### ISSUE TITLE
How to upgrade react-native-cli?

### ISSUE THREAD

**Issue by powerje** [facebook/react-native#392]
I mostly do native iOS work and am a bit confused by Node/npm!

I see on the [releases](https://github.com/facebook/react-native/releases) page a few new releases have come out since going public, but it looks like I'm on an older version:

````
$ npm list -g | grep react
├── react-native-cli@0.1.3
````

I tried following npm's instructions on [updating global packages](https://docs.npmjs.com/getting-started/updating-global-packages):
````
npm outdated -g
````

but `react-native-cli` was not on my list of outdated packages.

Is it just that the latest version (or any version after 0.1.3) isn't available on npm yet?

**Comment by powerje** [comment]
I think I just realized that react-native itself is different from react-native-cli.. I will see myself out.

**Comment by vjeux** [comment]
Global modules are really hard to get people to upgrade and cause conflicts when you have multiple projects. So we designed react-native-cli to do the bare minimum amount of things.

It knows about init and just creates a directory, npm install react-native and runs the init script from there.

All the other commands are forwarded to the currently installed react-native module. This way we can add/modify commands without changing the global cli :)

**Comment by powerje** [comment]
Ah I see, that makes sense! Thanks for the explanation :)

**Comment by vjeux** [comment]
@DandroidDeveloper 

```
npm uninstall -g react-native-cli
npm install -g react-native-cli
```

should do the trick

**Comment by vjeux** [comment]
If not, I'm not really sure what's going on and it's likely a bug with npm :( You can try [yarn](https://yarnpkg.com/) instead, maybe it'll fix it.

**Comment by DandroidDeveloper** [comment]
Same as before, it uninstalls and says I installed the correct version, but react-native -v ouputs 0.2.0, trying yarn now! Thanks! @vjeux

**Comment by vjeux** [comment]
One thing you can do is

```
which react-native
```

it's going to tell you where it is installed. Just rm that file/folder and run `npm install -g react-native-cli` again, it should hopefully fix it.

**Comment by DandroidDeveloper** [comment]
LOL, I switched my node path so I didn't get Eaccess errors when I install global packages and I just didnt add react native to my .bashrc file, my bad, thanks for your help, the which react-native command pointed that out! @vjeux
