### ISSUE TITLE
TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by PrinceSP** [facebook/react-native#39228]
### Description

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 10.15.7
  CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Memory: 33.98 MB / 8.00 GB
  Shell:
    version: 5.7.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/javascript/.gem/ruby/3.2.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 14.4
      - DriverKit 20.2
      - macOS 11.1
      - tvOS 14.3
      - watchOS 7.2
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 27.0.3
      - 28.0.2
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-29 | Intel x86 Atom_64
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 4.1 AI-201.8743.12.41.6953283
  Xcode:
    version: 12.4/12D4e
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.2.0
    path: /Users/javascript/.rubies/ruby-3.2.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Fix the ViewPropTypes problem or remove it if not useful anymore, so it won't get any error in the future.

### Snack, screenshot, or link to a repository

![simulator_screenshot_549D9F0F-9154-4147-A652-A8F0FC1ED261](https://github.com/facebook/react-native/assets/30646160/07869687-c508-4c3e-be53-a5ad0b42e026)

**Comment by freeboub** [comment]
cannot be investigated without code, but it looks llike you miss importing:

import PropTypes from 'prop-types'

**Comment by phanindraVarmaG** [comment]
> ### Description
> Invariant Violation: "main" has not been registered. This can happen if:
> 
> * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
> * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
> 
> ### React Native Version
> 0.72.4
> 
> ### Output of `npx react-native info`
> info Fetching system and libraries information... System: OS: macOS 10.15.7 CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz Memory: 33.98 MB / 8.00 GB Shell: version: 5.7.1 path: /bin/zsh Binaries: Node: version: 18.17.1 path: /usr/local/bin/node Yarn: Not Found npm: version: 9.8.1 path: /usr/local/bin/npm Watchman: Not Found Managers: CocoaPods: version: 1.12.1 path: /Users/javascript/.gem/ruby/3.2.0/bin/pod SDKs: iOS SDK: Platforms: - iOS 14.4 - DriverKit 20.2 - macOS 11.1 - tvOS 14.3 - watchOS 7.2 Android SDK: API Levels: - "29" - "30" - "31" - "33" Build Tools: - 27.0.3 - 28.0.2 - 28.0.3 - 29.0.2 - 30.0.2 - 30.0.3 - 31.0.0 - 33.0.0 System Images: - android-29 | Intel x86 Atom_64 - android-30 | Google APIs Intel x86 Atom - android-30 | Google Play Intel x86 Atom - android-30 | Google Play Intel x86 Atom_64 Android NDK: Not Found IDEs: Android Studio: 4.1 AI-201.8743.12.41.6953283 Xcode: version: 12.4/12D4e path: /usr/bin/xcodebuild Languages: Java: version: 11.0.10 path: /usr/bin/javac Ruby: version: 3.2.0 path: /Users/javascript/.rubies/ruby-3.2.0/bin/ruby npmPackages: "@react-native-community/cli": Not Found react: installed: 18.2.0 wanted: 18.2.0 react-native: installed: 0.72.4 wanted: 0.72.4 react-native-macos: Not Found npmGlobalPackages: "_react-native_": Not Found Android: hermesEnabled: Not found newArchEnabled: Not found iOS: hermesEnabled: Not found newArchEnabled: Not found
> 
> ### Steps to reproduce
> Fix the ViewPropTypes problem or remove it if not useful anymore, so it won't get any error in the future.
> 
> ### Snack, screenshot, or link to a repository
> ![simulator_screenshot_549D9F0F-9154-4147-A652-A8F0FC1ED261](https://user-images.githubusercontent.com/30646160/264536074-07869687-c508-4c3e-be53-a5ad0b42e026.png)

@PrinceSP did you find a solution for this ?

Even i  am having same issue
