### ISSUE TITLE
Border radius not respected when setting width in onLayout when nesting views

### ISSUE THREAD

**Issue by lindskogen** [facebook/react-native#3922]
Expected behavior is that both of the views have a border radius, but the inner view does not respect this property.

I have been able to reproduce it here: https://rnplay.org/apps/sqbFrQ
As you can see it only affects iOS, not Android.

**Comment by browniefed** [comment]
This appears to be fixed. Both views look like they have border radius working on IOS

**Comment by browniefed** [comment]
@facebook-github-bot answered
