### ISSUE TITLE
App Crashes 

### ISSUE THREAD

**Issue by asifbadeghar54** [facebook/react-native#39233]
### Description

App Crashes  at the time of  calling or call receiving  for other than samsung devices. its working properky in samsung devices other than samsung its crashes.

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Unknown

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'motorola/coful_g/coful:12/S3RWBS32.125-29-2-7/a319ee:user/release-keys'
Revision: 'PVT'
ABI: 'arm64'
Timestamp: 2023-08-31 12:16:36.030490819+0530
Process uptime: 0s
Cmdline: com.vimolive.vimo
pid: 4000, tid: 4326, name: mqt_native_modu  >>> com.vimolive.vimo <<<
uid: 10581
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76657b9100
    x0  0000007666cd7fc0  x1  0000007666cd72d8  x2  0000000000000001  x3  00000076658a6960
    x4  0000007666cd7fc0  x5  00000075ebdbdcc4  x6  fefeff1f5a749b0a  x7  7f7f7f7f7f7fff7f
    x8  00000076657b9100  x9  0000000000000003  x10 0000000000004001  x11 0000000000000000
    x12 0000000000000000  x13 0000000000000001  x14 ffffffffffffffff  x15 0000000000000001
    x16 00000075e619e368  x17 000000771e352240  x18 00000075b2c0e000  x19 0000007666cd72d8
    x20 0000007666cd7fc0  x21 0000007666cde000  x22 0000000000000001  x23 0000007666cd7fc0
    x24 0000000000000000  x25 0000007666cd8618  x26 0000007666cde000  x27 0000000000000001
    x28 00000075e5f598ac  x29 0000007666cd72b0
    lr  00000075ebdc223c  sp  0000007666cd72b0  pc  00000076657b9100  pst 0000000000001000
backtrace:
      #00 pc 00000000000b3100  [anon:libc_malloc]
      #01 pc 00000000000e8238  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
      #02 pc 00000000000e7e6c  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
      #03 pc 00000000000e3f50  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!libc++_shared.so (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
      #04 pc 00000000000e3da4  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!libc++_shared.so (__gxx_personality_v0+224) (BuildId: fcc246cbb373c5edee634b117c4b4564cc9becf3)
      #05 pc 0000000000c6be5c  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #06 pc 0000000000c6c364  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #07 pc 00000000009b1c34  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (lime::Db::load_LimeUser(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, long&, lime::CurveId&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >&, bool)+1428) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #08 pc 0000000000982450  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (lime::load_LimeUser(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::function<void (std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char> > const&, std::__ndk1::function<void (int, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char> > const&)> const&)> const&, std::__ndk1::shared_ptr<std::__ndk1::recursive_mutex>, bool)+232) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #09 pc 0000000000978e58  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (lime::LimeManager::load_user(std::__ndk1::shared_ptr<lime::LimeGeneric>&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool)+232) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #10 pc 000000000097a58c  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (lime::LimeManager::get_selfIdentityKey(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char> >&)+36) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #11 pc 0000000000892140  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (LinphonePrivate::LimeX3dhEncryptionEngine::getEncryptionParameters()+204) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #12 pc 00000000006d489c  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (LinphonePrivate::MediaSessionPrivate::setupImEncryptionEngineParameters(std::__ndk1::shared_ptr<LinphonePrivate::SalMediaDescription>&)+128) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #13 pc 00000000006c9300  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (LinphonePrivate::MediaSessionPrivate::makeLocalMediaDescription(bool, bool, bool, bool)+5440) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #14 pc 00000000006dd6b8  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (LinphonePrivate::MediaSession::configure(_LinphoneCallDir, _LinphoneProxyConfig*, LinphonePrivate::SalCallOp*, LinphonePrivate::Address const&, LinphonePrivate::Address const&)+940) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #15 pc 0000000000644a24  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (LinphonePrivate::Call::Call(std::__ndk1::shared_ptr<LinphonePrivate::Core>, _LinphoneCallDir, LinphonePrivate::Address const&, LinphonePrivate::Address const&, _LinphoneProxyConfig*, LinphonePrivate::SalCallOp*, LinphonePrivate::MediaSessionParams const*)+704) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #16 pc 000000000060fe20  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (linphone_call_new_outgoing+200) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #17 pc 00000000008ba850  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (linphone_core_invite_address_with_params_2+580) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #18 pc 000000000094bcb8  /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!liblinphone.so (Java_org_linphone_core_CoreImpl_inviteAddressWithParams+260) (BuildId: c7fe9aa0a93e40e5ad42062c0a038ab2174a1dff)
      #19 pc 0000000000377030  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #20 pc 00000000003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #21 pc 00000000004906b4  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+1248) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #22 pc 000000000050a5d4  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+2380) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #23 pc 00000000003797d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #24 pc 000000000019ac3c  [anon:dalvik-classes11.dex extracted in memory from /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!classes11.dex] (org.linphone.core.CoreImpl.inviteAddressWithParams+0)
      #25 pc 000000000037cde0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.1377403774332988508)+356) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #26 pc 000000000049120c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4152) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #27 pc 000000000050aca4  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+4124) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #28 pc 00000000003797d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #29 pc 00000000000a70c0  [anon:dalvik-classes2.dex extracted in memory from /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!classes2.dex] (com.vimo.sipmno.SipManager.makeCall+0)
      #30 pc 000000000037cde0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.1377403774332988508)+356) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #31 pc 000000000049120c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, bool, art::JValue*)+4152) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #32 pc 0000000000509f94  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>(art::interpreter::SwitchImplContext*)+780) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #33 pc 00000000003797d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #34 pc 0000000000001b34  [anon:dalvik-classes6.dex extracted in memory from /data/app/~~OIQQFY6LAYJ8KU9n2OCUjw==/com.vimolive.vimo-7LShc9xZT2l_2AAo_nKWtA==/base.apk!classes6.dex] (bridge.sip.SIPModule.establishCall+0)
      #35 pc 000000000037cde0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.__uniq.112435418011751916792819755956732575238.llvm.1377403774332988508)+356) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #36 pc 000000000037c560  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+672) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #37 pc 0000000000377168  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #38 pc 00000000003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #39 pc 000000000026bad0  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+5336) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #40 pc 000000000026a5e8  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #41 pc 0000000000377030  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: b10f5696fea1b32039b162aef3850ed3)
      #42 pc 0000000002012558  /memfd:jit-cache (deleted)

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.0.1
  CPU: (8) arm64 Apple M1
  Memory: 153.70 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 19.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2022.12.05.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

https://github.com/facebook/react-native/assets/39403588/4c8aa33b-a381-467b-a6a3-93dc0b1f3aa8

### Snack, screenshot, or link to a repository

iam using linphone library for call at the time of call Build fingerprint: 'motorola/coful_g/coful:12/S3RWBS32.125-29-2-7/a319ee:user/release-keys'
Revision: 'PVT'
ABI: 'arm64'
Timestamp: 2023-08-31 12:16:36.030490819+0530
Process uptime: 0s
Cmdline: com.vimolive.vimo
pid: 4000, tid: 4326, name: mqt_native_modu  >>> com.vimolive.vimo <<<
uid: 10581
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76657b9100

**Comment by freeboub** [comment]
Your side package liblinphone is crashing in native library, not react native

**Comment by NickGerleman** [comment]
As above, the crashing module is not React Native. The issue is somewhere in the chain of calling liblinphone or inside of it.

Unsynbolicated stack traces without repro are not useful for finding a root issue (are you running a release build maybe?), but if you are able to get a repro, and this is internal to the library instead of calling it incorrectly, the projects Github repo might be a good plVe to start. 

https://github.com/BelledonneCommunications/liblinphone
