### ISSUE TITLE
I was having the same issue in expo app the problem was react navigation and maps downgraded both versions and it worked

### ISSUE THREAD

**Issue by Pau1fitz** [facebook/react-native#39245]
> I was having the same issue in expo app the problem was react navigation and maps downgraded both versions and it worked

_Originally posted by @zainulabdeen5 in https://github.com/facebook/react-native/issues/36084#issuecomment-1422652692_
            
@zainulabdeen5 can you explain what versions you ended up downgrading to, and what versions of react native and expo you are using?

**Comment by cortinico** [comment]
@Pau1fitz Closing as you should reach out directly to the other GitHub user.
