### ISSUE TITLE
Apps crashing while taking picture in some phone

### ISSUE THREAD

**Issue by minhaz19** [facebook/react-native#39257]
### Description

The issue is that the app crashes and restarts from the splash screen when taking an image. This problem doesn't occur on all phones; it's specific to some models like the SM-A105F with API level 30, and a few others. Most phones don't experience this issue. Initially, I suspected it might be related to the package I was using, so I tried both "react-native-image-crop-picker" and "react-native-image-crop-picker," but the same problem persisted.

What could be causing this problem, and how can I resolve it?

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 69.03 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/hawk_eyes/nagad-TMR-app/node_modules/.bin/npm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Try to take the image with Samsung Galaxy A10(SM-A105F)(API level -30) and at some point image will not save and restart the app from the splash screen.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@minhaz19/image-picker-hook

**Comment by cortinico** [comment]
> Most phones don't experience this issue. Initially, I suspected it might be related to the package I was using, so I tried both "react-native-image-crop-picker" and "react-native-image-crop-picker," but the same problem persisted.

You should open this issue on those libraries issue tracker rather than here, as they can support you further.
