### ISSUE TITLE
Security Issues About Binary Packages

### ISSUE THREAD

**Issue by beibeiGeng** [facebook/react-native#39252]
### Description

In the 0.68.7 version, stack protection is not enabled for some compiled binary files (such as libbutter.so) in the react-native binary package. Is there any risk in the use of common commercial services?
Can the official avoid or fix these compiler security files, open their stack protection mechanism?

### React Native Version

0.68.7

### Output of `npx react-native info`

null

### Steps to reproduce

In this version, stack protection is not enabled for some files after the compilation files are scanned.

### Snack, code example, screenshot, or link to a repository

null

**Comment by NickGerleman** [comment]
NDK should set flags for this, but these weren't getting propagated. Context in https://github.com/facebook/react-native/pull/38018

I think this left off with wanting to investigate why these aren't being set. @cortinico might make sense to kick the tires on this again now that we did NDK bump.

To set expectations, this would target RN 0.73.
