### ISSUE TITLE
[IOS] [Navigator] Using different navbars for each Route

### ISSUE THREAD

**Issue by josev55** [facebook/react-native#3926]
Hi,
Im trying to implement Navigator for the top navigation and im dealing with some views where i need a button on the right item of the nav bar. I don't want to create different navigators whenever i need to change the layout of the nav bar.

Is there anyway to achieve that with the passed navigator object? Can I just change the nav bar of the navigator object?
@ericvicenti sorry that i tag you but i saw you helped another user with an issue regarding Navigator component.

Thanks in advance.

**Comment by ericvicenti** [comment]
Navigation bars are fixed to the navigator. You could make a custom navbar that knows how to transition between two modes based on the routes that you use. If you just need to change the button, you can set up the `RightButton` function in your NavigationBar routeMapper

**Comment by gre** [comment]
**This is a pretty common use-case** (having a button contextual to a screen) and **I wish RN Navigator would bring some solution for this**.

one way to fix it is with Flux pattern (you can track the route state and based on that change navigation content). It forces you to put all your states in stores (which is not a so bad idea anyway but that might not be your architecture). The problem with Flux approach to solve this problem to me is that you will have to maintain logic both in Nav and Screen places.. and I think it's preferable to keep the screen render() along with the button render().

The way i've fixed this in my project is not perfect but works. Here is a summary: App have a state that holds the **vdom** of the nav right content. each screen receives a `setNavRightContent` function that can be called to set that `vdom` state. To have a less imperative style to this, I define a renderNavBar method and always call `setNavRightContent(this.renderNavBar(nextProps, state))` in `componentWillReceiveProps`.
This is a pretty hacky setup and I wish I can find something better but this solve my need to have screen render() logic with the button render() logic.
I think a better solution would be to have a concept of "Screen". I would like to be able to do this: `<Screen> <Nav>...</Nav> <Body>...<Body> </Screen>` in render() function of each "screen" with Nav being an opportunity to dynamically set the nav content.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-navigator-using-different-navbars-for-each-route

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
