### ISSUE TITLE
FlatList/ScrollView Container Border Radius doesn't work on Android

### ISSUE THREAD

**Issue by PaulLampe** [facebook/react-native#39270]
### Description

Using a FlatList with horizontal scrolling and a border radius applied to the content container (with and without overflow:'hidden') works fine in web and on iOS but the borderRadius is not applied on Android. (See Screenshots)

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 12.6.1
  CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
  Memory: 52.89 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: Dolphin 2021.3.1 Patch 1 Dolphin 2021.3.1 Patch 1
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Use FlatList in horizontal mode and set BorderRadius and BackgroundColor in contentContainerStyle.

### Snack, screenshot, or link to a repository

Snack: https://snack.expo.dev/@paullampe/flatlist-container-borderradius-not-working

<img width="332" alt="Bildschirmfoto 2023-09-02 um 20 51 20" src="https://github.com/facebook/react-native/assets/25662007/3f478519-f637-451c-8982-c3951843c734">
<img width="334" alt="Bildschirmfoto 2023-09-02 um 20 51 12" src="https://github.com/facebook/react-native/assets/25662007/ea997b2a-f734-4e76-bab3-7538d159cbb0">
<img width="330" alt="Bildschirmfoto 2023-09-02 um 20 50 54" src="https://github.com/facebook/react-native/assets/25662007/d5d2cdf1-42f6-4d4b-9df5-748f7f874c69">

**Comment by cortinico** [comment]
Duplicates #30550

**Comment by bogdanovic91** [comment]
why is this issue closed? it is still a problem

**Comment by abdulragib** [comment]
i am getting same issue , it work fine in ios but not working in android
