### ISSUE TITLE
onpress event locationX and locationY incorrect on repeated presses

### ISSUE THREAD

**Issue by dannyhw** [facebook/react-native#39282]
### Description

When using onPress or any other press event on Pressable or any other touchable/pressable if I try to use event.nativeEvent.locationX to drive some animation or other behaviour I get the wrong values. On repeated presses the value will revert to what seems to be an initial value instead of its actual position and then swap between this and the true value repeatedly. See the video, note that my cursor remains in the same position for long periods whilst the red circle moves erratically. Also when pressing the inner text the offset is not relative to the text instead of the pressable.

video is from the repro
https://github.com/dannyhw/pressable-repro

https://github.com/facebook/react-native/assets/3481514/0fd7ee70-b64f-49ee-a3aa-eec3ba30e424

### React Native Version

0.72.4

### Output of `npx react-native info`

```
System:
  OS: macOS 13.5.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 77.03 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/Library/pnpm/node
  Yarn:
    version: 1.22.19
    path: ~/Library/pnpm/yarn
  npm:
    version: 9.7.2
    path: ~/Library/pnpm/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/danielwilliams/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/danielwilliams/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- add an onPress and log the result of event.nativeEvent.locationX
- press multiple times in the same location
- note that the value does not remain the same

### Snack, screenshot, or link to a repository

https://github.com/dannyhw/pressable-repro

**Comment by dhruvpvx** [comment]
set prop 
`pointerEvents="none"`
to the red dot View

**Comment by dannyhw** [comment]
@dhruvpvx oh wow, can't believe it was that simple... thanks!
