### ISSUE TITLE
[Android] No support for handling exceptions

### ISSUE THREAD

**Issue by Iverum** [facebook/react-native#3928]
On iOS a delegate can be assigned to the RCTExceptionManager to catch exceptions and provide some custom handling for them. However, on Android it appears that this functionality is missing.

Am I missing the way to do this on Android or is it just not there?

**Comment by mkonicek** [comment]
I believe Sentry has support for React Native Android so this should be possible?

cc @foghina

**Comment by mkonicek** [comment]
Try reading the codebase.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
