### ISSUE TITLE
Unable to use ReadonlyArray for Direct Events

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [facebook/react-native#39283]
### Description

I have event to trigger from native containing array, but I don't see a workaround to use arrays in the events. Tried using ReadonlyArray but it does not work, just fails on codegen. ReadonlyArray works fine with props, don't know why I does not work with events. Please share the working example if we can use ReadonlyArray for events.

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (12) arm64 Apple M2 Pro
  Memory: 2.93 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ravindragupta/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.0.4
    path: /Users/ravindragupta/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: true

### Steps to reproduce

Try to add ReadonlyArray in the object for direct event
It won't compile by codegen.

### Snack, code example, screenshot, or link to a repository

<img width="931" alt="Screenshot 2023-09-05 at 10 10 17 AM" src="https://github.com/facebook/react-native/assets/97147467/1e4006a2-fe51-45bb-9008-57fbdca7c020">

Error Screenshot:
<img width="1131" alt="Screenshot 2023-09-05 at 11 06 03 AM" src="https://github.com/facebook/react-native/assets/97147467/30165fe7-1068-4d74-b694-22118e8217c6">

**Comment by ravindraguptacapgemini** [comment]
I can't provide reproducer, Already provided the code snippet @cipolleschi

**Comment by cipolleschi** [comment]
This feature will be released in 0.73. Branch cut ETA is for end of the month, so stay tuned.
