### ISSUE TITLE
[Packager] Source Maps are not supported in custom transformer (typescript in this case)

### ISSUE THREAD

**Issue by svdoever** [facebook/react-native#393]
React Native seems to fall over sourcemaps. I compile TypeScript modules with:

tsc --module commonjs --sourcemap MyClass.ts

If I don't include --sourcemap option it works...

**Comment by amasad** [comment]
Can you add more information about how you're using typescript? Do you compile your typescript to JS and then have the packager pick them up?
If so can you paste the generated bundle somewhere and link it here?

**Comment by svdoever** [comment]
Hi @amasad, I created a project as follows:

    react-native init ReactNativeTypescriptSourcemapIssue

Then I go into the folder:

    cd ReactNativeTypescriptSourcemapIssue

Now create a simple typescript file *TestClass.ts* that can be compiled as a commonjs module:

    class TestClass {
      doit(): string {
        return "Hello world!";
      }
    }
    export=TestClass

Now compile this file as follows, without sourcemap information:

    tsc --module commonjs TestClass.ts

This results in a JavaScript file *TestClass.js*:

    var TestClass = (function () {
        function TestClass() {
        }
        TestClass.prototype.doit = function () {
            return "Hello world!";
        };
        return TestClass;
    })();
    module.exports = TestClass;

Reference this file in *index.io.js*:

  /**
     * Sample React Native App
     * https://github.com/facebook/react-native
     */
    'use strict';

    var React = require('react-native');
    var TestClass = require("./TestClass"); // Require

    var {
      AppRegistry,
      StyleSheet,
      Text,
      View,
    } = React;

    var ReactNativeTypescriptSourcemapIssue = React.createClass({
      render: function() {
        var testClass = new TestClass(); // Usage
        return (
          <View style={styles.container}>
            <Text style={styles.welcome}>
              Welcome to React Native and say: {testClass.doit()}
            </Text>
            <Text style={styles.instructions}>
              To get started, edit index.ios.js{'\n'}
              Press Cmd+R to reload
            </Text>
          </View>
        );
      }
    });

    var styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
      },
      welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
      },
      instructions: {
        textAlign: 'center',
        color: '#333333',
      },
    });

    AppRegistry.registerComponent('ReactNativeTypescriptSourcemapIssue', () => ReactNativeTypescriptSourcemapIssue);

This results into a working app:

![screen shot 2015-03-30 at 22 08 03](https://cloud.githubusercontent.com/assets/246842/6905632/a9df0c06-d729-11e4-9b77-88a84f3672b5.png)

Now compile the TypeScript file with sourcemap information:

    tsc --module commonjs --sourcemap TestClass.ts

This results in a JavaScript file *TestClass.js*:

    var TestClass = (function () {
        function TestClass() {
        }
        TestClass.prototype.doit = function () {
            return "Hello world!";
        };
        return TestClass;
    })();
    module.exports = TestClass;
    //# sourceMappingURL=TestClass.js.map

The result is an app with the following error:

![screen shot 2015-03-30 at 22 10 14](https://cloud.githubusercontent.com/assets/246842/6905683/11536d14-d72a-11e4-8102-830e7af609fa.png)

Where can I find the generated bundle?

**Comment by frantic** [comment]
> Where can I find the generated bundle?

http://localhost:8081/index.ios.bundle

**Comment by frantic** [comment]
I don't think we support source maps from external generators yet

**Comment by svdoever** [comment]
I don't think so too:-) No problem, I can live without it (for now). Is there a way to include generators like TypeScript or CoffeeScrip into the auto-build process, or is this something that should be handled by custom build scripts (grunt, gulp), or the often built-in watch commands of the compilers (tsc -watch ...)?

**Comment by frantic** [comment]
I'll defer the answer to @amasad, but I think we want to have a way to plug in custom transformers in the future.

**Comment by amasad** [comment]
Yes, we're already half way there, we just need to be abel to use source maps from those transformers as well. As for grunt/gulp etc. We want to make sure you are able to use your own build scripts, but for us to do that there is some work needs to be done in React and in our internal codebases so that's still some time away.

**Comment by svdoever** [comment]
Good news, timing is no problem, it all works if we don't use sourcemap with TypeScript. TypeScript is easy enough to read in compiled form. Good luck with all the work!

**Comment by amasad** [comment]
Thanks, I'll keep this open as a task to support consuming source maps from the transformer.

**Comment by amasad** [comment]
This is now fixed, if you return a `.map` property from your transformer the packager will use it and combine it with other sourcemaps. See:
https://github.com/facebook/react-native/blob/8b93b99d4a769f86fffc95d65434f2f6a3fd827d/packager/react-packager/src/Packager/Package.js#L37-L41

**Comment by Thegaram** [comment]
I'd also like to use Typescript for React Native (with sourcemaps). As far as I understand, the solution recommended by @amasad is to create a new transformer that returns a `map` property and pass it to the packager. Is there a way to use sourcemaps generated prior to starting the packager?

@svdoever Could you please share the solution you ended up using?

**Comment by qimingweng** [comment]
@amasad How do we make sure we pass the .map property? I'm not sure which interface this is talking about.

**Comment by scttnlsn** [comment]
Should the `map` property be the source map filename or the contents of the source map?

**Comment by scttnlsn** [comment]
@qimingweng Not entirely sure but I'm experimenting with the following approach:

```js
var transformer = require('react-native/packager-transformer');

module.exports = function (data, callback) {
  if (/* data.filename needs source map */) {
    callback({
      code: data.sourceCode,
      map: data.filename + '.map' // not sure if this is right
    });
  } else {
    transformer(data, callback);
  }
};
```

**Comment by amasad** [comment]
Map property should be the sourcemap itself

**Comment by hfutrell** [comment]
@amasad I am working with Typescript and have found some success with a custom transformer based on work in the [boot-react-native](https://github.com/mjmeintjes/boot-react-native/issues/23) project. But I've encountered a few problems. The first, which they also ran into, is that once you return the `.map` property for a module, RN starts to expect that property for all modules. It is not clear to me what the custom transformer should return for the `map` property when no source map is available. But if it returns nothing then Google Chrome will error parsing the source maps. The second issue is that built-in transformer calls into babel and uses the source map generated by babel. If we do not call the built-in transformer from our custom transformer, this babel transformation step is skipped. But if we do call the built-in transformer then its not clear to me how to compose our own source maps with the ones generated by babel. If we pass in our own source maps the line numbers may be slightly off.  

`
const fs = require('fs');
const transformer = require('react-native/packager/transformer');

module.exports = function (data, callback) {
    if (data.sourceCode && data.filename.indexOf('index.ios.js') > -1) {
			fs.readFile('index.ios.js.map', function (err, map) {
					var sourceMap = JSON.parse(map.toString());
					sourceMap.sourceRoot = './';
					sourceMap.moduleName = ['index.ios.tsx']
					var results = {	code: data.sourceCode, map: sourceMap };
					callback(null, results);
	    });
    } else {
        var cb = function(err, mod) {
            // callback wrapping needed or Google Chrome will fail to parse source maps
            mod.map = getBasicSourceMap(data.filename, mod.code);
            return callback(err,  mod);
        };
        transformer(data, cb);
    }
};
`

**Comment by frogcjn** [comment]
@hfutrell 

This is[ my solution](https://gist.github.com/frogcjn/fb33fd721e0186cc70ab47994f5c77dc) based on `vscode-node-debug` and `boot-react-native`

Also refer to this issue
https://github.com/Microsoft/vscode-react-native/issues/240

**Comment by frogcjn** [comment]
Here is my post to explain how to debug ReactNative project in VSCode with typescript:
[make_VSCode_debug_RN_TS.md](https://gist.github.com/frogcjn/3bb47ce01a5168d8cd570a46cc71bb02)

**Comment by mhzed** [comment]
Take a look at this:

https://github.com/mhzed/react-native-sm-transformer

**Comment by webzepter** [comment]
@frogcjn could you please provide instructions for non-VSCode environment?

**Comment by frogcjn** [comment]
You can just skip the steps on Problem 3. https://gist.github.com/frogcjn/3bb47ce01a5168d8cd570a46cc71bb02

**Comment by alloy** [comment]
Here’s a custom transformer that sets up a pipeline that does TypeScript -> JS -> Babel transformation and all the source-map mangling required: https://github.com/artsy/emission/compare/93ab096089c3d07040511e070cb0585e66cccec2...5c6728b7058eac6a8fbd4353cd98e9f91a58ff99

**Comment by olegdizus** [comment]
Hi, @alloy! Can you explain how to use this solution?

**Comment by alloy** [comment]
* Start the packager and point it to a custom config like so https://github.com/artsy/emission/blob/185d9610832b9698de525a5a89178473464406ba/package.json#L15
* Have a custom config file that points to the custom transformer like so https://github.com/artsy/emission/blob/185d9610832b9698de525a5a89178473464406ba/rn-cli.config.js
* And place the transformer files in the path pointed to from the custom config file https://github.com/artsy/emission/tree/185d9610832b9698de525a5a89178473464406ba/transformer

**Comment by olegdizus** [comment]
Thanks! I'll try it later.

**Comment by alloy** [comment]
@olegdizus Oh btw, you also need the RN patch that’s applied to 0.42 in my fork https://github.com/alloy/react-native/tree/v0.42.0-with-customisable-source-exts. We’re in the process of making it all work with 0.43.rc1, some things have changed.

**Comment by olegdizus** [comment]
@alloy, okay. Do you added a PR to react-native repo? I want to vote for =)

**Comment by jmfirth** [comment]
@olegdizus https://github.com/facebook/react-native/pull/11932
