### ISSUE TITLE
Rctnetworking  is not defined in react native 0.72

### ISSUE THREAD

**Issue by martsa** [facebook/react-native#39309]
### Description

i am using RCTNetworking.clearcookies to clear cookies. it was working till react native 0.71 but due to dependecy issue i have updated to 72 and in error it was mentioned that its undefined. 

### React Native Version

react native 49

### Output of `npx react-native info`

System:
  OS: macOS 13.2.1
  CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Memory: 175.28 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.6.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 2.15.12
    path: ~/ReactNative/backup/ParrotProjectv2/node_modules/.bin/npm
  Watchman:
    version: 2023.08.28.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 21.0.6113669
IDEs:
  Android Studio: 4.1 AI-201.8743.12.41.7042882
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 13.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

### Steps to reproduce

 const RCTNetworking = require('react-native/Libraries/Network/RCTNetworking');
    RCTNetworking.clearCookies((result) => {
      console.log(result); //true if successfully cleared
    });

### Snack, screenshot, or link to a repository
 ERROR  TypeError: RCTNetworking.clearCookies is not a function (it is undefined)

my main idea of using Rctnetworking is to clear http cookies from axios and fetch  before every authentification process starts. Otherwise it takes old authentication username and password values and never accepted new value. Some how with update of reactnative 49.. Rctnetworking looks undefined and i cannot clear cookies

**Comment by cortinico** [comment]
Could you provide a repro?

**Comment by ellouzeskandercs** [comment]
I see that there were a [change in the RCTNetworking to use ESM exports instead of CJS exports](https://github.com/facebook/react-native/commit/b6064495f5d49a70ef075f72dba9be374829c290). So as a quick fix, you can add a `.default` at the end of your require statement `const RCTNetworking = require('reactnative/Libraries/Network/RCTNetworking').default;`
