### ISSUE TITLE
[ActionSheetIOS] Documentation

### ISSUE THREAD

**Issue by rileybracken** [facebook/react-native#3931]
According to the documentation `ActionSheetIOS` takes options: 
`static showActionSheetWithOptions(options: Object, callback: Function) `

But in the example it gives the only option of URL:
```
    ActionSheetIOS.showShareActionSheetWithOptions({
      url: 'https://code.facebook.com',
    },
```
What are the other options (if any)? I could see it being super useful to have things like `text` and `imageUrl`.

**Comment by brentvatne** [comment]
UIExplorer has more options listed: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ActionSheetIOSExample.js

The objc source also has a full list: https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L52-L143

Would be good to have some documentation around the options for sure though! A PR would be very welcome for this :) I'm going to close this for now but feel free to dm me on Twitter if you have more questions and looking forward to a pr ;)

**Comment by davodesign84** [comment]
So there is no way to set up a thumbnail?
