### ISSUE TITLE
What's the recommended way to make image processing ?

### ISSUE THREAD

**Issue by CallMeSH** [facebook/react-native#3932]
Hi everyone !
I'm working on a React Native project and I wanted to process images downloaded from the network to obtain the vibrancy colors and improve the UI. [More infos in Google's Doc](https://developer.android.com/reference/android/support/v7/graphics/Palette.html)
Unfortunately I could not find any informations on how to extract the downloaded Image buffer or local temporary file path of the Image component.

I could write a completely new component but I would loose the whole implementation of the Image component which could create side effects.

An other solution would be to download the image as a Node.JS buffer, make the analyse happen and then insert back the buffer inside the Image component. But other issues point that as a very bad solution for performances.

Anyone has a better idea ? 
Thanks !

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow
