### ISSUE TITLE
react-native IOS fontFamily does not take effect for custom fonts

### ISSUE THREAD

**Issue by vksgautam1986** [facebook/react-native#39321]
### Description

Custom Font family is not working for ios , working fine for android

I have downloaded few ttf and otf fonts and placed it.
"assets/fonts"

Then i created react-native.config.js 
`module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./App/assets/fonts'],
};`
![Screenshot 2023-09-07 at 3 43 32 PM](https://github.com/facebook/react-native/assets/133006606/bf1f0a16-44b0-4df6-a00c-ff3a9e48e656)

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 119.97 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.5.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/netsmartz/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.1
      - iOS 16.1
      - macOS 13.0
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 14.1/14B47
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/netsmartz/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Get the font file needed for your project
Create a configuration file react-native.config.js in the root project directory and add the code below:
`module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts'],
};`

run this command
npx react-native-asset 

### Snack, screenshot, or link to a repository

![Screenshot 2023-09-07 at 3 43 32 PM](https://github.com/facebook/react-native/assets/133006606/ca935a99-7c1b-4d66-9b5f-0a4be558ea04)
![Screenshot 2023-09-07 at 3 26 57 PM](https://github.com/facebook/react-native/assets/133006606/9dc1b9f8-24e6-4ff9-aca4-d9a441a04b46)

**Comment by emmbyiringiro** [comment]
Specific for iOS. It's required to use **PostScript** Font Family Name not font file name style definition.
![font-info](https://github.com/facebook/react-native/assets/46843540/2db17fe2-cacd-4570-87e2-b41e9bd51391)

**Comment by vksgautam1986** [comment]
Hi , i am using this highlighted one.
![Screenshot 2023-09-08 at 11 17 20 AM](https://github.com/facebook/react-native/assets/133006606/00b0b5ea-feb2-4a84-bf47-207993e0930d)

**Comment by emmbyiringiro** [comment]
You are using a font file name which is not a PostScript name. Use Apple Font Book app, not Finder.

**Comment by vksgautam1986** [comment]
thanks its working fine now. i missed this one

**Comment by fkazemi5236** [comment]
this link is explains that what is the postScript name of the font in mac

https://apple.stackexchange.com/a/79889

**Comment by AdityaSinghXenelsoft** [comment]
@vksgautam1986 , Can you guide me how to use Custom font .I am using .ttf fonts that is working fine.But,otf fonts are not working
![Screenshot 2024-06-12 125028](https://github.com/facebook/react-native/assets/160213931/7ac0ee8b-3ad0-4f5a-90a4-abe630c1e8df)

**Comment by whoisyurii** [comment]
@emmbyiringiro thank for PostScript naming hint, gentleman
