### ISSUE TITLE
Borders overlap on android resulting into black squares

### ISSUE THREAD

**Issue by Renszit** [facebook/react-native#39323]
### Description

Noticed on android that the corners of the borders seem to result in black corners when using an opacity lighter than 1.

When using explicit color for each border and omitting one it does work and the black corners do not show up.

Please see snack for an example. 

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 50.33 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

- create new project
- add overlay with borders
- give borders a lighter opacity
- open on android

### Snack, screenshot, or link to a repository

https://snack.expo.dev/0pjlerGtI?platform=android

**Comment by cortinico** [comment]
Can you also share a screenshot?

**Comment by Renszit** [comment]
<img width="329" alt="image" src="https://github.com/facebook/react-native/assets/70590294/74e58786-0163-4224-9737-87a0341aec17">

**Comment by manuel-grondona** [comment]
Same issue here, borders seem to be overlapping and when `opacity` less than 1 is set, you can see darker spots because of this issue
