### ISSUE TITLE
[Animated] [Web] Animation Memory Leak

### ISSUE THREAD

**Issue by Big-Cheung** [facebook/react-native#39332]
### Description

There is a memory leak on Web on the newest version of react-native. When starting a new animation, the previous Animated.Value is not unallocated.

This memory leak was not present in version 0.71.8, which was my previous React Native version before updating to Expo 49.
Because of this, the snack attached below does not have a memory leak present, as it is running using Expo 48, which does not support React native 0.72.4

Below is a screenshot of the memory snapshots from the attached snack code ran on my local system. Snapshot 4 was taken at 0 resets, and Snapshot 5 was taken at 100 resets. The difference between the two is 100 new AnimatedValue allocations, 200 AnimatedProps allocations, 200 AnimatedStyle allocations, and 400 AnimatedInterpolation allocations.

Please view the Snack below for the source code.

![image](https://github.com/facebook/react-native/assets/27376894/6dde204c-63a3-4b8c-a4e7-7cbe8243d01e)

The most likely candidates to introduce these are :
b589123, dccb57f, c06323f
which were all found in the changelog between 0.71.8 and 0.72.4 

Let me know if you need any more information.

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  Memory: 5.45 GB / 15.95 GB
Binaries:
  Node:
    version: 18.16.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.10121639
  Visual Studio:
    - 16.11.32602.291 (Visual Studio Community 2019)
Languages:
  Java:
    version: 17.0.7
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Create any animated value.

Create an animation and start it.
Create another animation and start it.

The associated AnimatedValue objects should remain in memory without being cleared until the component containing them is unrendered.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@bigcheung/suspicious-tortillas

**Comment by cortinico** [comment]
> There is a memory leak on Web on the newest version of react-native. When starting a new animation, the previous Animated.Value is not unallocated.

Why do you mention "Web" specifically here? Is this not an issue on Android or iOS?

**Comment by Big-Cheung** [comment]
> > There is a memory leak on Web on the newest version of react-native. When starting a new animation, the previous Animated.Value is not unallocated.
> 
> Why do you mention "Web" specifically here? Is this not an issue on Android or iOS?

Was unable to test on Android or iOS at the time. Can only confirm that this issue is present on web.

**Comment by cortinico** [comment]
Can we test on Android & iOS before we can proceed with further triaging here?

**Comment by kholland950** [comment]
+1

We seem to be having this identical issue when upgrading from Expo 49 -> 51 and React Native 71 -> 74

@Big-Cheung Did you ever identify a cause?
