### ISSUE TITLE
KeyboardAvoidingView with behavior set to height is a bit too tall only the first time on iOS

### ISSUE THREAD

**Issue by GNUGradyn** [facebook/react-native#39331]
### Description

When using the KeybaordAvoidingView with the behavior set to height on iOS, the first time the keyboard is invoked, the view is a bit too tall and cut off slightly. If the keyboard is invoked a second time, it is fine. Android appears immune to the issue

The first video is of the MRE linked below, the second is of an app I am working on that shows the issue a bit better.

https://github.com/facebook/react-native/assets/20762604/3f9208bc-2668-4416-9098-db64a3401fd8

https://github.com/facebook/react-native/assets/20762604/9678540e-117b-4a68-acf1-43d938080598

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5.1
  CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
  Memory: 23.72 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      
DriverKit 22.4
iOS 16.4
macOS 13.3
tvOS 16.4
watchOS 9.4
Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "react-native": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. Create a KeyboardAvoidingView that has a height of 100% and a behavior of height. Put something at the bottom (like a border for example) so you can tell if it's cut off
2. Put something in the KeyboardAvoidingView to allow invoking the keyboard (like a TextInput)
3. Run the app on iOS
4. Invoke the keyboard

Notice the bottom of your KeyboardAvoidingView is cut off. This is not supposed to happen

5. Collapse and invoke the keyboard again

Notice the bottom of the KeyboardAvoidingView is still visible. This is how it should be 

### Snack, screenshot, or link to a repository

https://github.com/GNUGradyn/KeyboardAvoidingViewMre

**Comment by olegmilan** [comment]
I'm facing the same issue after upgrading to 0.72.8
