### ISSUE TITLE
[PushNotificationIOS] Support Local Notifications in Simulator

### ISSUE THREAD

**Issue by jhabdas** [facebook/react-native#3933]
Local notifications support was added in https://github.com/facebook/react-native/pull/1616. Unlike remote notifications, local notifications will indeed work in the iOS simulator under Xcode 7 and iOS 9. However, the `PushNotificationIOS` lib uses some branching logic based on iOS version and, therefore, prevents local notifications from working as they could.

For example, in `RCTPushNotificationManager.m`, if the first condition in the below code block isn't bypassed in the simulator you will rewarded you with a dialog requesting permissions:

```obj-c
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0

  id notificationSettings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
  [[UIApplication sharedApplication] registerUserNotificationSettings:notificationSettings];
  [[UIApplication sharedApplication] registerForRemoteNotifications];

#else

  [[UIApplication sharedApplication] registerForRemoteNotificationTypes:types];

#endif
```

The simulator also allows scheduling and handling of local notifications, but not under the current native module construction. Perhaps there's a way to coax the simulator into reporting itself as an iPhone as a workaround.

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix

**Comment by mkonicek** [comment]
@facebook-github-bot bugfix
