### ISSUE TITLE
copyright problem in 0.14.0 ( cannot build )

### ISSUE THREAD

**Issue by inithink** [facebook/react-native#3934]
I'm using windows. And I'm developing an android application.

In 0.14.0, I found a file, "node_modules\react-native\local-cli\setup_env.bat" has problem.

In github, there are no problem. (The file commented with ':')

But if I use 'react-native init <Project name>' command, 

the file in local system commented with c style comment(/* */).

Because of it, I can't use commands like 'react-native run-android'.

(Of course, I can use the commands after changing the file.)

Please check it.

**Comment by liesislukas** [comment]
something similar happened to me too. downgraded to v13.2

**Comment by bartonhammond** [comment]
How do you downgrade?  I'm having problems w/ 0.14.0 on mac.

**Comment by liesislukas** [comment]
I've deleted node_modules and changed package.json:

 "react-native": "^0.13.2",

**Comment by jsierles** [comment]
@facebook-github-bot answered
