### ISSUE TITLE
Issues with Xcode's bundling script node finding the `react-native` command

### ISSUE THREAD

**Issue by jaredly** [facebook/react-native#3935]
This is in response to @chirag04's comment here https://github.com/facebook/react-native/pull/3545#issuecomment-154248860

There are two possibilities here:

1) you don't have `react-native-cli` installed; in that case, do `npm install -g react-native-cli` and all should be well
2) Xcode doesn't have the `react-native` command on its path when running the script, probably because your `node` installation isn't global. For me, since I have node installed via `nvm`, I just changed the "Run Script" Xcode entry to be
![image](https://cloud.githubusercontent.com/assets/112170/10987316/638a0bb6-83ef-11e5-84ec-336e727cfa63.png)
The `. ~/.nvm/nvm.sh` line is an easy way to get my node installation on the PATH.

Another way to do it is type `which react-native` in your normal terminal, and you'll get something like:
```
/Users/jared/.nvm/versions/node/v5.0.0/bin/react-native
```
Then take the parent directory of that executable, (`/Users/jared/.nvm/versions/node/v5.0.0/bin/` in this case) and then change that script to be
![image](https://cloud.githubusercontent.com/assets/112170/10987361/df775350-83ef-11e5-80ea-e8962fca4dec.png)

## And now the actual question
Given that the script doesn't always work out of the box, could the `react-native init/upgrade` script be modified to figure out its own directory, and then add the `export PATH=$PATH:/path/to/my/directory` line to the Xcode script automatically?

cc @frantic

**Comment by eddanger** [comment]
:+1: Adding `. ~/.nvm/nvm.sh` to the `Bundle React Native code and images` build phase fixed this for me.

**Comment by chirag04** [comment]
@jaredly Thanks for creating the issue with elaborate description. Since ``nvm`` is the documented dev setup env, ``. ~/.nvm/nvm.sh`` is reasonable.  I wish there was a generic way.

cc @ide

**Comment by chirag04** [comment]
I get:
``/bin/sh: /Users/chirag/Library/Developer/Xcode/DerivedData/lrn-dsvwidjkkxwdtafnxqzavyicmsbs/Build/Intermediates/lrn.build/Debug-iphonesimulator/lrn.build/Script-00DD1BFF1BD5951E006B06BC.sh: .: bad interpreter: Permission denied``

when using . ~/.nvm/nvm.sh

**Comment by ide** [comment]
I looked in some of our Xcode files and we have this:
```
export NVM_DIR=$HOME/.nvm
[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh
[[ -s $(brew --prefix nvm)/nvm.sh ]] && source $(brew --prefix nvm)/nvm.sh
```

**Comment by ide** [comment]
I don't think that's entirely right like NVM_DIR should probably use `brew --prefix nvm` if you installed it with homebrew, but I think what I pasted is roughly correct.

**Comment by jaredly** [comment]
You'll might also want `/bin/bash/` instead of `/bin/sh` as the shell used

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issues-with-xcodes-bundling-script-node-finding-the-react-native-command

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by SudoPlz** [comment]
I just copied some code from within the `react-native-xcode.sh` script and pasted it to my Build path.
I had installed nvm with brew, and node via nvm, so Xcode was not able to find my node installation. Now it can.

My build path now looks like this:

	if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
	. "$HOME/.nvm/nvm.sh"
	elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
	. "$(brew --prefix nvm)/nvm.sh"
	fi
	export NODE_BINARY=node
	../node_modules/react-native/packager/react-native-xcode.sh
