### ISSUE TITLE
Hidden Status Bar results in black bar instead of transparent [Android 13, Google Pixel 6]

### ISSUE THREAD

**Issue by jordanjuras** [facebook/react-native#39362]
### Description

Greetings,

Reporting a bug found in react-native Status Bar, specifically on Google Pixel 6. I have only been able to test on a Pixel 6 device setup with Android v13 (API 33).

In order to hide the status bar, and expose the view behind it, we do the following:
```
  StatusBar.setHidden(true);
  if (Platform.OS === 'android')
  {
    StatusBar.setBackgroundColor('transparent');
    StatusBar.setTranslucent(true);
  }
```

On Pixel 6, this does not work, and instead the status bar is rendered as a black bar, entirely covering the status bar area.

The bug does not reproduce on any of the following devices available to me:
- Google Pixel 3 Android v11
- Samsung Galaxy s9 Android v10
- **Android Pixel 6 v13 EMULATOR**

EXPECTED:
Pixel 3 & Galaxy s9 - init state
![Pixel3_v11_and_GalaxyS9_v10_statusbar_initState](https://github.com/facebook/react-native/assets/22614707/25ca87c9-b245-4eb5-bf7e-b7f197628f4b)

Pixel 3 & Galaxy s9 - touched
![Pixel3_v11_and_GalaxyS9_v10_statusbar_touched](https://github.com/facebook/react-native/assets/22614707/ed133ad3-6be7-4c46-a336-a32330285f03)

ACTUAL:
Pixel 6 - init state
![Pixel6_v13_statusbar_initState](https://github.com/facebook/react-native/assets/22614707/7cb16e2f-4acd-470c-a4f6-2303809332d7)

Pixel 6 - touched
![Pixel6_v13_statusbar_touched](https://github.com/facebook/react-native/assets/22614707/642b92bf-abda-4386-b90e-1e38c3009398)

### React Native Version

0.71.7

### Output of `npx react-native info`

```
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 60.08 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - /opt/homebrew/bin/npm
    Watchman: 2023.07.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/joju/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 20.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

On Google Pixel 6, create react native app with the following component

```
import { Component } from "react";
import { Platform, StatusBar, View } from "react-native";

export default class App extends Component<{},{}> {

  componentDidMount() {

    StatusBar.setHidden(true);
    if (Platform.OS === 'android')
    {
      StatusBar.setBackgroundColor('transparent');
      StatusBar.setTranslucent(true);
    }
      
  }

  render() {
    return (
      <View style={{flex: 1, backgroundColor:'blue'}}/>
    );
  }

}
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/Kdn-2a-rX

**Comment by jordanjuras** [comment]
I have tested and the issue is reproducible on react native version `0.71.13`

**Comment by jordanjuras** [comment]
I have just confirmed that the issue also reproduces on Google Pixel 7 Android v13.

**Comment by IamMasterWayne** [comment]
+1

**Comment by yaroslavnikiforov** [comment]
The same issue is on Android 14 and react-native 0.69.9.

**Comment by jrpn93** [comment]
Same Issue here!
<StatusBar hidden={true} /> will result in black area in some devices in android 13 & 14.
Devices like Google Pixel 6, MIUI Devices with camera cut-outs.

**Comment by jrpn93** [comment]
Okay, I found a solution pretty quickly!
Adding  `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`  in my android/app/src/main/res/values/styles.xml resolved this issue.
just use `<StatusBar hidden={true} />` after adding & Rebuilding your react native android app

Found Here : [](https://github.com/expo/expo/issues/15244#issuecomment-1181617641)

**Comment by yaroslavnikiforov** [comment]
Thanks @jrpn93

**Comment by AustineA** [comment]
> Okay, I found a solution pretty quickly! Adding `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` in my android/app/src/main/res/values/styles.xml resolved this issue. just use `<StatusBar hidden={true} />` after adding & Rebuilding your react native android app
> 
> Found Here : [expo/expo#15244 (comment)](https://github.com/expo/expo/issues/15244#issuecomment-1181617641)

This doesn't work on Samsung devices

**Comment by shubhamguptadream11** [comment]
I am also facing this issue.
Not working in OnePlus, Vivo.

I tried creating sample android app as well.
Without following approaches but didn't worked. 

```
Approach 1:
//    private fun hideStatusBar() {
//        window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_FULLSCREEN
//        actionBar?.hide()
//    }
//
//    private fun showStatusBar() {
//        window.decorView.systemUiVisibility = View.SYSTEM_UI_FLAG_VISIBLE
//        actionBar?.show()
//    }

Approach 2:
//    fun hideStatusBar(activity: Activity) {
//        activity.window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
//    }
//
//    fun showStatusBar(activity: Activity) {
//        activity.window.clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
//    }
```
Is this an issue with all such devices with camera notch at top?

**Comment by shubhamguptadream11** [comment]
I had shared my findings regarding this here: https://github.com/facebook/react-native/issues/46070#issuecomment-2295191599
Also shared one fix. Let me know if it fixes this.

**Comment by shubhamguptadream11** [comment]
@jordanjuras This is fixed in above linked PR.
We can mark this closed now.
