### ISSUE TITLE
 App crashes when I change permission from settings (Read Contact and Read SMS)

### ISSUE THREAD

**Issue by varshaDahare** [facebook/react-native#39386]
### Description

I am using my application, and when I go to the settings and deny permission for contacts and SMS, then return to my app, it crashes. I am using PermissionsAndroid.

### React Native Version

0.71.0

### Output of `npx react-native info`

System:
OS: Windows 10 10.0.22621
CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Memory: 4.94 GB / 13.92 GB
Binaries:
Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
Watchman: Not Found
SDKs:
Android SDK: Not Found
Windows SDK: Not Found
IDEs:
Android Studio: AI-223.8836.35.2231.10671973
Visual Studio: Not Found
Languages:
Java: 17.0.2 - /c/Program Files/Eclipse Adoptium/jdk-17.0.2.8-hotspot/bin/javac
npmPackages:
@react-native-community/cli: Not Found
react: 18.2.0 => 18.2.0
react-native: 0.71.4 => 0.71.4
react-native-windows: Not Found
npmGlobalPackages:
react-native: Not Found

### Steps to reproduce

PermissionsAndroid

### Snack, screenshot, or link to a repository

.

**Comment by cortinico** [comment]
Can you provide a repro?
