### ISSUE TITLE
RN 1.4.0 Build in Xcode: Command `bundle` unrecognized.

### ISSUE THREAD

**Issue by race604** [facebook/react-native#3938]
When the RN 1.4.0 released. I init a new rn project, and run in Xcode, show error like this:

```
+ DEST=/Users/Jing/Library/Developer/Xcode/DerivedData/AwesomeProject-dwggrdvziuvowcaqumecdkqjrbws/Build/Products/Debug-iphonesimulator/AwesomeProject.app
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/Jing/Library/Developer/Xcode/DerivedData/AwesomeProject-dwggrdvziuvowcaqumecdkqjrbws/Build/Products/Debug-iphonesimulator/AwesomeProject.app/main.jsbundle --assets-dest /Users/Jing/Library/Developer/Xcode/DerivedData/AwesomeProject-dwggrdvziuvowcaqumecdkqjrbws/Build/Products/Debug-iphonesimulator/AwesomeProject.app
Command `bundle` unrecognized.Did you mean to run this inside a react-native project?
Command /bin/sh failed with exit code 1
```

It works fine when I run the `react-native bundle ...` command in the root directory of project.

My node version is 4.2.1. Xcode is Version 7.1.

**Comment by AustinAmoruso** [comment]
Same problem...

**Comment by guiguan** [comment]
@race604 LOL, same here. It looks like the $PATH problem.

**Comment by race604** [comment]
Thanks for @guiguan 's help, I figured out my actual problem, the node.js environment is not configured properly for Xcode, so this issue is duplicated with: https://github.com/facebook/react-native/issues/3935

My solution is adding first two lines in project *Build Phases-->Bundle React Native code and images*
```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
../node_modules/react-native/packager/react-native-xcode.sh
```

**Comment by codejet** [comment]
thanks @race604, that fixed it for me as well (while adding ```. ~/.nvm/nvm.sh```didn't seem to work)

**Comment by myusuf3** [comment]
This is still happening for me!

**Comment by myusuf3** [comment]
I have submitted this question now. http://stackoverflow.com/questions/34216567/command-bundle-unrecognized-did-you-mean-to-run-this-inside-a-react-native-pr
