### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

### ISSUE THREAD

**Issue by shaneguru7** [facebook/react-native#39398]
### Description

Intermittent crash occurring in iOS, unable to replicate the issue on our end but production users are impacted. 36% of the crashes are occurring in the background.
Started occuring after updating from react native 0.66 to 0.68.1
 
`
# Crashlytics - Stack trace
# Application: App
# Platform: apple
# Version: app version
# Issue: 2667f4bf9b6d3a0f2892c21ebf84ee4c
# Session: session
# Date: Mon Sep 11 2023 20:23:58 GMT+1000 (Australian Eastern Standard Time)

com.apple.main-thread
0  UIKitCore                      0x67b408 <redacted> + 414
1  UIKitCore                      0x21d724 <redacted> + 264
2  UIKitCore                      0x21fb4c <redacted> + 104
3  UIKitCore                      0xd0e42c <redacted> + 188
4  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
5  libdispatch.dylib              0x7150 _dispatch_block_invoke_direct$VARIANT$mp + 220
6  FrontBoardServices             0xb2ac <redacted> + 40
7  FrontBoardServices             0xa7c0 <redacted> + 176
8  FrontBoardServices             0xe960 <redacted> + 24
9  CoreFoundation                 0xb3448 <redacted> + 24
10 CoreFoundation                 0xc3578 <redacted> + 204
11 CoreFoundation                 0x5790 <redacted> + 348
12 CoreFoundation                 0xae08 <redacted> + 768
13 CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
14 GraphicsServices               0x1988 GSEventRunModal + 160
15 UIKitCore                      0x4e5a88 <redacted> + 1080
16 UIKitCore                      0x27ef78 UIApplicationMain + 336
17 app                            0x6e14 main + 14 (AppDelegate.swift:14)
18 ???                            0x1023704d0 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  Foundation                     0x17eac <redacted> + 232
6  Foundation                     0x56fd0 <redacted> + 88
7  UIKitCore                      0x464ef4 <redacted> + 512
8  Foundation                     0x64bdc <redacted> + 792
9  libsystem_pthread.dylib        0x3338 _pthread_start + 116
10 libsystem_pthread.dylib        0x1938 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x20d8c FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x2116c FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x18394 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x1abf0 FIRCLSMachExceptionServer + 688
4  libsystem_pthread.dylib        0x3338 _pthread_start + 116
5  libsystem_pthread.dylib        0x1938 thread_start + 8

Realm notification listener
0  libsystem_kernel.dylib         0x2294 kevent + 8
1  Realm                          0x3ac40c realm::_impl::ExternalCommitHelper::listen() + 156
2  Realm                          0x3ac55c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&, realm::RealmConfig const&)::$_0> >(void*) + 52
3  libsystem_pthread.dylib        0x3338 _pthread_start + 116
4  libsystem_pthread.dylib        0x1938 thread_start + 8

com.facebook.react.JavaScript
0  JavaScriptCore                 0xd6928c <redacted> + 2834
1  JavaScriptCore                 0x3c835c <redacted> + 163844
2  JavaScriptCore                 0x3c52d0 <redacted> + 151416
3  JavaScriptCore                 0x3c5368 <redacted> + 151568
4  JavaScriptCore                 0x3c5368 <redacted> + 151568
5  JavaScriptCore                 0x3c5368 <redacted> + 151568
6  JavaScriptCore                 0x3c5368 <redacted> + 151568
7  JavaScriptCore                 0x3c52d0 <redacted> + 151416
8  JavaScriptCore                 0x3c52d0 <redacted> + 151416
9  JavaScriptCore                 0x3c52d0 <redacted> + 151416
10 JavaScriptCore                 0x3a00ac <redacted> + 264
11 JavaScriptCore                 0xb32858 <redacted> + 532
12 JavaScriptCore                 0xe4ddf8 <redacted> + 496
13 JavaScriptCore                 0x3c835c <redacted> + 163844
14 JavaScriptCore                 0x3c5368 <redacted> + 151568
15 JavaScriptCore                 0x3c52d0 <redacted> + 151416
16 JavaScriptCore                 0x3c52d0 <redacted> + 151416
17 JavaScriptCore                 0x3c52d0 <redacted> + 151416
18 JavaScriptCore                 0x3c5368 <redacted> + 151568
19 JavaScriptCore                 0x3c5368 <redacted> + 151568
20 JavaScriptCore                 0x3c5368 <redacted> + 151568
21 JavaScriptCore                 0x3c52d0 <redacted> + 151416
22 JavaScriptCore                 0x3c52d0 <redacted> + 151416
23 JavaScriptCore                 0x3c5368 <redacted> + 151568
24 JavaScriptCore                 0x3c5368 <redacted> + 151568
25 JavaScriptCore                 0x3c52d0 <redacted> + 151416
26 JavaScriptCore                 0x3c5368 <redacted> + 151568
27 JavaScriptCore                 0x3c52d0 <redacted> + 151416
28 JavaScriptCore                 0x3c5368 <redacted> + 151568
29 JavaScriptCore                 0x3c5368 <redacted> + 151568
30 JavaScriptCore                 0x3c52d0 <redacted> + 151416
31 JavaScriptCore                 0x3c6634 <redacted> + 156380
32 JavaScriptCore                 0x3c659c <redacted> + 156228
33 JavaScriptCore                 0x3c52d0 <redacted> + 151416
34 JavaScriptCore                 0x3c5368 <redacted> + 151568
35 JavaScriptCore                 0x3c52d0 <redacted> + 151416
36 JavaScriptCore                 0x3a00ac <redacted> + 264
37 JavaScriptCore                 0xb32858 <redacted> + 532
38 JavaScriptCore                 0xe4ddf8 <redacted> + 496
39 JavaScriptCore                 0x3a0258 <redacted> + 280
40 JavaScriptCore                 0xb328ac <redacted> + 616
41 JavaScriptCore                 0x4485a0 JSObjectCallAsFunction + 576
42 jsi                            0xc8c0 facebook::jsc::JSCRuntime::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 268
43 jsireact                       0x128e8 facebook::jsi::Value facebook::jsi::Function::call<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value>(facebook::jsi::Runtime&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, facebook::jsi::Value&&) const + 648
44 jsireact                       0x12538 std::__1::__function::__func<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_4, std::__1::allocator<facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&)::$_4>, void ()>::operator()() + 272
45 React                          0x9174 void std::__1::__invoke_void_return_wrapper<void, true>::__call<void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()> >(void (*&)(std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>), std::__1::function<void ()> const&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > ()>&&) + 144
46 jsireact                       0x8258 facebook::react::JSIExecutor::callFunction(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, folly::dynamic const&) + 2232
47 cxxreact                       0x4fe74 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const + 96
48 React                          0x360dc facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 32
49 React                          0x4bd60 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 40
50 React                          0x4b50c ___ZN8facebook5react16RCTMessageThread8runAsyncENSt3__18functionIFvvEEE_block_invoke + 48
51 CoreFoundation                 0x6d68c <redacted> + 20
52 CoreFoundation                 0x6e4b0 <redacted> + 408
53 CoreFoundation                 0xb1dc <redacted> + 1748
54 CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
55 React                          0x1d328 +[RCTCxxBridge runRunLoop] + 232
56 Foundation                     0x64bdc <redacted> + 792
57 libsystem_pthread.dylib        0x3338 _pthread_start + 116
58 libsystem_pthread.dylib        0x1938 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  CFNetwork                      0x246b9c _CFURLStorageSessionDisableCache + 50420
6  Foundation                     0x64bdc <redacted> + 792
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0xaac mach_msg_trap + 8
1  libsystem_kernel.dylib         0x107c mach_msg + 72
2  CoreFoundation                 0x6c88 <redacted> + 368
3  CoreFoundation                 0xaf90 <redacted> + 1160
4  CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
5  CoreFoundation                 0x99320 CFRunLoopRun + 60
6  CoreMotion                     0x12ab0 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 21528
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

AVAudioSession Notify Thread
0  AudioToolbox                    0x1f50c8 <redacted> + 26
1  libAudioToolboxUtility.dylib    0x27b0 <redacted> + 260
2  CoreFoundation                  0x4ac6c <redacted> + 56
3  CoreFoundation                  0x4e270 <redacted> + 596
4  CoreFoundation                  0xb460 <redacted> + 2392
5  CoreFoundation                  0x1e174 CFRunLoopRunSpecific + 572
6  AudioSession                    0x6478 CADeprecated::GenericRunLoopThread::Entry(void*) + 156
7  AudioSession                    0xf7c8 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 88
8  libsystem_pthread.dylib         0x3338 _pthread_start + 116
9  libsystem_pthread.dylib         0x1938 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  JavaScriptCore                 0xe14f8 <redacted> + 1120
3  libsystem_pthread.dylib        0x3338 _pthread_start + 116
4  libsystem_pthread.dylib        0x1938 thread_start + 8

Thread
0  libdispatch.dylib              0x11304 _dispatch_cache_cleanup + 16
1  libsystem_pthread.dylib        0x3d90 <redacted> + 520
2  libsystem_pthread.dylib        0x6c08 <redacted> + 80
3  libsystem_pthread.dylib        0x224c <redacted> + 98
4  libsystem_pthread.dylib        0x1e88 _pthread_wqthread + 420
5  libsystem_pthread.dylib        0x192c start_wqthread + 8

com.apple.network.connections
0  libnetwork.dylib               0x1385b0 nw_parameters_copy_prohibited_netagent_uuids + 2
1  libnetwork.dylib               0xcbadc nw_path_network_is_satisfied_update_reason + 460
2  libnetwork.dylib               0x7b0534 nw_path_signature_changed_from_previous + 152
3  libnetwork.dylib               0x59d398 nw_protocol_definition_should_flush_cache + 132
4  libnetwork.dylib               0x4a34e0 __nw_association_update_paths_block_invoke + 88
5  libnetwork.dylib               0x70fb4 nw_hash_table_apply + 164
6  libnetwork.dylib               0x4a2f3c nw_association_update_paths + 204
7  libnetwork.dylib               0x15a218 nw_path_necp_update_evaluator + 1884
8  libnetwork.dylib               0x13dfa8 nw_path_necp_check_for_updates + 844
9  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
10 libdispatch.dylib              0x6bb8 _dispatch_continuation_pop$VARIANT$mp + 440
11 libdispatch.dylib              0x188dc _dispatch_source_invoke$VARIANT$mp + 1668
12 libdispatch.dylib              0xc398 _dispatch_workloop_invoke$VARIANT$mp + 1692
13 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
14 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
15 libsystem_pthread.dylib        0x192c start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1014 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1e4c _pthread_wqthread + 360
2  libsystem_pthread.dylib        0x192c start_wqthread + 8

com.apple.root.default-qos
0  libsystem_kernel.dylib         0x2d8c __fcntl + 8
1  libsystem_kernel.dylib         0x2504 fcntl + 84
2  Realm                          0x2becd0 realm::util::File::barrier() + 28
3  Realm                          0x1b24c0 realm::GroupWriter::commit(unsigned long) + 300
4  Realm                          0x195e24 realm::DB::low_level_commit(unsigned long long, realm::Transaction&, bool) + 504
5  Realm                          0x195b38 realm::DB::do_commit(realm::Transaction&, bool) + 140
6  Realm                          0x2ae254 realm::Transaction::commit_and_continue_as_read(bool) + 88
7  Realm                          0x3c52a0 realm::_impl::RealmCoordinator::commit_write(realm::Realm&, bool) + 100
8  Realm                          0x452d9c realm::Realm::commit_transaction() + 168
9  Realm                          0x1284e0 -[RLMRealm commitWriteTransactionWithoutNotifying:error:] + 248
10 RealmSwift                     0x71964 $s10RealmSwift0A0V5write16withoutNotifying_xSaySo20RLMNotificationTokenCG_xyKXEtKlF + 460
11 Firebase                       0x7708 $s10Firebase27FirebaseRemoteConfigServiceC28deleteDismissedAnnouncementsyyF + 376
12 Firebase                       0x71bc $s10Firebase27FirebaseRemoteConfigServiceC17handleFetchResult6status5error10completionySo09FIRRemotedG6StatusV_s5Error_pSgy10ModuleBase0cD0VctFySb_AKtcfU_ + 364
13 Firebase                       0x7570 $sSbs5Error_pSgIegyg_SbSo7NSErrorCSgIeyByy_TR + 68
14 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
16 libdispatch.dylib              0x6858 _dispatch_queue_override_invoke + 720
17 libdispatch.dylib              0x13b94 _dispatch_root_queue_drain + 340
18 libdispatch.dylib              0x1439c _dispatch_worker_thread2 + 172
19 libsystem_pthread.dylib        0x1dc4 _pthread_wqthread + 224
20 libsystem_pthread.dylib        0x192c start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0x1924 <redacted> + 270

Thread
0  libsystem_pthread.dylib        0x1924 <redacted> + 270

Crashed: com.facebook.react.NativeNavigationModuleQueue
0  app.                           0x4d6e40 $s14app15ReactNavigationC19setScreenProperties_14withInstanceIdySDySSyXlGSg_SSSgtF + 268
1  app.                           0x4d7228 $s14app15ReactNavigationC19setScreenProperties_14withInstanceIdySDySSyXlGSg_SSSgtFTo + 140
2  CoreFoundation                 0x20cf0 <redacted> + 144
3  CoreFoundation                 0x3cdd8 <redacted> + 300
4  CoreFoundation                 0x7120c <redacted> + 76
5  React                          0x56f48 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 480
6  React                          0x59bdc facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 704
7  React                          0x59700 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 164
8  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
10 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
11 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
12 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
13 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
14 libsystem_pthread.dylib        0x192c start_wqthread + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  JavaScriptCore                 0x45cd4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1984
3  JavaScriptCore                 0xdb5c <redacted> + 176
4  JavaScriptCore                 0xdfac <redacted> + 328
5  JavaScriptCore                 0x65d44 <redacted> + 336
6  JavaScriptCore                 0x6801c <redacted> + 12
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8

SCNetworkReachability.callback
0  libnetwork.dylib               0x140908 nw_path_should_fallback + 770
1  libnetwork.dylib               0xd5d88 -[NWConcrete_nw_path description] + 12
2  Foundation                     0x1aa20 _NS_os_log_callback + 224
3  libsystem_trace.dylib          0x6cf0 _os_log_fmt_flatten_NSCF + 60
4  libsystem_trace.dylib          0x6400 _os_log_fmt_flatten_object + 228
5  libsystem_trace.dylib          0x42f8 _os_log_impl_flatten_and_send + 1828
6  libnetwork.dylib               0x7ad5e8 __nw_path_necp_update_evaluator_block_invoke + 440
7  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
9  libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
10 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
11 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
12 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
13 libsystem_pthread.dylib        0x192c start_wqthread + 8

JSC Heap Collector Thread
0  libsystem_kernel.dylib         0x1484 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x9bc4 <redacted> + 1240
2  JavaScriptCore                 0x45cd4 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1984
3  JavaScriptCore                 0xdb5c <redacted> + 176
4  JavaScriptCore                 0xdfac <redacted> + 328
5  JavaScriptCore                 0x65d44 <redacted> + 336
6  JavaScriptCore                 0x6801c <redacted> + 12
7  libsystem_pthread.dylib        0x3338 _pthread_start + 116
8  libsystem_pthread.dylib        0x1938 thread_start + 8`

Crashed thread:
`Crashed: com.facebook.react.NativeNavigationModuleQueue
0  app.                           0x4d6e40 $s14app15ReactNavigationC19setScreenProperties_14withInstanceIdySDySSyXlGSg_SSSgtF + 268
1  app.                           0x4d7228 $s14app15ReactNavigationC19setScreenProperties_14withInstanceIdySDySSyXlGSg_SSSgtFTo + 140
2  CoreFoundation                 0x20cf0 <redacted> + 144
3  CoreFoundation                 0x3cdd8 <redacted> + 300
4  CoreFoundation                 0x7120c <redacted> + 76
5  React                          0x56f48 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 480
6  React                          0x59bdc facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 704
7  React                          0x59700 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 164
8  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
9  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
10 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp + 644
11 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp + 408
12 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread + 632
13 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
14 libsystem_pthread.dylib        0x192c start_wqthread + 8
`

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: macOS 13.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 194.51 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: Not Found
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /Users/shanegurusingha/.rvm/gems/ruby-3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: javac 17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Unable to reproduce. 

### Snack, screenshot, or link to a repository

-

**Comment by cortinico** [comment]
Closing as not actionable for us unless you provide a reproducer.
