### ISSUE TITLE
MinifyEnabled breaks app after React Native 0.72.4 upgrade

### ISSUE THREAD

**Issue by UnderTheMoonspell** [facebook/react-native#39391]
### Description

Hey all!

We just upgraded to React Native 0.72.4 following the upgrade helper website. All was good in our QA pipeline, we tested a lot on top of the new version. 

Problems arose when we were in our deployment phase and we noticed that a release version would not start in Android (only). After some investigation the issue seems to be the minifyEnabled in build.gradle. As we were able to startup the app in release mode if its not enabled.

The obfuscated stacktrace is also not very helpful anyone have any idea?

<img width="1179" alt="image" src="https://github.com/facebook/react-native/assets/10156878/f5c5f4f9-6c17-4816-bd7b-5ead94cf8c98">

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 260.80 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.0
    path: ~/.nvm/versions/node/v18.14.0/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.3.1
    path: ~/.nvm/versions/node/v18.14.0/bin/npm
  Watchman:
    version: 2022.10.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/**/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/**/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

.

### Snack, screenshot, or link to a repository

.

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to React Native Firebase. Please open this issue against this other repository:

https://github.com/invertase/react-native-firebase/issues
