### ISSUE TITLE
DeviceEventEmitter example in tutorial fails

### ISSUE THREAD

**Issue by mpj** [facebook/react-native#394]
There is an issue with the tutorial, with the sendAppEventWithName call. 
![Screenshot of issue](https://www.dropbox.com/s/6h6l8zwkbykto6b/Sk%C3%A4rmklipp%202015-03-28%2014.06.11.png?dl=1) 
From: https://facebook.github.io/react-native/docs/nativemodulesios.html

This example code will fail with this problem:
![Screenshot of issue](https://www.dropbox.com/s/036ldd1ycwi2kkp/Sk%C3%A4rmklipp%202015-03-28%2014.08.18.png?dl=1) 
Text for search engine: "Requiring unknown module "RCTNativeAppEventEmitter". If you are sure the modules is there, try restarting the packager.

This is because this call...
https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/React/Base/RCTEventDispatcher.m#L39

Will eventually hit this line, where the error occurs, because there is no RCTNativeAppEventEmitter in the dependency tree. I guess this is because the JavaScript in the example is using the DeviceEventEmitter which is actually requiring the RCT**Device**EventEmitter, not the RCT**App**EventEmitter which I cannot find anywhere in the JS code? 

Changing the example Objective-C to call sendDeviceEventWithName instead of sendAppEventWithName fixes the problem.

**Comment by tptee** [comment]
:+1: sendDeviceEventWithName works for me as well

**Comment by vitch** [comment]
Seems like #918 is a fix so you can still `RCTAppEventEmitter` but for now I'm also using the `DeviceEventEmitter`. It would be good to know what the purpose of the two separate emitters is meant to be...

**Comment by watsonwu9** [comment]
sendDeviceEventWithName works for me too. thanks

**Comment by brentvatne** [comment]
Fixed now!
