### ISSUE TITLE
ForceRTL(false) isn't working when device language is Arabic or Urdu

### ISSUE THREAD

**Issue by sarahabuteen** [facebook/react-native#39414]
### Description

I have an app that has 3 languages, when you install the app for the first time it will detect the device language and set the app language based on it, and in case the user switches the language from the app it will be read from AsyncStorage. It's all working fine except that when the device language is Arabic/Urdu and I try to switch the app language to English the direction stays RTL, even though I added the needed code in order to change it.

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 10.37 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "23"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

**AppDelegate.mm**
```
#import "React/RCTI18nUtil.h"
[[RCTI18nUtil sharedInstance] allowRTL:YES];
```

**MainApplication.java**
```
import com.facebook.react.modules.i18nmanager.I18nUtil;

I18nUtil sharedI18nUtilInstance = I18nUtil.getInstance();
sharedI18nUtilInstance.allowRTL(getApplicationContext(), true);
```

**AndroidManifest.xml**
`android:supportsRtl="true"`

**React native code:**

**Code that checks the initial app language**
```
try {
        await AsyncStorage.getItem('lng').then((language) => {
          if (language) {
            return callback(language);
          }
          let lng = '';
          const deviceLanguage = Platform.OS === 'ios'
            ? NativeModules.SettingsManager.settings.AppleLocale
          || NativeModules.SettingsManager.settings.AppleLanguages[0]
            : NativeModules.I18nManager.localeIdentifier;
          if (deviceLanguage?.startsWith('en')) {
            lng = 'en';
          } else if (deviceLanguage?.startsWith('ar')) {
            lng = 'ar';
          } else if (deviceLanguage?.startsWith('ur')) {
            lng = 'ur';
          }

          return callback(lng);
        });
      } catch (error) {
        console.error('Failed to get language from async storage:', error);
      }
```
    
**Code that switches the app language:**
```
switch (lng) {
      case 'ar':
        i18n
          .changeLanguage('ar')
          .then(() => {
            AsyncStorage.setItem('lng', 'ar');
            I18nManager.allowRTL(true);
            I18nManager.forceRTL(true);
            RNRestart.Restart();
          });
        break;

      case 'en':
        i18n
          .changeLanguage('en')
          .then(() => {
            AsyncStorage.setItem('lng', 'en');
            I18nManager.allowRTL(false);
            I18nManager.forceRTL(false);
            RNRestart.Restart();
          });
        break;

      case 'ur':
        i18n
          .changeLanguage('ur')
          .then(() => {
            AsyncStorage.setItem('lng', 'ur');
            I18nManager.allowRTL(true);
            I18nManager.forceRTL(false);
            RNRestart.Restart();
          });
        break;

      default:
        return null;
      }
```
 

### Snack, screenshot, or link to a repository

N/A

**Comment by nazmeln** [comment]
+1

**Comment by nazmeln** [comment]
Hey @sarahabuteen,
Please verify if isRTL is still not forced by adding the log to AppDelegate file:

`RCTLogInfo(@"isRTLForced: %d", [[RCTI18nUtil sharedInstance] isRTLForced]);`
  
And don't forget to add this import `#import <React/RCTLog.h>`

Hope it helps! :)

**Comment by omaranwaar** [comment]
Hi @sarahabuteen @nazmeln, I have the same issue with the RTL layout I want to set the layout to RTL by default when user installs the app, it is working fine in iOS but in android when I add this code 
```
sharedI18nUtilInstance.forceRTL(this, true);
sharedI18nUtilInstance.allowRTL(this, true);
```
in mainApplication.java it always stay in the RTL mode even after applying  `I18nManager.forceRTL(false)` , but if I remove the mainApplication.java additions then it doesn't change the layout to RTL at all.

**Comment by nazmeln** [comment]
Hey @omaranwaar,
I suppose it might happen because you you force RTL in MainApplicationJava and it sets this flag to true, then you cannot change it from the RN part. Have you tried to remove forceRTL from the Java file and call it only on RN side?
After removing the code, please delete application and rebuild again.

**Comment by omaranwaar** [comment]
@nazmeln yes, I did. In short, If I add the code in mainApplication.java it keeps on RTL always and if I don't add that, it keeps on LTR always. Which is pretty annoying as mainApplication.java builds only once and if I am forcing it using i18nManager and restarting the app it should work. :(

**Comment by nazmeln** [comment]
@omaranwaar 
Hmm, yeah, it should work. Can you try to debug if the flag is forced on Android side? I think you can log some data to AndroidStudio console.

**Comment by oviedo97fer** [comment]
+1

**Comment by Khalid-Badawi2001** [comment]
holy this issue needs a fix, have u fixed it bro?

**Comment by omaranwaar** [comment]
@Khalid-Badawi2001 I made some changes natively and stored the language in shared preferences in MainApplication.java for first install. Same for iOS and everything works as expected.

**Comment by Khalid-Badawi2001** [comment]
thanks for the reply brother, can u explain abit further?

**Comment by arsensgitacc** [comment]
@Khalid-Badawi2001 have you found a solution? The @omaranwaar's solution not working for me, cause `RNRestart.Restart();` doesn't go through native code's init parts (onCreate and application:didFinishLaunchingWithOptions). Can we re-open the issue?

**Comment by ferasabufaresKabi** [comment]
> @Khalid-Badawi2001 have you found a solution? The @omaranwaar's solution not working for me, cause `RNRestart.Restart();` doesn't go through native code's init parts (onCreate and application:didFinishLaunchingWithOptions). Can we re-open the issue?


@arsensgitacc  same here did you find any solution for this problem
