### ISSUE TITLE
onSubmitEditing not working in TextInput with multiline 

### ISSUE THREAD

**Issue by rockimanj** [facebook/react-native#39427]
### Description

In TextInput, onSubmitEditing is not firing when tap on 'done' button in keyboard. Below are props

returnKeyType="done"
multiline={true}

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Pro
  Memory: 98.86 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.8.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.18.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2022.08.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/msubramaniam/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

In TextInput, set props to multiline and returnKeyType to 'done'. when tap on done , onSubmitEditing not triggered

### Snack, screenshot, or link to a repository

NA

**Comment by Cyber-Griffo** [comment]
You need to set the property "bluronsubmit={true}" in order to fire the onSubmit Event

**Comment by rockimanj** [comment]
> You need to set the property "blurOnSubmit={true}" in order to fire the onSubmit Event

Yes, it worked.. Thank you!!

**Comment by liuxzzz** [comment]
> Yes, it worked.. Thank you!!

Thank you!!

**Comment by richardo2016x** [comment]
> You need to set the property "blurOnSubmit={true}" in order to fire the onSubmit Event

It works, thank you. And when I met the issue, the property `blurOnSubmit` has been deprecated

<img width="664" height="243" alt="Image" src="https://github.com/user-attachments/assets/df94d5f2-27d9-4030-820f-6660fa8d064a" />

The new solution is set `submitBehavior="blurAndSubmit"` for `multiple={true}`

<img width="553" height="344" alt="Image" src="https://github.com/user-attachments/assets/4a325745-0fb7-4f8f-96aa-d9c2d4ba751e" />
