### ISSUE TITLE
[RN 0.12] Native Modules require override of createViewManagers(ReactApplicationContext)

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#3942]
I was following the Android Toast Native Modules tutorial on the RN. While createViewManagers() is for native UI components instead, and the docs mentions nothing about it, Android Studio suggests error for not implementing it and results in compilation error as shown below. The error was returned after saving all code in Android Studio and running react-native run-android command in console. Can I know how to get around this error? Thank you.

Error Message:

RegisterToastPracticeModule.java:13: error: RegisterToastPracticeModule is not abstract and does not override abstract method createViewManagers(ReactApplicationContext) in ReactPackage
public class RegisterToastPracticeModule implements ReactPackage {
       ^
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by lucasferreira** [comment]
Hi @ACCTFORGH,

You have to create the complete class, override all of the methods not only that are suggest in docs, it's something like that:

public class RNSendIntentPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new RNSendIntentModule(reactContext));
        return modules;
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

}

Unfortunately, this is a Java thing, but it is to solve.

I made some react-native android modules, if you need to see how I do check on my github:
https://github.com/lucasferreira/react-native-send-intent
https://github.com/lucasferreira/react-native-simpledialog-android

**Comment by ACCTFORGH** [comment]
@lucasferreira Awesome, thanks Lucas. It works. Your repo is impressive too!  By the way, @ide, will we have documentation about the RN Java API's as well?

**Comment by soniaparikh** [comment]
Hi Lucas,
I am getting following error.
/android/app/src/main/java/com/dntandroidapp/MainActivity.java:44: error: cannot find symbol
            new RNSendIntentPackage() 
                ^
  symbol:   class RNSendIntentPackage
  location: class MainActivity
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

I see your repo. And I replaced my two java classes RNSendIntentPackage and RNSendIntentModule. But, still it gives me the error.

**Comment by lucasferreira** [comment]
Hi @soniaparikh,

I'd recommend that you follow the instructions from here: https://github.com/lucasferreira/react-native-send-intent

Using npm to install the package, change your android files (gradle and etc) and them use the module.

**Comment by soniaparikh** [comment]
Thank you for reply. Its working fine now. I missed some settings.

**Comment by uc-des** [comment]
Hello Lucasferreira 

:app:compileDebugJavaWithJavacC:\Users\Deeksha Gupta\git\pe-gold-native\android\app\src\main\java\com\pegoldnative\MainActivity.java:39: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by lucasferreira** [comment]
Hi @uc-des 

Whats is your RN version? The things changed a lot in the latest versions of RN.

Now we have two files to work (MainActivity.java and MainApplication.java). I think that your method could be the one moved to MainApplication.java.

Since they not belong to MainActivity anymore, the @Override notation didn't works.

Look for more info here:
https://facebook.github.io/react-native/docs/native-modules-android.html
https://facebook.github.io/react-native/docs/native-components-android.html

**Comment by uc-des** [comment]
Thank you for reply. I was missing  MainApplication.java this file. Now its working fine
