### ISSUE TITLE
require('image!somePng') broken on Android for 0.14.0

### ISSUE THREAD

**Issue by Kudo** [facebook/react-native#3943]
I have an issue for RN 0.14.0 that cannot import a static asset image.
However, npm install react-native from github master branch and gradle compile from maven local build works fine.

There must be some wrong from 0.14.0 however, there are too much changes between 0.14.0 and master.
Are there any hints if I can solve this?
Thanks.

**Comment by 52myu** [comment]
require(./somePng.png),try it

**Comment by kusamakura** [comment]
Hi @Kudo, 0.14 changed the way you can manage your images for both iOS and Android. It's like requiring .js files. Check here: http://facebook.github.io/react-native/docs/images.html#content

**Comment by Kudo** [comment]
Thank you guys. However how if I would require images from Android project drawables (i.e. android/app/src/main/res/drawable-*/ ) ?

**Comment by 52myu** [comment]
It can automatically find the directory

**Comment by 52myu** [comment]
https://github.com/52myu/react-native/commit/1019cc3aef56ef0d105b6781f3d5dd5342243172

**Comment by Kudo** [comment]
My test for 0.14.0.
js file at `${ProjectRoot}/src/containers/App.js`

```jsx
      <View style={styles.container}>
        <ToolbarAndroid
          style={styles.toolbar}
          navIcon={require('./ic_menu_white_24dp.png')}
          titleColor='#fff'
          title={'Toolbar'}
        />
        <Text>foo</Text>
      </View>
```

![screen shot 2015-11-06 at 5 57 40 pm](https://cloud.githubusercontent.com/assets/46429/10994211/e4499e36-84af-11e5-84fc-610b97461367.png)

Output of files at `find ${ProjectRoot}/ -name '*ic_menu_white_24dp.png'`
```
./android/app/build/intermediates/res/merged/debug/drawable-hdpi/ic_menu_white_24dp.png
./android/app/build/intermediates/res/merged/debug/drawable-mdpi/ic_menu_white_24dp.png
./android/app/build/intermediates/res/merged/debug/drawable-xhdpi/ic_menu_white_24dp.png
./android/app/build/intermediates/res/merged/debug/drawable-xxhdpi/ic_menu_white_24dp.png
./android/app/build/intermediates/res/merged/debug/drawable-xxxhdpi/ic_menu_white_24dp.png
./android/app/src/main/res/drawable-hdpi/ic_menu_white_24dp.png
./android/app/src/main/res/drawable-mdpi/ic_menu_white_24dp.png
./android/app/src/main/res/drawable-xhdpi/ic_menu_white_24dp.png
./android/app/src/main/res/drawable-xxhdpi/ic_menu_white_24dp.png
./android/app/src/main/res/drawable-xxxhdpi/ic_menu_white_24dp.png
```

Did I have anything wrongs?

**Comment by sarriaroman** [comment]
From Android resources the right way to use the drawable is

```
<View style={styles.container}>
        <ToolbarAndroid
          style={styles.toolbar}
          navIcon={{ uri: 'ic_menu_white_24dp' }}
          titleColor='#fff'
          title={'Toolbar'}
        />
        <Text>foo</Text>
      </View>
```

"ic_menu_white_24dp" must be in your drawables ;)

**Comment by Kudo** [comment]
@sarriaroman the syntax works fine, thank you.
I guess we should update the UIExplorer sample code if `require('image!...')` is not work or going to deprecate.

**Comment by marsprince** [comment]
@Kudo I tried require(./somePng.png) and {{ uri: 'ic_menu_white_24dp' }},both of them can't work well.What's your solution?

**Comment by marsprince** [comment]
Oh,I tyied new Image Resources System, all fail.Require is OK but I can't see image.Why?

**Comment by Kudo** [comment]
@marsprince Any further information such as your code snippet, image file structure and error log ?
For my worked solution is just to use `navIcon={{ uri: 'ic_menu_white_24dp' }}`.

**Comment by jozn** [comment]
I have the same problem

**Comment by marsprince** [comment]
@Kudo The problem is no any error.Everything right but it showed null.DId you use github master branch instead of npm branch to make it work?

**Comment by Kudo** [comment]
@marsprince Where did you put your my-icon.png?
I think you should put my-icon.png in the same folder as the JS file for your case. (I.e. not in Android drawable folder)

BTW, regarding the "Failed propType", please try to remove the double quotes from the width/height value.

**Comment by marsprince** [comment]
@Kudo thank you,guys.If I put my pictures in a wrong folder,packager will throw a ERROR.However I didn't get it.Maybe other fault.

**Comment by Kudo** [comment]
@marsprince I only have this issue in debug JS mode as #3989 
You may try to inspect the element if the element is constructed.
and further add console.log to https://github.com/facebook/react-native/blob/v0.14.1/Libraries/Image/Image.android.js#L143 and check the imageProps content.

You can check the console.log output from Xcode console, adb logcat, or Chrome devtool is you are in debugging JS mode.

There might be a "src" field, which has the image URL, check if you can view the image by the URL in your simulator or real device.
This is just my way to find #3989's problem, just for your reference if it may helps.

**Comment by marsprince** [comment]
@Kudo  Thank you,guys! I will try it.

**Comment by atom992** [comment]
I am using 0.14.0
I tried 
```
navIcon={{ uri: 'ic_menu_white_24dp' }}
```

and 
```
navIcon={{ uri: "ic_menu_white_24dp", isStatic: true }}
```

and 
```
navIcon={require('./ic_menu_white_24dp.png')}
```

all of those ways didn't work.

**Comment by Kudo** [comment]
@atom992 You may try the way https://github.com/facebook/react-native/issues/3943#issuecomment-155139757 to troubleshooting.  I guess the issue may relate to your environment.

**Comment by Kudo** [comment]
I am going to close this issue that the problem is solved for @sarriaroman's help. Thank you guys.
For RN 0.14, to use hybrid app's resource, we should follow http://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources.

If there are further questions which are not real issues, maybe we could follow up on stackoverflow?
