### ISSUE TITLE
iPhone 15 Pro Max simulator crash with newly-generated react-native project

### ISSUE THREAD

**Issue by karatekid430** [facebook/react-native#39438]
### Description

https://stackoverflow.com/questions/77095463/crash-when-running-react-native-app-on-iphone-15-pro-max-simulator

Thread 1: "Failed to load bounding path bitmap data from the asset manager for asset name: BoundingPathBitmap-1290x2796-430x932-3.00x"

It works on iPhone 15 Pro simulator - it seems to be a problem with the screen resolution of the iPhone 15 Pro Max (1290x2796px). But I cannot find these files for other resolutions, but they must exist somewhere because it does not fail to load the assets for other simulators.

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5.2
  CPU: (8) arm64 Apple M1
  Memory: 126.17 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/nicholas/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8512546
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/nicholas/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

`npx react-native@0.72.4 init MyReactNativeApp --template react-native-template-typescript && cd MyReactNativeApp && yarn && npx pod-install`

Then open the ios folder in Xcode 15.0 and build for iPhone 15 Pro Max simulator and notice the runtime crash.

### Snack, screenshot, or link to a repository

Do the above steps.

**Comment by cipolleschi** [comment]
Hello @karatekid430. I'm sorry that you are encountering this issue, but I think it is something related to your local environment.

I just spin up a new app from 0.72.4 and one from the nightly of 2 days ago and they both work fine without a single change.

| Nightly | 0.72.4 |
| --- | --- |
| <img width="350" alt="Screenshot 2023-09-14 at 13 45 42" src="https://github.com/facebook/react-native/assets/11162307/7245063a-859b-4263-9bf5-fc0d2a1b4a9c"> | <img width="350" alt="Screenshot 2023-09-14 at 13 45 42" src="https://github.com/facebook/react-native/assets/11162307/47c6d4c7-d047-4451-bc81-6420b5961150"> |

**Comment by cipolleschi** [comment]
Sorry, but I need a reproducer and a clear set of instruction to follow.
As shown above, I could spin up a new app using 0.72.4 and running it on an `iPhone 15 Pro Max`.


Also, the  `--template react-native-template-typescript` is not maintained anymore, as React Native is using Typescript by default nowadays. So it could be that the issue is due to the outdated template.

**Comment by pecabum** [comment]
@cipolleschi everything works fine on simulators, app is crashing on real devices.

**Comment by cipolleschi** [comment]
Can you try without the `--template` parameter?
Can you also share the crash report?

**Comment by chris-hulbert-wfd** [comment]
I successfully resolved this by running: `sudo xcode-select -s /Applications/Xcode.app`, might be worth a try if others hit this issue.
