### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

### ISSUE THREAD

**Issue by vicheanath** [facebook/react-native#39436]
### Description

I can't build or run DBUG

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 190.45 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Documents/Project/MobleApp/ReactNative/XXXXX/node_modules/.bin/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- Android

### Snack, screenshot, or link to a repository

<img width="1053" alt="Screenshot 2023-09-13 at 9 47 23 PM" src="https://github.com/facebook/react-native/assets/48352653/4ed8a091-d755-4681-ab17-1398dbf946f9">

**Comment by cortinico** [comment]
> Java:
> version: 20.0.2

Could you downgrade to JDK 17 (or 19) as that is the cause of your problem.
