### ISSUE TITLE
"Property storage exceeds 196607 properties" error when using `fetch` more than a certain number of times in React Native

### ISSUE THREAD

**Issue by ishikawa** [facebook/react-native#39441]
### Description

We are developing an application using React Native and Expo. This application needs to run 24/7 and performs network requests using `fetch()` regularly for monitoring purposes.

The issue we are facing is that after running the application for a while, from some point, network requests starting to fail. Through investigation using logs from Sentry, we have identified the following problem:

- We are using `fetch()` for network requests.
- At the completion of a `fetch()` request, an error occurs: `Property storage exceeds 196607 properties`.

The stack trace when this error occurs is as follows:

```
message: Property storage exceeds 196607 properties,
name: RangeError,
stack:
RangeError: Property storage exceeds 196607 properties
    at register (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:13781:20)
    at createFromOptions (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:13614:30)
    at get (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:13182:67)
    at anonymous (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:15155:45)
    at call (native)
    at dispatchEvent (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:14686:31)
    at setReadyState (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:13481:31)
    at __didCompleteResponse (/Users/expo/Library/Developer/Xcode/DerivedData/xxx/main.jsbundle:13289:29)
    at apply (native)
    at anonymous
```

Through further investigation, the following findings have been uncovered:

- The polyfill used for `fetch`, [whatwg-fetch](https://github.com/JakeChampion/fetch), returns responses as `Blob` objects.
- When a `Blob` is created, it is registered with blobID in the [BlobRegistry](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Blob/BlobRegistry.js), which is not automatically released.
- This issue was previously reported in #19248 and was fixed by modifying whatwg-fetch. However, with the implementation of automatic garbage collection in #24405, the implementation was reverted in commit bccc92dfdd2d85933f2a9cb5c8d1773affb7acba, returning to the original behavior.
- Although #24405 enables `Blob` objects to be garbage collected, the Blob IDs registered in the BlobRegistry remain, causing the count to increase each time `fetch` is called.
- As a result, the `Property storage exceeds 196607 properties` error occurs

## Our solution

To address this issue and prevent the error, we have modified the implementation of `BlobRegistry` to use a `Map` instead of an object. By using a Map, there is no limit to the number of entries.

```js
const registry: Map<String, number> = new Map();

const register = (id: string) => {
  const used = registry.get(id);

  if (used != null) {
    registry.set(id, used + 1);
  } else {
    registry.set(id, 1);
  }
};

const unregister = (id: string) => {
  const used = registry.get(id);

  if (used != null) {
    if (used <= 1) {
      registry.delete(id);
    } else {
      registry.set(id, used - 1);
    }
  }
};

const has = (id: string): number | boolean => {
  return registry.get(id) || false;
};

module.exports = {
  register,
  unregister,
  has,
};
```

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M2
  Memory: 92.86 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /Users/takanori.ishikawa/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Invoke `fetch()` more than 196,607 times 😄 

### Snack, screenshot, or link to a repository

To demonstrate this issue, I created a simple Expo application.
https://github.com/ishikawa/react-native-fetch-property-storage-exceeds-error

You can run it with expo:

```
$ npm i
$ npm run ios
```

![20230914173506（中）](https://github.com/facebook/react-native/assets/18448/be11ee7a-eaa8-467a-ad45-e4680597cc17)
![20230914173531（中）](https://github.com/facebook/react-native/assets/18448/fa741d28-f396-461c-a07c-e6182811129a)

**Comment by ishikawa** [comment]
I also added PR https://github.com/facebook/react-native/pull/39528

**Comment by ishikawa** [comment]
The fix is merged https://github.com/facebook/react-native/pull/39528 in https://github.com/facebook/react-native/commit/deca8c56ee009226f95c1f131e47025119884d35. Thanks!

**Comment by robsadams** [comment]
Will this be in release 0.72.4 and beyond?

**Comment by Ladvace** [comment]
getting same issue too

**Comment by robsadams** [comment]
Is this rolled back to react-native .71.2?   If so, does anybody know how to pick it up on vscode?  I am already using react-native tools which seems to be using react-native .71.2.... I can't find instructions to pick up patches or upgrade react native within vscode.

**Comment by brunomartins-com** [comment]
Do you guys know which version it is fixed? I am using 0.72.6 and getting this error.

**Comment by robsadams** [comment]
Above they gave a thumbs up to .72.4 so I assume from that point on... I upgraded to .73 and have not seen it.... although I have not tried to recreate it.

**Comment by softmarshmallow** [comment]
Can anyone tell what this is regards to? which module is throwing this error? no clue, can't debug.

**Comment by Nantris** [comment]
Can anyone confirm what version this is fixed on? Or even that it really is fixed?

**Comment by robertdue** [comment]
> Can anyone confirm what version this is fixed on? Or even that it really is fixed?

I have the same with 0.72.10

**Comment by faisal-rehman19** [comment]
Facing the same issue with 0.73.1

**Comment by gabriel-messas** [comment]
0.73.4 still with error here

**Comment by Nantris** [comment]
@ishikawa are you sure this is fixed and should be closed?

**Comment by DrRefactor** [comment]
Observing the same issue on long running app in 0.72.6.

**Comment by jack2684** [comment]
Same issue with `0.73.2`

![image](https://github.com/facebook/react-native/assets/1225301/e7dbe2bb-2804-4213-86f9-03a09d399a17)

**Comment by Nantris** [comment]
@ishikawa would you please re-open this issue?

**Comment by simon-accesso** [comment]
> @ishikawa would you please re-open this issue?

This! Observed with 72.6 and higher.

**Comment by jbernardo** [comment]
Happened today in React Native v0.73.5.

RangeError: Property storage exceeds 196607 properties, js engine: hermes

**Comment by tribou** [comment]
https://github.com/facebook/hermes/issues/851 may be related

**Comment by therbta** [comment]
I'm facing the same issue on Android.

**Comment by Vilandry** [comment]
I'm facing this as well, could anyone find a solution?

**Comment by zameschua** [comment]
Facing this on ios 0.73.6

**Comment by untilhamza** [comment]
Facing this with react native 0.73.6 as well

**Comment by dhaval97shah** [comment]
I am also facing the same issue

**Comment by damdafayton** [comment]
same problem here

**Comment by domenicoprestia** [comment]
same problem here, when trying to interact (edit or delete) images on bucket

**Comment by RemiHin** [comment]
same issue

**Comment by calipsow** [comment]
also same here

**Comment by gikami** [comment]
У меня такая же ошибка

**Comment by CommanderRedYT** [comment]
I also have this issue with 0.72.6

**Comment by landabaso** [comment]
Still an issue in 0.74.1 using Hermes engine.

**Comment by robsadams** [comment]
How do we get this reopened?   It is likely not being looked at because it is closed.

**Comment by daveyd80** [comment]
Same Issue here 0.73.1 in a long running app. Issue needs re-opening please!

RangeError: Property storage exceeds 196607 properties

```
This error is located at:
    in Unknown (created by LogBoxInspectorSourceMapStatus)
    in RCTView (created by View)
    in View (created by LogBoxButton)
    in TouchableWithoutFeedback (created by LogBoxButton)
    in LogBoxButton (created by LogBoxInspectorSourceMapStatus)
    in LogBoxInspectorSourceMapStatus (created by LogBoxInspectorStackFrames)
    ...
```

**Comment by arun057** [comment]
Facing the same issue on 0.74.1 with Hermes.

**Comment by Med5KDB** [comment]
Facing the same issue when trying to upload file to aws s3 (even if I think it's not related to file-upload action, seems to be related to the `fetch`

**Comment by Mikail-1022063** [comment]
Facing the same issue, any updates on this? I also have a image upload, and somethimes after being a couple of minutes afk in the app i get this error Property storage exceeds 196607 properties

**Comment by inkCrazy** [comment]
Has the problem been solved？

**Comment by iamsreeragkp** [comment]
Still facing this problem in 0.73.0

**Comment by danyalutsevich** [comment]
What can be the cause of this error?
Im having this error in react-native 0.74.2
Im using expo 51.0.14

**Comment by Nantris** [comment]
> What can be the cause of this error?

I believe the cause is that objects can only support a maximum of 196607 properties in the Hermes engine

**Comment by NewvilleMedia** [comment]
I get this error when the simulator is open and I let it sit idle for a bit.

**Comment by Dat-Mobile** [comment]
For me I `console.log` the Buffer variable, removed it and now working fine

**Comment by AlastairTaft** [comment]
> For me I `console.log` the Buffer variable, removed it and now working fine

Thank you, you've saved me a headache

**Comment by f1shy-dev** [comment]
> For me I `console.log` the Buffer variable, removed it and now working fine

Can you show details of this implementation/fix? What do you mean?

**Comment by AlastairTaft** [comment]
> > For me I `console.log` the Buffer variable, removed it and now working fine
> 
> Can you show details of this implementation/fix? What do you mean?

Console logging on an extremely large array causes the error / crash. Which makes sense.

**Comment by jeafgilbert** [comment]
I used `clone` function from 'lodash' had this error, now working fine after switch to ramda.

**Comment by ywisax** [comment]
Same problem in react-native 0.74.5

**Comment by atalayio** [comment]
This is javascript engine error, you can try build and see the result. You won't get such an error in native build or any performance issue too. I wasn't figured out this but in build I was used without any error.

**Comment by stdiodavid** [comment]
Same problem in React Native v0.75.2

**Comment by landabaso** [comment]
Hi @ishikawa,

I see that several users, including myself, are still facing this issue in the latest versions. Would you consider reopening this issue to raise awareness and revisit the problem?

Thank you!

**Comment by Whitelistedd** [comment]
also experiencing the same thing

**Comment by bumpingChris** [comment]
I'm experiencing the same thing too

**Comment by just-dodo** [comment]
experiencing the same thing

**Comment by ishikawa** [comment]
Apologies for the delay in responding. Since the fix I proposed was merged, I have not been able to reproduce the issue **when using `fetch`**, and I believe the PR resolved the problem. Our app has been running for over a year since the issue, and we haven't encountered the same problem.

I also updated my previous reproduction code to the latest Expo SDK 51 (w/ react-native 0.74.5), but the issue still does not reproduce.

- [https://github.com/ishikawa/react-native-fetch-property-storage-exceeds-error](https://github.com/ishikawa/react-native-fetch-property-storage-exceeds-error)

While I don’t have much capacity to dive deeper into this, if anyone is seeing this issue with `fetch` under different conditions, it would be interesting to hear more details.

**Comment by angelopedroso** [comment]
I'm using tanstack query to do a get requisition from 5 to 5s, after 6h (maybe), emit this error. 0.73.6. I'm using axios with react query

**Comment by XantreDev** [comment]
```ts
function App() {
  useEffect(() => {
    const tenMb = new Uint8Array(10 * 1024 * 1024);
    const formData = new FormData();
    formData.append("0", tenMb);

    fetch("https://www.google.com/", {
      method: "POST",
      body: formData
    })
      .then(res => {
        console.log("successfully send 10mb", res);
      })
      .catch(err => {
        console.log("failed to send 10mb", err);
      });
  }, []);
  return null
```
```
 LOG  failed to send 10mb [RangeError: Property storage exceeds 196607 properties]
 ```

**Comment by vitordesouza** [comment]
This does not seem to be exclusively related to fetch. 
I am getting this error simply by leaving the app running, no requests, no usage. Couple hours in standby and I get this error. React native 0.74.5

**Comment by edgarciametro** [comment]
> This does not seem to be exclusively related to fetch. I am getting this error simply by leaving the app running, no requests, no usage. Couple hours in standby and I get this error. React native 0.74.5

this is my exact experience, started a new build and for now it is gone.

**Comment by fistofzen** [comment]
same for me 

> > This does not seem to be exclusively related to fetch. I am getting this error simply by leaving the app running, no requests, no usage. Couple hours in standby and I get this error. React native 0.74.5
> 
> this is my exact experience, started a new build and for now it is gone.

**Comment by Nantris** [comment]
I think people are not understanding this is related to the maximum properties an object can have. Make an enormous array and log it out and you'll face this problem too.

**Comment by fistofzen** [comment]
> I think people are not understanding this is related to the maximum properties an object can have. Make an enormous array and log it out and you'll face this problem too.

I dont have any case like that.

**Comment by vitordesouza** [comment]
> I think people are not understanding this is related to the maximum properties an object can have. Make an enormous array and log it out and you'll face this problem too.

Yes, that may be true. The problem is that the identity of the hypothetical enormous array is a mistery. 
- I don't deal with big objects or big amounts of data in my own code.
- The error occurs independently from the usage at random moments which makes it impossible to debug.

**Comment by Ceft7412** [comment]
> For me I `console.log` the Buffer variable, removed it and now working fine

This solved my issue! I have a for loop and a console.log of my base64 variable, removing it fixed the problem.

**Comment by gavinsykes** [comment]
This is still an issue on v0.73.6, but now the included `BlobRegistry` implementation is the same as what ishikawa first posted on here. What else could be causing it?

**Comment by psnet** [comment]
Dear React Native developers, I understand your concerns about [increase heap size](https://github.com/facebook/hermes/blob/main/CMakeLists.txt#L137), but can we at least make **error message more informative**? Because of now, it doesnt really helps with `RangeError: Property storage exceeds 196607 properties`:
- `RangeError` for what? First thought "did miss somewhere with `TypedArray`? Did I try to put over `255` for `Uint8Array` etc?"
- What is `Property storage`?
- What a magic number `196607`? Why not power of 2?
- And many other questions...

In many cases if error message could describe that it relates to pure **js `Object`'s own properties count**, devs possible could find problem solving faster.

Also relates to

https://github.com/facebook/hermes/issues/851
https://github.com/facebook/hermes/issues/1070
https://github.com/facebook/react-native/issues/39441

**Comment by vicnguyenqt** [comment]
Any update? Can we reopen the ticket?
