### ISSUE TITLE
~/.m2/repository/com/facebook/react/gradleplugin missing

### ISSUE THREAD

**Issue by hacksparrow** [facebook/react-native#3944]
Where does one get `~/.m2/repository/com/facebook/react/gradleplugin` from?

**Comment by leeight** [comment]
+1

**Comment by potsypantsy** [comment]
+1

**Comment by BigPun86** [comment]
+1

**Comment by grabbou** [comment]
What is the RN version you are using? Gradle plugin used to be back in the day, but looks like it does not exist anymore. If you were upgrading your app from the early version, most likely you might need to update your files.

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-8** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
