### ISSUE TITLE
Build Failed with Expo and React Native - main.jsbundle does not exist

### ISSUE THREAD

**Issue by tej-thambi** [facebook/react-native#39460]
### Description

I'm developing an app using Expo and React Native, and trying to make an iOS build using eas build -p iOS. It fails every time at Run fastlane, and the build details show the following message:

❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/freeapp-celtkelekabrvocesclaslgcuhcp/Build/Intermediates.noindex/ArchiveIntermediates/freeapp/BuildProductsPath/Release-iphoneos/freeapp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.3.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 684.48 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 14.21.2
    path: ~/.nvm/versions/node/v14.21.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v14.21.2/bin/yarn
  npm:
    version: 6.14.17
    path: ~/.nvm/versions/node/v14.21.2/bin/npm
  Watchman:
    version: 2023.01.30.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9514443
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

eas build -p iOS

### Snack, screenshot, or link to a repository

https://github.com/expo/expo/issues/21542

**Comment by cortinico** [comment]
If you're using Expo, please report the bugs on Expo's repository.

> This must be a bug with React Native, please report it here: [facebook/react-native/issues](https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

This error message is confusing and should probably be changed by the Expo folks (cc @Kudo)

**Comment by Kudo** [comment]
@cortinico you should did that already in f874a7e7d3639d953749643eac072f29c25525b0 😅

@tej-thambi for eas build problem. please open an issue at https://github.com/expo/expo/issues.

**Comment by cortinico** [comment]
> you should did that already in [f874a7e](https://github.com/facebook/react-native/commit/f874a7e7d3639d953749643eac072f29c25525b0) 😅

Oh man 😅 you're so right
