### ISSUE TITLE
[ImagePickerIOS] require('NativeModules').ImagePickerIOS is undefined

### ISSUE THREAD

**Issue by dvcrn** [facebook/react-native#3947]
Hi,

I noticed that with react 0.14.0 `ImagePickerIOS` is no longer inside `require('NativeModules')`, resulting in all function calls on it throwing an error. 
Couldn't figure out why that is yet. Anyone a idea? 

Tested with a fresh project with react 0.14.0

**Comment by nicklockwood** [comment]
ImagePicker used to be included in RCTImage lib, but is now in RCTCemeraRoll. You need to include the RCTCameraRoll.xcodeproj in your project Libraries, and then make sure libRCTCameraRoll.a is included under "Link Binary With Libraries" in the Build Phases tab.

**Comment by dvcrn** [comment]
Oh I didn't know that! That would explain things. Thanks for the speedy answer.
