### ISSUE TITLE
`cancelAnimationFrame` does not work if `callback` uses `setState`

### ISSUE THREAD

**Issue by szmarczak** [facebook/react-native#39492]
### Description

Happens most of the time.

### React Native Version

0.72.4

### Output of `npx react-native info`

```
> npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600 6-Core Processor              "
  Memory: 16.28 GB / 31.91 GB
Binaries:
  Node:
    version: 20.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.7.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.9971841
  Visual Studio:
    - 17.5.33424.131 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.16.1
    path: C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

Create an Expo project using the code below.

1. Remove `foo` from `App.js`.
2. Ticks are still being logged.

If it stops logging immediately, add some string to `text`, SAVE (hot-reload), remove it, SAVE (hot-reload). It may be required to repeat this 5-10 times, but happens after all.

### Snack, screenshot, or link to a repository

https://gist.github.com/szmarczak/10680a2bcef82f89de2e764ee96a16ea

**Comment by szmarczak** [comment]
Stupid bot.

**Comment by groot007** [comment]
@szmarczak I've checked this on expo sandbox and cannot reproduce it here [sandbox](https://snack.expo.dev/@kolia_stanis/sandbox)

**Comment by szmarczak** [comment]
@groot007 Don't use Snack, it's like another environment.

Clone this repo: https://github.com/szmarczak/rn-raf-bug
Running `npm run start` and modifying the `App.tsx` file as previously mentioned triggers the bug for me.
