### ISSUE TITLE
[iOS] how can i overwrite system font size setting?

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#3949]
We are working on a reading app and we want to keep the font size same regardless of user settings in general > accessibility > larger text/bold text. Is there a settings somewhere we can use or we have to go native to find the scalling?

**Comment by ide** [comment]
You could set `allowFontScaling={false}` on the Text components whose size you would like to keep constant. To generalize this more widely, you could create a custom component called `FixedText` that simply renders a `Text` component with `allowFontScaling={false}` (and forwards all other props) and use `<FixedText>` throughout your app code.

**Comment by seph14** [comment]
ah, ok, i thought this was for handling automatically font size shrinking when the text component is not big enough to fit in all the texts. Thanks!

**Comment by seph14** [comment]
just another thought, if this is the case, shouldn't it be default to false? I think that might be the general case

**Comment by ide** [comment]
The general case should support accessibility.
