### ISSUE TITLE
CameraRoll / Cannot read property 'getPhotos' of undefined

### ISSUE THREAD

**Issue by klausbreyer** [facebook/react-native#3950]
Hi there, 

I wanted to use the CameraRoll. But it does not work. 

```
   CameraRoll.getPhotos({first: 2,}, 
            function(data) { // richtiger callback
            console.log(data);
        }, function(err) { // error callback
            console.log(err);
        });
        
```

this is my header: 
```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  View,
  Animated,
  StatusBarIOS,
  CameraRoll,
  TouchableOpacity,
  TouchableWithoutFeedback,
  Text,
  StyleSheet,
  NavigatorIOS
} = React;

```

are there any more requirements I possibly missed? 

 "react-native": "^0.13.2",

**Comment by whokilledtheelectricmonk** [comment]
For Android: #3901 
For iOS: You need to link the libraries in XCode.

**Comment by JakeRawr** [comment]
@klausbreyer 

https://thebhwgroup.com/blog/accessing-iphone-camera-roll-images-react-native

I followed this tutorial on how to use Camera Roll. I've only tried it on iOS. I'm not certain that Android works the same

**Comment by ide** [comment]
@whokilledtheelectricmonk thanks for answering!

**Comment by CarlosLCervantes** [comment]
More info on linking the lib:
You have to import node_modules/react-native/Libraries/CameraRoll/RCTCameraRoll.xcodeproj

**Comment by adamkdean** [comment]
FWIW, https://facebook.github.io/react-native/docs/linking-libraries-ios.html – Manual Step 2.

![image](https://cloud.githubusercontent.com/assets/1639527/17990151/38328fc8-6b2b-11e6-96f7-88d810af2257.png)

**Comment by zk** [comment]
For those running into problems after correctly linking the `libRCTCameraRoll.a` library, don't forget to correctly set [NSPhotoLibraryUsageDescription](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW17) in `Info.plist`.

**Comment by paulsoh** [comment]
I followed the instructions here:
https://facebook.github.io/react-native/docs/linking-libraries-ios.html

If I add libRCTCameraRoll.a it puts out an error saying that 
```
Unable to run command 'Libtool libRCTCameraRoll.a' - this target might include its own product.
```
Can anyone point out what I'm missing?

**Comment by lmadigan** [comment]
Hi @paulsoh did you find the solution to this?
