### ISSUE TITLE
[Layout] `text-overflow:ellipsis` in a View ?

### ISSUE THREAD

**Issue by mc-zone** [facebook/react-native#3951]
I already know there is a feature `numberOfLines` used on `Text`. 

But it can't be work when I have a RICH-TEXT paragraph which includes some `Image` elements.

So I can't make a pretty text ellipsis on the line end. Then `overflow:hidden` is not always suitable in this case, it might result in text truncation. 

For example:
![2015-11-06 9 02 05](https://cloud.githubusercontent.com/assets/4403937/10997645/ac55c2d8-84c9-11e5-82cc-babe58d5edf5.png)

The best feature should like: 人 (求...

Does anybody know a better way to solve it?

**Comment by gangstaJS** [comment]
For me, this question is also relevant

**Comment by wtfil** [comment]
You can achieve same effect with  ```<Text numberOfLines ={1}>long long text<Text>```

**Comment by Kureev** [comment]
@facebook-github-bot answered

**Comment by Athaphian** [comment]
This was NOT answered, because the original question stated that this is a problem when NOT using Text and the solution is based on the usage of Text... I also want ellipsis on View, not on Text.
