### ISSUE TITLE
Support slashed-zero font-variant

### ISSUE THREAD

**Issue by JackCA** [facebook/react-native#39523]
### Description

The [slashed-zero font-variant property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric) is not currently supported. It's absence does not appear to be a technical limitation (but I may be wrong). The documentation does not claim to support this.

Note: _This was originally a suggestion in the discussions-and-proposals repo [here](https://github.com/react-native-community/discussions-and-proposals/discussions/713), but was encouraged to bring up here_ 

### React Native Version

0.70.13

### Output of `npx react-native info`

```
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.98 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /private/var/folders/6w/2pyynk1d6vn3fpf65dvrzybw0000gp/T/xfs-aaad0225/node
    Yarn: 3.2.4 - /private/var/folders/6w/2pyynk1d6vn3fpf65dvrzybw0000gp/T/xfs-aaad0225/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /Users/j/.rvm/gems/ruby-2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: ^11.0.1 => 11.0.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.13 => 0.70.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    ```

### Steps to reproduce

Attempt to use `slashed-zero` fontVariant:

```jsx
<Text style={{fontVariant: ['slashed-zero']}}> Foo </Text>
```

and you'll get this error:

```
Invalid RCTFontVariantDescriptor 'slashed-zero'. should be one of: (
    "lining-nums",
    "oldstyle-nums",
    "proportional-nums",
    "small-caps",
    "tabular-nums"
)
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/9bAyZKk8X?platform=ios

**Comment by JackCA** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.70.13. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

I have updated to `0.70.13`

**Comment by JackCA** [comment]
Bumping

**Comment by im-adithya** [comment]
+1, this would be useful to us, can anyone atleast reopen this issue? cc @cortinico
