### ISSUE TITLE
[Memory Issue] When I use the repository code directly in the project, the app consumes memory every second.

### ISSUE THREAD

**Issue by rocman** [facebook/react-native#3953]
However, when I just use the original one generated by "react-native init", the case does not happen. I just wonder what's the key difference?

**Comment by rocman** [comment]
I've just confirmed that the memory issue does exist.

When I created a project by 'react-native init AwesomeProject', a project with the 'original' react-native node-module was in use. And in this case, the memory consumes slowly, the memory usage stay at a level.

And then I deleted the react-native folder in node-modules, and got the 'master' code in place by 'git clone https://github.com/facebook/react-native.git' & 'cd react-native && npm install'. When the 'master' code got ready, I run the project again and found the memory is consuming fast, the usage got more and more, second by second.

**Comment by ide** [comment]
Is this on iOS or Android? And is the app code doing anything?

**Comment by rocman** [comment]
It's on iOS simulator, and doing nothing

**Comment by ide** [comment]
cc @tadeuzagallo @nicklockwood

**Comment by rocman** [comment]
I guess the case might be caused by the systrace. When I clicked "stop systrace" on the menu, the memory stopped consuming fast.

**Comment by tadeuzagallo** [comment]
Yes, I was literally just checking and there doesn't seem to be any memory leak like that, however, if you have systrace running it will keep profiling information in memory, which would definitely look like that (if you want to know more about systrace's memory usage check my comment on #1452, some numbers might have changed, but the overall idea should still apply).

**Comment by ide** [comment]
@tadeuzagallo thanks for your answer.
@rocman do you want to close this issue?

**Comment by rocman** [comment]
Thanks @tadeuzagallo for the answer.

I did want to believe the case reasons from the systrace. However, by chance, I found with the git branch "0.14 stable" the case did not happened, but with the git branch "0.15 stable" the case did. Both with the systrace not running.

I've double checked the above, and you can try it yourselves. So It seems that some changes since "0.14 stable" make the case happen, and we'd better find them out.

**Comment by tadeuzagallo** [comment]
Are you running your iOS app in profile mode and your JavaScript with `dev=false`? How fast is the memory growing? Did you try triggering a memory warning?

**Comment by rocman** [comment]
As you can see in my description, I did the test with a new project, and did nothing more. If the case is due to the things you mentioned, I guess they at least should not be the default settings.

**Comment by rocman** [comment]
Answering the second question: the memory grows about 100k per second with '0.15 stable', while grows little with '0.14 stable'.

**Comment by NishanthShankar** [comment]
Having the same issue. The memory used seems to grow linearly. Testing a basic code on iOS device

**Comment by tadeuzagallo** [comment]
> Are you running your iOS app in profile mode and your JavaScript with `dev=false`?

**Comment by ide** [comment]
We were seeing a similar effect in the iOS UIExplorer with dev=true and profiling turned off. Didn't investigate where the leak was coming from but it was easy to repro.

**Comment by tadeuzagallo** [comment]
It's related to the WebSocket heartbeat that keeps trying to connect to React dev tools, it's debug only though, I'm looking into it.

**Comment by rocman** [comment]
👏🎉🎊👍🏼

**Comment by ide** [comment]
Awesome, thanks @tadeuzagallo.

**Comment by NishanthShankar** [comment]
Has this been merged with 0.16.0-rc? The travis build for this has commit seems to have failed.

**Comment by boldkhuu** [comment]
This issue is still occurring on initial project with 0.16.0 (dev=true).

**Comment by tadeuzagallo** [comment]
This commit is not in `v0.16.0`, should be in the next release.

**Comment by boldkhuu** [comment]
@tadeuzagallo Got it. Thank you.

**Comment by rclai** [comment]
When will this fix ship? It's almost impossible to test with an actual device without it dying of memory starvation in the next few minutes.

**Comment by tadeuzagallo** [comment]
@rclai The new version ships by the end of next week. You can simply generate the JavaScript with `dev=false` in the mean time.

**Comment by mkonicek** [comment]
The fix will ship in 0.17.

**Comment by mkonicek** [comment]
Here's the commit: https://github.com/facebook/react-native/commit/ea96a7edb8a17fbcc57db99217783302bb790056
