### ISSUE TITLE
can not Archive at iOS using RN 0.72.4

### ISSUE THREAD

**Issue by irfanismaya20** [facebook/react-native#39550]
### Description

main.jsbundle does not exist

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 365.50 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.1
    path: ~/.nvm/versions/node/v18.12.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.12.1/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.1/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. open file restuque.xcworkspace
2. choose menu product in Xcode and choose sub menu archive
<img width="474" alt="Screenshot 2023-09-20 at 13 53 42" src="https://github.com/facebook/react-native/assets/12542123/3251f2af-4bb0-46bc-823c-78169ae441c9">

### Snack, screenshot, or link to a repository

<img width="474" alt="Screenshot 2023-09-20 at 13 53 42" src="https://github.com/facebook/react-native/assets/12542123/27e27057-c867-4c43-9b56-e95a1bb8324a">

**Comment by annx10kn** [comment]
same issue

**Comment by Moustafa-mahmaed** [comment]
same issue here

**Comment by emil-malmgaard-rasmussen** [comment]
Why is this closed? Getting same error...

File /Users/[USER]/Library/Developer/Xcode/DerivedData/[APP_NAME]-hkkxnxtxugqfssgyivbmjcqyhpow/Build/Intermediates.noindex/ArchiveIntermediates/[APP_NAME]/BuildProductsPath/Release-iphoneos/[APP_NAME]app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues
