### ISSUE TITLE
Two instances of app could exist if app is opened via Google Files app

### ISSUE THREAD

**Issue by MykolaSauliak** [facebook/react-native#39553]
### Description

it could be a problem with Google Files app, but will post here to investigate if someone had similar problem
See screenshots
Firsly I have tried to open file ( that app could open ) from Google Files and our app is launched inside Google Files app (new android task is not created). Then I could open app from Home screen and two app instances could exist (see screenshot).
We couldn't change launchMode="singleTask" (and it is default value by the way), changing other manifest [attributes](https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManagingTasks) seems doesn't help.

### React Native Version
version 0.72.4
version 0.67

### Output of `npx react-native info`

IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
Languages:
  Java:
    version: 11.0.15
  Ruby:
    version: 2.7.6
npmPackages:
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- setup bare react-native app
- add next intent-filter

```
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="application/octet-stream"/>
            </intent-filter>

```

try to open file from Google Files via this app

### Snack, screenshot, or link to a repository

Example project:

- https://github.com/MykolaSauliak/two-instances-rn-app-bug

![Screenshot_20230920_131827_One UI Home~2](https://github.com/facebook/react-native/assets/16925900/51e4bdab-625c-4da0-9f0e-0127e8f66077)

![Screenshot_20230920_131840_One UI Home~2](https://github.com/facebook/react-native/assets/16925900/42aa2cb9-ea82-40c7-a326-c90c3cdf773e)

**Comment by MykolaSauliak** [comment]
> ### Description
> 
> it could be a problem with Google Files app, but will post here to investigate if someone had similar problem See screenshots Firsly I have tried to open file ( that app could open ) from Google Files and our app is launched inside Google Files app (new android task is not created). Then I could open app from Home screen and two app instances could exist (see screenshot). We couldn't change launchMode="singleTask" (and it is default value by the way), changing other manifest [attributes](https://developer.android.com/guide/components/activities/tasks-and-back-stack#ManagingTasks) seems doesn't help.
> ### React Native Version
> 
> v0.72.4
> ### Output of `npx react-native info`
> 
> IDEs: Android Studio: 2022.2 AI-222.4459.24.2221.10121639 Xcode: version: 14.2/14C18 Languages: Java: version: 11.0.15 Ruby: version: 2.7.6 npmPackages: react: installed: 18.2.0 wanted: 18.2.0 react-native: installed: 0.72.4 wanted: 0.72.4 react-native-macos: Not Found npmGlobalPackages: "_react-native_": Not Found Android: hermesEnabled: true newArchEnabled: false iOS: hermesEnabled: true newArchEnabled: false
> ### Steps to reproduce
> 
>     * setup bare react-native app
> 
>     * add next intent-filter
> 
> 
> ```
>             <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <data android:mimeType="application/octet-stream"/>
>             </intent-filter>
> ```
> 
> try to open file from Google Files via this app
> ### Snack, screenshot, or link to a repository
> 
> Example project:
> 
>     * https://github.com/MykolaSauliak/two-instances-rn-app-bug
> 
> 
> ![Screenshot_20230920_131827_One UI Home~2](https://user-images.githubusercontent.com/16925900/269252914-51e4bdab-625c-4da0-9f0e-0127e8f66077.jpg)
> 
> ![Screenshot_20230920_131840_One UI Home~2](https://user-images.githubusercontent.com/16925900/269252915-42aa2cb9-ea82-40c7-a326-c90c3cdf773e.jpg)

reproduced on v0.67 and latest one (probably for all versions)

**Comment by Ldoppea** [comment]
Hi,

We encountered the same problem in my team's project.

The solution provided in this SO thread seems to be a good workaround: https://stackoverflow.com/a/57751301

>  You could try detecting if the flag is missing or if your activity is not the task root and launching a new activity and killing the one that is part of the Google Files task. Something like this:

```java
@Override
protected void onCreate(Bundle state) {
    super.onCreate(state);
    setContentView(R.layout.main);

    if (!isTaskRoot()) { // Or check getIntent().getFlags() for SINGLE_INSTANCE
        Intent newIntent = new Intent(getIntent());
        newIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        startActivity(newIntent);
        finish();
    }
}
```

This resolves our problem (but we are still doing some regression tests)

Our understanding is that any app can [override the launchMode](https://developer.android.com/guide/components/activities/tasks-and-back-stack#IntentFlagsForTasks) when opening an intent. Maybe Google Files is doing this.

**Comment by stefoid** [comment]
Can I necro this?  

I am using react-native-share-menu which has the code suggested above . (see line 96)   [https://github.com/Expensify/react-native-share-menu/blob/master/android/src/main/java/com/meedan/ShareMenuModule.java](url)

This doesnt always work.  It seems to crash/hang my app when it launches cold, and if it was already running, when the app is brought to the foreground, it is not in the same state it was  before - it seems somehow 'reset' .   Without this code - the behaviour is as the OP has complained above.  So it seems we need this 'hack' to get around something that the Google Files app is doing.  But the hack is not reliable.

A baffling thing to me is that the behaviour is fine on emulators, but goes wrong (as above) on the actual device - the same device and android version that works on the emulator - so what could account for the difference in behaviour?

here is my stack exchange issue with more information:  https://stackoverflow.com/questions/78209973/android-sharing-files-from-other-apps-to-my-app-react-native-but-is-probably
