### ISSUE TITLE
Xcode 15 and iOS 17 crash on start

### ISSUE THREAD

**Issue by gabrielmaldi** [facebook/react-native#39562]
### Description

I've been closely following #37748 but nothing there has fixed my issue. When I use Xcode 15 to deploy my RN app to my iPhone (14 Pro Max) running iOS 17 GM, the app crashes on start (see attached screenshot).

This seems to be exactly what happens to another commenter in the issue I referenced: https://github.com/facebook/react-native/issues/37748#issuecomment-1727836506

### React Native Version

0.71.12

### Output of `npx react-native info`

```
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 87.09 MB / 16.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /Users/gabrielmaldi/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Electric Eel 2022.1.1 Patch 2 Electric Eel 2022.1.1 Patch 2
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.12 => 0.71.12
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Build the app using Xcode 15 and deploy to an iPhone running iOS 17
2. The app crashes on start (everything worked perfectly with Xcode 14.3.1).

### Snack, screenshot, or link to a repository

<img width="1440" alt="Screenshot 2023-09-19 at 13 20 43" src="https://github.com/facebook/react-native/assets/3728897/48e0b2f4-4f78-48e8-8384-e2b28e282e4a">

**Comment by imamrobani** [comment]
same here, what is the solution?

**Comment by gabrielmaldi** [comment]
@imamrobani, for me it was this: https://github.com/mrousavy/react-native-vision-camera/issues/1802#issuecomment-1728167110

**Comment by imamrobani** [comment]
> @imamrobani, for me it was this: [mrousavy/react-native-vision-camera#1802 (comment)](https://github.com/mrousavy/react-native-vision-camera/issues/1802#issuecomment-1728167110)

ah I see, thanks a lot, it's work for me.
because my error is also the same as your screenshot

Does this only happen in xcode15? 
because before I used Xcode 14 it was fine
