### ISSUE TITLE
Random crash on iOS - EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)

### ISSUE THREAD

**Issue by marcoizzo** [facebook/react-native#39573]
### Description

Hi guys,

I'm facing random crashed on iOS and unfortunately I'm not able to reproduce manually
I was able to get the stacktrace from crashlytics and only recently the crash appears during detox test.

I attach all the material that I have

Can anyone faced similar problem?
Thank you

### React Native Version

0.70.13

### Output of `npx react-native info`

```
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 77.66 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.1.0 
    react-native: ^0.70.13 => 0.70.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

Unable to identify the steps

### Snack, screenshot, or link to a repository

![Screenshot 2023-09-21 alle 11 27 48](https://github.com/facebook/react-native/assets/13518657/652feb8f-ea97-4ae4-ad4f-94821b800a92)

[stacktrace.txt](https://github.com/facebook/react-native/files/12682897/stacktrace.txt)

[detox_stacktrace.txt](https://github.com/facebook/react-native/files/12682936/detox_stacktrace.txt)

**Comment by cortinico** [comment]
> I'm facing random crashed on iOS and unfortunately I'm not able to reproduce manually

I'm unsure how we can help you here without a proper reproducer sadly

**Comment by PetroPavlenko** [comment]
hey @marcoizzo 
[this](https://github.com/facebook/react-native/issues/39562) might be related

**Comment by marcoizzo** [comment]
Thanks for the response @PetroPavlenko, I don't think so because that issue is on start app (mine randomly during the usage of the app) and it's related to a library that I'm not using

Do you know if there is a smart way to get more detailed logs?

**Comment by PetroPavlenko** [comment]
looks like you posted everything.
random error without reproduction steps is not that easy to fix.
But currently there is issue with xcode 15 and ios 17 + RN build. Maybe your issue is on native ios side ?

**Comment by PetroPavlenko** [comment]
p.s. here is [issue](https://github.com/facebook/react-native/issues/37748#issuecomment-1727940094) I'm talking about

**Comment by marcoizzo** [comment]
I was able to get the error during test automation process:

Hope can help someone to suggest me some fix... 

`
The pending request #387 ("invoke") has been rejected due to the following error:

    The app has crashed, see the details below:

    Signal 11 was raised
    (
        0   Detox                               0x0000000109ff5cc0 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 36
        1   Detox                               0x0000000109ff88d0 __DTXHandleCrash + 440
        2   Detox                               0x0000000109ff8f00 __DTXHandleSignal + 72
        3   libsystem_platform.dylib            0x0000000108defc60 _sigtramp + 52
        4   hermes                              0x000000010a2a6c48 facebook::jsi::JSError::~JSError() + 1088444
        5   Curriculify                         0x00000001043c0ff0 facebook::hermes::inspector::Inspector::getScriptInfoFromTopCallFrame() + 276
        6   Curriculify                         0x00000001043c11d0 facebook::hermes::inspector::Inspector::addCurrentScriptToLoadedScripts() + 36
        7   Curriculify                         0x00000001043da7a8 facebook::hermes::inspector::InspectorState::RunningDetached::didPause(std::__1::unique_lock<std::__1::mutex>&) + 204
        8   Curriculify                         0x00000001043c3390 facebook::hermes::inspector::Inspector::didPause(facebook::hermes::debugger::Debugger&) + 88
        9   hermes                              0x000000010a197810 facebook::hermes::debugger::Command::eval(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, unsigned int) + 1144
        10  hermes                              0x000000010a2a25dc facebook::jsi::JSError::~JSError() + 1070416
        11  hermes                              0x000000010a2a1a18 facebook::jsi::JSError::~JSError() + 1067404
        12  hermes                              0x000000010a1c5194 facebook::jsi::JSError::~JSError() + 164104
        13  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        14  hermes                              0x000000010a20a9bc facebook::jsi::JSError::~JSError() + 448816
        15  hermes                              0x000000010a28b64c facebook::jsi::JSError::~JSError() + 976320
        16  hermes                              0x000000010a28ba0c facebook::jsi::JSError::~JSError() + 977280
        17  hermes                              0x000000010a25cb4c facebook::jsi::JSError::~JSError() + 785088
        18  hermes                              0x000000010a275abc facebook::jsi::JSError::~JSError() + 887344
        19  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        20  hermes                              0x000000010a1a4638 facebook::jsi::JSError::~JSError() + 30124
        21  hermes                              0x000000010a2765a0 facebook::jsi::JSError::~JSError() + 890132
        22  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        23  hermes                              0x000000010a1c4770 facebook::jsi::JSError::~JSError() + 161508
        24  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        25  hermes                              0x000000010a1a5d34 facebook::jsi::JSError::~JSError() + 36008
        26  hermes                              0x000000010a276898 facebook::jsi::JSError::~JSError() + 890892
        27  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        28  hermes                              0x000000010a1c4770 facebook::jsi::JSError::~JSError() + 161508
        29  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        30  hermes                              0x000000010a1a5d34 facebook::jsi::JSError::~JSError() + 36008
        31  hermes                              0x000000010a276898 facebook::jsi::JSError::~JSError() + 890892
        32  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        33  hermes                              0x000000010a1c4770 facebook::jsi::JSError::~JSError() + 161508
        34  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        35  hermes                              0x000000010a1a6764 facebook::jsi::JSError::~JSError() + 38616
        36  hermes                              0x000000010a24aa0c facebook::jsi::JSError::~JSError() + 711040
        37  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        38  hermes                              0x000000010a1c4770 facebook::jsi::JSError::~JSError() + 161508
        39  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        40  hermes                              0x000000010a1a5d34 facebook::jsi::JSError::~JSError() + 36008
        41  hermes                              0x000000010a1a4638 facebook::jsi::JSError::~JSError() + 30124
        42  hermes                              0x000000010a2765a0 facebook::jsi::JSError::~JSError() + 890132
        43  hermes                              0x000000010a1a5a8c facebook::jsi::JSError::~JSError() + 35328
        44  hermes                              0x000000010a1c4770 facebook::jsi::JSError::~JSError() + 161508
        45  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        46  hermes                              0x000000010a1a5d34 facebook::jsi::JSError::~JSError() + 36008
        47  hermes                              0x000000010a1a559c facebook::jsi::JSError::~JSError() + 34064
        48  hermes                              0x000000010a1c4794 facebook::jsi::JSError::~JSError() + 161544
        49  hermes                              0x000000010a1c3c70 facebook::jsi::JSError::~JSError() + 158692
        50  hermes                              0x000000010a1a5d34 facebook::jsi::JSError::~JSError() + 36008
        51  hermes                              0x000000010a1a559c facebook::jsi::JSError::~JSError() + 34064
        52  hermes                              0x000000010a18a9d0 facebook::hermes::HermesRuntime::rootsListLength() const + 12584
        53  Curriculify                         0x00000001043b8224 facebook::jsi::RuntimeDecorator<facebook::jsi::Runtime, facebook::jsi::Runtime>::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 76
        54  Curriculify                         0x00000001043b68f4 facebook::jsi::WithRuntimeDecorator<facebook::react::(anonymous namespace)::ReentrancyCheck, facebook::jsi::Runtime, facebook::jsi::Runtime>::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 88
        55  Curriculify                         0x00000001032b838c facebook::jsi::Function::call(facebook::jsi::Runtime&, facebook::jsi::Value const*, unsigned long) const + 100
        56  Curriculify                         0x00000001032b831c facebook::jsi::Function::call(facebook::jsi::Runtime&, std::initializer_list<facebook::jsi::Value>) const + 112
        57  Curriculify                         0x000000010410ad3c facebook::jsi::Value facebook::jsi::Function::call<double const&, facebook::jsi::Value>(facebook::jsi::Runtime&, double const&, facebook::jsi::Value&&) const + 184
        58  Curriculify                         0x000000010410aab8 facebook::react::JSIExecutor::invokeCallback(double, folly::dynamic const&) + 188
        59  Curriculify                         0x000000010391cdac facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3::operator()(facebook::react::JSExecutor*) const + 272
        60  Curriculify                         0x000000010391cc90 decltype(std::declval<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3&>()(std::declval<facebook::react::JSExecutor*>())) std::__1::__invoke[abi:v160006]<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3&, facebook::react::JSExecutor*>(facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3&, facebook::react::JSExecutor*&&) + 36
        61  Curriculify                         0x000000010391cc3c void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3&, facebook::react::JSExecutor*>(facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3&, facebook::react::JSExecutor*&&) + 32
        62  Curriculify                         0x000000010391cc10 std::__1::__function::__alloc_func<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3, std::__1::allocator<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3>, void (facebook::react::JSExecutor*)>::operator()[abi:v160006](facebook::react::JSExecutor*&&) + 36
        63  Curriculify                         0x000000010391b9a4 std::__1::__function::__func<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3, std::__1::allocator<facebook::react::NativeToJsBridge::invokeCallback(double, folly::dynamic&&)::$_3>, void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*&&) + 36
        64  Curriculify                         0x0000000103925a04 std::__1::__function::__value_func<void (facebook::react::JSExecutor*)>::operator()[abi:v160006](facebook::react::JSExecutor*&&) const + 76
        65  Curriculify                         0x0000000103925984 std::__1::function<void (facebook::react::JSExecutor*)>::operator()(facebook::react::JSExecutor*) const + 36
        66  Curriculify                         0x0000000103925950 facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8::operator()() const + 92
        67  Curriculify                         0x00000001039258e8 decltype(std::declval<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>()()) std::__1::__invoke[abi:v160006]<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&) + 24
        68  Curriculify                         0x00000001039258a0 void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&>(facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8&) + 24
        69  Curriculify                         0x000000010392587c std::__1::__function::__alloc_func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()[abi:v160006]() + 28
        70  Curriculify                         0x0000000103924410 std::__1::__function::__func<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8, std::__1::allocator<facebook::react::NativeToJsBridge::runOnExecutorQueue(std::__1::function<void (facebook::react::JSExecutor*)>)::$_8>, void ()>::operator()() + 28
        71  Curriculify                         0x00000001029b4a20 std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const + 68
        72  Curriculify                         0x00000001029b2110 std::__1::function<void ()>::operator()() const + 24
        73  Curriculify                         0x000000010343df2c facebook::react::tryAndReturnError(std::__1::function<void ()> const&) + 24
        74  Curriculify                         0x000000010346793c facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 36
        75  Curriculify                         0x000000010346c3b4 facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1::operator()() const + 80
        76  Curriculify                         0x000000010346c358 decltype(std::declval<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>()()) std::__1::__invoke[abi:v160006]<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&) + 24
        77  Curriculify                         0x000000010346c310 void std::__1::__invoke_void_return_wrapper<void, true>::__call<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&>(facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1&) + 24
        78  Curriculify                         0x000000010346c2ec std::__1::__function::__alloc_func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()[abi:v160006]() + 28
        79  Curriculify                         0x000000010346affc std::__1::__function::__func<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1, std::__1::allocator<facebook::react::RCTMessageThread::runOnQueue(std::__1::function<void ()>&&)::$_1>, void ()>::operator()() + 28
        80  Curriculify                         0x00000001029b4a20 std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const + 68
        81  Curriculify                         0x00000001029b2110 std::__1::function<void ()>::operator()() const + 24
        82  Curriculify                         0x00000001034676a4 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 48
        83  DetoxSync                           0x0000000109f31254 ____detox_sync_CFRunLoopPerformBlock_block_invoke + 44
        84  CoreFoundation                      0x00000001803ee464 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
        85  CoreFoundation                      0x00000001803edbac __CFRunLoopDoBlocks + 352
        86  CoreFoundation                      0x00000001803e8a78 __CFRunLoopRun + 2364
        87  CoreFoundation                      0x00000001803e7d28 CFRunLoopRunSpecific + 572
        88  Curriculify                         0x0000000103418160 +[RCTCxxBridge runRunLoop] + 736
        89  DetoxSync                           0x0000000109f33588 swz_runRunLoopThread + 276
        90  Foundation                          0x0000000180dfe27c __NSThread__start__ + 720
        91  libsystem_pthread.dylib             0x0000000109d674c0 _pthread_start + 104
        92  libsystem_pthread.dylib             0x0000000109d626f0 thread_start + 8
    )
`

**Comment by lucaswitch** [comment]
Having this weird issue too, on IOs only.
@marcoizzo were you able to fix it?

**Comment by marcoizzo** [comment]
Unfortunately no... my last tentative will be in upgrading RN, but still not planned

**Comment by lucaswitch** [comment]
Having this exact issue on 0.72.7. Also randomly along the usage of the application. Only ocurring on iOS

**Comment by lucaswitch** [comment]
Still not working on 0.73

**Comment by lucaswitch** [comment]
@marcoizzo Do you use redux or something similar, found some memory leaks within my application that "could" make this happen.

**Comment by marcoizzo** [comment]
Yes I use redux

**Comment by lucaswitch** [comment]
@marcoizzo having same stack trace as yours and same behaviour.
I'll try to disable hermes for a while and see if the crashes dissapears. 

![Screenshot 2023-12-29 at 09 54 04](https://github.com/facebook/react-native/assets/29023475/1574453a-6c56-402c-9807-0ed411c5d860)

**Comment by lucaswitch** [comment]
Still not able to solve this issue.

**Comment by marcoizzo** [comment]
I jumped from RN 0.71 to RN0.73.2 (upgrade also many other libraries) and now the problem seems not anymore present. ¯\_(ツ)_/¯

**Comment by lucaswitch** [comment]
Happy that it works for you @marcoizzo. Still struggling to solve it. Can you share your package.json?

**Comment by marcoizzo** [comment]
@lucaswitch here you are

```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "aab": "npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle && cd android && ./gradlew clean && ./gradlew bundleRelease",
    "test-android-build": "react-native start",
    "test-android": "detox test --configuration android.emu.debug",
    "test-ios": "detox test --configuration ios.sim.debug",
    "postinstall": "patch-package",
    "lint": "eslint ."
  },
  "reactNativePermissionsIOS": [
    "AppTrackingTransparency"
  ],
  "dependencies": {
    "@expo/react-native-action-sheet": "^4.0.1",
    "@gorhom/bottom-sheet": "^4.6.0",
    "@invertase/react-native-apple-authentication": "^2.3.0",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-community/slider": "^4.5.0",
    "@react-native-firebase/analytics": "^18.7.3",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/app-check": "^18.7.3",
    "@react-native-firebase/auth": "^18.7.3",
    "@react-native-firebase/crashlytics": "^18.7.3",
    "@react-native-firebase/database": "^18.7.3",
    "@react-native-firebase/firestore": "^18.7.3",
    "@react-native-firebase/functions": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",
    "@react-native-firebase/remote-config": "^18.7.3",
    "@react-native-firebase/storage": "^18.7.3",
    "@react-native-google-signin/google-signin": "^11.0.0",
    "@react-navigation/elements": "^1.3.21",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@reduxjs/toolkit": "^2.0.1",
    "collapse-white-space": "^2.1.0",
    "eventemitter3": "^5.0.1",
    "i18n-js": "^4.3.2",
    "immer": "^10.0.3",
    "lottie-react-native": "^6.5.1",
    "moment": "^2.30.1",
    "pdf-lib": "^1.17.1",
    "react": "^18.2.0",
    "react-native": "^0.73.2",
    "react-native-actions-shortcuts": "^1.0.1",
    "react-native-animatable": "^1.4.0",
    "react-native-autoheight-webview": "^1.6.5",
    "react-native-base64": "^0.2.1",
    "react-native-blob-util": "^0.19.6",
    "react-native-bootsplash": "^5.2.2",
    "react-native-date-picker": "^4.3.5",
    "react-native-device-info": "^10.12.0",
    "react-native-document-picker": "^9.1.0",
    "react-native-draggable-flatlist": "^4.0.1",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.14.0",
    "react-native-google-mobile-ads": "^12.9.0",
    "react-native-handlebars": "^5.0.0-alpha.1",
    "react-native-haptic-feedback": "^2.2.0",
    "react-native-image-crop-picker": "^0.40.2",
    "react-native-image-viewing": "^0.2.2",
    "react-native-inappbrowser-reborn": "^3.7.0",
    "react-native-keyboard-accessory": "^0.1.16",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-launch-arguments": "^4.0.2",
    "react-native-localize": "^3.0.5",
    "react-native-mail": "^6.1.1",
    "react-native-notification-badge": "^1.0.5",
    "react-native-pell-rich-editor": "^1.9.0",
    "react-native-permissions": "^4.0.4",
    "react-native-prompt-android": "^1.1.0",
    "react-native-purchases": "^7.6.0",
    "react-native-rate": "^1.2.12",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "^3.6.1",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "^4.8.2",
    "react-native-screens": "^3.29.0",
    "react-native-share": "^10.0.2",
    "react-native-signature-canvas": "^4.7.1",
    "react-native-svg": "^14.1.0",
    "react-native-touchable-scale": "^2.2.0",
    "react-native-ui-lib": "^7.6.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-version-number": "^0.3.6",
    "react-native-webview": "^13.6.4",
    "react-redux": "^9.0.4",
    "redux": "^5.0.1",
    "rn-placeholder": "^3.0.3",
    "semver": "^7.5.4",
    "use-debounce": "^10.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@babel/preset-env": "^7.20.2",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "^0.73.19",
    "@react-native/eslint-config": "^0.73.2",
    "@react-native/metro-config": "^0.73.3",
    "@react-native/typescript-config": "^0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "detox": "^20.14.8",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "patch-package": "^8.0.0",
    "prettier": "^2.8.8",
    "react-native-codegen": "^0.0.7",
    "react-native-svg-transformer": "^1.3.0",
    "react-test-renderer": "^18.2.0",
    "typescript": "^5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

```

**Comment by lucaswitch** [comment]
Thank you @marcoizzo, i was able to solve it by removing a jsi dependency.

**Comment by faizanmansoori1** [comment]
@marcoizzo @lucaswitch I have this same error
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x3d68 objc_release + 16
1  SafariServices                 0x65d38 <redacted> + 40
2  UIKitCore                      0x2ff978 <redacted> + 2176
3  UIKitCore                      0x3447a8 <redacted> + 240
4  UIKitCore                      0x2b2cb0 <redacted> + 140
5  UIKitCore                      0x2b1d1c <redacted> + 128
6  UIKitCore                      0x2b2ea0 <redacted> + 180
7  UIKitCore                      0x2b2aa0 <redacted> + 832
8  UIKitCore                      0x1060598 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ + 36
9  UIKitCore                      0xce148 <redacted> + 636
10 UIKitCore                      0xcd0a4 <redacted> + 436
11 UIKitCore                      0xcc7c0 <redacted> + 196
12 UIKitCore                      0xcc8d4 <redacted> + 472
13 QuartzCore                     0x13474 <redacted> + 232
14 libdispatch.dylib              0x3eac <redacted> + 20
15 libdispatch.dylib              0x126a4 <redacted> + 928
16 libdispatch.dylib              0x122f4 _dispatch_main_queue_callback_4CF + 44
17 CoreFoundation                 0x98bb8 <redacted> + 16
18 CoreFoundation                 0x7a4f0 <redacted> + 1992
19 CoreFoundation                 0x7f37c CFRunLoopRunSpecific + 612
20 GraphicsServices               0x135c GSEventRunModal + 164
21 UIKitCore                      0x39cf58 <redacted> + 888
22 UIKitCore                      0x39cbbc UIApplicationMain + 340
23 Engage Company                 0x8a78 main + 8 (main.m:8)
24 ???                            0x1b31e8dec (Missing)

What does this mean __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ @cortinico
