### ISSUE TITLE
TouchableNativeFeedback slow to animate

### ISSUE THREAD

**Issue by jcsmesquita** [facebook/react-native#3958]
When using TouchableNativeFeedback on Android I noticed the native response is slow. When tapping quickly the native animation isn't noticeable. Anybody experiencing the same issue?

**Comment by astuetz** [comment]
Set the ```delayPressIn``` prop to 0:

```
<TouchableNativeFeedback background={TouchableNativeFeedback.SelectableBackground()} delayPressIn={0}></TouchableNativeFeedback>
```

Also took me a while to figure out - this should definitely be more obvious.
The only problem you then have is that the feedback is shown as soon as you touch the view, even if you just want to scroll a ScrollView for example :( Setting the property to a slightly bigger value and hope that it's long enough to not show up when scrolling is just pure guessing. I think Android handles the motion events on its Views a bit different than RN does at the moment.

**Comment by jcsmesquita** [comment]
I hadn't noticed TouchableNativeFeedback (and the others) are inheriting props from TouchableWithoutFeedback, thanks for the tip! You're right it should be more clear in the docs! Perhaps we could do a PR to fix this?

I tried your suggestion and it works well, you're right about the scrolling though... Maybe open another issue ticket for that?

I could try to create a PR for the doc improvement and close this issue... never done one before though ^^

**Comment by brentvatne** [comment]
Do you have dev mode enabled by any chance? You can disable it through dev settings menu

**Comment by jcsmesquita** [comment]
doesn't seem to make a difference

**Comment by rashmi-chachan** [comment]
TouchableWithoutFeedback, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback take around 3 seconds to respond in react-native android. How can I reduce it??? i have given delayPressIn={0}  delayPressOut={0} also.

**Comment by brentvatne** [comment]
@rashmi-chachan - this must be with dev=true on a very slow device, I have never seen such a huge delay like 3 seconds. @jcsmesquita - is this on device or emulator? which device/emulator? Which app? Is source available somewhere?

**Comment by tomauty** [comment]
If you're by chance using `redux-logger`, make sure that's off in `dev=false` builds.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchablenativefeedback-slow-to-animate

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by yaronlevi** [comment]
I should be documented that delayPressIn is not 0 by default. When using TouchableNativeFeedback the common use case is that you do want the animation to kick in right as you touch the screen.

**Comment by henrikra** [comment]
@yaronlevi Nowadays delayPressIn is 0 by default https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L138

**Comment by iMokhles** [comment]
@henrikra it's [TouchableWithoutFeedback.js#L156](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L156) now
