### ISSUE TITLE
Headers/Public/ReactCommon/react/bridging/Base.h:13:10: fatal error: 'butter/function.h' file not found

### ISSUE THREAD

**Issue by LuckyRoc** [facebook/react-native#39588]
### Description

butter/function.h not found

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M2 Pro
  Memory: 91.19 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.4
    path: /Users/roclucky/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

npx react-native init MyTestAppnpx， Init a project and pod install

### Snack, screenshot, or link to a repository

![Uploading image.png…]()

**Comment by LuckyRoc** [comment]
fabric_enabled is false  why generate FBReactNativeSpecJSI-generated? and  FBReactNativeSpecJSI use react/bridging  but Base.h not found butter/function.h

**Comment by cortinico** [comment]
Duplicates #38520

**Comment by leviduan** [comment]
Still have this issue, anyone have a good idea？
