### ISSUE TITLE
Native module tutorial should mention that synthesize is required

### ISSUE THREAD

**Issue by mpj** [facebook/react-native#396]
This part of the tutorial:
http://facebook.github.io/react-native/docs/nativemodulesios.html#content
![Screenshot](https://www.dropbox.com/s/o0o5ochb3qw5lwj/Sk%C3%A4rmklipp%202015-03-28%2014.21.09.png?dl=1)

Will cause the not-very-helpful error "Unrecognized selector sent to instance 0x7fc546a12b30" bridge is not synthesized, and this needs to be added to CalendarManager.m:

```@synthesize bridge = _bridge;```

It's in the RCTBridgeModule code (https://github.com/facebook/react-native/blob/6500ba7bfbdc2bd8e3301813b3cb606aeea35331/React/Base/RCTBridgeModule.h#L32), but it took me quite some time to figure out because the error message is so weird (or at least to me that has only done a little iOS development before). A lot of the people doing this tutorial are going to be semi-fresh to iOS development.

**Comment by ide** [comment]
This is present in the docs: http://facebook.github.io/react-native/docs/nativemodulesios.html#sending-events-to-javascript

**Comment by naoufal** [comment]
Docs moved to http://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript.
