### ISSUE TITLE
not run react native ios

### ISSUE THREAD

**Issue by MohamedSuja** [facebook/react-native#39609]
### Description

I try to npx react-native run-ios i is not running and it’s showing this error How can I solve this problem

```
    error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening test.xcworkspace.
    Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace test.xcworkspace -configuration Debug -scheme test -destination id=8E4F9416-0C08-4ACA-B41D-D950C2208A66
    
    User defaults from command line:
        IDEPackageSupportUseBuiltinSCM = YES
    
    Prepare packages


........

    
    Computing target dependency graph and provisioning inputs   
    
     The following build commands failed:
            PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/mohammedsuja/Library/Developer/Xcode/DerivedData/test-eabnxomykigrnaepxsyqxilqoeiw/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00018190.sh (in target 'React-rncore' from project 'Pods')
        (1 failure)
```

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 95.53 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "31"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mohammedsuja/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

How can solve this issue 

### Snack, screenshot, or link to a repository

.

**Comment by pasteancalin** [comment]
I have the same issue after upgrading to 0.72.5

**Comment by solazio** [comment]
Same for me on 0.72.5

**Comment by Mugilan-Codes** [comment]
Facing the same issue on `0.72.5`. Had to resort to `system` ruby of my M1 Mac. My teammate could not get it to work and facing the issue, even their code does not work on my machine.

Facing with the below error
```bash
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/<MY_LOCATION>/Library/Developer/Xcode/DerivedData/<PROJECT_NAME>-gablhitnpbbtnrazgkolmxscnmtv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00019AE0.sh (in target 'React-rncore' from project 'Pods')
```

my system ruby is this and working on my system
```bash
➜  ruby -v
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]

➜  rbenv versions
* system (set by /Users/<MY_LOCATION>/<PROJECT_NAME>/.ruby-version)
  2.7.5
  2.7.6
  3.2.0
  3.2.2
```

**Comment by atifumacaxi** [comment]
same error here... Sonoma OS - chip M1

**Comment by biremux3bin** [comment]
some error here. Sonoma OS-chim M2

**Comment by labadcloyd** [comment]
Same error here Sonoma M2

**Comment by zirho** [comment]
it was working fine until I tried to upgrade it to 0.73.0
I fallbacked to 0.72.7 and I could not get it back up running ever again.

<details>
  <summary>System summary </summary>
  
```
System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 151.70 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /var/folders/_x/qtc9_21n1496whg1yth_37dh0000gp/T/yarn--1702781471399-0.7653925783020112/node
  Yarn:
    version: 1.22.21
    path: /var/folders/_x/qtc9_21n1496whg1yth_37dh0000gp/T/yarn--1702781471399-0.7653925783020112/yarn
  npm:
    version: 10.2.3
    path: /opt/homebrew/opt/node@18/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/yj/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-30 | Google APIs ATD ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/yj/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 12.3.0
    wanted: ^12.3.0
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```
</details>

**Comment by mrshahzeb7** [comment]
I cloned again my project now it is working fine 
I tried to update react native to latest version then switched back after that it was not running for iOS!
