### ISSUE TITLE
[Errors] Letting RCTExceptionsManagerDelegate override default behavior

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3960]
As of https://github.com/facebook/react-native/commit/31b5b0ac010d44afe3e742e85c75a9ef9e72a9e0 the delegate no longer can override the default behavior. That is, if there is a delegate its methods run alongside the default behavior. We could replace the whole module wholesale so this isn't a super critical blocker but it'd be nice to preserve the prior functionality/flexibility.

If it's considered a feature to let both the delegate's methods and the default behavior both to run, one proposal is to have the delegate methods return a BOOL saying whether to run the default behavior or not (kind of like `preventDefault` semantics, loosely speaking).

cc @javache would like your input & context here

**Comment by javache** [comment]
Sorry for breaking your stuff :)

To be clear, you don't want any of the default behaviour? The only thing that's really fixed in the new implementation is the redBox call, which is nil in production anyway. The fatal'ing behaviour can be configured through RCTSetFatalHandler.

**Comment by ide** [comment]
> To be clear, you don't want any of the default behaviour?

Yeah, I reimplemented the redbox actually so a way to tell RN "don't worry about this error, I got this" is what I'm looking for.

**Comment by javache** [comment]
Perhaps we could have a boolean flag on RCTExceptionsManager whether to show redboxes?

Also just wondering, how are you disabling the redbox here? https://github.com/facebook/react-native/blob/c1ae4780ceb25fbb350e7f802fa150f4ee30ed74/React/Base/RCTLog.m#L239

Since the redbox is just another bridge module anyway, you could also consider replacing that?

**Comment by ide** [comment]
When handling fatal exceptions, I'd also like to suppress the default behavior of restarting the bridge and take care of that myself.

> Since the redbox is just another bridge module anyway, you could also consider replacing that?

Good idea. I believe we weren't disabling the redbox in that place you pointed out either.

**Comment by javache** [comment]
The default for RCTFatal is currently to throw an exception, with the expectation that it will terminate the app. It's behaviour is totally configurable (which is why I made this change).

Sounds like disabling the redbox and setting a (empty) fatal handler would resolve your issues here then?

**Comment by ide** [comment]
Sorry, when I said "fatal" that was a bit ambiguous. I was referring to the exceptions passed to "reportFatalException:" (https://github.com/facebook/react-native/blob/0c83407dd2a748d31bc2dd17477c6dff59f1ef54/React/Modules/RCTExceptionsManager.m#L63) which may get passed to RCTFatal but aren't always.

One way to achieve what I'm looking for is to have an RCTDefaultExceptionsManagerDelegate class that implements the default behavior (redboxes and reloading) and is the default value of `exceptionsManager.delegate` (though i guess it's not typical of Cocoa APIs to have a default delegate). Then I could override the delegate pretty easily. And if you wanted to still get the default behavior the custom delegate could call the original delegate's methods.

**Comment by javache** [comment]
Are you trying to accommodate the scenario where _maxReloadAttempts is non-default and > 0? If anything, I'd actually like to move that functionality out of RCTExceptionsManager and into the default RCTFatal handler.

**Comment by ide** [comment]
I guess I would like bridge-specific RCTFatal handlers since we have multiple bridges. That'd be a clean solution to our use case.

The one thing that is still nice about letting the delegate cancel the default exception handling is that regardless of what other code gets added to RCTExceptionsManager, I could be pretty confident that it wouldn't get run. Specifically, I can override the redbox module and RCTFatal handler, but if some other new module/API gets called from the exception handler, I'd have to make sure to override that too. This isn't a huge deal but thought it's worth highlighting.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/errors-letting-rctexceptionsmanagerdelegate-override-default-behavior

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
