### ISSUE TITLE
getting error @react-native-community_art:generateReleaseRFile when get android release with CI/CD tools (bamboo)

### ISSUE THREAD

**Issue by sootood** [facebook/react-native#39620]
### Description

our app produced for several companies so use react-native-config for creating profiles and use them in CI/CD (bamboo) when we run bamboo to make releases (android/iOS) for each profile at least for 3-4 profiles get error @react-native-community_art:generateReleaseRFile one solution is run "gradlew clean" but I cant always run it i want to solve it or make it automatic.

this error usually show by "react-native-community_art" but sometimes change to other libraries

the completed error is

Execution failed for task ':@react-native-community_art:generateReleaseRFile' A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable pathToDirectory/node_modules/@react-native-community/art/android/build/intermediates/local_only_symbol_list/release/R-def.txt

or

Execution failed for task ':@react-native-community_art:generateReleaseRFile'. A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable /pathTodProjectDirectory/node_modules/@react-native-community/art/android/build/intermediates/merged_manifest/release/AndroidManifest.xml

sometimes it gets in debug mood

how can i fix that please help me

react-native : 0.71.11/ 0.69.3
i try :
remove all jCenter() from android gradle (installed dependencies)
sync compilegradleVersion (installed dependencies and root project)
rerun bamboo for fixe and continue to execute releasing app

### React Native Version

0.71.11

### Output of `npx react-native info`

 SDKs:
    Android SDK:
      Android NDK: 21.4.7075529
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-222.4459.24.2221.10121639
    Visual Studio: Not Found
  Languages:
    Java: 11.0.6 - C:\Program Files\Java\jdk-11.0.6\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.11 => 0.71.11
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

when rerun bamboo to get release after some profiles it gets error

### Snack, screenshot, or link to a repository

https://stackoverflow.com/questions/77162991/getting-error-react-native-community-artgeneratereleaserfile-when-get-android

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to an external package. Please open this issue against this other repository:

https://github.com/react-native-art/art/issues
https://github.com/software-mansion/react-native-svg/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
