### ISSUE TITLE
0.14.0 iOS Simulator does not update w/ Cmd+R

### ISSUE THREAD

**Issue by bartonhammond** [facebook/react-native#3962]
Using workaround from [https://github.com/facebook/react-native/issues/3948](https://github.com/facebook/react-native/issues/3948), running ios simulator and after changing index.ios.js, CMD+R does not update view.

**Comment by bartonhammond** [comment]
Ooops - restarted "npm start" and all is good

**Comment by iamfog** [comment]
i tried "npm start", but it doesn't work...
