### ISSUE TITLE
objc[81508]: Swift class extensions and categories on Swift classes are not allowed to have +load methods

### ISSUE THREAD

**Issue by ombogdanJoinToIt** [facebook/react-native#39623]
### Description

I run my app on Xcode 15.0 and after building get this error: objc[81508]: Swift class extensions and categories on Swift classes are not allowed to have +load method

### React Native Version

0.70.3

### Output of `npx react-native info`

    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/Projects/WebstormProjects/ReactNative/mobile/node_modules/.bin/npm
    Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Update Xcode to 15.0
Use only react native version 0.70.3
Try to open app after running
Simulator iPhone 15Pro Max

### Snack, screenshot, or link to a repository

Doesn`t have

**Comment by reddybs123** [comment]
I am also getting same error after I upgrade my mac with latest version and xcode 15 

Output of npx react-native info

info Fetching system and libraries information...
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 32.51 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      API Levels: 29, 30, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Intel x86_64 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by hassanharoon321** [comment]
any solution?

**Comment by zjkuang** [comment]
Same issue after upgrade to Xcode 15.

**Comment by SalaSuresh** [comment]
The same issue after updating the Mac OS and Xcode.

**Comment by fedpre** [comment]
Same here. Why was the issue closed without a solution?

**Comment by Danushka96** [comment]
Same here, any solution?

**Comment by pasquale95** [comment]
Same error, please reopen the issue

**Comment by pasquale95** [comment]
I started getting such error after updating to XCode Version 15.0 (15A240d)

**Comment by fedpre** [comment]
I actually found that it is a library giving the problem, but still, I didn't get the error without Xcode 15

**Comment by pasquale95** [comment]
@fedpre can you say which library and which version?

**Comment by fedpre** [comment]
@pasquale95 Sure! It is `react-native-vision-camera` v2.15.0

**Comment by pasquale95** [comment]
Thanks @fedpre, your hints allowed me to solve the issue.
For whoever has the same dependency, @mrousavy published recently the new release [2.16.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.2) to fix this exact problem.

Therefore, update `react-native-vision-camera` in your `package.json`:
```
  "react-native-vision-camera": "^2.16.2",
```
and run a `pod install` in the `ios/` folder.

**Comment by fedpre** [comment]
@pasquale95 YOU DA MAN! I fixed the error as well! Thank you so much. I love the power of community!

**Comment by pasquale95** [comment]
The app builds now, but after switching to that version I get this error at runtime now:
```
frame-processor/unavailable: Frame Processors are not enabled. See https://react-native-vision-camera.com/docs/guides/troubleshooting, js engine: hermes
```
@fedpre do you have also such issue on your side?

**Comment by fedpre** [comment]
@pasquale95 I have manually updated the relevant code on 2.15.4 as I have a custom fix for orientation that I don't want to lose. However, I don't get an error like that but it says that it cannot find my frame processor function (in my case `__pose`)

**Comment by pasquale95** [comment]
Opened a separate issue in `react-native-vision-camera`: https://github.com/mrousavy/react-native-vision-camera/issues/1937

**Comment by Danushka96** [comment]
> Thanks @fedpre, your hints allowed me to solve the issue. For whoever has the same dependency, @mrousavy published recently the new release [2.16.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.2) to fix this exact problem.
> 
> Therefore, update `react-native-vision-camera` in your `package.json`:
> 
> ```
> "react-native-vision-camera": "^2.16.2",
> ```
> 
> and run a `pod install` in the `ios/` folder.

This fixed my issue

**Comment by mrousavy** [comment]
Glad to hear I fixed the issue for you guys

**Comment by edritech93** [comment]
The same issue after updating the Mac OS Sonoma and Xcode 15

**Comment by vidurajith-darshana** [comment]
> Thanks @fedpre, your hints allowed me to solve the issue. For whoever has the same dependency, @mrousavy published recently the new release [2.16.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.2) to fix this exact problem.
> 
> Therefore, update `react-native-vision-camera` in your `package.json`:
> 
> ```
> "react-native-vision-camera": "^2.16.2",
> ```
> 
> and run a `pod install` in the `ios/` folder.

this answer saved my day

**Comment by mrousavy** [comment]
> this answer saved my day

this answer or my update? 🙃

**Comment by vidurajith-darshana** [comment]
> > this answer saved my day
> 
> this answer or my update? 🙃

Probably your update 😅❤️

**Comment by SalaSuresh** [comment]
> @pasquale95 I have manually updated the relevant code on 2.15.4 as I have a custom fix for orientation that I don't want to lose. However, I don't get an error like that but it says that it cannot find my frame processor function (in my case `__pose`)

Can you share me the patch file?

**Comment by ombogdanJoinToIt** [comment]
> > Thanks @fedpre, your hints allowed me to solve the issue. For whoever has the same dependency, @mrousavy published recently the new release [2.16.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.2) to fix this exact problem.
> > Therefore, update `react-native-vision-camera` in your `package.json`:
> > ```
> > "react-native-vision-camera": "^2.16.2",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and run a `pod install` in the `ios/` folder.
> 
> this answer saved my day

but now the frame processor does not work on ios and android

**Comment by shyrynaz** [comment]
> Thanks @fedpre, your hints allowed me to solve the issue. For whoever has the same dependency, @mrousavy published recently the new release [2.16.2](https://github.com/mrousavy/react-native-vision-camera/releases/tag/v2.16.2) to fix this exact problem.
> 
> Therefore, update `react-native-vision-camera` in your `package.json`:
> 
> ```
> "react-native-vision-camera": "^2.16.2",
> ```
> 
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/pieces.png)
> Copy And Save
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/link.png)
> Share
> ![](https://storage.googleapis.com/pieces-web-extensions-cdn/copilot.png)
> Ask Copilot
> and run a `pod install` in the `ios/` folder.

this resolved my issue

**Comment by SalaSuresh** [comment]
I have added below code in my patch file and it is working for me without any package update.
```
diff --git a/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorPlugin.h b/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorPlugin.h
index 9408774..0585fac 100644
--- a/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorPlugin.h	
+++ b/node_modules/react-native-vision-camera/ios/Frame Processor/FrameProcessorPlugin.h	
@@ -33,7 +33,7 @@
  */
 #define VISION_EXPORT_FRAME_PROCESSOR(frame_processor)                              \
                                                                                     \
-+(void)load                                                                         \
++(void)initialize                                                                         \
 {                                                                                   \
   [FrameProcessorPluginRegistry addFrameProcessorPlugin:@"__" @ #frame_processor callback:^id(Frame* frame, NSArray<id>* args) { \
     return frame_processor(frame, args);                                           \
@@ -53,7 +53,7 @@ objc_name : NSObject<FrameProcessorPluginBase>
 @end                                                                                \
 @implementation objc_name (FrameProcessorPlugin)                                    \
                                                                                     \
-+(void)load                                                                          \
++(void)initialize                                                                          \
 {                                                                                   \
   [FrameProcessorPluginRegistry addFrameProcessorPlugin:@"__" @ #name callback:^id(Frame* frame, NSArray<id>* args) {    \
     return [objc_name callback:frame withArgs:args]; 
```

**Comment by AyazQadri** [comment]
Hi All,

I'm also getting the same error after updating my xcode to 15 but the issue gets resolved on xcode 15 after udpating pkg to this "react-native-vision-camera": "^2.16.2", but now it crashes the application on lower OS versions as well as on Android too.

Do we have any solution for that ?
