### ISSUE TITLE
RN 0.72.5 - use_frameworks no longer works

### ISSUE THREAD

**Issue by enchorb** [facebook/react-native#39639]
### Description

Was getting the `react/debug/react_native_assert.h` error (https://github.com/facebook/react-native/issues/38283). After applying the fixes in the comments am now getting the error `ReactCommon/TurboModuleBinding.h' file not found` from `React-NativeModulesApple`. 

After further investigation this seems to be caused by `use_frameworks` https://github.com/react-native-tvos/react-native-tvos/issues/575

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 439.93 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.16.1/bin/yarn
  npm:
    version: 10.1.0
    path: ~/Documents/Code/node_modules/.bin/npm
  Watchman:
    version: 2023.06.26.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ankur/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-30 | Google APIs Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/ankur/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Snack, screenshot, or link to a repository

https://snack.expo.dev

**Comment by enchorb** [comment]
After further debugging this seems to be an issue with the recent `0.72.5` release. `0.72.4` works for me on `XCode 14.3.1` & `15`, but `0.72.5` leads to the above errors.

**Comment by cipolleschi** [comment]
Hi @enchorb I'm sorry to hear that. We have tests to keep this in check in CI, so I'm pretty sure it works.
Can you provide a reproducer using https://github.com/react-native-community/reproducer-react-native?

**Comment by enchorb** [comment]
@cipolleschi using a work repo so don't really have the time to convert it to a reproducible example but you can see in the two following issues that more and more people are  running into this:

https://github.com/facebook/react-native/issues/38283
https://github.com/react-native-tvos/react-native-tvos/issues/575

**Comment by cipolleschi** [comment]
@enchorb as I said, `use_frameworks!` it is working on React Native Core 0.72 branch, with both static and dynamic linking.

If you are facing issues with `react-native-tvos`, please open an issue in that repo: it is a fork of react-native and we do not maintain it.

**Comment by evelant** [comment]
@cipolleschi Do you run a test with `pnpm` as the package manager? I think that's the core issue here. `0.72.5` doesn't build with `use_frameworks!` if someone is using `pnpm`. https://github.com/facebook/react-native/issues/38283

**Comment by cipolleschi** [comment]
@fukemy please do not spam your issue in other issues as it makes harder for the people that are helping/following an issue to understand whether your comment is relevant. I'm deleting it.

@evelant technically, we are not supporting pnpm yet. We have people working on supporting it properly as we know it is important but, right now, the support is experimental.
In 0.72.4 [we had some changes](https://github.com/facebook/react-native/commit/58adc5e4b9ab74b67b4af04d1e72c387af848ea7) in iOS to support it better that we [had to revert](https://github.com/facebook/react-native/commit/e9eca07f5222cb846c3069705cf48a9db9209863) as they were make other part of the system fails, unfortunately. My guess is that there is something odd with the `header_mappings_dir` of some podspecs. :( 

We don't have a proper solution yet, unfortunately. To unblock yourself, you can try to reapply the changes from 58adc5e4 for the time being.
