### ISSUE TITLE
no type or protocol named UIApplicationOpenURLOptionsKey 

### ISSUE THREAD

**Issue by ElangoPrince** [facebook/react-native#39647]
### Description

#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)app
  openURL:(NSURL *)url
  options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:app openURL:url options:options];
}

<img width="594" alt="Screenshot 2023-09-26 at 1 39 25 PM" src="https://github.com/facebook/react-native/assets/34785789/1c602c89-a470-4f18-a409-0323d1d9aec8">
<img width="947" alt="Screenshot 2023-09-26 at 1 41 12 PM" src="https://github.com/facebook/react-native/assets/34785789/4bda69a7-4172-4faf-85c6-5ee02ec4bb84">

"react-native": "0.72.5",
XCode - 14

### React Native Version

0.72.5

### Output of `npx react-native info`

warn Multiple Podfiles were found: ios/Podfile,macos/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 93.98 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 19.5.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 6.14.18
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.01.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/elango/.rvm/gems/ruby-2.7.6/bin/pod

### Steps to reproduce

react-native run-macos

### Snack, screenshot, or link to a repository

warn Multiple Podfiles were found: ios/Podfile,macos/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 93.98 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 19.5.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 6.14.18
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.01.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/elango/.rvm/gems/ruby-2.7.6/bin/pod

**Comment by ElangoPrince** [comment]
LinkingIOS not working actually!

**Comment by cortinico** [comment]
> react-native run-macos

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to React Native MacOS

https://github.com/microsoft/react-native-macos/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
