### ISSUE TITLE
After upgrading React-native, the Android app crashes with an error on Linux.

### ISSUE THREAD

**Issue by dingsq820** [facebook/react-native#39642]
### New Version

0.71.12

### Old Version

0.66.3

### Build Target(s)

android

### Output of `react-native info`

System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 2.90 GB / 15.40 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
    Watchman: 2022.07.04.00 - /home/linuxbrew/.linuxbrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 28, 30, 31, 33
      Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-31 | Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

09-26 10:47:12.532 F/i.digitalwalle( 9177): runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x25
09-26 10:47:12.532 F/i.digitalwalle( 9177): runtime.cc:677]     string: 'ws://localhost:9089?medium=1&sdk_version=4&app=�%B1U%20wallet&device_id=unknown&device=sdk_gphone64_x86_64%20-%2012%20-%20API%2031&os=Android'
09-26 10:47:12.532 F/i.digitalwalle( 9177): runtime.cc:677]     input: '0x77 0x73 0x3a 0x2f 0x2f 0x6c 0x6f 0x63 0x61 0x6c 0x68 0x6f 0x73 0x74 0x3a 0x39 0x30 0x38 0x39 0x3f 0x6d 0x65 0x64 0x69 0x75 0x6d 0x3d 0x31 0x26 0x73 0x64 0x6b 0x5f 0x76 0x65 0x72 0x73 0x69 0x6f 0x6e 0x3d 0x34 0x26 0x61 0x70 0x70 0x3d 0xce <0x25> 0x42 0x31 0x55 0x25 0x32 0x30 0x77 0x61 0x6c 0x6c 0x65 0x74 0x26 0x64 0x65 0x76 0x69 0x63 0x65 0x5f 0x69 0x64 0x3d 0x75 0x6e 0x6b 0x6e 0x6f 0x77 0x6e 0x26 0x64 0x65 0x76 0x69 0x63 0x65 0x3d 0x73 0x64 0x6b 0x5f 0x67 0x70 0x68 0x6f 0x6e 0x65 0x36 0x34 0x5f 0x78 0x38 0x36 0x5f 0x36 0x34 0x25 0x32 0x30 0x2d 0x25 0x32 0x30 0x31 0x32 0x25 0x32 0x30 0x2d 0x25 0x32 0x30 0x41 0x50 0x49 0x25 0x32 0x30 0x33 0x31 0x26 0x6f 0x73 0x3d 0x41 0x6e 0x64 0x72 0x6f 0x69 0x64'
09-26 10:47:12.532 F/i.digitalwalle( 9177): runtime.cc:677]     in call to NewStringUTF
09-26 10:47:12.532 F/i.digitalwalle( 9177): runtime.cc:677]     from void com.facebook.flipper.android.EventBase.loopForever()
09-26 10:47:12.697 E/libc    ( 9288): The property "ro.build.fingerprint" has a value with length 96 that is too large for __system_property_get()/__system_property_read(); use __system_property_read_callback() instead.
09-26 10:47:12.772 E/libc    ( 9292): The property "ro.build.fingerprint" has a value with length 96 that is too large for __system_property_get()/__system_property_read(); use __system_property_read_callback() instead.
09-26 10:47:12.807 F/libc    ( 9177): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9268 (FlipperEventBas), pid 9177 (i.digitalwallet)
09-26 10:47:12.845 E/DEBUG   ( 9295): failed to read /proc/uptime: Permission denied
09-26 10:47:13.249 E/libprotobuf-native( 9295): [libprotobuf ERROR external/protobuf/src/google/protobuf/wire_format_lite.cc:584] String field 'Tombstone.abort_message' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
09-26 10:47:13.250 E/libprotobuf-native( 9295): [libprotobuf ERROR external/protobuf/src/google/protobuf/wire_format_lite.cc:584] String field 'LogMessage.message' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
09-26 10:47:13.251 E/libprotobuf-native( 9295): [libprotobuf ERROR external/protobuf/src/google/protobuf/wire_format_lite.cc:584] String field 'LogMessage.message' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
09-26 10:47:13.251 F/DEBUG   ( 9295): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-26 10:47:13.252 F/DEBUG   ( 9295): Build fingerprint: 'google/sdk_gphone64_x86_64/emulator64_x86_64_arm64:12/SE1A.220630.001/8789670:userdebug/dev-keys'
09-26 10:47:13.252 F/DEBUG   ( 9295): Revision: '0'
09-26 10:47:13.252 F/DEBUG   ( 9295): ABI: 'x86_64'
09-26 10:47:13.252 F/DEBUG   ( 9295): Timestamp: 2023-09-26 10:47:12.844778141+0800
09-26 10:47:13.252 F/DEBUG   ( 9295): Process uptime: 0s
09-26 10:47:13.252 F/DEBUG   ( 9295): Cmdline: com.xxxx.digitalwallet
09-26 10:47:13.252 F/DEBUG   ( 9295): pid: 9177, tid: 9268, name: FlipperEventBas  >>> com.xxxx.digitalwallet <<<
09-26 10:47:13.253 F/DEBUG   ( 9295): uid: 10172
09-26 10:47:13.253 F/DEBUG   ( 9295): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-26 10:47:13.253 F/DEBUG   ( 9295): Abort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x25
09-26 10:47:13.253 F/DEBUG   ( 9295):     string: 'ws://localhost:9089?medium=1&sdk_version=4&app=�%B1U%20wallet&device_id=unknown&device=sdk_gphone64_x86_64%20-%2012%20-%20API%2031&os=Android'
09-26 10:47:13.253 F/DEBUG   ( 9295):     input: '0x77 0x73 0x3a 0x2f 0x2f 0x6c 0x6f 0x63 0x61 0x6c 0x68 0x6f 0x73 0x74 0x3a 0x39 0x30 0x38 0x39 0x3f 0x6d 0x65 0x64 0x69 0x75 0x6d 0x3d 0x31 0x26 0x73 0x64 0x6b 0x5f 0x76 0x65 0x72 0x73 0x69 0x6f 0x6e 0x3d 0x34 0x26 0x61 0x70 0x70 0x3d 0xce <0x25> 0x42 0x31 0x55 0x25 0x32 0x30 0x77 0x61 0x6c 0x6c 0x65 0x74 0x26 0x64 0x65 0x76 0x69 0x63 0x65 0x5f 0x69 0x64 0x3d 0x75 0x6e 0x6b 0x6e 0x6f 0x77 0x6e 0x26 0x64 0x65 0x76 0x69 0x63 0x65 0x3d 0x73 0x64 0x6b 0x5f 0x67 0x70 0x68 0x6f 0x6e 0x65 0x36 0x34 0x5f 0x78 0x38

**Comment by cortinico** [comment]
> 09-26 10:47:13.251 E/libprotobuf-native( 9295): [libprotobuf ERROR external/protobuf/src/google/protobuf/wire_format_lite.cc:584] String field 'LogMessage.message' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but is related to protobuf. Please open this issue against the protobuf issue tracker.
