### ISSUE TITLE
App is very slow in android 13 for the react-native version 0.71.8

### ISSUE THREAD

**Issue by hemasaitudo** [facebook/react-native#39656]
### Description

App is becoming very sluggish when try to run on the latest android devices.
But the same is very fast in lower android version that checked for 10.
Also when the compileSdkVerison is changed to 32 the app is fast in all devices.
But the same compileSdkVerison is 33 the app is becoming very sluggish.

### React Native Version

0.71.8

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    Memory: 2.88 GB / 7.84 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.20
  npmPackages:
    @react-native-community/cli: ^10.2.5 => 10.2.5
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native run-android

### Snack, screenshot, or link to a repository

The info already provided

**Comment by cortinico** [comment]
Duplicates #36296

**Comment by hemasaitudo** [comment]
@cortinico  The app is still sluggish , we are also using firebase as a backend 
Below is the react native info 
System:
    OS: Windows 10 10.0.17134
    CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
    Memory: 1.78 GB / 7.84 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.20
  npmPackages:
    @react-native-community/cli: ^10.2.5 => 10.2.5
    react: 18.2.0 => 18.2.0
    react-native: 0.71.13 => 0.71.13
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    changed the version that mentioned
