### ISSUE TITLE
[Xcode] React native run script build phase fails

### ISSUE THREAD

**Issue by isair** [facebook/react-native#3966]
I faced this issue in my project which I upgraded, but I created a new project using `react-native init` and I'm seeing it there as well.

```sh
../node_modules/react-native/packager/react-native-xcode.sh
```

Fails saying node is not found. I fixed it by changing it to the following.

```sh
source ~/.nvm/nvm.sh
../node_modules/react-native/packager/react-native-xcode.sh
```

**Comment by ilansas** [comment]
+1 for this and thanks for the fix

**Comment by lukasreichart** [comment]
+1

**Comment by gre** [comment]
dup https://github.com/facebook/react-native/issues/3948

**Comment by ide** [comment]
Please try react-native 0.14.2, which should include a fix for this.
