### ISSUE TITLE
Update RN from 0.68.7 to 0.71.1 Using react.gradle in your project is deprecated

### ISSUE THREAD

**Issue by juliaitbaeva** [facebook/react-native#39684]
### New Version

0.71.1

### Old Version

0.68.7

### Build Target(s)

Android release build

### Output of `react-native info`

% npx react-native info
warn Package @react-native-community/google-signin contains invalid configuration: "dependency.platforms.ios.project" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package appcenter contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-vector-icons contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 64.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/wprojects/temp/voya-cust/node_modules/.bin/yarn
    npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0, 34.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.7 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.0.0 => 10.0.0 
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.10 => 0.71.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Issue and Reproduction Steps

When I generate android build debug and run it in simulator I've got a WARNING from .gradlew clean:
```
> Configure project :app
##############################

Using react.gradle in your project is deprecated! You should move to "apply plugin: com.facebook.react"
react.gradle is going to be removed in a future React Native project and your project will not build anymore.
You can use the template as a reference:
https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle

##############################
…
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 24s
61 actionable tasks: 8 executed, 53 up-to-date
```

When it run android release build in AppCenter I've got an error:
```
ERROR:[drawable-xxxhdpi-v4/node_modules_reactnativecalendars_src_img_down] /projects/android/app/build/generated/res/react/devRelease/drawable-xxxhdpi/node_modules_reactnativecalendars_src_img_down.png [drawable-xxxhdpi-v4/node_modules_reactnativecalendars_src_img_down] /projects/android/app/build/generated/res/react/dev/release/drawable-xxxhdpi/node_modules_reactnativecalendars_src_img_down.png: Resource and asset merger: Duplicate resources

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDevReleaseResources'.
> [drawable-xhdpi-v4/node_modules_reactnativevideocontrols_assets_img_topvignette] /projects/android/app/build/generated/res/react/devRelease/drawable-xhdpi/node_modules_reactnativevideocontrols_assets_img_topvignette.png       [drawable-xhdpi-v4/node_modules_reactnativevideocontrols_assets_img_topvignette] /projects/android/app/build/generated/res/react/dev/release/drawable-xhdpi/node_modules_reactnativevideocontrols_assets_img_topvignette.png: Error: Duplicate resources
  [drawable-xhdpi-v4/node_modules_reactnativevideocontrols_assets_img_volume] /projects/android/app/build/generated/res/react/devRelease/drawable-xhdpi/node_modules_reactnativevideocontrols_assets_img_volume.png 
...
  [drawable-xxxhdpi-v4/node_modules_reactnativecalendars_src_img_down] /projects/android/app/build/generated/res/react/dev/release/drawable-xxxhdpi/node_modules_reactnativecalendars_src_img_down.png: Error: Duplicate resources

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 5m 6s
744 actionable tasks: 739 executed, 5 up-to-date
error Failed to build the app.
Error: Command failed: ./gradlew app:assembleRelease
    at makeError (/projects/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/projects/node_modules/execa/index.js:338:15)
    at build (/projects/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:83:22)
    at Object.buildAndroid [as func] (/projects/node_modules/@react-native-community/cli-platform-android/build/commands/buildAndroid/index.js:75:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.handleAction (/projects/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
```

 if I remove react.gradle package  from android/app/build.gradle, I delete `apply from: "../../node_modules/react-native/react.gradle”`
 then all builds broken, debug and release and I got the error:
```
> Configure project :app
FullStory: Adding FS maven repo [url=https://maven.fullstory.com] to the project repo
FullStory: Adding 'com.fullstory:instrumentation-full:1.26.0@aar' as an implementation dependency
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/project/android/app/build.gradle' line: 28

* What went wrong:
A problem occurred configuring project ':app'.
> Could not get unknown property 'bundleDevReleaseJsAndAssets' for project ':app' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

I use build variants in android/app/build.gradle 
 ```
afterEvaluate {
    bundleDevReleaseJsAndAssets.doFirst {
        environment "TARGET_CONFIGURATION", "dev"
    }
    bundleFusionReleaseJsAndAssets.doFirst {
        environment "TARGET_CONFIGURATION", "fusion"
    }
    bundleQaReleaseJsAndAssets.doFirst {
        environment "TARGET_CONFIGURATION", "qa"
    }
    bundleUatReleaseJsAndAssets.doFirst {
        environment "TARGET_CONFIGURATION", "uat"
    }
    bundleProdReleaseJsAndAssets.doFirst {
        environment "TARGET_CONFIGURATION", "prod"
    }
} 
```
It seems like without plugin react.gradle bundle${variable}JsAndAssets  not generated and we get get unknown property 'bundleDevReleaseJsAndAssets'. I've added react-native-gradle-plugin with `yarn add` to project but error persists, is the same.
I use react-native-navigation in project

**Comment by cortinico** [comment]
```
afterEvaluate {
   bundleDevReleaseJsAndAssets.doFirst {
       environment "TARGET_CONFIGURATION", "dev"
   }
   bundleFusionReleaseJsAndAssets.doFirst {
       environment "TARGET_CONFIGURATION", "fusion"
   }
   bundleQaReleaseJsAndAssets.doFirst {
       environment "TARGET_CONFIGURATION", "qa"
   }
   bundleUatReleaseJsAndAssets.doFirst {
       environment "TARGET_CONFIGURATION", "uat"
   }
   bundleProdReleaseJsAndAssets.doFirst {
       environment "TARGET_CONFIGURATION", "prod"
   }
} 
```

why do you need this code? @juliaitbaeva

**Comment by juliaitbaeva** [comment]
@cortinico I use this code to it sets the environment variables, to build the rest of items and bundle res files

**Comment by juliaitbaeva** [comment]
It's not clear what's the instructions to set environment variables with new gradle plugin, can we do it from build.gradle? What's the task can we use if bundle${variable}JsAndAssets not found?

**Comment by cortinico** [comment]
@juliaitbaeva what do you need to set the environment variable for? Who's using those values?

**Comment by juliaitbaeva** [comment]
fixed issue with using applicationVariants to app build.gradle:
```
project.ext {
    TARGET_CONFIGURATION_DEV = "dev"
    TARGET_CONFIGURATION_FUSION = "fusion"
    TARGET_CONFIGURATION_QA = "qa"
    TARGET_CONFIGURATION_UAT = "uat"
    TARGET_CONFIGURATION_PROD = "prod"
}

android.applicationVariants.all { variant ->
        def TARGET_CONFIGURATION = ""
        switch (variant.buildType.name) {
            case "dev":
               TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_DEV
                break
            case "fusion":
                TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_FUSION
                break
            case "qa":
                TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_QA
                break
            case "uat":
                TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_UAT
                break
            case "prod":
                TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_PROD
                break
        }
    }
```

**Comment by cortinico** [comment]
> fixed issue with using applicationVariants to app build.gradle & delete `apply from: "../../node_modules/react-native/react.gradle”`

Closing because of this

**Comment by juliaitbaeva** [comment]
Sorry, I've found out that next approach not working
 android.applicationVariants.all { variant ->
        def TARGET_CONFIGURATION = ""
        switch (variant.buildType.name) {
            case "dev":
               TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_DEV
                break
            ...
            case "prod":
                TARGET_CONFIGURATION = project.ext.TARGET_CONFIGURATION_PROD
                break
        }
    }
