### ISSUE TITLE
codegenNativeComponent has types and interfaces but is a .js file??

### ISSUE THREAD

**Issue by reykeem** [facebook/react-native#39683]
### Description

I am having trouble building my storybook app that uses react native, rollup and metro to bundle a distribution folder because it hangs up on 

![image](https://github.com/facebook/react-native/assets/106338511/e6c4bfd2-9e73-473b-8eb1-763fd92d8785)

Why are there types in codegenNativeComponent.js when it is a js file and not a ts extension? 

### React Native Version

0.72.1

### Output of `npx react-native info`

System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 73.77 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.1.0
    path: ~/.nvm/versions/node/v20.1.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.1.0/bin/yarn
  npm:
    version: 9.7.2
    path: ~/.nvm/versions/node/v20.1.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

- N/A

### Snack, screenshot, or link to a repository

N/A

**Comment by cortinico** [comment]
> Why are there types in codegenNativeComponent.js when it is a js file and not a ts extension?

That's because that file is a Flow file (see https://flow.org/)
