### ISSUE TITLE
react tab not show in chrome

### ISSUE THREAD

**Issue by passol1988** [facebook/react-native#3968]
I want to debug via React Dev Tools.when I cmd+D in my simulator, the "inspect element" is missing and also the "react" tab  missing? is there some problem or I miss something?
I already set allow local file url  in the extension
I use react 0.13.2 .Chrome: 46.0.2490.80 (64-bit)

the console print:
Launching Dev Tools...
tab id 111 of window id 34

but it doesn't work

**Comment by passol1988** [comment]
debug cmd+d menu changed ?
![0.13.1][1]
![0.9.0] [2]
[1]: http://i.imgur.com/QEvX7pd.png "menu"
[2]: http://i.imgur.com/nACMt03.png "menu"

**Comment by mbrock** [comment]
This issue is known since (I think) 0.12.

https://github.com/facebook/react-devtools/issues/229

**Comment by ide** [comment]
Yeah - the React dev tools don't support RN right now. Follow the dev tools issue for updates.
