### ISSUE TITLE
Expo build failed due to @react-native/normalize-colors@0.73.1 node incompatible engine

### ISSUE THREAD

**Issue by tipleavalentin** [facebook/react-native#39699]
### Description

Main error when I run the android build:  @react-native/normalize-colors@0.73.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.18.1"
It seems this package requires an update.

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.22621
  CPU: "(16) x64 AMD Ryzen 7 2700X Eight-Core Processor         "
  Memory: 16.64 GB / 31.93 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "32"
    Build Tools:
      - 23.0.3
      - 24.0.3
      - 25.0.3
      - 26.0.3
      - 27.0.3
      - 28.0.3
      - 29.0.3
      - 30.0.3
      - 33.0.1
    System Images:
      - android-22 | Google APIs Intel x86 Atom
      - android-29 | Google APIs Intel x86 Atom
      - android-31 | Google Play Intel x86_64 Atom
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Enabled
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.17763.0
IDEs:
  Android Studio: AI-223.8836.35.2231.10671973
  Visual Studio: Not Found
Languages:
  Java:
    version: 1.8.0_282
    path: C:\Programs\jdk\java-1.8.0-openjdk-1.8.0.282\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Execute Android build on Expo "yarn install":

Running "yarn install" in /home/expo/workingdir/build/project directory

yarn install v1.22.17

info No lockfile found.

[1/4] Resolving packages...

[stderr] 

warning @expo/webpack-config > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4

[stderr] 

warning @expo/webpack-config > css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

[stderr] 

warning @react-native-community/masked-view@0.1.11: Repository was moved to @react-native-masked-view/masked-view

[stderr] 

warning expo > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

[stderr] 

warning expo > expo-file-system > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

[stderr] 

warning expo > expo-constants > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

[stderr] 

warning expo > babel-preset-expo > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

[stderr] 

warning expo > babel-preset-expo > @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.

[stderr] 

warning expo > babel-preset-expo > metro-react-native-babel-preset > @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.

[stderr] 

warning expo > @expo/cli > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

[stderr] 

warning expo-notifications > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

[stderr] 

warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.

[stderr] 

warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.

[stderr] 

warning react-native > @react-native/codegen > jscodeshift > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.

[stderr] 

warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer > babel-preset-fbjs > @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.

[stderr] 

warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-react-native-babel-transformer > babel-preset-fbjs > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

[stderr] 

warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

[stderr] 

warning @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.

[2/4] Fetching packages...

[stderr] 

error @react-native/normalize-colors@0.73.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.18.1"

[stderr] 

error Found incompatible module.

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Unknown error. See logs of the Install dependencies build phase for more information.

### Snack, screenshot, or link to a repository

![build failed](https://github.com/facebook/react-native/assets/14072036/146bad50-b6c5-4505-a0e0-4334e6bfc890)

**Comment by ungveloper** [comment]
Same here !! 😭

**Comment by tipleavalentin** [comment]
It seems the Expo build is fine now, no error on this hour.

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/39692

**Comment by ungveloper** [comment]
@cortinico Thank you so much. I have confirmed that the build is now working properly without any errors.

**Comment by Esantos03** [comment]
tengo el mimo problema alguien me indica como resolverlo?: 
![image](https://github.com/facebook/react-native/assets/97195685/652f5c5e-b02b-4f44-b740-ef4d6a1b4302)

**Comment by lelimit** [comment]
Suddenly, I'm currently experiencing the same problem

**Comment by fazlerabbi092** [comment]
currently I am facing same issue

**Comment by fazlerabbi092** [comment]
> 

How you solved that?

**Comment by fazlerabbi092** [comment]
Is there any solutions?

**Comment by vawn-t** [comment]
You can detect Node version in `eas.json`. See: https://docs.expo.dev/build/eas-json/#selecting-build-tool-versions
