### ISSUE TITLE
SIGABRT: Application tried to present modally a view controller <RCTModalHostViewController: 0x161479d30> that is already being presented by <UIViewController:

### ISSUE THREAD

**Issue by Hmoulvad** [facebook/react-native#39693]
### Description

I am seeing this issue all across my React Native App.

The issue is ONLY related to IOS.

It's happening when closing a screen and then navigating to a new.

### React Native Version

0.71.13

### Output of `npx react-native info`

System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 134.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.13 => 0.71.13
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Navigating with React Navigation to a new screen from a Callback within a Modal.

### Snack, screenshot, or link to a repository

App just crashes and stops working.

**Comment by cortinico** [comment]
Duplicates #37198
