### ISSUE TITLE
@react-native/normalize-colors@0.73.1

### ISSUE THREAD

**Issue by KuldipReactNative** [facebook/react-native#39694]
### Description

Hello @mojodna , @jsierles , @augustl , @aroth , @sharnik ,

 unable to install node_modules please find the below error, Please help to us

```json error @react-native/normalize-colors@0.73.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.0"```

### React Native Version

0.63.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 17.02 GB / 31.36 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmGlobalPackages:
    react-native-cli: 2.0.1
info React Native v0.72.5 is now available (your project is running on v0.63.4).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.5.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.63.4.
info To upgrade, run "react-native upgrade".

### Steps to reproduce

run the command yarn install and you will get the error

### Snack, screenshot, or link to a repository

![MicrosoftTeams-image (44)](https://github.com/facebook/react-native/assets/56621598/f45e13e6-bc08-477b-b8a9-185f095052fa)

**Comment by tipleavalentin** [comment]
I have the same issue with React Native 0.72.5

**Comment by ungveloper** [comment]
I have the same issue with React Native 0.72.3

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/39692

**Comment by KuldipReactNative** [comment]
> Duplicates #39692

Hi @cortinico ,
Please assist me since we do not want to upgrade React Native as it is now at version 0.63.4.

**Comment by popejrh19** [comment]
Unsubscribe

William Pope Jr
