### ISSUE TITLE
XCode 15 iOS 12 Build Bridge Crash: Thread 1: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mronline** [facebook/react-native#39697]
### Description

I tried it in xCode 14 and there is no crash. But xCode 15 i tried Debug/Release and the result is the same:

React Native 0.70.13:
<img width="1512" alt="AwesomeProject-0 70 13" src="https://github.com/facebook/react-native/assets/7905030/ca3ca930-913b-405a-a0bc-e4bfc3c23c58">

React Native 0.62.3 - 0.68.7:
<img width="1840" alt="AwesomeProject-0 68 7" src="https://github.com/facebook/react-native/assets/7905030/5277dbf1-11fe-4800-a972-aca6e8fde055">

### React Native Version

0.70.13

### Output of `npx react-native info`

System:
    OS: macOS 13.5.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 1.50 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 6.14.18 - /opt/homebrew/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.13 => 0.70.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

npx react-native init AwesomeProject --version 0.70.13
npx react-native run-ios

### Snack, screenshot, or link to a repository

Unknown

**Comment by frenberg** [comment]
+1

We have the same crash as in your second screenshot (0.62.3-0.68.7) (Maybe since were not using flipper?). We're running 0.71.13. Our app crash on startup for devices running ios 12. (testing on iPhone 6 plus running)

When creating a new project from `npx react-native@0.71.13 init xc15ios12test --version 0.71.13` I get the same crash as your first image. I guess flipper is enabled by default.

**Comment by shilpa12233** [comment]
I am also facing same issue

**Comment by frenberg** [comment]
Yes I will work, the simple template app is working on 0.72.5. You can try with `npx react-native init MyNewApp` and it will run on a device with ios 12.
Unfortunately we can't update to 0.72.5 yet because we use detox to run our tests and they dont support 0.72. So I hope this will have a fix soon.

**Comment by shilpa12233** [comment]
@frenberg my app runs fine on simulator, RN 0.68.2 but crashes in react core pod RCTCxxBridge file - at _reactInstance.reset(new Instance); when I try running on device.

**Comment by mronline** [comment]
@shilpa12233 Yes, it works fine in the simulator, but it does not work on a real device. If you have an urgent need before the React-Native update, your problem will be solved if you download xCode 14.3.1 and get the build. https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_14.3.1/Xcode_14.3.1.xip

@frenberg Thank you, I will upgrade to 0.72.5 and try it.

**Comment by cipolleschi** [comment]
We are aware of the problem and we have a fix for it. The Release Crew is releasing new versions of React Native in these weeks, starting from 0.73 and back to 0.70 to fix the issue.
Thanks for your patience.

**Comment by n1tesh** [comment]
@cipolleschi Can you please share the fix PR. We cannot do a React upgrade at this moment so need to check if we could patch that changes.

**Comment by frenberg** [comment]
Anyone have the code for adding appending this via Podfile since podsproject is wiped on pod install?

**Comment by buschco** [comment]
Will there be a fix for 0.72?

**Comment by frenberg** [comment]
.72 was not broken in 72.5 when I tested template projects.

**Comment by buschco** [comment]
sorry I meant 0.70 🙈

**Comment by frenberg** [comment]
Ahh 😅 I think maybe it already was released? 0.71.14? There was something about the flag in there at least -ld_classic.

**Comment by thomasviaud** [comment]
I'm having the pb with 0.72.6

**Comment by cipolleschi** [comment]
0.70.14 is about to be released soon this week.
0.72.6 and 0.71.14 has been released with the fix.

@thomasviaud: could you please:
- try to delete the `.xcworkspace` project and regenerate it
- check what the `xcode-select -p` command returns.

If the `xcode-select` command does not return a path with Xcode 15, it means that the predefined toolchain is not Xcode 15, and therefore the flags are not added to the project.

**Comment by tarouboy** [comment]
I have upgraded to 0.71.14 but still receive crash reports from user with iPhone 6 / 6 Plus running iOS 12.

**Comment by cipolleschi** [comment]
@tarouboy can you try to navigato to your `ios` folder and run:
```
bundle install
bundle exec pod deintegrate
bundle exec pod install
```
and try again.

Also, what's the output of your `xcodebuild -version` command? This will tell us which version of Xcode Cocoapods is targeting. Make sure to use the same Xcode version when you open the project.

**Comment by tarouboy** [comment]
```
bundle install
bundle exec pod deintegrate
bundle exec pod install
```
I have done but I couldn't validate anyway, coz' I don't have any devices that running iOS 12 at this moment. Xcode won't let me start the iOS 12 simulator either.

`xcodebuild -version` return 15.0.1 build ver 15A507.

btw, I found this:
https://developer.apple.com/forums/thread/738317

I have tried to link `-ld_classic` and see if it helps.
Thanks for your help.

**Comment by tarouboy** [comment]
Just purchased a 2nd hand iPhone 6 ( iOS 12.5 ). Confirmed that after running these lines still crash on app start. It's ok to "Run" on XCode, but crash when doing "Product > Profile" or installing from App Store.

**Comment by hezhii** [comment]
@tarouboy Have you solved this problem?

**Comment by tarouboy** [comment]
> @tarouboy Have you solved this problem?

Yes, but not exactly.
I used another mac that still runs Xcode 14 to archive the app as a temporary solution.

**Comment by mronline** [comment]
When I created a new project, I could not see a problem, but even if I reinstalled the pods in my existing project, the result did not change. I looked at the difference between the new project and my existing project.

If your project has a Swift bridging header, an error like this occurs:

Xcode Thread 1:
```
dyld`:
    0x102eba410 <+0>:  mov    x16, #0x209
    0x102eba414 <+4>:  svc    #0x80
->  0x102eba418 <+8>:  b.lo   0x102eba430               ; <+32> == Thread 1: signal SIGABRT
    0x102eba41c <+12>: stp    x29, x30, [sp, #-0x10]!
    0x102eba420 <+16>: mov    x29, sp
    0x102eba424 <+20>: bl     0x102eb9850               ; cerror_nocancel
    0x102eba428 <+24>: mov    sp, x29
    0x102eba42c <+28>: ldp    x29, x30, [sp], #0x10
    0x102eba430 <+32>: ret    
```
Xcode Console:
```
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
Referenced from: /var/containers/Bundle/Application/C4645550-997A-452B-B65D-013EAE5FB0EF/AwesomeProject.app/AwesomeProject
Reason: image not found
```

**Comment by tarouboy** [comment]
> Edit: I solved the problem like this: https://stackoverflow.com/a/60991366/2649770 There doesn't seem to be a problem for now. @hezhii @tarouboy If you are getting the same error, can you try this way?

Just updated my Xcode to 15.1 today, didn't help.
But after linking the SwiftUI manually it works! Thanks @mronline !!!

**Comment by hezhii** [comment]
> When I created a new project, I could not see a problem, but even if I reinstalled the pods in my existing project, the result did not change. I looked at the difference between the new project and my existing project.
> 
> If your project has a Swift bridging header, an error like this occurs:
> 
> Xcode Thread 1:
> 
> ```
> dyld`:
>     0x102eba410 <+0>:  mov    x16, #0x209
>     0x102eba414 <+4>:  svc    #0x80
> ->  0x102eba418 <+8>:  b.lo   0x102eba430               ; <+32> == Thread 1: signal SIGABRT
>     0x102eba41c <+12>: stp    x29, x30, [sp, #-0x10]!
>     0x102eba420 <+16>: mov    x29, sp
>     0x102eba424 <+20>: bl     0x102eb9850               ; cerror_nocancel
>     0x102eba428 <+24>: mov    sp, x29
>     0x102eba42c <+28>: ldp    x29, x30, [sp], #0x10
>     0x102eba430 <+32>: ret    
> ```
> 
> Xcode Console:
> 
> ```
> dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
> Referenced from: /var/containers/Bundle/Application/C4645550-997A-452B-B65D-013EAE5FB0EF/AwesomeProject.app/AwesomeProject
> Reason: image not found
> ```
> 
> Edit: I solved the problem like this: https://stackoverflow.com/a/60991366/2649770 There doesn't seem to be a problem for now. @hezhii @tarouboy If you are getting the same error, can you try this way?

It works!!

**Comment by aadityabrainfog** [comment]
[Thread 1: EXC_BAD_ACCESS](https://gist.github.com/aadityabrainfog/35152770c1bc4db0f95625e555375b6a)

need help in this
