### ISSUE TITLE
Unable to create new RN 0.72 project with Node 16

### ISSUE THREAD

**Issue by mfazekas** [facebook/react-native#39692]
### Description

```sh
% node --version
v16.20.1

%npx --yes react-native@0.72.5 init testcli --template react-native@0.72.5
```

```
...
error @react-native/normalize-colors@0.73.1: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.1"
error Found incompatible module.
```

```
% yarn why @react-native/normalize-colors
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@react-native/normalize-colors"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@react-native/normalize-colors@0.72.0"
info Reasons this module exists
   - "react-native" depends on it
   - Hoisted from "react-native#@react-native#normalize-colors"
info Disk size without dependencies: "24KB"
info Disk size with unique dependencies: "24KB"
info Disk size with transitive dependencies: "24KB"
info Number of shared dependencies: 0
=> Found "deprecated-react-native-prop-types#@react-native/normalize-colors@0.73.1"
info This module exists because "react-native#deprecated-react-native-prop-types" depends on it.
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 0
✨  Done in 0.18s.
```

Looks like the issue was caused by recent publish of `@react-native/normalize-colors@0.73.1` 
https://github.com/facebook/react-native/tree/main/packages/normalize-color

### React Native Version

0.72.5

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 13.6
  CPU: (12) arm64 Apple M2 Max
  Memory: 703.91 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.20.1/bin/yarn
  npm:
    version: 9.7.2
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/boga/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 15.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/boga/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

```
% node --version
v16.20.1

npx --yes react-native@0.72.5 init testcli --template react-native@0.72.5
````

### Snack, screenshot, or link to a repository

See also https://github.com/facebook/react-native/issues/38298

**Comment by mfazekas** [comment]
@duasfh thanks, I'm personally not affected, this was an issue we saw on our CI, we've updated CI to node 18, so we're fine. But I don't think it was an intended/documented change that rn 0.72.* requires node 18 now.

**Comment by Definitely-Not-Vlad** [comment]
Considering the latest stable RN includes the following in `package.json`:

```
"engines": {
  "node": ">=16"
}
```

I would kindly ask for a RN side resolution to this. Not sure if this is an acceptable approach, but it comes to mind; publishing 0.73.0 as 0.73.2, then publishing 0.73.1 as 0.74.0, considering it's a breaking change due to its change of Node minimum version requirements.

For the time being I'm resolving this on my side using:
```
"resolutions": {
  "@react-native/normalize-colors": "0.73.0"
}
```
In my `package.json`, but I would much prefer not having to add this.

**Comment by cortinico** [comment]
Thanks for flagging this @mfazekas, we're currently investigating what's the best resolution for this problem. As you mentioned, setting the `resolutions` for `"@react-native/normalize-colors": "0.73.0"` is a valid workaround as that version doesn't contain the `engines` directive.

**Comment by cortinico** [comment]
Closing as per https://github.com/facebook/react-native/pull/39698 
We published `@react-native/normalize-colors` version 0.73.2 which fixes this issue

**Comment by devbdo** [comment]
# 🚀 SOLUTION: iOS 18 + Xcode 16 Build Issues with OneSignal (After April 26, 2025)

📌 PROBLEM:
Build failures after updating to iOS 18, Xcode 16, and OneSignal.

✅ SOLUTION STEPS:

## 1. 📥 Download Xcode 16 
- Download from Apple Developer Portal:
  https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_16/Xcode_16.xip

## 2. 📝 Update Podfile Configuration  
Modify your Podfile to include:

```ruby 
platform :ios, '18'  # Do not use min SDK auto-versioning! 
```

##  3. 📦 ONESIGNAL VERSION
Use these stable versions:

For React Native:
```ruby 
"react-native-onesignal": "^4.5.4"
```

## 4. 🔄 CLEAN INSTALL
Run these commands:
pod repo update
pod install

Then in Xcode:
Clean Build Folder (Shift+Cmd+K)

##  5. ⚠️ UPDATE OTHER DEPENDENCIES
Check these packages if issues continue:
- Flipper
- Firebase
- React Native


##  6.  🛠️ RN 0.72+ SPECIFIC FIXES
If using New Architecture:
- Update folly to 2023.08.07.00 in Podfile:
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

##  💬 TROUBLESHOOTING RN 0.72+:
1. Check Metro server compatibility
2. Verify Hermes version matches RN 0.72+ requirements
3. Ensure CocoaPods 1.12.0+ is installed


##  🤝 SUPPORTED VERSIONS:
This solution verified working with:
- RN 0.72.4
- RN 0.73.2
- RN 0.74.0
- ++ or last version

LABELS:
iOS18, Xcode16, OneSignal, BuildError
