### ISSUE TITLE
UIExplorer app sample crashed in my iPhone5 crashed because react-native huge memory.

### ISSUE THREAD

**Issue by luosong** [facebook/react-native#397]

**Comment by sahrens** [comment]
Do you recall what you did exactly leading up to the crash?  Can you reproduce reliably?

**Comment by jaygarcia** [comment]
Please take the time to post reproducible steps and a stack trace if possible when reporting bugs.  

JG


:: sent from my mobile device ::

**Comment by luosong** [comment]
I use iPhone 6 plus.
Step：
1、Clone UIExplorer source code .
2、Build & run app in my IP6.
3、Run CameraRollExample keep drag up & drag down many times.
4、You will see memory keep increase, sometime up 200M !

**Comment by bluemsn** [comment]
@luosong I use simulator 【iphone6】, and also get crash , the memory keep 120MB.

**Comment by brentvatne** [comment]
Dupe #779
