### ISSUE TITLE
Could not find implementation class "com.facebook.react.ReactPlugin"

### ISSUE THREAD

**Issue by muhammadalizkhan** [facebook/react-native#39707]
### Description

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\Muhammad Ali Khan\Desktop\React Native Apps\ReactNativeApp01\android\app\build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find implementation class 'com.facebook.react.ReactPlugin' for plugin 'com.facebook.react' specified in jar:file:/C:/Users/Muhammad%20Ali%20Khan/.gradle/caches/jars-9/7f5e73fa009bbe0e0387b17a1592a9db/react-native-gradle-plugin.jar!/META-INF/gradle-plugins/com.facebook.react.properties.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  Memory: 607.22 MB / 7.41 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 11.0.8-internal
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

I Install React Native and Setup all Required things, I create three projects in months that working properly, but today when i create an new project, its give me this eroor, just 5 hours ago, all pervious prjects working properly

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/72930799/a4d63f38-00c6-41ea-90d7-b4559e1f48e8)

**Comment by ramizqazi** [comment]
Same issue

**Comment by muhammadalizkhan** [comment]
> Same issue

I Solve this Issue, But really don't remember right now!!

**Comment by joaovitorleffa** [comment]
Same issue

**Comment by muhammadalizkhan** [comment]
> Same issue

I Solve this issue, vist:  https://github.com/muhammadalizkhan/React-Native_App-01 and match your gradle and JSON files

**Comment by lasithalakmal** [comment]
Facing the same issue.

**Comment by andresjpulido** [comment]
same issue here

**Comment by lasithalakmal** [comment]
Just created a new project (0.73.3) and it seems to be working now

**Comment by litoco** [comment]
Had to [re-install nodejson my mac](https://stackoverflow.com/a/78103518/14004940) and re-initialised a fresh project with `npx react-native@latest init AwesomeProject`, to get rid of this error. The problem was with my nodejs setup.

**Comment by Harrisbaig7** [comment]
same issue right now

**Comment by AliYar-Khan** [comment]
having same issue

**Comment by sagar-jadhav-vas** [comment]
Reinstalling node modules worked

**Comment by Bilalwarind** [comment]
rm -rf node_modules
rm yarn.lock
yarn install
