### ISSUE TITLE
After react-native init Aproject, run "npm i" compile error

### ISSUE THREAD

**Issue by leenux** [facebook/react-native#3971]
$ npm i

> bufferutil@1.2.1 install /Users/xxxxx/Developer/xxxxxx/AProject/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:7:
In file included from /Users/xxxxx/.node-gyp/4.2.2/include/node/v8.h:19:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/include/stdint.h:63:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/usr/include/sys/_types.h:32:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk/usr/include/sys/cdefs.h:680:2: error: 
      Unsupported architecture
#error Unsupported architecture
 ^
....
etc.....

my mac env:
osx ver 10.11.1
xcode Version 6.4 (6E35b)
iOS sdk ver 8.4
npm ver 3.3.12
node-gyp ver v3.0.3
node.js ver v4.2.2

**Comment by leenux** [comment]
btw:
Both android and iOS,The app is good when "react-native run-android" or in Android studio,is fine
In Xcode run fine too.

**Comment by christopherdro** [comment]
@leenux I've gotten from time to time and it seems to go away every time I restart my computer.

Whats important is that the project runs on both Android and iOS, which has been the case for me as well.
