### ISSUE TITLE
Task :packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes FAILED

### ISSUE THREAD

**Issue by ravir-simform** [facebook/react-native#39721]
### Description

I am trying to run testcases on main repo, I have Mac M1 but still getting this issue. Any idea or suggestion?

    > Task :packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes FAILED

I have done `yarn` on root before running the command `./gradlew :packages:react-native:ReactAndroid:test`
Here is full error log I am getting

```
> Task :packages:react-native:ReactAndroid:downloadGlog UP-TO-DATE
Download https://github.com/google/glog/archive/v0.3.5.tar.gz

> Task :packages:react-native:ReactAndroid:downloadGtest UP-TO-DATE
Download https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz

> Task :packages:react-native:ReactAndroid:downloadLibevent UP-TO-DATE
Download https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz

> Task :packages:react-native:ReactAndroid:hermes-engine:downloadHermes UP-TO-DATE
Download https://github.com/facebook/hermes/tarball/main

> Task :packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':packages:react-native:ReactAndroid:hermes-engine:configureBuildForHermes'.
> A problem occurred starting process 'command 'cmake''`
```

### React Native Version

main branch clone

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M1
  Memory: 96.44 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
ravi.ruparaliya@SF-LAP-086 react-native-main % npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M1
  Memory: 181.73 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

clone/download `main` branch
Run `yarn`
Run `./gradlew :packages:react-native:ReactAndroid:test`

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/61235892/de91f473-8c57-4e3b-b7cb-0062ca1f59c8)

**Comment by ravir-simform** [comment]
@cortinico Here is the issue as we have discussed on this thread https://github.com/facebook/react-native/issues/38825

**Comment by cortinico** [comment]
@ravir-simform can you share the output of:

```
env | grep ANDROID
```
?

**Comment by ravir-simform** [comment]
@cortinico  Here is the output

    ANDROID_HOME=/Users/ravi.ruparaliya/Library/Android/sdk

**Comment by cortinico** [comment]
@ravir-simform Could you open Android Studio, and verify that you have CMake `3.22.1` installed? If not, could you install it and try to run the command again?

It should look like the following screendshot:

<img width="1094" alt="Screenshot 2023-10-03 at 10 45 02" src="https://github.com/facebook/react-native/assets/3001957/ad20a5e9-e110-4f76-aeaa-abc9e82f4354">

I believe we might have an underlying bug to solve, but if this unblocks you it's great

**Comment by ravir-simform** [comment]
@cortinico Now this looks great, I was having it already installed but just updated it to newer version of `CMake` and everything worked like a charm. Thanks a lot.
