### ISSUE TITLE
keyboard dismiss makes re-render component

### ISSUE THREAD

**Issue by ZoHayk** [facebook/react-native#39742]
### Description

Hello, I noticed a strange bug in the work keyboard dismiss.
When we enter something in the input and closes the keyboard, it re renders component. If we take data from the store via redux. The important point is that after entering, not even after deleting, and even just opening and closing, but after entering this strange bug is happening.

If close the keyboard via Keyboard.dismiss(), a re-render occurs. And if close through the return button in the keyboard it works correctly. I haven't anything in the store about opening and closing the keyboard!

### React Native Version

0.72.5

### Output of `npx react-native info`

```
    "@reduxjs/toolkit": "^1.9.5",
    "react": "18.2.0",
    "react-native": "0.72.5",
    "react-redux": "^8.1.2",
```

### Steps to reproduce

[Video](https://drive.google.com/file/d/1mBBPzeLMrJthkrwAS9kBx0Lj_A02vEON/view?usp=sharing)

### Snack, screenshot, or link to a repository

```
import React from 'react';
import { TextInput, TouchableOpacity, View, Keyboard } from 'react-native';
import { createSelector } from '@reduxjs/toolkit';
import { useSelector, useDispatch } from 'react-redux';
import { RootState } from 'types';
import { changeTestInfo } from 'features/test/slice';

export const MenuScreen: React.FC = () => {
  const dispatch = useDispatch();
  const { name, email, searchText, sendStatus, ... } = useSelector((state: RootState) => state.test);

  console.log(screenState);
  return (
    <View style={{ flex: 1, backgroundColor: 'green', paddingTop: 100 }}>
      <TextInput
        placeholder="Enter here"
        value={searchText}
        onChangeText={value => dispatch(changeTestInfo({ key: 'searchText', value }))}
        style={{ backgroundColor: 'white', height: 40, fontSize: 30 }}
      />
      <TouchableOpacity
        style={{ height: 100, width: 100, backgroundColor: 'yellow' }}
        onPress={() => Keyboard.dismiss()}
      />
    </View>
  );
};
```

If do the same with useState, it works correctly.

```
  const [searchText, setSearchText] = useState('');
```

Or do you need to specifically take from redux what you need.

```
  const searchText = useSelector((state: RootState) => state.test.searchText);
  ...
  value={searchText}
```

I don't understand why closing the keyboard causes re-rendering.

**Comment by ZoHayk** [comment]
https://github.com/reduxjs/redux-toolkit/issues/3759

**Comment by EmericReactJS** [comment]
Hi, i have a similar behavior on physical device only

react-native: 0.68
xcode: 15 (also 13.X.X)
iphone: 14
ios: 16.6

if i select a textInput, and then dismiss the keyboard by:
- click outside 
- click return

View on my  app rearrange itself drastically (it's like an empty view comes above everything else)

In Xcode, when this happens, this exact error shows up:

`[Assert] +[UIInputViewSetPlacementInvisible placementWithPlacement:]: Should not be called with an invisible placement`

hope it helps

**Comment by Milanp24** [comment]
> Can you check this function : `onChangeText`, I think it's get called when keyboard dismiss, if it's called then it's will replace your redux state with new value => the log display when dismiss keyboard

Yes onChangeText gets called when keyboard dismissed. Adding appropriate condition will solve the issue.
