### ISSUE TITLE
IOS Thread 1 signal SIGABART error App crashes

### ISSUE THREAD

**Issue by ozgurbayram** [facebook/react-native#39749]
### Description

My app crashes when i try to build for both simulator and real device, it stops in a debugger and returns `objc[94762]: Swift class extensions and categories on Swift classes are not allowed to have +load methods` this error to the console, im trying to solve this bug for over 3 days and couldn't find a solution, help pls.

### React Native Version

0.71.3

### Output of `npx react-native info`

System:
    OS: macOS 13.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 63.12 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    Watchman: 2023.09.25.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/local/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Open XCode
- Select Device / Simulator
- Click Build 
- And it stops in the debugger

### Snack, screenshot, or link to a repository

<img width="1221" alt="Screenshot 2023-10-02 at 10 14 44" src="https://github.com/facebook/react-native/assets/56888644/f776acca-6839-43f3-b8da-c8ec8e4edbfc">

**Comment by cipolleschi** [comment]
Hi @ozgurbayram, I'm sorry you are facing the issue. The error is clear, though:

`Swift class extensions and categories on Swift classes are not allowed to have +load methods`

This means that in the iOS native side there is a `Swift extension` that is trying to override the objective-c `load` method and that's not allowed in Swift.

Either you have written that code in Swift while it should have been written in objectiveC, or you are using a library that is not written properly. This is not a problem in React Native core.
