### ISSUE TITLE
npm_module config  gets required from /Users/node_modules instead of ./node_modules

### ISSUE THREAD

**Issue by peveloper** [facebook/react-native#3975]
When requiring [config](https://www.npmjs.com/package/config)  :
```
var config = require('config');
```
which is included in `package.json` as:

```
{
  "name": "sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.14.0",
    "config": "^1.16.0"
  }
}
```
 apparently react-native is searching in the wrong folder: 

```
Unable to resolve module config from /Users/user/Documents/dev/AwesomeProject/index.ios.js: Invalid directory /Users/node_modules/config
```

**Comment by jedrekk** [comment]
I'm getting this issue with any NPM module I try to use.

**Comment by jmreidy** [comment]
+1 - all requires of node_modules appear broken.

**Comment by nc** [comment]
:+1: seeing this too ```Invalid directory /Users/node_modules/react-native"```

**Comment by jmreidy** [comment]
Interestingly, I'm only seeing this behavior with firebase right now. I can require redux and associated modules without a problem.

**Comment by jmreidy** [comment]
I have a fix. Sadly it makes no sense. I uinstalled firebase, reinstalled, tried installing a different version, restarted xcode - nothing worked. But the following steps DID work:

* mv node_modules/firebase node_modules/fbase
* change require to require('fbase');
* build and test in simulator - looks correct
* move fbase back to firebase
* change require back to 'firebase'

Then everything worked normally.

**Comment by peveloper** [comment]
Wow that's annoying. Later I will try your solution with other npm packages. Btw great job @jmreidy, really appreciated.

**Comment by skevy** [comment]
Hey everyone, can you all try:

1) upgrading to latest RN
2) `watchman watch-del-all`
2) `rm -rf $TMPDIR/react-native-packager-*`
3) restart the packager

And let me know if that fixes the issue?

**Comment by jmreidy** [comment]
@skevy I just created a new test repo, recreated the bug, and then ran your commands. That fixed the issue in the test repo!

**Comment by ghamaide** [comment]
@skevy doesn't work for me... still the same error

**Comment by DaveAdams88** [comment]
Hi guys,

I am also getting this error when using jsdom-jscore (or jsdom/jsdom-little)

`uncaught error Error: UnableToResolveError: Unable to resolve module querystring from /Users/•••/•••/•••/node_modules/react-native-svg/node_modules/jsdom-jscore/lib/builtins/url/url.js: Invalid directory /Users/node_modules/querystring
    at ResolutionRequest.js:351:15`

I have tried the steps from both comments by @skevy and @jmreidy but no luck.

I have also completely removed node, nvm and npm from my mac and then reinstalled following the steps on the react-native setup guide (using latest node and npm@2). Then reinstalled node_modules in project (I had removed them before setting up node), but still the same error

**Comment by julipur** [comment]
I'm having the same problem with numerous packages. I start working on a new project and it works. I bring in a new package and it randomly stops working and I start getting the same error looking in users/node_modules. Does not matter which package. I start a new project and add the package it is complaining about and it works. 

I am new to node, but have been playing with react-native for last couple of weeks and always run into this issue.

**Comment by Casy** [comment]
@julipur do you have the solution?

**Comment by julipur** [comment]
@Casy Not really. 

If I stop everything and git clone my project into a new folder and then npm install, it works. That's the workaround that I've been doing. 

This does sound like some sort of caching issue. If I understand correctly the solution by @skevy above in the thread would solve the caching issue, but that has not worked for me.

**Comment by joshblour** [comment]
i've got this problem too. just started after updating react-native:0.17.0-rc to 0.17.0, although that might not be related (Downgrading back to 0.17.0-rc doesn't fix it)

**Comment by joshblour** [comment]
also, on my machine, the tmp files weren't named `react-native-packager-*`

try running `rm -rf $TMPDIR/react*` instead

**Comment by satya164** [comment]
Closing in favor of #4968 . Let's track it there.

**Comment by satya164** [comment]
Closing in favor of #4968 . Let's track it there.

**Comment by FirstBloodFB** [comment]
<img width="359" alt="2016-08-01 12 22 22" src="https://cloud.githubusercontent.com/assets/10174415/17283419/a81aef26-57e2-11e6-9565-54480ab0179c.png">      It is  not work as the  following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
  What can 1 do

**Comment by levda** [comment]
Node js have group of possible folders that can contain modules. When you install one module sometimes module can be dependent to other modules. You have to install this dependancies manual. For example if the error is like /Users/node_modules/module you have to install "npm install -S module". It is showing error as missing path in /Users/node_modules because this is the last element of array full with possible paths that can contain modules (for MAC).

Full list of paths by OS : https://www.npmjs.com/package/npm-paths

**Comment by sevli** [comment]
who can help me to resolve this question ！？？？
