### ISSUE TITLE
ListView onEndReached not triggered

### ISSUE THREAD

**Issue by adrian-social-prod** [facebook/react-native#3978]
After update from 0.11 to 0.14, onEndReached now triggers as soon as a list is rendered with no event  argument and then doesn't trigger again when scrolling to the end. 

On first render contentLength is assigned to this._sentEndForContentLength and so when scrolling to the end the following test prevents a new trigger if contentLength has not changed

 this.scrollProperties.contentLength !== this._sentEndForContentLength 

_maybeCallOnEndReached is being called on line 474 of ListView with no event argument and so the View listener needs to handle an optional event argument

**Comment by ms88privat** [comment]
I could work around that in pure javascript in 0.14.x (master branch). But after upgrading to 15.0-rc it is even worse than before. It triggers multiple times on start with no arguments and multiple times with an argument when I reach the threshold.

I don't know how to use it know without doing 5+ requests

**Comment by adrian-social-prod** [comment]
I reverted my ListView back to where it was in July before this change https://github.com/facebook/react-native/commit/b0bdd4e45d6de4a8f60cffe8d82f063381088f6c which has caused the problems. The ListView is not the most elegant code but it worked before. 

onEndReached should only be triggered when the view is scrolled and the end has been reached. If people need an init state event which can indicate whether more items need to be loaded then that should be done with a new event

**Comment by adrian-social-prod** [comment]
This seems ok using the v0.16.0-rc version of this file, although there is still an issue with onEndReached sending no argument on the first call and subsequent calls with an argument

**Comment by cowboy129** [comment]
@adriansprod 
>onEndReached should only be triggered when the view is scrolled and the end has been reached. If people need an init state event which can indicate whether more items need to be loaded then that should be done with a new event

This event is what I need. Could you please tell me how to use it?
