### ISSUE TITLE
Requiring Node modules that support AMD causes them to try to expose themselves as AMD

### ISSUE THREAD

**Issue by stevenpetryk** [facebook/react-native#398]
Most Node packages expose themselves via AMD, CommonJS (`module.exports`), or globals depending on the environment. I understand that React-native does indeed support AMD, but is there any way to force modules to be treated as CommonJS?

Steps to reproduce:

1. Create a new React Native project
2. Run `npm install exoskeleton` (this, along with jsSHA, are the first two libraries I noticed this with)
3. Add the following to index.ios.js:
    ```js

    var Exoskeleton = require('exoskeleton');
    console.log(Exoskeleton);

    ```
4. Notice how, in the debug console, an empty object is logged.

**Comment by stevenpetryk** [comment]
To add to this, if one goes into Exoskeleton's source, and adds the following (at the top of the file, starting at line 10):

```js
(function(root, factory) {
  // Set up Backbone appropriately for the environment.
  if (typeof define === 'function' && define.amd) {

    console.log('Using AMD'); // <----------------- ADD THIS

    define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
      root.Backbone = root.Exoskeleton = factory(root, exports, _, $);
    });
  } else if (typeof exports !== 'undefined') {
    var _, $;
    try { _ = require('underscore'); } catch(e) { }
    try { $ = require('jquery'); } catch(e) { }
    factory(root, exports, _, $);
  } else {
    root.Backbone = root.Exoskeleton = factory(root, {}, root._, (root.jQuery || root.Zepto || root.ender || root.$));
  }
```

You will see `Using AMD!` logged to the console.

**Comment by NovaDev94** [comment]
This also happend with `lodash`. Using the same test method by @stevenpetryk. Insert `console.log('Using AMD');` to line 11776 of `lodash/index.js`:

```javascript
  // Export lodash.
  var _ = runInContext();

  // Some AMD build optimizers like r.js check for condition patterns like the following:
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    console.log('Using AMD');
```

**Comment by vjeux** [comment]
Thanks for investigating. @amasad will investigate why we have define as a global when he gets a chance

**Comment by NovaDev94** [comment]
I think it's probably related to https://github.com/facebook/react-native/issues/406

**Comment by vjeux** [comment]
Closing this one, #406 is tracking it.
