### ISSUE TITLE
modal position different on simulator 7.0 and 8.3

### ISSUE THREAD

**Issue by passol1988** [facebook/react-native#3981]
I followed the official example to make a Modal , but I fount it has different position in 7.0 and 8.3 simulator . I use react **0.13.1**
this is right on 8.3
![right](http://i.imgur.com/1KaA65W.png)

this is wrong on 7.0 
![wrong](http://i.imgur.com/BKrHePL.png)

**Comment by lucasferreira** [comment]
There are many problems in using Modals windows in iOS 7. And I can't figure out how to solve them =/ so I up to iOS 8 the base minimum version in my App.

**Comment by christopherdro** [comment]
@passol1988 @lucasferreira Any chance you can try running on the latest version of React Native?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
