### ISSUE TITLE
[JSC] function (Array.sort) won't sort Array

### ISSUE THREAD

**Issue by LeoJiaXin** [facebook/react-native#3982]
```
var a = [1,3,2];
a.sort((num1, num2) => num1 > num2);
Global.alert('' + a);
```
And it logs [1,3,2],function `sort` does nothing

**Comment by brentvatne** [comment]
Same result on iOS and Android, also checked to see if value was just returned and it is not. see: https://rnplay.org/apps/yHvHGg

Note that this executes as expected in Chrome:

```
var a = [1,3,2];
a.sort((num1, num2) => num1 > num2);
alert('' + a);
```

Note that if you leave out the compare function, this works on both iOS and Android: https://rnplay.org/apps/n92mLg

Oddly, the compare function does get called with the expected args -- I tested this by just alert'ing the each of the values within the compare function.

**Comment by ide** [comment]
Doesn't the sorter need to return a number instead of a boolean?

**Comment by LeoJiaXin** [comment]
Yes, I have just tried
```
var a = [1,3,2];
a.sort((num1, num2) => num1 > num2 ? -1 : 1);
Global.alert('' + a);
```
It works

**Comment by LeoJiaXin** [comment]
Thanks! @ide @brentvatne ,I'll close this issue

**Comment by harwinvoid** [comment]
Thanks @LeoJiaXin
