### ISSUE TITLE
[0.73.0-rc.1] 'uncaught_exceptions' is unavailable: introduced in iOS 10.0 on RCT-Folly Scopeguard

### ISSUE THREAD

**Issue by efstathiosntonas** [facebook/react-native#39826]
### New Version

0.73-rc.1

### Old Version

0.72.5

### Build Target(s)

iOS

### Output of `react-native info`

```
System:
  OS: macOS 14.0
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 86.50 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /opt/homebrew/opt/ruby@2.7/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Issue and Reproduction Steps

After upgrading to `0.73-rc.1` iOS throws this error on Xcode 15

`'uncaught_exceptions' is unavailable: introduced in iOS 10.0`

![Screenshot 2023-10-05 at 08 12 22](https://github.com/facebook/react-native/assets/717975/e534af1e-6010-4fc9-85ab-5858a63f6efd)

**Comment by cipolleschi** [comment]
Hi @efstathiosntonas, thank you for reporting. However, that feels strange...
The [podspec for RCT-Folly](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/third-party-podspecs/RCT-Folly.podspec#L153) specifies 13.4 as version. As you can see, the [`min_supported_versions`](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/react_native_pods.rb#L47-L49) refers to the constant [`Helpers::Constants.min_ios_version_supported`](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/cocoapods/helpers.rb#L41) which is 13.4.

In fact, we can't reproduce it for a new app created with the template.
Have you run `pod install` before building?

Could you please double check which version is set for your RCT-Folly?
0. Open Xcode 
1. Navigate to your project `⌘+1`
2. Select the `Pods` Project
3. Select `RCT-Folly`
4. Select `Build Settings`
5. Filter for `Deployment`
6. look at the `iOS Deployment Target`

**Which version does it reports?** 

If it is not 13.4 could you please try:
1. in your main project folder run `yarn install`
2. `cd ios`
3. `bundle exec pod install`
4. Repeat the step to check which `iOS Deployment Target` for Folly do you have.

**Comment by gabrieldonadel** [comment]
This is actually being cause by reanimated and not RCT-Folly
