### ISSUE TITLE
When using Linking.openURL, the computer will crash

### ISSUE THREAD

**Issue by JoyXiyangyang** [facebook/react-native#39827]
### Description

After I forcibly restart my computer, an error will be reported when I run the project again,metro has encountered an error

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12490F
  Memory: 17.41 GB / 31.86 GB
Binaries:
  Node:
    version: 18.14.2
    path: D:\operating environment\node\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: D:\operating environment\node\npm.CMD
  Watchman:
    version: 20230806.083715.0
    path: D:\download\llq\watchman-v2023.08.07.00-windows\bin\watchman.EXE
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Added a button component to a blank page, where the click event is to jump to the webpage，using Linking.openURL('https://www.baidu.com'); .After the jump, the page was briefly displayed and the computer crashed immediately

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/109515244/beb58fac-c811-4aa6-b4dc-d0cc8fea1995)

**Comment by JoyXiyangyang** [comment]
0.72.5version，This problem still exists

**Comment by JoyXiyangyang** [comment]
The only difference is that after restarting, the project can still run normally in 0.72.5 version

**Comment by cortinico** [comment]
> The only difference is that after restarting, the project can still run normally in 0.72.5 version

I'm not sure what was your local issue, but this seems related to your specific environment.
We can't really help further without a dump or a stacktrace of the crash your computer experienced
