### ISSUE TITLE
Command /bin/sh failed with exit code 8

### ISSUE THREAD

**Issue by georgi-kovachev** [facebook/react-native#3983]
I am following this tutorial
https://facebook.github.io/react-native/docs/getting-started.html#content
And it worked fine but now I have this error when I retried.
+ DEST=/Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app
+ react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app/main.jsbundle --assets-dest /Users/User/Library/Developer/Xcode/DerivedData/AwesomeProject-abayzwfqcshpereqmyhwxuvxnzeo/Build/Products/Debug-iphonesimulator/AwesomeProject.app

/Users/User/Documents/Project/Test/AwesomeProject/node_modules/react-native/local-cli/cli.js:56
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/User/Documents/Project/Test/AwesomeProject/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/User/Documents/Project/Test/AwesomeProject/node_modules/react-native/cli.js:15:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
Command /bin/sh failed with exit code 8

My node version is 5.0.0.
I installed nvm also
 nvm ls
         v4.2.1
->       v5.0.0
         system
default -> node (-> v5.0.0)
node -> stable (-> v5.0.0) (default)
stable -> 5.0 (-> v5.0.0) (default)
iojs -> N/A (default)

Any idea please help.

**Comment by jcward10** [comment]
:+1:

**Comment by ilarip** [comment]
I started playing with React Native and found out the same problem. Xcode ```$PATH``` is different from the one in your user shell. I included _nvm_ to the loop by adding ```source ~/.bash_profile``` to ```../myproject/node_modules/react-native/packager/react-native-xcode.sh``` and it fixed the problem. You can also play with your project's settings in Xcode to fix this.

**Comment by georgi-kovachev** [comment]
Yay!!!
It worked with packager/react-native-xcode.sh file.
Thanks.
can you let me know which menu link of Xcode should I follow in case of using Xcode project's settings?

**Comment by TheSavior** [comment]
I had this problem as well and moifying the shell file fixed it. Since the [getting started](https://facebook.github.io/react-native/docs/getting-started.html#content) recommends nvm aliasing 4+ to default, it seems like react-native should be assuming nvm.

**Comment by jcward10** [comment]
That's a good work around, but I was hoping for a little more out of react native. Then, I realized there are 700+ issues. This does not seem like a great framework. Is this because react-native is in beta or something ?

**Comment by sHarenZzz** [comment]
@ilarip I try to doing something follow ur said.but it's not useful.ur means adding "source ~/.bash_profile" to react-native-xcode.sh? my english is pool. :) please help.

**Comment by gre** [comment]
dup https://github.com/facebook/react-native/issues/3948

**Comment by christopherdro** [comment]
@georgi-kovachev Try using 0.14.2.

**Comment by christopherdro** [comment]
@georgi-kovachev Any progress?

**Comment by georgi-kovachev** [comment]
I was able to make it working using packager/react-native-xcode.sh file which @ilarip commented 12 days ago.
But I couldn't find the settings in xcode

**Comment by christopherdro** [comment]
Glad to hear you got it working. Could you please close out the issue? Thanks!
