### ISSUE TITLE
Question: Packager: Configure alternative entry file location

### ISSUE THREAD

**Issue by tristangodfrey** [facebook/react-native#3984]
Haven't been able to find anything about this in the docs, but I'd like to find away of configuring the entry file location for the xCode packager. I found the following code in `packager/react-native-xcode.sh` , but I very much doubt that is depends completely on a hard-coded string.

```
react-native bundle \
  --entry-file index.ios.js \
  --platform ios \
  --dev $DEV \
  --bundle-output "$DEST/main.jsbundle" \
  --assets-dest "$DEST"
```

Any help would be greatly appreciated.

**Comment by SAPIBELPRODUCTIONS** [comment]
Me too I need help, how to upload files into reactive native.

**Comment by gre** [comment]
dup https://github.com/facebook/react-native/issues/3948

**Comment by tristangodfrey** [comment]
@gre Sorry for bothering you again but I just need a little bit of final clarification. I read the thread you referenced and I just need to know if I'm understanding this correctly.

My use case:

I open up the xcode project inside of my react-native project
I hit build & run in the xcode gui
The app runs with the message: `"Cannot find entry file index.ios.js in any of the roots"`

This is an expected error because I moved index.ios.js into my "source" directory. 

So am I correct in assuming that the proposed solution is to somehow modify my .bash_profile to automatically execute `react-native bundle` with the `--entry-file` option?

Thanks in advance.

**Comment by gre** [comment]
I'm afraid, there is no generic answer to solve this because it depends on environment of each developer.
You need to make that script having `react-native` in its PATH.

The solution is not to modify your .bash_profile (or whatever .profile) but to modify `node_modules/react-native/packager/react-native-xcode.sh` and add the relevant sourcing before `react-native` is executed.

If you use bash, I guess adding `source ~/.bash_profile` would work for you

**Comment by tristangodfrey** [comment]
Thanks a lot for your response @gre , unfortunately I can't actually find `node_modules/react-native/packager/react-native-xcode.sh` in my react-native project. Am I blind or just looking in the wrong place?

**Comment by tristangodfrey** [comment]
![image](https://cloud.githubusercontent.com/assets/4503386/11034095/0cd76b0e-86e9-11e5-8dbf-52b1be498420.png)

@gre Here's a screenshot of the directory structure I'm looking at.

**Comment by gre** [comment]
are you sure you are on 0.14 ? weirdly this script seems to be gone in master

**Comment by tristangodfrey** [comment]
Good point, I was on 0.12. Unfortunately I'm having an issue with updating from 0.12 to 0.14.1 when running `react-native upgrade` : 

`Error: Cannot find module 'babel-core/register'`

Any idea how to fix this @gre? I promise I'll get off your back once this is over haha.

**Comment by gre** [comment]
no I don't know regarding `react-native upgrade`, sorry

**Comment by tristangodfrey** [comment]
I've solved it with a clean install, and after the clean install of course I ran into issue #3946.
For future reference it might be handy for me to leave my solution here, I solved my problem by executing the following commands from project root:
```
cd node_modules/react-native/packager
./packager.sh --projectRoots={custom directory containing index.ios.js (full path)}
```

**Comment by montogeek** [comment]
@tristangodfrey This package build the bundle for RN, but, How to get the app installed in the Simulator?

**Comment by ThaJay** [comment]
WHY is this command so hard to find? Please add this to the documentation.
`--projectRoots=`

**Comment by ThaJay** [comment]
@tristangodfrey so what to import using projectRoots?
I'd assume it sees everything under the folder (so if I have the file core/helper.js `--projectRoots=/home/user/dev/project/core,/home/user/dev/project/view` would enable me to `import name from 'helper.js'` but no luck yet.)
