### ISSUE TITLE
Errors getting swallowed - `Uncaught Error: Invariant Violation: Level "fatal" not one of log,info,warn,error,mustfix`

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#3988]
I think my issue has something to do with the new error handling that was introduced here: https://github.com/facebook/react-native/commit/31b5b0ac010d44afe3e742e85c75a9ef9e72a9e0 (thanks @ide for reporting #3960 so I could figure this out haha)

```javascript
componentWillReceiveProps(nextProps) {
    if (changed(nextProps.isRegistered, this.props.isRegistered) && nextProps.isRegistered) {
      console.log('successfully registered');
      console.log('now authenticate');
      dispatch(AuthActions.authenticate());
    }

    if (changed(nextProps.isAuthenticated, this.props.isAuthenticated) && nextProps.isAuthenticated) {
      console.log('do relay mutation');
    }
  }
```

You can see that this method has a glaring error: `dispatch` is not defined.

However, the first time this method is called (and it gets past the first `if` statement), no error is thrown in the console and no red box pops up. When it's called a second time, the red box shows up and this appears in the console: 

![Image of console output](https://s3.amazonaws.com/f.cl.ly/items/0W1V1T0T3n072n1t1B0H/Screen%20Shot%202015-11-08%20at%208.55.53%20PM.png)

Any thoughts on this?

/cc @javache @nicklockwood

**Comment by javache** [comment]
I've been trying to remove mostfix in favor or fatal, I guess I missed a spot here: https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/Utilities/RCTLog.js. Thanks for reporting!

**Comment by skevy** [comment]
@javache FWIW I tried adding "fatal" in `RCTLog.js`...it resolves the error Uncaught Error, but doesn't prevent the error from being swallowed the first time it happens. Any ideas?

**Comment by javache** [comment]
Could you set a breakpoint in `_RCTLogInternal` in RCTLog.m and verify it gets called correctly?

**Comment by skevy** [comment]
Shoot. I feel stupid. It's an uncaught promise rejection in redux-promise that's eating the error. Then for some reason when I call it again, it throws it loudly and react-native's error handling picked it up.

Damn.

Well, at least I found the missing "fatal" :)

Thanks for your help.

**Comment by skevy** [comment]
(leaving open to track the original bug that this issue brought up)

**Comment by javache** [comment]
Fixed in https://github.com/facebook/react-native/commit/4b78ed2123e638f4169ee59fede35ac5ec204107
