### ISSUE TITLE
Images become invisible when Chrome Debugger is enabled

### ISSUE THREAD

**Issue by thstarshine** [facebook/react-native#3989]
As title, I just upgraded to RN 0.14.1 and apply new image asset structure.
Images display correctly when app is launched, 
but once the debugger is enabled, all static images become invisible.
(network images are not affected)

Using Node 4.0 under Ubuntu 14.04.

**Comment by Kudo** [comment]
I have the same issue for android on genymotion.
After some debugging and found the simulator cannot connect to dev server, then I use `adb reverse tcp:8081 tcp:8081` to solve the problem.
For your reference if it can help you.

**Comment by christopherdro** [comment]
@thstarshine Were you able find a solution?

**Comment by thstarshine** [comment]
Not yet. (FYI I'm now on RN 0.17 but the issue is still not solved yet)

**Comment by alvaromb** [comment]
Same here!

**Comment by alvaromb** [comment]
Feel free to vote here: https://productpains.com/post/react-native/images-become-invisible-when-chrome-debugger-is-enabled/

**Comment by martinbigio** [comment]
@foghina any clue what might be wrong? This seems like a blocker to use the debugger on Android

**Comment by tomauty** [comment]
I've found that they just take a long time to load, depending on how large the image is. Does the packager say that the app requested the asset?

**Comment by foghina** [comment]
This was fixed in 3d4889b and will go out in 0.18 :)
