### ISSUE TITLE
[iOS] allowFontScaling doesn't reset lineHeight

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#3991]
The allowFontScaling property only resets the font scaling but not line height. Therefore we get ugly typography if user sets largerText to be on in their settings.

![line1](https://cloud.githubusercontent.com/assets/6417336/11026779/412157b2-86e9-11e5-8290-0c354d34ab53.png)
![line2](https://cloud.githubusercontent.com/assets/6417336/11026793/62400024-86e9-11e5-98ea-25d75dc9f77e.png)

You can see clearly the difference here. First image has larger text on, second off. Both of them have allowFontScaling to false, but line height is different.

**Comment by mc-zone** [comment]
Same as #2783.

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/b3cfc598ced7b3e11cec1bf277159685411ac561
