### ISSUE TITLE
'-Wl -ld_classic ' in OTHER_LDFLAGS gets added on every Pod installation regardless if it already exists

### ISSUE THREAD

**Issue by xeroxoid** [facebook/react-native#39944]
### Description

After updating to react-native 0.72.5 every time `pod install` is run, the `'-Wl -ld_classic '` flags are added to `OTHER_LDFLAGS` even if they already exist.

I guess there is no check in-place for if the flags already exists in [this patch for XCode 15](https://github.com/facebook/react-native/blob/63557034fe642e72c521f470a86c1d5c502a2ae7/packages/react-native/scripts/cocoapods/utils.rb#L155C21-L155C21) as the code suggests that it will add the flags every time if XCode >= 15 and remove if not.

I also noticed that the in first addition the `-Wl` flag is not appended correctly as a separate entry but as part of `$(inherited)-Wl` which may or may not be part of the problem.

### React Native Version

0.72.5

### Output of `npx react-native info`

```
System:
  OS: macOS 14.0
  CPU: (12) arm64 Apple M2 Max
  Memory: 622.66 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: ~/Library/Caches/fnm_multishells/69989_1696588949148/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Library/Caches/fnm_multishells/69989_1696588949148/bin/yarn
  npm:
    version: 9.8.1
    path: ~/Library/Caches/fnm_multishells/69989_1696588949148/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/xxx/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /Users/xxx/.jenv/shims/javac
  Ruby:
    version: 3.0.0
    path: /Users/xxx/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

Reproduction repo url: https://github.com/xeroxoid/rn-xcode15-flag-repro/tree/main/ReproducerApp

- run `pod install`
- check `OTHER_LDFLAGS` in **project** build settings (targets are inherited)

### Snack, screenshot, or link to a repository

Other Linker Flags after running `pod install` 3 times:

![Screenshot 2023-10-06 at 14 10 16](https://github.com/facebook/react-native/assets/1199451/e17881fc-9447-4779-9a0d-685d41c1248a)

**Comment by cipolleschi** [comment]
Thanks for reporting. We already provided a fix for it and it will be included in 0.72.6. https://github.com/facebook/react-native/commit/67ebc7c7d5e04405d59b8cd29dd6cf7d33115cd5

**Comment by gkartalis** [comment]
Will this be included on a follow-up for 0.70.14 ?

**Comment by cipolleschi** [comment]
0.70.14 doesn't have that issue, as we fixed it in [this commit](https://github.com/facebook/react-native/commit/735d06c01fe743fad58213e80bca64a0c70ea8ca).

Make sure to cleanup the project and that the `xcodebuild --version` output is correct:
* if it outputs Xcode 15, it adds the flags if they are not there
* if it outputs Xcode 14, it removes the flags if they are present.

**Comment by simon-assistiq** [comment]
I do not have these flags locally, I am running Xcode 15.2 and I set the min deployment version in Xcode to iOS 16. Don't have issues when I build locally but when I run on GitHub Actions it's adding these flags (which breaks my Fastlane lane because I have a check to make sure the repo is clean before building). Based on the [Xcode 15 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes) these flags shouldn't be needed if the deployment target is iOS 15+.

I am using React Native 0.73.6.

**Comment by cipolleschi** [comment]
@simon-assistiq I'm sorry that you are facing this issue. The code that adds those flags [is here](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/cocoapods/utils.rb#L177-L196) and the `is_using_xcode_15_0` is [here](https://github.com/facebook/react-native/blob/0.73-stable/packages/react-native/scripts/cocoapods/utils.rb#L412-L428).

Make sure that you are using the right version of Xcode in Github Actions. I feel that there is some misconfigurations between your setup and GH Actions.

**Comment by simon-assistiq** [comment]
Oh so these changes are only supposed to show up in 15.0 and not later versions?

**Comment by simon-assistiq** [comment]
According to logs, GitHub Actions is using the same version of Xcode (15.2, 15C500b)

<img width="382" alt="image" src="https://github.com/facebook/react-native/assets/148139046/c5e539bd-443f-4bd5-85fc-e05387df0f9c">

**Comment by simon-assistiq** [comment]
Though now it looks likely that it's happening because I call the Xcode step *after* the yarn / pod install steps
