### ISSUE TITLE
v0.14 Static Image Resource In Custom UI Module

### ISSUE THREAD

**Issue by edcs** [facebook/react-native#3995]
The new static image resource loader looks great - being able to store project images in with the JS seems super useful!

However, I've built a wrapper for the Google Maps SDK and I was using the old method to load the map markers. The JS looked a bit like this:

```javascript
{
    latitude: addresses[i].location.lat,
    longitude: addresses[i].location.lng,
    icon: require('images!GreenMarker'),
}
```

And the Objective C looked like this to then get the path:

```objective-c
NSString *markerPath = marker[@"icon"][@"path"];
```

This worked great - It'd return the correct image path which I could then `[UIImage imageNamed:markerPath]` into a UIImage. The new loader seems to return an NSNumber which looks to be null. What am I meant to be doing with this? Is it possible to `require` images into custom UI modules or should I be just passing a string reference to the image and then loading it manually? I can't quite figure out what's going on in the RCTImageView class.

**Comment by rpastorelle** [comment]
@edcs Did you ever figure this one out?

**Comment by browniefed** [comment]
@facebook-github-bot close
