### ISSUE TITLE
React-RCTAppDelegate unstable checksum in Podfile.lock (new architecture)

### ISSUE THREAD

**Issue by heath-clink** [facebook/react-native#39971]
### Description

We observed that the checksum for `React-RCTAppDelegate` in Podfile.lock was unstable, in that it changes from one developer to another. This causes a problem with our CI which uses the `--deployment` flag to `pod install`, causing it to fail because the checksum for `React-RCTAppDelegate` appears to have changed.

Tracked it down to `ios/Pods/Local Podspecs/React-RCTAppDelegate.podspec.json` which contains a fully-qualified path like `/Users/redacted-username/depots/myapp/etc` which will be different for different users/environments, and so the checksum of that file will be different for those different users.

### React Native Version

0.72.5

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.5.2
  CPU: (10) arm64 Apple M1 Max
  Memory: 114.30 MB / 32.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2023.08.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/username-redacted/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/username-redacted/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1. `mkdir example1 example2`
2. `(cd example1 && npx react-native@latest init AwesomeProject)`
3. `(cd example2 && npx react-native@latest init AwesomeProject)`
4. `(cd example1/AwesomeProject/ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install)`
5. `(cd example2/AwesomeProject/ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install)`
6. `diff example?/AwesomeProject/ios/Podfile.lock`
7. Observe different checksums for React-RCTAppDelegate, should be the same.
8. `diff example?/AwesomeProject/ios/Pods/Local\ Podspecs/React-RCTAppDelegate.podspec.json`
9. Observe differing paths, which is the cause of differing checksums

### Snack, screenshot, or link to a repository

no reproducer needed, just follow the steps to reproduce

**Comment by heath-clink** [comment]
This patch replaces `ENV['app_path']` with `${REACT_NATIVE_PATH}/../..`. This works in my environment but there is probably a better way to implement the fix.

```
--- a/node_modules/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec
+++ b/node_modules/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec
@@ -101,10 +101,10 @@ Pod::Spec.new do |s|
       :script => "
 WITH_ENVIRONMENT=\"$REACT_NATIVE_PATH/scripts/xcode/with-environment.sh\"
 source $WITH_ENVIRONMENT
-${NODE_BINARY} ${REACT_NATIVE_PATH}/scripts/codegen/generate-legacy-interop-components.js -p #{ENV['APP_PATH']} -o ${REACT_NATIVE_PATH}/Libraries/AppDelegate
+${NODE_BINARY} ${REACT_NATIVE_PATH}/scripts/codegen/generate-legacy-interop-components.js -p ${REACT_NATIVE_PATH}/../.. -o ${REACT_NATIVE_PATH}/Libraries/AppDelegate
       ",
       :execution_position => :before_compile,
-      :input_files => ["#{ENV['APP_PATH']}/react-native.config.js"],
+      :input_files => ["${REACT_NATIVE_PATH}/../../react-native.config.js"],
       :output_files => ["${REACT_NATIVE_PATH}/Libraries/AppDelegate/RCTLegacyInteropComponents.mm"],
     }
   end

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/31121

**Comment by heath-clink** [comment]
This is NOT a duplicate of #31121. That was fixed by a commit which is already released. This is a different podspec file than the one in #31121.

**Comment by cortinico** [comment]
> This is NOT a duplicate of #31121. That was fixed by commits which are already in currently released react-native versions. This is a different podspec file than the one in #31121.

Thanks for the clarification @heath-clink.
@cipolleschi can you take a look at this one?

**Comment by cipolleschi** [comment]
The problem here is that the script needs to access to the root project.
The `ENV['APP_PATH']` is the right environment variable that allow us to retrieve that.

The suggested patch works for you but is not general enough to be applied to everyone.

I think that the proper approach is to:
1. fetch the  `ENV['APP_PATH']` value to get the path to the app
2. fetch the pods path, where the pods are installed
3. compute the relative path from the pods path to the app path
4. use that as base relative path.

I'll try to put up something.
