### ISSUE TITLE
Make MapView fill entire view

### ISSUE THREAD

**Issue by antonshevchenko** [facebook/react-native#400]
I'm not too sure how to achieve this. I've been trying using `flex: 1`, but it doesn't show up in the view since I don't define `width` or `height`.

Here's a code sample:
```js
var app = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <MapView style={styles.map}>
        </MapView>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  map: {
    flex: 1,
  },
});
```

**Comment by martco** [comment]
Mine shows full-view. I had to add a `latitude` and `longitude` props. I also am just rendering the `MapView` without its parent. My `MapView` has the `container` styles.

**Comment by antonshevchenko** [comment]
@martco Thanks! Remove the `<View>` fixed it.
