### ISSUE TITLE
Getting error when adding/removing webviews

### ISSUE THREAD

**Issue by CorpusCallosum** [facebook/react-native#4002]
I have a ScrollView component that is loading several WebViewBridge components as it's children. This all works fine and good, except when I remove some of these children from the ScrollView via a state change, I sometimes get this error:

>2015-11-09 10:07:35.066 taFlashCard_1_0_0[72905:6619776] *** Assertion failure in __53-[RCTWebViewManager(WebViewManager) callbackCleanup:]_block_invoke(), /Users/jkalish/Documents/Work/IBM Studio/TA15/ta15-native-app/node_modules/react-native-webview-bridge/WebViewBridge/RCTWebViewManager+WebViewManager.m:37

>2015-11-09 10:07:35.067 [error][tid:main][RCTUIManager.m:887] Exception thrown while executing UI block: Invalid view returned from registry, expecting RKWebView, got: (null)

Not sure what this means or what's causing it, any ideas?

**Comment by christopherdro** [comment]
This looks like a issue with the external module that your using. I would go ahead and open up and issue with them.

**Comment by jaygarcia** [comment]
Please close this issue.

**Comment by ide** [comment]
Yeah. Looks like this is coming from eact-native-webview-bridge.
