### ISSUE TITLE
optical glitches when using borderradius with borderWidth 

### ISSUE THREAD

**Issue by klausbreyer** [facebook/react-native#4004]
Hey there all together, 

I wanted to design an record button with onboard styles. 

```
        <TouchableOpacity onPressIn={this.record.bind(this)} onPressOut={this.pause.bind(this)} style={styles.controlBtn}>
        </TouchableOpacity>
```
```
    controlBtn: {
        backgroundColor: "red",
        padding: 10,
        opacity: 1,
        borderRadius: 40,
        height: 80,
        width: 80, 
        borderWidth: 10,
        borderStyle: 'solid',
        borderColor: "#ccc"
    },
```

this is the result. 

I don't think, that this is intended. Or is it? :) 

![screen shot 2015-11-09 at 16 36 42](https://cloud.githubusercontent.com/assets/32771/11037841/3a692af0-8700-11e5-9a0d-a30613e7cb86.png)

**Comment by jeanregisser** [comment]
Thanks! This has already been reported under https://github.com/facebook/react-native/issues/2089

**Comment by ide** [comment]
Yep, covered in #2089 so I'll close this dupe. I don't think anybody is working on it though, so if you want to give it a try fixing it please go ahead.
