### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by hojberg** [facebook/react-native#4006]
After upgrading to React Native 0.14 I get this when trying to build. (node 5.0.0; npm 3.3.6)
```
const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
Command `bundle` unrecognized. Did you mean to run this inside a react-native project?
Command /bin/sh failed with exit code 1
```

**Comment by christopherdro** [comment]
Related 3948

**Comment by hojberg** [comment]
https://github.com/facebook/react-native/issues/3948 deals with `exit code 127`.
In that thread @samsalisbury solves the `exit code 1` problem with updating his babelrc.
However I do not have that specific feature whitelisted and i'm on Node 5, not 4.

**Comment by christopherdro** [comment]
@hojberg I understand that the error codes might be different but I just wanted to make reference that all of these issues might be related to the addition of https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh

**Comment by hojberg** [comment]
@christopherdro ah that makes sense; reasonable :)

**Comment by hojberg** [comment]
Fixed by RN 0.14.2

**Comment by sankhadeeproy007** [comment]
I had a RN 0.13.2 project which was working fine on Xcode 6. Now after upgrading 0.16.0-rc and Xcode 7.1 I'm getting `Command /bin/sh failed with exit code 1` on building. My node version is 4.2.1 and npm is 3.4.0. The solution at #3948 doesn't seem to work for me either. Any help regarding this?

**Comment by marclundgren** [comment]
@sankhadeeproy007 I'm suddenly having this problem on RN 0.17. Did you ever learn how to resolve the error yourslef?

**Comment by rainer-liao** [comment]
+1

**Comment by rainer-liao** [comment]
@marclundgren 
I try Target -> Build-Phases -> Bundle React Native code and Images 
check Run script only when installing.

**Comment by Michael-Jas** [comment]
I had this same issues and spent a few hours trying to get it fixed. @rainer-liao  thank you!

**Comment by JuniorJser** [comment]
@rainer-liao  Thank you!!

**Comment by qasimalbaqali** [comment]
@rainer-liao thank you! +1 works like a charm

**Comment by rock1002** [comment]
@rainer-liao Thanks for this solution....really helpful

**Comment by wangxiaofeng0010** [comment]
@rainer-liao thank you so much !!!!

**Comment by NativeR** [comment]
thanks @rainer-liao!

**Comment by TheoGit** [comment]
@rainer-liao you saved the day - thanks!  Any idea why/how this problem seems to appear out of nowhere?

**Comment by SumaiyaKhan** [comment]
Thank You so much for your suggestion!
It worked... 
You are a STAR !!!

**Comment by MIFind** [comment]
Thank you so much!
