### ISSUE TITLE
Error on ./gradlew assembleRelease

### ISSUE THREAD

**Issue by mehdinasiripoor** [facebook/react-native#40078]
### Description

i can't get export from even new project. ./gradlew clean work but ./gradlew assembleRelease doesn't work.

java --version :
openjdk 21 2023-09-19 OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35) OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)

build.gradle :
```
buildscript {
ext {
    buildToolsVersion = "33.0.0"
    minSdkVersion = 21
    compileSdkVersion = 33
    targetSdkVersion = 33

    // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
    ndkVersion = "23.1.7779620"
}
repositories {
    google()
    mavenCentral()
}
dependencies {
    classpath("com.android.tools.build:gradle")
    classpath("com.facebook.react:react-native-gradle-plugin")
}}
```

gradle version:distributionUrl=https://services.gradle.org/distributions/gradle-8.0.1-all.zip

and the error is :

```
> Could not resolve all files for configuration ':app:androidJdkImage'. Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}. > Execution failed for JdkImageTransform: /Users/mehdinasiripoor/Library/Android/sdk/platforms/android-33/core-for-system-modules.jar. > Error while executing process /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home/bin/jlink with arguments {--module-path /Users/mehdinasiripoor/.gradle/caches/transforms-3/c40273315238db45e8af12bd10f1acc3/transformed/output/temp/jmod --add-modules java.base --output /Users/mehdinasiripoor/.gradle/caches/transforms-3/c40273315238db45e8af12bd10f1acc3/transformed/output/jdkImage --disable-plugin system-modules}
```

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 111.09 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.11.1
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 8.14.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2021.10.11.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "33"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33-ext4 | Google Play ARM 64 v8a
      - android-33-ext4 | Google Play Intel x86_64 Atom
      - android-33-ext5 | Google Play ARM 64 v8a
      - android-33-ext5 | Google Play Intel x86_64 Atom
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

i can't get apk release from my project

### Snack, screenshot, or link to a repository

![Screenshot 1402-07-15 at 21 44 23](https://github.com/facebook/react-native/assets/39670236/61aa16d3-6d12-4d3d-b649-4ae051135a92)
![Screenshot 1402-07-15 at 21 44 56](https://github.com/facebook/react-native/assets/39670236/9feeb581-e692-4c9b-b62d-52b024ee12a6)

**Comment by bekroz** [comment]
Try removing your nkd folder. Maybe it's corrupted:

`rm -rf ~/Library/Android/sdk/ndk`

**Comment by frankcalise** [comment]
Can you try setting up your JDk to the recommended version found in [Environment Setup](https://reactnative.dev/docs/environment-setup?platform=android#installing-dependencies) ?

> If you have already installed JDK on your system, we recommend JDK 11. You may encounter problems using higher JDK versions.

**Comment by cortinico** [comment]
What is `':app:androidJdkImage'`? This is not part of React Native nor part of the Android SDK.
Can you share your `android/app/build.gradle` @mehdinasiripoor ?
