### ISSUE TITLE
react-haste dependency causes failure inside ReactErrorUtils

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#4007]
I get a `document is undefined` error from ReactErrorUtils.js from `react-haste` on the latest master branch.

It looks like it was already fixed in facebook/react...but it's not in the latest `react-haste` package: https://github.com/facebook/react/blob/master/src/shared/utils/ReactErrorUtils.js#L63-L65

/cc @spicyj

**Comment by spicyj** [comment]
Sorry, this happens using Chrome debugging (which you can turn off for now with a Cmd-D). I'll upgrade soon to 0.14.2 and then this shouldn't be a problem.

**Comment by skevy** [comment]
Thanks @spicyj. :+1:

**Comment by spicyj** [comment]
No problem.

**Comment by christopherdro** [comment]
I'm running to this again on master with Android. Am I missing something?

Here are the errors the console outputs.

`document is not defined`
`Requiring module "React" which threw an exception`
`Cannot read property 'runApplication' of undefined`

**Comment by skevy** [comment]
@christopherdro yah, I'm getting this too after pulling down master, running the example Movie project on iOS, and debugging in chrome.

I'm really not sure where the regression was, because this was definitely working. Unless someone knows offhand, this is going to be kind of a pain to find.

**Comment by skevy** [comment]
So, what seems to be happening, is that when I run npm install, on a completely clean react-native checkout, using npm v2.14.14 (latest npm 2), it's installing react-haste@0.14.0. 

It clearly says react-haste@0.14.2 in the package.json...so i'm very confused. 

@spicyj do you have any ideas here?

**Comment by spicyj** [comment]
Maybe the shrinkwrap file is wrong.

**Comment by skevy** [comment]
Ha, yep. Didn't even think to look there.

**Comment by skevy** [comment]
Thanks for the tip @spicyj

**Comment by skevy** [comment]
It broke here: i ask because this commit broke it: https://github.com/facebook/react-native/commit/b699526123ea9e141c3bd106cd6e839634361820.

@mkonicek do you need to regenerate on your side? Or can we manually fix?

**Comment by mkonicek** [comment]
Oops sorry. In our internal repo in npm-shrinkwrap.json I see:

    "react-haste": {
      "version": "0.14.2",
      "from": "react-haste@0.14.2",
      "resolved": "https://registry.npmjs.org/react-haste/-/react-haste-0.14.2.tgz"
    },

On github it's 0.14.0. In package.json it's 0.14.2.

Fixed in https://github.com/facebook/react-native/commit/f9f123ba96fea76bce6b21aabb5da4d79ee26db7.

**Comment by mkonicek** [comment]
When does this actually happen? Does it happen when running examples? Or when using Chrome debugging with 0.16? I don't understand the issue description very well:

> I get a document is undefined error from ReactErrorUtils.js from react-haste on the latest master branch.

**Comment by mkonicek** [comment]
Thanks for debugging this @skevy and @spicyj!

**Comment by spicyj** [comment]
Should happen when any React event handler fires (e.g., tapping) when using Chrome debugging.

**Comment by skevy** [comment]
Yah, I've confirmed that this is fixed now that react-haste is 0.14.2 in the shrinkwrap. That's what was causing it, and has been broken for 28 days and through 0.16 and 0.16rc. Curious that we haven't received more bug reports about it.

**Comment by christopherdro** [comment]
:rocket:
