### ISSUE TITLE
[0.14.0] Requiring a RN class/utility from a custom module -- breaks with 14.x

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#4009]
I get an exception when trying to require `EdgeInsetsPropType` in a custom module with 0.14.0, where it tries to find that file in `./`. With 0.13.2, it works perfectly. What are the new rules for release 0.14.0 to require such a file from the RN library for custom components?

```
var EdgeInsetsPropType = require('EdgeInsetsPropType');
```

**Comment by ide** [comment]
The simple rule is: always go through `require('react-native')`, which is the public interface. For this specific case, EdgeInsetsPropType is publicly exported: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js#L90.
