### ISSUE TITLE
MapView is not visible when I build to device

### ISSUE THREAD

**Issue by martco** [facebook/react-native#401]
![image](https://cloud.githubusercontent.com/assets/420959/6881643/72b9525a-d525-11e4-9a15-cd932f83bcf0.png)

It works fine in the simulator but doesn't appear to show when I build to device. Also, can I use Chrome developer tools to debug device builds? If so, how?

**Comment by robbiemccorkell** [comment]
There are instructions on deploying to devices inside AppDelegate.m, I'm sure this will be included in the docs soon. And to run chrome dev tools just press CMD+D twice in the simulator.

**Comment by martco** [comment]
Cool thanks. I was able to build to device (I think), but I didn't know about cmd+d twice in the simulator. Would you happen to know how that works on device?

**Comment by martco** [comment]
I see the map on simulator just fine:
![image](https://cloud.githubusercontent.com/assets/420959/6881643/72b9525a-d525-11e4-9a15-cd932f83bcf0.png)

**Comment by martco** [comment]
It had to do a with a firewall issue. I was blocking access to my laptop from other devices. Thanks!

**Comment by robbiemccorkell** [comment]
No worries, have fun!

**Comment by martco** [comment]
I am having so much fun :+1:

**Comment by vjeux** [comment]
> It had to do a with a firewall issue. I was blocking access to my laptop from other devices. Thanks!

It would be nice to have a better error message. Do you think you can add a warning when that happens?

**Comment by sahrens** [comment]
For device debugging, you should be able to physically shake the decide and select debug mode from the options. If you have things configured to load the bundle from your computer's IP, it should be able to find it if you're on the same wifi network. We'll add proper docs at some point ;)

**Comment by sahrens** [comment]
Sorry, setting the bundle to load over wifi will let you live reload, but to debug you'll probably need to change the websocket config, which is less explored territory. Let us know if you can get it working.

**Comment by martco** [comment]
I'll take a stab at it.
