### ISSUE TITLE
`SliderIOS` has no propType for native prop `RCTSlider.onChange` of native type `BOOL`

### ISSUE THREAD

**Issue by patelsan** [facebook/react-native#4011]
I just did `react-native initi TestApp`, it is running in to following error on launch, any suggestions?

``SliderIOS` has no propType for native prop `RCTSlider.onChange` of native type `BOOL``

**Comment by patelsan** [comment]
I had multiple versions of react-native running side by side, may be that caused the issue? It's working fine after the restart! closeing the issue.

**Comment by rainbowhat** [comment]
help!

**Comment by gs-akhan** [comment]
@patelsan  restarting what ?? 
Thanks

**Comment by patelsan** [comment]
Restarting the Xcode and the simulator.

On Fri, Dec 11, 2015 at 4:12 AM, facebook/react-native
<reply@reply.github.com>
wrote:
@patelsan [https://github.com/patelsan] restarting what ??
Thanks

—
Reply to this email directly or view it on GitHub
[https://github.com/facebook/react-native/issues/4011#issuecomment-163899263] .[https://github.com/notifications/beacon/AA21MXiiTjAzzV6uk-86_KrjWgUCfWxaks5pOpkFgaJpZM4Ge0N2.gif]

**Comment by PWDream** [comment]
@patelsan I restart the XCode and simulator ,but the don't work? Can you help me ?

**Comment by patelsan** [comment]
It did work, but might be just a coincidence. I didn't make any other changes. Sorry, I wish I could help more.

On Tue, Dec 22, 2015 at 12:27 PM, PWDream <notifications@github.com> wrote:

@patelsan<https://github.com/patelsan> I restart the XCode and simulator ,but the don't work? Can you help me ?

**Comment by PWDream** [comment]
Thanks

**Comment by gs-akhan** [comment]
This happened to be after the upgrade from react-native 0.15 to 0.16. I then created new app and moved the files and error disappeared. If this helps :(
