### ISSUE TITLE
[Android] fetch throwing "Network request failed" in 0.14

### ISSUE THREAD

**Issue by madwed** [facebook/react-native#4013]
Fetch is throwing a `Network request failed` error when I try to make a request to a local server.  I'm pretty sure the request isn't getting out of the app.  I've checked and double checked the request headers and target URL.  I tried disabling CORS on my local server.  I'm using digits in my app and digits is able to make contact with its server outside the app and return authorization.

**Comment by madwed** [comment]
Figured out the issue, because the android emulator runs in a VM localhost points at the device.  You need to specify your ip instead.

**Comment by blacksunset** [comment]
Hi, how to specify the ip?

**Comment by waifo** [comment]
Where do we need to change the ip...?
