### ISSUE TITLE
[Android] Transparent components capture touch events unlike in iOS

### ISSUE THREAD

**Issue by isair** [facebook/react-native#4014]
https://rnplay.org/apps/P0bQDA

Two components placed on top of each other, each have a button centered inside of them. Top component is set to have 0 opacity. When the center of the screen is tapped on iOS the visible component responds to the touch event, but on Android the invisible component that is on top does.

**Comment by ide** [comment]
This difference should be fixed in an upcoming version of React Native (certainly 0.15.0-rc), where Android's behavior is the default and you can use `pointerEvents="none"` to get back to iOS's behavior. Thanks for reporting though!

**Comment by aleclarson** [comment]
@ide Are breaking fixes like this one described somewhere? I like to know about the changes that could possibly break my UI. Thanks! :smile:

**Comment by ide** [comment]
We'll try to cover breaking changes in the release notes if time permits. It's a rather manual task so sometimes we don't cover everything or have the time toe document the release in detail, so the commit log is another good place to look.
