### ISSUE TITLE
[Image] New assets system breaks defaultSource

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#4016]
Specifying the `defaultSource` prop like so (new assets system):
```javascript
defaultSource={require('MyApp/assets/placeholder.png')}
```
Results in the red box error `JSON value 'http://localhost:8081/assets/assets/placeholder.png?platform=ios&hash=blahblahblah' of type NSString cannot be converted to an image. Only local files or data URIs are supported`

If I reference it from my Xcode bundle (the old system):
```javascript
defaultSource={require('image!placeholder')}
```
it loads fine. It should also be noted that I can set that exact same `require` to the normal `source` prop, and the image loads (just to confirm the image definitely exists in the right place).

**Comment by srosenda** [comment]
+1

**Comment by timzaak** [comment]
+1

**Comment by Sh3rawi** [comment]
+1

**Comment by Sh3rawi** [comment]
on 0.17 its still broken.

**Comment by scaletimes** [comment]
+1
