### ISSUE TITLE
Handling environment configurations

### ISSUE THREAD

**Issue by igo88** [facebook/react-native#4017]
It would be great if i could name files this way:

configuration.[environment].js just like we are doing with platform. (index.android/index.ios)

Does this feature already exists?? Which would be the best way to include modules based on environment configuration?

Thanks,

Rodrigo.

**Comment by facucacho** [comment]
+1

**Comment by amgarcia** [comment]
+1

**Comment by ide** [comment]
What do you mean by environment? Like dev vs. prod? (There is a global variable called `__DEV__` that you can control via the `?dev=` query param in the JS bundle URL.)

**Comment by igo88** [comment]
For example, i would like to load specific module if i am running at a staging environment.

I can set something like dev=staging or dev=production?

Thanks

**Comment by ide** [comment]
There are no staging vs. production options in the packager. You'll have to determine that at runtime.

**Comment by vespakoen** [comment]
I saw some references to this in the packager, using `.android.js` and `.ios.js` postfixes, would you want to test it out (on the latest react) and let us know?

**Comment by Kureev** [comment]
@vespakoen these postfixes works, but I believe the question is about an environment, not a platform.
What is a next action for this issue? Should we close it?

**Comment by jsierles** [comment]
@facebook-github-bot no-reply
