### ISSUE TITLE
Is it possible to use replacement module with Packager?

### ISSUE THREAD

**Issue by zsszatmari** [facebook/react-native#4018]
Hi!

browserify can do the following: I specify this in package.json:

```
"browser": {
    "request": "browser-request"
  }
```

and every module which depends on request will use browser-request module instead. Is similar possible with Packager?
(btw I would happily rtfm but couldn't find a documentation for packager)

Thank You!

**Comment by ide** [comment]
Yes, "browser" field should already be honored. There's a PR out to add a "react-native" field: https://github.com/facebook/react-native/pull/2208

**Comment by zsszatmari** [comment]
Thanks for the quick answer! However, I can't seem to make it work. For example I have a module in my package.json and hence node_modules which depends on 'request' which depends on 'net'. I would like it to require browser-request instead, but it's still ```Requiring unknown module "net"``` :/
(Restarted packager, no help)

**Comment by siuying** [comment]
react native packager do not seems to do it on dependencies? if it is just at top level, it would not have much use as I can always use require("react-native-level-fs") instead of require("fs").

**Comment by vespakoen** [comment]
It does do it recursively, however, some packages expect to be run after being "browserified", and depend on node modules that browserify will automatically replace / shim with a browser compatible version.

At the moment you can use: https://github.com/mvayngrib/rn-nodeify to "hack" the package.json's of your sub-node_modules to add in the necessary replacements

**Comment by jsierles** [comment]
Closing this out in favor of discussion on the meta-issue at #6253.
