### ISSUE TITLE
[Asset System] Does the new asset system support GIF files?

### ISSUE THREAD

**Issue by isair** [facebook/react-native#4019]
I've written a shell script that generates an Images module with all images required in it. Inside this module generated by the script, the following line

```js
uie_activity: require('./img/uie_activity.gif'),
```

causes a resolve error.

![simulator screen shot 9 nov 2015 13 58 37](https://cloud.githubusercontent.com/assets/988213/11047986/21e718a4-86ea-11e5-8469-eed63be341df.png)

However, this is the last require inside this module and all other images (PNGs) are required successfully and I can confirm that the path is correct.

**Comment by christopherdro** [comment]
PR #3738 resolves this.
Related to #3731.
