### ISSUE TITLE
Reconsider restrictions in patents file

### ISSUE THREAD

**Issue by honkskillet** [facebook/react-native#402]
As detailed on this HN post... https://news.ycombinator.com/item?id=9271331

````
The first thing I do now on each Facebook open-source reveal, 
is to check the PATENTS file for the toxic second paragraph, 
to see if they've changed it.
Sadly, no. I can't imagine being able to use this at any decent-sized company with lawyers. :-( 
https://github.com/facebook/react-native/blob/master/PATENTS 
See for example the discussions at https://news.ycombinator.com/item?id=9111849 
(eg. https://news.ycombinator.com/item?id=9113515)

**Comment by vjeux** [comment]
We updated the patent grant:
https://code.facebook.com/posts/1639473982937255/updating-our-open-source-patent-grant/

**Comment by gaearon** [comment]
React Native (including Metro, Fresco, and Yoga) has been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
