### ISSUE TITLE
synatax error attempted to redefine property backgroundcolor

### ISSUE THREAD

**Issue by mymickey** [facebook/react-native#4032]
synatax error attempted to redefine property backgroundcolor line 11353

**Comment by ide** [comment]
You probably have a syntax error in your code where you are defining backgroundColor twice in the same object.

**Comment by santhosh77h** [comment]
@ide  at the time of runtime

>  i got this error that: Attempted to redefine property
> textAlign

 but if I do `DebugJSRemotely` that error never comes why so and how can i access bundle file
