### ISSUE TITLE
v0.14.1 Static Image Asset Unable to Be Required

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#4033]
I was not able to require the static image, while the image is clearly imported into Android Studio under Res/drawable folder. I did run react-native run-android command line to compile the image but the framework returns "requiring unknown module "image!menu" "error. I have noticed previous discussion about similar errors on v0.3.0 but that seems to be for the iPhone platform and fix patched for that specific report. I've also tried restarting the JS server and updating Android Studio to latest. V0.14.0 returns the same error. 

Previous Github discussion: https://github.com/facebook/react-native/issues/282

My system info is Mac OS+RN0.14.1 (Android) + Genymotion. I've spent hours today on this bug as image is a crucial part of my app. Really appreciate your help！

Same issue has been raised in StackOverflow: http://stackoverflow.com/questions/33625495/static-image-asset-unable-to-be-required-rn-v0-14-1

**Comment by Kallikrein** [comment]
relaunching with ```react-native start --assetRoots ./android/app/src/main/res/```  fixes the error message but the image is not displayed.

```<Image source={require('image!ic_launcher')} style={styles.icon} />```

It's my first time trying react-native so it might be my image that fails to display.

uri image works fine though.

**Comment by ACCTFORGH** [comment]
@Kallikrein Thanks! The command works, finally the bug is solved! For image not displaying, I usually check the styles to see if there's anything missing. Typically it's a missing flex:1 or margin setting issue. Thanks a lot again for the command!

**Comment by Kallikrein** [comment]
Update: 

I managed to get images, even in drawable-mdpi "à la android".

I had to relaunch compilation with ```react-native run-android```.
It crashed the server. Once relaunched, images are displaying correctly.

**Comment by aj9045** [comment]
I always get a `Requiring unknown module "image!image_name"` error.  So after I run `react-native run-android` I **always** have to run `react-native start --assetRoots ./android/app/src/main/res/`, which is a bit irritating to run each time I need to run the packager.  But, it does work with that.

**Comment by jsierles** [comment]
@facebook-github-bot answered
