### ISSUE TITLE
Customize the  js exception handler

### ISSUE THREAD

**Issue by sospartan** [facebook/react-native#4036]
'Redbox' handle the js or native execute exception in dev mode , while I am wandering can i customize the error handler in non-dev mode ?  It will help in these use cases:
* Notify user that app has a unexpected error , reload app or leads to a customize error handler bundle
* collect error data to server for further analysis   
...

Is there already a way to achieve this ,or should I try to make a pull request ? @ide @mkonicek

**Comment by sospartan** [comment]
ping @mkonicek

**Comment by browniefed** [comment]
I believe this will be a possibility with the new `handleErrors` in React 15. If that doesn't appear to be the case then feel free to reopen

**Comment by browniefed** [comment]
@facebook-github-bot close
