### ISSUE TITLE
React-Native-CLI not up to date?

### ISSUE THREAD

**Issue by orta** [facebook/react-native#404]
The docs say:
```
npm install -g react-native-cli
react-native init AwesomeProject
```

When I ran it:

```
 ~/s/ios  $ npm install -g react-native-cli
/usr/local/bin/react-native -> /usr/local/lib/node_modules/react-native-cli/index.js
react-native-cli@0.1.3 /usr/local/lib/node_modules/react-native-cli

 ~/s/ios  $ react-native init AwesomeProject
Command `init` unrecognized
Usage: react-native <command>

Commands:
  start: starts the webserver

```

Could you be referring to a version not on npm yet?

**Comment by tadeuzagallo** [comment]
You usually get this message when you already inside a React Native project, can you check it?

**Comment by orta** [comment]
Nope, I'm inside a project container folder `/Users/orta/spiel/ios`

**Comment by tadeuzagallo** [comment]
Is there any chance you have a `/Users/orta/spiel/ios/node_modules/react-native` folder?

Because `react-native` runs the script installed by the `react-native-cli` module, and then this script checks for the `cli.js` file inside the `react-native` module.

**Comment by orta** [comment]
I do, how strange, thanks for the explanation. I'm still extremely new to using NPM, thanks for the patient walk though :+1:

**Comment by orta** [comment]
After a `rm -rf node_modules` and a re-run of `npm install -g react-native-cli` I got it working perfectly:

```
~/s/ios  $ react-native
You did not pass any commands, did you mean to run `react-native init`?
```

**Comment by tadeuzagallo** [comment]
No problem, glad you got it working! :)

**Comment by amasad** [comment]
Maybe we should add this info to the message?

**Comment by tadeuzagallo** [comment]
@amasad Couldn't do any harm... Maybe the first line outputted could be the context it's running.
