### ISSUE TITLE
[ios]RCTActionSheetManager.showActionSheetWithOptions is undefined

### ISSUE THREAD

**Issue by divefox** [facebook/react-native#4042]
Hi,guys:
when I debug ActionSheet in the simulator Ipad air, I have the problem like  https://github.com/facebook/react-native/issues/3498
Then, I update my ActionSheetIOS like 
https://github.com/facebook/react-native/commit/a859d9e9315c2ff79432ffbf4b636ef78c990567
But,it still have the problem in my simulator,and the problem like this:
undefined is not an object (evaluating 'RCTActionSheetManager.showActionSheetWithOptions')'

Can anyone tell me how to fix it?or is it a bug?

Thank you very much!

**Comment by carl1990** [comment]
+1

use `react-native@0.13.0-rc`

**Comment by yerenyo** [comment]
+1
use react-native@0.16.0-rc

**Comment by DickyT** [comment]
+1
use react-native@0.16.0-rc

**Comment by DickyT** [comment]
i figured it out. I am using cocoapods integrating with native app, and i did not add 'RCTActionSheet' into podfile

**Comment by aflanagan** [comment]
This has been one of the biggest gotchas I've faced integrating into an existing iOS app. Would be awesome to have better error messaging around this!

**Comment by zyg-github** [comment]
+1
use react-native@0.19

**Comment by grabbou** [comment]
As noted - you have to either add the local `ActionSheet` podspec or drag & drop the `ActionSheetIOS.xcodeproj` to your Xcode (see https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking - instead of PushNotifications, just use ActionSheet file)

**Comment by alper** [comment]
I'm continuously running into issues like this. Could this be added to the documentation?

**Comment by grabbou** [comment]
@alper - sure, anything that would contribute to a better documentation is much appreciated! Happy to help you landing such change

**Comment by mkalygin** [comment]
I've got this error using `Share` module in React Native `v0.48.4`, iOS. The `RCTActionSheet.xcodeproj` is in the XCode, but the `libRCTActionSheet.a` wasn't added to Build Phases in XCode.

I feel like if it's by design, this setup step should be added to the documentation. Your thoughts?
