### ISSUE TITLE
[Android] RCTNetInfo "undefined is not an object"

### ISSUE THREAD

**Issue by madwed** [facebook/react-native#4047]
On app startup I call `NetInfo.isConnected.fetch().done(this._handleNetworkChange);`
which results in a red screen with 
`undefined is not an object (evaluating 'RCTNetInfo.getCurrentReachability')`.  

`NetInfo.isConnected.addEventListener(...)` is also called in the same function, with no problems.

**Comment by cosmith** [comment]
NetInfo hasn't been open sourced yet, see http://facebook.github.io/react-native/docs/known-issues.html#content

**Comment by madwed** [comment]
Ah, my mistake.  Looked over that page a few times, but didn't see that.

**Comment by lalith26** [comment]
Hi

Is NetInfo still not available on android?
But the docs suggest that it is available. I have upgraded react-native to v0.16.0.
But I still see the same message.
Can you please clarify?

Thanks
Lalith

**Comment by cosmith** [comment]
It should work on Android (https://github.com/facebook/react-native/blob/0.16-stable/Libraries/Network/NetInfo.js) did you add all the permissions to your Manifest?

**Comment by fender** [comment]
@cosmith @lalith26 I am also still seeing the error described in this issue although on version `v0.16.0`. Permissions are added to my manifest. `NetInfo` is returning `undefined` on Android.

**Comment by cosmith** [comment]
Looks like it was fixed in 0.17 https://github.com/facebook/react-native/commit/cf892a96d693af778679278549fc8fa354326f43

**Comment by jonolock91** [comment]
@cosmith I've just upgraded to 0.17.0 and I can now check on NetInfo if isConnected, but adding a listener for a change doesn't work it doesn't get called, any ideas?

**Comment by tuneZola** [comment]
+1, I am also getting the red screen of death. Is it not being open sourced mean that it will always be undefined or is it because I am running RN 15.0? Also is there a workaround of Android.
