### ISSUE TITLE
Passing `NSDate` to native modules results in crash

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#4049]
Anyone had similar issue? Looks like (regression / not-mentioned bc / something i've missed) to me (been working on 0.11 w/o issues)

I guess it's because one of the elements stored in the `NSDictionary` I pass down as `initialProps` to React is actually a Date (or __NSTaggedDate as represented by Apple private class).

Expected behaviour in my opinion is to convert it to String, just like JSON.stringify is doing. It's probably because of the fact that `NSJSONSerialization` does not handle `NSDate`.

Below is the stack trace:
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (__NSTaggedDate)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001134e6f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000112b02deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001134e6e7d +[NSException raise:format:] + 205
	3   Foundation                          0x00000001103ad99f _writeJSONValue + 698
	4   Foundation                          0x00000001103b15fa ___writeJSONObject_block_invoke + 226
	5   CoreFoundation                      0x000000011341f3d6 __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 102
	6   CoreFoundation                      0x000000011341f2ca -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 202
	7   Foundation                          0x00000001103b0d84 _writeJSONObject + 436
	8   Foundation                          0x00000001103ad871 _writeJSONValue + 396
	9   Foundation                          0x00000001103b17bd ___writeJSONArray_block_invoke + 132
	10  CoreFoundation                      0x0000000113415a42 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	11  CoreFoundation                      0x0000000113415132 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 194
	12  Foundation                          0x00000001103b0ff5 _writeJSONArray + 330
	13  Foundation                          0x00000001103ad90d _writeJSONValue + 552
	14  Foundation                          0x00000001103ad691 -[_NSJSONWriter dataWithRootObject:options:error:] + 124
	15  Foundation                          0x00000001103b00b2 +[NSJSONSerialization dataWithJSONObject:options:error:] + 333
	16  pfc-mobile                          0x000000010f0e19e2 RCTJSONStringify + 322
	17  pfc-mobile                          0x000000010f02ac32 -[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 994
	18  pfc-mobile                          0x000000010f02a0aa __33-[RCTBatchedBridge handleBuffer:]_block_invoke + 826
	19  libdispatch.dylib                   0x0000000114710e5d _dispatch_call_block_and_release + 12
	20  libdispatch.dylib                   0x000000011473149b _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x00000001147192af _dispatch_main_queue_callback_4CF + 1738
	22  CoreFoundation                      0x00000001134472e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	23  CoreFoundation                      0x00000001134088a9 __CFRunLoopRun + 2073
	24  CoreFoundation                      0x0000000113407e08 CFRunLoopRunSpecific + 488
	25  GraphicsServices                    0x00000001156cbad2 GSEventRunModal + 161
	26  UIKit                               0x000000011139130d UIApplicationMain + 171
	27  pfc-mobile                          0x000000010ef4efbf main + 111
	28  libdyld.dylib                       0x000000011476592d start + 1
	29  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Reproduction 1:
From native code:
```objc
NSDictionary *initialState = @{
  @"initialState": @{
      @"whatever": [NSDate date]
  }
};

RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"pfc-mobile" initialProperties:initialState launchOptions:launchOptions];
```

Reproduction 2:
From client code:
```js
Analytics.setIdentity(this.props.user.profile);
```
(User contains `dob` field that is a `new Date` - created by Javascript when response has been dispatched to stores)

Looks like the only way is to do it like here: https://github.com/facebook/react-native/blob/master/Libraries/Components/DatePicker/DatePickerIOS.ios.js#L124 In all places where Date is about to be sent.

**Comment by grabbou** [comment]
PS. Just clicked `run` again and it automagically started working :o:

**Comment by grabbou** [comment]
Here's the screenshot presenting object caught inside `RCTJSONStringify` that caused exception:
<img width="603" alt="screen shot 2015-11-10 at 18 35 35" src="https://cloud.githubusercontent.com/assets/2464966/11070097/fab2675c-87d9-11e5-886f-971a302fab27.png">

It's `user.profile.dob`.

**Comment by ide** [comment]
cc @nicklockwood @javache -- what do you guys think about having the opposite of RCTConvert -- a standard way to go from NSObjects to JS objects?

**Comment by nicklockwood** [comment]
Yeah, we've talked about it. It's not quite a symmetrical problem though, since this would be many -> few instead of few -> many.

We could add them to RCTConvert using a different naming convention, something like: `+(id)FooToJSON:(Foo *)foo`

Or a more intuitive implementation might be to have a standard method we can exposed on all native objects (using categories for built-in types) - something like `-(id)reactJSONValue`.

It would also be neat to have something similar on the JS side, so we could pass something like a Date directly over the bridge instead of having to manually convert to a string or number.

**Comment by nicklockwood** [comment]
Note also: the native bridge has no statically defined knowledge of the types that JS method and callbacks are expecting, so it wouldn't be possible to do this reverse-conversion automatically, like we do for JSON -> native. That makes it somewhat less valuable to have a standard mechanism (and we already have ad-hoc methods in RCTUtils for some of the common cases, like NSError).

**Comment by ide** [comment]
I like either of those solutions. Good point about conversion on the JS side -- for @grabbou's use case we'd want to go from NSDate --> NSNumber --(across the bridge)--> JS Number --> JS Date.

**Comment by grabbou** [comment]
Oh yeah. Plus it would've made your `datePicker` code easier by eliminating need to call `this.props.date.getTime()` call before passing to native component.

**Comment by ide** [comment]
@grabbou are you able to work around the issue for now? I imagine this isn't the highest priority task and might not get looked at right away but it's good to start a discussion around it.

**Comment by grabbou** [comment]
Yep, already fixed it by storing string in my Redux store and calling `new Date(this.user.dob)` when necessary (e.g. DatePickerIOS). I'd be interested in implementing new functionality as per @nicklockwood suggestions, but I imagine there's still a lot of things to be discussed before we start.

**Comment by nicklockwood** [comment]
@grabbou I don't understand how this is something that would have changed between RN releases. We've always serialized events sent from native to JS using NSJSONSerializer, and that's never supported NSDate AFAIK.

**Comment by grabbou** [comment]
Me neither, but had 0.11 app in production for 2 weeks and it had never crashed!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/passing-nsdate-to-native-modules-results-in-crash

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
