### ISSUE TITLE
After Update to 0.14.0 my apk build doesn´t show my Images i use...

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#4050]
Like the title says. After i updated my React Native module my App doesn´t show me any images i used for the App. This might be caused by the Image resources which i had to change after the update. Bevor Update we required images like this 

    source={require('image!someImage')}

after Update it is: 

     source={require('./Image/someImage.png)}

Does any one else experienced the same issue?

If i run the App in the Emulator everything works fine. As soon as i debug the App or install the signed apk on my Device, then no images are there...

**Comment by dbecker215** [comment]
+1

**Comment by yusufseyrek** [comment]
I have same issue on IOS. Images not showing when i set release schema on simulator.

When i get bundle, i set asset-dest property to my asset folder. It copied successfully after that i use that to use images;

source={{uri : 'slide_menu_logo.png'}}
As i said images showing on simulator with debug build configuration but not on release build conf.

**Comment by ms88privat** [comment]
:+1:  https://github.com/facebook/react-native/issues/4084
