### ISSUE TITLE
Several packages seem to be incompatible with the new `react-native` on platform Android with new-arch enabled

### ISSUE THREAD

**Issue by UNIDY2002** [facebook/react-native#40560]
### New Version

0.73.0-rc.1

### Old Version

0.72.5

### Build Target(s)

Android

### Output of `react-native info`

System:
  OS: Linux 6.1 Manjaro Linux
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 5.39 GB / 13.51 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.7.0
    path: /tmp/yarn--1696745056791-0.4798124459808675/node
  Yarn:
    version: 1.22.19
    path: /tmp/yarn--1696745056791-0.4798124459808675/yarn
  npm:
    version: 10.1.0
    path: /usr/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /usr/bin/watchman
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: javac 21
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0-rc.1
    wanted: 0.73.0-rc.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

**Steps to reproduce:**

- Create a fresh `react-native@0.73.0-rc.1` project
- Install `react-native-webview`
- Edit `android/gradle.properties` and set `newArchEnabled` to true
- Build application

Then, I can see the following error:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/unidy/repos/proj/node_modules/react-native-webview/android/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':react-native-webview'.
> Failed to apply plugin 'com.facebook.react'.
   > The value for property 'languageVersion' is final and cannot be changed any further.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-webview'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
==============================================================================
```

The same thing is happening to `@react-native-async-storage/async-storage` and some more packages.

Here is a real-world example that showcase this error:
- https://github.com/thu-info-community/thu-info-app/actions/runs/6445847567/job/17500319634

Thanks!

**Comment by iBotPeaches** [comment]
@UNIDY2002 - Packages often require changes to support newer React Native versions. I don't think this is a bug.

**Comment by UNIDY2002** [comment]
I get it. But since it is a common problem, I am hoping to get a solution or guideline for how to make adaptions to these packages. Thank you in advance!

**Comment by UNIDY2002** [comment]
After further investigation, I tend to think that adaptions need to be made to RNGP in order for third-party libraries to build. I have little knowledge about RN under the hood, so be free to correct me if I am wrong.

First, I came across [this doc](https://docs.gradle.org/current/userguide/upgrading_version_8.html#eager_evaluation_of_configuration_attributes) from Gradle. While it seems to be specified for Gradle 8.3, its explanations instructed me to investigate further.

Then, I began to doubt whether it is related to multiple-updating of the property `languageVersion`.

As a common practice of supporting the new-arch, `react-native-webview` [applies the plugin `com.facebook.react` when the new-arch is enabled](https://github.com/react-native-webview/react-native-webview/blob/master/android/build.gradle#L54). This may lead to RNGP being executed twice, which further results in setting the property `languageVersion` twice (just a hypothesis).

Then I simply commented out the following lines (of course, it will cause unexpected results):
- https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt#L38-L39
- https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt#L45
- https://github.com/facebook/react-native/blob/main/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt#L48

And the issue "The value for property 'languageVersion' is final and cannot be changed any further" disappeared. And after properly setting `kotlinOptions.jvmTarget` and `compileOptions.targetCompatibility`, the project began to build successfully.

I understand that those changes stated above are definitely incorrect. I am sharing my findings to draw attention into this issue, and hoping to get a proper solution for this problem.

Thank you!

**Comment by UNIDY2002** [comment]
You may have a look at this patch: https://github.com/UNIDY2002/repro-rn-73-android-new-arch/blob/main/ReproducerApp/patches/%40react-native%2Bgradle-plugin%2B0.73.1.patch

Compare:
- (Before patch) https://github.com/UNIDY2002/repro-rn-73-android-new-arch/actions/runs/6452787124/job/17515283126
- (After patch) https://github.com/UNIDY2002/repro-rn-73-android-new-arch/actions/runs/6452817486/job/17515365242

**Comment by cipolleschi** [comment]
Hi @UNIDY2002! Thank you so much for the thorough investigation. Would you mind opening a PR with the fix? So the commit, when we merge it, would properly associated to your user name. 😄 

@cortinico will look at it as soon as he can!

**Comment by cortinico** [comment]
Thanks for the PR @UNIDY2002
We're looking into this issue and we'll make sure it's fixed before 0.73 goes out

**Comment by cortinico** [comment]
Thanks for sending this over @UNIDY2002 and also thank you very much for the thorough investigation. You're right that the function `configureJavaToolChains` was invoked too many times and we're going to include your fix https://github.com/facebook/react-native/pull/40757 inside the upcoming RC3 for 0.73.

Thanks for doing it!

**Comment by fadi-quader-mox** [comment]
I'm encountering this error after i bumped to 0.73.8. my android has two modules  `app` and `instant-app`. Is there any way to fix this issue?
