### ISSUE TITLE
Unclear error encountered attempting to deploy app to local device.

### ISSUE THREAD

**Issue by jcdavison** [facebook/react-native#4056]
I have a smallish app working properly in the emulator.  Following the react docs on device deployment, option 2 for offline js package mgmt, getting an error i'm unclear on.

![screenshot 2015-11-10 12 58 58](https://cloud.githubusercontent.com/assets/6944945/11076708/10447f70-87b1-11e5-8ba6-69d446725540.png)

Working code base is https://github.com/jcdavison/bio-stream-native/tree/deploy-to-device

and SO post is http://stackoverflow.com/questions/33639542/what-error-is-prohibiting-my-react-native-build-for-on-device-app-execution

I appreciate this probably isn't a library bug but I generally get low activity on SO about react native questions and was hoping for some polite flash-light shining into a direction I should be thinking about going. 

Cheers,

JD

**Comment by browniefed** [comment]
@facebook-github-bot answered
