### ISSUE TITLE
[Animated] crashes when animated value is computed with other variables.

### ISSUE THREAD

**Issue by jthestupidkid** [facebook/react-native#4058]
I'm using a single Animated.Value to drive the opacity of 2 components, when I compute ( 1 - this.state.anim) it crashes the app with some ShadowQueue error on XCode.

How to repro would be like 
`
var Sample = React.createClass({
  getInitialState() {
    return {
      anim: new Animated.Value(0),
    };
  },
  render() {
    return (
      <View>
        <View
          style={{
          opacity: this.state.anim,
          }}
        />
        <View
          //errors on this
          style={{
          opacity: 1 - this.state.anim,
          }}
        />
      </View>
    );
  },
});
`

**Comment by browniefed** [comment]
I don't think things should crash however I will say this is not how animated works. 

`this.state.anim` is not an actual value it is an instance in which `Animated.View` can grab the current value and apply it, watch here. Also you need to use `Animated.View` to use animated values. Watch how this all works here (https://www.youtube.com/watch?v=xtqUJVqpKNo)

**Comment by ide** [comment]
I bet the native layer is crashing on a NaN opacity value. The app should throw up a redbox but probably should outright crash back to the home screen.

**Comment by jthestupidkid** [comment]
Thanks, @browniefed for pointing me in the right direction, I'm now using interpolate, but yes @ide, in the previous versions where I tried computing the other variables with Animated.Value it does not crash in XCode, funny that I only realized this mistake in 0.14.2.

**Comment by browniefed** [comment]
This looks like it can be closed?
