### ISSUE TITLE
signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by fengruyi** [facebook/react-native#40600]
### Description

 Process name is com.oppo.store, not key_processkeyProcess: 0*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***Build fingerprint: 'OPPO/PFEM10/OP5209L1:14/UP1A.230620.001/S.1369ae5_9998-a35:user/release-keys'Revision: '0'ABI: 'arm64'Timestamp: 2023-10-01 12:21:44.726671702+0800Process uptime: 8154sCmdline: com.oppo.storepid: 27008, tid: 8561, name: mqt_native_modu  >>> com.oppo.store <<<uid: 10530tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)pac_enabled_keys: 000000000000000f (PR_PAC_APIAKEY, PR_PAC_APIBKEY, PR_PAC_APDAKEY, PR_PAC_APDBKEY)signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000Cause: null pointer dereference    x0  00000000709413c8  x1  0000000070b290b8  x2  0000000070b25e60  x3  00000000709735a8    x4  00000000708138d8  x5  00000000ffffffff  x6  0000000014398f60  x7  0000000000000010    x8  0000000013787b6c  x9  00000000000000d7  x10 0000000000000000  x11 0000000000000000    x12 00000077119a0030  x13 000000007fffffff  x14 000000000572e1aa  x15 000006978bdcc0cf    x16 0032d6722ac79aa8  x17 0000000034155555  x18 00000074aaed0000  x19 b4000074d7660400    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 00000000ffffffff    x24 0000000000000001  x25 000000007fffffff  x26 0000000071157020  x27 0000000013787b68    x28 b40000759d189f80  x29 0000000070397a08    lr  00000000723aaccc  sp  00000074abdd5820  pc  000000765e756ec0  pst 000000004000100011 total framesbacktrace:     
#00 pc 0000000000226ec0  /apex/com.android.art/lib64/libart.so (art_quick_implicit_suspend+0) (BuildId: e38a016f1c1a4da7b105e036f9e9f2fe)     
#01 pc 0000000000605cc8  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+712) (BuildId: 93938bc8eea0a766ddde0c7da772cb0755341429)     
#02 pc 00000000006022d0  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+96) (BuildId: 93938bc8eea0a766ddde0c7da772cb0755341429)     
#03 pc 00000000006021e0  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+640) (BuildId: 93938bc8eea0a766ddde0c7da772cb0755341429)     
#04 pc 000000000074f32c  /data/app/~~4OrTdT_Guk6kNQHO72M_jQ==/com.oppo.store-dwjn5fe3i-pN8b95tUc_1w==/oat/arm64/base.odex (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+460)     
#05 pc 000000000017f6b8  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 7bbf84ba2f7d8b5bae6da27ae26dc6b72b87f77c)     
#06 pc 00000000002109a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: e38a016f1c1a4da7b105e036f9e9f2fe)     
#07 pc 0000000000254720  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+176) (BuildId: e38a016f1c1a4da7b105e036f9e9f2fe)     
#08 pc 0000000000683ae4  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1412) (BuildId: e38a016f1c1a4da7b105e036f9e9f2fe)     
#09 pc 0000000000104fc4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: d1a98b526f2f94260a53c3055979a4f6)     
#10 pc 000000000009e764  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: d1a98b526f2f94260a53c3055979a4f6)
              

### React Native Version

0.68

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 558.06 MB / 15.78 GB
  Binaries:
    Node: 16.15.1 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - D:\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10 - D:\as\jre\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

na

### Snack, screenshot, or link to a repository

na

**Comment by cortinico** [comment]
Version of RN is out of support, plus we can't help with just a stacktrace sorry
