### ISSUE TITLE
zsh: command not found: react-native

### ISSUE THREAD

**Issue by coding102** [facebook/react-native#4064]
So after following the instructions to prepare the environment for Native I now followed these instructions;

$ npm install -g react-native-cli
$ react-native init AwesomeProject 

and this is what my terminal is showing;

zsh: command not found: react-native

**Comment by coding102** [comment]
Apparently I had somehow downloaded another version into the most recent version's folder

**Comment by christopherdro** [comment]
@coding102 Does it work now?

**Comment by coding102** [comment]
yes thanks

**Comment by christopherdro** [comment]
@coding102 Great! Could you please close the issue? Thanks!

**Comment by joshbang** [comment]
I hate to comment on such an old post... But I have the same problem and have been working on it for about 2 and a half hours now.  Nothing online has been helpful. I've been just following along with the React Native tutorial and when I got to "react-native init AwesomeProject" I get "-bash: react-native: command not found" Just like coding102 did.

**Comment by LohitakshTrehan** [comment]
i am facing same problem as @joshbang but i think, no one will reply the solution :(
