### ISSUE TITLE
many node modules

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#4069]
Since the upgrade to RN 0.14.1 I have a ton of node modules in my project. Is this normal?

**Comment by MossP** [comment]
I think they changed the nested folders to be flat for compatibility reasons.

**Comment by jaygarcia** [comment]
(I thought I posted on this already. Was the message deleted?)
If this isn't an issue, this post should be closed.

**Comment by MossP** [comment]
I'd not seen any post of yours @jaygarcia. But I agree, this should be closed.

**Comment by jaygarcia** [comment]
Thanks @MossP. It could be a casualty of multitasking ;)

**Comment by FaridSafi** [comment]
I just tested, I don't have many modules using nodejs v4.2.2

**Comment by MossP** [comment]
Did you upgrade or create a fresh project? React-native init AwesomeProject seems to flatten the paths for me.

**Comment by MossP** [comment]
Maybe it's a node version thing? I'm on 5.0.0

**Comment by FaridSafi** [comment]
react-native init yes
If you use nvm you can do
nvm install v4.2.2
nvm use v4.2.2
nvm alias default 4.2.2

**Comment by eyaleizenberg** [comment]
I'm also on node 5. I was upgrading an existing project.

**Comment by ide** [comment]
Try using npm 2 instead of 3 and see if that changes things.

**Comment by ide** [comment]
I get many packages under node_modules with npm3. It's just how npm behaves now.
