### ISSUE TITLE
Error when trying to invoke devtools on Chrome Canary

### ISSUE THREAD

**Issue by asavin** [facebook/react-native#407]
![ios_simulator_-_iphone_6_-_iphone_6___ios_8_2__12d508_](https://cloud.githubusercontent.com/assets/487468/6882026/a7a39b7a-d56f-11e4-983f-48fdd9bc5a37.png)

If you don't have Chrome stable running, and have Chrome Canary instead, pressing Cmd-D in iOS simulator will give you this error (and not invoke devtools). Works fine with Chrome stable.

**Comment by schokocappucino** [comment]
You have to change "Google Chrome" to "Google Chrome Canary" in `./node_modules/react-native/packager/launchChromeDevTools.applescript`

**Comment by vjeux** [comment]
Great catch @schokocappucino, would you mind updating the applescript to try both?

**Comment by schokocappucino** [comment]
I tried, but I'm not very familiar with applescript

**Comment by oaleynik** [comment]
@vjeux Chrome Canary works for me like a charm

**Comment by brentvatne** [comment]
@asavin - Is this still an issue for you? Seems to work for @oaleynik now

**Comment by oaleynik** [comment]
@brentvatne I'm able to reproduce this issue when Live Reload is enabled. Here is some steps to reproduce:

1. Build and run app in emulator
2. Enable live reload
3. Enable debugging with Chrome (doesn't matter will it be latest stable release or Chrome Canary)
4. Change something in the source code and save

**Comment by jsierles** [comment]
@oaleynik @asavin This is working for me on Chrome and Chrome Canary, with RN 0.4.4.
