### ISSUE TITLE
How use Subscribable.Mixin in a class

### ISSUE THREAD

**Issue by moale** [facebook/react-native#4070]
i trying to use Subscribable.Mixin in a class, i inject the mixin through 

```javascript
Object.assign(MyClass.prototype, Subscribable.Mixin);
```
in this way the mixin override componentWillMount and componentWillUnMount methods and my code is not performed any more.

Anyone can help?
thank you

**Comment by mohanrohith** [comment]
@moale Did you find the solution for this issue?
