### ISSUE TITLE
run-android fails without a message

### ISSUE THREAD

**Issue by zane-commeatio** [facebook/react-native#40719]
### Description

After upgrading to 0.72.5 I can't run the android app on dev mode 

![image](https://github.com/facebook/react-native/assets/36542885/6c6156c2-433d-4fa5-be90-f832c67e1a48)

`./gradlew installDevDebug` is working, app installed on device but not connected to the dev server

`run-ios` is working, opening the app on the simulator, connecting to the dev server, everything fine

I've spent 9hours on this already so I tried so much things that I can't even remember and my brain is just dead at this point

Tried to install almost all openjdk version that every existed but got back to 11 after no success

I don't even know what to say I followed the steps in the docs (Setup environment) 2 times

I tried all the "fixes" found in stackoverflow

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 80.83 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: ~/.nvm/versions/node/v20.5.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.5.1/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v20.5.1/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/zane/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "33"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/zane/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

I can't provide a reproducible obviously because I've been working on this project for 6 months already so the all the files have been modified for the various modules that I added

and it's for a customer so I can't share the repo

Anyway I guess it's not code related but it have to do with my laptop config

also, the 'react-native doctor' command complained about the android SDK missing, but this is now resolved
![image](https://github.com/facebook/react-native/assets/36542885/c7de0a17-e89f-4d7c-ae65-ffc53e68ffb3)
(I don't know exactly what fixed this, I installed a lot of SDK versions, changed env variables like JAVA_HOME a lot of times, at some point it worked but the `run-android` still fail silently)

### Snack, screenshot, or link to a repository

The reproducer is "buy an macbook pro M1 and go back in time to do every action I every did on it" lol

**Comment by zane-commeatio** [comment]
For more information

![image](https://github.com/facebook/react-native/assets/36542885/ce689540-3a5f-4923-8490-2551f5aca4ae)

![image](https://github.com/facebook/react-native/assets/36542885/5185f287-915a-4051-8116-1f4d185ea85a)

![image](https://github.com/facebook/react-native/assets/36542885/636e26f4-0395-4f66-89e4-4eaea0fd5277)

![image](https://github.com/facebook/react-native/assets/36542885/9da014d6-50c7-45cf-ac0d-9233ba74a5df)

![image](https://github.com/facebook/react-native/assets/36542885/a3d26a5f-5e46-4904-b8e5-4ff6d34d55ad)

![image](https://github.com/facebook/react-native/assets/36542885/c230ce1f-1732-457f-b995-5479c4d3f5f5)


If you want more infos feel free to ask

**Comment by frankcalise** [comment]
Are you sure your are using JDK v11? Your `npx react-native info` output says otherwise.

**Comment by cortinico** [comment]
Please dont' post console screenshots. They make for terrible searchability for out users.

Also this is an issue related to the CLI so should be opened here:
https://github.com/react-native-community/cli/issues
