### ISSUE TITLE
react-native build failing because on FirebaseMessaging

### ISSUE THREAD

**Issue by mohreRohan1** [facebook/react-native#40725]
### Description

The following build commands failed:
	CompileC /Users/admin/Library/Developer/Xcode/DerivedData/MohreAuthApplication-ekbnaiphyuiqpocekfqmkujfosdb/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseMessaging.build/Objects-normal/x86_64/FIRMessagingTokenFetchOperation.o /Users/admin/Downloads/MohreAuthenticator/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseMessaging' from project 'Pods')
(1 failure)

### React Native Version

0.72.4

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 13.6
  CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Memory: 153.36 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.8.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/admin/.rvm/gems/ruby-3.2.1/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

npx react-native run-ios

### Snack, screenshot, or link to a repository

<img width="1667" alt="Screenshot 2023-10-09 at 11 55 15 AM" src="https://github.com/facebook/react-native/assets/146716520/d4df8a3f-f7d1-4b9e-9b34-fa18262a9e3b">

**Comment by frankcalise** [comment]
@mohreRohan1 could you help provide the steps of how you got here? Did you install react-native-firebase and install pods?

**Comment by mohreRohan1** [comment]
> @mohreRohan1 could you help provide the steps of how you got here? Did you install react-native-firebase and install pods?


@frankcalise 
I ran 'npx react-native run-ios' in the react-native project's root directory.\

---------------------------------------------------------------
package.json has below entries for react-native and firebase;
"react-native": "0.72.4",
"@react-native-firebase/app": "^18.5.0",
"@react-native-firebase/messaging": "^18.5.0",
------------------------------------------------------------
POD version: 1.12.1
-------------------------------------
PODfile has below pod entries:

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Firebase/Messaging', :modular_headers => true
  pod 'Firebase/Core', :modular_headers => true

**Comment by mohreRohan1** [comment]
@frankcalise  can you please check , let me know if you need more details

**Comment by frankcalise** [comment]
@mohreRohan1 I was able to install the firebase packages you listed and pod install without any issue. My steps to reproduce were:

1. npx react-native init MyFirebaseApp
2. cd MyFirebaseApp
3. yarn add @react-native-firebase/app @react-native-firebase/messaging
4. npx pod-install

At this point the pod install failed
```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
Couldn't install Pods. Updating the Pods project and trying again...
```

Reading the [documentation](https://rnfirebase.io/#altering-cocoapods-to-use-frameworks), I followed the proper steps to edit the Podfile accordingly, adding `  use_frameworks! :linkage => :static` after the `config = use_native_modules!` line. I also disabled flipper like it mentions.

Then I ran  `npx pod-install` again and it completed successfully. I'm on node version 18.11.0, not sure if that matters.

Please give the above steps a try and see what you run into

**Comment by cipolleschi** [comment]
Thanks @frankcalise for helping out here!
