### ISSUE TITLE
dont show message "refreshing"

### ISSUE THREAD

**Issue by Ghabriel-elias** [facebook/react-native#40735]
### Description

when update react native 70 to 72, the message "refreshing" dont sho anymore when i run the command ctrl + s

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 95.42 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.14.0/bin/yarn
  npm:
    version: 8.3.1
    path: ~/.nvm/versions/node/v16.14.0/bin/npm
  Watchman:
    version: 2023.05.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Just initi app with 0.72.4 and run the command ctrl + s

### Snack, screenshot, or link to a repository

https://github.com/Ghabriel-elias/contexto

**Comment by cortinico** [comment]
Thanks for reporting. This was fixed by https://github.com/facebook/react-native/commit/5dedf277cb903528659f0d8a71412274d9d32a65

It will be backported to patches on 0.71 and 0.72
