### ISSUE TITLE
run react-native run-android error

### ISSUE THREAD

**Issue by stoneCrystal** [facebook/react-native#4074]
:app:packageDebug UP-TO-DATE
:app:zipalignDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

**Comment by stoneCrystal** [comment]
on mac pro

**Comment by kevyu** [comment]
I think you should start the android emulator before run ```react-native run-android```.

**Comment by stoneCrystal** [comment]
you mean  i should create a device on avd?

**Comment by kevyu** [comment]
@stoneCrystal yes, or connect your android device to you mac.

**Comment by offbye** [comment]
make sure you can `adb devices ` see you device connected

**Comment by xstable** [comment]
How does this work exactly?
Must i first start the emulator:
```
./emulator @AVD_for_Nexus_5_by_Google
```
 and then do 
```react-native run android```?

Only if I do start the emulator first, I see devices in adb devices.

But if I then run it with ```react-native run android```, I got:

> Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to establish session

**Comment by xstable** [comment]
Ok, it seems the failure was the name... How ever, _react-native run android_ tried to start 
> emulator-5554 - 6.0
After I've recreated and renamed the AVD to "reactNative" it starts without problems.
