### ISSUE TITLE
[Packager] Root require ?

### ISSUE THREAD

**Issue by trongnd** [facebook/react-native#4075]
Hi,
I'm looking for the way to do **"root require"** in `react-native`

For example, I have 2 files with the location like this:
```
root-folder/app/common/util.js
root-folder/app/components/sub-folder/some-component.js
```

In `some-component.js`, If i want to require `util.js`, currently I'm doing like this: `require('../../util.js')`

I want to avoid the relative path `../../util.js` by using something like `~/common/util.js`. The `~/` means the path starts from some **root folder** *that I can custom via some configuration*, in this example is `root-folder/app`. (*`~/` can be replaced by something else, such as `@/`, for example*)

Currently to do this, I modified the **packager** by adding some code to the `_resolveNodeDependency` function in the file `node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js`, like this:

```javascript
_resolveNodeDependency(fromModule, toModuleName) {
    // add the code to resolve the module starts with "~/"
    if (toModuleName.startsWith('~/')) {
      var realModuleName = toModuleName.slice(2);
      // hardcode the "root folder" path here
      realModuleName = process.cwd() + '/app/' + realModuleName;
      realModuleName = require.resolve(realModuleName);

      return this._loadAsFile(realModuleName)
        .catch(() => this._loadAsDir(realModuleName));
    }
   .....
```

It seems working, but is there any better way to do this kind of require in `react-native`.

Thanks.

**Comment by doublefree** [comment]
+1

**Comment by satya164** [comment]
cc @martinbigio

**Comment by martinbigio** [comment]
This looks very useful because it turns the namespace into one more flat. In other words, the benefits you get are similars to the ones you'd get usin Haste modules, so I think we shouldn't support this.

cc @davidaurelio

**Comment by davidaurelio** [comment]
need to let this sink in a bit

**Comment by grabbou** [comment]
You can require by package name (if your root folder has name, just write require('@rootfoldername/path/to/file')). 

Check my medium article that shows the possible use cases: https://medium.com/@grabbou/a-cure-for-relative-requires-in-react-native-2b263cecf0f6

**Comment by JohnyDays** [comment]
This is supported in webpack, and AFAIK used widely. I use it in all my projects and it greatly simplifies refactoring by not relying on relative folder structure.

**Comment by benhughes** [comment]
So this issue has now been closed: https://github.com/facebook/react-native/issues/4185#event-582090584. Once it's released you should be able to write a babel plugin to achieve this, but the article posted by @grabbou works quite well and we adopted this practise in our codebase instead.

**Comment by ide** [comment]
^ Something like https://github.com/tleunen/babel-plugin-module-alias

**Comment by jsierles** [comment]
@facebook-github-bot answered

**Comment by pewh** [comment]
Hi @ide, I think [https://github.com/tleunen/babel-plugin-module-alias](https://github.com/tleunen/babel-plugin-module-alias) didn't work on React 15. And RN 0.27 force me to use React 15.

Related issues:
https://github.com/facebook/react-native/issues/6118#issuecomment-215885029
https://github.com/tleunen/babel-plugin-module-alias/issues/29#issuecomment-228702158
