### ISSUE TITLE
Chrome Debugger when Running on Device

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4076]
Is there any way to use the Chrome Debugger when running on device (I am in dev mode and am ["Accessing development server from device"](https://facebook.github.io/react-native/docs/running-on-device-ios.html#accessing-development-server-from-device))?

From [this line](https://github.com/facebook/react-native/blob/cce9ba864f00a6b8aa52306f75d87374209dd6ef/Libraries/WebSocket/RCTWebSocketExecutor.m#L44) it looks like the host is hard coded as `localhost`.

**Comment by ide** [comment]
Debugging on device is not supported out of the box.

**Comment by AlicanC** [comment]
Hard coded localhosts aren't just a debugging on device issue. I develop our iOS app on a Windows machine so the packager runs there and I have to patch `AppDelegate.m` and `RCTWebSocketExecutor.m` to make things work.

Being able to specify packager host in react-native-cli commands would be a nice addition:
```
react-native run-ios --packager-host 192.168.1.123:8081
```

**Comment by jsierles** [comment]
@cancan101 Thanks for bringing this up!

This still isn't supported, but there's a [Product Pains entry](https://productpains.com/post/react-native/allow-packager-port-to-be-configurable-change-from-8081) you can upvote to get more attention around the issue of configurable hosts and ports for React Native development tools.

Closing out this issue in favor of the PP discussion, or a PR!
