### ISSUE TITLE
Excessive Lag/Response Time on React Native App when Heavy UI Updates

### ISSUE THREAD

**Issue by Yasas4D** [facebook/react-native#40769]
### Description

I am encountering a significant delay in response time in my React Native application. This issue becomes particularly pronounced when there are **heavy updates in the UI component**, such as frequent component updates.

In my application, I have a list of cards to be rendered. These cards are based on a card model, and I'm using the **Hookstate** library to manage the state. The data for each card is continuously updated at a rapid rate (every 100 milliseconds- using setInterval), simulating a scenario similar to a separate **socket service** in my real application.

Each card component receives this data, and Hookstate handles the re-rendering of the components upon data updates. This mechanism allows the UI to reflect real-time changes in the Card data.

There is a button at the top of the card list,  that allows navigation to the next page. When this button is clicked, it **does not respond to the event for approximately 15 to 20 seconds**. 

I have recorded a video demonstration of this issue for better understanding, which can be viewed in here.
https://drive.google.com/file/d/1jC0oajkOS349IyuX-mFU44fxlRGNZ32L/view?usp=sharing
![image](https://github.com/facebook/react-native/assets/49401137/c26f637c-1b5f-4b17-946f-c328aa1717f8)

### React Native Version

0.72.5

### Output of `npx react-native info`

```
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Memory: 2.19 GB / 15.69 GB
Binaries:
  Node:
    version: 18.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-30 | Google Play Intel x86 Atom
      - android-33 | Google APIs Intel x86 Atom_64
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-213.7172.25.2113.9123335
  Visual Studio: Not Found
Languages:
  Java: 11.0.16.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

- Clone the Repository and Launch the Application
- Observe the initial rendering of the cards
- Click the "Toggle Data Update" button on the screen
- Note the delay in responding to the click event (approximately 15-20 seconds)

I would like to note that while I am using a `setInterval` function to update the Card data, there is a concern about a potential memory leak as the `setInterval` is not being cleared using `clearInterval()` However, in this case, I don't need to clear it upon component unmounting, as the `setInterval` is used outside of the React component to simulate data updates.

Additionally, I have tested this application with the new React Native architecture enabled, and it responded instantly under that configuration.
https://drive.google.com/file/d/1ysFbaKmqbjOOXGUxtGmiMlhR_C0BzbfS/view?usp=drive_link

### Snack, screenshot, or link to a repository

https://github.com/Yasas4D/TestRenderingIssue

**Comment by frankcalise** [comment]
Hi @Yasas4D 

You should note that there are performance implications to rendering long lists of components just inside a `ScrollView`. You can optimize this rendering by either using a `FlatList` or [Shopify's FlashList](https://github.com/Shopify/flash-list) if your components are really heavy.

ScrollView will attempt to render everything you throw at it, even if it is not inside the viewport at the moment. So if your components are heavy with many views and/or state changes, you may experience performance drops like this because the app is busy rendering, so your button press is getting delayed.

There is documentation with tips on [Optimizing Flatlist Configuration](https://reactnative.dev/docs/optimizing-flatlist-configuration).

**Comment by Yasas4D** [comment]
Hi @frankcalise 

Thank you for your prompt response and the valuable insights you shared. I appreciate your suggestion regarding using a FlatList or Shopify's FlashList.

I have already used [VirtualizedList ](https://reactnative.dev/docs/virtualizedlist) as it provides more flexibility than the FlatList can offer. However, the issue still persists. 

I'll continue investigating and appreciate any further guidance you or the community can provide.

![image](https://github.com/facebook/react-native/assets/49401137/6a6fa61f-670f-4708-9484-290baae0ea8c)

**Comment by frankcalise** [comment]
@Yasas4D can you try just rendering one `Card` component in your `CardList` and see if the button press is more responsive?

**Comment by Yasas4D** [comment]
yah @frankcalise It's more responsive when we have a few cards. Decreased with the increment of cards.

**Comment by frankcalise** [comment]
Makes sense. Then I would definitely check out Shopify's FlashList!

**Comment by cortinico** [comment]
Is this a regression from 0.71?

**Comment by frankcalise** [comment]
@cortinico seems like it could fall under #36296 but at the same time this feels like a relatively new spun up application.

**Comment by Obhenimen** [comment]
I can see the new architecture works very well. Why aren't you sticking with the new architecture

**Comment by Kaizodo** [comment]
i have significant delays on state updates i am on latest react native  version here is simple counter code to check the delays 

```typescript
import { View, Text, Button } from 'react-native'
import React, { useEffect, useRef, useState } from 'react'

export default function Test3Screen() {
    const [count, setCount] = useState(0);
    const startTime = useRef<any>(null);

    const increment = () => {
        startTime.current = performance.now(); // Record start time
        setCount((prevCount) => prevCount + 1);
    };

    useEffect(() => {
        if (startTime.current !== null) {
            const endTime = performance.now();
            console.log(`Re-render took ${endTime - startTime.current} ms`);
            startTime.current = null; // Reset the timer
        }
    }, [count]); // Run this effect whenever `count` changes

    return (
        <View>
            <Text>Count: {count}</Text>
            <Button title="Increment" onPress={increment} />
        </View>
    );
}

```


it outputs following delays when i rapidly hit the button when i start hitting the button too frequently i see reduced delays but when i hit first it goes 80ms delays 

```console
 (NOBRIDGE) LOG  Re-render took 80.24374997615814 ms
 (NOBRIDGE) LOG  Re-render took 88.2104170024395 ms
 (NOBRIDGE) LOG  Re-render took 83.52604097127914 ms
 (NOBRIDGE) LOG  Re-render took 26.175519973039627 ms
 (NOBRIDGE) LOG  Re-render took 65.73176997900009 ms
 (NOBRIDGE) LOG  Re-render took 48.13020798563957 ms
 (NOBRIDGE) LOG  Re-render took 56.59895798563957 ms
 (NOBRIDGE) LOG  Re-render took 53.877083986997604 ms
 (NOBRIDGE) LOG  Re-render took 49.64114499092102 ms
 (NOBRIDGE) LOG  Re-render took 76.77187499403954 ms
 (NOBRIDGE) LOG  Re-render took 80.74375000596046 ms
 (NOBRIDGE) LOG  Re-render took 32.85260498523712 ms
 (NOBRIDGE) LOG  Re-render took 83.88020798563957 ms
 (NOBRIDGE) LOG  Re-render took 28.76197901368141 ms
 (NOBRIDGE) LOG  Re-render took 57.24270898103714 ms
 (NOBRIDGE) LOG  Re-render took 58.033853977918625 ms
 (NOBRIDGE) LOG  Re-render took 65.97708398103714 ms
 (NOBRIDGE) LOG  Re-render took 60.15364599227905 ms
 (NOBRIDGE) LOG  Re-render took 36.572396010160446 ms
 (NOBRIDGE) LOG  Re-render took 27.677604019641876 ms
 (NOBRIDGE) LOG  Re-render took 72.62343800067902 ms
 (NOBRIDGE) LOG  Re-render took 51.771874994039536 ms
 (NOBRIDGE) LOG  Re-render took 53.77812501788139 ms
 (NOBRIDGE) LOG  Re-render took 56.99322900176048 ms
 (NOBRIDGE) LOG  Re-render took 37.80364599823952 ms
 (NOBRIDGE) LOG  Re-render took 50.42604199051857 ms
 (NOBRIDGE) LOG  Re-render took 50.978645980358124 ms
 (NOBRIDGE) LOG  Re-render took 48.03541699051857 ms
 (NOBRIDGE) LOG  Re-render took 53.28437498211861 ms
 (NOBRIDGE) LOG  Re-render took 52.32083401083946 ms
 (NOBRIDGE) LOG  Re-render took 50.298436999320984 ms
````
