### ISSUE TITLE
Unsure of how to reload in android emulator

### ISSUE THREAD

**Issue by hendrikswan** [facebook/react-native#4077]
I'm probably just being stupid, but I can't figure out how to reload my JS bundle from the android emulator.  I was following along with this: https://facebook.github.io/react-native/docs/android-setup.html. 

I managed to get it reloading using the genymotion virtual machine, but it was way too slow for me, and after I fiddled around with performance settings in Virtualbox, it crashed and wouldn't start up anymore. 

So I'm trying to get my JS bundle reloaded in the stock google emulator, but with no luck so far. 

Can anyone point me in the right direction?

**Comment by hendrikswan** [comment]
Nevermind, found the solution on SO: http://stackoverflow.com/a/32614200/431522

**Comment by jose920405** [comment]
R+R works for android emulators.

**Comment by fabiorbap** [comment]
@jose920405 Not working for me on emulator :/ I have to press CMD+M (I'm on a Mac) to show the developer menu and reload it.

**Comment by zhumanasyrov** [comment]
Need to press Fn+CMD+M. the will open developer mode on android emulator.
