### ISSUE TITLE
[Android] Android equivalent of Obj-C’s bridge.addUIBlock?

### ISSUE THREAD

**Issue by erickreutz** [facebook/react-native#4078]
Can anyone tell me the Android equivalent of this Obj-c pattern for looking up view from a native module given a views tag?

I've tried IRC, StackOverflow, discuss.reactjs.org and have got nothing. I realize this isn't the place for generic dev questions but it's a last resort.

Help would be much appreciated!

https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/RCTMapboxGL/RCTMapboxGLManager.m#L60

**Comment by brentvatne** [comment]
It's a little bit different -- check out the implementations of setPage and setPageWithoutAnimation in https://github.com/facebook/react-native/pull/3621/files :)

**Comment by erickreutz** [comment]
Thanks so much!
