### ISSUE TITLE
Unable to create new RN 0.72 project with Node 16 again

### ISSUE THREAD

**Issue by jonthysell** [facebook/react-native#40797]
### Description

`@react-native/normalize-colors@0.74.0` was just published, breaking 0.72.5 with Node 16 again. Same problem as #39692.

### React Native Version

0.72.5

### Output of `npx react-native info`

Can't create a project, so can't run info.

### Steps to reproduce

`npx --yes react-native@0.72.5 init testcli72 --template react-native@0.72.5`

See #39692.

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/10852185/24bc6685-cef5-44d0-a6ac-2d94e989300f)

**Comment by robhogan** [comment]
Thanks for reporting - we're about to publish an update to `normalize-colors` removing the Node 18 restriction, and tighten the transitive dependency via `react-native-deprecated-prop-types`.

## Workaround
As a mitigation, you can init the project using Node 18, add a `resolutions` field to your `package.json`, and then drop back to Node 16.

```sh
nvm use 18
npx --yes react-native@0.72.5 init testcli72 --template react-native@0.72.5 --skip-install
cd testcli72
```

Add to your new `package.json` as a top-level field (docs: [`resolutions`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)):
```json
"resolutions": {
  "@react-native/normalize-colors": "^0.72.0"
},
```

```sh
nvm use 16
yarn install
yarn start
```
