### ISSUE TITLE
Creating a native view component in Swift and accessing view properties

### ISSUE THREAD

**Issue by chris-erickson** [facebook/react-native#4080]
I am able to create the view, and export all the functions as needed, but I'm stuck on how to export the view properties.  The [suggested process](https://facebook.github.io/react-native/docs/native-components-ios.html#properties) is to use the `RCT_EXPORT_VIEW_PROPERTY `macro in the view `Manager`.  This appears to be operating on the view that the manager returns in the `view` method.  Since this macro can't be used in a Swift defined manager, ie:
```swift
@objc override func view() -> UIView! {
    return MyFancySwiftView()
}
```
how are we to export view properties?  The worst idea I had so far was to add setter/getter methods to the view, and expose those as functions.  This seems really awkward, and then they aren't exposed as props.  I imagine you could write a shim layer in JS that allows them to be used like props at a higher level, then set after the component is instantiated in JS.  Maybe I can just define the output manually that the macro is trying to build?

Am I missing something?

**Comment by idibidiart** [comment]
I've only done it with Objective-C so far, and I'm curious about the way to do it in Swift.

I don't yet know enough about Objective-C/Swift integration, but could you have used Objective-C for the view manager with the view itself being defined in Swift?

**Comment by chris-erickson** [comment]
I considered that, but then I found myself needing to write the view manager logic in Obj-C.  Maybe not usually an issue, but in my case, the manager is a delegate for a MapView, so the bulk of the work is actually there.  Your idea still is compelling though - perhaps that Delegate logic goes in a third file.  Which is fine, but wow the contortions I'm going through to avoid just doing it in Obj-C!

**Comment by brentvatne** [comment]
Not a bug, please ask these kinds of questions on StackOverflow -- we don't have the bandwidth to deal with these in the issues :)
