### ISSUE TITLE
Image doesn't show after bundling into the apk

### ISSUE THREAD

**Issue by rockerhieu** [facebook/react-native#4084]
Here is the project structure:
```
android-project
+---app
|   \---src
|       \---main
|           \---assets
|           \---java
|           \---res
+---reactnative
|   \---assets
|       \---image@1x.png
|       \---image@2x.png
|       \---image@3x.png
----index.android.js
```

Here's the code to show the image:
```
<Image
    source={require('./reactnative/assets/image.png')}
    resizeMode='contain'
    style={styles.image} />
```

The above code works fine when running together with localhost `react-native start`. But it doesn't work after bundling react native resources into the apk:
```
react-native bundle --platform android -dev false --entry-file index.android.js \
--bundle-output app/src/main/assets/index.android.bundle \
--assets-dest app/src/main/res/
```

Here's the output:
```
android-project
+---app
|   \---src
|       \---main
|           \---assets
|               \---index.android.bundle
|           \---java
|           \---res
|               \---drawable-xxxhdpi
|                   \---reactnative_assets_image1.png
|               \---drawable-xxhdpi
|                   \---reactnative_assets_image1.png
|               \---drawable-xhdpi
|                   \---reactnative_assets_image1.png
|               \---drawable-mdpi
|                   \---reactnative_assets_image1.png
```

Is it the right way to generate the apk with react native? Please troubleshoot. Thanks!

**Comment by ms88privat** [comment]
:+1: got the same problem with iOS too.

**Comment by hoangviet** [comment]
@ms88privat for ios, you can do this way:
1. `react-native bundle --assets-dest ./ --entry-file ./ReactComponent/main.ios.js --bundle-output ./Dist/main.jsbundle --platform ios`. Change the the name of bundle output and assets-dest as you wish.
2. Put Dist and assets folder as folder references in your project.
<img width="287" alt="screenshot_2015-11-13_10_57_23" src="https://cloud.githubusercontent.com/assets/1713660/11138531/0c2a8546-89f6-11e5-8982-8bc3bdb9b7c4.png">

After debug around the `RCTImageView.m`, I recognize that they load our assets as the same way with external assets, So we just make sure the path is correct, and It works !

**Comment by rockerhieu** [comment]
It seems that Fresco can't load `res:/` or `res://` URIs: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java#L266. Related issue: https://github.com/facebook/fresco/issues/759.

**Comment by grabbou** [comment]
It's still quite weird, e.g. real path in project is `require('../../assets/images/foto.png')` and as a result, after bundling app, I end up with `assets/assets/images/foto.png`.

**Comment by rockerhieu** [comment]
It's interesting that there is no one else ever asked this question. Am I the only one getting this issue with 0.14.2 on Android?

**Comment by rockerhieu** [comment]
I have tried the latest example on `master`. Same issue.

**Comment by grabbou** [comment]
I am not sure if that solution is correct @hoangviet. From my experience, you should not add any assets nor main.jsbundle to your app. The only thing you need is to attach `react-native-xcode.sh` script as a next build phase and that will bundle all the things automagically for you, both for release and for demo purposes.

@ide side note - I love that feature a lot! That script actually made the CI lots easier, esp. as a part of another process.

**Comment by PCharpentier** [comment]
@hoangviet Do you have a same solution for Android ?

**Comment by cnsnake11** [comment]
@rockerhieu why `reactnative_assets_image1.png` ? it should be `reactnative_assets_image.png`

**Comment by Creemli** [comment]
I also meet this bug in IOS with bundled file~~~

**Comment by Creemli** [comment]
Fixed this issue with @hoangviet answer.
Please noticed that, when you add the assets folder into xcode project, use the operation "copy reference" rather not "create group".

@hoangviet   Thanks very much.

**Comment by tomauty** [comment]
This should work without the assets option in the bundler. At least, it has for me.

**Comment by andpor** [comment]
Assets do not seem to be bundled into the main offline bundle by default. Definitely does not work on iOS using 0.18. It works fine in dev mode when image is fetched from dev server but obviously I want to deploy the app standalone.

What are the instructions for iOS and Android to get the assets/images into the deployed app? What is the syntax of the shell commands for packager that need to be run. Where does React look in the app bundle when images are 'required' using a relative path to the hosting React component??

Thanks.

**Comment by typologist** [comment]
Follow this process:

1. Run the bundle command from your project root (adjust as needed):
```
react-native bundle \
--platform ios \
--entry-file index.ios.js \
--bundle-output ./main.jsbundle \
--assets-dest ./ \
--dev false
```
2. Above step will generate an "assets" folder and a "main.jsbundle" file. Add them both to your project in Xcode.

3. Finally, make sure that the images path in your JS **follow the same path relative to the assets folder**. E.g. in your image: `source={require('./app/img/image.png')`, that image should be in "assets/app/img/image.jpg".

**Comment by jsierles** [comment]
@rockerhieu Thanks for bringing up this issue!

This issue should be resolved in later versions of React Native. Assets are also automatically bundled by the iOS and Android release builds.

**Comment by sloanwolf** [comment]
Just for anybody trying to Run Release mode / main.jsbundle / assets on iOS Simulator and Images are blank, they work on device but not in Simulator.

React-Native 0.36.0.
iOS 10.1 Simulator

**Comment by Arshiamidos** [comment]
hey guys  
found the trick base on [Image doesn't show after bundling into the apk](https://github.com/facebook/react-native/issues/4084).   
as you know **require('index.html')** work on _simulator_ and _emulator_ for both &driod and IOS  
but problem will faced when you bundle and you want release your app   
for android just follow this  **enablejavascript**  and copy you files in **assets** folder in `YOUR_APP/app/src/main/assets` and use just picture below.  

and for ios just bundle package with 
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
when bundle created you have **main.bundle.js** and **asset** folder   
just copy you files in  **.xcworkspace** like this image  
![ios](https://user-images.githubusercontent.com/6451804/39201543-963c2e00-4804-11e8-9031-fb87a9f2c46e.jpg)
and set free all **refrence** in will be and unchanged just like mine. 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/39201713-1260aeac-4805-11e8-92dd-efd9209cb44f.png)
i hope this tutorial help you from confusing release app in RN
