### ISSUE TITLE
iPhone X,11,12,13,14 home indicator behavior, 

### ISSUE THREAD

**Issue by Beknur2002** [facebook/react-native#40853]
### Description

I am trying to emulate a behavior of the home indicator on iPhone X but can't figure out how. In some apps, the home indicator goes dim, and you have to swipe it to activate normal behavior. I have found an option in the Controller to hide the indicator, but that isn't what I am looking for. In Clash Royale and Clash of Clans, for example, the home indicator dims, then when you swipe up on it the indicator gets brighter, and if you do it again it activates 'home'. Hiding the indicator using an API I found really just makes it behave weirdly.

`- (UIRectEdge)preferredScreenEdgesDeferringSystemGestures {
    return UIRectEdgeAll;
}`

I add this code in my AppDelegate.m, and trying to use setNeedsUpdateOfScreenEdgesDeferringSystemGestures, prefersHomeIndicatorAutoHidden but its not work

### React Native Version

0.72.4

### Output of `npx react-native info`

OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 579.22 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Home indicator not hide

### Snack, screenshot, or link to a repository

![Screenshot 2023-10-12 at 12 23 20](https://github.com/facebook/react-native/assets/106955040/c1b1b95c-b10d-4014-aa3e-77c0d9d03d69)

**Comment by Beknur2002** [comment]
https://github.com/facebook/react-native/assets/106955040/7b77283c-1b1c-47e1-b25a-29f302d6f9c7

I'm looking for a behavior where the indicator dims, then when the user swipes up it activates, and when they swipe up again it triggers the main action

**Comment by hazemmuuhammed** [comment]
Did you find any solution ?
