### ISSUE TITLE
[IOS] <Image/> what the local image mean?

### ISSUE THREAD

**Issue by RandyZ** [facebook/react-native#4085]
I follow the Getting Start and buildup my React-Native project.
It runs perfectly, but has some problem with Image node.
I use require('image!default_icon') to show a local image.

When I change the ios project positiong out of the nodejs project folder and fix the library import, It can not work.
I get this error "Requiring unknown module 'image!default_icon'. If you are sure the module is there, try restarting the packager."
It looks like can not find the module,but i use it to load an image packed into my app.

Is there any other way to do this?

![Uploading github.png…]()

**Comment by christopherdro** [comment]
The new asset system was introduced as of 0.14.0. 
More info here http://facebook.github.io/react-native/docs/images.html#content

**Comment by RandyZ** [comment]
Thanks,I got it. But when i upgrade to 0.14, precomputeStyle.js is missed, what ti do with setNativeProps? @christopherdro

**Comment by RandyZ** [comment]
@ide @brentvatne ,precomputeStyle.js is deleted on 0.14.4? What other way do replace it?

**Comment by christopherdro** [comment]
@RandyZ Looks like its related to #3760

**Comment by nicklockwood** [comment]
Closing this, since the original question seems to have been answered.
