### ISSUE TITLE
impossible to init a new project in Linux version 0.73.0-rc.2

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native#40857]
### Description

In Linux , I do simply : 
npx react-native@next init RN0730RC2 --version 0.73.0-rc.2
 I get  

`
✔ Downloading template
⠋ Copying template/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/RN0730RC2/babel.config.js'
    at Object.chmodSync (node:fs:1991:3)
    at Object.chmodSync (/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
    at ReadStream.emit (node:events:517:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/RN0730RC2/babel.config.js'
}

Node.js v18.18.0
`
we cannot init the projet at all ! 

### React Native Version

0.73.0-rc.2

### Output of `npx react-native info`

`System:
  OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Memory: 55.70 GB / 62.62 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
`

### Steps to reproduce

simply : in a user account (it was ok on 0.72.4 ...)

npx react-native@next init RN0730RC2 --version 0.73.0-rc.2

### Snack, screenshot, or link to a repository

no use

**Comment by Productivix** [comment]
I do not understand the question sorry.
It is too easy to reproduce ?

**Comment by Productivix** [comment]
In projects versions 0.71 , I used to order a chmod 755 ./android/gradlew
on 0.72 projects I need a windows machine to init a project and transfert via Github : all is blocked in Linux ! The chmod should not be done in node commands but in bash commands

**Comment by Productivix** [comment]
same blocking bug on 0.72.6 ...

**Comment by cortinico** [comment]
> same blocking bug on 0.72.6 ...

Are you saying that you're blocked from creating projects on Linux on version .72 also?

Coudl you open an issue also here please?

https://github.com/react-native-community/cli/issues

**Comment by szymonrybczak** [comment]
Hey, this issue has been [fixed](https://github.com/react-native-community/cli/pull/2096) inside CLI, we'll release it soon.

**Comment by szymonrybczak** [comment]
Released in `11.3.9` 👍
