### ISSUE TITLE
StickyHeaderComponent not working as expected

### ISSUE THREAD

**Issue by LydGol90** [facebook/react-native#40867]
### Description

I don't think the StickyHeaderComponent is working as expected, but I may be misunderstanding the docs. The component is not docking at the top on scroll.

### React Native Version

0.70.8

### Output of `npx react-native info`

    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 52.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/XXX/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.8 => 0.70.8
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Create a very simple Flatlist with a ListHeaderComponent and a StickyHeaderComponent. By setting the stickyHeaderIndices=[1] I expected the StickyHeaderComponent to be under the ListHeaderComponent and then by setting stickyHeaderHiddenOnScroll={true} I thought that would mean it would dock at the top when scrolling up. The StickyHeaderComponent is in the second position but it does not dock when scrolling up.

`    <FlatList<number>
      data={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
      renderItem={() => <View style={{ height: 100, borderWidth: 1 }} />}
      ListHeaderComponent={() => (
        <View style={{ height: 200, borderWidth: 3 }} />
      )}
      stickyHeaderIndices={[1]}
      stickyHeaderHiddenOnScroll={true}
      StickyHeaderComponent={() => (
        <View style={{ height: 100, backgroundColor: 'red' }} />
      )}
    />`

### Snack, screenshot, or link to a repository

https://github.com/facebook/react-native/assets/29592293/021b0add-887c-4007-a81e-ccb4ad536e13

Many thanks in advance!

**Comment by LydGol90** [comment]
I've made something work by transforming the Y translation of the sticky header component myself, but again, not sure if this is how the component is supposed to work. Thanks

**Comment by Marcoo09** [comment]
@LydGol90 I'm not really sure why it doesn't work, but you can use the section list to get the same result. [Here](https://github.com/facebook/react-native/issues/31109) you'll find a similar discussion
