### ISSUE TITLE
[Android] run on device: Unable to upload some APKs

### ISSUE THREAD

**Issue by liesislukas** [facebook/react-native#4086]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unable to upload some APKs
```

TM-550 Android tablet. Unknown sources enabled. Debug via USB - enabled. 
Tablet is new, no Google Account or anything attached.

**Comment by atom992** [comment]
I fixed by rerun the following command:
```
adb install app/build/outputs/apk/app-debug.apk
```

**Comment by liesislukas** [comment]
I've already done that app. Solution was OS restart. Don't know what was wrong. Didn't knew about adb install command. Thanks, maybe it will help me next time or someone else reading this issue :+1:

**Comment by sahas-** [comment]
I ran into this problem last night..adb install did the trick..

**Comment by SuunZhu** [comment]
however, adb install is not better to resolve this issue

**Comment by JoeLucky** [comment]
Did you really just restart OS sloving this problem, or did some other oprating? I cannot fix it by restarting OS. By the way, adb install is really not a good idea.

**Comment by liesislukas** [comment]
@JoeLucky try genymotion, i never had any similar issues with it. They have paid plans, but you can live with free plan easily.

https://www.genymotion.com/download/

**Comment by JoeLucky** [comment]
I solve that problem by turning gradle version into low version. (from 2.4 to 2.2).

**Comment by owen19891030** [comment]
because of gradle version is high,so change the version lower

**Comment by yimsamtam** [comment]
66

**Comment by GerryQuest** [comment]
I had to increase the gradle version to 2.0.0
