### ISSUE TITLE
Need to tap twice in order to tap on TouchableHighlight when it is within a ScrollView or ListView

### ISSUE THREAD

**Issue by shrimpywu** [facebook/react-native#4087]
perform below action in sample app

1) input something in the text box
2) click the button 

https://rnplay.org/apps/KjmElQ

expecting:
tap once, keyboard will go away and will trigger "onPress" event on the TouchableHightlight

actual:
have to tap twice. first tap keyboard go away, second tap then trigger "onPress" event on TouchableHightlight

**Comment by FaridSafi** [comment]
did you try to add keyboardShouldPersistTaps={true} to the scrollview props ?

**Comment by shrimpywu** [comment]
@FaridSafi thanks for the suggestion. it solve the issue that need to click twice. however it cause another issue. the keyboard won`t go away.

**Comment by hufeng** [comment]
try my solution. 

```javascript
export default FormContainer = React.createClass({
  mixins: [PureRenderMixin],


  render() {
    return (
      <ScrollView
        showsVerticalScrollIndicator={true}
        automaticallyAdjustContentInsets={false}
        contentContainerStyle={styles.content}
        keyboardDismissMode='on-drag'
        keyboardShouldPersistTaps={true}>
        <View
          onStartShouldSetResponderCapture={(e) => {
            const focusField = TextInputState.currentlyFocusedField();

            if (focusField != null && e.nativeEvent.target != focusField){
              dismissKeyboard();
            }
          }}>
          {this.props.children}
        </View>
      </ScrollView>
    );
  }
});
```

**Comment by marcshilling** [comment]
@hufeng this is awesome except if you have multiple text inputs in the form, the keyboard "jumps" switching between them

**Comment by hufeng** [comment]
@marcshilling yes, i have multiple text inputs in the form.

**Comment by gre** [comment]
anyone have an idea to fix this globally, not specifically with workaround provided here? I would be happy to provide a PR, but I'm not sure where the problem source is.

**Comment by jcihocki** [comment]
I'm experiencing this issue even when the keyboard isn't in play. I have a TouchableHighlight within a scrollview, and only the second tap on the button results in onPress being invoked.

**Comment by grabbou** [comment]
@gre I am using a `Dismissable` component, wrapping any number of children will hide the keyboard and forward the events.

Here's the source:
```js
import React, {
  View,
  TextInput
} from 'react-native';

import MainEntryContext from '../components/main-entry-context';
import ReactNativeTagHandles from 'ReactNativeTagHandles';

class Dismissable extends React.Component {
  static propTypes = {
    ignoredAreas: React.PropTypes.func,
  };

  static defaultProps = {
    ignoredAreas: () => [],
  };

  componentDidMount() {
    this.ignoredNodes = this.props.ignoredAreas()
      .map(ref => React.findNodeHandle(ref))
      .map(tag => ReactNativeTagHandles.tagToRootNodeID[tag]);
  }

  _dismissKeyboard = (e) => {
    const ignoredTarget = this.ignoredNodes.find(node => e.dispatchMarker.indexOf(node) >= 0);

    if (!ignoredTarget) {
      TextInput.State.blurTextInput(
        TextInput.State.currentlyFocusedField()
      );
    }

    return false;
  };

  render() {
    return (
      <View style={{ flex: 1 }} onStartShouldSetResponderCapture={this._dismissKeyboard}>
        {this.props.children}
      </View>
    )
  }
};

module.exports = Dismissable;
```
Just wrap any component and optionally pass it an array of refs to ignore (e.g inputs)

**Comment by gre** [comment]
@grabbou interesting idea :)

**Comment by alloy** [comment]
@jcihocki I have the same issue, without any text inputs. Were you able to find out the cause in your situation?

**Comment by cyphire** [comment]
@jcihocki & @alloy I also have the same problem... Any find?

**Comment by alloy** [comment]
@cyphire My bad, I should’ve updated earlier in my case it ended up being a native module of mine that was using the `RCTUIManager` to find a view for a react tag in an incorrect way. It works fine for me now.

**Comment by cyphire** [comment]
Thanks for the update... A month ago I had rusty JavaScript.. Now I'm
crushing it!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/need-to-tap-twice-in-order-to-tap-on-touchablehighlight-when-it-is-within-a-scrollview-or-listview

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by indivisable** [comment]
I am experience same thing but only with Views and buttons (no text input), has anyone found a good solution for this?

**Comment by deepaksisodiya** [comment]
This is how i solve it.

I had one input and one button inside view.

```
<View>
  <Input>
  <Button>
</View>
```

I wanted it to be scrollable so i added

```
<ScrollView>
<View>
  <Input>
  <Button>
</View>
</ScrollView>
```
But then button needs to have a double click in order to work
so i added keyboardShouldPersistTaps={true} in scrollView in order to button work on one click

```
<ScrollView keyboardShouldPersistTaps={true}>
<View>
  <Input>
  <Button>
</View>
</ScrollView>
```

But this causes the not hide keyboard when click on anywhere on screen. So i did it by doing this

final code

```
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'
import dismissKeyboard from 'react-native-dismiss-keyboard';

<KeyboardAwareScrollView keyboardShouldPersistTaps={true} >
   <TouchableWithoutFeedback onPress={dismissKeyboard}>
       <View>
          <Input>
         <Button>
      </View>
  </TouchableWithoutFeedback>
</KeyboardAwareScrollView>
```

The above code works for all condition

**Comment by ragnorc** [comment]
You can now also user Keyboard.dismiss after importing Keyboard from react-native:

`import {Keyboard} from 'react-native';`

**Comment by deepaksisodiya** [comment]
@ragnorc 
Thanks, I will try your solution also :)

**Comment by joshuapinter** [comment]
@ragnorc is correct. They fixed this over the last two years and now just setting `keyboardShouldPersistTaps="handled"` on your `ScrollView` allows your children `Touchables` to handle the click event when appropriate. 

Progress! 🚀

**Comment by shakyShane** [comment]
as @joshuapinter pointed out, `keyboardShouldPersistTaps="handled"` should be enough. If however you have 2 (or more) nested components that all handle this prop, you'll need to provide it to each.

eg: 

```jsx
<ScrollView
    keyboardShouldPersistTaps="handled">
    ...
    ...
    <SwipeableListView
        dataSource={ds}
        keyboardShouldPersistTaps="handled"    
    >
        ...
        ...
        ...
    </SwipeableListView>
</ScrollView>
```

**Comment by AndrewHenderson** [comment]
Is anyone trying to use `keyboardShouldPersistTaps` on a ListView? I have it working on ScrollViews, but I can't press a touchable item in a ListView without first closing the keyboard.

**Comment by agersoncgps** [comment]
This solved it for me: https://stackoverflow.com/questions/42808294/react-native-have-to-double-click-for-onpress-to-work

**Comment by bportman** [comment]
Update - The above was definitely not workable, but I was able to get the desired by behavior by modifying the ScrollResponders.js file in /react-native/Libraries/Components as described here: https://github.com/facebook/react-native/issues/4229#issuecomment-174333284

Would love a solution that doesn't require me to modify a react-native file though!
