### ISSUE TITLE
React Native ios app crashes with an error - Undefined symbol: _RTNQrCodeCls

### ISSUE THREAD

**Issue by Yurii-Lutsyk** [facebook/react-native#40886]
### Description

When running the React Native ios app (version 0.76) from the git repository https://github.com/Yurii-Lutsyk/rnapp, the app crashes with an error message "Undefined symbol: _RTNQrCodeCls". This issue occurs when generating codegen artifacts and installing pods.

Expected Result: The app should run without any errors and display the expected output.

Actual Result: The app crashes with an error message "Undefined symbol: _RTNQrCodeCls".

Environment:
- React Native version: 0.76.2
- OS: iOS
- Git repository: https://github.com/Yurii-Lutsyk/rnapp

Additional Information:
This issue seems to be related to the new architecture of React Native. Further investigation is required to identify the root cause of this issue.

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 63.20 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: ~/.nvm/versions/node/v18.15.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.15.0/bin/yarn
  npm:
    version: 9.5.0
    path: ~/.nvm/versions/node/v18.15.0/bin/npm
  Watchman:
    version: 2023.04.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 3.1.3
    path: /opt/homebrew/opt/ruby@3.1/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1. Run from parent rnapp folder - node rnapp/node_modules/react-native/scripts/generate-codegen-artifacts.js \
  --path rnapp/ \
  --outputPath rnapp/RTCScanQr/generated/
2. Install pods - yarn pod-install
3. Run yarn ios.

### Snack, code example, screenshot, or link to a repository

https://github.com/Yurii-Lutsyk/rnapp

**Comment by Yurii-Lutsyk** [comment]
@cortinico

**Comment by cipolleschi** [comment]
Can you share your podspec inside a <code>```ruby</code> block, please?

**Comment by cortinico** [comment]
Closing as answered
