### ISSUE TITLE
[Android] TextInput maxLength is broken.

### ISSUE THREAD

**Issue by qbig** [facebook/react-native#4089]
```
  <TextInput maxLength={4} style={styles.emptyText} />
```

This props have no effect for the code above. Is it iOS only ?

**Comment by ide** [comment]
Yes, as the docs say it is iOS only.

**Comment by fxhereng** [comment]
The doc doesn't mention it (https://facebook.github.io/react-native/docs/textinput.html#maxlength), is it fixed in the version 0.16.0-rc ?

**Comment by Kudo** [comment]
@fxhereng Fixed in 0.16.0 from #3873
