### ISSUE TITLE
.gradlew bad permissions at transfert on Linux gives a bad error message clue

### ISSUE THREAD

**Issue by Productivix** [facebook/react-native#40913]
### Description

- you have a RN 0.72 project on Windows, you transfert it by Github clone on Linux
- so you can see that android/gradlew execution permissions are none (-rw-r--r--)
- you run "yarn run android" and system replies : 
`yarn run v1.22.19
$ react-native run-android
info JS server already running.

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

error Failed to install the app.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

which is FALSE : the message was more explicit on version 0.71 ! (saying that gradlew cannot be run)

You can search the problem a long time with such a message !!

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Memory: 52.71 GB / 62.62 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

on linux : simple !
- remove the exec permissions of gradlew 
- yarn run android

### Snack, screenshot, or link to a repository

you can init a blank project on linux (if you can because of other bugs !)
and you make the 2 simple steps to reproduce.

**Comment by Productivix** [comment]
I upgraded to 0.72.6
same issue , same repro

**Comment by cortinico** [comment]
> * so you can see that android/gradlew execution permissions are none (-rw-r--r--)

We use the default permissions that Gradle creates for the Gradle Wrapper.
I can see that the execution bit is set correctly:

```
$ ls -la
drwxr-xr-x   9 ncor  staff   288 Oct 13 16:10 .
drwxr-xr-x  20 ncor  staff   640 Oct 13 16:10 ..
drwxr-xr-x   6 ncor  staff   192 Oct 13 16:10 app
-rw-r--r--   1 ncor  staff   601 Oct 13 16:10 build.gradle
drwxr-xr-x   3 ncor  staff    96 Oct 13 16:10 gradle
-rw-r--r--   1 ncor  staff  1902 Oct 13 16:10 gradle.properties
-rwxr-xr-x   1 ncor  staff  8497 Oct 13 16:10 gradlew
-rw-r--r--   1 ncor  staff  2868 Oct 13 16:10 gradlew.bat
-rw-r--r--   1 ncor  staff   249 Oct 13 16:10 settings.gradle
```

**Comment by Productivix** [comment]
yes, I forgot to tell you but you can imagine : 
- I cannot on Linux create (init ) a project, so they come through Github from a Windows init 
- that is to say that at Gthub clone from a Windows initied project, that we still not have the adapted message to solve our issue.
so I will come back and close as soon I can init a project on Linux.

**Comment by cortinico** [comment]
This and other similar issues related to the `init` command shoudl be opened against the CLI as that's where the `init` code lives.

https://github.com/react-native-community/cli/issues

**Comment by cortinico** [comment]
Let's open another issue there and let's continue the conversation there

**Comment by Productivix** [comment]
hi , on new 0.72.7 created , gradlew has the exec permission on linux - good - thks
