### ISSUE TITLE
The debug package crashes while running, and the release package will not：__emutls_get_address ...libfolly_runtime.so

### ISSUE THREAD

**Issue by yubaokang** [facebook/react-native#40928]
### Description

The debug package compiled from local source code will crash, while the release package will not. The error is as follows:

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~BQSbFHjH1qN53NQ8u0q9zw==/com.xxxx.xxxxxx-3joEDE9HHdg2BRteyx4Mfw==/lib/arm64/libfolly_runtime.so"...

<img width="1373" alt="image" src="https://github.com/facebook/react-native/assets/7115700/2b8ba9b6-b38b-4f52-895b-4e98dc3042d5">

### React Native Version

0.72.5

### Output of `npx react-native info`

I integrated it in the form of a native app

![image](https://github.com/facebook/react-native/assets/7115700/a1d68357-5697-43e5-a989-4fa7a5b440b7)

### Steps to reproduce

none

### Snack, screenshot, or link to a repository

none

**Comment by cortinico** [comment]
Can you create a reproducer?

**Comment by shubhamguptadream11** [comment]
@yubaokang Are you able to solve this?
I am also getting this on my brownfield project.

**Comment by cortinico** [comment]
Closing with the same reason as https://github.com/facebook/react-native/issues/41238.
This is most likely caused by you using a wrong version of the NDK (or any of your dependency importing a native library which has been compiled with a different version of the NDK)

**Comment by 553082694** [comment]
I meet the same problem, pls help me

**Comment by gamingumar** [comment]
facing same issue, please help

**Comment by zhairui** [comment]
I meet the same problem , but I have many so files, how can i find which so file was used other ndk version? thank you

**Comment by flyskywhy** [comment]
> I meet the same problem , but I have many so files, how can i find which so file was used other ndk version? thank you

Just remove a `react-native-SOME` one by one in `package.json`, then build and see if the APP will not crash on start anymore :stuck_out_tongue_closed_eyes:

**Comment by flyskywhy** [comment]
No need to rebuild third-party `.aar` or `.so`, just patch:
```
cd tools/android-sdk/ndk

mv ./21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so ./21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/origin_libc++_shared.so
cp ./23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so ./21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/
```
as described in [Patch to fix `__emutls_get_address` crash on Android](https://github.com/flyskywhy/playtorch/commit/8bcbb0c2c5679c70e0416f0a0a5e3aace529a833)

**Comment by wenchengshen** [comment]
@yubaokang 你后面是怎么解决这个问题的

**Comment by inkCrazy** [comment]
问题怎么解决的？

**Comment by inkCrazy** [comment]
> @yubaokang 你后面是怎么解决这个问题的

问题怎么解决的？@wenchengshen

**Comment by Qdafengzi** [comment]
被这个问题折磨了一天了，原因就是 ffmpeg-kit-full 库已经不在维护，二进制文件已经被删除了， 手动依赖arr 导致了类似的错误，自从使用了react native 每天都在跟这个东西斗智斗勇，快被折磨死了。
