### ISSUE TITLE
Xcode build error when run  react-native-xcode.sh

### ISSUE THREAD

**Issue by shanwen0120** [facebook/react-native#4092]
After I upgrade my project to RN v0.14.2, i got below error when build project.

+  react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/username/Library/Developer/Xcode/DerivedData/testproject-xxxxxxxxxxxxx/Build/Products/Debug-iphonesimulator/infaniapp.app/main.jsbundle --assets-dest /Users/username/Library/Developer/Xcode/DerivedData/testproject-xxxxxxxxxxxxxxxx/Build/Products/Debug-iphonesimulator/testproject.app
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module image!login-bg from /Users/username/Documents/ReactNative/testproject/js/pages/login/menu.js: Invalid directory /Users/node_modules/image!login-bg
    
  at /Users/username/Documents/ReactNative/testproject/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:323:15
    
  at ...

Command /bin/sh failed with exit code 1

This project works fine in RN v0.13.2.
It seems like it want to get image under "/Users/node_modules/image!login-bg" ? but there isn't this folder actually. How can i fix the problem?

Thanks so much.

**Comment by christopherdro** [comment]
@shanwen0120 This is because of the new asset system that was implement in 0.14.0.
See, https://facebook.github.io/react-native/docs/images.html#content

**Comment by shanwen0120** [comment]
Oh my gosh! I'm so stupid for missing this document!! 
Thanks for replying.
