### ISSUE TITLE
normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'project_name' from project 'project_name')

### ISSUE THREAD

**Issue by Piyush-Ratlani** [facebook/react-native#40932]
### Description

When running npx react-native run-ios I am getting the error

normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'project_name' from project 'project_name')

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M2
  Memory: 173.06 MB / 8.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 16.20.1
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 8.19.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/opt/ruby/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1. npx react-native@latest init project_name
2. cd ios
3. bundle install
4. pod install
5. cd ..
6. npx react-native run-ios

Project worked correctly here

Then I installed and setup the packages as mentioned in package.json. I first setup all the packages except firebase, and the project worked absolutely correct till then. Then I setup firebase for ios using the methods provided in the documentation - [https://rnfirebase.io/#3-react-native-cli---ios-setup](url) . Then I started facing the errors for normal arm64, then I resolved some of them by editing Podfile (code provided below). But atlast I am getting the error "normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'project_name' from project 'project_name')", which I am unable to resolve.

I tried clean build folder from xcode, tried cleaning pod cache nothing worked. I have also attached appdelegate.mm below for your reference.

below is my xcode build error.

![image](https://github.com/facebook/react-native/assets/69811087/b9a572f4-9525-4141-9d27-f6c4e0747287)

### Snack, code example, screenshot, or link to a repository

package.json

`{
  "name": "sa.reno.customerapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-firebase/app": "^18.5.0",
    "@react-native-masked-view/masked-view": "^0.3.0",
    "@react-navigation/bottom-tabs": "^6.5.9",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "@react-navigation/stack": "^6.3.18",
    "@reduxjs/toolkit": "^1.9.7",
    "base-64": "^1.0.0",
    "i18next": "^23.5.1",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-i18next": "^13.2.2",
    "react-native": "0.72.5",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^2.13.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-ratings": "^8.1.0",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-redux": "^8.1.3",
    "redux-persist": "^6.0.0",
    "url": "^0.11.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
`

Podfile

`
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, "13.4"
prepare_react_native_project!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

prefix = path

target 'reno_customer' do
  config = use_native_modules!

  flags = get_default_flags()

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'reno_customerTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
    end

    installer.pods_project.targets.each do |target|
      if target.name == "RNScreens" || target.name == "RNGestureHandler"
          append_header_search_path(target, "${PODS_ROOT}/../../node_modules/react-native/ReactCommon")
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

def append_header_search_path(target, path)
  target.build_configurations.each do |config|
      # Note that there's a space character after `$(inherited)`.
      config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
      config.build_settings["HEADER_SEARCH_PATHS"] << path
  end
end
`

AppDelegate.mm

`
#import "AppDelegate.h"
#import "React/RCTI18nUtil.h"
#import <React/RCTBundleURLProvider.h>
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];

  // Enable RTL support
  [[RCTI18nUtil sharedInstance] allowRTL:YES];

  self.moduleName = @"reno_customer";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

`

**Comment by cipolleschi** [comment]
duplicated of #38283: the errors are different but the root cause is the same. There are packages that are not working due to some missing `header_search_path`. I hope to be able to fix that first thing next week.

Please, let's collect all the failures there.

**Comment by sebasgre** [comment]
This solution works fine for me, try to do the same:

```
flipper_config = FlipperConfiguration.disabled
#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'rnOwner' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
```
