### ISSUE TITLE
[Suggestion] Add doc clarification whether RN Flexbox uses dp or pixel as the unit of sizing values

### ISSUE THREAD

**Issue by ACCTFORGH** [facebook/react-native#4094]
I was used to using dp in native Android but I am really confused whether the default unit used for Flexbox sizes is dp or pixels.  In the documentation, there is the code below that suggests it uses dp instead of pixel as the size unit. Here the getPixelSizeForLayoutSize() function tries to convert dp values to pixel values. However, in real applications, my components get out of screen bound when not dividing the size values (height/width, etc) by PixelRatio.get(). Would really appreciate your clarification!

var image = getImage({
  width: PixelRatio.getPixelSizeForLayoutSize(200),
  height: PixelRatio.getPixelSizeForLayoutSize(100),
});
<Image source={image} style={{width: 200, height: 100}} />

Same question raised in StackOverflow: http://stackoverflow.com/questions/33670100/does-flexbox-in-react-native-use-dp-or-pixel

**Comment by ide** [comment]
Answered on SO. If you want to send a PR to add a short note to the docs we can take a look and help merge it.

**Comment by ACCTFORGH** [comment]
Thanks @ide. All my designs are now in dp (Android version of the iOS "points" or logical pixels). Is there a way to convert dp to iOS points? I did some search but couldn't find much useful info.

**Comment by ide** [comment]
Logical pixels == iOS points. If you're trying to convert to device pixels, multiply by `[UIScreen mainScreen].screenScale`.

**Comment by ACCTFORGH** [comment]
@Ide Thanks. I've also figured it out. I guess there is some different understanding of dp. In Android it also means Density-independent pixel. At Javascript level, I think Flexbox uses dp as the unit.
