### ISSUE TITLE
[Navigator] Changing the defaultTransitionVelocity affect all transitions

### ISSUE THREAD

**Issue by elisei-timofte** [facebook/react-native#4096]
I want for one transition to have a very hight velocity, so the FloatFromRight or another effect will not be seen. I realized that when I've changed the defaultTransitionVelocity of a push, all navigator.push will use the new value. 

I want to use something like transitionVelocity, to alter locally not globally

```javascript
this.props.navigator.push({
          ref: rootRef, 
          sceneConfig: Object.assign({}, Navigator.SceneConfigs.FloatFromLeft, {
            defaultTransitionVelocity: 10000,
          })
})
```

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
