### ISSUE TITLE
[Android] "Network request failed" with Parse.com Restful API

### ISSUE THREAD

**Issue by AwesomeJerry** [facebook/react-native#4097]
Hello, I'm trying to use GET request of "https://api.parse.com/1/classes/Hello" to get my data back, and everything works well with queries like "https://api.parse.com/1/classes/Hello"(return an array with data) and "https://api.parse.com/1/classes/Hello/objectId"(return the object). However, it shows the "Network request failed" if I add any constraints to the url such as "https://api.parse.com/1/classes/Hello?where={"name":"world"}". 
Is there anyone who encounters the same circumstance and found out a solution?

**Comment by christopherdro** [comment]
@AwesomeJerry Were you able to resolve this issue? If not, could you provide some code of how your making your api calls?

**Comment by AwesomeJerry** [comment]
It turns out I need to use encodeURIComponent to encode the parameters, which is unnecessary in iOS.
this can be closed! Thanks!!
