### ISSUE TITLE
"ReferenceError: Can't find variable: process" after update to 0.14.2

### ISSUE THREAD

**Issue by robinsmedberg** [facebook/react-native#4098]
Hi,

I updated to version 0.14.2 from 0.13 and getting errors referring to variable "process" that does not yet exist.

First location it fails is here in the main.jsbundle:

var ReactPerf={
enableMeasure:false,
storedMeasure:_noMeasure,
measureMethods:function(object,objectName,methodNames){
if(process.env.NODE_ENV !== 'production'){

My package.json:

{
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "art": "^0.10.0",
    "flux-util": "0.1.1",
    "immutable": "^3.7.4",
    "is-promise": "^2.0.0",
    "parse": "^1.6.9",
    "parse-react": "^0.5.0",
    "pure-render-decorator": "^0.1.0",
    "react": "^0.14.2",
    "react-dom": "^0.14.2",
    "react-native": "^0.14.2",
    "react-native-carousel": "^0.3.5",
    "react-native-image-picker": "^0.9.0",
    "react-native-linear-gradient": "^1.1.0-alpha",
    "react-native-navbar": "^0.5.2",
    "react-native-video": "^0.6.1",
    "react-pure-render": "^1.0.2",
    "react-timer-mixin": "^0.13.2"
  }
}

**Comment by kusamakura** [comment]
I believe this is also #4022

**Comment by jsierles** [comment]
This should be fixed in latest versions of React Native. Closing out for now!

**Comment by GeoffreyPlitt** [comment]
The recommendations all say to upgrade react to 15.2.1. I just got this same error/crash with react=15.3.1.

**Comment by cvongrim** [comment]
Same problem here as GeoffreyPlitt. Receive the error with both react 15.2.1 and 15.3.1

**Comment by woniesong92** [comment]
This error is quite prevalent in the latest RN. It happens the most when a new npm package has been installed.

**Comment by LukeStClair** [comment]
Downgrading to 15.3.2 solved this for me. Didn't figure out the issue with 15.4.0.

**Comment by LoseTheQuit** [comment]
I've been having this same issue. I renamed one file and hit when to schittz.. I've tried downgrading my react-native package and also my react package. I can't find the right combination of react-native@0.3?.? with react-@15.??.? to get my app up and running. If anyone has any suggestions. Let me know please.

**Comment by matttti** [comment]
I had the same error (react-native@0.34.1, react@15.3.2). I've tried virtually everything and what finally helped was a restart of my MBP. Sounds weird, i have no idea why, but if this is of help to you, i'm happy.

**Comment by duzliang** [comment]
I had the same error after upgrade react-native(0.37.0) and react(15.4.0) , finally I downgrading the react to 15.3.2 solved this

**Comment by JonasWho** [comment]
I am getting this error too. With RN 0.37. I've tried everything now. Restarting, changing React version etc. Nothing works. Any help out there?

**Comment by matttti** [comment]
Do you use any custom babel plugins? I had one which tried to access process.env before proper initialization by RN.

**Comment by JonasWho** [comment]
@matttti No, but after 24h of trying a million things, finally upgrading to RN 0.38 solved it. No idea why though. But thanks for the reply!

**Comment by Gelassen** [comment]
Faced with similar issue on version react-native@0.39.2. Environment: Win 7. Do you have any proposals how to solve it?

**Comment by nobalmohan** [comment]
@Gelassen Downgrade to react-native@0.38.0

**Comment by blackLearning** [comment]
I use yarn instead of npm v5 to solves this problem(for anyone might stuck in here)

**Comment by itinance** [comment]
having this issue with RN 0.51. Is it only me?

**Comment by roshangm1** [comment]
@itinance I do have the issue too.

**Comment by 1c7** [comment]
yep, 2018-Jan-20, RN 0.51 same problem, no idea why,
