### ISSUE TITLE
How to update maven url in 0.72?

### ISSUE THREAD

**Issue by linxianxi** [facebook/react-native#40997]
### Description

I added this line but it didn't work. I could only find a way to modify the version on Google, but the new version no longer has the allprojects configuration.
```
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'http://maven.aliyun.com/nexus/content/repositories/releases' }   // add this line
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}
```

### React Native Version

0.72.5

### Output of `npx react-native info`

.

### Steps to reproduce

.

### Snack, screenshot, or link to a repository

.

**Comment by cortinico** [comment]
> How to update maven url in 0.72? #40997

Can you clarify what you're looking into doing? @linxianxi
