### ISSUE TITLE
RN 0.68.2 com.facebook.jni.CppException: Compiling JS failed: Wrong bytecode version. Expected 84 but got 94 Buffer size 6188882 starts with: c61fbc03c103191f5e00000044e4c8f7 and has protection mode(s): r--p

### ISSUE THREAD

**Issue by thang-duong** [facebook/react-native#40995]
### Description

com.facebook.jni.CppException: Compiling JS failed: Wrong bytecode version. Expected 84 but got 94 Buffer size 6188882 starts with: c61fbc03c103191f5e00000044e4c8f7 and has protection mode(s): r--p
                                         	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                         	at android.os.Handler.handleCallback(Handler.java:789)
                                         	at android.os.Handler.dispatchMessage(Handler.java:98)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                         	at android.os.Looper.loop(Looper.java:164)
                                         	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
                                         	at java.lang.Thread.run(Thread.java:764)

### React Native Version

0.68.2

### Output of `npx react-native info`

System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 84.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
    Watchman: 2023.09.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30, 31, 32, 33, 33, 33, 34
      Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
      System Images: android-23 | ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-26 | ARM 64 v8a, android-26 | Google APIs ARM 64 v8a, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86_64 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs ARM 64 v8a, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs ARM 64 v8a, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86_64 Atom, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | AOSP ATD ARM 64 v8a, android-30 | AOSP ATD Intel x86 Atom, android-30 | AOSP ATD Intel x86_64 Atom, android-30 | ARM 64 v8a, android-30 | Intel x86_64 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86_64 Atom, android-30 | Google APIs ATD ARM 64 v8a, android-30 | Google APIs ATD Intel x86 Atom, android-30 | Google APIs ATD Intel x86_64 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86_64 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play ARM 64 v8a, android-31 | Google Play Intel x86_64 Atom, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86_64 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

Build app use expo build -> Install app on device -> Expo update app -> Open app and execute update app

### Snack, screenshot, or link to a repository

<img width="1062" alt="Screenshot 2023-10-16 at 11 43 25" src="https://github.com/facebook/react-native/assets/27408573/2928c889-7a08-448c-950b-04079842c214">

**Comment by muhammadalizkhan** [comment]
Its must be version issue or may be expo node r-n compatibility, 

npm update -g expo-cli
npm update --save
npx react-native start --reset-cache

//bash
rm -rf node_modules
npm install

also you need to upgrade your react native version, if you want to use older than check all npm node expo etc compatibility with each other

**Comment by cortinico** [comment]
> com.facebook.jni.CppException: Compiling JS failed: Wrong bytecode version. Expected 84 but got 94 Buffer size 6188882 starts with: c61fbc03c103191f5e00000044e4c8f7 and has protection mode(s): r--p

This happens when you're using a version of `hermesc` locally which doesn't correspond to the version of `hermes-engine` you're shipping in your app.

Without looking at your code or at a reproducer we can't help further sadly.

**Comment by usmanabid94** [comment]
I am also facing the same issue updated the project from 0.61 to 0.72.6 and on app startup get this error

**Comment by ryan-k-swyftx** [comment]
@cortinico I'm running into a similar issue on upgrade, do you know where one could check their versions of `hermesc` and compare to the `hermes-engine` version?

**Comment by usmanabid94** [comment]
I had been able to run down the same error on a different project any body has any idea on it why it occurs:
![image](https://github.com/facebook/react-native/assets/47411086/59568edc-3174-4d59-a6c9-8e19ad1ad1dd)
