### ISSUE TITLE
Include ListViewDataSource docs somewhere

### ISSUE THREAD

**Issue by glenjamin** [facebook/react-native#410]
I guess ideally they should be on the ListView page?

The docblocks in https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListViewDataSource.js seem fairly complete, I just can't find the info on the docs site.

**Comment by pjjanak** [comment]
Would be resolve by PR #360

**Comment by Crash--** [comment]
I think there is a regression here. I can't find the documentation about ListViewDataSource on the ListView page (https://facebook.github.io/react-native/docs/listview.html#datasource)

**Comment by satya164** [comment]
Same here. `ListViewDataSource`docs will be awesome to have.

**Comment by TiagoGouvea** [comment]
Needing too.

**Comment by mikedizon** [comment]
+1

**Comment by thunderousNinja** [comment]
+1

**Comment by wootwoot1234** [comment]
+1

**Comment by vjeux** [comment]
cc @martinkonicek

**Comment by vjeux** [comment]
cc @mkonicek

**Comment by jordansexton** [comment]
+1

**Comment by tomauty** [comment]
+1

**Comment by appden** [comment]
These docs are _still_ missing.

**Comment by crockpotveggies** [comment]
+1

**Comment by tkmoney** [comment]
+1

**Comment by sjchmiela** [comment]
+1

**Comment by MichaelDanielTom** [comment]
+1

**Comment by rodginez** [comment]
+1

**Comment by satya164** [comment]
It would be great if somebody could send a PR for this.

**Comment by jordansexton** [comment]
#1 result on Google for ListViewDataSource is this issue.
#2 is #1880.
Yep. It would be great if someone who knows how it works could document it.

**Comment by grabbou** [comment]
I have submitted an initial take on that which basically just includes what we have already documented. That probably helps a bit, but if any of you could take a look at the current state of DataSource docs and see if they can be improved, it would be awesome!
