### ISSUE TITLE
TextInput handles don't reflect selectionColor on Android

### ISSUE THREAD

**Issue by szmarczak** [facebook/react-native#41004]
### Description

<img src="https://github.com/facebook/react-native/assets/36894700/bdeb1397-7eef-4634-828d-1c9de772bf16" width="300">

The handles are cyan but should be red.

### React Native Version

0.72.5

### Output of `npx react-native info`

```
>npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600 6-Core Processor              "
  Memory: 14.86 GB / 31.91 GB
Binaries:
  Node:
    version: 20.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.7.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33424.131 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.20.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

Link below. Run on Android.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@szmarczak/smart-blue-bubblegum

**Comment by frankcalise** [comment]
Hey thanks for the report - is this a regression since a certain version do you know? Or has it always been like this?

**Comment by szmarczak** [comment]
I'm quite new to React Native and this is the first time I'm using `TextInput`, however this seems to be a regression: https://github.com/facebook/react-native/issues/30283

**Comment by jakex7** [comment]
Hi, I have found a solution to this problem on the native side and would like to create a PR. However, I am wondering if selectionColor/cursorColor is the right place to set handles color. 

The current behavior is that if the API level is below 28 handles color is set along with `cursorColor`. 

There are two possible solutions to this problem: 
1. create a new prop called `handlesColor`, which would contain the carried over logic from the API before 28 and a new one that will work in newer versions.
1. adding new logic to `cursorColor` to continue the behavior as it is currently on older versions of Android

Let me know what you think about this and which solution would be better @szmarczak @frankcalise

**Comment by szmarczak** [comment]
I've got Android 13 and it doesn't work regardless if I use `selectionColor` or `cursorColor`.

I think it would be best to create a new attribute like you mentioned - `selectionHandlesColor`. If it's `undefined`, then the handles use `selectionColor`. Otherwise, use the new value.

**Comment by 1280103995** [comment]
This problem still exists. selectionColor does not change the cursor color on Android 7. (RN0.76)
