### ISSUE TITLE
Bug in ios 17 in Flatlist

### ISSUE THREAD

**Issue by roysG** [facebook/react-native#41007]
### Description

Sometimes in FlatList i started to get this error:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={4.9999847412109375, 0}, scale=3.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.'
*** First throw call stack:
(0x18bc3a5e0 0x183f6fc00 0x18b1a44d4 0x18de548b0 0x10507a6b8 0x105079fec 0x1050d4cec 0x18d1ab51c 0x18d1b194c 0x18d1aac3c 0x18d1aa8e4 0x18de0b228 0x18de0ad40 0x18de0a430 0x18de0a4ec 0x18bb84acc 0x18bb83d48 0x18bb824fc 0x18bb81238 0x18bb80e18 0x1ce6455ec 0x18df8f2fc 0x18df8e938 0x104f10354 0x1ae36bd44)
libc++abi: terminating due to uncaught exception of type NSException

The error started when i updated to ios 17

### React Native Version

0.68

### Output of `npx react-native info`

System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.08.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1.Create FlatList with many rows, 
2. add Icons in the list
3. start scrolling

(The crash not always happens, but most of the time)

### Snack, screenshot, or link to a repository

I do not have

**Comment by roysG** [comment]
> do you use fast-image to load image?

Hi,
No, i am using the regular load image of react native

**Comment by benzman81** [comment]
@roysG why did you close this? did you fix this? we have the same error.

**Comment by trucuit** [comment]
same issue

**Comment by cuongnv1** [comment]
b
