### ISSUE TITLE
Image Preloading / Image load order

### ISSUE THREAD

**Issue by meznaric** [facebook/react-native#4100]
I want to control in what order images are loaded. I created an utility javascript file for managing order of images to load.

I tried using `fetch(imageUrl)` directly, but it does't seem it is caching the images. After some googling I found issue https://github.com/facebook/react-native/issues/2314 which has some snippets in the comments... But unfortunately react codebase has updated since and `RCTImageDownloader` does not exists anymore.

I went through few files in `Libraries/Image` and tried to produce my own solution, but I was unable to do so because of my insufficient obj-c skills.

What are my options to preload images?

**Comment by meznaric** [comment]
Okay, after spending some more time I found a solution. Apparently you can use `loadImageWithTag` from `RCTImageView`. Here is the code from #2314 but modified so it works with latest version of react.

    #import "RNPreloadImage.h"
    #import "RCTImageView.h"
    #import "RCTBridge.h"
    #import "RCTImageLoader.h"

    @implementation RNPreloadImage

    RCT_EXPORT_MODULE(); // actually exported as "RNPreloadImage"

    @synthesize bridge = _bridge;

    //
    RCT_EXPORT_METHOD(prefetch:(NSString *) src
                      onComplete:(RCTResponseSenderBlock)completeBlock) {
      [self.bridge.imageLoader loadImageWithTag:src size:CGSizeMake(1, 1) scale:1 resizeMode:UIViewContentModeCenter progressBlock:^(int64_t progress, int64_t total) {} completionBlock:^(NSError *error, UIImage *image) {
        if(error != nil) {
          completeBlock(@[error.localizedDescription]);
        } else {
          completeBlock(@[[NSNull null],@{
                            @"width": @(image.size.width),
                            @"height": @(image.size.height)
                            }]);
        }
      }];
    }
    @end

**Comment by nicklockwood** [comment]
Yeah, this is the right approach. I'm intending to add something similar to RCTImageLoader.

**Comment by meznaric** [comment]
@nicklockwood Thanks for confirming :) !

**Comment by ms88privat** [comment]
After I upgraded from 0.15.0 to 0.17.0, I had to change the `resizeMode constant` from `UIViewContentModeCenter` to `UIViewContentModeScaleAspectFill` to get it working again.

This should be the same, right?

@meznaric
