### ISSUE TITLE
dispatch_queue_t DISPATCH_QUEUE_SERIAL in react native ios project objective-C not working

### ISSUE THREAD

**Issue by rajendrabhole** [facebook/react-native#41031]
### Description

I want to call a delegate method of class `AVCaptureMetadataOutput`. Implementation as below, 

    //Protocol inheritance
      @interface QRScannerVC : UIViewController<AVCaptureMetadataOutputObjectsDelegate>{

    //Code of delegate assignment of AVCaptureMetadataOutput
    capturedMetadataOutput = [[AVCaptureMetadataOutput alloc] init];
    [_captureSession addOutput:capturedMetadataOutput];
    capturedMetadataOutput.metadataObjectTypes = @[AVMetadataObjectTypeQRCode];
    dispatch_queue_t dispatchQueue = dispatch_queue_create("qrQueue", DISPATCH_QUEUE_SERIAL);
    //Delegate method assignment
    [capturedMetadataOutput setMetadataObjectsDelegate:self queue:dispatchQueue];

    Delegate method,
    - (void)captureOutput:(AVCaptureOutput *)output didOutputMetadataObjects:(NSArray<__kindof AVMetadataObject *> *)metadataObjects fromConnection:(AVCaptureConnection *)connection {
    
        if (metadataObjects != nil && metadataObjects.count > 0) {
            
            AVMetadataMachineReadableCodeObject *metadataObject = [metadataObjects objectAtIndex:0];
            
            if ([[metadataObject type] isEqualToString:AVMetadataObjectTypeQRCode]) {
                
                [_labelStatus performSelectorOnMainThread:@selector(setText:) withObject:[metadataObject stringValue] waitUntilDone:NO];
                
                [self performSelectorOnMainThread:@selector(stopReading) withObject:nil waitUntilDone:NO];
                _isReading = NO;
            }
        }
As per [apple documentation][1] `capturedMetadataOutput:setMetadataObjectsDelegate:queue` method must be call on the serial queue for continuous streaming. And as per [react native documentation][2] we can invoke our method if operation take long time to complete.

  [1]: https://developer.apple.com/documentation/avfoundation/avcapturemetadataoutput/1616309-setmetadataobjectsdelegate?language=objc
  [2]: https://reactnative.dev/docs/native-modules-ios.html#threading

But in my case `capturedMetadataOutput:setMetadataObjectsDelegate:queue` method not calling. If i use same code in pure iOS native Objective-C project then it will works good. 
Doesn't get what is is an issue in React native.

Mac os version - Ventura 13.5, Apple M2
XCode version - 14.3.1

### React Native Version

0.72.6

### Output of `npx react-native info`

    - (void)captureOutput:(AVCaptureOutput *)output didOutputMetadataObjects:(NSArray<__kindof AVMetadataObject *> *)metadataObjects fromConnection:(AVCaptureConnection *)connection {
 
method not calling after the camera launch and QR code scanning.

### Steps to reproduce

1. Create a react library using https://github.com/callstack/react-native-builder-bob (Turbo and Fabric both I tried.)
2. Add AVFoundation camera functionality in the iOS code given in the query.
3. Configure the above lib in your react native code or in the example given when created by RN bob builder.
4. Run code on iOS device 
5. After camera lunch try to scan QR code image.

### Snack, screenshot, or link to a repository

There is only live camera view.

**Comment by pe1ros** [comment]
@rajendrabhole 
Hi
try to use somethink like that

you native module 

- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}

....... setMetadataObjectsDelegate: (NSOperationQueue *)[NSOperationQueue currentQueue] ......

**Comment by DanielFrTB** [comment]
@cortinico 

There is any update?
Is there any option to interact with the UI thread from Turbo modules (new architecture)?
https://reactnative.dev/docs/native-modules-ios#threading

**Comment by rajendrabhole** [comment]
@DanielFrTB, I got the solution. Actually, we need to understand deep level of working of React Native with native, in other words understanding of architecture and data structure.  Read selected para from below image,
<img width="1158" alt="Screenshot 2024-06-20 at 5 09 57 PM" src="https://github.com/facebook/react-native/assets/198213/a39b9d69-0775-45bb-b9b8-810cc4b871eb">

So in my case `AVCaptureSession`,  `AVCaptureMetadataOutput`, `AVCaptureMetadataOutputDelegate` are running separate queue's. Of course, your code running without crashing but delegates doesn't call because for seperate queue allocation. So all code stuff come under single queue, when your camera detected any QR code then delegate method should call inside same queue where your camera session was executed.
