### ISSUE TITLE
[Android] Can't figure out how to open dev menu in emulator

### ISSUE THREAD

**Issue by rreusser** [facebook/react-native#4105]
The iOS experience has been great, but now I'm trying to get started with Android. I've been trying for an hour to read docs, learn my way around, and figure out how to open up the dev menu in the default emulator (not genymotion). Apparently there's no shake emulation and I'm unable to find any obvious button that triggers this. I'm using a brand new init'd project with RN 0.14.2.

<img width="341" alt="screen shot 2015-11-12 at 5 02 07 pm" src="https://cloud.githubusercontent.com/assets/572717/11133005/465a3efe-8961-11e5-91b9-b4fc7ed44aa4.png">

<img width="415" alt="screen shot 2015-11-12 at 5 00 27 pm" src="https://cloud.githubusercontent.com/assets/572717/11132970/1aa27880-8961-11e5-9ecf-97fd9275da28.png">

**Comment by rreusser** [comment]
One potential answer: just drop a few bucks and pay for Genymotion. Took like five minutes and ⌘-M works just fine.

**Comment by rreusser** [comment]
Yeah, Genymotion appears dramatically more stable, functional and likely to result in a workable dev workflow. Phew. I was rather worried for a bit there.

I'm content at the moment, but perhaps in addition to genymotion being 'much easier', the docs should point out that the stock emulator can be unstable and (do correct me if I'm wrong!) may have some particular trick for opening the dev menu.

**Comment by ide** [comment]
You can get a free version of Genymotion, just with some features locked. That said all the Android devs I've talked to say they develop on a device because the simulators aren't that good. If you're serious about Android development you might want to get one of the brand new Nexus 5X phones that look quite nice and are < $400 unlocked.

**Comment by atom992** [comment]
you can run: 
```
android avd
```
by Term, and go to [Device Definitions] , click the "Nexus 5" you used, and change Buttons from **software** to **Hardware**. 
then you can use the menu button.

**Comment by rreusser** [comment]
Hmm… I pasted the screenshot above. I don't see the Buttons option beyond 'Skin with dynamic hardware controls' which didn't end up usable anyway.

**Comment by atom992** [comment]
It's under **Device Definitions**, not **Android Virtual Devices**.

**Comment by rreusser** [comment]
Got it. Sorry. It didn't dawn on me that those might be anything but presets for the AVD tab.

I opened this so there'd be a google hit that explains what to do when people get stuck right away, but unless a more ominous word of warning is necessary [in the docs](https://facebook.github.io/react-native/docs/android-setup.html#install-genymotion) (i.e. that getting the stock emulator running is only the beginning of the challenges), I'm content to close it.

**Comment by ide** [comment]
The docs mention you can try hitting F2 with the stock simulator as well. If that works I think we're pretty well-covered. I'll close this out for now.

**Comment by lsadehaan** [comment]
On linux I had to hit Cntrl-F2 to get it working.

**Comment by ddresch** [comment]
On Mac it's `CMD + m` just for reference.

**Comment by adamski** [comment]
I'm having a lot of trouble getting Cmd+M working again, on OS X. Tried installing Genymotion too. Same deal. No response from Menu button or Cmd+M.

**Comment by stonecold123** [comment]
Cntrl-m isn't working on linux

**Comment by thg303** [comment]
@stonecold123 I think it might be a window manager issue, see here is how I do it in xfce (xubuntu):
1. select the Emulator window
2. open an irrelevant window (like calculator or anything else)
3. I close the irrelevant window (the calculator)
4. the emulator window got the focus (title bar highlights)
5. then I press `ctrl-m` and boom! it shows up

hope this helps, I would appreciate any simpler solution ;-)

**Comment by GabrielBB** [comment]
CTRL + M works for me on Windows 8

**Comment by sagar-chandani** [comment]
@stonecold123 you will have to edit in emulator settings as follows : 

1. Press 3 dots on emulator extended controls.
2. Go to Settings in there.
3. Set "Send keyboard shortcuts to : Emulator controls (default).


It worked for me that way.
Hope it helps.

**Comment by wajih123** [comment]
for windows 10 you need to press Ctrl+M and it shows the menu
