### ISSUE TITLE
The min_ios_version_supported is 12.4 and not 13.4 in a new project

### ISSUE THREAD

**Issue by eduardo-santos-tribia** [facebook/react-native#41053]
### Description

[This PR](https://github.com/facebook/react-native/pull/39474) added a new `Helpers` module to `packages/react-native/scripts/cocoapods/helpers.rb` with the `min_ios_version_supported` (used in `Podfile`) returning the value 13.4, but for some reason this value is still 12.4 when creating a new react-native project from scratch or updating react-native to a new version in an existing project.

Am I missing something or this value should be 13.4? I'm using a third party library that requires the minimum iOS target version of 13.0, so I was trying to understand better this "min_ios_version_supported" concept added to react-native. 

From my understanding, I should not remove the `min_ios_version_supported` attribute from Podfile and add the minimum version there explicitly, because react-native already is setting the correct version 13.4 (for my case).

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Max
  Memory: 11.56 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.0
    path: /var/folders/93/dcrjcbf93wq3v4tn6vtfbck40000gn/T/yarn--1697626741264-0.8327458535384211/node
  Yarn:
    version: 1.22.19
    path: /var/folders/93/dcrjcbf93wq3v4tn6vtfbck40000gn/T/yarn--1697626741264-0.8327458535384211/yarn
  npm:
    version: 9.3.1
    path: ~/.nvm/versions/node/v18.14.0/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/my-user/.rvm/rubies/ruby-2.7.8/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: Not found

### Steps to reproduce

1. Start a new project with `npx react-native@latest init AwesomeProject`.
2. Open the `node_modules/react-native/scripts/cocoapods/helpers.rb` file.
3. The return value of `self.min_ios_version_supported` will be 12.4 instead of 13.4.
4. You can also print the value of `min_ios_version_supported` in your Podfile to check.

### Snack, screenshot, or link to a repository

<img width="1208" alt="image" src="https://github.com/facebook/react-native/assets/113356915/79290408-3cd5-4b73-81d6-74c40a04875b">

**Comment by cipolleschi** [comment]
The commit you mentioned has been picked only for 0.73.0. The min iOS version for 0.72 is still 12.4 and it is correct to stay that way. The change to be on 13.4 will be forced by 0.73.
