### ISSUE TITLE
IOS Build is Successful but crashes on react native 72

### ISSUE THREAD

**Issue by dotsinspace** [facebook/react-native#41068]
### Description

I am experiencing weird issue in my react-native setup everything works fine during build but when app launches it crashes. right now i am using simulator iphone 15. Please suggest me solution over here.

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 186.39 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.0.0
    path: ~/.nvm/versions/node/v18.0.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.6.0
    path: ~/.nvm/versions/node/v18.0.0/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.72.2
    wanted: 0.72.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Dont know it just appeard in ios side. 

### Snack, screenshot, or link to a repository

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: D1DE1DA0-2B69-448A-8AEB-6451BA8166EF
CrashReporter Key:   4B5E0B4F-E813-D4E3-CA9A-118E1CEC6880
Hardware Model:      MacBookPro18,1
Process:             app [97711]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/639C9C8C-1E7B-47E4-B0D7-36984F23E65F/data/Containers/Bundle/Application/DA062C50-A990-4B80-A5B6-3132CCBB5CB3/app.app/app
Identifier:          com.app.startupnews
Version:             1.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [55855]
Coalition:           com.apple.CoreSimulator.SimDevice.639C9C8C-1E7B-47E4-B0D7-36984F23E65F [16176]
Responsible Process: SimulatorTrampoline [3738]

Date/Time:           2023-10-18 22:50:27.5426 +0530
Launch Time:         2023-10-18 22:50:20.0979 +0530
OS Version:          macOS 14.0 (23A344)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: app [97711]

Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	       0x1124c527d __exceptionPreprocess + 226
1   libobjc.A.dylib               	       0x10db84894 objc_exception_throw + 48
2   app                           	       0x102a405c0 RCTFormatError + 0 (RCTAssert.m:167)
3   app                           	       0x102a564a5 __28-[RCTCxxBridge handleError:]_block_invoke + 577
4   libdispatch.dylib             	       0x1117d5a90 _dispatch_call_block_and_release + 12
5   libdispatch.dylib             	       0x1117d6d3a _dispatch_client_callout + 8
6   libdispatch.dylib             	       0x1117e5ac0 _dispatch_main_queue_drain + 1420
7   libdispatch.dylib             	       0x1117e5526 _dispatch_main_queue_callback_4CF + 31
8   CoreFoundation                	       0x112421850 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
9   CoreFoundation                	       0x11241c18b __CFRunLoopRun + 2463
10  CoreFoundation                	       0x11241b409 CFRunLoopRunSpecific + 557
11  GraphicsServices              	       0x11d29b187 GSEventRunModal + 137
12  UIKitCore                     	       0x13bf3c3a2 -[UIApplication _run] + 972
13  UIKitCore                     	       0x13bf40e10 UIApplicationMain + 123
14  app                           	       0x10292037e main + 80 (main.m:6)
15  dyld_sim                      	       0x10c6303ee start_sim + 10
16  dyld                          	       0x2044593a6 start + 1942

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	       0x1041a2a78 ???
1   <translation info unavailable>	       0x105768bcc ???
2   libsystem_pthread.dylib       	       0x115d89f30 pthread_kill + 262
3   libsystem_c.dylib             	       0x113dc4d60 abort + 133
4   libc++abi.dylib               	       0x10ccca1b2 abort_message + 241
5   libc++abi.dylib               	       0x10ccbc38a demangling_terminate_handler() + 266
6   libobjc.A.dylib               	       0x10db635e6 _objc_terminate() + 96
7   libc++abi.dylib               	       0x10ccc960b std::__terminate(void (*)()) + 6
8   libc++abi.dylib               	       0x10ccc95c6 std::terminate() + 54
9   libdispatch.dylib             	       0x1117d6d4e _dispatch_client_callout + 28
10  libdispatch.dylib             	       0x1117e5ac0 _dispatch_main_queue_drain + 1420
11  libdispatch.dylib             	       0x1117e5526 _dispatch_main_queue_callback_4CF + 31
12  CoreFoundation                	       0x112421850 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
13  CoreFoundation                	       0x11241c18b __CFRunLoopRun + 2463
14  CoreFoundation                	       0x11241b409 CFRunLoopRunSpecific + 557
15  GraphicsServices              	       0x11d29b187 GSEventRunModal + 137
16  UIKitCore                     	       0x13bf3c3a2 -[UIApplication _run] + 972
17  UIKitCore                     	       0x13bf40e10 UIApplicationMain + 123
18  app                           	       0x10292037e main + 80 (main.m:6)
19  dyld_sim                      	       0x10c6303ee start_sim + 10
20  dyld                          	       0x2044593a6 start + 1942

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffc322b4 ???

Thread 2:
0   ???                           	    0x7ff7ffc5094c ???

Thread 3:
0   ???                           	    0x7ff7ffc5094c ???

Thread 4:
0   ???                           	    0x7ff7ffc5094c ???

Thread 5:
0   ???                           	    0x7ff7ffc5094c ???

Thread 6:: com.apple.uikit.eventfetch-thread
0   ???                           	       0x1041a2a78 ???
1   <translation info unavailable>	       0x104281f34 ???
2   libsystem_kernel.dylib        	       0x115c51e4a mach_msg2_internal + 84
3   libsystem_kernel.dylib        	       0x115c4ab6e mach_msg_overwrite + 653
4   libsystem_kernel.dylib        	       0x115c43d1f mach_msg + 19
5   CoreFoundation                	       0x1124215bf __CFRunLoopServiceMachPort + 143
6   CoreFoundation                	       0x11241bd47 __CFRunLoopRun + 1371
7   CoreFoundation                	       0x11241b409 CFRunLoopRunSpecific + 557
8   Foundation                    	       0x116769eee -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
9   Foundation                    	       0x11676a16c -[NSRunLoop(NSRunLoop) runUntilDate:] + 72
10  UIKitCore                     	       0x13c014797 -[UIEventFetcher threadMain] + 518
11  Foundation                    	       0x116794699 __NSThread__start__ + 1024
12  libsystem_pthread.dylib       	       0x115d8a202 _pthread_start + 99
13  libsystem_pthread.dylib       	       0x115d85bab thread_start + 15

Thread 7:
0   ???                           	    0x7ff7ffc5094c ???

Thread 8:
0   ???                           	    0x7ff7ffc5094c ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000113dd13c0  rsi: 0x00000002044ff240  rbp: 0x000000030ae6ece0  rsp: 0x000000030ae6ea80
   r8: 0x000000030ae6ebf8   r9: 0x000000030ae6ece0  r10: 0x0000000000000000  r11: 0x000000010cccd67d
  r12: 0x0000000000000103  r13: 0x0000003000000008  r14: 0x00000002044ff240  r15: 0x0000000000000016
  rip: <unavailable>       rfl: 0x0000000000000287
 tmp0: 0xffffffffffffffff tmp1: 0x00000001041a2a4c tmp2: 0x000000010cfba9b0

**Comment by cortinico** [comment]
Not enough information to debug this, we can't just fix it by looking at a stacktrace.
Please provide a reproducer and we'll look into it.

**Comment by doneill** [comment]
This looks to be related to #39635, I think would be difficult to reproduce outside of the app that is failing.  We are seeing both issues on start of an app from testflight that builds and runs on device
