### ISSUE TITLE
Snackbar for android

### ISSUE THREAD

**Issue by pedro** [facebook/react-native#4106]
Hi folks,

I created a Snackbar component for Android apps:
https://github.com/luggg/react-native-android-snackbar

Is this something you'd be interested in bringing in, or is the plan to leave these as 3rd party components? If the plan is to incorporate these I'll happily work on a pull.

Thanks,

**Comment by bozzmob** [comment]
This looks amazing! Was this committed?

**Comment by ide** [comment]
When there's a clear separation between a component and the code in this repo it's generally better to maintain separate repos for several reasons. When code lands in the main RN repo the responsibility and cost of maintaining it shifts to the core developers and can be very expensive. One thing that changes the calculus is if the core developers (primarily FB) have a need for the feature and are improving the API and learning about bugs and are incentivized to maintain it. Also sometimes code best belongs in core, like changes to the gesture system or the native bridge. Generally though, separate repos keep lines of ownership clearer, and are more scalable for the RN ecosystem.

**Comment by pedro** [comment]
Sounds reasonable to me! Thanks, closing this one then.

**Comment by pedro** [comment]
Ah, to extend a bit on @ide's point: this is all going to come together when we have a better way to browse and plug 3rd party React Native components into our apps.

I've seen a few discussions here and there on both fronts, but let me know if there's a particular thread/issue I can follow to get more info or hopefully contribute to either. In particular thinking about ways to avoid the [manual setup](https://github.com/luggg/react-native-android-snackbar#setup), and some sort of catalogue of components built on top of [npm's](https://www.npmjs.com/).
