### ISSUE TITLE
[Packager] Loading images does not work if the filenames inside of the imageset do not match the containing imageset

### ISSUE THREAD

**Issue by chedabob** [facebook/react-native#411]
If after importing images into Xcode you rename the imageset, the packager generates the wrong module code and it cannot load the image. See the screenshot below where the imageset has been renamed to 'test' but the initial filename that generated it was 'tab_account.png'

![react-native-package-issue](https://cloud.githubusercontent.com/assets/168025/6882644/83597d24-d584-11e4-8413-ea73f3a72b8a.png)

Using the imageset's name as follows:

    <TabBarIOS.Item
        [...]
        icon={require('image!test')}>
    </TabBarIOS.Item>

Results in "Requiring unknown module "image!test"" inside the simulator

Using the actual filename:

    <TabBarIOS.Item
        [...]
        icon={require('image!tab_account')}>
    </TabBarIOS.Item>

Results in "The tab bar icon 'tab_account' did not match any known image or system icon"

This is quite an edge case as by default the imageset matches the filenames of the imported assets, but this scenario is valid in a standard iOS project.

**Comment by ide** [comment]
You need to keep the imageset and the real filenames in sync; see #365. Perhaps write a small tool and share it on GitHub?

**Comment by christopherdro** [comment]
Duplicate #365
