### ISSUE TITLE
Refresh ListView with complex data

### ISSUE THREAD

**Issue by JeanLebrument** [facebook/react-native#4113]
Hello,

I encountered a problem with the refreshing of a ListView when data from the dataSource are updated.

Hopefully, somebody found a workaround on SO: http://stackoverflow.com/questions/33436902/how-force-redraw-listview-when-this-state-changed-but-not-the-datasource

However, this fix isn't clean and can be heavy at runtime. I would like to know if there is a better way to handle this kind of problem?

Best,
Jean

**Comment by ide** [comment]
That answer is correct. For ListView to be efficient it needs to do equality quickly, and immutability is a good way to allow for quick equality checks.
