### ISSUE TITLE
Unable to access an element via it's ref

### ISSUE THREAD

**Issue by CorpusCallosum** [facebook/react-native#4114]
Having a very strange issue... I have several components laid out in my app. One of my custom components called ProgressBar is accessed via a ref to tell it to update. This works fine when I have the component at the top of by View hierarchy, but if I move the component down to the bottom of the stack, I get the error:
>undefined is not an object (evaluating 'this.refs.progressBar.updateProgressBarWidth')

Here is the view being rendered, this works fine when the ProgressBar is above the CardList, but when I move the ProgressBar to below the CardList, I get the error mentioned above.
``` jsx
    <View style={this.getViewContainerStyle()}>
        <Animated.View style={{top:this.state.cardListYPos, left:this.state.cardListXPos}}>
	        <ProgressBar ref='progressBar'/>
            <CardList
	        onCardScrollCallback = {this.onCardScrollCallback.bind(this)}
		    ref='cardList' />
        </Animated.View>
    </View>
```

Here is the method that throws the error, this is called as a callback from the CardList:

```jsx
onCardScrollCallback(index){
    this.refs.progressBar.updateProgressBarWidth(index);
}
```
Why would simply reordering a component in a View hierarchy make it no longer accessible via it's ref? Could it be that callback from the CardList gets called before the ProgressBar is rendered? That does not make sense to me, but perhaps I have some misunderstanding about the underlying architecture of React. Thanks.

**Comment by jjshammas** [comment]
String refs are very strange. I've found much better results by passing a function to the ref object as such:

```html
<ProgressBar ref={(element) => this.progressBar = element} />
```

```javascript
if (this.progressBar)
   this.progressBar.updateProgressBarWidth(index)
```

**Comment by CorpusCallosum** [comment]
Thanks for your suggestion, I tried that but I'm having the same issue. Works above the CardList component, does not work below it.

**Comment by mikearmstrong001** [comment]
I've been able to reliably use refs after the component is mounted, for example componentDidMount. Is your callback get called before this point in the component life cycle?

**Comment by brentvatne** [comment]
@CorpusCallosum - are you setting a ref internally on the ProgressBar component? Make sure that if you do that you also use a callback ref like @jjshammas mentioned above.

This isn't a bug although it would be nice to be documented more thoroughly. Refs overall can be pretty confusing beyond the simple case of adding it to a built-in component. Eg: if you use a decorator, you won't be able to call some function on it, using callback refs vs named refs, cloning components with refs. cc @sebmarkbage 

That said, we don't have bandwidth here to deal with issues that aren't bugs so can you please repost this to StackOverflow?

**Comment by sebmarkbage** [comment]
We're in the process of updating all docs to strongly prefer "callback refs", and maybe even remove docs for string refs at some point since they're getting deprecated anyway.

It is likely that `onCardScrollCallback` is getting called in `componentWillMount`, `componentWillReceiveProps` or `componentWillUpdate`. It is an anti-pattern to have callbacks firing in any of these life-cycles since they happen in the middle of the rendering. Try moving them to `componentDidMount` or `componentDidUpdate`.

As mentioned above, this is better suited as a StackOverflow question until you can find a small reproducible example. I.e. the exact bug. However, in this case I don't think there is a bug.
