### ISSUE TITLE
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by liuyunqiang** [facebook/react-native#41141]
### Description

Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### React Native Version

0.64.2

### Output of `npx react-native info`

System:
    OS: macOS 14.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 949.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

<img width="849" alt="截屏2023-10-22 04 09 14" src="https://github.com/facebook/react-native/assets/17231906/04f7bc04-9f6f-4699-972d-dbc9aa5c0d07">

### Snack, screenshot, or link to a repository

<img width="849" alt="截屏2023-10-22 04 09 14" src="https://github.com/facebook/react-native/assets/17231906/51b2b9a4-a2a6-45c0-9b3e-161f6e260030">

**Comment by RikSchefferOberon** [comment]
You should try to run it with the Environment variable NO_FLIPPER=1
And you should add this to the react-native.config.js:
`  dependencies: {
    ...(process.env.NO_FLIPPER
      ? {'react-native-flipper': {platforms: {ios: null}}}
      : {}),
  },`

**Comment by solitarysp** [comment]
I also have the error, can anyone help me :((

**Comment by keremoge** [comment]
Same problem here with Xcode 15.2 and RN 0.72.12

**Comment by vadimt2** [comment]
Same here

**Comment by chgouthamraj** [comment]
same here

**Comment by mahmoudshaeerhomzmart** [comment]
+1

**Comment by IseeUDenis** [comment]
same here

**Comment by duongnguyen17** [comment]
+1

**Comment by ashcode1** [comment]
+1

**Comment by mikpalm** [comment]
For me the error on CoreAudioType was a bogus one i was trying to add a library.a file and Xcode 15 uses by default the new linker. so adding -ld_classic to Other linker flags solved everything. Just putting it out there if anyone have the same issues.
