### ISSUE TITLE
TouchableNativeFeedback not working on android

### ISSUE THREAD

**Issue by Pungsnigel** [facebook/react-native#4115]
Having trouble using TouchableNativeFeedback on android devices. Even when just running react-native init, and adding only a TouchableNativeFeedback, I get the following error: "Trying to add unkown view tag: 13..."

Minimal project where this error occurs: https://github.com/Pungsnigel/react-native-broken-example

I'm running react-native 0.14.2, and using a OnePlus One with Android 5.1.1

**Comment by satya164** [comment]
I guess you need to wrap your `Text` component in a `View`.

**Comment by Pungsnigel** [comment]
@satya164 Can't believe it was that simple... Working now, thanks a bunch!
