### ISSUE TITLE
throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [facebook/react-native#41150]
### Description

Error: yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/Users/minhnguyen/_f/_f/_f/node_modules/yargs-parser/build/index.cjs:1015:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/minhnguyen/_f/_f/_f/node_modules/yargs/build/index.cjs:1:60570)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Command PhaseScriptExecution failed with a nonzero exit code

![Screenshot 2023-10-23 at 16 38 46](https://github.com/facebook/react-native/assets/30792140/5690592d-1b22-4736-8a83-fd17aec04632)

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 13.3.1
  CPU: (8) arm64 Apple M1
  Memory: 152.25 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: /opt/homebrew/opt/node@16/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.4
    path: /opt/homebrew/opt/node@16/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/minhnguyen/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
  
 ---------------
  
`  nvm ls`
       v10.24.1
      v12.22.12
       v14.16.0
       v16.17.1
       v16.18.0
->       system
default -> v16.18.0
node -> stable (-> v16.18.0) (default)
stable -> 16.18 (-> v16.18.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/hydrogen (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1
lts/erbium -> v12.22.12
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.18.2 (-> N/A)

### Steps to reproduce

npx react-native init newProject --version 0.72.3

cd ios && pod install

open newProject.xcworkspace

build

### Snack, screenshot, or link to a repository

Create a new project with version 0.72.3 and getting error build project by xcode.

**Comment by cortinico** [comment]
```
  nvm ls
v10.24.1
v12.22.12
v14.16.0
```

Could you try to uninstall all the node versions < 16 and try again?

**Comment by NguyenHoangMinhkkkk** [comment]
Hi, after remove many node version in nvm. the result below. 
i tried to run project again by xcode -> build failed with the same error
> ps: build app success with cmd "npx react-native run-ios"

btw, Removing nvm node versions seem not a good solution, cause i need these version for other works.

`nvm ls`
-----
->     v16.18.0
         system
default -> v16.18.0
node -> stable (-> v16.18.0) (default)
stable -> 16.18 (-> v16.18.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/hydrogen (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)

`node -v`
-----
v16.18.0

`npm version`
-----
{
  documentx: '0.0.1',
  npm: '8.19.2',
  node: '16.18.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.10',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022b',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'
}

`which node`
-----
/Users/minhnguyen/.nvm/versions/node/v16.18.0/bin/node

**Comment by cortinico** [comment]
I'm unsure what is happening in your environment, you should seek further support on StackOverflow or other forums.

We use this issue tracker only for bug reports.

In order to use RN 0.72, you need to have node >= 16 installed.
The problem you're seeing is because the environment you're executing is probably not using Node >= 16

**Comment by NguyenHoangMinhkkkk** [comment]
i found a solution from https://github.com/facebook/react-native/issues/35657#issuecomment-1636136312

** add 2 lines below into ios/.xcode.env

> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
