### ISSUE TITLE
Can't upgrade to 0.14.2 (from 0.13): Error building DepdendencyGraph ... RCTTest/SnapshotView

### ISSUE THREAD

**Issue by gpbl** [facebook/react-native#4117]
I've installed 0.14.2 (from 0.13), but when I run the iOS app now I get this error:

```
Error building DepdendencyGraph:
 Error: ENOENT: no such file or directory, open '/node_modules/react-native/Libraries/RCTTest/SnapshotView.js'
``` 

How do I know what is requiring that file?

**Comment by 6i6arka** [comment]
+1

**Comment by gpbl** [comment]
@6i6arka could you try if following http://facebook.github.io/react-native/docs/upgrading.html#from-0-13-to-0-14 solves your problem?

**Comment by 6i6arka** [comment]
@gbpl I am having the same issue, but for Android. The docs seem to handle iOS only?

**Comment by gpbl** [comment]
I have no idea for Android. On iOS, I worked around this problem by creating a new project from the CLI and copying on it all my sources :-1: 
However I suspect the issue comes out if you don't delete first the old main.jsbundle, because there was the only place where I could find a require of `SnapshotView`

**Comment by tylermcginnis** [comment]
I'm running into the same issue.

**Comment by satya164** [comment]
Closing as it was for an old version and is likely fixed. If you're still facing the issue, let's reopen.
