### ISSUE TITLE
TextInput rendered value clears when the `value` type changes from `number` to `string`

### ISSUE THREAD

**Issue by houkanshan** [facebook/react-native#41189]
### Description

The value rendered in a TextInput will be cleared when the `typeof value` changes from `number` to `string`.

Despite the [the document specifies the value type as `string`](https://reactnative.dev/docs/textinput#value), `number` is allowed and is converted to a string in the `onTextChange` & `onChange` callbacks. So it's unexpected when the rendered value is cleared.

I think it would be nice to fix this issue so it aligns with behavior on web browsers. Alternatively, if the type must strictly be `string`, it would be beneficial to tell developers through a console warning if the value is not a `string`.

Can reproduce it on both iOS and Android. react-native-web is not affected.

### React Native Version

0.72.6

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 12.6.6
  CPU: (8) arm64 Apple M1 Pro
  Memory: 111.36 MB / 16.00 GB
  Shell:
    version: 3.6.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 20.2.0
    path: ~/.local/share/nvm/v20.2.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.local/share/nvm/v20.2.0/bin/yarn
  npm:
    version: 9.6.6
    path: ~/.local/share/nvm/v20.2.0/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: ^0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

```jsx
import { SafeAreaView, TextInput, Text } from 'react-native';
import { useState } from 'react';

export default function App() {
  const [value, setValue] = useState('');
  return (
    <SafeAreaView style={{ padding: 40 }}>
      <Text>Type `111.111`</Text>
      <TextInput
        value={value}
        inputMode="decimal"
        onChangeText={(v) => {
          if (v.endsWith('.')) setValue(v);
          else {
            const num = parseFloat(v);
            setValue(num);
          }
        }}
        style={{ borderWidth: 1, borderColor: 'black' }}
      />
      <Text>`{value}` is {typeof value}</Text>
    </SafeAreaView>
  );
}
```

1. Type `111` in the input, `value` is `number`
2. Type `.`, `value = '111.'` is `string`
3. Type `1`, `value = `111.1` is `number`. But the input is cleared.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@mhou-tw/textinput-value-type-change-from-number-to-string

https://github.com/facebook/react-native/assets/657962/536816f4-7752-4725-95cb-e19f47fe6843

**Comment by houkanshan** [comment]
Hey thanks, I upgraded react-native and it's still reproducible.

**Comment by jakex7** [comment]
Hi @houkanshan
I don't think this is the actual problem. The documentation clearly states that the value must be a string, and it is obvious that passing something else will result in unpredictable behavior. However, if someone from Core Contributors confirms that there should be a warning, I'd be happy to do a PR with it.

**Comment by fabriziobertoglio1987** [comment]
Hello,

Thanks for the issue. I have been contributing to facebook/react-native for 4 years and specialize in the Text/TextInput components. I currently have 58 facebook/react-native PRs:

https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+ 

It is the suggested approach from the react-native core team (see this [discussion](https://github.com/react-native-community/discussions-and-proposals/discussions/731#discussioncomment-7651145)).

I'm publishing several fixes for Text and TextInput component in a separate library [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved). 

- The Component is based on ReactTextView, it is the same implementation from react-native.
- It will include several bug fixes. 
- You can use the library until the PR is merged and released with react-native. 
- You can use side by side both components from react-native and react-native-improved, depending on where you need the fix.
- I will also publish the PR to facebook/react-native (daily fixes and releases).

The advantages would be:
- Increased engagement with the community, issues are quickly fixed.
- No limitations when merging PRs (react-native main branch is used on facebook marketplace).
- Only Meta employees can merge and review facebook/react-native PRs.
- Allows us to further experiment and develop react-native.

Do you want me to publish for you a patched release? I'm working on a list of priorities. Thanks
