### ISSUE TITLE
Upgrade React Native to version 0.72.0

### ISSUE THREAD

**Issue by CFPanda** [facebook/react-native#41184]
### Description

I want to upgrade React Native to version 0.72.0, and I would like to know how Native sends a message to JavaScript in the new version。Originally implemented using RCTBridge, now the bridge uses a new TurboModule. How to achieve native to JavaScript communication using the new bridge.

### React Native Version

0.72.0

### Output of `npx react-native info`

nothing

### Steps to reproduce

nothing

### Snack, screenshot, or link to a repository

nothing

**Comment by cortinico** [comment]
You can find documentation on Turbo Native Modules here:
https://reactnative.dev/docs/0.71/the-new-architecture/pillars-turbomodules
