### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

### ISSUE THREAD

**Issue by mayurmudoi** [facebook/react-native#41193]
### Description

I have been facing this issue for quite a few days,  Earlier I was getting the same BUG with version 64. So, 

**Updated To**
_JAVA_: java version "21.0.1" 2023-10-17 LTS
_GRADLE_: Gradle 8.4
_NODE_: v20.9.0

Now facing this issue.

### React Native Version

0.72.6

### Output of `npx react-native info`

_**System:**_
    OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  Memory: 1.35 GB / 7.84 GB
_**Binaries:**_
  Node:
    version: 20.9.0
    path: D:\Tools\Node\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.0.0
    path: D:\Tools\Node\nodejs\npm.CMD
  Watchman: Not Found
_**SDKs:**_
  Android SDK: Not Found
  Windows SDK: Not Found
_**IDEs:**_
  Android Studio: AI-223.8836.35.2231.10671973
  Visual Studio:
    - 17.7.34031.279 (Visual Studio Community 2022)
_**Languages:**_
  Java: 21.0.1
  Ruby: Not Found
_**npmPackages:**_
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
_**npmGlobalPackages:**_
  "*react-native*": Not Found
_**Android:**_
  hermesEnabled: true
  newArchEnabled: false
_**iOS:**_
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Facing this issue after creating a new react-native-applications.

### Snack, screenshot, or link to a repository

![Screenshot (49)](https://github.com/facebook/react-native/assets/111069361/0ce3ee5b-c432-4bee-9ece-d2c098736629)

**Comment by cortinico** [comment]
> _JAVA_: java version "21.0.1" 2023-10-17 LTS

Java 21 is currently unsupported. The recommendation is to use JDK 11

**Comment by m1daz** [comment]
I need an explanation. 

Tried this
<img width="630" alt="image" src="https://github.com/facebook/react-native/assets/102895212/413dad5d-07c4-446d-ad14-702a6d85349b">
Tried this
<img width="749" alt="image" src="https://github.com/facebook/react-native/assets/102895212/0231f50d-d986-4f82-8021-909e7224a703">

Tried JDK 17, Java 8, JDK 21

> Could not open cp_proj generic class cache for build file '****' (/Users/administrator/.gradle/caches/8.0.1/scripts/1ygqc4rlllvkp18ic30fv7mb1).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

**Comment by andvalsol** [comment]
I'm having the same issue and I'm using `corretto-11`

**Comment by pyprince** [comment]
Me too. If someone resolved this issue, please let me know.

**Comment by shriya-begalileo** [comment]
I am using grade 8.3 and jdk version 20 which is compatible stilll facing same issue

**Comment by michaelemercer** [comment]
Hello, I don't know if this is the issue, but I'm having the same issue. But for me the directory is <HOME>/.gradle/caches/8.1.1.

Now I'm assuming 8.1.1 would be the gradle version??? I'm using 8.7 with java 21.

Could this be the issue?
