### ISSUE TITLE
Extremely poor performance when nesting FlatLists on certain versions of Android

### ISSUE THREAD

**Issue by MorganDavid** [facebook/react-native#41205]
### Description

On certain android devices (possibly related to android version, I'm able to repro on android 13), nesting of FlatLists (as shown in the snack) results in unusable FlatLists performance when using heavy components. these same components work fine when the FlatLists are NOT nested, but nesting them causes some android devices to suffer severe performance issues (<1fps JS thread when scrolling and lots of input lag). this probably isn't related to device hardware since it runs terribly on my Galaxy S21 (android 13) but better on my cheap old android phone (android 12).

### React Native Version

0.71.6

### Output of `npx react-native info`

    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 163.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.6 => 0.71.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

nest a flatlist inside the renderItem or ListHeaderComponent of another flatlist and render a lot of heavy components in the inner flatlist.

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@morgandavid/android-nested-flatlist-performance-issue-with-heavy-component

**Comment by cortinico** [comment]
Have you searched here if another similar issue already exists?
https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+nested+flatlist

**Comment by MorganDavid** [comment]
> Have you searched here if another similar issue already exists? https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+nested+flatlist

Hi, I can't find any perf issues related to nesting. General flatlist perf issues is the closest https://github.com/facebook/react-native/issues/13413

**Comment by MorganDavid** [comment]
attaching ADB reveals lots of exceptions along the lines of: 
```                                                                  
com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 34987 could not be found.
```
as well as (I think) large gc calls.
```
2023-10-30 11:55:06.387 23110-23120 rding.birda_dev         com.chirpbirding.birda_dev           I  Background concurrent copying GC freed 157849(23MB) AllocSpace objects, 11(724KB) LOS objects, 20% free, 93MB/117MB, paused 60us,78us total 138.638ms
```

adb logs: https://pastebin.com/ccu1EX2T

these only occur when scrolling.

**Comment by Crizzooo** [comment]
Bumping - We recently upgraded from ~62 to ~72 and have also observed some very weird behavior. 

Rather than experiencing such an FPS drop, we are seeing Android 13 devices just sometimes appear to "render null".

The elements dont appear to be drawn, yet element inspector can show their bounding boxes. And the "ghost elements" are clickable.

This is the weirdest bug Ive experienced in working with RN, and so far I think Ive been fixing it by just removing FlatLists completely. 

Anyone else experience anything like this - elements not being visible at all, despite taking up space and respecting click events?

**Comment by jeveloper** [comment]
Just curious @Crizzooo  Christopher if the issue for your specific item iterated is still problematic in RN 0.73

**Comment by Crizzooo** [comment]
@jeveloper We are on RN 72.5

Is it supposed to be fixed in 73 - should we upgrade ASAP?

**Comment by jeveloper** [comment]
@Crizzooo I would imagine Expo will release after the new year. Humans need a good healthy break :)
I definitely wouldn't mix 73 with 72 based expo. 
Honestly, i would invest in writing a custom flatlist with native java/kotlin code and make sure memory is released how you want it. I've been working with RN for 6 years and there is no universal solution yet. E.g. having small images in each item easily can create a headache. Smooth on ios.

**Comment by hsjoberg** [comment]
I suppose you could try FlashList, which is pretty much a drop-in for FlatList, and see if it yields a better experience.

**Comment by jeveloper** [comment]
Thanks for sharing that lib @hsjoberg

**Comment by hsjoberg** [comment]
Sure cheers @jeveloper. I will use it in production on my next version. It's really really fast in my experience (but don't get fooled by the debug build).
