### ISSUE TITLE
Error setting property 'secureTextEntry' of RCTTextField

### ISSUE THREAD

**Issue by ben-manes** [facebook/react-native#4120]
I'm not much of a mobile / front-end developer, so please bare with me.

We have a register / login form with a tab selector between the two forms. Previously both forms were just the login / password, but now we're requiring first and last name. This resulted in the failure `Error setting property 'secureTextEntry' of RCTTextField` for the password `TextInput` field(s) and the application crashes when switching tabs.

If one of the `password` inputs is not set as secure then it works properly. If a single `TextInput` field is added, then it works. It seems that if the tabs differ by an even number of fields then the crash occurs, but if odd then it works properly. I'm guessing there is some off-by-one error somewhere in the framework.

The workaround was to have an empty `TextInput` that is not rendered.

**Comment by wv1124** [comment]
{
    title: 'Passwords',
    render: function() {
      return (
        <TextInput
          defaultValue="iloveturtles"
          password={true}
          style={[styles.singleLine, {color: 'green'}]}
        />
      );
    }
  },

**Comment by browniefed** [comment]
Is this still happening?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
