### ISSUE TITLE
'react/bridging/LongLivedObject.h' file not found

### ISSUE THREAD

**Issue by ArtsiomAstrouski** [facebook/react-native#41203]
### Description

❌  /Users/mac/Library/Developer/Xcode/DerivedData/name-cyhmusmnrimlvbgabnbaiohwxlxj/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core/ReactCommon/LongLivedObject.h:11:10: 'react/bridging/LongLivedObject.h' file not found

### React Native Version

0.72.6

### Output of `npx react-native info`

-

### Steps to reproduce

-

### Snack, screenshot, or link to a repository

![Снимок экрана 2023-10-26 в 14 33 35](https://github.com/facebook/react-native/assets/86202029/8721c349-280e-4ce6-bca3-b0d21c7a930c)
![Снимок экрана 2023-10-26 в 14 33 16](https://github.com/facebook/react-native/assets/86202029/17e798eb-0c62-44c7-8236-f9dbd02b3807)

**Comment by cortinico** [comment]
Please fill in the issue template and provide a reproducer as this issue is currently invalid
