### ISSUE TITLE
Build App IOS ERROR

### ISSUE THREAD

**Issue by ngocchinh4984** [facebook/react-native#41229]
### Description

2 days ago when I built it it was normal, but now when I build it there is an error

Run fastlanne :
Generating debug ReliposSaleOrder » ReliposSaleOrder.app.dSYM

› Executing ReliposSaleOrder » Bundle React Native code and images

    the transform cache was reset.

❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/ReliposSaleOrder-ewdmlwntzptsgbdugffzlcepqjhl/Build/Intermediates.noindex/ArchiveIntermediates/ReliposSaleOrder/BuildProductsPath/Release-iphoneos/ReliposSaleOrder.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/ReliposSaleOrder-ewdmlwntzptsgbdugffzlcepqjhl/Build/Intermediates.noindex/ArchiveIntermediates/ReliposSaleOrder/IntermediateBuildFilesPath/ReliposSaleOrder.build/Release-iphoneos/ReliposSaleOrder.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'ReliposSaleOrder' from project 'ReliposSaleOrder')

▸ (1 failure)

** ARCHIVE FAILED **

The following build commands failed:

	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/ReliposSaleOrder-ewdmlwntzptsgbdugffzlcepqjhl/Build/Intermediates.noindex/ArchiveIntermediates/ReliposSaleOrder/IntermediateBuildFilesPath/ReliposSaleOrder.build/Release-iphoneos/ReliposSaleOrder.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'ReliposSaleOrder' from project 'ReliposSaleOrder')

(1 failure)

### React Native Version

0.70.14

### Output of `npx react-native info`

System:
    OS: macOS 12.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 39.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.8.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.14 => 0.70.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

eas build --platform ios

### Snack, screenshot, or link to a repository

Snack : https://snack.expo.dev/@phanmemhopnhat/e3c950

**Comment by ngocchinh4984** [comment]
Help me Pls

**Comment by mjubilee1** [comment]
Also seeing the same exact issue

**Comment by elobredor** [comment]
i have the same error too.

**Comment by titanve** [comment]
I am also trying to build in Expo and I'm getting the same error:
```
+ [[ ! -f /Users/expo/Library/Developer/Xcode/DerivedData/MyApp-dytmggbduaumbmbkuwfpwuxdshsg/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle ]]

+ echo 'error: File /Users/expo/Library/Developer/Xcode/DerivedData/MyApp-dytmggbduaumbmbkuwfpwuxdshsg/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'

error: File /Users/expo/Library/Developer/Xcode/DerivedData/MyApp-dytmggbduaumbmbkuwfpwuxdshsg/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/BuildProductsPath/Release-iphoneos/MyApp.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

+ exit 2
```

**Comment by MadJohnny** [comment]
Yes, am seeing the same after upgrading to 0.7.14

**Comment by Minh-ka** [comment]
same issue
<img width="1023" alt="Screenshot 2023-10-30 at 09 02 27" src="https://github.com/facebook/react-native/assets/102807556/6989dbd5-a3e8-4a01-a0d8-e9abd025af02">

**Comment by lamhtf** [comment]
same issue here and waiting for any suggestion or solution too

build successfully without issue until last friday

**Success case:**
2023-10-26T15:42:39.2133230Z [RUN_FASTLANE] › Executing ABC» Bundle React Native code and images
2023-10-26T15:42:40.2456460Z [RUN_FASTLANE]     the transform cache was reset.
2023-10-26T15:51:10.7752570Z [RUN_FASTLANE] › Executing ABC» [CP] Copy Pods Resources
2023-10-26T15:51:13.2351730Z [RUN_FASTLANE] › Executing ABC » [CP-User] [RNFB] Core 

**Fail case**
2023-10-27T09:01:32.5098180Z [RUN_FASTLANE] › Executing ABC» Bundle React Native code and images
2023-10-27T09:01:32.5496440Z [RUN_FASTLANE]     the transform cache was reset.
2023-10-27T09:05:18.7416620Z [RUN_FASTLANE] 
2023-10-27T09:05:18.7423060Z ❌  error: File /Users/runner/Library/Developer/Xcode/DerivedData/ABC-fqrtiynyduzjgvdyoccmjndnoggp/Build/Intermediates.noindex/ArchiveIntermediates/ABC/BuildProductsPath/Release-iphoneos/ABC.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

**Comment by Minh-ka** [comment]
this fixed it for me: https://docs.expo.dev/guides/using-hermes/#using-sdk-47-or-lower

**Comment by trayldev** [comment]
@Minh-ka This worked for me - thank you so much. We're getting ready to launch our product and I've been at a standstill for two days on this issue! Thank you! 👏

**Comment by akitoshi** [comment]
@Minh-ka Solved!! thank you 👏

**Comment by lamhtf** [comment]
@Minh-ka 
thanks, your method works like a charm

**Comment by zhiqingchen** [comment]
why

**Comment by firasrg** [comment]
@Minh-ka thank you for the suggestion. However, i'd like to know why doing this please

**Comment by cipolleschi** [comment]
If you are using Expo, please open an issue in [their repo](https://github.com/expo/expo), not in React Native one. They will be better equipped to answer your question.

**Comment by elobredor** [comment]
@Minh-ka I tried this but it didn't work, Do you know anything else I can try?
 
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 3.22 GB / 15.37 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: AI-222.4459.24.2221.9971841
    Visual Studio: Not Found
  Languages:
    Java: 20.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.14 => 0.70.14
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by brentvatne** [comment]
it looks like there was a regression in a patch release of react-native 0.70 between 0.70.9 and 0.70.14, so i rolled back the recommended version to 0.70.8 for SDK 47. that should resolve the issue.

the problem appears to be that on react-native 0.70.14, specifying the `hermes_enabled` property in the Podfile is insufficient, and it also looks for a `USE_HERMES` environment variable, and if that is not defined, then it assumes you are using hermes.

**Comment by firasrg** [comment]
hey @brentvatne! thanks for the investigation. Does that means that, if we retry building now, we no longer find issues? Or should we do an update to CLI or what exactly ?

**Comment by titanve** [comment]
I could built last night without issues.

**Comment by andreas-moneygate** [comment]
Managed to build today without changing anything.

**Comment by elobredor** [comment]
It is solved

**Comment by brentvatne** [comment]
@firasrg - correct, you can just run a new build. we reverted the recommend react-native version for sdk 47 from 0.70.14 to 0.70.8, so we no longer pull in the commit from react-native that caused this regression
