### ISSUE TITLE
[Android CI] Excluding `createBundleReleaseJsAndAssets` in gradle tasks no longer possible on 72.5

### ISSUE THREAD

**Issue by PaperbagWriter** [facebook/react-native#41224]
### New Version

0.72.5

### Old Version

0.71.8

### Build Target(s)

Android in Release/Debug flavors

### Output of `react-native info`

System:
  OS: macOS 13.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 3.57 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.18.0
    path: ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn:
    version: 1.22.15
    path: ~/.nvm/versions/node/v16.18.0/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v16.18.0/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/jbastien/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.1
      - iOS 16.1
      - macOS 13.0
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9862592
  Xcode:
    version: 14.1/14B47b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/jbastien/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Issue and Reproduction Steps

`react-native info` is a bit wonky but our project uses Hermes on Android and everything else works as expected.

Issue: 

Excluding gradle tasks app:createBundleDebugJsAndAssets app:createBundleReleaseJsAndAssets no longer works. 
On the CI this important for us because when we run our native android tests we do not require the bundles for those.

STR: 
On 0.71.8: `./gradlew test -p . --no-daemon -x :app:createBundle<ourVariant>ReleaseJsAndAssets -x :app:createBundle<ourVariant>DebugJsAndAssets --stacktrace --info` working
On 0.72.5: `./gradlew test -p . --no-daemon -x :app:createBundle<ourVariant>ReleaseJsAndAssets -x :app:createBundle<ourVariant>DebugJsAndAssets --stacktrace --info` not working.

```
> Task :app:merge<ourVariant>ReleaseResources FAILED
:app:merge<ourVariant>ReleaseResources (Thread[Execution worker Thread 2,5,main]) completed. Took 0.05 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:merge<ourVariant>ReleaseResources'.
> Querying the mapped value of flatmap(provider(task 'createBundle<ourVariant>ReleaseJsAndAssets', class com.facebook.react.tasks.BundleHermesCTask)) before task ':app:createBundle<ourVariant>ReleaseJsAndAssets' has completed is not supported
```

To resolve this issue or at least help I have added both variants to `debuggableVariants`. But this creates other issues that are blocking us. Removing the release variant from debuggableVariants makes our CI fail due to Java heap size:

```
 w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
16:53:07  
16:53:07  FAILURE: Build failed with an exception.
16:53:07  
16:53:07  * What went wrong:
16:53:07  A problem was found with the configuration of task ':app:createBundle<ourVariant>ReleaseJsAndAssets' (type 'BundleHermesCTask').
```

Thanks for helping

**Comment by cortinico** [comment]
This is happening as now we're using the Artifacts API from AGP to populate the APK. So if you exclude the task, the APK will still attempt to query the task to ask for its output (hence the error).

Using `debuggableVariant` should be the preferred way to achieve what you're looking into doing. The Java Heap space should be easy to fix if you increase the JVM memory in your `gradle.properties` file:

```
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
```

**Comment by PaperbagWriter** [comment]
> This is happening as now we're using the Artifacts API from AGP to populate the APK. So if you exclude the task, the APK will still attempt to query the task to ask for its output (hence the error).
> 
> Using `debuggableVariant` should be the preferred way to achieve what you're looking into doing. The Java Heap space should be easy to fix if you increase the JVM memory in your `gradle.properties` file:
> 
> ```
> org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
> ```

Thanks we ended up doing exactly this in the end, we had no choice but to remove the release flavor from the debuggableVariant as we had problem with some assets not being assembled releasing in prod and absolutely needing to build the JS bundle for our tests was not ideal. 

We ended up isolating our tests under the variant debug and no longer run test but `testDebug`, which is no longer triggering the release gradle steps.
