### ISSUE TITLE
Show Network Requests in Chrome Developer Tools' Network Tab

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4122]
Would be cool to see the [network requests](https://facebook.github.io/react-native/docs/network.html) made by react native on Chrome's Developer Tools Network tab.

**Comment by ide** [comment]
You can manually opt into this (see the thread here https://github.com/facebook/react-native/issues/934#issuecomment-150772039) but it's not enabled by default because Chrome's networking stack is different than iOS or Android's.
