### ISSUE TITLE
Windows OS development platform, 'Examples\UIExplorer' build successful, app installed on Android emulator, but does not do anything

### ISSUE THREAD

**Issue by pkpower** [facebook/react-native#4123]
Hi, 

The 'Examples\UIExplorer' build succeeds in the Windows development platform and installs fine in the Android emulator, but does not run in the emulator. When i open the app, i see a blank page.

> But I cannot execute the step './packager/packager.sh' on Windows

How do i get this to work properly?

**Comment by horsenn** [comment]
I have the same problem,it's looks like dosen't startup the react server,but i don't know how to startup the server

**Comment by jiangqqlmj** [comment]
you had build UIExplorer project and install app on emulator。you should execute ./packager/packager.sh   to start service

**Comment by fhelwanger** [comment]
I have the same problem.

When I run the packager, I get:

```
Usage: packager [-options] <jar file name> <bean name>

where options include:
   -clsid <class-id><class-id>         CLSID for the packaged bean
   -out <output directory><output directory>   destination directory for the packaged bean
   -reg                      consent to register the Active-X control
```

**Comment by fhelwanger** [comment]
Found a fix!

I'm using cmder, which includes cygwin, so you can run:

`sh packager/packager.sh`

**Comment by jsierles** [comment]
This can be handled by running your `packager/packager.sh` from a tool like cygwin, as suggested.

If you have a better solution for Windows, a PR is welcome! Closing this out for now.
