### ISSUE TITLE
My React-native app worked perfectly on 10/20/2023 but after I pulled the latest repo from gitlab and made an npm i legacy-peer-deps and installed the latest versions on 10/24/2023 I had a Podfile error which I never had 

### ISSUE THREAD

**Issue by Dusi10** [facebook/react-native#41235]
### Description

My React-native app worked perfectly on 10/20/2023 but after I pulled the latest repo from gitlab and made an npm i legacy-peer-deps and installed the latest versions on 10/24/2023 I had a Podfile error which I never had the error message is shown below.

macbook@Macbooks-MacBook-Air ios % pod install
error Cannot read properties of undefined (reading 'configurations').

[!] Invalid `Podfile` file: unexpected token at 'TypeError: Cannot read properties of undefined (reading 'configurations')

    at Object.dependencyConfig (/Users/macbook/Desktop/szigetkozapp/node_modules/react-native/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)

    at /Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/loadConfig.js:35:61

    at Array.reduce (<anonymous>)

    at getDependencyConfig (/Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/loadConfig.js:31:51)

    at Object.get @gorhom/bottom-sheet [as @gorhom/bottom-sheet] (/Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/loadConfig.js:101:20)

    at /Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/commands/config.js:15:51

    at Array.forEach (<anonymous>)

    at filterConfig (/Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/commands/config.js:14:38)

    at Object.func (/Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli-config/build/commands/config.js:25:32)

    at Command.handleAction (/Users/macbook/Desktop/szigetkozapp/node_modules/@react-native-community/cli/build/index.js:111:23)
'.

 #  from /Users/macbook/Desktop/szigetkozapp/ios/Podfile:7
 #  -------------------------------------------
 #  target 'SzigetkozApp' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

### React Native Version

0.66.5

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 148.59 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.18.0
    path: ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.18.0/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v16.18.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/macbook/.rvm/gems/ruby-3.0.3/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8.1
    path: /usr/bin/javac
  Ruby:
    version: 3.0.3
    path: /Users/macbook/.rvm/rubies/ruby-3.0.3/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.9
    wanted: ^11.3.9
  react:
    installed: 17.0.2
    wanted: 17.0.2
  react-native:
    installed: 0.66.5
    wanted: ^0.66.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: Not found

### Steps to reproduce

I tried to solve the error by deleting a node_modules and npm i legacy-peer-deps again but it didnt work, also tried to generate a Gemfile and specify the networking and cocoapods version but that also didnt work, tried to upgrade/downgrade the versions but that didnt work as well.

### Snack, screenshot, or link to a repository

no screenshots or repository yet

**Comment by uqmessias** [comment]
@Dusi10 did you solve this issue? The same problem is happening to me, but in my case, I'm using [Yarn Workspaces](https://yarnpkg.com/features/workspaces) to build a monorepo.

I have the root folder at `~/dev/myproject` and the actual react native folder is at `~/dev/myproject/packages/app`

**Comment by uqmessias** [comment]
> @Dusi10 did you solve this issue? The same problem is happening to me, but in my case, I'm using [Yarn Workspaces](https://yarnpkg.com/features/workspaces) to build a monorepo.
> 
> I have the root folder at `~/dev/myproject` and the actual react native folder is at `~/dev/myproject/packages/app`

In my case, it happened because the `@react-native-community/cli` was updated to a newer version due to the `"resolution"` properties inside of `~/dev/myproject/packages/app/package.json` being ignored. After I moved it to the `~/dev/myproject/package.json`, it worked again.

In any case, if you're reading this and is going through the same issue, take a look at this [blog post](https://tonsnoei.nl/en/post/2022/11/06/cannot-read-properties-of-undefined-reading-configurations/)
