### ISSUE TITLE
Error on "run fastlane" step while building with expo

### ISSUE THREAD

**Issue by andreas-moneygate** [facebook/react-native#41237]
### Description

Suddenly building IOS with expo is not working. Only change was accepting new terms and conditions with Apple.

"Build failed: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs."

error: File /Users/expo/Library/Developer/Xcode/DerivedData/Moneygate-ejsypnaybrnqcndbhqaksklbolce/Build/Intermediates.noindex/ArchiveIntermediates/Moneygate/BuildProductsPath/Release-iphoneos/Moneygate.app/main.jsbundle 

 ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/Moneygate-ejsypnaybrnqcndbhqaksklbolce/Build/Intermediates.noindex/ArchiveIntermediates/Moneygate/IntermediateBuildFilesPath/Moneygate.build/Release-iphoneos/Moneygate.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'Moneygate' from project 'Moneygate')

### React Native Version

0.70.14

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 11.44 GB / 31.70 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-221.6008.13.2211.9514443
    Visual Studio: 17.6.33829.357 (Visual Studio Community 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.14 => 0.70.14 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

eas build --profile production --clear-cache

### Snack, screenshot, or link to a repository

https://github.com/andreas-moneygate/mobile-app

**Comment by alichaudhry55** [comment]
Facing the same issue

› Generating debug HappySnaglist » HappySnaglist.app.dSYM

› Executing HappySnaglist » Bundle React Native code and images

    the transform cache was reset.


❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/HappySnaglist-guiayqbewpcligdmwfeecexxjmcy/Build/Intermediates.noindex/ArchiveIntermediates/HappySnaglist/BuildProductsPath/Release-iphoneos/HappySnaglist.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

**Comment by cipolleschi** [comment]
Please, open the same question on the [Expo repo](https://github.com/expo/expo). We don't use fastlane in the React Native vanilla workflow and they could help you better.

**Comment by andreas-moneygate** [comment]
> Please, open the same question on the [Expo repo](https://github.com/expo/expo). We don't use fastlane in the React Native vanilla workflow and they could help you better.

https://github.com/expo/expo/issues/25115

**Comment by ByronStar** [comment]
Having exactly the same environment and the same issue, I had a look at the Xcode log and found

/Users/expo/workingdir/build/node_modules/react-native/scripts/react-native-xcode.sh: line 169: /Users/expo/workingdir/build/ios/Pods/hermes-engine/destroot/bin/hermesc: No such file or directory

For me this looks quite like a react-native issue and I tried to fix it by forcing JSC engine in app.json:

`{
  "expo": {
    "jsEngine": "jsc"
  }
}`

But that didn't help ☹️

**Comment by ByronStar** [comment]
"Fun" fact using

{ "expo": { "jsEngine": "hermes" } }

fixed the build issues on iOS. Now the ball is definitively in the Expo court.

**Comment by andreas-moneygate** [comment]
Hi @ByronStar and thanks for the info. I tried both "jsEngine": "jsc"  & "jsEngine": "hermes" but no luck.

**Comment by cipolleschi** [comment]
Please open the issue against Expo repository.
