### ISSUE TITLE
Inconsistent Alignment of Text and Inline Views Across Platforms

### ISSUE THREAD

**Issue by ehsemloh** [facebook/react-native#41231]
### Description

On Android, inline views are aligned with center of the text while on iOS they are aligned with line bottom.

On the consumer side, this discrepancy causes extra platform specific code to further layout of inline graphic in rich text field, and is better eliminated.

<img width="569" alt="Screenshot 2023-10-30 at 10 08 04" src="https://github.com/facebook/react-native/assets/149237137/9288e9b1-896c-4c49-9870-4b8c9260a85a">

### React Native Version

0.72.6

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 115.42 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

(node:87116) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Steps to reproduce

Putting an image in paragraph in hello app

### Snack, screenshot, or link to a repository

<img width="569" alt="Screenshot 2023-10-30 at 10 08 04" src="https://github.com/facebook/react-native/assets/149237137/71059800-29e2-48b7-a1f4-512e77dd90ef">

**Comment by ehsemloh** [comment]
PR raised: https://github.com/facebook/react-native/pull/41233

**Comment by fabriziobertoglio1987** [comment]
Hello,

Thanks for the issue. I have been contributing to facebook/react-native for 4 years and specialize in the Text/TextInput components. I currently have 58 facebook/react-native PRs:

https://github.com/facebook/react-native/pulls?q=is%3Apr+author%3Afabriziobertoglio1987+ 

It is the suggested approach from the react-native core team (see this [discussion](https://github.com/react-native-community/discussions-and-proposals/discussions/731#discussioncomment-7651145)).

I'm publishing several fixes for Text and TextInput component in a separate library [react-native-improved](https://github.com/fabriziobertoglio1987/react-native-improved). 

- The Component is based on ReactTextView, it is the same implementation from react-native.
- It will include several bug fixes. 
- You can use the library until the PR is merged and released with react-native. 
- You can use side by side both components from react-native and react-native-improved, depending on where you need the fix.
- I will also publish the PR to facebook/react-native (daily fixes and releases).

The advantages would be:
- Increased engagement with the community, issues are quickly fixed.
- No limitations when merging PRs (react-native main branch is used on facebook marketplace).
- Only Meta employees can merge and review facebook/react-native PRs.
- Allows us to further experiment and develop react-native.

Do you want me to publish for you a patched release? I'm working on a list of priorities. Thanks

**Comment by ehsemloh** [comment]
Hi @fabOnReact, yes, I would love to patch this issue. Thank you very much!
