### ISSUE TITLE
[windows] Generating Signed APK not working

### ISSUE THREAD

**Issue by danhanfry** [facebook/react-native#4124]
sorry for my English, this is my first issues

Trying to create a production apk

I can run perfect react-native start / react-native run-android and it works great

------------------------------------------------------
SO: windows 10
node: 4.2.2
npm: 2.14.7
react-native: 0.1.7

------------------------------------------------------

I followed this tutorial completely accurate https://facebook.github.io/react-native/docs/signed-apk-android.html#content

1- the key gender [ok]
![2](https://cloud.githubusercontent.com/assets/8139751/11161819/2ddc66a4-8a88-11e5-97dc-83c0eb5e8f01.png)

2- Edit the file ~/.gradle/gradle.properties [ok]
![screenshot_2](https://cloud.githubusercontent.com/assets/8139751/11161830/77fa37fc-8a88-11e5-943c-5d25765dc900.png)

3- Adding signing config to your app's gradle config (android/app/build.gradle)
![screenshot_3](https://cloud.githubusercontent.com/assets/8139751/11161854/f1c22ee6-8a88-11e5-8f86-cf558b335d70.png)

------------------------------------------------------
launch command ./gradlew assembleRelease

------------------------------------------------------

The error is as follows
![screenshot_1](https://cloud.githubusercontent.com/assets/8139751/11161860/2919a95a-8a89-11e5-8265-31faf5363d14.png)

did not find the command-native react

![screenshot_4](https://cloud.githubusercontent.com/assets/8139751/11171331/b9eacb2a-8bed-11e5-9cc5-b86939cebf72.png)

then we change the absolute path

```
    // set up the call to the react-native cli
    workingDir reactRoot
    commandLine "C:/Users/yo/AppData/Roaming/npm/react-native.cmd", "bundle", "--platform", "android", "--dev", "false", "--entry-file",
            entryFile, "--bundle-output", jsBundleFileRelease, "--assets-dest", resourcesDirRelease
```

in this case, it fails. It is infinite loading

```
:app:prepareComFacebookReactReactNative0140Library UP-TO-DATE
:app:prepareComGoogleAndroidExoplayerExoplayerR151Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
> Building 79% > :app:bundleReleaseJsAndAssets
```

----------

**test without key file (is exactly the same)**

After testing several commands.

    ./gradlew --info assembleRelease

If I wait long at the end I get an error

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/LlPZj.png

**Comment by InnerPeace080** [comment]
i have same issue like you.

**Comment by AnnatarHe** [comment]
i have same issue like you.

**Comment by ippa** [comment]
Same issue here.

**Comment by tdzl2003** [comment]
I'll take a look at this.

**Comment by InnerPeace080** [comment]
it seem still not work

![capture4](https://cloud.githubusercontent.com/assets/3762408/11260296/3f97e4d2-8e9c-11e5-890e-70a948e4ac9c.PNG)

**Comment by danhanfry** [comment]
same here
```


* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:bundleReleaseJsAndAssets'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.ja

```

**Comment by InnerPeace080** [comment]
i found tempolary for myown : you can refer here #4170

**Comment by danhanfry** [comment]
some, like

**Comment by tdzl2003** [comment]
About the issue part 2, #4071 works for me.

**Comment by InnerPeace080** [comment]
oh. thank you. this work for me too. it's better than my solution . i tried add //pipe/ but it not work , maybe i add it not right (so stupid)

**Comment by danhanfry** [comment]
## unified solutions
https://github.com/danhanfry/react-native-windows-apk

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/windows-generating-signed-apk-not-working

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
