### ISSUE TITLE
IOS Build Bug

### ISSUE THREAD

**Issue by chrisgod336** [facebook/react-native#41243]
### Description

I am trying to buil my app to IOS, but evert time I try to build a error happen saying that a necessary file does not exists, but I never had seem this file.

### React Native Version

0.70.6

### Output of `npx react-native info`

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 804.95 MB / 7.75 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\SEMPRE\MobileCondominioSindico\node_modules\.bin\yarn.CMD
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.14 => 0.70.14
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/SempreSndico-ekrsxgtzhbzxcxbstiylbytspxsr/Build/Intermediates.noindex/ArchiveIntermediates/SempreSndico/BuildProductsPath/Release-iphoneos/SempreSndico.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/SempreSndico-ekrsxgtzhbzxcxbstiylbytspxsr/Build/Intermediates.noindex/ArchiveIntermediates/SempreSndico/IntermediateBuildFilesPath/SempreSndico.build/Release-iphoneos/SempreSndico.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'SempreSndico' from project 'SempreSndico')

▸ (1 failure)

** ARCHIVE FAILED **

The following build commands failed:

	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/SempreSndico-ekrsxgtzhbzxcxbstiylbytspxsr/Build/Intermediates.noindex/ArchiveIntermediates/SempreSndico/IntermediateBuildFilesPath/SempreSndico.build/Release-iphoneos/SempreSndico.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'SempreSndico' from project 'SempreSndico')

(1 failure)

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.210.1                 |

| sdk         | iPhoneOS16.1.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Snack, screenshot, or link to a repository

https://expo.dev/accounts/christiansantos/projects/mobile-sempre-sindico/builds/f51ad8e5-e1ec-4187-b052-ffa66d69da2d

**Comment by cipolleschi** [comment]
This seems an Expo failure, as we don't use fastlane in vanilla React Native. Please open this same question in the [Expo repo](https://github.com/expo/expo).
