### ISSUE TITLE
Design changed when changed the version from 8.4 to 9.1 in 5s

### ISSUE THREAD

**Issue by shaikhussian** [facebook/react-native#4126]
Hai, i checked an react-example: in Iphone5s device version:8.4,with the same 5s device, when i changed the version to 9.1 I got a design problem, and i have doubt that how to fix the same font view for different devices,
I  am using:
react-native: 0.11.4

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow with more details, thanks!
