### ISSUE TITLE
Unable to run the project on the simulator after i run on a usb device

### ISSUE THREAD

**Issue by AngelRmrz** [facebook/react-native#41268]
### Description

I can't run my project in a simulator after running it on my physical device, I always get the same error logs, I have been trying the solutions provided in this [issue](https://github.com/facebook/react-native/issues/39743) I still get the same error. 

Here is a screenshot of the logs:

<img width="1440" alt="Captura de pantalla 2023-10-31 a la(s) 1 31 11 p m" src="https://github.com/facebook/react-native/assets/69778769/0fb8e937-ea51-4768-a23d-7f5d55e9bb47">

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M2
  Memory: 1.71 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Just run npm start and select the run on ios 

### Snack, screenshot, or link to a repository

<img width="1440" alt="Captura de pantalla 2023-10-31 a la(s) 1 32 50 p m" src="https://github.com/facebook/react-native/assets/69778769/c07260b6-c48f-4b32-9909-1fb0acdcb7ec">

Also when i run npx react-native-doctor the log looks like this:

<img width="1440" alt="Captura de pantalla 2023-10-31 a la(s) 1 59 54 p m" src="https://github.com/facebook/react-native/assets/69778769/53e6cbd8-2a0d-4011-8e22-ef7c781bf07a">

**Comment by kdemishev** [comment]
The same issue.
https://github.com/facebook/react-native/issues/39743 didn't help

**Comment by cipolleschi** [comment]
This is more likely an Expo issue. We had already closed several issues with similar symptoms: https://github.com/facebook/react-native/issues/39743 for example.

If you are using expo, please open an issue in [their repo](https://github.com/expo/expo) as they would be more helpful.
