### ISSUE TITLE
Framework not found ASN1Decoder

### ISSUE THREAD

**Issue by pilarelisii** [facebook/react-native#41269]
### Description

The error appears when I build the iOS app in Xcode. Also, don't know if they are related but another error appear that says 'Linker command failed with exit code 1 (use -v to see invocation)'.

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: macOS 13.0.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 928.14 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.10.23.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

opening myproject.xcworkspace and then build.

### Snack, screenshot, or link to a repository

<img width="257" alt="Captura de pantalla 2023-10-31 a la(s) 17 17 38" src="https://github.com/facebook/react-native/assets/69323603/71c68a43-824e-4d3b-8ebd-0f90d559f4c7">

**Comment by DylanTet** [comment]
Have you tried removing ASN1Decoder and re-adding it?
