### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':tasks'. > Could not create task ':app:extractDeepLinksDebug'.    > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by Yashtoddle** [facebook/react-native#41271]
### New Version

0.72.0

### Old Version

0.71.13

### Build Target(s)

System:   OS: macOS 14.0   CPU: (8) arm64 Apple M1   Memory: 67.50 MB / 8.00 GB   Shell:     version: "5.9"     path: /bin/zsh Binaries:   Node:     version: 16.20.0     path: /usr/local/bin/node   Yarn: Not Found   npm:     version: 6.14.15     path: ~/student-app/node_modules/.bin/npm   Watchman:     version: 2023.08.28.00     path: /opt/homebrew/bin/watchman Managers:   CocoaPods:     version: 1.12.1     path: /usr/local/bin/pod SDKs:   iOS SDK:     Platforms:       - DriverKit 22.2       - iOS 16.2       - macOS 13.1       - tvOS 16.1       - watchOS 9.1   Android SDK: Not Found IDEs:   Android Studio: 2022.2 AI-222.4459.24.2221.10121639   Xcode:     version: 14.2/14C18     path: /usr/bin/xcodebuild Languages:   Java:     version: 11.0.20.1     path: /opt/homebrew/opt/openjdk@11/bin/javac   Ruby:     version: 2.6.10     path: /usr/bin/ruby npmPackages:   "@react-native-community/cli": Not Found   react:     installed: 18.2.0     wanted: 18.2.0   react-native:     installed: 0.72.6     wanted: ^0.72.0   react-native-macos: Not Found npmGlobalPackages:   "*react-native*": Not Found Android:   hermesEnabled: false   newArchEnabled: false iOS:   hermesEnabled: false   newArchEnabled: false

### Output of `react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 67.50 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 6.14.15
    path: ~/student-app/node_modules/.bin/npm
  Watchman:
    version: 2023.08.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: ^0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Issue and Reproduction Steps

I was trying to update my react native version from 0.71.13 to 0.72.0 than I am facing this issue 
just simply do the changes according to update guide and run the app

**Comment by palaniqplay** [comment]
Same here.

**Comment by justinjaeger** [comment]
Same, been attempting to debug for days.

Working with `Android Studio Giraffe | 2022.3.1 Patch 3`

**Comment by cortinico** [comment]
> extractDeepLinksDebug

We (React Native) don't own this task. This is created by an external library or tool. You should report this issue to them.

Also without a repro this is impossible to debug.

**Comment by josanjohnata** [comment]
I updated the RN 0.70.13 to 0.72.0 and I got that same error here.
