### ISSUE TITLE
[OS X] ./gradlew assembleRelease generates same apk, no changes

### ISSUE THREAD

**Issue by liesislukas** [facebook/react-native#4127]
Hi, was using this command successfully, maybe some update came in. I can't find out what's wrong, but when building debug apk js updates in avd device, when i assemble release apk and move it to tablet - no changes. Apk works fine, but js is not up to date. I've tried all kind of magic - restart, factory reset of tablet.. nothing helps, old apk gets generated again and again while doing release.

I'm deleting old apk with all build folder from /android/app/build i get new one, but it has no js changes.

some gradle cache? what can be wrong?

node_modules > react-native  "version": "0.14.2",

$ npm --version
2.14.7
$ node --version
v4.2.2
$ react-native --version
0.1.7

OS X El Capitan v 10.11.1

OS x newest

**Comment by satya164** [comment]
Isn't the directory supposed to be `android/app/build/outputs/apk/app-release.apk`?

**Comment by liesislukas** [comment]
yes it is, that apk gets generated same again and again. I thought, maybe it's some cache, i've deleted all "build" directory, it was all regenerated again, but no luck. I've got new apk file with old code again. It works fine with debuging on avd.. But if i buil release - no errors, just old code at ne apk.

**Comment by liesislukas** [comment]
Thanks god, it works again!! I've deleted build dir, closed everything, restarted my pc and it worked! i don't know what was that, but restart didn't helped first time. I guess it was some kind of cache..
