### ISSUE TITLE
'react/bridging/LongLivedObject.h' file not found

### ISSUE THREAD

**Issue by ArtsiomAstrouski** [facebook/react-native#41281]
### Description

❌ /Users/mac/Library/Developer/Xcode/DerivedData/name-cyhmusmnrimlvbgabnbaiohwxlxj/Build/Products/Debug-iphonesimulator/ReactCommon/ReactCommon.framework/Headers/react/nativemodule/core/ReactCommon/LongLivedObject.h:11:10: 'react/bridging/LongLivedObject.h' file not found

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Memory: 66.35 MB / 32.00 GB
  Shell:
    version: "5.9"
Binaries:
  Node:
    version: 18.18.2
  Yarn:
    version: 1.22.19
  npm:
    version: 9.8.1
Managers:
  CocoaPods:
    version: 1.14.2
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3
  Xcode:
    version: 14.3/14E222b
Languages:
  Java:
    version: 21.0.1
  Ruby:
    version: 3.2.2
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

After installing yarn install => cd ios => pod install => react-native start --verbose => ENVFILE=.env react-native run-ios I get this. 99% of all articles point to an error in Gradle.
I tried adding https://github.com/facebook/react-native/issues/35664#issuecomment-1446204160 but it didn’t help, the same error when updating to “react-native”: “0.73.0-rc.3”, and Gradle 0.8 .3

Tried https://github.com/mrousavy/react-native-vision-camera/issues/1121#issuecomment-1680806830 - did not help

Tried this https://github.com/facebook/react-native/issues/34102#issuecomment-1176370957 - didn't help

   "@babel/plugin-syntax-import-assertions": "^7.22.5",
    "@babel/plugin-transform-template-literals": "^7.22.5",
    "@craftzdog/react-native-buffer": "^6.0.5",
    "@hookform/resolvers": "^3.3.2",
    "@openspacelabs/react-native-zoomable-view": "2.1.4",
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-camera-roll/camera-roll": "6.0.0",
    "@react-native-clipboard/clipboard": "^1.12.1",
    "@react-native-community/checkbox": "^0.5.16",
    "@react-native-community/datetimepicker": "^7.6.1",
    "@react-native-community/geolocation": "^3.1.0",
    "@react-native-community/netinfo": "^9.4.1",
    "@react-native-community/slider": "^4.4.3",
    "@react-native-firebase/app": "^18.4.0",
    "@react-native-firebase/dynamic-links": "^18.4.0",
    "@react-native-firebase/messaging": "^18.4.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^1.9.5",
    "amazon-cognito-identity-js": "^5.2.14",
    "aws-amplify": "^4.3.x",
    "aws-amplify-react-native": "^7.0.7",
    "aws-sdk": "^2.1395.0",
    "base-64": "^1.0.0",
    "base64-arraybuffer": "^1.0.2",
    "buffer": "^4.9.1",
    "coap-packet": "^1.1.1",
    "deprecated-react-native-prop-types": "^2.3.0",
    "eslint-plugin-ft-flow": "^2.0.3",
    "events": "^3.3.0",
    "fast-text-encoding": "^1.0.6",
    "i18next": "^22.5.1",
    "i18next-conv": "^14.0.0",
    "lottie-ios": "4.3.3",
    "lottie-react-native": "6.3.1",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.43",
    "patch-package": "^6.5.1",
    "posixtz": "^1.0.0",
    "posthog-react-native": "^2.7.1",
    "postinstall-postinstall": "^2.1.0",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-hook-form": "^7.44.3",
    "react-i18next": "^12.3.1",
    "react-native": "0.72.5",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-animatable": "^1.3.3",
    "react-native-contacts-wrapper": "^0.2.4",
    "react-native-copilot": "^3.2.1",
    "react-native-device-info": "^10.11.0",
    "react-native-document-picker": "^8.2.0",
    "react-native-exception-handler": "^2.10.10",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "2.13.2",
    "react-native-haptic-feedback": "^2.2.0",
    "react-native-image-picker": "^5.3.1",
    "react-native-in-app-review": "^4.3.3",
    "react-native-input-spinner": "^1.8.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-localize": "^2.2.6",
    "react-native-modal-datetime-picker": "^14.0.1",
    "react-native-otp-textinput": "0.0.9",
    "react-native-paper": "^5.8.0",
    "react-native-permissions": "3.8.4",
    "react-native-quick-base64": "^2.0.6",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.27.0",
    "react-native-select-dropdown": "^3.3.3",
    "react-native-share": "^8.2.2",
    "react-native-sound": "^0.11.2",
    "react-native-sound-manager": "^1.0.9",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^13.9.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-text-input-mask": "^3.2.0",
    "react-native-touch-id": "^4.4.1",
    "react-native-udp": "^4.1.7",
    "react-native-vector-icons": "^10.0.1",
    "react-native-video": "^6.0.0-alpha.8",
    "react-native-webview": "13.6.2",
    "react-native-wifi-reborn": "^4.8.3",
    "react-redux": "^8.0.7",
    "reactotron-react-native": "^5.0.3",
    "reanimated-color-picker": "^2.3.1",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "socket.io-client": "^4.6.2",
    "styled-components": "^5.3.11",
    "utf8": "^3.0.0",
    "yup": "1.2.0"

### Snack, screenshot, or link to a repository

![Снимок экрана 2023-11-01 в 16 51 00](https://github.com/facebook/react-native/assets/86202029/ef0510d9-23d6-4001-957c-46efb843aa8e)
![ошибка лайт](https://github.com/facebook/react-native/assets/86202029/cfc00a0e-c14f-4d26-8541-fa22ffc81f37)

**Comment by ArtsiomAstrouski** [comment]
I also removed 99% of all libraries, except for the basic react libraries, the error persisted

**Comment by ArtsiomAstrouski** [comment]
updated to 0.72.6, the same thing, on version 0.71.14, there were no problems

**Comment by cipolleschi** [comment]
We are aware of the problem. There are some libraries that are not configured in the way we are suggesting to configure them and they don't work when `use_framework!` is enabled, which is required by Firebase.
For example, I opened PRs on [`RNScreens`](https://github.com/software-mansion/react-native-screens/pull/1920) and [`RNGestureHandler`](https://github.com/software-mansion/react-native-gesture-handler/commit/2300af719edd6297ad0c9436fbd6b5d9b4837e02) to update their configuration.

But I haven't had the time to go through all the libraries, of course, and we have to rely on maintainer to release new versions of those updated libraries.

The list of dependencies is helpful, thanks for providing this.
