### ISSUE TITLE
white screen in jailbreak iphone

### ISSUE THREAD

**Issue by justTemp** [facebook/react-native#4129]
Hi, first, thanks for a great work here.

we develop an app with react-native 0.12, and already push it in app store.
anything is ok, but we get white screen in some jailbreak iphone

iphone5s, 7.0.6(11B651)

![p51114-180026](https://cloud.githubusercontent.com/assets/15847768/11164316/eb37b132-8b27-11e5-924a-51e5dff6eaab.jpg)

**Comment by ide** [comment]
Please provide debug logs, crash logs, etc.

**Comment by brentvatne** [comment]
@ide - do you think it's worth supporting jailbroken phones? imo it's not worth it as there could be any number of changes that we couldn't possible reproduce and try to fix on our end

**Comment by ide** [comment]
It's pretty low-pri for those reasons though I could see taking good PRs that fix bugs that are exposed by jailbroken devices. I believe I've seen RN run on a clean jailbroken device before (no cydia for example). Let's close this issue if we don't get a PR or logs identifying the issue in a few days.

**Comment by justTemp** [comment]
hi, ide, I am sorry for the slow response. is sunday in China.

(1) no crash, keep in white screen after LaunchScreen
(2) get access log in Terminal, but no error
[11:58:33] <START> request:/index.ios.bundle?platform=ios&dev=true
[11:58:33] <END>   request:/index.ios.bundle?platform=ios&dev=true (20ms)

any idea to get more debug log? thanks

**Comment by justTemp** [comment]
@ide @brentvatne i don't think it is worth to support  jailbroken phones before.
but it's strange in China,  Jailbroken is popular.
if ignore jailbroken user, will be a regret for developer.

**Comment by justTemp** [comment]
solved it.

1, remove all ES6 syntax, etc " for (var element of array) { } "
2, Don't call originalConsole methods when they don't exist
https://github.com/facebook/react-native/commit/e885628245193dfbd893ec27aed901607a543cdc

this work in react-native 0.12, iphone5s, 7.0.6(11B651),  jailbreak

**Comment by ide** [comment]
I think the issue here was that you needed to test on iOS 7, which doesn't support the same JS features.

**Comment by justTemp** [comment]
@ide i think so, thanks
