### ISSUE TITLE
Is there anyway to send event back to javascript after install/unistalling of apps?

### ISSUE THREAD

**Issue by Sharathnasa** [facebook/react-native#4131]
Could you please let me know if there is way/react-native supports sending events back to javascript after installing or unistalling of apps. I know we can send events back to JS from native code. But for the above mentioned scenario, i have tired but not able to achieve it. Could someone please help me in this regards.

Regards,
Sharath

**Comment by ide** [comment]
On iOS at least you don't get notified when the user installs or uninstalls apps. Maybe it is different on Android. Maybe it is not possible, though, regardless of whether you are using RN.

If you can get events at the native layer, then you should write a native React Native module that sends these events from Java to JS. See the RN Android docs and the React Native code for examples of how to do this.

If there is something specific to RN that can facilitate this, leave a comment.

**Comment by Sharathnasa** [comment]
It is possible in android. I was able to do it using RN. I wrote a plugin to do the same. Thanks
