### ISSUE TITLE
Native React - VS Studio Code - npm run android - Execution failed for task ':app:checkDebugAarMetadata'

### ISSUE THREAD

**Issue by yuezonglun** [facebook/react-native#41310]
### Description

I have been getting this error when trying to run npm android build on my native react project. I have gone through the entire android setup along with updating Environment variables. The emulator works but the install fails with the following message:

`* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform react-android-0.72.6-debug.aar (com.facebook.react:react-android:0.72.6) to match attributes {artifactType=android-aar-metadata, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/yueyue/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.72.6/2e2db118c9084b05c1a5d6079148bc983668f372/react-android-0.72.6-debug.aar.
         > Java heap space`

build.gradle as follows:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        kotlinVersion = "1.7.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
        maven {url 'https://dl.google.com/dl/android/maven2/'}
    }
}
`
Please help.

### React Native Version

0.72.6

### Output of `npx react-native info`

npm WARN cli npm v10.2.2 does not support Node.js v16.17.0. This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 14.1
  CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Memory: 111.47 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.0
    path: ~/.nvm/versions/node/v16.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.2
    path: ~/.nvm/versions/node/v16.17.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "23"
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-30 | Intel x86 Atom_64
      - android-30 | Google APIs Intel x86 Atom
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

yarn android 

### Snack, code example, screenshot, or link to a repository

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        kotlinVersion = "1.7.0"

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
    }
    dependencies {
        // implementation project(':jpush-react-native')  // 添加 jpush 依赖
        // implementation project(':jcore-react-native')  // 添加 jcore 依赖
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }
        google()
        maven { url 'https://www.jitpack.io' }
        maven {url 'https://dl.google.com/dl/android/maven2/'}
    }
}
`

**Comment by 12ya** [comment]
Try to delete the app from your phone and build again

**Comment by yuezonglun** [comment]
> Try to delete the app from your phone and build again

Deleted it, but still have this problem

**Comment by yuezonglun** [comment]
@12ya Deleted it, but still have this problem

**Comment by pekq** [comment]
I was able to resolve by clearing caches using this awesome tool https://github.com/taboulot/rn-game-over

```
npx rn-game-over -a
npx rn-game-over -j
```

I first tried with built in clean tool (`npx react-native clean`) but it had no effect.

I  encountered this bug when removing `expo-dev-client` package from the project.

**Comment by cortinico** [comment]
> > Java heap space

This means you're running out of memory.
You can increase the max memory you're giving to the build process in your `gradle.properties` file:
https://github.com/facebook/react-native/blob/0cbd2a345d613b1b6e6a5b1c2965018adfb45f6f/packages/react-native/template/android/gradle.properties#L13

**Comment by VNDRN** [comment]
> npx rn-game-over -a
> npx rn-game-over -j

This and rebooting my device worked for me!

**Comment by ObscurusGrassator** [comment]
After clean and restart gradle is this error retry (react native 76.2). I am must set:

```org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m```

This is not good solution. Please repair real problem in backround.

**Comment by zahid502** [comment]
**Using Android Studio's AVD Manager:**
Open Android Studio.
Navigate to Tools > AVD Manager.
In the AVD Manager window, locate the virtual device you wish to wipe data from.
Click the down arrow icon (often a triangle or three dots) under the "Actions" column for that virtual device.
Select "**Wipe Data**" from the dropdown menu.
Confirm the action when prompted
