### ISSUE TITLE
Unable to send data from ReactNative App to Android Kotlin Standalone app

### ISSUE THREAD

**Issue by iamsamuelhere** [facebook/react-native#41323]
### Description

My use case is I have a standalone android kotlin app. And I have a standalone reactnative app. I have built reactnative app and generated a bundle file for the reactnative app. Now I have included it in standalone android project and using reactrootview to invoke the reactnative code from android screen which works fine.

**My use case is to send data from Reactnative project to Android app.**
While reading in docs, it suggests NativeModules / ReactBridge but that is written only inside the same reactnative project's android/ios folder to communicate internally within the app (what I understood).

I am able to send data from ReactNative to Android while invoking the bundle using ReactRootView. But I need to send some data back to the Android app to consume and use.

What should be the approach to pass data from ReactNative to Android app? Please help

### React Native Version

0.72.4

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 82.09 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.14.2
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/userone/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

- Generate the bundle file of the ReactNative App:

- Android - npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output ./index.android.bundle --assets-dest ../index.android.bundle

- Include the bundle file into your native android app use the RootReactView to invoke the bundle
- Try passing some data from ReactNative App to Android. And Check if the value is received on Android App.

### Snack, code example, screenshot, or link to a repository

I have also tried ReactBridge Native Modules but when I tried to check NativeModules in ReactNative app got {}.
(Native modules were created on the standalone android app)
Link for code - https://stackoverflow.com/questions/77422711/facing-issue-while-calling-reactmethod-from-reactnative-app-to-standalone-andro

**Comment by cortinico** [comment]
You can use a NativeModule to write to a shared storage. For example you could use SharedPreferences, writing on File, or using a DB like Room. Then you can access that same information from the Android-only part of your app.
