### ISSUE TITLE
Horizontal FlatList scrolls in the opposite direction of swipe

### ISSUE THREAD

**Issue by Leena-Sharma-rsys** [facebook/react-native#41351]
### Description

On an Android device, when swiping back to the beginning of a FlatList with horizontal={true} the FlatList often scrolls in the opposite direction of your swipe, sending you away from the beginning and back towards end. The problem does not seem to occur on iOS.

### React Native Version

0.69.6

### Output of `npx react-native info`

System:
  OS: macOS 12.4
  CPU: (10) arm64 Apple M1 Pro
  Memory: 106.75 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 8.3.1
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.2
      - iOS 15.2
      - macOS 12.1
      - tvOS 15.2
      - watchOS 8.3
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.1 AI-211.7628.21.2111.8193401
  Xcode:
    version: 13.2.1/13C100
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.8
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.1.0
    wanted: 18.1.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.69.6-3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

### Steps to reproduce

Hi,
just create a horizontal flatlist

The similar isssue has been reported to #38859
but the fix was for vesrion 0.72 version.. which did not fix in my case

### Snack, screenshot, or link to a repository

Not a public code

**Comment by NickGerleman** [comment]
This is fixed in likely fixed in RN 0.73 with https://github.com/facebook/react-native/commit/30c7e9dfa41348e96e946384c76f038ccd859896
