### ISSUE TITLE
TabBarIOS icons not positioned in center on iPad

### ISSUE THREAD

**Issue by patelsan** [facebook/react-native#4136]
TabBarIOS item icons not positioned correctly on iPad

![image](https://cloud.githubusercontent.com/assets/898353/11167664/a41cc16a-8b32-11e5-9b37-cdb826d2e22b.png)

Setting the width on the TabBarIOS Item doesn't have any effect. So, may be it is an iOS issue as explained in this SO answer: http://stackoverflow.com/questions/23846478/uitabbar-images-and-title-are-not-center-aligned-in-ipad

If this is correct, may be we need to call `setItemWidth` through TabBarIOS? (just like `setTintColor` is called for `tintColor`) Or is there any workaround?

**Comment by mkonicek** [comment]
@facebook-github-bot stack-oveflow

**Comment by mkonicek** [comment]
Hey @patelsan, we're a small team and rely on the community to send bugfixes for issues that don't affect fb apps.

**Comment by mkonicek** [comment]
I don't know about this specific issue but if you know how to improve the TabBarIOS consider sending a pull request.

**Comment by geirman** [comment]
@facebook-github-bot bugfix

**Comment by geirman** [comment]
@facebook-github-bot label Help Wanted

**Comment by geirman** [comment]
@facebook-github-bot label iOS
