### ISSUE TITLE
Bugs in displaying the app size on iPad

### ISSUE THREAD

**Issue by fkazemi5236** [facebook/react-native#41373]
### Description

I created a basic React Native app and ran it on iPad devices. The problem I encountered is the size of the app on the iPad
I need the program to match the device size exactly, but I ran into a problem

device: iPad (10th eneration)
RN version: 0.72.4

<img width="1175" alt="Screenshot 1402-08-17 at 10 05 50 in the morning" src="https://github.com/facebook/react-native/assets/46262018/cec8774f-c59e-4b2e-bef0-98cdd964f150">

### React Native Version

0.72.4

### Output of `npx react-native info`

npm run ios

### Steps to reproduce

npm start
npm run ios

### Snack, screenshot, or link to a repository

https://github.com/facebook/react-native

**Comment by fkazemi5236** [comment]
@mojodna how i can fix this problem with show app in ipad scale

**Comment by kr396** [comment]
> how i can fix this problem with show app in ipad scale

<img width="723" alt="image" src="https://github.com/facebook/react-native/assets/60640854/0a4d66a0-fee0-4dd5-b813-c52af11ea8e5">


Select target -> General -> Supported destination-> Using + icon add iPad.
