### ISSUE TITLE
Networking - Issue with Handling of Chunked Gzip Stream Data

### ISSUE THREAD

**Issue by wsliaw** [facebook/react-native#41386]
### Description

I'm encountering an issue when attempting to receive chunked gzip stream data from the server. While the current implementation works flawlessly for both plain text and fully gzipped responses, it fails to handle chunked gzipped responses appropriately. Specifically, only the first chunk of data is received.

Since React Native's fetch doesn't support streaming, I utilize [react-native-fetch-api](https://github.com/react-native-community/fetch), which directly interacts with React Native's Networking API.

What I discovered is that [incrementalDataBlock](https://github.com/facebook/react-native/blob/27651720b40cab564a0cbd41be56a02584e0c73a/Libraries/Network/RCTNetworking.mm#L557) is only called once when the stream is chunked and gzipped (it is called the same number of times when not gzipped).

### React Native Version

0.72.6

### Output of `npx react-native info`

```
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 180.95 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.4.1
    path: /usr/local/bin/yarn
  npm:
    version: 8.15.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.10.23.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

I have implemented a Node JS server and client that function perfectly across all test cases. 
However, I'm encountering an issue with the React Native client.

Steps:
1. Start the Node JS server.
2. Launch the React Native client.
3. Tap the stream button to initiate the server call.
4. Observe the difference in behavior based on the ZIP flag in server.js.

Behavior:
Successful reception of full data when the `ZIP` flag in server.js is set to false ✅.
Only the first chunk is received when the `ZIP` flag is set to true ❌.

Expectation:
I expect the React Native client to exhibit consistent behavior across all test cases, similar to the Node JS client. Regardless of the `ZIP` flag, the client should receive the full data stream.

### Snack, screenshot, or link to a repository

[Node JS server & client](https://github.com/wsliaw/stream)
[React Native client](https://github.com/wsliaw/react-native-stream-client)

**Comment by cristianbote** [comment]
Having the same issue here as @wsliaw. Nice reproduction repo!
