### ISSUE TITLE
boxShadow

### ISSUE THREAD

**Issue by oisinlavery** [facebook/react-native#414]
Do you plan on supporting boxShadow directly in the Stylesheet object?
https://facebook.github.io/react-native/docs/flexbox.html

In regular native development, shadows are added to a UIView's layer, how do I interact with a layer using React? A code example would be great.

...and thanks for making this, loving it so far.

**Comment by ericvicenti** [comment]
We definitely need this feature.

@nicklockwood, is this on your radar? Do you have any advice for the community about how it should be implemented in [RCTViewManager](https://github.com/facebook/react-native/blob/master/React/Views/RCTViewManager.m)?

**Comment by wangii** [comment]
not being able to enable shadow with stylesheet settings:
``` javascript
        shadowOffset:{
            width: 10,
            height: 10,
        },
        shadowColor: 'black',
        shadowOpacity: 1.0,
```

anything missing in above code?

**Comment by oisinlavery** [comment]
Those shadow settings seem to only apply to Text elements right now.

**Comment by oisinlavery** [comment]
My mistake! This is working as described. Here is precise documentation: 
http://facebook.github.io/react-native/docs/view.html#style

**Comment by wangii** [comment]
@oisinlavery could you shade some light?

**Comment by wangii** [comment]
forget it. it appears to be a bug in iOS simulator 5s and above that `setShadowOpacity` not processed.

**Comment by antoinerousseau** [comment]
any plan on having `boxShadow` on Android?

**Comment by cinder92** [comment]
👍  for Android!

**Comment by winterbe** [comment]
For Android take a look at the `elevation` prop in `<View>`.

Unified shadows via `boxShadow` style would be super awesome! 👍

**Comment by mhdayyoob** [comment]
hi,
            can you please help me to write box-shadow in RN. please show de a demo as you written.

thanks in Advance

**Comment by uriklar** [comment]
+1 for a good example

**Comment by uriklar** [comment]
For anyone here looking for one, here's a working example you can play with
https://rnplay.org/apps/dkhXVw

**Comment by seyaobey** [comment]
@uriklar This works only on ios. Is it possible to have boxShadow with android?

**Comment by Rolando-Barbella** [comment]
@uriklar the link is broken
