### ISSUE TITLE
Switch react-native to use core-js (more specifically core-js Promise)

### ISSUE THREAD

**Issue by burgalon** [facebook/react-native#4142]
Currenttly react-native [is using](https://github.com/facebook/react-native/blob/master/package.json#L104) [then/Promises](https://github.com/then/promise) which is missing reporting of unhandled exception/rejected promises.
This important feature is available in [core-js](https://github.com/zloirock/core-js) which seems to work fine with JSC though I'm not seeing any official notes on compatibility.
I was able to just use `npm i --save core-js` and do `import 'core-js'` in order to run over the react-native polyfill.

I would love to try and turn this into a pull request unless there's something I'm missing here

**Comment by davidaurelio** [comment]
Addressed in b064094
