### ISSUE TITLE
[Android 12, 13] When some android devices are on the background, the app is stopped or restarted 

### ISSUE THREAD

**Issue by faker007** [facebook/react-native#41438]
### Description

Hi, folks. I'm facing weird issue about restarting when some android devices are on the background.

Firstly, I've suspected maybe, it is caused by  low-memory issue?

But, It seems like to not.

My company has 3 test android phones.

1. Galaxy A12 (Android 12) (RAM: 3GB)
2. Galaxy S22+ (Android 13) (RAM: 8GB)
3. Galaxy Zlip 5G (Android 13) (RAM: 8GB)

And it is reproducible on 1, 3. Not 2. 

So, I thought it is not about low-memory things.

I'm running for the sliver bullet on this problem, almost a week... 

But none of that doesn't work.

# What I found
## It is maybe related to `react-native-screens`
* The doc of `react-native-screens` says that

```
  // Before
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
  }
```  

```
  // After
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(null);
  }
```

### For summary, 

* `Before` code, app is just stopped. when the app is on the background, and making it foreground.
* `After` code, app is just restarted. when the app is on the background, and making it foreground.

* So, I have gut feeling about `Bundle savedInstanceState`... and that is the key. (Maybe I'm wrong...)
* (Or, I just did misunderstand about lifecycle of Android)

# What I want eventually
* I want to persist the what as is, when foreground -> background -> foreground.

Thanks for reading and every opinions are welcome!

Cheers,
Jin.

P. S. Just let me know if I missed the template, typo, or most importantly solving problem! 

### React Native Version

0.72.3

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 87.41 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.8.1
    path: ~/.nvm/versions/node/v19.8.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Desktop/KatchersApp/node_modules/.bin/yarn
  npm:
    version: 9.5.0
    path: ~/.nvm/versions/node/v19.8.1/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/gyejinlee/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.2
    System Images:
      - android-27 | Google APIs ARM 64 v8a
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google APIs ARM 64 v8a
      - android-30 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: 25.2.9519653
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/gyejinlee/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1. Please grab the specific real devices like I said Galaxy A12, or Galaxy ZFlip 5G.
2. Please run the app on the phone.
3. Please hit the button, which makes app to the background.
4. and see app is stopped. 

### Snack, screenshot, or link to a repository

None

**Comment by faker007** [comment]
# Updated
* I profiled by using Locat in Android Studio.

## Case 1. (normal)
*  In this case, the device is Galaxy S22+.
*  Open the app. (Activity state: Created)
*  Hit the background button (Not the back button, Activity state: Saved -> Stopped)
* Open the app from background list, and everything is working as expected

## Case 2. (Seems like not normal)
* In this case, the device is Galaxy A12
* Open the app (Activity state: Created)
* Hit the background button (Not the back button, Activity state: Saved -> Stopped -> **Destroyed**)
* Open the app from background lis, and the app is restarted.

### Deep into Case 2.
* When comes to case 2, I had to set some Android native side code like

```
// <root>/app/src/main/.../MainActivity.java
@Override
protected void onCreate(Bundle savedInstanceState) {
  SplashScreen.show(this);

  if (savedInstanceState != null) {
    savedInstanceState.remove("android:support:fragments");
    savedInstanceState.remove("android:fragments");
  }

  super.onCreate(savedInstanceState);
}

@Override
protected void onSaveInstanceState(Bundle outState) {
  super.onSaveInstanceState(outState);
    if (outState != null) {
      outState.clear();
    }
 }
```
* Without above code, the app is even not restarted.

* I concluded this is happening by Android OS level, and I don't have any control of them for now.
* And I checked the Sentry, I assume, only 15 people is experienced this in 50k people. (Everyone is using Android, and Android 9 ~ 13, almost manufactured by Samsung, various devices.)

* Now, I dont have any ideas where is really coming from.
* I just noted down, hoping this note helps you.

**Comment by Hamidrezana** [comment]
@faker007
I have this problem too.
Did you find any solution?
