### ISSUE TITLE
npx react-native@latest init error installing ruby gems

### ISSUE THREAD

**Issue by maciejwiacek** [facebook/react-native#41433]
### Description

While trying to create a react native CLI app on M1 Mac an error occured while installing Ruby Gems:

> ✖ Installing Ruby Gems
error There was an error while trying to write to
`/Users/maciejwiacek/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions.61581.tmp`.
It is likely that you need to grant write permissions for that path.
✖ Installing Ruby Gems
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=android and follow the React Native CLI QuickStart guide for macOS and iOS.

I tried reinstalling my macos, cocoapods, ruby versions, homebrew, watchman etc.

### React Native Version

0.72.0

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 107.72 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: ~/.nvm/versions/node/v20.8.1/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.0
    path: ~/.nvm/versions/node/v20.8.1/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/maciejwiacek/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /Users/maciejwiacek/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

I did everything what official docs says about creating React Native CLI project. After npx react-native init command I had an error while installing ruby gems.

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/135031892/4abb867c-f6cc-4157-b78e-d757b8225704)

**Comment by BernardoOlisan** [comment]
Did you solve it?
