### ISSUE TITLE
When running the iOS app on an M1 mac, `getInitialURL` does not work

### ISSUE THREAD

**Issue by nmalzieu** [facebook/react-native#41447]
### Description

When running the iOS version on an M1 Mac (using Mac (designed for iPad) option in XCode)

Deep links do not work when the app is killed i.e. `getInitialURL()` always returns empty string even if the app was opened using a deep link.

(If the app is already opened, the `addEventListener` `url` is called as usual)

### React Native Version

0.72.5

### Output of `npx react-native info`

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 433.00 MB / 16.00 GB
  Shell:
    version: 3.6.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 18.18.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.17
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.9.1
    path: ~/Documents/Projets/converse/app/node_modules/.bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/noemalzieu/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "30"
    Build Tools:
      - 30.0.3
    System Images:
      - android-30 | Google APIs Intel x86 Atom_64
      - android-32 | Google APIs ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/noemalzieu/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.5
    wanted: ^0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Create a RN application and build it for M1 Mac in Xcode using the "Mac (Designed for iPad)" option.

Open the app via a custom scheme link while it's killed.

The `getInitialURL` method returns an empty string while it should contain the link used to open the app.

### Snack, screenshot, or link to a repository

Here is the example repo : https://github.com/nmalzieu/deeplinkmacos

I added the following custom scheme : `noedeeplinkmacos`
If I build for iOS & kill the app then click on the following link : `noedeeplinkmacos://test-deeplink` - it opens the app with the following screen:

<img width="480" alt="Capture d’écran 2023-11-13 à 13 48 29" src="https://github.com/facebook/react-native/assets/2102342/351cdb6b-57ba-497c-8e59-fdcbf68bf96a">

I then build for Mac (Designed for iPad) : NB I modified the scheme to "Wait for the executable to be launched". I then click on the same deeplink and here is what I get:

<img width="1031" alt="Capture d’écran 2023-11-13 à 13 50 07" src="https://github.com/facebook/react-native/assets/2102342/787da10f-da18-4324-8047-218688479336">

However you can see that following clicks do trigger a linking event : 

<img width="1024" alt="Capture d’écran 2023-11-13 à 13 53 16" src="https://github.com/facebook/react-native/assets/2102342/3540c6b7-a76b-4f88-be75-76014069a8bc">

So it's only the initial URL that doesn't get filled on Mac.

**Comment by MatheusLima7** [comment]
same problem

**Comment by fahad86** [comment]
Hoping that this issue is looked into.. Now that Mac apps are becoming more and more popular

**Comment by fahad86** [comment]
@mdvacca @sammy-SC @rubennorte can this issue be re-opened? What do you guys think?

**Comment by fahad86** [comment]
@react-native-bot with many iterations of Macs with Apple Silicon already released and Mac Apps being more and more popular nowadays, I think it would be crucial for this issue to be fixed now. Do re-open this issue.
