### ISSUE TITLE
[IOS] Touchable consume 800ms+ on my iphone6 ...

### ISSUE THREAD

**Issue by RandyZ** [facebook/react-native#4146]
I do this after ListView item clicked.
```javascript
<TouchableOpacity onPress={(eventObj)=>this._onItemClick(eventObj, thisStory)}>
```

```javascript
_onItemClick: function(event, story) {
   PlayingStory = story;
   NativeMethodSet.playStory(story, (error, curStory)=>{
     MoudleBean.setState({
       PlayerStatus:curStory
     });
   });
},
```
It take about 800ms+. When Continuous quick click, the RCTRootView looks like dead, and not reponse other touch event.Should i call the setState to change other views perform? Or there is some other idea to do this?

**Comment by hufeng** [comment]
try,
```javascript
_onItemClick: function(event, story) {
  this.requestAnimationFrame(() => {
     PlayingStory = story;
     NativeMethodSet.playStory(story, (error, curStory)=>{
         MoudleBean.setState({
             PlayerStatus:curStory
         });
     });
  });
}
```

**Comment by RandyZ** [comment]
@hufeng Thanks,but it's not work. I try to delete setState,it works perfectly. I think it maybe refrence to refresh ui.

**Comment by hufeng** [comment]
@RandyZ  :+1:

**Comment by grabbou** [comment]
Closing as @RandyZ mentioned "it works perfectly" w/o the content, so event is dispatched correctly. Please reopen if we have closed this by a mistake!
