### ISSUE TITLE
TextView not working with dynamically heights in React Native Fabric

### ISSUE THREAD

**Issue by RalissonMattias** [facebook/react-native#41476]
### Description

I'm trying to create a native fabric component, basically the component needs to show a TextView with spannable, but the automatically height not working. I try to set a layoutParam to WRAP_CONTENT but seems the React Native override my height. I hope that the height adjust with the content

### React Native Version

0.72.6

### Output of `npx react-native info`

```
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M2
  Memory: 63.08 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 10.2.1
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/ralissonmattias/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/ralissonmattias/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Steps to reproduce

1. Create a new fabric component with: `npx create-react-native-library@latest react-native-awesome-module`
2. Simulate my code

My native view:

```kotlin
package com.textwithdynamicheight

import android.content.Context
import android.util.AttributeSet
import android.view.ViewGroup
import androidx.appcompat.widget.AppCompatTextView

class TextWithDynamicHeightView : AppCompatTextView {
  constructor(context: Context?) : super(context!!)
  constructor(context: Context?, attrs: AttributeSet?) : super(context!!, attrs)
  constructor(context: Context?, attrs: AttributeSet?, defStyleAttr: Int) : super(
    context!!,
    attrs,
    defStyleAttr
  )

  init {
    text = "MY VIEW TEST"

    layoutParams = ViewGroup.LayoutParams(200, 200)
    requestLayout()
  }
}

```

My React Native component
```
import * as React from 'react';

import { StyleSheet, View } from 'react-native';
import { TextWithDynamicHeightView } from 'react-native-text-with-dynamic-height';

export default function App() {
  return (
    <View style={styles.container}>
      {/* NOT WORKING */}
      <TextWithDynamicHeightView />

      {/*  WORKING */}
      <TextWithDynamicHeightView style={styles.box} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: 60,
    height: 60,
    marginVertical: 20,
  },
});

```

### Snack, code example, screenshot, or link to a repository
[Repo](https://github.com/RalissonMattias/text-with-dynamic-height)

**Comment by javache** [comment]
React Native custom components do not use the Android system for Layout. You'll need to implement a ShadowNode to make it participate in the yoga layout process.

**Comment by Ralisson-Mattias** [comment]
> React Native custom components do not use the Android system for Layout. You'll need to implement a ShadowNode to make it participate in the yoga layout process.

Thanks man. Do you have some examples?

**Comment by javache** [comment]
Old architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/progressbar/ProgressBarShadowNode.java#L58

New architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/react/renderer/components/progressbar/android/react/renderer/components/progressbar/AndroidProgressBarShadowNode.cpp#L29

**Comment by RalissonMattias** [comment]
> Old architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/progressbar/ProgressBarShadowNode.java#L58
> 
> New architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/react/renderer/components/progressbar/android/react/renderer/components/progressbar/AndroidProgressBarShadowNode.cpp#L29

Thanks, I'll try

**Comment by RalissonMattias** [comment]
> Old architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/progressbar/ProgressBarShadowNode.java#L58
> 
> New architecture: https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/react/renderer/components/progressbar/android/react/renderer/components/progressbar/AndroidProgressBarShadowNode.cpp#L29

Do you have a kotlin reference in new architecture?

**Comment by javache** [comment]
No, these components haven't been migrated to Kotlin yet.

**Comment by NiuGuohui** [comment]
@javache Is there more detailed documentation or tutorials to help developers familiarize themselves with how to build custom native views of dynamic sizes?
Can Codegen help me with these heavy duty tasks?

**Comment by deepak-dpt** [comment]
I think it should have been mentioned in the documentation that you'll have to implement a ShadowNode if you want a dynamically sized view to be part of yoga layout process. I've been struggling for days trying to figure out why my custom text view is not resizing when the text content is changed.
