### ISSUE TITLE
Inability to network recovery during seamless WiFi switching

### ISSUE THREAD

**Issue by TallNutAlt** [facebook/react-native#41475]
### Description

https://github.com/facebook/react-native/assets/109561878/2dadcde9-e940-4cc8-b846-3ee558838b4b

Android has an intelligent feature for selecting the best WiFi. When WiFi sends a seamless switch, the network seamlessly recovers, as shown in the video for over 20 seconds. After WiFi sends a seamless switch, the network seamlessly recovers only when WiFi is turned off and restarted

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: Windows 11 10.0.22621
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
  Memory: 3.08 GB / 15.73 GB
Binaries:
  Node:
    version: 18.17.0
    path: D:\SDK\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.6.7
    path: D:\SDK\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.8
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

After an Android phone automatically and seamlessly switches to another WiFi in two WiFi environments, the network cannot be restored and is unavailable

### Snack, screenshot, or link to a repository

https://github.com/16638964387/AwesomeProject

**Comment by 16638964387** [comment]
We discovered this issue during the project testing process and consulted relevant personnel. Finally, we initialized a new project using only a Scrollview tag and a dropdown refresh fetch request. Then we conducted testing and found that this issue could also be replicated in an empty project, and submitted this issue
