### ISSUE TITLE
SliderIOS not work when set state ,the position does not change

### ISSUE THREAD

**Issue by liubobo** [facebook/react-native#4147]
'use strict';
var React = require('react-native');
var {
  SliderIOS,
  Text,
  StyleSheet,
  View,
} = React;
var SliderExample = React.createClass({
  getInitialState() {
    return {
      value: 0,
    };
  },
  componentDidMount:function () {
    // body...

    setInterval(() => {
              this.setState({
                  value: 6
              });
          }, 500);

  },
  render() {
    return (
      <View>
        <Text style={styles.text} >
          {this.state.value}
        </Text>
        <SliderIOS
          style={styles.slider}
          ref ={'slider'}
          onValueChange={(value) => this.setState({value: value})} />
      </View>
    );
  }
});
var styles = StyleSheet.create({
  slider: {
    height: 10,
    margin: 10,
  },
  text: {
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '500',
    margin: 10,
  },
});
 module.exports = SliderExample

**Comment by skv-headless** [comment]
could you put your code inside ``` brackets https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by liubobo** [comment]
SliderIOS can change value by  setstate     onValueChange={(value) => this.setState({value: value})}

**Comment by liubobo** [comment]
'use strict';

var React = require('react-native');
var {
  SliderIOS,
  Text,
  StyleSheet,
  View,
} = React;

var SliderExample = React.createClass({
  getInitialState() {
  	
	setInterval(() => {
	this.setState({
		value: 6
	});
}, 500);

    return {
      value: 0,
    };
  },
  render() {
    return (
      <View>
        <Text style={styles.text} >
          {this.state.value}
        </Text>
        <SliderIOS
          {...this.props}
          onValueChange={(value) => this.setState({value: value})} />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  slider: {
    height: 10,
    margin: 10,
  },
  text: {
    fontSize: 14,
    textAlign: 'center',
    fontWeight: '500',
    margin: 10,
  },
});

**Comment by christopherdro** [comment]
@liubobo Were you able to resolve this issue?

**Comment by liubobo** [comment]
i use react-native-slider replace

**Comment by christopherdro** [comment]
@liubobo Could you please close out this issue if you were able to find a solution? Thanks!
