### ISSUE TITLE
Requiring images with 0.14.2

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#4148]
With the new image asset system, there seemed to be a bug when requiring an asset as follows (yes I made sure both the folder containing the png and the png itself had all lowercase):

require('../../../img/goldbadgeicon/goldbadgeicon.png');

I get an unable to resolve module... error.

When I change the folder containing the png to something else in the require statement AND the actual directory, the error disappears (and the image appears correctly):

require('../../../img/goldBadgeIcon/goldbadgeicon.png');

I suspect it may have something to do with the similarly named folder and file name? Weirdly, this only occurs on some images and not on others. Putting this up here in case anyone has similar issues and to see if this really is a bug or not.

**Comment by nlhkh** [comment]
I am seeing the same issue

**Comment by mkonicek** [comment]
Is this on Windows?

**Comment by mkonicek** [comment]
Can you try a recent version of RN?

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
