### ISSUE TITLE
[Android] Item list bounced back and forth when I use FlatList horizontal data dynamically (ScrollView also)

### ISSUE THREAD

**Issue by on29-dev** [facebook/react-native#41492]
### Description

Item list bounced back and forth when I use FlatList horizontal data dynamically and after changing data I scroll the list horizontally. Especially this occurs when changing data from large enough to require scrolling to small enough data to not require scrolling.(I use scrollToIndex to index 0 when change the data.)

### React Native Version

0.68.5

### Output of `npx react-native info`

System:
    OS: macOS 12.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 59.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
    Watchman: 2023.07.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/on29.biz/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 25, 27, 28, 29, 30, 31, 33
      Build Tools: 25.0.1, 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-31 | Intel x86 Atom_64, android-31 | Google TV Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. Make Flatlist horizontally using dynamic data(state), scrollToIndex(0) 
2. Change data from large enough to require scrolling to small enough data to not require scrolling
3. Scroll left and right a few times.

### video

https://github.com/facebook/react-native/assets/11909001/36ccf3cd-2092-45c3-b1ce-ae32b03e9f34

### code 

```jsx

import React, {useState, useRef} from 'react';
import {
  SafeAreaView,
  View,
  FlatList,
  StyleSheet,TouchableOpacity,
  Text,
  StatusBar,
} from 'react-native';

const DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d72',
    title: 'Third Item',
  },
];
const ADD_DATA = [
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba11',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f6322',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d7233',
    title: 'Third Item',
  },
  {
    id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba44',
    title: 'First Item',
  },
  {
    id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f6355',
    title: 'Second Item',
  },
  {
    id: '58694a0f-3da1-471f-bd96-145571e29d7266',
    title: 'Third Item',
  },
]

type ItemProps = {title: string};

const Item = ({title}: ItemProps) => (
  <View style={styles.item}>
    <Text style={styles.title}>{title}</Text>
  </View>
);

const App = () => {
  const [data, setData] = useState(DATA);
  const flatListRef = useRef(null);
  return (
    <SafeAreaView style={styles.container}>
      <TouchableOpacity
        style={{width: 200, borderWidth:1,}}
        onPress={()=>setData([...data,...ADD_DATA])}>
          <Text>+</Text>
      </TouchableOpacity>
      <TouchableOpacity
              style={{width: 200, borderWidth:1}}
        onPress={()=>{
          setData(DATA)
          flatListRef.current?.scrollToIndex({ index: 0 });
        }}>
        <Text>-</Text>
      </TouchableOpacity>
      <FlatList
        data={data}
        ref={flatListRef}
        horizontal
        renderItem={({item}) => <Item title={item.title} />}
        keyExtractor={item => item.id}
      />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: StatusBar.currentHeight || 0,
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    width:100,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: 32,
  },
});

export default App;
```

**Comment by DevVibhor** [comment]
@on29-dev I've tried your code on Snack. It works fine there, maybe it has got to do something with your device that you are using. Can you try it on some other android/iOS device and see if the issue persists?

**Comment by tamayo7** [comment]
I'm still facing the same issue on version `0.71` and it only happens only on  Android both emulator and device.

**Comment by hieuminh1810** [comment]
same issue on android rn 0.73.2 :(

**Comment by j-s-ott** [comment]
This looks like the same issue as https://github.com/facebook/react-native/issues/36617. I agree that it's limited to Android: I'm seeing it on an emulated Pixel 6 running react-native version `0.72`.

**Comment by evanezent** [comment]
Put some randomize key inside your `ScrollView` every list item value was changed **solved the problem** for me. It seems like the `ScrollView` itself self not resetting its component, so when the list was "long list" and then changed into "short list", the ScrollView still uses the "long list" component for the "short list" rendering.

```js
<ScrollView
        key={some value}
        horizontal
 >
...
</ScrollView>
```

Sorry, I can't explain it technically :(

**Comment by AhsanShihab** [comment]
This is also happening with static data. On horizontal mode, if the data is not long enough to fill the width, this bouncing is happening.
@on29-dev were you able to fix it?

**Comment by ashwinmridul** [comment]
call `flatListRef.current.scrollToEnd()` inside `onEndReached` callback of FlatList to scroll to end whenever you reach to the end because of dynamically remove any item.

Can do more optimisations to restrict calling `scrollToEnd` forcefully everytime the scroll position reaches end of list.

```
<FlatList
    ref={flatListRef}
    onEndReached={() => {
        if (Platform.OS === 'android') flatListRef.current.scrollToEnd();
    }}
/>
```

**Comment by CostasCF** [comment]
Can confirm it's still happening in react-native@0.73.0

**Comment by 810505339** [comment]
https://github.com/facebook/react-native/assets/50100966/04f8baba-eaa0-455c-ba9f-05482d618cfe

it doesn't look normal

**Comment by 810505339** [comment]
> Android.Emulator.-.Pixel_7_Pro_API_34_5554.2024-03-19.23-39-56.mp4 
> 看起来不正常

`react-native 0.73.5`

**Comment by CostasCF** [comment]
At this point,  the only "hacky" solution is to disable the scroll entirely if the items are less than a specified number and viceversa.

**Comment by arche-soft** [comment]
number
