### ISSUE TITLE
Nested Text components do not respect individual transform styles

### ISSUE THREAD

**Issue by bmbmjmdm** [facebook/react-native#41527]
### Description

When nesting Text components, if you try to apply a transform to one of your nested Text components, it will ignore the transform entirely. This issue is visible on Android, not sure about other platforms

### React Native Version

0.72.6

### Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: "(12) x64 AMD Ryzen 5 3600 6-Core Processor              "
  Memory: 6.68 GB / 15.93 GB
Binaries:
  Node:
    version: 16.10.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 7.24.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    Android NDK: 21.0.6113669
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.9862592
  Visual Studio: Not Found
Languages:
  Java: 20.0.2
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Steps to reproduce

Create an app with the following render function, you will see that the text "Hello" is displayed in the center, rather than being spread out across the screen. This issue is visible on Android, not sure about other platforms

export default function App() {
  return (
    <View style={{flex: 1, justifyContent: "center", alignItems: "center"}}>
      <Text>
        <Text style={{transform: [{translateX: 100}, {translateY: 50}]}}>H</Text>
        <Text>e</Text>
        <Text style={{transform: [{translateX: 50}, {translateY: -50}]}}>l</Text>
        <Text style={{transform: [{translateX: 200}, {translateY: 0}]}}>l</Text>
        <Text style={{transform: [{translateX: 0}, {translateY: 200}]}}>o</Text>
      </Text>
    </View>
  )

### Snack, screenshot, or link to a repository

https://snack.expo.dev/vu4R1z0QE

**Comment by fabriziobertoglio1987** [comment]
Do you still experience this issue? If yes, I will publish the fix in the react-native-improved package https://github.com/fabriziobertoglio1987/react-native-improved. Thanks a lot

**Comment by bmbmjmdm** [comment]
Hi yes this is still an issue, thank you!
