### ISSUE TITLE
Mount a reactComponent to a UIKit View

### ISSUE THREAD

**Issue by xiekw2010** [facebook/react-native#4152]
I want use a React component which as:

```ruby
  _topConfigCell(event) {
    const cell = (
      <View
        ref={(textMenu) => this.textMenu = textMenu}
      >
        <Text>
          hello world
        </Text>
      </View>
    )

    const cellNode = React.findNodeHandle(this.textMenu);
    CollectionViewManager.updateCellContentView(2, cellNode, {secion: 1, item: 2})
  },
```
Here i am not using it in `render()` method, just a method of a React component(`_topConfigcell`).

But the `cellNode` could not be found which is `null`.

Is there any possible I could find the cellNode which later I will use in OC method `adUIBlock:`

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
