### ISSUE TITLE
Not latest version of @react-native/metro-config is published

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#41536]
`npm outdated`
![image](https://github.com/facebook/metro/assets/17779660/b8bafbd3-cd57-442b-afb4-4cfbc98e5a77)

I would expect that 0.74.0 is the latest and not last published 0.73.2

**Comment by robhogan** [comment]
(Transferred to `facebook/react-native` because this is an RN-monorepo package versioned and released with RN, not Metro)

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/41587
