### ISSUE TITLE
main.jsbundle does not exist.

### ISSUE THREAD

**Issue by ripon008** [facebook/react-native#41553]
### Description

main.jsbundle does not exist.

### React Native Version

0.72.7

### Output of `npx react-native info`

main.jsbundle does not exist.

### Steps to reproduce

main.jsbundle does not exist.

### Snack, screenshot, or link to a repository

main.jsbundle does not exist.

**Comment by lucaswitch** [comment]
Having this issue on 0.72.7

**Comment by lucaswitch** [comment]
Actually reinstalled whole application and fixed directory permissions and the issue was solved.

**Comment by cortinico** [comment]
Closing as invalid

**Comment by ripon008** [comment]
how to fix?
