### ISSUE TITLE
[Image] Image meta data from images with the same name conflict during packaging

### ISSUE THREAD

**Issue by Intellicode** [facebook/react-native#4156]
When you have an image that is loaded using the `require('image!back');` syntax, the packager might use the meta data from a similarly named image found in other xcode projects (in my case Google maps). 

```
});
__d('image!back',[],function(global, require, module, exports) {  module.exports = {"__packager_asset":true,"isStatic":true,"path":"/Users/tom/Projects/xxx/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Versions/Current/Resources/GoogleMaps.bundle/back@3x.png","uri":"back","width":12,"height":12,"deprecated":true};
});
```

This bug might not be relevant for the new asset loading system. But I thought it would be good to at least register the bug here for people who use the old asset loading system.

**Comment by browniefed** [comment]
@facebook-github-bot close
