### ISSUE TITLE
Error happened when I run demo on ios 

### ISSUE THREAD

**Issue by DamonsJ** [facebook/react-native#41576]
### Description

[error-info.txt](https://github.com/facebook/react-native/files/13422641/error-info.txt)

I want to create my own native module in IOS , so ,firstly, I set up environment according steps in:
https://reactnative.dev/docs/environment-setup?guide=native&package-manager=npm

after I run : npm run ios
I get many errors, it seems glog can not be compiled !

![image](https://github.com/facebook/react-native/assets/28893028/dc47cfc2-b7ca-4691-b3b9-dccdcde4dc87)

### React Native Version

0.72.7

### Output of `npx react-native info`

➜  iosTest npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 12.4
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 40.46 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.11.13.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/honglei.sun/.rvm/rubies/ruby-2.7.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 15.5
      - macOS 12.3
      - tvOS 15.4
      - watchOS 8.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7935034
  Xcode:
    version: 13.4/13F17a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.1.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.2
    path: /Users/honglei.sun/.rvm/rubies/ruby-2.7.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

(node:50455) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

### Steps to reproduce

1. npx react-native@latest init iosTest 
2. time too long to install hermes, so I stop it and pod install in ios folder using hermes downloaded in my disk, change podfile like this : ENV["HERMES_ENGINE_TARBALL_PATH"]="/Users/xxxx/react-native-artifacts-0.72.7-hermes-ios-debug.tar.gz"
3. cd iosTest
4. cd ios
5. pod install
6. npm run ios

### Snack, screenshot, or link to a repository

![image](https://github.com/facebook/react-native/assets/28893028/c35050f6-4e00-4286-8600-cde30bced6e6)

**Comment by cortinico** [comment]
Please provide the full build log not as an image

**Comment by DamonsJ** [comment]
> Please provide the full build log not as an image

I have provided all the info in description: 
https://github.com/facebook/react-native/files/13422641/error-info.txt

this is all the build log generated, it is too long to display in shell.
