### ISSUE TITLE
node_module folder shows me a bunch of modules...

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#4158]
I am not sure if it is an issue, because my project works fine. But since i moved my project to a new working station (bought me a new macbook pro :dancer: ) the node_module folder shows me a bunch of folders/directories....

![node_module](https://cloud.githubusercontent.com/assets/7880624/11187113/64843a16-8c85-11e5-849a-108994df54b2.png)

Someone with same "issue"

**Comment by MossP** [comment]
Dupe of https://github.com/facebook/react-native/issues/4069#event-465130631 Has been closed as normal behaviour.

@ide, @brentvatne  - another to close. Thanks.

**Comment by ide** [comment]
This is expected because of npm (has nothing to do with React Native, in particular).

**Comment by davidblumer** [comment]
this has nothing to do with react, its because of npm.
