### ISSUE TITLE
Please make @react-native/metro-config version 0.74.0 as latest not 0.73.2

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#41587]
### Description

npm outdated:
![image](https://github.com/facebook/react-native/assets/17779660/d0c6bcfe-574c-4d74-a399-5893b4ca8d43)

https://www.npmjs.com/package/@react-native/metro-config/v/0.74.0

![image](https://github.com/facebook/react-native/assets/17779660/5f5b34f1-de1e-4bd8-937f-6959d7e247e5)
![image](https://github.com/facebook/react-native/assets/17779660/39d977c1-ffd4-4d83-85ad-291bc042d5af)
![image](https://github.com/facebook/react-native/assets/17779660/458f5228-8855-4502-9cad-c4d48170da19)

### React Native Version

0.72.7

### Output of `npx react-native info`

Not important

### Steps to reproduce

npm outdated

### Snack, screenshot, or link to a repository

Not important

**Comment by cortinico** [comment]
That's intended. `latest` mirrors the upcoming stable version of react-native (in this case 0.73).
