### ISSUE TITLE
Native Modules don't support both Callback AND Promise

### ISSUE THREAD

**Issue by mrousavy** [facebook/react-native#41583]
### Description

Hey folks! 
I have a native function "`startRecording()`" in [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera) that needs both a callback and returns a Promise:

```ts
function startRecording(callback: (videoUri: string) => void): Promise<void>
```

The `Promise` resolves once the Camera _started recording_ (probably after ~200ms), and the `callback` gets called once the Camera _stops recording_, which might be after a few seconds or minutes.

However it looks like both Callback and Promise are not supported with the React Native Bridge - is that a known bug?

In short:

1. This works
    ```objc
    RCT_EXTERN_METHOD(startRecording:(nonnull NSNumber*)node
                      onRecordCallback:(RCTResponseSenderBlock)onRecordCallback);
    ```
2. This works
    ```objc
    RCT_EXTERN_METHOD(startRecording:(nonnull NSNumber*)node
                      resolve:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject);
    ```
3. This does not work
    ```objc
   RCT_EXTERN_METHOD(startRecording:(nonnull NSNumber*)node
                      onRecordCallback:(RCTResponseSenderBlock)onRecordCallback
                      resolve:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject);
    ```

Instead, it gives me the following error when I try to call that native function:

<img src="https://github.com/facebook/react-native/assets/15199031/497ba437-e6c4-4e48-8478-874525d32de4" width="45%" />

### React Native Version

0.72.7

### Output of `npx react-native info`

```
info Fetching system and libraries information...
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 64.09 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2023.11.13.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /opt/homebrew/opt/openjdk@11/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Create a native module (or use an existing one)
2. Create a method that accepts both a callback and a Promise, like so:
    ```objc
   RCT_EXTERN_METHOD(startRecording:(nonnull NSNumber*)node
                      onRecordCallback:(RCTResponseSenderBlock)onRecordCallback
                      resolve:(RCTPromiseResolveBlock)resolve
                      reject:(RCTPromiseRejectBlock)reject);
    ```
    (or use a ObjC method instead of an EXTERN Swift one)
3. Call that from JS

### Snack, screenshot, or link to a repository

https://github.com/mrousavy/react-native-vision-camera 

here's said method: 

- ObjC: https://github.com/mrousavy/react-native-vision-camera/blob/deb3c41ee0a55e64cbb83ead912ccdd53d10988f/package/ios/CameraViewManager.m#L61-L64
- Swift: https://github.com/mrousavy/react-native-vision-camera/blob/deb3c41ee0a55e64cbb83ead912ccdd53d10988f/package/ios/CameraViewManager.swift#L41-L49
- JS: https://github.com/mrousavy/react-native-vision-camera/blob/deb3c41ee0a55e64cbb83ead912ccdd53d10988f/package/src/Camera.tsx#L151-L185

**Comment by mrousavy** [comment]
Issue still persists on react-native 0.72.7, just confirmed.

I can see that the cause of the issue is that `NativeModules.genMethod(...)` here either creates a `promise` method, or an `async`/`sync` method: https://github.com/facebook/react-native/blob/ce0dabddf369587311198290b5bfc8e058a39a28/packages/react-native/Libraries/BatchedBridge/NativeModules.js#L98-L162

An `async`/`sync` method has two trailing callbacks, a success callback (`onSuccess`) and error (`onFail`, this is optional).

I'm not sure - is this something that could be supported? If yes, I can create a PR and try to make it non breaking.

**Comment by vhakulinen** [comment]
This should be documented. I just spent half a day to figuring out why my _second_ callback isn't called. To make matters worse, the logged error suggest that the second callback would already be called.
