### ISSUE TITLE
Android rootTag value implementation is broken on RN 0.72.x

### ISSUE THREAD

**Issue by ergenekonyigit** [facebook/react-native#41584]
### Description

Before RN 0.71, the root tag value increased by ten on every bundle reload. After upgrading to RN 0.72 this value was broken on Android. iOS versions working as expected. 

### React Native Version

0.72.7

### Output of `npx react-native info`

```
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 73.66 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 8.10.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 34.0.0
    System Images:
      - android-30 | Google APIs ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-32 | Google Play ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/<username>/.rvm/rubies/ruby-2.7.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

- Create a new project with this script
```
npx react-native init AwesomeProject
```
- Run android 

### Snack, screenshot, or link to a repository

**Working on 0.70.x**

https://github.com/facebook/react-native/assets/7110136/f759d90e-2816-4d07-8f86-8c1a0971c841

**Broken on 0.71.x**

https://github.com/facebook/react-native/assets/7110136/70b637ab-dc77-4ac3-900c-6a58065e7bdb

**Broken on 0.72.x**

https://github.com/facebook/react-native/assets/7110136/b2861512-507b-4e0e-9a40-1525ae2da20c

**Comment by gokselpirnal** [comment]
maybe related to the change https://github.com/facebook/react-native/commit/4d642a2250251d90d4afec8e81bf19848217c3f6

**Comment by ergenekonyigit** [comment]
We have a feature that depends on this rootTag value just like the Facebook app. We can adapt our feature based on this behavior, but this commit created an inconsistency between iOS and Android. I think it should work like pre-71 on both platforms.

**Comment by ergenekonyigit** [comment]
We show a special splash screen on the first app open. This screen only appears at `rootTag === 1` condition. Also, we use react-native-restart in some cases, this special splash screen should not appear on restarting moments.

**Comment by cortinico** [comment]
> We show a special splash screen on the first app open

You should hold a state to know when is the first app open. You should not rely on implementation details of React Native.

**Comment by ergenekonyigit** [comment]
You are right, we departed our implementation from rootTag. But triggering the increment rootTag method twice on Android is still a problem. This is why I opened this issue.

**Comment by cortinico** [comment]
> But triggering the increment rootTag method twice on Android is still a problem

Yes it is, but it's not a user facing regression. So we'll keep it open till someone can look into it.
