### ISSUE TITLE
THUMB_URLS of Examples are not anymore available.

### ISSUE THREAD

**Issue by bozzmob** [facebook/react-native#4159]
Hi,

In the following files, the **THUMB_URLS** links are broken -
ListViewGridLayoutExample.js
ListViewExample.js
ListViewPagingExample.js

They throw 5xx server error. I would be glad to fix this with a pull request. But, would like to have the source of URL's. If any good source URL for 128x128 images are ok, I do it right away with what I am using now. Let me know @ide  and other contributors.
```
var THUMB_URLS = [
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851549_767334479959628_274486868_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851561_767334496626293_1958532586_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851579_767334503292959_179092627_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851589_767334513292958_1747022277_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851563_767334559959620_1193692107_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851593_767334566626286_1953955109_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851591_767334523292957_797560749_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851567_767334529959623_843148472_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851548_767334489959627_794462220_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851575_767334539959622_441598241_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-ash3/t39.1997/p128x128/851573_767334549959621_534583464_n.png',
  'https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/t39.1997/p128x128/851583_767334573292952_1519550680_n.png',
];
```

**Comment by ide** [comment]
@vjeux any ideas what these URLs were? We should probably use imgur or github images.

**Comment by bozzmob** [comment]
@ide @vjeux At least I see by checking out google history, one of them was a like button. Were they smiley’s or something?

**Comment by bozzmob** [comment]
I will take care of this in the next few hours. Thanks @vjeux and @ide

**Comment by mrcasals** [comment]
Solved by https://github.com/facebook/react-native/commit/6e01c514d2ca7e1ab10e94c04822c183825ba5e3, this can be closed :)

**Comment by ide** [comment]
The image files are empty for some reason. Might be the sync bot not being able to handle non-text files cc @vjeux

**Comment by bozzmob** [comment]
Closing this issue as the commit was checked in and works fine
