### ISSUE TITLE
Linking.sendIntent encodes all numeric extras as Double and not Integer

### ISSUE THREAD

**Issue by lucasloisp** [facebook/react-native#41615]
### Description

We're guiding our Android users to set up their Biometrics, using the [ACTION_BIOMETRIC_ENROLL](https://developer.android.com/reference/android/provider/Settings#ACTION_BIOMETRIC_ENROLL) intent. Because we want to use it on the keystore, we require Class 3 biometrics, determined by an Extra Integer on the intent, [EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED](https://developer.android.com/reference/android/provider/Settings#EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED) with value [BIOMETRIC_STRONG = 15](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager.Authenticators#BIOMETRIC_STRONG).

Because this is a number, sendIntent codes it up as a Double (known behavior, code comments in code point to #4141), but Android fails, with the warning `ClassCastException: java.lang.Double cannot be cast to java.lang.Integer`, on the `BiometricEnrollActivity`.

Doing `adb shell am start -a android.settings.BIOMETRIC_ENROLL --ei android.provider.extra.BIOMETRIC_AUTHENTICATORS_ALLOWED 15` works without warning, due to the type being an Integer.

Logcat output:
```
11-22 21:01:29.848 20250 20250 W Bundle  : Attempt to cast generated internal exception:
11-22 21:01:29.848 20250 20250 W Bundle  : java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1255)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.content.Intent.getIntExtra(Intent.java:9446)
11-22 21:01:29.848 20250 20250 W Bundle  :      at com.android.settings.biometrics.BiometricEnrollActivity.onCreate(BiometricEnrollActivity.java:179)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.Activity.performCreate(Activity.java:8591)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.Activity.performCreate(Activity.java:8570)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:106)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.os.Looper.loopOnce(Looper.java:226)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.os.Looper.loop(Looper.java:313)
11-22 21:01:29.848 20250 20250 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:8757)
11-22 21:01:29.848 20250 20250 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
11-22 21:01:29.848 20250 20250 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-22 21:01:29.848 20250 20250 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Issue looks to be here: https://github.com/facebook/react-native/blob/072a2006e0bd8bd8cc9a75385cc03759bcf63c61/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/intent/IntentModule.java#L232

### React Native Version

0.72.7

### Output of `npx react-native info`

```
System:
  OS: Linux 6.5 Pop!_OS 22.04 LTS
  CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Memory: 1.96 GB / 7.51 GB
  Shell:
    version: 3.6.1
    path: /usr/bin/fish
Binaries:
  Node:
    version: 18.14.0
    path: ~/.nvm/versions/node/v18.14.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.14.0/bin/yarn
  npm:
    version: 9.3.1
    path: ~/.nvm/versions/node/v18.14.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.9971841
Languages:
  Java: Not Found
  Ruby:
    version: 3.0.2
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

Use `Linking.sendIntent` to open a BIOMETRIC_ENROLL intent with the BIOMETRIC_STRONG extra,

```
import React from 'react';
import {SafeAreaView, View, Button, Linking} from 'react-native';

const ACTION_BIOMETRIC_ENROLL = 'android.settings.BIOMETRIC_ENROLL';
const EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED =
  'android.provider.extra.BIOMETRIC_AUTHENTICATORS_ALLOWED';
const BIOMETRIC_STRONG = 15;

function App(): JSX.Element {
  const onPress = () => {
    Linking.sendIntent(ACTION_BIOMETRIC_ENROLL, [
      {key: EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED, value: BIOMETRIC_STRONG},
    ]);
  };
  return (
    <SafeAreaView>
      <View>
        <Button onPress={onPress} title="Send Intent" />
      </View>
    </SafeAreaView>
  );
}

export default App;
```

### Snack, screenshot, or link to a repository

https://snack.expo.dev/@lucasloisp/linking-sendintent-has-extra-integer-as-double

**Comment by lucasloisp** [comment]
Behavior this bug produces, is that if the user has a Biometric method setup that is **not** `BIOMETRIC_STRONG` (e.g. Face Recognition), then, because Android fails to parse `EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED` argument, the user will not get prompted to set up fingerprints.

<img width="300" src="https://github.com/facebook/react-native/assets/3135138/e116de64-964b-4961-80f6-0b11f5d973c3" />

*With "Face Recognition" set up, button does nothing*

https://github.com/facebook/react-native/assets/3135138/0e0b7e48-1834-4053-a521-bc0a880be3c7


*With No Method set up, button takes the user to fingerprint, because that is the default* 

https://github.com/facebook/react-native/assets/3135138/8c471e12-94a8-405a-8b79-c2929c187690

Note: blank screen in the middle is the passcode step.

**Comment by lucasloisp** [comment]
Given Numbers are no more specific than that at the JS level, perhaps an option would be to change the API for sendIntent, and receive, at least optionally, a way to "tag" a number as integer - and it can fail if it's not, or round down.

```ts
Linking.sendIntent(ACTION_BIOMETRIC_ENROLL, [
  {key: EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED, value: BIOMETRIC_STRONG, type: 'integer'},
]);
```

Problem here is we open `type` to also take `double`, `boolean`, etc. - and I'd rather keep those "inferred" from the type of `value`. 

Maybe an `isInteger: boolean` flag? Would only take effect if `typeof value === 'number'`

**Comment by gabimoncha** [comment]
@lucasloisp i ended up using expo's [IntentLauncher](https://docs.expo.dev/versions/latest/sdk/intent-launcher/)
