### ISSUE TITLE
cant able to run app in ios simulator after upgrading to xcode 15.0.1 from 14.3.1

### ISSUE THREAD

**Issue by SVN-05** [facebook/react-native#41619]
### Description

The following build commands failed:
        CompileC /Users/vc/Library/Developer/Xcode/DerivedData/VoxGuru-hdqormiuaohjswcekdtxhjxszfyv/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RCT-Folly.build/Objects-normal/x86_64/json.o /Users/vc/CycesProjects/VoxGuruApp/ios/Pods/RCT-Folly/folly/json.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RCT-Folly' from project 'Pods')
(1 failure)

### React Native Version

0.69.6

### Output of `npx react-native info`

System:
    OS: macOS 14.1.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 547.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    Watchman: 2023.09.25.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

updating macos from 13 to 14, installing xocde 15.0.1 and it's build tools, iphone 15 simulator. and trying to run ios app

### Snack, screenshot, or link to a repository

https://github.com/facebook/react-native/issues/39743

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/39568
