### ISSUE TITLE
RCTRootView.h file not found

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#4164]
I've found several posts regarding this issue but my problem seems different. At first I installed react native and tested the example programs which worked fine. Then I created my own projects which also worked fine. But after creating my own projects the example projects stopped working and returned the error: "Naming collision detected" upon trying to start npm.

It seems the node modules in the react-native root folder are clashing with the node modules in the folders for the individual projects I've created. Of course the projects were created automatically but I'm not sure why they're different to the examples. Also not sure why it seems to be set up to create a clashing problem.

**Comment by hufeng** [comment]
npm install

**Comment by hasen6** [comment]
Is that the end of your post? Did you mean to just write that? Yes obviously I have npm installed..

**Comment by christopherdro** [comment]
@hufeng You need to make sure that none of your custom modules specify react-native as a dependency. Check the node_modules directories from your custom modules and make sure there isn't a copy of react-native in there.

**Comment by christopherdro** [comment]
@hufeng Closing this for now since it's been inactive for a week. Please report back if you are still have problems. Thanks!
