### ISSUE TITLE
-sourcemap-output path containing spaces in Xcode projects results in no sourcemaps

### ISSUE THREAD

**Issue by JorenVos** [facebook/react-native#41652]
### Description

See https://github.com/facebook/react-native/pull/40937

Fix is already provided, needs to be merged. 

### React Native Version

0.71.0

### Output of `npx react-native info`

https://github.com/facebook/react-native/pull/40937

### Steps to reproduce

See https://github.com/facebook/react-native/pull/40937

### Snack, screenshot, or link to a repository

Fix provided in https://github.com/facebook/react-native/pull/40937.  Needs to be merged.

**Comment by cortinico** [comment]
See also:
- https://github.com/facebook/react-native/issues/41844
- https://github.com/facebook/react-native/pull/41845

**Comment by cortinico** [comment]
Closing as fix has been merged in 0.74.x
