### ISSUE TITLE
Firebase crash - IOS - Fatal Exception: NSMallocException Failed to grow buffer

### ISSUE THREAD

**Issue by VinothEI** [facebook/react-native#41651]
### Description

Fatal Exception: NSMallocException
0  CoreFoundation                 0x92c80 __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreFoundation                 0x19174c -[NSInvocation retainArguments].cold.1
3  CoreFoundation                 0x18a3a4 __CFReallocationFailed
4  CoreFoundation                 0x30f9c __CFSafelyReallocate
5  Foundation                     0x36f24 _NSMutableDataGrowBytes
6  Foundation                     0x32d50 -[NSConcreteMutableData appendBytes:length:]
7  Foundation                     0x786b8 __49-[_NSDispatchData enumerateByteRangesUsingBlock:]_block_invoke
8  Foundation                     0x7abf8 -[_NSDispatchData enumerateByteRangesUsingBlock:]
9  Foundation                     0x6101c -[NSConcreteMutableData appendData:]
10 CommonApp_name                      0x22bd40 -[RCTNetworkTask URLRequest:didReceiveData:] + 168 (RCTNetworkTask.mm:168)
11 CommonApp_name                      0x226764 -[RCTHTTPRequestHandler URLSession:dataTask:didReceiveData:] + 171 (RCTHTTPRequestHandler.mm:171)
12 CFNetwork                      0x606c4 CFHTTPCookieStorageCreateFromFile
13 Foundation                     0x4e39c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
14 Foundation                     0x5fa70 -[NSBlockOperation main]
15 Foundation                     0x39a8c __NSOPERATION_IS_INVOKING_MAIN__
16 Foundation                     0x49fcc -[NSOperation start]
17 Foundation                     0x4d498 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
18 Foundation                     0x5accc __NSOQSchedule_f
19 libdispatch.dylib              0x11544 _dispatch_block_async_invoke2
20 libdispatch.dylib              0x64094 _dispatch_client_callout
21 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp
22 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp
23 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread
24 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
25 libsystem_pthread.dylib        0x193c start_wqthread

### React Native Version

0.72.6

### Output of `npx react-native info`

IOS crash .
this system details of mine.
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 78.80 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Its a firebase crash, not able to reproduce.

### Snack, screenshot, or link to a repository

<img width="1146" alt="Screenshot 2023-11-27 at 1 40 30 PM" src="https://github.com/facebook/react-native/assets/121219032/df5dd135-74ee-44ee-8d94-5d0d4b55c9b6">

**Comment by cortinico** [comment]
We can't debug firebase crashes. Please provide a reproducer or we can't help further

**Comment by VinothEI** [comment]
**It is crashed below way, but am not able to recreate. After updating RN 0.72.6, am getting this crash on IPAD OS 15**

Fatal Exception: NSMallocException
0  CoreFoundation                 0x92c80 __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  CoreFoundation                 0x19174c -[NSInvocation retainArguments].cold.1
3  CoreFoundation                 0x18a3a4 __CFReallocationFailed
4  CoreFoundation                 0x30f9c __CFSafelyReallocate
5  Foundation                     0x36f24 _NSMutableDataGrowBytes
6  Foundation                     0x32d50 -[NSConcreteMutableData appendBytes:length:]
7  Foundation                     0x786b8 __49-[_NSDispatchData enumerateByteRangesUsingBlock:]_block_invoke
8  Foundation                     0x7abf8 -[_NSDispatchData enumerateByteRangesUsingBlock:]
9  Foundation                     0x6101c -[NSConcreteMutableData appendData:]
10 CommonMyApp_name  0x22bd40 -[RCTNetworkTask URLRequest:didReceiveData:] + 168 (RCTNetworkTask.mm:168)
11 CommonMYApp_name  0x226764 -[RCTHTTPRequestHandler URLSession:dataTask:didReceiveData:] + 171 (RCTHTTPRequestHandler.mm:171)
12 CFNetwork                      0x606c4 CFHTTPCookieStorageCreateFromFile
13 Foundation                     0x4e39c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
14 Foundation                     0x5fa70 -[NSBlockOperation main]
15 Foundation                     0x39a8c __NSOPERATION_IS_INVOKING_MAIN__
16 Foundation                     0x49fcc -[NSOperation start]
17 Foundation                     0x4d498 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
18 Foundation                     0x5accc __NSOQSchedule_f
19 libdispatch.dylib              0x11544 _dispatch_block_async_invoke2
20 libdispatch.dylib              0x64094 _dispatch_client_callout
21 libdispatch.dylib              0xa73c _dispatch_lane_serial_drain$VARIANT$mp
22 libdispatch.dylib              0xb1f4 _dispatch_lane_invoke$VARIANT$mp
23 libdispatch.dylib              0x14ec8 _dispatch_workloop_worker_thread
24 libsystem_pthread.dylib        0x1e10 _pthread_wqthread
25 libsystem_pthread.dylib        0x193c start_wqthread
