### ISSUE TITLE
StatusBarManager.HEIGHT not working on Fabric Android

### ISSUE THREAD

**Issue by vincentmegia** [facebook/react-native#41663]
### Description

Created a clean project, 
enable new architecture in gradle.properties
Native module StatusBarManager.HEIGHT stops working or not even defined.

```
import React from 'react';
import {NativeModules, Text} from 'react-native'
const App = () => {
  return (
  <>
    <Text>Value of status bar manager height {NativeModules.StatusBarManager.HEIGHT}</Text>
  </>
  );
}
```

export default App;

### React Native Version

0.72.7

### Output of `npx react-native info`

System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M2
  Memory: 73.55 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.6.1
    path: ~/Repository/tools/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v19.8.0/bin/yarn
  npm:
    version: 9.8.1
    path: ~/Repository/tools/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/p1337452/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "23"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
    System Images:
      - android-23 | Google APIs ARM 64 v8a
      - android-29 | ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/p1337452/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

1) Create fresh react-native project
2) Use NativeModules.StatusBarManager.HEIGHT

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by maksymhcode-care** [comment]
Please check this

**Comment by maksymhcode-care** [comment]
@cortinico Can this be reviewed?

**Comment by cortinico** [comment]
You can achieve the same behaivor on New Architecture with:

```js
import {Text, StatusBar} from 'react-native';

function MyComponent() {
  return (
    <Text>{StatusBar.currentHeight}</Text>
  );
}
```

**Comment by maksymhcode-care** [comment]
> You can achieve the same behaivor on New Architecture with:
> 
> ```js
> import {Text, StatusBar} from 'react-native';
> 
> function MyComponent() {
>   return (
>     <Text>{StatusBar.currentHeight}</Text>
>   );
> }
> ```

Big thank you

**Comment by Romick2005** [comment]
> You can achieve the same behaivor on New Architecture with:
> 
> ```js
> import {Text, StatusBar} from 'react-native';
> 
> function MyComponent() {
>   return (
>     <Text>{StatusBar.currentHeight}</Text>
>   );
> }
> ```

Is there any plans to [have it on iOS](https://github.com/facebook/react-native/blob/0d5c02656904ba53e12b13e54060f9476f63dc44/packages/react-native/Libraries/Components/StatusBar/StatusBar.js#L235) also?

**Comment by maksymhcode-care** [comment]
> > You can achieve the same behaivor on New Architecture with:
> > ```js
> > import {Text, StatusBar} from 'react-native';
> > 
> > function MyComponent() {
> >   return (
> >     <Text>{StatusBar.currentHeight}</Text>
> >   );
> > }
> > ```
> 
> Is there any plans to [have it on iOS](https://github.com/facebook/react-native/blob/0d5c02656904ba53e12b13e54060f9476f63dc44/packages/react-native/Libraries/Components/StatusBar/StatusBar.js#L235) also?

Good question

**Comment by Romick2005** [comment]
So my hacked solution for now is using internal info:

```
import NativeStatusBarManagerIOS from "../../node_modules/react-native/Libraries/Components/StatusBar/NativeStatusBarManagerIOS";
import NativeStatusBarManagerAndroid from "../../node_modules/react-native/Libraries/Components/StatusBar/NativeStatusBarManagerAndroid";

const StatusBarManager = isIOS ? NativeStatusBarManagerIOS : NativeStatusBarManagerAndroid;
const statusBarHeight = StatusBarManager.getConstants().HEIGHT || 44;
```

console.log("statusBarHeight = " + statusBarHeight, StatusBarManager.getConstants());
