### ISSUE TITLE
Nesting Navigators

### ISSUE THREAD

**Issue by isikfsc** [facebook/react-native#4166]
@ericvicenti
Is it supported to nest Navigators in React Native?

I get an error message of 'Invariant Violation...' when ı try to nest them.

I have a [react native playground code here](https://rnplay.org/apps/CWB7YQ).

My purpose is to have same navigation functionality with the <LibrarySecondaryBar />, which is the tabor at top in the <Library /> scene, as I have with the <PrimaryBar />, which is at the bottom of the screen.
If I do not use a second Navigatorand just use simple compnents to produce secondar tabbar there is no problem. but this way navigating into subviews gets difficult, leaving builtin `Navigator` goodies animations and event handling to me.

**Comment by sospartan** [comment]
@isikfsc  what's the message right after 'Invariant Violation' ? that may help to locate the problem.

**Comment by isikfsc** [comment]
`Invariant Violation: Element type is invalid: expected string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of 'Navigator'`

**Comment by ericvicenti** [comment]
When you define `ROUTE_STACK_LIBRARY` your components like `Books` are not defined. So the `renderScene` of your nested navigator does not actually return a valid view.

Declaring the components first fixes it: (note, it is broken in v0.13rc, but it works fine in v0.11.4)  https://rnplay.org/apps/kShCKA

I'll add an invariant to Navigator that makes this more obvious
