### ISSUE TITLE
ReadableMap getCallback (Android)

### ISSUE THREAD

**Issue by mjhlybmwq** [facebook/react-native#4168]
Any way to get a method of the object passed to native module

**Comment by satya164** [comment]
NativeModules can take a callback or a promise as an argument.

```java
    @ReactMethod
    public void doSomething(final ReadableMap options, final Callback callback) {
        // do stuff
        callback.invoke(result);
    }
```

or

```java
    @ReactMethod
    public void doSomething(final ReadableMap options, final Promise promise) {
        try {
            // do stuff

            promise.resolve(result);
        } catch (Exception e) {
            promise.reject(e.getMessage());
        }
    }
```

**Comment by mjhlybmwq** [comment]
@satya164 I know. But if there're multiple callbacks, it's hard to keep the code tidy. Besides, keeping the arguments in the right order is no easy job. It's common in javascript that wrap the arguments as an object to keep the code clean.

**Comment by satya164** [comment]
You can write a wrapper on javascript side which passes multiple callbacks to the module, but exposes a simpler API to your app.

like,

```js
MyModule = opts => {
    return MyNativeModule(opts.success, opts.error);
};

MyModule = doSomething({ success: fn, error: fn });
```

**Comment by mjhlybmwq** [comment]
That's the solution I just worked out! THX!!
