### ISSUE TITLE
Could not init a new project 

### ISSUE THREAD

**Issue by lycaste** [facebook/react-native#4169]
when i use  " react-native init AwesomeProject" to create a new project ,but it does n0t work, the terminal aways says "Installing react-native package from npm...".nothing  happened in the "AwesomeProject"file except a json("{"AwesomeProject":"HelloWorld","version":"0.0.1","private":true,"scripts":{"start":"react-native start"}}") file.
but the NPM works normally.
npm:3.4.0
node:5.0.0

**Comment by InnerPeace080** [comment]
i think you should wait...

**Comment by lycaste** [comment]
i wait almost 2 hours..

**Comment by ide** [comment]
Can you try installing npm 2 and seeing if that works better for you? `npm install -g npm@2`, then `react-native init HopeThisWorks`.

**Comment by lycaste** [comment]
well...it works..thx

**Comment by mkonicek** [comment]
Thanks so much for answering @ide! Closing the issue.

**Comment by ide** [comment]
I'll update the docs to tell people to install npm 2. npm 3 is extremely slow (at least 2x slower, maybe 4x) for installing RN.
