### ISSUE TITLE
can't build release for android  - Windows 7

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#4170]
hi . i follow tutorial at here  (http://facebook.github.io/react-native/docs/signed-apk-android.html#content)

but when i run command "gradlew assembleRelease" in cmd (i use window 7 , 64 bit)  . 
it fail at line ':app:bundleReleaseJsAndAssets'

i have spend much time to find out what happen here. When i use --stacktrace , --info , and --debug flag as recommend . it say fail when run command "react-native bundle ..."

when i run above command alone , it stuck in 5 minute (that is timeout of create server as i founded) and return  error : listen EACCES , port : -1

seem like a permision error, but i can't find anything else , i run command with admintrator . 

Sorry about my english.

**Comment by AnnatarHe** [comment]
i have same issue like you....

**Comment by danhanfry** [comment]
Exactly the same, I give more details here
https://github.com/facebook/react-native/issues/4124

**Comment by InnerPeace080** [comment]
i have just success when run command 'react-native bundle ...' alone (i change way to server and client work (PATH -->> PORT) in SocketInterface node modul) . 


![capture](https://cloud.githubusercontent.com/assets/3762408/11238392/d55a5566-8e17-11e5-8f85-91a444c8b277.PNG)

but it still fail when run command 'gradlew assembleRelease'  :(((.

![capture2](https://cloud.githubusercontent.com/assets/3762408/11238415/f90c944c-8e17-11e5-85dc-252e144079de.PNG)

**Comment by InnerPeace080** [comment]
finally. i success to build release for android. i must write password, keyAlias... direct to build.gradle file (not use variable in gradle.properties anymore).:

![capture5](https://cloud.githubusercontent.com/assets/3762408/11261298/a40c7d8e-8ea5-11e5-9b8f-9d0e102fe922.PNG)



and by use solution here : https://github.com/hzerica/react-native/commit/32c755bf76f88aee289fedbd0cc8c3c0d4ec8749

i success to run command ' gradlew assembleRelease '

**Comment by InnerPeace080** [comment]
better solution https://github.com/facebook/react-native/pull/4071 .

**Comment by ismeteor** [comment]
I had  installed  react-native-cli  fiexed this issue.
