### ISSUE TITLE
Nesting ListViews in ScrollView

### ISSUE THREAD

**Issue by vanBrunneren** [facebook/react-native#4171]
Hi 
I'm trying to nest multiple ListViews in a ScrollView and I want to trigger the onEndReached Event of each ListView. I know that the ScrollView's Scroll is taken in this particular example but is there a way to manage this?

I thought about using a View instead a ScrollView for a Container but my Content is bigger than the Screen and I don't know the height of my Content.

Is there a way to either make a View as height as the Content or to Decide witch scroll should be taken? 

Something like this:
```
<ScrollView>
   <ListView>
     -> Scroll To End
   <ListView>
</ScrollView>
```

(I hope you understood my problem :smile: )

**Comment by christopherdro** [comment]
Not sure but maybe you can set a separate reference on each one of the listView components?

**Comment by vanBrunneren** [comment]
hi thank you for your response
I made another workaround. I have set the height of each ListView to the full height of the device. Then when the end is reached I load the next ListView. 

I close this issue until I run in the same problem again.
