### ISSUE TITLE
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: Request has not been opened

### ISSUE THREAD

**Issue by Vikasatneaxus** [facebook/react-native#41714]
### Description

![Screenshot 2023-11-30 at 1 08 42 PM](https://github.com/facebook/react-native/assets/85869501/bdb20fb3-7efe-49b5-a3fe-ac3070d18103)

# Crashlytics - Stack trace
# Application: meatigo
# Platform: apple
# Version: 11.5.1 (1)
# Issue: 94fb28018c12b0c7921b72267b8bb64f
# Session: dea4009ebe6a43d28ce6f5c4c4700703_DNE_0_v2
# Date: Wed Nov 29 2023 19:21:28 GMT+0530 (India Standard Time)

Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: Request has not been opened
0  CoreFoundation                 0x9e38 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  meatigo                        0x1de044 RCTFormatError + 166 (RCTAssert.m:166)
3  meatigo                        0x24fb60 -[RCTExceptionsManager reportFatal:stack:exceptionId:] + 68 (RCTExceptionsManager.mm:68)
4  meatigo                        0x25032c -[RCTExceptionsManager reportException:] + 135 (RCTExceptionsManager.mm:135)
5  CoreFoundation                 0x746b4 __invoking___
6  CoreFoundation                 0x20b1c -[NSInvocation invoke]
7  CoreFoundation                 0x20534 -[NSInvocation invokeWithTarget:]
8  meatigo                        0x20c250 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 587 (RCTModuleMethod.mm:587)
9  meatigo                        0x20e244 facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 183 (RCTNativeModule.mm:183)
10 meatigo                        0x20de94 invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 419 (Optional.h:419)
11 libdispatch.dylib              0x2460 _dispatch_call_block_and_release
12 libdispatch.dylib              0x3f88 _dispatch_client_callout
13 libdispatch.dylib              0xb640 _dispatch_lane_serial_drain
14 libdispatch.dylib              0xc18c _dispatch_lane_invoke
15 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread
16 libsystem_pthread.dylib        0xdf8 _pthread_wqthread
17 libsystem_pthread.dylib        0xb98 start_wqthread

com.apple.main-thread
0  libsystem_blocks.dylib         0x1d70 -[__NSStackBlock__ retain] + 278
1  UIKitCore                      0x2b9cc _UIGetCurrentFallbackTraitCollection + 92
2  UIKitCore                      0x442c9c +[UITraitCollection _currentTraitCollectionWithFallback:markFallback:] + 192
3  UIKitCore                      0x408508 _UICurrentImageTraitCollection + 28
4  UIKitCore                      0x3f758 +[UIImageConfiguration _completeConfiguration:fromConfiguration:] + 120
5  UIKitCore                      0x1d7200 +[UIImage imageNamed:inBundle:withConfiguration:] + 152
6  meatigo                        0x235e2c RCTImageFromLocalAssetURL + 819 (RCTUtils.m:819)
7  meatigo                        0x275690 -[RCTLocalAssetImageLoader loadImageForURL:size:scale:resizeMode:progressHandler:partialLoadHandler:completionHandler:] + 52 (RCTLocalAssetImageLoader.mm:52)
8  meatigo                        0x26a808 -[RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:priority:attribution:progressBlock:partialLoadBlock:completionBlock:] + 537 (RCTImageLoader.mm:537)
9  meatigo                        0x26c368 -[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:priority:attribution:progressBlock:partialLoadBlock:completionBlock:] + 811 (RCTImageLoader.mm:811)
10 meatigo                        0x269af4 -[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:priority:progressBlock:partialLoadBlock:completionBlock:] + 373 (RCTImageLoader.mm:373)
11 meatigo                        0x2699ec -[RCTImageLoader loadImageWithURLRequest:size:scale:clipped:resizeMode:progressBlock:partialLoadBlock:completionBlock:] + 352 (RCTImageLoader.mm:352)
12 meatigo                        0x372170 -[AIRMapMarker setImageSrc:] + 317 (AIRMapMarker.m:317)
13 meatigo                        0x1e46b4 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.35 + 315 (RCTComponentData.m:315)
14 meatigo                        0x1e49ac __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_2.36 + 333 (RCTComponentData.m:333)
15 meatigo                        0x1e4bd8 __37-[RCTComponentData setProps:forView:]_block_invoke + 371 (RCTComponentData.m:371)
16 CoreFoundation                 0x13538 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
17 CoreFoundation                 0x9db90 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 212
18 meatigo                        0x1e4b60 -[RCTComponentData setProps:forView:] + 373 (RCTComponentData.m:373)
19 meatigo                        0x23033c __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 1199 (RCTUIManager.m:1199)
20 meatigo                        0x23042c __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.146 + 1222 (RCTUIManager.m:1222)
21 libdispatch.dylib              0x2460 _dispatch_call_block_and_release + 32
22 libdispatch.dylib              0x3f88 _dispatch_client_callout + 20
23 libdispatch.dylib              0x127f4 _dispatch_main_queue_drain + 928
24 libdispatch.dylib              0x12444 _dispatch_main_queue_callback_4CF + 44
25 CoreFoundation                 0x9a6c8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
26 CoreFoundation                 0x7c02c __CFRunLoopRun + 2036
27 CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
28 GraphicsServices               0x1368 GSEventRunModal + 164
29 UIKitCore                      0x3a1668 -[UIApplication _run] + 888
30 UIKitCore                      0x3a12cc UIApplicationMain + 340
31 meatigo                        0x46e8 main + 7 (main.m:7)
32 ???                            0x1efe94960 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  Foundation                     0x42054 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41f3c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4d66a4 -[UIEventFetcher threadMain] + 436
10 Foundation                     0x5b518 __NSThread__start__ + 716
11 libsystem_pthread.dylib        0x16cc _pthread_start + 148
12 libsystem_pthread.dylib        0xba4 thread_start + 8

com.facebook.react.JavaScript
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  meatigo                        0x1ef3d8 +[RCTCxxBridge runRunLoop] + 378 (RCTCxxBridge.mm:378)
8  Foundation                     0x5b518 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0xf703c scavenger_thread_main + 1164
3  libsystem_pthread.dylib        0x16cc _pthread_start + 148
4  libsystem_pthread.dylib        0xba4 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x12b0 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  meatigo                        0x8073c FIRCLSMachExceptionServer + 192 (FIRCLSMachException.c:192)
5  libsystem_pthread.dylib        0x16cc _pthread_start + 148
6  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  CFNetwork                      0x257ff0 _CFURLStorageSessionDisableCache + 61088
8  Foundation                     0x5b518 __NSThread__start__ + 716
9  libsystem_pthread.dylib        0x16cc _pthread_start + 148
10 libsystem_pthread.dylib        0xba4 thread_start + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

Heap Helper Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

JSC Heap Collector Thread
0  libsystem_kernel.dylib         0x167c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x806c _pthread_cond_wait + 1232
2  JavaScriptCore                 0x4cbfc WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 1808
3  JavaScriptCore                 0xd62c bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 304
4  JavaScriptCore                 0xdaa8 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 248
5  JavaScriptCore                 0x6f3b4 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
6  JavaScriptCore                 0x7163c WTF::wtfThreadEntryPoint(void*) + 16
7  libsystem_pthread.dylib        0x16cc _pthread_start + 148
8  libsystem_pthread.dylib        0xba4 thread_start + 8

com.apple.CFStream.LegacyThread
0  libsystem_kernel.dylib         0xda8 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x13a1c mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x13c5c mach_msg_overwrite + 388
3  libsystem_kernel.dylib         0x12ec mach_msg + 24
4  CoreFoundation                 0x7aac4 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7bd08 __CFRunLoopRun + 1232
6  CoreFoundation                 0x80eb0 CFRunLoopRunSpecific + 612
7  CoreFoundation                 0x10921c _legacyStreamRunLoop_workThread + 300
8  libsystem_pthread.dylib        0x16cc _pthread_start + 148
9  libsystem_pthread.dylib        0xba4 thread_start + 8

Crashed: com.google.firebase.crashlytics.ios.exception
0  meatigo                        0x86824 FIRCLSProcessRecordAllThreads + 393 (FIRCLSProcess.c:393)
1  meatigo                        0x86c04 FIRCLSProcessRecordAllThreads + 424 (FIRCLSProcess.c:424)
2  meatigo                        0x7e230 FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  meatigo                        0x79254 __FIRCLSExceptionRecord_block_invoke + 232 (FIRCLSException.mm:232)
4  libdispatch.dylib              0x3f88 _dispatch_client_callout + 20
5  libdispatch.dylib              0x13574 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  meatigo                        0x7828c FIRCLSExceptionRecord + 234 (FIRCLSException.mm:234)
7  meatigo                        0x78d74 FIRCLSExceptionRecordNSException + 126 (FIRCLSException.mm:126)
8  meatigo                        0x77ee4 FIRCLSTerminateHandler() + 398 (FIRCLSException.mm:398)
9  libc++abi.dylib                0x10f28 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x10ec4 std::terminate() + 56
11 libobjc.A.dylib                0x33bec objc_terminate + 16
12 libdispatch.dylib              0x3f9c _dispatch_client_callout + 40
13 libdispatch.dylib              0xb640 _dispatch_lane_serial_drain + 672
14 libdispatch.dylib              0xc18c _dispatch_lane_invoke + 384
15 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
16 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_pthread.dylib        0xb90 start_wqthread + 254

com.moengage.analytics.datatracking.Y3OFR64WNN48P6LOGAG71UWZ
0  libsystem_kernel.dylib         0x14a8 stat + 8
1  libsystem_kernel.dylib         0x14a8 stat64 + 8
2  Foundation                     0x2b734 -[NSFileManager fileExistsAtPath:isDirectory:] + 96
3  MoEngageCore                   0x33ee4 keypath_get.19Tm + 33704
4  MoEngageCore                   0x3405c keypath_get.19Tm + 34080
5  MoEngageCore                   0x342f0 keypath_get.19Tm + 34740
6  MoEngageCore                   0x5767c __swift_project_boxed_opaque_existential_0 + 2260
7  MoEngageAnalytics              0x35a60 block_destroy_helper.53 + 9876
8  MoEngageAnalytics              0x36648 block_destroy_helper.53 + 12924
9  MoEngageAnalytics              0x338e4 block_destroy_helper.53 + 1304
10 libdispatch.dylib              0x2460 _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3f88 _dispatch_client_callout + 20
12 libdispatch.dylib              0xb640 _dispatch_lane_serial_drain + 672
13 libdispatch.dylib              0xc18c _dispatch_lane_invoke + 384
14 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
15 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
16 libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x12b0 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x12b0 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe44 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xb98 start_wqthread + 8

### React Native Version

0.68.7

### Output of `npx react-native info`

System:
    OS: macOS 13.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 20.23 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/node_modules/.bin/npm
    Watchman: 2023.09.25.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.7 => 0.68.7 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

firebase crashlytics 

### Snack, screenshot, or link to a repository

![Screenshot 2023-11-30 at 1 21 55 PM](https://github.com/facebook/react-native/assets/85869501/ef0fb041-7d4c-4118-98d1-173d12aa33c4)

**Comment by cortinico** [comment]
Closing as we don't offer support to Firebase Crashlytics reports unless you provide a reproducer

**Comment by Vikasatneaxus** [comment]
![image](https://github.com/facebook/react-native/assets/85869501/22284aeb-ab38-4903-ad54-5d6e0e2584fe)

look at this 

![Screenshot 2023-12-15 at 11 13 38 AM](https://github.com/facebook/react-native/assets/85869501/097361f1-15d2-4ca7-ac48-cdece941cd23)
