### ISSUE TITLE
Bug- Sometimes buttons or touchableOpacity are not working on the android phone.

### ISSUE THREAD

**Issue by aatiqJalanSWE** [facebook/react-native#41718]
### Description

Button or TouchableOpacity are not working on the android phone on some specific devices like(OnePlus[6t , 9r] , Samsung ) and few of the android phone are working smoothly as expected.

If I'll run same devices via USB debugging on emulator it is working fine for me and whenever I'll click manually on the phone sometimes it works and sometimes it is not.

### React Native Version

0.72.1

### Output of `npx react-native info`

System:                             
  OS: macOS 14.1.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 11.93 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.11.06.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Mostly issues are related to button component and on the touchableOpacity.

Button UI is from the React Native Elements Libaray.

### Snack, screenshot, or link to a repository

issue facing after the deployment of the app.

**Comment by cortinico** [comment]
Duplicates #36710
