### ISSUE TITLE
[podspec] prepare_command : npm install --production would duplicate react-native dependcies

### ISSUE THREAD

**Issue by panjianjun** [facebook/react-native#4174]
Since 0.13.x,we can't integrate react-native to existing apps from cocoapods spec repo anymore.We need to install react-native from npm and then install pod dependency from local.But after installing react-native from local path,the prepare_command would execute and download the depencies that has been downloaded when we install react-native from npm again.That would cause a confliction when we run `ract-native bundle`.

After I remove the pre_command in React.podspec manually, everything goes fine.

So I'm wondering if the prepare_command in React.podspec should be removed?

**Comment by ide** [comment]
You're right -- could send a PR?

**Comment by chirag04** [comment]
This is fixed in this pull request: https://github.com/facebook/react-native/pull/4291
