### ISSUE TITLE
React Native v0.72.7 Issue

### ISSUE THREAD

**Issue by sonjaie** [facebook/react-native#41740]
### New Version

0.72.7

### Old Version

0.65.1

### Build Target(s)

iOS Simulator

### Output of `react-native info`

System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 50.22 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Issue and Reproduction Steps

after upgrading react native version and then clean and build the app in xcode the error shows like

Undefined symbols for architecture arm64:
  "_YGNodeStyleGetGap", referenced from:
      -[RCTShadowView rowGap] in libReact-Core.a(RCTShadowView.o)
      -[RCTShadowView columnGap] in libReact-Core.a(RCTShadowView.o)
      -[RCTShadowView gap] in libReact-Core.a(RCTShadowView.o)
  "_YGNodeStyleSetGap", referenced from:
      -[RCTShadowView setRowGap:] in libReact-Core.a(RCTShadowView.o)
      -[RCTShadowView setColumnGap:] in libReact-Core.a(RCTShadowView.o)
      -[RCTShadowView setGap:] in libReact-Core.a(RCTShadowView.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

<img width="597" alt="image" src="https://github.com/facebook/react-native/assets/91644233/f0f9d43f-7d51-40fc-bb14-a0fec41b3d30">

**Comment by sonjaie** [comment]
@cortinico can you help me?

**Comment by cortinico** [comment]
@sonjaie not without a reproducer as the bot asked you here https://github.com/facebook/react-native/issues/41740#issuecomment-1835894185

**Comment by jason-heroes620** [comment]
@sonjaie, i am having the same error, did you managed to find a solution?

**Comment by sonjaie** [comment]
> @sonjaie, i am having the same error, did you managed to find a solution?

yup what i did is to update all core needed for that react native version you want to upgrade

**Comment by jason-heroes620** [comment]
> > @sonjaie, i am having the same error, did you managed to find a solution?
> 
> yup what i did is to update all core needed for that react native version you want to upgrade

can you elaborate a bit on this? what is it that i need to update and where? Thanks
