### ISSUE TITLE
[iOS] Clear image in `RCTImageView` causes lagging

### ISSUE THREAD

**Issue by leafduo** [facebook/react-native#4175]
We mix React Native and native code in our iOS app, and we run into a problem when using `RCTImageView`.

Steps to reproduce:
1. Put a `RCTRootView` in view controller A, inside the root view, we have a `<Image>` and a `<Text>` component.
2. Schedule some heavy work on main thread in `-viewWillAppear:`. (In the demo, we put a `sleep(1)`)
3. Push to another view controller
4. Pop to view controller A

Result: The image doesn't show immediately after the pop finishing, while the text shows instantly.
Expected behavior: The image and text should both show immediately after the pop.

We made a demo of the bug: https://github.com/leafduo/RCTImageView-lagging-bug

![untitled](https://cloud.githubusercontent.com/assets/28619/11211114/16159c2e-8d68-11e5-91f5-3d033fe59789.gif)

After reading part of the source code of `RCTImageView`, we found out that `clearImage` actually cause the problem. It set `image` property to `nil`, and `reloadImage` doesn't finish loading the image again until our heavy work finished.

```
- (void)clearImage
{
  [self cancelImageLoad];
  [self.layer removeAnimationForKey:@"contents"];
  self.image = nil;
}
```

Deleting `self.image = nil` solves the bug.

This behavior was first introduced in commit https://github.com/facebook/react-native/commit/98ab7581a560c8db4f9637bc5de14f273f599d27. I haven't fully understand the purpose of the commit. If it's made for improving the performance of `ListView`, maybe we should do some work in `ListView`, because improving the performance of a component that can be used inside `ListView` doesn't solve the problem of `ListView` itself.

**Comment by nicklockwood** [comment]
It's actually a memory optimisation - if we keep offscreen images in memory, the total RAM consumed by a long list could become huge.

I'm working to improve the performance with better image caching, so this should get better soon.

**Comment by browniefed** [comment]
I'm guessing this has landed by now?

**Comment by grabbou** [comment]
Don't think so, still getting that.

**Comment by juanpujol** [comment]
Is there any news on this? Thank you.

**Comment by ericvicenti** [comment]
Sorry, this isn't likely to get fixed unless somebody in core prioritizes it. If this is important to you, I'd suggest posting a ticket on product pains so the community can vote it up.

Until then, it is a known issue that clear images on iOS cause lag because the additional compositing that must be done.
