### ISSUE TITLE
Disconnect socket after onPause on Android

### ISSUE THREAD

**Issue by oney** [facebook/react-native#4177]
If users tap back button to leave app, I want to disconnect the socket(using socket.io). However, all Javascript threads are stopped after onPause of Activity, so the socket isn't disconnected.
```java
@Override
protected void onPause() {
    super.onPause();

    if (mReactInstanceManager != null) {
//            mReactInstanceManager.onPause();
    }
}
```
If I comment line `mReactInstanceManager.onPause();`, the socket will be disconnected.
How to disconnect the socket after onPause on Android?

**Comment by satya164** [comment]
I would also like to have this implemented. Any ideas on what will be a good way to do it?

cc @mkonicek

**Comment by skv-headless** [comment]
Thats for I've build ```AppState``` for android. I think we can make ```AppState``` listeners. Close when app goes to background and open when it became visible. Or do you think it should be default behavior?

**Comment by terrysahaidak** [comment]
But what's about socket "services" which should still work even if the app state is 'background'?

**Comment by satya164** [comment]
Does `AppState` module helps with this?

**Comment by junyangbb** [comment]
I have a similar issue related to the onPause. I try to send an event to JavaScript using DeviceEventEmitter right after onResume. However, I have send the event with 50 milliseconds postDelayed to make it work. Otherwise, the Javascript will just ignore my message. Any ideas?

**Comment by lacker** [comment]
There is new headless support in master so you could try that out. In general I think there just might not be a pure-js solution here. I'm going to close this issue because I think this discussion has run its course, but feel free to reopen an issue if there is a specific solution or possible solution it would be useful to discuss.
