### ISSUE TITLE
[iOS][ListView] Pretty nasty bug with UIExplorer's ListView implementation on master

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#4179]
Just pulled as 2016/11/17 09:30 Eastern and noticed these issues with ListView:

![listview](https://cloud.githubusercontent.com/assets/180031/11214326/950a8b84-8d0e-11e5-9f03-05f1130be56a.gif)

**Comment by skevy** [comment]
@jaygarcia yikes! Do you have any time to go bisect and figure out a commit where this might have been introduced?

**Comment by andyxhz** [comment]
Hi @jaygarcia, which APP is this ? I will try solve this :)

**Comment by browniefed** [comment]
@andyxhz this is the UIExplorer which is in the Examples folder of react-native repo https://github.com/facebook/react-native/tree/master/Examples/UIExplorer

**Comment by arunshan** [comment]
@jaygarcia Is your issue pertaining to the onPress event being triggered when you scroll through the listview? https://github.com/facebook/react-native/issues/3452

**Comment by jaygarcia** [comment]
@arunshan , TBH, i don't know. I've been dealing with so many issues that it's hard to keep track of them, myself :(.

**Comment by jaygarcia** [comment]
Already linked to another bug report. closing this one.
