### ISSUE TITLE
[Question] react-native-bundle --dev argument does not appear to be working

### ISSUE THREAD

**Issue by andrewsardone** [facebook/react-native#4181]
I'm up against an issue where my bundled JS seems to be perpetually in `__DEV__` mode, and I'm curious if anyone else has seen this problem or has a solution.

I am not using a `react-native init`’d project, but instead a home-rolled hybrid app. I'm running the following `react-native bundle` command to generate my `main.jsbundle` file:

```bash
react-native bundle --dev false --entry-file index.ios.js --platform ios --bundle-output main.jsbundle
```

The command generates my bundle, and I'm able to compile and run my app. My `main.jsbundle` starts with `__DEV__=!1`, but I don't think I'm actually running in a non-dev-mode. When starting the app, I'm seeing [the 'Loading from pre-bundled file' message][ss], and my console is logging out my views' params:

```
[info][tid:com.facebook.React.JavaScript] 'Running application "ReactApp" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
```

The `__DEV__ === true, development-level warning are ON` message leads me to believe that the bundle was not properly compiled for production.

Any thoughts? Any known issues, or areas I can investigate? Nothing popped up for me when searching across issues, and I came across the `--dev` flag via [`bundleCommandLineArgs.js`](https://github.com/facebook/react-native/blob/3a223e970e9b213b999fce221b65f69aeb806b99/private-cli/src/bundle/bundleCommandLineArgs.js#L28-L30).

My current relevant dependencies:

- `"react-native": "^0.14.1"`
- `"react-native-cli": "^0.1.7"`

Thanks!

[ss]: https://cloud.githubusercontent.com/assets/14554/11221950/cfabb232-8d35-11e5-9c9e-9ad0670c9e79.png
[foo]: https://github.com/facebook/react-native/blob/3a223e970e9b213b999fce221b65f69aeb806b99/private-cli/src/bundle/bundleCommandLineArgs.js#L28-L30

**Comment by eyaleizenberg** [comment]
same here

**Comment by andrewsardone** [comment]
I figured out my problem – **I realized that this was a non-issue**.

Given that my `main.jsbundle` starts with `__DEV__=!1` and looks minified, `react-native bundle --dev false` is properly working.


As for seeing [the 'Loading from pre-bundled file' message][ss], and [my console logging out my views' params](https://gist.github.com/andrewsardone/831f874ce1fca15ee9c6), this was because my Xcode _build configuration_ was set to `DEBUG`.

In native-land, React Native [sets up its own `RCT_DEBUG` definition][rctd]. Internally, `RCTLog()` [determines its logging behavior based on `RCT_DEBUG`][rctlog]. That explains why I was still seeing logging of my view's params and such.

Similarly there's an [`RCT_DEV` definition based on Xcode's `DEBUG` build configuration][rctdev]. This definition dictates, for example, whether or not the ['Loading from…'][ss] status bar [view is shown][dload], or the [shake-to-show dev menu is enabled][devm].

---

I have attempted to clarify these points in the docs via this PR: https://github.com/facebook/react-native/pull/4299

[rctd]: https://github.com/facebook/react-native/blob/f827a513a1a312a9d7b2f056cd025f9621426fff/React/Base/RCTDefines.h#L23-L33
[rctlog]: https://github.com/facebook/react-native/blob/f827a513a1a312a9d7b2f056cd025f9621426fff/React/Base/RCTLog.m#L195-L196
[rctdev]: https://github.com/facebook/react-native/blob/f827a513a1a312a9d7b2f056cd025f9621426fff/React/Base/RCTDefines.h#L35-L45
[dload]: https://github.com/facebook/react-native/blob/f827a513a1a312a9d7b2f056cd025f9621426fff/React/Modules/RCTDevLoadingView.m#L17
[ss]: https://cloud.githubusercontent.com/assets/14554/11221950/cfabb232-8d35-11e5-9c9e-9ad0670c9e79.png
[devm]: https://github.com/facebook/react-native/blob/f827a513a1a312a9d7b2f056cd025f9621426fff/React/Modules/RCTDevMenu.h#L22-L26

**Comment by ide** [comment]
Thanks for following up with a PR!

**Comment by JakeRawr** [comment]
Hi, 

It does show` __DEV__=!1` but i believe optimization is still off.
I also see this in the Xcode console: 
```
'Running application "IOS_99GAMERS" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
```
I've tried setting `__Dev__ = false` directly from main.jsbundle. It didn't work.

Any idea what I can do to set Dev to be false?

**Comment by JakeRawr** [comment]
Sorry, I figured out my own problem. as @andrewsardone said, Xcode build configuration has to set to "Release" for development mode. 

Here's how for people who want to know:
<img width="446" alt="screen shot 2015-11-25 at 10 58 57 am" src="https://cloud.githubusercontent.com/assets/7199499/11406917/ab00e99a-9364-11e5-88c1-4e3a4774681e.png">
Select "Edit Scheme" 

<img width="894" alt="screen shot 2015-11-25 at 10 57 54 am" src="https://cloud.githubusercontent.com/assets/7199499/11407004/17012736-9365-11e5-9b23-7971f183af8f.png">
Change build configuration to Release

When launching the app on device via xcode, shake your device, if no developer menu shows up, it's in development mode.

**Comment by EdBrooks** [comment]
I am still getting 
"Running application with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF"

as well as a white blank screen in simulator

**Comment by pareekkhushboo77** [comment]
@EdBrooks  any luck for white blank screen

**Comment by Amurmurmur** [comment]
My app crashes on boot when running this:
`react-native bundle --platform android --dev false --entry-file index.android.js  --bundle-output android/app/src/main/assets/index.android.bundle`

and building a signed APK.

Could anybody give any advise?

**Comment by godfredcs** [comment]
Guys I also have the same problem. I'm using expo and I'm getting _DEV_ === true, development-level warning are ON, performance optimizations are OFF. My apps take too long to open up on my simulator so I'm stuck with this white blank screen.

Can I get any help please?
