### ISSUE TITLE
Run babel transformation before finding dependencies

### ISSUE THREAD

**Issue by benhughes** [facebook/react-native#4185]
Right now the React Native packager builds the dependency tree and then runs the babel transformation this can cause issues if you have babel plugins that manipulate the path of required modules (e.g. resolve ~/my_module to your root directory). Is it possible to run babel first then build the dependency tree?

**Comment by buhe** [comment]
some plugin like https://github.com/codemix/babel-plugin-macros also need this.

**Comment by ide** [comment]
This would probably be a substantial change to the packager / Haste -- @martinbigio is this something you think could be done in a few days or is it too big of a project to invest time in?

**Comment by martinbigio** [comment]
@davidaurelio was planning to work on this when he gets some free bandwidth :)

**Comment by davidaurelio** [comment]
I am working on it. Should be in master this week

**Comment by adamshone** [comment]
Hey @davidaurelio,

This would be really useful for me as well. Do you have an idea when it's likely to get in?

Cheers!

**Comment by davidaurelio** [comment]
I hope it gets in tomorrow. I have it mostly working. It was an awful lot of work.

**Comment by adamshone** [comment]
Awesome news. Thanks David.
