### ISSUE TITLE
'optional' file not found

### ISSUE THREAD

**Issue by Ananthakr-Jupiter** [facebook/react-native#41872]
### Description

Xcode is throwing 
- `'optional' file not found`
- `'utility' file not found`

errors during compilation(after new architecture is enabled). From the initial looks, this seems to be a C++ compiler compatability issue, but couldn't narrow down why or how to fix it.

### Steps to reproduce

1. Create a React Native project with 0.72.6
2. Configure RN Bootsplash
3. Enable New architecture

### React Native Version

0.72.6

### Affected Platforms

Runtime - iOS

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 100.47 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.15.0
    path: ~/.asdf/installs/nodejs/16.15.0/bin/node
  Yarn:
    version: 3.2.0
    path: /usr/local/bin/yarn
  npm:
    version: 8.5.5
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman:
    version: 2023.08.14.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/ananthakumar/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-29 | Google Play ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.14.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/ananthakumar/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
node_modules/react-native/Libraries/RCTRequired/RCTRequired/RCTRequired.h:8:10 'utility' file not found

node_modules/react-native/Libraries/TypeSafety/RCTConvertHelpers.h:8:9 'optional' file not found

ios/Pods/Headers/Public/RCTRequired/RCTRequired/RCTRequired.h:8:10 'utility' file not found

~/Library/Developer/Xcode/DerivedData/Jupiter-dpakkcsiqsoortecrrkkegznetck/Build/Products/Debug-iphonesimulator/React-Codegen/React_Codegen.framework/Headers/RNBootSplashSpec/RNBootSplashSpec.h:15:2 This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
```

### Reproducer

https://github.com/zoontek/react-native-bootsplash/tree/5.1.1/example

### Screenshots and Videos

<img width="1419" alt="Screenshot 2023-12-09 at 5 29 36 PM" src="https://github.com/facebook/react-native/assets/105293354/55e49e12-915a-419c-949d-92355436a70a">

**Comment by cortinico** [comment]
>   Xcode:
>    version: 14.3.1/14E300c

Could you update to XCode 15 and try again @Ananthakr-Jupiter ?

**Comment by Ananthakr-Jupiter** [comment]
Getting the same error in Xcode 15 @cortinico

**Comment by Ananthakr-Jupiter** [comment]
We have abandoned the new architecture migration at that time. We are exploring to move to 0.76 again now, if we got any further updates, will update in your thread.

**Comment by zoontek** [comment]
@Ananthakr-Jupiter Be sure that your `AppDelegate.mm` [correctly compile as ObjC++](https://github.com/zoontek/react-native-bootsplash/discussions/657#discussioncomment-11417484)

**Comment by jamesrogers93** [comment]
In my case I was importing `#import "RNBootSplash.h"` in my `AppDelegate.h`. Moving it to `AppDelegate.mm` fixed the issue for me

**Comment by Ananthakr-Jupiter** [comment]
This worked @zoontek . Thank you! 🚀
