### ISSUE TITLE
[Android] App doesn't load unless Chrome Debugger is active

### ISSUE THREAD

**Issue by madwed** [facebook/react-native#4187]
My app just hangs on the background indefinitely after it finishes building.  When I open Chrome Debugger the app loads with no issues.  Using react-native 0.14.2.  Pretty stumped as to how to troubleshoot this.

Here is what's going on in the packager when the debugger isn't running.
```
[1:37:28 PM] <START> request:/index.android.bundle?platform=android&dev=true
[1:37:28 PM] <END>   request:/index.android.bundle?platform=android&dev=true (21ms)
::ffff:127.0.0.1 - - [17/Nov/2015:18:37:29 +0000] "GET /flow/ HTTP/1.1" 404 18 "-" "okhttp/2.4.0"
```
And when it is.
```
[1:38:36 PM] <START> request:/index.android.bundle?platform=android&dev=true
[1:38:36 PM] <END>   request:/index.android.bundle?platform=android&dev=true (33ms)
::ffff:127.0.0.1 - - [17/Nov/2015:18:38:37 +0000] "GET /flow/ HTTP/1.1" 404 18 "-" "okhttp/2.4.0"
```

**Comment by mattds** [comment]
Have you tried running adb logcat? I was getting the same issue, and was able to diagnose easily in the logs, for instance mine was caused by defining ref twice on the same component "SyntaxError: Attempted to redefine property 'ref'"

**Comment by madwed** [comment]
Thanks! After running logcat I see that the problem is in the bundle.... When the debugger isn't running it seems like babel isn't properly applied? Is this a problem with the packager? Maybe I'm missing a plugin.

The offending line is 
```
[TypeError: undefined is not a function (evaluating 'Array.from(new Array(total),function(x,i) ...
```
from
```
_createClass(Dots,[{
key:'render',
value:function render(){
var _this=this;

var _props=this.props;
var total=_props.total;
var active=_props.active;

var range=Array.from(new Array(total),function(x,i){
return i;});
```

**Comment by HananeAlSamrout** [comment]
how to solve the issue?
