### ISSUE TITLE
 com.facebook.react:flipper-integration which is missing the version number on v0.73.0

### ISSUE THREAD

**Issue by NorbertoStudios** [facebook/react-native#41876]
### Old Version

0.72.6

### New Version

0.73.0

### Description

When building with yarn the project fails to build the android app due to the new com.facebook.react:flipper-integration
which is missing the version number

### Steps to reproduce

yarn android 
fails 
[Could not determine the dependencies of task ':app:compileDebugJavaWithJavac']
 Could not find com.facebook.react:flipper-integration:. 

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 106.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.11.20.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google APIs ARM 64 v8a
      - android-31 | Android TV ARM 64 v8a
      - android-33 | Google TV ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
  react-native-tvos:
    installed: 0.73.0-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find com.facebook.react:flipper-integration:. Required by: project :app * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 4s.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

A fix is to add the version number to the android/app/build.gradle file 
something like this 
Line 110
  implementation("com.facebook.react:flipper-integration:0.73.0")

**Comment by mjaggard** [comment]
This has happened to me today too. It seems that `com.facebook.react:flipper-integration` has not been released to mavenCentral at version `0.74.0` and so the automatic version number calculation is wrong.

Incidentally manually putting `0.73.7` in manually also doesn't work because of a duplicate class.

**Comment by cortinico** [comment]
> This has happened to me today too. It seems that `com.facebook.react:flipper-integration` has not been released to mavenCentral at version `0.74.0` and so the automatic version number calculation is wrong.

This is intentional as Flipper integration has been removed from React Native.
This is part of the deprecation cycle mentioned here:
- https://github.com/react-native-community/discussions-and-proposals/pull/641

**Comment by eisodev** [comment]
> > This has happened to me today too. It seems that `com.facebook.react:flipper-integration` has not been released to mavenCentral at version `0.74.0` and so the automatic version number calculation is wrong.
> 
> This is intentional as Flipper integration has been removed from React Native. This is part of the deprecation cycle mentioned here:
> 
> * [RFC: Decoupling Flipper from React Native core react-native-community/discussions-and-proposals#641](https://github.com/react-native-community/discussions-and-proposals/pull/641)

How will this affect users trying to stay on 0.73.7 to continue use Flipper for a while?

**Comment by DeadlyEagle** [comment]
Anyone can solved this issue?

**Comment by Drizzy-hub** [comment]
> :0.73.0

I am currently facing same issue and will only comment it out in the mean time as a solution

**Comment by raphaelweis** [comment]
I had the same issue that started after upgrading our expo sdk. Deleting the android directory then regenerating it solved the issue.

**Comment by Khayo99** [comment]
> Eu tive o mesmo problema que começou após atualizar nosso Expo SDK. Excluir o diretório Android e depois regenerá-lo resolveu o problema.

Obrigado mano, aqui só funcionou com a sua dica, após excluir a pasta android funcionou perfeitamente. Obrigado

**Comment by szhabolcs** [comment]
> I had the same issue that started after upgrading our expo sdk. Deleting the android directory then regenerating it solved the issue.

Can confirm this work with upgrading from expo v50 to v51

Thank you 🙏

**Comment by khanhvohoangvib** [comment]
for me it's caused by @types/react-native-htmlview, I removed this one then I can build normally
