### ISSUE TITLE
[TextInput] Focus on new TextInput resets value of previous TextInput

### ISSUE THREAD

**Issue by esauter5** [facebook/react-native#4189]
I had a project on v0.11.0 where I was creating a series of input boxes that would jump to the next box when a certain condition was met. Since updating to 0.14.0, I've seen a weird behavior when this happens. The input box updates appropriately as I type, but when it focuses on the next input, it seems to reset the input value to the initial state for the previous input. To be clear though, the actual state I am holding is correct, it is just the value that is incorrect.

Sample video here: https://www.dropbox.com/s/wh8n75l1utcydvy/nameInput.mov?dl=0

This behavior did not occur when the app was on 0.11.0. I thought it might be due to a higher order TextInput, I've created, but in the video I ended up using the base TextInput and saw the same results.

I created a generic version of my code on RNPlay. You can see my code here: https://rnplay.org/apps/U0WaSQ. It mirrors the basic structure of the video, I've just abstracted my specific application code out of the RNPlay version. The problem is I do not see the same behavior on RNPlay. RNPlay is still using 0.13.0rc though, so if 0.14.0 is the source of the issue, I can't confirm on RNPlay.

I'll do some more digging. In the meantime, I'd be curious if anyone has seen a similar behavior?

**Update**
I was also able to produce the same incorrect behavior seen in the video locally when using 0.14.2 and the same code that I used in my RNPlay version.

**Comment by idibidiart** [comment]
Hi

the example you linked to doesn't work.... TextInput and all React Native components return independent instances of the underlying UIKit component, so what you're reporting must have its cause somewhere in your JS, but to determine if that's actually true I'd need a working example that shows the problem :)

**Comment by esauter5** [comment]
I'm not seeing the same thing as you. I just checked it and it looks fine for me.

The problem with this example as I noted is that on RN Playfround it works *as expected*. I'm unable to replicate the issue on RNPlayground and I believe this is due to the fact that the latest version of react-native on RNPlayground is `0.13.0rc`. I can however replicate the problem is new projects on my own machine. If you copy the code from that app into a new project and use a version of react-native >= `0.14.0` you should see the issue. If you add 3 more i's to the "Hi" input, it will focus on the next input and "Hiiii" will become "Hi".

Does that make sense?

**Comment by christopherdro** [comment]
Looks fine for me me as well.

**Comment by brentvatne** [comment]
That's pretty weird @esauter5! Especially given that it's working for @christopherdro. Could you possibly provide a repo that I can just clone off Github?

**Comment by esauter5** [comment]
@brentvatne I *think* @christopherdro was agreeing with me and saying that the RNPlayground example worked fine.  I don't think he was saying he doesn't see the bug I am reporting. My problem was that I couldn't show the problem on RNPlayground because I think its a 0.14 issue and RNPlayground only goes up to `0.13.0rc`. Before 0.14 versions, this issue did not exist for me.

Your idea is exactly what I should have done in the first place though. I'll set up a sample project using a version of react-native >= 0.14.0 that you can clone so its easy to see the issue. I should have some time tomorrow to do this.

**Comment by brentvatne** [comment]
Great, thanks @esauter5 :)

**Comment by christopherdro** [comment]
Sorry I wasn't clear on my comment. I was confirming that things were working fine for me on the playground. I will try and test this locally on 0.14+ and report back when I get a chance.

**Comment by esauter5** [comment]
@brentvatne You can check out this repo I created to see the bug I've been talking about: https://github.com/esauter5/SampleInputBug

**Comment by esauter5** [comment]
@brentvatne This appears to have been fixed in a recent version of react-native. Not sure which version specifically, but I have a project using 0.17.0 and I also upgraded my sample project to 0.18.0 and TextInput works properly in both instances. I'll close.
