### ISSUE TITLE
Scroll Bar in <ScrollView /> is content left or center position sometimes on iOS 16.1

### ISSUE THREAD

**Issue by suinkimme** [facebook/react-native#41905]
### Description

I readed similar issues but I think. It doesn't fixed it.

![image](https://github.com/facebook/react-native/assets/91166097/d04ff6d8-7dc9-4a39-a433-7baf72a59aec)

### Steps to reproduce

1. Just Refresh or Sometimes...

### React Native Version

0.70.6

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M2 Pro
    Memory: 1.20 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/kimsuin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
none
```

### Reproducer

none

**Comment by cortinico** [comment]
> 0.70.6

Can you update to one of the supported React Native verison and try again?

**Comment by suinkimme** [comment]
I have to develop only in this environment...

**Comment by suinkimme** [comment]
> > 0.70.6
> 
> Can you update to one of the supported React Native verison and try again?

I have to develop only in this environment...

**Comment by suinkimme** [comment]
> > 0.70.6
> 
> Can you update to one of the supported React Native verison and try again?

I have to develop only in this environment...
