### ISSUE TITLE
Could not find com.facebook.react:react-android:0.73.0

### ISSUE THREAD

**Issue by HaNguyenRN** [facebook/react-native#41919]
### Description

* What went wrong:
Could not determine the dependencies of task ':app:compileDevDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devDebugCompileClasspath'.
   > Could not find com.facebook.react:react-android:0.73.0.
     Required by:
         project :app
         project :app > project :react-native-community_art
         project :app > project :react-native-community_cameraroll
         project :app > project :react-native-firebase_analytics
         project :app > project :react-native-firebase_app
         project :app > project :react-native-firebase_messaging
         project :app > project :react-native-pager-view
         project :app > project :react-native-twilio-phone

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

### Steps to reproduce

cd android && ./gradlew installDevDebug

### React Native Version

0.73

### Affected Platforms

Runtime - Android

### Output of `others version`

```text
Java version:
openjdk 17.0.9 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
Node version: v20.3.0
Android Version: 14
Devices Name: Pixel 7
```

### Packages.json

```text
   "@react-native-community/art": "1.2.0",
   "@react-native-community/cameraroll": "^4.1.2",
   "@react-native-firebase/analytics": "18.7.2",
   "@react-native-firebase/app": "18.7.2",
   "@react-native-firebase/messaging": "18.7.2",
   "react-native-pager-view": "6.2.3",
```

### Reproducer

::::

### Screenshots and Videos

::

**Comment by cortinico** [comment]
> cd android && ./gradlew installDevDebug

Cannot reproduce. This works correctly on a newly created project.
Please provide a reproducer and we can reopen this.
