### ISSUE TITLE
[v0.73.0][iOS] Issue with `react-native-xcode.sh`

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#41928]
### Description

Upgrade of an existing project from RN 0.72.7 to 0.73.0. Running a new arch build for iOS on my (unfortunately old Intel-based) macOS. Fails this way:
![image](https://github.com/facebook/react-native/assets/20144632/e1d2653b-3ed5-4b78-87fb-fa5218d1ecad)

So, this happens inside `react-native/scripts/react-native-xcode.sh` script, here:
https://github.com/facebook/react-native/blob/5a600e60d93a47173d457ffcd47a37b9064bcc80/packages/react-native/scripts/react-native-xcode.sh#L17-L22

On my machine `ipconfig getifaddr en0` exits with error code `1` (which interrupts entire script with that error), and `ipconfig getifaddr en1` returns a valid network IP. If I just modify the script in-place changing to `for num in 1 2...` (so it starts trying with `1`, then everything works fine &mdash; the build completes, and the app starts on my device, able to load from the dev server.

I am not much knowledgeable in such stuff, but my first impression is that the shell script should be corrected to not abort on error codes on the line 18?

### Steps to reproduce

See above

### React Native Version

0.73.0

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by mlazari** [comment]
0.73.1 is out, but looks like this was not included for some reason...

**Comment by cortinico** [comment]
> 0.73.1 is out, but looks like this was not included for some reason...

Listed here https://github.com/reactwg/react-native-releases/discussions/95#discussioncomment-7958002
Will be included in 0.73.

For the future, please head over to the `react-native-releases` WG and request a pick if you rely on a fix being out in a point release 👍

**Comment by mlazari** [comment]
@cortinico Thank you, I probably misunderstood your previous comment or the process how the fixes are included in a future RN release. I am using a patch for now, but thanks for requesting that to be included in 0.73.2 in `react-native-releases`.
