### ISSUE TITLE
[Geolocation] Android support

### ISSUE THREAD

**Issue by Kudo** [facebook/react-native#4194]
Just to check the reason that why RN did not support geolocation polyfill for Android in the mean time?
I knew there are some 3rd party modules exist, but I would like to see if it could be a builtin feature.
Are there any concerns?  If need, I can help to do it and send a PR.
Thanks.

**Comment by ide** [comment]
Cc @dmmiller

**Comment by brentvatne** [comment]
@Kudo - this is on the roadmap, you can see it here: https://facebook.github.io/react-native/docs/known-issues.html#missing-modules-and-native-views

**Comment by Kudo** [comment]
Sorry I missed the know issues document.
Thank you guys for hard working.  React Native is really cool, and hope it will be better and change to mobile development ecosystem.
If there are anything I can help, please feel free to let me know.

**Comment by brentvatne** [comment]
No problem, thanks @Kudo! Feel free to open up other issues if you run into bugs :)
