### ISSUE TITLE
Static image missing in main.jsbundle in 0.14.2

### ISSUE THREAD

**Issue by Thorbenandresen** [facebook/react-native#4195]
I have a simple app where I added a new static image resource"

`<Image source={require('./img/options.png')}></Image>`

the image displays nicely when I am running the app on the localhost. I then bundle the the app with the following command: 

`react-native bundle --dev true --assets-dest ./ios --entry-file index.ios.js --platform ios --bundle-output ios/main.jsbundle`

which logs:

```
bundle: Created ReactPackager
bundle: Closing client
bundle: start
bundle: finish
bundle: Writing bundle output to: ios/main.jsbundle
bundle: Done writing bundle output
bundle: Copying 1 asset files
bundle: Done copying assets
```

when I now run the app from the bundle, it does not display that image. How can I fix that? 

(btw. I don't know if that is of any importance, but I actually needed to re-add the main.jsbundle to xcode to prevent a blank screen "Loading from (null) : (null)".)

**Comment by alvinwoon** [comment]
Having this issue as well. 

react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output main.jsbundle --assets-dest ./images

assets in 'images' folder on project root. Upgrading from 0.13 to 0.14.2. Latest ios, xcode version. Works on index.ios.js but not on bundle.

**Comment by alvinwoon** [comment]
Alright you need to run the script: ../node_modules/react-native/packager/react-native-xcode.sh

http://facebook.github.io/react-native/docs/upgrading.html

**Comment by Thorbenandresen** [comment]
ok, thanks - I unfortunately cant run that script. See (here)[https://github.com/facebook/react-native/issues/3948#issuecomment-157568831]

**Comment by IanWang** [comment]
I got the same issue, so how did you solve this one? @Thorbenandresen
