### ISSUE TITLE
How to know the custom component's position in a scollView?

### ISSUE THREAD

**Issue by Jerrylingit** [facebook/react-native#4197]
I want to adjust the position of textInput when the keyboard appear.  While in Objective-C, there are many ways to do. But here in React Native, I could not found the API that similar to Objective-C。So, i wander if anyone who figure it out and please tell me .

**Comment by Jerrylingit** [comment]
I want to adjust the position of textInput when the keyboard appear.  While in Objective-C, there are many ways to do. But here in React Native, I could not found the API that similar to Objective-C。So, i wander if anyone who figure it out and please tell me .

**Comment by christopherdro** [comment]
Try using the `onLayout` prop on your component. The information should be there.
