### ISSUE TITLE
Crash issue in 0.73.0 when Keyboard has InputAccessoryView enabled.

### ISSUE THREAD

**Issue by aschick82** [facebook/react-native#41986]
### Description

In version 0.73.0 the **Keyboard** component goes frozen and causes an **app crash** when InputAccessoryView is added and enabled.

### Steps to reproduce

Add an **InputAccessoryView** to a **TextInput**. When the **Touch Keyboard** is shown, the app freezes and crashes.

### React Native Version

0.73.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
-
```

### Stacktrace or Logs

```text
-
```

### Reproducer

-

**Comment by cortinico** [comment]
Closing as invalid: missing reproducer, stacktrace, logs, etc.

**Comment by Moreno97** [comment]
I can confirm this bug, upgrading the app to React Native 0.73 and using a `InputAccessoryView`, causes the app to freeze and manually closing it.

Strangely, it only happens to us on release mode for iOS, Android is working fine.

**Comment by mobinni** [comment]
I've found the same happens here, any remediation possible?
