### ISSUE TITLE
Not able to run release after 0.73.1

### ISSUE THREAD

**Issue by Alper-Demir-Eng** [facebook/react-native#42007]
### Old Version

0.73.0

### New Version

0.73.1

### Description

After updating to 0.73.1, I'm getting an error when running (npm run android -- --mode="release"):
"error Cannot start server in new window because no terminal app was specified."
Building is completing successfully, running in development also works, run releasing does not...
I even tried with a newly initialized project (including the reproducer project)..
Is anyone else experiencing this? 

### Steps to reproduce

1. Make sure you are on 0.73.1
2. npx react-native build-android --mode=release
3. npm run android -- --mode="release"
4. notice the error.

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 2.19 GB / 15.71 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.2.5
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found //Not sure why it is "Not Found", I can build and release on 0.73.0
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11076708
  Visual Studio: Not Found
Languages:
  Java: 17.0.9
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: ^0.73.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
error Cannot start server in new window because no terminal app was specified.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by Mo3tasm** [comment]
I'm not sure how to provide a reproducer, the problem seems to be project-agnostic, and only occurs upon updating to 0.73.1
Tried my production project, a newly initialized one and the reproducer project as well.

**Comment by ahanusek** [comment]
The same when upgrading fresh project from 0.73.0 to 0.73.1. Cannot find any information where I should set terminal app.

**Comment by lyswhut** [comment]
This is i tested results in v0.73.0: https://github.com/facebook/react-native/issues/41867#issuecomment-1853289632

**Comment by Alper-Demir-Eng** [comment]
@lyswhut  Thank you for the workaround, on one terminal I run `npx react-native start`  and then on another I run `npm run android -- --mode="release"`  and it works..

**Comment by lunaleaps** [comment]
I'm wondering if its' because of the CLI bump we picked in 0.73.1 https://github.com/facebook/react-native/commits/0.73-stable/

**Comment by lyswhut** [comment]
@Alper-Demir-Eng  you can try to edit `node_modules/@react-native-community/cli-tools/build/findDevServerPort.js` file:

```diff
const findDevServerPort = async (initialPort, root) => {
  let port = initialPort;
- let startPackager = true;
+ let startPackager = false;
  const packagerStatus = await (0, _isPackagerRunning.default)(port);
  if (typeof packagerStatus === 'object' && packagerStatus.status === 'running') {
    if (packagerStatus.root === root) {
      startPackager = false;
      (0, _port.logAlreadyRunningBundler)(port);
    } else {
      const result = await (0, _handlePortUnavailable.default)(port, root);
      [port, startPackager] = [result.port, result.packager];
    }
  } else if (packagerStatus === 'unrecognized') {
    const result = await (0, _handlePortUnavailable.default)(port, root);
    [port, startPackager] = [result.port, result.packager];
  }
  return {
    port,
    startPackager
  };
};
```

**Comment by Alper-Demir-Eng** [comment]
@lunaleaps @lyswhut Thank you for your assistance, I had no problem on 0.73.0, and yes changing `let startPackager` to false does the trick.
