### ISSUE TITLE
Not Working in real device in debug mode

### ISSUE THREAD

**Issue by RutvinBhanderi** [facebook/react-native#42009]
### Description

I installed new react native project and its working well in the simulator. but when I built in real device in debug mode it was showing paseExecution error. then i found some solution that i have to change something in build phase.

1. In the build phase I marked for install builds only inside the **Bundle React Native code and images** 
![Screenshot 2023-12-20 at 11 57 02 AM](https://github.com/facebook/react-native/assets/86949269/f21a1b31-9e89-4ea2-83d9-6870a819712d)

then it is building successfully but when the app opens it stuck at splash screen.
i got this error.
![Screenshot 2023-12-20 at 12 02 06 PM](https://github.com/facebook/react-native/assets/86949269/3530aa24-a685-445a-89e3-1689d7cdc131)

### Steps to reproduce

1. Initialize the new react native app
npx react-native@latest init AwesomeProject

2. mark For install build only (Build phase > Bundle React Native code and images)
3. run code in real device

### React Native Version

0.73.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 67.70 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2022.11.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
dyld[932]: Library not loaded: @rpath/OpenSSL.framework/OpenSSL
  Referenced from: <C17BD18C-F8E6-38B9-91F4-52A8CE635CFA> /private/var/containers/Bundle/Application/250C2226-652A-452C-8E9B-1892DD0840E9/AwesomeProject.app/AwesomeProject
  Reason: tried: '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/250C2226-652A-452C-8E9B-1892DD0840E9/AwesomeProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/250C2226-652A-452C-8E9B-1892DD0840E9/AwesomeProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/250C2226-652A-452C-8E9B-1892DD0840E9/AwesomeProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file), '/private/var/containers/Bundle/Application/250C2226-652A-452C-8E9B-1892DD0840E9/AwesomeProject.app/Frameworks/OpenSSL.framework/OpenSSL' (no such file)
```

### Reproducer

https://github.com/RutvinBhanderi/react-native-reproducer

**Comment by Hao-yiwen** [comment]
I think maybe you should change your openssl version.Or run `bundle install` in your root of project.

**Comment by RutvinBhanderi** [comment]
> I think maybe you should change your openssl version.Or run `bundle install` in your root of project.

i did bundle install but not working.

then i markled install build only ([CP] Embed Pods Frameworks,[CP] Copy Pods Resources) inside build phase but its showing library not loaded.
![Screenshot 2023-12-21 at 10 35 51 AM](https://github.com/facebook/react-native/assets/86949269/16bcf702-85a1-45db-b1fb-f38d3151d371)

**Comment by TomWq** [comment]
The same problem, there is no solution

**Comment by mmilvydas112** [comment]
My solution was network related. Make sure to turn off antivirus, or just open 8081 port for all network traffic in antivirus firewall settings (which solved issue for me)

**Comment by cipolleschi** [comment]
Hi @RutvinBhanderi, thanks for the issue. 

What is `MobileVLCKit`? It is not something that comes with React Native and it is that thing that is making your app fail.
It does not seem to be a React Native issue. For another issue, I just installed a React Native app on my physical devie in both Debug and Release mode.

As of today, we are aware of an issue with React Native on device but only if you run `pod install` with the `USE_FRAMEWORKS=dynamic` option turned on, which is not the default settings.

From your log, it looks like you have some dylibs... What setup are you using?

**Comment by RutvinBhanderi** [comment]
> USE_FRAMEWORKS

I am using vlc media player but that is not the even if i remove the vlc library then also it is coming.
this is how my podfile looks 
![Screenshot 2023-12-28 at 12 27 22 PM](https://github.com/facebook/react-native/assets/86949269/976f1a1d-0547-4e15-8c1e-f515502e4cb2)

**Comment by cipolleschi** [comment]
Can you report **exactly** which command you issued/what did you do to run it on device?

I did it yesterday and it worked with no issues (I only had to change the bundle id to match the provisioning profiles, of course).

**Comment by RutvinBhanderi** [comment]
> Can you report **exactly** which command you issued/what did you do to run it on device?
> 
> I did it yesterday and it worked with no issues (I only had to change the bundle id to match the provisioning profiles, of course).
in xcode i just edit schema to debug mode and just build in my phone.
xcode version :- 15.1

getting this error :- **Command PhaseScriptExecution failed with a nonzero exit code**

**Comment by danidaryaweesh** [comment]
Not working for me as well, getting Command PhaseScriptExecution failed with a nonzero exit code issue, but building to simulator with no issues. I even tried with several iOS devices.

**Comment by RutvinBhanderi** [comment]
> @RutvinBhanderi I had the exact same issue and it turns out that RN was not bundling my index file because I'm using Typescript, so my bundle file is index.tsx and it expects index.js. Check that out if you're using Typescript in your project.


i am not using typescript. initially the project was generated in typescript but i changed app.tsx and index.tsx file to .js

**Comment by cipolleschi** [comment]
@RutvinBhanderi can you follow the steps highlighted [here](https://levelup.gitconnected.com/how-to-properly-read-xcode-error-7b979692333d) to properly understand which script is failing? It is hard to help without knowing what's going on.
