### ISSUE TITLE
Build fails for Xcode 15  for 17 version

### ISSUE THREAD

**Issue by g7crservice-Binni-kumari** [facebook/react-native#42010]
### Description

In Hash file I got in these set of line of code 

  **#else
        template <typename T>
        struct hash_base : std::unary_function<T, std::size_t> {};
#endif**

I modified underscore as suggested 

  **#else
        template <typename T>
        struct hash_base : std::__unary_function<T, std::size_t> {};
#endif**

After this, I am getting errors in **FBReactnativeSpec** file 

<img width="1728" alt="Screenshot 2023-12-20 at 12 50 28 PM" src="https://github.com/facebook/react-native/assets/98733632/a950cf1b-365d-4076-9866-fa9571e2f0ea">

As you can see in this image.

why this error is coming? Is it new error or I am missing something?

### Steps to reproduce

1. Install New version Somona.
2. Install xcode latest version - 15.1
3. Install latest emulator - < 17 verion , I am running iPhone 15 pro max.
4. try to build from xocde.

### React Native Version

0.70.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
I can not print the output, as mentioned in the above image getting a build error.
```

### Stacktrace or Logs

```text
Value is unavailable introduced in ios 12.0.
```

### Reproducer

https://github.com/below/react-Xcode15Bug

### Screenshots and Videos

<img width="1728" alt="Screenshot 2023-12-20 at 12 50 28 PM" src="https://github.com/facebook/react-native/assets/98733632/dd0dd580-6791-4902-b1c7-bcd8274b4348">

**Comment by pnthach95** [comment]
You report about v0.70.0, but 2 reproducers are 0.71.8 (copied from https://github.com/facebook/react-native/issues/37748) and 0.73.1 (which is never failed with xcode 15). If you want to run v0.70 with xcode 15, use v0.70.14 or latest version

**Comment by pnthach95** [comment]
How do you upgrade? If you only bump version in package.json, it fails 100%. And 0.72.8 isn't the latest

**Comment by pnthach95** [comment]
That isn't how to upgrade react native version, use [upgrade helper](https://react-native-community.github.io/upgrade-helper/). Your screenshot didn't finish uploading

**Comment by supriyoMondal** [comment]
to fix the problem you are facing you need to open project in xcode , inside the targets select react-codegen , go to build settings , make sure iOS deployment target is minimum 12.4.

**Comment by cortinico** [comment]
Closing as you received relevant answers already.
React Native 0.70 was not compatible with XCode 15.
If you upgrade to the latest stable (0.73) you should be able to build correctly
