### ISSUE TITLE
the develpoer menu can't work

### ISSUE THREAD

**Issue by lizhangqu** [facebook/react-native#4202]
In Android,i use XiaoMi 3 to run react-native app,but when i press the menu (whatever short press or long press),the developer menu can't show,also shaking the device can't work too,And I alse use **setUseDeveloperSupport(true)** ,what's the reason?

**Comment by lizhangqu** [comment]
小米三悬浮窗权限打开即可

**Comment by plcstpierre** [comment]
What did you do? I have the same problem.

**Comment by plcstpierre** [comment]
Got it: have to disable the permission manager.

On my MIUI 7.1: 

(Settings > System apps > Security > Permissions > Permission manager)

react-native does not support the on demand permission api.

**Comment by ios122** [comment]
Note For Chinese: 小米三, MI3W:
开启调试菜单方法:设置 --> 系统应用 --> 安全中心 |  (当前页最下面)各模块功能设置 | 授权管理 --> 应用权限监控 ,关闭即可. Thanks @lizhangqu @plcstpierre

**Comment by ggepenyan** [comment]
I'm working on xiaomi a1, it's android version is 8. I'm not able to open developer menu to enable hot reloading. What can I do?

**Comment by ggepenyan** [comment]
For me there is not permission for this. I tried long press menu button, but it does another action, displays app on half of the screen. Please help I can't do anything.
