### ISSUE TITLE
network request failed when fetch('https://mywebsite.com/mydata.json');  0.73.1 => https://reactnative.dev/docs/network

### ISSUE THREAD

**Issue by megabeehothanhminh** [facebook/react-native#42056]
### Description

Not call api .json

### Steps to reproduce

Not call api .json

### React Native Version

0.73.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
0.73.1
```

### Stacktrace or Logs

```text
network request failed
```

### Reproducer

network request failed

**Comment by megabeehothanhminh** [comment]
npx react-native@latest init AwesomeProject
=> fetch error

**Comment by cortinico** [comment]
> Not call api .json

Closing as invalid as your steps to reproduce are unclear. Please update your issue and we can look into it. You also need to provide a reproducer.

**Comment by HaNguyenRN** [comment]
I still get errors with both Android & Ios. Any solution for this bugs?
