### ISSUE TITLE
error Cannot start server in new window because no terminal app was specified.

### ISSUE THREAD

**Issue by MUSHTHAK2899** [facebook/react-native#42074]
### Description

![Screenshot 2023-12-27 132743](https://github.com/facebook/react-native/assets/106859154/cb757d27-69a2-45b2-ae54-6548763e40b3)
![Screenshot 2023-12-27 132726](https://github.com/facebook/react-native/assets/106859154/1e921a66-e7e7-4bf9-a19e-16c5003e7fcc)

### Steps to reproduce

dont run app

### React Native Version

0.73.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
error Cannot start server in new window because no terminal app was specified.
```

### Stacktrace or Logs

```text
error Cannot start server in new window because no terminal app was specified.
```

### Reproducer

error Cannot start server in new window because no terminal app was specified.

### Screenshots and Videos

error Cannot start server in new window because no terminal app was specified.

**Comment by cortinico** [comment]
Potential fix https://github.com/react-native-community/cli/pull/2236

**Comment by aajahid** [comment]
@MUSHTHAK2899  - The fix got merged. But until a new release comes out - you can work around by using

`npx react-native start` and then press `a` to start android build

<img width="631" alt="image" src="https://github.com/facebook/react-native/assets/1908862/7794fe33-63b4-42a6-96a8-1fc78ad587e1">

**Comment by RayHughes** [comment]
Having the same issue here

**Comment by cortinico** [comment]
This should be fixed by 0.73.2, can verify so we can close this one?

**Comment by james-cohen** [comment]
This is still happening in 0.73.2

**Comment by aajahid** [comment]
I don't see any new `cli` release.

**Comment by cortinico** [comment]
It turns out this will be fixed in 0.73.3

**Comment by cortinico** [comment]
Correct. This will be fixed in 0.73.4. Apologise for the delay

**Comment by dylanFdvhuset** [comment]
@cortinico Just upgraded to 0.73.4 and still have this issue showing up

**Comment by cortinico** [comment]
> @cortinico Just upgraded to 0.73.4 and still have this issue showing up

Then please open an issue on
https://github.com/react-native-community/cli/issues

**Comment by aajahid** [comment]
I created a new project yesterday using react-native 0.73.4 and it did work fine. 

@cortinico  - you might need to delete your `node_modules` and package-lock.json and run `npm install` again.
