### ISSUE TITLE
[Windows] Static local image

### ISSUE THREAD

**Issue by PCharpentier** [facebook/react-native#4207]
I have a problem with the new asset system on Windows : http://stackoverflow.com/questions/33778766/react-native-android-static-local-image/33780354?noredirect=1#comment55335206_33780354

I have a file index.android.js in my repository App with this code :

    <Image source={require('./house.png')} style={styles.image}/>

It works if I put my image in App and in App/assets. If I just put my image in App, it doesn't work.

Then, I want write my code like this :

    <Image source={require('./img/house.png')} style={styles.image}/>

But, if I put my image in App/img, it doesn't work. Even if I add my image in App/assets/img, it doesn't work.

**Comment by WoLfulus** [comment]
I have the same issue here. The problem seems to be that react is generating invalid requests to the packager.

The asset provider (packager) serves the files well, but the request that comes from the app adds an additional dash to the URL, making it invalid.

![capture](https://cloud.githubusercontent.com/assets/412397/11262654/de3ae15e-8e68-11e5-9c42-425be0224b43.PNG)

Any solution for this?

**Comment by WoLfulus** [comment]
Changing the line

     httpServerLocation: path.join('/assets', path.dirname(relPath)),

to

     httpServerLocation: path.join('assets', path.dirname(relPath)),

Location:
 https://github.com/facebook/react-native/blob/b907f40957bbd822cfab3a56d82363ffd58d2e78/packager/react-packager/src/Bundler/index.js#L306

This solves the issue, but I'm not sure if it will create additional issues on other platforms tho.

**Comment by LaurentSouchet-Orange** [comment]
@WoLfulus It's ok for us now on Windows with your information. Thinks

**Comment by PCharpentier** [comment]
@WoLfulus Thanks for your help.

I have a similar problem with file .js
I read my globals variables in App/common/globals.js
But, when I write this code :
> var myStrings = require ('./common/gloabals');
> ...
> <Text>{myStrings.form_value_damage}</Text>
I have a white zone instead of by Text.
