### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by danidaryaweesh** [facebook/react-native#42104]
### Description

Getting this issue only when building to real devices using Xcode 15.1 and any version of iOS 17. Works with no issues when building to simulators. 

### Steps to reproduce

1. yarn install 
2. run Xcode start to a targeted device

### React Native Version

0.73.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6.3
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 299.42 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.17
    path: /usr/local/bin/yarn
  npm:
    version: 9.2.0
    path: ~/.npm-packages/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No logs, only Command PhaseScriptExecution failed with a nonzero exit code issue.
```

### Reproducer

Brand new RN project

**Comment by rafaels-dev** [comment]
I used the following code to diagnose the error on the `node_modules/react-native/scripts/react-native-xcode.sh`
```sh
err_report() {
    echo "Error on line $1"
}

trap 'err_report $LINENO' ERR
```
The function `err_report` noticed to me that the error was found on the `for num in 0 1 2 3 4 5 6 7 8`.
This `for` was created to get the local ip address of the metro server.

As you can see below, I commented the entire for and replaced with the new command, and my build is working fine now.
```sh
IP=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | head -1 | awk '{ print $2 }')
  # for num in 0 1 2 3 4 5 6 7 8; do
  #   IP=$(ipconfig getifaddr en${num})
  #   if [ ! -z "$IP" ]; then
  #     break
  #   fi
  # done
```

**Comment by danidaryaweesh** [comment]
Thanks @rafaels-dev, it turns out that my entry file was causing the issue (index.tsx). Bundling in RN only considers index.js. That was my issue, appreciate you taking your time trying to help!
