### ISSUE TITLE
[iOS] Build Fails when Scheme is set to Release

### ISSUE THREAD

**Issue by idibidiart** [facebook/react-native#4210]
Just changed the Scheme to Release based o the hint about disabling debug menu:
https://facebook.github.io/react-native/docs/debugging.html#debugging-react-native-apps

I get this error now with 0.14.2
```
Developer/Library/Frameworks'
Undefined symbols for architecture arm64:
  "_RCTSetLogFunction", referenced from:
      -[rnpocTests testRendersWelcomeScreen] in rnpocTests.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by idibidiart** [comment]
Anyone else ran into this?

**Comment by stefanopiovesn** [comment]
I have the same issue. No errors with Debug, 2 errors in Release schema
` Undefined symbols for architecture armv7:
  "_RCTSetLogFunction", referenced from:
      -[myrule1Tests testRendersWelcomeScreen] in myrule1Tests.o
ld: symbol(s) not found for architecture armv7`

**Comment by hasen6** [comment]
Getting this as well. No errors running in debug mode but have this error on release along with error "linker command failed with exit code 1 (use -v to see invocation)" in React Native 0.17

**Comment by hasen6** [comment]
Ok I had dead code stripping enabled to solve a previous error. But with this version, disabling it corrects these other errors and it builds successfully.

**Comment by Yukaii** [comment]
same issue as well...

**Comment by mattcollins** [comment]
I just hit this issue as well. After disabling dead code stripping (per @hasen6's comment), the build completed successfully.

Here's how I disabled it:

1. Opened XCode and pressed cmd + 1
2. Clicked on my project in the left panel, my target in the middle panel
3. Clicked on "Build Settings"
4. In the "Linking" section, under the "Dead Code Stripping" section, changed the setting for "Release" from "Yes" to "No"

This is just a workaround, but hopefully helpful if you're also hitting this.

**Comment by chenyu1520** [comment]
@mattcollins Nice!

**Comment by calvinf** [comment]
I ran into the same issue and had to disable dead code stripping, too.

**Comment by calvinf** [comment]
I found a solution to the problem in the comments for a previous issue:
https://github.com/facebook/react-native/issues/2685#issuecomment-142137371

I believe this issue can be closed as a duplicate.

**Comment by janicduplessis** [comment]
@facebook-github-bot duplicate #2685

**Comment by MiLeung** [comment]
My app's build succeeds, but gives me another error:

`[NSException raise:name format:@"%@", message];`

**Comment by MiLeung** [comment]
@mattcollins Your solution doesn't seem to work on 0.29.0.  I've also noticed that Facebook changed the docs for building app for production.

**Comment by longsangstan** [comment]
HI,
I have the same problem but
-it says architecture i386 instead of arm64
-it only happens when i choose iphone 5/4s simulators; other version such as 5s/6/6s don't have the problem

I tried the dead code stripping and add libReact.a to TESTS, both of them are not working for me.

Have anyone had the same problem?

**Comment by khaire1111** [comment]
Yes I have same problem
- I create objective-c custom framework and import to my project it's working 100% for debug mode.
- But whenever I build for release mode and import to my project it is getting error only for iPhone 4s, iPhone 5 and iPad 2 otherwise it's working for all.

- Error like this - Undefined symbols for i386 or x86_64. 

Please anyone tell me solution..
