### ISSUE TITLE
[Error installing boost]  Verification checksum was incorrect, expected 

### ISSUE THREAD

**Issue by kdn0325** [facebook/react-native#42110]
### Description

[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

Error occurred during React Native pod install. Please help

### Steps to reproduce

`npx react-native@latest init AwesomeProject `

`cd ios & pod install`

### React Native Version

0.73.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 355.98 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/abel/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/abel/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

 abel@Abelui-MacBookPro  ~/Desktop/AwesomeProject   main  >....
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/abel/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
[!] Error installing boost
Verification checksum was incorrect, expected 6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff
```

### Reproducer

https://github.com/kdn0325/AwesomeProject-bug-report

### Screenshots and Videos

<img width="773" alt="스크린샷 2023-12-31 오후 6 04 02" src="https://github.com/facebook/react-native/assets/91298955/a4d3eb34-d090-4bb2-896d-9b49e2f2b981">

**Comment by wswebcreation** [comment]
I've filed [this](https://github.com/boostorg/boost/issues/843) ticket for the Boost project (assuming I'm right)

Curling the file also gives a different checksum

```sh
curl -sL https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2 | shasum -a 256

5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff  -
```

**Comment by wswebcreation** [comment]
Ok, created a simple patch for this for RN 0.73.1, but everyone could do this for their version


1. **Install `patch-package`:**
   ```bash
   npm install --save-dev patch-package postinstall-postinstall
   ```

2. **Modify `boost.podspec`:**

change

```podspec
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.83.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
                  :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }

  # Pinning to the same version as React.podspec.
  spec.platforms = min_supported_versions
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end

```

to

```podspec
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.83.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  # Patched due to issue https://github.com/boostorg/boost/issues/843
  spec.source = { :http => 'https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.bz2',
                  :sha256 => '6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e' }

  # Pinning to the same version as React.podspec.
  spec.platforms = min_supported_versions
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end

```

3. **Create a Patch:**
   - Run `npx patch-package react-native` to create a patch file based on your changes. This command generates a patch file in a directory called `patches/`.

4. **Apply the Patch Automatically:**
   - Modify your `package.json` to apply the patch after installation. Add the following to your scripts section:
     ```json
     "scripts": {
       "postinstall": "patch-package"
     }
     ```
   - Now, whenever you run `npm install`, `patch-package` will automatically apply the patch to the `boost.podspec` file.

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/42109

**Comment by abdullahwt** [comment]
Solved this issue by follow these steps [Link](https://stackoverflow.com/questions/77738691/error-installing-boost-verification-checksum-was-incorrect-expected/77745446#77745446)

**Comment by netanelz-amdocs** [comment]
It started to happen again today....

**Comment by OmerWow** [comment]
> It started to happen again today....

Yeah happens to me again too...

**Comment by MartinGambit** [comment]
yea i am having same issues damn...

**Comment by OmkarK45** [comment]
Same issue : Trying to build via bitrise

**Comment by hodayaGruzm** [comment]
me toooo,

**Comment by codebycarlos** [comment]
Same 🙃

**Comment by compwron** [comment]
same

**Comment by favianCVM** [comment]
same here.

**Comment by minkgkyaw9899** [comment]
Same 🥺

**Comment by markallanevans** [comment]
Just happened to me as well (RN 0.71.14)

**Comment by LasithaOffice** [comment]
Same here

**Comment by thtRajasthaniGuy** [comment]
same here..... using react-native version 0.70.6

**Comment by doyunnn** [comment]
Same here.

**Comment by dsumayan21** [comment]
same here. react native v 0.69.9

**Comment by dintiger** [comment]
same

**Comment by shifanpark** [comment]
Same here.  react native version 0.72.6

**Comment by doanhtrinh95** [comment]
Same here. react native version 0.73.1

**Comment by mattijsf** [comment]
I don't see react-native's CI tests failing but I think that's mainly because the workflows save/restore cocoapod cache so they don't fetch boost basically.

**Comment by pietro-marrone-dka** [comment]
Same here

**Comment by matteodanelli** [comment]
Happens again from yesterday.

**Comment by loreleensablot** [comment]
Happening it again, just now

**Comment by vishal-nayak07** [comment]
Facing the same issue again

**Comment by ts-ign0re** [comment]
Guys!

DO NOT REPLACE HASHSUM

Replace this url
https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2

with
https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2

**Comment by Johan-dutoit** [comment]
https://github.com/facebook/react-native/pull/42118

**Comment by LukaBabunadze** [comment]
> https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2

Thanks!

**Comment by LukaBabunadze** [comment]
> Guys!
> 
> DO NOT REPLACE HASHSUM
> 
> Replace this url https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2
> 
> with https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2

Thanks!

**Comment by cipolleschi** [comment]
We have an official workaround and a pinned issue: https://github.com/facebook/react-native/issues/42180.
I'm locking this conversation.
