### ISSUE TITLE
Can't run React Native 0.73.1 on Android 5.1.1 

### ISSUE THREAD

**Issue by sun-jkp** [facebook/react-native#42135]
### Description

After build, install and run app on emulator. It's crash.
The emulator that I used is
-7" WSVGA(Tablet)
-Lollipop (Android 5.1)
-API Level 22

I got error message "Unfortunately, AwesomeProject has stopped." on emulator's screen.
Can Anyone help me this problem.

![Screenshot 2024-01-04 114430](https://github.com/facebook/react-native/assets/122416761/977a48b3-790b-4dd2-8495-217417496942)

### Steps to reproduce

1. npx react-native@latest init AwesomeProject
2. cd AwesomeProject
3. npx react-native start
4. npx react-native run-android
5. look at emulator

### React Native Version

0.73.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  Memory: 4.76 GB / 15.39 GB
Binaries:
  Node:
    version: 20.10.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "22"
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-22 | Intel x86_64 Atom
      - android-22 | Google APIs Intel x86 Atom
      - android-33 | Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11255304
  Visual Studio:
    - 15.9.34118.181 (Visual Studio Community 2017)
Languages:
  Java: 17.0.8
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
-
```

### Reproducer

-

### Screenshots and Videos

npx react-native doctor
![Screenshot 2024-01-04 114631](https://github.com/facebook/react-native/assets/122416761/d3db5046-59fe-4214-833a-7f65ef5b1975)

logcat files
[reeman-Android-5.1.1_2024-01-04_145112.logcat.txt](https://github.com/facebook/react-native/files/13827494/reeman-Android-5.1.1_2024-01-04_145112.logcat.txt)

**Comment by cetfu** [comment]
I think you need to provide device logs. 
And it says here that React Native 0.73 will be the last version supporting android 5.0/5.1. https://github.com/react-native-community/discussions-and-proposals/discussions/740

**Comment by sun-jkp** [comment]
> I think you need to provide device logs. And it says here that React Native 0.73 will be the last version supporting android 5.0/5.1. [react-native-community/discussions-and-proposals#740](https://github.com/react-native-community/discussions-and-proposals/discussions/740) maybe you should use newer android version
I exported log from logcat.
[reeman-Android-5.1.1_2024-01-04_145112.logcat.txt](https://github.com/facebook/react-native/files/13827490/reeman-Android-5.1.1_2024-01-04_145112.logcat.txt)

**Comment by cortinico** [comment]
This is a known issue. The fix will be in 0.73.2 which will be released in the near future.

**Comment by efstathiosntonas** [comment]
0.73.2 was released yesterday, I think this should be closed now @cortinico

**Comment by chanTanya** [comment]
i got same problem on react-native 0.73.8
