### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code.

### ISSUE THREAD

**Issue by safwanchundakkadan** [facebook/react-native#42134]
### Description

    showing error Command PhaseScriptExecution failed with a nonzero exit code.

When I am trying to play the ios project from a M2 chip Macbook Pro, it is working fine in Intel Chip.

showing error when trying to play from vscode--

The following build commands failed:

PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/safwan/Library/Developer/Xcode/DerivedData/skizzlehr-aqdqtsvzpusqzbchycwsluqghbka/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00025130.sh (in target 'React-rncore' from project 'Pods')

### Steps to reproduce

try to build the app in ios with m2 chip mac pro

### React Native Version

0.72.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/safwan/Library/Developer/Xcode/DerivedData/skizzlehr-aqdqtsvzpusqzbchycwsluqghbka/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00025130.sh (in target 'React-rncore' from project 'Pods')
```

### Stacktrace or Logs

```text
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/safwan/Library/Developer/Xcode/DerivedData/skizzlehr-aqdqtsvzpusqzbchycwsluqghbka/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-rncore.build/Script-46EB2E00025130.sh (in target 'React-rncore' from project 'Pods')
```

### Reproducer

not available

**Comment by cortinico** [comment]
Potentially a duplicate of https://github.com/facebook/react-native/issues/39609

**Comment by cortinico** [comment]
And also related to https://github.com/facebook/react-native/issues/39734

**Comment by huzaifahazelGit** [comment]
> This issue was closed because the author hasn't provided the requested feedback after 7 days.

> Have you looked through the other issues on the repo? https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+%22Command+PhaseScriptExecution+failed+with+a+nonzero+exit+code%22
> 
> In general we don't offer specific support for environ
<img width="1512" alt="Screenshot 2024-02-06 at 5 26 11 PM" src="https://github.com/facebook/react-native/assets/107028141/d06225c2-e089-4bf0-bd86-6b8e278c803f">
ment problems.
> 
> Your code looks fine to me. I suggest you seek support on StackOverflow or other forums.

I looked through the other all  issues on the repo but no any found against this error,,,,,this error occur when I have used macbook pro m2 with latest react native 0.73.4 ,node version 

System:
  OS: macOS 14.3
  CPU: (12) arm64 Apple M2 Pro
  Memory: 141.50 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.1
    path: ~/.nvm/versions/node/v21.6.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v21.6.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v21.6.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/muhammadhuzaifajunaid/.rubies/ruby-3.3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false


I have tried many ways to attempt this issue but remain failed So kindly provide exact solution

**Comment by OnurVar** [comment]
It's already mentioned in Gemfile but please make sure you're using `cocoapods` version is lower `1.15`
