### ISSUE TITLE
I am unable to Build successful as a result of org.gradle.toolchains.foojay-resolver-convention

### ISSUE THREAD

**Issue by elkee2003** [facebook/react-native#42149]
### Description

After run android on my project I get this error message
`* What went wrong:
An exception occurred applying plugin request [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.5.0']
> Failed to apply plugin class 'org.gradle.toolchains.foojay.FoojayToolchainsPlugin'.
   > FoojayToolchainsPlugin needs Gradle version 7.6 or higher

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
![Screenshot (81)](https://github.com/facebook/react-native/assets/42178058/2f602b2a-cedf-4c5a-b728-e0c1aa5cac2b)
`

### Steps to reproduce

1. npm start
2. npm run android
3. Then I get the error

### React Native Version

0.73.1

### Affected Platforms

Runtime - Desktop

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22000
  CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Memory: 488.36 MB / 7.88 GB
Binaries:
  Node:
    version: 18.14.2
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11255304      
  Visual Studio: Not Found
Languages:
  Java: 19.0.2
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
log.debug("Debug message");
log.info("Information message");
log.warn("Warning message");
log.error("Error message");
```

### Reproducer

https://github.com/elkee2003/Atua2023

**Comment by cortinico** [comment]
> FoojayToolchainsPlugin needs Gradle version 7.6 or higher

The error says clearly what's your issue.
You're on a older version of Gradle:

https://github.com/elkee2003/Atua2023/blob/75fea1c9fb62ebbf54b3148c6c6448dc9d5df3a9/android/gradle/wrapper/gradle-wrapper.properties#L3

Please look through the upgrade helper and make sure you update all the files

**Comment by renatoarg** [comment]
That is not enough, in my team there are 2 members using gradle 7.5 and FooljayToolchainsPlugin is working fine for them. On the other hand, I am using gradle 7.5 and seeing the exception.

So, there is more on this issue than the gradle version.

**Comment by makalaravikiran** [comment]
Having the same issue. Any help?

**Comment by gustavos00** [comment]
Having the same issue.

**Comment by AizenSousuke** [comment]
same issue..

**Comment by omartamer-git** [comment]
This happened to me after updating react native and then attempting to run on android (and then attempting to update gradle, which caused this error). Fix was to `npm install` after upgrading react native.

**Comment by UraFIZ** [comment]
keep this version distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip in gradle/wrapper/gradle-wrapper.properties

**Comment by eliasg52** [comment]
> keep this version distributionUrl=https://services.gradle.org/distributions/gradle-8.3-all.zip in gradle/wrapper/gradle-wrapper.properties

this works for me, thanks!

**Comment by krolow** [comment]
> keep this version distributionUrl=https://services.gradle.org/distributions/gradle-8.3-all.zip in gradle/wrapper/gradle-wrapper.properties

thx @UraFIZ  works 👍🏼

**Comment by najumasad** [comment]
> keep this version distributionUrl=https://services.gradle.org/distributions/gradle-8.3-all.zip in gradle/wrapper/gradle-wrapper.properties

**Comment by inyong-e** [comment]
>That is not enough, in my team there are 2 members using gradle 7.5 and FooljayToolchainsPlugin is working fine for them. On the other hand, I am using gradle 7.5 and seeing the exception.

It was worked for me! 
Thank you!

**Comment by dhananjay7781** [comment]
I'm having this issue Plugin [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.5.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin:0.5.0')
  Searched in the following repositories:
    MavenRepo
    Google
    Gradle Central Plugin Repository

**Comment by zamanphp** [comment]
I'm having this issue Plugin too.
 [id: 'org.gradle.toolchains.foojay-resolver-convention', version: '0.5.0'] was not found
Anyone has an idea?

**Comment by sky1412001** [comment]
This is the best Solution :-
./gradlew --stop
./gradlew build

**Comment by corwin-imp** [comment]
Had the same problem. It was http proxy ports.
this can help

 - https://dev.to/leofolive/setup-macbook-m1-for-react-native-development-4ca7
 - https://stackoverflow.com/questions/35520337/how-to-remove-jvm-property-https-proxyhost


Here is what worked for me, just write in terminal

`JAVA_OPTS="$JAVA_OPTS -DsocksProxyPort"`

 - open android studio => reset android studio caches
 - you can also insall plagin "gradle utilities" (there you can clear gradle caches)

**Comment by groupofstars** [comment]
As you can see in attached screenshot, you go to Gradle User Home folder at C:\Users\**_Username_**\.gradle and edit the file "gradle.properties" file.
```
systemProp.http.proxyHost=
systemProp.http.proxyPassword=
systemProp.http.proxyPort=4010
systemProp.https.proxyHost=13.12.174.232
systemProp.https.proxyPassword=
systemProp.https.proxyPort=4010
systemProp.https.proxyUser=***********
```
Like this, I had a setting of proxy, so I removed it.
I hope this could help you and save your time.
Best

**Comment by tmaly1980** [comment]
> This is the best Solution :- ./gradlew --stop ./gradlew build

Stopping the daemon fixed it for me, it must have been running with an old version of code.

**Comment by Shivampurbia** [comment]
Tried everything, still facing the same issue on react-native 81

**Comment by k-angama** [comment]
> This is the best Solution :- ./gradlew --stop ./gradlew build

This solution works for me, but I needed to kill all the React Native processes and then run `./gradlew clean` before building.
