### ISSUE TITLE
Error setting property on RCTBubblingEventBlock 

### ISSUE THREAD

**Issue by LionelMyFit** [facebook/react-native#42154]
### Description

Hi, i have created a **RCTViewManager** class in swift : 

`@objc(RCTSDKRecoView)
class RCTSDKRecoView: RCTViewManager {
  var myFitRecommendationView: MyFitRecommandationSDKView?
  
  override static func requiresMainQueueSetup() -> Bool {
    return true
  }
  
  @objc var onCallback: RCTBubblingEventBlock?
  
  override func view() -> UIView! {
    myFitRecommendationView = MyFitRecommandationSDKView()
    return myFitRecommendationView
  }
}
`

**and the bridge in Obj :** 

`@interface RCT_EXTERN_MODULE(RCTSDKRecoView, RCTViewManager)

RCT_EXPORT_VIEW_PROPERTY(onCallback, RCTBubblingEventBlock)

@end`

My ts : 

`<SDKRecoView
          ref={sdkRecoViewRef}
          onCallback={(result: any) => {
            console.log(result);
          }}
          style={styles.fullsize}
        />`

My goal is to trigger callback in the swift class 

I have a runtime error on the render method : 

_Error setting property 'onCallback' of RCTSDKRecoView with tag #579: Exception thrown while executing UI block: -[PodMyFitScan.MyFitRecommandationSDKView setOnCallback:]: unrecognized selector sent to instance 0x11360dce0_

### Steps to reproduce

1. Launch the application with the RCTViewManager above

### React Native Version

0.73.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 89.31 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Error setting property 'onCallback' of RCTSDKRecoView with tag #579: Exception thrown while executing UI block: -[PodMyFitScan.MyFitRecommandationSDKView setOnCallback:]: unrecognized selector sent to instance 0x11360dce0
```

### Reproducer

https://github.com/facebook/react-native

**Comment by cortinico** [comment]
Please provide a valid reproducer @LionelMyFit
