### ISSUE TITLE
myapp@0.0.1: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.3"

### ISSUE THREAD

**Issue by leminhcse** [facebook/react-native#42150]
### Description

I use react-native 0.72.7 and my node version is 14.21.3. 
In my project and when I run yarn install or yarn install --frozen-lockfile command, I get following error:
```
error myapp@0.0.1: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.3"
error Found incompatible module.
```

### Steps to reproduce

Run yarn install or yarn install --frozen-lockfile

### React Native Version

0.72.7

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 153.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3
    Yarn: 1.18.0
    npm: 6.14.18
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33, 34
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0, 33.0.2
      System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
```

### Stacktrace or Logs

```text
yarn install v1.18.0
[1/5] 🔍  Validating package.json...
error myapp@0.0.1: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.21.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by Patrick-web** [comment]
Shouldn't you just switch to node 16 and above? That is what the error is telling you.

**Comment by kelset** [comment]
yup, this is not a bug - I would highly recommend you switch your node version to at least the current LTS, Node 20: https://nodejs.org/en

**Comment by leminhcse** [comment]
> yup, this is not a bug - I would highly recommend you switch your node version to at least the current LTS, Node 20: https://nodejs.org/en

Thank @kelset , I tried to upgrade nodeJS to 18 and it works now !
