### ISSUE TITLE
[RN@0.73.1][iOS] An issue with `with-environment.sh` script

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#42164]
### Description

If I call `with-environment.sh` from XCode build phase, it fails to me here, at the line 17:
https://github.com/facebook/react-native/blob/cabae397c61ed18b2eae9c84811028857f1a72a8/packages/react-native/scripts/xcode/with-environment.sh#L15-L17

I have node installed via NVM, so `NODE_BINARY` there is empty. In my `.xcode.env` I have the correct init code
```sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```
after which that `command -v node` would work alright. But, I guess, that `NODE_BINARY` export is intentionally placed before the environment loading commands below, and thus should be somehow corrected in-place to not fail the shell script?

### Steps to reproduce

N/A

### React Native Version

0.73.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by birdofpreyru** [comment]
Agh... I see, like in another script I had problems with, it should read at the line 16:
```sh
NODE_BINARY=$(command -v node || echo "")
```

**Comment by cortinico** [comment]
Yup @birdofpreyru could you send a PR that fixes this?

**Comment by birdofpreyru** [comment]
Hey @cortinico I've created PR https://github.com/facebook/react-native/pull/42181 into [0.73-stable](https://github.com/facebook/react-native/tree/0.73-stable) branch, but I have doubts now... will you remind me, please, should be PRs done into such version branch, or into main, to not be lost in future RN versions?

**Comment by cortinico** [comment]
> will you remind me, please, should be PRs done into such version branch, or into main, to not be lost in future RN versions?

In this case, let's do the fix against `main`. We'll pick it on the release branch as needed

**Comment by birdofpreyru** [comment]
Ok @cortinico , here is the correct PR into **main** &mdash; https://github.com/facebook/react-native/pull/42184
