### ISSUE TITLE
How to close development mode on android platform

### ISSUE THREAD

**Issue by haledeng** [facebook/react-native#4217]
"JavaScript thread performance suffers greatly when running in dev mode. This is unavoidable: a lot more work needs to be done at runtime to provide you with good warnings and error messages, such as validating propTypes and various other assertions."  

From the document at [https://facebook.github.io/react-native/docs/performance.html](https://facebook.github.io/react-native/docs/performance.html), we know development mode may cause performance problems, but how to close it.

**Comment by brentvatne** [comment]
Hi @haledeng - go into the developer menu on your device (shake your phone from within a react native app to open it) and uncheck the first option on the screen

**Comment by haledeng** [comment]
Hi @brentvatne , what I mean is when we bundle the resource, how do we turn off development mode.
Because I see the app run in a development mode by default.   (In index.android.bundle file, __DEV__ = true)

**Comment by brentvatne** [comment]
https://facebook.github.io/react-native/docs/signed-apk-android.html#if-you-don-t-have-a-react-gradle-file

see the line with `react-native bundle --platform android --dev false` ... etc :smile:

**Comment by haledeng** [comment]
well, In the index.android.bundle file, the first line code is still __DEV__ = true.
I think that does not work.

**Comment by kuangc2008** [comment]
if you close DEV mode, then you can only open page from assets.
