### ISSUE TITLE
Metro Bundler is not opening automatically in both android & ios after upgrading to React native 0.73.1

### ISSUE THREAD

**Issue by prateekuttreja2020** [facebook/react-native#42173]
### Description

Metro Bundler is not opening automatically in both android & ios after upgrading from 0.72.3 to 0.73.1

we need to run manually with "npm start" command

### Steps to reproduce

1. Install the application
2. Notice the crash

### React Native Version

0.73.1

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.4.1
  CPU: (8) arm64 Apple M1
  Memory: 40.95 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/local/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.1
    wanted: 0.73.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No Bundle URL Present
```

### Reproducer

https://github.com/prateekuttreja2020/sample

### Screenshots and Videos

![Simulator Screenshot - iPhone 14 Pro - 2024-01-05 at 17 48 52](https://github.com/facebook/react-native/assets/65911005/0d93377a-2814-4914-9951-c8ed2f84dbfc)

**Comment by cortinico** [comment]
Duplicates https://github.com/react-native-community/cli/issues/2155

This will be fixed in 0.73.2 which will be out in the near future

Also you already reported this same issue 3 days ago:
https://github.com/facebook/react-native/issues/42152

Please refrain from cloning more issues.

**Comment by Shahzaib114** [comment]
> Duplicates [react-native-community/cli#2155](https://github.com/react-native-community/cli/issues/2155)
> 
> This will be fixed in 0.73.2 which will be out in the near future
> 
> Also you already reported this same issue 3 days ago: #42152
> 
> Please refrain from cloning more issues.

0.73.2 version has the same issue too!

**Comment by Shahzaib114** [comment]
For now, you can downgrade your version of react native to 0.72.9. most probably, metro working on this version

> ### Description
> 
> Metro Bundler is not opening automatically in both android & ios after upgrading from 0.72.3 to 0.73.1
> 
> we need to run manually with "npm start" command
> ### Steps to reproduce
> 
>     1. Install the application
> 
>     2. Notice the crash
> 
> 
> ### React Native Version
> 
> 0.73.1
> ### Affected Platforms
> 
> Runtime - Android, Runtime - iOS
> ### Output of `npx react-native info`
> 
> ```
> System:
>   OS: macOS 13.4.1
>   CPU: (8) arm64 Apple M1
>   Memory: 40.95 MB / 16.00 GB
>   Shell:
>     version: 3.2.57
>     path: /bin/bash
> Binaries:
>   Node:
>     version: 20.10.0
>     path: ~/.nvm/versions/node/v20.10.0/bin/node
>   Yarn: Not Found
>   npm:
>     version: 10.2.3
>     path: ~/.nvm/versions/node/v20.10.0/bin/npm
>   Watchman: Not Found
> Managers:
>   CocoaPods:
>     version: 1.14.3
>     path: /usr/local/bin/pod
> SDKs:
>   iOS SDK:
>     Platforms:
>       - DriverKit 22.4
>       - iOS 16.4
>       - macOS 13.3
>       - tvOS 16.4
>       - watchOS 9.4
>   Android SDK: Not Found
> IDEs:
>   Android Studio: 2021.3 AI-213.7172.25.2113.9014738
>   Xcode:
>     version: 14.3/14E222b
>     path: /usr/bin/xcodebuild
> Languages:
>   Java:
>     version: 17.0.9
>     path: /usr/local/opt/openjdk@17/bin/javac
>   Ruby:
>     version: 2.6.10
>     path: /usr/bin/ruby
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: 18.2.0
>   react-native:
>     installed: 0.73.1
>     wanted: 0.73.1
>   react-native-macos: Not Found
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: false
> iOS:
>   hermesEnabled: true
>   newArchEnabled: false
> ```
> 
> ### Stacktrace or Logs
> 
> ```
> No Bundle URL Present
> ```
> 
> ### Reproducer
> 
> https://github.com/prateekuttreja2020/sample
> ### Screenshots and Videos
> 
> ![Simulator Screenshot - iPhone 14 Pro - 2024-01-05 at 17 48 52](https://private-user-images.githubusercontent.com/65911005/294823991-0d93377a-2814-4914-9951-c8ed2f84dbfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzk2NzEsIm5iZiI6MTcwNTAzOTM3MSwicGF0aCI6Ii82NTkxMTAwNS8yOTQ4MjM5OTEtMGQ5MzM3N2EtMjgxNC00OTE0LTk5NTEtYzhlZDJmODRkYmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA2MDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NmQyZjI1ZjhmY2UxMmNhMTIxNWM2ZGEyMTVkMjMwZDhlMWMxNmIxY2MyZTAwZjkxYzI3M2I3NmZhM2QzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j5ZM_07t747tSCcr6J-q3VeLM39rujCXJaygQuDiIUg)

**For now, you can downgrade your version of react native to 0.72.9. most probably, metro working on this version**

**Comment by phamhieu1412** [comment]
same issue, i use both 0.73.2 or 0.73.1 
what is your solution??

**Comment by cortinico** [comment]
> same issue, i use both 0.73.2 or 0.73.1

This has been fixed in 0.73.3

**Comment by phamhieu1412** [comment]
> > same issue, i use both 0.73.2 or 0.73.1
> 
> This has been fixed in 0.73.3

what? i see new version is 0.73.2, are you sure ?

**Comment by jcarioti** [comment]
> > same issue, i use both 0.73.2 or 0.73.1
> 
> This has been fixed in 0.73.3

Any idea for a deployment date for 73.3?

**Comment by timothyerwin** [comment]
Same problem 0.73.2

**Comment by mihailapuste** [comment]
> > > same issue, i use both 0.73.2 or 0.73.1
> > 
> > 
> > This has been fixed in 0.73.3
> 
> Any idea for a deployment date for 73.3?

@jcarioti Im dealing with the same issue, but it seems to persist in 73.3

**Comment by usmanabid94** [comment]
I am also facing the same issue metro won't start automatically had to run the npm start command to run it on 0.72.4

**Comment by a-kova** [comment]
I'm having the same issue on freshly installed 73.3. However, this error only appears when I start an app from XCode. If I run it from CLI it works.

**Comment by mihailapuste** [comment]
> I'm having the same issue on freshly installed 73.3. However, this error only appears when I start an app from XCode. If I run it from CLI it works.

This is intended: Metro will no longer be started when running builds via Xcode ([dc6845739e](https://github.com/facebook/react-native/commit/dc6845739e29ea8cf63583d530f67c2498286a3e) by [@huntie](https://github.com/huntie))

**Comment by a-kova** [comment]
oh, got it, thanks!

**Comment by gkasireddy202** [comment]
I built my project in react-native:0.73.7 and did not show metro in iOS and Android release mode.
Metro bundler showing in debug mode only. Any thoughts?

<img width="646" alt="Screenshot 2024-05-17 at 1 12 50 PM" src="https://github.com/facebook/react-native/assets/90603484/0363c596-de46-4588-8ca8-b32ff5faa802">
