### ISSUE TITLE
Text is not displayed on Android physical device after 0.73.0

### ISSUE THREAD

**Issue by dhruvpvx** [facebook/react-native#42196]
### Description

Since version 0.73.0 text in the Text component is not displayed on a physical connected Android device.

It works well both on Android Studio Emulator (tested with API 33 and API 34) and on physical connected device with react native below 0.73.0

Tested on two different physical devices

If I add background color to it, Text component would be visible, but content is not. Also, text is visible in TextInput component. Text in error logs is not visible too, but visible in loading log (at the very top of the application)

### Steps to reproduce

1.Install the application on physical Android device (OnePlus 9r or 9rt With Custom Rom, It is Working Fine In stock rom tested in multiple 9r devices)
2.Notice that any text in the Text component is not displayed

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.1.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 101.45 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 10.2.5
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/dheerajgour/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
No Logs just clean terminal
```

### Reproducer

https://github.com/crawraps/reproducer

### Screenshots and Videos

![Screenshot_20240109-120824_Reproduce](https://github.com/facebook/react-native/assets/59329978/b3fbe669-e730-40eb-9bb6-0a45070a213f)

**Comment by dhruvpvx** [comment]
> ⚠️	Missing Reproducible Example
> ℹ️	We could not detect a reproducible example in your issue report. Please provide either:
> * If your bug is UI related: a [Snack](https://snack.expo.dev)
> * If your bug is build/update related: use our [Reproducer Template](https://github.com/react-native-community/reproducer-react-native/generate). A reproducer needs to be in a GitHub repository under your username.

it can we reproduced very easily in a fresh generated react native project just need a oneplus 9r or 9rt device with custom rom

**Comment by cortinico** [comment]
Duplicates #42089 

Let's keep the conversation there
