### ISSUE TITLE
Not Getting Scroll Positions From ReactRootView In Android

### ISSUE THREAD

**Issue by Mukuljangir372** [facebook/react-native#42226]
### Description

Getting Scroll X And Y positions 0 after scrolling up and down from `ReactRootView` In Android. For instance, `ReactRootView` inside `FrameLayout` gets scrolled down or up. `ReactRootView` returning Scroll Y 0.

### Steps to reproduce

1. Integrate ReactRootView Inside FrameLayout In Android
2. Scroll Up Or Down
3. Observe Scroll Y In ReactRootView

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
Device
Name - Samsung
Model - M31
RAM - 8GB
```

### Reproducer
1. Integrate ReactRootView Inside FrameLayout In Android
2. Scroll Up Or Down
3. Observe Scroll Y In ReactRootView

Actual Result : Scroll Y value is zero.
Excepted Result : Scroll Y value should be equal to scrolled y as per scrolled list.

**Comment by cortinico** [comment]
Please fill the issue template correctly

**Comment by Mukuljangir372** [comment]
Hi @cortinico Thanks for your reply! What details you require? It would be happy to share the details.

**Comment by cortinico** [comment]
Definitely the `npx react-native info` + a reproducer using the linked tempalte
