### ISSUE TITLE
Build target hermes-engine: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by yedi97** [facebook/react-native#42221]
### Description

I am facing the following problem after running my project again, the pod installed successfully without any problem, but when running using yarn run ios command, the error as below occurs, has anyone encountered this? like me? please help me. Yesterday I ran React Native version 0.73.1 and it still worked fine. Today, when I upgraded to 0.73.2, the following problem occurred. I also downgraded back to 0.73.1 but still no luck.

![image](https://github.com/facebook/react-native/assets/20843653/4e099341-cd31-462c-a795-807fcab69c40)

### Steps to reproduce

1. rm -rf node_modules && rm -rf yarn.lock && yarn install  
2. cd ios && rm -rf Pods/ && rm -rf Podfile.lock && pod install
3. cd .. && yarn ios

### React Native Version

0.73.2

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1
  Memory: 476.27 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.73.2
    wanted: ^0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Build target hermes-engine of project Pods with configuration Release

warning: Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')


Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.

PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Library/Developer/Xcode/DerivedData/myProjectName-gzdlehmipieiindfjyfrhhcjupam/Build/Intermediates.noindex/ArchiveIntermediates/myProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/hermes-engine.build/Script-46EB2E0002C950.sh (in target 'hermes-engine' from project 'Pods')

Node found at: /var/folders/d5/f1gffcfx27ngwvmw8v8jdm7m0000gn/T/yarn--1704767526546-0.12516067745295967/node

/Library/Developer/Xcode/DerivedData/myProjectName-gzdlehmipieiindfjyfrhhcjupam/Build/Intermediates.noindex/ArchiveIntermediates/myProjectName/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/hermes-engine.build/Script-46EB2E0002C950.sh: line 9: /var/folders/d5/f1gffcfx27ngwvmw8v8jdm7m0000gn/T/yarn--1704767526546-0.12516067745295967/node: No such file or directory

Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducer

https://github.com/yedi97/reproducer-react-native

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/20843653/605490bc-ff8d-473c-8748-0acbb8c0ffad)

**Comment by DAMHONGDUC** [comment]
same here

**Comment by yedi97** [comment]
> <img alt="Screenshot 2024-01-10 at 10 51 35" width="269" src="https://private-user-images.githubusercontent.com/58001785/295443949-7d7ddf2f-ad8a-4175-8518-f7fa44e4b36c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NTkxMjYsIm5iZiI6MTcwNDg1ODgyNiwicGF0aCI6Ii81ODAwMTc4NS8yOTU0NDM5NDktN2Q3ZGRmMmYtYWQ4YS00MTc1LTg1MTgtZjdmYTQ0ZTRiMzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAzNTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTUzMjBkNGM1OTVkNDY1N2MzZGVjMGM5NTQ0OThmMDJhZDJkOGQ3ZDA3Mjg5Njk4NWVhZDBkMzBkYzQ0ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wx8myRRk7bqH0rOCZxQImJ5EsWSwMALBBw8dxKCEzSQ">
> same here

haizz, it took me more than a day but I still can't fix it, even though I tried many ways

**Comment by yedi97** [comment]
I'm resolved from https://github.com/facebook/react-native/issues/36762#issuecomment-1755400555, thanks all!

**Comment by GunnarAK** [comment]
This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.

Source: https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316

**Comment by denka9999** [comment]
@GunnarAK thanks my friend!!! It worked for me

**Comment by patras1** [comment]
Hi,
I'm still facing the issue I tried the comment below it didn't work. ( in iOS )

I also tried to disable the herms by :  :hermes_enabled => false.

Any suggestions?

> This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> 
> Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)

**Comment by MarlonAEC** [comment]
That' didn't work for me, still struggling with this issue. Any clue how to solve it?

**Comment by OnurVar** [comment]
It's already mentioned in Gemfile but please make sure you're using `cocoapods` version is lower `1.15`

**Comment by tuanngocptn** [comment]
I just fixed with issue by linking the Node to `/usr/local/bin/node`.
First you need to find out the real Node PATH by 
```sh
command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
```
Then Link that to `/usr/local/bin/node`.
```sh
ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
```
Or short cut with:
```sh
ln -s $(command -v node) /usr/local/bin/node
```
hope that will help you.

**Comment by usamaabutt** [comment]
> This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> 
> Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)

Thanks this saved me to waste more time.

**Comment by DevNvll** [comment]
I had this problem when changing the node version via nvm. I was just using `nvm use lts/iron`
It worked when I used `nvm alias default lts/iron`. I also deleted the .xcode.env.local file

**Comment by SachinRajyaguru** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

It's working on me

**Comment by christophelebris-fulll** [comment]
With react-native 0.74.2 none of the proposed fix above work

**Comment by alexlic** [comment]
Same on my end, non of the fixes mentioned above seems to work on react-native 0.74.2

**Comment by MrSolimanKing** [comment]
> Same on my end, non of the fixes mentioned above seems to work on react-native 0.74.2

Have you figured out the solution, I tried all previous solutions but there is nothing worked with me with react-native 0.74.3

**Comment by johnfruit** [comment]
> > Same on my end, non of the fixes mentioned above seems to work on react-native 0.74.2
> 
> Have you figured out the solution, I tried all previous solutions but there is nothing worked with me with react-native 0.74.3

same issue for me I can't build on my xode using "react-native": "^0.74.3",

**Comment by MrSolimanKing** [comment]
I faced this issue when I upgraded my React native app from version `0.72` to `0.74.3` I tried all other solutions but nothing worked I ended up creating a new project using `npx @react-native-community/cli@latest init AwesomeProject` it was a hard time to copy my old project files and native side code to the new one but eventually it worked fine

**Comment by Jmzp** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

This works for me!, Many thanks!

**Comment by webtamizhan** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

This is working

**Comment by ashuvssut** [comment]
if you are doing expo development builds, then do `прх ехро prebuild --clean` and try again

**Comment by djkad** [comment]
> > I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> > ```shell
> > command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then Link that to `/usr/local/bin/node`.
> > ```shell
> > ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or short cut with:
> > ```shell
> > ln -s $(command -v node) /usr/local/bin/node
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > hope that will help you.
> 
> This is working

Life Saver. This worked for me too

**Comment by lanhuyun** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

Thx a lot. This worked for me. My react native version is 0.74.5.

**Comment by flacito** [comment]
https://github.com/facebook/react-native/issues/42221#issuecomment-2067908859

Very applicable if you use nvm and switch node versions.

Small improvement just in case you run often: `ln -s $(command -v node) /usr/local/bin/node`

**Comment by flacito** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

Particularly if you are switching node versions with nvm.  Thanks!

**Comment by atanu-crescentek** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.
This helped thanks .

**Comment by vatsal1302** [comment]
I just upgrade my project to 0.70.13 to 0.75.1 . I have the same issue while upgrading.  Is there any solution??

**Comment by Rodrigo816** [comment]
In my case on .xcode.env I changed to this
`export NODE_BINARY="/usr/local/bin/node"`

and run the command
`ln -s $(command -v node) /usr/local/bin/node`

solved the problem for me

**Comment by jon-eubank** [comment]
In my case (RN 0.73.9) when I ran "pod install" it was automatically generating the .xcode.env.local if it didn't already exist.  The NODE_BINARY it was setting in that file was set to a location of node, but it wasn't the same as the location that appeared when I would run "which node".  

After replacing the default NODE_BINARY location with the path from "which node" everything worked correctly.

**Comment by christophelebris-fulll** [comment]
Finally found the solution for RN 0.74.5 (might work for any version starting from 0.73). For those like me who tried the solutions above, the missing piece of the puzzle could be the node install cleaning.

### Clean node install

- I installed nvm then added `[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  # This loads NVM ` to the end of my `~/.zshrc `
- I uninstalled node completely from my machine 
- Then used nvm to reinstall it (node version 18), the command `which node` gives me `/Users/username/.nvm/versions/node/v18.20.4/bin/node` (which is the same result as `command -v node`)
- Deleted `/usr/local/bin/node`
- Relinked node with the command below 
```
ln -s $(command -v node) /usr/local/bin/node
```


### Side notes 

I didn't delete `.xcode.env.local` which contains `export NODE_BINARY=$(which node)`

I do have the following patch for "find-node-for-xcode.sh"

```
diff --git a/node_modules/react-native/scripts/find-node-for-xcode.sh b/node_modules/react-native/scripts/find-node-for-xcode.sh
index a36bbc2..c7b9321 100644
--- a/node_modules/react-native/scripts/find-node-for-xcode.sh
+++ b/node_modules/react-native/scripts/find-node-for-xcode.sh
@@ -4,7 +4,7 @@
 # This source code is licensed under the MIT license found in the
 # LICENSE file in the root directory of this source tree.
 
-set -e
+set +e
 
 # WHY WE NEED THIS:
 # This script is used to find a valid instance of `node` installed in the machine.
 ```

**Comment by PulasthiAbey** [comment]
The best solution for this is to delete the `ios/projectname.xcodeproj/project.pbxproj` file it self and try building the project in the XCode. It sorted out the issues for me

**Comment by omar-diop** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

Thanks a lot! This is working with XCode 15 , nvm and react-native 0.74.5

**Comment by tenztshering** [comment]
I have resolved it by changing:
export NODE_BINARY=/opt/homebrew/bin/node
in ios > .xcode.env.local
and updating dependency packages like react, react native etc...

**Comment by saxenanickk** [comment]
The above solution working fine when you are installing Cocoapods using `pod install`.
But somehow it doesn't work when you have script which takes care of pod installation. Along with some environment variables.

The issue here is it creates a `.xcode.env.local` with a temporary version of node. This path usually starts with `/var`

**Comment by thadshap** [comment]
> > This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> > Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)
> 
> Also working here for a recent project upgraded to RN 0.73.6 🎉

This really worked for me. I deleted my .xcode.env file and ran pod install, but that didn't work. Then, I also deleted .xcode.env.local and ran pod install again. That worked for me when I built my project in Xcode.

**Comment by YasirNaeem25** [comment]
i solved this by adding .xcode.env.local in IOS folder 
export NODE_BINARY=<static_node_path>
<img width="341" alt="Screenshot 2024-12-19 at 10 39 49 AM" src="https://github.com/user-attachments/assets/715b420d-11d6-4420-9a63-5b34418465f4" />

1-open xcode press cmd+shift+k
2- cmd+shift+b

**Comment by AmirDiafi** [comment]
> I just fixed with issue by linking the Node to `/usr/local/bin/node`. First you need to find out the real Node PATH by
> 
> ```shell
> command -v node # in my machine that show => /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node
> ```
> 
> Then Link that to `/usr/local/bin/node`.
> 
> ```shell
> ln -s /Users/runner/hostedtoolcache/node/18.20.2/arm64/bin/node /usr/local/bin/node
> ```
> 
> Or short cut with:
> 
> ```shell
> ln -s $(command -v node) /usr/local/bin/node
> ```
> 
> hope that will help you.

That works: mac m3

**Comment by eramudeep** [comment]
facing same issue 
nothing helps.  tried multiple things
1. Deleting .xcode.env.local
2. Adding .xcode.env.local
3. Adding static path
4. Removing pods and reinstalling

**Comment by SGarcia710** [comment]
> facing same issue nothing helps. tried multiple things
> 
> 1. Deleting .xcode.env.local
> 2. Adding .xcode.env.local
> 3. Adding static path
> 4. Removing pods and reinstalling

Literally this made my day. Basically the node path at .xcode.env is not working and in order to avoid modifying it we can replace it with a hardcoded local route in our .xcode.env.local :) 

working like charm now!

**Comment by MuhammadAmann** [comment]
> This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> 
> Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)

this also worked for me, Thanks

**Comment by mikemilla** [comment]
> > This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> > Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)
> 
> this also worked for me, Thanks

This works for me as well. My xcode env local file was using node 18 and my machine was using 22.

**Comment by kjgetcarnera** [comment]
**Solution That Worked for Me:**
The problem was caused by a stale .xcode.env.local file that pointed to a removed Node.js version.

**Steps to Fix:**
Delete the .xcode.env.local file:

rm ~/.xcode.env.local
Reinstall dependencies and clean the project:

cd ios
rm -rf Pods Podfile.lock
pod install
cd ..
Clean and rebuild the project:

npx react-native run-ios


**Why This Works:**
.xcode.env.local stores environment variables and can contain outdated paths for Node.js after an upgrade.
Deleting it allows Xcode to use the correct Node.js path.

**Comment by gayanrathnayaka** [comment]
None of the suggested solutions works for me

Xcode version 16.3
React Native Version 0.79.1

**Comment by fadhildwia** [comment]
please for 
Xcode version 16.3
React native version 0.72.7

**Comment by Buddhaa97** [comment]
As mentioned above, export NODE_BINARY=<static_node_path> worked. Although I already had the static path, I was still encountering this issue. I later noticed that my path was not wrapped in double quotes (""), and adding them resolved the problem.
export NODE_BINARY="/Users/xx/.nvm/versions/node/xx.xx.x/bin/node"

**Comment by carlgrob5171989** [comment]
> None of the suggested solutions works for me
> 
> Xcode version 16.2 React Native Version 0.79.1

Did you resolve the issue?

**Comment by gayanrathnayaka** [comment]
> > None of the suggested solutions works for me
> > Xcode version 16.2 React Native Version 0.79.1
> 
> Did you resolve the issue?

In my case, the problem was due to an incorrect REACT_NATIVE_PATH. The error message pointed to a specific script—when I opened that script in my editor, I saw it was trying to reference REACT_NATIVE_PATH, but the path it was using didn’t exist.

To fix it, I defined the correct REACT_NATIVE_PATH as a user environment variable. Once I did that, the issue was resolved.

Carefully read the full error message it usually mentions the script where the error originates. Open that script to investigate further; it often provides valuable clues.

**Comment by aybarska** [comment]
in build phases, under "bundle react native and images" there is a export to rnxcode.sh just add quotes to path

export NODE_BINARY="node
../node_modules/react-native/scripts/react-native-xcode.sh"

**Comment by SherryLinn** [comment]
> This issue was fixed for me by deleting `ios/.xcode.env.local`. Then I ran `pod install` and installed the app successfully on my device.
> 
> Source: [#36762 (comment)](https://github.com/facebook/react-native/issues/36762#issuecomment-1782525316)

It's very helpful for me.Thanks very much!!

**Comment by vincicat** [comment]
If you see the error message contains "Node found at: [NON-EXIST PATH]", that is your `ios/.xcode.env.local`'s fault, delete it or update the path should work

**Comment by SherryLinn** [comment]
您好！您发送的邮件我已收到。谢谢！
