### ISSUE TITLE
Keyboard keeps closing when typing on textinput on android 

### ISSUE THREAD

**Issue by Mehdise04** [facebook/react-native#42246]
### Description

we have a problem with our app on some ANDROID devices (working fine on IOS), whenever we try to type something on textinput the keyboard keeps closing we tried so many solutions, we even thought the problem might be with react-native migration, so we migrated from react native 0.65 to 0.71.1, it solved the problem at the first try but when i generated another bundle and tested it we faced the same problem again, on some android devices not all of them like always.
 
 i tried the solutions on this issue https://github.com/facebook/react-native/issues/33164 but didn't work, cleared the caches many times removed node_modules and re installed all but same problem. 
 
we dont know exactly what is the problem, we getting claims from our users that they cannot change their informations on the app and stuff like that and that is really frustrating.

https://github.com/facebook/react-native/assets/73404509/b668105e-9be0-4940-94a2-5bc80063da89

thanks in advance.

 

### Steps to reproduce

1. yarn install.
2. build the app and working fine on simulator.
3. generate signed release bundle.
4. test it on real device, and the problem appears.

### React Native Version

0.71.1

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 65.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.2, 34.0.0
      System Images: android-33 | Android TV ARM 64 v8a, android-33 | Android TV Intel x86 Atom, android-33 | Google TV ARM 64 v8a, android-33 | Google TV Intel x86 Atom, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play ARM 64 v8a, android-33 | Google Play Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.1 => 0.71.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
.
```

### Environment

- "@react-navigation/bottom-tabs": "^6.0.9",
- "@react-navigation/core": "^6.1.0",
- "@react-navigation/native": "^6.0.6",
- "@react-navigation/native-stack": "^6.2.5",
- "@react-navigation/stack": "^6.0.11",
- "react": "18.2.0",
- "react-native": "0.71.1",
- "react-native-screens": "~3.10.2",
- "redux": "^4.0.5",
- "redux-thunk": "^2.3.0",
- node version : v14.18.1
- kotlin_version="1.7.10"
- distributionUrl= url////// gradle-7.5.1-bin.zip

### Reproducer

react native textInput

<TextInput
          style={styles.input}
          value={searchValue}
          placeholderTextColor={theme.colors.gray6}
          placeholder={I18n.trans('Votre recherche ici ...')}
          onChangeText={search => handleSearch(search)}
        />

### Screenshots and Videos

https://github.com/facebook/react-native/assets/73404509/5f1a8e9a-a1a3-4f22-b5de-9f394030e54e

**Comment by Mehdise04** [comment]
update: 
hope this helps but we found out that when moving to some screens it works then when moving to other screens it fails again :/.

**Comment by cortinico** [comment]
Without a reproducer we can't help here sadly. Please provide a reproducer

**Comment by Mehdise04** [comment]
> Without a reproducer we can't help here sadly. Please provide a reproducer

tbh i dont know how to do that in a correct way but i added the text input im using, and tried to add some packages im using with versions. hope that helps
