### ISSUE TITLE
Yoga error: invalid value 'c++20' in '-std=c++20' on Xcode iOS 

### ISSUE THREAD

**Issue by JuanHernandezAlonso** [facebook/react-native#42260]
### Description

Im on MacBook Pro, macOS Catalina 10.15.17 with Xcode 12.4, ruby version 3.3.0 and using react native 0.73.1.

When trying to build the app it return and error when compiling event.cpp of Yoga.
For what I've read, a possible solution for this was to change the C++ Language Dialect in the build settings, but didn't work for me.

### Steps to reproduce

1. install and select Ruby 3.3.0
2. init a new react native project
3. bundle install in project root
4. cd ./iOS
5. pod install --repo-update
6. open project with xcode
7. build

### React Native Version

0.73.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 10.15.7
  CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Memory: 39.95 MB / 8.00 GB
  Shell:
    version: 5.7.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.5
    path: ~/Downloads/GestorumCli/node_modules/.bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/user/.rvm/rubies/ruby-3.3.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 14.4
      - DriverKit 20.2
      - macOS 11.1
      - tvOS 14.3
      - watchOS 7.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 12.4/12D4e
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.3.0
    path: /Users/user/.rvm/rubies/ruby-3.3.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
error: invalid value 'c++20' in '-std=c++20'
note: use 'c++98' or 'c++03' for 'ISO C++ 1998 with amendments' standard
note: use 'gnu++98' or 'gnu++03' for 'ISO C++ 1998 with amendments and GNU extensions' standard
note: use 'c++11' for 'ISO C++ 2011 with amendments' standard
note: use 'gnu++11' for 'ISO C++ 2011 with amendments and GNU extensions' standard
note: use 'c++14' for 'ISO C++ 2014 with amendments' standard
note: use 'gnu++14' for 'ISO C++ 2014 with amendments and GNU extensions' standard
note: use 'c++17' for 'ISO C++ 2017 with amendments' standard
note: use 'gnu++17' for 'ISO C++ 2017 with amendments and GNU extensions' standard
note: use 'c++2a' for 'Working draft for ISO C++ 2020' standard
note: use 'gnu++2a' for 'Working draft for ISO C++ 2020 with GNU extensions' standard
warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'Yoga' from project 'Pods')
Command CompileC failed with a nonzero exit code
```

### Reproducer

https://github.com/JuanHernandezAlonso/AwesomeProject.git

### Screenshots and Videos

Reproducer not stetted, just created it

**Comment by iBotPeaches** [comment]
Fairly sure Xcode 15 is required for a large chunk of c++20. You can confirm yourself here: https://developer.apple.com/xcode/cpp/

**Comment by NickGerleman** [comment]
> Xcode 12.4

This is way to old. 0.73 Requires 14.1, and App store requires 14.1 to ship to app store.

**Comment by NickGerleman** [comment]
> Fairly sure Xcode 15 is required for a large chunk of c++20. You can confirm yourself here: https://developer.apple.com/xcode/cpp/

We have intentionally been avoiding interesting usages of it incompatible with older XCode, but this may shift in 0.74 as Apple this April will require XCode 15 to ship to app store.

**Comment by wakabaa** [comment]
Hi, I encountered a similar issue while working with React Native and Firebase Crashlytics. I was facing the invalid value 'c++20' in '-std=c++20' error when building for iOS, and I resolved it by updating my Podfile.
Here's the solution that worked for me:

Open your Podfile and add the following post_install block:

`post_install do |installer|
  installer.pods_project.targets.each do |target|
    # 针对 FirebaseCrashlytics pod 修改 C++ 标准
    if target.name == 'FirebaseCrashlytics'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      end
    end

    # 设置 iOS 部署目标
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end`

After updating the Podfile, run pod install to apply the changes.

Try rebuilding the project again in Xcode.

These changes ensure that the minimum iOS version is correctly set, and the C++ standard is properly configured to avoid the error. This solution worked for me, and I hope it helps you as well!

I'm just a beginner with iOS development, and I found this solution through researching online. I don’t fully understand the exact reason why these settings work, but they resolved the issue for me.
