### ISSUE TITLE
Rename existing project?

### ISSUE THREAD

**Issue by sankhadeeproy007** [facebook/react-native#4227]
Is there any way I can rename an existing project? Which flies do I need to change to make sure everything works fine.

**Comment by offbye** [comment]
for androd, just change the gradle file and strings.xml
the path is /android/app/build.gradle, ./android/app/src/main/res/values/strings.xml

**Comment by sankhadeeproy007** [comment]
@offbye Thanks, but what if it's an iOS only project? Where do I rename?

**Comment by offbye** [comment]
Info.plist ,  find bundle name

**Comment by brentvatne** [comment]
grep the project for that name. If you have further issues with renaming the project please get help on StackOverflow or Discord, as per our README :)

**Comment by sankhadeeproy007** [comment]
Sure! @brentvatne Sorry for putting it here.

**Comment by brentvatne** [comment]
no problem @sankhadeeproy007! I hope you were able to resolve this

**Comment by SpyKing** [comment]
I was able to rename my react native project by changing the name and displayName in app.json. Mind you, this does not change the name of the Android app, for that, go to strings.xml and change the app_name field there.

**Comment by lukecwilliams** [comment]
Posted a complete open source step-by-step from the info we found scattered around the web for renaming an RN project: https://github.com/2MR/renaming-a-react-native-project
