### ISSUE TITLE
what difference between constructor and getInitState?

### ISSUE THREAD

**Issue by Jerrylingit** [facebook/react-native#4228]
Recently I read some codes about React Native.And some are using constructor to init the component, the other is using getInitState , apparently they both work well. But I want to know what difference between them. 
I guess if constructor suit for ES6 and getInitState is the old version?
please save my curiosity……

getInitState code like this
var photographyService = React.createClass({
  propTypes:{
      operate : PropTypes.string,
      goodsID : PropTypes.string,
    },

  getInitialState: function(){
    return{
      sourceDic : null, 
      isShowLimit : false, 
      limitOption : null, 
      changeValue : null,
      changeValueOfKey : null, 
      content_array : new Array(),  
      timeZoneOffsetInHours: (-1) * (new Date()).getTimezoneOffset() / 60,
      date: new Date(),
      showDatePickerView : false,
      KeyBoardHeight : 0,
      is_loading:false,
      saving : false
    };  
  },

And constructor like this
  	constructor(props) {
        super(props);
        this.state = {
          _text_off_y:0,
          KeyBoardHeight:0,
          is_loading:false,
          subscription:null,
          notificationCenter:null,
          _current_select:0,
   }

**Comment by adarshmuthappa** [comment]
Constructor is for ES6 compliance

**Comment by Jerrylingit** [comment]
ok,thks@adarshmuthappa

**Comment by christopherdro** [comment]
@adarshmuthappa Is correct.
@Jerrylingit Could you close this issue out if it answered your question? Thanks!
