### ISSUE TITLE
Pressable and View lose background colour on iOS, when borderStyle is "dashed" or "dotted", and borderWidth is 0

### ISSUE THREAD

**Issue by l1m2p3** [facebook/react-native#42289]
### Description

`Pressable` and `View` lose `backgroundColor` on iOS, when`borderStyle` is `"dashed"` or `"dotted"`, and `borderWidth` is 0.

### Steps to reproduce

1. create vanilla RN app
2. add a View and Pressable
3. set their `borderStyle` to either `"dotted"` or `"dashed"`, and `borderWidth` to 0, and `backgroundColor` to something more visible (e.g, `"red"`)
4. observe they don't have the `backgroundColor`set
5. change either `borderStyle` to something else (e.g. "solid"), or `borderWidth` to bigger than 0 (e.g. 0.001)
6. observe `backgroundColor` is set correctly

### React Native Version

0.73.2

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
n/a
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

https://snack.expo.dev/@l1m2p3/pressable-view-losing-backgroundcolor-bug?platform=ios

### Screenshots and Videos

https://github.com/facebook/react-native/assets/6405712/20fb7868-6fbd-4791-841f-6e22fa4db6a0

**Comment by l1m2p3** [comment]
Updated RN Version from 0.73 to 0.73.2 that can be parsed

**Comment by shubhamguptadream11** [comment]
I am working on fixing this.

**Comment by shubhamguptadream11** [comment]
Raised a PR to fix this: https://github.com/facebook/react-native/pull/45430

**Comment by shubhamguptadream11** [comment]
@l1m2p3  This is fixed here https://github.com/facebook/react-native/pull/45430

**Comment by shubhamguptadream11** [comment]
@cortinico This issue is fixed in above mentioned PR. We can close this issue now.
