### ISSUE TITLE
CocoaPods could not find compatible versions for pod "React-FabricImage"

### ISSUE THREAD

**Issue by softmarshmallow** [facebook/react-native#42296]
### Old Version

0.72.6

### New Version

0.73.2

### Description

I've upgraded react-native version to 0.73.2 due to solve this https://github.com/facebook/react-native/issues/39441 issue.
I'm using RN with expo, yet expo does not has a version other then `50.0.0-preview.11` with 0.73.x support.

I've upgraded both expo and react-native, and I'm getting below pod install error while building / running for ios.

```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "React-FabricImage":
  In Podfile:
    React-FabricImage (from `../node_modules/react-native/ReactCommon`)

Specs satisfying the `React-FabricImage (from `../node_modules/react-native/ReactCommon`)` dependency were found, but they required a higher minimum deployment target.

pod install --repo-update --ansi exited with non-zero code: 1
✨  Done in 12.94s.
```

### Steps to reproduce

Create expo project with `npx create-expo-app`
Both upgrade react-native (0.73.x) and expo (50.0.0-preview.x)
Run for ios, fails.

(same error log as above)

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (24) arm64 Apple M2 Ultra
  Memory: 28.32 GB / 128.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: ^0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```
```


### Stacktrace or Logs

```text
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "React-FabricImage":
  In Podfile:
    React-FabricImage (from `../node_modules/react-native/ReactCommon`)

Specs satisfying the `React-FabricImage (from `../node_modules/react-native/ReactCommon`)` dependency were found, but they required a higher minimum deployment target.

pod install --repo-update --ansi exited with non-zero code: 1
✨  Done in 12.94s.
```
```


### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

_No response_

**Comment by cipolleschi** [comment]
Hi @softmarshmallow, thanks for opening the issue, but this is more a problem of the integration between Expo and React Native, rather than a React Native problem.

As a first attempt, 
1. Make sure to run `yarn install` from the root folder of the project
2. Run `bundle exec pod deintegrate` to clean the pod projeect
3. Run `bundle exec pod install` to reinstall the pods.

If the problem persists, first try to open the issue with Expo, in [their repo](https://github.com/expo/expo). They are better equipped to help you out with the integration between React native and Expo.

**Comment by hakanolgunsv** [comment]
The issue also happens in React Native CLI projects. It happened when i upgrade from 0.72.6 to 0.73.2 version of react-native. I removed **ios/Pods** folder and **Podfile.lock** file then i run `pod install` again then the error has gone.

**Comment by cipolleschi** [comment]
10 versions of React Native is a huge leap @piclez! 😮 
Have you tried running `bundle exec pod deintegrate` and then `bundle exec pod install` again?

**Comment by nverdavtyan** [comment]
I have the same problem

**Comment by davidcort** [comment]
I have the same error after upgrade the SDK Expo version to 50 from 40.

I run:
cd ios && rm -rf Pods && pod cache clean --all && pod install && cd ..

But the error persist  : /
![image](https://github.com/facebook/react-native/assets/6045573/a1b397b6-e0c2-4feb-a797-44bcb081f59a)

**Comment by christian-smith** [comment]
I was able to fix this by running expo prebuild --clean.  I believe the fix is because it changes the minimum iOS version to 13.4

**Comment by carlosvstokkur** [comment]
I was able to fix this by updating my Podfile setting the correct `min_ios_version_supported`

**Comment by Moonko** [comment]
> I was able to fix this by updating my Podfile setting the correct `min_ios_version_supported`

Confirming that updating min iOS version solves the issue

**Comment by Areeb0206** [comment]
> > I was able to fix this by updating my Podfile setting the correct `min_ios_version_supported`
> 
> Confirming that updating min iOS version solves the issue

13.4 works for me

**Comment by Harmew** [comment]
in folder ios open Podfile and change this line 

> platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0

to 

> platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4

and try again npx pod-install

**Comment by TrustDec** [comment]
I  upgrade react-native 0.71.16 to 0.73.6 through the upgrade assistant. then run `rm -rf node_modules && rm -rf yarn.lock && yarn` error occurred. Running `bundle exec pod deintegrate` and then `bundle exec pod install` did not solve this problem. I changed `platform :ios, 13.0` to `platform :ios, 13.4` in Podfile under the iOS file, and then re-executed `npx pod-install` to solve this problem.

**Comment by Taseen18** [comment]
My Podfile file had already said 13.4, I had another file called Podfile.properties.json which said 13.0. changed it to 13.4 and re-ran pod install. fixed it

**Comment by Christopher96u** [comment]
> My Podfile file had already said 13.4, I had another file called Podfile.properties.json which said 13.0. changed it to 13.4 and re-ran pod install. fixed it

it worked to me too, thanks mate

**Comment by coderdiaz** [comment]
> in folder ios open Podfile and change this line
> 
> > platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0
> 
> to
> 
> > platform :ios, podfile_properties['ios.deploymentTarget'] || '13.4
> 
> and try again npx pod-install

It works for me using expo 50 and react-native 0.73.6 🔥

**Comment by SafiDS** [comment]
Solved by adding one line pod file:
React Native: 0.75.1

**platform :ios, min_ios_version_supported**

Complete pod file
`def node_require(script)
   # Resolve script with node to allow for hoisting
   require Pod::Executable.execute_command('node', ['-p',
     "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
 end

# Resolve react_native_pods.rb with node to allow for hoisting
 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Notifications'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ProjectName' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ProjectName' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
`

**Comment by kbqdev** [comment]
> I upgrade react-native 0.71.16 to 0.73.6 through the upgrade assistant. then run `rm -rf node_modules && rm -rf yarn.lock && yarn` error occurred. Running `bundle exec pod deintegrate` and then `bundle exec pod install` did not solve this problem. I changed `platform :ios, 13.0` to `platform :ios, 13.4` in Podfile under the iOS file, and then re-executed `npx pod-install` to solve this problem.

It's work. Thank you so much.

**Comment by MakStashkevich** [comment]
what helped me:

`sudo xcode-select --switch /Applications/Xcode.app`
