### ISSUE TITLE
Handle different build enviroments

### ISSUE THREAD

**Issue by DanielMSchmidt** [facebook/react-native#4232]
Hi there,

First of all, thanks for this great tool!
Regarding different build environments (develop, staging, production,...) I would like to ask for the preferred way to solve e.g. different API routes for each environment.

Our current solution was to use the babel plugin "utility.inlineEnvironmentVariables", so we specified node.env.API_URL and could use this in our build task. As we upgraded to 0.14.2 we found that this is problematic and throws the following error:

    mobile/node_modules/react-native/private-cli/src/bundle/buildBundle.js:22
        'production' = args.dev ? 'development' : 'production';
        ^^^^^^^^^^^^

    ReferenceError: Invalid left-hand side in assignment
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:414:25)
        at normalLoader (/Users/danielschmidt/Arbeit/Weluse/projekte/ramelow/ramelowApp/mobile/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:199:5)
        at Object.require.extensions.(anonymous function) [as .js] (/Users/danielschmidt/Arbeit/Weluse/projekte/ramelow/ramelowApp/mobile/node_modules/react-native/node_modules/babel-core/lib/api/register/node.js:216:7)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/Users/danielschmidt/Arbeit/Weluse/projekte/ramelow/ramelowApp/mobile/node_modules/react-native/private-cli/src/bundle/bundle.js:11:21)
        at Module._compile (module.js:435:26)

This is (almost) the same error @samsalisbury mentions in https://github.com/facebook/react-native/issues/3948 

I understand the problem with this problem, but I am not quite sure how this problem should be solved ideally. Thanks for your help and if you wish I would be glad to write a page in the docs about the  `.babelrc` and which transformators are supported and which not, as this is currently missing.

**Comment by fschindler** [comment]
+1

**Comment by samsalisbury** [comment]
The docs you mention would be really helpful @DanielMSchmidt ... I wouldn't know where to begin trying to find out which transforms are allowed though. Hoping one of the core contributors will be able to offer pointers :)

**Comment by ide** [comment]
Looks like the issue could be that Babel, which is used to transform the packager tool written in ES7, is finding your .babelrc. We'd need a way to tell Babel not to look for .babelrc files outside of react-native when transforming the packager source.

**Comment by DanielMSchmidt** [comment]
@samsalisbury Exactly, I will prepare them over the weekend and would just need to know which ones are supported and which not.

@ide not exactly, the babelrc is written by me, so babel behaves correctly. I need the transformation feature in order to distinguish between the different enviroments.

**Comment by samsalisbury** [comment]
Cool, I suspect what @ide means is that your .babelrc config is being used to compile [the packager code itself](https://github.com/facebook/react-native/blob/master/local-cli/bundle/buildBundle.js#L22) (rather than your code @DanielMSchmidt). I'm searching for a way to mark a .babelrc file as "root" similar to how .editorconfig files work.

@ide [is this the .babelrc](https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc) that is being used in this case? I can't quite understand the structure of the project, as the "local-cli" dir seems to be called "private-cli" at build time... Or I could just be barking up the wrong tree...

**Comment by ide** [comment]
@samsalisbury exactly.

This is where the packager enables Babel when it begins to run: https://github.com/facebook/react-native/blob/master/packager/react-packager/index.js#L11, and it picks up the .babelrc file you linked to.

**Comment by samsalisbury** [comment]
Well, the behaviour in Babel 6+ should be to pick up the nearest .babelrc according to [this comment on .babelrc cascading](https://phabricator.babeljs.io/T2214#57748)

However looking at my local source tree, I don't see [the react native .babelrc](https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc) anywhere in the hierarchy `node_modules/react-native/private-cli/src/bundle/buildBundle.js`, so I think it's just picking up my .babelrc from my project root, outside of the npm package, unless something magic is happening at https://github.com/facebook/react-native/blob/master/packager/react-packager/index.js#L11

**Comment by DanielMSchmidt** [comment]
@ide Ah, understood what you mean, sorry for the confusion.
@samsalisbury yes, looks like it takes the local .babelrc, which completely explains my error. Do you have any suggestions on how to solve different enviroments? I think I may use the dev flag for the production / local switch, but another enviroment seems quite hard at the moment.

**Comment by samsalisbury** [comment]
@DanielMSchmidt afaik you _should_ be able to use anything compatible with your own code in your project's own `.babelrc` including `utility.inlineEnvironmentVariables`. So, I think this is a genuine issue that needs to be solved in the react-native module, by isolating the compilation of react-native internal components from any .babelrc outside of the module (i.e. in your project's own source tree). That said, I can't quite grasp how the build process works at the moment, I'm pretty green at Node, so I think this will be solved quicker by someone with deeper knowledge (maybe @ide :)

**Comment by jsierles** [comment]
@DanielMSchmidt Thanks for submitting this issue!

Due to the massive growth of Github issues, we're trying to focus on bugs, so discussions on feature requests should be handled on [Product Pains](https://productpains.com/product/react-native) or PRs that implement a specific solution to your problem. We're closing this out for now. Thanks for understanding!

**Comment by DanielMSchmidt** [comment]
Thank you for the input, I just opened a Product Pains issue for that: https://productpains.com/post/react-native/add-mechanism-to-configure-an-enviroment

**Comment by Andreyco** [comment]
Anyone interested, please vote for this feature on ProductsPain.
