### ISSUE TITLE
Unable to download hermes-runtime-darwin-v0.70.15.tar.gz with rn v0.70.15 (404 - not found)

### ISSUE THREAD

**Issue by albat** [facebook/react-native#42356]
### Description

Hi,

When trying to install pods of v0.70.15, I get a 404 - not found for hermes-runtime-darwin-v0.70.15.tar.gz

[!] Error installing hermes-engine
[!] /usr/bin/curl -f -L -o /var/folders/hf/kb627n8d7dj24c89ry3ljv9h0000gn/T/d20240118-71489-hdqnf3/file.tgz https://github.com/facebook/react-native/releases/download/v0.70.15/hermes-runtime-darwin-v0.70.15.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

Can somebody add the file on the server ? :D

Thanks

### Steps to reproduce

1. Use "react-native": "0.70.15",
2. Run npm install
3. Go to ios folder
4. Run pod install

### React Native Version

0.70.15

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
-
```

### Stacktrace or Logs

```text
[!] Error installing hermes-engine
[!] /usr/bin/curl -f -L -o /var/folders/hf/kb627n8d7dj24c89ry3ljv9h0000gn/T/d20240118-71489-hdqnf3/file.tgz https://github.com/facebook/react-native/releases/download/v0.70.15/hermes-runtime-darwin-v0.70.15.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

### Reproducer

-

**Comment by bhandanyan-nomad** [comment]
+1

**Comment by friederbluemle** [comment]
@cortinico - Was this closed on purpose? I'm also having the same issue...

Hopefully we can have the missing file in the expected location soon.

Meanwhile, a workaround for local development:
https://stackoverflow.com/questions/77843155/react-native-0-70-15-error-installing-hermes-engine-curl-404

1. Download the previous version from https://github.com/facebook/react-native/releases/download/v0.70.14/hermes-runtime-darwin-v0.70.14.tar.gz
2. Use env variable HERMES_ENGINE_TARBALL_PATH during Pod installation

```
HERMES_ENGINE_TARBALL_PATH=/tmp/hermes-runtime-darwin-v0.70.14.tar.gz pod install
```

**Comment by cortinico** [comment]
> Hopefully we can have the missing file in the expected location soon.

It was closed because the user hasn't provided enough information + it's for RN 0.70 which is out of support. We won't be publishing new patches for that version anymore.

**Comment by albat** [comment]
> > Hopefully we can have the missing file in the expected location soon.
> 
> It was closed because the user hasn't provided enough information + it's for RN 0.70 which is out of support. We won't be publishing new patches for that version anymore.

How can you tell there is no info ?

The file is missing on your server and is returning a 404.
RN 0.70.15 is not usable for iOS because there is that error during pod install
It's pretty clear.

Up to you to don't fix it but that version is useless then.

The workaround provided can work on a local setup but not in a production environment with pipeline setup

Kind regards

**Comment by cortinico** [comment]
Thanks for clarifying @albat
I've re-uploaded the file to the GitHub release here:
https://github.com/facebook/react-native/releases/tag/v0.70.15

Now everything should work as expected

**Comment by friederbluemle** [comment]
I can confirm everything is working now. Thanks for the quick fix @cortinico :+1:
