### ISSUE TITLE
Cannot compile the project created with react-native init

### ISSUE THREAD

**Issue by jeangui** [facebook/react-native#4235]
Hi,

Very strange. I cannot compile in xcode the simple project that i have created with react-native init.
I get the following errors:

https://gist.github.com/jeangui/ee475c0d956fbe10de34

thanks in advance for your help.

Best
jeangui

**Comment by gorkemyurt** [comment]
You are probably missing a parenthesis above the ````AppRegistry.registerComponent('Project1', () => Project1);```` statement.

**Comment by brentvatne** [comment]
Just initialized a project fresh and compiled and ran it just fine. I suspect there is a problem with your node version, I'm using 4.2.1 right now. If this doesn't help, please repost to stackoverflow!
