### ISSUE TITLE
running on iPhone6s

### ISSUE THREAD

**Issue by FeiYao** [facebook/react-native#4237]
I followed 3 stepped http://facebook.github.io/react-native/docs/running-on-device-ios.html#content for "accessing development server from device". It doesn't work for me, even though i replaced my localhost with IP.

Using offline bundle doesn't work for me either. The step seems to be straightforward. Can someone share some detailed step or gotchas?

Thanks
Fei

**Comment by christopherdro** [comment]
Are both your server and phone connected to the same network?
Can you share what your Appdelegate.m looks like?

If you would like to use the offline bundle you need to make sure to run `react-native budle` in the root of your app and add jsbundle to your project if it's not already in there.

**Comment by FeiYao** [comment]
Thanks Chris.

```javascript
jsCodeLocation = [NSURL URLWithString:@"http://10.209.16.45:8081/index.ios.bundle?platform=ios&dev=true"];
```

It is still not working, I'm wondering whether port is an issue. I tried using browser in iPhone6s to reach http://10.209.16.45:8081/index.ios.bundle, but failed as well.

**Comment by christopherdro** [comment]
Hmm. Does anything get logged inside the terminal where the packager is running?

**Comment by brentvatne** [comment]
Make sure that you're on the same wifi network on your phone/computer @FeiYao -- if that doesn't fix it I will reopen this.
