### ISSUE TITLE
Adding subject into ActionSheetIOS share options

### ISSUE THREAD

**Issue by dajomu** [facebook/react-native#4239]
Hi,

I noticed that when I was trying to share from my react native app to email, there was no way to set the subject field of the email.

I've added in an additional parameter to the share object given to ActionSheetIOS.showShareActionSheetWithOptions so that it is now -
```
ActionSheetIOS.showShareActionSheetWithOptions({
      url: 'https://code.facebook.com',
      message: 'message to go with the shared url',
      subject: 'a subject to go in the email heading',
   },
```
I also updated the example to reflect this.

The pull request is here -
https://github.com/facebook/react-native/pull/4238

**Comment by dajomu** [comment]
This has been merged now

**Comment by gregblass** [comment]
Just wondering if this is for the mail app only? Most people I know use the Gmail app on iOS. The subject doesn't seem to work there. There doesn't seem to be any mention of it in the documentation. Is this just assumed that the user is using the default iOS mail app?

**Comment by gregblass** [comment]
This looks like its happening outside of React Native too, and appears to be a bug or shortcoming of the Gmail iOS app. Typical situation where Google and Apple don't care about working together on stuff like this. Not really a problem of React Native though.
