### ISSUE TITLE
Absolute positioned view inherits the padding from parent

### ISSUE THREAD

**Issue by meznaric** [facebook/react-native#4240]
I've built [this RNPlay.org](https://rnplay.org/apps/INABtA) to demonstrate the issue.

When `View` is absolutely positioned inside a `View` that has a padding, padding gets inherited by absolutely positioned div.  I did not expect this behaviour at all. Is this normal?

**Comment by brentvatne** [comment]
Hi @meznaric! I'm not really sure what the issue is -- no padding is being inherited in the example that you provided. Perhaps you mean the spacing on `Text` -- you actually can't use the `flex` property on `Text`, you should just use that on container views. I fixed your example here: https://rnplay.org/apps/yAseGA

**Comment by meznaric** [comment]
Hey @brentvatne! I forked your example and reintroduced `paddingHorizontal` which you removed. I also changed the colours for clarity. Here is the updated code https://rnplay.org/apps/4M1JoA (look at iOS version).

What I expect:
 - `Container` has `paddingHorizontal` and its contents should respect it
 - Absolutely positioned Views inside `Container` shouldn't be affected by `Container`'s padding

What I get:
 - Absolutely positioned Views (in my example `error`) have some weird padding on the right which seems to be double of paddingHorizontal (paddingLeft+paddingRight). Where does it come from?

![Problem](http://i.imgur.com/4l0DObD.png)

Hopefully I described a problem better this time.

**Comment by brentvatne** [comment]
Hey @meznaric! Thanks for that, it definitely helped! I'll create an issue on https://github.com/facebook/css-layout and reference this! :smile:

**Comment by brentvatne** [comment]
See https://github.com/facebook/css-layout/issues/152

**Comment by nikoloza** [comment]
Workaround for this can be:

Instead of:
```
width: ...
```

Use:
```
left: 0,
right: 0,
```
