### ISSUE TITLE
why can't creat a new project for ios?

### ISSUE THREAD

**Issue by nodreamnolove** [facebook/react-native#4241]
I installed brew, npm, watchman, flow 
localhost:~ mac$ npm -v
2.14.7
localhost:~ mac$ node -v
v4.2.2
 But when I do next :
localhost:~ mac$ sudo react-native init AweSomeApp
Password:
This will walk you through creating a new React Native project in /Users/mac/AweSomeApp
Installing react-native package from npm...
waited , wait ,waiting ......
what can i do 
I am from China

**Comment by roysG** [comment]
this is the same problem for me!!

**Comment by brentvatne** [comment]
Does `npm install react-native` work?

**Comment by jaygarcia** [comment]
Call me crazy, but i don't think that you need `sudo` to init an application.

**Comment by brentvatne** [comment]
This works, it is almost certainly an issue with npm. Will reopen this issue if `npm install react-native` works but `react-native init` does not, please let me know!

**Comment by nodreamnolove** [comment]
Of course, I installed react-native .
react-native -v
0.1.7

**Comment by nodreamnolove** [comment]
$ sudo npm install -g react-native-cli
/usr/local/bin/react-native -> /usr/local/lib/node_modules/react-native-cli/index.js
react-native-cli@0.1.7 /usr/local/lib/node_modules/react-native-cli
├── semver@5.1.0
├── chalk@1.1.1 (ansi-styles@2.1.0, supports-color@2.0.0, escape-string-regexp@1.0.3, has-ansi@2.0.0, strip-ansi@3.0.0)
└── prompt@0.2.14 (pkginfo@0.3.1, revalidator@0.1.8, read@1.0.7, winston@0.8.3, utile@0.2.1)

**Comment by sailei1** [comment]
me  too
