### ISSUE TITLE
onPressOut: Unable to distinguish if it's triggered by RESPONDER_RELEASE or not

### ISSUE THREAD

**Issue by brianstern** [facebook/react-native#4242]
I've found that for touchable classes, I'm unable to programmatically determine how an onPressOut event was triggered. There are two mutually exclusive cases of concern:

1. If a user moves their touch outside the press retention area (as defined by pressRetentionOffset), an onPressOut event is triggered.
2. If a user ends their touch inside the press retention area, an onPressOut event is triggered, immediately followed by an onPress event.

For my purposes, I need to be able to know, from the perspective of the onPressOut event, whether it's being called in case 1 or  2. My solution to this problem was to modify _performSideEffectsForTransition() in Touchable.js. The original section is as follows:

```javascript
if (newIsHighlight && !curIsHighlight) {
  this._savePressInLocation(e);
  this.touchableHandleActivePressIn && this.touchableHandleActivePressIn(e);
} else if (!newIsHighlight && curIsHighlight && this.touchableHandleActivePressOut) {
  if (this.touchableGetPressOutDelayMS && this.touchableGetPressOutDelayMS()) {
    this.pressOutDelayTimeout = this.setTimeout(function() {
      this.touchableHandleActivePressOut(e);
    }, this.touchableGetPressOutDelayMS());
  } else {
    this.touchableHandleActivePressOut(e);
  }
}
```
And I changed it to:
```javascript
if (newIsHighlight && !curIsHighlight) {
  this._savePressInLocation(e);
  this.touchableHandleActivePressIn && this.touchableHandleActivePressIn(e);
} else if (!newIsHighlight && curIsHighlight && this.touchableHandleActivePressOut && signal !== Signals.RESPONDER_RELEASE) {
  if (this.touchableGetPressOutDelayMS && this.touchableGetPressOutDelayMS()) {
    this.pressOutDelayTimeout = this.setTimeout(function() {
      this.touchableHandleActivePressOut(e);
    }, this.touchableGetPressOutDelayMS());
  } else {
    this.touchableHandleActivePressOut(e);
  }
}
```
In this way, I've disabled the onPressOut event when the RESPONDER_RELEASE signal occurs, so that in case 2, only the onPress event is triggered. My onPressOut function no longer needs to know how it was called, and I can properly handle these two cases independently.

I'm worried that this edit may introduce horrifying bugs somewhere down the line, and that the choice to call onPressOut in both cases was deliberate and well-considered.

Is there a better way to achieve the logical independence between those two cases that I'm looking for, or a better way of thinking about this problem in general? Or is my modification a legitimate solution to an actual issue?

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by mkonicek** [comment]
Can you try making the StackOverflow post as short as possible? It will make others more motivated to look at it.
