### ISSUE TITLE
Can't build the Animated Library

### ISSUE THREAD

**Issue by TheSisb** [facebook/react-native#4244]
I:
- clone this repo 
- cd react-native/Libraries/Animated/release
- npm install
- gulp

```js
Time: 1617ms
          Asset     Size  Chunks             Chunk Names
animated.min.js  22.5 kB       0  [emitted]  main
chunk    {0} animated.min.js (main) 70 kB [rendered]
    [0] ./lib/AnimatedWeb.js 933 bytes {0} [built]
    [1] ./lib/AnimatedImplementation.js 46.3 kB {0} [built] [1 error]
    [2] ./lib/Easing.js 3.67 kB {0} [built]
    [3] ./lib/InteractionManager.js 475 bytes {0} [built]
    [4] ./lib/Interpolation.js 8.68 kB {0} [built] [1 error]
    [5] ./lib/Set.js 596 bytes {0} [built]
    [6] ./lib/SpringConfig.js 2.26 kB {0} [built]
    [7] ./lib/bezier.js 2.5 kB {0} [built]
    [8] ./lib/flattenStyle.js 377 bytes {0} [built]
    [9] ./~/fbjs/lib/emptyFunction.js 1.09 kB {0} [built]
   [10] ./~/fbjs/lib/invariant.js 1.52 kB {0} [built]
   [11] ./~/fbjs/lib/nativeRequestAnimationFrame.js 618 bytes {0} [built]
   [12] ./~/fbjs/lib/requestAnimationFrame.js 957 bytes {0} [built]
   [13] external "React" 42 bytes {0} [not cacheable]

ERROR in ./lib/AnimatedImplementation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./ViewStylePropTypes in /Users/shadi/react-native/Libraries/Animated/release/lib
 @ ./lib/AnimatedImplementation.js 42:25-56

ERROR in ./lib/Interpolation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./tinycolor in /Users/shadi/react-native/Libraries/Animated/release/lib
 @ ./lib/Interpolation.js 34:16-38
```

Is this a bug or am I doing something incorrectly?

**Comment by ide** [comment]
I don't think this is supported -- cc @vjeux ?

**Comment by vjeux** [comment]
It was work in progress and needs to be continued... But it is probably not working right now :(

**Comment by ide** [comment]
OK. So it works fine in RN but isn't supported in other environments.

**Comment by TheSisb** [comment]
Sad to hear that, this page: http://fooo.fr/~vjeux/fb/animated-docs/ showed great potential.
Hope it gets prioritization soon!

**Comment by browniefed** [comment]
After running a git bisect, and some false positives when `tinycolor2` was switched to it looks like the failing commit is https://github.com/facebook/react-native/commit/7c1b6b0fb645669d1b0185c15a98a4b14093fbb7 when tinycolor got vendorized apparently?

It's not the only failing issue when the build is run though, still unsure why even when resolving the tinycolor issue with `_moduleMap` that things are still failing for other things like `ViewStylePropTypes` even when they weren't before.

**Comment by browniefed** [comment]
@vjeux Got `AnimatedWeb` rebuilding. Went through a few different options, attempting to just use webpack/babel and no gulp to output bundle and files. Ran into some issues with `React`, `alias/external`combo.
Attempted to get the babel `rewrite-module` working with `babel-loader` but was unsuccessful.

Looked into to use `react-native-webpack-server` and the dependency resolve to get access to `@provideModule` dynamic locations, but that was also a meh option. Also was failing on master due to the `sprintf` not being included in `moduleMap`? Wasn't sure.

Ultimately I went with the worst option. I had to map directly to each file that was now being included w/ the including of `ViewStylePropTypes`. Eh. If it's a good enough option I can submit a PR.

```
var paths = {
  dist: 'dist',
  entry: 'lib/AnimatedWeb.js',
  lib: 'lib',
  src: [
    '*src/**/*.js',
    '*src/../../vendor/tinycolor/tinycolor.js',
    '*src/../../Components/View/ViewStylePropTypes.js',
    '*src/../../StyleSheet/LayoutPropTypes.js',
    '*src/../../StyleSheet/TransformPropTypes.js',
    '*src/../../../node_modules/react-haste/isomorphic/classic/types/ReactPropTypes.js',
    '*src/../../../node_modules/react-haste/isomorphic/classic/types/ReactPropTypeLocationNames.js',
    '*src/../../../node_modules/react-haste/isomorphic/classic/element/ReactElement.js',
    '*src/../../../node_modules/react-haste/isomorphic/classic/element/ReactCurrentOwner.js',
    '*src/../../../node_modules/react-haste/shared/utils/getIteratorFn.js',
    '*src/../../../node_modules/react-haste/shared/stubs/Object.assign.js',
    '!src/**/__tests__/**/*.js',
    '!src/**/__mocks__/**/*.js'
  ]
};
```

**Comment by TheSisb** [comment]
@browniefed Thanks for looking into this! 

"Ultimately I went with the worst option. I had to map directly to each file that was now being included w/ the including of ViewStylePropTypes"  - I came to the same conclusion :/

I'm on vacation right now but thanks for adding your notes into this issue ticket - hope it helps them clear the issues out down the line!

**Comment by browniefed** [comment]
@TheSisb did a little work here. To get stuff working we just need to flatten the transform for the web.
```
function flattenTransform(transforms) {
  var value = transforms.reduce((prevValue, currentValue) => {
    var key = Object.keys(currentValue)[0];
    return prevValue + ' ' + key + '(' + currentValue[key] + ')'; 
  }, '')
  return value;
}
```

And in the implementation
```
class AnimatedTransform extends AnimatedWithChildren {
  _transforms: Array<Object>;

  constructor(transforms: Array<Object>) {
    super();
    this._transforms = transforms;
  }

  __getValue(): Array<Object> {
    return flattenTransform(this._transforms.map(transform => {
      var result = {};
      for (var key in transform) {
        var value = transform[key];
        if (value instanceof Animated) {
          result[key] = value.__getValue();
        } else {
          result[key] = value;
        }
      }
      return result;
    }));
  }
```
Now to go about implementing things properly. Not entirely certain how we should go about this. `AnimatedTransform` could be busted out, in the web build process we swap out the `AnimatedTransform` with our web implementation.

Not sure if we should make it depend on a build process, or a configuration, like `AnimatedImplementation` is a function and we pass in something different with `AnimatedWeb` to tell that it needs to flatten styles.

Not certain what direction we should take here.

**Comment by browniefed** [comment]
So I ended up just bringing in `CSSProperty`, `CSSPropertyOperations`, and `dangerousStyleValue` into the polyfills folder so we can take advantage of React code already written.
Bumped `fbjs` dep as well.

Then just doing

```
function flattenTransform(transforms) {
  if (!transforms) return '';

  return transforms.map(transform => {
      var result = '';
      for (var key in transform) {
        var value = transform[key];
        result += key + '(' + value + ')';
      }
      return result;
    }).join(' ');
}
////
if (this.refs[refName].setNativeProps) {
          var value = this._propsAnimated.__getAnimatedValue();
          this.refs[refName].setNativeProps(value);
        } else if (this.refs[refName].getDOMNode().setAttribute) {
          var value = this._propsAnimated.__getAnimatedValue();
          var style = value.style;
          var strStyle = CSSPropertyOperations.setValueForStyles(this.refs[refName].getDOMNode(), {
            ...flattenStyle(value.style),
            transform: flattenTransform(style && style.transform)
          }, this.refs[refName]);
        } else {
          this.forceUpdate();
        }
```

Seems to work with minimal code changes. But obviously it's still using `13.3` and not `.14` so we need to call `getDOMNode`, should update all that.
