### ISSUE TITLE
Store sensitive information on Android

### ISSUE THREAD

**Issue by homer0** [facebook/react-native#4247]
I'm trying to migrate an ObjC app to RN in order to add support for Android, and one of my concerns is that in ObjC I'm using Keychain to store OAuth Login information, and I don't know if there's a way to replicate this kind of _secure storage_ on Android with RN.

I know how to create a module in ObjC and then export it to RN in order to add the functionality, and there's also [this library](https://github.com/oblador/react-native-keychain) that allows me to work with Keychain in iOS, but I couldn't find anything about storing sensitive data in a secure way on Android.

Any ideas that doesn't involve me learning Java :P?

Thanks!

**Comment by ide** [comment]
AFAIK there isn't anything out there yet. As a meta point though, I highly recommend being familiar with Java+Android and Obj-C+Cocoa if you're using React Native. It's ~so~ much better when you or someone you're working with writes a native module to meet your needs.

**Comment by homer0** [comment]
@ide Thanks for the quick answer, and yes, I code in ObjC so I can create the modules I'm missing for iOS, but I didn't want to learn Java :stuck_out_tongue_closed_eyes: .

Thanks again!
