### ISSUE TITLE
Document how create native module for custom components. 

### ISSUE THREAD

**Issue by drkibitz** [facebook/react-native#425]
The example here leaves a bit to be desired:
http://facebook.github.io/react-native/docs/nativemodulesios.html#content

Been trying to find out the best way to create a custom component with native backing. For example, something utilizing UIMotion objects allowing them to be passed via `addMotionEffect` to views.

**Comment by jaygarcia** [comment]
@drkibitz ,

I've been able to implement a custom audio player and views.  The audio player implements a custom C library known as libGME.

Please see the below project for a *very experimental* implementation.   

https://github.com/ModusCreateOrg/EZGmePlayer

Feel free t ping with any questions.  The code is not documented very well, as i'm moving very fast and only doing this part-time. :(

**Comment by ide** [comment]
Docs are much better now.
