### ISSUE TITLE
Why RN still depends on NineOldAndroid？

### ISSUE THREAD

**Issue by ASCE1885** [facebook/react-native#4251]
Since minSdkVersion is 16，it could uses the system api for animation

**Comment by mkonicek** [comment]
I believe it is because [Fresco](https://github.com/facebook/fresco) (the image library we use) has a legacy dependency on this. Once they remove it we should get rid of the dependency.

If you consider this a good answer please consider closing the issue :)

**Comment by ASCE1885** [comment]
thanks
