### ISSUE TITLE
[Android] app crashes on start

### ISSUE THREAD

**Issue by kitolog** [facebook/react-native#4253]
11-20 11:17:11.058 2163-2163/? A/fbassert: Assert (/Users/mkonicek/code/react-native/ReactAndroid/src/main/jni//first-party/jni/fbjni/Exceptions.cpp:86): localUnknownCppExceptionClass
11-20 11:17:11.059 2163-2163/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadb00c in tid 2163 (com.ptreact)
11-20 11:17:11.138 835-850/? W/ActivityManager: Force removing ActivityRecord{24a1546 u0 com.ptreact/.MainActivity t8106}: app died, no saved state

react-native -v
0.1.7

**Comment by brentvatne** [comment]
@kitolog - sorry I think we need more information! What SDK version? What OS?

@mkonicek - I see your name in there, weird!

**Comment by mkonicek** [comment]
Just grepped the codebase for my username - no occurrences, phew! :)

**Comment by brentvatne** [comment]
5 days without a response means this issue is inactive so I'm closing it :) @kitolog - feel free to open a new issue for this with more information so we can properly help you debug the problem!

**Comment by satya164** [comment]
@mkonicek I think your name appears when crashes occur in the C++ code. I've seen it before :D

**Comment by andreipt** [comment]
@kitolog How did you fix this? I am also getting the same error when when integrating react-native v0.19.0 with an existing Android app. Thanks!
