### ISSUE TITLE
[Android] [TextInput] keyboardType numeric actually shows the phone keyboard

### ISSUE THREAD

**Issue by trippcr** [facebook/react-native#4260]
The keyboard that is shown for type `numeric` is actually the phone keyboard.

![phonekeypad](https://cloud.githubusercontent.com/assets/236023/11310267/4161c7a4-8f8e-11e5-8efe-7dfff7893ab3.png)

While it does work as a number pad, it's not the greatest, especially when there is a dedicated number keyboard available on Android.

I think the problem is that, while `setKeyboardType` method in `ReactTextInputManager` does set the flag to `InputType.TYPE_CLASS_NUMBER`, it doesn't clear out any of the other possible type class values. So it ends up ORing `InputType.TYPE_CLASS_NUMBER` with `InputType.TYPE_CLASS_TEXT`, which would be the `InputType.TYPE_CLASS_PHONE` value.

**Comment by brentvatne** [comment]
Hi @trippcr! Could you send a pull request for this?

**Comment by trippcr** [comment]
I think got it figured out: pull #4328

**Comment by cspkop** [comment]
+1 for the issue.

**Comment by andreicoman11** [comment]
Fixed in https://github.com/facebook/react-native/commit/cc449b394e9cd3300343016a5d6a3c924823cd2b
