### ISSUE TITLE
Bug: When I used "react native" version 0.73.2 for memory testing, I found a memory leak

### ISSUE THREAD

**Issue by luojiyanyu** [facebook/react-native#42605]
When I used "react native" version 0.73.2 for memory testing, I found a memory leak
<img width="1101" alt="截屏2024-01-22 15 06 33" src="https://github.com/facebook/react/assets/16015656/74ab770d-136c-4d13-9647-1a88b6d4c2a0">
How should I handle it

**Comment by rickhanlonii** [comment]
Transferred to react-native repo.

**Comment by luojiyanyu** [comment]
I put the demo in this project

https://github.com/luojiyanyu/RN_memoryLeak_demo_0.73.2.git

**Comment by luojiyanyu** [comment]
The iOS 16.6 system can be replicated

**Comment by luojiyanyu** [comment]
> I put the demo in this project
> 
> https://github.com/luojiyanyu/RN_memoryLeak_demo_0.73.2.git

I put the demo in this project

https://github.com/luojiyanyu/RN_memoryLeak_demo_0.73.2.git
The iOS 16.6 system can be replicated
