### ISSUE TITLE
ReactNative 0.73 did not include the Hermes WeakMap memory leak fix

### ISSUE THREAD

**Issue by edkimmel** [facebook/react-native#42620]
### Description

It looks like ReactNative 0.73 took a build of hermes from September 2023.  The WeakMap memory leak was fixed in November. https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670

Would it be possible to get a minor version / hotfix built of 0.73 to include that fix?  Right now, our choices are to patch and host a custom hermes ourselves or to continue to call GC manually to work around the issue.

### Steps to reproduce

https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://github.com/facebook/hermes/commit/e7b2abefabb6a9671e1d30d7af08cd1f32c9a670

**Comment by cortinico** [comment]
Closing as you should ask for this pick here:
https://github.com/reactwg/react-native-releases/discussions/98

The change doesn't look that invasive so we should be able to pick it. However we'll need to get a confirmation from @neildhar @tmikov that it's safe to pick this change on for 0.73.

**Comment by neildhar** [comment]
Confirming that this is safe to pick
