### ISSUE TITLE
Navigator overlapping inner content

### ISSUE THREAD

**Issue by fender** [facebook/react-native#4264]
I'm using the native `Navigator` component but when using a NavigatorBar, it is overlapping my inner content like so:
![screenshot1](https://cloud.githubusercontent.com/assets/1436470/11312480/39bc66f4-8fce-11e5-8d0a-b4841a628a59.png)

This is the content that should be visible but only shows when dragged/scrolled down.
![screenshot2](https://cloud.githubusercontent.com/assets/1436470/11312481/3b0695f2-8fce-11e5-8b9b-6fce60d605d3.png)

Here is my nav component:
```jsx
  ...
  render() {
    return (
      <Navigator
        style={styles.appContainer}
        initialRoute={{component: SplashScreen}}
        renderScene={this.renderScene}
        navigationBar={
          <Navigator.NavigationBar
            routeMapper={this.navBarRouteMapper}
            style={styles.navBar}
          />
        }
      />
    );
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF'
  },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    marginBottom: 5
  },
  button: {
    marginBottom: 7,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 2,
    padding: 5
  }
});
```

And the inner component:
```jsx
  ...
  render() {
    return (
      <ListView style={styles.container}
        dataSource={this.state.dataSource}
        renderRow={this.renderRow}
      />
    );
  }

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'center',
    padding: 10,
    backgroundColor: '#F6F6F6',
  },
  separator: {
    height: 1,
    backgroundColor: '#CCCCCC',
  },
  text: {
    flex: 1,
  }
});
```

**Comment by FaridSafi** [comment]
you can add sceneStyle={{paddingTop: 64}} to your navigator props

**Comment by sospartan** [comment]
@FaridSafi better use this "Navigator.NavigationBar.Styles.General.NavBarHeight" I think

**Comment by brentvatne** [comment]
Hi there! Not a bug, please post these types of issues to StackOverflow :)

**Comment by lrettig** [comment]
Has this issue been addressed on StackOverflow? I'm having the same issue and couldn't find anything related there. Just wanted to check before opening a new ticket. Thanks!

**Comment by fender** [comment]
@lrettig I just added a paddingTop as mentioned above.

**Comment by lrettig** [comment]
Thanks. I was confused by #470 as this:

> Very simple solution will be wrap the <Text> with a container view, like ScrollView

didn't work for me. Adding `paddingTop` does, of course, help. I guess this is the accepted way of working around this issue.

**Comment by ragamufin** [comment]
Just an addition to @sospartan 's comment. I think the correct height can be found in `Navigator.NavigationBar.Styles.General.TotalNavHeight`

**Comment by pejalo** [comment]
Another tip: Scroll bars look better if you use `marginTop` instead of `paddingTop`

**Comment by ReDetection** [comment]
Well, Navigator is deprecated and removed from default package. What is recommended solution now?

**Comment by nhoxbypass** [comment]
I think paddingTop is the only solution if you don't want to embed it in a ScrollView or use 3rd library to get exactly the StatusBar height.
