### ISSUE TITLE
Error on reload: ERROR  Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent()..

### ISSUE THREAD

**Issue by skinnynpale** [facebook/react-native#42640]
### Description

if you reload the application from the simulator (using the hot button), we get the following error, if you reload the application from the metro bundler, then there is no such error

ERROR  Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry.          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes

### Steps to reproduce

if you reload the application from the simulator (using the hot button), we get the following error, if you reload the application from the metro bundler, then there is no such error

### React Native Version

0.73.2

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer, TurboModule - The New Native Module System, JSI - Javascript Interface, Bridgeless - The New Initialization Flow, Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 104.56 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/skinnynpale/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 3.0.6
    path: /Users/skinnynpale/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
ERROR  Invariant Violation: Failed to call into JavaScript module method RCTEventEmitter.receiveEvent(). Module has not been registered as callable. Bridgeless Mode: false. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, HMRClient, AppRegistry.          A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

### Reproducer

--

### Screenshots and Videos

![telegram-cloud-photo-size-2-5298888882256991998-w](https://github.com/facebook/react-native/assets/52371356/f45e9a36-2a42-4918-9df6-ee2b4aa36eab)

**Comment by cortinico** [comment]
> if you reload the application from the simulator (using the hot button)

What do you mean with the "hot button" in the simulator?

**Comment by cortinico** [comment]
I've tested this on RN Tester, and the problem doesn't happen. @skinnynpale are you able to create a reproducer of any sort? I suppose this could be related to some 3rd party library you have included.

**Comment by RSNara** [comment]
@skinnynpale, are you running into this issue in Bridgeless mode?

> Fabric - The New Renderer, TurboModule - The New Native Module System, JSI - Javascript Interface, **Bridgeless - The New Initialization Flow**, Codegen

This code should never run in Bridgeless mode! I think you've stumbled onto an interesting bug. Looking forward to the reproducer!

**Comment by cortinico** [comment]
> we don't have Bridgeless enabled, I thought it was enabled by default in the new architecture

Nope it needs to be enabled separately in 0.73
@skinnynpale are you able to create a repro in any form?

**Comment by cortinico** [comment]
> it caused by the react-native-screens with @react-navigation/bottom-tabs,

Great, can we open an issue against `react-native-screens` and link it here?

**Comment by sbin1211** [comment]
> > it caused by the react-native-screens with @react-navigation/bottom-tabs,
> 
> Great, can we open an issue against `react-native-screens` and link it here?

sure. @cortinico please help to link it. i don't know which side (RN or RNScreens) cause this issue.

**Comment by cortinico** [comment]
> sure. @cortinico please help to link it.

Please create the issue there, and post it here afterwards

**Comment by wcastand** [comment]
i'm seeing this on android in my production app logs. did anyone had a chance to fix the issue on their side by any chance?
issue on native-screen closed with no solution either :/

**Comment by alextbogdanov** [comment]
> i'm seeing this on android in my production app logs. did anyone had a chance to fix the issue on their side by any chance? issue on native-screen closed with no solution either :/

I'm having the same issue on ios whenever I open the expo menu in the app

**Comment by cortinico** [comment]
Closing because of:
https://github.com/software-mansion/react-native-screens/issues/2027#issuecomment-2010077331

**Comment by HeXiuLian** [comment]
Solution：
**RNSScreen.mm** 
```
@implementation RNSScreenView {
  __weak RCTBridge *_bridge;
}

#ifdef RCT_NEW_ARCH_ENABLED
- (instancetype)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    static const auto defaultProps = std::make_shared<const facebook::react::RNSScreenProps>();
    _props = defaultProps;
    _reactSubviews = [NSMutableArray new];
    _bridge = [RCTBridge currentBridge];
    [self initCommonProps];
  }

  return self;
}
#endif // RCT_NEW_ARCH_ENABLED

- (void)notifyTransitionProgress:(double)progress closing:(BOOL)closing goingForward:(BOOL)goingForward
{
#ifdef RCT_NEW_ARCH_ENABLED
  if (_eventEmitter != nullptr) {
    std::dynamic_pointer_cast<const facebook::react::RNSScreenEventEmitter>(_eventEmitter)
        ->onTransitionProgress(facebook::react::RNSScreenEventEmitter::OnTransitionProgress{
            .progress = progress, .closing = closing ? 1 : 0, .goingForward = goingForward ? 1 : 0});
  }
  RNSScreenViewEvent *event = [[RNSScreenViewEvent alloc] initWithEventName:@"onTransitionProgress"
                                                                   reactTag:[NSNumber numberWithInt:self.tag]
                                                                   progress:progress
                                                                    closing:closing
                                                               goingForward:goingForward];
  if (_bridge) {
    [_bridge.eventDispatcher sendEvent:event];
  } else {
    [[RCTBridge currentBridge].eventDispatcher sendEvent:event];
  }
  
  
#else
  if (self.onTransitionProgress) {
    self.onTransitionProgress(@{
      @"progress" : @(progress),
      @"closing" : @(closing ? 1 : 0),
      @"goingForward" : @(goingForward ? 1 : 0),
    });
  }
#endif
}
```

**Comment by alextbogdanov** [comment]
Create a pr?

**Comment by rousseau634** [comment]
In my case, it solved when I replaced AppDelegate with swift
