### ISSUE TITLE
Package the taro-rn project using Android Studio, but the generated release.apk is React, which is the official demo

### ISSUE THREAD

**Issue by Ccc437647** [facebook/react-native#42652]
### Description

This is an rn project developed by Taro

Packaging Android APK files using Android Studio

Packaging debug.apk is the project engineering file I developed, and there is no problem with it

But the packaged release.apk is the demo file of the framework (App. js), which saved this. What's going on

![18](https://github.com/facebook/react-native/assets/74176833/07da4847-2cc1-4d58-9869-3b4b7cef8227)
![19](https://github.com/facebook/react-native/assets/74176833/0712c20e-e2bb-4160-b2a4-26b092c56dd8)

### Steps to reproduce

 
![18](https://github.com/facebook/react-native/assets/74176833/d52261bf-586f-4f64-8e3f-5e5b2264c090)
![19](https://github.com/facebook/react-native/assets/74176833/156fb67e-90c4-4fc8-9796-46f19e32c60e)

### React Native Version

0.70.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: Windows 10 10.0.22621
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 2.96 GB / 15.90 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 17.0.9 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
nnnno
```

### Reproducer

https://github.com/NervJS/taro-native-shell

**Comment by cortinico** [comment]
Plaese open this issue against https://github.com/NervJS/taro-native-shell/issues
