### ISSUE TITLE
An error occurs when integrating into an existing native applicatio

### ISSUE THREAD

**Issue by querli** [facebook/react-native#42658]
### Description

The project created with npx react-native@latest init xx works fine，But
According to the documentation that is integrated into the existing application, run the yarn start or npx react-native start command to report error No Metro config found in /xx/ xx/Demo/RNDemo.
error Command failed with exit code 1.

info Fetching system and libraries information...
System:
  OS: macOS 12.7.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 61.48 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK: Not Found
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

<img width="421" alt="image" src="https://github.com/facebook/react-native/assets/45426897/13d49f73-555c-401b-bdbc-1d477d06158e">

### Steps to reproduce

If the yarn start command is used to integrate existing application documents, the compilation fails

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
error No Metro config found in /Users/querli/Demo/RNDemo.
```

### Stacktrace or Logs

```text
error No Metro config found in /Users/querli/Demo/RNDemo.
```

### Reproducer

xx

**Comment by cortinico** [comment]
As the error says, you need a Metro config to run.

You can add a file in your root folder called `metro.config.js` with this content:
```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

And it should work fine
