### ISSUE TITLE
gradlew assembleRelease  failed

### ISSUE THREAD

**Issue by lizhangqu** [facebook/react-native#4266]
```
:app:mergeReleaseResources (Thread[main,5,main]) completed. Took 3.278 secs.
:app:bundleReleaseJsAndAssets (Thread[main,5,main]) started.
:app:bundleReleaseJsAndAssets
Executing task ':app:bundleReleaseJsAndAssets' (up-to-date check took 4.638 secs
) due to:
  No history is available.
Starting process 'command 'react-native''. Working directory: C:\Users\Administr
ator\Desktop\AwesomeProject Command: react-native bundle --platform android --de
v false --entry-file index.android.js --bundle-output C:\Users\Administrator\Des
ktop\AwesomeProject\android\app\build\intermediates\assets\release\index.android
.bundle --assets-dest C:\Users\Administrator\Desktop\AwesomeProject\android\app\
build\intermediates\res\merged\release
:app:bundleReleaseJsAndAssets FAILED
:app:bundleReleaseJsAndAssets (Thread[main,5,main]) completed. Took 4.773 secs.

```

**Comment by WoLfulus** [comment]
Is your packager open?

**Comment by lizhangqu** [comment]
I have sovled it.say [https://github.com/facebook/react-native/commit/6124298dd7c555c0c913defc5c927b592a368ead](https://github.com/facebook/react-native/commit/6124298dd7c555c0c913defc5c927b592a368ead)

**Comment by WoLfulus** [comment]
@lizhangqu thanks for that!

**Comment by deju** [comment]
@WoLfulus  I had the problem in Mac. Gradlew failed, but the error had some different.

	Executing task ':app:bundleReleaseJsAndAssets' (up-to-date check took 3.171 secs) due to:
	  Output file /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/assets/release/index.android.bundle has changed.
	Starting process 'command 'react-native''. Working directory: /Users/tudeju/Project/react/JJTest Command: react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/assets/release/index.android.bundle --assets-dest /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/res/merged/release
	:app:bundleReleaseJsAndAssets FAILED
	:app:bundleReleaseJsAndAssets (Thread[Daemon worker Thread 9,5,main]) completed. Took 3.185 secs.

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:bundleReleaseJsAndAssets'.
	> A problem occurred starting process 'command 'react-native''

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

	BUILD FAILED

	Total time: 18.278 secs
	Stopped 0 compiler daemon(s).
	Received result CommandFailure[value=org.gradle.launcher.exec.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:bundleReleaseJsAndAssets'.] from daemon DaemonInfo{pid=68357, address=[fcf0a51c-b0d3-42da-8780-034150dcfe48 port:52043, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=e83b1e6a-98c6-4893-8131-eb83fae3bd16,javaHome=/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home,daemonRegistryDir=/Users/tudeju/.gradle/daemon,pid=68357,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]}.

**Comment by Anthonyzou** [comment]
@deju Killing the gradle daemon and retrying fixed that issue for me

**Comment by eds101** [comment]
Killing the gradle daemon fixed that issue for me as well. But what the heck -- I have to keep doing it!

**Comment by eds101** [comment]
@deju @Anthonyzou  Did either of you find a long term solution to this? Rather than just having to kill gradle daemon like once per day?

**Comment by Anthonyzou** [comment]
@eds101 I don't seem to have the issue with the latest version of RN.
Maybe update your CLI version of react-native? If that doesn't work update the project version of react native.

**Comment by eds101** [comment]
@Anthonyzou Thanks!

**Comment by fendorio** [comment]
@Anthonyzou 's solution works. I killed Android Studio and the CLI build was successful.
