### ISSUE TITLE
codegen cli not accessible

### ISSUE THREAD

**Issue by imtheaman** [facebook/react-native#42689]
### Description

As per the docs, we're suggested to use ```npx react-native codegen ...``` to generate code and don' care bou' new arch. or old arch. but that's resulting into `codegen not a command` error. i installed @react-native/codegen as well, but that didn' work as well.

### Steps to reproduce

1. create an example rn-turbo-module
2. try generating code with the command suggested in the docs
i.e. ```npx react-native codegen --path={your_module_path} --platform=all --outputPath={generated dir path}```

expected error:
codegen: command not found

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

TurboModule - The New Native Module System, Codegen

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M2
  Memory: 118.33 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/a_man/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

/* ran it inside my turboModule package repo */
```

### Stacktrace or Logs

```text
error: unknown command 'codegen'
```

### Reproducer

https://github.com/imtheaman/rn-unique-identifier

**Comment by cipolleschi** [comment]
Hi @imtheaman, thanks for opening the issue, but it does not apply.
If you look at the website, the selector is set to `next`. This means that you are looking at the doc for the Next version of react-native: 0.74.

It is expected for that feature not to be available in 0.73.

<img width="1481" alt="Screenshot 2024-01-27 at 11 05 26" src="https://github.com/facebook/react-native/assets/11162307/6e10f0c8-b692-414b-9340-6c558e7702a8">

**Comment by cortinico** [comment]
> @imtheaman You can use react-native 0.74.0-beta3 in package.json to use this now

You should not depend on react-native@0.74.0-beta3 directly in your package.json as you will most likely forget to update it once 0.74.0 is released

**Comment by imtheaman** [comment]
> EDIT: For future travelers, I used: node node_modules/react-native/scripts/generate-codegen-artifacts.js -p . -o tm. The Android documentation seems to reference "tm_build" but I'm not sure if that's the intended or that should be changed to 'build'

what's `tm_build`?

**Comment by therealpurplemana** [comment]
> > EDIT: For future travelers, I used: node node_modules/react-native/scripts/generate-codegen-artifacts.js -p . -o tm. The Android documentation seems to reference "tm_build" but I'm not sure if that's the intended or that should be changed to 'build'
> 
> what's `tm_build`?

It was this line in the CMakeLists.txt file that confused me:

+ add_subdirectory(${REACT_ANDROID_DIR}/../../../tm/ tm_build)

It seems to be correct because Android and iOS both build properly out of the box for me!  iOS requires me to build using XCode for some reason but it works for now.
