### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-React-Native-Project-Root"]  at ServerResponse.setHeader (node:_http_outgoing:651:3)

### ISSUE THREAD

**Issue by bouakram** [facebook/react-native#42680]
### Description

**Description:**

I encountered the following error when starting a new React Native project:

### Steps to reproduce

**Steps to Reproduce:**

1. Create a new React Native project using the React Native CLI.
2. Run the project using the command: npm start -> a for android.
3. Observe the error mentioned above.

**Expected Behavior:**

I expected the new React Native project to start without any errors.

**Error:**

info Opening app on Android...
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-React-Native-Project-Root"] at ServerResponse.setHeader (node:_http_outgoing:651:3)

**Environment:**

- Node.js version: >=18
- npm version: 10.1.0

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
...
System:
  OS: Windows 11 10.0.22621
  CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
  Memory: 2.37 GB / 15.77 GB
Binaries:
  Node:
    version: 18.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio: Not Found
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
...
```

### Stacktrace or Logs

```text
info Opening app on Android...
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-React-Native-Project-Root"]
    at ServerResponse.setHeader (node:_http_outgoing:651:3)
    at statusPageMiddleware (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\@react-native-community\cli-server-api\build\statusPageMiddleware.js:19:7)
    at call (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:239:7)
    at next (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:183:5)
    at next (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:161:14)
    at next (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:161:14)
    at next (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:161:14)
    at next (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:161:14)
    at nocache (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\nocache\index.js:11:5)
    at call (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\connect\index.js:239:7)
```

### Reproducer

https://github.com/bouakram/reactnp

### Screenshots and Videos

![ERRORRRRRR](https://github.com/facebook/react-native/assets/75098963/ab23f77a-a9c2-4610-93b3-31ad4fbd0c9b)

**Comment by cortinico** [comment]
>     at statusPageMiddleware (C:\Users\kikou\OneDrive\المستندات\ReactNative projects\algbnb\client\node_modules\@react-native-community\cli-server-api\build\statusPageMiddleware.js:19:7)


I believe the characters you have in the path could be the culprit.
Anyway this code you're hitting is part of the Community CLI so you should report it here:

https://github.com/react-native-community/cli/issues

**Comment by lxtuyen** [comment]
I'm also facing this same situation, someone help me

**Comment by RafikGadzhiyev** [comment]
I had the same issue. And I was researching a lot and I found this^
1. Go to `node_modules/@react-native-community/cli-server-api/build/statusPageMiddleware.js`
2. On line 19 wrap process.cwd() to new URL() like this:
`new URL(process.cwd())
`3. Before reload clean cache in `npm using npm cache clean --force`
4. Run using `npm run start` / `npm run android`

I hope this will help you too 😇

**Comment by lxtuyen** [comment]
I think this is problem The following packages should be updated for best compatibility with the installed expo version:
  expo@50.0.2 - expected version: ~50.0.4
Your project may not work correctly until you install the correct versions of the packages.

**Comment by Andrey123815** [comment]
Can't solve problem by all listed ways (((
expo version ^50.0.7

**Comment by KhvatikG** [comment]
I had the same problem, moving the project to a directory whose path does not contain spaces and non-Latin characters helped. For example: C:\NativeProject\

**Comment by Esraa22M** [comment]
> I had the same issue. And I was researching a lot and I found this^
> 
> 1. Go to `node_modules/@react-native-community/cli-server-api/build/statusPageMiddleware.js`
> 2. On line 19 wrap process.cwd() to new URL() like this:
>    `new URL(process.cwd())`
> 3. Before reload clean cache in `npm using npm cache clean --force`
> 4. Run using `npm run start` / `npm run android`
> 
> I hope this will help you too 😇

**Comment by Esraa22M** [comment]
worked with me

**Comment by yg10323** [comment]
> I had the same problem, moving the project to a directory whose path does not contain spaces and non-Latin characters helped. For example: C:\NativeProject\

thanks, it worked for me

**Comment by wsilvadev** [comment]
> I had the same problem, moving the project to a directory whose path does not contain spaces and non-Latin characters helped. For example: C:\NativeProject\

Thanks, This worked for me.
