### ISSUE TITLE
onImageChange Callback Is Not Working Properly

### ISSUE THREAD

**Issue by rkcollabro** [facebook/react-native#42695]
### Description

The user is unable to trigger any sort of callback when a `gif` file is selected from the `TextInput` component. Instead, the message "Expo Go doesn't support image insertion here" is seen. The issue persists even after installing `"react-native-image-keyboard": "^2.2.1"` and adding an `onImageChange` callback.

### Steps to reproduce

1. Install the application with `yarn install` (includes "react-native-image-keyboard": "^2.2.1")
2. Launch the app with `expo start`
3. Navigate to the screen with the `TextInput`
4. Select the 'GIF' option from the Google keyboard
5. Select any GIF from the options
6. Notice the message "Expo Go doesn't support image insertion here" is seen AND nothing gets logged in the `onImageChange` callback to suggest that the callback is functioning

### React Native Version

0.72.10

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Memory: 3.30 GB / 15.96 GB
Binaries:
  Node:
    version: 18.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.9971841
  Visual Studio: Not Found
Languages:
  Java:
    version: 20.0.1
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.10
    wanted: 0.72.10
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
No crash, but the toast popup "Expo Go doesn't support image insertion here" appears when selecting a GIF from the `TextInput`.
```

### Reproducer

https://snack.expo.dev/@randyk98/trusting-red-blueberries

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/106646880/5ddf7044-6e7e-4bce-9907-f76772a9e5da)
![image](https://github.com/facebook/react-native/assets/106646880/5e4e99ef-1ea6-4445-a52e-78a6201cb738)
![image](https://github.com/facebook/react-native/assets/106646880/4f5b7a74-17fc-4b0c-bc94-fd65f9a5a91e)
![image](https://github.com/facebook/react-native/assets/106646880/fb4087bd-4da2-4075-8fdf-6c22256d5362)
![image](https://github.com/facebook/react-native/assets/106646880/f456b194-f188-46bd-8e6f-4dd9aa97c111)

**Comment by rkcollabro** [comment]
Issue still happens on version 0.72.10

**Comment by lunaleaps** [comment]
onImageChange isn't a callback on React Native's TextInput. Please move this issue to react-native-image-keyboard repo
