### ISSUE TITLE
"Pacifico" font is not recognized 

### ISSUE THREAD

**Issue by 0xBerard** [facebook/react-native#42693]
### Description

I cannot use the [Pacifico][1] font on React Native. Although I think I have followed all the necessary steps, it cannot recognise the font.

The project when compiled gives no error.

I downloaded the `.ttf` file and added it in a `fonts` folder located in `assets`. 

I ran the command `npx react-native-asset` and built the project again.

File `react-native.config.js`:

```js
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./assets/fonts'],
};
```

Interested file:

```js
<Text style={styles.title}>Test</Text>

title: {
    fontFamily: "Pacifico-Regular", 
    fontSize: 50,
    color: 'white',
    textAlign: 'center',
  },
```

**P.S** I'm not using a library, I imported everything manually, as there is no direct compatibility between Google Fonts and React-Native.

  [1]: https://fonts.google.com/specimen/Pacifico

### Steps to reproduce

1 - Download the `.ttf` file in [Google Fonts](https://fonts.google.com/specimen/Pacifico)

2 - Add the file in `/assets/fonts` folder on your project.

3 - Run `npx react-native-asset` on the Terminal.

4 - Try to import the font with `fontFamily` parameter.

### React Native Version

0.72.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (12) x64 Intel(R) Core(TM) i7-12700K CPU @ 5.00GHz
  Memory: 5.70 GB / 31.82 GB
Binaries:
  Node:
    version: 21.5.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.3.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Intel x86_64 Atom
      - android-33 | Google APIs Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    Versions:
      - 10.0.22621.0
IDEs:
  Android Studio: AI-223.8836.35.2231.10811636
  Visual Studio:
    - 17.8.34408.163 (Visual Studio Community 2022)
Languages:
  Java: 17.0.8
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
// There is no crash failure. The code is working fine.
```

### Reproducer

//

**Comment by badalsaibo** [comment]
Do you see the generated font files on the respective iOS and android folder after your run `npx react-native-asset`?
