### ISSUE TITLE
2048 example crashes on start

### ISSUE THREAD

**Issue by gitim** [facebook/react-native#4270]
Hi! 2048 from examples crashes with red screen of death:
<img width="965" alt="2015-11-21 23 20 28" src="https://cloud.githubusercontent.com/assets/3778452/11320352/29b04c9c-90a7-11e5-9c0b-c74d359c894e.png">
because sprintf module, which is required in YellowBox, was not provided, after manually installing it example works fine. Whether we should add sprint to package.json or stop using it?

**Comment by leeight** [comment]
Missing the `sprintf` dpes in `package.json`

**Comment by ide** [comment]
We need to pull in sprintf from fbjs.

**Comment by mkonicek** [comment]
Good catch! This was fixed in https://github.com/facebook/react-native/commit/6b3a6e59580e71256a3a6b885b0fb8f88bd1cb6e, thanks for reporting it.
