### ISSUE TITLE
No matching version found for @react-native/community-cli-plugin@0.73.14

### ISSUE THREAD

**Issue by msageryd** [facebook/react-native#42713]
### Description

`npx react-native init myAwesomeProject` no longer works as of 0.73.3. 
It works fine in 0.73.2.

Getting: `No matching version found for @react-native/community-cli-plugin@0.73.14`

### Steps to reproduce

`npx react-native init myAwesomeProject`

### React Native Version

0.73.3

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
No output
```

### Stacktrace or Logs

```text
No logs
```

### Reproducer

nope

**Comment by efstathiosntonas** [comment]
0.73.3 just came out, give it some time until all CI are finished and it will be released.

**Comment by msageryd** [comment]
Sure!
Thank you for a speedy reply.

I just wanted to "heads up" others. I was in the middle of creating a new RN project and had to sort out a bunch of Ruby problems. After sorting out the Ruby problems I got this error instead. I didn't realize that I installed new RN version compared to the exact same init-command 20 minutes earlier.

The DX is sometimes not optimal when it comes to installing and upgrading RN. In this case this could have been prevented by releasing a new CLI at the same time. Not a biggie, but maybe unneccesary badwill for the RN installer..

**Comment by efstathiosntonas** [comment]
it's released, enjoy 😄

**Comment by msageryd** [comment]
I'm sorry. Don't want to be a PITA. 
Just curious, what is "catching up". Do you mean that the CI is generating files and it's not yet done? How long do this normally take?

**Comment by kamyarz-aws** [comment]
Now I am getting this 

npm ERR! notarget No matching version found for @react-native/metro-babel-transformer@0.73.14. I am getting it for any npm install that I do before this I was getting the above

**Comment by efstathiosntonas** [comment]
@msageryd yes, the CI's are generating all the packages required by react-native to be installed, it takes some time for tests to run for each package, when they finish the packages are published on npm registry.

**Comment by efstathiosntonas** [comment]
it's fine now, here's the list of the CIs running: https://app.circleci.com/pipelines/github/facebook/react-native

**Comment by samtsai** [comment]
Btw, I appreciate the back and forth, it's helpful to have both an issue to track and some explanation even if it's just a matter of waiting. Thanks!

**Comment by msageryd** [comment]
Thank you @efstathiosntonas 
This was great information and also a very speedy reply.

**Comment by minhnndev** [comment]
Follow this table [https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility](https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility)
Ex: `npx @react-native-community/cli@14.0.0 init RNAquariuxMovie --version 0.75.5`

**Comment by minhnndev** [comment]
Follow this table [https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility](https://github.com/react-native-community/cli?tab=readme-ov-file#compatibility)
Ex: `npx @react-native-community/cli@14.0.0 init myAwesomeProject --version 0.75.5`
