### ISSUE TITLE
Hermes WeakRef Support in React Native

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native#42742]
### Description

Hermes has support for `WeakRefs`, but we're missing the integration code on React Native to properly enable.

From Original Issue: https://github.com/react-native-community/discussions-and-proposals/issues/741

---

From https://github.com/facebook/hermes/issues/658 and https://github.com/facebook/hermes/issues/1195, it seems that this requires action on the React Native side (enabling the microtask-queue flag for Hermes and then routinely calling drainMicrotasks).

**Comment by efstathiosntonas** [comment]
@cortinico I think @apollo/client@3.9.0 which was released yesterday is affected by this: https://github.com/apollographql/apollo-client/issues/11543

They introduced the `toBeGarbageCollected.ts` which uses `WeakRef`: https://github.com/apollographql/apollo-client/commit/7d939f80fbc2c419c58a6c55b6a35ee7474d0379#diff-83faa655149377a65d05a36458355e0a84925b36d1ebe017f68196c27a369670

**Comment by phryneas** [comment]
Generally, `@apollo/client` in all versions is impacted by this - we use `WeakRefs` for our internal LRU `WeakCache` implementation and in React Native we have to fall back to default behaviour which is a lot more memory-consuming - things stay in memory even if they aren't used in the rest of the app until the cache will reach it's maximum size and things will be cache-collected because of that.

It still works, and it's not growing indefinitely, but it could be a lot better (like on every other platform) if `WeakRef` were available.

**Comment by nbarrow-inspire-labs** [comment]
Is there any updates on this?

**Comment by cortinico** [comment]
> Is there any updates on this?

Nope we'll be sharing updates here once we have them

**Comment by rubennorte** [comment]
This is fixed by #43396, which was just merged. Please take into account that this will only work in the new RN architecture.

**Comment by rubennorte** [comment]
This is fixed by #43396, which was just merged. Please take into account that this will only work in the new RN architecture.

**Comment by teodorciuraru** [comment]
> This is fixed by #43396, which was just merged. Please take into account that this will only work in the new RN architecture.

@rubennorte Awesome news! So I'm using constructs like `WeakRef` and `FinalizationRegistry` inside my new-arch RN project, basically doing nothing. Can you please tell me how to use this new functionality you say it was implemented?

**Comment by rubennorte** [comment]
You'd need to use RN from the main branch because this was just merged. I can reopen the issue and close it when we release 0.75 (which is going to be the version this is shipped in).

If you want to test it now, you can clone the repository and build the RNTester app :)

**Comment by teodorciuraru** [comment]
@rubennorte If I need this functionality before 0.75, do you think it's feasible to have them exposed through JSI (i.e. `WeakRef`, `FinalizationRegistry`) or I'll bump into some blockers?

**Comment by rubennorte** [comment]
> @rubennorte Thank you. If I need this functionality before 0.75, do you think it's feasible to have them exposed through JSI (i.e. `WeakRef`, `FinalizationRegistry`) or I'll bump into some blockers?
> 
> Incidentally, do you know the estimated release date for 0.75 or how can I access such a roadmap?

Unfortunately, this depends on having support for microtasks in Hermes, which is only supported with the new event loop that's only on main. You'll have to wait for 0.75. The branch cut for 0.74 was done recently, so this might take a while (possibly end of Q2 or beginning of Q3).

**Comment by teodorciuraru** [comment]
@rubennorte, will this new work on a new event loop give us also a solution for long-running background C++ callbacks that require access to the JSI runtime object? I'm solving this by continuously polling for a new JSI runtime, the same as N-API (which hits hard on the battery).

**Comment by rubennorte** [comment]
> @rubennorte, will this new work on a new event loop give us also a solution for long-running background C++ callbacks that require access to the JSI runtime object? I'm solving this by continuously polling for a new JSI runtime, the same as N-API (which hits hard on the battery).

Sorry I don't have context about that. Can you share more details?

**Comment by cyrillicw** [comment]
Will FinalizationRegistry be supported as well or only WeakRefs get supported?

**Comment by rubennorte** [comment]
> Will FinalizationRegistry be supported as well or only WeakRefs get supported?

That's a question for Hermes, but I think FinalizationRegistry isn't supported yet.

**Comment by teodorciuraru** [comment]
How can we enabled `WeakRef` for the legacy architecture too? I get `ReferenceError: Property 'WeakRef' doesn't exist, js engine: hermes` (RN 0.75, old architecture).

**Comment by rubennorte** [comment]
> How can we enable `WeakRef` for the legacy architecture too? I get `ReferenceError: Property 'WeakRef' doesn't exist, js engine: hermes` (RN 0.75, old architecture).

Unfortunately it's not possible, as `WeakRef` require support for microtasks, which is only implemented in the new architecture.

**Comment by teodorciuraru** [comment]
@rubennorte, is it planned to be implemented for the legacy arch too or we hope that everyone will eventually switch to the new one? I'm curious if you know any strategy to mock it in the meantime or if we should just accept the memory handling constrains of it.

**Comment by rubennorte** [comment]
> @rubennorte, is it planned to be implemented for the legacy arch too or we hope that everyone will eventually switch to the new one? I'm curious if you know any strategy to polyfill it in the meantime or if we should just accept the memory issues of mocking it.

It would require a lot of work to support it in the legacy architecture because there are a lot of missing pieces, so we're not going to do that.

AFAIK there's no way to polyfill it in a way that retains its semantics (in other words, you'll have to keep things in memory).
