### ISSUE TITLE
Update package.json with sprintf module.

### ISSUE THREAD

**Issue by prashanth1509** [facebook/react-native#4274]
Cannot find a equivalent module on npm repository. Please provide a npmrc / publish to npm repo.

**Comment by HotWordland** [comment]
yes i found this problem and solve by manual npm install sprintf

**Comment by skevy** [comment]
@prashanth1509 there is a module on npm called sprintf: https://www.npmjs.com/package/sprintf

React Native uses a vendored version from FBJS.
