### ISSUE TITLE
Setting up RN environment for macOS Sonoma m2 chip is failing

### ISSUE THREAD

**Issue by BernardoOlisan** [facebook/react-native#42755]
### Description

’ve been trying to use React Native in a macOS Sonoma m2 chip, with the `react-native-cli`. Following the documentation of RN setting up the environment for macOS IOS, is not working for me and this is why.

First, I tried the following process.

1. Install Xcode (current version 15.2) and command line tools.
2. Using the command `npx react-native init MyProject` everything seems to work at the beginning, but when the **installing dependencies** arrived, it throws “*error installing pods”*, or sometimes *“error installing cocoapods”.* And obviously, RN says, *“this doesn’t affect the initialization, but you will need to install cocoapods and pods manually”.* So I did that.
    1. Run `cd /MyProject` and `sudo npm install`
    2. Run `cd /ios` and `bundle install` in my case what it worked was `sudo bundle install` because it was giving me a permission error.
    3. Run `bundle exec pod install` thanks to the permission error, it worked `sudo bundle exec pod install --allow-root`
    4. Finally we can execute the app in Xcode by opening the `.xcworkspace` and hitting run. I have to mention that I changed the permissions to read & write in order for me to open the folder, I changed it for `.xcworkspace` `.xcodeproj` and inside the **/pods** folder the permissions for `.xcodeproj`

Everything installed correctly, but when hitting run in Xcode, the build failed giving me the logs of “*Command PhaseScriptExecution failed with a nonzero exit code*”. I don’t know if this has to do with the changes I made in the process, like the permissions from point number 4 (I was not able to open the file if I didn’t change permissions) or maybe instead of `bundle exec pod install` I ran `sudo bundle exec pod install --allow-root` 

I know I can install cocoapods by using Homebrew or Gems, and I tried this:

1. Run `brew install cocoapods` or `sudo gem install cocoapods`
2. Then I saw in some forums that for mac m1/m2 chips, it was necessary to install `sudo gem install ffi -n /usr/local/bin` 
3. Then run in the **/ios** folder `pod install` in my case, thanks to permissions errors, it was `sudo pod install --allow-root`

This last commands didn’t work, with Homebrew or Gems, because it gave me the error “*Failed to install hermes_engine*”. I know that hermes_engine takes a lot of space and I need to install it another way, but even setting hermes_engine to false, in my Podfile `:hermes_enabled => false` the installation was a success with `sudo pod install --allow-root` but, hitting run in Xcode gave me the same error “*Command PhaseScriptExecution failed with a nonzero exit code*”.

I saw that maybe the ruby version was the problem to all of this, but even installing a ruby version with Homebrew was not working, it was causing the same errors from `pod install`. I didn’t tried using RVM.

I tried uninstalling everything, Node, Homebrew, … And installing them again, but it was giving me the same errors. I also tried using the terminal Rosetta2 and `sudo arch -arm64 pod install --allow-root` but reached the same place. 

I really don’t know what is going on. Some people in tutorials manage to run the installation of react native init cleaned, while I’m dealing with it all the time without being able to run neither with the terminal or Xcode. Maybe I’m missing something, is there a solution to my problem? and please, don’t tell me to use ExpoGo with a bare workflow, because It didn’t work too and I want to work with the react-native-cli to go deeper in native stuff.

This is my current setup:

- macOS: Sonoma M2 chip
- Ruby: 2.6.10 (System default)
- Node: 20 (Current LTS)
- Xcode: 15.2
- Homebrew: 4.2.3
- Gem: 3.0.3.1

### Steps to reproduce

1. Clone the project
2. cd /project and run `npm install`
3. That's it

### React Native Version

0.73.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M2
  Memory: 347.84 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducer

https://github.com/BernardoOlisan/testRN

**Comment by cortinico** [comment]
Have you looked through the other issues on the repo?
https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+%22Command+PhaseScriptExecution+failed+with+a+nonzero+exit+code%22

In general we don't offer specific support for environment problems.

Your code looks fine to me. I suggest you seek support on StackOverflow or other forums.

**Comment by huzaifahazelGit** [comment]
> Have you looked through the other issues on the repo? https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+%22Command+PhaseScriptExecution+failed+with+a+nonzero+exit+code%22
> 
> In general we don't offer specific support for environment problems.
> 
> Your code looks fine to me. I suggest you seek support on StackOverflow or other forums.

I looked through the other all  issues on the repo but no any found against this error,,,,,this error occur when I have used macbook pro m2 with latest react native 0.73.4 ,node version 

So kindly provide exact solution
