### ISSUE TITLE
(RN 0.72.5) How do we disable `hermes` for debug variant of Android App and keep `hermes` enabled for release variants?

### ISSUE THREAD

**Issue by siddarthkay** [facebook/react-native#42766]
### Old Version

0.69.10

### New Version

0.72.5

### Description

This is more of a question and an attempt to figure out if something needs to be added to react-native to make this easier.
Prior to upgrading to react native 0.70.x we were able to disable `hermes` for our debug builds like this -> https://github.com/status-im/status-mobile/pull/14041
After we upgraded to react native 0.72.5 I kept `hermes` enabled and then later realised that we need to disable it for debug variants.

However when I tried to do so I could not find a straightforward way to do so.
If I keep `hermesEnabled` as `false` in `gradle.properties` hermes is now disabled for all build variants.
We want to disable it for debug but keep it enabled for release variants so that we can reap the benefits of the Hermes Engine.

I tried a very hacky way to achieve this here -> https://github.com/status-im/status-mobile/pull/18675
but I am not sure if this is the best way to do so.

### Steps to reproduce

Just try to get `hermes` to be disabled when you do `npx react-native run-android` and keep it enabled when you prepare it for release on react-native 0.72.x and above.

### Affected Platforms

Runtime - Android, Build - MacOS, Build - Linux

### Output of `npx react-native info`

```text
[nix-shell:~/code/status-im/PR/status-mobile]$ npx react-native info
warn Package react-native-blob-util contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 14.3
  CPU: (8) x64 Apple M2
  Memory: 20.21 MB / 24.00 GB
  Shell:
    version: 5.2.21
    path: /nix/store/5cvi09jkz66vlp62zbqxvjybc6yn1cqh-bash-interactive-5.2-p21/bin/bash
Binaries:
  Node:
    version: 18.16.0
    path: /nix/store/4d4sar5gv82d7wn96lq1ddxq3vxfh7h1-nodejs-18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /nix/store/y4yns1i4j0p15v3yjhdvwsfilg7s78qm-yarn-1.22.19/bin/yarn
  npm:
    version: 9.5.1
    path: /nix/store/4d4sar5gv82d7wn96lq1ddxq3vxfh7h1-nodejs-18.16.0/bin/npm
  Watchman:
    version: 4.9.0
    path: /nix/store/ak2bihxc4by13kpw8fdln3pdbmpqhdm6-watchman-4.9.0/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "33"
    Build Tools:
      - 33.0.0
    Android NDK: 25.2.9519653
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /nix/store/cpp2dbw1189xj7xd4073iy13saczcr3i-zulu11.48.21-ca-jdk-11.0.11/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/siddarthkumar/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
There is no failure stacktrace, only the failure of my ability to disable hermes on debug builds :)
```

### Reproducer

https://github.com/status-im/status-mobile

**Comment by cortinico** [comment]
> After we upgraded to react native 0.72.5 I kept `hermes` enabled and then later realised that we need to disable it for debug variants.

Why do you need to disable Hermes only for debug?
Ultimately, this is not a supported configuration. You should be using Hermes for both Debug and Release.

**Comment by JB712** [comment]
@cortinico To be able to debug via [react-native-debugger](https://github.com/jhen0409/react-native-debugger) which use a Chrome debug console, we need to disable Hermes.

**Comment by cortinico** [comment]
> @cortinico To be able to debug via [react-native-debugger](https://github.com/jhen0409/react-native-debugger) which use a Chrome debug console, we need to disable Hermes.

Have you tried using our experimental debugger?
https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#debugging-improvements

Ultimately this is a problem of [react-native-debugger](https://github.com/jhen0409/react-native-debugger) so they should provide you support here

**Comment by siddarthkay** [comment]
> Why do you need to disable Hermes only for debug

Hi @cortinico : we found here https://github.com/status-im/status-mobile/issues/18493#issuecomment-1916614254 
that our debug app crashes very often during development time when `hermes` is enabled, we tried a few things listed in this issue to fix this crash but what worked best was to disable `hermes`

**Comment by siddarthkay** [comment]
Anyone that came here trying to figure this out, I was able to turn `hermes` off by setting this environment variable locally : 
`export ORG_GRADLE_PROJECT_hermesEnabled := false`
ref -> example 3 from here : https://docs.gradle.org/current/userguide/project_properties.html
my CI will refer to `gradle.properties` where `hermesEnabled` is set to true.

So this problem is solved for me.
