### ISSUE TITLE
Getting Error While initialization react native app in ubuntu 

### ISSUE THREAD

**Issue by ankitshivmalan** [facebook/react-native#42765]
### Description

when i am initialization the new project in react native in Ubuntu 22.04.3 LTS. i am getting error of "Template is not getting Download" ---> "✖ Downloading template". while i perform the same on windows it's executed perfectly but the issue i am facing in ubuntu

### Steps to reproduce

1.Setup the environment as described in the react native documentation 
2. command for initialization a new project

### React Native Version

0.73.0

### Affected Platforms

Build - Linux

### Output of `npx react-native info`

```text
Downloading templateerror Cannot parse yarn version: 
⠴ Downloading templateerror Cannot parse yarn version: 
error Cannot parse yarn version: 
⠹ Downloading templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

✖ Downloading template

  
  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/home/whited3vil/myNewProject12" && npx react-native run-android
```

### Stacktrace or Logs

```text
Downloading templateerror Cannot parse yarn version: 
⠴ Downloading templateerror Cannot parse yarn version: 
error Cannot parse yarn version: 
⠹ Downloading templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

✖ Downloading template

  
  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/home/whited3vil/myNewProject12" && npx react-native run-android
```

### Reproducer

NA

### Screenshots and Videos

![Screenshot from 2024-01-31 17-27-17](https://github.com/facebook/react-native/assets/58619844/fb53345b-8e1f-410d-a89f-0effd06b8477)

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-community/cli/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.

**Comment by luizricardo-co** [comment]
Same error

**Comment by ankitshivmalan** [comment]
@luizricardo-co  please try this :
npm install -g yarn
yarn global add react-native-cli
react-native init sample
yarn run android
yarn start
