### ISSUE TITLE
Slowness during manipulations with HTML/strings

### ISSUE THREAD

**Issue by maksimlya** [facebook/react-native#42797]
### Description

Hi, my company is trying to migrate from using webview on android to use React Native with Hermes engine. We had some limited success(start time, debugging tools etc), but same time some bottlenecks that we are trying to solve.

One think I noticed is a big regression when working with html (in our case we use cheerio lib which imitates usage of JQuery in webworker environment.

I added quite simple test in here with comparison to other envs that shows how slow processing of the function is:

```
RN With Hermes(Redmi note 9): 3500 ms
RN JSC(Redmi note 9): 1700 ms
Android Webview(Redmi note 9): 150-200 ms
iOS Webview(iphone XR): 90 ms
NodeJS(Mac mini 2018): 150 ms
```

What I tried so far - using outdated https://www.npmjs.com/package/react-native-cheerio lib, with it I could reduce the timings to:

RN With Hermes:    1700 ms
RN JSC:                      1200 ms

Yet it still at least 8-10 times slower than even Android Webview(which we trying to move away from due to it working on Android's UI thread).

Attaching here also the sampling profile for the operation.

Wanted to ask, what are my options in here? Obviously something is not optimized in here, but my project relies on lots of other cheerio/string/html manipulations for which we need high performance on.
Is it better to look for other libraries? Or maybe to try to  use some native GO modules via JSI?

### Steps to reproduce

npm i
npm start

'a' to run android

### React Native Version

0.73.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Linux 6.6 Fedora Linux 39 (KDE Plasma)
  CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Memory: 17.62 GB / 31.28 GB
  Shell:
    version: 5.2.26
    path: /bin/bash
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
LOG  Running "testRN" with {"rootTag":11}
 LOG  start
 LOG  cheerio.load done: 1185
 LOG  After append: 34
 LOG  After convert tables: 98
 LOG  After img processing: 11
 LOG  After video processing: 7
 LOG  After body processing: 2171
 LOG  After styles processing: 14
 LOG  After html generate: 21
 LOG  After html unescapeAmpersands: 6
 ERROR  ExecutionTime = 3549
```

### Reproducer

https://github.com/maksimlya/TestRNPerf.git

### Screenshots and Videos

[sampling-profiler-trace4726458570050190420-converted.json](https://github.com/facebook/react-native/files/14131562/sampling-profiler-trace4726458570050190420-converted.json)

![Screenshot_20240202_000907-1](https://github.com/facebook/react-native/assets/18153628/66fef4ef-72dc-46c5-a408-ce40c212cfc4)

**Comment by cortinico** [comment]
You should report this to the library author, and not to react-native core:
https://github.com/leon3110l/react-native-cheerio
