### ISSUE TITLE
[NavigatorIOS] back button and componentWillReceiveProps

### ISSUE THREAD

**Issue by igodzp** [facebook/react-native#428]
I have 2 components: ```HomeScreen (initialRoute)``` and ```SettingScreen```. When the right nav button is clicked, the ```SettingScreen``` is pushed to the navigator. 

The problem is whenever the back button is clicked, the ```componentWillReceiveProps``` function in the ```HomeScreen``` triggers. Is this behavior intentional?

**Comment by christopherdro** [comment]
@igodzp Any updates?

**Comment by brentvatne** [comment]
Unfortunately we don't have anybody working on NavigatorIOS, Navigator is the recommended way to go. I can't comment on whether or not this is intended, but if you can point to why this is a problem for you and explain your use case then we can discuss further! Is it causing issues for you? And is this still happening? :smile: Sorry for not getting back to you more quickly. Feel free to ping me and I can reopen this if this is causing you problems.
