### ISSUE TITLE
[upgrade] 0.13 to 0.14, have to change every asset manually?

### ISSUE THREAD

**Issue by viix** [facebook/react-native#4280]
I have checked http://facebook.github.io/react-native/docs/upgrading.html#from-0-13-to-0-14
and know 0.14 use new asset system
but if upgrade from 0.13 to 0.14, to use the new asset system, do I have to change every image folder and require src location manually?

**Comment by satya164** [comment]
You can write a script to do it for you.

**Comment by christopherdro** [comment]
@viix Yes, unfortunately thats the case :(
But as @satya164 suggested, you can try writing a script if you have a lot of assets to deal with.

**Comment by viix** [comment]
@satya164 @christopherdro got it, thanks
