### ISSUE TITLE
iOS Native App Sending GET Requests Instead of POST on Form Submission When Navigated URL Contains Query Parameters

### ISSUE THREAD

**Issue by ramchandra-st** [facebook/react-native#42807]
### Description

In the iOS native app, when performing a form submission with the HTTP method POST, the application is sending a GET request instead of the intended POST request. This behavior occurs specifically when the app navigates to a URL that contains query parameters.

### Steps to reproduce

Steps to Reproduce:
1. Open the iOS native application.
2. Navigate to a screen or view within the application that contains a form.
3. Fill out the form fields with the necessary information.
4. Submit the form using the POST method.
5. While submitting, ensure that the application navigates to a URL that includes query parameters.

### React Native Version

0.71.14

### Affected Platforms

Runtime - iOS

**Comment by cortinico** [comment]
> Navigate to a screen or view within the application that contains a form.

Please provide a repro
