### ISSUE TITLE
with-environment.sh does not work properly with .xcode.env

### ISSUE THREAD

**Issue by msageryd** [facebook/react-native#42804]
### Description

The purpuse of `xcode.env` is to export your own node executable path without messing with the build script.

This does not work properly when using NVM, due to `with-environment.sh` trying to call `node -v` prematurely.

`with-environment.sh` crashes at line 16 because there is no node executable to be found before `nvm.sh` is sourced.

```
# Start with a default
NODE_BINARY=$(command -v node).  # this is line 16
```

If `xcode.env` is used correctly with NVM, `nvm.sh` should be sourced in this file before the call to `node -v`. Unfortunately, `xcode.env` itself is sourced after line 16 in `with-environment.sh`, which is too late. Line 16 isn't even needed since the same call is performed in `xcode.env`.

Workaround:
Remove line 16 in `with-environment.sh`.
```
# Start with a default
#NODE_BINARY=$(command -v node)
```

I suggest that the premature call to node from within `with-environment` is removed so the nicely separated `xcode.env` can do it's thing.

### Steps to reproduce

1. Install NVM
2. Update xcode.env as per the commented instructions
3. Build from XCode

### React Native Version

0.73.3

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
not needed
```

### Stacktrace or Logs

```text
+++ command -v node
++ NODE_BINARY=
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducer

nope

**Comment by msageryd** [comment]
Will this issue be disregarded because I don't have a "Reproducible Example"?
I have exactly pinpointed a problem at line 16 in a bash file. What more can I do?

**Comment by cortinico** [comment]
Already fixed by https://github.com/facebook/react-native/pull/42184

If you wish to have this backported to 0.73, please comment on the relevant discussion on https://github.com/reactwg/react-native-releases/

**Comment by msageryd** [comment]
Great thanks!
I searched in issues, but didn't find any on this. Hence my post.

**Comment by msageryd** [comment]
I didn't get a fixed with-environment.sh with my upgrade to 0.74.4. Was this patch omitted when picking patches for 0.73.4?

No big deal for me. I just want to understand how releases and patch-picking works.

**Comment by cortinico** [comment]
This pick in only on main.

> If you wish to have this backported to 0.73, please comment on the relevant discussion on [reactwg/react-native-releases](https://github.com/reactwg/react-native-releases/)

As I said, if you want this pick to be picked on the future 0.73.x, head over to https://github.com/reactwg/react-native-releases/ and comment on the relevant conversation

**Comment by msageryd** [comment]
Ah, ok.
I thought you meant backported to 0.73.3 and it would be automatically picked for the next release. I think this should be picked ASAP in order to minimize the hazzle for people encountering this. I'll leave a comment in the release-conversation.

**Comment by bheftyes** [comment]
@msageryd what is your .xcode.env looking like? I can't seem to be able to get nvm to work.

**Comment by msageryd** [comment]
@bheftyes I haven't revisited this since I solved the problem brute-force. Currently I have hardcoded my Node path.

```
export NODE_BINARY=/Users/michaelsageryd/.nvm/versions/node/v18.19.0/bin/node
```

**Comment by zhouhao27** [comment]
I still got this issue in 0.76.1. My Xcode version is 16.1. Any idea?
