### ISSUE TITLE
How can a team not include a simple way of including fonts?

### ISSUE THREAD

**Issue by imrnh** [facebook/react-native#42834]
### Description

Been doing RN for a long period. And surely it gots many worst practices. But adding fonts take eternity. How come such a necessary things hasn't been simplified. No wonder facebook's product.

### Steps to reproduce

Literally create a new project and try to add another fonts.

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android, Runtime - iOS, Runtime - Web, Runtime - Desktop, Build - MacOS, Build - Windows, Build - Linux

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
  Memory: 569.06 MB / 7.70 GB
Binaries:
  Node:
    version: 20.5.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.8.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowAllTrustedApps: Disabled
IDEs:
  Android Studio: AI-231.9392.1.2311.11255304
  Visual Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
nothing
```

### Reproducer

https://github.com/facebook/react-native

**Comment by cortinico** [comment]
> Been doing RN for a long period. And surely it gots many worst practices. But adding fonts take eternity. How come such a necessary things hasn't been simplified. No wonder facebook's product.

Closing as a violation of our code of conduct:
https://github.com/facebook/react-native/blob/main/CODE_OF_CONDUCT.md#our-standards
