### ISSUE TITLE
Build failed - Xcode caches file contents?

### ISSUE THREAD

**Issue by mrzmyr** [facebook/react-native#4286]
- Run app in Xcode
- Syntax Error found: `Command /bin/sh failed with exit code 1`
- I fix the error 
- Rerun the app with Xcode
- Xcode still points out the same syntax error (I even tried to completely empty my `index.ios.js` file)

Does Xcode caches the files or is it react native ?
Any ideas how to solve this ?

**Comment by gre** [comment]
I guess this is dup with https://github.com/facebook/react-native/issues/3948

**Comment by marcshilling** [comment]
Same issue. The only workaround I have is checking the "Run script only when installing" checkbox under the "Bundle React Native code and images" build phase.

It's definitely caching files.

**Comment by christopherdro** [comment]
https://github.com/facebook/react-native/issues/3948#issuecomment-192737351
