### ISSUE TITLE
[TextInput] RewriteExample not working

### ISSUE THREAD

**Issue by wowpet** [facebook/react-native#4290]
I'm having trouble running TextInputExample.ios.js in the Example, UIExplorer.

TextInputExample.ios.js contains below code, which means the space character will be dynamically updated to dash character upon type

``
<TextInput
          multiline={false}
          maxLength={limit}
          onChangeText={(text) => {
            text = text.replace(/ /g, '-');
            this.setState({text});
          }}
``

I expect type string "a a" will result in "a-a", but the "a a" show up unchanged.

Can someone please check into the issue so the RewriteExample will function as expected

**Comment by satya164** [comment]
You're not setting the text prop. `text={this.state.text}`.

**Comment by wowpet** [comment]
Actually, the code to set the value is here, it's just not updating the value for some reason

Full code below

```javascript
class RewriteExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = {text: ''};
  }
  render() {
    var limit = 20;
    var remainder = limit - this.state.text.length;
    var remainderColor = remainder > 5 ? 'blue' : 'green';
    return (
      <View style={styles.rewriteContainer}>
        <TextInput
          multiline={false}
          maxLength={limit}
          onChangeText={(text) => {
            text = text.replace(/ /g, '-');
            this.setState({text});
          }}
          style={styles.default}
          value={this.state.text}
        />
        <Text style={[styles.remainder, {color: remainderColor}]}>
          {remainder}
        </Text>
      </View>
    );
  }
}
```

**Comment by christopherdro** [comment]
@wowpet It seems to working here https://rnplay.org/apps/tMJKx. However, this example is running 0.13-rc.

I tried locally on 0.14.2 and it does NOT work so I wanted to get some more information from you before trying to debug this further. Could you let me know what version of RN you are using? Thanks!

**Comment by wowpet** [comment]
Hi @christopherdro , thanks for the reply.

I'm testing the code against latest github repository.
```javascript
"name": "react-native",
"version": "0.12.0",
```

I have tested on both iphone 6 plus emulator, and on iphose 5s device.
