### ISSUE TITLE
Intl.RelativeTimeFormat Not Working 0.73

### ISSUE THREAD

**Issue by enchorb** [facebook/react-native#42914]
### Description

All other Intl APIs I tested were working, `Intl.RelativeTimeFormat` throws the error `TypeError: Cannot read property 'prototype' of undefined`. This code was working fine in 0.72/

### Steps to reproduce

```
new Intl.RelativeTimeFormat('en', {
                      numeric: 'auto'
                    }).format(6, 'days')
                  )
```

### React Native Version

0.73.4

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by lunaleaps** [comment]
Verified this occurs in 0.73.3 as well

**Comment by neildhar** [comment]
Hermes has never supported `Intl.RelativeTimeFormat`, so if it was previously working, it was likely through a polyfill. Perhaps the polyfill was dropped in the upgrade?

**Comment by lunaleaps** [comment]
@neildhar Thanks for clarifying and thanks @alfonsocj for verifying! 

@neildhar Is there a place where we can see what is supported in Hermes?

Closing this issue as its not a regression

**Comment by art3mHQ** [comment]
same problem on  0.74.2, also Polyfill `intl-relative-time-format` not working as well

**Comment by JamieGoodson** [comment]
Also getting this error in 2025
