### ISSUE TITLE
Issue with .plist Default Build

### ISSUE THREAD

**Issue by KavanBahrami** [facebook/react-native#4292]
run: react-native init AppName
open: app Info.plist (as source)

Maybe this doesn't make a difference when being read by Xcode, but the 'more info' url thats hard coded into the build seems to be breaking the final NSAllowsArbitraryLoads due to a missing space key between the end of the url and -->

Two screenshots below to show before and after edit.
DEFAULT BUILD:
![screen shot 2015-11-22 at 9 14 26 pm](https://cloud.githubusercontent.com/assets/1649393/11330306/577bb28a-915e-11e5-8f5f-c0dda8295e81.png)
AFTER EDIT:
![screen shot 2015-11-22 at 9 14 48 pm](https://cloud.githubusercontent.com/assets/1649393/11330307/577cd98a-915e-11e5-8cbb-63d907d10f48.png)

**Comment by ide** [comment]
Could you send a PR to fix it?

**Comment by KavanBahrami** [comment]
@ide Would love to but I don't know how. Really just getting started.

**Comment by christopherdro** [comment]
@KavanBahrami I double checked and can confirm the problem. Nice Catch! 
I went ahead and created a PR to fix the issue.

If you'd like to create a PR in the future, you can...
1. Fork the facebook repo
2. Create a separate branch
3. Commit your changes including the issue # if your one exists. i.e "Fixes #4292"
4. Push the changes to your forked repo and create a PR.

Note: You want to make sure that your forked repo is up to date with master. If for some reason some changes get merged while your working on your changes you can use `git rebase -i facebook/master` to sync your version with the current master.

Hope this helps. Thanks again!
