### ISSUE TITLE
Cannot install any packages with npm

### ISSUE THREAD

**Issue by heliumsoule** [facebook/react-native#4293]
Hello,

For some reason, I cannot install any new packages with npm. I tried to do npm install react-native-video --save and received the following error message. 

> bufferutil@1.2.1 install /Users/user/LearningReact/customView/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/user/.nvm/versions/node/v5.0.0/bin/node" "/Users/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/LearningReact/customView/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.2.1 install /Users/user/LearningReact/customView/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/user/.nvm/versions/node/v5.0.0/bin/node" "/Users/user/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/LearningReact/customView/node_modules/utf-8-validate
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1
customView@0.0.1 /Users/user/LearningReact/customView
└─┬ react-native-video@0.6.1 
  └── keymirror@0.1.1 

If anyone could offer some thoughts about why this is occurring that would be very helpful! Thank you in advance.

**Comment by udnisap** [comment]
try removing the node packages and install
```
rm -rf node_modules
npm install
```

if it still persist attache the output of `npm ls`

**Comment by ide** [comment]
This is an issue with your OS X compiler tools. I am fairly sure React Native or the bufferutil dependency are not related. Try restarting your computer -- that has fixed the lgcc error for me before.

**Comment by heliumsoule** [comment]
Thanks so much ide. This solved the issue!

**Comment by idibidiart** [comment]
Thanks @ide  you saved me from having to stay up all night. Restarting did the trick,
