### ISSUE TITLE
 Absolutely positioned TextInput unrespondable after hiding the keyboard with the button

### ISSUE THREAD

**Issue by TMaszko** [facebook/react-native#42968]
### Description

Absolutely positioned TextInput component (with `position: 'absolute'`) is unrespondable after hiding keyboard with the button on Android.

### Steps to reproduce

1. Open provided snack or create TextInput with `position: 'absolute'`
2. Press on the TextInput
3. Hide keyboard with the keyboard button on Android
4. Try to press TextInput to open the keyboard again

### React Native Version

0.72.10

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
Only tried on snack so far. Will provide output of `npx react-native info` soon.
```

### Stacktrace or Logs

```text
I don't have any logs yet. I'll try to reproduce it without expo in the bare react-native app soon.
```

### Reproducer

https://snack.expo.dev/@tmaszko/rn-absolute-text-input

**Comment by Pradnyeshp** [comment]
Any updates on the issue ?
