### ISSUE TITLE
How come RCTPromiseResolveBlock / RCTPromiseRejectBlock isn't mentioned in docs?

### ISSUE THREAD

**Issue by adbl** [facebook/react-native#4301]
I just stumbled upon this article, https://medium.com/the-exponent-log/react-native-meets-async-functions-3e6f81111173#.7vykfox2i

That is great! But why isn't it mentioned in the [Native Modules](https://facebook.github.io/react-native/docs/native-modules-ios.html#content) section of the docs? Seems likely people are not converting their code since the suggested way to handle errors by the docs is still to use node-style `RCTResponseSenderBlock` for async functions?

**Comment by ide** [comment]
Want to send a PR to update the docs?

**Comment by satya164** [comment]
@ide #4306

**Comment by adbl** [comment]
cool @satya164 =)
