### ISSUE TITLE
[Bundle] Does not accept `root` 

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#4303]
Imo should be implemented since the packager accepts that here https://github.com/facebook/react-native/blob/master/local-cli/server/server.js#L34-L36.

Otherwise, with alternative project structure you are going to be able to start packager and serve the jsbundle but you won't be able to generate it with the `react-native-xcode.sh` script.

**Comment by grabbou** [comment]
Solved, but looks like it might be worth including that in docs (rn-cli.config.js)

```js
var defaultConfig = require('react-native/local-cli/default.config.js');
var path = require('path');

var config = {
  getProjectRoots() {
    var roots = defaultConfig.getProjectRoots();
    roots.unshift(path.resolve(__dirname, '../../core'));
    return roots;
  }
}

module.exports = config;
```

**Comment by Apercu** [comment]
@grabbou Instead of creating an extra-file, you can now specify the `--root` option, allowing to add one or more root to the packager
