### ISSUE TITLE
Automatically link native products

### ISSUE THREAD

**Issue by olivierlesnicki** [facebook/react-native#4304]
90% of react-native npm modules that have iOS native functionality only require two steps to be enabled:
- [x] Add the Project to the Library folder
- [x] Link the Product in the Build Phase

Is there no way those two steps can be automated by a shell script?

**Comment by hufeng** [comment]
react-native 0.15 is supported react-native link

**Comment by skevy** [comment]
@olivierlesnicki This is currently a work in progress. As @hufeng says, `react-native link` now exists...but there's a whole workflow that is being built around this currently, that hopefully will make it out soon.

Considering that `react-native link` solves your original issue, would you consider closing this? Stay tuned to the release notes for the official announcement (and documentation) of the feature! :)

**Comment by olivierlesnicki** [comment]
@skevy more than happy to close it. Do you have a link to the command documentation?

**Comment by skevy** [comment]
@olivierlesnicki documentation isn't out yet, but I can point you to the commit :)

https://github.com/facebook/react-native/commit/4e5a2bc0791a77ac67c2b564a220278bea889fcf

It will get documented along with the rest of the workflow when that's finished.
