### ISSUE TITLE
[Android] Static images not displaying - 0.14.2

### ISSUE THREAD

**Issue by jonolock91** [facebook/react-native#4305]
I've upgraded from React native 0.12 I believe it was, to 0.14.2. But now using the new image system which has the new unified way of managing images, my Android images are not showing. I went through the upgrade process and update all my files and the gradle.build file react-native dependency. The images work fine on my iOS version of the app. An example of my code is:

`<Image
     style={{height:50,width:50}}
     source={require('./images/logo.png')}
     />`

**Comment by edenman** [comment]
@jonolock91 http://facebook.github.io/react-native/docs/upgrading.html#from-0-13-to-0-14

**Comment by jonolock91** [comment]
@edenman I've gone through that twice now and can't see any reason why it might not be showing. I updated my Xcode IDE as displayed on the upgrade page and my iOS app works fine, just my Android...

**Comment by edenman** [comment]
@jonolock91 sorry, misread.

**Comment by lizhangqu** [comment]
@jonolock91 https://github.com/WoLfulus/react-native/commit/33e2d052b6e2e3e6b3595572abbc3cb9b66d5755

**Comment by jonolock91** [comment]
@lizhangqu I just made that change, but still no luck. Is there any specific name/location where the image directory should sit? My directory is called 'images' and sits in the main directory on the same level as Android, iOS etc.

**Comment by jonolock91** [comment]
From the function getScaledAssetPath the correct image path is returned which successfully displays on my localhost http://localhost:8081/assets/images/logo.png.

**Comment by mkonicek** [comment]
Can you see the packager printing logs about fetching the assets?

You could try out version 0.15.0 which just shipped.

**Comment by jonolock91** [comment]
I can't see anything on my packager output relating to images, I'll try upgrading to 0.15.0.

**Comment by jonolock91** [comment]
0.15.0 broke my Xcode with a node module of icons that I'm using so I reverted to 0.14.2.

**Comment by satya164** [comment]
For me it was not showing in the debug version. Clearing the app data helped.

**Comment by rmevans9** [comment]
@satya164 can you elaborate on what you mean by clearing the app data? 

I am having the issue @jonolock91 describes in a project created on 0.14.2 and then upgraded to 0.15.0. Neither version was showing images correctly on either my mac or windows 10 machines. I dug into the issue a bit last night and found that when pulling the image path which ends up being http://localhost:8081/assets/...etc if I switched the path manually to the IP of the computer running the React Native package it worked. If I leave it localhost and fails. I intend to dig into it a bit more later but if you have a simple solution then it'll save me some time!

**Comment by satya164** [comment]
System Settings > Apps > Your app > Clear data

**Comment by rmevans9** [comment]
ah within the emulator. I was thinking you mean something in the project. I tried it and no luck. I will have to dig into this more later and see if it is just something on my machine/setup or what might be going on. Thanks for the info!

**Comment by jonolock91** [comment]
@satya164 I tried clearing the data on my app through met emulator and that hasn't worked. I still haven't managed to figure out the problem.

**Comment by satya164** [comment]
@jonolock91 That's weird. Try creating a new project and copy your changes over. That should work.

**Comment by jonolock91** [comment]
@satya164 ah that's actually worked, with react native version 0.15.0, I'm sure I had tried this before but it's working now! Thanks! I'll just copy across my application across now piece by piece. Might be worth keeping this open for @rmevans9 until his issue is resolved.

**Comment by satya164** [comment]
@jonolock91 Glad that it workd.

**Comment by christopherdro** [comment]
@rmevans9 Are you still having issues?

**Comment by rmevans9** [comment]
My issue was resolved by applying the fix from PR#4416. It hasn't been merged yet but this got it going for me.

**Comment by christopherdro** [comment]
:+1: Nice! Thanks for reporting back so quick!

**Comment by mkonicek** [comment]
Cool, merging that PR now, let's close this so we don't forget to close it once that lands.

**Comment by pareekkhushboo77** [comment]
you can load static images by converting images into base64 and loading base64 ..
I have used it, and its working absolutely flawless..
It is also stated in official React Native Component....

https://facebook.github.io/react-native/docs/image.html

**Comment by gocampos** [comment]
I was stuck at this problem for a while and had success when added the same images of "app/images" directory in the "android/app/src/main/res/drawable-mdpi/" path with the prefix "app_images_". 
So: app/images/test.png was also added at android/app/src/main/res/drawable-mdpi/app_images_test.png and it started to work
