### ISSUE TITLE
Can't use vector drawables for Android

### ISSUE THREAD

**Issue by YoungElPaso** [facebook/react-native#4308]
I'm not sure why this doesn't work, except that the packager doesn't look for *.xml files.  It would be great to have resolution/density independent image support.

**Comment by mkonicek** [comment]
Vector drawables are not supported by the asset system. You'll need to place them into the drawables folder and use them the same way you'd do in any Android app.

**Comment by mkonicek** [comment]
For feature requests, please check out Product Pains: https://productpains.com/product/react-native/?tab=top
It has an awesome feature - people can vote on issues, which makes it clear what what the most impactful things are for the community and what should be worked on. That is something that's very hard to do with Github issues.

If you think that answers this issue please consider closing.

**Comment by mkonicek** [comment]
And thanks for reporting this! It's a good point that people might want to use vector drawables in RN too.

**Comment by YoungElPaso** [comment]
@mkonicek Thanks for the input. I'll check out Product Pains for sure. I guess I should have been more explicit though, because I don't believe that even when in drawables, those will work.  I could do more testing on that however.  Either way, I suppose its a feature request and not a bug.

**Comment by YoungElPaso** [comment]
@mkonicek As you suggested: 

https://productpains.com/post/react-native/vector-drawables-for-icons-in-android/

And I'll close.
