### ISSUE TITLE
[Promises] Make RN Android Promise.reject take an Exception instead of String

### ISSUE THREAD

**Issue by ide** [facebook/react-native#4309]
We can easily go from Exception -> String without loss of info but not the other way. This brings us closer to iOS parity (which takes NSErrors) and will let us surface native stack traces to JS.

cc @davidaurelio @satya164

**Comment by davidaurelio** [comment]
Good idea!

**Comment by mjhlybmwq** [comment]
Can we convert a java object to a WritableMap by reflection?
