### ISSUE TITLE
com.facebook.react.devsupport.LogBoxDialogSurfaceDelegate.hide LogBoxDialogSurfaceDelegate.java, line 85

### ISSUE THREAD

**Issue by Mushthak007** [facebook/react-native#43125]
### Description

android.view.WindowManagerGlobal.findViewLocked WindowManagerGlobal.java:578
android.view.WindowManagerGlobal.removeView WindowManagerGlobal.java:470
android.view.WindowManagerImpl.removeViewImmediate WindowManagerImpl.java:172
android.app.Dialog.dismissDialog Dialog.java:557
android.app.Dialog.dismiss Dialog.java:537
com.facebook.react.devsupport.LogBoxDialogSurfaceDelegate.hide LogBoxDialogSurfaceDelegate.java:85
com.facebook.react.devsupport.LogBoxModule$3.run LogBoxModule.java:78
android.os.Handler.handleCallback Handler.java:888
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:213
android.app.ActivityThread.main ActivityThread.java:8178
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:513
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1101

### Steps to reproduce

issue Android-10

### React Native Version

0.69.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
1
```

### Stacktrace or Logs

```text
1
```

### Reproducer

11

**Comment by cortinico** [comment]
Closing as 0.69 is not supported anymore. Please move to 0.73 and try again. If the issue persists we can look into it
