### ISSUE TITLE
0.15.0 should use `react-haste` instead of `react-tools`

### ISSUE THREAD

**Issue by baoti** [facebook/react-native#4312]
Look in [source of branch 0.15-stable](https://github.com/facebook/react-native/blob/v0.15.0/package.json#L78), it's dependencies doesn't match "React Native now uses React 0.14" in [v0.15.0-rc release note](https://github.com/facebook/react-native/releases/tag/v0.15.0-rc).

@ide @mkonicek

**Comment by ide** [comment]
Thanks for the heads-up. Removed that from the release notes. 0.16-rc is going out tomorrow.
