### ISSUE TITLE
:ReactNative:Running '[node, -e, try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}]' command failed.

### ISSUE THREAD

**Issue by martosdw11** [facebook/react-native#43121]
### Description

can't running app 
:ReactNative:Running '[node, -e, try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}]' command failed.

<img width="825" alt="Screenshot 2024-02-21 at 13 55 42" src="https://github.com/facebook/react-native/assets/45554293/6af3b600-ae8a-49c8-97cb-87ace63029d9">

* What went wrong:
A problem occurred evaluating script.
> Could not find method exec() for arguments [ReactNativeModules$_getCommandOutput_closure16@40814d12] on object of type org.gradle.api.internal.provider.DefaultProviderFactory_Decorated.

### Steps to reproduce

I try reinstall env
https://reactnative.dev/docs/environment-setup.
<img width="1144" alt="Screenshot 2024-02-21 at 14 07 37" src="https://github.com/facebook/react-native/assets/45554293/c34070c7-057d-4e33-813e-b8ead54aee27">

### React Native Version

0.70.8

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 106.28 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    Android SDK:
      API Levels: 23, 28, 29, 30, 33, 33, 34
      Build Tools: 28.0.3, 29.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
      System Images: android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 15.1/15C65 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.8 => 0.70.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method exec() for arguments [ReactNativeModules$_getCommandOutput_closure16@a15bcec] on object of type org.gradle.api.internal.provider.DefaultProviderFactory_Decorated.
```

### Reproducer

none

### Screenshots and Videos

<img width="1302" alt="Screenshot 2024-02-21 at 14 10 31" src="https://github.com/facebook/react-native/assets/45554293/9eac941c-4e6f-466d-8220-4fade1b0ceec">

**Comment by cortinico** [comment]
We can't help without a reproducer sadly + you're on a unsupported version of React Native.

**Comment by martosdw11** [comment]
> 0.70.8



> We can't help without a reproducer sadly + you're on a unsupported version of React Native.

can you tell me, what version does it support? @cortinico

**Comment by cortinico** [comment]
Here they are: https://github.com/reactwg/react-native-releases/#which-versions-are-currently-supported

**Comment by WilliamAstudillo1** [comment]
close android studio and open from terminal with  open -a /Applications/Android\ Studio.app help me

**Comment by talaikis** [comment]
Same for Windows RN 0.74-rc4

**Comment by douglasndm** [comment]
Same problem on Mac M1 RN 0.74.1

> ReactNative:Running '[node, /Users/douglasndm/Documents/Projects/expirychecker/node_modules/@react-native-community/cli/build/bin.js, config]' command failed.

> FAILURE: Build failed with an exception.

> * Where:
Script '/Users/douglasndm/Documents/Projects/expirychecker/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 401

**Comment by the-bao** [comment]
Same problem on Windows RN 0.74.3

> :ReactNative:Running '[node, -e, try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}]' command failed.

> FAILURE: Build failed with an exception.

> * Where:
Script 'node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 397

**Comment by xccjk** [comment]
Same problem

**Comment by m-usman-yousuf** [comment]
facing same problem in RN 0.74. please open the issue

**Comment by Ahmadhamdan47** [comment]
For the ones who are facing this problem with supported versions of React native :
replace in you **AndroidManifest.xm**l:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android>"`

**with:**

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="<your package name>">
`
