### ISSUE TITLE
[0.74.0-rc.0] Specs are generated but not correctly linked to `appmodules`

### ISSUE THREAD

**Issue by tido64** [facebook/react-native#43145]
### Old Version

0.73.0

### New Version

0.74.0-rc.0

### Description

In 0.74.0-rc.0, specs are generated but not correctly linked to `appmodules`:

```
  /~/android/app/build/generated/rncli/src/main/jni/rncli.cpp:10:10: fatal error: 'RNWWebStorageSpec.h' file not found
  #include <RNWWebStorageSpec.h>
           ^~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

Bisecting nightlies, I found that the first build to fail is [0.74.0-nightly-20240220-e9351f0f8](https://www.npmjs.com/package/react-native/v/0.74.0-nightly-20240220-e9351f0f8). The one before that, [0.74.0-nightly-20240219-28da7f9f5](https://www.npmjs.com/package/react-native/v/0.74.0-nightly-20240219-28da7f9f5), builds fine.

### Steps to reproduce

```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.74 -- --core-only
yarn
cd example/android
sed -i '' 's/#newArchEnabled/newArchEnabled/' gradle.properties
./gradlew assembleDebug
```

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
n/a
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

https://github.com/microsoft/react-native-test-app

**Comment by tido64** [comment]
cc @cortinico

**Comment by cortinico** [comment]
Thanks for reporting this @tido64 
Fix is here:
- https://github.com/react-native-community/cli/pull/2306

This requires a bump of the CLI on the 0.74 branch.

BTW for the future:
This:
```
sed -i '' 's/#newArchEnabled/newArchEnabled/' gradle.properties
./gradlew assembleDebug
```

can be just this:
```
./gradlew  assembleDebug -PnewArchEnabled=true
```

**Comment by cortinico** [comment]
Fixed in RC1 👍
