### ISSUE TITLE
[TabBarIOS] Icon doesn't rerender on state change

### ISSUE THREAD

**Issue by kilgoremaskreplica** [facebook/react-native#4314]
An overview: I'm using a conditional statement on the icon prop and title prop of a TabBarIOS item. When  the conditional value changes (through a state update) the title will rerender but not the icon. Is this a known bug? 

I've included an example of the code below. I am updating the state of the TabBar in a seperate function. 

```
<TabBarIOS.Item
    title=""
    selected={this.state.selectedTab === 'pomodoro'}
    icon={this.state.timerActive ? require('image!Play') : require('image!Pause') }
    onPress={() => {
        this.setState({
           selectedTab: 'pomodoro',
        });
    }}>
    <Pomodoro timerActive={this.state.timerActive}/>
</TabBarIOS.Item>

```

**Comment by skevy** [comment]
@kilgoremaskreplica could you throw together a quick example on RNPlay.org for this?

**Comment by kilgoremaskreplica** [comment]
Hey Skevy, thanks for the reply. 

Rnplay doesn't support requiring assets from within the IOS bundle so unfortunately I can't replicate this issue using that site.  

However, after going through the process I have discovered this icon rerendering issue is directly tied to requiring an image from the IOS bundle. For instance this works:

		systemIcon={this.state.timerActive ? 'contacts' : 'bookmarks' }

**Comment by skuridin** [comment]
I think I have related issue.
![ezgif-1802978386](https://cloud.githubusercontent.com/assets/929601/12008977/74d4acb8-ac86-11e5-908b-f70c5ece628e.gif)

```js
export default class TabBarItem extends Component {
  render() {
    let icon = `ios-${this.props.icon}`;

    if (!this.props.selected) icon += '-outline';

    return (
      <Icon.TabBarItem
        iconName={icon}
        title={this.props.title}
        onPress={this.props.select}
        selected={this.props.selected}
      >
        <View></View>
      </Icon.TabBarItem>
    );
  }
}
```

**Comment by christopherdro** [comment]
@kilgoremaskreplica Could you try @skuridin solution and see if that works for you?

**Comment by satya164** [comment]
@facebook-github-bot answered
