### ISSUE TITLE
Hermes experimental debugger does not open on iOS with custom build configurations

### ISSUE THREAD

**Issue by sliptype** [facebook/react-native#43185]
### Description

I have an iOS build configuration `Staging.Debug` that is a copy of `Debug`. The experimental debugger fails to launch when running this build configuration via:
```
react-native start --experimental-debugger
```
and
```
react-native run-ios --mode Staging.Debug
```

Output from metro:

```
info Launching JS debugger (experimental)...
warn No compatible apps connected. JavaScript debugging can only be used with the Hermes engine.
```

I've confirmed that the app is using Hermes:
<img width="380" alt="image" src="https://github.com/facebook/react-native/assets/19916043/48d37af7-18a0-4519-8a0c-26167ee9602b">

The debugger launches properly when doing:
```
react-native run-ios --mode Debug
```

 I did a little digging and see there is a check for the `Debug` configuration [here](https://github.com/facebook/react-native/blob/c7bacf610db1e04ec148a87ae4f1812db2472499/packages/react-native/sdks/hermes-engine/utils/build-apple-framework.sh#L57) and [here](https://github.com/facebook/react-native/blob/c7bacf610db1e04ec148a87ae4f1812db2472499/packages/react-native/sdks/hermes-engine/utils/build-hermes-xcode.sh#L34), but I'm not sure if relevant.

`Staging.Debug` was created by copying `Debug` following [these instructions](https://medium.com/@ywongcode/building-multiple-versions-of-a-react-native-app-4361252ddde5). I would like to debug `Staging.Debug` because I need certain configuration for my staging app.

### Steps to reproduce

1. ```git clone git@github.com:sliptype/RNRepro1.git```
2.  ```yarn i && pod install --project-directory=ios```
3.  ```yarn start```
4.  In another shell ```yarn ios```
5. Launch debug menu with `CMD + D` or **Device > Shake**
6. Press **Open Debugger**

### React Native Version

0.73.4

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 142.52 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.17.0/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/sebastian/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/sebastian/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
info Launching JS debugger (experimental)...
warn No compatible apps connected. JavaScript debugging can only be used with the Hermes engine.
```

### Reproducer

https://github.com/sliptype/RNRepro1

**Comment by truongngodang** [comment]
same issues

**Comment by kmarushchakItomy** [comment]
Also experiencing this.
RN 0.73.5

**Comment by ayoubbahmad** [comment]
Same issues! when I add new schemes with custom build configurations

**Comment by sandeepsuthar** [comment]
Same issue while using custom configuration (Debug-QAT) with custom Scheme (QAT) but it's working as expected with Debug configuration.

**Comment by sternlucas** [comment]
Seme problem here. How can I fix this until the new version is released ?

**Comment by sternlucas** [comment]
Same issue here. How can I fix this until de next version is released ?
