### ISSUE TITLE
Declarative Animation example?  (RCTAnimationManager Scope issue?)

### ISSUE THREAD

**Issue by chadobado** [facebook/react-native#432]
Have been running experiments with React Native's current animation capabilities (LayoutAnimation and the more declarative Animation API).

Using the declarative API I'm attempting a simple animation (scaling a view from an onPress event), informed from the 2048 example:

https://github.com/facebook/react-native/blob/master/Examples/2048/Game2048.js#L80

What I expected to be a trivial test is resulting in:

```
"Cannot read property 'startAnimation' of undefined.

Object.Animation.startAnimation
Animation.js:31
```
https://github.com/facebook/react-native/blob/master/Libraries/Animation/Animation.js#L31
```javascript
//Animation.js:31
var tag: number = RCTAnimationManager.startAnimation(nodeHandle, AnimationUtils.allocateTag(), duration, delay, easingSample, properties);
```
For some reason it appears RCTAnimationManager is not in scope?

Also, assuming a different issue, when I nest TouchableHighlight in a parent View, onPress events no longer fire.

Thanks in advance for any feedback:

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Animation,
  Text,
  TouchableHighlight,
  View,
} = React;

var WebViewApp = React.createClass({

  getInitialState: function() {
    return {}
  },

  _onPress: function() {
    console.log('starting animation');
    Animation.startAnimation(this.refs['this'], 300, 0, 'easeInOutQuad', {scaleXY: [0.5, 0.5]});
  },

  render: function() {
    return (
      
          <TouchableHighlight style={styles.container} onPress={this._onPress}>
            <View>
              <Text style={styles.text}>
                Click here to start animation!
              </Text>
              <View ref='this' style={styles.box}/>
            </View>
          </TouchableHighlight>
      
    );
  }
});

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    top:200,
    width: 200,
    height: 200,
  },
  text: {
    fontSize: 16,
  },
  box:{
    backgroundColor:'red', 
    width: 50, 
    height: 50,
  }
});



AppRegistry.registerComponent('WebViewApp', () => WebViewApp);

```

**Comment by volkanunsal** [comment]
>  <TouchableHighlight style={styles.container} onPress={this._onPress}>

I'm not exactly sure, but passing `_onPress` directly might be changing the context of `this`. Try the fat arrow notation:

>  <TouchableHighlight style={styles.container} onPress={()=>{ this._onPress()} }>

**Comment by chadobado** [comment]
Thanks @volkanunsal for taking a stab at it... after digging further I realized RCTAnimationManager is not linked.  After adding RCTAnimationManager.h and RCTAnimationManager.m (and RCTAnimationManager.xcodeproj to Libraries) everything seems to be working.

**Comment by danielkramer** [comment]
I'm trying to get animation's working as well.  I'm not clear how to link in RCTAnimationManager.xcodeproj.  Any advice? Thanks

**Comment by vjeux** [comment]
Check this guide for how to link libraries http://facebook.github.io/react-native/docs/linking-libraries.html#content
