### ISSUE TITLE
Please publish @react-native/metro-config proper version as latest.

### ISSUE THREAD

**Issue by Romick2005** [facebook/react-native#43208]
### Description

![image](https://github.com/facebook/react-native/assets/17779660/d8bc1dd2-ba62-446f-a771-ba42a806694c)

### Steps to reproduce

npm outdated

### React Native Version

0.73.4

### Affected Platforms

Runtime - Android, Runtime - iOS, Runtime - Web, Runtime - Desktop, Build - MacOS, Build - Windows, Build - Linux, Other (please specify)

### Output of `npx react-native info`

```text
No
```

### Stacktrace or Logs

```text
No
```

### Reproducer

No needed

**Comment by cortinico** [comment]
Fixed 👍
