### ISSUE TITLE
Static Image Resource cannot load in mobile?

### ISSUE THREAD

**Issue by charmingzuo** [facebook/react-native#4321]
the require code

```javascript
// img.js
module.exports = {
    back: require('./back.png'),
    write: require('./write.png'),
    talk: require('./talk.png')
};
```

```javascript
// Toolbar.js
let img = require('../../img/img');
// ...
<ToolbarAndroid navIcon={img.back} />
```

```
|- widget/Toolbar/Toolbar.js
|- img/
   |-img.js
   |-back.png
   |-back@2x.png 
   |-back@3x.png
   |-talk.png
   |-talk@2x.png
   |-talk@3x.png
   |-write.png
   |-write@2x.png
   |-write@3x.png
```

The image working well in my genymotion, but did not visible in my mobile.
So, how does the packager packages "Static Image Resources"? or am I missed some document?

**Comment by christopherdro** [comment]
Did you by any chance create your project with a version before 0.14?

**Comment by miracle2k** [comment]
I had this problem, and yes, my project was old. The trick for me was to add the "assets" folder that is generated by the bundle script to my xcode project _as a folder reference_.

See also https://github.com/facebook/react-native/issues/4084#issuecomment-183753588

**Comment by jsierles** [comment]
@facebook-github-bot answered
