### ISSUE TITLE
[0.74.0-rc.1] Invariant violation when accessing TurboModules

### ISSUE THREAD

**Issue by tido64** [facebook/react-native#43213]
### Old Version

0.73.4

### New Version

0.74.0-rc.1

### Description

If a New Architecture enabled library implements `ReactModuleInfoProvider` using a pattern like below:

```kotlin
    override fun getReactModuleInfoProvider(): ReactModuleInfoProvider = ReactModuleInfoProvider {
        val info = ReactModuleInfo(
            WebStorageModule.NAME,
            WebStorageModule::class.java.name,
            false,
            false,
            false,
            false,
            TurboModule::class.java.isAssignableFrom(WebStorageModule::class.java)  // <-- THIS
        )
        mapOf(info.name() to info).toMutableMap()
    }
```

It will no longer be detected as a TurboModule because `TurboModule::class.java.isAssignableFrom()` will now return `false`. The reason is because the `TurboModule` class used here is no longer the same `TurboModule` class used for the generated spec: https://github.com/facebook/react-native/commit/b7191cde4e36d3d712affc8b714e7d6179642cbb

Quite a number of libraries currently use this pattern: https://github.com/search?q=TurboModule.class.isAssignableFrom&type=code

### Steps to reproduce

```sh
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
npm run set-react-version 0.74 -- --core-only
yarn
cd example
yarn android --extra-params "-PnewArchEnabled=true"

# In a separate terminal
yarn start
```

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

n/a

### Stacktrace or Logs

n/a

### Reproducer

https://github.com/microsoft/react-native-test-app.git

### Screenshots and Videos

n/a

**Comment by tido64** [comment]
cc @cortinico

**Comment by tido64** [comment]
Update: I found that `TurboModule::class.java.isAssignableFrom(WebStorageModule::class.java)` no longer returns `true`. I had to hard-code it to `true`.

It looks like `com.facebook.react.turbomodule.core.interfaces.TurboModule` is now `com.facebook.react.internal.turbomodule.core.interfaces.TurboModule`?

**Comment by cortinico** [comment]
> I found that `TurboModule::class.java.isAssignableFrom(WebStorageModule::class.java)` no longer returns `true`. I had to hardcode it to `true`.

@tido64  Where is this code you're referring? Where have you hardcoded it to true?
I think we can either revert the renaming or update the logic to handle both.

**Comment by tido64** [comment]
> @tido64 Where is this code you're referring? Where have you hardcoded it to true? I think we can either revert the renaming or update the logic to handle both.

Sorry, I meant the native module that we were using to smoke test autolinking. I have a PR to fix it here: https://github.com/microsoft/rnx-kit/pull/2989

**Comment by cortinico** [comment]
@tido64 How about a fix like this one?
- https://github.com/facebook/react-native/pull/43219

**Comment by tido64** [comment]
> @tido64 How about a fix like this one?
> 
> * [Do not use TurboModule.class.isAssignableFrom #43219](https://github.com/facebook/react-native/pull/43219)

I left a comment on the PR.

Slightly off-topic: What will be the replacement for `getReactModuleInfoProvider()`? The deprecation comment in `TurboModule` points to https://github.com/facebook/react-native/pull/41412, but this doesn't give me much details. Are you going to use reflection or something like that?

**Comment by cortinico** [comment]
Practically fixed by https://github.com/facebook/react-native/pull/43219 which will be included in RC2
