### ISSUE TITLE
LogBox.ignoreLog is not ignoring console logs.

### ISSUE THREAD

**Issue by rashmi-priya** [facebook/react-native#43238]
### Description

Hello,

I've been working on an iOS project and have integrated LogBox for debugging purposes. However, I encountered an issue with the ignoreLog API. Despite utilizing the ignoreLog API to suppress certain logs, I've noticed that console.log statements are still appearing in the console.

```
import { AppRegistry, LogBox } from 'react-native';

import { name as appName } from './app.json';

LogBox.ignoreAllLogs();

LogBox.ignoreLogs(['test string']);

console.log('test string');

AppRegistry.registerComponent(appName, () => () => null);
```

### Steps to reproduce

npm run ios

### React Native Version

0.73.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 12.4
  CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Memory: 31.52 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.9.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2022.09.05.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
DriverKit 21.4
iOS 15.5
macOS 12.3
tvOS 15.4
watchOS 8.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 13.4.1/13F100
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.8
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
LOG test string
```

### Reproducer

https://snack.expo.dev/@rp_expo/4ecb88?platform=ios

**Comment by rashmi-priya** [comment]
https://snack.expo.dev/@rp_expo/4ecb88?platform=ios

**Comment by elencho** [comment]
+1

**Comment by psbdgr8** [comment]
+1

**Comment by frankcalise** [comment]
The reproducer you provided doesn't launch correctly, most notably missing `appName`, `app.json` and a default export from `App.js`. Please fix that so we can properly see the issue.

Also, are you saying this experience changed? [LogBox is documented](https://reactnative.dev/docs/debugging#logbox) to be used to ignore either all or specific warnings/errors, not general console.logs

**Comment by cortinico** [comment]
@rashmi-priya can you follow up to what @frankcalise requested?

**Comment by jakex7** [comment]
I believe everything is working as expected. According to the [documentation](https://reactnative.dev/docs/debugging#logbox), `LogBox` is used to hide pop-ups appearing on the app screen, not in the metro console (terminal). Since `console.log` doesn't manifest as an on-screen notification, there's nothing to ignore there.

In other words, even using
```ts
LogBox.ignoreAllLogs(true);
LogBox.ignoreLogs(['test']);
```
and executing `console.error('test')`, the error should still appear in the terminal.

**Comment by rashmi-priya** [comment]
Thanks @jakex7.

**Comment by showtan001** [comment]
+1

**Comment by rickhanlonii** [comment]
This is intentional, see the commit message here: https://github.com/facebook/react-native/commit/fa2842d113f04c8d33d2f71f43d4232e470b77ac
