### ISSUE TITLE
Hermes does not compile for iOS

### ISSUE THREAD

**Issue by CyberMew** [facebook/react-native#43241]
## Bug Description

In Pods: [Hermes] Using the latest commit from main.

Showing Recent Issues
/Users/user/Downloads/AwesomeProject4/node_modules/react-native/ReactCommon/hermes/inspector-modern/InspectorState.cpp:225:40: No member named 'AsyncTrigger' in 'facebook::hermes::debugger::PauseReason'

/Users/user/Downloads/AwesomeProject4/node_modules/react-native/ReactCommon/hermes/inspector-modern/InspectorState.cpp:366:33: No member named 'AsyncTrigger' in 'facebook::hermes::debugger::PauseReason'

Also tried other RN versions https://github.com/facebook/react-native/issues/43082

Sidenote: CMAKE is apparently required but it is not part of any dependencies (something to take note of, otherwise the scripts cannot compile at all and error immediately)

- [x] I have confirmed this bug does not occur with JSC
- [x] The issue is reproducible with the latest version of React Native.

Hermes git revision (if applicable):
React Native version: 0.73.4
OS: macOS Sonama 14.3.1
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): Apple Silicon

## Steps To Reproduce

1. Init a new AwesomeProject for 0.73.4. 
2. Build iOS

code example: NA

## The Expected Behavior

Compiles successfully.

**Comment by cipolleschi** [comment]
Hi @CyberMew, I think that there is something wrong with your setup.
If you are using a stable version of React Native (0.73.4, from the description) you should always use a prebuilt version of Hermes we ship with the framework. The download and all the setup is automatically handled by React Native and the url is here: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.4/

You should never try to use a different version of hermes by tampering with the node_modules and the podspecs because there is no guarantee (yet) that newer versions of Hermes are compatible with older versions of React Native.

@Ann-MarieKemp  You probably has something somewhere else that is setting a global environment variable `BUILD_FROM_SOURCE` to `true` and that is affecting how Hermes is built.

On the React Native side, we can disambiguate that [`BUILD_FROM_SOURCE`](https://github.com/facebook/react-native/blob/main/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L88) env variable with a different one, which is harder to clash with.
Meanwhile, you can workaround install your pods with `BUILD_FROM_SOURCE=false bundle exec pod install` and that should fix the issue.

**Comment by CyberMew** [comment]
Hi @cipolleschi, yes I tried using 0.73.4 with a fresh copy using the standard commands so I don't think it's something to do with my setup (it's a fresh macOS install). No issues when I use my old 0.71.14 project (with Gem/Podfile lock files already working previously). I did not try a fresh copy of 0.71.14 (without the lock files). It seems like there could be some version compatibility? I will delete my lock files and retest to see if it is related to Gem/Podfile and report result.

**Comment by cipolleschi** [comment]
@CyberMew, 0.71 didn't have the `BUILD_FROM_SOURCE` env var switch, so it's expected that it works.

Can you try to:
1. `echo $BUILD_FROM_SOURCE` from a terminal and report what it outputs?
2. run `cd <YourApp>/ios && bundle install && BUILD_FROM_SOURCE=false bunlde exec pod install`?

You should not see the `build hermes from the latest commit on main` message. Instead, you should see something like this:
<img width="1028" alt="Screenshot 2024-02-29 at 11 26 49" src="https://github.com/facebook/react-native/assets/11162307/5b5f0e12-f330-4c3f-a4ea-7b201d1c5a2b">

**Comment by CyberMew** [comment]
@cipolleschi I have done that before and `echo $BUILD_FROM_SOURCE` returns nothing.

Did `npx react-native init AwesomeProject6` from Terminal. 

```
╰─ bundle install && BUILD_FROM_SOURCE=false bundle exec pod install
Bundle complete! 3 Gemfile dependencies, 40 gems now installed.
Bundled gems are installed into `../vendor/bundle`
/Users/user/Downloads/AwesomeProject6/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/core_ext/big_decimal/conversions.rb:3: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.1 to add bigdecimal into its gemspec.
/Users/user/Downloads/AwesomeProject6/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/notifications/fanout.rb:3: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.1 to add mutex_m into its gemspec.
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
/Users/user/.cocoapods/repos-art/cocoapods-remote/.artpodrc
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the latest commit from main.
Const Defined!
/Users/user/.cocoapods/repos-art/cocoapods-remote/.artpodrc
/Users/user/.cocoapods/repos-art/cocoapods-remote/.artpodrc
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.73.5)
Installing FBReactNativeSpec (0.73.5)
Installing Flipper (0.201.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.2.0.1)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.10)
Installing Flipper-Glog (0.5.0.5)
Installing Flipper-PeerTalk (0.0.4)
Installing FlipperKit (0.201.0)
Installing OpenSSL-Universal (1.1.1100)
Installing RCT-Folly (2022.05.16.00)
Installing RCTRequired (0.73.5)
Installing RCTTypeSafety (0.73.5)
Installing React (0.73.5)
Installing React-Codegen (0.73.5)
Installing React-Core (0.73.5)
Installing React-CoreModules (0.73.5)
Installing React-Fabric (0.73.5)
Installing React-FabricImage (0.73.5)
Installing React-ImageManager (0.73.5)
Installing React-Mapbuffer (0.73.5)
Installing React-NativeModulesApple (0.73.5)
Installing React-RCTActionSheet (0.73.5)
Installing React-RCTAnimation (0.73.5)
Installing React-RCTAppDelegate (0.73.5)
Installing React-RCTBlob (0.73.5)
Installing React-RCTFabric (0.73.5)
Installing React-RCTImage (0.73.5)
Installing React-RCTLinking (0.73.5)
Installing React-RCTNetwork (0.73.5)
Installing React-RCTSettings (0.73.5)
Installing React-RCTText (0.73.5)
Installing React-RCTVibration (0.73.5)
Installing React-callinvoker (0.73.5)
Installing React-cxxreact (0.73.5)
Installing React-debug (0.73.5)
Installing React-graphics (0.73.5)
Installing React-hermes (0.73.5)
Installing React-jserrorhandler (0.73.5)
Installing React-jsi (0.73.5)
Installing React-jsiexecutor (0.73.5)
Installing React-jsinspector (0.73.5)
Installing React-logger (0.73.5)
Installing React-nativeconfig (0.73.5)
Installing React-perflogger (0.73.5)
Installing React-rendererdebug (0.73.5)
Installing React-rncore (0.73.5)
Installing React-runtimeexecutor (0.73.5)
Installing React-runtimescheduler (0.73.5)
Installing React-utils (0.73.5)
Installing ReactCommon (0.73.5)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing boost (1.83.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.73.5)
Installing libevent (2.1.12)
Generating Pods project
Setting USE_HERMES build settings
Setting REACT_NATIVE build settings
Setting CLANG_CXX_LANGUAGE_STANDARD to c++20 on /Users/user/Downloads/AwesomeProject6/ios/AwesomeProject6.xcodeproj
Pod install took 972 [s] to run
Integrating client project

[!] Please close any current Xcode sessions and use `AwesomeProject6.xcworkspace` for this project from now on.
/Users/user/.cocoapods/repos-art/cocoapods-remote/.artpodrc
Pod installation complete! There are 73 dependencies from the Podfile and 61 total pods installed.

[!] hermes-engine has added 2 script phases. Please inspect before executing a build. See `https://guides.cocoapods.org/syntax/podspec.html#script_phases` for more information.
```
Seems like something else is wrong such that it is pulling from main. I am using M1 Pro Sonama 14.3.1 (23D60). Is there something I can edit to force it pulling the artifacts directly and not from main?

**Comment by CyberMew** [comment]
@cipolleschi Thank you for the tip. That was the issue. That url is blocked on my machine and to make things worse I am using Artifactory, so on top of changing the URL I also needed to modify the curl command in the code to add `-u user:apikey` for it to return 200 http code.

For some reason previously on 0.71.x it will immediately return a download failure with the url during the `pod install`, so it was evident something broke which is easily fixed when I searched/changed the URL to Artifactory (didn't have to add user:apikey for some reason back then 🤷) and it simply worked.

I think the script should be made more clear to user that the default release artifacts is not accessible (some error code shown), so it is highlighted what happened (i.e. print URL it is grabbing from and also error code) instead of just defaulting to build source from main "silently" (which is not the usual path). Usually we want to lock the version to use a known compatible version and not use the latest code. 

Nonetheless thank you very much for your assistance.

**Comment by Ann-MarieKemp** [comment]
> On the React Native side, we can disambiguate that [`BUILD_FROM_SOURCE`](https://github.com/facebook/react-native/blob/main/packages/react-native/sdks/hermes-engine/hermes-utils.rb#L88) env variable with a different one, which is harder to clash with. Meanwhile, you can workaround install your pods with `BUILD_FROM_SOURCE=false bundle exec pod install` and that should fix the issue.

Thank you for your response on this. We tried this but it turned out our issue was the same as @CyberMew's with the blocked url. That fix resolved our issue.

**Comment by cipolleschi** [comment]
> I think the script should be made more clear to user that the default release artifacts is not accessible (some error code shown), so it is highlighted what happened (i.e. print URL it is grabbing from and also the error code) instead of just defaulting to build source from main "silently" (which is not the usual path). Usually we want to lock the version to use a known compatible version and not use the latest code.

Yes, I completely agree. We can do a better job when reporting the issue.

**Comment by showtan001** [comment]
> @CyberMew, 0.71 didn't have the `BUILD_FROM_SOURCE` env var switch, so it's expected that it works.
> 
> Can you try to:
> 
> 1. `echo $BUILD_FROM_SOURCE` from a terminal and report what it outputs?
> 2. run `cd <YourApp>/ios && bundle install && BUILD_FROM_SOURCE=false bunlde exec pod install`?
> 
> You should not see the `build hermes from the latest commit on main` message. Instead, you should see something like this: <img alt="Screenshot 2024-02-29 at 11 26 49" width="1028" src="https://private-user-images.githubusercontent.com/11162307/308904402-5b5f0e12-f330-4c3f-a4ea-7b201d1c5a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjY3ODUsIm5iZiI6MTcxMDkyNjQ4NSwicGF0aCI6Ii8xMTE2MjMwNy8zMDg5MDQ0MDItNWI1ZjBlMTItZjMzMC00YzNmLWE0ZWEtN2IyMDFkMWM1YTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5MjEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMGQ0MzJlNTgxMjhjYzI0MzllMjJjZTcxZjlhNmQzYTRhZTY0ZjQ2NzAzM2ZlNmFlY2Q2M2IwNDU2MWMzNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.plTDGXlsBfaTwfEo5rcWR1DjCOFYgc_LLz_ZffyJRNQ">
> 
> as you can see from the yellow-ish line, I used 0.73.5, but it should be the same for 0.73.4.

Running error:
![image](https://github.com/facebook/react-native/assets/32892347/9a7b2053-6457-4050-8536-bc6b31f7aba7)
How to solve it?

**Comment by kayakyakr** [comment]
> @cipolleschi Thank you for the tip. That was the issue. That url is blocked on my machine and to make things worse I am using Artifactory, so on top of changing the URL I also needed to modify the curl command in the code to add `-u user:apikey` for it to return 200 http code. I also had to delete the `ios/Pods/hermes-engine` folder in order for it to repull accordingly to the script.

Where did you update the command to hit your internal url? I'm also behind an artifactory, can't find the spot to update.

**Comment by CyberMew** [comment]
> > @cipolleschi Thank you for the tip. That was the issue. That url is blocked on my machine and to make things worse I am using Artifactory, so on top of changing the URL I also needed to modify the curl command in the code to add `-u user:apikey` for it to return 200 http code. I also had to delete the `ios/Pods/hermes-engine` folder in order for it to repull accordingly to the script.
> 
> Where did you update the command to hit your internal url? I'm also behind an artifactory, can't find the spot to update.

Access the node_modules/react-native/sdks/hermes-engine/hermes-utils.rb file. You can search for the maven https path entry and curl entries there. Modify them accordingly so it points to your url instead. For the user/pass, just add it after curl commands for the two instances you will find. Hope that helps!

**Comment by chirag-blueed** [comment]
> 0.73.5

Hi is this resolved yet, i am getting the same issue with the latest React native 0.76.2
