### ISSUE TITLE
TextInput with  prop keyboardtype number-pad doesnt render returnKeyType next?

### ISSUE THREAD

**Issue by arnoldc** [facebook/react-native#43243]
### Description

When using Textinput component with a `keyboardType="number-pad"` and with a `returnKeyType="next"`
The keyboard doesnt render any "next" button

here is a demo below

https://github.com/facebook/react-native/assets/242780/5e782150-318e-4484-9bfe-3f5b61e2e4c9

### Steps to reproduce

1. install a react native version 0.73.4
2. create a basic TextInput component , use similar prop like below

  ```
<TextInput
        style={styles.input}
        onChangeText={() => {}}
        value={}
        placeholder=""
        keyboardType="number-pad"
        returnKeyType="next"
      />
```
      
3. Test it in iOS simulator and ensure that keyboard will show
      
      

### React Native Version

0.73.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
its expo project but i believe this is happening also in bare react native
```

### Stacktrace or Logs

```text
dont have stacktrace
```

### Reproducer

https://snack.expo.dev/@arnoldc/b5f7f2

**Comment by elencho** [comment]
can I work on this issue?

**Comment by elencho** [comment]
https://github.com/facebook/react-native/pull/43362
