### ISSUE TITLE
Hermes Debugger doesn't connect for 0.74 Release Candidate

### ISSUE THREAD

**Issue by lunaleaps** [facebook/react-native#43259]
### Old Version

0.73.x

### New Version

0.74.0-rc.1

### Description

Following the instructions to connect to the Hermes debugger https://reactnative.dev/docs/next/debugging

I expect to see the Hermes target in `chrome://inspect` but I don't.

This happens on both iOS and Android. It also occurs on 0.74.0-rc.0

It does not reproduce on 0.73.x so its a new regression

### Steps to reproduce

1. `npx react-native init Release074 --version 0.74.0-rc.2`
2. Get metro running `yarn start` & built on either iOS or Android
3. Follow instructions for Hermes debugger via https://reactnative.dev/docs/next/debugging by heading to `chrome://inspect` and putting the port forwarding information

I'd expect to see the Hermes target in dev tools, but nothing shows up

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
n/a
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

--

**Comment by motiz88** [comment]
Ack, taking a look.

On my machine, at least for the iOS app, `http://localhost:8081/json` does show the targets, but `chrome://inspect` doesn't - I'm investigating why that could be.

**Comment by motiz88** [comment]
The bug is from https://github.com/facebook/react-native/pull/42590. Manually reverting it fixes the issue for me. I will put up a new diff to fix the original `Content-Length` issue correctly.

**Comment by bhandanyan-nomad** [comment]
Are there any recommendations for investigating inability to connect to hermes debugger on the latest stable version of v0.74? We recently upgraded and no longer can connect but only when running on iOS 🤔
