### ISSUE TITLE
[0.16] Things we should cherry-pick to 0.16

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#4327]
0.16.0-rc has been published to npm. Here are the things we should get into 0.16.0:

  * [x] Make imports work: https://gist.github.com/ehd/49cb2465df9da6b39710, https://github.com/facebook/react-native/commit/ffea7793aff0961ebc22007d650ce36f7c2e61cb
  * [x] Need a fix for Chrome debugging? https://github.com/facebook/react-native/issues/4418. Update: @skevy and @mkonicek can't repro, likely fixed in https://github.com/facebook/react-native/commit/c73809d1169dd28cfce4380710522b9baab8beed
  * [ ] Add the Android Dialog module
  * [x] Add the Android Pull-to-refresh view: 37f81341a006458d84d934882485c2a0a8838497 (originally `PullToRefreshLayoutAndroid`, renamed in cad4686)
  * [ ] Add Android WebView
  * [x] Android view shadows: https://github.com/facebook/react-native/commit/b65f1f223488b52963f80a67bb41956103263d27
  * [ ] If there's bandwidth: Exporting default class that extends a base class won't work due to Babel's [T2694](https://phabricator.babeljs.io/T2694)
  * [x] Potentially "Update touch handling to properly handle transformed Views": https://github.com/facebook/react-native/commit/c929e15523c2c33297b1e9895e9bea49442e4f73
  * [x] For-of support: https://github.com/facebook/react-native/commit/5dc40afbf681839947cbab691a9f4d2d1ccb7bc0
  * [x] Support for ES6 modules in Babel plugins https://github.com/facebook/react-native/commit/dff8f53664009f49756c79f5f7c4982eaa39a5c3

We should eventually also figure out what's up with `react-native bundle`: https://github.com/facebook/react-native/issues/3948 (have little context). Update, fixed in 0.16.0-rc in 9a64f17. Thank you @ide!

**Comment by skevy** [comment]
@mkonicek where was the regression on the imports issue?

**Comment by mkonicek** [comment]
@skevy It was somewhere in the big upgrade to Babel 6. Added a note here: https://github.com/facebook/react-native/blob/master/breaking-changes.md

**Comment by ide** [comment]
We should also put out a warning about decorators if Babel support doesn't land in time. Any project with decorators in babelrc must wait for https://phabricator.babeljs.io/T2645 before upgrading to 0.16.

**Comment by skevy** [comment]
@ide :+1: I use decorators _everywhere_...as do you I think :)

**Comment by mkonicek** [comment]
Good point about decorators! Updated https://github.com/facebook/react-native/blob/master/breaking-changes.md

**Comment by satya164** [comment]
I had to migrate my projects to move away from decorators. I love decorators, but there is this bug with Babel 6, and Flow doesn't support decorators either :(

**Comment by satya164** [comment]
We should also cherry-pick this - #4298

It's a faitrly small fix for the annoyance where the Switch gets cut off in Android.

**Comment by dlindahl** [comment]
Adding a note about the `babelHelpers.interopRequireDefault is not a function` error being caused by "Make imports work" because it is nearly impossible to discover this issue through a GitHub search or Googling it. I only [found this due to a Twitter search](https://twitter.com/void_0/status/669155663835213824) of all places.

**Comment by satya164** [comment]
@dlindahl That commit fixes the issue, not cause it.

**Comment by dlindahl** [comment]
@satya164 :+1: My comment is just a bit of SEO so that others can find this issue if they encounter the `babelHelpers.interopRequireDefault is not a function` error like I did.

**Comment by satya164** [comment]
@dlindahl Nice. The wording can confuse them though. Would be great if you can reword it.

**Comment by dlindahl** [comment]
Re-word my [comment](https://github.com/facebook/react-native/issues/4327#issuecomment-160224557)?

**Comment by satya164** [comment]
@dlindahl Yeah, to make ti clear that that commit fixes the issue.

**Comment by skevy** [comment]
@mkonicek looks like [#T2694](https://phabricator.babeljs.io/T2694) is fixed in Babel.

**Comment by 362228416** [comment]
I also encountered such a problem, how to solve

**Comment by satya164** [comment]
We should also cherry pick https://github.com/facebook/react-native/commit/c929e15523c2c33297b1e9895e9bea49442e4f73

**Comment by mkonicek** [comment]
@satya164 Added it to the summary above.

**Comment by mkonicek** [comment]
Has anyone else see Chrome debugging not working? Just tried and works for me in 0.16.0-rc: https://github.com/facebook/react-native/issues/4418

**Comment by satya164** [comment]
@mkonicek Thanks :D

**Comment by mkonicek** [comment]
0.16 is out, closing.

**Comment by mkonicek** [comment]
Working on Dialogs.

**Comment by skevy** [comment]
Question, on Babel's issue tracker, [T2694](https://phabricator.babeljs.io/T2694) is closed. Looks like it was release in Babel 6.2.2.

I noticed that it wasn't checked off here...was it not fixed?

**Comment by aleki** [comment]
Android WebView?
