### ISSUE TITLE
Overheating issue observed in iOS 17 and above

### ISSUE THREAD

**Issue by kolindalanaresh** [facebook/react-native#43284]
### Description

I hope this message finds you well. We're currently experiencing a concerning issue with our application on iOS 17 and above, specifically related to overheating.  Kindly suggest us is this related to OS issue or react native framework issue as we are unable to observe overheating issue in android.

React-Native version: 0.72.0

### Steps to reproduce

This issue when bottom tab bar navigation is happened.

### React Native Version

0.72.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.6.3
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 52.60 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.0
    path: ~/.nvm/versions/node/v18.12.0/bin/node
  Yarn: Not Found
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.0/bin/npm
  Watchman:
    version: 2023.05.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0
    wanted: ^0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
```

### Stacktrace or Logs

```text
My bug is not a crash.
```

### Reproducer

https://github.com

**Comment by NickGerleman** [comment]
This issue has no useful information to diagnose, or a reason why we think this is a React Native bug. Please create a new issue following the template, if you have useful information to share.
