### ISSUE TITLE
Text truncation for front or middle of string

### ISSUE THREAD

**Issue by bvogelzang** [facebook/react-native#4329]
I realize the `numberOfLines` prop on the `Text` component can be used to effectively truncate the tail of strings if they are too long. What I'm requesting is that we have the option to truncate the middle or front of the string if needed. Something equivalent to the `NSLineBreakByTruncatingHead` and `NSLineBreakByTruncatingMiddle` options in iOS. Adding a new prop such as `truncatePosition` would be a great addition in my book. Thanks!

```javascript
<Text numberOfLines={1} truncatePosition="middle">Long Text</Text>
```

**Comment by mkonicek** [comment]
Hey @bvogelzang, we're a small team and rely on the community to fix bugs that don't affect fb apps. If you know this is a bug please consider sending a pull request with a fix.

**Comment by mkonicek** [comment]
@facebook-github-bot answered
