### ISSUE TITLE
network request failed when fetch in release build

### ISSUE THREAD

**Issue by avikbox** [facebook/react-native#43302]
### Description

in dev mode everything works fine, all network requests work. but when I build the release, network requests from the application don't fire at all. I tried it on version 73.4 and recreated the application on version 73.5, the result was the same.

### Steps to reproduce

I just install the release apk
[package.json](https://github.com/facebook/react-native/files/14474527/package.json)
 build on the device

### React Native Version

0.73.4 and 0.73.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3
  CPU: (8) arm64 Apple M1 Pro
  Memory: 93.78 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.3.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/vik/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-31 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/vik/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
no Stacktrace
```

### Reproducer

no repo

**Comment by AutumnWithJay** [comment]
Same in 0.71.17
The above behavior occurs on Android API LEVEL 23 and does not occur on newer API Levels

**Comment by avikbox** [comment]
> Same in 0.71.17 The above behavior occurs on Android API LEVEL 23 and does not occur on newer API Levels

I raised the minimum version to 24, still the same.
installed the react-native-network-logger package, in dev mode it shows all network requests. in the release build it doesn’t show anything, requests don’t go through

**Comment by avikbox** [comment]
> Can we get a repro of any sort?

I found the reason. Before the network call, I used console.dir(), it stopped working and all the code that followed it stopped working. This only appeared in the release build.

**Comment by cortinico** [comment]
> I found the reason. Before the network call, I used console.dir(), it stopped working and all the code that followed it stopped working. This only appeared in the release build.

Still this is not a repro

**Comment by avikbox** [comment]
> > I found the reason. Before the network call, I used console.dir(), it stopped working and all the code that followed it stopped working. This only appeared in the release build.
> 
> Still this is not a repro

Sorry, it's a commercial product and it doesn't have a repository.
