### ISSUE TITLE
want java file instead of kotlin version@0.73.5

### ISSUE THREAD

**Issue by ramanguptazelhus** [facebook/react-native#43306]
### Description

please whenever I create a react-native app, most of my files are in Kotlin e.g. MainActivity.kt, please is there a way to make my default files in Java?
version - 0.73.5

### Steps to reproduce

1. Install the app with npm i 

### React Native Version

0.73.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22621
  CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Memory: 8.68 GB / 19.89 GB
Binaries:
  Node:
    version: 18.13.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 8.19.3
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 18.0.2.1
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
How can I get MainApplication.java and MainActivity.java file instead of Kotlin file extension in the latest version -- 0.73.5
```

### Reproducer

https://github.com/ramanguptazelhus

**Comment by cortinico** [comment]
> please is there a way to make my default files in Java?

You can just rename the files from `.kt` to `.java` and undo the conversion.
You can use those two files as reference:
https://github.com/facebook/react-native/tree/0.72-stable/packages/react-native/template/android/app/src/main/java/com/helloworld

**Comment by SWARAJSINGH211** [comment]
having problems with build.gradle during building and was not able to fix them is there not a default argument to have files in java. would really love that!

**Comment by skizzo** [comment]
> > please is there a way to make my default files in Java?
> 
> You can just rename the files from `.kt` to `.java` and undo the conversion. You can use those two files as reference: https://github.com/facebook/react-native/tree/0.72-stable/packages/react-native/template/android/app/src/main/java/com/helloworld

This doesn't work at all, also I'm wondering why this issue is closed.

@ramanguptazelhus did you find a way to revert to Java after all?

**Comment by maaz-msf** [comment]
React Native community appears to have a template that still uses Java as the basis of the Android side. You can use it in a new project like so:

npx react-native init MyApp --template react-native-template-typescript@6.12.10

I would suggest just creating a second project and copy-pasting the Android contents of that project into your actual one.

That said, I think it is worth noting that Kotlin is fully compatible with Java, and that Kotlin is the preferred basis for Android projects these days. It would be worthwhile becoming familiar with the language.

**Comment by gogHeroDream** [comment]
I tried to change the next file，but i do not know it is right or wrong! 
// MainActivity.java
package com.awesomeproject;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is
   * used to schedule
   * rendering of the component.
   */
  @Override
  public String getMainComponentName() {
    return "AwesomeProject";
  }

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use
   * [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags
   * [fabricEnabled]
   */
  @Override
  public ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(this, getMainComponentName(),
        DefaultNewArchitectureEntryPoint.getFabricEnabled());
  }
}
// MainApplication.java
package com.awesomeproject;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactHost;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactHost;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(this) {
    @Override
    public List<ReactPackage> getPackages() {
      PackageList packageList = new PackageList(this);
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packageList.add(new MyReactNativePackage());
      return packageList.getPackages();
    }

    @Override
    public String getJSMainModuleName() {
      return "index";
    }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    public boolean isNewArchEnabled() {
      return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
    }

    @Override
    public Boolean isHermesEnabled() {
      return BuildConfig.IS_HERMES_ENABLED;
    }
  };

  @Override
  public ReactHost getReactHost() {
    return DefaultReactHost.getDefaultReactHost(getApplicationContext(), mReactNativeHost);
  }

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, false);
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    // ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
}

**Comment by maaz-msf** [comment]
> I tried to change the next file，but i do not know it is right or wrong! // MainActivity.java package com.awesomeproject;
> 
> import com.facebook.react.ReactActivity; import com.facebook.react.ReactActivityDelegate; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactActivityDelegate;
> 
> public class MainActivity extends ReactActivity {
> 
> /**
> 
> * Returns the name of the main component registered from JavaScript. This is
> * used to schedule
> * rendering of the component.
>   */
>   @OverRide
>   public String getMainComponentName() {
>   return "AwesomeProject";
>   }
> 
> /**
> 
> * Returns the instance of the [ReactActivityDelegate]. We use
> * [DefaultReactActivityDelegate]
> * which allows you to enable New Architecture with a single boolean flags
> * [fabricEnabled]
>   */
>   @OverRide
>   public ReactActivityDelegate createReactActivityDelegate() {
>   return new DefaultReactActivityDelegate(this, getMainComponentName(),
>   DefaultNewArchitectureEntryPoint.getFabricEnabled());
>   }
>   }
>   // MainApplication.java
>   package com.awesomeproject;
> 
> import android.app.Application; import com.facebook.react.PackageList; import com.facebook.react.ReactApplication; import com.facebook.react.ReactHost; import com.facebook.react.ReactNativeHost; import com.facebook.react.ReactPackage; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactHost; import com.facebook.react.defaults.DefaultReactNativeHost; import com.facebook.soloader.SoLoader; import java.util.List;
> 
> public class MainApplication extends Application implements ReactApplication {
> 
> private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(this) { @OverRide public List getPackages() { PackageList packageList = new PackageList(this); // Packages that cannot be autolinked yet can be added manually here, for example: // packageList.add(new MyReactNativePackage()); return packageList.getPackages(); }
> 
> ```
> @Override
> public String getJSMainModuleName() {
>   return "index";
> }
> 
> @Override
> public boolean getUseDeveloperSupport() {
>   return BuildConfig.DEBUG;
> }
> 
> @Override
> public boolean isNewArchEnabled() {
>   return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
> }
> 
> @Override
> public Boolean isHermesEnabled() {
>   return BuildConfig.IS_HERMES_ENABLED;
> }
> ```
> 
> };
> 
> @OverRide public ReactHost getReactHost() { return DefaultReactHost.getDefaultReactHost(getApplicationContext(), mReactNativeHost); }
> 
> @OverRide public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
> 
> @OverRide public void onCreate() { super.onCreate(); SoLoader.init(this, false); if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) { // If you opted-in for the New Architecture, we load the native entry point for this app. DefaultNewArchitectureEntryPoint.load(); } // ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); } }

what you are trying to acheive tell me ? i will let you know the solution ?

**Comment by gogHeroDream** [comment]
> the

I just don't want to develop with Kotlin. Want to use Java instead.

**Comment by gogHeroDream** [comment]
> > I tried to change the next file，but i do not know it is right or wrong! // MainActivity.java package com.awesomeproject;
> > import com.facebook.react.ReactActivity; import com.facebook.react.ReactActivityDelegate; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactActivityDelegate;
> > public class MainActivity extends ReactActivity {
> > /**
> > 
> > * Returns the name of the main component registered from JavaScript. This is
> > * used to schedule
> > * rendering of the component.
> >   */
> >   @OverRide
> >   public String getMainComponentName() {
> >   return "AwesomeProject";
> >   }
> > 
> > /**
> > 
> > * Returns the instance of the [ReactActivityDelegate]. We use
> > * [DefaultReactActivityDelegate]
> > * which allows you to enable New Architecture with a single boolean flags
> > * [fabricEnabled]
> >   */
> >   @OverRide
> >   public ReactActivityDelegate createReactActivityDelegate() {
> >   return new DefaultReactActivityDelegate(this, getMainComponentName(),
> >   DefaultNewArchitectureEntryPoint.getFabricEnabled());
> >   }
> >   }
> >   // MainApplication.java
> >   package com.awesomeproject;
> > 
> > import android.app.Application; import com.facebook.react.PackageList; import com.facebook.react.ReactApplication; import com.facebook.react.ReactHost; import com.facebook.react.ReactNativeHost; import com.facebook.react.ReactPackage; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactHost; import com.facebook.react.defaults.DefaultReactNativeHost; import com.facebook.soloader.SoLoader; import java.util.List;
> > public class MainApplication extends Application implements ReactApplication {
> > private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(this) { @OverRide public List getPackages() { PackageList packageList = new PackageList(this); // Packages that cannot be autolinked yet can be added manually here, for example: // packageList.add(new MyReactNativePackage()); return packageList.getPackages(); }
> > ```
> > @Override
> > public String getJSMainModuleName() {
> >   return "index";
> > }
> > 
> > @Override
> > public boolean getUseDeveloperSupport() {
> >   return BuildConfig.DEBUG;
> > }
> > 
> > @Override
> > public boolean isNewArchEnabled() {
> >   return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
> > }
> > 
> > @Override
> > public Boolean isHermesEnabled() {
> >   return BuildConfig.IS_HERMES_ENABLED;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > };
> > @OverRide public ReactHost getReactHost() { return DefaultReactHost.getDefaultReactHost(getApplicationContext(), mReactNativeHost); }
> > @OverRide public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
> > @OverRide public void onCreate() { super.onCreate(); SoLoader.init(this, false); if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) { // If you opted-in for the New Architecture, we load the native entry point for this app. DefaultNewArchitectureEntryPoint.load(); } // ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); } }
> 
> what you are trying to acheive tell me ? i will let you know the solution ?

I just don't want to develop with Kotlin. Want to use Java instead.

**Comment by maaz-msf** [comment]
> > > I tried to change the next file，but i do not know it is right or wrong! // MainActivity.java package com.awesomeproject;
> > > import com.facebook.react.ReactActivity; import com.facebook.react.ReactActivityDelegate; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactActivityDelegate;
> > > public class MainActivity extends ReactActivity {
> > > /**
> > > 
> > > * Returns the name of the main component registered from JavaScript. This is
> > > * used to schedule
> > > * rendering of the component.
> > >   */
> > >   @OverRide
> > >   public String getMainComponentName() {
> > >   return "AwesomeProject";
> > >   }
> > > 
> > > /**
> > > 
> > > * Returns the instance of the [ReactActivityDelegate]. We use
> > > * [DefaultReactActivityDelegate]
> > > * which allows you to enable New Architecture with a single boolean flags
> > > * [fabricEnabled]
> > >   */
> > >   @OverRide
> > >   public ReactActivityDelegate createReactActivityDelegate() {
> > >   return new DefaultReactActivityDelegate(this, getMainComponentName(),
> > >   DefaultNewArchitectureEntryPoint.getFabricEnabled());
> > >   }
> > >   }
> > >   // MainApplication.java
> > >   package com.awesomeproject;
> > > 
> > > import android.app.Application; import com.facebook.react.PackageList; import com.facebook.react.ReactApplication; import com.facebook.react.ReactHost; import com.facebook.react.ReactNativeHost; import com.facebook.react.ReactPackage; import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint; import com.facebook.react.defaults.DefaultReactHost; import com.facebook.react.defaults.DefaultReactNativeHost; import com.facebook.soloader.SoLoader; import java.util.List;
> > > public class MainApplication extends Application implements ReactApplication {
> > > private final ReactNativeHost mReactNativeHost = new DefaultReactNativeHost(this) { @OverRide public List getPackages() { PackageList packageList = new PackageList(this); // Packages that cannot be autolinked yet can be added manually here, for example: // packageList.add(new MyReactNativePackage()); return packageList.getPackages(); }
> > > ```
> > > @Override
> > > public String getJSMainModuleName() {
> > >   return "index";
> > > }
> > > 
> > > @Override
> > > public boolean getUseDeveloperSupport() {
> > >   return BuildConfig.DEBUG;
> > > }
> > > 
> > > @Override
> > > public boolean isNewArchEnabled() {
> > >   return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
> > > }
> > > 
> > > @Override
> > > public Boolean isHermesEnabled() {
> > >   return BuildConfig.IS_HERMES_ENABLED;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > };
> > > @OverRide public ReactHost getReactHost() { return DefaultReactHost.getDefaultReactHost(getApplicationContext(), mReactNativeHost); }
> > > @OverRide public ReactNativeHost getReactNativeHost() { return mReactNativeHost; }
> > > @OverRide public void onCreate() { super.onCreate(); SoLoader.init(this, false); if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) { // If you opted-in for the New Architecture, we load the native entry point for this app. DefaultNewArchitectureEntryPoint.load(); } // ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); } }
> > 
> > 
> > what you are trying to acheive tell me ? i will let you know the solution ?
> 
> I just don't want to develop with Kotlin. Want to use Java instead.





Then use this command for Java version of android

npx react-native init AwesomeProject --version 0.63.4
