### ISSUE TITLE
C++17 function cannot be found by dependency with React Native 0.73.5 on Android

### ISSUE THREAD

**Issue by milanpro** [facebook/react-native#43308]
### Description

When adding the following dependency https://github.com/Governikus/AusweisApp (com.governikus:ausweisapp:2.1.0) to the Android App and starting it in the onCreate method I get the following crash:

```
FATAL EXCEPTION: qtMainLoopThread
 Process: com.aa2test2:ausweisapp2_service, PID: 9904
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVNSt6__ndk13pmr25monotonic_buffer_resourceE" referenced by "/data/app/~~C4l_mRmUqYPFB7K9Bn86PA==/com.aa2test2-k8yOUFZGiJUstsUM1QUl1A==/lib/arm64/libQt6Core_arm64-v8a.so"...
 at java.lang.Runtime.load0(Runtime.java:929)
 at java.lang.System.load(System.java:1625)
 at org.qtproject.qt.android.QtNative$2.run(QtNative.java:235)
 at org.qtproject.qt.android.QtThread$2.run(QtThread.java:51)
 at org.qtproject.qt.android.QtThread$1.run(QtThread.java:25)
 at java.lang.Thread.run(Thread.java:1012)
```

As std::pmr::monotonic_buffer_resource is a C++17 function this looks like an issue with the libc++ version included in the React Native build even though the NDK version is set to "25.1.8937393"

### Steps to reproduce

1. Build and start Android app which should instantly crash with the above mentioned stacktrace

### React Native Version

0.73.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 83.89 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: /var/folders/yz/hyjkcq2d59s5bscn9zms73jm0000gn/T/yarn--1709557513841-0.23140906385048532/node
  Yarn:
    version: 1.22.19
    path: /var/folders/yz/hyjkcq2d59s5bscn9zms73jm0000gn/T/yarn--1709557513841-0.23140906385048532/yarn
  npm:
    version: 10.4.0
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.1.1
    path: /Users/I500763/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
FATAL EXCEPTION: qtMainLoopThread
 Process: com.aa2test2:ausweisapp2_service, PID: 9904
 java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZTVNSt6__ndk13pmr25monotonic_buffer_resourceE" referenced by "/data/app/~~C4l_mRmUqYPFB7K9Bn86PA==/com.aa2test2-k8yOUFZGiJUstsUM1QUl1A==/lib/arm64/libQt6Core_arm64-v8a.so"...
 at java.lang.Runtime.load0(Runtime.java:929)
 at java.lang.System.load(System.java:1625)
 at org.qtproject.qt.android.QtNative$2.run(QtNative.java:235)
 at org.qtproject.qt.android.QtThread$2.run(QtThread.java:51)
 at org.qtproject.qt.android.QtThread$1.run(QtThread.java:25)
 at java.lang.Thread.run(Thread.java:1012)
```

### Reproducer

https://github.com/milanpro/AA2_issue_reproducer

**Comment by NickGerleman** [comment]
> As std::pmr::monotonic_buffer_resource is a C++17 function this looks like an issue with the libc++ version included in the React Native build even though the NDK version is set to "25.1.8937393"

React Native 0.73 uses NDK 26 (though we distribute our native binaries as prefabs), and use some new features from C++ 20. This is not an issue of the NDK not being new enough, and we build with libc++ from LLVM 17, which is very recent.

I don't think our team can help with a QT build outside of React Native that is not related to our build.

**Comment by milanpro** [comment]
> @milanpro have you found any fix related to the issue? I am also running into this problem on a native Android application - the trace is similar to yours.

Sadly no. This issue occurs with AusweisApp SDK Version 2.0 and higher and needs to be fixed by Governikus, the developer of the AusweisApp SDK.

**Comment by I557816-SB** [comment]
Hi This Issue is still persisting with AusweisApp 2.2.2 (https://github.com/Governikus/AusweisApp/releases/tag/2.2.2)

**Comment by sb049** [comment]
Hi This Issue is still persisting with AusweisApp 2.2.2 (https://github.com/Governikus/AusweisApp/releases/tag/2.2.2)

**Comment by paulinabls** [comment]
Same for us with Ausweis SDK 2.2.2 , we tried to define NDK version explicitly in `app:` `build.gradle` ,
 (tried "27.1.12297006", "25.1.8937393" ,"26.1.10909125") and nothing works. We're stuck with Ausweis SDK pre 2.0 :|

**Comment by misery** [comment]
> ### Reproducer
> 
> https://github.com/milanpro/AA2_issue_reproducer
> ### Screenshots and Videos

I tried your example. After the build the APK uses `libc++_shared.so` with 1 MB. It looks like it uses the library from NDK 25 as the library is 1,3 MB since NDK 26. The `libc++_shared.so` from AusweisApp AAR is 1,3 MB. So your build uses and outdated library. Please use the library from the AAR or from NDK 26/27.
Looks like ndkVersion in build.gradle as no effect here.
