### ISSUE TITLE
lineHeight as multiplier

### ISSUE THREAD

**Issue by alfrednerstu** [facebook/react-native#4331]
As React Native uses lineHeight unit-less it makes much more sense and would also be more flexible if it worked like CSS unit-less line-height ie that it's a multiplier of the font size.

That would enable you to set a common line height for several different sizes without needing to recalculate and it would also work well with text that changes in size dynamically.

Thanks!

**Comment by jalooc** [comment]
@alfrednerstu why have you closed this issue? I like your idea.
