### ISSUE TITLE
cassert.h, iosfwd.h and memory.h file not found

### ISSUE THREAD

**Issue by balsikandar** [facebook/react-native#43319]
### Description

After successfully running yarn install and  RCT_NEW_ARCH_ENABLED = 1 pod install command. When i try to run the project from Xcode. I get that cassert.h not found, iosfwd.h file not found and memory file not found. I'm trying to enable New arch on existing project and yarn install and let me clarify again RCT_NEW_ARCH_ENABLED=1 works fine but when i try to install the build on device i encounter this issue

What i have tried so far?
- I have tried to build a new Sample project with all the dependencies i have and it worked when i was targeting 0.72 post 0.72 in the sample project now i get error in react-native-webview.
- I have also been successfull in running the build without Reanimated library and i can't remove it since its widely used in the project. Any suggestions will be helpful.
- One more thing npm i fails so i have been using yarn install

### Steps to reproduce

Well, I have mentioned above that this issue is happening for existing project and not for new projects so Steps are very simple.

- After npm i and RCT_NEW_ARCH_ENABLED = 1 pod install
- When i try to build from Xcode it fails. 
- yarn ios command also doesn't work but this could be metro being removed i believe

### React Native Version

0.73.5

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer, Other (please specify)

### Output of `npx react-native info`

```text
System:
OS: macOS 13.5.2
CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Memory: 469.99 MB / 16.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 18.19.0
path: ~/.nvm/versions/node/v18.19.0/bin/node
Yarn:
version: 1.22.19
path: ~/node_modules/.bin/yarn
npm:
version: 10.2.3
path: ~/.nvm/versions/node/v18.19.0/bin/npm
Watchman: Not Found
Managers:
CocoaPods:
version: 1.14.3
path: /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.2
- iOS 17.2
- macOS 14.2
- tvOS 17.2
- visionOS 1.0
- watchOS 10.2
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode:
version: 15.2/15C500b
path: /usr/bin/xcodebuild
Languages:
Java:
version: 11.0.11
path: /usr/bin/javac
Ruby:
version: 3.1.3
path: /Users/zupee/.rbenv/shims/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.73.5
wanted: ^0.73.0
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: false
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: true
```

### Stacktrace or Logs

```text
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/ludoios/AppDelegate.m:14:
/Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/RNCPushNotificationIOS/RNCPushNotificationIOS.h:18:46: warning: 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings [-Wdeprecated-declarations]
+ (void)didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings;
                                             ^
In module 'UIKit' imported from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/React-Core/React/RCTJavaScriptLoader.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been explicitly marked deprecated here
@interface UIUserNotificationSettings : NSObject
           ^
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/ludoios/AppDelegate.m:14:
/Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/RNCPushNotificationIOS/RNCPushNotificationIOS.h:22:38: warning: 'UILocalNotification' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationRequest [-Wdeprecated-declarations]
+ (void)didReceiveLocalNotification:(UILocalNotification *)notification;
                                     ^
In module 'UIKit' imported from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/React-Core/React/RCTJavaScriptLoader.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UILocalNotification.h:18:12: note: 'UILocalNotification' has been explicitly marked deprecated here
@interface UILocalNotification : NSObject<NSCopying, NSCoding>
           ^
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/ludoios/AppDelegate.m:44:
/Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Private/React-Core/React/RCTCxxBridgeDelegate.h:8:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
While building module 'glog' imported from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/React-debug/react/debug/react_native_assert.h:52:
In file included from <module-includes>:1:
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/glog/glog-umbrella.h:13:
/Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/glog/glog/logging.h:42:10: fatal error: 'iosfwd' file not found
#include <iosfwd>
         ^~~~~~~~
1 error generated.
While building module 'ReactCommon' imported from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/React-NativeModulesApple/ReactCommon/RCTTurboModuleManager.h:17:
In file included from <module-includes>:1:
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/ReactCommon/ReactCommon-umbrella.h:13:
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/ReactCommon/react/bridging/Array.h:10:
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/ReactCommon/react/bridging/Base.h:10:
In file included from /Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/ReactCommon/react/bridging/Convert.h:10:
/Users/zupee/Desktop/zupee/ludo-native/ios/Pods/Headers/Public/React-jsi/jsi/jsi.h:10:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
2 warnings and 3 errors generated.
```

### Reproducer

NA

### Screenshots and Videos

<img width="1752" alt="Screenshot 2024-03-05 at 11 08 15 AM" src="https://github.com/facebook/react-native/assets/13173447/f66ac931-6fb6-4566-bcfd-88b4dae1b863">

**Comment by cortinico** [comment]
Is this happening only if you enable the New Architecture? What happens if you disable it? @balsikandar

**Comment by balsikandar** [comment]
Yes @cortinico, when NewaArch is disabled there's no build problem.

**Comment by cortinico** [comment]
Could you share a reproducer?

**Comment by balsikandar** [comment]
Sure @cortinico I'll try but right now I'm trying to fix it. Once I get time I'll do it.

**Comment by vonovak** [comment]
This happened to me because of a `.m` file in the project. It was compiled as objective C. Changing the extension to `.mm` should move you further.

**Comment by vonovak** [comment]
It was while I was working on rn Google sign in. 

https://github.com/react-native-google-signin/google-signin/blob/v11.0.0/ios/RNGoogleSigninButtonManager.m

**Comment by cortinico** [comment]
> Sure @cortinico I'll try but right now I'm trying to fix it. Once I get time I'll do it.

Closing as no reproducer was provided. @balsikandar do you still have this problem? If so let's re-open and add a reproducer otherwise is not actionable for us.

**Comment by oliviermartin** [comment]
Hi @cortinico , this issue seems to be reproducable when a non `*.mm` file is present in the ìos`directory.

@balsikandar had the file `ios/ludoios/AppDelegate.m` and @vonovak mentioned the file `[ios/RNGoogleSigninButtonManager.m](https://github.com/react-native-google-signin/google-signin/blob/v11.0.0/ios/RNGoogleSigninButtonManager.m)`

In my case I was trying to add a `Calculator.swift` in the example from this page https://github.com/reactwg/react-native-new-architecture/blob/main/docs/turbo-modules.md and I had the same error.

Here is my setup:

```
% npx react-native info
info Fetching system and libraries information...
(node:92531) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.2.1
  CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Memory: 40.57 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/opt/ruby/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

Note: I am aware I will still need the Objective-C++ to bridge with Javascript and Swift.

**Comment by oliviermartin** [comment]
Modifying the example from https://github.com/reactwg/react-native-new-architecture/blob/main/docs/turbo-modules.md#write-the-native-ios-code

From:

```
#import <RTNCalculatorSpec/RTNCalculatorSpec.h>

NS_ASSUME_NONNULL_BEGIN

@interface RTNCalculator : NSObject <NativeCalculatorSpec>

@end

NS_ASSUME_NONNULL_END
```

to:

```
#ifdef RCT_NEW_ARCH_ENABLED
#import <RTNCalculatorSpec/RTNCalculatorSpec.h>

NS_ASSUME_NONNULL_BEGIN

@interface RTNCalculator : NSObject <NativeCalculatorSpec>

@end

NS_ASSUME_NONNULL_END
#endif
```

`RCT_NEW_ARCH_ENABLED` seems to only be passed to C++ and Object-C++. It skips this content for Swift (and I guess Object-C).

**Comment by zoontek** [comment]
Everyone here: Be sure that your `AppDelegate.mm` [correctly compile as ObjC++](https://github.com/zoontek/react-native-bootsplash/discussions/657#discussioncomment-11417484)

**Comment by vpetrykov** [comment]
> This happened to me because of a .m file in the project. It was compiled as objective C. Changing the extension to .mm should move you further.
That being said, I got this error after upgrading to RN 74.rc-5. It wasn't present before.

@vonovak you saved me lots of time debuggin, I had an issue with AsyncStorage’s generated code imports C++ STL headers like `<optional>` and `<utility>`, which a pure Objective-C compiler (.m) doesn’t recognize and therefore errors out as “file not found.” Tried renamin to .mm, the compiler enabled C++17/20 standard library alongside Obj-C, so the STL headers become valid and the build succeeds 🎊
