### ISSUE TITLE
'folly/portability/Config.h' file not found

### ISSUE THREAD

**Issue by zhengmiaokai** [facebook/react-native#43318]
### Description

RNDemo project created through `npx react-native init RNDemo`, it can run in the simulator. But if I add pod 'WeexSDK', '~> 0.30.0', and after re-installing pod, I will get the error `'folly/portability/Config.h' file not found` when compiling with the simulator.

Error information: ~/RNDemo/ios/Pods/Flipper-Folly/folly/portability/Stdlib.h:21:10: 'folly/portability/Config.h' file not found
<img width="399" alt="image" src="https://github.com/facebook/react-native/assets/13111933/c5dfa74d-10fd-4e28-b97d-465ef9f4b235">

Pofile configuration: [Podfile.txt](https://github.com/facebook/react-native/files/14489552/Podfile.txt)

Background description：WeexSDK is referenced in existing projects, and now we want to introduce ReactNative, transform the Weex page into an RN page, and finally remove WeexSDK, so WeexSDK and ReactNative need to be dependent on both in the early stage.

### Steps to reproduce

1、Use the terminal, execute `npx react-native init RNDemo`.
2、Open the folder `RNDemo/ios` and replace the configuration of Podfile-[Podfile.txt](https://github.com/facebook/react-native/files/14489552/Podfile.txt).
3、Use the terminal to enter the ios folder and execute `pod install`.
4、Open `RNDemo/ios/RNDemo.xcworkspace`, run it in the  simulator.

### React Native Version

0.72.0 and 0.73.2 

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3
  CPU: (6) x64 Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
  Memory: 1.92 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
no stacktrace
```

### Reproducer

RNDemo: https://github.com/zhengmiaokai/RNDemo-Reproducer

**Comment by zhengmiaokai** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.11. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.



> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.11. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.



> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.11. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

This problem can also be reproduced using version 0.73.2

**Comment by zhengmiaokai** [comment]
> ⚠️	Newer Version of React Native is Available!
> ℹ️	You are on a supported minor version, but it looks like there's a newer patch available - 0.72.11. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

This problem can also be reproduced using version 0.73.2

**Comment by cipolleschi** [comment]
@zhengmiaokai, thanks for the issue.
I see that WeexSDK is trying to use a file `folly/portability/Config.h`.

Let's check what's happening:
1. Does your library use anything from Folly directly?
2. In your `Pods/RCTFolly/folly/portability` folder, do you have the Config.h file?
3. Does the error persist if you remove the WeexSDK library?
4. In your WeexSDK.podspec file, can you add [here]():
```diff
 s.pod_target_xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '${PODS_TARGET_SRCROOT}/weex_core/Source/ ${PROJECT_DIR}/../../../weex_core/Source',
    'GCC_PREPROCESSOR_DEFINITIONS' => 'OS_IOS=1',
+   "HEADER_SEARCH_PATHS" => \"$(PODS_ROOT)/RCT-Folly\",
}
``` 

This should fix the issue.

**Comment by zhengmiaokai** [comment]
@cipolleschi , thanks for your reply. 

Answer to the four questions above：
1. My Library don't use anything from Folly directly.
2. In my `Pods/RCT-Folly/folly/portability` folder, It have the `Config.h` file.
3. If I remove the WeexSDK library, the error don't occurred.
4. I add `"HEADER_SEARCH_PATHS" => \"$(PODS_ROOT)/RCT-Folly\"` in my WeexSDK.podspec file, But the error occurred.

**Comment by cipolleschi** [comment]
There must be some transitive dependency in your SDK that makes it depends on Folly, and the podspec can't find the right paths.
In React Native there are some other pods that depends on Folly.

Can you try to add:
1. [These lines](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/ReactCommon.podspec#L19-L20) to get the folly flags
2. add [these `compiler_flags`](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/ReactCommon.podspec#L36) (Only the folly ones, not the boost ones, for now).
3. Keep the `RCT-Folly` entry in the `HEADER_SEARCH_PATH`as [shown here](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/ReactCommon.podspec#L37)

**Comment by Ahsanali012** [comment]
Still i am getting this error having RN 0.72.3

`'folly/folly-config.h' file not found`

**Comment by cipolleschi** [comment]
@Ahsanali012 can you provide a reproducer using [this template](https://github.com/react-native-community/reproducer-react-native)?

Meanwhile, try to:
1. `bundle exec pod deintegrate`
2. `bundle exec pod install`
3. Open the `xcworkspace` and not the `xcodeproj` file
4. Build

**Comment by eldaroid** [comment]
Helped for me:
```
post_install do |installer|
  system("chmod -R u+w Pods/RCT-Folly")
  Dir.glob("Pods/RCT-Folly/folly/Portability.h").each do |file|
    text = File.read(file)
    new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
    File.open(file, "w") { |file| file.puts new_contents }
  end
end
```
Taken from: https://github.com/facebook/folly/issues/2297
