### ISSUE TITLE
App doesn´t work after 0.15 Update!

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#4333]
Like the Title says. I updated my RN to 0.15.0 from 0.13.0. Now the app won´t start and shows me following error, which i just can´t trace...

<img width="464" alt="screen shot 2015-11-24 at 22 32 07" src="https://cloud.githubusercontent.com/assets/7880624/11381320/a5a37e86-92fb-11e5-8b2b-51a4f5b86e9f.png">

Please Help! :P

**Comment by satya164** [comment]
Hi. Can you share your upgrade process? Did you use the command `react-native upgrade`?

**Comment by BigPun86** [comment]
I edited the package.json file where i pointed react-native from 0.13.0 to 0.15.0 and after that i simply used npm install, which installed the update. After that i updated every third party module with npm install react-native-some-module@latest

**Comment by satya164** [comment]
@BigPun86 After doing that, you can use the `react-native upgrade` command, which will also update the native library, gradle files etc.

Let me know if it helps.

**Comment by BigPun86** [comment]
Okay i found out that the update has issues with my integrated Flux. I created a complete new Project, and as soon as i integrated my "ScreenAction" it shows me a WhiteScreen!

LoginScreen:

```javascript
var ScreenAction = require('../../Flux/Actions/ScreenActions')
var LoginScreen = React.createClass({

 render: function () {
        return (
            <Navigator
                renderScene={this.renderScene}
                navigator={this.props.navigator}
                navigationBar={
                    <Navigator.NavigationBar
                            style={{backgroundColor: 'red'}}
                            routeMapper={NavigationBarRouteMapper}
                    />}
            />
        );
    },

renderScene: function () {
        return (
            <View style={styles.container}>
                <MKButton
                    onPress={ScreenAction._btnRegisterListener(this.props.navigator)} style={styles.buttonContainerRegister}>
                    <Image source={require ('../../Images/greenbutton.png')}>
                        <Text style={styles.buttonText}>
                            {STRINGS.buttonRegistration}
                        </Text>
                    </Image>
                </MKButton>
            </View>
        )
    },
})
```

ScreenActions:

```javascript
var Dispatcher = require('../Dispatcher');
var ActionTypes = require('../ActionTypes');

module.exports = {

    /**
     * @param  {props} navigator
     */
    _btnRegisterListener: function (navigator) {
        Dispatcher.dispatch({
            actionType: ActionTypes.SCREEN_REGISTRATION,
        });
        navigator.push({
            name: 'RegistrationScreen',
        });
    },
```

Dispatcher: 
```javascript
var Dispatcher = require ("flux").Dispatcher;
module.exports = new Dispatcher ();
```

"flux": "^2.1.1",
"keymirror": "^0.1.1",

**Comment by BigPun86** [comment]
Okay found the problem. Has nothing to do with flux! I called the Action to switch Screen directly in the onPress of MKButton (react-native-material-kit), which obviously doesn´t work...It will produce a whiteScreen without any error tracing. Didn´t know that this doesnt work...

**Comment by satya164** [comment]
Closing the issue since it's a big with a third party library. It would be great if you could report the issue in RN Material Kit repo.
