### ISSUE TITLE
[Navigator] Custom Bar

### ISSUE THREAD

**Issue by rileybracken** [facebook/react-native#4334]
**The problem:**
I ran into a problem where I needed to pass the navbar a custom view and there was no way to do it.

**Application:**
I needed a gradient inside of the navbar, and to my knowledge the only way to get a gradient is to add Brent Vatne's linear gradient plugin https://github.com/brentvatne/react-native-linear-gradient. I could see this being used if you needed a image in as a background as well.

In most cases I can see this only being useful if you need a gradient. That is why I think that a PR with my solution might be un-necessary.

**The solution:**
I made this work like when you want to render a header, a ScrollView or a row on ListViews.

``` Javascript
<Navigator
    renderScene={ () => <SettingsIndex /> }
    navigationBar={
      <Navigator.NavigationBar
        routeMapper={ NavigationBarRouteMapper }
        renderBar={ () => this.renderCustomBar() }
      />
    }
 />

```

**Result:**
![image](https://cloud.githubusercontent.com/assets/3174647/11382525/9436eba6-92bf-11e5-92c5-b544bbdfb18a.png)

I guess my question is, will this help anyone else? I could do a PR for it, it was really easy to implement. To do a PR I would want to write some tests and some documentation as well.

**Comment by satya164** [comment]
Hey @rileybracken . Thanks for the awesome work. Can you give a link to your implementation?

I guess an easier approach will be to wrap the NavigationBar in your custom component? Like so?

```js
class CustomNavigationBar extends React.Component {
    updateProgress(...args) {
        this._navbar.updateProgress(...args);
    }

    render() {
        return (
            <Wrapper>
                <Navigator.NavigationBar ref={c => this._navbar = c} {...this.props} />
            </Wrapper>
        );
    }
}
```

I've not tested this though.

**Comment by rileybracken** [comment]
Yeah here is the commit for it on my forked repo.

https://github.com/rileybracken/react-native/commit/e994b75fac195a69709580c17548e42993c54c5f

**Comment by satya164** [comment]
@rileybracken Looks good. @ide @mkonicek do we want this in core?

**Comment by ide** [comment]
It seems useful. A couple of use cases I can think of off the top of my head are a gradient and blur view. Both of those can't be implemented with a style.

I think it's very good that the API is flexible and makes you write your own code instead of something like `barLinearGradient={['#45baef', '#34bcd5']}`.

cc @ericvicenti

**Comment by mkonicek** [comment]
I believe @ericvicenti is not actively working on RN as he moved to a different team.

**Comment by rileybracken** [comment]
There aren't any docs for the `NavigatorNavigationBar` component should I just make the https://facebook.github.io/react-native/docs/navigator.html#navigationbar docs more detailed before making a PR?

**Comment by ide** [comment]
@rileybracken that'd be helpful, thanks! What would be really great is if there were a separate docs page for NavigationBar like how TabBarIOS and TabBarIOS.Item have their own docs.

**Comment by rileybracken** [comment]
@ide Tried writing some docs tonight but can't get the website setup locally. I am getting:

> Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory

because of: (for example in getting-started.js)

``` JavaScript
var Post = React.createClass({
  render: function() {
    return layout({metadata: {"id":"getting-started","title":"Getting Started","layout":"docs","category":"Quick Start","permalink":"docs/getting-started.html","next":"android-setup"}}, content);
  }
});
```

It seems like this is auto generated when I refresh the page how can I get around this?

**Comment by ide** [comment]
@rileybracken, could you perhaps be using npm 3? I've seen that website error before when using npm 3 instead of 2.

**Comment by rileybracken** [comment]
@ide I was using 3 but switched to two after what you said. Still getting the same error though. I reset my NPM cache and restarted my machine to see if that would make it go.

```
➜  website git:(rb-add-custom-navigator) ✗ npm -v
2.14.13
```

**Comment by satya164** [comment]
Any updates on this?

**Comment by rileybracken** [comment]
@brentvatne got me all figured out on the docs, worked on some of the docs for `NavigationBar` on Friday. Will get a PR ASAP.

**Comment by satya164** [comment]
@rileybracken Awesome :)

**Comment by rileybracken** [comment]
@satya164 Sorry I completely forgot about this until I updated the project I was working on with it. After updating my fork to v0.19 I made some changes and recommitted. 

I still want to write some documentation for `Navigator.NavigationBar` but I think this is worth getting in now. Then adding documentation later. 

Thoughts on opening a PR?

**Comment by ericvicenti** [comment]
@rileybracken  We are working on the next-generation navigator, which includes a new navigation bar. Because it isolates the views from the navigation logic and uses the new Animated library, it is much easier to hack on than the current `Navigator.NavigationBar`.

Take a look here, and please open issues for feedback!

https://github.com/ericvicenti/navigation-rfc/blob/master/CustomComponents/NavigationHeader.js

**Comment by geirman** [comment]
@ericvicenti do we need to keep this open? Maybe, since NavigatorExperimental isn't official yet, eh?

**Comment by ericvicenti** [comment]
Lets close it for now because we don't plan on making any changes to Navigator.NavigationBar
