### ISSUE TITLE
iOS Wrapping react-native into dynamic library caused Fabric exception

### ISSUE THREAD

**Issue by nanatlantica** [facebook/react-native#43343]
### Description

I wrapped libPods-ReactNativeSDK.a into a dynamic library for the app to depend on it, but my custom Fabric component cannot display (init method not called), and there is no error message.

### Steps to reproduce

1.Create dynamic library xcode project
2.install react native by Pod install
3.compile this project into .framework file
4.My app embeded the .framework file
5.Run

### React Native Version

0.72.5

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 288.92 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
nothing
```

### Reproducer

...

**Comment by cipolleschi** [comment]
Sorry, but this is not a setup we support at the moment. It is not that straight forward, as React Native is composed by several pieces and they are not all consolidated into a single static library.

Out of curiosity, did it worked in previous versions of the framework?

**Comment by nanatlantica** [comment]
> Sorry, but this is not a setup we support at the moment. It is not that straight forward, as React Native is composed by several pieces and they are not all consolidated into a single static library.
> 
> Out of curiosity, did it worked in previous versions of the framework?
I've paste my repo address
https://github.com/facebook/react-native/issues/43354

**Comment by nanatlantica** [comment]
here is my repo   :      https://github.com/nanatlantica/RNDynamic

Please help me to find out why Fabric components not displayed ?

**Comment by nanatlantica** [comment]
I’ve paste my repo in comment，would you please to help me find out the reason?

| |
董熠
***@***.***
|
---- Replied Message ----
| From | Riccardo ***@***.***> |
| Date | 03/06/2024 22:05 |
| To | facebook/react-native ***@***.***> |
| Cc | nanatlantica ***@***.***>,
Author ***@***.***> |
| Subject | Re: [facebook/react-native] iOS Wrapping react-native into dynamic library caused Fabric exception (Issue #43343) |

Sorry, but this is not a setup we support at the moment. It is not that straight forward, as React Native is composed by several pieces and they are not all consolidated into a single static library.

Out of curiosity, did it worked in previous versions of the framework?

**Comment by dominicstop** [comment]
i'm actually having the same problem; when dynamic linkage + new arch is enabled, the fabric views don't get called at all, only RN views exported via `RCTViewManager`

when i used static linkage, they work again.
