### ISSUE TITLE
Can not Build from Source , error when building with cmake, Looking for pthread_create in pthreads - not found

### ISSUE THREAD

**Issue by ncwuguowei** [facebook/react-native#43358]
### Description

windows 10, build form source, cmake fail

  [CXX1429] error when building with cmake using D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid\src\main\jni\CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Found Python: C:/Program Files/Python312/python.exe (found version "3.12.2") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done

![image](https://github.com/facebook/react-native/assets/10015460/4e5efef3-e282-4ae6-b43c-50f94e237d67)

### Steps to reproduce

1.follow the document
 https://reactnative.dev/contributing/how-to-build-from-source ,
 try build react-native project ,version 0.73.0
and modify settings. gradle 

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')

includeBuild('../node_modules/react-native') {
    dependencySubstitution {
        substitute(module("com.facebook.react:react-android")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:react-native")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:hermes-android")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
        substitute(module("com.facebook.react:hermes-engine")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
    }
}

2. add local.properties file to /node_modules/react-native
 sdk.dir=D\:\\Software\\Android\\Sdk
3. install python versio 3.12.2
4. try sync project ,but cmake fail
 
[CXX1429] error when building with cmake using D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid\src\main\jni\CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Found Python: C:/Program Files/Python312/python.exe (found version "3.12.2") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done

C++ build system [configure] failed while executing:
    @echo off
    "D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\src\\main\\jni" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_ANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-DCMAKE_FIND_ROOT_PATH=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\prefab\\x86\\prefab" ^
      "-BD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\x86" ^
      -GNinja ^
      "-DREACT_COMMON_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native/ReactCommon" ^
      "-DREACT_ANDROID_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid" ^
      "-DREACT_BUILD_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build" ^
      "-DANDROID_STL=c++_shared" ^
      "-DANDROID_TOOLCHAIN=clang" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON"
  from D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid
CMake Error in CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/hermes/executor/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
 
![image](https://github.com/facebook/react-native/assets/10015460/c47fb608-571f-46d2-ae4a-578c12aac77a)

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
npx react-native info

  WARNING: You should run npx react-native@latest to ensure you're always using the most current version of the CLI. NPX has cached version (0.73.0) != current re
lease (0.73.5)
  
info Fetching system and libraries information...
System:                                                      
  OS: Windows 10 10.0.19045                                  
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Memory: 3.95 GB / 15.71 GB                                 
Binaries:                                                    
  Node:
    version: 20.11.1
    path: D:\Programs\nodejs\node.EXE
  Yarn:
    version: 1.22.21
    path: D:\Programs\nodejs\node_modules\node_modules\yarn\bin\yarn.CMD
  npm:
    version: 10.2.4
    path: D:\Programs\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.73.5 is now available (your project is running on v0.73.0).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.5
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
```

### Stacktrace or Logs

```text
[CXX1429] error when building with cmake using D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid\src\main\jni\CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: D:/Software/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Found Python: C:/Program Files/Python312/python.exe (found version "3.12.2") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done

C++ build system [configure] failed while executing:
    @echo off
    "D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\src\\main\\jni" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_ANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-DCMAKE_FIND_ROOT_PATH=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\prefab\\x86\\prefab" ^
      "-BD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\x86" ^
      -GNinja ^
      "-DREACT_COMMON_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native/ReactCommon" ^
      "-DREACT_ANDROID_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid" ^
      "-DREACT_BUILD_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build" ^
      "-DANDROID_STL=c++_shared" ^
      "-DANDROID_TOOLCHAIN=clang" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON"
  from D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid
CMake Error in CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/hermes/executor/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/hermes/inspector-modern/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Warning in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/react/renderer/components/progressbar/CMakeLists.txt:
  The object file directory

    D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/.cxx/Debug/5m92g3t3/x86/ReactCommon/react/renderer/components/progressbar/CMakeFiles/rrc_progressbar.dir/./

  has 185 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    android/react/renderer/components/progressbar/AndroidProgressBarMeasurementsManager.cpp.o

  cannot be safely placed under this directory.  The build may not work
  correctly.


CMake Warning in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/react/renderer/components/legacyviewmanagerinterop/CMakeLists.txt:
  The object file directory

    D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/.cxx/Debug/5m92g3t3/x86/ReactCommon/react/renderer/components/legacyviewmanagerinterop/CMakeFiles/rrc_legacyviewmanagerinterop.dir/./

  has 211 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    LegacyViewManagerInteropShadowNode.cpp.o

  cannot be safely placed under this directory.  The build may not work
  correctly.


CMake Warning in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/react/renderer/textlayoutmanager/CMakeLists.txt:
  The object file directory

    D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/.cxx/Debug/5m92g3t3/x86/ReactCommon/react/renderer/textlayoutmanager/CMakeFiles/react_render_textlayoutmanager.dir/./

  has 195 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    platform/android/react/renderer/textlayoutmanager/TextLayoutManager.cpp.o

  cannot be safely placed under this directory.  The build may not work
  correctly.


CMake Error in D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactCommon/react/runtime/hermes/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in react/hermes/instrumentation/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in react/runtime/hermes/jni/CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Generate step failed.  Build files cannot be regenerated correctly.
Affected Modules: ReactAndroid, hermes-engine
```

### Reproducer

https://github.com/ncwuguowei/reproducer-react-native

### Screenshots and Videos

C++ build system [configure] failed while executing:
    @echo off
    "D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\src\\main\\jni" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_ABI=x86" ^
      "-DCMAKE_ANDROID_ARCH_ABI=x86" ^
      "-DANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_ANDROID_NDK=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393" ^
      "-DCMAKE_TOOLCHAIN_FILE=D:\\Software\\Android\\Sdk\\ndk\\25.1.8937393\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=D:\\Software\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build\\intermediates\\cxx\\Debug\\5m92g3t3\\obj\\x86" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-DCMAKE_FIND_ROOT_PATH=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\prefab\\x86\\prefab" ^
      "-BD:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\.cxx\\Debug\\5m92g3t3\\x86" ^
      -GNinja ^
      "-DREACT_COMMON_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native/ReactCommon" ^
      "-DREACT_ANDROID_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid" ^
      "-DREACT_BUILD_DIR=D:\\Workspace\\AwesomeProject61_2_backup\\node_modules\\react-native\\ReactAndroid\\build" ^
      "-DANDROID_STL=c++_shared" ^
      "-DANDROID_TOOLCHAIN=clang" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE=ON"
  from D:\Workspace\AwesomeProject61_2_backup\node_modules\react-native\ReactAndroid
CMake Error in CMakeLists.txt:
  Imported target "hermes-engine::libhermes" includes non-existent path

    "D:/Workspace/AwesomeProject61_2_backup/node_modules/react-native/ReactAndroid/hermes-engine/build/prefab-headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by ncwuguowei** [comment]
update reproducer 
https://github.com/ncwuguowei/reproducer-react-native
use viersion 0.73.5 build from source ,Runtime - Android, Build - Windows 10, cmake fail also.

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/37770

**Comment by ncwuguowei** [comment]
windows Platforms can not resolve build from souce? 
build on  Platforms Ubuntu or Mac can work？

**Comment by cortinico** [comment]
Exactly. We don't currently support build from source on Windows
