### ISSUE TITLE
[Codegen] Optional parameters in spec are not annotated as `@Nullable` in the Android generated code

### ISSUE THREAD

**Issue by NiuGuohui** [facebook/react-native#43360]
### Description

When props set nullable type, generating `XXXManagerInterface` class dont have `@Nullable` annotation.

### Steps to reproduce

TS file:

```ts
import type { DirectEventHandler, Float, Int32 } from 'react-native/Libraries/Types/CodegenTypes';

export interface RTNBlockKeyboardInputProps extends ViewProps {
  value?: Float;
  maxLength?: Int32;
}
```

Generate `XXXManagerInterface.java`:
```java

public interface XXXManagerInterface<T extends View> {
  void setValue(T view, float value); // ---> there should add @Nullable annotation.
  void setMaxLength(T view, int value);
}

```

### React Native Version

0.73.5

### Affected Platforms

Runtime - Android, Build - MacOS

### Areas

Fabric - The New Renderer, Codegen

### Output of `npx react-native info`

```text
.
```

### Stacktrace or Logs

```text
.
```

### Reproducer

.

**Comment by cortinico** [comment]
Yup you're right. I believe we don't annotate params with `@Nullable` because we don't want to use boxed types (`Integer` vs `int`).

**Comment by NiuGuohui** [comment]
So, how to handle the situation when props may be null?

**Comment by cortinico** [comment]
> > Yup you're right. I believe we don't annotate params with `@Nullable` because we don't want to use boxed types (`Integer` vs `int`).
> So, how to handle the situation when props may be null?

You just don't call `setMaxLength` if the value is null

**Comment by NiuGuohui** [comment]
> > > Yup you're right. I believe we don't annotate params with `@Nullable` because we don't want to use boxed types (`Integer` vs `int`).
> > > So, how to handle the situation when props may be null?
> 
> You just don't call `setMaxLength` if the value is null

tks

**Comment by radixdev** [comment]
Is there some other annotation you can set on the parameter so the downstream code knows it can be nullable? This matters a lot for Kotlin
