### ISSUE TITLE
tsconfig custom paths not working in 0.73.x

### ISSUE THREAD

**Issue by Crare** [facebook/react-native#43382]
### Description

upgrading from 0.72.9 to 0.73.5 gives error from tsconfig paths.

I've also reported issue about this to upgrade support, but it may not be directly related to it other than that the tsconfig changed, but the upgrading doesn't include custom paths in tsconfig setup. https://github.com/react-native-community/upgrade-support/issues/258

### Steps to reproduce

1. make new react-native cli app.
2. add components-folder under root.
3. add file under components-folder:
```
import React from 'react';
import {Text, View} from 'react-native';

export const TestComponent = () => {
  return (
    <View>
      <Text>Hello world</Text>
    </View>
  );
}
```
4. update App.tsx to return  TestComponent in render:
```
...
import {TestComponent} from 'components/testComponent';
...
function App(): React.JSX.Element {
  return (
    <SafeAreaView>
      <TestComponent />
    </SafeAreaView>
  );
}
...
```
5. add tsconfig with path:
```
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "components/*": ["components/*"]
    }
  }
}
```
6. run "yarn start" and select device ios or android. or run "yarn android".
7. get error: 

> error: Error: Unable to resolve module components/testComponent from /Users/username/git/test/AwesomeProject/App.tsx: components/testComponent could not be found within the project or in these directories:
>   node_modules
>   ../../../node_modules
>    6 |  */
>    7 |
> >  8 | import {TestComponent} from 'components/testComponent';
>      |                              ^
>    9 | import React from 'react';
>   10 | import type {PropsWithChildren} from 'react';
>   11 | import {
>     at ModuleResolver.resolveDependency (/Users/username/git/test/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
>     at DependencyGraph.resolveDependency (/Users/username/git/test/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
>     at /Users/username/git/test/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:156:21
>     at resolveDependencies (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
>     at visit (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Promise.all (index 2)
>     at async visit (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
>     at async Promise.all (index 0)
>     at async buildSubgraph (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)

### React Native Version

0.73.5

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
'''
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 94.20 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.2
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/username/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.22
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/username/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
'''
```

### Stacktrace or Logs

```text
error: Error: Unable to resolve module components/testComponent from /Users/username/git/test/AwesomeProject/App.tsx: components/testComponent could not be found within the project or in these directories:
    node_modules
    ../../../node_modules
    6 | */
    7 |

        8 | import {TestComponent} from 'components/testComponent';
        | ^
        9 | import React from 'react';
        10 | import type {PropsWithChildren} from 'react';
        11 | import {
        at ModuleResolver.resolveDependency (/Users/username/git/test/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:138:15)
        at DependencyGraph.resolveDependency (/Users/username/git/test/AwesomeProject/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
        at /Users/username/git/test/AwesomeProject/node_modules/metro/src/lib/transformHelpers.js:156:21
        at resolveDependencies (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
        at visit (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async Promise.all (index 2)
        at async visit (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
        at async Promise.all (index 0)
        at async buildSubgraph (/Users/username/git/test/AwesomeProject/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
```

### Reproducer

https://github.com/Crare/rn0.73.x_tsxonfig_paths_issue

**Comment by cortinico** [comment]
> upgrading from 0.72.9 to 0.73.5 gives error from tsconfig paths.

What was the tsconfig you were using on 0.72.9?

**Comment by Crare** [comment]
> > upgrading from 0.72.9 to 0.73.5 gives error from tsconfig paths.
> 
> What was the tsconfig you were using on 0.72.9?

It was "@tsconfig/react-native/tsconfig.json"

**Comment by cortinico** [comment]
cc @NickGerleman do you have an idea of what might be happening here?

**Comment by NickGerleman** [comment]
Don’t have any real ideas, but I noticed the casing of the import is incorrect, which can cause issues on some file systems.

**Comment by Rc85** [comment]
Also experiencing this after upgrading to 0.73.5

**Comment by Crare** [comment]
> Oh wait, this is happening during bundling, and not type checking.
> 
> @huntie @robhogan was CLI Metro resolution tsconfig aware at some point?
> 
> The existing guidance is to customize resolver at Babel level for this, which seems off. https://reactnative.dev/docs/typescript#using-custom-path-aliases-with-typescript

Yeah I tried that too. Didn't work.

**Comment by robhogan** [comment]
> @huntie @robhogan was CLI Metro resolution tsconfig aware at some point?

There's never been any support for this in Metro itself - Expo has some via a custom resolver IIRC, don't think there's ever been any in RNCLI.

The nearest change I can think of is that we flipped the default for [`enableGlobalPackages`](https://metrobundler.dev/docs/configuration/#enableglobalpackages), which could achieve a similar result but only if you have a `package.json` inside `components`.

@Crare / @Rc85 , could you share your `babel.config.js` (if any), and your `metro.config.js`?

**Comment by Crare** [comment]
> > @huntie @robhogan was CLI Metro resolution tsconfig aware at some point?
> 
> There's never been any support for this in Metro itself - Expo has some via a custom resolver IIRC, don't think there's ever been any in RNCLI.
> 
> The nearest change I can think of is that we flipped the default for [`enableGlobalPackages`](https://metrobundler.dev/docs/configuration/#enableglobalpackages), which could achieve a similar result but only if you have a `package.json` inside `components`.
> 
> @Crare / @Rc85 , could you share your `babel.config.js` (if any), and your `metro.config.js`?

I do have package.json-files inside the custom path folders like such:
```
{
    "name": "components"
}
```

repro files are here: https://github.com/Crare/rn0.73.x_tsxonfig_paths_issue/blob/main/ReproducerApp/babel.config.js
and here: https://github.com/Crare/rn0.73.x_tsxonfig_paths_issue/blob/main/ReproducerApp/metro.config.js

but in actual project they are set like this:

babel.config.js:
```
/* eslint-disable no-undef */

module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
    plugins: ['jsx-control-statements', 'react-native-reanimated/plugin']
};
```

metro.config.js:
```
/* eslint-disable @typescript-eslint/no-var-requires */
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
    transformer: {
        babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
        assetExts: assetExts.filter(ext => ext !== 'svg'),
        sourceExts: [...sourceExts, 'svg']
    }
};

module.exports = mergeConfig(defaultConfig, config);

```

**Comment by robhogan** [comment]
> I do have package.json-files inside the custom path folders like such.

This sounds like the answer then - Metro will resolve these if `resolver.enableGlobalPackages: true`, regardless of `tsconfig.json`.

[Global (aka "Haste") packages](https://metrobundler.dev/docs/resolution#resolvehastepackage-string--string) are a deprecated feature because they're not an industry standard and only likely to lead to surprises and confusion, which is why they're now off by default, as of Metro [0.79](https://github.com/facebook/metro/releases/tag/v0.79.0). I'd **recommend** keeping your `package.json` files and using [`workspaces`](https://classic.yarnpkg.com/lang/en/docs/workspaces/) instead, which are standard and also TypeScript compatible (without using `paths`).

To get the previous behaviour (**not recommended**):

```js
// metro.config.js
const config = {
    resolver: {
        enableGlobalPackages: true,
        // ...
    },
    // ...
};

**Comment by Crare** [comment]
Using those workspaces seems to fix the problem. Thanks!
