### ISSUE TITLE
0.15.0 throws compile errors

### ISSUE THREAD

**Issue by r6203** [facebook/react-native#4340]
After upgrading my app to react-native 0.15.0 I can't compile my app from within Xcode.
Creating a new project and compiling it gives the same errors.

![rn error](https://cloud.githubusercontent.com/assets/4466258/11391768/4fece1c6-9355-11e5-883d-921bd1e2d57e.png)

Is this a know bug?

edit: Of course I also upgraded my app with "react-native upgrade". But as I encounter the same error with a blank project, I assume the errors are somewhere else.

**Comment by mihirsoni** [comment]
@r6203  

Hi tried doing same steps ,and it seems it is working fine. With new project as well as upgrade.

Are you sure while upgrading you made sure that that conflicts/merge resolve properly. It may overwrite your changes, **(if you have made any)**.

From next time , please use http://stackoverflow.com for asking such question, until you feel this is bug in project.

**Comment by r6203** [comment]
@mihirsoni 

Thanks for your answer.

Yes, I resolved all conflicts properly.

Just now I discovered that I'm running Xcode 6. At the moment I'm upgrading to 7 and then I'll try again.
May I ask which version you are running?

I posted it here because I thought it were an project bug. Sorry for that.

**Comment by mihirsoni** [comment]
@r6203 

No problem. I am using Xcode 7.0.

If it still doesn't work let me know , and if it works please close this bug.

**Comment by ide** [comment]
This looks related to Obj C generics. Upgrading to Xcode 7 should fix this.
