### ISSUE TITLE
npm start doesn't work after upgrade to 0.15.0

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#4341]
`npm start` stopped working after upgrading to React-Native 0.15.0 yielding:
```
> AwesomeProject@0.0.1 start Dev/tmp/AwesomeProject
> react-native start

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
```

Output of `npm -g list --depth=0`:
```
/usr/local/lib
├── bower@1.6.5
├── grunt-cli@0.1.13
├── npm@3.5.0
└── react-native-cli@0.1.7
```

Output of `npm list --depth=0`:
```
AwesomeProject@0.0.1 Dev/tmp/AwesomeProject
└── react-native@0.16.0-rc
```
To be noted, using `react-native start` works as expected, which make me think this is a npm bug but I'm not sure on how to get started.

**Comment by ahanriat** [comment]
Related to http://stackoverflow.com/questions/33908314/packager-wont-start

**Comment by radko93** [comment]
Try adding react-native-cli to your (dev) dependencies.

**Comment by ahanriat** [comment]
It works perfectly ! Thanks @radko93

**Comment by Bhullnatik** [comment]
Thanks, this works but is it the expected behavior? Shouldn't `react-native-cli` be installed globally? Why the change in the 0.15.0?

**Comment by ide** [comment]
npm 3 might have broken global lookup of modules from npm run-scripts (I haven't verified... just a guess)

**Comment by Bhullnatik** [comment]
@ide That's what my first thought was, but under the same node/npm configuration it works with React-Native 0.14.0, while it doesn't with the 0.15.0+.
I would be interested in fixing this myself, but I don't know where to begin looking.

Thanks for your answer.

**Comment by radko93** [comment]
It's not npm 3 case, I've tested it on npm v2.

**Comment by grimen** [comment]
Ran into the issue, resolved after plenty of head scratching by cleaning `node_modules` (`rm -rf ./node_modules`) and then upgrading NPM (`npm install npm -g`) and install deps in the generated React Native project (`npm install`). Upgrade clash I guess, didn't have this issue last week.

**Comment by exoer** [comment]
Solved on Stackoverflow http://stackoverflow.com/questions/33908314/packager-wont-start

**Comment by mosesoak** [comment]
I got it to work by running npm install -g react-native-cli again and then closing the terminal window and opening a new one. npm start works now.

**Comment by xxmyjk** [comment]
http://stackoverflow.com/questions/33908314/packager-wont-start, the following helps me
```
  "scripts": {
    "start": "$NVM_BIN/react-native start"
  }
```

**Comment by GantMan** [comment]
:+1:  adding cli as a dependency worked for me for android deploys

**Comment by GantMan** [comment]
Something went fishy with today's build.   I had to:
`npm un react-native-cli` and `npm i react-native-cli`
FYI for others.

**Comment by muratsu** [comment]
@GantMan same thing happened to me too. Reinstalling `react-native-cli` once you update `react-native` solves the problem as you mentioned.

**Comment by madhums** [comment]
Adding react-native-cli to dev-deps doesn't solve the issue. What is the real issue here? 

```
"react-native": "0.19.0",
"react-native-cli": "~0.2.0"
```
```
$ node -v 
v6.1.0
$ npm -v 
3.8.6
```

**Comment by madhums** [comment]
After npm install, 

```sh
$ ls -l node_modules/.bin/react-native
lrwxr-xr-x  1 madhu  staff  47 May 17 15:04 node_modules/.bin/react-native -> ../react-native/local-cli/wrong-react-native.js
```

**Comment by madhums** [comment]
Ah, nevermind 

```
npm un react-native-cli -D
npm un react-native-cli -g
rm -rf node_modules
npm cache clear
npm i
npm i react-native-cli -D
```

and then it works. Weird !!
