### ISSUE TITLE
【iOS】The contentOffset property is missing from TextInputView's onScroll callback

### ISSUE THREAD

**Issue by rabbitmouse** [facebook/react-native#43428]
### Description

I found that in the onScroll callback of textInput, the old schema contained the contentOffset attribute, but the new schema did not, causing a crash!

### Steps to reproduce

```
const onInputScroll = (e) => {
    if (Platform.OS !== "web") {
      const {
        nativeEvent: {
          contentOffset: { x, y },
        },
      } = e;
      console.log('onInputScroll ====', e?.nativeEvent)
    }
  };

<TextInput
        onScroll={onInputScroll}
        ref={inputRef}
        multiline
>
```

### React Native Version

0.73.3

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
OS: macOS 14.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 109.81 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.1
    path: ~/.nvm/versions/node/v21.6.1/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v21.6.1/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/zhuzhiqin/.rvm/gems/ruby-2.7.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.2
    path: /Users/zhuzhiqin/.rvm/rubies/ruby-2.7.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.73.3
    wanted: 0.73.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Cannot read x from undefined
```

### Reproducer

https://github.com/rabbitmouse

### Screenshots and Videos

The old architecture scroll callback is as shown below
<img width="724" alt="image" src="https://github.com/facebook/react-native/assets/11554140/e61c04d5-84f3-439f-ad55-6e8739e5327e">

The new architecture scroll callback is as shown below
<img width="575" alt="image" src="https://github.com/facebook/react-native/assets/11554140/f041a1d7-0c54-4f4d-ada2-e27f89267c76">

I confirm that this is still described in the official documentation.
<img width="839" alt="image" src="https://github.com/facebook/react-native/assets/11554140/4d74d0d6-72f1-4bdd-bed3-a57032cf3c72">

Please fix it as soon as possible!

**Comment by cortinico** [comment]
@rabbitmouse thanks for your report.

Can you provide:
1. A valid reproducer (you linked your personal GH profile)
2. The code snippets as code and not as image (for SEO reasons)

And then we could look into it

**Comment by rabbitmouse** [comment]
https://github.com/facebook/react-native/pull/43445 

Yes I think this submission is correct, thx
