### ISSUE TITLE
[iOS][Information] App store submissions will require a privacy manifest and signature for hermes

### ISSUE THREAD

**Issue by leocpadua7** [facebook/react-native#43439]
### Description

Firstly, I know this may not be the correct way to address the issue here. It's not a bug, but I think the discussion could benefit from the visibility provided by opening an issue here.

That said, some context: Last year, Apple announced the “[Privacy updates for App Store submissions](https://developer.apple.com/news/?id=r1henawx)”.  It requires third-party SDKs to include a privacy manifest file, and this will be required by Spring 2024. Now, we know the actual deadline is May 1, according to [this post](https://developer.apple.com/news/?id=3d8a9yyh). 
Hermes is on the list of [third-party SDKs that require a privacy manifest and signature](https://developer.apple.com/support/third-party-SDK-requirements/). [An issue](https://github.com/facebook/hermes/issues/1216) was opened at facebook/hermes github, but the responsibility for addressing the issue is pointed to the react-native team.

So, what's the plan to solve this? I noted [this PR](https://github.com/facebook/react-native/pull/42979) that may be related, but couldn't find an answer there.

If this comes as a patch, which RN versions will be supported? Could be possible for this update or patch to be applied to `0.70`?

### Steps to reproduce

-

### React Native Version

0.73, 0.72, 0.71, 0.70

### Affected Platforms

Runtime - iOS, Build - MacOS, Other (please specify)

### Output of `npx react-native info`

```text
-
```

### Stacktrace or Logs

```text
-
```

### Reproducer

-

**Comment by cortinico** [comment]
The latest on this are here:
https://github.com/react-native-community/discussions-and-proposals/discussions/766

Let's avoid opening further issues as it fragments the information.

We'll share more guidance in the near future.
