### ISSUE TITLE
Cookies not being sent to webview for iOS after React Native Upgrade

### ISSUE THREAD

**Issue by caralin3** [facebook/react-native#43440]
### Description

Web view should be rendering a web page that has a cookie authentication. Instead it is rendering sign in page. This is happening on iOS after I upgraded to react native 0.73+. It was working properly before the upgrade.

I have both `thirdPartyCookiesEnabled={true}` and `sharedCookiesEnabled={true}` enabled. Also in `handleNavigationStateChange` I reset the cookies for iOS:

```
async function resetCookies() {
    const cookies = await CookieManager.getAll(Platform.OS === 'ios');
    Object.keys(cookies).forEach(key => {
      const cookie = cookies[key];
      if (cookie.domain === domain) {
        CookieManager.clearByName(url, cookie.name, Platform.OS === 'ios');
      }
    });
  }
```

**Expected behavior:**

Web view should render account page, not sign in page

**Environment:**
 - OS: Android, iOS
 - OS version: Android 34+, iOS 14+
 - react-native version: 0.73.6
 - react-native-webview version: 13.8.1

### Steps to reproduce

1. After logging into app, navigate to webview
2. Observe login page instead of info page

### React Native Version

0.73.6

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1
  Memory: 104.89 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.1.0
    path: ~/.nvm/versions/node/v19.1.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/Documents/app/node_modules/.bin/yarn
  npm:
    version: 8.19.3
    path: ~/.nvm/versions/node/v19.1.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 12.3.5
    wanted: ^12.1.1
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: ^0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https

**Comment by cortinico** [comment]
> This is happening on Android and iOS after I upgraded to react native 0.73+

1. From which version are you upgrading from?
2. Can you provide a reproducer?

**Comment by caralin3** [comment]
@cortinico Upgrading from:
```
"react-native": "0.70.8" -> "react-native": "0.73.4"
"react-native-webview": "11.26.0" -> "react-native-webview": "13.8.1"
```
Can't really provide a reproducer since this is a client's site.
