### ISSUE TITLE
Error: undefined is not an object (evaluating \'process.versions.node\')

### ISSUE THREAD

**Issue by atom992** [facebook/react-native#4345]
I am using react native 0.13.2
when I add the following module into my react native project:
```
npm install fs path deasync
```

and add the following code
```
var deasync = require('deasync');
```

I got the error:
```
Error: undefined is not an object (evaluating \'process.versions.node\')
```

**Comment by ide** [comment]
You probably need to define process.versions yourself before requiring deasync. One thing to keep in mind is React Native != Node.
