### ISSUE TITLE
TouchableWithoutFeedback crashes when SVG component is a direct child of it

### ISSUE THREAD

**Issue by am0ka** [facebook/react-native#43467]
### Description

After moving my app to Expo SDK 50, hence `react-native@0.73.4`, I got following error:
```
Exception thrown while executing UI block: - [RNSVGSvgView setOnClick:]: unrecognized selector sent to instance 0x7f8f3b8e3c00
```

After some time of debugging, I understood, that the problem in part of the code that looks like this:
```
import SvgIcon from "../assets/icon.svg;
...
<TouchableWithoutFeedback onPress={() => console.log("pressed")}
  <SvgIcon />
</TouchableWithoutFeedback>
...
```
If I wrap `SvgIcon` with `View` component, everyting works just fine.

### Steps to reproduce

1. I am using Expo dev-build, which were initialized from `npx react-native@latest init <project-name>`.
1. Also use [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer) to be able to import svg directly into the code

### React Native Version

0.73.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 442.61 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.18
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No console/debugger output, only on my iOS Simulator screen (provided screenshot)
```

### Reproducer

https://snack.expo.dev/@amoka/upbeat-orange-crackers

### Screenshots and Videos

![Simulator Screenshot - iPhone 15 Pro - 2024-03-13 at 23 03 56](https://github.com/facebook/react-native/assets/34053162/e7a5a664-fe86-4fd2-93b6-fae352e27268)

**Comment by cortinico** [comment]
Hi @am0ka 
Thanks for reporting this issue.

You should open this issue here first:

https://github.com/kristerkari/react-native-svg-transformer/issues

And get back to us if the library authors report that this is a React Native core issue
