### ISSUE TITLE
`Uncaught ReferenceError: require is not defined` when running on iOS device after upgrading to 0.15.0

### ISSUE THREAD

**Issue by npapanastasiou** [facebook/react-native#4347]
The app runs fine in Simulator, but when running on a physical iPhone 6 the app does not function save for TextInput components receiving input and Touchables registering presses. A Debug in Chrome reveals only the message from the title: `Uncaught ReferenceError: require is not defined`

Additional information I just remembered in case it can help:
- This very same issue also happened with version 0.14.2.
- Nothing of the sort happened between 0.11.0 through 0.13.0
- A second look revealed `Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'file:///private/var/mobile/Containers/Bundle/Application/63E36D01-6171-4230-9822-FA2BB6A44DEC/ArcInspect.app/main.jsbundle' failed to load.` immediately before the titular error message.

**Comment by chirag04** [comment]
@npapanastasiou Have you changed the ip address while running your app on real device?

Here is the doc explaining more about it: https://facebook.github.io/react-native/docs/running-on-device-ios.html#content

Make sure you computer and your mobile device are connected to the same network.

**Comment by npapanastasiou** [comment]
@chirag04 Yes, this fixed it. Thanks!

**Comment by chirag04** [comment]
:+1:
