### ISSUE TITLE
FBReactNativeSpec build commands failed with RN 0.71.4 / Xcode 15.3 / M2

### ISSUE THREAD

**Issue by aaronpliu** [facebook/react-native#43474]
### Description

After fix build issue with #43335, Xcode is ok to archive. Running with Jenkins CI, it ran into FBReactNativeSpec error.

The following build commands failed:
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/ywiuser/Library/Developer/Xcode/DerivedData/hwcApp-dvmqpzncteelaievntyghfvifnud/Build/Intermediates.noindex/ArchiveIntermediates/hwcApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E000z8E70.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)

**ENV:**
Xcode: 15.3
Arch: M2 Chip
OS: 14.3
RN: 0.71.4
Node: 18.9 (/usr/local/bin/node)

### Steps to reproduce

1. Xcode archive command with option -sdk iphoneos

### React Native Version

0.71.4

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.3.1
    CPU: (24) arm64 Apple M2
    Memory: 39.91 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 15.3/15E5202a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
The following build commands failed:
PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/ywiuser/Library/Developer/Xcode/DerivedData/hwcApp-dvmqpzncteelaievntyghfvifnud/Build/Intermediates.noindex/ArchiveIntermediates/hwcApp/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E000z8E70.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)
```

### Reproducer

https://github.com

**Comment by cortinico** [comment]
Please provide a valid repro

**Comment by aaronpliu** [comment]
it caused by node. Installed node 18 via installer (/usr/local/bin/node), also configured .xcode.env under /ios with export NODE_BINARY=$(command -v node). it's ok to change `$(commad -v node)` to `/usr/local/bin/node`. Also checked another build machine, same error, but it installed nvm before, using old node version (v16.7) instead of node 18.
similar issue like https://github.com/react-native-community/upgrade-support/issues/214

**Comment by cortinico** [comment]
> it caused by node. Installed node 18 via installer (/usr/local/bin/node), also configured .xcode.env under /ios with export NODE_BINARY=$(command -v node). it's ok to change `$(command -v node)` to `/usr/local/bin/node`. Also checked another build machine, same error, but it installed nvm before, using old node version (v16.7) instead of node 18. similar issue like [react-native-community/upgrade-support#214](https://github.com/react-native-community/upgrade-support/issues/214)

So is your issue solved?

**Comment by Linuhusainnk** [comment]
Try rebuild by upgrading ReactCodegen deployment target to IOS 12

**Comment by BogdanRad** [comment]
hello @aaronpliu, did you find a solution? I have same error.. 
Xcode: 15.3
"react-native": "0.71.7"
<img width="442" alt="image" src="https://github.com/facebook/react-native/assets/40359109/ce7e0911-f595-49dd-8850-50f9a5523ea4">

**Comment by BogdanRad** [comment]
SOLVED: I removed the `.xcode.env.local` from ios folder.

**Comment by harleenarora** [comment]
Any solution? I have same error
Xcode: 15.3
react-native: 0.70.7
node --version: 20.12.2

**Comment by Neeraj-WebNeuron** [comment]
I have the same issue
The following build commands failed:
        PhaseScriptExecution [CP-User]\ [Hermes]\ Replace\ Hermes\ for\ the\ right\ configuration,\ if\ needed /Users/ios/build/Pods.build/Debug-iphoneos/hermes-engine.build/Script-46EB2E00021D90.sh (in target 'hermes-engine' from project 'Pods')
(1 failure)

**Comment by wordisthebird** [comment]
> SOLVED: I removed the `.xcode.env.local` from ios folder.

Worked for me!
