### ISSUE TITLE
Prevent Chrome Debugger Tab from Getting Focus in JS Refresh

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4349]
If I am using the chrome debugger, when I refresh the JS code, the debugger tab ("React Native JS code runs inside this Chrome tab.") gets focused which is annoying / unnecessary since there is no meaningful content on this page.

posted here: https://productpains.com/post/react-native/prevent-chrome-debugger-tab-from-getting-focus-on-js-refresh/

**Comment by satya164** [comment]
It seems more to be more of Chrome's behaviour than RN.

**Comment by cancan101** [comment]
This issue no longer seems to happen in RN 0.15.

**Comment by satya164** [comment]
@cancan101 Are you sure? I'm on 0.15 and it happens for me.

**Comment by cancan101** [comment]
What version of Chrome?

**Comment by satya164** [comment]
Version 45.0.2454.101 (64-bit)

**Comment by cancan101** [comment]
I am now on: 46.0.2490.86

**Comment by satya164** [comment]
Upgraded Chrome to Version 47.0.2526.73 (64-bit) and this no longer happens. Closing the issue.
