### ISSUE TITLE
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by solitarysp** [facebook/react-native#43498]
### Description

executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -final_output -Xlinker /Applications/mobile.app/mobile -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile.swiftmodule -ObjC -lAmplitude -lBase64 -lCodePush -lDoubleConversion -lEXAppleAuthentication -lEXApplication -lEXClipboard -lEXConstants -lEXFont -lEXKeepAwake -lEXRandom -lEXWebBrowser -lExpo -lExpoModulesCore -lFBReactNativeSpec -lFirebaseABTesting -lFirebaseCore -lFirebaseCoreInternal -lFirebaseInstallations -lFirebaseRemoteConfig -lGoogleUtilities -lJWT -lMultiplatformBleAdapter -lPermission-Camera -lPermission-FaceID -lPromisesObjC -lRCT-Folly -lRCTTypeSafety -lRNCAsyncStorage -lRNCMaskedView -lRNDeviceInfo -lRNFBApp -lRNFBRemoteConfig -lRNFS -lRNFastImage -lRNGestureHandler -lRNKeychain -lRNLocalize -lRNPermissions -lRNReanimated -lRNSVG -lRNScreens -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-perflogger -lReactCommon -lSDWebImage -lSDWebImageWebPCoder -lSSZipArchive -lYoga -lamplitude-react-native -lappcenter-analytics -lappcenter-core -lc++ -lglog -liconv -llibwebp -llottie-ios -llottie-react-native -lnanopb -lreact-native-ble-plx -lreact-native-blur -lreact-native-camera -lreact-native-lottie-splash-screen -lreact-native-minimizer -lreact-native-netinfo -lreact-native-safe-area-context -lreact-native-webview -lsqlite3 -lsqlite3.0 -lstdc++ -lz -framework AppCenter -framework AppCenterAnalytics -framework AppCenterReactNativeShared -framework AudioToolbox -framework CoreBluetooth -framework CoreGraphics -framework CoreTelephony -framework EXFileSystem -framework EXSplashScreen -framework FirebaseAnalytics -framework Foundation -framework GoogleAppMeasurement -framework GoogleAppMeasurementIdentitySupport -framework ImageIO -framework JavaScriptCore -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -lc++ -lPods-mobile -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/InstallationBuildProductsLocation/Applications/mobile.app/mobile
ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  _swift_stdlib_isStackAllocationSafe, referenced from:
      function signature specialization <Arg[1] = Owned To Guaranteed> of function signature specialization <Arg[0] = [Closure Propagated : reabstraction thunk helper from @callee_guaranteed (@unowned FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error), Argument Types : [@callee_guaranteed (@unowned FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error)]> of generic specialization <FirebaseCoreInternal.TimePeriod, Foundation.Date> of Swift._NativeDictionary.filter(((key: A, value: B)) throws -> Swift.Bool) throws -> Swift._NativeDictionary<A, B> in libFirebaseCoreInternal.a[6](HeartbeatController.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce

Build release IOS

### React Native Version

0.64.4

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 235.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.19.0 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /Users/levanthanh/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -final_output -Xlinker /Applications/mobile.app/mobile -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile.swiftmodule -ObjC -lAmplitude -lBase64 -lCodePush -lDoubleConversion -lEXAppleAuthentication -lEXApplication -lEXClipboard -lEXConstants -lEXFont -lEXKeepAwake -lEXRandom -lEXWebBrowser -lExpo -lExpoModulesCore -lFBReactNativeSpec -lFirebaseABTesting -lFirebaseCore -lFirebaseCoreInternal -lFirebaseInstallations -lFirebaseRemoteConfig -lGoogleUtilities -lJWT -lMultiplatformBleAdapter -lPermission-Camera -lPermission-FaceID -lPromisesObjC -lRCT-Folly -lRCTTypeSafety -lRNCAsyncStorage -lRNCMaskedView -lRNDeviceInfo -lRNFBApp -lRNFBRemoteConfig -lRNFS -lRNFastImage -lRNGestureHandler -lRNKeychain -lRNLocalize -lRNPermissions -lRNReanimated -lRNSVG -lRNScreens -lReact-Core -lReact-CoreModules -lReact-RCTAnimation -lReact-RCTBlob -lReact-RCTImage -lReact-RCTLinking -lReact-RCTNetwork -lReact-RCTSettings -lReact-RCTText -lReact-RCTVibration -lReact-cxxreact -lReact-jsi -lReact-jsiexecutor -lReact-jsinspector -lReact-perflogger -lReactCommon -lSDWebImage -lSDWebImageWebPCoder -lSSZipArchive -lYoga -lamplitude-react-native -lappcenter-analytics -lappcenter-core -lc++ -lglog -liconv -llibwebp -llottie-ios -llottie-react-native -lnanopb -lreact-native-ble-plx -lreact-native-blur -lreact-native-camera -lreact-native-lottie-splash-screen -lreact-native-minimizer -lreact-native-netinfo -lreact-native-safe-area-context -lreact-native-webview -lsqlite3 -lsqlite3.0 -lstdc++ -lz -framework AppCenter -framework AppCenterAnalytics -framework AppCenterReactNativeShared -framework AudioToolbox -framework CoreBluetooth -framework CoreGraphics -framework CoreTelephony -framework EXFileSystem -framework EXSplashScreen -framework FirebaseAnalytics -framework Foundation -framework GoogleAppMeasurement -framework GoogleAppMeasurementIdentitySupport -framework ImageIO -framework JavaScriptCore -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -lc++ -lPods-mobile -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/IntermediateBuildFilesPath/mobile.build/Beta-iphoneos/mobile.build/Objects-normal/arm64/mobile_dependency_info.dat -o /Users/user/Library/Developer/Xcode/DerivedData/mobile-enlqcscemfhhjjfldsucnptaosmk/Build/Intermediates.noindex/ArchiveIntermediates/mobile/InstallationBuildProductsLocation/Applications/mobile.app/mobile
ld: warning: ignoring duplicate libraries: '-lc++'
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  _swift_stdlib_isStackAllocationSafe, referenced from:
      function signature specialization <Arg[1] = Owned To Guaranteed> of function signature specialization <Arg[0] = [Closure Propagated : reabstraction thunk helper from @callee_guaranteed (@unowned FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error), Argument Types : [@callee_guaranteed (@unowned FirebaseCoreInternal.TimePeriod, @in_guaranteed Foundation.Date) -> (@unowned Swift.Bool, @error @owned Swift.Error)]> of generic specialization <FirebaseCoreInternal.TimePeriod, Foundation.Date> of Swift._NativeDictionary.filter(((key: A, value: B)) throws -> Swift.Bool) throws -> Swift._NativeDictionary<A, B> in libFirebaseCoreInternal.a[6](HeartbeatController.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Screenshots and Videos

<img width="1005" alt="image" src="https://github.com/facebook/react-native/assets/20993683/139b0ac4-fe21-45cd-8291-d016763497a6">

**Comment by IseeUDenis** [comment]
I face the similar issue, you can check your Pod config first

![image](https://github.com/facebook/react-native/assets/8266838/59ae5ad9-d5e6-4b49-a1b3-0abaed961902)

Pull the follow in Podfile

```
    installer.pods_project.build_configurations.each do |config|
      if config.name.include?("Debug")
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        if !config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include? 'DEBUG=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEBUG=1'
        end
      end
    end
```
    
  Try "pod install" again

**Comment by lingluanchen** [comment]
> I face the similar issue, you can check your Pod config first
> 
> ![image](https://private-user-images.githubusercontent.com/8266838/327724193-59ae5ad9-d5e6-4b49-a1b3-0abaed961902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDkxNzEsIm5iZiI6MTcxODcwODg3MSwicGF0aCI6Ii84MjY2ODM4LzMyNzcyNDE5My01OWFlNWFkOS1kNWU2LTRiNDktYTFiMy0wYWJhZWQ5NjE5MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTEwNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M0YWEyOGNiYmRlNjQ5N2FiNjA5MTYyNDYyMGFkYmQ1ZjJhYmIwOTVkMWY2ZWU4MDMyYmZjMjAzYTBhN2UzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s3gqfWxGtxmbCxtt5CqeZA5e121n5vTfCsVxE0A8X30)
> 
> Pull the follow in Podfile
> 
> ```
>     installer.pods_project.build_configurations.each do |config|
>       if config.name.include?("Debug")
>         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
>         if !config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include? 'DEBUG=1'
>           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEBUG=1'
>         end
>       end
>     end
> ```
> 
> Try "pod install" again

It doesn't work

**Comment by damdafayton** [comment]
having same problem with "react-native": "0.76.9"
