### ISSUE TITLE
[Image - System Icons] Support for native UIBarButton images possible?

### ISSUE THREAD

**Issue by stefalda** [facebook/react-native#435]
Yesterday I saw this [question](http://stackoverflow.com/questions/29323069/how-to-display-an-icon-in-react-native/29326995#29326995) on StackOverflow that asked how to use the System icons in button, but, as I've answered there, I guess that's currently not possible because iOS AFAIK doesn't export that images other than by creating the UIBarButton element, am I wrong?

Is there any plan to map these elements or should we use an Image (that could not be the same used system wide) to emulate this behavior?

**Comment by brentvatne** [comment]
Interesting question, @ide any idea about this?

**Comment by ide** [comment]
It is possible but not implemented and AFAIK no one is working on it. You could expose a prop like leftButtonSystemIcon that takes the name of an icon, and on the Obj-C side display the corresponding icon.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/image-system-icons-support-for-native-uibarbutton-images-possible
