### ISSUE TITLE
[Navigator] Long previous route title and the leftButton from the navbar collide 

### ISSUE THREAD

**Issue by elisei-timofte** [facebook/react-native#4350]
On long titles some of the text of the previous route title appears on the screen.
<img width="440" alt="screen shot 2015-11-25 at 17 53 36" src="https://cloud.githubusercontent.com/assets/6162068/11401885/88bbdb0e-939d-11e5-8694-fc14beac69b2.png">
Is this a problem with the Navigator or I am doing something wrong?
Thanks in advance!

**Comment by lightsuner** [comment]
Got the same problem (iphone 5 emu.) 

![image of bug](http://i.imgur.com/RSpv3Jb.png)

**Comment by elisei-timofte** [comment]
here is the productpain [link] (https://productpains.com/post/react-native/long-previous-route-title-collide-with-the-leftbutton-of-the-navbar/). You can up rate and comment it there. May be they will fix it

**Comment by lightsuner** [comment]
@elisei-timofte thx

**Comment by christopherdro** [comment]
Closing this issue here since one exists on Product Pains. 
https://productpains.com/post/react-native/long-previous-route-title-collide-with-the-leftbutton-of-the-navbar/

Thank you.
