### ISSUE TITLE
v7 Navigating back randomly causes NAVIGATE action to be dispatched instead of GO_BACK

### ISSUE THREAD

**Issue by Caundy** [facebook/react-native#43515]
### Description

Posting in hope that someone has already encountered this issue or could reason about the incorrect behaviour observed. Issue happens in a proprietary codebase but if noone can advise on further steps, I'll try creating a reproduction repository.

Having updated the navigation configuration in our app from v4 to v7, very rarely and seemingly in a completely random fashion, when using `props.navigation.goBack()`, the `GO_BACK` action is replaced by `NAVIGATE` one - always navigating to the last stack within the bottom tab navigator.

Using dynamic configuration with `@react-navigation v7` + `backBehavior: 'history'`.

Navigation structure is as follow:
```
BOTTOM-TABS
    NATIVE_STACK A
        LIST_SCREEN + DETAILS_SCREEN
    NATIVE_STACK B
        LIST_SCREEN + DETAILS_SCREEN
    NATIVE_STACK C
        LIST_SCREEN + DETAILS_SCREEN
    NATIVE_STACK D
        LIST_SCREEN + DETAILS_SCREEN
```

When following actions' order like so:
```
1 Load app, get navigated to NATIVE_STACK A (LIST_SCREEN)
2 Using bottom tab, navigate to NATIVE_STACK C  (LIST_SCREEN)

3 Open the DETAILS_SCREEN for one of the items
4 Press hardware back button or icon triggering props.navigation.goBack()
5 Observe navigation correctly going back to NATIVE_STACK C's LIST_SCREEN

6 Repeat steps 3&4 (open details -> go back) until the bug occurs
6 Observe navigation having been set to NATIVE_STACK D's LIST_SCREEN 
```

After the error occurs, when navigating to the NATIVE_STACK C using bottom tab, one can observe the DETAILS_SCREEN has not been removed. 
Additionally, listener added to the `beforeRemove`  event does not trigger when trying to `goBack` when the error occurs. 

The issue happens in all the stacks where user tries to trigger the back navigation - can happen in `NATIVE_STACKs A,B or C`. When the bug occurs, the user is *always* navigated to the last stack in the bottom tab navigator.

Cheers in advance!

### Steps to reproduce

The reproduction steps can be performed in either development build or a production apk.  
Running either on an emulator or a real device, with different system versions (tested i.e. Android 11 and 13)

### React Native Version

0.73.2 (also happens in v0.73.6)

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
"@react-navigation/bottom-tabs": "^7.0.0-alpha.8",
"@react-navigation/devtools": "^6.0.25",
"@react-navigation/native": "^7.0.0-alpha.7",
"@react-navigation/native-stack": "^7.0.0-alpha.12",
```

### Stacktrace or Logs

```text
-
```

### Reproducer

-

**Comment by cortinico** [comment]
> Having updated the navigation configuration in our app from v4 to v7

Hey @Caundy 
you should report this against react-navigation and not here 👍

Closing as it's unrelated to react-native
