### ISSUE TITLE
[Text] Weird gap in text elements

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#4353]
Hi guys,

I'm having a weird issues with ```<Text>``` element in React Native ```0.13.0```
Some texts are breaking into multiple lines although there's enough space.
![simulator screen shot 25 nov 2015 17 58 05](https://cloud.githubusercontent.com/assets/1016375/11402241/8022a430-939f-11e5-8169-c4841d7a6a61.png)

Another issue is that some text have extra useless space after the text ends
![simulator screen shot 25 nov 2015 18 09 14](https://cloud.githubusercontent.com/assets/1016375/11402307/e06cbe8e-939f-11e5-8309-9865a48197bd.png)

Are these know issues? I'm not sure what caused this because other texts are just fine.
Any tips on how to debug/fix this issue?

Thanks.

**Comment by christopherdro** [comment]
@ranyefet Is there anyway you can try this with the latest version, 0.15 and see if the problem still persists?

**Comment by ranyefet** [comment]
@christopherdro Thanks, I still haven't tested it on 0.15 (or now 0.16) but I managed to find a work around.

On my ```<Text>``` element I had ```paddingRight: 50``` which I suspected to cause this issue.
So instead of:
```
<View>
  <Text style={{paddingRight: 50}}>Hello World very long text</Text>
</View>
```

I moved this property into the parent ```<View>``` that wraps my ```<Text>``` node and it's now working.
```
<View style={{paddingRight: 50}}>
  <Text>Hello World very long text</Text>
</View>
```

It's still a bug, so I leave it open but at least we have a workaround now ;)
I hope it helps.

**Comment by DanielHoffmann** [comment]
@christopherdro @ranyefet I have been having similar problems with my app, in one screensize everything works great, in a device with a slightly smaller screen size I all my Text elements are having letters disappearing (even though there is more than enough room for the letters). I believe it might have something to do with applying a margin/padding to an element when there is not enough room to actually put that margin/padding there, probably making some variable go negative

**Comment by ranyefet** [comment]
I've upgraded to v0.15 but the problem returned. So no workaround ATM :(

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/text-weird-gap-in-text-elements

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
