### ISSUE TITLE
 on Android，After upgrading React Native from 0.64.2 to 0.72.5, constants returned via getContents in bridge classes cannot be used in JavaScript

### ISSUE THREAD

**Issue by zwyzzu** [facebook/react-native#43573]
### Description

Java：
public class RTNCalculatorTurbo extends NativeRTNCalculatorSpec {
  @Override
  public Map<String, Object> getConstants() {
    final Map<String, Object> map = new HashMap<>();
    map.put("valueStr", "valueString");
    return map;
  }
  
  JS
  console.log('============' + RTNCalculator.valueStr)
  
  log：
   LOG  ============undefined
  

### Steps to reproduce

1

### React Native Version

0.72.5

### Affected Platforms

Runtime - Android

### Areas

TurboModule - The New Native Module System

### Output of `npx react-native info`

```text
1
```

### Stacktrace or Logs

```text
LOG  ============undefined
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by cortinico** [comment]
What is the question @zwyzzu ?

**Comment by zwyzzu** [comment]
In the JAVA class (RTNCalculatorTurbo extends NativeRTNCalculatorSpec), the getContents method is overridden to return a map (with map.put("valueStr", "valueString")). In 0.64.2, we were able to reference the constant (RTNCalculator.valueStr) normally, but after upgrading to 0.72.5, using RTNCalculator.valueStr shows undefined

**Comment by cortinico** [comment]
> In the JAVA class (RTNCalculatorTurbo extends NativeRTNCalculatorSpec), the getContents method is overridden to return a map (with map.put("valueStr", "valueString")). In 0.64.2, we were able to reference the constant (RTNCalculator.valueStr) normally, but after upgrading to 0.72.5, using RTNCalculator.valueStr shows undefined

How does your JS file look like for Calculator?
Can you please provide a valid reproducer?

**Comment by zwyzzu** [comment]
Java

package com.awesomeproject.turbomodule;

import android.util.Log;

import com.autohome.rnmodule.rtncalculator.NativeRTNCalculatorSpec;
import com.awesomeproject.react.RTNCalculatorModuleImpl;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactMethod;

import java.util.HashMap;
import java.util.Map;

public class RTNCalculatorTurbo extends NativeRTNCalculatorSpec {

  private static final String TAG = "yedr.RTNCalculatorTurbo";

  private ReactApplicationContext reactContext;

  private RTNCalculatorModuleImpl impl;

  public RTNCalculatorTurbo(ReactApplicationContext reactContext) {
    super(reactContext);
    this.reactContext = reactContext;
    impl = new RTNCalculatorModuleImpl(reactContext);
  }

  @ReactMethod
  public void add(double a, double b, Promise promise) {
    // call Delegate
    Log.d(TAG, "[newArch]add");
    impl.add(a, b, promise);
  }

  @Override
  public boolean hasConstants() {
    return true;
  }

  @Override
  @ReactMethod(isBlockingSynchronousMethod = true)
  public Map<String, Object> getConstants() {
    final Map<String, Object> map = new HashMap<>();
    map.put("valueStr", "valueString");
    return map;
  }

  @Override
  public void onCatalystInstanceDestroy() {
    impl.onCatalystInstanceDestroy();
  }

  @Override
  public void initialize() {
    impl.initialize();
  }

//  @Override
//  public void invalidate() {
//    super.invalidate();
//    impl.invalidate();
//  }
}


JavaScript
import type {TurboModule} from 'react-native/Libraries/TurboModule/RCTExport';
import {TurboModuleRegistry} from 'react-native';

export interface Spec extends TurboModule {
  add(a: number, b: number): Promise<number>;
}

export default TurboModuleRegistry.get<Spec>(
  'RTNCalculator',
) as Spec | null;



Using in JavaScript
import RTNCalculator from 'RTNCalculator/js/NativeRTNCalculator.ts';  // TruboModule
console.log('============' + RTNCalculator.valueStr)

**Comment by zwyzzu** [comment]
By logging, it was found that the getContents method of RTNCalculatorTurbo was not called.

**Comment by cortinico** [comment]
```diff
import type {TurboModule} from 'react-native/Libraries/TurboModule/RCTExport'; import {TurboModuleRegistry} from 'react-native';

+export interface SomeConstants {
+   x: string;
+   y: number;
+   z: boolean;
+}

export interface Spec extends TurboModule { 
+   getConstants(): SomeConstants
	add(a: number, b: number): Promise; 
}

export default TurboModuleRegistry.get( 'RTNCalculator', ) as Spec | null;
```

In order to support Constants with TurboModules, you will have to follow this syntax
