### ISSUE TITLE
Trying to return null from a render, but no null placeholder component was injected

### ISSUE THREAD

**Issue by glenjamin** [facebook/react-native#436]
With the following code:
```jsx
var Thingy = React.createClass({
  render() {
    if (!this.props.count) {
      return null;
    }
    return (
      <View style={styles.thing}>
        <Text style={styles.thingText}>Things</Text>
        <Text style={styles.thingCount}>{this.props.count}</Text>
      </View>
    );
  }
});
```

I get this rather cryptic error:

![screen shot 2015-03-29 at 12 34 45](https://cloud.githubusercontent.com/assets/151272/6885266/006f5708-d610-11e4-8944-32a961f768e3.png)

Easy enough to work around for now, but it's not obvious to me from this error whether `null` isn't supported, or there's something odd about this case which makes it not work.

**Comment by vjeux** [comment]
@spicyj fixed it
