### ISSUE TITLE
Handling different XCode Configurations

### ISSUE THREAD

**Issue by bleonard** [facebook/react-native#4362]
Currently the [react-native-xcode.sh command](https://github.com/facebook/react-native/blob/9a64f17de84e50a4fc60f1b96168aa61925934a8/packager/react-native-xcode.sh) crashes when the `$CONFIGURATION` is anything but `Release` or `Debug`.

There are reasons why we have a configuration for `Staging`. All Xcode projects treat this as the default (usually Release). Your goals seems to be to set `DEV` to true or false. I would suggest doing an else case to false.

If you also want to throw an error if not running in XCode, it seems like just haveing `$CONFIGURATION` (or a few more) would be sufficient.

Here is the code in my project (Build Phase) that is currently working around this for those interested.

```
if [ "${CONFIGURATION}" == "Debug" ]
then
BUNDLECONFIG=Debug
else
BUNDLECONFIG=Release
fi

CONFIGURATION=$BUNDLECONFIG ../node_modules/react-native/packager/react-native-xcode.sh
```

**Comment by bleonard** [comment]
I'd be happy to make a PR if the above sounds more or less ok.

**Comment by bleonard** [comment]
hmm, ok. I'd be happy to do the latter. @frantic @ide let me know if you have anything against being a little more lax in there and I'll submit a PR.

**Comment by grabbou** [comment]
I think it could play well with rn-cli.config.js and e.g. method `getConfiguration(xCodeRelease)` for instance.

**Comment by javache** [comment]
I think this is a good boundary for transforming the xcode config to a packager option (I don't think we would want to duplicate to similar logic for the Android config), so making react-native-xcode default to `DEV=false` sounds good to me.

**Comment by bleonard** [comment]
PR https://github.com/facebook/react-native/pull/4520
