### ISSUE TITLE
React Native 0.74.0-rc.4: `use_ccache` is broken: no ccache wrapper script `ccache-clang.sh` bundled in npm package

### ISSUE THREAD

**Issue by CatStudioApp** [facebook/react-native#43633]
### Description

if `use_ccache`, it would find wrapper scripts in this path `node_modules/react-native/scripts/xcode/...` but this directory does not contain that script
https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/xcode/ccache-clang.sh

<img width="300" alt="image" src="https://github.com/facebook/react-native/assets/52243759/dc84136c-e3b5-45f5-b1fb-97d7d675ebc9">

### Steps to reproduce

N/A

### React Native Version

0.74.0-rc.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by cortinico** [comment]
Thanks for the report. This will be included in 0.74 RC6
