### ISSUE TITLE
react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java:133  miss contanst

### ISSUE THREAD

**Issue by coderlin** [facebook/react-native#4367]
hi react-native, thanks for read
when I clone the react-native project, after setup my env(sdk,ndk....)
then I run 'npm install' and './gradlew :Examples:UIExplorer:android:app:installDebug'
I found the error like this:

..............
bi-v7a/libreactnativejni.so
[x86] StaticLibrary  : libreactnative.a
[x86] SharedLibrary  : libreactnativejni.so
[x86] Install        : libreactnativejni.so => /Users/lam/Documents/develop/react-native/react-native/ReactAndroid/build/react-ndk/all/x86/libreactnativejni.so
make: Leaving directory `/Users/lam/Documents/develop/react-native/react-native/ReactAndroid/src/main/jni/react/jni'
:ReactAndroid:packageReactNdkLibs
:ReactAndroid:processReleaseJavaRes UP-TO-DATE
:ReactAndroid:compileReleaseJavaWithJavac
/Users/lam/Documents/develop/react-native/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java:133: 错误: 找不到符号
          Systrace.isTracing(Systrace.TRACE_TAG_REACT_APPS) ? "true" : "false");
                                     ^
  符号:   变量 TRACE_TAG_REACT_APPS
  位置: 类 Systrace
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误
:ReactAndroid:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

plz told me where am I miss??

**Comment by lashad** [comment]
Hi @coderlin,

Just workaround !! 

Edit CatalystInstanceImpl.java file line 133. Replace Systrace.TRACE_TAG_REACT_APPS constant with Systrace.TRACE_TAG_REACT_JAVA_BRIDGE

good luck.

**Comment by ide** [comment]
This should be fixed in master.

**Comment by coderlin** [comment]
thx @lashad @ide I will pull down and try again
