### ISSUE TITLE
[0.74] Performing a refresh is unstable under Bridge Mode on Android (RNTester / New Arch)

### ISSUE THREAD

**Issue by huntie** [facebook/react-native#43692]
### Description

Performing a refresh is leading to some lifecycle error that results in a black screen.

Affects `0.74-stable` and `main`.

### Steps to reproduce

1. Install RNTester on Android, having disabled Bridgeless (-> Bridge Mode).
    <img width="1325" alt="image" src="https://github.com/facebook/react-native/assets/2547783/7b227a35-05cc-49fa-a827-b291ee021878">
2. Open Dev Menu and trigger a reload.
    - 🎯 This will randomly fail and display a blank screen. See video (on attempt 3).

### React Native Version

0.74.0, main

### Affected Platforms

Runtime - Android

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
—
```

### Stacktrace or Logs

```text
manager.UIManagerHelper  E  Unhandled SoftException
                         E  com.facebook.react.bridge.ReactNoCrashSoftException: Cannot get UIManager because the context doesn't contain an active CatalystInstance.
                         E      at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:82)
                         E      at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcher(UIManagerHelper.java:134)
                         E      at com.facebook.react.uimanager.UIManagerHelper.getEventDispatcherForReactTag(UIManagerHelper.java:112)
                         E      at com.facebook.react.internal.interop.InteropEventEmitter.receiveEvent(InteropEventEmitter.kt:37)
                         E      at com.facebook.react.uimanager.events.ReactEventEmitter.receiveEvent(ReactEventEmitter.java:146)
                         E      at com.facebook.react.uimanager.events.ReactEventEmitter.receiveEvent(ReactEventEmitter.java:65)
                         E      at com.facebook.react.uimanager.events.ReactEventEmitter.receiveEvent(ReactEventEmitter.java:58)
                         E      at com.facebook.react.uimanager.events.Event.dispatch(Event.java:173)
                         E      at com.facebook.react.uimanager.events.Event.dispatchModern(Event.java:209)
                         E      at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:376)
                         E      at android.os.Handler.handleCallback(Handler.java:958)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                         E      at android.os.Looper.loopOnce(Looper.java:205)
                         E      at android.os.Looper.loop(Looper.java:294)
                         E      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:235)
                         E      at java.lang.Thread.run(Thread.java:1012)
```

### Reproducer

https://github.com/facebook/react-native/tree/main/packages/rn-tester

### Screenshots and Videos

https://github.com/facebook/react-native/assets/2547783/2a63c65a-8b8a-4564-b8ae-1430d35aa5fa

**Comment by cortinico** [comment]
This is indeed an issue, and the fix is here https://github.com/facebook/react-native/pull/43999

**Comment by cortinico** [comment]
✅ Picked, this will land in 0.74 RC8

**Comment by rmace001** [comment]
> ✅ Picked, this will land in 0.74 RC8

Hi @cortinico! I am experiencing this issue even on 0.74.7. In my case, we migrated from 0.71.12 to 0.73.5 and noticed this issue. Then, we migrated to 0.74.7 due to seeing your comment. Unfortunately, we are still having issues with performing a refresh. We also do not have the new arch enabled.

**Comment by cortinico** [comment]
> > ✅ Picked, this will land in 0.74 RC8
> 
> Hi [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/3001957?s=64&amp;u=612480c64b45755601addb40b5ede4bc7c221a05&amp;v=4">@cortinico](https://github.com/cortinico?rgh-link-date=2025-02-10T22%3A47%3A41.000Z)! I am experiencing this issue even on 0.74.7. In my case, we migrated from 0.71.12 to 0.73.5 and noticed this issue. Then, we migrated to 0.74.7 due to seeing your comment. Unfortunately, we are still having issues with performing a refresh. We also do not have the new arch enabled.

Please open a new issue + provide reproducer. Ideally also make sure that this reproduces on 0.77 as 0.74 is out of support
