### ISSUE TITLE
Version 0.73, ios cannot debug with hermes engine when setup mutiple configuration scheme

### ISSUE THREAD

**Issue by tronghoangtdt** [facebook/react-native#43709]
### Description

ios cannot debug with hermes engine when setup mutiple configuration scheme

![Screenshot 2024-03-29 at 09 39 00](https://github.com/facebook/react-native/assets/92295859/813ccc35-ec93-44ca-8312-7665c1d500c5)
![Screenshot 2024-03-29 at 09 42 13](https://github.com/facebook/react-native/assets/92295859/b995f30c-14de-4ce5-a014-d51a22ec1ae9)

### Steps to reproduce

1. create app with version 0.73
2. install react-native-config
3. create mutiple configuration
4. add  => project 'App', {
  'DebugStaging' => :debug,
  'DebugProduction' => :debug,
  'ReleaseStaging' => :release,
  'ReleaseProduction' => :release,
} => to pod file
5. remove flipper

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1
  Memory: 290.02 MB / 16.00 GB
  Shell:
    version: 3.7.0
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2024.03.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
App not crash, just cannot debug with hermes engine
```

### Reproducer

I not using expo

### Screenshots and Videos

![Screenshot 2024-03-29 at 09 39 00](https://github.com/facebook/react-native/assets/92295859/f4d9e7ba-a1ba-4457-8b06-858923942853)
![Screenshot 2024-03-29 at 09 42 13](https://github.com/facebook/react-native/assets/92295859/bab34287-13a0-420c-97ce-4043a1e966a3)

**Comment by sternlucas** [comment]
@tronghoangtdt I think this error was just fixed.

[PR43780](https://github.com/facebook/react-native/pull/43780)

I have the same problem here. But I don't know how I can fix this until the new version is released.
