### ISSUE TITLE
[AlertIOS] AlertIOS.alert crash in v0.15.0

### ISSUE THREAD

**Issue by jarvys** [facebook/react-native#4372]
`AlertIOS.alert()` crash because `RCTKeyWindow()` always return nil.

**Comment by christopherdro** [comment]
@jarvys Could you provide us with a bit more information on your environment such as the version of React Native and iOS? Thanks!

**Comment by christopherdro** [comment]
@jarvys Just tested this on 0.15 and everything is working fine. 
Closing this for now, feel free to open it again if the problem persists.

Thanks!
