### ISSUE TITLE
fetch needs patched for try/catch on JSON.parse

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#4376]
Please fix <https://github.com/facebook/react-native/blob/854689dcfaa7dc13e8ee5dec69f9f7a569595dd1/Libraries/Fetch/fetch.js#L232> to have try/catch surrounding JSON.parse?

**Comment by niftylettuce** [comment]
also why are you throwing errors instead of sending them back with Promise.reject?

<https://github.com/facebook/react-native/blob/854689dcfaa7dc13e8ee5dec69f9f7a569595dd1/Libraries/Fetch/fetch.js#L125> uses reject but this doesn't https://github.com/facebook/react-native/blob/854689dcfaa7dc13e8ee5dec69f9f7a569595dd1/Libraries/Fetch/fetch.js#L194

**Comment by niftylettuce** [comment]
Basically because you are throwing errors and not wrapping JSON.parse in a try/catch block - I had to dig deep to find out that my 404 response could not use `res.json()` in this example:

```js
        fetch(apiUri + path, {
          method: 'GET',
          headers: that.headers
        })
        .then((res) => res.json())
        .then((res) => {
          if (res && res.error)
            return fn(res.error);
          fn(null, res);
        })
        .catch(fn)
```

The error is thrown that it can't parse JSON (the body is text response)

**Comment by niftylettuce** [comment]
The reason I have to use `fetch` polyfill is because `superagent` doesn't work because it's trying to run in a node runtime environment and not a browser environment or something.  This is broken and we can't even hook in a simple API into react-native...

**Comment by satya164** [comment]
if an error is thrown inside the `.then` callback, isn't it supposed to be propagated to the `.catch` callback?

**Comment by brentvatne** [comment]
Closing as per discussion in https://github.com/github/fetch/issues/235
