### ISSUE TITLE
[Android] `fetch` silently fails without resolving or rejecting the promise

### ISSUE THREAD

**Issue by Kuzmin** [facebook/react-native#4382]
Trying to `fetch` an url like `https://example.com/api/resources/?scopes=new&filter={"name":"Hello World"}` on Android silently fails. On iOS it successfully executes the request. 

This seems to be an issue in how the `fetch` adapter for Android handles malformed URLs, since by running `encodeURIComponent` on the relevant parts in the URL, this was resolved. 

This is an issue because the Promise neither resolves nor rejects, but just hangs there. For me, who migrated an app from iOS to Android, it lead to a bunch of confusing behaviour, and it took a long while to trace it back to issues with the URL format. I think that simply rejecting the promise/raising an exception in the right place would make this a lot easier to debug for other users in the future.

**Comment by satya164** [comment]
cc @mkonicek

**Comment by qbig** [comment]
```javascript
    fetch('https://example.com/api/resources/?scopes=new&filter={"name":"Hello World"}')
    .then(function(obj){
      console.log(obj)
    }).catch(function(err) {
      console.log(err)
    })
```
logs 
"12-03 04:39:12.228 7289-14152/com.facebook.react.uiapp I/ReactNativeJS: [TypeError: Network request failed]
"
@Kuzmin Could you clarify what do you mean by 'silently fails', as it seems catch was invoked.

**Comment by Kuzmin** [comment]
@qbig Hm, it didn't seem to throw that error for me previously, but now that I try your example in react-native 0.15, it does in fact work and give me an error..

I looked at the file that's responsible for the Android XMLHttpRequest bridge in https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/NetworkingModule.java, and it doesn't seem that it had changed either.. 

It seems that the problem is resolved now, so this can be closed for now I guess.

**Comment by ankitpatial** [comment]
i have react native android app that gives `Network request failed` issues with url like
`fetch('https://example.com/api/resources/?scopes=new&filter={"name":"Hello World"}')`
All works ok for ios, why it has issues with android? is this something related to query string?

**Comment by Kuzmin** [comment]
You might get issues because of the JSON in the querystring. Try passing that part of the query through `encodeURIComponent()` and it might start working?

I had a similar issue on Android

**Comment by ankitpatial** [comment]
i suspect the same but the same thing works ok in iOS, i wonder why it causing issues for Android only, can it be something related to CORS ?

**Comment by Kuzmin** [comment]
The Android library for handling URLs doesn't seem to handle as many edge cases as iOS. I think it's as simple as that. Could you try wrapping sensitive parts of the url in the function call and see if it helps?

**Comment by ankitpatial** [comment]
thank you @Kuzmin i will try that.

**Comment by ankitpatial** [comment]
Yes, encodeURIComponent() does the trick.
