### ISSUE TITLE
React 0.15 Android static es6 Array methods bug [Array.from, Array.of]

### ISSUE THREAD

**Issue by Thomas101** [facebook/react-native#4385]
Hey,

Found an interesting bug. Using React 0.15 if you add any static es6 Array methods such as `Array.from` the app comes up with an `undefined is not a function` error. Interestingly though when you turn on Chrome debugging it all works fine.

I've tried this in our own app and using the blank template app and get the same results. Here are some of the methods I've tested...

`Array.from([1,2,3])` **affected**
`Array.of(1, 2, 3)` **affected**
`Array.isArray([])` es5 static methods **not affected**
`[1,2,3].findIndex(function() { return true })` es6 instance methods **not affected**
`Object.assign({}, {})` es6 static methods on object **not affected**

It seems to only be Android that is affected by this, iOS works fine. We've tested on android 4.4.2 and 6.0

Tom

**Comment by satya164** [comment]
Hey. Thanks for reporting. `Array.from` is available in RN only from `0.16.0-rc` - https://github.com/facebook/react-native/commit/c4739746ba583b4d549d1f131c6690adc5d17cd1

**Comment by ide** [comment]
cc @mkonicek updating android-jsc should fix this -- should we match iOS 9's version of JSC (in general, following the latest iOS)?

**Comment by Thomas101** [comment]
@satya164  Thanks for the heads up on 0.16!

**Comment by satya164** [comment]
Closing since these have been available for quite some time.
