### ISSUE TITLE
<Image> events are missing payload data on iOS

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#43874]
### Description

`<Image>` event payloads for `onLoad` and `onError` are missing when Fabric is enabled. For example, the `onLoad` event is missing `source` data and the `onError` event is missing `error` and `responseCode`. Confirmed as a regression on iOS but not on Android.

[Fabric implementation](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/react/renderer/components/image/ImageEventEmitter.cpp) is incomplete when compared to the [Paper implementation](https://github.com/facebook/react-native/blob/main/packages/react-native/Libraries/Image/RCTImageView.mm#L40-L48).

### Steps to reproduce

1. Log the `Image` load or error event.
2. Paper result: `e.nativeEvent.source {"height":130,"width":100,"uri":"https://reactnative.dev/img/homepage/phones.png"}`
3. Fabric result: `e.nativeEvent.source undefined`

### React Native Version

Meta Internal

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
.
```

### Stacktrace or Logs

```text
(NOBRIDGE) LOG  Image src e.nativeEvent {"target": 6232}
 (NOBRIDGE) LOG  Image src e.nativeEvent.source undefined
 (NOBRIDGE) LOG  Image source e.nativeEvent {"target": 6238}
 (NOBRIDGE) LOG  Image source e.nativeEvent.source undefined
```

### Reproducer

https://snack.expo.dev/Bgkn4S3-OCv19NbldBqc7?platform=ios

**Comment by cortinico** [comment]
Fixed by https://github.com/facebook/react-native/pull/43945
