### ISSUE TITLE
OpenSource vs Facebook Internal

### ISSUE THREAD

**Issue by alizain** [facebook/react-native#4387]
So I've been keeping up with comments on issues that affect the community, and it seems that there exists divergence between the OSS RN and Facebook's internal RN. As someone who is experimenting with using RN in production, this perceived "double-effort" is disconcerting and raises many questions. The crux of those questions boils down to one: which is of a higher priority for FB, the OSS RN or internal RN?

Timely performance updates, support, development, and everything in between is dependant on that question. Can we, the tiny one-man shops be confident we're standing solid ground, with FB's full support/vested interests?

**Comment by mkonicek** [comment]
We use the OSS RN internally and build on top of it.

For a detailed explanation see this talk (slides 45+): https://speakerdeck.com/mkonicek/under-the-hood-of-react-native

**Comment by mkonicek** [comment]
The issues that affect both fb apps and everyone else (which also tend to be the important ones) are the most likely ones to get fixed first.

See also the comment we put on every issue above, it has lots of info relevant to your question.

**Comment by chirag04** [comment]
@mkonicek's answer summarized everything. @alizain If you have more questions, let's continue the discussion on discord or stackoverflow.

**Comment by mkonicek** [comment]
:+1:

**Comment by alizain** [comment]
Thank you very much! @mkonicek @chirag04
