### ISSUE TITLE
assetRoots argument is never considered

### ISSUE THREAD

**Issue by jpapillon** [facebook/react-native#4388]
Setting assetRoots argument for 'react-native start' doesn't change a thing. This is due to these lines in 'local-cli/server/server.js':
```
args.assetRoots = args.assetRoots
    ? argToArray(args.projectRoots).map(dir =>
      path.resolve(process.cwd(), dir)
    )
    : config.getAssetRoots();
```
It's using args.projectRoots instead of args.assetRoots on second line.

**Comment by christopherdro** [comment]
@jpapillon 
Could you send a pull request with the change and reference this issue?

Thanks!
