### ISSUE TITLE
AwesomeProject/ node_modules/react-native/packager/packager.js not creating in windows 7 ?

### ISSUE THREAD

**Issue by prashanthnani** [facebook/react-native#4391]
If I run command like react-native start 
Am getting watchman error 
Watchman taking too long to load

**Comment by satya164** [comment]
Hey @prashanthnani, If you hit a `ERROR  Watcher took too long to load` on Windows, try increasing the timeout in [this file](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/FileWatcher/index.js#L17) (under your node_modules/react-native).

This will be added to the docs in #4151
