### ISSUE TITLE
[Error] UIExplorer.app on Android

### ISSUE THREAD

**Issue by sergiolepore** [facebook/react-native#4392]
I'm getting this error as soon as the Android app starts:

```
undefined is not an object (evaluating 'require('NativeModules').UIManager.RCTMap.Constants')

<unknown>
MapView.js:18

requireImpl
require.js:61

require
require.js:21

<unknown>
react-native.js:28

requireImpl
require.js:61

require
require.js:21

<unknown>
UIExplorerApp.android.js:19

requireImpl
require.js:61

requireImpl
require.js:29

require
require.js:21

<unknown>
require-UIExplorerApp.js:1
```

**Platform:**

OSX 10.11.1
react-native 0.1.7
Node 4.2.2
Genymotion Google Nexus 4 - Android 4.4.4 - API 19

**Comment by adamduren** [comment]
:+1: I'm having this same issue.

**Comment by zjaml** [comment]
Same issue here

**Comment by oppakub** [comment]
Same issue as well

**Comment by felipemartim** [comment]
me too :(

**Comment by BigMurry** [comment]
Same issue when starting the UIExplorer in the emulator.

**Comment by ide** [comment]
Fix is here: https://github.com/facebook/react-native/pull/4405

It will land in master after the author addresses the comments.

**Comment by christopherdro** [comment]
The commit for this fix has been shipped.
