### ISSUE TITLE
When will RN support Android M permissions mechanism

### ISSUE THREAD

**Issue by christocracy** [facebook/react-native#4394]
Hopefully the framework will soon provide support for modules to request and respond to the new Android permissions mechanism I'm sure we're all aware of.

Cordova has released [their implementation](http://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html) (@see "Android Permissions") and it's very nice.

Ideally, we'll be able to do something similar from within a Module, where we interact with `ReactContext` to request permissions.

**Comment by cosmith** [comment]
+1 on this, it should probably be part of core. I added a feature request on Product Pains: https://productpains.com/post/react-native/add-android-m-permissions-model-support/

**Comment by mkonicek** [comment]
Upvoted. It's also listed here: https://facebook.github.io/react-native/docs/known-issues.html

No ETA yet, we're working on open sourcing the internal modules as quickly as we can in the order of upvotes.

@christocracy I think that answers your question so I'll close this.

**Comment by mpretty-homepass** [comment]
Hey @mkonicek is there been any update on this?
