### ISSUE TITLE
Confusion as to which `Map` to use

### ISSUE THREAD

**Issue by herby** [facebook/react-native#4396]
There is `Map` that react-native uses internally and was available via `require('Map')`, OTOH, babel that processes react-native code provides its own polyfill.

The confusion leads to issues such as oney/react-native-gcm-android#4. The fix is ugly, using internal part of react-native. What is the right thing here? Should global `Map` be used, as babel's version is good enough (in that case, wouldn't it be better to just drop the react-native internal polyfill?). Should `Map` be exported by react-native (like `const {Component, ...., Map} = React;`)?

**Comment by ide** [comment]
> OTOH, babel that processes react-native code provides its own polyfill.

Could you verify this is actually the case? To my knowledge the babel-runtime plugin is excluded (https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc), so RN's Map polyfill is the only Map. You should access `Map` globally in the same way you'd access Array or Math or Promise globally.
