### ISSUE TITLE
Is `invariant` usage endorsed? If yes, how to get it?

### ISSUE THREAD

**Issue by herby** [facebook/react-native#4397]
See oney/react-native-gcm-android#4 for the problem. The module uses `invariant(...)` call, but the old `require('invariant')` is not weorking any more, and the solution (oney/react-native-gcm-android@ca9087f) is less than optimal.

Should `invariant` be used? If yes, how to obtain it right way?

**Comment by ide** [comment]
`invariant` is a private implementation detail of React Native. The public interface is whatever is exported from `require('react-native')`.
