### ISSUE TITLE
`fontVariant` doesn't work on iOS when using the new architecture

### ISSUE THREAD

**Issue by j-piasecki** [facebook/react-native#44064]
### Description

`fontVariant` prop on the `Text` component has no effect on iOS when using the new architecture.

On Android it's not applied unless `fontWeight` is also set to any value, possibly some other props but I haven't tested all of them. This behavior is consistent with the old architecture, though iOS on the old arch works correctly without setting `fontWeight`.

### Steps to reproduce

1. Install the application on Android and on iOS
2. On Android font variants specified in styles are applied only when `fontWeight` is set
3. On iOS font variants aren't applied at all

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 243.70 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.01.16.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/jakubpiasecki/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "24"
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 26.0.3
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/jakubpiasecki/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Stacktrace or Logs

```text
There are no logs
```

### Reproducer

https://github.com/j-piasecki/font-variant-repro

### Screenshots and Videos

<img width="502" alt="Screenshot 2024-04-12 at 17 56 01" src="https://github.com/facebook/react-native/assets/21055725/b6f69c02-f2bd-4ac6-b8cf-d1867b4d6d1d">
<img width="448" alt="Screenshot 2024-04-12 at 17 56 06" src="https://github.com/facebook/react-native/assets/21055725/ce894e31-9485-4eff-986a-0f3e95964a3d">

**Comment by artymir** [comment]
Same issue on 74.5
