### ISSUE TITLE
Build issues with 0.71 RNSha256 XCode 15.3

### ISSUE THREAD

**Issue by xgenem** [facebook/react-native#44060]
### Description

Incompatible function pointer types sending 'unsigned char *(const void *, CC_LONG, unsigned char *)' (aka 'unsigned char *(const void *, unsigned int, unsigned char *)') to parameter of type 'DIGEST_FUNCTION' (aka 'unsigned char (*)(const void *, unsigned int, unsigned char *)')

### Steps to reproduce

n/a

### React Native Version

0.71.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 487.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /Users/eugene/.gem/ruby/2.7.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11076708
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.22 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

n/a

### Screenshots and Videos

<img width="1512" alt="Screenshot 2024-04-12 at 9 55 36 PM" src="https://github.com/facebook/react-native/assets/3133845/af007c1b-0f3e-464c-b1b2-163aa3870cbb">

**Comment by cortinico** [comment]
@xgenem Please provide a valid reproducer

**Comment by xgenem** [comment]
Fixed at https://github.com/itinance/react-native-sha256/issues/70
