### ISSUE TITLE
I have implemented Shadow Views in Android with CardView equivalent, should I send pull request?

### ISSUE THREAD

**Issue by VansonLeung** [facebook/react-native#4406]
I think not having Shadow support for Android React Native lower than lollipop is not acceptable, so I made my shadow view today.

I am not really using CardView or support library things.
I have extracted RoundRectDrawableWithShadow.java  Drawable & set as background for ReactViewGroups.
Tested with settings corner Radius & shadow Radius, as well as margin & paddings.
Also tested both iOS + Android compatible (for iOS would be using the default style syntax)

It could be used like this:

```
<CoreShadowView cornerRadius={4} shadowRadius={4} style={[{backgroundColor: '#FFFFFF'}]}>
                <Text>D. 完全知道</Text>
</CoreShadowView>
```

<img width="621" alt="2015-11-29 7 57 00" src="https://cloud.githubusercontent.com/assets/1129695/11456893/752db9a2-96d3-11e5-98f9-e8cbfcf2d6c5.png">
<img width="621" alt="2015-11-29 7 57 12" src="https://cloud.githubusercontent.com/assets/1129695/11456894/75829e22-96d3-11e5-9a6f-d22b279a9c90.png">
<img width="423" alt="2015-11-29 8 02 17" src="https://cloud.githubusercontent.com/assets/1129695/11456906/2152b3e0-96d4-11e5-8ee8-206ff417ccef.png">

Next, I will implement my own Rounded Image View for Android as my client projects need it, which is also embarrassingly not supported.

**Comment by satya164** [comment]
Hey. Thanks for your work.

cc @mkonicek 

About rounded image view, what are you trying to achieve? Does a image with border radius not work for you?

**Comment by VansonLeung** [comment]
Should be working , but I don't know why my <Image> in Android build does not clip images inside the borderRadius bounds. Is it also occurring on your builds?

**Comment by satya164** [comment]
@VansonLeung Yes, directly setting border radius doesn't work, but it works when you wrap it in a View with same border radius

**Comment by yfsx** [comment]
how to achieve this @VansonLeung ?
can you tell how to extract that class to be implemented in react-native?
thanks!

**Comment by satya164** [comment]
Closing this since elevation has been available on Android for quite some time.

**Comment by brentvatne** [comment]
@VansonLeung - those are some pretty looking screenshots :) as @satya164 pointed out, I think this can all be done with the elevation prop, please correct us if we are wrong

**Comment by VansonLeung** [comment]
Yes, should be able to close now. The intent of this PR was just to cater Android 4.0+ devices shadow views.

**Comment by jagan-veeraraghavan** [comment]
@VansonLeung I am trying to implement the shadow views for Android 4.0+. Is it possible for the feature to be made into an npm module.

**Comment by VansonLeung** [comment]
I think yes, but it consists of a new Android Module of files and I need to figure out how to publish it.

**Comment by brentvatne** [comment]
@VansonLeung - you can check out https://github.com/brentvatne/react-native-linear-gradient and https://github.com/chirag04/react-native-mail for some simple examples of modules for React Native

**Comment by jreziga** [comment]
@satya164  Elevation only available on Android 5.X What are possibilities for Android 4.X ?

**Comment by Kishanjvaghela** [comment]
@jr-k  I have implemented CardView for react-native with elevation, that support android(All version) and iOS. Let me know is it help you or not. https://github.com/Kishanjvaghela/react-native-cardview

**Comment by Noitidart** [comment]
Wow very cool @Kishanjvaghela thank you !!

**Comment by conditionsapply** [comment]
@Kishanjvaghela this not supporting in "react-native": "0.46.4", getting an error

**Comment by Yandamuri** [comment]
@VansonLeung Does cornerRadius={4} shadowRadius={4} work for Android? I tired in Android 6.0, but didn't work. Could you suggest anything for this?
