### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by Eulerianial** [facebook/react-native#4409]
I am seeing following error:
Warning: React.renderToString is deprecated. Please use ReactDOMServer.renderToString from require('react-dom/server') instead.
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
Error: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
  at invariant (/home/vijay/SAGEMATH/smc/src/smc-webapp/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)

The JS code is extremely stable. Just wondering can this be an issue with Nodejs, NPM or react versions??

My versions are:
Nodejs: 5.2.1

**Comment by browniefed** [comment]
Resolving on discord, please close.

**Comment by ide** [comment]
Unrelated to RN.
