### ISSUE TITLE
[Packager] is a bit quiet when hitting an unrecognised image

### ISSUE THREAD

**Issue by glenjamin** [facebook/react-native#441]
There's a line here where it logs at debug

https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js#L154

But apart from that it's a tricky to figure out what's going on

**Comment by amasad** [comment]
I would love to make it more strict. We had some issues internally that stopped us from doing that. Anyways, that's on top of my list.

**Comment by brentvatne** [comment]
Protip: use the commit sha in your links so that when master changes we can still see the exact code you're referring to :smile:

**Comment by glenjamin** [comment]
Whoops! I normally do that - "y" to toggle hash in URL

**Comment by brentvatne** [comment]
@glenjamin - I did not know that shortcut, awesome!

**Comment by amasad** [comment]
nice shortcut!

**Comment by amasad** [comment]
let's merge this with #1098
