### ISSUE TITLE
textInput props textAlign will cause long text to be cut off after the hyphen when out of focus and focus again

### ISSUE THREAD

**Issue by LayMui** [facebook/react-native#44107]
### Description

textInput: When I type a very long text with a hyphen and the text exceed the view of the textInput and when I go out of focus and enter into focus again, the text after the hyphen will get cut off.
this happen for the css style textAlign props

code snippet:
<TextInput
        style={styles.input}
        textAlign={'left'}
      />

the above issue happen for all left, right and center

const styles = StyleSheet.create({

  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
..

### Steps to reproduce

create the RN app
add the code snippet to the App.tsx
import {
  TextInput
} from 'react-native';

<TextInput
        style={styles.input}
        textAlign={'center'}
      />

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
(node:33422) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 42.90 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.6.2
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
NA
```

### Reproducer

https://github.com/LayMui/textInput

### Screenshots and Videos

<img width="337" alt="Screenshot 2024-04-16 at 10 16 44 AM" src="https://github.com/facebook/react-native/assets/11436517/002d4d2a-f517-4d3e-bb2a-e4b8d40710e2">
<img width="319" alt="Screenshot 2024-04-16 at 10 17 01 AM" src="https://github.com/facebook/react-native/assets/11436517/f426a633-d9a0-4349-ad08-b3af33d6011c">

**Comment by shubhamguptadream11** [comment]
@LayMui Can you please verify this on latest RN version: `0.74.3`?

**Comment by shubhamguptadream11** [comment]
I am debugging this from a while and found out that this isn't specific to just `textAlign` prop.
Instead if we pass any props listed below the issue will arise
`baseWritingDirection, lineBreakStrategy, lineHeight, textAlign`. Common thing between these props is all are paragraphStyle props.

So what happens here is paragraphStyle will apply a default `lineBreakMode=NSLineBreakByWordWrapping`. Changing this to `NSLineBreakByTruncatingTail` will solve the issue.

Possible Solution:
- Currently we aren't exposing lineBreakMode to RN world. So we can expose `lineBreakMode` to react-native world to set this attribute as well for iOS only.

Attaching file reference(Issue happening on old and new both): 
Fabric: https://github.com/facebook/react-native/blob/91ecd7eb5330f5d725f5587744713064d614a6b3/packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTAttributedTextUtils.mm#L208
Old Arch: https://github.com/facebook/react-native/blob/91ecd7eb5330f5d725f5587744713064d614a6b3/packages/react-native/Libraries/Text/RCTTextAttributes.mm#L103

@cortinico If you think this is the correct way then I can pick it up.
Thanks

**Comment by shubhamguptadream11** [comment]
@cortinico Can you look into this once.

**Comment by cortinico** [comment]
> @cortinico Can you look into this once.

We're currently hyperfocused on New Architecture bugs only at the moment as that's our P0 priority. As this is not a New Architecture bug, we can't sadly invest time on this one at the moment.

If you wish to send a PR with the change you suggested @shubhamguptadream11 please do. I can't promise it will be merged/reviewed in a timely manner at the moment, sorry for that.

**Comment by shubhamguptadream11** [comment]
@cortinico This is happening on new architecture as well. So in order to solve this issue I am thinking of exposing `lineBreakMode` props to react-native world as well only for iOS. Let me know what are your thought on this.
Thanks for your time.

**Comment by cortinico** [comment]
> @cortinico This is happening on new architecture as well.

I understand, but is not a New Architecture regression.

**Comment by shubhamguptadream11** [comment]
@cortinico I had raised a PR here: https://github.com/facebook/react-native/pull/45968
Please check.

**Comment by shubhamguptadream11** [comment]
Fixed PR had been merged. Closing this issue.
In short we now have new prop `lineBreakModeIOS` exposed which will handle cropping strategy.
