### ISSUE TITLE
close the first modal  with animation,  then open the second modal  immediately, the second modal can't be showed

### ISSUE THREAD

**Issue by dodododooo** [facebook/react-native#44108]
### Description

close the first modal  with animation,  then open the second modal  immediately, the second modal can't be showed
if the first modal without animation, the second modal show ok;

### Steps to reproduce

close the first modal  with animation,  then open the second modal  immediately

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
empty
```

### Stacktrace or Logs

```text
empty
```

### Reproducer

empty

### Screenshots and Videos

empty

**Comment by athaljen** [comment]
Also face the same issue in iOS, In my case i use 

`InteractionManager.runAfterInteractions(() => {
      setModalVisible(true)
  })`
