### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "React-RCTAnimation":   In Podfile:     React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)

### ISSUE THREAD

**Issue by bettyrjc** [facebook/react-native#44126]
### Description

I updated react-native and pass it to me

### Steps to reproduce

pod install

### React Native Version

0.73

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1
  CPU: (8) arm64 Apple M1
  Memory: 82.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.7.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.11
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.09.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK: Not Found
  Android SDK:
    API Levels:
      - "23"
      - "29"
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
    System Images:
      - android-27 | Google APIs ARM 64 v8a
      - android-30 | Google Play ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.7
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "React-RCTAnimation":
  In Podfile:
    React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)

Specs satisfying the `React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)` dependency were found, but they required a higher minimum deployment target.

pod install --repo-update --ansi exited with non-zero code: 1
```

### Reproducer

n

**Comment by athaljen** [comment]
> ### Description
> I updated react-native and pass it to me
> 
> ### Steps to reproduce
> pod install
> 
> ### React Native Version
> 0.73
> 
> ### Affected Platforms
> Runtime - iOS
> 
> ### Output of `npx react-native info`
> ```
> System:
>   OS: macOS 14.1
>   CPU: (8) arm64 Apple M1
>   Memory: 82.16 MB / 16.00 GB
>   Shell:
>     version: "5.9"
>     path: /bin/zsh
> Binaries:
>   Node:
>     version: 20.7.0
>     path: /opt/homebrew/bin/node
>   Yarn:
>     version: 1.22.11
>     path: /opt/homebrew/bin/yarn
>   npm:
>     version: 10.1.0
>     path: /opt/homebrew/bin/npm
>   Watchman:
>     version: 2023.09.18.00
>     path: /opt/homebrew/bin/watchman
> Managers:
>   CocoaPods:
>     version: 1.14.2
>     path: /opt/homebrew/bin/pod
> SDKs:
>   iOS SDK: Not Found
>   Android SDK:
>     API Levels:
>       - "23"
>       - "29"
>       - "30"
>       - "31"
>       - "33"
>     Build Tools:
>       - 29.0.2
>       - 30.0.2
>       - 30.0.3
>       - 31.0.0
>       - 33.0.0
>       - 33.0.2
>     System Images:
>       - android-27 | Google APIs ARM 64 v8a
>       - android-30 | Google Play ARM 64 v8a
>       - android-33 | Google Play ARM 64 v8a
>       - android-34 | Google APIs ARM 64 v8a
>       - android-34 | Google Play ARM 64 v8a
>     Android NDK: Not Found
> IDEs:
>   Android Studio: 2022.2 AI-222.4459.24.2221.9971841
>   Xcode:
>     version: /undefined
>     path: /usr/bin/xcodebuild
> Languages:
>   Java:
>     version: 17.0.7
>     path: /usr/bin/javac
>   Ruby:
>     version: 2.6.10
>     path: /usr/bin/ruby
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: 18.2.0
>   react-native:
>     installed: 0.73.6
>     wanted: 0.73.6
>   react-native-macos: Not Found
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: false
>   newArchEnabled: false
> iOS:
>   hermesEnabled: Not found
>   newArchEnabled: false
> ```
> 
> ### Stacktrace or Logs
> ```
> Command `pod install` failed.
> └─ Cause: CocoaPods could not find compatible versions for pod "React-RCTAnimation":
>   In Podfile:
>     React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
> 
> Specs satisfying the `React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)` dependency were found, but they required a higher minimum deployment target.
> 
> pod install --repo-update --ansi exited with non-zero code: 1
> ```
> 
> ### Reproducer
> n
> 
> ### Screenshots and Videos
> _No response_



### Had the same issues for CocoaPods 1.14.2
### Update it to 1.15.2

`brew upgrade cocoapods`
