### ISSUE TITLE
Fatal error "available height is undefined" when editing textinput the app closes

### ISSUE THREAD

**Issue by Ivancmendoza** [facebook/react-native#44141]
### Description

This morning not everything was working perfectly, I even updated some expo libraries, specifically: expo from 15.0.14 to 15.0.17 in addition to the expo-media-library from 15.9.0 to 15.9.1 and there was no problem, When editing the textinput everything was going well, but just an hour ago this error appeared, I tried a previous version of my project and the same thing happened, I just couldn't explain it, I have seen that this problem has been around for a while but I have not seen a solution. Tanks for readme

### Steps to reproduce

https://github.com/facebook/react-native/assets/110744750/646983a3-946c-48af-95f8-548c951fb438

### React Native Version

0.73.6

### Affected Platforms

Runtime - Android, Build - Linux

### Output of `npx react-native info`

```text
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
  Memory: 2.07 GB / 7.50 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.12.2
    path: /usr/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: /usr/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: ^0.73.6
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
In the console I don't get any messages, only the Expo go app closes suddenly, I added a demonstration video where I get this error: available height is indefinite so height measure mode must be measured mode::undefined
```

### Reproducer

https://github.com/facebook/react-native/assets/110744750/646983a3-946c-48af-95f8-548c951fb438

**Comment by bernardinaquintas** [comment]
Esse erro geralmente ocorre quando usamos valores percentuais para definir a altura de elementos filhos entro de um **ScrollView** ou **FlatList** no **React Native**, tenta definir  a altura dos elementos filhos do **ScrollView** ou **FlatList** usando valores fixos. E por outra verifique compatibilidade de bibliotecas que esta a ser usada no seu projecto.
