### ISSUE TITLE
Error React Native app:checkDebugAarMetadata

### ISSUE THREAD

**Issue by FidelNR** [facebook/react-native#44177]
### Description

When I run the command `npm run android` it starts to load, but when it reaches this part it marks error, this did not happen before and I want to know what I can do to fix it, I have already checked that I have everything required in the documentation and all the correct configuration, but it keeps marking that error always. When I **run the doctor** it tells me that I have no SDK but I have installed it correctly. I have already tried uninstalling and installing the SDK and all the other components that are required but it doesn't work either.

### Steps to reproduce

1.- Open the app.
2.- Run the command

### React Native Version

0.73.7

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
  Memory: 3.62 GB / 15.74 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-232.10300.40.2321.11668458
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.73.7
    wanted: ^0.73.7
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
> inventario2@0.0.1 android
> react-native run-android

info A dev server is already running for this project on port 8081.
info Installing the app...
Starting a Gradle Daemon, 1 busy and 2 stopped Daemons could not be reused, use --status for details
> Task :app:checkDebugAarMetadata FAILED                                                                                                                                                    
11 actionable tasks: 2 executed, 9 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A build operation failed.
      Cannot snapshot output property 'outputDirectory'.
   > Cannot snapshot output property 'outputDirectory'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 53s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:checkDebugAarMetadata'. > A build operation failed. Cannot snapshot output property 'outputDirectory'. > Cannot snapshot output property 'outputDirectory'. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 1m 53s.
```

### Reproducer

https://github.com/FidelNR/inventario2.git

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/121914666/e12e5582-e67a-497b-9b7e-eb241f171563)
![image](https://github.com/facebook/react-native/assets/121914666/b12525f0-3935-4e12-8028-93d676d88ebc)

**Comment by cortinico** [comment]
This is unrelated to React Native but is a bug with Android/Gradle. See:
https://github.com/gradle/gradle/issues/24853

The solution is to remove the `android/.gradle` folder and try to build again

**Comment by FidelNR** [comment]
Thank you so much, already function my system.

**Comment by imabhishek028** [comment]
> This is unrelated to React Native but is a bug with Android/Gradle. See: [gradle/gradle#24853](https://github.com/gradle/gradle/issues/24853)
> 
> The solution is to remove the `android/.gradle` folder and try to build again

Hey, i tried it but its not working, encountering exact same error
