### ISSUE TITLE
Project with React Native SVG fails to build on 0.74.0-rc.9 with new architecture

### ISSUE THREAD

**Issue by Naturalclar** [facebook/react-native#44174]
### Description

A project using react-native 0.74.0-rc.9 fails to build with the latest react-native-svg on new architecture.

At first I thought it was a problem with react-native-svg library, but after further investigation it seems like codegen is generating incorrect typings so it maybe an issue on codegen side.

Method that's causing the build to fail has input of Double, but generated type suggests that it needs to override method with input paramter of Integer

App can be built successfully on the latest 0.73 with new architecture.

### Steps to reproduce

1. Initialize new react-native app v0.74.0-rc.9
2. install latest react-native-svg
3. on `gradle.propertires`, set `newArchitectureEnabled=true`
4. run `yarn android`

### React Native Version

0.74.0-rc.9

### Affected Platforms

Build - MacOS

### Areas

Codegen

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 355.16 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: ~/.volta/tools/image/node/20.8.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.volta/tools/image/yarn/1.22.22/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.volta/tools/image/node/20.8.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/naturalclar/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /Users/naturalclar/.asdf/shims/javac
  Ruby:
    version: 2.7.6
    path: /Users/naturalclar/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0-rc.9
    wanted: 0.74.0-rc.9
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
BUILD FAILED in 1s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/naturalclar/.ghq/github.com/Naturalclar/RN74Test/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/RNSVGRenderableManager.java:33: error: RNSVGRenderableManager is not abstract and does not override abstract method getScreenCTM(Integer) in NativeSvgRenderableModuleSpec
class RNSVGRenderableManager extends NativeSvgRenderableModuleSpec {
^
/Users/naturalclar/.ghq/github.com/Naturalclar/RN74Test/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewModule.java:21: error: SvgViewModule is not abstract and does not override abstract method toDataURL(Integer,ReadableMap,Callback) in NativeSvgViewModuleSpec
class SvgViewModule extends NativeSvgViewModuleSpec {
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':react-native-svg:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details. * Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights. BUILD FAILED in 1s.
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
╭─ ~/.ghq/github.com/Naturalclar/RN74Test [main]
```

### Reproducer

https://github.com/Naturalclar/repro-rn74-new-arch-svg-build-fail

**Comment by mensonones** [comment]
Hey, @Naturalclar! 

I downloaded your project and noticed something. View the library's **NativeSvgViewModule.ts** file

![image](https://github.com/facebook/react-native/assets/5387202/1547ec28-2fa8-450e-a703-0a777d4ee495)

Now see the same file in the library repository

https://github.com/software-mansion/react-native-svg/blob/main/src/fabric/NativeSvgViewModule.ts


I believe the problem has already been resolved, but they have not yet released a version with the correction.

If I'm wrong on something please let me know, otherwise it's been a pleasure trying to help. :)

**Comment by cortinico** [comment]
> I believe the problem has already been resolved, but they have not yet released a version with the correction.

@Naturalclar can we open an issue on react-native-svg's end to verify if this is the case?

**Comment by Naturalclar** [comment]
@cortinico 

> @Naturalclar can we open an issue on react-native-svg's end to verify if this is the case?

Sure! That would be great 👍

**Comment by cortinico** [comment]
@Naturalclar can you do it? :)

**Comment by WoLewicki** [comment]
And it is available in the newest release: https://github.com/software-mansion/react-native-svg/releases/tag/v15.2.0 :tada:
