### ISSUE TITLE
0.16 can't debug in chrome

### ISSUE THREAD

**Issue by xuchuanqiu** [facebook/react-native#4418]
When I use react-native 0.16-rc . if I "Debug in Chrome" , then App show the redbox:
![simulator screen shot 2015 11 30 11 04 29](https://cloud.githubusercontent.com/assets/870050/11462723/d1cb4f88-9752-11e5-8ad4-ef9d5de9d11e.png)

and chrome console display:
![chrome screen shot](https://cloud.githubusercontent.com/assets/870050/11462749/1e8c4458-9753-11e5-958d-d415be6feb1f.png)

**Comment by satya164** [comment]
Hey @xuchuanqiu . Thanks for the report. How did you upgrade to `0.16-rc`? Which platform are you on (iOS/Android) ?

**Comment by xuchuanqiu** [comment]
The iOS platform .  I checkout branch( master and 0.16-stable) and open Examples/Movies/Movies.xcodeproj ，the problem occurs . It's ok in branch 0.15-stable .

**Comment by satya164** [comment]
Are you trying on Emulator or device? What's the version of OS X and X Code?

**Comment by xuchuanqiu** [comment]
I am run app on iOS emulator (iPhone 6s). 
OSX version : 10.11.1
XCode version: 7.1.1

node version: 4.2.1 (and same problem in 5.0)
babel version: 6.2.0


chrome version:  46.0.2490.86 (64-bit)

**Comment by Clunt** [comment]
I have the same trouble with "document is not defined", And I am using the same version as xuchuanqiu.
But, when I visite the http://localhost:8081/debugger-ui in Safari, this problem was solve.

**Comment by mkonicek** [comment]
Just tried this with 0.16.0-rc on iOS and can't repro.

**Comment by mkonicek** [comment]
$ node --version
    v4.2.1

**Comment by skevy** [comment]
@mkonicek  I can't repro either.

This should have been fixed here: https://github.com/facebook/react-native/commit/c73809d1169dd28cfce4380710522b9baab8beed

**Comment by mkonicek** [comment]
@skevy Thanks for looking! Ben Alpert just pointed me to the same commit so it's likely that.

**Comment by mkonicek** [comment]
That commit made it to 0.16.0-rc.

**Comment by skevy** [comment]
@mkonicek no problem. I actually had that commit memorized :)

**Comment by xuchuanqiu** [comment]
@skevy It‘s OK when pick up https://github.com/facebook/react-native/commit/c73809d1169dd28cfce4380710522b9baab8beed commit. Should I close this issue.

**Comment by satya164** [comment]
@xuchuanqiu Yes, please :D

**Comment by mauron85** [comment]
I've same problem.

react-native 0.18
node v5.4.0
OSX 10.11.3
Xcode 7.2
Chrome Canary: 50.0.2628.0 canary (64-bit)

In my case exception is caught in socket.io.js lib on [this line](https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L2733)

and  exports.storage is undefined

PS: App is working normaly, when not debugging in Chrome 

```
/**
 * Load `namespaces`.
 *
 * @return {String} returns the previously persisted debug modes
 * @api private
 */

function load() {
  var r;
  try {
    r = exports.storage.debug;
  } catch(e) {}
  return r;
}
```

![image](https://cloud.githubusercontent.com/assets/359450/12530688/00a78d6c-c1e7-11e5-90bf-215b6d2b1d9d.png)
