### ISSUE TITLE
SliderIOS: minimumValue, maximumValue props ignored?

### ISSUE THREAD

**Issue by gcanti** [facebook/react-native#442]
https://github.com/facebook/react-native/blob/master/Libraries/Components/SliderIOS/SliderIOS.js#L82

```js

...

  render: function() {
    return (
      <RCTSlider
        style={[styles.slider, this.props.style]}
        value={this.props.value}
        onChange={this._onValueChange}
      />
    );
  }

...

```

**Comment by kangguru** [comment]
yea. i stumbled upon the same.

**Comment by davidgtonge** [comment]
+1 - found this also - min and max values don't work

**Comment by donyu** [comment]
Made a quick PR to fix this if you guys want to try it out. Thanks!

**Comment by benigeri** [comment]
+1 thanks for fixing it @donyu, hopefully it will be merged soon.

**Comment by brentvatne** [comment]
#583 was a good start, #835 fixes interplay between min/max value and initial value

**Comment by donyu** [comment]
@brentvatne Thanks for catching the interplay issue!
