### ISSUE TITLE
npx react-native@0.73 init cammnd installs the lattest version of react-native

### ISSUE THREAD

**Issue by sqb47** [facebook/react-native#44207]
### Description

i used the command npx react-native@0.73 init it does the initial setup of react native but when i open the package.json it shows the react native version 0.74.0

### Steps to reproduce

1. run `npx react-native@0.73 init projectName`
2. open the project and check package.json

### React Native Version

0.73

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
(node:15290) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: macOS 14.1.2
  CPU: (8) arm64 Apple M1 Pro
  Memory: 166.41 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

n/a

**Comment by okwasniewski** [comment]
You need to run `npx react-native@latest init projectName --version 0.73`

**Comment by cortinico** [comment]
> You need to run `npx react-native@latest init projectName --version 0.73`

That's the correct answer 👍

**Comment by sqb47** [comment]
> You need to run `npx react-native@latest init projectName --version 0.73`

now i feel stupid for not reading the documentation carefully
thanks for the help

**Comment by 4sskick** [comment]
> You need to run `npx react-native@latest init projectName --version 0.73`

I do this command, and got 
npx: installed 556 in 32.619s
Unexpected token '?'
![image](https://github.com/facebook/react-native/assets/7526887/18841805-bda1-4c1d-a78e-c79138825f15)
