### ISSUE TITLE
Unable to install signed apk

### ISSUE THREAD

**Issue by kenny1har** [facebook/react-native#4421]
After successfulyl running 
./gradlew assembleRelease
```
BUILD SUCCESSFUL

Total time: 15.842 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html
```

I put the "app-release.apk" into the phone, and tried to install it using File Browser. The app icon is showing nowhere.
"App not installed"
![screenshot_2015-11-30-16-04-56-819](https://cloud.githubusercontent.com/assets/1797207/11466509/4cce05ee-977c-11e5-90b3-ef9d9fbad591.jpeg)

**Comment by satya164** [comment]
Do you have the debug version installed? In that case, you'll need to uninstall it first.

**Comment by satya164** [comment]
Closing as no reply from author.

**Comment by clucasalcantara** [comment]
satya164 I've uninstalled the debug apk, configured the singin properties and generated a new keystore and a new signed apk but i'm still getting the same error while installing the apk on device or emulator.

**Comment by metallurgical** [comment]
`.....................................
......................................
bundle: start
bundle: finish
bundle: Writing bundle output to: C:\reactnative\MAFIH\android\app\build\intermediates\assets\release\index.android.bundle
bundle: Done writing bundle output
bundle: Copying 7 asset files
bundle: Done copying assets
                                                                                                                       :app:processReleaseManifestessReleaseManifest
:app:processReleaseResources
:app:generateReleaseSources
:app:incrementalReleaseJavaCompilationSafeguard
:app:compileReleaseJavaWithJavac
:app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources
:app:lintVitalRelease
:app:transformClassesWithDexForRelease
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:app:mergeReleaseJniLibFolders
:app:transformNative_libsWithMergeJniLibsForRelease
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease
:app:packageRelease
:app:assembleRelease

BUILD SUCCESSFUL

Total time: 3 mins 33.801 secs`

Same here. Build process success, but failing to install.

**Comment by fraazhashmi** [comment]
Did you forget adding this line to `build.grade` by any chance?

`signingConfig signingConfigs.release`
