### ISSUE TITLE
import module can not destructor

### ISSUE THREAD

**Issue by hufeng** [facebook/react-native#4423]
for example,
```javascript
import React, {
  View,
  StyleSheet,
  addons: {PureRenderMixin}
} from 'react-native';
```

2015-11-30 17:26:25.916 [error][tid:main] SyntaxError  ... index.js: Unexpected token (4:8)

**Comment by skevy** [comment]
Hi @hufeng - destructuring within an import is not supported by the Babel or the ES6 module syntax, and thus is out of scope of React Native.

You can try it for yourself here: http://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=import%20React%2C%20%7B%0A%20%20View%2C%0A%20%20StyleSheet%2C%0A%20%20addons%3A%20%7BPureRenderMixin%7D%0A%7D%20from%20'react-native'%3B

Instead, you'd need to do:

```javascript
import React, { 
  View,
  StyleSheet,
  addons
} from 'react-native';

const { PureRenderMixin } = addons;
```

Let us know if you have anymore questions.

Thanks!
-Adam

**Comment by hufeng** [comment]
@skevy  thank you very much.
