### ISSUE TITLE
onPress work one time only

### ISSUE THREAD

**Issue by pigeonmal** [facebook/react-native#44245]
### Description

I try to create my bottom sheet.
onPress work only one time, when pressable component is in root. Sometimes it's just the first time click, sometimes is after many clicks, and after does not work anymore.
onPressIn work perfectly

The bug is on v0.73.7 (new arch, bridgless false) and v0.74.0 (new arch, bridgless true), tested only on Android. 

### Steps to reproduce

(TEST ON ANDROID, v0.73.7, and v0.74.0, new arch)
1. Create component (BottomOption), that show only with state true, with pressable for testing
2. In App component, add BottomOption inside GestureHandlerRootView.
3. Click pressable inside screen, that change visible state of BottomOption.
4. Try click pressable of BottomOption.

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: "(2) x64 AMD Athlon Silver 3050U with Radeon Graphics   "
  Memory: 426.10 MB / 3.42 GB
Binaries:
  Node:
    version: 18.19.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
No crash or failure in logs

I try debug onPress call with console.log("TEST");

as onPress doesn't call, console.log too.
```

### Reproducer

github.com/pigeonmal/react-native-onpress-bug

### Screenshots and Videos

This is video of my app.
Normally it's like the reproducer.

https://github.com/facebook/react-native/assets/40658543/408b7987-8291-4c71-a465-ec481ade907b

**Comment by mensonones** [comment]
> ### Descrição
> Tento criar minha folha de baixo. onPress funciona apenas uma vez, quando o componente pressionável está na raiz. Às vezes é apenas o primeiro clique, às vezes depois de muitos cliques e depois não funciona mais. onPressIn funciona perfeitamente
> 
> O bug está na v0.73.7 (novo arco, bridgless falso) e v0.74.0 (novo arco, bridgless verdadeiro), testado apenas no Android.
> 
> ### Passos para reproduzir
> (TESTE NO ANDROID, v0.73.7 e v0.74.0, novo arco)
> 
> 1. Criar componente (BottomOption), que mostra apenas com estado verdadeiro, com pressionável para teste
> 2. No componente App, adicione BottomOption dentro de GestureHandlerRootView.
> 3. Clique em pressionável dentro da tela, que altera o estado visível de BottomOption.
> 4. Tente clicar pressionável em BottomOption.
> 
> ### Versão nativa do React
> 0,74,0
> 
> ### Plataformas afetadas
> Tempo de execução - Android
> 
> ### Saída de`npx react-native info`
> ```
> System:
>   OS: Windows 10 10.0.19045
>   CPU: "(2) x64 AMD Athlon Silver 3050U with Radeon Graphics   "
>   Memory: 426.10 MB / 3.42 GB
> Binaries:
>   Node:
>     version: 18.19.1
>     path: C:\Program Files\nodejs\node.EXE
>   Yarn:
>     version: 1.22.22
>     path: ~\AppData\Roaming\npm\yarn.CMD
>   npm:
>     version: 10.2.4
>     path: C:\Program Files\nodejs\npm.CMD
>   Watchman: Not Found
> SDKs:
>   Android SDK: Not Found
>   Windows SDK: Not Found
> IDEs:
>   Android Studio: Not Found
>   Visual Studio: Not Found
> Languages:
>   Java: 17.0.10
>   Ruby: Not Found
> npmPackages:
>   "@react-native-community/cli": Not Found
>   react:
>     installed: 18.2.0
>     wanted: 18.2.0
>   react-native:
>     installed: 0.74.0
>     wanted: 0.74.0
>   react-native-windows: Not Found
> npmGlobalPackages:
>   "*react-native*": Not Found
> Android:
>   hermesEnabled: true
>   newArchEnabled: true
> iOS:
>   hermesEnabled: Not found
>   newArchEnabled: Not found
> ```
> 
> ### Stacktrace ou registros
> ```
> No crash or failure in logs
> 
> I try debug onPress call with console.log("TEST");
> 
> as onPress doesn't call, console.log too.
> ```
> 
> ### Reprodutor
> github.com/pigeonmal/react-native-onpress-bug
> 
> ### Capturas de tela e vídeos
> Este é o vídeo do meu aplicativo. Normalmente é como o reprodutor.
> 
>  Registro_2024-04-24-22-06-44.mp4

Hey, @pigeonmal! Create a valid reproduction! I tried to adjust some things, but it still couldn't run.

![image](https://github.com/facebook/react-native/assets/5387202/b916f7a6-3600-4cd2-8b03-55d8ec3ac145)

![876e5210-a590-45ba-b61f-9e245989ee2a](https://github.com/facebook/react-native/assets/5387202/55e59514-0c4c-40a6-b4ad-8bd9b6b942f4)

When the example is ok, it will be a pleasure to try to help.

**Comment by necmettindev** [comment]
I think it is about "react-native-animated" not the react-native.
