### ISSUE TITLE
[ListView] Not updating as expected

### ISSUE THREAD

**Issue by asimparvez91** [facebook/react-native#4425]
Hi, I have been using list view in my application.  It does not update the state of individual rows once I have changed their property. I am doing it like this:
  
```js
  rowData.showMenuDiv =  !rowData.showMenuDiv;
  this.setState({ dataSource : this.state.dataSource });
```

But only the first row responds correctly and the rest are not updated correctly. I have also tried making a new array and assigning it like:

```js
 rowData.showMenuDiv =  !rowData.showMenuDiv;
 var newArray = oldDataArray.splice()
 this.setState({ dataSource : dataSource.cloneWithRows(newArray) });
```

But this didn't work at all.

The only solution that is working, is by creating a new data source and assigning it the updated array
like:

```js
  rowData.showMenuDiv = !rowData.showMenuDiv;
 var dataSource = new ListView.DataSource
                              ( {rowHasChanged: (r1, r2) => ( r1.showMenuDiv != r2.showMenuDiv )});
  this.setState({ dataSource : dataSource.cloneWithRows(oldDataArray) });
```

Please explain if I am doing any thing wrong in the top two methods. Or the method I am using to update rows is correct (the last method)?

**Comment by slmille4** [comment]
Is this considered a bug? It seems to be a pretty common problem
http://stackoverflow.com/questions/33436902/how-force-redraw-listview-when-this-state-changed-but-not-the-datasource
http://stackoverflow.com/questions/33426760/react-native-listview-not-updating-on-data-change
