### ISSUE TITLE
close development mode in android

### ISSUE THREAD

**Issue by haledeng** [facebook/react-native#4428]
In android, when I set 
```
__DEV__ = false
```
 in bundle file , the whole page shows blank.
I saw there are many logic to detect `__DEV__`, does it effect the page display.

**Comment by satya164** [comment]
Hey @haledeng , you don't have to set `__DEV___` directly? The bundle command will do it automatically for you.

e.g.- 

```sh
react-native bundle --platform android --dev false --entry-file index.android.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/src/main/res/
```

**Comment by haledeng** [comment]
I try, it does not work. `__DEV__`  is still true.
Besides, while `__DEV__ = false`,  the whole page shows empty.

**Comment by satya164** [comment]
@haledeng Can you try with the latest React Native and see if it's fixed?

**Comment by satya164** [comment]
@haledeng Any updates?

**Comment by satya164** [comment]
Closing since no response. Let's re-open if you're still having the issue.
