### ISSUE TITLE
It is possible to break the docs site and have it still publish

### ISSUE THREAD

**Issue by glenjamin** [facebook/react-native#443]
When https://github.com/facebook/react-native/pull/433 was merged, the build ran and published an updated docs site, but every page ended up displaying a stack trace.

This should probably get caught during the travis build and not publish.

**Comment by glenjamin** [comment]
![2015-03-29 17 57 46](https://cloud.githubusercontent.com/assets/151272/6886256/3a640ab2-d62e-11e4-8d08-0a1051d0a8a3.png)

here's what it looked like.

**Comment by brentvatne** [comment]
I believe that this is protected against now, thanks for the issue @glenjamin!
