### ISSUE TITLE
Can't display Image with source as required()

### ISSUE THREAD

**Issue by SmileHub** [facebook/react-native#44314]
### Description

Couldn't include images with source targeting the required() includes such as:

## Description
As I've encountered the same issue with my own code where image doesn't get loaded if it's loading from "required" source, i went into the official documentation.

Inside the docs [https://reactnative.dev/docs/image](https://reactnative.dev/docs/image) there are only 2 images out of coded 3 images loaded. This image isn't loaded as well:

`      
<Image
        style={styles.tinyLogo}
        source={require('@expo/snack-static/react-native-logo.png')}
      />
`

resulting a missing image:

![image](https://github.com/facebook/react-native/assets/8821939/50fbf1ff-7f66-4bea-8f24-c85cff3e7629)

As seen in source, the image isn't even added to the sources (same thing i encounter in my app):

![image](https://github.com/facebook/react-native/assets/8821939/e5bfcc33-a360-489c-a2f2-ccbc3b0e86ce)

## Documentation version
0.74

## Extra information:
Recreated same behavior with my react environment.

### React Native Version

0.73.6

### Affected Platforms

Runtime - Web, Build - Windows

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 5600H with Radeon Graphics         "
  Memory: 2.26 GB / 13.86 GB
Binaries:
  Node:
    version: 20.11.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-221.6008.13.2211.9619390
  Visual Studio: Not Found
Languages:
  Java:
    version: 19.0.2
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.74.0 is now available (your project is running on v0.73.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.74.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.0
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
```

### Stacktrace or Logs

```text
It's a runtime visual non-rendering without a crash.
```

### Reproducer

https://reactnative.dev/docs/image

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/8821939/632558fd-328b-45fb-84be-0b29f7a0875f)
![image](https://github.com/facebook/react-native/assets/8821939/2fd825dd-b05f-4744-b2ce-8f10782ec3d7)

**Comment by NickGerleman** [comment]
Is this specific to react-native-web?

**Comment by SmileHub** [comment]
No, same behavior on android and same on web: image doesn't get displayed:
![image](https://github.com/facebook/react-native/assets/8821939/a059755a-28e5-4fdc-a1b8-8d32d06c3dcd)

**Comment by muhammadalizkhan** [comment]
is this is react-native-web?

**Comment by abhinav-22-tech** [comment]
> No, same behavior on android and same on web: image doesn't get displayed: ![image](https://private-user-images.githubusercontent.com/8821939/326739339-a059755a-28e5-4fdc-a1b8-8d32d06c3dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjQzODAsIm5iZiI6MTcxNDU2NDA4MCwicGF0aCI6Ii84ODIxOTM5LzMyNjczOTMzOS1hMDU5NzU1YS0yOGU1LTRmZGMtYTFiOC04ZDMyZDA2YzNkY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMTE0ODAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM3YmY5NDU3YjU0Y2IwNzk2YzVmMGEyMzA1MzMzYTgyNWZkZDM3ZmFkOTE4NjRhYzJiYWU4NTM2MzYzMGY0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yo6f98D569AbvENS7JQ7lKOEY-DF6LC0TgneD0AFbVU)

Android working fine for me. 
But on web image is not visible.

**Comment by AliRehman7141** [comment]
I'm using React Native ("react-native": "0.75.3") in two different projects. In one project, importing or requiring images works, but in the second project, nothing is displayed.
