### ISSUE TITLE
Attempted to assign to readonly property

### ISSUE THREAD

**Issue by bozzmob** [facebook/react-native#4432]
I am trying to check if the entry exists in the AsycStore and if it doesn't exist then, I create an object and set it. And there is a return statement that returns the dataobject.

Here is the pseudocode-
```
AsyncStorage.getItem("dataobject").then((do) => {
  if(do == undefined)
  {
    console.log("initializing obj + setting data");
    var dobj = "data object";
    dobj.isdirty = true;
    AsyncStorage.setItem("dataobject",dobj);
  }
  return AsyncStorage.getItem("dataobject");
}).done();
},

```

I am getting an error in console -
```
W/ReactNativeJS: 'Error: Attempted to assign to readonly property.\n stack: \n  <unknown>

index.android.bun…:53047\n  tryCallOne                           
index.android.bun…:5094\n  <unknown>                            
index.android.bun…:5160\n  <unknown>                            
index.android.bun…:3399\n  callTimer                            
index.android.bun…:2954\n  callImmediates                       
index.android.bun…:3003\n  <unknown>                            
index.android.bun…:2523\n  guard                                
index.android.bun…:2452\n  __callImmediates                     
index.android.bun…:2523\n  <unknown>                            
index.android.bun…:2503\n  guard                                
index.android.bun…:2452\n  invokeCallbackAndReturnFlushedQueue  index.android.bun…:2501\n URL: http://localhost:8081/index.android.bundle?platform=android&dev=true\n line: 53047\n message: Attempted to assign to readonly property.'
```
I am not really sure what is the readonly property I am trying to assign. The line number that is being warned is this line - "dobj.isdirty = true";

Should I not add a property to an object? How do I solve this problem? What's the right way of doing it?

Screenshot-
![reactnativeerror](https://cloud.githubusercontent.com/assets/1252941/11475865/aa8983a6-97a5-11e5-8e30-b1d09a132dd1.png)

**Comment by bozzmob** [comment]
I made a [stackoverflow](http://stackoverflow.com/questions/33999948/react-native-attempted-to-assign-to-readonly-property) question for the same. Please help me with this for now.

**Comment by satya164** [comment]
@bozzmob You're trying assign a property to a string (a primitive). Strings are read-only and you cannot add a property to string.

Normally, nothing happens, but since you're in strict mode, this throws an error.

**Comment by bozzmob** [comment]
Yes. Thanks @satya164 ! :+1:
