### ISSUE TITLE
npm can't find tesseract-ocr

### ISSUE THREAD

**Issue by HarryDaWin** [facebook/react-native#44343]
### Description

npx react-native init testing123

npm ERR! code ENOENT
npm ERR! syscall spawn C:\Program Files\Tesseract-OCR;
npm ERR! path C:\Users\harri\match
npm ERR! errno -4058
npm ERR! enoent spawn C:\Program Files\Tesseract-OCR; ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

### Steps to reproduce

1. Install Node js
2. Added to environment variable
3. Tried running npx react-native init testing123 then error popped up

### React Native Version

latest

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
npm ERR! code ENOENT
npm ERR! syscall spawn C:\Program Files\Tesseract-OCR;
npm ERR! path C:\Users\harri\match
npm ERR! errno -4058
npm ERR! enoent spawn C:\Program Files\Tesseract-OCR; ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Stacktrace or Logs

```text
npm ERR! code ENOENT
npm ERR! syscall spawn C:\Program Files\Tesseract-OCR;
npm ERR! path C:\Users\harri\match
npm ERR! errno -4058
npm ERR! enoent spawn C:\Program Files\Tesseract-OCR; ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

### Reproducer

none

**Comment by NickGerleman** [comment]
This error is unrelated to React Native unfortunately
