### ISSUE TITLE
[TextInput] Setting secureTextEntry={true} forces input text to color:#000

### ISSUE THREAD

**Issue by slavik0329** [facebook/react-native#4435]
There doesn't seem to be anything I can do to get it to the set style color. This only happens when secureTextEntry is true.

**Comment by sankhadeeproy007** [comment]
Is there a solution for this yet?

**Comment by shubhamgautam** [comment]
any solution yet ?

**Comment by christopherdro** [comment]
Could you try replacing `secureTextEntry` with `password`.

**Comment by wv1124** [comment]
any idea?

**Comment by 9mm** [comment]
Also maybe changing the font would be nice... it looks weird as a different font.

**Comment by mkonicek** [comment]
Pull requests welcome :)

**Comment by mkonicek** [comment]
Commented on the PR.

**Comment by adamrainsby** [comment]
I think this issue is resolved in 0.23.0?

**Comment by grabbou** [comment]
That's true, implement in PRs linked above.
