### ISSUE TITLE
Sending events to JS from Swift across the bridge

### ISSUE THREAD

**Issue by chris-erickson** [facebook/react-native#4436]
Is this something that should be possible to do?  I'm struggling finding any concrete details on it, and would love some feedback from the community.  I realize this isn't the ideal forum for such a thing, but questions go unanswered elsewhere.  See my question [on SO](https://stackoverflow.com/questions/31870775/react-native-sending-events-to-javascript-in-swift).  I'll keep that updated if I find a resolution.

**Comment by ide** [comment]
You can do this with RCTDeviceEventEmitter for example. See https://facebook.github.io/react-native/docs/native-components-ios.html#events. (The example is in Obj-C. It's usually simple to write the equivalent Swift code though.)
