### ISSUE TITLE
React Native requires XCode >= 14.3. Found 14.2

### ISSUE THREAD

**Issue by shahjahanpak** [facebook/react-native#44384]
### Description

Initialising a new project and running `pod install ` throws this error

```sh
React Native requires XCode >= 14.3. Found 14.2.

[!] Invalid `Podfile` file: Please upgrade XCode.

 #  from project/ios/Podfile:20
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------
```

### Steps to reproduce

1. npx react-native@latest init AwesomeProject
2. cd AwesomeProject/ios
3. pod install

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: macOS 12.7.4
  CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Memory: 152.50 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.03.18.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mac/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
$ /Users/mac/.nvm/versions/node/v20.11.1/bin/node -p require.resolve(     "react-native/scripts/react_native_pods.rb",     {paths: [process.argv[1]]},   )
  /Users/mac/Desktop/projects/AwesomeProject/ios
  /Users/mac/Desktop/projects/AwesomeProject/node_modules/react-native/scripts/react_native_pods.rb
  $ /Users/mac/.nvm/versions/node/v20.11.1/bin/node -p require.resolve(     "@react-native-community/cli-platform-ios/native_modules.rb",     {paths:
  [process.argv[1]]},   ) /Users/mac/Desktop/projects/AwesomeProject/node_modules/react-native/scripts
  /Users/mac/Desktop/projects/AwesomeProject/node_modules/@react-native-community/cli-platform-ios/native_modules.rb
  $ /Users/mac/.nvm/versions/node/v20.11.1/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e)
  {console.log(require('react-native/cli').bin);}
  /Users/mac/Desktop/projects/AwesomeProject/node_modules/@react-native-community/cli/build/bin.js
React Native requires XCode >= 14.3. Found 14.2.

[!] Invalid `Podfile` file: Please upgrade XCode.

 #  from /Users/mac/Desktop/projects/AwesomeProject/ios/Podfile:20
 #  -------------------------------------------
 #  
 >    use_react_native!(
 #      :path => config[:reactNativePath],
 #  -------------------------------------------

/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `new'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

### Reproducer

https://github.com/shahjahanpak/AwesomeProject

### Screenshots and Videos

<img width="1101" alt="Screenshot 2024-05-02 at 11 43 17 AM" src="https://github.com/facebook/react-native/assets/47810605/7778011d-eee8-4dcf-a71f-64af12662ef3">

**Comment by cortinico** [comment]
> React Native requires XCode >= 14.3. Found 14.2.

The error is self explanatory: you need to update XCode version.
Please update XCode version and get back to use if the issue persists

**Comment by HunnySajid** [comment]
> > React Native requires XCode >= 14.3. Found 14.2.
> 
> The error is self explanatory: you need to update XCode version. Please update XCode version and get back to use if the issue persists

The problem is xcode 14.3 requires MacOS 13.3, my current macbook only offers an update to MacOS 12.7.4.
Is there a way I can run react-native without making these updates? 
Maybe downgrading the react-native to a specific version...

**Comment by DanTol-cloud** [comment]
The same issue exactly is there any solution for this?

> > > React Native requires XCode >= 14.3. Found 14.2.
> > 
> > 
> > The error is self explanatory: you need to update XCode version. Please update XCode version and get back to use if the issue persists
> 
> The problem is xcode 14.3 requires MacOS 13.3, my current macbook (MacBook Pro (Retina, 15-inch, Mid 2015)) only offers an update to MacOS 12.7.4. Is there a way I can run react-native without making these updates? Maybe downgrading the react-native to a specific version...

The same issue exactly. Is there a solution?

**Comment by cortinico** [comment]
Nope sorry. Those limitations are imposed by Apple and outside our control

**Comment by mustafaerken** [comment]
I have same issue:

Device:           MacBook Pro (Retina, 15-inch, Mid 2015).
macOS:          12.7.4 (Monterey).
xCode:           14.2 (This is the last version for my MacBook Pro 2015.).
ReactNative:  I tried 0.71.7 and 0.74.1

There is a problem when we open projects or pod install.

**Comment by mustafaerken** [comment]
I fixed my problem with making new project with;

npx react-native init App01 --version 0.71.7

I hope this helps.

**Comment by HunnySajid** [comment]
> I fixed my problem with making new project with;
> 
> npx react-native init App01 --version 0.71.7
> 
> I hope this helps.

It also worked for me once I downgraded react-native to 0.71.7
Thank you

**Comment by Rajavicky07** [comment]
> I fixed my problem with making new project with;
> 
> npx react-native init App01 --version 0.71.7
> 
> I hope this helps.

how to show this issue my xcode version 14.1 i couldn't install 14.3 xcode version

**Comment by mustafaerken** [comment]
> > I fixed my problem with making new project with;
> > npx react-native init App01 --version 0.71.7
> > I hope this helps.
> 
> how to show this issue my xcode version 14.1 i couldn't install 14.3 xcode version is helps npx react-native init App01 --version 0.71.7 ?

We couldn't also install xCode 14.3 so this helped us.
It should also help for you if you have similar problem.

**Comment by mustafaerken** [comment]
> Nope sorry. Those limitations are imposed by Apple and outside our control

You just giving easy answer to the people and not helping them.
Answer was simple to someone who knows ReactNative well.
It should be more easy for you.

If this is your job you are not good worker.
Be a better human and do your job.

**Comment by herhu** [comment]
> Nope sorry. Those limitations are imposed by Apple and outside our control

Hello , solution  provided is buy a new MacBook but sometimes this is not too easy and many of us we want to develop in this case the Max solution from apple is use Xcode 14.2 and here RN we have to guess it because is not a version I can use ?

**Comment by yminfosys** [comment]
npx react-native init App01 --version 0.71.7

it works for me

thanks

**Comment by dipo1** [comment]
Version 0.73.7 also works. I think it is the last version before deprecating XCode 14.2.
`npx @react-native-community/cli@latest init --version=0.73.7`

IMO, the rationale for deprecating XCode 14.2 is not sufficient. MacOS Monterey will no longer be compatible with recent React Native versions and that also means any MacBook Pro released before 2017.

See the commit message.
https://github.com/facebook/react-native/commit/1021448d7cf462d5280ce82f484f029fd29e40a6

If you don't mind the "cryptic error", you can bypass this by changing the `min_xcode_version_supported` value in `node_modules/react-native/scripts/cocoapods/helpers.rb line 41

Such a big sacrifice for a small feature.

**Comment by iamunadike** [comment]
the saving grace is a fix called open-core patcher, yes perhaps you dont want to upgrade your macbook but want the latest os and do this and do that, Yes you can with Open-core patcher you can run the latest mac os on that old system it works even for Mac OS 10 and so on .so give it a shot , you can send me a tip and follow me as well if you liked this
