### ISSUE TITLE
Live reload eats CPU

### ISSUE THREAD

**Issue by danawoodman** [facebook/react-native#444]
When I run live reload on my iOS app in the emulator (iPhone 5s simulation), the CPU jumps to about 170%. If I leave it open the simulator just freezes and I have to force quit it. Not sure if this is a know issue or if there is a way to work around it.

I'm on a 15" MacBook Pro Retina FWIW.

**Comment by sahrens** [comment]
Can you tell which processes are eating the most CPU?

**Comment by jaygarcia** [comment]
I've never seen this, even when i've done hideous things like tax the OBJC JS bridge in a 10ms endless loop, querying for 512 floats ;).

Can you post code to replicate this?

FWIW, I am on a 2012 15" MBP Retina also.

**Comment by frantic** [comment]
Can you also include packager logs, your node version, etc.? Live reload uses long-polling and should not be causing this. Do you have watchman installed, `watchman --version`?

**Comment by jaygarcia** [comment]
I've still not had this issue :(.

**Comment by danawoodman** [comment]
Not able to reproduce, if I am, I'll reopen with details!

**Comment by jaygarcia** [comment]
@danawoodman Please close if this is no-longer a current issue. =)

**Comment by danawoodman** [comment]
Whoops, thought I did. Thanks!

**Comment by grabbou** [comment]
Still an issue here...

No livereload:
![screen shot 2015-06-09 at 09 18 16](https://cloud.githubusercontent.com/assets/2464966/8052520/8a414206-0e88-11e5-9cd5-abdbdb901fd2.png)

With livereload 10 seconds after:
![screen shot 2015-06-09 at 09 18 29](https://cloud.githubusercontent.com/assets/2464966/8052529/921655fc-0e88-11e5-9287-36636d11b8c9.png)
