### ISSUE TITLE
[0.74.0] Missing concurrentRoot in initialProps on android new architecture 

### ISSUE THREAD

**Issue by FightFarewellFearless** [facebook/react-native#44404]
### Description

The concurrentRoot is missing from initialProps on new architecture enabled. Look at this:
![image](https://github.com/facebook/react-native/assets/83485510/0641e9b4-01c9-404f-a166-2f11e8ed6bbf)

And when im using concurrent features such as startTransition, this error comes out:
![image](https://github.com/facebook/react-native/assets/83485510/163ae4c8-7f8d-47dd-b486-cd92d8f5f561)
![image](https://github.com/facebook/react-native/assets/83485510/69b3b812-b19c-41ce-9607-67f1dc9e98ac)

This error also persists in expo sdk 51

### Steps to reproduce

1. Run the app with `npm run android`
2. Check the error on console

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android

### Areas

Fabric - The New Renderer, Other (please specify)

### Output of `npx react-native info`

```text
System:
  OS: Linux 5.15 Linux Mint 21.3 (Virginia)
  CPU: (4) x64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
  Memory: 2.48 GB / 11.66 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.5.1
    path: ~/.nvm/versions/node/v20.5.1/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.5.1/bin/yarn
  npm:
    version: 9.8.0
    path: ~/.nvm/versions/node/v20.5.1/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
(NOBRIDGE) ERROR  TypeError: Cannot read property 'add' of undefined

This error is located at:
    in Section (created by App)
    in RCTView (created by View)
    in View (created by App)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in concurrentrootproblem(RootComponent)
```

### Reproducer

https://github.com/FightFarewellFearless/concurrentrootproblem

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/83485510/c032a3ab-4e57-4b57-9611-5d6e4112b861)

**Comment by cortinico** [comment]
That's expected because the `concurrentRoot` value has been hardcoded to true, so we won't be printing it on screen anymore.

**Comment by FightFarewellFearless** [comment]
> That's expected because the `concurrentRoot` value has been hardcoded to true, so we won't be printing it on screen anymore.

What about the error i mention?

**Comment by tmitchel2** [comment]
I get this same error "Cannot read property 'add' of undefined" when trying to use startTransition and make a state update.  Is startTransition supported?

**Comment by FightFarewellFearless** [comment]
> I get this same error "Cannot read property 'add' of undefined" when trying to use startTransition and make a state update. Is startTransition supported?

Use `useTransition` works, don't use startTransition from react directly, use it from useTransition hook
