### ISSUE TITLE
How to replace NativeModules.SourceCode under Fabric architecture?

### ISSUE THREAD

**Issue by sailor1861** [facebook/react-native#44418]
### Description

Hello,

I'm currently transitioning to the new React Native Fabric architecture and I'm looking for a way to replace the functionality provided by `NativeModules.SourceCode`. In the legacy architecture, we used `NativeModules.SourceCode` to obtain information about the running JS bundle, such as its URL.

Could you please provide guidance or point me towards the recommended approach for accessing this kind of information within the context of the Fabric architecture? Is there a new API or an alternative method that we should use now?

Thank you for your assistance.

Best regards,

### Steps to reproduce

console.log("NativeModules.SourceCode:" + NativeModules.SourceCode + "; scriptURL" + NativeModules.SourceCode.scriptURL);

### React Native Version

0.72.5

### Affected Platforms

Runtime - Android

### Areas

TurboModule - The New Native Module System

### Output of `npx react-native info`

```text
nfo Fetching system and libraries information...
System:
  OS: macOS 12.5
  CPU: (8) arm64 Apple M1 Pro
  Memory: 106.81 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/node/node-16.20.1/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 9.8.0
    path: ~/node/node-16.20.1/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 15.5
      - macOS 12.3
      - tvOS 15.4
      - watchOS 8.5
  Android SDK:
```

### Stacktrace or Logs

```text
ERROR  TypeError: null is not an object (evaluating '_reactNative.NativeModules.SourceCode.scriptURL')
```

### Reproducer

 https://git.corp.com/GP_APPMAIN_RN/react-native-auto.git

**Comment by tarunrajput** [comment]
@sailor1861 , try using 
```javascript
SourceCode.getConstants().scriptURL
```

**Comment by tarunrajput** [comment]
try using TurboModuleRegistry.getEnforcing<Spec>('SourceCode').getConstants().scriptURL or SourceCode.getConstants().scriptURL

**Comment by sailor1861** [comment]
TurboModuleRegistry.getEnforcing('SourceCode').getConstants().scriptUR is OK；thanks @arunrajput
