### ISSUE TITLE
Layout inspector shows wrong frames when using `DrawerLayoutAndroid`

### ISSUE THREAD

**Issue by j-piasecki** [facebook/react-native#44425]
### Description

When using the layout inspector alongside `DrawerLayoutAndroid`, the drawer content is always selectable, even if the drawer is closed. It's also always positioned as if the drawer is on the left.

### Steps to reproduce

1. Open layout inspector
2. Tap around the screen
3. The content of the drawer is selectable even though it's closed

### React Native Version

0.75.0

### Affected Platforms

Runtime - Android

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 124.63 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.01.16.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/jakubpiasecki/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "24"
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 26.0.3
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/jakubpiasecki/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Stacktrace or Logs

```text
This is a visual bug
```

### Reproducer

https://snack.expo.dev/@jpiasecki/drawer-android-inspector-bug

### Screenshots and Videos

https://github.com/facebook/react-native/assets/21055725/398745ba-ec5f-4dab-9e66-2770058636ae

https://github.com/facebook/react-native/assets/21055725/ca2b1a5f-0c53-4b96-9493-8a47647ff1ac

**Comment by DrZoidberg09** [comment]
The same happens to me with custom overflow buttons using Reanimated that open a selection. These buttons a pressable in the position the would be, if opened, even in closed state. Also happens only on Android. 

Happy to open another issue, if you think this is unrelated.

**Comment by realsoelynn** [comment]
I have PR https://github.com/facebook/react-native/pull/44707 to fix this issue from JS Side.

The reason this type of issue surfacing in New Architecture is that `View` are not set with [relevant `pointerEvents`](https://reactnative.dev/docs/view#pointerevents) to identify if it can accept pointer events. This is one of the key differences between old and new architecture where Node is found by querying through ShadowNode instead of relying on Native Platform View click event to get React Root Tag to identify Node for the Inspector Tools.

@DrZoidberg09 issue can be solved with same approach by setting appropriate `pointerEvents` to be `box-only`, `box-none` or `none`

To go more in-depth around this, this is a good PR https://github.com/facebook/react-native/pull/44327 to reference.

**Comment by DrZoidberg09** [comment]
@realsoelynn Awesome! That did the trick. Thanks!

**Comment by cipolleschi** [comment]
Good! Let's close this issue as soon as https://github.com/facebook/react-native/pull/44707 lands, what do you think?

**Comment by realsoelynn** [comment]
PR is merged. I am closing this issue.
