### ISSUE TITLE
Execution failed for task ':app:compileDebugKotlin'.

### ISSUE THREAD

**Issue by gkasireddy202** [facebook/react-native#44473]
### Description

Getting the below error I upgraded the project from 0.68.7 to 0.73.2

Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

### Steps to reproduce

react-native run-android 

### React Native Version

0.73.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.2.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 38.38 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/gopi/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google APIs Intel x86 Atom
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google APIs Intel x86 Atom
      - android-32 | Google APIs Intel x86 Atom_64
      - android-32 | Google Play Intel x86 Atom_64
      - android-33 | Google APIs Intel x86 Atom_64
      - android-33 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8609683
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/gopi/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Getting the below error I upgraded the project from 0.68.7 to 0.73.2

rebuild the project in Android studio

Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

### Reproducer

No Git url

**Comment by gkasireddy202** [comment]
We recently upgraded my project to 0.73.2.
iOS builds successfully and issues with Android.

**Comment by cortinico** [comment]
Your Android code is not compiling.
We need to full build log to see what happened here.

**Comment by gkasireddy202** [comment]
@cortinico - Thanks for the reply.The issue with namespace in build.gradle.
Now i am getting this error.I am using distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

**Comment by cortinico** [comment]
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> For more on this, please refer to [docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings](https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings) in the Gradle documentation.

This is a warning, not an error, you can ignore it (also is caused by the Android/Google toolchain). Closing as this is solved

**Comment by AbdessamadAe** [comment]
@gkasireddy202 I have the same issue and I am using Gradle 8.8. My react native app works fine in Expo GO. But when I build it  and run it on an android device it goes blank.
Running `npm run android` fails with this output:
`> Task :app:compileDebugKotlin FAILED
<<
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details`
Here is my package.json:
`{
  "name": "Médicaments",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/lato": "^0.2.3",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "expo": "~51.0.9",
    "expo-camera": "^15.0.10",
    "expo-font": "~12.0.6",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "^3.0.4",
    "expo-updates": "~0.25.15",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-picker-select": "^9.1.3",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-webview": "13.8.6",
    "react-navigation": "^5.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "@types/react-navigation": "^3.4.0",
    "typescript": "~5.3.3"
  },
  "private": true
}
`

**Comment by gkasireddy202** [comment]
@AbdessamadAe - I upgraded the expo manually instead of auto-linking.

**Comment by AbdessamadAe** [comment]
@gkasireddy202 Expo version is updated. I initiated a new blank project and tried to build, it had same issue. Any suggestions on how to fix that?

**Comment by gkasireddy202** [comment]
Can you please try to run the app in debug mode then you will know the exact error.
I found my issue like that only.

**Comment by neilhendricks** [comment]
Did you ever resolve this issue?

**Comment by winwonwen** [comment]
Check it out
app/build.gradle 
namespace

**Comment by uguraktas** [comment]
I have same issue

**Comment by AbdessamadAe** [comment]
I built a new express project and copied my code. That resolved it.

**Comment by Nikit-Singh** [comment]
I am using expo (managed workflow). After deleting the `android` folder and then running the app fixed the issue for me.

**Comment by fab-araujo** [comment]
> Check it out app/build.gradle namespace

That resolved my issue. The name space in android/app/build.grade must be the same as in the app.json

**Comment by navyaxb** [comment]
> > Check it out app/build.gradle namespace
> 
> That resolved my issue. The name space in android/app/build.grade must be the same as in the app.json

app.json "name" or "displayName"?

**Comment by abdullahSolace** [comment]
2025 and still getting this error in react-native : 0.71.1

**Comment by somanath27** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 15m 38s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set.
Proceeding without mode-specific .env
Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\@react-native-async-storage\async-storage\android\src\javaPackage\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\@react-native-community\slider\android\src\oldarch\java\com\reactnativecommunity\slider\ReactSliderManager.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\react-native-safe-area-context\android\src\paper\java\com\th3rdwave\safeareacontext\NativeSafeAreaContextSpec.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\react-native-screens\android\src\paper\java\com\swmansion\rnscreens\NativeScreensModuleSpec.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: D:\Final\BuyOnMaps\node_modules\expo-dev-menu\vendored\react-native-safe-area-context\android\devmenu\com\th3rdwave\safeareacontext\SafeAreaUtils.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/1bd320581c44090a3bc23d0132f4db6e/transformed/jetified-play-services-measurement-api-22.2.0-api.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/java.com.google.android.gms.libs.filecompliance.proto_file_access_api_type_kt_proto_lite.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_only_for_use_in_proto_generated_code_its_generator_and_tests.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_shared_runtime.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 15m 38s.

**Comment by ayushtps** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:compileDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 15m 38s error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 The NODE_ENV environment variable is required but was not specified. Ensure the project is bundled with Expo CLI or NODE_ENV is set. Proceeding without mode-specific .env Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules@react-native-async-storage\async-storage\android\src\javaPackage\java\com\reactnativecommunity\asyncstorage\AsyncStoragePackage.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules@react-native-community\slider\android\src\oldarch\java\com\reactnativecommunity\slider\ReactSliderManager.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\react-native-safe-area-context\android\src\paper\java\com\th3rdwave\safeareacontext\NativeSafeAreaContextSpec.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: D:\Final\BuyOnMaps\node_modules\react-native-screens\android\src\paper\java\com\swmansion\rnscreens\NativeScreensModuleSpec.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details. Note: D:\Final\BuyOnMaps\node_modules\expo-dev-menu\vendored\react-native-safe-area-context\android\devmenu\com\th3rdwave\safeareacontext\SafeAreaUtils.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/1bd320581c44090a3bc23d0132f4db6e/transformed/jetified-play-services-measurement-api-22.2.0-api.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/java.com.google.android.gms.libs.filecompliance.proto_file_access_api_type_kt_proto_lite.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_only_for_use_in_proto_generated_code_its_generator_and_tests.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. e: file:///C:/Users/Somanath/.gradle/caches/8.8/transforms/d1cb7c6b3ba204ee1125ebda76111b33/transformed/jetified-play-services-measurement-impl-22.2.0-api.jar!/META-INF/third_party.kotlin.protobuf.src.commonMain.kotlin.com.google.protobuf.kotlin_shared_runtime.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0. FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':app:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 15m 38s.

in my project react native version is "react-native": "^0.75.0" so it gives same error but when i changed this version with "react-native": "^0.76.3" it's completely run with android and IOS both but in this case react native stipe is not support in 0.76 or higher version

**Comment by AtoZDebug-Developer** [comment]
I m facing the same issue. Can anyone help me resolve it?

**Comment by hazemmuuhammed** [comment]
@tohel17  didn't work for me

**Comment by ronnioliveira** [comment]
I'm already in 2.0.21 and still not working

**Comment by Usmanqayyum109** [comment]
Worked for me after installing @react-native/gradle-plugin 0.77 and upgrading distributionUrl to gradle-8.9-all.zip in gradle-wrapper.properties. My project is targeting to React Native version 0.75.3

**Comment by SagarGhosh1995** [comment]
> Worked for me after installing @react-native/gradle-plugin 0.77 and upgrading distributionUrl to gradle-8.9-all.zip in gradle-wrapper.properties. My project is targeting to React Native version 0.75.3

This worked for me. Thanks

**Comment by MujeebAyokunle** [comment]
After installing @react-native/gradle-plugin, I got this error
`What went wrong:
Execution failed for task ':react-native-reanimated:configureCMakeDebug[x86]'.
> Failed to create directory '/Users/test/Documents/developments/Buildas/resilient_power/node_modules/react-native-reanimated/android/build/intermediates/cxx/Debug/607092u1/logs/x86'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 5m 50s
773 actionable tasks: 763 executed, 10 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Could not stop all services.
> Could not stop all services.
   > Failed to release lock on Build Output Cleanup Cache (/Users/test/Documents/developments/Buildas/resilient_power/node_modules/@react-native/gradle-plugin/.gradle/buildOutputCleanup)
   > Failed to release lock on execution history cache (/Users/test/Documents/developments/Buildas/resilient_power/node_modules/@react-native/gradle-plugin/.gradle/8.10.2/executionHistory)
> Could not stop all services.
   > Failed to release lock on cache directory md-supplier (/Users/test/.gradle/caches/8.10.2/md-supplier)
   > Could not stop all services.
      > Failed to release lock on Build Output Cleanup Cache (/Users/test/Documents/developments/Buildas/resilient_power/android/.gradle/buildOutputCleanup)
      > Failed to release lock on execution history cache (/Users/test/Documents/developments/Buildas/resilient_power/android/.gradle/8.10.2/executionHistory)
   > Failed to release lock on cache directory md-rule (/Users/test/.gradle/caches/8.10.2/md-rule)`

Then I ran the following to resolve it. **NOTE:** Keep your keystone file in a safe place 

`# Stop all Gradle daemons
./gradlew --stop

# Clean the project
cd android && ./gradlew clean

# Delete Gradle caches (careful: this resets all cached dependencies)
rm -rf ~/.gradle/caches/
rm -rf android/.gradle/
rm -rf node_modules/react-native-reanimated/android/.gradle/`

`# Give full permissions to your project directory
sudo chown -R $(whoami) /Users/test/Documents/developments/Buildas/resilient_power
sudo chmod -R 755 /Users/test/Documents/developments/Buildas/resilient_power`

`# Clean npm/yarn cache
npm cache clean --force || yarn cache clean

# Reinstall node_modules
rm -rf node_modules package-lock.json
npm install || yarn install

# Reinstall pods (if iOS)
cd ios && pod install --repo-update && cd ..`

`# For Android
npx react-native run-android --variant=debug

# For iOS
npx react-native run-ios`

I hope this helps someone.

**Comment by francoangulo** [comment]
if anyone else is still experiencing this issue, I fixed it with 2 little changes in the MainApplication.kt

```diff
--- a/android/app/src/main/java/com/packagename/MainApplication.kt
+++ b/android/app/src/main/java/com/packagename/MainApplication.kt
@@ -38,7 +38,7 @@ class MainApplication : Application(), ReactApplication {
   override val reactNativeHost: ReactNativeHost =  ReactNativeHostWrapper(
             this,
     object : DefaultReactNativeHost(this) {
-      override fun getPackages(): ArrayList<ReactPackage>? =
+      override fun getPackages(): MutableList<ReactPackage> =
         PackageList(this).packages.toMutableList().apply {
           // Packages that cannot be autolinked yet can be added manually here, for example:
           // add(MyReactNativePackage())
```

if you are doing `.packages.toMutableList()` make sure the return type of `getPackages()` is also of `MutableList`
