### ISSUE TITLE
Xcode works normally during real machine debugging, but when disconnected, clicking on the app to open will crash. The mobile system is 13.8. No problem with systems above 14

### ISSUE THREAD

**Issue by xialun** [facebook/react-native#44478]
### Description

Xcode works normally during real machine debugging, but when disconnected, clicking on the app to open will crash. The mobile system is 13.8. No problem with systems above 14, this is the demo project address:https://gitee.com/wang-shuaisheng/rn-crash.git](https://github.com/reactnativecn/react-native-website/issues/834)

### Steps to reproduce

Xcode works normally during real machine debugging, but when disconnected, clicking on the app to open will crash. The mobile system is 13.8. No problem with systems above 14, this is the demo project address:https://gitee.com/wang-shuaisheng/rn-crash.git](https://github.com/reactnativecn/react-native-website/issues/834)

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Areas

Codegen

### Output of `npx react-native info`

```text
Last login: Wed May  8 17:28:54 on ttys006
wangshuai@wangshuaideMacBook-Pro NewProject % npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Memory: 700.37 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 9.8.1
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2020.3 AI-203.7717.56.2031.7583922
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 16.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

wangshuai@wangshuaideMacBook-Pro NewProject %
```

### Stacktrace or Logs

```text
{"app_name":"NewProject","timestamp":"2024-05-08 11:07:59.00 +0800","app_version":"1.0","slice_uuid":"11f4e45e-e911-3b67-88de-329775e72255","adam_id":"0","build_version":"1","bundleID":"www.mynjj.rn","share_with_app_devs":"1","is_first_party":"0","bug_type":"109","os_version":"iPhone OS 13.7 (17H35)","incident_id":"F881568F-C280-485F-8DE0-574FAB3A31CE","name":"NewProject"}
```

### Reproducer

https://gitee.com/wang-shuaisheng/rn-crash.git

**Comment by cipolleschi** [comment]
Xcode 15.3 is bugged. Apple rewrote the linker and dropped support for weak symbols. 
They fixed in Xcode 15.0 and 15.1 with a new flag and then fixed for good in Xcode 15.2.
Unfortunately, it regressed in 15.3.

Can you check if the problem persist when using Xcode 15.2?

This other issue might give you more information: #42230.

**Comment by xialun** [comment]
demo pah is https://gitee.com/wang-shuaisheng/rn-crash.git ;This path can reproducible

**Comment by xialun** [comment]
we have a other question, app need suppor from ios9. If not init React Native ,how to app run normal below ios13.4

**Comment by xialun** [comment]
app crashed  but no detail crash log. The log content is {"app_name":"NewProject","timestamp":"2024-05-08 11:07:59.00 +0800","app_version":"1.0","slice_uuid":"11f4e45e-e911-3b67-88de-329775e72255","adam_id":"0","build_version":"1","bundleID":"www.mynjj.rn","share_with_app_devs":"1","is_first_party":"0","bug_type":"109","os_version":"iPhone OS 13.7 (17H35)","incident_id":"F881568F-C280-485F-8DE0-574FAB3A31CE","name":"NewProject"}
