### ISSUE TITLE
 redefinition of module 'ReactCommon' iOS

### ISSUE THREAD

**Issue by daimonkor** [facebook/react-native#44502]
### Description

`/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap:1:8: error: redefinition of module 'ReactCommon'
module ReactCommon {
       ^
/ios/Pods/Headers/Public/ReactCommon/React-RuntimeApple.modulemap:1:8: note: previously defined here
module ReactCommon {
       ^
1 error generated.`

### Steps to reproduce

1. react-nativre upgrade to 0.74.0 (from 0.73.8)

### React Native Version

0.74.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 256.48 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.0
    path: ~/.nvm/versions/node/v20.8.0/bin/node
  Yarn:
    version: 1.22.21
    path: /Volumes/Ext/Projects/ReactNative/outcome-mobile/node_modules/.bin/yarn
  npm:
    version: 10.2.0
    path: ~/.nvm/versions/node/v20.8.0/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/usersmart/.gem/ruby/3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "23"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 23.0.1
      - 25.0.2
      - 26.0.3
      - 27.0.3
      - 28.0.2
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-22 | Google APIs Intel x86_64 Atom
      - android-23 | Google APIs Intel x86 Atom_64
      - android-26 | Google APIs ARM 64 v8a
      - android-28 | Google APIs Intel x86 Atom
      - android-29 | Google APIs Intel x86 Atom_64
      - android-29 | Google Play Intel x86 Atom
      - android-30 | Google Play Intel x86 Atom_64
      - android-31 | Intel x86_64 Atom
      - android-31 | Google APIs Intel x86_64 Atom
      - android-31 | Google Play Intel x86 Atom_64
      - android-32 | Google APIs Intel x86_64 Atom
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs Intel x86_64 Atom
      - android-33 | Google Play Intel x86_64 Atom
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/usersmart/.rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
❌  /Volumes/Ext/Projects/ReactNative/outcome-mobile/ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap:1:8: redefinition of module 'ReactCommon'

module ReactCommon {
                                                                   ^
```

### Reproducer

1. react-nativer upgrade 0.74.1
2. react-native run-ios

**Comment by daimonkor** [comment]
> ⚠️ 	Newer Version of React Native is Available!
> ℹ️ 	You are on a supported minor version, but it looks like there's a newer patch available - 0.74.1. Please [upgrade](https://reactnative.dev/docs/upgrading) to the highest patch for your minor or latest and verify if the issue persists (alternatively, create a new project and repro the issue in it). If it does not repro, please let us know so we can close out this issue. This helps us ensure we are looking at issues that still exist in the most recent releases.

Upgraded ti 0.74.1, bug reproduced again

**Comment by KikotVit** [comment]
Same issue.
I have tried to delete the declaration of that module manually
`module ReactCommon { ...` (everything in file)
And it works for me. 
But it looks weird...

**Comment by justbaum30** [comment]
I have also run into this issue and reported it here - https://github.com/reactwg/react-native-releases/issues/284

**Comment by johnny-mcfadden-dailypay** [comment]
+1

**Comment by TwistedMinda** [comment]
> Same issue. I have tried to delete the declaration of that module manually `module ReactCommon { ...` (everything in file) And it works for me. But it looks weird...

Yep, can build locally with the removal of ReactCommon, but breaks CI/CD obviously, therefore prevents upgrade to 74

**Comment by cipolleschi** [comment]
The issue does not have a reproducer, so I can't investigate it.
Have a look at [this other issue](https://github.com/reactwg/react-native-releases/issues/284), specifically, [this comment](https://github.com/reactwg/react-native-releases/issues/284#issuecomment-2120398878).

If you are using Firebase, make sure to install pods as static frameworks and to follow the firebase installation instructions
If you are using `RNCheckNotificationPermission`, this library has a bug in one of the imports

**Comment by MtoagF** [comment]
Redefinition of module 'ReactCommon'

when i installed fireabse in xcode 15.4.1

**Comment by drewm1192** [comment]
Same issue for me.

**Comment by krzysiek-mc** [comment]
As a workaround try to remove `use_modular_headers!` from your Podfile and apply modular headers only to specific pods 

```
pod 'FirebaseCore', :modular_headers => true
pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
```

worked for me

**Comment by ywisax** [comment]
Same problem, ios/Pods/Headers/Public/ReactCommon/ReactCommon.modulemap and ios/Pods/Headers/Public/ReactCommon/React-RuntimeApple.modulemap

**Comment by kitalia** [comment]
+1

**Comment by cipolleschi** [comment]
@ywisax and @kitalia I'm sorry that you are encountering this issue. I can't really fix it if I can't reproduce it.
Can you set up a reproducer using this [template](https://github.com/react-native-community/reproducer-react-native)?

**Comment by ywisax** [comment]
> @ywisax and @kitalia I'm sorry that you are encountering this issue. I can't really fix it if I can't reproduce it. Can you set up a reproducer using this [template](https://github.com/react-native-community/reproducer-react-native)?

@cipolleschi 
This is the reproducable repo, https://github.com/ywisax/rn-issue-44502
![iShot_2024-09-19_11 31 13](https://github.com/user-attachments/assets/3cd2b953-9331-458c-8f44-80b957a2e8b1)

**Comment by ywisax** [comment]
This is a possible fix, https://github.com/expo/expo/issues/29004#issuecomment-2180180240
