### ISSUE TITLE
Appreance.getColorScheme() always returns "light" | Android | IOS | React Native | Expo

### ISSUE THREAD

**Issue by AbdullahSherMuhammad** [facebook/react-native#44522]
### Description

Whenever using Expo to build React Native apps, Apperance.getColorScheme always returns "Light". It is not a React Native bug rather a Expo bugs. I search for a solution for days but couldn't find one. Ever had a same issue of github titled same but no good answer. 

Finally I got the fix and I want to share it with the community "Note: make sure your iOs or Android project is not hard-coded to a light user-interface style, or the above will not work. If using Expo, you will need to set "userInterfaceStyle": "automatic" in your app.json under the expo key (the default is “light”)."

### Steps to reproduce

"expo": {
    "name": "FirstRNApp",
    "slug": "FirstRNApp",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },

### React Native Version

0.73.6

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
light
```

### Stacktrace or Logs

```text
This error is located at:
    in App (at withDevTools.js:18)
    in withDevTools(App) (at renderApplication.js:57)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:127)
    in RCTView (at View.js:116)
    in View (at AppContainer.js:155)
    in AppContainer (at renderApplication.js:50)
    in main(RootComp
```

### Reproducer

https://github.com/AbdullahSherMuhammad/FocusApp-ReactNative

**Comment by cortinico** [comment]
> Whenever using Expo to build React Native apps, Apperance.getColorScheme always returns "Light". It is not a React Native bug rather a Expo bugs. I search for a solution for days but couldn't find one. Ever had a same issue of github titled same but no good answer.

> Finally I got the fix and I want to share it with the community "Note: make sure your iOs or Android project is not hard-coded to a light user-interface style, or the above will not work. If using Expo, you will need to set "userInterfaceStyle": "automatic" in your app.json under the expo key (the default is “light”)."

Thanks for sharing your solution. Closing it 👍
