### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code with ios build

### ISSUE THREAD

**Issue by AwsBTek** [facebook/react-native#44533]
### Description

When I tried to build the iOS project, I faced this issue:

/Users/pc/Downloads/einvoicing-react-native-mobile-app-1/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../scripts/react_native_pods_utils/script_phases.sh: line 86: /usr/local/bin/node
: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code.

My react version: ` "react-native": "0.70.5",`

The script_phases line: 86 is: 
<img width="973" alt="image" src="https://github.com/facebook/react-native/assets/165676865/76905a6b-8a96-4fc2-8ea0-e814eec4754d">

### Steps to reproduce

1. Yarn.
2. `cd ios`.
3. `pod install` -> pods installed successfully.
4. open xcode project.
5. Product -> build.
6. <img width="264" alt="image" src="https://github.com/facebook/react-native/assets/165676865/4524fad0-8fc6-4eb1-806e-21cc83711854">

### React Native Version

0.75.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 120.72 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.15.2 - /Users/awshakam/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.2 AI-232.10300.40.2321.11668458
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found.
```

### Stacktrace or Logs

```text
/Users/pc/Downloads/einvoicing-react-native-mobile-app-1/ios/Pods/../.xcode.env: line 5: 
: command not found
Node found at: /usr/local/bin/node
/Users/pc/Downloads/einvoicing-react-native-mobile-app-1/ios/Pods/../../node_modules/react-native/React/FBReactNativeSpec/../../scripts/react_native_pods_utils/script_phases.sh: line 87: /usr/local/bin/node
: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

### Reproducer
https://github.com/AwsBTek/react_native_issue

**Comment by Siliconvelly** [comment]
Facing same issue on my side i am integrated new latest version of react native 0.74.1  on android side it is running but on ios side it gives error like your (@AwsBTek) mentioned.

![Uploading Screenshot 2024-05-11 at 11.47.14 AM.png…]()

**Comment by MUSHTHAK2899** [comment]
check Your Mac storage

**Comment by MUSHTHAK2899** [comment]
check Your Mac storage

**Comment by AwsBTek** [comment]
@MUSHTHAK2899 My Macbook's storage is 415 GB free.

**Comment by sandipsarkar13** [comment]
Facing same issue on the latest version of react native 0.74.1.  I'm getting the following error:
~/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E00030580.sh: line 2: /scripts/xcode/with-environment.sh: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by baenacoco** [comment]
I got the error, 

ios/.xcode.env => In this file you will found the instructions to set up NODE_BINARY that is necessary for building the project. I tried to set up in my .zhsrc file but it didn´t work because it have to be set up in this file.
So my solution is:
Create or modify a file "ios/.xcode.env.local" with this content "export NODE_BINARY=$(which node)" so you can replace "$(which node)" for your local bin node.

**Comment by awshakam1998** [comment]
@baenacoco 
Many thanks; I was able to solve the problem with your help.

**Comment by AwsBTek** [comment]
@baenacoco 
Many thanks; I was able to solve the problem with your help.

**Comment by mMarcos208** [comment]
Same issue react native 0.74.1 when archive.

I verify my .xcode.env and I see

`export NODE_BINARY=$(command -v node)`

In my .xcode.env.local 

`export NODE_BINARY=/usr/local/bin/node`

change to `export NODE_BINARY=$(command -v node)` and not working.

**Comment by mMarcos208** [comment]
Same issue react native 0.74.2 when archive.

<img width="763" alt="image" src="https://github.com/facebook/react-native/assets/14351491/0e341b9d-3928-42c2-b7ef-8e1c53d50fa0">


I verify my .xcode.env and I see

`export NODE_BINARY=$(command -v node)`

running in my terminal `usr/local/bin/node`

> Welcome to Node.js v20.10.0.
> Type ".help" for more information.

In my .xcode.env.local 

`export NODE_BINARY=/usr/local/bin/node`

change to `export NODE_BINARY=$(command -v node)` and not working.

**Comment by gitcoder-23** [comment]
i facing same issue in flutter project please help to fix it. I am using Mac M3 system. Xcode 15.4.
