### ISSUE TITLE
2 files found with path 'lib/arm64-v8a/libopencv_java4.so' from inputs:  - /Users/wegile-1003/.gradle/caches/transforms-3/8ec77b58992a0a620e60c240eaed7c29/transformed/jetified-rppg_core-0.2.0/jni/arm64-v8a/libopencv_java4.so  - /Users/wegile-1003/.gradle/caches/transforms-3/a576edfdc1ae89d711e78c8d27ec535b/transformed/jetified-opencv-android-4.1.2/jni/arm64-v8a/libopencv_java4.so If you are using jniLibs and CMake IMPORTED targets, see

### ISSUE THREAD

**Issue by sumitjainwegile** [facebook/react-native#44570]
### Description

2 files found with path 'lib/arm64-v8a/libopencv_java4.so' from inputs:
 - /Users/wegile-1003/.gradle/caches/transforms-3/8ec77b58992a0a620e60c240eaed7c29/transformed/jetified-rppg_core-0.2.0/jni/arm64-v8a/libopencv_java4.so
 - /Users/wegile-1003/.gradle/caches/transforms-3/a576edfdc1ae89d711e78c8d27ec535b/transformed/jetified-opencv-android-4.1.2/jni/arm64-v8a/libopencv_java4.so
If you are using jniLibs and CMake IMPORTED targets, see

### Steps to reproduce

After Adding these code in app/build.gradle under dependencies object
implementation("com.facebook.react:react-android")
    implementation("com.facebook.react:flipper-integration")
    implementation(files("libs/rppg_common-0.5.2.aar"))
    implementation(files("libs/rppg_core-0.2.0.aar"))

    // camerax
    //def camerax_version = '1.0.0-rc01'
    def camerax_version = '1.3.0-alpha04'
    def camerax_view_version = '1.0.0-alpha20'
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"

    //mlkit
    def mlkit_version = "16.0.3"
    implementation "com.google.mlkit:face-detection:${mlkit_version}"

    //socket
    implementation "com.neovisionaries:nv-websocket-client:2.4"

//    //opencv
    def opencv_version = '4.1.2'
    implementation "com.github.iamareebjamal:opencv-android:${opencv_version}"

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.5
  CPU: (8) arm64 Apple M1
  Memory: 101.86 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/local/bin/yarn
  npm:
    version: 9.6.7
    path: /usr/local/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.4
      - iOS 16.0
      - macOS 12.3
      - tvOS 16.0
      - watchOS 9.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 14.0/14A309
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
implementation("com.facebook.react:react-android")
    implementation("com.facebook.react:flipper-integration")
    implementation(files("libs/rppg_common-0.5.2.aar"))
    implementation(files("libs/rppg_core-0.2.0.aar"))

    // camerax
    //def camerax_version = '1.0.0-rc01'
    def camerax_version = '1.3.0-alpha04'
    def camerax_view_version = '1.0.0-alpha20'
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"

    //mlkit
    def mlkit_version = "16.0.3"
    implementation "com.google.mlkit:face-detection:${mlkit_version}"

    //socket
    implementation "com.neovisionaries:nv-websocket-client:2.4"

    //opencv
    def opencv_version = '4.1.2'
    implementation "com.github.iamareebjamal:opencv-android:${opencv_version}"
```

### Reproducer

https://github.com/facebook/react-native/issues/44553

### Screenshots and Videos

<img width="1440" alt="Screenshot 2024-05-14 at 5 32 38 PM" src="https://github.com/facebook/react-native/assets/105035653/8bc053af-db86-4607-95ae-50d9aad95fec">

**Comment by efstathiosntonas** [comment]
use `pickFirst` like this in `android/app/build.gradle`, replace `libcrpyto.so` with your duplicate `.so` from the error you get:

```
android {
...
packagingOptions {
        pickFirst 'lib/x86/libcrypto.so'
        pickFirst 'lib/x86_64/libcrypto.so'
        pickFirst 'lib/armeabi-v7a/libcrypto.so'
        pickFirst 'lib/arm64-v8a/libcrypto.so'
    }
}
```

**Comment by cortinico** [comment]
> use `pickFirst` like this in `android/app/build.gradle`, replace `libcrpyto.so` with your duplicate `.so` from the error you get:

That's the correct answer, thanks @efstathiosntonas
