### ISSUE TITLE
[Text] Emoji changes the line height

### ISSUE THREAD

**Issue by h3l** [facebook/react-native#4457]
The demo is [here](https://rnplay.org/apps/fI38fg),
Emoji will change the line height.

**Comment by adbl** [comment]
Related to this:

Rendering a text at fontSize 15 results in a lineheight of 18 (default font), setting the lineHeight to 18 explicitly and including an emoji will also lift up the baseline (which results in??) emoji getting cut at the top.

If there are several lines of text, an emoji on second line will fit an not get cut...

**Comment by adbl** [comment]
@h3l do you know of any workaround?

**Comment by h3l** [comment]
I'm sorry to tell you  that there is still no solution for this.
What about to direct mention a contributor about it?

**Comment by adbl** [comment]
I found somewhat of a workaround actually... detect if the text contains any emoji and in that case apply additional style:
```
  emojiText: {
    fontSize: 15,
    lineHeight: 18
    marginBottom: -2,
    paddingTop: 2,
  }
```

Obviously it is tied to this fontSize (and font?)...

**Comment by h3l** [comment]
Yes, this style fix the problem in a given fontsize.
But when use change the fontsize in setting, it may have a problem.

**Comment by h3l** [comment]
@brentvatne Could you please have a look at this problem?

**Comment by brentvatne** [comment]
@h3l - sorry I had so many notifs I just noticed this. I'm not familiar with this part of the codebase but I'm noticing some strange behaviours with lineHeight on Android so looking into that..

**Comment by eugenehp** [comment]
@h3l hey Hel, do you have accounted the same issue on android platform?

**Comment by eugenehp** [comment]
@brentvatne what do you think about this? do you think [this](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L345) might be the good place to start finding the way to fix this interesting issue?

**Comment by adbl** [comment]
In iOS 10 the behaviour is a bit different, I think the line height no longer changes, but instead the emoji will get cut at the Text bottom margin.

**Comment by regrex** [comment]
@adbl I resolved this problem by add a character, like space.

**Comment by hramos** [comment]
This is an old issue and it's not clear to me if it's still affecting people.

Please feel free to re-open, and fill in the template with details.

**Comment by adbl** [comment]
@hramos it is still an issue, it acts differently in iOS 10 vs before. There are hacks to get around it, the best one I could come up with is to add zero width space to the text. It's still a bug

**Comment by hramos** [comment]
Alright - can you open a new issue?

**Comment by adbl** [comment]
I will not bother because we have solved it for our purposes. This issue
has some of the information that explains what is wrong. Why close and open
a new one?

**Comment by hramos** [comment]
The issue lacks all the detail required in the template, has been open for a really long time, and people have commented with possibly unrelated issues. If someone really cares about this, then the best way forward is to open a new issue with all the necessary details.

**Comment by adbl** [comment]
Ok, hopefully someone does care about it enough to do that then.

**Comment by rikur** [comment]
Still an issue.

**Comment by rikur** [comment]
@hramos I would love to, but unfortunately I can't verify the issue with latest version of React Native as it breaks remote debugging. I noticed the latest version has new implementation of Text.

I will try again with the next release.

**Comment by ccfz** [comment]
I have been looking into this issue for a while now and there are some hacky solutions out there related to adjusting the fontSizes / lineHight etc. The issue does not arise when one uses `System` in `FontFamily`, which to my understanding is related to the way `System` font was implemented in react-native with IOS/Android presets #1635. The problem with `System`is that it does not allow for font variations such as `SF UI Display`. I found this solution #18559 that separates emojis from their string to give them a smaller `fontSize`.  The issue with that solution is that it is dependent on the styles of the font. What I discovered though is that if I apply the `System` fontFamily to just the emoji it will behave as expected without having to add custom font. 

So based on the code from #18559 I just changed the `fontSize: 11` to `fontFamily: System`.

In our project we are only using variants of `San Fransico` font and since `System` is `SF UI Text` it might only work with variants of the default system fonts. I am interested to see if this works with other custom fonts as well. 

For convenience the snippet from #18559 the way I implemented it and with the `fontFamily`change.

```javascript
import React from 'react';
import { Text } from 'react-native';

const EmojiText = ({ style, children, ...rest }) => {
  // eslint-disable-next-line
  const emojiRe = /(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|[\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|[\ud83c[\ude32-\ude3a]|[\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])/g
  const emojis = children.match(emojiRe);
  const strings = children.split(emojiRe);

  function renderEmoji(index) {
    if (emojis === null) { return null; }

    return (
      <Text style={{ fontFamily: 'System' }}>
        {emojis[index]}
      </Text>
    );
  }

  return (
    <Text style={style} {...rest}>
      {strings.map((value, index) => (
        <Text>
          {value}
          {renderEmoji(index)}
        </Text>
      ))}
    </Text>
  );
};

export default EmojiText;

```
