### ISSUE TITLE
Can't enable debugging for the movies app

### ISSUE THREAD

**Issue by despairblue** [facebook/react-native#446]
I try to get the debugger working for the movies example.

When I simply press `cmd+d` I get:
![screenshot 2015-03-29 18 00 18](https://cloud.githubusercontent.com/assets/927609/6886414/b939b120-d63d-11e4-9a91-67a5504b7358.png)

After that I tried to include RCTWebSocketDebugger by following [this](https://facebook.github.io/react-native/docs/linking-libraries.html#content) guide. Now I get this link error:

```
Undefined symbols for architecture x86_64:
  "_utf8_nextCharSafeBody", referenced from:
      _validate_dispatch_data_partial_string in libRCTWebSocketDebugger.a(SRWebSocket.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Does anyone have an idea what I'm missing?

**Comment by tadeuzagallo** [comment]
Hum, it shouldn't happen, but you can fix it by adding `libicucore.dylib` to the build phases of your project.

**Comment by a2** [comment]
@tadeuzagallo The podspec? No I haven't updated it yet. I can do that now.
@ despairblue Are you using CocoaPods?

**Comment by despairblue** [comment]
Nope, to be honest I've never developed for iOS.

**Comment by a2** [comment]
@despairblue Did you follow @tadeuzagallo's advice? It's probably because you aren't linking against `libicucore.dylib`.

**Comment by tadeuzagallo** [comment]
@a2 Oh, that's true, you're going to fix the podspec... I was thinking about actually importing it on RCTWebSocket project.

**Comment by a2** [comment]
@tadeuzagallo Yeah I'm updating the podspec now.

**Comment by despairblue** [comment]
Adding `libicucore.dylib` did fix it. Thanks, and sorry for taking that long, I'm not used to getting responses that quickly :smile:

**Comment by tadeuzagallo** [comment]
@a2 don't update the podspec yet.

I should probably add that to the docs as well. Adding `libicucore` on the `RCTWebSocketDebugger` project doesn't fix it. it has to be added to the main project :/

**Comment by a2** [comment]
@tadeuzagallo If you add it to the podspec, it gets linked in the main project. It's that magical. :rainbow: 

Can you merge https://github.com/facebook/react-native/blob/f3cd27cf483671b8821e4f50bfa7bb370893e59a/React.podspec back internally? It seems that it wasn't and has been overwritten.
