### ISSUE TITLE
Duplicate styles in stylesheet causes white screen [bug]

### ISSUE THREAD

**Issue by fxhereng** [facebook/react-native#4461]
I've just noticed a bug that causes me long times of debug, a duplicate style name like this: 
```
    var styles = StyleSheet.create({
      inputStyle: {
        flex: 1,
      },
      inputStyle: {
        otherProperty: 'value',
      },
    });
```

caused me a white screen at launching the application with no error messages, which can be pretty uncomfortable when your stylesheet becomes big. I'm using currently the 0.14.2 version.

This wasn't a style sheet in the splash screen (my first route), it happens in whatever style sheet of the project.

I don't know if it's a known issue or if it is fixed in the last version, I haven't found any issues talking about this.

Regards

**Comment by satya164** [comment]
Hey @fxhereng . Please consider using a linter like [ESLint](http://eslint.org/) to catch these kinds of bugs early. AFAIK there is no way to detect these kinds of errors from within JavaScript.
