### ISSUE TITLE
React-Codegen Error when build iOS

### ISSUE THREAD

**Issue by ibrahim7elmasry** [facebook/react-native#44625]
### Description

I have an error when build iOS from XCode,

and there is a warning after pod install

<img width="268" alt="Screenshot 2024-05-20 at 3 59 59 PM" src="https://github.com/facebook/react-native/assets/19375545/b60dbbfe-487a-4f45-b80d-ff426e8c5de9">

<img width="829" alt="Screenshot 2024-05-20 at 3 53 19 PM" src="https://github.com/facebook/react-native/assets/19375545/09e952c2-060d-493b-8f57-0add1956d595">

### Steps to reproduce

1- pod install
2- run from xcode

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 81.61 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.2.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.7.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/ibrahimelmasry/.rvm/gems/ruby-3.2.1/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 3.2.1
    path: /Users/ibrahimelmasry/.rvm/rubies/ruby-3.2.1/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.1
    wanted: ^0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
t
```

### Reproducer

https://github.com/facebook/react-native

### Screenshots and Videos

<img width="829" alt="Screenshot 2024-05-20 at 3 53 19 PM" src="https://github.com/facebook/react-native/assets/19375545/72be86e9-c94a-479b-82c4-b7b5a4a082db">
<img width="268" alt="Screenshot 2024-05-20 at 3 59 59 PM" src="https://github.com/facebook/react-native/assets/19375545/0b9ecf7f-4dea-43db-9c0f-0cbc2e6080f6">

**Comment by cortinico** [comment]
We need to full build log to see what happened

**Comment by ibrahim7elmasry** [comment]
I have solved it after many hours, in .xcode.env.local file the export NODE_BINARY path was not correct
after run which node I have write the correct path then it solved

**Comment by farooqalam20996** [comment]
Hi everyone:
    I am, facing this issue since two days, And I tried many solutions but didn't solved my problem, let me share the full details Hope you may help me.
    
Thanks
I ran the following command:
 npx react-native run-ios
 
 
 Console log:
 
...other logs...........

**Comment by farooqalam20996** [comment]
> I have solved it after many hours, in .xcode.env.local file the export NODE_BINARY path was not correct after run which node I have write the correct path then it solved

Hi @ibrahim7elmasry I tried your solution but it's not working, I am facing the above issue again and again even I delete my xcode and the whole setup then reinstall everything and restart my Macbook and create new react native project and then run app on ios again but still face the same issue.

**Comment by ibrahim7elmasry** [comment]
> > I have solved it after many hours, in .xcode.env.local file the export NODE_BINARY path was not correct after run which node I have write the correct path then it solved
> 
> Hi @ibrahim7elmasry I tried your solution but it's not working, I am facing the above issue again and again even I delete my xcode and the whole setup then reinstall everything and restart my Macbook and create new react native project and then run app on ios again but still face the same issue.

try to disable hermes  in the pod file inside use_react_native

:hermes_enabled => false,

**Comment by ibrahim7elmasry** [comment]
> > I have solved it after many hours, in .xcode.env.local file the export NODE_BINARY path was not correct after run which node I have write the correct path then it solved
> 
> Hi @ibrahim7elmasry I tried your solution but it's not working, I am facing the above issue again and again even I delete my xcode and the whole setup then reinstall everything and restart my Macbook and create new react native project and then run app on ios again but still face the same issue.

Hi @farooqalam20996, try to disable hermes in the pod file inside use_react_native

:hermes_enabled => false,

**Comment by AdamBCo** [comment]
@ibrahim7elmasry By any chance did one of the directories in your project have a space? For example `Sample Project` as opposed to `SampleProject`. I've found I run into this issue when a space is present in one of the parent directories.

**Comment by WilliamDanielsson** [comment]
> [@ibrahim7elmasry](https://github.com/ibrahim7elmasry) By any chance did one of the directories in your project have a space? For example `Sample Project` as opposed to `SampleProject`. I've found I run into this issue when a space is present in one of the parent directories.

Wow thanks a lot! I got the same error message and I had a space in my folder that contained the repo. I was struggling with this for way to long and was ready to throw in the towel. I cant thank you enough!

**Comment by YasirNaeem25** [comment]
i Fix by changes in gemfile
https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8

**Comment by VijayKumarKTG** [comment]
Removing the space from the folder name also worked for me. Thanks @AdamBCo 👍🏽

**Comment by hassanilyas786** [comment]
> [@ibrahim7elmasry](https://github.com/ibrahim7elmasry) By any chance did one of the directories in your project have a space? For example `Sample Project` as opposed to `SampleProject`. I've found I run into this issue when a space is present in one of the parent directories.

Thanks @AdamBCo

**Comment by ShrutiIcorp** [comment]
I am Facing Error in Xcode while running react native project.
ReactCodeGen Command PhaseScriptExecution failed with a nonzero exit code.

My MacOs version: 15.6
My Xcode version: 16.4
My Node version: 23.11.0
My React native version: 0.80.2

I have tried every solutions but unable to solve this issue.

**Comment by aybarska** [comment]
this did the trick for me 

```
1. `yarn install`

2. `cd ios && pod install`

3. Build with New Arch: `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

4. `yarn ios`
```
