### ISSUE TITLE
Was  Precomputing style  removed

### ISSUE THREAD

**Issue by viphsx123** [facebook/react-native#4463]
Was  Precomputing style  removed ？

![qq20151201-1 2x](https://cloud.githubusercontent.com/assets/7017684/11496589/efcd313a-984d-11e5-8226-9bcc4fcd207e.png)

**Comment by ide** [comment]
I think it was never part of the public API to begin with and it just so happened that you could reach inside react native and require it. Everything here is the public API: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js (I don't see precomputeStyle).
