### ISSUE TITLE
[codegen] inconsistent use of `toSafeCppString` in `generateEnum` (GenerateModuleH.js)

### ISSUE THREAD

**Issue by robbeman** [facebook/react-native#44632]
### Description

The codegen step after pod install creates broken "SpecJSI" files.

I think a simple fix could be done here:
https://github.com/facebook/react-native/blob/2a96dba075367047be6bdb88d2fee6a1a05bc85c/packages/react-native-codegen/src/generators/modules/GenerateModuleH.js#L432

```diff
-    values: members.map(member => member.name).join(', '),
+    values: members.map(member => toSafeCppString(member.name)).join(', '),
```

### Steps to reproduce

1. Install a package that needs to bridge enums
    - Example: https://github.com/orbital-systems/react-native-esp-idf-provisioning
2. Run `pod install` in ios folder
3. Build project
    - You will notice build errors, in this case in `./ios/build/generated/ios/RNEspIdfProvisioningSpecJSI.h`

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 1.32 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.04.01.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/***/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/***/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Example of 1 error:

/ios/build/generated/ios/RNEspIdfProvisioningSpecJSI.h:27:46 No member named 'Ble' in 'facebook::react::EspIdfProvisioningESPTransport'; did you mean 'ble'?
```

### Reproducer

https://github.com/robbeman/react-native-generate-module-bug-report

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/3245659/fc68dcf3-97e7-47c6-8c17-a2ea0bbcf0e5)

**Comment by robbeman** [comment]
Sidenote: this does not happen in react-native 0.73, in which codegen does not pick up the file in the above example. So maybe the codegen script just started processing files it does not need to?


In any case, here's a patch file for people running into the same problem. (Only tested in this specific scenario.)

[@react-native+codegen+0.74.83.patch](https://github.com/facebook/react-native/files/15390286/%40react-native%2Bcodegen%2B0.74.83.patch)

**Comment by cortinico** [comment]
Fix for this is here:
- https://github.com/facebook/react-native/pull/44654
