### ISSUE TITLE
Can't build the app due to colliding 'react-native' bin declarations

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#4465]
We ran in an issue today when trying to bundle a react native app with only local dependencies. Meaning that both `react-native` and `react-native-cli` where declared in our app's `package.json`.
When doing this, however, running `react-native bundle (...)` would execute `react-native`'s `bin` script -> `wrong-react-native.js` instead of the one of `react-native-cli` because both modules declare a `react-native` bin in their `package.json`.
We saw that this commit (https://github.com/facebook/react-native/commit/2856be9a07582310c9e56667e8db21fb7b29ab48) re-introduced the `global-check` but also broke the ability to build an archive without global dependencies.
Does this mean the recommended way to build apps is to use global deps?

**Comment by bestander** [comment]
Currently we rely on react-native-cli to be global but keep in mind that react-native-sli is a very [thin wrapper](https://github.com/facebook/react-native/blob/master/react-native-cli/index.js) 
Feel free to not use it at all or copy it into your project.
