### ISSUE TITLE
[Android] Use dependency injection to manage packages and modules 

### ISSUE THREAD

**Issue by mjhlybmwq** [facebook/react-native#4466]
Can we use a xml/json file to add packages and modules instead of coding in the ```MainActivity.java```? 
Here's an example of the xml file:

```
<packages>
	<package class="com.foo.FooPackage.java" name="FooPackage">
		<module class="com.foo.FooModule.java" name="FooModule" />
		<module class="com.foo.AnotherModule.java" name="AnotherModule" />
		...
	</package>
	<Package class="com.foo.AnotherPackage.java" name="AnotherPackage">
		...
	</Package>
</packages>
```

**Comment by satya164** [comment]
@mjhlybmwq Why would you want to do that? It means learning an entirely new thing to add packages. Current way is good enough IMO, and with `react-native link` being worked on, it's simple to use too.

**Comment by mjhlybmwq** [comment]
@satya164 , thanks for your attention.

I think it's easier to learn for new-learners. Besides, managing packages by xml/json means it's possible to make a package manager, which makes it much easier to publish, install and uninstall a package.

**Comment by ide** [comment]
The XML looks easier but it's covering up a lot of details. With one or two lines of code you get a much more explicit view of what is happening, and if you want to understand more you can drill down into the Android SDK and read more code. The code is simple and significantly more transparent.

**Comment by satya164** [comment]
@mjhlybmwq Also the XML syntax is a lot less flexible that what  you'll be able to do with Java. For example, some packages might take some parameters in the constructor, etc. There is no way to accomodate all these with the XM syntax.

**Comment by mjhlybmwq** [comment]
Both of you made a point! Thanks a lot!
