### ISSUE TITLE
xcodebuild -derivedDataPath and react-native bundle 

### ISSUE THREAD

**Issue by adbl** [facebook/react-native#4467]
On 0.14.2...

JS errors sometimes "stick" in the `react-native bundle` phase when building with `xcodebuild -derivedDataPath` 

1. `xcodebuild -derivedDataPath X ... build`

        ...
        + react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output '.../X/Build/Products/Debug-iphonesimulator/Foo.app/main.jsbundle' --assets-dest '.../X/Build/Products/Debug-iphonesimulator/Foo.app'
        bundle: Created ReactPackager
        uncaught error Error: SyntaxError: /.../Bar.js: Unexpected token (506:6)
        ...

2. Fix my code
3. run build command again, same error =(
4. `xcodebuild -derivedDataPath X ... clean`
5. run build command again, success

I guess it has something to do with stuff that ends up in `derivedDataPath` and building from within xcode somehow creates like random paths for each build?

Happy to try and fix this if I can get some pointers...

**Comment by geirman** [comment]
@adbl sorry this has gone so long without any attention to it. Is this still an issue in 0.22? I'm not familiar with derivedDataPath, else I'd try to verify myself. Would you mind having another look and letting us know?

**Comment by geirman** [comment]
@facebook-github-bot label Needs Response from Author

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-8** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
