### ISSUE TITLE
After installing react-native-screens ios build not working - Error: info Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by durejagaurav** [facebook/react-native#44678]
### Description

I installed react-native-screens on my project. When I start npm and press i. Getting the following:

info Run CLI with --verbose flag for more details.

using React Native version 74.1

### Steps to reproduce

NA

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 92.72 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.2.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /usr/local/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
NA
```

### Reproducer

NA

### Screenshots and Videos

<img width="837" alt="Screenshot 2024-05-25 at 2 41 12 PM" src="https://github.com/facebook/react-native/assets/66942797/c6405a08-8900-4dca-a870-1717723c2f79">

**Comment by DonElect** [comment]
I am having same issue.

The project was fine until I installed react-native-screens. The react native version is 0.74.1 and I also added expo version 51.0.8. I ran npx react-native run-android. Below is part of the error I am getting:

 Task :react-native-screens:buildCMakeDebug[armeabi-v7a] FAILED
492 actionable tasks: 78 executed, 414 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

Note: C:\Users\User\Desktop\Primer Space Chat App\primer-space-chat-app-mobile\BuzzLine\node_modules\react-native-screens\android\src\paper\java\com\swmansion\rnscreens\NativeScreensModuleSpec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:buildCMakeDebug[armeabi-v7a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\User\Desktop\Primer Space Chat App\primer-space-chat-app-mobile\BuzzLine\node_modules\react-native-screens\android\.cxx\Debug\381q2a6h\armeabi-v7a'

**Comment by cortinico** [comment]
> I installed react-native-screens on my project. When I start npm and press i. Getting the following:

Hi @DonElect 
Thanks for reporting this issue.

You should be opening your issue against `react-native-screens` instead

https://github.com/software-mansion/react-native-screens/issues
