### ISSUE TITLE
token for a long time to create a new project 

### ISSUE THREAD

**Issue by inickel** [facebook/react-native#4468]
when i want to init a new project,it would token for a long time during the npm installing packages,
is there have another way to fixed this problem?
 such as make a easy project template in local file system,when i want to create a new project , just copy it to my dest project with some config.
xd~

**Comment by mihirsoni** [comment]
Hi @inickel 

``react-native init ProjectName`` install react-native and all other required packages from npm and create the Template project for the given ProjectName.
You can make your own changes for your requirements. But I believe it doesn't make sense to make change on react-native cli.

If this answers your question , please close the issue.

**Comment by ide** [comment]
The CLI is designed to download the latest version of react-native from npm. It doesn't include a template itself.

You can try a few things:
1. Use npm 2
2. Make sure you have a fast connection to the npm registry server

**Comment by inickel** [comment]
just a suggestion ,maybe someone face the same problem,ths for the all answers
