### ISSUE TITLE
Parent border is drawn over the child content

### ISSUE THREAD

**Issue by rafalmoneta** [facebook/react-native#44690]
### Description

Starting from version 0.74.0 of React Native, when fabric is enabled, the border of the parent element is rendered over its children elements on iOS. You can refer to the provided screenshot to visualize this issue. This behavior mirrors what's observed in iOS with Swift. However, it lacks compatibility with Android.

### Steps to reproduce

1. Install the application with `yarn ios`
2. [Enable the new architecture](https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md) 

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 101.33 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.0
    path: ~/.nvm/versions/node/v18.18.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.18.0/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.0/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/softwaremansion/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/softwaremansion/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
none
```

### Reproducer

https://github.com/rafalmoneta/react-native-border-issue

### Screenshots and Videos

| | Old Architecture | New Architecture |
| --- | --- | --- |
| 0.73 | <img width="447" alt="Screenshot 2024-05-27 at 13 26 17" src="https://github.com/facebook/react-native/assets/27514558/b48f8c61-0ff6-404a-9903-90be83cef1de"> | <img width="453" alt="Screenshot 2024-05-27 at 13 29 35" src="https://github.com/facebook/react-native/assets/27514558/a477793d-5ad8-4d92-aafd-f6d323fb2188"> |
| 0.74 | <img width="453" alt="Screenshot 2024-05-27 at 15 29 43" src="https://github.com/facebook/react-native/assets/27514558/7d143a64-ad7f-42f0-8e39-7141d42bc994"> | <img width="450" alt="Screenshot 2024-05-27 at 13 22 47" src="https://github.com/facebook/react-native/assets/27514558/3c35a65f-6c02-47a0-bc3a-0bcfcab626f9"> |

**Comment by rafalmoneta** [comment]
Upgraded.

**Comment by cortinico** [comment]
cc @j-piasecki

**Comment by j-piasecki** [comment]
I'll look into it
