### ISSUE TITLE
packager confused with RxJS which requires Node's EventEmitter

### ISSUE THREAD

**Issue by staltz** [facebook/react-native#447]
I'm experimenting with using Cycle with React Native. Cycle depends on RxJS's npm package, which in turn [requires Node's `'events'` package](https://github.com/Reactive-Extensions/RxJS/blob/master/index.js#L16-L17), which I suppose does not exist in whatever environment React Native is running in.

The consequence is a runtime error `Requiring unknown module "events"`. Cycle uses browserify, and the resulting bundle does not contain the RxJS code which requires 'events', that's why this runtime error does not happen with Cycle running in browsers.

I see some possible actions to solve this:
- Make `packager` work more like browserify, using the same solutions.
- packager warning, instead of runtime error, for unknown modules required.
- RxJS's npm package should not have Node-specific functions, but instead put those in a special purpose `rx.node.js` helper library. cc @mattpodwysocki 

I believe this issue affects not only Cycle, but any time anyone attempts to use RxJS together with React Native.

**Comment by vjeux** [comment]
There's a npm package called events which is the exact same code as node's events. https://www.npmjs.com/package/events

I wonder what happens if you add the events dependency on node, does it use node's one or does it use the npm installed one?

**Comment by staltz** [comment]
Well, that works. :P
Feel free to close this issue since I made also https://github.com/Reactive-Extensions/RxJS/issues/639 through, let's see how that one goes.

**Comment by vjeux** [comment]
I really want to make sure to find a good solution for sharing code between node, browser and react native. This would suck to lose all those great libraries just because we're using a slightly different but incompatible system.

The idea of bundling all the node modules by default like browserify is not out of the question, but I really don't want React Native to be in the game of keeping those libraries up to date with node and all the dependency management that it entails.

**Comment by jlmitch5** [comment]
Thanks for filing this issue.  I am attempting to combine the flux todomvc tutorial with react-native, and I ran into this issue.  +1 for including modules from node core...somehow :)

**Comment by amasad** [comment]
>packager warning, instead of runtime error, for unknown modules required.

We should really do that. Actually the packager does a ton of debug warnings, the reason it doesn't throw errors is probably a historic one. I'll look into it.

**Comment by amasad** [comment]
This is now fixed that we look at the `browser` field in the package.json. Tested using:

```js
var Rx = require('rx');
var obs = Rx.Observable.of(42);
obs.forEach(function (x) { alert(x); });
```

**Comment by abbothzhang** [comment]
m
