### ISSUE TITLE
[0.74.1] Npm install WARN

### ISSUE THREAD

**Issue by kbqdev** [facebook/react-native#44701]
### Description

I'm trying start new Project (0.74.1) but so many conflict and WARN and i don't know how to solve it.
![Screenshot 2024-05-29 at 14 13 35](https://github.com/facebook/react-native/assets/87011701/513e3075-3881-411c-b3e7-89dfbf7d61b3)

### Steps to reproduce

npx react-native init Name
rm -rf node_modules
npm install

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android, Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 33.88 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 19.0.0
    path: ~/.nvm/versions/node/v19.0.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v19.0.0/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v19.0.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/kieuquang/.rvm/gems/ruby-3.2.1/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.2.1
    path: /Users/kieuquang/.rvm/rubies/ruby-3.2.1/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: eslint-plugin-jest@26.9.0
npm WARN Found: @typescript-eslint/eslint-plugin@6.21.0
npm WARN node_modules/@typescript-eslint/eslint-plugin
npm WARN   @typescript-eslint/eslint-plugin@"^6.7.4" from @react-native/eslint-config@0.74.83
npm WARN   node_modules/@react-native/eslint-config
npm WARN     dev @react-native/eslint-config@"0.74.83" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @typescript-eslint/eslint-plugin@"^5.0.0" from eslint-plugin-jest@26.9.0
npm WARN node_modules/eslint-plugin-jest
npm WARN   eslint-plugin-jest@"^26.5.3" from @react-native/eslint-config@0.74.83
npm WARN   node_modules/@react-native/eslint-config
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm WARN deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 1144 packages, and audited 1145 packages in 31s

152 packages are looking for funding
  run `npm fund` for details
```

### Reproducer

https://github.com/brightkieu/shopping

### Screenshots and Videos

![Screenshot 2024-05-29 at 14 06 35](https://github.com/facebook/react-native/assets/87011701/0988209c-06b7-40cb-9956-24e62fc0ab77)

**Comment by cortinico** [comment]
Closing as duplicates of various similar issues:
- https://github.com/reactwg/react-native-releases/issues/239

This will be fixed in 0.74.2

**Comment by kbqdev** [comment]
<img width="718" alt="Screenshot 2024-06-15 at 18 01 14" src="https://github.com/facebook/react-native/assets/87011701/458ca2ee-a42f-47aa-9cb3-54d8e885475b">

Still got warning

**Comment by kbqdev** [comment]
npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

1. npm ls inflight@1.0.6
└─┬ @react-native/codegen@0.74.84
  └─┬ glob@7.2.3
    └── inflight@1.0.6
2. npm ls @babel/plugin-proposal-optional-catch-binding@7.18.6
└─┬ @react-native/babel-preset@0.74.84
  └── @babel/plugin-proposal-optional-catch-binding@7.18.6
 3.  npm ls @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
 ├─┬ @react-native/babel-preset@0.74.84
│ └── @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
└─┬ @react-native/codegen@0.74.84
  └─┬ jscodeshift@0.14.0
    └── @babel/plugin-proposal-nullish-coalescing-operator@7.18.6
 4. npm ls @babel/plugin-proposal-class-properties@7.18.6 ├─┬ @react-native/babel-preset@0.74.84
│ └── @babel/plugin-proposal-class-properties@7.18.6
└─┬ @react-native/codegen@0.74.84
  └─┬ jscodeshift@0.14.0
    └── @babel/plugin-proposal-class-properties@7.18.6 deduped
 5. npm ls @humanwhocodes/config-array@0.11.14
 └─┬ eslint@8.57.0
  └── @humanwhocodes/config-array@0.11.14
