### ISSUE TITLE
Metro is not starting on custom port

### ISSUE THREAD

**Issue by hariomsharma-jmd** [facebook/react-native#44700]
### Description

Metro is not starting on custom port. It is always starting on 8081 port.
I am using below command.
npm start -- --port=8087

<img width="674" alt="image" src="https://github.com/facebook/react-native/assets/10772719/c1865b0e-b87a-40fe-a3fd-3ac723bd5277">

I initialized new project.
RN Version - v0.74.1
OS- Windows

### Steps to reproduce

Start metro using npm start -- --port=8087

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22621
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
  Memory: 14.26 GB / 31.66 GB
Binaries:
  Node:
    version: 18.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11255304
  Visual Studio: Not Found
Languages:
  Java: 11.0.21
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
..
```

### Reproducer

.

**Comment by cortinico** [comment]
Cannot reproduce, just tested on a 0.74.1 project:

![Screenshot 2024-06-04 at 11 40 43](https://github.com/facebook/react-native/assets/3001957/fbef07df-ef78-40b1-926f-02fa56a6831e)

I suspect the problem is with the react native CLI + you using Windows.
Please open a new issue here:

https://github.com/react-native-community/cli/issues
