### ISSUE TITLE
DatePickerIOS

### ISSUE THREAD

**Issue by lewisbarber** [facebook/react-native#4473]
Is it possible to change the font color of the DatePickerIOS text? I have it on a black background and can't read the black text...

Passing color:'white' in the style param doesn't work, and from looking at the source code it looks like a RCTDatePickerIOS element is wrapped in a view. I can change the background color of this view, so the black text is legible, but this is not really ideal.

**Comment by mihirsoni** [comment]
Hi @lewisbarber ,

As iOS docs says  there is no official API for changing appearance.  [You cannot customize the appearance of date pickers](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UIDatePicker.html#//apple_ref/doc/uid/TP40012857-UIDatePicker)

**Comment by christopherdro** [comment]
Related #3768

**Comment by teebolt** [comment]
Anyone find a workaround for this? Would love to change the text color of the date picker.

**Comment by quangas** [comment]
Go to React.xcodeproj/views/RCTDatePickerManager.m

Replace the view with this - choose your own color. Tested on iOS 7 - 9.3

- (UIView *)view
{
 RCTDatePicker *datePicker = [RCTDatePicker new];
 [datePicker setValue:[UIColor whiteColor] forKeyPath:@"textColor"];
 
 return datePicker;
}

**Comment by nitrogenlabs** [comment]
Just created a PR that will solve this problem.

https://github.com/facebook/react-native/pull/10356

**Comment by sexykodo** [comment]
Hi, i tried @quangas solution, but doesn't see to work for me with RN 0.35, any hint?

**Comment by omar-salah-elboredy** [comment]
@maurovisintin I think you have to run the project in Xcode after applying edit you want, not using `react-native run-ios`
