### ISSUE TITLE
React native downloading react-android-0.74.1-debug.aar again and again wtih so slow speed

### ISSUE THREAD

**Issue by theahmadzai** [facebook/react-native#44750]
### Description

I'm setting up environment for React Native development, The android packages are downloaded so fast but it's stuck on to download `react-android-0.74.1-debug.aar` from the past 3 days, I'm tried multiple times I thought it's always downloading different packages but when I noticed it's always this file, it takes 30 minutes and starts again

2 GB of Android packages take 5 minutes to download, but this one file of 250 MB takes 30 minutes to download and restarts downloading

### Steps to reproduce

A clean install of android studio and react native's latest version on a new machine

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android, Build - Windows

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 3600 6-Core Processor              "
  Memory: 4.15 GB / 15.93 GB
Binaries:
  Node:
    version: 22.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "34"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-232.10300.40.2321.11668458
  Visual Studio: Not Found
Languages:
  Java:
    version: 17.0.9
    path: /c/Program Files/Android/Android Studio/jbr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
None
```

### Reproducer

None

### Screenshots and Videos

![image](https://github.com/facebook/react-native/assets/9446563/93cefef2-7dbc-42d5-9196-fc38ccceaecb)

**Comment by theahmadzai** [comment]
It downloaded and finished the process on 2nd try now successfuly, but it was a very bad experience with so slow download.

**Comment by cortinico** [comment]
> 2 GB of Android packages take 5 minutes to download, but this one file of 250 MB takes 30 minutes to download and restarts downloading

This is outside our control. The file is hosted on Sonatype's CDN so if they experience some slowness there is really nothing we can do.
