### ISSUE TITLE
SliderIOS allow custom images for the left and side of track

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#4476]
Instead of setting one image for both as done [here](https://github.com/facebook/react-native/blob/9fc3991615b5dd6815713697945dd5d9bc300a66/React/Views/RCTSlider.m#L42-L46), it would be nice to be able to set an image for both sides and be able to customize the cap insets.

**Comment by satya164** [comment]
@rclai Would be great if you can send a pull request.
