### ISSUE TITLE
Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4477]
![image](https://cloud.githubusercontent.com/assets/51059/11515042/b9a260ca-9849-11e5-9bf1-6f1b2242bf2b.png)
![image](https://cloud.githubusercontent.com/assets/51059/11515046/bfe08bce-9849-11e5-9c7c-d23f081ea39b.png)
```
Cannot read property '_currentElement' of null
handleException	@	ExceptionsManager.js:63
handleError	@	InitializeJavaScriptAppEngine.js:76
ErrorUtils.reportFatalError	@	error-guard.js:28
guard	@	MessageQueue.js:41
callFunctionReturnFlushedQueue	@	MessageQueue.js:82
messageHandlers.executeJSCall	@	debuggerWorker.js:25
onmessage	@	debuggerWorker.js:42
```

**Comment by msathis** [comment]
@cancan101 From my experience, This error mostly happens if any of the component is null.

**Comment by cancan101** [comment]
That might be the case though perhaps this ticket should be modified that better error logging is provided in these cases (e.g. which Component is rendering with null).

**Comment by satya164** [comment]
@cancan101 Can you share the code which is causing this?

**Comment by sethx** [comment]
I'm getting the same thing when doing navigator.pop and when changing the visibility state of a <Modal>. Only get this since 0.16.0 and the code surrounding this hasn't really changed.

**Comment by sethx** [comment]
@msathis: Can you explain what you mean by "a component is null" ?

**Comment by stereodenis** [comment]
I get this, when don't createFactory from component, cause I don't use jsx

**Comment by sethx** [comment]
Solved my issue. It was caused by multiple <Text> Elements not being wrapped within a <View> inside of a <TouchableHighlight>. The error is really cryptic though, should be improved.

**Comment by ide** [comment]
This error is pretty obscure and seems to happen after another error occurs in React and puts it in a bad state. Would be super great if someone could send a PR to React to address it.

**Comment by satya164** [comment]
Closing this since there is no reproducible example and this has more to do with React than React Native.
