### ISSUE TITLE
Animation problem with 64 bits architecture

### ISSUE THREAD

**Issue by axelhzf** [facebook/react-native#448]
I'm having problems with animation in 64 bits devices (iPhone 5s +)

I think the problems is in the RCTAnimationManager.m:155

```
[fromValue getValue:fromFields];
```
This code is trying to store a float into a CGFloat

And CGFloat is defined as double for 64 bits architecture

CGBase.h:228

````
#if defined(__LP64__) && __LP64__
# define CGFLOAT_TYPE double
# define CGFLOAT_IS_DOUBLE 1
# define CGFLOAT_MIN DBL_MIN
# define CGFLOAT_MAX DBL_MAX
#else
# define CGFLOAT_TYPE float
# define CGFLOAT_IS_DOUBLE 0
# define CGFLOAT_MIN FLT_MIN
# define CGFLOAT_MAX FLT_MAX
#endif

/* Definition of the `CGFloat' type and `CGFLOAT_DEFINED'. */

typedef CGFLOAT_TYPE CGFloat;
```

**Comment by vjeux** [comment]
cc @a2

**Comment by a2** [comment]
Everything you're saying seems valid, but I don't see why that line is the problem? CoreAnimation uses `CGFloat` values (and `CGFloat`-based structs like `CGPoint`, `CGSize`, `CGRect`) for all FP values.

**Comment by jaygarcia** [comment]
It's worth noting that __LP64__ is set and means "Leopard 64bit (and greater)". 

This apple code works across all recent Apple  systems without a hitch.  

JG

301.785.6030 :: @moduscreate

:: sent from my mobile device ::

**Comment by axelhzf** [comment]
Yes, using `CGFloat` to do animations is the right thing to do. 
The problem is to copy a `float` to a `CGFloat`. It doesn't get the right value and the animations doesn't work.

I can make an example to illustrate the problem if you want.

**Comment by a2** [comment]
@axelhzf An example project with a repro case would help immensely. Thanks!

**Comment by axelhzf** [comment]
This is the code

https://github.com/axelhzf/AnimationProblem/blob/master/index.ios.js

The animation works on iPhone 5 simulator, but not on iPhone 5s simulator

**Comment by brentvatne** [comment]
The animation module has been renamed to `RCTAnimationExperimentalManager` and is on its way out, it's suggested that you use an existing React library like `react-tween-state` for animations in the meantime, as it is likely that you will have many issues with `RCTAnimationExperimentalManager`.
