### ISSUE TITLE
React native webview image download without external storage permission

### ISSUE THREAD

**Issue by DARPANMANEK** [facebook/react-native#44802]
### Description

https://www.npmjs.com/package/react-native-webview

I am using this library for webview in react native I put image url link in source of webview and it download image automatically without any permission.

### Steps to reproduce

create a new react native app add react-native-webview and put any image url in source of webview component

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Memory: 4.53 GB / 15.78 GB
Binaries:
  Node:
    version: 20.14.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.4.0
    path: ~\AppData\Roaming\npm\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: javac 20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
no
```

### Reproducer

https://github.com/DARPANMANEK/react-native-webview-demo

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-native-webview/react-native-webview/issues
