### ISSUE TITLE
Wrong orientation width and height values on iPad only,

### ISSUE THREAD

**Issue by ChadyAyoub4** [facebook/react-native#44801]
### Description

The orientation width are values are reveresed on ipad until i put the ipad in a rotation that is parallel to the ground.

### Steps to reproduce

just add this code in app.js 
const SCREEN_WIDTH = useWindowDimensions().width;
  const SCREEN_HEIGHT = useWindowDimensions().height;

  console.log({ SCREEN_HEIGHT, SCREEN_WIDTH });

on ios mobile it works fine however in iPad the width and height values are swapped and when i put the ipad in a flat position it then returns the correct values.
i also tried loggin metrics in the useWindowDimensions and commented out the if statement. It seems that the values are not correctly updated until the ipad is in a flat like position. but rotating it left and right does not correctly updates the values

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3
  CPU: (10) x64 Apple M1 Pro
  Memory: 46.21 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman:
    version: 2024.04.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/chadyayoub/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/chadyayoub/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
no crash, just orientation issue on ios on ipad only
```

### Reproducer

https://github.com/ChadyAyoub4/react-native-orientation-bug-reproducer

**Comment by ChadyAyoub4** [comment]
i have updated the version to 0.74.2 and the issue persists. However i found out that on a new project the issue does not happen. Does anyone have a clue on what might the issue be.

**Comment by cortinico** [comment]
> However i found out that on a new project the issue does not happen

What do you mean with this? Where is the issue happening exactly?

**Comment by ChadyAyoub4** [comment]
False alarm, this bug was caused by a library i had that was not correctly configured after converting from appDelegate.m to appDelegate.mm

**Comment by ChadyAyoub4** [comment]
False alarm, this bug was caused by a library i had that was not correctly configured after converting from appDelegate.m to appDelegate.mm

**Comment by HeavenMin** [comment]
> False alarm, this bug was caused by a library i had that was not correctly configured after converting from appDelegate.m to appDelegate.mm

Can you give more information about this issue? I'm having the same problem as you on my ipad.

**Comment by ChadyAyoub4** [comment]
@HeavenMin I was using react-native-home-indicator, which requires setup in AppDelegate.m, but after upgrading react-native 0.73 it was changed to AppDelegate.mm and some of the functions got removed and some were changed. 
I Needed to remove the old code related to RNHomeIndicator.h in appdelegate.mm and add this function
- (UIViewController *)createRootViewController
{
  return [HomeIndicatorViewController new];
}

**Comment by jameswilddev** [comment]
Might be fixed by this https://github.com/facebook/react-native/pull/46353
