### ISSUE TITLE
0.15-0.16-rc Version of the problem

### ISSUE THREAD

**Issue by qiepei123** [facebook/react-native#4484]
0.15-0.16 - rc version to execute commands run - android system CARDS maxed out, hope the official will give solution

**Comment by satya164** [comment]
Hey @qiepei123 . Thanks for the issue. But I didn't quite get what you said. Can you explain a bit?

**Comment by yychun1217** [comment]
@satya164 There is a red page after I upgrade the react native version to 0.16.0-rc.

Upon opening the app, the red page appears.

![Image of error]
(http://postimg.org/image/wfb42hddj/)

**Comment by satya164** [comment]
Cannot see the image. Can you re-upload?

**Comment by satya164** [comment]
@qiepei123 Any news?
