### ISSUE TITLE
Can't run project made with react-native init

### ISSUE THREAD

**Issue by TomClarkson** [facebook/react-native#4485]
When I try to run the hello world app i get heaps of syntax errors. Please tell me how can I fix it?

![screen shot 2015-12-02 at 6 55 50 pm](https://cloud.githubusercontent.com/assets/2054503/11523300/eeaa9328-9925-11e5-91bc-c8f07812d677.png)

**Comment by ide** [comment]
My guess is you are using an old version of Xcode. Can you check whether you are using Xcode 7?

**Comment by sankhadeeproy007** [comment]
I had a RN 0.13.2 project which was working fine on Xcode 6. Now after upgrading 0.16.0-rc and Xcode 7.1 I'm getting `Command /bin/sh failed with exit code 1` on building. My node version is 4.2.1 and npm is 3.4.0. The solution at #3948 doesn't seem to work for me either. Any help regarding this?

**Comment by TomClarkson** [comment]
Upgraded Xcode to 7.1.1 fixed all errors. Thank you.
