### ISSUE TITLE
If users runs the react-native app with bad network

### ISSUE THREAD

**Issue by huangqiaobo** [facebook/react-native#4486]
If users runs the react-native app with bad network, they may need to wait a long time to load bundle.
How to deal with this situation？

**Comment by ide** [comment]
During development, the bundle is loaded over your local network so it should be fast. In production, if you want to download the bundle then you should make sure your servers have a fast connection with users (lots of different optimizations possible but they aren't specific to React Native. you could probably hire a performance consultant  though) and write whatever caching policy you want. It's really up to you -- React Native is very flexible here.

**Comment by huangqiaobo** [comment]
@ide 
do I need this?
such as always load bundle from local and download newest bundle for use for next time。
do you have better plan to recomment it ?

**Comment by ide** [comment]
@huangqiaobo during development, your app downloads the JS bundle from your computer. When you publish your app, React Native will add the JS bundle to your app so that users don't have to download it at all. That is the fastest and simplest solution.
