### ISSUE TITLE
Downloading template error

### ISSUE THREAD

**Issue by wildman82** [facebook/react-native#44892]
### Description

Hi,

For the past few months I am receiving a "Downloading template error Installing pods failed"

### Steps to reproduce

I have tried the following command (previously react-native has been working fine):

npx --yes react-native@latest init <projectName> --version "latest"

### React Native Version

react-native: n/a - not inside a React Native project directory

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```

### Stacktrace or Logs

```text
| Downloading templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed.
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

× Downloading template
```

### Reproducer

https://microsoft.github.io/react-native-windows/docs/getting-started

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core but related to the Community CLI. Please open your issue against:

https://github.com/react-native-community/cli/issues
