### ISSUE TITLE
RN The official scaffolding project introduced bundlejs and modified it again, but the hot update could not be triggered

### ISSUE THREAD

**Issue by nianxiongdi** [facebook/react-native#44917]
### Description

1. install project 
```js
npx react-native@latest init AwesomeProject

```
2. Description
Introduced in app.tsx. official scaffolding、official scaffolding、official scaffolding、official scaffolding

```js
const infos = require('./infos')



const App = () => {

  <View>

  <<infos />
</view>
}
     
export default App;
````
3. Modify file A and cannot trigger hot.

4. I would like to ask how to trigger my bundlejs file through metro and trigger hot update again.

5. Thank you very much.

### Steps to reproduce

none

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
none
```

### Stacktrace or Logs

```text
none
```

### Reproducer

none

**Comment by nianxiongdi** [comment]
same problem.

**Comment by nianxiongdi** [comment]
```js
// source code of metro
const inject = ({ module: [id, code], sourceURL }) => {
  if (global.globalEvalWithSourceUrl) {
    global.globalEvalWithSourceUrl(code, sourceURL);
  } else {
    eval(code);
  } 
};
```
uuring the second update code, it was found that `the code and sourceURL` were the latest, but the original components were used when rendering. The component is not updated.

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/44890
