### ISSUE TITLE
Not able to run my react-native app

### ISSUE THREAD

**Issue by Kbamborde** [facebook/react-native#44945]
### Description

Whenever I try to run the command `npm start` in my newly created react-native project I am getting the following error trying to run the same command with --verbose flag gives the same output.

![Screenshot 2024-06-14 172855](https://github.com/facebook/react-native/assets/95536083/3e496441-1aa0-43e1-a3b8-fbeb18af7482)

### Steps to reproduce

1) Create a new project using npm @react-native-comunnity/cli@latest init AppName
2) Run the command `npm start`

### React Native Version

0.74

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Memory: 5.40 GB / 15.86 GB
Binaries:
  Node:
    version: 20.14.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 34.0.0
    System Images:
      - android-34 | Google APIs Intel x86_64 Atom      
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-233.14808.21.2331.11926650
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
NA
```

### Reproducer

NA

**Comment by cortinico** [comment]
This a Gradle issue:
- https://github.com/gradle/gradle/issues/27844

The recommended workaround is to update your:
`android/gradle/wrapper/gradle-wrapper.properties`

as follows

```diff
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/46210
