### ISSUE TITLE
useWindowDimensions does not work for Expo 51

### ISSUE THREAD

**Issue by GHEAD1802** [facebook/react-native#44946]
### Description

I have create new app using epxo 51 Template and i am trying to implement usewindowDimensions to keep my container inside screen responsive when screen rotates, but it does not work

### Steps to reproduce

Do -npm install -npx expo start to start app

### React Native Version

0.74.2

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
expo-env-info 1.2.0 environment info:
System:
OS: macOS 13.6.4
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.11.1 - /usr/local/bin/node
Yarn: 1.22.21 - /opt/homebrew/bin/yarn
npm: 10.2.4 - /usr/local/bin/npm
Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
Managers:
CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
IDEs:
Xcode: 15.2/15C500b - /usr/bin/xcodebuild
npmPackages:
expo: ~51.0.14 => 51.0.14
react: 18.2.0 => 18.2.0
react-native: 0.74.2 => 0.74.2
npmGlobalPackages:
eas-cli: 9.1.0
expo-cli: 6.3.10
Expo Workflow: managed
```

### Stacktrace or Logs

```text
I don't have any crash but it's front end issue which does not render original functionality of usewindowDimensions
```

### Reproducer

https://github.com/GHEAD1802/Test-APP.git

### Screenshots and Videos

https://github.com/facebook/react-native/assets/40683262/74921c3b-0e0d-48b8-90e0-c5a742e6236d

**Comment by GHEAD1802** [comment]
This issue was originally created with expo and they passed it to React-native as useWindowDimensions id under react native.
Here is the Link for your reference
https://github.com/expo/expo/issues/29746
Issue #29746

**Comment by jtmaddux** [comment]
@GHEAD1802 i see this was closed on both expo and react side did you get any resolution?  I have the same issue.

**Comment by redkean** [comment]
I'm also experiencing this issue and it seems to be a problem on Expo side.

I tried creating a minimal reproduction with:
```jsx
import {View, Text, useWindowDimensions} from 'react-native';

export default function App() {
  const {width, height} = useWindowDimensions();

  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Width: {width}</Text>
      <Text>Height: {height}</Text>
    </View>
  );
}
```
then created a release build using **EAS** and the results works as expected.

**Comment by jtmaddux** [comment]
I posted a new issue on expo side to hopefully get help on this:
https://github.com/expo/expo/issues/32024
