### ISSUE TITLE
codegen - 0.74: Int32 | null generates Nullable Integer on java side, but Ljava/lang/Double on c++ side.

### ISSUE THREAD

**Issue by mfazekas** [facebook/react-native#44963]
### Description

In RN 0.74 we started to see `Error: Exception in HostFunction: no non-static method "Lcom/rnmapbox/rnmbx/components/mapview/NativeMapViewModule;.setHandledMapChangedEvents(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V`

We implement the function as 
```kotlin
   typealias ViewRefTag = Int

   ...

   override fun setHandledMapChangedEvents(
        viewRef: ViewRefTag?,
        events: ReadableArray,
        promise: Promise
    ) {
```

### Codespec: Int32
Our [maps/src/specs/NativeMapViewModule.ts](https://github.com/rnmapbox/maps/blob/34db17e58f5b8c23ed55d0820b423f5a2cd30850/src/specs/NativeMapViewModule.ts#L41-L44) has:

```ts
setHandledMapChangedEvents: ( viewRef: Int32 | null,  events: ReadonlyArray<string>) => Promise<Object>; 
```

### specs-generated.cpp: java.lang.Double

Codegen generated cpp: `android/build/generated/source/codegen/jni/rnmapbox_maps_specs-generated.cpp` has `Ljava/lang/Double`
```cpp
static facebook::jsi::Value __hostFunction_NativeMapViewModuleSpecJSI_setHandledMapChangedEvents(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
  static jmethodID cachedMethodId = nullptr;
  return static_cast<JavaTurboModule &>(turboModule).invokeJavaMethod(rt, PromiseKind, "setHandledMapChangedEvents", "(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V", args, count, cachedMethodId);
}
```

### ModuleSpec.java: java.lang.Integer

Codegen generate-specs-cli.js generated [maps/android/src/main/old-arch/com/rnmapbox/rnmbx/NativeMapViewModuleSpec.java](https://github.com/rnmapbox/maps/blob/34db17e58f5b8c23ed55d0820b423f5a2cd30850/android/src/main/old-arch/com/rnmapbox/rnmbx/NativeMapViewModuleSpec.java#L78-L80) has as:

```java
public abstract void setHandledMapChangedEvents(@Nullable Integer viewRef, ReadableArray events, Promise promise); 
```

See https://github.com/rnmapbox/maps/pull/3527

### Steps to reproduce

1.) check out the main branch of the `rnmapbox/maps` repository
2.) install modules
```
yarn generate
cd example
yarn install
```

3.) change `newArchEnabled` to `newArchEnabled=true` in `example/android/gradle.properties`
4.) Build the project 

    ```
    cd example/android
    ./gradlew assembleDebug
    ```
    
Check the files mentioned in description

### React Native Version

0.74.2

### Affected Platforms

Runtime - Android

### Areas

TurboModule - The New Native Module System, Codegen

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.5
  CPU: (12) arm64 Apple M2 Max
  Memory: 83.89 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.2
    path: ~/.nvm/versions/node/v18.20.2/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.20.2/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.20.2/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/boga/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /Users/boga/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Error: Exception in HostFunction: no non-static method "Lcom/rnmapbox/rnmbx/components/mapview/NativeMapViewModule;.setHandledMapChangedEvents(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V"
                                                                                                    
This error is located at:
    in MapView (created by SetTintColor)
    in RCTView (created by View)
    in View (created by SetTintColor)
    in SetTintColor
    in RCTView (created by View)
    in View (created by Page)
    in Page
    in Unknown (created by Item)
    in Item (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous) (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by AppStackNavigator)
    in AppStackNavigator (created by AppContainer)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by AppContainer)
    in AppContainer (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in RNMapboxGLExample(RootComponent), js engine: hermes
```

### Reproducer

https://github.com/rnmapbox/maps

**Comment by cortinico** [comment]
Is this a regression from 0.73 to 0.74 @mfazekas ?

**Comment by mfazekas** [comment]
@cortinico yes I believe so. At least the error - `Error: Exception in HostFunction: no non-static method "Lcom/rnmapbox/rnmbx/components/mapview/NativeMapViewModule;.setHandledMapChangedEvents(Ljava/lang/Double;Lcom/facebook/react/bridge/ReadableArray;Lcom/facebook/react/bridge/Promise;)V` we've not encountered with 0.73.

But looking at the sources this part was not touched in 4 years.
https://github.com/facebook/react-native/blame/9922628032ace4d87257c1b3d70c2dc6c38a60a6/packages/react-native-codegen/src/generators/modules/GenerateModuleJniCpp.js#L262-L263

So not sure why we started to face the issue now.

**Comment by cortinico** [comment]
@mfazekas Could we get a small repro using https://github.com/react-native-community/reproducer-react-native ? That would make it way easier for me to understand what happened.

**Comment by mfazekas** [comment]
@cortinico sure will try to do that

**Comment by mfazekas** [comment]
@cortinico so the issue is that in RN 0.73 
`GenerateModuleJavaSpec.js` has generated 

```diff
public abstract void setHandledMapChangedEvents(@Nullable Double viewRef, ReadableArray events, Promise promise); 
```

while RN 0.74 it's changed to:
```diff
- public abstract void setHandledMapChangedEvents(@Nullable Double viewRef, ReadableArray events, Promise promise); 
+ public abstract void setHandledMapChangedEvents(@Nullable Integer viewRef, ReadableArray events, Promise promise);
```

see
https://github.com/facebook/react-native/commit/ccd3b047709fda00123e8aec4294dce024b80244
https://github.com/facebook/react-native/pull/42126

But rest of RN 0.74 has not made this change.

https://github.com/facebook/react-native/blob/9922628032ace4d87257c1b3d70c2dc6c38a60a6/packages/react-native-codegen/src/generators/modules/GenerateModuleJniCpp.js#L262-L263

**Comment by mfazekas** [comment]
As for if it's a breaking change? I'm not 100% sure many modules like `react-native-svg` are generating it once, and haven't rerun with the changed codegen in RN 0.74. We've reran with @rnmapbox/maps that's why we've faced the issue. 

https://github.com/software-mansion/react-native-svg/blob/main/android/src/paper/java/com/horcrux/svg/NativeSvgRenderableModuleSpec.java

**Comment by cortinico** [comment]
This is indeed a bug. Fix for it is here:
- https://github.com/facebook/react-native/pull/45024

@mfazekas if you could try it with patch-package and report back, would be gold. We could include it in the next 0.74 patch release.

**Comment by mfazekas** [comment]
@cortinico 
I've tested it with patch-package, and it worked fine.
https://github.com/mfazekas/maps-1/commit/dbcf2b182ff86c1473f8cb207c459100ffee6018

Note that this fix, while looks great and is correct. Can actually cause issues in some case - like, the mentioned react-native-svg has  the spec generated with 0.73 or even older, so it might work because of the current but, but with next 0.74.* release they'll need to update those generated java code: https://github.com/software-mansion/react-native-svg/blob/main/android/src/paper/java/com/horcrux/svg/NativeSvgRenderableModuleSpec.java

**Comment by cortinico** [comment]
> I've tested it with patch-package, and it worked fine.

Great thanks for the confirmation 👍

> Note that this fix, while looks great and is correct. Can actually cause issues in some case

We're aware of this. That's why this change was marked as breaking + started from last version we added support for `includesGeneratedCode`:

https://github.com/facebook/react-native/blob/64d5de73719f407a8b7f2d718348d8139a77f32f/packages/react-native-test-library/package.json#L44

That will allow libraries to ship the generated code so that mismatch between codegen versions like this one won't happen again

**Comment by cortinico** [comment]
Ok so for React Native SVG the fix would be here:
- https://github.com/software-mansion/react-native-svg/pull/2309

@mfazekas have you noticed any similar failures?

**Comment by cortinico** [comment]
We ended up reverting the partial Int32/Float implementation, as attempting to fix it with the previous PR I linked would create more problems with libraries like `-svg` and others.

We'll get back to it in a future release.

**Comment by mensonones** [comment]
@cortinico
So, it will not be possible to use Int when mapping from TS to Java/Kotlin? (Sincere doubt)
