### ISSUE TITLE
Done Button In Keyboard

### ISSUE THREAD

**Issue by edo1493** [facebook/react-native#4499]
Hi guys, 
I am trying to look for a solution that is similar to this screenshot I have posted. I need a done button on top of the keyboard. The problem is that on a Multiline textfield I can't find a way to close the keyboard and access, for example, the TabBar. 

I was wondering if there were some solutions to this or if the only way is to have a look at the native code. 

I was also thinking that I could try to implement something that closes the keyboard when the textinput is tapped the second time, so if it's focused and you are tapping it again, the keyboard disappears. 

![img_1311](https://cloud.githubusercontent.com/assets/2309030/11534381/5f3374fe-9906-11e5-8243-2b7b220574b2.PNG)

**Comment by christopherdro** [comment]
Duplicate #641

**Comment by anitalanet** [comment]
Hi

We can do the focus on next textinput when user click on keyboard next button using refs property

Here is the demo

 <TextInput
                        placeholder='Password'
                        ref='Password'
                        placeholderTextColor={'#e68a00'}
                        returnKeyType={ "next" }
                        style={{height: 40, borderColor: '#e68a00', borderWidth: 1,padding:10,marginTop:10,borderWidth:1,borderRadius:3}}
                        onSubmitEditing={(event) => {
                         this.refs.CPassword.focus();}}
                        onChangeText={(text) => this.setState({tv_name_placeHolderText1 : text})}
                    />
                    <TextInput
                        placeholder='Confirm Password'
                        ref='CPassword'
                        onSubmitEditing={(event) => {
                         this.refs.PNumber.focus();}}
                        placeholderTextColor={'#e68a00'}
                        returnKeyType={ "next" }
                        style={{height: 40, borderColor: '#e68a00', borderWidth: 1,padding:10,marginTop:10,borderWidth:1,borderRadius:3}}
                        onChangeText={(text) => this.setState({tv_name_placeHolderText1 : text})}
                    />
