### ISSUE TITLE
Timers in the new architecture are not spec compliant

### ISSUE THREAD

**Issue by rubennorte** [facebook/react-native#45085]
### Description

`setTimeout`, `clearTimeout`, `setInterval` and `clearInterval` all have a different behavior regarding error handling compared to Web.

On Web, `setTimeout` and `clearTimeout` only throw when the callback argument isn't provided. They don't even throw when the callback isn't a function. `clearTimeout` and `clearInterval` never throw.

RN (in the new architecture) throws in many more cases:
* `setTimeout` and `setInterval` throw is any of the arguments is missing, or has the wrong type.
* `clearTimeout` and `clearInterval` throw if the argument is missing, isn't a number or isn't a registered timer.

We should align these behaviors with the Web (more details in https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-settimeout-dev).

### React Native Version

0.74.2 / main

### Affected Platforms

Runtime - Android, Runtime - iOS, Runtime - Web, Runtime - Desktop

### Areas

Bridgeless - The New Initialization Flow, Other (please specify)

**Comment by robik** [comment]
@rubennorte Should we also support passing function source string as first argument to be spec compliant? 🤔

**Comment by rubennorte** [comment]
> @rubennorte Should we also support passing function source string as first argument to be spec compliant? 🤔

oh, please no! :P

This is mostly focused on error handling, not about being 100% spec compliant (which, for cases like that, we shouldn't).
