### ISSUE TITLE
ReferenceError: Can't find variable: require (Using genymotion emulator on Windows 10)

### ISSUE THREAD

**Issue by TASimpson** [facebook/react-native#4510]
![image](https://cloud.githubusercontent.com/assets/11613404/11541727/6b3ec490-98f9-11e5-927b-59aa04599c35.png)

I created Nexus 6P for Genymotion, cannot get passed this error. I am on Windows 10

**Comment by bob3695** [comment]
I have seen this on Windows 10 when I don't have the dev server running. Did you run react-native start in the directory where your project is?

**Comment by mkonicek** [comment]
Yup, this is most likely because the dev server is not running. Let's reopen if that's not the case. We should improve the error message.

**Comment by TASimpson** [comment]
@bob3695  I got much closer! However now I am coming across this error: 

![image](https://cloud.githubusercontent.com/assets/11613404/11549787/c2958e60-992e-11e5-8f83-c889432fed7b.png)

I have react-native start running in one prompt and react-native run-android --emulator in the other

**Comment by bob3695** [comment]
That simply just looks like you have a require pointing at something that
doesn't exist. Check your require statements and make sure they are all
valid...specifically one that is looking in the appConfig folder.

**Comment by TASimpson** [comment]
@bob3695 THANK YOU! You were right, I missed an npm install step for something and that folder was missing completely.
