### ISSUE TITLE
[iOS 8] string.includes causes crash

### ISSUE THREAD

**Issue by sercanov** [facebook/react-native#4511]
Weird one.

ES6 string.prototype.includes function causes crash on iOS 8.
( https://developer.mozilla.org/tr/docs/Web/JavaScript/Reference/Global_Objects/String/includes ) 

This one crashes with "undefined is not a function"
`rowData.viewCount.includes("Million")`

This one not
`rowData.viewCount.indexOf("Million")`

**Comment by ide** [comment]
iOS 7 and 8 don't include the ES6 String methods. You can implement your own polyfill or use indexOf as you've pointed out.
