### ISSUE TITLE
Could not find generated setter for class com.facebook.react.views

### ISSUE THREAD

**Issue by maaz-msf** [facebook/react-native#45211]
Getting this issue suddenly from no where this morning app is crashing while running 
when i checked locgcat i got following :

0 StatusBar} Window{db20767 mode=1 rootTaskId=722 u0 com.awesomeproject/com.awesomeproject.MainActivity} Window{b51c00e mode=1 rootTaskId=1 u0 com.miui.miwallpaper.wallpaperservice.MiuiKeyguardPictorialWallpaper} Window{a47ba31 mode=1 rootTaskId=1 u0 com.miui.miwallpaper.wallpaperservice.ImageWallpaper} 
06-28 11:42:34.581   626   626 I hwcomposer: [HWCDisplay] [Display_0 (type:1)] fps:14.576963,dur:1989.44,max:1224.47,min:4.60  
06-28 11:42:34.746   965  1049 E Accelerometer: Acceleration: x:0.057000, y:7.991000, z:6.478000]
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: Error while updating prop fontFamily
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:291)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:111)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:321)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:248)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:422)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at java.lang.reflect.Method.invoke(Native Method)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.jni.NativeRunnable.run(Native Method)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at android.os.Handler.handleCallback(Handler.java:938)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at android.os.Looper.loop(Looper.java:236)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
06-28 11:42:34.804 19269 19364 E unknown:ViewManager: 	at java.lang.Thread.run(Thread.java:923)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: Exception in native call
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'fontFamily' in shadow node of type: RCTText
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:125)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:321)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:248)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:422)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.jni.NativeRunnable.run(Native Method)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:236)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:923)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$StringPropSetter.getValueOrDefault(ViewManagersPropertyCache.java:291)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:111)
06-28 11:42:34.814 19269 19364 E unknown:ReactNative: 	... 15 more

**Comment by maaz-msf** [comment]
issue is solved so closed immediately.
Thanks

**Comment by RohovDmytro** [comment]
> issue is solved so closed immediately.
How did you solve this issue?..

**Comment by maaz-msf** [comment]
did you have integrated native modules ?

**Comment by RohovDmytro** [comment]
@maaz-msf i have 100+ dependencies, so I guess yes, although I'm not sure.

Is this a warning due to Native Modules?

**Comment by maaz-msf** [comment]
not dependencies i mean custom native module for example :- let say you made any android java class and integrated that in react and then using functions from that class into react as native module ?
