### ISSUE TITLE
MapView example in the UIExplorer shows "Failed propType" warning

### ISSUE THREAD

**Issue by tehong** [facebook/react-native#4521]
When running the RN MapView UIExplorer example from the Master branch and running my own code that's built against the Master branch, warnings are seen with MapView prop "tintColor" and MapView overlays props "strokeColor" and "fillColor".   Screenshot is shown below.

![screen shot 2015-12-02 at 9 24 12 pm](https://cloud.githubusercontent.com/assets/13394121/11552596/2c3865fc-993b-11e5-89c9-bc6b79a87e72.png)

It looks like the latest implementation of the MapView is not able to deal with the color string correctly.

**Comment by christopherdro** [comment]
Related #2397.

What happening is the propTypes get changed from strings to integers before

**Comment by christopherdro** [comment]
Closing this. Will be tracked here #4547
