### ISSUE TITLE
[iOS] ScrollView inside ListView doesn't scroll well with multiple pan gestures

### ISSUE THREAD

**Issue by skatou** [facebook/react-native#4526]
Hi,

In my project I have a scrollview which is a subview of a listview, I noticed the bounce animation of the scrollview stop suddenly and the content offset reset, if I pan on the scrollview before the animation finished.

From native side I read the following code,
```objc
- (BOOL)_shouldDisableScrollInteraction
{
  UIView *JSResponder = [RCTUIManager JSResponder];
  if (JSResponder && JSResponder != self.superview) {
    BOOL superviewHasResponder = [self isDescendantOfView:JSResponder];
    return superviewHasResponder;
  }
  return NO;
}

- (void)handleCustomPan:(__unused UIPanGestureRecognizer *)sender
{
  if ([self _shouldDisableScrollInteraction]) {
    self.panGestureRecognizer.enabled = NO;
    self.panGestureRecognizer.enabled = YES;
  }
}
```
so the animation is interrupted because ListView becomes JSResponder, but this behavior is not proper in my case, I think interfaces should be provided so that lib user can have finer control.

Thanks.

**Comment by samuelkraft** [comment]
There's a thread about this on product pains. Hopefully we'll have a solution soon.
https://productpains.com/post/react-native/scrolling-ends-prematurely-in-scrollviews-embedded-in-a-parent-scrollview/

**Comment by brentvatne** [comment]
This is marked as solved on ProductPains now :) If you're still having the issue on 0.18 then please create a new issue on here, thanks! :rocket:
