### ISSUE TITLE
[v0.73 & 0.74] Hermes chrome debugging no longer working

### ISSUE THREAD

**Issue by bhandanyan-nomad** [facebook/react-native#45265]
### Description

Our iOS simulator devices are not appearing in chrome to debug since upgrading to v0.73. The devices still don't show with 0.74. It was working in v0.72 and before.

Android is not affected.

### Steps to reproduce

1. Build and run the iOS application
2. Open chrome://inspect/#devices  
3. No option to debug with hermes

### React Native Version

0.73.8 & 0.74.3

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (12) arm64 Apple M2 Pro
  Memory: 358.67 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/benjamin/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/benjamin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.8
    wanted: 0.73.8
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
```


### Stacktrace or Logs
N/A


### Reproducer

N/A

### Screenshots and Videos

_No response_

**Comment by cortinico** [comment]
Just tested on 0.74 and I'm able to attach to the Hermes debugger:
![Screenshot 2024-07-03 at 15 55 48](https://github.com/facebook/react-native/assets/3001957/b63a84e0-26b7-46ce-b700-2ec5bff3e574)

I've tried on several Android/iOS emulator and physical devices and it always works (both on 0.74 and also on 0.75). So this looks like a local misconfiguration of your environment

**Comment by bhandanyan-nomad** [comment]
I assumed as much so do you have any recommendation for what configuration(s) would be likely to cause this? Where should I look?

**Comment by cortinico** [comment]
> I assumed as much so do you have any recommendation for what configuration(s) would be likely to cause this? Where should I look?

I'm sorry but we don't offer support here, unless there is a valid reproducer with evidence that this is a bug for everyone on React Native.
We do receive too many issues for offering user support for everyone, I hope you will understand.

Please consider asking your question on StackOverflow here:
https://stackoverflow.com/questions/tagged/react-native

Thanks

**Comment by Hejifei** [comment]
Same, have you solved it ?

**Comment by bhandanyan-nomad** [comment]
@cortinico I just now figured out the issue - it's because i'm using a build configuration called "Local" instead of "Debug". Is it a requirement that we must use "Debug" configuration or should it work with any configuration name?

**Comment by cortinico** [comment]
> EDIT: I submitted this as a [new issue](https://github.com/facebook/react-native/issues/48168) with a reproducer

Let's continue the conversation over there
