### ISSUE TITLE
Android FlatList dynamically adds and deletes lists, the list shakes

### ISSUE THREAD

**Issue by pzhasaki** [facebook/react-native#45276]
### Description

I am using flatlist to simulate a message comment area. A message is added every 500ms and scrolls to the bottom. When the list exceeds the length, the header data needs to be deleted after the scrolling is completed. At this time, the list jitters.
It only appears on Android devices，that detail code : 
`
import React, { type VFC, useEffect, useRef, useState } from 'react';
import {
    FlatList,
    type NativeScrollEvent,
    type NativeSyntheticEvent,
    StyleSheet,
    Text,
    View,
} from 'react-native';

const styles = StyleSheet.create({
    container: {
        backgroundColor: '#ccc',
        height: 78,
        marginTop: 100,
        position: 'relative',
    },
});

const ITEM_HEIGHT = 26;

const getItemLayout = (_: any, index: number) => ({
    length: ITEM_HEIGHT,
    offset: ITEM_HEIGHT * index,
    index,
});
// render item
const renderItem = ({ item }: { item: any }) => (
    <View
        style={{
            alignItems: 'center',
            backgroundColor: 'red',
            height: 20,
            marginBottom: 6,
        }}
    >
        <Text style={{ color: '#fff' }}>{item?.text}</Text>
    </View>
);

let time = 0;
const log = (...args: any) => {
    let d = Date.now();
    [time, d] = [d, d - time];
    console.log(d.toString().padStart(5), ...args);
};

let contentH = 0;

const App: VFC = () => {
    const MAX = 10; // renderList max length
    const emptyLen = 3; // mock empty view
    const [renderList, setRenderList] = useState(() => new Array(emptyLen).fill({
            id: Math.random().toString(),
            text: Math.random().toString() + '-name',
        }));
    const bufferList = useRef(
        new Array(100).fill(0).map(() => ({
            id: Math.random().toString(),
            text: Math.random().toString() + '-name',
        })),
    );
    const listRef = useRef<FlatList<any>>(null);
    const [updateEnabled, setUpdateEnabled] = useState(true);
    const scrollTimer = useRef(0);

    // forbid scroll when person slide
    const onScrollBeginDrag = () => {
        if (scrollTimer.current) clearTimeout(scrollTimer.current);
        setUpdateEnabled(false);
        scrollTimer.current = setTimeout(() => {
            setUpdateEnabled(true);
        }, 1000);
    };

    const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
        const offsetY = event.nativeEvent.contentOffset.y;
        const contentHeight = event.nativeEvent.contentSize.height;
        const screenHeight = event.nativeEvent.layoutMeasurement.height;

        if (offsetY + screenHeight >= contentHeight) {
            const LEN = renderList.length;
            log('xxxxxxxxxxxxxxxxx', offsetY, screenHeight, contentHeight, LEN > MAX);
             if (LEN > MAX) {
                console.log('@slice----------------');
                // setRenderList(list => list.slice(-MAX));
            }
        }
    };

    const onContentSizeChange = (_, h) => {
        if (h > contentH) {
            console.log('@scroll-----------------');
            listRef.current?.scrollToEnd();
        }
        contentH = h;
    };

    useEffect(() => {
        const interval = setInterval(() => {
            if (updateEnabled && bufferList.current.length) {
                const newItem = bufferList.current.pop();
                log('@add');
                setRenderList(list => [...list, newItem]);
            }
        }, 1000);
        return () => clearInterval(interval);
    }, [updateEnabled, bufferList]);

    return (
        <View style={styles.container}>
            <FlatList
                data={renderList}
                ref={listRef}
                onScroll={handleScroll}
                renderItem={renderItem}
                keyExtractor={item => item?.id || Math.random().toString()}
                removeClippedSubviews={true}
                getItemLayout={getItemLayout}
                showsVerticalScrollIndicator={false}
                scrollEventThrottle={16}
                onContentSizeChange={onContentSizeChange}
                onScrollBeginDrag={onScrollBeginDrag}
            />
        </View>
    );
};

export default App;
`

### Steps to reproduce

run the code i provide

### React Native Version

0.62.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 581.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.18 - ~/Desktop/live/frontend-live-rn/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.11.27.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
none
```

### Reproducer

the container was provide by Client

### Screenshots and Videos

https://github.com/facebook/react-native/assets/78007999/21fc24c9-4faa-4209-83e9-984285e3b5ce

**Comment by mishkeTz** [comment]
I have the same issue on `0.73.8`. Any updates on this one?
