### ISSUE TITLE
how to pack the app for production

### ISSUE THREAD

**Issue by cmnstmntmn** [facebook/react-native#453]
i'm new to mobile programming, and there's something i could not get,
how can i use the app, after i put it on my mobile?

everything works fine, untill i remove the usb cable from phone, 
then i get the red screen

![red_screen](https://cloud.githubusercontent.com/assets/2312755/6887124/246b08e8-d65e-11e4-8a13-119b6619b22b.gif)

**Comment by nav** [comment]
You will need to change the ip address in AppDelegate.m from localhost to your private ip.

Example:

From:
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];

To:
jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.10:8081/index.ios.bundle"];

**Comment by cmnstmntmn** [comment]
@nav i know that, and it works, by changing the IP
but the problem i am facing with, occurs after i unplug the phone from computer

**Comment by glenjamin** [comment]
See #240.

If there's a way of doing this with a compile-time flag, that would be much neater.

**Comment by boopathi** [comment]
@glenjamin , you can have a `User Defined` build setting, and use a flag to choose between http url or file location.

**Comment by frantic** [comment]
Closing in favor of #240
