### ISSUE TITLE
Upstream autolinking improvements to React Native Core

### ISSUE THREAD

**Issue by szymonrybczak** [facebook/react-native#45302]
### Description

Recently we've landed few improvements to autolinking mechanism, but since autolinking was moved to Core we need to replicate these fixes:
- https://github.com/react-native-community/cli/pull/2387 which adds support for autolinking C++ Pure TurboModules on Android,
- https://github.com/react-native-community/cli/pull/2379 which introduces new option `--platform` with which only platform's specific Config is fetched.

cc: @cortinico

**Comment by cortinico** [comment]
Hey @szymonrybczak, so I could easily upstream https://github.com/react-native-community/cli/pull/2387

The other PR however is a bit more complicated (https://github.com/react-native-community/cli/pull/2379). The reason is that by default, the Android template will invoke `npx @react-native-community/cli config --platform "android"`. 

As `--platform "android"` got added only in the latest alpha, this is causing a failure on CI. I need to get back to it in the future

**Comment by szymonrybczak** [comment]
> As --platform "android" got added only in the latest alpha, this is causing a failure on CI. I need to get back to it in the future

But we can land this change in `main` so it'll wait for 0.76 release, right? We don't need to backport it

**Comment by cortinico** [comment]
> But we can land this change in `main` so it'll wait for 0.76 release, right? We don't need to backport it

@szymonrybczak I'm not sure I follow you

**Comment by szymonrybczak** [comment]
@cortinico Hm, maybe I didn't understand.
>As --platform "android" got added only in the latest alpha, this is causing a failure on CI. I need to get back to it in the future

If latest `main` is using latest alpha release of CLI why CI is failing when providing `--platform` flag for `config`?

**Comment by cortinico** [comment]
> If latest `main` is using latest alpha release of CLI why CI is failing when providing `--platform` flag for `config`?

That's a good question :) not sure why it's failing

**Comment by szymonrybczak** [comment]
@cortinico could you send me a job that failed, I can take a look :)

**Comment by cortinico** [comment]
@szymonrybczak here it is: https://github.com/facebook/react-native/pull/45360
Agree that error message is not ideal, this should improve it https://github.com/facebook/react-native/pull/45333

**Comment by szymonrybczak** [comment]
@cortinico thank you for working on these! :pray:
