### ISSUE TITLE
> @fannnzhang is the issues similar to this? #45217

### ISSUE THREAD

**Issue by satheshrgs-rksv** [facebook/react-native#45310]
> @fannnzhang is the issues similar to this? #45217

I think it doesn't seem to be the case. There are quite a few memory leaks in the current new version. So far, I have discovered at least two. One is related to this PR, and the other is in the call chain of FabricUIManager, where a reference to the Activity is held and not released. I will take some time to organize this issue further and might raise an issue and a PR for it later.

_Originally posted by @fannnzhang in https://github.com/facebook/react-native/issues/45261#issuecomment-2213159253_

**Comment by cortinico** [comment]
Closing this and I'd let @fannnzhang open a proper issue with reproducer once he's ready
