### ISSUE TITLE
When calling the Image.getSize method, an error is reported. 

### ISSUE THREAD

**Issue by nianxiongdi** [facebook/react-native#45339]
### Description

When calling the Image.getSize method, an error is reported. The error message is `failed to get size for image  https://xxxx/xxx.png`

### Steps to reproduce

scaffolding tools

### React Native Version

0.73.0

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
failed to get size for image  https://xxxx/xxx.png
```

### Reproducer

-

**Comment by cortinico** [comment]
Please provide a valid repro

**Comment by efstathiosntonas** [comment]
@cortinico I've starting getting this error on iOS with images being picked by the library on 0.74.3


```
Failed to getSize of file:///var/mobile/Containers/Data/Application/1CFA2DA2-6D24-44E1-A36C-BA4D579EE700/tmp/AA057E22-3A8E-4ABD-A01A-D15B44BB9FF3.jpg
```

this is the full stack trace: 

![Screenshot 2024-07-26 at 12 12 08](https://github.com/user-attachments/assets/84919b49-2cd3-414d-a174-243ea7af800a)


It's hard to repro, I use react-native-image-crop-picker and it appears it's totally random.
