### ISSUE TITLE
REACT NATIVE 0.74.3 Signed Release APK Issue

### ISSUE THREAD

**Issue by contactahsanraza** [facebook/react-native#45361]
### Description

0

I am using React Native Latest version 0.74.3 for developing an APP. My App works fine if I ran this on Emulator with np react-native run-android.

When I try to generate the Signed APK for Android using Android Studio I am facing issue, but same android studio works fine for generating a signed apk for my another react native project which was developed in 0.74.2. here is the Build Error on Release.

### Steps to reproduce

1. Install React native 0.74.3
2. Create an APP is VS Code
3. Generate a signed APK using Android Studio

### React Native Version

0.74.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
"Execution failed for task ':app:checkReleaseDuplicateClasses'.


Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output."
```

### Stacktrace or Logs

```text
Could not resolve all files for configuration ':app:releaseRuntimeClasspath'. Failed to transform react-android-0.74.3-release.aar (com.facebook.react:react-android:0.74.3) to match attributes {artifactType=enumerated-runtime-classes, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}. > Could not download react-android-0.74.3-release.aar (com.facebook.react:react-android:0.74.3): No cached version available for offline mode Failed to transform hermes-android-0.74.3-release.aar (com.facebook.react:hermes-android:0.74.3) to match attributes {artifactType=enumerated-runtime-classes, com.android.build.api.attributes.BuildTypeAttr=release, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}. > Could not download hermes-android-0.74.3-release.aar (com.facebook.react:hermes-android:0.74.3): No cached version available for offline mode
```

### Reproducer

https://github.com/facebook/react-native/releases

### Screenshots and Videos

![BuildEerr](https://github.com/facebook/react-native/assets/130341834/19a359f8-3c4d-42ce-a257-8f0f8473450e)

**Comment by migueldaipre** [comment]
Looks like you were offline. 

`...(com.facebook.react:hermes-android:0.74.3): No cached version available for offline mode`

**Comment by contactahsanraza** [comment]
No My internet is working fine I am not In offline mode as I can generate another Project Relase APK but that is in 0.74.2 react version

**Comment by contactahsanraza** [comment]
> Looks like you were offline.
> 
> `...(com.facebook.react:hermes-android:0.74.3): No cached version available for offline mode`

No My internet is working fine I am not In offline mode as I can generate another Project Relase APK but that is in 0.74.2 react version

**Comment by Hammad089** [comment]
buildscript {
    ext {
        buildToolsVersion = "32.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 32
        androidXBrowser = "1.4.0"
        
        kotlinVersion = "1.8.0"
    }
...
}You can fix it by adding kotlinVersion in your build.gradle config:
Update kotlinVersion

**Comment by cortinico** [comment]
>  No cached version available for offline mode

You have Gradle offline mode configured somewhere (either in the Android Studio settings) or in the CLI or so on.
