### ISSUE TITLE
Websocket connection for debugging leaks memory on iOS devices [0.15]

### ISSUE THREAD

**Issue by deviantintegral** [facebook/react-native#4540]
* Create a new project with react-native init
* Set the appropriate IP / hostname of your packager and debugger
* Build and run on a physical device
* Enable debugging in Chrome
* Watch memory rapidly grow

![memorytest xcodeproj 2015-12-03 10-32-01](https://cloud.githubusercontent.com/assets/255023/11564811/17b7e512-99a9-11e5-91e8-35c2d2a69fc8.jpg)

In the debugger / instruments, once the app is bootstrapped there's no JS or other code running except for the RCTWebSocket library.

What's really strange is that I don't see the same issue when running in a simulator. The code to run isn't identical because the simulator can't access the external IP, but I would have thought setting it to 127.0.0.1 would make the code paths nearly identical.

**Comment by ide** [comment]
This should be fixed in master. 0.17-RC will be going out in a few days.

**Comment by deviantintegral** [comment]
I just upgraded my test project to master, and the leak is still there. Is there any chance this wouldn't have been fixed by running react-native upgrade && npm i? What's the commit that should fix this? All I'm finding are commits that were already in 0.15.

**Comment by ide** [comment]
It was something to do with the WebSocket debugger even if you weren't using it.

**Comment by brentvatne** [comment]
Dup of #4730
