### ISSUE TITLE
onEndReached does not trigger even though onEndReachedThreshold is set

### ISSUE THREAD

**Issue by adminruparupa** [facebook/react-native#45438]
### Description

onEndReached does not trigger even though onEndReachedThreshold is set

### Steps to reproduce

<FlatList
        data={data}
        ListHeaderComponent={
          <View>
            {renderHeaderComponent()}
          </View>
        }
        ListEmptyComponent={renderEmpty}
        ListFooterComponent={renderFooter}
        refreshing={refresh}
        onRefresh={() => refreshItems()}
        numColumns={2}
        contentContainerStyle={{ paddingBottom: 30 }}
        initialNumToRender={16}
        onEndReachedThreshold={0.3}
        onEndReached={() => { handlePagination() }}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
      />

### React Native Version

0.72.15

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
..
```

### Stacktrace or Logs

```text
onEndReached is not triggered even though onEndReachedThreshold is set
```

### Reproducer

..

### Screenshots and Videos

<FlatList
        data={data}
        ListHeaderComponent={
          <View>
            {renderHeaderComponent()}
          </View>
        }
        ListEmptyComponent={renderEmpty}
        ListFooterComponent={renderFooter}
        refreshing={refresh}
        onRefresh={() => refreshItems()}
        numColumns={2}
        contentContainerStyle={{ paddingBottom: 30 }}
        initialNumToRender={16}
        onEndReachedThreshold={0.3}
        onEndReached={() => { handlePagination() }}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
      />

**Comment by cortinico** [comment]
Closing as duplicates of https://github.com/facebook/react-native/issues/36529#issuecomment-1695732823

**Comment by NikhilPacewisdom** [comment]
```
import React, { forwardRef, useCallback } from 'react';
import { FlatList, FlatListProps, ScrollView } from 'react-native';

interface Props<T> extends FlatListProps<T> {
  ListEmptyComponent?: React.ReactNode | (() => React.ReactNode);
}

const Flatlist = forwardRef(
  <T,>(props: Props<T>, ref: React.Ref<FlatList<T>>) => {
    const { ListEmptyComponent, ...rest } = props;

    const renderComponent = useCallback((component: any) => {
      return component
        ? typeof component === 'function'
          ? component()
          : component
        : null;
    }, []);

    if (rest.data && rest.data.length === 0) {
      return (
        <ScrollView {...rest}>
          {renderComponent(rest.ListHeaderComponent)}
          {renderComponent(ListEmptyComponent)}
          {renderComponent(rest.ListFooterComponent)}
        </ScrollView>
      );
    }

    return <FlatList {...rest} ref={ref} />;
  },
);

export default React.memo(Flatlist) as <T>(
  props: Props<T> & { ref?: React.Ref<FlatList<T>> },
) => React.ReactElement;
```

Try this
