### ISSUE TITLE
Dimensions.addEventListener not firing react native 0.74.3

### ISSUE THREAD

**Issue by sedatb** [facebook/react-native#45497]
### Description

I tried IOS tablet devices but Dimensions.addEventListener not firing in react native 0.74.3
Works fine on iPhones. On tablets, when I change orientation, it doesn't firing.

### Steps to reproduce

1. Play video
2. Change orientation on tablet
3. Not firing dimension eventListener

### React Native Version

0.74.3

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 851.80 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.0.0
    path: /var/folders/7k/zzwy60lx4m755sl1419v7x500000gn/T/yarn--1721225982346-0.35930533064896863/node
  Yarn:
    version: 1.22.22
    path: /var/folders/7k/zzwy60lx4m755sl1419v7x500000gn/T/yarn--1721225982346-0.35930533064896863/yarn
  npm:
    version: 10.5.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.04.29.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Not crash log
```

### Reproducer

https://github.com/facebook/react-native

**Comment by sedatb** [comment]
I use splashViewController to play gif in my splash screen. I tried to remove it in appDelegate then it worked. In appDelegate, when I use this code block, listener works perfectly, 
  
  bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions];
  return didFinish;
  
  but when I use ->  return YES;
  listener doesnt't works truely.

**Comment by cortinico** [comment]
> I use splashViewController to play gif in my splash screen. I tried to remove it in appDelegate then it worked. In appDelegate, when I use this code block, listener works perfectly,
> 
> bool didFinish = [super application:application didFinishLaunchingWithOptions:launchOptions]; return didFinish;
> 
> but when I use -> return YES; listener doesnt't works truely.

We need a GitHub repo that consistently reproduces your issue. You can use this template:
https://github.com/react-native-community/reproducer-react-native

**Comment by cortinico** [comment]
Closing as @sedatb is unresponsive and a valid reproducer was never provided
