### ISSUE TITLE
Babel plugins registration goes wrong with `npm link`

### ISSUE THREAD

**Issue by thenewvu** [facebook/react-native#4553]
Hello RN team,

I'm working on a custom project generator, which's taking advantage from `npm link` to sync changes easily with a local RN repo.

The project structure looks like this:

```console
├── android
├── hybrid
│   └── index.android.js
├── node_modules
│   └── react-native -> /home/vu/.npm/lib/node_modules/react-native
└── package.json
```

As you see, the `react-native` is linking to the global module, which's linking again to the local RN:

```console
$ ln -s /home/vu/.npm/lib/node_modules/react-native

/home/vu/.npm/lib/node_modules/react-native -> /data/projects/react-native-td/
```

The problem is I can not run the local CLI from the project directory:

```console
$ ./node_modules/react-native/packager/packager.sh

/data/projects/react-native-td/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i));
          ^

ReferenceError: Unknown plugin "syntax-async-functions" specified in "foreign" at 0
    at /data/projects/react-native-td/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:17
    at Array.map (native)
    at Function.normalisePlugins (/data/projects/react-native-td/node_modules/babel-core/lib/transformation/file/options/option-manager.js:163:20)
    at OptionManager.mergeOptions (/data/projects/react-native-td/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:36)
    at compile (/data/projects/react-native-td/node_modules/babel-register/lib/node.js:87:15)
    at loader (/data/projects/react-native-td/node_modules/babel-register/lib/node.js:128:14)
    at Object.require.extensions.(anonymous function) [as .js] (/data/projects/react-native-td/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

My first solution is to put this to the project's `package.json`:

```json
  "scripts": {
    "start": "projectRootPath=$(pwd); cd <%= ReactNativePath %> ; node ./local-cli/cli.js start --root $projectRootPath"
  },
```

But it's so painful if I also need to add `bundle` or other commands.

After few hours, my next solution is to make this change in the local RN:

```diff
diff --git a/cli.js b/cli.js
old mode 100644
new mode 100755
index 13b3ce7..3385127
--- a/cli.js
+++ b/cli.js
@@ -1,3 +1,5 @@
+#!/usr/bin/env node
+
 /**
  * Copyright (c) 2015-present, Facebook, Inc.
  * All rights reserved.
@@ -8,8 +10,16 @@
  */
 'use strict';
 
+process.chdir(__dirname);
+
 require('./packager/babelRegisterOnly')([
   /private-cli\/src/
 ]);
 
-module.exports = require('./local-cli/cli.js');
+var localCli = require('./local-cli/cli.js');
+
+if (require.main === module) {
+  localCli.run();
+}
+
+module.exports = localCli;
\ No newline at end of file
diff --git a/package.json b/package.json
index 2231a1d..ff0dc4f 100644
--- a/package.json
+++ b/package.json
@@ -50,7 +50,7 @@
     "start": "/usr/bin/env bash -c './packager/packager.sh \"$@\" || true' --"
   },
   "bin": {
-    "react-native": "local-cli/wrong-react-native.js"
+    "react-native": "cli.js"
```

So now I only need to add this to the project's `package.json`:

```json
  "scripts": {
    "start": "react-native start --root $(pwd)"
  },
```

But one thing makes me so confuse is why this:

```json
  "bin": {
    "react-native": "local-cli/wrong-react-native.js"
  },
```

Is the team having some future plan ? My simple solution can make any break to other parts of RN ?

Thank you,

**Comment by thenewvu** [comment]
Moreover, this solution affects to building android project in release mode. The packager can't find out the entry file, because it can't find the right app project root directory.

About Babel plugins registration, some commits that I think they relate to the problem, you can see latest commits of this [file](https://github.com/babel/babel/commits/master/packages/babel-core/src/transformation/file/options). Doesn't it make any sense ?

**Comment by satya164** [comment]
@thenewvu RN packager doesn't support symlinks. You might wanna place the project inside the `node_modules` folder.

**Comment by thenewvu** [comment]
@satya164 Thank you. It's an life-hacked feature if exists. I'm going to pay next few days to dig into the internal of packager and hot-loading server, hope get some help from here.

**Comment by satya164** [comment]
@thenewvu The reason packager doesn't support symlink is because `watchman` doesn't support them, and supporting symlinks is very hard.

RN issue - #637
Watchman issue - #105
