### ISSUE TITLE
Unhandled JS Exception: Invalid regular expression:

### ISSUE THREAD

**Issue by aparnagude396** [facebook/react-native#45536]
### Description

Hi I'm using react native version 0.73.6 and node version 18.1.0. I'm trying to build application in iOS. but in react native start it is giving error. unhandled js exception. Can anyone please help me on this. I have tried with latest node version too. But no luck.

### Steps to reproduce

1. Build the app in Xcode
2. rpm start in terminal
3. got the error in simulator like "unhandled JS Exception: Invalid regular expression: invalid group specifier name"

### React Native Version

0.73.6

### Affected Platforms

Runtime - iOS, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.2.1
  CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Memory: 991.41 MB / 12.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.1.0
    path: ~/.nvm/versions/node/v18.1.0/bin/node
  Yarn:
    version: 1.22.10
    path: /usr/local/bin/yarn
  npm:
    version: 8.8.0
    path: ~/.nvm/versions/node/v18.1.0/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /usr/bin/javac
  Ruby:
    version: 3.0.2
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
2024-07-19 15:35:36.578861+0530 TechmoShop[74486:375882] [native] Unhandled JS Exception: Invalid regular expression: invalid group specifier name

no stack
```

### Reproducer

https://github.com/facebook/react-native/issues/27445

### Screenshots and Videos

![Screenshot 2024-07-19 at 3 46 23 PM](https://github.com/user-attachments/assets/96833df4-49c1-4542-9a18-b43f11d6506d)

**Comment by cortinico** [comment]
> Can anyone please help me on this. I have tried with latest node version too. But no luck.

Due to extreme number of issues we receive, we accept only bug report on this issue tracker and we can't offer user support. Sorry for that
