### ISSUE TITLE
TextInput hidden by keyboard

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#4556]
I put a TextInput at bottom of the View.
When the virtual keyboard shows up, the TextInput is hidden by the keyboard on ios, but not on android.
It is  automatically raise up on android. 
Why does the inconsistency happen?

**Comment by alvaromb** [comment]
Hi @narychen!

Take a look at this issue https://github.com/facebook/react-native/issues/3195

**Comment by mkonicek** [comment]
This is a different behavior between the platforms. #3195 contains some relevant discussion.

**Comment by mitesh1301** [comment]
Hi All,
i just resolve this issue with alternative solution, by using the animation, Hope this will help

---------------------------------------------------------------------------------------
import { Animated, Keyboard} from 'react-native';

constructor(props) {
        super(props);

        //For the keyboard
        this.keyboardHeight = new Animated.Value(0);
}

 //For key board
    componentWillMount () {
        console.log("Keyboard componentWillMount")
        this.keyboardWillShowSub = Keyboard.addListener('keyboardWillShow', this.keyboardWillShow);
        this.keyboardWillHideSub = Keyboard.addListener('keyboardWillHide', this.keyboardWillHide);
      }
    
      componentWillUnmount() {
          console.log("Keyboard componentWillUnmount")
        this.keyboardWillShowSub.remove();
        this.keyboardWillHideSub.remove();
      }
    
      keyboardWillShow = (event) => {
        console.log("keyboardWillShow")
        Animated.parallel([
            Animated.timing(this.keyboardHeight, {
              duration: event.duration,
              toValue: event.endCoordinates.height,
            })
          ]).start();
      };
      
      keyboardWillHide = (event) => {
        console.log("keyboardWillHide")
        Animated.parallel([
            Animated.timing(this.keyboardHeight, {
              duration: event.duration,
              toValue: 0,
            })
          ]).start();
      };

 render() {
                <Animated.View style={[styles.container, { paddingBottom: this.keyboardHeight }]}>
                   <Myview>
                       <TextInput ........>
                      </Textinput>
                  </Myview>
                </Animated.View>
}
