### ISSUE TITLE
Getting started with 0.15.0 fails in IOS

### ISSUE THREAD

**Issue by lvonk** [facebook/react-native#4557]
I am unable to start a newly generated IOS app following the getting started guide https://facebook.github.io/react-native/docs/getting-started.html#content

Starting the IOS app results in the following error in XCODE:

```
Dec  4 09:53:38  NavigatorExample[42204] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Dec  4 09:53:38  NavigatorExample[42204] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

I do have a running 0.14.1 app. I want to start another project and ran `react-native init NavigatorExample`.

The package.json of the new project:

```
{
  "name": "NavigatorExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.15.0"
  }
}
```

Any ideas?

**Comment by mihirsoni** [comment]
Hi @lvonk ,

Could you please confirm which Xcode version you are using.

I tried with Version 7.1 (7B91b) and new project initiated with ``react-native init NavigatorExample`` and I am able to compile and Run Successfully.

**Comment by lvonk** [comment]
I have version Version 7.1.1 (7B1005)

**Comment by christopherdro** [comment]
@lvonk Any luck getting this working?
