### ISSUE TITLE
IOS Application crash in networking code RCTNetworking.m#L177

### ISSUE THREAD

**Issue by FarazShaikh** [facebook/react-native#4558]
I modified the movies example to point to my rest server. Every time I scroll beyond the viewable page size for my listview (fetches next page from a golang rest server) the react native app crashes deep inside 

RCTNetworking.m
-------------------------
https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTNetworking.m#L177

Error shown in chrome console
------------------------------------------
The RCTURLRequestHandlers RCTFileRequestHandler: 0x7b2392d0 and RCTDataRequestHandler: 0x7b233910 both reported that they can handle the request NSMutableURLRequest: 0x7da29ed0 { URL: (null) }, and have equal priority (0). This could result in non-deterministic behavior.

XCODE Error
------------------------
2015-12-04 00:46:44.795 [trace][tid:com.facebook.React.JavaScript][RCTContextExecutor.m:129] 'Running application "hazen" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF'
2015-12-04 00:47:19.861 [warn][tid:com.facebook.React.RCTNetworkingQueue][RCTNetworking.m:175] The RCTURLRequestHandlers <RCTFileRequestHandler: 0x7b2392d0> and <RCTDataRequestHandler: 0x7b233910> both reported that they can handle the request <NSMutableURLRequest: 0x7da29ed0> { URL: (null) }, and have equal priority (0). This could result in non-deterministic behavior.
2015-12-04 00:47:19.930 hazen[58790:928100] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfURL:options:error:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x0153ca84 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x00788e02 objc_exception_throw + 50
	2   CoreFoundation                      0x0153c9ad +[NSException raise:format:] + 141
	3   Foundation                          0x0035a25d -[NSData(NSData) initWithContentsOfURL:options:error:] + 100
	4   Foundation                          0x0035a1df +[NSData(NSData) dataWithContentsOfURL:options:error:] + 83
	5   hazen                               0x0018f098 __50-[RCTDataRequestHandler sendRequest:withDelegate:]_block_invoke + 760
	6   Foundation                          0x00435a6b __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	7   Foundation                          0x003598ff -[NSBlockOperation main] + 108
	8   Foundation                          0x00339d84 -[__NSOperationInternal _start:] + 697
	9   Foundation                          0x00339ac4 -[NSOperation start] + 83
	10  Foundation                          0x00339902 __NSOQSchedule_f + 245
	11  libdispatch.dylib                   0x04a119cd _dispatch_client_callout + 14
	12  libdispatch.dylib                   0x049f5650 _dispatch_queue_drain + 2227
	13  libdispatch.dylib                   0x049f4b04 _dispatch_queue_invoke + 570
	14  libdispatch.dylib                   0x049f77bb _dispatch_root_queue_drain + 550
	15  libdispatch.dylib                   0x049f758e _dispatch_worker_thread3 + 115
	16  libsystem_pthread.dylib             0x04d31270 _pthread_wqthread + 1050
	17  libsystem_pthread.dylib             0x04d2ef82 start_wqthread + 34
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

This is 100% reproducible, I can share the client side code .. (but server still runs on my local box so client won't run out of the box on react playground)

NOTES
-----------
This looks like some debug assert code under RCT_DEBUG, i removed it and tried going past the issue but the application still crashed. (so must be something serious)

Please let me know if anything else is needed in to debug this.

**Comment by nicklockwood** [comment]
Looks like a nil url being passed in. We shpuld probably guard against that.

**Comment by FarazShaikh** [comment]
Indeed it was URL being NULL issue. Fixed for me. Leaving the bug opened for guarding against it. Feel free to close it this is a minor issue.

**Comment by BillyBarbaro** [comment]
Hi there.  I've been using react native for a month or 2, and having been looking to contribute back to the community.  Above is my attempt at a fix if I'm understanding the problem correctly; however, I'm not really sure how to test this code manually or write some automated tests around the issue.  If someone could point me in the right direction, I'm willing to keep looking into this in hopes of submitting a small PR.   Thanks!

**Comment by FarazShaikh** [comment]
It's reproducible by pass a null URL object to the fetch api.

Faraz

**Comment by BillyBarbaro** [comment]
Got it.  So now I'm making a call something like:

    fetch(null)
        .then((response) => response.json())
        .then((responseData) => {
            console.log(responseData);
        })
        .done();

and that's throwing the error for me.  I just wanted to verify that I'm producing the error you were discussing here.

So if a null url is passed in, what kind of behavior do we want here?  Do we want fetch to return null?  It seems to me like passing in a null URL is an error, so I would lean toward outputting a more descriptive warning message.  Do you have any thoughts or opinions here?
