### ISSUE TITLE
[Animation] Examples?

### ISSUE THREAD

**Issue by nextriot** [facebook/react-native#456]
Hi guys:

Awesome work on this. Absolutely in lust right now.

I've been trying to wrap my head around doing animations, from what I've gathered POP is leveraged for all animation work, which I'm not familiar with, perhaps that's my shortcoming.

I'm trying some basic animations from other examples I've scouted throughout the repo and using this file for potential properties to animate: [PopAnimation.js] (https://github.com/facebook/react-native/blob/0c83766e3b7d17674954bacf9ccc308d4dd4b2b3/Libraries/BatchedBridge/BatchedBridgedModules/POPAnimation.js)

```jsx
getInitialState: function() {
  return {
    isAnimating: true
  }
},

toggleScale: function() {
  this.setState({
    isAnimating: !this.state.isAnimating
  });

  Animation.startAnimation(this.refs['this'], 300, 0, 'easeInOutQuad', {
    scaleXY: this.state.isAnimating ? [2.0, 2.0] : [0.5, 0.5],
  });
},

render: function() {
  return (

        <TouchableHighlight style={styles.container} underlayColor='#99d9f4' onPress={() => this.toggleScale()}>
          <View>
            <Text style={styles.text}>
              Click here to start animation!
            </Text>
            <View ref='this' style={styles.box}/>
          </View>
        </TouchableHighlight>
  );
}
```

With a property such as `opacity` this seems to work fine: click once - hidden, click again - shown. However, `scaleXY` doesn't commit its animation, i.e. after the animation happens it then jumps back to it's original state, which sort of makes sense as Cocoa Touch has the same implementation and forces you to set the final state in a block / closure after the animation. But given opacity's behaviour I'm not sure why this acts differently.

Also I've no clue how to animate positions, or even which value to animate positions with: `positionX` or `translationX`?

Are there any examples which show a simple, 'from -> to' animation. e.g. `on press move this box from posA to posB and commit the animation`?

Amazing stuff again. Very much looking forward to Nuclide to make this all a little easier.

**Comment by chadobado** [comment]
Hey @nextriot, source looks familiar so assuming you saw: https://github.com/facebook/react-native/issues/432

Am still sorting through this myself, but It seems you may be mixing up the syntax for the declarative API and LayoutAnimation.  Your setState in toggleScale is firing render().  If you want to animate on a state change you will likely want to take advantage of LayoutAnimation to config the animation prior to changing your state, or remove the state change from toggleScale if you want to animate declaratively.

The example I linked above demonstrates the declarative Animation API, here's similar w/ LayoutAnimation:

```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  LayoutAnimation,
  Text,
  TouchableHighlight,
  View,
} = React;

var WebViewApp = React.createClass({

  getInitialState: function() {
    return {box:true}
  },

  _onPress: function() {
    console.log('starting animation');
    // Animation.startAnimation(this.refs['this'], 800, 0, 'easeInOutQuad', {scaleXY: [5, 5]});
    LayoutAnimation.configureNext(animations.layout.easeInEaseOut);
    this.setState({box:!this.state.box})
  },

  render: function() {
    var box =  this.state.box === true ? 
    <View ref='this' style={styles.box}/> :
    <View ref='this' style={styles.box2}/>

    return (
      
          <TouchableHighlight style={styles.container} onPress={this._onPress}>
            <View>
              <Text style={styles.text}>
                Click here to start animation!
              </Text>
             {box}
            </View>
          </TouchableHighlight>
      
    );
  }
});

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    top:200,
    width: 200,
    height: 200,
  },
  text: {
    fontSize: 16,
  },
  box:{
    backgroundColor:'red', 
    width: 50, 
    height: 50,
  },
  box2:{
    backgroundColor:'red', 
    width: 550, 
    height: 550,
  }
});


var animations = {
  layout: {
    spring: {
      duration: 0.75,
      create: {
        duration: 0.3,
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.opacity,
      },
      update: {
        type: LayoutAnimation.Types.spring,
        springDamping: 0.4,
      },
    },
    easeInEaseOut: {
      duration: 0.3,
      create: {
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.scaleXY,
      },
      update: {
        delay: 0.1,
        type: LayoutAnimation.Types.easeInEaseOut,
      },
    },
  },
};

AppRegistry.registerComponent('WebViewApp', () => WebViewApp);

```

**Comment by drkibitz** [comment]
@chadobado do you have a similar example by chance, for animating on `componentDidMount`? I've tried and it seems that starting the animation here is too soon, before the current layout is actually set. Is this known behavior?

**Comment by chadobado** [comment]
@drkibitz seems to work for me with both LayoutAnimation and Animation APIs.  

I noticed in the 2048 example animations in componentDidMount are being wrapped with a timeout:

https://github.com/facebook/react-native/blob/master/Examples/2048/Game2048.js#L86

Perhaps due to the second paragraph of this:

https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount

But in my tests, the timeout was not needed:

LayoutAnimation:
```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  LayoutAnimation,
  Text,
  TouchableHighlight,
  View,
} = React;

var WebViewApp = React.createClass({

  getInitialState: function() {
    return {boxOpen:false}
  },
  componentDidMount: function() {
    LayoutAnimation.configureNext(animations.layout.easeInEaseOut);
    this.setState({boxOpen:!this.state.boxOpen})
  },
  _onPress: function() {
    console.log('starting animation');
    // Animation.startAnimation(this.refs['this'], 800, 0, 'easeInOutQuad', {scaleXY: [5, 5]});
    LayoutAnimation.configureNext(animations.layout.easeInEaseOut);
    this.setState({boxOpen:!this.state.boxOpen})
  },

  render: function() {
    var box =  this.state.boxOpen === true ? 
    <View ref='this' style={styles.boxOpen}/> :
    <View ref='this' style={styles.boxClosed}/>

    return (
      
          <TouchableHighlight style={styles.container} onPress={this._onPress}>
            <View>
              <Text style={styles.text}>
                Click here to start animation!
              </Text>
             {box}
            </View>              
          </TouchableHighlight>
      
    );
  }
});

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    top:200,
    width: 200,
    height: 200,
  },
  text: {
    fontSize: 16,
  },
  boxClosed:{
    backgroundColor:'red', 

    width: 50, 
    height: 50,
    margin: 5,
  },
  boxOpen:{
    backgroundColor:'red', 
    width: 550, 
    height: 550,
  }
});


var animations = {
  layout: {
    spring: {
      duration: 0.75,
      create: {
        duration: 0.3,
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.opacity,
      },
      update: {
        type: LayoutAnimation.Types.spring,
        springDamping: 0.4,
      },
    },
    easeInEaseOut: {
      duration: 0.3,
      create: {
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.scaleXY,
      },
      update: {
        delay: 0.1,
        type: LayoutAnimation.Types.easeInEaseOut,
      },
    },
  },
};

AppRegistry.registerComponent('WebViewApp', () => WebViewApp);
```

Animation:
```javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Animation,
  Text,
  TouchableHighlight,
  View,
} = React;

var WebViewApp = React.createClass({
  componentDidMount: function() {
    // setTimeout(() => {
      Animation.startAnimation(this.refs['this'], 300, 0, 'easeInOutQuad', {scaleXY: [5, 5]});
      Animation.startAnimation(this.refs['this'], 100, 0, 'easeInOutQuad', {opacity: 1});
    // }, 0);
  },
  getInitialState: function() {
    return {}
  },

  _onPress: function() {
    console.log('starting animation');
    Animation.startAnimation(this.refs['this'], 300, 0, 'easeInOutQuad', {scaleXY: [2.5, 2.5]});
  },

  render: function() {
    return (

          <TouchableHighlight style={styles.container} onPress={this._onPress}>
            <View>
              <Text style={styles.text}>
                Click here to start animation!
              </Text>
              <View ref='this' style={styles.box}/>
            </View>
          </TouchableHighlight>

    );
  }
});

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    top:200,
    width: 200,
    height: 200,
  },
  text: {
    fontSize: 16,
  },
  box:{
    backgroundColor:'red', 
    width: 50, 
    height: 50,
  }
});



AppRegistry.registerComponent('WebViewApp', () => WebViewApp);
```

**Comment by drkibitz** [comment]
@chadobado in your `Animation` example is the scaleXY actually scaling from a 200x200 layer, or something smaller? What I saw was that it appears to work, but was always scaling from no layout rather than the dimensions specified in the styles, that is until a timeout was used.

**Comment by drkibitz** [comment]
@chadobado and thank you!

**Comment by chadobado** [comment]
@drkibitz the scaleXY is scaling from height/width defined in styles.box in the Animation example.  The LayoutAnimation example is not scaling, it's tweening the size between the height/width of boxClosed (50px/50px) and boxOpen (550px/550px).

Also @nextriot positioning for LayoutAnimation can be defined with standard css styles as you might expect (possibly other ways?):
```javascript
  boxClosed:{
    backgroundColor:'red', 
    width: 50, 
    height: 50,
    margin: 5,
    opacity: 1,
  },
  boxOpen:{
    backgroundColor:'red', 
    width: 550, 
    height: 550,
    position: 'absolute',
    top: 100,
    left: 100,
  }
```

and with "position" using Animation (bound by parent):

```javascript
Animation.startAnimation(this.refs['this'], 300, 0, 'easeInOutQuad', {position:[100,0]});
```

I'm not able to get rotations to work with either API currently.

**Comment by syousif94** [comment]
@chadobado rotation doesn't seem to work in stylesheets either

**Comment by qingfeng** [comment]
@chadobado how to use `POPAnimation`? thanks

**Comment by brentvatne** [comment]
@qingfeng - https://github.com/facebook/react-native/issues/1365#issuecomment-104792251

@syousif94 - rotation works as expected now [see docs](https://facebook.github.io/react-native/docs/transforms.html#content) eg: `transform: [{rotate: '30deg'}]`

**Comment by brentvatne** [comment]
Looks like there are plenty of examples above now, more exciting stuff re: animations coming soon!

**Comment by alinz** [comment]
@brentvatne @chadobado Do you guys know why animation doesn't work for transition from opacity 1 to opacity 0. The interesting thing here is it works perfectly fine when you want to transit from opacity 0 to opacity 1. I just want to do fade in and fade out.

**Comment by iSimar** [comment]
@alinz I would also like to do fade in and fade out, did you figure out a way to do it?

**Comment by alinz** [comment]
@iSimar Since LayoutAnimation won't fix this issue in near future, your best bet is to implement fade in and out by using opacity. For my project I ended up creating one from scratch and I have opened source it here. [react-native-scene-manager](https://github.com/alinz/react-native-scene-manager). There is no doc yet but you can take a look at the example folder. 

Let me know if you need any help.
