### ISSUE TITLE
Cannot access CameraRoll - undefined is not an object(evaluating RCTCameraRollManager.getPhotos)

### ISSUE THREAD

**Issue by vinu123** [facebook/react-native#4560]
I cannot use 'CameraRoll' anymore. So as per some suggestions on StackOverFlow I downloaded RCTCameraRoll.xcodeproj and added it under libraries. Then, I located libRCTCameraRoll.a under 'Products' and linked that under 'Build Phases'. And still nothing.

Am I doing something wrong? Just using CameraRoll component before used to do the trick but not anymore.

![linked](https://cloud.githubusercontent.com/assets/240336/11586636/8242def4-9a9a-11e5-94cc-efa69e0af0a8.png)

**Comment by asamiller** [comment]
Make sure you add libRCTCameraRoll.a to the Linked Frameworks and Libraries section of your main Xcode project not the RCTCameraRoll.xcodeproj subproject. Also, you can add the RCTCameraRoll.xcodeproj project from `node_modules/react-native/LibrariesCameraRoll` rather than downloading it from the repo. That way its matched to your React Native version.

**Comment by vinu123** [comment]
Thanks so much man. That was pretty neat @asamiller

**Comment by skevy** [comment]
@vinu123 if your issue is fixed, please consider closing this to help us keep the issue tracker clean! :)

**Comment by gorjanz** [comment]
Just tried to use CameraRoll as indicated here, with React Native v0.20:

http://facebook.github.io/react-native/releases/0.20/docs/cameraroll.html#content

and had problems on iOS, android is working as expected. The problem on iOS is that, although, in ```Build Settings / Header Search Paths``` there is an entry in the form of: ```$(SRCROOT)/../node_modules/react-native/React``` which is marked recursive, the ```RCTCameraRoll.xcodeproj``` is not linked with your app, which consequently leads to ```libRCTCameraRoll.a``` not being in the ```Linked Frameworks and Libraries``` section. After connecting this manually, everything behaves as expected.
Would the proper solution here be that we add an entry to ```Build Settings / Header Search Paths```, to the ```Libraries``` folder, same as it is to the React folder, or do we do this manually for each native functionality that we use in our project?

Also, it would be nice if this can be added somewhere in the documentation.

**Comment by verystrongjoe** [comment]
where can I get libRCTCameraRoll.a? I can't find it!!

**Comment by gorjanz** [comment]
You should be able to find it in the Libraries folder of React Native, once you install it via npm, so something like {projectDir}/node_modules/react-native/Libraries/... {check out Camera Roll, and Image directories}. Don't forget to link the corresponding projects also.

**Comment by adamkdean** [comment]
I don't see any `.a` files.

![image](https://cloud.githubusercontent.com/assets/1639527/17990005/c2f801e4-6b29-11e6-8c14-7fff7ce71c74.png)

**Comment by a3diti** [comment]
I have the same problem, any solution in this page does not work

Error screen:
<img src="https://user-images.githubusercontent.com/3646190/36078686-50375ed8-0f7a-11e8-96ab-2a186a2fa5ba.jpg" width="300">

What i found at `node_modules/react-native/Libraries/CameraRoll/CameraRoll.js:291`
<img width="550" alt="screen shot 2018-02-11 at 22 30 58" src="https://user-images.githubusercontent.com/3646190/36078807-c3271bb2-0f7b-11e8-8a55-4a306b7e82c5.png">

What i have done so far:

1. Added Header Search Paths
`$(SRCROOT)/../node_modules/react-native/Libraries/CameraRoll`

2. Linking is properly done, confirmed it:
<img width="1125" alt="screen shot 2018-02-11 at 22 17 20" src="https://user-images.githubusercontent.com/3646190/36078659-e9e5d542-0f79-11e8-9512-5bcb64380e41.png">

3. At my component, both `console.log(CameraRoll)` and `console.log(CameraRoll.getPhotos)` have their proper object, which means no errors there.

4. Already added `<key>NSPhotoLibraryUsageDescription</key>` and its `<string>` description at `Info.plist`

5. Deleted and re-installed the app

6. run `yarn start --reset-cache`

7. Tried on both simulator and device

The error still persist! 🤔
Using React Native v0.51.0

**Comment by HoangTran160196** [comment]
@a3diti i think you need to run react-native run-ios again.

**Comment by prayuditb** [comment]
I have had the same issue and I'm using `react-native-camera` with `RNCamera.xcodeproj`.
Based on information from @a3diti, I just add `RCTCameraRoll.xcodeproj` again from `node_modules/react-native/Libraries/CameraRoll` and `libRCTCameraRoll.a` to my `Link binary with libraries`

Thanks
