### ISSUE TITLE
Master build problem in android. "Cannot read property 'Constants' of undefined"

### ISSUE THREAD

**Issue by msathis** [facebook/react-native#4562]
I followed https://github.com/facebook/react-native/blob/master/docs/AndroidBuildingFromSource.md for building from source.  But while running the app, im getting 
```Cannot read property 'Constants' of undefined``` from MapView.js:18

The line number 18 in MapView.js looks like
 ```var RCTMapConstants = require('NativeModules').UIManager.RCTMap.Constants;```

Am i doing something wrong or it's a real bug?

**Comment by mkonicek** [comment]
This is just a warning, right? It's because we haven't open sourced MapView on Android yet. You can ignore the warning for now.

**Comment by msathis** [comment]
@mkonicek It's not a warning. It's a redbox. Attaching a screenshot.

![screen](https://cloud.githubusercontent.com/assets/2977899/11592497/d7c83b1a-9ac4-11e5-961b-68a21fcb8db0.png)

I had to fix it by changing that line to 
```javascript 
     var RCTMap = require('NativeModules').UIManager.RCTMap;
     var RCTMapConstants = RCTMap ? RCTMap.Constants : undefined;
```

**Comment by liyayun** [comment]
Same issue when I  tried to integrates react-native with an existing android app. I followed <a href="http://facebook.github.io/react-native/docs/embedded-app-android.html#content">Official guide</a>.When everything was done. I started the development server then run my android app.I got the error.

In chrome console:

![69691811-9450-471d-9da3-8a0ef88bd33d](https://cloud.githubusercontent.com/assets/9899298/11803545/ea609ed2-a336-11e5-8694-2aff339b6e62.png)
