### ISSUE TITLE
Text Layout without float and CSS Exclusions

### ISSUE THREAD

**Issue by olofd** [facebook/react-native#4563]
I'm trying to layout text with react-native and see some constraints in the layout engine for text-layout.
I was wondering if there are any plans in supporting text that flows around images?

In the browser this would be done with float or CSS Exclusions/Regions (In the near future).
Have there been any discussions in supporting such a use case?

And of course, if this somehow already is possible in some way that I have missed, please let me know.

Included a screenshot with a typical broswer-of-today image-floating.
![place](https://cloud.githubusercontent.com/assets/933408/11588159/b64738a6-9a7e-11e5-9a17-7d42d2703f25.jpg)

**Comment by ide** [comment]
The repo to discuss this on is facebook/css-layout. It might be a long time before this is implemented though so if you need it you should write a custom native component.

**Comment by brentvatne** [comment]
I think this is a great feature request to add to [Product Pains](https://productpains.com/product/react-native/) - can you repost it there @olofd? Thanks!

**Comment by olofd** [comment]
Will do! @brentvatne

**Comment by Noitidart** [comment]
@olofd did you post it there? I would love to up vote it. It is something I need. I was redirected here from - https://stackoverflow.com/questions/39514335/how-to-float-text-around-image-in-react-native
