### ISSUE TITLE
Error: Watcher took too long to load (react-native 0.16.0-rc [on Windows])

### ISSUE THREAD

**Issue by manojHM** [facebook/react-native#4564]
'react-native start' stopped working after i upgraded react-native from 0.14.2 to 0.16.0-rc.
i googled but I dint find any particular solution  for windows.

 error:

        
           ERROR  Watcher took too long to load
           Try running `watchman version` from your terminal
           https://facebook.github.io/watchman/docs/troubleshooting.html
           Error: Watcher took too long to load
           Try running `watchman version` from your terminal
            https://facebook.github.io/watchman/docs/troubleshooting.html
           at [object Object]._onTimeout (index.js:102:16)
           at Timer.listOnTimeout (timers.js:92:15)

**Comment by satya164** [comment]
Duplicate of #2841
