### ISSUE TITLE
automaticallyAdjustKeyboardInsets doesn't work in the new arch

### ISSUE THREAD

**Issue by ceopaludetto** [facebook/react-native#45647]
### Description

When using `automaticallyAdjustKeyboardInsets={true}` and the software keyboard is open in the new architecture nothing happens, it should move the content above the keyboard

### Steps to reproduce

1. Clone the repository and `cd` into `ReproducerApp`
1. Install dependencies with `yarn install`
1. `cd` into `ios/` folder and install pods with fabric enabled `RCT_NEW_ARCH_ENABLED=1 pod install` (actually you can install with or without fabric enabled to compare behaviors) 
1. `cd ..` and run `yarn ios` 
1. if `yarn ios` doesn't work, try to run with xcode instead

### React Native Version

0.74.3

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 205.66 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: ~/.local/share/mise/installs/node/latest/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.local/share/mise/installs/node/latest/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.3
    path: /Users/carlos/.local/share/mise/installs/java/corretto-21.0.3.9.1/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
.
```

### Reproducer

https://github.com/ceopaludetto/keyboard-inset-new-arch-repro

### Screenshots and Videos

| Old arch | New arch |
| --------  | --------- |
| [video](https://github.com/user-attachments/assets/8157df1a-7a57-4396-9473-f1aaa4d60030) | [video](https://github.com/user-attachments/assets/8c9df5bd-2f77-4dc7-8b9e-e3f052d5153e) |

**Comment by shubhamguptadream11** [comment]
Looking into this issue.

**Comment by cortinico** [comment]
@shubhamguptadream11 I'm assigning this to you. Let us know if you get stuck, thanks for the support!

**Comment by cortinico** [comment]
Looks like we got a PR with the fix from @okwasniewski

**Comment by okwasniewski** [comment]
Hey @cortinico, the PR has been merged: https://github.com/facebook/react-native/pull/45939
