### ISSUE TITLE
Letter spacing CSS property

### ISSUE THREAD

**Issue by lachlanjc** [facebook/react-native#457]
There doesn’t seem to be a StyleSheet property for the `letter-spacing` CSS property. Is it just called something else or does it not exist yet? If not, it’d be a fantastic addition.

**Comment by sahrens** [comment]
Not supported, sorry. Would love a PR ;)

**Comment by lachlanjc** [comment]
@sahrens Do you mean iOS doesn’t support it, or just that React Native doesn’t yet support it?

**Comment by sahrens** [comment]
I believe iOS supports letter spacing via NSKernAttributeName on NSAttributedString, which should be pretty easy to map into <Text> in react native, but hasn't been done yet ;)

**Comment by lachlanjc** [comment]
Got it @sahrens. I will definitely check out adding it soon!

**Comment by frantic** [comment]
See #482
