### ISSUE TITLE
Jest fails on use of require('warning')  v0.16

### ISSUE THREAD

**Issue by adriansprod** [facebook/react-native#4572]
Jest tests which include React fail anywhere require('warning') is used by RN, which is in 57 places. I am using v0.16.0 and latest node. The first error is as follows.

Unexpected token ...
        at Object.exports.runInContext (vm.js:43:16)
        at Object.<anonymous> (node_modules/react-native/node_modules/react-haste/renderers/dom/shared/DOMPropertyOperations.js:19

 If I remove the use of 'warning' in that file then the error is triggered on the next file which uses it

**Comment by satya164** [comment]
@adriansprod Can you test if this still happens with master?

**Comment by brentvatne** [comment]
cc @cpojer

**Comment by cpojer** [comment]
I don't think this is still going to be an issue with jest 0.9.0.
