### ISSUE TITLE
'View' has no propType for native prop 'RCTView.elevation' of native 'number'

### ISSUE THREAD

**Issue by robtg4** [facebook/react-native#4573]
Creating iOS + Android App via React Native. iOS app comes up fine but Android simulator comes up with following error: 

![screen shot 2015-12-04 at 7 41 55 pm](https://cloud.githubusercontent.com/assets/13613075/11604836/cc47d250-9abf-11e5-8e69-a6e772430b48.png)

Here's my main.js code

//register on both android and ios index.js files
var React = require('react-native');
var Signin = require('./components/authentication/signin');
var Signup = require('./components/authentication/signup');
var Parse = require('parse/react-native');
var Tweets = require('./components/tweets/tweets');

var {
	View, 
	StyleSheet, 
	Text, 
	Navigator,
} = React;

var ROUTES ={
	//relates to imported component to display
	//initial route is am object with the name of the route within this variable
	signin: Signin,
	signup: Signup,
	tweets: Tweets,
}

module.exports = React.createClass({
	componentWillMount: function() {
		//executed when component shows on screen
		//tells app to initialize parse 
		Parse.initialize("Fd24vY1AhfOWzMT4XB1KXH0cXGgV1Ufr4weNWqEs", "EwxWhKGYuQ1Ou9BP6yMQML0Q4vjKi3E1WfnkcYEo");
	}, 
	renderScene: function(route, navigator) {
		//when navigator is initially shown it has to render initial route 
		//render a component and return it, whatever we return is placed on stack
		//add navigator property into this component for all app access
		var Component = ROUTES[route.name]; //ROUTE['signin'] => Signin
		return <Component route={route} navigator={navigator} />;
	}, 
	render: function() {
		return (
			<Navigator 
				style={styles.container}
				initialRoute={{name: 'signin'}}
				renderScene={this.renderScene}
				configureScene={ () => { return Navigator.SceneConfigs.FloatFromRight; }} />
		);
	}
});

var styles = StyleSheet.create({
	container: {
		flex: 1,
	}
});

**Comment by henriknorberg** [comment]
I got the same issue today.

**Comment by robtg4** [comment]
@henriknorberg  did you ever figure it out?

**Comment by henriknorberg** [comment]
I just did. Updating react native to the latest fixed it.

**Comment by cspkop** [comment]
I am facing same issue now..

**Comment by satya164** [comment]
It works fine with `0.16.0`.

@robtg4 @cspkop For instructions on how to upgrade, refer - http://facebook.github.io/react-native/docs/upgrading.html#content

**Comment by cspkop** [comment]
@satya164 @henriknorberg Thanks! this solved the issue.

**Comment by robtg4** [comment]
Thanks! Will update now!

**Comment by Newt0n** [comment]
@satya164 also solved my issue, thanks!
