### ISSUE TITLE
cd react-native && npm install   , then fsevents@1.0.5 not compatibale with my OS .Anybody know how to fix this pro

### ISSUE THREAD

**Issue by gamedilong** [facebook/react-native#4578]
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\person-workspace\offical-demo1\react-native\npm-debug.log

**Comment by ide** [comment]
fsevents should be optional so you shouldn't worry about it.

**Comment by skevy** [comment]
@gamedilong are you still encountering this issue? If not, please consider closing it - we're trying to keep the issue tracker easier to maintain.

**Comment by wisetwo** [comment]
try to install with this command: "npm install --no-shrinkwrap"
you can refer this issue: https://github.com/facebook/react-native/issues/4138
