### ISSUE TITLE
Promise.catch on a newline generates parsing error

### ISSUE THREAD

**Issue by RickWong** [facebook/react-native#458]
````js
		}).
		catch(function (error) {
````

> ![http://i.imgur.com/5oPp7VF.png](http://i.imgur.com/5oPp7VF.png)

Error is gone if `.catch()` without newline is used. This parsing error does not occur with `.\nthen()`

**Comment by amasad** [comment]
I think this might be jstransform reserved name quoting transform. Can you open the issue on the jstransform repo?

https://github.com/facebook/jstransform

**Comment by zpao** [comment]
This is a bug in jstransform (I have a fix). But @amasad, why are we using the reserved words transform at all in react-native? Surely we don't need to support any runtimes that depend on that.

**Comment by zpao** [comment]
Ah, because you're just including all the visitors from react-tools. We should do #518 and target es5.

**Comment by amasad** [comment]
@zpao although I wrote it, I forget that it's togglable

**Comment by brentvatne** [comment]
I believe this is no longer an issue
