### ISSUE TITLE
"ERROR: Unknown option --no-pretty" from watchman

### ISSUE THREAD

**Issue by adamski** [facebook/react-native#4580]
I am getting an error from watchman: 
```Error: watchman--no-pretty get-sockname returned with exit code 1 ERROR: Unknown option --no-pretty```

I initially installed it with npm install -g watchman. Have since uninstalled it via npm. Installed via `brew install watchman --HEAD`

**Comment by skevy** [comment]
Hi @adamski - could you open up an issue on the watchman repo about this and consider closing this one? Thanks.

**Comment by adamski** [comment]
OK no probs, done.
