### ISSUE TITLE
'IconImage' has no propType for native prop 'SMXIconImage.renderToHeadwareTextureAndroid' of native type 'boolean' on Android

### ISSUE THREAD

**Issue by awesomepankaj** [facebook/react-native#4581]
I just upgraded my react native version to 0.16.0 and then I am getting error.

**Comment by christopherdro** [comment]
@awesomepankaj Looks like this is coming from the third party module [react-native-icons](https://github.com/corymsmith/react-native-icons).

Perhaps making sure that your using the latest version might be a good place to start but I would also recommend you open up an issue with them as well.

**Comment by awesomepankaj** [comment]
ok. thanks
