### ISSUE TITLE
[0.74.4]ERROR: [ContentDelivery.Uploader] Asset validation failed (90360) Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle XXXX.XXXX/Frameworks/hermes.framework is required.

### ISSUE THREAD

**Issue by efstathiosntonas** [facebook/react-native#45823]
### Description

After updating from 0.74.3 to 0.74.4 I get this error when shipping to testflight: 

```
ERROR: [ContentDelivery.Uploader] Asset validation failed (90530) Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'XXXX.XXXX/Frameworks/hermes.framework' is ''. (ID: 30ace45d-a8c8-4863-97bc-9d5d5434822d)
ERROR: [ContentDelivery.Uploader] Asset validation failed (90360) Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle XXXX.XXXX/Frameworks/hermes.framework is required.
```

probably offending PR: https://github.com/facebook/react-native/commit/924fb3de9bc9328c3315316fbb796b933be5bcbe

### Steps to reproduce

1. just updated from 0.74.3 to 0.74.4

### React Native Version

0.74.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6
  CPU: (20) arm64 Apple M1 Ultra
  Memory: 136.20 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.16.0
    path: ~/.nvm/versions/node/v20.16.0/bin/node
  Yarn:
    version: 4.2.2
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.16.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/stathis/.gem/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.4
    wanted: 0.74.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
```


### Stacktrace or Logs

```text
none
```

### Reproducer

none

**Comment by efstathiosntonas** [comment]
this is the `info.plist` of hermes: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AvailableLibraries</key>
	<array>
		<dict>
			<key>BinaryPath</key>
			<string>hermes.framework/hermes</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>xros-arm64</string>
			<key>LibraryPath</key>
			<string>hermes.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>xros</string>
		</dict>
		<dict>
			<key>BinaryPath</key>
			<string>hermes.framework/hermes</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-simulator</string>
			<key>LibraryPath</key>
			<string>hermes.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
		<dict>
			<key>BinaryPath</key>
			<string>hermes.framework/hermes</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>xros-arm64-simulator</string>
			<key>LibraryPath</key>
			<string>hermes.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>xros</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
		<dict>
			<key>BinaryPath</key>
			<string>hermes.framework/Versions/0/hermes</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-maccatalyst</string>
			<key>LibraryPath</key>
			<string>hermes.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>maccatalyst</string>
		</dict>
		<dict>
			<key>BinaryPath</key>
			<string>hermes.framework/hermes</string>
			<key>DebugSymbolsPath</key>
			<string>dSYMs</string>
			<key>LibraryIdentifier</key>
			<string>ios-arm64</string>
			<key>LibraryPath</key>
			<string>hermes.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
		</dict>
	</array>
	<key>CFBundlePackageType</key>
	<string>XFWK</string>
	<key>XCFrameworkFormatVersion</key>
	<string>1.0</string>
</dict>
</plist>
```

**Comment by huextrat** [comment]
Same error after update to `0.74.4` (previously 0.74.3)

**Comment by nicolascavallin** [comment]
In my case, affecting only after the update to `0.74.4`

**Comment by efstathiosntonas** [comment]
@cipolleschi Hi, just a cc 😄

**Comment by okwasniewski** [comment]
Hey, thanks for tagging me. I'll take a look today and try to come up with a fix cc: @cipolleschi

**Comment by okwasniewski** [comment]
This PR should adress this issue: #45840

**Comment by parthkanani93** [comment]
Getting the same issue  Please help anyone to fix this
<img width="784" alt="Screenshot 2024-08-01 at 11 30 27 AM" src="https://github.com/user-attachments/assets/bae50aca-5cce-4234-9b62-6280e9f6d8e3">

**Comment by efstathiosntonas** [comment]
@parthkanani93 there are 2 PRs linked in the issue and one comment linking to the PR that fixes it. Just wait for Meta team to merge and release a new version

**Comment by akilamist** [comment]
Guys any update on this ? My expo build is failing due to this

**Comment by parthkanani93** [comment]
Finally after 18 to 20 hrs Finally I have been able to solve using this you need add this key value pair on this infoplist of herems pods
<img width="835" alt="Screenshot 2024-08-02 at 12 49 28 PM" src="https://github.com/user-attachments/assets/0983cc61-44f7-474d-849d-cd2f8f347488">

**Comment by lorenc-tomasz** [comment]
On CI I'm using this on `Podfile`:

```python
post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # TODO Temporary fix for Hermes
    # Define the path to the Info.plist file
    info_plist_path = 'Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/Info.plist'

    # Check if Info.plist exists
    if File.exist?(info_plist_path)
      # Use PlistBuddy to add or update the MinimumOSVersion key
      # Add the key if it does not exist
      system("/usr/libexec/PlistBuddy -c 'Add :MinimumOSVersion string 14.0' '#{info_plist_path}' 2>/dev/null")

      # Set the value if the key already exists
      system("/usr/libexec/PlistBuddy -c 'Set :MinimumOSVersion 14.0' '#{info_plist_path}'")

      puts "Updated Info.plist at #{info_plist_path}"
    else
      puts "Info.plist not found at #{info_plist_path}"
    end
  end
  ```

**Comment by Cyberbolt** [comment]
> Finally after 18 to 20 hrs Finally I have been able to solve using this you need add this key value pair on this infoplist of herems pods最后，在 18 到 20 小时后，我终于能够使用这个解决问题了，您需要在herems pods的infoplist上添加这个键值对
> 
> ```
> <key>MinimumOSVersion</key>
> <string>14.0</string>
> ```
> 
> <img alt="Screenshot 2024-08-02 at 12 49 28 PM" width="835" src="https://private-user-images.githubusercontent.com/47061736/354574153-0983cc61-44f7-474d-849d-cd2f8f347488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzA1MjQsIm5iZiI6MTcyMjkzMDIyNCwicGF0aCI6Ii80NzA2MTczNi8zNTQ1NzQxNTMtMDk4M2NjNjEtNDRmNy00NzRkLTg0OWQtY2QyZjhmMzQ3NDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3NDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMmEyNzU0ZDc0YmEzNDNkOTIzMjgwNmVkYzRiZGYxY2ViYjFlNGUzZTAxYTY0ZjExOTVhZDA3ZTUxYjgyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZfmvHbHvJ4ZPrryB-QLcnmjCpQkDECMNAoo-Bc13fLg">

But this is dynamically linked in by RN. It’s not good to manually change the info.plist here, right?

**Comment by huextrat** [comment]
Version 0.74.5 fixes this bug

**Comment by JackJBlundell** [comment]
> 0.74.5

Nope, it does not!

**Comment by JackJBlundell** [comment]
Even with 0.74.5 this is still happening for me, not sure how to fix!

**Comment by okwasniewski** [comment]
> Even with 0.74.5 this is still happening for me, not sure how to fix!

Could you let me know if you removed the previously cached version of Hermes? After updating please run: 

```
git clean -xdf ios
```

To clean unchecked files. Running pod install again will download a new Hermes binary.

**Comment by JackJBlundell** [comment]
This unfortunately has not changed anything, I still get this when trying to archive and distribute:


<img width="744" alt="Screenshot 2024-08-06 at 12 34 26" src="https://github.com/user-attachments/assets/bb7d9e18-257f-4e5a-881e-48c47e536121">

**Comment by lorenc-tomasz** [comment]
@JackJBlundell Check Podfile.lock if it has new hermes. Sometime `pod install` doesn't update that one pod. No idea why, but it happens. 

@okwasniewski Just check 0.74.5 locally and on CI. Works as expected to me :) Thank you :)

**Comment by igorlamos** [comment]
> Version 0.74.5 fixes this bug

Works like a charm. Thank you!

**Comment by JackJBlundell** [comment]
> @JackJBlundell Check Podfile.lock if it has new hermes. Sometime `pod install` doesn't update that one pod. No idea why, but it happens.
> 
> @okwasniewski Just check 0.74.5 locally and on CI. Works as expected to me :) Thank you :)

Thanks! This worked for me - It's rare to get help so quickly - I sincerely appreciate it.

**Comment by alexander0205** [comment]
Solution for me.

1. Update React native to 0.75.5
2. Remove your Podfile.lock 
3. Install again

**Comment by efstathiosntonas** [comment]
hey guys, a simple `pod update` will do the trick. 

If a Pod get's updated and you can't or don't want to update then pin it on Podfile:

```ruby
pod 'SDWebImage', '=' + "5.19.2"
```

**Comment by afXIII** [comment]
> Check Podfile.lock if it has new hermes. Sometime `pod install` doesn't update that one pod. No idea why, but it happens.


@lorenc-tomasz this fixed it for me. Interesting that 'pod install' updates all pods with the exception of just one pod in this case: hermes-engine.

very curious why this happens

**Comment by JacobDel** [comment]
fyi: 0.74.5 introduces new issues (https://github.com/expo/expo/issues/30921). 0.75.0 is very new and a new update was introduced 9 hours later.. downgrading to 0.74.3 might be the better option

**Comment by JacobDel** [comment]
> Finally after 18 to 20 hrs Finally I have been able to solve using this you need add this key value pair on this infoplist of herems pods
> 
> ```
> <key>MinimumOSVersion</key>
> <string>14.0</string>
> ```
> 
> <img alt="Screenshot 2024-08-02 at 12 49 28 PM" width="835" src="https://private-user-images.githubusercontent.com/47061736/354574153-0983cc61-44f7-474d-849d-cd2f8f347488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDgyNzAsIm5iZiI6MTcyMzgwNzk3MCwicGF0aCI6Ii80NzA2MTczNi8zNTQ1NzQxNTMtMDk4M2NjNjEtNDRmNy00NzRkLTg0OWQtY2QyZjhmMzQ3NDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MDZmMGI4ZDU5ODRiNzE4NzZiMThhMmViNGZhMmVkMmU4NWU2ZmE5ZjM3Y2FhYmVlYmQ0NzkzYTIwNzM4ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Enj_RyZIU5ydmKcmG4ZJBHXoXik52oSSeUyzqH5pQDM">

0.74.5 is bugged for me (can't load images).
Assuming 0.75.1 is unstable, this might still be the best hardcoded solution.
However, the MR fix (https://github.com/facebook/react-native/commit/10e9669ad11141b155caa606638b4c6081fcf01c) suggests version 13.4 rather than 14

**Comment by cipolleschi** [comment]
@JacobDel I'm sorry you encounter this problem. 0.74.5 is working correctly. We checked that all the plots inside the frameworks contain the right key-values.

Have you tried to run `bundle exec pod deintegrate && bundle exec pod install` to force Cocoapods to redownload the artifacts?
I think that it was using a malformed cached version of the tarball

**Comment by JacobDel** [comment]
> @JacobDel I'm sorry you encounter this problem. 0.74.5 is working correctly. We checked that all the plots inside the frameworks contain the right key-values.
> 
> Have you tried to run `bundle exec pod deintegrate && bundle exec pod install` to force Cocoapods to redownload the artifacts? I think that it was using a malformed cached version of the tarball

Apologies for the confusion, I just wanted to give a heads up to others who were thinking of upgrading to 0.74.5 or higher.
0.74.5 indeed resolves the issue described in this thread.

**Comment by MateuszBukowski93** [comment]
downgrade to 0.74.3  fixed issue

**Comment by cipolleschi** [comment]
@MateuszBukowski93 0.74.5 fixes it, please do not downgrade but rather upgrade to the version with the fix.
if you are still encountering the issue, run `pod deintegrate` to cleanup the pods and reinstall the pods.

**Comment by marcos-cunha-gringo** [comment]
> Finally after 18 to 20 hrs Finally I have been able to solve using this you need add this key value pair on this infoplist of herems pods
> 
> ```
> <key>MinimumOSVersion</key>
> <string>14.0</string>
> ```
> 
> <img alt="Screenshot 2024-08-02 at 12 49 28 PM" width="835" src="https://private-user-images.githubusercontent.com/47061736/354574153-0983cc61-44f7-474d-849d-cd2f8f347488.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTc3NTIsIm5iZiI6MTcyNjQ5NzQ1MiwicGF0aCI6Ii80NzA2MTczNi8zNTQ1NzQxNTMtMDk4M2NjNjEtNDRmNy00NzRkLTg0OWQtY2QyZjhmMzQ3NDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE0MzczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ZjM0Y2JhMTQwOTlhODk2YzM5Yzg2MDM2NWVhM2RhZTI3YTM5NTVlYzQ1ZmZlNjJjODIzZmNlYmI5NzEwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SBSrucJg-y38GLv0o0SPnfe3qeuKRjw2t0qmDQX0ZcY">

This solution worked for me!

**Comment by DZamataev** [comment]
My approach after still having this issue on 0.74.5 was to add the lines in a podfile post install script.
```
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    # fix rn 0.74 issue https://github.com/facebook/react-native/issues/45823
    hermes_engine_path = File.join('Pods', 'hermes-engine', 'destroot', 'Library', 'Frameworks', 'universal', 'hermes.xcframework', 'ios-arm64')
    puts "[Fix rn 0.74 issue] Navigating to directory: #{hermes_engine_path}"

    # Find all Info.plist files in any subfolders, except the specific one
    Dir.glob(File.join(hermes_engine_path, '**', 'Info.plist')).each do |plist_path|
      puts "[Fix rn 0.74 issue] Processing Info.plist file: #{plist_path}"
      
      # Read the plist file
      plist_content = File.read(plist_path)
      puts "[Fix rn 0.74 issue] Read content from Info.plist file: #{plist_path}"
      
      # Check if the lines are already present
      if plist_content.include?('<key>MinimumOSVersion</key>') && plist_content.include?('<string>14.0</string>')
        puts "[Fix rn 0.74 issue] Lines already present in Info.plist file: #{plist_path}"
      else
        puts "[Fix rn 0.74 issue] Lines not present in Info.plist file: #{plist_path}"
        # Append the lines to the plist content
        updated_plist_content = plist_content.sub('</dict>', <<-PLIST
    <key>MinimumOSVersion</key>
    <string>14.0</string>
    </dict>
    PLIST
        )
        puts "[Fix rn 0.74 issue] Updated content for Info.plist file: #{plist_path}"
        # Write the updated content back to the plist file
        File.write(plist_path, updated_plist_content)
        puts "[Fix rn 0.74 issue] Wrote updated content to Info.plist file: #{plist_path}"
      end
    end
  end
```

**Comment by cipolleschi** [comment]
this is fixed. If you still have the issue, you have a cached version of hermes. 
Please run `bundle exec pod deintegrate` and then reinstall pods with `bundle exec pod install`

**Comment by aik117** [comment]
Following steps fixed this for me.

1) Update react-native version to 0.74.5
2) Delete package-lock.json
3) Run npm install
4) Delete Podfile.lock and Pods folder
5) Go to ios folder
6) Run pod deintegrate
7) Run bundle exec pod install
8) Clean build from xcode
9) Build from xcode
10) Archive from xcode

When i tried validating or distributing the archive, the error did not appear again
