### ISSUE TITLE
The loading area of RefreshControl does not disappear on iOS

### ISSUE THREAD

**Issue by huanguolin** [facebook/react-native#45858]
### Description

On iOS, as shown in the GIF below, page1 contains a `ScrollView` with a `RefreshControl`. I've set the background of the RefreshControl to a dark color. When the button on page1 is clicked, it navigates to page2. Clicking the button on page2 triggers the refreshing on page1, and then we navigate back to page1. However, after the refreshing on page1, the area occupied by the RefreshControl doesn't disappear. But, if I slightly scroll the page manually, the area shrinks and returns to normal.

### Steps to reproduce

Minimal repository to reproduce the issue: [rnRefreshControlIssue2](https://github.com/huanguolin/rnRefreshControlIssue2)

I have tested this on iPhone 14 Pro (iOS 17.5.1) and iPhone 13 (iOS 17.4.3), and can reproduce the issue 100% of the time on both devices.

Steps to reproduce:
1. On a Mac device, `git clone https://github.com/huanguolin/rnRefreshControlIssue2`
2. npm run ios:init
3. npm run ios
4. Tap "goto page2"
5. Tap "press to refresh and go back"
6. Now you should see that the gray area containing the RefreshControl does not disappear. It only disappears after manually scrolling the page.

### React Native Version

0.74.3

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Memory: 3.83 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.0
    path: ~/.nvm/versions/node/v18.16.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.16.0/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/leyserkids/.gem/ruby/2.7.7/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.7
    path: /Users/leyserkids/.rubies/ruby-2.7.7/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
emtpy
```

### Reproducer

https://github.com/huanguolin/rnRefreshControlIssue2

### Screenshots and Videos

![test](https://github.com/user-attachments/assets/382e4d60-fbfb-494e-92ed-48feed7895dc)

**Comment by huanguolin** [comment]
I tested it on the latest version 0.74.4, and there are no changes.

**Comment by AptypTheKing** [comment]
@huanguolin Why do you need to refresh page1 after leaving it? You need to add a state, which call RefreshControl when you need it. At least your case will not happen, but yeah, it should not be like that in any case.

**Comment by huanguolin** [comment]
@AptypTheKing This is common when using react-query because it caches the data. If page 1 is a todo list and page 2 is the page where the todo's are added, the todo list needs to be invalidated when you return to page 1 after the todo's have been added. Here is the code that is executed when page1 is returned:
```ts
const handlePress = useCallback(() => {
    queryClient.invalidateQueries({queryKey: [KEY]});
    nav.navigate('Page1');
  }, [queryClient, nav]);
```

**Comment by AptypTheKing** [comment]
@huanguolin I understand, but you are invalidating it even before navigated, I would change the flow for sure

**Comment by deepanshushuklad11** [comment]
@huanguolin Is This happening on android too ?

**Comment by huanguolin** [comment]
> @huanguolin Is This happening on android too ?

Android is working fine.

**Comment by huanguolin** [comment]
> @huanguolin I understand, but you are invalidating it even before navigated, I would change the flow for sure

Um.. Do you mean to reorder the two lines of code? 
Like this
```ts
nav.navigate('Page1');
queryClient.invalidateQueries({queryKey: [KEY]});
```

**Comment by deepanshushuklad11** [comment]
@huanguolin  On app start i can see the grey background , is this expected too .
If i scroll a bit it disappears.

**Comment by deepanshushuklad11** [comment]
@huanguolin can you try using removeQueries
queryClient.removeQueries({queryKey: [KEY]});

**Comment by huanguolin** [comment]
> @huanguolin On app start i can see the grey background , is this expected too . If i scroll a bit it disappears.
No, but this is not in my product app. So I'm not stressing about it.

**Comment by huanguolin** [comment]
> @huanguolin can you try using removeQueries queryClient.removeQueries({queryKey: [KEY]});

Thanks for your suggestion!
With this change, the bug is not triggered, but the behaviour is not what is expected: page1 is not refreshed after returning from page2.
