### ISSUE TITLE
SocketRocket: app store rejection

### ISSUE THREAD

**Issue by tptee** [facebook/react-native#459]
There's reports on SocketRocket's repo that the _connect method in SocketRocket resembles a private API method and doesn't pass iTunes Connect validation:r

https://github.com/square/SocketRocket/issues/226

**Comment by sahrens** [comment]
SocketRocket is only needed for debugging - you shouldn't have to include it in your final app submission if you run into any issues with this.

**Comment by tptee** [comment]
Cool, thanks for the heads-up!

**Comment by frantic** [comment]
@a2 - would you remind me how you did DEBUG/prod configuration for linking libraries? We would like to link libRCTWebSocketDebugger only for DEBUG builds

**Comment by a2** [comment]
You would want to set add the `-lRCTWebSocketDebugger` build flag only in DEBUG. If you use CocoaPods, this becomes much easier as you can set up a debug-only dependency using the following in your _Podfile_:

```ruby
pod 'React/RCTWebSocketDebugger', :configurations => ['Debug']
```
