### ISSUE TITLE
Why does TabBarIOS.Item's `icon` property have a `scale` value?

### ISSUE THREAD

**Issue by dygg** [facebook/react-native#4591]
In the UIExplorer example :
`icon={{uri: base64Icon, scale: 1}}`

`icon` is the `Image.propTypes.source` type, but that type have not `scale` named value:

`
type ImageSource = {
  uri: string;
};
`

how can i known any other named value supported by the `icon` or `Image.propTypes.source` ?

**Comment by brentvatne** [comment]
Good point! We should change the definition of `selectedIcon` propType to include scale. This would be a nice easy first pull request :)

**Comment by mkonicek** [comment]
@facebook-github-bot answered
