### ISSUE TITLE
hard to find runtime error location

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#4593]
![2015-12-06 12 04 27](https://cloud.githubusercontent.com/assets/1779816/11611611/ac4e9526-9c11-11e5-80fd-6ba9d7eb3675.png)

Just as the picture shows. It's really hard to find out where the error located, especially when code base is very large. There is no stack trace associated with your code.

Anyone knows any solution?

**Comment by aksonov** [comment]
@narychen Check your page carefully or post it here, probably you forgot some space or something to wrap inside <Text>

**Comment by brentvatne** [comment]
@narychen - agreed, this is difficult to follow, we should try to get better traces here

**Comment by bestander** [comment]
@facebook-github-bot stack-overflow
