### ISSUE TITLE
Lowercase method names provided to fetch will fail on Android

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#4594]
When `fetch` is called with a lowercase method name, such as `patch` instead of `PATCH`, it will fail. Due to [okhttp's `permitsRequestBody`](https://github.com/square/okhttp/blob/parent-2.4.0/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpMethod.java#L32-L35), it performs a case-sensitive check for the provided method name. If a request body is supplied, and the method name is not explicitly `DELETE`, `POST`, `PUT` or `PATCH`, then it will not satisfy `permitsRequestBody` and will become thrown.

A solution would probably be to uppercase the incoming method name.

**Comment by ajwhite** [comment]
Ah! [normalizeMethod](https://github.com/facebook/react-native/blob/master/Libraries/Fetch/fetch.js#L239-L244) in `fetch` is missing `PATCH`.

PR incoming.

**Comment by ide** [comment]
For fetch please submit a patch (pun partly intended) to github who maintains the fetch polyfill.

**Comment by ajwhite** [comment]
Will do. For my understanding -- is `Libraries/Fetch/fetch.js` not used? Or a mirror of the GH polyfill?

**Comment by ide** [comment]
It's a manually synced copy of GitHub's fetch.

**Comment by ajwhite** [comment]
Thanks :+1:

**Comment by ajwhite** [comment]
Soo `PATCH` isn't in the `fetch` spec https://github.com/github/fetch/pull/243#issuecomment-162292086


Guess we'll just have to be careful

**Comment by skevy** [comment]
Given the fact that this is a fetch bug, not an RN one, I'm going to close this issue.

Thanks!

**Comment by ajwhite** [comment]
Sounds good. A heads up that they are not looking to address it.

**Comment by skevy** [comment]
Fwiw, axios (https://github.com/mzabriskie/axios) is a non-fetch-based http client that works on react native. Maybe give that a try?

**Comment by ajwhite** [comment]
Thanks for the link. I'm fine with fetch, it's just unfortunate there's a method that is commonly used this day that won't be added to their spec. Oh well.
