### ISSUE TITLE
[iOS] App does not correctly render RNTester borders, backgrounds, and shadow <Image> examples

### ISSUE THREAD

**Issue by cipolleschi** [facebook/react-native#45958]
### Description

The RNTester <Image> examples for border, Old arch and New arch also does not seem to correctly draw borders when a border-radius is set, and draws the border as if the radii is not present.

Table below represents the desired behavior, that is happening for Android, and how iOS renders the same scenario for the Old Arch and the New Arch

| Android (✅) | Old Architecture (❌) | New Architecture (❌)|
| --- | --- | --- |
| <img width="447" alt="Screenshot 2024-08-09 at 10 39 52" src="https://github.com/user-attachments/assets/5d5184da-ddba-4e02-aa39-beafdbbbd4b6"> | <img width="447" alt="Screenshot 2024-08-09 at 10 35 50" src="https://github.com/user-attachments/assets/0b8f2c0c-829f-4bf4-83c2-da0bd1b74f5f"> | <img width="447" alt="Screenshot 2024-08-09 at 10 34 12" src="https://github.com/user-attachments/assets/ed80ec73-30a1-4214-9dbc-f3de22ed1504"> |

### Steps to reproduce

1. Run RNTester
2. Scroll down to Image
3. Scroll down until Box Shadow is visible

To disable the New Architecture on iOS, you can also add this to the AppDelgate:
```objc
- (BOOL)newArchEnabled {
  return NO;
}
```

### React Native Version

0.76

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
n/a
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

https://github.com/facebook/react-native/packages/rn-tester

**Comment by coado** [comment]
Hey, I can check this out.

**Comment by NickGerleman** [comment]
IIRC @joevilches and @jorge-cab may have fixed some of these?

**Comment by cipolleschi** [comment]
Yes, this can be closed.
