### ISSUE TITLE
Can't build app with enabled Bridgeless mode on Android, but without can

### ISSUE THREAD

**Issue by RustamHashymov** [facebook/react-native#45955]
### Description

Try to build and bundle app with bridgeless mode on Android. So build is succeeded and also bundle, but after it immediately error happen. Tried build and bundle without bridgeless mode, and it works fine.  

### Steps to reproduce

1. Install app with react native 0.74.0
2. Enable bridgeless mode in MainApplication.kt.
3. Build app and bundle it.
4. See an error displayed on emulator

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android, Build - MacOS

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 84.42 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 4.3.1
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Stacktrace or Logs

```text
No logs. Error just displayed on emulator device
```

### Reproducer

-

### Screenshots and Videos

![CleanShot 2024-08-09 at 10 51 52](https://github.com/user-attachments/assets/f66c8401-7b13-46ec-968e-db4f99536dd0)

**Comment by cortinico** [comment]
We need a reproducer to help you further @RustamHashymov

**Comment by cipolleschi** [comment]
@RustamHashymov For Android, you should not enable bridgeless mode alone, but you should modify the `gradle.properties` file to set the `newArch` flag to true.

In 0.74, the New Architecture includes bridgeless enabled by default.
Bridgeless requires also TurboModule and Fabric to work properly, you cannot enable it alone.

**Comment by RustamHashymov** [comment]
@cipolleschi I mean here
```
package com.reproducerapp

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
  }
}

```

If I try to build and bundle with `load()` not `load(bridgelessEnabled=false)` it fails

**Comment by cortinico** [comment]
> @cipolleschi I mean here

@RustamHashymov please provide a reproducer project using this template: https://github.com/react-native-community/reproducer-react-native

**Comment by cipolleschi** [comment]
@RustamHashymov Yes, I know: Bridgeless is not supposed to be enabled in that way, in isolation. That setup will not work as it is not meant to work.

To enable Bridgeless for Android you need to enable the New Architecture:

1. Navigate to `<yourProject>/android` folder
2. Open the `gradle.properties` file
3. Change the `newArchEnabled` flag from `false` to `true`
4. Navigate back to `<yourProject>` folder
5. Run `yarn android`

And it will work!

That Boolean in the MainActivity is there if you want to **disable** Bridgeless **after** you enabled the New Architecture.

**Comment by RustamHashymov** [comment]
@cipolleschi I forgot to mention that I have enabled it in my project and app runs successfully, but after I enable bridgeless, I can't run app and have that error.

**Comment by cipolleschi** [comment]
If you enabled the new architecture on 0.74, you don't have to enable also bridgeless. It is enabled by default.
See https://github.com/reactwg/react-native-new-architecture/discussions/174
