### ISSUE TITLE
Annoying warning messages in debugger

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#4596]
![screen shot 2015-12-06 at 10 07 36](https://cloud.githubusercontent.com/assets/1061345/11612402/7fd309ba-9c01-11e5-9727-1001be0fd6b5.png)

These appear on the first key press when I am stopped in a breakpoint in chrome. Anybody else getting these?

**Comment by jaygarcia** [comment]
@eyaleizenberg , is this for React JS (Web??)

**Comment by eyaleizenberg** [comment]
For React Native @jaygarcia

**Comment by brentvatne** [comment]
@eyaleizenberg - I'm not seeing this and no mention of webkitIDBTransaction in the React Native codebase.. Is this Android?

**Comment by eyaleizenberg** [comment]
@brentvatne It seems to be originating from node_modules/uglify-js/tools/domprops.json

**Comment by brentvatne** [comment]
@eyaleizenberg - is it happening on master for you? are you using a minified bundle with dev mode enabled?

**Comment by eyaleizenberg** [comment]
I'm on RN 0.17 using master.
