### ISSUE TITLE
Image {require} is broken in React Native for Resizing

### ISSUE THREAD

**Issue by bradynapier** [facebook/react-native#4598]
It appears that it is not possible to create a full size image anymore within React Native using the require method.  I have tried many variations, but basically you can not get the image to automatically fit the dimensions of the entire screen.  Essentially when the image is too large, it stays too large, and it is not big enough, it is impossible to fill it.

I have tried absolutely positioning, flex values, resize modes, flex stretching, everything and nothing will work.  When loading from a uri it works beautifully using these methods.

http://www.smashingmagazine.com/images/iphone-wallpapers/gr.jpg

I will use this image as an example.  It works beautifully when using that

      <View style={{flex: 1, alignItems: 'stretch', backgroundColor: 'black'}}>
        <Image
          source={{uri: 'http://www.smashingmagazine.com/images/iphone-wallpapers/gr.jpg'}}
          style={{flex: 1, resizeMode: 'cover'}}
          resizeMode='cover'>
          {children}
        </Image>
      </View>

![image](https://cloud.githubusercontent.com/assets/8041420/11612943/5928d8fa-9bc3-11e5-8470-b4a3a2f571c7.png)

Now if I require it, there appears to be no way to automatically have it fill the screen without hacking it together in some way that will never guarantee perfect results with out a TON of calculations and extra libraries.

      <View style={{flex: 1, alignItems: 'stretch', backgroundColor: 'black'}}>
        <Image
          source={require('../assets/backgrounds/gr.jpg')}
          style={{flex: 1, resizeMode: 'cover'}}
          resizeMode='cover'>
          {children}
        </Image>
      </View>

![image](https://cloud.githubusercontent.com/assets/8041420/11612948/8b2fbbac-9bc3-11e5-928d-6aa6394f2983.png)

It would appear that the image itself is being wrapped in a view or something that is not filling the screen automatically.  Positioning with absolute position top bottom left and right makes the image the exact normal size of the image. 

     <View style={{flex: 1, alignItems: 'stretch', backgroundColor: 'black'}}>
        <Image
          source={require('../assets/backgrounds/gr.jpg')}
          style={{position: 'absolute', top: 0, right: 0, bottom: 0, left: 0}}
          resizeMode='stretch'>
          {children}
        </Image>
      </View>

![image](https://cloud.githubusercontent.com/assets/8041420/11612953/13d4a576-9bc4-11e5-88a1-8b2e16200307.png)

Anyway - the end result is it is impossible to work with dynamically required images.  Please fix this as it is a critical bug for my app, having to load them from the web kind of sucks!

**Comment by bradynapier** [comment]
Unfortunately Product Pains does not appear to work, it just says "uh-oh something went wrong" after posting and it also does nto support images inline with the content so the post may be confusing.

**Comment by edvinerikson** [comment]
I think the [image guide](https://facebook.github.io/react-native/docs/images.html#why-not-automatically-size-everything) holds the answer. If you use the `require` function the image will get a fixed width and height which will override any other properties that tries to alter the image size.

I solved this by not using the `require` function and instead doing it like this:
`<Image style={{resizeMode: 'cover', flex: 1}} source={{uri: 'BackgroundImage', isStatic: true}} />`
Where `BackgrondImage` is a asset/static resource in xcode.
However this was a few versions ago so things may have changed a bit.. (There was bugs like `.jpg` didn't work but `.png` did, etc)

**Comment by bradynapier** [comment]
Yes, static assets should work, but this is still a fairly critical bug as it doesn't work as one would expect.  It should be able to be overwritten just like any other asset.  Now I was able to solve this using a secondary module to feed the width and height of the screen to the image and manually set the width and height to the dimensions of the screen.  Once I have done that, it would appear that the resizeMode works as intended.  

This being said, it should make it simple enough for someone familiar with the RN Code to simply pull in the device dimensions from the Dimensions module and set the image properly when resizeMode='stretch' and the container is the size of the screen. I did notice that flex: 1 makes a difference when doing it this way.

This is kind of a hacky work around and it of course requires you make sure you feed the proper width/height to the image whenever the screen orientation is changed.

        <Image
          source={require('../assets/backgrounds/palms.jpg')}
          style={{flex: 1, width, height}}
          resizeMode='cover'>
          {children}
        </Image>

![image](https://cloud.githubusercontent.com/assets/8041420/11613103/f1177e90-9bc9-11e5-8bd7-5e9e7f075457.png)

![image](https://cloud.githubusercontent.com/assets/8041420/11613104/0573a1e8-9bca-11e5-8369-691c9aa89135.png)

**Comment by bradynapier** [comment]
andd... just in case, here is the entire component

     const Background = ({ height, width, background, children }) => {
       let bg;
       if (background === 'palms') {
         bg = require('../../assets/backgrounds/palms.jpg');
       } else if (background === 'blackwood') {
         bg = require('../../assets/backgrounds/blackwood.png');
       } else {
         // Default Background or no match to props provided
         bg = require('../../assets/backgrounds/space.jpg');
       }
     
       return (
           <Image
             source={bg}
             style={{flex: 1, width, height}}
             resizeMode='cover'>
             {children}
           </Image>
       );
     }

**Comment by DanielHoffmann** [comment]
@bradynapier as work around for now you can use base64 encoded images:
```
     <Image
         source={{uri: data:image/png;base64,iVBORw0KGgoAAAAN... }}
       </Image>
```
Dunno about the performance implications with react diffing algorithm though.

**Comment by satya164** [comment]
@bradynapier Have you tried setting `height` and `width` to `null`?

**Comment by bradynapier** [comment]
@satya164 you my friend are a genius!  That works beautifull!

**Comment by bradynapier** [comment]
Here is a re-useable version for anyone who needs it which will wrap an image behind it's children.  I stripped out the extra stuff so it'd be more re-useable.

     const Background = ({ children }) => {
       return (
           <Image
             source={require('./myBackground.png')}
             style={{flex: 1, width: null, height: null}}
             resizeMode='cover'>
               {children}
            </Image>
       );
     }

and it being used...
     
     <Background>
          ... content
     </Background>

**Comment by ph3b** [comment]
@bradynapier This is awesome! However, the children components seems to get rendered above the image. Like this:
![Image of Yaktocat](http://i.imgur.com/yYgynYR.png?1)
This is the code used:
```
     render(){
     return (
       <BgImage source={BackgroundImage}>
         <Text style={styles.text}>Hello</Text>
       </BgImage>
     )
}
```
Where BgImage is you functional component.

Do you use any special styles on the children components?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-require-is-broken-in-react-native-for-resizing

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by ceefour** [comment]
@satya164 no longer works in RN 0.47, setting width: null, height: null, simply makes the entire Image go unrendered (unless it has children, then it renders only part where there is children)

sigh :( heeeelppp..

**Comment by jdelafon** [comment]
Why is this closed? It is still broken, setting width and height to `null` did not help, and it is kind of an absurd and counterintuitive issue anyway, isn't it? The solution above is about a background, not the general case. And if there is a solution, where is it in the docs?
