### ISSUE TITLE
Are flexbox animations from JS possible?

### ISSUE THREAD

**Issue by jlongster** [facebook/react-native#46]
I'm writing another blog post about the theoretical possibility of applying React Native to the browser, running JS in a worker and using an asm.js-powered renderer on the main thread. (let's just assume that we can do text measurement and ignore a bunch of other big problems). I have an abstract question.

I know React Native handles animations, but I must be missing it in the source. I see `InteractionManager` which lets you schedule code to be run after animations are completed. But what is actually applying the animation?

Are we able to animate elements of a flexbox? Say we animated the width of an element from 50 to 100. If we did that, other elements with `flex: 1` would need to re-adjust. Since we do the flexbox layout in the JS side (right?) we would need to perform the animation on the JS side. But that's not possible is it? Wouldn't they prone to all sorts of jank, not even from talking over the bridge but even GC stuff?

Of course native animations are supported, but I'm wondering about transitions with the flexbox layout system.

**Comment by NecoleYu** [comment]
+1

**Comment by wootwoot1234** [comment]
Thanks @vjeux.  I'm new to React Native and still trying to wrap my head around everything.  I just re-read this thread after playing around with animations and it's very helpful.

I've been using AnimationExperimental, is that the same thing at Pop?  If not, is there a good example out there of using Pop in React Native?  If AnimationExperimental is an implementation of Pop, do you have an example of using the callback?  I would like to chain animations.

**Comment by brentvatne** [comment]
@wootwoot1234 - AnimationExperimental is deprecated. It uses CoreAnimation explicit animations under the hood, not Pop :) Unfortunately we're in an awkward limbo phase where a new animation API is about to land, but isn't quite ready yet.. I would recommend looking at react-tween-state or rebound.js (which you can grep for in the react-native source and find it is used in multiple places) to do pure js animations for now.

**Comment by skevy** [comment]
@wootwoot1234 You can also use GSAP to do imperative animations on react
native. Simple demo here: http://github.com/skevy/react-native-gsap-demo

**Comment by wootwoot1234** [comment]
@brentvatne, you're all over the place!  :)  You've been really helpful to me today, thanks!  I'll check out the js animations and will look forward to the new animations api.

@skevy thanks for the link, I'll check that out too.

**Comment by keithkml** [comment]
Hello, I read this entire thread and I don't understand the actual resolution. 

Sorry for using terms from other bug tracking systems, but was this issue closed as "won't fix," "obsolete," or "invalid"? I'm trying to understand whether animating changes in flex components is possible in RN.

Thanks!
