### ISSUE TITLE
Flipper repeatedly launches when initiating JS debugger

### ISSUE THREAD

**Issue by Eumhongin** [facebook/react-native#46001]
### Description

When launching the JS debugger, Flipper is repeatedly called and launched, causing interruptions and potentially slowing down the debugging process.

### Steps to reproduce

1. Start a React Native project
2. Attempt to launch the JS debugger
3. Observe that Flipper is repeatedly called and launched

### React Native Version

0.74.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 131.34 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
info Launching JS debugger...
warn Attempting to debug JS in Flipper (deprecated). This requires Flipper to be installed on your system to handle the 'flipper://' URL scheme.
info In React Native 0.74, Flipper is no longer included for new React Native projects. The Flipper React Native plugin is also unsupported. You can continue to use Flipper to debug your app's JavaScript code, however we recommend switching to a modern alternative.
See https://reactnative.dev/docs/debugging#opening-the-debugger.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by Eumhongin** [comment]
version 0.73.8 same

**Comment by huntie** [comment]
@Eumhongin Can you share a video screencast with the behaviour? If you can, please also try with a newer/older version of Flipper, to see if the behaviour changes.

**Comment by Eumhongin** [comment]
@huntie Thx for Reply!

I don't usually use Flipper, and this issue occurred independently of Flipper. I haven't tried using either the new or previous versions of Flipper, and I don't plan on using it. Is there another solution or suggestion you might have?

I Just Press D on Metro and Press Just Debug!

**Comment by Eumhongin** [comment]
@huntie 0.72.15 is Working!

**Comment by Eumhongin** [comment]
or any recommand debug tools? anyone? 😭 I use React-Native-Debugger with Redux Devtools.
This.

https://github.com/jhen0409/react-native-debugger

**Comment by Eumhongin** [comment]
Even after setting up the latest React Native boilerplate, I am seeing Flipper requests. Could anyone explain why this is happening? I was expecting a clean setup without any such requests.

**Comment by Eumhongin** [comment]
The React Native Debugger does not support apps using Hermes. So we must find new tools Thank you all. Close issue
