### ISSUE TITLE
unexpected use  of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by timzaak** [facebook/react-native#4601]
```
npm install -g react-native-cli
react-native init testProejct
```
open the ios proejct by Xcode, and run. then the following happens.

![abc](https://cloud.githubusercontent.com/assets/6149407/11614106/dc29730e-9c72-11e5-96b9-c088b297d0e2.png)

**Comment by satya164** [comment]
What version of Node are you using? You need at least Node 4.0

**Comment by timzaak** [comment]
node version is 4.2.3

**Comment by timzaak** [comment]
now I try one more time. And it successes! I don't know why. Sorry for this issue.

**Comment by matthewsimo** [comment]
@timzaak - What steps did you take to resolve this? I'm running into this setting up a new project and seeing same results. Tried multiple times with no luck. Any leads might help, thanks!

**Comment by satya164** [comment]
@matthewsimo Do you have a `.babelrc` in your project by any chance?

**Comment by matthewsimo** [comment]
@satya164 It does!

```
{
  "presets": ["stage-0", "react-native"],
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

**Comment by satya164** [comment]
@matthewjohnston4 The `.babelrc` looks correct though. Can you try removing it and see if works anyways?

**Comment by matthewsimo** [comment]
@satya164 Yes, we made a branch that removed the babel dependency and it is building properly for now. Doing some digging to find out where the conflict is, but no luck as of yet. Appreciate your responses, thanks. :+1:
