### ISSUE TITLE
Open Debugger button is missing when Hermes is disabled

### ISSUE THREAD

**Issue by Eumhongin** [facebook/react-native#46013]
### Description

After disabling Hermes by setting :hermes_enabled => false in the Podfile, the Open Debugger button is missing in the React Native DevTools. This issue prevents me from using the debugging tools when Hermes is disabled.

### Steps to reproduce

1. Open the Podfile in your React Native iOS project.
2. Set :hermes_enabled => false.
3. Run pod install to apply the changes.
4. Build and run the app.
5. Open the React Native DevTools.
6. Observe that the Open Debugger button is missing.
7. 
![스크린샷 2024-08-14 오후 3 02 45](https://github.com/user-attachments/assets/6b49dc6f-7f74-437c-af4f-ef067ef23368)

### React Native Version

0.74.5

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 1.33 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.11.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12071903
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
no
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

![스크린샷 2024-08-14 오후 3 03 39](https://github.com/user-attachments/assets/92778eee-7658-4b4c-b445-f6b57650e210)

**Comment by Eumhongin** [comment]
It is a disaster.. OMG

**Comment by cortinico** [comment]
cc @huntie

**Comment by huntie** [comment]
@Eumhongin When Hermes is disabled, you are using the JSC engine, where we are only offering support for [**Remote JS Debugging**](https://reactnative.dev/docs/next/other-debugging-methods#remote-javascript-debugging-deprecated). 

Since React Native 0.73, Remote JS Debugging is now **deprecated**, and we removed the option from the Dev Menu. Please see instructions above and in the [0.73 release post](https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#remote-javascript-debugging).
