### ISSUE TITLE
Issue with ScrollView and position: absolute in React Native 0.72.4

### ISSUE THREAD

**Issue by Hwirin-Kim** [facebook/react-native#46014]
### Description

When using position: absolute on a ScrollView, the scrollable area is limited to the height of its parent element, and any content beyond that height is not scrollable. 
This issue becomes particularly problematic when the parent element is smaller than the ScrollView. 

However, if you encounter the same issue, you can resolve it by using the ScrollView from the react-native-gesture-handler library, which does not exhibit this problem.

I'm currently using React Native version "react-native": "0.72.4".

### Steps to reproduce

1. Create a new React Native project (or use an existing one) with "react-native": "0.72.4".
2. Create a parent View with a fixed height (e.g., 100px).
3. Inside the parent View, add a ScrollView with position: absolute and content that exceeds the height of the parent View.
4. Run the application and try to scroll within the ScrollView.
5. Observe that the scrollable area is limited to the height of the parent View and any content beyond that is not scrollable.

### React Native Version

0.72.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 58.11 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
none
```

### Reproducer

none

### Screenshots and Videos

none

**Comment by cortinico** [comment]
Reproducer is missing
