### ISSUE TITLE
Inspector breaks when selecting a stateless component

### ISSUE THREAD

**Issue by edvinerikson** [facebook/react-native#4602]
When you select a stateless component in the Inspector (CMD-D -> Show Inspector) you will get `Cannot read propery 'props' of null`.

I've tracked the error down to this line: https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/Inspector/Inspector.js#L118-L119

The reason it throws is because the [`getPublicInstance`](https://github.com/facebook/react/blob/master/src/renderers/shared/reconciler/ReactCompositeComponent.js#L892-L894) method always returns `null` when you call it on a stateless component.

Without looking too much into the Inspector component code it seems that it uses the `style` prop from the selected component to paint a border around it (right?).
So to be able to "debug" stateless components we need access to the component props, and for we to able to access the props we need to access the public instance (any other way of access props?). 

I'm aware of two ways to access the instance.
 
1. use the `getPublicInstance` method (we can't atm).
2. use internals, access the `_instance` property (Very anti-pattern..).

The first one is not an option (not right now at least).
The second alternative seems very anti-pattern to me.

Is there any other alternatives? 

I'm willing to try to fix this bug but I need some advice on these things.

**Comment by skevy** [comment]
Hi @edvinerikson -- thanks so much for reporting!

I'm not sure how to fix this off the top of my head, but just a quick thought...would we be able to look at how React Devtools handles this to maybe get an idea of the proper way to make this work?

**Comment by edvinerikson** [comment]
It seems that Devtools is using `_instance` to get access.
https://github.com/facebook/react-devtools/blob/b18ec33387da1f315082564acb34015c772cf4b6/backend/getData.js#L35-L37

**Comment by spicyj** [comment]
Yeah, this should probably just use _instance. Don't use that in your own code, of course.

**Comment by ide** [comment]
Tagging this as help wanted since IIRC the inspector tools were an intern project and not sure if there's a clear owner of it at FB. Might be easy to fix if there's a React Dev Tools example already.

**Comment by edvinerikson** [comment]
Thanks for the advises. :+1:  I've submitted a PR https://github.com/facebook/react-native/pull/4642 that fixes this. A review of my solution would be very appreciated.

**Comment by skevy** [comment]
Thanks @edvinerikson. Closing as I shipped the PR.
