### ISSUE TITLE
[0.75.0] Failed to download template when init new app

### ISSUE THREAD

**Issue by EzioLi01** [facebook/react-native#46028]
### Description

Create new application with `init` command, failed in download template step. 

### Steps to reproduce

1. Install react-native
2. Create new app with init command
3. Get failure in download template step

### React Native Version

0.75.0

### Affected Platforms

Build - MacOS, Build - Windows, Build - Linux

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 58.11 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
✖ Downloading template
error Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

<img width="582" alt="Screenshot 2024-08-15 at 10 57 53" src="https://github.com/user-attachments/assets/4ead3c62-a7ee-48a8-b1a4-ca1918069b32">

**Comment by andrewhamili** [comment]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/ec89681d-f7d6-4369-ae0a-667465c2dcb5">

Also experiencing this issue on my side

**Comment by KingAmo** [comment]
see: https://github.com/reactwg/react-native-releases/issues/317#issuecomment-2289490391

**Comment by JakeStoeffler** [comment]
Is there a temporary workaround? I also tried `npx react-native@0.74.4 init MyNewProject` with no luck. Got the same error and empty project directory.

**Comment by juhyunk0820** [comment]
node.js와 npm 을 재설치하고, 모듈과 package-lock.json 등등 수정을 했는데도 같은 에러가 발생해요. 해결방안을 알 수 있는 가이드 라인이 있나요?

**Comment by Bileeta123** [comment]
> Is there a temporary workaround? This doesn't seem specific to 0.75. I also tried `npx react-native@0.74.4 init MyNewProject` with no luck. Got the same error and empty project directory.
> 
> edit: `npx react-native init MyNewProject --version 0.74.4` works!

Yes this works. (M1 Macbook pro)

**Comment by tobua** [comment]
In version `0.75.0` published to npm, there is no `/template` folder, which I assume is where the template is supposed to be. It seems [they are aware](https://github.com/reactwg/react-native-releases/issues/317#issuecomment-2289876785) of this issue, and it should be fixed in version `0.75.1`.

**Comment by tobua** [comment]
**Update**: Just read the release notes 😂 the template location was moved, try this:

```
bunx @react-native-community/cli@latest init AwesomeProject --template react-native-community/template
```

**Comment by andrewhamili** [comment]
> **Update**: Just read the release notes 😂 the template location was moved, try this:
> 
> ```
> bunx @react-native-community/cli@latest init AwesomeProject --template @react-native-community/template
> ```

Worked for me. Thanks

**Comment by toanle06** [comment]
> Is there a temporary workaround? This doesn't seem specific to 0.75. I also tried `npx react-native@0.74.4 init MyNewProject` with no luck. Got the same error and empty project directory.
> 
> edit: `npx react-native init MyNewProject --version 0.74.4` works!

you saved my day!

**Comment by cortinico** [comment]
> In version `0.75.0` published to npm, there is no `/template` folder, which I assume is where the template is supposed to be. It seems [they are aware](https://github.com/reactwg/react-native-releases/issues/317#issuecomment-2289876785) of this issue, and it should be fixed in version `0.75.1`.

Yup as mentioned, we're working on it and we'll publish a hot fix in the coming hours

**Comment by cortinico** [comment]
This has now been fixed with version 0.75.1:
https://github.com/facebook/react-native/releases/tag/v0.75.1

**Comment by TahaKhalidM** [comment]
same issue with this version as well

**Comment by Pajimo** [comment]
> **Update**: Just read the release notes 😂 the template location was moved, try this:
> 
> ```
> bunx @react-native-community/cli@latest init AwesomeProject --template @react-native-community/template
> ```

This worked for me, thank you. Looks like I will be using 'bunx' from now, already so used to npm or yarn
