### ISSUE TITLE
【Android】There is a delay in calculating the height of Modal content

### ISSUE THREAD

**Issue by peaktangf** [facebook/react-native#46029]
### Description

When the new architecture is opened and the bridge mode is closed, the Modal content height calculation has a problem, it is 0 at the beginning, and then it is normal

https://github.com/user-attachments/assets/9aa99389-a774-458a-8491-d1456ffbbebe

### Steps to reproduce

1、install the application with `yarn android`
2、load(true, true, false)
3、Modal show

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 13.4
  CPU: (10) arm64 Apple M2 Pro
  Memory: 90.53 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.0.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.6.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/01400926/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/01400926/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
not
```

### Reproducer

not

**Comment by shubhamguptadream11** [comment]
@peaktangf It will be great if you provide a repro using this [template](https://github.com/new?template_name=reproducer-react-native&template_owner=react-native-community). Also is this android specific?

**Comment by peaktangf** [comment]
> @peaktangf[如果您能提供使用此模板的](https://github.com/new?template_name=reproducer-react-native&template_owner=react-native-community)复制版本就太好了。这也是 Android 独有的吗？

yes
