### ISSUE TITLE
Facing Maximum call stack size exceeded (native stack depth), stack while upgrading react-native from 0.64.2 to 0.74.0

### ISSUE THREAD

**Issue by dev1038** [facebook/react-native#46085]
### Description

I am trying to upgrade react native for our android application from version 0.64.2 to 0.74.0 & able to build apk.
Installed apk in device & started metro server from $yarn start getting error 
com.facebook.react.common.JavascriptException: Maximum call stack size exceeded (native stack depth), stack

Below is content of my package.json
"peerDependencies": {
    "react": "^18.2.0",
    "react-native": "^0.74.0",
    "react-native-macos": "^0.72.21-0",
    "react-native-windows": "^0.74.0-0"
  },
  "dependencies": {
    "hoist-non-react-statics": "^3.3.2",
    "react-native-device-info": "^10.0.2",
    "react-native-gesture-handler": "1.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/plugin-transform-object-assign": "^7.12.1",
    "@babel/plugin-transform-private-methods": "^7.24.7",
    "@babel/plugin-transform-react-jsx-source": "^7.0.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/preset-react": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@react-native/babel-preset": "^0.74.81",
    "@react-native/metro-config": "^0.74.81",
    "@storybook/addon-actions": "^6.3.6",
    "@storybook/addon-essentials": "^6.3.6",
    "@storybook/addon-jest": "^6.3.6",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^6.3.6",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react": "^6.3.6",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "@types/react": "^17.0.19",
    "@types/react-native": "^0.64.13",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-loader": "^8.2.2",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-istanbul": "^6.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.6",
    "enzyme-to-json": "^3.6.2",
    "eslint": "7.14.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-promise": "^5.1.0",
    "eslint-plugin-standard": "^5.0.0",
    "flow-bin": "0.137.0",
    "jest": "^26.6.3",
    "metro": "^0.76.9",
    "metro-config": "^0.76.9",
    "patch-package": "^6.4.7",
    "prettier": "2.8.8",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.0",
    "react-native-macos": "^0.72.21-0",
    "react-native-safe-area-context": "^4.10.8",
    "react-native-web": "^0.17.1",
    "react-native-windows": "^0.74.0-0",
    "react-test-renderer": "18.2.0",
    "zulip-js": "^2.0.8"
  },
  "packageManager": "yarn@1.22.1"

### Steps to reproduce

- update package.json with mentioned version detail
- install node module
- created android apk from ./gradew assembleDebug
- install apk in device
- start metro server from $yarn start
- Getting Maximum call stack size error

### React Native Version

0.74.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 12.7.5
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 195.07 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 22.2.0
    path: ~/.nvm/versions/node/v22.2.0/bin/node
  Yarn:
    version: 1.22.1
    path: ~/.nvm/versions/node/v22.2.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v22.2.0/bin/npm
  Watchman:
    version: 2024.07.08.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 15.0
      - DriverKit 20.4
      - macOS 11.3
      - tvOS 15.0
      - watchOS 8.0
  Android SDK:
    API Levels:
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.2
      - 34.0.0
    System Images:
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11926650
  Xcode:
    version: 13.0/13A233
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.0
    wanted: 0.74.0
  react-native-macos:
    installed: 0.72.21
    wanted: ^0.72.21-0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
8764	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		Exception in native call from JS
8765	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		com.facebook.react.common.JavascriptException: Maximum call stack size exceeded (native stack depth), stack:
8766	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		RangeError: Maximum call stack size exceeded (native stack depth)
8767	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at call (native)
8768	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at call (native)
8769	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at slice (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:137523:76)
8770	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at call (native)
8771	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at call (native)
8772	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at slice (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:137523:76
8836	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at slice (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:137523:76)
8837	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at _taggedTemplateLiteral (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:141775:26)
8838	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:141893:89)
8839	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at loadModuleImplementation (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:267:14)
8840	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at guardedLoadModule (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:175:38)
8841	08-14	20:12:16.211	E	31160	31345	unknown:ReactNative:		at metroRequire (http://localhost:8081/index.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:89:92)
8965	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		Exception in native call
8966	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
8967	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at com.facebook.jni.NativeRunnable.run(Native Method)
8968	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at android.os.Handler.handleCallback(Handler.java:958)
8969	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at android.os.Handler.dispatchMessage(Handler.java:99)
8970	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
8971	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at android.os.Looper.loopOnce(Looper.java:205)
8972	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at android.os.Looper.loop(Looper.java:294)
8973	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
8974	08-14	20:12:16.228	E	31160	31345	unknown:ReactNative:		at java.lang.Thread.run(Thread.java:1012)
```

### Reproducer

NA

### Screenshots and Videos

<img width="510" alt="Screenshot 2024-08-18 at 1 12 26 PM" src="https://github.com/user-attachments/assets/e123f46e-044b-481f-9a99-783a7b004c79">

**Comment by cortinico** [comment]
We can't help without a repro. In general you should seek support for this kind of issues on Stackoverflow.

Also I'd suggest you upgrade version per version and avoid making a 10 version jump
