### ISSUE TITLE
Android how to provide a way for JS calls

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#4609]
I defined a Native UI component, it provides several methods for JS call , I added ReactMethod, but not able to find the method JS call , how should I do ?

**Comment by brentvatne** [comment]
Hi there! This isn't the best place to ask this kind of question, as the comment above suggests, you should try StackOverflow.

Here's my best attempt to quickly answer this question: check out this code for ViewPager to implement setPage & setPageWithoutAnimation: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/viewpager/ReactViewPagerManager.java#L57-L88

Good luck! :)

**Comment by shexiaoheng** [comment]
@brentvatne thanks , when i implement the JavaScript module , there was a mistake "Cannot read property 'dispatchViewManagerCommand' of undefined " , what should i do ?  My react-native version is 0.15.+ .

**Comment by shexiaoheng** [comment]
@brentvatne  thanks , I should be able to get it .

**Comment by shexiaoheng** [comment]
@brentvatne Many thanks for your answer , and how do i implement the JavaScript module to call UI component method?

**Comment by shexiaoheng** [comment]
@brentvatne Many thanks for your answer , I have solved this problem .
