### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by furkankinyas** [facebook/react-native#461]
Could not find dependencies.
Ensure dependencies are installed - run 'npm install' from project root.

Process terminated. Press <enter> to close the window

**Comment by corymsmith** [comment]
@furkankinyas Did you run npm install? Or was this project created via react-native init?

**Comment by arhoads76** [comment]
I'm running into the same problem.  I've tried react-native init for a custom project and also git clone on facebook/react-native followed by npm install.

**Comment by arhoads76** [comment]
looks like it was an old version of node.  updated node and nom and it's working fine now.

**Comment by corymsmith** [comment]
Glad you got it working.

**Comment by sethwklein** [comment]
If the above doesn't work for you, see https://github.com/facebook/react-native/issues/1758 .

**Comment by 3bola** [comment]
Try to install `babel` and `react-tools` locally to the project and not globally.
