### ISSUE TITLE
0.16.0 packager fails to build dependency graph

### ISSUE THREAD

**Issue by zmxv** [facebook/react-native#4610]
After I upgraded React Native from 0.15.0 to 0.16.0 and Babel from 5 to 6, the RN packager fails to start:

```
Error building DependencyGraph:
 Error: ENOENT: no such file or directory, open './node_modules/react-native/packager/react-packager/src/transforms/babel-plugin-system-import/6/index.js'
    at Error (native)
```

Without a stack trace, I have no idea which module is trying to load this non-existent file.

The release note did say that 0.16.0 using Babel 6 is a breaking change, so what needs to be done to fix it?

**Comment by christopherdro** [comment]
@zmxv Could you try wiping out your `node_modules` directory and run `npm install` again?

**Comment by zmxv** [comment]
@christopherdro Thanks! That works.
