### ISSUE TITLE
Some of us hate kotlin, give us java back.

### ISSUE THREAD

**Issue by rxbert125** [facebook/react-native#46106]
### Description

So new versions of react-native have kotlin files instead of java

developers like me that rely heavily on making native modules, use java for this purpose and java has always been the go to language and will forever be the goto language. Some of us absolutely hate kotlin and we dont want to develop in kotlin. So maybe at least give us the option to choose betwen java or kotlin

and bring back create-react-native-app npm package

### Steps to reproduce

yarn i 

### React Native Version

0.75.0

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
no react-native info neeeded
```

### Stacktrace or Logs

```text
No stack trace needed
```

### Reproducer

http://localhost

**Comment by cortinico** [comment]
> So maybe at least give us the option to choose betwen java or kotlin

You can totally use Java in your files as Java and Kotlin are interoperable. Just rename your files from `.kt` to `.java` and adapt the code to be compile for Java and you should be good to go.

We updated the default to be Kotlin, because that's where the mobile market was moving to.
