### ISSUE TITLE
React Native CLI - Error "configureCMakeDebug[arm64-v8a]" [CXX1410]

### ISSUE THREAD

**Issue by quanganh-snake** [facebook/react-native#46147]
### Description

Cmake using folder SDK expected buildTargetsCommandComponents command 'C:\Users\Anonuni\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe' to exist.

Maybe I changed the path of the SDK when installing Android Studio (D:\ASTSdkSetup), now I still want to use that new path to contain the SDK, how can I fix this error?

### Steps to reproduce

1. install "yarn install"
2. start "yarn start"
3. selected "a"

### React Native Version

0.74.5

### Affected Platforms

Runtime - Android, Build - Windows

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
COMPUTER:
Computer Type  	ACPI x64-based PC (Mobile)
Operating System  	Microsoft Windows 10 Pro
OS Service Pack  	-
Internet Explorer  	11.789.19041.0
Edge  	127.0.2651.105
DirectX  	DirectX 12.0

Storage:
Storage Controller  	Intel Chipset SATA RAID Controller
Storage Controller  	Microsoft Storage Spaces Controller
Disk Drive  	NVMe HFM001TD3JX013N (1024 GB, PCI-E 3.0 x4)
SMART Hard Disks Status  	FAIL

Processor Properties:
Manufacturer  	Intel(R) Corporation
Version  	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Serial Number  	To Be Filled By O.E.M.
Asset Tag  	To Be Filled By O.E.M.
Part Number  	To Be Filled By O.E.M.
External Clock  	100 MHz
Maximum Clock  	8300 MHz
Current Clock  	2673 MHz
Type  	Central Processor
Voltage  	0.8 V
Status  	Enabled
Socket Designation  	U3E1
HTT / CMP Units  	2 / 4
Capabilities  	64-bit, Multi-Core, Multiple Hardware Threads, Execute Protection, Enhanced Virtualization, Power/Performance Control
```

### Stacktrace or Logs

```text
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:configureCMakeDebug[arm64-v8a]'.
> [CXX1410] D:\1. Code Fullstack\react-native\TheCoffee_App\node_modules\react-native-screens\android\.cxx\Debug\64f12654\arm64-v8a\android_gradle_build.json debug|arm64-v8a : expected buildTargetsCommandComponents command 'C:\Users\QuangAnh\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe' to exist
```

### Reproducer

https://github.com/quanganh-snake/the-coffee-app

**Comment by cipolleschi** [comment]
Hi @quanganh-snake, thanks for opening the issue.
 
I don't think this is a New Architecture specific issue. From your reproducer, the New Architecture [is disabled](https://github.com/quanganh-snake/the-coffee-app/blob/main/android/gradle.properties#L37).

It look like your system is missing a dependency on [`ninja`](https://ninja-build.org/). But, AFAIK, it should not be mandatory.

cc. @cortinico ?

**Comment by cortinico** [comment]
> It look like your system is missing a dependency on [`ninja`](https://ninja-build.org/). But, AFAIK, it should not be mandatory.
> @cortinico do you know why we are looking for ninja and failing if we don't find it?

Ninja is installed as part of the Android SDK, so what you're having is a misconfigured environment @quanganh-snake 

Please follow the instructions on the getting started page:
https://reactnative.dev/docs/set-up-your-environment?os=windows&platform=android

and try again.
