### ISSUE TITLE
-X is not a valid cp flag, as a result condition always throws exit 1

### ISSUE THREAD

**Issue by mattmarich** [facebook/react-native#46141]
### Description

https://github.com/facebook/react-native/blob/774fe0cf6f22f832b756c166599973d9db6a93de/packages/react-native/scripts/react_native_pods_utils/script_phases.sh#L107

invalid flag for cp, please remove -X

### Steps to reproduce

Use script_phases.sh script

### React Native Version

na - latest

### Affected Platforms

Build - Linux

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 1.44 GB / 32.00 GB
  Shell:
    version: 5.2.21
    path: /opt/homebrew/bin/bash
...
npmPackages:
  react-native:
    installed: 0.73.8
    wanted: 0.73.8
...
```

### Stacktrace or Logs

```text
cp: invalid option -- 'X'
Try 'cp --help' for more information.
```

### Reproducer

na

**Comment by cortinico** [comment]
> React Native Version
> na - latest

Which version are you using. Here you say latest but in the `info` box you specified 0.73 @mattmarich
