### ISSUE TITLE
Android provide a way for JS calls , How do I write a Java and JS code?

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#4615]
My own definition of a component that provides a method to make JS call , and I need to achieve JS Module, I would like to refer to the full code . Thanks for the help of every person .

**Comment by mkonicek** [comment]
Hey @shexiaoheng, just curious - did StackOverflow work well for you?

**Comment by bozzmob** [comment]
@shexiaoheng Use [native components android](https://facebook.github.io/react-native/docs/native-components-android.html) to achieve the same.

**Comment by shexiaoheng** [comment]
@bozzmob I have solved it, thank you.

**Comment by shexiaoheng** [comment]
@mkonicek I can't find the relevant problems in the StackOverflow, but I have to solve it.
