### ISSUE TITLE
[Android] gradlew assembleRelease failing at bundleReleaseJsAndAssets

### ISSUE THREAD

**Issue by alexduckmanton** [facebook/react-native#4616]
I'm trying to generate a signed APK and can't seem to get `./gradlew assembleRelease` to complete. I'm on a Mac using React Native version 0.16.0. It fails at `:app:bundleReleaseJsAndAssets` with:

```
:app:bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/Users/alexduckmanton/Sites/project/Build/Intermediates/ArchiveIntermediates/project/BuildProductsPath/Release-iphoneos/project.app'.
```

Any ideas? Thanks!

**Comment by lalith26** [comment]
+1

**Comment by turka50** [comment]
+1

**Comment by brentvatne** [comment]
Weird! Still having this issue @alexduckmanton? I'd try deleting the build path and running it again. If this has persisted please re-create the issue :)

**Comment by JakeDoe** [comment]
+!
