### ISSUE TITLE
FlatList Items Not Occupying Full Screen Height with Paging Enabled

### ISSUE THREAD

**Issue by softgenicsShubham** [facebook/react-native#46175]
### Description

I'm encountering an issue with FlatList in a React Native application where items are not fully occupying the screen height when scrolling. The setup involves displaying video items in a FlatList within a bottom tab navigator, with each item intended to take up the entire screen height minus the bottom tab bar height. However, when scrolling, the next item begins to appear before the current item has completely scrolled off the screen.

Expected Behavior:
Each item should occupy the full screen height without any part of the next item being visible during scrolling. Scrolling should snap precisely to the next item, filling the entire screen.

Observed Behavior:
When scrolling, the next item starts becoming visible before the current item has fully scrolled off the screen. This causes an overlap where two items are partially visible at the same time, which is not the intended behavior.

### Steps to reproduce

1. Create a FlatList within a screen that is part of a bottom tab navigator.
2. Set each item in the FlatList to have a height equal to the screen height minus the bottom tab bar height.
3. Enable pagingEnabled on the FlatList to allow one item per screen.
4. Scroll through the items.

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 3.35 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/apple/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/apple/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
LOG  Running "video_app" with {"rootTag":11}
```

### Reproducer

https://github.com/softgenicsShubham/react-native-reproducer.git

### Screenshots and Videos

![Screenshot_1724345304](https://github.com/user-attachments/assets/5d1224cb-71d1-4107-8f74-9f4f6fcbfb97)

**Comment by shubhamguptadream11** [comment]
@softgenicsShubham I tried reproducing this with your repro provided. Not able to repro it on Pixel emulator.
Attaching video for your reference.
[Screen_recording_20240823_142520.webm](https://github.com/user-attachments/assets/d5d602a9-0d85-4865-a1cb-e7d274067791)

Is it device specific?

**Comment by softgenicsShubham** [comment]
@shubhamguptadream11, you will experience the same thing after some videos. As shown in the above screenshot, it will slightly start from the 24th video

**Comment by softgenicsShubham** [comment]
By the way, adding these two props will resolve the issue:

```jsx
snapToAlignment='start'
decelerationRate={'normal'}
```

 updated `FlatList` code

```jsx
<FlatList
  ref={flatListRef}
  data={data}
  pagingEnabled={true}
  onRefresh={handleRefreshing}
  refreshing={isRefreshing}
  renderItem={renderItem}
  keyExtractor={(item, index) => index.toString()}
  scrollEventThrottle={16}
  onEndReached={handleEndReached}
  onEndReachedThreshold={0.2}
  showsHorizontalScrollIndicator={false}
  showsVerticalScrollIndicator={false}
  initialNumToRender={1}
  removeClippedSubviews={true}
  onViewableItemsChanged={onViewableItemsChanged}
  viewabilityConfig={viewabilityConfig}
  pinchGestureEnabled={true}
  snapToAlignment='start'
  decelerationRate={'normal'}
  getItemLayout={(data, index) => (
    { length: height_screen, offset: height_screen * index, index }
  )}
/>
```

**Comment by varunvarshney00** [comment]
Thanks now my reels are working fine on android as well as ios. @softgenicsShubham

**Comment by suresmaharjan** [comment]
Thanks mine too
