### ISSUE TITLE
__DEV__ = false doesn't produce dead-code

### ISSUE THREAD

**Issue by glenjamin** [facebook/react-native#462]
It's unclear to me at this point whether this is important for a bundled native app.

When running normally, the bundle looks like this:

```js
> curl -s http://localhost:8081/index.ios.bundle?dev=true | head -n 20
/* eslint global-strict:0 */
__DEV__ = true;

/* eslint global-strict:0,eqeqeq:0,no-bitwise:0,no-undef:0 */
(function(global) {

  // avoid redefining require()
  if (global.require) {
    return;
  }

  var __DEV__ = global.__DEV__;

  var toString = Object.prototype.toString;

      /**
      * module index: {
      *   mod1: {
      *     exports: { ... },
      *     id: 'mod1',
```

And then when disabling dev mode

```js
> curl -s http://localhost:8081/index.ios.bundle?dev=false | head -n 20
/* eslint global-strict:0 */
__DEV__ = false;

/* eslint global-strict:0,eqeqeq:0,no-bitwise:0,no-undef:0 */
(function(global) {

  // avoid redefining require()
  if (global.require) {
    return;
  }

  var __DEV__ = global.__DEV__;

  var toString = Object.prototype.toString;

      /**
      * module index: {
      *   mod1: {
      *     exports: { ... },
      *     id: 'mod1',
```

Uglify doesn't seem to be able to figure out that `if(__DEV__)` can be eliminated, adding `sed s/\(__DEV__/\(false/` into a pipeline seems to work though.

**Comment by amasad** [comment]
I think we have a transform internally that does, I'll take a closer look. Do you know if closure compiler would be able to easily do that?

**Comment by ide** [comment]
You can also tell uglify to do constant replacement. It would need a little work since it changes `__DEV__ = false` into `false = false` but would otherwise fit well with the current pipeline.

**Comment by amasad** [comment]
I believe babel does simple dead code elimination now cc @sebmck

**Comment by sebmck** [comment]
@amasad Yup, through the optional `minfication.deadCodeElimination` and `minification.inlineExpression` transformers. Babel actually implements a JavaScript interpreter for expressions which I'm hoping to extend to statements in the future to allow some extremely awesome constant folding.

**Comment by amasad** [comment]
@sebmck This is awesome! Can you give an example of the awesome constant folding that would require understanding statements?

**Comment by sebmck** [comment]
@amasad 

What I really want to do is statically execute functions so turning:

```javascript
function square(num) {
  return num * num;
}

var a = square(4);
var b = square(2);
```

into:

```javascript
var a = 16;
var b = 4;
```

Similarly, I've got this currently working in a Babel branch:

```javascript
var a = 30;
var b = 9 - (a / 5);
var c;
c = b * 4;
if (c > 10) {
  c = c - 10;
}
console.log(c * (60 / a));
```

to

```javascript
console.log(4);
```

But it's pretty naive and there are a lot of edgecases that aren't handled which is why it's turned off.

**Comment by paramaggarwal** [comment]
Folks, could you please share how I can achieve dead code elimination here. I am generating a bundle with `dev=false` and still clocking 500KB. Please help!
