### ISSUE TITLE
RN@0.75 / Android / New Arch - Bug

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#46204]
### Description

Upgrading [my fork of `react-native-fs`](https://github.com/birdofpreyru/react-native-fs/tree/dev-v2.28) from RN@0.74 to RN@0.75, I believe I noticed a RN bug when building/running the library's example app for Android with the new arch. [This block of code](https://github.com/birdofpreyru/react-native-fs/blob/bf6a3dd1c823e07a22d07fccf97de92562a8073f/android/src/main/java/com/drpogodin/reactnativefs/Uploader.kt#L148-L157) with RN@0.74 worked fine without `if (key !== null)` safeguard; but when running with RN@0.75.2 it crashes because of the key being `null`, if I don't add the if guard, which is deemed unnecessary by Kotlin &mdash; when I open the project in Android Studio the `map` type is evaluated as ` (Mutable) Map<String!, (Mutable) List<String!>!>!`, hence the type of `key` is non-nullable `String!`, though it somehow may end-up `null` in the runtime.

I believe, these headers/keys originate from [this earlier block of code](https://github.com/birdofpreyru/react-native-fs/blob/bf6a3dd1c823e07a22d07fccf97de92562a8073f/android/src/main/java/com/drpogodin/reactnativefs/Uploader.kt#L62-L71), where `headers` originate from [here](https://github.com/birdofpreyru/react-native-fs/blob/bf6a3dd1c823e07a22d07fccf97de92562a8073f/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.kt#L744), and before that [here](https://github.com/birdofpreyru/react-native-fs/blob/bf6a3dd1c823e07a22d07fccf97de92562a8073f/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.kt#L730), and the `options: ReadableMap` object they are taken from corresponds to the TS-side definition [`headers?: StringMapT`](https://github.com/birdofpreyru/react-native-fs/blob/bf6a3dd1c823e07a22d07fccf97de92562a8073f/src/NativeReactNativeFs.ts#L219), where `StringMapT` is simply `type StringMapT = { [key: string]: string };`. So, my naive guess is that Codegen does something wrong now, or something else related to passing optional objects from TS to native side?

### Steps to reproduce

Clone https://github.com/birdofpreyru/react-native-fs/commit/bf6a3dd1c823e07a22d07fccf97de92562a8073f, and run Example App from the repo for Android, with `if (key !== null)` safeguard removed, see how `uploadFile()` test in the app fails; while it does not fail with the safeguard in place.

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android

### Areas

Codegen

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by cortinico** [comment]
> hence the type of `key` is non-nullable `String!`, though it somehow may end-up `null` in the runtime.

The type `String!` is a platform type, which meant that it could either by nullable or not (it depends from the Java side of things).

I think you're noticing this now as we migrated `WritableMap` to Kotlin in 0.75.

Do we know why you have a `null` key inside `.headerFields` in the first place @birdofpreyru

**Comment by cipolleschi** [comment]
Could it be due to this commit: https://github.com/facebook/react-native/commit/67b9628af588e8fc778d732fc387dbd48acf705e ?

**Comment by birdofpreyru** [comment]
> _do we know why you have a null key inside .headerFields in the first place_

No, at the TS side the method is called with undefined headers object, thus I'd expect that writable map to be just empty on native side.

**Comment by cortinico** [comment]
> No, at the TS side the method is called with undefined headers object, thus I'd expect that writable map to be just empty on native side.

What's the value for the `null` key?
