### ISSUE TITLE
Tried to show an alert while not attached to an Activity

### ISSUE THREAD

**Issue by birdofpreyru** [facebook/react-native#46201]
### Description

Migrating my existing libraries / apps from RN@0.74 to the latest RN@0.75.2. Using new architecture, targeting Android. Got `Tried to show an alert while not attached to an Activity` error when calling `Alert.alert('abc', 'def');`. Seems to be a regression of an old bug #13439?

P.S.: No, I had no chance yet to check whether it is reproducible in a clean RN app.

### Steps to reproduce

Above.

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android

### Areas

Other (please specify)

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by cipolleschi** [comment]
@birdofpreyru could you provide a reproducer using this [template](https://github.com/react-native-community/reproducer-react-native)? You can add whichever library you need to make the reproducer work.

It's quite hard for us to help out if we don't know how to repro it.

**Comment by cipolleschi** [comment]
It seems to work fine on my side... Am I missing something?

https://github.com/user-attachments/assets/56e7c5a4-a05f-4b9e-b84c-55b0c9fb0e42

**Comment by birdofpreyru** [comment]
Hmm... it works now for me as well 0.o Tried everything that comes to my mind &mdash; the older commit at which I was when reporting it, a clean build, a few different Android versions in the emulator... still no problem anymore.

**Comment by camerontbelt** [comment]
I had react-native-bottom-action-sheet installed, I started seeing this error and uninstalled bottom sheet and the error resolved.

**Comment by jenskuhrjorgensen** [comment]
I got here with the same issue and reading that it magically fixed itself for others made me try to close and reopen the app - and then it was also magically fixed on my end..

**Comment by Pingou** [comment]
Same problem, a restart helped, there must be some underlying bug though, can we reopen?

**Comment by jpancotti** [comment]
Fought this for an hour before finding this and restarting solved mine as well.
Do we have any idea if this is isolated to dev builds? I am concerned that alerts may be failing in production for whatever the same root cause is...
