### ISSUE TITLE
`Text` Components Positioned with bottom: 0 Gets Hidden Behind Navigation Bar on Android Devices

### ISSUE THREAD

**Issue by softgenicsShubham** [facebook/react-native#46217]
### Description

Description: When positioning a Text component at the bottom of the screen using position: 'absolute' and bottom: 0, the component gets hidden behind the navigation bar on Android devices that have a bottom navigation bar. This makes the content inaccessible or invisible to users.

### Steps to reproduce

1. Create a simple React Native application with a View container that occupies the full screen.
2. Add a Text component inside the View with position: 'absolute' and bottom: 0.
3. Run the application on an Android device with a bottom navigation bar.

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.35 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/apple/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/apple/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
logs
```

### Reproducer

https://github.com/softgenicsShubham/react-native-reproducer.git

### Screenshots and Videos

![Uploading Screenshot_1724697901.png…]()

**Comment by shubhamguptadream11** [comment]
@softgenicsShubham Can you update your screenshot. It's not visible I guess.

**Comment by shubhamguptadream11** [comment]
@softgenicsShubham Did you tried `useSafeAreaInsets` from [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context)?

**Comment by softgenicsShubham** [comment]
@shubhamguptadream11 

Yes, but I think that's a different thing. Even if you notice the warning or error messages generated internally, they still appear behind the navigation bar, which was not the case previously. 

And, it's not suitable for me because I also need the height of the status bar.

**Comment by shubhamguptadream11** [comment]
What if you provide `flex:1` to parent view instead of width and height? Since you are covering full screen only.

**Comment by softgenicsShubham** [comment]
That doesn't affect anything.

**Comment by shubhamguptadream11** [comment]
Can you try this code once.
```
import { Dimensions, StyleSheet, Text, View } from 'react-native'
import React from 'react'

const { width, height } = Dimensions.get('screen')

const App = () => {
  return (
    <View style={{flex: 1 }}>

      <Text
        style={{
          position: 'absolute',
          bottom: 40
        }}>
        Another text
      </Text>

      <Text
        style={{
          position: 'absolute',
          bottom: 0
        }}>
        App
      </Text>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})
```

**Comment by softgenicsShubham** [comment]
Above code will Work, But i have to keep the status bar hidden.

```
import { Dimensions, StyleSheet, Text, View } from 'react-native'
import React from 'react'
import { setHidden } from './src/native_modules/NavigationColorModules'

const { width, height } = Dimensions.get('screen')

const App = () => {
  return (
    <View style={{flex: 1 }} onLayout={() => {setHidden(true)}}>

      <Text
        style={{
          position: 'absolute',
          bottom: 40
        }}>
        Another text
      </Text>

      <Text
        style={{
          position: 'absolute',
          bottom: 0
        }}>
        App
      </Text>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})
```

**Comment by softgenicsShubham** [comment]
By the way,  Inside `SareAreaView` with `flex: 1` will work perfectly.
```
import { Dimensions, StyleSheet, Text, View } from 'react-native'
import React from 'react'
import { setHidden } from './src/native_modules/NavigationColorModules'
import { SafeAreaView } from 'react-native-safe-area-context'


const App = () => {
  return (
    <SafeAreaView style={{flex: 1}}>
      <View style={{ flex: 1 }} onLayout={() => { setHidden(true) }}>

        <Text
          style={{
            position: 'absolute',
            bottom: 40
          }}>
          Another text
        </Text>

        <Text
          style={{
            position: 'absolute',
            bottom: 0
          }}>
          App
        </Text>
      </View>
    </SafeAreaView>
  )
}

export default App

const styles = StyleSheet.create({})
```

**Comment by shubhamguptadream11** [comment]
Cool That's great @softgenicsShubham

**Comment by softgenicsShubham** [comment]
![Screenshot_1724772362](https://github.com/user-attachments/assets/cf2a55d0-ab20-4a79-8c9d-22eaca2f2a06)

**Comment by mahishdino** [comment]
@softgenicsShubham its not happening for me ?`import React from 'react';
import {Text, View} from 'react-native';

const App = () => {
  return (
    <View
      style={{
        flex: 1,
      }}>
      <View style={{bottom: 0, position: 'absolute'}}>
        <Text style={{fontWeight: '700'}}>Mahish Dino</Text>
      </View>
    </View>
  );
};

export default App;
![Screenshot_1724772890](https://github.com/user-attachments/assets/1a678019-0588-4ef5-b3ed-f2a0806b7ab3)

`

**Comment by softgenicsShubham** [comment]
@mahishdino Have you tried the reproducer ?

**Comment by softgenicsShubham** [comment]
You can try this

```
import { Dimensions, StyleSheet, Text, View } from 'react-native'
import React from 'react'
import { setHidden } from './src/native_modules/NavigationColorModules'

const { width, height } = Dimensions.get('screen')

const App = () => {
  return (
    <View style={{flex: 1 }} onLayout={() => {setHidden(true)}}>

      <Text
        style={{
          position: 'absolute',
          bottom: 40
        }}>
        Another text
      </Text>

      <Text
        style={{
          position: 'absolute',
          bottom: 0
        }}>
        App
      </Text>
    </View>
  )
}

export default App

const styles = StyleSheet.create({})
```

**Comment by mahishdino** [comment]
> setHidden

what is this setHidden ?

**Comment by softgenicsShubham** [comment]
@mahishdino  Please try reproducer ?

**Comment by mahishdino** [comment]
> @mahishdino Please try reproducer ?

I followed the steps which u have given, even tested your code, im not facing that issue. 
![Screenshot_1724773726](https://github.com/user-attachments/assets/c3a8cd27-d6f2-47da-b272-ce0e1f68238a)

**Comment by softgenicsShubham** [comment]
> You can try this
> 
> ```
> import { Dimensions, StyleSheet, Text, View } from 'react-native'
> import React from 'react'
> import { setHidden } from './src/native_modules/NavigationColorModules'
> 
> const { width, height } = Dimensions.get('screen')
> 
> const App = () => {
>   return (
>     <View style={{flex: 1 }} onLayout={() => {setHidden(true)}}>
> 
>       <Text
>         style={{
>           position: 'absolute',
>           bottom: 40
>         }}>
>         Another text
>       </Text>
> 
>       <Text
>         style={{
>           position: 'absolute',
>           bottom: 0
>         }}>
>         App
>       </Text>
>     </View>
>   )
> }
> 
> export default App
> 
> const styles = StyleSheet.create({})
> ```

have you tried this ?

**Comment by mahishdino** [comment]
> > You can try this
> > ```
> > import { Dimensions, StyleSheet, Text, View } from 'react-native'
> > import React from 'react'
> > import { setHidden } from './src/native_modules/NavigationColorModules'
> > 
> > const { width, height } = Dimensions.get('screen')
> > 
> > const App = () => {
> >   return (
> >     <View style={{flex: 1 }} onLayout={() => {setHidden(true)}}>
> > 
> >       <Text
> >         style={{
> >           position: 'absolute',
> >           bottom: 40
> >         }}>
> >         Another text
> >       </Text>
> > 
> >       <Text
> >         style={{
> >           position: 'absolute',
> >           bottom: 0
> >         }}>
> >         App
> >       </Text>
> >     </View>
> >   )
> > }
> > 
> > export default App
> > 
> > const styles = StyleSheet.create({})
> > ```
> 
> have you tried this ?

Yes, I tired it, I'm using RN 0.75.2 and Tested the code which you gave me. Issue is not happening at my side.

**Comment by softgenicsShubham** [comment]
This may only happen on the android version above 11.

**Comment by mahishdino** [comment]
@softgenicsShubham can u share me import { setHidden } from './src/native_modules/NavigationColorModules' this setHidden

**Comment by mahishdino** [comment]
> This may only happen on the android version above 11.

![Screenshot_1724774454](https://github.com/user-attachments/assets/80175fcb-7ce6-4f58-9a55-a582291621a9)
mine is Android 15 which is above 11

**Comment by softgenicsShubham** [comment]
@mahishdino That will be on the reproducer ?

**Comment by softgenicsShubham** [comment]
```

// Define and export the `setHidden` function
const setHidden = (hidden: boolean): void => {
    if (isNavigationColorModule(NavigationColor)) {
        NavigationColor.setHidden(hidden);
    } else {
        console.error('NavigationColor module or setHidden method is not available');
    }
};
```

**Comment by mahishdino** [comment]
> @mahishdino That will be on the reproducer ?

i got it

**Comment by mahishdino** [comment]
I'm checking on reproducer now
