### ISSUE TITLE
EarlyJsError: Unexpected token "?"

### ISSUE THREAD

**Issue by n9fy** [facebook/react-native#46278]
### Description

Disable Hermes engine and try to run app on android:

EarlyJsError: Unexpected token "?"

### Steps to reproduce

1. Disable Hermes
2. Run Android with `yarn android`

### React Native Version

0.75.2

### Affected Platforms

Runtime - Android

### Areas

Other (please specify)

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.0
  CPU: (12) arm64 Apple M2 Pro
  Memory: 132.44 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.0
    path: ~/.nvm/versions/node/v18.20.0/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.20.0/bin/npm
  Watchman:
    version: 2024.06.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-28 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
..
```

### Reproducer

..

### Screenshots and Videos

![Screenshot_1725033072](https://github.com/user-attachments/assets/31cb3369-9cd3-41a3-96fa-551d974e3736)

**Comment by cipolleschi** [comment]
Hi @n9fy Sorry that you are encountering the issue.

I just tried with a new app with 0.75.2 and it works fine on my side. You can see that I'm on 0.75.2, on the New Architecture and with no hermes, but the app is running fine.

<img width="1370" alt="Screenshot 2024-08-30 at 17 15 53" src="https://github.com/user-attachments/assets/1c2c238a-e4c4-463c-bb4d-4fe5d9c5487d">

please provide a reproducer using this [template](https://github.com/react-native-community/reproducer-react-native), otherwise we would not be able to help

**Comment by gurbela** [comment]
+1

**Comment by vksgautam1** [comment]
clean the build again and sync the files again in android studio. it should work

**Comment by cortinico** [comment]
Closing as we haven't heard from @n9fy anymore. Please get back to us with a valid reproducer and we'll be able to look into it

**Comment by musabgulfam** [comment]
Still encountering an error somewhat similar. I just upgraded from `react-native` version `0.72.7` to version `0.76.0`.
![Screenshot_20241201_171904_Park Social](https://github.com/user-attachments/assets/a1fbe26d-65c8-4a61-a6ad-d2d8dd88e886)

MainActivity.kt
```
package com.cannabis
import android.os.Bundle
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

class MainActivity : ReactActivity() {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "Cannabis"

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(null)
  }

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate] which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate = DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}
```

gradle.properties
```
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx512m -XX:MaxMetaspaceSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.jvmargs=-Xmx4096m


# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
android.enableJetifier=true

# Use this property to specify which architecture you want to build.
# You can also override it from the CLI using
# ./gradlew <task> -PreactNativeArchitectures=x86_64
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Use this property to enable support to the new architecture.
# This will allow you to use TurboModules and the Fabric render in
# your application. You should enable this flag either if you want
# to write custom TurboModules/Fabric components OR use libraries that
# are providing them.
newArchEnabled=true

# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled=true
MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
MYAPP_UPLOAD_STORE_PASSWORD=***
MYAPP_UPLOAD_KEY_PASSWORD=***
```

**Comment by musabgulfam** [comment]
> Still encountering an error somewhat similar. I just upgraded from `react-native` version `0.72.7` to version `0.76.0`. ![Screenshot_20241201_171904_Park Social](https://private-user-images.githubusercontent.com/40719485/391330968-a1fbe26d-65c8-4a61-a6ad-d2d8dd88e886.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTYxODQsIm5iZiI6MTczMzA1NTg4NCwicGF0aCI6Ii80MDcxOTQ4NS8zOTEzMzA5NjgtYTFmYmUyNmQtNjVjOC00YTYxLWE2YWQtZDJkOGRkODhlODg2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDEyMjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMzVhZTBmNjRmYWQ5MTU2ODRlNDEyYTJjNTk4NDRjMDQyMmFmMjlhMTAyMzAxYzFmMDVkZjRkZGU2MTk5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o8C6_gAFkJh6UsSXzVaUKYmtkBimoBcEeYmy7o075Do)
> 
> MainActivity.kt
> 
> ```
> package com.cannabis
> import android.os.Bundle
> import com.facebook.react.ReactActivity
> import com.facebook.react.ReactActivityDelegate
> import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
> import com.facebook.react.defaults.DefaultReactActivityDelegate
> 
> class MainActivity : ReactActivity() {
> 
>   /**
>    * Returns the name of the main component registered from JavaScript. This is used to schedule
>    * rendering of the component.
>    */
>   override fun getMainComponentName(): String = "Cannabis"
> 
>   override fun onCreate(savedInstanceState: Bundle?) {
>     super.onCreate(null)
>   }
> 
>   /**
>    * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate] which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
>    */
>   override fun createReactActivityDelegate(): ReactActivityDelegate = DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
> }
> ```
> 
> gradle.properties
> 
> ```
> # Project-wide Gradle settings.
> 
> # IDE (e.g. Android Studio) users:
> # Gradle settings configured through the IDE *will override*
> # any settings specified in this file.
> 
> # For more details on how to configure your build environment visit
> # http://www.gradle.org/docs/current/userguide/build_environment.html
> 
> # Specifies the JVM arguments used for the daemon process.
> # The setting is particularly useful for tweaking memory settings.
> # Default value: -Xmx512m -XX:MaxMetaspaceSize=256m
> # org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
> org.gradle.jvmargs=-Xmx4096m
> 
> 
> # When configured, Gradle will run in incubating parallel mode.
> # This option should only be used with decoupled projects. More details, visit
> # http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
> # org.gradle.parallel=true
> 
> # AndroidX package structure to make it clearer which packages are bundled with the
> # Android operating system, and which are packaged with your app's APK
> # https://developer.android.com/topic/libraries/support-library/androidx-rn
> android.useAndroidX=true
> android.enableJetifier=true
> 
> # Use this property to specify which architecture you want to build.
> # You can also override it from the CLI using
> # ./gradlew <task> -PreactNativeArchitectures=x86_64
> reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
> 
> # Use this property to enable support to the new architecture.
> # This will allow you to use TurboModules and the Fabric render in
> # your application. You should enable this flag either if you want
> # to write custom TurboModules/Fabric components OR use libraries that
> # are providing them.
> newArchEnabled=true
> 
> # Use this property to enable or disable the Hermes JS engine.
> # If set to false, you will be using JSC instead.
> hermesEnabled=true
> MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
> MYAPP_UPLOAD_KEY_ALIAS=my-key-alias
> MYAPP_UPLOAD_STORE_PASSWORD=***
> MYAPP_UPLOAD_KEY_PASSWORD=***
> ```

This is the upgrade guide
https://react-native-community.github.io/upgrade-helper/?from=0.72.7&to=0.76.0

**Comment by musabgulfam** [comment]
Yes, switching to versio `0.76.3` resolved the issue yesterday.
