### ISSUE TITLE
Fatal Exception: com.facebook.react.common.JavascriptException ReferenceError: Property 'until' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by AlphaebarcodeDevelopers** [facebook/react-native#46292]
### Description

In Android the app randomly crashing with the below error. Got this in firebase crashlytics dashboard and there is no log to debug and reproduce. 

Below are the dependencies.

"@coffeebeanslabs/react-native-inviewport": "^0.2.0",
    "@notifee/react-native": "^7.8.2",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-community/datetimepicker": "^8.2.0",
    "@react-native-community/netinfo": "^11.3.2",
    "@react-native-firebase/app": "^18.8.0",
    "@react-native-firebase/messaging": "^18.8.0",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.4.0",
    "deprecated-react-native-prop-types": "^2.2.0",
    "lottie-react-native": "^6.7.2",
    "moment": "^2.30.1",
    "numeral": "^2.0.6",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-animated-loader": "^1.0.0",
    "react-native-blob-util": "^0.19.9",
    "react-native-countdown-component": "^2.7.1",
    "react-native-detector": "^0.2.3",
    "react-native-device-info": "^11.1.0",
    "react-native-document-picker": "^9.3.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-exit-app": "^2.0.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.17.1",
    "react-native-image-pan-zoom": "^2.1.12",
    "react-native-image-picker": "^7.1.2",
    "react-native-image-slider": "^2.0.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-modal": "^13.0.1",
    "react-native-orientation": "^3.1.3",
    "react-native-paper": "^5.12.3",
    "react-native-pdf": "^6.7.5",
    "react-native-permissions": "^4.1.5",
    "react-native-progress-circle": "^2.1.0",
    "react-native-safe-area-context": "^4.10.8",
    "react-native-screens": "^3.32.0",
    "react-native-segmented-control-tab": "^4.0.0",
    "react-native-share": "^10.2.1",
    "react-native-simple-bottom-sheet": "^1.0.4",
    "react-native-simple-modal": "^9.0.1",
    "react-native-simple-toast": "^3.3.1",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^15.3.0",
    "react-native-swiper": "^1.6.0",
    "react-native-table-component": "^1.2.2",
    "react-native-text-ticker": "^1.14.0",
    "react-native-vector-icons": "^10.1.0",
    "react-native-video": "^6.3.0",
    "react-native-vision-camera": "^3.9.1",
    "react-native-webview": "^13.10.5"

### Steps to reproduce

Got it in Firebase Crashlytics and Play Store

### React Native Version

0.74.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.17134
  CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700F
  Memory: 4.31 GB / 15.84 GB
Binaries:
  Node:
    version: 20.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.18034.62.2411.12169540
  Visual Studio: Not Found
Languages:
  Java: 17.0.12
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
Fatal Exception: com.facebook.react.common.JavascriptException: ReferenceError: Property 'until' doesn't exist, js engine: hermes, stack:
anonymous@1:998365
anonymous@1:631935
emit@1:65632
emit@1:63340
__callFunction@1:55692
anonymous@1:53992
__guard@1:54951
callFunctionReturnFlushedQueue@1:53950

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:1013)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:328)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:233)
       at java.lang.Thread.run(Thread.java:1012)
```

### Reproducer

No response

### Screenshots and Videos

![Capture](https://github.com/user-attachments/assets/133236c5-e868-410a-aa4d-d82ceee9849a)

**Comment by cortinico** [comment]
> In Android the app randomly crashing with the below error. Got this in firebase crashlytics dashboard and there is no log to debug and reproduce.

The problem is that your app is dying while trying to execute the 'until' function:

```
Fatal Exception: com.facebook.react.common.JavascriptException: ReferenceError: Property 'until' doesn't exist, js engine: hermes, stack:
```

That could be coming from your application code or from a 3p library. Without a reproducer we can't help you further. You should seek further support on StackOverflow or create a reproducer.
