### ISSUE TITLE
Archive Generation bug using xCode: File /Users/codercrew/Library/Developer/Xcode/DerivedData/afrotech-fukqmquitupajjdgncczitrwnchg/Build/Intermediates.noindex/ArchiveIntermediates/afrotech/BuildProductsPath/Release-iphoneos/AfroTech.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'

### ISSUE THREAD

**Issue by mianaamirshehzad** [facebook/react-native#46309]
### Description

While generating Archive in the Xcode, I am facing the following issue:

File /Users/codercrew/Library/Developer/Xcode/DerivedData/afrotech-fukqmquitupajjdgncczitrwnchg/Build/Intermediates.noindex/ArchiveIntermediates/afrotech/BuildProductsPath/Release-iphoneos/AfroTech.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'

### Steps to reproduce

1. I'm using npm to install packages.
2. Install pods in iOS directory
3. Then open Xcode, clean build folder, select the device (any iOS device) and then start generating Archive. 

### React Native Version

0.72.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1
  Memory: 83.16 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.21
    path: ~/Downloads/afrotech-app/node_modules/.bin/yarn
  npm:
    version: 10.8.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
File /Users/codercrew/Library/Developer/Xcode/DerivedData/afrotech-fukqmquitupajjdgncczitrwnchg/Build/Intermediates.noindex/ArchiveIntermediates/afrotech/BuildProductsPath/Release-iphoneos/AfroTech.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues'
```

### Reproducer

None

### Screenshots and Videos

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b35e3d80-9da4-437a-95b3-e293179b187c">

**Comment by cipolleschi** [comment]
@mianaamirshehzad Sorry that you are encountering this issue.
The latest patch for version 72 is 0.72.17. There are several bugfixes in the 13 versions between .4 and .17. One of those might fix your issue.
Please, upgrade and try again.

0.72 is also out of support, so I anyway suggest you to upgrade to one of the supported versions.

**Comment by mianaamirshehzad** [comment]
> @mianaamirshehzad Sorry that you are encountering this issue. The latest patch for version 72 is 0.72.17. There are several bugfixes in the 13 versions between .4 and .17. One of those might fix your issue. Please, upgrade and try again.
> 
> 0.72 is also out of support, so I anyway suggest you to upgrade to one of the supported versions.

Thanks, this helped me in fixing the above issue.
