### ISSUE TITLE
App Crash using ReactNative@0.75.2&iOS12

### ISSUE THREAD

**Issue by salmanjones** [facebook/react-native#46323]
### Description

The app crashes when using React Native version 0.75.2 on iOS 12, but it runs successfully when using React Native version 0.72.10 on iOS 12.

### Steps to reproduce

1.build app

### React Native Version

0.75.2

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Max
  Memory: 2.01 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.3
    path: ~/.nvm/versions/node/v18.20.3/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.20.3/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.3/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.2
      - 31.0.0
      - 33.0.3
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_401
    path: /Library/Java/JavaVirtualMachines/jdk-1.8.jdk/Contents/Home/bin/javac
  Ruby:
    version: 3.3.3
    path: /Users/zhangchao/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
dyld: Library not loaded: @rpath/hermes.framework/hermes
  Referenced from: /var/containers/Bundle/Application/1A87F6A4-229D-4E84-882D-62B71F0A247D/TabletMagugi.app/TabletMagugi
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/1A87F6A4-229D-4E84-882D-62B71F0A247D/TabletMagugi.app/Frameworks/hermes.framework/hermes: missing LC_DYLD_INFO load command
	/private/var/containers/Bundle/Application/1A87F6A4-229D-4E84-882D-62B71F0A247D/TabletMagugi.app/Frameworks/hermes.framework/hermes: missing LC_DYLD_INFO load command
Message from debugger: Terminated due to signal 6
```

### Reproducer

https://github.com/salmanjones/TabletMagugi

### Screenshots and Videos

![WX20240904-174004@2x](https://github.com/user-attachments/assets/cab44465-e2a4-4961-b18e-e8a9ab37d3ce)
![WX20240904-174017@2x](https://github.com/user-attachments/assets/a3348596-32a2-485d-8c69-cce26bb90571)

**Comment by migueldaipre** [comment]
0.75+ requires min iOS 13.4 

https://reactnative.dev/blog/2024/08/12/release-0.75#last-version-supporting-minsdk-23-and-miniosversion-134

**Comment by salmanjones** [comment]
> 0.75+ requires min iOS 13.4
> 
> https://reactnative.dev/blog/2024/08/12/release-0.75#last-version-supporting-minsdk-23-and-miniosversion-134

What is the highest version of React Native that supports iOS 12? 
0.72.10？

**Comment by migueldaipre** [comment]
> > 0.75+ requires min iOS 13.4
> > https://reactnative.dev/blog/2024/08/12/release-0.75#last-version-supporting-minsdk-23-and-miniosversion-134
> 
> What is the highest version of React Native that supports iOS 12? 0.72.10？

Yes, [v0.72.17 ](https://github.com/facebook/react-native/blob/v0.72.17/packages/react-native/scripts/cocoapods/helpers.rb#L40) iOS 12.4
