### ISSUE TITLE
Style backgroundColor affecting layout

### ISSUE THREAD

**Issue by DanielHoffmann** [facebook/react-native#4632]
For some very strange reason not applying a backgroundColor seems to be making content outside the view become visible.
Take this example:
```javascript
    render() {
        return (
            <View style={{flex: 0, backgroundColor: 'blue'}}>
                <View style={{position: 'absolute', top: 50 }}>
                    <Text>aaaa</Text>
                </View>
            </View>
        );
   }
```
it gives this screen:
![image](https://cloud.githubusercontent.com/assets/2980150/11648313/34bef786-9d5a-11e5-9b09-1820f0411623.png)

Now lets try removing the backgroundColor on the View:
```javascript
    render() {
        return (
            <View style={{flex: 0}}>
                <View style={{position: 'absolute', top: 50 }}>
                    <Text>aaaa</Text>
                </View>
            </View>
        );
   }
```
it gives this screen (the text is visible):
![image](https://cloud.githubusercontent.com/assets/2980150/11648328/68119878-9d5a-11e5-8c01-4f18be23f187.png)

I am really confused now, I believe the second screen is the one that is correct (the outer View should have a height of zero). This was tested on Android 5.1, React Native 0.16.0.

**Comment by Creemli** [comment]
I have tried your code on IOS, it's ok. I guess the reason is position absolute.

**Comment by skevy** [comment]
@DanielHoffmann for the sake of making the RN issue tracker easier to maintain, I'm going to suggest that you open up a StackOverflow issue and close this.

If you find that there actually is a bug in RN surrounding this, feel free to ping here and we'll reopen.
