### ISSUE TITLE
React package in Cocoapod doesn't have the function "bundle" and some others, will facebook complete these functions?

### ISSUE THREAD

**Issue by Creemli** [facebook/react-native#4635]
In npm packages, react-native provide these functions: 
<code><pre>
 case 'start':
    runPackager();
    break;
  case 'install':
    install.init();
    break;
  case 'bundle':
    bundle.init(args);
    break;
  case 'new-library':
    newLibrary.init(args);
    break;
  case 'init':
    printInitWarning();
    break;
  case 'android':
    generateAndroid(
      process.cwd(),
      JSON.parse(fs.readFileSync('package.json', 'utf8')).name
    );
    break;
  case 'run-android':
</pre></code>

but in Cocoapod React, we can only find:
<code><pre>
case 'init':
    if (args[1]) {
      var verbose = process.argv.indexOf('--verbose') >= 0;
      init(args[1], verbose);
    } else {
      console.error(
        'Usage: react-native init <ProjectName> [--verbose]'
      );
      process.exit(1);
    }
    break;
  default:
    console.error(
      'Command `%s` unrecognized. ' +
      'Did you mean to run this inside a react-native project?',
      args[0]
    );
    process.exit(1);
    break;
  }
</pre></code>

<b>Does facebook plan to complete these functions in the future?</b>

Many thanks ~~

**Comment by ide** [comment]
Facebook doesn't use CocoaPods so I don't think these functions will be supported. Use `react-native init` instead of CocoaPods if you would like to use them, or if you would like to use CocoaPods then the source code is freely available for you to simulate what those functions are doing.
