### ISSUE TITLE
ListView doesn't have scrollTo method

### ISSUE THREAD

**Issue by mjhlybmwq** [facebook/react-native#4637]
```ListView``` doesn't  have ```scrollTo``` method like ```ScrollView```

**Comment by ide** [comment]
Call `listView.getScrollResponder().scrollTo(....)`:

```js
  /**
   * Provides a handle to the underlying scroll responder to support operations
   * such as scrollTo.
   */
  getScrollResponder: function() {
```

https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js#L224
