### ISSUE TITLE
react native ios app in xcode,when i run this project, the packager server start automatically

### ISSUE THREAD

**Issue by lvming6816077** [facebook/react-native#4638]
i don not want to start packager server automatically, because my js code not in this project.

**Comment by bob9630** [comment]
Hey Lvming6816077,
You can disable this by removing the build script in XCode. Look in your Dependencies group for React.xcodeproj. Then click on the "Build Phases" tab and delete the script. I assume you want this so you can include your JavaScript as a bundle directly in your app.

**Comment by lvming6816077** [comment]
thx bob9630, It works!
