### ISSUE TITLE
Android Crash: SIGSEGV 0x0000000000000000 - libc.so | Crashed: null pointer dereference 

### ISSUE THREAD

**Issue by vinayak-bm-ai** [facebook/react-native#46396]
### Description

```
Crashed: null pointer dereference #1
SIGSEGV 0x0000000000000000

libc.so
(Missing BuildId d1a98b526f2f94260a53c3055979a4f6)
```

We've observed that this crash spiked on 7th Sep.  
React Native Version: 0.71.13 with Hermes enabled

After investigating the statistics in Firebase Crashlytics, I found

1. It is happening mostly on Android 12+ devices.
2. Could not relate this to the memory shortage, devices had free memory (Adding screenshots for the same).

### Steps to reproduce

Not able to reproduce this issue as this has been occurring randomly on Android devices.

### React Native Version

0.71.13

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: Not Found
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Watchman: 2024.08.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33, 33, 34
      Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.2, 34.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10811636
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.13 => 0.71.13 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
null pointer dereference: SIGSEGV  0x0000000000000000
#00 pc 0x96850 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#01 pc 0x5b510c libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#02 pc 0x5b487c libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#03 pc 0x5b6814 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#04 pc 0x54eeb0 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#05 pc 0x5b6148 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#06 pc 0x933e24 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#07 pc 0x93023c libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#08 pc 0x160fc libbase.so (BuildId: 42d41ca7c77853791d096606e7186547)
#09 pc 0x156d0 libbase.so (BuildId: 42d41ca7c77853791d096606e7186547)
#10 pc 0x5b74ec libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#11 pc 0x30b2b4 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#12 pc 0x63eec8 libart.so (BuildId: 7300f6c36a74cc43266451736b120528)
#13 pc 0x104fc4 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
#14 pc 0x9e764 libc.so (BuildId: d1a98b526f2f94260a53c3055979a4f6)
```

### Reproducer

NA

### Screenshots and Videos

<img width="1413" alt="Screenshot 2024-09-09 at 17 35 29" src="https://github.com/user-attachments/assets/f7f763fc-feca-4943-ae20-1caa5d40603d">
<img width="1325" alt="Screenshot 2024-09-09 at 17 35 01" src="https://github.com/user-attachments/assets/89636b98-5d9c-4762-acd5-00b60bb7ecae">
<img width="1324" alt="Screenshot 2024-09-09 at 17 34 54" src="https://github.com/user-attachments/assets/47b3fa9a-3ffa-4e48-92cb-9b747cd644a1">
<img width="1317" alt="Screenshot 2024-09-09 at 17 34 47" src="https://github.com/user-attachments/assets/37574329-a7b9-4511-ba8a-d909729acb79">
<img width="1379" alt="Screenshot 2024-09-09 at 17 34 40" src="https://github.com/user-attachments/assets/b7538a9f-42bf-4191-9e13-840223e7cb63">

[com.brightcapital.app_issue_f4e23ef0af3b92e13a709b01f249ecfd_crash_session_66dea84e0283000168d5d19a075ad28a_DNE_0_v2_stacktrace (1).txt](https://github.com/user-attachments/files/16930320/com.brightcapital.app_issue_f4e23ef0af3b92e13a709b01f249ecfd_crash_session_66dea84e0283000168d5d19a075ad28a_DNE_0_v2_stacktrace.1.txt)

**Comment by cortinico** [comment]
> React Native Version: 0.71.13 with Hermes enabled

0.71 is unsupported sadly + this is a crash inside libc which we don't control. Sadly without a reliable reproducer there is nothing we can do here.
