### ISSUE TITLE
can i develop android or ios app in linux system, IDE use intellij or android stdio

### ISSUE THREAD

**Issue by wuchuguang** [facebook/react-native#4639]
i don't have Mac machine, so want use linux system develop android ,ios app, can i do it?
thx

**Comment by ImInApp** [comment]
@wuchuguang please post questions over here: http://stackoverflow.com/questions/tagged/react-native

**Comment by satya164** [comment]
@wuchuguang Hi @wuchuguang . Sadly, no. As of now, you need a Mac and OS X to develop iOS apps :(

**Comment by will-min** [comment]
no way
