### ISSUE TITLE
[Touchable] TouchableHighlight sometimes doesn't throw error when child is not native

### ISSUE THREAD

**Issue by jgable** [facebook/react-native#464]
I'm running into an error `Undefined is not a function` in `TouchableHighlight.js:161` where it looks like the `_showUnderlay` function is trying to call `setNativeProps` but that function doesn't exist on my component.

There is a `ensureComponentIsNative(this.refs[CHILD_REF]);` that fires in `componentDidMount` but the invariant exception is getting swallowed in `Transaction.js:216`.  This might be the real issue, why does the error get caught and ignored?

I tried to put together an example but the correct invariant error is thrown in [my example](https://gist.github.com/jgable/43391acf85ccdbf249bc).  I have a [branch up on Github](https://github.com/jgable/LoLCompanion/tree/swalledTouchableHighlightError) that you can clone down and modify to get it to reproduce (you'll need to comment out the `define.amd = {}` in `haste/polyfills/require.js` because of #406).

**Comment by brentvatne** [comment]
It looks like this is fixed now in 0.5: https://rnplay.org/apps/FtnarQ

Let me know if you run into it again!

**Comment by jgable** [comment]
:+1: thanks for verifying and closing, you're awesome.

**Comment by brentvatne** [comment]
:blush:
