### ISSUE TITLE
Testing Push Notifications

### ISSUE THREAD

**Issue by mikefrancis** [facebook/react-native#4641]
More of a question than an issue, wasn't really sure where to ask it.

Trying to set up Push Notifications and I've followed the [docs](https://facebook.github.io/react-native/docs/pushnotificationios.html), but when trying to use [APN Tester](https://itunes.apple.com/gb/app/apn-tester-free/id626590577?mt=12) with either the development or production certificates, I get nothing.

Just checking this is actually possible? If I use the device token/certificates from our native iOS app and try it works fine.

**Comment by richarddewit** [comment]
@mikefrancis - are you testing on the Simulator? Because there you won't be able to get a device token, so no way to receive push notifications. If you test on a device, you do get them.

**Comment by mikefrancis** [comment]
@richarddewit Think I've managed to figure it out - was testing on a connected device so I was able to get a device token.
