### ISSUE TITLE
reactnative.dev SITE IS DOWN. IT HAS BEEN DOWN FOR MORE THAN 3 HOURS

### ISSUE THREAD

**Issue by brighton-ifaya** [facebook/react-native#46446]
### Description

The site is simply not available.

### Steps to reproduce

Visit the site

### React Native Version

0.73.0

### Affected Platforms

Runtime - Web

### Output of `npx react-native info`

```text
The website!!
```

### Stacktrace or Logs

```text
The website!!
```

### Reproducer

https://reactnative.dev

**Comment by migueldaipre** [comment]
It's working normally
