### ISSUE TITLE
I can't open the new architecture according to the steps on the official website, on ios and android platforms

### ISSUE THREAD

**Issue by Qy742698** [facebook/react-native#46450]
### Description

Running "app_name" with {"fabric":true,"initialProps":{"concurrentRoot":true,"foo":"bar"},"rootTag":1} Not shown

### Steps to reproduce

1.yarn android 

### React Native Version

0.72.5

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
Running "app_name" with {"rootTag":1}
```

### Stacktrace or Logs

```text
no logger
```

### Reproducer

no

**Comment by cipolleschi** [comment]
Hi @Qy742698, version 0.72.5 is not supported anymore.
Can you try using version 0.75.3, which is the latest version?

Also, it's not clear what you are doing. Once you have an app, follow these steps to turn on the New Architecture:
#### Android:
* navigate to `<your app>/android` folder
* open the `gradle.properties` file
* change the flag `newArchEnabled` from `false` to `true`
* navigate back to `<your app>` folder
* run `yarn android`

#### iOS
* navigate to `<your app>/ios` folder
* run `bundle install` if you haven't done it yet (only once per app)
* run `RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
* navigate back to `<your app>` folder
* run `yarn ios`

**Comment by Qy742698** [comment]
The official document does not say that the bundle install command needs to be executed. The RCT_NEW_ARCH_ENABLED=1 bundle exec pod install command is executed, but the Running "app_name" with {"fabric":true,"initialProps":{"concurrentRoot":true,"foo":"bar"},"rootTag":1} log is not generated.
