### ISSUE TITLE
React Native IOS build not working with nodenv

### ISSUE THREAD

**Issue by migeorge** [facebook/react-native#4645]
Hello,

I'm using React Native 0.16.0 and I've found that the build task in Xcode does not use the same path as my terminal. Because of this it is unable to find nodenv and does not use the correct version of nodejs.

I was able to fix this by adding the following to react-native-xcode.sh

```
export PATH="$HOME/.nodenv/bin:$PATH"
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
```

Is this something that you would like a pull request for, or do you plan on supporting nvm only?

Thanks!

**Comment by skevy** [comment]
Hi @migeorge -

Personally, I'm not all that familiar with Nodenv, but if it helps newcomers to RN get started easier, I think we'd definitely accept a PR.

Feel free to submit and link it here.

**Comment by lpil** [comment]
:+1:

**Comment by ide** [comment]
#4801 is in master.

**Comment by thedaniel** [comment]
#4801 does not work for nodenv installed via homebrew, as binaries are in `/usr/loca/bin` not the user's homedir.

I fixed this on my own machine by creating a `~/.nodenv/bin` dir and symlinking `ln -s /usr/local/bin/nodenv ./nodenv`

I am not sure if this project wants to check a variety of places for nodenv or submit a patch to homebrew's nodenv package to add this symlink (as i gather from #4801 the bin is expected to be there) or something else.
