### ISSUE TITLE
[id: 'com.facebook.react.settings'] > java.io.UncheckedIOException:

### ISSUE THREAD

**Issue by manzoorsofi** [facebook/react-native#46479]
### Description

Just started the project with the latest version of React Native
at first build only got this error

What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
java.io.UncheckedIOException: Could not move temporary workspace

i tried removing gradle caches etc
Nope!

### Steps to reproduce

create latest react native project 
run in andriod
and thats where you see this error 

### React Native Version

0.75.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
  Memory: 3.88 GB / 15.79 GB
Binaries:
  Node:
    version: 18.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: ~\AppData\Roaming\npm\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.18034.62.2412.12266719
  Visual Studio: Not Found
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
Error resolving plugin [id: 'com.facebook.react.settings']
> java.io.UncheckedIOException: Could not move temporary workspace (C:\Users\sofim\Desktop\SalescrmApk\android\.gradle\8.8\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-257b0a10-5d39-44f3-ab1a-c8ed796303ff) to immutable location (C:\Users\sofim\Desktop\SalescrmApk\android\.gradle\8.8\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)
```

### Reproducer

https://github.com/idonthave

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/46210

**Comment by Vinayak-Soni-Git** [comment]
I created a new React Native project using React Native 0.77 and faced the same issue, but I just deleted the .gradle folder in the Android directory, and then I rerun the command 'npm run android,' and that worked for me.
