### ISSUE TITLE
No timeout on XMLHttpRequest

### ISSUE THREAD

**Issue by bobylito** [facebook/react-native#4648]
It seems that React Native is not implementing `timeout` [property](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout) on XMLHttpRequest.

**Comment by klvs** [comment]
Was this a result of code written by you (in your app) or from using a 3rd party library (parse, twilio, loopback, etc.)? Just curious. I'm working on a fix, but if it's not 3rd party code you could always use the fetch api in the meantime.

**Comment by bobylito** [comment]
Thanks @klvs :) I'm working on fixing a third party library (algoliasearch-client) for React-Native :)

Does `fetch` implement any timeout?

**Comment by klvs** [comment]
@bobylito My apologies, I was mistaken in thinking fetch has a timeout. Somewhat surprised myself but should have research more. Regardless, hopefully my PR is of high enough quality and will help you if you're still looking for a fix.

**Comment by mkonicek** [comment]
Let's continue discussing on the PR so the discussion is in one place: https://github.com/facebook/react-native/pull/4832
