### ISSUE TITLE
Simulator unusually slow, cannot debug

### ISSUE THREAD

**Issue by nickzarate** [facebook/react-native#4652]
For some reason, my react-native application is very slow when I simulate it. On an actual device, everything is normal and works properly. An example for what I mean when I say acting slow is that when I press CMD + D to try to debug in Chrome, the panel that comes up from the bottom of the screen moves slower than normal, and when it finishes coming up on the screen for some reason I cannot press any of the buttons. Also reloading the app with CMD + R reloads the application, but the panel that comes up when you press CMD + D stays up, and in order to hide it I have to stop the application in Xcode and start it again.

The same thing happens if I use an "alert" in my code, the alert message will appear slowly with the same effects (I can't press "OK" and I have to reboot the whole thing). Another example is that I am using Facebook login, and when I connect to Facebook, the Facebook permissions page comes up from the bottom of the screen very slowly, however, I can interact with that page and the application will continue as normal.

The issue I am having is that I cannot debug in Chrome because when I press CMD + D, I cannot click "Debug in Chrome". That is my main concern because I cannot debug, but I would also like to fix the slow animations because that should not be happening.

**Comment by ide** [comment]
Do you have slow animations turned on in the simulator?

**Comment by nickzarate** [comment]
Sorry Im new to this, how would I check that?

**Comment by ide** [comment]
See: https://stackoverflow.com/questions/8624519/simulator-slow-motion-animations-are-now-on

**Comment by nickzarate** [comment]
Yup had slow animations turned on, thanks for the help!
