### ISSUE TITLE
React Native Library .so files are not fortified

### ISSUE THREAD

**Issue by Rishitha2010** [facebook/react-native#46537]
### Description

Hi ,

When we analyze our build during decompilation there we could some react native libraries .so files are not compiled with D_FORTIFY_SOURCE=2.Fortify is a security feature to protect against incorrect use of standard functions - i.e. to protect against bad code implementation.

### Steps to reproduce

The command we use for checking Library compiled without binary protection is checksec --dir=lib/ after unzipping the APK file in Kali Linux.

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M3
  Memory: 75.69 MB / 24.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.3.0
    path: /private/var/folders/2y/kgbq31jn1dj6f9pm89d82lyc0000gn/T/xfs-1f504fc8/node
  Yarn:
    version: 3.6.4
    path: /private/var/folders/2y/kgbq31jn1dj6f9pm89d82lyc0000gn/T/xfs-1f504fc8/yarn
  npm:
    version: 10.8.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Ref: https://owasp.org/www-project-mobile-top-10/2014-risks/m10-lack-of-binary-protections
https://www.appknox.com/blog/understanding-owasp-top-10-mobile-lack-of-binary-protections
```

### Reproducer

https://github.com/slimm609/checksec.sh

### Screenshots and Videos

<img width="1370" alt="Image" src="https://github.com/user-attachments/assets/99d5a851-afca-4013-be02-e50716068aa3">

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/36870

Please see my comment here:
https://github.com/facebook/react-native/issues/36870#issuecomment-1714007068

Also please test against 0.76 RC1 as we implemented native library merging so now you will have to check only `libreactnative.so`.
