### ISSUE TITLE
Ability to dynamically unwrap ReadableMap and ReadableArray

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#4655]
I was working on the android integration of [react-native-intercom](https://github.com/asamiller/react-native-intercom) today and found that I had to forward an arbitrary `ReadableMap` to `Intercom` as a normal `Map` fully unboxed. I quickly realized there was no way to transform the `ReadableMap` into a usable object without recursively deconstructing it by hand.

Ideally, it'd be nice to have the ability to say `unwrap()` or `getObject()`.

My current approach is to use the `ReadableMapKeySetIterator` and [go through each node recursively](https://github.com/ajwhite/react-native-intercom/blob/88f2ddb84d3b850c1999e1f6e941735edd4d3a25/android/src/main/java/com/robinpowered/react/Intercom/IntercomModule.java#L131-L192)

```java

private Map<String, Object> recursivelyDeconstructReadableMap(ReadableMap readableMap) {
    ReadableMapKeySetIterator iterator = readableMap.keySetIterator();
    Map<String, Object> deconstructedMap = new HashMap<>();
    while (iterator.hasNextKey()) {
        String key = iterator.nextKey();
        ReadableType type = readableMap.getType(key);
        switch (type) {
            case Null:
                deconstructedMap.put(key, null);
                break;
            case Boolean:
                deconstructedMap.put(key, readableMap.getBoolean(key));
                break;
            case Number:
                deconstructedMap.put(key, readableMap.getDouble(key));
                break;
            case String:
                deconstructedMap.put(key, readableMap.getString(key));
                break;
            case Map:
                deconstructedMap.put(key, recursivelyDeconstructReadableMap(readableMap.getMap(key)));
                break;
            case Array:
                deconstructedMap.put(key, recursivelyDeconstructReadableArray(readableMap.getArray(key)));
                break;
            default:
                throw new IllegalArgumentException("Could not convert object with key: " + key + ".");
        }

    }
    return deconstructedMap;
}

private List<Object> recursivelyDeconstructReadableArray(ReadableArray readableArray) {
    List<Object> deconstructedList = new ArrayList<>(readableArray.size());
    for (int i = 0; i < readableArray.size(); i++) {
        ReadableType indexType = readableArray.getType(i);
        switch(indexType) {
            case Null:
                deconstructedList.add(i, null);
                break;
            case Boolean:
                deconstructedList.add(i, readableArray.getBoolean(i));
                break;
            case Number:
                deconstructedList.add(i, readableArray.getDouble(i));
                break;
            case String:
                deconstructedList.add(i, readableArray.getString(i));
                break;
            case Map:
                deconstructedList.add(i, recursivelyDeconstructReadableMap(readableArray.getMap(i)));
                break;
            case Array:
                deconstructedList.add(i, recursivelyDeconstructReadableArray(readableArray.getArray(i)));
                break;
            default:
                throw new IllegalArgumentException("Could not convert object at index " + i + ".");
        }
    }
    return deconstructedList;
}
```

This seems like a handy method that could exist on the `ReadableMap` and `ReadableArray` itself.

**Comment by ajwhite** [comment]
As a follow up question, would it be okay to implement this [in the java abstraction](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java)? Or would this need to live down in the [`jni` implementation](https://github.com/facebook/react-native/blob/510d50fc17157f186a593c2c02b3fcf610889c77/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp#L397-L464)

For instance, there's some [methods on the WritableNativeMap](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableNativeMap.java#L40-L60) that call the native methods

**Comment by morenoh149** [comment]
I would also find this useful. Honestly I can't even find docs on the `ReadableMap` type.

**Comment by morenoh149** [comment]
Nvm found it's a custom interface.

**Comment by ajwhite** [comment]
Yeah, takes a little looking around to locate it. Glad to see that there is some interest in this, I'll be getting to #4658 this week.

**Comment by hey99xx** [comment]
The commit should have likely been on `ReadableMap`, not on `ReadableNativeMap` (same applies for the array equivalents). 

The way it's written means the user has to cast `ReadableMap` into `ReadableNativeMap` before calling `toHashMap`. Although this would normally be ok, for anyone using [JavaOnlyMap](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/JavaOnlyMap.java) in their unit tests to mock their native modules (like me) this is a huge annoyance.
