### ISSUE TITLE
Problem embedding multiple ReactNative applications within main Objective-C app

### ISSUE THREAD

**Issue by justinmakaila** [facebook/react-native#4657]
I'm trying to run multiple `ReactNative` applications within a single Objective-C app. I wrote a little bundle script, very similar to `react-native-xcode.sh`. The only difference is that mine is based off the input and output files supplied by the user:
```
#!/bin/bash

case "$CONFIGURATION" in
  Debug)
    DEV=true
    ;;
  Release)
    DEV=false
    ;;
  "")
    echo "$0 must be invoked by Xcode"
    exit 1
    ;;
  *)
    echo "Unsupported value of \$CONFIGURATION=$CONFIGURATION"
    exit 1
    ;;
esac

# For the number of input files, get the input file name and corresponding output file name, and
# create a static bundle.
for (( i=0; i<$SCRIPT_INPUT_FILE_COUNT; i++ ))
do
  eval INPUT_FILE_NAME=\${SCRIPT_INPUT_FILE_$i}
  eval OUTPUT_FILE_NAME=\${SCRIPT_OUTPUT_FILE_$i}

  echo $INPUT_FILE_NAME
  echo $OUTPUT_FILE_NAME

  $(which react-native) bundle \
    --entry-file $INPUT_FILE_NAME \
    --dev $DEV \
    --platform ios \
    --bundle-output $OUTPUT_FILE_NAME

done
```

I have `ReactNative` applications specified in my `package.json` and installed using `npm install`. I specify the path to my input and output files in the `Run Script` build phase:
![screen shot 2015-12-08 at 18 03 59](https://cloud.githubusercontent.com/assets/1638996/11671401/151ec0b0-9dd6-11e5-9422-83e65047df53.png)

For whatever reason, my bundle is never updated after `npm install`.

Code:
<img width="545" alt="screen shot 2015-12-08 at 14 45 08" src="https://cloud.githubusercontent.com/assets/1638996/11671493/d294e444-9dd6-11e5-886d-eaf85e56755b.png">

Bundle:
![screen shot 2015-12-08 at 14 45 17](https://cloud.githubusercontent.com/assets/1638996/11671495/d697dbf0-9dd6-11e5-8f05-7cd5f72e41d1.png)

FWIW, the package, before being installed, did have a text component reading "Choose Subscriptions". It seems as if the `react-native bundle` command is using a cached file or something...

**Comment by skevy** [comment]
@justinmakaila In lieu of trying to make the issue tracker easier to manage, questions like this should probably go to StackOverflow (as the friendly Github bot up top explains).

If you determine that an issue in RN core is causing any issue that your seeing, or if you feel like there's places we can improve the documentation on embedding RN in existing iOS apps, please feel free to comment here and reopen this issue. :)

**Comment by skevy** [comment]
Also, if you post on StackOverflow, feel free to comment here with a link to the post.
