### ISSUE TITLE
[Packager] npm3 mainless package.json throws

### ISSUE THREAD

**Issue by dzannotti** [facebook/react-native#4659]
When using nod5 + npm 3 vanilla install, trying to require a module that does not have "main" in it's package.json (for ex `socket.io-client`) the packager fuses to require successfully. After downgrading to npm2 the same error disappeared.

not sure if it's because of missing "main" actually, but it's definitely a packager bug
(not letting me require files directly from node_modules using relative paths either for some reasons).

Can produce repro if needed

**Comment by jsierles** [comment]
@dzannotti Still seeing this issue? This package has a 'main' entry in lib/index, but I did notice it won't load unless you load the browser-compatible file as mentioned here: http://stackoverflow.com/a/32234446/1370358

If you think this is still an issue, please reopen here or open another issue with a repo we can test against. Thanks!
