### ISSUE TITLE
[iOS] Scrollviews inside row doesn't fire onMomentumScrollEnd

### ISSUE THREAD

**Issue by GuilhermeHCDias** [facebook/react-native#46592]
### Description

I tried to reproduce this same issue with the "old" architecture, and it works correctly, even though there's a closed issue due to inactivity (https://github.com/facebook/react-native/issues/32592) that describes this problem. However, it functions correctly in the old architecture. This issue only occurs in the new architecture.

When inserting 3 or more ScrollViews inside a View that has the style: `flex-direction: 'row'`, the `onMomentumScrollEnd` event is not triggered in one of the ScrollViews. The `snapToInterval` also doesn't work correctly, and is ignored. I imagine `snapToInterval` relies on `onMomentumScrollEnd` or something similar to it.
For some reason, if the ScrollView container takes up the full width of the device, the bug doesn't occur.

1. If you use any horizontal padding, the bug occurs.
2. If you place any element next to the ScrollViews, the bug occurs.

1. If you use margin, the bug doesn't occur.

In my reproduction, I included all these examples. Perhaps it is something related to the `contentContainer` of the ScrollView? I'm not sure. I tried reproducing as many scenarios as possible to reach a conclusion.

The bug occurs in Android and iOS(I don't tested in other devices)

### Steps to reproduce

1. run `yarn`.
2. run yarn `pod-install` if you want to use iOS devices.
3. run `yarn android` or `yarn ios`.
4. Scroll any of the rendered ScrollViews, each one exhibits the described issue.

### React Native Version

0.75.3

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

JSI - Javascript Interface

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 786.73 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.14.0
    path: /usr/local/bin/node
  Yarn:
    version: 3.6.4
    path: /usr/local/bin/yarn
  npm:
    version: 10.7.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.08.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.4
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
don't have
```

### Reproducer

https://github.com/GuilhermeHCDias/new-arch-scrollview-bug

### Screenshots and Videos

![Screenshot 2024-09-21 at 12 29 39](https://github.com/user-attachments/assets/87383b08-beb7-495f-8409-574938f76feb)

**Comment by GuilhermeHCDias** [comment]
up

**Comment by coado** [comment]
Hey @GuilhermeHCDias, the repro seems to be a default starting react native app. I think you might forget to commit the changes.

**Comment by GuilhermeHCDias** [comment]
> Hey @GuilhermeHCDias, the repro seems to be a default starting react native app. I think you might forget to push the changes.

You're right, man! So sorry, i've pushed the updates. Thank you!

**Comment by coado** [comment]
@GuilhermeHCDias I am not sure if I understand that correctly, but it seems like the `onMomentumScrollEnd` is called on each of the scroll views on the red examples. I've checked that on Fabric bridgeless, Fabric and old arch. I might misunderstand something, so could you please clarify the problem?

https://github.com/user-attachments/assets/0aebcb02-336e-4796-a932-1fdccc7f8bb1

**Comment by GuilhermeHCDias** [comment]
> @GuilhermeHCDias I am not sure if I understand that correctly, but it seems like the `onMomentumScrollEnd` is called on each of the scroll views on the red examples. I've checked that on Fabric bridgeless, Fabric and old arch. I might misunderstand something, so could you please clarify the problem?
> 
>  scrollviews-issue-recording.mov

So, what happens is that some scrollviews don’t trigger, while others do. If I perform the movement abruptly, it triggers, but if I do it slowly, it doesn’t. I’m running the example on an iPhone 16 Pro, but it happens on other devices as well. Is something with snapToInterval or onMomentumScrollEnd. Thank you for your try

https://github.com/user-attachments/assets/506e59c3-02a6-4110-bc2d-1131c5e656c0

**Comment by coado** [comment]
@GuilhermeHCDias I can see the problem now, thanks!

**Comment by coado** [comment]
> I’ve also tested it on other versions, including the latest unstable release (0.76.0-rc.3), but the issue still persists.

mhm and you also see this issue happen on Android? It seems to be fine there 🤔

**Comment by GuilhermeHCDias** [comment]
> mhm and you also see this issue happen on Android? It seems to be fine there 🤔

Sorry for the delay, I’ve been swamped lately. I tested it again on Android, and the bug didn’t show up this time, but it’s weird because I remember seeing it happen before on Android too.

**Comment by GuilhermeHCDias** [comment]
Yeah, man, you're right! This don't happens on Android, i've tested on 3 different Android versions on three diferent devices and the bug not happen
- Pixel 7
- Samsung Galaxy Note 20
- Redmi Note 7

**Comment by coado** [comment]
> Yeah, man, you’re right! This doesn’t happen on Android, i've tested on 3 different Android versions on 3 different devices.
> 
> * Pixel 7
> * Samsung Galaxy Note 20
> * Redmi Note 7

Awesome! Thank you so much for also checking this out 😁

**Comment by GuilhermeHCDias** [comment]
Thank you for updates ♥️

**Comment by zyy0810** [comment]
Version 0.81.4 still has issues
