### ISSUE TITLE
[Android] Error while updating property 'navIcon'  of a view managed by: ToolbarAndroid

### ISSUE THREAD

**Issue by NexusLee** [facebook/react-native#4660]
when I press one Item of the movie list, I get this error. I dont know what's wrong?

![qq 20151209084233](https://cloud.githubusercontent.com/assets/4703440/11673166/8685e3a2-9e51-11e5-9d5d-e3db69cae28f.png)

**Comment by NexusLee** [comment]
@facebook-github-bot  Thank you.

**Comment by jondot** [comment]
Please include `adb logcat` output, and look for a native Android exception and stacktrace to dump here. It is most probable that one of the resources is missing, or is not packed into the APK.

**Comment by terrysahaidak** [comment]
@NexusLee did you fix the issue?

**Comment by NexusLee** [comment]
@terrysahaidak Sorry，I didn't.

**Comment by anhldbk** [comment]
@NexusLee  Try to run react-native with sudo

**Comment by satya164** [comment]
Do you have a reproducible example?

**Comment by logicalicy** [comment]
Fyi, this error appears when you use `react-native-vector-icons`. Upgrading to 0.21+ fixes it apparently. See https://github.com/oblador/react-native-vector-icons/issues/134.

**Comment by christopherdro** [comment]
@facebook-github-bot answered
