### ISSUE TITLE
`onTextInput` callback of `TextInput` called twice in Android

### ISSUE THREAD

**Issue by jja08111** [facebook/react-native#46640]
### Description

The onTextInput of the TextInput component is called twice in Android. But it's called only once in iOS. 

### Steps to reproduce

1. Type the code in the app.
```tsx
function TestComponent() {
  return <TextInput onTextInput={(e) => console.log(e)} />
}
```

2. Run in Android.
3. Typing any text into TextInput.
4. Logged twice when typing text. 

### Expected Behavior

Called callback only once.

### Actual Behavior

Called twice. 

### React Native Version

0.74.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (12) arm64 Apple M3 Pro
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.yarn/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v16.20.2/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/khanhlequoc/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text

```

### Reproducer

https://snack.expo.dev/ZHB_NJNKYLXMqhc7GaSCi

**Comment by shubhamguptadream11** [comment]
@jja08111 onTextInput callback is now longer supported. Few months back it's JS reference was also removed [here](https://github.com/facebook/react-native/commit/910cde6134d5c1f6886764ab27c1102584532795).

You can check this release change: https://github.com/facebook/react-native/releases/tag/v0.74.5

**Comment by jja08111** [comment]
@shubhamguptadream11 Thanks for   your response!
