### ISSUE TITLE
is there a way to control the ripple duration in TouchableNativeFeedback??

### ISSUE THREAD

**Issue by manojHM** [facebook/react-native#4665]

**Comment by skevy** [comment]
Hi @manojHM, can you provide more information here? I'm not sure exactly what you mean.

**Comment by manojHM** [comment]
I used TouchableNativeFeedback for a View in my code .Onpressing that View i m navigating to the other page.But On press the ripple effect takes  a second or more sometimes to complete and navigate to the next page.I am calling a function on press of the View as shown below.


                  <TouchableNativeFeedback    
                   underlayColor='#A3A7AC' 
                   onPress={this.props.mainNavAction.bind(null,categoryitems[index])}
                   background={TouchableNativeFeedback.Ripple('#A3A7AC',false)}>     
                       <View >
                        ............
                       </View>       
                 </TouchableNativeFeedback>

**Comment by gtejasvi** [comment]
What my observation while using the TouchableNativeFeedback it takes a while for the action to work when using it. This is what I had observed.
As soon as the View is touched (delayPressIn and delayPressOut set to 0 to ensure that there is no delay), the native ripple feedback starts and continues till the end which takes about 200-300ms. I have given an animation to move the view around attached to the onPress, but this does not start till the ripple effect is complete, whereas I am expecting that action to happen in parallel. The way it looks is that your action begins only after the Ripple effect is completed and not as soon as the touch ends.

**Comment by satya164** [comment]
@manojHM Currently there is no way to configure the ripple effect duration.
@gtejasvi You can wrap your function in `requestAnimationFrame` for the effect to be visible immediately.

**Comment by elhachmi** [comment]
Hi,
I'm doing something like this to ensure that the navigation action of the press button is fired asynchronously after a ripple action has launched

```javascript
onPress={() => {
    let props = this.props
    setTimeout(function() {
        props.navigation.navigate("Action")
    }, 1)
    }
}
```
