### ISSUE TITLE
RN (0.75.2) metro bundler not connecting with iOS physical devices, if i build via Xcode

### ISSUE THREAD

**Issue by Praveencena88** [facebook/react-native#46660]
### Description

I have newly created a fresh react native app using `npx @react-native-community/cli@latest init AwesomeProject --version 0.75.2`

I'm building the app using Xcode and trying to install it on iPad device, the buld is getting successful and it installs the app on the device. But it doesnt connect with the metro bundle even after running `npx react-native start`

it throws this 

![Screenshot 2024-09-26 at 3 34 30 PM](https://github.com/user-attachments/assets/7b970b38-4158-41fb-ae66-d56701172bf2)

### Steps to reproduce

Build ios app using Xcode and try installing it on physical device and it doesnt connect with metro bundler

### React Native Version

0.75.2

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 15.0
  CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  Memory: 54.12 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.09.23.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.24
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
warning: the transform cache was reset.
                Welcome to Metro v0.80.12
              Fast - Scalable - Integrated


info Dev server ready

i - run on iOS
a - run on Android
d - open Dev Menu
r - reload app

info Reloading connected app(s)...
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading connected app(s)...
warn No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
```

### Reproducer

https://

**Comment by Praveencena88** [comment]
Xcode version - `Version 16.0 (16A242d)`
iPad OS version - 18.0
Processor - Intel Mac

**Comment by maxckelly** [comment]
Did you find a solution to this?

**Comment by BogdanRad** [comment]
> Experiencing the same issue with RN 0.74.7, Mac OS 15.5, Xcode 16.2 and iOS 18.4.1.
> 
> I think this started happening overnight after I updated my device's iOS to 18.4.1.
> 
> No issue building on android (physical device) or on iOS simulator.

Hello @mednche, did you find a solution? I have the same issue on android emulator.

<img width="575" alt="Image" src="https://github.com/user-attachments/assets/042cedfe-9f7a-430f-a5db-38472203298d" />

**Comment by astrahov** [comment]
Experiencing the same issue with RN 0.81.4, Mac OS 26.0.1, Xcode 26.0.1 and iOS 26.0.1.
