### ISSUE TITLE
Android app rejected by Google 

### ISSUE THREAD

**Issue by DThalikar** [facebook/react-native#46682]
### Description

We have uploaded the app to Google Playstore and it's been rejected. 
The reason they gave is app was not loading on Android 10. 
We recently upgraded the RN version from 0.72.4 to 0.74.5.

This is the log from Google's pre-launch report in Play console:
backtrace:
  #00  pc 0x00000000005032e4  /data/app/~~Ms0eoWRzPbrPucnCrt2KPg==/com.abcd.mobile-zS2cEkIoQEYqvvABZXkaTA==/base.apk!libjsc.so (BuildId: 9cb83e4124e3ee1471bc717c722b4109614385ba)
  #01  pc 0x000000000000089c  [vdso]
  #02  pc 0x00000000000a7cf8  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
  #03  pc 0x0000000000017cc0  /system/lib64/libutils.so (android::Looper::pollInner(int)+192)
  #04  pc 0x0000000000017b9c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #05  pc 0x0000000000168800  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #06  pc 0x00000000001c3964  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116)
  #07  pc 0x000000000058cc10  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+288)
  #08  pc 0x000000000043436c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556)
  #09  pc 0x0000000000466b9c  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1552)
  #10  pc 0x0000000000466564  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48)
  #11  pc 0x0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120)
  #12  pc 0x000000000202b300  /memfd:jit-cache (androidx.test.espresso.base.Interrogator.getNextMessage+176)
  #13  pc 0x000000000202879c  /memfd:jit-cache (androidx.test.espresso.base.Interrogator.loopAndInterrogate+284)
  #14  pc 0x00000000020259e8  /memfd:jit-cache (androidx.test.espresso.base.UiControllerImpl.loopUntil+456)
  #15  pc 0x0000000002029c24  /memfd:jit-cache (androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle+1108)
  #16  pc 0x000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #17  pc 0x00000000000d3972  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction.doPerform+30)
  #18  pc 0x000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #19  pc 0x00000000000d37e8  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform)
  #20  pc 0x0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #21  pc 0x00000000000d30ce  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction$1.call+106)
  #22  pc 0x000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #23  pc 0x00000000000d3048  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction$1.call)
  #24  pc 0x00000000002985ec  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+188)
  #25  pc 0x0000000000586f44  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+84)
  #26  pc 0x000000000058a2b8  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1032)
  #27  pc 0x0000000000589e10  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+560)
  #28  pc 0x00000000002ee444  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1316)
  #29  pc 0x0000000000434600  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576)
  #30  pc 0x0000000000466d34  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1960)
  #31  pc 0x0000000000466564  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48)
  #32  pc 0x0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120)
  #33  pc 0x0000000000503eb0  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+144)
  #34  pc 0x000000000050d1cc  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3404)
  #35  pc 0x0000000000434600  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576)
  #36  pc 0x000000000057e378  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+900)
  #37  pc 0x00000000005f1d7c  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+160)
  #38  pc 0x00000000000c1c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #39  pc 0x00000000000ce470  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+856)
  #40  pc 0x0000000000002570  /system/bin/app_process64 (main+1304)
  #41  pc 0x000000000004b930  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)

### Steps to reproduce

1. Install the app on Android 10 version
2. Repeatedly kill and open the app
3. App is not loading / crashing

### React Native Version

0.74.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 14.6.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 1.70 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: /usr/local/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: /usr/local/bin/npm
  Watchman:
    version: 2021.10.11.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.75.3 is now available (your project is running on v0.74.5).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.75.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.74.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

### Stacktrace or Logs

```text
backtrace:
  #00  pc 0x00000000005032e4  /data/app/~~Ms0eoWRzPbrPucnCrt2KPg==/com.abcd.mobile-zS2cEkIoQEYqvvABZXkaTA==/base.apk!libjsc.so (BuildId: 9cb83e4124e3ee1471bc717c722b4109614385ba)
  #01  pc 0x000000000000089c  [vdso]
  #02  pc 0x00000000000a7cf8  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+8)
  #03  pc 0x0000000000017cc0  /system/lib64/libutils.so (android::Looper::pollInner(int)+192)
  #04  pc 0x0000000000017b9c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116)
  #05  pc 0x0000000000168800  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48)
  #06  pc 0x00000000001c3964  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+116)
  #07  pc 0x000000000058cc10  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+288)
  #08  pc 0x000000000043436c  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+556)
  #09  pc 0x0000000000466b9c  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1552)
  #10  pc 0x0000000000466564  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48)
  #11  pc 0x0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120)
  #12  pc 0x000000000202b300  /memfd:jit-cache (androidx.test.espresso.base.Interrogator.getNextMessage+176)
  #13  pc 0x000000000202879c  /memfd:jit-cache (androidx.test.espresso.base.Interrogator.loopAndInterrogate+284)
  #14  pc 0x00000000020259e8  /memfd:jit-cache (androidx.test.espresso.base.UiControllerImpl.loopUntil+456)
  #15  pc 0x0000000002029c24  /memfd:jit-cache (androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle+1108)
  #16  pc 0x000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #17  pc 0x00000000000d3972  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction.doPerform+30)
  #18  pc 0x000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #19  pc 0x00000000000d37e8  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform)
  #20  pc 0x0000000000209334  /apex/com.android.art/lib64/libart.so (nterp_helper+52)
  #21  pc 0x00000000000d30ce  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction$1.call+106)
  #22  pc 0x000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #23  pc 0x00000000000d3048  /data/app/~~-8DAZKIPDcBfQHzS1RdNNw==/androidx.test.tools.crawler-6UQkRYg1H0_6Ct51OeSg6Q==/oat/arm64/base.vdex (androidx.test.espresso.ViewInteraction$1.call)
  #24  pc 0x00000000002985ec  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+188)
  #25  pc 0x0000000000586f44  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+84)
  #26  pc 0x000000000058a2b8  /system/framework/arm64/boot-framework.oat (android.os.Looper.loopOnce+1032)
  #27  pc 0x0000000000589e10  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+560)
  #28  pc 0x00000000002ee444  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1316)
  #29  pc 0x0000000000434600  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576)
  #30  pc 0x0000000000466d34  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1960)
  #31  pc 0x0000000000466564  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+48)
  #32  pc 0x0000000000099148  /system/framework/arm64/boot.oat (art_jni_trampoline+120)
  #33  pc 0x0000000000503eb0  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+144)
  #34  pc 0x000000000050d1cc  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+3404)
  #35  pc 0x0000000000434600  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+576)
  #36  pc 0x000000000057e378  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+900)
  #37  pc 0x00000000005f1d7c  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+160)
  #38  pc 0x00000000000c1c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #39  pc 0x00000000000ce470  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+856)
  #40  pc 0x0000000000002570  /system/bin/app_process64 (main+1304)
  #41  pc 0x000000000004b930  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100)
```

### Reproducer

https://github.com/DThalikar

**Comment by DThalikar** [comment]
We are struggling with this issue, it's critical. Please do not close.

**Comment by cortinico** [comment]
> We are struggling with this issue, it's critical. Please do not close.

Please provide a reproducer.

Also I see you're using JSC, consider switching to Hermes.
