### ISSUE TITLE
[Android] How to use offline bundle on android?

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#4668]
How to use offline bundle on android?
I didn`t see the document about use offline bundle on android.
I tried to uncomment code in build.gradle

```
project.ext.react = [
    // the name of the generated asset file containing your JS bundle
    bundleAssetName: "index.android.bundle",

    // the entry file for bundle generation
    entryFile: "index.android.js",

    // whether to bundle JS and assets in debug mode
    bundleInDebug: false,

    // whether to bundle JS and assets in release mode
    bundleInRelease: true,

    // the root of your project, i.e. where "package.json" lives
    root: "../../",

    // where to put the JS bundle asset in debug mode
    jsBundleDirDebug: "$buildDir/intermediates/assets/debug",

    // where to put the JS bundle asset in release mode
    jsBundleDirRelease: "$buildDir/intermediates/assets/release",

    // where to put drawable resources / React Native assets, e.g. the ones you use via
    // require('./image.png')), in debug mode
    resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",

    // where to put drawable resources / React Native assets, e.g. the ones you use via
    // require('./image.png')), in release mode
    resourcesDirRelease: "$buildDir/intermediates/res/merged/release",

    // by default the gradle tasks are skipped if none of the JS files or assets change; this means
    // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
    // date; if you have any other folders that you want to ignore for performance reasons (gradle
    // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
    // for example, you might want to remove it from here.
    inputExcludes: ["android/**", "ios/**"]
]
```

but it didn`t work.It still get the JS bundle from the server.Is there something I missed?

**Comment by coderlin** [comment]
use method 'recreateReactContextInBackground' in ReactInstanceManager, it can use bundle from local file

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-how-to-use-offline-bundle-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by jaynsw** [comment]
This is really pain. no answer in official document and the people don't think it is a bug in the config file

**Comment by pbojinov** [comment]
I agree, it's not very clear how to use the offline JS bundle for Android apps.

I get the build part, but now how to actually use the bundle

`react-native bundle --entry-file ./index.android.js --platform android --bundle-output android/app/src/main/assets/index.android.bundle`

**Comment by Iragne** [comment]
https://stackoverflow.com/questions/34175416/how-to-use-offline-bundle-on-android-for-react-native-project your answer 
react.gradle

change
ext.react = [
    **bundleInDebug     : true,**
    bundleInRelease   : true
]
