### ISSUE TITLE
Percentage values in Translation not working on Android (Value for translateY cannot be cast from String to double)

### ISSUE THREAD

**Issue by victorevan** [facebook/react-native#46684]
### Description

https://reactnative.dev/blog/2024/08/12/release-0.75#percentage-values-in-translation

According to the docs, percentage values can now be used on both Android and iOS. However, they actually only work on iOS. On the latest version of Android 14, you get the following crash attempting to use percentage values with translate:

![4161187218071454338](https://github.com/user-attachments/assets/97489de4-f786-44cf-94a3-12edf33483f8)

### Steps to reproduce

1. Use the recommended command from the docs: `npx @react-native-community/cli@latest init MyProject --version latest`
2. Run the project on the latest stable version of Android.
3. Set the following style on any View: `transform: [{ translateY: '100%' }]`
4. Experience the crash.

### React Native Version

0.75.3

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.0
  CPU: (16) arm64 Apple M3 Max
  Memory: 1.02 GB / 128.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.0
    path: ~/.nvm/versions/node/v20.15.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.15.0/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/victor/.gem/ruby/3.3.3/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "31"
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-35 | Google APIs ARM 64 v8a
      - android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
      - android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
      - android-VanillaIceCream | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.19072.14.2412.12360217
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.3
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Value for translateY cannot be cast from String to double
getDouble
ReadableNativeMap. kt: 204
processTransform
TransformHelper java: 157
setTransformProperty
BaseViewManager •java: 543
setTransformProperty
ReactViewManager• java: 327
setTransformProperty
ReactViewManager. java: 43
onAfterUpdateTransaction
BaseViewManager java: 629
updateProperties
ViewManager. java: 89
updateProperties
NativeViewHierarchyManager.java: 138
execute
UIViewOperationQueue.java: 94
run
UIViewOperationQueue. java: 851
flushPendingBatches
UIViewOperationQueue. java: 964
-##Nest$mflushPendingBatches
ทu11
doFrameGuarded
UIViewOperationQueue.java: 1024
doFrame
GuardedFrameCallback.kt :22
```

### Reproducer

https://github.com/victorevan/react-native-android-translate-percentage-crash-repro

### Screenshots and Videos

![4161187218071454338](https://github.com/user-attachments/assets/74a03232-05be-4075-a9d7-5ead12cf289c)
<img width="589" alt="Screenshot 2024-09-26 at 8 17 36 PM" src="https://github.com/user-attachments/assets/b067064d-1ef4-4c42-9a85-3a11d303855e">

**Comment by shubhamguptadream11** [comment]
@victorevan Based on the `npx react-native info `logs you shared, it seems you're using the old architecture. I recommend switching to the new architecture. The [documentation](https://reactnative.dev/blog/2024/08/12/release-0.75#yoga-31-and-layout-improvements) also mentions that these new Yoga changes are only available in the new architecture.

**Comment by victorevan** [comment]
How did I completely miss that? Thanks for the correction.
