### ISSUE TITLE
Generated release apk fails to run in 0.16

### ISSUE THREAD

**Issue by arunabha** [facebook/react-native#4671]
I'm having trouble running the generated apk files. This problem happens on both the emulator and physical device.

Steps to reproduce
1) Created a blank application using init.
2) Verify that the app runs using run-android
3) Genrate apk following instructions at http://facebook.github.io/react-native/docs/signed-apk-android.html#content

4) Install the app-release.apk on phone.
5) Running the app produces this output in logcat

--------- beginning of crash
--------- beginning of system
--------- beginning of main
E/ReactNative( 8863): Got JS Exception: ReferenceError: Can't find variable: require

**Comment by jforaker** [comment]
@arunabha did you try opening the developer menu (shake the device or click the hardware menu button in emulator) selecting "Debug in Chrome"?

**Comment by arunabha** [comment]
@jforaker No, I couldn't. The app shuts down immediately upon launching producing the logcat output mentioned in the original report. There is no chance to try the dev menu.

**Comment by satya164** [comment]
This most probably means that the JS bundle didn't get included. Did you upgrade from a previous version?

**Comment by satya164** [comment]
@arunabha Any updates on this?

**Comment by schinknbrot** [comment]
I have the same problem.
I tried once with my existing project that was upgraded from `0.16.0` to `0.17.0` and as this was not working and showing the same message as mentioned by @arunabha , I tried with a completely new project with `react-native init` and again, the same output was shown in the log.

**Comment by arunabha** [comment]
Yes, I upgraded from a previous version. I was able to get it working by regenerating the signing key.

**Comment by satya164** [comment]
@schinknbrot Try clearing the build directory to see if this is fixed for you.

**Comment by satya164** [comment]
@arunabha Good to know. Closing.
