### ISSUE TITLE
when dev=true, the js packager should't be ‘Whole Program Optimisations’ when js file changed

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#4672]
happened on master branch
[18:53:56] <END>   transform (553ms)
[18:53:56] <END>   transform (542ms)
[18:53:56] <START> Whole Program Optimisations
[18:54:20] <END>   Whole Program Optimisations (24066ms)
[18:54:20] <END>   request:/CustomViews/MainPageView.bundle?platform=ios&dev=true (24390ms)

**Comment by cosmith** [comment]
+1, live reload takes ~20s on my app which is a pain.

**Comment by sarriaroman** [comment]
+1 here too. Also takes too much CPU

**Comment by malinthe** [comment]
+1

**Comment by dsibiski** [comment]
Actually, this seems to happen no matter whether Dev mode is on or off. I filed a bug on ProductPains here: https://productpains.com/post/react-native/packager-whole-program-optimisations-taking-forever-on-live-reload/

Please upvote it there!

**Comment by magicismight** [comment]
+1

**Comment by skevy** [comment]
@dsibiski that link doesn't work anymore...any idea where it went?

**Comment by dsibiski** [comment]
@skevy Hmm, I don't know...weird, it's just gone. Well, I created it again here: https://productpains.com/post/react-native/packager-whole-program-optimisations-taking-forever-on-live-reload/

**Comment by AlexeyToksarov** [comment]
Working link: https://productpains.com/post/react-native/packager-whole-program-optimisations-taking-forever-on-reload/

**Comment by ide** [comment]
AFAIK the plan is to run WPO only when minify=true.  cc @tadeuzagallo

**Comment by skevy** [comment]
If anyone wants a quick fix in lieu of the update, comment this out: https://github.com/facebook/react-native/blob/57a76c0c014eacb9c138ab8faf9aaabd964e416d/packager/react-packager/src/Bundler/Bundle.js#L113-L124

Don't forget to put it back in before you bundle!

**Comment by brentvatne** [comment]
This is fixed now!
