### ISSUE TITLE
[Android] onResume() in MainActivity doesn't seem to work in v0.6.1

### ISSUE THREAD

**Issue by edcs** [facebook/react-native#4677]
The `MainActivity` class contains the following override:

```java
 @Override
 protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onResume(this);
    }
}
```

The method call `mReactInstanceManager.onResume(this)` shows an error stating that `onResume`'s first argument should be an instance of `Activity`. `this` is a `MainActivity` class but it extends `Activity` so it should work? The React Native docs on this subject are still talking about v0.13.0 so I am unable to see what needs to be changed there.

For now I have commented out this line so that the app can build, but I'd like to find out what the real solution for this should be. Is there something up with my implementation or is there an issue with React?

**Comment by Bhullnatik** [comment]
I believe the code should be
```java
 @Override
 protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onResume(this, this);
    }
}
```
=> [reference (MainActivity.java L75)](https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/package/MainActivity.java#L75).

Using `react-native upgrade` should have updated your `MainActivity.java` to the correct code, see [docs on how to upgrade](http://facebook.github.io/react-native/docs/upgrading.html#content).

**Comment by satya164** [comment]
Closing this since @Bhullnatik already answered your question (thanks @Bhullnatik ).
