### ISSUE TITLE
CocoaPods published version is a bit behind

### ISSUE THREAD

**Issue by nevir** [facebook/react-native#4682]
Latest version published to CocoaPods [appears to be `0.13-rc`](https://cocoapods.org/pods/React).  Could probably use some love :)

**Comment by ide** [comment]
We intentionally don't publish to CocoaPods since there are bugs that arise if you have react-native under Pods and node_modules. The only supported solution is to tell CocoaPods to read from node_modules which is documented here: https://facebook.github.io/react-native/docs/embedded-app-ios.html

**Comment by nevir** [comment]
Ah! Maybe it's worth yanking the CocoaPods repo entirely to reduce confusion, then?
