### ISSUE TITLE
Container folder is not a project file 0.75.4

### ISSUE THREAD

**Issue by BogdanRad** [facebook/react-native#46881]
### Description

I updated my project from 0.74.1 to 0.75.4. In ios folder I have the container folder with GTM file. When I run from terminal I have this error `xcodebuild: error: '/Users/bogdan/apps/react-native-mobile-app/ios/container' is not a project file.`
If I run from xcode the build is successful. Can you help me to fix this problem from terminal?

### Steps to reproduce

1. after update to 0.75.4
2. when I run yarn ios

### React Native Version

0.75.4

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
`System:
  OS: macOS 14.4.1
  CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
  Memory: 172.63 MB / 52.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.19.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: /usr/local/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/bogdan/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/bogdan/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false`
```

### Stacktrace or Logs

```text
`error Command failed with exit code 66: xcodebuild -list -json -project /Users/bogdan/apps/react-native-mobile-app/ios/container
2024-10-08 09:56:50.644 xcodebuild[86734:4199341] Writing error result bundle to /var/folders/r5/wpsjwhg9245cgqcjs95l5kjc0000gn/T/ResultBundle_2024-08-10_09-56-0050.xcresult
xcodebuild: error: '/Users/bogdan/apps/react-native-mobile-app/ios/container' is not a project file.
Error: Command failed with exit code 66: xcodebuild -list -json -project /Users/bogdan/apps/react-native-mobile-app/ios/container
2024-10-08 09:56:50.644 xcodebuild[86734:4199341] Writing error result bundle to /var/folders/r5/wpsjwhg9245cgqcjs95l5kjc0000gn/T/ResultBundle_2024-08-10_09-56-0050.xcresult
xcodebuild: error: '/Users/bogdan/apps/react-native-mobile-app/ios/container' is not a project file.
    at makeError (/Users/bogdan/apps/react-native-mobile-app/node_modules/execa/lib/error.js:60:11)
    at module.exports.sync (/Users/bogdan/apps/react-native-mobile-app/node_modules/execa/index.js:194:17)
    at /Users/bogdan/apps/react-native-mobile-app/node_modules/@react-native-community/cli-platform-apple/build/tools/getInfo.js:81:41
    at Array.reduce (<anonymous>)
    at getInfo (/Users/bogdan/apps/react-native-mobile-app/node_modules/@react-native-community/cli-platform-apple/build/tools/getInfo.js:74:15)
    at getConfiguration (/Users/bogdan/apps/react-native-mobile-app/node_modules/@react-native-community/cli-platform-apple/build/commands/buildCommand/getConfiguration.js:36:37)
    at Object.func (/Users/bogdan/apps/react-native-mobile-app/node_modules/@react-native-community/cli-platform-apple/build/commands/runCommand/createRun.js:113:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/Users/bogdan/apps/react-native-mobile-app/node_modules/@react-native-community/cli/build/index.js:118:9)
error Command failed with exit code 1.`
```

### Reproducer

is private

### Screenshots and Videos

<img width="906" alt="image" src="https://github.com/user-attachments/assets/8fe9410e-07be-4ed6-92d6-c4ad7cc23802">

**Comment by cipolleschi** [comment]
Hi @BogdanRad, I understand that the reproducer is private, but can you try to replicate the minimal setup starting from this [template](https://github.com/react-native-community/reproducer-react-native)? Otherwise it would be quite hard for us to help you.

In 0.75 we introduced some changes in the CLI, so this specific use case might got broken. cc. @blakef, @szymonrybczak and @thymikee that worked on the CLI recently.

**Comment by blakef** [comment]
I can replicate this, it's CLI bug from a feature added 4 months ago (react-native-community/cli#2415).  It's [make some assumptions](https://github.com/react-native-community/cli/blob/main/packages/cli-platform-apple/src/tools/getInfo.ts#L60-L72) about what's in the xcworkspace `contents.xcworkspacedata` XML file.  If I start adding other files via the Xcode project navigator:
![CleanShot 2024-10-08 at 11 55 19@2x](https://github.com/user-attachments/assets/afb145f6-aa8b-448b-9f2b-b91e0d1ef6c3)

It blows up:
![CleanShot 2024-10-08 at 12 00 05@2x](https://github.com/user-attachments/assets/287093c5-31b5-42ba-a664-4337ceb56490)

We could make this a little more robust in the CLI:
![CleanShot 2024-10-08 at 11 56 59@2x](https://github.com/user-attachments/assets/384ba708-399e-420f-986c-f68a437f12ec)

@cipolleschi I think @BogdanRad is unblocked as he can build with Xcode, but I'll add some tests and try get a fix out on the CLI.

**Comment by blakef** [comment]
I'm going to close this as it isn't a React Native bug.  Please track the progress on react-native-community/cli#2522.
