### ISSUE TITLE
React Native Library .so files are not stack canary protected and the binary does not have any fortified functions

### ISSUE THREAD

**Issue by muralitharana** [facebook/react-native#46880]
### Description

Reason for creating this issue: 

**Existing issues are closed related to this**
1. [https://github.com/facebook/react-native/issues/36870](36870) 
2. [https://github.com/facebook/react-native/issues/46537](46537)

Continuation of issue: 46537
Tool used to analysis: MobSF

Tried with 0.76.0-rc.1, Still I can see on these files, binary does not have a stack canary value and not have any fortified functions. 
1. armeabiv7a/libc++_shared.so
2. arm64-v8a/libc++_shared.so
3. armeabiv7a/libc++_shared.so
4. x86/libc++_shared.so
5. x86_64/libc++_shared.so

### Steps to reproduce

1. create a fresh react native project using 0.76.0-rc.1
2. create a release build
3. static analysis of apk using MobSF 

### React Native Version

0.76.0-rc.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 189.58 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.0
    path: ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v16.14.0/bin/yarn
  npm:
    version: 9.8.1
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2022.10.10.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "21"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 34.0.0
      - 35.0.0
    System Images:
      - android-30 | Google APIs ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-32 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0-rc.1
    wanted: 0.76.0-rc.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
No logs ---
```

### Reproducer

https://github.com/MobSF/Mobile-Security-Framework-MobSF

### Screenshots and Videos

![Screenshot 2024-10-08 at 12 00 20 PM](https://github.com/user-attachments/assets/b360d6ae-0c91-4302-8217-7d84b355af7f)

**Comment by cortinico** [comment]
> Tried with 0.76.0-rc.1, Still I can see on these files, binary does not have a stack canary value and not have any fortified functions.
> 
> 1. armeabiv7a/libc++_shared.so
> 2. arm64-v8a/libc++_shared.so
> 3. armeabiv7a/libc++_shared.so
> 4. x86/libc++_shared.so
> 5. x86_64/libc++_shared.so

We don't produce those files. They are the C++ standard library. So you should open this issue against the Android NDK https://github.com/android/ndk/issues

**Comment by muralitharanaspritle** [comment]
Thanks for the information @cortinico
