### ISSUE TITLE
Missing cherypick of #46656 for 0.76.0-rc.4

### ISSUE THREAD

**Issue by usta** [facebook/react-native#46909]
### Description

https://github.com/facebook/react-native/pull/46656 is missing in [0.76.0-rc.4](https://github.com/facebook/react-native/releases/tag/v0.76.0-rc.4) branch

### Steps to reproduce

You can observe this on v0.76.0-* branches

### React Native Version

v0.76.0

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
.
```

### Stacktrace or Logs

```text
.
```

### Reproducer

.

**Comment by cortinico** [comment]
That is missing because the pick was never requested on https://github.com/reactwg/react-native-releases/

If you wish to have it picked, please open a pick request there

**Comment by usta** [comment]
> That is missing because the pick was never requested on https://github.com/reactwg/react-native-releases/
> 
> If you wish to have it picked, please open a pick request there

Thanks :heart:  , request added to related page
