### ISSUE TITLE
How to detect timezone?

### ISSUE THREAD

**Issue by coderdave** [facebook/react-native#4691]
Is there a way to easily detect the timezone? I need to store it in the DB.

**Comment by calvinf** [comment]
You may want to look through the source code if you can't find references in the docs: 
https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=timeZone

Specifically, look at the DatePicker example:
https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Examples/UIExplorer/DatePickerIOSExample.js

**Comment by coderdave** [comment]
I see that it's getting the timezone *offset*, but not the timezone itself... unless I'm missing something.

I'm thinking about using `geolocation.getCurrentPosition()` to get the latitude and longitude and then feeding that to my API that can then lookup the timezone based on that information.

Closing, since this isn't really a bug.
