### ISSUE TITLE
flexDirection: 'row' causing Text elements to drop characters in some pixel densities

### ISSUE THREAD

**Issue by DanielHoffmann** [facebook/react-native#4693]
In my app I have been having problems which I traced down to styling a View with flexDirection: 'row'.

Here is the code in which I managed to isolate the problem:
```javascript
'use strict';

let React = require('react-native');
let {
    AppRegistry,
    Text,
    View,
    PixelRatio,
    Dimensions,
} = React;



let Test = React.createClass({
    render() {
        return (
            <View>
                <Text>Texts with flexDirection: 'row':</Text>
                <View style={{flexDirection: 'row'}}>
                    <Text>1234567890-1234567890</Text>
                    <Text>a</Text>
                    <Text>bc</Text>
                    <Text>defg</Text>
                    <Text>hijkl</Text>
                    <Text>mnopqr</Text>
                </View>
                <Text></Text>
                <Text>Same texts without flexDirection: 'row':</Text>
                <Text>1234567890-1234567890</Text>
                <Text>a</Text>
                <Text>ab</Text>
                <Text>abc</Text>
                <Text>abcd</Text>
                <Text>abcdef</Text>
                <Text></Text>
                <Text>Device properties:</Text>
                <Text>PixelRatio: {PixelRatio.get()}</Text>
                <Text>Dimensions width: {Dimensions.get('window').width}</Text>
                <Text>Dimensions height: {Dimensions.get('window').height}</Text>
            </View>
        );
    }
});

AppRegistry.registerComponent('Test', () => Test);
```

Here is a screenshot from Genymotion emulator (Android 5.1), nothing wrong here:

![image](https://cloud.githubusercontent.com/assets/2980150/11706461/2700eb40-9ee0-11e5-9730-b5511a0fbbb8.png)

Here is a screenshot from my personal phone (Moto G with Androind 5.1.1):

![image](https://cloud.githubusercontent.com/assets/2980150/11706455/11712574-9ee0-11e5-87ca-2029e278d6b2.png)

Notice the Text elements that are inside the View with `flexDirection: 'row'` are missing a few characters each and a space mystoursly appeared at the end of a few of the Texts

<Text>1234567890-1234567890</Text> -> missing 7890, a space appeared at the end
<Text>a</Text> -> nothing is missing
<Text>bc</Text> -> missing c, a space appeared at the end
<Text>defg</Text> -> missing g, a space appeared at the end
<Text>hijkl</Text>  -> missing l, a space appeared at the end
<Text>mnopqr</Text> -> missing qr

My phone has a 4.7″ diagonal HD 1280×720 (316 ppi) screen according to wikipedia
At the end of the screenshots you will find information about the device screen. Since my phone runs cyanogen I can change the pixel density of the device, I got the same problem in these following configurations:

Cyanogen LCD density option: 240 DPI
PixelRatio: 1.5
width: 480,
height: 805.333333333334

Cyanogen LCD density option: 280 DPI
PixelRatio: 1.75
width: 411.42857142857144
height: 683.4285714285714

Cyanogen LCD density option: 300 DPI
PixelRatio: 1.875
width: 384
height: 634.6666666666

Cyanogen LCD density option: 320 DPI
PixelRatio: 2
width: 360
height: 592

Cyanogen LCD density option: 340 DPI (same as screenshot)
PixelRatio: 2.125
width: 338.8235294117647
height: 554.352941164706

Cyanogen LCD density option: DPI
PixelRatio: 2.25
width: 320
height: 520.888888888889

In these following configurations the problem did not manifest:

Cyanogen LCD density option: 260 DPI (second smallest that is supported)
PixelRatio: 1.625
width: 443.0769230769231,
height: 739.6923076923077

Moto X emulated on Genymotion (1280x720 resolution):
PixelRatio: 2
width: 360
height: 592

There is definitely something wrong in Android at least. It is strange that one of the densities is not giving the problem while another is giving on my phone, but not on the emulator
React Version 0.16.

**Comment by DanielHoffmann** [comment]
My much more complex application is also working fine on 260 DPI, but in all others all the texts are dropping characters at the end (all texts are deeply nested into Views, with at least one having `flexDirection: 'row'`.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/flexdirection-row-causing-text-elements-to-drop-characters-in-some-pixel-densities

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
