### ISSUE TITLE
CDP Runtime.evaluate does not drain async tasks 

### ISSUE THREAD

**Issue by EmielM** [facebook/react-native#46966]
## Bug Description

I'm trying to run some automated testing scripts through the Hermes CDP interface using [Runtime.evaluate](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate).

First off, the `awaitPromises` flag does not seem to be supported at all. There are some work-arounds to this, so that's fine.

A bigger issue seems to be that after `Runtime.evaluate`, planned Promise tasks are not executed. What I see is usually after a second or 5-10, the queue is triggered and drained again. (I also tried to workaround this by running `HermesInternal.drainJobs` after every command, but [this is unexposed](https://github.com/facebook/hermes/blob/add4115869df5b78914fab0ca15d71ab958e8588/lib/VM/JSLib/HermesInternal.cpp#L815) without hermes-internal-test-methods flag see; I didn't manage to enable that flag in an otherwise vanilla RN project either.)

Tried to create a simple case to replicate, but the overall setup is pretty involving.

**Comment by hoxyq** [comment]
Thanks for reporting this!

> A bigger issue seems to be that after Runtime.evaluate, planned Promise tasks are not executed.

We are aware of this issue and planning to fix this on React Native side. I will share more details once we have confirmed the timeline for it.
