### ISSUE TITLE
[TextInput] [android] onChange report error

### ISSUE THREAD

**Issue by liusong1111** [facebook/react-native#4698]
Once I input a character on the TextInput, it reports:

```
undefined is not an object(evaluating 'this.refs.input.setNativeProps')

_onChange
TextInput.js:567
```

Env: react-native 0.16.0, android
in TextInput.js, this.refs.input got undefined.

Please check it, thanks.

**Comment by gre** [comment]
are you sure you have restarted the packager running 0.16? because it seems to be correctly set https://github.com/facebook/react-native/blob/0.16-stable/Libraries/Components/TextInput/TextInput.js#L516

**Comment by liusong1111** [comment]
Sorry my fault.
After restart the packager, it becomes ok.

Please close this issue.
