### ISSUE TITLE
[Modal] How to manipulate Modal component directly?

### ISSUE THREAD

**Issue by just4fun** [facebook/react-native#4701]
I have noticed that `NativeMethodsMixin is not available on composite components that aren't directly backed by a native view`.

However, I used Redux in my case, when I wanna open a Modal, I don't want to send an action to store for changing a state field such as `isModalOpen` and then re-render the whole app (pass new state down).

So is there any approach to manipulate Modal directly instead of maintaining a state for it?

**Comment by qbig** [comment]
@just4fun I encounter similar situation and I just make sure that shouldComponentUpdate do some basic check, so that changing 'isModalOpen' would not trigger a complete re-render (shouldComponentUpdate return false mostly).

**Comment by just4fun** [comment]
@qbig thanks, I know what you mean, but what I concerned is not performance.

My concern is that if I maintain a state, I also have to add a reducer file, an action file, even some action type constants since I used Redux. Absolutely that's the Redux way (or unidirectional flow), but it's more fuss, I just want to open a Modal, not request endpoint.

**Comment by just4fun** [comment]
@qbig I think the best approach is using `this.state` for Modal component, because `isModalOpen` is UI related state, it should be local, and the state which reducer produced is global.

This issue could be closed.
