### ISSUE TITLE
The jsbundle file is  javascript  code? I want to know how the oc code excute the js code?

### ISSUE THREAD

**Issue by lvming6816077** [facebook/react-native#4703]
what is the relationship between js and oc?

**Comment by qbig** [comment]
@lvming6816077 You can take a look at http://tadeuzagallo.com/blog/react-native-bridge/ . OC code do NOT execute js code. RN iOS using 'JavaScriptCore'(if I am not wrong http://nshipster.com/javascriptcore/)  to run js code. So overall more like JS <---‘bridge' ---> OC.    

On a side note, this type of question might be a better fit for Stackoverflow, and more people would benefit from the answer as well, as mentioned by the fb bot :)
