### ISSUE TITLE
[Android] Image loading events & styles

### ISSUE THREAD

**Issue by Thomas101** [facebook/react-native#4704]
Hey

I've found that the `onLoad`, `onLoadEnd` and `onLoadStart` events aren't fired on the image in android. I'm guessing the docs need updating on this.

Also I've found that on Android the `resizeMode` style gets passed to the children of an image resulting in a warning... e.g.

```
<Image style={{resizeMode:'cover'}}>
   <Text>Loading</Text>
</Image>
```

**Comment by Kuzmin** [comment]
For what it's worth, these are actually properly labeled with the `@platform: ios` tag in the source code, but it seems that the documentation has not been re-generated since those labels were added.

So, a re-generation of the documentation should fix this.

**Comment by brentvatne** [comment]
@Thomas101 - `onLoadStart`, `onLoad` and `onLoadEnd` all fire on Android for network images, see: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ImageExample.js#L51-L53

Created #5085 for the resizeMode issue! Thanks :)

**Comment by cbjs** [comment]
onLoad not firing on 0.43 & 0.44
