### ISSUE TITLE
Text with adjustFontSizeToFit and numberOfLine equal to 1 leads to text being cut off or having extra width

### ISSUE THREAD

**Issue by itsramiel** [facebook/react-native#47045]
### Description

I have a row of the 3 items. Each item contains two texts. I want that the left text shrinks in size if needed, so I have set `flexShrink: 1`, adjustFontSizeToFit, and `numberOfLines={1}`. While it works for some, it breaks for others in two ways:

1. The text is for some reason cut off 
Android: <img width="392" alt="Screenshot 2024-10-16 at 9 32 53 AM" src="https://github.com/user-attachments/assets/7e7670a6-b75c-4378-a80b-b3925462a767">
iOS: <img width="372" alt="Screenshot 2024-10-16 at 9 33 51 AM" src="https://github.com/user-attachments/assets/6dc39752-5947-4eea-9861-f2eb13d98049">

2. The text is taking more space than needed:
Android: <img width="397" alt="Screenshot 2024-10-16 at 9 34 44 AM" src="https://github.com/user-attachments/assets/ae89f0b6-1acc-4d7f-92bc-0396218a775c">
iOS: doesnt seem to happen here

### Steps to reproduce

1. Clone the repo
2. Run the app on iOS/Android

### React Native Version

0.75.4

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (14) arm64 Apple M3 Max
  Memory: 98.53 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/itsramiel/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/itsramiel/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```
```


### Stacktrace or Logs

```text
No Crash or failure
```

### Reproducer

https://github.com/itsramiel/SingleLineText

### Screenshots and Videos

| **iOS** | **Android** |
| ---------- | --------- |
| <video src="https://github.com/user-attachments/assets/f99869e4-fe4f-4b6b-b379-e5cb83eb073b"></video> | <video src="https://github.com/user-attachments/assets/050f3d4a-30a2-404e-a34f-e0f94498d2f3"></video> |

**Comment by cortinico** [comment]
@itsramiel is this happening also on New Architecture?

@coado @j-piasecki do you have any context on this one?

**Comment by j-piasecki** [comment]
This is an interesting one. The code for scaling down the font size when `adjustsFontSizeToFit` effectively doesn't run for single-character text. On Android it relies on line breaks to check whether the text doesn't fit in the container and single character cannot be broken. On iOS it relies on `truncatedGlyphRangeInLineFragmentForGlyphAtIndex` which seems to always return `NSNotFound` when the string has only one character.

**Comment by itsramiel** [comment]
@j-piasecki  Interesting finding. That is consistent with the seen effect, where it only happens to single character in the screenshots above.

Do you have a fix in mind, is it easy to implement?

**Comment by j-piasecki** [comment]
@itsramiel I'm not sure whether it's the perfect solution, but I've opened a PR which is fixing the problem in the repro you've provided. Could you verify that it works for you?

**Comment by cortinico** [comment]
> I am not sure what the easiest way to test it, but I copied your changes to my react-native files in my node_modules. iOS worked but Android didnt.

Android doesn't work with patch package unless you enable build from source:
https://reactnative.dev/contributing/how-to-build-from-source

**Comment by itsramiel** [comment]
> I am not sure what the easiest way to test it, but I copied your changes to my react-native files in my node_modules. iOS worked but Android didnt.
> 
> Android doesn't work with patch package unless you enable build from source: [reactnative.dev/contributing/how-to-build-from-source](https://reactnative.dev/contributing/how-to-build-from-source)

Thank you, now able to test!

> @itsramiel I'm not sure whether it's the perfect solution, but I've opened a PR which is fixing the problem in the repro you've provided. Could you verify that it works for you?

Tested and seems to work!! Maybe add some reviewers to collect feedback?

**Comment by cortinico** [comment]
We're discussing the PR internally and we'll get back to you whenever we can (please note that this week we might be slower to respond and do reviews than usual)

**Comment by YasinAkimura** [comment]
I had a similar issue using this on react native 0.76.1 using iOS it's caused a little bit differently by a setting the lineHeight bigger then the original fontSize: result it completely glitches out per render cycle either by a too small font or sometimes back to normal. 
In my case it was easily fixed by tweaking the lineHeight or removing it but that did not happen in the old arch using 0.75

**Comment by rastapasta** [comment]
@YasinAkimura Thanks.

Running into same issue on 0.76.3 (iOS **and** Android), removing the lineHeight also helped in my case and on both platforms. My texts got miniturized as soon as an adjust was neccesary.
