### ISSUE TITLE
Add validation of CSS colors

### ISSUE THREAD

**Issue by ExplodingCabbage** [facebook/react-native#4708]
Most supported CSS properties already have some kind of validation implemented. For instance, 

```js
React.StyleSheet.create({
  thing: {
    position: 'monkey',
  },
});
```

yields an error:

> Error: Invariant Violation: Invalid prop `position` of value `monkey` supplied to `StyleSheet header`, expected one of ["absolute","relative"].

However, CSS colors currently have no validation. This doesn't error out, it just produces a white background:

```js
React.StyleSheet.create({
  thing: {
    backgroundColor: 'monkey',
  },
});
```

Such validation should be added to aid debugging when a developer typos a color.

**Comment by shtefanntz** [comment]
I'll have a pull request in a few hours for this. 
I would need some details whether colors like "#ABC" are valid values for react-native.
Also, can anyone confirm if this is list is supported by react-native? 
http://www.w3schools.com/cssref/css_colornames.asp

Thanks!

**Comment by satya164** [comment]
@shtefanntz hex, rgb and rgba colors are supported. not sure about others.

One quick way to verify the supported named colors will be to create a small React component on http://rnplay.org

**Comment by christopherdro** [comment]
@shtefanntz Take a look at [processColor](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/processColor.js).

**Comment by shtefanntz** [comment]
Thanks for the tip, @christopherdro . I was going to reimplement some of the code from there :)

@satya164, forgot about this site. Thanks!
