### ISSUE TITLE
Unable to create react native project as aar

### ISSUE THREAD

**Issue by supriyamalusare** [facebook/react-native#47111]
### Description

We are trying to create our React native project as library.
But we are receiving errors as "Failed to resolve: com.facebook.react:react-native:+" , if we apply like apply plugin: 'com.android.library'.
If we are using like apply plugin: 'com.android.application', then project is able to create apk.

.aar file is not generating due to this issue.

This is happening for all the external react native plugins that we have used in our project.

### Steps to reproduce

1. npm i
2. cd android
3. Change com.android.application with apply plugin like com.android.library in app/build.gradle.
4. Remove applicationId from defaultConfig block.
5. Remove the applicationVariants block and replace it with libraryVariants.
6. ./gradlew clean
7. ./gradlew assembleRelease

### React Native Version

0.71.4

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 71.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: Not Found
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    Watchman: 2024.09.30.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 15.0/15A5229m - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
Failed to resolve: com.facebook.react:react-native:+
Show in Project Structure dialog
Affected Modules: app, react-native-async-storage_async-storage, react-native-background-timer, react-native-community_datetimepicker, react-native-community_geolocation, react-native-community_masked-view, react-native-community_netinfo, react-native-community_progress-bar-android, react-native-contacts, react-native-device-info, react-native-file-viewer, react-native-firebase_app, react-native-firebase_crashlytics, react-native-firebase_messaging, react-native-fs, react-native-geolocation-service, react-native-image-crop-picker, react-native-inappbrowser-reborn, react-native-maps, react-native-permissions, react-native-push-notification, react-native-safe-area-context, react-native-screens, react-native-splash-screen, react-native-system-setting, react-native-vector-icons, react-native-version-check, react-native-webview, sp-react-native-in-app-updates
```

### Reproducer

NA

**Comment by cortinico** [comment]
> We are trying to create our React native project as library.
> But we are receiving errors as "Failed to resolve: com.facebook.react:react-native:+" , if we apply like apply plugin: 'com.android.library'.

You will then have to specify a version manually, like:

```kotlin
implementation("com.facebook.react:react-native:0.75.3")
```

We don't support distributing libraries as `.aar` at the moment so you'll have to figure out how to do it by yourself.

Also there are a number of other things to consider such as bundling your code.
Moreover, your `.aar` library will break if you try to use it as part of another application which also uses React Native.
