### ISSUE TITLE
Framework 'CoreModules' not found in Xcode 16.0 after making Podfile changes to support Firebase SDK

### ISSUE THREAD

**Issue by imann24** [facebook/react-native#47123]
### Description

Xcode 16.0 fails to build for the iOS simulator given the following project: https://github.com/imann24/firebase-react-native-build-issues-repro

### Steps to reproduce

1. Clone this project: https://github.com/imann24/firebase-react-native-build-issues-repro
1. `npm install`
1. `cd ios`
1. `pod install`
1. Open Xcode
1. Try to build for an iOS 18.0 simulator
1. Observe failure

### React Native Version

0.75.4

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 15.0.1
  CPU: (8) arm64 Apple M1
  Memory: 101.78 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/isaiah/.rvm/gems/ruby-2.6.10/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_275
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/isaiah/.rvm/rubies/ruby-2.6.10/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Framework 'CoreModules' not found
```

### Reproducer

https://github.com/imann24/firebase-react-native-build-issues-repro

### Screenshots and Videos

<img width="919" alt="image" src="https://github.com/user-attachments/assets/69ec627f-1bf9-467c-9a22-fd7d20e73235">

**Comment by cortinico** [comment]
Have you reported this to 
https://github.com/invertase/react-native-firebase/issues

?

Please report it there first and get back to use if they point the issue as a problem with React Native core

**Comment by iMonk777** [comment]
Hi @imann24, Did you find any solution for your issue? I have the same problem after Apple forced me to upgrade to Xcode 16, and then I had to upgrade RN from 0.74.5, to 0.79.1 
I can't find any reference for this issue in the firebase package

**Comment by myzkyy** [comment]
You may need to manually add AppDelegate.swift if it doesn't appear in Xcode.
Otherwise, Xcode won't be able to find the entry point, and you may encounter errors such as `Framework 'CoreModules' not found` or `Undefined symbol: _main`.
