### ISSUE TITLE
 Reporting a Bug to React Native

### ISSUE THREAD

**Issue by NyLaurent** [facebook/react-native#47155]
### Description

The app crashes when the user clicks the button on the Home screen. The crash occurs without any warning, making it difficult to understand the root cause.

### Steps to reproduce

Install the application with yarn android.
Click on the button on the Home screen.
Notice the crash.

### React Native Version

0.73.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 417.81 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node: 18.14.0
  Yarn: 1.22.19
  npm: 9.5.0
  Watchman: 2023.03.13.00
  Xcode: 14.3.1
  Android Studio: 2022.2
  Java: 17.0.3
```

### Stacktrace or Logs

```text
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfabricjni.so caused by: com.facebook.react.fabric.StateWrapperImpl result: 0
    at com.facebook.soloader.SoLoader.g(Unknown Source:341)
    at com.facebook.soloader.SoLoader.t(Unknown Source:124)
    at com.facebook.soloader.SoLoader.s(Unknown Source:2)
    at com.facebook.soloader.SoLoader.q(Unknown Source:42)
    at com.facebook.soloader.SoLoader.p(Unknown Source:1)
```

### Reproducer

import React from 'react'; import { View, Button, Alert } from 'react-native';  const App = () => {   const handleButtonClick = () => {     Alert.alert("Button Clicked!");   };    return (     <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>       <Button title="Click Me" onPress={handleButtonClick} />     </View>   ); };  export default App;

**Comment by migueldaipre** [comment]
@NyLaurent Can you share a reproducer? If possible try to use the latest stable version or v0.76

**Comment by cortinico** [comment]
As @migueldaipre mentioned, we can't help you without a reproducer.

> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfabricjni.so

Also this crash happens when your application doesn't have a dynamic library (`libfabricjni.so` in this case). This happens either because your build is misconfigured, or because you're manipulating the final APK.

You can find plenty of similar resolved issues in the issue tracker
