### ISSUE TITLE
Unable to create a build and deploy visionOS app to TestFlight.

### ISSUE THREAD

**Issue by codingslash76** [facebook/react-native#47174]
### Description

Unable to create a build and deploy visionOS app to TestFlight.

After changing the build settings to set the Base SDK to 'visionOS' under Architectures, I encountered multiple errors stating 'Module Map file not found', as shown in the screenshots. It works fine on iOS devices.

### Steps to reproduce

1. Go to your build settings and under Architectures, set Base SDK to 'visionOS'. Then you will see the Destination 'Any visionOS Device (arm64)' in Xcode.
2. Create build -> Build Failure

### React Native Version

0.75.2

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 136.09 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.5.1
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.07.15.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2411.12169540
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
Module Map file not found
Command SwiftGeneratePch emitted errors but did not return a non zero exit code to indicate failure.
```

### Reproducer

https://github.com

### Screenshots and Videos

![Screenshot 2024-10-23 at 7 12 40 PM](https://github.com/user-attachments/assets/1896ede8-a1a8-4249-b0d9-db7134a97300)
![Screenshot 2024-10-23 at 7 13 20 PM](https://github.com/user-attachments/assets/42fdbdb6-84bf-486c-a91c-f13cbfc16a8f)
![Screenshot 2024-10-23 at 7 14 03 PM](https://github.com/user-attachments/assets/a663e3e1-e29c-4725-9a01-ae2a372e0211)
![Screenshot 2024-10-23 at 7 14 52 PM](https://github.com/user-attachments/assets/85a11302-4063-4aa8-b798-a972d62e9b21)

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/callstack/react-native-visionos/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
