### ISSUE TITLE
Problems with iOS "Integrating with Existing Apps" documentation

### ISSUE THREAD

**Issue by DougBanksPersonal** [facebook/react-native#4717]
Working through:

https://facebook.github.io/react-native/docs/embedded-app-ios.html#content

hitting a few issues.

Some background on me: not familiar with node, nvm, etc.  Some experience with iOS/Cocoapods.  No experience with React.

1. The instruction "Install your copy of React Native under your node_modules directory where your JS resides." is confusing.

It isn't explained anywhere how to do this.  

In "Getting started", the react-native package is installed as a side effect of running:
```
react-native init AwesomeProject
```
but there's no instructions, that I could find, about how to install just the package in an existing project.

This is made more confusing by the overloading of 'react-native'.  It is both a command-line tool and a package name.  You do provide directions on installing the command-line-tool, but nothing for installing the package.

Finally figured this out with some help: 
```
npm install react-native
```
I still am not clear where I should run this command: If my directory structure is 
```
project_parent_dir
    project_dir
        myproject.xcworkspace
        myproject.xcodeproj
        directory_with_my_custom_react_js
        other_directories_which_may_contain_js
        Podfile
        Pods
```
should I be running this command in project_parent_dir, parent_dir, directory_with_my_custom_react_js, somewhere else?

2. "Pods/React" is never created.
When following instructions to start the server:
```
(JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)
```
the 'cd Pods/React' command always fails because Pods/React is not created.  The 'pod install' command succeeds, with output indicating React was installed:
```
$ pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `React` from `./node_modules/react-native`
Downloading dependencies
Using AFNetworking (2.6.0)
Using Alamofire (3.0.1)
Using EGOCache (2.1.3)
Using FPPicker (5.0.1)
Using FSImageViewer (3.4)
Using Fabric (1.6.1)
Using Kanna (1.0.3)
Using Kingfisher (1.6.1)
Using MBProgressHUD (0.9.1)
Using PSPDFTextView (1.2.0)
Installing React 0.14.2 (was 0.14.2)
Using SVWebViewController (1.0)
Using SwiftValidator (3.0.0)
Using SwiftyJSON (2.3.2)
Using UAProgressView (0.1.2)
Generating Pods project
Integrating client project
Sending stats
lsPod installation complete! There are 23 dependencies from the Podfile and 15 total pods installed.
```

3. The server is always trying to find js from more than one root directory.
The command
```
(JS_DIR=`pwd`/ReactComponents; cd Pods/React; npm run start -- --root $JS_DIR)
```
would suggest that I am telling the server to look for js under 'ReactComponents'.

Instead, as part of the server starting, I see the following spew:
```
Looking for JS files in
   /Users/douglasbanks/zeemeesrc/zeemee-ios/ZeeMeeApp
   /Users/douglasbanks/zeemeesrc/zeemee-ios/ZeeMeeApp/ReactComponents 
```

I can't seem to get rid of that first line no matter what I do.  It seems to always include the parent of 'node_modules/react-native'.

I suppose I could make sure that I install node_modules/react-native in my ReactComponents directory, or off to the side somewhere so that it's not picking up duplicate/unintended js files.  If that really is the case (like it's always going to include that parent directory), the documentation should be very clear that where you install node_modules matters.

**Comment by skevy** [comment]
@DougBanksPersonal thanks for reporting.

Docs are definitely something that need work across RN, and I appreciate you being so detailed in your issue. 

After some debugging, where did you end up? I saw on #4735 that you may have gotten somewhere...would you be willing to put those learnings in a PR that could get merged into the docs? I'd be happy to help review!

**Comment by DougBanksPersonal** [comment]
For what it's worth, already logged all my learnings here:
http://zeemeeeng.blogspot.com/

I would be happy to help edit your docs, but I don't understand how.

PR = pull request?  From git?
If so, where on git would I find this doc:
https://facebook.github.io/react-native/docs/embedded-app-ios.html#content

Thanks
Doug

**Comment by Crash--** [comment]
You will find the doc to edit here : https://github.com/facebook/react-native/blob/master/docs/EmbeddedAppIOS.md

**Comment by DougBanksPersonal** [comment]
New PR with edits:

https://github.com/facebook/react-native/pull/4828

Thanks for your help with this.

Doug

**Comment by skevy** [comment]
Closing as #4828 is merged. :-)

**Comment by rclai** [comment]
Guys I'm having trouble setting this up, or rather, having trouble knowing whether I set it up correctly.

I was trying to replicate a regular `react-native init myApp` folder structure so I did:

```
-- myRootFolder
  -- ios (this has the existing iOS I want to integrate RN with)
    -- Podfile
  -- android (nothing here yet, but I will eventually have an existing Android app to integrate with RN)
  -- app (where all my RN js code is)
  -- node_modules
    -- react-native
```

My Podfile looks like this:

```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  'RCTActionSheet',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTPushNotification',
  'RCTVibration',
  'RCTLinkingIOS',
  'RCTTest',
  # Add any other subspecs you want to use in your project
]
```

When I ran `pod install` this was my output:

```
richard $ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Downloading dependencies
Installing React (0.17.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MyApp.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 8 dependencies from the Podfile and 1 total pod
installed.

[!] The `MyApp [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `MyApp [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

Is this right?

I noticed that in my project's `Build Phases`, I don't have all the React Native binaries (i.e. `libReact.a`) under the `Link Binary With Libraries` section. Is it supposed to have them?

**Comment by rclai** [comment]
I got it to work, however, I think the docs does also need to say you have to add `libReact.a` to the list of binaries.

**Comment by adamski** [comment]
I can't find the `libReact.a` to add the `Link Binary With Libraries` section. Where does it live? 
I'm stuck on `ld: framework not found React` 
One of my attempts was to add `React.framework` to the build and it seems to still be looking for it..

**Comment by rclai** [comment]
If you pull up the list of binaries to choose from, it should be in the Workspace folder, if not, then there might have been something wrong in the Pod installation.

**Comment by adamski** [comment]
@rclai thanks, the only thing I see is `React.framework`, is that what you mean?

**Comment by rclai** [comment]
I don't have a React.framework, I think that's implicit in Pods.

**Comment by adamski** [comment]
Ok - perhaps my installation has gone wrong somewhere… I get the same on two different projects, however both were generated in the same way. (They are JUCE C++/iOS projects)

**Comment by rclai** [comment]
Could you trace your steps?

**Comment by adamski** [comment]
* create or save iOS build from [Introjucer](http://www.juce.com/learn/introjucer) 
* run `npm install react-native` from root of project (alongside the `.jucer` file)
* create Podfile in `Builds/iOS` as per the guide
* run `pod install`
* open workspace in Xcode
* adjust `GCC_PREPROCESSOR_DEFINITIONS` to include `$(inherited)` 
* build

Example project here: https://github.com/adamski/juce-native-navigation/tree/react-native-cocoapods

**Comment by adamski** [comment]
I think there is something going on with Introjucer generated project, as I tried the whole process on a fresh new Xcode project and it builds fine. (I'm cross posting info also on SO: http://stackoverflow.com/questions/34792596/ld-framework-not-found-react)
