### ISSUE TITLE
GitHub release notes for 0.76 point to 0.75 post

### ISSUE THREAD

**Issue by johnf** [facebook/react-native#47181]
### Description

The release notes link to the 0.75 blog post

### Steps to reproduce

Visit https://github.com/facebook/react-native/releases/tag/v0.76.0 click on blog post link

### React Native Version

0.76.0

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

### Screenshots and Videos

N/A

**Comment by johnf** [comment]
@blakef FYI

**Comment by blakef** [comment]
Fixed, thank you @johnf
