### ISSUE TITLE
[0.76][Regression] Resolved $NODE_BINARY with spaces fails Xcode build

### ISSUE THREAD

**Issue by huntie** [facebook/react-native#47211]
### Description

Building a new 0.76 project on iOS from Xcode is no longer completing, for particular system Node paths.

This is due to something we've changed in our Xcode script handling (apologies that I had to stop short of fixing this during today!).

- On my system, under [fnm](https://github.com/Schniz/fnm), the result of `with-environment.sh` is `~/Library/Application\ Support/fnm/node-versions/v20.12.0/installation/bin/node` — a path which contains a space character.
    - This has come up before for other users (https://github.com/facebook/react-native/pull/21383).
- When executed as part of the Xcode build phase `[Hermes] Replace Hermes for the right configuration, if needed`, the build fails due to this space breaking the executed command.

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/f0f430aa-35bf-48d2-8869-0d384b0784c9">

| 0.75 | 0.76 |
| - | - |
| <img width="1440" alt="image" src="https://github.com/user-attachments/assets/4029e298-a645-4020-9f09-a4416ae3a651"> | <img width="861" alt="image" src="https://github.com/user-attachments/assets/aa2cbf57-494d-4afc-8384-ca27464b17e6"> |
| ✅ Builds from Xcode | ❌ Fails |

Potentially related to https://github.com/facebook/react-native/issues/32984. 

### Steps to reproduce

Init new project and build with Xcode.

```sh
npx @react-native-community/cli@latest init RN076 --version 0.76.0
cd RN076/
xed ios
```

### React Native Version

0.76.0

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 15.0.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 144.95 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.0
    path: ~/Library/Caches/fnm_multishells/36757_1729887672338/bin/node
  Yarn:
    version: 1.22.22
    path: ~/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: ~/Library/Caches/fnm_multishells/36757_1729887672338/bin/npm
  Watchman:
    version: 2024-10-21T04:02:12Z
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/huntie/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.15989.150.2411.11948838
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.8
    path: /Users/huntie/.jenv/shims/javac
  Ruby:
    version: 2.7.4
    path: /Users/huntie/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
—
```

### Reproducer

—

**Comment by cortinico** [comment]
Fixed by https://github.com/facebook/react-native/commit/eeaa3ff458a3e5c902075bb45161d6ccde31fe53

Pick request already lined up here:
- https://github.com/reactwg/react-native-releases/issues/592
