### ISSUE TITLE
DevSettingsActivity is not removed in release builds of Android

### ISSUE THREAD

**Issue by SanjayDevTech** [facebook/react-native#47223]
### Description

I am using Expo managed workflow to build apps. But I do think this issue is not related to expo alone, so putting it here.

On Debug mode we can open the dev settings page by typing "m" in the console. I have seen DevSettingsActivity added to the AndroidManifest on debug app.

But when I build the release apk (by using github actions not eas cloud, but I think both doing the same), I still seeing the DevSettingsActivity added to AndroidManifest.

I saw there is a comment https://github.com/facebook/react-native/blob/dc2000c8750f42b2f01bdad75455750814d567c6/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/AndroidManifest.xml#L5-L8 mentioned like it will be removed in release.

Currently to remove I am using a config plugin
```js
const { withAndroidManifest } = require("@expo/config-plugins")

module.exports = function androiManifestPlugin(config) {
  return withAndroidManifest(config, async config => {
    const androidManifest = config.modResults.manifest;

    const application = androidManifest["application"][0];

    application.activity = application.activity.map(
      activity => {
        if (activity.$["android:name"] !== "com.facebook.react.devsupport.DevSettingsActivity") return activity;
        activity.$["tools:node"] = "remove";
        return activity;
      }
    )

    return config
  })
}
```

### Steps to reproduce

1. Create any React Native App
2. Build it in Release mode
3. Analyse the APK using any APK analyser app found in playstore.

### React Native Version

0.74.6

### Output of `npx react-native info`

```text
System:
  OS: Windows 11 10.0.22631
  CPU: "(8) x64 AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx  "
  Memory: 2.76 GB / 13.95 GB
Binaries:
  Node:
    version: 20.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.8.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 30.0.3
      - 33.0.1
      - 34.0.0
      - 35.0.0
    Android NDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
IDEs:
  Android Studio: AI-242.21829.142.2421.12409432
  Visual Studio: Not Found
Languages:
  Java:
    version: 21.0.3
    path: C:\Program Files\Android\Android Studio\jbr\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by SanjayDevTech** [comment]
I found two PRs that does removes the DevSettingsActivity from main AndroidManifest.xml
- https://github.com/facebook/react-native/pull/37771
- https://github.com/facebook/react-native/pull/28770

But I don't know when it was changed again back.

**Comment by cortinico** [comment]
> * [](https://github.com/facebook/react-native/pull/28770)
> 
> 
> But I don't know when it was changed again back.

The manifest that you linked is not used at all. It's only used by our internal build system, but is ignored by Gradle, so is not affecting React Native Open Source.

The source of thruth is here:
https://github.com/facebook/react-native/blob/dc2000c8750f42b2f01bdad75455750814d567c6/packages/react-native/ReactAndroid/src/debug/AndroidManifest.xml#L11

As you can see that manifest file is inside `src/debug/...` so it will be considered only for debug builds.

Where do you see that the `DevSettingsActivity` is added also for release builds?

**Comment by SanjayDevTech** [comment]
I have created a repo that reproduces this https://github.com/SanjayDevTech/demo-expo-app

if you run `npx expo prebuild --clean`, and check the `android/app/src/main/AndroidManifest.xml`, you can see the DevSettingsActivity added.

**Comment by SanjayDevTech** [comment]
Just now saw the pr thanks

**Comment by cortinico** [comment]
> if you run `npx expo prebuild --clean`, and check the `android/app/src/main/AndroidManifest.xml`, you can see the DevSettingsActivity added.

Also that's a Expo related issue, you should probably open another issue on:

https://github.com/expo/expo/issues
