### ISSUE TITLE
Too many bugs to run or install on windows and not proper running in phone.

### ISSUE THREAD

**Issue by sharibtanweer** [facebook/react-native#47226]
### Description

Too many bugs to run or install on windows and not proper running in phone.
If it is a cross platform than why windows can not able to run project to ios device?
This react native should be like android and xcode features together and should contain android and ios emulator and installing steps should be easy like android studio which contain all the feature and all kind of emulator of android and ios and all dependency adding should be integrated.

### Steps to reproduce

Log cat is too long and unable to see what exactly the error is and why it need command line to run project instead it should have run and rebuilt and clean project button.

### React Native Version

0.76

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
Too many bugs to run or install on windows and not proper running in phone.
If it is a cross platform than why windows can not able to run project to ios device?
This react native should be like android and xcode features together and should contain android and ios emulator and installing steps should be easy like android studio which contain all the feature and all kind of emulator of android and ios and all dependency adding should be integrated.
```

### Stacktrace or Logs

```text
Too many bugs to run or install on windows and not proper running in phone.
If it is a cross platform than why windows can not able to run project to ios device?
This react native should be like android and xcode features together and should contain android and ios emulator and installing steps should be easy like android studio which contain all the feature and all kind of emulator of android and ios and all dependency adding should be integrated.
```

### Reproducer

https://github.com/sharibtanweer

### Screenshots and Videos

Too many bugs to run or install on windows and not proper running in phone.
If it is a cross platform than why windows can not able to run project to ios device?
This react native should be like android and xcode features together and should contain android and ios emulator and installing steps should be easy like android studio which contain all the feature and all kind of emulator of android and ios and all dependency adding should be integrated.

**Comment by cortinico** [comment]
> If it is a cross platform than why windows can not able to run project to ios device?

To briefly answer here: Xcode is not supported on Windows therefore we can't use it to build iOS apps. React Native depends on Xcode to build iOS apps so that makes it impossible for us to add support for iOS+React Native apps on Windows
