### ISSUE TITLE
Ability to initialize new react-native project with past versions of react-native

### ISSUE THREAD

**Issue by jordanell** [facebook/react-native#4723]
I am trying to create a new react native project which should utilize an older version of react-native.

The result I would like would be to do something like: `react-native init MyProject -v 0.13.2` and have the version of react-native it uses be 0.13.2 with all of the proper generated templates put into place in xCode (and android for later versions)

However, there doesn't seem to be any options with react-native-cli for initializing with old versions of react-native.

Currently there is an `upgrade` command to help install these new templates moving up versions, but no `downgrade` for the reversal of these templates.

**Comment by ide** [comment]
We don't support versions older than the very latest and master, but my recommendation would be to manually set up a project and npm install an older version of RN. To set up the templates you could go back to one of the release branches in this repo and see how the template is generated.

**Comment by skevy** [comment]
Honestly, I'm unsure why you'd _want_ to do this...keeping up with the latest version of RN as much as possible is definitely the recommended approach, given the fact that it changes as fast as it does. If you get even 3 versions behind (which can happen in just 6 weeks, if you're going by stable branches), you run the risk of having a large number of breaking changes when you upgrade.

If you have a particular use case for using an older version, you should maintain your own fork (we've done that internally at my company, and it's worked well to keep from having to upgrade constantly).

In light of the fact that we're not supporting older versions of RN, I'm going to close this issue.

**Comment by sghiassy** [comment]
I recommend we reopen this issue. There is definitely a need to init a new project with older versions of RN. One example (there are many others), is that I'm a publisher of a React-Native component. 

When developers open up issues against my GH repo and state the component doesn't work on RN version 0.XX then I need to be able to access that older version of a RN project and test within it. RN is moving very fast and components can/do break between versions. 

This example alone, makes me feel we should support resolving issue.

**Comment by niftylettuce** [comment]
Please reopen

**Comment by niftylettuce** [comment]
For temporary solution (manual way) see <http://stackoverflow.com/a/34213517>:

> If you install the version of react-native that you want in your project, you can then navigate to (project)/node_modules/react-native/local-cli. Here you will see three generator folders which enclose the exact files RN would have used to initiate a project.

**Comment by niftylettuce** [comment]
Another approach that might work, and might be easiest, perhaps we should document it, is to navigate through GitHub to the tag/release you want to use for React Native version.  Then install the CLI for that version specifically, e.g. for RN 0.17, you'd install `npm install -g react-native-cli@0.1.7` per <https://github.com/facebook/react-native/blob/0.17-stable/react-native-cli/package.json>.  And then make your new project that uses RN 0.17 with `react-native init MySadDeprecatedProjectLol`

**Comment by niftylettuce** [comment]
Actually that doesn't seem to work, it installs the latest RN version, scratch my previous comment :facepunch:

**Comment by niftylettuce** [comment]
My next best solution is to `git clone` this repository, then checkout to the branch `git checkout 0.17-stable`, then `cd react-native-cli`, edit the `index.js` to explicitly say `install react-native@0.17` (for all occurrences) and then `npm install` from inside that folder, and then run `./index.js init MyProject`, and then `mv MyProject ~/elsewhere`.

**Comment by emmby** [comment]
This seems worth re-opening

**Comment by jordanell** [comment]
As per this post on stackoverflow: http://stackoverflow.com/questions/34211131/new-react-native-project-with-old-version-of-react-native/37623531#37623531 there is now a npm package that has been started to solve this issue https://github.com/jacobbubu/rninit .

**Comment by drpancake** [comment]
It looks like this is now possible:

`react-native init --version="0.36.0" MyNewApp`

**Comment by DanielRuf** [comment]
> react-native init --version="0.36.0" MyNewApp

It seems this is not documented (at least when trying to get the options at the terminal).
