### ISSUE TITLE
iOS - Custom Component Unavailable in Javascript

### ISSUE THREAD

**Issue by m4rcoperuano** [facebook/react-native#4724]
Hello all. First, gotta say thanks for the awesome framework! I've been working with it for about a month or so and so far I'm loving it. 

Here's the issue I just had and fixed

- Created custom component called RCTImageGalleryViewManager
- Created javascript file to wrap that custom view in a react native component
- Kept getting an error saying that RCTImageGalleryViewManager didn't exist.

After many hours of trying multiple things, I decided to create a new component called RCTTesting. Swapped RCTImageGalleryViewManager for RCTTesting in javascript, and boom, it worked. So that made me think..was it the name? Could it be that "ViewManager" or some combination of the name is causing my issue? I then created RCTTestingViewManager - I got the error again! Apparently RN does not like custom components to be suffixed with ViewManager. Maybe I missed this in the documentation? Idk, but I'm glad I found out what the issue was... or did i? Am i crazy?

Thanks!

**Comment by christopherdro** [comment]
@m4rcoperuano I've actually experienced something similar in the past but can't think of what name I using for my module! :)

Closing this since it appears your were able to find a workaround.
