### ISSUE TITLE
Dimensions do not reliably update after orientation change on iPadOS in v0.76.0

### ISSUE THREAD

**Issue by mhoran** [facebook/react-native#47262]
### Description

After upgrading to 0.76.0 I found that Dimensions do not update reliably after orientation change on iPad. This seems to be the root cause of https://github.com/facebook/react-native/issues/47251. 

This was not an issue in 0.75.0 but I have not been able to trace down the breaking commit.

### Steps to reproduce

1. Install the application **on an iPad simulator** with `yarn ios`
2. Note the correct dimensions displayed
3. Change the screen orientation
4. Note dimensions do not change
5. On subsequent orientation change, sometimes dimensions do update, but not reliably
6. Note that dimensions will update if app is sent to the background

### React Native Version

0.76.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.7
  CPU: (16) arm64 Apple M3 Max
  Memory: 2.53 GB / 48.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.4
    path: /opt/homebrew/Cellar/node@18/18.20.4_1/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.7.0
    path: /opt/homebrew/Cellar/node@18/18.20.4_1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
None
```

### Reproducer

https://github.com/mhoran/stale-dimensions-repro

**Comment by mhoran** [comment]
I've traced the issue to f22a5ef4ed12a37d87d76b534770ca414ff1d015. Reverting this commit resolves the `Dimensions` issue and also fixes the `KeyboardAvoidingView` issue.

**Comment by mhoran** [comment]
Confirmed this is fixed by https://github.com/facebook/react-native/commit/e271b23fad89e1e7da2e91a8f1e5cbb295406c74 which is included in 0.76.1.

**Comment by JB712** [comment]
I observed this bug with react native 0.74.6 (just for information)

**Comment by BenLeffler** [comment]
Seeing a potential regression for this issue in 0.76.6 - came across this ticket hunting for solutions to a KeyboardAvoidingView issue which I am currently experiencing on an iPad as described in [47251](https://github.com/facebook/react-native/issues/47251))
