### ISSUE TITLE
LayoutAnimation.configureNext onAnimationDidEnd not called when animation finished

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#4727]
Master branch:
LayoutAnimation.configureNext onAnimationDidEnd not called when animation finished:

LayoutAnimation.configureNext(LayoutAnimation.create(
            500, LayoutAnimation.Types.linear, LayoutAnimation.Properties.opacity
        ), (e)=>{
            console.log("finished") // never called!
        });

**Comment by alinz** [comment]
@nowaits @skevy There is a pending PR https://github.com/facebook/react-native/issues/3106 which needs to be addressed.

**Comment by skevy** [comment]
@alinz for records sake, the PR was actually #3190. It should be merged shortly.

**Comment by alinz** [comment]
@skevy Awesome. What about Android? Android version is pretty broken on this one!

**Comment by nowaits** [comment]
i have tried the master branch, the problem seems have been solved😁
