### ISSUE TITLE
How to present model view controller?

### ISSUE THREAD

**Issue by tjwudi** [facebook/react-native#473]
When working with some apps needs **OAuth2**, we usually need to pop a model view controller. How to present model view controller in React Native? Is it supported?

**Comment by tjwudi** [comment]
This is discussed in #483, which allows us to present own view controller.

**Comment by vkurchatkin** [comment]
I'm not sure it's a good idea though. `RCTRootView`s are supposed to be independent, ideally one per app (hence root), so it would be hard to communicate between components. Also using view controller infrastructure is not really "reacty", I think it's better to implement modals in terms of React components. (I might be wrong, first day using ReactNative :-) )

**Comment by tjwudi** [comment]
@vkurchatkin "Reacty" is somehow a relative and flexible term. In the context of iOS application, modal view controller can be a very important part.

Some ideas around making it easy to communicate between components, and also keep it "Reacty", we can provide some level of encapsulation. Maybe a standalone component.

**Comment by tjwudi** [comment]
I wrote following code to implement a simple ModalViewController. When I open it using `WBModal.presentModal` in JS, the screen displayed the right view for a little while, and then turns black. Anybody know why?

**WBModal.m**

```
@import UIKit;

#import "WBModal.h"
#import "RCTBridge.h"
#import "RCTEventDispatcher.h"
#import "RCTRootView.h"

@interface WBModal()

@end

@implementation WBModal

@synthesize bridge = _bridge;

- (void)presentModalWithTitle:(NSDictionary*)options {
    RCT_EXPORT(presentModal);
    
    UIViewController *modalViewController = [[UIViewController alloc] init];
    modalViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    modalViewController.title = options[@"title"];
    
    dispatch_async(dispatch_get_main_queue(), ^{
        UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
        UIViewController *rootViewController = keyWindow.rootViewController;
        
        
        // Init RCTRootView
        NSString *urlString = [NSString stringWithFormat:@"http://localhost:8081/%@", options[@"path"]];
        NSURL *jsCodeLocation = [NSURL URLWithString:urlString];
        RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                moduleName:options[@"registerName"]
                                                        launchOptions:nil];
        
        [rootViewController setView: rootView];
        
        [rootViewController presentViewController:modalViewController animated:YES completion: nil];
    });
}

@end
```

**Comment by tjwudi** [comment]
I made a mistake here.

```
[rootViewController setView: rootView];
```

This line should be

```
[modalViewController setView: rootView];
```

And it works now.

**Comment by tjwudi** [comment]
Further thought on this. This will not break the component thinking of React. We can organize code in different ViewController as standalone app. It is fully decoupled and can absolutely be reused. :)

**Comment by tjwudi** [comment]
Closed. See #483
