### ISSUE TITLE
flexDirection: row breaks numberOfLines in nested <Text/>

### ISSUE THREAD

**Issue by doochik** [facebook/react-native#4733]
The actual result I want to get is

```
<View>
<Text>Long truncated text...</Text> <Text>Fixed string on same line</Text>
</View>
```

I tried some cases, but it seems that flex breaks Text@numberOfLines

```
// works but "Fixed" on the new line
<View style={{padding: 20}}>
    <Text numberOfLines={1}>
        1. This text is truncated This text is truncated This text is truncated
    </Text>
    <Text>Fixed</Text>
</View>

// text is not truncated, padding is ignored
<View style={{padding: 20, flexDirection: 'row'}}>
    <Text numberOfLines={1}>
        2. This text is truncated 2. This text is truncated 2. This text is truncated
    </Text>
    <Text>Fixed</Text>
</View>

// text is not truncated, padding is ignored
<View style={{padding: 20, flexDirection: 'row'}}>
    <Text numberOfLines={1} style={{flex: 1, overflow: 'hidden'}}>
        3. This text is truncated 3. This text is truncated 3. This text is truncated
    </Text>
    <Text>Fixed</Text>
</View>

// text is not truncated, padding is ignored
<View style={{padding: 20, flexDirection: 'row'}}>
    <Text numberOfLines={1} style={{flex: 1, overflow: 'hidden', minWidth: 0}}>
        4. This text is truncated 4. This text is truncated 4. This text is truncated
    </Text>
    <Text>Fixed</Text>
</View>

// text is not truncated, padding is ignored
<View style={{padding: 20, flexDirection: 'row'}}>
    <Text numberOfLines={1} style={{overflow: 'hidden'}}>
        5. This text is truncated 5. This text is truncated 5. This text is truncated
    </Text>
    <Text style={{flex: 1}}>Fixed</Text>
</View>
```

Here is my result

![2015-12-11 21-23-28 iphone 5s - iphone 5s ios 9 0 13a344](https://cloud.githubusercontent.com/assets/31961/11751893/78cf827e-a04d-11e5-92b8-43088b3a3180.png)

**Comment by hufeng** [comment]
+1

**Comment by zoontek** [comment]
+1

**Comment by pocman** [comment]
+1

**Comment by 9mm** [comment]
Have any of you guys found workarounds for this? Not sure how to go about doing this...

**Comment by mikelambert** [comment]
I had the same issue, and spent 45m+ trying to figure out why this worked: http://stackoverflow.com/questions/36284453/react-native-text-going-off-my-screen-refusing-to-wrap-what-to-do but my code did not.

Looks like my top-most Component had a style containing "alignItems: 'center'", which caused the above problem to happen for me. Have a look here: https://rnplay.org/apps/Usel7g (change the parent from fixedContainer to brokenContainer to see things break).

I still believe this represents some sort of bug in React, and should remain open. (Or at least, something that needs more thorough documentation to clarify the layout model here in this action-at-a-distance of sorts), but at least I have a workaround that works for me.

**Comment by fov42550564** [comment]
just use View wrap it,
```js
<View style={{width: screen.width}}>
    <Text>Long truncated text...</Text>
</View>
```
it work fine for me

**Comment by jzzj** [comment]
I have a very simple solution:
change this:
 `<Text numberOfLines={1} >long text....</Text>`
to:
**`<View style={{flex: 1}}>
    <Text numberOfLines={1} >long text....</Text>
</View>`**

This solved my problem.

**Comment by jzzj** [comment]
@facebook-github-bot closed.

**Comment by jzzj** [comment]
@facebook-github-bot fixed.

**Comment by oureta** [comment]
`numberOfLines` does not work on `Text` nested inside `Text`

**Comment by ericnakagawa** [comment]
Hi @doochik, are you still experiencing this issue? Seems like the suggested solution of wrapping it in a <View> is workable?

As for numberOfLines not working properly, @oureta can you put together a PR?

**Comment by oureta** [comment]
Hi @ericnakagawa, i just do JS.

**Comment by doochik** [comment]
@ericnakagawa I've tested my examples in RN 0.40. This example works as expected
```    
                <View style={{padding: 20, flexDirection: 'row'}}>
                    <Text numberOfLines={1} style={{flex: 1, overflow: 'hidden'}}>
                        3. This text is truncated 3. This text is truncated 3. This text is truncated
                    </Text>
                    <Text>Fixed text</Text>
                </View>
```

**Comment by farusy** [comment]
@doochik  it is working only for numberOfLines={1}.
 if you use a different number of lines it makes all of the shorter...
