### ISSUE TITLE
Still can't use svg images. rn 0.76

### ISSUE THREAD

**Issue by jeongeun-ezllabs** [facebook/react-native#47351]
### Description

I created a new project of version 0.76 and put the xml file in the android drawable folder.
I wrote code like <Image source={{uri:'image_name'}}/>, but the image is not visible.

### Steps to reproduce

just create project and load Image

### React Native Version

0.76.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.3
  CPU: (11) arm64 Apple M3 Pro
  Memory: 126.45 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.10.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.1
    path: /Users/shinjeongeun/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.5
    path: /Users/shinjeongeun/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0-alpha.2
    wanted: 15.0.0-alpha.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.0
    wanted: 0.76.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
no error
```

### Reproducer

.

**Comment by cortinico** [comment]
SVG support is offered via this community library:
https://github.com/software-mansion/react-native-svg

**Comment by jeongeun-ezllabs** [comment]
> SVG support is offered via this community library: https://github.com/software-mansion/react-native-svg

https://github.com/facebook/react-native/commit/aad9240fd435d549812b5075767c5ea39a8fbb4f
According to this commit,
Put the xml file in android drawable folder and 
use it like the example code(rn-tester), 
I think the image should be visible, shouldn't it?

**Comment by cortinico** [comment]
> I think the image should be visible, shouldn't it?

The commit you reference is for vector drawables, which are a different format than SVG

**Comment by jeongeun-ezllabs** [comment]
> > I think the image should be visible, shouldn't it?
> 
> The commit you reference is for vector drawables, which are a different format than SVG

@cortinico 
I converted svg to xml. I also downloaded and tested the file in ic_android.xml in rn_tester, but it is not visible.
<img width="281" alt="image" src="https://github.com/user-attachments/assets/070e50f9-cc43-4570-b252-5af49c65c5df">
<img width="756" alt="image" src="https://github.com/user-attachments/assets/951031d8-407c-4cb7-8514-b62b3ac19477">
Please tell me if there is anything wrong
