### ISSUE TITLE
Yarn Prepare failure

### ISSUE THREAD

**Issue by bmahajanZ** [facebook/react-native#47353]
### Description

Following this article to create a native module and then convert it to an npm package. Getting issues with yarn prepare command. 
https://reactnative.dev/docs/the-new-architecture/create-module-library

### Steps to reproduce

1. Create library - npx create-react-native-library@latest <Name of Your Library>
2. Using the default code that comes with the above command. 
3. Run yarn prepare. Seeing this issue 

❯ yarn prepare
ℹ Building target codegen
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Compiling 2 files in src with babel
ℹ Compiling 2 files in src with babel
ℹ Generating type definitions with tsc
ℹ Cleaning up previous iOS codegen native code at ios/generated
ℹ Cleaning up previous Android codegen native code at android/generated
✔ Wrote files to lib/commonjs
✔ Wrote files to lib/module
✔ Wrote definition files to lib/typescript
✖ 
/test-library/node_modules/react-native-builder-bob/lib/targets/codegen.js:48
    throw new Error('Failed generate the codegen files.');
          ^

Error: Failed generate the codegen files.
    at build (/test-library/node_modules/react-native-builder-bob/lib/targets/codegen.js:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildTarget (/test-library/node_modules/react-native-builder-bob/lib/index.js:421:7)

Node.js v20.11.1

### React Native Version

0.76.1

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
❯ npx react-native info

⚠️ react-native depends on @react-native-community/cli for cli commands. To fix update your package.json to include:


  "devDependencies": {
    "@react-native-community/cli": "latest",
  }




/test-library  on main +52 ?4 ──────────────────── at 15:26:23 
❯ npx @react-native-community/cli@latest info                             
info Fetching system and libraries information...
System:
  OS: macOS 14.7
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 83.04 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.06.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/bhaskarmahajan/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.3.3
    path: /Users/bhaskarmahajan/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found


 /test-library  on main +52 ?4 ────────── took 8s  at 15:27:58 
❯
```

### Stacktrace or Logs

```text
yarn prepare                               
ℹ Building target codegen
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Cleaning up previous iOS codegen native code at ios/generated
ℹ Cleaning up previous Android codegen native code at android/generated
ℹ Compiling 2 files in src with babel
ℹ Compiling 2 files in src with babel
✔ Wrote files to lib/commonjs
✔ Wrote files to lib/module
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
✖ 
/test-library/node_modules/react-native-builder-bob/lib/targets/codegen.js:48
    throw new Error('Failed generate the codegen files.');
          ^

Error: Failed generate the codegen files.
    at build (/test-library/node_modules/react-native-builder-bob/lib/targets/codegen.js:48:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildTarget (/test-library/node_modules/react-native-builder-bob/lib/index.js:421:7)

Node.js v20.11.1
```

### Reproducer

https://github.com/mbhaskar98/test-library

**Comment by cortinico** [comment]
> Following this article

Which article?

**Comment by bmahajanZ** [comment]
@cortinico https://reactnative.dev/docs/the-new-architecture/create-module-library. Updated the description.

**Comment by bmahajanZ** [comment]
Seeing same error with versions 0.76.0 and 0.76.1. 
The command works fine without any error for versions 0.75.3 and 0.75.4.

**Comment by migueldaipre** [comment]
Hey, this issue is related to the [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob) library and not with the react-native core.

Please, if you can create an issue [here](https://github.com/callstack/react-native-builder-bob/issues) and shows your spec file. I would like to help

**Comment by bmahajanZ** [comment]
@migueldaipre new bug opened - https://github.com/callstack/react-native-builder-bob/issues/676
