### ISSUE TITLE
BackAndroid removeEventListener not removing listener

### ISSUE THREAD

**Issue by golorry** [facebook/react-native#4736]
My code snipped is as below. The issue is that if I put the code below in multiple pages (n pages), the navigator will pop n times when the back button is clicked. I am not sure if this the remove listener function issue or it's meant to this this way. I will need to handle a back button action in one page specifically so would need to insert the listener to that page. Thanks a lot!

I am using RN 0.15.0 Android on Mac OS

  navigatorPop(){
    this.props.navigator.pop();
    return true;
  },
  componentDidMount(){
    BackAndroid.addEventListener('hardwareBackPress', this.navigatorPop)
  },
  componentWillUnmount(){
    BackAndroid.removeEventListener('hardwareBackPress',this.navigatorPop)
  },

**Comment by theoriginalgri** [comment]
```BackAndroid::removeEventListener``` internally uses ```delete()``` on the subscription which does not exist, ```remove()``` would be the correct function.

See https://github.com/facebook/react-native/blob/62e8ddc20561a39c3c839ab9f83c95493df117c0/Libraries/Utilities/BackAndroid.android.js#L71

**Comment by golorry** [comment]
I think I figured out the reason. I was using adding the listener to the drawer framework I use in every screen and I also added a listener to one of the children in the screen as well, so the listeners are added twice. It goes back to normal after I removed the drawer listeners.

**Comment by alvaromb** [comment]
I'm trying to remove the listener using ``BackAndroid.removeEventListener`` but it's not removing it. Are you sure you managed to remove it correctly?

**Comment by golorry** [comment]
@alvaromb Yeah, it's working fine now. See if the function was really called when it's meant to.

**Comment by alvaromb** [comment]
Never mind, a ``bind`` problem. Thanks!

**Comment by ivesy85** [comment]
@alvaromb  I think I may be having the same issue as you. How did you solve this. My code in this area is as follows.

componentDidMount() {
        console.log('mount');
        BackAndroid.addEventListener('hardwareBackPress', this.pasEditUnmountFunction.bind(this));
    }

    componentWillUnmount() {
        console.log('unMount');
        BackAndroid.removeEventListener('hardwareBackPress', this.pasEditUnmountFunction.bind(this));
    }

    pasEditUnmountFunction() {
        console.log('perform function');
        if(this.props.getSelectedTab() == 'recent') {
            this.props.mainNav.replace({id: 'recentPas'});
        }
    }

**Comment by satya164** [comment]
@ivesy85 `.bind` returns a new function. So the function you're passing to `BackAndroid.removeEventListener` is not the same as the one you passed to `BackAndroid.addEventListener`. Try something like the following,

```js
    constructor(props) {
        this._ pasEditUnmountFunction = this._pasEditUnmountFunction.bind(this);
    }

    componentDidMount() {
        BackAndroid.addEventListener('hardwareBackPress', this._pasEditUnmountFunction);
    }

    componentWillUnmount() {
        BackAndroid.removeEventListener('hardwareBackPress', this._pasEditUnmountFunction);
    }

    _pasEditUnmountFunction() {
        if (this.props.getSelectedTab() === 'recent') {
            this.props.mainNav.replace({ id: 'recentPas' });
        }
    }
```

**Comment by pimkle** [comment]
Why remove the listener, you can just write some judgement to avoid code being executed:
  bind: function() {
    if (navigator.getCurrentRoutes().length > 1) {
      navigator.pop();
      return true;
    }
    var time = (new Date()).getTime();
    if (time - Globals.timer > 3000) {
      Globals.timer = time;
      ToastAndroid.show('Click Again to exit', ToastAndroid.SHORT);
      return true;
    }
    return false;
  },

**Comment by abhivijay96** [comment]
@GHACCT , I am facing the same issue with my application which is a UWP application which uses react-native (https://github.com/ReactWindows/react-native-windows#opening-issues)
Can you please tell me how you rectified this.

**Comment by shoumma** [comment]
@satya164 Thank you very much....have been trying to achieve it all the day

**Comment by rameshvishnoi90904** [comment]
@satya164 your Solution Worked. Thanks

**Comment by chenvan** [comment]
@satya164 Thanks! Save my time :+1:

**Comment by sarahmarciano** [comment]
@satya164 Thank you very much!!!!

**Comment by lhcshine** [comment]
@satya164  Thanks a lot!!

**Comment by rajsuvariya** [comment]
@satya164 I am using react-native-router-flux and I want confirmation popup for one screen on back press so my code is like below
``` 
               onExit={() => {
                  console.log('onExit');
                  BackHandler.removeEventListener('hardwareBackPress', () => {
                    console.log(this.props);
                    NativeModules.ActivityManager.openBottomSheet(()=>{
                      Actions.pop();
                    }, () => {
                    });
                    return true;
                  })
                }
              }
              onEnter={() => {
                console.log('onEnter');
                BackHandler.addEventListener('hardwareBackPress', () => {
                  console.log(this.props);
                  NativeModules.ActivityManager.openBottomSheet(()=>{
                    Actions.pop();
                  }, () => {
                  });
                  return true;
                })
              }}
```
But it is not removing the listner

**Comment by vongohren** [comment]
@satya164 this should go into the documentation some how. I know .bind is not react native specific, but that it returns a new function, which again makes the remove listener function not work. Is something that should be documented.

**Comment by cstehreem** [comment]
Binding the function in constructor is still not working for me. I press hardware back button and it pops out all screens. Any other solution?

**Comment by edencakir** [comment]
@cstehreem you're probably not invoking `componentWillUnmount()`, use console logs to test that case
