### ISSUE TITLE
[Android][Redbox Message] Misleading redbox message when starting app for the first time without packager running.

### ISSUE THREAD

**Issue by qbig** [facebook/react-native#4739]
<img width="828" alt="screen shot 2015-12-12 at 3 52 12 pm" src="https://cloud.githubusercontent.com/assets/5563225/11760893/823f22c4-a0e8-11e5-9bd3-54d59c87cd65.png">

The first time you run(accidentally) RN app without the packager running, the redbox would show the above message. Only after clicking 'reload' the info **below** would be shown, which is a lot more helpful?

<img width="822" alt="screen shot 2015-12-12 at 3 52 22 pm" src="https://cloud.githubusercontent.com/assets/5563225/11760891/8051025c-a0e8-11e5-8357-6b280ac7ce23.png">

I am not sure but should we use the second redbox info for both cases ?

**Comment by qbig** [comment]
```java
 private void recreateReactContextInBackgroundInner() {
    UiThreadUtil.assertOnUiThread();

    if (mUseDeveloperSupport && mJSMainModuleName != null) {
      if (mDevSupportManager.hasUpToDateJSBundleInCache()) {
        // If there is a up-to-date bundle downloaded from server, always use that
        onJSBundleLoadedFromServer();
      } else if (mJSBundleFile == null) {
        mDevSupportManager.handleReloadJS();
      } else {
        mDevSupportManager.isPackagerRunning(
            new DevServerHelper.PackagerStatusCallback() {
              @Override
              public void onPackagerStatusFetched(final boolean packagerIsRunning) {
                UiThreadUtil.runOnUiThread(
                    new Runnable() {
                      @Override
                      public void run() {
                        if (packagerIsRunning) {
                          mDevSupportManager.handleReloadJS();  
                        } else {
                          recreateReactContextInBackgroundFromBundleFile(); // <-- First time run would end up here
                        }
                      }
                    });
              }
            });
      }
      return;
    }

    recreateReactContextInBackgroundFromBundleFile();
  }
```

if **reload** is clicked, 
```
                          mDevSupportManager.handleReloadJS();  
```
would get executed and show the correct the redbox info.

Seems this is the problem ?
```
                        if (packagerIsRunning) {
                          mDevSupportManager.handleReloadJS();  
                        } else {
                          recreateReactContextInBackgroundFromBundleFile(); // <-- First time run would end up here
                        }
```
@mkonicek

**Comment by ippa** [comment]
Also, why not spell it out to new users "Please run 'react-native start' in the root of your project and make sure your device is connected"?

Maybe even mention "adb reverse tcp:8081 tcp:8081" if android is detected.. not sure about this one.

**Comment by arypurnomoz** [comment]
is there anyway to solve this problem?

**Comment by satya164** [comment]
PRs are welcome for a better error message.

**Comment by qbig** [comment]
<img width="1577" alt="screen shot 2015-12-28 at 12 14 56 am" src="https://cloud.githubusercontent.com/assets/5563225/12011003/1ac89cb2-acf8-11e5-84cd-1110fdc10977.png">

The root of the issue is that we are calling 'runJSBundle' when there isn't one. And the native cpp implementation throw back the wrong error message. Can fix this in cpp land. But I was struggling getting jni debugging working. Or alternatively, we can check the validity of the bundle before calling 'runJSBundle', which is what I tried in #4738

Any suggestions would be great @satya164 @mkonicek

**Comment by mkonicek** [comment]
Can we simply replace both error messages with the message iOS has? http://imgur.com/SFlUGsn

IMHO "Can't find variable __fbBatchedBridge" is never useful to anyone. If you can't replace it the message in C++, can you detect that exception reliably and throw one with a better message?

The "Unable to download JS bundle" message is not very good either. Replacing that with the clear message should be trivial.

Thanks so much for working on this, the cryptic message has been bothering many people for a long time.

@kmagiera, @foghina What do you think?

**Comment by kmagiera** [comment]
We used to have a better error message for this case. This looks like a regression then. But yeah, the one on iOS is even better, so let's go with that

**Comment by philikon** [comment]
As for 0.18.0rc, the `__fbBatchedBridge` error message is now also the one shown on iOS. Seems like a regression on both platforms.

**Comment by mkonicek** [comment]
Yeah this is pretty bad. Anyone up for sending a fix?

**Comment by satya164** [comment]
Not sure if this is the correct way, but here is a PR - https://github.com/facebook/react-native/pull/5235

**Comment by satya164** [comment]
@mkonicek Can you cc someone who has more context on this?

**Comment by foghina** [comment]
Is this still happening on 0.18?

**Comment by satya164** [comment]
@foghina Yes, happens on master!

**Comment by jsierles** [comment]
Just wanted to chime in here. #5235 improved the message related to the packager not running. However, the `__fbBatchedBridge` error still pops up in two cases:

- when adb reverse hasn't been setup yet for android devices (common enough)
- when a build tries to load a non-existent main.jsbundle (happens if you want to run a debug build with a jsbundle)

Any suggestions for making sure these two cases are covered as well?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidredbox-message-misleading-redbox-message-when-starting-app-for-the-first-time-without-packager-running

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
