### ISSUE TITLE
GIF not working in Android - React Native 0.76 

### ISSUE THREAD

**Issue by sujathasperi2022** [facebook/react-native#47408]
### Description

GIF not working in Android - React Native 0.76.
But it is correctly working in iOS. 

android/app/build.gradle  is updated with gif support library 
`implementation 'com.facebook.fresco:animated-gif:3.1.3'`

### Steps to reproduce

1. nom install
2. npx react-native run-android

### React Native Version

0.76.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (8) arm64 Apple M1
  Memory: 92.86 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.2.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.09.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/amithsnair/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.4.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/amithsnair/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Not getting any errors or logs
```

### Reproducer

https://github.com/sujathasperi2022/testapp.git

### Screenshots and Videos

![Screenshot_1730790418](https://github.com/user-attachments/assets/6958efd7-2867-4352-bc3a-085b01dfbd7a)

**Comment by shubhamguptadream11** [comment]
@sujathasperi2022 Is this issue started coming from 0.76.0?

**Comment by sujathasperi2022** [comment]
@shubhamguptadream11 I recently started a new project with RN version 0.76.0 in which I noticed this in **Android** in iOS is working properly
I created a Testapp which i linked above to see if any package in my project is causing this but NO. The teat app only has basic template of a RN project. 
I have a old project in RN version 0.70.1 in that the gif is working correctly in both platforms

**Comment by shubhamguptadream11** [comment]
@sujathasperi2022 Your fresco library version is outdated. Try upgrading it to `3.4.0.` It's possible that current fresco version you are using is not compatible with 0.76 RN.

**Comment by sujathasperi2022** [comment]
Will check with that and let you know

**Comment by cortinico** [comment]
> Will check with that and let you know

Also could you please check if your same setup but with RN 0.75.x is working or not?

**Comment by nianxiongdi** [comment]
@cortinico   i am on RN version 0.75.2, and gif cannot be played either.

**Comment by nianxiongdi** [comment]
@sujathasperi2022  Has it been resolved?

**Comment by deepakSenseHawk** [comment]
Upgrading fresco library solved my issue, Thanks @shubhamguptadream11

**Comment by amitkumarcoding** [comment]
"Add the following dependency to the `app/build.gradle` file:

`implementation 'com.facebook.fresco:animated-gif:3.6.0'`

If this specific version doesn't work, you must use the latest available version of the Fresco library instead."

**Comment by PichsineeWittayakotanakun** [comment]
> "Add the following dependency to the `app/build.gradle` file:
> 
> `implementation 'com.facebook.fresco:animated-gif:3.6.0'`
> 
> If this specific version doesn't work, you must use the latest available version of the Fresco library instead."

I'm using react native "0.79.0"
add implementation 'com.facebook.fresco:animated-gif:3.6.0' works for me, Thanks
