### ISSUE TITLE
[bridgeless][interop] setTimeout breaks when app goes background and using headlessJsTaskService

### ISSUE THREAD

**Issue by lovegaoshi** [facebook/react-native#47436]
### Description

setTimeouts will stop working if the app is using headlessJsTaskService and goes minimized then resumed. a demonstration of this issue is shown as the white counter in the provided app at the very top (counts +1 every second); once the app is minimized and restored, it will stop counting. 

I have investigated and it appears that[ ClearFrameCallback in JavaTimeManager should always clear](https://github.com/lovegaoshi/RNTPExampleNewArch/blob/bug/hook-not-updating/patches/react-native%2B0.76.1.patch), instead of only when headlessJsTask is empty as well. (the provided app has this patched in, remove to see its broken)

### Steps to reproduce

1. open app
2. minimize app
3. resume app
4. see counter is no longer counting

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
  CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Memory: 28.90 GB / 62.72 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 21.7.2
    path: ~/.nvm/versions/node/v21.7.2/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v21.7.2/bin/yarn
  npm:
    version: 10.8.3
    path: ~/.nvm/versions/node/v21.7.2/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    Android NDK: 23.0.7344513-beta4
IDEs:
  Android Studio: Not Found
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
n/a
```

### Reproducer

https://github.com/lovegaoshi/RNTPExampleNewArch/tree/bug/hook-not-updating

**Comment by cortinico** [comment]
@robik is this something you could help us with?

**Comment by lovegaoshi** [comment]
tracked by https://github.com/facebook/react-native/issues/47495
