### ISSUE TITLE
I can't install react-native.  Unknown command: "init$1$1"

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#47485]
### Description

I copied the installation command from the official website. I have previously set up the environment, everything is fine. But the installation command gives an error. 

```npx @react-native-community/cli@latest init AwesomeProject```

![image](https://github.com/user-attachments/assets/c16cdb9a-322b-4bc9-a0e0-f0b1f711dcb2)

 I understand that probably react-native is not to blame here, but I no longer know where to go for help. The error is not even Googled!

### Steps to reproduce

npx @react-native-community/cli@latest init AwesomeProject

### React Native Version

0.76.1

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
no react-native
```

### Stacktrace or Logs

```text
⠹ Downloading template

error An unexpected error occurred: Command failed with exit code 1: npm init -y
Unknown command: "init$1$1"

To see a list of supported npm commands, run:
  npm help.
```

$ node -v
v22.11.0

$ npm -v
10.9.0

$ npx -v
10.9.0

**Comment by cavadibrahimli1** [comment]
> I had same problem.
> 
> I reinstalled NPM, Nodejs. Then I tried this one in the C: folder, It worked for me.
> 
> `npx @react-native-community/cli@latest init SampleApp --version 0.76.0`

I advice you to restart your device after doing the reinstallation phase

**Comment by cortinico** [comment]
> I had same problem.
> 
> I reinstalled NPM, Nodejs. Then I tried this one in the C: folder, It worked for me.
> 
> `npx @react-native-community/cli@latest init SampleApp --version 0.76.0`

Yup this sounds like the right solution @valery-lavrik 

If that doesn't help, could you open your same issue here:

https://github.com/react-native-community/cli/issues

The code where the failure happens is inside the Community CLI so if there is a bug there, it should be fixed inside the Community CLI code

**Comment by valery-lavrik** [comment]
I found the reason.   The problem was that during the installation I was distributing Internet from my mobile phone. As soon as I switched to normal wi-fi, everything worked immediately. I don't understand how this is connected....

**Comment by cavadibrahimli1** [comment]
@valery-lavrik I advice you to connect both your phone and your computer to the same WiFi network during development
