### ISSUE TITLE
Timers don't work in headless tasks and may break in the application when headless tasks are used

### ISSUE THREAD

**Issue by j-piasecki** [facebook/react-native#47495]
### Description

`JavaTimerManager` is being registered to receive headless tasks events in the [`TimingModule`](https://github.com/facebook/react-native/blob/0ee963ea65bcc88122044d51027511e611bde584/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/core/TimingModule.kt#L28-L29), which isn't used on Bridgeless. Due to this, timers don't work in headless tasks unless the app is in the foreground, and minimizing/reopening the app may entirely break the timers.

### Steps to reproduce

1. Build the android app
2. Click on the `SetTimeout` button
3. Observe console log after 2 seconds
4. Click `StartService` (the app will close)
5. There are no logs from the service unless the app is in foreground (timeouts don't work in the headless task)
6. Reopen the app
7. Go back to home screen
8. Go back to the app
9. Click on the `SetTimeout` button
10. Timeouts don't work in the app at all

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android

### Areas

Bridgeless - The New Initialization Flow

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.7
  CPU: (12) arm64 Apple M3 Pro
  Memory: 106.73 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman:
    version: 2024.09.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "24"
      - "26"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 26.0.3
      - 28.0.3
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
      - 35.0.0
    System Images:
      - android-28 | Google ARM64-V8a Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/jakubpiasecki/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```
```


### Stacktrace or Logs

```text
-
```

### Reproducer

https://github.com/j-piasecki/timer-headless-task-issue

### Screenshots and Videos

https://github.com/user-attachments/assets/c49a5209-7296-4420-96ba-07eef9016371

**Comment by Raiden-16F7** [comment]
Im using expo SDK 52, with react native 0.76.9 and still facing this issue that my setTimeout's dont work in my headless notification task while the app is in the background on android.
