### ISSUE TITLE
DefaultNewArchitectureEntryPoint.load() does not exist

### ISSUE THREAD

**Issue by tapz** [facebook/react-native#47511]
### Description

Updated my code per React Native Upgrade Helper to 0.76.1. Now the code does not compile:

```
MainApplication.kt:153:14 None of the following candidates is applicable:
static fun init(p0: Context!, p1: Int): Unit
static fun init(p0: Context!, p1: Boolean): Unit
```

As a workaround, I can comment the line out as I have never managed to get the new architecture compile anyway. But would be nice if there was a way to make it actually work.

### Steps to reproduce

1. Call DefaultNewArchitectureEntryPoint.load()

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
info Fetching system and libraries information...
System:
  OS: macOS 15.0.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 1021.33 MB / 96.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.18.0
    path: ~/.nvm/versions/node/v20.18.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.18.0/bin/npm
  Watchman:
    version: 2024.11.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 23.0.1
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
MainApplication.kt:153:14 None of the following candidates is applicable:
static fun init(p0: Context!, p1: Int): Unit
static fun init(p0: Context!, p1: Boolean): Unit
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by cortinico** [comment]
> ### Description
> Updated my code per React Native Upgrade Helper to 0.76.1. Now the code does not compile:
> 
> ```
> MainApplication.kt:153:14 None of the following candidates is applicable:
> static fun init(p0: Context!, p1: Int): Unit
> static fun init(p0: Context!, p1: Boolean): Unit
> ```
> 
> As a workaround, I can comment the line out as I have never managed to get the new architecture compile anyway. But would be nice if there was a way to make it actually work.
> 
> ### Steps to reproduce
> 1. Call DefaultNewArchitectureEntryPoint.load()

Your error refers to a method called `init` (which I suppose is coming from `SoLoader.init`) while you're talking about the `load` method from `DefaultNewArchitectureEntryPoint`.

Moreover, we can't help you without looking at your code.

This is definitely something going on with your setup in your MainApplication.kt
Please refer to the official one from the template:
https://github.com/react-native-community/template/blob/0.76-stable/template/android/app/src/main/java/com/helloworld/MainApplication.kt

**Comment by tapz** [comment]
My code is exactly as the upgrade helper instructs. I can't just give access to my employees code. But this is basically what I'm doing:

```
SoLoader.init(this, OpenSourceMergedSoMapping)
if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
  load()
}
```

**Comment by cortinico** [comment]
> My code is exactly as the upgrade helper instructs. I can't just give access to my employer's code. But this is basically what I'm doing:

Then please use the reproducer template to reproduce your error:
https://github.com/react-native-community/reproducer-react-native

and we can look into ti

**Comment by ObscurusGrassator** [comment]
I create new r.n. app (by last instruction) and transform kotlin files to java.
(By the way, it is a huge fail that you have officially stopped supporting Java projects)
npm start android compile error:

```
MainApplication.java:64: error: cannot find symbol
    SoLoader.init(this, OpenSourceMergedSoMapping);
                        ^
  symbol:   variable OpenSourceMergedSoMapping
  location: class MainApplication
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Interesting: the import does not report a problem:
```
import com.facebook.react.soloader.OpenSourceMergedSoMapping;
```

<details>
<summary>npx react-native info:</summary>
System:
  OS: macOS 14.7
  CPU: (12) arm64 Apple M2 Max
  Memory: 509.55 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | AOSP ATD ARM 64 v8a
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | AOSP ATD ARM 64
      - android-35 | ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
      - android-35 | Pre-Release 16 KB Page Size Google Play ARM 64 v8a
      - android-35 | Pre-Release 16 KB Page Size Google APIs ARM 64 v8a
      - android-35 | Google APIs ATD ARM 64
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /opt/homebrew/opt/ruby@2.7/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: 15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
<details>
