### ISSUE TITLE
[newarch regression] [iOS] Font scale changes are not applied until app restart

### ISSUE THREAD

**Issue by SimpleCreations** [facebook/react-native#47522]
### Description

In Old Architecture, if font scale is updated while the app is running (e.g. using Cmd Option `+`/`-` on a simulator), the changes are immediately applied.

In New Architecture, if font scale is updated while the app is running, a restart or reload is required for changes to take effect.

### Steps to reproduce

1. Run the example on iOS simulator with `ENV['RCT_NEW_ARCH_ENABLED'] = '0'`.
2. Press Cmd Option `+`.
3. Observe that font scale changes took effect immediately (all text grew larger).
4. Run the example on iOS simulator with `ENV['RCT_NEW_ARCH_ENABLED'] = '1'`.
5. Press Cmd Option `+`.
6. Observe that font scale changes didn't take effect.
7. Reload the app.
8. Observe that now font scale changes took effect.

### React Native Version

0.76.1

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://snack.expo.dev/ZHX6ikN41oI4Dths91h9T

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/45655
