### ISSUE TITLE
android crash new arch

### ISSUE THREAD

**Issue by philipheinser** [facebook/react-native#47535]
### Description

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.react.interfaces.fabric.ReactSurface com.facebook.react.ReactHost.createSurface(android.content.Context, java.lang.String, android.os.Bundle)' on a null object reference
    com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:292)
    com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:137)
    com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:132)
    com.facebook.react.ReactActivity.onCreate(ReactActivity.java:47)
```

### Steps to reproduce

after update run on android 

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.2
  CPU: (12) arm64 Apple M2 Pro
  Memory: 110.81 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.1.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.11.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.1
    wanted: 15.1.1
  react:
    installed: 18.3.1
    wanted: ^18.3.1
  react-native:
    installed: 0.76.1
    wanted: ^0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.react.interfaces.fabric.ReactSurface com.facebook.react.ReactHost.createSurface(android.content.Context, java.lang.String, android.os.Bundle)' on a null object reference
    com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:292)
    com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:137)
    com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:132)
    com.facebook.react.ReactActivity.onCreate(ReactActivity.java:47)
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by Eralyne** [comment]
Hey, I'm facing this same issue and struggling to find the source of the problem. What solution did you find?

**Comment by Eralyne** [comment]
@philipheinser That sucks to hear, thanks for the quick reply.

**Comment by VimukthiShohan** [comment]
Same issue

**Comment by aleksnied** [comment]
hi all, I ran into the same issue upgrading from an older version to 0.76. The fix for me was a missing override in my MainApplication.kt that was not needed there previously:

`  override val reactHost: ReactHost
    get() = ReactNativeHostWrapper.createReactHost(applicationContext, reactNativeHost)`
    
    After I added this in the app now launches fine. Easy to miss, previously only reactNativeHost override was required.

**Comment by Ryan82012993** [comment]
> hi all, I ran into the same issue upgrading from an older version to 0.76. The fix for me was a missing override in my MainApplication.kt that was not needed there previously. After I added this in the app now launches fine. Easy to miss, previously only reactNativeHost override was required.
> 
> ` override val reactHost: ReactHost get() = ReactNativeHostWrapper.createReactHost(applicationContext, reactNativeHost)`

Where did the ReactNativeHostWrapper come from?

**Comment by tekinalper** [comment]
I'm facing with this as well. Any details?

**Comment by Ryan82012993** [comment]
> I'm facing with this as well. Any details?

setup expo can fix

**Comment by saiyam-zepto-dev** [comment]
Is this expo ? @aleksnied 

Because for me there is no file named ReactNativeHostWrapper in the node_modules of react-native signalling that the import cant be done

**Comment by Phecda** [comment]
try this if you are not using expo

``` kotlin
   override val reactHost: ReactHost
        get() = getDefaultReactHost(applicationContext, reactNativeHost)
```
