### ISSUE TITLE
[Android] Unable to upload APKS

### ISSUE THREAD

**Issue by super2457** [facebook/react-native#4756]
Android system version：5.11
pc system：window7
DOS instruction：react-native run-android
error：
![1450009022820-1449886131239-qq 20151212100825](https://cloud.githubusercontent.com/assets/9149356/11767034/a7b0b962-a1da-11e5-9c89-e6752338a474.png)

![1450009022818-1449886138620-qq 20151212100838](https://cloud.githubusercontent.com/assets/9149356/11767026/3324ec30-a1da-11e5-9080-def6aeebdc26.png)
My cell phone has turned on the developer mode.
But I don't know why, every cell phone I got is this kind of situation. I follow the requirements of the document, the configuration of each step is good.

Thank！

**Comment by satya164** [comment]
Hey @super2457 

It's most likely a bug with gradle rather than React Native. You can try changing your build tools version to see if it fixes your issue.

**Comment by christopherdro** [comment]
@super2457  We're you able to resolve this issue?

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow
