### ISSUE TITLE
 In Xcode7.2 , has failed :(

### ISSUE THREAD

**Issue by git-lt** [facebook/react-native#4757]
all proj run in Xcode7.2 is failed;
img show like this:
http://i4.tietuku.com/627513ed7ceba0ed.jpg

**Comment by christopherdro** [comment]
@git-lt Did this work in a previous version of Xcode. I don't see how that could be the issue though.

Can you double check that `test` is the same value used in `registerComponent` ?

**Comment by git-lt** [comment]
react-natve  Version : 0.1.7
xcode Version:  7.2 (7C68)
@christopherdro 
Just happen at that Upgrade Xcode to 7.2
new proj create like this:
react-native init test

index.ios.js
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var test = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('test', () => test);
```

**Comment by theaqua** [comment]
I has same problem, it was because I have cache from another project with different name and XCode use it's `main.jsbundle` (https://github.com/facebook/react-native/issues/4289).

I kill all processes, delete everything in TMPDIR and then start my build with `--resetCache true`

**Comment by git-lt** [comment]
Running rm -rf $TMPDIR/react-*, now is working!  Thks!!!!!!!

**Comment by tgoldenberg** [comment]
I am also getting an error with XCode 7.2 - app builds and run just fine, but the Simulator doesn't show anything!
