### ISSUE TITLE
0.76.1 Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.   > Java heap space

### ISSUE THREAD

**Issue by ayanWappnet** [facebook/react-native#47582]
### Description

i create new project with 0.76.1 and install library package and i migrate my old project to new 0.76.1 

### Steps to reproduce

1. install yarn which version 1.22.22
2. react native 0.76.1 
3. clean build with  =>  cd android && ./gradlew clean && cd ..
4. and run project

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android, Build - Linux

### Output of `npx react-native info`

```text
System:
  OS: Linux 5.8 Ubuntu 20.04.6 LTS (Focal Fossa)
  CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  Memory: 5.17 GB / 15.57 GB
  Shell:
    version: 5.0.17
    path: /bin/bash
Binaries:
  Node:
    version: 21.7.3
    path: ~/.nvm/versions/node/v21.7.3/bin/node
  Yarn:
    version: 1.22.22
    path: /usr/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v21.7.3/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
```

### Stacktrace or Logs

```text
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Failed to transform react-android-0.76.1-debug.aar (com.facebook.react:react-android:0.76.1) to match attributes {artifactType=android-databinding, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform:

.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.76.1/100f1d6599f807cbf57a4c51764b302eb2bd8b71/react-android-0.76.1-debug.aar.
         > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'. > Failed to transform react-android-0.76.1-debug.aar (com.facebook.react:react-android:0.76.1) to match attributes {artifactType=android-databinding, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}. > Execution failed for JetifyTransform: 

.gradle/caches/modules-2/files-2.1/com.facebook.react/react-android/0.76.1/100f1d6599f807cbf57a4c51764b302eb2bd8b71/react-android-0.76.1-debug.aar. > Java heap space * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 12s.
```

### Reproducer

<>

**Comment by shubhamguptadream11** [comment]
Please provide a valid reproducer. You can use this [template](https://github.com/react-native-community/reproducer-react-native/generate).

**Comment by ayanWappnet** [comment]
Hey @shubhamguptadream11  it's private repo 

 some times  i found this error 
 Error: ENOENT: no such file or directory, lstat 'NativeSampleTurboModule'
 ules/@react-native/codegen/lib/cli/combine/combine-js-to-schema-cli.js:26:10)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'NativeSampleTurboModule'

**Comment by FouadMagdy01** [comment]
I think i have faced this issue yesterday and i have done this and as i remember it helped

Go to file > Invalidate Caches
Select the three checkboxes 

I am not sure if this would help

**Comment by cholazzzb** [comment]
I got the same error in macOS. 

I did the same things: I create new project with 0.76.1 and install library package and i migrate my old project to new 0.76.1

**Comment by cholazzzb** [comment]
I solve this issue by installing `react-native gradle-plugin` with the same version with `react-native` 

```
npm install @react-native/gradle-plugin@0.76.1 --exact
# or if yarn
yarn add @react-native/gradle-plugin@0.76.1 --exact
```

I hope this help @ayanWappnet

**Comment by ayanWappnet** [comment]
@cholazzzb  not work and i also upgrade 0.76.2

**Comment by ctTushar** [comment]
can you try this change by increase `org.gradle.jvmargs=-Xmx4608m` and see if it's works.

**Comment by cortinico** [comment]
> can you try this change by increase `org.gradle.jvmargs=-Xmx4608m` and see if it's works.

This is the correct answer.

"Java heap space" means that Gradle ran out of memory.
You can find similar issues in the issue tracker as well:
https://github.com/facebook/react-native/issues?q=%22Java+heap+space%22+is%3Aclosed
