### ISSUE TITLE
Compile jsbundle to hbc on iOS

### ISSUE THREAD

**Issue by nanatlantica** [facebook/react-native#47586]
### Description

Currently, my RN server is sending the jsbundle file, but the server cannot temporarily send the hbc file. I am now using Hermes engine version 0.75. How can I compile the jsbundle file into an hbc file on the iOS client and use it?

### Steps to reproduce

Currently, my RN server is sending the jsbundle file, but the server cannot temporarily send the hbc file. I am now using Hermes engine version 0.75. How can I compile the jsbundle file into an hbc file on the iOS client and use it?

### React Native Version

0.75.0

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
macOS : 15.0.1
iOS : 16.7.10
```

### Stacktrace or Logs

```text
null
```

### Reproducer

https://github.com/nanatlantica/RNDynamic.git

**Comment by cortinico** [comment]
> How can I compile the jsbundle file into an hbc file on the iOS client and use it?

You can use `hermesc` to do that. You can find it inside the `node_modules/react-native/sdks/hermesc` folder.

If you need an idea of the same CLI flags we use for Android during the regular bundling, you can find them here:

https://github.com/facebook/react-native/blob/1a9780f0e3714ac18ffae34cb67376c711b0e031/packages/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/tasks/BundleHermesCTask.kt#L178-L186
