### ISSUE TITLE
[Android] Issue using resizeMode style on <Image />, RN 0.16

### ISSUE THREAD

**Issue by cbrevik** [facebook/react-native#4759]
I keep getting two similar warnings on Android;
```
Warning: Failed propType: Invariant Violation: Invalid props.style key `resizeMode` supplied to `View`.
Bad object: {
  "width": 300,
  "height": 220,
  "overflow": "hidden",
  "resizeMode": "stretch",
  "justifyContent": "space-around"
}
Valid keys: [
 ...
] Check the render method of `Image`.
```
And almost the same message, but with `supplied to RCTView` instead of `View`, and `Check the render method of View` instead of `Image`.

The only thing in my app I can see this corresponding to is the following;
```
<Image style={styles.card} source={card_images[this.state.cardImgIndex]} >
    <Text>
        {this.props.question}
    </Text>
</Image>
```

with this style;
```
card: {
    width: 300,
    height: 220,
    resizeMode: 'stretch',
    justifyContent: 'space-around'
}
```

The style not being applied correctly on Android, the image is not displayed as it should. This works fine on iOS.

**Comment by ms88privat** [comment]
@cbrevik did you try to set the resizeMode directly on the Image? `<Image resizeMode="cover" .../>`

**Comment by cbrevik** [comment]
@ms88privat that works, thanks! Still, it should be possible to apply it through styles, shouldn't it?

**Comment by ide** [comment]
resizeMode is not a style: https://facebook.github.io/react-native/docs/image.html#props. The fact this works on iOS is because it's lenient but is unsupported behavior.
