### ISSUE TITLE
[NavigatorIOS] resetTo will not change the title or rightButton

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#476]
I'm not sure if this is a feature or a bug.

My initial route:

```js
return <NavigatorIOS
       style={{flex: 1}}
       initialRoute={{
               component: Login,
               title: 'Login',
       }} />;
```

in `Login`, I have such function to handle reseting route:

```js
_handleLogin() {
     this.props.navigator.resetTo({
       component: ChatList,
       title: 'Chat List',
     });
},
```

However, the title seems not change even the ChatList is rendered correctly.

**Comment by a-warner** [comment]
This is happening to me as well, pretty sure it's a bug, since `push`ing another route afterwards and then popping does change the title correctly to the title specified in `resetTo`

**Comment by pwmckenna** [comment]
This seems to be a bug with any navigation that defers to [`replaceAtIndex`](https://github.com/facebook/react-native/blob/master/Libraries/Components/Navigation/NavigatorIOS.ios.js#L471), which doesn't do the locking that push/pop/etc do.

**Comment by pwmckenna** [comment]
@ericvicenti thoughts? If I was on the right path I could try put a pull request together. Don't really have a sense of the scale of the issue though.

**Comment by ericvicenti** [comment]
Yeah, it sounds like you are on the right track. If this is affecting you then I would see what you can do to fix it or work around it. We don't use NavigatorIOS internally, so we can't spend much time fixing things, but we are happy to accept any fixes that people contribute.

**Comment by AdamBrodzinski** [comment]
+1 I'm having to same issue too.

**Comment by pwmckenna** [comment]
@ericvicenti do you guys just use navigator internally?

**Comment by ericvicenti** [comment]
Yep, we only use the Navigator in our apps right now. It gives us a bit more flexibility over gestures and animations, and we're using it on Android as well, which helps us share code.

We don't have the bandwidth to support components which aren't used by our internal clients, so it is up to the community to maintain NavigatorIOS. We are happy to accept your PRs!

**Comment by jaredly** [comment]
@pwmckenna the base issue is that NavigatorIOS doesn't have the logic for updating nav items in-place [see source](https://github.com/facebook/react-native/blob/master/React/Views/RCTNavigator.m#L486)

**Comment by brentvatne** [comment]
@jaredly - seems like this is worth adding support for - I had an initial shot at this [here](https://github.com/facebook/react-native/issues/1403#issuecomment-106588791), we could use the same strategy for other props

**Comment by mccambridge** [comment]
I seems as if replace suffers from the same issue.

**Comment by Iragne** [comment]
well i create this PR for that https://github.com/facebook/react-native/pull/1733

**Comment by AdamBrodzinski** [comment]
I've found a work around to use `resetTo` that resets the title. When you want to use `resetTo`, save a reference to the route and use `replace` instead. 

```
 nextPage() {
    global.__feedRoute = {
      title: 'Feed',
      component: __Feed
    };
    __nav.replace(__feedRoute);
  }       
```

Then in the next component (Feed in this example), call `resetTo` which removes the back button and animates in.

```
  // Feed.js
  componentWillMount() {
    __nav.resetTo(__feedRoute);
  },          
```

The first call to replace will change the title and hopefully the right button, this also does not animate it. The next call to `replaceTo` will reset the stack and you should be good to go.

**Comment by hanai** [comment]
same problem with replace

**Comment by Iragne** [comment]
may be this PR can help 
https://github.com/facebook/react-native/pull/2526

**Comment by matejkramny** [comment]
`replace` has the same issue.

What needs to happen to fix this? Any way i can help?

**Comment by cancan101** [comment]
There is this: https://github.com/facebook/react-native/pull/3516

**Comment by iqnivek** [comment]
#3516 was replaced by #3809. Seems like @rocman has a potential fix, but is dealing with a failing CI build.

**Comment by Iragne** [comment]
I check both implementation in objective c. i think the delegate link in this pr https://github.com/facebook/react-native/pull/2526  is more code compliant.

**Comment by longsangstan** [comment]
I use <Navigator> and have similar issue.
The old rightButton still clickable (although hidden) after pushing to the new route.

**Comment by DenisIzmaylov** [comment]
Up!

**Comment by lacker** [comment]
AFAICT this issue now covers a number of different problems, of which https://github.com/facebook/react-native/pull/3809 and https://github.com/facebook/react-native/pull/2526 fixed two of them. I am going to close this issue but if there is still a problem then I encourage folks to open a new issue with a repro of the specific bug in a rnplay.org link.
