### ISSUE TITLE
Physics Device not connect metro, but works fine on simulator

### ISSUE THREAD

**Issue by yedi97** [facebook/react-native#47601]
### Description

It works fine on simulator but with physics device it cannot connect.
Sure i'm using the same wifi network, tried many ways like:

1. Reset my phone
2. Unpair and reconnect my phone
3. reset cache (npm start -- --reset-cache)
4. run with xcode

### Steps to reproduce

1. connect ios physics device with usb and same wifi
2. npx react-native run-ios --udid "my Identifier"
3. my iphone using IOS 18.1, XS model

### React Native Version

0.76.1

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (8) arm64 Apple M1
  Memory: 338.73 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.9.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 4.1.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.3
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: ^15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.
info Reloading connected app(s)...
```

### Reproducer

https://github.com/yedi97/reproducer-react-native

**Comment by shubhamguptadream11** [comment]
Did you tried running this using Xcode?

**Comment by rizwan-gill** [comment]
I'm also facing the same issue on the Android real device. it works on the simulator.

**Comment by yedi97** [comment]
> Did you tried running this using Xcode?

Yes, but it still not works

**Comment by yedi97** [comment]
> Hi
> 
> 1. Try shaking the iOS device and adding your IP Address manually. Check if it works.
> 2. If the above doesn't work, then remove watchman (if you have) then try the same as above.

I tried both methods above before, but it still doesn't work

**Comment by the-mysterious-kid** [comment]
Was there any fix to this issue? @yedi97
