### ISSUE TITLE
fetch data before rendering navigator

### ISSUE THREAD

**Issue by joshbedo** [facebook/react-native#4760]
I'm currently trying to find a way to check if a user session exists on the backend before rendering the navigator scene but can't seem to delay render until the fetch is complete. Wondering if anyone has solved this already.

Here is the code
```js
'use strict';

import React from 'react-native'

let {
  StyleSheet,
  Navigator,
  PropTypes,
  AsyncStorage
} = React

import { GET_USER_SESSION } from '../utils/API'
import LoginContainer from './LoginContainer'
import MainContainer from './MainContainer'

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      user: null,
      isLoggedIn: null,
    }
  }

  componentWillMount() {
    // fetch asyncOffline token and user if user go to main otherwise login
    AsyncStorage.getItem('user').then((userId) => {
      console.log(userId, 'userId');
      // token doesnt matter right now but we might want to add later
      return this.getUser()
    }).then((resp) => {
      this.setState({
        user: resp.user,
        isLoggedIn: true
      });
    })
  }

  getUser() {
    return fetch(GET_USER_SESSION, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      }
    })
    .then((response) => {
      return response.json()
    })
    .then((data) => {
      return data
    }).catch((err) => this.showError('Error Signing Up, Please Try Again.'))
  }

  renderScene(route, navigator) {
    let Component = route.component

    return (
      <Component navigator={navigator} route={route} />
    )
  }

  configureScene(route) {
    if (route.name && route.name === 'Search') {
      return Navigator.SceneConfigs.FadeAndroid
    } else {
      return Navigator.SceneConfigs.FloatFromBottomAndroid
    }
  }

  render() {
    console.log(this.state.isLoggedIn, 'isLoggedIn')

    // here is where i want to change the container depending on the user session
    let Route = (this.state.isLoggedIn) ?
      MainContainer : LoginContainer

    return (
      <Navigator
        ref='navigator'
        style={styles.navigator}
        configureScene={this.configureScene}
        renderScene={this.renderScene}
        initialRoute={{
          component: LoginContainer, // Route
          name: 'Login'
        }} />
    )
  }
}

let styles = StyleSheet.create({
  navigator: {
    flex: 1
  }
})

export default App
```

**Comment by Sh3rawi** [comment]
Add a 'ready' key to the getInitialState with false value, and as long as its false, render a waiting view or whatever, and then when the data is fetched from the backend, change this state key to true and render the navigator.
render() {
if (!this.state.ready) {
  return (<View> {some waiting login} </View>);
} else {
  // here you already have the data to know if he has a session
  return (
    the navigator and all its stuff
  );
}
Does this solve your problem ?

**Comment by satya164** [comment]
You can return `null` from the render function until the data fetching is complete, or maybe a loading spinner.

```js
render() {
    let Route = (this.state.isLoggedIn) ? MainContainer : LoginContainer;

    if (!this.state.isLoggedIn) {
        return <LoadingScreen />;
    } else {
        return (
          <Navigator
            ref='navigator'
            style={styles.navigator}
            configureScene={this.configureScene}
            renderScene={this.renderScene}
            initialRoute={{
              component: LoginContainer, // Route
              name: 'Login'
            }} />
        );
    }
  }
```

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by zifnab87** [comment]
`return null;` in `render()` made it for me thanks to @satya164
