### ISSUE TITLE
Gradual memory leak with fetch (iOS only)

### ISSUE THREAD

**Issue by ajwhite** [facebook/react-native#4761]
I noticed my application, which relies on periodic polling, has a memory footprint that grows consitently over time. I've vetted it for any global leaks and decided to scale down the scenario with a new project that runs a single `fetch` on an interval and observed the same behavior in steady growth. Android remained flat with no growth after releasing resources.

_Note: this is in release mode, `dev=false`_

![screen shot 2015-12-13 at 5 13 29 pm](https://cloud.githubusercontent.com/assets/656630/11769763/ef672890-a1bc-11e5-87a7-7ebebc8a0b50.png)

The component does one thing -- a `fetch` every second and updates the state with a counter.

```js
class NetworkTesting extends Component {
  constructor(props) {
    super(props);
    this.state = {value: 1};
  }
  componentDidMount() {
    this.fetchInterval = setInterval(() => {
      fetch('https://www.google.com')
        .then(() => {
          this.state.value++;
          this.setState(this.state);
        });
    }, 1000);
  }
  componentWillUnmount() {
    clearInterval(this.fetchInterval);
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {this.state.value}
        </Text>
      </View>
    );
  }
}
```

Here's a peak at the allocation instrument
![screen shot 2015-12-13 at 5 19 57 pm](https://cloud.githubusercontent.com/assets/656630/11769800/c09444c0-a1bd-11e5-9c5c-bbc8faa265a2.png)

At around 5 hours in the footprint is over 6x what it initially was:
![screen shot 2015-12-13 at 10 34 12 pm](https://cloud.githubusercontent.com/assets/656630/11772338/a972ac24-a1e9-11e5-8b8d-d8d05b96213a.png)

Here's a breakdown over time, I will continue to update it over the next few hours:

- Initially: ~25 MB
- 3 mins: 27MB
- 15 mins: 30 MB
- 45 mins: 45 MB
- 60 mins: 53 MB
- 75 mins: 61.5 MB
- 90 mins: 72 MB
- 120 mins: 84 MB
- 150 mins: 98 MB
- 170 mins: 111 MB
- 210 mins: 131 MB
- 225 mins: 141 MB
- 300 mins : 182 MB

This is seen in `0.15.0`, however I believe this is is separate than that of https://github.com/facebook/react-native/issues/4538

**Comment by ajwhite** [comment]
Wondering if this is something that @nicklockwood might have some thoughts towards

**Comment by ajwhite** [comment]
I've tested this a couple more times. 
- With `0.17.0-rc`, which includes the fix for #4538
- Without `fetch` and simply with a `setInterval` that updates the `state`.

Both of these have a gradual rise in memory. Without `fetch`, the increase is much smaller, but it still grows over time. The rise in memory also still exists in `0.17.0-rc` with `dev=false`

**Comment by aroth** [comment]
Also discussed at https://github.com/facebook/react-native/issues/4730

**Comment by ajwhite** [comment]
Thanks for the cross ref, there's a few threads open and I haven't seen this one yet.

**Comment by ajwhite** [comment]
After retesting these cases in **release mode**, I can confirm that this is not a problem and only exists when running in debug mode.

:tada:
