### ISSUE TITLE
Java project error: cannot find symbol: OpenSourceMergedSoMapping

### ISSUE THREAD

**Issue by ObscurusGrassator** [facebook/react-native#47633]
### Description

I create new r.n. app (by last instruction) and transform kotlin files to java (Kotlin files working good).
(By the way, it is a huge fail that you have officially stopped supporting Java projects)

### Steps to reproduce

I create new r.n. app (by last instruction) and transform kotlin files to java (Kotlin files working good).
(By the way, it is a huge fail that you have officially stopped supporting Java projects)

There is probably a problem with overwriting this file:
MainApplication.java:
```java
package com.aaatest;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactHost;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.react.defaults.DefaultReactHost;
import com.facebook.react.soloader.OpenSourceMergedSoMapping;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  @Override
  public ReactNativeHost getReactNativeHost() {
    return new DefaultReactNativeHost(this) {
      @Override
      public boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
      }

      @Override
      protected List<ReactPackage> getPackages() {
        @SuppressWarnings("UnnecessaryLocalVariable")
        List<ReactPackage> packages = new PackageList(this).getPackages();
        return packages;
      }

      @Override
      protected String getJSMainModuleName() {
        return "index";
      }

      @Override
      protected boolean isNewArchEnabled() {
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
      }

      @Override
      protected Boolean isHermesEnabled() {
        return BuildConfig.IS_HERMES_ENABLED;
      }
    };
  }

  @Override
  public ReactHost getReactHost() {
    return DefaultReactHost.getDefaultReactHost(getApplicationContext(), getReactNativeHost());
  }
      
  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, OpenSourceMergedSoMapping);

    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
  }
}
```

### React Native Version

0.76.2

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
<details>
<summary>npx react-native info:</summary>
System:
  OS: macOS 14.7
  CPU: (12) arm64 Apple M2 Max
  Memory: 509.55 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.17.0
    path: ~/.nvm/versions/node/v20.17.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v20.17.0/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | AOSP ATD ARM 64 v8a
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | AOSP ATD ARM 64
      - android-35 | ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
      - android-35 | Pre-Release 16 KB Page Size Google Play ARM 64 v8a
      - android-35 | Pre-Release 16 KB Page Size Google APIs ARM 64 v8a
      - android-35 | Google APIs ATD ARM 64
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.6
    path: /usr/bin/javac
  Ruby:
    version: 2.7.8
    path: /opt/homebrew/opt/ruby@2.7/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: 15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
<details>
```

### Stacktrace or Logs

```text
MainApplication.java:64: error: cannot find symbol
    SoLoader.init(this, OpenSourceMergedSoMapping);
                        ^
  symbol:   variable OpenSourceMergedSoMapping
  location: class MainApplication
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Interesting: the import does not report a problem:
```
import com.facebook.react.soloader.OpenSourceMergedSoMapping;
```
```


### Reproducer

 a

### Screenshots and Videos

_No response_

**Comment by shubhamguptadream11** [comment]
@ObscurusGrassator Can you re-try after cleaning all the caches ones?
- node_modules
- gradle cache
- android build folder

**Comment by ObscurusGrassator** [comment]
@shubhamguptadream11 No, cleaning all the caches did not help.

**Comment by root-io** [comment]
Same issue following https://react-native-community.github.io/upgrade-helper/?from=0.75.4&to=0.76.2 and still having a MainApplication.java instead of kt.

**Comment by ruijiang** [comment]
Same here. Followed https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#breaking-changes-1 to upgrade to 0.76.2, and hit this too!

**Comment by limal** [comment]
Same here. If you're facing the problem it's worth converting just your `MainApplication.java` to `MainApplication.kt`. It's quite easy to do actually.

The rest of you files, including `MainActivity.java` and your custom native modules, can stay in Java.

**Comment by Hyeeeein** [comment]
> 저도 마찬가지예요.
> 
> 문제에 직면했다면 그냥 당신 `MainApplication.java`으로 변환하는 게 가치가 있습니다 `MainApplication.kt`. 실제로 하는 건 꽤 쉽습니다.
> 
> `MainActivity.java`사용자 정의 네이티브 모듈을 비롯한 나머지 파일은 Java로 유지해도 됩니다.
> 
> 1. React Native Upgrade Helper 참조나 LLM을 사용하여 `MainApplication.java`파일의 이름을 바꾸고 변환합니다 .`MainApplication.kt`
> 2. `apply plugin: "org.jetbrains.kotlin.android"`맨 위에 줄을 추가합니다 `app/build.gradle`.
> 3. 아래 두 줄을 추가하세요 `build.gradle`.
> 
> ```
> buildscript {
>     ext {
>         /* ... */
>         ndkVersion = "26.1.10909125"
>         kotlinVersion = "1.9.22".   <------ ADD THIS
>     }
>     repositories {
>         google()
>         mavenCentral()
>     }
>     dependencies {
>         classpath("com.android.tools.build:gradle")
>         /* ... */
>         classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0'. <------ ADD THIS
>         ``` 
> ```

It worked successfully! Thank you. However, I'm really curious as to why Java couldn't find the symbol.

**Comment by Muzamil544** [comment]
> In `MainApplication.java`, use `SoLoader.init(this, OpenSourceMergedSoMapping.INSTANCE);`.
> 
> Don't forget to catch the `IOException` that can occur.

worked for me

**Comment by theagam** [comment]
> In `MainApplication.java`, use `SoLoader.init(this, OpenSourceMergedSoMapping.INSTANCE);`.
> 
> Don't forget to catch the `IOException` that can occur.

Thanks @c100k for this solution.

If still fail, can try this using try catch block -

import com.facebook.react.soloader.OpenSourceMergedSoMapping;
import java.io.IOException;

 try {
            SoLoader.init(this, OpenSourceMergedSoMapping.INSTANCE);
        } catch (IOException e) {
            e.printStackTrace();
        }

Thanks.

**Comment by vansh-vm04** [comment]
Thank you so much @c100k for this solution❤️
I was stuck in this issue for a day.
