### ISSUE TITLE
[Image] Can't load image from app home dir

### ISSUE THREAD

**Issue by demiurga** [facebook/react-native#4768]
Same problem with #2551, using RN-0.14. Error like that:

The RCTImageURLLoaders \<RCTAssetsLibraryImageLoader: 0x3ba97250\> and \<RCTPhotoLibraryImageLoader: 0x3ba1b630\> both reported that they can load the URL ~/Documents/imageName.png, and have equal priority (0). This could result in non-deterministic behavior.

I tried both `source={{uri: '~/Documents/imageName.png'}}` and `source={{uri: '/Users/MYNAME/Library/Developer/CoreSimulator/Devices/20596C4E-XXXX-XXXX-XXXX-2D3CAC299F04/ ... /Documents/imageName.png'}}` and got same error.

**Comment by Ehesp** [comment]
Have you tried going backwards down the directories to see if that works?

`source={{uri: '../../../..//imageName.png'}}`

**Comment by demiurga** [comment]
@Ehesp I tried what you said, but no luck there. Still got same error :(

**Comment by demiurga** [comment]
Ok, it works with `source={{uri: '/Users/MYNAME/Library/Developer/CoreSimulator/Devices/20596C4E-XXXX-XXXX-XXXX-2D3CAC299F04/ ... /Documents/imageName.png'}}` after I cleaned my `Documents` dir. Close this even I don't know why it happened...
