### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Pradip-BCA** [facebook/react-native#47692]
### Description

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> java.io.UncheckedIOException: Could not move temporary workspace (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-5dd2a0af-cc67-4253-ad4c-ccfe5db8d92b) to immutable location (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
info Run CLI with --verbose flag for more details.

### Steps to reproduce

FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> java.io.UncheckedIOException: Could not move temporary workspace (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-5dd2a0af-cc67-4253-ad4c-ccfe5db8d92b) to immutable location (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
info Run CLI with --verbose flag for more details.

### React Native Version

0.76.2

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
Windows 11
8GB RAM, 512 GB SAD
AND RISEN 5
PLEASE SOLVE THE PROBLEM
```

### Stacktrace or Logs

```text
FAILURE: Build failed with an exception.

* Where:
Settings file 'D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> java.io.UncheckedIOException: Could not move temporary workspace (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10-5dd2a0af-cc67-4253-ad4c-ccfe5db8d92b) to immutable location (D:\Mobile_App_Devlopment\LetestMobileApp\demo\android\.gradle\8.10.2\dependencies-accessors\569c8b261a8a714d7731d5f568e0e5c05babae10)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 10s
info Run CLI with --verbose flag for more details.
```

### Reproducer

expo/expo-template-default

### Screenshots and Videos

![Screenshot 2024-11-19 092250](https://github.com/user-attachments/assets/b768a0f1-b00b-4373-995b-cd06a0fa9c11)

**Comment by Sanjayng125** [comment]
Try cd android
./gradlew clean
And npx react-native run android or npm start

**Comment by mrozanc** [comment]
I have the same problem on all my projects, on 2 different computers, with different versions of Gradle (8.11.1, 8.11, 8.10.2), on projects that were working before without me touching anything. And on WSL it works fine for the same projects, so I think this problem is Windows 11 related. I only have it on Kotlin projects and not on Java projects also, so maybe it's related to the kotlin plugin.

```
❯ gradle --version

------------------------------------------------------------
Gradle 8.11.1
------------------------------------------------------------

Build time:    2024-11-20 16:56:46 UTC
Revision:      481cb05a490e0ef9f8620f7873b83bd8a72e7c39

Kotlin:        2.0.20
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.14 compiled on August 16 2023
Launcher JVM:  21.0.5 (Eclipse Adoptium 21.0.5+11-LTS)
Daemon JVM:    C:\Users\marc\scoop\apps\temurin21-jdk\current (no JDK specified, using current Java home)
OS:            Windows 11 10.0 amd64

❯ gradle init --type kotlin-library --dsl kotlin --project-name test-project --java-version 21

Select test framework:
  1: kotlin.test
  2: JUnit Jupiter
Enter selection (default: kotlin.test) [1..2] 1

Generate build using new APIs and behavior (some features may change in the next minor release)? (default: no) [yes, no] no


> Task :init
Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11.1/samples/sample_building_kotlin_libraries.html

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
```

`./gradlew clean --debug --stacktrace` generates this output:
[output-log.txt](https://github.com/user-attachments/files/17882644/output-log.txt)

**Comment by aryanagarwal15** [comment]
For me this worked:

In` gradle-wrapper.properties`
change:
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip`
to
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip`

then clean gradle by performing
`cd android
./gradlew clean`

**Comment by zhanyijie** [comment]
In gradle-wrapper.properties change: distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip to distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip

then clean gradle by performing cd android  ./gradlew clean

I have also tried it, and the result is correct on a Windows computer
