### ISSUE TITLE
(NOBRIDGE) ERROR TypeError: null is not an object (evaluating '_reactNative.NativeModules.DevSettings.setIsDebuggingRemotely') 

### ISSUE THREAD

**Issue by mohammedelnady** [facebook/react-native#47711]
### Description

React Native Version: 0.76.2 (New Architecture with Hermes enabled)
Debugging Tool: react-native-devsettings (No Flipper installed)

Issue Description:
Encountered an error when attempting to enable Remote JS Debugging using react-native-devsettings. The following error is thrown:
(NOBRIDGE) ERROR TypeError: null is not an object (evaluating '_reactNative.NativeModules.DevSettings.setIsDebuggingRemotely')

Steps to Reproduce:

Use a React Native project configured with the new architecture and Hermes.
Install and integrate the react-native-devsettings package to handle remote debugging.
Attempt to enable Remote JS Debugging.
Observe the error.

Expected Behavior:
Remote JS Debugging should activate without errors.

Actual Behavior:
Remote JS Debugging fails with the above error message.

Notes:

No Flipper is installed in the project.
Feel free to ask for additional details if needed.

### Steps to reproduce

Use a React Native project configured with the new architecture and Hermes.
Install and integrate the react-native-devsettings package to handle remote debugging.
Attempt to enable Remote JS Debugging.
Observe the error.

Expected Behavior:
Remote JS Debugging should activate without errors.

Actual Behavior:
Remote JS Debugging fails with the above error message.

Notes:

No Flipper is installed in the project.
Feel free to ask for additional details if needed.

### React Native Version

0.76.2

### Output of `npx react-native info`

```text
System:

OS: macOS 15.1
CPU: (8) arm64 Apple M1
Memory: 1.04 GB / 16.00 GB
Shell:
Version: 5.9
Path: /bin/zsh
Binaries:

Node:
Version: 20.5.0
Path: ~/.nvm/versions/node/v20.5.0/bin/node
Yarn:
Version: 3.6.4
Path: ~/.nvm/versions/node/v20.5.0/bin/yarn
npm:
Version: 10.9.0
Path: ~/.nvm/versions/node/v20.5.0/bin/npm
Watchman:
Version: 2024.01.22.00
Path: /opt/homebrew/bin/watchman
Managers:

CocoaPods:
Version: 1.15.2
Path: ~/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:

iOS SDK:
Platforms:
DriverKit 24.1
iOS 18.1
macOS 15.1
tvOS 18.1
visionOS 2.1
watchOS 11.1
Android SDK:
API Levels: 28, 29, 30, 31, 32, 33, 34, 35
Build Tools: 32.0.0, 34.0.0, 35.0.0
System Images:
android-29 | Google APIs ARM 64 v8a
android-29 | Google Play ARM 64 v8a
android-32 | Google APIs ARM 64 v8a
android-32 | Google Play ARM 64 v8a
android-33-ext5 | Google Play ARM 64 v8a
android-34 | Google Play ARM 64 v8a
android-TiramisuPrivacySandbox | Google Play ARM 64 v8a
android-UpsideDownCakePrivacySandbox | Google Play ARM 64 v8a
android-UpsideDownCakePrivacySandbox | Google Play Intel x86_64 Atom
Android NDK: Not Found
IDEs:

Android Studio: 2024.2 AI-242.23339.11.2421.12550806
Xcode:
Version: 16.1/16B40
Path: /usr/bin/xcodebuild
Languages:

Java:
Version: 20.0.2
Path: /usr/bin/javac
Ruby:
Version: 2.7.6
Path: ~/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:

@react-native-community/cli:
Installed: 15.0.1
Wanted: 15.0.1
react:
Installed: 18.3.1
Wanted: 18.3.1
react-native:
Installed: 0.76.2
Wanted: 0.71.0
react-native-macos: Not Found
npmGlobalPackages:

react-native: Not Found
Android:

Hermes Enabled: true
New Arch Enabled: true
iOS:

Hermes Enabled: true
New Arch Enabled: true
```

### Screenshots and Videos

![Simulator Screenshot - iPhone 16 Pro - 2024-11-19 at 15 46 20](https://github.com/user-attachments/assets/6c557e46-a61c-40e0-b63b-78ee1680b5fb)
![Simulator Screenshot - iPhone 16 Pro - 2024-11-19 at 15 46 23](https://github.com/user-attachments/assets/b8bd91d6-00c6-470d-a2b3-7783701588ac)

**Comment by cortinico** [comment]
Hi,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/gusgard/react-native-devsettings/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
