### ISSUE TITLE
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'. > > [CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.

### ISSUE THREAD

**Issue by mdalishanali** [facebook/react-native#47720]
### Description

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.

### Steps to reproduce

Setup the React Native Environment in Windows 11 and download the latest everythings.

### React Native Version

latest version

### Affected Platforms

Build - Windows

### Output of `npx react-native info`

```text
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.
```

### Stacktrace or Logs

```text
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

### Screenshots and Videos

Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.

**Comment by migueldaipre** [comment]
Hey @mdalishanali,

You need to set up Cmake in Android Studio. See https://developer.android.com/studio/projects/install-ndk.

If it doesn't works, please add a reproducer with a valid link
