### ISSUE TITLE
Android build issue moving to 0.76.2

### ISSUE THREAD

**Issue by ajouve** [facebook/react-native#47727]
### Description

I had an error moving to RN 0.76.2 following this helper https://react-native-community.github.io/upgrade-helper/?from=0.74.3&to=0.76.2

I resolved this issue keeping `android.enableJetifier=true` but this should not be a good practice

### Steps to reproduce

1. Upgrade from RN 0.74.3 ro RN 0.76.2
2. Run ./gradlew bundleRelease

### React Native Version

0.76.2

### Affected Platforms

Runtime - Android, Build - MacOS

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 809.80 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: /opt/homebrew/opt/node@20/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.4
    path: /opt/homebrew/opt/node@20/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/ajouve/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 22.0.1
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/ajouve/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.2
    wanted: 0.76.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
/Users/xxx/.gradle/caches/8.10.2/transforms/0fd0166c4f0b7f2b3a94f0420432a518/transformed/material-1.6.1/res/values/values.xml:7497:4: Duplicate value for resource 'attr/actionBarSize' with config 'DEFAULT' and product ''. Resource was previously defined here: com.xxx.xxx.app-mergeDebugResources-79:/values/values.xml:8497: .

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile values resource file /Users/xxx/Developer/xxx/app-native/android/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not add resource (com.android.aaptcompiler.ParsedResource@329c2b83) to table.). Check logs for more details.
```

### Reproducer

https://github.com/react-native-community/reproducer-react-native

**Comment by yurihikari** [comment]
I have the same issue. However, since I use eas and expo, the prebuild command during the EAS build process alway clean the android directory, so even the enableJetifier=true solution isn't a viable temp solution for me, as it won't add that line in the gradle.properties.

**Comment by baptiste-mnh** [comment]
Same probleme here using Expo with the 0.76.2.

**Comment by ahmedfaraz587** [comment]
Same problem

**Comment by migueldaipre** [comment]
Hey, thank you for reporting this.

Please add a valid reproducer for further investigation.

**Comment by cortinico** [comment]
> I resolved this issue keeping `android.enableJetifier=true` but this should not be a good practice

This is caused by one of your library.

Could you share the output of:

```
cd android && ./gradlew androidDependencies
```

We'll be able to isolate the rogue library and update it.

**Comment by cortinico** [comment]
> I'm getting the same error, here is the output of the androidDependencies command

Could you run `cd android && ./gradlew androidDependencies --scan` and share with me the Gradle Scan (is a URL you will get on console)

**Comment by msantang78** [comment]
> > I'm getting the same error, here is the output of the androidDependencies command
> 
> Could you run `cd android && ./gradlew androidDependencies --scan` and share with me the Gradle Scan (is a URL you will get on console)

https://gradle.com/s/bm7xhntu5efug

**Comment by cortinico** [comment]
@msantang78 in your particular project, the offending libraries are:
- `react-native-photo-editor` (here the problem: https://github.com/prscX/react-native-photo-editor/blob/04a120ca8d37336090180f386bc8090311f31c39/android/build.gradle#L50-L52)
- `rn-update-apk` (you will need version 5.x at least https://github.com/mikehardy/react-native-update-apk/releases/tag/v5.0.0)

<img width="738" alt="Screenshot 2024-12-10 at 07 22 36" src="https://github.com/user-attachments/assets/36421a33-6926-4cc1-86a6-a27ed89823fe">

Please either:
- update those dependencies
- re-add the `enableJetifier` property
- reach out to the library maintainer to ask for an update
- use patch-package to circumvent the problem

**Comment by davoam** [comment]
@cortinico can you please share what is necessary to do to find such dependencies which require enabled `enableJetifier`?

**Comment by cortinico** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/3001957?u=612480c64b45755601addb40b5ede4bc7c221a05&amp;v=4&amp;size=80">@cortinico](https://github.com/cortinico?rgh-link-date=2025-02-24T09%3A33%3A29.000Z) can you please share what is necessary to do to find such dependencies which require enabled `enableJetifier`?

I mentioned in the message above.

You should either:

1. update those dependencies
2. re-add the enableJetifier property
3. reach out to the library maintainer to ask for an update
4. use patch-package to circumvent the problem

**Comment by cortinico** [comment]
> But my question is how to find these libraries? I don't know what libraries in my dependencies require `enableJetifier` to be `true`.

You need to either:

1. Search for `com.android.support` inside the `node_modules` (something like `grep -r "com.android.support" node_modules --include=*.gradle` could do the job).
2. Build your project with `cd android && ./gradlew assembleDebug --scan`. Then use the scan link to search for `com.android.support` in the "Dependencies" tab. That will show you which project are still importing the old support library.

**Comment by davoam** [comment]
@cortinico thanks a lot! In our case, `react-native-iap` requires this flag.
