### ISSUE TITLE
[Docs] Showcase should work well on mobile

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#4777]
![12369401_10153311757591188_651648200_o](https://cloud.githubusercontent.com/assets/90494/11801074/22d489f4-a297-11e5-8819-4df5d7c080c0.jpg)

**Comment by dabit3** [comment]
@satya164 Are you picking this up, or can I jump on it? Thanks.

**Comment by satya164** [comment]
@dabit3 I've not started on this. Feel free to jump on it of you want. Also thanks :)

**Comment by dabit3** [comment]
Great, I will. Thanks!

**Comment by satya164** [comment]
@dabit3 :+1:

**Comment by jsierles** [comment]
Merged in #4847. Nice!
