### ISSUE TITLE
The WebView has no java implementation

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#4779]
webview.android.js did not find the corresponding Java implementation

**Comment by satya164** [comment]
@shexiaoheng It's planned, and will probably be in the next release.

**Comment by shexiaoheng** [comment]
@satya164 It will TabBarAndroid?

**Comment by satya164** [comment]
@shexiaoheng Sorry, didn't get you. The next release will probably include a `WebView` component. There is no `TabBarAndroid` component in the works (nor is it planned). You can however use - https://github.com/brentvatne/react-native-scrollable-tab-view

**Comment by shexiaoheng** [comment]
@satya164 Thanks very much , I'll  try to use it .
