### ISSUE TITLE
Android reload very slow

### ISSUE THREAD

**Issue by alvinwoon** [facebook/react-native#4780]
![image](https://cloud.githubusercontent.com/assets/1026383/11806429/0bc49616-a34e-11e5-8ff1-cf8321e29952.png)
Everytime I hit save on IDE and the live reload kicks in, it takes 20 seconds for the changes to show up on the device. This happens regardless of whether I turn on DEV flag or 'debug in chrome'. Some info on my tooling:

RN version: 0.16
Phone: LG4
Android version: 5.1

**Comment by shixy** [comment]
+ 1

**Comment by shixy** [comment]
+1

**Comment by AlexeyToksarov** [comment]
This is a duplicate of https://github.com/facebook/react-native/issues/4672

**Comment by brentvatne** [comment]
This is fixed now!
