### ISSUE TITLE
New 'export default' issue in 0.16

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native#4784]
I can reproduce an issue with using `export default` since upgrading to 0.16.

The following scenario: 

```js
// constants.js 
const constants = {
  fetchStates: {
    LOADING: 'loading'
  }
};
export default constants;

// -------------------------------------------

// In another module
import { fetchStates } from './constants';
console.log(fetchStates.LOADING);
```

Once this code is transformed and run the error message is `undefined is not an object (evaluating '_constants.fetchStates.LOADING')`

What does not seem to work is the following line:

```js
// Does NOT work
import { fetchStates } from './constants';
```

It also does not work with require:

```js
// Does NOT work
const { fetchStates } = require('./constants');
```

This works though:

```js
// Does work
import constants from './constants';
const { fetchStates } = constants;
```

Alternatively using `module.exports = ` instead of `export default ` works too.

These are both not great workarounds, there seems to be something wrong with `export default` in general. I ran into another set of issues when requiring the files from jest tests. The exported object would be nested inside another `default` key.

I tried all I can digging into this and trying to find the root cause but boiling it down to this scenario is as far as I came.

**Comment by gre** [comment]
noticed this too.

workaround is either to `require("./foo").default` or to not use `export default`

**Comment by satya164** [comment]
@pietropizzi

About the first issue, React Native 0.16 uses Babel 6 to transpile, which changed lots of things. Can you try it by just using Babel 6, and if the issue persists, report this issue on Babel's bug tracker?

About the second issue with `require('./module')`, it's how it's supposed work. `default` exports are just named exports with a special name `default`. So you need to do `require('./module').default` instead.

**Comment by pietropizzi** [comment]
An update on this issue:

My aforementioned code:

```js
// constants.js 
const constants = {
  fetchStates: {
    LOADING: 'loading'
  }
};
export default constants;

// -------------------------------------------

// In another module
import { fetchStates } from './constants';
console.log(fetchStates.LOADING);
```

should not actually work according to spec and apparently Babel 5 made it work but Babel 6 is stricter. The right way to do the export is:

```js
// constants.js 
export const fetchStates = {
  LOADING: 'loading'
};

// or

const fetchStates = {
  LOADING: 'loading'
};

export { fetchStates };
```

I changed that and now I can live without `module.exports = ` BUT

Inside of jest tests it still does not work. There the only way to make it work now is to change all the named imports to this:

```js
import * as constants from './constants';
const { fetchStates } = constants;
```

Inside of tests I unfortunately need to use `require` (which I fixed up the way you described) since imports are being hoisted to the top of the file. But that is the only difference. Any ideas here?

**Comment by pietropizzi** [comment]
Closing this, since it is only about the tests. Narrowed it down, find more info here https://github.com/facebook/react-native/issues/3999#issuecomment-164806033

**Comment by ide** [comment]
In summary, Babel 6 implements a stricter but correct behavior. It's sort of a pain to migrate but from personal experience if you move entirely to import/export one thing that's nice is that cycles are less of an issue because there is no more clobbering of `module.exports`; with JS's `import/export` everything is assigned to `exports`.
