### ISSUE TITLE
Tabs are not showing bottom navigation in react-native 0.76.2 with expo

### ISSUE THREAD

**Issue by iahmadhabibx** [facebook/react-native#47879]
### Description

I am using react-native v0.76.2 along with expo and I haven't done any complex code but even with just a simple navigation code, the bottom navigation are not appearing using `Tabs` with `expo-router`

Here is my package.json

```
{
  "name": "court",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "autoprefixer": "^10.4.20",
    "expo": "~52.0.8",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "~4.0.7",
    "expo-splash-screen": "~0.29.11",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.3",
    "expo-web-browser": "~14.0.1",
    "nativewind": "^4.1.23",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.2",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "^3.16.2",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.4",
    "zustand": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.2",
    "react-test-renderer": "18.3.1",
    "tailwindcss": "3.3.2",
    "typescript": "^5.3.3"
  },
  "private": true
}

```

Here is my folder structure:
<img width="224" alt="Screenshot 2024-11-21 at 5 44 34 PM" src="https://github.com/user-attachments/assets/c098a831-a353-45d5-96df-0e18974af8b1">

Here is my tabs _layout.tsx:
<img width="583" alt="Screenshot 2024-11-21 at 5 44 54 PM" src="https://github.com/user-attachments/assets/e1cf5978-789e-4851-88e2-33a3434af118">

Here is my root _layout.tsx:
<img width="585" alt="Screenshot 2024-11-21 at 5 45 08 PM" src="https://github.com/user-attachments/assets/e5d1a7ee-cb16-409a-b052-c4c9cd166016">

### Steps to reproduce

1. yarn start

### React Native Version

0.76.2

### Affected Platforms

Runtime - Android, Runtime - iOS, Runtime - Web

### Output of `npx react-native info`

```text
⚠️ react-native depends on @react-native-community/cli for cli commands. To fix update your package.json to include:


  "devDependencies": {
    "@react-native-community/cli": "latest",
  }
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://github.com/iahmadhabibx

### Screenshots and Videos

<img width="377" alt="Screenshot 2024-11-21 at 10 08 33 PM" src="https://github.com/user-attachments/assets/91323288-6d1a-46b6-8ebe-12b98916eba4">

**Comment by migueldaipre** [comment]
Hey @iahmadhabibx,
Thanks for reporting this issue.

It seems like this issue is actually unrelated to React Native core. Please open this issue against this other repository:

https://github.com/react-navigation/react-navigation/issues

I'll be closing this but feel free to reopen if the other repo points back to us as a issue in the core of React Native.
