### ISSUE TITLE
Is react native's ReactNativeART library ready to use?

### ISSUE THREAD

**Issue by prashanth1509** [facebook/react-native#4789]
ReactNativeART examples are spilled across web but not in react native docs and source code has references.
Is it available for ios and android and if so why isn't documented yet on react native documentation page?

**Comment by skevy** [comment]
We use it on a production app...but I'm pretty sure that there isn't much work being done on it internally.

It does _work_, however :)

@mkonicek can you comment?

**Comment by mkonicek** [comment]
No one is working on it at fb but I believe it's good to go. If anything doesn't work please report issues / send PRs.

You're right it doesn't have any docs which is sad: https://github.com/facebook/react-native/blob/master/Libraries/ART/ReactNativeART.js

If anyone can add docs to that file that would be awesome :)

**Comment by prashanth1509** [comment]
@browniefed I'm following your examples :)

**Comment by getnashty** [comment]
Looks like its actively being worked on a year later (last commit 19 days ago), still no sign in the docs. Would reactArt docs map to this?

**Comment by Obooman** [comment]
🍻  I have created a repo called [react-native-art-doc](https://github.com/react-native-china/react-native-ART-doc).Dear guys you can help me to check it or contribute to the repo. @getnashty @prashanth1509
