### ISSUE TITLE
[Android] PullToRefreshViewAndroid child ListView not scrollable

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#4793]
I have a basic example of a ListView, which has a parent PullToRefreshViewAndroid:

```
        return (
            <PullToRefreshViewAndroid
                refreshing={isRefreshing}
                onRefresh={this.onRefresh}
            >
                <ListView
                    dataSource={races}
                    renderRow={(row) => <Text>{row}</Text>}
                />
            </PullToRefreshViewAndroid>
        );
```

The outcome of this is that pull to refresh works, but the ListView is not scrollable. The only way to fix this is by applying `style={{flex:1}}` to PullToRefreshViewAndroid... Is this a bug or intentional? I'd expect PullToRefreshViewAndroid to take the full height of it's child by default?

If it's a bug, I can potentially submit a PR for this.

**Comment by ide** [comment]
Could you send a PR mentioning in the docs that flex:1 is required?
