### ISSUE TITLE
The RCTInstanceDidLoadBundle notification is sent before loadScript completes loading the JSBundle

### ISSUE THREAD

**Issue by zhutc** [facebook/react-native#47949]
### Description

In the **_loadScriptFromSource** method of **RCTInstance**, the **_reactInstance->loadScript** internally loads the JSBundle asynchronously, which results in the **RCTInstanceDidLoadBundle** notification being sent first. Could this be a bug?

<img width="920" alt="image" src="https://github.com/user-attachments/assets/3c45b429-13af-497f-866a-3f049bb70e7a">

<img width="883" alt="image" src="https://github.com/user-attachments/assets/a393b413-af50-40c6-aea9-5c9350841fdd">

### Steps to reproduce

none

### React Native Version

0.76.3

### Affected Platforms

Runtime - iOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.0.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 81.69 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.4
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.7.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2024.08.19.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.0
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 1.8.0_292
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: true
```

### Stacktrace or Logs

```text
It is not necessary, the application does not crash or fail.
```

### Reproducer

https://github.com/facebook/react-native/blob/v0.76.3/packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm

**Comment by zhongwuzw** [comment]
Yes, I think it's a bug, may fixed in #48082
