### ISSUE TITLE
AwesomeProject(ios) parse issue

### ISSUE THREAD

**Issue by scsidisk** [facebook/react-native#4794]
path/AwesomeProject/node_modules/react-native/React/Base/RCTBridgeModule.h:222:14: Expected '>'

```
222 - (NSArray<id<RCTBridgeMethod>> *)methodsToExport;
```

Xcode 6.3.1
node.js 5.2.0

**Comment by skevy** [comment]
@scsidisk I can't repro tihs...but can you try updating to XCode 7?

**Comment by theoriginalgri** [comment]
"lightweight generics" were introduced with XCode 7, so this is a minimum requirement for react-native

**Comment by skevy** [comment]
:+1

**Comment by skevy** [comment]
Closing this one.
