### ISSUE TITLE
AppState: Is `memoryWarning` event available on Android?

### ISSUE THREAD

**Issue by gredajustyna** [facebook/react-native#47951]
### Description

I want to listen to `memoryWarning` event in my Android app. The [documentation](https://reactnative.dev/docs/0.72/appstate) doesn't state it is available on iOS only, but there was a similar [issue](https://github.com/facebook/react-native/issues/36426) here already. However, it doesn't answer my question. Moreover, an example for the `AppState` in the repo shows it as platform-specific:

```
{
    platform: 'ios',
    title: 'Memory Warnings',
    description:
      'In the IOS simulator, hit Shift+Command+M to simulate a memory warning.',
    render(): React.MixedElement {
      return <AppStateSubscription showMemoryWarnings={true} />;
    },
  },
  ```
  
  Is this event available on Android? I am able to receive some native logs about the memory pressure before my app crashes but nothing coming from RN side. 

### Steps to reproduce

Subscribe to the `AppState.memoryWarning` event, for example:

```
    React.useEffect(() => {
        const memoryWarningSubscription = AppState.addEventListener('memoryWarning', () => {
            console.log('AppState - Memory Warning');
        });

        return () => {
            memoryWarningSubscription.remove();
        };
    }, []);
```

### React Native Version

0.72.0

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.7.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 183.33 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.5
    path: ~/.local/share/mise/installs/node/18.20.5/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: ~/.local/share/mise/installs/node/18.20.5/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK: Not Found
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native:
    installed: 0.72.0
    wanted: 0.72.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```text
none
```

### Reproducer

not required

**Comment by cortinico** [comment]
> Is this event available on Android? I am able to receive some native logs about the memory pressure before my app crashes but nothing coming from RN side

I see that the event is implemented for iOS only, so we should update the docs on reactnative.dev to mention this is not implemented on Android (yet).
