### ISSUE TITLE
When will babel dependency be updated to fix export default class?

### ISSUE THREAD

**Issue by dubert** [facebook/react-native#4798]
In 0.16 release notes under breaking changes:

* Exporting default class that extends a base class won't work due to Babel's [T2694](https://phabricator.babeljs.io/T2694).

This was [fixed](https://github.com/babel/babel/pull/3096) in babel 6.2.2 so upgrading babel should solve the issue.

**Comment by skevy** [comment]
@mkonicek we should get updating to the latest Babel on the release schedule for .17 stable if possible.

**Comment by brentvatne** [comment]
Looks like this was updated in 0.17 -- let me know if this is still an issue.

https://github.com/facebook/react-native/commit/8d347d6add784e8e8e10e42a2645e9dec4df075d
