### ISSUE TITLE
i upgraded my react-native project from 0.68.5 to 0.74.0

### ISSUE THREAD

**Issue by PriyanshuPandey-github** [facebook/react-native#47999]
i upgraded my react-native project from 0.68.5 to 0.74.0 
the ios config comes null
 `"healthChecks": [],
  "platforms": {
    "ios": {},
    "android": {}
  },
  "project": {
    "ios": null,
    "android": {
      "sourceDir": "/Users/test/android",
      "appName": "app",
      "packageName": "com.test",
      "applicationId": "com.test",
      "mainActivity": ".MainActivity"
    }
  }
}`

_Originally posted by @PriyanshuPandey-github in https://github.com/facebook/react-native/issues/38087#issuecomment-2505555553_

**Comment by migueldaipre** [comment]
Hey @PriyanshuPandey-github,

Please follow our standard template [here](https://github.com/facebook/react-native/issues/new/choose) to open a valid issue
