### ISSUE TITLE
Support for Camera Roll

### ISSUE THREAD

**Issue by JoeStanton** [facebook/react-native#48]
A comment in the image component references support for local assets that are part of the bundle, but also other places such as the **camera roll**.

https://github.com/facebook/react-native/blob/6e04a3c964848c3beb0966dcfb54fff370ab68d7/Libraries/Components/Image/Image.ios.js#L30

Does this mean I can feed in URL's of the scheme `assets-library://`, or is this not supported? As the component currently reports that the image is not found. If it isn't, would I need to implement it in `RCTConvert` similarly to Gif support?

eg.

``` jsx
  <Image style={styles.icon} source={ix('assets-library://asset/asset.JPG?id=x&ext=JPG')}  />
```

**Comment by srameshr** [comment]
@vjeux I have a catch here. If I load a GIF from asset library with a path like: ```assets-library://asset....&ext=GIF```, then I just end up getting the first frame but not the whole GIF. How do I get it as a GIF image so I can display it as a playing GIF with the ```Image``` tag.
