### ISSUE TITLE
NetInfo.fetch().done gives undefined reach in iOS

### ISSUE THREAD

**Issue by DuntyVinayRaj** [facebook/react-native#4802]
When I use NetInfo.fetch().done to find out the type of reach in iOS which is supposed to be wifi, cell, none or unknown, I always found reach to be undefined. Digging a bit into it, I noticed that getCurrentReachability method exported from RCTNetInfo.m sends status with key 'network_info' where as this is accessed as resp.network_reachability in NetInfo.js. 

As I changed the NetInfo.js to access resp.network_info, reach worked properly giving wifi/cell/none/unkniwn values. Please check.

Have attached screenshots for more clarity. The top one is the code from NetInfo.js fetch() function where a call is made to getCurrentreachability and resp.network_reachability is passed as reach.

The second one is the RCTNetInfo.m screen shot where the value from getCurrentReachability is sent with "network_info" key.
  
<img width="370" alt="screen shot 2015-12-16 at 2 26 28 am" src="https://cloud.githubusercontent.com/assets/4964340/11823867/8031bf76-a39c-11e5-85a0-47211a6beadc.png">
<img width="551" alt="screen shot 2015-12-16 at 2 26 39 am" src="https://cloud.githubusercontent.com/assets/4964340/11823869/86464896-a39c-11e5-98e2-caa61fdd83ae.png">

**Comment by christopherdro** [comment]
I think you may have a old version of React Native installed. This was fixed with the following commit.
https://github.com/facebook/react-native/commit/53403423ca281c7961fb8b7d5e99ed04c7d65748
