### ISSUE TITLE
onRequestClosed not called in iOS pageSheet Modal

### ISSUE THREAD

**Issue by jacolack** [facebook/react-native#48030]
### Description

I have noticed a regression with the "New Architecture". In iOS, the `pageSheet` `presentationStyle` usually calls the `onRequestClose` callback when the user "swipes down" on the modal. This is no longer the case. I cannot therefore get the modal to even dismiss.

### Steps to reproduce

Here is a snack: https://snack.expo.dev/@jacolack/modal?platform=ios

Simply set the "Expo" version to 52.0.0 to reproduce:

Tap the button to show the Modal. 
Try to swipe down on the modal to hide it.
You cannot.

Set the "Expo" version to 51.0.0 to see that it does work, therefore this is a regression.

### React Native Version

0.76.3

### Affected Platforms

Runtime - iOS

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

https://snack.expo.dev/@jacolack/modal?platform=ios

**Comment by zhongwuzw** [comment]
May fixed in #48037.
