### ISSUE TITLE
Keyboard listener is not getting callback on Keyboard hide event on Google Pixel 8 pro with Android 15

### ISSUE THREAD

**Issue by dev1038** [facebook/react-native#48072]
### Description

Keyboard listener is not getting callback on Keyboard hide event on Google Pixel 8 pro with Android 15.

### Steps to reproduce

1. Install android application with targetSDK=34 on Google Pixal 8 Pro(Android 15/SDK 35)
2. Launch the keyboard from edit text, in react-native ui.
3. keep the log in keyboardDidShow/keyboardDidHide callback for below code to understand the call flow.
    Keyboard.addListener('keyboardDidShow', onKeyboardDidShow);
    Keyboard.addListener('keyboardDidHide', onKeyboardDidHide);
    
    We are not getting keyboardDidHide logs, when keyboard is not shown.

### React Native Version

0.70.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 106.18 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.2.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    Watchman: 2024.07.08.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2023.3 AI-233.14808.21.2331.11926650
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.24 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: ^0.70.5 => 0.70.15 
    react-native-macos: ^0.63.43 => 0.63.43 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Stacktrace or Logs

```text
No call back logs in method keyboardDidHide observed when hide keyboard.
```

### Reproducer

NA

**Comment by Isaccobosio** [comment]
@dev1038 I'm having same issue!
Did you find any solution? I noticed that `keyboardDidShow` event is fired twice instead.
I'm thinking about to get the API level of the device and set a specific rule for that.. which sounds crazy to me but I have no choices.
Do you have any better suggestion?

**Comment by Isaccobosio** [comment]
I managed the situation using the device info `getApiLevel` API.
Based on the fact that the keyboardDidShow event is fired twice for devices with API level >= 35, this is what I did:

```ts
const handleKeyboardShow = ({ endCoordinates }: KeyboardEvent) => {
    if (apiLevel && apiLevel >= 35) {
      // android 15 and above does not fire keyboardDidHide event. They fire keyboardDidShow twice
      // once with keyboard height 0 (or less than maxKeyboardHeight) and once with actual keyboard height
      const currentKeyboardHeight = endCoordinates?.height ?? 0;
      const _maxKeyboardHeight = currentKeyboardHeight > maxKeyboardHeight ? currentKeyboardHeight : maxKeyboardHeight;
      setMaxKeyboardHeight(_maxKeyboardHeight);
      setIsKeyboardVisible(_maxKeyboardHeight === currentKeyboardHeight);
    } else {
      setIsKeyboardVisible(true);
    }
};
```

**Comment by Aparna-Pushpay** [comment]
I'm experiencing the same issue, and I think it's affecting the `keyboardHidesTabBar` prop in @react-navigation/bottom-tabs
