### ISSUE TITLE
Image onLoad not fired on Android

### ISSUE THREAD

**Issue by seb0zz** [facebook/react-native#4807]
I am currently using version 0.16.0 of react-native. The `onLoad` prop for images on iOS works like a charm. Strange thing is that on Android the callback does not get executed. Also `onLoadStart` and `onLoadEnd` do not work for me on Android. Don't know if any example could is needed for this one, should be just including in `Image` into a react native `Component`, add an `onLoad` handler and run it on Android.

**Comment by theoriginalgri** [comment]
Is this a duplicate of #4704?

**Comment by seb0zz** [comment]
Yes, duplicate of #4704
