### ISSUE TITLE
Has anyone used UI Testing with react native?

### ISSUE THREAD

**Issue by wootwoot1234** [facebook/react-native#4808]
Has anyone used UI Testing with react native?  I want to use Snapshot (part of Fastlane) to save my screenshots but when I try to record my clicks in the UI Test I get code that looks like this:

    app/*@START_MENU_TOKEN@*/.otherElements["    \Ue00e Getting Started \Ue00c   \Ue00e Unlimited Foods \Ue00c   \Ue00e Limited Foods \Ue00c "].otherElements["  \Ue00e Getting Started \Ue00c"]/*[[".otherElements[\"       \\Ue00e   \\Ue004   \\Ue00d   \\Ue006     Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c  \"]",".otherElements[\"      \\Ue00e   \\Ue004   \\Ue00d   \\Ue006     Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c  \"]",".otherElements[\"     \\Ue00e   \\Ue004   \\Ue00d   \\Ue006     Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".otherElements[\"    \\Ue00e   \\Ue004   \\Ue00d   \\Ue006     Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".otherElements[\"    Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".otherElements[\"   Info       \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".otherElements[\"     \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".scrollViews.otherElements[\"    \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]",".otherElements[\"   \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c\"].otherElements[\"  \\Ue00e Getting Started \\Ue00c\"]",".otherElements[\"  \\Ue00e Getting Started \\Ue00c\"]",".otherElements[\"    \\Ue00e Getting Started \\Ue00c   \\Ue00e Unlimited Foods \\Ue00c   \\Ue00e Limited Foods \\Ue00c \"]"],[[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6],[-1,4,5],[-1,3,4],[-1,2,3],[-1,1,2],[-1,0,1]],[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6],[-1,4,5],[-1,3,4],[-1,2,3],[-1,1,2]],[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6],[-1,4,5],[-1,3,4],[-1,2,3]],[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6],[-1,4,5],[-1,3,4]],[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6],[-1,4,5]],[[-1,10,8],[-1,7,8],[-1,6,7],[-1,5,6]],[[-1,10,8],[-1,7,8],[-1,6,7]],[[-1,10,8],[-1,7,8]],[[-1,9],[-1,8]]],[0,0]]@END_MENU_TOKEN@*/.tap()

and it won't run, it gives errors like:

    Invalid escape sequence in literal

**Comment by wootwoot1234** [comment]
Ok, thanks.  I asked the question here:

http://stackoverflow.com/questions/34302710/has-anyone-used-ui-testing-with-react-native

**Comment by ultrabook** [comment]
Have you tried changing upper case U to lower case? 
like `\ue00e Getting Started \ue00c`

**Comment by wootwoot1234** [comment]
@ultrabook Thanks for the idea.  I tried that just now and unfortunately it didn't help.
