### ISSUE TITLE
Early JsError: Turbo Module Registry.getEnforcing (...): 'PlatformConstants' could not be found. Verify that a module by this name is registered in the native binary. Bridgeless mode: true. Turbo Module interop: true. Modules loaded: ("NativeModules":["TurboModules: "NotFound": ["NativePerformance ObserverCxx","Native PerformanceCxx","PlatformConstants")),

### ISSUE THREAD

**Issue by xiaowen123456789** [facebook/react-native#48108]
### Description

![WechatIMG11](https://github.com/user-attachments/assets/5c998041-6339-4cba-ad5a-786cd056a4b1)

{
  "name": "FalconApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "build:android:release": "cd android && ./gradlew assembleRelease",
    "build:android:aab": "cd android && ./gradlew bundleRelease",
    "clean": "react-native start --reset-cache",
    "ios": "react-native run-ios",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "format": "prettier --write .",
    "lint:fix": "eslint . --fix",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-community/netinfo": "^11.4.1",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/stack": "^6.4.1",
    "@reduxjs/toolkit": "^2.3.0",
    "@shopify/react-native-skia": "^1.6.0",
    "axios": "^1.7.7",
    "i18next": "^24.0.0",
    "native-base": "^3.4.28",
    "react": "18.3.1",
    "react-i18next": "^15.1.1",
    "react-native": "0.76.1",
    "react-native-ble-plx": "^3.2.1",
    "react-native-camera-kit": "^14.1.0",
    "react-native-device-info": "^14.0.0",
    "react-native-gesture-handler": "^2.20.2",
    "react-native-image-picker": "^7.1.2",
    "react-native-localize": "^3.3.0",
    "react-native-reanimated": "^3.16.1",
    "react-native-reanimated-carousel": "4.0.0-alpha.12",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^3.35.0",
    "react-native-svg": "^15.8.0",
    "react-native-svg-transformer": "^1.5.0",
    "react-native-vector-icons": "^10.2.0",
    "react-native-webview": "^13.12.3",
    "zustand": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.0",
    "@react-native-community/cli-platform-android": "15.0.0",
    "@react-native-community/cli-platform-ios": "15.0.0",
    "@react-native/babel-preset": "0.76.1",
    "@react-native/eslint-config": "0.76.1",
    "@react-native/metro-config": "0.76.1",
    "@react-native/typescript-config": "0.76.1",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "codegenConfig": {
    "name": "AppSpecs",
    "type": "modules",
    "jsSrcsDir": "specs",
    "android": {
      "javaPackageName": "com.sampleapp.specs"
    }
  }
}

### Steps to reproduce

1.Importing C library  android/app/src/main/jni/CMakeLists.txt.  OnLoad.cpp
set(CL_SDK ../../../../../shared/cl)

target_include_directories(${CMAKE_PROJECT_NAME} PUBLIC
    ${CL_SDK}/include
    ${CL_SDK}/include/QtCore
    ${CL_SDK}/include/QtGui
    ${CL_SDK}/include/QtWidgets
)
target_link_directories(${CMAKE_PROJECT_NAME} PUBLIC
    ${CL_SDK}/lib
)
target_link_libraries(${CMAKE_PROJECT_NAME}
    Qt5Core_${ANDROID_ABI} Qt5Gui_${ANDROID_ABI} cl_canvas_${ANDROID_ABI}
)

OnLoad.cpp 
  if (name == NativeSampleModule::kModuleName) {
    return std::make_shared<NativeSampleModule>(jsInvoker);
 }

2. In the shared directory NativeSampleModule.cpp use
#include "NativeSampleModule.h"
#include <QString>
#include <QDebug>
#include "cl/CanvasScene.h"
#include "cl/CanvasViewport.h"

namespace facebook::react {

NativeSampleModule::NativeSampleModule(std::shared_ptr<CallInvoker> jsInvoker)
    : NativeSampleModuleCxxSpec(std::move(jsInvoker)) {}

std::string NativeSampleModule::reverseString(jsi::Runtime& rt, std::string input) {
  return std::string(input.rbegin(), input.rend());
}
std::string NativeSampleModule::testMethod(jsi::Runtime& rt, std::string input) {
    return std::string(input.rbegin(), input.rend());
}

std::string NativeSampleModule::getBataData(jsi::Runtime& rt,std::string input) {
    cl::canvas::GraphicsScene scene;
    scene.setSize(400, 400);
    scene.addRect(10, 10, 100, 100);
    scene.addEllipse(120, 10, 100, 100);
    cl::canvas::GraphicsViewport v;
    v.setScene(&scene);
    // std::cout << v.toSvg().toStdString() << std::endl;

    return std::string(input.rbegin(), input.rend());
}

} // namespace facebook::react
3.Use NativeSampleModule.ts in the specs directory
import {TurboModule, TurboModuleRegistry} from 'react-native';

export interface Spec extends TurboModule {
  readonly reverseString: (input: string) => string;
  readonly testMethod: (input: string) => string;
  readonly getBataData: (input: string) => string;
}

export default TurboModuleRegistry.getEnforcing<Spec>(
  'NativeSampleModule',
);
4.package.json
 "codegenConfig": {
    "name": "AppSpecs",
    "type": "modules",
    "jsSrcsDir": "specs",
    "android": {
      "javaPackageName": "com.sampleapp.specs"
    }
  }

### React Native Version

0.76.1

### Affected Platforms

Runtime - Android, Runtime - iOS

### Areas

TurboModule - The New Native Module System

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 103.89 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.4
    path: ~/.nvm/versions/node/v18.20.4/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.20.4/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.4/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "30"
      - "31"
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12550806
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.0
    wanted: 15.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.1
    wanted: 0.76.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Early JsError: Turbo Module Registry.getEnforcing (...): 'PlatformConstants' could not be found. Verify that a module by this name is registered in the native binary. Bridgeless mode: true. Turbo Module interop: true. Modules loaded: ("NativeModules":["TurboModules: "NotFound": ["NativePerformance ObserverCxx","Native PerformanceCxx","PlatformConstants")),
```

### Reproducer

https://github.com/facebook/react-native

**Comment by cortinico** [comment]
Duplicates https://github.com/facebook/react-native/issues/47352
