### ISSUE TITLE
Installing yoga 0.0.0 podspec not using versions

### ISSUE THREAD

**Issue by FrederickEngelhardt** [facebook/react-native#48107]
### Description

Yogo podspec seems to be using 0.0.0 for its version when yoga 3.x.x is expected for react native 0.74.5 to 0.76.3. Is this expected for the podspec to have a 0.0.0 version? 

### Steps to reproduce

1. Install a fresh clone of react native
2. run pod install (with no pods installed otherwise delete the iOS/Pods folder).

### React Native Version

0.76.3

### Affected Platforms

Build - MacOS

### Output of `npx react-native info`

```text
N/a
```

### Stacktrace or Logs

```text
When running pod install I always see 


Installing Yoga (0.0.0)
```
```


### Reproducer

https://github.com/FrederickEngelhardt/react-native-issue-yoga-0-0-0/tree/main/ReproducerApp

### Screenshots and Videos

![20241204_180839](https://github.com/user-attachments/assets/a3950c20-9a87-4d78-9d4d-ce93294881fe)

**Comment by NickGerleman** [comment]
The Yoga version built as part of RN is versioned independently of OSS Yoga releases (its whatever commit matches in the monorepo). So it makes sense that it doesn't snap to Yoga public versions.

I'm not sure if there is any consequence of it not e.g. snapping to RN versions though (like if that has any potential to cause stale build or the like).

There was also some recent change to expose the headers from Yoga to full app, which may get weird if another library brings in public version of Yoga for its own use.

**Comment by cortinico** [comment]
Closing as answered

**Comment by FrederickEngelhardt** [comment]
I guess the consequence could be when looking at the podfile if someone required yoga at a specific version it could pull in the public version on top of the react native version even if they were equivalent. 

To me it just looks weird having a 0.0.0 version install. Makes sense though if this is not a direct copy of the public library.

Thanks for clarifying 👍
