### ISSUE TITLE
use Navigator navigationBar props has a warning when I upgrade to 0.16 on android

### ISSUE THREAD

**Issue by 362228416** [facebook/react-native#4810]
Warning: cloneWithProps(...) is deprecated.......

<Navigator
                        
                        renderScene={this.renderScene}
                        initialRoute={{
                        component: ..,
                        navigationBar: <View></View>
                    }}/>

**Comment by ide** [comment]
This might be as simple as converting it to use cloneElement but please thoroughly test.

**Comment by 362228416** [comment]
how disabled warning message ?

**Comment by giacomorebonato** [comment]
Now react-native breaks because cloneWithProps has been removed https://facebook.github.io/react/blog/2016/04/07/react-v15.html

**Comment by lacker** [comment]
AFAICT `Navigator` is functional in master now so I believe this issue has been resolved. I am going to close this issue but if there is still a problem here feel free to reopen it.
