### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'GLOBAL.Text...

### ISSUE THREAD

**Issue by jayli** [facebook/react-native#4811]
hi

I can't run the 'HelloWorld' successfully. I don't know what's wrong. 

I have just installed npm@2.14.7 node@4.2.3  react-native-cli@0.1.7 xcode@7.1.1. And I have initialized a new prject with `react-native init HelloWorld` without any error. Then hit run in Xcode.  It shows me this:

![](https://gw.alicdn.com/tps/TB15hAmKVXXXXbTXpXXXXXXXXXX-602-992.png)

    TypeError: undefined is not an object (evaluating 'GLOBAL.Text = {
    get defaultProps(){
    throw getInvalidGlobalUseError('Text');}}')

This file throw an exception:

	node_modules/react-native/Libraries/JavaScriptAppEngine/polyfills/document.js.
	
![](https://gw.alicdn.com/tps/TB1SVMAKVXXXXXUXXXXXXXXXXXX-797-572.png)

'GLOBAL' is undefined? `node_modules/react-native/package.json` shows version is 0.17.0-rc. Is it the correct version? How to fix this？

**Comment by jayli** [comment]
[here](http://stackoverflow.com/questions/34112110/upgrade-to-react-native-0-16-error) is the solution

I reinstall the '[preset-react](http://babeljs.io/docs/plugins/preset-react/)', remove the `"presets": ["es2015"]` from `~/.babelrc`. Then add `"presets": ["react"]` to this file.

**Comment by natdm** [comment]
I'm having the exact same issue, though I was always able to run projects fine in the past. I don't have a ~/.babelrc folder. Am I supposed to have created one? Is that something new?

**Comment by jayli** [comment]
@natdm 

You can create a new file called `.babelrc`

**Comment by natdm** [comment]
that worked, thanks!

**Comment by herby** [comment]
I wanted to have tests, processed by babel, as well.
I ended up with this helper file `mkrnbabelpreset.js` having in the project root (ugly, but works):

```js
'use strict';

const fs = require('fs');

const rnBabelRc = JSON.parse(
    fs.readFileSync(
        require.resolve("react-native/packager/react-packager/.babelrc"),
        {encoding: 'utf-8'}
    )
);

function rnPlugin (name) {
    return "11require('babel-plugin-" + name + "')99";
}

const myPlugins = rnBabelRc.plugins.map(each =>
    typeof each === "string" ?
        rnPlugin(each) :
        [rnPlugin(each[0])].concat(each.slice(1))
);

const stringifiedPlugins = JSON.stringify({plugins: myPlugins}, null, 4)
    .replace(/"11/g, "").replace(/99"/g, "");
fs.writeFileSync("node_modules/react-native/babel-preset.js", `module.exports = ${stringifiedPlugins};`);
```

running it once (or before mocha in npm test specification) created babel preset that copies react-native's .babelrc. You should then have your root `.babelrc` as this:

```json
{
	"presets": ["react-native/babel-preset"]
}
```

**Comment by herby** [comment]
Put his in your `.babelrc`:

```json
{
	"extends": "./react-native/packager/react-packager/.babelrc"
}
```

And that's it - you copy react-native settings for your whole project (so no conflict).
