### ISSUE TITLE
[DeviceEventEmitter] How to use keyboard easing

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#4812]
```
DeviceEventEmitter.addListener('keyboardWillShow', this._keyboardWillShow.bind(this));
```

when `keyboardWillShow` event fired.It will pass an argument with an `easing` attribute inside.
just like 
```
_keyboardWillShow = (e) => {
    // e.easing === 'keyboard';
}
```

so.How to do animtion with `keyboard` easing,or this easing attribute has no usage at all?
If this easing attribute has nothing to do with Animated easing,what`s the point of passing it.

**Comment by neciu** [comment]
:+1:

**Comment by magicismight** [comment]
finally.
I found out how to use `keyboard` easing.
It\`s not for js animation: Animated 
It\`s used for native animation: LayoutAnimation

for example
```
DeviceEventEmitter.addListener('keyboardWillShow', e => {
        LayoutAnimation.configureNext(LayoutAnimation.create(
            e.duration,
            LayoutAnimation.Types[e.easing]
        ));
        this.setState({
            bottom: e.endCoordinates.height
        });
});
```
This works fine on IOS, haven`t have it tested on Android yet.

There should be a document about this.

**Comment by vaibhawc** [comment]
This works. But I have a listview above the keboard and listview does not respect layoutanimation.
#677 
So I need to know what must be done to mimic to easing of the keyboard in the animated api.
