### ISSUE TITLE
How to sperate reactnative.bundle file into 2 part?

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#4813]
I use reactPackager to bundle my rn project, and find that the bundle file is > 1MB , how can i sperate the bundle file into 2 part.One of them include all of react-native related resource and core coding, the anther is only my business codes, not include any reactnative codes.
So i can modify my native load component, before load remote server bundle file, use text merge them into a full file for running.

**Comment by brentvatne** [comment]
Hi! This is a work in progress but isn't ready yet. I'm not working on this myself so I can't give a timeline but it is being worked on within FB :)
