### ISSUE TITLE
react_native_assert failure: link_.status != Status::Running && "Surface must not be running."

### ISSUE THREAD

**Issue by L0NG4R3S** [facebook/react-native#48149]
### Description

I recently integrated React Native into my native Swift app, it worked normally with version 0.75.4
But I updated to React Native 0.76.3 to be able to use the new architecture.
After the update, when building, the app crashes with the error: "Surface must not be running".

### Steps to reproduce

Integrate with existing Swift App following docs: https://reactnative.dev/docs/integration-with-existing-apps
Upgrade to React 0.76.3: https://react-native-community.github.io/upgrade-helper/?from=0.75.4&to=0.76.3

1. Clone project: https://github.com/L0NG4R3S/SurfaceErrorRepository
2. Run yarn start
3. yarn install && cd ios && pod install
4. yarn ios or open ReproducerApp.xcworkspace in xcode and run

### React Native Version

0.76.3

### Affected Platforms

Runtime - iOS

### Areas

TurboModule - The New Native Module System

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1.1
  CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Memory: 227.51 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.3
    path: ~/.nvm/versions/node/v21.7.3/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v21.7.3/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v21.7.3/bin/npm
  Watchman:
    version: 2024.10.21.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.0
    wanted: ^16.0.0
  react:
    installed: 19.0.0
    wanted: 19.0.0
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos:
    installed: 0.76.4
    wanted: ^0.76.4
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1206 09:11:06.964253 89726976 SurfaceHandler.cpp:318] react_native_assert failure: link_.status != Status::Running && "Surface must not be running."
Assertion failed: (link_.status != Status::Running && "Surface must not be running."), function setUIManager, file SurfaceHandler.cpp, line 318.
```

### Reproducer

https://github.com/L0NG4R3S/SurfaceErrorRepository

### Screenshots and Videos

<img width="1106" alt="Captura de Tela 2024-12-06 às 09 29 05" src="https://github.com/user-attachments/assets/76b07522-d173-4868-8730-122291d431a8">

**Comment by cortinico** [comment]
> But I updated to React Native 0.76.3 to be able to use the new architecture.

I'd suggest you first update to 0.76.3 **without** the New Architecture and then enable it. Otherwise it will be hard to understand what is causing the failure

**Comment by chinamcafee** [comment]
I met the same issue, perhaps react native can't support React 19 right now. 

But I wonder if there is a roadmap when React Native can fully support React 19.
