### ISSUE TITLE
Cause: ndk-build binary cannot be found, check if you've set $ANDROID_NDK environment variable correctly or if ndk.dir is setup in local.properties

### ISSUE THREAD

**Issue by eva1943** [facebook/react-native#4816]
Hello! 
I had set ndk.dir in local.properties and also set $ANDROID_NDK in system path.
Also show ndk-build cannot be found.

<img width="526" alt="bd57c86c-65aa-419f-ac6f-1e356fae61d6" src="https://cloud.githubusercontent.com/assets/4629156/11838526/a38d0e2c-a422-11e5-91c0-b841b987705e.png">

<img width="570" alt="3e883b3c-39c5-4294-acb3-676e103a8fd4" src="https://cloud.githubusercontent.com/assets/4629156/11838550/d224383c-a422-11e5-810a-8820de62ca50.png">

**Comment by guizmaii** [comment]
Is your local.properties file next to the ```gradlew``` file (in the source tree) ?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by skv-headless** [comment]
`local.properties` don't work for me, but I launched studio from terminal `./Android\ Studio.app/Contents/MacOS/studio` and it found `ANDROID_HOME` variable

**Comment by RajuPedda** [comment]
It got worked for me by setting up the environment variable as "ANDROID_NDK_HOME" to the located NDK(in my case it is - C:\Android\android-ndk-r10e-windows-x86_64\android-ndk-r10e).
