### ISSUE TITLE
iOS debugging only works with a configuration called "Debug"

### ISSUE THREAD

**Issue by bhandanyan-nomad** [facebook/react-native#48168]
### Description

The [code that adds the build settings for enabling the hermes debugger](https://github.com/facebook/react-native/blob/4165884b700341ba549ed8385480fd98128e7bb1/packages/react-native/scripts/cocoapods/utils.rb#L47-L50) will only run if the configuration is called (or maybe contains) "Debug" 

### Steps to reproduce

Reproducer with "Debug" scheme renamed to "Local"
https://github.com/benhandanyan/react-native-debugger-local-bug

1. Clone the reproducer locally
2. Install dependencies and pods
3. Run the ios app with `yarn ios`
4. Attempt to open the debugger

### React Native Version

0.76.4

### Output of `npx react-native info`

```text
npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 15.1.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 1.10 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.09.30.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/benjamin/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /Users/benjamin/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.4
    wanted: 0.76.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```
```


### Screenshots and Videos

_No response_

**Comment by bhandanyan-nomad** [comment]
I [previously reported this issue](https://github.com/facebook/react-native/issues/45265) as a problem with an upgrade from v0.72 to 0.73. Prior to version 0.73 I could debug my application with my "Local" configuration

**Comment by bhandanyan-nomad** [comment]
Based on some quick local testing, it looks like it would be possible to use `config.type` instead of `config.name` to add certain configurations. With my custom configs, none of which are named debug or release, they all have `config.type` values of either "debug" or "release". If there are other settings that are dependent on specific configuration names, there could be other bugs or issues beyond just the native debugger impacted as well.

**Comment by yuvashrikarunakaran** [comment]
post_install do |installer|
  react_native_post_install(installer)

  # Check the build configuration
  installer.pods_project.targets.each do |target|
    if target.name == 'React-Core'
      # Ensure Hermes is enabled for custom schemes
      target.build_configurations.each do |config|
        if config.name == 'Debug' || config.name == 'Local' # Add any schemes you want
          config.build_settings['ENABLE_HERMES'] = 'YES'
        end
      end
    end
  end
end
Step 3: Clean Build and Rebuild
Clear Derived Data: Sometimes, Xcode can cache settings, which might cause issues. You can clean your build folder by running:

bash
Copy code
rm -rf ~/Library/Developer/Xcode/DerivedData/*
Reinstall Pods: Reinstall your CocoaPods to make sure all configurations are applied:

bash
Copy code
cd ios
pod install --repo-update
cd ..
Clear Metro Bundler Cache: Sometimes caching causes issues with Hermes. Clear the Metro cache by running:

bash
Copy code
npx react-native start --reset-cache
Rebuild the App: After performing the above steps, run your app again:

bash
Copy code
yarn ios

**Comment by KevinSheedy** [comment]
Hi @bhandanyan-nomad 
Are you aware of a workaround for this on react-native v0.73.10? Can it be enabled explicitly?
When I try run an app using any XCode config not named exactly "Debug" it fails with an error:

```
Undefined symbol: facebook::hermes::inspector_modern::chrome::CDPHandler::registerCallbacks(std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)>, std::__1::function<void ()>)

```
Thanks

**Comment by cipolleschi** [comment]
the issue is fixed in the supported versions of react native (0.76 --> 0.78). Version 0.73 is out of support and we highly recommend to upgrade.
That said, you should be able to patch react native applying changes similar to the one [in this commit](https://github.com/facebook/react-native/commit/eda4f185b381f7569a1029b7697f9a1c8bc6d108). The codebase might have changed, so it is unlikely that you can apply the commit as it is.
