### ISSUE TITLE
ReferenceError: Can't find variable: require( line 1 in the generated bundle)

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#4817]

**Comment by shexiaoheng** [comment]
I execute the following command to create a new project , an error has occurred : "ReferenceError: Can't find variable: require( line 1 in the generated bundle) "
```shell
$ npm install -g react-native-cli
$ react-native init Test
$ cd Test
$ react-native run-android
```

**Comment by ahanriat** [comment]
@shexiaoheng which version of Android are you using ?

**Comment by shexiaoheng** [comment]
@ahanriat yes , it's 6.0 . I now use Android5.1 no problem , Thanks.

**Comment by yychun1217** [comment]
@shexiaoheng I am experiencing the same issue as well. Have no luck to solve it

**Comment by shexiaoheng** [comment]
@yychun1217 using Android 5.1 or Android 5.0

**Comment by gauravbhusare** [comment]
How to change to android 5.1

**Comment by shexiaoheng** [comment]
@gauravbhusare use Android 5.1 operating system

**Comment by ZakosDim** [comment]
I face the same problem at android 6. Tha means android 6 is not supported?
