### ISSUE TITLE
Text outputs raw HTML-encoded string when set via variable

### ISSUE THREAD

**Issue by theoriginalgri** [facebook/react-native#4818]
The ```Text``` Element outputs the raw HTML-encoded string when it was set via a variable:

```
render() {
  var text = "Escape Test: &copy;";
  return <Text>{text} &copy;</Text>
}
```

Displays: ```Escape Test: &copy; ©"```
Affects both iOS and Android with RN master (as of 0.16.0+).

**Comment by ide** [comment]
This is expected and desired behavior. You'll need to run an HTML entity decoder yourself.
