### ISSUE TITLE
Lots of Warnings after upgrading react-native version 0.76.3

### ISSUE THREAD

**Issue by trantuandatvietnam** [facebook/react-native#48194]
### Description

After upgrading expo from version 51 to 52, which requires upgrading react-native to version 0.76.3. When I open the app, a lot of warnings are displayed, making the app seem to hang for a while. This error comes from the react-native library
![image](https://github.com/user-attachments/assets/58fb5c2a-f86b-4bd4-847c-fe1fa7309d28)

### Steps to reproduce

1. Install react-native version 0.76.3
2. Run app

### React Native Version

0.76.3

### Output of `npx react-native info`

```text
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 12th Gen Intel(R) Core(TM) i3-12100
  Memory: 1.27 GB / 15.72 GB
Binaries:
  Node:
    version: 20.10.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
  Yarn:
    version: 1.22.22
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.3
  npm:
    version: 10.2.3
    version: 10.2.3
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
  Watchman: Not Found
SDKs:
SDKs:
  Android SDK: Not Found
  Android SDK: Not Found
  Windows SDK: Not Found
  Windows SDK: Not Found
IDEs:
IDEs:
  Android Studio: AI-233.14808.21.2331.11709847
  Visual Studio: Not Found
Languages:
  Java:
    version: 19.0.1
    path: /c/Program Files/Common Files/Oracle/Java/javapath/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: ^15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.76.5 is now available (your project is running on v0.76.3).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.76.5
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.76.3&to=0.76.5
info For more info, check out "https://reactnative.dev/docs/upgrading?os=windows".
```

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/490a77e6-f0fe-44be-b796-ba008ff3ceff)

**Comment by trantuandatvietnam** [comment]
I upgraded to the latest version of React-native but still having the same problem

**Comment by cortinico** [comment]
This doesn't happen on a empty project.

> * Install react-native version 0.76.3
> * Run app

Please provide a valid reproducer

**Comment by trantuandatvietnam** [comment]
This is a company project and I cannot provide further information. My problem was after I upgraded expo from version 51 to 52, which required updating version of react native. Specifically, my package.json file looks like this:
"dependencies": {
    "@bugsnag/expo": "^49.0.0",
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-native-firebase/analytics": "^17.3.2",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/messaging": "^17.3.2",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@react-navigation/stack": "^6.4.1",
    "@shopify/flash-list": "1.6.4",
    "deprecated-react-native-prop-types": "^4.0.0",
    "expo": "^51.0.32",
    "expo-application": "~5.9.1",
    "expo-auth-session": "~5.5.2",
    "expo-barcode-scanner": "~13.0.1",
    "expo-blur": "~13.0.2",
    "expo-brightness": "~12.0.1",
    "expo-camera": "^15.0.15",
    "expo-constants": "~16.0.2",
    "expo-crypto": "~13.0.2",
    "expo-device": "~6.0.2",
    "expo-file-system": "~17.0.1",
    "expo-haptics": "~13.0.1",
    "expo-image": "^1.12.15",
    "expo-intent-launcher": "~11.0.1",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-local-authentication": "~14.0.1",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-notifications": "^0.28.16",
    "expo-random": "~14.0.1",
    "expo-secure-store": "~13.0.2",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "^0.25.24",
    "expo-web-browser": "~13.0.3",
    "intl": "^1.2.5",
    "lodash": "^4.17.21",
    "metro-react-native-babel-transformer": "^0.77.0",
    "native-base": "^3.1.0",
    "numeral": "^2.0.6",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-intl": "^6.1.1",
    "react-native": "0.74.5",
    "react-native-drax": "^0.10.2",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-get-random-values": "~1.11.0",
    "react-native-maps": "1.18.0",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "13.1.2",
    "react-native-pager-view": "6.3.0",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-render-html": "4.2.4",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-scroll-into-view": "^2.0.2",
    "react-native-segmented-picker": "^2.0.2",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "15.2.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.5.2",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.8.6",
    "scandit-react-native-datacapture-barcode": "6.25.0",
    "scandit-react-native-datacapture-core": "6.25.0",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "swr": "^2.0.3",
    "unstated-next": "^1.1.0"
  },

After update:

"dependencies": {
    "@bugsnag/expo": "^49.0.0",
    "@expo/vector-icons": "^14.0.2",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/datetimepicker": "8.2.0",
    "@react-native-community/netinfo": "11.4.1",
    "@react-native-firebase/analytics": "^17.3.2",
    "@react-native-firebase/app": "^17.3.2",
    "@react-native-firebase/messaging": "^17.3.2",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@react-navigation/stack": "^6.4.1",
    "@shopify/flash-list": "1.7.1",
    "dayjs": "^1.11.13",
    "deprecated-react-native-prop-types": "^4.0.0",
    "expo": "^52.0.17",
    "expo-application": "~6.0.1",
    "expo-auth-session": "~6.0.1",
    "expo-barcode-scanner": "~13.0.1",
    "expo-blur": "~14.0.1",
    "expo-brightness": "~13.0.2",
    "expo-camera": "~16.0.9",
    "expo-constants": "~17.0.3",
    "expo-crypto": "~14.0.1",
    "expo-device": "~7.0.1",
    "expo-file-system": "~18.0.4",
    "expo-haptics": "~14.0.0",
    "expo-image": "~2.0.3",
    "expo-intent-launcher": "~12.0.1",
    "expo-linear-gradient": "~14.0.1",
    "expo-linking": "~7.0.3",
    "expo-local-authentication": "~15.0.1",
    "expo-localization": "~16.0.0",
    "expo-location": "~18.0.3",
    "expo-notifications": "~0.29.11",
    "expo-random": "~14.0.1",
    "expo-secure-store": "~14.0.0",
    "expo-splash-screen": "~0.29.16",
    "expo-status-bar": "~2.0.0",
    "expo-updates": "~0.26.10",
    "expo-web-browser": "~14.0.1",
    "intl": "^1.2.5",
    "lodash": "^4.17.21",
    "metro-react-native-babel-transformer": "^0.77.0",
    "native-base": "^3.1.0",
    "numeral": "^2.0.6",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-intl": "^6.1.1",
    "react-native": "0.76.3",
    "react-native-drax": "^0.10.2",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-get-random-values": "~1.11.0",
    "react-native-maps": "1.18.0",
    "react-native-modal": "^13.0.0",
    "react-native-modal-datetime-picker": "13.1.2",
    "react-native-pager-view": "6.5.1",
    "react-native-qrcode-svg": "^6.1.1",
    "react-native-reanimated": "~3.16.1",
    "react-native-render-html": "4.2.4",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-scroll-into-view": "^2.0.2",
    "react-native-segmented-picker": "^2.0.2",
    "react-native-size-matters": "^0.4.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "15.8.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.5.2",
    "react-native-uuid": "^2.0.1",
    "react-native-web": "~0.19.6",
    "react-native-webview": "13.12.5",
    "scandit-react-native-datacapture-barcode": "6.25.0",
    "scandit-react-native-datacapture-core": "6.25.0",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "swr": "^2.0.3",
    "unstated-next": "^1.1.0"
  },

**Comment by cortinico** [comment]
> This is a company project and I cannot provide further information. My problem was after I upgraded expo from version 51 to 52, which required updating version of react native. Specifically, my package.json file looks like this:

Then please 
1. use this template: https://github.com/react-native-community/reproducer-react-native
2. add all your dependencies
3. make sure you can recreate the same error you're seeing
4. share it here

**Comment by NickGerleman** [comment]
Does the error in the app, or error in RN DevTools show more context? The end of the warning in the screenshot started saying "Component stack", and that's the thing that would point to what code or library is causing this error.

**Comment by trantuandatvietnam** [comment]
Thank for reply. I detected the isssue. It's from react-native-drax library. This lib was quite old

**Comment by trantuandatvietnam** [comment]
> > This is a company project and I cannot provide further information. My problem was after I upgraded expo from version 51 to 52, which required updating version of react native. Specifically, my package.json file looks like this:
> 
> Then please
> 
> 1. use this template: https://github.com/react-native-community/reproducer-react-native
> 2. add all your dependencies
> 3. make sure you can recreate the same error you're seeing
> 4. share it here

Thank for reply. I detected the isssue. It's from react-native-drax library. This lib was quite old

**Comment by cortinico** [comment]
> Thank for reply. I detected the isssue. It's from react-native-drax library. This lib was quite old

Closing as per this last comment

**Comment by norellanac** [comment]
@trantuandatvietnam 
would you mind posting more details about your fix?
I am facing similar issues using `"react-native-drax": "^0.10.3"`,

**Comment by trantuandatvietnam** [comment]
@norellanac yeah, you should go to `https://github.com/nuclearpasta/react-native-drax/pull/176` and use patch package for this lib

**Comment by AlexGarneau** [comment]
If it helps, I got that error when I was trying to reference the listNodeHandle index number when calling measureLayout in an onLayout call. Instead of that, just pass in a reference to the parent object itself. They changed the measureLayout method to take in the object reference instead of an index number.
