### ISSUE TITLE
how to disable  YellowBox (enabled in iOS by default)

### ISSUE THREAD

**Issue by MrPluto** [facebook/react-native#4819]
i choose release mode in Xcode ,why my app still has the yellow box?

**Comment by sospartan** [comment]
`console.disableYellowBox = true;` 
@MrPluto

**Comment by MrPluto** [comment]
Thanks a lot. :+1:

**Comment by michelarteta** [comment]
Sorry, where do you add console.disableYellowBox = true; ?

**Comment by krsjoseph** [comment]
@michelarteta you can put in in your top most component to disable it for the entire app

**Comment by ohtangza** [comment]
@krsjoseph Can I re-enable it after disabling it for a while?

**Comment by krsjoseph** [comment]
Yes you can just delete or comment out  the line of code.

**Comment by ohtangza** [comment]
@krsjoseph Thanks for your answer. I'll try :)

**Comment by grovdata** [comment]
I have the same issue. Why does it appear in release builds at all? From the documentation:

> RedBoxes and YellowBoxes are automatically disabled in release (production) builds.

**Comment by rogchap** [comment]
Just in case someone finds their way here:

Ignore YellowBox warnings with `YellowBox.ignoreWarnings([...])` rather than `console.ignoredYellowBox = [...]` 

Since RN 0.52.0
