### ISSUE TITLE
[iOS] Attempt to present <RCTFabricModalHostViewController: 0x11c98e200> on <RCTFabricModalHostViewController: 0x11a3c7a00> (from <RCTFabricModalHostViewController: 0x11a3c7a00>)  whose view is not in the window hierarchy.

### ISSUE THREAD

**Issue by georgi2005atanasov** [facebook/react-native#48195]
### Description

Hello, i am getting this error when opening one modal after the other. 

### Steps to reproduce

I am trying to render conditionally the modals like this:

`  
<FIrstModal visible={stage === Stages.FirstStage} closeHandler={close} />
<SecondModal visible={stage === Stages.SecondStage} closeHandler={close} />
<ThirdModal visible={stage === Stages.ThirdStage} closeHandler={close} />
`

of course, each modal has a 'visible' property which is determined by the current stage (which is an enum) as shown in this example. After closing the first modal (closing basically represents changing the current stage so it gets increased by 1 and goes to the second modal and so on) I get the error which I pasted in the title. I would be glad if someone had already faced this kind of issue! 

### React Native Version

0.76.3

### Affected Platforms

Build - MacOS

### Areas

Fabric - The New Renderer

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1.1
  CPU: (8) arm64 Apple M3
  Memory: 960.16 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.3.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.11.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /Users/myname/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/myname/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: ^18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
Attempt to present <RCTFabricModalHostViewController: 0x11c98e200> on <RCTFabricModalHostViewController: 0x11a3c7a00> (from <RCTFabricModalHostViewController: 0x11a3c7a00>)  whose view is not in the window hierarchy.
```

### Reproducer

https://github.com/georgi2005atanasov

**Comment by WilliamWelsh** [comment]
Possibly related to https://github.com/facebook/react-native/issues/47694 ?

**Comment by georgi2005atanasov** [comment]
Guys, the problem was related tothe version itself - after I upgraded to 0.76.5 every problem disappeared. React native bot did its job :).
