### ISSUE TITLE
Missing '#include "ReactCommon/SchedulerPriority.h"'; 'SchedulerPriority' must be declared before it is used

### ISSUE THREAD

**Issue by benji-jo** [facebook/react-native#48218]
### Description

I was trying to introduce a new Architecture, but this error occurred.
How do I solve this?
Missing '#include "ReactCommon/SchedulerPriority.h"'; 'SchedulerPriority' must be declared before it is used

### Steps to reproduce

1. pod install 2. Xcode build 3. error

### React Native Version

0.76.3

### Affected Platforms

Build - MacOS

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.6.1
  CPU: (12) arm64 Apple M3 Pro
  Memory: 496.03 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 4.2.2
    path: ~/.nvm/versions/node/v18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman:
    version: 2024.11.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/benji/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.7.4
    path: /Users/benji/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Stacktrace or Logs

```text
ios build error
```

### Reproducer

private repository

### Screenshots and Videos

<img width="363" alt="스크린샷 2024-12-12 오전 1 50 08" src="https://github.com/user-attachments/assets/1f8aa1db-b8dd-46f2-8d0c-6318237435bc" />
<img width="1029" alt="스크린샷 2024-12-12 오전 2 12 02" src="https://github.com/user-attachments/assets/3f14b39e-d436-43c7-9bbf-61e744a86abb" />

**Comment by benji-jo** [comment]
Even if you upgrade to 0.76.5, the same error occurs.

**Comment by labrute974** [comment]
@benji-jo how did you resolve the issue ?
