### ISSUE TITLE
Dependencies and releases are not fully checked

### ISSUE THREAD

**Issue by evan1715** [facebook/react-native#48221]
### Description

RN 0.76.4 was released previously on Github, but not on NPM a week or so ago. Now fixed, but says 0.76.4 and 0.76.5 were released "2 days ago" on the same date.

RN 0.76.5 does not include package match semver for @react-native/babel-preset, @rreact-native/metro-config, etc for 0.76.5 inside the Upgrade Helper. Leads to confusion as do I match the versioning or do I not.
seen here: https://react-native-community.github.io/upgrade-helper/?from=0.76.4&to=0.76.5

On the same link, there's a non-existent binary on Upgrade Helper.

Hermes dSYMS URLs are not found: https://github.com/facebook/react-native/releases/tag/v0.76.5

### Steps to reproduce

N/A

### React Native Version

0.76.5

### Affected Platforms

Other (please specify)

### Output of `npx react-native info`

```text
N/A
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

### Screenshots and Videos

N/A

**Comment by cortinico** [comment]
> RN 0.76.4 was released previously on Github, but not on NPM a week or so ago. Now fixed, but says 0.76.4 and 0.76.5 were released "2 days ago" on the same date.

Releasing a React Native version is quite of a long progress. I see both 0.76.4 and 0.76.5 are on NPM/GitHub. Please allow some time from when the release ends up on all the various repositories for it to be fully usable.

> RN 0.76.5 does not include package match semver for @react-native/babel-preset, @rreact-native/metro-config, etc for 0.76.5 inside the Upgrade Helper. Leads to confusion as do I match the versioning or do I not. seen here: [react-native-community.github.io/upgrade-helper?from=0.76.4&to=0.76.5](https://react-native-community.github.io/upgrade-helper/?from=0.76.4&to=0.76.5)
> On the same link, there's a non-existent binary on Upgrade Helper.

That's a bug on the upgrade helper.
See here: 
- https://github.com/react-native-community/upgrade-helper/issues/392

> Hermes dSYMS URLs are not found: [`v0.76.5` (release)](https://github.com/facebook/react-native/releases/tag/v0.76.5)

Fixed. There was a type on the URL
