### ISSUE TITLE
[feature request] Add purge cache option to "react-native bundle" command

### ISSUE THREAD

**Issue by skatou** [facebook/react-native#4823]
Hi,

It cost me over an hour to figure out why my pre-bundle js not get updated after some code changes, it's because "react-native bundle" command is using caches.  I find where the cache is by using the "--verbose" option.

The command line help doesn't provide any option relates to the cache used, it will confuse people who meet the same issue.

**Comment by fov42550564** [comment]
+1

**Comment by fov42550564** [comment]
cd /var/folder && sudo find -name react-packager*

**Comment by ranyefet** [comment]
@skatou Thanks, for reporting good to see I'm not alone with this issue.
I also wasted few hours on it until found this thread.

@fov42550564 thanks, deleting the cache worked for me. 

Any plans for permanent  solution?

**Comment by hufeng** [comment]
+1

**Comment by jsierles** [comment]
While there is no command to ONLY clear the cache, the packager now can clear cache at startup.

`react-native start --reset-cache`

It would be a great PR to separate this functionality into a separate command!
