### ISSUE TITLE
[feature request] make navigator methods returning a Promise

### ISSUE THREAD

**Issue by gre** [facebook/react-native#4824]
I don't know how feasible and how much work this involve but I would love to have navigator methods retuning promise.

Basically,
```js
navigator.push({}).then(navigationWasSuccessful, navigationWasSomehowAborted);
```
(but also for almost all `navigator.*` methods)

This unlock a lot of use-case. One of my best use-case is I have buttons that trigger navigation, and I want to "lock that button" until the navigation is done (meaning the button is not touchable until it's action is completed (succeed or failed)). This is an interesting pattern with buttons and promise. This prevent async stuff (like saving something to the server) to be done twice when double tapping it, in the case of navigation, this also prevent ugly errors when you tap a lot on a navigation button.

**Comment by brentvatne** [comment]
Hey @gre - nobody is working actively on the current version of Navigator at the moment, a pull request would be welcome for this, but work is being directed towards a re-written version of Navigator currently :) You can try that out and comment on it here: https://github.com/ericvicenti/navigation-rfc
