### ISSUE TITLE
How to add ReactNative to an existing iOs app

### ISSUE THREAD

**Issue by kennydee** [facebook/react-native#483]
Hi there,

Is there any guide, or anyone knowing how how to add progressively ReactNative to an already existing iOs app ?

The point here, is for example to add a new view made with ReactNative on an existing app. I don't really know how to begin ;)

Thanks

**Comment by vkurchatkin** [comment]
@kennydee as far as I know, you can instantiate `RCTRootView` class and add it as a subview to any existing view

**Comment by Sunify** [comment]
See AppDelegate.m file in project folder

**Comment by tjwudi** [comment]
@vkurchatkin Very helpful comment! It also can be applied when you want to manually add a view controller like a modal view controller.

**Comment by tjwudi** [comment]
@kennydee I also provide sample code of doing this in #473, if you are interested.

**Comment by kennydee** [comment]
Great ! Thanks all :)
Wil look at That and reopen later if needed.
I think a tutorial would help a lot of people on this ;)

**Comment by tjwudi** [comment]
@kennydee I wrote a tutorial [here](http://blog-en.leapoahead.com/post/use-react-native-in-existing-ios-app).

@vjeux Any thoughts on this post? Or can we add it to **Guides** docs?

**Comment by vjeux** [comment]
Yeah w

**Comment by vjeux** [comment]
Would be a great guide
