### ISSUE TITLE
babelHelpers.objectDestructuringEmpty is not a function

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4831]
I upgraded from RN 15 to RN 16 and now I get:
`babelHelpers.objectDestructuringEmpty is not a function`:
![image](https://cloud.githubusercontent.com/assets/51059/11855689/b4d137d4-a419-11e5-9eb5-dea906b167e9.png)

Currently my `.babelrc` files looks like:
```json
{
  "presets": ["react"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-es2015-classes",
    "transform-export-extensions"
  ]
}
```

I previously also had `es2015` in the `presets` list but then I got: http://stackoverflow.com/questions/34112110/upgrade-to-react-native-0-16-error.

**Comment by udfalkso** [comment]
Hi @cancan101 I'm also hitting this issue.  Did you manage to solve it?  Thanks

**Comment by cancan101** [comment]
Try adding `"transform-runtime"` to the plugins.

**Comment by udfalkso** [comment]
Thanks.  Did you have to add babel-runtim@6.x to your package file to get this to work?

I've tried that and now I get this problem: 

```
Error: 
 stack: Error: Requiring unknown module "babel-runtime/core-js/number/min-safe-integer". If you are sure the module is there, try restarting the packager.
    at requireImpl (http://192.168.20.127:8081/index.ios.bundle?platform=ios&dev=true:48:7)
```
But this file is there.  

```
(develop)[udi@udis-mac:node_modules/babel-runtime]$ find . -name "*min-safe-integer*" -print
./core-js/number/min-safe-integer.js
./node_modules/core-js/fn/number/min-safe-integer.js
./node_modules/core-js/library/fn/number/min-safe-integer.js
./node_modules/core-js/library/modules/es6.number.min-safe-integer.js
./node_modules/core-js/modules/es6.number.min-safe-integer.js
```

**Comment by udfalkso** [comment]
@cancan101 Any chance you could share what's in your package.json and .babelrc files?  Would be very helpful, thanks!

**Comment by udfalkso** [comment]
Finally managed to get past this error.  It turns out that I had code like this that needed to be removed:

```
var {
} = React;
```

**Comment by cancan101** [comment]
That worked for me as well.

**Comment by cancan101** [comment]
Is this some sort of know issue ? How did you figure it out.

**Comment by udfalkso** [comment]
Just a lot of digging around and trial and error.

**Comment by satya164** [comment]
You seem to be using very few transforms. It'll be better to copy [React Native's `.babelrc`](https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc) and what you need.

**Comment by udfalkso** [comment]
Aren't those transforms automatically being run by the RN packager @satya164 ?  This was a special case of destructuring an empty object which I think caused the problem here.

**Comment by satya164** [comment]
@udfalkso Yeah, in your case yes. But the packager uses your `.babelrc` instead if you have one, or at least that's how it used to be. I haven't tried with a custom `.babelrc` in the latest version though.

**Comment by cancan101** [comment]
Right now I am using a `.babelrc` of:
```json
{
  "presets": [],
  "plugins": [
    "transform-decorators-legacy",
    "transform-export-extensions"
  ]
}
```
and it works as long as I remove all instances of:
```js
const {
} = React;
```

**Comment by udfalkso** [comment]
I'm using an empty .babelrc file, but using es6 modules and other things.  So I assume RN packager is picking up the rest of the slack.  Finally all working now.

**Comment by cancan101** [comment]
Is this an issue with Babel 6? A feature?

**Comment by marco-amoroso** [comment]
2 days ago we decided to upgrade RN from 0.14 to 0.19, after trial and errors we reached the `babelHelpers.objectDestructuringEmpty is not a function` error and found this thread. Thanks indeed. We had some `function(state, {}) ...` in our codebase.

Not sure if it's a feature but it was working fine in Babel 5. Most likely Babel 6 is stricter.

**Comment by gelobelo02** [comment]
can someone further explain the solution to this error?

**Comment by philolo1** [comment]
I had a similar issue because I used `{}` at some point, is this an issue with babel, and if so which repo should we report it.

**Comment by 3DEsprit** [comment]
I found this issue when having braces in place for destructuring, but without any values between the braces. 

e.g. `const value = ({}) => { ... }`

I believe Babel is simply complaining that the object is in fact empty, and does not have any values to destructure.

**Comment by sujitpk-perennial** [comment]
For me adding extra curly bracket causing this issue. so I have changed 
from renderTextInput= {({}) => ()}
to renderTextInput= {() => (})

**Comment by alexthegoodman** [comment]
I too fell down this trap! Yes, you may use an empty object {}, but are you sure you aren't having a syntax error like:

let {  } = this.props;

That's what got me!

**Comment by patrickleemsantos** [comment]
Hi Guys,

I am also experiencing this error when I Run and Build my react native app on XCode.

[error][tid:com.facebook.react.JavaScript] babelHelpers.objectDestructuringEmpty is not a function. (In 'babelHelpers.objectDestructuringEmpty(o.default)', 'babelHelpers.objectDestructuringEmpty' is undefined)

I already tried all the solutions here but still faceing the problem.

**Comment by HananeAlSamrout** [comment]
i had this issue also, the reason was 
`let {}=this.state`

**Comment by mckrava** [comment]
`let { } = some_object;`
This "empty definition" in any place of code is a reason of babel error.

**Comment by dgreensp** [comment]
It's a shame that the only fix here is "don't do that."  Empty destructuring is perfectly valid, and it could be a nice idiom for ignoring an argument, as in `({}, foo) => ...`.  In fact, the Babel helper in question exists specifically to allow destructuring an empty object in a spec-compliant way: https://github.com/babel/babel/issues/681

**Comment by punksta** [comment]
I had similar problem:
```
const removeKey = (key: string, {[key]: {}, ...rest}) => rest;
```
it works good in debug, but release build chased. 

![image](https://user-images.githubusercontent.com/13404754/39046261-3dfb9b2c-449e-11e8-87b6-9f3254b14c20.png)

fixed by changing `{}` to `_`. 
```
const removeKey = (key, {[key]: _, ...rest}) => rest;
```

**Comment by vigneshprabhu20** [comment]
I got this fix upon installing babel helper plugin.

Package.json:
"devDependencies": {
    "babel-cli": "6.26.0",
    "babel-plugin-external-helpers": "^6.22.0",
....
}

babelrc:
{
  "presets": ["react-native", "flow"],
  "plugins": [
    "external-helpers",
...
  ]
}

Reference to install this plugin:
https://www.npmjs.com/package/babel-plugin-external-helpers

**Comment by RossKinsella** [comment]
My issue was an empty destructuring for the arguments of a function. What's interesting is this was only an issue when I did a production build. In my iOS emulator I didn't get an exception.

**Comment by ishigamii** [comment]
@vigneshprabhu20 I just tried your solution and sadly I still have the same problem. 

Is there any way to find the reason why it crashes with this error cause I am stuck on this...

**Comment by ramonprata** [comment]
tks @vigneshprabhu20 you solution worked for me
