### ISSUE TITLE
Cannot fetch stream api response

### ISSUE THREAD

**Issue by huseyinaltas** [facebook/react-native#48314]
### Description

When I implement this fetch curl api on node.js standalone project, I get stream response,
And I implement in react-native project I cannot get response

 async function chat(prompt) {

  const API_KEY = "XXXX";
  const url = new URL(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?key={API_KEY}`
  );
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: prompt }],
        },
      ],
    }),
  });

  if (!response.ok) {
    console.error("Request failed", response.statusText);
    return;
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let done = false;
  let content = "";

  while (!done) {
    const { value, done: readerDone } = await reader.read();
    done = readerDone;
    content += decoder.decode(value, { stream: true });
    console.log(content);
  }

  // Final content received
  console.log("Final Content:", content);
}

### Steps to reproduce

 Copy above code and use fetch in single node.js project
 It gets logging out stream response

When I copy and past on react-native project
And I call it,
Not getting response.body in fetch
 
 
 "dependencies": {
    "@google/generative-ai": "^0.21.0",
    "@react-native-firebase/analytics": "^19.3.0",
    "@react-native-firebase/app": "^19.3.0",
    "@react-native-firebase/auth": "^19.3.0",
    "@react-native-firebase/firestore": "19.3.0",
    "@react-native-firebase/functions": "^19.3.0",
    "@react-native-firebase/messaging": "^19.3.0",
    "@react-native-firebase/remote-config": "^19.3.0",
    "@react-navigation/stack": "^6.3.29",
    "axios": "^1.7.9",
    "country-flag-icons": "^1.5.13",
    "https-browserify": "^1.0.0",
    "moment-timezone": "^0.5.45",
    "react": "18.2.0",
    "react-native": "^0.73.9",
    "react-native-device-info": "^10.13.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.1",
    "react-native-keychain": "^8.1.3",
    "react-native-localize": "^3.2.1",
    "react-native-paper": "^5.12.3",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-sound": "^0.11.2",
    "react-native-sse": "^1.2.1",
    "react-native-vector-icons": "^10.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-native-vector-icons": "^6.4.18",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },

### React Native Version

"react-native": "^0.73.9" 

### Affected Platforms

Runtime - Android, Runtime - iOS

### Output of `npx react-native info`

```text
OS: macOS 15.2 
  CPU: (12) arm64 Apple M2 Pro
  Memory: 202.84 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 23.3.0
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.11.18.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11709847
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.9
    wanted: ^0.73.9
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
ERROR  Error fetching data: [TypeError: Cannot read property 'read' of undefined]
```

### Reproducer

https://github.com/huseyinaltas/Shock

**Comment by huseyinaltas** [comment]
upgraded react-native 0.75.4 and trying now

**Comment by huseyinaltas** [comment]
0.75.4 has same issue

**Comment by sarthak-d11** [comment]
Hi @huseyinaltas,

It would be really helpful if you could provide a sample reproducer. You can use this [template](https://github.com/new?template_name=reproducer-react-native&template_owner=react-native-community) to create one.

Also, I noticed that the link to your repository ([Shock](https://github.com/huseyinaltas/Shock)) is returning a 404 error, so I’m unable to access it.

Could you let me know if this issue is platform-specific (i.e., Android or iOS)? I see that you're using the old architecture—would it be possible to try with the new architecture as well?

**Comment by huseyinaltas** [comment]
Hi @sarthak-d11  - I pushed app to here
https://github.com/huseyinaltas/ChatAPP

Issue is occurring on IOS and Android 
I get "Error generating content: [TypeError: Cannot read property 'pipeThrough' of undefined]"

**Comment by yanglee2421** [comment]
import { fetch } from "expo/fetch"
> [docs](https://docs.expo.dev/versions/latest/sdk/expo/#expofetch-api)

**Comment by huseyinaltas** [comment]
Thank you @yanglee2421, this is the way. closing.

**Comment by NiuGuohui** [comment]
> import { fetch } from "expo/fetch"
> 
> > [docs](https://docs.expo.dev/versions/latest/sdk/expo/#expofetch-api)

This is a bad solution for projects that do not use expo :(
