### ISSUE TITLE
[Geolocation] navigator.geolocation.getCurrentPosition doesn't get executed first time it is called

### ISSUE THREAD

**Issue by daesan** [facebook/react-native#4834]
I've upgraded from RN 0.16.0 to 0.17.0-rc and navigator.geolocation.getCurrentPosition() doesn't get executed any more.

However, if I insert "navigator.geolocation.getCurrentPosition(()=>null, ()=>null)" before the actual call, it does get executed. Maybe this is related to new lazy loading feature?

**Comment by christopherdro** [comment]
This was recently fixed with the following commit. https://github.com/facebook/react-native/commit/f48dbbecd658123e6fdaacf1b5762692d4d1d7f5

**Comment by daesan** [comment]
Great. Thanks!
