### ISSUE TITLE
View not resize when keyboard pop-up/focus on TextInput

### ISSUE THREAD

**Issue by benzsuankularb** [facebook/react-native#4837]
This is when resize working

![screen shot 2558-12-17 at 3 56 10 pm](https://cloud.githubusercontent.com/assets/2444351/11865633/cc4329f4-a4d7-11e5-930d-221a55fab5a4.png)

This is when resize not working

![screen shot 2558-12-17 at 3 56 53 pm](https://cloud.githubusercontent.com/assets/2444351/11865641/e43f4df8-a4d7-11e5-91b6-57bacc0900d9.png)

When I firstly open this page, Keyboard show up and view resize properly

I hide the keyboard by using hide soft keys at the buttom then click on the inputText to focus it again, This seems work properly.

Now, when i press back on the Android Toolbars It's go back to previous page (main page),
I come to this page again, And it's not working.

I've tried to hide keyboard before press back but still not working

I figure out that it's will work again when this page is completely reloaded/re-rendered/renew object (something) because It's will work again after I open-close drawer and went back to this page. (May be It's reload my hole view)

Note: I'm not using Navigator for this view. I just set this page as a state of main page.

**Comment by theoriginalgri** [comment]
Did you try to set ```android:windowSoftInputMode``` explicitly to ```adjustResize``` (or another option that suits your view) in your ```AndroidManifest.xml```?

I also had strange behavior with keyboard and the resize without setting this option myself.

**Comment by satya164** [comment]
@benzsuankularb You need to the following,

1. In your `AndroidManifest.xml`, change/add `android:windowSoftInputMode` to `adjustResize`. The default is Pan which will move your screen up.

2. Listen to `keyboardDidShow` and `keyboardDidHide` events and add a spacer at the bottom of the view.

Here is an example `KeyboardSpacer.js`,

```js
import React from "react-native";

const {
	Platform,
	Animated,
	View,
	DeviceEventEmitter
} = React;

const KITKAT = 19;

class KeyboardSpacer extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			keyboardHeightAnim: new Animated.Value(0)
		};
	}

	componentWillMount() {
		this._registerEvents();
	}

	componentWillUnmount() {
		this._unRegisterEvents();
	}

	_registerEvents() {
		this._keyboardDidShowSubscription = DeviceEventEmitter.addListener("keyboardDidShow", e => this._keyboardDidShow(e));
		this._keyboardDidHideSubscription = DeviceEventEmitter.addListener("keyboardDidHide", e => this._keyboardDidHide(e));
	}

	_unRegisterEvents() {
		this._keyboardDidShowSubscription.remove();
		this._keyboardDidHideSubscription.remove();
	}

	_keyboardDidShow(e) {
		Animated.spring(this.state.keyboardHeightAnim, {
			toValue: e.endCoordinates.height
		}).start();
	}

	_keyboardDidHide() {
		Animated.spring(this.state.keyboardHeightAnim, {
			toValue: 0
		}).start();
	}

	render() {
		return <Animated.View style={{ height: this.state.keyboardHeightAnim }} />;
	}
}

// The app pans to show the Keyboard below Kitkat (We set it to resize from Kitkat to upwards)
export default Platform.OS === "android" && Platform.Version < KITKAT ? View : KeyboardSpacer;
```

**Comment by benzsuankularb** [comment]
@satya164 @theoriginalgri Solved my problem.

**Comment by khushboogupta1** [comment]
I am getting keyboard space issue in IOS. I am attaching images and my code also. I want screen to move up when keyboard opens up while clicking on autocomplete textInput. 

![img-6421](https://user-images.githubusercontent.com/16782546/41894016-35c22990-793b-11e8-95e7-de2146a12a4d.PNG)
![img-6422](https://user-images.githubusercontent.com/16782546/41894017-36701d5c-793b-11e8-90cc-401ac3ef8a31.PNG)



Code:

    import React, { Component } from 'react';
    import { StyleSheet, Text, TextInput, Platform, TouchableOpacity, TouchableHighlight, Picker,Alert, ActivityIndicator, ScrollView, 
        View, ToastAndroid,Keyboard,TouchableWithoutFeedback, KeyboardAvoidingView } from 'react-native';
    import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-dimensions';
    import AutoTags from 'react-native-tag-autocomplete';
    import RadioForm, { RadioButton, RadioButtonInput, RadioButtonLabel } from 'react-native-simple-radio-button';
    import { StackNavigator } from 'react-navigation';
    import Toast from 'react-native-simple-toast';
    
    render()
    {
        return 
        (
            <View style={styles.container}>
                <Text style={{ padding: 5, fontSize: 35, backgroundColor: '#00BCD4', marginBottom: 7 }}>Geo Targeting</Text>
                    <ScrollView keyboardShouldPersistTaps='handled' >
                        <View style={{ marginBottom: 15,  flex: 1 }}>
                            <Text style={{ fontSize: 25, color: 'blue' }}> Select Locations</Text>
                            <RadioForm
                                ref="radioForm"
                                style={styles.radioButtonStyle}
                                radio_props={this.state.radio_props}
                                initial={this.state.selectedLocation}
                                formHorizontal={true}
                                buttonColor={'#2196f3'}
                                labelStyle={{ marginRight: 20 }}
                                onPress={(value, index) => {
                                    this.setState({
                                        value: value,
                                        valueIndex: index
                                    })
                            }} />
                        </View>
                            {console.log("include locations: " + this.state.includesuggestions)}
                            <View style = {styles.includeLocationsContainer}> 
                                    <Text style={styles.label}>
                                        Type the name of a country or city to include
                                    </Text>
                                    <AutoTags
                                        listStyle={{ maxHeight: 150 }}
                                        //required
                                        suggestions={this.state.includesuggestions}
                                        tagsSelected={this.state.includeTagsSelected}
                                        handleAddition={this.includeAddition}
                                        handleDelete={this.inlcudeDelete}
                                        //optional
                                        placeholder="Add a location.."
                                        filterData={this.includeFilterData}
                                        renderSuggestion={this.includeRenderSuggestions}
                                        renderTags={this.includeRenderTags}
                                    />
                                </View>

                        
                        <View style = {styles.excludeLocationsContainer}> 
                                <Text style={styles.label}>
                                    Type the name of a country or city to exclude
                                </Text>
                                <AutoTags
                                        listStyle={{ maxHeight: 150 }}
                                        //required
                                        suggestions={this.state.exculdeSuggestions}
                                         tagsSelected={this.state.excludeTagsSelected}
                                        handleAddition={this.excludeAddition}
                                        handleDelete={this.exlcudeDelete}
                                        //optional
                                        placeholder="Add a location.."
                                        filterData={this.excludeFilterData}
                                        renderSuggestion={this.excludeRenderSuggestions}
                                        renderTags={this.excludeRenderTags}
                                    />
                            </View>
                            
                        <View style={styles.messageContainer}>
                            <TouchableOpacity
                                style={styles.SubmitButtonStyle}
                                activeOpacity={.5}
                                onPress={this.onSaveLocations} >
                                <Text style={styles.TextStyle}> SAVE</Text>
                            </TouchableOpacity>
                        </View>
                    </ScrollView>
            </View>
        );
    }

    const styles = StyleSheet.create({

        container: {
            justifyContent: 'center',
            paddingTop: (Platform.OS === 'ios') ? 20 : 30,
            padding: 5,
        },

        includeLocationsContainer: {
        marginBottom: 10,
        flex: 1,
        left: 20,
        overflow: 'visible',
        position: 'relative',
        zIndex: 999,
        },

        excludeLocationsContainer: {
            left: 20,
            flex: 1,
            marginTop: 15,
            overflow: 'visible',
            position: 'relative',
            zIndex: 998,
        },

    });
