### ISSUE TITLE
The FlatList jumps while scrolling

### ISSUE THREAD

**Issue by valery-lavrik** [facebook/react-native#48382]
### Description

I am developing in windows for android

I have built a column of images in the FlatList. Many have different sizes.
but during scrolling, something goes wrong, and the list jumps to a certain place. I've recorded a video, and I'm attaching it to the message.

### Steps to reproduce

I have created a repository where I can test the problem myself.

### React Native Version

0.76.5

### Affected Platforms

Runtime - Android

### Output of `npx react-native info`

```text
npx react-native info
info Fetching system and libraries information...
(node:1516) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
  Memory: 2.99 GB / 15.71 GB
Binaries:
  Node:
    version: 22.11.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.9.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.15989.150.2411.11948838
  Visual Studio: Not Found
Languages:
  Java:
    version: 17.0.11
    path: /c/Program Files/Microsoft/jdk-17.0.11.9-hotspot/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 15.0.1
    wanted: 15.0.1
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Stacktrace or Logs

```
import React from 'react';
import { FlatList, Dimensions, Image } from 'react-native';


export default function App() {

    const IMAGES = [ { "id": 54760676, "url": "https://img.com-x.life/comix/17767/610982/1733835303.7601.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 0 }, { "id": 54760677, "url": "https://img.com-x.life/comix/17767/610982/1733835304.6572.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 1 }, { "id": 54760678, "url": "https://img.com-x.life/comix/17767/610982/1733835305.5284.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 2 } ];

    const W = Dimensions.get('screen').width;
    const initialScrollIndex = 20;

    const gettSizeOfTheImageToTheScreen = (item) => parseInt(((W / item.width) * item.height), 10)

    return (
        <FlatList
            data={IMAGES}
            initialNumToRender={3}
            maxToRenderPerBatch={2}
            initialScrollIndex={initialScrollIndex}
            keyExtractor={(item) => `${item.id}`}
            getItemLayout={(data, index) => {
                const ITEM_HEIGHT = gettSizeOfTheImageToTheScreen(data[index]);
                return { length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index }
            }}
            renderItem={({ item }) => (
                <Image
                    style={{
                        width: W,
                        height: gettSizeOfTheImageToTheScreen(item),
                        resizeMode: 'contain',
                    }}
                    source={{
                        uri: item.url,
                        headers: item.headers,
                    }}
                />
            )}
        />
    );
}
```

### Reproducer

https://github.com/valery-lavrik/flatlist_test

### Screenshots and Videos

https://github.com/user-attachments/assets/a9edcfe5-a578-4e8c-a441-0e2faf49920b

**Comment by valery-lavrik** [comment]
Sample code for playback
```
import React from 'react';
import { FlatList, Dimensions, Image } from 'react-native';


export default function App() {

    const IMAGES = [ { "id": 54760676, "url": "https://img.com-x.life/comix/17767/610982/1733835303.7601.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 0 }, { "id": 54760677, "url": "https://img.com-x.life/comix/17767/610982/1733835304.6572.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 1 }, { "id": 54760678, "url": "https://img.com-x.life/comix/17767/610982/1733835305.5284.jpg", "headers": { "Referer": "https://com-x.life/" }, "cache_key": "2818811-0", "width": 1200, "height": 1845, "index": 2 } ];

    const W = Dimensions.get('screen').width;
    const initialScrollIndex = 20;

    const gettSizeOfTheImageToTheScreen = (item) => parseInt(((W / item.width) * item.height), 10)

    return (
        <FlatList
            data={IMAGES}
            initialNumToRender={3}
            maxToRenderPerBatch={2}
            initialScrollIndex={initialScrollIndex}
            keyExtractor={(item) => `${item.id}`}
            getItemLayout={(data, index) => {
                const ITEM_HEIGHT = gettSizeOfTheImageToTheScreen(data[index]);
                return { length: ITEM_HEIGHT, offset: ITEM_HEIGHT * index, index }
            }}
            renderItem={({ item }) => (
                <Image
                    style={{
                        width: W,
                        height: gettSizeOfTheImageToTheScreen(item),
                        resizeMode: 'contain',
                    }}
                    source={{
                        uri: item.url,
                        headers: item.headers,
                    }}
                />
            )}
        />
    );
}
```

**Comment by ralph1233** [comment]
`import React from 'react';
import {FlatList, Dimensions, Image} from 'react-native';

export const IMAGES = [
  {
    id: 54760676,
    url: 'https://img.com-x.life/comix/17767/610982/1733835303.7601.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 0,
  },
  {
    id: 54760677,
    url: 'https://img.com-x.life/comix/17767/610982/1733835304.6572.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 1,
  },
  {
    id: 54760678,
    url: 'https://img.com-x.life/comix/17767/610982/1733835305.5284.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 2,
  },
  {
    id: 54760679,
    url: 'https://img.com-x.life/comix/17767/610982/1733835306.4632.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 2000,
    height: 1538,
    index: 3,
  },
  {
    id: 54760680,
    url: 'https://img.com-x.life/comix/17767/610982/1733835307.9671.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 4,
  },
  {
    id: 54760681,
    url: 'https://img.com-x.life/comix/17767/610982/1733835308.9042.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 5,
  },
  {
    id: 54760682,
    url: 'https://img.com-x.life/comix/17767/610982/1733835309.8052.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 6,
  },
  {
    id: 54760683,
    url: 'https://img.com-x.life/comix/17767/610982/1733835310.6976.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 7,
  },
  {
    id: 54760684,
    url: 'https://img.com-x.life/comix/17767/610982/1733835311.5839.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 2000,
    height: 1538,
    index: 8,
  },
  {
    id: 54760685,
    url: 'https://img.com-x.life/comix/17767/610982/1733835313.1639.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 2000,
    height: 1538,
    index: 9,
  },
  {
    id: 54760686,
    url: 'https://img.com-x.life/comix/17767/610982/1733835314.679.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 10,
  },
  {
    id: 54760687,
    url: 'https://img.com-x.life/comix/17767/610982/1733835315.5782.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 11,
  },
  {
    id: 54760688,
    url: 'https://img.com-x.life/comix/17767/610982/1733835316.4692.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 12,
  },
  {
    id: 54760689,
    url: 'https://img.com-x.life/comix/17767/610982/1733835317.383.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 13,
  },
  {
    id: 54760690,
    url: 'https://img.com-x.life/comix/17767/610982/1733835318.379.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 14,
  },
  {
    id: 54760691,
    url: 'https://img.com-x.life/comix/17767/610982/1733835319.2762.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 15,
  },
  {
    id: 54760692,
    url: 'https://img.com-x.life/comix/17767/610982/1733835320.1779.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 2000,
    height: 1538,
    index: 16,
  },
  {
    id: 54760693,
    url: 'https://img.com-x.life/comix/17767/610982/1733835321.7229.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 17,
  },
  {
    id: 54760694,
    url: 'https://img.com-x.life/comix/17767/610982/1733835322.6278.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 18,
  },
  {
    id: 54760695,
    url: 'https://img.com-x.life/comix/17767/610982/1733835323.5127.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 19,
  },
  {
    id: 54760696,
    url: 'https://img.com-x.life/comix/17767/610982/1733835324.4145.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 20,
  },
  {
    id: 54760697,
    url: 'https://img.com-x.life/comix/17767/610982/1733835325.3065.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 21,
  },
  {
    id: 54760698,
    url: 'https://img.com-x.life/comix/17767/610982/1733835326.2234.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 1200,
    height: 1845,
    index: 22,
  },
  {
    id: 54760699,
    url: 'https://img.com-x.life/comix/17767/610982/1733835327.1076.jpg',
    headers: {Referer: 'https://com-x.life/'},
    cache_key: '2818811-0',
    width: 2000,
    height: 1538,
    index: 23,
  },
];

export default function App() {
  const W = Dimensions.get('window').width;
  const initialScrollIndex = 20;

  const gettSizeOfTheImageToTheScreen = item =>
    parseInt((W / item.width) * item.height, 10);

  // Calculate cumulative heights using useMemo
  const cumulativeHeights = React.useMemo(() => {
    return IMAGES.reduce((acc, item, index) => {
      const currentHeight = gettSizeOfTheImageToTheScreen(item);
      acc.push((acc[index - 1] || 0) + currentHeight); // Add current height to the previous sum
      return acc;
    }, []);
  }, [IMAGES, W]);

  // Function to get cumulative height of all images up to the given index
  const gettSizeOfAllImagesToTheScreen = index =>
    cumulativeHeights[index - 1] || 0; // Return 0 for index 0

  return (
    <FlatList
      data={IMAGES}
      initialNumToRender={3}
      maxToRenderPerBatch={2}
      initialScrollIndex={initialScrollIndex}
      keyExtractor={item => `${item.id}`}
      getItemLayout={(data, index) => {
        const ITEM_HEIGHT = gettSizeOfTheImageToTheScreen(data[index]);

        return {
          length: ITEM_HEIGHT,
          offset: gettSizeOfAllImagesToTheScreen(index),
          index,
        };
      }}
      renderItem={({item}) => (
        <Image
          style={{
            width: W,
            height: gettSizeOfTheImageToTheScreen(item),
            resizeMode: 'contain',
          }}
          source={{
            uri: item.url,
            headers: item.headers,
          }}
        />
      )}
    />
  );
}
`


try this

**Comment by valery-lavrik** [comment]
Thank you very much!   it worked, I didn't think it could be a problem...

**Comment by princektripathi** [comment]
@shubhamguptadream11, it is resolved. You can can close this issue.
