### ISSUE TITLE
React Native DevTools Fails to Open on Fresh Install: `TypeError: fetch failed`

### ISSUE THREAD

**Issue by aabuhijleh** [facebook/react-native#48384]
### Description

I can't open React Native DevTools on a fresh install using the latest version. 

I'm getting the following error

```sh
Failed to open the React Native DevTools.
TypeError: fetch failed
```

And I'm not the only one facing this issue. See https://github.com/react-native-community/discussions-and-proposals/discussions/819#discussioncomment-11355384

### Steps to reproduce

Here's a repo where I can reproduce this issue 100% of the time: https://github.com/aabuhijleh/fresh-start

```sh
# init app
$ npx create-expo-app@latest

# use development build (or don't; same issue)
$ npm install expo-dev-client

# install and run the app on android emulator (or physical device, or ios; same issue)
$ npm run android
```

Then after pressing `j`, the dev tools won't open and you get an error message instead.

### React Native Version

0.76.5

### Output of `npx react-native info`

```text
System:
  OS: macOS 15.1.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 174.23 MB / 18.00 GB
  Shell:
    version: 3.7.1
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 20.17.0
    path: ~/.local/share/nvm/v20.17.0/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.8.2
    path: ~/.local/share/nvm/v20.17.0/bin/npm
  Watchman:
    version: 2024.12.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.19072.14.2412.12360217
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.3
    wanted: ^15.1.3
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.5
    wanted: 0.76.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Screenshots and Videos

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/7323f361-bc90-41b9-9180-2d826359baf3" />

https://github.com/user-attachments/assets/f527738a-b376-40f1-bbfc-b7b64473bbc2

**Comment by aabuhijleh** [comment]
I believe this is an issue with the expo cli. So I'm opening it there https://github.com/facebook/react-native/issues/48384

**Comment by ground-beetle** [comment]
@aabuhijleh I guess wrong link 😄 You meant this [one](https://github.com/expo/expo/issues/33833)
