### ISSUE TITLE
'babelHelpers.taggedTemplateLiteral' is undefined in react native wen using tagged template strings

### ISSUE THREAD

**Issue by setdvd** [facebook/react-native#4838]
I'm trying to use tagged template strings in react native app (rn version 0.16) like this 
```javascript
    let i18n = function(){
        return 'should be fun';
    };
    console.log(i18n`not fun`);
```

I get exception - 'babelHelpers.taggedTemplateLiteral' is undefined;

if I use just template string like:
```javascript
    console.log(`Fun`);
```
It is working.

Since 0.16 rn moved to babel 6 and may be it is not only rn specific. I have check packager and "babel-plugin-transform-es2015-template-literals" included. 

Any idea?

**Comment by brentvatne** [comment]
Is this still an issue? Seems like it might have been a Babel6 bug, perhaps it is fixed now? If not, please reopen the issue :)

**Comment by setdvd** [comment]
It was solved in RN 18
