### ISSUE TITLE
[Android]Native code ,how to let a custom RN view invokes a function and callback?

### ISSUE THREAD

**Issue by everfire130** [facebook/react-native#4840]
We can call a view function like below in manager,but how to callback?
![image](https://cloud.githubusercontent.com/assets/11308837/11869126/e38717c2-a4f7-11e5-9d1a-5b2f7d40c604.png)
OR:
How to get the view instance through domNode(ReactTag) like iOS?
![image](https://cloud.githubusercontent.com/assets/11308837/11869169/543f76d0-a4f8-11e5-82f1-409792310e59.png)

**Comment by aexmachina** [comment]
@everfire130 this question doesn't belong on Github. Maybe do the project a favour and close the issue.

**Comment by brentvatne** [comment]
@everfire130 - please repost to StackOverflow or ask it in Discord :)
