### ISSUE TITLE
[Android]run-android error  

### ISSUE THREAD

**Issue by cxh80301983** [facebook/react-native#4843]
i have error code 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 23.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.902 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

i have not method

**Comment by christopherdro** [comment]
@cxh80301983 You need to install Build tools through your sdk manager.
https://facebook.github.io/react-native/docs/android-setup.html#configure-your-sdk

**Comment by cxh80301983** [comment]
thanks  I think that are configured
 
INSTALL_RECEIPT.json docs                 samples
README               etc                  sources
add-ons              extras               system-images
bin                  platform-tools       temp
build-tools          platforms            tools
/usr/local/Cellar/android-sdk/24.4

and  
.zshrc file  export ANDROID_HOME=/usr/local/Cellar/android-sdk

**Comment by cxh80301983** [comment]
thanks 
I found a solution

####中文

> 我找到解决方法了
  首先 确定 是用 brew install android-sdk 
  安装后 会在 /usr/local/Cellar/android-sdk 这个目录 
  同时 /usr/local/var/lib/android-sdk  这个目录也会存在一部分 源
  前者 一部分 以 link  后者的
  最后  要把 前者目录里的  platform-tools   build-tools   拷贝到   /usr/local/var/lib/android-sdk 
  ANDROID_HOME=/usr/local/var/lib/android-sdk  
  react-native run-android 
</code>


###English
> I found a solution
First determine with brew install android-sdk
In / usr / local / Cellar / android-sdk directory after installation
While / usr / local / var / lib / android-sdk directory will be present as part of the source
In the latter part of the former link
Finally, should the former platform-tools build-tools copied to / usr / local / var / lib / android-sdk
ANDROID_HOME = / usr / local / var / lib / android-sdk

it's ok

**Comment by dcu-sharepoint** [comment]
I am working on the windows system and this is what I get when running the app:

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

the problem is that the **read the error above for details** is nowhere to be seen, in other words, the error log is MISSING....

Have read the installation instructions several time but I can't find what is wrong... 

any leads would be greatly appreciated!!!!

**Comment by cristian-eriomenco** [comment]
This is my third attempt of getting the dev environment setup. And I got stuck with the same problem on windows 10. Slightly being sarcastic, but does it really need to be that complicated with hacking environment variables, shamanism with SDKs, AVDs, HAXM, cherry picking versions etc ? Feels like dealing with a "Touch me here.." system.

**Comment by dcu-sharepoint** [comment]
@cristian-eriomenco I feel for you. Unfortunately, these technologies are made with a MAC in mind so when it comes to windows all you hear is: **windows is useless, the terminal program is useless** and other stupid comments. when I go for a meetup on any of these technologies tied to a Microsoft technology it looks like a commercial for an apple product line along with related stupid comments about Windows and yet they're using Microsoft as the main application target.... I feel your pain.

Cheer up, you'll get it done, I finally did and now have react-native working like a charm using the Genymotion emulator and it's all good.... and on a windows 10 system from the **good for nothing, monopolistic company and we need to destroy or get rid of Micrsoft**....

Cheers

**Comment by guguji5** [comment]
@ibeeger even though I can't find the path you mentioned, but I try your command `brew cask install android-sdk` and `react-native run-android' .it works.
I don't know why.
