### ISSUE TITLE
[Idea] Layer component

### ISSUE THREAD

**Issue by maxs15** [facebook/react-native#4848]
Hey guys,

What do you think about creating a Layer component in order to improve performances ? Would it be difficult to implement ?
This issue is well described in this example: https://github.com/facebook/react-native/issues/3203
Coud be useful, I'm not an IOS expert but I guess that any view that doesn't accept any user input should be a CALayer.

**Comment by satya164** [comment]
What's a Layer component?

**Comment by maxs15** [comment]
A component based on CALayer instead of UIView currently used in the View component

**Comment by browniefed** [comment]
I'm assuming this is basically ReactNativeART, granted it doesn't currently support touch events.

**Comment by ide** [comment]
I don't know if we want to expose a Layer component. Maybe a flag on a component that tells it to use a layer? But this is the kind of prop that may get deleted in a future version of RN.

**Comment by maxs15** [comment]
I completely missed this ART component ! Awesome that's the kind of thing I was looking for :+1:
Would be definitely interesting to add some docs about it as specified in this issue: https://github.com/facebook/react-native/issues/4789

**Comment by browniefed** [comment]
@maxs15 the only issue is currently unsupported for Android, and also not touchable at each particular layer. :/

**Comment by maxs15** [comment]
Ok, well Android is another problem I'm sure this is on the roadmap.
I guess it doesn't support touch events in order to improve performances, the ability to wrap it with ``TouchableWithoutFeedback`` is enough.
Awesome examples in your blog posts @browniefed ! If someone is looking for a great example to use ART [check this out](http://browniefed.com/blog/2015/11/07/react-native-how-to-create-twitter-exploding-hearts/).
