### ISSUE TITLE
Click on button inside scrollview when textinput is focused

### ISSUE THREAD

**Issue by philolo1** [facebook/react-native#4853]
I encountered the following issue: I have a view with two textboxes and one text button. Ones i enter something in the textbox and click on the text button, i have to click twice so that it actually works. If i replace the Scrollview by a View it works. Is there a fix for it?

var TestScreen = React.createClass({
  render: function() {
    var self = this;
   return (
     <ScrollView>
       <TextInput
      placeholder='test' 
       style = {{
         height: 50, 
          backgroundColor: 'green',
       }} />
      <TextInput
      placeholder='test' 
       style = {{
         height: 50, 
          backgroundColor: 'blue',
       }} />
       <Text onPress={() => alert('click')} style = {{
       backgroundColor: 'orange', 
       }} > Text </Text>
     </ScrollView> 
   );
  }
})

**Comment by rmevans9** [comment]
http://stackoverflow.com/questions/34290787/touchableopacity-as-item-in-listview-only-reacts-after-textinput-has-lost-focus

**Comment by philolo1** [comment]
thanks!
