### ISSUE TITLE
Transfer large data between js and native (java android)

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#4856]
hi every body. i have a question.

i know we can use readableArray and writeableArray to transfer array between js and native.
But i must copy data from true array buffer to it.

Have any other way to do this (faster?) like a memory use by all js and native? I wish transfer a lot of data between them. 

Thanks

**Comment by ide** [comment]
React Native isn't designed for this because the JS <-> UI message channel needs to run at 60fps for smooth UI. Best to keep your large objects only in JS or only in native and design your APIs around that constraint.

**Comment by InnerPeace080** [comment]
Thank for your reply
