### ISSUE TITLE
UIExplorer install failed

### ISSUE THREAD

**Issue by castlesix** [facebook/react-native#4858]
run ./gradlew :Examples:UIExplorer:android:app:installDebug

error: 
react-native/ReactAndroid/src/main/java/com/facebook/react/views/webview/ReactWebViewManager.java:78: error: cannot find symbol
    if (ReactBuildConfig.DEBUG && Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
        ^
  symbol:   variable ReactBuildConfig
  location: class ReactWebViewManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:ReactAndroid:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 18.187 secs

**Comment by christopherdro** [comment]
Related #4857

**Comment by ide** [comment]
Same issue; closing this one.
