### ISSUE TITLE
Area behind warnings is not clickable after dismissing them

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#4861]
Hi,

We've recently updated our app to RN 0.16 from 0.13 and we've found these great new yellow boxes that show you warning messages. However, after you dismiss them, the area behind them is not clickable if you are using `TouchableNativeFeedback` or `TouchableHighlight`

As you can see in the screenshot, a button falls right behind the warnings. However only the thin blue line visible above it is clickable after dismissing the warning.

![captura de pantalla 2015-12-18 a las 14 09 39](https://cloud.githubusercontent.com/assets/252257/11897603/42ff5aa4-a591-11e5-8422-bb0d0d8620c9.png)

This warning is caused by the new pull to refresh component and we cannot fix it on our behalf.

Thanks, cheers,
Miguel

**Comment by ide** [comment]
Just so you're unblocked, add this to your code:

```js
console.ignoredYellowBox = [
  'Warning: Failed propType: Invalid prop `colors[0]` of type `number` supplied to `AndroidSwipeRefreshLayout`',
];
```

**Comment by maraujop** [comment]
Thank you James for the tip, it was a little painful to dismiss the warning every time.
