### ISSUE TITLE
ProgressBarAndroid doesn't work in real device.

### ISSUE THREAD

**Issue by inithink** [facebook/react-native#4868]
I'm trying to make loading progressBar on android (0.16.0).

With Genymotion, I'm very excited with react-native's ProgressBarAndroid. It's great.

But when I test with real devices, It doesn't work (does not appear).

The devices were Samsung SM-T320, SM-G906

I tried [react-native-material-kit](https://github.com/xinthink/react-native-material-kit) alternative to progressBar.

When I used [Spinner](https://github.com/xinthink/react-native-material-kit#spinner), the spinner blinks forever.
(It doesn't make circle, It is just piece of circle, The spinner's color changes on same place)

I want to attach the symptom. But I don't know how.. sorry.

Can I solve this problem?

Thanks, cheers

**Comment by satya164** [comment]
@inithink Works fine for me. Can you provide some sample code? May be a demo on http://rnplay.org ?

**Comment by brentvatne** [comment]
Closing because inactivity
