### ISSUE TITLE
the React Developer Tools extension for Google Chrome Bug?

### ISSUE THREAD

**Issue by skyming** [facebook/react-native#487]
I just do as the following:
 " Install the React Developer Tools extension for Google Chrome. This will allow you to navigate the view hierarchy if you select the React tab when the developer tools are open. " 
But ,when i install extension , restart chrome , but did't say react tab

**Comment by brentvatne** [comment]
This belongs on the [facebook/react-devtools repo](https://github.com/facebook/react-devtools)
