### ISSUE TITLE
TouchableHighlight does not work unless TouchableNativeFeedback is also included

### ISSUE THREAD

**Issue by apike** [facebook/react-native#4870]
As of 8a9b534a695c50b0199af75fe1b39d69fbddc557, the <TouchableHighlight> component doesn't work on iOS (as in, taps cause no highlight and onPress is not called) unless TouchableNativeFeedback (the Android equivalent) is also included. This isn't documented anywhere, so I believe it's a bug. I'd like to make the time to put up a reduced testcase, but in the meantime this is here for folks searching for the issue.

**Comment by satya164** [comment]
@apike Can you give a code sample of what you're facing? I don't see how that commit is related though.

**Comment by apike** [comment]
@satya164 The relevance of 8a9b534 is that is the version of react-native I was using (master from ~2 weeks ago) when I hit the issue. When I'm able I'll put together a sample project, and test it again against master to see if the problem has been fixed.

**Comment by satya164** [comment]
@apike In the commit you referenced, there is no version change. Also it says that,

> Only needed until the artifacts propagate to Maven Central

Which should have happened soon after that.

**Comment by corbt** [comment]
As of the current `master`, I'm using `TouchableHighlight` without importing `TouchableNativeFeedback` in a number of places in my app without any issues, so I'll assume this issue got resolved. If it's still a problem on the 0.18 release or on `master`, would you mind providing a test case that shows the problem? Thanks.
