### ISSUE TITLE
How to get the version of react-native

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#4871]
How can I show the version of react native in terminal?

**Comment by satya164** [comment]
```sh
grep \"version\": node_modules/react-native/package.json | sed s/\"//g | tr ' ' '\n' | tail -n 1
```

**Comment by hasen6** [comment]
That was more complex than I thought, I was expecting something like 

$ react-native version

to be the answer. What you suggested didn't work, it returned directory not found but its ok, I was able to find out from your answer that I could just go directly to node_modules/react-native/package.json and look in the file to see the version number.

Thanks for your help.

**Comment by satya164** [comment]
@hasen6 Probably you ran it from a wrong directory?

There is `react-native --version`, but it'll give the version of `react-native-cli`.

Anyways. Closing this issue now
