### ISSUE TITLE
In 0.17, WebView on Android failed to show UTF-8 characters

### ISSUE THREAD

**Issue by dozenlue** [facebook/react-native#4873]
Making JS able to set default encoding of a web view might be a solution. e.g. In Java, to call
WebSettings settings = mWebView.getSettings();
settings.setDefaultTextEncodingName("utf-8");

In React Native JS, add a property "defaultTextEncodingAndroid"?

**Comment by wzpan** [comment]
Same problem. Messy codes are shown when the page contains UTF-8 characters.

**Comment by wzpan** [comment]
My problem may have a little bit difference. I tried to display the content of [this page](http://paichyperiondev.github.io/api/posts/ciiekajt400065qtg01uwyczb.json) via setting the prop `html` of RN WebView component.

Part of the code looks like this:

``` js
componentDidMount: function() {
    this.fetchData();
  },

  fetchData: function() {
    fetch(this.props.url)
      .then((response) => response.json())
        .then((responseData) => {
          this.setState({
            title: responseData.title,
            content: responseData.content,
            permalink: responseData.permalink,
            loaded: true
          })
        })
        .done();
  },

  render: function(){
    if (!this.state.loaded) {
      return this.renderLoadingView();
    } else {
      if (this.state.content) {
        var html = '<!DOCTYPE html><html><head><link rel="stylesheet" type="text/css" href="'
          + CSS_URL
          + '" /></head><body><h1>' + this.state.title + "</h1>" + this.state.content
          + '</body></html>';
        return (
            <WebView
              style={styles.webview}
              html={html}
              startInLoadingState={true}
              automaticallyAdjustContentInsets={false}
              javaScriptEnabledAndroid={true}
              scalesPageToFit={this.state.scalesPageToFit}
              >
            </WebView>
        );
      } else {
        return this.renderLoadFail();
      }
    }
  },
```

And I can see only messy characters.

**Comment by dozenlue** [comment]
Hi, is there any plan to fix this in near releases?

**Comment by deminoth** [comment]
+1

**Comment by dozenlue** [comment]
@deminoth Thanks. Your fix did fix UTF-8 issue. I guess facebook may have it's own plan to make WebView on Android fully configurable, but your fix is the best in near term.

**Comment by brentvatne** [comment]
Shipped the PR
