### ISSUE TITLE
How to upgrade React Native

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#4874]
I wanted to follow up my previous issue regarding showing React Native version but it was closed too quickly so am posting another. I have an app running version 0.16 which is suffering from the memory leak problem, so I wanted to upgrade it to 0.17. I tried:

$ React-Native upgrade

which seems to do something but upon checking the package.json in node_modules/react-native/ it seems to still show 0.16 after the upgrade. How exactly do you upgrade for any particular app?

**Comment by satya164** [comment]
First install the RN version you want to upgrade to,

```sh
npm install -S react-native@0.17.0
```

Then do,

```sh
react-native upgrade
```

http://facebook.github.io/react-native/docs/upgrading.html#1-upgrade-the-react-native-dependency

**Comment by hasen6** [comment]
Ok thanks that worked great. I tried

$ npm install

and then

$ react-native upgrade

but that didn't do it. It seems you have to specifically select the version like you described. Its upgraded now no problem.

**Comment by hasen6** [comment]
Confirmed, the method in the link you gave won't upgrade from 0.16 to 0.17. It has to be done as you described here.

**Comment by satya164** [comment]
@hasen6 The docs tell you to change in the `package.json` file first. But the way I said is a bit easier.

May be we should update the docs. Care to send a PR?

**Comment by hasen6** [comment]
Ok I see but there are so many entries of 0.17 in the package.json file to change, also using your method here its all done automatically. Also if you change the version number yourself you have no way of knowing if it was successful or not since as far as I know, checking the package.json file is the only place to check the version number.

And a PR is what exactly? I'm new here as you can tell. :)

**Comment by satya164** [comment]
@hasen6 So many entries? There should be a "react-native" entry with the version number. Example - https://github.com/scrollback/io.scrollback.neighborhoods/blob/master/package.json#L11

You have to run `npm install` after changing the version number. It's the same as `npm install -S package@version`.

PR, short for pull request :)

I was saying we should update the documentation to say that we can do `npm install -S react-native@0.17.0` instead of manually changing in `package.json`.

**Comment by hasen6** [comment]
Yes but its like this in package.json:

      "react-native@0.17.0",
      "/Users/hasen/react/dongbeihua"
    ]
  ],
  "_from": "react-native@0.17.0",
  "_id": "react-native@0.17.0",
  "_inCache": true,
  "_location": "/react-native",
  "_nodeVersion": "4.2.1",
  "_npmUser": {
    "email": "martin.konicek@gmail.com",
    "name": "mkonicek"
  },
  "_npmVersion": "2.7.1",
  "_phantomChildren": {},
  "_requested": {
    "name": "react-native",
    "raw": "react-native@0.17.0",
    "rawSpec": "0.17.0",
    "scope": null,
    "spec": "0.17.0",

And also at the bottom. All of these were previously 0.16. You could change them but its just not that clear what to touch and what not to. Anyway the main point was that if I update the figure myself then I don't know if its successful or what version its really updated to since there are also rc versions.

Yes that would be good to update the docs but I haven't made a pull request before and after reading how to do it it doesn't seem to be the same on the facebook docs page.

**Comment by satya164** [comment]
@hasen6 I was talking about the changing the version in `package.json` in your project root, not under `node_modules`.

**Comment by hasen6** [comment]
Ok but shouldn't it also change in node_modules? It changed after using your method here, but not with the method in the docs.

**Comment by satya164** [comment]
@hasen6 After changing it and running `npm install`, it will automatically install the new version under `node_modules`.

May be it didn't change previously because you didn't run `npm install`.

**Comment by hasen6** [comment]
Like I said above: I ran

$ npm install

and then

$ react-native upgrade

I actually tried this again to be sure when I received your reply 'cos I too thought it should update to the latest version with just npm install....but surprisingly it didn't. Afterwards I tried your method above and then it did update.

**Comment by satya164** [comment]
It's 3 steps,

1. Change version in `package.json`
2. Run `npm install`
3. Run `react-native upgrade`

Or

1. Run `npm install -S react-native@version`
2. Run `react-native upgrade`

**Comment by hasen6** [comment]
Oh I see, update the package.json in your root directory, then it will know which version to update to, otherwise 'npm install' will just do nothing at all. Ok I get it now. Would be good to update the docs.
