### ISSUE TITLE
[Memory Leak] Animation Issue 

### ISSUE THREAD

**Issue by heliumsoule** [facebook/react-native#4875]
Hey guys,

I'm trying to build a mobile pool game in React Native for experience and am running into problems concerning garbage collection. Right now I have ten circles that are being rendered simultaneously that bounce around the screen. However, memory consumption for the application is increasing over time and I don't know how to address this issue. 

It seems like this was a React Native problem in earlier versions and I do notice falls in memory over time as shown in the graph here but in a much larger application, I am concerned that this may be issue. Has anyone else had similar issues or have solutions? 

The relevant code is here and any help is greatly appreciated. Thank you!

```js
'use strict';

var React = require('react-native');
var Dimensions = require('Dimensions');
var screenWidth = Dimensions.get('window').width;
var screenHeight = Dimensions.get('window').height;

var {
    AppRegistry,
    StyleSheet,
    Text,
    View,
    Animated,
    TouchableWithoutFeedback,
    ListView
} = React;

var SQUARE_DIMENSIONS = 30;
var TIMING_CONFIG = {duration: 30};
var DIST_TO_EDGE = screenWidth * .39;
var startCount = 10;

var Test = React.createClass({
    getInitialState: function() {
        var circs = [];
        for (var i = 0; i < startCount; i++) {
            circs.push({
                id: i,
                x: 0,
                y: 0,
                vx: 2 + Math.random() * 2,
                vy: 2 + Math.random() * 2,
                dx: 0,
                dy: 0,
                cOb: new Animated.ValueXY({x: 0, y: 0}),
            });
        }

        return {
            circles: circs,
            stop: 1
        };
    },
    stopCircle: function() {
        this.state.stop = -1 * this.state.stop;
        this.setState(this.state);
    },
    componentDidMount: function() {
        this.animateCircles();
    },
    animateCircles: function() {
        this.triggerAnimation(this.animateCircles);
    },
    triggerAnimation: function(ani) {
        for (var i = 0; i < this.state.circles.length; i++) {
                var cCircle = this.state.circles[i];
                if (cCircle.x * cCircle.x + cCircle.y * cCircle.y > DIST_TO_EDGE * DIST_TO_EDGE) {
                    var prevX = cCircle.x - cCircle.vx;
                    var prevY = cCircle.y - cCircle.vy;
                    var exitX = (1.5 * prevX + .5 * cCircle.x) / 2;
                    var exitY = (1.5 * prevY + .5 * cCircle.y) / 2;
                    cCircle.x = prevX;
                    cCircle.y = prevY;

                    var exitRad = Math.sqrt(exitX * exitX + exitY * exitY);
                    exitX = exitX * DIST_TO_EDGE / exitRad;
                    exitY = exitY * DIST_TO_EDGE / exitRad;

                    var twiceProjFactor = 2 * (exitX * cCircle.vx + exitY * cCircle.vy) / (DIST_TO_EDGE * DIST_TO_EDGE);
                    cCircle.vx = cCircle.vx - twiceProjFactor * exitX;
                    cCircle.vy = cCircle.vy - twiceProjFactor * exitY;
                    break;
                }
        }
        if (this.state.stop == 1) {
            for (var k = 0; k < this.state.circles.length; k++) {
                this.state.circles[k].x += this.state.circles[k].vx;
                this.state.circles[k].y += this.state.circles[k].vy;
            }
        }
        this.setState(this.state);
        var animateC = [];
        for (var i = 0; i < this.state.circles.length; i++) {
            var currCirc = this.state.circles[i];
            animateC.push(
                Animated.timing(currCirc.cOb, {
                    ...TIMING_CONFIG,
                    toValue: {x: currCirc.x, y: currCirc.y}
            }));
        }
        Animated.parallel(
            animateC
        ).start(ani);
    },
    getStyle: function(which) {
        return [
            styles.circle,
            {transform: this.state.circles[which].cOb.getTranslateTransform()}
        ];
    },
    render: function() {
        return (
            <View style={styles.container}>
                <View style={styles.edge}>
                </View>
                {
                    this.state.circles.map(function(c, i) {
                        return (
                            <TouchableWithoutFeedback key={i} onPress={this.stopCircle}>
                                <Animated.View style={this.getStyle(i)} />
                            </TouchableWithoutFeedback>
                        );
                    }, this)
                }
            </View>
        );
    },
});


var styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'column',
    },
    circle : {
        width: screenWidth * .1,
        height: screenWidth * .1,
        backgroundColor: 'blue',
        borderRadius: screenWidth * .1 / 2,
        position: 'absolute',
        left: screenWidth * .45,
        top: screenWidth * .81
    },
});

AppRegistry.registerComponent('Test', () => Test);
```

The application can be found at https://github.com/heliumsoule/React-Native-Pool if you want to run the application for yourself.

Thank you again.

**Comment by brentvatne** [comment]
Discussed in email, couldn't reproduce, @tadeuzagallo may look into it when he has time!

**Comment by jozn** [comment]
I tested his code but didn't see any significant memory increase. JS memory usage has increased but not with fast rate. but react-native has a serious memory leak problem. I have opened another issue with an example code that shows how view object doesn't get destroyed after releasing reference to it's instance, see #4963 and test it.

**Comment by heliumsoule** [comment]
Jozn,

How long did you run the code and under what conditions? I let it run for
around two hours and noted a significant memory increase of 1.5x to 2x.
Thanks.

Hsoule

**Comment by jozn** [comment]
I test it again and in 15 min memory usage has increased from 49MB to 63MB. and most of that increase was in js side. surely  there is memory leak problem here.
For now what is holding me back for using RN in production is memory leak like the one i have put in #4963 .
Thanks

**Comment by brentvatne** [comment]
@tadeuzagallo - did you have a chance to look into this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/memory-leak-animation-issue-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
