### ISSUE TITLE
Android: Public interface to recreateReactContextInBackground()

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native#4877]
Hi,

is it possible to make 
`````javascript
recreateReactContextInBackground()
``````
 a public interface? I need to reload RN from within JS and I thought about writing a native module to call this method. 

In iOS, i use 
````javascript
[self.bridge reloadBridge]
````
@mhorowitz What do you think about that? I've seen that you have worked on this part. Would you accept a PR for that?

Regards
Philipp

**Comment by Richard-Cao** [comment]
you can use 
```
/**
     * Path to the JS bundle file to be loaded from the file system.
     *
     * Example: {@code "assets://index.android.js" or "/sdcard/main.jsbundle}
     */
    public Builder setJSBundleFile(String jsBundleFile) {
      mJSBundleFile = jsBundleFile;
      return this;
    }
```
this method

**Comment by Richard-Cao** [comment]
you can use 
```
/**
     * Path to the JS bundle file to be loaded from the file system.
     *
     * Example: {@code "assets://index.android.js" or "/sdcard/main.jsbundle}
     */
    public Builder setJSBundleFile(String jsBundleFile) {
      mJSBundleFile = jsBundleFile;
      return this;
    }
```
this method

**Comment by satya164** [comment]
@PhilippKrone You can just add some method in Java which restarts the activity and call the method from JS. And then on the restart, set the path to new URL.

**Comment by PhilippKrone** [comment]
@satya164 Yea I know, but I wonder whether using the method recreateReactContextInBackground() isnt easier / better, as 1) its more like iOS concerning reloading bridge I think and secondly, the description of this method seems to say exactly what I want to be - only point is that it isnt public and I wonder / would like to know why. Does it have any drawbacks to use this method?

**Comment by satya164** [comment]
@PhilippKrone I've no idea what this method actually does. And making methods public always has a risk, you can't change them ever! I think its fine though, restarting activity.iOS doesn't have a concept of activity at all, so we can't really map everything to how it works on iOS. I guess code push also restarts the activity.

If this is about OTA updates to bundle, in the app I'm working on, I don't prompt the user to reload the bundle at all. It's loaded silently in background and used when he uses the app next time. Much simpler.

**Comment by PhilippKrone** [comment]
@satya164 Yea, concerning not being able to change it ever, I agree. I'm using codepush for OTA, but I'm currently experimenting with reloading bundles dynamically for a different use case - and as "createReactContextInBackground()" is public, I was just wondering why "recreateReactContextInBackground()" isnt - and especially whether a PR here would be fine or not ;)

**Comment by satya164** [comment]
@PhilippKrone Okay. Cool then.

If I may ask, what's the use case? Just eager to know.

I don't know if there are any plans to make it public or not though May be you can send a PR and discuss the use cases and see?

**Comment by brentvatne** [comment]
Simple enough for it to be an easy PR, @PhilippKrone can you make it public and explain your use case in a PR?

Thanks!
