### ISSUE TITLE
[Android] TouchableOpacity transparency bug

### ISSUE THREAD

**Issue by gre** [facebook/react-native#4878]
Tested on RN 0.17.
TouchableOpacity transparency is not working on Android, and it's inconsistent with iOS.

<img width="662" alt="screen shot 2015-12-19 at 21 00 33" src="https://cloud.githubusercontent.com/assets/211411/11914995/b9efa29c-a693-11e5-9b62-09cc3d0bbab6.png">

```html
          <View style={{ position: "relative", width: 256, height: 180 }}>
            <TouchableOpacity>
              <Image source={{ uri: "http://i.imgur.com/qM9BHCy.jpg" }}
                style={{
                  width: 256,
                  height: 180,
                  position: "absolute",
                  top: 0,
                  left: 0
                }}
              />
            </TouchableOpacity>
            <View style={{
                position: "absolute",
                top: 0,
                left: 0,
                backgroundColor: "rgba(255,0,0,0.5)",
                width: 256,
                height: 180
              }} />
          </View>
```

Note that, if removing the `<TouchableOpacity>`, it works the same:

<img width="644" alt="screen shot 2015-12-19 at 21 02 46" src="https://cloud.githubusercontent.com/assets/211411/11914999/e0405afe-a693-11e5-842c-811591b0716b.png">

https://productpains.com/post/react-native/android-content-absolute-over-touchableopacityimage-make-the-image-disappear/

**Comment by ms88privat** [comment]
I'm not sure but you could try something like this: 

```jsx
<TouchableOpacity>
  <Image source={{ uri: "http://i.imgur.com/qM9BHCy.jpg" }}
    style={{
      width: 256,
      height: 180,
      position: "absolute",
      top: 0,
      left: 0,
   }}
  >
    <View style={{
      flex: 1, 
      backgroundColor: "rgba(255,0,0,0.5)",
      }} 
     />
  </Image>
</TouchableOpacity>

```

**Comment by gre** [comment]
Image can have children? weird
I can probably find a workaround getting this to work (like moving the touchableopacity on top) but that still make the initial code a bug.

**Comment by satya164** [comment]
@gre If you want to set the image as the background, the correct way would be to add the element as children of `<Image />` as @ms88privat described.

**Comment by gre** [comment]
Ok cool :) nice tip, thanks.

But that's still a bug (or at least an inconsistency with iOS) on absolute
positioning I guess (imagine if my layer with opacity takes the full
viewport).

2015-12-20 12:18 GMT+01:00 Satyajit Sahoo <notifications@github.com>:

> @gre <https://github.com/gre> If you want to set the image as the
> background, the correct way would be to add the element as children of <Image
> /> as @ms88privat <https://github.com/ms88privat> described.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/4878#issuecomment-166110596>
> .
>



-- 
Gaëtan Renaudeau, greweb.fr / @greweb <https://twitter.com/greweb> /
Github: gre <https://github.com/gre>

**Comment by satya164** [comment]
@gre Yeah. Can you post this on product pains :)

**Comment by gre** [comment]
created https://productpains.com/post/react-native/android-content-absolute-over-touchableopacityimage-make-the-image-disappear/

**Comment by alex3t** [comment]
same problem. 
fixed by moving `position: 'absolute'` style to TouchableOpacity from child View component

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-touchableopacity-transparency-bug

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
