### ISSUE TITLE
Unable to fetch location within 0s.

### ISSUE THREAD

**Issue by Grmiade** [facebook/react-native#4879]
When i try to get my position with the proposed example in docs (https://facebook.github.io/react-native/docs/geolocation.html), i have this error: `Unable to fetch location within 0s.` 
I have tried on simulator with a location and on device. Same error :/
An idea ? I use v0.17.0.

**Comment by Pikaurd** [comment]
@Grmiade That seems a bug in v0.17.0
[A quick fix](https://gist.github.com/Pikaurd/636069c6ee4cb03c89d1) here
but this version will ignore `accuracy`. :(

**Comment by Grmiade** [comment]
Thanks @Pikaurd, i will test that.

**Comment by skevy** [comment]
@Grmiade would you be able to try this on master and let us know if the bug still exists?

**Comment by seb0zz** [comment]
@skevy issue is fixed on master (could reproduce it on 0.17.0 and tested it on master)

**Comment by satya164** [comment]
Closing. Let's reopen if you are still facing the bug.

**Comment by npomfret** [comment]
I get this error when trying to get a gps position during a callback for a push notification.  Any idea whats going on?
