### ISSUE TITLE
Can't find variable: __fbBatchedBridge (line 1 in the generated bundle)

### ISSUE THREAD

**Issue by steve-ng** [facebook/react-native#4881]
new project on react-native 0.17.0 Android

does anyone experience this too?

**Comment by qbig** [comment]
@steve-ng There is a chance that your packager is not running. This happens when you tried to pass an empty bundle file to jsc to execute.

**Comment by steve-ng** [comment]
thanks @qbig is there any possible place that I can check this? I didn't fiddle with my packager

**Comment by NexusLee** [comment]
I got this error too

**Comment by NexusLee** [comment]
![image](https://cloud.githubusercontent.com/assets/4703440/11917917/fb60126c-a755-11e5-9bfe-8be1646c08b3.png)

**Comment by onzag** [comment]
I'm getting this error as well, however if I switch to production then it doesn't happen.

**Comment by qbig** [comment]
@steve-ng not sure but if you 'npm start' at your project dir did the packager start normally? @onzag if you switch to production, you would be using a pre-bundle file. So it wouldn't happen.

**Comment by onzag** [comment]
@qbig I understand that, what I'm supposing is that the server is not actually running; but my question is, as I run react-native run-android I don't really seem to get any server running, I'm trying to find out where it is, but all the good guides I find are for xcode. I'm a bit lost here.

**Comment by trungdq88** [comment]
Having a same issue here.

**Comment by trungdq88** [comment]
Having a same issue here. Can't run the default project on Android (iOS still works).

**Comment by onzag** [comment]
@qbig @steve-ng @trungdq88 I found what's the reason of this issue, first make sure you have watchman installed if you're on windows or linux; https://facebook.github.io/watchman/docs/install.html

Then you make sure to run react-native start before running react-native run-android so that the server, and the packager is running... you'll most likely anyway hit the error.

Shake your device or hit the menu and go to Dev Settings, Debug Server host and port, seek for the host and port of your computer, and put them there... eg. 192.168.1.4:8081 in my case, then shake again and click reload JS, all it's set up :)

**Comment by onzag** [comment]
Also make sure you have the gradle daemon running just that it doesn't take ages. https://docs.gradle.org/2.9/userguide/gradle_daemon.html happy coding :)

**Comment by trungdq88** [comment]
@onzag thank you, it works now. Btw, my server is automatically start when I run `react-native android`, so I think might be a gradle daemon problem. (Or is it just works because I just have restarted my device?)

**Comment by onzag** [comment]
@trungdq88 well to be fair I'm not sure, I've never used gradle before, also, I'm on linux mint now, it might be a platform differences problem, if you're using mac that's what it supposed to happen.

I also noticed that the device has to be connected to the same network of the computer, I'm trying to find a workaround for offline usage, because making sure that the device is connected wirelessly in the same LAN of the computer could be annoying in some circumstances.

**Comment by hiquanta** [comment]
how to solve this?

**Comment by andreyluiz** [comment]
Same here.

**Comment by andreyluiz** [comment]
I tried to run ```react-native start``` and I got:
```
Looking for JS files in
   /home/andrey/Projects/React/NativeTest 

[11:31:16] <START> Building Dependency Graph
[11:31:16] <START> Crawling File System
[11:31:16] <START> Loading bundles layout
[11:31:16] <END>   Loading bundles layout (0ms)

React packager ready.
```

Next I tried to issue in another terminal the command ```react-native run-android``` to run in my Nexus 5, connected to my laptop. The packager terminal added the following:

```
[11:31:43] <END>   Crawling File System (26401ms)
[11:31:43] <START> Building in-memory fs for JavaScript
[11:31:47] <END>   Building in-memory fs for JavaScript (4036ms)
[11:31:47] <START> Building in-memory fs for Assets
[11:31:51] <END>   Building in-memory fs for Assets (3884ms)
[11:31:51] <START> Building Haste Map
[11:31:53] <START> Building (deprecated) Asset Map
[11:31:53] <END>   Building (deprecated) Asset Map (777ms)
[11:31:54] <END>   Building Haste Map (3028ms)
[11:31:54] <END>   Building Dependency Graph (37950ms)
```

The app starts in my Nexus, but still the error occurs.
Any tips?

**Comment by elinac** [comment]
I got the same error when i try to run react-native/Examples/UIExplorer release apk.I slove it after I change the BundleAssetName and JSMainModuleName  in  react-native\Examples\UIExplorer\android\app\src\main\java\UIExplorerActivity.java.
Maybe you can try  correcting your React-Native  Actitivy.

**Comment by satya164** [comment]
Make sure that you also run `adb reverse tcp:8081 tcp:8081` when testing on device.

**Comment by qbig** [comment]
based on the number of ppl got stuck on this, maybe #4739 ? Should be a useful but minor fix.

**Comment by satya164** [comment]
@qbig A PR to improve the error message is much appreciated.

**Comment by dkokic** [comment]
Just to make it clear, this error shows after updating react-native dependencies to 0.17.0 
The very same code "works" with react-native 0.16.0 (packager running, reverse proxy set)

**Comment by onzag** [comment]
@andreyluiz Currently you have to shake your device and pick in Dev settings the ip and port of your computer so that the device can access the server.

**Comment by onzag** [comment]
@dkokic in 0.17.0 you don't need to set the reverse proxy... you just have to set the IP and port of your computer, that's for remove usage, so it makes sense to use it that way. However I may be wrong, I only started using this library 1 week ago.

**Comment by brentvatne** [comment]
Related to #4739, PR welcome to improve the message!

**Comment by herbertdai** [comment]
Thanks @satya164,  `adb reverse tcp:8081 tcp:8081`  this fixed my issue.

**Comment by andreyluiz** [comment]
It worked. @satya164  :+1:

**Comment by raunaqrox** [comment]
`adb reverse tcp:8081 tcp:8081`
this only works for android 5.0+ (API 21)

**Comment by cubbuk** [comment]
Same here, I tried to run it on genymotion emulator. I had to run `adb reverse tcp:8081 tcp:8081`, then `react-native start` then `react-native run-android` to run an android app on Ubuntu 14.04. I am using `react-native 0.17.0` as a dependency.

**Comment by sfatih** [comment]
My problem solved!
I was getting this error when i try to 
`react-native run-android` on stock android avm 
![screenshot_2016-02-15-13-32-08-](https://cloud.githubusercontent.com/assets/11010650/13047736/e3ba8b68-d3e9-11e5-8285-9090cceb46d4.png)

What I do?
After Run `react-native run-android` and get "_fbBatchedBridge" error, 
i run `react-native start`
![react-packager](https://cloud.githubusercontent.com/assets/11010650/13047885/dd0aa09a-d3ea-11e5-8850-75c7eb9f37bc.PNG)
Then clicked "Reaload JS" button on AVM,
Then waited for some(about 1.5 min) process in packager and i get this:
![react-packager2](https://cloud.githubusercontent.com/assets/11010650/13047960/442ea442-d3eb-11e5-86a8-66913e0a8d2e.PNG)

Then my app ready:
![react-avm-running](https://cloud.githubusercontent.com/assets/11010650/13048004/8ef53cd4-d3eb-11e5-89f2-074fbab4841c.PNG)

**Comment by ufo22940268** [comment]
@stavash Thanks. It works. I think this answer should go to tutorial.
