### ISSUE TITLE
not sure if javascript

### ISSUE THREAD

**Issue by yonatanmn** [facebook/react-native#4885]
please review code example

https://github.com/facebook/react-native/blob/master/docs/Animations.md

typescript perhaps?

**Comment by ms88privat** [comment]
@yonatanmn What is your question or bug report here? The code examples in the link are in javascript 2015 (e.g "ES6" / "ES2015" ).

**Comment by yonatanmn** [comment]
line 2:
` constructor(props: any) {`
8: 
`render(): ReactElement {`

I think the rest is fine

**Comment by satya164** [comment]
@yonatanmn It's ES2015 + JSX + Flow

http://flowtype.org

**Comment by yonatanmn** [comment]
ahhh flow... thx!

**Comment by yonatanmn** [comment]
maybe 
`/* @flow */`
will be informative
