### ISSUE TITLE
iOS: Geolocation with NSLocationAlwaysUsageDescription

### ISSUE THREAD

**Issue by seb0zz** [facebook/react-native#4886]
I use version 0.17.0 of React Native

Geolocation works for me if I use `NSLocationWhenInUseUsageDescription` like mentioned in the documentation on https://facebook.github.io/react-native/docs/geolocation.html. Unfortunately it doesn't ask for the permissions if I specify `NSLocationAlwaysUsageDescription` in my `Info.plist`. Is this a known issue?

Could also be related to #4879

**Comment by christopherdro** [comment]
@seb0zz I think if you've accepted Location permissions once it won't ask you again unless you clear the settings.

It might be easier to just setup a new app and test `NSLocationAlwaysUsageDescription`.

**Comment by seb0zz** [comment]
@christopherdro That was my first thought, too. So I tested my app on a real iOS device. I am now able to reproduce the problem by the following steps:

1. Add `NSLocationWhenInUseUsageDescription` to my plist file
2. Deploy to my real device
3. Get asked for permissions
4. Uninstall the app from my real device
5. Change the key in my plist file to `NSLocationAlwaysUsageDescription`
6. Deploy to my real device
7. Not receiving any request for permissions
8. Uninstall again and redeploy with `NSLocationWhenInUseUsageDescription` 
9. Get asked for the permissions again

**Comment by seb0zz** [comment]
When I test this on master `NSLocationAlwaysUsageDescription` does not get ignored but throws an error message.

![image](https://cloud.githubusercontent.com/assets/1436535/11968769/0a226050-a910-11e5-9a15-ed482b65704d.png)

**Comment by brentvatne** [comment]
@seb0zz - you can add both and `NSLocationWhenInUseUsageDescription` will be ignored - https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18

If you want to fix this, it should be a very easy PR :) https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L328-L333 - just update this block to check for either of them. I will merge right away! :rocket:
