### ISSUE TITLE
How can I get the selected text from TextInput

### ISSUE THREAD

**Issue by ibraheemabukhdair** [facebook/react-native#4887]
I was wondering how can I get selected text from TextInput? It does not seem to be a UIControl with events at all. If someone could give me some direction that would be great. Thank you.

**Comment by brentvatne** [comment]
You can use the `onSelectionChange` prop: https://github.com/facebook/react-native/blob/36d26c7d3b09cc7f241ceb3d5f5be26a8c88f213/Libraries/Components/TextInput/TextInput.js#L399-L405 - currently only available on iOS. If you need this for Android, I'd suggest opening up a request on ProductPains!

**Comment by narychen** [comment]
It's still not supported on Android.
