### ISSUE TITLE
Add more documentation on `Dimensions`, e.g. `Dimensions.get('window').width;`

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#4888]

**Comment by niftylettuce** [comment]
In particular we should document that stuff like `Dimensions.get('window').width` will return points and not pixels.  Per <http://www.paintcodeapp.com/news/iphone-6-screens-demystified>.  We should document some examples maybe?  This is super useful for responsive design with screen height sizes.

**Comment by christopherdro** [comment]
@niftylettuce That sounds like a good idea!

Do you think you can provide a few examples and submit a PR?

**Comment by niftylettuce** [comment]
@christopherdro no time at the moment :frowning:

**Comment by brentvatne** [comment]
PR welcome but going to close issue because we could have a million of these :P
