### ISSUE TITLE
Android - Method POST must have a request body

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#4890]
It looks like we can't send POST requests without a body.

Might be a bug with our HTTP Android layer?

https://github.com/square/retrofit/issues/854
https://stackoverflow.com/questions/30626100/failed-to-get-request-token-method-post-must-have-a-request-body

Not sure where it comes from, but I'm assuming the patch for now is to just send over a blank request body.

**Comment by lexs** [comment]
This should already have been fixed: https://github.com/facebook/react-native/pull/4518

Please reopen if this is incorrect.
