### ISSUE TITLE
Node Gyp build fail

### ISSUE THREAD

**Issue by mrcmrc** [facebook/react-native#4893]
System: Windows 10
Location:Brazil
Hello, i try start a project using react-native, but the cmd returns a node gyp error.

C:\Users\anton\trimtrim>react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\Users\anton\trimtrim\AwesomeProject                Installing react-native package from npm...

> utf-8-validate@1.2.1 install C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Compilando os projetos desta solu��o um de cada vez. Para habilitar a compila��o paralela, adicione a op��o "/m".
MSBUILD : error MSB3428: N�o foi poss�vel carregar componente "VCBuild.exe" do Visual C++. Para corrigir isso, 1) instale o .NET Framework 2.0 SDK, 2) instale o Microsoft Visual Studio 2005 ou 3) adicione o local do componente ao caminho do sistema se ele estiver instalado em outro local.  [C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate\build\binding.sln]

> bufferutil@1.2.1 install C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Compilando os projetos desta solu��o um de cada vez. Para habilitar a compila��o paralela, adicione a op��o "/m".
MSBUILD : error MSB3428: N�o foi poss�vel carregar componente "VCBuild.exe" do Visual C++. Para corrigir isso, 1) instale o .NET Framework 2.0 SDK, 2) instale o Microsoft Visual Studio 2005 ou 3) adicione o local do componente ao caminho do sistema se ele estiver instalado em outro local.  [C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil\build\binding.sln]

> spawn-sync@1.0.13 postinstall C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\yeoman-generator\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@1.0.6
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\anton\trimtrim\AwesomeProject\node_modules\react-native\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json.b6548ef82219bd9e82e1b2029ba5b4f4
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json.b6548ef82219bd9e82e1b2029ba5b4f4' -> 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json.b6548ef82219bd9e82e1b2029ba5b4f4' -> 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\anton\\AppData\\Roaming\\npm-cache\\is-arrayish\\0.2.1\\package\\package.json.b6548ef82219bd9e82e1b2029ba5b4f4',
npm ERR!   dest: 'C:\\Users\\anton\\AppData\\Roaming\\npm-cache\\is-arrayish\\0.2.1\\package\\package.json',
npm ERR!   parent: 'error-ex' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\anton\trimtrim\AwesomeProject\npm-debug.log

`npm install --save react-native` failed

What is this? You can help me?

**Comment by rmevans9** [comment]
It looks like it ran into a permissions issue when trying to do a rename operation.

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json.b6548ef82219bd9e82e1b2029ba5b4f4' -> 'C:\Users\anton\AppData\Roaming\npm-cache\is-arrayish\0.2.1\package\package.json'

I would recommend running npm cache clean and trying again. See logged issue on NPM's repo: https://github.com/npm/npm/issues/10826

**Comment by mrcmrc** [comment]
@rmevans9 I clear npm cache, but this error continues.
![image](https://cloud.githubusercontent.com/assets/3610681/11969414/6fe92758-a900-11e5-8afc-ebdcaa959b87.png)

What i can do?
