### ISSUE TITLE
tabbar run on 0.17  error

### ISSUE THREAD

**Issue by atlas1119** [facebook/react-native#4896]
my app run on 0.16 ,no error ,but run 0.17  run error.  the reason is tabbar icon is error.
![image](https://cloud.githubusercontent.com/assets/9478646/11923089/54ee48de-a7d9-11e5-9fcd-c217648d2a10.png)

please help me, why?

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow, thanks!
