### ISSUE TITLE
no clicks are registering on 0.17.0

### ISSUE THREAD

**Issue by eyaleizenberg** [facebook/react-native#4898]
Hi,
I just upgraded to RN 0.17 and for some reason none of my clicks are working at all. Any ideas?

**Comment by satya164** [comment]
@eyaleizenberg Can you provide a code sample? Which platform are you on?

**Comment by eyaleizenberg** [comment]
I am running on Xcode Version 7.1 (7B91b), RN 0.17.0

**Comment by eyaleizenberg** [comment]
OK, so the issue was related to a modal I had which for some reason was interrupting the other views. I had to move it up the 'dom' in order to get this to work.
