### ISSUE TITLE
[ANDROID] generating apk stuck

### ISSUE THREAD

**Issue by turka50** [facebook/react-native#4901]
Hi , 

This is the command i used to generate the apk : 
 cd android && ./gradlew assembleRelease

It seems to run but it gets stuck on :app:bundleReleaseJsAndAssets.

Any ideas ? 
Thanks.

**Comment by turka50** [comment]
![image](https://cloud.githubusercontent.com/assets/10440278/11929861/42c17966-a7e7-11e5-9f71-32138f88058e.png)

This is the error i'm getting .

**Comment by turka50** [comment]
Issue resolved after upgrading to 0.17

**Comment by onzag** [comment]
I'm getting this issue on 0.17

**Comment by jaimecorrea** [comment]
Same issue!
