### ISSUE TITLE
SyntaxError: Unexpected use of reserved word 'import'

### ISSUE THREAD

**Issue by cancan101** [facebook/react-native#4910]
In RN 0.17: I am getting: `SyntaxError: Unexpected use of reserved word 'import'`:
![image](https://cloud.githubusercontent.com/assets/51059/11938806/6c6cc6c2-a7eb-11e5-988c-0a5b960bff5f.png)
with `.babelrc`:
```json
{
  "presets": ["es2015"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-es2015-classes",
    "transform-export-extensions",
    "transform-runtime"
  ]
}
```

**Comment by mihirsoni** [comment]
Hi @cancan101 

Could you please provide a code snippet you are trying to run ?

**Comment by cancan101** [comment]
Caused by `"transform-runtime"` running before certain other transforms. Fixed by removing it from the list.
