### ISSUE TITLE
pod mananger

### ISSUE THREAD

**Issue by PWDream** [facebook/react-native#4914]
hello,I manager the react use pod ,but the version is 0.13 now, can I how update? thanks

**Comment by ide** [comment]
Please refer to the docs: https://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods

> CocoaPods is a package management tool for iOS/Mac development. We need to use it to download React Native. If you haven't installed CocoaPods yet, check out this tutorial.
>
> When you are ready to work with CocoaPods, add the following lines to Podfile. If you don't have one, then create it under the root directory of your project.
>
```
# Depending on how your project is organized, your node_modules directory may be
# somewhere else; tell CocoaPods where you've installed react-native from npm
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
  # Add any other subspecs you want to use in your project
]
```
> Remember to install all subspecs you need. The <Text> element cannot be used without the RCTText subspec, for example.
>
>Then install your pods:
```
$ pod install
```
