### ISSUE TITLE
Initialise a react-native project with a specific react-native version

### ISSUE THREAD

**Issue by jacobbubu** [facebook/react-native#4917]
For now, initialise a new rect-native project using react-native-cli can not specify the react-native version that the new project use (react-native-cli can only install the latest version of react-native from npm).

Since that the react-native has a very frequent release cycle (2 weeks) and brings breaking changes in common. We need to do a lot of cross versions verifications for our codes and 3rd packages.

I hope that the `react-native-cli init` may have an extra argument to specify  the version of react-native that the new project may used.

I've just copied and changed the code from `react-native-cli` and published to npm as a new tool [`rninit`](https://github.com/jacobbubu/rnini) to do that things, but that would be more convenient if this feature could be added to `react-native-cli` itself.

**Comment by satya164** [comment]
@jacobbubu I don't think this can be something in core as we don't support old React Native versions.

You should commit the generated android and ios files to version control and not generate a new project everytime. Genrate a new project only when it's actually new.

**Comment by jacobbubu** [comment]
Two weeks ago, I tried the [gl-react-native](https://github.com/ProjectSeptemberInc/gl-react-native) on react-native version 0.15 and found that all of the examples provided by gl-react-native did not work.

And then I setup [Sinopia](https://www.npmjs.com/package/react-native-cli) as a npm proxy that let me use any of the version of react-native to create testing project. That is not trivia. Well, gl-react-native works fine on its original dependent react-native version.

Such thinks happened again and again when you try the 3rd components that listed on [react-parts](https://react.parts/native). You need to do a lot of version traversals to testing their compatibility and availability.

Version control has nothing to do about these things.

**Comment by satya164** [comment]
@jacobbubu Sorry for the inconvenience. React Native is currently moving in a very fast pace and things break very frequently. Hopefully we'll reach API stability soon enough, but we're not there yet.

If we allow initializing new projects with older versions of React Native, then it would mean that we have to support the old versions in terms of bug reports and questions etc. We are having a hard time managing the bug reports and don't have enough bandwidth to afford supporting older versions for now.

Of course no one is stopping you from creating tools that do these kinds of things, as you already did. That actually addresses your use case and solves your issue.

**Comment by satya164** [comment]
Also worth noting that you don't have to regenerate the project every time. To change the React Native version you can run the following inside the project,

```sh
npm install react-native@version
react-native upgrade
```

Which is probably a better and easier way.

**Comment by jacobbubu** [comment]
Yes, that is the way to do better for read-native later than version 0.13.
Thanks!
