### ISSUE TITLE
How can I auto dismiss the Alert View, without Tapping any button?

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#4919]
How can I auto dismiss the Alert View, without Tapping any button?

**Comment by satya164** [comment]
@nowaits Currently there is no wat to do this. Up for a PR?

**Comment by nowaits** [comment]
@satya164 good idea

**Comment by bradywatkinson** [comment]
Just wondering if anyone else has made progress on this? It seems to me that having this feature will be very useful

**Comment by yzfdjzwl** [comment]
I really want it ~
