### ISSUE TITLE
firefox devtools

### ISSUE THREAD

**Issue by iamdustan** [facebook/react-native#492]
What would it take to support Firefox Devtools as well? I suspect that facebook/react-devtools#56 may be a blocker.

**Comment by vjeux** [comment]
Nothing. It should work if you update the applescript to open Firefox instead of Chrome. https://github.com/facebook/react-native/blob/master/packager/launchChromeDevTools.applescript#L13

Do you want to try it out?

**Comment by iamdustan** [comment]
Trying to understand this.

Initially the whole thing errors. Removing things and going step by step my first issue is:

```
execution error: plugin-container got an error: every window doesn’t understand the “count” message. (-1708)
```

this is referring to

```
if (count every window) = 0 then
  make new window
end if
```

I’m assuming that Fx doesn’t have `every window` or it is done in a different way... do you have any good Applescript references?

**Comment by iamdustan** [comment]
Firefox has poor (relatively no) applescript support. I’m exploring other options for this.

**Comment by iamdustan** [comment]
Stepping it up to a slightly larger discussion, does it make sense to change the applescript approach to something with Webdriver for Windows (and Linux) support?

**Comment by iamdustan** [comment]
WIP incomplete support: https://github.com/facebook/react-native/compare/master...iamdustan:fx-dev-tools?expand=1

1. It assumes Firefox Developer Edition is already open.
2. It blindly opens more tabs (there isn’t a good way to view and grab active tabs that I’m aware of)

**Comment by vjeux** [comment]
The applescript is just there to open chrome/firefox on the right page, after the js opens a websocket to the node server and everything runs from there

**Comment by iamdustan** [comment]
@vjeux by `everything runs from there` I assume that the node server just pipes the JS back and forth between the browser and native processes? Or is the js running on the node instance and having it’s results piped to the browser and native processes?

**Comment by vjeux** [comment]
You probably want to look at the debugger.html source that does the piping. JS is running inside of the browser.
https://github.com/facebook/react-native/blob/master/packager/debugger.html#L34-L62
