### ISSUE TITLE
Syntax error in ImageEditingExample.js for using 'type' for Objects

### ISSUE THREAD

**Issue by vinu123** [facebook/react-native#4920]
I am getting Syntax error for the following objects. I do hope they are objects.

      type ImageOffset = {
        x: 100;
        y: 100;
      };

      type ImageSize = {
        width: 100;
        height: 100;
      };

      type TransformData = {
        offset: ImageOffset;
        size: ImageSize;
      }

How do I fix this syntax error?

**Comment by satya164** [comment]
They are [Flow](http://flowtype.org) type declarations. Babel supports stripping them out. Where are you getting syntax errors?

**Comment by satya164** [comment]
@facebook-github-bot answered
