### ISSUE TITLE
fontWeight '300' not working on Android

### ISSUE THREAD

**Issue by bodyflex** [facebook/react-native#4925]
setting `fontWeight` to `'300'` on Android doesn't make any difference although it switches to a lighter font on iOS.

example:
```xml
<Text style={{fontWeight: '300'}}>test</Text>
```

I'm using RN 0.17.0

**Comment by nicklockwood** [comment]
I think Android only supports bold and regular (I was told this is a limitation of Android itself, not just React Native)

cc: @dmmiller

**Comment by bodyflex** [comment]
Android certainly supports light fonts: http://stackoverflow.com/a/13329907/1810160

**Comment by nicklockwood** [comment]
@bodyflex in that case, I must have either misunderstood the issue, or been misinformed. If you think you know how to implement this, a PR would be appreciated.

**Comment by satya164** [comment]
@bodyflex I guess it's because you're referencing them by the font name, i.e. "roboto-thin" and not font family + weight?

**Comment by bodyflex** [comment]
@satya164 yes, that's true. but I don't think that makes it impossible to implement?

@nicklockwood I would do a PR if I had any familiarity with this code base. although, a quick look suggested that you are only using the constants in [TypeFace](http://developer.android.com/reference/android/graphics/Typeface.html), although to address this you should somehow also incorporate the font name:
```java
textView.setTypeface(Typeface.create("sans-serif-light", Typeface.NORMAL));
```

**Comment by satya164** [comment]
@bodyflex Can't you just put the font like `assets/fonts/Roboto-Thin` and then reference it in the style as `fontFamily: 'Roboto-Thin'` without specifying any fontWeight? Doesn't it work?

**Comment by bodyflex** [comment]
@satya164 if I want to use the system font on iOS instead of Roboto I'd have to do a separate check for the platform. I could make it work of course, but shouldn't the API do this for me instead?

**Comment by satya164** [comment]
@bodyflex Yeah, it should. Go ahead with the PR if you can. These are the relevant files,

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java

**Comment by bodyflex** [comment]
might look into doing a PR when I have more time. right now I'm using a work around like this:
```javascript
text: {
  fontWeight: '300',
  fontFamily: Platform.OS === 'android' && 'sans-serif-light'
}
```

**Comment by bodyflex** [comment]
would it be wrong to implement this for Android by updating only Text.js with a solution like above? so without modifying any native code.

**Comment by nicklockwood** [comment]
@bodyflex ideally we'd like to try and keep Text.js as similar as possible between iOS and Android. But you could always put up a PR and we can see if it looks reasonable as a stopgap.

**Comment by satya164** [comment]
I'd prefer to have it in native since the logic for determining the weight from filename is currently in native code. Having similar logic split across to different places seems bad IMO.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/fontweight-300-not-working-on-android

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
