### ISSUE TITLE
[Modal] Appears above the Inspector

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native#4926]
When using `Modal` the Inspector is hidden bellow the Modal, which means you can't really use the Inspector.

**Comment by yelled3** [comment]
https://productpains.com/post/react-native/modal-appears-above-the-inspector/

**Comment by tuxtux00** [comment]
Hi guys,
Is this issue fixed ? 
I can still see this bug under v0.26

**Comment by Tenkir** [comment]
This is definitely still an issue in v0.28

**Comment by stereodenis** [comment]
https://github.com/facebook/react-native/pull/9600

**Comment by mehdijjz** [comment]
why is this closed ?!
