### ISSUE TITLE
Add a dismiss event for Alert dialog

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#4928]
Currently the Alert dialog on Android can be dismissed by tapping outside or pressing back button as well as pressing on any of the action buttons. The problem with this is that you've no way of knowing that the dialog was cancelled if the user cancels it by tapping outside.

For example, consider a location based app (my use case),
- Check if GPS is enabled, if not, prompt the user to enable it
- If the user chooses to enable GPS, wait for the location data
- If the user cancels the dialog, fallback to something else

I'm not sure what'll be the correct way to handle this. Few things come to my mid,
- Disable dismiss on back button and touch outside

```java
dialog.setCancelable(false);
dialog.setCanceledOnTouchOutside(false);
```

- Dispatch a global event when a dialog is dismissed

```js
Alert.addListener('dismiss', () => { /* do the thing */ });
```

- Add a callback to the dialog, which gets called when it is dismissed

```js
Alert.alert('Title', 'Message',  [ { text: 'Okay' } ], () => { /* do the thing */ });
```

Please give your inputs on what do you think the best way is. For me personally, I prefer the last one.

**Comment by mkonicek** [comment]
The native module does say whether the dialog was dismissed:
https://github.com/facebook/react-native/blob/master/Libraries/Utilities/Alert.js#L115

But it might be the same constant for the Cancel button and tapping outside the dialog. Shouldn't that always do exactly the same thing? If there should be a button that does something else than *dismiss the dialog* (this is what tapping outside does), maybe it should be a different, third button?

I didn't see API for that on iOS so wanted to keep the API consistent.

**Comment by mkonicek** [comment]
Some users might not know that tapping outside the dialog dismisses it. Having the 'Cancel' button, Back button and tapping outside do exactly the same thing (usually, do nothing), sounds consistent from the UX perspective. What do you think?

**Comment by satya164** [comment]
@mkonicek Totally agree. The ideal behaviour would be to trigger same handler as cancel button.

We allow having a dialog without cancel button though. But I guess it's okay, because if the dev wanted to handle cancel event, he would have added a cancel button. I can send a PR to do this, if it's what we settle on.

I don't know what's the behaviour on iOS. Curious to know. cc @ide

**Comment by ide** [comment]
On iOS you can't dismiss alerts by tapping outside of them (at least on an alert that I just tested). Would it be possible to design a clean API that acts almost the same whether the user tapped Cancel or tapped outside of the dialog, but also passes in a bit of extra information specifying how the dialog was canceled?

**Comment by satya164** [comment]
@ide May be pass an event object or something like that?

```js
function onPress(e) {
    // e.cancelledOnTouchOutside
    // e.cancelledByBackButton
};
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/add-a-dismiss-event-for-alert-dialog

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by antonzy** [comment]
Any progress on this one? 
Really annoying on Android....

**Comment by satya164** [comment]
@antonzy #8652 might help

**Comment by myJarvis** [comment]
how to dismiss an alert programmatically, any suggestions?

**Comment by sandropoluan** [comment]
Any update?

**Comment by eassymo** [comment]
any update? x2

**Comment by dann1609** [comment]
any update? x3

**Comment by kunalqss** [comment]
If you could give us a way to dismiss a dialog programmatically, that'd be great, thanks. :grin:

**Comment by bintoll** [comment]
I also think that it would be really great

**Comment by rumbogs** [comment]
+1

**Comment by myJarvis** [comment]
This issue is from 4-5 months open only.

Bottomline is - Framework is just a Framework , Not a replacement for any
Core Language.

**Comment by mmazzarolo** [comment]
> Framework is just a Framework , Not a replacement for any
Core Language

🤔

**Comment by huunovahub** [comment]
any update x4?
