### ISSUE TITLE
SVG Support?

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#4929]
Do you have plans to include support for SVG?

**Comment by gre** [comment]
it's not built-in but you can use https://github.com/brentvatne/react-native-svg

**Comment by antoxi4** [comment]
Yes but it only for IOS not for Android.There it currently no way to decide it problem.

**Comment by adriansprod** [comment]
Try https://github.com/oblador/react-native-vector-icons

**Comment by bestander** [comment]
@facebook-github-bot feature

**Comment by janicduplessis** [comment]
@facebook-github-bot close

**Comment by seekshiva** [comment]
I just published a new package that lets you load remote svg images!

`react-native-remote-svg`

https://yarnpkg.com/en/package/react-native-remote-svg
