### ISSUE TITLE
Option to disable overscroll effect in ScrollView

### ISSUE THREAD

**Issue by davidengler** [facebook/react-native#4932]
There is no option to disable overscroll effect in ScrollView

**Comment by satya164** [comment]
What do you mean by fading edge? Do you mean the color tint that appears when you overscroll?

**Comment by davidengler** [comment]
When you over scroll there is like a transparent rounded color that is more
dark as you over scroll

**Comment by davidengler** [comment]
Its an over scroll effect, not fading edge, sorry

**Comment by brentvatne** [comment]
@davidengler - pull request welcome! If you don't think you're up to the task then please create an issue on ProductPains for this: https://productpains.com/product/react-native/
