### ISSUE TITLE
Dimensions.get('window').height is sometimes wrong on Android

### ISSUE THREAD

**Issue by jaysoo** [facebook/react-native#4934]
This only happens on a real device (I'm using OnePlus One). Could not reproduce on an emulator.

1. Create an example app that displays the window height.
2. Open the app for the first time.
3. The height is reported as some value (e.g. 592 for me) -- See screenshot below
4. Press home button.
5. Go back to the example app.
6. See that the window height is now different (e.g. 640 for me) -- See screenshot below

It seems that the first load, the height excludes the soft menu bar, but on subsequent reloads it includes it. (the soft menu bar for me is 48).

Here's the code I was running in my app:

```js
'use strict';

const React = require('react-native');
const {
  AppRegistry,
  Dimensions,
  Text,
  View
  } = React;

const window = Dimensions.get('window');

const Example = React.createClass({
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text style={{ fontSize: 48}}>Height is {window.height}</Text>
      </View>
    );
  }
});

AppRegistry.registerComponent('Example', () => Example);
```

### First load

![screenshot dec 22 2015 4-58-01 pm](https://cloud.githubusercontent.com/assets/53559/11967005/860c2c8e-a8cd-11e5-8eaf-fd328e3d6ee9.png)

### Reload

![screenshot dec 22 2015 4-57-28 pm](https://cloud.githubusercontent.com/assets/53559/11967010/8ca960ac-a8cd-11e5-8473-4e948121c331.png)

**Comment by DanielHoffmann** [comment]
Yeah, Dimensions is badly broken in android, if you rotate the screen the dimensions will still be in their old values. If you close the application and open it again but with the orientation changed, the values will be correct. The Dimension values keep their original values as opposed to change when the device orientation changes.

Also a way to assign a callback when the Dimensions change would be nice, if I could register a callback in `componentDidMount` and unregister it on `componentWillUnmount` I would be so happy.

**Comment by jaysoo** [comment]
@DanielHoffmann I created a module just so I can get going on my own project.

https://github.com/jaysoo/react-native-extra-dimensions-android

A callback would be easy to implement. Although I'd prefer it being in RN core if it makes sense.

**Comment by mjisican** [comment]
is this fixed already on .26?

**Comment by infinityl00p** [comment]
bump... this is a pretty major issue, how has this not been fixed?

**Comment by metahexane** [comment]
Can we get an update on this issue, I'm still experiencing this with RN 0.55.2 along with CRNA.

**Comment by Billy-** [comment]
Closed with no explanation...? Can anyone comment on this issue please? @cpojer ?
