### ISSUE TITLE
ViewPagerAndroid: adapter didn't implemented getItemPosition

### ISSUE THREAD

**Issue by tdzl2003** [facebook/react-native#4937]
This method is used by view pager to decide which page view is at after datachanged.

So now when we change the children of viewpager, the result is weird.

**Comment by tdzl2003** [comment]
I'll give a PR later.

**Comment by mkonicek** [comment]
:+1:

**Comment by brentvatne** [comment]
Thanks @tdzl2003! Closing this, looking forward to PR. Let's try to limit issues to bugs
