### ISSUE TITLE
concatenation of views before returning

### ISSUE THREAD

**Issue by iSimar** [facebook/react-native#495]
Hello there,

When we are returning from a render function is there a way to concatenate multiple view elements before returning.

Ex: let's say you want to generate Text elements using a for loop? Then returning it from a render function.

**Comment by kennydee** [comment]
haha :) this is related to my demand on your github project : https://github.com/iSimar/HackerNews-React-Native/issues/2 ?

I'm also interested in knowing how to achieve something like that :)

**Comment by vkurchatkin** [comment]
This works just fine:

```javascript
var text = ['aaaa', 'bbbb', 'cccc'];
    return (
      <View style={styles.container}>
        {text.map(t => <Text>{t}</Text>)}
      </View>
    );
```

**Comment by iSimar** [comment]
Perfect, Thank you.
