### ISSUE TITLE
[Android] Alert not working

### ISSUE THREAD

**Issue by Sunify** [facebook/react-native#4964]
I try to show alert, but get this error:
TypeError: undefined is not an object (evaluating 'DialogModuleAndroid.showAlert')

**Comment by christopherdro** [comment]
@Sunify Could you provide a snippet of how your calling alert?

**Comment by Sunify** [comment]
Yes, sure:
```
Alert.alert('Error', 'Error message');
```
On iOS it works fine.

**Comment by satya164** [comment]
@sunify Are you you have the latest version of the Java library? Try running `react-native upgrade` inside your project.

**Comment by Sunify** [comment]
@satya164 upgrade solve issue, thanks!

**Comment by 9mm** [comment]
When I call `react-native upgrade` I get

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Package name com.music-native is invalid
    at [object Object].module.exports.yeoman.generators.NamedBase.extend.initializing (index.js:41:13)
    at /Users/Yo/Code/music-native/node_modules/react-native/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by satya164** [comment]
@9mm Package names cannot have a `.` in it.

**Comment by Overload119** [comment]
I'm getting this error as well, and react-native upgrade didn't help.
I'm running React Native `com.facebook.react:react-native:0.17.+`
