### ISSUE TITLE
API consistency in React Native

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#4971]
Currently React Native has lots of incosnistencies in its APIs. This is an attempt to settle on a standard way for API methods and change the current APIs to the standard format by discussing a migration path.

## Currently available modules and their callbacks

The available APIs can be categorized into the following categories,

### 1. Node-style error-first callbacks

```js
// https://facebook.github.io/react-native/docs/asyncstorage.html#content
AsyncStorage.getItem(key: string, callback?: ?(error: ?Error, result: ?string) => void) // all AsyncStorage methods
```

### 2. Value first callbacks

```js
// https://facebook.github.io/react-native/docs/netinfo.html#content
NetInfo.isConnectionExpensive(callback: (metered: ?boolean, error?: string) => void)
```

### 3. Separate callbacks for success and error, success-first

```js
// https://facebook.github.io/react-native/docs/cameraroll.html#content
CameralRoll.saveImageWithTag(tag, successCallback, errorCallback);
CameralRoll.getPhotos(params, callback, errorCallback);

// https://facebook.github.io/react-native/docs/nativemethodsmixin.html#content
NativeMethodsMixin.measureLayout(relativeToNativeNode: number, onSuccess: MeasureLayoutOnSuccessCallback, onFail: () => void)
```

### 4. Separate callbacks for success and error, error-first

```js
// https://facebook.github.io/react-native/docs/actionsheetios.html#content
ActionSheetIOS.showShareActionSheetWithOptions(options: Object, failureCallback: Function, successCallback: Function)
```

### 5. Callbacks with no error

```js
// https://facebook.github.io/react-native/docs/actionsheetios.html#content
ActionSheetIOS.showActionSheetWithOptions(options: Object, callback: Function)

// https://facebook.github.io/react-native/docs/alertios.html#prompt
Alert.prompt(title: string, value?: string, buttons?: Array<{ text?: string; onPress?: ?Function; style?: AlertButtonStyle; }>, callback?: Function)

// Clipboard: not documented yet
Clipboard.getString(callback: Function)

// https://facebook.github.io/react-native/docs/intentandroid.html#content
IntentAndroid.canOpenURL(url: string, callback: Function)
IntentAndroid.getInitialURL(callback: Function)

// https://facebook.github.io/react-native/docs/linkingios.html#content
LinkingIOS.canOpenURL(url: string, callback: Function)

// https://facebook.github.io/react-native/docs/nativemethodsmixin.html#content
NativeMethodsMixin.measure(callback: MeasureOnSuccessCallback)

// https://facebook.github.io/react-native/docs/pushnotificationios.html#content
PushNotificationIOS.getApplicationIconBadgeNumber(callback: Function)
PushNotificationIOS.checkPermissions(callback: Function)
```

### 6. Promise based APIs

```js
// https://facebook.github.io/react-native/docs/asyncstorage.html#content
AsyncStorage // all AsyncStorage methods

// https://facebook.github.io/react-native/docs/netinfo.html#content
NetInfo.fetch().done(callback: Function)
```

## Candidates for the standardized callbacks

The callbacks should encourage error handling IMO. Keeping that in mind, I think the following should be good candidates.

1. Node-style error-first callbacks (enforces error handling)
2. Separate callbacks for success and error, success-first (only by enforcing it in the module manually)
3. Separate callbacks for success and error, error-first (enforces error handling)
4. Promise based APIs (when error logging is implemented and errors show redbox - https://github.com/then/promise/pull/116)

## Problems to discuss

1. Discuss on the advantages and disadvantages for all of the above types of callbacks and settle on one
2. Think of a good migration path, for example when someone is using the incorrect API, show a redbox saying that API is different

If I missed any, please edit the post and add them. Thanks :D

cc @vjeux @mkonicek @nicklockwood @ide @brentvatne @skevy

**Comment by feichngr** [comment]
I think consistent use of ES6 promises, optionally with the additional non-standard done() method (`NetInfo.fetch()` returns a `Promise`, so `NetInfo.fetch().done(callback: Function)` probably shouldn't be part of category 5), is the way to go.It gives us async-await syntax in ES2016 and probably the best compatibility with libraries which consume async data.

**Comment by ippa** [comment]
What feichngr said - I would go with promises. Love working with fetch() in RN right now. Functions returning promises makes for some nice composability.

**Comment by satya164** [comment]
Yeah, personally I think that promises are the way to go. Currently the problem with promises in React native is that errors are not shown unless you call `.done()`, which is easy to forget, and also non-standard. But it seems that this is going to be fixed soon - https://github.com/then/promise/pull/116 and then it'll be a good candidate for the APIs.

**Comment by corbt** [comment]
Another vote for promises, especially since babel lets us use `async`/`await` in RN. I also agree though that unhandled errors in promises should be presented as a redbox, otherwise it's too easy to not realize that something has failed.

**Comment by brentvatne** [comment]
Nice writeup @satya164 :) Another vote for promises

**Comment by satya164** [comment]
@davidaurelio is the promise polyfill with error tracking being used in RN yet?

**Comment by davidaurelio** [comment]
No, will update it… thanks for the reminder?

**Comment by skevy** [comment]
@davidaurelio the Promise polyfill is going to live in fbjs after this PR is merged, fyi: https://github.com/facebook/react-native/pull/5084

**Comment by davidaurelio** [comment]
@skevy thanks for the heads up.

**Comment by satya164** [comment]
Now that RN has rejection tracking for promises, we could get started on this. @skevy

**Comment by corbt** [comment]
This may be opening a whole different can of worms, but I think it would be worth considering including/standardizing on an RxJS `Observable` pattern for stuff that emits event streams like `NetInfo.addEventListener`. It could be used like:

```js
// Basic example to print all connectivity events
NetInfo.connectivityEvents.subscribe(connection => console.log(`current connection: ${connection}`));

// Start sync when connected on wifi
NetInfo.connectivityEvents.filter(connection => connection === 'wifi').subscribe(startSync);
```

**Comment by ide** [comment]
> This may be opening a whole different can of worms

I think so. Also word through the grapevine is some bigger cos are moving away from Observable.

**Comment by grabbou** [comment]
Is this still something we should keep opened? Looks like we have decided to go with Promise-based API, that's what other libraries started to adapting and the general `API consistency` issue mentioned seems to be solved (if there are any components / APIs in a need of update, I believe we can handle them in smaller issues).

**Comment by satya164** [comment]
@grabbou Yeah, we can file smaller issues and close this.

**Comment by mkonicek** [comment]
> Yeah, we can file smaller issues and close this.

OK I'll close this one. Just saw the description again, it's an awesome writeup! Have a lot of APIs been migrated to Promises?

**Comment by satya164** [comment]
@mkonicek Thank you :)

Yeah, most have been migrated to promises. I think only `PushNotificationIOS` and `NativeMethodsMixin` are remaining from this post.

**Comment by grabbou** [comment]
And.... ActionSheetIOS but there's open PR for that :)
