### ISSUE TITLE
Why not make the RCTBridge as a single SDK? Then other projects can use this JS SDK to call Objective-C functions from JS.

### ISSUE THREAD

**Issue by longv2go** [facebook/react-native#4972]

**Comment by sospartan** [comment]
+1
建议你直接搞一个,最小化的RN,跟他们讨论,就算有戏也得猴年马月了,而且这事跟他们的目标不一定契合

**Comment by longv2go** [comment]
@sospartan 正在看RCTBridge 代码，研究透了之后搞一搞，哈哈！

**Comment by satya164** [comment]
@longv2go Didn't get you. Can you provide an example?

**Comment by brentvatne** [comment]
Let's move this to ProductPains -- if there is enough demand for it, it will be considered! https://productpains.com/product/react-native/
