### ISSUE TITLE
Can't pass in initial arguments to instantiate native view in RCTViewManager

### ISSUE THREAD

**Issue by ppong** [facebook/react-native#498]
I am trying to write a native module to wrap Google Maps. However, it is unclear from the documentations how to pass in initial arguments such as `latitude`, `longitude` and `zoom` to instantiate the view. Thanks! Any guidance would be appreciated.

```
#import <GoogleMaps/GoogleMaps.h>

@implementation GoogleMapManager
- (UIView *)view
{
    GMSCameraPosition *camera = [GMSCameraPosition cameraWithLatitude:-33.86 longitude:151.20 zoom:15];
    GMSMapView *mapView = [GMSMapView mapWithFrame:CGRectZero camera:camera];
    return mapView;
}
```

**Comment by brentvatne** [comment]
Check out the related bits from my implementation of a `Video` element here:

[RCTVideoManager.m](https://github.com/brentvatne/react-native-login/blob/master/RCTVideoManager.m#L15-L16) - this passes the props on to `setX` methods in `RCTVideo`

[RCTVideo.m](https://github.com/brentvatne/react-native-login/blob/master/RCTVideo.m#L20-L34) - this defines how the setters work

[Video.ios.js](https://github.com/brentvatne/react-native-login/blob/master/Video.ios.js#L52) - this is where we pass it in to the element itself via js.

**Comment by dvcrn** [comment]
Can you go a bit into detail how exactly you got it working? I am also trying to implement google maps into my native react app but have problems with passing parameters to it

**Comment by brentvatne** [comment]
@dvcrn - can you post your code and point to the specific place where you are having a problem passing params?

**Comment by dvcrn** [comment]
I am looking for an example in how to implement the same code @ppong mentioned above. 

```
#import <GoogleMaps/GoogleMaps.h>

@implementation GoogleMapManager
- (UIView *)view
{
    GMSCameraPosition *camera = [GMSCameraPosition cameraWithLatitude:-33.86 longitude:151.20 zoom:15];
    GMSMapView *mapView = [GMSMapView mapWithFrame:CGRectZero camera:camera];
    return mapView;
}
```

I'm trying to pass a latitude, longitude and zoom value from javascript into the mapmanager so the mapmanager can instantiate the camera and mapview correctly. I read through a few finished native react modules but couldn't quite find the important bits

**Comment by brentvatne** [comment]
Similar problem was solved [here on react-native-mapbox-gl](https://github.com/bsudekum/react-native-mapbox-gl/pull/25/files) 

There is no way to pass in some values into a constructor, but if you move the view you are creating into something like `RCTMapboxGL` in the above link, then you can defer creating the underlying native component that you are wrapping until all of the necessary initialization props are available.
