### ISSUE TITLE
Screen rotation animation is not smooth

### ISSUE THREAD

**Issue by cpunion** [facebook/react-native#4980]
I found a problem when screen is rotating, just create a `Test` project and change the `backgroundColor` to a dark color, then run it and rotate screen, it has a very ugly **BIG WHITE AREA**!

My react-native version is 0.17.0

See below, Same on iPhone device.

Q: Seems it is a bug? and **HOW TO RESOLVE IT?**

![untitled3](https://cloud.githubusercontent.com/assets/8459/12005908/864d9a48-abf7-11e5-9872-0d2e628ef5cb.gif)

I checked GIF frames, and I found that three consecutive frames:

![untitled4](https://cloud.githubusercontent.com/assets/8459/12005909/8cc707ce-abf7-11e5-938d-1f5f924d1abc.jpg)
![untitled5](https://cloud.githubusercontent.com/assets/8459/12005910/8e4d545e-abf7-11e5-93c9-5800c7efed29.jpg)
![untitled6](https://cloud.githubusercontent.com/assets/8459/12005911/9264c310-abf7-11e5-9daa-f8dd59ed100e.jpg)

**Comment by grabbou** [comment]
Are you sure you don't have `Slow Animations` turned on in the Simulator?

**Comment by cpunion** [comment]
@grabbou Yes I have `Slow Animations` turned on for see clearly. I turned off it and recorded a new screenshots. See below.

![untitled5](https://cloud.githubusercontent.com/assets/8459/12009769/3ecdccf8-acc2-11e5-8206-8112e0f41a7b.gif)

When rotation start, the RCTRootView resize to finally size, no transition animation. I guess that is the problem.

**Comment by satya164** [comment]
Have you tried changing the root view background color? http://moduscreate.com/changing-the-react-native-rootview-background-color-ios-and-android/

**Comment by cpunion** [comment]
@satya164 Thank you for that workaround. I would use it.

**Comment by jdmunro** [comment]
The workaround works for simple solid colours, however it is not ideal for more complicated cases where the background colour may be dynamic.

**Comment by cpunion** [comment]
@jdmunro Yes, could you please vote at https://productpains.com/post/react-native/screen-rotation-animation-is-not-smooth/ ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/screen-rotation-animation-is-not-smooth

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by ArtemKosiakevych** [comment]
I find solution http://moduscreate.com/changing-the-react-native-rootview-background-color-ios-and-android/
