### ISSUE TITLE
Resizing native component in native code does not work.

### ISSUE THREAD

**Issue by jayshah123** [facebook/react-native#4990]
I have a custom native component which needs to change its size when some click is provided to it.
I use following api but with no effect -
```
onClick(){
    getLayoutParams().height = 200
    getLayoutParams().width = 200
   requestLayout();
}
```
but with no effect, it is not able to change its size.
How to circumvent such behaviour?

**Comment by jayshah123** [comment]
I am using react-native v0.13rc with android.

**Comment by jayshah123** [comment]
Particularly subviews are also not able to change their size, even if the exposed native component is of fixed size or with flex:1 and styled from JS,
```
onClick(){
    subview.getLayoutParams().height = 200
    subview.getLayoutParams().width = 200
    subview.requestLayout();
    requestLayout();
}
```

**Comment by jayshah123** [comment]
If somebody happens to know the reason or has faced similar problem I would be glad to know the same.
 For know it is not a very primary concern for me so closing the issue.

**Comment by realaboo** [comment]
You can manually trigger layout.

See [ReactPicker.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/picker/ReactPicker.java) or [ReactToolbar.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/toolbar/ReactToolbar.java) for example.

```
 @Override
  public void requestLayout() {
    super.requestLayout();

    // The spinner relies on a measure + layout pass happening after it calls requestLayout().
    // Without this, the widget never actually changes the selection and doesn't call the
    // appropriate listeners. Since we override onLayout in our ViewGroups, a layout pass never
    // happens after a call to requestLayout, so we simulate one here.
    post(measureAndLayout);
  }
```

**Comment by gsavvid** [comment]
@realaboo Thanks so much for this. I spent days banging my head against the wall but this solved it!

**Comment by RobertoArtiles** [comment]
@realaboo Thanks! It's insane that it's not a part of the documentation.

**Comment by svyatogor** [comment]
@realaboo thank you so much!
