### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string ( for built-in components) or a class/function (for composite components)  but got: object. Check the render method of `Index`.

### ISSUE THREAD

**Issue by shexiaoheng** [facebook/react-native#4993]
When I put my project to upgrade from 0.14.0 to 0.17.0 , appear this error .

**Comment by yannxiao** [comment]
模块的导出与导入有点变化，如过导出时使用的原生的方式，则导入时也应该使用原生的，而不是require， require与import导入默认模块时会有点区别，require会把`export default`导出的对象放到`default`上，0.17.0我们不能直接拿到`default`上的对象了。

**Comment by shexiaoheng** [comment]
@yannxiao It's OK,谢谢。
