### ISSUE TITLE
[General][Minor][Label] Making React Native More contributor friendly

### ISSUE THREAD

**Issue by qbig** [facebook/react-native#4996]
With 861 + issues and 180+ PRs, I think this efforts would pay off in the long run for RN. @vjeux @brentvatne @ide @mkonicek @satya164 @astreet 

First Timers Only
A suggestion to Open Source project maintainers…

https://medium.com/@kentcdodds/first-timers-only-78281ea47455#.b06e3lz7k

and this http://up-for-grabs.net/#/tags/JavaScript, understanding that we already had a similar tags but this seems to be a even better approach.

**Comment by satya164** [comment]
Will get to this asap. Thanks a lot @qbig .

**Comment by DanielHoffmann** [comment]
A guide on how to clone and run the project would be very welcome.

**Comment by satya164** [comment]
@DanielHoffmann https://github.com/facebook/react-native/tree/master/ReactAndroid

**Comment by satya164** [comment]
@qbig Great suggestion. May be we  could just rename our label `Good First Task` to `up-for-grabs`?

It's important to make it easier to contribute. If you've any other ideas please suggest. I would love to collborate with you to get those implemented.

cc @mkonicek @vjeux @skevy @ide @brentvatne

**Comment by qbig** [comment]
@satya164 would love to help making this happen.  Think we can even use the same good first task label.  Just to need to set it up with the up-for-grabz site.  I will take a look

**Comment by satya164** [comment]
@qbig Awesome. Let me know how it goes.

**Comment by qbig** [comment]
@satya164 maybe could just tweet this out once it's merged https://github.com/up-for-grabs/up-for-grabs.net/pull/300/files or just add https://github.com/facebook/react-native/labels/Good%20First%20Task somewhere in the Doc

**Comment by satya164** [comment]
@qbig Thanks a lot. Yeah we should both tweet it out and add somewhere in the docs.

cc @brentvatne

**Comment by brentvatne** [comment]
@DanielHoffmann - Do you want to try to learn how to do that and then write up a guide? Would be best from the perspective of someone who is new as well.

@satya164 - Happy to tweet that out! @qbig - once it's merged can you submit a pull request to add that to our docs :)

Going to close this issue now we can continue discussion on above mentioned pull requests, thanks a lot people! :rocket:

**Comment by satya164** [comment]
It is merged now. Yay!

**Comment by qbig** [comment]
@satya164  :+1:
