### ISSUE TITLE
[Packager] Global CLI module check conflicts with npm run scripts.

### ISSUE THREAD

**Issue by paramaggarwal** [facebook/react-native#5004]
This commit 2856be9a07582310c9e56667e8db21fb7b29ab48 has a specific problem wherein if you try to make an `npm run` command with `react-native bundle` for example, it will use this instead of the global `react-native-cli` based `react-native` command. This is because `npm run` scripts by default get `node_modules/.bin` in their `PATH`.

I install `react-native-cli` locally and then point `npm run` scripts to use it's `react-native`. But now this `react-native` command overwrites the one provided by `react-native-cli`.

Also, I would like to use `npm run` scripts because the `react-native bundle` commands becomes long once you start adding parameters to it. Hence the need for a custom `npm run` script in the project.

cc: @martinbigio

**Comment by martinbigio** [comment]
@paramaggarwal could you refer the global cli from the npm scripts instead? We added this check because lot of people were getting confused by this. cc @mkonicek

**Comment by paramaggarwal** [comment]
@martinbigio Sure, not a problem.
