### ISSUE TITLE
Warning about "watchman" even when using NodeWatcher

### ISSUE THREAD

**Issue by wvengen** [facebook/react-native#5005]
Readers of packager's `FileWatcher/index.js` warning message _Watcher took too long to load / Try running watchman version from your terminal / https://facebook.github.io/watchman/docs/troubleshooting.html_ may conclude that they have a problem with watchman, also when [NodeWatcher](https://github.com/amasad/sane#sanenodewatcherdir-options) is being used.

Since `watchman` is often not installed (on Linux), this may be a source of confusion. I'd suggest to include the watcher name in the message, and perhaps something like _when you're using watchman, try ..._.

**Comment by philikon** [comment]
+1 agreed.

Want to throw up a pull request?

**Comment by wvengen** [comment]
Thanks! -> #5022
