### ISSUE TITLE
Android ,text props:fontSize :18,I don't konw the unit,The unit of the font?

### ISSUE THREAD

**Issue by amibition521** [facebook/react-native#5018]
React Native Android ,text props:fontSize :18,I don't konw the unit,The unit of the font?

**Comment by christopherdro** [comment]
@amibition521 I'm not sure I understand your question clearly. Could you try rephrasing it?

**Comment by Ehesp** [comment]
Are you asking what the unit of `fontSize: 18` is? I believe it's scaleable pixels... so `18sp`.

**Comment by amibition521** [comment]
I just want to know the font unit in React Native .I know the unit is sp in android.

**Comment by satya164** [comment]
It's `sp`. But you only specify the amount in JavaScript, not the unit.
