### ISSUE TITLE
Loading packager from real device failed due to App Transport Security

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#5019]
Hello,

I'm trying to debug my app on a real device (iOS),
so I need to edit ```AppDelegate.m``` and change ```localhost``` to  my local IP address
```
http://localhost:8081/index.ios.bundle?platform=ios&dev=true
```

The problem is when I change it to my IP the device can't connect because of ```AppTransportSecurity```
And the packager request is using ```http```.
I already fixed it for ```localhost``` by adding exception to ```Info.plist``` but it doesn't make sense to keep adding local IP addresses that will keep change every time I like to debug on a real device.

The only permeant fix is to globally allow insecure requests with ```NSAllowsArbitraryLoads``` set to true.
But that not a real option for the long term...

As I see the options are:

1. Maybe there's a way to add ```NSAllowsArbitraryLoads``` automatically only during development? (but might cause confusion when and weird bugs when trying to build for production)
2. Run the packager using ```https``` with self signed certificate? (Need to make sure that it will not require any exception to be added under App Transport Security)

I'm using:
Xcode - 7.2
React Native - 0.15
Node - v4.2.2

Your help is appreciated,
Thanks, Ran.

**Comment by skevy** [comment]
Based on a small amount of research that I just did, self-signed certs won't allow for NSAllowsArbitraryLoads to be turned off.

My recommendation for people is to create a new target for your App Store build, and make sure App Transport Security is enabled there.

**Comment by ranyefet** [comment]
@skevy What does it mean to create a new target?

**Comment by jsierles** [comment]
You can duplicate your existing project target and updates the value there.

![screen capture on 2016-03-20 at 21-46-41](https://cloud.githubusercontent.com/assets/82/13907036/57b27fba-eee5-11e5-98fe-42fb95af064c.gif)

Closing this out for now, thanks for bringing the issue up!
