### ISSUE TITLE
Has <ListView> infinite scroll and pull to refresh?

### ISSUE THREAD

**Issue by danicomas** [facebook/react-native#502]
If the answer is YES. Anyone can give me an example?

**Comment by colinramsay** [comment]
I believe the answer is NO :disappointed: 

Possible duplicate of: #121 ?

**Comment by danicomas** [comment]
OMG It is a basic component :S

**Comment by colinramsay** [comment]
Which is open source and available for improvement!

**Comment by ide** [comment]
It does have infinite scrolling (look at the data source code) but a refresh control is separate. ++@colinramsay, it's all open source so build what you need.

**Comment by nicklockwood** [comment]
IIRC, refreshControl is somewhat tricky to get working correctly outside of a UITableViewController.

**Comment by vjeux** [comment]
Please see #502 for pull to request

**Comment by danicomas** [comment]
Pull to refresh https://gist.github.com/jsdf/6930c0211e0dc5bf0227

**Comment by danicomas** [comment]
Is it correct to use the event onEndReached for infinite scroll? I don't like because I need to have an array in js memory. :S

**Comment by danicomas** [comment]
If I use this onEndReached in iOS simulator works great but in iPhone 4 the scroll sometimes causes a lazy/strange effect. It is posible a memory problem? 

Look this video with simulator iphone 4S iOS 7.1:
https://www.dropbox.com/s/101lfqwc0da9bir/VID_20150401_142655.mp4?dl=0

And this with physical iphone 4 iOS 7.1:
https://www.dropbox.com/s/ni8nwy5vxqbe58t/VID_20150401_144523.mp4?dl=0

My code is the following:



Could you reopen the issue?

**Comment by khanghoang** [comment]
@danicomas check it out, it may help you https://github.com/facebook/react-native/issues/499

**Comment by bluemsn** [comment]
+1 , @danicomas  I also found the problem. and did you fix it  ?

**Comment by danicomas** [comment]
I have been disconnected in React the last month I can't help you sorry @bluemsn but I will try soon.

**Comment by khacanh** [comment]
I'm late to this, but it may help others, I created a demo project for pull-to-refresh and endless scrolling here https://github.com/CodeLinkIO/ReactNative-Endless-Scrolling

**Comment by emretekince** [comment]
https://facebook.github.io/react-native/docs/refreshcontrol.html
