### ISSUE TITLE
RCTNetworking.sendRequest stops working after a JS error

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#5020]
I'm using `RCTNetworking.sendRequest` (indirectly via the `fetch` function) to load CoffeeScript source maps after a fatal error is reported.

Any advice?

**Edit:** It depends on the error. Throwing at certain areas apparently disrupts RCTBatchedBridge.

**Comment by basketofsoftkittens** [comment]
:+1:

**Comment by satya164** [comment]
Can you show a code sample of what you're doing?

**Comment by aleclarson** [comment]
@satya164 Unfortunately I fixed the specific error that was breaking the `RCTBatchedBridge`. If I come across anything similar, I'll be sure to let you know.
