### ISSUE TITLE
[Android] IntentAndroid.getInitialURL is undefined

### ISSUE THREAD

**Issue by grimor** [facebook/react-native#5023]
I was trying to call `IntentAndroid.getInitialURL` using example from the React docs
```javascript
componentDidMount() {
  var url = IntentAndroid.getInitialURL(url => {
    if (url) {
      console.log('Initial url is: ' + url);
    }
  });
}
```
I've configured intent-filter in manifest file but I've got an error that's saying `getInitialURL` is `undefined`. Don't know if I've done something wrong or it's just a bug or I need to make something more to get this to work. I also want to note that `canOpenURL` and `openURL` methods works fine.

React Native v0.17

**Comment by Haegin** [comment]
`getInitialURL` isn't implemented in v0.17. It's in master but they haven't released a version including it yet. I've just run into the same problem and am currently trying to get it working using `react-native: "facebook/react-native"` in my `package.json` to use the `master` version directly from the git repo.

**Comment by christopherdro** [comment]
@grimor Here is a reference to the commit: https://github.com/facebook/react-native/commit/eb188c8d98fa08686c6b9335e3dcbefe3f524b7e

Feel free to close this if you get it working after testing on master.

**Comment by grimor** [comment]
@christopherdro Thanks! I thought it could be not released yet. But It should be be available in the docs then ? Or maybe it should have some information about it's upcoming feature

I've managed to solve my problems using WebView but I'll test it anyway later today and close issue if it will work.

**Comment by grimor** [comment]
Ok, I've managed to update react-native from github master branch. And `getInitialState` is working, but not able to listen for app launch from an external url registered to my app. Anyway when I tried to update to newest react-native I ran into that bug #5030, I had to update MainActivity.java and had to recompile `react-native` from source using NDK. Then everything worked fine

**Comment by maksimr** [comment]
@christopherdro have the same issue. I installed react-native from github but it throw error `IntentAndroidModule.getInitialURL is not a function`

NOTE: I have method `IntentAndroid.getInitialURL` on **IntentAndroid** but **IntentAndroidModule**(seems it's native module) does not have getInitialURL(callback);
and IntentAdroid failed when I call function getInitialURL

**Comment by grimor** [comment]
You recompiled react-native using NDK ? I had to do taht in order to get
that method working

**Comment by maksimr** [comment]
@grimor thanks for response. 

> You recompiled react-native using NDK 
I think no, how can I do it?

**Comment by grimor** [comment]
There is explanation how to do that
https://facebook.github.io/react-native/docs/android-building-from-source.html#content

**Comment by satya164** [comment]
Note that you can also try the `0.18.0-rc`.
