### ISSUE TITLE
[Networking] fetch() over http2

### ISSUE THREAD

**Issue by pkieltyka** [facebook/react-native#5024]
It would be nice if fetch() could also support http 2. A few options would be:

1. Javascript-only: the underlying WebView component of the respective SDK can provide an http2 interface, I am sure this will happen one day and fetch() can be wrapped to support it
2. Native function: expose a custom fetch() command as a native function that wraps an HTTP client for the respective iOS / Android platforms
3. any other ideas?

**Comment by feichngr** [comment]
I just did a quick `fetch` test against https://http2.akamai.com/demo and both Android (6.0) and iOS (9.1, simulated) seem to connect via HTTP/2 already.

**Comment by pkieltyka** [comment]
thats amazing!

**Comment by christopherdro** [comment]
@feichngr Thanks for checking!

**Comment by deepmehtait** [comment]
@feichngr  Can you share your quick `fetch` test?
