### ISSUE TITLE
Unable to resolve module (RN v0.17)

### ISSUE THREAD

**Issue by hojberg** [facebook/react-native#5025]
I'm having trouble loading some modules that for sure are in my node_modules folder.

I get the `Unable to load module` error in the Simulator. It also seems to be trying to find the module in `/Users/node_modules` ?

Here's how the error looks:
<img width="487" alt="screen shot 2015-12-29 at 5 18 31 pm" src="https://cloud.githubusercontent.com/assets/2371/12037562/35e2d306-ae50-11e5-9066-0e461b0b2f92.png">

Things i've tried:
 - source my .zshrc file from `react-native-xcode.sh`, though that seemed pointless due to it already doing the correct thing of loading my nvm.sh file.
- Added `PATH="$(npm prefix -g)/bin:$PATH` to `react-native-xcode.sh`
- `npm cache clean`
- Fully re-installed node and npm
- Cleared the haste cache

I'm all out of ideas :/

**Comment by christopherdro** [comment]
Appears to be a duplicate of #4968

**Comment by hojberg** [comment]
@christopherdro you're right! thanks
