### ISSUE TITLE
launchPackager.command error

### ISSUE THREAD

**Issue by furkankinyas** [facebook/react-native#503]
i take terminal error "can not open launchPackager.command"

CoreServicesUIAgent uygulamasının belgeleri Terminal’de açmasına izin verilmediği için “launchPackager.command” açılamıyor.

**Comment by frantic** [comment]
How did you get react-native? When you download it from web in a zip file, OSX marks all executable files as "unsafe". Try  doing `git clone` or find `launchPackager.command` file in the repo (it's in `packager/` folder), right click - Open, and it will ask you if you want to trust it. Please reopen if this doesn't help
