### ISSUE TITLE
[Modal] should be [ModalIOS]

### ISSUE THREAD

**Issue by dangnelson** [facebook/react-native#5032]
If the Modal Component is iOS only, shouldn't it be re-named to ModalIOS?

It's confusing for it not to have that naming scheme, since your docs have effectively trained me to look for it to spot components that don't work across both platforms.

I just spent a few hours working with it only to find out it doesn't work in Android.

**Comment by satya164** [comment]
I think Modal will be worked on for Android in future. The IOS or Android naming is for the components which are OS specific. For example, say ActionSheetIOS, there is no Action Sheet on Android.

**Comment by brentvatne** [comment]
Sorry about the confusion @dangnelson! As @satya164 pointed out, Modal is on the roadmap for Android (see https://facebook.github.io/react-native/docs/known-issues.html#content) so this name will make more sense very soon.
