### ISSUE TITLE
is ~8mb the smallest size RN android apk can get?

### ISSUE THREAD

**Issue by alvinwoon** [facebook/react-native#5037]
I have a simple app. Ran proguard and it went down to 7.5mb. I just want to know whether there's other way to reduce the apk size that I am not aware of.

**Comment by MuruganDurai** [comment]
Hi @alvinwoon, How did you ran the pro-guard, can you please share the steps.

**Comment by satya164** [comment]
@alvinwoon React Native app APKs include JSCore binaries for x86 and ARM. If you don't need x86 you could reduce the size even more.

**Comment by alvinwoon** [comment]
@satya164 Thanks! That reduce it down to 5.2mb but crashes the app upon opening. Need to debug more and report back.

**Comment by MuruganDurai** [comment]
@satya164 After proguard enabled I could not get the build finished, got unable to compute hash error at ":app:packageRelease". Also If I disabled the proguard minify, able to generate the apk but the app crashes always for first navigation with error "Unfortunattely <>...", after that first crash app works perfectly. Do you know how to get the crash reports for this error and fix for the previous error.

**Comment by brentvatne** [comment]
cc @mkonicek

**Comment by MuruganDurai** [comment]
Thanks @brentvatne, after re-generating key everything works fine, but getting crash reports would be very helpful.

**Comment by satya164** [comment]
@MuruganDurai You have 2 options for crash reports,

1. Use `adb logcat`, or the logs panel in Android studio to see logs (filter only errors to see crash reports).
2. Use something like crashlytics in your productions apps to track crashes

**Comment by hosainnet** [comment]
@MuruganDurai How did you solve the 'got unable to compute hash error at ":app:packageRelease"' issue exactly? I tried regenerating the key but no luck

**Comment by MuruganDurai** [comment]
@Hosain As I said before I copied all the contents suggested from stackoverflow for "proguard-rules.pro" and re-generated the key.


-keep class * extends com.facebook.react.bridge.JavaScriptModule { *; }
-keep class * extends com.facebook.react.bridge.NativeModule { *; }
-keepclassmembers class *  { @com.facebook.react.uimanager.UIProp <fields>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.ReactPropGroup <methods>; }

# okhttp

-keepattributes Signature
-keepattributes *Annotation*
-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

-dontwarn rx.Observale.**
-dontwarn rx.**
-dontwarn com.squareup.okhttp.internal.huc.**
-dontwarn com.google.appengine.api.urlfetch.**

# okio

-keep class sun.misc.Unsafe { *; }
-dontwarn java.nio.file.*
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn okio.**

 -dontwarn butterknife.**

 -keep public class com.google.android.gms.**

-dontwarn android.support.v7.**
-keep class android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }

-dontwarn java.lang.invoke**

-dontwarn android.support.**
-dontwarn com.github.**
-dontwarn com.squareup.picasso.**



________________________________

**Comment by MuruganDurai** [comment]
@satya164 Thanks for the suggestions. How to remove "React Native JSCore binaries for x86" to reduce the size further.

**Comment by satya164** [comment]
@MuruganDurai Remove `x86` from `abiFilters`.

**Comment by MuruganDurai** [comment]
Thanks @satya164

**Comment by SuhairZain** [comment]
@MuruganDurai 
Hi, you could also try using the split feature to create separate apks for different CPU architectures. In case of RN, this creates 2 APKs (x86 and ARMv7a). Just change the following line in your android/app/build.gradle:

```diff
- def enableSeparateBuildPerCPUArchitecture = false
+ def enableSeparateBuildPerCPUArchitecture = true
```
Upload both these files to Google Play and the users will automatically get the appropriate APK file. If you want to upload to other markets such as [APKFiles](https://www.apkfiles.com/), which do not support multiple APKs for a single app, change the following line as well to create a big universal APK with binaries for both CPUs.

```diff
- universalApk false  // If true, also generate a universal APK
+ universalApk true  // If true, also generate a universal APK
```

**Comment by MuruganDurai** [comment]
@SuhairZain  Thanks.

**Comment by teodors** [comment]
@SuhairZain This seems like a good addition to the docs or even a tutorial. Wink. Wink.

**Comment by martsie** [comment]
Using @SuhairZain 's suggestion we got our APK size down from 15.2MB for the universal to 8.4MB for the ARMv7a and 10.3MB for x86.

**Comment by wenq1** [comment]
I did some [primary experiments](https://github.com/wenq1/jsbridges) on Alibaba's weex which is based on Chrome's v8, similar to ReactNative in architecture. Switching from v8 to duktape bindings significantly reduces the solib size (from 3MB to 300kB), without functional impacts. I suppose the same approach can be applied to ReactNative although its bindings seems more complex.

**Comment by alvinwoon** [comment]
@wenq1 That is amazing.
