### ISSUE TITLE
NavigatorIOS doesn't work with TabBarIOS

### ISSUE THREAD

**Issue by evanwalsh** [facebook/react-native#504]
Inside of my `index.ios.js`, I've got this:

```jsx
render() {
    return (
      <TabBarIOS
        selectedTab={this.state.selectedTab}>
        <TabBarItemIOS
          name="search"
          icon={require('image!search')}
          selected={this.state.selectedTab === 'search'}
          onPress={() => {
            this.setState({
              selectedTab: 'search'
            });
          }}>
          <View>
            <NavigatorIOS
              ref="nav"
              initialRoute={{
                component: SearchScreen,
                title: config.names.search,
              }}
            />  
          </View>
        </TabBarItemIOS>
      </TabBarIOS>
    );
  }
```

When the tab is selected, it does not display the NavigatorIOS correctly. The navigation bar appears at the top (and the navigator's initial route component does get mounted). However, it is not displayed at all. It's just a blank space inside.

When I try rendering the initial route component outside of the NavigatorIOS, it works just fine. Is this intended behavior?

**Comment by pjjanak** [comment]
Try giving your NavigatorIOS a style of flex=1:

```
...
<NavigatorIOS
    ref="nav"
    style={{
        flex:1,
    }}
   initialRoute={{
       ...
   }}
/>
...
```

**Comment by evanwalsh** [comment]
@pjjanak Unfortunately, that does not fix it. Thank you for the suggestion, though!

**Comment by frantic** [comment]
Try @pjjanak suggestion but remove wrapper `<View>` around `<NavigatorIOS>`

**Comment by evanwalsh** [comment]
That works! Thanks!
