### ISSUE TITLE
[Performance] UI not responsive when there's a network request

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native#5041]
Hello,

In my app I'm using TabBarIOS and every time I switch tabs, I'm making a network request to refresh that tab data.

The problem is that when the network request is processing, the UI is not responsive and the app is barely usable.

Are network request using ```fetch``` api blocks the JavaScript thread? Or am I doing something wrong?
If so, Is there a plan to use a background thread to handle the requests?

Thanks,
Ran.

**Comment by satya164** [comment]
The networking APIs are polyfilled with Native code, and they run in a separate thread from the JavaScript AFAIK.

**Comment by ide** [comment]
I doubt the network request is the problem. Try commenting out your response handler to ensure that you're not doing slow work after the response comes back.

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow

**Comment by uc-hus** [comment]
I have created a native app, My UI showing properly in emulator screen but after creation apk in real device I'm facing pixel issues in UI. Meant in mobile app UI not sowing properly.
