### ISSUE TITLE
[ios] [view] borderColor:'rgb(0,0,0,.0)'  not working

### ISSUE THREAD

**Issue by liuxufeng** [facebook/react-native#5043]
[ios] [view] borderColor:'rgb(0,0,0,.0)'  not working

**Comment by skevy** [comment]
Hi there - could you provide more information about the problem you're seeing?

**Comment by chirag04** [comment]
@liuxufeng Use ``rgba`` instead of ``rgb`` for alpha.

**Comment by skevy** [comment]
@chirag04 ha I didn't even see that.

**Comment by chirag04** [comment]
ha. I also missed it first. Actually found it when i tried in the app.
