### ISSUE TITLE
Is there anyway to embed image in <Text> in react-native

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#5046]
Someone may want to implement a rich text edit or rich text view. In html we can do it with inline image tag, but react-native Text can only nest Text in it.

**Comment by satya164** [comment]
@narychen Right now it's only possible in iOS. PR is welcome for Android.

**Comment by narychen** [comment]
I tried it. It's true that it only work on ios. Furthermore the style seems not applying to the image. The size of the image cannot be changed by width and height.

**Comment by narychen** [comment]
I test some smaller pics and it works on android. The width and height also works on android but not on ios with those smaller pics.

**Comment by brentvatne** [comment]
@narychen :)

Feel free to open another issue with a screenshots / details of that problem!
