### ISSUE TITLE
LinkingIOS.addEventListener for deep linking is not working when the app is closed.

### ISSUE THREAD

**Issue by KiraNavarro** [facebook/react-native#5047]
When deep linking to the app when it is closed I can't get to _handleOpenURL(e) to be able to handle that url.

When the app is in the background deep linking is working fine. 

Does anyone have some idea why is this happening and if it can be fixed?

**Comment by satya164** [comment]
Not familiar with iOS, but when the app is opened by tapping a link, you should be able to get the initial url with `LinkingIOS.popInitialURL`.

**Comment by KiraNavarro** [comment]
HI, I can get the url but when the app is closed I'm not able to handle it, looks like this._handleOpenURL  is not being fired.

**Comment by brentvatne** [comment]
Hi @KiraNavarro! I think you will find this article useful: http://blog.lum.pe/listening-to-application-urls-in-react-native/

If it doesn't solve your problem I'd suggest asking on StackOverflow :)

**Comment by KiraNavarro** [comment]
Hey Thanks @brentvatne ! yeah, I did follow that blog post to build the deep linking, I'll try StackOverflow :)

**Comment by zachrnolan** [comment]
@KiraNavarro Did you ever find a solution for this? Running into the same issue.

**Comment by zachrnolan** [comment]
Figured it out. In case anyone else has the same issue just use the following:

```
Linking.getInitialURL().then((url) => {
        if (url) {
          console.log('Initial url is: ' + url)
          this.handleOpenURL({url})
        }
      }).catch(err => console.error('An error occurred', err))
```

This is the only way to get the URL when the app is starting fresh.

**Comment by AndrewHenderson** [comment]
I can't seem to get any use from Linking.getInitialURL which I have on my app root. It fires with `url` as `null`.

`Linking.addEventListener('url', this._handleOpenURL);` never executes the callback at all. 😕

**Comment by romsearcher** [comment]
Hi, I report having the same issue using React Native 0.46. I have the same deep linking code for handling the initial url as stated in the docs: [url](https://facebook.github.io/react-native/docs/linking.html#handling-deep-links) and the code I have for my AppDelegate.m is the following:

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  

  BOOL handled;
  
  if ([RCTLinkingManager application:application
                             openURL:url
                   sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                          annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
       ]) {
    handled = YES;
  }
  
  handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                openURL:url
                                                      sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                             annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                  ];
  // Add any custom logic here.
  return handled;
}
```

Has anyone figured a solution to the problem? @AndrewHenderson could you find a solution or workaround?

**Comment by fpauer** [comment]
Same issue here. Android is working when the app is closed or in background. But for iOS only works when the app is "opened" in background. If the app was forced to close and you try to open it using a deep link, it does not work. 

```
Linking.getInitialURL().then((url) => {
     console.log(url);  // ALWAYS null
});
```

AppDelegate.m
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
```

**Comment by fpauer** [comment]
@brentvatne @AndrewHenderson  I just found the issue. 

in RCTLinkingManager.m , `getInitialURL` is waiting for some data in launchOptions param:
```
RCT_EXPORT_METHOD(getInitialURL:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  NSURL *initialURL = nil;
  if (self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey]) {
    initialURL = self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey];
  } else {
    NSDictionary *userActivityDictionary =
      self.bridge.launchOptions[UIApplicationLaunchOptionsUserActivityDictionaryKey];
    if ([userActivityDictionary[UIApplicationLaunchOptionsUserActivityTypeKey] isEqual:NSUserActivityTypeBrowsingWeb]) {
      initialURL = ((NSUserActivity *)userActivityDictionary[@"UIApplicationLaunchOptionsUserActivityKey"]).webpageURL;
    }
  }
  resolve(RCTNullIfNil(initialURL.absoluteString));
}
``

So in my AppDelegate.m , method `didFinishLaunchingWithOptions:(NSDictionary *)launchOptions` was initiating the Bridge like this :
```
[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation];
```

However, I should initiate the bridge passing launchOptions as parameter:
```
[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions]
```

I hope it can help you guys.

**Comment by romsearcher** [comment]
Thanks! @fpauer It worked! I still could not launche the app with the notification url just by changing the
`[[RCCManager sharedInstance] initBridgeWithBundleURL:jsCodeLocation launchOptions:launchOptions]` line but I did manage to make it work by editing the `getInitialURL ` method you analyzed.

In my case I managed to make it work by adding a check for `UIApplicationLaunchOptionsRemoteNotificationKey` key. 

```
RCT_EXPORT_METHOD(getInitialURL:(RCTPromiseResolveBlock)resolve
                  reject:(__unused RCTPromiseRejectBlock)reject)
{
  NSURL *initialURL = nil;
    
  if (self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey]) {
    initialURL = self.bridge.launchOptions[UIApplicationLaunchOptionsURLKey];
      
  }else if (self.bridge.launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey]){
      // keep in mind I'm extracting a dict here as my notification payload is a dictionary but it could be modified to extract any specific thing your payload sends
      NSDictionary *dict = self.bridge.launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey];
      NSString *string_url = [dict valueForKey:@"url"];
      initialURL = [NSURL URLWithString:string_url];
  } else {
    NSDictionary *userActivityDictionary =
      self.bridge.launchOptions[UIApplicationLaunchOptionsUserActivityDictionaryKey];
    if ([userActivityDictionary[UIApplicationLaunchOptionsUserActivityTypeKey] isEqual:NSUserActivityTypeBrowsingWeb]) {
      initialURL = ((NSUserActivity *)userActivityDictionary[@"UIApplicationLaunchOptionsUserActivityKey"]).webpageURL;
    }
  }
  resolve(RCTNullIfNil(initialURL.absoluteString));
}
```
For anyone that also needs to modify the method: **keep in mind I'm extracting a dictionary as my notification payload is a dictionary but it could be modified to extract any specific thing your payload sends.**

**Comment by GopiKrishna10** [comment]
@AndrewHenderson @KiraNavarro Guys have you solved the issue.am also facing the same problem.When the app is closed(i.e kill from backround)its working fine as expected.If the app running in the background.Tap on the link from the mail it opens the app but this.handleopenURL callback is not firing.can you help me guys
This is my code for ios.Android is working fine 

if(Platform.OS === 'ios'){
        Linking.addEventListener('url', this.handleOpenURL);
        Linking.getInitialURL().then((url) => {
          if (url) {
             this.handleOpenURL(url)
          }
        })
        .catch((e) => {})
    }else{
      AppState.addEventListener('change', this._handleAppStateChange);
    }
