### ISSUE TITLE
polyfill "crypto"

### ISSUE THREAD

**Issue by gre** [facebook/react-native#5049]
A bunch of libs (like seedrandom and node-uuid) depends on "crypto".
They work on Browserify because browserify uses https://www.npmjs.com/package/crypto for polyfill, could React Native do the same?

**Comment by gre** [comment]
related https://github.com/davidbau/seedrandom/issues/31 (I guess it's either a fix to report here, or to report to the N libs, but I think fixing it once in React Native would be better)

**Comment by brentvatne** [comment]
I think that this has been brought up before but can't find the issue at the moment. I think if possible this would be great as a 3rd party module.. cc @ide

**Comment by ide** [comment]
Architecturally it's not very easy to polyfill `crypto` but if you were to I'd suggest it as an npm package unless you can convince FB to pay the maintenance cost.

**Comment by satya164** [comment]
Also, as far as I remeber, the browserify crypto polyfill added a significant size to the bundle. So I guess it's better to use from NPM rather than including it, so that apps which doesn't need it don't have to pay the size cost.

**Comment by brentvatne** [comment]
OK @gre - I think this will need to be done as a npm module for now then. If you think it's important to get it into core as well, then probably the best approach is to create an issue on ProductPains and others can upvote to show that it's important to them as well :)

**Comment by gre** [comment]
ok, then, do you think we should fix react-native to not crash when `try { require("crypto"); } catch (e) { }` ? (like it wouldn't in Node, nor in Browserify context)

**Comment by brentvatne** [comment]
@gre - that's a good point.. I'm not sure what a good way to handle this is. cc @vjeux @ide

**Comment by ide** [comment]
Worth looking ahead at the ES7 System spec to see how this is handled and then backport the semantics to be compatible with require syntax.

**Comment by satya164** [comment]
Probably it's worth opening a different issue for this?

**Comment by gre** [comment]
opened https://github.com/facebook/react-native/issues/5079

**Comment by satya164** [comment]
Thanks @gre :D

**Comment by sasavranic** [comment]
Any news how to generate uuid with react-native?

**Comment by satya164** [comment]
@sasavranic https://www.npmjs.com/browse/keyword/uuid works for me

**Comment by L3V147H4N** [comment]
@sasavranic https://github.com/eugenehp/react-native-uuid seems to work great

**Comment by saulshanabrook** [comment]
I created https://github.com/saulshanabrook/react-native-webview-crypto to polyfil crypto through async communcation with a webview.
