### ISSUE TITLE
WebView: Add an option to load local resource from the app bundle

### ISSUE THREAD

**Issue by pilwon** [facebook/react-native#505]
`<WebView/>` currently only supports `url` prop to control what content to load in the web view.

We need an option to load local resource (mainly `html` but could be others too) from the application bundle.

We could either introduce a new prop for that or reuse `url` and do some magic conversion. For example, `local://<path>.<ext>` can be automatically converted to `file:///<converted-url>`.

```obj-c
NSURL *convertedURL = [[NSBundle mainBundle] URLForResource:@"<path>" withExtension:@"<ext>"];
```

(Use case: #497)

**Comment by AbeEstrada** [comment]
:+1:

**Comment by adrian-social-prod** [comment]
+1

**Comment by nicklockwood** [comment]
WebView now has an html property:

https://github.com/facebook/react-native/blob/master/Libraries/Components/WebView/WebView.ios.js#L84

**Comment by pilwon** [comment]
@nicklockwood What kind of string values does `html` prop expect?

**Comment by pilwon** [comment]
@nicklockwood ~~What kind of string values does `html` prop expect?~~ Looks like you closed a wrong issue. The above link points at a line modified by the commit https://github.com/facebook/react-native/commit/4b4e8ecc9bf67b47577f9cfdd52bd1d177c0ab44 and it partially fixes #506, not #505.

**Comment by nicklockwood** [comment]
Oh, sorry, quite right. But as it happens, any relative URL is considered to be relative to the app resource bundle, so <WebView url="foo.html" /> should load a file called foo.html that's been added to the project.

**Comment by nicklockwood** [comment]
Let me know if that isn't working, and I'll re-open.

**Comment by pilwon** [comment]
@nicklockwood It works! :scream_cat::scream_cat::scream_cat: This is the best solution for this issue :metal: Thanks-

**Comment by mydearxym** [comment]
@nicklockwood i use the method <WebView url="test.html" />  and it show :
```javascript
Error setting property 'url' of RCTWebView with tag #507: The file 'test.html -- file:///Users/xieyiming/Library/Developer/CoreSimulator/Devices/283F4434-57…rs/Bundle/Application/72594A59-1805-4D5C-B8AB-AB79958D08B6/phone_side.app/' does not exist
```

**Comment by mydearxym** [comment]
@nicklockwood i use the method <WebView url="test.html" />  and it show :
```javascript
Error setting property 'url' of RCTWebView with tag #507: The file 'test.html -- file:///Users/xieyiming/Library/Developer/CoreSimulator/Devices/283F4434-57…rs/Bundle/Application/72594A59-1805-4D5C-B8AB-AB79958D08B6/phone_side.app/' does not exist
```

**Comment by carbonphyber** [comment]
@mydearxym Local files must also be compiled into the bundle.
[See step #2](http://wl3.me/2015/05/01/react-in-your-react-native-webview-so-you-can-react-while-you-react.html)

**Comment by gs-akhan** [comment]
Where do we add this foo.html ? in xCode where exactly ?

Thanks

**Comment by gs-akhan** [comment]
@carbonphyber  I am render the html file using query params 
example "index.html?data=hello"
:(
Thanks

**Comment by nicklockwood** [comment]
@gs-akhan Yeah, that won't work - file paths can't have GET params.

**Comment by DaveAdams88** [comment]
This works great in iOS, but having trouble getting it to work with android - I've put the web view in "android/app/src/main/assets/" - and using "source='webview.html'" - is there a step I am missing? .. or am I flat out doing it wrong? :s

**Comment by nicklockwood** [comment]
@dmmiller, do relative paths work the same way in Android as they do in iOS? Can you use "foo.html" as a shorthand for "android/app/src/main/assets/foo.html" ?

**Comment by dmmiller** [comment]
@nicklockwood Not sure.  I'll check it out on Monday

**Comment by nicklockwood** [comment]
Thanks @dmmiller!

@DaveAdams88 there's another option that I just landed support for in master, which *should* work cross platform. You can now use require() to load HTML files like you do with images:

    <WebView source={require('./foobar.html')}/>

You can see this working in the UIExplorer WebView example. What's great about this is that it serves the file via the packager, so it lives relative to your js, and you can modify it without rebuilding the app.

The downside is that you'll have to embed any CSS, images, etc. inline in the HTML file because the packager won't automatically bundle any files referenced by the HTML unless they are also require()'d in your js code somewhere.

**Comment by DaveAdams88** [comment]
That's awesome! thanks @nicklockwood! :)

**Comment by jaulz** [comment]
@nicklockwood That sounds great! Is it also possible to use it outside of WebView? When I try to require a *.html file I get a simple 1 returned:
```
console.log(require('test.html'));
> 1
````

**Comment by nicklockwood** [comment]
@jaulz `require(...)` doesn't return the source object directly, it returns a resource id. Try this:

    var resolveAssetSource = require('resolveAssetSource');
    var source = resolveAssetSource(require('test.html'));
    console.log(source.uri);

**Comment by jaulz** [comment]
@nicklockwood Thanks for the quick answer :) Though I hoped that it is possible to get the content of the HTML file as a JavaScript string. I assume this is not possible?

**Comment by nicklockwood** [comment]
@jaulz once you have the uri, you can load it via XMLHttpRequest.

**Comment by jaulz** [comment]
@nicklockwood XMLHttpRequest does not really sound what I would like to do. What a pity... I thought there would be a way to link static resources anyhow.

**Comment by nicklockwood** [comment]
@jaulz If you want to get a copy of a file as a string in JS, XMLHttpRequest is currently the only way.

The only real difference between that and having require() return the string directly is that it's async.

**Comment by varunvs** [comment]
Guys, I'm developing an Android app and I tried using `require('test.html')` as suggested by @nicklockwood to load file into the webview. It works great during development but when I take a production build, the webview doesn't load the file. Any clue?

**Comment by comiclee** [comment]
I have the same problem as @varunvs

**Comment by ruqqq** [comment]
@varunvs @comiclee 

To load html from asset for Android, a workaround which worked for me is to prepend `file:///android_asset/` to the uri:

````
<WebView
        source={{ uri: 'file:///android_asset/index.html' }}
        startInLoadingState={true} />
```

**Comment by comiclee** [comment]
Thank @ruqqq ! Your solution works for me.

**Comment by saboteurkid** [comment]
Guys, I'm developing an iOS app that will use a static html, index.html in my case. And inside index.html, I use a js file name test.js.
As @nicklockwood said: 

> unless they are also require()'d in your js code somewhere.

So I've already insert a code like this in my render function:
`initL: function(){
require('./test.js');
},
render: function() {
    this.initL();
    ... so on
}
`
The problem is: the index.html is loaded, but the test.js is not. Is there any way that can let me load my js/css file? (I intend to make an offline webview)
Thanks in advance.

**Comment by nicklockwood** [comment]
@saboteurkid I believe the issue is that .js files are treated differently than other resources. When you require a .js file, it get's merged into your app bundle, it doesn't copy the actual file into your resources folder. I think your only option is to put the JS code inline in your HTML inside a <script> tag. CC: @davidaurelio for other ideas.

You css file also won't work, but for a different reason - we don't currently include .css in the list of recognized resource file types. You can fix that by making a pull request that adds it in all the necessary places (see this other PR for reference: https://github.com/facebook/react-native/pull/7004).

**Comment by saboteurkid** [comment]
@nicklockwood: thank you for your lighting reply. I think that I should make it online and add some inline code to minimize Ajax call. Thank you so much 👍

**Comment by ramilushev** [comment]
@nicklockwood Keep in mind that on android, bundled html files do not load in release version. They work fine on debug.

**Comment by zhv7777** [comment]
uri: 'file:///android_asset/index.html'  didn't work for me on android. Is there any way to include local html file on android?

**Comment by xiemeilong** [comment]
require('./foobar.html') works on iOS, not on Android, 'file:///android_asset/index.html' also not work.  I am using React Native 0.28.

**Comment by varunvs** [comment]
@xiemeilong Ensure that you place the file you want to load in Android assets directory. It works fine for me on RN 0.28

**Comment by joncursi** [comment]
@varunvs where exactly should the file be placed for `'file:///android_asset/index.html'` to work?

```
android/app/src/main/assets/index.html
```

or

```
android/app/build/intermediates/assets/index.html
```

or?

**Comment by varunvs** [comment]
@joncursi You need to place the file in `android/app/src/main/assets` directory.

**Comment by mishuagopian** [comment]
@varunvs @ruqqq I'm placing the `.html` file in `android/app/src/main/assets` directory and works as expected, but `script` tag is never run.
Attaching screenshots:
<img width="370" alt="screen shot 2016-09-02 at 4 08 32 pm" src="https://cloud.githubusercontent.com/assets/9448790/18215494/d5586302-7127-11e6-8d17-fbac1c7ec8f3.png">
<img width="295" alt="screen shot 2016-09-02 at 4 09 28 pm" src="https://cloud.githubusercontent.com/assets/9448790/18215493/d5560f08-7127-11e6-9d50-ba4d7b19b281.png">
Has this happened to you guys?

**Comment by varunvs** [comment]
@mishuagopian I had noticed that alerts don't run in Webview on Android. Not sure that it is React Native specific. If your intention is to test script execution, use something like `document.querySelector('h1').textContent = 'Hello world'` and see if it works.

**Comment by mishuagopian** [comment]
@varunvs It's working! Thank you very much!

**Comment by mishuagopian** [comment]
@varunvs I've discovered if I inject to the `WebView`a script which contains javascript comments it will fail the script execution. I'll create an issue for that.

**Comment by lorrainefox** [comment]
I'm working on a project using ReactNative for the front end and Android studio.   I cannot get the html to show when I create a signed apk.  The html displays when I run in debug mode running reactnative server.  Below is the code snippet in reactnative component, following the gradle build that copies the assets to res:

<View accessibilityLabel={'statementBox'} style={styles.webviewContainer}>
        <WebView
          style={styles.webview}
          source={require('./assets/ElectronicDelivery.html')}
        />
      </View>

"-c", "PATH=\"~/bin:\$PATH\";
[ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\";
source ~/.nvm/nvm.sh; cd ${rootDir}/../../app-reactnative;
react-native bundle --platform android --dev false --entry-file index.android.js
--bundle-output ../android/app-android/app/src/main/assets/index.android.bundle
--assets-dest ../android/alpp-android/app/src/main/res/; exit 0"

**Comment by lorrainefox** [comment]
The html cannot be in res, but when I move the html to assets, the html still won't display when I run the signed apk.

**Comment by liuliangsir2016** [comment]
how to load ios web html file for webview source html attribute

**Comment by liuliangsir** [comment]
thx~

**Comment by Dryymoon** [comment]
Place this script in any file of ReactNative code, recomended to first index file.
And it will fix problem.

```javascript
import { Platform } from 'react-native';
import { setCustomSourceTransformer } from 'react-native/Libraries/Image/resolveAssetSource';

setCustomSourceTransformer(function (resolver) {

  if (Platform.OS === 'android'
    && !resolver.serverUrl
    && !resolver.bundlePath
    && resolver.asset.type === 'html') {
    resolver.bundlePath = '/android_asset/';
  }

  return resolver.defaultAsset();
});
```

**Comment by timscott** [comment]
I'm stuck. 

I started with the HTML file in the same folder as the component. This worked fine in development.

```jsx
<WebView
  ref="chartWebView"
  style={{
    backgroundColor: 'transparent'
  }}
  source={require('./myGraph.html')}
  injectedJavaScript={js}
  javaScriptEnabled={true}
  domStorageEnabled={true}
  decelerationRate="normal"
  startInLoadingState={true}
  scalesPageToFit={true}
/>
```

But when when I build for release.

```
react-native run-android --configuration=release
```

It fails.

```
Execution failed for task ':app:mergeReleaseResources'.
> /code/android/app/src/main/res/drawable-mdpi/native_components_mycomponent_mygraph.html: Error: The file name must end with .xml or .png
```

So I moved the html file and the changed the source property.

```
source={{url: 'file:///android_assets/myGraph.html'}}
```

But now, though WebView renders, the injected script doesn't run. It's the same script that was working before.

**Comment by keshavkaul** [comment]
How can I load local css file into web view's html?

**Comment by dijimon** [comment]
Is it correct to use source={{uri: path_to_file}} for iOS app?
If yes, than what url format should I use.  I mean in android I'm using 'file:///android_asset/path_to_file', but what in iOS?

**Comment by mishuagopian** [comment]
@dijimon in iOS you have to link the file to your project as it is specified in [this guide](https://medium.com/@dabit3/adding-custom-fonts-to-react-native-b266b41bff7f#.nqowukrez), in which the author links fonts.

Once you've done that, you can do something like the following when rendering the `WebView`:
```jsx
 <WebView source={{ uri: Platform.OS === 'ios' ? 'the-linked-file.html' : 'file:///android_asset/path-to/the-linked-file.html'; }} />
```

Remember importing `Platform` and `WebView` as the following:
```jsx
import { Platform, WebView } from 'react-native';
```

**Comment by dijimon** [comment]
But if I don't want to do it manually in Xcode. For instance I want to add some files to the app bundle using some script before making a build, and then I want to require one of those files for showing WebView

**Comment by mishuagopian** [comment]
Maybe you can do the link programatically, but I've never than that 👎

**Comment by dijimon** [comment]
I guess there is no way to include some file to the WebView on the fly on iOS.
Because require('path_to_file') doesn't support dynamic urls
and {uri: 'path_to_file'} requires to add files manually using Xcode

**Comment by gs-akhan** [comment]
@dijimon What is the use case you want to add dynamic files ? May be I can help 
Thanks

**Comment by tommhuth** [comment]
I see `require("somefile.html")` referenced alot, but no matter what I do, I cannot get this to output the actual HTML from the file (only a resource id, with no ref to any content). 

Is is even possible to make it do that, so i can do `source={{ html: require("somefile.html") }}`, or am I missing something here?

**Comment by shaunsaker** [comment]
@Dryymoon Too legit, thank you!

**Comment by dayongxie** [comment]
I found the function getDevServerURL and getBundleSourceURL from resolveAssetSource.js, It's helpfull.
And I create my workaround solution , it worked in both dev and production mode
```javascript
function getBundleSourceURL(): ?string {
    if (_bundleSourceURL === undefined) {
        const scriptURL = NativeModules.SourceCode.scriptURL;
        if (!scriptURL) {
            // scriptURL is falsy, we have nothing to go on here
            _bundleSourceURL = null;
            return _bundleSourceURL;
        }

        let match = scriptURL && scriptURL.match(/^https?:\/\/.*?\//);
        if (match) {
            // Bundle was loaded from network
            _bundleSourceURL = match[0];
            return _bundleSourceURL;
        }

        _bundleSourceURL = scriptURL.substring(0, scriptURL.lastIndexOf('/') + 1);

        if (scriptURL.startsWith('assets://')) {
        // android: running from within assets, no offline path to use
           _bundleSourceURL = _bundleSourceURL.replace('assets://', "file:///android_asset/");
           return _bundleSourceURL;
        }
        if (!scriptURL.startsWith('file://')) {
            // Add file protocol in case we have an absolute file path and not a URL.
            // This shouldn't really be necessary. scriptURL should be a URL.
            _bundleSourceURL = 'file://' + _bundleSourceURL;
        }
    }

    return _bundleSourceURL;
}

export default class WebPage extends Component<{}> {
    static navigationOptions = ({navigation})=> {
        return {
            title: `${navigation.state.params.title}`,
        }
    };

    render() {
        let {source} = this.props.navigation.state.params;

        if (typeof(source) === 'string') {
            if (!source.match(/^.*:\/\/.*?/)) {
                if (getBundleSourceURL()) {
                    source = getBundleSourceURL() + source;
                }
            }
            source = {uri: source};
        }
        return (
            <View style={{flex:1}}>
                <WebView
                    source={source}
                />
            </View>
        );
    }
}
```

**Comment by vvavepacket** [comment]
what is the equivalent **android/app/src/main/assets** for iOS?

**Comment by sujitpk-perennial** [comment]
@vvavepacket  need to create main.jsbundle. Check this https://github.com/facebook/react-native/issues/4084

**Comment by Arshiamidos** [comment]
hey guys  
found the trick base on [Image doesn't show after bundling into the apk](https://github.com/facebook/react-native/issues/4084).   
as you know **require('index.html')** work on _simulator_ and _emulator_ for both &driod and IOS  
but problem will faced when you bundle and you want release your app   
for android just follow this  **enablejavascript**  and copy you files in **assets** folder in `YOUR_APP/app/src/main/assets` and use just picture below.  

and for ios just bundle package with 
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
when bundle created you have **main.bundle.js** and **asset** folder   
just copy you files in  **.xcworkspace** like this image  
![ios](https://user-images.githubusercontent.com/6451804/39201543-963c2e00-4804-11e8-9031-fb87a9f2c46e.jpg)
and set free all **refrence** in will be and unchanged just like mine. 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/39201713-1260aeac-4805-11e8-92dd-efd9209cb44f.png)
i hope this tutorial help you from confusing release app in RN

**Comment by Arshiamidos** [comment]
worked with rn 0.54 🙏
