### ISSUE TITLE
Add ability to configure the app that should open when starting debugging

### ISSUE THREAD

**Issue by axemclion** [facebook/react-native#5051]
When trying to debug a ReactNative today, the ReactNative packager opens `google-chrome`. This is hard coded into [packager](https://github.com/facebook/react-native/blob/3a92f2017fc2e51c2a915f0e535397cb3937d412/local-cli/server/middleware/getDevToolsMiddleware.js). 
Could we make this depend on an environment variable, just like we do [for the editor](https://github.com/facebook/react-native/blob/a710eb329212f47def6689f2ff8dcabe6c9554f6/local-cli/server/util/launchEditor.js) ? This way, other tool chains can also be attached for debugging ReactNative apps.

**Comment by axemclion** [comment]
I am working on [Reactnative support for VSCode](http://taco.tools/vscode/rn.html) and we would like to attach VSCode as a debugging in ReactNative. 

This was also briefly [discussed on twitter](https://twitter.com/tadeuzagallo/status/679262493454241792) with @tadeuzagallo

**Comment by tadeuzagallo** [comment]
Hey, sorry for the delay, I was on holidays for a while, and am catching up now.

The reason I asked you to open an issue was that I wasn't sure how much of the environment could you control (preprocessor macros, environment variables, etc.) but if environment variables work for you, I think it'd be okay.

/cc @davidaurelio @martinbigio

**Comment by martinbigio** [comment]
Sounds good to me! Thanks for working on this :)

**Comment by axemclion** [comment]
We should be able to send in a pull request for this. I guess the only other piece of information that we would need is the root of the project. The debug is triggered from the packager, and a custom IDE connecting to this debugger cannot know just from the packager about the root of the project. We could send in a pull request with the changes for review.

**Comment by jsierles** [comment]
Closing as REACT_DEBUGGER was implemented in the accepted PR #5683. Thanks for bringing this up!
