### ISSUE TITLE
[Android] Can we allow views accept Context? (not ThemedReactContext)

### ISSUE THREAD

**Issue by deminoth** [facebook/react-native#5053]
I've made a RN android app with the [YouTube Android Player API](https://developers.google.com/youtube/android/player/). In the API, `YouTubePlayerView` constructor requires `YouTubeBaseActivity` as a context parameter. My native module is like below:
```java
  @Override
  public YouTubePlayerView createViewInstance(ThemedReactContext context) {
    mContext = context;
    
    mYouTubePlayerView = new YouTubePlayerView(mActivity);
    mYouTubePlayerView.initialize(YOUTUBE_API_KEY, this);
    
    return mYouTubePlayerView;
  }
```
But when the RN drop this view, it notify view manager with `onDropViewInstance`,
```java
resolveViewManager(view.getId()).onDropViewInstance(
  (ThemedReactContext) view.getContext(),
  view);
```
and it shows the redbox `...MainActivity cannot be cast to com.facebook.react.uimanager.ThemedReactContext`.

I'm applying a workaround by checking `view.getContext() instanceof ThemedReactContext`. Is it only my problem? Or can we allow `Context` as a constructor parameter of views? Any other suggestions?

**Comment by brentvatne** [comment]
cc @kmagiera @foghina

**Comment by foghina** [comment]
You shouldn't store a reference to your activity, and instead pass the `ThemedReactContext` to the `YouTubePlayerView` constructor. Is there a specific reason why you're holding a reference to the activity and passing it instead?

**Comment by foghina** [comment]
Nevermind, just saw the constructor for `YouTubePlayerView` needs a special type activity. Hmm.

**Comment by foghina** [comment]
We can probably change the signature of `onDropViewInstance` to take a `Context` instead, and view managers can cast to themed if they really need to. However, most managers don't even implement this method AFAIK, so the signature change should be pretty safe. Would you mind sending a PR for this?

**Comment by deminoth** [comment]
@foghina https://github.com/facebook/react-native/pull/5125
