### ISSUE TITLE
【UIExplorer】Unable to download JS bundle

### ISSUE THREAD

**Issue by ArronXY** [facebook/react-native#5059]
I follow these two command
1) ./gradlew :Examples:UIExplorer:android:app:installDebug
2) ./packager/packager.sh

and got this error:
![image](https://cloud.githubusercontent.com/assets/3257076/12062817/184137a4-afde-11e5-9bef-ad1ba8586dc1.png)

besides，the console log shows that it download js bundle always ended at 【99% 443/449】：
![image](https://cloud.githubusercontent.com/assets/3257076/12062833/620a3340-afde-11e5-8ddb-70756e1e9b97.png)

please let me know if you get the solution, thx！

**Comment by christopherdro** [comment]
Try pulling again from master.
This was fixed yesterday via https://github.com/facebook/react-native/commit/bec91104f8fd4d3eb0c5b562d0179595f625dcb6

**Comment by ArronXY** [comment]
it works ! thx!
