### ISSUE TITLE
WebView: Add an option to load raw HTML & JS.

### ISSUE THREAD

**Issue by pilwon** [facebook/react-native#506]
`<WebView/>` currently only supports `url` prop to control what content to load in the web view.

We need an option to load raw HTML & JS instead of URL to expose `[webView loadHTMLString: baseURL:]` and `[webView stringByEvaluatingJavaScriptFromString:]`.

(Use case: #497)

**Comment by nicklockwood** [comment]
Adding an "html" property should be straightforward (although if you also wanted to specify a baseURL, it would either need to be a separate property, or a method with two arguments).

What's the use case for exposing "stringByEvaluatingJavaScriptFromString" though?

**Comment by pilwon** [comment]
@nicklockwood `stringByEvaluatingJavaScriptFromString` gives us power to do something like [this](https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/React/Views/RCTWebView.m#L156-L178) ourselves.

**Comment by nicklockwood** [comment]
Fair enough.

**Comment by colinramsay** [comment]
I haven't tried it, and it's pretty clunky, but could you now use the new html prop to pass in a script tag to WebView?

**Comment by nicklockwood** [comment]
It would replace the previously loaded web page, so no, not in the way you mean.

This property was added as an unrelated feature to your request though, so don't assume this means ee eon't be adding a means to execute JS code.

**Comment by ckknight** [comment]
A means to execute javascript code with a callback would be wonderful.

**Comment by brentvatne** [comment]
@ckknight - executing JS would be easy to implement but adding a callback would be a bit more complicated. @oveddan is going to have a shot at least at executing JS in #1349, I mentioned also possibly adding a callback there as well!
