### ISSUE TITLE
[Android] ScrollView slow on initial load

### ISSUE THREAD

**Issue by tUrG0n** [facebook/react-native#5069]
I have around 400 records that I want to display in a ScrollView.
Once the app starts, the issue is that it takes around 4 to 5 seconds in order for the data to appear.
After that, i can scroll as much as i want in a very smooth fashion.

What can i do to improve the initial display time?

Thanks and Happy new year :) :fireworks:

**Comment by ide** [comment]
The answer is to slice up rendering into smaller batches. 400 views is a lot since Views are somewhat expensive on iOS and Android even at the native level. How you slice up rendering is completely up to you, but there is a convenience API called ListView that will do this for you.

**Comment by tUrG0n** [comment]
Yeah indeed ListView solved it for me.
Thx!
