### ISSUE TITLE
Proposal: PixelRatio.pixel()

### ISSUE THREAD

**Issue by corbt** [facebook/react-native#5073]
It seems like a fairly common pattern to want a line that's the thinnest possible width. Currently this can be accomplished with a style something like:

```js
StyleSheet.create({
  myStyle: {
    borderBottomWidth: 1 / PixelRatio.get()
    [...]
  }
});
```

This works fine, but without reading the documentation of `PixelRatio` it's not obvious what's going on. 

I propose adding a function `PixelRatio.pixel` (or alternatively `PixelRatio.smallestPixel`) that simply returned the inverse of `PixelRatio.get`. This would make it immediately clear what a style using it is trying to accomplish, even to someone who hasn't read the PixelRatio documentation.

I'm happy to implement and document this if there's general agreement that it's a good idea.

**Comment by brentvatne** [comment]
I like this idea, let's move it into a pull request!

**Comment by corbt** [comment]
Cool, working on it.
