### ISSUE TITLE
React native js layers with android Java layer communication, real-time communication

### ISSUE THREAD

**Issue by amibition521** [facebook/react-native#5078]
The react native js layers with android Java layer communication, transmission key/value pair from each other.I know that can be gained through the event from the java data, but the underlying coming is an event, how do I get the keys?And how to turn. The values in the js file to the  Java layer, this I really don't have any idea, ask god for help.

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow and try to provide some more detailed information on exactly what you want to accomplish :)
