### ISSUE TITLE
How do you change the launch screen?

### ISSUE THREAD

**Issue by joshbedo** [facebook/react-native#5083]
I tried following this tutorial but it didn't work and i can't figure out how to change the default launch screen image.

https://medium.com/@jvlob/change-default-launch-screen-in-react-native-ios-app-544f94f1e947

**Comment by brentvatne** [comment]
Hi there! Please post this to StackOverflow, as @facebook-github-bot mentioned above :) This is nothing specific to React Native, any guide for how to do this on iOS will work.
