### ISSUE TITLE
resizeMode passed to Image children

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#5085]
@Thomas101: "on Android the resizeMode style gets passed to the children of an image resulting in a warning... e.g."

```
<Image style={{resizeMode:'cover'}}>
   <Text>Loading</Text>
</Image>
```

**Comment by Charca** [comment]
I don't see this happening in the latest version. @Thomas101 can you add an example of this behavior?

**Comment by Thomas101** [comment]
Thanks. This seems to be fixed in 0.17

**Comment by geirman** [comment]
looks like this issue could be closed

**Comment by geirman** [comment]
@facebook-github-bot close
