### ISSUE TITLE
Enable `babel-plugin-transform-es2015-function-name`

### ISSUE THREAD

**Issue by epeli** [facebook/react-native#5094]
When using function components with the arrow syntax this would make debugging a lot easier because the components will have a name in the React warnings and React devtools (once it works again https://github.com/facebook/react-devtools/issues/229). 

More info about this ES6 feature here http://www.2ality.com/2015/09/function-names-es6.html

----

On the side note is it possible to enable babel plugins from the userland?

**Comment by skevy** [comment]
@epeli we're close to getting the babel issue fixed.

We need to update Babel, and then provide some documentation on how to use a project .babelrc.

That will enable you to use whatever transforms you want.

Closing this now...in favor of #4062, where we're tracking the Babel issue.

**Comment by skevy** [comment]
@epeli also just FYI - here's the PR to update Babel https://github.com/facebook/react-native/pull/5097
