### ISSUE TITLE
Documentation for NavigatorNavigationBar?

### ISSUE THREAD

**Issue by mmahalwy** [facebook/react-native#5099]
Where is this located? I am searching the web to find good examples of this for android specifically and no luck.

**Comment by brentvatne** [comment]
@mmahalwy - no docs are published for it at the moment, but you can check out the example from UIExplorer here: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigationBarSample.js

**Comment by mmahalwy** [comment]
Thanks @brentvatne
