### ISSUE TITLE
<Navigator> and "endless swiping"

### ISSUE THREAD

**Issue by ippa** [facebook/react-native#5100]
Hi, I'm trying to implement 'endless swiping' where a user can swipe through an endless stream of pages (using Navigator.SceneConfigs.HorizontalSwipeJump).

Having played with various prototypes for the last 2 days I think an addition to the Navigator-API is needed to implement it well.

I think that the main-issue is that I can't easily create new routes for the navigator without jumping to them. For endless swiping to work well I need to be 1 step ahead all the time, so the user has something to swipe to.

I've tried pre-creating ~100 routes/pages with ```immediatelyResetRouteStack()```, but it comes with awkward jumping cause it will jump to the last route.. and then I have to trigger jumping back to the page the user was at.

I've tried using ```<Navigator initialRouteStack=[...] />``` to fill up empty "placeholder"-routes which I later (using 'didfocus'-event and navigator.replaceAtIndex) fill out with real content by fetching it over the network. But if I pre-create 50-100 empty routes I start seeing drops to ~30-40 fps (on my nexus5) even when only switching through empty ones and Not fetching any content over the network.

Asking around on IRC and checking SO I see others are having similar problems and are looking for solutions. 

Could ```immediatelyResetRouteStack()``` take a second option 'active route'? And if it's the same as the current route, no jumping will be triggered?

Could we have an ```navigator.add``` method that works like push, but doesn't jump to the added route?

**Comment by deminoth** [comment]
+1 to `navigator.add`

**Comment by KamuelaFranco** [comment]
Another way to deal with the route stack would be ideal.

**Comment by brentvatne** [comment]
You folks might want to bring this up in the [navigation-rfc repo](https://github.com/ericvicenti/navigation-rfc), where @ericvicenti is working on a new version of Navigator.

**Comment by KamuelaFranco** [comment]
@brentvatne I was thinking about attempting this outside of Navigator, as I'm currently using Redux to manage all state in my application. However, I'm very new to RN and not sure how to approach this. Also, is using a Flux library an anti-pattern in React Native? Seems like it isn't discussed much, and I see a lot of state handled at the component level.

**Comment by ericvicenti** [comment]
You should absolutely use flux patterns in react native! The example code mostly uses state for simplicity, but all of the react best practices are applicable in RN. At FB, we use Flux and Relay (which has flux-like patterns), but we're also big fans of Redux. You should use whatever you want!

**Comment by tomauty** [comment]
I'm currently working on a large RN + redux production app, and redux (and of course flux patterns in general) have made iteration insanely easy. Not at all an anti-pattern.

**Comment by tomauty** [comment]
Regarding your state comment: I generally confine state management to things that only the component itself cares about. You can see Dan's discussions about "smart" and "dumb" components for more color on this. Basically, if I do an action that affects the _application_ state, I want to be using the inherited actions from reducers. If I'm only modifying component state, I'll use `setState`. It's up to you to decide what's worthy of being considered "application state", but I generally think that anything I'd want to be able to restore from vanilla reload to be application-state-worthy.

**Comment by KamuelaFranco** [comment]
I think I have the right idea then. But I'm still confused as to how to implement this without rebuilding Navigator from scratch, e.g. its component parts. Because I would like routes to be part of my state in this case, but I'm not sure how to get Navigator to simply obey my Redux state tree. It currently maps that part of the application state to the way Navigator internally manages scenes. I'm just not sure how to drop the need for the navigator prop.

**Comment by tomauty** [comment]
Here's a snippet of how I've tied `Navigator` into redux. This probably isn't the best implementation, but hopefully it helps somewhat. This is the `Router` component.

```javascript
  componentWillReceiveProps(nextProps) {
    if (this.props.router.currentRoute === nextProps.router.currentRoute) { return; }
    switch (nextProps.router.type) {
      case 'ROUTER_REPLACE_AT_INDEX': this.refs.navigator.replaceAtIndex(nextProps.router.replacement, nextProps.router.index); break;
      case 'ROUTER_POP_TO_TOP': this.refs.navigator.popToTop(); break;
      case 'ROUTER_REPLACE': this.refs.navigator.replace(nextProps.router.currentRoute); break;
      case 'ROUTER_PUSH': this.refs.navigator.push(nextProps.router.currentRoute); break;
      case 'ROUTER_POP': this.refs.navigator.pop(); break;
      default: break;
    }
  }```

**Comment by KamuelaFranco** [comment]
@tomauty So your solution goes into every component that is a scene, and Navigator needs to be the main controlling component each time?

**Comment by ericvicenti** [comment]
Navigator doesn't have a declarative API, which makes it tricky to use with redux. The navigation components in https://github.com/ericvicenti/navigation-rfc are declarative and should be easier to use

**Comment by antigirl** [comment]
I think this should have always been in Navigator, theres several use cases - for example: Tinder UI, the way more cards get added as you swipe,

I'm not sure of any side effects yet however the modification is quite simple,
[Navigator.js]
```js
push: function(route, transitionFlag) {
// .... 
 if (!transitionFlag) {
   this._transitionTo(destIndex, nextSceneConfig.defaultTransitionVelocity);
 }
}
````

I can submit a proper pull request but i assume this version Navigator is going to get depreciated ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigator-and-endless-swiping

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
