### ISSUE TITLE
Way to retrieve TextInput value programmatically via property access or method call?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#511]
I've been looking @ the TextInput.ios.js source and noticed that there is no programmatic way for developers to query the current value.

Perhaps _onChange or _onTextInput should cache the value?

I'm happy to attempt a PR, but wanted to gather the team & community thoughts about this.

**Comment by jaygarcia** [comment]
I've put a hack together locally:
```
...
    onTextInputChange : function(event) {
        this.textInputValue = event.nativeEvent.text;
    },

...
                    <TextInput
                        placeHolder="Test placeHolder"
                        autoCapitalize="sentences"
                        style={styles.textInput}
                        ref="textInput"
                        onChange={this.onTextInputChange}
                    />
...
```
Works but i'm really not proud of it.

**Comment by frantic** [comment]
See Controlled Components: https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by jaygarcia** [comment]
Thanks @frantic .  It seems that I was onto the correct path with onChange. :-\ 

I'm used to the pattern of "asking" for the value, rather than it being constantly presented, so this feels a bit strange.

Many thanks for the prompt response.

**Comment by gs-akhan** [comment]
@jaygarcia 
I dont see event.target.value in case of "onSubmitEditing" event in react native, however I do see my value in event.nativeEvent.text, 
So is it ok to go with event.nativeEvent.text,
Thanks

**Comment by manask88** [comment]
onChange is not always the solution. I am having issues when I use keyboard shorcuts:
This is the scenario: I am filling up a login form (username and password)
I set a shortcut for my username.
When I enter the shortcut and then I push on the return button, I go to the next field (password).
When I enter the last key for the shortcut, onChangeText and onChange will return the value of the shortcut.
When I push enter, none of those events are called up and therefore , I am not able to get the actual value for the shortcut. 
Sine there is no way to get the value of the input text other than using those callbacks, what would be a solution for this case?

**Comment by zoontek** [comment]
This is how I do:

```js
class Login extends Component {
  constructor(props) {
    super(props)

    this.fields = {
      email: null,
      password: null,
    }

    this.state = {
      ...this.fields,
    }
  }

  render() {
    return (
      <View>
        <TextInput
          value={this.state.email}
          onChangeText={text => this.fields.email = text}
        />

        <TextInput
          value={this.state.password}
          onChangeText={text => this.fields.password = text}
        />

        <TouchableHighlight onPress={this._submitForm}>
          <Text>Submit</Text>
        </TouchableHighlight>
      </View>
    )
  }

  _submitForm = () => {
    const { email, phone } = this.fields

    this.setState({
      email,
      phone,
    })

    // do some stuff here…
  };
}
```

Probably not the best solution, but clean enough for me.

**Comment by flyingace** [comment]
Frankly, I believe that @zoontek's solution is the cleanest I've seen thus far. All the other solutions I've seen seem to be predicated on the notion that each field will have its own method used to update the state, otherwise how will the function know which state property it's supposed to be updating?

Additionally, `onSubmitEditing` seems somewhat unreliable in that it doesn't fire when the user changes fields without hitting a submit button, which may leave some values unrecorded. (This was the case at least in the XCode emulator, which may not reflect actual behavior.) Better perhaps to record each change to the text with `onChange`, retrieve all the values from an object recording those changes and then updating the state with that when the form's submit button is pressed.

**Comment by suyax** [comment]
thank you @zoontek very helpful

**Comment by mark0978** [comment]
@zoontek, your code above does not work for me unless I call this.setState.  I'm using react-ntave 0.22.2

Did they change the way react-native worked between Jan 10 and March?

**Comment by zoontek** [comment]
@mark0978 react-native change a lot, so yes, no hack needed using 0.22.2. I updated the snippet.

**Comment by mark0978** [comment]
@zoontek  Are you sure that is right?  Looks like you clobber the rest of the state that way.....

**Comment by zoontek** [comment]
@mark0978 I've just tried it with RN 0.22.2 and it works great.
The rest of the state don't change because I'm using this.setState(), and not this.state = {}

**Comment by mark0978** [comment]
It's good to know that, I'm new to react.

**Comment by janzenz** [comment]
@mark0978 If you are like and doesn't want to use or pollute state for one-off components here's what I did:

    export default class Registration extends Component {
      _register = () => {
        const payload = {
          firstName: this.firstName,
          /* other values */
        }
    
        console.log(payload)
      }
    
      render() {
        return (
          <RegisterLayout>
            <Text style={styles.welcome}>
              Register
            </Text>
    
            <InputText
              placeholder="First Name"
              onChangeText={(text) => this.firstName = text} />
            // More components...
            <CustomButton
              backgroundColor="steelblue"
              handlePress={this._register}>
              Submit
            </CustomButton>
         </RegisterLayout>
        )
      }
    }

**Comment by peacechen** [comment]
The value of TextInput may be retrieved through its `_lastNativeText`property.

this.refs.myTextInput._lastNativeText

The TextInput component needs a ref assigned to it of course.

**Comment by iamhabbeboy** [comment]
According to peacehen post, You can use
`  sendMessage() {
    let phone   = this.refs.phone._lastNativeText;
    let encrypt = this.refs.encryptkey._lastNativeText;
    //do something
  }
 <TextInput ref="phone" />
<TextInput ref="encryptkey" />
  <TouchableOpacity style={styles.btn}
                    onPress={this.sendMessage.bind(this)}
                >
                   <Text style={styles.btnText}>
                      Send Message
                   </Text>
 </TouchableOpacity>
`
Hope it help

**Comment by kylecorbelli** [comment]
No need to deal with `refs`. And here's how you'd clean up all the multiple calls to `this.setState` in case you have many form fields. Simply define a method (`updateFormField`) that takes a string parameter of the field name and returns an event-handling function:

```javascript
class SignIn extends React.Component {
  state = {
    email: '',
    password: '',
  }

  constructor (props) {
    super(props)
    this.updateFormField = this.updateFormField.bind(this)
    this.submitForm = this.submitForm.bind(this)
  }

  updateFormField (fieldName) {
    return (event) => {
      this.setState({
        [fieldName]: event.nativeEvent.text,
      })
    }
  }

  submitForm () {
    const {
      email,
      password,
    } = this.state
    // Now do something with email and password
  }

  render () {
    return (
      <View>
        <TextInput onChange={this.updateFormField('email')}/>
        <TextInput onChange={this.updateFormField('password')}/>
        <Button title="Sign In" onPress={this.submitForm} />
      </View>
    )
  }
}
```

**Comment by zoontek** [comment]
@kylecorbelli `refs` are only used in my example to focus on the next input when the keyboard submit button is pressed.

Your solution is interesting, and can be simplified to:

```js
class SignIn extends React.Component {
  state = {
    email: '',
    password: '',
  }

  updateFormField = fieldName => text => {
    this.setState({ [fieldName]: text })
  }

  submitForm = () => {
    const { email, password } = this.state
    // now do something with email and password
  }

  render() {
    return (
      <View>
        <TextInput onChangeText={this.updateFormField('email')} />
        <TextInput onChangeText={this.updateFormField('password')} />
        <Button title="Sign In" onPress={this.submitForm} />
      </View>
    )
  }
}
```

**Comment by kylecorbelli** [comment]
@zoontek nice!

**Comment by parmeet9891** [comment]
```
import React, { Component } from 'react';
import { AppRegistry, Text, TextInput, View, StyleSheet, TouchableOpacity } from 'react-native';

export default class PizzaTranslator extends Component {
  constructor(props) {
    super(props);
    this.state = {username: '', password: '', email: ''};
  
    this.login = this.login.bind(this);
  }
  
  login = () => {
    console.log(this.state, 'console')
    alert("Username : " + this.state.username);
  }
  
  render() {
    let {username, email, password} = this.state;
    return (
      <View>
        <TextInput
          style = {styles.input}
          value={username}
          placeholder = "Enter Your Name"
          refs = "textInput"
          onChangeText = {(username) => this.setState({username})}
          >
        </TextInput>
        
         <TouchableOpacity
          style = {styles.button} 
          onPress = {
            () => this.login()
          }>
          <Text>Submit</Text>
        </TouchableOpacity>
        
      </View>
    );
  }
}

const styles = StyleSheet.create({
  input : {
    flex:1,
    margin: 20,
    height: 20,
  },
  button : {
    textAlign: 'center',
    margin: 20,
    padding: 20,
    backgroundColor: 'steelblue',
  }
})

// skip this line if using Create React Native App
AppRegistry.registerComponent('AwesomeProject', () => PizzaTranslator);
```
This worked for me, getting username value and showing in alert.
