### ISSUE TITLE
what is the best practice to force update another UI component?

### ISSUE THREAD

**Issue by shrimpywu** [facebook/react-native#5120]
i have a question on SO, but no proper answer for more than a month. so i come here.
         http://stackoverflow.com/questions/33493105/how-to-update-another-tabs-state

Context:
I have two tabs inside a TabBarIOS.

First tab insert data into AsyncStorage

Second tab display all item from AsyncStorage

But when i run my app, after adding a new item from First Tab, navigate to second tab i don`t see page re-render, i will need to do a Command+R then i see my new data.

One way to resolve the issue is to read asyncStorage in shouldComponentUpdate, but notice that shouldComponentUpdate will be called constantly by react. While i only want to force update the UI on demand.

***Question***:
So in react native, what is the right way to update state of another UI component?

code sample:
https://drive.google.com/file/d/0B8kAIsj2xDnUMklIQmc0b3NiSVE/view?usp=sharing

**Comment by alvinwoon** [comment]
Try pubsub or event emitter. 
https://colinramsay.co.uk/2015/07/04/react-native-eventemitters.html

**Comment by shrimpywu** [comment]
thanks @alvinwoon
