### ISSUE TITLE
Can't open Chrome Debugger due to RCTBatchedBridge.m error

### ISSUE THREAD

**Issue by esauter5** [facebook/react-native#5121]
When I try to open the Chrome debugger on `master`, my app hangs and I get an `EXC_BAD_ACCESS` error on this line https://github.com/facebook/react-native/blob/master/React/Base/RCTBatchedBridge.m#L853 which was introduced in https://github.com/facebook/react-native/commit/89ae0e040d9c85d9f1adcd1f7df0f67b54ac7a7c

I'll try to dig a little deeper later when I have same time, although the answer may be obvious to someone else.

**Comment by christopherdro** [comment]
@esauter5 Running into this as well.

**Comment by esauter5** [comment]
Closing this. It looks like 18cdead76 reverted the bad commit.
