### ISSUE TITLE
Can't Open Developer Menu

### ISSUE THREAD

**Issue by jkhustler** [facebook/react-native#5122]
I am on React Native 0.17.0 and trying to open the Developer Menu by shaking the simulator(Hardware> Shake Gesture) after downloading code from my local server. Nothing appears.

My schemes and build configurations are not named "Debug" and "Release". Are the names of the configuration important to making the developer menu work? Or perhaps can I directly include some variable in the .xcconfig files?

**Comment by gre** [comment]
yeah you must be in Debug mode for the dev menu to works.

How have you bootstrapped the project? If you bootstrap with react-native init you should have the 2 modes available in *Product → Scheme → Edit Scheme... (or press ⌘ + <).*

**Comment by jkhustler** [comment]
I am integrating react native with a pre-existing project. So React Native literally looks at the name of the build configuration and not a flag inside the actual build configuration file?

**Comment by mikeygee** [comment]
I ran into the same issue. It would be nice if the dev menu wasn't tied to the configuration name. This basically limits us to one config for development. I have defined some others, and can't reload or debug with these.

**Comment by satya164** [comment]
@mikeygee @jkhustler You can customise whether to enable dev menu in MainActivity.

**Comment by mikeygee** [comment]
@satya164 This issue applies to XCode / iOS development

**Comment by satya164** [comment]
@mikeygee Ah. I'm sure there should be something in iOS for this also. Need to check.

**Comment by jkhustler** [comment]
Yes something like that for iOS would be tremendously helpful.

**Comment by mkonicek** [comment]
Can anyone with iOS experience try to debug why this happens?

@nicklockwood is there an obvious place where we rely on the configuration being named 'Debug'?

**Comment by nicklockwood** [comment]
It's not based on the configuration name, it depends on the DEBUG preprocessor macro being set to 1. This is set up automatically if you use the default Debug target, but you can add it manually in build settings if you're using custom targets.

**Comment by nicklockwood** [comment]
<img width="653" alt="screen shot 2016-02-21 at 23 17 12" src="https://cloud.githubusercontent.com/assets/546885/13206217/4027edf8-d8f1-11e5-8f69-6a48931fea5b.png">

**Comment by mkonicek** [comment]
Awesome, thank you so much Nick!

@chrisbianca Can you verify? Let's close this issue if that works.

**Comment by mikeygee** [comment]
It is not using the DEBUG macro based on what I've observed. If you even just change the configuration name from Debug to something else, it will stop working. Change it back to Debug, and it works again. Cloning the Debug configuration, which includes the macros also does not work.

**Comment by chrisbianca** [comment]
Agree with @mikeygee - his findings match what I identified in https://github.com/facebook/react-native/issues/6011.
There's more detail of the different things I tried to get this working there.

**Comment by nicklockwood** [comment]
I can assure you that it *is* using the DEBUG macro - you can see the code that references it inside RCTDefines.h.

I suspect the issue is that the Debug target in your project is separate from the one in the React framework's subproject.

When they are both named Debug, Xcode seems to know to set them both, but if you rename the one in your project, I guess that switching to the debug profile in your project no longer has the effeect of toggling the React library itself to Debug mode as well.

I'm not sure how to work around that though.

**Comment by mikeygee** [comment]
@nicklockwood Thanks for the tip. I got it working by clicking on the React.xcodeproj in the Libraries directory, and adding a config with the same name as I use in my app project. This makes things much easier, thank you!

**Comment by jkhustler** [comment]
@nicklockwood thanks for pointing out the file. This seems resolved. Closing.

**Comment by Thorbenandresen** [comment]
@mikeygee can you please tell me which steps you specifically took to resolve this? I got the same problem today without me (knowingly) changing something

**Comment by mikeygee** [comment]
@Thorbenandresen Check your scheme settings. The current scheme shows at the top of Xcode. Click on it, then Edit Scheme. Under "Run", make sure the build configuration is set to Debug. If it's set to something different, you won't get the dev menu.

If you want to use a configuration not named "Debug" like me, then it's a little more work to add a config to the React library, but it doesn't sound like you need that.

**Comment by Thorbenandresen** [comment]
@mikeygee thanks but that seems fine. I have described my issue here in more detail: http://stackoverflow.com/questions/36413602/cant-open-dev-menu-via-cmdd-or-reload-via-cmdr-any-longer

**Comment by jeffbowen** [comment]
Check out my [comment on issue 2246](https://github.com/facebook/react-native/issues/2246#issuecomment-217187621).

**Comment by NickJorgensen** [comment]
> @nicklockwood Thanks for the tip. I got it working by clicking on the React.xcodeproj in the Libraries directory, and adding a config with the same name as I use in my app project. This makes things much easier, thank you!

I would like to confirm that this is working and I would also like to add that I had to do this with RCTWebSocket.xcodeproj or the chrome debugging tools would not work.

With the above fixes, setting up DEV, PROD, and STAGE environments is working for me.  Chrome debugging and live reload are working as well.  I followed the tutorial here [](http://www.blackdogfoundry.com/blog/migrating-ios-app-through-multiple-environments/) which uses multiple Project - Info - configuration setups.

**Comment by alekhurst** [comment]
We came across this problem, and altered both the RN bundle script (to match any build configuration with the name *Debug) and then wrote a ruby script to sync the build configurations throughout our Pods. 

This also solves the problem of not being able to open "Debug in Chrome" (and a lot of other bugs...)

Check steps 4 and 5 here: https://zeemee.engineering/how-to-set-up-multiple-schemes-configurations-in-xcode-for-your-react-native-ios-app-7da4b5237966#.ucgthnlfd

**Comment by jomaint** [comment]
I am unable to open dev menu, using all the above stated methods. Anyone has any other alternative solutions?

**Comment by thundenilla** [comment]
@jomaint hey! did you manage to solve it? seems like we're having the same issues. i cant open the dev-menu on my emulator (genymotion)

**Comment by blargity** [comment]
I think I've solved this in a somewhat generic way that will allow everyone to share the solution. You just put your schemes in your package.json and the script deals with the build configs and script steps.

https://github.com/Thinkmill/react-native-schemes-manager

@alekhurst your work is the basis for this, thanks! I took what you did in Ruby and moved it over to Node, as well as added an automatic step to update the run script step in the build so that it should be pretty plug and play.

@thundenilla, it's *really* early days and I've only tried it on one project of mine, but feel free to give the package above a whirl and see if it works for you. Any feedback would be awesome.

**Comment by jnrepo** [comment]
@jomaint did you ever solve this? We just ran into this issue randomly and have no idea what is going on

**Comment by stuartjeasyodds** [comment]
@jnrepo I have the same issue with react-native 0.42.0. 

It started happing after I changed my navigation to the new [React Navigation](https://reactnavigation.org/docs/intro/) and added the Native Animation library.

Have you fixed the issue?

**Comment by jnrepo** [comment]
@stuartjeasyodds I had to remove `React` from my Podfile and had to manually move the libraries I needed into my Xcode project, which let me use it again. I followed what others did on this ticket https://github.com/facebook/react-native/issues/10366

**Comment by stuartjeasyodds** [comment]
thanks @jnrepo. Fingers crossed the next few react native updates aren't as painful!

**Comment by jnrepo** [comment]
@stuartjeasyodds seriously, its like playing with fire

**Comment by ngnclht1102** [comment]
@blargity hey Kenvin, thanks!

**Comment by pencilcheck** [comment]
I solved it by making sure that the project that builds React target (sometimes it might not be in your primary xcodeproject) has the preprocessor flag DEBUG=1

For example, i'm using detached expo project, which creates a Pod.xcodeproj next to the main xcodeproj within the xcodeworkspace.

I made sure in my bottom section of the Podfile, this happens
```
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      # Build React Native with DEBUG enabled
      if target.name == 'React'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEBUG=1'
        end
      end
    end
  end
```

Then run `$ pod install` in the ios folder to make sure that your project configuration contains that flag, then off you go!

**Comment by nikhilag** [comment]
It's still not working for me on Genymotion Android Emulator. 
@thundenilla Were you able to fix this?

**Comment by sneerin** [comment]
same to me, it's strange but on real devices it works, it seems like debugging schemes are over-complicated so many issues. separate projects for managing this and still lot's of issues.

**Comment by av-k** [comment]
I do not pretend to solve the problem, but as an option you can: 
Simulator > Hardware > Keyboard > Connect Hardware Keyboard (to active)
![Image of bug](https://raw.githubusercontent.com/av-k/pub/master/images/xcode/simulator-ios-dev-menu.png)

**Comment by anhnnp** [comment]
i found ansewer from stackoverflow: 
https://stackoverflow.com/a/47268425/4380510
thanks mriza1815!

**Comment by deva11** [comment]
Here is the answer for this. 

It happens with wrong import statement in MainApplication.java, You have to check if any statement like `import com.facebook.react.BuildConfig;` is in the imports. If so, remove that and run  

`react-native run-android`

No need to delete assets folder
