### ISSUE TITLE
[Android] Method for pausing application/Activity, and lifecycle hooks

### ISSUE THREAD

**Issue by jaysoo** [facebook/react-native#5123]
There is a need for Android apps to pause instead of exiting completely when the user presses the back button.

Also, there should be support for lifecycle hooks similar to [`AppStateIOS`](https://facebook.github.io/react-native/docs/appstateios.html). i.e. app resume, app pause, (app destroyed?)

I'm currently using my own module for this, but it'd be great to see this supported in core.

https://github.com/jaysoo/react-native-activity-android

Also: https://productpains.com/post/react-native/android-method-for-pausing-applicationactivity-and-lifecycle-hooks/

**Comment by christopherdro** [comment]
Added via https://github.com/facebook/react-native/commit/c2d75d7a65a2bdf6e1e24a9ce887f9492be477de
