### ISSUE TITLE
Issues in installing homebrew

### ISSUE THREAD

**Issue by Hari70a** [facebook/react-native#5149]
Can u explain the procedure to install  react-native for android

**Comment by Hari70a** [comment]
Please provide me the steps to install react native for android

**Comment by jaggs6** [comment]
This should help you get started @Hari70a 

https://facebook.github.io/react-native/docs/getting-started.html#content

https://facebook.github.io/react-native/docs/android-setup.html#content

**Comment by Hari70a** [comment]
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
I have the a

**Comment by satya164** [comment]
@Hari70a Homebrew is for Mac (and Linux). On windows you can't install homebrew. It's required to install watchman if you don't want to compile from source.

On windows just do `npm install -g react-native`. No need to install watchman (it'll be a bit slower, but it'll work).
