### ISSUE TITLE
Cannot use "Api" as folder name when require modules

### ISSUE THREAD

**Issue by xiaodao** [facebook/react-native#5151]
I have a viewModel which need to do http request and an endpoint configured in Api/endpoint.js

If I use `var api = require("../Api/endpoint.js")`, then I will get 

`Unable to resolve module..` error.

But if I rename the "Api" folder to "Endpoint" or something else, the error disappears.

I'm working on iOS project.

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow
