### ISSUE TITLE
console.warn shows two times in yellowBox and once in console

### ISSUE THREAD

**Issue by kitze** [facebook/react-native#5154]
I have this simple React Native application https://gist.github.com/0061e2aeeb2d6e2529b8
In the render method i'm printing console.warn('Rendering component') 
 
In the yellowBox i'm seeing (2) Rendering component -> https://i.imgur.com/OkyrEzE.png
In the chrome console it's only printed once -> https://i.imgur.com/IpiT2Ph.png

Is this a bug?

**Comment by Tiagojdferreira** [comment]
I can confirm I am having the same issue with React 0.19.

**Comment by grabbou** [comment]
Tested on master and the warning box appears only once. If you could confirm it's no longer an issue or give additional information, that would be great.

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-8** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
