### ISSUE TITLE
react native ART

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#5157]
Any Documentation for art on Android?

**Comment by Roconda** [comment]
Hi @antoxi4, did you checkout this commit's summary? 27ac04742ab4665cd529fe63fd68a30db9293b76

Hope this helps.

**Comment by antoxi4** [comment]
Yes.Just i can't  make LinearGradient. And nobody can't help me((

**Comment by tomauty** [comment]
@antoxi4 try out this library: https://github.com/brentvatne/react-native-linear-gradient 

I use it for my app and love it :)

**Comment by antoxi4** [comment]
Yep, but i'm not shure what it working with shape in ART)

**Comment by tomauty** [comment]
What's the use case you have that isn't solved by this implementation?

**Comment by maraujop** [comment]
That commit you mention @Roconda quotes:

> Tested in open source by adding a `import com.facebook.react.ARTPackage;` and `.addPackage(new ARTPackage())` to UIExplorerActivity.java, running

However, I've been unable to fin ARTPackage in version 0.18 and compilation fails prompting it cannot find this library, how do you start using ART in Android? what am I doing wrong?

Cheers,
Miguel

**Comment by tomauty** [comment]
^ Having the same issue

**Comment by antoxi4** [comment]
this example usage ART in 0.18.0 or later RN on Android.

```javascript
var {
  AppRegistry,
  StyleSheet,
  Text,
  ART,
  View,
  Dimensions
} = React;

var {
    Shape,
    LinearGradient,
    Transform,
    Group,
    Surface
} = ART;
```

**Comment by browniefed** [comment]
@facebook-github-bot duplicate #5200
