### ISSUE TITLE
react-native-cli v0.1.8 `react-native init project` hangs

### ISSUE THREAD

**Issue by verdammelt** [facebook/react-native#5159]
Running `react-native init project` fails to complete with v0.1.8 while v0.1.7 completes successfully.

The project directory, and `package.json` file are created. It appears that the `npm install` also completes, but the `npm` process never terminates. The react-native script never moves on to the "Setting up new React Native app".

The problem is reproducible. It works for 0.1.7 and does not with 0.1.8. No other environment changes. 

Using `dtruss` shows no system calls from `npm` while it is hanging.

Versions:
* nvm 0.30.1
* node v5.3.0
* npm 3.3.12.

**Comment by verdammelt** [comment]
With a little debugging help from @mjording it appears that problem was introduced with the `--verbose` and `--debug`.

The difference can be seen at https://github.com/facebook/react-native/commit/6af7ae55b1ccffd185eb269b81f9ed1ee9f77cc7#diff-61047f57836fe20d8104bb5fc5155fe3. (approximately line 192)

In v0.1.8 without either the `--verbose` or `--debug` flags the `{stdio: 'inherit'}` is not passed in to the `spawn` function.

This reported problem does not occur if these flags are provided.

**Comment by skevy** [comment]
cc @mkonicek

**Comment by montogeek** [comment]
Thank you! I just hit this bug :)

**Comment by gasperz** [comment]
i also encountered this bug. Tried with react-native-cli 0.1.9 and --verbose or --debug is still needed to succeed at init.

**Comment by mkonicek** [comment]
That's bad. Will take a look this weekend.

**Comment by mkonicek** [comment]
What OS are you using? Might be because of npm 3?

For me:

    $ npm list -g --depth=0
    ...
    react-native-cli@0.1.9

    $ npm --version
    2.7.1

    $ node --version
    v4.2.1

    $ react-native init foo
    Installing react-native package from npm...
    # finishes successfully

**Comment by mkonicek** [comment]
@ide We still recommend npm 2 right? https://facebook.github.io/react-native/docs/getting-started.html

**Comment by ide** [comment]
@mkonicek Yeah, although I've been testing npm 3 myself for the past two weeks to see if it is any better. So far haven't had major problems that I couldn't fix myself.

**Comment by verdammelt** [comment]
Early when trying to debug this I switched between npm 3 and npm 2 and back. I *believe* that it failed in both cases - but I will test again.

**Comment by montogeek** [comment]
I added the --verbose flag and it worked perfectly

**Comment by verdammelt** [comment]
It still fails with npm2. I just tried both 0.1.8 and 0.1.9

**Comment by verdammelt** [comment]
@mkonicek OS = OSX

**Comment by mkonicek** [comment]
I've just committed https://github.com/facebook/react-native/commit/521bd03f0a94df35e21d368a3416599f5f01f5dc and released 0.1.10: https://www.npmjs.com/package/react-native-cli

**Comment by gasperz** [comment]
It is working for me now. 
btw I am using it with:
OSX
npm 3.3.12
node 5.4.0
react-native-cli 0.1.10

Thank you very much.

**Comment by gustavjf** [comment]
I was having the same issue on 0.1.9 but can also confirm 0.1.10 fixes the problem for me. Thanks.

OSX
npm 3.3.12
node 5.4.0

**Comment by verdammelt** [comment]
I have tested react-native-cli 0.10.0 with both npm 2.14.15 and 3.5.3 and it works. Thanks

**Comment by mkonicek** [comment]
OK I'll close this, sorry about the breakage guys!
