### ISSUE TITLE
Ability to update navigationBar in Navigator

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#5177]
Currently we're able to define our own navigationBar when creating the Navigator:

```
<Navigator
    navigationBar={<MyBasicToolbar />}
```

This works well, however currently I don't see any way (unless it's not documented?) to replace this?

Lets say I push to a new component, however with this I want the navigationBar to be completely different with new functionality - maybe something like [this](https://github.com/ManuelPeinado/FadingActionBar).

![image](https://cloud.githubusercontent.com/assets/842078/12166255/88d9553a-b51c-11e5-84bf-f7fe809ab2cb.png)

This would most probably be another component, but how would I replace the existing `MyBasicToolbar`?

Something like:
```
this.props.navigator.push({
    message: 'Change toolbar',
    sceneConfig: Navigator.SceneConfigs.FloatFromBottom,
    navigationBar: <FadingActionBar some='prop' />
});
```

Is this possible? Do-able?

**Comment by bozzmob** [comment]
Hi @Ehesp It is possible. And there is already a react native implementation [react-native-parallax-scroll-view](https://github.com/jaysoo/react-native-parallax-scroll-view). It's really a great implementation. I have tried it and used it. :)

**Comment by Ehesp** [comment]
But the problem is, if I define a Toolbar on the Navigator, and then only want a specific View to have this other parallax scroll view, how am I supposed to replace it?

**Comment by ide** [comment]
Navigator doesn't support this -- for one, it's not clear how it should replace the old nav bar with the new one. What you could do is write a custom nav bar (start with the existing nav bar implementation and fork it yourself) so that it transitions the way you want it to.

**Comment by Ehesp** [comment]
@ide Thanks, I will figure something out was just hoping there was a simple way!
