### ISSUE TITLE
Upgrade to react-tools 0.13.1, drop jstransform

### ISSUE THREAD

**Issue by zpao** [facebook/react-native#518]
At least until I ship https://github.com/facebook/jstransform/pull/81, we should change react-native to just use `require('react-tools').transform` directly. The transform step we have right now is pretty wonky. All of https://github.com/facebook/react-native/blob/master/packager/transformer.js#L26 can pretty much be replaced with a single call, with options `{harmony: true, stripTypes: true}`

cc @spicyj @amasad

**Comment by ide** [comment]
Can this be closed out Friday too?

**Comment by zpao** [comment]
Yea, I closed my PR to actually switch to jstransform so lets close this too.
