### ISSUE TITLE
"Naming collision detected" on start

### ISSUE THREAD

**Issue by siuying** [facebook/react-native#5180]
Found a "Naming collision detected" on launch, where a fbjs file is collides with another fbjs files ...

```
Error building DependencyGraph:
 Error: Naming collision detected: app/node_modules/fbjs/flow/include/CSSCore.js 
 collides with app/node_modules/fbjs/lib/CSSCore.js
```

```
react-native -v
react-native-cli: 0.1.8
react-native: 0.18.0-rc
```

**Comment by respectTheCode** [comment]
I am running into the same problem

**Comment by fsp** [comment]
I solved this issue by erasing fbjs from react native's node_modules folder.

**Comment by corbt** [comment]
I ran into this same issue when updating from react-redux 3 to 4. I tried @fsp's solution but it didn't fix it. I ended up blowing up the whole `node_modules` folder and reinstalling, and **then** doing what @fsb said, which fixed the issue for me. 

I'm using 0.18-rc (but I've switched between 0.18-rc, 0.17 and `master` a number of times recently, so it's possible my `node_modules` folder was in a weird/inconsistent state).

**Comment by masom** [comment]
Happens on  `rm -rf node_modules && npm install` with `0.18.0-rc`

**Comment by txix** [comment]
Having the exact same issue with the fbjs package. Removing it manually did not fix it for me, because a conflict still exists but then in the node_modules/fbemitter directory.

**Comment by rclai** [comment]
I am also having this issue and none of the above solutions worked at all, even with `npm cache clear`.

**Comment by adamterlson** [comment]
Try upgrading to npm@3. Does it work then (after deleting node_modules and npm installing again?

**Comment by jasonmerino** [comment]
I'm also running into a similar naming collision error when trying to upgrade to 0.18.1. Mine shows as follows:

```bash
[10:33:06 AM] <END>   Crawling File System (1352ms)
[10:33:06 AM] <START> Building in-memory fs for JavaScript
[10:33:06 AM] <END>   Building in-memory fs for JavaScript (335ms)
[10:33:06 AM] <START> Building in-memory fs for Assets
[10:33:06 AM] <END>   Building in-memory fs for Assets (310ms)
[10:33:06 AM] <START> Building Haste Map
[10:33:07 AM] <START> Building (deprecated) Asset Map
[10:33:07 AM] <END>   Building (deprecated) Asset Map (159ms)
Error building DependencyGraph:
 Error: Naming collision detected: /Users/jason.merino/Code/MyApp/node_modules/fbjs/flow/include/warning.js collides with /Users/jason.merino/Code/MyApp/node_modules/fbemitter/node_modules/fbjs/lib/warning.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/jason.merino/Code/MyApp/node_modules/promise/lib/core.js:37:12)
    at /Users/jason.merino/Code/MyApp/node_modules/promise/lib/core.js:123:15
    at flush (/Users/jason.merino/Code/MyApp/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

I have done the following and it still shows up:

`rm -rf node_modules`
`npm cache clean`
`npm i`

Here's my current setup

npm 3.3.12
react native 0.18.1

**Comment by corbt** [comment]
Ok yeah @jasonmerino probably the version of fbjs that "fbemitter" wants doesn't match the version that react-native requires, so even npm3 installs it twice. This is a problem we need to get solved.

**Comment by jasonmerino** [comment]
Thanks @corbt! Yeah, I was thinking that was odd that npm3 still had some nested dependencies, but a version mismatch makes sense.

**Comment by ferologics** [comment]
Same problem here on: 
npm 3.3.12 
react native 0.18.1

 Error: Naming collision detected: /Users/master/Pomodoro/node_modules/reactfire/node_modules/react/lib/BeforeInputEventPlugin.js collides with /Users/master/Pomodoro/node_modules/react/lib/BeforeInputEventPlugin.js

**Comment by ferologics** [comment]
After deleting the BeforeInputEventPlugin from "node_modules/reactfire/" dir I get

 Error: Naming collision detected: /Users/master/Pomodoro/node_modules/reactfire/node_modules/react/lib/CSSCore.js collides with /Users/master/Pomodoro/node_modules/fbjs/lib/CSSCore.js

**Comment by ericraio** [comment]
@fsp thanks! I was able to fix this by removing the fbjs directory. I hope there is a proper solution soon.

**Comment by yelled3** [comment]
is this also an issue with `v0.19.0-rc` ?

**Comment by danpe** [comment]
Still having the same issue either using npm2 or npm3

**Comment by jasonmerino** [comment]
I'm getting a new error in my project after installing `babel-preset-react-native` and adding it to my `.babelrc` file. The odd thing is that it's complaining about a `package.json` file which, obviously, doesn't use the `@providesModule` comment.

```sh
Error building DependencyGraph:
 Error: Naming collision detected: /Users/jason.merino/Code/MyApp/node_modules/babel-preset-react-native/node_modules/react-transform-hmr/package.json collides with /Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/react-transform-hmr/package.json
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:112:32
    at tryCallOne (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/jason.merino/Code/MyApp/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by joshuapinter** [comment]
Getting the same error over here as well. Looks like `fbemitter` and `react-native` are both including the same `warning.js` and this causes it to barf up.

```bash
Error: Naming collision detected: 
node_modules/fbemitter/node_modules/fbjs/lib/warning.js 
collides with 
node_modules/react-native/node_modules/fbjs/lib/warning.js
```

This seems.... avoidable.

I'm new to React and React Native (and npm actually), any ideas?

Thanks.

**Comment by jasonmerino** [comment]
@joshuapinter The consensus seems to be adding a `postinstall` script to your `package.json` file that removes all `fbjs` folders in node_modules that is not at the top level. [Check this gist out](https://gist.github.com/jrichardlai/a6a36352e1b98eb2946a) for help on that.

This also assumes that you have installed `fbjs` as a dependency in your project.

**Comment by yelled3** [comment]
i'm using react-native `v0.19.0` & `npm3` and I still get the same error.
the only thing that worked for me was using the hack mentioned by @jasonmerino.

**Comment by rclai** [comment]
By the way, what's with 0.19.0? Last I checked it was an official release and all of a sudden it's back to 0.18.0?

**Comment by joshuapinter** [comment]
@jasonmerino Thanks for the advice. I created the postinstall script and did a fresh npm install. Now I'm getting this: 

```bash
Error: Naming collision detected: 
node_modules/fbjs/flow/include/toArray.js 
collides with 
node_modules/fbjs/lib/toArray.js
```

Any ideas?

Many Thanks!

**Comment by ericmasiello** [comment]
Does anyone know if downgrading to react-redux 3.1.2 and using react native 18 still works?

**Comment by rclai** [comment]
@ericmasiello, yes it works, I had to do that.

**Comment by ajwhite** [comment]
Having the same issue over in https://github.com/dancormier/react-native-swipeout/issues/65

**Comment by arunabha** [comment]
@joshuapinter What worked for me (react native 0.19, npm 3.6.0) was to pin fbjs to 0.6.1 and ensuring that only the top level fbjs was present (following https://github.com/facebook/react-native/issues/5467)

```bash
npm uninstall fbjs
npm install fbjs@0.6.1
find . -name 'fbjs' -print (delete all fbjs directories except the one at the top level)
```

Hope this helps. I really love React Native, but upgrades are certainly not good for the hairline :-)

**Comment by joshuapinter** [comment]
Voila!

Thanks @arunabha!

I see this with Rails and Bundler from time to time but I didn't expect it with only a few modules in the package.

**Comment by iTonyYo** [comment]
Check [**here**](https://gist.github.com/iTonyYo/ff9d76fbb3a3e366a876) to solve this issue. :clap::+1::smiley:

**Comment by daemonchen** [comment]
@iTonyYo It doesn't work for me.

my npm version is 3.3.12; my react-native is 0.20.0.

I try `rm -rf node_modules/` & `rm -rf $TMPDIR/react-*` & `find . -name 'fbjs' -print | grep "\./node_modules/fbjs" -v | xargs rm -rf` & even change all the `fbjs` dependencies to `0.7.2`,
but it's still not work...

**Comment by Kureev** [comment]
Run your packager with a `--resetCache` flag.
```
$ ./node_modules/react-native/packager/packager.sh start --resetCache
```

**Comment by license2e** [comment]
It isn't just *fbjs* that is throwing the error, its also *react*

Running `npm dedupe` got it past the "Naming collision detected"

**Comment by yelled3** [comment]
@license2e can you please write a step by step solution? (& specify versions, etc...)

**Comment by jsierles** [comment]
Thanks to everyone for the suggested fixes provided in this thread.

As of the upcoming 0.22 release, fbjs and react are consumed from npm, not vendored, so most of these issues should go away. Please give 0.22.0-rc4 a try!

To keep issues focused on current bugs, we're closing this issue.

Feel free to continue the discussion here for earlier versions, or reopen should this issue come back using 0.22.0. Thanks!

**Comment by rahulbhankar786** [comment]
getting same error.

Error building DependencyGraph:
 Error: Naming collision detected: E:\react-native demo\demo-app-master\node_modules\react-native\node_modules\fbjs\lib\CSSCore.js collides with E:\react-native demo\demo-app-master\node_modules\react\node_modules\fbjs\lib\CSSCore.js
    at HasteMap._updateHasteMap (E:/react-native demo/demo-app-master/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:132:13)
    at E:/react-native demo/demo-app-master/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:103:28
    at tryCallOne (E:\react-native demo\demo-app-master\node_modules\promise\lib\core.js:37:12)
    at E:\react-native demo\demo-app-master\node_modules\promise\lib\core.js:123:15
    at flush (E:\react-native demo\demo-app-master\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
