### ISSUE TITLE
[Jest] ReferenceError with inlineRequire: true

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#5182]
Possibly related to #3999 @cpojer comments.

After upgrading from 0.14.2 to 0.17 and using react-native preprocessor.js - with default value set to true:
```
ReferenceError: /src/auth/newPasswordForm.js: _immutable is not defined
        at Object.<anonymous> (src/auth/newPasswordForm.js:3:30)
```
that:
```js
import {Map} from 'immutable'
```
is simply striped out from transformed code (the first line in the file). Setting it to false makes tests green again.

Funny fact is that it's only affected by the jest. When running normally with packager - all goes smoothly.

**Comment by wvengen** [comment]
I'm having a similar issue, replacing `import ... from ...` with `require()` works around the error. Perhaps somehow Babel is not setup correctly while testing?

**Comment by ColCh** [comment]
Same, for jest `0.9.0-fb2` and react-native `0.19`.
Probably, using `require` or setting `inlineRequires: false` gets work done, but any update on this issue?

**Comment by grabbou** [comment]
Setting inlineRequires: false on 0.22 makes it work again

**Comment by cpojer** [comment]
btw. I'll be recommending to use `babel-jest` together with `babel-preset-react-native` but I haven't had enough time to rewrite the documentation for this yet, unfortunately.

**Comment by grabbou** [comment]
This is still a super breaking thing for us internally @cpojer, so I'd be more than happy to submit few patches & try out undocumented solutions to get it working

**Comment by cpojer** [comment]
Thank you for your patience. We launched Jest 14.0 with experimental react-native support:

* [Blog Post](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
* [React-Native Tutorial](http://facebook.github.io/jest/docs/tutorial-react-native.html)

Please feel free to create new issues after trying out the new integration if any issues remain.
