### ISSUE TITLE
Developing for iOS on Windows

### ISSUE THREAD

**Issue by richierob62** [facebook/react-native#5189]
1. Is there a timeline or roadmap for the capability of developing for iOS using React Native on a Windows machine? (I am aware that Android development with a few minor inconveniences is already possible).

2. I'm a relative newbies to asking questions on github, so if is the wrong way to do it, please guide me to a place I can learn the proper protocol.

**Comment by ide** [comment]
Frankly I don't think this is going to be practical nor on the roadmap for FB because of they're almost entirely on Macs. For this reason and several others, one of my top tips for learning and working with React Native is to get a Mac.
