### ISSUE TITLE
Bug and/or best practice question around usage of CocoaPod

### ISSUE THREAD

**Issue by andrewsardone** [facebook/react-native#519]
Hi there! Given that this is my first React Native issue, let me just say, “awesome work!” This is an impressive project, and I especially appreciate the team open sourcing it.

I’m up against an issue using React Native when brought in as a [CocoaPods dependency](http://cocoapods.org/pods/React).

At first, the structure looks sound. My `Pods/React` directory includes everything and I’m able to compile an app that constructs a simple `RCTRootView`, but upon serving up my bundle JS file simple components seem to be throwing errors:

```
RCTJSLog> "Running application "ReactCocoaPodsDemo" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTRawText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTRawText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTRawText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTRawText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTText"
[RCTLog][tid:0x7f8528c53570][RCTUIManager.m:710]>No manager class found for view with module name "RCTRawText"
```

I’ve posted [a sample repo](https://github.com/andrewsardone/ReactCocoaPodsDemo) with steps to recreate the issue:

1. `git clone https://github.com/andrewsardone/ReactCocoaPodsDemo`
- `cd ReactCocoaPodsDemo && open ReactCocoaPodsDemo.xcworkspace`
- In a shell, run `script/server` and leave it running
- In Xcode, `⌘R` to build and run
- Note that no [`<Text>` components](https://github.com/andrewsardone/ReactCocoaPodsDemo/blob/aab3030cfd472d36b38c84314ef970190a32c124/index.ios.js#L15-L30) are rendered, and Xcode’s console is noting the above warnings

I’m at a loss on how to move forward, so any help would be appreciated.

Thanks!

**Comment by ide** [comment]
You could try to pull in #508 and #285 and optionally #261. The current master branch doesn't handle cocoapods very well but once something like a scalable module system (#235) is built out things should get a lot better.

**Comment by andrewsardone** [comment]
Thanks for the reply, @ide! I’ll take a look at those issues, but actually my problem was much simpler: I simply didn’t include the `React/RCTText` subspec dependency in my `Podfile`. This was pointed out to me by @mudetroit: https://github.com/andrewsardone/ReactCocoaPodsDemo/pull/1.

I’m excited to see development of a broader module system (https://github.com/facebook/react-native/issues/235), so I’ll catch up on that thread. But frankly, right now [this CocoaPods setup](https://github.com/andrewsardone/ReactCocoaPodsDemo) doesn’t seem too bad!

Closing the ticket – cheers!
