### ISSUE TITLE
Error when running packager

### ISSUE THREAD

**Issue by dentrite** [facebook/react-native#5190]
The message I got in chrome

~~~~~~~~~~~~~~~~~~~~~~~~~
TransformError: E:\\TestProject\\node_modules\\react-native\\node_modules\\react-transform-hmr\\node_modules\\react-proxy\\node_modules\\react-deep-force-update\\lib\\index.js: Cannot read property 'error' of null
~~~~~~~~~~~~~~~~~~~~~~~~
react-native-cli@0.1.7, node.js 4.1 on Win 8

**Comment by corbt** [comment]
Did this error just start after the upgrade to react-native 0.18-rc? It may be related to #5188, you have the same error message we've been running into. It looks like packager may not be passing through underlying babel error messages.

**Comment by corbt** [comment]
This should have been cleared up in 0.18. If it's still an issue after upgrading please reopen.
