### ISSUE TITLE
ViewPagerAndroid doesn't allow null as a child

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#5195]
Here's an example:

```
<ViewPagerAndroid
    style={{ flex: 1 }}
    initialPage={0}
>
    {false && 
        <View>
            <Text>Previous</Text>
        </View>
    }
    <View>
        <Text>Current</Text>
    </View>
    <View>
        <Text>Next</Text>
    </View>
</ViewPagerAndroid>
```

I've put in `false` right now, but this happens with a variable from state/props. Basically doing this throws a blank error (`{}`). However if I change the `false` to `true` it works fine.

Any ideas? Sometimes I don't want to render the "Previous" section.

**Comment by satya164** [comment]
I always use ternary operators,

```js
{true ?
    <Text>Hello</Text> :
    null
}
```

**Comment by Ehesp** [comment]
Works, now I'm getting the error `null is not an object`. Since every child of `ViewPagerAndroid` should be a `View`, is this causing it?

I also cannot do:

```
{tab > 0 ?
    <View><Text>Hello</Text></View> :
    <View />
}
```
as it renders a blank page still.

**Comment by Ehesp** [comment]
@satya164 I think this is a bug...

**Comment by satya164** [comment]
cc @mkonicek

**Comment by satya164** [comment]
Have you tried the folloiwng?

```js
const pages = [ ... ];

<ViewPagerAndroid
    style={{ flex: 1 }}
    initialPage={0}
>
    {pages}
</ViewPagerAndroid>

```

Where pages array holds all the views.

**Comment by Ehesp** [comment]
Thanks ^, that works... something like:

```
const middle = (<View><Text>Middle</Text></View>);
const end = (<View><Text>End</Text></View>);
let pages = [middle, end];

if (tab > 0) {
    const start = (<View><Text>Start</Text></View>);
    pages.unshift(start);
}

<ViewPagerAndroid
    style={{ flex: 1 }}
    initialPage={0}
>
    {pages}
</ViewPagerAndroid>
```

So that's a work around for now, assuming the initial issue is a bug?

**Comment by satya164** [comment]
@Ehesp Not sure. If `props.children.length` returns 3 when it has null, then this is the expected behaviour.

cc @vjeux

**Comment by janicduplessis** [comment]
I already had a similar issue when looping through children in other components, ```React.Children.map``` used to modify style in ViewPagerAndroid.android.js can get called with null/undefined which is not handled at the moment. I'll submit a PR to fix this.
