### ISSUE TITLE
TouchableNativeFeedback.Ripple does not work on Android API 6.0

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#5203]
Hello

I've got a basic button, which implements `TouchableNativeFeedback`:

```
...
<TouchableNativeFeedback
                background={TouchableNativeFeedback.Ripple('#000000')}
...
```

On my emulator, this works absolutely fine on Android 5.1.1, on both development and a signed APK (color isn't #000000 here):

![workng-demo](https://cloud.githubusercontent.com/assets/842078/12207393/47e11aea-b63e-11e5-95a0-b22e61234856.gif)

This on the 6.0 emulator, and device, both test and signed APK only shows the initial background color and not the ripple:

![broken](https://cloud.githubusercontent.com/assets/842078/12207836/d4f54ce2-b640-11e5-9481-bbd5aaeb4a92.gif)

**Comment by Salakar** [comment]
+1 same here, thought I was going mad.

**Comment by satya164** [comment]
Strange. I just upgraded to Android 6.0 and ripples work just fine. Can you share the full code?

**Comment by Ehesp** [comment]
Full code of the render is below. It's like the ripple is trying to render right after the touch has been released. Fine on 5.1 again:

```
        return (
            <TouchableNativeFeedback
                background={TouchableNativeFeedback.Ripple('#000000')}
            >
                <View style={{ height: 50 }}>
                    <Text>
                        NORMAL
                    </Text>
                </View>
            </TouchableNativeFeedback>
        );
```
![broke](https://cloud.githubusercontent.com/assets/842078/12223128/cabf0e48-b7c6-11e5-978e-07c1d53876c3.gif)

The emulator & device (Nexus 6P) is on (with the same issue):

![image](https://cloud.githubusercontent.com/assets/842078/12223131/e512b0ce-b7c6-11e5-9e1d-ae18c39f4b9b.png)

**Comment by satya164** [comment]
I just tested this on the Gmail app, and seems the ripple effect only happens when you lift your finger. So this seems like a recent change in Marshmallow.

**Comment by Ehesp** [comment]
A recent change or Marshmallow in general? Not sure where to look in React Native to see where the issue is coming from to help fix it.

**Comment by satya164** [comment]
Marshmallow in general, since I also see the same behavior in Gmail app.

**Comment by Salakar** [comment]
@satya164 The default android 'Messenger' app does ripple though.

**Comment by Ehesp** [comment]
@satya164 If you go to the Messenger app, and then hold down on a convo, it fills the background with the darker color, and when you let go does a little ripple. This is exactly what is happening on "tap" with React Native.

**Comment by Ehesp** [comment]
@satya164 Do you think this is related? http://stackoverflow.com/questions/33054903/android-rippleforeground-bounded-mode-implementation

**Comment by satya164** [comment]
Seems to be related.

**Comment by jordangarside** [comment]
I have this same issue, the ripple is showing way below the touch point (sometimes it just won't show up at all).
It seems to happen when you have certain flex properties on containing Views.

I will make a demo sometime soon.

**Comment by bcalik** [comment]
Ripple effect is working on 6.0, the issue is ripple is misplaced if you press on child component, so you don't see it. See the issue below for videos and rnplay samples: https://github.com/facebook/react-native/issues/6139

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchablenativefeedbackripple-does-not-work-on-android-api-60

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
