### ISSUE TITLE
iOS: How to make a "drop down list"?

### ISSUE THREAD

**Issue by mbrochh** [facebook/react-native#5210]
On Android, I'm using https://www.npmjs.com/package/react-native-dropdown-android which works great.

On iOS I believe one uses a `UITextField` and sets the `inputView` value to a `UIPickerView`, but unfortunately the react-native `TextInput` doesn't have an `inputView` property.

We already have a `PickerIOS` component, it seems like a small step to somehow marry it to the `TextInput`component. I'm sure almost all apps have a drop down list somewhere, so this should be a solved problem?

Is there a best practice already that I am not aware of to solve this issue?

**Comment by tomauty** [comment]
I use `<ListView>` with a search bar. Search bar text change reduces the list.

**Comment by mbrochh** [comment]
That would be a great solution for lists with a lot of items, but for just quickly picking one of three options, I think having the PickerIOS in the Keyboard would be better.

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow

**Comment by wnr** [comment]
@mbrochh I'm in the exact same situation. Did you find any solution?
