### ISSUE TITLE
Getting Character offset from touch nativeEvent.locationX/Y

### ISSUE THREAD

**Issue by yapcheahshen** [facebook/react-native#5212]
I am trying to get the word beneath finger tip, currently I need to create text element for each character, which is quite expensive.
How to translate nativeEvent locationX/Y to character offset ? 
my goal is to implement one-touch dictionary checking feature when reading bunch of text.

demo https://rnplay.org/apps/3zd66g

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow
