### ISSUE TITLE
setState({value, 'a long long text') in ios multiline textInput won't wrap in multiline

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#5213]
If the text is too long for the textInput line, it won't be wrapped in multiline automaticly until you edit something.
For example setState({value, 'a long long long long long long long long long long text'), you will only see a long long long long ... if the lineView is not that long, not a muliline wrapping text.
This issue doesn't happen when set the initial state. 
And it only happens on ios. 
I check the code in TextInput.js. The android  &lt;AndroidTextInput&gt; support multiline but ios use two different view as &lt;RCTTextField&gt; and &lt;RCTTextView&gt;. It uses &lt;RCTTextView&gt; to implement multiline.
Maybe setting the text value on it directly doesn't  trigger the wrapping action. But I could not figure it out.

**Comment by narychen** [comment]
I finally figure out what's wrong.
In RCTTextView.m  
```objective-c
- (void)setText:(NSString *)text
{
  NSInteger eventLag = _nativeEventCount - _mostRecentEventCount;
  if (eventLag == 0 && ![text isEqualToString:_textView.text]) {
    UITextRange *selection = _textView.selectedTextRange;
    _textView.text = text;
    [self _setPlaceholderVisibility];
    _textView.selectedTextRange = selection; // maintain cursor position/selection - this is robust to out of bounds
    [self updateContentSize]; //  ---------------MISSING THIS-------------
  } else if (eventLag > RCTTextUpdateLagWarningThreshold) {
    RCTLogWarn(@"Native TextInput(%@) is %zd events ahead of JS - try to make your JS faster.", self.text, eventLag);
  }
}
```

**Comment by satya164** [comment]
@narychen Up for sending a PR?

**Comment by narychen** [comment]
@satya164 Just one line code, maybe the one who write this file could check for it.

**Comment by satya164** [comment]
@narychen A PR is welcome though :)

**Comment by narychen** [comment]
PR has been made.  https://github.com/facebook/react-native/pull/5247

**Comment by micro1226** [comment]
this bug happened again on version4.2.
this time setText function did not operated, instead doing `- (void)setTextStorage:(NSTextStorage *)textStorage`on RCTText.m
so, how to fix it?
