### ISSUE TITLE
[Idea: DeviceEventEmitter] Namespace device events

### ISSUE THREAD

**Issue by ide** [facebook/react-native#522]
Since the device event emitter is shared by every module in the app it might be a good idea to namespace the events. This could be part of the native API for sending events like:
```objc
[self.bridge.eventDispatcher sendDeviceEventWithNamespace:@"React"
  name:@"appStateDidChange"
  body:...]
```
which emits an event named "React.appStateDidChange".

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
