### ISSUE TITLE
Encounter warning: Module is not registered: "RCTNativeAppEventEmitter"

### ISSUE THREAD

**Issue by Yukaii** [facebook/react-native#5224]
![screen shot 2016-01-09 at 10 14 04 pm](https://cloud.githubusercontent.com/assets/4230968/12216797/de1a5c7a-b728-11e5-87b1-661b2d91a89b.png)

I use https://github.com/naoufal/react-native-safari-view/ this component, and safari view setup and run correctly, has somebody faced this warning?

Here's a post might be relevant.
* http://stackoverflow.com/questions/29424913/is-react-native-modules-sending-events-to-javascript-doc-correct

**Comment by rh389** [comment]
I'm seeing this occur (using 0.19) when the native side uses the `bridge.eventEmitter` to send an event, but the `RCTNativeAppEventEmitter` module has not been registered (is never used) on the javascript side. (Seems to be a legitimate use case to me that a provider sends events which the consumer doesn't have to listen for. )

Importing the NativeAppEventEmitter module **and using or at least mentioning it** on the JS side seems to do the trick for me. If you're not listening for any native events, you still need at minimum:
```
import { NativeAppEventEmiter } from 'react-native';
NativeAppEventEmitter;
```
The second line is hacky and shouldn't achieve anything, but without it the module is apparently not registered. (Maybe some kind of clean-up effort by the packager?)

I'd be interested to know whether there's a better solution for this currently - can the native side either ensure or query whether a module is registered?

**Comment by jsierles** [comment]
@Yukaii I can't reproduce this on React Native 0.21 and the latest version of that module.

@rh389 is this still happening for you on 0.21? I'm curious what use case exists for native emitting events without a listener? In general, this is only used in modules and they tend to implement both.

@tadeuzagallo perhaps you can comment?

**Comment by sebmarkbage** [comment]
I believe this was fixed over at https://github.com/facebook/react-native/issues/6227 about a week ago.

**Comment by jsierles** [comment]
@facebook-github-bot answered
