### ISSUE TITLE
v0.18.0-rc can't run on iphone4-ios 7.1

### ISSUE THREAD

**Issue by tinygipxy** [facebook/react-native#5227]
I got this error when try to run bare project of react native 0.18.0-rc on iphone 4:
[__NSConcreteURLComponents queryItems]: unrecognized selector sent to instance

**Comment by adamski** [comment]
I'm getting this issue also.
The culprit is line 594 in `RCTUtils.m`:
```
NSString *RCTGetURLQueryParam(NSURL *URL, NSString *param)
{
  RCTAssertParam(param);
  if (!URL) {
    return nil;
  }
  NSURLComponents *components = [NSURLComponents componentsWithURL:URL
                                           resolvingAgainstBaseURL:YES];
  for (NSURLQueryItem *item in components.queryItems.reverseObjectEnumerator) {  // <-- iOS 8 only
    if ([item.name isEqualToString:param]) {
      return item.value;
    }
  }
  return nil;
}
```

**Comment by nicklockwood** [comment]
This was fixed in https://github.com/facebook/react-native/commit/180fc06b7a54cd48a9ed7ace661cc4cdd262a689

I guess we need to make sure that makes it into 0.18 @mkonicek

**Comment by adamski** [comment]
Great, any timeframes for this? Are there pre-release versions we can use?

**Comment by nicklockwood** [comment]
@adamski if it's blocking you, you can just copy RCTUtils.m from master.

**Comment by mkonicek** [comment]
I've cherry-picked 180fc06 into 0.18.0 (and 0.18.1). @tinygipxy can you please upgrade to 0.18.1 and confirm it's fixed?

**Comment by mkonicek** [comment]
If it's fixed can you please close this issue?

**Comment by adamski** [comment]
I can confirm this issue is now fixed

**Comment by mkonicek** [comment]
Nice!
