### ISSUE TITLE
Can't build the getting started demo for Android on Linux

### ISSUE THREAD

**Issue by Shivang44** [facebook/react-native#5229]
Hi, I'm trying to just get started with React. I installed react-native-cli through npm, and made a new project. Then I ran "react-native run-android", but when gradle gets to the point where it installs the APK, it times out. Here is the error log:

http://pastebin.com/Q6HcJMC4

I'm fairly certain I have my device setup correctly (adb shows it as "device"), and I even increased the timeout as described here:

https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/FileWatcher/index.js#L16

It doesn't seem to help. 

Thanks

**Comment by satya164** [comment]
This is more likely an issue with adb rather than React Native. Seems that installing the apk timed out.

**Comment by Shivang44** [comment]
@satya164 Could you please elaborate on what the "issue with adb" could be? It shows the device as connected and USB debugging is enabled. I'm not sure what else could be wrong with adb.

Thanks

**Comment by satya164** [comment]
@Shivang44 Can you install apps using `adb install`? Because that's the step which seems to be failing. I'd say try upgrading/downgrading your adb version and gradle versions to see if it works.

**Comment by jsierles** [comment]
@facebook-github-bot no-reply
