### ISSUE TITLE
[Android WebView] No Fullscreen API Support

### ISSUE THREAD

**Issue by sdca** [facebook/react-native#5230]
YouTube embeds never show a fullscreen button, and buttons on this test page fail:

http://pearce.org.nz/fullscreen/

**Comment by avishayil** [comment]
+1 on this.

**Comment by Frulko** [comment]
+1

**Comment by Frulko** [comment]
Any answers ?

**Comment by TeodorKolev** [comment]
Is that a joke?

**Comment by stereodenis** [comment]
is this PR about issue? https://github.com/facebook/react-native/pull/6880

**Comment by satya164** [comment]
@stereodenis Nope. That PR was filed long after this issue was posted. If anyone has experience with WebView, and can send a PR to fix this, please do. A quick google search gives this - http://stackoverflow.com/questions/15768837/playing-html5-video-on-fullscreen-in-android-webview

**Comment by wcastand** [comment]
Hi,
i did some digging and found out that we 'only' need to implement two functions to provide the fullscreen on Android since the WebChromeClient is already implemented in the PR posted earlier #6880

From the android documentation, [link](https://developer.android.com/reference/android/webkit/WebView.html) : 
```
Full screen support
In order to support full screen — for video or other HTML content — 

you need to set a WebChromeClient and implement both 
onShowCustomView(View, WebChromeClient.CustomViewCallback)
and onHideCustomView(). 

If the implementation of either of these two methods is missing
then the web contents will not be allowed to enter full screen. 

Optionally you can implement getVideoLoadingProgressView() to customize
the View displayed whilst a video is loading.
```

I'm not a Java developper at all so i don't really know how to do this.

**Comment by satya164** [comment]
PRs are welcome for this.

**Comment by mangogogos** [comment]
Has anyone been working on this? Would love to have fullscreen support for videos playing in an Android WebView

**Comment by T-Spoon** [comment]
Submitted a PR for this: https://github.com/facebook/react-native/pull/10327

Getting some eyes on it would be good!

**Comment by DeanMW** [comment]
@T-Spoon please see #10327

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-webview-no-fullscreen-api-support

**Comment by Hauuguu** [comment]
Can we please re-open this? Having the same issue in 0.49.3.

**Comment by hramos** [comment]
@Hauuguu can you open a new issue and fill out the entire template?

You can also take a look at #10327 which attempts to fix this, but was closed due to lack of followup.
