### ISSUE TITLE
Module parse failed (for Portal)

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#5231]
```
node_modules/react-native/Libraries/Portal/Portal.js Line 15: Unexpected token :
You may need an appropriate loader to handle this file type.
| var View = require('View');
|
| var _portalRef: any;
|
| // Unique identifiers for modals.
```

What plugin for babel was used to transform this and support type hinting like this?

**Comment by satya164** [comment]
We don't support third party packagers. Please use stackoverflow for these kinds of questions instead.

https://github.com/facebook/react-native/blob/51d8ed92d5c491b1be945f4d86c6e583a77abe38/packager/react-packager/.babelrc

**Comment by niftylettuce** [comment]
Yeah, fixed this, sorry!  I'm using native packager now... check this out @satya164 https://github.com/niftylettuce/react-native-loading-spinner-overlay

**Comment by satya164** [comment]
Cool!
