### ISSUE TITLE
Error Screen Enchacment! (0.18.0-rc)

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#5234]
Hi,

Many errors are displayed on the error screen as if the dev server is not running. 
Maybe a better error message would be less confusing.

Thank You!

**Comment by DHidee66** [comment]
There was a bug in my redux actions apparently. Maybe another error status would be better.

**Comment by jaygarcia** [comment]
@DHidee66 , can you please post more information?  Are you saying that the issue is that errors are appearing if the dev server *is* running?

Please post stack trace/screenshots.

**Comment by satya164** [comment]
#5235

**Comment by DHidee66** [comment]
@jaygarcia  If there are bugs in the code then the JSX transformation stops at the last file (ex. 500/501) and the error page says that the dev server is not running. 
I haven't yet found a common theme throughout the bugs that cause this error page.
@satya164 It's not a server issue. The message that you put on the error page is related only to the dev server.

**Comment by satya164** [comment]
@DHidee66 There is a bug with the current version which doesn't show proper error messages. Master branch shows proper errors.

![screenshot_20160110-231356](https://cloud.githubusercontent.com/assets/1174278/12222942/147b0e14-b7f0-11e5-9424-5fd2cc1eeb8e.png)
