### ISSUE TITLE
Xcode build failed, hangs on building dependency graph

### ISSUE THREAD

**Issue by ferologics** [facebook/react-native#5237]
here's the [screenshot](https://www.dropbox.com/s/dz1g06gawr0rtnt/Screenshot%202016-01-10%2011.17.03.png?dl=0)

pastebin link to the Xcode error [message](http://pastebin.com/C441SxJa)

I recently switched machines, it might be me but this was a problem for past 2 days, can't figure out what's wrong at all ..

**Comment by christopherdro** [comment]
Looks like you missing a dependency.

` Unable to resolve module reactfire from /Users/master/Flow/loginView.js`.

**Comment by ferologics** [comment]
Yea, sorry about that looks like the problem resolved, I had some issues
with namings and the require() method always tried to go from./node-modules
whatever the path I specified to it.

Thanks ^^

On Sun, 10 Jan 2016 at 11:43 Christopher Dro <notifications@github.com>
wrote:

> Looks like you missing a dependency.
>
> Unable to resolve module reactfire from /Users/master/Flow/loginView.js.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native/issues/5237#issuecomment-170384458>
> .
>
-- 
Frantisek Hetes, iOS Developer, Makeschool student
*f.hetes@gmail.com <f.hetes@gmail.com> | @ferbini | makeschool.com
<http://makeschool.com>*

**Comment by jaygarcia** [comment]
@ferologics , please close this issue.
