### ISSUE TITLE
Is there a way to render a String into a JSX component in React Native?

### ISSUE THREAD

**Issue by ericnograles** [facebook/react-native#5240]
Hi guys,

Quick question -- I may have run into a use case where I need to render JSX dynamically with strings in RN.  I know in plain jane React, I could just use babel-core and do a `babel.transform`, but I was unclear if this approach would also work in RN?  More importantly, is such a thing even possible on RN?

Thanks!

Eric

**Comment by gre** [comment]
https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html

see how JSX turns into an object format `{type, props, ...}`? Maybe you can use that as your "dynamic" way of providing content. But JSX is not supported to be "parsed" at runtime and I don't think it will ever be, it's a temporary sugar to writing JavaScript.

also, I think [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) is more appropriate for questions

**Comment by ericnograles** [comment]
Thanks, @gre! And yes, duly noted, perhaps I should read the guidelines next time  :smile: I got some assistance with a solution on Discord, so closing this issue.

**Comment by my-love** [comment]
@ericnograles Could you tell me how did you achieve it?

**Comment by yray** [comment]
@ericnograles same here, need to know how to achieve it, or maybe you can provide us on your stackoverflow link

**Comment by KarthikeyanSekar93** [comment]
@ericnograles  am also stuck on this same type of task. please share your discord answer

**Comment by shukerullah** [comment]
@ericnograles could you tell me how you achieve it?

**Comment by yuriy-yarosh** [comment]
Well, you could use react-native-mock for testing purposes and render RN JSX components into a string via react-dom the same way.
