### ISSUE TITLE
Invalid directory /Users/node_modules/ReactPropTypes

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#5242]
I'm newbie starting react-native that trying [chart](https://github.com/onefold/react-native-chart/) 3rd part lib, but I find below error.

```
Unable to resolve module ReactPropTypes from /Users/jovi/AwesomeProject/node_modules/react-native-chart/Chart.ios.js: Invalid directory /Users/node_modules/ReactPropTypes
```

version `react-native-0.17` + `react-native-chart@0.0.4`

could anybody help me,  thanks..

**Comment by jaygarcia** [comment]
This is a proper post as an issue for the project itself as it does not seem to fully conform to the current patterns ^react native 0.15.0.

**Comment by ide** [comment]
@jaygarcia's point looks right to me too... the charting library shouldn't be doing this:
```
var PropTypes = require('ReactPropTypes');
var ReactNativeViewAttributes = require('ReactNativeViewAttributes');
var createReactNativeComponentClass = require('createReactNativeComponentClass');
var StyleSheet = require('StyleSheet');
var NativeMethodsMixin = require('NativeMethodsMixin');
var flattenStyle = require('flattenStyle');
var merge = require('merge');
```

**Comment by L-Jovi** [comment]
@jaygarcia @ide  thanks for your time,  maybe I'll choose another chart lib .. or try native exist project.

**Comment by ide** [comment]
You could also fix the project and send a PR or use a fork. Lots of options.

**Comment by L-Jovi** [comment]
I'll consider it, thanks.
