### ISSUE TITLE
[Text] How to specify default font family?

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#5243]
Is there any way to change default font family except change native code?
I don`t want to specify font family for every Text element,It would be a mess if I do so.

**Comment by magicismight** [comment]
resolved.

```
let oldRender = Text.prototype.render;
Text.prototype.render = function (...args) {
    let origin = oldRender.call(this, ...args);
    return cloneElement(origin, {
        style: [origin.props.style, styles.defaultFontFamily]
    });
};
```
override Text.prototype.render works for me.
It would be much better is there is an official way to resolve this

**Comment by pannz** [comment]
this will affect custom icon when you use icon font

**Comment by NelsonPetitos** [comment]
How to avoid this behavior then @pannz ?

**Comment by makovkastar** [comment]
@magicismight Thank you, your solution works. But wouldn't it be better to put `styles.defaultFontFamily` before `origin.props.style` so we can customize the default font attributes?

For example:

```
const styles = AppStyleSheet.create({
  defaultFontFamily: {
    fontFamily: "Proxima Nova",
    fontWeight: '300'
  },
  ...
  titleText: {
    fontWeight: 'bold' <- Customize the font weight.
  },
});
```
