### ISSUE TITLE
Issue with javaScriptEnabled in v0.18.0-rc

### ISSUE THREAD

**Issue by shidhincr** [facebook/react-native#5245]
I was trying to use the v0.18.0-rc, but found that it's not matching with the release notes.

The [commit](https://github.com/facebook/react-native/commit/6edcebef9c2a6f271ec7aaca97addcaf7545e48c) is there in master, but not picked up in the v0.18.0-rc tag.

If you try to use `javaScriptEnabled ` with v0.18.0-rc, it's not going to work. 

Also `javaScriptEnabled` is not a breaking change, as there is a fallback to `javaScriptEnabledAndroid` with deprecation message. So please update the release notes accordingly.

**Comment by christopherdro** [comment]
Hey there! 
Earlier it took some time to sync the docs with release canditiates but now documentation is available for multiple versions.
See: https://facebook.github.io/react-native/versions.html
