### ISSUE TITLE
When can RN support UWP APP?

### ISSUE THREAD

**Issue by yuanguozheng** [facebook/react-native#5248]
I think it's a good idea to support Microsoft UWP platform....

**Comment by Ehesp** [comment]
Yeah it probably won't be... I haven't seen anything regarding this so don't expect a timeframe.

**Comment by skevy** [comment]
Thanks of for the suggestion! We try to keep the issue tracker related to issues only...so if you could put things like this on Product Pains, that would be great!! https://productpains.com/product/react-native/

**Comment by evisong** [comment]
This is quite a forecasting ticket. https://blogs.windows.com/buildingapps/2016/04/13/react-native-on-the-universal-windows-platform/ , cool!

**Comment by yajiex** [comment]
Here you go: https://github.com/ReactWindows/react-native-windows
