### ISSUE TITLE
DrawerLayoutAndroid - TouchableOpacity still touchable on the scene when drawer open

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#5249]
This doesn't happen with `TouchableNativeFeedback`, but still seems to happen with `TouchableOpacity`.

The `pressIn` handler is being triggered in my scenes when the nav drawer is open. However it does also close the nav drawer. Here's an example.

1. I show the button performing a custom ripple like normal, and as expected.
2. I open the drawer, the button is still touchable in the background... and `onPressIn` is called, but not `onPressOut`.

![drawable-broke](https://cloud.githubusercontent.com/assets/842078/12233128/63a3c96a-b85c-11e5-8e27-9e1193a9d0e0.gif)

Code for the button is:

```
            <TouchableOpacity
                ref='container'
                activeOpacity={1}
                onPress={onPress}
                onLongPress={onLongPress}
                onPressIn={this._highlight}
                onPressOut={this._unHighlight}
            >
                <View
                    style={style || {}}
                    elevation={elevation ? elevation : 0}
                >
                    <Animated.View  style={[
                        styles.background, {
                            backgroundColor: rippling ? rippleColor : 'transparent',
                            opacity: fadeValue,
                        }
                    ]}/>
                    <Animated.View style={[
                        styles.ripple,
                        location &&
                            {
                                backgroundColor: rippleColor,
                                width: size,
                                height: size,
                                top: pageY - location.pageY - size / 2,
                                left: pageX - location.pageX - size / 2,
                                borderRadius: size / 2
                            },
                        {
                            transform: [{ scale: scaleValue }]
                        }]}
                    />
                    {children}
                </View>
            </TouchableOpacity>
```

**Comment by mangogogos** [comment]
You could hook into the onDrawerOpen and onDrawerClose methods to set a flag which you could read in the handler for the touchable in the meantime

**Comment by christopherdro** [comment]
@Ehesp Any chance you tried the above suggestion or have any updates on the issue?

**Comment by Ehesp** [comment]
Well the above response isn't really a fix, it would work fine but it's not
very elegant.

Unfortunately not, it needs to be fixed at the core.

**Comment by christopherdro** [comment]
@facebook-github-bot bug-fix

**Comment by geirman** [comment]
@facebook-github-bot bugfix

**Comment by geirman** [comment]
@facebook-github-bot label Help Wanted

**Comment by lacker** [comment]
It's not clear to me that this is a bug - it seems more like a case where the ideal solution is still inelegant. I'm going to close this issue, but I do think it sounds like something where we could improve. If someone has an idea for a PR to fix this then I encourage them to open a new "request for comment" type issue with their suggestions or just open a PR.
