### ISSUE TITLE
Application is not installing on the device

### ISSUE THREAD

**Issue by Hari70a** [facebook/react-native#5251]
It shows the following error:

Error:Watcher took too long time to load(NodeWatcher)
 at [object Object]._onTimeout (index.js:99:16)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by christopherdro** [comment]
Duplicate #2841

**Comment by mkonicek** [comment]
Closing as duplicate.

**Comment by mkonicek** [comment]
Thanks for finding the duplicate @christopherdro! Feel free to close issues like this one.
