### ISSUE TITLE
Unable to resolve module ReactUpdates

### ISSUE THREAD

**Issue by mhollweck** [facebook/react-native#5252]
After upgrading to 0.18.0-rc, I get the following erro:

[error][tid:main] Unable to resolve module ReactUpdates from /Users/***/node_modules/react-native/Libraries/react-native/react-native.js: Invalid directory /Users/node_modules/ReactUpdates

Anyone who got the same error?

**Comment by mhollweck** [comment]
Update: was a problem with the rn upgrade. Started the upgrade again and it worked. closing1

**Comment by Jonp713** [comment]
I restart the upgrade and this still happens..

**Comment by jose920405** [comment]
the `upgrade` is not the solution. The problem still happening

**Comment by tronin** [comment]
+1

**Comment by jose920405** [comment]
hi @tronin i fix this issue here 

http://stackoverflow.com/questions/40730787/unable-to-resolve-module-react-lib-reactupdates/40737409#40737409

**Comment by tronin** [comment]
thx, fixed too. 

fixed after installed shrinkwrap

**Comment by liuliangsir2016** [comment]
thx, @jose920405
