### ISSUE TITLE
resolvers appear to be completely incompatible /w npm3

### ISSUE THREAD

**Issue by lightsofapollo** [facebook/react-native#5256]
I tried on an existing app but I am pretty sure this is generic behavior... npm3 resolves to a very flat structure (i.e. react is in $APP/node_modules/react instead of $APP/node_modules/react-native/node_modules/react).

**Comment by tomauty** [comment]
Yeah, this is how npm3 works. For now I have a `postinstall` script that removes nested `react-native` dependencies for third-party libs, but have been letting them know that they should remove their `react-native` dependencies.
