### ISSUE TITLE
Cannot require node's util module

### ISSUE THREAD

**Issue by lazywei** [facebook/react-native#526]
I got this when trying requiring [fluxxor](https://github.com/BinaryMuse/fluxxor) on react native.

![image](https://cloud.githubusercontent.com/assets/2840571/6911814/6150bbdc-d798-11e4-9af9-d4862a691daf.png)

I thought `util` module should be part of node js and I don't need to install it manually.

**Comment by lazywei** [comment]
It seems this is duplicated of https://github.com/facebook/react-native/issues/375
So React Native doesn't (and won't) support node runtime, right?

**Comment by glenjamin** [comment]
These might help: https://github.com/substack/browserify-handbook#builtins

**Comment by amasad** [comment]
For now, it should work if you do `npm install util`. Let's track the issue here #447
