### ISSUE TITLE
borderRadius does not frame component

### ISSUE THREAD

**Issue by mikeborozdin** [facebook/react-native#5261]
The `borderRadius` style attribute doesn't change the border of a component correctly.

I would expect to see a green circle on the red background without any white space. Instead, I see this.

<img width="203" alt="screen shot 2016-01-11 at 23 59 13" src="https://cloud.githubusercontent.com/assets/1240215/12250636/670fa682-b8c0-11e5-9791-024c33907ce3.png">

```
class Healthie extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.button} />
      </View>
    );
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  button: {
    backgroundColor: 'green',
    borderRadius: 50,
    width: 100,
    height: 100,
    textAlign: 'center'
  }
});
```
react-native version: 0.17.0.

**Comment by tomauty** [comment]
I think you might want a container for the button with `backgroundColor: 'transparent'`

**Comment by mikeborozdin** [comment]
Hi @tomauty,

Thanks! I've just wrapped the `Text` inside a `View` and it worked! I applied the `borderRadius` property onto the `View` and didn't have to use `backgroundColor: 'transparent'` at all.

**Comment by tomauty** [comment]
:)
