### ISSUE TITLE
Can we expect MapView for Android soon?

### ISSUE THREAD

**Issue by nbastoWM** [facebook/react-native#5266]
I read sometime ago that MapView would come for Android with the latest RN 0.17 but that still didn't happen. Can we expect it soon? 
That would be awesome!

**Comment by christopherdro** [comment]
/cc @mkonicek Any ideas?

I recently came across this that looks very promising. https://github.com/lelandrichardson/react-native-mapview

**Comment by jaygarcia** [comment]
*crosses fingers*

**Comment by mkonicek** [comment]
Yes so that module is totally awesome and now we just need to decide whether to open source the internal one that we use in fb apps or bring that one it. See https://github.com/lelandrichardson/react-native-mapview/issues/2

**Comment by mkonicek** [comment]
Closing this as it's a question rather than a bug but we can keep discussing here.

**Comment by jiangqqlmj** [comment]
this is a good case,but we are in china~.i want to use baidumap~~~
