### ISSUE TITLE
layoutanimation on android not work

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5267]
layoutanimation on android not work

**Comment by magicismight** [comment]
```
UIManager.setLayoutAnimationEnabledExperimental &&   UIManager.setLayoutAnimationEnabledExperimental(true);
```
to enable LayoutAnimation on Android

**Comment by amiuhle** [comment]
This should be documented in `LayoutAnimation`.

**Comment by alvaromb** [comment]
+1 @amiuhle

**Comment by VaJoy** [comment]
This SHOULD be documented in `LayoutAnimation`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by JasonScopServ** [comment]
Where do I put this code?

**Comment by janmarsicek** [comment]
@JasonScopServ Hey I usually put it to the `constructor`:

```
constructor() {
    super();

    if (Platform.OS === 'android') {
      UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
    }
  }
```

**Comment by heldertb** [comment]
This should really be documented, broke my head over this.

**Comment by jasan-s** [comment]
@janmarsicek Super helpful.

**Comment by janmarsicek** [comment]
Hi @jasan-s! According the docs it should be ok to set the following flags like in the example in https://github.com/facebook/react-native/blob/master/docs/Animations.md#layoutanimation-api Sorry I don't have time to check if it works...

**Comment by UmeshAndroid** [comment]
One more thing to import **Platform**.
`import { Platform } from 'react-native';`

**Comment by atljoseph** [comment]
still not getting this to work with an actual animation, whether i set the flag in the app.js file or ini a component directly.

**Comment by ngohungphuc** [comment]
I manage to fix this issue 
https://github.com/ngohungphuc/Mobile-Development/issues/2

**Comment by vitto-moz** [comment]
Could anyone answer: 
If we use LayoutAnimation in several components - should we call
UIManager.setLayoutAnimationEnabledExperimental(true)
in each component, or we can just call it once?
Thanks
