### ISSUE TITLE
AlertIOS issues "Tried to display alert view but there is no application window. args"

### ISSUE THREAD

**Issue by jxintang** [facebook/react-native#5269]
here's my code below
```
componentDidMount(){
        var _this = this;
        TouchID.isSupported()
          .then(supported => {
              _this.setState({isTouchIDSupported:true})
              _this.authenticateTouchID();
          })
          .catch(error => {
              if (error.name == 'LAErrorTouchIDNotEnrolle') {
                setTimeout(()=>{
              AlertIOS.alert(
                      'yyyy',
                      'Touch0 ID无法工作。请通过[设置]-[Touch ID]登记您的指纹',
                      [
                        {text: '确定',type:'default'},
                      ],
                      'default'
                  )
                });
                  
              } 
          });
    }
render() {
        var {isTouchIDSupported} = this.state;
        var {navigator} = this.props;
        return (
            <View style={{width:width,height:height,backgroundColor:'#FFF'}}>
                <View style={{marginTop:30,marginBottom:30,alignItems:'center'}}>
                    <Text>LOGO位置</Text>
                </View>
                <View style={{marginTop:100,alignItems:'center'}}>
                    <TouchableOpacity onPress={this.goHome.bind(this)}>
                      <Text>进入首页</Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    }
```

when run the app on the device,an error accurs with the message"Tried to display alert view but there is no application window. args", I don't know why

**Comment by tomauty** [comment]
Is this happening in your root component?

**Comment by jxintang** [comment]
@tomauty  yes,but what should I do to fix this bug?

**Comment by tomauty** [comment]
Curious if this would still happen if you put this behavior in a nested component instead. I _believe_ RN is looking for a root view over which to draw.

**Comment by NikolayS** [comment]
Experiencing the same issue. Any news about it?
Haven't tried in "nested view" yet, but – if it's not working with root view, it's anyway a bug, right?

**Comment by besarthoxhaj** [comment]
Got the same problem, do someone know why that happens?

**Comment by anton-aleksandrov** [comment]
any news?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alertios-issues-tried-to-display-alert-view-but-there-is-no-application-window-args

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
