### ISSUE TITLE
how can i set DrawerLayoutAndroid lock mode to DrawerLayout.LOCK_MODE_LOCKED_CLOSED ?

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5270]
how can i set DrawerLayoutAndroid lock mode to DrawerLayout.LOCK_MODE_LOCKED_CLOSED ?

**Comment by aleki** [comment]
+1

**Comment by andybb** [comment]
I think I got this to work, will put up a pull request later.

**Comment by kalpeshbewakoof** [comment]
how to use DrawerLayout.LOCK_MODE_LOCKED_CLOSED in real project?
I want to show drawer for multiple pages except few.
So I have included drawer in my mainpage above navigator so I got the the drawer in all inner pages. But now I want to hide drawer on one inner page. How should I hide it using LOCK_MODE?

**Comment by RichardLindhout** [comment]
+1 same problem as @kalpeshbewakeof, looks like we can't change it dynamic. I use this with navigationexperimental and I only want this on the first page to be touchable.

**Comment by RichardLindhout** [comment]
Same problem as @kalpeshbewakoof . 

But there is a code. I'll try this out now

public void setDrawerLockMode(ReactDrawerLayout view, @Nullable String drawerLockMode) {
 +    if (drawerLockMode == null || "unlocked".equals(drawerLockMode)) {
 +      view.setDrawerLockMode(DrawerLayout.LOCK_MODE_UNLOCKED);
 +    } else if ("locked-closed".equals(drawerLockMode)) {
 +      view.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_CLOSED);
 +    } else if ("locked-open".equals(drawerLockMode)) {
 +      view.setDrawerLockMode(DrawerLayout.LOCK_MODE_LOCKED_OPEN);
 +    } else {
 +      throw new JSApplicationIllegalArgumentException("Unknown drawerLockMode " + drawerLockMode);
 +    }
 +  }

**Comment by RichardLindhout** [comment]
@kalpeshbewakoof Please comment on https://github.com/facebook/react-native/issues/9092 that you have the same issue. (if that's te case)
