### ISSUE TITLE
[Docs] Add YellowBox console.warn console.error

### ISSUE THREAD

**Issue by imton** [facebook/react-native#5271]
That'd have been really useful to know :)

**Comment by christopherdro** [comment]
I'm thinking this would fit best under [debugging](https://facebook.github.io/react-native/docs/debugging.html).


@imton Any chance you can put a PR together?

Another great addition to the debugging section would be to include the adb logcat command where.
`Run adb logcat *:S ReactNative:V ReactNativeJS:V in a terminal to see your app's logs`

**Comment by brentvatne** [comment]
Great points @christopherdro -- @imton that would be great if you could do the above :)
