### ISSUE TITLE
AlertIOS.prompt() default values are broken

### ISSUE THREAD

**Issue by corbt** [facebook/react-native#5273]
Currently when using `AlertIOS.prompt()` with a default prompt value, that value is applied as the prompt's message, not the default value as the docs indicate. It looks like this regression was introduced between 0.16 and 0.17.

## RN 0.16
<img width="280" alt="screen shot 2016-01-12 at 8 06 41 pm" src="https://cloud.githubusercontent.com/assets/176426/12275501/4a4c542a-b968-11e5-9faf-aeaa5f0907e8.png">

## RN 0.18-rc
<img width="283" alt="screen shot 2016-01-12 at 8 09 26 pm" src="https://cloud.githubusercontent.com/assets/176426/12275533/67f85e9c-b968-11e5-9046-1b2b21f7644a.png">

I'm planning on looking into this today or tomorrow.

**Comment by mkonicek** [comment]
Thanks @corbt!

**Comment by corbt** [comment]
Fixed in https://github.com/facebook/react-native/pull/5286
