### ISSUE TITLE
babel config of a dependency breaks build

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/react-native#5274]
I have a dependency that includes this Babel configuration in `package.json`:

```json
"babel": {
    "presets": [
      "es2015",
      "react"
    ]
  }
```

I have found that when this dependency is installed I get the following error (sometimes at runtime or sometimes at build):

<img width="358" alt="screen shot 2016-01-12 at 4 24 11 pm" src="https://cloud.githubusercontent.com/assets/284476/12277377/017f4014-b949-11e5-9d05-8f9c992bf79f.png">

If I remove the `babel` settings aforementioned this error does not occur. I think the opaque error message is due to https://github.com/facebook/react-native/issues/5191.

**Comment by satya164** [comment]
Related #4062 #5221

**Comment by jasonkuhrt** [comment]
Thanks.
