### ISSUE TITLE
onEndEditing is firing after onSubmitEditing 

### ISSUE THREAD

**Issue by scottwilson312** [facebook/react-native#5275]
Using 0.16 on Android.

I have a TextInput, OnSubmitEditing fires when I submit it. Then, I click somewhere on the screen and OnEndEditing fires. 

Not sure if this is intended behavior, but it seems unintuitive that OnEndEditing would fire after OnSubmitEditing has already fired and the keyboard has disappeared.

In other words, this happens:

1) User submits the textinput - onSubmitEditing fires, and the keyboard disappears. 
2) The user does nothing for 30 seconds while they stare at the screen
3) The user clicks anywhere on the screen, onEndEditing fires

**Comment by christopherdro** [comment]
@facebook-githb-bot stack-overflow
