### ISSUE TITLE
Any reference about the static bundle?

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#528]
The react-native cli automatically generates **index.os.js**, but I'm planning to design a universal app targeting both iOS and Android, so the entry point should be the same. By checking out the official examples, I found the **Movies** app did the trick, and in the **AppDelegate.m**,

```objc
[NSURL URLWithString:@"http://localhost:8081/Examples/Movies/MoviesApp.includeRequire.runModule.bundle"]
```

instead of 

```objc
[NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];
```

then I renamed **index.os.js** to **App.js** and made some modifications as below, hit the run, but it seems that the **App.bundle** couldn't be found.

```js
//App.js
AppRegistry.registerComponent('App', () => App);
module.exports = App;
```
```objc
//AppDelegate.m
jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/App.bundle"];
```

**Comment by glenjamin** [comment]
See #240

**Comment by amasad** [comment]
What do you get if you open http://localhost:8081/App.bundle in your browser?
