### ISSUE TITLE
Button Bind Issue! (0.18.0-rc)

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#5282]
Hi,

There is an issue when you try to bind two pieces of data to any button type
`<TouchableNativeFeedback onPress={this.buttonPress.bind(self, rowData)} ...>`
it passes on only the first one. The second parameter is either undefined or the button object.
On RN 0.17 it works fine.

Thank You!

**Comment by DHidee66** [comment]
The only way it works is this:
`<TouchableNativeFeedback onPress={() => this.buttonPress(self, rowData)} ..>`

**Comment by christopherdro** [comment]
@DHidee66 That's right, you have to call it with an anonymous function or else the code just automatically get executed when it loads. The reason why this is happening is because in your original code you are actually invoking that method by passing in your parameters `(self, rowData)`.

**Comment by jaygarcia** [comment]
@christopherdro `this.buttonPress` should not be executing.  It's bind member should be, which should be inherited by `Function.prototype.bind`;

Function.bind should return an anonymous, executable function, whose context is the first parameter (an object).  

```
var obj = { a : 1 };
var fn = function(param1) {
   console.log(this.a, param1);
}

var boundFn = fn.bind(obj, 'hello there');
boundFn();
```
Yields:
```
1 "hello there"
```

**Comment by DHidee66** [comment]
@christopherdro @jaygarcia Thank you for your help. Strange that it works in RN 0.17.
