### ISSUE TITLE
Improve Images Documentation

### ISSUE THREAD

**Issue by agolovenko** [facebook/react-native#5287]
I use a png image as a background on my views. Even if the view is nothing more than a few strings of text I notice a significant delay in displaying background image. 

After I switched the image source from 
    ```<Image style={{width: sWidth, height: sHeight}} source={require('../../img/main_background.png')}/>```
to 
    ```<Image style={{width: sWidth, height: sHeight}} source={{uri: 'main_background'}}/>```

and put the image into XCode's Image.xcassets I saw significant boost in loading speed. 

So here is the topic omitted in docs - what place is better to store image assets performance-wise? Seems like Xcode image assets are the better choice to load faster bigger images.

**Comment by ios122** [comment]
@agolovenko u help me!thanks!

**Comment by grabbou** [comment]
@agolovenko don't forget that in development mode assets are loaded from packager remotely, which means there is a delay. In production builds, they are all bundled just like Xcode assets. Can you check if you see any perf. differences in a non-Debug builds? (e.g. Release)

**Comment by lacker** [comment]
We have overhauled the docs on Images so I think this is a lot better now. I'm closing but if you have specific suggestions for more Image doc improvements feel free to open a new issue or a PR to improve it.
