### ISSUE TITLE
ReferenceError: can't find variable: _fbBatchedBridge

### ISSUE THREAD

**Issue by rkmax** [facebook/react-native#5289]
I just install 
- node 5.4
- npm@2
- react-native@0.18.0-rc

and  following the getting started from the documentation

after that run the project `react-native run-android` with my deviced attached and got this

![reactnative_error](https://cloud.githubusercontent.com/assets/395707/12304064/ad6338b0-b9fb-11e5-8ff6-99a824ee5737.png)

**Comment by AlejandroGnz** [comment]
after you run the project : 
-run on console react-native start
-reload js on device

**Comment by rkmax** [comment]
@AlejandroGnz I tried but still getting same error on device

![captura de pantalla de 2016-01-13 14-04-29](https://cloud.githubusercontent.com/assets/395707/12304606/5d64ccf4-b9fe-11e5-9c6d-87fbaccf0417.png)

**Comment by shercoder** [comment]
I am seeing the similar issue as well. I have tried it on my device and the emulator. To me it seems like some sort of environment issue. I have even tried going back to `RN 0.15.0` but I was getting the same error until yesterday and then all the sudden it switched to a different error (keep in mind I did not make any changes in my codebase that would cause the change of error message).

Here is what I started seeing now:
![screen shot 2016-01-12 at 4 51 52 pm](https://cloud.githubusercontent.com/assets/1681066/12304735/f3471cfe-b9e5-11e5-9c29-481340f5cca3.png)

**Comment by AlejandroGnz** [comment]
you has to set you ip on your app to realoadjs:
-display the menu app in your device and set the ip and port
![menu](https://cloud.githubusercontent.com/assets/14167720/12305034/e945b764-ba04-11e5-8123-9cb5b0ec13d0.png)
![devop](https://cloud.githubusercontent.com/assets/14167720/12305047/f84dc922-ba04-11e5-906b-7baad81fe718.png)
![ip](https://cloud.githubusercontent.com/assets/14167720/12305048/f8531198-ba04-11e5-9069-a20ba2b7bbfd.png)
-make sure you are in the same wifi network
you can get more info here:
https://facebook.github.io/react-native/docs/running-on-device-android.html#configure-your-app-to-connect-to-the-local-dev-server-via-wi-fi

**Comment by rkmax** [comment]
@AlejandroGnz thanks that works for me. I think would be a great idea link that configuration page to the getting started document

**Comment by lwansbrough** [comment]
@chirag04 Getting the same issue after moving from `0.18.0-rc` to `0.18.0`. I'm using the Android emulator. I closed everything, ran the emulator, waited for the homescreen. Then I ran `react-native run-android`. Waited for the app to deploy and got this message. I can see on my package server that the requests are being received. I checked the package URL and there is no error.

I've tried setting the my dev IP on the device to both `localhost:8081` and my local IP. I also ran `adb reverse tcp:8081 tcp:8081`. The device is online and everything. I've even tried uninstalling react-native and reinstalling. I also ran `react-native upgrade` just in case. Nothing worked.

**Comment by lwansbrough** [comment]
Just tried deleting my entire `node_modules` folder and rerunning npm install (all my version numbers are exact so this should work if everything is working the way it should be.) Still not working.

**Comment by lwansbrough** [comment]
![](https://i.imgur.com/rFMEqGH.png)

That's the relevant error that I was able to see after enabling Chrome debugging.

**Comment by lwansbrough** [comment]
This issue may be related to the problem outlined here: https://github.com/facebook/react-native/issues/4968
