### ISSUE TITLE
What components are coming?

### ISSUE THREAD

**Issue by SanderSpies** [facebook/react-native#53]
I'd like to implement an existing IOS component inside React Native, but would prefer to pick something that isn't already implemented by Facebook. Would be great if you guys could clarify the future plans of React Native a bit more, so we could also help out :-).

**Comment by potsypantsy** [comment]
@vjeux do you know if the CameraIOS component will be released anytime soon? I wanted to use the native camera but wasn't sure if I should implement something in the meanwhile or wait for the CameraIOS you mentioned. Thanks!

**Comment by vjeux** [comment]
We don't have any Camera implementation inside of Facebook and don't have any project lined up that needs it. Hopefully someone from the community will be able to build it :)

**Comment by potsypantsy** [comment]
@vjeux Thanks for the heads up!  In that case, maybe I should go ahead and build a component and share it :)

**Comment by sahrens** [comment]
We do have a camera component internally, but it's not longer used so is probably pretty crusty.

**Comment by schokocappucino** [comment]
If you're looking for ideas, I'd like to open a share dialog (UIActivityViewController) from js.

**Comment by danicomas** [comment]
+1 for CameraIOS

**Comment by brentvatne** [comment]
@ericvicenti - I like that! I assume that calling `subscribeTo` will add the subscription to some array that will then be removed upon unmount? Looking forward to seeing that released!

**Comment by vjeux** [comment]
Most of the components on this list have been exported, will close this one. Let's recreate an issue
