### ISSUE TITLE
if react-native support full CSS selector function,provide Dom API and like JQuery element，my project ReactMix is useless to keep going?

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#5303]
First , Thanks for ReactNative team provide a so greatful framework for all the web developer.
We met a lot of problem when use it, such as
1. only support inline style ,not support full CSS func
2. can`t find a Dom Element provide JQuery DOM API
3. can`t use on H5 driectly
... etc.
So , we build a translate layer on the react-native , called ReactMix(https://github.com/xueduany/react-mix), object to help react-native codes friendly to H5 JQuery developer, support CSS selector, and JQuery DOM API. But I still have a question, if facebook team decide to support CSS, and DOM, whether our project is worth to keep going?

**Comment by corbt** [comment]
I'm not on the internal team, but I don't believe that Facebook is currently working on building out support for CSS selectors, the javascript DOM API, etc.

I think what you're doing is the right approach for that type of large, experimental functionality -- build it out as a separate project on top of React Native, and if you find it's useful to you and enough other people, the team can make the decision at that point about whether to add that functionality to RN core. Good luck! :smiley:

**Comment by ide** [comment]
React Native's goal isn't to reimplement CSS and DOM. If you want that you should use a web view.

**Comment by xueduany** [comment]
Thank you,But webview`s fps performance is still waiting for imporve ,and do not have some native only function. Css selector and JQuery API is a very important gramma suger for a lot of web developer.
