### ISSUE TITLE
[0.18-rc] onlyChild must be passed a children with exactly one child

### ISSUE THREAD

**Issue by israelidanny** [facebook/react-native#5307]
Previous version worked just fine. Now suddenly after updating I get this error. 

I looked in the issues here and only saw something related to tab bars (which I'm not using).
![screen shot 2016-01-14 at 2 50 10 pm](https://cloud.githubusercontent.com/assets/1970424/12324824/35b5c016-bace-11e5-8fbf-2ef9eee9717a.png)

**Comment by israelidanny** [comment]
My bad, the error wasn't `react-native`'s fault, but rather a side effect of updating to the new `react-redux` (which can finally be done with 0.18), which has a breaking change where this:
```
<Provider store={store}>
  {() => <App />}
</Provider>
```

Turns into this:
```
<Provider store={store}>
  <App />
</Provider>
```

**Comment by krishbhattacharyya** [comment]
Hi, 
I am beginner in react native.
I am also getting this error.
Please have a look the code- 
export default class AwesomeProject extends Component { 
	render() {
	  const routes = [
	    {title: 'First Scene', index: 0},
	    {title: 'Second Scene', index: 1},
	  ];
	  return (
	    <Navigator
	      initialRoute={routes[0]}
	      initialRouteStack={routes}
	      renderScene={(route, navigator) =>
	        <TouchableHighlight onPress={() => {
	          if (route.index === 0) {
	            navigator.push(routes[1]);
	          } else {
	            navigator.pop();
	          }
	        }}>
	        <Text>Hello {route.title}!</Text>
	        </TouchableHighlight>
	      }
	      navigationBar={ <Navigator.NavigationBar routeMapper={{ 
	      	LeftButton: (route, navigator, index, navState) => 
	      		{ 
	      		  if (route.index === 0) 
				    { 
				    	return null; 
				    } 
				  else 
				    { 
				    	return ( 
				      		<TouchableHighlight onPress={() => navigator.pop()}> <Text>Back</Text> </TouchableHighlight> 
				      	); 
				    } 
				},
	      	RightButton: (route, navigator, index, navState) => 
	      		{ return (<Text>Done</Text>); }, 
	      	Title: (route, navigator, index, navState) => 
	      		{ return (<Text>Awesome Nav Bar</Text>); }, 
	      	}} 
	      	style={{backgroundColor: 'gray'}} />
	      }
	      style={{padding: 100}}
	    />
	  );
	}
}

When I am using this I got the error bellow I have share this---
else 
 { 
	return ( 
		<TouchableHighlight onPress={() => navigator.pop()}> <Text>Back</Text> </TouchableHighlight> 
		  ); 
  }

![1](https://cloud.githubusercontent.com/assets/10433734/16813388/db723e62-494e-11e6-8215-a87573275972.jpg)

Am I done anything wrong here?
