### ISSUE TITLE
Implementation of ART.Path.arcTo on Android Renders Incorrectly

### ISSUE THREAD

**Issue by hswolff** [facebook/react-native#5311]
I'm trying to dynamically draw an arc in my react-native application using ART (which is awesome btw).

What I've found is that the Android implementation of `arcTo` behaves widely different than the iOS implementation, with the same JS code powering it.

[I've created a test case for this issue that you can easily add to your application to see the differences.](https://gist.github.com/hswolff/1869bd0be5a9af931364)

Running the above code on iOS produces:
<img width="250" alt="ios-arcto" src="https://cloud.githubusercontent.com/assets/322576/12329366/18656900-baae-11e5-92fe-6d35f16c963e.png">

Running the above code on Android produces:
![android-arcto](https://cloud.githubusercontent.com/assets/322576/12329502/aa2b960c-baae-11e5-9625-51f2d96e5f23.png)

For curiosity's sake I changed line 46 from `arcTo` to `lineTo`.

That produced the following on iOS:
<img width="250" alt="ios-lineto" src="https://cloud.githubusercontent.com/assets/322576/12329401/3cc45356-baae-11e5-875e-3fc1de2938a1.png">

And the following on Android:
![android-lineto](https://cloud.githubusercontent.com/assets/322576/12329520/b9ed251a-baae-11e5-8dcd-c4b2294b1192.png)

I imagine the issue resets somewhere in here https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTShapeShadowNode.java#L228-L243 however would love some input.

**Comment by hswolff** [comment]
This is version of react 0.18.0-rc FYI.

**Comment by gadiel** [comment]
@hswolff can you describe how you managed to get ReactArt running on Android?
tried
"Tested in open source by adding a `import com.facebook.react.ARTPackage;` and `.addPackage(new ARTPackage())` to UIExplorerActivity.java, running"

no luck

**Comment by hswolff** [comment]
@gadiel that line isn't necessary, just be sure you're running at least 0.18.0-rc and it worked out of the box for me.

**Comment by rops** [comment]
+1

**Comment by ol2dd** [comment]
+1

**Comment by mehdichamouma** [comment]
Should this issue be closed by this PR ?
https://github.com/facebook/react-native/pull/7049

**Comment by doddys** [comment]
the problem still persists in RN 0.28

**Comment by robclouth** [comment]
And in RN 0.33

**Comment by lacker** [comment]
It seems like there are some different bugs being discussed here because https://github.com/facebook/react-native/pull/7049 fixed some but not all things. I think we should close this particular issue but if people are still running into ART + Android + arc problems it would be great to get new issues filed, ideally with rnplay.org links too. Thanks for helping out folks!
