### ISSUE TITLE
Can't get started with react-native app (ulimit)

### ISSUE THREAD

**Issue by AbrahamArun** [facebook/react-native#5314]
I have followed the same steps as mentioned in the  <strong>getting started</strong> page and I can't run the xcode project.

It throws the following error:

![screen shot 2016-01-14 at 10 24 35 pm](https://cloud.githubusercontent.com/assets/5391059/12330985/a95d2dbc-bb0d-11e5-940f-d2441a3a3cef.png)

Even after setting it to a higher limit '<strong>ulimit -n 4096</strong>', it does not seem to solve the issue. And the above is done in <strong>node version 5.2.0, react-native-cli 0.1.10 with watchman installed</strong>. Can someone tell me what could be wrong? I tried even in older versions of node such 4.0.0 and it seems to be the same case.

**Comment by AbrahamArun** [comment]
Yikes. Looks like '<strong>npm  start</strong>' was just the missing part, doing that solved my issue. Even though this is a common process for npm projects, I think this should be mentioned in the getting started docs. It is not very obvious for everyone.

**Comment by AbrahamArun** [comment]
This is a weird issue. For some reason ulimit -n 4096 in the setup_env.sh does not work in my mac.

**Comment by asaf** [comment]
@AbrahamArun I'm having the same issue, any reason for closing the issue?

ulimit in macos requires root privileges, I don't see any reason why this command should be executed during the setup env phase,

Thanks.

**Comment by bestander** [comment]
We are going to fix this in next release
