### ISSUE TITLE
Module code should be strict mode code

### ISSUE THREAD

**Issue by svkurowski** [facebook/react-native#5316]
According to the [standard](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code):
> Module code is always strict mode code.

React-Native enables the ES 2015 Modules Babel transformations (see [here](https://facebook.github.io/react-native/docs/javascript-environment.html#content)). However, modules in React Native don't have strict mode code by default.

To reproduce:
```bash
react-native init StrictModulesTest
cd StrictModulesTest
cat <<EOT > foo.js
export default function foo() {
delete Object.prototype;
}
EOT
```
Then insert into `index.ios.js` or `index.android.js`:

    import foo from './foo';
    foo();

and run the app.
Expected: Error `Unable to delete property.`.
Actual: App is showing as normal.

Now insert `"use strict";` at the beginning of `foo.js` and the error shows up.

Note that [babel-plugin-transform-es2015-modules-commonjs](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs) inserts the `"use strict";` automatically, so in some way React-Native must disable this behavior.

**Comment by ide** [comment]
I think this is because facebook has some modules that aren't compliant with strict mode. @martinbigio do you know if this is the reason strict mode is not enforced everywhere?

**Comment by skevy** [comment]
@svkurowski fyi - it's disabled specifically here: https://github.com/facebook/react-native/blob/master/packager/react-packager/.babelrc#L16

**Comment by svkurowski** [comment]
Thanks for the pointers! Maybe we should add this to the documentation (e.g. somewhere around [here](https://facebook.github.io/react-native/docs/javascript-environment.html#content). I spent some time trying to figure out why using [babel-plugin-transform-strict-mode](https://babeljs.io/docs/plugins/transform-strict-mode/) breaks my app (and also some time until I figured out that it was this plugin that broke it), I guess it's really that some of the modules aren't compliant with strict code.

**Comment by satya164** [comment]
If you enable strict mode, it'll show the `GLOBAL.Text` error.

cc @martinbigio

**Comment by corbt** [comment]
Yeah I played with enabling strict mode by default in the .babelrc a few months ago and ran into errors so I didn't pursue it. However, requiring 'use strict' is unexpected behavior using ES6 modules, so it should be documented at least or ideally turned on.

Is there a particular reason why strict-mode-in-modules can't be enabled? pinging @tadeuzagallo because it looks like he authored that line [in the babel 6 transition](https://github.com/facebook/react-native/commit/b48964717e123c2fd3e02bdad355a9dcf9ae80a5) (but I seem to remember 'use strict' being necessary before the transition to babel 6 as well).

**Comment by martinbigio** [comment]
Yeah, @ide is right, we have many internal modules which are not strict mode compatible. cc @davidaurelio

**Comment by janicduplessis** [comment]
I took a look at it and fixed the bugs that were cause by enabling strict mode. We can then enable strict mode by default in OSS when the babel config will be easy to change.

**Comment by ide** [comment]
@janicduplessis you're on fire!

**Comment by janicduplessis** [comment]
@ide :D

**Comment by DaleJefferson** [comment]
@janicduplessis It looks like strict mode has not been enabled yet, https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js#L28

Is there anything stopping us turning strict mode on?

**Comment by satya164** [comment]
@DaleJefferson since packager also transpiles files under `node_modules`, any library not written with strict mode breaks.

**Comment by teameh** [comment]
@satya164 so that makes it almost impossible to turn this on for all users right? But it's safe for individual users to turn it on by using the babel plugin if they don't rely on code that's not written with strict mode on right?
