### ISSUE TITLE
Documentation on creating a release

### ISSUE THREAD

**Issue by wski** [facebook/react-native#532]
I snooped around the issues as best I could and didn't find anything-- As far as I can tell right now react-native relies on having a development server to run; could we get some information on when we can expect to be able to have standalone applications? Even if it's far off it would be awesome to get a bit more guidance / heads up in the docs.

**Comment by vjeux** [comment]
Yup, we need to document this officially. In the meantime the instruction is in https://github.com/facebook/react-native/issues/240
