### ISSUE TITLE
React Native + jest + shallow rendering = unexpected token error

### ISSUE THREAD

**Issue by mikeborozdin** [facebook/react-native#5323]
I'm trying to test a React Native component using jest and shallow rendering.

However, calls to ShallowRenderer.render() results in an error

>SyntaxError: Unexpected token ... at eval (native) at Object.eval (components/list-conditions.js:1:244) at >Spec.eval (tests/components/list-conditions-test.js:14:48)

The test code is very simple, I don't even need to have an assert statement to get that error:

```
jest.dontMock('../../components/list-conditions.js');

const React = require('react');
const TestUtils = require('react-addons-test-utils');

const ListConditions = require('../../components/list-conditions.js');

describe('ListConditions', () => {

  it('renders buttons', () => {
    var renderer = TestUtils.createRenderer();
    renderer.render(<ListConditions conditions={['a', 'b']} />);
  });

});
```

**Comment by ide** [comment]
@cpojer is this something you are interested in supporting with React Native, and if so, is it on your roadmap or do you want help with it?

**Comment by cpojer** [comment]
@ide absolutely. Unfortunately I don't have much immediate time. Would you be willing to help me debug why some files aren't being transformed with react-native? @bartonhammond is running into this problem with https://github.com/bartonhammond/snowflake – cloning the repo and running the jest tests should show that some files aren't being transformed by babel even though they are passed through the preprocessor.

**Comment by ide** [comment]
@cpojer cool. This isn't a priority for us so I probably can't look into this myself either but I know that a lot of people want to testing components. Marked this as "Help Wanted" in case someone else is interested in helping investigate.

**Comment by lelandrichardson** [comment]
NOTE: I will likely be spending some time on this in near future in order to get https://github.com/airbnb/enzyme working smoothly with RN components

**Comment by cpojer** [comment]
@lelandrichardson we definitely want that too. Feel free to join us on discord: facebook.github.io/jest/support.html in the #jest channel :)

**Comment by brentvatne** [comment]
@lelandrichardson - amazing!

**Comment by mikeborozdin** [comment]
So, is unit testing with Jest not yet officially supported?

I've managed to get it to work with a combination of this [tutorial](http://www.schibsted.pl/2015/10/testing-react-native-components-with-jest/) and the [snowflake](https://github.com/bartonhammond/snowflake) starter kit.

**Comment by Thorbenandresen** [comment]
@mikeborozdin any code you could share? I can still not make it work with RN17/18 and the mentioned resources

**Comment by cpojer** [comment]
Thank you for your patience. We launched Jest 14.0 with experimental react-native support:

* [Blog Post](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
* [React-Native Tutorial](http://facebook.github.io/jest/docs/tutorial-react-native.html)

Please feel free to create new issues after trying out the new integration if any issues remain.
