### ISSUE TITLE
iOS app crashes after warning: unable to load source map: source code is unavailable

### ISSUE THREAD

**Issue by Matthew-C** [facebook/react-native#5326]
We host react-native in a navigation view controller and every time user navigate back react native component is discarded and create a new react native root view. 

After a couple of times we saw a warning:unable to load source map: source code is unavailable. and if we tap on buttons an RCTFatalException will be raised and app crashes.

My question is is there a way for our app to gracefully shut down react-native to avoid this?

**Comment by christopherdro** [comment]
@Matthew-C Any updates on this issue?

**Comment by lacker** [comment]
It looks like this issue is abandoned so I am going to close it. Please feel free to open a new issue if you have a bug with a way to reproduce it.
