### ISSUE TITLE
can we make TabBarIOS title bigger? 

### ISSUE THREAD

**Issue by kamyzd** [facebook/react-native#5329]
Help! I made a tabBar using TabBarIOS,but the title ..I can't find a way ti make it bigger 
![2016-01-15 3 52 57](https://cloud.githubusercontent.com/assets/12152855/12348283/b6099be8-bba0-11e5-94e3-f471636507b0.png)
how to ?

**Comment by brentvatne** [comment]
Hi there! Please post these types of questions to StackOverflow :) Thanks
