### ISSUE TITLE
cache js in webview

### ISSUE THREAD

**Issue by falltodis** [facebook/react-native#5334]
now,i write an app by react native,but it is hard for me to draw kinds of charts in the app  
so i used a webview to show the chart view,but so i found it is slow to load that,is that any way to cache the js lib and webview context locally ,so that when the app start, it need not to load js and the htmlcontext from server to save a lot of time ,thanks

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow

**Comment by aqnaruto** [comment]
same issue  https://github.com/facebook/react-native/pull/8578
