### ISSUE TITLE
delayPressOut throws an error/doesn't trigger onPressOut

### ISSUE THREAD

**Issue by Ehesp** [facebook/react-native#5337]
I'm on Android 5.1, and the following doesn't work with `TouchableWithoutFeedback`:

```
...
<TouchableWithoutFeedback
    delayPressOut={5000}
    onPressOut={() => { console.warn('Pressed') }}
>
...
```

`onPressOut` is never fired. If I remove `delayPressOut` it triggers instantly.

I can however cause an internal React Native error, if using it with `TouchableNativeFeedback`:

```
...
<TouchableNativeFeedback
    background={TouchableNativeFeedback.Ripple('#000000')}
    delayPressOut={5000}
    onPressOut={() => { console.warn('Pressed') }}
>
...
```

This again doesn't wait for 5 seconds, but instead instantly throws an error:

![image](https://cloud.githubusercontent.com/assets/842078/12357100/fa324f84-bb9d-11e5-9ead-dccf7c23c9f1.png)

I've no clue whether it's related, but Ripple doesn't work on Android 6: https://github.com/facebook/react-native/issues/5203

**Comment by avishayil** [comment]
+1 on this.
