### ISSUE TITLE
[HMR] Ensure Hot Loading is working on Android

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5338]
We've done quite many changes to HMR since @satya164 added the Hot Loading option to the dev menu. This task is to make sure Hot Loading works on a brand new project. Also, we need to gate the feature for now, we don't want to release up until we're sure it's stable.

**Comment by JohnyDays** [comment]
Using the latest v0.21.0-rc I can't seem to figure out how to enable HMR, should there be a dev menu option? 
I simply ran `react-native init` then `npm install --save react-native@0.21.0-rc`.

**Comment by satya164** [comment]
@JohnyDays For now you need to install from master - http://facebook.github.io/react-native/docs/android-setup.html#content

**Comment by JohnyDays** [comment]
Thanks, I'll give it a look and give some feedback :+1:

**Comment by satya164** [comment]
@JohnyDays 😄

**Comment by JohnyDays** [comment]
For anyone stuck in making it work, there is no need to install from master, here are the steps for a new project:

  1. `react-native init`
  2. `npm install --save react-native@0.21.0-rc`
  3. `react-native upgrade` (Choose yes for everything it asks)
  4. You're done! An option to enable hot reload should appear in the android dev menu

**Comment by satya164** [comment]
Oh! I thought @martinbigio removed it before the RC. Finally we have HMR for Android in a public release :tada:

**Comment by JohnyDays** [comment]
It seems to work perfectly, but everytime a change happens, this error pops up
![screenshot from 2016-02-24 07-27-10](https://cloud.githubusercontent.com/assets/4540763/13285585/7937724c-dac9-11e5-9890-17ddacea5cf9.jpg)
And it keeps stacking up at the bottom of the app, so if I save the file 5 times, it appears 5 times (consistently)

**Comment by JohnyDays** [comment]
Figured out the problem. The source maps are being requested from 
`http://localhost:8081/index.android.map?platform=android&runModule=false&entryModuleOnly=true&hot=true`, 
it should be requested from the remote url/ip (e.g 192.168.1.183). Is this packager related, or android-specific? At the end of the generated HMR patch, the sourcemaps are referenced as 
`//# sourceMappingURL=/index.android.map?platform=android&dev=true&hot=true`

**Comment by martinbigio** [comment]
Hmm though @mkonicek removed it. It wasn't intended to have the option visible on the menu yet

**Comment by martinbigio** [comment]
Ohh, this is 0.21RC. We'll remove the option from the menu there. If everything goes well we should be able to open the feature on 0.22 :)

**Comment by martinbigio** [comment]
@JohnyDays Thanks so much for working on adding support for having multiple clients!. Please let us know if you find any bug or if there're other feature requests you think we should implement. We'll need help on testing this, so the more people use it before it's open the better :)

**Comment by JohnyDays** [comment]
I'm having some trouble getting the android version to compile my java code changes consistently.
I have react-native cloned into the node_modules folder, and when I run `react-native run-android` it doesn't seem to pick up on them, regardless of me changing branches or whatever I do. 
I tried doing `cd android && ./gradlew clean` but had the same result. Is there something obvious I'm missing?

**Comment by satya164** [comment]
@JohnyDays follow the instructions here - http://facebook.github.io/react-native/docs/android-setup.html#content

**Comment by satya164** [comment]
Symlinking won't work, coz watchman, which RN uses to watch files, doesn't support symlinks.

**Comment by JohnyDays** [comment]
Yeah I have my machine (arch-linux) setup with the sdk, and gradle daemon, all the build tools and genymotion.
The builds always succeed, my problem seems to be related to the file system changes not being picked up. 
I started a new project and it works perfectly again, it's probably a linux-interop problem.

**Comment by JohnyDays** [comment]
Shaping up! Still get those warnings though :cry: 

![optimized](https://cloud.githubusercontent.com/assets/4540763/13338354/12f34e8c-dbde-11e5-9026-8e487d757483.gif)

PS: I just spent way more time than I should trying to make that gif under 10mb, sorry for the terrible colors

**Comment by JohnyDays** [comment]
@martinbigio Just a heads up, i reimplemented the changes to attachHMRServer.js from b2b41da37f70c2b0da381ad86a701443f13b27f4 and b2b41da37f70c2b0da381ad86a701443f13b27f4,  so there wouldn't be any problems with conflicts. I should be able to open the PR today, cheers :beer:

**Comment by martinbigio** [comment]
Wow, this indeed will be helpful for a lot of people!.

I recently added support for redux stores and modules that export pure functions and modified this file (https://github.com/facebook/react-native/commit/436db67126f1e64d1889c2d084b77c98c8d63f8d). Most likely you'll have to rebase.

**Comment by NishanthShankar** [comment]
Just updated to rn-0.22 and the warnings(as shown by @JohnyDays) are still there

**Comment by th0th** [comment]
Yep, I am also getting this on genymotion with react-native 0.22. I also tried setting debug server host & port to point to my development machine, no luck.

![screen shot 2016-03-22 at 09 43 58](https://cloud.githubusercontent.com/assets/698079/13945006/b1d4f774-f012-11e5-95e9-c262ef7a051d.png)

**Comment by JohnyDays** [comment]
@martinbigio I did some digging on this when i was working on multiple clients, and it appears to be related to source maps. e.g even if you are requesting from a remote ip, the source maps still point to localhost.

**Comment by martinbigio** [comment]
Genymotion sets a special ip to access localhost  from the simulator, however to fetch the sourcemaps we're using localhost...

**Comment by martinbigio** [comment]
The problem is that JS lacks of this logic: https://github.com/facebook/react-native/blob/1f94a00785a472d135d121958d5c2fa73ec94103/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevServerHelper.java#L158-L160

cc @mkonicek

**Comment by JohnyDays** [comment]
Shouldn't it be the java sending this information to the packager? Such as genymotion=true or localhost=10.0.3.2 in the url

**Comment by martinbigio** [comment]
Yup, we're going to expose this on the `AndroidConstants` native module. @satya164 will send a PR in a couple of hours :)

**Comment by suhaotian** [comment]
same error as above still

react-native version: 
➜  AwesomeReactNative git:(master) ✗ react-native -v     
react-native-cli: 0.2.0
react-native: 0.22.2
