### ISSUE TITLE
[HMR] Improve Hot Loading gating

### ISSUE THREAD

**Issue by martinbigio** [facebook/react-native#5339]
Hot Loading is currently disabled by default until we're confident enough it's good to go. On iOS, users have to enable it by tweaking the method `hotLoadingEnabled` on `RCTDevMenu.m`. @satya164 might know about how to enable this on Android.

Ideally the feature should be enabled way easier (i.e.: by implementing a method on `AppDelegate.m` for instance). I don't know much about Android to make a proposal.

**Comment by satya164** [comment]
I'll look into how to do this on Android.

**Comment by martinbigio** [comment]
@javache any pointer on how to enable this on `AppDelegate` given the current gating code on `RCTDevMenu`/`RCTBridgeDelegate`? :)

**Comment by javache** [comment]
Our default app delegate template (https://github.com/facebook/react-native/blob/master/local-cli/generator-ios/templates/app/AppDelegate.m) doesn't really make use of the bridge's delegate methods. We could change this to create a RCTBridge first, but you'd lose the advantage of the simple RCTRootView API.

Anyone who has a slightly more complicated setup should be able to simply element the new delegate method.

**Comment by satya164** [comment]
I was thinking, on Android, we can have the following to enable experimental features,

```
protected List<Integer> getEnabledExperiments() {
    return Array<Integer>.asList(
        Experiments.HOT_MODULE_REPLACEMENT
        Experiments.SOME_OTHER_CRAZY_EXPERIMENT);
}
```

What do you think about the approach before I implement it?

**Comment by satya164** [comment]
cc @mkonicek

**Comment by satya164** [comment]
So another approach would be to allow people enable experiments from dev settings UI as @mkonicek suggested.

**Comment by satya164** [comment]
I'm not sure about having it in the UI, because it's very easy to find and enable, and then we can get bug reports even if it's not ready. Adding it only in code means that only people who know what they are doing enable experimental things, and we get better quality bug reports.

**Comment by martinbigio** [comment]
Yeah, that makes sense

**Comment by mkonicek** [comment]
@martinbigio When I start the packager in a new RN app I see it listens on "/hot" by default. Is that intentional?

![screen shot 2016-01-21 at 12 46 50 pm](https://cloud.githubusercontent.com/assets/346214/12483632/0b1bc64a-c04e-11e5-86f3-d6950cf4430f.png)

**Comment by satya164** [comment]
@mkonicek It'll only work when the url has `hot=true`. By default it's `hot=false` in Android. In iOS it seems to be turned on by default.

**Comment by mkonicek** [comment]
Cool, get it. Don't think it should be enabled by default on iOS though, should it?

**Comment by satya164** [comment]
@mkonicek Yes, it shouldn't. @martinbigio can confirm :)

**Comment by martinbigio** [comment]
The feature is disabled but if a user would modify `RCTDevMenu` to return `YES` on `hotLoadingAvailable`, the feature will not only become visible on the menu but enabled by default. Will fix that today

**Comment by JohnyDays** [comment]
Hey, is there any guidelines on testing the feature for android? I'd love to give some feedback on it, but can't seem to figure out how to enable it. 
People in e018aa31 seem to be asking for it as well. Cheers :+1:

**Comment by satya164** [comment]
@JohnyDays For now you can install from master. There will be an option to enable it in the dev menu.

**Comment by jsierles** [comment]
Now HMR is enabled in 0.22.0, is this issue still relevant?

**Comment by satya164** [comment]
No, let's close it.
