### ISSUE TITLE
UISegmentedControl support

### ISSUE THREAD

**Issue by clayallsopp** [facebook/react-native#534]
Hey there, any thoughts on `UISegmentedControl` support?

I suppose it would look like this:

```
<SegmentedControlIOS
  values={["One", "Two"]}
  selectedValue={}
  momentary={false}
  onValueChange={() =>}
  tintColor={}
  // TODO: how to handle image items?
/>
```

or this better left to an add-on/plugin sort of thing?

**Comment by clayallsopp** [comment]
I started working on a diff, seems pretty doable (if the project wants it).

is there precedent/example of how to handle default sizing of an element that usually sizes itself? The segmented control usually sizes its width to fit its items, plus whatever offsets you set (but it can be overriden), but it seems like some default styles (like a switch) hard code the width

Thanks!

**Comment by joshaber** [comment]
>it seems like some default styles (like a switch) hard code the width

Indeed: https://github.com/facebook/react-native/blob/af9f0972b63167912696e59eaecc58fb840147f0/Libraries/Components/SwitchIOS/SwitchIOS.ios.js#L112-113

**Comment by vjeux** [comment]
Internally, we reimplemented the segmented control in pure js. We found that it was easier than to wrap the native implementation.

**Comment by malkomalko** [comment]
I found this post http://qiita.com/laiso/items/5c5ef9158a37726d109d.  It's not in english but you should be able to tell what's going on.
