### ISSUE TITLE
Change unselected tab colour in TabBariOS

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#5350]
There doesn't seem to be an option to set the colour for the unselected tab in the TabBarIOS. I've set up the background colour and the colour for the selected tab but it just leaves the unselected tab in grey which looks really strange right now.

**Comment by brentvatne** [comment]
Hi there! Please post questions like this to StackOverflow in the future :)

AFAIK UITabBar does not provide any way to do this aside from changing your barTintColor. If you'd like more control, you might want to give this library a try: https://github.com/exponentjs/react-native-tab-navigator - as an added bonus it's pure JS so it works on iOS and Android, and you can change whatever you like.

**Comment by hasen6** [comment]
I assumed this is a genuine issue so don't see why you're asking me to post this in StackOverflow. How can it be possible to change the background colour, the selected tab colour but not the unselected tab? Clearly a problem that needs to be fixed.

**Comment by brentvatne** [comment]
@hasen6 - AFAIK this is not supported in the underlying iOS library, UITabBar, so we cannot support it :P
