### ISSUE TITLE
Add Buck as a build option 

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/react-native#5351]
My understanding is that Facebook uses Buck internally, it would be great if external developers had an example Buck configuration for React Native.

https://buckbuild.com

**Comment by brentvatne** [comment]
@mkonicek is looking into this soon

**Comment by mkonicek** [comment]
Yes we've started working on this internally.

**Comment by respectTheCode** [comment]
I added this to product pains as I am also very interested in using buck with react native projects.

https://productpains.com/post/react-native/add-buck-as-a-build-option/

**Comment by mkonicek** [comment]
We've added Buck files to the repo started running unit tests for React Native itself:
https://circleci.com/gh/facebook/react-native/tree/master

All of this is for building React Native itself.

We haven't done any work on supporting Buck in React Native apps and won't have time to look into it very soon. If someone had bandwidth to do that check out this SO question: http://stackoverflow.com/questions/34997158/how-can-i-use-buck-to-build-react-native-apps-for-both-ios-and-android

I'll close this issue as it's more of a discussion /feature request than a bug. We can continue discussing on Product Pains though.

**Comment by lyahdav** [comment]
I just got the basics of this working on iOS: http://stackoverflow.com/a/38966896/62

**Comment by lingz** [comment]
Would love to see a working android example

**Comment by fungilation** [comment]
If buck > gradle for Android build times (substantially?), shouldn't RN make a complete switch from gradle to buck? Especially since buck is from Facebook as well?
