### ISSUE TITLE
Pass configuration parameters to javascript when build/develop app

### ISSUE THREAD

**Issue by maksimr** [facebook/react-native#5353]
For example in our application we use backendUrl, which developers can configure themselves. But in production it will be permanent.
It will be nice have something like `react-native start --initial-props="backendUrl: 'foo'"`

I dont found any options to pass build/start react app parameters which I can use in js
I found [issue](https://github.com/facebook/react-native/issues/746) about appParams.initialProps seems it's very close what I want

**Comment by brentvatne** [comment]
You're welcome to write a patch for this :) A simple way to do it would be to wrap the react-native start command with your own script that adds your flags to a js file that is required in your root component. Otherwise I'd suggest creating a ProductPains issue :)

**Comment by maksimr** [comment]
@brentvatne thanks

> A simple way to do it would be to wrap the react-native start command with your own script that adds your flags to a js file that is required in your root component.

If I have understood you right you suggest write flag to file, and then require it in <main>.js(root component). Looks like workaround.
i think it's common case when we want pass some parameters to js from command line or from process environment. I will try make path

**Comment by brentvatne** [comment]
@maksimr - Yeah it's definitely a workaround, I haven't needed this yet but yeah awesome looking forward to your PR!

**Comment by pedro** [comment]
fwiw I've been using [react-native-config](https://github.com/luggg/react-native-config) to configure my apps – might be helpful next time you want to bring a configuration value to js.

**Comment by maksimr** [comment]
@pedro thx

**Comment by simonbuchan** [comment]
IOS has `NSProcessInfo.processInfo().arguments` and `NSUserDefaults.standardUserDefaults()` and android has `InstrumentationRegistry.getArguments()`. I think it's worth react-native exposing these for e.g. screenshot generation, since building a different app is another point of failure and involves quite a bit of platform-specific work (that I've just done!) to make that work cleanly.
