### ISSUE TITLE
Naming collision from react-native and react in fbjs\lib\CSSCore.js

### ISSUE THREAD

**Issue by jjchula** [facebook/react-native#5357]
run "react-native start" for android and got this error

Error building DependencyGraph:
 Error: Naming collision detected: D:\rx2\node_modules\react-native\node_modules\fbjs\lib\CSSCore.js collides with D:\rx2\node_modules\react\node_modules\fbjs\lib\CSSCore.js

Details
package dependencies 
    "react-native": "^0.18.0-rc",
	    "react": "^0.14.6",
    "react-dom": "^0.14.6"
  
Environment
npm 2.14.15
react-native-cli 0.1.10
Windows 10

**Comment by tomauty** [comment]
Try removing the `react` and `react-dom` dependencies, if you can. RN ships with it. Are you using npm3?

**Comment by josebalius** [comment]
Getting the same thing when upgrading from 0.17 -  0.18.0-rc

**Comment by satya164** [comment]
Try deleting your `node_modules` folder and run `npm install` again.

**Comment by brentvatne** [comment]
Make sure you're using npm3 also!

**Comment by jjchula** [comment]
react v0.14.x has "fbjs" devDependency.
While v0.14 to v0.17 of react-native have no "fbjs" dependencies, v0.18.0-rc does.
So, with npm2, if the RN project also includes package with react peerDependency, Bang!

**Comment by josebalius** [comment]
Yeah, what @jjchula said. After deleting the `node_modules` folder, and run `npm install` again, i get:

```
[1:58:54 PM] <END>   Building (deprecated) Asset Map (1220ms)
Error building DependencyGraph:
 Error: Naming collision detected: /Users/josebalius/Sites/Ravedish/node_modules/react/node_modules/fbjs/lib/warning.js collides with /Users/josebalius/Sites/Ravedish/node_modules/react-native/node_modules/fbjs/lib/warning.js
```

**Comment by josebalius** [comment]
I tried it with npm@3 and ran into this issue: https://github.com/facebook/react-native/issues/4296 however https://github.com/facebook/react-native/issues/4296#issuecomment-164078248 seems to fix it for me.

**Comment by masom** [comment]
Latest RN ( 0.18 release ) seems to fix naming collisions.

**Comment by masom** [comment]
Fixed by forcing `npm install -g npm@2`.

**Comment by brentvatne** [comment]
Moving discussion to #5357
