### ISSUE TITLE
0.18-rc BabelHelper Error

### ISSUE THREAD

**Issue by alexcurtis** [facebook/react-native#5369]
Trying to use another library like 'Frisbee' or 'Axios' returns an error:
![screen shot 2016-01-17 at 21 15 06](https://cloud.githubusercontent.com/assets/379213/12380014/6a48ca9c-bd5f-11e5-877a-a8cafbf40d29.png)

.babelrc:

```javascript
{
  "presets": ["stage-0", "es2015"],
  "retainLines": true,
  "compact": true,
  "comments": false,
  "sourceMaps": false
}
```

Packages:

"babel-preset-es2015": "^6.3.13",
"babel-preset-stage-0": "^6.3.13"

**Comment by satya164** [comment]
Not sure how conflicts in babelrc are managed. Note that React Native packager has its own babel configuration, which doesn't use the `es2015` preset, but a set of plugins with different options (for example strict mode is not enabled). A better approach to use custom `.babelrc` is to extend it.

**Comment by alexcurtis** [comment]
@satya164 Yep, I've tried extending the .babelrc file, but its not fixing the issue.

**Comment by satya164** [comment]
Can you post your full .babelrc?

**Comment by alexcurtis** [comment]
@satya164 Sure.

```
{
   "extends": "react-native/packager/react-packager/.babelrc",
  "presets": ["es2015", "stage-0"],
  "retainLines": true,
  "compact": true,
  "comments": false,
  "sourceMaps": false
}
```

**Comment by alexcurtis** [comment]
Seems ok after upgrading to 0.18 release. Closing.
