### ISSUE TITLE
[HMR] Hot reloading doesn't work with ES6 classes

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#5371]
The following works,

```js
import React from 'react-native';

const {
    View,
    Text
} = React;

export default React.createClass({
    render() {
        return <View><Text>Hello world!</Text></View>;
    }
});
```

But this doesn't,

```js
import React from 'react-native';

const {
    View,
    Text
} = React;

export default class MyApp extends React.Component {
    render() {
        return <View><Text>Hello world!</Text></View>;
    }
}
```

It shows the following warning,

![iphone 5 - iphone 5 - ios 9 2 13c75 simulator today at 4 31 53 am](https://cloud.githubusercontent.com/assets/1174278/12380821/d9ce226c-bda1-11e5-8e66-13b82f7f0746.png)

cc @gaearon @martinbigio

**Comment by RyGuyM** [comment]
I am getting the same issue.

**Comment by martinbigio** [comment]
looking..

**Comment by gaearon** [comment]
The underlying tech should support this:

https://github.com/gaearon/babel-plugin-react-transform/tree/master/test/fixtures/code-class-extends-react-component
https://github.com/gaearon/react-proxy/blob/d9c971338e08b6ad453933c36a496ffa020b2f8a/test/instance-method.js#L7-L71

**Comment by martinbigio** [comment]
@gaearon, the problem is that `babel-plugin-react-transform` runs on non ES6 code so the heuristic fails. Here's an example of the code it runs on:

```
Object.defineProperty(exports,\"__esModule\",{value:true});var _reactNative=require('react-native/Libraries/react-native/react-native.js');var _reactNative2=babelHelpers.interopRequireDefault(_reactNative);var \n\n\n\n\n\n\n\nView=_reactNative2.default.View;var \nText=_reactNative2.default.Text;var \n\n\nMasonExample=(function(_React$Component){babelHelpers.inherits(MasonExample,_React$Component);function MasonExample(){babelHelpers.classCallCheck(this,MasonExample);return babelHelpers.possibleConstructorReturn(this,Object.getPrototypeOf(MasonExample).apply(this,arguments));}babelHelpers.createClass(MasonExample,[{key:'render',value:function render()\n{\nreturn _reactNative2.default.createElement(View,null,_reactNative2.default.createElement(Text,null,'Hello world!'));}}]);return MasonExample;})(_reactNative2.default.Component);exports.default = MasonExample;\n\n\n\nmodule.exports = MasonExample;
````

**Comment by gaearon** [comment]
Oh, then it makes sense. It was supposed to run on ES6 code. :-)

**Comment by martinbigio** [comment]
This is another example why I think you're right on why we need a better long term strategy other than this type of heuristics :).

Would it be possible to tweak `babel-plugin-react-transform`  to account for transformed code as well?

I think this is the major blocker for people in OSS.

**Comment by martinbigio** [comment]
I'm moving HMR to the external transformer, this should work very soon :)
