### ISSUE TITLE
[TabBarIOS] AccessibilityLabel not getting added to TabBarIOS.Item

### ISSUE THREAD

**Issue by janmonschke** [facebook/react-native#5379]
When adding an `accessibilityLabel` prop to `TabBarIOS.Item` it is not added to the rendered View:

![screen shot 2016-01-18 at 15 31 14](https://cloud.githubusercontent.com/assets/68591/12393875/c82f674e-bdf8-11e5-98c3-dce55d5ee1cb.png)

![screen shot 2016-01-18 at 15 15 38](https://cloud.githubusercontent.com/assets/68591/12393877/c96ff5b0-bdf8-11e5-9f2c-a5500e716c5e.png)

**Comment by ryankask** [comment]
`TabBarIOS.Item`is backed by `RCTTabBarItem` which as you've noticed doesn't expose `accessibilityLabel` (https://github.com/facebook/react-native/blob/0.31-stable/React/Views/RCTTabBarItemManager.m). 

It should be straightforward to add. Is this still an issue for you? Are you able to submit a PR?

I suspect there are other native views that have the same issue but I guess they can be fixed as needed.
