### ISSUE TITLE
Can I config these warningss closed as default ?

### ISSUE THREAD

**Issue by Hkmu** [facebook/react-native#5380]
![2016-01-19 1 52 21 am](https://cloud.githubusercontent.com/assets/3169251/12398604/b9d6d522-be4f-11e5-81c8-a448eb096bea.png)

**Comment by ide** [comment]
You can use either:
```
console.disableYellowBox = true;
// or
console.ignoredYellowBox = ['Warning:'];
```

Read the code here for the docs: https://github.com/facebook/react-native/blob/ae2f556c71ff1e83690ca082604c30cac574f340/Libraries/ReactIOS/YellowBox.js
