### ISSUE TITLE
React Native init not running

### ISSUE THREAD

**Issue by neilwilliams36** [facebook/react-native#5388]
I following the instructions on the website to get a react native app up and running.

I get the following messages
Genymotion Andriod simulator  Reference Error: can't find variable _fbBatchedBridge
IOS simulator  Unable to execute JS call: _fbBatchedBridge is undefined
React Package Manager synchonization failed

React native version 0.18.0
React native cli 0.1.10
Node 4.2.4

Mac Os X Yosemite
XCode Version 7.2

**Comment by chirag04** [comment]
dupe https://github.com/facebook/react-native/issues/4952 & https://github.com/facebook/react-native/issues/5289

**Comment by TheeSweeney** [comment]
I had the exact same error and figured out after some debugging that it was caused by my having a multi-line comment, ie one denoted by /*  and */. 

I changed my comment so that I just had // at the start of each line and it worked fine

**Comment by pickhardt** [comment]
@TheeSweeney Why would a multiline comment cause problems?
