### ISSUE TITLE
Naming collision: flux/node_modules/fbjs/flow/include/ErrorUtils.js

### ISSUE THREAD

**Issue by sethx** [facebook/react-native#5390]
Hello,

After upgrading to 0.18.0 and rebuilding my project from scratch (Deleting all files, generating a new project via react-native init, redowloading only source from version control, recreating the node_modules folder from scratch) i get this: 

Error building DependencyGraph:
 Error: Naming collision detected: /Users/d/Desktop/project/node_modules/flux/node_modules/fbjs/flow/include/ErrorUtils.js collides with /Users/d/Desktop/project/node_modules/react-native/Libraries/Utilities/ErrorUtils.js

My environment:
npm 3.5.1
node v4.1.1
lastest react-native-cli tools
OSX

My package.json's dependencies:
    "fbemitter": "^2.0.0",
    "flux": "^2.1.1",
    "react-native": "0.18.0",
    "react-native-swipeout": "^2.0.11",
    "react-mixin": "^3.0.0",
    "gb-native-router": "^0.6.0",
    "react-native-item-cell": "^1.3.0",
    "react-native-linear-gradient": "v1.3.0"

**Comment by chirag04** [comment]
@sethx npm3 is not officially recommended yet. Till then can you try removing fbjs from any nested dep and installing it under ``./node_modules/fbjs``

**Comment by lesniakania** [comment]
I had similar issue, for me helped upgrading to Node 5.0.2 and npm 3.3.12

**Comment by jasonmerino** [comment]
I had a similar issue with naming collisions in fbjs, but in different files. The steps that @chirag04 posted fixed it for me.

**Comment by adriansprod** [comment]
I had a fbjs camelize.js clash but the @chirag04 instructions plus restarting xcode and the iOS simulator to completely clear caches

**Comment by dabit3** [comment]
@chirag04 fix worked for me as well, thanks!

**Comment by sampurcell93** [comment]
This fix worked great, thank you.

**Comment by joewood** [comment]
The fix didn't work for me. The **fbjs** in npm is different to the ones used by react-native. The version of **lib/invariant.js** in the package now doesn't have `providesModule invariant` - this is causing build failures. If you install **fbjs@0.6.0** this solves the issue.

**Comment by alex-mcleod** [comment]
As an extension to the answer by @chirag04, you can add a npm post install script with this line to automatically take care of the problem whenever `npm install` is run:

`find ./node_modules -name "fbjs" -type d -prune -exec sh -c 'if [ {} != "./node_modules/fbjs" ]; then rm -rf {};fi' \;`

**Comment by joewood** [comment]
I found it easier to just tell the packager to ignore all versions of fbjs other than the one you install. So, install your version of fbjs (I found v.0.6 to only work):
```
npm install fbjs@0.6.0
```
And then create a **rn-cli.config.js** file in your root. This worked for me:
```javascript
var blacklist= require("react-native/packager/blacklist");
var config = {
    getBlacklistRE(platform) {
        return blacklist(platform,[/MYAPPNAME.+\/node_modules\/fbjs.*/]);
    }
}
module.exports = config;
```
Replacing MYAPPNAME with your app's directory name (remember to escape out any regex chars, like`-`). All this is doing is adding to the package blacklist regex pattern. The `.+` ensures that there must be more than one character between the root dir and the node_modules.

**Comment by jihopark** [comment]
@joewood's solution worked for me. thanks!

**Comment by BigPun86** [comment]
@chirag04 solution worked for me (Node v5.5.0 & npm 3.3.12 & RN18)

**Comment by ghamaide** [comment]
I'm having the same issue and after doing the steeps above I have this error...
`Error: Naming collision detected: /Users/gregoirehamaide/Documents/NeedlIOS/node_modules/fbjs/flow/include/warning.js collides with /Users/gregoirehamaide/Documents/NeedlIOS/node_modules/fbjs/lib/warning.js`

Any thoughts ?

**Comment by joewood** [comment]
@ghamaide which version of fbjs did you install? This error looks like a conflict within fbjs and its local flow install. Try fbjs@0.6.0

**Comment by arianitu** [comment]
@joewood What exactly is MYAPPNAME? Is this the name in package.json?

**Comment by joewood** [comment]
Just the root directory of your app. The blacklist logic in the packager is matching the full pathname, so it includes your root dir.

**Comment by arianitu** [comment]
That seems to fix the conflict issue when the packager is running, but I get errors when my app actually runs. The error I get is:

```Unable to resolve module invariant from /Users/auka/Development/personal/secret/client/node_modules/react-native/Libraries/ReactIOS/NativeMethodsMixin.js: Invalid directory /Users/node_modules/invariant```

I have installed fbjs@0.6.0, ```cat /Users/auka/Development/personal/secret/client/node_modules/fbjs/package.json``` returns 0.60.

I'm using npm version 2.14.7 and node v4.2.0 and react-native 0.19.0

If I do npm install invariant, I end up getting:
```Unable to resolve module keyMirror from /Users/auka/Development/personal/secret/client/node_modules/react-native/Libraries/Utilities/MessageQueue.js: Invalid directory /Users/node_modules/keyMirror```

 I haven't found a way to fix the conflicts between fbjs in flux and react-native, got any other ideas?

**Comment by arianitu** [comment]
@joewood what version of NPM are you using?

**Comment by joewood** [comment]
I'm on npm 2.14.16, node 4.2.3 and RN 0.18.1
Can you check that your local **fbjs** is providing `invariant`? What does this produce:
```
grep "providesModule invariant" node_modules/fbjs/**/*.js
```

You may need to package with a `--resetCache` and clear down the packager temp files.

**Comment by ambarc** [comment]
I'm getting an error similar to @ghamaide, but with the flux library instead of fbjs. I'm seeing conflicts arise from within the same package.

> Error: Naming collision detected: node_modules/flux/node_modules/fbjs/lib/getActiveElement.js collides with node_modules/flux/node_modules/fbjs/flow/include/getActiveElement.js

node_modules only has one flux folder and no other instances of other flux-es deeper down.

**Comment by digitalmaster** [comment]
@joewood Thanks.. worked for me!

**Comment by Durgaprasad-Budhwani** [comment]
@alex-mcleod solution worked for me. Thanks

**Comment by andreacab** [comment]
Neither of the provided solutions worked for me.

I am on npm 3.3.12 and node 5.3.0

`grep "providesModule invariant" node_modules/fbjs/**/*.js` returns 
`node_modules/fbjs/lib/invariant.js: * @providesModule invariant`

error is `Failed to build DependencyGraph: Naming collision detected: /Users/KAB/Desktop/Development/snofolio2/src/main/webapp/node_modules/flux/node_modules/fbjs/lib/TouchEventUtils.js collides with /Users/KAB/Desktop/Development/snofolio2/src/main/webapp/node_modules/fbjs/lib/TouchEventUtils.js`

Any ideas ?
Thanks

**Comment by pedrodevoto** [comment]
@joewood the blacklist worked for me!

**Comment by SamTharani** [comment]
I also faced this issue but in different file

Failed to build DependencyGraph: Naming collision detected: /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/fbjs/flow/include/fetch.js collides with /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/react-native/Libraries/Fetch/fetch.js
Error: Naming collision detected: /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/fbjs/flow/include/fetch.js collides with /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/react-native/Libraries/Fetch/fetch.js

**Comment by liesislukas** [comment]
having this issue with RN v0.20

**Comment by sethx** [comment]
My solution is always to delete the:
node_modules/flux/node_modules/fbjs folder . Works time after time.

**Comment by BigPun86** [comment]
+1 to @sethx. Works for me as well. It is weird that i always get this issue as soon as i install anything with npm. After that just delete the mentioned folder and everything should be fine

**Comment by liesislukas** [comment]
@BigPun86 you have to folder appears again because npm installs it again. That's why it's bad solution. You should not touch anything inside node_modules folder.

**Comment by cherniv** [comment]
I have a mix of this bug and flux and #4968 , and my workaround for now is:
```
npm uninstall --save flux
rm -rf node_modules && npm install
npm install --save flux
rm -rf node_modules/fbemitter/package.json
rm -rf node_modules/flux/node_modules/fbjs/
 rm -rf node_modules/flux/package.json 
```

**Comment by futurefeeling** [comment]
@joewood 's solutions worked

**Comment by digitalmaster** [comment]
tried a million things.. installing `npm install fbjs@0.6.0` finally did it

**Comment by rclai** [comment]
Solution that worked for me as of 0.21.0:

```
rm -rf node_modules
npm i
npm i fbjs@0.6.0
find ./node_modules -name "fbjs" -type d -prune -exec sh -c 'if [ {} != "./node_modules/fbjs" ]; then rm -rf {};fi' \;
rm -fr $TMPDIR/react-*
watchman watch-del-all
npm start --reset-cache
```

**Comment by YashYash** [comment]
@chirag04 && @joewood all i can say is thank you
