### ISSUE TITLE
Using CSS to draw triangle under Android

### ISSUE THREAD

**Issue by Nyte7** [facebook/react-native#5396]
I can't seem to draw triangles using the common CSS trick:

    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderBottomWidth: 20,
    borderTopWidth: 0,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: 'red',
    borderTopColor: 'transparent',
    alignItems: 'center'

Code produces rectangles but works on the web.

**Comment by christopherdro** [comment]
@Nyte7 I believe there is a issue with transparent borders on Android. See. #3652

**Comment by trave7er** [comment]
There was a PR addressed to this issue: https://github.com/facebook/react-native/pull/5911

**Comment by christopherdro** [comment]
Added via https://github.com/facebook/react-native/commit/a6a4389bf4a581de5adfe0e5dda4aa4f70438dfc
