### ISSUE TITLE
[Android]ReactInstanceManager singleton question

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#5398]
New version 0.18, `ReactInstanceManager` in `ReactActivity` not a singleton. But [Sharing a ReactInstance across multiple Activities / Fragments in your app](https://facebook.github.io/react-native/docs/embedded-app-android.html#sharing-a-reactinstance-across-multiple-activities-fragments-in-your-app) said `ReactInstanceManager` should be a singleton. If `ReactInstanceManager` not a singleton, we can get multiple `bundle` file, can we?

**Comment by Richard-Cao** [comment]
cc@satya164

**Comment by satya164** [comment]
You can override the `createReactInstanceManager` method of `ReactActivity` to provide your own instance, and use it for other activities.
