### ISSUE TITLE
How to separate js bundle

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#5399]
How to separate js bundle to frameworkBundle and appBundle?

js bundle is more 500k+, but business code is less then 10%

**Comment by Richard-Cao** [comment]
@satya164

**Comment by Creemli** [comment]
Wow, I just wanna fix this issue, and have tried https://github.com/mjohnston/react-native-webpack-server/ but failed.

Also I tried to get a dev version bundle and copy the framework code as framework.jsbundle, but when I package the business code, I cannot analysis the correct dependencies.

Looking forward this solutions~~~~

**Comment by Creemli** [comment]
@Richard-Cao  IOS also have this issue~~

**Comment by Richard-Cao** [comment]
@Creemli Looking forward……

**Comment by Creemli** [comment]
@Richard-Cao  Help to remove the [Android] tag and then more people can search this issue.

**Comment by Richard-Cao** [comment]
@Creemli ok

**Comment by corbt** [comment]
What's the purpose of splitting the bundle? Is it just to make incremental app updates lighter weight, or is there some runtime goal you're trying to accomplish?

**Comment by Richard-Cao** [comment]
both @corbt

**Comment by corbt** [comment]
To help me understand the scope of this, what are the use cases for this beyond just making lighter-weight app updates (which I get)?

**Comment by Creemli** [comment]
@corbt  Yeah, this can make user download less code when updating.
And if we can separate them, we maybe not have to bundle the whole codes, we can combine any business project with the framework code, it's lighter, I think.

**Comment by satya164** [comment]
I think @martinbigio was looking into this.

**Comment by martinbigio** [comment]
Yeah, we were looking into this mostly to help on TTI but decided to pursue another approach, namely `unbundling`. To make code downloading faster it's not actually necessary to have multiple bundles but to use a "more clever" protocol (i.e.: one that could send diffs only).

**Comment by hufeng** [comment]
@martinbigio  cool

**Comment by corbt** [comment]
If the main use case for this is just to have smaller updates, then I don't think bundle-splitting is the best solution. There should just be some library that manages updating the JS bundle file using versioned diffs. Such a solution would perform strictly better than bundle-splitting in the size of the updates it would need to send, and would also require less user intervention (in deciding where to split the bundle) to get right.

This would probably make more sense in something like [Code Push](https://github.com/Microsoft/react-native-code-push) than in React Native core.

**Comment by jkrems** [comment]
Another possible use is to lazy load parts of a (bigger) app at runtime to reduce startup time. Or is that unlikely to make a difference?

**Comment by dmendis** [comment]
I can give an example of what is being talked about here. 

I have a tabbed UI app that already has a bunch of native code already written (iOS and Android). React Native tabs exist side by side with other webview and native tabs. For this scenario, I am having to load all of the app code (core + tab 1 + tab 2 + tab 3) for each tab. Splitting the bundle would mean that: 

- the app kicks off tabs faster (TTI?) 
- some functionality that is rarely used can be directly loaded from a server without having to be pre-cached all the time
- updating a tab doesn't mean I have to send few megs down the network each time (I understand some diffing protocol was suggested up in the thread)

Also, what is `unbundling`?

**Comment by dickeylth** [comment]
ref #570

**Comment by Richard-Cao** [comment]
any  solution?

**Comment by sheldonhan** [comment]
any updates?

**Comment by Creemli** [comment]
Ah, try this: https://github.com/ctripcorp/moles-packer

**Comment by christineRR** [comment]
any progress?

**Comment by markzhai** [comment]
looking forward to updates

**Comment by cangyue0322** [comment]
Looking forward...and...what is unbundling？

**Comment by hzy00** [comment]
@Creemli  moles-packer only resolve the propblem separate js bundle, but how to load them in native module?

**Comment by mc-zone** [comment]
Hi @martinbigio, @corbt,

Our guys have been develop APPs with RN Integration for a long time. And we think bundle-splitting is also usefull in these scenarios (maybe not limited to Integration).

- **Decrease initial time (Run base codes previously)**
    If we could split some initial and definition codes to a ***base.jsbundle*** and run it in JSContext previously before users really enter React Native partition, it can decrease user's waiting time .

- **Update partially**
    Just like @Creemli said. If we just use a lock version RN(or update infrequently) , the most of changes and updates is about our business codes. We can also separate some framework code (i.e. React, RN Components, APIs, and even with some other framework) into a base bundle, but business codes in business bundle. So we can fetch business bundle standalone from network and get smaller size with download to hot update. Even without diff it's not too bad. I mean, maybe it's easier to implement than integrate a diff algorithm to the entire work flow.


- **Share common modules between multiple bundle**
    If we had the ***base.jsbundle*** like the above mentioned, we also can make multiple bundle share it as a common library (it's Just like DllPlugin usecase in webpack). Suppose we have two `ReactRootView` in our App, currently we should bundle out two ***jsbundle*** files both independent and overall with base codes, it includes many duplicated. 


## Let me generalize my opinion through this picture:
(In order to save space, I omit the `--platform`, `.ios`, `.android` here)

![image](https://cloud.githubusercontent.com/assets/4403937/19918580/6cc11c7a-a107-11e6-8d05-4683ad48798a.png)


This simple way seems like the DllPlugin in webpack:

1. **Compile-time**

    Build ***base.jsbundle***. Meanwhile records it's dependecies list and save it, for example,  named by ***base.manifest.json*** . 

    Build ***index1.jsbundle*** with the ***base.manifest.json*** passed through `cli`. When resolve modules, use their id from ***base.manifest.json*** and skip their definition if they has recorded in the manifest. So a clear business bundle has done! 

    Build antoher business bundle like the above (We can set a prefix to module id to prevent override).

1. **Run-time**

    Run ***base.jsbundle*** in JSContext at a good time (e.g. Native App launch done, enter to a parent Activity/Controller ). 

    Run ***index1.jsbundle*** when user click/open and will enter to this React Native partition.

    Run ***index2.jsbundle***  or other when user will enter to another React Native partition.

    Update business bundle from CDN if needed.

How do you think ? 😄

**Comment by njafei** [comment]
any updates?

**Comment by njafei** [comment]
android can try unbundle. this will separate mian.jsbundle into pieces of js files。

**Comment by jimzhao2012** [comment]
@njafei unbundle is not a good design, too many small files in output bundles.
it's very easy to split main.jsbundle to base.bundle.js and business.bundle.js, but you need modify the native code for RN to load different parts.

**Comment by Richard-Cao** [comment]
@mc-zone Amazing!

**Comment by ckitterl** [comment]
@jimzhao2012  I don't is a good idea to modify RN code.　Mybe could eval business.bundle.js at base.bundle.js?

**Comment by ronniegong** [comment]
@mc-zone can you explain how to 【run _base.jsbundle_ in JSContext at a good time】,don't get it, thanks

**Comment by yoution** [comment]
I hava package react-native code using webpack,https://github.com/yoution/rn-pack; and split code using commonChunk plugin,alse can fix module id in chunk; but I can not know how to load the splited bundle

**Comment by jsdario** [comment]
@jimzhao2012 is there any resource to look deeper into it?
Also, how could we use and pack with `unbundle`? I can produce the unbundle files, but I don't know yet how to install and run the `unbundle` result and I don't find many resources on how to do it.

**Comment by freemanon** [comment]
For those who wants to try out unbundle, there's a PR documenting it:
https://github.com/facebook/react-native/pull/15317/files

**Comment by JasonHao123** [comment]
I'm working on an existing app rewrite, to separate js bundles and hot reload are two important feature for me to investigate, reasons are:
1. We are running agile approach, so would like delivery our artifact for each sprint, but deliver through app store/google play too often definitely is not good for commercial app. So we would like to deliver major version by store, minor version by hot deploy.
2. splitting bundle is because inside the app, there are different modules developed under different project, and some function is not used quite often, for example help & service. to have separate bundle will reduce the dependency and decrease project risk, since we can deliver and replace modules separately 

Beyond that, we are also interested in bundle encryption/decryption, and file patching, which make is more useful for commercial app.

**Comment by zfha** [comment]
+1 mark

**Comment by punksta** [comment]
Also that can speed up ci/server-side builds. Most of builds has same versions of libs, only code of app changes. We can `--reset-cache` for app bundle only. 

For example: we have project with 1200 npm packages. android ci build takes about 3m, ios 5. 80% of build time takes building of bunde.js

Also we can bundle it with two package processes to speed up.

**Comment by jsdario** [comment]
Would this be the equivalent to [webpack DDL plugin](http://engineering.invisionapp.com/post/optimizing-webpack/)? I made the [following question](https://stackoverflow.com/questions/46192585/is-the-bundler-faster-if-code-splitting-is-enabled) in stackoverflow about the unbundle speed for rebuilds and I am interested in finding a guide to follow the same strategy for react-native.

Maybe it won't be possible for code-push updates or faster app initialization, but I am interested in improving the DX.

**Comment by virtuallyjeff** [comment]
I never saw a resolution of this issue.  it's a very important question and a valuable use-case.  unbundling is not a solution and not the same thing as splitting the framework from app.  is anyone working on this?

**Comment by skizzo** [comment]
Was anybody able to use unbundling in combination with CodePush?
