### ISSUE TITLE
ListView sticky headers are offset when RefreshControl is active

### ISSUE THREAD

**Issue by samuelkraft** [facebook/react-native#5405]
When using a ListView with "renderSectionHeader" together with RefreshControl the sticky headers will be offset during refreshing. To reproduce pull down to refresh and then scroll back up before the refresh finishes. This is an issue on both 0.17 (onRefreshStart) and 0.18 (RefreshControl).
Gif:
![stickyheaderrefresh](https://cloud.githubusercontent.com/assets/2223418/12416901/8de73448-bea4-11e5-87c6-102f31d809ec.gif)

**Comment by janicduplessis** [comment]
Thanks for reporting this, I just submitted a PR to fix it!

**Comment by samuelkraft** [comment]
Thanks! Let's hope for a merge soon :+1:

**Comment by janicduplessis** [comment]
There you go :)

**Comment by samuelkraft** [comment]
Yay! 🎉

**Comment by tomauty** [comment]
I think this regressed somewhere along the way.

**Comment by pfeiffer** [comment]
Yup, this is still present in 0.34

**Comment by idris** [comment]
@janicduplessis should this issue be re-opened?  Or is there a new issue somewhere?

**Comment by schultka** [comment]
Still present in 0.38

**Comment by krailler** [comment]
Same issue in 0.40 :/

**Comment by catarinasoliveira** [comment]
Same problem in 0.42.0 :/

**Comment by putuyoga** [comment]
same problem here
