### ISSUE TITLE
fresco-0.8.1.aar  NOT FOUND

### ISSUE THREAD

**Issue by captainblue2013** [facebook/react-native#5407]
I try to run-android but catch error

Could not get resource 'https://jcenter.bintray.com/com/facebook/fresco/fresco/0.8.1/fresco-0.8.1.aar'

And I found that there is not 0.8.1  in   https://jcenter.bintray.com/com/facebook/fresco/fresco/

**Comment by ide** [comment]
@balazsbalazs could you or one of your teammates publish 0.8.1 if it is supposed to be on jcenter?

**Comment by balazsbalazs** [comment]
Yeah, we're not supporting jcenter officially. I'm going to upload them manually and we're adding jcenter support for our scripts.

**Comment by captainblue2013** [comment]
@balazsbalazs How can i build my project with fresco-0.8.0 ?

**Comment by bestander** [comment]
Closing this as it is not a RN issue.
Please continue at https://github.com/facebook/fresco
