### ISSUE TITLE
Text textAlign 'justify' error

### ISSUE THREAD

**Issue by L3V147H4N** [facebook/react-native#5408]
textAlign: 'justify', brings up the "Error while updating property 'textAlign' of a view managed by: RCTText. on Android.

**Comment by vitalets** [comment]
also got this

**Comment by dagobertrenouf** [comment]
For now I'm doing `textAlign: (Platform.OS === 'ios') ? 'justify' : 'left'`.
Would be nice if it was automatic or better, if we found a way to implement justify in Android (is that even close to doable?)

**Comment by PuYart** [comment]
i also meet this.
