### ISSUE TITLE
can not run Examples

### ISSUE THREAD

**Issue by blueken** [facebook/react-native#541]
I open the  /users/bob/documents/learn/github/react-native/Exapmples/SampleApp.xcodeproj  , click run  , got message below:

cannot find entry file Exapmles/SampleApp/index.ios.js in any of the roots: ["/users/bob/documents/learn/HelloReact"]

why did react native find index.ios.js  in other folders?  how to correct it to  /users/bob/documents/learn/github/react-native/Exapmples/ ?

**Comment by blueken** [comment]
sorry, I run a project in /learn/HelloReact before.  I stop that service.  It's fine now

**Comment by jaygarcia** [comment]
@blueken  If you fix your own problems, please close the issue.

Thanks :)

**Comment by kujohn** [comment]
Interested on how this was resolved. Where can I stop the service.

**Comment by frank-xue-porch** [comment]
@blueken  could you tell us how to stop the service you've run? Thanks in advance!

**Comment by frank-xue-porch** [comment]
@kujohn  it's the node server running in terminal as a background worker. stop that and rebuild should be working.

**Comment by qjloong** [comment]
Cannot find entry file in any of the roots: index.ios.js
    at DependecyGraph.getOrderedDependencies ...

**Comment by zxiest** [comment]
@kujohn do `ps aux | grep node` ; stop those processes.
Next, go to the main react-native directory, and do `npm install` to make sure you have all the modules.
Once this is good, do `npm start` ; this will run `packager.sh` and allow our example apps to run.
Next, open the project in XCode and run it. You should be good =)

**Comment by kujohn** [comment]
Thanks @zxiest !
