### ISSUE TITLE
[Tests] Exposing promise lib on global breaks async tests

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native#5410]
The addition of 

```js
global.Promise = require('promise');
```

in

https://github.com/facebook/react-native/commit/3ff39870ce776c653823e1733363be0401896294

leads to all tests with Promises to not work because the Promises never resolve. When the line is removed everything works fine again.

The above mentioned commit does not mention the reason for the line and only talks about the other lines added (mocking the batched bridge).

**Comment by satya164** [comment]
cc @cpojer

**Comment by cgreening** [comment]
Please see

https://github.com/facebook/react-native/issues/6104

Which has a simple test case to recreate the issue.

**Comment by brentvatne** [comment]
Collapsing this issue into #5410
