### ISSUE TITLE
Prevent ToolbarAndroid action touch while processing another one

### ISSUE THREAD

**Issue by juggleru** [facebook/react-native#5416]
Hello there.

I'm using ToolbarAndroid with 2 action buttons.

    var toolbarActions = [
        {
            title: 'Exit', 
            icon: require('../img/exit.png'), 
            show: 'always', 
            showWithText: false
        },
        {
            title: 'Save', 
            icon: require('../img/save.png'), 
            show: 'always',  
            showWithText: false},
    ];
    
    render: function() {
        return (
            <ToolbarAndroid actions={toolbarActions} onActionSelected={this._onActionSelected}>
            </ToolbarAndroid>
        )
    },
    
    _onActionSelected: function(position) {
        switch position {
            case 0: // Exit without save
                this.props.navigator.pop();
            case 1: // Save and exit
                this._saveData(); // Save some data
                this.props.navigator.pop();
        }
    },
    

When I push to action 1 button and then push fast to action 0 button this.props.navigator.pop() executing twice.
Is it possible to prevent toolbar action handling while another action is in process?

**Comment by pangers** [comment]
@juggleru 
When you have clicked on a Toolbar button, you should disable the user from clicking the other buttons. To do that, you will need to somehow keep track of if the navigator is currently in the process of popping or not. Perhaps you can use some state to track this. You will also probably need to hook into the navigator lifecycle events as mentioned here https://facebook.github.io/react-native/docs/navigator.html#onwillfocus

**Comment by juggleru** [comment]
@pangers 
Thanks a lot for your answer.
I try to track with state, but it doesn't work. State does not changing before the handler is called for the second time. I'll try to track state with 'willfocus' listener.

**Comment by juggleru** [comment]
Now I'm preventing second touch by code:

    _onActionSelected: function(position) {
        if (this.state.isBusy) {
            return;
        }

        this.setState({isBusy: true});

        switch position {
            case 0: // Exit
                if (this.state.isDataChanged) {
                    Alert.alert(
                        "Warning!",
                        "Data was changed. Save changes?",
                        [
                            {text: 'No', onPress: () => this.props.navigator.pop()},
                            {text: 'Cancel'},
                            {text: 'Save', onPress: () => {
                                if (this._saveData()) {
                                    this.props.navigator.pop();
                                }
                            }},
                        ]
                    );
                }
                else {
                    this.props.navigator.pop();
                }
                break;
            case 1: // Save and exit
                if(this._saveData()) { // Save some data
                    this.props.navigator.pop();
                    return;
                }
        }
        this.setState({isBusy: false}); // If do not pop current view in previous code
    },
    
Does it mean that I must use this preventing schema for all touchable components? Is there native way to make touchable* components single-touch?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/prevent-toolbarandroid-action-touch-while-processing-another-one

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
