### ISSUE TITLE
Implement OAuth 2 in Android

### ISSUE THREAD

**Issue by arjunkomath** [facebook/react-native#5423]
Is it possible to implement OAuth 2 in Android, using Custom URL or any other means?

Thanks.

**Comment by grabbou** [comment]
Would you mind providing more details on this issue? I don't understand how oAuth2 implementation could relate to what we have in react-native.

Here's sample Medium article showing what to do: https://medium.com/@jtremback/oauth-2-with-react-native-c3c7c64cbb6d

I believe you could also try asking on StackOverflow for the tips how to go further with that.

**Comment by arjunkomath** [comment]
I had doubt regarding deep linking back in android, I'll figure it out. Thanks

**Comment by cablegunmaster** [comment]
Did you figure it out @arjunkomath ? I am having the same issues.

http://stackoverflow.com/questions/37302280/react-native-android-oauth2

**Comment by arjunkomath** [comment]
The redirect_uri for OAuth should link back to your app using Deep linking. You can read more about it here: http://facebook.github.io/react-native/releases/0.25/docs/linking.html#handling-deep-links

**Comment by cablegunmaster** [comment]
Is there a android equivalent for it? because the link given explains its only for ios.
or did you mean: https://developer.android.com/training/app-indexing/deep-linking.html#adding-filters

**Comment by arjunkomath** [comment]
Linking is for both Android and iOS, and you need both the javascript and the android part to make it work. As mentioned in docs: For instructions on how to add support for deep linking on Android, [refer Enabling Deep Links for App Content - Add Intent Filters for Your Deep Links](https://developer.android.com/training/app-indexing/deep-linking.html#adding-filters).
