### ISSUE TITLE
[Android][TextInput] Remove underline option?

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#5424]
I was working around it by setting the `underlineColorAndroid` to the same color as the background, but when you focus, the underline color changes to a teal color no matter what.

**Comment by Ehesp** [comment]
Have you tried just need to underlineColorAndroid='rgba(0,0,0,0)'?

**Comment by rclai** [comment]
I'll give that a try when I get a chance.

**Comment by madwed** [comment]
Setting `rgba(0,0,0,0)` works for me.  I was using `#fff` before with the same problem as @rclai

**Comment by rclai** [comment]
Cool, thanks guys.

**Comment by varungupta85** [comment]
I am also observing a similar problem and setting the `underlineColorAndroid` to `rgba(0, 0, 0, 0)` doesn't seem to help me. This is what I am observing.

This is how it appears to begin with which is good. Before I added `underlineColorAndroid`, there was an underline in the complete width of the text box which was gone once I added the `underlineColorAndroid` which is good.

![screen shot 2016-10-10 at 3 09 34 pm](https://cloud.githubusercontent.com/assets/7475133/19232187/131a5d5c-8efc-11e6-9b3e-ddf67b5b91b6.png)

This is how it appears after adding some text. Notice an underline below the typed text. I want to get rid of that underline too. Do I need to set some other prop on the `TextInput` to get rid of that underline

![screen shot 2016-10-10 at 3 09 51 pm](https://cloud.githubusercontent.com/assets/7475133/19232193/1c535a4a-8efc-11e6-8e47-20b6cf07d6de.png)

**Comment by Sommerfeld** [comment]
@varungupta85 `autoCorrect={false}` might help here.

**Comment by varungupta85** [comment]
@Sommerfeld Great, using `autoCorrect={false}` fixed it. Thanks a lot!

**Comment by afilp** [comment]
It seems that the **autocorrect** solution does not work when the TextInput is **multiline** (I have v0.33).

Are you aware of this? I suppose it is a bug?

**Comment by Sommerfeld** [comment]
The autocorrect solution does not skip the underlineColorAndroid step. The line seen in the image of @varungupta85 is not from the textInput itself it is from the autocorrect and would not have appear for the first word if he would have started typing a second one. (my guess, not tested, not 100% familiar with Android)

**Comment by four-eyes-04-04** [comment]
this should do the trick as per [react-native TextInput documentation](https://facebook.github.io/react-native/docs/textinput.html)

```
<TextInput underlineColorAndroid='transparent'>
```

### Before
![image](https://cloud.githubusercontent.com/assets/21032419/20550016/7c1ce4b8-b16c-11e6-8b06-f4283e374d75.png)

### After
![image](https://cloud.githubusercontent.com/assets/21032419/20550032/9ed80104-b16c-11e6-9e28-4d61bb0662db.png)

**Comment by xuechinahb** [comment]
`underlineColorAndroid='transparent'` works for me. At first, it does not work on android 6.0 emulator. Then run code on android 7.0 emulator, underline is dismiss. So, run on 6.0 again, it works. Maybe `autoFocus={true}` is setted, press R twice to reload JS failed.

**Comment by neilakoh** [comment]
`underlineColorAndroid='transparent'` definitely did the magic for me

**Comment by sagarparikh** [comment]
underlineColorAndroid='transparent' is definitely the way to go.

**Comment by bingle87** [comment]
underlineColorAndroid='transparent' worked for me with single line text.

**Comment by lavarajallu** [comment]
**To give in your Text input Use this Property Remove Under Line**
 <TextInput underlineColorAndroid="transparent" />

**Comment by vijayst** [comment]
underlineColorAndroid="transparent" seems to disable the underline in all TextInput. How to selectively remove the underline for only a few TextInput?

**Comment by lavarajallu** [comment]
i din't get u point


On Sat, Jan 28, 2017 at 1:44 PM, Vijay Thirugnanam <notifications@github.com

**Comment by vijayst** [comment]
@lavarajallu Please ignore the comment, It seems to work now.

**Comment by azamkth** [comment]
work for me

**Comment by razi1122** [comment]
Type underlineColorAndroid='transparent' inside textinput its work 100%

**Comment by ScreamZ** [comment]
Why is this not `underlineColorAndroid="transparent"` by default, this make sense for easy compatibility with iOS ?

**Comment by lavarajallu** [comment]
Bcz when you install nodumodules default color in text Input comparing both
Platforms

**Comment by hoangvuanhdevelopervn** [comment]
underlineColorAndroid='white' It's work for me 👯‍♂️

**Comment by yhugow** [comment]
Thank you guys <3 
<TextInput underlineColorAndroid='transparent'/>

Works fine now!
