### ISSUE TITLE
Error building dependency graph when using packager

### ISSUE THREAD

**Issue by DeeBrad** [facebook/react-native#5431]
I'm having some issues running the packager.  When using 'npm start' I get the following: https://gist.github.com/DeeBrad/7f1d57600a37f6112daa. I have tried deleting node_modules and running npm install again, but that didnt solve it. Any help would be great!

**Comment by chirag04** [comment]
Try

``rm -fr $TMPDIR/react-*``

``watchman watch-del-all``

``npm start --reset-cache``

**Comment by jsierles** [comment]
@facebook-github-bot no-reply
