### ISSUE TITLE
RefreshControl jumping in ListView [iOS]

### ISSUE THREAD

**Issue by seb0zz** [facebook/react-native#5432]
In my application I am the `ListView` component like in the code below. Everything works like charm except of one tiny ugly bug. When I start pulling the list view down it goes down smoothly and increases the number of strokes of the loading spinner. But in the moment the spinner graphic completes and starts spinning I am observing an ugly jump. 

This is exactly the same behavior as described in this [stackoverflow post](http://stackoverflow.com/questions/23769967/pull-to-refresh-jump-in-ios)

```javascript
<ListView
  onEndReached={this._loadMore.bind(this)} 
  onEndReachedThreshold={0}
  refreshControl={
    <RefreshControl
      refreshing={this.state.isRefreshing}
      onRefresh={this._refresh.bind(this)}
    />
  }
  renderFooter={() => {
    return <Image style={styles.loadingIndicator} source={require('../../images/loading.gif')}/>
  }}
  dataSource={this.state.dataSource.cloneWithRows(preparedItems)}
  loadData={this._refresh.bind(this)}
  scrollRenderAheadDistance={1600}
  pageSize={6}
  removeClippedSubviews={true}
  initialListSize={20}
  renderRow={this._renderRow.bind(this)}
/>
```

**Comment by janicduplessis** [comment]
Hi, on what device/simulator does this happens and what version of iOS? Also can you show me the content of your `_refresh` function?

**Comment by seb0zz** [comment]
I can reproduce this bug in every simulator, on my iPhone 6 and also on my iPhone 6s device. My current iOS version is 9.2.

This is my `_refresh` function:

```javascript
_refresh() {
  return new Promise((resolve) => {
    this.setState({isRefreshing: true, skip: 0}, () => {
      this.loadItems(this.state.limit, this.state.skip)
    })
  })
}
```

**Comment by janicduplessis** [comment]
Ok I see what you mean, the ScrollView content scrolls down by like 30px when it starts refreshing.

@nicklockwood @tadeuzagallo @sahrens Any idea why this happens?

**Comment by axelander** [comment]
I had the same problem a couple of months ago trying to implement a UIRefreshControl on a UIWebView. 

> UIScrollView is slowing down the tracking of the pan gesture when you pull past the edge of the scrollview. However, UIScrollView is not accounting for changes to contentInset during tracking. UIRefreshControl changes contentInset when it activates, and this change is causing the jump.

Although I never solved it for the scrollview embedded in the webview, I believe [this solution](http://stackoverflow.com/a/19926917/896173) was the best I came across at that time.

**Comment by yueshuaijie** [comment]
I encounter the same werid problem.

However, I find this only happen if there is few rows in the ListView. If there is many rows, everything is OK. It seems if all the rows exceed the listview's contentSize, the "jumping" appears.

**Comment by ivpusic** [comment]
having the same issue. Anybody got this working?

**Comment by ptmt** [comment]
```
NSLog(@"contentOffset: %f", contentOffset.y);
...

2016-07-19 14:55:34.341 Archy[398:63453] contentOffset: -104.500000
2016-07-19 14:55:34.357 Archy[398:63453] contentOffset: -106.000000
2016-07-19 14:55:34.373 Archy[398:63453] contentOffset: -108.500000
2016-07-19 14:55:34.390 Archy[398:63453] contentOffset: -111.000000
2016-07-19 14:55:34.394 Archy[398:63453] contentOffset: -60.000000
2016-07-19 14:55:34.395 Archy[398:63453] contentOffset: -111.000000
2016-07-19 14:55:34.407 Archy[398:63453] contentOffset: -151.500000
2016-07-19 14:55:34.423 Archy[398:63453] contentOffset: -153.500000
2016-07-19 14:55:34.440 Archy[398:63453] contentOffset: -156.000000
```

Thanks to @axelander, this answer from StackOverflow http://stackoverflow.com/questions/19483511/uirefreshcontrol-with-uicollectionview-in-ios7/19926917#19926917 fixed the issue for me.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/refreshcontrol-jumping-in-listview-ios

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
