### ISSUE TITLE
[0.18] Requiring module "NativeModules" which threw and exception (line 64 in the generated bundle)

### ISSUE THREAD

**Issue by gadiel** [facebook/react-native#5433]
Throws after getting data from packager

**Comment by gadiel** [comment]
fixed it by deleting react-native from /node_modules and redoing npm-install

**Comment by tsvetann** [comment]
@gadiel I did as per your last post here but no success. Still getting this error message on Android 4.4.4

**Comment by bruz** [comment]
I ran into this, and in my case it was from forgetting to restart React Packager after upgrading to 0.18.1.

**Comment by tsvetann** [comment]
In my case the problem was using the old version of npm. After upgrading to peerDependencies removed the node_modules, reinstalled and all was working.

**Comment by danpe** [comment]
deleting node_modulels and redoing `npm install` did not solve it for me

**Comment by tsvetann** [comment]
@danpe node/npm versions? Can you pls post the stack trance from the packager!

**Comment by BigPun86** [comment]
Ran into same issue when updating my Node and npm (v5.5.0 & 3.3.12). I have some naming collision which i could fix but i have no clue how to solve this...

**Comment by tsvetann** [comment]
@BigPun86 did you try deleting node_modules and then npm install?

**Comment by BigPun86** [comment]
@tsvetann Yes i tried it. After that i got naming collisions accorded to fbjs. I followed this issue #5390 which fixed that part.

**Comment by avishayil** [comment]
I have the same issue as well.
Tried to follow the steps on the naming collisions to fbjs, tried to delete react-native and reinstall by npm install, nothing works.

**Comment by ghamaide** [comment]
I'm having this error with naming collisions (in the same package...)
`Error: Naming collision detected: /Users/gregoirehamaide/Documents/NeedlIOS/node_modules/fbjs/flow/include/warning.js collides with /Users/gregoirehamaide/Documents/NeedlIOS/node_modules/fbjs/lib/warning.js`

**Comment by BigPun86** [comment]
1) rm -rf node_modules
2) npm install
3) npm install fbjs
3) find . -name 'fbjs' -print
4) manually remove all fbjs inside any node_module except one at top level
5) rm -fr $TMPDIR/react-*
6) watchman watch-del-all
7) react-native start --reset-cache

Refer to #5390

**Comment by gadiel** [comment]
Before having this problem I followed [this steps](https://github.com/facebook/react-native/issues/5390#issuecomment-172679236) to solve the fbjs naming collisions.

I also tried deleting the app from my phone, and doing a clean **react-native run-android**

another thing to try would be to delete the **npm cache** maybe there was a network timeout while downloading RN 18

**Comment by ghamaide** [comment]
OK, works fine, thx. Weird thought cause I followed these steps the last time. Anyway, thx !

**Comment by avishayil** [comment]
In my case the Alt library, which contains the module flow was the problematic library.
After investigation I found that Alt version 0.18.0 (latest is 0.18.2) is working fine with React-Native 0.19.0. So if you don't need any of the features of 0.18.2, you should use 0.18.0 probably.

Other than that:

- I'm using npm2, so npm install -g npm@2

1) I removed node_modules directory 
2) watchman watch-del-all
3) ./node_modules/react-native/packager/packager.sh -root . -clean

4) react-native run-android in another terminal window

Now everything works.

**Comment by cldwalker** [comment]
I had the same NativeModules issue with RN 0.20.0 and node 5.7.1. Locking down fbjs to 0.6.1 as explained in https://github.com/facebook/react-native/issues/5622#issuecomment-189364805 and following the above fbjs instructions resolved this for me

**Comment by jsierles** [comment]
React Native 0.22.0 should solve the naming problems mentioned here, so please give 0.22.0-rc a try!

Closing this issue out - feel free to continue discussion here or reopen should either of these errors resurface.
