### ISSUE TITLE
[ScrollView] Image fixed inside the scrollview

### ISSUE THREAD

**Issue by JeremDsgn** [facebook/react-native#5438]
Hi !

I would like to fixed an image, and a linear gradient as well, on a dedicate view inside the scrollview component. I tried with some styles, but each times, the image scroll with content.

What can I do ?

```jsx
<ScrollView>
  {/* TODO: Prevent scroll for this View — Add blur image on background */}
  <View>
    <Image source={{ uri: cover_photo }} />
    <LinearGradient  />
  </View>

  {/* This view is scrollable ABOVE the background image */}
  <View>
     {…content}
  </View>
</ScrollView>
```

**Comment by jevakallio** [comment]
Try declaring your background element "behind" the ScrollView using `position:absolute` within a `position:relative` container, and make the ScrollView transparent to let the background show through:

```
<View style={[styles.container]}>
  <View style={[styles.fixed]}>
    {backgroundImageContent}
  </View>
  <ScrollView style={[styles.fixed, {backgroundColor: 'transparent'}]}>
    {scrollableContent}
  </ScrollView>
</View>
```

```
var styles = StyleSheet.create({
  container: {
    position: 'relative'
  },
  fixed: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  }
})
```

These types of questions are better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). The GitHub issues are best used for reporting problems with the framework itself.

**Comment by JeremDsgn** [comment]
Thanks. This is what the bot said, I posted on stackoverflow.
