### ISSUE TITLE
[RefreshControl][ListView] setState of ListView dataSource at the same time as refreshing causes sticky header error

### ISSUE THREAD

**Issue by gtfargo** [facebook/react-native#5440]
![screen shot 2016-01-20 at 1 14 38 pm](https://cloud.githubusercontent.com/assets/2320535/12462851/169d9c3c-bf86-11e5-8738-f509a40651d6.png)

Temporary workaround is to setState of refreshing AFTER the datasource is updated.  

```
this.setState({dataSource: this.state.dataSource.cloneWithRowsAndSections(obj)});
setTimeout(() => this.setState({isRefreshing: false}), 1);
```

**Comment by janicduplessis** [comment]
I'll look at this, I managed to repro the bug. It seems to happen only when there is 1 row per section and when removing elements from the DataSource.
