### ISSUE TITLE
ERROR  watchman--no-pretty get-sockname

### ISSUE THREAD

**Issue by infacq** [facebook/react-native#5444]
i know this error has been solved. I followed everything uninstall then reinstall. update and upgrade. run `npm r -g watchman`... but all fail when try to run `npm start`

I suspect because my `LaunchAgents` on macbook has been interrupted. this is what I get when run 

`ls -ld ~/Library/LaunchAgents`

```bash
lrwxr-xr-x  1 infacq  staff  46 Aug 16 11:03 /Users/infacq/Library/LaunchAgents -> /usr/local/opt/mysql/homebrew.mxcl.mysql.plist
```

anyone experience this?

**Comment by grabbou** [comment]
Hey @infacq, do you have any news here? Looks like no-one had this issue so far (judging by the amount of answers). Was that something or your end or a watchman issue that got fixed in the meantime?
