### ISSUE TITLE
[Docs] ShadowPropTypesIOS style link broken

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#5450]
https://facebook.github.io/react-native/docs/view.html#style

**Comment by eduvon0220** [comment]
The link is broken because the page doesn't exist anywhere, at least I can't seem to find it.

**Comment by brentvatne** [comment]
@eduvon0220 - that seems to be true indeed! so this issue would involve adding it back

**Comment by lizouzt** [comment]
May be we can look this [https://github.com/facebook/react-native/blob/e4c53c28aea7e067e48f5c8c0100c7cafc031b06/Libraries/Components/View/ShadowPropTypesIOS.js](url)

**Comment by dabit3** [comment]
Seems to be fixed now https://facebook.github.io/react-native/docs/shadowproptypesios.html

**Comment by caltrain** [comment]
Hi @dabit3 I think it is still broken, because all the 3 links are now redirecting to "Getting started" page.
