### ISSUE TITLE
alignSelf:'center' is Invalid

### ISSUE THREAD

**Issue by senpng** [facebook/react-native#5451]
![image](https://cloud.githubusercontent.com/assets/7333114/12471780/e7f87760-c03b-11e5-9d39-1b53f375a6a1.png)
![image](https://cloud.githubusercontent.com/assets/7333114/12471761/af18e704-c03b-11e5-88bf-96c030f0a612.png)
This ''blue line" is not center;

when i set the parent view's height and the blue line is center

![image](https://cloud.githubusercontent.com/assets/7333114/12471802/20048964-c03c-11e5-9643-4739c2cb46d7.png)
![image](https://cloud.githubusercontent.com/assets/7333114/12471806/294b5336-c03c-11e5-941a-6bb45ab9c98f.png)

I think it is bug at here. because the blue line's parent view's height is determine.

**Comment by corbt** [comment]
This may be related to https://github.com/facebook/css-layout/pull/145, there are a few layout bugs similar to this one that should fix.

**Comment by satya164** [comment]
Yeah. Please post it on the css-layout repo. Closing this,
