### ISSUE TITLE
Image  drawable question

### ISSUE THREAD

**Issue by jiangqqlmj** [facebook/react-native#5453]
Now，when i use Image Component, i find that must let images into drawable or drawable-hdpi .eg。
but from init project that The default does not exist drawable in android project!
so  this is a bug?
The official code ：&lt;Image source={{uri: 'app_icon'}} style={{width: 40, height: 40}} /&gt;

**Comment by jiangqqlmj** [comment]
<Image source={{uri: 'app_icon'}} style={{width: 40, height: 40}} />

**Comment by satya164** [comment]
You can put images wherever you want and can directly require them. Refer http://facebook.github.io/react-native/docs/images.html#content
