### ISSUE TITLE
'react-native upgrade' overwrites .flowconfig without asking

### ISSUE THREAD

**Issue by gnl** [facebook/react-native#5455]
...when upgrading to 0.18.1.
react-native-cli version is 0.1.10

**Comment by mkonicek** [comment]
@gnl Would you be up for sending a PR to fix this?

**Comment by satya164** [comment]
Duplicate of #4852

**Comment by gnl** [comment]
Looks like someone's already on it (I guess a search might've been a good idea before filing this)
