### ISSUE TITLE
RN 0.17.0/0.18.1 new app - iOS memory usage keeps climbing - leak?

### ISSUE THREAD

**Issue by joshblour** [facebook/react-native#5458]
I noticed that the memory usage of my app would keep climbing, sometimes reaching 500mb.

To test, I created a brand new app `$ react-native init AwesomeProject` and ran it on my iPhone 6. The memory usage climbs steadily. It quickly reached 60mb after just 5min of idling.
![screen shot 2016-01-21 at 12 17 38](https://cloud.githubusercontent.com/assets/1440796/12479067/0e538d62-c039-11e5-9ca1-3e3dc4bd9633.png)

**Comment by tomauty** [comment]
Is this when you're building for `Debug`, or `Release`? There are some things going on with `Debug` that may make this happen.

**Comment by joshblour** [comment]
Ok, my mistake. I thought I had experienced this issue even while building for `Release` but I just tried again and couldn't reproduce. I'll close the issue, sorry about that.
