### ISSUE TITLE
[Docs] Add documentation for ColorPropType

### ISSUE THREAD

**Issue by Cryszon** [facebook/react-native#5459]
Looking at the source code of [ColorPropType.js](https://github.com/facebook/react-native/blob/847220957aec7e094d66b1a6436cd3850e2c1291/Libraries/StyleSheet/ColorPropType.js) I found out that ColorPropType uses [TinyColor](https://github.com/bgrins/TinyColor) for color validation and from there it's easy to see which values are accepted. However, I couldn't find this anywhere in the documentation. All the style props simply list colors as `ColorPropType`, which isn't really helpful.

**Comment by mkonicek** [comment]
@Cryszon can you send a PR please? No one on the team is realistically going to have time to fix issues like this but we can review a PR.

**Comment by mkonicek** [comment]
Please link the PR to this issue so it gets closed when the PR is merged.

**Comment by eduvon0220** [comment]
@mkonicek I can work on this but my forked repo isn't matching up with what's on remote master branch.  For instance, the path on remote to Switch.js is `Libraries/Components/Switch/Switch.js` but on my local forked repo it's `/Libraries/Components/SwitchIOS/SwitchIOS.ios.js`.  Am I missing something here?

**Comment by oviava** [comment]
https://github.com/facebook/react-native/commit/1154f2a371e9489ccc1e6a5ec24a1de2b79a9b73. 
@mkonicek can probably be closed.
