### ISSUE TITLE
Image with invalid source URI crashes in 0.18 on Android

### ISSUE THREAD

**Issue by thomdixon** [facebook/react-native#5465]
Easy enough to reproduce:

Use `<Image source={{uri: null}} />` and it will crash your application. Likewise, invalid URIs, such as `<Image source={{uri: '//facebook.github.io/react-native/img/header_logo.png'}} />` will also crash.

This is because [line 279 in ReactImageView.java of ReactAndroid](https://github.com/facebook/react-native/blob/1f501a9431a56a357987dcf42520c0626b713b50/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageView.java#L279) passes a null URI to [line 103 in ImageRequestBuilder.java of fresco](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/request/ImageRequestBuilder.java#L103) that calls `Preconditions.checkNotNull` on the null `uri`, which throws a NPE.

**Comment by dmmiller** [comment]
I'm going to get a fix in for this.  And will get it picked over to 0.19

**Comment by thomdixon** [comment]
Thanks so much @dmmiller!!!

**Comment by natdm** [comment]
Is this totally fixed? I'm getting mine to crash on correct image links, but it won't on incorrect image links.

Here's a video of it happening for me.
https://www.youtube.com/watch?v=oqjZ-2zKcO8&feature=youtu.be

**Comment by natdm** [comment]
It looks like one of my images was broken, still killing the app.

I've got "events" which have pictures in them. One is crashing, the other is not. If I update them all to one image that I know works, it all works fine. If I use the actual links - one event busts, but the others are fine. I'm thinking that event has one broken image. What do you need from me to look in to it more?

**Comment by dmmiller** [comment]
What version are you still seeing this on?  Can you maybe give me the image link that seems to fail?  The easiest thing is if you just make a small component with <Image src={uri:crashing-value}/> and post a link.  I can look further then.
