### ISSUE TITLE
Listview section header doesn't respond to state changes

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#5473]
I've asked this question on stackoverflow but you don't tend to get many responses regarding React Native over there. It seems like it might be an issue anyway.

http://stackoverflow.com/questions/34917120/react-native-listview-with-fixed-section-header-that-can-be-updated

This header responds to state changes no problem but is not fixed in place:

    <ListView
      dataSource: dataSource.cloneWithRowsAndSections(dataBlob, sectionIDs, rowIDs),
      renderHeader={this.renderHeader}
      renderRow={this._renderRow}
    />

    renderHeader: function() {
     return (
     <View>
      <Text>{this.state.header}</Text>
    </View>

This way is fixed in place but does not respond to state changes:

    <ListView
      dataSource: dataSource.cloneWithRowsAndSections(dataBlob, sectionIDs, rowIDs),
      renderSectionHeader={this.renderSectionHeader}
      renderRow={this._renderRow}
    />

    renderSectionHeader: function() {
    return (
     <View>
      <Text>{this.state.header}</Text>
     </View>

**Comment by satya164** [comment]
Check your `sectionHeaderHasChanged` method.

**Comment by hasen6** [comment]
Its just set to this:

          sectionHeaderHasChanged: (h1, h2) => h1 !== h2,

**Comment by satya164** [comment]
Well, it means that if header data hasn't changed, don't update the header. If your header depends on state, you need to change the function to compare previous state to current state to determine if header should be updated or not.

Please use StackOverflow to ask such kind of questions in the future.

**Comment by hasen6** [comment]
There's a link to the stackoverflow question in the original post. With the extreme lack of documentation on these things its very hard to figure out how to do these things and even if you do it might be an error preventing it from working.

**Comment by rgoldiez** [comment]
@hasen6 - Did you find a resolution to this?
