### ISSUE TITLE
How do i compile a React Native project to Android apk

### ISSUE THREAD

**Issue by gregkawere** [facebook/react-native#5479]
Just finished a react native project for an app we are developing, we want to compile the code to an apk anyone know how i can do this

**Comment by Ehesp** [comment]
Have you even read the docs? https://facebook.github.io/react-native/docs/signed-apk-android.html#content

**Comment by gregkawere** [comment]
yes i have but the $ cd android && ./gradlew assembleRelease is a ios
command it does not run on windows

Greg Kawere
+27 7342 99519
gregkawere@gmail.com

**Comment by Ehesp** [comment]
Have you tried running `gradlew assembleRelease` on it's own without `./`?

**Comment by satya164** [comment]
Try running the following, `cd android && gradlew.bat assembleRelease`

You prolly don't need the `.bat`. I've not tested this as I don't have a Windows box. Please test it and lemme know if it works. PRs are welcome to fix the docs.

**Comment by satya164** [comment]
We should prolly have commands `react-native build-android --release` and  `react-native build-android --debug` which detects windows or Mac/Linux and runs the relevant commands accordingly.

**Comment by gregkawere** [comment]
reinstalled jdk, sdk and updated react and finally got the apk to generate using "gradelew assembleRelease" But now it doesnt load assets, so apk doesnt install, any ideas 
ps: i am using a windows machine

**Comment by satya164** [comment]
@gregkawere If you cannot install the APK, that prolly means that you didn't generate a signed APK. In case the bundle was not included, app will install fine, but crash on opening.

**Comment by gregkawere** [comment]
any ideas on how i can fix this

**Comment by satya164** [comment]
@gregkawere http://facebook.github.io/react-native/docs/signed-apk-android.html#content

Replace `~/.gradle/gradle.properties` with `C:\Users\<username>\.gradle\gradle.properties` in the docs. (PR is welcome)

**Comment by satya164** [comment]
Any luck with this?

**Comment by efkan** [comment]
@gregkawere , 
I've created an apk in Windows by using Cygwin and [official site directions](http://facebook.github.io/react-native/docs/signed-apk-android.html). Cygwin provide simple and basic Linux terminal command set on the Windows. Look at [this](https://cygwin.com/install.html).

After installing Cygwin, the command of `cd android && bash ./gradlew assembleRelease` can be used. Keep in mind using the **`bash`** word in the command. It is necessary.

Good luck.

**Comment by janicduplessis** [comment]
@facebook-github-bot stack-overflow

**Comment by TRIPTI-JAIN** [comment]
You need to manually create the bundle for a debug build:-

Bundle debug build:
**Run this command in your Project**
react-native bundle --dev false --platform android --entry-file index.android.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug

**Create debug build:**

cd android
./gradlew assembleDebug

For Windows: gradlew assembleRelease

Generated apk will be located at android/app/build/outputs/apk

**Comment by umair3649** [comment]
(react-native bundle --dev false --platform android --entry-file index.android.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug) is this a full command??

**Comment by umair3649** [comment]
![screenshot 13](https://user-images.githubusercontent.com/22945448/38419594-7c737378-39ba-11e8-9d05-85c9871ec22f.png)

> i made changes in react-navigation folder for tab view i think because of that it won't let me make apk.  I tried alot but failed. Guide me how can i make apk now.

**Comment by umair3649** [comment]
![file](https://user-images.githubusercontent.com/22945448/38419922-9e117786-39bb-11e8-99df-f0975a4c7a75.PNG)

> I made changes in react-navigation folder for tab view. I think because of that it won't let me build apk. I tried alot but failed. Kindly Guide me how can i make apk file now.

**Comment by TRIPTI-JAIN** [comment]
https://github.com/facebook/react-native/issues/6745
https://stackoverflow.com/questions/35283959/build-and-install-unsigned-apk-on-device-without-the-development-server
open this Url and you can find solution
