### ISSUE TITLE
The $ cd android && ./gradlew assembleRelease command does not execute on a Windows machine

### ISSUE THREAD

**Issue by gregkawere** [facebook/react-native#5482]
When i try to run the command $ cd android && ./gradlew assembleRelease on a Windows machine inorder to create an apk file the command does not run,

It seems the && is a apple command. can u please update the documentation on how to compile to apk on a windows machine https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by andybb** [comment]
Run `gradlew assembleRelease` from the android folder on Windows.

**Comment by satya164** [comment]
Duplicate of #5479

**Comment by dhlopez** [comment]
After running gradlew assembleRelease I get this:
* What went wrong:
Could not compile build file '~\node_modules\react-native\ReactAndroid\build.gradle'.
> startup failed:
import de.undercouch.gradle.tasks.download.Download

Any clue?
