### ISSUE TITLE
ToolbarAndroid action title color

### ISSUE THREAD

**Issue by py110** [facebook/react-native#5483]
in ToolbarAndroid  actions
var toolbarActions = [
  {title: 'Create', icon: require('image!ic_create_black_48dp'), show: 'always'},
  {title: 'Filter'},
  {title: 'Settings', icon: require('image!ic_settings_black_48dp'), show: 'always'},
];

how to change the action title color

**Comment by janicduplessis** [comment]
There's no built in way in react-native to do that but it is possible to do it by changing the styles.xml file of your app.

See this for examples of how to do it http://stackoverflow.com/questions/28352963/change-toolbar-menu-item-color-non-hidden-action

**Comment by janicduplessis** [comment]
@facebook-github-bot answered
