### ISSUE TITLE
Navigator with HorizontalSwipeJump leads to poor touch recognition

### ISSUE THREAD

**Issue by marcusroberts** [facebook/react-native#5485]
My React Native 0.17 app, based on Navigator, was showing an infuriating inability to recognise touch/taps after Navigator pushes and pops.  This seemed to affect the Android version in release mode the most.  Half the time touches would be recognised, the rest of the time you could tap between one and ten times on a Touchable* component before it would respond.

I was using the HorizontalSwipeJump animation type.  After switching this to FloatFromRight to PushFromRight the issue went away.   Looking at the differences in these animations, the most obvious is HorizontalSwipeJump enables gestures.

If I use the same animation with no gestures, it all works perfectly

configureScene={() => {
          return Object.assign({}, Navigator.SceneConfigs.HorizontalSwipeJump , {gestures: {}})
 }}

I guess there's some interaction between the gestures and touch handling - profiling shows no overrunning animations or JS thread work.

(Hope this helps anyone in the same situation, I reworked every part of my app looking for the performance hit until I changed the animation type)

**Comment by bradbumbalough** [comment]
Amazing! I had the same issue in 0.21.

**Comment by lacker** [comment]
Thanks for reporting this! This seems like an informative issue, but since it's fundamentally a performance issue with a workaround this issue seems to be mostly being useful just by existing and being googleable, so I'm going to close it. Feel free to reopen an issue if there is a specific area that should be improved here.
