### ISSUE TITLE
Using xcodebuild to build a ReactNative application

### ISSUE THREAD

**Issue by flexaddicted** [facebook/react-native#5487]
I'm using the following script to build a ReactNativeApplication.

    xcodebuild \
      -sdk iphonesimulator \
      -arch i386 \
      -project MyProject.xcodeproj \
      -configuration Debug \
      clean build | xcpretty

The structure of the project is the following.

    MyProject
        - Libraries
              - React.xcodeproj
              - RCTAction.xcodeproj
              - ...

I always end with the following errors.

    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/ActionSheetIOS/build/Debug-iphonesimulator/libRCTActionSheet.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Geolocation/build/Debug-iphonesimulator/libRCTGeolocation.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Image/build/Debug-iphonesimulator/libRCTImage.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/LinkingIOS/build/Debug-iphonesimulator/libRCTLinking.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Network/build/Debug-iphonesimulator/libRCTNetwork.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Settings/build/Debug-iphonesimulator/libRCTSettings.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Text/build/Debug-iphonesimulator/libRCTText.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/Vibration/build/Debug-iphonesimulator/libRCTVibration.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/Libraries/WebSocket/build/Debug-iphonesimulator/libRCTWebSocket.a'
    ❌  clang: error: no such file or directory: '/node_modules/react-native/React/build/Debug-iphonesimulator/libReact.a'

Any suggestion?

**Comment by timjacobi** [comment]
@flexaddicted We had the same problem today and figured it out
```Bash
```

**Comment by timjacobi** [comment]
@flexaddicted We had the same problem today and figured it out

The command you ran only builds the main project and not the dependencies. If you want to build the dependencies as well do the following.

You have to run `xcodebuild` with the `-workspace` flag. This requires you to pass the workspace name and a scheme.

To get the list of schemes run
```Bash
xcodebuild -workspace {your project}.xcodeproj/{your workspace}.xcworkspace/ -list
```
Then pick the scheme for you project and run
```Bash
xcodebuild -workspace {your project}.xcodeproj/{your workspace}.xcworkspace/ -scheme {your scheme}
```

**Comment by h3l** [comment]
@timjacobi have you get the right ipa?
I always get a previous ipa

**Comment by alexprice91** [comment]
@h3l @timjacobi were either of you able to figure this out? It seems to build, but when I try to use it in my tests, appium gives me the error:

```
Encountered internal error running command: Error: Could not extract Info.plist from application: Plist file doesn't exist: '/Users/alexprice/code/private/scheduler/react-native/ios/build/Release-iphoneos/chat.app/Info.plist'
```

**Comment by timjacobi** [comment]
@alexprice91 nope never seen that sorry

**Comment by chc200** [comment]
I'm having the same problem clang: error: no such file or directory: '/Users/cc/Library/Developer/Xcode/DerivedData/ybFrontEnd/Build/Products/Debug-iphonesimulator/libReact.a'

did you guys have any luck?

**Comment by kiliwalk** [comment]
HI @chc200 , have you solved this problem? same as using pods

**Comment by romeldris** [comment]
@chc200 @kiliwalk I jus started seeing this locally as well, have you guys figured it out?

**Comment by kiliwalk** [comment]
@romeldris Yep, But may not be helpful to you.  You can see [here](https://github.com/ivpusic/react-native-image-crop-picker/issues/21#issuecomment-235785183).

**Comment by romeldris** [comment]
@kiliwalk I actually just deleted my .xcworkspace and re ran a pod install and that seemed to work

**Comment by Thorbenandresen** [comment]
I had to add `-lc++` to `Other Linker Flags` for my **MyProjectTest** target  and everything worked again. This flag was already set to **MyProject** target out of the box.

**Comment by chrise86** [comment]
I'm still getting this after trying everything here, any ideas? :-/

**Comment by nartawak** [comment]
I have the same issue : 
clang: error: no such file or directory: /Users/xxxx/Library/Developer/Xcode/DerivedData/xxxxx-gbijunyftuykpjfbqaoweubyfotv/Build/Products/Debug-iphoneos/libReact.a'

In the debug-iphoneos directory, i have a React directory and the libreact.a is generated in this folder 👎 :

`debug-iphoneos` : 
drwxr-xr-x   22 SQLI  staff   748B 12 aoû 17:39 .
drwxr-xr-x@   4 SQLI  staff   136B 12 aoû 17:38 ..
drwxr-xr-x   20 SQLI  staff   680B 12 aoû 17:39 Bolts
drwxr-xr-x   23 SQLI  staff   782B 12 aoû 17:39 FBSDKCoreKit
drwxr-xr-x   10 SQLI  staff   340B 12 aoû 17:39 FBSDKLoginKit
drwxr-xr-x   36 SQLI  staff   1,2K 12 aoû 17:39 FBSDKShareKit
drwxr-xr-x    3 SQLI  staff   102B 12 aoû 17:38 xxxxx.app
drwxr-xr-x  148 SQLI  staff   4,9K 12 aoû 17:39 React
-rw-r--r--    1 SQLI  staff   4,6K 12 aoû 17:39 libPods-xxxxx.a
-rw-r--r--    1 SQLI  staff   4,7K 12 aoû 17:39 libPods-xxxxxTests.a
-rw-r--r--    1 SQLI  staff    70K 12 aoû 17:39 libRCTActionSheet.a
-rw-r--r--    1 SQLI  staff    78K 12 aoû 17:39 libRCTGeolocation.a
-rw-r--r--    1 SQLI  staff   544K 12 aoû 17:39 libRCTImage.a
-rw-r--r--    1 SQLI  staff    42K 12 aoû 17:39 libRCTLinking.a
-rw-r--r--    1 SQLI  staff   342K 12 aoû 17:39 libRCTNetwork.a
-rw-r--r--    1 SQLI  staff    35K 12 aoû 17:39 libRCTSettings.a
-rw-r--r--    1 SQLI  staff   593K 12 aoû 17:39 libRCTText.a
-rw-r--r--    1 SQLI  staff    16K 12 aoû 17:39 libRCTVibration.a
-rw-r--r--    1 SQLI  staff   398K 12 aoû 17:39 libRCTWebSocket.a
drwxr-xr-x    8 SQLI  staff   272B 12 aoû 17:39 react-native-fbsdkcore
drwxr-xr-x    6 SQLI  staff   204B 12 aoû 17:39 react-native-fbsdklogin
drwxr-xr-x   15 SQLI  staff   510B 12 aoû 17:39 react-native-fbsdkshare

`React directory` : 

drwxr-xr-x  148 SQLI  staff   4,9K 12 aoû 17:39 .
drwxr-xr-x   22 SQLI  staff   748B 12 aoû 17:39 ..
-rw-r--r--    1 SQLI  staff   2,5K 12 aoû 17:39 CSSLayout-internal.h
-rw-r--r--    1 SQLI  staff   6,2K 12 aoû 17:39 CSSLayout.h
-rw-r--r--    1 SQLI  staff   522B 12 aoû 17:39 CSSMacros.h
-rw-r--r--    1 SQLI  staff   993B 12 aoû 17:39 CSSNodeList.h
-rw-r--r--    1 SQLI  staff   951B 12 aoû 17:39 RCTAccessibilityManager.h
-rw-r--r--    1 SQLI  staff   402B 12 aoû 17:39 RCTActivityIndicatorView.h
-rw-r--r--    1 SQLI  staff   531B 12 aoû 17:39 RCTActivityIndicatorViewManager.h
-rw-r--r--    1 SQLI  staff   471B 12 aoû 17:39 RCTAlertManager.h
-rw-r--r--    1 SQLI  staff   565B 12 aoû 17:39 RCTAnimationType.h
-rw-r--r--    1 SQLI  staff   386B 12 aoû 17:39 RCTAppState.h
-rw-r--r--    1 SQLI  staff   5,2K 12 aoû 17:39 RCTAssert.h
-rw-r--r--    1 SQLI  staff   1,2K 12 aoû 17:39 RCTAsyncLocalStorage.h
-rw-r--r--    1 SQLI  staff   999B 12 aoû 17:39 RCTAutoInsetsProtocol.h
-rw-r--r--    1 SQLI  staff   2,1K 12 aoû 17:39 RCTBorderDrawing.h
-rw-r--r--    1 SQLI  staff   491B 12 aoû 17:39 RCTBorderStyle.h
-rw-r--r--    1 SQLI  staff   4,3K 12 aoû 17:39 RCTBridge+Private.h
-rw-r--r--    1 SQLI  staff   6,1K 12 aoû 17:39 RCTBridge.h
-rw-r--r--    1 SQLI  staff   2,3K 12 aoû 17:39 RCTBridgeDelegate.h
-rw-r--r--    1 SQLI  staff   828B 12 aoû 17:39 RCTBridgeMethod.h
-rw-r--r--    1 SQLI  staff   8,0K 12 aoû 17:39 RCTBridgeModule.h
-rw-r--r--    1 SQLI  staff   1,8K 12 aoû 17:39 RCTBundleURLProvider.h
-rw-r--r--    1 SQLI  staff   398B 12 aoû 17:39 RCTClipboard.h
-rw-r--r--    1 SQLI  staff   1,9K 12 aoû 17:39 RCTComponent.h
-rw-r--r--    1 SQLI  staff   1,3K 12 aoû 17:39 RCTComponentData.h
-rw-r--r--    1 SQLI  staff   576B 12 aoû 17:39 RCTConvert+CoreLocation.h
-rw-r--r--    1 SQLI  staff   796B 12 aoû 17:39 RCTConvert+MapKit.h
-rw-r--r--    1 SQLI  staff   8,7K 12 aoû 17:39 RCTConvert.h
-rw-r--r--    1 SQLI  staff   552B 12 aoû 17:39 RCTDataRequestHandler.h
-rw-r--r--    1 SQLI  staff   381B 12 aoû 17:39 RCTDatePicker.h
-rw-r--r--    1 SQLI  staff   507B 12 aoû 17:39 RCTDatePickerManager.h
-rw-r--r--    1 SQLI  staff   1,9K 12 aoû 17:39 RCTDefines.h
-rw-r--r--    1 SQLI  staff   438B 12 aoû 17:39 RCTDevLoadingView.h
-rw-r--r--    1 SQLI  staff   2,8K 12 aoû 17:39 RCTDevMenu.h
-rw-r--r--    1 SQLI  staff   657B 12 aoû 17:39 RCTDisplayLink.h
-rw-r--r--    1 SQLI  staff   709B 12 aoû 17:39 RCTErrorCustomizer.h
-rw-r--r--    1 SQLI  staff   736B 12 aoû 17:39 RCTErrorInfo.h
-rw-r--r--    1 SQLI  staff   2,8K 12 aoû 17:39 RCTEventDispatcher.h
-rw-r--r--    1 SQLI  staff   1,2K 12 aoû 17:39 RCTEventEmitter.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTExceptionsManager.h
-rw-r--r--    1 SQLI  staff   755B 12 aoû 17:39 RCTFPSGraph.h
-rw-r--r--    1 SQLI  staff   548B 12 aoû 17:39 RCTFileRequestHandler.h
-rw-r--r--    1 SQLI  staff   1,4K 12 aoû 17:39 RCTFrameUpdate.h
-rw-r--r--    1 SQLI  staff   407B 12 aoû 17:39 RCTGIFImageDecoder.h
-rw-r--r--    1 SQLI  staff   548B 12 aoû 17:39 RCTHTTPRequestHandler.h
-rw-r--r--    1 SQLI  staff   531B 12 aoû 17:39 RCTI18nManager.h
-rw-r--r--    1 SQLI  staff   725B 12 aoû 17:39 RCTI18nUtil.h
-rw-r--r--    1 SQLI  staff   476B 12 aoû 17:39 RCTImageBlurUtils.h
-rw-r--r--    1 SQLI  staff   408B 12 aoû 17:39 RCTImageEditingManager.h
-rw-r--r--    1 SQLI  staff    10K 12 aoû 17:39 RCTImageLoader.h
-rw-r--r--    1 SQLI  staff   1,4K 12 aoû 17:39 RCTImageSource.h
-rw-r--r--    1 SQLI  staff   1,3K 12 aoû 17:39 RCTImageStoreManager.h
-rw-r--r--    1 SQLI  staff   4,1K 12 aoû 17:39 RCTImageUtils.h
-rw-r--r--    1 SQLI  staff   860B 12 aoû 17:39 RCTImageView.h
-rw-r--r--    1 SQLI  staff   392B 12 aoû 17:39 RCTImageViewManager.h
-rw-r--r--    1 SQLI  staff   409B 12 aoû 17:39 RCTInvalidating.h
-rw-r--r--    1 SQLI  staff   3,2K 12 aoû 17:39 RCTJSCExecutor.h
-rw-r--r--    1 SQLI  staff   731B 12 aoû 17:39 RCTJSCProfiler.h
-rw-r--r--    1 SQLI  staff   3,1K 12 aoû 17:39 RCTJSCWrapper.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTJSStackFrame.h
-rw-r--r--    1 SQLI  staff   2,9K 12 aoû 17:39 RCTJavaScriptExecutor.h
-rwxr-xr-x    1 SQLI  staff   1,6K 12 aoû 17:39 RCTJavaScriptLoader.h
-rw-r--r--    1 SQLI  staff   1,6K 12 aoû 17:39 RCTKeyCommands.h
-rw-r--r--    1 SQLI  staff   394B 12 aoû 17:39 RCTKeyboardObserver.h
-rw-r--r--    1 SQLI  staff   4,1K 12 aoû 17:39 RCTLog.h
-rw-r--r--    1 SQLI  staff   429B 12 aoû 17:39 RCTMacros.h
-rw-r--r--    1 SQLI  staff   1,5K 12 aoû 17:39 RCTMap.h
-rw-r--r--    1 SQLI  staff   994B 12 aoû 17:39 RCTMapAnnotation.h
-rw-r--r--    1 SQLI  staff   386B 12 aoû 17:39 RCTMapManager.h
-rw-r--r--    1 SQLI  staff   548B 12 aoû 17:39 RCTMapOverlay.h
-rw-r--r--    1 SQLI  staff   724B 12 aoû 17:39 RCTModalHostView.h
-rw-r--r--    1 SQLI  staff   475B 12 aoû 17:39 RCTModalHostViewController.h
-rw-r--r--    1 SQLI  staff   443B 12 aoû 17:39 RCTModalHostViewManager.h
-rw-r--r--    1 SQLI  staff   2,8K 12 aoû 17:39 RCTModuleData.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTModuleMethod.h
-rw-r--r--    1 SQLI  staff   1,5K 12 aoû 17:39 RCTNavItem.h
-rw-r--r--    1 SQLI  staff   391B 12 aoû 17:39 RCTNavItemManager.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTNavigator.h
-rw-r--r--    1 SQLI  staff   393B 12 aoû 17:39 RCTNavigatorManager.h
-rw-r--r--    1 SQLI  staff   486B 12 aoû 17:39 RCTNetInfo.h
-rw-r--r--    1 SQLI  staff   1,9K 12 aoû 17:39 RCTNetworkTask.h
-rw-r--r--    1 SQLI  staff   940B 12 aoû 17:39 RCTNetworking.h
-rw-r--r--    1 SQLI  staff   456B 12 aoû 17:39 RCTNullability.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTParserUtils.h
-rw-r--r--    1 SQLI  staff   3,1K 12 aoû 17:39 RCTPerformanceLogger.h
-rw-r--r--    1 SQLI  staff   728B 12 aoû 17:39 RCTPicker.h
-rw-r--r--    1 SQLI  staff   389B 12 aoû 17:39 RCTPickerManager.h
-rw-r--r--    1 SQLI  staff   519B 12 aoû 17:39 RCTPointerEvents.h
-rw-r--r--    1 SQLI  staff   7,2K 12 aoû 17:39 RCTProfile.h
-rw-r--r--    1 SQLI  staff   395B 12 aoû 17:39 RCTProgressViewManager.h
-rw-r--r--    1 SQLI  staff   390B 12 aoû 17:39 RCTRawTextManager.h
-rw-r--r--    1 SQLI  staff   1,2K 12 aoû 17:39 RCTRedBox.h
-rw-r--r--    1 SQLI  staff   520B 12 aoû 17:39 RCTRefreshControl.h
-rw-r--r--    1 SQLI  staff   397B 12 aoû 17:39 RCTRefreshControlManager.h
-rw-r--r--    1 SQLI  staff   778B 12 aoû 17:39 RCTResizeMode.h
-rw-r--r--    1 SQLI  staff   786B 12 aoû 17:39 RCTRootShadowView.h
-rw-r--r--    1 SQLI  staff   5,2K 12 aoû 17:39 RCTRootView.h
-rw-r--r--    1 SQLI  staff   889B 12 aoû 17:39 RCTRootViewDelegate.h
-rw-r--r--    1 SQLI  staff   667B 12 aoû 17:39 RCTRootViewInternal.h
-rw-r--r--    1 SQLI  staff   4,2K 12 aoû 17:39 RCTSRWebSocket.h
-rw-r--r--    1 SQLI  staff   2,5K 12 aoû 17:39 RCTScrollView.h
-rw-r--r--    1 SQLI  staff   538B 12 aoû 17:39 RCTScrollViewManager.h
-rw-r--r--    1 SQLI  staff   875B 12 aoû 17:39 RCTScrollableProtocol.h
-rw-r--r--    1 SQLI  staff   592B 12 aoû 17:39 RCTSegmentedControl.h
-rw-r--r--    1 SQLI  staff   399B 12 aoû 17:39 RCTSegmentedControlManager.h
-rw-r--r--    1 SQLI  staff   432B 12 aoû 17:39 RCTShadowRawText.h
-rw-r--r--    1 SQLI  staff   1,7K 12 aoû 17:39 RCTShadowText.h
-rw-r--r--    1 SQLI  staff   8,3K 12 aoû 17:39 RCTShadowView.h
-rw-r--r--    1 SQLI  staff   845B 12 aoû 17:39 RCTSlider.h
-rw-r--r--    1 SQLI  staff   389B 12 aoû 17:39 RCTSliderManager.h
-rw-r--r--    1 SQLI  staff   481B 12 aoû 17:39 RCTSourceCode.h
-rw-r--r--    1 SQLI  staff   588B 12 aoû 17:39 RCTStatusBarManager.h
-rw-r--r--    1 SQLI  staff   503B 12 aoû 17:39 RCTSwitch.h
-rw-r--r--    1 SQLI  staff   389B 12 aoû 17:39 RCTSwitchManager.h
-rw-r--r--    1 SQLI  staff   583B 12 aoû 17:39 RCTTabBar.h
-rw-r--r--    1 SQLI  staff   857B 12 aoû 17:39 RCTTabBarItem.h
-rw-r--r--    1 SQLI  staff   393B 12 aoû 17:39 RCTTabBarItemManager.h
-rw-r--r--    1 SQLI  staff   389B 12 aoû 17:39 RCTTabBarManager.h
-rw-r--r--    1 SQLI  staff   485B 12 aoû 17:39 RCTText.h
-rw-r--r--    1 SQLI  staff   572B 12 aoû 17:39 RCTTextDecorationLineType.h
-rw-r--r--    1 SQLI  staff   1,2K 12 aoû 17:39 RCTTextField.h
-rw-r--r--    1 SQLI  staff   393B 12 aoû 17:39 RCTTextFieldManager.h
-rw-r--r--    1 SQLI  staff   387B 12 aoû 17:39 RCTTextManager.h
-rw-r--r--    1 SQLI  staff   1,4K 12 aoû 17:39 RCTTextView.h
-rw-r--r--    1 SQLI  staff   391B 12 aoû 17:39 RCTTextViewManager.h
-rw-r--r--    1 SQLI  staff   526B 12 aoû 17:39 RCTTiming.h
-rw-r--r--    1 SQLI  staff   902B 12 aoû 17:39 RCTTouchEvent.h
-rw-r--r--    1 SQLI  staff   532B 12 aoû 17:39 RCTTouchHandler.h
-rw-r--r--    1 SQLI  staff   3,8K 12 aoû 17:39 RCTUIManager.h
-rw-r--r--    1 SQLI  staff   1,4K 12 aoû 17:39 RCTURLRequestDelegate.h
-rw-r--r--    1 SQLI  staff   1,9K 12 aoû 17:39 RCTURLRequestHandler.h
-rw-r--r--    1 SQLI  staff   6,1K 12 aoû 17:39 RCTUtils.h
-rw-r--r--    1 SQLI  staff   3,1K 12 aoû 17:39 RCTView.h
-rw-r--r--    1 SQLI  staff   773B 12 aoû 17:39 RCTViewControllerProtocol.h
-rw-r--r--    1 SQLI  staff   4,7K 12 aoû 17:39 RCTViewManager.h
-rw-r--r--    1 SQLI  staff   556B 12 aoû 17:39 RCTWebSocketExecutor.h
-rw-r--r--    1 SQLI  staff   483B 12 aoû 17:39 RCTWebSocketManager.h
-rw-r--r--    1 SQLI  staff   445B 12 aoû 17:39 RCTWebSocketModule.h
-rw-r--r--    1 SQLI  staff   679B 12 aoû 17:39 RCTWebSocketProxy.h
-rw-r--r--    1 SQLI  staff   565B 12 aoû 17:39 RCTWebSocketProxyDelegate.h
-rw-r--r--    1 SQLI  staff   1,2K 12 aoû 17:39 RCTWebView.h
-rw-r--r--    1 SQLI  staff   390B 12 aoû 17:39 RCTWebViewManager.h
-rw-r--r--    1 SQLI  staff   1,0K 12 aoû 17:39 RCTWrapperViewController.h
-rw-r--r--    1 SQLI  staff   408B 12 aoû 17:39 RCTXCAssetImageLoader.h
-rw-r--r--    1 SQLI  staff   626B 12 aoû 17:39 UIView+Private.h
-rw-r--r--    1 SQLI  staff   2,3K 12 aoû 17:39 UIView+React.h
-rw-r--r--    1 SQLI  staff   7,7M 12 aoû 17:39 libReact.a

Any idea ?

**Comment by parkerdan** [comment]
@nartawak, are you using CocoaPods?  This answer might do the trick along with restarting xcode, and clean.  https://github.com/ivpusic/react-native-image-crop-picker/issues/21#issuecomment-235785183
