### ISSUE TITLE
[StyleInspector] Warning: Each child in an array or iterator should have a unique “key” prop. Check the render method of `StyleInspector`

### ISSUE THREAD

**Issue by af7** [facebook/react-native#5491]
I receive these warnings when debugging my React Native application in Chrome (the app being installed on an actual device).

- Warning: Each child in an array or iterator should have a unique “key” prop. Check the render method of `StyleInspector`

- Warning: Each child in an array or iterator should have a unique “key” prop. Check the render method of `ElementProperties`

**Comment by satya164** [comment]
Do you have code sample which can reproduce this issue?

**Comment by petrbrzek** [comment]
I've also seen those in iOS simulator when opening inspector. When I close it it's gone.

**Comment by af7** [comment]
I cannot give specific code because it is happening almost everywhere when I open the Inspector (on simulator too, not only on the device).

**Comment by satya164** [comment]
I can't seem to reproduce this with master or 0.18, so if you can track down the specific code it'll be a lot helpful.

**Comment by ide** [comment]
Should be fixed in master with https://github.com/facebook/react-native/commit/c1aed7ba41246ff250e7aebac2c5ee2532c14868. We'll reopen this issue if it's still present.
