### ISSUE TITLE
0.18 document is not defined when debugging in Chrome Canary 

### ISSUE THREAD

**Issue by mauron85** [facebook/react-native#5498]
I've same problem.

react-native 0.18
node v5.4.0
OSX 10.11.3
Xcode 7.2
Chrome Canary: 50.0.2628.0 canary (64-bit)

In my case exception is caught in socket.io.js lib on [this line](https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L2733)

```
/**
 * Load `namespaces`.
 *
 * @return {String} returns the previously persisted debug modes
 * @api private
 */

function load() {
  var r;
  try {
    r = exports.storage.debug;
  } catch(e) {}
  return r;
}
```

The exception is raised because **exports.storage** is undefined

PS: App is working normally, when not debugging in Chrome 

![image](https://cloud.githubusercontent.com/assets/359450/12530688/00a78d6c-c1e7-11e5-90bf-215b6d2b1d9d.png)

**Comment by satya164** [comment]
React Native doesn't have DOM, so you should not rely on the `document` object. When connected to Chrome debugger, React Native runs in a `WebWorker` which doesn't have a `document` object either.

You should disable JSONP with socket.io so that it doesn't rely on `document`.

**Comment by mauron85** [comment]
Makes sense. Thanks
