### ISSUE TITLE
[Question] Use UIWebView/WebView to layout components

### ISSUE THREAD

**Issue by bartq** [facebook/react-native#5499]
Just wondering how hard would it be to use UIWebView in iOS or WebView on Android to use modern HTML/CSS3 capabilities to layout elements and them map their positions back to native components? With it we could use pure CSS3 to calculate positions and then read them with JS and pass to native area? Of course using custom elements inside HTML, for clarity.
What do you think?

**Comment by satya164** [comment]
Interesting idea, but I think it'll be wasteful to run an entire webview for this. Also you'll have to calculate the positions on everyframe during any user interaction like scrolling, or animations. Which will be immensly slow than directly calculating the values.

**Comment by bartq** [comment]
I'm not sure it should be done on every frame... You can scroll natively after layouting. Can you spot other problems?

**Comment by satya164** [comment]
May be not for scroll, but for any kind of animation, gestures etc., you'll
need to calculate frames every second.

If React Native depends on the DOM to render everything (which is not very
fast on a mobile), then copy coordinates and does the rendering again,
it'll be extremely slow.
