### ISSUE TITLE
TouchableWithoutFeedback's onLongPress doesn't work while debugging in Chrome

### ISSUE THREAD

**Issue by raigfp** [facebook/react-native#5516]
```
<TouchableWithoutFeedback
  onLongPress={...}
>
  ...
</TouchableWithoutFeedback>
```
Just nothing happens
With "onPress" or without Chrome debugging works fine

react-native 0.1.7 (android app)

**Comment by mkonicek** [comment]
iOS or Android? Anything you see in the logs?

**Comment by raigfp** [comment]
Android, which logs?

**Comment by satya164** [comment]
Seems to be same as this - #4470
