### ISSUE TITLE
[iOS] Supporting RCTPromiseRejectBlock change in a back compat way

### ISSUE THREAD

**Issue by lostintangent** [facebook/react-native#5524]
Now that the RCTPromiseRejectBlock typedef has been [changed](https://github.com/facebook/react-native/commit/0c5f279c9df869db2afb3e1d92a54e6d930551ad#diff-6dc01074330d7af8d99288cad5a021b7R40) to accept three arguments instead of one, what is the recommended solution for native module methods to return promises in a way that supports 0.19.0, but in a backward compatible way? 

This is probably an Objective-C question, but it's not clear how to invoke the reject block in a way that can support both signatures, depending on the version of the parent project's React Native version.

Additionally, should this change be added to the list of breaking changes for the 0.19.0-RC release? Presumably there are numerous existing native modules using promises that will begin having compilation problems for apps that upgrade to RN 0.19.0-RC.

**Comment by ide** [comment]
There will sometimes be breaking changes and the answer to this is to update your obj c modules and require people to use a new version of React Native. Only the most recent release is supported and even that is a hand wavy statement because Facebook is always on master.

As for this specific issue I think we should actually revert to the old signature and read properties off of the NSError or userInfo to get its code and message, and define a helper function that lets you create a new NSError from and existing one and specify a new code and message.

**Comment by lostintangent** [comment]
I would definitely vote for reverting this change. I can definitely appreciate the need to make breaking changes at some point, but it seems unfortunate for module developers to have to support different versions for 0.19.0 and pre 0.19.0, for a change that could be achieved in other ways.

**Comment by satya164** [comment]
This change actually coincides with similar change on Android, which allowed specifying only error message previously.

BTW, you don't have to support both with one version. People just have to install an older version of the module instead of the latest (which you can document). Just sayin'.

**Comment by lostintangent** [comment]
@satya164 I'm fully aware of that solution, but it's a pretty heavy-handed workaround, that I'd prefer not to do unless it was absolutely necessary. If I could fix a bug or ship a new feature to a native module, without requiring users to upgrade their React Native dependency, that would be much more ideal. Upgrading platform versions isn't exactly "free" (e.g. you may need to do a bunch of testing again, the RN upgrade may have broken other modules you were using).

**Comment by geof90** [comment]
@ide's solution sounds like a good compromise to me!

**Comment by lostintangent** [comment]
Closing this bug since the breaking change made its way into 0.19.0, so it's a moot discussion :)
