### ISSUE TITLE
org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:bundleReleaseJsAndAssets'

### ISSUE THREAD

**Issue by deju** [facebook/react-native#5528]
I got the error When i created apk.

    Executing task ':app:bundleReleaseJsAndAssets' (up-to-date check took 3.171 secs) due to:
	  Output file /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/assets/release/index.android.bundle has changed.
	Starting process 'command 'react-native''. Working directory: /Users/tudeju/Project/react/JJTest Command: react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/assets/release/index.android.bundle --assets-dest /Users/tudeju/Project/react/JJTest/android/app/build/intermediates/res/merged/release
	:app:bundleReleaseJsAndAssets FAILED
	:app:bundleReleaseJsAndAssets (Thread[Daemon worker Thread 9,5,main]) completed. Took 3.185 secs.

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':app:bundleReleaseJsAndAssets'.
	> A problem occurred starting process 'command 'react-native''

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

	BUILD FAILED

	Total time: 18.278 secs
	Stopped 0 compiler daemon(s).
	Received result CommandFailure[value=org.gradle.launcher.exec.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:bundleReleaseJsAndAssets'.] from daemon DaemonInfo{pid=68357, address=[fcf0a51c-b0d3-42da-8780-034150dcfe48 port:52043, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=e83b1e6a-98c6-4893-8131-eb83fae3bd16,javaHome=/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home,daemonRegistryDir=/Users/tudeju/.gradle/daemon,pid=68357,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]}.
	

It was ok yesterday. I restarted the computer this morning.
How can i fix it?

**Comment by deju** [comment]
@facebook-github-bot  I asked on StackOverflow. [Qusetion Link](http://stackoverflow.com/questions/34986320/org-gradle-internal-exceptions-locationawareexception-execution-failed-for-task). Waiting for the answer. :)

**Comment by deju** [comment]
react-native: 0.17.0

It is ok when i just create bundle file.

The screenshot:

<img width="639" alt="0125" src="https://cloud.githubusercontent.com/assets/1439939/12544804/009420b4-c378-11e5-8416-2bb5321030b1.png">

**Comment by deju** [comment]
It is ok when i restarted my Mac.

Maybe the environment has some problems. Try to restart your computer If your script run ok yesterday.

**Comment by kohver** [comment]
I don't need to restart your mac, my workaround is:
```shell
$ ps aux | grep gradle # get pid
$ kill 81827 # kill it!
```
