### ISSUE TITLE
setVisibility on android native view module

### ISSUE THREAD

**Issue by soxunyi** [facebook/react-native#5531]
I use android native view in js file，If a sub view 'mViewXXX' of native view is ```setVisibility(View.GONE)``` before render on screen， and click other button of native view to show mViewXXX（using ```setVisibility(VISIBLE)```）, but mViewXXX is not show on screen. And I found its width and height are both zero, but its visibility is VISIBLE. Why from ```setVisibility(GONE)``` to ```setVisibility(VISIBLE)``` not work? Anyone encounter this issue?

**Comment by satya164** [comment]
Can you give an example and code sample on what are you trying to achieve?

**Comment by soxunyi** [comment]
@satya164   
I submit demo project as follows：https://github.com/soxunyi/reactnative_android_nativeview_visibility_issue

Please run react-native run-android, then click button ’Click me!‘ on home page, but the right button can not be shown. You can see the following code in MyView.java
```
Button bt1 = (Button) view.findViewById(R.id.btn_test1);
        final Button bt2 = (Button) view.findViewById(R.id.btn_test2);
        bt1.setOnClickListener(new OnClickListener() {
            @Override public void onClick(View v) {
                bt2.setVisibility(View.VISIBLE);
                Toast.makeText(mReactContext, "Button 2 should be shown! But not shown! Why?", Toast.LENGTH_LONG).show();
            }
        });
```
Thanks

**Comment by satya164** [comment]
@facebook-github-bot stackoverflow

**Comment by satya164** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@soxunyi have you found out why? I think I may have encounter this issue as well in RN 0.52.
