### ISSUE TITLE
[RCTSRWebSocket retain]: message sent to deallocated instance

### ISSUE THREAD

**Issue by NSKevin** [facebook/react-native#5533]
Crash

![image](https://cloud.githubusercontent.com/assets/1697281/12547881/c17084d4-c38d-11e5-83c1-5b2c087e4e49.png)

![image](https://cloud.githubusercontent.com/assets/1697281/12544118/ceb32f00-c371-11e5-8016-2587d4922558.png)

**Comment by NSKevin** [comment]
anybody?

**Comment by NSKevin** [comment]
When the app run, it will crash for a while. But I don't know why

**Comment by epaga** [comment]
Yes I get this, too. Best to upvote https://productpains.com/post/react-native/crash-in-rctsrwebsocketm so they see it.

**Comment by javache** [comment]
Same as #5198.
