### ISSUE TITLE
Expose message attribute on ActionSheetIOS

### ISSUE THREAD

**Issue by bradbumbalough** [facebook/react-native#5537]
Hello,

I noticed with the upgrade of `ActionSheetIOS` to `UIAlertController`, we now have the ability to pass a `message` prop... currently though it's set to `nil` in RCTActionSheetManager.m. Is there a reason to not expose message? if not, would you accept a PR to implement this? I believe it would only work in iOS 8+ (according to the [UIActionSheet class reference](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIActionSheet_Class/index.html)).

Version: `0.18.0`

Thanks!

**Comment by janicduplessis** [comment]
I don't think there's any reason not to, you can submit a PR to add the prop. Maybe just mention in the doc that it only works on iOS 8+.

**Comment by grabbou** [comment]
That has been already fixed in https://github.com/facebook/react-native/commit/928fd0d60512566b4047f709431ee565499e506f#diff-b6ec6c60921763a2cc180dd8ed24ba35
