### ISSUE TITLE
[Image] Does not fade in on Android unless borderRadius is set

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#5545]
[See example gifv here](http://imgur.com/2RAqeND)

``` javascript
'use strict';

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Image,
  Text,
  View
} from 'react-native';

class AndroidImageFadeTest extends Component {
  render() {
    let reactImage = (
      <Image
        source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}}
        fadeDuration={5000}
        style={styles.image} />
    );

    let catImage = (
      <Image
        source={{uri: 'https://www.petfinder.com/wp-content/uploads/2012/11/140272627-grooming-needs-senior-cat-632x475.jpg'}}
        fadeDuration={5000}
        style={[styles.image, {borderRadius: 1}]} />
    );

    return (
      <View style={styles.container}>
        <View style={{flexDirection: 'row'}}>
          {reactImage}
          {reactImage}
          {reactImage}
        </View>

        <View style={{flexDirection: 'row'}}>
          {catImage}
          {catImage}
          {catImage}
        </View>

        <View style={{flexDirection: 'row'}}>
          {reactImage}
          {reactImage}
          {reactImage}
        </View>

        <View style={{flexDirection: 'row'}}>
          {catImage}
          {catImage}
          {catImage}
        </View>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  image: {
    width: 100,
    height: 100,
  },
});

AppRegistry.registerComponent('AndroidImageFadeTest', () => AndroidImageFadeTest);
```

**Comment by brentvatne** [comment]
cc @balazsbalazs @mkonicek

**Comment by mkonicek** [comment]
Wow good find! I know little about the implementation, here it is: https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java

Maybe Fresco does some special casing. Pinged the Fresco oncall.

**Comment by balazsbalazs** [comment]
The one thing that stands out is that we're not making the view dirty. I don't know much about ReactNative so not sure when the setters are called but it seems that unless we mark something as dirty the settings won't be applied.
Eg. look at the ReactImageView.setFadeDuration

@mkonicek happy to pair with you on this but it seems that the problem is in ReactImageView

**Comment by mkonicek** [comment]
@brentvatne does looking at `ReactImageView.setFadeDuration` help?

**Comment by brentvatne** [comment]
@mkonicek - I tried setting that manually and it didn't have any impact, the only way it fades is if I set borderRadius specifically

**Comment by mkonicek** [comment]
I'll try to find some time to look into it.

**Comment by odino** [comment]
BTW same thing happens when the image has some content ie.

```
        <Image fadeDuration={200} style={[styles.bgImage, {borderRadius: 1}]} source={someImage} >
          <View>
             ...
          </View>
        </Image>
```

**Comment by mkonicek** [comment]
Ah, I didn't get to this. @brentvatne do you remember if we found a solution?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
