### ISSUE TITLE
[Feature] add option to enable Redbox msg in production?

### ISSUE THREAD

**Issue by qbig** [facebook/react-native#5547]
Just an idea. Not sure if it's an 'shortcut' or 'detour' or 'dead end'.

Currently, error logging in Production is not very straightforward with RN, as reflected by a few others issues/stackoverlfow questions/my own very limited experience. Sentry seems promising, but requires uploading of bundle file and sourcemap for every deployment. So not as ideal either comparing to native ios/android development.(too spoiled by Crashlytics I guess)

But during development Redbox is fanstastic!  So just wondering if it is possible to enable Redbox in Production, but instead of throw it to users' face, log the exception infos(**directly sourcemapped in users' device like Redbox**) etc, so that Crashlytics or other native logging service would be able to pick them up.

Another potential benefits of this approach is that, it would be able to catch everything, comparing to Sentry/Raven, which is essentially a js client and would be helpless when exceptions happens in native objective-c/java land.

Is this an dumb idea ? If not, would PR be welcome?

**Comment by qbig** [comment]
Hi @satya164 any thoughts on this ?

**Comment by cosmith** [comment]
What I do which is in the same vein is add this to my main .js file:

```js
if (__DEV__ === false) {
    var ErrorUtils = require("ErrorUtils");
    var Flurry = require("Flurry");
    ErrorUtils.setGlobalHandler((error, isFatal) => {
        Flurry.logError(error, isFatal);
    });
}
```

It kind of works but no sourcemap... I have to hunt through the generated jsbundle to figure out the errors most of the time.

**Comment by javache** [comment]
The red box, as the UI mechanism is disabled, but all the other error handling is still in place.

You can use the RCTExceptionsManager API to catch all these errors on the native side and report them to your server. You would need to upload your sourcemap file to that server as well for symbolication, but this is no different from uploading your symbols for native crash reporting.

**Comment by qbig** [comment]
thanks @cosmith that is probably the way to go. Yet sourcemap is still the main pain point here.

@javache What I hope to achieve is to "reuse" the source-map mechanism of red box, so that I could have symbolication within the app js environment, and upload to server afterwards. Is that possible ? Or is it because the symbolication happening in the packager and we could not do it?

**Comment by jsierles** [comment]
@facebook-github-bot feature
