### ISSUE TITLE
how to load more items in the listview when pull up

### ISSUE THREAD

**Issue by bluesky0109** [facebook/react-native#5550]
I use onEndReached to load more 
  _onEndReached(){
    console.log('\n\n onEndReached \n\n');
    //正在加载中
    if (this.state.isLoadingTail) {
      // We're already fetching or have all the elements so noop
      return;
    }
    this._loadMoreData();
  }

  render() {
    return (
      <View style={styles.container}>
        {this._renderOperatesView()}
          <ListView
            contentContainerStyle={styles.list}
            dataSource={this.state.dataSource}
            renderRow={(rowData, sectionID, rowID) => this._renderRow(rowData, rowID)}
            renderSeparator={this._renderSeparator.bind(this)}
            renderHeader={this._renderHeader.bind(this)}
            renderFooter={this._renderFooter.bind(this)}
            onEndReached={this._onEndReached.bind(this)}/>
      </View>
    );
  }

but I do not scroll(pull up) the listview,onEndReached was called,end when load more data,onEndReached trigger again, and then call load more, cyclic call onEndReached

**Comment by wilcosheh** [comment]
I come across this problem too..

**Comment by hufeng** [comment]
you can ,

```javascript
onEndReached(e) {
  onsole.log('\n\n onEndReached \n\n');
  //正在加载中
  if (!e && this.state.isLoadingTail) {
    // We're already fetching or have all the elements so noop
    return; 
   }
   this._loadMoreData();
  }
}
```
