### ISSUE TITLE
Using NodeJS modules packages via Browserify?

### ISSUE THREAD

**Issue by pori** [facebook/react-native#5555]
I am currently attempting to use packages that depend on core NodeJS modules like `events` and `timer`. However, these don't work as Packager does not provide shims for them, like Browserify does. 

Is it possible to use Browserify too? At least, is there some possible configuration/workflow that could avoid modifying original sources with polyfills?

If not, this would be a great step towards compatibility with node packages in general (save for any with binary dependencies, of course).

**Comment by vespakoen** [comment]
You can check what browserify is using for these here:
https://github.com/substack/node-browserify/blob/master/lib/builtins.js
And use those instead.

events: https://github.com/Gozala/events
timers: https://github.com/jryans/timers-browserify

**Comment by jsierles** [comment]
Closing this in favor of discussion on the meta-issue here: #6253
