### ISSUE TITLE
[website][docs] Include class methods in generated docs

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#5557]
For example `DrawerLayoutAndroid` has the method `openDrawer`:
https://github.com/facebook/react-native/blob/master/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js

But we only generate docs for propTypes:
https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#content

**Comment by janicduplessis** [comment]
I'll work on this this week :)

**Comment by janicduplessis** [comment]
Done in #6890 

@facebook-github-bot close

**Comment by janicduplessis** [comment]
@facebook-github-bot close
