### ISSUE TITLE
Date Picker - Only pick year and month

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/react-native#5558]
I'm currently using `DatePickerIOS` to select a specific date, down to the individual day.  However, I want to only pick the month and year.  I've looked through the docs and issues and can't find any examples.  Is it possible to do this with `DatePickerIOS`?

**Comment by gvaish** [comment]
@jacob-israel-turner `UIDatePicker` view does not support that mode.

You can either write a custom view or just use two `PickerIOS`.
