### ISSUE TITLE
Serializable Animated API

### ISSUE THREAD

**Issue by alinz** [facebook/react-native#5564]
There is a section in doc that mentions

> Note that Animated is designed to be fully serializable so that animations can be run in a high performance way, independent of the normal JavaScript event loop. 

How would someone serialize animated configuration and run it in backend/native in high performance way? Everyone is talking about it but there is no simple example of it. Even @sahrens says at [this video](https://www.youtube.com/watch?v=xDlfrcM6YBk&feature=youtu.be&t=161).

**Comment by satya164** [comment]
It's not implemented yet. Check - https://productpains.com/post/react-native/offload-some-animations-from-js-thread-for-better-perf/
