### ISSUE TITLE
Room for improvement on cloneWithRowsAndSections?

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5572]
I find this to be extremely confusing the way one has to set up the section ID array and row ID array to pass into this function. It feels like a real brain-buster, and I don't think it should be. I was wondering if the team is open to ideas on refining this and making it much more straightforward.

**Comment by ffxsam** [comment]
Like for instance, why can't we pass just a single data blob like this?

```
[
  {
    section: 'Fruits',
    rows: [
      {
        name: 'Apple',
        color: 'red'
      },
      {
        name: 'Orange',
        color: 'orange'
      }
    ]
  },
  {
    section: 'Vegetables',
    rows: [
      {
        name: 'Celery',
        color: 'green'
      },
      {
        name: 'Carrot',
        color: 'orange'
      }
    ]
  }
]
```

**Comment by ide** [comment]
That could work - write a helper function that takes in that data structure and returns a data source and publish your code to npm.

**Comment by ffxsam** [comment]
Hang on.. if I'm understanding the code, it seems like the section ids and row ids arguments for `cloneWithRowsAndSections` are optional. If you pass a data blob, probably structured similarly to the above, it'll handle all that for you. I'm testing now.

**Comment by ffxsam** [comment]
I tried following the format specified here:

https://github.com/facebook/react-native/blob/0e8b207cc34f230eb2cced3981734b522b601817/Libraries/CustomComponents/ListView/ListViewDataSource.js#L100-L110

And just passed a data blob into `cloneWithRowsAndSection` (no section IDs or row IDs), and all formats failed. Something's not right. In fact, this should work:

    { sectionID_1: [ <rowData1>, <rowData2>, ... ], ... }

And so I tried doing the following:

      dataBlob = {
        'Fruits': [{name: 'apple'}, {name: 'orange'}],
        'Veggies': [{name: 'broccoli'}]
      };

      this.setState({
        dataSource: this.state.dataSource.cloneWithRowsAndSections(
          dataBlob
          //sectionIds,
          //rowIds
        ),
        loading: false
      });

And I get literally thousands of these errors about sticky header out of range.

![screenshot_1_27_16__2_31_am](https://cloud.githubusercontent.com/assets/12532733/12610730/31f454a4-c49e-11e5-88eb-5d897674fc4b.png)

**Comment by Taakn** [comment]
@ffxsam https://github.com/facebook/react-native/issues/1706

**Comment by ffxsam** [comment]
Thanks for that. Still though, it doesn't function as it's supposed to. The source code comments say you can just pass a certain structure in, and that fails. I'll attempt to do a PR once I have some free time.

**Comment by mowi22** [comment]
Any update on this? Im having the same problem. I've tried so many ways and I cant get around thousands of sticky warnings.

**Comment by sscaff1** [comment]
I'm having the same issues too.

**Comment by benadida** [comment]
fwiw, I've had success using a blob with `sectionId` and `rowId` keys, so a map of maps, not a map of arrays. For example:

```
{
  "s1": {
      "row1": {...},
      "row2": {...},
  },
  "s2": {
      "row3": {...},
      "row4": {...}
  }
}

**Comment by lacker** [comment]
I think Ben's workaround here looks pretty good. We want to improve the ListView in general since it's one of the most feedbacked-about components, see a few more details in the roadmap at https://github.com/facebook/react-native/wiki/Roadmap . I am going to close this issue but I think if someone was interested in sending a PR to improve the documentation that would be great.

**Comment by guilhermecvm** [comment]
My personal preference is by using an array of array.
```javascript
const sections = [{ title: 'Married' }, { title: 'Single' }]
const rows = [
  [
    { col1: 'Guilherme', col2: '26'},
    { col1: 'Luiza', col2: '22'}
  ],
  [
    { col1: 'Valentina', col2: '2'},
    { col1: 'Julian', col2: '1'}
  ]
]
const ds = new ListView.DataSource({
  rowHasChanged: (r1, r2) => r1 !== r2,
  sectionHeaderHasChanged : (s1, s2) => s1 !== s2,
  getRowData: (dataBlob, sectionID, rowID) => rows[sectionID][rowID],
  getSectionHeaderData: (dataBlob, sectionID) => sections[sectionID]
})
const dataSource = ds.cloneWithRowsAndSections(rows)
```
