### ISSUE TITLE
why android Image not support capInsets?

### ISSUE THREAD

**Issue by nowaits** [facebook/react-native#5576]
same as title

**Comment by gvaish** [comment]
@nowaits Use 9-Patch PNGs. That's Android image with `capInsets`. Natively, Android `ImageView` doesn't support `capInsets` on the fly.

**Comment by thatsmydoing** [comment]
How are we supposed to use 9-patch images in react-native?

Loading via require('./image.9.png') treats it as a regular image that shows the hints at the edges.

While loading via resources, {uri: 'image'} does load it without the 9patch hints, but it doesn't respect the scaling hints. It just scales it as if it were a regular image without the hints at the edges.

**Comment by yomybaby** [comment]
Is there any news? I can't find user 9-patch image in react-native. :(

**Comment by zhaixiaoou** [comment]
I have the same question. I need use 9-patch image in react-native. how i resolve  it? @gvaish

**Comment by ylquankai** [comment]
I really need it.

**Comment by fencex** [comment]
Try this npm package:
[https://www.npmjs.com/package/react-native-image-capinsets](https://www.npmjs.com/package/react-native-image-capinsets)

Support for Android and iOS platforms!

Thank you, madsleejensen
