### ISSUE TITLE
Android: Image and embedded video in WebView are not shown

### ISSUE THREAD

**Issue by ma94264** [facebook/react-native#5588]
is it because we need to set property

"setMixedContentMode"

for API level 21 and above?
Need to add this in  ReactWebViewManager.Java ?

**Comment by Richard-Cao** [comment]
@satya164

**Comment by Richard-Cao** [comment]
same question +1

**Comment by Richard-Cao** [comment]
`javaScriptEnabledAndroid` work but `javaScriptEnabled` not work on Android.
react-native version: 0.18

**Comment by ma94264** [comment]
@Richard-Cao Thanks man!~ that works...
