### ISSUE TITLE
How to layer Views using Flexbox? (z-index)

### ISSUE THREAD

**Issue by arianitu** [facebook/react-native#559]
I've set a View to absolute and tried to position it on top of a ListView, but it goes underneath. Is there a way to layer things currently? I basically want a dialog on top of a ListView, or a menu on top of a ListView, or a ListView on top a ListView, you get the idea =P

**Comment by arianitu** [comment]
https://github.com/facebook/react-native/issues/131

**Comment by Iragne** [comment]
Well i know it's closed but it's very useful to have these properties bringSubviewToFront and inverse 

See The PR https://github.com/facebook/react-native/pull/1891
