### ISSUE TITLE
[Feature]provide a way to cancel a fetch request

### ISSUE THREAD

**Issue by SuBeibei** [facebook/react-native#5590]
I sent a request using fetch in "componentDidMount", then I try to cancel it in "componentWillUnmount".But I didn't find a way to do it.I notice that in Android NetworkingModule provides method "abortRequest".

**Comment by satya164** [comment]
`fetch` doesn't have a way to cancel the request as per the Promise spec. You can use `XMLHttpRequest` directly if you need to cancel the request.

**Comment by hfossli** [comment]
I would love to see this reopened.

**Comment by superandrew213** [comment]
@hfossli use https://github.com/apentle/react-native-cancelable-fetch

**Comment by ssssssssssss** [comment]
Shall we reopen this for the AbortController? http://mo.github.io/2017/07/24/abort-fetch-abortcontroller-polyfill.html

**Comment by ahmadalfy** [comment]
`fetch` is now cancellable via `AbortController`

The final version of AbortController has been added to the [DOM specification](https://dom.spec.whatwg.org/#aborting-ongoing-activities)
The corresponding PR for the fetch specification is now [merged](https://github.com/whatwg/fetch/pull/523).
