### ISSUE TITLE
Unable to download js bundle

### ISSUE THREAD

**Issue by Hiramxu** [facebook/react-native#5592]
![react-nativeerror](https://cloud.githubusercontent.com/assets/5267692/12636953/75a4d3a2-c5cc-11e5-9195-ac42c8bc8637.png)
 when running react-native run-android, I am getting a red screen on the android emulator, with the following text:
Unable to download JS bundle. Did you forget to start the development server or connect your device?

onResponse 
DevServerHelper.java:191

execute
Call.java:168

run
NamedRunnable.java:33

runWorker
ThreadPoolExecutor.java:1076

run
ThreadPoolExecutor.java:569

run
Thread.java:856

I've changed the Debug server host for device set the ipaddress with port my machine's IP,but still not fixed.

**Comment by qbig** [comment]
@Hiramxu  http://stackoverflow.com/questions/32572399/react-native-android-failed-to-load-js-bundle had a lot of answers here.

**Comment by jiangqqlmj** [comment]
Now you really machine debugging, using computers to keep the same wifi network。
1.you should delete node_modules/react-deep-force-update/.babelrc 
2.if your version is v0.18.1，This path has changed。now you should delete /node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/.babelrc 
plesase see the details

**Comment by TangSirOnGit** [comment]
#5618  maybe useful to you.

**Comment by christopherdro** [comment]
@Hiramxu Did you ever get it up and running?

**Comment by janicduplessis** [comment]
@facebook-github-bot stack-overflow

**Comment by haitang3009** [comment]
Hello there,

I have fixed this issue by the step below:

**if your machine do not install McAfee antivirus, please go to step 2**

if you installed McAfee antivirus, the default port of McAfee log is 8081. You should manual change the port of your react native server

Step 1: go to <your app>\node_modules\react-native\local-cli\server\server.js and change the port 8081 to 8088

const args = parseCommandLine([{

command: 'port',

default: 8088,

type: 'string',

}

Step 2: Create an "assets" folder under "android/app/src/main"

Step 3: in node.js run "react-native start" and navigate to the url "http://localhost:8088/index.android.bundle?platform=android"

**p/s: do not install McAfee antivirus please go with port 8081**

Step 4: save the bundle to assets folder and you are all set. in node.js run "react-native run-android" to view the result

Regards,

Hai Tang
