### ISSUE TITLE
WebView works only if Debug in Chrome is enabled on iPhone 5

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#5594]
WebView works only if Debug in Chrome is enabled on iPhone 5

**Comment by stereodenis** [comment]
https://productpains.com/post/react-native/iphone5-webview-not-working-with-disabled-debug-in-chrome/

**Comment by stereodenis** [comment]
http://stackoverflow.com/questions/35058193/webview-not-working-with-disabled-debug-in-chrome

**Comment by stereodenis** [comment]
http://take.ms/AfXhK

**Comment by stereodenis** [comment]
found solution

**Comment by LRcompany** [comment]
Hi @stereodenis, How solution did you find ?!

**Comment by christopherfowers** [comment]
yeah, LRcompany is right, posting the found solution here would help others. I've been putting in a lot of time to find this with no luck.
