### ISSUE TITLE
[TextInput] Cursor color

### ISSUE THREAD

**Issue by FunnyDevs** [facebook/react-native#5595]
Is possible there isn't any option to change cursor color both Android and iOS???

**Comment by jordanranz** [comment]
I have done it in iOS.  Is this what you mean?

<img width="375" alt="screen shot 2016-01-28 at 1 39 35 pm" src="https://cloud.githubusercontent.com/assets/3868826/12659613/9a3ec978-c5c4-11e5-9d9a-77f1dc5afd75.png">

You would simply have to change the tint color for UITextView

Here is a snippet of the React code:
<img width="454" alt="screen shot 2016-01-28 at 1 42 37 pm" src="https://cloud.githubusercontent.com/assets/3868826/12659730/26dc8b54-c5c5-11e5-802a-3868a43b9dd2.png">

I could work on PR if this is something we want

**Comment by FunnyDevs** [comment]
There isn't any reference to attr tintColor on documentation. 
I have tried it on Android and it doesn't work. Do you have tested it with an Android app?

**Comment by jordanranz** [comment]
The property would have to be bridged.  It is not implemented in React Native.

I am not too familiar with the Android code, but it looks like something would need to be added to the ReactEditText object which extends EditText.  Here is more information regarding what must be done in the Android code to change the cursor color:

http://stackoverflow.com/questions/11649234/change-edittext-cursor-color

**Comment by dmmiller** [comment]
Update for Android as well in https://github.com/facebook/react-native/commit/0c91931adf15fb456e72d08dca872f632661b655

**Comment by FunnyDevs** [comment]
Ok, but this doesn't change android cursor color.

**Comment by dmmiller** [comment]
Correct, this only changes the selectionColor.  Changing the cursor color programmatically looks like you have to use reflection to get the textCursorDrawable and it is probably not worth it.  There is not an API on TextView which will let you adjust it.  iOS just keeps these in sync.

**Comment by FunnyDevs** [comment]
Yes, the only solution is reflection and the code is simple. Why do you think it is probably not worth it? Performance problems??
I think it's a big limitation not allow to change cursor color in Android.

**Comment by dmmiller** [comment]
I worry about performance and the possibility of the underlying member variable changing names.  That said, you can put up a PR if you want and we can look at it.  If you do, I'd keep it the same property as SelectionColor and make it set both selection and cursor like it does on iOS.

**Comment by FunnyDevs** [comment]
Ok, i start a PR. Thanks

**Comment by efkan** [comment]
Actually [this blog](http://android--code.blogspot.com.tr/2015/08/android-edittext-cursor-color.html) says;

> Set the android:textCursorDrawable attribute value to @null, then EditText widget will display text color as cursor color

So, if the cursor color can be changed, performance issues may not be exist. 

```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/rl"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="10dp"
    tools:context=".MainActivity"
    android:background="#ced4cb"
    >
    <!--
        android:textCursorDrawable="@null"
        android:textColor

            Set the android:textCursorDrawable attribute value to @null,
            then EditText widget will display text color as cursor color
    -->
    <EditText
        android:id="@+id/et"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:hint="Input your country"
        android:padding="10dp"
        android:textCursorDrawable="@null"
        />
    <EditText
        android:id="@+id/et_city"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:hint="Input your City"
        android:padding="10dp"
        android:layout_below="@+id/et"
        android:textCursorDrawable="@null"
        android:textColor="#ff0004"
        />
</RelativeLayout>
 
```

![androidedittextcursorcolor](https://cloud.githubusercontent.com/assets/6974198/13488186/587759e0-e128-11e5-9915-b4f11ed15459.png)

![androidedittextcursorcolor2](https://cloud.githubusercontent.com/assets/6974198/13488191/5c83d75c-e128-11e5-87f1-eca17023df09.png)
