### ISSUE TITLE
Import of Component/PropTypes

### ISSUE THREAD

**Issue by mudetroit** [facebook/react-native#5598]
This is simply a question for clarification reasons.

In a react web project you do the following:
```
import React, {Component, PropTypes} from 'react';
import ReactDOM from 'react-dom';

class Foo extends Component {
...
}

ReactDOM.render(<Foo/>);
```

It seems like in React Native even post v0.18 you still do:
```
import React, {Component, PropTypes} from 'react-native';

class Foo extends Component {
...
}
```

Is there some underlying reason for the difference between these two or is it simply a legacy from the old vendored version of React that React Native had?

**Comment by satya164** [comment]
cc @ide

**Comment by ide** [comment]
When `react` is a peer dependency instead of a dependency of `react-native` you will be able to import from `react`. Till then, it's not correct to do so, but will work if you're using npm 3.

**Comment by mudetroit** [comment]
Okay that makes sense, I guess what I am wondering is if at the point it becomes a peer dependency should the export on react-native become deprecated. Mostly wondering in terms of teaching people the interface, and that part is inconsistent at the moment.

**Comment by grabbou** [comment]
As of 0.25 - requiring React api from `react-native` results in a warning and the first snippet you showed is correct. I think it can now be closed.
