### ISSUE TITLE
[Packager] Improve the error message when the packager can't find a module

### ISSUE THREAD

**Issue by ide** [facebook/react-native#5600]
Currently the packager emits errors like this:

> Unable to resolve module XXX from /Users/jd/App/Module.js: Invalid directory /Users/node_modules/XXX

This is confusing and should instead read:

> Unable to resolve module XXX from /Users/xx/App/Module.js: The packager was unable to find this module in its module map or any of the node_modules directories under /Users/xx/App and its parent directories

**Comment by auszone** [comment]
Can I work on this? :)
