### ISSUE TITLE
Image.getSize doesn't work with static images

### ISSUE THREAD

**Issue by manask88** [facebook/react-native#5603]
I've tried
```
Image.getSize('./myimage.png', (width, height) => {
      console.log(width)
 });
```

But doesn't work. It seems to only work with network images. It always complains with this: Failed to get size for image: ./myimage.png

**Comment by miracle2k** [comment]
Related to #2180.

**Comment by janicduplessis** [comment]
I think it was only implemented for network images since you should know the size of the image if it is bundled with your app. If you'd like to have that feature, I suggest you submit a PR.

**Comment by janicduplessis** [comment]
@facebook-github-bot feature

**Comment by markusguenther** [comment]
It seems that no one created a feature request. So if you also want that feature in RN vote here https://react-native.canny.io/feature-requests/p/support-static-images-in-imagegetsize

**Comment by sstur** [comment]
> [...] only implemented for network images since you should know the size of the image if it is bundled with your app.

This would be a nightmare to keep in sync on a medium to large project. I agree that calculating it asynchronously at runtime is not ideal. What I really want is a way to calculate this at BUILD time!

```
import image, {width, height} from './images/goat.png';
```

Does anything like this exist in the ecosystem? Is there any way to plug into the build system to get this info? Maybe using [Haul](https://github.com/callstack-io/haul) since that's built on webpack which is pluggable?

**Comment by idibidiart** [comment]
> [...] only implemented for network images since you should know the size of the image if it is bundled with your app.
This would be a nightmare to keep in sync on a medium to large project.

Yup, it really would be a nightmare.... I doubt the answer is not to ask the framework usetrs to submit a PR, not to say that none of us would but for those who work on RN full time this deserves attention.

**Comment by Oblongmana** [comment]
To add another scenario to this situation - I have images that are not network images, and I can't reasonably be expected to know the size of them. They're being retrieved via an API where I need to authenticate (so I can't just plumb it in as a URI into getSize), so it's being pulled down to the device.  getSize works on iOS, but not android, funnily enough. If there's something I'm missing here, it certainly doesn't seem to be anything documented.

Will give the `resolveAssetSource` approach a try :/

**Comment by andreiciceu** [comment]
This should be re-opened, as there's still no documented way of displaying a *static image*, that's been bundled with the app (e.g. android drawable folder), like so `<Image ... source={{ uri: this.state.selectedQuestion.image }} />`, without knowing its size in advance.
For example, in my app I have lots of  (3000+) multiple choice questions stored in an SQLLite db, each being linked to an image (via a column in the db). The images differ in size and are stored (in android) in the drawable folder.
Not setting the width and height properties, lead to the image not being rendered at all; also, `Image.getSize()` throws a wanring, that the image was not found. Setting the width and height to some values allow the image to be displayed, but it is either cropped or with white-space.

**Comment by andreiciceu** [comment]
@facebook-github-bot /reopen

**Comment by cyphire** [comment]
I've been trying to crop images taken from react-native-camera basically forever... It has never worked.  Just trying to get a square image out of the camera.  None of the approaches have worked and its disappointing that the latest try involves the Image.get_size and ImageEditor.  My images are on the device, having just been taken by the camera.  They aren't static images and they aren't coming down from the network.  Anyone have any idea how to do this after all this time?  If we could get some uniformity in regard to image processing in react-native would be awesome...
