### ISSUE TITLE
[BUG] Redscreen error when TouchRelease triggered on a component no longer in the tree

### ISSUE THREAD

**Issue by eadz** [facebook/react-native#5604]
*Unrecognized signal `RESPONDER_RELEASE` or state `undefined` for Touchable responder `null`*

This issue is triggered by the following:
  - A Touch event on a component ( Keep Pressing  )
  - A state/props update removes the component from the tree and render is performed
  - A Touch Release event. ( When you release the press on the component no longer there )

<img width="314" alt="screen shot 2016-01-29 at 12 55 19 am" src="https://cloud.githubusercontent.com/assets/11939/12663836/1f5eed3c-c623-11e5-92c1-666e8eed00d1.png">

version 0.18.1 of react-native

**Comment by eadz** [comment]
Just to confirm this is an issue on Android as well.

**Comment by kanerogers** [comment]
I'm having this same issue, @eadz!

**Comment by eadz** [comment]
Does my fix work you as well?

**Comment by kanerogers** [comment]
I haven't yet had a chance to have a look - I'll check it out and let you
know!

**Comment by eadz** [comment]
Fix Merged.
