### ISSUE TITLE
Unable to run React-Native android  Awesome project on Android version 4.4 

### ISSUE THREAD

**Issue by deeppatidar** [facebook/react-native#5608]
I am playing my hands on android project and when i running it on android 5 and 6 its working fine but when switched to android version 4 it giving error like 
"reference error can't find variable: _fbBatchedBridge (line 1 in the generated bundle)" and when i reload JS its turn to 
"Unable to download JS bundle. Did you forget to start the development server or connect your device? "

even i started server using "react-native start" but still getting same error.

can any one help at where i 'm wrong. ?

**Comment by christopherdro** [comment]
@deeppatidar You have to enter your ip address manually for anything os version below 5.0
See: [Connect to the local dev server via wifi](https://facebook.github.io/react-native/docs/running-on-device-android.html#configure-your-app-to-connect-to-the-local-dev-server-via-wi-fi)
