### ISSUE TITLE
Image shows by its real size

### ISSUE THREAD

**Issue by peacepassion** [facebook/react-native#5611]
I'm an android developer and learning RN now. It is great. But I encounter a problem. Please help.

How can I present an image by its real size including width and height? Just like following android xml code.
 ```xml
<ImageView 
    layout_width="wrap_content"
    layout_height="wrap_content"
    src="@drawable/image" 
/>
```

**Comment by satya164** [comment]
```js
<Image source={{ uri: ... }} style={{ height: null, width: null }} />
```

Please use stackoverflow for such questions in the future.

**Comment by peacepassion** [comment]
@satya164 Thanks. I will.
