### ISSUE TITLE
[Image] Can't display avatar with HTTP 301

### ISSUE THREAD

**Issue by just4fun** [facebook/react-native#5616]
I created an [iOS APP](https://github.com/just4fun/uestc-bbs-react-native) for university BBS (built in PHP) with React Native 0.14.

When I send request to fetch user info, I will get a record including filed `avatar`, which has value like `http://bbs.uestc.edu.cn/uc_server/avatar.php?uid=32044&size=middle`, and I assigned it to `source` filed of `<Image>` like below,

```javascript
<Image
  style={styles.avatar}
  source={{uri: authrization.avatar}} />
```

**Updated recently:**

**~~It seems like a PHP method (I'm not familiar with PHP), since the value of `avatar` will become `http://bbs.uestc.edu.cn/uc_server/data/avatar/000/03/20/44_avatar_middle.jpg` if I type the original value in the browser.~~**

**I tried to display `http://bbs.uestc.edu.cn/uc_server/avatar.php?uid=32044&size=middle` in html with `<img> tag`, it will get 301 code and then get the right picture with extension.**

However, the avatar is not displayed sometimes with RN. See the [screenshot](http://g.recordit.co/Z3RyLrdFTq.gif).

**Seems like RN didn't support the redirect well even in latest 0.21.**

Does the `<Image>` component only support static picture file which ends with `jpg|png|gif`?

**Comment by k7k0** [comment]
@just4fun I'm having the same problem, images without extension aren't showed. Did you resolve the issue?

**Comment by just4fun** [comment]
@k7k0 No, there is no feedback both on Github issue and [StackOverflow](http://stackoverflow.com/questions/35115476/react-native-image-cant-work-sometimes).

@ide Any ideas?

**Comment by k7k0** [comment]
@just4fun on my case it turned to be a file-format problem, it's a WebP file instead of regular JPG. Not supported on iOS yet  http://stackoverflow.com/questions/34815053/load-remote-image-without-extension/34825697#34825697

**Comment by just4fun** [comment]
@k7k0 thank you, in my case, there is no any extension, the url seems like a PHP method.

**Comment by grabbou** [comment]
I think the issue here is not the type, but redirection that happens and that might not be supported in RN itself.

**Comment by just4fun** [comment]
@grabbou yes, there is no extension but redirect in my case, I also think it's not supported well in RN. But sometimes it works well, it's weird.

**Comment by just4fun** [comment]
I tried to display `http://bbs.uestc.edu.cn/uc_server/avatar.php?uid=32044&size=middle` in html with `<img>` tag, it will get `301` code and then get the right picture with extension.

Seems like RN didn't support the redirect well even in latest 0.21.

**Comment by janicduplessis** [comment]
@facebook-github-bot bugfix

**Comment by hayeah** [comment]
#7262 should fix this problem.

**Comment by just4fun** [comment]
@hayeah Thank you, but I found your PR has been closed?

**Comment by grabbou** [comment]
GitHub bot closes PRs and merges them manually - see the commit reference above :)

**Comment by just4fun** [comment]
@grabbou Gotcha, thanks.
@hayeah I'm gonna learn Objective-C if FB can't support this feature, since this issue avoid me to submit my RN app to App Store. Thanks again.

**Comment by hayeah** [comment]
@just4fun the PR is merged
