### ISSUE TITLE
[TextInput] When maxLength is full automatically focus next field

### ISSUE THREAD

**Issue by xcarpentier** [facebook/react-native#5617]
Hello RN awesome team !

I have an issue in my app with TextInput for a bank card number (error because user not type all number 16 digits).

So I would like to cut CB number on 4 TextInputs and focus automatically on next field after filled the 4 digits. (as already seen it in the web app)

But when I focused the next field, the current became empty, even if the state is correctly set.

Do you have an idea about how can I do that or is it impossible ?

ie. see the onChangeText on this example (exp date actually) :

```
<TextInput
    ref='card_exp_date_mm'
    style={[styles.inputTxt, {width: 30, flex: 0}]}
    value={this.state.cardExpDateMonth}
    keyboardType='numbers-and-punctuation'
    placeholder='MM'
    returnKeyType='next'
    clearTextOnFocus={false}
    autoCorrect={false}
    placeholderTextColor={Constants.placeholderTextColor}
    maxLength={2}
    enablesReturnKeyAutomatically={true}
    blurOnSubmit={false}
    onChangeText={text => {
      this.setState({cardExpDateMonth: text})
      //console.log('onChangeText', this.refs.card_exp_date_mm)
      if(text && text.length == 2){
        this.refs.card_exp_date_aa.focus();
      }
    }}
    onSubmitEditing={()=>this.refs.card_exp_date_aa.focus()}/>
```

Thanks by advance for your help.

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow

**Comment by xcarpentier** [comment]
Already did it : http://stackoverflow.com/questions/35085917/textinput-when-maxlength-is-full-automatically-focus-next-field

**Comment by browniefed** [comment]
@xcarpentier sorry about that, we did an issue clean up over the weekend. We are trying to keep react-native github issues focused on actual bugs. 
That being said .22 was just released, I'd recommend upgrading to that and seeing if it fixes your issues. 

If that doesn't create a simple reproduction on http://rnplay.org  so it is easier for people to run and debug. Without full code to look at it is very difficult to help you.

**Comment by Raktima** [comment]
@xcarpentier How did u solve your issue? Please explain. I followed ur link to stackoverflow. It does throw some light on how to move to next text field. But how do i check if max length is reached?
