### ISSUE TITLE
AlertIOS.prompt() breaks when passing in type or defaultValue

### ISSUE THREAD

**Issue by coderdave** [facebook/react-native#5621]
It looks like `AlertIOS.prompt()` is fundamentally broken in `0.18.0`.

This breaks:
````javascript
AlertIOS.prompt(
  'The Title',
  'The Message',
  [
    {text: 'Cancel'},
    {text: 'Ok'},
  ],
  'secure-text'
)
````

You'll get the following error:
"Must provide either a button list or a callback, but not both" (AlertIOS.js @ 119:0)

It works fine if you don't pass in a type.

All of the prompt examples are also failing on the example page.

**Comment by christopherdro** [comment]
@coderdave Is this still an issue on 0.19?

**Comment by p1zzadog** [comment]
@christopherdro I don't see anything about it in the patch notes

https://github.com/facebook/react-native/releases

**Comment by janicduplessis** [comment]
Tested on 0.22 and the examples work fine. There was a pretty big refactor of AlertIOS in 0.20 so that probably fixed it.

**Comment by janicduplessis** [comment]
@facebook-github-bot close
