### ISSUE TITLE
Unable to resolve module keyMirror

### ISSUE THREAD

**Issue by lrettig** [facebook/react-native#5622]
CC @zpao 

Upgrading to fbjs 0.7.0 (which was just released) causes react-native to fail every time I try to build anything. I guess fbjs 0.7.0 did something to `keyMirror`, which `react-native` depends on indirectly via `fbjs` (and there is no direct dependency). Downgrading fbjs back to 0.6.1 fixed this for me.

Wonder whether this is related to https://github.com/facebook/react-native/issues/4296

Also for the record fbjs is still screwed up because of https://github.com/facebook/react-native/issues/5467 so I only have one copy of it installed in the root node_modules and I've deleted all of the others.

Note that the usual bag of tricks (`rm -rf node_modules`, clear npm cache, watchman del all, clear react cache, etc. etc. did nothing).

```
bundle: Created ReactPackager
uncaught error Error: UnableToResolveError: Unable to resolve module keyMirror from /Users/foo/foo/node_modules/react-native/Libraries/Utilities/MessageQueue.js: Invalid directory /Users/node_modules/keyMirror
    at ResolutionRequest.js:356:15
    at tryCallOne (/Users/foo/foo/node_modules/promise/lib/core.js:37:12)
    at /Users/foo/foo/node_modules/promise/lib/core.js:123:15
    at flush (/Users/foo/foo/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
See logs /var/folders/rs/61p0bjp90ts_r161p5pystyh0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:139:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/foo/foo/node_modules/bser/index.js:289:10)
    at /Users/foo/foo/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
Command /bin/sh failed with exit code 1
```

**Comment by ide** [comment]
Until RN 0.20 (hopefully) you will have to use the same version of fbjs as React Native.

**Comment by MattFoley** [comment]
I'm seeing a similar issue. When I run `react-native bundle` on my docker instance, I see this exact error and stack. However, I'm not using keyMirror myself, although I do include flux. This is on Node 5.3, and NPM 3.3.12

**Comment by nnmer** [comment]
same here

**Comment by nnmer** [comment]
my bad, forget to restart the terminal. after restarting it was running

**Comment by skevy** [comment]
@lrettig fbjs 0.7.x is not compatible with RN at the moment.

As soon as #5084 is merged, it will be.

Is 0.7.x installing for you automatically? Or did you install it for a specific reason?

**Comment by skevy** [comment]
also, `react-native` definitely does have a direct dependency on fbjs: https://github.com/facebook/react-native/blob/a769f91ccf008ff1deca3ab490e23cd6bb518fdf/package.json#L145

**Comment by magrinj** [comment]
Hello,

I've the exact same issue on my app, I try to create an empty app with `react-native AltProject init`, in this project I just add `alt@^0.18.2`, my `package.json` looks like:

`{
  "name": "AltProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "alt": "^0.18.2",
    "react-native": "^0.19.0"
  }
}`

I also add a new file `rn-cli.config.js` to the root of my projet, to avoid the collision of the multiple directories of `fbjs`, this file looks like:

`/*eslint-disable */
var blacklist= require("react-native/packager/blacklist");
var config = {
    getBlacklistRE(platform) {
        return blacklist(platform,[/.+\/node_modules\/fbjs.*/]);
    }
}
module.exports = config;`

This file resolve my first problem, but when I try to run my app at this point I've the same issue @lrettig, and I don't know why.
That's looks like node try to find the module keyMiror but can't find it.

`Unable to resolve module keyMirror from /Users/USERNAME/AltProject/node_modules/react-native/Libraries/Utilities/MessageQueue.js: Invalid directory /Users/node_modules/keyMirror`

My node version is `v5.5.0` and my npm version is `3.7.1`, I also try with npm 2, but I have the same error.

As mentioned in this ticket [#4296](https://github.com/facebook/react-native/issues/4296), I also tried to do this:

1) upgrading to latest RN
2) `watchman watch-del-all`
2) `rm -rf $TMPDIR/react-packager-*`
3) restart the packager

But I still get the same error.
Anyone have an idea ? 

Thanks!

**Comment by skevy** [comment]
@magrinj what version of fbjs is installed?

```npm ls | grep fbjs```

**Comment by magrinj** [comment]
`fbjs 0.6.1`

Apparently I just fix the problem, I miss the project name in my `rn-cli.config.js`, so just by adding my project name like that:

>/eslint-disable */
>var blacklist= require("react-native/packager/blacklist");
>var config = {
>getBlacklistRE(platform) {
>return blacklist(platform,[/AltProject.+\/node_modules\/fbjs./]);
>}
>}
>module.exports = config;

That's solved my problem apparently :)

Thanks! :+1:

**Comment by lrettig** [comment]
@skevy IIRC I think this happened when I just ran `npm update`, no other specific reason. Thanks.

As a workaround for #5467 I added a postinstall dependency to delete all extra copies of `fbjs`; I'm guessing this accomplishes the same thing that @magrinj did here more cleverly.

**Comment by magrinj** [comment]
@skevy Yes, a postinstall script also work :) 

Thanks for you help @skevy :+1:

**Comment by mroswald** [comment]
@lrettig @magrinj fixing alt to v0.18.1 (remove ^) fixed this for me (until RN comes with fbjs > 0.7) without adding something to my project

**Comment by tomkis1** [comment]
Just to explain reason why react-native does not work with `fbjs ^0.7.0` -> in the commit https://github.com/facebook/fbjs/commit/adc43281fd947f824cd09645b44ab9e845bbb87a `@ providesModule` is stripped, react-native packager relies on the presence of `@providesModule` (https://github.com/facebook/react-native/blob/0.20-stable/packager/react-packager/src/DependencyResolver/Module.js#L106-L120)

**Temporary workaround:**
With `react-native` < 0.23 (which is currently basically any react-native) lock your `fbjs` version to `0.6.1`, looks like in `react-native` 0.23 we won't need `fbjs` at all.

**Comment by marcshilling** [comment]
No solutions here working for me

**Comment by magrinj** [comment]
@marcshilling Did you try mine ? What error did you get ?

**Comment by marcshilling** [comment]
@magrinj yes, I tried your solution exactly. Unable to resolve module keyMirror

**Comment by tomkis1** [comment]
@marcshilling are you sure that you locked your `fbjs` version in the root `package.json` file to `0.6.1` ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/unable-to-resolve-module-keymirror

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
