### ISSUE TITLE
ToolbarAndroid setDisplayHomeAsUpEnabled(true)

### ISSUE THREAD

**Issue by burgalon** [facebook/react-native#5627]
Missing a way to set the home icon as an UP action using the setDisplayHomeAsUpEnabled(true) function

**Comment by satya164** [comment]
React Native doesn't use Activities for Navigation, but uses Navigator. I guess you can just use `onIconClicked` to do whatever you want, for example, Navigation.

Please use StackOverflow for questions in the future.

**Comment by burgalon** [comment]
Hi @satya164 the setDisplayHomeAsUpEnabled() doesn't have any relation to actual navigation but rather to the look and feel of the toolbar which helps to implement [hierarchical navigation](http://developer.android.com/design/patterns/navigation.html)

**Comment by satya164** [comment]
You can easily set a custom icon for the button.
