### ISSUE TITLE
[Layout] Absolutely positioned children inside flexbox container don't override flex positioning?

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#5628]
I'm trying to create a navbar that has a middle aligned item and one item that is aligned to the right like this:

```jsx
// Desired effect
_______________________________
|            middle      right |
|______________________________|

// Actual effect
_______________________________
|         middle right         |
|______________________________|

const navbar = () => (
	<View style={{
		alignItems: 'center',
		justifyContent: 'center',
		height: 60,
		paddingTop: 20,
	}}>
		<View>
			<Text>Centered Item</Text>
		</View>

		{/* This item keeps getting centered alongside with
			the sibling above, absolute positioning has no effect */}
		<View style={{
			position: 'absolute',
			right: 0
		}}>
			<Text>Right Item</Text>
		</View>
	</View>
);
```

To work around this I had to create a dummy `<View />` that goes before the middle item, do a flex direction row, and a space-between alignment.

Is there a proper way to do this or is this a bug?

**Comment by grabbou** [comment]
Copied & pasted your code and all looks good:
<img width="392" alt="screen shot 2016-03-03 at 15 03 27" src="https://cloud.githubusercontent.com/assets/2464966/13496551/26ad847e-e151-11e5-9d46-84129786d455.png">

I have also added `top: 0` to make it go to top.

If you are still having this issue, please provide rnplay example with reproduced glitch so we can check what's wrong :)
