### ISSUE TITLE
[ios]RCTRefreshControl bug

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#5634]
![RCTRefreshControl bug](https://cloud.githubusercontent.com/assets/5953992/12696724/cb9c7f80-c7ac-11e5-83c4-b877c3dc098a.png)

react-native version: 0.18.0
I uesd `"react-native-scrollable-tab-view": "^0.3.5"`
and I uesd `ListView` and `RefreshControl`, but get this crash.

How to solve? 
@satya164

**Comment by alfredogt** [comment]
you could show it the code?

**Comment by janicduplessis** [comment]
@Richard-Cao Could you provide a small example that reproduces the bug so we can look into it?

**Comment by janicduplessis** [comment]
@facebook-github-bot label Needs more information

**Comment by Richard-Cao** [comment]
@janicduplessis 0.21.0 fix it

**Comment by browniefed** [comment]
@facebook-github-bot answered
