### ISSUE TITLE
[0.19.0-rc]debug crashes while including PickerAndroid

### ISSUE THREAD

**Issue by siger-young** [facebook/react-native#5636]
According to the example https://github.com/facebook/react-native/commit/18437093f2664beedd3239bb525d7daa3f2bcdbd, I tried `PickerAndroid` like the following in a `View`:

```
<PickerAndroid
	style={{width: 100, height: 56}}
	onSelect={this.onSelect.bind(this, 'color')}
	mode="dialog"
>
	<Item text="red" color="red" value="red" selected={this.state.color === 'red'}/>
	<Item text="green" color="green" value="green" selected={this.state.color === 'green'}/>
	<Item text="blue" color="blue" value="blue" selected={this.state.color === 'blue'} />
</PickerAndroid>
```
when I tried reloading JS, the debug app crashes without any error info.
it's really strange that if I remove children of PickerAndroid, it works with blank items.
so what's the exact problem?

**Comment by satya164** [comment]
Can you check the stack trace with `adb logcat` or Android Studio?

**Comment by mkonicek** [comment]
Closing until we have more info, let's reopen then.

**Comment by mkonicek** [comment]
The reason I'm closing this is the issue doesn't stay open forever. @siger-young if you can debug why this happens we should reopen and look into it.
