### ISSUE TITLE
Android - Auto Reload Issues

### ISSUE THREAD

**Issue by AlexLourenco** [facebook/react-native#5638]
I have had some issues with Application's not detecting file changes every once in awhile. 
After some debugging I have noticed that DevServerHelper seems to be calling /onchange way too often (every 10 seconds to be exact), rather than waiting the expected 2 minutes before considering that the server request has timed-out.

According to https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java
The default read time for okhttp is: readTimeout = 10_000;

Increasing the read time out to 2 minutes seems to fix the issue:

``` java
  public void startPollingOnChangeEndpoint(
      OnServerContentChangeListener onServerContentChangeListener) {
    if (mOnChangePollingEnabled) {
      // polling already enabled
      return;
    }
    mOnChangePollingEnabled = true;
    mOnServerContentChangeListener = onServerContentChangeListener;
    mOnChangePollingClient = new OkHttpClient();
    mOnChangePollingClient
        .setConnectionPool(new ConnectionPool(1, LONG_POLL_KEEP_ALIVE_DURATION_MS))
        .setConnectTimeout(HTTP_CONNECT_TIMEOUT_MS, TimeUnit.MILLISECONDS);
     /* - */
   mOnChangePollingClient.setReadTimeout(LONG_POLL_KEEP_ALIVE_DURATION_MS, TimeUnit.MILLISECONDS);
     /* - */
    enqueueOnChangeEndpointLongPolling();
  }
```

**Comment by janicduplessis** [comment]
Hey @AlexLourenco, could you send a PR that has the fix you mentioned?

**Comment by Roshanjossey** [comment]
@janicduplessis, @grabbou: I'd love to take this up and send a PR

**Comment by lacker** [comment]
If any of the commenters wants to send a PR, go for it! But it seems like this just might be a somewhat rare issue, because it's been stale for a while, so I am going to close this issue.
