### ISSUE TITLE
[ListView] Doesn't render section headers when section has no rows

### ISSUE THREAD

**Issue by pglotov** [facebook/react-native#5639]
I'm not sure why empty sections are designed to not be rendered at all. The code which bypasses empty sections is in `ListView.render()` as follows

```javascript
...
    for (var sectionIdx = 0; sectionIdx < allRowIDs.length; sectionIdx++) {
      var sectionID = dataSource.sectionIdentities[sectionIdx];
      var rowIDs = allRowIDs[sectionIdx];
      if (rowIDs.length === 0) {
        continue;
      }
...
```

I suggest removing `rowIDs.length === 0` check. Or adding a property to indicate if empty sections should have header rendered.

**Comment by satya164** [comment]
Why would you want to render section headers for empty sections?

**Comment by pglotov** [comment]
Say there is a list of objects by category. Category may have no objects in it, but it needs to be present in the list since the category header component may have a button to add an object. When category is first created it is empty, so there would be no way to add objects to it if it is not rendered.

**Comment by pglotov** [comment]
Also it looks like if someone wouldn't want to render empty sections they can do it in `cloneWithRowsAndSections()` call by not including empty section keys in `sectionIdentities`.

**Comment by pglotov** [comment]
I have some code, should i make a PR?

**Comment by satya164** [comment]
@pglotov Sounds reasonable. Sure.

**Comment by sasavranic** [comment]
Hello, 
I'm still unable to show empty sections. I set "enableEmptySections" to true in ListView component.
I have:

data[today] = [{obj1}, {obj2}, ...]
data[tomorrow] = []

tomorrow is not displayed

**Comment by nathan-k** [comment]
I know this issue is old, but if anyone else runs into this problem, make sure to include sectionHeaderHasChanged when creating the ListView DataSource: 

`this.ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2, sectionHeaderHasChanged: (s1, s2) => s1 !== s2})`
