### ISSUE TITLE
[iOS][RN 0.19] Custom view has an unexpected black background

### ISSUE THREAD

**Issue by xinthink** [facebook/react-native#5644]
I have a custom view drawing colored path, worked well before RN 0.19

But on RN 0.19, it seems like there is a default black background, which prevent me from using translucent colors.

It looks like this:
<img width="89" alt="2016-01-31 1 50 19" src="https://cloud.githubusercontent.com/assets/390805/12700518/993c42e4-c821-11e5-92f7-f728d5af366e.png">
If I draw nothing or some translucent color on the entire rect, you'll see the black layer

```obj-c
- (void)drawRect:(CGRect)rect
{
    [[UIColor colorWithWhite:0 alpha:0] setFill];
    CGContextFillRect(UIGraphicsGetCurrentContext(), rect);

    UIBezierPath *path = [UIBezierPath bezierPathWithRect:CGRectMake(10, 10, 20, 20)];
    [[UIColor redColor] setFill];
    [path fill];
}
```

please help me fix this problem.

**Comment by gre** [comment]
Have you tried to set backgroundColor:transparent ?

**Comment by gre** [comment]
See this https://github.com/facebook/react-native/commit/73417068848aa363e01ddf55096140452f5dc645

**Comment by xinthink** [comment]
ok, thanks @gre
