### ISSUE TITLE
 undefined is not an object (evaluating 'h.propTypes.style')

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [facebook/react-native#5646]
An application with a simple view->scrollview->image nesting, throws 
 undefined is not an object (evaluating 'h.propTypes.style')

Setup: 
react-native-cli: 0.1.10
package.json:
{
  "name": "hybrid",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.19.0"
  }
}
The index.android.js 

`render:function() {
    return (
     \< View style={styles.container}> 
       \<ScrollView style={styles.scrollView} >
           \<Image style={{width:Dimensions.get('window').width}} source={require('./hybrid-v1@2x.png')} />   
        \</ScrollView>
      \</View>
    );
  }
const styles = StyleSheet.create({
  container: {
    flex: 1,
    width:  Dimensions.get('window').width, 
     
  },
  scrollView:{
    flex:1,
    width:  Dimensions.get('window').width,
  },
 
});`

01-31 17:01:01.367  3276  3292 E ReactNativeJS: undefined is not an object (evaluating 'h.propTypes.style')
01-31 17:01:01.372  3276  3293 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-31 17:01:01.372  3276  3293 E AndroidRuntime: Process: com.hybrid, PID: 3276
01-31 17:01:01.372  3276  3293 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: <unknown>
01-31 17:01:01.372  3276  3293 E AndroidRuntime:     index.android.bundle:15:8982
.
.
.
01-31 17:01:01.372  3276  3293 E AndroidRuntime:     global code@index.android.bundle:17:26630

**Comment by Richard-Cao** [comment]
+1

**Comment by jjshammas** [comment]
+1

**Comment by kristjanmik** [comment]
We have a good discussion going on in #5655

**Comment by jagan-veeraraghavan** [comment]
#5655 resolves this issue, so closing it.
