### ISSUE TITLE
com.facebook.react:react-native:0.19.0 @ReactProp issue on android

### ISSUE THREAD

**Issue by soxunyi** [facebook/react-native#5649]
If you use android native view, and annotations ReactProp. Please import the right ReactProp class, ```import com.facebook.react.uimanager.annotations.ReactProp```, rather than ```import com.facebook.react.uimanager.ReactProp```. 

com.facebook.react.uimanager.ReactProp is not work on 0.19.0. 

Why do not remove this class on 0.19.0?

**Comment by rpopovici** [comment]
temporary fix for this is to add the following to your build.gradle

android {
...
    lintOptions {
        warning 'InvalidPackage'
    }
}

dependencies {
    ...
    compile 'com.facebook.react:react-native:0.19.+'
}

and then import com.facebook.react.uimanager.annotations.ReactProp

**Comment by deminoth** [comment]
+1. `import com.facebook.react.uimanager.ReactProp` does not showing any error but not working.

**Comment by janicduplessis** [comment]
This was a breaking change in 0.19, sorry if it was not communicated properly.

**Comment by janicduplessis** [comment]
@facebook-github-bot answered

**Comment by taypo** [comment]
Lost two days on this. Please make a remark on the documentation.

**Comment by fiattt** [comment]
Lost one days on this  - -!
