### ISSUE TITLE
0.19 ios run error

### ISSUE THREAD

**Issue by lizi2013** [facebook/react-native#5653]
when i init a react-native project and run it in xcode  i have get last error who can help me 

TransformError: /Users/lizi/Desktop/ATFProject/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/lib/index.js: [BABEL] /Users/lizi/Desktop/ATFProject/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/lib/index.js: Unknown option: /Users/lizi/Desktop/ATFProject/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/.babelrc.stage

**Comment by aboutqx** [comment]
#https://github.com/facebook/react-native/issues/5393#issuecomment-174319207

**Comment by ShadowZheng** [comment]
0.19 android is also have same problem. please help me. it's block me two days.

**Comment by bestander** [comment]
Try `rm -rf node_modules && npm install`

**Comment by bestander** [comment]
@facebook-github-bot answered
