### ISSUE TITLE
minWidth/minHeight/maxWidth/maxHeight missing on 0.19?

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#5657]
On updating to 0.19 (from 0.17) I found warning on unsupported styling of minWidth/minHeight/maxWidth/maxHeight. I didn't find anything regarding to these in the breaking change release note and since these are the new stuff only be added since 0.17, any chance this is a mistake?

**Comment by ide** [comment]
They were never supported to begin with -- the fact that they showed up in the documentation was a mistake.

**Comment by sjmueller** [comment]
Hmm, I was using maxHeight and minHeight effectively in 0.19, but now with 0.20.0-rc I get red the red screen of death.  What is the alternative to allow a view to prevent a view from growing/shrinking beyond a certain height?

**Comment by ide** [comment]
height: min(this.state.measuredHeight, maxHeight)

**Comment by sjmueller** [comment]
:+1:

**Comment by mpretty-homepass** [comment]
@ide That doesn't seem like a great solution as you need to set the state in onMeasure which will re-render the UI. Previously the min/max values would be followed without having to re-render the component.

Is there an alternative way which doesn't require the component to render twice?

**Comment by ide** [comment]
No, the layout engine doesn't support that.
