### ISSUE TITLE
lineHeight on Text component not rendering consistently on iOS vs Android

### ISSUE THREAD

**Issue by axelander** [facebook/react-native#5662]
Seems like setting the lineHeight property on a Text component gives different results on Android vs iOS.
Tested without custom font and still the same issue.
![lineheight_example](https://cloud.githubusercontent.com/assets/3784741/12714005/7354bbf4-c8d2-11e5-9eda-2ec178c42652.png)

Digging in to the source it seems like it has something to do with [`view.setLineSpacing(PixelUtil.toPixelFromSP(lineHeight), 0);`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextViewManager.java#L78). Setting the multiplier to 1 gives at least the same spacing between all lines but then the height gets screwed up and I guess we want to keep it at zero. Any thoughts on why this happens?

**Comment by kozlowskij** [comment]
@axelander, did you find a way to fix this? It seems to only occur with custom fonts. I'm on 0.20.0.

**Comment by axelander** [comment]
@kozlowskij Yes, the problem only occured with custom fonts for me too, my mistake. I got a bit closer to consistent rendering by running the font through [fontbakery fix for vertical metrics](https://github.com/googlefonts/fontbakery/blob/master/tools/fontbakery-fix-vertical-metrics.py).

**Comment by sbycrosz** [comment]
In case anyone come here in the future, this seems to be caused by UILabel's instead of RN (http://stackoverflow.com/questions/5414730/custom-installed-font-not-displayed-correctly-in-uilabel)
