### ISSUE TITLE
[ListView] performance with more complicated renderRow

### ISSUE THREAD

**Issue by go1t** [facebook/react-native#567]
I was trying to implement a real time filtering using textInput. However, the re-rendering of the ListView is incredibly slow (about 1 seconds after finish typing). 

This is what the renderRow function returns: (I simplified it a lot from my real renderRow, still slow)

```
<View>
  <TouchableOpacity onPress={this.props.onSelect}>
    <View style={cellstyle}>
        <Image
          source={require('image!logo')}
          style={[
            styles.cellImage,
            {resizeMode: Image.resizeMode.contain}
          ]}
        />

      <View style={styles.textContainer}>
        <Text numberOfLines={2} lineHeight={1}>
          {this.props.item.name.trim()}
        </Text>
        <Text>
          {digits(this.props.item.price)}
        </Text>
      </View>
    </View>
  </TouchableOpacity>
  <View style={styles.cellBorder} />
</View>
```

I have tried to replace TouchableOpacity with View, but that still doesn't help improve the performance much.

**Comment by wangii** [comment]
Is it related to `rowHasChanged`?

**Comment by igodzp** [comment]
my ```rowHasChanged``` was the same as the documentation:

```rowHasChanged: (r1, r2) => r1 !== r2```

**Comment by wangii** [comment]
assume each of your item has unique id:
`rowHasChanged:(r1, r2)=> r1.item.id !== r2.item.id`

**Comment by igodzp** [comment]
I doubt it would make anything faster, since ```r1 !== r2``` does the reference checking, which should be more optimal than ```r1.item.id !== r2.item.id``` where you have to reference the object for the id, and compare them.

**Comment by karanbhangui** [comment]
Any updates on this? Having similar performance issues.

**Comment by chirag04** [comment]
+1

**Comment by josebalius** [comment]
+1 for me as well, ListViews are becoming a bit of an issue in our app. Our renderRows contain the same if not more nodes than the example above.

**Comment by cyprusglobe** [comment]
+1 seeing this issue as well.

**Comment by thisbejim** [comment]
+1

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by robertjpayne** [comment]
This is a big issue for myself as well -- seems to be especially bad on older devices, newer devices don't seem to exhibit much issue with very complex rows.

**Comment by pukhalski** [comment]
+1 here. Tried [SGListView](https://www.npmjs.com/package/react-native-sglistview) instead of a standard one. A bit better, but it still feels like a hybrid app...

**Comment by Pajn** [comment]
I tried with a very simple row on android, just `(item) => (<Viev><Text>{item.name}</Text></View>)` and even then it's slow to unusable.

**Comment by pukhalski** [comment]
Any updates on this one so far?

**Comment by thunderousNinja** [comment]
:+1:

**Comment by jozn** [comment]
+1

**Comment by braunsquared** [comment]
+1

**Comment by jaygarcia** [comment]
Does removal (just asking) of the image make a difference?

**Comment by Pajk** [comment]
The ListView performance is not very good in general. I have also an image in each row and the scrolling and re-rendering is not very smooth. Without the image the performance is much better.

**Comment by jaygarcia** [comment]
The issue isn't list view then. It's probably the images rendering.  They seem to cause the JS event loop to stutter :(

**Comment by marcshilling** [comment]
Just something to try...set `shouldRasterizeIOS={true}` on your images in renderRow(). I've seen some performance improvements this way.

**Comment by rzvavram** [comment]
+1

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-performance-with-more-complicated-renderrow

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by tslater** [comment]
+1

**Comment by ammichael** [comment]
+1

**Comment by tslater** [comment]
I really don't think this should be closed. It's a big deal.

**Comment by ammichael** [comment]
Here a gif showing the problem: https://www.dropbox.com/s/60z3hrs76ijs96c/SlowPepperoni.gif?dl=0

**Comment by TyrealGray** [comment]
Try this:
shouldComponentUpdate(nextProps, nextState) {
		return nextState.SOME_DATA !== this.state.SOME_DATA;
}

**Comment by trongan** [comment]
+1
I have similar this problem.

**Comment by jekram** [comment]
+1

**Comment by Jithinag007** [comment]
i am facing same issues how to solve ?

**Comment by IbraheemAlSaady** [comment]
+1
