### ISSUE TITLE
[PushNotification] Obtain deviceToken from PushNotification

### ISSUE THREAD

**Issue by mrdanjlee** [facebook/react-native#568]
What is the best way to obtain the deviceToken from the PushNotification API?

**Comment by darylrowland** [comment]
I'm trying to figure this out too. Feels like when you register you should get a token back?

**Comment by darylrowland** [comment]
Anyone got any ideas on this? Really need to be able to pull the token back in the app I'm creating.

**Comment by ide** [comment]
If it's not yet supported (I don't think it is) the quickest path forward is to submit a PR.

**Comment by darylrowland** [comment]
In case anyone is interested, I ended up writing a custom module for this (had to make quite a few changes). I've put the code up on github here: https://github.com/darylrowland/react-native-remote-push
