### ISSUE TITLE
not play video with WebView

### ISSUE THREAD

**Issue by alfredogt** [facebook/react-native#5681]
hello everybody,
i have the following problem:
i'm trying the example from documentation for use of WebView, but when run in my phone it does not work.
shows me the following error

![2f2695a2-bab7-4931-8f0d-b8054b37e9a5](https://cloud.githubusercontent.com/assets/8040552/12731639/d6ce6112-c8ff-11e5-8fe5-c1e3f9ff04c7.jpeg)

I tried with different videos and does not play any
https://www.youtube.com/watch?v=nlcIKh6sBtc
http://www.jwplayer.com/
http://www.albinoblacksheep.com/flash/elvis
https://vimeo.com/153123641

nothing

version android: 4.2.1
version react-native 0.19.0

thanks.

(excuse my wording does not understand much English)

**Comment by Frulko** [comment]
+1

**Comment by ejb1123** [comment]
+1

**Comment by charpeni** [comment]
I know this issue is older than #6405, but I will close this one since the other contains more information and a workaround and fix.

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #6405
