### ISSUE TITLE
RTCNetworking.sendRequest got 7 arguments, expected 6

### ISSUE THREAD

**Issue by agutoli** [facebook/react-native#5684]
Hello, I try to change  react-native **0.18.1** to **0.19.0** but I caught this error.

![captura de tela 2016-02-01 as 23 06 52](https://cloud.githubusercontent.com/assets/298845/12736589/b356f5d0-c938-11e5-8afc-4870f3d26541.png)

## My AVD

![captura de tela 2016-02-01 as 23 09 25](https://cloud.githubusercontent.com/assets/298845/12736621/f5af3884-c938-11e5-80d7-06b408d95170.png)

**Comment by satya164** [comment]
Please use `react-native upgrade` command to upgrade you RN version.
