### ISSUE TITLE
Version number in tag v0.19.0 is missing?

### ISSUE THREAD

**Issue by yueshuaijie** [facebook/react-native#5685]
In the git repo tag v0.19.0, package.json: https://github.com/facebook/react-native/blob/v0.19.0/package.json
"version": "0.0.0-master",

And the React.podspec: https://github.com/facebook/react-native/blob/v0.19.0/React.podspec
s.version             = "0.0.0-master"

Shouldn't the version numbers be "0.19.0"? not "0.0.0-master"?

This cause install React to an existing iOS project from cocoapods with this pod config failed:
pod 'React', :git => 'http://github.com/facebook/react-native', :tag => 'v0.19.0'
Since it cannot find a React.podspec with correct version number.

Also, I find the native code from "npm i react-native@0.19.0" and git repo tag v0.19.0 not exactly the same, for example, from npm install, node_modules/react-native/React/Views/RCTWebViewManager.m is not same as https://github.com/facebook/react-native/blob/v0.19.0/React/Views/RCTWebViewManager.m
As a result, I cannot run react-native with js code installed from npm package and native code from git repo tag v0.19.0
It seems that native code from branch 0.19-stable HEAD works with js in npm package 0.19.0

Is there something wrong or did I miss something?

**Comment by satya164** [comment]
cc @bestander

**Comment by bestander** [comment]
I'll investigate, thanks

**Comment by bestander** [comment]
So, looks like we have a release done wrong.
Need to make the scripts less stateful and do them on CI, cc @mkonicek.

Can anyone confirm whether npm release got bonkers, or just git tag is pointing to a wrong commit?
It would be much easier to fix the tag rather than make a 0.19.1 release.

**Comment by bestander** [comment]
Ok, looks like tag v.0.19.0 was added to master branch by mistake:
https://github.com/facebook/react-native/commits/0.19-stable
vs
https://github.com/facebook/react-native/commits/v0.19.0

I'll checkout 0.19-stable and retag it as 0.19.0.
That should make fix the first issue.

**Comment by bestander** [comment]
Ok, tag fixed.

**Comment by bestander** [comment]
So before I jump into fixing npm package, and releasing 0.19.1, does this fix the problem?
```
"react-native": "git@github.com:facebook/react-native.git#v0.19.0"
```

**Comment by danieldkim** [comment]
thanks for the quick response on this!  btw, not sure how the documentation is generated but the description for `CameraRoll.getPhotos()` still shows the [newer version of the API](http://facebook.github.io/react-native/docs/cameraroll.html#content).

**Comment by bestander** [comment]
Yeah, current docs show what is on master branch.
I'll work on per release docs starting tomorrow

**Comment by bestander** [comment]
Closing it.
Please reopen if there are further issues
