### ISSUE TITLE
[Windows][Packager] Custom rn-cli.config.js files cannot be found

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#5686]
`rn-cli.config.js` files cannot be found due to a bug in how paths are handled in [Config.js](https://github.com/facebook/react-native/blob/5ec1d354c2ebbe0b168c84dd0486459266e29708/local-cli/util/Config.js).

This issue was reported by #3512 (closed) but this bug still repros in 0.19 and it appears that the fix that was described doesn't exist in [Config.js](https://github.com/facebook/react-native/blob/5ec1d354c2ebbe0b168c84dd0486459266e29708/local-cli/util/Config.js#L66).

**Comment by janicduplessis** [comment]
Thanks for reporting this! I will be fixed when #6553 lands.

**Comment by janicduplessis** [comment]
@facebook-github-bot close
