### ISSUE TITLE
minus margin broken on 0.19

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#5690]
I haven't test everything but minus margin (i.e. marginTop:-1,marginLeft:-1, etc) is no longer working between Views on 0.19.0. Is this an on purposed change or by mistake?

**Comment by grabbou** [comment]
Hey, would you mind double checking if all works? I just tested on latest 0.25-rc release and marginTop worked fine on my `View`.

**Comment by lacker** [comment]
I am closing this issue under the theory that it actually does work. Feel free to reopen if this bug still exists and you have repro information.
