### ISSUE TITLE
Why do the examples use TypeScript?

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5691]
https://facebook.github.io/react-native/docs/listview.html#examples

Just wondering why that choice was made, rather than sticking with pure ES6.

**Comment by ide** [comment]
They use Flow (not TypeScript) because Facebook uses it. That's the answer for most of the arbitrary decisions in this repo :)

**Comment by ffxsam** [comment]
Aha! I tried Googling around to see what syntax that was, the closest I could come up with was TypeScript. Thanks!
