### ISSUE TITLE
Wrong version of CameraRoll.js published to npm version 0.19.0

### ISSUE THREAD

**Issue by danieldkim** [facebook/react-native#5693]
I just did an npm install of version 0.19.0 and the file does not match the [version tagged in github](https://github.com/facebook/react-native/blob/v0.19.0/Libraries/CameraRoll/CameraRoll.js).  The version in npm still has the deprecated API for `getPhotos()` that takes the callback arguments.  Haven't checked if this is an issue with other files.

**Comment by yueshuaijie** [comment]
See #5685  https://github.com/facebook/react-native/issues/5685

**Comment by satya164** [comment]
Closing in favour of #5685
