### ISSUE TITLE
How to keep cursor of TextInput in focus but keyboard dismiss?

### ISSUE THREAD

**Issue by rachelyao** [facebook/react-native#5694]
I want to dismiss the system keyboard and keep the cursor still in focus to build a custom keyboard.

**Comment by grabbou** [comment]
Not sure how that works on Android, but on iOS this is limited and can be done natively using some API exposed by Apple. Since that has nothing to do with react native itself, I believe you might find an answer on StackOverflow or in some iOS/Android related communities.
