### ISSUE TITLE
onPanResponderTerminationRequest is not working.

### ISSUE THREAD

**Issue by jihopark** [facebook/react-native#5696]
I want to make `onPanResponderTerminationRequest: (evt, gestureState)=>false`, 

so that parent ListView won't take away the gesture but it doesn't seem like working properly..

Does anyone know why? I am looking into the library but still cannot find why.

**Comment by rpastorelle** [comment]
I seem to be experiencing this as well. I have some draggable `Accessory` components on top of the `ViewPagerAndroid` component. When dragging an `Accessory` component horizontally the lifecycle method `onShouldBlockNativeResponder` is called but return value is not respected. `onPanResponderTerminate` is called and the `ViewPagerAndroid` takes over. `onPanResponderTerminationRequest` was never called.

**Comment by christopherdro** [comment]
@facebook-githb-bot bugfix

**Comment by Smallpath** [comment]
@rpastorelle  I'm running into the same problem with ViewPagerAndroid. `onPanResponderTerminationRequest` is never called. Do you solve the problem?

**Comment by bigsassy** [comment]
I'm running into a similar problem.  I have a `VIew` with a PanResponder that sits inside of a ScrollView.  My `onShouldBlockNativeResponder` handler is getting ran, but the return value gets ignored.  And I can't get the `onPanResponderTerminationRequest` to ever get called.  I can go into more detail if needed.

Any movement anywhere on looking into this or solving it?  Have anyone who previously posted here find a solution?

**Comment by rpastorelle** [comment]
@Smallpath It was a while ago but I believe this was the hack that hid the problem for me:

```
onMoveShouldSetPanResponder: (e, gestureState) => {
        if (
          Platform.OS == 'android'
          && (gestureState.dx < 1 && gestureState.dx > -1)
          && (gestureState.dy < 1 && gestureState.dy > -1)
        ) {
          return false;
        }

        return true;
}
```

**Comment by tiemevanveen** [comment]
I was having the same problem. `onPanResponderTerminate` get called immediately when the user scrolls the parent's ListView.. 

I checked the source code and found this: 

> **Scrolled views automatically become responder**. The reasoning is that a platform scroll view that isn't built on top of the responder system has began scrolling, and the active responder must now be notified that the interaction is no longer locked to it - the system has taken over.
 
https://github.com/facebook/react/blob/master/src/renderers/shared/stack/event/eventPlugins/ResponderEventPlugin.js#L151-L154

So I think that explains why the ListView takes over...

I'm working on a workaround by setting `scrollEnabled={false}` on my ListView as soon my panResponder becomes the responder. Will post the code here later.

**Comment by aymericbouzy** [comment]
Not sure if that's the correct answer, but shouldn't you add `scrollEnabled={false}` to your `ListView` while you are handling the gesture ?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
