### ISSUE TITLE
[0.19] warning on interpolated color

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#5697]
If created a color object by interpolating an animated variable, using the following code:
`this.state.trans.interpolate({
      inputRange: [0,1],
      outputRange:['rgba(204,204,204,1.0)','rgba(102,102,102,1.0)']
 });`

The following warning will show up:

> 
> Warning: Failed propType: Invalid color supplied to color: rgba(203.978144256, 203.978144256, 203.978144256, 1). Valid color formats are
>   - #f0f (#rgb)
>   - #f0fc (#rgba)
>   - #ff00ff (#rrggbb)
>   - #ff00ff00 (#rrggbbaa)
>   - rgb(255, 255, 255)
>   - rgba(255, 255, 255, 1.0)
>   - hsl(360, 100%, 100%)
>   - hsla(360, 100%, 100%, 1.0)
>   - transparent
>   - red

The interpolate code was working fine on 0.17, and there seems no way to round the numbers to integer in the interpolate function (or there is?). Any way we can make this work?

**Comment by nicklockwood** [comment]
A fix for this issue has been landed in master: https://github.com/facebook/react-native/commit/bee6988f94888acdc9a4539c780e664a32ecf63f
