### ISSUE TITLE
ProgressDialog like Android

### ISSUE THREAD

**Issue by shukerullah** [facebook/react-native#5698]
How can I achieve ProgressDailog like android?

**Comment by alwx** [comment]
Check this library that allows you to do almost anything with Android dialogs: https://github.com/aakashns/react-native-dialogs/ (actually, it is just a wrapper for another awesome library https://github.com/afollestad/material-dialogs)

**Comment by shukerullah** [comment]
@alwx thanks

**Comment by edvaldoszy** [comment]
Checkout this library https://github.com/douglasjunior/react-native-simple-dialogs
