### ISSUE TITLE
On 0.19, WebView is always loading

### ISSUE THREAD

**Issue by Daniel-ccx** [facebook/react-native#5699]
![image](https://cloud.githubusercontent.com/assets/5927124/12748260/1c9a89de-c9e4-11e5-9d1c-9a177948640a.png)

Hope u understand the picture

**Comment by Richard-Cao** [comment]
use `url` instead `source`

**Comment by lrettig** [comment]
Docs need to be updated

**Comment by ffxsam** [comment]
Ok, I'm confused. Check out the source:

https://github.com/facebook/react-native/blob/81fb985335a8ee3657905177abe32380b6b5fdc0/Libraries/Components/WebView/WebView.ios.js#L95-L103

What are we actually supposed to use? Are the docs out of date, or is the source not updated?

**Comment by lrettig** [comment]
both? :) :disappointed:

**Comment by christopherdro** [comment]
Docs are being extracted from the source code on master so they are up to date.
The changes for this can be found on this commit https://github.com/facebook/react-native/commit/46106f756ad230ed381ecaf06e6fcd87c318b148.

You can use the `source` prop if your working of 0.20
