### ISSUE TITLE
[Packager] how to load multiple bundles especially share base bundle?

### ISSUE THREAD

**Issue by mickshu** [facebook/react-native#570]
In a App，how to load multiple bundles ;especially share base bundle?

**Comment by amasad** [comment]
We don't have a great answer to that yet, but it's something we're thinking about.

**Comment by bluemsn** [comment]
@amasad Thanks for you answer ~ but  since you last answer already more than a month has passed?  Did you had  solved ?

**Comment by amasad** [comment]
No, sadly. But I hear @philikon is thinking about this.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by amasad** [comment]
@martinbigio is working on this.

**Comment by dickeylth** [comment]
Four months have passed, are we making any progress on this issue?

**Comment by dickeylth** [comment]
Four months have passed, are we making any progress on this issue?

**Comment by martinbigio** [comment]
We paused working on this issue as we're pursuing other approaches to reduce the time it takes to load the JS bundle.

**Comment by zhou7758437** [comment]
We have the same problem in production. Because we have many business departments working on one app, they share same native base libraries. We'd like to share base  js bundle between those departments and upgrade them separately. Any suggestions?

**Comment by alloy** [comment]
@zhou7758437 I’m unsure why I’m being mentioned on this thread.

**Comment by dickeylth** [comment]
@martinbigio I think this is more than a performance issue, if common shared bundle loading is possible, it could reduce total bundle size dramatically, this is very meaningful for production, so I'm still looking forward to any progress on this issue.

**Comment by zhou7758437** [comment]
@alloy Sorry for my mistake.
@dickeylth Do you have any solutions for this？

**Comment by ide** [comment]
I believe FB deprioritized this

**Comment by christineRR** [comment]
I want to know about this issue. Is there any progress recently? ☺️

**Comment by sakim** [comment]
Any progress or alternative way to resolve this?

**Comment by BaihaoTian** [comment]
looking forward any progress.

**Comment by hzy00** [comment]
+1

**Comment by ide** [comment]
My understanding is that this is not being worked on and there are no updates. You should build this feature yourself if you want it.

**Comment by khannasaransh** [comment]
Any update on this??

**Comment by Shiza1aas** [comment]
+1

**Comment by ronak301** [comment]
+1

**Comment by fov42550564** [comment]
+100

**Comment by gandhirahul** [comment]
2 years passed,  any progress recently?

**Comment by doniyor2109** [comment]
+1

**Comment by tourze** [comment]
+1

**Comment by tourze** [comment]
+1

**Comment by cyqresig** [comment]
+1

**Comment by yanqiw** [comment]
+1

**Comment by JimmyDaddy** [comment]
+1

**Comment by ibmsoft** [comment]
+1

**Comment by MJ0826** [comment]
Do we have any update on this ?

**Comment by vance-liu** [comment]
+1

**Comment by zfha** [comment]
+1 mark

**Comment by sdyxch** [comment]
+1

**Comment by yanqiw** [comment]
some ideas for ios https://github.com/yanqiw/metro-bundler/blob/master/build-bundle.md

**Comment by princenaman** [comment]
Anything?

**Comment by virtuallyjeff** [comment]
All -- has there been any update on this?  Really hoping to see a solution from you.  it's obvious that multiple people have this requirement.  please don't suggest that we focus on other approaches, such as an optimized diff download.  there are valid use cases for the basic question -- splitting a platform or framework from app.  and not producing the complete bundle every time (whether it's in a diff or not).
