### ISSUE TITLE
Animating ListView row deletions with LayoutAnimation

### ISSUE THREAD

**Issue by talkol** [facebook/react-native#5702]
I'm having difficulty animating the deletion of a row from ListView using LayoutAnimation. Since `LayoutAnimation.spring` preset animation handles view updates with a spring and view creations with a fade, I expected the bottom existing rows to spring upwards after the deletion. Instead, they fade in.

```
let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
var movies = [movie1, movie2, movie3, movie4, movie5];

...

renderRow(row) {
  return <MovieRow key={row.movieId} />
}

...

// immutable delete of element in reducer (redux)
movies = movies.slice(0, 2).concat(movies.slice(3));

...

LayoutAnimation.spring();
this.setState({
  dataSource: ds.cloneWithRows(movies)
});
```

**Comment by talkol** [comment]
My mistake was that the slice,concat,slice approach changed the rowIDs for all rows which caused a re-render. The correct approach is to keep rowIDs identical on updates. So an alternative delete mechanism would be to save a set of all deleted rowIDs and on the row render check against this set and return false if the rowID is there.

**Comment by inetfuture** [comment]
> My mistake was that the slice,concat,slice approach changed the rowIDs for all rows which caused a re-render. The correct approach is to keep rowIDs identical on updates. So an alternative delete mechanism would be to save a set of all deleted rowIDs and on the row render check against this set and return false if the rowID is there.

Interesting, but how do you handle row insertion?
