### ISSUE TITLE
Bundle update without App update?

### ISSUE THREAD

**Issue by StevenLangbroek** [facebook/react-native#571]
For a product I'm lead developer for, we currently use a WebView component, for a very specific reason: we supply an SDK to developers, and want to be able to update this product without forcing all our clients to update said SDK (this is always a long process, and per client dependent on their release-cycle). What are your thoughts on having an app ping our server for a "current version number", and if it's higher than the one in the app, have the app download a new one? Is this even possible with React Native?

**Comment by amasad** [comment]
Sounds like it could be possible, however, we don't have any tools in place to do that, nor do we do that internally. If this worked for you please share back with the community. Thanks

**Comment by jnak** [comment]
Hey @amasad 

At the react conf, some fb employee showed me a hidden drawer in the fb group app where you could see all the bundles built and download / run any old version of the app. So yes it is possible. 

Though I doubt Apple is ok with over the air updates that do not go through their vetting process. I'm sure some people do that, but they are probably staying under the radar for this reason. 

Thoughts ?

**Comment by amasad** [comment]
@jnak I honestly don't have that much context on this. Good luck!
