### ISSUE TITLE
TextInput font family incorrect after switching `secureTextEntry` off

### ISSUE THREAD

**Issue by jevakallio** [facebook/react-native#5710]
RN 0.19 on iOS.

I am implementing a component that allows user to see their password in plain text by pressing a button:

![screen shot 2016-02-02 at 19 16 46](https://cloud.githubusercontent.com/assets/1203949/12761114/9a61b9a8-c9e1-11e5-8ad3-1959a0677bbb.png)

I would expect the font of the text input to be as defined by the style sheet

![screen shot 2016-02-02 at 19 18 33](https://cloud.githubusercontent.com/assets/1203949/12761184/c79d2d08-c9e1-11e5-99d3-b67985bd3fe7.png)

Instead, the font family of the characters is a default serif font:

![screen shot 2016-02-02 at 19 19 41](https://cloud.githubusercontent.com/assets/1203949/12761220/ef2875c6-c9e1-11e5-85e7-f3403415b144.png)

I am able to work around this by forcing the `TextInput` to re-render by setting a new `key` prop, but this causes the input to lose focus and keyboard to withdraw.

**Comment by johnnynanjiang** [comment]
I have the same problem, even when re-rendering the page.

**Comment by christopherdro** [comment]
Duplicate #6149
