### ISSUE TITLE
RefreshControl with refreshing=true does not show refreshing indicator on first render

### ISSUE THREAD

**Issue by TheBerg** [facebook/react-native#5716]
With this code:
```
        <ListView
          refreshControl={
            <RefreshControl
              refreshing={true}
              ...
            />
          }
          dataSource={this.dataSource}
          ...
        />
```
The refreshing indicator is not shown until a pull to refresh occurs. This would be helpful to work for initial data loading.

**Comment by Sh3rawi** [comment]
+1

**Comment by leovanhaaren** [comment]
Is it me or is this just the way it's supposed to work. You are loading the initial data and not refreshing data thats already there. If you really need a initial loader you can look at using a loading container.

**Comment by nicklockwood** [comment]
@leovanhaaren is correct that this is a slightly unusual way to indicate loading, however there's no reason I'm aware of why it shouldn't work, so it's probably a bug.

**Comment by janicduplessis** [comment]
I agree this should work, I'll probably have some time to look at this soon.

**Comment by TheBerg** [comment]
@janicduplessis Thanks! That is awesome! Please let me know if there is anything I can do to help in the process. :)

**Comment by ranyefet** [comment]
+1 Spent good few hours on that issue :sob:

**Comment by TheBerg** [comment]
Fixed in #5745

**Comment by fisch0920** [comment]
Thanks!

**Comment by Gentlee** [comment]
@TheBerg actual again in `0.52.0` (only for `ios`).

**Comment by megabayt** [comment]
@janicduplessis @TheBerg any news about this issue?

**Comment by getconcar** [comment]
We're experiencing this again too.

**Comment by kevinscience** [comment]
experiencing this issue now as well

**Comment by Cawfree** [comment]
Same problem. Not sure if this is associated with the fact I'm using `keyboard-aware-scroll-view`?
