### ISSUE TITLE
Load variables from a Theme file?

### ISSUE THREAD

**Issue by darkcode85** [facebook/react-native#5719]
I have a react native application called **A** (that supports IOs & Android), now I want create another application very similar to **A**, I only need change some colours the rest of the code is exactly the same. One option could be create a new application **B** and copy all the code from **A** and change the hard coded colours, obviously it doesn't look very clever because now I have to maintain two different applications.

There are any way to load the colours information from a _theme file_ and then when I start the application determinate what file the application should use?

**Comment by nicklockwood** [comment]
You can just define all your color constants in a single file and then have two versions: `themeColors.ios.js` and `themeColors.android.js`. React Native will load the correct file for each platform.

**Comment by grabbou** [comment]
+1 what @nicklockwood said. I am using that approach in my multi-branded app and works well. Having `colors.js` file that I am changing when new version is being made (separate branch). When I work on the main one (in master), I just sync up the changes to all branches.
