### ISSUE TITLE
[ListView] Padding at the bottom of list view doesn't work

### ISSUE THREAD

**Issue by cleercode** [facebook/react-native#572]
Adding `paddingBottom` to a list view doesn't seem to actually adding padding to the bottom. Other padding values work fine.

**Comment by donyu** [comment]
This seems to be an issue with <ScrollView> also.

**Comment by aleclarson** [comment]
+1

**Comment by donyu** [comment]
@vjeux @a2 Do you have any tips on how to fix this? I couldn't figure out the issue after spending a few hours on it. `RCT_EXPORT_SHADOW_PROPERTY` and `RCT_PADDING_PROPERTY` seem to be set properly for paddingBottom, and `(UIEdgeInsets)paddingAsInsets` is being called with the correct padding values.

In the meantime, setting `paddingBottom` for the `contentContainerStyle` prop works for ListViews and ScrollViews.

**Comment by a2** [comment]
In some of the UIExplorer examples, we've added a blank `<View />` with a specific height to the bottom of the `<ScrollView />`. Does that work for you?

**Comment by donyu** [comment]
Adding a blank `<View/>`, setting `paddingBottom` for `contentContainerStyle`, and using `renderFooter` all work, but I was hoping for advice on how to fix the `paddingBottom` style property at the API level.

**Comment by christopherdro** [comment]
@cleercode Did any of the above solutions end up working out for you?

**Comment by christopherdro** [comment]
Closing this since no one has responded for a while.

**Comment by xingrz** [comment]
@christopherdro The solution works, but this bug should be fixed properly in the ListView. So please reopen this issue.

**Comment by pqkluan** [comment]
This issue also affects FlatList ;(
