### ISSUE TITLE
Android: scrollReponderScrollWithoutAnimationTo on ListView doesn't do anything.

### ISSUE THREAD

**Issue by jkhustler** [facebook/react-native#5721]
The documentation has me believing that calling scrollResponderScrollWithoutAnimationTo on a ListView ref should allow me to set the scroll position on Android. It looks like it's not doing anything. Is this known behavior?

**Comment by nicklockwood** [comment]
That method is deprecated (although it should still work?). Try using scrollResponderScrollTo() instead.

**Comment by janicduplessis** [comment]
@jkhustler Are you using a RefreshControl? There is an issue that scrollTo is not working when using that (#5725).

**Comment by jkhustler** [comment]
@nicklockwood I've tried that also, still no dice :/

@janicduplessis Yes I am! This explains it. So I am not going crazy. Thanks so much for your response :)

**Comment by jkhustler** [comment]
Closing since this is a dupe

**Comment by janicduplessis** [comment]
@jkhustler Great, I just submitted a PR so it should get fixed soon :)
