### ISSUE TITLE
[Navigator][0.19.0][ios][bug]: Scene Component will render twice and more

### ISSUE THREAD

**Issue by soliury** [facebook/react-native#5726]
I have use rn before, and code a app in react-native. But the old rn don't rerender a component when pop back to the last scene. 

But now I found that:

* when load to the initial route, the initial route will render, I mean the constructor will run once.  +1
* when I push to another scene, the initial route component will render, the constructor will run once. +1
* after push to another scene, and then I pop this scene, and return to initial route, the constructor will run again after the scene didFocus. +1

So the scene state is losing, I don't know whether this is a functional to navigator, but I think this is a bug. It just like the web, it can't cache the last scene state, so and it make the navigator so slow.

**Comment by soliury** [comment]
I have found that: every scene in navigator, it will unmount when push to another scene.

**Comment by soliury** [comment]
This must be a bug

**Comment by ndao** [comment]
+1

**Comment by chirag04** [comment]
dupe https://github.com/facebook/react-native/pull/3016
