### ISSUE TITLE
ES6 string.includes does not work on IOS 8 (it works on ios9)

### ISSUE THREAD

**Issue by anback** [facebook/react-native#5727]
Spent like two says debugging this and it boiled down to that "ES6 string.includes does not work on IOS 8"

Tested on IOS 9 it works. I have switched to good ole string.indexOf for now and now my app runs smoothly.

When debugging you dont see this as the code runs in a chrome browser (hence hard to discover)

React Native version 0.19.
Ios version 8.4.1

![image](https://cloud.githubusercontent.com/assets/2440382/12778727/a274dd5e-ca64-11e5-954c-5cdf95a558dd.png)

**Comment by anback** [comment]
spent like two **d**ays

**Comment by janicduplessis** [comment]
Thanks for finding this, javascript runtime environment differences are a pain -_-

We should add this polyfill https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/includes to `packager/react-packager/src/Resolver/polyfills/String.prototype.es6.js`

Would you be interested in submitting a PR to do it?
