### ISSUE TITLE
React Native Picker for android does not exist in the latest stable release

### ISSUE THREAD

**Issue by cubbuk** [facebook/react-native#5730]
Hi,

In the official documents; there is a section for picker which states that it can be used for both android and IOS. However I am using the 0.18.1 and there isn't any implementation for `Picker`. Is it just a mistake in the documents or will that be part of 0.19? And if so could you estimate when that will be ready or should I look for some other solution?

https://facebook.github.io/react-native/docs/picker.html#content

Thanks.

**Comment by satya164** [comment]
Currently docs are generated from master branch. Picker should be part of next release.
