### ISSUE TITLE
iOS: Cannot use Linking API?

### ISSUE THREAD

**Issue by mbrochh** [facebook/react-native#5749]
I'm trying to open an external URL in Safari like this:

```
import React from "react-native";
import { Linking, ...other stuff } from  "react-native";

export default class MyComponent extends React.Component {
  handlePress() {
    Linking.openURL("https://google.com"); 
  }
}
```

I'm getting the following error: 

```
undefined is not an object (evaluating 'Linking.openURL')
```

Am I doing this wrong?

**Comment by bartolkaruza** [comment]
@mbrochh You should import LinkingIOS (instead of Linking) for IOS and IntentAndroid for Android.
If you want a nice wrapper for those two (to make it work for both IOS and Android, checkout https://www.npmjs.com/package/react-native-communications

**Comment by satya164** [comment]
`Linking` will be in next version of RN. Currently the docs are generated from the master branch. So it's a bit confusing.
