### ISSUE TITLE
Add CameraIOS API to take pictures

### ISSUE THREAD

**Issue by danicomas** [facebook/react-native#575]
Would be amazing if the picture was returned in Base64 similar than http://ngcordova.com/docs/plugins/camera/

**Comment by vkurchatkin** [comment]
What's the point of having base64 representation? seems just a waste of CPU

**Comment by danicomas** [comment]
To send via WS is a good way using base64. What is your proposal @vkurchatkin?

**Comment by vjeux** [comment]
The way we deal with images in React Native is that we keep the image data in obj-c land and only pass a handle (a small string) to JS. Then we can send this handle to <Image> to display it, send to an image manipulation library to apply filters, save to cameraroll... This way we don't have to copy this huge image twice.

**Comment by danicomas** [comment]
If you have to send this image via WS you need to send this handle @vjeux?

**Comment by vkurchatkin** [comment]
Transferring images as base64 is a waste of both CPU and traffic (~33.3%)

**Comment by vjeux** [comment]
@danicomas: have your websocket bindings know how to send this image handle. For example our internal implementation of XHR.send(image) will send the raw data when passed an image handle (we need to reproduce this feature in open source btw).

**Comment by danicomas** [comment]
Nice @vjeux We will need to wait for this.

**Comment by thanzen** [comment]
+1

**Comment by rt2zz** [comment]
@vjeux do image "handles" exist in open source react-native? I do not see anything in `RCTConvert.m`

**Comment by nicklockwood** [comment]
The "handles" are just urls. They reference an image in the camera roll, or a temporary local file.

**Comment by brentvatne** [comment]
@danicomas - not using websockets but you could adapt this accordingly: https://github.com/kamilkp/react-native-file-transfer

**Comment by kahunamoore** [comment]
@vjeux - I'm using React Native and have a websocket that delivers raw image data (RGBA video frames) that I need to display at around 20 fps but I can't find a way to get Image or any other RN component to display raw data. Most components assume they will load the data (and decode it) before displaying it. I just need to display existing data stored in an ArrayBuffer.

Our existing webapp (pure JS) uses the websocket to get the data and displays it directly on a canvas element. This works great for our purposes. Is there a viable replacement for the canvas element in React Native or is there a way to get the Image component to load raw data without creating my own react image loader or writing to a local/temp file?

Thanks in advance!

**Comment by nicklockwood** [comment]
@kahunamoore you can pass the `<Image/>` component a base64-encoded image url. If you can efficiently convert your video frames to base64 on the JS side then that might work. I suspect that won't be fast enough, but it's probably the first thing you should try.

The ideal solution would be to pass the data directly from the native web socket to the native imageView without the round trip via JS (which actually involves two base64 conversions both ways), but setting that up will involve a lot of complex changes to the way React Native works, and we'd have problems with tracking the lifecycle of the data to avoid memory leaks.

**Comment by kahunamoore** [comment]
That is kind of what I thought... although I didn't realize the existing base64 encoding happening on the websocket. My other thought was to try to leverage one of the opengl/webgl components. TBD.

Thanks for the quick response!
