### ISSUE TITLE
react-native bundle with --dev false fails with runtime error

### ISSUE THREAD

**Issue by andpor** [facebook/react-native#5755]
if --dev is true seems to not fail. this is Xcode 7 and React 0.18

![screen shot 2016-02-04 at 2 11 32 pm](https://cloud.githubusercontent.com/assets/10236571/12815877/6e99c5fe-cb49-11e5-87fe-44caaf3d8013.png)

**Comment by grabbou** [comment]
This looks like a babel issue that was likely fixed as we have upgraded it quite a few times in the meantime. Would you mind reporting if this issue still exists?
