### ISSUE TITLE
Can't build release version of app - __fbBatchedBridge is undefined

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5770]
I've got an app ready to go live, but I'm unable to build a release version.

Steps I took:

1. In Xcode, edited the scheme and set Build Configuration to Release and unchecked "Debug executable."
2. In Terminal, ran `react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --resetCache`
3. Set Xcode build target to Simulator (5s, iOS 9.3) and hit run.

I get the following error:

```
2016-02-04 18:59:17.582 [error][tid:com.facebook.React.JavaScript] Unable to execute JS call: __fbBatchedBridge is undefined
2016-02-04 18:59:17.585 SydTechEco[76215:10166934] *** Terminating app due to uncaught exception 'RCTFatalException: Unable to execute JS call: __fbBatchedBridge is undefined', reason: 'Unable to execute JS call: __fbBatchedBridge is undefined'
```

**Comment by ffxsam** [comment]
The strange thing is, I can build/run a release version on my physical device, but not Simulator.

**Comment by stereodenis** [comment]
got this on 0.19

**Comment by ffxsam** [comment]
It also happens on a totally fresh project with literally no code added.

**Comment by stereodenis** [comment]
when I run `react-native run-ios` i got this
```
/bin/sh -c /Users/stereodenis/work/evrone/WTCCEuroSport/ios/build/Build/Intermediates/WTCCEuroSport.build/Debug-iphonesimulator/WTCCEuroSport.build/Script-00DD1BFF1BD5951E006B06BC.sh
Skipping bundling for Simulator platform
```

**Comment by stereodenis** [comment]
@javache Why bunling is skipping for Simulator platform?

**Comment by javache** [comment]
Because on the simulator, you'll use a local packager server to serve up the bundle contents.

**Comment by stereodenis** [comment]
@javache when I want to try bundled app on simulator — what should I do?

**Comment by javache** [comment]
You can uncomment these line in react-native-xcode.sh: https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh#L15-L18 and make sure your rootview/bridge config points to the right JS file.

**Comment by stereodenis** [comment]
@javache it's a dirty hack)

**Comment by javache** [comment]
Yeah, we don't use this system internally, and it's mostly aimed at making this work fast for the default use case. You can always create a copy of this script, modify it and use that copy instead in your xcode project.

**Comment by stereodenis** [comment]
@javache thanks for advice!

**Comment by ffxsam** [comment]
Any responses as to the bug reported in the first post on this thread?

**Comment by ffxsam** [comment]
Thanks. Commenting out that part of the script worked.

**Comment by pedramsaleh** [comment]
I got this same error on 0.20.0, and it was because my Appdelegate.m file had the line for running on the simulator uncommented, and I was trying to run on a physical device.  I switched back to the other line and it ran fine.

**Comment by dorthwein** [comment]
+1 commenting out the lines as @javache pointed out worked for me as well in react 0.20.0

**Comment by miracle2k** [comment]
@chetstone Change that line too; I have my script in the project's ios folder, and I write:

    REACT_NATIVE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/node_modules/react-native"

**Comment by gre** [comment]
also fall into this and found out the script is `"Skipping bundling for Simulator platform"` .. I think it's wrong, you shouldn't prevent us from testing the "bundle" mode on the simulator.

**Comment by joostlubach** [comment]
I also think this is wrong. Especially since Facebook (!!) requires a working Simulator version for App Review. It makes much more sense to use Debug / Release configs as a determinator whether a bundled version should be created / used, or whether the local packager should be used.

**Comment by ffxsam** [comment]
Nice to see some other voices join in here. I still feel that, out of the box, it should not fail when using bundle mode in the simulator.

**Comment by stereodenis** [comment]
I hope we will not have to change every time the build options

**Comment by gre** [comment]
I just upgraded to RN 0.22 and this somehow get improved though. Now, the script will only not run if you are not Debug/Dev mode, which quite make sense because you should run Debug with a dev server and "Release" mode with the bundle mode.
so maybe it makes sense?

**Comment by andresn** [comment]
I am now seeing the same as @gre, and the lines from @javache's temp solution are now off, here's the full diff with the improvement (thank you RN team btw!):
https://github.com/facebook/react-native/commit/9ae3714f4bebdd2bcab4d7fdbf23acebdc5ed2ba#diff-e35d320a1bf991537277377d63b968e9

**Comment by kwelch** [comment]
I am still getting this error. I am using RN0.22.

I am NOT using a simulator though, I am attempting with an iPad mini. 

I am attempting to "Run" from within XCode, I had done the exact steps as the OP.

**Comment by mtford90** [comment]
+1 on 0.22.2

**Comment by mschipperheyn** [comment]
+1 on 0.24.1

**Comment by lionrock** [comment]
+1 on 0.25.1

**Comment by vitalbone** [comment]
Similar to @kwelch, I needed to do a manual upgrade from 0.13 -> 0.14.
Was able to fix issue on 0.21.0 by following the _Manual Upgrades_ section of https://facebook.github.io/react-native/docs/upgrading.html#from-0-13-to-0-14

**Comment by mschipperheyn** [comment]
I had this issue and a number of others. I finally resolved mine by removing babel stage-0, stage-1, stage-2 presets and using the 
"react-native",
"react-native-stage-0",
"react-native-stage-0/decorator-support"

in my .babelrc
Not sure, if this resolves this issue since it's one of those rabbit holes, but have a look if this does the trick for you.

**Comment by alexprice91** [comment]
I too am having this issue. I am using xcodebuild to generate an ipa so that I can use that to test with appium. 

It looks like I can run the app in "release" mode fine when I run my app on a simulator. The issue comes when I load the ipa generated from xcodebuild onto a simulator.

**Comment by aarmand** [comment]
+1 on 26.2 
Alains-MacBook-Pro:AwesomeProject klik$ nvm alias
default -> node (-> v5.2.0)
node -> stable (-> v5.2.0) (default)
stable -> 5.2 (-> v5.2.0) (default)
iojs -> N/A (default)
Alains-MacBook-Pro:AwesomeProject klik$ watchman version
{
    "version": "4.5.0"
}
Alains-MacBook-Pro:AwesomeProject klik$ npm -g react-native-cli -v
3.3.12
Alains-MacBook-Pro:AwesomeProject klik$ react-native -v
react-native-cli: 0.2.0
react-native: 0.26.2

**Comment by dlahyani** [comment]
+1 on 0.26.0
The weird thing is that it happens on my mac pro but not on my mack book.
I completely removed node and any installed node modules, removed watchman and reinstalled them back just to make sure I have the same environment on both machines. Same node, npm and watchman version, exact same node modules installed (both globally and locally). And yet on the mac book everything works fine on the mac pro i get this error.

Notice that i also got stack trace in XCode console as soon as the JS bundle is loaded:
```
2016-06-27 12:35:47.795 [error][tid:com.facebook.react.JavaScript] Error: babelHelpers.typeof is not a function. (In 'babelHelpers.typeof(global)', 'babelHelpers.typeof' is undefined), stack:
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:24062:61
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:23176:8
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:52:37
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  global code@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:77564:9


2016-06-27 12:35:47.798 [error][tid:com.facebook.react.JavaScript] Error: Can't find variable: process, stack:
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:2287:11
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:1961:20
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:1604:25
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:1434:26
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:1417:23
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:59:32
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:1408:19
  loadModuleImplementation@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:105:8
  guardedLoadModule@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:52:37
  _require@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:43:18
  global code@http://localhost:8081/jssrc/index.ios.bundle?platform=ios&dev=true:77566:9


2016-06-27 12:35:49.637 [fatal][tid:main] Unable to execute JS call: __fbBatchedBridge is undefined
```
Which makes me suspect Babel...

**Comment by evanmrose** [comment]
@dlahyani +1, I'm getting the same error. Have tried numerous fixes.

**Comment by justsans** [comment]
Getting the same error on any newly created react-native app without any code changes or when trying to run the examples under react-native/Examples

I am creating react-native apps with the command
react-native init AwesomeApp

node: v6.2.2
npm: 2.15.5
ruby: ruby 2.3.1p112

**Stack trace:** 
2016-06-27 12:05:50.628 [error][tid:com.facebook.react.JavaScript] Error: babelHelpers.typeof is not a function. (In 'babelHelpers.typeof(global)', 'babelHelpers.typeof' is undefined), stack:
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:23228:61
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:22335:8
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:63:37
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
global code@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:76191:9
2016-06-27 12:05:50.635 [error][tid:com.facebook.react.JavaScript] Error: Can't find variable: process, stack:
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2428:11
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:2076:20
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:1711:25
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:1541:26
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:1524:23
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:70:32
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
http://localhost:8081/index.ios.bundle?platform=ios&dev=true:1474:19
loadModuleImplementation@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:127:8
guardedLoadModule@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:63:37
_require@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:54:18
global code@http://localhost:8081/index.ios.bundle?platform=ios&dev=true:76192:9
2016-06-27 12:05:52.453 [fatal][tid:main] Unable to execute JS call: __fbBatchedBridge is undefined

**Comment by dlahyani** [comment]
@evanmrose @justsans I think i managed to solve this on my mac, it took me the whole day to figure this out.
First of all I add the `--reset-cache` flag to my 'npm start' script, this caused the project to fail on my mac book as well (previously it was working on my mac book but not on my mac pro).
Secondly I removed the `.babelrc` file in the root of my project (i.e. the one that resides in the same directory as the `package.json`).
And finally I fixed the version of babel modules and plugins versions to match those used by RN (I am not sure if this one really did change anything). So my package.json looks something like that:
```
"scripts": {
    "lint": "eslint",
    "start": "node node_modules/react-native/local-cli/cli.js start --reset-cache",
    "test": "mocha --require ./jstestutils/mocha-require --compilers js:babel-core/register --recursive ./jstests"
  },
  "dependencies": {
    "react": "15.0.2",
    "react-native": "0.26.0"
  },
  "devDependencies": {
    "babel-core": "6.6.4",
    "babel-polyfill": "6.6.1",
    "babel-preset-es2015": "6.5.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-native": "1.9.0",
    "babel-preset-stage-0": "6.5.0",
    "babel-register": "6.6.0",
    "enzyme": "2.3.0",
    "expect": "1.20.1",
    "mocha": "2.4.5",
    "react-addons-test-utils": "15.0.2",
    "react-dom": "15.0.2",
    "react-native-mock": "0.2.2"
  }
```

Let me know if it did help you guys.

**Comment by sydneyitguy** [comment]
+1 on 0.28.0
It just suddenly happened few minutes ago without any code changes.

**Comment by mschipperheyn** [comment]
I've had this shit happen to me several times and it always seemed to suddenly happen. I finally figured out that it had to do with babelrc and certain wrong presets I was loading into the project. https://github.com/facebook/react-native/issues/4844 Try going to back to the bare bones babelrc you really really need and remove any babel-presets you're loading into the project. 

My .babelrc is this:

    {
      "presets": [
        "react-native",
        "react-native-stage-0",
        "react-native-stage-0/decorator-support"
     ]

   }

**Comment by gabs24** [comment]
For those like me who may spend a day figuring out why they have the error "Unable to execute JS call: __fbBatchedBridge is undefined" after they upgrade to OS x El Capitan 10.11 with react-native 0.29
When upgrading, the owner of usr/local changes and then the watchman can't run so you have to exec a chown on that folder so that it belongs to you.
Once done, you will be able, in the folder of your project, to start again npm and finally to build your app without this error ;)

**Comment by sysco-dev** [comment]
@gabs24  could you explain which folder are you talking about. I do not have  a usr/local folder. Thanks for the update as I am struggling with this problem for a long time now.

**Comment by justsans** [comment]
@gabs24 Could you give more information on the folder you mentioned. Why is the usr/local folder important?. Can you explain which folder you are exactly talking about. 

Really appreciate your input as I have been stuck with this issue for a while now.?

**Comment by gabs24** [comment]
Sure, just execute this command in your terminal : sudo chown $(USER):admin /usr/local
Indeed you (your user) need to be admin of that folder so that the watchman can run.
That way, the watchman will be able to run for the run-ios command of react native.

**Comment by dmr** [comment]
I'm not sure if my case applies here but I had the "__fbBatchedBridge is undefined" issue when I tried to build a production app and the reason was that my "schema" in XCode was set to "Debug". --> Changing to "Release" fixed the issue.

<img width="896" src="https://cloud.githubusercontent.com/assets/128286/16853764/18532188-4a0e-11e6-93b3-eb9aece95152.png">

**Comment by natdm** [comment]
.25 to .29 - getting this. Can't seem to get it to work with any of the above suggestions. Only on a physical device, not emulator.

**Comment by sysco-dev** [comment]
None of the above solutions worked for me. Finally I updated my version to an old version which worked.  The following versions worked for me.
    "react": "^15.1.0",
    "react-native": "^0.27.2"

**Comment by tuneZola** [comment]
Your probably getting this because you are trying to use option 2, bundling in your AppDelegate.m file. You should be using option one when using the simulator, but this all changes for RN .30.

**Comment by dmr** [comment]
Cool. When will .30 be ready?

**Comment by dmr** [comment]
^^

**Comment by tuneZola** [comment]
Its ready now,  just make sure you run `react-native upgrade`

**Comment by phil-travelbytes** [comment]
`react-native upgrade` worked for me. 
thanks @tuneZola

**Comment by javache** [comment]
The deployment issues mentioned in this thread should all be solved, or depend on individual project's configuration. Please open a new issue if the cause of this error message is different.

**Comment by worldlyjohn** [comment]
still seeing this with RN 0.33.0 and React 15.3.1

**Comment by az-9** [comment]
My app starting to show this error in the middle of the developing.
Delete the app from the simulator and run `react-native run-ios`

**Comment by jjant** [comment]
Still seeing this on 0.45.0

**Comment by aterribili** [comment]
Still seeing this on 0.46.1

**Comment by webjay** [comment]
I'm getting it on 0.47.1

**Comment by shuang1026** [comment]
I'm getting it on 0.47.2

**Comment by poberwong** [comment]
I'm getting it on 0.50.3

**Comment by changran52m** [comment]
+1 same error on 0.51.0
