### ISSUE TITLE
Writing iOS utilities using bridge: is RCTViewManager the right vector for extension?

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#578]
I'm currently writing an article on one dimension of writing ObjC <> JavaScript, which is the development of utilities (non-UI native code).

From my digging in the recent past, I've found that extending RCTViewManager is a vector that gets me to that goal.  Does anyone have any suggestions on another class to extend for utility-only native extensions?

```
#import "RCTViewManager.h"
 
@interface MCFileWriterUtil : RCTViewManager
...
```

**Comment by joshaber** [comment]
The push notification example might be a good one to draw inspiration from: https://github.com/facebook/react-native/tree/master/Libraries/PushNotificationIOS

Looks like implementing `RCTBridgeModule` is the way to go.

**Comment by tadeuzagallo** [comment]
`RCTViewManager` is a view manager, as the name suggests...
If you just want to expose methods to JavaScript what you need is a `RCTBridgeModule`, that is a `@protocol`.

**Comment by jaygarcia** [comment]
Fantastic. Thanks ;)

**Comment by jaygarcia** [comment]
FTR,

Code changed as such, works like an offing champ. 
``` 
#import  "RCTBridge.h"

@interface MCFileWriterUtil : NSObject <RCTBridgeModule>


```
