### ISSUE TITLE
[Bridge] Native module inside framework

### ISSUE THREAD

**Issue by voximplant** [facebook/react-native#579]
Is there a way to implement native module inside framework instead of static library?

**Comment by a2** [comment]
As of now, this is not possible because React Native looks for all [RCT_EXPORT](https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/React/Base/RCTBridgeModule.h) entries in its binary.

**Comment by voximplant** [comment]
Sometimes developer needs to use native modules inside frameworks. For example, it's required to avoid build problems because of the conflicts between 3rd party libs code and React Native libs.
Can we propose to extend React Native functionality to let Objective-C class that implements RCTBridgeModule has an option to return list of methods for export to JS?

**Comment by drkibitz** [comment]
Not exactly sure I am following this issue, but I'm interested. Is the question if you can add a new Framework that utilizes react native and exposes functionality?

**Comment by ide** [comment]
@drkibitz yes, if you publish e.g. a keyboard component that has some native code, it currently has to be distributed as a static library. This means you can't write helper code in Swift without splitting it out into a separate framework.

So far I've found RCT_EXPORT easy to type and maintain so it would be nice to keep it or something very similar. Maybe it (or a new macro) could generate dummy methods that RCTBridge knows to scan for?

**Comment by a2** [comment]
Alright, I'm currently working on an updated version of `RCT_EXPORT` and I will look into making this possible.

**Comment by ide** [comment]
@a2 That sounds really great. One of the practical benefits of framework support is that you can use CocoaPods containing Swift -- if a pure-ObjC pod (e.g. a React module) depends on a pod with Swift code (e.g. Alamofire, whatever) then CocoaPods builds both as frameworks.

**Comment by voximplant** [comment]
@a2 sounds good, will be waiting eagerly!

**Comment by tptee** [comment]
:+1: this is the last thing blocking my WebSockets native extension: https://github.com/tptee/RCTWebSocket

This'll help distribution/CocoaPods interop immensely.

**Comment by voximplant** [comment]
Any news?

**Comment by tptee** [comment]
https://github.com/facebook/react-native/pull/982 is done, which is awesome, but I'm not sure frameworks  work yet. When CocoaPods builds a framework, it spits all of the project's headers into one folder, and a few headers in React Native reference relative paths. This breaks clang modules, which CocoaPods framework support depends on. So while we can write extensions in Swift, we can't deliver them in a clean way yet :/

**Comment by nicklockwood** [comment]
That's true. I'm working on it :-)

**Comment by tptee** [comment]
👍

**Comment by tptee** [comment]
As of 0.4.1 I can successfully build a framework linked to React with the new Swift export macros. However, when I import the framework module into a React Native app target, I get the following:

```
Class WebSocketManager was not exported. Did you forget to use RCT_EXPORT_MODULE()?
```

Any ideas? Looks like RCT_EXTERN_MODULE didn't export the class from the framework correctly.

**Comment by nicklockwood** [comment]
That's correct, we still don't support modules linked from dynamic libraries yet. That's coming soon.

**Comment by tptee** [comment]
Cool, thanks for the update!

**Comment by yusefnapora** [comment]
To update this, as of 0.7.0-rc.2, I was able to define a module in a shared framework and use it from an iOS app target.  The new module loading system seems to have done away with embedding strings into the binaries to a registration system based on defining `+ (void) load` on native module classes.

As far as I can tell, things work perfectly.  Adding React to an existing project using CocoaPods with `use_frameworks!` runs without issue, and you can define native modules in frameworks.

**Comment by ide** [comment]
@yusefnapora thanks for the update!

**Comment by colinhang** [comment]
@yusefnapora  @nicklockwood Has this issue been fixed? Could you please show me the commit? I a m still not able to link dynamic library (.framework) into my RN project. There are many 3rd party solutions to create native UI components using objective-c and we can easily integrate them into a RN project as they target static library.
