### ISSUE TITLE
Fail to build UIExplorer for android because missing JSModulesUnbundle.cpp

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native#5790]
I clone the master branch yesterday and I found that I fail to run 

`./gradlew :Examples:UIExplorer:android:app:installDebug --stacktrace`

In commit cc926211b61d305b0cc61faa55fc4329bb456898 ,
it rename the file to **JniJSModulesUnbundle.cpp**

> make: Entering directory `/home/vshy/Documents/react-native/ReactAndroid/src/main/jni/react/jni'
> [armeabi-v7a] Compile++ thumb: reactnativejni <= OnLoad.cpp
> [armeabi-v7a] Compile++ thumb: reactnativejni <= ProxyExecutor.cpp
> 
> make: *** No rule to make target `/home/vshy/Documents/react-native/ReactAndroid/src/main/jni//react/JSModulesUnbundle.cpp', needed by `/home/vshy/Documents/react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/objs/reactnative/JSModulesUnbundle.o'.  Stop.
> make: *** Waiting for unfinished jobs....
> [armeabi-v7a] Compile++ thumb: reactnative <= JSCWebWorker.cpp
> make: Leaving directory `/home/vshy/Documents/react-native/ReactAndroid/src/main/jni/react/jni'
> :ReactAndroid:buildReactNdkLib FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> > Process 'command '/home/vshy/Android/android-ndk-r10e/ndk-build'' finished with non-zero exit value 2
> 
> * Try:
> Run with --info or --debug option to get more log output.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ReactAndroid:buildReactNdkLib'.
>

**Comment by janicduplessis** [comment]
The build with gradle is broken on master at the moment, see #5791

**Comment by vshy108** [comment]
@janicduplessis I success to build it after refer to the changes in #5791, thanks

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/62440b86b04839583bbab0199be997ce1e868a73
