### ISSUE TITLE
socket.io not working with v0.19 it was working before

### ISSUE THREAD

**Issue by liesislukas** [facebook/react-native#5798]
Trying to use socket.io with React native. It seems, like it was possible to connect these 2 around November-December, 2015. I found related stackoverflow question and also video on Youtube
http://stackoverflow.com/questions/29408492/is-it-possible-to-combine-react-native-with-socket-io
https://www.youtube.com/watch?v=iR360rOT8Qc

But now, it's just not connecting to socket. It seems I'm not alone having this issue:

http://stackoverflow.com/questions/35220546/is-react-native-v0-19-version-currently-unusable-with-socket-io

maybe it could be fixed in v0.20? Or at least any guidelines how to make work around for now

**Comment by christopherdro** [comment]
@liesislukas Not sure what your actual use case is but it might be worth it to look into implementing the built in [WebSocket](http://facebook.github.io/react-native/docs/network.html#websocket) api.

This won't work out of the box when trying to connect to a socket.io server. However, you can just setup a standard [ws](https://www.npmjs.com/package/ws) server.

Here is an [gist](https://gist.github.com/zeusdeux/5491cff541fb4ac4c142) that compares both implementations.

**Comment by liesislukas** [comment]
i already have web app all depended on socket.io. I could create another service just for mobile apps, but then trying to make GCM work. No luck yet. Socket connection would eat battery a lot more.

**Comment by christopherdro** [comment]
@liesislukas Still having this issue? Could you share some code or the what the actual error is that your getting?

Also, how would using built in websocket vs socket.io drain the battery more?

**Comment by liesislukas** [comment]
Decided to use GCM, because GCM vs socket would save battery.

**Comment by Pau1fitz** [comment]
I am having lots of difficulties setting up react-native with socket.io.

Below is my react native component and node server.js code  that I am trying to connect to my node websocket backend.

My react code is running on the same computer as the server. I have found so many varying answers on here, and github, none of which I can get working.

I also found this [question][1] which was never answered, and [this question][2] has an answer, which I cannot get working (was asked over a year ago)

I have found [this article][3] and tried to amend my code based on these guidelines but this did not work.

**react code**  

    import React from 'react';
    import { StyleSheet, Text, View, Image } from 'react-native';
    
    import io from 'socket.io-client';
    let socket = io('http://localhost:3000');
    
    export default class App extends React.Component {
    
        constructor(props) {
            super(props);
            console.log(socket);
        }
    
        render() {
            return (
                <View>
                    <Text>Websocket</Text>
                </View>
            );
        }
    }

**server.js**

    const express = require('express');
    const http = require('http')
    const socketio = require('socket.io');
    
    const app = express();
    const server = http.Server(app);
    const websocket = socketio(server);
    server.listen(3000, () => console.log('listening on *:3000'));
    
    console.log(websocket)
    
    // The event will be called when a client is connected.
    websocket.on('connection', (socket) => {
      console.log('A client just joined on', socket.id);
    });


  [1]: http://stackoverflow.com/questions/37505661/react-native-with-socket-io-doesnt-work?rq=1
  [2]: http://stackoverflow.com/questions/29408492/is-it-possible-to-combine-react-native-with-socket-io
  [3]: https://medium.com/@ekryski/how-to-actually-use-socket-io-in-react-native-39082d8d6172
