### ISSUE TITLE
npm installing a new package causes packager to error

### ISSUE THREAD

**Issue by rimunroe** [facebook/react-native#580]
While running a project with live reload, running npm install yields an error message on my device saying:

> react-packager has encountered an internal error, please check your terminal error output for more details

In my terminal, I see the following error `Error: EISDIR, read`. After this happens, clicking reload JS yields the same error message again in both the terminal and the app. Shutting the project down and rebuilding/running it fixes the problem.

It seems to be independent of which module is being installed, and it doesn't matter if the module is actually required anywhere in the JavaScript.

(I'm on OS X 10.10)

**Comment by ericvicenti** [comment]
I think this is the same as https://github.com/facebook/react-native/issues/406, but I haven't seen the `Error: EISDIR, read` error

**Comment by rimunroe** [comment]
I don't believe so, because that one appears to have to do with the `requires` not working, whereas this bug happens even if the module isn't required at all. Also, the requires work fine once the packager is restarted.

**Comment by rimunroe** [comment]
I think this can also be called by making any change to the directory structure in node_modules/. I just ran `$ mkdir node_modules/bloop` and encountered the same problem.

**Comment by ericvicenti** [comment]
Ah. I haven't seen this bug, but it is definitely something with the packager. cc @amasad

**Comment by amasad** [comment]
Fixed via 2cced4b94056770e923e3dba45d5f54506862ea9

**Comment by amasad** [comment]
published v0.3.3

**Comment by oSpring** [comment]
should close all of the window include Xcode terminal and and restart again. should fix this.
