### ISSUE TITLE
'Unknown Plugin' error when creating a new project

### ISSUE THREAD

**Issue by mikeborozdin** [facebook/react-native#5804]
I have updated `react-native-cli` to version`0.1.10` and I get this error when calling `react-native init`:

>ReferenceError: Unknown plugin "syntax-async-functions" specified in "<my-app>/node_modules/react-native/local-cli/bundle"

**Comment by ajwhite** [comment]
Same issue, can't start any new projects here on `0.1.7`

**Comment by uiruson** [comment]
Same issue, version 0.1.10

**Comment by TheGreggle** [comment]
This has now been fixed. After troubleshooting the missing packages I came across the error posted here https://github.com/facebook/react-native/issues/5806.

There just committed a fix. Running init now appears to work for me.

**Comment by kittens** [comment]
@ajwhite @uiruson @mikeborozdin This should be fixed, can any of you confirm?

**Comment by TheGreggle** [comment]
@kittens Definitely fixed it for me. Thanks!

**Comment by kittens** [comment]
Great, thanks for confirming @TheGreggle! Please ping this issue if this is still a problem and I'll look into it further.

**Comment by ajwhite** [comment]
:+1:  here as well, ty @kittens!

**Comment by uiruson** [comment]
here as well thanks guys!

**Comment by mikeborozdin** [comment]
@kittens this has fixed it for me! Thanks a lot!
