### ISSUE TITLE
Proposal: Support UIViewController with custom components

### ISSUE THREAD

**Issue by lucasfeliciano** [facebook/react-native#5807]
I'm creating a custom component using a external SDK ( Scandit ).

The problem is: 

The `view` method from `RCTViewManger` needs to return a  instance of `UIView` but the Scandit SDK provides me a `UIViewController` instance.

I can change the rootViewController with the ScanditViewController but doing that I lose the navigation and I can't render others react components in the same scene.

**Comment by nicklockwood** [comment]
We have a couple of other components that wrap UIViewControllers, such as Navigator and TabBarIOS. Might be worth taking a look at how they are implemented.

The basic idea is that your component returns a view, but when that view is mounted, it walks up the responder chain to find the nearest parent view controller, then creates a view controller instance of its own and inserts it into the VC hierarchy.

In this way, we invert the normal order of things by having our views manage their view controllers instead of the other way round, which may seem a little weird, but it allows us to keep the concept of View Controllers out of the client side abstraction, and leave them as an iOS-specific implementation detail.

**Comment by lucasfeliciano** [comment]
- RCTScandit.m
```objectivec
#import "RCTScandit.h"
#import <ScanditBarcodeScanner/ScanditBarcodeScanner.h>
@implementation RCTScandit

/*
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
*/

-(void)viewDidLoad {
  [super viewDidLoad];

  [self overlayAsView];

}

- (void)barcodePicker:(SBSBarcodePicker *)picker didScan:(SBSScanSession *)session {
  NSArray* recognized = session.newlyRecognizedCodes;
  SBSCode *code = [recognized firstObject];
  // add your own code to handle the barcode result e.g.
  NSLog(@"scanned %ld barcode: %@", (long)code.symbology, code.data);
}

- (void)overlayAsView {

  SBSScanSettings* scanSettings = [SBSScanSettings defaultSettings];
  scanSettings.cameraFacingPreference = SBSCameraFacingDirectionBack;
  [scanSettings setSymbology:SBSSymbologyEAN13 enabled:YES];
  [scanSettings setSymbology:SBSSymbologyUPC12 enabled:YES];
  [scanSettings setSymbology:SBSSymbologyQR enabled:YES];

  self.picker = [[SBSBarcodePicker alloc] initWithSettings:scanSettings];
  self.picker.scanDelegate = self;

  [self addChildViewController:self.picker];
  [self.view addSubview:self.picker.view];
  [self.picker didMoveToParentViewController:self];

  [self.picker startScanning];

}
@end
```

- RCTScanditManager.m
```objectivec
#import "RCTScanditManager.h"
#import "RCTScandit.h"

@implementation RCTScanditManager
RCT_EXPORT_MODULE();

- (UIView *)view
{
  RCTScandit *scandit = [[RCTScandit alloc] init];
  return scandit.view;
}


@end
```

This is what I have.
I'm returning the view property of the UIViewController.
If I run this code in a native iOS project it works fine.
When I try to run as a react-native component it renders the view overlay but the camera doesn't start. 

The app even ask for camera permission but the part of the camera in the view stays black.

I debugged it and it is passing through the part of the code which start the camera, so I kinda don't know what to expect.

I'm not a iOS developer so I'm struggling to gather some knowledge about the iOS concepts and functionalities

**Comment by nicklockwood** [comment]
@lucasfeliciano the RCTScandit instance will be released as soon as the view has been created and returned in the RCTScanditManager.m file, as you aren't retaining any references to it.

Instead of making RCTScandit a UIViewController subclass, make it a UIView subclass, and return it directly instead of returning its view. Something like this:

- RCTScandit.m
```objectivec
#import "RCTScandit.h"
#import <ScanditBarcodeScanner/ScanditBarcodeScanner.h>
@implementation RCTScandit

/*
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
*/

- (void)barcodePicker:(SBSBarcodePicker *)picker didScan:(SBSScanSession *)session
{
  NSArray *recognized = session.newlyRecognizedCodes;
  SBSCode *code = [recognized firstObject];
  // add your own code to handle the barcode result e.g.
  NSLog(@"scanned %ld barcode: %@", (long)code.symbology, code.data);
}

- (instancetype)initWithFrame:(CGRect)frame
{
  if ((self = [super initWithFrame:frame])) {
    SBSScanSettings* scanSettings = [SBSScanSettings defaultSettings];
    scanSettings.cameraFacingPreference = SBSCameraFacingDirectionBack;
    [scanSettings setSymbology:SBSSymbologyEAN13 enabled:YES];
    [scanSettings setSymbology:SBSSymbologyUPC12 enabled:YES];
    [scanSettings setSymbology:SBSSymbologyQR enabled:YES];

    self.picker = [[SBSBarcodePicker alloc] initWithSettings:scanSettings];
    self.picker.scanDelegate = self;

    [self addSubview:self.picker.view];

    [self.picker startScanning];
  }
  return self;
}

- (void)layoutSubviews
{
  [super layotuSubviews];
  self.picker.view.frame = self.bounds;
}

@end
```

**Comment by lucasfeliciano** [comment]
@nicklockwood Thank you for your reply man.

I got some progress here.

I make those changes and now the view doesn't show anything besides a white screen in the other hand it is handling the scan.

I can put a barcode in front of the camera and it is logging into the console the barcode.

I'll keep debugging here to try to figure it out what is going on, but if you have anything in mind let me know :)

**Comment by lucasfeliciano** [comment]
Maybe because the frame is `0 0`?
`<RCTScandit: 0x1366de9d0; frame = (0 0; 0 0); layer = <CALayer: 0x1366deb50>>`

**Comment by nicklockwood** [comment]
The frame of RCTScandit will also be zero when it's created. It will then be updated after layout happens. The purpose of the layoutSubviews method is to update the underlying picker view's frame to match RCTScandit when that happens.

**Comment by lucasfeliciano** [comment]
yeah, make sense but I need to call the the `initWithFrame` method, right?

`RCTScandit *scandit = [[RCTScandit alloc] initWithFrame:CGRect];`

Like this, and probably create the CGRect with the size of my screen, right?

How can I get this values from the `RCTScanditManager.m`

This are the headers that I'm importing

```objective-c
#import "RCTBridge.h"
#import "RCTViewManager.h"
#import "RCTScandit.h"
```

**Comment by nicklockwood** [comment]
No. `[[RCTScandit alloc] init]` calls `[[RCTScandit alloc] initWithFrame:CGRectZero]` which is the expected behaviour. The frame will be set later by React Native - you shouldn't set it when the view is created because the frame is controlled by flexbox.

Of course, if you aren't setting the view size in your JS component styles then it will still have a size of zero.

**Comment by lucasfeliciano** [comment]
Got it. 
And makes sense.

Question, when the code execute the startScanning method is the component already rendered?

`[self.picker startScanning];` 


Because the camera is working if I put a barcode in front of the camera it calls the callback and print the code but there is no camera rendered.

![img_0792](https://cloud.githubusercontent.com/assets/968014/13224367/805a3c22-d988-11e5-88cc-1db4eaca90bd.PNG)

**Comment by nicklockwood** [comment]
> when the code execute the startScanning method is the component already rendered?

No, it wouldn't be. If you want to defer the scanning until the component is rendered, you could put this in RCTScandit.m:

    - (void)didMoveToWindow
    {
      [super didMoveToWindow];
      if (self.window) {
        [self.picker startScanning];
      } else {
        [self.picker stopScanning];
      }
    }

**Comment by lucasfeliciano** [comment]
@nicklockwood THANK YOU, really!
It is working!
:heart: 

Time to implement the api and the property for the component :D
Closing issue :)

![slack for ios upload-7](https://cloud.githubusercontent.com/assets/968014/13249601/7816143a-da25-11e5-948e-6e5f5134cd53.jpg)
