### ISSUE TITLE
[0.19][Android] TypeError: undefined is not an object (evaluating 'GLOBAL.Text= .. )

### ISSUE THREAD

**Issue by bartek** [facebook/react-native#5808]
Hi there,

Am trying to get my existing React Native application running, but am hitting the dreaded red box. Here's the error:

<img width="419" alt="screen shot 2016-02-07 at 8 59 28 pm" src="https://cloud.githubusercontent.com/assets/5839/12877207/b6b07810-cddd-11e5-9033-dcb3e9c03eac.png">

I'm on OSX Mavericks, using Genymotion. I'm using the following dependencies:

```
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-core": "^6.3.15",
    "babel-eslint": "^5.0.0-beta4",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-hmre": "^1.0.0",
    "babel-register": "^6.4.3",
    "deep-freeze": "0.0.1",
    "eslint": "^1.10.3",
    "eslint-plugin-babel": "^3.0.0",
    "eslint-plugin-react": "^3.11.3",
    "expect": "^1.13.3",
    "mocha": "^2.3.4",
    "nock": "^3.6.0"
  },
  "dependencies": {
    "react-native": "~0.19.0",
    "babel-plugin-array-includes": "^2.0.2",
    "isomorphic-fetch": "^2.2.0",
    "lodash": "~4.2.1",
    "react": "~0.14.7",
    "react-dom": "~0.14.7",
    "react-redux": "~4.4.0",
    "redux": "~3.3.1",
    "redux-logger": "~2.0.4",
    "redux-thunk": "~1.0.3"
  }
```

Thank you in advance for your help!

**Comment by janicduplessis** [comment]
Are you using a `.babelrc` file in your project that overrides react native default transforms?

**Comment by bartek** [comment]
@janicduplessis Yes, I had:

```
{
    "presets": ["react", "es2015", "react-hmre"],
    "plugins": ["array-includes"]
}
```

These presets were compiled before I ported my app to React Native, and I wasn't clear if I should keep them around (Perhaps making this clear in the "Javascript Environment" docs. I'm happy to do a PR!)

However, upon removing `.babelrc`, I still receive the same error. Do I need to clear cache in some way? (I've done `watchman watch-del-all`)

**Comment by janicduplessis** [comment]
Can you try these steps to clear the packager cache:

1. Clear watchman watches: \`watchman watch-del-all\`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

**Comment by bartek** [comment]
@janicduplessis Yes! That worked, thank you! I guess I was not sure how I should approach `.babelrc` in a react-native app, but it makes sense to me now. Much appreciated.

Just for the sake of it, here's the results of the first two steps (the last not giving any, obviously):

```

$ watchman watch-del-all
{
    "version": "3.9.0",
    "roots": [
        "/Users/bartekc/dev/MyApp"
    ]
}
```

```

$ npm install
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
npm WARN prefer global babel@5.8.35 should be installed with -g

> fsevents@1.0.7 install /Users/bartekc/dev/BabyName/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/bartekc/dev/BabyName/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> bufferutil@1.2.1 install /Users/bartekc/dev/BabyName/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> utf-8-validate@1.2.1 install /Users/bartekc/dev/BabyName/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> expect@1.14.0 postinstall /Users/bartekc/dev/BabyName/node_modules/expect
> node ./npm-scripts/postinstall.js


> spawn-sync@1.0.15 postinstall /Users/bartekc/dev/BabyName/node_modules/spawn-sync
> node postinstall
```

**Comment by janicduplessis** [comment]
There has been work recently to be able to easily configure babel. In 0.20.0 there is a babel preset for react native. 
```
{
  "presets": ["react-native"]
}
```
Your issue was happening because the babel preset es2015 includes the `transform-es2015-modules-commonjs` plugin but it was not compatible with react-native as of 0.19.0 because it adds strict mode to every module. 0.20.0 added support proper support for strict mode so this should not happen anymore.

**Comment by bartek** [comment]
@janicduplessis This is great to know, thanks for the context. Will keep in mind as the project evolves. I had trouble running mocha tests after I removed `.babelrc` but it seems I was able to get around not conflicting with react-native by adding the `babel` configuration in my `package.json`.

Mocha runs fine now and can compile tests, and _hopefully_ it won't collide with React-Native.

**Comment by janicduplessis** [comment]
You can add your .babelrc inside your test directory I think and it will only apply to thoses files.

**Comment by bartek** [comment]
@janicduplessis Ah, great to know. Much appreciated!
