### ISSUE TITLE
Support WebSocket sub-protocols on Android

### ISSUE THREAD

**Issue by mikemintz** [facebook/react-native#5810]
I rely on the `protocols` argument in the [WebSocket constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) to negotiate the client/server protocol. It looks like it's supported in react-native iOS, but Android appears to be ignoring it.

See [WebSocketModule.java line 66](https://github.com/facebook/react-native/blob/9b87e6c860a95fe3d55285314d3d56be06cb7833/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L66)

**Comment by sodik82** [comment]
+1: I am using STOMP.js over WS and it is working in iOS but not in Android. Most likely the same issue.

**Comment by zxcpoiu** [comment]
the [WebSocketModule.java line 66](https://github.com/facebook/react-native/blob/9b87e6c860a95fe3d55285314d3d56be06cb7833/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L66) says:

> // ignoring protocols, since OKHttp overrides them.

related code in okhttp: [WebSocketCall.java line 71](https://github.com/square/okhttp/blob/master/okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java#L71).

I tried to hard-coded in [WebSocketModule.java line 87](https://github.com/facebook/react-native/blob/9b87e6c860a95fe3d55285314d3d56be06cb7833/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L87) with `builder.addHeader("Sec-WebSocket-Protocol", "myprotocol");`, and it DID add the header `Sec-WebSocket-Protocol` on the WebSocket handshake. (It did NOT get overridden by OKHttp.)

I tested it on react-native@0.20

Does that mean we can add back the support of websocket sub protocols now?
