### ISSUE TITLE
[ANDROID] Default app release version broken since 0.19

### ISSUE THREAD

**Issue by dagobertrenouf** [facebook/react-native#5818]
Hey guys,
After starting a new project with react-native init, the default app crashes on Android when installed as a signed APK. This doesn't happen on 0.18. After digging through the changes, the cause is this line : 
`def enableProguardInReleaseBuilds = true` in [this file](https://github.com/facebook/react-native/blob/342a7630f12ec78c2849802053e83afe4d95a117/local-cli/generator-android/templates/src/app/build.gradle)

Setting it to true fixes the problem.

**Comment by b12k** [comment]
This is a bug in 0.19 React-Native release.
Had same issued.
Fixed it with: https://github.com/facebook/react-native/issues/5655#issuecomment-178896957

Change ```your_app_path/android/app/react.gradle```:
From (lines 45-46):
```
-keepclassmembers class *  { @com.facebook.react.uimanager.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.ReactPropGroup <methods>; }
```
To:
```
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class *  { @com.facebook.react.uimanager.annotations.ReactPropGroup <methods>; }
```

**Comment by mkonicek** [comment]
Thanks for answering this @b12k.

@christopherdro If an issue is answered feel free to close :)

**Comment by mkonicek** [comment]
Sorry about the bug in the first place! Fixed now.
