### ISSUE TITLE
Add how to embed database with react-native app example.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#582]
It would be nice to see an example on how to add embedable database with react-native app.

@amasad any idea?

**Comment by amasad** [comment]
We use RocksDB. I don't know the details. Maybe @sahrens does.

**Comment by chirag04** [comment]
Ok. Cool. I figured rocksdb is the solution here. Thanks for the help.

@sahrens  Can you give some more details about how to use rocksdb with react-native.

**Comment by sahrens** [comment]
What do you want to do exactly?  The AsyncStorage module is built into ReactNative already and should be fine for most key-value storage applications. If you want SQL, RocksDB won't help and you'll need to write a separate module (ideally following the WebSQL spec).  If you hit perf issues with AsyncStorage let me know and we'll be a RocksDB module up and running.

**Comment by chirag04** [comment]
I want to embed data into the app.We want the app to run completely offline. Data is really small but changes based on user activity. I want the changes to persist. 

With AsyncStorage, i guess everytime the app starts i have to load the data into the asynstorage from a text file i guess? Is there a better way to do it?

**Comment by chirag04** [comment]
@sahrens 

Only more question: Asyncstorage docs says it global. Does it mean my app data is accessible to other apps also?

**Comment by vkurchatkin** [comment]
One option is to use Couchbase Lite. It can expose local CouchDB compatible REST interface that can be consumed via XHR or fetch API

**Comment by sahrens** [comment]
No, it's global within your app, i.e. all JS modules in your app will share it. iOS prevents apps from seeing each other's data so you don't have to worry about that.

You don't have to worry about loading anything from a text file, AsyncStorage handles everything for you, just like LocalStorage does on the web. Just do `AsyncStorage.getItem('myKey', function(value) { ... });`, etc. check out AsyncStorageExample.js

**Comment by chirag04** [comment]
@sahrens Thanks for info.

I guess i have to load from file once though. When the user opens the app for first time. Asyncstorage will be empty that time. Subsequent loads can be from asyncstorage.

Thanks for all the help on this.

**Comment by rsp8055** [comment]
MySql Database was created for previously build web application on server, now i want to create android app in react native need to fetch data from that database, so what exactly i need to do can anyone please help me out there>?
Thanks in advanced.
