### ISSUE TITLE
[0.19][Android] Sticky header is called out in release notes, but not actually working

### ISSUE THREAD

**Issue by KelseyRegan** [facebook/react-native#5825]
In the release notes for 0.19, the much anticipated sticky header for Android was said to be implemented:

 - Added stickyHeaderIndices to ListView – 4bc425c

However, it doesn't seem to actually work.  The referenced commit does add the parameter, but I don't see any native changes.  

Are the release notes incorrect?

**Comment by mkonicek** [comment]
cc @cancan101

**Comment by cancan101** [comment]
My pr added the sticky header just for ios. I'm not sure why the release notes set android.

**Comment by ide** [comment]
I updated the release notes by moving that item from Android to iOS. Thanks for the heads-up.

**Comment by waleedarshad-vf** [comment]
+1
