### ISSUE TITLE
react-native run-ios fails with ambiguous simulator targets

### ISSUE THREAD

**Issue by MSLaguana** [facebook/react-native#5850]
I've been trying to use the `react-native run-ios` command introduced in 0.19.0, and I've run into some issues. It seems to default to launching for iPhone 6, but on my machine there is both an "iPhone 6 (9.0)" and an "iPhone 6 (9.0) + Apple Watch - 38mm (2.0)" which causes ambiguity. The end result of this is the simulator does not change over to the correct device (or start at all if it is not already running) and my app appears to crash on startup since it is targeting a different phone.

I think it would be possible to fix this if instead of constructing
``` const simulatorFullName = `${selectedSimulator.name} (${selectedSimulator.version})`;```
you did
``` const simulatorFullName = `${selectedSimulator.name} (${selectedSimulator.version}) [`; ```

which includes the start of the unique device ID and removes the possibility of the watch being involved.

**Comment by icodethings** [comment]
This will be fixed with https://github.com/facebook/react-native/pull/6043

**Comment by zhonshu** [comment]
I first run iPhone 6 Simulator, then run Visual Studio Code DEBUG IOS success.
I hope to help you.
In Xcode 7.3, react native 0.22.2.

**Comment by lacker** [comment]
Looks like this got fixed
