### ISSUE TITLE
RCTPromise now requires every native module method to resolve with an array.

### ISSUE THREAD

**Issue by geof90** [facebook/react-native#5851]
The issue is related to this change:

https://github.com/facebook/react-native/commit/9baff8f437eee49f8ab0e6f433bf86466ca16662#diff-8d9841e5b53fd6c9cf3a7f431827e319R331

Because of this, right now, every native module has to resolve with an array, which is silly if we only intend to resolve with a single value.

For example, pre RN 0.20-rc1, we could do:
```
resolve(@"A value");
```

Now we have to wrap it with an array and do:
```
resolve(@[@"A value"]);
```

From what I see, the simple fix is to revert that change. Running our plugin on RN 0.20-rc1 yielded this error:
![screen shot 2016-02-09 at 3 50 06 pm](https://cloud.githubusercontent.com/assets/8598682/12935271/7a23dde8-cf49-11e5-9e40-6a2b1d0ef2fb.png)

After reverting that change, everything worked great.

@dmmiller @ide

**Comment by geof90** [comment]
Also a note that this change is not documented anywhere, e.g the website docs do not say that the RCTPromise must always resolve with the value wrapped in an array.

**Comment by dmmiller** [comment]
Let me look into this.  Someone else reported this internally.  I'll look today.  Thanks for reporting it.

**Comment by geof90** [comment]
@dmmiller Thanks for looking into it!! Really appreciate it.

**Comment by skevy** [comment]
Resolved in https://github.com/facebook/react-native/commit/c9a1956c4fd9cfb6bf883c835b501d097181e1a4

**Comment by geof90** [comment]
Thanks guys!!

**Comment by cnsnake11** [comment]
thanks，this fix my problem.

**Comment by kanerogers** [comment]
Thanks so much for fixing this guys - this was driving me nuts!
