### ISSUE TITLE
WebView not working as documented

### ISSUE THREAD

**Issue by ffxsam** [facebook/react-native#5852]
See issue #5699 

It's unclear how `WebView` is supposed to work as far as referencing a URI or static content. The documentation and code in GitHub say to not use `html` and `url`, but in actual practice, `source` does not work at all.

**Comment by christopherdro** [comment]
This is because the docs are being extracted from the source code on master and your probably running your project of a stable release.

You can update your project to use the master branch and test out the `source` prop on Webview or just wait till 0.20 stable is released in a week or two.

**Comment by ffxsam** [comment]
I am indeed running a stable release. Shouldn't the docs reflect that? And shouldn't `master` = production release?
