### ISSUE TITLE
[Navigator] Override swipe back behavior?

### ISSUE THREAD

**Issue by aksonov** [facebook/react-native#5854]
Is there anyway to call some own methods during swipe back? Currently it calls navigator.pop() method, but i want to customize it to solve issue: https://github.com/aksonov/react-native-router-flux/issues/176

**Comment by lynndylanhurley** [comment]
I'm having the same issue.

My use-case is that I want my Header component do change styles depending on the current screen. This is possible when navigating to screens, but not when swiping back from screens. So now I'm forced to disable the gesture.

**Comment by lynndylanhurley** [comment]
I just created a Product Pains post for this:
https://productpains.com/post/react-native/override-swipe-back-behavior/

**Comment by lu-ko** [comment]
+1

**Comment by charpeni** [comment]
I'll close this issue since it's a feature request, a nice one BTW.

Please refer to the product pains entry.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-4** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
