### ISSUE TITLE
[Android] pagingEnabled property

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#5858]
When do you plan to do it?

**Comment by kocyigityunus** [comment]
paging enabled scroll view called view pager in android. 

i think you are looking for https://facebook.github.io/react-native/docs/viewpagerandroid.html#content

**Comment by stereodenis** [comment]
@kocyigityunus what about horizontal and vertical direction?

**Comment by kocyigityunus** [comment]
it's only works on horizontal direction right now.

**Comment by stereodenis** [comment]
@kocyigityunus I need vertical direction too

**Comment by ide** [comment]
@stereodenis you'll probably need to build that yourself. Android doesn't support this out of the box.

**Comment by stereodenis** [comment]
@ide on ios I have two scrollview types: one horizontal with a lot of vertical in it. How can I reproduce it?

**Comment by ide** [comment]
It's just not supported with RN Android. My suggestion is to figure out how you would implement this with pure native Android (Java) and use the same techniques in RN Android and, if necessary, write some Java code to expose this new feature to the RN JS.

**Comment by brentvatne** [comment]
@facebook-github-bot answered
