### ISSUE TITLE
Navigator swipes even when Modal is present

### ISSUE THREAD

**Issue by yamill** [facebook/react-native#5860]
My current Navigator scene config is setup to ```Navigator.SceneConfigs.HorizontalSwipeJump```. If a modal is present inside one of my scenes I am able to swipe the scene behind it.

Is there a way to disable swiping? Looks like a bug...

![modalswipe](https://cloud.githubusercontent.com/assets/755943/12957058/006e30b0-cff9-11e5-8fd6-3ca9082866aa.gif)

**Comment by kocyigityunus** [comment]
are you sure about it's a navigator? can it be a scroll view? because to go forth in a navigator you need to tap a button or something. 

or maybe it's a bigger bug than we think.

**Comment by yamill** [comment]
@kocyigityunus With HorizontalSwipeJump you don't need a button. You can move between route scene's by just swiping if you have a routestack.

**Comment by ms88privat** [comment]
@yamill try this on your modal view as a property. 

```
pointerEvents enum('box-none', 'none', 'box-only', 'auto') 

In the absence of auto property, none is much like CSS's none value. box-none is as if you had applied the CSS class
```

**Comment by yamill** [comment]
@ms88privat no luck with pointerEvents - I believe that only applies to presses not gestures.

**Comment by yamill** [comment]
@brentvatne @ericvicenti any idea why this is happening?

**Comment by yamill** [comment]
I ended up using https://github.com/brentvatne/react-native-scrollable-tab-view - there's a ```locked``` parameter that allows me to do exactly what I was trying to do. I can just toggle the locked param when opening and closing the modal :+1: 

@brentvatne this is definitely something that should be implemented in the core for HorizontalSwipeJump :wink: your module saved me lots of headache.
