### ISSUE TITLE
CameraRollManager is not in NativeModules (iOS)

### ISSUE THREAD

**Issue by huston007** [facebook/react-native#5878]
I'm trying to get gallery photos on iOS 9.2, react-native 0.20.0-rc1.
When I call CameraRoll.getPhotos({first: 25}), i got error `Cannot read property 'getPhotos' of undefined`
I debugged a bit and found that in file `CameraRoll.js`:
```
var RCTCameraRollManager = require('NativeModules').CameraRollManager;
//There is no CameraRollManager property actually
...
RCTCameraRollManager.getPhotos(params).then(successCallback, errorCallback);
//Throws error
```

**Comment by huston007** [comment]
Also, on android I got another error message with the same call:
`RKCameraRollManager.getPhotos got 1 arguments, expected 3`
![screen shot 2016-02-11 at 17 21 21](https://cloud.githubusercontent.com/assets/4318513/12978739/eb1d1f32-d0e3-11e5-956f-817f1e1c53b7.png)

**Comment by KristoferEng** [comment]
Any luck with this? I just got this error for iOS.

**Comment by Kureev** [comment]
@huston007 maybe [this part of the CameraRoll example](https://github.com/facebook/react-native/blob/892497408c14b61687cb823a144bd80996023404/Examples/UIExplorer/CameraRollView.js#L138-L151) may help you?

**Comment by grabbou** [comment]
You have to add https://github.com/facebook/react-native/tree/master/Libraries/CameraRoll xcodeproj from this folder to your project to make native code available. It's not in the `react-native init` project by default.

The other error I believe was already explained well by @Kureev - in case you encounter any other errors with CameraRoll module, consider opening a StackOverflow question where lots of people using it in production will be able to see your question and help you out!

**Comment by sheerun** [comment]
@grabbou For some reason cli is not able to link it. I tried `react-native link` but with no luck..

**Comment by a3diti** [comment]
#4560
