### ISSUE TITLE
node module locked / not locked ?

### ISSUE THREAD

**Issue by andyf625** [facebook/react-native#588]
not sure whats going on but when i do 
>> react-native init AwesomeProject

 get this error, can post the npm-debug.log if needed

>>
computer:~ user$ cd documents/reactnative
computer:reactnative user$ ls
AwesomeProject	react-native
computer:reactnative user$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/user/Documents/ReactNative/AwesomeProject
npm WARN locking Error: EACCES, open '/Users/user/.npm/_locks/react-native-e6be3bf68e351b63.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/user/.npm/_locks/react-native-e6be3bf68e351b63.lock failed { [Error: EACCES, open '/Users/user/.npm/_locks/react-native-e6be3bf68e351b63.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/user/.npm/_locks/react-native-e6be3bf68e351b63.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "react-native"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/user/Documents/ReactNative/AwesomeProject/node_modules/react-native, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Documents/ReactNative/AwesomeProject/npm-debug.log
`npm install --save react-native` failed

**Comment by amasad** [comment]
Can you try the suggestions here? https://github.com/facebook/react-native/issues/225

**Comment by andyf625** [comment]
yup working now. thanks

this sorted it..

sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules

**Comment by amasad** [comment]
@andyf625 can you add this to our troubleshooting page? :)
https://github.com/facebook/react-native/blob/master/docs/Troubleshooting.md

**Comment by amasad** [comment]
actually I just did that since it's simple enough https://github.com/facebook/react-native/commit/52b64907a8d55373e03e697bf5bcf6ede6fe5dc7
