### ISSUE TITLE
Compatibility: node packages depending on V8 can't function in react-native iOS

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#5881]
I'm building a react-native app to go across Android and iOS. I'm noticing some dependencies in libraries I'm using depend on having a V8 (node) runtime. This breaks the JavaScriptCore JS runtime on iOS, with RN error-ing with something like: 

`Requiring unknown module _moduleA_. If you are sure the module is there try restarting the packager.`

What I'm noticing is that v8 requiring _moduleA_ doesn't get copied over in the react bundle that gets placed on the phone. I found this by logging the modules present in

`node_modules/react-native/packager/react-packager/src/Resolver/polyfills/require.js`

Since I don't own the libraries that I'm trying to use I can't modify the dependency.

In my case I'm trying to use the **twilio** module which uses Node's **crypto** module.

I'm guessing I won't face this issue when I build RN on Android.

What are the options like?

**Comment by grabbou** [comment]
I would't say this is possible, just like it's not possible to use node modules in Chrome or Firefox.

You can check this out, but I don't think it's going to be production ready: https://github.com/mvayngrib/rn-nodeify

**Comment by ide** [comment]
> just like it's not possible to use node modules in Chrome or Firefox

For emphasis: just as Node and the browser are different environments that happen to use the same language, React Native is a third JS environment that's not a browser and isn't Node. Packages need to be written to either be universal or specifically written for React Native.

There's the "react-native" key in package.json for aliasing modules but fundamentally packages made for Node aren't necessarily going to work with RN.

**Comment by lacker** [comment]
In practice, I suggest bugging Twilio to make their stuff work with React Native. I'm closing this issue because I believe it has only the potential for philosophical angst at this point. Good luck!

**Comment by aschrijver** [comment]
There's the option to run V8 on android with node built-in. Haven't tried yet, but I will.
- https://github.com/eclipsesource/J2V8
