### ISSUE TITLE
XMLHttpRequest.DONE is not defined

### ISSUE THREAD

**Issue by sreesharp** [facebook/react-native#5883]
Hello, 

Currently the default XMLHttpRequest class (https://github.com/facebook/react-native/blob/master/Libraries/Network/XMLHttpRequestBase.js) don't provide access to the following variables.  
UNSENT, OPENED, HEADERS_RECEIVED, LOADING, DONE.
We have it as object level properties, but not accessible at class level.

In standard web browser environment, we can access XMLHttpRequest.DONE , and many JS libraries out there uses it.  It would be great if we ReactNative can also support XMLHttpRequest.DONE (and other properties).

Regards
Sreejumon
http://sreesharp.com

**Comment by satya164** [comment]
Thanks for the report. Can you send a PR?

**Comment by sreesharp** [comment]
Hey @satya164  Please review the PR https://github.com/facebook/react-native/pull/5895
