### ISSUE TITLE
Weird rerender condition for ListView

### ISSUE THREAD

**Issue by timsuchanek** [facebook/react-native#5907]
**Use Case**
I have a `ListView` on android that contains several content that depends on `Dimensions.get('window').width`.
So I want `onLayout` to fire and change for the List Items.

**Weird behaviour**
But `ListView` only updates the Items, if you provide a callback for `onChangeVisibleRows`

https://github.com/facebook/react-native/blob/e7005f7f5429422b6f2e9c2aa29c9d57bda7b77a/Libraries/CustomComponents/ListView/ListView.js#L523

Providing an empty callback solved my problem, on orientation change, now a rerender is triggered.

**Proposal**
But wouldn't make somthing like `rerenderOnLayout={true}` more sense?
I think the API currently is totally disguised at that point.

What do you think?

**Comment by sahrens** [comment]
Not sure what problem you're having exactly, _updateVisibleRows doesn't do anything that affects anything internal to ListView - all it does is call onChangeVisibleRows, so if that callback isn't provided, it has nothing to do. It simply updates `this._childFrames` and `this._visibleRows` which aren't read outside of that function. Or did something slip in that I'm missing?

Please re-open if I'm missing something and this is still a problem.
