### ISSUE TITLE
onPress not canceled when rootView is inside a Native ScrollView

### ISSUE THREAD

**Issue by imton** [facebook/react-native#5913]
Hey guys,

I am using React Native in parts of my app, so not all my app is React Native.

One of my views that is done in RN has a ListView, its RN root view is inside a Native Paged ScrollView.

When a ListView item is pressed, it is not canceled when the Native Paged Scroll View moves. 

What ends up happening is that this ListView onPress transitions (navigation) to child and at same time the Native Paged Scroll View move up/down (vertical orientation like snapchat).

How can RN take into consideration higher hierarchy ScrollView touches that are higher than its root view.

Thank you
G

![rn_scroll_views](https://cloud.githubusercontent.com/assets/637225/13030824/a1613e96-d296-11e5-9016-fe1907410e6d.png)

**Comment by geirman** [comment]
@facebook-github-bot stack-overflow
