### ISSUE TITLE
startActivityForResult to get Camera picture result failed, the log show 【Couldn't find method canDrawOverlays, referenced from method com.facebook.react.ReactActivity.onCreate】

### ISSUE THREAD

**Issue by sadikelong** [facebook/react-native#5915]
I create a module to get camera picture uri when camera result saved.

the step is below:
1). create an intent to start camera.

	Intent cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        // we create a tmp file to save the result
        File path = Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_PICTURES);
        File imageFile;
        try {
            // Make sure the Pictures directory exists.
            path.mkdirs();
            imageFile = File.createTempFile("image_picker_capture_", ".jpg", path);
        } catch (IOException e) {
            e.printStackTrace();
            response.putString("error", e.getMessage());
            callback.invoke(response);
            return;
        }
        cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(imageFile));
2). startActivityForResult.

        try {
            mMainActivity.startActivityForResult(cameraIntent, REQUEST_LAUNCH_CAMERA);
        } catch (ActivityNotFoundException e) {
            e.printStackTrace();
        }
3). In MainActivity override onActivityResult method.

    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mImagePicker.handleActivityResult(requestCode, resultCode, data);
    }

2 in 10 times, this code work well, but 8 times the app instance is restart. The log show 【Couldn't find method canDrawOverlays, referenced from method com.facebook.react.ReactActivity.onCreate】. So the onActivityResult function can not receive the result.
![image](https://cloud.githubusercontent.com/assets/7940552/13032248/1b14d952-d326-11e5-8e3c-f7762447b345.png)

The test enviroment is an android 4.4 mobile phone. compileSdkVersion is 23. targetSdkVersion is 22. RN 0.18.1

**Comment by satya164** [comment]
Have you proguard enabled by any chance?

**Comment by satya164** [comment]
Do you have*

**Comment by sadikelong** [comment]
@satya164 , I check the build.gradle, screenshot is below:
![image](https://cloud.githubusercontent.com/assets/7940552/13037790/8d1a75e6-d3c3-11e5-80e4-2ae139db4821.png)
I only change targetSdkVerstion to 22.

**Comment by sadikelong** [comment]
The android os kill the activity which start camera for result. I override onConfigurationChanged in Mainactivity and add largeHeap in manifest, but sometimes(50%) the Mainactivity is still killed! I think this is not a issue with RN. Close it.
