### ISSUE TITLE
Remove React Devtools from docs until fixed

### ISSUE THREAD

**Issue by motiazu** [facebook/react-native#5918]
![image](https://cloud.githubusercontent.com/assets/8556495/13032842/902b5bdc-d30b-11e5-9fe4-7a52a1eb29c9.png)

For some reason, the [Debugging](https://facebook.github.io/react-native/docs/debugging.html) doc says you can use `React Devtools` plugin to debug `react-native` apps.
As pointed out in [this](http://stackoverflow.com/questions/35338412/how-to-see-react-tab-in-chrome-devtools-when-debugging-react-native-app) SO answer, the [Known Issues](https://facebook.github.io/react-native/docs/known-issues.html#content) page does say that this will not work.

Unfortunately, my team spent quite some time trying to get the devtools to work until we asked in SO (google wasn't very helpful, I was able to find about this with google in hindsight) just to realize the docs were fooling us.

**Comment by janicduplessis** [comment]
Sorry about that -_-

**Comment by satya164** [comment]
Removed from docs now.
