### ISSUE TITLE
Android Text's paddingTop is not working on 0.19 or 0.20

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#5921]
I am surprised this hasn't been reported before, but it appears to be a new issue. I believe paddingTop doesn't work on Texts on Android. Here is an example RNPlay demonstrating it:

https://rnplay.org/apps/xRcJKw

![screen shot 2016-02-14 at 12 51 04 pm](https://cloud.githubusercontent.com/assets/610082/13036341/ac1f635c-d319-11e5-986b-bb16bd0bf52b.png)

![screen shot 2016-02-14 at 12 50 58 pm](https://cloud.githubusercontent.com/assets/610082/13036342/ac20aa00-d319-11e5-9dfe-f76b380c85c9.png)

**Comment by xiaobuu** [comment]
+1

**Comment by toadums** [comment]
I think it is because android's text elements dont support padding

https://github.com/facebook/react-native/issues/3233

**Comment by satya164** [comment]
Duplicate of #3233
