### ISSUE TITLE
LinkingIOS docs should be updated

### ISSUE THREAD

**Issue by thisbejim** [facebook/react-native#5925]
Took a half hour of digging around the net to figure out you need to do 1-3 manual steps on [this page](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) before you can effectively follow the [docs for LinkingIOS](https://facebook.github.io/react-native/docs/linkingios.html#content). I recommend updating the LinkingIOS docs to make this clearer.

**Comment by satya164** [comment]
PRs are welcome.

**Comment by mkonicek** [comment]
Please send a pull request.
