### ISSUE TITLE
TextInput onChange is not working for me

### ISSUE THREAD

**Issue by jsntghf** [facebook/react-native#5928]
![qq20160215-0](https://cloud.githubusercontent.com/assets/182790/13041677/5e8d5c76-d3f4-11e5-89d9-8e5f50d72e03.png)

RN: 0.19.0   iOS: 9.2

the value of TextInput is not synchronized with the display text。

my code:
![qq20160215-1](https://cloud.githubusercontent.com/assets/182790/13041798/656c18f6-d3f5-11e5-8f09-7a066e8cd314.png)

**Comment by jsntghf** [comment]
if i add multiline={true}, the value of TextInput will synchronized with the display text。
![qq20160215-2](https://cloud.githubusercontent.com/assets/182790/13041850/ed01a8d0-d3f5-11e5-9c09-3f30ea16831f.png)

someone can help me?

**Comment by gre** [comment]
you missed to pass-in text back to the text input.

```
  <TextInput
    style={{height: 40, borderColor: 'gray', borderWidth: 1}}
    onChangeText={(text) => this.setState({text})}
    value={this.state.text}
  />
```

See the `value` prop here

**Comment by jsntghf** [comment]
@gre it isn't working for me after add value prop

**Comment by jayesbe** [comment]
I was working on a quick sample react-native program today for Android. A simple TextInput configured as such:
```
          onChangeText={(text) => this.setState({text})}
          onChange={
            console.log('one')
          }
          onBlur={
            console.log('two')            
          }
          onSubmitEditing={
            console.log('three')
          }
          onEndEditing={
           console.log('four') 
          }
```

results in 
```
02-19 16:00:31.378 5067-5100/com.test I/ReactNativeJS: one
02-19 16:00:31.378 5067-5100/com.test I/ReactNativeJS: two
02-19 16:00:31.378 5067-5100/com.test I/ReactNativeJS: three
02-19 16:00:31.378 5067-5100/com.test I/ReactNativeJS: four
02-19 16:00:31.643 5067-5100/com.test I/ReactNativeJS: one
02-19 16:00:31.643 5067-5100/com.test I/ReactNativeJS: two
02-19 16:00:31.643 5067-5100/com.test I/ReactNativeJS: three
02-19 16:00:31.643 5067-5100/com.test I/ReactNativeJS: four
02-19 16:00:31.790 5067-5100/com.test I/ReactNativeJS: one
02-19 16:00:31.790 5067-5100/com.test I/ReactNativeJS: two
02-19 16:00:31.790 5067-5100/com.test I/ReactNativeJS: three
02-19 16:00:31.790 5067-5100/com.test I/ReactNativeJS: four
```

As soon as the TextInput opens the keyboard.. I have a starting value of 'example' 
As soon as I remove one letter, all 4 events fire.. Why?
Remove another letter.. all 4 events fire.. ? 

It makes no sense to me. I have been trying for 2 hours .. wondering how exactly I am to know just When is a user done entering text.  What event can I hook into that will tell me when that happens?

**Comment by geirman** [comment]
@jsntghf if you're using @gre's example verbatim (copy/paste) it may not have worked for you. Can you try this and let us know whether this is an actual issue?

```javascript
    <TextInput
        style={{height: 40, borderColor: 'gray', borderWidth: 1}}
        onChangeText={(text) => this.setState({input: text})}
        value={this.state.input}
     />
```

**Comment by geirman** [comment]
@jayesbe the reason all 4 are executing is because of the way you're executing the console.log, which will fire each time regardless. Try fat arrow like this and you'll see that `onEndEditing` and `onBlur` will probably give you what you're looking for. 

```javascript
   <TextInput
          style={{height: 40, borderColor: 'gray', borderWidth: 1}}
          onChangeText={(text) => this.setState({input: text})}
          onBlur={(ev) => console.log('onBlur', ev)}
          onEndEditing={(ev) => console.log('onEndEditing', ev)}
          onSubmitEditing={(ev) => console.log('onSubmitEditing', ev)}
          onSelectionChange={(ev) => console.log('onSelectionChange', ev)}
          value={this.state.input}
        />
```

**Comment by geirman** [comment]
@facebook-github-bot answered
