### ISSUE TITLE
[Android] Image.propTypes.source is required by default, while in IOS isn't

### ISSUE THREAD

**Issue by roscoe054** [facebook/react-native#5929]
the code look like this: 
```JSX
propTypes: {
  imgSource: Image.propTypes.source
},
```
In Android Image.propTypes.source will show warning "Failed propType: Required prop imgSource was not specified in ...", but this warning won't show In IOS.
As seen in this [demo](https://rnplay.org/apps/r00zig)

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/a11f980a3425149bed7f560a3162315cc8c0e82f
