### ISSUE TITLE
TouchableOpacity initial opacity bug

### ISSUE THREAD

**Issue by jdmunro** [facebook/react-native#5932]
I've noticed a bug where if you have an opacity set in a style that is used by a ```TouchableOpacity```: the opacity will not be seen until the component has been tapped once. See gif below for an example:

![bug](https://cloud.githubusercontent.com/assets/17656/13047809/9fb27418-d3d9-11e5-9528-306eb3cc8444.gif)

In this example the ```TouchableOpacity``` has an opacity specified in a style as 0.2 (to represent a disabled state), however the button must be pressed before the initial opacity is set correctly. You could argue not to use a ```TouchableOpacity``` if the component within is disabled however there may be more valid cases for having a different initial opacity.

I believe this could be the source of the bug: https://github.com/facebook/react-native/blob/33d8db599ef8eb85dc27150e04c71719be6ffd26/Libraries/Components/Touchable/TouchableOpacity.js#L72

The default opacity is always set to 1 for the animation. I believe it should take the value from the style if this is possible.

**Comment by Hu4F00d** [comment]
+1 Any initial opacity style that you give TouchableOpacity is ignored until the first interaction with the element.

**Comment by breadadams** [comment]
+1 Having the same issue as @jdmunro & @Hu4F00d

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/touchableopacity-initial-opacity-bug

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by Kielan** [comment]
this issue should not be closed. @jdmunro gave a very good issue and source and still not resolved.

**Comment by xasopheno** [comment]
I'm having the same problem.

**Comment by drakmail** [comment]
:+1: have same problem

**Comment by beausmith** [comment]
## Running into this bug ? 🐞 

### Up-vote this… ➡️  [TouchableOpacity initial opacity bug](https://react-native.canny.io/feature-requests/p/touchableopacity-initial-opacity-bug) ⬅️
