### ISSUE TITLE
[0.19][ListView][Android] ListView crashes when ListView.DataSource is updated (with example code)

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#5934]
Updating a ListView.DataSource on Android causes a NullPointerException if list is long enough that it does not all fit on screen.

Here's a sample project with code that illustrates the bug: https://github.com/npomfret/react-native-bug-reports/tree/master/ListViewUpdatingBug

It does not appear to happen on IOS.

![screen shot 2016-02-15 at 13 39 45](https://cloud.githubusercontent.com/assets/5489469/13050193/b43a7d3a-d3e9-11e5-8cd8-ef9f19304d96.png)

`Exception in native call from JS
                                                                        java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
                                                                            at android.widget.TextView.checkForRelayout(TextView.java:7128)
                                                                            at android.widget.TextView.setText(TextView.java:4342)`

**Comment by Iliyass** [comment]
I have the same error, did you manage to fix this ?

**Comment by npomfret** [comment]
See my [sample code](https://github.com/npomfret/react-native-bug-reports/tree/master/ListViewUpdatingBug), you don't need many data items to make it go wrong, but there do need to be enough that they cannot all be rendered and the component needs to scroll.

I've mentioned it on [productpains](https://productpains.com/post/react-native/listview-crashes-when-listviewdatasource-is-updated-with-example-code/), please up vote if you can.

I've found a work around for now which is to use the _renderScrollComponent_ property.  I found a third party implementation called [InvertibleScrollView](https://github.com/exponentjs/react-native-invertible-scroll-view) which doesn't seem to suffer from the same problem:

`renderScrollComponent={props => <InvertibleScrollView inverted />}`

**Comment by kenny1har** [comment]
Set the data source to empty array before changing. It works.
var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
this.setState({dataSource: ds.cloneWithRows([])});
this.setState({dataSource: ds.cloneWithRows(data)});

**Comment by buddyfavors** [comment]
Thanks @kenny1har that worked for me too

**Comment by adnbsr** [comment]
Okay, it is proper way @kenny1har  mentioned, but we would not have this checkpoint.

**Comment by npomfret** [comment]
Setting the _datasource_ to an empty array may work but I believe it will cause flicker because the UI will clear itself out before redrawing your non-empty data set.

I've found that setting the `renderScrollComponent` to anything other than the default is a satisfactory workaround.  In my case I've used:

 `renderScrollComponent={props => <RecyclerViewBackedScrollView  />}`.

**Comment by brothersharp91** [comment]
hi.I meet the same question.I have solved it.
when change datasource,you should render a blank screen first,then render the screen you want to show. I think its a bug.

**Comment by apalmblad** [comment]
I updated the reproduction from @npomfret to 0.21 and the issue still happens.

Through testing, I found a few workarounds:
* Adding a the property renderScrollComponent to the listview, ie `renderScrollComponent={(props) => <React.RecyclerViewBackedScrollView {...props}/>}`
* Setting scrollRenderAheadDistance to 0 on the list view seems to fix the issue, but crashes with values > 0
* Setting removeClippedSubviews to false also fixes the issue
* Finally, leaving ListView as-is, but setting style={{overflow:hidden}} on the component returned by renderRow also fixes the issue.

Now, from the docs:
> A performance optimization for improving scroll perf of large lists, used in conjunction with overflow: 'hidden' on the row containers. This is enabled by default.

So it looks like the solution is already documented; however I'd argue that making the results of renderRow *require* a certain style setting to work by default is not the friendliest option.  I'd say that applying that style to the result of renderRow would be a reasonable solution, but until that change is made setting the default back to false for removeClippedSubviews would work.

**Comment by ceichinger** [comment]
@apalmblad thanks! fixed it for me :)  
(used scrollRenderAheadDistance in my case)

**Comment by npomfret** [comment]
Using
`
renderScrollComponent={(props) => <RecyclerViewBackedScrollView {...props}/>}
`

On a static (never changing) list results in nothing being displayed at all in android!

**Comment by ms88privat** [comment]
I have the same problem with my ListView Footer. Never encountered something like that before. I'm on 0.22.0. If I have some variable in a textfield, it is not working anymore.

renderFooter:
```jsx
<Text>{var}</Text> // not working
<Text>xyz</Text> // working
```

thanks to @apalmblad for the workaround with removeClipedSubiew or overflow: hidden, both are working for me :+1:

**Comment by bosung90** [comment]
Is there any pull request that solves this problem?

**Comment by npomfret** [comment]
I don't think so, but the work around is to use a `renderScrollComponent`.

**Comment by bosung90** [comment]
I tried that and it broke my pull to refresh. I had to do removeClippedSubviews={false} to fix the issue

**Comment by npomfret** [comment]
Not sure when this got fixed but it seems fine in rn 0.26

**Comment by bosung90** [comment]
Currently stuck with 0.24  but I'll keep this in mind. Thanks for checking

**Comment by bennyguitar** [comment]
So I'm looking at Crashlytics for our app, and noticing a ton of different variations of this error where all stack traces end up at `textView.checkForRelayout`.

* Does this only happen with ListViews?
* The underlying problem is that the layout params are null in `checkForRelayout`. How does the view set up ever get into that state?

**Comment by npomfret** [comment]
As far as I'm aware the original issue i reported is fixed.
