### ISSUE TITLE
How do you get the city from GeoLocation API?

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#594]
Is there a way to get the city corresponding to the watched coordinates?
```
   this.watchID = navigator.geolocation.watchPosition((lastPosition) => {
      this.setState({lastPosition});
    });
```

**Comment by tadeuzagallo** [comment]
What you need for that is Reverse Geocoding, iOS doesn't provide it, you'll have to use 3rd party APIs.

**Comment by soheil** [comment]
I believe CLGeocoder does.

**Comment by tadeuzagallo** [comment]
Wow, I really didn't know that, thanks! (and sorry for the misleading reply)

But no, that hasn't been exposed yet...

**Comment by brentvatne** [comment]
Oh neat, CLGeocoder integration would be a nice addition

**Comment by soheil** [comment]
In the meanwhile I guess I'll be using NativeModules to access CLGeocoder,
hope I don't have to be forced to keep doing that for many other things.

**Comment by rickeybobby** [comment]
Please take me off this list

**Comment by spicyj** [comment]
@rickeybobby At https://github.com/watching you can unsubscribe from notifications for this repo.

**Comment by soheil** [comment]
I created a gist for those interested:

objectiveC code:
https://gist.github.com/soheil/cfdb4cad068ac12d6142

js code:
https://gist.github.com/soheil/64e6ef71179c3de72822
