### ISSUE TITLE
[Android][0.20.0-rc][WebView] injectedJavaScript doesn't work in Android in 0.20

### ISSUE THREAD

**Issue by maraujop** [facebook/react-native#5940]
Hi there,

I've just upgraded to RN 0.20 and I've seen how `injectedJavaScript` only works on iOS. I've created a sample application as a test case:
https://rnplay.org/apps/XppVqg

Thanks, cheers,
Miguel

**Comment by Sean-Snow** [comment]
+1   0.20.0

**Comment by hufeng** [comment]
+1 0.20.0

**Comment by maraujop** [comment]
Hi all,

I decided to find the root cause of this bug and submit a patch, so I pulled react-native source and build it. Then I found out that the webclient being used in Android, doesn't have an alert function, however javascript execution really works.

Other thing I was doing wrong, was having a line comment within the javascript code injected, because this code is concatenated into a one line chunk of code, ending in a unfinished wrong piece of JS.

Using webview debugging helped me a lot, getting the right code to work. I think adding an example to the docs and a warning would be good enough in this case.

Cheers,
Miguel

**Comment by cablegunmaster** [comment]
@maraujop webview debugging? 
how do you do this? Is this different from remote debugging? 
I am kinda need of doing this, to compare why it won't run locally. 
But runs if Included from a external source. (which in my opinion is very bad practise).

Any tips or help is appreciated.

**Comment by cinder92** [comment]
+1 RN 0.38

**Comment by chinachuner** [comment]
+1 RN 0.38

**Comment by JB-CHAUVIN** [comment]
+1
