### ISSUE TITLE
NavigationBar default styles

### ISSUE THREAD

**Issue by AntonNiklasson** [facebook/react-native#5953]
I find the default styles for the NavigationBar a bit confusing. I would like to add `justifyContent: 'center';` to all three components in `BASE_STYLES` in both `NavigatorNavigationBarStylesAndroid.js` and `NavigatorNavigationBarStylesIOS.js`. This would make the components in the navigation bar vertically centered by default.

Thoughts?

**Comment by satya164** [comment]
PRs are welcome.

A new experimental Navigator is being worked on though, you might wanna have a look at that.
