### ISSUE TITLE
[Packager] cli.js does not pass arguments to packager.js

### ISSUE THREAD

**Issue by imaffett** [facebook/react-native#596]
cli.js does not currently pass arguments to packager.js .  This would be nice to be able to change the  port that packager is listening to via the command line.

**Comment by amasad** [comment]
Patches welcome! :)

**Comment by brentvatne** [comment]
@imaffett - still interested in this feature? Seems simple enough to make a PR, ping me on irc/twitter @notbrent if you need a hand

**Comment by imaffett** [comment]
Hey @brentvatne - The fix is easy, but I'm currently not permitted to contribute to React Native (by Intel), only React.js .

**Comment by ide** [comment]
@imaffett the licenses for the two projects are identical, word for word except for the project names, if that helps you get permission from your legal team.

**Comment by imaffett** [comment]
@ide -  I wish it were that easy :).  Theres a multi level process for approval at Intel (legal and then other approvals for scope of work on projects).  I'm hoping to get approval for React Native, but it could be another month or two.  Thanks for the information though!

**Comment by ide** [comment]
@imaffett OK. I've added the "good first task" tag to encourage contributions from other devs in the community =)

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/packager-clijs-does-not-pass-arguments-to-packagerjs
