### ISSUE TITLE
[0.20] React Native - Upgrade, Error

### ISSUE THREAD

**Issue by ekonstantinidis** [facebook/react-native#5962]
When trying to upgrade from `0.19` to `0.20` using `react-native upgrade` while I am using `Node 5.6.0` I am getting this error:

    ~/Projects/my-app> react-native upgrade
    /Users/Manos/Projects/my-app/node_modules/react-native/local-cli/bundle/buildBundle.js:17
    function buildBundle(args, config, output = outputBundle) {
                                             ^
    SyntaxError: Unexpected token =
       at exports.runInThisContext (vm.js:53:16)
       at Module._compile (module.js:387:25)
       at loader (/Users/Manos/Projects/my-app/node_modules/babel-register/lib/node.js:130:5)
       at Object.require.extensions.(anonymous function) [as .js] (/Users/Manos/Projects/my-app/node_modules/babel-register/lib/node.js:140:7)
       at Module.load (module.js:357:32)
       at Function.Module._load (module.js:314:12)
       at Module.require (module.js:367:17)
       at require (internal/module.js:16:19)
       at Object.<anonymous> (bundle.js:11:21)
       at Module._compile (module.js:413:34)

I double-checked and it works fine with `Node 4.3.0` so I am wondering if Node 5 is supported.
Earlier today I was able to upgrade a project from `0.18.1` to `0.19` using Node `5.6.0` successfully.

**Comment by janicduplessis** [comment]
Seems to be caused by 32fa0b7fa196ae83e7f65bf1836d672b58f2213c. Node 5 doesn't support default function arguments, and this code is not run through babel.

cc @davidaurelio

**Comment by janicduplessis** [comment]
In the meantime you can edit your `node_modules/react-native/local-cli/bundle/buildBundle.js` and and replace this at line 17
``` js
function buildBundle(args, config, output = outputBundle) {
```
by that
``` js
function buildBundle(args, config, output) {
  output = output || outputBundle;
```

**Comment by satya164** [comment]
This code seems to be run through Babel, as the error is coming from `babel-register`. Probably a Babel version issue?

**Comment by janicduplessis** [comment]
@satya164 Oh yes you are right I didn't think about that. This is weird it effectively looks a a problem with the babel config. The local-cli is using the react-native babel preset. Do you have a .babelrc file in your project? Also maybe try reinstalling your node_modules.

**Comment by qasimalbaqali** [comment]
Getting the same error. 

```
/node_modules/react-native/local-cli/bundle/buildBundle.js:17
function buildBundle(args, config, output = outputBundle) {
                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at loader (/Users/qasimalbaqali/Documents/ReactJS/vloomarkt/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/qasimalbaqali/Documents/ReactJS/vloomarkt/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (bundle.js:11:21)
    at Module._compile (module.js:435:26)
```

**Comment by ekonstantinidis** [comment]
@janicduplessis Even if I change what you suggested then the scripts crashes again a couple of lines later:

    /Users/Manos/Projects/my-app/node_modules/react-native/local- cli/bundle/buildBundle.js:57
        Promise.all([clientPromise, bundlePromise]).then(([client]) => {
                                                          ^

**Comment by satya164** [comment]
@ekonstantinidis Try deleting the `node_modules` folder and running `npm install` again.

**Comment by ekonstantinidis** [comment]
@satya164 Just tried again but got the same error. Were you able to upgrade using Node 5 (particularly `5.6.0`)?

**Comment by MacKentoch** [comment]
Is that me or this version 0.20 creates a lot of issues (*horrible transitions user experience, bugs not only due to deprecated props or stuffs...*) ?

Upgrading seems like not worth right now.
I will try creating from scratch to see if it goes better...

**Comment by janicduplessis** [comment]
@skevy Could this be related to the babel/react-native-preset changes? The packager code is using the same babel config as the transforms, this is probably wrong as we don't want users to be able to change that and we could also optimise what transforms are run since we have a node env there vs jsc.

**Comment by qasimalbaqali** [comment]
The thing that worked for me was deleting the node_modules folder and using `npm install` to install my dependencies.

**Comment by janicduplessis** [comment]
@MacKentoch @ekonstantinidis Do you have a .babelrc file in the project that fails to upgrade?

**Comment by MacKentoch** [comment]
@janicduplessis I event started from scratch a new project.

I got these 2 last issues in fact : 

 - [#6027](https://github.com/facebook/react-native/issues/6027)
 - and navigator transition has now a ugly dark background for few seconds (*before it was smooth staying grey - as I defined -*)
```javascript
///////////////////////////////////////////////////////////////
// navigator : my scene transition effect
///////////////////////////////////////////////////////////////
 configureScene={()=>Navigator.SceneConfigs.FadeAndroid}

///////////////////////////////////////////////////////////////
//each Views : before 0.20 it was a smooth fadeIn effect when component mounted
///////////////////////////////////////////////////////////////
// I wait all is ok to render my view (I set this.state.isReady)
  componentDidMount() {
    // to delay display heavy content and display a loading
    InteractionManager.runAfterInteractions(() => {
      this.setState({isReady: true});
    });

// in render
  render() {
    // test if loading
    if (!this.state.isReady) {
      return this.renderPlaceholder(); //this just render an empty grey back background with a loading icon
    }

   // real view when ready will appear in a fadeIn effect (thanks to react-native-animatable)
    const viewInfos = InfosModel.map((info, index) => {
      if (index === this.state.currentSavoirId) {
        return (
          <Animatable.View
            key={index}
            animation="fadeIn"
            duration={1500}


  }
```

Now I have a drawer `react-native-drawer` with black background.
So maybe it is something related... 

I have to dig more.

**Comment by MacKentoch** [comment]
Ok I changed drawer side content color to the opposite (white).
>Now I clearly see that the ugly dark effect is related to side content drawer background color.
So I guess I have to open an issue in `react-native-drawer` for that.

Migration to 0.20 just had this problem for me : [6027](https://github.com/facebook/react-native/issues/6027).

So it is already better :smile:

**Comment by janicduplessis** [comment]
At least #6027 doesn't do anything bad, it is just annoying -_-

**Comment by ekonstantinidis** [comment]
Any update/solution to the issue with Node 5? Node 4 is not an option for me because I also have tests and need react as a dependency.

**Comment by MacKentoch** [comment]
Fully agree. This warning won't break my application (just go production mode and it is gone :+1:). I'm glad this new version like previous seems like good.

**Comment by MacKentoch** [comment]
Ok I fixed my react-native-drawer transition issue.

It has nothing related to react native but a mix with react-native-drawer I guess.
>Fixing is easy and not a hack at all.


>To avoid ugly blink on navigation just specify a background color style to your navigator (*to avoid it from being transparent and showing drawer content color on navigation*).

In my application my views backgrounds are in grey and my drawer content is black. 
So I just added prop `sceneStyle={{ backgroundColor: '#ECECEC' }}` to navigator and I have same nice looking application as before migration.

```javascript

      <Drawer
        ref="drawer"
        onOpen={()=>this.handlesDrawerOpen()}
        onClose={()=>this.handlesDrawerClose()}
        type={'static'}
        panCloseMask={0.2}
        tapToClose={true}
        negotiatePan={true}
        panStartCompensation
        openDrawerOffset={0.2}
        closedDrawerOffset={-3}
        content={DrawerContent}
      >
        <Navigator
          ref="navigator"
          initialRoute={{ id: 1, refView : 'RootView' }}
          sceneStyle={{ backgroundColor: '#ECECEC' }}
          renderScene={(route, navigator)=>this.renderScene(route, navigator)}
          configureScene={()=>Navigator.SceneConfigs.FadeAndroid}
          navigationBar={
            <Navigator.NavigationBar
              routeMapper={navigationBarRouteMapper}
              style={styles.navBar}
            />
          }
        />
      </Drawer>
```

**Comment by latusaki** [comment]
@janicduplessis no .babelrc in standard build, only when running tests (same project with @ekonstantinidis )

**Comment by morochena** [comment]
I just had to update babel-register to 6.6.0 and it fixed this issue.

**Comment by fxhereng** [comment]
Installing babel-register 6.6.0 (which I have no idea what it is for) solved it
 :+1: @morochena

**Comment by jhabdas** [comment]
This seems fairly critical given the upgrade paths for most users have been blocked now and the upgrade instructions for `v0.21.0` call for a mandatory `react-native upgrade`.

**Comment by jhabdas** [comment]
@fxhereng The more dependencies you install the harder your app becomes to maintain. If you're not sure what something does, or if it seems like magic, good practice calls for further research before affecting change.

**Comment by jhabdas** [comment]
@MacKentoch The general comments in this issue regarding RN made it difficult for me to follow this thread. Do you know if there' s a chatroom for general upgrade chat?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/020-react-native-upgrade-error

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
