### ISSUE TITLE
[0.20] [Android] screenPhysicalPixels undefined

### ISSUE THREAD

**Issue by mikefowler** [facebook/react-native#5963]
Changes in 228a1fe7d48d57a0fbb2d852135ef94247198aaa appear to have broken Android. The requiring of `Dimensions` throws the following error:

`undefined is not an object (evaluating 'screenPhysicalPixels.width')`

![screen shot 2016-02-16 at 12 41 35 pm](https://cloud.githubusercontent.com/assets/744542/13090471/db3cb65c-d4aa-11e5-85e3-39b36d1d8326.png)

**Comment by ames89** [comment]
+1

I'm having the same issue, on the file react-native/Libraries/Utilities/Dimensions.js

in the object 

dimensions.screen = {
  width: screenPhysicalPixels.width / screenPhysicalPixels.scale,
  height: screenPhysicalPixels.height / screenPhysicalPixels.scale,
  scale: screenPhysicalPixels.scale,
  fontScale: screenPhysicalPixels.fontScale,
};

**Comment by gre** [comment]
Just reached the same problem. Any workaround?

**Comment by gre** [comment]
Ok I think actually it's a caching bug. I've removed the app from my phone and it worked.
make sure you also npm install from scratch

**Comment by RyanMitchellWilson** [comment]
Just tried removing the app, installed fresh node modules and reinstalled the app to the emulator and I'm still getting the same error.

**Comment by mikefowler** [comment]
I've also repeated similar steps to no avail:

1. Removed app from device
2. Stopped packager
3. `rm -rf $TMPDIR/react-*` to clear packager cache
4. `rm -rf node_modules && npm install` to reinstall all dependencies
5. `npm start`
6. `react-native run-android`

Same error.

**Comment by southerneer** [comment]
Same here. Tried @mikefowler 's steps and same result.

**Comment by paulbao** [comment]
same Issue, my workaround is change it to:
  // if (Platform.OS === 'android') {
  //   // Screen and window dimensions are different on android
  //   var screenPhysicalPixels = dimensions.screenPhysicalPixels;
  //   dimensions.screen = {
  //     width: screenPhysicalPixels.width / screenPhysicalPixels.scale,
  //     height: screenPhysicalPixels.height / screenPhysicalPixels.scale,
  //     scale: screenPhysicalPixels.scale,
  //     fontScale: screenPhysicalPixels.fontScale,
  //   };

  //   // delete so no callers rely on this existing
  //   delete dimensions.screenPhysicalPixels;
  // } else {
    dimensions.screen = dimensions.window;
  // }

in 'Libraries/Utilities/Dimensions.js'

**Comment by rameshvishnoi90904** [comment]
@paulbao it worked.

**Comment by paulbao** [comment]
Could you please help to confirm if it works now?

**Comment by rameshvishnoi90904** [comment]
@paulbao i am using android device and its working fine along with react-native @0.20

**Comment by paulbao** [comment]
@rameshvishnoi90904 Yes, you are right mate. I just forget to change dependencies.
`
 compile "com.facebook.react:react-native:0.20.+"
`
I guest we all made the same mistake.

**Comment by xfworld** [comment]
+1

**Comment by MrPluto** [comment]
@rameshvishnoi90904 @paulbao you're right. :beers:

**Comment by RyanMitchellWilson** [comment]
@satya164 why was this closed? This hasn't been fixed yet and I'd really rather not have to dig into my node_modules and fix the code everytime I reinstall them.

**Comment by gre** [comment]
@RyanMitchellWilson actually there are no bugs. grep for 0.19, you probably have an old version somewhere.

**Comment by mikefowler** [comment]
Confirmed. Though it's unclear if we all did something wrong or if `react-native upgrade` failed to update the string in `android/app/build.gradle`.

**Comment by sreesharp** [comment]
Confirmed. Updating build.gradle works.

**Comment by paulbao** [comment]
@mikefowler I updated react-native manually and it's my mistake not to update build.gradle also.

**Comment by zxcpoiu** [comment]
confirmed.

At first, I update react native only by `change dependency in packge.json then just npm install again`, it did NOT update build.gradle for you. That's what I was doing wrong.

If you are just running example or simple project without any specific settings, maybe it's proper to use `react-native upgrade`, it will detect conflicts and ask your confirm to overwrite like:

```
 conflict .gitignore
? Overwrite .gitignore? do not overwrite
     skip .gitignore

 conflict ios/project.xcodeproj/project.pbxproj
? Overwrite ios/project.xcodeproj/project.pbxproj? overwrite
    force ios/project.xcodeproj/project.pbxproj

 conflict android/app/build.gradle
? Overwrite android/app/build.gradle? overwrite
    force android/app/build.gradle

 conflict android/app/proguard-rules.pro
? Overwrite android/app/proguard-rules.pro? overwrite
    force android/app/proguard-rules.pro
```

**Comment by kunkun12** [comment]
change android/app/build.gradle  file    `compile "com.facebook.react:react-native:0.20.+" ` has solved

**Comment by aoriani** [comment]
Can someone point out which exact version of react-native fixes it? 0.20.1?  Using `+`  is discouraged and gives you a nice lint warning.  I prefer to have a fixed version.

**Comment by aoriani** [comment]
Okay. I verified that `compile 'com.facebook.react:react-native:0.20.1'` does the job.

**Comment by liyabo967** [comment]
I try to run ' react-native android ' at the root directory, and it works.
