### ISSUE TITLE
 Doc is not available in site http://facebook.github.io/react-native (Props , Styles)

### ISSUE THREAD

**Issue by jcsena** [facebook/react-native#5964]
documentation is not available in (Props , Styles) in COMPONENTS when I click on link redirect to home  site ex:

When touch in component TextInput [Text#style](https://facebook.github.io/react-native/text.html#style) redirect automatically to home site.

**Comment by jcsena** [comment]
React-native  doc version 0.20

**Comment by satya164** [comment]
cc @bestander

**Comment by bestander** [comment]
Thanks, will fix in a couple of hours

**Comment by jcsena** [comment]
it's solved for TextInput but i test with the [Text](https://facebook.github.io/react-native/docs/text.html#style) Component and redirect to home when clic on the link [View#Style...](https://facebook.github.io/react-native/view.html#style)

**Comment by bestander** [comment]
Yeah, thanks, already making another patch

**Comment by bestander** [comment]
fixed now
