### ISSUE TITLE
npm server fails to start on brand new project

### ISSUE THREAD

**Issue by pedramsaleh** [facebook/react-native#5966]
I just started on a fresh dev environment with Xcode 7.2.1, and installed react-native (0.20.0).  I initialized a test project to see if it would run, and I got the following error:
**~/dev/TestProj/node_modules/react-native/packager ~
packager.sh: line 11: node: command not found**

The iOS Simulator screen says:

**Could not connect to development server.**

**Ensure the following:**
**- Node server is running and available on the same network - run 'npm start' from react-native root**
**- Node server URL is correctly set in AppDelegate**

**URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true**

Sure enough, if I go into the project folder in a terminal window and run 'npm start' from there, the packager starts and everything works.  In my experience the packager should run by itself though when you run a project with React Native.  Am I doing something wrong here or is there an issue?

**Comment by mkonicek** [comment]
Can't repro on a fresh project. Can you debug where packager.sh is being called and why it fails and send a pull request to fix it?

Please see the comment above:

> If you don't know how to do something or something is not working as you expect but not sure it's a bug, please ask on StackOverflow with the tag react-native

This really helps us keep track of bugs in the GitHub bug tracker.

Closing as can't repro.

**Comment by mkonicek** [comment]
Have you followed https://facebook.github.io/react-native/docs/getting-started.html?

**Comment by pedramsaleh** [comment]
Yes I believe I followed those steps, as I had done before, but this time I got that error.
I moved on to trying to get my old project working on the same machine, and while trying to use npm to add new packages, I added the following to my .profile. I'm guessing this fixed it: 
export NPM_DIR="$HOME/.npm" [ -s "$NPM_DIR/npm.sh" ] && . "$NPM_DIR/npm.sh"
