### ISSUE TITLE
DatePickerIOS ignores minuteInterval in "time" mode

### ISSUE THREAD

**Issue by Somojojojo** [facebook/react-native#5967]
I've seen this issue posted once before but it was closed for some reason, even though users were still reporting it was broken. It seems to have been lost in the haystack so I'm reviving it.

The issue is: When you render a DatePickerIOS component with the mode set to `time` and the minuteInterval set to any integer (let's say 5, for example), the resulting component ignores the minuteInterval and draws normal incremental minutes, instead of those divisible by 5.
Set the mode to `datetime` and suddenly the component draws the minuteInterval correctly.

**Comment by christopherdro** [comment]
I believe the original issue was #2763.

What version of RN are you on?

Also any change you can throw a quick demo of it on rnplay.org? Its running on 0.20 stable right.

**Comment by Somojojojo** [comment]
We are running 0.19. I see that the 0.20 version seems to be working just fine. That's really weird though, because the datepicker stuff hasn't been touched in months. Is there any way to change rnplay to use older releases, to see if it's just 0.20 that fixes it?

**Comment by christopherdro** [comment]
@Somojojojo 
Unfortunately, rnplay only supports 0.20 at the moment. However, I just did a fresh install of both 0.19 & 0.20, and the `minuteInterval` prop works just fine in both `time` and `datetime` mode.

**Comment by Somojojojo** [comment]
Chris, I updated our react native install and tried the widget elsewhere
and it is working now... So weird. Sorry for bothering you, you can close
this issue.

**Comment by christopherdro** [comment]
:+1: No worries! Glad you got it resolved.

**Comment by ilove8** [comment]
Is it ok now? I updated react native version 0.31, but DatePickerIOS ignores minuteInterval in "time" mode.

**Comment by dizlexik** [comment]
I just created a brand new project with 0.38 and this is still an issue. `minuteInterval` does not work with `mode="time"`, but does work with `mode="datetime"`. I wonder how this ever worked for anyone... or has there been a regression? I really need this to work with `mode="time"` :/

**Comment by dizlexik** [comment]
So I found issue #9566 while investigating this and [@dsibiski's workaround](https://github.com/facebook/react-native/commit/002024cc456246761421f6e5c354466baa819843#commitcomment-19473525) of adding `width: 320` back to the styles in `DatePickerIOS.ios.js` resolved this issue for me.

**Comment by kalanaw** [comment]
The problem is still there with 0.41.2 and it's quite annoying. Setting the hardcoding a `width` in `DatePickerIOS.ios.js` works but certainly not the solution. Can anyone suggest a better looking hack?

**Comment by noaharogers** [comment]
Still not working, adding `width: '100%'` works as well.
