### ISSUE TITLE
WebSocketModule.connect RN 0.20 Android

### ISSUE THREAD

**Issue by skyride99** [facebook/react-native#5969]
When I upgraded to 0.20
got 4 arguments expected 2
When I Look at the java signature connect has 4 arguments.
iOS works fine...
This is the firebase node module.

<img width="534" alt="screen shot 2016-02-17 at 10 12 28 am" src="https://cloud.githubusercontent.com/assets/3801142/13097893/1ff3b952-d560-11e5-99ea-b517159eb978.png">

**Comment by satya164** [comment]
No idea why this will happen, since the JS code seems to call connect with 4 arguments. Probably you've a older version installed under `node_modules`.

**Comment by skyride99** [comment]
i think its an NPM issue had to upgrade to from 2 to 3. And reinstall all node packages.
