### ISSUE TITLE
Cmd+Shift+Z for dev menu in Sample App is not correct

### ISSUE THREAD

**Issue by krazyeom** [facebook/react-native#597]
To show dev menu is to press "Cmd + Control + Z" in the iOS simulator.

![screen shot 2015-04-02 at 7 38 22 am](https://cloud.githubusercontent.com/assets/442477/6954315/424359b0-d90b-11e4-8b12-aec36aa96ce7.png)

**Comment by vjeux** [comment]
@frantic we failed :(

**Comment by frantic** [comment]
:cry: @krazyeom please submit a PR

**Comment by krazyeom** [comment]
@frantic  https://github.com/facebook/react-native/pull/598 already submit a PR. Please check it.

**Comment by vjeux** [comment]
Fixed with 0.3.4, thanks!
