### ISSUE TITLE
iOS - when debug in chrome Cannot read property 'screenWidth' of undefined

### ISSUE THREAD

**Issue by newfun1994** [facebook/react-native#5996]
No any problem when run react native iOS app without debugging in chrome.
but when debug in chrome Cannot read property 'screenWidth' of undefined.
I use callback function to get screenWidth from objective-c

index.ios.js
`var DeviceInfo = require('react-native').NativeModules.DeviceInfo;`
`var deviceInfo;`

`DeviceInfo.deviceInfoEvent((error, events) => { `
    `if (error) {`
    ` console.error(error);`
   ` } else {`
   `  deviceInfo = events;`
   `  console.log({deviceInfo});`
   ` }
  `});`

`class ReactNativeDemo extends Component {`
`  render() {`
 `   return (`
 ` 	<View style={styles.container}>`
  `	  <Text>`
  `          screenWidth:{deviceInfo.screenWidth}{'\n'}`
  `	</Text>`
  `    </View>`
  `  );`
 ` }`
`}`

DeviceInfo.m
`RCT_EXPORT_METHOD(deviceInfoEvent:(RCTResponseSenderBlock)callback){`
`  NSNumber *screenWidth = @([UIScreen mainScreen].bounds.size.width);`
`  NSDictionary *deviceInfo = @{ @"screenWidth":screenWidth};`
`  callback(@[[NSNull null], deviceInfo]);`
`}`

**Comment by cosmith** [comment]
You shouldn't have to use DeviceInfo to get screen width, use `Dimensions` instead, like this:

```js
var {Dimensions} = require("react-native");
var {height, width} = Dimensions.get('window');
```

**Comment by cosmith** [comment]
@facebook-github-bot answered
