### ISSUE TITLE
CocoaPod spec

### ISSUE THREAD

**Issue by ide** [facebook/react-native#60]
CocoaPods is like npm for iOS and OS X. It keeps your dependencies up-to-date and sets up the Xcode workspace file so you don't have to manually drag ReactKit into the Movies project, for example. It probably makes sense to publish a CocoaPod for the public release.

There are a couple steps in this process. One thing that needs to be figured out is how to deploy the JS files under Libraries. Usually a CocoaPod will include Obj-C along with resource files inside of a bundle, but ReactKit's packager wants to bundle up both the core library files with the application JS (side note: worth thinking about changing this so apps don't need to load all the JS at boot). The right setup might be to split the project into three parts: ReactKit's native code (fetched via CocoaPods), ReactKit's core JS libraries (via npm), and react-kit-tools (packager, etc, fetched via npm). The workflow would look like:

```
pod try ReactKit
npm install react-kit react-kit-tools
npm start
# done!
```

Looking to get feedback on the overall idea or the specifics, especially because it affects both adoption of ReactKit and touches FB's syncing between the public and private repos.

**Comment by jaisanth** [comment]
+1 for @ide 's suggestion.

**Comment by a2** [comment]
Can we close this now that we have a CP spec?

**Comment by ide** [comment]
@a2 Yeah soon I think. The podspec needs a little bit of work (see #285) but with my diff I've gotten things running.

I would like to exclude unused code soon though, which is one thing a package system should provide. Discussion about external packages can continue in #235.

**Comment by zetachang** [comment]
As an iOS developer, +1 on @ide 's suggestion.

**Comment by paramaggarwal** [comment]
+1 on @ide 's suggestion to use npm as parent package manager and CocoaPods/Maven as platform-specific installers.

**Comment by ide** [comment]
The podspecs for RN and its helper libraries are in a reasonable place now. Module system still needs to be worked out and let's have that discussion separately.

**Comment by paramaggarwal** [comment]
Hop on to the module system discussion over at #235 if you want to hear about progress on the above suggestions.
