### ISSUE TITLE
autoGenerateWrapperClass is null 

### ISSUE THREAD

**Issue by chandu0101** [facebook/react-native#600]
I am writing wrapper for react-native in scala-js

      lazy val reactNative = js.Dynamic.global.require("react-native")
      val View = reactNative.View
      val component = ReactNativeB[Unit]("NativeYeah")
              .render(P => {
                 reactNative.createElement(View,null)
            }).buildU
      reactNative.AppRegistry.registerComponent("iOSscala", () => component())

**Component registered fine** ,but its failing while creating View element! 

> null is not a function (evaluating 'autoGenerateWrapperClass(tag)')"

Full stack trace : 

    CTJSLog> "Error: 
     stack: 
      getComponentClassForElement     index.ios.bundle:5894
      validatePropTypes               index.ios.bundle:5634
      createElement                   index.ios.bundle:5681
      renderApplication               index.ios.bundle:33913
      run                             index.ios.bundle:33858
      runApplication                  index.ios.bundle:33880
      jsCall                          index.ios.bundle:7237
      _callFunction                   index.ios.bundle:7484
      applyWithGuard                  index.ios.bundle:877
      guardReturn                     index.ios.bundle:7286
      callFunctionReturnFlushedQueue  index.ios.bundle:7493
     URL: http://localhost:8081/index.ios.bundle
     line: 5894
     message: null is not a function (evaluating 'autoGenerateWrapperClass(tag)')"

while debugging this function 

    function getComponentClassForElement(element) {
      if (typeof element.type === 'function') {
        return element.type;
      }
      var tag = element.type;
      var componentClass = tagToComponentClass[tag];
      if (componentClass == null) {
        tagToComponentClass[tag] = componentClass = autoGenerateWrapperClass(tag);
      }
      return componentClass;
    }

element type is ReactElement 

Note : the above code works fine in reactjs with div tag / react component.

***This is road blocker for me ,Could you please point me where i am doing wrong ...***

**Comment by spicyj** [comment]
Your component name needs to start with a capital letter. I should improve the warning for this.

**Comment by chandu0101** [comment]
i changed my component name 
````js
reactNative.AppRegistry.registerComponent("AwesomeProject", () => AwesomeProject())
```
still same error!

**Comment by vjeux** [comment]
reactNative.AppRegistry.registerComponent(AwesomeProject, () => AwesomeProject())

With no quotes

**Comment by vjeux** [comment]
Ooos sorry, nevermind me

**Comment by spicyj** [comment]
Can you reproduce the same problem in JS? I don't know scala-js, nor do we support it but if you show me the problem in JS I can take a look.

**Comment by chandu0101** [comment]
hmm , in js i am not able  to reproduce this . 
is something changed in react-native ? because the above builder generates react elements  which works fine in reactjs.
and in js land while debugging ``getComponentClassForElement`` element.type for React.createElement(View... ) is function but in my case ReactElement , do you see anything fishy here ?

**Comment by spicyj** [comment]
If you can't reproduce in plain JS, this isn't a react-native issue. Perhaps a scala-js list would be a better forum for this question.

**Comment by vjeux** [comment]
Note that when you pass `undefined` to React.createElement it displays this crazy error. We need a more explicit message.

Example:

```
var Component = undefined;
var c = <Component />; // crashes with autoGenerateWrapperClass is null
```

We need to fix this @spicyj

**Comment by spicyj** [comment]
@vjeux Thanks – filed https://github.com/facebook/react/issues/3565 to track.
