### ISSUE TITLE
Websocket Not Working (Android, tried connecting to a local and online server)

### ISSUE THREAD

**Issue by cabooserwar** [facebook/react-native#6001]
So this is detailed in my stackoverflow post here:
http://stackoverflow.com/questions/35450756/react-native-websocket-android-not-connecting-to-server

Right, now I'm trying to run (originally on react-native 0.18, and then later on 0.20) a websocket through react-native android on a Samsung Galaxy S4. 

Here is the gist of my code:
```javascript
var hostname = "192.168.X.XXX";
var port = "4567";
const webSocket = new WebSocket("ws://" + hostname + ":" + port + "/chat");
```

```javascript
componentWillMount: function(){

    console.log("MOUNTING CHAT COMPONENT");
    webSocket.onopen = function(){ 
      console.log("binding to chat room");
      bindToChatRoom(); 
      setTimeout(keepWebSocketOpen, 30000); 
      ws_connected = true; 
    };

    webSocket.onmessage = function (msg) {
      this.handleMsg(msg); 
    };

    webSocket.onclose = function () {
      console.log("WebSocket connection closed"); 
      ws_connected = false; 
    };

    webSocket.onerror = function (e){
      //add some error handling -> DO THIS
      console.log(e.message);
    };
  },
```

I tried connecting to a locally hosted sparkjava server (that has been tested using regular html and js), and then I tried connecting to ws://echo.websocket.org but neither would print the console.log message "binding to chat room". Does anyone know what's going on? No answer on stackoverflow, and the android examples of this are really limited, so I can't really tell what I'm doing wrong.

**Comment by satya164** [comment]
`WebSocket` works fine for me on `0.18` with `engine.io`. I had tested with `echo.websocket.org` previously and it was working fine with it.

**Comment by christopherdro** [comment]
I've also been using it with 0.19 + 0.20 without any issues.

@satya164 Makes a good point. Where are you defining the websocket. You can just try to move everything to componentDidMount for testing.

**Comment by cabooserwar** [comment]
Ah okay, I'll try that out tonight and get back to you.

**Comment by cabooserwar** [comment]
yup, just had to move 
`const webSocket = new WebSocket("ws://echo.websocket.org");` into componentWillMount. Thanks!
