### ISSUE TITLE
[WebViewExample] Bundled HTML does not work

### ISSUE THREAD

**Issue by lu-ko** [facebook/react-native#6004]
I cannot render bundled HTML file in [WebView](https://facebook.github.io/react-native/docs/webview.html). I suppose it is a bug in React Native because it does not work also in your [WebViewExample ](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/WebViewExample.js) and [UIExplorer](http://www.reactnative.com/uiexplorer/).

**Error in Android emulator:**
- E/ReactNativeJS: Requiring unknown module "./helloworld.html". If you are sure the module is there, try restarting the packager.
- Restart of packager did not help.
- React Native version: 0.19

**Error in your online [UIExplorer](http://www.reactnative.com/uiexplorer/):**
- Error loading page. Domain: NSURLErrorDomain. Error Code: -1100. Description: The requested URL was not found on this server.
- See screenshot.

![uiexplorer-webview-bundledhtml-error](https://cloud.githubusercontent.com/assets/9402679/13139749/55deaf94-d62e-11e5-970b-672fcff18371.PNG)

**Comment by lu-ko** [comment]
It's fixed in React Native v.0.20, but there is still the same error in UIExplorer. Maybe it was not upgraded to latest version yet. Thank you guys!

**Comment by letsila** [comment]
+1

**Comment by rotemsloo** [comment]
I have the same error and behavior , can't present local html in webView in both ios and Android.
here's a sample RN app to demonstrate the behavior.

[sample app](https://github.com/rotemsloo/testing-RN-webview-local)

any idea? I'm on 0.23.1 and now testing on 0.24 and it also don't wokr.

**Comment by comiclee** [comment]
+1 It doesn't work on the latest 0.25.1

**Comment by rotemsloo** [comment]
@comiclee  one solution is to load the html with require , I still haven't upgraded to 0.25 but it works for 0.23

**Comment by comiclee** [comment]
@rotemsloo, require html files can work in develope mode, but fails in release apk file

**Comment by ramilushev** [comment]
+1. I'm seeing this on latest version. Debug build is fine, but release shows blank page.

**Comment by nicklockwood** [comment]
cc: @dmmiller

**Comment by dmmiller** [comment]
Looking at release build now.  Thanks for the heads up.

**Comment by lacker** [comment]
As far as I can tell this got fixed. I'm going to close this issue but if people see it recur with recent builds of React Native please feel free to open a new issue.

**Comment by saumya** [comment]
Its still not working, I mean its not fixed.

RN 0.36 on Android. Assets need to be manually placed as suggested above.

**Comment by eggli** [comment]
Not working on RN 0.37 as well.

**Comment by xsstomy** [comment]
Not working on RN 0.39.2 as well.

**Comment by Lxxyx** [comment]
Not working on RN 0.40 as well.

**Comment by raymallperez** [comment]
Not working on RN 0.41 as well.

**Comment by wkw** [comment]
on RN 0.40, `require('./file.html') is failing for me in Build release variant. as others have mentioned above. As workaround, I was able to put the file in android assets dir, and `{ uri: file:///android_asset/file.html` } it in from there. Unfortunately for my situation, the html file loads remote third-party libs which internally reference protocol-agnostic resources: e.g., `//domain.com/file.json`. So those all got turned into `file://domain.com/file.json` links and of course failed. 
I monkey patched XMLHttpRequest to change `//...` to `https://...` which solved that problem, but none of the images those libs attempt to load, will load. all broken. And I've been unable to find a way to determine what the requests look like for those images, to see why they break/fail-to-load.

**Comment by saumya** [comment]
As @lacker was saying we should open a new issue, has anyone opened a new issue for this? Or should we continue in this thread? For me, it seems we should continue here only and re-open this one.

**Comment by FuadBalashov** [comment]
It looks like this is being tracked in this issue now: https://github.com/facebook/react-native/issues/7924
