### ISSUE TITLE
[0.20][iOS] React native throws View has no propType error after upgrade.

### ISSUE THREAD

**Issue by BilalBudhani** [facebook/react-native#6006]
After upgrading from react-native 0.19 to 0.20. When I run iOS emulator from `react-native run-ios` command, my app is throwing following error: 

```
View has no propType for native prop RCTView.maxHeight of native type CGFloat
If you haven't changed this prop yourself, this means that your versions of the native code and javascript code are out of sync. 
Updating both should make this error go away
```

However, When I run the emulator from XCode, My app works fine. I'm not able to figure out what part is native code and what is javascript code so that I can get them in sync, as pointed out by error message. 

Screenshot: 
<img width="375" alt="screen shot 2016-02-18 at 4 33 54 pm" src="https://cloud.githubusercontent.com/assets/1650995/13141499/a69894c0-d65d-11e5-8c61-812724ba0220.png">

Node version: 5.6.0

**Comment by mkonicek** [comment]
Hey @BilalBudhani, the {min/max}{Width/Height} props were removed in https://github.com/facebook/react-native/pull/5522, the Flexbox layout library RN uses (https://github.com/facebook/css-layout) doesn't support them correctly, sorry about that! Is it possible to achieve your layout without those?

There's also https://github.com/facebook/react-native/issues/4644

I'll close this as that answers your question.

**Comment by mkonicek** [comment]
I'd like to ask a meta question :)

I've added the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) and hoping it would make it clear it's best to ask on StackOverflow first before filing a bug on GitHub.

I'd like to ask: is that description clear enough? What did you think when you saw it? Was it too long for example?

**Comment by BilalBudhani** [comment]
@mkonicek The issue template did made me think twice before creating this issue. However, I believe the `Stackoverflow` section should be moved to the top, swapping with `debug and fix` section. Because I feel that's the most occurred scenario. 

Also, What me create this issue here rather than posting on StackOverflow is, The app was breaking when ran from command line and not from XCode. That made me certain that this is a bug needs to be reported.

**Comment by lorensr** [comment]
I also get this error on new repo. To reproduce, I do:

```sh
$ react-native init repro
$ cd repro
$ react-native run-ios
$ react-native -v
react-native-cli: 1.0.0
react-native: 0.32.0
```
