### ISSUE TITLE
Trying to use Android Studio

### ISSUE THREAD

**Issue by BigPun86** [facebook/react-native#6007]
Hey there, i am trying to use ReactNative with Android Studio. I followed the steps on: [Building React Native for Android](https://github.com/facebook/react-native/tree/master/ReactAndroid)
But it fails when i try to copy gradleplugin from my local maven repo to android studios maven repo. 

    cp -r ~/.m2/repository/com/facebook/react/gradleplugin /Applications/Android\Studio.app/Contents/gradle/m2repository/com/facebook/react/

Thats what i get: 

    No such file or directory 

Actually i don´t have any local maven repo, maybe someone can help me how to set it up

**Comment by mkonicek** [comment]
Good catch, those docs haven't been updated in a while. Will commit a fix.
