### ISSUE TITLE
Required prop `onDateChange` was not specified in `RCTDatePicker`.

### ISSUE THREAD

**Issue by iTonyYo** [facebook/react-native#6008]
![image](https://cloud.githubusercontent.com/assets/5499703/13144174/e8db3164-d683-11e5-8ff6-ef9ed2136009.png)
![2 pic_hd](https://cloud.githubusercontent.com/assets/5499703/13144188/067ff8bc-d684-11e5-813a-79bd8578a771.jpg)

**Comment by Emilios1995** [comment]
And what's the issue? The warnings are clearly telling you what to do. If you don't know how to do something, you should post a question on stackoverflow.com

**Comment by vanBrunneren** [comment]
I have the same problem, take a look at https://github.com/facebook/react-native/issues/4547

**Comment by mkonicek** [comment]
People need to see your code to be able to debug the issue. How do you declare the `DatePicker`s in your code?

Closing until this has more info so it is actionable.
