### ISSUE TITLE
bundle use dev=false transforms/whole-program-optimisations dead-module-elimination error

### ISSUE THREAD

**Issue by joeyzone** [facebook/react-native#6018]
when i use command react-native start , http package use dev=false, creat a new file example test1.js and test2.js empty file. http find test1.bundle is right. http find test2.bundle is not correct. 
because dev=false  use  'transforms/whole-program-optimisations' that require 'dead-module-elimination', result bundle not require test2. i can't find this dead-module-elimination bable plgin error. but if i don't use this plugin is right budle result.

my react-native version is 0.17

**Comment by chujj** [comment]
I also has this problem with 0.17.0 through http server api.

The new create *.jsx **sourcecode will totally removed** from result *.bundle with argument _dev=false_ .

Now I remove babel transform code in[ Bundle.js](https://github.com/facebook/react-native/blob/v0.17.0/packager/react-packager/src/Bundler/Bundle.js#109) to avoid this problem.


    
    109 //    if (dev) {
    110       return this._source;
    111 //    }

**Comment by brentvatne** [comment]
Hi there! This should no longer be an issue in newer versions of react-native, where whole program optimisations only runs when bundling for release
