### ISSUE TITLE
[Tests] JS tests on Travis CI hang after completion

### ISSUE THREAD

**Issue by ide** [facebook/react-native#6019]
It appears likely to be related to the Haste 2 change (cc @cpojer). The JS, CLI, and packager tests all run Jest and terminate with:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

https://travis-ci.org/facebook/react-native/builds/110065663

This is the build log, which makes me think something in Haste 2 is the cause:

<img width="955" alt="screenshot 2016-02-18 18 05 58" src="https://cloud.githubusercontent.com/assets/379606/13164472/68fed34c-d66a-11e5-90ab-8ec20a30b855.png">

**Comment by cpojer** [comment]
Yeah it is likely haste 2 and file watching. Pretty sure it is one of these two: https://github.com/facebook/jest/blob/master/src/resolvers/HasteResolver.js#L117 – maybe persisting the cache or for some reason it can't stop watching the file system?

Can you somehow trigger a run just without properly ending either of these?

**Comment by skevy** [comment]
@cpojer I'm pretty sure it does have to do with the filewatcher...I encountered this when I was using node-haste elsewhere. I had to explicitly call `.end()` which is something we're probably not doing in these tests anywhere.

**Comment by cpojer** [comment]
ohhhhh... I noticed this in Jest too when I was creating a real FileWatcher instance in one of my tests and then I didn't kill that one. Are we doing this anywhere in the tests for react-native? Like, create an unmocked instance of FileWatcher that we don't call .end() on?

**Comment by cpojer** [comment]
Ide, this is fixed now, right? Feel free to reopen if its still an issue.

**Comment by ide** [comment]
LGTM, tests are failing instead of erroring so that's good.

**Comment by master-atul** [comment]
Hi, We are getting this same issue on travis now.
We are using  "jest": "^19.0.2"
