### ISSUE TITLE
Crashing when starting up RN on Android due to JS error on h.propTypes

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#6021]
I believe my app is crashing on an Android Galaxy S3 inside React Native 0.19's Javascript. From Crashlytics, I can see the error is happening at this point:

Fatal Exception: com.facebook.react.modules.core.JavascriptException: <unknown>
    index.android.bundle:15:8607

I built index.android.bundle and had a look at it, and line 15 looks like it is still part of RN, not my app. That's why I believe this is a RN bug, but I could very well be wrong.

The app runs fine when I run it locally with react-native run-android. It's only happening on my Android once I shipped the app to Google Play.

Character 8607 is the last 's' character in h.propTypes, where h is t("View"), which I believe is React Native's View. If I had to guess, it's probably a JS error "Uncaught TypeError: Cannot read property 'propTypes' of null"

```
... function(e,t,n,r){"use strict";var o=t("ColorPropType"),i=t("NativeMethodsMixin"),s=t("React"),a=t("ReactNativeViewAttributes"),u=t("StyleSheet"),c=t("react-timer-mixin/TimerMixin.js"),l=t("Touchable"),p=t("TouchableWithoutFeedback"),h=t("View"),d=t("ensureComponentIsNative"),f=t("ensurePositiveDelayProps"),v=t("keyOf"),m=t("merge"),g=t("onlyChild"),y={activeOpacity:.8,underlayColor:"black"},_={top:20,left:20,right:20,bottom:30},b=s.createClass({displayName:"TouchableHighlight",propTypes:babelHelpers["extends"]({},p.propTypes,{activeOpacity:s.PropTypes.number,underlayColor:o,style:h.propTypes.style ...
```

Character 8607 is the 's' in propTypes at the end there.

I'm going to try upgrading to 0.20, but is this a known issue for 0.19?

**Comment by dsibiski** [comment]
@pickhardt I wonder if you're JS bundle is getting created when you are building for release...when you build for release, does it generate a `index.android.bundle` file in `android/app/src/main/assets/`?

If not, run this command in the root of your project before building your app for release:

```
react-native bundle --platform android --dev false --entry-file index.android.js \
  --bundle-output android/app/src/main/assets/index.android.bundle \
  --assets-dest android/app/src/main/res/
```

Then run:

`cd android && ./gradlew assembleRelease`

I remember for me the 'assembleRelease' command for some reason didn't always generate the bundle. I dunno, at least it's something to try.

**Comment by pickhardt** [comment]
The instructions say you only have to do that if you don't have a react.gradle file. (https://facebook.github.io/react-native/docs/signed-apk-android.html#content)

When I run `cd android && ./gradlew assembleRelease` it outputs the APK, but no, it doesn't output an `index.android.bundle` file in `android/app/src/main/assets`.  It doesn't say in the instructions that it should do that, so I don't think it needs to.

Nonetheless, I'll try it and see if that fixes the problem.

Also, having upgraded to 0.20 last night, then deploying to Android, that did not fix the problem.

**Comment by dsibiski** [comment]
Yeah, if the index.android.bundle file isn't there, then you have no JS,
which explains the crash. There is probably a bug in that script or
something. I know it's new. I'm pretty sure that is it because that's what
I had to do for a release of one of my Android apps and I haven't had any
crashes.

**Comment by pickhardt** [comment]
Closing this because the problem was fixed by running `react-native upgrade`
