### ISSUE TITLE
Support elevation for the drawer in DrawerLayoutAndroid

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#6022]
`style` on `View` supports an `elevation` property on Android 5+ that works with Android's Elevation API.

But there is no external access to the view for the actual drawer used in `DrawerLayoutAndroid`. It can't be replaced like `navigationBar` in `Navigation` allows, setting `style={{elevation: 16}}` doesn't work, and there's no prop to pass styles for the drawer. `renderNavigationView` exists, but that defines the contents of the drawer, not the drawer itself, so elevation on it doesn't work.

Under the Material Design guidelines navigation drawers should have an elevation of 16.
https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-

On the navigation drawers page you can see the shadow cast by the elevation:
https://www.google.com/design/spec/patterns/navigation-drawer.html
![...](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3RkZGRGhaM3c5ZDg/patterns_navdrawer_metrics1.png)

**Comment by janicduplessis** [comment]
There was quite a few things that made this not work will be fixed in #6100. It would be nice to support the transparent StatusBar with the drawer under it too, I'll probably look at it when I get some time :)

**Comment by dantman** [comment]
@janicduplessis For the status bar, you mean dynamically? Or natively?

I'm actually already doing that just by tweaking my styles.xml and padding/underlaying the status bar area using a calculation of the status bar height given by a 3rd party lib.

**Comment by janicduplessis** [comment]
I'd like it to work without having to tweak the styles.xml. The StatusBar module already supports making the app draw under the status bar and then I can either use the native drawer layout setStatusBarColor or just draw it in js in the DrawerLayout component.
