### ISSUE TITLE
about Websocket

### ISSUE THREAD

**Issue by xhacker5000** [facebook/react-native#6026]
I saw the RN's doc have 4 events

``
onopen
onmessage
onerror
onclsoe
``

I wanna know when I call 
```javascirpt
new WebSocket('ws://xxx');
//if server not open which one can handle this situation, I try each of them , no event recv.

```
Is there any way to set timeout with websocket connect event ?

**Comment by antigirl** [comment]
I'm pretty sure error is called.
`       ws = new WebSocket('ws://localhost:3000');
        ws.onerror = (e) => {
            alert('WebSocket error: ' + e.message);
        };`

I've used websockets in my chat app if you wanna have a look
https://github.com/antigirl/ReactNativeChatApp

**Comment by christopherdro** [comment]
@xhacker5000 

@antigirl Is right. The `onerror` callback will be called.
