### ISSUE TITLE
warning in ScrollResponder.scrollResponderScrollNativeHandleToKeyboard

### ISSUE THREAD

**Issue by yueshuaijie** [facebook/react-native#6027]
Version 0.20.0
When I use ScrollResponder.scrollResponderScrollNativeHandleToKeyboard to scroll my view when keyboard shows, there is a warning: 
`scrollResponderScrollTo(x, y, animated)` is deprecated. Use `scrollResponderScrollTo({x: 5, y: 5, animated: true})` instead.

The reason is Libraries/Components/ScrollResponder.js, line 464:
`this.scrollResponderScrollTo(0, scrollOffsetY);`

**Comment by janicduplessis** [comment]
This was fixed in 78a9125de87006c0da40edcd5d6029d360247ded

**Comment by alduro** [comment]
@janicduplessis was this fix deployed in some particular React Native version ?

**Comment by janicduplessis** [comment]
No, I'll try to get it cherry picked into 0.21

**Comment by alduro** [comment]
@janicduplessis thanks ! it is a warning but keyboard is not being shown due to this I guess.

**Comment by geirman** [comment]
@janicduplessis looks like this can be closed to me. It appears this has been included in every release since 0.22-rc. Agreed?

**Comment by janicduplessis** [comment]
Yep :)

@facebook-github-bot close
