### ISSUE TITLE
ScrollView can be zoomed even if scrollEnabled is false

### ISSUE THREAD

**Issue by gre** [facebook/react-native#6031]
to me either scrollEnabled={false} should also disable the zoom/pan feature OR we need a zoomEnabled props.

**Comment by grabbou** [comment]
2nd one sounds more reasonable to me.

**Comment by martincox** [comment]
First try at contributing here! :)

I tried to replicate this but cannot.

Both [maximumZoomScale](https://facebook.github.io/react-native/docs/scrollview.html#maximumzoomscale) and [minimumZoomScale](https://facebook.github.io/react-native/docs/scrollview.html#minimumzoomscale) are set to 1.0 by default, which implicitly disables zooming.

When implementing a ScrollView you would need to set those props explicitly to enable zooming, and is that is not a desirable behaviour, it can be left unmodified.

**Comment by grabbou** [comment]
Ah, that's right. It might have been added in the meantime @gre ? Anyway, as far as I am aware of native capabilities here, that's also the way to disable zooming in Obj-C (there's no zoomEnabled property on a UIScrollView).

Thanks @martincox for your help here!

**Comment by gre** [comment]
@martincox true, but I have a use-case that make it hard to "just change min and max".

Let's say I am implementing a "cropper" when someone can zoom (like from 1x to 5x) and pan in an image. In some cases I want to disable the zoom feature but leave what the user zoom was (like maybe it was 2.345x). It's hard to implement that by changing the min max to this value (I would say it's a hack).

It's a bit like saying: let's not implement input disabled for range, you can just do `<input type=range min=2.345 max=2.345 />`

**Comment by grabbou** [comment]
Maybe you could use a custom PanResponder for that purpose and just discard the events when that condition happens?

**Comment by gre** [comment]
true, but it's a bit more complex than just a prop I guess? I mean, since we have scrollEnabled, I feel we should have zoomEnabled. at least if it makes sense on the iOS UIScrollView side.

**Comment by grabbou** [comment]
That's true, however the main problem here is that native UIScrollView does not have that property itself (the only way to disable zooming is to just set min/max to be the same).

**Comment by gre** [comment]
oh ok. so I guess we shouldn't introduce this then. I guess RN idea is to reflect props from UI components, not reinvent some. We'll just have to try initial suggestion of setting them from JS I guess then.

Thanks
