### ISSUE TITLE
Merge PRs that get master back to good state

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#6037]
Creating this issue purely to track everything that's remaining to get master back to good state:

The e2e test on Travis has been consistently failing for several days:
https://travis-ci.org/facebook/react-native/builds

My understanding is the root cause is the interaction between these two PRs (reverting both makes `npm install` from master and running an app work again): https://github.com/facebook/react-native/pull/5812 (75869519e6703b5afd74dfcbcb886c73098e199a), https://github.com/facebook/react-native/pull/5813 (9f01f9677096117da8be721913a09db870505c2f).

The following PRs should get us back to good state: https://github.com/facebook/react-native/pull/6039 (depends on https://github.com/facebook/node-haste/pull/33) and https://github.com/facebook/react-native/pull/5084. Possibly also https://github.com/facebook/react-native/pull/6040.

**Comment by skevy** [comment]
This one too: https://github.com/facebook/react-native/pull/5811

Updates Babel to 6.5.x, which has a ton of bug fixes, and also puts React in "devDependencies" (in addition to peer) so that it works properly in Travis/Circle.

**Comment by skevy** [comment]
@bestander if you run into trouble when trying out npm 3.7, it's most likely because React needs to be a dev dep, which is fixed in that PR ^^ :)

**Comment by bestander** [comment]
:+1:

**Comment by grabbou** [comment]
Is there anything else to do on this issue? I have just checked and all PRs mentioned here were either closed or merged.

**Comment by satya164** [comment]
I guess it should be good to close. Please re-open if 'm wrong.
