### ISSUE TITLE
I integrate react-native with my existing app,  how can running on device using offline bundle.

### ISSUE THREAD

**Issue by loumzy** [facebook/react-native#6045]

**Comment by loumzy** [comment]
I have solved the problem by running the command in terminal 

```
cd  /Users/smallpie/ios/ocProject/Fanli2/node_modules/react-native 
```

```
curl http://localhost:8081/index.ios.bundle -o main.jsbundle
```

these command create a "main.jsbundle", and copy this file into my project ,it running correctly

**Comment by dsibiski** [comment]
@loumzy You can only run this command, right from the root of your project:

`react-native bundle --entry-file index.ios.js --bundle-output ios/main.jsbundle --dev=false`

That should save you the last step where you copy the file to your project. :+1:

**Comment by mkonicek** [comment]
Cool, thanks @dsibiski.

Closing as the question has been answered.
