### ISSUE TITLE
Use Strict Error Crash!

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#6048]
Hi,

Redefining a property inside the StyleSheet causes the app to crash with no error screen or message. 
Also function declarations inside functions. So I would guess every error caused by 'use strict' crashes the app. You would need to do a fresh install to get the app run again.
The only way to get the error log message is with Android Studio.

Thank You!

**Comment by browniefed** [comment]
@facebook-github-bot label Needs More Information

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow

**Comment by mkonicek** [comment]
Can you provide some code to repro this?

**Comment by mkonicek** [comment]
What is the log message?

**Comment by browniefed** [comment]
@facebook-github-bot reopen

**Comment by DHidee66** [comment]
Not using `use strict` on top of the js files doesn't check for duplicates inside the `StyleSheet` properties. So for example if you have two `marginTop` inside the same object it will use the last one.
If you add `use strict` an error about `A/libc ` appears on the debugger console and the app crashes with no error screen.

**Comment by satya164** [comment]
Duplicate properties should be allowed in loose mode. It seems to be an issue with JSC, not the parser.

**Comment by mkonicek** [comment]
Duplicate props in strict mode only crash the app on Android, not iOS, right? Does iOS show a redbox?

@DHidee66 Would you be up for sending a PR that makes it show a redbox instead?

**Comment by DHidee66** [comment]
@mkonicek I haven't tried it in iOS. I will try and fix it. :)
