### ISSUE TITLE
Shadow rendering and LayoutAnimation

### ISSUE THREAD

**Issue by williambout** [facebook/react-native#6050]
Hi,
I have an issue with shadows and LayoutAnimation. When I animate the height of a view with a shadow, the rendering of the shadow is not working properly.
It looks like the shadow is rendered with the final height of the view, not the current height.

Here is a little demo of the problem : https://rnplay.org/apps/Xm5KLg

**Comment by williambout** [comment]
Fixed with Animated.

**Comment by MrLoh** [comment]
Hey @williambout I ran into the same issue, could you provide me with some hints as to how you solved this with Animated?

**Comment by stajics** [comment]
@williambout Same issue. Could you provide me with some hints as to how you solved this with Animated?

**Comment by MrLoh** [comment]
@stajics You can solve it by just manually animating the e.g. width value from the start to the end position. You'll have to calculate the width yourself though using onLayout etc.
