### ISSUE TITLE
Failed run android simulator : com.android.builder.testing.api.DeviceException: Timeout getting device list.

### ISSUE THREAD

**Issue by kukuv2** [facebook/react-native#6060]
I try to run app on android simulator but failed:
![image](https://cloud.githubusercontent.com/assets/6963328/13202297/8d51482a-d8d0-11e5-87e7-f20ce8bad439.png)
![image](https://cloud.githubusercontent.com/assets/6963328/13202298/962b17aa-d8d0-11e5-9475-46df0631114c.png)
![image](https://cloud.githubusercontent.com/assets/6963328/13202304/f97349b8-d8d0-11e5-9fc6-217377fb8383.png)
someone can help?

**Comment by jiangqqlmj** [comment]
see environment。  set config '.bash_profile'  file  with ANDROID_HOME

**Comment by kukuv2** [comment]
@jiangqqlmj Thank you! I try it ,but it doesn't work.The following is my ~/.bash_bashrc and my ~/.bash_profile 

![image](https://cloud.githubusercontent.com/assets/6963328/13202526/f1b145d8-d8d8-11e5-914e-24d758a6566c.png)
![image](https://cloud.githubusercontent.com/assets/6963328/13202527/f4ef12b6-d8d8-11e5-809a-640718986436.png)

**Comment by mkonicek** [comment]
This looks related to Gradle. Can and independent of React Native. Can you try googling "Timeout getting device list" before filing this bug on React Native?

I'll close this for now and if you can't resolve this by Googling let's reopen.
