### ISSUE TITLE
Unable to get MapView heading angle and rotate my view in map annotation

### ISSUE THREAD

**Issue by tehong** [facebook/react-native#6065]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Please read the following tips before filing an issue:

Is this something you can debug and fix?
-------------------------------------------------------

Can you see anything in the logs? Can you debug why this happens? **Send a pull request**! Bug fixes and documentation fixes are very welcome.

Have a question or not sure you've found a bug?
-----------------------------------------------------------------
Please ask your question [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) with the tag `react-native`. StackOverflow is amazing for Q&A. Because of the reputation system it is likely the community will see and answer your question there.

Make sure you **include a short code snippet to demonstrate the problem**.

Have an idea for a feature?
------------------------------------
Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system that lets us focus on the most important issues the community is experiencing. The higher number of votes the more likely it is a feature will get implemented. You could always implement it yourself, too.

None of the above, want to create a GitHub issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the issue** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- If this is a bug, provide a **minimal code snippet** that reproduces it
- Provide **screenshots** where appropriate
- What's the **version** of React Native you're using?
- Does this occur on iOS, Android or both?
- Are you using Mac, Linux or Windows?

**Comment by tehong** [comment]
The latest MapView is great to put custom component in the annotation.  However, when I rotate the map heading angle via finger touch rotation.  The annotation view doesn't rotate with it.  More details:  I have annotation that have symbols point to a specific angle from the true north, however, when I use two finger touches to rotate the map heading angle, my symbol on the annotation doesn't rotate.   So I need a way to rotate my symbol by detecting the current MapView heading angle from the true north or I need way to tell the annotation automagically rotate with the map's changing heading angle.

**Comment by mkonicek** [comment]
Hey and thanks for posting this!

This looks like an usage question. There's an awesome place to post code / ask question first before filing an issue: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
