### ISSUE TITLE
Task 'installDebug' not found in root project 'AwesomeProject'.

### ISSUE THREAD

**Issue by anwarhussain93** [facebook/react-native#6072]
**This error happens on windows** 

* What went wrong:
Task 'installDebug' not found in root project 'AwesomeProject'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info                                                                                                                        or                                                                                                                     --debug                                                                                                                  
option to get more log output.

**Comment by mkonicek** [comment]
Hey, this issue needs more information. The error from Gradle will be printed above the error you posted.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by CharlesJQuarra** [comment]
this issue keeps happening on latest react version

**Comment by sduqlsc** [comment]
@mkonicek same issue here, it happened after adding product flavor in `build.gradle` as below:
```
productFlavors {

            prod {
                applicationId "com.AA.BB"
            }
       }

```
Note that orginal appliactionId is `com.BB`, btw, is there a way to change the 'appliactionId' generated by 'react-native'. Till now, not find a solution for that, :( .

**Comment by DarrylD** [comment]
Stilling happening, any fix for this?

**Comment by sduqlsc** [comment]
@DarrylD if you have the same issue with me, just use command `react-native run-android --variant [productFlavorName][debug/release]`。

**Comment by DarrylD** [comment]
@sduqlsc after searching around for 3 hours, go to the docs and the answer is right there. Thanks for confirming!

**Comment by sduqlsc** [comment]
@DarrylD  glad to hear that, :).

**Comment by ickyrr** [comment]
@DarrylD , Hello, can you please tell me where exactly did you find the solution? Thank.

**Comment by Kennytian** [comment]
react-native run-android --variant [productFlavorName][debug/release]

e.g.
react-native run-android --variant GooglePlaydebug
react-native run-android --variant Huaweidebug

**Comment by Ramaraju1992** [comment]
@Kennytian  what if we have two flavors in productFlavor??

> productFlavors {
>         app {
>         }
>         appfdroid {
>         }
>     } 

to release..........?

**Comment by sduqlsc** [comment]
@Ramaraju1992 same to the reply provided by @Kennytian 
```
react-native run-android --variant GooglePlayrelease
react-native run-android --variant HuaweiRelease

```

**Comment by LuckySambial** [comment]
Task 'installGooglePlaydebug' not found in root project 'android'.
getting this error can anyone help me ?
@sduqlsc @DarrylD

**Comment by sduqlsc** [comment]
@LuckySambial have you configured googoleplay in `productflavor` of `build.gralde`
