### ISSUE TITLE
Document options for statusbarios style

### ISSUE THREAD

**Issue by joshbedo** [facebook/react-native#6077]
There is no documentation on the styling options provided. The component example page only shows 'default' and 'light-content'.

**Comment by janicduplessis** [comment]
This is the only 2 options available. It kind of suck that we only display the flow type name and not what it actually is. You have to look at the source at the moment to know the possible values.

https://github.com/facebook/react-native/blob/master/Libraries/Components/StatusBar/StatusBar.js#L22

**Comment by joshbedo** [comment]
Alright, thanks for sharing :)

**Comment by janicduplessis** [comment]
@facebook-github-bot answered
