### ISSUE TITLE
Can I use react-native for Android now if I don't use the native UI stuff ?

### ISSUE THREAD

**Issue by ShawnOceanHu** [facebook/react-native#608]
Hi guys, I'm thinking building the UI with famo.us -- which is awesome, and combining the power of react-native -- which is also awesome : ), so if I don't use the native UI stuff, can I use react-native for Android now ? What native modules does it currently have ? How do I integrate with famo.us ? Curious ~

**Comment by brentvatne** [comment]
@ShawnOceanHu - None of the react-native Android project is open source currently, it is still about 6 months off from release. Sorry, there's no way around it, I wish there were!

**Comment by ShawnOceanHu** [comment]
6 months ... that's long ~

closing this ~
