### ISSUE TITLE
Is it possible to mark a library under "node_modules" to be reloadable?

### ISSUE THREAD

**Issue by babyLiyuan** [facebook/react-native#6081]
After disassembling my project into several modules, I create some links between them using" npm ln" (in fact I use the [linklocal](https://github.com/timoxley/linklocal) tools instead, but this is trivial). So that after "npm install", the npm creates the link to their original folder under the _node_modules_.

One troublesome thing here is that in the development, if I modify some code in the linked library source files, the react-native packager could not reload them dynamically. Then I must restart the server manually for every modification. Is there any method to mark some libraries to be reloadable here?

thanks very much!

**Comment by satya164** [comment]
React Native packager uses `watchman`, which doesn't support symbolic links. Consider putting the project under `node_modules` while testing. Related #637
