### ISSUE TITLE
Invariant Violation: Callback with id 55: PhotoManager.getNetImageBase64() not found

### ISSUE THREAD

**Issue by zxyah** [facebook/react-native#6084]
i write a native method for get the network image's base64 value 
in program, i need execute much times
native method is:
`@objc func getNetImageBase64(param: String,callback: RCTResponseSenderBlock) {
    responseCallback = callback;
    Just.get(param) { (r) in
      if (r.ok && r.statusCode == 200) {
        if let _ = r.content {
          self.responseCallback([AppUtil.createSuccessResponseCallback(r.content!.base64EncodedStringWithOptions(.Encoding64CharacterLineLength))]);
        } else {
          self.responseCallback([AppUtil.createFailResponseCallback("content is null")]);
        }
      } else {
        self.responseCallback([AppUtil.createFailResponseCallback("fail, statusCode=\(r.statusCode), message=\(r.error)")]);
      }
    }
  }`

javascript code is:
`PhotoManager.getNetImageBase64('http://image.com/image', ((rr) => {console.log(rr);}));
                    PhotoManager.getNetImageBase64('http://image.com/image', ((rr) => {console.log(rr);}));
                    PhotoManager.getNetImageBase64('http://image.com/image', ((rr) => {console.log(rr);}));`

in chrome debug console, it tell me error:
`Invariant Violation: Callback with id 55: PhotoManager.getNetImageBase64() not found`
i have execute the method three times, but it only execute one time, and has the error
for test, in native code, i callback direct, not in the image request callback, it's ok
why?

**Comment by browniefed** [comment]
@facebook-github-bot stack-overflow
