### ISSUE TITLE
Following 'getting started' on react native 0.20, unmodified app crashes on first run

### ISSUE THREAD

**Issue by refugeefromflashland** [facebook/react-native#6085]
Following the https://facebook.github.io/react-native/docs/getting-started.html#content:

Creating and initing the app (with '$ npm install -g react-native-cli' , then '$ react-native init Canine) seems to work fine.

But then opening the unmodified app in xcode and running results in red screen (see attached screenshot and xcode log).

Same error happens when building it from commandline (with 'react-native run-android').

Last time I started a new app (then using 0.17), this crash did not happen.

Node version is 5.3.0, xcode version is 7.2

![simulator screen shot 22 feb 2016 14 17 13](https://cloud.githubusercontent.com/assets/17407768/13219277/456c58a2-d96f-11e5-9eba-b75db39481fb.png)
[xcodelog.txt](https://github.com/facebook/react-native/files/140631/xcodelog.txt)

**Comment by Kureev** [comment]
Funny, but I have a different one:
![image](https://cloud.githubusercontent.com/assets/2273613/13219478/92fd012e-d970-11e5-85f6-98c8ace92899.png)

**Comment by Kureev** [comment]
Have you tried to upgrade your native part? Try to run
```
$ react-native upgrade
```

**Comment by refugeefromflashland** [comment]
Tried that, get same error.

**Comment by Kureev** [comment]
Have you tried to reset a packager cache after upgrade?
```
$ ./node_modules/react-native/packager/packager.sh start --reset-cache
```

**Comment by refugeefromflashland** [comment]
That seems to have done the trick, app now shows the default 'welcome...' index,js just as it should! Thanks!

**Comment by Kureev** [comment]
You're always welcome :+1:
