### ISSUE TITLE
[0.21] Commits to cherry-pick into 0.21-stable

### ISSUE THREAD

**Issue by bestander** [facebook/react-native#6087]
- [ ] 78a9125 Update `ScrollResponder.js` to use new `scrollTo` API. This fixes a warning in the current release version.
- [ ] ecf6981093f7f9afe4a462eee9e7af864c6d9e70 Only freeze valid attributes in `mountComponent`
- [ ] Disable HMR menu option on Android, not ready for prime time just yet: https://github.com/facebook/react-native/commit/f5144094955a0099d57bf3ad1439a376f46bce48

**Comment by bestander** [comment]
@mkonicek, should we make more changes to cli upgrade command?
It seems that Gradle still downloads react-native 0.20.1 from Maven.
We need to link gradle to the .jar in node_modules.

**Comment by janicduplessis** [comment]
78a9125 Update `ScrollResponder.js` to use new `scrollTo` API. This fixes a warning in the current release version.

**Comment by mkonicek** [comment]
:+1: Thanks @janicduplessis!

@bestander I created a new app using 0.21.0-rc. `react-native init` still uses 0.20.0 because that's marked as latest in [npm](https://www.npmjs.com/package/react-native).

In package.json, I changed the RN dependency to 0.21.0-rc, `rm -rf node_modules`, `npm install`.

Ran:

    $ cd android
    $ ./gradlew app:dependencies
    ...    
    com.facebook.react:react-native:+ -> 0.21.0
    ...

Just to double check, I did `rm -rf ~/.gradle/cache` and ran:

    `react-native run-android`

Saw the POM file is still downloaded (this is indeed surprising, good catch!):

    Download https://jcenter.bintray.com/com/facebook/react/react-native/0.20.1/react-native-0.20.1.pom
    ...
    Download https://jcenter.bintray.com/com/facebook/fresco/imagepipeline-okhttp/0.8.1/imagepipeline-okhttp-0.8.1.aar

But the .aar file wasn't downloaded.

**Comment by jsierles** [comment]
If #5084 is ready in the next day or so, it would be great to get it in, so Relay can be used out of the box with React Native!

**Comment by lostintangent** [comment]
It would be awesome if #6119 could be considered as well, since this has been a source of confusion for a lot of users.

**Comment by Kureev** [comment]
Also looking forward for #5084

**Comment by mkonicek** [comment]
Hey guys, I'm looking forward to #5084 landing as well. David Aurelio is working hard to merge it into the fb codebase. Our internal setup makes it not trivial to merge unfortunately.

@lostintangent The cherry-picks are intended for small and completely safe bug-fixes. #6119 looks great but by looking at the code I can't tell with 100% confidence it won't break anything for anyone so prefer to release it in 0.22.0-rc next week and let people test it for 2 weeks before shipping it in 0.22.

**Comment by matthewwithanm** [comment]
Could you please grab ecf6981093f7f9afe4a462eee9e7af864c6d9e70? It's kind of a follow-up to bb3d8d535000ad78a95776f2de9282130f80d0bd (which I think is already in).

**Comment by mkonicek** [comment]
@spicyj Should we cherry-pick https://github.com/facebook/react-native/commit/ecf6981093f7f9afe4a462eee9e7af864c6d9e70 into the release? https://github.com/facebook/react-native/commit/bb3d8d535000ad78a95776f2de9282130f80d0bd is in, not sure if it makes sense without the followup commit?

**Comment by spicyj** [comment]
The latter stands alone as an improvement, but the former is a bug fix that we could include. I am fine either way.

**Comment by lostintangent** [comment]
@mkonicek Makes sense, I just thought I would ask :) Thanks!

**Comment by matthewwithanm** [comment]
ecf6981093f7f9afe4a462eee9e7af864c6d9e70 is needed to avoid an error in Nuclide debugging so I would *really* appreciate it!
