### ISSUE TITLE
[Question] Is it possible to roll in Safari View controller bridges into react-native module itself instead of having apps to implement their own or use a module on npm?

### ISSUE THREAD

**Issue by pvenkatakrishnan** [facebook/react-native#6091]
Currently we have our own bridge implementation for ios to launch Safari view controller from a react-native app. Wondering if I can PR it back into react-native module or was there a specific thought around not doing this in the first place.
Thanks.

**Comment by satya164** [comment]
Feel free to publish it as a separate npm module.
