### ISSUE TITLE
[iOS] [Linking] Linking.getInitialURL() doesn't work for universal links

### ISSUE THREAD

**Issue by daesan** [facebook/react-native#6099]
When an iOS RN app is launched by clicking an universal link, there is no way to retrieve the url from JS land. Linking.getInitialURL() works only for custom URL schemes and Linking.addEventListener() doesn't work for the initial launch.

**Comment by javache** [comment]
Correct. The custom URL scheme API and Universal Links API use very different entry points. We'd need to support Handoff in our AppDelegate (https://developer.apple.com/library/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html), but abstracting away that difference in Linking would be great.

**Comment by daesan** [comment]
@javache I have tried to update launchOptions on rootView.bridge from AppDelegate. However, launchOptions turns out to be a readonly property.

Simple solution could be to change launchOptions property to read/write. Do you think that's a possible approach?

**Comment by javache** [comment]
Actually, it looks like someone already added support for Universal Links in https://github.com/facebook/react-native/commit/f4c286f7ac0665edc3027e952d3b445703918c9c. Could you see if that works for you?

**Comment by daesan** [comment]
The commit you referred adds a support for Linking.addEventListener for Universal Links. The problem is that when the app being launched from Universal Link and "application:continueUserActivity:restorationHandler:" is being called, javascript land is not yet loaded and the call gets ignored. (Linking.addEventListener() has not been executed by then.)

That's why there is "Linking.getInitialURL()". When the app is being launched, it needs to check whether the app is being launched by url link and process it accordingly. However, Linking.getInitialURL() depends on launchOptions which only supports custom URL schemes.

**Comment by javache** [comment]
I think this will always be a race-condition of some sort, so mutating _launchOptions is not going to help. Would it be possible to guarantee the internal event listener in Linking is setup before the event is dispatched? Inside that JS module, we could also store it until listeners are registered?

**Comment by daesan** [comment]
> Would it be possible to guarantee the internal event listener in Linking is setup before the event is dispatched?

I don't think so. Event dispatch happens in AppDelegate and I would think it happens as soon as the app is launched. Event listener is set up in "Linking/Linking.js". I presume that since Javascript code is executed asynchronously, there is no way that the event listener is set up before the event is dispatched.

> Inside that JS module, we could also store it until listeners are registered?

"RCTLinkingManager.application:continueUserActivity:restorationHandler:" uses "NSNotificationCenter". However, it seems that message delivery in NSNotificationCenter happens synchronously. Do you think it is possible to use some sort of queue so that message delivery can hold if no listener for such messages is registered?

**Comment by daesan** [comment]
I looked into launchOptions in AppDelegate and realized that URL parameter for Universal Links is available under different key than custom URL scheme. I made a change to Linking.getInitialURL() so that it works for both custom URL scheme and Universal Links. Could you review it if I make a PR?

**Comment by javache** [comment]
Sure, go for it.
