### ISSUE TITLE
Packager should not launch editor if non-interactive

### ISSUE THREAD

**Issue by pesterhazy** [facebook/react-native#6103]
By default the react-native packager launches an interactive editor (like vim) when you click on one of the stack trace lines in the Red Screen. This breaks non-interactive use.

Let me explain. In `boot-react-native`, a tool that continuously transpiles ClojureScript to react-native-ready javascript, we run the react-native packager non-interactively in the background. When an editor is launched, this leads to a scrambled screen: https://github.com/mjmeintjes/boot-react-native/issues/38

I'd argue that calling (and guessing!) an interactive editor is unusual and surprising default behavior. The best solution would be to make this behavior opt-in.

Another possibility would be to provide a command line switch to disable launching editors. Similarly, the packager could check if a `tty` is present before attempting to launch interactive programs.

**Comment by ThaJay** [comment]
+1 on: 
> The best solution would be to make this behavior opt-in.

**Comment by lacker** [comment]
I found this somewhat annoying when I wasn't using Nuclide, but invaluable that it worked without me configuring anything when I was using Nuclide. @mkonicek had some ideas for improving the `react-native` CLI, Martin I wonder what do you think about this? Maybe we could just make it work when you already have a visual editor open?

**Comment by lacker** [comment]
I think people like this behavior, but it would still be a good idea to make it not happen if you were running the packager non-interactively. Are you interested in sending a pull request to make this work?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/packager-should-not-launch-editor-if-non-interactive
