### ISSUE TITLE
create project on Window

### ISSUE THREAD

**Issue by navihr** [facebook/react-native#6108]
i.m using windows
->react-native init AutobotProject
This will walk you through creating a new React Native project in C:\Users\Navi\AutobotProject
Installing react-native package from npm...
this on the screen more than few hours not respond 

my project file create only one package.json file
 after few hours display this error
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0

npm ERR! shasum check failed for C:\Users\Navi\AppData\Local\Temp\npm-4148-016236de\registry.npmjs.org\rebound\-\rebound-0.0.13.tgz
npm ERR! Expected: 4a225254caf7da756797b19c5817bf7a7941fac1
npm ERR! Actual:   073eb296fe00d40a4a8757e9367f104dabfc2e49
npm ERR! From:     https://registry.npmjs.org/rebound/-/rebound-0.0.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Navi\AutobotProject\npm-debug.log

`npm install --save react-native` failed

what i do pls help....

**Comment by maluramichael** [comment]
Try to use an other version of node (e.g. 5.6.0) and npm.

**Comment by navihr** [comment]
thanks...
change my  node version 4.-.-LTS
before a hour start-->
react-native init AutobotProject
This will walk you through creating a new React Native project in C:\Users\Navi\Desktop\AutobotProject
Installing react-native package from npm...

but now create package.json and node-module others not created.
 please help.

**Comment by Proyoyo** [comment]
Are you saying that the package.json didn't get initialized by "react-native init" command?

**Comment by navihr** [comment]
now created...

**Comment by navihr** [comment]
thank u guys..

**Comment by dsibiski** [comment]
Closing as it seems the original issue is now fixed.

**Comment by geakw** [comment]
Hi,guys,how did it solved? i meet it too
os : windows 7 64 bit
nodejs:v5.10.1
