### ISSUE TITLE
Image scaling when only width is provided results in unexpected heights

### ISSUE THREAD

**Issue by mosesoak** [facebook/react-native#6112]
Related to https://github.com/facebook/react-native/pull/1538.

Currently when using a static image (`require('./image.png')`) and passing a width only in the style, the image scales to a height that doesn't quite make sense:

Static Image `(@2x): 750 x 424` = 1.7688679245 aspect ratio

iPhone 6: passing `width:375` results in **`height:212`** = 1.7688679245 - we published the image for this resolution so the aspect ratio is correct here.

iPhone 5: passing `width:320` results in **`height:212`** = 1.5094339623 
- **Height seems to have been left unchanged.**
- Aspect ratio has been altered. Left/right of image are cropped

iPhone 6 Plus: passing `width:621` results in **`height:320`** = 1.940625
- **Height has been recalculated & changed, but it's unclear how**
- Aspect ratio has been altered. Top/bottom of image are cropped

As a developer, my expectation or hope is that regardless of `resizeMode`, I should be able to pass only a width on an image – or use a container that clearly defines a bounding width without defining a bounding height – and the image frame should automatically scale to the image's aspect ratio. That's the simplest way to build for multiple device sizes, since you often only know what width you want and that you want to show the whole image, and are happy to allow content below to flow normally below the image. 

In fact, react-native _does_ seem to be trying to do this to some degree, it just seems to be making some weird calculations.

A few related thoughts:

IMO adding a new `resizeMode` is probably going too far since it's easier to just omit height and let the image scale on its own. The current resizeModes are adequate for defining image resizing when both width & height are specified, whereas when a developer defines only a width and not a height it's a clear indication that they are hoping the image frame will adjust itself accordingly.

Hopefully I'm not glossing over a big issue with remote images, my thought is that it could potentially work the same way in the width-only case once image data is available. (Perhaps the placeholder image or surrounding container can be swapped out with a width-only version after download, using a ternary statement in the render method after `onLoad`.)

In general, if only width is specified and the unexplained calculations listed above were normalized to fall back on aspect ratio, that would be a great help in building apps for multiple screen sizes. Thanks in advance for the opportunity to discuss this issue!

**Comment by sahrens** [comment]
@davidaurelio , @frantic - who owns static bundle images these days?

**Comment by frantic** [comment]
Hey @mosesoak! A few things you can do to debug the issue (please attach the output of the command below):

from Terminal (assuming inside the folder with the image):
```
$ sips -g pixelHeight -g pixelWidth image*.png
```

from RN app (for iPhone 5 and 6+):
```
require('resolveAssetSource')(require('./image.png'))
```

**Comment by davidaurelio** [comment]
@sahrens Do you think this is related to metadata extraction?

**Comment by sahrens** [comment]
Not sure. Who owns the system e2e?


On Apr 6, 2016, at 8:01 AM, David Aurelio <notifications@github.com<mailto:notifications@github.com>> wrote:


@sahrens<https://github.com/sahrens> Do you think this is related to metadata extraction?

**Comment by davidaurelio** [comment]
I don’t think there’s an owner atm

**Comment by lacker** [comment]
Hey, since this has remained quiescent for a while I am going to close this issue. I think a useful way to make progress would be to run those commands that sahrens suggested above, so if you have that and we can make a bit of progress here then feel free to reopen this issue.
