### ISSUE TITLE
[Andorid] [Image] some .jpg images not showing

### ISSUE THREAD

**Issue by daiying-zhang** [facebook/react-native#6116]
when i use <Image /> load a network image with ext .jpg. some image can show currently，some others can not. and the 'onLoad' callback will not be invoked.

**Comment by Kureev** [comment]
Hi @daiying-zhang, can you please provide us a way to reproduce this issue on a blank project?

I have a question for you. Did you see the [New Issue Guidelines](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) when creating this issue? Is there anything we could improve there? Is the text too long or unclear for example?
