### ISSUE TITLE
How to get a component in React Native

### ISSUE THREAD

**Issue by khanghoang** [facebook/react-native#612]
Hi there,

I wonder is there a way to get component like React's **refs**
Because in my case, i have implemented the side menu like what iOS has, now i wanna make some functions like **SideMenu.toggle()** that can be called at any places in my app but I don't know how to get the **SideMenu** component.

**Comment by vjeux** [comment]
React refs should be working like in React (React Native uses the latest version of React). Isn't it working for you?

**Comment by khanghoang** [comment]
Let me illustrate to make it simple.
```javascript

var App = React.createClass({
  render: function () {
    return (
      <View style={styles.container} >
        <SideMenu 
        ref={"sideMenu"} 
        frontView={<FrontView />} 
        sideView={<SideView />} />
      </View>
    );
  }
})
```
Then how can I expose the **sideMenu** instance that I can you at any places of the app.

**Comment by checkraiser** [comment]
Ref is used to reference child component.
So if your SideMenu is used as a child component, it can be accessed by parent by ref.

**Comment by khanghoang** [comment]
@checkraiser then can i expose **SideMenu** from its parent? 

```javascript
AppRegistry.registerComponent('SideMenu', () => App);
```

And how can I get the the App instance?

**Comment by checkraiser** [comment]
As far as i know, you don't need to register child component. You just need to require('SideMenu') to use it.
Read more about here: https://facebook.github.io/react/docs/more-about-refs.html

**Comment by khanghoang** [comment]
@Kureev, @checkraiser thanks for quick answers. 
@Kureev ya, i tried it
```javascript
var SideMenu = <SideMenu .../>;
```
 but i can't see the its functions.

Here is my code https://github.com/khanghoang/RNSideMenu/blob/master/index.ios.js#L47-L58
I wanna make the **SideMenu** as global variable so I can call its function (sth like **SideMenu.toggle()**) at any places. But when I tried to debug it, I can't see its functions :sob: 

FYI here is the implementation of SideMenu https://github.com/khanghoang/RNSideMenu/blob/master/SideMenu.js

**Comment by joewood** [comment]
Hi Khang - I think you should look at modeling the toggle state through a property.

The Switch component is similar, in that events are hooked up and the component is re-rendered with new properties. 

https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/Components/SwitchIOS/SwitchIOS.ios.js


The SlideMenu’s state would therefore be held at a higher level. Updating this state is how you explicitly toggle the menu.

 






From: Khang Hoang Trieu
Sent: ‎Thursday‎, ‎April‎ ‎2‎, ‎2015 ‎11‎:‎15‎ ‎AM
To: facebook/react-native





@Kureev, @checkraiser thanks for quick answers. 
@Kureev ya, i tried it

var SideMenu = <SideMenu .../>;

but i can't see the its functions.

Here is my code https://github.com/khanghoang/RNSideMenu/blob/master/index.ios.js#L47-L58
I wanna make the SideMenu as global variable so I can call its function (sth like SideMenu.toggle()) at any places. But when I tried to debug it, I can't see its functions  :sob: 

FYI here is the implementation of SideMenu https://github.com/khanghoang/RNSideMenu/blob/master/SideMenu.js

**Comment by khanghoang** [comment]
@joewood you're right about using the state. But in my case, i think it is little bit different, the child view of the SideMenu may have a button to change the state of SideMenu, so how can we update the parent's state when we're in the child? And in the real case the child view maybe at the very deep of the hierarchy.

**Comment by Kureev** [comment]
@khanghoang the best way to solve it in your case - use `context`, but it hasn't been introduced yet.

**Comment by joewood** [comment]
@khanghoang you should always look to move your state management to a higher level.  So the state of your container will decide if the slider is open or not.  If you have a button on your slidemenu that toggles the state open/close state, you simply expose clicking of that toggle button as a property.  You can then propagate that property event up through the component hierarchy to where the state is, and call `setState` on the parent container.  This will in turn will cause a render, which will render the sideView and frontView with new properties reflecting that state.

If you want to animate your children of the container, you use keys on the child elements.

I hope that helps.

**Comment by khanghoang** [comment]
@Kureev @joewood & @checkraiser thanks guys, I think I get it. :beers:
