### ISSUE TITLE
Push CocoaPods podspec on releases?

### ISSUE THREAD

**Issue by alloy** [facebook/react-native#6125]
I’m wondering if you could automatically push out podspecs when you release new versions?

The reason I’d like to use it is because I’m integrating RN into an existing iOS application, thus I want the existing workflow (`pod install`) to be able to automatically include the RN version that my component depends on.

**Comment by grabbou** [comment]
React (and other modules from the ecosystem) ship with local podspecs you could potentially use like below:
```ruby
pod 'React', :subspecs => [
    'ART',
    'RCTImage',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTPushNotification',
    'RCTSettings',
    'RCTVibration',
    'RCTText',
    'RCTWebSocket'
  ], :path => '../../node_modules/react-native'
```
I think that should do the trick?

**Comment by alloy** [comment]
The point for my situation is that that expects a project to adopt the `npm install` workflow, which is not something I want to do just yet. I’d like to integrate it into the existing workflow, which is to `pod install`.

**Comment by grabbou** [comment]
That was the motivation behind removing it: https://github.com/facebook/react-native/issues/4682#issuecomment-163368310

**Comment by hfossli** [comment]
What if I want to create a pod which uses react native? And other pods/3rd-party projects may also depend on react. Shouldn't that be supported?

**Comment by grabbou** [comment]
> What if I want to create a pod which uses react native?

What would be the particular use-case for that?

**Comment by alloy** [comment]
That is actually what I’m doing. I’m pulling a new component that happens to be backed by React Native into an existing app.

For now I just have a forked podspec in our own spec repo for the latest RN version.

**Comment by oblador** [comment]
@alloy: Not sure how you're supposed to build a RN app without using `npm` dependencies. The local podspec has the upside of it being very easy to use RN from master or your own fork. Don't believe there's a problem defining `React` as a dependency in third party modules (I'm doing it) but it wont be fetched automatically for obvious reasons, think of it as a `devDependency` – you have to first include it in your main `Podfile`.

**Comment by hfossli** [comment]
@grabbou We don't have one monolithic codebase. Our apps consists of several projects each with their own responsibility. One of these projects is responsible for drawing various content from our content providers – this is the one that we would like to have a dependency to RN. We are creating many apps using this codebase. All those apps have dependencies to our various libraries. My guess is that this setup using npm is in favor for those who are creating apps entirely in RN. We are sort of just seasoning our app with RN. :)

**Comment by alloy** [comment]
You wouldn’t, it’s just that `npm install` etc would be called (under the hood) from the existing pod workflow.

Anyways, I’ve concluded that this inherently remains inelegant, no matter what workflow you prefer. So I’m more on the fence about this all. I do think that if you would prefer to not distribute a podspec to the central spec repo, you should deprecate the pod there so that people are not simply installing older RN versions without _any_ indication that it’s out-of-date.

**Comment by oblador** [comment]
@alloy: Agreed that it's not ideal! But removing it would break existing installations and according to cocoapods stats, they have 20K downloads/month to 1,513 apps. Last version released there was 0.13-rc so not sure how many are really still stuck with that and if the numbers lie. 

Can you maybe try to do `npm install` in `pre_install`?

**Comment by alloy** [comment]
Deprecating a pod does not remove it and should not break existing installations. It’s meant as a signal, after which people will probably be more inclined to research why it has been deprecated and how they _should_ be using it?

> Can you maybe try to do `npm install` in `pre_install`?

That is the kind of thing that I am currently doing to integrate it into our existing workflow.

**Comment by oblador** [comment]
@alloy: Yeah, in that case it should be deprecated. :+1: 

Will CocoaPods try to resolve dependencies prior to running `pre_install`?

**Comment by alloy** [comment]
> Will CocoaPods try to resolve dependencies prior to running `pre_install`?

Yup: https://guides.cocoapods.org/syntax/podfile.html#pre_install

The way to do something before anything else is to just do it from the top-level of the Podfile, i.e. as it is evaluated.

**Comment by ide** [comment]
Could we commit `spec.deprecated = true` straight to the podspec repo somehow? We want to deprecate an existing version without publishing a new one.

**Comment by orta** [comment]
If you run `pod trunk deprecate react` on a CocoaPods 1.0 beta it should propagate through the system

**Comment by alloy** [comment]
@orta Ace, thanks :+1:

**Comment by ide** [comment]
I got a generic error message but can try again later: 

```sh
$ pod --version
1.0.0.beta.6

$ pod trunk deprecate React
[!] An unexpected error ocurred: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by alloy** [comment]
@ide Can you try again with the released v1 version?

**Comment by alloy** [comment]
With regards to this original ticket, for our workflow I settled on:

* Building the React Native views in [a separate repo](http://github.com/artsy/emission), where I do all the NPM work as well.
* Then I build [a release JS bundle](https://github.com/artsy/emission/blob/master/Pod/Assets/Emission.jsbundle) and store that in the Pod’s assets.
* Then in our app I use CocoaPods like so:

```ruby
pod 'React', :git => 'https://github.com/facebook/react-native.git'
pod 'Emission', :git => 'https://github.com/artsy/emission.git'
```

This means that for my colleagues, working on the app _outside_ of RN, they do not need to know anything about NPM or deal with it, it all just works transparently with `pod install` as they were used to.

So I’m considering this one settled for me.

**Comment by ide** [comment]
I get a 404 page when running `pod trunk deprecate React`. The CocoaPods CLI receives the HTML for the 404 page and doesn't know what to do with it.

One small change I would suggest is to add `:tag => 0.26.2` to your Podfile so that the consistency of `pod install` is less dependent on Podfile.lock.

**Comment by orta** [comment]
It was the redirect that failed, it was deprecate back in March 15, t's deprecated - see https://cocoapods.org/pods/React ( issue https://github.com/CocoaPods/trunk.cocoapods.org/issues/168 )

**Comment by alloy** [comment]
Thanks for checking, @orta.

> One small change I would suggest is to add `:tag => 0.26.2` to your Podfile so that the consistency of `pod install` is less dependent on Podfile.lock.

@ide ah yeah, totes. Thanks, updated my example 👍

**Comment by alloy** [comment]
FYI Here’s an article that describes how we integrate RN into our existing app without changing the workflow (CocoaPods) of that app http://artsy.github.io/blog/2016/08/24/On-Emission/

**Comment by alloy** [comment]
@ide I’d also like to ask you to reconsider the choice to not push to the central CP registry. I currently push to our registry, I know SoundCloud’s situation is similar, and I’m sure there are others. (As said before, I would gladly offer my time to do the maintenance work.)
