### ISSUE TITLE
[AsyncStorage] multiGet/multiSet should return/receive object(hash map) instead of array.

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#6127]
For me it is weird to iterate over response to get values. It just much more convenient to work with an object.

instead of
```multiGet(['k1', 'k2'], cb) -> cb([['k1', 'val1'], ['k2', 'val2']])```
I want 
```multiGet(['k1', 'k2'], cb) -> cb({'k1': 'val1', 'k2': 'val2'})```

**Comment by skv-headless** [comment]
Actually I can work on this. So I just need approval

**Comment by sahrens** [comment]
There are pros and cons of each and I don't see a compelling reason to change. This would break a lot of apps and I don't think it's worth bloating the API to support this as an option. I'd recommend just making and using a little utility that zips the array up into an object if that's easier for you to work with. Any reason that won't work for you? If so, feel free to re-open with a thorough argument.
