### ISSUE TITLE
Expose WebSocket protocol getter attribute on iOS

### ISSUE THREAD

**Issue by mikemintz** [facebook/react-native#6137]
On iOS, the code seems to correctly take care of negotiating the protocol with the WebSocket server, but it doesn't expose the resulting protocol in the [`protocol` attribute of the WebSocket instance](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). The attribute is [declared in WebSocketBase.js](https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/WebSocketBase.js#L38) but doesn't seem to be populated after the protocol is negotiated in [RCTSRWebSocket.m](https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/RCTSRWebSocket.m#L439).

(This is similar to https://github.com/facebook/react-native/issues/5810, where Android is missing support for setting the `Sec-WebSocket-Protocol` for WebSocket connections.)

**Comment by zxcpoiu** [comment]
I have the same issue

**Comment by ianlin** [comment]
#6223

**Comment by zxcpoiu** [comment]
oh no, sorry, I must closed this issue via android commit, should be reopen.

I hate @ian

**Comment by ian** [comment]
Sorry :/

**Comment by zxcpoiu** [comment]
@ian all my bad 👎

**Comment by ianlin** [comment]
Ah should be me - mis-reference this issue to @zxcpoiu's commit 6223.

Sorry!

**Comment by ian** [comment]
Just playin around :)

Thanks for all the work on react-native.  Awesome project.

**Comment by lacker** [comment]
Looks like this is fixed by the referenced PR so I am going to close this issue.
