### ISSUE TITLE
[Text] How to replace text string with text component?

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#614]
Kindof trying to build a syntax highlighting for react-native. I want to replace certain matches with text components to highlight.

eg:
```
<Text style={styles.syntax}>
     {this.props.text.replace(/this/, <Text style={styles.green}>this</Text>)}
</Text>
```

I'm trying to replace this with highlighted this in the above example but doesn't seem to work.

**Comment by vjeux** [comment]
The problem here is that replace is going to convert <Text /> into a string and not do what you want. If the input string is `'var a = this.a;'`, you want to end up with `['var a = ', <Text />, '.a;']`.

I don't think there is any default method to cleanly do it so you'll probably have to use a for loop and build the array yourself.

**Comment by chirag04** [comment]
@sahrens  As per my discussion with @vjeux  It seems you have done something similar in groups app.

Just to explain the use case: we have text strings like "Welcome to <g>Lrn</g>!" and want to highlight Lrn with green. <g> for green. We have <r><b> etc for red, blue.

Right now there is no easy way to do it at run time. So as a workaround we wrote a template system that does the nesting and outputs the nested code.

Happy to change the input format if we can have a better api/idea.

**Comment by chirag04** [comment]
@sahrens ping :)

**Comment by sahrens** [comment]
Hmm, I haven't done this directly, I was more focused on getting our current text styling system working in an editable text input.

What's the problem with parsing the raw text and building a tree of react components?

**Comment by chirag04** [comment]
Ok. I just wanted to see if there is a way to improve the text api for nested text tags.

parsing is def one way to doing it. Not sure if performance will be a problem as we din't test parsing yet. We have a basic implementation of parsing and building the tree like one below.

```
//map of tag - style class to apply. blue is a style obj here { color: 'blue' };
var lookup = {
  'b': 'blue',
  'p': 'purple',
  'g': 'green',
  'r': 'red',
};

function highlight(text) {
  // split on highlight tags to get the arrays.
  text = text.split(/(<.*?>.*?<\/.*?>)/g);

  // odd indexes in array will be tags to be replaced with text tag.
  for(var i = 1; i < text.length; i += 2) {
    
    // extract the text string to highlight.
    var word = text[i].replace(/<.*?>(.*?)<\/.*?>/, '$1');

    //apply the style and return the text tag.
    text[i] = <Text style={styles[lookup[text[i][1]]]}>{word}</Text>;

  }
  return text;
}
```

Just throwing it out there for anyone else looking to do run-time highlight.  Let know if we can improve anything here.

**Comment by brentvatne** [comment]
Thanks for the detailed follow up @chirag04 :rainbow: :tada: :star:

**Comment by sahrens** [comment]
Yeah that's reasonable. The only thing I might suggest is to use some
standard template lib (markdown or html?) instead of your own, but if
that's working for you it seems fine.
