### ISSUE TITLE
URLSearchWithParams

### ISSUE THREAD

**Issue by niftylettuce** [facebook/react-native#6141]
Can we get URLSearchWithParams integrated into RN implementation of `fetch` by default?

Per <https://github.com/github/fetch/issues/167> and <https://github.com/Jxck/URLSearchParams>.

This would allow us to use querystring params in the body of our HTTP request with `fetch`.

For instance (`googleapi` is an instance of [Frisbee](https://github.com/niftylettuce/frisbee) with `baseURI` set to Google's API URI)):

```js
let params = new URLSearchParams();
        params.append('key', 'foobar');
        params.append('language', 'en');
        params.append('location', [
          coords.latitude,
          coords.longitude
        ].join(','));
        params.append('radius', 500);
        googleapi.get(
          '/maps/api/place/nearbysearch/json',
          { body: params }, // <--------------- body is set to URLSearchWithParams instance
          (err, res, message) => {
            console.log('googleapi', 'err', err,
                        'res', res, 'message', message);
          }
        );
```

**Comment by niftylettuce** [comment]
The alternative we have right now is to do the following:

```js
        import querystring from 'querystring';

        let params = querystring.stringify({ key: 'foobar', language: 'en' }); // etc.

        googleapi.get(
          '/maps/api/place/nearbysearch/json?' + params, // <-- set in the URI
          (err, res, message) => {
            console.log('googleapi', 'err', err,
                        'res', res, 'message', message);
          }
        );

**Comment by dsibiski** [comment]
Since we are basing our Fetch implementation off of Github's (direct copy/paste - https://github.com/facebook/react-native/issues/1162#issuecomment-99681477), I think we'd only add something like this once GitHub uses it in the original lib. Perhaps @brentvatne or @vjeux have some thoughts about that.

I'll close this now, we can reopen if someone on the core team decides that forking away from the base Fetch is something we want to do.

**Comment by vjeux** [comment]
Everything we add by default is going to slow down startup path, take more memory, increase the bundle size... The standard to add new things is pretty high.

If this gets big traction in the community and solves a problem that people have, we can consider it. However, from the look of it, it looks a bit early: the polyfill docs says "WIP" and has only 6 stars.

Happy to reconsider it in a few months :)
