### ISSUE TITLE
[Android] TextInput placeholder font family is incorrect when secureTextEntry={true}

### ISSUE THREAD

**Issue by gaykov** [facebook/react-native#6149]
RN 20.0 (Android only)

When I use `secureTextEntry={true}` for TextInput, the font-family for placeholder is always default:

![input-bug](https://cloud.githubusercontent.com/assets/9068073/13320261/b5fd3788-dbd8-11e5-9e0b-3cb19eb7a20b.png)

**Comment by lynndylanhurley** [comment]
I'm seeing the same issue.

**Comment by eric1iu** [comment]
got the same issue.

**Comment by Raz0rwire** [comment]
I also have the same issue

**Comment by mmazzarolo** [comment]
Same issue on all Android versions I tested

**Comment by Raz0rwire** [comment]
I did find this:

> Tip: By default, when you set an EditText element to use the "textPassword" input type, the font family is set to monospace, so you should change its font family to "sans-serif" so that both text fields use a matching font style.

Here: http://developer.android.com/guide/topics/ui/dialogs.html#CustomLayout but I'm not sure how to go about fixing it.. @christopherdro

**Comment by danhawkes** [comment]
@Raz0rwire In native android the default behaviour is as you describe, but setting the font family works to override the default. What seems to be happening here is that the override is not being applied.

**Comment by christopherdro** [comment]
Related: https://github.com/facebook/react-native/issues/4435

**Comment by charpeni** [comment]
It will be fixed by PR #6564.

**Comment by charpeni** [comment]
@facebook-github-bot close
