### ISSUE TITLE
After upgrade 0.18 to 0.20.0 the same code run freeze in iOS

### ISSUE THREAD

**Issue by Arnold134777** [facebook/react-native#6158]
After upgrade 0.18 to 0.20.0 the same code run freeze in iOS,init code as follow:

```objc
 NSURL *jsCodeLocation;
    jsCodeLocation = [NSURL URLWithString:APP_Config.rnBundlePath];
    RCTBridge *bridge = [[RCTBridge alloc] initWithBundleURL:jsCodeLocation
                                              moduleProvider:nil
                                               launchOptions:launchOptions];
    
    APP_Context.bridge = bridge;// APP_Config and APP_Context is global variable
```

freeze code as follow:

```
void RCTExecuteOnMainThread(dispatch_block_t block, BOOL sync)
{
  if ([NSThread isMainThread]) {
    block();
  } else if (sync) {
    dispatch_sync(dispatch_get_main_queue(), ^{ // get freeze here
      block();
    });
  } else {
    dispatch_async(dispatch_get_main_queue(), ^{
      block();
    });
  }
}
```

I compare the different code between 0.18 and 0.20，i change `RCTBatchedBridge.m` 

```objc
 dispatch_group_notify(initModulesAndLoadSource, dispatch_get_main_queue(), ^{
    RCTBatchedBridge *strongSelf = weakSelf;
    if (sourceCode && strongSelf.loading) {
            [strongSelf executeSourceCode:sourceCode];
    }
  });
```

to 

```objc
 dispatch_group_notify(initModulesAndLoadSource, dispatch_get_main_queue(), ^{
    RCTBatchedBridge *strongSelf = weakSelf;
    if (sourceCode && strongSelf.loading) {
        dispatch_async(bridgeQueue, ^{
            [strongSelf executeSourceCode:sourceCode];
        });
    }
  });
```

the freeze disappear.So i don`t know it`s right way to solve the problem,anyone can help solve it? thanks.

**Comment by mroswald** [comment]
initWithBundleURL is deprecated. Maybe we should change the default AppDelegate.m to use initWithDelegate?

**Comment by Arnold134777** [comment]
i have tried, use initWithDelegate is not useful too.

**Comment by oldashes** [comment]
+1 
the same problem

**Comment by breezykermo** [comment]
+1, same error

**Comment by ios122** [comment]
It May Help:
```oc
        /* RN0.20.0版本,存在潜在的死锁问题,此处可修复.主要可能是因为RN未充分考虑到嵌入RN的Native的场景,某个关键函数,使用同步GCD,引起主线程死锁.后续,如果再次死锁,可尝试将延时加大;当RN代码占到一定数量后,可将此处的延迟关闭,以提高效率. */
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.05 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            @strongify(self);
            RCTBridge * bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions: launchOptions];
            
            self.bridge = bridge;
        });
```

**Comment by oldashes** [comment]
@ios122 
hi , could you post some more details?
it may be solved my problem.
thank u.

**Comment by ios122** [comment]
Simple,when App Init,don't creat RCTBridge immediately; I do it,after 0.05 seconds;

**Comment by oldashes** [comment]
@ios122 
i fixed my bug as your idea
it's not the same problem , but thank you all the same.😄

**Comment by Arnold134777** [comment]
@ios122 Lazy load is it right way? How long need to delay,how to judge?  I did same to you before,but i don't think it's the rightest way to solve it.

**Comment by ios122** [comment]
@Arnold134777 @oldashes  up to 0.21.0 It will be OK! It works,but i don't know how!

**Comment by oldashes** [comment]
@ios122 you could read the source code in `RCTModuleData.m` , the `- (void)setBridgeForInstance` has changed.It may help you to know that.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/after-upgrade-018-to-0200-the-same-code-run-freeze-in-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
