### ISSUE TITLE
Upgrade 0.19 to 0.20 error

### ISSUE THREAD

**Issue by pangers** [facebook/react-native#6160]
After upgrading from 0.19 to 0.20, whenever I try to run the app (iOS) I get a red screen error saying: "SyntaxError /Users/MyName/MyProjectName/node_modules/react-native/Libraries/Components/ActivityIndicatorIOS/ActivityIndicatorIOS.ios.js: Unexpected token (35:4)"

Also in the packager window, I'm getting the errors:

```
transforming [============================            ] 69% 478/691[BABEL] Note: The code generator has deoptimised the styling of "/Users/MyName/MyProject/node_modules/immutable/dist/immutable.js" as it exceeds the max of "100KB".
transforming [==============================          ] 76% 526/691[BABEL] Note: The code generator has deoptimised the styling of "/Users/MyName/MyProject/node_modules/moment/moment.js" as it exceeds the max of "100KB".
transforming [===================================     ] 87% 603/691[BABEL] Note: The code generator has deoptimised the styling of "/Users/MyName/MyProject/node_modules/rx/dist/rx.all.js" as it exceeds the max of "100KB".
transforming [===================================     ] 87% 604/691[BABEL] Note: The code generator has deoptimised the styling of "/Users/MyName/MyProject/node_modules/react-native-htmlview/vendor/htmlparser2.js" as it exceeds the max of "100KB".
transforming [===================================     ] 88% 605/691Error while persisting cache: SyntaxError /Users/MyName/MyProject/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js: Unexpected token (38:8)
```

I'm using:
npm - 3.7.3
node - 4.2.3 

Any ideas?

**Comment by arjunkomath** [comment]
@pangers While upgrading, did you run the `react-native upgrade` command to update some of the project files?

**Comment by pangers** [comment]
@arjunkomath Yes I have done that aswell when upgrading to 0.20.

**Comment by Kureev** [comment]
Hi @pangers,

You actually have only 1 error: 
```
transforming [=================================== ] 88% 605/691 Error while persisting cache: SyntaxError /Users/MyName/MyProject/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js: Unexpected token (38:8)
```

I think if you run a packager with `--reset-cache` flag, that would solve your problem:
```
./node_modules/react-native/packager/packager.sh start --reset-cache
```

**Comment by pangers** [comment]
@Kureev,

Thanks for the suggestion, I gave it a try and I still seem to be having the exact same problem with the same error message..Still unable to upgrade as of yet.

**Comment by pangers** [comment]
Solved the issue. I stumbled across this thread http://stackoverflow.com/questions/34112110/upgrade-to-react-native-0-16-error?rq=1

It was because I had my own .babelrc file when in fact 0.20.0, if you specify your own .babelrc file, "React Native does not apply its default Babel configuration in this case". So when I deleted the .babelrc, the problems was solved.
