### ISSUE TITLE
Duplicate haste modules because of npm shrinkwrap

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#6161]
Using RN from master in a project I get duplicate module errors because of npm shrinkwrap. react-native uses fbjs@0.6.0 (even if the dependency is ^0.6.0 the shrinkwrap forces it to 0.6.0) but react@0.14.7 uses fbjs@0.6.1 which lead to duplicate haste modules.

I don't know much about the usefulness of the npm shrinkwrap but should we remove it to avoid these errors or should node haste support multiple versions of the same module? Using a branch without the npm-shrinkwrap.json file fixes the issue.

cc @skevy

**Comment by skevy** [comment]
@janicduplessis we're definitely aware of this issue on master. On the RC, the commits that cause this are backed out.

https://github.com/facebook/node-haste/pull/33/ <-- that PR fixes the issue with the shrinkwrap and node-haste. It's ready to merge...so as soon as it does, master should work again :)

**Comment by janicduplessis** [comment]
@skevy Awesome, I was wondering where was the fix for this :)
