### ISSUE TITLE
i want to know  MapView is supported by Android？

### ISSUE THREAD

**Issue by jiangqqlmj** [facebook/react-native#6162]
i want to know  MapView is supported by Android？
thank you very much~

**Comment by liesislukas** [comment]
Ask questions at stackoverflow.com with tag react-native. There is a mess already with issues here. Github issues are for bug reports not general questions. http://stackoverflow.com/questions/tagged/react-native

**Comment by christopherdro** [comment]
@jiangqqlmj There is no MapView for Android in React Core. However, there is a great third-party module that you should try. https://github.com/lelandrichardson/react-native-maps
