### ISSUE TITLE
Naming Collision issue

### ISSUE THREAD

**Issue by SamTharani** [facebook/react-native#6164]
Hi all
I found a Naming collision issue when I try to run the command npm start
==========================================================================
 Failed to build DependencyGraph: Naming collision detected: /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/fbjs/flow/include/fetch.js collides with /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/react-native/Libraries/Fetch/fetch.js
Error: Naming collision detected: /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/fbjs/flow/include/fetch.js collides with /home/samantha/Projects/prepaid-portal/m1-prepaid-portal-web/node_modules/react-native/Libraries/Fetch/fetch.js
=============================================================================
Can you help me to fixed this one
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Please read the following tips before filing an issue:

Is this something you can debug and fix?
-------------------------------------------------------

Can you see anything in the logs? Can you debug why this happens? **Send a pull request**! Bug fixes and documentation fixes are very welcome.

Have a question or not sure you've found a bug?
-----------------------------------------------------------------
Please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native) with the tag `react-native`. StackOverflow is amazing for Q&A. Because of the reputation system it is likely the community will see and answer your question there.

Make sure you **include a short code snippet to demonstrate the problem**.

Have an idea for a feature?
------------------------------------
Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system that lets us focus on the most important issues the community is experiencing. The higher number of votes the more likely it is a feature will get implemented. You could always implement it yourself, too.

None of the above, want to create a GitHub issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the issue** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- If this is a bug, provide a **minimal code snippet** that reproduces it
- Provide **screenshots** where appropriate
- What's the **version** of React Native you're using?
- Does this occur on iOS, Android or both?
- Are you using Mac, Linux or Windows?

**Comment by grabbou** [comment]
Closing in favour of #5467
