### ISSUE TITLE
Naming collision between react-native and react libs

### ISSUE THREAD

**Issue by fxhereng** [facebook/react-native#6167]
Using RN 0.20, naming collision when I have both react and react-native packages installed:

Doing `react-native start`, I got this:

```
Failed to build DependencyGraph: Naming collision detected: /home/cloud/React-native/Fincaus/node_modules/react-native/node_modules/react/lib/ReactServerBatchingStrategy.js collides with /home/cloud/React-native/Fincaus/node_modules/react/lib/ReactServerBatchingStrategy.js
Error: Naming collision detected: /home/cloud/React-native/Fincaus/node_modules/react-native/node_modules/react/lib/ReactServerBatchingStrategy.js collides with /home/cloud/React-native/Fincaus/node_modules/react/lib/ReactServerBatchingStrategy.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/home/cloud/React-native/Fincaus/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /home/cloud/React-native/Fincaus/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/home/cloud/React-native/Fincaus/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

```

`ReactServerBatchingStrategy.js` seemed to be the problem. If I delele react/ library from project it's working but it's not what I want...

How I could fix this? Maybe installing react apart is not advised? (I installed it for test purposes)

Thanks for helping,

**Comment by Kureev** [comment]
`react-native` ships with `react` under the hood. Can you explain why you need to have a custom react installation?

**Comment by fxhereng** [comment]
I followed this tutorial from https://blog.formidable.com/unit-testing-react-native-with-mocha-and-enzyme-51518f13ba73#.tklnfwpi6 for unit testing which requires to have react to test the components. Do you think it's not mandatory?

**Comment by fxhereng** [comment]
Yes, it's confirmed, the test doesn't work if I don't have the lib 'react' installed.

So my question is : Is there a way of importing react from react-native?

Like: 
```javascript
import React from 'react-native/react'
```

I tried it but it doesn't work.

**Comment by Kureev** [comment]
Got it. To be honest I never tried to use something else than Jest for testing react-native components. But anyway, I don't get why it doesn't catch up you react from the node_modules. Are you sure that version of the react you're installing is compatible with [this one](https://github.com/facebook/react-native/blob/master/package.json#L119-L121)?

**Comment by fxhereng** [comment]
Yes, I tried both actually, but Mocha is faster. It's true it's not the recommended way according to the docs. I'm using this version:

```json
"react": "^0.14.7"
```

I will try to downgrade it

**Comment by grabbou** [comment]
React is now a peerDependency so that issue is likely to be gone when new version is released.
https://github.com/facebook/react-native/blob/master/package.json#L120.

**Comment by fxhereng** [comment]
Thanks for the answer! I'll try it out.

Regards,

**Comment by grabbou** [comment]
No worries,
for some inspirations how to add more folders and stuff, check out default blacklist here https://github.com/facebook/react-native/blob/master/packager/blacklist.js#L15

**Comment by fxhereng** [comment]
Thanks for helping,

Is it supposed to be run itself when packager is starting?

Or Do I need to execute it somewhere?

**Comment by grabbou** [comment]
No, packager will magically pick it (it's an alternative to command line args. You could specify other bits here like root paths etc)
