### ISSUE TITLE
Unexpected token error only when running on device

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#6169]
I have an app working fine on any device in the simulator but when I try to run it on my device I'm getting the error:

2016-02-26 19:54:15.988 [error][tid:main] SyntaxError: Unexpected token ','

Which is weird and doesn't really tell me anything about how to solve the error. I've had no problem with other apps running on this phone. I checked it on the simulator right after and it runs fine. Really strange. Its version 0.19. My phone is running iOS 7.

**Comment by christopherdro** [comment]
@hasen6 Stack track doesn't know which file the unexpected token is coming from?

**Comment by hasen6** [comment]
No the call stack in XCode doesn't show anything. I assume you're referring to the debug navigator in Xcode. I doubt there can be an error in the code since it works absolutely fine every time in the emulator, with every device model.

I also tried another app on my phone through xcode and it worked fine. That was with react native 0.18.1.

**Comment by hasen6** [comment]
This is all that's reported in Xcode:

2016-02-27 11:26:10.350 [trace][tid:com.facebook.React.JavaScript][RCTJSCProfiler.m:63] JSC profiler is not supported.
2016-02-27 11:26:11.039 [error][tid:main] SyntaxError: Unexpected token ','

**Comment by hasen6** [comment]
I found the 'error' by manually removing and adding code until the problem was clear. Its pretty weird. It was two elements passed as props with the same name. One a function and the other a state. Basically:

```
    this.props.navigator.push({
            passProps: {gameover:this.gameover,gameover: this.state.gameover}
        });
```

It worked fine in the emulators but not on my phone. Changing the name of one solved the error.

**Comment by hasen6** [comment]
Don't really think this is solved since it certainly shouldn't be reporting this kind of error. Why is it saying there's an Unexpected token ','??? And then not even saying which file the error is associated with.

Not to mention that the error was only on my phone and not on the simulator at all!

**Comment by Kureev** [comment]
cc @mkonicek

**Comment by chenxsan** [comment]
Same problem here on my device, no stack track. All i have in Xcode is:

```
2016-03-31 10:35:00.047 [fatal][tid:main] SyntaxError: Unexpected token ','
```
And the error on device:
![unexpect-token](https://cloud.githubusercontent.com/assets/1091472/14163957/79fce858-f72d-11e5-98df-9e70cab00fb1.jpg)

**Comment by hasen6** [comment]
Yes its a very weird error. What version are you using?

I wouldn't hold your breath on it getting solved though. Most issues here tend to get closed without being solved at all.

**Comment by chenxsan** [comment]
@hasen6 I'm running react-native 0.22. The error showed on my iPhone 5s (iOS 7.1) device. Nothing wrong on iPhone 6 device with iOS 9.3 or any simulators. It's really difficult to debug such an error.

**Comment by hasen6** [comment]
Well the error is clearly still there in the latest version then along with loads of other ignored issues. What I did to solve it was go through every file, removing them from by commenting references out and then removing parts of code until the error is gone. Then add things back in until the error appears. Eventually you'l find the offending code.

Check it isn't the same as the issue I had above.

**Comment by xcarpentier** [comment]
+1

**Comment by giftman** [comment]
+1...

**Comment by xcarpentier** [comment]
About my problem : there is no bug on ios 9.3 but on ios 8. I fixed it on my app, it was because a component tag contain same props twice. I think because the JavaScript Core engine is different and more permissive in 9.3 when you have same keys in object.
