### ISSUE TITLE
Integration with Existing App, should I start server through the cmd by hand

### ISSUE THREAD

**Issue by DavidYangNO1** [facebook/react-native#617]
follow  the step of 'Integration with Existing App' , i success deploy to the existing project. but one question: if i don't start  React Native development server , the existing project can't running, so the existing project must start server  through the  cmd by hand , it's not good solution, do you have any  suggestion

**Comment by frantic** [comment]
React.xcodeproj has a build step that runs packager automatically, see https://github.com/facebook/react-native/blob/master/React/React.xcodeproj/project.pbxproj#L450

Note that you can also ship pre-built bundle within the app itself http://facebook.github.io/react-native/docs/runningondevice.html#content
