### ISSUE TITLE
[RCTUtils] RCTJSErrorFromNSError looses original error code

### ISSUE THREAD

**Issue by zeasy** [facebook/react-native#6171]
In RCTUtils.m, RCTJSErrorFromNSError https://github.com/facebook/react-native/blob/master/React/Base/RCTUtils.m#L375 always passes `RCTErrorUnspecified` as an error code which always results in `RCTErrorUnspecified` as a code.

**Comment by grabbou** [comment]
With the current description, it's quite hard to tell what is the real issue/question. Please feel free to reopen after you update the original question with more informations. The code pasted does indeed have `errorInfo[@"code"]` so looks like there's nothing wrong with it.

**Comment by zeasy** [comment]
But RCTJSErrorFromNSError incoming call RCTJSErrorFromCodeMessageAndNSError code equal RCTErrorUnspecified, that errorInfo [@ "code"] = code:? RCTErrorUnspecified in errorInfo [@ "code"] will always be equal RCTErrorUnspecified, view RCTModuleMethod.m 311 line , when the callback type RCTResponseErrorBlock time , code will be lost forever .

**Comment by grabbou** [comment]
Thanks! That's much clearer now :)

**Comment by grabbou** [comment]
FYI - that used to work properly at some stage https://github.com/facebook/react-native/blob/3c541ca54095fbf9d572362bcb661593acc1b64b/React/Base/RCTUtils.m#L299
