### ISSUE TITLE
fontWeight should support the wording as in Xcode

### ISSUE THREAD

**Issue by fatuhoku** [facebook/react-native#618]
In Xcode you can select out of a handful of values for font weight: 

![screen shot 2015-04-02 at 12 06 06](https://cloud.githubusercontent.com/assets/430233/6963099/e38d586c-d932-11e4-8351-714870de6726.png)

React Native's supported values for `fontWeight` looks like this: ![screen shot 2015-04-02 at 12 24 05](https://cloud.githubusercontent.com/assets/430233/6963142/66dd353e-d933-11e4-810c-03d9e6d96c41.png). It's not obvious what `200` or `900` means in relation to iOS font weight values like "Semibold" or "Thin".

How could the mapping be made clearer?

**Comment by vkurchatkin** [comment]
I think this is the way it is for compatibility with CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

**Comment by ericvicenti** [comment]
Yep, we're sticking to the web standards everywhere we can, but we don't want you to be restricted. Is there anything that you can do in Xcode that you can't do with the font-weight CSS spec?

Feel free to send a PR to clarify the docs and link to the spec

**Comment by fatuhoku** [comment]
@ericvicenti Hi, coming back to this, I guess it's possible to make a mapping for the following strings (essentially an enum) onto the relevant `fontWeight`s... it's just that our designer would specify the font weight in terms of 'Medium' or 'Light' and translating into a number like 100 is simply not descriptive.

100 = Thin (Hairline)
200 = Extra Light (Ultra Light)
300 = Light
400 = Normal
500 = Medium
600 = Semi Bold (Demi Bold)
700 = Bold
800 = Extra Bold (Ultra Bold)
900 = Black (Heavy)
