### ISSUE TITLE
[Accessibility] Touchable components need "Touch Sounds" for more native feeling.

### ISSUE THREAD

**Issue by bcalik** [facebook/react-native#6188]
Hello,

Touchable components must have a native android touch sound for more native feeling.
It feels unnatural to me since there is no tap/touch sound at all.

I did not test it on iOS.

**Comment by bcalik** [comment]
@christopherdro could you please label this as `android`.

**Comment by christopherdro** [comment]
I was thinking about this myself the other day. 
This would be something custom since it's currently not available through React Native. 

Going to leave this open for both platforms.

**Comment by bcalik** [comment]
I don't know for iOS, but these touch sounds are default on Android native apps. When you just add a simple Button component, it has touch sounds by default.

**Comment by brentvatne** [comment]
@bcalik - did you try [TouchableNativeFeedback](https://facebook.github.io/react-native/docs/touchablenativefeedback.html)?

**Comment by bcalik** [comment]
@brentvatne Yes I have been using TouchableNativeFeedback in my app.

**Comment by brentvatne** [comment]
@bcalik - and does that work as you expect?

**Comment by bcalik** [comment]
@brentvatne No, that's why I am reporting this issue.

**Comment by brentvatne** [comment]
@bcalik - OK. If you would like to submit a pull request to fix this, we can discuss there. I created a ProductPains issue to track this, it is the tool that we use to prioritize features from open source, please go ahead and upvote there: https://productpains.com/post/react-native/touchable-components-need-touch-sounds-for-more-native-feeling/

Anyone else interested should also upvote on ProductPains :)

Thanks for the report!

**Comment by bcalik** [comment]
Looks like Android play click sound effect while using `OnClickListener`, but not for `OnTouchListener`.
To implement sound effect for OnTouchListener, you have to play it yourself like:

```java
public boolean onTouch(View v, MotionEvent event)
{
    if(event.getAction() == MotionEvent.ACTION_DOWN)
    {
        v.playSoundEffect(SoundEffectConstants.CLICK);
    }
    return true;
}
```

I hope this may help someone to implement this to React-Native.

**Comment by mikemonteith** [comment]
I am trying to implement this, but this is my first ReactNative PR. Help would be welcome :)
https://github.com/mikemonteith/react-native/tree/android-click-sounds

I'm adding a new command to `UIManager#dispatchViewManagerCommand` that plays the click sound when a TouchableNativeFeedback component is pressed.

**Comment by brentvatne** [comment]
Reopening this because there seems to be more interest :)

I don't have time to work on this unfortunately, maybe @satya164 or @janicduplessis can help you out @mikemonteith!

**Comment by janicduplessis** [comment]
@mikemonteith Looks good, you should submit a PR with that and I'll check it out!

Should we make it work for other types of touchables or just this TouchableNative?

**Comment by janicduplessis** [comment]
Also I double checked and there are no sounds on iOS so we don't have to worry about that.

**Comment by bcalik** [comment]
It also would be better if there is a prop to enable and disable sounds.

**Comment by janicduplessis** [comment]
Agreed :)

**Comment by mikemonteith** [comment]
Created a PR. https://github.com/facebook/react-native/pull/6825
I moved the code into the Touchable.Mixin so that other touchable components are affected.
Also added a prop soundEffectsEnabled which defaults to true.

**Comment by lacker** [comment]
Closing since the linked PR has been closed

**Comment by bcalik** [comment]
@lacker But the issue still exists. So this should stay open until someone fixes the issue.

**Comment by janicduplessis** [comment]
The PR was not merged because of inactivity, if someone wants to pick it up and do the requested changes it would be great.

**Comment by abbasfreestyle** [comment]
I hope this can be implemented soon. It really needs it for that native feel, Android app kinda feels naked without it.

**Comment by lneves12** [comment]
Actually the lack of this sounds is the only way I have to distinguish an native app from a react-native app (which is bad)

**Comment by ericvicenti** [comment]
This is a feature request that proably belongs on [product pains](https://react-native.canny.io/feature-requests), unless somebody wants to submit a PR for it.

**Comment by nsisodiya** [comment]
Can somebody tell me any `workaround` ?

**Comment by abbasfreestyle** [comment]
I've added this into ProductPains / Canny

Please upvote to give it more attention:
https://react-native.canny.io/feature-requests/p/touchable-component-sounds-android

**Comment by bm-software** [comment]
Hi all, this "issue" has been resolved? I notice that the PR [#6825](https://github.com/facebook/react-native/pull/6825) has been closed but I don't understand if the code of that PS has been merged or not...

**Comment by deehuey** [comment]
Hey guys, any update on this? Like @bcalik said, this is an absolutely essential feature that seems to be missing. Is there any way to achieve this?

**Comment by Macromeda** [comment]
it's been more than 2 years and you guys still haven't added this very simple feature...

**Comment by janicduplessis** [comment]
https://github.com/facebook/react-native/pull/17183 landed recently
