### ISSUE TITLE
Android Device RCTView Error!

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#6191]
Hi,

I get this error only on my device, on the simulator it works fine. (Android 4.4.2 / RN 0.20)
![screen shot 2016-02-27 at 8 47 09 pm](https://cloud.githubusercontent.com/assets/6751025/13374947/5b4bbf14-dd93-11e5-84e8-9e6d6761af48.png)

Thank You!

**Comment by alvaromb** [comment]
Check if you have any `TouchableNativeFeedback` with `Ripple` option and you're running in a lower Android version.

**Comment by DHidee66** [comment]
@alvaromb Yeah that was the problem. There are some things like the `Ripple` option and the elevation that are not available on API 19. Thanks for your answer :)
