### ISSUE TITLE
2048 - Keystokes don't change board

### ISSUE THREAD

**Issue by blin17** [facebook/react-native#6196]
I'm trying out the 2048 example. I was able to build it successfully using npm install without any errors, but I can't get it to do anything besides show a static board. None of the keystrokes work. Also I get a warning for RCTImageView Does Not Exist.

Running the iOS version on Mac OS, Node v5.7, React v0.20

![http://i.imgur.com/02bUqsF.jpg](http://i.imgur.com/02bUqsF.jpg)

**Comment by jaredly** [comment]
the game isn't set up for keystrokes; it's a mobile app :D try tapping on the board.

**Comment by blin17** [comment]
Ah thanks @jaredly ! After giving it another try, I found out the problem was that I wasn't dragging with the simulator and instead just tapping.
