### ISSUE TITLE
[Bridge] Pass __fbBatchedBridgeConfig into the bundle instead of making it global

### ISSUE THREAD

**Issue by ide** [facebook/react-native#62]
This is to reduce globals and encourage scoping. A specific approach I have in mind is to make the bundle produce a function that takes the bridge config as an argument:

```js
(function(batchedBridgeConfig) {
// current bundle code here
});
// source map stuff
```

And when setting up ReactKit:

```objc
// get the js context from the executor -- API for this needs to be thought out
[[context evaluateScript:bundleScriptString] invokeWithArguments:@[configObject]]
```

Then the global goes away and you don't need `-[RCTJavaScriptExecutor injectJSONText:asGlobalObjectNamed:callback:]` either!

**Comment by sahrens** [comment]
Closing for now since it doesn't sound like this is blocking anything.
