### ISSUE TITLE
<TextInput> and the underlineColorAndroid-property [RN 0.19]

### ISSUE THREAD

**Issue by ippa** [facebook/react-native#6202]
Trying to color the textinput-line according to the docs http://facebook.github.io/react-native/releases/0.19/docs/textinput.html#underlinecolorandroid

But I keep getting "underlineColorAndroid" is not a valid style property.

**Comment by ippa** [comment]
brainfart, it's a property not a styling-element, closing :).

**Comment by pimkle** [comment]
haha
