### ISSUE TITLE
navBar.immediatelyRefresh() is not a function

### ISSUE THREAD

**Issue by crockpotveggies** [facebook/react-native#6205]
Using React-native on iOS 9.0+. Found a weird error when changing navigation:

```
_this3._navBar.immediatelyRefresh is not a function
```

The error occurs on line `379` of Navigator.js:

```
this._navBar && this._navBar.immediatelyRefresh();
```

No idea what prompted this - it appears to be a bug with React-native itself. Here are some relevant screenshots:

![screen shot 2016-02-28 at 7 03 07 pm](https://cloud.githubusercontent.com/assets/1445295/13384791/fa9c533e-de4d-11e5-9ed4-37e028d0ca17.png)

![screen shot 2016-02-28 at 7 03 51 pm](https://cloud.githubusercontent.com/assets/1445295/13384796/074bd6c2-de4e-11e5-9e84-33e87785c829.png)

##Additional Info##
Realized this happens when I'm attempting to unmount the components in the navigator stack. This is a `reset`.

**Comment by zxcpoiu** [comment]
Are you using react-native-router-flux between version 2.3.4~2.3.6 ?
If so, either stick with 2.3.1 or try 2.3.7
see: aksonov/react-native-router-flux#258

**Comment by crockpotveggies** [comment]
@zxcpoiu correct. And thanks for the tip! I will close this issue.

**Comment by reallistic** [comment]
I just received this error using react-native versions:
```
react-native-cli: 0.2.0
react-native: 0.23.1
```
I am NOT using the flux router nor is it installed.

The documentation does not mention that the navigationBar component needs this method defined.
Should the documentation be updated?

**Comment by zxcpoiu** [comment]
are you mess around between `Navigator` and `NavigationExperimental` ?
you may have to modify your code to work with `NavigationExperimental` accordingly on 0.23+

**Comment by reallistic** [comment]
I forgot to mention that once I added an empty `immediatelyRefresh` to my navBar this worked.

Is the NavigationExperimental a drop-in replacement?

**Comment by zxcpoiu** [comment]
I think it is a breaking change. are you import `Navigator` or `NavigationExperimental`?
you can learn nearly everything from Example corresponds to each:

https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/Navigator
and
https://github.com/facebook/react-native/tree/master/Examples/UIExplorer/NavigationExperimental

**while your playing, make sure you choose the right release branch**

**Comment by ide** [comment]
NavigationExperimental is not a drop-in replacement for Navigator. It is a completely different API.

As for the original issue with immediatelyRefresh -- that method is part of the NavigationBar API so you should implement it, even with a no-op.
