### ISSUE TITLE
[Animation] Easing.bezier returning faulty values

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#6207]
This [CodePen](http://codepen.io/aleclarson/pen/VawJyJ?editors=0012) demonstrates the issue.

**Comment by mkonicek** [comment]
cc @vjeux

**Comment by vjeux** [comment]
Do you have a fix? Or another bezier implementation that we can use that doesn't have this issue?

**Comment by aleclarson** [comment]
Found the fix [here](https://github.com/arian/cubic-bezier/issues/1).

Something with Newton's method is bugged.

Comment out this code:
```js
// First try a few iterations of Newton's method -- normally very fast.
for (t2 = x, i = 0; i < 8; i++){
  x2 = curveX(t2) - x;
  if (Math.abs(x2) < epsilon) { return curveY(t2); }
  d2 = derivativeCurveX(t2);
  if (Math.abs(d2) < 1e-6) { break; }
  t2 = t2 - x2 / d2;
}
```

**Comment by ide** [comment]
IIRC the bezier calculation in RN was written quickly to get things working and hasn't been optimized. Could be a good, self-contained opportunity for optimization if anyone is interested in helping out.

**Comment by vjeux** [comment]
@ide I googled for bezier and found the one linked. It appeared to work so I copy and pasted it :p

**Comment by vjeux** [comment]
Feel free to send a pull request. Would be nice to add some tests as well if you have time :)

**Comment by aleclarson** [comment]
PR submitted: #6340 :wink:
