### ISSUE TITLE
[Packager] Idea: Check @2x and @3x images for pixel misalignment

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#6209]
Throw an error when a `@2x` image isn't exactly twice the width & height of its 1x version. Same for `@3x`.

**Comment by gre** [comment]
:+1:

**Comment by brentvatne** [comment]
@aleclarson - what's the pain point you want to address here? If we add this, it should probably be an opt-in feature.

**Comment by aleclarson** [comment]
From [this article](http://blog.xebia.com/ios-pixel-misalignment-why-its-bad-how-to-fix-it/):

> Image misalignment degrades rendering performance significantly on iOS. This happens because a misaligned image needs to be interpolated with it’s surrounding pixels to determine what color values actually have to be sent to the screen buffer.

And this:

> Faulty dimensions on retina image resources is a common cause as well for pixel misalignment.

The packager can detect this problem! :smile:

https://productpains.com/post/react-native/packager-detect-pixel-misalignment-on-image-assets/

**Comment by jsierles** [comment]
This issue was [moved to Product Pains](https://productpains.com/post/react-native/packager-detect-pixel-misalignment-on-image-assets/)
