### ISSUE TITLE
[Android]RangeError:Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by jqmobile** [facebook/react-native#6211]
When I open a bundle from another bundle which has been open, it crashed.One bundle is open from local asset directory,the other is open from server by loadscript.I have a question about file named "CatalystInstanceImpl.java". Whether there is a limit of bundle quantities in one app.If there has been a bundle open,can i use it to open another bundle?

**Comment by jaredly** [comment]
Can you describe how you "open a bundle from another bundle"?
Is your question "can I have multiple bridges that are loaded from different JS bundles"? In that case, I believe the answer is yes.

Could you provide a stacktrace to your error? It is very difficult to help w/ your specific problem without more information.

**Comment by jqmobile** [comment]
@jaredly 
![screenshot_2016-03-03-20-14-41](https://cloud.githubusercontent.com/assets/7835147/13494251/170108de-e17e-11e5-9b59-862a820a9611.jpeg)

Here is a screenshot of my program running on device.  In my program, there is a bundle open when app start. And this bundle is locate in assets directory. And this bundle is used for selecting another bundle from server. It sends a request to server, such as "http://10.2.35.211:9798/com.beecode.nectar.bmd/web/jsx/index.android.bundle". And the server return a bundle. Then, app will start this bundle to change itself.

some code in here:
```
mReactRootView = new ReactRootView(this.getContext());

mReactInstanceManager = ReactInstanceManager.builder()
.setApplication(this.activity.getApplication())
.setJSBundleFile(bundleFile)
.setJSMainModuleName(jsMain)
.addPackage(new MainReactPackage())
.setUseDeveloperSupport(info.dev)
.setInitialLifecycleState(LifecycleState.RESUMED)
.build();

mReactRootView.startReactApplication(mReactInstanceManager, info.module, launchConfig);
this.addView(mReactRootView, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
```

Everytime I start a bundle from local assets directory or server by request in this way. It will run these code. 
'info' is some information of bundle.
'bundleFile' is address of bundle.Maybe 'file:///android_asset/index.android.bundle' or 'http://10.2.35.211:9798/.../index.android.bundle'.

When I debug this program. The local bundle is no problem. But When it start the bundle from server, It will crash in  'runJSBundle'. This method belong to CatalystInstanceImpl.java. The more detail said that it will run  'future.set(callable.call())' in MessageQueueThreadImpl.java,and then crash. It catch an error like screenshot, then the program quit.

I can't find mistake in my program by debuging. I'm not sure whether react-native support this usage method.The react-native version of mine is 0.20.
Can you give me some suggest? Thanks!

**Comment by brentvatne** [comment]
Hi there! This is not a bug so you will need to get some help on StackOverflow. You could alternatively reach out to the people working on CodePush (https://github.com/microsoft/code-push) or AppHub (https://apphub.io/) who know a lot about this type of thing.
