### ISSUE TITLE
AsyncStorage Problem

### ISSUE THREAD

**Issue by geobde** [facebook/react-native#6212]
Hi guys,
I am new to React and JavaScript.I have create a todo app with react native and i cant figure out how to save my data.

This is the code:
'use strict';
import React, {
  AppRegistry,
  Component,
  StyleSheet,
  StatusBar,
  Text,
  View,
  TextInput,
  ScrollView,
  TouchableHighlight
} from 'react-native';

var  Todo = React.createClass({

    getInitialState: function() {
        return {items: [], text: ''};
    },

    newItem: function(itemText) {
       return (
            <Text style={styles.todos}> ·  {itemText}</Text>

       );
    },

    addItem: function() {
        var nextItems = this.state.items.concat([this.state.text]);
        var nextText = '';
        this.setState({items: nextItems, text: nextText});
    },

    removeItems: function() {
       this.setState({items: []});
    },

   render: function() {
     return (
    <View style={styles.container}>
           <View style={styles.bar}>
               <TouchableHighlight
                     onPress={this.addItem}
                     underlayColor='none'>
                     <Text style={styles.add}>Add </Text>
              </TouchableHighlight>
             <TouchableHighlight
                   underlayColor='none'>
                   <Text style={styles.title}>Todo List</Text>
            </TouchableHighlight>
            <TouchableHighlight
                  onPress={this.removeItems}
                  underlayColor='none'>
                  <Text style={styles.clear}>Clear</Text>
           </TouchableHighlight>
         </View>
         <ScrollView>
         <View style={styles.main}>
              <View style={styles.todosList}>
               {this.state.items.map(this.newItem)}
               </View>
              <View style={styles.textInput}>
                  <TextInput style={styles.placeholder}
                          placeholder="Put your item"
                          value={this.state.text}
                          onChangeText={(text) => this.setState({text})}
                          maxLength={20}
                          underlineColorAndroid={'none'}
                          placeholderTextColor={'white'}
                   />
               </View>
              </View>
    </ScrollView>
  </View>
    );
  }
});
var styles = StyleSheet.create({
..........
});

**Comment by Kureev** [comment]
Hi @geobde,

There's an awesome place to post code / ask question first before filing an issue: StackOverflow. It's the best system for Q&A. Many people from the community hang out there and will be able to see and answer your question. This lets us use the github bug tracker for bugs.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
