### ISSUE TITLE
ScrollView's 'contentOffset' does not use a "scrolling" effect when reaching the target "Y".

### ISSUE THREAD

**Issue by af7** [facebook/react-native#6219]
I am using the `contentOffest` prop in `ScrollView` (on latest React Native, 0.20), in order to show different sections of the `ScrollView` content depending on which button the user presses.

The shifting works, no problem with that, but it goes to the related "Y" instantly, not with the same "scrolling" effect it would use when we scroll with the finger.

Can this be fixed somehow?

Thanks.

**Comment by jaredly** [comment]
You want to search for "animate scrolling javascript" or something like that. StackOverflow would be a great place for this question if you are unable to find an answer

**Comment by brentvatne** [comment]
You can just use `scrollTo` - https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L365-L387

It would be nice to add this to our docs :)

**Comment by brentvatne** [comment]
@facebook-github-bot answered
