### ISSUE TITLE
[Android] {flexDirection: 'row'} not work

### ISSUE THREAD

**Issue by gut4** [facebook/react-native#6230]
react-native v0.21.0

Even basic:
`<View slyle={{flexDirection: 'row'}}>
<View><Text>abc</Text></View>
<View><Text>abc</Text></View>
<View><Text>abc</Text></View>
</View>`

Views stays in column.

**Comment by gut4** [comment]
hey, this example not work too.
![screen shot 2016-03-01 at 8 28 04 pm](https://cloud.githubusercontent.com/assets/148298/13435664/65932650-dfec-11e5-9135-0179397f5d38.png)

**Comment by grabbou** [comment]
BTW - isn't that because of we have `slyle` instead of `style` ? :)

**Comment by gut4** [comment]
now this working on android but not in ios ;)
I think it's issue. Examples with nested <View> not work on both ios and android, with <Text> inside <View> work only on android.
