### ISSUE TITLE
accessibilityLabel and testID props in 3rd party modules

### ISSUE THREAD

**Issue by timjacobi** [facebook/react-native#6233]
I have come across a couple of react-native third party modules that don't pass on the props accessibilityLabel and testID to the underlying components e.g. `<Text />` and `<View />`. While it is completely up to the module author to implement this it makes it much harder to test apps using these components as test frameworks like *Appium* for example rely on these IDs to be set in order to be able to uniquely identify a component. (Okay there's XPath but that is not a great option)

How should this be addressed? I can think of the following options

* Let react-native handle it automatically
* Include a note in the docs to remind authors that this is important
* Have react-native display a warning if the props are not being passed on

**Comment by satya164** [comment]
> Let react-native handle it automatically

How do you think it'd work?

> Include a note in the docs to remind authors that this is important

We should probably do this

> Have react-native display a warning if the props are not being passed on

It'll generate a lot of warnings which are not possible to fix everywhere. In many places these are used just for styling and layout, so accessibility props don't make sense there.

**Comment by timjacobi** [comment]
Good points. Be no means I know the react-native code by heart so I am not sure if the APIs for the first option exist. I guess raising awareness through documentation is the best way then.

**Comment by brentvatne** [comment]
@timjacobi - if you come up with a proposal for how we can solve this we can open an issue with your suggested approach.

I think this will need to be driven by library authors. If you create issues or pull requests on the libraries that you're using to fix this, that is probably the best way forward right now and I'm sure others would appreciate your efforts!

**Comment by timjacobi** [comment]
@brentvatne Agreed. I'm already doing that.
