### ISSUE TITLE
Retaining ListView/ScrollView Content Offset When Toggling Components With State

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#6234]
Hi,

I'm trying to re-create a native area of our app in which we have a segmented control placed in the nav bar which toggles between two tables: "Activities" and "My Activities".

I'm updating a container components state when the segmented control value is changed and then determining which ListView to show based on that state.

The problem is that I can't figure out a way to retain the original ListView components and so a new list view is created with each toggle of the segmented control and the content offset returns to 0, 0

I tried a workaround where I save the current content offset and use that as the default when rendering the ListView but then there's a long delay while the ListView catches up on the cell rendering.

How do you deal with this scenario? I see that the TabBar is able to switch between views without this issue with it because there's a native component that simply swaps the views but I would assume people have had a similar issue in plain react where there isn't such an option.

I was considering SO for this but I can't quite tell if this is a bug, a feature request or just me not having enough knowledge on the subject.

Thanks!
Luke

**Comment by brentvatne** [comment]
@lprhodes - easiest to post some code for this (even if you strip out irrelevant parts) as sometimes code is more clear than words ;) also it's good to relate to functionality in a popular app so we have a better idea of what you're trying to accomplish, or show a mockup. This does seem like a StackOverflow issue, though, so I will close this but if you link to the StackOverflow thread for this on here that would be useful :)
