### ISSUE TITLE
Flexbox doesn't work inside a ListView Cell

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#6237]
Hi,

I've created an example of the issue here:
https://rnplay.org/apps/xk2Jrg

I need the left and right columns to equal the height of the middle column so that I can center items vertically in them - this works outside of a ListView and while I've tired applying additional style to the StaticRenderer and ListView I've been unable to make it work.

Any ideas?

Thanks

Luke

**Comment by lprhodes** [comment]
Hi,

I've created an example of the issue here:
https://rnplay.org/apps/xk2Jrg

I need the left and right columns to equal the height of the middle column so that I can center items vertically in them - this works outside of a ListView and while I've tired applying additional style to the StaticRenderer and ListView I've been unable to make it work.

Any ideas?

Thanks

Luke

**Comment by jjshammas** [comment]
In general, I've found that if a parent's size is determined by its children's dimensions, flexbox will not work inside that parent. What I did to solve the same problem you ran into was to measure the list row item after `onLayout` was called, and used a state variable called `height` that I would then pass as a style property to whichever element I needed to have vertically centered children.

**Comment by lprhodes** [comment]
I've updated the title/deleted the original description sorry (I thought I'd done this yesterday just after creating the issue)

Thanks for your suggestion - I'll give it a go but a fear it may be too slow for a ListVIew.

Here's another example of it working as expected when not contained in a ListView so there definitely looks to be something up here: https://rnplay.org/apps/hu9Jvw

**Comment by grabbou** [comment]
For me both examples look the same, am I missing something?

https://rnplay.org/apps/hu9Jvw
https://rnplay.org/apps/xk2Jrg

**Comment by bomalley** [comment]
@grabbou – Those two rnplay links produce different results for me – exactly as @lprhodes describes. 

Here are the screenshots:  [React Native Flexbox Issue Screenshots](http://imgur.com/a/GiF0u/all)

I'm seeing similar issues with absolutely positioned items that don't have their dimensions set explicitly.  It's a huge challenge to style those components.

**Comment by grabbou** [comment]
There was a discussion about absolute positioning somewhere here if I am not wrong (i've gone into that issue as well).

I am probably blind, but I still see the same behaviour on both pictures - yellow bg takes 100% of the row height in both cases?

**Comment by brentvatne** [comment]
@vjeux - I know you're out of office but if you have some free time and want to weigh in on this it might be appreciated :)

**Comment by brentvatne** [comment]
Problem: Layout for ListView rows is different than if you lay out the row outside of a ListView. In column 1 and 3 if you set flex: 1, it will not take up the full height of the container.

```
┌──────────────────────────┐                                 
│ ListView row - expected  │                                 
└──────────────────────────┘                                 
┌───────────────┬───────────────────────────┬───────────────┐
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
└───────────────┴───────────────────────────┴───────────────┘
                                                             
┌───────────────────────────┐                                
│   ListView row - actual   │                                
└───────────────────────────┘                                
┌───────────────┬───────────────────────────┬───────────────┐
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222│333333333333333│
│111111111111111│222222222222222222222222222├───────────────┤
│111111111111111│222222222222222222222222222│               │
│111111111111111│222222222222222222222222222│               │
│111111111111111│222222222222222222222222222│               │
├───────────────┤222222222222222222222222222│               │
│               │222222222222222222222222222│               │
│               │222222222222222222222222222│               │
│               │222222222222222222222222222│               │
└───────────────┴───────────────────────────┴───────────────┘
```

**Comment by vjeux** [comment]
I've seen this fix: https://github.com/facebook/css-layout/pull/145 than landed on Android https://github.com/facebook/react-native/commit/f538032888976f0199659645ddecf0650133cc62 which may fix the problem.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/flexbox-doesnt-work-inside-a-listview-cell

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
