### ISSUE TITLE
[Android] 0.20 to 0.21 Manual Upgrade Documentation

### ISSUE THREAD

**Issue by jeffchienzabinet** [facebook/react-native#6238]
There's documentation for manual upgrade from 0.13 to 0.14 on iOS but there's no documentation on the upgrade from 0.20 to 0.21 on Android. I've made changes to my project that seems to break compatibility with the yeoman generator (my node package name has a dash so when it tries to use that for the Java package name it fails) so knowing how to do it manually is probably more convenient than trying to fix the upgrade script for my edge case.

https://github.com/facebook/react-native/blob/master/docs/Upgrading.md

**Comment by mkonicek** [comment]
> my node package name has a dash

We'll need some example code / project to understand what this means.

**Comment by satya164** [comment]
@mkonicek The `name` field in `package.json` has a `-` which is not supported in an android package name. Right now we use the name field to generate a package name, which we should probably change in the future.

**Comment by jeffchienzabinet** [comment]
@satya164 nailed the issue.

**Comment by brentvatne** [comment]
So we have a decision that needs to be made here:

- Do we update the Android package name script to properly deal dashes or do we add docs to the upgrade process? It seems to me that we should be dealing with this edge case.

**Comment by satya164** [comment]
@brentvatne I think custom package names can cover a wider use case. Most packages (at least on android) follow the format domain.company.name, and I think we should support this use case (I can give it a try). But of course it's not as simple as stripping out invalid characters. I think we can go with stripping the characters first, then we can add support for customizing the package name.

**Comment by brentvatne** [comment]
@satya164 - it looks like you can customize the package name when you init the project by providing the `package` option: https://github.com/facebook/react-native/blob/master/local-cli/__tests__/generators-test.js#L111-L116

Do we just need to make this work with upgrade? Let's decide on this and update our implementation and test plan.

**Comment by satya164** [comment]
@brentvatne Wut! Never knew this existed. I'll test if it works with `react-native upgrade`, and if does update the docs.

**Comment by brentvatne** [comment]
Haha awesome :) I assigned you so it's clear who is taking over this one

**Comment by pyrech** [comment]
Will this issue be fixed in some day? As far as I can see, it's still present with RN v0.30?

**Comment by satya164** [comment]
@pyrech Haven't gotten time to look into it yet. Feel free to take this up if you want.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-020-to-021-manual-upgrade-documentation

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by jpshelley** [comment]
I'm still having this issue on my upgrades as mentioned above.
My React Native directory and project name in my `package.json` is `hudl-messaging`.
However my Android project should be `com.hudl.messaging`. How would I go about defining this so my upgrade works? I'm trying to upgrade from 0.35 to 0.37.
