### ISSUE TITLE
Can i develop react native IOS apps on windows pc

### ISSUE THREAD

**Issue by anwarhussain93** [facebook/react-native#6240]
Hi everyone, Can i able to develop react-native IOS apps in my windows pc, if possible then please post what are the requirements and setup require to develop and run react-native ios apps in windows pc

**Comment by peterp** [comment]
You'll need Xcode, which means that you'll need OS X, which means that you need a Mac or virtualization software.

Here's a guide: https://blog.udemy.com/xcode-on-windows/. You should more than likely post this on StackOverflow instead.

**Comment by chirag04** [comment]
@peterp summarized it nicely. Feel free to post more such questions on stackOverflow or react-native channel on discord if you need any help.

**Comment by anwarhussain93** [comment]
@peterp thanks for your neat information.

**Comment by cooolan00p** [comment]
Can I create a react native app in windows machine and use the same project for building ios app in a mac?

**Comment by peterp** [comment]
@cooolan00p Yes, but you'll be creating one for Android on Windows.

**Comment by cooolan00p** [comment]
yes, I actually created a  project in such a manner that it supports android, ios and web devolopment....When I tried to run it in android, it ran with no issues, but when it came to ios it started showing some errors.

**Comment by peterp** [comment]
@cooolan00p "learn once, write everywhere" was the slogan, but I think with a bit of knowledge of both the highs and lows in each platform you can do it. :)

**Comment by cooolan00p** [comment]
Finally I got it working...I just changed the strategy.I just started the process all over once and this time on mac, there I checked on the simulator and its working and finally used the same source code in the windows machine and found that its working for android too...finally relieved....

**Comment by knwabueze** [comment]
What about create-react-native-app? As long as you don't eject, you are able to test your app on iOS and Android by using [Expo](https://expo.io/) and the app on the respective device. You can probably find some way to integrate Expo into your existing project, however I don't have much experience with that.

**Comment by nzhtrtlc** [comment]
You can use expo. With expo you can run ios app on windows no need mac or xcode.
BUT you need an iphone device. As the result you need at least one mac device.

**Comment by SamiChab** [comment]
Is it possible to generate an .ipa file (iOS application archive file which stores the iOS app) on a windows machine running Expo?

**Comment by optimatex** [comment]
@nzhtrtlc
Hi. How can I do this? I mean I have iPhone and expo. Which steps should I perform to run ios app on windows?

**Comment by nzhtrtlc** [comment]
@optimatex If i'm not after you follow thesee steps you should be able to run your app in your iphone.

First run your app.
- npm run ios
Then there should be a qrcode.
Scan the qrcode using expo application in your iphone device. If qrcode wont work, try internal ip address. Example: exp://192.168.0.2:19000
After that you'll be able to debug your app using your real device which is iPhone.

**Comment by nicoara** [comment]
Hello,

I have a virtual machine with MacOS on Windows. I want to be able to run the app on my own real iPhone device. How to proceed, given that the exp://192.168,0.2 is a local address that is not visible outside the virtual machine?
Inside Expo XDE, the Device button shows only the simulator, and Share will provide a qr code with the local address.

Thank you

**Comment by stevefan1999** [comment]
@nicoara Well you could do this the other way round, shift your Expo/CRNA environment and RNPM in Windows side, find the host-only address in your macOS VM (usually 192.168.6X.X range) and connect to your Windows host.

I'd be covering this in my Medium article but I doubt I have time to do.

**Comment by f3ltron** [comment]
Expose doesn't run a real app no ? It just create an app but you can't access all native feature am i wrong ?

**Comment by stevefan1999** [comment]
@f3ltron Expo doesn't support native modules I'm afraid. Behind the scene, it is still the 60fps smooth React Native, it just requires you to go full-JS, which is what most of the devs are doing. I don't think you'd really need native modules unless you are trying to breakthrough some performance barrier (e.g. sophiticated algorithms, adapting existing native codebases, bridging closed source product etc).

**Comment by stevefan1999** [comment]
@f3ltron I'm not sure what you mean. If you are using CRNA you need to eject your repo to use Expo Kit so your native modules could co-exist, but you lost the benefits of managed Expo (like automated builds).

**Comment by f3ltron** [comment]
with ionic. You have ionic dev app looks like expose. But with that app you have some restricted access to contacts books storage etc. My question with expose is that we have the same restriction or not ?

**Comment by stevefan1999** [comment]
@f3ltron It's called Expo, not Expose. I never used the codebase you mentioned. If those modules aren't using native-code, they shall be running fine.

**Comment by chhonmeily** [comment]
wow thank you so much everyone, this has been a very helpful conversation between everyone here.
