### ISSUE TITLE
[Android] fetch never reaches then or catch on PATCH

### ISSUE THREAD

**Issue by mudetroit** [facebook/react-native#6246]
I seriously hate filing issues like this; because the best information I can give still seems very incomplete. But have been trying to track down more details then this for a couple days and I am not getting anywhere with it.

When executing a call to the 'fetch' polyfill with the 'PATCH' method I am very frequently, but not always sadly seeing it fail to ever trigger either the then or the catch handlers.

```
fetch(url, {
  method: 'PATCH'
  headers,
  body: JSON.stringify(patches)
})
.then((response) => console.log(response))
.catch((error) -> console.log(error));
```

The majority of the time nothing ever makes it to the logs down either of those code paths. Not certain if there is some basic item I am missing, or if I am stumbling on some more fundamental problem. Worth noting. The same code path in our iOS project doesn't seem to suffer from the same problems.

**Comment by grabbou** [comment]
I can confirm no issues on iOS (I am using patch quite heavily), however - in few Android apps I haven't noticed it as well.

CC: @vjeux you seem to be active in polyfill-related discussions, so cc'ing!

**Comment by mudetroit** [comment]
FWIW, some change between v0.20.0 and v0.21.0 seems to have fixed whatever problem was underlying my issue. I am trying to figure out what changed that led to it, but base problem is gone now.
