### ISSUE TITLE
Settings UITabBar Tint

### ISSUE THREAD

**Issue by skevy** [facebook/react-native#626]
What's the best way to set UITabBar tint in React Native?

In just plain ole Objective-C you'd do:

```[[UITabBar appearance] setTintColor:[UIColor whiteColor]];```

I don't see a specific way to set appearance properties in React Native when looking through the code. Would this need a separate API of some kind, or is there some simple way to do it that I'm missing?

**Comment by skevy** [comment]
cc @nickhudkins

**Comment by Kureev** [comment]
:+1: I tried to implement custom component with `backgroundColor` and I always got it overriden by white color. How and why? I'm not passing any `style` attribute to the component.

**Comment by nickhudkins** [comment]
UITabBar tintColor is controlled by the static setTintColor method on UITabBar#appearance. In order to actually adjust the TabBarItem tint, you either need to implement custom Tab Bar Items, or you'll need to provide a hook to the method @skevy mentioned.

**Comment by brentvatne** [comment]
This is resolved now [here](https://facebook.github.io/react-native/docs/tabbarios.html#bartintcolor)
