### ISSUE TITLE
[Android][TextInput] Cursor color

### ISSUE THREAD

**Issue by efkan** [facebook/react-native#6263]
TextInput needs a prop like 'syncCursorColor' to change cursor color. 

syncCursorColor prop value should be a bool. If there is a syncCursorColor prop in the `textInput` component (it means the prop value is `true`) then the java code of `android:textCursorDrawable="@null"` has to be run in Android side.

I've never contribute to this repository. So I don't know what the React-Native textInput component code and how should it be changed.

The cursor color cannot be changed yet. And if placeholderTextColor and underlineColorAndroid are assigned the component appearance is not good like the following.

![white_cursor](https://cloud.githubusercontent.com/assets/6974198/13488474/233c98d8-e12a-11e5-9b96-127b8636aa9d.png)

![black_cursor](https://cloud.githubusercontent.com/assets/6974198/13488477/25bab824-e12a-11e5-9efa-516d8d7c76dd.png)

However [this blog](http://android--code.blogspot.com.tr/2015/08/android-edittext-cursor-color.html) says;

> Set the android:textCursorDrawable attribute value to @null, then EditText widget will display text color as cursor color

```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/rl"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="10dp"
    tools:context=".MainActivity"
    android:background="#ced4cb"
    >
    <!--
        android:textCursorDrawable="@null"
        android:textColor

            Set the android:textCursorDrawable attribute value to @null,
            then EditText widget will display text color as cursor color
    -->
    <EditText
        android:id="@+id/et"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:hint="Input your country"
        android:padding="10dp"
        android:textCursorDrawable="@null"
        />
    <EditText
        android:id="@+id/et_city"
        android:layout_width="250dp"
        android:layout_height="wrap_content"
        android:hint="Input your City"
        android:padding="10dp"
        android:layout_below="@+id/et"
        android:textCursorDrawable="@null"
        android:textColor="#ff0004"
        />
</RelativeLayout>
 
```

![androidedittextcursorcolor](https://cloud.githubusercontent.com/assets/6974198/13488186/587759e0-e128-11e5-9915-b4f11ed15459.png)

![androidedittextcursorcolor2](https://cloud.githubusercontent.com/assets/6974198/13488191/5c83d75c-e128-11e5-87f1-eca17023df09.png)

**Comment by grabbou** [comment]
@mkonicek shouldn't this be default behaviour?

**Comment by efkan** [comment]
@grabbou , your question is not for me but I think shouldn't. 

Because Android sets the EditText cursor and placeholder as gray as default. However, when developing Android app this color can be changed. 

For instance; YouTube search EditText's cursor color. When pressing the magnifying glass to search video, the title and menu icon are removed and cursor color is changed to 'red'. (Sony music app sets search EditText's color as 'cyan' etc.)

In my case I use a dark color (deep purple) as toolbox color. I can color everything as white except cursor. And the user can not be aware of the cursor on the textInput.

**Comment by mkonicek** [comment]
See https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md

This is a feature request that should live on Product Pains so people can see how many people want this feature and prioritize based on that. Also, this should be implemented by the community, fb won't add this unless it's needed in one of the fb apps. GitHub should be used for tracking bugs.

I'll close this but feel free to move this to Product Pains / continue the discussion here.
