### ISSUE TITLE
Shared a component between scenes occurs a unwanted behavior on render

### ISSUE THREAD

**Issue by srlopez** [facebook/react-native#6268]
Between scenes that share a component, the component thought to belong to the first scene that render it.

Using 
- "react-native": "0.19.0",
- "react-redux": "4.1.2",
- "redux": "3.1.7",
as @alinzin explain in [github](https://github.com/alinz/example-react-native-redux), with all the tricks to setup this project. Are out there any other good solution? 

This is a simple App that shares a component between scenes using Navigator in [stackoverflow.com](http://stackoverflow.com/questions/35769644/) [http://stackoverflow.com/questions/35769644/](url)

The data to be presented is a counter, stored in a Redux store, so it is not on the state of the component.
The  inner component  thinks belong to the first scene that presented it, and does not behave as expected on rendering in the second component.

The first scene use 'connect' to pass state and actions as props, but the second scene receive their props as passProps from the Navigator. Is this 

Wich is the default behavior in theses cases.
I am wrong with this approach to share components?

**Comment by grabbou** [comment]
I believe passProps are only evaluated at the time you call the function for the first time, meaning the next time they change - these won't be propagated to the scene (that's why you don't see any updates).

I think you should instead of `passProps: {...this.props}` in your Scene1 component, just pass {...this.props} inside `App.js` and that should fix the issue.

So, change App.js to be:
```js
export default class App extends Component {
  render() {
    return (
      <Provider store={createStoreWithMiddleware(reducer, initialState)}>
        <Navigator style={{flex: 1}}
          initialRoute={{
            name: 'Scene1',
            component: connectComponent(Scene1),
          }}
          renderScene={(route, navigator) => {
            const Component = route.component;
            return (
              <View style={{flex: 1, marginTop: 40}}>
                <Component navigator={navigator} route={route} {...this.props} />
              </View>
            );
          }}
        />
      </Provider>
    )
  }
}
```

**Comment by srlopez** [comment]
Thanks @grabbou,
I just test that line you said 
` <Component navigator={navigator} route={route} {...this.props} />`
The Scene2 can't `render`, the counter is '`undefined`', and click on the actions throw this error `_this4.props.increment is not a function`, so this.props in that line doesn't bind nothing.

I don't understand why, as `passProps` in the `navigator.push` in Scene1, is just a brige to `<Component navigator={navigator} route={route} {...route.passProps} />` in the `Navigator` `renderScene`  why the inner component Counter doesn't not react  ;) as we expected.

**Comment by grabbou** [comment]
Ah, sorry - forgot to mention your App component has to be connected to Redux. So you should do:
```js
export default class RootComponent extends Component {
  render() {
    return (
      <Provider store={createStoreWithMiddleware(reducer, initialState)}>
        <App />
      </Provider>
    )
  }
}
```
and change your App to be connected to redux store. Then, you should be able to pass down the props from store to underlying components (currently your Scene1 component is connected to Redux so that all changes made to store only cause re-render in that component).

**Comment by srlopez** [comment]
Hi again @grabbou,
I made these changes, and some others like the App has been 'connect'ed before as a Container to bind the store and actions, removed the Provider form App component, and removed the passProps in Scene1

I have declared AppContainer inside the render of the RootComponent. Is this a good place? I don't use in any other place and RootComponent never render again?

```
export default class RootComponent extends Component {
  render () {
    const AppContainer = connectComponent(App); //<< App has to be container
    return (
      <Provider store={createStoreWithMiddleware(reducer, initialState)}>
        <AppContainer/>
      </Provider>
    )
  }
}

```
From App removed the Provider component

```
class App extends Component {
  render () {
    return (
        <Navigator style={{flex: 1}}

          initialRoute={{
            name: 'Scene1',
            //component: connectComponent(Scene1), <<.--Changed!
            component: Scene1,
          }}

          renderScene={ (route, navigator) => {
            const Component = route.component;
            return (
              <View style={{flex: 1, marginTop:40}}>
                <Component navigator={navigator} route={route} {...this.props} />
                {/*}<Component navigator={navigator} route={route} {...route.passProps} />{*/}
              </View>
            );
          }}
        />
    )
  }
}

```
And in Scene1 i have removed the passPros key from the route inside the buton to navigate to Scene2

```
<TouchableOpacity onPress={()=>{
          this.props.navigator.push({
            name: 'Scene2',
            component: Scene2,
            //passProps: {...this.props}
           })
        }}>
```

Just an other question: Now the trace show that when i press 'Forward' to Scene2, the Scene1 is rendered before !!!! and then Scene3 is rendered.


Thanks for your invaluable help

**Comment by grabbou** [comment]
No worries, so does it work now as desired?

> Now the trace show that when i press 'Forward' to Scene2, the Scene1 is rendered before !!!! and then Scene3 is rendered.

Did you mean `Scene2 is rendered` instead of Scene3? 

Anyway, if the main issue here is resolved, feel free to close. You can find me on Discord under the same nickname in 10-20 GMT+1 - we could keep discussion in there so I could help you with the remaining bit.

**Comment by srlopez** [comment]
Thanks @grabbou 
Oh! Wrong write!

Now the trace show that when i press 'Forward' to Scene2 (in Scene1), the Scene1 is rendered again !!!! and then Scene2 is rendered, so Scene1 is rendered twice. (minor problem)
