### ISSUE TITLE
Unable to execute JS call: __fbBatchedBridge is undefined

### ISSUE THREAD

**Issue by jandom** [facebook/react-native#6282]
Hi guys, 

I believe a similar sounding bug has already made it here some time ago (just searching the issue tracker). 

The message in the Xcode console is 
```
2016-03-03 22:49:51.428 [warn][tid:main][RCTDevMenu.m:323] RCTSourceCode module scriptURL has not been set
2016-03-03 22:49:51.432 [fatal][tid:com.facebook.React.JavaScript] Unable to execute JS call: __fbBatchedBridge is undefined
```

Steps to reproduce (using "react-native": "^0.21.0")

1. Execute `react-native init AwesomeProject`
2. open AwesomeProject.xcodeproj in Xcode
3. edit AppDelegate.m, uncomment `   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`
4. Product -> Run

I'm just trying to follow the docs from here https://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle maybe I'm misunderstanding something. 

I also tried generate the main.jsbundle file with `react-native bundle --entry-file ./index.ios.js --platform ios --bundle-output ios/main.jsbundle` but the same error happens when clicking Run

Thanks for all your work on React native, it's really fantastic!

**Comment by grabbou** [comment]
Hey,

So, none of the already proposed solutions in the closed issues works for you yet? :(

Leaving the search link for reference: https://github.com/facebook/react-native/issues?utf8=%E2%9C%93&q=__fbBatchedBridge

**Comment by jandom** [comment]
Hey, 

Thanks for getting back so quickly. Yeah, tried a handful yesterday and a few today – but it's hard to do a complete enumeration... 

However, irrespectively of whether there is a fix in one of those Issues, this is likely close to a step-by-step copy&paste instructions that new users will follow, since this is the vanilla AwesomeProject.

Here is what i tried:
* https://github.com/facebook/react-native/pull/5779 change url dev to false (breaks with a new error) add libReact.a to test target (same error, no change)

* https://github.com/facebook/react-native/issues/5820 `react-native bundle --entry-file ./index.ios.js --platform ios --bundle-output ios/main.jsbundle` the reference to main.jsbundle is present (same error, no change)

* https://github.com/facebook/react-native/issues/4881 running `react-native run-ios` with AppDelegate.m modified and Xcode turned off gives the original error message, so at least things are consistent here. the packager is running so issuing `react-native start` has no effect 

Again, thanks for getting back so fast and providing this support.

**Comment by shahchirag** [comment]
Hey,

Can you try commenting out the following lines https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh#L15-L18 . It was mentioned [here](https://github.com/facebook/react-native/issues/5770#issuecomment-180403648) and worked for me

**Comment by jandom** [comment]
That fixed for me, thanks @shahchirag and @grabbou 

in `node_modules/react-native/packager/packager.sh `

Replace 
```
    if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then		
      echo "Skipping bundling for Simulator platform"		
      exit 0;		
    fi
```
with 
```
#    if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then		
#      echo "Skipping bundling for Simulator platform"		
#      exit 0;		
#    fi
```

**Comment by jandom** [comment]
Out of curiosity, and largely as a digression to this issue, is this a bug? Or is it due to xcode/simulator? 

Additionally, i'm guessing not everybody is dependent on the xcode-heavy workflow that i go through, but how else does one upload the Archived version of the code to testflight and alike?

**Comment by Jeansilva89** [comment]
:+1:  This solution also worked for me. I just started a new project on React-Native 0.21.0

**Comment by shahchirag** [comment]
I know this sort of feels like a hack, but currently that's the only way to fix it. I believe this would be fixed in the coming days.

**Comment by marcshilling** [comment]
I don't know why those lines exist...you should absolutely have the option of running the bundled code on the simulator.

**Comment by ggharry** [comment]
The hack works, but any updates on this from the React team?

**Comment by philohelp** [comment]
Worked here too RN0.22

**Comment by luzuoquan** [comment]
Same code need to comment in `node_modules/react-native/packager/react-native-xcode.sh`

`if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then           
echo "Skipping bundling for Simulator platform"       
exit 0;     
    fi`

**Comment by longsangstan** [comment]
The uncomment solution works!
Just wondering is there any side effect for this?
My RN version: 0.26.2

**Comment by nverdhan** [comment]
@longsangstan The code is for speeding up build times as stated
```
# Speed up build times by skipping the creation of the offline package for debug
# builds on the simulator since the packager is supposed to be running anyways.
```
, so commenting it should just affect build-times, no other side-effects supposedly.

**Comment by ThomasRedstone** [comment]
Should this still be occurring for 0.39.2?
I'm getting the same error message, and the fix is working on macOS, building for iOS.

**Comment by tonydiepenbrock** [comment]
Just ran into this issue today as well, any ideas?

**Comment by ameego** [comment]
@tonydiepenbrock, same here!

**Comment by Mattk14** [comment]
Occurring on 0.40.0

**Comment by SteffenBerlin** [comment]
I am getting this issue no 0.41 as well! Commenting out fix doesn't work.. Any ideas?

**Comment by pdoggi** [comment]
Getting error on `react-native 0.41.2`. Commenting https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh#L17-L20 fixes it for me.

**Comment by ferologics** [comment]
Occurring on 0.41.0

**Comment by jarsen** [comment]
I was having this problem on 0.42.0 when launching from vscode. I somehow got it fixed by quitting the simulator, and first running `react-native run-ios`. Now it works when I launch from vscode.

**Comment by fabe** [comment]
Running `react-native-git-upgrade` fixed this for me.

**Comment by Luckygirlllll** [comment]
I have the same problem on 0.42.0, commenting didn't help me, and when I tried "react-native-git-upgrade" , it just says "command not found". Any ideas how to fix it?

**Comment by MattyK14** [comment]
@Luckygirlllll did you run `npm install -g react-native-git-upgrade` first?

**Comment by Luckygirlllll** [comment]
@MattyK14 Just have tried it, so I done `react-native-git-upgrade`, and after that `react-native run-ios`, and the error didn't disappear.

**Comment by MaxwellGover** [comment]
I'm on the latest version 0.43 and still getting this issue? :(

**Comment by DominicTobias** [comment]
Also getting this on 0.44

**Comment by DominicTobias** [comment]
I was getting this in 0.44, had to import `./app/index` instead of `./app` for some reason

**Comment by LAITONEN** [comment]
0.46 keep constantly getting this error.

**Comment by jpmonette** [comment]
Getting the exact same in `0.46.1`.

**Comment by martinezguillaume** [comment]
same here, 0.45 with expo sdk 18

**Comment by Stophface** [comment]
same here with expo xde 2.19.2

**Comment by williamwlchan** [comment]
Same here. Every time when I do Remote JS Debugging, I get this error on my iOS simulator. If I do not do Debugging, it is fine.

**Comment by aterribili** [comment]
I'm getting it in production on iOS. Any news?

**Comment by LAITONEN** [comment]
Not getting this error anymore. Maybe because:
- I started using **LAN** or **localhost** hosts of Expo.
- Expo got updated
- Started using simulator more often than phone itself for testing
