### ISSUE TITLE
How can React-Native textInput component can be modified?

### ISSUE THREAD

**Issue by efkan** [facebook/react-native#6285]
I've asked on [stackoverflow ](http://stackoverflow.com/questions/35776017/how-can-react-native-textinput-component-can-be-modified)but there is no a solution.

React-native offers developing [native modules][1] and UI components.

However I want to make minor changes in the [`TextInput` component][2] which is used in my app and is found on my computer. However there is no a Java file that is related with `TextInput`. 

I've tried to change textInput which is within `node_modules/react-native/android/com/facebook/react/react-native/0.21.0/react-native-0.21.0-sources.jar` folder. Unfortunately a change didn't happen. If I did properly.

In fact, **although I remove  `node_modules/react-native/android` folder, everything works normally**.

Is there any way to make small changes in `TextInput` in my app?

Ps: I want to try in my own app. If it works I can PR for that.

  [1]: http://facebook.github.io/react-native/docs/native-modules-android.html#content
  [2]: https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/views/textinput

**Comment by grabbou** [comment]
React Native ships with already compiled Android source to speed up the run time process. If you want to change its internals and `compile from source`, please follow this guide: https://facebook.github.io/react-native/docs/android-building-from-source.html#content

PS. It'd highly recommend you to write your own component on top of TextComponent or even copy it to your source so you can persist changes across updates.
