### ISSUE TITLE
Strange error with multiple callbacks

### ISSUE THREAD

**Issue by SteveAquino** [facebook/react-native#6286]
I'm trying to implement a module with multiple callbacks (eg, onStart and onComplete), however it seems that even with a minimal example React Native errors out executing the second callback.  Here is an example:

```objc
// RCTActivityViewManager.m

#import "RCTCallbackTest.h"
#import "RCTEventDispatcher.h"

@implementation RCTActivityViewManager
@synthesize bridge = _bridge;

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(test:(RCTResponseSenderBlock)firstCallback nextCallback:(RCTResponseSenderBlock)nextCallback) {
  firstCallback(@[[NSNull null]]);
  nextCallback(@[[NSNull null]]);
}

@end
```

```javascript
ActivityViewManager.test((_ => ()), (_ => ()));
```

And the resulting error:

![screen shot 2016-03-03 at 11 11 57 pm](https://cloud.githubusercontent.com/assets/539839/13520472/6b95be00-e195-11e5-826b-f92fe331588d.png)

If I comment out the second callback in the Objective C implementation there is no error, so it seems that React Native can't handle multiple callbacks for some reason.

More info:
- React Native is version 0.19.0
- testing on iOS in simulator on a Mac computer

**Comment by ide** [comment]
Due to how RN works, exactly one callback must be called exactly once (for garbage collection reasons). We should make the error message clearer though (opened https://github.com/facebook/react-native/issues/6300).

If you need to send multiple signals from native to JS, use DeviceEventEmitter or NativeAppEventEmitter instead. Here is an example: https://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript

**Comment by crazy9code** [comment]
![screen shot 2017-08-03 at 2 46 27 am](https://user-images.githubusercontent.com/16454771/28895432-0c63561a-77f6-11e7-93bc-5b3948fa6bf2.png)

**Comment by crazy9code** [comment]
@objc(Utilities)
class Utilities: NSObject {
    
    var bridge: RCTBridge!
    
swift file code:    
@objc func getFontSize(_ index: NSNumber, _ callback: @escaping RCTResponseSenderBlock) -> Void {
        // see
        NSLog("Bridge: %@", self.bridge);
        NSLog("%@", index)
        callback([NSNull(),AppConstants.fontSizes.medium])
    }

javascript file 
NativeModules.Utilities.getFontSize(1, (textSize)=>{
        styles.TextStyleH1 = StyleSheet.flatten([styles.TextStyleH1, {
          ...Platform.select({
             ios: {
               fontFamily: "PFEncoreSansPro-Book",
               fontSize: textSize/PixelRatio.get()
             },
             android: {
               fontFamily: "pfencoresanspro_book",
               fontSize: textSize/PixelRatio.get(),
             },
           }),
         }]);
       }
     );

but it shows above error.

**Comment by crazy9code** [comment]
react-native: 0.46.3
Xcode 8.2.1
