### ISSUE TITLE
Chrome debugging from phone

### ISSUE THREAD

**Issue by StephaneP** [facebook/react-native#6291]
I've had some problems when deploying the react-native app on my and wanted to debug, the RCTWebSocketExecutor.m in the setup funciton:

    NSString *URLString = [NSString stringWithFormat:@"http://localhost:%zd/debugger-proxy?role=client", port];

I have to changed the localhost to my proper IP, I suggest that the code does the same as the port on this line, I might do a PR to add this in.

This is the only way I have right now to debug the app from my phone this is especially useful when debugging with the camera.

**Comment by grabbou** [comment]
Awesome, I've been wondering recently why this is not working as well! PRs welcome :)

**Comment by aleclarson** [comment]
+1

You might also want to change [this line](https://github.com/facebook/react-native/blob/f2438b440d410ca1aa3ca7d0544d6e000e29e774/React/Modules/RCTRedBox.m#L97) (if you tap the stack trace to open it in the text editor).

**Comment by brentvatne** [comment]
Hi all!

Let's make this actionable. The least friction approach to fix this is to update the docs to include @StephaneP and @aleclarson's changes, so let's do that.

**Implementation plan:** Add a note to running on device for iOS docs to indicate the changes that need to be made to `RCTWebSocketExecutor.m` and `RCTRedBox.m` to debug in Chrome on a device.

**Test plan:** Generate new project, follow the docs you wrote exactly, imagining that you are someone who is new to react native, and you should be able to debug and follow stack trace.

Great first ticket for anybody interested in contributing!

**Comment by Kureev** [comment]
Maybe it's a good time for `--device` flag? 
Example: `run-ios --device` or `run-android --device`

**Comment by aleclarson** [comment]
I agree with @Kureev here. Automating the process would be great for when my IP address randomly changes. And not having to dig in source code is nice for newbies. :stuck_out_tongue_closed_eyes:

**Comment by Kureev** [comment]
I'm currently working on this one with @kaphacius. We'll try to send a PR this evening.

**Comment by christopherdro** [comment]
@Kureev Maybe this helps.
https://github.com/wildlifela/react-native/commit/b2f079c121522f224e2f4ce4810c9bd5d86c495d

**Comment by Kureev** [comment]
@christopherdro hm, if that's already in the master, why we don't need this issue? It's no longer a manual step.

**Comment by Kureev** [comment]
@christopherdro we had a similar idea. The only difference is how you store an IP. Our proposal was to store it into `*.plist` using PlistBuddy, but `#define` statement also looks fine to me.

**Comment by Kureev** [comment]
@mkonicek @grabbou seems this issue can be closed (fix is already in the master).

**Comment by aleclarson** [comment]
@Kureev [The fix isn't in master yet.](https://github.com/facebook/react-native/blob/64d56f34b779de94f251f4b443463cbfe790912d/Libraries/WebSocket/RCTWebSocketExecutor.m#L54)

And we should add `LOCAL_IP_ADDRESS` to these places too:
- [RCTRedBox.m](https://github.com/facebook/react-native/blob/f2438b440d410ca1aa3ca7d0544d6e000e29e774/React/Modules/RCTRedBox.m#L97)
- [AppDelegate.m](https://github.com/facebook/react-native/blob/9ae3714f4bebdd2bcab4d7fdbf23acebdc5ed2ba/local-cli/generator-ios/templates/app/AppDelegate.m#L34)

**Comment by grabbou** [comment]
Nice, updated labels. Fingers crossed :)

**Comment by christopherdro** [comment]
@Kureev That commit was cherry picked to another fork of React Native. I never made a PR because I knew there were probably some other issues involved in getting it working completely.

@aleclarson I don't remember having any issues with android.

**Comment by aleclarson** [comment]
#6362 :checkered_flag: :+1: :beers:

**Comment by aleclarson** [comment]
It looks like there was already a similar PR: #6345 

Have anything to add to this, @frantic?

**Comment by aleclarson** [comment]
And there was already a huge conversation here: #4245

**Comment by frantic** [comment]
> Does Android have this same problem?

On Android there is a wonderful tool called `adb reverse` that forwards TCP ports from device to the computer. They don't have this problem because all connections to `localhost:8081` are tunneled (for emulator via virtual ethernet, for the physical devices over the wire). I have a prototype of a tool that works the same for iOS, I'll put up a PR soon.

**Comment by nevir** [comment]
> On Android there is a wonderful tool called adb reverse that forwards TCP ports from device to the computer.

It's still useful to have a baked in IP address when playing with your app over wifi (sure, you can do `adb` over it, but it'd be a lot nicer to have it Just Work)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/chrome-debugging-from-phone

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
