### ISSUE TITLE
[Errors] Improve the error message shown when an unregistered callback is invoked

### ISSUE THREAD

**Issue by ide** [facebook/react-native#6300]
See https://github.com/facebook/react-native/issues/6286. RN expects exactly one callback to be called exactly once, after which point it unregisters the callbacks to free memory. We should print a nicer error message when an unregistered callback is invoked.

**Comment by agiron123** [comment]
Is this issue still open? I see that the referenced issue is closed. 
Anyways, I'm a first time contributor that would love to help out. Is there anything that I should keep in mind while I familiarize myself with the code base and begin to put together a PR with associated unit tests?

**Comment by ide** [comment]
@agiron123 Hi, this issue is still open and thanks for offering to help. To answer your question, I would say the main thing to keep in mind is balancing the cost of maintaining the code with how valuable a feature is to everyone using React Native. For this issue specifically, I don't think that will be an issue -- a clearer error message in this case should be simple and strictly better than what we currently have.

**Comment by the4dpatrick** [comment]
Should this issue be closed since the PR was merged into master? fd2cf119b13af65dbaeed9c5a6a34cfd27ef06af
