### ISSUE TITLE
Packager fails with bundled html files with embedded svg. 

### ISSUE THREAD

**Issue by rawcreative** [facebook/react-native#6305]
Version: 0.21
Platform: IOS
Machine: OSX

After upgrading to 0.21, I cannot build my app as the packager fails with the error: `uncaught error Error: TypeError: invalid svg` There are no SVG's in the project, other than what is embedded in html files that are rendered via webview. Since they are svg's using the <symbol> property to define the paths it appears that the image-size module is throwing the error due to no declared width or height. Why is the packager trying to analyze svgs that are embedded in an html document?

**Comment by StephaneP** [comment]
Declare width and height In your svg document declaration usually fixes this.

**Comment by grabbou** [comment]
@rawcreative did the @StephaneP tip help you? :)

**Comment by kxxoling** [comment]
@StephaneP Works for me. To be cleared, the origin svg file looks like this:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><linearGradient ..../></svg>
```

Fixed after I changed it to:

```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" height="100%" width="100%"><linearGradient ..../></svg>
```

**Comment by ericvicenti** [comment]
Closing because there is a way to avoid this. Even though the packager shouldn't crash in this case, this issue is pretty low priority

**Comment by xahon** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 550 100" width='100%' height='100%'>`
not working for me  
```
4:56:09 PM: Failed building JavaScript bundle  
4:56:09 PM: TypeError: invalid svg
```

**Comment by adamski** [comment]
@xahon I think you need double not single quotes in an XML file.
