### ISSUE TITLE
RefreshControl layout breaks on device rotation

### ISSUE THREAD

**Issue by corbt** [facebook/react-native#6311]
When the device is rotated while a `RefreshControl` is active and refreshing, both its position and dimensions change in an unexpected way.

### Expected Appearance (portrait)
![simulator screen shot mar 5 2016 6 32 36 pm](https://cloud.githubusercontent.com/assets/176426/13549633/c7ea958c-e301-11e5-9895-508f7bceedf1.png)

### Appearance after rotating from portrait to landscape
![simulator screen shot mar 5 2016 6 32 40 pm](https://cloud.githubusercontent.com/assets/176426/13549642/e0fc15aa-e301-11e5-958f-611f15612d54.png)

### Appearance after rotating from landscape back to portrait
![simulator screen shot mar 5 2016 6 32 44 pm](https://cloud.githubusercontent.com/assets/176426/13549646/ee8317c8-e301-11e5-91b8-c337737403d6.png)

In all cases, once the `ScrollView` is touched/moved, the `RefreshControl` jumps back to its correct size/location. It's just in the period between a device rotation and the user's first interaction that the weird behavior appears.

To reproduce, just create a project with the following minimal content in `index.ios.js`:

```js
import React, {
  AppRegistry,
  Component,
  RefreshControl,
  ScrollView,
  Text,
} from 'react-native';

class App extends Component {
  render() {
    return (
      <ScrollView
        style={{ backgroundColor: 'green' }}
        refreshControl={
          <RefreshControl
            style={{ backgroundColor: 'gold' }}
            refreshing={true}
          />
        }
      >
        <Text>Dummy ScrollView content</Text>
      </ScrollView>
    );
  }
}

AppRegistry.registerComponent('RotateControl', () => App);
```

cc @janicduplessis

**Comment by janicduplessis** [comment]
Thanks @corbt for the detailed report! Seems like we need to invalidate the layout somehow on screen rotation, I'll take a look at this.

**Comment by corbt** [comment]
Fixed in https://github.com/facebook/react-native/pull/6359
