### ISSUE TITLE
Broken link on 'LinuxWindowsSupport.md'

### ISSUE THREAD

**Issue by DanielRosenwasser** [facebook/react-native#6314]
From [LinuxWindowsSupport.md](https://github.com/facebook/react-native/blob/a6a89fe4e08b6cf834df35cb176feac077234025/docs/LinuxWindowsSupport.md):

> If you hit a `ERROR  Watcher took too long to load` on Windows, try increasing the timeout in [this file](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/DependencyResolver/FileWatcher/index.js#L16) (under your node_modules/react-native).

However, [the code that should've been linked to](https://github.com/facebook/react-native/blob/5fa33f3d07f8595a188f6fe04d6168a6ede1e721/packager/react-packager/src/DependencyResolver/FileWatcher/index.js) has moved to [node-haste](https://github.com/facebook/node-haste/blob/c14390fbb616b59730dc2233cc4ddd8ddfb70d17/src/FileWatcher/index.js#L16).

I'd send a PR but, well, I'm not certain how dependencies have moved around.

**Comment by brentvatne** [comment]
cc @cpojer

**Comment by cpojer** [comment]
Ugh, we should at least update the documentation, but then the problem is that the developer has to dig into compiled output in `node_modules/node-haste/lib`. Is this a common issue? If yes, we should probably make this a configurable option for FileWatcher instances.

**Comment by brentvatne** [comment]
@cpojer - good point, perhaps this should be configurable. I'm not sure where this originated from and don't use windows, @DanielRosenwasser do you know if this is common?

**Comment by DanielRosenwasser** [comment]
Well I ran into it when starting to use React Native on Windows, and someone else documented it at some point, so it's probably sufficiently common.

For the record, I don't see node-haste as a dependency in version 0.21.0, so I don't know what the correct workaround is right now.

**Comment by cpojer** [comment]
For older versions that don't have node-haste, you can just update https://github.com/facebook/react-native/blob/5fa33f3d07f8595a188f6fe04d6168a6ede1e721/packager/react-packager/src/DependencyResolver/FileWatcher/index.js as you pointed out yourself in the initial comment.

**Comment by DanielRosenwasser** [comment]
> as you pointed out yourself in the initial comment.

D'oh. Forgot where I'd left off last night. :smile:
