### ISSUE TITLE
Remote Images are not fetched with existing cookies?

### ISSUE THREAD

**Issue by ramneekhanda** [facebook/react-native#6316]
Hi,
I am required to authenticate with server before i can fetch images and the server sticks some cookies for the further http requests. 

If i do this with browser it works but seemingly react Image fetch doesnt use existing cookies that have been set via fetch.

Here is what works:
1. Auth request using fetch - works and sets cookies on client side
2. Another request using fetch which needs authentication cookies set - works
3. Image which requests authentication cookies set - doesnt work

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by ramneekhanda** [comment]
hi @brentvatne, I dont think i can provide you a minimal example as the issue requires setting some cookies and needs some support on the server etc..

version of react native that i used is 0.21

OS i tested was primarily on iOS.

Will see when i get time, i will open a proper issue but would suggest to reopen this in the mean time.
