### ISSUE TITLE
[iOS] [ListView] the item's dealloc method would't be called in listview even with the removeClippedSubviews optimizations option

### ISSUE THREAD

**Issue by JansenLi** [facebook/react-native#6320]
I used ListView in my project. I also found the same memory problem with this  [issue](https://github.com/facebook/react-native/issues/499#issuecomment-128836161) . I turned the removeClippedSubviews option on. But I found the item's dealloc method would't be called. I wonder how the memory benefit from this property if the item is still in the memory.

**Comment by brentvatne** [comment]
Hi @JansenLi!

So it doesn't actually dealloc the view, but rather it removes the view from the underlying view hierarchy which allows images to be unloaded from memory. This is where the benefit comes from.

Hope that helps!
