### ISSUE TITLE
ES6 style import text inside of string breaks packager

### ISSUE THREAD

**Issue by jaulz** [facebook/react-native#6323]
```
// assign test to the string "import test from 'test'"
var test = `import test from 'test'`
```

It seems that as soon as you try to have a variable that contains the string to import a module the packer breaks. It's really easy to reproduce: https://rnplay.org/apps/FBm0LQ 
The obvious workaround is to have a variable that concatenates the string but does that make sure that there are no other side effects?

**Comment by satya164** [comment]
cc @martinbigio

**Comment by brentvatne** [comment]
Also cc @cpojer

**Comment by cpojer** [comment]
We don't use static analysis to analyze dependencies but rather just regex, for performance reasons. Unfortunately that means we can't ignore strings that look like imports/require's. As you suggested, the workaround is string concatenation.

**Comment by jaulz** [comment]
Thanks for the quick answers and good to know :)
@cpojer any hint where I can find that part of the code?

**Comment by cpojer** [comment]
All of this is in https://github.com/facebook/node-haste :)
