### ISSUE TITLE
“Unexpected end of input” exception when using Fetch API with Chrome debugging enabled

### ISSUE THREAD

**Issue by steveluscher** [facebook/react-native#6326]
This testcase uses the Fetch API to fetch some data from the network and display it. With Chrome debugging off, it renders the response as expected. With Chrome debugging on, the response is the empty string.

**Test case**:

```js
import React, {
  Component,
  Text,
  View,
} from 'react-native';

export default class SampleApp extends Component {
  constructor() {
    super();
    this.state = {
      text: 'Please wait. Loading.',
    };
  }
  componentDidMount() {
    fetch('http://jsonplaceholder.typicode.com/posts/1')
      .done(result =>
        result.text().done(text => this.setState({text}))
      );
  }
  render() {
    return (
      <View style={{margin: 30}}>
        <Text>{text}</Text>
      </View>
    );
  }
}
```

This is especially inconvenient when trying to load and parse a JSON response, since `JSON.parse('')` results in the following redbox:

<img width="374" alt="screen shot 2016-03-06 at 3 35 01 pm" src="https://cloud.githubusercontent.com/assets/13243/13558119/082ac572-e3b1-11e5-9aac-23705d3ee959.png">

React Native version: https://github.com/facebook/react-native/commit/ea882b6f161409ff439b93dfa146431944a42d9d
Tested on iOS Simulator only. Unsure if Android is affected.

**Comment by l-urence** [comment]
@steveluscher Updated the Libraries/Fetch/fetch.js to latest from https://github.com/github/fetch. This seems to fix this. Should I send a PR for this?

**Comment by skevy** [comment]
@l-urence yep, if that fixes it, please send a PR and tag both me and steve :)

**Comment by skevy** [comment]
@steveluscher i'm not sure when this started happening...seems odd though, given that people are constantly using `fetch` and I don't see that this error has been reported before.

**Comment by corbt** [comment]
Just as another data point, I got this error a few times on `master` a couple of days ago but it has since disappeared. I don't remember if I was debugging with chrome or not at the time though.

**Comment by davidaurelio** [comment]
Fixed in fd3a0ba781082a567d5713524fb269877baa0b1d

**Comment by paulinthought** [comment]
I was getting a similar issue and found that it was happening because I had mode: 'no-cors' set in fetch but cors was set on the server. Worth checking if it happens to anyone else.

**Comment by msmfsd** [comment]
@davidaurelio agreed - I had same error, I had cors set on my express server with middleware and no-cors on my fetch header.

**Comment by cubbuk** [comment]
@paulinthought @msmfsd just check the following link http://stackoverflow.com/questions/35169728/redux-fetch-body-is-not-use-with-no-cors-mode . Seems like this is an expected response when using `no-cors` mode: https://fetch.spec.whatwg.org/#concept-filtered-response-opaque

**Comment by msmfsd** [comment]
@cubbuk thanks for the clarification. I ended up always using cors on both ends and ensuring form data was serialized to the body with content type set to JSON:
```
const serialized = JSON.stringify(formData)
    const opts = {
      method: 'post',
      headers: {
        'Content-type': 'application/json'
      },
      body: serialized
    }
```

**Comment by GoMino** [comment]
@cubbuk thank you, I didn't know about filtered response :D

**Comment by GoMino** [comment]
@cubbuk thank you, I didn't know about filtered response

**Comment by ruoru** [comment]
I was getting a similar issue and found that it was happening because I get the fuck backend response is not JSON format. Worth checking if it happens to anyone else.
