### ISSUE TITLE
cannot find entry file ...UIExplorerApp.android.js in any of roots

### ISSUE THREAD

**Issue by tonytbl** [facebook/react-native#6331]
help me

I just clone https://github.com/facebook/react-native.git
then npm install
then ./gradlew :Example:UIExplorer:android:app:installDebug
then ./packager/packager.sh
then below...

I don't have any changes in codes,juest want to run it,and learn.

![qq 20160307100034](https://cloud.githubusercontent.com/assets/3360934/13559334/12b958e4-e44e-11e5-9ae4-b7c25da8b378.jpg)

**Comment by ck227** [comment]
any solution?

**Comment by janicduplessis** [comment]
Windows support is broken ATM on master :(. I'll got a PR fixing it, it should get merged soon. #6260

**Comment by ning-zhao** [comment]
@janicduplessis Have you solved this problem? I'm into same question.

**Comment by aboutqx** [comment]
Seems there is another problem when change scene in UIExplorer with this PR.

**Comment by janicduplessis** [comment]
I think the PR was based on a bad version of master, I rebased it and got merged so Windows support should work properly on master now. Feel free to reopen if im wrong :)

**Comment by janicduplessis** [comment]
@facebook-github-bot close
