### ISSUE TITLE
[Android] underlineColorAndroid somehow applies globally to all TextInput components

### ISSUE THREAD

**Issue by KarandikarMihir** [facebook/react-native#6332]
I have a component in search.js. Something like this-

```
<TextInput 
    placeholder={'Search keyword'}
    placeholderTextColor={'#cccccc'}
    style={styles.input}
    autoCapitalize={'none'}
    autoFocus={true}
    underlineColorAndroid={'#cccccc'}
>
</TextInput>

```

The style for given TextInput is this-

```
input: {
    padding: 5,
    height: 45,
    fontSize: 16,
    color: '#111111',
    marginBottom: 20,
    borderWidth: 1,
  },
```

![screenshot from 2016-03-07 10 57 13](https://cloud.githubusercontent.com/assets/17466938/13561502/b738ab9a-e453-11e5-86a5-95b2baa6c31e.png)

I have another TextInput placed in my sign-in page. 

```
<TextInput 
    style={styles.input} 
    value={this.state.username} 
    onChangeText={(text) => this.setState({username: text, error: ''})}
    autoCapitalize={'none'} 
    autoCorrect={false} 
    returnKeyType='next' 
    keyboardType={'email-address'}
>
</TextInput>
```

Style-

```

input: {
        padding: 4,
        height: 45,
        fontSize: 22,
        color: '#ffffff',
        marginBottom: 20,
        borderWidth: 1,
        textAlign: 'center'
    },
```

![screenshot from 2016-03-07 11 01 59](https://cloud.githubusercontent.com/assets/17466938/13561527/14f3434e-e454-11e5-8511-1e633557521a.png)

Why is underlineColorAndroid={'#cccccc'} from first TextInput is being applied to the second TextInput? Am I doing something wrong? Or is this a legitimate issue?

**Comment by brentvatne** [comment]
Example re-creating this on rnplay: https://rnplay.org/apps/_btSdw

**Comment by mihir-harbinger** [comment]
> Example re-creating this on rnplay: https://rnplay.org/apps/_btSdw
@brentvatne Your example is explicitly setting underlineColorAndroid for every TextInput individually. Whereas in my app, I am passing the same underlineColorAndroid prop for only one TextInput. It should not affect other TextInput, right?

**Comment by mihir-harbinger** [comment]
@brentvatne Thanks!

**Comment by evollu** [comment]
is anyone looking into this?

**Comment by ansmonjol** [comment]
+1

**Comment by ansmonjol** [comment]
Got the same here.

I'm using tcomb-native-form lib to generate my forms in the app, I have a template for textarea
```
  _areaTemplate(locals) {
    return (
      <View
        style={styles.marginVertical12}
      >
        <Text
          style={[styles.inputLabel]}
        >
          {locals.label}
        </Text>
        <View
          style={[styles.marginVertical12, {borderColor: 'grey', borderWidth: 1}]}
        >
          <TextInput
            onChangeText={(text) => this._onChangeText(text)}
            style={{textAlignVertical: 'top'}}
            underlineColorAndroid={'transparent'}
            multiline={locals.multiline}
            numberOfLines={locals.numberOfLines}
          />
        </View>
      </View>
    );
  }
```
Since I don't mount this component, all the inputs in my app have the "default" option on underline color (grey then kind of blue on focus), but once I've open this view and mount this component, all my inputs in the app have an underline transparent

**Comment by lacker** [comment]
Is this happening all the time when there are multiple inputs, or only sometimes? I can't get that rnplay link working.

**Comment by evollu** [comment]
If you have 2 inputs on the same screen and set underline color for only 1 of them. The color will be applied to both inputs

**Comment by mehulmpt** [comment]
Happened with my code as well. I applied underlineColorAndroid="transparent" and all of the input's underlines are gone.

**Comment by JoeRoddy** [comment]
Still happening for me, only applies globally once I visit the screen that sets one input as "underlineColorAndroid='rgba(0,0,0,0)' ".  Before visiting that view, all my inputs are fine.  Once I leave that view, all my inputs have the hidden underline applied to them.

**Comment by anthonylebrun** [comment]
+1 I can confirm that I'm having this exact same issue as well.

**Comment by reedspool** [comment]
+1 @facebook-github-bot This should not have been closed because that PR was closed. From what I understand that PR was closed without merging and the issue is still being looked into. This is the first hit on Google when searching for this so it should be reopened until it's really solved or a workaround is generated. I can't believe there's no solution or workaround yet for such a glaring issue.
