### ISSUE TITLE
Android how to support font strikethrough（line-through）

### ISSUE THREAD

**Issue by juncocoa** [facebook/react-native#6333]
Android how to support font strikethrough（line-through）
By textDecorationLine  property

**Comment by juncocoa** [comment]
`old Price：<Text style={{textDecorationLine :'line-through'}}>{'$ ' + oldPrice}</Text>`

**Comment by christopherdro** [comment]
Hey there! Closing this issue since it's a feature request. 
We are trying to keep GitHub issues strictly for bugs. 

You can try creating a ticket on [Product Pains](https://productpains.com/product/react-native/?tab=top) where community members can vote on this feature requests.

Thanks!
