### ISSUE TITLE
Support "selected" state icons in TabBarIOS.Item

### ISSUE THREAD

**Issue by ide** [facebook/react-native#635]
TabBarIOS doesn't yet support showing a different icon when its tabs are selected. Is anyone working on this? I might work on this in the near future otherwise.

**Comment by vjeux** [comment]
It does support it, selectedIcon prop. I just documented it much better, going out in the next sync

**Comment by ide** [comment]
You're right. I was looking at propTypes and it wasn't there but I see it in render().

**Comment by vjeux** [comment]
Yeah, this component was in dire need of cleanup/documentation
