### ISSUE TITLE
Packager error upgrading to 0.21 from 0.20

### ISSUE THREAD

**Issue by arunabha** [facebook/react-native#6350]
Upgrading from 0.20 to 0.21 causes an error in the packager. The project builds fine, but when the packager launches, it gives an error 

```bash
[3:05:34 PM] <END>   Building (deprecated) Asset Map (431ms)
Failed to build DependencyGraph: ENOENT: no such file or directory, open '/Users/agh/dev/schoolapp/mobile/SchoolApp/node_modules/react-native/ReactAndroid/src/androidTest/assets/ScrollViewTestModule.js'
Error: ENOENT: no such file or directory, open '/Users/agh/dev/schoolapp/mobile/SchoolApp/node_modules/react-native/ReactAndroid/src/androidTest/assets/ScrollViewTestModule.js'
    at Error (native)
~
Process terminated. Press <enter> to close the window
```

It might have something to do with the change in directory structure.

in 0.20

```bash
ls node_modules/react-native/
LICENSE       Libraries     PATENTS       README.md     React         React.podspec ReactAndroid  cli.js        jestSupport   local-cli     package.json  packager
```

in 0.21 
```bash
ls node_modules/react-native
LICENSE       Libraries     PATENTS       README.md     React         React.podspec android       cli.js        jestSupport   local-cli     package.json  packager
```

Is there a workaround ?

**Comment by christopherdro** [comment]
@arunabha It appears that the ReactAndroid folder is not being copied when you upgrade.
This is from some recent changes to the Android build process.

A update has already been pushed here.
https://github.com/facebook/react-native/commit/403176ae9332fb7c8beac339dd41cbb067f995fd

You can either update react natives package.json and run npm install again, or just copy the the directory  over manually. 

That should get things working again. Feel free to re-open the issue if the problem persists.
