### ISSUE TITLE
React Native RCT Networking.sendRequest got 6 arguments, expected 7

### ISSUE THREAD

**Issue by huyhva909** [facebook/react-native#6358]
Hi All, 
Please help me fix this error.
i have one application. I had run it by real device (Samsung galaxy s5).
I run all command it's work. But my device's screen is red with error.
Error is below:

RCTNetworking.sendRequest got 6 arguments, expected 7

invoke
BasejavaModule.java: 227

call
NativeModuleRegistry.java: 158

call
CatalystInstanceImpl.java: 428

run
NativeRunableDeprecated.java: -2

handleCallBack
Handler.java: 95

dispatchMessage
MessageQueueThreadHandler.java: 31

loop
Looper.java 145

what i need to do to fix this problem ? thank you guys !

**Comment by satya164** [comment]
You RN JS and Native code are out of sync. Run `react-native upgrade` in your project to fix the issue.

**Comment by bickerstoff** [comment]
I took a stab at adding it to stackoverflow.

http://stackoverflow.com/questions/35877867/react-native-rctnetworking-sendrequest-got-6-arguments-expected-7/35877868#35877868
