### ISSUE TITLE
Redux reducer different behavior on the same action

### ISSUE THREAD

**Issue by srlopez** [facebook/react-native#6360]
@gaearon @grabbou I need help on this question.
The dispachts on redux actions seem fine, but the reducer behaves differently if invoked from the parent component props or from the detail element props in ListView.

I don't know how to continue. 

All the code is in this repo [https://github.com/srlopez/test][1]

This is the reducer, all seems to be  ok

        //Reducer
        const reducer = (state = initialState, action = {}) => {
          switch (action.type) {
          case DECREMENT:
            return Object.assign({}, state, { ...state,
              idx: (state.idx-1 + state.list.length) % state.list.length
            })
          case INCREMENT:
            return Object.assign({}, state, { ...state,
              idx: (state.idx+1) % state.list.length
            })
          case ADD:
            return Object.assign({}, state, { ...state,
              list: [ ...state.list, { name: action.name, status: false }]
            })
          case UPDATE:
            return Object.assign({}, state, { ...state,
              list: [
                ...state.list.slice(0, action.idx),
                Object.assign({}, state.list[action.idx], {
                  status: !state.list[action.idx].status
                }),
                ...state.list.slice(action.idx + 1)
              ]
            })
          case REMOVE:
            return Object.assign({}, state, { ...state,
              list: [
                ...state.list.slice(0, action.idx),
                ...state.list.slice(action.idx + 1)
              ]
            })
          default:
            return state
          }
        }

And this is the App. I marked as //ERROR the lines with problems

    class App extends Component {
      constructor(){
        super();
        this.ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        console.dir(this.props);
      }
    
      itemMenu(idx, item){
        Alert.alert(
          item.name, 'options',
          [
     // ERROR in this two lines
            {text: 'update', onPress:() => this.props.update(idx) },
            {text: 'remove', onPress:() => this.props.remove(idx) },
            {text: 'cancel'}
          ]
        )
      }
    
      render () {
        const dataSource = this.ds.cloneWithRows(this.props.list);
    
        return (
          <View style={styles.container}>
    
            <View style={{ flexDirection: 'row', margin: 3}}>
              <Text style={[styles.button, { backgroundColor: 'orange' }]}>#{this.props.idx}  </Text>
              <TouchableHighlight
                onPress={() => {this.props.increment()}}>
                <Text style={styles.button}> [+] </Text></TouchableHighlight>
    
              <TouchableHighlight
                onPress={() => {this.props.decrement()}}>
                <Text style={styles.button}> [-] </Text></TouchableHighlight>
    
              <TouchableHighlight
                onPress={() => {this.props.update(this.props.idx)}}>
                <Text style={styles.button}> update </Text></TouchableHighlight>
    
              <TouchableHighlight
                onPress={() => {this.props.remove(this.props.idx)}}>
                <Text style={styles.button}> remove </Text></TouchableHighlight>
    
              <TouchableHighlight
                onPress={() => {this.props.add( 'Buy '+Math.floor((Math.random() * 100) + 1)+' apples')}}>
                <Text style={styles.button}> add </Text></TouchableHighlight>
            </View>
    
    
            <ListView style={{flex:1}}
                    dataSource={dataSource}
                    renderRow={(rowData, sectionID, rowID) =>
                      <Item rowID={rowID} rowData={rowData}
                        onPress={this.props.update}
                        onLongPress={this.itemMenu.bind(this)}/>
                    }
                  />
    
    
          </View>
        )
      }
    }
    
    class Item extends Component {
      render() {
        const rowData = this.props.rowData;
        const rowID = this.props.rowID;
        return (
          <View>
            <TouchableHighlight
    //ERROR on Press and LongPress
              onPress={() => { this.props.onPress( rowID ) }}
              onLongPress={() => { this.props.onLongPress( rowID, rowData ) }}>
              <View style={styles.container0}>
                <Text
                  style={[styles.txt, rowData.status && styles.up]}>
                  #{rowID}. {rowData.name}
                </Text>
              </View>
            </TouchableHighlight>
            <View style={styles.hr}/>
          </View>
        );
      }
    }

**Comment by satya164** [comment]
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)
