### ISSUE TITLE
Unable to resolve module path from ...

### ISSUE THREAD

**Issue by jaulz** [facebook/react-native#6365]
Hey. I get the famous red error box with the message "Unable to resolve module path from ... /*/*/node_modules/amdefine/amdefine.js". The path stated here though exists and I wonder what the issue could be. Until now I followed the described steps of the error:
1) upgrading to latest RN
2) watchman watch-del-all
2) rm -rf $TMPDIR/react-*
3) npm start -- --reset-cache
3) restart the packager

Any idea what else the issue could be?
Thanks a lot!

**Comment by Kureev** [comment]
Maybe I'll ask a very silly question, but are you sure you have `amdefine` installed?

**Comment by jaulz** [comment]
Yes, certainly - the path exists but the difference is that it was installed (and is required) via a dependency. Anyway what I wonder about is that the file path of the actual error message exist so there must be a check for a different file. Can you point out any potential checks that I can debug?

**Comment by grabbou** [comment]
> was installed (and is required) via a dependency

What is the dependency name?

**Comment by Hi-Rube** [comment]
if you filename is A.js  , but  you use ```import {some} from './a' ```  it will be error

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by laurent-descrivan** [comment]
If anyone have the same error: actually the missing module is named "path", required by amdefine. So in the sentence "Unable to resolve module path from ...", one must read as "Unable to resolve module $MODULE_THAT_HAPPENS_TO_BE_NAMED_PATH from ...".

The package amdefine require the "path" module provided by node.js. But in react-native's context, this native module does not exist. So as a simple workaround, just install a drop-in replacement:

`npm install --save path`

**Comment by ChenLi0830** [comment]
@laurent-descrivan Thank you very much for the post.

**Comment by FMGordillo** [comment]
@laurent-descrivan That little workaround it could solve you, but to me, first it was "path", then "fs", and it stays there (even If I do `npm i --save fs` it gives the module error)

**Comment by luanfelipecosta** [comment]
@FMGordillo  me the same! any solutions?

**Comment by MrLoh** [comment]
This is like trying to use node specific modules in the browser. React Native JS != Browser JS != Node JS, when you are looking for a package you need to make sure it will work in your environment. While most packages that work in the browser will work in react native, node specific packages will not work in react native. So you really wanna pay attention for which JS envrionment a package is.

**Comment by luanfelipecosta** [comment]
Hello, I find the solution for my problem. I am using https://github.com/mcnamee/react-native-starter-app, so when I commited my app to repo, it ignored .babelrc file, so the babel-dot-env module broke fs , I don't know exacly why. but no its Okay.
