### ISSUE TITLE
Issue to track 0.22 stability

### ISSUE THREAD

**Issue by bestander** [facebook/react-native#6366]
List of commits to cherry-pick into 0.22-stable branch
- [x] node-haste fix Windows compat fd816b1
- [x] live reload 2e9c888dcd9bf1dbfe62282caa9cf35b91630d0a 972395a7c9a72d746bd9baead803e5caa4c071a2
- [x] netinfo fetch  336dbe4
- [x] new npm publish script with CI ceb6bd5272f7d6971fef8ee9647213ba40e9fd9c
- [ ] fix HMR variable namings d0caf7e48b12e9a11185eb86e0a17017c9a3287c - not importing this
- [x] source maps fix bcb37c0b6ae6c319bc99b569a2253c30c3715a07
- [x] revert f538032888976f0199659645ddecf0650133cc62

**Comment by satya164** [comment]
For HMR, we need to do disable the HMR menu when Dev is disabled. I'll do it. Just mentioning here.

**Comment by janicduplessis** [comment]
#6260 When the node-haste stuff is resolved.

**Comment by martinbigio** [comment]
https://github.com/facebook/react-native/pull/6325 when it lands in a few minutes

**Comment by corbt** [comment]
https://github.com/facebook/react-native/pull/6373 fixes `NetInfo.fetch` returning `undefined`.

**Comment by bestander** [comment]
https://github.com/facebook/react-native/pull/6260 node haste

**Comment by satya164** [comment]
#6325 landed in 2e9c888dcd9bf1dbfe62282caa9cf35b91630d0a

**Comment by martinbigio** [comment]
@davidaurelio if we cherry pick https://github.com/facebook/react-native/pull/6260 wouldn't we need to pick https://github.com/facebook/react-native/commit/972395a7c9a72d746bd9baead803e5caa4c071a2 as well so that HMR doesn't break?

cc @@bestander

**Comment by martinbigio** [comment]
Lets merge https://github.com/facebook/react-native/commit/972395a7c9a72d746bd9baead803e5caa4c071a2

**Comment by corbt** [comment]
#6373 landed in https://github.com/facebook/react-native/commit/336dbe4c00484feec84037e1f23deaf895a9a11a

**Comment by bestander** [comment]
releasing 0.22.0-rc1 automatically with CI for the first time
The first 4 ticks were cherry-picked

**Comment by rclai** [comment]
Are you guys able to add in [this one](https://github.com/facebook/react-native/commit/0176ac488e57b77dfa82984c114901d884e90b53)?

**Comment by bestander** [comment]
it should be in RC already

**Comment by janicduplessis** [comment]
Will 0.22.0-rc1 be on npm? If it is I can tell users that had issues on windows to update to that.

**Comment by pthrasher** [comment]
Will this also contain all the various changes for relay compatibility?

**Comment by bestander** [comment]
yes, once this is green
https://circleci.com/gh/facebook/react-native/tree/0.22-stable
You can do `npm install react-native@0.22.0-rc1`

**Comment by bestander** [comment]
If right now `npm install react-native@next` has it then it will.

**Comment by bestander** [comment]
FYI react-native@0.22.0-rc4 has been published to npm.
It has the changes picked above.
If no more things to be picked till Monday we will release it as react-native@0.22.0

**Comment by bestander** [comment]
@pthrasher react-native@0.22.0-rc4 has react as peer dependency installed at the root of node_modules. This should allow Relay compatibility afaik.

**Comment by pthrasher** [comment]
@bestander thanks! :-)

**Comment by martinbigio** [comment]
need to cherry pick this one as well: d0caf7e48b12e9a11185eb86e0a17017c9a3287c

**Comment by cknitt** [comment]
Are you aware that rc4 seems to include different versions of css-layout for iOS and Android?

See https://github.com/facebook/react-native/issues/6447 and @vjeux's comments in https://github.com/facebook/react-native/issues/6237 and https://github.com/facebook/react-native/commit/f538032888976f0199659645ddecf0650133cc62.

It seems the fix from https://github.com/facebook/css-layout/pull/145 was merged for Android, but not for iOS. It would be great if you could get it merged for iOS, too, before releasing 0.22.0.

**Comment by daesan** [comment]
When I run 0.22.0-rc4, my app hangs at the following code.

`NSArray<NSHTTPCookie *> *cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL:components.URL];`
Libraries/WebSocket/RCTSRWebSocket.m line 290

I think this happens when my app tries to fetch remote javascript code. Are anyone else having this issue? Could someone guess what might be the problem?

**Comment by bestander** [comment]
A wild guess - JavaScript did not compile and server can't start.
Can you do 'npm start' in terminal?

**Comment by daesan** [comment]
Sure. I tried running the app several times and sometimes the following the server is accessed and other times the server is not even accessed.

I mean I see the following output on the console, only some of the times when I run the app.

`[10:58:15 AM] <START> request:/index.ios.bundle?platform=ios&dev=false`
`[10:58:15 AM] <END>   request:/index.ios.bundle?platform=ios&dev=false (34ms)`

**Comment by martinbigio** [comment]
@bestander need to cherry pick this one as well: https://github.com/facebook/react-native/commit/bcb37c0b6ae6c319bc99b569a2253c30c3715a07

**Comment by bestander** [comment]
Thanks for more details, @daesan.
This issue is created for tracking what needs to be cherry-picked into the release, i.e. things that are already in master branch.
In your case better create a standalone issue and help us track it and land a fix into master branch. Only then we could cherry-pick it into release.
0.22 is due to release today, so this fix is most likely coming to next RC this week.

**Comment by bestander** [comment]
@daesan, could you help us out and see if any of these issues are related? https://github.com/facebook/react-native/search?q=EXC_BAD_ACCESS&type=Issues&utf8=%E2%9C%93

**Comment by bestander** [comment]
0.22.0-rc5 is being released to npm.
Cherry-picking d0caf7e is a bit involved, delaying 0.22.0 release while resolving it

**Comment by bestander** [comment]
0.22.0 is released.

**Comment by daesan** [comment]
@bestander Got you. I thought this could be a release holding issue but it turns out that this only arises when JSX bundle is hosted on Linux server.

I created a new issue as you suggested. #6581 If someone has a clue about this error please talk about it there.
