### ISSUE TITLE
Can't set AndroidToolbar logo if set it to null before

### ISSUE THREAD

**Issue by farwayer** [facebook/react-native#6374]
If you set `logo` in `AndroidToolbar` to `null` at least once setting it to valid image don't work.
```xml
<ToolbarAndroid
    logo={this.props.isRoot ? this._logo : null}
/>
```

This works:
```xml
<ToolbarAndroid
    logo={this.props.isRoot ? this._logo : this._transparentImage}
/>
```

**Comment by mkonicek** [comment]
Hey @farwayer, mind sending a PR with a fix?

**Comment by farwayer** [comment]
Hmmm... You convinced me :) I like react native and I am happy to make it better. And I noticed that the problem with nav and actions icons also.
