### ISSUE TITLE
UICollectionView?

### ISSUE THREAD

**Issue by matthewga0** [facebook/react-native#638]
Anyone consider to make UICollectionView available in React Native?

* Implement in javascript based on **ScrollView**
* Export native UICollectionView from **UIKit**

Which one is better?

---
And I'm wondering why wouldn't React Native support `display: none`, this style makes the current component been removed from the superView, and `display:flex` add it back, this maybe useful to reduce memory usage I think.

**Comment by vjeux** [comment]
> And I'm wondering why wouldn't React Native support display: none

You can just remove it from render to achieve the same effect and reduce memory usage no?

**Comment by matthewga0** [comment]
@vjeux StyleSheet provides a high level way, manipulating the DOM is mostly like the low level way to control the views stack. As usual stylesheet, `display` is most useful rules, so I think React Native should implement this to give developers more choices.

**Comment by ranyefet** [comment]
+1 for UICollectionView, any estimate when it might be available?

**Comment by vjeux** [comment]
@ranyefet no one inside of Facebook is working on this right now and likely for the next few months. If you need this, I would encourage you to build it yourself or find someone to. The native component integration API should be all you need :)

**Comment by brentvatne** [comment]
@matthewga0 @ranyefet - if either of you would like to have a shot at this, ping me @notbrent in irc!

**Comment by matthewga0** [comment]
This one maybe works, but it's not the best solution for `flex` layout.
https://github.com/lucholaf/react-native-grid-view

**Comment by brentvatne** [comment]
@matthewga0 - thanks for sharing. Closing this issue - for now this will have to be a community-built module :smile:

**Comment by ovr** [comment]
+ 1

**Comment by jose920405** [comment]
try with 

https://github.com/lucholaf/react-native-grid-view
or 
http://stackoverflow.com/questions/29394297/listview-grid-in-react-native#29395686

**Comment by outaTiME** [comment]
+1
