### ISSUE TITLE
Rquiring unknown module <module> in RN 0.21.0, error when using .jsx instead of js.

### ISSUE THREAD

**Issue by kostandinangjellari** [facebook/react-native#6383]
After upgrading to react-native 0.21.0 and running the app **Rquiring unknown module <module> when using .jsx instead of js.** error message is shown.

When changing module extensions to .js it works ok.
Any idea ?

**Comment by janicduplessis** [comment]
.jsx entensions are not supported in RN, see this comment for the reasoning why. https://github.com/facebook/react-native/pull/5233#discussion_r49682279

**Comment by janicduplessis** [comment]
@facebook-github-bot expected
