### ISSUE TITLE
[Docs] Permalinks are undefined, or resolving to getting started page

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6384]
http://screencast.com/t/sus9HGNGxVrS

Heads up and adds resistance to adoption of RN.

**Comment by cosmith** [comment]
Thanks for the bug report! Do you have any idea where it comes from? Do you think you could maybe send a pull request to fix it?

@facebook-github-bot label Documentation

**Comment by cosmith** [comment]
@facebook-github-bot label Documentation

**Comment by skv-headless** [comment]
Fixed on master and 22rc. http://facebook.github.io/react-native/releases/0.22/docs/getting-started.html#requirements feel free to close

**Comment by cosmith** [comment]
Thanks!

**Comment by cosmith** [comment]
@facebook-github-bot close

**Comment by andresn** [comment]
Awesome, thanks!

**Comment by andresn** [comment]
@skv-headless I happened on the permalinks not working for this one (where did the PR go for your prior fix btw, perhaps I and others can follow suit when we catch these):
https://facebook.github.io/react-native/docs/mapview.html
