### ISSUE TITLE
[iOS][Text] Text textAlign is being overriden by iPhone's default NSTextAlignmentNatural

### ISSUE THREAD

**Issue by verilogz** [facebook/react-native#6386]
I am using RN 0.21 on Mac for iOS 8 & 9.

I am building an app that supports both RTL and LTR, and I have noticed that switching my phone language between RTL and LTR languages will override the following style attributes: textAlign, writingDirection, and flex.

Case 1: App should display English text, while the phone language is in Arabic, while <Text> component has the following style attributes:
{
        textAlign: "left",
        writingDirection: "ltr", //Added as an attempt to fix this bug
        flex: 1
}

Result 1: 
The <Text> component will align text according to the phone's default "NSTextAlignmentNatural" instead of my textAlign style attribute

Case 2: App displaying Arabic text while the phone language is in English, while <Text> component has the following style attributes:
{
        textAlign: "right",
        writingDirection: "rtl", //Added as an attempt to fix this bug
        flex: 1
}

Result 2: 
The <Text> component will align text according to the phone's default "NSTextAlignmentNatural" instead of my textAlign style attribute

Note:  If I set a flex value and text overflows, the <Text> component will not display the overflowing text, but if I remove the flex value, then text will overflow outside the <Text> component bounds

**Comment by mihir-harbinger** [comment]
How about using alignSelf: ["center", "flex-start", "flex-end"]?

**Comment by verilogz** [comment]
@mihir-harbinger  Using alignSelf makes the text overflow.

Here is a sample code
https://rnplay.org/apps/MVXW2A

If you run the code in the rnplay link on iPhone device/simulator with the app's language set to English, you get this:

![english_phone_lang](https://cloud.githubusercontent.com/assets/4957895/13668211/a548e69c-e6bb-11e5-81bc-a9af1ff975ae.png)

and if you run the same app while the phone language setting is set to Arabic, you get this:

![arabic_phone_lang](https://cloud.githubusercontent.com/assets/4957895/13668232/ce3455aa-e6bb-11e5-9c87-3a945c33d78a.png)

**Comment by mihir-harbinger** [comment]
@verilogz I tried to tweak around a bit. Nothing worked. Perhaps, post this on stackoverflow.

**Comment by verilogz** [comment]
It is a framework issue and I think it should be discussed here

**Comment by verilogz** [comment]
@mihir-harbinger I found the bug!

In React/Base/RCTConvert file
RCTConvertEnumValue method
Line `return value ?: defaultValue;` should be `return value ? value: defaultValue;`

**Comment by lacker** [comment]
There is new RTL support in RN as of https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps.html so I would try that out. I'm going to close this issue since I think it is stale.
