### ISSUE TITLE
Error when debugging on chrome

### ISSUE THREAD

**Issue by coolicer** [facebook/react-native#6394]
![qq20160309-0 2x](https://cloud.githubusercontent.com/assets/811078/13657265/dc0c1c02-e6a8-11e5-9212-a228748c44d6.png)
![qq20160310-0 2x](https://cloud.githubusercontent.com/assets/811078/13657266/dc0f64ac-e6a8-11e5-9ab1-b54c9604a486.png)

**Comment by Kureev** [comment]
Close all debug chrome tabs, restart packager and the error should go.
From what I see, you have a problem with running a debugger for you app on emulator. First error tells you pretty much what you need to do, the second one tells you that there is a DNS resolution failure(see [this](http://stackoverflow.com/questions/2897610/receiving-error-domain-kcferrordomaincfnetwork-code-2-when-attempting-to-read-fr)).

@facebook-github-bot stack-overflow

**Comment by Kureev** [comment]
^ this moment, when you don't have a permission to use a github-bot

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow

**Comment by Kureev** [comment]
@facebook-github-bot shack-overflow

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow
