### ISSUE TITLE
Is sharing ReactInstanceManager across multiple activities broken?

### ISSUE THREAD

**Issue by guyca** [facebook/react-native#6410]
I'm trying to share a ReactInstanceManager singleton across multiple activities. I've wired my ReactInstanceManager instance the my activities life cycle methods, so when `ReactActivity.onDestroy` is called, the `mReactInstanceManager` also gets destroyed and then `mCurrentReactContext` is set to null.

When opening a new activity and instanciating react views with the singelton manager everything works fine. **But** when I close the second activity with the back button, it's `onDestroy()` is invoked after `onResume()` of the first activity. Now when I try to interact with react views i get the following warning message:

`03-10 13:35:33.164 1627-1627/com.awesomeproject W/unknown:React: Unable to handle touch in JS as the catalyst instance has not been attached`

since `mReactInstanceManager.getCurrentReactContext()` in `handleTouchEvent()` returns null.

Is sharing ReactInstanceManager across activities/fragment still supported?

I'm running RN 0.20.0 on Android.
The repro scenario is very simple:
create a react activity (MainActivity). Open another activity from it, and click the back button to go back to the MainActivity.
results: any RN view in MainActivity can't be interacted with.

Logs:

```
03-10 10:46:10.043 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onCreate
03-10 10:46:10.101 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onStart
03-10 10:46:10.101 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onResume
// Opening second activity
03-10 10:46:48.320 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onPause
03-10 10:46:48.325 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onCreate
03-10 10:46:48.328 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onStart
03-10 10:46:48.328 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onResume
03-10 10:46:48.771 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onStop
// Back button clicked
03-10 10:47:29.772 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onPause
03-10 10:47:29.775 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onStart
03-10 10:47:29.775 10740-10740/com.awesomeproject V/RctActivity[MainActivity]: onResume
03-10 10:47:30.105 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onStop
03-10 10:47:30.105 10740-10740/com.awesomeproject V/RctActivity[SecondActivity]: onDestroy
```

**Comment by guyca** [comment]
@AndrewJack My activities extend ReactActivity, as intended, in this case you can't really prevent the call to `ReactActivity.onDestroy()`. 

Seems like this issue was introduced when [Add a base activity for React Native apps](https://github.com/facebook/react-native/pull/4827) was merged.

**Comment by AndrewJack** [comment]
Just make your own ReactActivity

**Comment by guyca** [comment]
hmm... I feel like that misses the whole point of having a base activity for react native apps.

**Comment by guyca** [comment]
@AndrewJack I wasn't aware of this, but according to the docs `onTerminate` [is called only on simulator](http://developer.android.com/reference/android/app/Application.html#onTerminate()).

>   This method is for use in emulated process environments.  It will
     never be called on a production Android device, where processes are
     removed by simply killing them; no user code (including this callback)
     is executed when doing so.

Also `ReactInstanceManager` has a `ReactContext` which in turn, keeps a [hard reference](https://github.com/facebook/react-native/blob/e018aa3100d93abf0e222cd70bbcbb6ab248eced/ReactAndroid%2Fsrc%2Fmain%2Fjava%2Fcom%2Ffacebook%2Freact%2Fbridge%2FReactContext.java#L44) to the Activity (in ReactContext) so not calling `onDestroy` will result in memory leaks.

**Comment by satya164** [comment]
@guyca You can just override the `onDestroy` method of `ReactActivity` to prevent destroying the instance manager.

**Comment by guyca** [comment]
@satya164 Thanks for the response. I might be experiencing a brain fart, but how does overriding `onDestroy` solves this? I would still have to call `super.onDestroy`

**Comment by satya164** [comment]
@guyca Yeah, missed that.

**Comment by AndrewJack** [comment]
@guyca Interesting about `onTerminate`. Once the process is destroyed everything is destroyed, so unless there is something major we need to tear down this shouldn't be an issue.

onResume sets the current activity, in [ReactInstanceManagerImpl](https://github.com/facebook/react-native/blob/0.21-stable/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerImpl.java#L486) & [ReactContext](https://github.com/facebook/react-native/blob/0.21-stable/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L136)

This wouldn't cause a leak as long as every new activity to go to calls onResume, which will set a new current activity. However, if an activity started that didn't call onResume, and the previous activity was destroyed then that activity would leak.

Note: `onResume` has been renamed to `onHostResume` in 0.22.

**Comment by guyca** [comment]
@satya164 are there any planes to address this issue? Should I make a pull request?

**Comment by satya164** [comment]
@guyca Sure. Ping me when you do.

**Comment by guyca** [comment]
@satya164 wonderful, will do.

**Comment by guyca** [comment]
@satya164 here's my take on fixing this issue. What do you think?

**Comment by mkonicek** [comment]
> Just make your own ReactActivity

I agree.

> ReactInstanceManager singleton across multiple activities

This seems like a scenario not many people run into (so far). Until it becomes common I don't think we need to support it in the base class.

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by tianzhijiexian** [comment]
Are you fix it?

**Comment by sneerin** [comment]
We have the same issue

**Comment by littlehome-eugene** [comment]
We have the same issue

**Comment by jkwangbest** [comment]
ReactInstanceManager singleton across multiple activities
+1  @mkonicek

**Comment by yurykorzun** [comment]
Still an issue and no clear solution to it.
