### ISSUE TITLE
[CLI] Make `react-native upgrade` prompt to delete `node_modules`

### ISSUE THREAD

**Issue by ide** [facebook/react-native#6426]
A big source of problems comes from the fact that `node_modules` gets into inconsistent states depending on how you installed the packages and I believe this leads to issues with people getting the wrong JS after an upgrade (e.g., mismatched number of arguments for bridged method class, `__fbBatchedBridge` errors).

We probably want to support unattended upgrades as well so here are a couple ideas:
- By default, `react-native upgrade` prompts to delete `node_modules`
- If it's not running in a TTY, it doesn't delete `node_modules`
- Expose CLI options: `--delete-node-modules` and `--keep-node-modules`. Or maybe something like `--delete-node-modules={1 | true}` if you want to delete the modules, and `{0 | false}` if you explicitly want to keep them around
  - In TTY mode, specifying the option suppresses the prompt

cc @martinbigio

**Comment by satya164** [comment]
Right now, before running `react-native upgrade`, you have to do `npm install react-native@version` (which is quite slow). Deleting `node_modules` after that means you need to repeat the same thing again.

May be introduce a `react-native upgrade --version 0.22` command which prompts the deletion?

**Comment by grabbou** [comment]
@satya164 I don't actually use upgrade, but I am surprised it is not doing the installation process itself. Sounds that it would be reasonable to move it there & prompt to delete node_modules as @ide suggested.

**Comment by Kureev** [comment]
Can you help me guys to make this issue actionable? I'd like to pick it up.

**Comment by ide** [comment]
With Yarn this should be less of an issue. So my recommendation is for `react-native upgrade` and other RN tools to check if `yarn` is defined in `PATH` and use it if it is available. Then people should install Yarn and then we don't need to worry about npm's nondeterminism as much any more.

**Comment by lacker** [comment]
@mkonicek is working on the upgrade flow, so let me hereby bring this issue to his attention.

**Comment by ericvicenti** [comment]
cc @bestander who has more context on this issue. But I'm closing it because I think the `node_modules` inconsistency problems have largely been addressed
