### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by jcsjohnson** [facebook/react-native#6427]
![Uploading Simulator Screen Shot 11 Mar 2016, 7.18.23 PM.png…]()
I am getting this error on only one of my projects. I loaded the project on to my phone yesterday and today I am getting the error for only this one project. My other projects do not get this error. The odd thing is that the power went out last night and my computer restarted while the project in question was running. Has anyone heard of anything like this happening?

React-native - 0.21.0
NPM 3.8.0

I've checked my info.plist and it is accurate and same as my other projects. It was working fine from last night and nothing changed from then until when I tried today..... so confusing.

simulator screen shot 11 mar 2016 7 18 23 pm

**UPDATE
I rebuilt my project only including source and required components in the new build and it fixed... until it hit midnight. Then the error is back. When I run the project I get a green bar at the top of the simulator that says "Loading from 192..." then after about a minute I get the error "Could not connect to development server..."

What could possibly be causing this?

**Comment by gre** [comment]
Are you running the react-native dev server. what does it logs?

Can you check that your watchman is up to date

**Comment by jcsjohnson** [comment]
Thanks for reply @gre my watchman and everything else is up to date. What is the dev server?

I rebuilt my project multiple times, the last time in the most basic way and was able to get it going.

I think I solved part of the problem, which is that when the power went off the last digit of my IPv4 changed from .9 to .7 and in my AppDelegate.m I had my .9 IP already set in place of 'localhost' so I could use on my iPhone. But it still did not make sense because other projects with the .9 IP could still run and I was not trying to run it on my iPhone but rather on the simulator. Additionally I had turned my iPhone wifi off because no longer using it for testing, which I think created part of the problem because the last time I had been using it was while connected to my iPhone.

Summary:
IPv4 changed after power went out
IPv4 had to be updated in AppDelegate.m
iPhone wifi had to be turned back on (even though using simulator)

**Comment by gre** [comment]
by dev server, I mean the development server that starts when running `npm start` or `react-native start`.

Your issue sounds like an IP/network related thing but probably not related to React Native.

@facebook-github-bot stack-overflow

**Comment by jcsjohnson** [comment]
Ya that's what seems most likely, but it did not make sense that other projects were working.

**Comment by gre** [comment]
I just reached a similar bug. I don't know where it came from, but basically it looks like at some point the phone never succeed to reach the dev server, testing in my local network.

**Comment by gre** [comment]
this happens since i've upgraded to RN 0.21. not sure if it's related

**Comment by jcsjohnson** [comment]
what about if you use the simulator? Is there any issue?

**Comment by gre** [comment]
no issue with the simulator. it just happened once on my phone at the moment
