### ISSUE TITLE
Flow 0.22 broken for lib consumers (identifier `ReactElement`. Could not resolve name)

### ISSUE THREAD

**Issue by corbt** [facebook/react-native#6428]
Currently, the React Native codebase relies on the `ReactElement` and `ReactComponent` flow definitions that were previously included as part of Flow but have now been renamed to `React.Element` and `React.Component`. (See https://github.com/facebook/flow/issues/1438).

This works in the RN codebase because there is a `flow/react.js` file that aliases `ReactElement` to `React$Element` and does the same for `ReactComponent`. Unfortunately this `flow/` directory is not exported in the npm bundle, and isn't referenced in the generated `.flowconfig`. As a result library consumers get a ton of `identifier ReactElement. Could not resolve name` errors after upgrading to flow 0.22.

I think the best solution would be to export the `flow/` directory in the npm package, and then reference it in the generated `.flowconfig`. That way future definitions that React Native relies on will also be covered.

Long term, it would also be good to switch to React.Element and React.Component.

I'll put together a PR covering this if I get a chance to today.

**Comment by satya164** [comment]
Should be easy to switch to `React$Element` and `React.Component` instead, right? Someone could write a codemod to do that.

**Comment by corbt** [comment]
True, good idea. I think that's kind of orthogonal with this issue though. I doubt this will be the last time that something in the `react-native/flow/` directory will be necessary to get decent flow analysis in projects that consume RN.

**Comment by satya164** [comment]
@corbt Yeah, currently I had to completely ignore the `react-native` directory to get Flow working in my project. Which sucks :(

**Comment by corbt** [comment]
@satya164 is that with flow 0.22? With older versions I've been using it without errors. Are you using the `react-native upgrade`-generated .flowconfig?

**Comment by satya164** [comment]
@corbt Never got to error-free stage actually. Following is my current Flow config.

```
[ignore]

# Ignore test files
.*/__tests__/*
.*/tests/*
.*/test/*

# Some modules have their own node_modules with overlap
.*/node_modules/node-haste/.*

# Ugh
.*/node_modules/babel.*
.*/node_modules/babylon.*
.*/node_modules/invariant.*

# Ignore react and fbjs where there are overlaps, but don't ignore
# anything that react-native relies on
.*/node_modules/fbjs/lib/Map.js
.*/node_modules/fbjs/lib/Promise.js
.*/node_modules/fbjs/lib/fetch.js
.*/node_modules/fbjs/lib/fetchWithRetries.js
.*/node_modules/fbjs/lib/ExecutionEnvironment.js
.*/node_modules/fbjs/lib/isEmpty.js
.*/node_modules/fbjs/lib/crc32.js
.*/node_modules/fbjs/lib/ErrorUtils.js
.*/node_modules/fbjs/lib/Deferred.js
.*/node_modules/fbjs/lib/PromiseMap.js
.*/node_modules/fbjs/lib/resolveImmediate.js

# Flow has a built-in definition for the 'react' module which we prefer to use
# over the currently-untyped source
.*/node_modules/react/react.js
.*/node_modules/react/lib/React.js
.*/node_modules/react/lib/ReactDOM.js

# Lots of Flow errors from React Native, ignore for now
.*/node_modules/react-native/.*

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
interfaces/

[options]
module.system=haste

munge_underscores=true

module.name_mapper='^[./a-zA-Z0-9$_-]+\.jpg$' -> 'RelativeImageStub'
module.name_mapper='^[./a-zA-Z0-9$_-]+\.png$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```

**Comment by corbt** [comment]
Yeah there are lots of issues with RN dependencies and some modules, but they're all covered by the [ignore]s in the provided `.flowconfig`. I recommend running `react-native upgrade` in your project (you can just revert all the updates to files you don't want to change) and then inspecting the diff to your `.flowconfig` and adding back in whatever you need. If you have flow < 0.22 it should just work. If you have flow >= 0.22 you'll need this PR before running `react-native upgrade`: https://github.com/facebook/react-native/pull/6430.

**Comment by satya164** [comment]
@corbt I'm on Flow 0.22.1, so will wait :)

**Comment by shauns** [comment]
To share -- If you'd like to use RN 0.22-stable with Flow 0.22.1, then I have a suitable branch: https://github.com/shauns/react-native/tree/0.22-stable-with-flow-0.22.1
