### ISSUE TITLE
integrate native chart display incorrectly

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#6440]
hey there, I try to integrate smart [native iOS charts](https://github.com/danielgindi/ios-charts) to my react native project, but I found that when I moved on chart view while displaying messy, like below.

I ask the same question [here](http://stackoverflow.com/questions/35972015/integrate-native-chart-display-incorrectly) with relevant code, maybe someone could give my some suggestion.

thanks for your time.

regards.

![chart](https://cloud.githubusercontent.com/assets/7262199/13733377/1dd13592-e9cd-11e5-8639-088544845d51.png)

**Comment by jaygarcia** [comment]
Very silly question: Does the exact same thing happen when you render your ObjC implementation outside of React Native?

**Comment by L-Jovi** [comment]
@jaygarcia  I don't think it's silly question but I solve it now, sorry to trouble.
