### ISSUE TITLE
Unable to change path of index.android.js

### ISSUE THREAD

**Issue by shivangbtech** [facebook/react-native#6444]
I need to change path of index.android.js, By default it access the file from root of project created (created by react native), I want to put it in asset folder of android structure.

**Comment by grabbou** [comment]
I think you should override this method https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java#L60 and return appropriate path to your index in new location.

**Comment by shivangbtech** [comment]
I already tried this, but as you suggest, I'll again check it out. I'll get back to you soon.

**Comment by shivangbtech** [comment]
Yes its working, there was some problem in path last time.
