### ISSUE TITLE
[WebView] onNavigationStateChange doesn't have the notion of the real state

### ISSUE THREAD

**Issue by lc1983** [facebook/react-native#645]
Due to the natural design of UIWebView, the webViewDidStartLoading and webViewDidFinishLoading delegate will be called multiple times if the target web page has multiple frames (Related discussions on StackOverFlow and possible solutions: http://stackoverflow.com/questions/1842370/uiwebview-didfinishloading-fires-multiple-times). Current design of the onNavigationStateChange only exposes a "navState.loading" state as the indicator of the state but that property could always be false. Suggest to expose another state to match the webViewDidStartLoading, webViewDidFinishLoading and webView:didFailLoadWithError: or modify the onNavigationStateChange to wrap truly state on whether the web page has finished loading all frames on the web page.

**Comment by brentvatne** [comment]
cc @nicklockwood

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/webview-onnavigationstatechange-doesnt-have-the-notion-of-the-real-state
