### ISSUE TITLE
WebView demo not working

### ISSUE THREAD

**Issue by TeodorKolev** [facebook/react-native#6450]
WebView Demo did not working. Both Android and iOS shown same error: Module AppRegistry is not a registered callable module. Do I miss something, or demo is just incomplete/bugged?

**Comment by christopherdro** [comment]
@TeodorKolev Are you taking a look at the examples from the UIExplorer demo or the docs on the website?

If your copying the entire example into your own project your going to have to make sure that your app still calls `AppRegistry`. Take a look at the index files on a fresh init of RN and you'll see how AppRegistry is being used.

More info can be found here:
https://github.com/facebook/react-native/commit/ec9efb8a01ce59c7a594df5ca4c314a208ba1902

**Comment by TeodorKolev** [comment]
I have copy/paste to index.android.js. What should I change to make it working?
