### ISSUE TITLE
[Android] Translucent StatusBar bugs ScrollView

### ISSUE THREAD

**Issue by julianocomg** [facebook/react-native#6455]
When I set the the StatusBar translucent prop to true, the content of the app draws behind the status bar (as expected), however all the scroll views lost the capability of auto scroll to a focused input. When I remove the translucent prop, the app works as expected. (I'm using RN 0.21)

**Comment by janicduplessis** [comment]
Could you try 0.22-rc see if it still happens? I changed the implementation a bit and I think I know why it happens and should not anymore.

**Comment by julianocomg** [comment]
@janicduplessis I'm still getting the same bug on 0.22.0-rc :confused:

**Comment by janicduplessis** [comment]
Aww, I'll look into it.

**Comment by zarnifoulette** [comment]
Hello here, 

I have the same problem in react-native 0.51. Did you fix this ?
