### ISSUE TITLE
[UiExplorer Example] "No script URL provided" when running on phone

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6458]
Red screen of death: 
http://screencast.com/t/VqeuVMwPSM

Commented out:
  // sourceURL = [NSURL URLWithString:@"http://localhost:8081/Examples/UIExplorer/UIExplorerApp.ios.bundle?platform=ios&dev=true"];

Tried both of these:
  sourceURL = [NSURL URLWithString:@"http://192.168.1.92:8081/Examples/UIExplorer/UIExplorerApp.ios.bundle?platform=ios&dev=true"];

sourceURL = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

My react versions:
  "name": "react-native",
  "version": "0.0.0-master",

@brentvatne tried:
 $: git clean -dfx
 $: npm i && npm start
Product > Clean in Xcode
Then recompiling

UIExplorer runs fine in simulator and my other project runs fine in simulator and phone.

Please advise and thank you in advance for your time!

**Comment by turboza** [comment]
@andresn I got the same error too, it occurred because no generated javascript bundle inside the project. So you just need to do according to the comments in AppDelegate.m:66

While the server is running, 
```
$ curl 'http://localhost:8081/Examples/UIExplorer/UIExplorerApp.ios.bundle?platform=ios' -o main.jsbundle
```
then add the `main.jsbundle` file to your project.

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by andresn** [comment]
ah, thanks @turboza!

**Comment by soualid** [comment]
Thank @turboza, just in case it might help someone, I needed to add the `/js` to the command line path to have it working : 

    $ curl 'http://localhost:8081/Examples/UIExplorer/js/UIExplorerApp.ios.bundle?platform=ios' -o main.jsbundle

**Comment by jamesjenner** [comment]
Shouldn't the README be updated on the instructions for running on a device? The current README for UIExplorer doesn't mention this and just points the reader to https://facebook.github.io/react-native/docs/running-on-device-ios.html. The docs page for running on device doesn't mention anything about generating the bundle.

Out of curiosity, is this a general issue with building for devices  or specific to the UIExplorer project? I presume that `react-native init <project>` would normally create the missing bundle?
