### ISSUE TITLE
Jpg embeds not supported

### ISSUE THREAD

**Issue by debreuil** [facebook/react-native#646]
Using 0.3.4 I am able to embed png files with the {image!...} syntax, however if there is a jpg referenced there it will crash with the Requiring unknown module {image!...} error. A workaround for now is to rename the jpg extension to png (no need to convert the actual file format, just the name). 

It seems jpg files do no get written into the encoding format, at least they don't appear in the debugger. To reproduce I'm able to just convert an image in the UIExplorer sample to a jpg and re-embed it.

**Comment by jpincheira** [comment]
Just checked it again, still happening. Current solution is still renaming from `jpg` to `png`.

Thanks @debreuil

**Comment by amasad** [comment]
This landed internally, should land here next sync.

**Comment by amasad** [comment]
This should be landed. Reopen if it doesn't work https://github.com/facebook/react-native/blob/72c5e5d981a21ede12dcd76de5ca22a398c8bcaf/packager/packager.js#L203

**Comment by yelled3** [comment]
@amasad I'm using version `"0.4.2"` and this is still happening...
WDYT?

**Comment by dvine-multimedia** [comment]
I have the same issue with 0.4.4

**Comment by amasad** [comment]
Try the comment here https://github.com/facebook/react-native/issues/521#issuecomment-104731068

**Comment by andersryanc** [comment]
Same thing here, using react-native 0.11.0. Maybe the docs should be updated to mention this issue [static resources](https://facebook.github.io/react-native/docs/image.html#adding-static-resources-to-your-ios-app-using-images-xcassets) (similar to how there is a note about needing to rebuild after adding new images)?

![screen shot 2015-09-22 at 9 36 07 am](https://cloud.githubusercontent.com/assets/689046/10024732/7e0c6a60-610d-11e5-9f70-2d66f4c3dc35.png)
