### ISSUE TITLE
MapView annotations displayed is less than setted

### ISSUE THREAD

**Issue by chieryw** [facebook/react-native#6461]
Show items in mapView,and change type by segmentControl.
When changed selected，the different type items will show in mapView.
But,i found the item displayed is less than setted.

Problems cropped up in RCTMapAnnotationView, the function of 

```
- (void)setContentView:(UIView *)contentView
{
[_contentView removeFromSuperview];
_contentView = contentView;
[self addSubview:_contentView];
}
```

The pointer of _contentView may be equal to the pre added of contentView. When remove from superview,the pre added of contentView will be removed.

Fixed function is 
```
- (void)setContentView:(UIView )contentView
{
while (self.subviews.count) {
UIView child = self.subviews.lastObject;
[child removeFromSuperview];
}

_contentView = contentView;
[self addSubview:content];
}
```

[pullRequest](https://github.com/facebook/react-native/pull/6460)

**Comment by brentvatne** [comment]
Hi there! No need to have an open issue for this in addition to the pull request :) @chieryw -- can you answer nicklockwood in his response to your pull request? Thanks!
