### ISSUE TITLE
[WebView] white backgroundColor on load

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#6465]
When I load or reload app with WebView I got white background before page loads
Video — http://take.ms/PddHe
version 0.22.0-rc
iOS, Mac

**Comment by jaygarcia** [comment]
That's normal practice.

A good thread: http://stackoverflow.com/questions/2491654/how-to-control-the-color-of-a-uiwebview-before-contents-load

**Comment by dionbaby** [comment]
There is a trick I used to solve this issue.
(1) Embed the webview inside a view (like your theme color, black used here)
Set the webview opacity as 0 initially

`return (
            <View style={{flex:1, backgroundColor:'black'}}>
                <WebView style={{opacity:this.state.webViewOpacity}}
                         scalesPageToFit={false} source={{html: this.state.content}}/>;
            </View>
        );`

(2) Load HTML content from server / local page async, and then
`this.setState({content: htmlContent})`

Meanwhile, do not change webViewOpacity to 1 immediately! 
Wait for a few milliseconds (tune it by yourself XD).
`await sleep(500);
this.setState({webViewOpacity: 1});`

This allows some time for rendering process, and avoid the white flickering.
In the meantime, the UI will keep the theme background color (black here) until content presents.

(3) A very useful sleep function, used in (2):
` sleep(ms)
  {
       return new Promise(resolve => setTimeout(resolve, ms));
  }`

Hope it helps!
