### ISSUE TITLE
Iphone SDK not found by Xcode build

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6467]
So I have a fresh install of React Native, using Xcode 7.3 beta (7D162j, latest). Everything works upon build, except for a warning in which a test file dependency symlink is pointing to a none existent path:

ld: warning: directory not found for option '-F/Applications/Xcode-beta 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/Developer/Library/Frameworks'

When the closest thing I have locally is:
/Applications/Xcode-beta\ 2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/Library

Note: lrwxr-xr-x ... iPhoneOS9.3.sdk -> iPhoneOS.sdk

I'd Stackoverflow this, tried looking for the answer there, but the best one was to remove the test dir, which is lame. Either way, I think this might be a an issue with the react init not being turnkey enough to deal with this. Please advise and thank you in advance for your time!

**Comment by jaygarcia** [comment]
This doesn't seem to be a react-native specific question.

It's an Xcode install issue: 

Two good threads that might help:
http://stackoverflow.com/questions/15565765/iphonesimulator-sdk-not-found-error-in-xcode

https://forums.developer.apple.com/thread/3729

**Comment by andresn** [comment]
Warning went away it seems, played off of best answer here:
http://stackoverflow.com/questions/30810874/getting-framework-related-warning-in-xcode-7-0
Which requires:
- Going to [Project Name] > Targets > [Project Name]Tests > Search Paths > 
- Expanding Framework Search Paths
