### ISSUE TITLE
Picker automatically selects first value!

### ISSUE THREAD

**Issue by DHidee66** [facebook/react-native#6472]
Hi,

The picker on Android calls `onValueChange` when it is rendered and picks automatically the first value.
I now put the first Item in every picker with an empty value but not the best solution.

Thank You!

**Comment by brentvatne** [comment]
@bestander - is this intentional? perhaps we can just document if so

**Comment by bestander** [comment]
I think @mkonicek made it cross platform.
Is it intentional, Martin?

**Comment by mkonicek** [comment]
This might be the expected behavior for now although not idea. I don't think this affects any fb products. We rely on the community to fix issues that people discover. Can you send a PR with a fix?

**Comment by mkonicek** [comment]
Also, can you send a gif/video showing this in the UI Explorer? When working on the picker I think I remember the first value always being selected but not sure. Maybe we never had the need to have an empty picker before?

**Comment by mkonicek** [comment]
@facebook-github-bot anwered

**Comment by DHidee66** [comment]
Let's not bother @facebook-github-bot .
