### ISSUE TITLE
NavigationExperimental freezes on Android as seen in UIExplorer

### ISSUE THREAD

**Issue by jgibbons** [facebook/react-native#6474]
Hello,

In our app we can't get NavigationExperimental to perform smoothly. We've also witnessed the same problem on the UIExplorer example.
The NavigationCompositionExample in UIExplorer freezes and stops working after pushing multiple views on Android. We noticed that this has only been a problem in the current release, while previous releases work fine. 
Has anyone experienced similar problems yet with the NavigationExperimental?

@ericvicenti

**Comment by s7song** [comment]
+1

**Comment by apontious-gl** [comment]
I am seeing this. See the duplicate issue I just closed about it.

**Comment by jgibbons** [comment]
I just updated to the latest git version of react-native and everything seems fine. :)

**Comment by bosung90** [comment]
I am still seeing issues with NavigationExperimental when compiled from Windows.
Using PerfMonitor I can see JS framerate drops to 10~20 when pushing a card and -2 to 0 when pushing multiple cards.

**Comment by apontious-gl** [comment]
Yeah, I'm still seeing hangs and crashes running on a Galaxy S6, via a Mac, using 0.22.2.
