### ISSUE TITLE
TextInput onChangeText incorrect on Android emulator

### ISSUE THREAD

**Issue by jonesdar** [facebook/react-native#6483]
Create a TextInput with an onChangeText callback and run on an Android emulator.
Click on the TextInput and use 'adb shell input text blah' to send input.

The text always appears visually in the TextInput but very frequently the onChangeText callback gets called with some trailing chars missing in its text parameter.

Note that the onTextInput callback _does_ get the updates and shows what onChangeText is missing - see logcat output below.

This causes problems with automated tests (it also shows up when using tools like Appium).

React Native version 0.21.0 running on Mac OS X Yosemite 10.10.5.

    adb shell input text hello

I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 0, start: 0 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'h' }
**I/ReactNativeJS( 2211): TextInput onChangeText text=he**
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 1, start: 1 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'e' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 2, start: 2 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'l' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 3, start: 3 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'l' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 4, start: 4 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'o' }

    adb shell input text world

I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 5, start: 5 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'w' }
**I/ReactNativeJS( 2211): TextInput onChangeText text=hellowo**
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 6, start: 6 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'o' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 7, start: 7 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'r' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 8, start: 8 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'l' }
I/ReactNativeJS( 2211): TextInput onTextInput event=
I/ReactNativeJS( 2211): { target: 25,
I/ReactNativeJS( 2211):   range: { end: 9, start: 9 },
I/ReactNativeJS( 2211):   previousText: '',
I/ReactNativeJS( 2211):   text: 'd' }

**Comment by mkonicek** [comment]
Hey @jonesdar, can you send a PR with a fix? We're a small team and rely on the community to fix issues that don't affect fb apps.

**Comment by mkonicek** [comment]
Does it only happen when using `adb` or also when typing manually?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-onchangetext-incorrect-on-android-emulator

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.
