### ISSUE TITLE
[WebView] reload not working when renderError

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#6490]
1. I have no Internet connection and try to render WebView
2. Got error view with renderError implementation
3. Turn on Internet connection and try to reload component (`@refs.bridge.reload()`)
4. Nothing happened

0.22.0-rc, iOS, Mac

**Comment by stereodenis** [comment]
WebView has state.viewState == 'ERROR', so any manipulations with reload() make no sense

**Comment by andreassavva** [comment]
Hey, did you find a solution to this? I'm getting the same thing and using refs didn't work.
