### ISSUE TITLE
[iOS] writingDirection render not as expected

### ISSUE THREAD

**Issue by seph14** [facebook/react-native#6496]
![t1](https://cloud.githubusercontent.com/assets/6417336/13837677/ae44c206-ec48-11e5-8b88-18b11eae47a6.png)
![t2](https://cloud.githubusercontent.com/assets/6417336/13837679/aec11784-ec48-11e5-91e9-ade2732657ba.png)

Please take a look at the screenshots above. So same text, the first is using default writingDirection, the second one is using writingDirection:'rtl'. Notice that the . on the third line is rendered in wrong position, it should still be on the right side of Chain not left.

**Comment by jaygarcia** [comment]
To help expedite issue resolution, please include (well formatted) code.

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-7** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
