### ISSUE TITLE
[Android] Image module not loading network image?

### ISSUE THREAD

**Issue by prtkkmrsngh** [facebook/react-native#6498]
I'm using react native version 0.21.0 but also tried by degrading to 0.20.0 but no luck...

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by prtkkmrsngh** [comment]
Yes, I'm using it like this
`<Image
  style={{width:50, height:50}}
  source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
/>`
Rebuilding complete project seems to work but now only jpg image request being fired not png...

**Comment by charpeni** [comment]
@facebook-github-bot label android

I just tried this with png and jpg, it works on react-native 0.21 and Android 5.

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by grabbou** [comment]
Are you sure the source you are loading does not have a redirect?

**Comment by satya164** [comment]
Can you post an example on rnplay.org?

**Comment by prtkkmrsngh** [comment]
@grabbou no redirect.
This seems to be system issue. Working fine on another system.
Closing this issue. Thanks for your reply guys
