### ISSUE TITLE
Failed to establish session

### ISSUE THREAD

**Issue by guanMac** [facebook/react-native#6499]
When I used 'react-natvie run-androi', it showed that:

:app:installDebug
Installing APK 'app-debug.apk' on 'MI 4W - 6.0.1'

Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to establish session

my android phone is XIAOMI 4 , 6.0.1

**Comment by Kureev** [comment]
@facebook-github-bot duplicate #2720

**Comment by jiyinyiyong** [comment]
Same error here but during `./gradlew installRelease`. Also in XiaoMi 4, 6.0.1 . Some logs:

```text
17:26:16.747 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:installDebug'.
17:26:20.299 [LIFECYCLE] [org.gradle.api.Task] Installing APK 'app-debug.apk' on 'MI 4LTE - 6.0.1'
17:26:21.840 [ERROR] [org.gradle.api.Task] Unable to install /Users/chen/repo/gist/Demo/android/app/build/outputs/apk/app-debug.apk
com.android.ddmlib.InstallException: Failed to establish session
	at com.android.ddmlib.Device.installPackages(Device.java:894)
	at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:113)
```
```text
17:26:21.845 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 14.385 secs, idle: 0.049 secs
17:26:21.853 [ERROR] [org.gradle.BuildExceptionReporter]
17:26:21.855 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:26:21.855 [ERROR] [org.gradle.BuildExceptionReporter]
17:26:21.855 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
17:26:21.856 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:installDebug'.
17:26:21.856 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to establish session
17:26:21.857 [ERROR] [org.gradle.BuildExceptionReporter]
17:26:21.857 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
17:26:21.857 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:installDebug'.
17:26:21.858 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
17:26:21.858 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute
```

And reading 2720 does not solve my problem.

**Comment by bintansiregar** [comment]
Actually this problems comes from all of Xiaomi phones, MIUI block incoming action for installing adb from apk via usb. If you try install manual via "adb install nameofapk.apk" then of your Xiaomi's screen will pop permission that ask you to accept or deny installation from usb. That's the problem why apk won't automatically install when we type "react-native run-android", because that command use silent install via adb to Xiaomi Device. Silent install will not make pop up permission on Xiaomi's screen. So may the question is, how to remember permission access for install apk via adb usb, or maybe disable it.

Thanks

**Comment by lironess** [comment]
Seems to not work on Xiaomi Redmi Note 3 too. 
Can you please show explained way of solving this issue ?

**Comment by Shinichi52** [comment]
you can disable MIUI on developer options after run react-native run-android

**Comment by lironess** [comment]
Works !
for those who suffer from this:
1. enable developer mode - In your phone, go to Settings, About phone and click on MIUI version 7 times. You’ll a pop up which says you are a developer now.
2. Go back to Settings, Additional settings, Developer options and enable USB Debugging.
3. Connect your phone to your PC/Mac and on the phone authorize your computer
4. go back to Developer options, scroll down to find Turn on MIUI optimization and disable it. Your phone will be rebooted
5. Try it now :)

**Comment by idisfkj** [comment]
This problem confused me for a long time, thank you very much

**Comment by danilvalov** [comment]
@lironess Thank you! It work!

**Comment by huangMingHua** [comment]
@lironess it work   Thank you so much

**Comment by SanShiSir** [comment]
Many thanks for you!

**Comment by VentionYC** [comment]
@lironess Thank you so so much,it works

**Comment by qutek** [comment]
@lironess Thanks, you saved my day 👍

**Comment by AndyFightting** [comment]
it does not work for me .... i can run on android emulator, but device can not. device is Xiao Mi MIUI8.0, and i try the 5 step upon.........it does not work.......
////////////////////////////////////////////////////////////////////////////////////
:app:installDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unable to upload some APKs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.064 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by AndyFightting** [comment]
i solved my problem. i change android/build.gradle file line 8,  classpath 'com.android.tools.build:gradle:1.3.1'  to classpath 'com.android.tools.build:gradle:1.2.3'. it works...

link :http://csbun.github.io/blog/2015/12/starting-react-native-with-android/

**Comment by VentionYC** [comment]
把小米开发者选项中最后一行MIUI优化关掉就行

发自我的 iPhone

**Comment by AndyFightting** [comment]
@VentionYC 谢谢，我关了的，不行。我报的错和题主不一样，我的是com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unable to upload some APKs。我是把gradle:1.3.1 改成  gradle:1.2.3 就可以了。再改回去还是不行...难道只能用gradle:1.2.3？？我不知道为什么...先跑起来再说了....

**Comment by DDstar** [comment]
@AndyFightting 我的跟你的一样，改成1.2.3就可以了。。。。1.3.1的也一样不行，用的是MIUI手机，用模拟器的话都不用修改什么就运行起来了

**Comment by abhisheksoni27** [comment]
What's the word on this issue?

**Comment by miukki** [comment]
works for me. thX!

**Comment by t2krew** [comment]
@lironess Thank you !

**Comment by NayeemUrRehman** [comment]
@lironess Thank you!!... after trying all permutations and combination ... finally this helped me to sort the problem ... also advise for every1 here dont use MI phone for debugging it will not allow you to taste the actual flavour of android ... thank you all !!!!

**Comment by codeheadshopon** [comment]
@lironess Answer Worked for Xiomi. I think that is the solution for Xiomi handsets. Thanks mate  :)

**Comment by RomilChristian** [comment]
thank you very much man.

**Comment by qaz349293703** [comment]
thank you very much ,close the optimization mui is works for me

**Comment by d4rkm3z** [comment]
Thanks, work on Xiaomi Redmi 4 Pro/Prime

**Comment by ravkr** [comment]
Thanks SOOO MUCH!
Xiaomi Redmi 3S :smiley:

**Comment by liuliangsir** [comment]
Thanks, 
Solution: disabled Xiaomi 5 connection
Namely, pull the usb cable
Because, i charge phone by using usb cable

**Comment by pickfire** [comment]
Thanks a lot.

On redmi note 3s, once I disabled `使用MIUI优化` from settings and now it works.

**Comment by juicechu** [comment]
@AndyFightting thx, it work. gradle version change to 1.2.3

**Comment by SanalKumarK** [comment]
@lironess That worked for my Redmi note also... Thanks...

**Comment by praveen180490** [comment]
Thanks.. That also worked for my Redmi 3S Prime..

**Comment by fajrinimamarif** [comment]
thanks

**Comment by MrChinmaya** [comment]
@lironess Thanks Buddy. Works for Redmi Note3.

**Comment by amit1999999** [comment]
i am using Xiomi readmi 4 it is not woking...i am stuck

**Comment by amit1999999** [comment]
any body help,,,,with Xiomi read mi 4 i am working its no working

**Comment by Janaksan** [comment]
@lironess Oh man Thank you so much. It's Working. You save my time.

**Comment by themakerman** [comment]
Haha works like a charm...REDMI NOTE 4

**Comment by yinglovezhuzhu** [comment]
If your android device os version is above 5.0, you need to run cmd 'adb reverse tcp:8081 tcp:8081'

**Comment by wajih123** [comment]
my problem in with the emulator its the one thats give me that error

**Comment by afresh** [comment]
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to finalize session : INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.lovecode signatures do not match the previously installed version; ignoring!

因为手机中已经存在的相同包名的APK，将其删除就行了。

**Comment by gupta-ji6** [comment]
@lironess Thanks for the solution! Worked for me.
