### ISSUE TITLE
Fire a function after WebView fully loads

### ISSUE THREAD

**Issue by TeodorKolev** [facebook/react-native#6501]
Is it soon be possible to fire a function for example hide splash screen after webview url is fully loaded?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

You should take a look to [WebView Component](https://facebook.github.io/react-native/docs/webview.html#content).

>OnLoad function
>Invoked when load finish

>renderLoading function
>Function that returns a loading indicator.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by anotherstarburst** [comment]
While this should work in theory, the following doesn't work as expected.

      `<WebView
            source={{ uri: "http://www.bbc.com" }}
            style={ localStyles.webviewContainer }
            javaScriptEnabled = { true }
            injectedJavaScript={ this.state.webviewInjectedScript }
            onNavigationStateChange = { alert("onNavigationStateChange")}
            onLoadEnd = {alert("onLoadEnd")}
            onLoad = {alert("onLoad")}
          />`

One would expect the alerts to each fire once. However, on opening a new webview with the bbc.com link, the alerts each fire multiple times. Any ideas on what may be causing this?
