### ISSUE TITLE
Touchable inside touchable doesn't respond to touches

### ISSUE THREAD

**Issue by terrysahaidak** [facebook/react-native#6505]
I'm trying to build slack like message component - Avatar, Date, Text. The whole component is wrapped with the TouchableNativeFeedback and I have some actions triggered by `onPress` and `onLongPress`. But I want also to have the ability to click on user's avatar and navigate to user screen but figured out my touchable avatar doesn't respond to any press. Also, it won't work with `<View />`, but with `<Text />`, it works as well. Can't find similar StackOverflow question or any issue, and don't know if it the bug or the feature, but in the Slack native app it works, so I think it's a bug.

My component:
```jsx
<TouchableNativeFeedback
  onPress={() => this.onMessagePress()}
  onLongPress={() => this.onLongPress()}>
  <View style={[s.container, {opacity, backgroundColor}]}>
    <TouchableWithoutFeedback>
      {/* Won't work */}
      onPress={() => this.onUserAvatarPress()}>
      <Avatar src={fromUser.avatarUrlSmall} size={30} />
    </TouchableWithoutFeedback>
    <View style={s.content}>
      <View style={s.top}>
        <Text
          style={s.username}
          {/* Works! */}
          onPress={() => onUsernamePress(fromUser.username)}>
          {fromUser.username}
        </Text>
        <Text style={s.date}>{this.renderDate()}</Text>
      </View>
      <View style={s.bottom}>
        {this.renderMessageText()}
      </View>
    </View>
  </View>
</TouchableNativeFeedback>
```

**Comment by terrysahaidak** [comment]
`<TouchableOpacity />` solves the problem.

**Comment by wootwoot1234** [comment]
I'm having the same issue with nested touchable elements.  I tried switching them to `<TouchableOpacity />` but that didn't help.  How did you fix it?

**Comment by terrysahaidak** [comment]
Hi @wootwoot1234, I've used touchable opacity as my root component for that component. Also, you may try to play with `pointerEvents` prop for some your component's views.

**Comment by wootwoot1234** [comment]
Ok, thanks.  I'll look into pointerEvents.  Thanks for writing back!
