### ISSUE TITLE
[Documentation] Node 5.x may be recommended?

### ISSUE THREAD

**Issue by taypo** [facebook/react-native#6513]
There is a huge performance difference between node 4.x and 5.x and I think it should be mentioned in the documents. Node.js site says 4.4.0 is an LTS release which made me prefer it. But 5.x release use a newer npm that flattens dependencies. Which results to:

- Packager start times 200 seconds vs. 50 seconds. 
- node_modules directory size 1200 MB vs 200 MB.

For guys like me, who are not familiar with node.js, it is hard to figure out.

Platform: Win 7

Didn't submit a PR on the grounds that I may be talking sh.t because packager starts in 3 seconds on my mac.

**Comment by ide** [comment]
@taypo the flatter node_modules is due to npm 3, so we could recommend that people use npm 3 with Node 4 or 5 (or upcoming Node 6).

cc @bestander I saw you put out a PR recently to move Travis to npm 2 but what do you think about using npm 3 everywhere? npm 3 has gotten a lot faster recently too.

**Comment by peterp** [comment]
Pretty interesting, and just poking in here, what kind of performance differences are you seeing?

**Comment by bestander** [comment]
@ide Circle CI is npm 3. So we run flow, jest and Android tests using node 5.6 and npm 3.x.
I've left Travis at npm 2 to make sure we still get it compiling.
Personally I would prefer node 5 and npm 3.
My colleagues are hesitant because installing node_modules with npm 3 takes ages compared to npm 2.
Although we are experimenting on an laternative npm client that will bring both worlds together.
Stay tuned.

**Comment by taypo** [comment]
@peterp just to be clear, performance differences are not in the resulting application. Just the items I listed before. The time it takes the packager to start and the size of the node_modules directory (which indicates react-native init is downloading too much)

**Comment by ide** [comment]
@bestander npm 3 used to be very, very slow, but it's gotten better. I recommend setting `npm set progress false` and then comparing it to npm 2 -- npm 3 is still slower but not horribly slow anymore. That said, both npm 2 and 3 are ultra-slow and make it so hard to bisect compared to something like git-lock so your new npm client is very welcome :)

**Comment by mkonicek** [comment]
I'm using Node 4 and npm 2 locally and very happy with it.

I'll close this as it's a discussion rather than a bug (we'd like to use the GitHub bug tracker for bugs, and GitHub really needs to implement a Discussions tab) but feel free to continue discussing here.

**Comment by taypo** [comment]
I wish the whole project used gradle. npm is several steps back for a package manager IMHO.

**Comment by ide** [comment]
Gradle is pretty crazy and slow, and doesn't really address iOS. Moving forward the right thing might be to use Buck for builds instead of Gradle and CocoaPods, and npm for distribution.
