### ISSUE TITLE
Android ImageView should resize network images

### ISSUE THREAD

**Issue by kushal** [facebook/react-native#6514]
I'm writing an app that is heavy on network images of unbounded size that are not under my control, and I'm running into OOM issues. My guess is that ReactImageView.java shouldResize() should at least let the caller ask for resizing if not default to resizing any network image. Any hope of getting this added/fixed? Thanks!

**Comment by gre** [comment]
@facebook-github-bot label android

**Comment by mkonicek** [comment]
This would be a question for Fresco. Can you post there please? https://github.com/facebook/fresco

**Comment by kushal** [comment]
I'm not sure that's true. shouldResize() in ReactImageView.java implies
that react code is making this decision?
