### ISSUE TITLE
section header with overflow:'hidden' always exist one to forbiiden scroll

### ISSUE THREAD

**Issue by SeanXiao1988** [facebook/react-native#6518]
sample code

    _onRenderRow(item) {
        return (
            <View style={{overflow:'hidden', backgroundColor:'black', height:80}}/>
        )
    }

    _renderSectionHeader(sectionData, sectionID) {
        // console.log('sectionData :' + sectionData + ' sectionID :' + sectionID)
        return (
            <View style={{height : 60, overflow :'hidden'}}/>
        )
    }

**Comment by SeanXiao1988** [comment]
please help.

section header always exsit one with hidden middle of my screen...forbidding my touch and scroll event

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by SeanXiao1988** [comment]
@mkonicek I

**Comment by SeanXiao1988** [comment]
@mkonicek 
Hi, I use the react-native example project with this simple code.

I think this is a bug with react-native
