### ISSUE TITLE
[Question] When I build my RN App with Xcode in Release mode, the build fails: RCTLog.h not found

### ISSUE THREAD

**Issue by shotoreaper** [facebook/react-native#6524]
I had created the main.jsbundle  with this command:
react-native bundle --dev false --entry-file index.ios.js --platform ios --bundle-output main.jsbundle

My header search paths on Release:
$(SRCROOT)/../react-native/React (recursive)
$(SRCROOT)/../node_modules/react-native/React (recursive)
$(SRCROOT)/../../React (recursive)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include (non-recursive)
$(inherited) (non-recursive)

And yes, the file RCTLog.h exists in this folder:
/node_modules/react-native/React/Base

RN: 0.19.0
RN-Cli: 0.1.10
xCode: 7.2.1
iPhone: 6
iOS: 9.2.1

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label iOS

**Comment by brentvatne** [comment]
Hi there!

A couple of ideas:

1. You might want to try updating to the latest version of React Native -- we always have a bunch of bugfixes in each release.
2. This is probably a question better suited for StackOverflow :)

Best of luck!
