### ISSUE TITLE
ToolbarAndroid - set RTL not working

### ISSUE THREAD

**Issue by yaronlevi** [facebook/react-native#6531]
I am using a ToolbarAndroid, and I need it in a RTL configuration. So I followed the official docs:

- Set rtl={true} on the ToolbarAndroid Component

- Added android:supportsRtl="true" to the AndroidManifest.xml

- Added getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL); to the onCreate() method in the main activity 

But when the app loads on the device (i am debugging it on nexus 5), the tool bar stays in the regular direction, nothing has changed.

My component:  
```
<ToolbarAndroid
            actions={[{title: 'Settings', show: 'always'}]}
            style={styles.toolbar}
            title='MyToolBar'
            rtl={true}/>
```

**Comment by brentvatne** [comment]
Hi @yaronlevi! It sounds like you are doing this correctly, could you create a sample project with these exact steps and upload it to Github? Thanks!

**Comment by yaronlevi** [comment]
of course, here it is:
https://github.com/yaronlevi/reactNativeRtl

**Comment by lxsameer** [comment]
@yaronlevi I'll send you a working as soon as I find some free time

**Comment by yaronlevi** [comment]
ok thanks

**Comment by elad-solomon** [comment]
looking forward for a solution for that as well! :)

**Comment by menicherbakovsky** [comment]
+1
Looking forward for a solution as well

**Comment by cadr-sa** [comment]
+1
looking forward for a solution for that as well!

**Comment by lxsameer** [comment]
It seems like a valid bug and I'm debugging it right now

**Comment by yasicmd** [comment]
any progress in this case ?

**Comment by lxsameer** [comment]
Nothing yet, there is much to change, there is some deprecated API

**Comment by yasicmd** [comment]
setting rtl false solved my issue.........

**Comment by lxsameer** [comment]
what was your problem ? and why set to `false`.

**Comment by yasicmd** [comment]
toolbar icons set to rtl when i set the property rtl to false. I dont know how when i set rtl to true nothing changed but when i set rtl to false it its converted to rtl.

**Comment by lxsameer** [comment]
good info. thanks, I'll fix it

**Comment by lxsameer** [comment]
Using RN `0.33.0` I got it working without any problem. do you add the required code to you project before compiling it ?

**Comment by yaronlevi** [comment]
I can confirm this is working in 0.33.0.
So to recap:

1) in app manifest 
```
<application
      android:supportsRtl="true"
```

2)in mainActivity.java:
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
      getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
    }
```
Do not forget to:
```
import android.os.Bundle;
import android.view.View;
```

3) put rtl true on the toolbar itself
