### ISSUE TITLE
Confusing documentation for Android SDK Configuration

### ISSUE THREAD

**Issue by DanielRosenwasser** [facebook/react-native#6532]
Clearly the red squares signal that items in the list should be installed, but shouldn't prior steps reinforce that?

![image](https://cloud.githubusercontent.com/assets/972891/13894669/e34f19c6-ed27-11e5-9d54-b59f6ae6c7e3.png)

Basically, it makes the reader feel like there's an information gap. Could someone clarify what the intent is?

**Comment by mkonicek** [comment]
The screenshots show the same information as the text. It's just to make the docs easier to read.

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by DanielRosenwasser** [comment]
I don't think that's true - there are things in the image that are selected, but not described in the textual steps.

**Comment by satya164** [comment]
@DanielRosenwasser If you could send a PR to improve it, it would be great :)
