### ISSUE TITLE
[UI] How to create input intl tel phone number?

### ISSUE THREAD

**Issue by ga12ru12** [facebook/react-native#6536]
I want to create **intl tel phone input** for form login but I don't know how to do. Anyone have any suggestion pls? Thanks

**Comment by mkonicek** [comment]
Try looking at JS Coach which is a database of 3rd party React Native modules.
https://js.coach/?search=phone

If there's none you'll have to implement one yourself.

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow
