### ISSUE TITLE
signed apk : stopped working

### ISSUE THREAD

**Issue by Msiavashi** [facebook/react-native#6537]
i've generate a signed apk using [this](https://facebook.github.io/react-native/docs/signed-apk-android.html) tutorial  everything went without a hitch and i installed the release using gradlew installRelease and the installation was also successful but when i run the apk it says : "unfortunately, application has stopped" right before even running it . but when i install and tun it using react-native run-android command it will work perfectly . i couldn't find anything on the web . 
im using windows . could anyone please help me where might be the problem ?!

**Comment by charpeni** [comment]
You should check logs with logcat from [Android Studio](http://developer.android.com/intl/en/tools/debugging/debugging-studio.html#systemLogView) or [adb](http://developer.android.com/tools/help/logcat.html).

**Comment by jsierles** [comment]
@facebook-github-bot answered
