### ISSUE TITLE
Links between props broken in documentation 

### ISSUE THREAD

**Issue by joIivier** [facebook/react-native#6539]
While reading https://facebook.github.io/react-native/docs/touchablehighlight.html#content, I wanted to click on the link to the props of TouchableWithoutFeedback (at the top of the Props section) and landed on the documentation start page instead of the expected documentation page for TouchableWithoutFeedback.
After a quick digging it seems that these links are automatically generated but they are lacking the "doc/" part of the path, since the broken link brings me to

    https://facebook.github.io/react-native/touchablewithoutfeedback.html#props

Whereas the left doc menu about TouchableWithoutFeedback brings me to the working

    https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#content

**Comment by joIivier** [comment]
In fact the anchor links (or permanent link, whatever you call the # link that appears on hover to the right of any props) for the other props are also broken, for instance the target for activeopacity inTouchableHighlight is

   https://facebook.github.io/react-native/undefined#activeopacity

**Comment by satya164** [comment]
cc @bestander

**Comment by rseemann** [comment]
This seems to have been fixed already by f73f41779a5698043e33c2621e05ca975d07e501
