### ISSUE TITLE
Error importing an npm module

### ISSUE THREAD

**Issue by httpNick** [facebook/react-native#6541]
Currently creating an android app. I am simply trying to import the `spotify-web-api-node` module.

One line so far in my `index.android.js` to do this:

`import SpotifyWebApi from 'spotify-web-api-node';`

When I go to load the JS into my emulator I get the follow error:

`602/603Error while persisting cache: SyntaxError /path/to/the/project/node_modules/restler/lib/multipartform.js: Invalid number (112:35)`

I am using a mac, this occurs for android (have not tried ios yet). 

`react-native -v` = `
react-native-cli: 0.1.10
react-native: 0.21.0`

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow
