### ISSUE TITLE
Unable to find Podspec version

### ISSUE THREAD

**Issue by adamski** [facebook/react-native#6547]
I am creating a Podspec which depends on React. 
I have declared
```
s.dependency "React", "~> 0.0.1"
```
As per the latest Podspec in React Native master branch.

However `pod spec lint` fails with
```
- ERROR | [iOS] unknown: Encountered an unknown error (Unable to satisfy the following requirements:

- `React (= 0.0.1)` 
```
 
If I choose version `0.11.0` (the latest listed in CocoaPods) it finda the dependency but fails on missing header `RCTRootViewDelegate.h`:
```
ReactNativeControllers/ios/RCCLightBox.m:4:9: fatal error: 'RCTRootViewDelegate.h' file not found
```

How can I provide the CocoaPods dependency so it gets the latest RN version?

**Comment by mkonicek** [comment]
@facebook-github-bot stack-overflow

**Comment by brentvatne** [comment]
Hi there! We don't distribute through Cocoapods anymore, rather you can install from a local podspec that is distributed through the react-native npm package, see [Install React Native Using Cocoapods](http://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods)

**Comment by adamski** [comment]
@brentvatne ah ok, maybe `pod spec lint` is trying to check too much.. I already have RN setup with CocoaPods just trying to set up another library with a Podspec with dependency on RN.

**Comment by ide** [comment]
Only the local podspec is supported. It says v0.0.1-master just because we need a valid version number greater than 0.0.0.
