### ISSUE TITLE
How to  auto-slide a view when the keyboard shows up?

### ISSUE THREAD

**Issue by karthickvkumar** [facebook/react-native#6555]
When the TextInput is focus the keybord is hiding the submit buttom. How to auto-slide the components below the TextInput  
<img src="http://i.stack.imgur.com/yTjXt.png"> 
<img src="http://i.stack.imgur.com/iCLIc.png">

**Comment by ashleydw** [comment]
https://github.com/facebook/react-native/issues/3195

**Comment by browniefed** [comment]
@facebook-github-bot answered
