### ISSUE TITLE
Fatal signal 11 (SIGSEGV) on android

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#6562]
adb logcat>>>
03-21 22:47:33.148 21597-24508/? A/libc: Fatal signal 11 (SIGSEGV) at 0xbbadbeef (code=1), thread 24508 (mqt_js)

It only happens on android.

I finally found the code below leading to the bug
```javascript
export var shouldRelogin = async function(ws, data) {
    tlog('shouldRelogin');
    apps.emit('shouldRelogin');
};
```
I accidentally put the async keyword before the function but the body doesn't have an await.
When I delete the async keyword, the collapse disappeared.

Using RN 0.21

**Comment by Kureev** [comment]
So if you make a mistake in the code it fails? :smiley:

**Comment by narychen** [comment]
It shouldn't be collapse when we miss place the async in front of the function.
And if someone met it, it maybe very very hard to find this bug when the code base is large.
Because You cannot see any clue from the collapse information.

**Comment by narychen** [comment]
Nothing to be updated.

**Comment by npomfret** [comment]
I'm getting this on RN 0.32

**Comment by narychen** [comment]
@npomfret I changed to use Promise not async because babel just translate async to Promise and chrome debug cannot source-map correctly with async. Forget about async, it's not mature.
