### ISSUE TITLE
Hot reloading enabled by default and broken on master

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#6569]
I just created a new app by publishing what's on master to Sinopia locally, then did React Native init:

On iOS, HMR is enabled by default and consistently results in a redbox.

When disabling HMR, Reload JS works and the packager shows one request:

     <START> request:/index.ios.bundle?platform=ios&dev=true
     <END>   request:/index.ios.bundle?platform=ios&dev=true (78ms)

![screen shot 2016-03-21 at 6 22 34 pm](https://cloud.githubusercontent.com/assets/346214/13929497/510903e8-ef92-11e5-8342-dbcacb49a796.png)

When enabling HMR via the menu:

The app makes a request to the packager, `END` is not logged and I consistently get a redbox

    <START> request:/index.ios.bundle?platform=ios&dev=true&hot=true

![screen shot 2016-03-21 at 6 23 04 pm](https://cloud.githubusercontent.com/assets/346214/13929585/b86f7d0a-ef92-11e5-90d7-155dea04a46a.png)

I get the same on Android when enabling HMR, although HMR is disabled by default:

<img width="624" alt="screen shot 2016-03-21 at 6 31 11 pm" src="https://cloud.githubusercontent.com/assets/346214/13929673/31ccd8be-ef93-11e5-9d96-78a3cd67d76a.png">

**Comment by martinbigio** [comment]
HMR setting is persisted on the simulator. If you enable it and kill-restart an app when it restarts it will still be enabled. This is the same behavior we currently have for live reload.

**Comment by mkonicek** [comment]
Makes sense, thank @martinbigio! Any idea why we get the error on master when enabling it?

**Comment by martinbigio** [comment]
Fix landed on https://github.com/facebook/react-native/commit/3a1634ec7b0dfa2b5d8890118565006d845e2039

I'll release a new version of the preset tomorrow morning :)
