### ISSUE TITLE
DatePickerAndroid lack of color scheme API

### ISSUE THREAD

**Issue by CapitanRedBeard** [facebook/react-native#6571]
Hey RN, recently I've been trying to implement a different color scheme other than the one default teal one for the material design android date picker.
Default:
<img width="360" alt="default" src="https://cloud.githubusercontent.com/assets/5445860/13936725/e88d672e-ef7c-11e5-9994-5fc32149641c.png">
Desired:
<img width="360" alt="new" src="https://cloud.githubusercontent.com/assets/5445860/13936726/e88ee310-ef7c-11e5-8fdb-10806caab062.png">
Looking at the Library implementation of the component, it seems there is no API to change the color. I attempted to change the color of it via my own styles file in my own android directory like so: 

     
     <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
         
         <item name="android:datePickerDialogTheme">@style/Dialog.Theme</item>
     </style>

     <style name="Dialog.Theme" parent="Theme.AppCompat.Light.Dialog">
         <item name="colorPrimary">#FF0000</item>
         <item name="colorPrimaryDark">#FF0000</item>
         <item name="colorAccent">#FF0000</item>
     </style>

But this didn't produce any results. 

We could either passed these values in the options object parameter to open() OR we create a separate setter function in the DatePickerAndroid class that changes these values. The latter would probably be the cleanest. Thoughts?

**Comment by Bhullnatik** [comment]
I don't think it's possible to pass the color as a parameter because the [`DatePicker`](http://developer.android.com/reference/android/widget/DatePicker.html) on Android doesn't accept any method to modify the color. The best way to do this is using a custom theme in your app theme like you did. I'm not sure why yours is not working, to compare here is my `styles.xml`:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
    ...
    <item name="android:datePickerDialogTheme">@style/MyDialogTheme</item>
    <item name="android:timePickerDialogTheme">@style/MyDialogTheme</item>
</style>

<style name="MyDialogTheme" parent="Theme.AppCompat.Light.Dialog">
    <item name="colorAccent">@color/colorAccent</item>
</style>
```

Are you sure you're actually using `AppTheme` as your application theme ? Be sure to re-compile your app as it is a native change too.

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by charpeni** [comment]
@facebook-github-bot feature

**Comment by CapitanRedBeard** [comment]
@Bhullnatik Thanks Jimmy. I had the code in the wrong styles file. I had it in my SDK folder instead of my Demo folder. Appreciate your help!

**Comment by granumofficial** [comment]
I have run into this issue as well, my styles code is exactly the same, but it is not applying;

I have it the [...]/values/styles.xml path; but for some reason no changes are applying.

**Comment by bennygenel** [comment]
Hi @Bhullnatik;

There might be a bug on changing the styles on DatePickerAndroid dialog. I set the styles accordingly and it works fine if I omit mode prop. If I set mode to 'spinner' or 'calendar' it breaks and shows the dialog with default colors.
```

{
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
} 
```

**Comment by MnemosyneMei** [comment]
Hi @bennygenel ,

Same for my cases, when i change the mode to spinner, the colors does not change and shows the default colors. So do you manage to fix it?

**Comment by bennygenel** [comment]
Hi @MnemosyneMei; 

I couldn't fix it yet. So far I just omit the mode prop. I opened a new issue but so far no progress. I'm waiting for a fix too.

https://github.com/facebook/react-native/issues/13538

**Comment by rodrix** [comment]
Has any way to style the Calendar using CRNA and Expo?

**Comment by wcandillon** [comment]
I would also be interested to know if the color can be set dynamically in the JS userland.

**Comment by gechleng** [comment]
@granumofficial you need to recompile your app
