### ISSUE TITLE
Circular dependency while integrating Crashlytics in RN App

### ISSUE THREAD

**Issue by mohanrohith** [facebook/react-native#6574]
`
* What went wrong:
Circular dependency between the following tasks:
:app:bundleDebugJsAndAssets
+--- :app:mergeDebugResources
|    \--- :app:generateDebugResources
|         \--- :app:fabricGenerateResourcesDebug
|              \--- :app:processDebugManifest
|                   \--- :app:generateBundledResourcesHashDebug
|                        \--- :app:bundleDebugJsAndAssets (*)
`
Can someone help to resolve this issue?

**Comment by mwiley** [comment]
This is the guide I used to get Crashlytics working in my app. Maybe it will help you. https://medium.com/delivery-com-engineering/add-crashlytics-to-your-react-native-ios-app-69a983a9062a

**Comment by geof90** [comment]
@mohanrohith this looks like the same issue as https://github.com/Microsoft/react-native-code-push/issues/234 could you try the fix in that issue and verify that it works? Also upgrading to the latest CodePush plugin might be the permanent fix.

**Comment by mohanrohith** [comment]
@geof90 Yes commenting that line fixed it. Will update codepush and verify.
