### ISSUE TITLE
ListView performance problems when removing the ListView?

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native#6578]
On an iPhone, with React Native version 0.21.0, I have a ListView that is encountering performance problems.

Oddly enough, the problem occurs when the ListView is removed from the screen, not the initial rendering or scrolling of it. The problem is that the entire app freezes for anywhere from 5 to 30 seconds when the state changes such that the ListView gets removed from the screen.

It is fine on Android, and on my iPhone, but a tester's iPhone is reporting performance problems. I identified the problem as the ListView by trial and error, but don't know enough to fix it - it seems like a bug with ListView's performance, because I wouldn't have expected normal usage of a ListView to have this significant problem. The user has about 1000 items in the ListView, which seems big but not so huge that I'd see performance issues.

The following code snippet is more or less what I am using:

```js
  renderBottom: function() {
    if (!this.state.listViewToggled) {
      return null;
    }

    var items = [].concat(this.state.items1).concat(this.state.items2);
    var myDataSource = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    var clonedDataSource = myDataSource.cloneWithRows(items);

    return (
        <View>
          <ListView dataSource={ clonedDataSource }
              renderRow={ this.renderOtherItem }>
          </ListView>
        </View>
    );
  }
```

The problem occurs when the user clicks a button that toggles state.listViewToggled. The user is reporting that the app basically freezes for anywhere from 5 - 30 seconds or more when they advance the state such that the ListView is supposed to be hidden. I would have expected that removing a ListView would be good for performance, not bad, so I am really surprised this is happening.

**Comment by ms88privat** [comment]
wouldn't it be better if you outsource the `new ListView.DataSource` from the render?

**Comment by Kuzmin** [comment]
For what it's worth, I'm seeing similar issues with around 100 items in my `ListView` where the datasource isn't inside the render :)

**Comment by pickhardt** [comment]
@Kuzmin can you post a snippet of what yours is, the RN version, and whether it happens on all iPhones? In my case, it doesn't happen on my iPhone 6s with about 500 items, but someone with an iPhone 6 is saying that it happens with about 1000 items in their ListView.

**Comment by dannyflax** [comment]
out of curiosity, how complex are your ListView items?

**Comment by ide** [comment]
Try putting overflow: hidden on your rows if you don't already have that.

**Comment by pickhardt** [comment]
They aren't that complex. They're just a list of contacts, so first name and last name, followed by some text underneath along the lines of "Invite to Join".

I just tried overflow: hidden on the rows and had my tester retry it, and he said it's still slow. I double checked and removeClippedSubviews: true is enabled by default (this is the reason you were asking me to add overflow: hidden, right @ide ?)  The weird thing is the slowness happens when the list view gets hidden from the screen, but the scrolling itself is performant.

The screen looks like this:

[ stuff on first half of screen ]
[ list view ]
...more list view off screen...

That probably doesn't matter, just thought I'd add some detail.

**Comment by Kuzmin** [comment]
@dannyflax: How do I measure complexity in this context? This is the JSX rendering the row

```
      <TouchableOpacity
        onPress={this.onPress}
        style={styles.container}
      >
        <View style={styles.dataContainer}>
          <Text style={styles.subjectText}>{booking.subject}</Text>

          <Text>{`${school.name}, årskurs ${booking.klassName}`}</Text>
          {student && (
            <Text>{`Vikarie: ${student.name}`}</Text>
          )}
        </View>
        <View style={styles.chevronContainer}>
          <Image
            style={styles.chevronImage}
            source={CaretForward}
          />
        </View>
        <Text style={styles.dateText}>{formatInterval(booking)}</Text>
      </TouchableOpacity>
```

And my stylesheet is defined like this:

```
const styles = StyleSheet.create({
  container: {
    position: 'relative',
    borderTopWidth: 1,
    borderTopColor: '#efefef',
    backgroundColor: '#fff',
    padding: 15,
    paddingTop: 20,
    flexDirection: 'row',
  },

  dateText: {
    position: 'absolute',
    fontSize: 12,
    top: 4,
    right: 15,
  },

  subjectText: {
    fontSize: 16,
  },

  dataContainer: {
    flex: 1,
  },

  chevronContainer: {
    position: 'relative',
  },

  chevronImage: {
    position: 'absolute',
    right: 0,

    top: 10,

    tintColor: COLOR_SV_ACCENT,
    height: 21,
    width: 21,
  }
});
```

It's a few nested containers, some flexbox, and an image, so I can see that this becomes expensive with a hundred items in the list.

@ide: My ListItems are not overflowing right now, will it still help to set `overflow: 'hidden'`? (If this works, I'm also curious as to why it works, does it reduce the number of calculations needed before render?)

@pickhardt: Sadly, this is all back on React Native 0.15 (decided that what I had was good enough and to work on non-app features while waiting for Push on Android), so it might no longer be valid. Either way, it happens both when I add and when I remove the ListView.

**Comment by ide** [comment]
overflow: hidden + clipping lets RN remove cells that are outside the viewport. My suggestion for figuring out performance problems is to use Instruments and see where UIKit is spending CPU cycles (or maybe it's all in JSC and React is slow, but I'm guessing this has to do with UIKit).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-performance-problems-when-removing-the-listview

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub. GitHub issues have voting too, nevertheless
Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by Kuzmin** [comment]
Thanks @mkonicek :)
