### ISSUE TITLE
difficulty in navigating views in react native

### ISSUE THREAD

**Issue by shubham23596** [facebook/react-native#6589]
i am using react native 0.22 version right now, after getting try for 3-4 hrs i cannot able to manage react native views properly for example i have login form which is validating through node js server code but if token is valid i want to take user to login page and also store his username as a session variable , i am currently doing but i am never success properly in doing this in react native please help me. this is getting tougher for me ,
below is my little project 
[New folder.zip](https://github.com/facebook/react-native/files/184704/New.folder.zip)

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
