### ISSUE TITLE
[Android] How to set host and port in code

### ISSUE THREAD

**Issue by Leon1809** [facebook/react-native#6601]
Hello, We cannot find anywhere to set host and port in code for Android React.
(In IOS, we only need to modify : \ios\AwesomeProject\AppDelegate.m)

On Android platform, React is now popup a window to ask user setting host & port, while we could not use this to release as a product to user, right?

We find some "solutions" while they does not work.

So could you please tell us the way to set host & port in code(or something like configuration file) for Android React?

Thank you very much.

**Comment by ide** [comment]
@facebook-github-bot stackoverflow
