### ISSUE TITLE
Android font-weight: light

### ISSUE THREAD

**Issue by ColCh** [facebook/react-native#6607]
# Problem

We need to add a font for our app. Regular weight is just ok - we are able to use `fontFamily: 'Ubuntu'` in app, but for *light* weight (*100*) we faced a problem.

Files named both for _iOS_ and _android_ as `Ubuntu-L.ttf`

# Code snippet

this is style
```js
    fontFamily: 'Ubuntu',
    fontSize: 50,
    lineHeight: 50,
    fontWeight: `100`,
    textShadowColor: `rgba(159,164,175,.8)`,
    textShadowOffset: {
      width: 0,
      height: 1,
    },
    color: '#c4c7cf',
```

# Hotfix

Use `fontFamily` as your filename. `fontWeight` not works
```js
    fontFamily: Platform.OS === 'android' ? 'Ubuntu-L':'Ubuntu', // android not parses light weight for now
    fontSize: 50,
    lineHeight: 50,
    fontWeight: `100`,
    textShadowColor: `rgba(159,164,175,.8)`,
    textShadowOffset: {
      width: 0,
      height: 1,
    },
    color: '#c4c7cf',
```

# Screenshot

If you really need a screenshot, let me know.

# RN Version

*0.21.0* as well as *0.22.0*

# Where occurs

Nexus android emulator

# My platform

OS X El Capitan 10.11.1

**Comment by charpeni** [comment]
@facebook-github-bot android

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by grabbou** [comment]
Closing as #4925 is the same issue, esp. this commit points to the same workaround -> https://github.com/facebook/react-native/issues/4925#issuecomment-167228572
