### ISSUE TITLE
[Android]:Why not use a class annotation in the Java  ViewManager?

### ISSUE THREAD

**Issue by MegatronKing** [facebook/react-native#6609]
In the code of javascript components, we use '@providesModule' to export the component, but in java we define a unimplemented method getName() for mapping. I don't understand this design and I think using a class annotation named '@providesModule' in java would be better！

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by satya164** [comment]
`@providesModule` is an implementation detail in React Native. You shouldn't use it outside of the core React Native code.
