### ISSUE TITLE
Android Modal doesn't handle the back button

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#6612]
I tried using the Android Modal in 0.23.0-rc1. Did `react-native init AwesomeApp`, changed the version in package.json to 0.23.0-rc1 and ran `npm install` (actually I just tested using Sinopia but should be the same result).

Then I wrapped the `<Text>` "To get started, edit index.android.js" in a `<Modal>`. The Modal renders correctly but:
- Pressing the back button in Genymotion doesn't dismiss the Modal
- I can't press the menu button in Genymotion anymore to show the menu (and Reload JS)
- I can't double-tap R on my keyboard to Reload JS

Therefore I am now stuck in this state:

<img width="615" alt="screen shot 2016-03-23 at 6 39 58 pm" src="https://cloud.githubusercontent.com/assets/346214/13996819/3b5e6240-f127-11e5-8d46-0d99a912e009.png">

**Comment by dmmiller** [comment]
You need to override onRequestClose prop which is called when the back button is pushed.

**Comment by javache** [comment]
We should generate a warning in Modal.js when onRequestClose is not set. It seems pretty easy to forget.

**Comment by satya164** [comment]
Is it not a required prop?

**Comment by javache** [comment]
No, it's not (we'd need to make it conditionally required on Android): https://github.com/facebook/react-native/blob/master/Libraries/Modal/Modal.js#L64

**Comment by satya164** [comment]
@javache PR sent.
