### ISSUE TITLE
Is there any tool can check API compatible between different RN versions

### ISSUE THREAD

**Issue by Robert-Qiu** [facebook/react-native#6620]
We have an app using RN 0.17 and RN 0.19 in different app version.
When we port the codes using RN 0.19 to RN 0.17，the new API in RN 0.19 caused old version app crash online.
So, I want to know that is there any tool can check the problem before our codes published.

**Comment by satya164** [comment]
@Robert-Qiu No, there isn't. But we add warnings for deprecated APIs and list breaking changes in the release notes -  https://github.com/facebook/react-native/releases

You should test both the development and release versions to ensure that your app doesn't crash in production.

**Comment by satya164** [comment]
@facebook-github-bot answered
