### ISSUE TITLE
[0.23.0-rc1][Android] transform scaleY: -1, scaleX: -1 broken

### ISSUE THREAD

**Issue by gut4** [facebook/react-native#6622]
View with style `transform: [ { scaleY: -1 } ]` or `transform: [ { scaleX: -1 } ]` not displayed.
In 0.22 this works fine.

**Comment by terrysahaidak** [comment]
@gut4 are you using invertible scroll view?

**Comment by gut4** [comment]
invertible scroll view not displayed too.
Also I find that `transform: [{ rotateY: '100deg' }]`, `transform: [{ rotateX: '10deg' }]` broken too. Views inside scroll view or outside both not displayed.

**Comment by jgibbons** [comment]
Do you know what commits broke this?

**Comment by mkonicek** [comment]
Confirming this is Android-only. Same code on iOS and Android:

<img width="404" alt="screen shot 2016-03-31 at 12 35 06 pm" src="https://cloud.githubusercontent.com/assets/346214/14174551/02d145fc-f73d-11e5-95ad-5e85b2f31162.png">

<img width="615" alt="screen shot 2016-03-31 at 1 04 57 pm" src="https://cloud.githubusercontent.com/assets/346214/14175169/36848f5e-f741-11e5-8a72-04e1ec35ef4e.png">

**Comment by mkonicek** [comment]
Works after reverting 3e760f48c5a28b592cb60c4060ca28a1574f6274:

<img width="643" alt="screen shot 2016-03-31 at 1 33 31 pm" src="https://cloud.githubusercontent.com/assets/346214/14176032/d4357722-f746-11e5-8abd-902f84756ac3.png">

**Comment by mkonicek** [comment]
Releasing 0.23.0-rc3 now, @gut4, @terrysahaidak can you try that please?

**Comment by terrysahaidak** [comment]
Yeah, it works. Thanks.

**Comment by bryaneaton13** [comment]
This seems to be broken in 0.24.1 `transform: [ { scaleX: -1 } ]`
