### ISSUE TITLE
WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Invalid frame header

### ISSUE THREAD

**Issue by cgreening** [facebook/react-native#6627]
Seem to have started getting this random error when debugging with chrome, it will debug for a while and then die with the error:

    WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Invalid frame header

![screenshot 2016-03-24 15 10 20](https://cloud.githubusercontent.com/assets/706944/14021235/99d838ae-f1d2-11e5-9ec3-dad835192635.png)

We're using version 0.22 on the Mac with iOS

**Comment by gwhite-dayspring** [comment]
Also having this issue

**Comment by tal952** [comment]
+1

**Comment by robclouth** [comment]
Same. Version 0.22 on Mac with iOS.

**Comment by thealmightyone** [comment]
so has this been fixed? I'm running http server in node, listening on port 3001 and after react-native recieves any error (like parse Error for example) I need to restart it and react-android app no longer connects to that node server. I end up with just that message in debugger. I set up adb connection over wifi, 'adb devices' shows my phone and app starts normally - but doesnt connect over 3001

**Comment by rickyn73** [comment]
Also having same issue

**Comment by alexandrunicolae** [comment]
try running 'adb reverse tcp:8081 tcp:8081' in terminal to access the development server from the device

**Comment by IlyaRepo** [comment]
Same issue here on 0.24 version for iOS

**Comment by bestofsong** [comment]
same issue, react native 0.26.3

**Comment by ultragtx** [comment]
I have the same issue when using Chrome, but it won't happen if I use https://github.com/jhen0409/react-native-debugger.

**Comment by millerm** [comment]
Experiencing the same issue with react-native: 0.28.0

**Comment by Exilz** [comment]
@millerm are you referring to the ATS configuration in xcode ?

If so, it doesn't solve it for me. OSX / React native 0.28

**Comment by hendrikswan** [comment]
Perhaps it's antivirus? https://github.com/facebook/react-native/issues/7413

**Comment by KGALLET** [comment]
Have the same issue

RN 0.28
MAC OS

**Comment by hendrikswan** [comment]
A colleague of mine had the same issue on node version 6.x. He downgraded to the same version I'm running, v5.9.1, and it resolved his issue.

**Comment by Exilz** [comment]
Yup, I can confirm that Node 6.3 was the problem for me.

I downgraded as @hendrikswan suggested, but to version 6.2 and everything has been running without problems for a few hours.

**Comment by phil-travelbytes** [comment]
Downgrading of Node from 6.3.0 to 6.2.2 didn't work for me;
Issue still persists.

**Comment by hendrikswan** [comment]
Maybe downgrade further?

**Comment by ide** [comment]
I think this might be "fixed" in RN 0.30 which uses ws 1.1.1, which doesn't try to install native helper modules by default and should work more consistently across V8 versions.

**Comment by julienvincent** [comment]
Can someone confirm if RN 0.30 fixes this?

**Comment by tronin** [comment]
Have the same thing

**Comment by julienvincent** [comment]
I can confirm it is greatly improved in RN30. The error still pops up occasionally but its rare enough for it not to be a hindrance anymore.

**Comment by stewart42** [comment]
RN `0.30.0` does appear to be much better, not getting the error on node `6.3.1`.  I was getting it with RN `0.29.0`

**Comment by chrisfisher** [comment]
Upgrading from `0.29.0` to `0.30.0` also seems to have fixed the issue for me.

**Comment by waleedarshad-vf** [comment]
same error with RN 0.27.2

**Comment by ide** [comment]
Closing this issue since it's only happening with old versions AFAIK. Please open a new issue if the problem described in the first post is happening with RN 0.33+.

**Comment by MarkPare** [comment]
Similar error is preventing me from using Chrome dev tools for debugging React Native app.

`WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED` 

node v7.2.1
react-native-cli: 1.2.0
react-native: 0.44.0

**Comment by psoulages** [comment]
Hello MarkPare,

I am having the same issue, inside react-native debugger console error follows: WebSocket connection to 'ws://localhost:8081/debugger-proxy?role=debugger&name=Chrome' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

My Terminal is red and reads 'No Bundle URL Present'. Weird enough, my others aps I have made in the same folder don't have this issue. 

react": "16.0.0-alpha.6",
    "react-native": "^0.42.3",
    "react-native-router-flux": "^3.39.1",
    "react-redux": "^5.0.5"


Has anyone come across this recently?

**Comment by psoulages** [comment]
@MarkPare  ^ :)

**Comment by WwoeSsi** [comment]
Getting this on RN 0.45.1 :(

**Comment by salilbajaj** [comment]
Same Issue RN 0.45.1

**Comment by LAITONEN** [comment]
Same issue RN 0.47

**Comment by BarthesSimpson** [comment]
Me too

**Comment by Prateek479** [comment]
+1 same error in debugger  , getting hard day by day to use RN :(

**Comment by Joeyrodrigues92** [comment]
Same issues 

"react": "16.0.0-beta.5",
   "react-native": "0.49.3",
 "react-redux": "^5.0.6",

**Comment by anerivala** [comment]
Having the same issue...

**Comment by Speudyland** [comment]
+1 same error in debugger

**Comment by erwinwahyura** [comment]
Having the same issue...

**Comment by IvanIvaschenko** [comment]
having same issue.
"react": "^16.2.0",
"react-native": "^0.52.0".
Mac OS.

**Comment by Deno028** [comment]
having same issue after update to:
"react": "^16.2.0",
"react-native": "0.52.1"
running android emulator 
MacOS

**Comment by WojciechCendrzakXS** [comment]
having the same issue:
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.1",
iOS

**Comment by EsdrasEtrenne** [comment]
When this happened to me I had the computer simulator and the device running at the same time. So it might have something to do with conflicting simulators

**Comment by sarneetk** [comment]
What fixed the issue for me => cleared my local cache using `yarn clear cache` then did a `yarn install` and ran the app again.

**Comment by leoabacade** [comment]
same issue
"react": "16.3.1",
 "react-native": "0.55.4",

**Comment by tapumandal** [comment]
If you are using pusher server use **cluster**. I think error will be gone.

**Comment by PLopezD** [comment]
Any solution?

**Comment by aswinehart** [comment]
Having the same issue with RN 0.55.0
