### ISSUE TITLE
"Linker command failed with exit code 1" when including a Swift Framework.

### ISSUE THREAD

**Issue by joshuapinter** [facebook/react-native#6630]
I have a **very** simple Swift Framework that I'm trying to include in a react-native project, following the [official guide](/Users/joshuapinter/Development/TestUnifiedContacts/node_modules/react-native-unified-contacts-objc). 

The error I get is: 

![screenshot 2016-03-24 11 11 53](https://cloud.githubusercontent.com/assets/180819/14024934/40e7d28e-f1b1-11e5-8ede-dd4c9e2e7376.png)

```
"_RCTRegisterModule", referenced from:
+[HelloWorld(RCTExternModule) load] in HelloWorldBridge.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My Swift framework files look like this: 

**HelloWorld.swift**
```swift
import Foundation

@objc(HelloWorld)
class CalendarManager: NSObject {
    
    @objc func myHelloWorld() -> Void {
        NSLog("In myHelloWorld!")
    }
    
}
```

**HelloWorldBridge.m**
```objc
#import <Foundation/Foundation.h>

#import "RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(HelloWorld, NSObject)

RCT_EXTERN_METHOD(myHelloWorld)

@end
```

**HelloWorld-Bridging-Header.h**
```objc
#import "RCTBridgeModule.h"
```

Things I've done: 

* I've added the correct path to `Header Search Path`.
* Added `.framework` to `Embedded Binaries` and `Linked Frameworks and Libraries`.
* Disabled `Bitcode` for both the parent and framework projects. 
* Turned off `Dead Code Stripping` on both the parent and framework projects.
* Prayed to any god that'll listen but I haven't heard anything back. Ever.

I'm using React Native Version **0.22.0**.

Any help on this would be fantastic.

Thanks!

Josh

**Comment by joshuapinter** [comment]
Shit, sorry. Hit <Enter> prematurely by accident.

**Comment by rops** [comment]
Seems like the problem is with linking. I would double check that React.framework is linked to your target. All the steps seem correct

**Comment by joshuapinter** [comment]
Thanks @rops. I ended up creating a workspace instead of a framework and just importing that into my project. Not sure if I could get the .framework technique working but maybe I'll try again in the future. 

I'll close this for now. Thanks again.
