### ISSUE TITLE
Chrome debugging broke in 0.22 (weird breakpoints, no variables shown/console.log'able)

### ISSUE THREAD

**Issue by aforty** [facebook/react-native#6631]
Hi there,
I upgraded from 0.20 to 0.22 and Chrome debugging went completely off the rails. I had no issue before updating to 0.22. I'm attempting to debug in an iOS project on Chrome 49.

Some sample code just to demonstrate what I mean.

```
function (someVariable) {
  let someOtherVariable = 123
    , somePromise = getSomePromise(someVariable);

  somePromise.then(r => {
    if (r.someCondition) {
      doSomething(r);
    }

    doSomethingElse();
  });
  
  ...
}
```

- Setting breakpoints acts strangely as it sometimes jumps down a line or two. If I try to add a breakpoint on the `if` line, it will actually end up adding it to the empty line above `doSomethingElse()`.
- Variables don't show correctly. If I set a breakpoint on `somePromise.then(r => {` (line 4) and I hover over `someOtherVariable` then Chrome Debugger won't show anything. If I go into the console and type `console.log(someOtherVariable)` I get an error `VM144:1 Uncaught ReferenceError: someOtherVariable is not defined(…)`. I can view the value of `someVariable` just fine if I hover over it, this variable was passed into the method.

These issues are sporadic and not very consistent and I haven't noticed any pattern as to when it happens and doesn't happen. Very odd behavior and I'm not sure what I can do about this.

**Comment by ide** [comment]
`someOtherVariable` is no longer lexically referenced from that point on in the program so Chrome / V8 might mark it as eligible for cleanup, hence the non-determinism.

**Comment by satya164** [comment]
Does it happen with master or 0.23-rc?

**Comment by aforty** [comment]
That was a sample @ide, in my actual code that variable is still referenced. My apologies. 

I just downgraded to 0.21 and can confirm that it's working again. Let me try 0.23-rc real quick.

**Comment by aforty** [comment]
@satya164 Indeed it appears to be working on 0.23-rc1.

Looks like whatever the issue was will be fixed going forward, but let me know if there is any more information I can provide on this.

**Comment by satya164** [comment]
@aforty Thank you.

**Comment by MaxiSantos** [comment]
I see this bug with RN 0.53.. I tried with the trick of renaming all function with arrow funtions. Still the same bug
