### ISSUE TITLE
Unable to run UIExplorer project [Android][Windows]

### ISSUE THREAD

**Issue by efkan** [facebook/react-native#6637]
I've been trying to run UIExplorer project on Windows. I am getting the following error-

> ...
> ...
>  make: *** [D:\react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/reactnativejni/JExecutorToken.o] Error 2
> ...
> ...
> * What went wrong:
> Execution failed for task ':ReactAndroid:buildReactNdkLib'.
> > Process 'command 'C:\android-ndk-r11b\ndk-build.cmd'' finished with non-zero exit value 2
> ...
> ...
> Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\android-ndk-r11b\ndk-build.cmd'' finished with non-zero exit value 2

Is there any chance to overcome this issue?

**Comment by satya164** [comment]
We don't support latest NDK yet. Please download this version and try - http://dl.google.com/android/repository/android-ndk-r11b-windows-x86_64.zip

**Comment by satya164** [comment]
@facebook-github-bot answered
