### ISSUE TITLE
[0.23.0-rc1]Unable to resolve modules AssestRegistry when require image inside node_modules

### ISSUE THREAD

**Issue by evollu** [facebook/react-native#6638]
I have code like 
\<Image source={require('react-native-router-flux/src/back_chevron.png')} style={{height: 100, width: 100}}/\>  in my app and it works fine in 0.22.2

but in 0.23.0-rc1 system throws "Unable to resolve modules AssestRegistry [path to back_chevron.png" in IOS, and "Requireing unknown module "AssestRegistry"" in Android

**Comment by RWOverdijk** [comment]
:+1:

**Comment by philipshurpik** [comment]
Confirm - if require image inside project - it works
If image is required in library (that is placed in node_modules) - not working

**Comment by mkonicek** [comment]
Might be caused by: https://github.com/facebook/react-native/commit/06b5bda34923b68ba5141e78c36ccbdc5f4bcff1

ETA for a fix next week.
