### ISSUE TITLE
[Android] InteractionManager.runAfterInteractions not getting executed?

### ISSUE THREAD

**Issue by skleest** [facebook/react-native#6643]
I am building an Android equivalent of a production app in iOS. First of all, unbelievable performance on both platforms--thank you.

I have been using InteractionManager.runAfterInteractions in componentDidMount in most major views as recommended to make transitions smooth, and it's been working well on iOS. However, on Android, InteractionManager.runAfterInteractions does not execute the callback function (RN 0.21), even simple console.log. No error messages or anything and wanted to ask for quick help. Thank you.

**Comment by skleest** [comment]
Realized interaction manager works fine in non-dev mode.

**Comment by burgalon** [comment]
Why isn't it called on __DEV__ env?!

**Comment by jreziga** [comment]
Still an issue for me... Why all issues are closed without any explanations ?

**Comment by satya164** [comment]
@jreziga The author closed the issue.

This might be related - https://github.com/facebook/react-native/issues/8624
