### ISSUE TITLE
[Android]Can't reload js from dev server after upgrading from 0.21 to 0.22

### ISSUE THREAD

**Issue by dentrite** [facebook/react-native#6645]
windows8 android4.1.1 react-native@0.22.2
After upgrading from 0.21 to 0.22, reload js and live reload don't work anymore. Downgrading back to 0.21, everything works fine. 
## Update

Brand new project also has the issue.

**Comment by lyandrew** [comment]
I'm able to reload js and live reload just fine - using window 10, android 6.0, and react-native 0.22. 

I'm also using an emulator from android virtual device manager.

**Comment by christopherdro** [comment]
@dentrite Did you make sure to restart the packager after upgrading?

**Comment by dentrite** [comment]
@christopherdro Yeah I did restart the packager, and also rebuilt the app

**Comment by christopherdro** [comment]
@dentrite It appears there were a few issues surrounded 0.22 and it appears to be not that stable of a release. Could you  possibly try on 0.23-rc and see if works? Thanks!

**Comment by dentrite** [comment]
@christopherdro 0.23.0-rc1 still don't work for the existing project. A new project base on 0.22.2 seems to be fine after the upgrading.

**Comment by tal952** [comment]
+1

**Comment by Bing-Xia** [comment]
I met the same issue, both tried in real device and emulator, reload js not working at version 0.22, and android version is 6.0, now I'm trying to downgrade to 0.21

**Comment by xcchcaptain** [comment]
win10 ,android 6.0,0.23  ,i met the same problem

**Comment by torrchula** [comment]
Same issue (Not seeing changes after reloading) on RN 0.24.1, Windows 10, Android 4.4.4 on Genymotion.

**Comment by torrchula** [comment]
Issue still exists on RN 0.25.1 (Windows10, Android 4.4.4 on Genymotion).

**Comment by torrchula** [comment]
After I start the packager, by issuing react-native start, for the second time after creating a new RN 0.25.1 project, all reload features (Reload JS, Hot Reloading, Live Reload) seems to work well.  Will try on an upgraded project.

**Comment by torrchula** [comment]
I have upgraded project from 0.21 to 0.25.1 on Windows 10 , Android 4.4.4 on Genymotion, the reload didn't work right after upgrading.  However, after trying the following many times, the reload becomes working !  Not really know the exact sequence to make it work.
- Issue "react-native run-android"
- Issue "react-native start"
- Enable/disable hot reloading and live reload

**Comment by gendronb** [comment]
Windows 10, physical device running on Android 5.1.1, RN 0.26.2, same problem...

**Comment by jing2si** [comment]
RN 0.28.0，same problem,back to RN 0.27.0,it's work fine.

**Comment by harry008** [comment]
I am also having the same problem. I'm on windows8.1. RN 0.28.0 and Node 6.2.0 with genymotion. No changes are detected at all. :disappointed: also taking too much time for loading.

**Comment by SadeghAlavizadeh** [comment]
I have same problem with RN 0.29.0, Windows 8.1 and Genymotion.

**Comment by juanpasolano** [comment]
I think I am having the same issue with 0.30.0, Mac and Genymotion. It doesn't refresh any changes I make to the code.

**Comment by leglars** [comment]
+1
RN 0.30; emulator android 6.0;   win10
it works at last version. It seems happen after upgrade

**Comment by Arkanine** [comment]
The same err, RN 0.30 7.3 Xcode

**Comment by hongphi** [comment]
The same issue RN 0.31, Window 10 and Genymotion

**Comment by hongphi** [comment]
Run react-native start manual after run react-native run-android when app loaded. It work fine (RN 0.31).

**Comment by StudioPassDE** [comment]
The same issue RN 0.32.0, Webstorm, Android, Genymotion. Each time now I have to stop the packager and load it again to view the changes. Its so horrible. Can somebody give a solution.

**Comment by ldegrazia** [comment]
I am using VS Code, RN 0.31 and the Android emulator on Windows 10. Seems like I have to save the file, then, in the emulator, keep hitting rr on my keyboard. While debuggig in VS code, eventually I see "Connecting to remote debugger" and my changes appear.

**Comment by Fandekasp** [comment]
Having the same issue with RN 0.32.0, emulator from Android Studio 2.1.3 and Android 6.0. Not being able to use hot reloading is really painful...

**Comment by yuzhewo** [comment]
Mac ,android 7.0, 0.36 ,the same problem

**Comment by MatthiasDebaere** [comment]
Windows 10, Android 6.0, 0.36, same problem

**Comment by NeroDOC** [comment]
I found the way to fix this issue.
We need to set up "PATH" environment variable with address "%ANDROID_HOME\tools" (Example "D:\Android\SDK\tools")

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
