### ISSUE TITLE
[Docs][AlertIOS] Prompt button examples failing in appetize.io sim

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6648]
Just a heads up I'm seeing a red screen of death (n.forEach is not a function, or invariant violations) for just the prompt button section of the AlertIOS examples:
http://screencast.com/t/Zlvhxp3uBG

P.S. Awesome use of appetize.io!

**Comment by grabbou** [comment]
Sounds like it just works as of now -> https://facebook.github.io/react-native/docs/alertios.html#content.
