### ISSUE TITLE
update to V0.22.2,ListView not work well

### ISSUE THREAD

**Issue by zjhsd2007** [facebook/react-native#6650]
node V4.4.1
npm V3.8.2
react-native V0.22.2
platform:android

I made a drop-down to refresh the data, the effect of tensile load on the next page data, in V0.19 is good, but after update to V0.22.2, after loading the next page data, the data is not rendered.
here is the part of code
```javascript
    pageIndex = 0;
    data = [];

    fetchData() {
        this.setState({isLoading: true});
        fetch(url)
            .then((response) => response.json())
            .then((responseData) => {
                this.data = this.pageIndex === 0 ? responseData : this.data.concat(responseData);
                console.log(this.data);
                this.setState({
                    dataSource: this.state.dataSource.cloneWithRows(this.data),
                    isLoading: false
                });
                ++this.pageIndex;
            }).done();
    }
```
log this.data is right,but can not rendered.

**Comment by PeterKow** [comment]
I have the same issue with 0.22 version

I want to update view whenever I get new props
```javascript
 componentWillReceiveProps(nextProps) {
    const { menu } = nextProps
    const mappedKeys = mapSectionAndRows(menu)
    console.log('compareSection', menu)

    this.setState = {
      dataSource: this.state.dataSource.cloneWithRowsAndSections(menu, mappedKeys.sections, mappedKeys.rows),
    }
  }
```

also I am hooking everything in a constructor
```javascript
constructor(props) {
    super(props)

    const { menu } = this.props
    const ds = new ListView.DataSource({
      getRowData,
      rowHasChanged: compareRow,
      sectionHeaderHasChanged: compareSection,
    });

    const mappedKeys = mapSectionAndRows(menu)

    this.state = {
      dataSource: ds.cloneWithRowsAndSections(menu, mappedKeys.sections, mappedKeys.rows),
    }
  }
```

those are my compare functions
```javascript
function compareRow(r1, r2) {
  console.log('compoare rows ', r1.active !== r2.active)
  return r1.active !== r2.active
}

function compareSection(r1, r2) {
  return r1 !== r2
  //return r1.items[0].active !== r2.items[0].active
}
```

In console log I can see that after update `compareRow` method is being called and there is one change, but `_renderRow` still gets old value

![screen shot 2016-03-29 at 17 20 06](https://cloud.githubusercontent.com/assets/10186048/14115352/8aba0376-f5d2-11e5-87e8-5e7ac046dd42.png)

I was debugging react-native code and flags for dirtyUpdate are se, but view is rerendered with old values

**Comment by PeterKow** [comment]
I had simple bug in `this.setState = {`, instead of calling a function I overwrite it

working code:
```javascript
 componentWillReceiveProps(nextProps) {
    const { menu } = nextProps
    const mappedKeys = mapSectionAndRows(menu)
    console.log('compareSection', menu)

 this.setState({
      dataSource: this.state.dataSource.cloneWithRowsAndSections(menu, mappedKeys.sections, mappedKeys.rows),
    })
  }
```

Although I had to downgrade my RN version to 0.19, because of the performance problems on Android, so can't tell if it works on 0.22

**Comment by grabbou** [comment]
@zjhsd2007 can you provide the full component? To me it looks like an implementation error (been testing ListViews earlier today to answer other issues and everything was fine).

**Comment by zjhsd2007** [comment]
@grabbou , i change the data structure，then it`s works,such as change 
```javascript
{
    a:1,
   b:{
      c:2
   }
}
```

change to 
{
   a:1,
   c:2,
}

**Comment by damusnet** [comment]
@facebook-github-bot close

**Comment by grabbou** [comment]
@zjhsd2007 glad you sorted it out! Please check out StackOverflow in case you have any other questions regarding ListViews - generally you should either provide an array when you are dealing with rows only or an object with sections when using `cloneWithRowsAndSections`. Some useful examples of how `dataBlob` should look like are included in the ListView documentation you may find interesting as well.
