### ISSUE TITLE
make RN Android as .aar library?

### ISSUE THREAD

**Issue by WenruiCui** [facebook/react-native#6651]
I wan't to know how can make my Android RN project as library such as aar package?
Now , when I build an aar library , I find I can't put bundle file into my assets folder

**Comment by rops** [comment]
@facebook-github-bot stack-overflow

**Comment by bestander** [comment]
@facebook-github-bot stack-overflow

**Comment by sibelius** [comment]
@WenruiCui did u figure it out?

Check this SO question: http://stackoverflow.com/questions/33555530/gradle-aar-dependency-resolution-in-react-native-project

**Comment by vraghavachari** [comment]
Refer to [this SO link ](https://stackoverflow.com/questions/45099025/how-to-build-react-native-project-to-aar-library/48553105#48553105)
