### ISSUE TITLE
Set duration is not work for spring animation on android

### ISSUE THREAD

**Issue by liuchungui** [facebook/react-native#6653]
I want to make spring animation, and when animation stop, I will render again. But when i set duration, that not work for me. 

Here's my code.
```
    this.state.translateX.setValue(80);
    Animated.spring(
      this.state.translateX,
      {
        toValue: 0,
        friction: 1,
        tension: 50,
        duration: 1000,
      }
    ).start( (ret) => {
      this.setState({
        enterPassCode: '',
      });
    });
```
My react-native version is 0.21.0，0.22.0 was solved ?

**Comment by brentvatne** [comment]
Hi there! Springs don't take a duration option -- the duration of the animation depends on the friction and tension.

**Comment by liuchungui** [comment]
@brentvatne Thank you very much!
