### ISSUE TITLE
onEndReached doesn't work as expected using ListView on Android

### ISSUE THREAD

**Issue by cubbuk** [facebook/react-native#6656]
When I try render a list of items using ListView, `onEndReached` method of `ListView` is triggered without any interaction, as far as I understood it should only be called whenever all rows of the datasource is rendered but it doesn't work as it intended. It renders all the rows given to its datasource regardless of whether they are displayed on the screen or not.

I already asked a question on Stackoverflow and explained the details over there: 

http://stackoverflow.com/questions/36218698/onendreached-doesnt-work-as-expected-using-listview-on-android-with-reactnative

React-Native version: 0.22
Mobile Platform: Android and IOS

Does anyone have any idea what might be the problem?
Thanks

**Comment by cubbuk** [comment]
I guess I understood my problem. My ListView was under a ScrollView component as I had a search box in the same view. After moving ListView outside of the ScrollView it started to work as expected. I was also able to add search box under ListView using renderHeader prop.

**Comment by Pilon** [comment]
sou gay
