### ISSUE TITLE
Guide for publishing modules with native iOS / Android code

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#6661]
It would be great to port http://brentvatne.ca/packaging-react-native-component/ to the docs, update it, and write an Android equivalent. Good task for interested contributor!

Bonus: integrate with rnpm (@kureev @grabbou)

**Comment by grabbou** [comment]
Looks really cool! It should work `as is` with rnpm (at least iOS since we don't really care which structure you pick), but if we could automate that as a part of `react-native init xyz` - it would be really really cool.

**Comment by grabbou** [comment]
Is there anyone extensively working on this? If not, I'd assign it to myself and write iOS part.

**Comment by Hari70a** [comment]
@brentvatne and @grabbou 
 I have submitted the PR for updating the document .
https://github.com/facebook/react-native/pull/7323

**Comment by lacker** [comment]
Closing this issue as a dupe
