### ISSUE TITLE
Listview DataSource error

### ISSUE THREAD

**Issue by edelworksgithub** [facebook/react-native#6673]
Hi I am using react-native version 0.21.0
`var  ds = new ListView.DataSource({
        rowHasChanged: (row1, row2) => row1 !== row2,
      });`
is showing the below error (Android). I am developing the app in Mac.
![screenshot_2016-03-26-20-48-52_com tasksandmetricsmanagement](https://cloud.githubusercontent.com/assets/8638256/14060813/b788ff2c-f395-11e5-856a-30d23364b8dc.png)

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by edelworksgithub** [comment]
Please let me know, if this bug is because of me or react-native.
This is really urgent.
