### ISSUE TITLE
Filewatcher doesn't seem to work on Windows

### ISSUE THREAD

**Issue by AleCaste** [facebook/react-native#6674]
Hello,
I am using react native on Windows 7 64bit, deploying an Android app on a real device (not using an emulator).
Everything works fine, the JS bundle gets loaded an all BUT any changes I make to the js files won't show up on the app.
I can force the app to reload the JS bundle but still the js files that get loaded seem to be the very original ones, without any of the changes I make.
One thing I noticed is that the packager does not output anything new on its log whenever I make modifications to the js files (not even on 'index.android.js' !!!)
I understand that watchman is NOT being used by the sane filewatcher on Windows. So whatever it is sane is using, it is not working on my system.
When I start the packager I can see things like these on the log:
```
<START> Crawling File System
...
<END>   Crawling File System (432596ms)
```

The crawler takes quite a while to do its job, but still it seems to finish its tasks just fine without timing-out or producing any errors.
But still if I make modifications to the 'index.android.js' the packager won't pick them up and reloading the js bundle on the app will show the original version everytime.
I consider this to be a VERY important issue since I am forced to run the command ```react-native run-android``` and this takes a while.
Some people has reported this on stackoverflow:
http://stackoverflow.com/questions/35670753/react-native-cant-see-changes-to-my-code
... so at least I can see I am not the only one.
By the way, I don't know if this issue could be related to: https://github.com/facebook/react-native/issues/6318
Any info you may request from my configuration to resolve this, please let me know.
Alex

**Comment by janicduplessis** [comment]
What version of react-native and node are you using? Also just to make sure, if you open `http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false` in your browser when the packager is running can you see you code changes?

**Comment by AleCaste** [comment]
Hello!
I have found out what is going on.
The watcher being used (NodeWatcher on Windows) is working fine.
But I can see 2 problems:

1. The first one is that crawling the files/folders takes too long on my system (around 5 minutes) so the ```MAX_WAIT_TIME``` time is reached. That is fine but me -as a user- had no means of realizing this was happening since the packager was not reporting this error to me. The error should be reported by the packager, mentioning the MAX_WAIT_TIME variable so people running react-native for the first time can know how to fix this situation.

2. NodeWatcher does emit 'change' events on files even before it finishes crawling all folders (so even before the 'ready' event is emitted). This is VERY useful on slow machines like mine (not having to wait until the WHOLE folder structure is crawled!).
But looking at the node-haste FileWatcher class I can see that events from watchers are ONLY listened to and emitted up to the caller when ALL watchers are 'ready'. Could this be changed?
So on the '_createWatcher' block, instead of having:
```
function _createWatcher(rootConfig) {
  var watcher = new WatcherClass(rootConfig.dir, {
    glob: rootConfig.globs,
    dot: false
  });

  return new Promise(function (resolve, reject) {
    var rejectTimeout = setTimeout(function () {
      return reject(new Error(timeoutMessage(WatcherClass)));
    }, MAX_WAIT_TIME);

    watcher.once('ready', function () {
      clearTimeout(rejectTimeout);
      resolve(watcher);
    });

  });
}
```
... could we have something like this?
```
function _createWatcher(rootConfig) {
  var watcher = new WatcherClass(rootConfig.dir, {
    glob: rootConfig.globs,
    dot: false
  });
  var _this = this;

  return new Promise(function (resolve, reject) {
    var rejectTimeout = setTimeout(function () {
      return reject(new Error(timeoutMessage(WatcherClass)));
    }, MAX_WAIT_TIME);

    watcher.once('ready', function () {
      clearTimeout(rejectTimeout);
      resolve(watcher);
    });

    watcher.on('all', function () {  // args = (type, filePath, root, stat)
      for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
        args[_key] = arguments[_key];
      }
      return _this.emit.apply(_this, ['all'].concat(args));
    });
    
  });
}
```
As you can see I have added the ```watcher.on('all',``` listener there right after the 'ready' listener.
This way the change events will be emitted even before the watchers have finished crawling the folders.
I have no idea if this is the right way of doing but on systems like mine it would be VERY helpful.

Best regards,
Alex

**Comment by janicduplessis** [comment]
Hey Alex, thanks for the detailed report. I agree we could really improve the messages here to make sure it is clear what is going on. Not sure why the NodeWatcher is that slow on your system, it takes around 30sec on mine. You can also try watchman alpha for windows I had no issues using it and the packager starts in ~10sec https://facebook.github.io/watchman/docs/install.html.

As for improving the messages would you be down to submit a pull request implementing something like you linked in the above post?

**Comment by AleCaste** [comment]
Hello,
Thanks for the advice. I installed watchman and I noticed a significant improvement on speed!
Watchman only takes a few seconds to crawl the folders in comparison to those 5 minutes NodeWatcher takes on my system.
... but... the app reports an error when I reload the JS bundle (note that if I use NodeWatcher I can reload the bundle just fine!)
See error being reported:

![screenshot_2016-03-28-12-37-15](https://cloud.githubusercontent.com/assets/6316907/14087831/87016a26-f4f1-11e5-9812-b93dec5c0b2e.png)

By the way, I'll submit a pull request on node-haste filewatcher file since there are a few improvements that can be done (one of them is to do with the fact that the timeout error is silently swallowed by the promise code block meaning that the user never gets to see the error reported on the packager log).

Alex

**Comment by ThaJay** [comment]
This is an issue for me as well. The packager seemed to be working before, but on 0.23 it does not refresh the js. Crawling the filesystem always took me about 170 - 200 sec. so that's not workable.
I'm on win10 using git bash.

```
$ node -v
v5.9.1
 $ react-native -v
react-native-cli: 0.2.0
react-native: 0.23.1
```
android/app/build.gradle
```
compile "com.android.support:appcompat-v7:23.0.1"
```
will try out watchman or something

**Comment by pravin-d** [comment]
https://github.com/facebook/react-native/issues/6674

**Comment by janicduplessis** [comment]
I just downloaded the binary on their site and put it somewhere in my PATH.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/filewatcher-doesnt-seem-to-work-on-windows

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by Noor0** [comment]
i am having the same issue, packager logs nothing when i save changes made to file and nothing changes on reloading the app both on emulator or the device

**Comment by Silviu-Marian** [comment]
`node_modules/react-native/packager/react-packager/src/Server/index.js`

~line 86 
```js
const bundleOpts = declareOpts({
  forceRebuild: {
    type: 'boolean',
    default: false,
  },
```

~ line 443
```js
const building = !options.forceRebuild && this._bundles[optionsJson] || this.buildBundle(options);
```

~line 558

```js
forceRebuild: this._getBoolOptionFromQuery(urlObj.query, 'forceRebuild', false),
```

I know just how bad this is, but nothing else come to mind.
Right now I'm profiling an existing app, so I don't mind rebuilding manually.

I suppose you can mix https://github.com/thomasfl/filewatcher with http://gnuwin32.sourceforge.net/packages/wget.htm to touch that URL automatically.

**Comment by reza7rm** [comment]
I am facing the same issue right now and have no fixes so far
@Silviu-Marian  I can't find the path you mentioned, there's no packager folder in node_modules/react-native/

Development OS: Win 7
react-native-cli: 2.0.1
react-native: 0.47.1
node-v: 6.11.2
npm -v: 3.10.10
yarn --version: 0.27.5
device android version:6.0.1

**Comment by mistypix** [comment]
any solutions to this yet?
