### ISSUE TITLE
EXC_BAD_ACCESS in RCTComponentData

### ISSUE THREAD

**Issue by mpretty-homepass** [facebook/react-native#6677]
@nicklockwood I've managed to track this crash down to this change: https://github.com/facebook/react-native/pull/6411/commits/62177dbb3b4d4bdedf0c7a6fe9140ce049743fbf specifically to the changes in the setterBlock here https://github.com/facebook/react-native/blob/master/React/Views/RCTComponentData.m#L203

The crash I'm seeing is occurring when using https://github.com/maxs15/react-native-spinkit within the 'renderLoading' of a WebView. RNSpinKit has an NSNumber property called 'size'; it looks like there may also be an internal property called 'size' which is returning a non-object type causing an EXC_BAD_ACCESS (see http://stackoverflow.com/a/24232523 for a nicer explanation). To verify this, using in the following code does not crash (a CGSize of (0,0) is set):

```
if ([key isEqualToString:@"size"]) {
    CGSize (*get1)(id, SEL) = (typeof(get1))objc_msgSend;
    CGSize tmp = get1(target, getter);
}
else {
    defaultValue = get(target, getter);
}
```

Not sure what the best course of action would be in this case. Obviously I can do a PR to RNSpinKit to rename the 'size' property and that will prevent the crash in that case but it means if someone unintentionally uses the same property name as an internal non-object type variable this could crash solely on wether or not objc_msg_send finds that selector or the correct one first.

Any thoughts on how we could avoid these potential issues?

We could try NSInvocation (http://stackoverflow.com/a/8406133) but since it's slow having every property getter run through it is probably going to be problematic. Another option could be to check the return type (http://stackoverflow.com/a/19960352) against the values in this table https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html and if it isn't an object throw a warning? (through I'm not sure what kind of performance hit this would cause)

**Comment by nicklockwood** [comment]
This looks like a bug in the implementation of RNSpinKit. Properties exported via RCT_EXPORT_VIEW_PROPERTY are supposed to be readwrite, but you've only implemented setters, with the result that the "set" type is NSNumber, but the "get" type is CGSize.

If you declared these as @properties, and/or implemented the getter methods for them, the problem would go away.

We could probably introduce an extra check to verify that the first argument of the setter method is the same type as the return value. I'm not convinced that this will come up often enough to be worth doing that though.

**Comment by mpretty-homepass** [comment]
@nicklockwood Ah damn, sorry about that, I guess I should have taken a better look. I'll do a PR to fix the issue in RNSpinKit and I'm not sure how difficult it would be to catch and throw a different error as EXC_BAD_ACCESS is very nondescript (and leads down the rabbit hold I followed).

Will link the PR to this issue and then close.

**Comment by mpretty-homepass** [comment]
Looks like adding the getters fixed the issue, have created the PR on RNSpinKit (https://github.com/maxs15/react-native-spinkit/pull/8). Thanks for the help @nicklockwood
