### ISSUE TITLE
Move project to new directory will stop react server autorun feature

### ISSUE THREAD

**Issue by phamhieu** [facebook/react-native#668]
After creating react native project with 
```
react-native init [ProjectName]
```
When running the project in XCode, the react server will always auto run.

However, when move the project to a new directory, the react server will stop autorun. I have to manually call ```npm start```
Does we need to setup anything or any method like ```react-native update [ProjectName]``` to enable the autorun feature again?

**Comment by sahrens** [comment]
Are there any errors?  The packager autorun is done as part of a build script in React.xcodeproj.

**Comment by phamhieu** [comment]
There is no error. Just the simulator complains that It connot connect to the server. 



—

**Comment by brentvatne** [comment]
> However, when move the project to a new directory, the react server will stop autorun. I have to manually call npm start

I tried this on my own and this works fine, will reopen if you are still having the issue. If so, please explain step by step exactly what you're doing and we can try to narrow it down :smile:

**Comment by phamhieu** [comment]
"It turns out that my project is moved to a folder with "space" character in the name. So the run script fail to run."

I have a [push commit](https://github.com/facebook/react-native/pull/699) to fix the issue.

**Comment by brentvatne** [comment]
Thanks @phamhieu!
