### ISSUE TITLE
Chat panel

### ISSUE THREAD

**Issue by abhishekmedipta** [facebook/react-native#6684]
There is a bug in facebook in chat, there is a chat panel in right side of facebook page, when there are lots of people are online and that time, if we scroll the scroll bar, then last user are not showing properly.

see the attachment..
![screenshot 100](https://cloud.githubusercontent.com/assets/16331239/14066298/7d7f2c06-f463-11e5-9a4f-91d43de53a3f.png)

![screenshot 100 _3](https://cloud.githubusercontent.com/assets/16331239/14066347/bedf3140-f464-11e5-86cf-634cd44c2d04.png)

**Comment by chirag04** [comment]
@facebook-github-bot close

**Comment by chirag04** [comment]
@abhishekmedipta This is not the right place to report bug on facebook.com. I'm sure there is a better place to do that in a more secure and better way.

**Comment by abhishekmedipta** [comment]
@chirag04 Can u please tell where i can report this issue, please tell me right repository.
