### ISSUE TITLE
Style lineHeight attribute not working as well as H5

### ISSUE THREAD

**Issue by xueduany** [facebook/react-native#6690]
![image](https://cloud.githubusercontent.com/assets/1139866/14077835/98c2a1e0-f522-11e5-95f5-093fb4f151bd.png)

**Comment by cuitianze** [comment]
本来就不一样 ~。~

**Comment by magicismight** [comment]
那是叫web，真不知道H5这词谁想出来的，管随便什么东西都叫H5

**Comment by Kureev** [comment]
Я смотрю отличный диалог получается

**Comment by Kureev** [comment]
@facebook-github-bot stack-overflow
