### ISSUE TITLE
[Android] append items into ListView cause app crash

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#6701]
On Android device when appending item into ListView sometimes the js thread will drop to -2fps and crashed with those info:

`A/libc: Fatal signal 11 (SIGSEGV) at 0x87a40044 (code=2), thread 24083 (mqt_js)`

react-native: 0.22.2
nodejs: 5.9.1

**Comment by magicismight** [comment]
same code works fine in 0.20.0
but will crash in 0.21.0 and above if ListView scrolls fast in Android monitor and the device with low  hardware configuration

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by magicismight** [comment]
It seems only happened when the JS Dev Mode is on.
After I turned off the JS Dev Mode. It won`t happend any more

**Comment by prtkkmrsngh** [comment]
Yes this used to happen in Dev Mode....irrespective of the react-native version used.

**Comment by lacker** [comment]
It seems like this is fixed now. I'm going to close this issue but feel free to reopen it if there is still a problem in RN master.
