### ISSUE TITLE
ListView + renderSeparator => Incorrect reporting in onChangeVisibleRows

### ISSUE THREAD

**Issue by dlahyani** [facebook/react-native#6702]
Hey there.

I am using `ListView` to render an array of items, and after each item row i render some separator view (just a 1-pts height empty view with a grey background color) via the `renderSeparator` property of `ListView`.
I added a handler for the `onChangeVisibleRows` to my `ListView` in order to track which item is currently on the top of the list view. When i examined to `visibleRows` argument passed to my `onChangeVisibleRows` handler i noticed that it contains ~x2 items than actually visible. For example if the list-view visible rows have these ids `['0', '1', '2']` then the `visibleRows` argument will be `['0', '1', '2', '3', '4', '6']`. 

I was wondering for a while where these extra items come from, and then after playing with the properties of the list view i noticed that if i remove the `renderSeparator` property the `ListView` reports the correct set of `visibleRows`. It seems that `ListView` treats the separators as rows and counts them together with visible rows.

Here's a small code sample that should reproduce the error:
https://gist.github.com/dlahyani/f76b15919541285cc7aa

My build environment is XCode on Mac OS and I tried this on iOS only.

**Comment by dmueller39** [comment]
@vjeux Any suggestions on what we need to do for https://github.com/facebook/react-native/issues/6965  ? Should contributors just pick a reviewer when they create a PR?

**Comment by sibelius** [comment]
@dlahyani @dmueller39 this is fixed on master, could please close this?

**Comment by dlahyani** [comment]
@dmueller39 thanks for the fix.
