### ISSUE TITLE
CoreLocation API?

### ISSUE THREAD

**Issue by lenage** [facebook/react-native#671]
Anyone consider to make CoreLocation API available in React Native?

so, we can use iBeacon and other things..

**Comment by vjeux** [comment]
I don't think that anyone is working on it at the moment, would be nice if you could take a stab at it :)

**Comment by sahrens** [comment]
We have geolocation support from CoreLocation (check out GeolocationExample.js), but not beacon support.

**Comment by lenage** [comment]
Thanks, I will try it out :)

**Comment by brentvatne** [comment]
@lenage - Looking forward to seeing what you come up with! Let us know on irc when you have something. Can you close this issue now?

**Comment by lenage** [comment]
Yes, i'm closing it :)

**Comment by JoeStanton** [comment]
I've also been playing around with this FYI. Might have something in a few days...

**Comment by ouelletv** [comment]
Been looking toward this also. Let me know if you get to something :) +1

**Comment by frostney** [comment]
If you're looking for beacon support specifically, here's something I've been working on: https://github.com/geniuxconsulting/react-native-ibeacon

**Comment by brentvatne** [comment]
@frostney - awesome! can you submit a PR to add that to https://github.com/ericvicenti/react-native-community ?
