### ISSUE TITLE
Different value of AsyncStorage.multiGet for IOS and Android @0.19

### ISSUE THREAD

**Issue by marcelijanowski** [facebook/react-native#6712]
I have a code when user login in:
```
AsyncStorage.multiSet([
          ['@Storage:token', jsonData.sessionToken],
          ['@Storage:endpoint', jsonData.endPoint]
        ]).then(() 
```
Then I want to read values in other components:
```
AsyncStorage.multiGet(['@Storage:token', '@Storage:endpoint']).then((userSession) => {
      const token = userSession[1][1];
      const endPoint = userSession[0][1];
```
For android this getting correct values of token & endpoint  but for IOS values are switch so: 
```
token = endpoint
endpoint = token
```
How can I get this to work on IOS/Android same way or if this is a bug and how can I put if statement to detect device.

**Comment by ltk** [comment]
it is possible that the order of items within the returned `userSession` array is not reliable because of the asynchronous nature of these retrievals. I think your best bet would be to identify each key value pair by key before performing the assignment.

**Comment by dsibiski** [comment]
@ltk Is correct, you should not rely on the order of items in an array.

**Comment by dsibiski** [comment]
@facebook-github-bot answered
