### ISSUE TITLE
arrow function based StatelessComponents are not assigned names in react-native

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#6716]
When using the StatelessComponent pattern with arrow functions in react-native, the components don't appear to be assigned names (the way I believe they are supposed to). This means some errors generated from within these stateless components can become completely useless.

For example, this
```js
const ThisIsAnError = undefined;

const BugTest = () => (
  <View style={styles.container}>
    <ThisIsAnError />
  </View>
); 
```

Will generate the error:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `StatelessComponent`.
```

(I also have a full runnable example for this error https://github.com/dantman/react-native-bugtest-1)

The stack track starts at `instantiateReactComponent@instantiateReactComponent.js:64`. So nothing in the error message or the stack trace will give you any hint of which of the many components in your application is responsible for the error.

**Comment by satya164** [comment]
cc @skevy @martinbigio

**Comment by dantman** [comment]
I did some more experimenting. This appears to be because the react-native babel preset omits the es2015-function-name transform.

I actually tried experimenting with adding that transform once in the past, but I couldn't get it to work because I didn't know about `--reset-cache`.

**Comment by satya164** [comment]
@dantman Awesome. Up for a PR?

**Comment by satya164** [comment]
Oh, I see you already did. Thanks a lot.

**Comment by martinbigio** [comment]
Awesome, thanks for fixing this!
