### ISSUE TITLE
DrawerLayout drawerLockMode should also have 'closed' 'open' in unlocked mode

### ISSUE THREAD

**Issue by prateekbh** [facebook/react-native#6720]
If the App logic decided to make drawerLockMode:'unlocked' i should be able to make it drawerLockMode:'closed' in subsequent calls of setState

**Comment by satya164** [comment]
What happens when you do `drawerLockMode={null}`?

**Comment by tsvetann** [comment]
For me `drawerLockMode={null}` is ignored. It behaves like no drawerLockMode definition exists. Tested with RN v.24

**Comment by lacker** [comment]
We might have updated these docs since this issue was posted - the valid mode is "locked-closed" rather than just "closed" so maybe that is your problem here? see https://facebook.github.io/react-native/docs/drawerlayoutandroid.html . I'm going to close this issue but if I misunderstood then feel free to reopen it.

**Comment by prateekbh** [comment]
@lacker that kinda work in a way for what i wanted to achieve, but i guess we still need 'closed' and 'open' states.
I'll try to illustrate with an example
Step1: Someone opens my app, I check the user state and see that he/she is not logged in. At this time I would want to have locked-open state. and hence making it necessary to login first.
Step2: he/she logs in, now i want to close the drawer. But here locked-closed will not work. I would obviously want him/her to open it again.
One common hack that people will start putting in will look like this
this.setState({drawerState:'locked-closed'});
setTimeout(function(){
  this.setState({drawerState:'unlocked'});
},100);

Not a clean solution really... :(
