### ISSUE TITLE
borderStyle: 'dashed' / 'dotted' does not work on android

### ISSUE THREAD

**Issue by Hkmu** [facebook/react-native#6721]
borderStyle: 'dashed' / 'dotted' does not work on android

![image](https://cloud.githubusercontent.com/assets/3169251/14133868/5b8c7440-f685-11e5-959f-6c5ff2f4322a.png)
![image](https://cloud.githubusercontent.com/assets/3169251/14133870/60d9fe5e-f685-11e5-8730-c77edb3bc81f.png)

```javascript
borderStyle: 'dashed'
```

**Comment by charpeni** [comment]
@facebook-github-bot label android

**Comment by chirag04** [comment]
@Hkmu can you try again by setting borderRadius to some small value? say `borderRadius: 0.5`.

I think there is a bug where borderStyles are not applied unless you give borderRadius
