### ISSUE TITLE
hot reloading error

### ISSUE THREAD

**Issue by py110** [facebook/react-native#6722]
i upgrade V0.21 to V0.22.2 

use the hot reloading get the follow error,disable the hot reloading it is ok
![image](https://cloud.githubusercontent.com/assets/13548241/14138321/3d79643a-f69f-11e5-9c12-adc9464cc6ad.png)

**Comment by ifiokjr** [comment]
I'm having the same issue. It's my first time working with react-native so I may not be much help finding the root of the problem.

**Comment by cpunion** [comment]
Already fixed in `babel-preset-react-native@1.5.5`, See https://github.com/facebook/react-native/issues/6640

**Comment by dsibiski** [comment]
@facebook-github-bot duplicate (#6640)

**Comment by dsibiski** [comment]
@facebook-github-bot duplicate #6640
