### ISSUE TITLE
Error while persisting cache: SyntaxError Unexpected token.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#6723]
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
  0.22.2
- [ ] Does this occur on iOS, Android or both?
  tested only on iOS
- [ ] Are you using Mac, Linux or Windows?
  Mac

transforming [========================================] 99% 857/863
Error while persisting cache: SyntaxError /path/to/some/code.js: Unexpected token (15:6)

I am suddenly getting this error, and it won't go away.
Not very helpful error message as it does not provide anything else other than path to the file.
The file does not have any syntax problem according to babel and eslint.
Is there any way to dig deeper into this error message?

**Comment by joonhocho** [comment]
Figured out the problem.

I was using .babelrc "env" to configure babel.
Here's a copy of my .babelrc:
```

{
  "env": {
    "web": {
      "passPerPreset": true,
      "presets": [
        {
          "plugins": [
            "./plugins/babelRelayPlugin"
          ]
        },
        "react",
        "es2015",
        "stage-0"
      ],
      "plugins": [
        "transform-runtime"
      ]
    },
    "native": {
      "passPerPreset": true,
      "presets": [
        {
          "plugins": [
            "./plugins/babelRelayPlugin"
          ]
        },
        "react-native"
      ]
    }
  }
}

```
I used to run `BABEL_ENV=native react-native run-ios`.
It worked until now.
I had to change "native" -> "devolpment" in .babelrc to get it working again.
Not sure why it suddenly stopped working.
Seems like spawned terminal instance does not copy over `BABEL_ENV` from terminal that runs `react-native run-ios`.

**Comment by joonhocho** [comment]
Is it possible to automatically copy over environment variables from the current terminal to spawned terminal when running `react-native run-ios`?

**Comment by dsibiski** [comment]
@joonhocho You can start the packager yourself with `react-native start` (in another window) **before** you run `react-native run-ios` thus allowing you to start it with the env that you want and not worrying about the spawned terminal session.

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by joonhocho** [comment]
Thank you for your answer!
