### ISSUE TITLE
[ios] Can't read property 'document' of undefined

### ISSUE THREAD

**Issue by hojberg** [facebook/react-native#6726]
After upgrading OSX i'm getting this error in my console and can't start my app in the Simulator.

<img width="904" alt="screen shot 2016-03-30 at 3 47 32 pm" src="https://cloud.githubusercontent.com/assets/2371/14144123/cc3dcd70-f68e-11e5-8364-e39eea11e0c1.png">

The `Module AppRegistry is not a registered callable module.` error sounds pretty fundamental.

I'm running OSX 10.11.14, node 5.3.0, React Native 0.20.0 and Xcode 7.3

**Comment by kbarrette** [comment]
This happened to me as well, I assumed that my environment was misconfigured somehow. Glad to know I'm not alone.

**Comment by hojberg** [comment]
I'm suspecting some kind of issue with javascriptcore and d3. Still investigating.

**Comment by hojberg** [comment]
What seems to have happened is that javascriptcore no longer supports global variables or something like that.

d3 explodes because it expects a `this` to be present.

Anyone else experiencing  something similar?

**Comment by hojberg** [comment]
I have fixed this for me by upgrading d3 to v4 which is more modular and also does not rely on the global context.

Closing this.
