### ISSUE TITLE
Text margin, padding not working if in another Text component

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#6728]
Hi everyone,

I've a little problem with the text component, I don't really understand why that doesn't work.
So if I do a render like above:

Code:
```jsx
        <Text style={{ margin: 10, backgroundColor: 'pink' }}>
          <Text style={{ margin: 30, backgroundColor: 'yellow' }} >TEST1</Text>
          TEST
        </Text>
```

Picture:
<img src="http://img15.hostingpics.net/pics/912207ScreenShot20160330at44836PM.png"/>

The first text component gonna render the margin or padding if this one is in another component than text.
But, if the I add a new Text component inside the previous one, there no `margin` or `padding`, it's normal ?

Thanks for your answer.

**Comment by ltk** [comment]
The `<Text>` element is special as far as layout is concerned. From [the docs](https://facebook.github.io/react-native/docs/text.html#containers): "everything inside is no longer using the flexbox layout but using text layout. This means that elements inside of a `<Text>` are no longer rectangles, but wrap when they see the end of the line."

To achieve what you seem to be looking for, it's probably advisable to use a wrapping `<View>` with two inner `<Text>`s.

**Comment by magrinj** [comment]
@ltk Thanks for your answer, I'm gonna use a view to wrap my `Text` inside :)

I understand it's no longer a flex layout, but this shouldn't prevent margins, does he ?

**Comment by charpeni** [comment]
@facebook-github-bot answered
