### ISSUE TITLE
Text with numberOfLines renders with incorrect height

### ISSUE THREAD

**Issue by mikesurowiec** [facebook/react-native#673]
It seems ```<Text />``` with the number of lines property incorrectly renders with the text's original height.

```javascript
<View style={{padding: 10, paddingTop: 40}}>
  <Text style={{containerBackgroundColor: 'red'}} numberOfLines={2}>
    React native is the bees knees of native development. Much faster than traditional native development.
  </Text>
</View>
```
With ```numberOfLines={2}```:
![withnumberoflines](https://cloud.githubusercontent.com/assets/821435/6994294/1e4b0796-dae2-11e4-983d-7107e06da34b.png)
Without numberOfLines:
![withoutnumberoflines](https://cloud.githubusercontent.com/assets/821435/6994295/20a5ceb8-dae2-11e4-9b54-f3610ca5e50b.png)

**Comment by vjeux** [comment]
Thanks for the report, looks like the measure call doesn't take into account numberOfLines. Do you want to give a shot at fixing it?

Note that internally we use a different Text implementation that's unfortunately very tied to fb infra so we had to write a new one for open source. But the goal is to make it as solid as possible :)

**Comment by sahrens** [comment]
We already have a fix for this that should get sync'd soon.

**Comment by mikesurowiec** [comment]
Great, thanks fellas!

**Comment by brentvatne** [comment]
[Fixed!](https://rnplay.org/plays/vGvYSQ?autoplay=true)

![screen shot 2015-05-31 at 9 15 15 am](https://cloud.githubusercontent.com/assets/90494/7902672/95f52b18-0775-11e5-9676-2ee959473b96.png)
