### ISSUE TITLE
NavigationExperimental - does not disable interaction during transition

### ISSUE THREAD

**Issue by cgreening** [facebook/react-native#6732]
When navigating from one view to another you can still interact with the current view. This means that a user can tap a button multiple times and trigger multiple transitions.

The view that is being transitioned off the screen should not be allowed to receive any user interaction while it is being transitioned.

React-Native 0.22.2, iOS

**Comment by skevy** [comment]
cc @hedgerwang @ericvicenti

**Comment by ericvicenti** [comment]
@hedgerwang, I think we should implement this functionality into the NavigationCard. I don't want to bake this into the NavigationAnimatedView because there may be some use cases where people want to interact with a scene mid-transition

**Comment by ericvicenti** [comment]
Does anybody want to help us accomplish this? It should be doable by configuring `pointerEvents` on the `NavigationCard` `Animated.View`

**Comment by hedgerwang** [comment]
It's easy to do. I'll make this happen soon.

**Comment by brentvatne** [comment]
I think the underlying problem here is this: https://github.com/facebook/react-native/issues/7164 cc @hedgerwang

**Comment by lacker** [comment]
This would be a nice thing to fix with our navigation work in progress - @skevy @ericvicenti is that possible?

**Comment by ericvicenti** [comment]
@hedgerwang has properly implemented the fix to this, but as Brent pointed out, the underlying issue being experienced is here: https://github.com/facebook/react-native/issues/7164

If this comes up a lot we might try and hack around the problem.
