### ISSUE TITLE
iOS - System Ultralight Font Weights Don't Work

### ISSUE THREAD

**Issue by dannolan** [facebook/react-native#6735]
Hi there,

I'm not really sure where to start with this, but I just checked out the UIExplorer sample trying to get a San Francisco Ultralight font to work

I've provided an image as a sample
![pasted_image_at_2016_03_31_17_48](https://cloud.githubusercontent.com/assets/255678/14167777/54fa4dfc-f769-11e5-9bd3-0cc7d0306485.png)

It's the same as the light font. What too heck should I do? I'm going to go tool through UIFont stuff right now to see if I can send a PR through.

**Comment by dsibiski** [comment]
@dannolan Yeah, if you could find out what's going on and submit a PR for this it would be awesome. Thanks :+1:

**Comment by grabbou** [comment]
FYI here are the unit tests for ultralight that are passing -> https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorerUnitTests/RCTConvert_UIFontTests.m#L42-L44

**Comment by grabbou** [comment]
San Fransisco ships in two versions - Text & Display. The latter is used for bigger text whereas the first one for smaller ones.

> One of the great features of San Francisco is the way it optimizes the typeface dynamically. The system will automatically switch the Display/Text fonts according to the text size. Specifically, 20pt is the boundary.

The `Text` version does not ship with Thin & UltraLight (but Light only) which explains why values `100` and `200` are the same as `300` (fallback).

See <img src="https://cdn-images-1.medium.com/max/1600/1*WvvGsRFtBJxR9dsPZtkYpw.png" />

If you bump font size to something like `45` in the examples, it works.

<img width="531" alt="screen shot 2016-04-19 at 00 43 55" src="https://cloud.githubusercontent.com/assets/2464966/14622074/d0503a90-05c7-11e6-8157-64a947676ec7.png">
