### ISSUE TITLE
[Android] RefreshControl offset top

### ISSUE THREAD

**Issue by UnoDeTantos** [facebook/react-native#6740]
On IOS if you set a contentInset top to a scrollview, RefreshControl starts from that point but with android don't exist that option (or at least i don't know how to do the same thing)

A possible workaroud (or feature request):

Add method to SwipeRefreshLayoutManaget.java
```
import com.facebook.react.uimanager.PixelUtil;

[...]

@ReactProp(name = "progressViewOffset", defaultFloat = 0)
  public void setProgressViewOffset(final ReactSwipeRefreshLayout view, final float offset) {
    // Use `post` to get the progress circle diameter properly
    // Otherwise returns 0
    view.post(new Runnable() {
      @Override
      public void run() {
        int diameter = view.getProgressCircleDiameter();
        int start = Math.round(PixelUtil.toPixelFromDIP(offset)) - diameter;
        int end = Math.round(PixelUtil.toPixelFromDIP(offset+48));
        view.setProgressViewOffset(false,start,end);
      }
    });
  }
```

Add PropType to RefreshControl.js:
```
/**
     * Progress view offset top (display points)
     * @platform android
     */
    progressViewOffset: React.PropTypes.number
```

And then you can make something like this on a listview on android:
```
render() {
    const offset = 50;
    return (
      <ListView
        contentContainerStyle={{paddingTop:offset}}
        dataSource={this.state.dataSource}
        renderRow={this._renderRow}
        refreshControl={
          <RefreshControl
            refreshing={this.state.isRefreshing}
            onRefresh={this._onRefresh}
            progressViewOffset={offset}
          />
      }/>
    );
  }
```

**Comment by janicduplessis** [comment]
Looks like a good addition, you can submit a pull request!

**Comment by christopherdro** [comment]
Added via https://github.com/facebook/react-native/commit/f7ce0c1c2fd2d6dacbf2c76cf43f48d245e8779d

**Comment by Weakky** [comment]
Sorry for digging up that issue, but that's the only place I found some leading clues..
Author says `contentInset` prop does the trick of offsetting the`RefreshControl` on iOS.

Indeed it does, but it also offsets the whole `ScrollView` which is not something I want.
Is there a way to only offset the `RefreshControl` while keeping my `ScrollView` at the same position ? Thanks

**Comment by RHinderiks** [comment]
Having the same problem as @Weakky

**Comment by toytonic** [comment]
Same problem here. Unfortunately I don't know enough about native ios if this feature would be easy to achieve.
