### ISSUE TITLE
[RCTLocationObserver] BAD_ACCESS on reload

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#6741]
Hey,

I am getting EXC_BAD_ACCESS quite frequently on reloads in dev mode on that line:
https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L294

I am wondering shouldn't we use the `locationManager` provided by the delegate method instead of referencing to the one on instance? 

Update:
`_locationManager` is however defined, so not sure why this error happens.

**Comment by christopherdro** [comment]
@grabbou Is this still an issue?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by mkonicek** [comment]
Thanks @christopherdro for helping manage the issues!

**Comment by grabbou** [comment]
@christopherdro I am no longer working on the app that was suffering that issue though I can imagine that it still happens as I haven't seen anything fixing it. When I encounter it once again, I'll make sure to re-open :)
