### ISSUE TITLE
Google maps Webview and Navigator API

### ISSUE THREAD

**Issue by eMatsiyana** [facebook/react-native#6746]
Hello, has anyone tried using google maps inside a webview on Android? Whenever I use a Navigator the webview doesn't show anything and when I use the webview on its own it works.
The maps site is written in react js

The iOS version of the app works fine. I am using RN0.22
I am using this webview for geolocation: https://github.com/lucasferreira/react-native-webview-android

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow
