### ISSUE TITLE
Requiring unknown module "react-native".

### ISSUE THREAD

**Issue by henjue** [facebook/react-native#6753]
Whether it is Android or IOS, when the reload enabled hot, there is an error 
```
Requiring unknown module "react-native". If you are sure the module is there, try restarting the packager or running "npm install".
```

**Comment by notlose** [comment]
seems related to hot reloading, you can disable Hot Reloading in dev menu and reload the js again

**Comment by henjue** [comment]
@notlose but i want use hot reloading.........

**Comment by notlose** [comment]
#6731 <- did you upgrade babel-preset-react-native mentioned in this post?

**Comment by henjue** [comment]
thks
