### ISSUE TITLE
Android viewport buggy when keyboard is open

### ISSUE THREAD

**Issue by kapv89** [facebook/react-native#6757]
I am developing for android, on linux mint.

Upto v0.20(actually,  some particular version, not sure which), when I would focus on a `Textinput` and keyboard would open up, the whole viewport would get resized, and `ScrollView` would behave according to the new width and height.

Since v0.20, opening the keyboard shifts the viewport up(messes up any pure-js toolbars, at least) , and `ScrollView` doesn't work when keyboard is opened.

I started facing the problem recently when I cleared up gradle caches or something, which probably were providing me with older versions of ReactAndroid code.

This bug is pretty serious as it renders react-native sort of useless for android, the platform where the dev experience provided by react-native is literally 10x better than what existed before.

UPDATE: just checked, problem seems to persist even with v0.20. Digging more into this.
UPDATE: https://rnplay.org/apps/zqmeDg A demo rnplay of the problem. Please look into this.
UPDATE: On v0.20, I can fix the topbar issue by setting `android:windowSoftInputMode="adjustResize"` in `AndroidManifest.xml`. Using this, the topbar remains in place. However, I still cannot get the scrollview to work with keyboard open

UPDATE: Finally, resolved this. It still doesn't happen automatically, but listening for `keyboardDidOpen` and `keyboardDidClose` in my root view and setting a `visibleHeight` accordingly takes care of a lot of things. Now on to a major refractorin.

**Comment by holyxiaoxin** [comment]
This is definitely bothering. I had the same problem where selecting `TextInput` at the bottom causes the keyboard to open up. And when it did, it actually pushes the viewport out of the screen (upwards). Going out of the app, and coming back into the app solves this problem. I dug through the issues and found this. And adding `android:windowSoftInputMode="adjustResize"` indeed fixed the top bar in place. Thanks! (:
