### ISSUE TITLE
ScrollView inside a Pan Responder

### ISSUE THREAD

**Issue by CapitanRedBeard** [facebook/react-native#6764]
I am trying to do something like this :
 
     <Animated.View {...pandHandler}>
          <ScrollView >
               ... 
          </ScrollView >
     </Animated.View>

With the Scroll View being a vertical scroll view, is it possible to only take the delta x click for the panHandler and the delta y click for the Scroll View. The use case for this functionality is to have tinder like swipe cards of variable height that can have a scroll view in it.

**Comment by cridenour** [comment]
Hey @CapitanRedBeard - what did you end up doing here? Have a similar UX I want to achieve and having trouble getting reliable results.

**Comment by CapitanRedBeard** [comment]
@cridenour Try something like this within your PanReponder
```
            onPanResponderMove: (evt, { dx, dy }) => {
                if (!this.scrollControl) {
                    this.scrollControl = Math.abs(dx) > Math.abs(dy);
                }
                if (this.scrollControl) {
                    this.state.pan.x.setValue(dx);
                } else {
                   let shiftValue = -dy / PixelRatio.get(); 
                   this.refs.scrollView.scrollTo(shiftValue);
                }
           })

            onPanResponderRelease: (evt, {vx, vy}) => {
                this.scrollControl = null;
            })
```

**Comment by brendan-rius** [comment]
@CapitanRedBeard thank you for your answer. However that's clearly a hack and not a viable solution.

I think there is clearly a problem here: my child ScrollView does not become the responder, but my parent does, how come?
