### ISSUE TITLE
[ListView & ScrollView] Don't respect LayoutAnimation

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/react-native#677]
I was talking to @vjeux on IRC about this.

I was trying to animate the layout as the keyboard opens and as you can see in the video below the TextInput view is properly animating (sometimes 1 frame behind though) with the keyboard while the ListView instantly clips.

https://www.dropbox.com/s/iz1cm5p22ar9vfk/Screenflick%20Movie%207.mp4?dl=0

I tested by removing the ListView and replacing it with a plain ScrollView and setting the contentContainerStyle to solid red and basically the same thing happens. The contentContainer instantly clips and doesn't animate it's height. 

Any ideas of suggestions?

**Comment by brentvatne** [comment]
:+1: curious to see what the solution is

**Comment by dhrrgn** [comment]
:+1: Seeing the same thing here in 0.6.0-rc

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tadeuzagallo** [comment]
#1366 landed right after this issue, let me know if it's still an issue and I can reopen it.

**Comment by andrewsnowden** [comment]
I'm still having this issue using 0.27.0 - am trying to animate a ScrollView and it just jumps to the new height instead of animating it. Changing the top position animates, but none of 'bottom', 'height', 'marginBottom' or 'paddingBottom' animate.

**Comment by vaibhawc** [comment]
Surprisingly, this stays in 0.36.0 also. Any hacks?

**Comment by jgkim** [comment]
@tadeuzagallo I think this is still an issue in 0.39 so this issue needs to be reopened.

**Comment by tadeuzagallo** [comment]
I believe it'd be better to just open a new issue with more information rather than reopening a issue that's over an year old and has little context on it.

**Comment by rishabhpoddar** [comment]
This is also an issue in react-native v0.44.0. Any fixes yet?
