### ISSUE TITLE
SegmentedControlIOS on iPad

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#6773]
The SegmentedControlIOS looks fine on iPhone but with iPad its so small, in fact it just doesn't appear to resize at all. Its just stuck on one size no matter which iPhone or iPad model you select. I couldn't find any way to modify any style settings for the SegmentedControlIOS either.

**Comment by dsibiski** [comment]
Hi @hasen6, you can actually use a `transform` on any component or view like so:

`<SegmentedControlIOS style={{ transform: [{scaleX: 1.1}, {scaleY: 1.1}] }} />`

That will scale it up a little bit. You can change your values here depending on the device. Here it is in the docs: http://facebook.github.io/react-native/docs/transforms.html#transform

For future reference, things like these are best answered on StackOverflow. :+1:

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by hasen6** [comment]
That doesn't do anything at all. Did you try it? I haven't found that any style commands work with SegmentedControlIOS.

**Comment by dsibiski** [comment]
@hasen6 Yes, I have a project where I do exactly that, here is a runnable example: https://rnplay.org/apps/oZfroA

**Comment by hasen6** [comment]
Ok you're right, I was kind of thrown because it doesn't accept font style tags so I assumed it didn't accept any style tags. Its a workaround at least. I don't suppose you know some way to style the fonts? It would obviously look a whole lot nicer than transforming if we could just resize the fonts.
