### ISSUE TITLE
EXC_BAD_ACCESS on iOS using RN 0.21 & 0.22 - in ShadowQueue

### ISSUE THREAD

**Issue by andpor** [facebook/react-native#6775]
Hi there,

Encountered a crash on iOS running on 5s device.

Seems to be a null access on one of the threads from com.facebook.React.ShadowQueue.

faulting line in Thread 33 is reported as this
`    0x197a9521c <+816>:  b      0x197a952b8               ; <+972>
`
code=1 , address 0x0

source code seems to be pointing  to RCTBatchedBridge.m line 559

```
(void)dispatchBlock:(dispatch_block_t)block
                queue:(dispatch_queue_t)queue
{
  if (queue == RCTJSThread) {
    [_javaScriptExecutor executeBlockOnJavaScriptQueue:block];
  } else if (queue) {
    dispatch_async(queue, block);     <-----  enqueue from com.apple.root.default-qos-overcommit (Thread 25)
  }
}
```

Thread 25 seems to be com.facebook.React.Javascript, the last stmt seem to be executeBlockOnJavaScriptQueue

```
- (void)_executeJSCall:(NSString *)method
             arguments:(NSArray *)arguments
              callback:(RCTJavaScriptCallback)onComplete
{
  RCTAssert(onComplete != nil, @"onComplete block should not be nil");
  __weak RCTJSCExecutor *weakSelf = self;
 --- > [self executeBlockOnJavaScriptQueue:RCTProfileBlock((^{
    RCTJSCExecutor *strongSelf = weakSelf;
    if (!strongSelf || !strongSelf.isValid) {
      return;
    }
```

`JavaScriptCore`JSObjectCallAsFunction:
    0x186ae5130 <+0>:   stp    x28, x27, [sp, #-96]!
    0x186ae5134 <+4>:   stp    x26, x25, [sp, #16]
    0x186ae5138 <+8>:   stp    x24, x23, [sp, #32]
    0x186ae513c <+12>:  stp    x22, x21, [sp, #48]
    0x186ae5140 <+16>:  stp    x20, x19, [sp, #64]
    0x186ae5144 <+20>:  stp    x29, x30, [sp, #80]
    0x186ae5148 <+24>:  add    x29, sp, #80
    0x186ae514c <+28>:  sub    sp, sp, #144
    0x186ae5150 <+32>:  mov    x20, x5
    0x186ae5154 <+36>:  mov    x23, x4
    0x186ae5158 <+40>:  mov    x24, x3
    0x186ae515c <+44>:  mov    x22, x2
    0x186ae5160 <+48>:  mov    x21, x1
    0x186ae5164 <+52>:  mov    x19, x0
    0x186ae5168 <+56>:  sub    x0, x29, #88
    0x186ae516c <+60>:  mov    x1, x19
    0x186ae5170 <+64>:  bl     0x186ac473c               ; JSC::JSLockHolder::JSLockHolder(JSC::ExecState*)
    0x186ae5174 <+68>:  cbz    x21, 0x186ae51f8          ; <+200>
    0x186ae5178 <+72>:  and    x26, x21, #0xffffffffffff0000
    0x186ae517c <+76>:  ldr    x8, [x26, #1128]
    0x186ae5180 <+80>:  movz   x9, #0xb058
    0x186ae5184 <+84>:  add    x8, x8, x9
    0x186ae5188 <+88>:  ldr    x8, [x8]
    0x186ae518c <+92>:  ldr    w9, [x21]
    0x186ae5190 <+96>:  ldr    x8, [x8, #728]
    0x186ae5194 <+100>: ldr    x10, [x8, x9, lsl #3]
    0x186ae5198 <+104>: ldr    w10, [x10]
    0x186ae519c <+108>: ldr    x10, [x8, x10, lsl #3]
    0x186ae51a0 <+112>: cbz    x10, 0x186ae51b4          ; <+132>
    0x186ae51a4 <+116>: ldr    w11, [x10]
    0x186ae51a8 <+120>: ldr    x11, [x8, x11, lsl #3]
    0x186ae51ac <+124>: cmp    x10, x11
    0x186ae51b0 <+128>: b.ne   0x186ae53e0               ; <+688>
    0x186ae51b4 <+132>: cbz    x22, 0x186ae5200          ; <+208>
    0x186ae51b8 <+136>: and    x10, x22, #0xffffffffffff0000
    0x186ae51bc <+140>: ldr    x10, [x10, #1128]
    0x186ae51c0 <+144>: movz   x11, #0xb058
    0x186ae51c4 <+148>: add    x10, x10, x11
    0x186ae51c8 <+152>: ldr    x10, [x10]
    0x186ae51cc <+156>: ldr    w11, [x22]
    0x186ae51d0 <+160>: ldr    x10, [x10, #728]
    0x186ae51d4 <+164>: ldr    x11, [x10, x11, lsl #3]
    0x186ae51d8 <+168>: ldr    w11, [x11]
    0x186ae51dc <+172>: ldr    x11, [x10, x11, lsl #3]
    0x186ae51e0 <+176>: cbz    x11, 0x186ae5220          ; <+240>
    0x186ae51e4 <+180>: ldr    w12, [x11]
    0x186ae51e8 <+184>: ldr    x10, [x10, x12, lsl #3]
    0x186ae51ec <+188>: cmp    x11, x10
    0x186ae51f0 <+192>: b.eq   0x186ae5220               ; <+240>
    0x186ae51f4 <+196>: bl     0x186eb9544               ; WTFCrash
    0x186ae51f8 <+200>: movz   x21, #0
    0x186ae51fc <+204>: b      0x186ae53b4               ; <+644>
    0x186ae5200 <+208>: ldr    x10, [x19, #24]
    0x186ae5204 <+212>: and    x11, x10, #0xffffffffffff0000
    0x186ae5208 <+216>: ldr    x11, [x11, #1128]
    0x186ae520c <+220>: ldr    w10, [x10]
    0x186ae5210 <+224>: ldr    x11, [x11, #728]
    0x186ae5214 <+228>: ldr    x10, [x11, x10, lsl #3]
    0x186ae5218 <+232>: ldr    x10, [x10, #24]
    0x186ae521c <+236>: ldr    x22, [x10, #112]
    0x186ae5220 <+240>: str    wzr, [sp, #48]
    0x186ae5224 <+244>: orr    w10, wzr, #0x8
    0x186ae5228 <+248>: str    w10, [sp, #52]
    0x186ae522c <+252>: add    x10, sp, #48
    0x186ae5230 <+256>: add    x10, x10, #8
    0x186ae5234 <+260>: stp    x10, xzr, [sp, #120]
    0x186ae5238 <+264>: cbz    x24, 0x186ae52f8          ; <+456>
    0x186ae523c <+268>: str    x20, [sp, #8]
    0x186ae5240 <+272>: movz   x27, #0
    0x186ae5244 <+276>: add    x25, sp, #48
    0x186ae5248 <+280>: movz   x28, #0xffff, lsl #48
    0x186ae524c <+284>: movk   x28, #0x2
    0x186ae5250 <+288>: movz   x20, #0xb058
    0x186ae5254 <+292>: ldr    x1, [x23, x27, lsl #3]
    0x186ae5258 <+296>: cbz    x1, 0x186ae52a0           ; <+368>
    0x186ae525c <+300>: and    x8, x1, x28
    0x186ae5260 <+304>: cbnz   x8, 0x186ae52a4           ; <+372>
    0x186ae5264 <+308>: and    x8, x1, #0xffffffffffff0000
    0x186ae5268 <+312>: ldr    x8, [x8, #1128]
    0x186ae526c <+316>: add    x8, x8, x20
    0x186ae5270 <+320>: ldr    x8, [x8]
    0x186ae5274 <+324>: ldr    w9, [x1]
    0x186ae5278 <+328>: ldr    x8, [x8, #728]
    0x186ae527c <+332>: ldr    x9, [x8, x9, lsl #3]
    0x186ae5280 <+336>: ldr    w9, [x9]
    0x186ae5284 <+340>: ldr    x9, [x8, x9, lsl #3]
    0x186ae5288 <+344>: cbz    x9, 0x186ae52a4           ; <+372>
    0x186ae528c <+348>: ldr    w10, [x9]
    0x186ae5290 <+352>: ldr    x8, [x8, x10, lsl #3]
    0x186ae5294 <+356>: cmp    x9, x8
    0x186ae5298 <+360>: b.eq   0x186ae52a4               ; <+372>
    0x186ae529c <+364>: b      0x186ae53e0               ; <+688>
    0x186ae52a0 <+368>: orr    x1, xzr, #0x2
    0x186ae52a4 <+372>: ldr    x8, [sp, #48]
    0x186ae52a8 <+376>: lsr    x9, x8, #32
    0x186ae52ac <+380>: cmp    w8, w9
    0x186ae52b0 <+384>: b.ge   0x186ae52c8               ; <+408>
    0x186ae52b4 <+388>: ldr    x9, [sp, #120]
    0x186ae52b8 <+392>: str    x1, [x9, w8, sxtw #3]
    0x186ae52bc <+396>: add    w8, w8, #1
    0x186ae52c0 <+400>: str    w8, [sp, #48]
    0x186ae52c4 <+404>: b      0x186ae52d0               ; <+416>
    0x186ae52c8 <+408>: mov    x0, x25
    0x186ae52cc <+412>: bl     0x186bee47c               ; JSC::MarkedArgumentBuffer::slowAppend(JSC::JSValue)
    0x186ae52d0 <+416>: add    x27, x27, #1
    0x186ae52d4 <+420>: cmp    x27, x24
    0x186ae52d8 <+424>: b.lo   0x186ae5254               ; <+292>
    0x186ae52dc <+428>: ldr    x8, [x26, #1128]
    0x186ae52e0 <+432>: movz   x9, #0xb058
    0x186ae52e4 <+436>: add    x8, x8, x9
    0x186ae52e8 <+440>: ldr    x8, [x8]
    0x186ae52ec <+444>: ldr    w9, [x21]
    0x186ae52f0 <+448>: ldr    x8, [x8, #728]
    0x186ae52f4 <+452>: ldr    x20, [sp, #8]
    0x186ae52f8 <+456>: ldr    x9, [x8, w9, uxtw #3]
    0x186ae52fc <+460>: ldr    w10, [x9]
    0x186ae5300 <+464>: ldr    x10, [x8, x10, lsl #3]
    0x186ae5304 <+468>: cbz    x10, 0x186ae5318          ; <+488>
    0x186ae5308 <+472>: ldr    w11, [x10]
    0x186ae530c <+476>: ldr    x8, [x8, x11, lsl #3]
    0x186ae5310 <+480>: cmp    x10, x8
    0x186ae5314 <+484>: b.ne   0x186ae53e0               ; <+688>
    0x186ae5318 <+488>: ldr    x8, [x9, #72]
    0x186ae531c <+492>: ldr    x8, [x8, #56]
    0x186ae5320 <+496>: add    x1, sp, #32
    0x186ae5324 <+500>: mov    x0, x21
    0x186ae5328 <+504>: blr    x8
    0x186ae532c <+508>: mov    x8, x0
    0x186ae5330 <+512>: cbz    w8, 0x186ae53a8           ; <+632>
    0x186ae5334 <+516>: ldr    x9, [sp, #120]
    0x186ae5338 <+520>: str    x9, [sp, #16]
    0x186ae533c <+524>: ldr    w9, [sp, #48]
    0x186ae5340 <+528>: str    w9, [sp, #24]
    0x186ae5344 <+532>: add    x3, sp, #32
    0x186ae5348 <+536>: add    x5, sp, #16
    0x186ae534c <+540>: mov    x0, x19
    0x186ae5350 <+544>: mov    x1, x21
    0x186ae5354 <+548>: mov    x2, x8
    0x186ae5358 <+552>: mov    x4, x22
    0x186ae535c <+556>: bl     0x186ae53e4               ; JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
    0x186ae5360 <+560>: mov    x21, x0                 ** <---- this is the stmt highlighted**
    0x186ae5364 <+564>: ldr    x8, [x19, #24]
    0x186ae5368 <+568>: and    x8, x8, #0xffffffffffff0000
    0x186ae536c <+572>: ldr    x0, [x8, #1128]
    0x186ae5370 <+576>: movz   x9, #0xcbe8
    0x186ae5374 <+580>: add    x9, x0, x9
    0x186ae5378 <+584>: ldr    x22, [x9]
    0x186ae537c <+588>: cbz    x22, 0x186ae53ac          ; <+636>
    0x186ae5380 <+592>: cbz    x20, 0x186ae538c          ; <+604>
    0x186ae5384 <+596>: str    x22, [x20]
    0x186ae5388 <+600>: ldr    x0, [x8, #1128]
    0x186ae538c <+604>: bl     0x186eaa198               ; JSC::VM::clearException()
    0x186ae5390 <+608>: mov    x0, x19
    0x186ae5394 <+612>: bl     0x186c11854               ; JSC::ExecState::vmEntryGlobalObject()
    0x186ae5398 <+616>: ldr    x0, [x0, #1128]
    0x186ae539c <+620>: mov    x1, x19
    0x186ae53a0 <+624>: mov    x2, x22
    0x186ae53a4 <+628>: bl     0x186db4030               ; Inspector::JSGlobalObjectInspectorController::reportAPIException(JSC::ExecState*, JSC::JSValue)
    0x186ae53a8 <+632>: movz   x21, #0
    0x186ae53ac <+636>: add    x0, sp, #48
    0x186ae53b0 <+640>: bl     0x186b0c57c               ; JSC::MarkedArgumentBuffer::~MarkedArgumentBuffer()
    0x186ae53b4 <+644>: sub    x0, x29, #88
    0x186ae53b8 <+648>: bl     0x186a8a628               ; JSC::JSLockHolder::~JSLockHolder()
    0x186ae53bc <+652>: mov    x0, x21
    0x186ae53c0 <+656>: sub    sp, x29, #80
    0x186ae53c4 <+660>: ldp    x29, x30, [sp, #80]
    0x186ae53c8 <+664>: ldp    x20, x19, [sp, #64]
    0x186ae53cc <+668>: ldp    x22, x21, [sp, #48]
    0x186ae53d0 <+672>: ldp    x24, x23, [sp, #32]
    0x186ae53d4 <+676>: ldp    x26, x25, [sp, #16]
    0x186ae53d8 <+680>: ldp    x28, x27, [sp], #96
    0x186ae53dc <+684>: ret    
    0x186ae53e0 <+688>: bl     0x186eb9544               ; WTFCrash
`

Crashing thread 33:

`libsystem_pthread.dylib`_pthread_wqthread:
    0x197a94eec <+0>:    stp    x26, x25, [sp, #-80]!
    0x197a94ef0 <+4>:    stp    x24, x23, [sp, #16]
    0x197a94ef4 <+8>:    stp    x22, x21, [sp, #32]
    0x197a94ef8 <+12>:   stp    x20, x19, [sp, #48]
    0x197a94efc <+16>:   stp    x29, x30, [sp, #64]
    0x197a94f00 <+20>:   add    x29, sp, #64
    0x197a94f04 <+24>:   sub    sp, sp, #32
    0x197a94f08 <+28>:   mov    x22, x1
    0x197a94f0c <+32>:   mov    x19, x0
    0x197a94f10 <+36>:   tbnz   w4, #18, 0x197a94f44      ; <+88>
    0x197a94f14 <+40>:   adr    x8, #29791                ; "flags & WQ_FLAG_THREAD_NEWSPI"
    0x197a94f18 <+44>:   nop    
    0x197a94f1c <+48>:   movz   x9, #0x733
    0x197a94f20 <+52>:   adr    x10, #29761               ; "_pthread_wqthread"
    0x197a94f24 <+56>:   nop    
    0x197a94f28 <+60>:   stp    x9, x8, [sp, #16]
    0x197a94f2c <+64>:   adr    x8, #29525                ; "/SourceCache/libpthread/libpthread-106.40.1/src/pthread.c"
    0x197a94f30 <+68>:   nop    
    0x197a94f34 <+72>:   stp    x8, x10, [sp]
    0x197a94f38 <+76>:   adr    x0, #29705                ; "%s:%s:%u: failed assertion \`%s'"
    0x197a94f3c <+80>:   nop    
    0x197a94f40 <+84>:   bl     0x197a9b864               ; __pthread_abort_reason
    0x197a94f44 <+88>:   and    w9, w4, #0x20000
    0x197a94f48 <+92>:   and    w20, w4, #0xffff
    0x197a94f4c <+96>:   and    w23, w4, #0x10000
    0x197a94f50 <+100>:  adrp   x24, 16298
    0x197a94f54 <+104>:  ldr    w8, [x24, #636]
    0x197a94f58 <+108>:  lsl    w10, w23, #15
    0x197a94f5c <+112>:  tbnz   w8, #4, 0x197a94f74       ; <+136>
    0x197a94f60 <+116>:  cmp    w20, #16
    0x197a94f64 <+120>:  b.gt   0x197a94f98               ; <+172>
    0x197a94f68 <+124>:  cmp    w20, #9
    0x197a94f6c <+128>:  b.ne   0x197a95034               ; <+328>
    0x197a94f70 <+132>:  b      0x197a94f8c               ; <+160>
    0x197a94f74 <+136>:  cmp    w20, #32
    0x197a94f78 <+140>:  b.gt   0x197a94fbc               ; <+208>
    0x197a94f7c <+144>:  cmp    w20, #8
    0x197a94f80 <+148>:  b.gt   0x197a94fd0               ; <+228>
    0x197a94f84 <+152>:  cmp    w20, #5
    0x197a94f88 <+156>:  b.ne   0x197a95034               ; <+328>
    0x197a94f8c <+160>:  orr    x11, xzr, #0xff
    0x197a94f90 <+164>:  orr    x12, xzr, #0x100
    0x197a94f94 <+168>:  b      0x197a9503c               ; <+336>
    0x197a94f98 <+172>:  cmp    w20, #32
    0x197a94f9c <+176>:  b.gt   0x197a94fec               ; <+256>
    0x197a94fa0 <+180>:  cmp    w20, #17
    0x197a94fa4 <+184>:  b.eq   0x197a94fe0               ; <+244>
    0x197a94fa8 <+188>:  cmp    w20, #21
    0x197a94fac <+192>:  b.eq   0x197a95014               ; <+296>
    0x197a94fb0 <+196>:  cmp    w20, #25
    0x197a94fb4 <+200>:  b.ne   0x197a95034               ; <+328>
    0x197a94fb8 <+204>:  b      0x197a95008               ; <+284>
    0x197a94fbc <+208>:  cmp    w20, #33
    0x197a94fc0 <+212>:  b.ne   0x197a95034               ; <+328>
    0x197a94fc4 <+216>:  orr    x11, xzr, #0xff
    0x197a94fc8 <+220>:  orr    x12, xzr, #0x2000
    0x197a94fcc <+224>:  b      0x197a9503c               ; <+336>
    0x197a94fd0 <+228>:  cmp    w20, #16
    0x197a94fd4 <+232>:  b.gt   0x197a94ff8               ; <+268>
    0x197a94fd8 <+236>:  cmp    w20, #9
    0x197a94fdc <+240>:  b.ne   0x197a95034               ; <+328>
    0x197a94fe0 <+244>:  orr    x11, xzr, #0xff
    0x197a94fe4 <+248>:  orr    x12, xzr, #0x200
    0x197a94fe8 <+252>:  b      0x197a9503c               ; <+336>
    0x197a94fec <+256>:  cmp    w20, #33
    0x197a94ff0 <+260>:  b.ne   0x197a95034               ; <+328>
    0x197a94ff4 <+264>:  b      0x197a95028               ; <+316>
    0x197a94ff8 <+268>:  cmp    w20, #17
    0x197a94ffc <+272>:  b.eq   0x197a95014               ; <+296>
    0x197a95000 <+276>:  cmp    w20, #21
    0x197a95004 <+280>:  b.ne   0x197a95020               ; <+308>
    0x197a95008 <+284>:  orr    x11, xzr, #0xff
    0x197a9500c <+288>:  orr    x12, xzr, #0x800
    0x197a95010 <+292>:  b      0x197a9503c               ; <+336>
    0x197a95014 <+296>:  orr    x11, xzr, #0xff
    0x197a95018 <+300>:  orr    x12, xzr, #0x400
    0x197a9501c <+304>:  b      0x197a9503c               ; <+336>
    0x197a95020 <+308>:  cmp    w20, #25
    0x197a95024 <+312>:  b.ne   0x197a95034               ; <+328>
    0x197a95028 <+316>:  orr    x11, xzr, #0xff
    0x197a9502c <+320>:  orr    x12, xzr, #0x1000
    0x197a95030 <+324>:  b      0x197a9503c               ; <+336>
    0x197a95034 <+328>:  movz   x12, #0
    0x197a95038 <+332>:  movz   x11, #0
    0x197a9503c <+336>:  orr    x10, x12, x10
    0x197a95040 <+340>:  orr    x21, x10, x11
    0x197a95044 <+344>:  cbnz   w9, 0x197a951dc           ; <+752>
    0x197a95048 <+348>:  adrp   x25, 16297
    0x197a9504c <+352>:  add    x25, x25, #672
    0x197a95050 <+356>:  add    x1, x25, #32
    0x197a95054 <+360>:  orr    x3, xzr, #0x80000
    0x197a95058 <+364>:  orr    w4, wzr, #0x1
    0x197a9505c <+368>:  mov    x0, x19
    0x197a95060 <+372>:  bl     0x197a9699c               ; _pthread_struct_init
    0x197a95064 <+376>:  ubfx   x8, x22, #0, #32
    0x197a95068 <+380>:  str    x8, [x19, #248]
    0x197a9506c <+384>:  ldr    w8, [x19, #24]
    0x197a95070 <+388>:  movz   w9, #0xf3ff, lsl #16
    0x197a95074 <+392>:  movk   w9, #0xfffc
    0x197a95078 <+396>:  and    w8, w8, w9
    0x197a9507c <+400>:  movz   w9, #0x400, lsl #16
    0x197a95080 <+404>:  movk   w9, #0x2
    0x197a95084 <+408>:  orr    w8, w8, w9
    0x197a95088 <+412>:  str    w8, [x19, #24]
    0x197a9508c <+416>:  mov    x0, x19
    0x197a95090 <+420>:  bl     0x197a96a8c               ; _pthread_set_self
    0x197a95094 <+424>:  ldr    x8, [x25, #24]
    0x197a95098 <+428>:  cbz    x8, 0x197a950a8           ; <+444>
    0x197a9509c <+432>:  movz   w1, #0
    0x197a950a0 <+436>:  mov    x0, x19
    0x197a950a4 <+440>:  bl     0x197a998bc               ; _pthread_introspection_hook_callout_thread_create
    0x197a950a8 <+444>:  adrp   x0, 16297
    0x197a950ac <+448>:  add    x0, x0, #632
    0x197a950b0 <+452>:  bl     0x197a9be0c               ; symbol stub for: getpid
    0x197a950b4 <+456>:  ldr    w9, [x19, #16]
    0x197a950b8 <+460>:  orr    w8, w9, #0x1
    0x197a950bc <+464>:  str    w8, [x19, #16]
    0x197a950c0 <+468>:  and    w8, w9, #0x2
    0x197a950c4 <+472>:  ldrb   w10, [x19, #27]
    0x197a950c8 <+476>:  tbz    w10, #2, 0x197a950d4      ; <+488>
    0x197a950cc <+480>:  orr    w9, w9, #0x3
    0x197a950d0 <+484>:  str    w9, [x19, #16]
    0x197a950d4 <+488>:  cbnz   w8, 0x197a9510c           ; <+544>
    0x197a950d8 <+492>:  mov    x8, x19
    0x197a950dc <+496>:  str    xzr, [x8, #104]!
    0x197a950e0 <+500>:  adrp   x9, 16297
    0x197a950e4 <+504>:  add    x9, x9, #640
    0x197a950e8 <+508>:  ldr    x10, [x9, #8]
    0x197a950ec <+512>:  str    x10, [x19, #112]
    0x197a950f0 <+516>:  str    x19, [x10]
    0x197a950f4 <+520>:  str    x8, [x9, #8]
    0x197a950f8 <+524>:  adrp   x8, 16297
    0x197a950fc <+528>:  add    x8, x8, #656
    0x197a95100 <+532>:  ldr    w9, [x8]
    0x197a95104 <+536>:  add    w9, w9, #1
    0x197a95108 <+540>:  str    w9, [x8]
    0x197a9510c <+544>:  adrp   x0, 16297
    0x197a95110 <+548>:  add    x0, x0, #632
    0x197a95114 <+552>:  bl     0x197a9be18               ; symbol stub for: host_info
    0x197a95118 <+556>:  ldr    x8, [x25, #24]
    0x197a9511c <+560>:  cbz    x8, 0x197a95128           ; <+572>
    0x197a95120 <+564>:  mov    x0, x19
    0x197a95124 <+568>:  bl     0x197a99854               ; _pthread_introspection_hook_callout_thread_start
    0x197a95128 <+572>:  ldr    w8, [x24, #636]
    0x197a9512c <+576>:  tbz    w8, #1, 0x197a951dc       ; <+752>
    0x197a95130 <+580>:  cmp    w20, #32
    0x197a95134 <+584>:  b.gt   0x197a95154               ; <+616>
    0x197a95138 <+588>:  cmp    w20, #8
    0x197a9513c <+592>:  b.gt   0x197a95168               ; <+636>
    0x197a95140 <+596>:  cmp    w20, #5
    0x197a95144 <+600>:  b.ne   0x197a951c0               ; <+724>
    0x197a95148 <+604>:  orr    x8, xzr, #0xff
    0x197a9514c <+608>:  orr    x9, xzr, #0x100
    0x197a95150 <+612>:  b      0x197a951c8               ; <+732>
    0x197a95154 <+616>:  cmp    w20, #33
    0x197a95158 <+620>:  b.ne   0x197a951c0               ; <+724>
    0x197a9515c <+624>:  orr    x8, xzr, #0xff
    0x197a95160 <+628>:  orr    x9, xzr, #0x2000
    0x197a95164 <+632>:  b      0x197a951c8               ; <+732>
    0x197a95168 <+636>:  cmp    w20, #16
    0x197a9516c <+640>:  b.gt   0x197a95184               ; <+664>
    0x197a95170 <+644>:  cmp    w20, #9
    0x197a95174 <+648>:  b.ne   0x197a951c0               ; <+724>
    0x197a95178 <+652>:  orr    x8, xzr, #0xff
    0x197a9517c <+656>:  orr    x9, xzr, #0x200
    0x197a95180 <+660>:  b      0x197a951c8               ; <+732>
    0x197a95184 <+664>:  cmp    w20, #17
    0x197a95188 <+668>:  b.eq   0x197a951a0               ; <+692>
    0x197a9518c <+672>:  cmp    w20, #21
    0x197a95190 <+676>:  b.ne   0x197a951ac               ; <+704>
    0x197a95194 <+680>:  orr    x8, xzr, #0xff
    0x197a95198 <+684>:  orr    x9, xzr, #0x800
    0x197a9519c <+688>:  b      0x197a951c8               ; <+732>
    0x197a951a0 <+692>:  orr    x8, xzr, #0xff
    0x197a951a4 <+696>:  orr    x9, xzr, #0x400
    0x197a951a8 <+700>:  b      0x197a951c8               ; <+732>
    0x197a951ac <+704>:  cmp    w20, #25
    0x197a951b0 <+708>:  b.ne   0x197a951c0               ; <+724>
    0x197a951b4 <+712>:  orr    x8, xzr, #0xff
    0x197a951b8 <+716>:  orr    x9, xzr, #0x1000
    0x197a951bc <+720>:  b      0x197a951c8               ; <+732>
    0x197a951c0 <+724>:  movz   x9, #0
    0x197a951c4 <+728>:  movz   x8, #0
    0x197a951c8 <+732>:  orr    x8, x8, x9
    0x197a951cc <+736>:  mrs    x9, TPIDRRO_EL0
    0x197a951d0 <+740>:  and    x9, x9, #0xfffffffffffffff8
    0x197a951d4 <+744>:  str    x8, [x9, #32]
    0x197a951d8 <+748>:  ldr    w8, [x24, #636]
    0x197a951dc <+752>:  adrp   x10, 16297
    0x197a951e0 <+756>:  add    x10, x10, #672
    0x197a951e4 <+760>:  ldr    x9, [x10, #16]
    0x197a951e8 <+764>:  stp    x9, x20, [x19, #40]
    0x197a951ec <+768>:  tbnz   w8, #1, 0x197a95208       ; <+796>
    0x197a951f0 <+772>:  ldr    x8, [x10, #16]
    0x197a951f4 <+776>:  lsr    w1, w23, #16
    0x197a951f8 <+780>:  movz   x2, #0
    0x197a951fc <+784>:  mov    x0, x20
    0x197a95200 <+788>:  blr    x8
    0x197a95204 <+792>:  b      0x197a952b8               ; <+972>
    0x197a95208 <+796>:  ldr    x9, [x10, #16]
    0x197a9520c <+800>:  ldrb   w10, [x10]
    0x197a95210 <+804>:  tbz    w10, #0, 0x197a95220      ; <+820>
    0x197a95214 <+808>:  mov    x0, x21
    0x197a95218 <+812>:  blr    x9
    0x197a9521c <+816>:  b      0x197a952b8               ; <+972>
    0x197a95220 <+820>:  lsr    w1, w23, #16
    0x197a95224 <+824>:  cmp    w20, #16
    0x197a95228 <+828>:  tbnz   w8, #30, 0x197a95254      ; <+872>
    0x197a9522c <+832>:  b.le   0x197a95258               ; <+876>
    0x197a95230 <+836>:  cmp    w20, #32
    0x197a95234 <+840>:  b.gt   0x197a95290               ; <+932>
    0x197a95238 <+844>:  cmp    w20, #17
    0x197a9523c <+848>:  b.eq   0x197a9529c               ; <+944>
    0x197a95240 <+852>:  cmp    w20, #21
    0x197a95244 <+856>:  b.eq   0x197a95278               ; <+908>
    0x197a95248 <+860>:  cmp    w20, #25
    0x197a9524c <+864>:  b.ne   0x197a952b8               ; <+972>
    0x197a95250 <+868>:  b      0x197a95278               ; <+908>
    0x197a95254 <+872>:  b.gt   0x197a95268               ; <+892>
    0x197a95258 <+876>:  cmp    w20, #9
    0x197a9525c <+880>:  b.ne   0x197a952b8               ; <+972>
    0x197a95260 <+884>:  orr    w0, wzr, #0x3
    0x197a95264 <+888>:  b      0x197a952b0               ; <+964>
    0x197a95268 <+892>:  cmp    w20, #17
    0x197a9526c <+896>:  b.eq   0x197a9529c               ; <+944>
    0x197a95270 <+900>:  cmp    w20, #21
    0x197a95274 <+904>:  b.ne   0x197a952a4               ; <+952>
    0x197a95278 <+908>:  mrs    x8, TPIDRRO_EL0
    0x197a9527c <+912>:  and    x8, x8, #0xfffffffffffffff8
    0x197a95280 <+916>:  movz   x10, #0x10ff
    0x197a95284 <+920>:  str    x10, [x8, #32]
    0x197a95288 <+924>:  orr    w0, wzr, #0x1
    0x197a9528c <+928>:  b      0x197a952b0               ; <+964>
    0x197a95290 <+932>:  cmp    w20, #33
    0x197a95294 <+936>:  b.eq   0x197a952ac               ; <+960>
    0x197a95298 <+940>:  b      0x197a952b8               ; <+972>
    0x197a9529c <+944>:  orr    w0, wzr, #0x2
    0x197a952a0 <+948>:  b      0x197a952b0               ; <+964>
    0x197a952a4 <+952>:  cmp    w20, #25
    0x197a952a8 <+956>:  b.ne   0x197a952b8               ; <+972>
    0x197a952ac <+960>:  movz   w0, #0
    0x197a952b0 <+964>:  movz   x2, #0
    0x197a952b4 <+968>:  blr    x9
    0x197a952b8 <+972>:  orr    w0, wzr, #0x4
    0x197a952bc <+976>:  movz   x1, #0
    0x197a952c0 <+980>:  movz   w2, #0
    0x197a952c4 <+984>:  movz   w3, #0
    0x197a952c8 <+988>:  bl     0x197a9bcb0               ; symbol stub for: _pthread_exit
    0x197a952cc <+992>:  movz   x1, #0
    0x197a952d0 <+996>:  mov    x0, x19
    0x197a952d4 <+1000>: bl     0x197a95f58               ; _pthread_exit
`

**Comment by dsibiski** [comment]
If possible, please provide a basic app (with a repo on Github) where this can be reproduced along with instructions on reproducing it.

**Comment by andpor** [comment]
This also happens with React Native 0.22. Forgot to mention that I am running from a bundle generated with dev=false setting. Let me know if you any additional information from the Xcode thread dump etc.. 


![screen shot 2016-04-02 at 12 39 44 pm](https://cloud.githubusercontent.com/assets/10236571/14248252/d9c97dde-fa73-11e5-8bf7-8992fffca4e4.png)
![screen shot 2016-03-29 at 12 32 24 pm](https://cloud.githubusercontent.com/assets/10236571/14248253/d9ca867a-fa73-11e5-86f8-3d52ef78afb4.png)
![screen shot 2016-04-02 at 12 40 37 pm](https://cloud.githubusercontent.com/assets/10236571/14248254/d9ccb83c-fa73-11e5-879c-266044e6acc3.png)
![screen shot 2016-04-02 at 12 40 09 pm](https://cloud.githubusercontent.com/assets/10236571/14248255/d9cf8224-fa73-11e5-89d8-01785524ae33.png)
![screen shot 2016-04-02 at 12 39 16 pm](https://cloud.githubusercontent.com/assets/10236571/14248256/d9d5d03e-fa73-11e5-9d9f-015a2c28e57a.png)
![screen shot 2016-04-02 at 12 39 29 pm](https://cloud.githubusercontent.com/assets/10236571/14248257/d9d6569e-fa73-11e5-96ea-b07b72e65cfd.png)

**Comment by brentvatne** [comment]
@andpor - we need some code that can reproduce this crash :)

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-8** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.

**Comment by NSKevin** [comment]
I have the same problem in rn 0.20

**Comment by ide** [comment]
Only the latest version of RN (currently 0.36) is supported. If this is reoccurring on RN 0.36 (or whatever the latest version is at the time of reading), please open an new issue.
