### ISSUE TITLE
Text with numberOfLines doesn't work in ListView

### ISSUE THREAD

**Issue by LeezQ** [facebook/react-native#678]
![image](https://cloud.githubusercontent.com/assets/972813/6996075/c80ba81a-dba2-11e4-9c6c-1bdeb0d125c6.png)

I set numberOfLines is 3, but it show only 1 line . 

![image](https://cloud.githubusercontent.com/assets/972813/6996082/f3fac49c-dba2-11e4-917e-0fe84395ce73.png)

**Comment by vjeux** [comment]
Can you try adding style={{flex: 1}} on the text node?

**Comment by brentvatne** [comment]
@LeezQ - we need to see what `styles.comment` are here as well, I suspect your problem may be there. Also any styles on the `render` function itself.

This works fine for me with:

```javascript
  renderRow: function() {
    return (
      <View style={{backgroundColor: "transparent"}}>
        <Text numberOfLines={2}>When true, no visual change is made when text
        is pressed down. By default, a gray oval highlights the text on press
        down.</Text>
      </View>
    )
  },
```

![screen shot 2015-04-05 at 11 51 20 am](https://cloud.githubusercontent.com/assets/90494/6998097/1872f862-db8a-11e4-9cf8-e500db5eb601.png)

**Comment by brentvatne** [comment]
And to pre-empt a potential future question about the height with `numberOfLines` - a fix is coming very soon: https://github.com/facebook/react-native/issues/673

**Comment by LeezQ** [comment]
@vjeux  yes!  it's ok now, thx.  
@brentvatne , I add style={{flex: 1}} on the text node ,then it's ok.  
so if I don't add style {flex:1} on text node or its parent node, react-native can't computing the size of the box. does it right ?

**Comment by vjeux** [comment]
I need to double check but I'm pretty sure that this is how CSS actually behave.

**Comment by zpp-gp** [comment]
must be setting width !
------
<View style={{backgroundColor: "transparent"}}>
                                   <Text style={{width:200}} numberOfLines={1}>When true, no visual change is made when text
                                       is pressed down. By default, a gray oval highlights the text on press
                                       down.</Text>
</View>

------
this is ok!

**Comment by zpp-gp** [comment]
must be setting width!
---
`<View style={{backgroundColor: "transparent"}}>
                                   <Text style={{width:200}} numberOfLines={1}>When true, no visual change is made when text
                                       is pressed down. By default, a gray oval highlights the text on press
                                       down.</Text>
                               </View>`
---
this is ok!

**Comment by zpp-gp** [comment]
you must be setting Width !

`<View style={{backgroundColor: "transparent"}}>
                                   <Text style={{width:200}} numberOfLines={1}>When true, no visual change is made when text
                                       is pressed down. By default, a gray oval highlights the text on press
                                       down.</Text>
                               </View>`

**Comment by lazyTai** [comment]
@zpp-gp 
this shit doesnt work 
i set width  already
![image](https://user-images.githubusercontent.com/16125707/30237220-f61b2eb4-955f-11e7-9b7f-1f0e88f21d42.png)

![image](https://user-images.githubusercontent.com/16125707/30237223-01b45d18-9560-11e7-933e-1ffb20eeab7f.png)

**Comment by lazyTai** [comment]
it work 
If you change the root component from text to view and set the style directly on the nested text component it should all work as expected:
check out 
https://github.com/facebook/react-native/issues/10698
