### ISSUE TITLE
NavigationAnimatedView._onProgressChange comparing delta to Number.EPSILON

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#6781]
https://github.com/facebook/react-native/blob/68918e8773d8f14f6d8203a5a3af05d9a4b14672/Libraries/NavigationExperimental/NavigationAnimatedView.js#L138

```
    const delta = Math.abs(data.value - this.props.navigationState.index);
    if (delta > Number.EPSILON) {
      return;
    }
```

Shouldn't it be `delta < Number.EPSILON` not `delta > Number.EPSILON`?
So that it does not do anything if delta is negligible.

**Comment by skevy** [comment]
cc @hedgerwang @ericvicenti

**Comment by ericvicenti** [comment]
This is intentional. During the transition, the delta will be big, so we want to return and do nothing. When the animated value lands at the destination (the navState.index), the delta will be smaller than epsilon, so we can go and clean up the stale scenes.
