### ISSUE TITLE
onEndReached function of ListView Component auto run although my scroll still on the top

### ISSUE THREAD

**Issue by futurefeeling** [facebook/react-native#6782]
I also ask for help on http://stackoverflow.com/questions/36347396/react-native-listview-component-auto-run-onendreached-function-although-my-scrol.

And I found the same issue here https://github.com/facebook/react-native/issues/6002.

Thanks for all response.

**Comment by futurefeeling** [comment]
when i delete the ScrollView Component and give a style={{flex:1}} to ListView, it works

**Comment by Empact** [comment]
In my case, just removing a wrapping ScrollView was sufficient.

**Comment by bispul** [comment]
I don't have scrollview wrapped with flatlist but still i am getting this issue. the on endreached is called again and again although i have not scrolled my flatlist. I have kept my endReachedThreshold={0.7}
Can anyone help please?
