### ISSUE TITLE
Movie Cell's image not realoding on the Examples / Movies App.

### ISSUE THREAD

**Issue by kocyigityunus** [facebook/react-native#679]
when i search for something on the movies app. the images stay same like :

![screen shot 2015-04-05 at 11 20 32](https://cloud.githubusercontent.com/assets/922418/6996267/d8611adc-db85-11e4-911d-08ac3e32d769.png)
![screen shot 2015-04-05 at 11 20 43](https://cloud.githubusercontent.com/assets/922418/6996268/dc5664d0-db85-11e4-9427-c477e56ec12d.png)

and if my search text includes something like "  '  " the results becoming like this: 

![screen shot 2015-04-05 at 11 22 58](https://cloud.githubusercontent.com/assets/922418/6996271/2996d7e8-db86-11e4-9e5e-89b458081d51.png)

**Comment by kocyigityunus** [comment]
the second problem is about the url query. but the first one is not.

**Comment by bradoyler** [comment]
Dup of #89 ?

**Comment by brentvatne** [comment]
@bradoyler - indeed, this is a dup of #89
