### ISSUE TITLE
ReactAndroid:buildReactNdkLib FAILED

### ISSUE THREAD

**Issue by hiphonezhu** [facebook/react-native#6790]
Android+Windows+SDK(version is ok)+android-ndk-r11b(other version also has the problem)

My problem is:
react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/reactnativejni/JExecutorToken.o, ...) failed.
make (e=2): 系统找不到指定的文件。

and more log is liked "react-native\ReactAndroid\build\tmp\buildReactNdkLib/local/armeabi-v7a/objs/reactnativejni/xxx.o, ...) failed."

so how to solve it?

**Comment by ide** [comment]
`android-ndk-r11b` is not supported -- only r10e is. Try doing a clean and then make sure you're using r10e.

**Comment by hiphonezhu** [comment]
r10e is ok, thank you!
