### ISSUE TITLE
onResponderRelease doesn't work as expected using ListView on Android 

### ISSUE THREAD

**Issue by starzhy** [facebook/react-native#6791]
onResponderRelease doesn't work as expected using ListView on Android

**Comment by vitonzhang** [comment]
I also have this problem.

**Comment by shelly64** [comment]
same issue
it's calling that function

**Comment by mt81** [comment]
Same issue!!

**Comment by antoxi4** [comment]
Same issue on Lenovo Tab Only

**Comment by dimmetrius** [comment]
duplicate #8177

**Comment by satya164** [comment]
What do you mean by doesn't work as expected? Can you provide an example?

**Comment by tuneZola** [comment]
Same here, is there any work around for this?

**Comment by dimmetrius** [comment]
@satya164 i use scrolls like this:

**Comment by lacker** [comment]
I think we need more information - could you provide a project that reproduces this on rnplay.org? I am going to close this issue but please feel free to reopen if you do have that info.

**Comment by Exilz** [comment]
I'm experiencing this issue too on RN 0.39, `onResponderRelease` is never fired on Android.

**Comment by zachrnolan** [comment]
Also having the same issue on RN 0.43.3.
