### ISSUE TITLE
Android error when run 'Movies' example on device

### ISSUE THREAD

**Issue by hiphonezhu** [facebook/react-native#6792]
The error likes this 'Could not connect to development server'.

Windows platform when building with 'gradlew :Examples:Movies:android:app:installDebug', and my device is on the same Wi-Fi network(set debug server host & port for device correctly).

I had run 'AwesomeProject' successfully by 'react-native start', but  'react-native start' is error when in 'Movies' example, so how to solve it?

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by allenyulun** [comment]
i have the same issue,do yo resove it?
