### ISSUE TITLE
Moving to subfolder causes `run-ios` to fail. - Precompiled headers PCH

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#6797]
# :white_check_mark:  I'm willing to fix this
I just need to know where to start.

### The problem:
```shell
react-native init MyAwesomeProject
cd MyAwesomeProject
react-native run-ios # THIS WORKS
cd ..
mkdir newDir
mv MyAwesomeProject/ newDir/MyAwesomeProject
cd newDir/MyAwesomeProject
react-native run-ios # THIS NOW FAILS
```
*ERROR:*
`error: PCH was compiled with module cache path '/Users/gantman/Documents/Projects/rn/MyAwesomeProject/ios/build/ModuleCache/3UB7MQ6FP2IXG', but the
      path is currently '/Users/gantman/Documents/Projects/rn/PlanA/MyAwesomeProject/ios/build/ModuleCache/3UB7MQ6FP2IXG'`

*SOLUTION:*
`rm -rf ios/build/ModuleCache/*`

How can I help?

**Comment by satya164** [comment]
cc @nicklockwood

**Comment by grabbou** [comment]
I believe we can add this to FAQ -> http://stackoverflow.com/a/15463219/3110982

**Comment by GantMan** [comment]
I like adding the `rm` command, too.  As I have been trying to use `react-native run-ios` lately, instead of opening Xcode.

**Comment by GantMan** [comment]
@grabbou : Are you suggesting an edit to: http://facebook.github.io/react-native/docs/known-issues.html#content

Or is FAQ a different document?

**Comment by grabbou** [comment]
Probably, after `init hangs` bit. However I can see that in the future, we might need to split that into sep. files.

**Comment by zeroasterisk** [comment]
FYI this is still happening

**Comment by mateodelnorte** [comment]
+1 Same here
