### ISSUE TITLE
HMR fails to load "node_modules/react-transform/hmr/lib/index.js" on 0.24.0-rc

### ISSUE THREAD

**Issue by ide** [facebook/react-native#6798]
When enabling HMR on 0.24.0-rc in a brand new template project, we get a redbox that says:

> Requiring unknown module "node_modules/react-transform/hmr/lib/index.js". If you are sure the module is there, try restarting the packager or running "npm install".

![screenshot 2016-04-04 12 44 21](https://cloud.githubusercontent.com/assets/379606/14260960/142252d2-fa63-11e5-9185-4178292d45f5.png)

I verified that node_modules/react-transform/hmr/lib/index.js exists, and running `npm start -- --reset-cache` doesn't resolve the issue either.

**Repro steps:** run `./scripts/test-manual-e2e.sh` which sets up a new project and launches it in Android (need to have a simulator or device connected in advance). Enable HMR from the dev menu to get the redbox.

**Comment by martinbigio** [comment]
@ide `/scripts/test-manual-e2e.sh` are not run on CI, right?

**Comment by ide** [comment]
@martinbigio I believe that's correct. I ran [0.24.0-rc](https://github.com/facebook/react-native/tree/v0.24.0-rc) on my MBP (OS X 10.11.4) with Node 5.9.1.

**Comment by mkonicek** [comment]
No tests for HMR on CircleCI yet but @bestander is working on it :tada:

**Comment by martinbigio** [comment]
ok, I'l try to take a look tomorrow, not sure what broke this. Does this also affect hmr while developing or only this e2e tests?

**Comment by ide** [comment]
I believe this happens when developing too. The manual E2E tests set up a new project with `react-native init` and launch the new Android/iOS app. Then I manually opened the dev menu and turned on HMR and got the error.

**Comment by martinbigio** [comment]
The problem was that we were using an old version of the preset due to this commit https://github.com/facebook/react-native/commit/bc54a45542e7b2e537363a2e99a5ef537deac2ba.

The preset @`1.5.2` doesn't include this fix: https://github.com/facebook/react-native/commit/3a1634ec7b0dfa2b5d8890118565006d845e2039

cc @janicduplessis @bestander

**Comment by bestander** [comment]
Ok, #6814 should propagate in an hour.
We may want to cherry-pick it into 0.24.0, @ide

**Comment by martinbigio** [comment]
It's already on the list https://github.com/facebook/react-native/issues/6800 :)

**Comment by ide** [comment]
Thanks for the heads-up. I've cherry-picked it into 0.24-stable (tested -- HMR works) and will do another RC release after the fix for the AssetRegistry lands (https://github.com/facebook/react-native/pull/6822).
