### ISSUE TITLE
[Discussion] Process for depending on third-party Objective-C/Swift code

### ISSUE THREAD

**Issue by ide** [facebook/react-native#68]
What is the way to go about adding purely native third-party dependencies to the React Native backend? This would be the native analogue to adding JS dependencies to package.json. And what are the requirements e.g. license, ARC, iOS version, etc?

**Comment by browniefed** [comment]
@brentvatne already solved with #207 and specifically https://github.com/facebook/react-native/commit/b72acc2313db90b414e53b4ede533071284de4c2
