### ISSUE TITLE
Style native components using stylesheet

### ISSUE THREAD

**Issue by bolismauro** [facebook/react-native#680]
Hi everyone,
I just started to explore react-native and I want to export a native UI component (let's say a custom spinner) and use it in my javascript file.

I manage to do it starting from this gist https://gist.github.com/magus/82415a7b9dfee8e70ccc

What I want to do now is style some custom properties from javascript (eg: spinner color).
It would be cool to do it using the style property, do you think is it possible?
If not can I do it in another way?

Thank you!

**Comment by brentvatne** [comment]
@bolismauro - I believe that will only work if the component is a subclass of `RCTView` - check out `RCTViewManager.m` and notice how it is mapping the styles to native properties. You could create a RCTView subclass wrapper that adds it as a subview or layer and use that to set the frame of the component, which will give it the layout styles, and then you can pass on any other props if you like. See [react-native-video](https://github.com/brentvatne/react-native-video) for an example.

**Comment by bolismauro** [comment]
Perfect, I will try it!

Thank you
