### ISSUE TITLE
WebView scrolling suffers at 15 fps when keyboard is up

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#6801]
Here's a screenshot of the 15 FPS in UI I'm talking about, while scrolling a <WebView> on a Google search page with the keyboard up after focus on the search input box:
![screenshot 2016-04-04 13 42 08](https://cloud.githubusercontent.com/assets/3803466/14262611/3f987358-fa6b-11e5-80a6-ff75b115c5ff.png)

I've searched the web for answers on dismissing the keyboard, on user scrolling the WebView. The ScrollView has keyboardDismissMode=[on-drag|interactive] for doing exactly this, when user drag and scroll away from any input. This should be implemented also for WebView, since there's no trivial way to access state of UX inside the WebView short of injecting JS inside the WebView page, just to detect user interaction events. Seems to be a convoluted way to address this when keyboardDismissMode on WebView would solve this issue elegantly.

**Comment by christopherdro** [comment]
Hey @fungilation! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
