### ISSUE TITLE
[Core JS][Date Object] Obscure bug when instantiating Date with 'm-d-yyyy' across build configs

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6803]
// Build config = Debug
console.log( new Date('4-4-2016') )
"Mon Apr 04 2016 00:00:00 GMT-0700 (PDT)"

// Build config = Release (pushed to phone via Codepush)
{new Date('4-4-2016')}
"Invalid Date"

**Comment by ide** [comment]
I suspect this is because you're using the Chrome debugger while using the Debug build config. Can you make sure you're using the on-device JS VM and see if this issue repros?

**Comment by andresn** [comment]
@ide, whoops, correcting the description.

**Comment by lacker** [comment]
It's been a few months so my hypothesis here is that this was indeed an issue of using the on-device JS VM. I'm closing this issue but if this does repro with the right VM then feel free to reopen it with the new info.
