### ISSUE TITLE
removeClippedSubviews breaks TextInput text selection on Android

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#6805]
If you try to long press a TextInput to copy / cut / delete a block of text inside of a ScrollView with `removeClippedSubviews` set to true, it will not work -- it will just move your cursor to that position. All other interactions with the TextInput work as expected.

Reproduced here: https://github.com/brentvatne/text-selection-repro

1. Clone and run the repo, try to select text in the ListView part (first two text inputs). Try in ScrollVIew and View inputs and notice that it works.
2. Add `removeClippedSubviews={false}` to the ListView and reload, it should now work.

cc @dmmiller @kmagiera

**Comment by dmmiller** [comment]
@brentvatne can you put together a quick repro and I'll look in the next few days please?

**Comment by brentvatne** [comment]
@dmmiller - https://github.com/brentvatne/text-selection-repro just for you man

**Comment by dmmiller** [comment]
@brentvatne Thanks for the repro.  Looking now.  One of the things I found is that if you actually edit the text, it works.  Just go into the TextInput and type a single letter, then try long press and it will work again.

**Comment by dmmiller** [comment]
Found the issue.  Sending a PR internally to fix it, but I'll reference this issue

**Comment by dmmiller** [comment]
Fixed in the attached commit
