### ISSUE TITLE
is there any possible use PureRenderMixin in react native

### ISSUE THREAD

**Issue by L-Jovi** [facebook/react-native#6809]
I want to use `PureRenderMixin ` optimize performance through `shouldComponentUpdate`,
but after `npm i PureRenderMixin --save`, I find that I can't call `PureRenderMixin` correctly :(

I follow [react document](https://facebook.github.io/react/docs/pure-render-mixin.html) ES6 step.

```
import PureRenderMixin from 'react-addons-pure-render-mixin';
class FooComponent extends React.Component {
  constructor(props) {
    super(props);
    this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);
  }

  render() {
    return <div className={this.props.className}>foo</div>;
  }
}
```

and always get `Unable to resolve module react-addons-pure-render-mixin` error.

maybe the foolish question, is there any possible use `PureRenderMixin` in react native? if so, how should I fix it?

thanks for your time.

regards.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
