### ISSUE TITLE
Not possible to change title colour of RefreshControl

### ISSUE THREAD

**Issue by jdmunro** [facebook/react-native#6812]
As far as I can tell there's no way to change the title colour if you provide a title for RefreshControl:

```
<RefreshControl
  refreshing={isRankDataRefreshing}
  onRefresh={onRefreshRankings}
  title={'Refreshing'}
  tintColor='white'
  progressBackgroundColor='white'
/>
```

By default the colour will be black. This is problematic if you have a non-standard background colour:

![simulator screen shot 5 apr 2016 10 55 51](https://cloud.githubusercontent.com/assets/17656/14278147/163d8da0-fb1e-11e5-9758-fe822237513c.png)

I'm not sure if this is the best approach, but one solution would just be to add an additional prop, ```titleColor```, for instance.

**Comment by janicduplessis** [comment]
I think a titleColor prop is fine, the title property of the UIRefreshControl on iOS is an NSAttributedString so it should be simple to change the color. Would you like to submit a PR that implements that?

**Comment by skv-headless** [comment]
@janicduplessis could you please take a look at #6970? Looks terrible on dark background :disappointed:

**Comment by janicduplessis** [comment]
@skv-headless Oh, I missed that one :). I'll take a look today.
