### ISSUE TITLE
UNMET PEER DEPENDENCY react@^0.14.5

### ISSUE THREAD

**Issue by veryitman** [facebook/react-native#6815]
I want to use react-native of version 0.22.0.
I run 'npm install react-native@0.22.2 --save', but it show as follow
├── UNMET PEER DEPENDENCY react@^0.14.5
└── react-native@0.22.2 

npm WARN EPEERINVALID react-native@0.22.2 requires a peer of react@^0.14.5 but none was installed.
How to do? please help me.

**Comment by kapv89** [comment]
`npm install --save react@0.14.5`

**Comment by jeanregisser** [comment]
Hi @veryitman,

react was changed from a dependency to a peer dependency in react-native v0.21.0.
Therefore, it's necessary to include `react` in your project's dependencies.
Just run `npm install --save react`

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by veryitman** [comment]
@jeanregisser 
My contents  of package.json as follow:
{
  "name": "kkk",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.22.2"
  }
}

**Comment by veryitman** [comment]
@kapv89 
why?

**Comment by veryitman** [comment]
@jeanregisser 
I first run:
npm install --save react
and i run finaly:
npm install

It's no warning.But i can't understand.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@veryitman Don't forget `react-native upgrade`

**Comment by mohitsharma01** [comment]
I resolved this issue saying requires a peer of react@>=0.14.0 but none was installed. by uninstalling the react and react-dom and then locally install the react@0.14.0 and react-dom@0.14.0..
after this, I was able to install my module which had react@>=0.14.0 added as "peerDependencies": {
"react": ">=0.14.0"
},.
I uninstalled and installed the react with the latest version again, It worked for me.
