### ISSUE TITLE
Image 'contain' resizeMode not working

### ISSUE THREAD

**Issue by AleCaste** [facebook/react-native#6819]
Hello,
I am using React Native on a real Android device.
When creating a really simple app with just the following render function on the main app component...
```
  render() {
    <Image
      source={{uri:'http://resizing.flixster.com/DeLpPTAwX3O2LszOpeaMHjbzuAw=/53x77/dkpu1ddg7pbsk.cloudfront.net/movie/11/16/47/11164719_ori.jpg'}}
      style={
        {
          flex: 1,
          resizeMode: 'contain',
          backgroundColor: 'yellow'
        }          
      } />
  }
```
I get the following result on my device:
![screenshot_2016-04-05-11-05-41](https://cloud.githubusercontent.com/assets/6316907/14289173/4e7a891a-fb1f-11e5-834d-158873be9fd2.png)

As you can see the whole background is yellow so that tells us the image element is taking the whole screen size indeed. But it is just rendered wrong.
The 'cover' resizeMode does work as expected (and so does the 'stretch' mode).
It is the 'contain' mode that is not working (the most important one from my point of view).
The problem gets even worse when placing the image on a ListView since the image does not even show.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
