### ISSUE TITLE
Xcode build failed because of missing library (RCTGeolocation)

### ISSUE THREAD

**Issue by sebslomski** [facebook/react-native#682]
Hi,

after installing react-native-cli from scratch and creating a new project, the Xcode build is not passing. 

The error: 
```
ld: library not found for -lRCTGeolocation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas?

A react-native project I created two weeks ago is working perfectly.

**Comment by brentvatne** [comment]
@sebslomski - what does your "Link Binary with Libraries" screen look like? eg: http://url.brentvatne.ca/1gK2z

Also, is RCTGeolocation.xcodeproj under your Libraries directory? eg: http://url.brentvatne.ca/dWH9 - if not, you will need to add it to the project (node_modules/react-native/Libraries/GeoLocation/RCTGeolocation.xcodeproj)

**Comment by sebslomski** [comment]
Thanks for your input! The Xcode referenced to "node_modules/react-native/Libraries/Geo**L**ocation/RCTGeolocation.xcodeproj", but the folder is named Geo**l**ocation.
It's working on master head.

**Comment by ItsLeeOwen** [comment]
I'm also getting this error when running xcode immediately after "react-native init myproject".  What was the resolution?

**Comment by sebslomski** [comment]
Well, I'm running my OS X on a case sensitive file system. Switching to react-native master fixed that for me.

**Comment by Abrarmm** [comment]
@ItsLeeOwen how did you did this ?

**Comment by abuammar** [comment]
i got this error

The following build commands failed:
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolylineManager.o AirMaps/AIRMapPolylineManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygon.o AirMaps/AIRMapPolygon.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/ws1/Code/mobile/ios/build/Build/Intermediates/AirMaps.build/Debug-iphonesimulator/AirMaps.build/Objects-normal/x86_64/AIRMapPolygonManager.o AirMaps/AIRMapPolygonManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
Installing build/Build/Products/Debug-iphonesimulator/WS1.com.app
An error was encountered processing the command (domain=LaunchServicesError, code=0):
The operation couldn’t be completed. (LaunchServicesError error 0.)
Launching org.reactjs.native.example.ws1
An error was encountered processing the command (domain=FBSOpenApplicationErrorDomain, code=4):
The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.)
