### ISSUE TITLE
custom http Headers in source headers for WebView Request dont work

### ISSUE THREAD

**Issue by xpmike** [facebook/react-native#6820]
i modify the HTTP request headers of a React Native WebView component on iOS ，but  it doesn't seem to work

**Comment by charpeni** [comment]
Can you provide a snippet with expected result ?

You can even host it on https://rnplay.org/

**Comment by tomwalters** [comment]
I can add new headers [as shown here](https://rnplay.org/apps/M4tiGw) - but trying to modify something like User-Agent doesn't work. Looks like it's being overwritten after the custom headers have been set.

**Comment by xpmike** [comment]
i wanto debug this issue, and i add     NSLog(headers) in RCTConvert.m after on line 132,
but when i run the app, xcode display error
`
2016-04-07 14:11:18.523 [error][tid:main][RCTUIManager.m:1068] Error setting property 'source' of RCTWebView with tag #6: Exception thrown while executing UI block: -[__NSDictionaryM _fastCStringContents:]: unrecognized selector sent to instance 0x7febf2831cb0
`
i add custom header on android Is normal，but on ios dont work

**Comment by litaonet** [comment]
小豪 我顶你

**Comment by satya164** [comment]
Can you post the code you're using?

**Comment by xpmike** [comment]
@satya164 

my RN code is
`<WebView
          source={{uri: 'http://m.domain.com/item/123/inspect#er',headers:{'testkey':'testvalue','User-Agent':'my-app'}}}
          style={{width:Dimensions.get('window').width,height: Dimensions.get('window').height}}
        />`

the php script is
`<?php
print_r($_SERVER);`

===
when i run it, show this
`
            [testkey] => Array
                (
                    [0] => testvalue
                )
            [user-agent] => Array
                (
                    [0] => Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13E238
                )`

i think the user-agent show be modifed to 'my-app', but it seams my settings donot take effect

Is my method is wrong or a ReactNativeBug

**Comment by MrPluto** [comment]
in my case , when i set headers just like `headers:{key:value}`, and app crashed 
```2016-05-24 14:01:25.394 free[26305:1224069] -[__NSArrayM length]: unrecognized selector sent to instance 0x79708370
2016-05-24 14:01:25.397 free[26305:1224069] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM length]: unrecognized selector sent to instance 0x79708370'
```

**Comment by burgalon** [comment]
Use this code in your AppDelegate.m to set the user agent:
`NSUserDefaults.standardUserDefaults().registerDefaults(["UserAgent": "Custom-Agent"])`

**Comment by greena13** [comment]
https://github.com/facebook/react-native/issues/5821 describes some undocumented props for this purpose.

**Comment by ghidinelli** [comment]
We're experiencing this on reloads as well in #8693

**Comment by lacker** [comment]
I think this issue has been stuck in "needs more information" for a few months so I am going to close this.
