### ISSUE TITLE
Adding border only to the one side of the <Text/> component in React Native (iOS)

### ISSUE THREAD

**Issue by danginirav** [facebook/react-native#6833]
I am facing something weird issue with React-Native's `<Text/>` component in **iOS**.

I wanted to apply `borderBottomWidth` style into `<Text/>` component but it did NOT work. However, the `borderWidth` option **worked**.

- **Worked**
````
<Text style={{borderWidth:1}}> React Native </Text>
````

- **NOT Worked**
````
<Text style={{borderBottomWidth:1}}> React Native </Text>
````

<br/>Is there any way to only apply bottom level border into the `<Text/>` component? 

Thank you!

(I have added same question in [StackOverflow](http://stackoverflow.com/questions/36444874/adding-border-only-to-the-one-side-of-the-text-component-in-react-native-ios))

----
**Note:** 

I am aware of following mentioned approaches in order to achieve this but in my case, I required to apply the style only to the `<Text/>` component.

1. We can try wrapping `<View/>` to the `<Text/>` and apply `borderBottomWidth` style to the `<View/>`. (`borderBottomWidth` works fine with `<View/>`)
2. Adding such `<View/>` just below to the `<Text/>` component  which can look like a line.

**Comment by dsibiski** [comment]
This isn't currently possible. See the following RN issue: https://github.com/facebook/react-native/issues/29 and this ticket on Product Pains: https://productpains.com/post/react-native/add-borderwidth-left-right-top-bottom-to-textinput-/

**Comment by dsibiski** [comment]
@facebook-github-bot answered

**Comment by hellsingblack** [comment]
@facebook-github-bot answered

**Comment by Anita-Singh07** [comment]
ddd
