### ISSUE TITLE
Documentation search not working for 0.23

### ISSUE THREAD

**Issue by juankiz** [facebook/react-native#6845]
I tried with safari and chrome on a mac http://facebook.github.io/react-native/

**Comment by tomwalters** [comment]
I can't reproduce, what version OS and Safari are you using?

**Comment by tomazahlin** [comment]
I have the same problem, I can write something in the input, but cannot execute the search.

I have OSX 10.11.2, it does not work in Chrome and Safari. Not sure about other browsers.

Chrome Version 49.0.2623.87 (64-bit)
Safari Version 9.0.2 (11601.3.9)

**Comment by charpeni** [comment]
I confirm the issue, it doesn't related to a specific browser or OS.

@vjeux It seems related to Algolia facet filters with version tag, docsearch only works with `tags:master`, no result with `tags:0.2x`. Do you forget to update the index on Algolia on publishing ?

**Comment by vjeux** [comment]
Thanks for the ping, asking the Algolia folks

**Comment by redox** [comment]
> Thanks for the ping, asking the Algolia folks

We're on it!

**Comment by ElPicador** [comment]
It's back online. Happy searching.

The page http://facebook.github.io/react-native/versions.html has its structure changed, so we couldn't detect the new versions. It's fixed.

**Comment by charpeni** [comment]
@facebook-github-bot close
