### ISSUE TITLE
[Docs][AsyncStorage] Please update / elaborate "static mergeItem... Not supported by all native implementations."

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#6847]
"by all native implementations" Android? iOS? A min release of React?  Thanks in advance!

**Comment by satya164** [comment]
Most prolly means that it's not supported on Android. Not sure though.

**Comment by geirman** [comment]
This is a good suggestion! We should definitely clarify, but I'm also unclear what it means exactly and could only hazard a guess as @satya164 did. My guess would be that some **older versions** of Android don't support.

**Comment by sahrens** [comment]
Hmm, not sure any more - we have multiple internal AsyncStorage implementations internally and some probably don't support it.

**Comment by lacker** [comment]
I started digging and didn't totally figure it out but if you look at https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/Libraries/Storage/AsyncStorage.js there is a line:

`var RCTAsyncStorage = RCTAsyncRocksDBStorage || RCTAsyncSQLiteStorage || RCTAsyncFileStorage;`

At least some of those don't appear to be externally available to the open source project. I was gonna dig more but ran out of time so figured i'd post this as a hint to whoever continues this hunt. My suggestion, just use mergeItem, and if it works then it's likely to work everywhere. From the code it doesn't seem like this is about an old version of android, it seems like it's about some internal config setting.

**Comment by Kerrick** [comment]
Is this still the current state of `mergeItem`? We _think_ it works everywhere as long as it works somewhere? The docs still have the cryptic note this issue was created for.

**Comment by geirman** [comment]
@Kerrick that seems like a reasonable assumption. I think this ticket was closed as part of the general cleanup, and since no one objected, it stayed closed. If you dig deeper to investigate, let us know what you find by opening a new issue and referencing this one.
