### ISSUE TITLE
[iOS][upgrading from 0.19] XMLHttpRequest uploads file with incorrect mime-type after upgrade from 0.19?

### ISSUE THREAD

**Issue by javamonn** [facebook/react-native#6850]
Hi all,

I'm seeing some strange behavior after upgrading from RN 0.19. My situation is as follows: User selects an image to upload from assets from `CameraRoll`. App requests a [signed URL](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property) from app backend to upload the image to S3, passing the file name and file mime-type (parsed from the EXT= part of asset-library URIs). File is uploaded to S3 as follows:

```
var xhr = new XMLHttpRequest()
xhr.onload = () => {
   ....
}
xhr.open('PUT', signedUrl)
xhr.setRequestHeader('Content-Type', parsedMimeType)
xhr.timeout = 90000
xhr.send({uri: localFileUri})
```

But the upload fails, as S3 will calculate the signed url always using a mime type of `image/jpeg`, which results in a different signature, and S3 returns a 403. I'm fairly confident that this is not an issue in the upload or signed URL logic, as the same code will work without issue on Android. On iOS on RN 0.19 however, I can upload without issue when uploading from a simulator (uploading both .jpgs and .pngs), but cannot upload from a physical device without overriding the parsed mime type in favor of using `image/jpeg`. Once I upgrade to RN 0.20, both iOS simulator and device fail (with and without mime type forcing) and Android continues to work. 

Some questions:

1) Is there a better way I can view the XMLHttpRequest as it hits the network? Can I see or otherwise log the request headers that get sent and the request body? I'm curious to find where the type mismatch occurs - S3 is either inferring the `image/jpeg` type from the file or perhaps the Content-Type header is being overwritten?

2) Is there a better way to retrieve the mime-type of assets retrieved from the CameraRoll?

**Comment by satya164** [comment]
Try this - `xhr.send({ uri: uri, type: 'image/png' })` instead. Works for me.

**Comment by r049** [comment]
@satya164 I spent so much time for this issue, you saved me 👍

**Comment by javamonn** [comment]
For me, the core cause of this issue was due to https://github.com/facebook/react-native/issues/7329.
