### ISSUE TITLE
HMR is not compatible with tcomb-form-native

### ISSUE THREAD

**Issue by cpunion** [facebook/react-native#6853]
I created a project https://github.com/cpunion/TestTcomb to reproduce a problem about HMR is not compatible with https://github.com/gcanti/tcomb-form-native . Live Reload works fine, HMR can't work, `tcomb-form-native` is a pure JavaScript library, so I think maybe it is a problem of HMR.

**Environment**

* Mac OSX 10.11.4
* Xcode 7.3
* Node 5.5.0, npm 3.6.0
* react@0.14.8
* react-native@0.23.0
* tcomb-form-native@0.4.0

**Create steps**

> react-native init TestTcomb
> cd TestTcomb
> npm install --save tcomb-form-native
> Copy js code from https://github.com/gcanti/tcomb-form-native into index.ios.js and index.android.js

**Test steps**

* react-native run-ios
* Enable Hot Reloading, reproduce the problem
* Disable Hot Reloading, works find
* Has same problem on Android

**Disabled Hot Reloading**

<img width="468" alt="2016-04-07 12 58 00" src="https://cloud.githubusercontent.com/assets/8459/14341151/84ec60c4-fcc1-11e5-8aae-ba1601691827.png">

**Enabled Hot Reloading**

<img width="467" alt="2016-04-07 12 58 15" src="https://cloud.githubusercontent.com/assets/8459/14341161/a1082c0c-fcc1-11e5-8616-f56f05bfb98b.png">

**Comment by iZaL** [comment]
[https://github.com/gcanti/tcomb-form-native/issues/132](https://github.com/gcanti/tcomb-form-native/issues/132)

**Comment by cpunion** [comment]
@iZaL Thanks, I will track that issue.

**Comment by brentvatne** [comment]
Closing because it looks like it's being tracked on the other issue mentioned above and seems to be an issue with that lib! :)
