### ISSUE TITLE
Add support for multiple JS contexts

### ISSUE THREAD

**Issue by Richard-Cao** [facebook/react-native#6854]
What can we do?
https://github.com/facebook/react-native/commit/872b697730291575c5c25556bc9b49f66863947c

**Comment by dsibiski** [comment]
Hi @Richard-Cao, what is it that you're asking for here? Can you explain a bit more?

**Comment by Richard-Cao** [comment]
@dsibiski #5399    
like this?

**Comment by Richard-Cao** [comment]
separate js bundle? or anything?

**Comment by satya164** [comment]
Closing this since you've another issue open for this already. Please don't open issues for questions.
