### ISSUE TITLE
Contacts API

### ISSUE THREAD

**Issue by colinramsay** [facebook/react-native#686]
Doesn't look like there's anything been mentioned about a way of interfacing with the address book on a device. Is this a planned feature or something that'll be deferred to the community?

**Comment by vjeux** [comment]
Our current thinking around all of those APIs is that it's going to be left to whoever bridges it first. If we need it internally we'll build it and dogfood it. When it becomes good and stable, we'll include it in core. But if someone else in the community beats us to it and the package on npm gains significant traction, we'll likely bring it in core instead (assuming the author wants to).

The good part is that the plugin api is public and what is being used for all the existing components today, so no one has a disadvantage.

We don't have any plans for a feature that would use the contact api right now, so it's unlikely going to be coming from us in the next few months.

This whole plugin is still very much up in the air, please let me know if you have ideas on how to make it work best for everyone

**Comment by brentvatne** [comment]
@colinramsay - if you're interested in building a bridge, ping me as notbrent on irc (#reactnative on freenode) and I can help you get started!

**Comment by darylrowland** [comment]
I've started building a basic Contacts API for a project I'm working on. I'll try and pop it on Github this afternoon or tomorrow if it would be useful for people.

**Comment by mattotodd** [comment]
@darylrowland would love to check that out

**Comment by mattotodd** [comment]
I've begun work on this a had a few questions about the NativeModules bridge

Am I limited to String for error and params in the callbacks?  What would it look like to return a object or array of objects if that is possible?

Is there a standard for what errors should return?

I realize the Native Modules are still a work in progress, but what is the expected way to package/distribute?  @brentvatne showed me an example of his react-native-login which creates an example xcode project that includes his actual bridge.

By the way, I was psyched out how simple it was to extend this and get it working!

Current code. Not complete, but any advice would be appreciated as I do not come from an objective-c background.  (I intend to paginate the getAllContacts call,  this was just to see if it was working, and it is!!)

```objectivec
@import AddressBook;
#import "AddressBook.h"

@implementation AddressBook

- (void)hasABAuth:(RCTResponseSenderBlock)callback  {
  RCT_EXPORT(hasAuth);
  if (ABAddressBookGetAuthorizationStatus() == kABAuthorizationStatusDenied ||
    ABAddressBookGetAuthorizationStatus() == kABAuthorizationStatusRestricted){
    callback(@[[NSNull null], @"denied"]);
  } else if (ABAddressBookGetAuthorizationStatus() == kABAuthorizationStatusAuthorized){
    callback(@[[NSNull null], @"authorized"]);
  } else { //ABAddressBookGetAuthorizationStatus() == kABAuthorizationStatusNotDetermined
    callback(@[[NSNull null], @"undetermined"]);
  }
}

- (void)requestABAuth:(RCTResponseSenderBlock)callback  {
  RCT_EXPORT(requestAuth);
  ABAddressBookRequestAccessWithCompletion(ABAddressBookCreateWithOptions(NULL, nil), ^(bool granted, CFErrorRef error) {
    if (!granted){
      callback(@[[NSNull null], @"denied"]);
      return;
    }
    callback(@[[NSNull null], @"authorized"]);
  });
}

-(void)getAllContacts:(RCTResponseSenderBlock)callback  {
  RCT_EXPORT();
  ABAddressBookRef addressBookRef = ABAddressBookCreateWithOptions(NULL, nil);
  NSArray *allContacts = (__bridge NSArray *)ABAddressBookCopyArrayOfAllPeople(addressBookRef);
  NSLog(@"%@", allContacts);
}

@end
```

**Comment by frantic** [comment]
> Am I limited to String for error and params in the callbacks? What would it look like to return a object or array of objects if that is possible?

`callback` accepts array of any JSONable data, including `NSArray` and `NSDictionary`. E.g.:

```objective-c
callback(@[@[@1], @{@"foo": @"bar"}])
```

> Is there a standard for what errors should return?

For passing Error-like objects, see `RCTMakeError`. You can attach any field to your error object, but at minimum it's good to have `message`.

**Comment by mattotodd** [comment]
@frantic thx

One other question,  the react native [Image](https://facebook.github.io/react-native/docs/image.html) component takes a source uri (local, http, or static asset as part of project)

When accessing a AddressBook contact,  it seems there is no way to get access to the filepath of the persons image.  You obtain the image data and init it directly into a UIImage

```objectivec
NSData  *imgData = (NSData *)ABPersonCopyImageData(person);
UIImage  *img = [UIImage imageWithData:imgData]; 
```

Any thoughts on how to handle such a thing with react native? 
Unless I'm missing something, i'm having trouble trying to see if such a thing would be possible to resolve.

**Comment by mattotodd** [comment]
https://github.com/mattotodd/react-native-addressbook-ios

Comments appreciated

**Comment by rt2zz** [comment]
Thanks @mattotodd 

I took your code and reworked the organization / api a bit : https://github.com/rt2zz/react-native-addressbook.

**Comment by mattotodd** [comment]
@rt2zz Why not fork and create a pull-request ?  Seems like you just copy pasted my code for your initial commit.  

The reason for using familyname vs last name was that I was trying to use standards vs just ios specific. 

http://www.w3.org/TR/2011/WD-contacts-api-20110616/#idl-def-ContactName

That way when the time comes for react-native-android/windows etc, they would all be the same,  "learn once, write everywhere"

**Comment by brentvatne** [comment]
Thanks @mattotodd for putting that together :smile:

**Comment by niftylettuce** [comment]
Can you please re-open this issue?  We still don't have Android support.

See my bug bounty and the issue here <https://github.com/rt2zz/react-native-contacts/issues/10>

**Comment by mattotodd** [comment]
@niftylettuce the react-native team does not build out anything they don't directly use, Contacts being one of them. If a third-party build something and it gets good feedback, it can be pulled back in

I started an iOS version  https://github.com/mattotodd/react-native-addressbook-ios

I can take a look at an Android version, but might take a little time

**Comment by niftylettuce** [comment]
@mattotodd can you peak into https://github.com/rt2zz/react-native-contacts/pull/13#issuecomment-158701719

**Comment by brentvatne** [comment]
:nail_care:'d it @mattotodd

**Comment by mattotodd** [comment]
@brentvatne what did I nail ?

**Comment by pickhardt** [comment]
I've been using https://github.com/rt2zz/react-native-contacts but it is lacking in a number of ways, not that they aren't working on it, just that it's kind of important so I want to bring this up for discussion again. This is the sort of thing I think could really benefit by being part of official React Native, because it's pretty fundamental to a lot of apps. I'd estimate more apps would use contacts than a number of the official components (not that they're great to have too).

I propose that https://github.com/rt2zz/react-native-contacts be slated to be part of the official React Native, as a Contacts component.

**Comment by satya164** [comment]
@pickhardt It should stay as a different module IMO. The core team won't likely to be able to work on it. So it's better to be a third party module where it can get better care.

**Comment by mattotodd** [comment]
Let be honest, FB already knows all your contacts. They have no need to support the native contacts api, so like @satya164 said, it makes more sense for a third party to take care of it.

**Comment by niftylettuce** [comment]
I've had a lot of success with https://github.com/axemclion/react-native-cordova-plugin (see my fork for a bug I patched), in combination with official Cordova plugins like https://github.com/apache/cordova-plugin-contacts.  It's a port basically and has helped out in meanwhile.
