### ISSUE TITLE
WebSocket connection failed error after inactvity

### ISSUE THREAD

**Issue by fender** [facebook/react-native#6861]
If I lose internet connection for an extended period of time after opening a WebSocket and then come back to my app, I get the error shown below. Immediately after the error, my socket `onerror()` listener is called followed by `onclose()`. That seems right to me, but I feel like there shouldn't be a fatal error on the app. I would just re-connect the socket in this situation.

I am on the iOS Simulator for an iPhone 5 running React Native 0.22.2.

![simulator screen shot 7 apr 2016 15 14 47](https://cloud.githubusercontent.com/assets/1436470/14352214/acc11af6-fcd3-11e5-9e6f-f264ca61f8f9.png)

**Comment by satya164** [comment]
Might be that someone is trying to send a message when socket is not connected. Can you post the code to reproduce this?

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by af7** [comment]
+1 Can you please reopen this? It happens to me too. I am in "DEBUG" mode on an actual device and when the iPad sleeps then it shows this message when I turn it on. This is quite disturbing, if it could be fixed it would be good. Thanks!

**Comment by igolden** [comment]
+1 Happening to me now with large background requests to API
