### ISSUE TITLE
PerformanceOverlay issue

### ISSUE THREAD

**Issue by magrinj** [facebook/react-native#6862]
Hi everyone,

Today I got an exception with the `Inspector`, when I enable it with `command + D` on my emulator if I click on `Perf` button just across `Inspect`, I got this exception:

**Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `PerformanceOverlay`. See https://fb.me/react-warning-keys for more information.**

<img src="http://img15.hostingpics.net/pics/517958ScreenShot20160407at41830PM.png" alt="Heberger image" />

**Comment by skevy** [comment]
This looks like it was fixed in #6865. Thanks @magrinj and @gorangajic. :)
