### ISSUE TITLE
PickerIOS style is actually style of View around RCTPickerIOS

### ISSUE THREAD

**Issue by vjajetic** [facebook/react-native#6863]
When I put style on PickerIOS it's actually style for View which is around RCTPickerIOS in PickerIOS.ios.js, and when I change it and place {this.props.style} to RCTPickerIos style (instead of View around it), it applies directly to picker and it solves my problem. Can someone apply it (and if not, why is that so)? I can change it locally, but for every new version I would had to merge it or change it all over again. Thanks in advance

**Comment by grabbou** [comment]
Hey, there's also `itemStyle` property as of this commit that is applied to `RCTPickerIOS` component -> https://github.com/facebook/react-native/commit/e2c35dddbac6ce305f1ed7b445e92fd392b42865. That's probably what you have been looking for :)

**Comment by vjajetic** [comment]
That's it! Thank you very much! :)
