### ISSUE TITLE
When using XCode, console.log of js object containing cycles causes app to rapidly leak memory and crash.

### ISSUE THREAD

**Issue by mmmurf** [facebook/react-native#6866]
issue: console.log of js object containing cycles causes app to leak memory rapidly and crash.

react versions tested: react-native 23 and 22

occurs when using console.log and displaying output in XCode. Does not occur when using Chrome debugging.

It seems that the proper behavior would be to trigger an error if a js object cannot be printed because it contains cycles, or better yet to just print it the way Chrome does.

**Comment by brentvatne** [comment]
Hi there! If you'd like to submit a PR to fix this it would be welcome :)

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply
