### ISSUE TITLE
TextInput: crossPlatformKeyboardTypeMap error

### ISSUE THREAD

**Issue by checkraiser** [facebook/react-native#687]
I use TextInput inside a View, and i got error:

    undefined is not an object(evaluatiing      'keyboardTypeConsts[crossPlatformKeyboardTypeMap[this.props.keyboardType || this.props.keyboardType]')

Do you know what this error mean and how to fix it ?
Thank you very much.

**Comment by brentvatne** [comment]
@checkraiser - can you post the view code that causes this?

**Comment by checkraiser** [comment]
The strange thing is there is no code at all! I just put an TextInput to render:
   
    <View><TextInput /></View>

and it throws that error.
Tested on my simulator: iPhone 5.
Thank you for quick response.

**Comment by brentvatne** [comment]
@checkraiser - is this on a brand new project created with `react-native init`? Which version of `react-native-cli`?

**Comment by brentvatne** [comment]
@checkraiser - I just did the following, and it worked with `react-native-cli` 0.1.3:

1. Create project and cd into it
`react-native init TestText`
`cd TestText`

2. Edit `index.ios.js` and make it this:

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TextInput,
} = React;

var TestText = React.createClass({
  getInitialState() {
    return {}
  },

  render: function() {
    return (
      <View style={styles.container}>
        <View>
          <TextInput
            style={{height: 40, borderColor: 'gray', borderWidth: 1}}
            onChangeText={(text) => this.setState({input: text})}
          />
          <Text>{'user input: ' + this.state.input}</Text>
        </View>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+Control+Z for dev menu
        </Text>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TestText', () => TestText);
```

This works on the iPhone 5 simulator for me. Is it possible that you unlinked a core library in your project by accident?

**Comment by checkraiser** [comment]
Yes, it's a new project created with react-native init. I use version 0.3.1 of react-native. My code use bridge module, but in fact, i just test to render a TextInput before using anything special, and i got that error.

**Comment by brentvatne** [comment]
@checkraiser - can you push your entire project to a Github repo please?

**Comment by checkraiser** [comment]
Hi, i put the gist at [TextInput bug](https://gist.github.com/checkraiser/20343e4a0bc362327cd0)
There is an external module here but it's not important.

**Comment by brentvatne** [comment]
@checkraiser - tried to test that, hard to reproduce without the native module, could you post that?

**Comment by brentvatne** [comment]
@checkraiser - I replace `render` on `EtyList` with:

```javascript
  render: function() {
    return (
      <View style={{flex: 1}}>
        <React.TextInput placeholder='I love you' style={{flex: 1}} />
        <React.ScrollView scrollEventThrottle={500} contentInset={{top: -100}}
          style={styles.scrollView}>
            <TextInput />
            <React.ListView dataSource={this.state.user}
            renderRow = {this.renderItem}
            style={styles.listView} />
          </React.ScrollView>
      </View>
    )
```

It works just fine. All I did was replace `index.ios.js` on a new project created with `react-native init`. You could try doing init again if you don't want to debug too carefully, somewhere along the line it's possible that you accidentally unlinked an important core library.

**Comment by checkraiser** [comment]
Hm, i really don't understand what's going on here. If i remove that TextInput, the project runs fine. If i put it in, it shows error (specifically to the TextInput component). Thank you for support. I will try to get through.

**Comment by brentvatne** [comment]
@checkraiser - if you want to share the full repo on Github I can help debug further! Otherwise I suppose we can just close the issue

**Comment by checkraiser** [comment]
I put the project here: [https://github.com/checkraiser/onlineetymology](https://github.com/checkraiser/onlineetymology)
To test, please create sqlite with table ety, 3 columns Id, origin and definition. Both are string types.
Link the ety.db with Xcode and see.
Thank you for taking time with me.

**Comment by brentvatne** [comment]
@checkraiser - sorry for not getting back to you here, I somehow lost this amongst all of the other issue notifications :frowning:

I have used TextInput inside of View many times and I have never had any issues - if you are still having this problem on v0.5.0-rc, ping me and I can reopen.
