### ISSUE TITLE
Warning: Native component for "RCTMap" does not exist - Android

### ISSUE THREAD

**Issue by kristian-puccio** [facebook/react-native#6872]
Hi I'm getting the warning `Native component for "RCTMap" does not exist` on Android (emulator and rnplay) when I try to add MapView.

Here is a rnplay instance that has the same problem: https://rnplay.org/apps/v4N01g

I've tried with react-native 0.22 and 0.23.1, The rnplay is on 0.21 I think.

**Comment by brentvatne** [comment]
Hi @kristian-puccio! Sorry for the hassle! The Android Map component that we recommend using is [react-native-maps](https://github.com/lelandrichardson/react-native-maps) as it's more feature complete than the internal implementation at Facebook apparently ([see this note in docs](https://facebook.github.io/react-native/docs/known-issues.html#views)).

It would be great to have documentation for this inside of the MapView section of the docs, can you submit a PR for that?

**Comment by kristian-puccio** [comment]
No worries can do. So you'd like me to mention that the preferred way to
use maps is react-native-maps for both systems or just Android?
