### ISSUE TITLE
`- [RCTFPSGraph onTick:]` thread safety problem.

### ISSUE THREAD

**Issue by lldong** [facebook/react-native#6874]
[`- [RCTFPSGraph onTick:]`](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/React/Profiler/RCTFPSGraph.m#L99) is accessing the UILabel instance from React's JavaScript thread.

**Comment by tadeuzagallo** [comment]
Fixed on #7500
