### ISSUE TITLE
How to make a full screen modal ?

### ISSUE THREAD

**Issue by kocyigityunus** [facebook/react-native#688]
i am trying to make a full screen modal in a <NavigatorIOS/> at the root of the app like in the UIExplorer Example. but when i want to close the modal, it's always starting with the "InitialComponent" of the <NavigatorIOS />

what i solve this : 
1 ) instead of showing it on the root i set  styles " position : absolute, top, right = 0 etc. ". but this didn't work.
 
![screen shot 2015-04-05 at 20 51 21](https://cloud.githubusercontent.com/assets/922418/6997928/c0c5ffda-dbd7-11e4-977c-0b759b49693e.png)

2 ) instead of returning an NavigatorIOS element in render. i tried to create a NavigatorIOS element with React.createElement  and passing it to render method. but i couldn't get state of the parent.

    'use strict';

    var React = require('react-native');
    var {
      AppRegistry,
      NavigatorIOS,
      StyleSheet,
      View,
    } = React;

    var styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: 'white',
      },
      modal: {
        //flex: 1,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        top: 0
      }
    });

    var FirstScreen = require('./FirstScreen');

    var blabla = function( obj, modal ){
      console.log("obj : ", obj);
      console.log( "setState : ", obj.setState );
      // set state is always undefined
      obj.setState({ openModal: modal });
    };

    var DenemeApp = React.createClass({
      getInitialState: function() {
        return {
          openModal: (null: ?React.Component),
          modalOpened : true,
        };
      },
      closeModal : function() {
        this.setState( { modalOpened : false, } );
      },
      render: function() {
        if (this.state.openModal) {
          var Modal = this.state.openModal;
          return (
            <Modal
              onModalExit={() => {
                this.setState({ openModal: null, });
              }}
            />
          );
        }
        console.log( myNavigatorIOS )
        return myNavigatorIOS
      }
    });

    var myNavigatorIOS = React.createElement( NavigatorIOS,
      {style:styles.container,
        initialRoute : {
          title: 'FirstScreen',
          component: FirstScreen,
          passProps: {
            onModalRequested: (modal) => {
              blabla( DenemeApp, modal );
              //this.setState({ openModal: modal, });
            },
          }
        }
      }
    );

    AppRegistry.registerComponent('DenemeApp', () => DenemeApp);
    module.exports = DenemeApp;

i think that must be a better way

**Comment by brentvatne** [comment]
@kocyigityunus - have a look at [react-native-modal](https://github.com/brentvatne/react-native-modal) and let me know if that doesn't answer your question, I'll be happy to answer!

**Comment by kocyigityunus** [comment]
i allready looked at it.

when i tried to use it in or with <NavigatorIOS> compoenent. NavigatorIOS is being top of the my view with following style. this style is just like you use in modal.

    container: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    }

as you can see in the photo. Navigator bar on top.

![screen shot 2015-04-05 at 21 59 19](https://cloud.githubusercontent.com/assets/922418/6998143/18ef3e04-dbdf-11e4-91d4-72b6bc007ab3.png)

**Comment by brentvatne** [comment]
@vjeux - any insight into how we can absolute position a component to overlay `NavigatorIOS`?

**Comment by vjeux** [comment]
Yeah, this is unfortunate, internally we had to implement the modal component in objective-c, so that it can be on-top of NavigatorIOS and the status bar. cc @sahrens who built it

**Comment by brentvatne** [comment]
That makes sense, I'll have a go at fixing that. Thanks @vjeux

**Comment by brentvatne** [comment]
Having a bit of a hard time figuring out the right away to do this, any tips @sahrens?

**Comment by kocyigityunus** [comment]
maybe this can help : https://github.com/Kureev/react-native-navbar

**Comment by jordwalke** [comment]
We have tons of full screen modals with custom animations with the JS implemented navigator. (See the F8 app for an example). Would that work for you?

**Comment by brentvatne** [comment]
@jordwalke - that makes sense - I like the JS navigator personally, I was just thinking that it would be useful for others who choose to use `NavigatorIOS` for my `react-native-modal` library to just work well with it.

**Comment by Kureev** [comment]
@kocyigityunus it'll help, if you'll migrate from `NavigatorIOS` to basic `Navigator`. You'll be able to build your own view with navbar and position it however you want. Then, you'll just need to make an overlay and implement your modal (or use very nice [react-native-modal](https://github.com/brentvatne/react-native-modal) as has been mentioned before). Let me know if you'll have any issues with that.

**Comment by sahrens** [comment]
One thing you can do is to expose a native API to create a new UIWindow and render the modal content views into that. One way to do this is with a custom native modal component that creates the UIWindow in reactAddSubview and stuffs the view into their instead of as a subview of it's self like it would be default.

What happens if you put your react-native-modal component outside of (e.g. as a sibling to) the NavigatorIOS component?

**Comment by sahrens** [comment]
Ignore my last paragraph - I missed your example using the react-native-modal.

**Comment by brentvatne** [comment]
@sahrens - that's a neat idea re: overriding `reactAddSubview` to create a `UIWindow` - I'm going to give that a try

**Comment by fraserxu** [comment]
Would be great if @sahrens could share some code here!

**Comment by kocyigityunus** [comment]
i tried to have a es6 way to do that. but i think NavigatorIOS component is not keeping it's state. i am constructing it only once but result is the same. as you can see :


    'use strict';

    var React = require('react-native');
    var {
      AppRegistry,
      NavigatorIOS,
      StyleSheet,
      View,
    } = React;

    var FirstScreen = require('./FirstScreen');

    class DenemeApp extends React.Component{
      constructor(props){

        this.props = props;
        this.state = {
          openModal: (null: ?React.Component),
        }

        // only calling once
        console.log("trying to create own navigator!");

        this.props._ownNavigator = React.createElement( NavigatorIOS,
          {style:styles.container,
            initialRoute : {
              title: 'FirstScreen',
              component: FirstScreen,
              passProps: {
                onModalRequested: (modal) => {
                  console.log("on modal requested called!");
                  this.setState({ openModal: modal, });
                },
              }
            }
          }
        );

      }
      getInitialState() {
        // this method is not calling.
        //  this must be done in construtor
        console.log("get initial state called!");
        return { };
      }
      closeModal() {
        this.setState( { openModal : false, } );
      }
      render() {
        if (this.state.openModal) {
          var Modal = this.state.openModal;
          return (
            <Modal
              onModalExit={() => {
                console.log("will call openModal null!");
                this.setState({ openModal: null, });
              }}
            />
          );
        }
        // return the navigator object created on the constructor
        return this.props._ownNavigator;
      }
    }

    var styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: 'white',
      },
    });

    AppRegistry.registerComponent('DenemeApp', () => DenemeApp);
    module.exports = DenemeApp;

**Comment by brentvatne** [comment]
@sahrens - this worked, but when I render the subviews in the new window they stop responding to any click events, and cmd+r no longer refreshes, any idea?

**Comment by ide** [comment]
The window is probably affecting the responder chain. Is your modal window the key window?

**Comment by brentvatne** [comment]
@ide - I tried both with and without

```objc
    [_overlayWindow makeKeyAndVisible];
```

```objc
    _overlayWindow.userInteractionEnabled = YES;
    _overlayWindow.hidden = NO;
```

**Comment by brentvatne** [comment]
@ide - without being key, cmd+r works but presses won't.

**Comment by brentvatne** [comment]
https://gist.github.com/brentvatne/5115e83d02027869ca83

**Comment by sahrens** [comment]
Ah yes, you'll need to attach the RCTTouchHander to the modal...something like

```
[modalView addGestureRecognizer:[[RCTTouchHandler alloc] initWithBridge:_bridge]];
```

Sorry, I wish I had time to clean up what we have internally sooner, but it relies on some FB infra stuff :(

**Comment by brentvatne** [comment]
Thanks @sahrens :smile:

> Sorry, I wish I had time to clean up what we have internally sooner, but it relies on some FB infra stuff :(

No problem, this is an enjoyable learning exercise

**Comment by brentvatne** [comment]
@sahrens - so I have this mostly working, I just can't figure out how to properly dispose of the modal UIWindow and give touch control back to the main UIWindow. The only thing that I have found to work is `_mainWindow.windowLevel = UIWindowLevelStatusBar;` but that is undesirable of course because the main window's windowLevel should not need to change for this. [Example repo is here](https://github.com/brentvatne/NavigatorModalBug) and [component is here](https://github.com/brentvatne/NavigatorModalBug/blob/master/react-native-modal/RNModal.m)

**Comment by brentvatne** [comment]
@sahrens - Got this working, the problem was that the component is initialized twice by React - once as a base component without props, and immediately after that once more and the props are applied. The problem was that I was creating the `UIWindow` in the `init` function so the first one, for the base, would just stay around indefinitely.

@kocyigityunus - You can use `NavigatorIOS` with [react-native-modal](https://github.com/brentvatne/react-native-modal) now, just be sure to set the `forceToFront` prop to `true` on the modal so it will create it in a new `UIWindow`!

**Comment by brentvatne** [comment]
![demo-layered](https://cloud.githubusercontent.com/assets/90494/7059920/50a85132-de2d-11e4-97c7-48e440e128be.gif)

**Comment by jordwalke** [comment]
Awesome work!
Keep in mind that this approach will require reimplementing the same concept in Android, whereas the standard `Navigator` will not since the scenes are controlled in JS.

It's about tradeoffs, and the approach you've taken has benefits as well: I believe that if you embed a `ReactNative` container inside of a larger (non-`ReactNative`) app, your modal will still work well.

**Comment by kocyigityunus** [comment]
congs @brentvatne  great job.

**Comment by sahrens** [comment]
The original motivation was to work with NavigatorIOS, right?

**Comment by brentvatne** [comment]
@jordwalke - Agreed, definitely a matter of trade-offs here. Will definitely get the same thing working on Android when the time comes!

@sahrens - yup, but this could applicable to overlay any native component on `UIWindowLevelStatusBar`

@kocyigityunus - can we close this issue now?

**Comment by brentvatne** [comment]
Closing :smile:
