### ISSUE TITLE
Crash on touch: TypeError: Attempted to assign to readonly property in ResponderTouchHistoryStore.js

### ISSUE THREAD

**Issue by maxdjohnson** [facebook/react-native#6885]
We're seeing this mysterious crash in our production app. It happens seemingly at random, when the user drags in the app. I don't have a clean stack trace, but the error happens in the React codebase, here: https://github.com/facebook/react/blob/v0.14.7/src/renderers/shared/event/eventPlugins/ResponderTouchHistoryStore.js#L123
Looking at the code, I'm not sure how this could be happening - I suspect it could be a bug in JSC. Possibly related: https://bugs.webkit.org/show_bug.cgi?id=138038

Last seen in React Native 0.22, React 0.14.7, and iOS 9.3

**Comment by gre** [comment]
we have seen this too. using RN 0.22.2

**Comment by ide** [comment]
That linked JSC bug sounds like it was fixed in time for iOS 9 so I don't think that's it.

**Comment by drtangible** [comment]
We're seeing this as well.

**Comment by maxdjohnson** [comment]
Good catch @drtangible - going to close this out since it's believed to be fixed in RN 0.24
