### ISSUE TITLE
[Debugger] Chrome popping up on every reload (Already closed the debugging session)

### ISSUE THREAD

**Issue by sreejithr** [facebook/react-native#689]
More of an annoyance than a bug.

Picture this, I enter debugging pressing Cmd-D. Once I'm done with it, I close Dev Tools and Chrome. Now when I reload, I'm expecting the app to connect to my packager running in the terminal and leave Chrome alone. But instead, Chrome pops up on every reload.

Is this by design?

**Comment by vjeux** [comment]
If you press cmd+ctrl+z you can disable chrome debugging. Would be nice to improve the detection though if chrome dev tools are closed, to disable it automatically. cc @frantic

**Comment by iamdustan** [comment]
I’d be happy to explore this on #510.

**Comment by schickling** [comment]
Any updates on this. Would be nice if you could keep the debug session open but avoid popping up into foreground on each code change.
