### ISSUE TITLE
DrawerLayoutAndroid, unable to set opacity

### ISSUE THREAD

**Issue by holyxiaoxin** [facebook/react-native#6895]
I am having problems setting the opacity of `DrawerLayoutAndroid`. I'm currently on react-native `v0.23.1`.

```
On the left is android. On the right is IOS.
```
![image](https://cloud.githubusercontent.com/assets/5796213/14408694/c6534e02-ff31-11e5-9123-2042246cd4b9.png)

I've also tried creating a new project with just `DrawerLayoutAndroid` and some `View`s and `Text`s. However, I still have no luck in setting the transparency of the drawer.

**Comment by holyxiaoxin** [comment]
@christopherdro 
Realised that it's this single line of code here: https://github.com/facebook/react-native/blob/master/Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.android.js#L286

Can I send in a PR to remove hardcoding the background color of the navigation drawer?

**Comment by christopherdro** [comment]
@holyxiaoxin Sure you can!

You'll notice a template generate in the comments section when you create the PR. If you could take the time to fill that it out, it would help push the PR through.

Thanks again!

**Comment by grabbou** [comment]
Closing as fixed and Github didn't close, https://github.com/facebook/react-native/commit/7851572b405d22dd885c291de21d5b1a30d7c92c
