### ISSUE TITLE
Old cached app in the emulator instead of the current

### ISSUE THREAD

**Issue by akaiworld** [facebook/react-native#6900]
As this https://github.com/facebook/react-native/issues/4289 is closed seems i have to open a new one? 

Can not work at all. Every time I change & save a file - I get old results like I changed nothing. Working with ios simulator.

I get the cache reset only after i manually close processes and do
rm -rf $TMPDIR/react-*
react-native run-ios --reset-cache

It is really bad dev experience doing this after every change in the code.

Actually this is happening with modules. Sometimes it starts working well and every time a module changes the app in the simulator changes as well. But sometimes when the module is changed there is no any change in the app in the simulator!

**Comment by akaiworld** [comment]
I get the cache reset only after i manually close processes and do
rm -rf $TMPDIR/react-*
react-native run-ios --reset-cache

It is really bad dev experience doing this after every change in the code.

**Comment by christopherdro** [comment]
@akaiworld Did you every get this working?

**Comment by christopherdro** [comment]
@facebook-github-bot no-reply

**Comment by ericvicenti** [comment]
This should be working. Feel free to re-open an issue with specific directions on how to see the problem on new versions of react-native
