### ISSUE TITLE
set_borderRadius for only bottom-left and bottom-right corner of a View

### ISSUE THREAD

**Issue by upbit** [facebook/react-native#691]
I'm trying to implement the following effect by CAShapeLayer+UIBezierPath:
![react borderRadius](https://raw.githubusercontent.com/upbit/upbit.github.io/master/images/201504/react_bottom_borderRadius.png)

But the view/layer bounds.size is zero when `createAndRegisterViewWithReactTag:viewName:props:` -> `RCT_REMAP_VIEW_PROPERTY(borderRadius, layer.cornerRadius, CGFloat)`. Finally I hook RCTView's `reactBridgeDidFinishTransaction` to add border radius...

**Is there a better way** to set borderRadius for only bottom-left and bottom-right corner of a RCTView?

**Comment by loreasinclaire** [comment]
I am also curious how to assign individual corner border radiuses.. not all four corners. Thanks!

**Comment by brentvatne** [comment]
This is possible now with `borderBottomLeftRadius` etc :smile:

**Comment by upbit** [comment]
Great Works!
