### ISSUE TITLE
why the result same

### ISSUE THREAD

**Issue by youxikaifa** [facebook/react-native#6911]
i got same result when i revise the code,i  make sure the result different,so how can i resolve it?

**Comment by christopherdro** [comment]
@youxikaifa Not sure what your questions is here. Could you be more specific?

**Comment by youxikaifa** [comment]
i run the project on the android phone,when i add some component in this pro,then run again ,the ui not change.

**Comment by hknd** [comment]
@facebook-github-bot  stack-overflow

**Comment by jhack32** [comment]
Not sure if this answers your question but you can try typing adb shell input keyevent 82 and then Reload JS. @youxikaifa 

https://facebook.github.io/react-native/docs/running-on-device-android.html#running-on-device

**Comment by christopherdro** [comment]
@facebook-github-bot stack-overflow
