### ISSUE TITLE
ActionSheetIOS.showShareActionSheetWithOptions not show on Modal

### ISSUE THREAD

**Issue by someok** [facebook/react-native#6913]
Pic1 is normal View and ActionSheetIOS work fine.

Pic2 is Modal, ActionSheetIOS cannot show.

## pic1
![img_0023](https://cloud.githubusercontent.com/assets/1523082/14421633/4e4fae8a-0005-11e6-85f3-278be451e587.PNG)

## pic2
![img_0022](https://cloud.githubusercontent.com/assets/1523082/14421649/5ec8b158-0005-11e6-9bc6-a37c4f95128d.PNG)

**Comment by christopherdro** [comment]
@facebook-githb-bot bugfix
