### ISSUE TITLE
Android Studio 2.0 - Developer menu not available

### ISSUE THREAD

**Issue by LuckyLuky** [facebook/react-native#6919]
In the new release of Android Studio, the F2 shortcut for developer tools in the emulator (I'm using Windows 10) isn't working anymore.

**Comment by winkerVSbecks** [comment]
Apparently the shake gesture is not available in the updated version of the emulator (v2)

**Comment by chirag04** [comment]
you can do `cmd + m` on mac.

**Comment by winkerVSbecks** [comment]
That works for the iOS simulator on mac. Not on Android both on OS X and Windows.

**Comment by LuckyLuky** [comment]
@chirag04 You're right, it's `ctrl + m` on Windows, but the shortcut is working. Thanks.

**Comment by satya164** [comment]
Up for a PR to update the docs?

**Comment by LuckyLuky** [comment]
@satya164 I'm working on it, I've already sent PR for Android Setup page. Now I will look into Getting Started page.

**Comment by sangshuduo** [comment]
Isn't command+m for make current window minimal?
