### ISSUE TITLE
Android Camera preview is blurred

### ISSUE THREAD

**Issue by john1jan** [facebook/react-native#6930]
I am using https://github.com/ideacreation/react-native-barcodescanner native module for scanning barcode in my react application.

This module use zing library for barcode scanning. https://github.com/dm77/barcodescanner

In this module **ZBarScannerView** is used for displaying the camera preview and scanning the barcode.

We are creating a ReactBarcodeScannerView extending ZXingScannerView and creating a Native UI Component

But the Camera Preview is blurred with some patterns. But the same view works fine without any blur when it used on native side.

Is there any problem in react in rendering camera preview ?

Attaching the screen shot using **ZXingScannerView** in native side and the same for react side

**Native barcode scanning** ![screenshot_20160412-121755](https://cloud.githubusercontent.com/assets/4264813/14451973/d83e5de6-00a8-11e6-946d-cdb7290b07b8.png)

**React side barcode scanning using the same view** 
![screenshot_20160412-120915](https://cloud.githubusercontent.com/assets/4264813/14451995/f55c80f6-00a8-11e6-84f1-bac415cf3125.png)

**Comment by prateekbh** [comment]
Make sure the camera resolution is not disturbed.
ZXingScannerView expects the camera to take the full screen.
to avoid this we do a workaround with position absolute and overlapping elements

**Comment by john1jan** [comment]
@prateekbh thanks, It works in fullscreen. **Position absolute** did the trick. Thanks for the workaround

I have made the <BarcodeScanner/> component to occupy full screen, then overlapped my other components on top of it.

Now the scanning is perfect and there is no distortion.

**Comment by shuyu6** [comment]
Can I know how u made ur own `<BarcodeScanner/>` component? I meet the same problem and I cant find the solution

**Comment by prateekbh** [comment]
@shuyu6 lemme check if we can open source it in a different repo

**Comment by prateekbh** [comment]
@mohanrohith can help in this
