### ISSUE TITLE
PanResponder error with Android

### ISSUE THREAD

**Issue by Rice-M** [facebook/react-native#6935]
Hi, When I use 'PanResponder' with 'ListView' I meet some troubles. When gesture is completed, 'onPanResponderRelease' event don't trigger in Android. This is all right in iOS. What I want to do out like two or more views in 'ListView', when I scroll to the bottom of the first view the first view will scroll to the top automatic.

**Comment by cdmalcl** [comment]
me too!!
Wait solve this problem to look forward to a long time！！
ScrollView also so
only View can do that.
Using View to achieve ListView will bring more trouble.
I remember there was a version that could be done.
Or give onScroll more arguments, eg:touch position,touch distance.

**Comment by satya164** [comment]
Can you post a demo of what you're experiencing?

**Comment by my-love** [comment]
componentWillMount() {
     this.panResponder = PanResponder.create({
       onStartShouldSetPanResponder: (evt, gestureState) => true,
       onMoveShouldSetPanResponder: (evt, gestureState) => true,
       onPanResponderMove: this.handlePanResponderMove.bind(this),
       //onPanResponderEnd: this.handlePanResponderEnd.bind(this),
       onPanResponderRelease: this.handlePanResponderEnd.bind(this),
       onPanResponderTerminate: this.handlePanResponderEnd.bind(this)
       //onPanResponderStart: this.handlePanResponderStart.bind(this)
     });
  }
        < ListView
          {...this.panResponder.panHandlers}
          dataSource={this.state.dataSource}
          renderRow={this._renderRow.bind(this)}>
        </ ListView>

I add panResponder to the ListView,when my finger leave the screen, onPanResponderRelease or onPanResponderTerminate did not trigger either in Android. This is all right in iOS. ' onPanResponderEnd' event triggers in Android, but it triggers when my finger moves on the screen, not leave the screen

**Comment by BigPun86** [comment]
+1

**Comment by ericnakagawa** [comment]
Hi folks, are you folks still experiencing this issue?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
