### ISSUE TITLE
TextInput renders extra characters after `value` was resetted to null

### ISSUE THREAD

**Issue by chenxsan** [facebook/react-native#6936]
- React-native 0.23
- Tested on iOS 9.3 simulator.
- I'm on Mac OS X.

Sorry, I can't reproduce it on [rnplay](https://rnplay.org/apps/Fg-0fg).

I'm using redux to manage my store.

The initial state of the TextInput is set to `null`, that `Reset` button would reset the value to `null` by sending actions to redux store.

Then things got wired. As the gif below shows:

![react-native-textinput](https://cloud.githubusercontent.com/assets/1091472/14456136/f8279424-00d5-11e6-8f4f-f6ace1121387.gif)

Some extra characters are left there.

If I set the initial state of TextInput to `''`, and reset it to `''` too, then everything works as expected.

**Comment by alvaromb** [comment]
Same happens here. When set value to null, an extra character appears.

**Comment by dsibiski** [comment]
@chenxsan Thanks for reporting this, it definitely seems like a new bug since as you mentioned, you can't reproduce it on rnplay where the latest version of RN is 0.21. It must have been introduced in 0.22 or 0.23.

**Comment by grabbou** [comment]
Side note: https://github.com/facebook/react/issues/5013

**Comment by m3vaz** [comment]
@grabbou @nicklockwood @chenxsan
Given that this has been patched, should the discussion of changing the props of TextInput be reopened on a new issue?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
