### ISSUE TITLE
 undefined is not an object('evaluating RNGoogleSignin.BUTTON_SIZE_ICON')

### ISSUE THREAD

**Issue by DhruvSoni** [facebook/react-native#6938]
![screenshot_20160412-181517](https://cloud.githubusercontent.com/assets/16912403/14460331/940cf948-00da-11e6-86d3-f668e4507c5d.png)

code ---->

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  Image,
  View
} from 'react-native';

import {GoogleSignin, GoogleSigninButton} from 'react-native-google-signin'; <<<--- error at this line

**Comment by NewAndroidDev** [comment]
+1

**Comment by Jorianiiita** [comment]
i also hv the same problem

**Comment by ide** [comment]
Looks like a bug with RNGoogleSignin, not React Native itself.

**Comment by Jorianiiita** [comment]
there is no modules named as RNGoogleSignin in NativeModules of react-native..u can check it by logging NativeModule form react-native...

**Comment by Ignacio01** [comment]
Hello, I had the same problem and following these steps I was able to solve the error!
https://github.com/devfd/react-native-google-signin/blob/master/ios-guide.md

**Comment by fatinWasta** [comment]
Didn't helped. Going through same problem again and again.

**Comment by fatinWasta** [comment]
Finally, spending one week,
upgrading my react-native-google-signin from 0.8.1 to 0.11.0 resolved my problem.
hope this helps.

**Comment by samernady** [comment]
Any updates on this i am still facing the same problem
