### ISSUE TITLE
ListView Datasource update incorrect

### ISSUE THREAD

**Issue by akaiworld** [facebook/react-native#6939]
When I remove an item from the middle of the array and update the datasource I get an item removed, but not the needed one, but the last one.

**Comment by akaiworld** [comment]
http://stackoverflow.com/questions/35411797/react-native-listview-wrong-row-removed-when-deleting
this worked for me, but still it does not seem to be the way it should be.

**Comment by dsibiski** [comment]
@akaiworld Do you have any suggestions on how you think it should be?

**Comment by akaiworld** [comment]
For several hour I tryed to do it more straightforward as it is in the oficial documentation. Only later I found out that taking DataSource object out of the Class would make it work. 
I guess it should be marked in the documentation or the straightforward way should also be workable.

**Comment by dsibiski** [comment]
If you can submit a PR with some suggested changes for the documentation, that would be great! :smile:

**Comment by satya164** [comment]
@akaiworld

Taking the DataSource object out of the class isn't the correct solution.

I tried reproducing your issue on rnplay.org and after fixing the `onRowHasChanged` function, everything seems to work fine.

```js
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  ListView
} = React;

var SampleApp = React.createClass({
  

  getInitialState() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    var rows = ['row 1', 'row 2', 'row 3'];
    return {
      dataSource: ds.cloneWithRows(rows),
    };
  },

  _deleteRow() {
    var rows = ['row 1', 'row 3'];
    this.setState({dataSource: this.state.dataSource.cloneWithRows(rows)})
  },

  renderRow(rowData, sectionID, rowID) {
    return <TouchableOpacity onPress={this._deleteRow}
      style={{height: 60, flex: 1, borderBottomWidth: 1}}>
      <Text>{rowData}</Text>
    </TouchableOpacity>
  },

  render() {
    return (
      <ListView
        dataSource={this.state.dataSource}
        renderRow={this.renderRow}
      />
    );
  }

});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 28,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    fontSize: 19,
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

Let's re-open if it's still an issue.
