### ISSUE TITLE
Computed property name syntax fails when debugging in Chrome

### ISSUE THREAD

**Issue by HankMcCoy** [facebook/react-native#694]
I've created a [repo](https://github.com/HankMcCoy/ReactBrokenObjectTransform) demonstrating the problem with specific repro steps.

In short, using ES6 computed property names (e.g. `var foo = {[bar]: 123}` causes Chrome to throw a `SyntaxError: Unexpected token [` error when debugging. Confusingly, the same code works just fine when running in the simulator.

I'm happy to look into the problem, but it would be immensely helpful if someone with deeper knowledge of React Native's inner workings could at least point me in the right direction.

**Comment by vjeux** [comment]
When running in the simulator, you are using JavaScriptCore that supports computed properties natively.

When running in Chrome debugger, you are running stock Chrome (and v8) which doesn't support it.

We have many es6->es5 transforms that smooth out all those differences but computed properties is not one of them unfortunately.

**Comment by HankMcCoy** [comment]
That makes perfect sense. Thanks!

Is there anywhere in the documentation that lists which ES6/7 transformations React Native does? I'm guessing the [visitors](https://github.com/facebook/jstransform/tree/master/visitors) directory in the JSTransform repo is a complete list, albeit not a particularly user friendly one?

**Comment by jmorrell** [comment]
Oh wow, didn't realize any engine was supporting computed properties yet. Looks like Firefox does too. Sweet!

**Comment by kyle-ssg** [comment]
Does this mean that we can only reliably test react native whilst debugging chrome is disabled ?

Also, this sounds like it could be a cause for my two recent issues: 

https://github.com/facebook/react-native/issues/740
and
https://github.com/facebook/react-native/issues/741

**Comment by brentvatne** [comment]
The recent change to Babel should fix this!
