### ISSUE TITLE
Picker.Item

### ISSUE THREAD

**Issue by shibiaoz** [facebook/react-native#6940]
```
<Picker
                  selectedValue={this.state.language}
                  onValueChange={(lang) => this.setState({language: lang})}>
                    <Picker.Item label="Java" value="java" />
                    <Picker.Item label="JavaScript" value="js" />
                </Picker>
```
but error
errmsg: undefined is not an object(evaluating Picker.Item)

**Comment by mangogogos** [comment]
Can you show where you are importing/requiring Picker?

**Comment by shibiaoz** [comment]
var {
    View,
    Picker,
    TouchableHighlight,
    StyleSheet,
    Text
} = React;

**Comment by mangogogos** [comment]
And I assume you also have var React = require('react-native'); or import React from 'react-native'; as well? What react native version are you using?

**Comment by shibiaoz** [comment]
yes, i am sure require react-native
 "dependencies": {
    "react-native": "^0.12.0"
  }
all code in one component,
```
var React = require('react-native');

var {
    View,
    Picker,
    TouchableHighlight,
    StyleSheet,
    Text
} = React;
var styles = StyleSheet.create({
    buttonred: {
        color: '#00f',
        padding: 10,
        marginTop:20,
    }
});
class PickerComponent extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            language: 'java',
            services: ['a', 'b', 'c', 'd', 'e'],
        };
    }
    goBack() {
        this.props.navigator.pop();
    }
    render() {
        return (
            <View>
                <TouchableHighlight
                  onPress={this.goBack.bind(this)}
                  >
                    <Text style={styles.buttonred}>返回</Text>
                </TouchableHighlight>
                <Picker
                  selectedValue={this.state.language}
                  onValueChange={(lang) => this.setState({language: lang})}>
                    <Picker.Item label="Java" value="java" />
                    <Picker.Item label="JavaScript" value="js" />
                </Picker>
            </View>
        );
    }
}
module.exports = PickerComponent;

```

**Comment by dsibiski** [comment]
@shibiaoz What version of RN are you running? If you're on an older version, the cross-platform `Picker` may not have been around.

If you can't upgrade to the latest version quite yet, try changing your import to `PickerIOS` (of course, only if you aren't looking for Android support).

**Comment by shibiaoz** [comment]
@dsibiski,thank you ,i upgrade my rn to the lastest vesion, but run error,so i upgrade my react-native-cli,and then init a new project ,and copy file from old project to new project ,now i is ok

**Comment by dsibiski** [comment]
@shibiaoz Ok great!

**Comment by dsibiski** [comment]
@facebook-github-bot answered
