### ISSUE TITLE
Viewing console.logs from the safari view controller put up by react-native app.

### ISSUE THREAD

**Issue by pvenkatakrishnan** [facebook/react-native#6945]
On an ios simulator, I have a safari view controller that i put up, from my react-native views. How can i view the console.logs / errors from the page i load in my safari view controller via the react-native app?
I can only see the console.logs from the react-native app in the simulator logs...

Tried searching on stackoverflow. Only see information about logging from the react-native app.

Any information is appreciated.

Thanks.

Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [x] What's the **version** of React Native you're using?
- [x] Does this occur on iOS, Android or both?
- [x] Are you using Mac, Linux or Windows?

**Comment by pvenkatakrishnan** [comment]
* Using react-native 0.19
* testing on ios simulator
* testing on mac

**Comment by ide** [comment]
SFSafariViewController runs in a separate process I believe and might not provide a way to get the console logs from Obj-C.

This issue seems more related to the Apple APIs than React Native itself but if I'm mistaken feel free to reopen this issue.
