### ISSUE TITLE
Error: DefaultRenderer.getChildContext(): childContextTypes must be defined

### ISSUE THREAD

**Issue by bnns** [facebook/react-native#6947]
I am getting this error when running `react-native run-ios` on OSX with RN 0.23.1.

Running in Xcode seems to work.

![screen shot 2016-04-12 at 5 51 54 pm](https://cloud.githubusercontent.com/assets/1106502/14478028/98dcbfb0-00d7-11e6-8954-926c57965cb8.png)

**Comment by satya164** [comment]
Can you post a sample project to reproduce this issue?

**Comment by Olliepop** [comment]
@bnns See https://github.com/aksonov/react-native-router-flux/pull/518

**Comment by bnns** [comment]
This fixed it! Thanks!

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-7** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
