### ISSUE TITLE
[IOS 0.21.0] Not show static images when use bundle file in NSDocumentDirectory

### ISSUE THREAD

**Issue by HungTran92** [facebook/react-native#6953]
Hi everyone!

I push “main.jsbundle” to server. After that,I download and save the bundle like this:

NSURL *url = [NSURL URLWithString:_downloadUrlGet]; 
NSData *urlData = [NSData dataWithContentsOfURL:url];
NSString *filePath = [NSString stringWithFormat:@"%@/%@", [self getPathBundleTempFile],fileName];
[urlData writeToFile:filePath atomically:YES];

After that I set the jsCodeLocation to this filePath.
It works well but the images aren't show.

**Comment by bfwg** [comment]
+1

**Comment by satya164** [comment]
You also need to download the images into the same directory as the bundle, otherwise they won't show up. You can use something like `CodePush` which can do it for you.

Let's reopen if this is not the case.

**Comment by HungTran92** [comment]
thanks a lot!
