### ISSUE TITLE
[0.24.0-rc5][Android][NativeAnimatedModule]Native animated module is not available

### ISSUE THREAD

**Issue by ramilushev** [facebook/react-native#6958]
I am getting the following error in RN 0.24.0-rc5 - `Native animated module is not available`

`Animated.timing(
    this.state.anim, { duration: 200, toValue: 1, useNativeDriver: true }
).start();`

I am using it to update opacity only. 
Note that without `useNativeDrive: true` the animation works fine.

**Comment by ide** [comment]
`useNativeDriver` might not be supported -- just leave it off for now. Will be fixed in a release probably 2-8 weeks from now.

**Comment by ms88privat** [comment]
any news here? When does the NativeAnimatedModule arrive?

**Comment by nschurmann** [comment]
@ms88privat did you manage to enable this module?, i'm having issues enabling NativeAnimatedModule.

**Comment by ms88privat** [comment]
@nschurmann no, I didn't get it to work too. Keep me updated if you find a way, thanks!

**Comment by sibelius** [comment]
@nschurmann did u figure it out how to include nativeanimatedmodule on android?

**Comment by ramilushev** [comment]
@sibelius It is now included by default. Just add `useNativeDriver: true`.
