### ISSUE TITLE
[NavigationExperimental] BackAction for nested StackReducers

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#6963]
The outermost NavigationStackReducer will always handle a back action: https://github.com/facebook/react-native/blob/master/Libraries/NavigationExperimental/Reducer/NavigationStackReducer.js#L76

One possible solution would be to add a "key" to the back action and check for this key in the reducer.

Thoughts @ericvicenti?

**Comment by ericvicenti** [comment]
Thanks for raising this issue. I think the current behavior is a bug, and we always want to allow the inner reducer to handle a back action first. Can you submit a PR to re-arrange the reducer and fix this? Also cc @hedgerwang
