### ISSUE TITLE
[Android] ToolbarAndroid tablet padding too much

### ISSUE THREAD

**Issue by ssomnoremac** [facebook/react-native#6964]
On RN@master 

With `ToolbarAndroid` when you are using a tablet or a larger screen, the margin for the NavIcon is consistently too much or gravity is not set correctly. I've used vector icons and drawables both with the same result. Would prefer not to have to target each size screen with conditional styling.

![nexus7](https://cloud.githubusercontent.com/assets/3521359/14500690/091d3fd6-0171-11e6-9c2b-b6034e6c80fa.png)

**Comment by ssomnoremac** [comment]
From the Android docs on [Toolbar](http://developer.android.com/reference/android/widget/Toolbar.html) it appears that:

> 
Action buttons are vertically aligned within the Toolbar's minimum height, if set.

Yet it appears the [issue is closed](https://github.com/facebook/react-native/issues/1284) on setting min-height in React Native which, I'm not sure is enough to get this solved, but seems like heading in the right direction.

**Comment by lacker** [comment]
It seems like css-layout has been updated since this was an issue and from that other issue it seems like that was the main problem here. I'm going to close this issue under the theory that it is solved by that, but if it's still a problem feel free to reopen.
