### ISSUE TITLE
why not provide a method to Navigator push to the Native UIViewController？

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#6966]
hi，when I use react-native to develop my App,but I had a module which function is already finish by native code,I want to integrate with RN,but when I use the js based Navigator to push to it ,the UI can display,but can't take touch effect.
I implement The RCTView and RCTViewManager,
`@interface RCTConversationView : RCTView

@end`
`#import "RCTConversationView.h"

@implementation RCTConversationView
RCTWrapperViewController *_reactViewController;
RCConversationViewController *chatViewController ;
- (instancetype)initWithFrame:(CGRect)frame
{
  if ((self = [super initWithFrame:frame])) {
    chatViewController = [[RCConversationViewController alloc] initWithConversationType:ConversationType_PRIVATE targetId:@"targetIdYouWillChatIn"];
    chatViewController.conversationType = ConversationType_PRIVATE;
    chatViewController.targetId = @"targetIdYouWillChatIn";
    chatViewController.title = @"title here";
    [self addSubview:chatViewController.view];
    
  }
  return self;
}
- (void)layoutSubviews
{
  [super layoutSubviews];
  
  chatViewController.view.frame = self.bounds;
}

-(UIViewController *)reactViewController{
  return chatViewController;
}

`
can React-native provide a comfortable way to better compatible with the native UIViewController？

**Comment by christopherdro** [comment]
Hey @charlesluo2014! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
