### ISSUE TITLE
Image with resizeMode=contain blinks on rerender (Android)

### ISSUE THREAD

**Issue by MichaelDanielTom** [facebook/react-native#6971]
Hey guys,

I'm trying to change the image of a button based on if the button is selected or not. However if the image has resizeMode set to 'contain', the image always blinks before changing. Other resizeModes do not blink. The image sources are local, included with require.

Here's a barebones render method that should reproduce the issue:
```
render() {
    var source = this.props.isSelected ? require('./image1.png') : require('./image2.png')
    return (
        <TouchableNativeFeedback>
            <View>
                <Image style={{resizeMode: 'contain'}} source={source} />
            </View>
        </TouchableNativeFeedback>
    )
}
```

I'm using rn0.22.2 for Android, developing on a Mac. The issue occurs on both device and simulator, with debug mode both on and off.

**Comment by christopherdro** [comment]
@MichaelDanielTom Have you taken a look at this commit? https://github.com/facebook/react-native/commit/2070efa019f6b5dfb38500d41e4d7e263f59f0d2

It appears this landed in 0.24-rc5. Can you try giving that a shot report back? Thanks

**Comment by MichaelDanielTom** [comment]
That definitely helped with upscaling the image, but it doesn't fix the blinking problem, I did upgrade, and it's still there :/

**Comment by max-mykhailenko** [comment]
I have blinking on iOS with and without `resizeMode=contain`. Can you advise how to resolve problem?

![blinking](https://cloud.githubusercontent.com/assets/1213198/16874850/775ceea2-4aa4-11e6-862f-97c00174baab.gif)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-with-resizemodecontain-blinks-on-rerender-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by alikemalcivelek** [comment]
I have same issue. How can I resolve?

**Comment by devboy** [comment]
+1

**Comment by geekgugi** [comment]
Any update on this, I am using react-native 0.43.4, issue still persists. Image with `resizeMode='contain'` flickers upon re-render in android.

**Comment by paranat9221** [comment]
@max-mykhailenko I have some issues like this, can someone already fixed this??

**Comment by paranat9221** [comment]
I have problem like @max-mykhailenko and now I can fixed this by using **defaultSource** instead of **source**

**Comment by icazevedo** [comment]
I have the same problem, it only works when I set the height and width manually and directly. RN@0.51.1 on Android
