### ISSUE TITLE
Deploy on iphone error

### ISSUE THREAD

**Issue by bfwg** [facebook/react-native#6972]
After I deploy my app on the phone I see this error and all my images won't display.
<img width="1026" alt="screen shot 2016-04-14 at 1 54 50 am" src="https://cloud.githubusercontent.com/assets/12819525/14522582/14447262-01e4-11e6-9726-57f112f4c586.png">

Node 4.2.1
React Native 0.17.0 
on iOS
I'm using Mac

**Comment by dsibiski** [comment]
The error that you are showing here is actually a warning, so this might not be the culprit. It does say though that you are setting `shadowOffset` on an `Image` which is not a style property that `Image` has.

I'm not sure if that would make your images not appear though. Perhaps you can look a little further down the console to see if there is some other error reporting. Or you could try and fix the warning and see if that has something to do with it.

**Comment by bfwg** [comment]
I got raid of the warnings but the image still won't show up. The most weird thing is it will show up if I run on the Simulator and there's no error or warning on the console.

**Comment by cpunion** [comment]
`shadowOffset` of Image isn't support in `0.17` (see https://github.com/facebook/react-native/blob/0.17-stable/Libraries/Image/ImageStylePropTypes.js), can you upgrade by `npm install --save react-native@0.23.1` and try again?

**Comment by bfwg** [comment]
Hi, I removed `shadowOffset` but still images are down.

**Comment by satya164** [comment]
We don't really support old React Native versions. Can you update to the latest version and see if the issues are still there?

**Comment by bfwg** [comment]
It was fixed after an update, thx!
