### ISSUE TITLE
Document port change command

### ISSUE THREAD

**Issue by ShashankaNataraj** [facebook/react-native#6973]
Found this after a couple hours of struggling:

`react-native start --port <port_number>`

Why is this not documented [here](https://facebook.github.io/react-native/docs/running-on-device-android.html)? When `adb reverse` can be documented here, I believe this command needs to be too!

**Comment by dsibiski** [comment]
If you'd like to submit a PR adjusting the docs that would be greatly appreciated! :smile:

**Comment by mangogogos** [comment]
Omg this is a thing?!? What version was this added in?

**Comment by grabbou** [comment]
I don't think it really makes sense for that to be in Android guide (in fact it applies to both and Simulator as well). However there's no documentation for react-native commands in one place, maybe we should add such section entirely & add links in all places?

I could submit a proposal if that makes sense to anyone.

**Comment by hedgerh** [comment]
@grabbou I'm looking for a first task and can lend a hand.  I'm compiling the flags for each command now.

**Comment by hedgerh** [comment]
Along with adding to the docs, why not add a `help` command to the CLI to see flags and more detailed usage information about a command?  Usage: `react-native help [command]`.

I can take that on if it seems like a good idea.

Also, pulled all of the arguments for each command from the source:  https://gist.github.com/hedgerh/0178fe3ace33b1161949491fd0e5b649

**Comment by grabbou** [comment]
I would say it could be `--help` and `[command] --help` if that's doable.

Gist looks good - if we can somehow get these from each command and build an interface on top of that, I think it would be really great!

**Comment by hedgerh** [comment]
How about showing it on both `help` and `--help`?  Also, when trying to figure out how to use a command, I feel like I would naturally try `--help [command]` or `help [command]`.  What do you think?  I'm in favor of implementing all of our syntaxes, if that'd be okay.

> if we can somehow get these from each command dynamically (so that it works in the future) and build an interface on top of that, I think it would be really great!

had the same thought, and it should be no problem :)

**Comment by grabbou** [comment]
> How about showing it on both help and --help?

I have no opinion on that to be fair, I'd say let's wait for others. I think the former approach is slightly more `standardised` since that's what FB follows in e.g. `flowtype`

**Comment by hedgerh** [comment]
Any idea how I can go about running the `local-cli`/`react-native-cli` in a local environment?

**Comment by grabbou** [comment]
Good question. I think you can just:
1) clone the project into `myTestApp/node_modules/react-native` and just use it normally
2) https://github.com/facebook/react-native/tree/master/react-native-cli#running-cli-with-local-modifications
3) https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L80-L88

**Comment by hedgerh** [comment]
I made a first pass at this.  The following syntaxes work:

```
help [command]
--help [command]
[command] --help
```

I still need to get the output to display in a nice format, and I want to do some cleanup on some of the descriptions.  Will get back at it tomorrow.

I opened a PR on my fork for previewing:  https://github.com/hedgerh/react-native/pull/1

**Comment by ShashankaNataraj** [comment]
@hedgerh looks good!

**Comment by hedgerh** [comment]
Hey @ShashankaNataraj and @grabbou, I implemented the pretty formatting for the help printout.  I'm not sure what to put for the test plan when I open the PR, or if i need to write tests and how.  I will read up on it the next time I get a chance, but it would help move things along if someone could give me a little direction.

**Comment by janicduplessis** [comment]
@hedgerh Just explain briefly how you tested it and show images of the input / output.

**Comment by grabbou** [comment]
I think that's enough. You can also record a small video with QuickTime (if you are on Mac) to show all the possible use-cases for that command :)

**Comment by ShashankaNataraj** [comment]
Any more updates on this?

**Comment by hedgerh** [comment]
@ShashankaNataraj: The `react-native` CLI now has a `--help` command that can be used to show the different options for each command.

Usage: `react-native start --help`

To whom it may concern:  This issue can now be closed!e
