### ISSUE TITLE
[TextInput] Cursor not in correct place on multiline inputs

### ISSUE THREAD

**Issue by CaoLiang1991** [facebook/react-native#6994]
In Android,when multiline = true，the cursor is not in the first place, it is in the longitudinal habitat.

**Comment by dsibiski** [comment]
@CaoLiang1991 Can you provide a code snippet, screenshot or demo on http://rnplay.org of what you have found? That would be greatly appreciated. :smile:

**Comment by CaoLiang1991** [comment]
@dsibiski  
![23ad8c4de1d6f22351d433215e73020f](https://cloud.githubusercontent.com/assets/16915325/14591772/740e6410-0549-11e6-9fb1-b980d5ce9a4d.jpg)



     <View style={styles.viewStyle}>
          <TextInput style={styles.textInput} underlineColorAndroid = "transparent"
                     onChangeText = {(text) => this.setState({reasonText: text})}
                     placeholder = "请输入原因"
                     multiline = {true}
            />
        </View>

  viewStyle: {
    marginTop: 10,
    marginLeft: 20,
    width: React.Dimensions.get('window').width - 40,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1/React.PixelRatio.get(),
    borderLeftWidth: 1/React.PixelRatio.get(),
    borderRightWidth: 1/React.PixelRatio.get(),
    borderTopWidth: 4/React.PixelRatio.get(),
    borderColor: '#e5e5e5'
  },
  textInput: {
    height:150,
    fontSize: 14,
    color: '#666666',
    paddingLeft: 3
  },

**Comment by ashleydw** [comment]
I'm pretty sure you need `textAlignVertical`

http://facebook.github.io/react-native/docs/text.html#style

**Comment by charpeni** [comment]
@CaoLiang1991 does `textAlignVertical` fixed this issue?

**Comment by ajohn104** [comment]
@charpeni I can't speak for @ashleydw, but it worked perfectly for me. I had the exact same problem and I no longer do.

**Comment by charpeni** [comment]
@ajohn104 Thank you for your feedback, I'll close this issue as @CaoLiang1991 didn't reply.

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-1** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.

**Comment by poberwong** [comment]
Thanks, it works for me as well
