### ISSUE TITLE
How a Image component showing by a absolute local path

### ISSUE THREAD

**Issue by jaynsw** [facebook/react-native#6998]
I developed a customized image component to download the online image and saved to a local file. I can not find a way to show this local file by Image component. I am sure these file downloaded successfully, because I can open them. I have tried the following ways:

#1)
`<Image
							source={{isStatic:true, uri:'file:///Users/jay/Library/Developer/CoreSimulator/Devices/00520C5F-1307-427E-AA55-9E1E020B2EFB/data/Containers/Data/Application/522D5404-A2EF-4117-A768-CF63A6A3EE8F/Library/Caches/6ea32f8825c207ec582ad684ac6a3494'}}
							style={imageStyle} />`
#2)
`<Image
							source={{isStatic:true, uri:'/Users/jay/Library/Developer/CoreSimulator/Devices/00520C5F-1307-427E-AA55-9E1E020B2EFB/data/Containers/Data/Application/522D5404-A2EF-4117-A768-CF63A6A3EE8F/Library/Caches/6ea32f8825c207ec582ad684ac6a3494'}}
							style={imageStyle} />`

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by jaynsw** [comment]
My example is from stackoverflow. I also read a github project named react
native image cache. None of them work.
I Think this should be put in official document if there is a way

**Comment by jaynsw** [comment]
I don't believe stackoverflow is the best place for this question because
this looks like a new feature being requested or a missing document for a
popular feature. Anyway if you want to be peaceful just neglect my point.

**Comment by charpeni** [comment]
In fact, i'm totally agree with you and i'm wondering the same question as you.

However, as mentioned in the [issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) this repo uses GitHub for bugs and StackOverflow for usage question. Feature requests can be post on [Product Pains](Product Pains).

Please feel free to ask it on StackOverflow and post the link in this issue. After that with a good answer we'll be able to update the documentation.

**Comment by jaynsw** [comment]
The following image url is from the cameraroll api, it works. I only tested this on IOS
example:
"assets-library://asset/asset.JPG?id=8E0344AD-41C4-45C4-9E0F-293BC421F078&ext=JPG"

**Comment by salmankhann** [comment]
@jaynsw did you manage to figure out how to do this ?

**Comment by jaynsw** [comment]
The url format should be same as other iOS and Android App. I suggest you
can setup a break point in cameraroll example of UIExplorer to look into it.
Jay
