### ISSUE TITLE
Flex layout -- missing stretch.

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#70]
Many HTML5 devs have gotten used to the flexibility of the modern CSS3 Flexbox model : http://css-tricks.com/snippets/css/a-guide-to-flexbox/

It seems like the flex layout is started, but not quite complete. Are you guys planning on implementing stretch?

**Comment by coderdave** [comment]
@jaygarcia Do you mind sharing the final code to get this layout to work? Thanks.

**Comment by jaygarcia** [comment]
@coderdave do you mean the application itself?

**Comment by coderdave** [comment]
@jaygarcia No, mainly just the style code... and maybe the basic components needed that represent the layout.
