### ISSUE TITLE
[JS: Testing] require('react-native') and jest test fails

### ISSUE THREAD

**Issue by rogergl** [facebook/react-native#700]
I have the following simple Module

```javascript
/**
 * @providesModule DropBox
 * @flow
 */
'use strict';

var React = require('react-native');
var {
   NativeModules,
    } = React;

var _ = require('underscore')._;

class DropBox {

    constructor() {
        this.nativeModule = NativeModule.DropBox;
    }

    loadFiles() {
        return new Promise((resolve, reject) => {
            this.nativeModule.load((error, names, contents) => {
                if (error) {
                    reject(error);
                } else {
                    var parsedContent = contents.map((c) => {
                        return JSON.parse(c);
                    });
                    resolve(_.zip(names, parsedContent));
                }
            });
        })
    }
}

module.exports = DropBox;
```
and the following test:

```javascript
jest.dontMock('../js/model/DropBox');

describe('loadFiles', function() {
 it('adds 1 + 2 to equal 3', function() {
   var DropBox = require('../js/model/DropBox');
   expect(1 + 21).toBe(3);
 });

});
```
I know that the test is nonsense, but I just want to make sure that my setup works. Running npm test gives:
  - TypeError: /Users/roger/Documents/AwesomeProject/js/model/DropBox.js: /Users/roger/Documents/AwesomeProject/node_modules/react-native/Libraries/react-native/react-native.js: /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/browser/ui/React.js: /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/modern/class/ReactComponent.js: /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/core/ReactUpdateQueue.js: /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/core/ReactUpdates.js: undefined is not a function
        at /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/core/ReactUpdates.js:26:39
        at /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/core/ReactUpdateQueue.js:18:20
        at /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/modern/class/ReactComponent.js:14:24
        at /Users/roger/Documents/AwesomeProject/node_modules/react-tools/src/browser/ui/React.js:18:22
        at /Users/roger/Documents/AwesomeProject/node_modules/react-native/Libraries/react-native/react-native.js:20:47

**Comment by StevenLangbroek** [comment]
Related StackOverflow question with some more research: [How to use Jest with React Native](http://stackoverflow.com/questions/29730415/how-to-use-jest-with-react-native)

**Comment by amasad** [comment]
The main reason for this issue is that we currently ship React in source form (`react-tools`) inside `react-native`. That means that it's written in ES6 and it depends on globals like `__DEV__`, which your jest setup should support that. We have plans to start shipping react from npm, (I think with React v0.14). @zpao can you confirm this?

In the mean time here is what you can do: adapt the [`jestSupport` directory](https://github.com/facebook/react-native/tree/master/jestSupport) and the jest config in the [package.json](https://github.com/facebook/react-native/blob/master/package.json#L9-L22) to be used with your project.

**Comment by naoufal** [comment]
I'm actually still getting errors after using the `jestSupport`/`package.json` setup.  But it seems to be because I'm requiring a React component in my jest test.

I haven't seen any of the tests in this repo do that yet, so I'm assuming that isn't supported yet.  

@amasad can you confirm?

**Comment by rogergl** [comment]
@naoufal 

You have to mock react-native. The following example works:
```javascript
jest.setMock('react-native', {
	NativeModules: {}
});
jest.dontMock('../js/model/DropBox');
jest.dontMock('mori');

var mori = require('mori')

describe('loadFiles', function() {

	pit('Spec 1', function() {

   	var DropBox = require('../js/model/DropBox');
   	var dropBox = new DropBox({
   		load: function(callback) {
      		callback(false, 
				["file1"], 
				['{"value":1}'])}
    	});

   return dropBox.loadFiles().then(
		function(stuff) {
      		var result = mori.toJs(stuff);
      		expect(result.length).toBe(1);
  		});
	});
});
```

**Comment by brentvatne** [comment]
I think we need a section in the docs about how to test your React Native components

**Comment by naoufal** [comment]
@brentvatne I'd be glad to help if you guys think the approach here is satisfactory. naoufal/react-native-progress-hud#1

**Comment by brentvatne** [comment]
@naoufal - that would be great! can you write up a draft for that and submit a PR? I'll review and augment as necessary

**Comment by naoufal** [comment]
Sure — I'll try and submit a PR tomorrow.

**Comment by naoufal** [comment]
@brentvatne PR submitted #1477.  Can you review/leave feedback?

**Comment by Pajn** [comment]
I'm getting problems with react-natives special requires 
```
Error: /home/rasmus/Development/test/app/react/app/components/__tests__/button-test.tsx: /home/rasmus/Development/test/app/react/app/components/button.ios.tsx: /home/rasmus/Development/test/app/react/node_modules/react-native/Libraries/react-native/react-native.js: Cannot find module 'React' from '/home/rasmus/Development/test/app/react/node_modules/react-native/Libraries/react-native'
```

**Comment by vitalets** [comment]
Does anybody managed to get auto mocked `react-native` ?
I'm still getting error when try to `import React from 'react-native` in jest..

**Comment by brentvatne** [comment]
cc @cpojer

**Comment by taypo** [comment]
Any update on this issue? I'm looking for a straight forward way of testing components. Cheers..

**Comment by StevenLangbroek** [comment]
@taypo see this article: https://blog.formidable.com/unit-testing-react-native-with-mocha-and-enzyme-51518f13ba73

**Comment by cpojer** [comment]
I'm currently polishing up the release for 0.9.0 which should improve the babel support in Jest and will fix performance. The next step will be to improve mocking of react-native by *a lot*.

**Comment by cpojer** [comment]
Thank you for your patience. We launched Jest 14.0 with experimental react-native support:

* [Blog Post](http://facebook.github.io/jest/blog/2016/07/27/jest-14.html)
* [React-Native Tutorial](http://facebook.github.io/jest/docs/tutorial-react-native.html)

Please feel free to create new issues after trying out the new integration if any issues remain.
