### ISSUE TITLE
Custom fonts don't apply to UTF-8 languages

### ISSUE THREAD

**Issue by AdamGorkoz** [facebook/react-native#7007]
Hi , 

I've been to use custom fonts (roboto) in my component and it looks like the fonts do not apply in this language (Hebrew) its just defaults to whatever the default is...

![image](https://cloud.githubusercontent.com/assets/10440278/14576015/6d1c0734-036e-11e6-8e6f-6eede3adfda9.png)

You can see the difference in the English written name and Hebrew one.

I am currently working with React Native Android version 0.22.2 on windows , i do not know if the issue also exists in IOS.

**Comment by ide** [comment]
Does Roboto include glyphs for Hebrew characters?

**Comment by AdamGorkoz** [comment]
@ide  You are right they dont have support for hebrew, closing.

**Comment by AdamGorkoz** [comment]
@ide You are right they dont have support for hebrew, closing.
