### ISSUE TITLE
react-native-cli is not in the npm registry ???

### ISSUE THREAD

**Issue by kevwil** [facebook/react-native#701]
I tried following the Quick Start guide on [the react-native website](http://facebook.github.io/react-native/docs/getting-started.html#content), but I could only get as far as `npm install -g react-native-cli` where I got this error:
```
npm ERR! 404 'react-native-cli' is not in the npm registry.
```
Not sure if the website instructions are wrong or there's a problem with the react-native-cli package in npm, but I'm unable to move forward.

**Comment by vjeux** [comment]
This is super weird, it is there: https://www.npmjs.com/package/react-native-cli

Maybe you are using a custom version of npm (entreprise maybe?)

**Comment by vjeux** [comment]
In the meantime you can git clone the react-native repo, npm install and modify any example in the Examples/ folder

**Comment by kevwil** [comment]
Ah, yes, those sneaky IT bastards got me again. Corporate registry in use & out of date, easily worked-around. :)
