### ISSUE TITLE
[TextInput] rendered incorrect on iOS 

### ISSUE THREAD

**Issue by lavystord** [facebook/react-native#7019]
I found there are something wrong with Component TextInput rendering on iOS and Android.
TextInput renders different on iOS and Android  when it works with flex.
The code in render() method is 
` return (`
        `<View style={{height:64,flexDirection: 'row',marginTop:100,borderWidth:2,borderColor:'red'}}>`
            `  <View style={{flex:1}}>`
               `     <TextInput`
                    `    value="Where am I"`
                `  >`
                         `  </TextInput>`
            `</View>`
            `<View style={{flex:1}}>`
                `<View style={{height: 60, backgroundColor: '#333333'}} />`
            `</View>`
        `</View>`
    `);`
The View on iOS is:
![ios](https://cloud.githubusercontent.com/assets/16117095/14585815/83c9331e-04b6-11e6-869a-251b496ec407.jpg)
it didn't render value correct.
The view on Android is : 
![android](https://cloud.githubusercontent.com/assets/16117095/14585827/b27f21f0-04b6-11e6-85d1-a3d0ed4dfb6d.png)
And when I add flex style (  `   style={{flex:0.5}}`)to TextInput ,the view on iOS works right.
` return (`
      `  <View style={{height:64,flexDirection: 'row',marginTop:100,borderWidth:2,borderColor:'red'}}>`
          `  <View style={{flex:1}}>`
             `   <TextInput`
                `   style={{flex:0.5}}`
                  `  value="Where am I">`
             `   </TextInput>`
           ` </View>`
           ` <View style={{flex:1}}>`
             `   <View style={{height: 60, backgroundColor: '#333333'}} />`
            `</View>`
       ` </View>`
   ` );`
The view rendered as expected:
![ios2](https://cloud.githubusercontent.com/assets/16117095/14585923/eac9fc6c-04b9-11e6-8493-51353091393f.jpg)

I want to know what reason results in this issue.And my React Native version is 0.23.1,iOS version is 9.3.1 .

**Comment by christopherdro** [comment]
Hey @lavystord! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
