### ISSUE TITLE
Enabling Watchman on Windows causes JS errors

### ISSUE THREAD

**Issue by dimitrovskif** [facebook/react-native#7022]
Running React Native 0.23.1 (with CLI 0.2.0) on Windows 7 works and the phone **successfully** loads the JS bundle: (note: no watchman installed)

``` bash
[5:51:15 PM] <END>   Crawling File System (111063ms)
[5:51:15 PM] <START> Building in-memory fs for JavaScript
[5:51:16 PM] <END>   Building in-memory fs for JavaScript (689ms)
[5:51:16 PM] <START> Building in-memory fs for Assets
[5:51:16 PM] <END>   Building in-memory fs for Assets (520ms)
[5:51:16 PM] <START> Building Haste Map
[5:51:16 PM] <START> Building (deprecated) Asset Map
[5:51:17 PM] <END>   Building (deprecated) Asset Map (138ms)
[5:51:17 PM] <END>   Building Haste Map (630ms)
[5:51:17 PM] <END>   Building Dependency Graph (112912ms)
transformed 522/522 (100%)
[5:51:36 PM] <END>   find dependencies (111802ms)
[5:51:41 PM] <END>   request:/index.android.bundle?platform=android&dev=true&hot
=false&minify=false (116804ms)
```

![untitled](https://cloud.githubusercontent.com/assets/8115972/14588353/c2dbabe8-04c7-11e6-92f5-34ad887ca13e.png)

After installing watchman (alpha for Windows 7 x64), the process is faster a few orders of magnitude:

``` bash
[5:53:54 PM] <END>   Crawling File System (324ms)
[5:53:54 PM] <START> Building in-memory fs for JavaScript
[5:53:54 PM] <END>   Building in-memory fs for JavaScript (0ms)
[5:53:54 PM] <START> Building in-memory fs for Assets
[5:53:54 PM] <END>   Building in-memory fs for Assets (0ms)
[5:53:54 PM] <START> Building Haste Map
[5:53:54 PM] <START> Building (deprecated) Asset Map
[5:53:54 PM] <END>   Building (deprecated) Asset Map (1ms)
[5:53:54 PM] <END>   Building Haste Map (2ms)
[5:53:54 PM] <END>   Building Dependency Graph (333ms)
```

However, now the packager server returns an error:

``` json
{"message":"Cannot find entry file index.android.js in any of the roots: [\"C:\\\\Users\\\\Filip\\\\react\\\\demo\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
```

Deleting the index file and pasting it again randomly fixes the issue. However, the Android app now throws an error:

``` bash
ReferenceError: Can't find variable: __fbBatchedBridge(<unknown file>:1)
```

You'd think that it is similar to #4881 and #4952 and the issue is the packer not running, but it actually is and the device can access it (correct ip:port in settings, tcp communication happens):

![untitled](https://cloud.githubusercontent.com/assets/8115972/14588354/db20c760-04c7-11e6-9a18-2144d3694a1e.png)

``` bash
[5:58:09 PM] <END>   request:/index.android.bundle?platform=android&dev=true&hot
=false&minify=false (1578ms)
```

In addition the request returns valid babelified code that resembles the `index.android.js` source code (both when requested from the computer and the phone browser):

``` js
(function(global) {global.
__DEV__=true;

global.__BUNDLE_START_TIME__=Date.now();
})(typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : this);
(function(global) {var 
modules=Object.create(null);
var inGuard=false;

function define(id,factory){
modules[id]={
factory:factory,
module:{exports:{}},
isInitialized:false,
hasError:false};


if(__DEV__){
babelHelpers.extends(modules[id].module,{
hot:{

...........
```

Note: There is difference in source code size:
- GET index.android.bundle?minify=false without watchman: 250KB
- GET index.android.bundle?minify=false with watchman: 24KB

I am suspecting that the watchman ignores dependencies and generates a bundle which does not contain all the required code (including some dep `__fbBatchedBridge`)

**Comment by janicduplessis** [comment]
I've had success using watchman alpha on windows, not sure exactly what causes this but like you said the package is way too small.

Maybe you can try resetting everything with
```
rm -rf node_modules
watchman watch-del-all
npm install
npm start -- --reset-cache
```

**Comment by dimitrovskif** [comment]
Does not help. My temporary solution is to run the packager in a Linux VM while the android build happens in Windows itself. And I guess the docs should suggest that too (considering the buggy performance of RN on Windows)

**Comment by DylanMLG** [comment]
I get exactly the same errors. Haven't been able to figure it out yet.

**Comment by dimitrovskif** [comment]
It's still an issue.

**Comment by senthilsivanath** [comment]
Same issue !

With Postman getting this error

{"message":"Cannot find entry file index.android.js in any of the roots: [\"D:\\\\Instore\\\\react-native\\\\SampleProject\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}

Have tried all possible workarounds
1. Like clearing temp
2. --reset-cache
3. npm-install

Without watchman packager takes nearly 5 mins. App works.

**Comment by sunnylqm** [comment]
@dimitrovskif I really appreciate your work! And I mentioned this post on watchman repo, the man in charge said they need a separate issue there and detailed information.  https://github.com/facebook/watchman/issues/19#issuecomment-242893611 So can you post it there? Thank you so much!

**Comment by AleCaste** [comment]
I am experiencing the same issue on a Windows 7-64 machine.
Without watchman enabled, the packager takes more than 10 minutes.
With watchman enabled, only 2 seconds!!!
So there is definitely something wrong.
The watchman build I am using is:
https://ci.appveyor.com/api/buildjobs/kravw77nw7fqhvio/artifacts/watchman.zip

**Comment by MichelDiz** [comment]
I'm using the "The latest alpha build is available here:
http://bit.ly/watchmanwinalpha" from mitchellh. And OMG the build was taking like 10 min. With the Watchaman.exe tave 50s !!!! Has to be in the same folder/path

**Comment by chroufa1** [comment]
i am having this problem with react native poject ``
 │  Running packager on port 8081.                                            │

 │                                                                            │

 │  Keep this packager running while developing on any JS projects. Feel      │

 │  free to close this tab and run your own packager instance if you          │

 │  prefer.                                                                   │

 │                                                                            │

 │  https://github.com/facebook/react-native                                  │

 │                                                                            │

 └────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   C:\Users\asus\Desktop\AwesomeProject

Loading dependency graph...
React packager ready.

Loading dependency graph, done.
Bundling `index.android.js`  100.0% (404/404), done.
SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at process._tickCallback (internal/process/next_tick.js:109:7)
{ Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at Socket._writeGeneric (net.js:724:26)
    at Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at Socket.Writable.write (_stream_writable.js:241:11)
    at Socket.write (net.js:670:40)
    at Socket.Writable.end (_stream_writable.js:475:10)
    at Socket.end (net.js:440:31)
    at Promise.resolve.then.then.then.catch.then.message (C:\Users\asus\Desktop\
AwesomeProject\node_modules\react-native\packager\src\Server\symbolicate\worker.
js:35:33) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

any solution please :)

**Comment by chroufa1** [comment]
i am using windows 7 64bits and i i do not have not installed watchmen

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/enabling-watchman-on-windows-causes-js-errors
