### ISSUE TITLE
[Packager] Add an option for blacklisting paths from the packager CLI

### ISSUE THREAD

**Issue by mbrgm** [facebook/react-native#703]
I'm using an Xcode build phase to invoke curl and download the bundle to my working directory. Once this is done, packager will add the `.jsbundle` file to the bundle, so when I download it the next time, the content is duplicated. When packager tries to include the duplicated bundle file, it fails with `TransformError: Unexpected end of input`.

My proposal is to add an `--ignore <path>` option to packager. The argument would then be added to packager's internal blacklist. If you consider this a feasible option, I would implement it.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chirag04** [comment]
@mbrgm Is this still a problem for you?

**Comment by mbrgm** [comment]
@chirag04 No, no longer. It seems like 0.15.0 added a run script phase, which creates the `.jsbundle`. Thank you!

**Comment by chirag04** [comment]
:+1:
