### ISSUE TITLE
SyntaxError: Invalid character: '#'

### ISSUE THREAD

**Issue by cayrodmed1** [facebook/react-native#7034]
I'm getting a Syntax error while trying to run a simple application. I'm trying to use the `Netbeast API` (https://github.com/netbeast/api) in my code, but I get the syntax error in the line I import netbeast
`var beast = require('netbeast')`
 
This is the error that is thrown:
![captura de pantalla 2016-04-18 a las 15 55 00](https://cloud.githubusercontent.com/assets/16781072/14606538/068a2322-057e-11e6-8f40-e69cb4a1710a.png)

It happens in iOS and Android, and I'm using react-native 0.22 in Mac.

I think it is because react-native does not support yet one (or more) of the packages used by netbeast, but I don't know which is causing the error.

Any idea about this?

Thank you.

**Comment by rreusser** [comment]
I don't know the internal difference, but my first approach is always to try, e.g. `import beast from 'netbeast'` instead of `require`. Just a shot in the dark.

**Comment by grabbou** [comment]
This is caused by the following line https://github.com/mqttjs/MQTT.js/blob/master/mqtt.js#L1. Since mqtt is both executable and file we can import and e.g. call `connect` on it, we should be able to support it by simply ignoring it.

Imo looks like a good first task - @cayrodmed1 would you like to check that out further?

**Comment by ide** [comment]
Node strips the hashbang:

```
// Remove shebang                                                              
  var contLen = content.length;
  if (contLen >= 2) {
    if (content.charCodeAt(0) === 35/*#*/ &&
        content.charCodeAt(1) === 33/*!*/) {
      if (contLen === 2) {
        // Exact match                                                           
        content = '';
      } else {
        // Find end of shebang line and slice it off                             
        var i = 2;
        for (; i < contLen; ++i) {
          var code = content.charCodeAt(i);
          if (code === 10/*\n*/ || code === 13/*\r*/)
            break;
        }
        if (i === contLen)
          content = '';
	else {
          // Note that this actually includes the newline character(s) in the    
          // new output. This duplicates the behavior of the regular expression  
          // that was previously used to replace the shebang line                
          content = content.slice(i);
        }
      }
    }
  }
```

**Comment by grabbou** [comment]
@ide shall we just copy that, reference in a comment above the line & add a basic test (if we have them already for the packager?)

**Comment by ide** [comment]
Probably want to rewrite that code to use a regex so it's more readable. We'd run this code in the packager so this optimization probably isn't going to matter. This is the old code before https://github.com/nodejs/node/commit/ae18bbef48d87d9c641df85369f62cfd5ed8c250: 

```
const shebangRe = /^\#\!.*/;
content = content.replace(shebangRe, '');
```

**Comment by grabbou** [comment]
That looks good! Thanks for digging into this @ide. Submitted a proposal with unit tests.
