### ISSUE TITLE
[0.25] Commits to cherry-pick into 0.25-stable

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#7040]
List will be updated as new bugs and fixes arrive.

Warnings to fix / double check:
- [ ] "ReactNative.createElement is deprecated. Use React.createElement from “react” package" in a test project - https://github.com/facebook/react-native/pull/7060

**Comment by holyxiaoxin** [comment]
I'm seeing this warning too. Any idea which package is it coming from?

**Comment by ide** [comment]
The fix is to import the React API from the "react" package:
```js
import React, { PropTypes } from 'react';
```

**Comment by grabbou** [comment]
I've submitted a patch here -> https://github.com/facebook/react-native/pull/7060. Ideally I would like to cherry-pick it before the release as users might be confused why the errors are printed after creating a brand new project with CLI.

**Comment by holyxiaoxin** [comment]
It's still giving me this warning even after I've migrated every 'react' components. The warnings are lesser now. But I can't pinpoint which node_modules is giving me this error.

**Comment by grabbou** [comment]
It might be one of your dependencies - this warning is going to be quite annoying to work with. Would be really cool to disable warnings appearing on screen during development (kinda `mute` them), so you can just check the console w/o having your dx interrupted.

**Comment by satya164** [comment]
@grabbou @ide We should improve the warning and include a link. What do you say?

**Comment by satya164** [comment]
@grabbou I think what we should ideally do is show one warning instead of multiple.

**Comment by grabbou** [comment]
I think that's good idea and I seen it in React itself with flags like `!didShowWarning && console.warn()`. It's annoying to see probably 3/4 warnings covering half the screen each transition (+ there's no `close all` button)

**Comment by grabbou** [comment]
@satya164 opened up #7121 - I think the idea of showing only once is cool, but ability to just dismiss the on screen bar sounds like something more simple we can implement with just few lines :)

**Comment by bestander** [comment]
https://github.com/facebook/react-native/commit/1c6d815a887ec23585957202bb9c3079b20261e0 - version of simulator in docs https://github.com/facebook/react-native/pull/7061

**Comment by grabbou** [comment]
#7207 - document how to automatically upgrade all imports (if there's no codemod, consider preparing one).

**Comment by bestander** [comment]
https://github.com/facebook/react-native/commit/57c40d9a6f5a901cf108b72ab18f4bae9fc246e2#commitcomment-17284701

**Comment by grabbou** [comment]
All cherry picked :)

**Comment by charpeni** [comment]
@grabbou #6880 was introduced into 0.25, I think it should be listed in release notes ?

Android new feature : Added WebChromeClient as default WebView client.

**Comment by grabbou** [comment]
Good catch!

**Comment by charpeni** [comment]
@grabbou You linked the wrong commit hash, it should be f94abd3 :)
