### ISSUE TITLE
[Android] [TextInput] blurOnSubmit doesn't really blur i.e. relinquish focus, it only hides the keyboard

### ISSUE THREAD

**Issue by tejasd** [facebook/react-native#7047]
For an example of what I'm talking about, take a look at the UIExplorer Android app - the cursor is still visible when you submit and the onBlur callback gets called after you select another TextInput.

I've tried debugging it with no luck (I'm an iOS dev). Some paths I've explored:
- Changing the onKeyUp() method to call clearFocus() instead of hideSoftKeyboard() in ReactEditText.java - for some reason the debugger never hits that breakpoint.
- Tried tracing the changes in the blurOnSubmit PR (#6215) but I hit a roadbloack with trying to understand what's going on

Potential workarounds -
Call the blur() method on the textinput's ref in the TextInput's onSubmitEditing callback

Verified that this is an issue on RN master @ 42cfba558f18eda6e711cdea175303d9066bbb02 - 0.24+
Devices: Nexus 5, Genymotion

Would love some help in trying to understand what's going on! Thanks!

**Comment by radko93** [comment]
I think it's Android's behaviour to not lose focus onBlur. You can check [this](http://stackoverflow.com/questions/5056734/android-force-edittext-to-remove-focus)

**Comment by tejasd** [comment]
Ok, that makes a little more sense. Also, playing around with a few android apps, the more common convention was to not lose focus when you submit. (especially in the context of forms).

However we now have multiple confusing callbacks for TextInput - 
1) onBlur
2) onEndEditing

3) onSubmitEditing

I don't understand the difference between 1 and 2. Can someone more familiar point out the differences and/or similarities? Maybe it might be a good idea to simplify the two?

**Comment by alexkendall** [comment]
Having the same issue with this. Any updates / ways to workaround this issue?

**Comment by tejasd** [comment]
@alexkendall If you want a specific callback to be triggered and not necessarily have the text field lose focus, I'd recommend using one (or more) of the other callbacks (I'm using onEndEditing and onSubmitEditing).

**Comment by JimmyStavros** [comment]
Is there a built-in solution to this on android? It's incredibly frustrating that neither onSubmitEditing or onEndEditing work on android at all. I feel like this should be a bigger problem than google searching would suggest it is.

**Comment by af7** [comment]
+1

**Comment by inetfuture** [comment]
+1

**Comment by JimmyStavros** [comment]
+1

**Comment by sarovin** [comment]
+1

**Comment by antoinerousseau** [comment]
what about checking for any `\n` in `onChangeText` to manually trigger submit?

**Comment by huangkaiw3n** [comment]
same. just ran into this on android as well.

**Comment by abhisheknalin** [comment]
+1

**Comment by MrToph** [comment]
+1
Did anyone come up with a solution yet?

**Comment by f0rr0** [comment]
+1

**Comment by westcode** [comment]
+1

**Comment by lakhman** [comment]
argh, silly bug, I used the following solution by @MrToph, hopefully it helps others.

I would've thought this would `blur` the input when `done` was pressed on the keyboard.

```jsx
blurOnSubmit={true}  // ← Doesn't Work!
```

Add a `ref` to your `TextInput` and manually blur the input yourself using `onSubmitEditing`.

```jsx
<TextInput
    ref="search_input"
    onSubmitEditing={() => this.refs['search_input'].blur()}  // ← Works!
    // blurOnSubmit={true}                                    // ← Doesn't Work !!
    // onBlur={() => this.refs['search_input'].blur()}        // ← Doesn't Work !!
    // onEndEditing={() => this.refs['search_input'].blur()}  // ← Doesn't Work !!
/>
```

+1

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
