### ISSUE TITLE
Problem with running npm start - listening to default 8081 port

### ISSUE THREAD

**Issue by erinjerri** [facebook/react-native#705]
These threads helped me identify the problem:
https://github.com/facebook/react-native/issues/12

figuring out I needed to take steps in iOS app delegate:
https://github.com/facebook/react-native/issues/240

First I had to make sure I added the main.jsbundle to the project (the reference in the thread )

![image](https://cloud.githubusercontent.com/assets/3184381/7007916/c677fa3a-dc42-11e4-9c33-e801e9135ab4.png)

figuring out it was the 8081 port officiallyL
https://github.com/facebook/react-native/blob/master/packager/packager.js#L35

But I still kept getting the same problem and @mbrgm helped me through it. 

After that I tried 
    sudo lsof -nP -iTCP:8081 -sTCP:LISTEN

So I wrote in $PID, typed in my admin password:

We located that on node this was the issue '3960'

kill 3960 and the sudo command above. 
then I finally got the packager to run. 

![image](https://cloud.githubusercontent.com/assets/3184381/7008020/c9b4ea4a-dc43-11e4-838d-fa01ab4e1120.png)

![image](https://cloud.githubusercontent.com/assets/3184381/7008023/d2484a3a-dc43-11e4-87d2-5b9b1cd4299f.png)

**Comment by frantic** [comment]
note that your `kill $pid` command didn't actually kill anything, you need to run `pkill 3960`. But before that, try `ps aux | grep 3960` to see full path to the process that is taking that port.

**Comment by erinjerri** [comment]
Yup, I did that this morning too. Still not working unfortunately.

**Comment by erinjerri** [comment]
Finally got it to work, plus the curl thing I couldn't do. I had to recomment out things and do a fresh restart since I think OSX was locking up everything.

**Comment by mbrgm** [comment]
@frantic Should I send a PR adding a hint about the `EADDRINUSE` error to the troubleshooting section of the docs?

**Comment by frantic** [comment]
@mbrgm - as of #736 we provide better error message. Also the troubleshooting page already has instructions how to find out which process is taking the port and what to do. Or am I missing something?

**Comment by mbrgm** [comment]
@frantic Sorry, I missed that. This project is progressing so fast, I should've looked there before ;)
