### ISSUE TITLE
[prefetchImage] pass image dimensions to resolve callback

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#7050]
Would it be possible to pass image dimensions to `Image.prefetch`s resolve callback?

Like

``` js
Image.prefetch(url).then(dimensions => {
    let {width, height} = dimensions;
});
```

**Comment by gre** [comment]
sounds like you want to use `Image.getSize` ?
It looks like getSize is doing a downloading under the hood, so it might be doing same as prefetch + returning the size? (to be confirmed)

**Comment by skatpgusskat** [comment]
what about like this?
```
var prefetchTask = Image.prefetch(IMAGE_PREFETCH_URL);
...
prefetchTask.then(() => {
  Image.getSize(this.props.prefetchedSource.uri, (width, height) => {
    console.log(width, height);
  });
}, error => { ... });
```

**Comment by magicismight** [comment]
But there is a big problem.
Android don\`t support `Image.getSize`

**Comment by skatpgusskat** [comment]
@magicismight Good point. Then it could be the first priority to make ```Image.getSize``` for Android, isn't it?

**Comment by grabbou** [comment]
> It looks like getSize is doing a downloading under the hood

Not sure if fetching twice makes sense. I would just introduce an `image` object that would hold all these details and have place for future additions, like mime type etc.

Since currently prefetch does not resolve with anything, that would be an easy thing to do.

CC: @ide

**Comment by ide** [comment]
If prefetch and getSize both go through Fresco on Android and (IIRC) RCTImageDownloader on iOS, then they should share caches and dedupe concurrent requests.

For the API, I think we want `prefetch` (which can return metadata) and `getMetadata`. The reason is you might want to get the metadata of a locally embedded image or even a data URI, and that has nothing to do with prefetching.

**Comment by grabbou** [comment]
Thanks for the idea @ide, getMatadata definitely makes sense (shall we deprecate `getSize` in favour of that then?). Anyway, going to dig into that later today, will keep you updated.

**Comment by ide** [comment]
Yeah, I think deprecating getSize with a warning for a couple versions makes sense, if we're happy with the getMetadata API.

**Comment by Elf2707** [comment]
got some troubles with Image.getSize. It doesn't detect a size of the jpg image). I get an error while trying to detect size. Although, Image displays that jpg pretty nice. I guess, Image.getSize has some troubles with encoding. Fix it please). Thanks.

**Comment by lacker** [comment]
This sounds like a good idea for a small improvement, but the issue has been stale for a while and we are also trying to focus issues on bug reports, so I am going to close this issue. If someone is interested in making getSize work better then a pull request would be great!
