### ISSUE TITLE
it crash when I close or open **Photos** permission

### ISSUE THREAD

**Issue by linshaolie** [facebook/react-native#7051]
Hi, there is a bug after I run my app. and I access **Photos** or **Calendars** then I do these : 
<img width="320" alt="crash" src="https://cloud.githubusercontent.com/assets/6261591/14625350/e97106ce-0614-11e6-8656-1e17091fd35e.png"/>
<img width="843" alt="crash" src="https://cloud.githubusercontent.com/assets/6261591/14625371/1e061b22-0615-11e6-8209-0d23dba07cf6.png"/>

and it crash. I have not idea why it happen.
I am using RN v0.23.1 and I just test it on iOS.

**Comment by ide** [comment]
This is how iOS apps work I believe. If you can repro this only in React Native and not a plain iOS app please let us know.
