### ISSUE TITLE
Is it possible to use generators on React Native?

### ISSUE THREAD

**Issue by AleCaste** [facebook/react-native#7053]
Hello,
I am trying to use ```co``` (https://github.com/tj/co) on my React Native project but is not working.
I know ES6 async/await is supported, but... what about generators/yield? 
If the issue behind this is to do with uglifyjs, I believe the library is real close to support generators by now (https://github.com/mishoo/UglifyJS2/pull/959), but well, I am not sure if that would be the bottleneck here.

**Comment by ide** [comment]
@facebook-github-bot stack-overflow
