### ISSUE TITLE
Cannot Close Android App - React Native

### ISSUE THREAD

**Issue by balogic** [facebook/react-native#7056]
I have created an android app with react native which plays Radio using this module.

https://github.com/EstebanFuentealba/react-native-android-audio-streaming-aac

I have used the following code in my function,

`AACStreamingAndroid.setURLStreaming(channel);`
`AACStreamingAndroid.play();`

I cannot close the app once I start the radio and stop it.The app continues to stay in background.

Screenshot

![photo174286062476175850](https://cloud.githubusercontent.com/assets/6650280/14629365/a64e16d4-0623-11e6-9474-59db384af147.jpg)

Can anyone help?

**Comment by grabbou** [comment]
@facebook-github-bot stack-overflow
