### ISSUE TITLE
Documentation site still says version 0.23

### ISSUE THREAD

**Issue by BilalBudhani** [facebook/react-native#7059]
When clicked on version `0.24` docs the site still says `0.23` in the navigation header. 

<img width="273" alt="screen shot 2016-04-19 at 12 48 59 pm" src="https://cloud.githubusercontent.com/assets/1650995/14630729/14fc0efc-062d-11e6-9ac0-7188e6eccaf9.png">

<img width="1045" alt="screen shot 2016-04-19 at 12 48 46 pm" src="https://cloud.githubusercontent.com/assets/1650995/14630730/15253f0c-062d-11e6-86c6-c167724f37b6.png">

**Comment by charpeni** [comment]
It seems fixed now.

**Comment by charpeni** [comment]
@facebook-github-bot close
