### ISSUE TITLE
Alert text Tint Color

### ISSUE THREAD

**Issue by williambout** [facebook/react-native#7062]
Suggestion : Tint Color prop for Alert.

**Comment by charpeni** [comment]
I'll close this since GitHub issues should only be used for bugs.

Post your feature request on Product Pains, It has a voting system to surface the important issues as specified in the [ISSUE_TEMPLATE](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md).

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by dsibiski** [comment]
@williambout If you're able to submit a pull request for something like this (which seems relatively simple) it would be greatly appreciated. It's a great first task to become a contributor to RN!

**Comment by lenichols** [comment]
Adding this prop would be lovely...

**Comment by inferusvv** [comment]
I found a "global" way to change colors. You can change tint color via Android styles. You need to open `android/app/src/main/res/values/styles.xml` and add inside `<style>` tag next string:

`<item name="colorAccent">#000000</item>`

Tint color of alert buttons (and I suppose other elements, such as inputs) will become black.
