### ISSUE TITLE
RN 0.24 node_modules/react-native/Libraries/CameraRoll/CameraRoll.js: Missing class properties transform?

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#7065]
I upgraded to RN 0.24 and my app won't start up with this error message.
I'm not using CameraRoll.

Anybody got this issue?

**Comment by mschipperheyn** [comment]
Tried various babel configurations
Started out with this

    {
      "presets": [
        "es2015"
      ],
      "extends": "react-native/packager/react-packager/rn-babelrc.json",
      "plugins": [
       "babel-plugin-transform-decorators-legacy",
       "transform-es2015-modules-commonjs"
     ]
    }

Then I tried install a couple of plugins

    {
      "presets": [
        "es2015",
        "react-native",
        "react-native-stage-0",
        "react-native-stage-0/decorator-support"
      ],
      "extends": "react-native/packager/react-packager/rn-babelrc.json",
      "plugins": [
       "babel-plugin-transform-decorators-legacy",
       "transform-es2015-modules-commonjs"
     ]
    }

to no avail

**Comment by dbuarque** [comment]
+1

**Comment by mschipperheyn** [comment]
Lots of issues on my side. Tried cleaning all caches, running react-native upgrade.
Now I'm getting errors such as 

    Error: Requiring module "49" which threw an exception, stack:
    Error: Requiring module "49" which threw an exception
        at requireImpl (require.js:57)
        at _require (require.js:31)
        at ReactNativeDefaultInjection.js:19
        at requireImpl (require.js:82)
        at _require (require.js:31)
        at ReactNative.js:16
        at requireImpl (require.js:82)
        at _require (require.js:31)
        at React.js:14
        at requireImpl (require.js:82)

**Comment by mschipperheyn** [comment]
Downgraded to 0.24.0-rc5 but now I keep having this uninformative error.

**Comment by ide** [comment]
Can you try 0.24.1?

**Comment by mschipperheyn** [comment]
I did. And I got the same issue. I now tried reinstalling all node_modules. Same issue. Now I did a simulator reset.  Still not working.

I have been getting this one now for a while

    Error: Cannot read property 'process' of undefined, stack:
    TypeError: Cannot read property 'process' of undefined
        at setUpProcessEnv (/tmp/react-native.js:10338:22)
        at /tmp/react-native.js:10361:1
        at requireImpl (/tmp/react-native.js:87:13)
        at requireImpl (/tmp/react-native.js:44:25)
        at _require (/tmp/react-native.js:36:8)
        at /tmp/react-native.js:119371:2
        at Object.exports.runInContext (vm.js:44:17)

**Comment by mschipperheyn** [comment]
This is going from bad to worse. I upgraded again to RN 0.24.1, cleaned node_modules, caches, etc
Ran rnpm link. 

    Unabled to execute JS call:__fbBatchedBridge is undefined

Let's do one more full restart and see what's what

**Comment by mschipperheyn** [comment]
After much trial and error I managed to get back to the original reported error 

    node_modules/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationContext.js: Missing class properties transform.
    >   56 |  */
    >   57 | class NavigationContext {
    > > 58 |   __node: NavigationTreeNode;
    >      |   ^
    >   59 |   _bubbleEventEmitter: ?NavigationEventEmitter;
    >   60 |   _captureEventEmitter: ?NavigationEventEmitter;
    >   61 |   _currentRoute: any;
    >     at File.buildCodeFrameError (/Users/Shared/java/projects/react/projects/msa_mobile2/msa_mobile/node_modules/babel-core/lib/transformation/file/index.js:407:15)

**Comment by ide** [comment]
Do you have a custom .babelrc? You might have it misconfigured.

**Comment by mschipperheyn** [comment]
I have this one 

    {
      "presets": [
        "es2015"
      ],
      "extends": "react-native/packager/react-packager/rn-babelrc.json",
      "plugins": [
       "transform-decorators-legacy"
     ]
    }

**Comment by mschipperheyn** [comment]
Hmmm, this one seems to get it back in working order. Not sure if I still got my decorators working, but at least I'm seeing something happening on my side of the code 

    {
      "presets": [
        "react-native"
      ],
      "plugins": [
       "transform-decorators-legacy"
     ]
    }

**Comment by mschipperheyn** [comment]
I also realized that I suddenly am seeing all sorts of "buck" stuff that wasn't there before (I never used it). I think we might have something here ....

**Comment by mschipperheyn** [comment]
Yeah, removing the buck-out, .buckd content **seems** to fix the issue. I don't know. It works. Moving on.

**Comment by mschipperheyn** [comment]
I ran into this issue again. The solution can be found here: https://phabricator.babeljs.io/T3000
