### ISSUE TITLE
when i use navigator ,null is not an object 

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#7066]
[tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: null is not an object (evaluating 'internalInstance._currentElement')

**Comment by jhack32** [comment]
Can you post some code where this is happening?

**Comment by charpeni** [comment]
You can even host it on [React Native Playground](https://rnplay.org/).

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by MayeuldP** [comment]
You can find my ask about DrawerLayoutAndroid on StackOverflow... If you can help me.
<p> http://stackoverflow.com/questions/36722237/show-my-drawerlayoutandroid-onpress-rightbutton-from-navigationbarroutemappe <p> Just posted here for more visibility, don"t want to create a new issues, just for a link... Thank's !

**Comment by grabbou** [comment]
Awesome, left a comment, let's keep discussion up there
