### ISSUE TITLE
hot reloader issue in 0.24

### ISSUE THREAD

**Issue by gmchaturvedi1** [facebook/react-native#7068]
i am facing problem in hot reloading in .24 

screenshot is 

![screenshot](https://cloud.githubusercontent.com/assets/10846505/14647134/f2c847f4-0679-11e6-8abf-6b700b23286e.png)
kindly help me out to resolve this.

Regards
G m chaturvedi

**Comment by janicduplessis** [comment]
Hot reloading doesn't work on Windows in 0.24, it is fixed in 0.25rc but we haven't updated the babel-preset-react-native yet. Check #7076 for progress on that.

**Comment by janicduplessis** [comment]
@facebook-github-bot close
