### ISSUE TITLE
Image width and height props are gone?

### ISSUE THREAD

**Issue by gre** [facebook/react-native#7069]
I moved from 0.22 to 0.24 and it looks like there is a breaking change (or a regression ?) on the width and height props of an image.
I had a bunch of `<Image source={{ uri: httpURL }} style={{ position: "absolute", top: 0, left: 0 }} width={width} height={height} onLoad={onLoad} />` images in my code and it will never load since the migration, onLoad never get called neither (and i've even tried all onLoad* hooks).
But if I convert this to `<Image source={{ uri: httpURL }} style={{ position: "absolute", top: 0, left: 0, width, height }} onLoad={onLoad} />` it is working again.

I just want to log this issue, i'm ok to deprecate/remove this width/height props in favor of using style but be aware it is a recent breaking change and it is not mentioned anywhere.

**Comment by gre** [comment]
maybe it was me accidentally using width and height? is that from a very old RN version & how come support of this was recently dropped?

**Comment by radko93** [comment]
I think it's here https://github.com/facebook/react-native/commit/e4093a6abbe7c1e8e844e2b72f0f5c3562ad181f

**Comment by gre** [comment]
woo, good find. one year old. but i'm pretty sure was still working in 0.22. mmh.
i'm closing the issue anyway, i just wanted to create it because other people might run in this.
