### ISSUE TITLE
How to save image from URL to device?

### ISSUE THREAD

**Issue by vanloc0301** [facebook/react-native#7072]
I am building app with React Native, and what I've done is that:

fetch('https://server.com/images.json').then((json) => console.log(json))

Which returns json:

{images: ["cdn.server.com/image1.jpg", "cdn.server.com/image2.jpg"]}

And now I really don't know what to do to save images to my device, because then I need to use them to open Instagram Intent (https://www.instagram.com/developer/mobile-sharing/android-intents/) and it only works if image is saved to device.

Any ideas?

**Comment by charpeni** [comment]
You can use [react-native-fs](https://github.com/johanneslumpe/react-native-fs) to download files.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by vanloc0301** [comment]
Thanks @charpeni
