### ISSUE TITLE
[NavigationExpermental] Back actions for StackReducers

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#7074]
#6963 moved the back action to let inner stacks handle the action first, but I'm realizing now that you might want other behavior. For example, if an outer stack is displaying a modal, you probably want that stack to handle the back action rather than any inner stacks.

One solution would be to have two types of back actions, one that is handled by the inner-most stack first, and one that is handled by outer-most stacks. Another solution would be to tie a back action to a specific stack via a key property on the action.

@ericvicenti thoughts?

**Comment by ericvicenti** [comment]
If your modal has anything to go back inside of it, then I think the back action would mean to go back within the modal, and only close the modal once at the first screen of it. So I think the default behavior is correct, but we should enhance the capabilities of the action.

Sometimes you want to dismiss a specific scene (and everything within and ahead of it). We have keys on our navigationStates/scenes for this reason, so we can just add a key to the back action and implement it in our stack reducer.

I'd be happy to review the PR, if you want to take this on!
