### ISSUE TITLE
TouchableOpacity with repositioned child will grow on iOS, but clip on Android

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#7078]
If you stick a "top:" style offset on some element inside a TouchableOpacity, it behaves differently:
- the iOS version grows the Touchable to match the new location of the element
- The Android version has a static Touchable size, and the element gets clipped off the edge of the Touchable

You can see the bug here: https://www.rnplay.org/apps/df-sag (switch between iOS and Android)

Happened on RNPlay with 0.21, though I've seen it with 0.24 in my app. The bug is on Android, as the iOS behavior seems more robust.

**Comment by mikelambert** [comment]
My workaround is to reposition the TouchableOpacity itself, instead of the sub-elements inside. It works for my case now, but not sure it would work for every case...

**Comment by mikelambert** [comment]
My workaround is to reposition the TouchableOpacity itself, instead of the sub-elements inside. It works for my case now, but not sure it would work for every case...

**Comment by janicduplessis** [comment]
Probably related to this known issue: http://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android

**Comment by lacker** [comment]
Hmm, that rnplay.org link doesn't run for me. Maybe it decayed in the time since anyone responded to this issue. Since there's a workaround + known issue I am going to close this but if someone disagrees feel free to reopen it.

**Comment by mikelambert** [comment]
Yeah looks like bitrot since the rnplay update. I have fixed the rnplay sample here: https://www.rnplay.org/apps/e2qQXw

The workaround/known-issue link has changed, and is now here:
https://facebook.github.io/react-native/releases/0.26/docs/known-issues.html

I'm also not clear that this captures what I'm seeing here. This is not simply a case of wanting to overflow rendering outside the bounds of the parent.

My `<TouchableOpacity>` is not fixed size. If the elements inside use `top` to offset the contents, I'd expect the `TouchableOpacity` to still contain its contents, and grow to include the `<Text>` component, like it does on iOS.
