### ISSUE TITLE
[iOS] uploading a non-ready iCloud image results of sending empty bytes

### ISSUE THREAD

**Issue by gre** [facebook/react-native#7081]
I am using a custom camera roll picker that allows to pick iCloud images, and when you use them in a XHR and send them to a server (using their 'descriptor object', I mean the `{uri}` object), **they only are submitted if they are downloaded on the phone, but not if they are not in sync, in that second case, server will receives empty bytes because images was not ready**.

A workaround is to define a custom ObjC code to call before submitting the form, but IMO this should be solved by RN when it 'resolves' the `{uri}` object to bytes.

```objc

RCT_EXPORT_METHOD(ensureImageIsReady:(NSString *)arg
                  successCallback:(RCTResponseSenderBlock)callback
                  cancelCallback:(RCTResponseSenderBlock)cancelCallback)
{
  if ([arg length]<=5 || ![[arg substringToIndex:5] isEqualToString:@"ph://"]) {
    callback(@[@(false)]);
    return;
  }
  NSString *localIdentifier = [arg substringFromIndex:5];
  PHFetchResult *fetchResult = [PHAsset fetchAssetsWithLocalIdentifiers:@[localIdentifier] options:nil];
  PHImageManager *manager = [PHImageManager defaultManager];
  PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
  options.networkAccessAllowed = YES;
  for (PHAsset *asset in fetchResult) {
    [manager
     requestImageDataForAsset:asset
     options:options
     resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
       if (imageData)
         callback(@[@(true)]);
       else
         cancelCallback(@[@"image failed to download"]);
     }];
  }
}
```

**Comment by samuelkraft** [comment]
Related issue: #1885
Is iCloud support for images something that is planned to work out of the box with `CameraRoll` ?

**Comment by gre** [comment]
Even if camera roll don't support iCloud when listing photos, I think it's
a separated concern.
To me this is still a bug that photos aren't "resolved" when uploaded and
it's in React Native network stack (the form upload that resolve the {uri}
object).
If you happen to use a react-native plugin that use iCloud files (images or
whatever) you should still be able to manipulate it with React Native.

Le jeu. 21 avr. 2016 08:46, Samuel Kraft <notifications@github.com> a
écrit :

**Comment by 6061960** [comment]
Hi gre@,

As you mentioned you are using a custom camera roll.
It is not the official one? https://facebook.github.io/react-native/docs/cameraroll.html

How could you see the the icloud image from your camera roll?
In my case, no matter which groupTypes I choose, I can't see my icloud images which have only a preview version in local.
Only after I download the original image from my Photos, I can see it in the camera roll.

Thanks!

**Comment by gre** [comment]
@6061960 RN's CameraRoll have limitations as AFAIK you can only list the camera roll photos. If you want more advanced stuff, and for instance, you can use [QBImagePickerController](https://github.com/haiwen/QBImagePickerController) which allow to pick from iCloud and also support multi-selection (there are many other alternatives, depends on what you need, search on google).

**Comment by gre** [comment]
this bug was supposed to be fix, but it is still not fixed to me unfortunately.
tested on 0.34.

<img width="459" alt="screen shot 2016-09-29 at 13 14 50" src="https://cloud.githubusercontent.com/assets/211411/18951688/bab79bc4-8646-11e6-9684-19a723cdf811.png">

**Comment by ronaldheft** [comment]
Which iOS version? I've been unable to reproduce on iOS 10.

--
Ron Heft

**Comment by gre** [comment]
you are right. This works in iOS 10, but it doesn't on iOS 9 (tested on sim')

**Comment by ronaldheft** [comment]
Yeah, unfortunately, I don't have a good answer. The fix I implemented follows Apple's documentation. It indicates either there is a slight difference in how PhotoKit works on iOS 9; that it most likely does not trigger the progress logic correctly in React Native.

I do not have time to debug at the moment, but that's where I would start. Set some breakpoints on on the progress handler and see how React Native is handling the progress reports (or even if they're fired at all):

https://github.com/facebook/react-native/blob/34f98210b1fd9e07e7a61298c03382cad5a8a892/Libraries/CameraRoll/RCTPhotoLibraryImageLoader.m#L69
