### ISSUE TITLE
Cannot textAlign center in ListView renderHeader() function 

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native#7085]
The Text component is rendered with textAlign center style well if outside of ListView renderHeader() function. It seem like the textAlign is not working in ListView renderHeader()  part. It will make the text content not rendered.

**Comment by dsibiski** [comment]
Can you post an example where you can replicate this on http://rnplay.org? Also, what version of RN are you using? Is this happening on iOS/Android or both?

**Comment by vshy108** [comment]
I'm using RN 0.23.1 and the problem happened when I use flex on styling for View that contains Text component in the ListView renderHeader function. The Text component textAlign works well if the parent View component are given fixed height and width but it won't work well if use flex on parent View. This problem happened in Android platform, did not test on iOS.

**Comment by grabbou** [comment]
It's likely a styling issue - I couldn't reproduce it. Please take a look at my sample implementation: https://rnplay.org/apps/H68wEQ

Here's what I got:
<img width="303" alt="screen shot 2016-04-20 at 20 26 18" src="https://cloud.githubusercontent.com/assets/2464966/14685768/29a0c1d6-0736-11e6-913d-dfd1cc2ee09c.png">

I would suggest you CMD + D -> Toggle inspector (on Android just press `menu` button) to inspect what are the sizes your view takes and what's causing the text from not being aligned properly.

**Comment by braco** [comment]
@vshy108 did you figure this out? I'm getting this too – renderHeader is getting a width larger than the screen, so centering is justified toward the right. Must be a styling issue, but haven't tracked it down
