### ISSUE TITLE
RefreshControl can not work in android

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#7086]
hi，when I use ListView ，IOS work well，but android not work！ 

<ListView enableEmptySections={true}
                dataSource={this.state.dataSource}
                refreshControl={
                <RefreshControl
                  refreshing={this.state.isRefreshing}
                  onRefresh={this._onRefresh.bind(this)}
                  tintColor="#ff0000"
                  enabled={true}
                  title="pull down to update..."
                  colors={['#ff0000', '#00ff00', '#0000ff']}
                  progressBackgroundColor="#ffff00"
                />
              }
                onEndReached={this._pullUpToLoadMore.bind(this)}
                onEndReachedThreshold={this.state.dataSize}
                renderHeader={this._renderHeader.bind(this)}
                renderRow={(rowData)=>{return this._renderRow(rowData,_navigator)}}
                initialListSize = {20}
                renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} />}
                renderSeparator={(sectionID, rowID) => <View key={`${sectionID}-${rowID}`} style={styles.separator} />}
            />

**Comment by dsibiski** [comment]
@facebook-github-bot stack-overflow

**Comment by alokverma65977** [comment]
Use third party API for that or update the react-cli to 0.24 .In 0.24 that bug solved. https://www.npmjs.com/package/react-native-refresh-control

**Comment by charlesluo2014** [comment]
hi，thanks ，my ios is work well，but android not work
@alokverma65977

**Comment by hzy00** [comment]
+1 
pull-down doesn't work in android

**Comment by ophite** [comment]
+1

**Comment by keithics** [comment]
+1
