### ISSUE TITLE
Documentation Error: Animation API

### ISSUE THREAD

**Issue by clairesarsam-wf** [facebook/react-native#709]
On the react-native documentation site, the documentation for the `Animation` API doesn't look like it's generating correctly.

![image](https://cloud.githubusercontent.com/assets/6198081/7013035/d9e1553a-dc6a-11e4-8be3-bff3daaa058d.png)

**Comment by ide** [comment]
cc @sahrens this might be related to the AnimationExperimental rename.

**Comment by vjeux** [comment]
Yeah, we removed the Animation API from react-native as it's not being used anywhere and not good right now. I need to remove it from the docs.

**Comment by vjeux** [comment]
https://github.com/facebook/react-native/commit/6a970546966aa190e5d972bca17baa3d1c2a4786

-- 
Christopher "vjeux" Chedeau
Facebook Engineer
http://blog.vjeux.com/

**Comment by clairesarsam-wf** [comment]
Good to know, thanks!

**Comment by mattotodd** [comment]
@vjeux What are the plans on this?  Any recommendations for animation til then?

**Comment by vjeux** [comment]
I've seen people use react-tweet-state successfully https://github.com/chenglou/react-tween-state

**Comment by mattotodd** [comment]
perfect, thx
