### ISSUE TITLE
GET must not have a request body

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#7093]
I was getting this error because I used to do
```
if(data){ data = JSON.stringify(data) }else{ data = '' }
// and
request.send(data)
```
not a problem on web. Is it really that important for a GET to not have a body?
changed it to
```
      if (data) {request.send(data)} else {request.send()}
```
and that's fine. It did not take me any time to figure this out, but it did seem weird.

**Comment by dimitrovskif** [comment]
Read the HTTP RFC. GET requests support sending data using query parameters or headers, but sending a body is not possible.

I would suggest sending data in the query parameters if it's not big and confidential. In any other case, use other methods like POST and PUT.

**Comment by grabbou** [comment]
Closing as it's not really spec compliant. Also - even if that would work on web, the data is not sent anyway. I suggest checking `if (data && method !== 'GET')` if you can't change it earlier :)

**Comment by ThaJay** [comment]
that's okay, did not know the details of the spec (should have looked them up first). Thanks for the quick response. Browsers do have a tendency to make everything work don't they? :)
