### ISSUE TITLE
ScrollView.onScroll resets the offset value prematurely

### ISSUE THREAD

**Issue by DannyiCracked** [facebook/react-native#7097]
```
<ScrollView 
    onResponderRelease={(evt) => {
        console.log(this._scrollPosition);
        if(this._scrollPosition < -20) {
            alert("reached offset value");
        }
    }}
    onScroll={(evt) => { 
        this._scrollPosition = evt.nativeEvent.contentOffset.y;
    }}
    scrollEventThrottle={16}
    contentContainerStyle={{ height: window.height }} //see Dimensions
/>
```

react-native@0.23.1 - All iOS devices (including OS X simulator) - untested on Android

When you pull down in the ScrollView window the `evt.nativeEvent.contentOffset.y` value will be a minus number that shows the offset from the top of its container. 

It appears that when a user "finishes" scrolling, the `evt.nativeEvent.contentOffset.y` value is reset to 0, even though the bounce animation, and "return to home" animation has not finished.

To re-produce, use the code snippet above and watch your console. Release your finger from the ScrollView event, but rapidly re-apply your touch to beat the `alert`. If you start to scroll again, you will notice that the `evt.nativeEvent.contentOffset.y` value is no longer true to its position. Instead it defined its new base offset as the position of the beginning of the drag, rather than the container it lives in.

**Comment by ZackZheng2014** [comment]
It seems to be "0" anytime.

**Comment by lacker** [comment]
These comments seem like different problems - is it getting stuck at "0" at any time, or is it misdefining its base offset? I think it would help to have one repro codebase here, like a rnplay.org link.
