### ISSUE TITLE
Parent  < -- > Child relationships

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#71]
Given that the concepts of Components are heavy in this toolset, I can't help but think of parent-child relationships and UI events. 

I'm working on an example app that adds children to a parent via the parent's + button click, and removing children via the child's - button click.

The question becomes, how does a parent get notified that a child needs to be destroyed?

Parent: https://gist.github.com/jaygarcia/2157f7abac0a46449103
Child: https://gist.github.com/jaygarcia/af7cf118071b9c68c2eb

Demo: http://www.screencast.com/t/DGCKSQ8zYNU

**Comment by RockyF** [comment]
Do you know Context on React-native!
