### ISSUE TITLE
Is navigator.geolocation.watchPosition supported on android?

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#7100]
Its unclear from the docs if or not _navigator.geolocation.watchPosition_ and _navigator.geolocation.getCurrentPosition_ are working on android.  I've followed the instructions but neither seems to work for me.

**Comment by dimitrovskif** [comment]
Yes it is. If you have `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` in your manifest file, it should work.

**Comment by npomfret** [comment]
Hmm, I have that.  Maps work, there's even a blue dot for my location.  But those 2 api calls don't seem to work.  _ navigator.geolocation.getCurrentPosition_ just times out, no matter what time limit i supply, and _navigator.geolocation.watchPosition_ just does nothing.

**Comment by dimitrovskif** [comment]
What happens when you run this:

```javascript
var options = {
  enableHighAccuracy: true,
  timeout: 5000,
  maximumAge: 5000
};

function success(pos) {
  var crd = pos.coords;
  alert(crd.latitude + " " + crd.longitude);
};

function error(err) {
  alert('ERROR(' + err.code + '): ' + err.message);
};

navigator.geolocation.getCurrentPosition(success, error, options);
```

**Comment by npomfret** [comment]
I get 'error' & 'Location request timed out'

**Comment by dimitrovskif** [comment]
Are you running on a real Android device with working GPS sensor or an emulator? If you are running the app on emulator, you must connect to the emulator using telnet and run `geo fix 22 44` (or any other coordinate values)

**Comment by npomfret** [comment]
Real device.  It even shows my current location when I load a map (with the blue dot).  But the API calls simply don't work.

**Comment by npomfret** [comment]
I've partially solved the problem.  I stepped though the java code in the debugged and found out that the last position the phone recorded was over 20 hours ago.  So the max age limit was preventing getCurrentPosition from returning anything.

Why it doesn't have any gps data for 20 hours is a mystery.  Especially as I've view maps since then and they are showing the GPS position perfectly.

**Comment by dimitrovskif** [comment]
Just because position is shown correctly doesn't mean your sensor is working (you may have been at the same position 20 hours ago) Try testing your GPS with sensor test apps on Play Store.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by badis** [comment]
@npomfret  . I am getting exactly the same issue here!
Have you found any solution for it ?

**Comment by jjzazuet** [comment]
Hi. Still an issue. Thoughts? Thanks!
