### ISSUE TITLE
[0.24.1] "Can't find variable: __fbBatchedBridge" crash on Android release

### ISSUE THREAD

**Issue by jeffchienzabinet** [facebook/react-native#7102]
Recently our Android release builds have been plagued with occasional crashes during the startup on Android 5 and 6.

    04-20 17:10:54.486  2251  2284 I ActivityManager: Displayed com.zabinet.rnconsumer/.MainActivity: +471ms
    04-20 17:10:54.606  3589  7965 D GCM     : GcmService start Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.c2dm.intent.REGISTER
    04-20 17:10:54.699  2251  2283 D BluetoothManagerService: Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@2dbe12:true
    04-20 17:10:54.727 17751 17809 E ReactNativeJNI: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
    04-20 17:10:54.811 17751 17809 E AndroidRuntime: FATAL EXCEPTION: mqt_js
    04-20 17:10:54.811 17751 17809 E AndroidRuntime: Process: com.zabinet.rnconsumer, PID: 17751
    04-20 17:10:54.811 17751 17809 E AndroidRuntime: java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
    04-20 17:10:54.811 17751 17809 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
    04-20 17:10:54.812  2251  9753 W ActivityManager:   Force finishing activity com.zabinet.rnconsumer/.MainActivity

I tried looking for similar issues but I couldn't find any (most of them are about the iOS packager). This app does use a lot of external packages so I wouldn't be surprised if that was the cause, but removing them has been a long and ineffective quest so far, so I would appreciate any insight or advice as to why this is happening. Thanks!

**Comment by jeffchienzabinet** [comment]
Forgot to mention, but this has happened on 0.23.1 too. I'm not sure about before that; I didn't set up crash reporting before then.

**Comment by jeffchienzabinet** [comment]
Oh I've started trying out master and I guess I'm triggering the "JSCExecutor::callFunction" exception. Time to debug

**Comment by jeffchienzabinet** [comment]
Ah, I think I found the component.

**Comment by ipk2015** [comment]
I miss the same question.Could you tell me how did you solve it ?
I change  "android\app\src\main\java\com\rnwin0410\MainActivity" to "android\app\src\main\java\com\rnwin0410\myact\MainActivity" ,and I change the packageName in AndroidManifest.xml and applicationID in app/build.grandle to "com.rnwin0410.myact" .Then I meet the problem.
Could you help me about it? Thanks!
`04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.onProvideReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 158: Landroid/app/Activity;.onProvideReferrer ()Landroid/net/Uri;
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.getReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 75: Landroid/app/Activity;.getReferrer ()Landroid/net/Uri;
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/ReactNativeJNI: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                     Process: com.rnwin0410.myact, PID: 17685
                                                                     java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                                         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                                         at java.lang.Thread.run(Thread.java:841)`

**Comment by ipk2015** [comment]
I miss the same question.Could you tell me how did you solve it ?
I change "android\app\src\main\java\com\rnwin0410\MainActivity" to "android\app\src\main\java\com\rnwin0410\myact\MainActivity" ,and I change the packageName in AndroidManifest.xml and applicationID in app/build.grandle to "com.rnwin0410.myact" .Then I meet the problem.
Could you help me about it? Thanks!
`04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.onProvideReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 158: Landroid/app/Activity;.onProvideReferrer ()Landroid/net/Uri;
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.getReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 75: Landroid/app/Activity;.getReferrer ()Landroid/net/Uri;
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/ReactNativeJNI: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                     Process: com.rnwin0410.myact, PID: 17685
                                                                     java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                                         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                                         at java.lang.Thread.run(Thread.java:841)`

**Comment by ipk2015** [comment]
I miss the same question.Could you tell me how did you solve it ?
I change "android\app\src\main\java\com\rnwin0410\MainActivity" to "android\app\src\main\java\com\rnwin0410\myact\MainActivity" ,and I change the packageName in AndroidManifest.xml and applicationID in app/build.grandle to "com.rnwin0410.myact" .Then I meet the problem.
Could you help me about it? Thanks!
```
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.onProvideReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 158: Landroid/app/Activity;.onProvideReferrer ()Landroid/net/Uri;
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact I/dalvikvm: Could not find method android.app.Activity.getReferrer, referenced from method com.rnwin0410.myact.MainActivity.access$super
04-26 23:57:48.920 17685-17685/com.rnwin0410.myact W/dalvikvm: VFY: unable to resolve virtual method 75: Landroid/app/Activity;.getReferrer ()Landroid/net/Uri;
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/ReactNativeJNI: Got JS Exception: ReferenceError: Can't find variable: __fbBatchedBridge
04-26 23:57:49.240 17685-17743/com.rnwin0410.myact E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                                     Process: com.rnwin0410.myact, PID: 17685
                                                                     java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
                                                                         at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
                                                                         at java.lang.Thread.run(Thread.java:841)
```

**Comment by jeffchienzabinet** [comment]
For me, this is all just my conjecture so far, but I believe it's because I was using https://github.com/walmartreact/react-native-orientation-listener and there's a race condition where it tries to send an event via DeviceEventManagerModule and even though it checks for Catalyst (the Javascript engine) via hasActiveCatalystInstance, there's a very tiny window where hasActiveCatalystInstance is true but __fbBatchedBridge isn't set yet. I haven't confirmed or sent a bug report/fix yet to them, but I would advise you to check all of your plugins, especially ones that send Javascript events.

**Comment by jeffchienzabinet** [comment]
If I'm right, then I think the proper solution is to change the plugin(s) to use LifecycleEventListener and only send events after onHostResume

**Comment by ipk2015** [comment]
Finally, I solve the problem.But It's strange for the process.I init a new RN project,firstly change the applicationID in app/build.grandle, try running the project and successful.Then I change the packageName in AndroidManifest.xml and the path of MainActivity.java.  What's strange is that it's different result for different packageName in the same way. I don't know why.The only difference between two projects is I once installed app with the same packageName with the failing one.

**Comment by ipk2015** [comment]
@jeffchienzabinet  Thanks for giving me the thought about the problem.

**Comment by flegall** [comment]
We've had the same issue here, it turned out that our ReactActivity was not in the same java package as the AndroidManifest, therefore since the ReactActivity.getUseDeveloperSupport() was relying on BuildConfig.DEBUG, (which we imported as com.facebook.react.BuildConfig).

**Comment by hey99xx** [comment]
@jeffchienzabinet Do you if there's any place in React Native that gets it wrong and uses DeviceEventEmitter prematurely? I've isolated the same issue to the same cause, but I don't know who's calling it, likely my own code.

**Comment by hey99xx** [comment]
Also I am not sure how LifecycleEventListener would be more useful. That one does not listen to catalyst at all. Did you mean ReactInstanceEventListener
