### ISSUE TITLE
Possible Unhandled Promise Rejection (id:0)

### ISSUE THREAD

**Issue by albo1337** [facebook/react-native#7107]
Hey Team,

I get this yellow box: 

```
Possible Unhandled Promise Rejection (id: 0):
Already read
TypeError: Already read
    at consumed (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:12146:23)
    at Response.Body.text (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:12237:14)
    at _class._onRegisterPressed$ (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:73490:940)
    at tryCatch (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10389:30)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10665:12)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10422:13)
    at tryCatch (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10389:30)
    at invoke (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10465:12)
    at http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:10473:1
    at tryCallOne (http://10.10.1.227:8081/index.ios.bundle?platform=ios&dev=true:6407:8)
```

How can I fix this? I'm doing a server request inside a try catch block. Everything is working fine. I'm not getting any errors from my server, only this yellow box appears.

Thank you a lot for this great framework!

albo1337

**Comment by 601367322** [comment]
me too.....

**Comment by jhack32** [comment]
Seems like the response was already processed

http://stackoverflow.com/questions/34786358/what-does-this-error-mean-uncaught-typeerror-already-read

**Comment by grabbou** [comment]
Yep, that error happens when body has been already consumed, with e.g. `res.json()` call.

**Comment by gventuri** [comment]
Hi there, I have something similiar happening with my app, and it's pretty strange: infact, if I make a request to a Json file for https://en.wikiquote.org/w/api.php?format=json&action=query&list=search&srsearch=wikipedia&srwhat=text&srprop=timestamp&prop=info, it works great, but if I made the same request for the identical file on my website (http://gabrieleventuri.it/pog/getFlow.json), it doens't work and gives me several errors, as below:

![schermata 2016-08-24 alle 14 38 28](https://cloud.githubusercontent.com/assets/15671184/17931043/afa01fe4-6a09-11e6-9389-4fe3ee4634e4.png)
![schermata 2016-08-24 alle 14 38 09](https://cloud.githubusercontent.com/assets/15671184/17931045/afa9772e-6a09-11e6-9fbd-79510305d426.png)
![schermata 2016-08-24 alle 14 38 00](https://cloud.githubusercontent.com/assets/15671184/17931044/aface13e-6a09-11e6-8201-c931e3f76941.png)

This is my code:

’’’javascript
getPostsFromApi() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 != r2})

    fetch("http://gabrieleventuri.it/pog/getFlow.json")
     .then((response) => response.json())
     .catch((error) => console.warn("fetch error:", error))
     .then((response) => {
       this.setState({
         pogDataSource: ds.cloneWithRows(response.query.search)}
       )}
     )
  }

  componentDidMount(){
    this.getPostsFromApi()
  }
’’’

Can anyone help me? Thank you very much

**Comment by jhack32** [comment]
@gventuri try debugging by removing the this.setState and do a console.log(response) instead. What does that give you? From the error message, it doesn't look like you're getting the json object back.

**Comment by gventuri** [comment]
Yes, it is actually `undefined`, but I don't understand why. Also, it runs the getPostsFromApi() twice, but again, I don't understand why...

**Comment by jhack32** [comment]
You also need to return response.json()

**Comment by gventuri** [comment]
Ok, now my getPostsFromApi() looks like this

```javascript
getPostsFromApi() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 != r2})

    fetch("http://gabrieleventuri.it/pog/getFlow.json")
     .then((response) => response.json())
     .catch((error) => console.warn("fetch error:", error))
     .then((response) => {
       console.log(response)
       return response.json()
     }
     )
  }
```

and this is the console

![schermata 2016-08-24 alle 16 58 41](https://cloud.githubusercontent.com/assets/15671184/17935596/36b93ec2-6a1c-11e6-970c-d2d962d06d6b.png)

**Comment by jhack32** [comment]
`getPostsFromApi() {
    var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 != r2})

    fetch("http://gabrieleventuri.it/pog/getFlow.json")
     .then((response) => return response.json())
     .catch((error) => console.warn("fetch error:", error))
     .then((response) => {
       console.log(response)
     }
     )
  }`

Maybe I should've been clearer, but I meant to put the return response.json() in the first .then

**Comment by gventuri** [comment]
![schermata 2016-08-24 alle 17 08 49](https://cloud.githubusercontent.com/assets/15671184/17935954/7b6f1ae0-6a1d-11e6-95bc-41efae3b29e8.png)

**Comment by jhack32** [comment]
Might be related to this:

https://github.com/facebook/react-native/issues/4415

**Comment by gventuri** [comment]
@jhack32: Thank you very much! Now it works great!

**Comment by leinov** [comment]
i'm also have this question

**Comment by Eyesonly88** [comment]
Note for future readers: this error also happens if you have `throw Error(msg)` in your code!

**Comment by hellomarcoliver** [comment]
All code examples do not work when changing the .json file and fetching it from another website – for whatever reason I do not know.
