### ISSUE TITLE
<TouchableHighlight> android / ios border difference

### ISSUE THREAD

**Issue by markbrown4** [facebook/react-native#7109]
You can apply a single borderBottom to a TouchableHighlight with borderRadius in ios.
In Android, when you apply a borderRadius, to be able to see the borderBottomColor you need to have a border on all four sides.

```js
function HelloButton() {
  let styles = {
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 10,
    paddingTop: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#000'
    // uncomment to break borderBottomColor above
    // borderTopLeftRadius: 5,
    // borderTopRightRadius: 5,
  };

  return (
    <TouchableHighlight
      underlayColor={ '#000' }
      style={ styles }
    >
      <Text>Hello</Text>
    </TouchableHighlight>
  )
}
```

**Comment by christopherdro** [comment]
Hey @markbrown4! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
