### ISSUE TITLE
LayoutAnimation delete animation?

### ISSUE THREAD

**Issue by chadobado** [facebook/react-native#711]
Really been enjoying how intuitive LayoutAnimation is for tweening UI changes.  

Unfortunately support for ```delete``` reconciliation appears to be stubbed out but not implemented yet.   This results in update/create transitions working as expected, but any delete transitions simply disappear off the screen (pretty poor ux for half the experience).

Have attempted forcibly mounting otherwise inactive components and updating their styles prior to state changes, to at least allow RCTUIManager to use the ```update``` animation config.  Not a good solution for obvious reasons.

Any idea where this is on the roadmap?  ...or is there a workaround?  

Thanks in advance for any feedback..

For reference, adding a config such as the following:

```javascript
var animations = {
  layout: {
    spring: {
      duration: 750,
      create: {
        duration: 300,
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.opacity,
      },
      update: {
        type: LayoutAnimation.Types.spring,
        property: LayoutAnimation.Properties.scaleXY,
        springDamping: 400,
      },
      delete: {
        type: LayoutAnimation.Types.spring,
        property: LayoutAnimation.Properties.scaleXY,
        springDamping: 400,
      },

    },
    easeInEaseOut: {
      duration: 300,
      create: {
        type: LayoutAnimation.Types.easeInEaseOut,
        property: LayoutAnimation.Properties.scaleXY,
      },
      update: {
        delay: 100,
        type: LayoutAnimation.Types.easeInEaseOut,
      },
    },
  },
};
```
Produces this unfortunate (but at least informative) error:

```
[RCTLog][tid:0x7fb46c90b3e0][RCTUIManager.m:1389]>LayoutAnimation only supports create and update right now. Config: {
    create =     {
        duration = 300;
        property = opacity;
        type = easeInEaseOut;
    };
    delete =     {
        property = scaleXY;
        springDamping = 400;
        type = spring;
    };
    duration = 750;
    update =     {
        property = scaleXY;
        springDamping = 400;
        type = spring;
    };
}

```

**Comment by brentvatne** [comment]
Also would love to see this, consolidating into one issue #1440
