### ISSUE TITLE
webview can scroll while navigation animating but scrollview cannot, can it been the same?

### ISSUE THREAD

**Issue by fakefish** [facebook/react-native#7110]
hi,

I found that webview still can scroll while navigation is in back animation, but scrollview cannot scroll while navigation in back animation. I hope webview cannot scroll too.

![2 pic](https://cloud.githubusercontent.com/assets/1334025/14701571/a2e4f740-07d8-11e6-80db-876cbe21bb6c.jpg)
in the snapshot above, the webview can still scroll, the background is an other absolute position view.

**Comment by christopherdro** [comment]
Hey @fakefish! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue if necessary or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
