### ISSUE TITLE
[Android][CLI] Package name can't contain $

### ISSUE THREAD

**Issue by radko93** [facebook/react-native#7115]
I was making a PR for #4216 and ran into [this](https://github.com/facebook/react-native/blob/master/local-cli/generator-android/index.js#L17).
As stated in [android manifest guideline](http://developer.android.com/guide/topics/manifest/manifest-element.html#package):
> The name may contain uppercase or lowercase letters ('A' through 'Z'), numbers, and underscores ('_'). However, individual package name parts may only start with letters.

`generator-android` accepts `$` but it's not allowed. Happy to submit a PR.

**Comment by grabbou** [comment]
If you could make sure the validatePackageName is 100% spec-compliant yet it does not break any existing functionality, that'd be cool!
