### ISSUE TITLE
"undefined is not an object (evaluating 'ua.match')" when importing an incompatible (browser) library.

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#7117]
I'm getting `undefined is not an object (evaluating 'ua.match')` and `Module AppRegistry is not a registered callable module` all the time and there's not much to find on 'ua.match'

Don't know how useragent is decided, but I'm on a stock Android emulator and Ubuntu 15.10.
react-native 24.1
in the emulator I get:
```
undefined is not an object (evaluating 'ua.match')
getFirstMatch
browser.js:21

detect
browser.js:30

<unknown>
browser.js:8
```
and sometimes the AppRegistry error when it's not fully loaded yet or something.

The packager also sometimes starts about 200 transforms and errors out. It did that earlier today a couple of times as well but the app still worked.

So I tracked down the offending import and it was Radium https://github.com/FormidableLabs/radium
Obviously I can't use Radium in React-native, but we're using a common core with platform specific view logic so that's why I had this.

Summarising, this issue is about clarifying the useragent error to give a more meaningful message.

**Comment by janicduplessis** [comment]
The library probably does something like
``` js
var ua = navigator.userAgent;
...
ua.match(...);
```
We polyfill navigator as an empty object so this is why userAgent is undefined. Not sure what is the best approach here to avoid this, was the stack trace not enough to figure out where the error was coming from easily?

**Comment by satya164** [comment]
You can do something like the following to prevent the crash,

```js
if (!navigator.userAgent) {
  navigator.userAgent = 'ReactNative';
}
```

@facebook-github-bot answered

**Comment by ThaJay** [comment]
Thanks for the answers.
Unfortunately the stack trace was not helpful in this case because dependencies are resolved first and the error occurred when something down the chain depends on the library, not when it's used. There was only a source code dependency in my case.

**Comment by lacker** [comment]
It seems like this question has been answered so I'm going to close this issue. Feel free to reopen it if there is some more specific information about why these answers are insufficient.
