### ISSUE TITLE
Xcode doesn't recognize linked libraries

### ISSUE THREAD

**Issue by checkraiser** [facebook/react-native#712]
I've created new project with react-native init ProjectName. Then i open project with Xcode. 
But all reactnative linked libraries in Build Phases turn Red color. What's that problem ? Because Xcode build failed. It saied /bin/sh shell script invocation error.

**Comment by brentvatne** [comment]
@checkraiser - this script invocation error occurs because you're trying to build the project with a packager instance running each time - it's a bit annoying how that works right now but you just have to be sure to close it when you want to build it again (not required to just refresh JS in simulator).

**Comment by frantic** [comment]
@checkraiser could you please copy-paste detailed error description? You can find it by clicking on error message in the left pane in Xcode

![image](https://cloud.githubusercontent.com/assets/192222/7054857/67d80ad4-ddf4-11e4-9db7-c8fa2cd678a7.png)

**Comment by frantic** [comment]
Looks like packager thing has been fixed in #758

**Comment by brentvatne** [comment]
@checkraiser - ping me if this is still an issue! thanks for reporting :smile:

**Comment by LionWY** [comment]
the same problem

`shell script invocation error`
`/Users/FOODING/Library/Developer/Xcode/DerivedData/UIExplorer-almvrjqunvqtnidajmjweosvetil/Build/Intermediates/UIExplorer.build/Debug-iphonesimulator/UIExplorer.build/Script-68CD48B71D2BCB2C007E06A9.sh: line 3: /Users/FOODING/Desktop/React: No such file or directory`
