### ISSUE TITLE
Add ability to disable on-screen warnings

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#7121]
After upgrading to RN 0.25-rc, you are going to start getting a lot of warnings, most of them will probably cover your entire screen.

What's bad about that is that you can't control the dependencies and it's going to take a while for the community to upgrade.

I would like to implement a small feature (that could ideally be cherry-picked, but that's fine) to add `Disable on-screen warnings` to DevTools that basically hides them from appearing on-screen (reporting in console still works).

WDYT? Happy to send it over.

Related discussion: #7040 

CC: @satya164 @mkonicek @ide

**Comment by javache** [comment]
There's already an option to ignore certain warnings in YellowBox: https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/YellowBox.js#L39

**Comment by janicduplessis** [comment]
This should probably be documented in http://facebook.github.io/react-native/docs/debugging.html#yellowbox-redbox. Maybe also add a note about it in the release notes too since people will probably ask about that.

**Comment by grabbou** [comment]
Ok, that's awesome. Going to send a PR with updated docs.
