### ISSUE TITLE
Chrome Debugger Console Unresponsive [0.24.1]

### ISSUE THREAD

**Issue by jeremyeaton89** [facebook/react-native#7123]
I'm surprised to not have seen anyone else complain about this yet, but yesterday we upgraded to react native 0.24.1 and now when we debug using chrome the console becomes unresponsive. Often, the console will close, too. 

node 5.9.1
npm 3.7.3

Not sure what other information is relevant to this issue. 
Please let me know! And thank you in advanced.

**Comment by grabbou** [comment]
Does it just freeze w/o doing anything? Or during console.log? Or when it hits the breakpoint? When I was releasing 0.25-rc I tested all these things and didn't find any problems at all. Might be something related to the way your application works - hence extra information required.

**Comment by jeremyeaton89** [comment]
So, it logs, initially, and then freezes so that you cannot click into the console nor receive additional logging.

**Comment by jeremyeaton89** [comment]
![screen shot 2016-04-22 at 11 39 25 am](https://cloud.githubusercontent.com/assets/2295061/14751513/15e04910-087f-11e6-8b09-f9180ac415c7.png)

**Comment by jeremyeaton89** [comment]
![screen shot 2016-04-22 at 11 39 25 am](https://cloud.githubusercontent.com/assets/2295061/14751577/512c7d9a-087f-11e6-9a9d-408e0fbbb17c.png)

**Comment by jeremyeaton89** [comment]
we're having the same problem with 0.24.0 also if that helps.. we'll of course be looking into this ourselves as well.

**Comment by bwoodmansee** [comment]
Seeing the same behavior with 0.24.1

**Comment by messense** [comment]
Seeing the same behavior with 0.30.0

**Comment by barakcoh** [comment]
Seeing the same behavior with 0.35.0

**Comment by joeferraro** [comment]
Seeing the same behavior with 0.37.0

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
