### ISSUE TITLE
"Runtime not ready for debugging" running off real iPhone

### ISSUE THREAD

**Issue by fungilation** [facebook/react-native#7131]
I'm getting the redbox "Runtime not ready for debugging" while testing on real device. It's all fine in simulator.

I see on [RN's doc](https://facebook.github.io/react-native/docs/debugging.html) that I should update ```RCTWebSocketExecutor.m``` from "localhost" to my local server IP. I've already done that in AppDelegate.m and running the package on real device works fine. But there is no ```RCTWebSocketExecutor.m``` in my current version of RN! (0.24) Is this a case of file reshuffling from older RN version and the file just doesn't exist anymore? If so, what/where should the IP be configured for debugging from running on a real iOS device?

Thanks for advice, and also RN's doc can use updating too perhaps regarding ```RCTWebSocketExecutor.m```.

PS. Related to #297 but not for simulator, in which case the default localhost works.

**Comment by grabbou** [comment]
Looks like it's there -> https://github.com/facebook/react-native/blob/master/Libraries/WebSocket/RCTWebSocketExecutor.m#L54

**Comment by alokverma65977** [comment]
Checkout the Certificate are installed of u run on the iPhone device.

**Comment by jpca999** [comment]
im getting this issue on iphone simulator, how did you guys solved this ?
