### ISSUE TITLE
RecyclerViewBackedScrollView can not inherit refreshControl in android

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#7134]
Hi，when I use ListView ，set the props renderScrollComponent use RecyclerViewBackedScrollView，ios‘s refreshControl is work，but android not work！is that a bug？

 renderScrollComponent={props => <RecyclerViewBackedScrollView {...props} refreshControl={refreshControll} />

**Comment by janicduplessis** [comment]
`RecyclerViewBackedScrollView` doesn't implement refresh control, it would be pretty simple to do by doing the same thing as `ScrollView`.

**Comment by tegon** [comment]
I've added a pull request which adds the refresh control to `RecyclerViewBackedScrollView`: #8639

**Comment by ide** [comment]
Closing since PR was merged.
