### ISSUE TITLE
why the <text> has white background  when under the <Image>

### ISSUE THREAD

**Issue by sunny635533** [facebook/react-native#7144]
-----"##<Image source={require('./img/background.png')} style={{flex:1,width:Dimensions.get('window').width,flexDirection:'column'}}>
            <Text style={styles.title}>
                Showreel
            </Text>
</Image> " ------
like the code,i don't know why?Why the <text> has white background  when under the <Image>?

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by Naoto-Ida** [comment]
Just a guess, but I think he means having a <Text/> inside of a <Image /> block. I'm sure <Text /> has a white background by default, but it's noticeable when combined with other things.

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-9** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
