### ISSUE TITLE
Pod installation problem in react-native 0.24.1

### ISSUE THREAD

**Issue by zh-wowtv** [facebook/react-native#7149]
Got the following error message:

```
[!] Invalid `React.podspec` file: no implicit conversion of nil into String.

 #  from /Users/Public/Projects/pall/node_modules/react-native/React.podspec:3
 #  -------------------------------------------
 #  
 >  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 #  
 #  -------------------------------------------
 ✘ user@macbookpro  /Users/Public/Project/pall/ios  
```

It's no problem in 0.23

**Comment by grabbou** [comment]
Works fine on 0.25-rc
```
Analyzing dependencies
Fetching podspec for `React` from `../../node_modules/react-native`
```
Would you mind checking?

**Comment by mikefowler** [comment]
Verified that this is still occurring (on my machine) with 0.25-rc. 

A short-term workaround is to change `__dir__` to `File.dirname(__FILE__)`, but my Ruby knowledge ends there.

**Comment by mikefowler** [comment]
This is anecdotal, but I just updated my Ruby installation from `2.1.2 => 2.3.0` and this issue was resolved.

**Comment by zh-wowtv** [comment]
@mikefowler Thanks. I did:

- Upgrade ruby from 2.1.2 to 2.3.0
- Upgrade react-native from 0.24.0 to 0.25-rc
- Upgrade cocoapods 

> gem install cocoapods --pre

- Reset pod

> pod repo remove master
> pod setup
> pod install

Everything's fine then.

**Comment by qq644531343** [comment]
By the way , how to "Upgrade react-native from 0.24.0 to 0.25-rc" ?  thanks!

**Comment by qq644531343** [comment]
## When I copy the forder "node_modulesl" to my Xcode workspace and pod it  as bellow:

```
pod 'React',            :path => 'TBApp-OC/AppLib/libPod/node_modules/react-native',
                    :subspecs => [ 'Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket',]
```
## 
It occus error when I pod install as bellow:

```
Fetching podspec for `React` from `/Users/libo/Desktop/test/HelloReact/node_modules/react-native`

[!] Invalid `React.podspec` file: No such file or directory @ rb_sysopen - /Users/libo/Desktop/test/TBApp/TBApp-React/Pods/Local Podspecs/package.json. Updating CocoaPods might fix the issue.

 #  from /Users/libo/Desktop/test/TBApp/TBApp-React/Pods/Local Podspecs/React.podspec:3
 #  -------------------------------------------
 #  
 >  package = JSON.parse(File.read(File.join(__dir__, 'package.json')))
 #  
 #  -------------------------------------------

```

**Comment by JatinKinra** [comment]
When I added fbsdk in my project, I got errors like -
Warning: Native component for "RCTFBLikeView" does not exist
2016-06-21 22:27:38.898 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RCTFBLoginButton" does not exist
2016-06-21 22:27:38.899 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RCTFBSendButton" does not exist
2016-06-21 22:27:38.900 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RCTFBShareButton" does not exist

To solve this I went through this pod method -
https://github.com/facebook/react-native-fbsdk/issues/126

Now, when I run command "pod install", I am getting this error - 
No podspec found for react-native-fbsdkcore in ../node_modules/react-native-fbsdk/iOS/RCTFBSDK/core".

Can anybody tall what is wrong here ?

This is my pod file - 

platform :ios, ‘7.0’
use_frameworks!

xcodeproj ‘/Users/ais/Netizen/ios/Netizen.xcodeproj’

target ’Netizen’ do
  source ‘https://github.com/CocoaPods/Specs.git’
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '/Users/ais/Netizen/node_modules/react-native'
  pod 'react-native-fbsdkcore', :path => ‘../node_modules/react-native-fbsdk/iOS/RCTFBSDK/core’
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/RCTFBSDK/login’
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/RCTFBSDK/share’
end

target ‘NetizenTests' do

end
