### ISSUE TITLE
NavigationLegacyNavigator cause redux re-render all container components by any action

### ISSUE THREAD

**Issue by chenxiaohu** [facebook/react-native#7150]
I replace old navigator to NavigationLegacyNavigator, then any redux action re-rend all the container components.

**Comment by chenxiaohu** [comment]
[src.zip](https://github.com/facebook/react-native/files/232108/src.zip)

toggle the navigator  can see the re-render...

**Comment by lacker** [comment]
I think this issue needs more info - what is a sample project, ideally a link to rnplay.org, what did you expect to see, what did you see instead. I'm going to close this issue but feel free to reopen it if you do have more information.
