### ISSUE TITLE
ListView onEndReached call twise when init

### ISSUE THREAD

**Issue by charlesluo2014** [facebook/react-native#7159]
when I use componentWillMount to load data,and invoke setState,the onEndReached call twice,the expected result is Zero!why I set the state can effect it?

async componentWillMount(){

        var onInitLoadData=this.props.onInitLoadData;
        var refreshData;
        if(onInitLoadData){
            refreshData=await onInitLoadData();
        }

        if(!refreshData){
            refreshData=[];
        }
        refreshData=refreshData;
        if(refreshData.length>200){//only 200 datas
            refreshData=refreshData.slice(refreshData.length-200,refreshData.length)
        }

        if(refreshData.length>0) {
            this.setState({
                isRefreshing: false,
                datas: refreshData,
                dataSource: initDatasource.cloneWithRows(refreshData),
                currentPage:0
            });
        }else{
            this.setState({
                isRefreshing: false,
                datas: refreshData,
                currentPage:1
            });
        }

    }

2016-04-23 01:18:32.292 [info][tid:com.facebook.react.JavaScript] _onEndReached=================call====================
2016-04-23 01:18:32.307 [info][tid:com.facebook.react.JavaScript] _onEndReached=================call====================

**Comment by grabbou** [comment]
Keep in mind that your `componentWillMount` function is async. That means initially ListView will be rendered with no rows (empty) and if you e.g. attempt to scroll it or interact with it in anyway, it will trigger the `onEndReached` callback.

Second time that's called is when you render with data loaded but the amount of rows is smaller than what can fit on screen, which means the end was automatically reached.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by Empact** [comment]
See also #6782
