### ISSUE TITLE
[pod] Undefined is not an object (evaluating `navigator.geolocation.watchPosition`)

### ISSUE THREAD

**Issue by LeoLeBras** [facebook/react-native#7160]
I use version **0.24.1** of React Native.

I get this error only with Chrome Debugging disabled (with Chrome Debugging enabled, it works fine) :

<img width="406" alt="capture d ecran 2016-04-22 a 20 18 20" src="https://cloud.githubusercontent.com/assets/856188/14750983/f29aa4e8-08c7-11e6-8090-bc4c41cccf65.png">

My Podfile :
```
platform :ios, '7.0'
#use_frameworks!

target 'Wino' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => [
    'ART',
    'RCTImage',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'RCTAdSupport',
    'RCTGeolocation',
    'RCTPushNotification',
    'RCTSettings',
    'RCTVibration',
    'RCTText',
    'RCTWebSocket'
  ], :path => '../node_modules/react-native'
  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
end

target 'WinoTests' do

end
```

**Comment by christopherdro** [comment]
@LeoLeBras Any chance your using https://github.com/skellock/reactotron?

**Comment by LeoLeBras** [comment]
@christopherdro Yes, that was it. Thank you ! :)

**Comment by christopherdro** [comment]
Fixed via https://github.com/skellock/reactotron/commit/bfbc5102b8dde44094075399dfb45b2319ff6d3a
