### ISSUE TITLE
Touch hit detection on native can be out of sync with pointerEvents if JS is slow

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#7164]
One result of this is that Navigator / NavigationExperimental may push routes multiple times when tapped quickly. This is a little bit hard to explain so see a repro case for iOS and Android here: https://github.com/brentvatne/touch-handling-and-pointer-events-bug

The repro is essentially just this:

``` javascript
  _handleTap = () => {
    if (this.state.tapCount === 0) {
      burnCPU(2000);
    }

    this.setState({tapCount: this.state.tapCount + 1});
  };

  render() {
    return (
      <View pointerEvents={this.state.tapCount > 0 ? 'none' : 'auto'}>
        <TouchableHighlight onPress={this._handleTap}>
          <Text>
            Tap me!
          </Text>
        </TouchableHighlight>

        <View>
          <Text>
            {this.state.tapCount} taps
          </Text>
        </View>
      </View>
    );
  }
```

You would expect based off of reading the code that tapCount can never be greater than 1, but in reality onPress is called as many times as you tap while `burnCPU` is running for 2 seconds.

![screen shot 2016-04-22 at 2 40 43 pm](https://cloud.githubusercontent.com/assets/90494/14755675/dc5aa810-0898-11e6-8ae5-2fab20b612e4.png)

cc @skevy who noticed this and @vjeux to see what he thinks

**Comment by christopherdro** [comment]
@brentvatne Browsing some old issue with no comments.

Should we still keep this one open?

**Comment by vangberg** [comment]
This is still an issue for me on 0.34 at least.

**Comment by anttimo** [comment]
Also having this issue, currently using 0.33.0.

**Comment by zachrnolan** [comment]
Issue for me as well, using 0.39

**Comment by larryranches** [comment]
@brentvatne I am also experiencing this issue as well on RN 0.39.0 on both ios on android. If tapped multiple times on a slow network, it will actually crash the app on Android. 

Is there any elegant solution to know if a navigation transition is taking place/in progress so that we are able to disable buttons or render an Overlay which will make the view un-clickable and avoid this issue? I'm also using NavigationCardStack is that helps.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/touch-hit-detection-on-native-can-be-out-of-sync-with-pointerevents-if-js-is-slo
