### ISSUE TITLE
react-native-0.24.1,when i run the command "npm install", why the node_modules  has much more files than when we use @0.23.1

### ISSUE THREAD

**Issue by xcchcaptain** [facebook/react-native#7166]
windows 10 pro 64bit
node 4.4.3
npm 3.8.6
when i use @0.23.1
![image](https://cloud.githubusercontent.com/assets/5080022/14758621/f288a402-0938-11e6-901a-ee47bd112529.png)

when i use @0.24.1
![image](https://cloud.githubusercontent.com/assets/5080022/14758623/0f64b5fc-0939-11e6-86bc-a93f7fb3557e.png)

why they are so diffrent ,am'i get something wrong?

**Comment by ide** [comment]
This is how npm 3 works and isn't a bug. Maybe you used npm 2 before.
