### ISSUE TITLE
[CameraRoll] RCTCameraRollMananger should support fetching videos

### ISSUE THREAD

**Issue by jsierles** [facebook/react-native#717]
Currently this module only supports fetching information about photos. It would be nice to have able to use ALAssetsFilter.allAssets or .allVideos. What would be the best way to go about supporting this?

**Comment by browniefed** [comment]
As of .60 it appears that this is solved.
"Support fetching videos from Camera Roll"
Link for reference https://github.com/facebook/react-native/releases/tag/v0.6.0-rc

@brentvatne already fixed
