### ISSUE TITLE
Can not use "child_process"

### ISSUE THREAD

**Issue by LzxHahaha** [facebook/react-native#7170]
I try to write `var cp = require("child_process")` and get an error: `Requiring unknown module "child_process"`, it's that mean I can't use this module in react native?

RN vertion `0.23.0`, Node `5.11.0`

Windows and OSX got the same error.

**Comment by ide** [comment]
child_process and Node modules are not supported. It's sort of like how APIs like document.createElement don't exist in Node, and child_process doesn't exist in a browser -- React Native is a different environment.
