### ISSUE TITLE
ios device id changes each time, from 0.23

### ISSUE THREAD

**Issue by anysome** [facebook/react-native#7173]
```
react-native run-ios 
```
Every time run this command, the app install id changes. Version before 0.23 works well.

**Comment by grabbou** [comment]
Can you provide some details? Is this a bug? What you mean by `app install id`? Do you mean device ID? Identifier for vendor?

**Comment by anysome** [comment]
Yes, device ID, iOS app well generate new one when reinstall. 
It seems “react-native run-ios” will reinstall the app.
I'm using react-native-device-info to get the device ID, after upgrade rn, ID changes every time.

**Comment by grabbou** [comment]
Checked the library and `uniqueId` is deviceIdentifierForVendor which will change every time you reinstall the app and I think that's the ID I think you might be using. 

We could add a flag to `run-ios` to not install the app, just run, or check that if possible. 

Is that the `id` you meant? Could you link to specific line in that library that changes for you?

**Comment by anysome** [comment]
That's the right ID I used.
Sorry, I don't known how to setup the script, node script is a difficulty.

I just work around by stored and restored the ID when app is starting to run.

**Comment by grabbou** [comment]
Thanks - going to send a PR in a bit

**Comment by lacker** [comment]
I can't tell if there ever was a PR here. Since there's a workaround anyway and it's been idle for a while, I'm going to close this issue. I think it is fixed though. Feel free to reopen if someone can repro this bug from a new RN version.
