### ISSUE TITLE
How to pop a new view?

### ISSUE THREAD

**Issue by iceNuts** [facebook/react-native#718]
When I have a root component view to run, and I have a button, if I press the button, a new view should pop up like present view controller but it is still react native defined view. I am just wondering how to make this happen without a navigation container?

Thanks.

**Comment by Kureev** [comment]
There is [a nice plugin](https://github.com/brentvatne/react-native-modal) for that. Of course if you want, you can use `<Navigator>` and configure each route "by hand" (but as you mentioned, it's about `<Navigator>` and you don't want it).

**Comment by DiegoRBaquero** [comment]
Use a callback from the view containing the button to the parent and using a switch in the render display the new view.

View containing the button: <SignUpView onDone={(pUser) => this.setState({user: pUser})}/>

Render function of the parent:
if(this.state.user !== undefined) {
      return (
        <ChatView />
      );
    } else {
      return (
        <SignUpView onDone={(pUser) => this.setState({user: pUser})}/>
      )
    }

Call when button clicked: parent.props.onDone(user);

This is just an example, adjust to your needs.

**Comment by ericvicenti** [comment]
You can do this with [Navigator](http://facebook.github.io/react-native/docs/navigator.html#content), [community components](https://github.com/ericvicenti/react-native-community#navigation), or normal `<View>`s
