### ISSUE TITLE
TabBarIOS paddingBottom Bug

### ISSUE THREAD

**Issue by hnordt** [facebook/react-native#7188]
Hello.

I'm using React Native 0.24.1 on Mac.

`TabBarIOS` has different top and bottom padding:

<img width="487" src="https://cloud.githubusercontent.com/assets/1625399/14764764/d5e6ba52-099a-11e6-80ba-5fec904e9b80.png">

I tried to fix it with adding `paddingBottom` to `TabBarIOS` and `TabBarIOS.Item`, but of course it doesn't worked.

Is it a bug?

Here is my code:

```jsx
import React, { AppRegistry, Component, StyleSheet, TabBarIOS, Text, View } from 'react-native'

class App extends Component {
  renderContent(pageText) {
    return (
      <View style={styles.tabContent}>
        <Text>{pageText}</Text>
      </View>
    );
  }

  render() {
    return (
      <TabBarIOS>
        <TabBarIOS.Item systemIcon="history">
          {this.renderContent('Tab 1')}
        </TabBarIOS.Item>
      </TabBarIOS>
    )
  }
}

const styles = StyleSheet.create({
  tabContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  }
})

AppRegistry.registerComponent('App', () => App)
```

**Comment by grabbou** [comment]
I don't think it's a bug - if you will take a look at all built-in iOS apps where this component is used, the paddings are like that. The `style` you pass to `item` is actually a style of the page, not the tab bar item itself.

**Comment by hnordt** [comment]
Thank you @grabbou
