### ISSUE TITLE
Packager bug with ES2015 exports

### ISSUE THREAD

**Issue by radev** [facebook/react-native#7189]
Looks like when ES2015 export (default or named) is used then multiple lines are combined into one.

E.g. following code
```javascript
import { View } from 'react-native';

const x = View.propTypes.style;

export default function Test() {
  return <View />;
}
```
 
is compiled to 

```javascript
__d(776 /* TestApp/src/test.js */, function(global, require, module, exports) {Object.defineProperty(exports,"__esModule",{value:true});exports.default=



Test;var _reactNative=require(11 /* react-native */);var x=_reactNative.View.propTypes.style;function Test(){
return React.createElement(_reactNative.View,null);}
});
```
Multiple source lines are collapsed to one and this makes debugging a lot harder as often we're unable to place breakpoints where needed.

If I convert export to use CommonJS:
```javascript
import { View } from 'react-native';

const x = View.propTypes.style;

module.exports = function Test() {
  return <View />;
};
```
then it compiles to:
```javascript
__d(776 /* TestApp/src/test.js */, function(global, require, module, exports) {var _reactNative=require(11 /* react-native */);

var x=_reactNative.View.propTypes.style;

module.exports=function Test(){
return React.createElement(_reactNative.View,null);};
});
```
You can see that x assignment is on it's own line.

This is on react-native version 0.24.1. Linux & Android

**Comment by satya164** [comment]
cc @davidaurelio @martinbigio

**Comment by radev** [comment]
I've tested separately using babel-cli and babel-preset-react-native.

Reduced test case:
**npm install babel-cli babel-preset-react-native**

**.babelrc**
`{"presets": ["react-native"]}`

**test.js**
```javascript
const x = false;

export default function Test() {
  return x;
}
```

**./node_modules/.bin/babel test.js**
```
Object.defineProperty(exports,"__esModule",{value:true});exports.default=

Test;var x=false;function Test(){
return x;}

```

When I comment out `compact: true` and `retainLines: true` in https://github.com/facebook/react-native/blob/855c0cc25ea0456fa5813cc65fce09786b557d0f/babel-preset/configs/main.js#L15,L42 code returns to:
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = Test;
var x = false;

function Test() {
  return x;
}

```

I guess this is necessary because of sourceMaps: false.

**Comment by mroswald** [comment]
Is that related to #6946 ? Btw - sourceMaps should be able to handle this since they can map not only bundle:line to source:line (they do bundle:line.col => source:line.col, right?)

**Comment by radev** [comment]
https://github.com/facebook/react-native/blob/8edc35004ccaa450187179c65156906a55e0475e/packager/react-packager/src/Bundler/Bundle.js#L234

Looks like when minify is false bundler is expecting 1 to 1 line mapping and doesn't support column mapping.

**Comment by davidaurelio** [comment]
The plan is to give up on line-to-line mapping and using babel’s AST as long as possible. No idea when that will happen.

**Comment by mroswald** [comment]
@davidaurelio can you please give more information about that planned change? Is there anyone already working on that?

**Comment by davidaurelio** [comment]
There’s nobody currently working on that. 

Currently we do stuff like wrapping modules into `__d(…)` and replacing module IDs as operation on the source code (as in: string). That can lead to small errors in the generated source maps.

Using babel’s AST for all of that and generating code only at the end of the process should fix this.

**Comment by will-ockmore** [comment]
Are there any current workarounds for this issue (or changes in the works)?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/packager-bug-with-es2015-exports

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
