### ISSUE TITLE
Is is possible to POST binary data?

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#7190]
I need the body of an http post to contain binary data.  I don't mean a file upload (although it is effectively a file upload).  The server is not expecting a mutlipart form data body, just a stream of bytes.

**Comment by grabbou** [comment]
The following works fine for me when uploading app store receipts:
```js
fetch('http://foo.com/bar', { 
   method: 'POST', 
   headers: {
     'Content-Type': 'application/octet-stream',
   },
   body, // <some binary data you get from e.g. app store receipt,
})
```

**Comment by npomfret** [comment]
Thanks.  My data is a file on the phone.  Is there a way to provide a uri to the file?

**Comment by grabbou** [comment]
I think you could use `react-native-fs` to get it first (you can probably do better by writing custom native code to stream it directly), but should work in your case.

**Comment by npomfret** [comment]
Thats what I thought :(  Never written a live of Objective C in my life.  Time to learn I guess.

**Comment by grabbou** [comment]
In case you have any Q, feel free to reach out to us on Discord ;) And.... good luck!
