### ISSUE TITLE
[Android] Android 5.0 Scrolling WebView drops fps

### ISSUE THREAD

**Issue by cihancil** [facebook/react-native#7191]
I use RN version 0.24.0.

When I use Android 5.0+, WebView performance drops significantly. Under Android 5.0 it works fine. 

Problem occurs when WebView has more height than the screen. When user scrolls, JS and UI FPS drops to 0 - 1 FPS

I tried this at rnplay.org. The link is below. As soon as I scroll, I get these messages at console:

> Attempt to remove non-JNI local reference, dumping thread

https://rnplay.org/apps/ljXmyg

**Comment by christopherdro** [comment]
Hey @cihancil! Closing this issue for now since it hasn't had any activity in a while.

Please feel free to re-open this issue if necessary or create a ticket on [Product Pains](https://productpains.com/product/react-native/) so that other people can vote on it.
