### ISSUE TITLE
[Android] Unable to rotate orientation on release apk, but working on development

### ISSUE THREAD

**Issue by holyxiaoxin** [facebook/react-native#7195]
I was using https://github.com/yamill/react-native-orientation and it was working well in development. The screen was able to rotate on different navigator: scene. 

After creating the release package via `./gradlew assembleRelease`, and installing it, I was not able to achieve the same result. The device was able to lock on portrait, but unable to rotate to landscape. It seems that there is some optimisation that's causing the rotating of orientation to fail.

I've tried on the following react-native versions: `v0.25.0-rc` && `v0.25.0-rc5` && `v0.24.0`

**Comment by satya164** [comment]
Please file the bug report under - https://github.com/yamill/react-native-orientation

Thank you :)
