### ISSUE TITLE
Development server not start automatically when I start iOS project

### ISSUE THREAD

**Issue by zh-wowtv** [facebook/react-native#7198]
My development server doesn't start automatically when I start iOS project from either Xcode or i command line:

> react-native run-ios

When I start project from Xcode, I got the following error message:

> URL: http://localhost:8081/index.ios.bundle?platform=ios&dev=true
> 2016-04-24 22:15:21.838 [error][tid:main][RCTWebSocketManager.m:84] WebSocket connection failed with error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

My Info.plist:

<img width="523" alt="2016-04-24 10 42 32" src="https://cloud.githubusercontent.com/assets/18462946/14768199/e9abce46-0a6d-11e6-93f7-e0cc916e1075.png">

What could be the problem? Thanks.

**Comment by zh-wowtv** [comment]
Any suggestion? Thanks.

**Comment by kingr** [comment]
Make sure you don't have any other instances of the project running in another terminal.

**Comment by zh-wowtv** [comment]
There is no other instance. I have to start the development server manually everytime by:

> npm start

By the way, my iOS project is using Cocopods. Before that everything seems to be fine.

**Comment by sasikg** [comment]
I am also facing the same problem after using Cocoapods.

**Comment by bendellarocco** [comment]
@sasikg are you opening the .xcworkspace file instead of the .xcodeproj file after using cocopods?

**Comment by sasikg** [comment]
i am opening .xcworkspace file only, it works after i use npm start.

**Comment by kfiroo** [comment]
Having the same issue.
Everything worked well before I started using .xcworkspace.
Any idea where is this configured or how to resolve?

**Comment by wasabia** [comment]
i have the same issue.

it was beacuse my phone can not visit my computer, even if they are on same wifi ....  😢 

use safari on your phone open http://computer ip:8081/index.ios.bundle check it...

**Comment by rogchap** [comment]
This is configured in the React project as a Build Phase:

![image](https://cloud.githubusercontent.com/assets/270252/15461569/322a06a4-20ff-11e6-958b-78dcb6639b25.png)

If it's not working try adding the script to the workspace:

```bash
if nc -w 5 -z localhost 8081 ; then
  if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
    echo "Port 8081 already in use, packager is either not running or not running correctly"
    exit 2
  fi
else
  open "$SRCROOT/../packager/launchPackager.command" || echo "Can't start packager automatically"
fi
```

**Comment by max-mykhailenko** [comment]
@rogchap I don't have `run scripts` section. Packager starts not every time when launch `react-native run-ios`

**Comment by rogchap** [comment]
@max-mykhailenko Are you sure?? The `run scripts` is part of the React product library (not your project app)
Are you using CocoaPods for anything?

Ps. I normally run the packager independently from running automatically from the script... this gives you more control as you can easily start and stop the packager when required, without re-building the iOS native code.
Just do an `npm start` from the root of your react-native project; this will start the packager, then you can launch the app via `react-native run-ios`.

**Comment by lacker** [comment]
It seems like this isn't the sort of thing that people can reproduce per se, and it's more of an occasional issue where you need to go turn things off and on again. I'm going to close this issue but feel free to reopen if you have a specific case where you can reproduce a bug.
