### ISSUE TITLE
Bundler doesn't import index.js if require is on a Directory

### ISSUE THREAD

**Issue by boopathi** [facebook/react-native#72]
```
- Project
  \ _ Component
       \ _ index.js
  \ _ App.js
```

`App.js` is the entry point

```js 
// App.js
var Component = require('./Component');
```

doesn't import `index.js` automatically. Had to manually specify 

```js
// App.js
var Component = require('./Component/index');
```

**Comment by nmn** [comment]
+1 for normal commonJS instead of the `@provides` docblock. The node version of commonJS and custom JS build scripts would be the best case scenario.

**Comment by amasad** [comment]
I actually forgot to close this issue. If lib is a dir with index.js `require('./lib')` will be the same as `require('./lib/index.js')`.

And you don't have to use `@providesModule`. There are still differences from node modules and we'll work towards that, but I'm also happy to fix any differences you see in the near term

**Comment by vjeux** [comment]
Actually, please don't use @providesModule. This is an internal convention that shouldn't be exposed to developers.
