### ISSUE TITLE
[NavigatorIOS] Support hidesBottomBarWhenPushed in NavigatorIOS routes

### ISSUE THREAD

**Issue by thewei** [facebook/react-native#720]
Sometimes, i need the TabBarIOS hided when i use Navigator push a new view, how can i do it in react-native?

**Comment by vjeux** [comment]
Can you be more specific. Do you have screenshots/mocks of what you want the flow to look like?

**Comment by thewei** [comment]
Like this: http://modao.io/app/KHfXnjXLUZuNdH0IASNI
I do not know how to hide the TabBarIOS when i use Navigator push a new view.

**Comment by iostalk** [comment]
Wei shen me  the me zuo

**Comment by gabro** [comment]
I believe the what @thewei is talking about is the `hidesBottomBarWhenPushed` property of of the native `UIViewController`.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instp/UIViewController/hidesBottomBarWhenPushed

**Comment by thewei** [comment]
@gabro yes

**Comment by nickhudkins** [comment]
:+1:

**Comment by bogdantmm92** [comment]
+1

**Comment by maplebaby** [comment]
Is it solved?

**Comment by JonasJonny** [comment]
+1

**Comment by songqingkun** [comment]
how to solve it

**Comment by thewei** [comment]
@songqingkun I don't know

**Comment by thewei** [comment]
@vjeux

**Comment by songqingkun** [comment]
I see facebook group can hide.react native can't hidesBottomBarWhenPushed?

**Comment by songqingkun** [comment]
have you qq my 601307105

**Comment by JonasJonny** [comment]
To hide navigation top bar use simple Navigator, not NavigatorIOS.
Or https://github.com/Kureev/react-native-navbar
If you will not set navigationBar, it will be hidden.

For tabBar you have to have at least two Navigators.
One as primary and second one with tab bars.
Then you can use navigator.parentNavigator to target primary Navigator without tab bars and push your view there.

**Comment by songqingkun** [comment]
please give me a demo .thank you.I don't find similar demo with github.

**Comment by JonasJonny** [comment]
I am sorry but I don't have a time for that.
Read the docs and issues with tabBar and Navigator.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jxintang** [comment]
is it solved?

**Comment by atlas1119** [comment]
solved？

**Comment by tsenable** [comment]
@thewei 
Just put <Tabbar> in the <NavigatorIOS>

Home render:
</TabBarIOS>
 <TabBarIOS.Item
          title="我"
          }}>
        </TabBarIOS.Item>
      </TabBarIOS>


<NavigatorIOS
      style={{flex:1}}
      itemWrapperStyle={{flex:1}}
      initialRoute={{
        title: "出发",
        leftButtonTitle:"北京",
        component:Home,
        passProps:{
        }
      }}/>

**Comment by yangaqi** [comment]
@facebook-github-bot-3 solved?

**Comment by thewei** [comment]
@tsenable Yes, you are right. I write a component like web router to use Navigator now, It can manage the pages better. It support hidesBottomBarWhenPushed. 

@yangaqi @atlas1119 @jxintang @songqingkun @maplebaby
the repo: https://github.com/thewei/react-native-navigator
you can checkout the example

**Comment by pranjaltech** [comment]
Any solution here, guys? It still doesn't appear to be solved.

**Comment by DickyT** [comment]
@pranjaltech You can try [this](https://github.com/DickyT/react-native-tabbar-navigator)
![react-native-tab](https://cloud.githubusercontent.com/assets/4535844/10964643/bcab5856-837e-11e5-8995-54dc21cac68b.gif)

**Comment by jxintang** [comment]
@DickyT 
thanks,i will give a try

**Comment by pranjaltech** [comment]
@DickyT thanks, will check it out.

**Comment by DickyT** [comment]
@pranjaltech @jxintang no problem, this solution wasted me 2 nights LOL. Feel free to create new issues if you find something not working :-)

**Comment by thewei** [comment]
@pranjaltech https://github.com/thewei/react-native-navigator   react-native-navigator can hide bottomBar too
