### ISSUE TITLE
auth params in image urls don't work in android

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#7200]
If I have an image url like _http://**admin:pass@**host/image.jpg_ it appears that the username and password get stripped from it by the <Image> component.  Is this by design?

**Comment by grabbou** [comment]
I would say it probably gets striped out at some point -> if you could do some debugging by putting breakpoints here and there in this method https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L261 - it will probably tell you more.

Sounds like a small bugfix

**Comment by npomfret** [comment]
I've narrowed it down to an android bug, but I can't find the problem.  I think what's supposed to happen when you specify a username and password in the url, is that an _authorization_ header gets created with a base64 encode of the credentials.  At least that's what it looks like my browser does.

It seems that the Android java client isn't doing this.  I've stepped though the code and nowhere does it explicitly remove that text from the url.  I guess its just ignoring it and not creating the auth header.

**Comment by npomfret** [comment]
It might be the OkHttp library not supporting basic auth: https://github.com/square/okhttp/issues/2143

**Comment by jhack32** [comment]
It could also be the image size, when you console logged the url, does it show the url you're expecting? If it does, you can check the adb logs to see if it gives you an image too big error. adb logcat -t 500 to see the logs. If you do see the error, the image will need to be resized

**Comment by npomfret** [comment]
Its not the image size. OkHttp doesn't honour the Basic auth pattern, and Fesco doesn't put the auth headers in (in android at least).  I don't know which is incorrect, maybe both?   The problem doesn't happen on IOS.

An incorrect image size wouldn't result in a 401.

**Comment by jhack32** [comment]
You should check the adb logs and see what the error is, it'd tell you on there. It should also have the link somewhere in the logs.

**Comment by npomfret** [comment]
I think that it's going to be addressed in the OkHttp library. https://github.com/square/okhttp/issues/2143

**Comment by grabbou** [comment]
Feel free to close and thanks for digging into that. There's an issue in this repo about okhttp upgrading (there are some blockers on FB end). So if that ends up being fixed by them and released in next version - please reference it :)

**Comment by npomfret** [comment]
Its not being fixed by them unfortunately.  I'm not sure what do do now.  There's a proposed [solution](https://github.com/square/okhttp/issues/2143) but for some reason they won't implemented it.  Could it be added to RN?

**Comment by lacker** [comment]
Yeah, this is just pending on that Fresco upgrade and getting it in. I'm going to close this issue because I think we are already sufficiently tracking problems with the old fresco, thanks for reporting this!
