### ISSUE TITLE
[Android] Redundant onLayout event

### ISSUE THREAD

**Issue by hayeah** [facebook/react-native#7202]
Sample App: https://rnplay.org/apps/L_-nNQ

I am using a `RootView` component to detect device rotation, but when animating an absolutely positioned child View in the class hierarchy, the RootView is getting redundant layout events.

``` js
<RootView onLayout={onDeviceRotation}>
   <Animated.View>
   </Animated.View>
</RootView>
```

On Android, `onDeviceRotation` gets a layout event for each frame (when the child view changes). On iOS, `onDeviceRotation` is called only on initial layout.

Digging into the source code, I found that:
- On iOS, if a view is dirtied but if its frame doesn't change, then onLayout doesn't happen.
- On Android, if a view is dirtied but if its frame doesn't change, onLayout DOES happen.

![sample_app___react_native_playground](https://cloud.githubusercontent.com/assets/50120/14769956/6b46ee86-0a19-11e6-9ec5-62ad12645a56.jpg)

The relevant code is below.
## iOS Side

RCTUIManager dispatches onLayout event for views that received new frames.

See: https://github.com/facebook/react-native/blob/02578df4f731b411b7b0be5f5dd83bd7233d2800/React/Modules/RCTUIManager.m#L550-L567

``` objc
  for (RCTShadowView *shadowView in viewsWithNewFrames) {
    ...
    if (shadowView.onLayout) {
      CGRect frame = shadowView.frame;
      shadowView.onLayout(@{
        @"layout": @{
          @"x": @(frame.origin.x),
          @"y": @(frame.origin.y),
          @"width": @(frame.size.width),
          @"height": @(frame.size.height),
        },
      });
    }
```

RCTShadowNodes checks if frame changed, it not, don't add the view to `viewsWithNewFrames`, thus preventing onLayout event to get dispatched.

See: https://github.com/facebook/react-native/blob/02578df4f731b411b7b0be5f5dd83bd7233d2800/React/Views/RCTShadowView.m#L152-L155

``` objc
if (!CGRectEqualToRect(frame, _frame)) {
  _frame = frame;
  [viewsWithNewFrame addObject:self];
}
```
## Android Side

Android always dispatch an event if the layout is dirtied. In our case, the child view dirties the parent. We can do something similar as iOS, by checking if the frame changed before dispatching an event.

See: https://github.com/facebook/react-native/blob/02578df4f731b411b7b0be5f5dd83bd7233d2800/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIImplementation.java#L729-L744

``` java
cssNode.dispatchUpdates(
          absoluteX,
          absoluteY,
          mOperationsQueue,
          mNativeViewHierarchyOptimizer);

      // notify JS about layout event if requested
      if (cssNode.shouldNotifyOnLayout()) {
        eventDispatcher.dispatchEvent(
            OnLayoutEvent.obtain(
                tag,
                cssNode.getScreenX(),
                cssNode.getScreenY(),
                cssNode.getScreenWidth(),
                cssNode.getScreenHeight()));
      }
```

Specifically, we can change `dispatchUpdates` to return false if frame didn't change, and avoid dispatching the onLayout event.
---
- [x] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [x Provide **screenshots** where appropriate
- [x] What's the **version** of React Native you're using? 0.24.1
- [x] Does this occur on iOS, Android or both? Inconsistency between Android and iOS.
- [x] Are you using Mac, Linux or Windows? Mac

**Comment by hayeah** [comment]
fix  https://github.com/facebook/react-native/pull/7250

**Comment by mkonicek** [comment]
I asked on Twitter and there's a module to detect screen rotation properly, you might want to use that instead:
https://github.com/walmartreact/react-native-orientation-listener

Your PR https://github.com/facebook/react-native/pull/7250 might still make sense though (let's wait for others to comment).

**Comment by satya164** [comment]
@mkonicek It wasn't very usable on Android last time I tried it though - https://github.com/walmartreact/react-native-orientation-listener/issues

**Comment by erikatg** [comment]
I ran into this as well while evaluating different methods of detecting orientation change. There's various problems (at least for android) with the orientation-plugins out there.

**Comment by thoblr** [comment]
@mkconicek This issue causes problem on other cases than just orientation changes. For example, I've experience performance issues related to redundant layout events when animating a parent to a view that has on layout. In the app I'm working on I use onLayout to setState and this is causing the Android version to re-render component tree during animation and in turn causing animation to lag considerably.

I've created a small reproducer to show the reduntant layout events when animating here: [https://rnplay.org/apps/DUpmUA]. The result is similar to @hayeah's example, I.E. animation does not trigger any layout event on iOS but on Android it triggers plenty of them.

For me the PR #7250 fixes the issue and makes Android behave like iOS. (Merged it into 0.26-stable)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-redundant-onlayout-event

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:50841)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsea-004LaC-Qt
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:06 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzseY-000160-Ps
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:04 -0700
Date: Thu, 27 Oct 2016 14:56:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605361;
	bh=sobB5OwJDeSjMsJPteTX02I17Q/hbuD6Uo4/+cOBRD8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=byNfCDtb8pMDmTW1tTyFaAMB7IEiMb/NKbC8wzsr/dKAN8OVYtAOzccHMapeOAhBv
	 ziIBmr5ImOpVgl2mnH8jPr1Ch6hWyE5HKQymV7y+osgUC0KTYl1c3fdNv/EZjNGjb5
	 GiCF+6rbn0FP8NR6k/0GONR3w6XprSVF8hsCJT7o=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (67/60 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:44746)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsen-004Lgn-No
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:18 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsen-0002AM-3s
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:17 -0700
Date: Thu, 27 Oct 2016 14:56:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605376;
	bh=IU8I8GgQR9Q8lw6tcise7RmDepDr09cUzAD8I+Xl3xU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=pLRnyDXkSGA7AbnqEww/73OoSRtCF3+5gqJE3zbLPgA4qXXenYVxliOigOHspSykP
	 lVAmXdlxbwRpfg6e6Gb/kZRXoY/r+OeKZ7K3OwufXXb7KVdSeFkPDGghMzM2cPYax4
	 Y5QpuraEO138ewi7UAr3kon9JsNaVCdXoXlz4Jhg=

**Comment by hayeah** [comment]
I believe this issue is resolved and merged https://github.com/facebook/react-native/pull/7250
