### ISSUE TITLE
Issue with Segment control and text inputs

### ISSUE THREAD

**Issue by RD1991** [facebook/react-native#7206]
Hi There,

Im using one segment control which have 2 segments. (User & Moderator)
In first segment (user) I have 4 text inputs , in another (moderator) I have 7 text inputs.

Now when I enter some text in first input of user segment, and switched to moderator segment control it shows me same value to  its first input.

What is the problem can you please explain ?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow
