### ISSUE TITLE
Got warning message in 0.25.0-rc

### ISSUE THREAD

**Issue by zh-wowtv** [facebook/react-native#7207]
I got the following warning message:

> Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package...

How to fix it? Thanks.

**Comment by grabbou** [comment]
```js
import React from 'react';
import { AppRegistry, View } from 'react-native';
```

**Comment by damusnet** [comment]
@grabbou do you maybe think there will be a codemod for this?

**Comment by grabbou** [comment]
There's been already some work by @sebmarkbage in the repo (you can see his commits `fix up this patter` here and there). That could probably work, I am planning to roll that out along the final 0.25 release notes. Unfortunately, there's little we can do about the dependencies, so fingers crossed everyone updates quickly :)

**Comment by damusnet** [comment]
Okay, thanks. For what it's worth, this basic regex find & replace did the trick for me using Sublime Text:

Find: 
```
import React, {( Component)?(,)?( PropTypes)?(,)?(.*)?} from 'react-native';
```

Replace:
```
import React, {$1$2$3 } from 'react';
import {$5} from 'react-native';
```

But then again, all my imports where like `import React, { Component, PropTypes, View, Text } from 'react-native';`
