### ISSUE TITLE
Missing android,ios & android folders and js files

### ISSUE THREAD

**Issue by pc8067** [facebook/react-native#7216]
When I run "react-native init FirstApp".
This will walk you through creating a new React Native project in D:\ReactNative\FirstApp
Installing react-native package from npm...
There's no any errors in the console.
This FirstApp React Native Project just get package.json and node_modules and Missing android/ios folders and js files.

OS:Windows 7
nodejs:v5.11.0
react-native-cli: 0.2.0

**Comment by mkonicek** [comment]
@facebook-github-bot label Android

**Comment by lacker** [comment]
I think this is missing sufficient information to proceed, so I'm going to close this.
