### ISSUE TITLE
[MapViewIOS] Dragging pin crashes the app

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#7218]
Can be reproduced in UIExplorer.

Screen:
<img width="361" alt="screen shot 2016-04-25 at 20 14 12" src="https://cloud.githubusercontent.com/assets/2464966/14794221/32d321f4-0b23-11e6-92f0-b351fd6d62ae.png">

Here's the potential fix (also not sure why we are mutating props in this case):
https://github.com/grabbou/react-native/commit/9b3d64cd3ff39dfa3f7dd6efa17b67a647be5eba

Anyone into `MapView` has some ideas?

**Comment by christopherdro** [comment]
@grabbou Still an issue?

**Comment by grabbou** [comment]
Looks like the code in master has exactly the same fix, but the issue was never closed. Can be closed.
