### ISSUE TITLE
SyntaxError: Cannot declare a parameter named 'err' as it shadows the name of a strict mode function

### ISSUE THREAD

**Issue by L3V147H4N** [facebook/react-native#7227]
I'm running the app in debug and when I use the option to debug in chrome it works fine but otherwise it shows this error and I cannot figure out why

**Comment by grabbou** [comment]
Can you share some code snippets? Generally my thinking is you something similar to this https://github.com/ipfs/js-ipfs-api/pull/199/files

**Comment by L3V147H4N** [comment]
I already changed all my functions's parameters and now it works, it seemed extremely arbitrary, I changed every parameter and now any one of them is throwing the error so I don't know which one was causing the problem, the issue was inside my action Creator files from redux

**Comment by lacker** [comment]
I think without more information we can't make progress so I'm going to close this issue.
