### ISSUE TITLE
Positioning View above a parent

### ISSUE THREAD

**Issue by pedro** [facebook/react-native#7229]
Hey folks,

We're trying to position a `View` above its parent using a negative top. iOS renders it the way I'd expect:

![screen shot 2016-04-26 at 12 14 14 am](https://cloud.githubusercontent.com/assets/2248/14809736/d78f1ce6-0b43-11e6-9ada-2317334e7960.png)

But Android is trimming the view to match the parent:

![screen shot 2016-04-26 at 12 14 16 am](https://cloud.githubusercontent.com/assets/2248/14809741/e37195f2-0b43-11e6-92a9-4476db6936bc.png)

Code:

```js
class RNPositionBug extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.box}>
          <View style={styles.inner}/>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  box: {
    width: 200,
    height: 200,
    backgroundColor: 'red',
  },
  inner: {
    position: 'relative',
    top: -50,
    width: 100,
    height: 100,
    backgroundColor: 'blue',
  }
});
```

Tested in React-Native 0.24.1, OSX. Tried to use both absolute and relative positioning on the inner view.

Any ideas/pointers are appreciated, thanks!

**Comment by ashleydw** [comment]
What about `overflow: 'visible'` on the outer Views ?

**Comment by kohver** [comment]
Unfortunately, overflow style property defaults to hidden and cannot be changed on Android 
https://facebook.github.io/react-native/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android

**Comment by grabbou** [comment]
@facebook-github-bot answered

**Comment by pedro** [comment]
oops, thank you!

**Comment by conor909** [comment]
@grabbou whats the answer?

**Comment by JCMais** [comment]
The answer is that it doesn't works.

**Comment by grabbou** [comment]
Here is the answer: https://github.com/facebook/react-native/issues/7229#issuecomment-214682365.

Basically, `overflow` doesn't work on Android. Anything that you try to put outside of its parent (negative margin, negative absolute position) will be cropped.

**Comment by JCMais** [comment]
See this issue about a possible solution https://github.com/facebook/react-native/issues/16951
