### ISSUE TITLE
dyld: Symbol not found: _OBJC_CLASS_$_UIUserNotificationSettings

### ISSUE THREAD

**Issue by mcz** [facebook/react-native#723]
I wanted to run the UIExplorer demo on an iPhone 4 with iOS 7.1.2. I compiled the the project in Xcode with Deployment Target 7.1

After it's compiled the started on the devices a black blank screen show, app freezes and this is what I get in the console.

```
dyld: Symbol not found: _OBJC_CLASS_$_UIUserNotificationSettings
  Referenced from: /var/mobile/Applications/31651B19-5F83-446B-A49B-E732167C774C/UIExplorer.app/UIExplorer
  Expected in: /System/Library/Frameworks/UIKit.framework/UIKit
 in /var/mobile/Applications/31651B19-5F83-446B-A49B-E732167C774C/UIExplorer.app/UIExplorer
```

I figured it out, that if I comment out this three line, it solves the problem:
https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L104-L106

Probably the perpanent solution is to put these three lines into the #ifdef's else branch.

**Comment by mcz** [comment]
btw. here is a smart solution to the problem:

http://corinnekrych.blogspot.hu/2014/07/how-to-support-push-notification-for.html

**Comment by mcz** [comment]
It's very interesting because if I run this code

```objective-c
  if ([[UIApplication sharedApplication] respondsToSelector:@selector(registerUserNotificationSettings:)]) {
      UIUserNotificationType types = UIUserNotificationTypeSound | UIUserNotificationTypeBadge | UIUserNotificationTypeAlert;
      UIUserNotificationSettings *notificationSettings = [UIUserNotificationSettings settingsForTypes:types categories:nil];
      [[UIApplication sharedApplication] registerUserNotificationSettings:notificationSettings];
  } else {
    [[UIApplication sharedApplication] registerForRemoteNotificationTypes:
     (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeSound | UIRemoteNotificationTypeAlert)];
  }
```

It still throws the same symbol not found error shown previously. So probably it has to be fixed in the compiler settings.

**Comment by ide** [comment]
Your most recent code snippet looks right. This should be handled at runtime and not by the compiler as long as you're using the iOS 8 SDK.

**Comment by mcz** [comment]
Yes, but unfortunately it throws the same error.

**Comment by ide** [comment]
Can you verify with a breakpoint that `[[UIApplication sharedApplication] respondsToSelector:@selector(registerUserNotificationSettings:)]` returns true on iOS 7? I wouldn't expect it to which is what's surprising to me.

**Comment by mcz** [comment]
The problem is that the app won't even start. It throws this error right away. Here is the stack trace:

![image](https://cloud.githubusercontent.com/assets/689796/7041471/cfe6d4ea-ddd9-11e4-8e44-f291fa56e4ed.png)
![image](https://cloud.githubusercontent.com/assets/689796/7041481/ec368334-ddd9-11e4-8833-c961f8492c74.png)

**Comment by brentvatne** [comment]
This issue seems stale, ping me if you are still having this problem @mcz and we can look into it further :smile: sorry we didn't get around to it sooner

**Comment by mcz** [comment]
thanks, it was already fixed long time ago. i forgot to close the issue :)

**Comment by jawadrehman** [comment]
@brentvatne the app crashed when running on the simulator ... I had to work around it by wrapping the code around 
#if TARGET_IPHONE_SIMULATOR
  NSLog(@"This is simulator mode....");
#else

//REST OF THE CODE FROM ABOVE

#endif
