### ISSUE TITLE
Opening stack trace with atom not working

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#7230]
Clicking on a stack trace item in a redbox doesn't work with my configuration anymore. It focuses the atom window for a split second, then goes back to the emulator/simulator without opening anything.

OS : Mac OS X (10.11.4)
Node : v5.11.0
Atom : 1.7.2
React Native : 0.23.0

I wasn't able to pin down the exact commit responsible for this in Atom, but the 1.6.2 version of Atom still works fine, this seems to be broken starting at the 1.7.0 version (maybe related to this PR: https://github.com/atom/atom/pull/11054).

I tried to debug [`launchEditor.js`](https://github.com/facebook/react-native/blob/master/local-cli/server/util/launchEditor.js) but I didn't see any errors, and the script wasn't modified a lot recently.

I'm not sure if the error is coming from React Native, but this sample script is working fine across all Atom versions:
```js
#!/usr/local/bin/node

var child_process = require('child_process');

_childProcess = child_process.spawn('atom', ['filename:lineNumber'], {stdio: 'inherit'});
```

**Comment by lacker** [comment]
Atom is working for me now. I'm going to close this but if it's still an issue feel free to reopen.
