### ISSUE TITLE
UIExplorer AppDelegate.m is outdated yielding problems installing the app with offline js

### ISSUE THREAD

**Issue by vikeri** [facebook/react-native#7231]
_Mac, iOS, master(667d278)_

[AppDelegate.m](../blob/master/Examples/UIExplorer/UIExplorer/AppDelegate.m) is outdated and therefore [these instructions](https://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle) for doing an offline bundle do not work.

I guess what is needed is to update that file to resemble the [scaffolded version of AppDelegate.m](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/local-cli/generator-ios/templates/app/AppDelegate.m) but it might have some side effects for tests and such so maybe someone with a fuller picture should provide an opinion on this first.

I could mess around with it but I don't have the time atm.

**Comment by jsierles** [comment]
Can you give more details about what failed for you?

Uncommenting this line should work: https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/UIExplorer/AppDelegate.m#L82

The bundle is used for tests as well.

**Comment by vikeri** [comment]
Yes that is what I did as per the instructions. It gives me the error No script URL provided and then the app force closes.

**Comment by lacker** [comment]
We have updated those instructions since this issue was last discussed and it worked in testing so I am going to close this issue. If you continue to run into problems please feel free to open a new one - although there must be something different in your setup and in our testing setups so ideally it would be clear what that is.
