### ISSUE TITLE
UIExplorer is broken: undefined is not an object (evaluating 'styleInterpolator(props)')

### ISSUE THREAD

**Issue by stage88** [facebook/react-native#7234]
I am getting this error when launching UIExplorer.

![simulator screen shot 26 apr 2016 22 14 35](https://cloud.githubusercontent.com/assets/9906800/14818217/4186bcce-0bff-11e6-8f66-da4f4f20cc10.png)

## Environment

- OSX 10.11.4
- Xcode 7.3
- iPhone 6 Simulator
- React-Native version 036199d3f7f79c608ff7c526fe91db76346b7ce3

## Steps

```bash
git clone https://github.com/facebook/react-native.git
cd react-native 
npm install
open Examples/UIExplorer/UIExplorer.xcodeproj
```

In https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js, on line 200, I replaced the statement with following:

```javascript
(subviewStyle === undefined ? null : subviewStyle[name])
```

The above seems to have fixed the issue. Not really sure if that would be acceptable as a possible fix.

**Comment by anttimo** [comment]
Looks like the commit causing this has now been reverted in master https://github.com/facebook/react-native/commit/2eef115161b3f3c56dd7783401723ee291a1bfb4#diff-8835667577029593d693b2f9e541d605

@stage88 as the code causing this error is now removed can you please close this ticket?

**Comment by grabbou** [comment]
Closing as per @anttimo comment and also in fact, the commit has been reverted. In case it breaks again, please create a new issue as it's likely the reason will be different :)

Thanks for staying on master and making sure all works @stage88, good use of issue template :)
