### ISSUE TITLE
onEndReached not working

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#7237]
I tried the UIExplorer CameraRoll example.
The example shows all the photos in a listview with onEndReached set to load more pics when you scroll to the bottom. But it always loads all the pictures in my mobile phone and never use the onEndReached to trigger the loading more pictures action. When the picture number is very large, it will eat all memory and finally crashes the UIExplorer app.

I tested it on my iphone 6s ios 9.3.1 
and with RN 0.24.

**Comment by narychen** [comment]
I finally found what's wrong with it.
The height of ListView of UIExplorer CameraRoll example is not set.
So the scrollProperties.visibleLength is always growing with the list item added.
The distance between the bottom of the end is always smaller than the threshold.
```javascript
// code in ListView.js
  _getDistanceFromEnd: function(scrollProperties) {
    return scrollProperties.contentLength - scrollProperties.visibleLength - scrollProperties.offset;
  },
```
Set the height of the ListView will solve this problem
```
      <ListView
        renderRow={this._renderRow}
        renderFooter={this._renderFooterSpinner}
        onEndReached={this._onEndReached}
        style={styles.container}
        dataSource={this.state.dataSource}
        onEndReachedThreshold={0}
      />

.......
  container: {
    flex: 1,
    height: 300,  // add it====>
  },
```

**Comment by dsibiski** [comment]
@narychen If you could submit a PR for this it would be greatly appreciated 😄

**Comment by lacker** [comment]
Looks like this is fixed.
