### ISSUE TITLE
__fbBatchedBridge is undefined out of the blue

### ISSUE THREAD

**Issue by danieldunderfelt** [facebook/react-native#7241]
Hi!

I suddenly started getting this `__fbBatchedBridge is undefined` error suddenly after the app was working fine. Prepare yourself for a crappy bug report, but I am at a loss regarding what caused it or how to fix it.

- I am developing on a mac
- For iOS
- Using RN 0.24.1

I have tried:
- `watchman watch-del-all`
- Resetting packager cache
- Removing packager cache
- Removing all npm modules and reinstalling
- Rebooting my computer
- `git reset --hard` to the previous commit that did work
- Making a new RN project and chucking my JS sources in it. Afterwards I only added my fonts and linked some packages with `rnpm` (all of these worked previously)
- Downgrading to RN 0.22
- Upgrading back to RN 0.24.1

Because this is now a new project from the native point of view, and I reset all my changes I had made since the last commit that worked, I have no clue why this error is persisting. Is there anything else I can do? Any help to get me back to developing my app is warmly welcome.

**Comment by danieldunderfelt** [comment]
... and just as suddenly it started working. In desperation I tried enabling Chrome debugging again (which had previously said something like `process is undefined`) and it started working. One of the things above I did might have helped!

**Comment by wildQueequeg** [comment]
I got this issue three times in the past two days for the same project. Regenerating the jsbundle and replacing the reference in Xcode solved this issue for me:
`react-native bundle --entry-file ./index.ios.js --platform ios --bundle-output ios/main.jsbundle`

Would like to know what keeps causing this...
