### ISSUE TITLE
[flow] createAnimatedComponent signature

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#7242]
flow is giving me a warning if the root component in render is Animated.View (or any other animated).

```
render() {
  return (<Animated.View />);
}

74:   render() {
              ^ return. Missing annotation
```

i think the problem is in the signature for the following method

```
function createAnimatedComponent(Component: any): any { ... }
```

given that all animated are generated using it

```
module.exports = {
  ...AnimatedImplementation,
  View: AnimatedImplementation.createAnimatedComponent(View),
  Text: AnimatedImplementation.createAnimatedComponent(Text),
  Image: AnimatedImplementation.createAnimatedComponent(Image),
};
```

is there any reason why we have any instead of React.Element /?

**Comment by grabbou** [comment]
If that used to be `any`, maybe we could change its signature to be:
```
function createAnimatedComponent<T>(Component: T): T
```

**Comment by satya164** [comment]
@grabbou AFAIK, mostly the author of the original file, but @bestander watches everything!

Agree with your suggestion on updating the signature.

@7ynk3r up for a PR? :D

**Comment by 7ynk3r** [comment]
trying to but i can't get it to work. i'm not sure if it's a problem with flow.

following @grabbou idea i tried to apply the following change

    function createAnimatedComponent <T>(Component: T): T {
      class AnimatedComponent extends T { ... }
      return AnimatedComponent;
    }

but i get an error from flow at 

    1357:   class AnimatedComponent extends T {
                                            ^ identifier `T`. Could not resolve name

looks like flow is not able to use the type in the context or maybe i'm doing something wrong

i'm also getting this error but should be fixed if the previous works

    1453:   return AnimatedComponent;
                   ^^^^^^^^^^^^^^^^^ class type: AnimatedComponent. This type is incompatible with the expected return type of
    1354: function createAnimatedComponent<T>(Component: T): T {
          ^ some incompatible instantiation of `T`

and finally these error that i have no idea what they mean

    Libraries/Animated/src/AnimatedImplementation.js:1428
    1428:         <Component
                  ^ React element `Component`
    1354: function createAnimatedComponent<T>(Component: T): T {
                                           ^ T. This type is incompatible with
    174:     name: ReactClass<Config> | $Keys<$JSXIntrinsics>,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of polymorphic type: type `ReactClass` | key set. See lib: /private/tmp/flow/flowlib_18cad6e0/react.js:174
      Member 1:
      174:     name: ReactClass<Config> | $Keys<$JSXIntrinsics>,
                     ^^^^^^^^^^^^^^^^^^ type application of polymorphic type: type `ReactClass`. See lib: /private/tmp/flow/flowlib_18cad6e0/react.js:174
      Error:
      1354: function createAnimatedComponent<T>(Component: T): T {
                                             ^ T. This type is incompatible with
      174:     name: ReactClass<Config> | $Keys<$JSXIntrinsics>,
                     ^^^^^^^^^^^^^^^^^^ class type: existential. See lib: /private/tmp/flow/flowlib_18cad6e0/react.js:174
      Member 2:
      174:     name: ReactClass<Config> | $Keys<$JSXIntrinsics>,
                                          ^^^^^^^^^^^^^^^^^^^^^ key set. See lib: /private/tmp/flow/flowlib_18cad6e0/react.js:174
      Error:
      1354: function createAnimatedComponent<T>(Component: T): T {
                                             ^ T. This type is incompatible with
      174:     name: ReactClass<Config> | $Keys<$JSXIntrinsics>,
                                          ^^^^^^^^^^^^^^^^^^^^^ key set. See lib: /private/tmp/flow/flowlib_18cad6e0/react.js:174

**Comment by grabbou** [comment]
I think `class AnimatedComponent extends T { ... }` is invalid - you can't extend a Flow Type (that's why it says cannot resolve identifier `T`. React.Component was fine.

After taking a look at the function itself, I am thinking we don't need the generic anyway as the return type is always `AnimatedComponent` that originally extends `React.Component`. 

You should be able to just remove the return type `any` as Flow is likely to get the type automatically. In case it doesn't, `React.Component` or `AnimatedComponent` is probably fine :)

**Comment by lacker** [comment]
I believe @yungsters and @frantic are working on the flow types for the standard library stuff now, so tagging them here because Animated.View is a good thing to make sure it flowtypes correctly.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
