### ISSUE TITLE
[Node 6] General issue for tracking compatibility with Node 6

### ISSUE THREAD

**Issue by ide** [facebook/react-native#7245]
The latest version of Node is now Node 6. We want to support all versions of Node LTS and up, but most people are either using Node LTS (4.x) or the latest Node (was 5.x, now 6.x) so my thinking is that we should focus on testing those two releases of Node the most.

Things we need to do:

- [ ] Try out Node 6, see what works and what doesn't (native modules might have issues though node-gyp is pretty good about keeping things compiling)
- [ ] Change CI env from Node 5 to Node 6

**Comment by janicduplessis** [comment]
Related: #7287

**Comment by janicduplessis** [comment]
Tested quickly by running UIExplorer and everything worked properly,

**Comment by ide** [comment]
Closing since Node 6's been working fine.
