### ISSUE TITLE
RCTViewManager calls 1 more all the time.

### ISSUE THREAD

**Issue by kocyigityunus** [facebook/react-native#725]
i am trying to create a custom UIView with js side. but i create 1 on the js side it calls manager twice. if i create 2 on the js side it calls manager 3 times. and one if them's "reactTag" is always nil. i can share gists about this if you need.

and secondly how can i find reactTag of a component on js side?

**Comment by ide** [comment]
The ViewManager always creates n+1 UIViews to help with React's diffing technique. Is that what you are referring to?

**Comment by kocyigityunus** [comment]
yes. that what i am referring to. but how can i get reactTag from js side or  how can i go to reactTag from nav object ?

is there a way to calling a method on a particular view in "more than one view to connect one manager" ?

**Comment by ide** [comment]
`this.getNodeHandle()` gives you the react tag.

**Comment by jaygarcia** [comment]
From what I remember, you don't call methods on views.  You set properties via the view manager. 

I ran into this problem a month ago :(

Where I have trouble is finding particular instances of views via a view manager.  Is that a bad approach?

JG

@moduscreate

:: sent from my mobile device ::

**Comment by kocyigityunus** [comment]
You can call methods from a manager. And the manager calls your custom view. You can look at it at : https://github.com/brentvatne/react-native-video. 

takePicture method does it.

**Comment by kocyigityunus** [comment]
@ide  this.getNodeHandle() gives me an object like this. i couldn't find any reactTag in it.

![screen shot 2015-04-08 at 09 40 01](https://cloud.githubusercontent.com/assets/922418/7040093/5cfcb20c-ddd3-11e4-8f47-39c608a117d3.png)

**Comment by ide** [comment]
You should be able to use the node handle to go through the UIManager and get the underlying shadow view from Obj-C. Take a look at the the Obj-C side of the UIManager as a starting point.

**Comment by ide** [comment]
The new way to get the node handle is with `React.findNodeHandle(componentReference)`. You can use a uiBlock in a native module to get access to a lookup map from node handles to native views if needed. Closing this out.
