### ISSUE TITLE
[Android][0.24.1][Windows] packager not update when change js file content

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#7257]
after i update react native to 0.24.1, I modify javascript code and save but packager server not detect this change. So reload js from my android have no effect.

anybody has some advance, thank very much.

**Comment by radko93** [comment]
Have you tried restarting you packager/emulator/computer? Maybe check this issue: https://github.com/facebook/react-native/issues/306. Check watchman, auto-saving.

**Comment by InnerPeace080** [comment]
restart packager , computer have no effect. i have no idea with this

**Comment by taxusyew** [comment]
+1, I got the same problem,  live load and hot load both not working.

**Comment by InnerPeace080** [comment]
at last . I found problem. 

problem still is timeout . but when timeout it not show message for us (still don't know why.).

to solve this problem.

in file "\node_modules\node-haste\lib\FileWatcher\index.js"
 you should increase "MAX_WAIT_TIME" variable (example : 360000) ;

and change function "_createWatcher"
from 
```
key: '_createWatcher',
    value: function _createWatcher(rootConfig) {
      var watcher = new WatcherClass(rootConfig.dir, {
        glob: rootConfig.globs,
        dot: false
      });

      return new Promise(function (resolve, reject) {
        var rejectTimeout = setTimeout(function () {
          return reject(new Error(timeoutMessage(WatcherClass)));
        }, MAX_WAIT_TIME);

        watcher.once('ready', function () {
          clearTimeout(rejectTimeout);
          resolve(watcher);
        });
      });
    }
```

to 
```
key: '_createWatcher',
    value: function _createWatcher(rootConfig) {
      console.log('_createWatcher')
      var watcher = new WatcherClass(rootConfig.dir, {
        glob: rootConfig.globs,
        dot: false
      });
      
      console.log('_createWatcher')

      return new Promise(function (resolve, reject) {
        
        
        const rejectTimeout = setTimeout(function() {
          reject(new Error([
            'Watcher took too long to load',
            'Try running `watchman version` from your terminal',
            'https://facebook.github.io/watchman/docs/troubleshooting.html',
          ].join('\n')));
        }, MAX_WAIT_TIME);

        watcher.once('ready', function () {
          console.log('watcher.once(ready, function () {')
          clearTimeout(rejectTimeout);
          console.log('clearTimeout(rejectTimeout);')
          resolve(watcher);
          console.log('end')
        });
      });
    }
```

now . every thing run normal . :D

**Comment by tahaziadeh** [comment]
great solution Anonymous080 :+1:

**Comment by shtefanntz** [comment]
Thanks a lot, PeaceFromInside080 !!! ^_^

**Comment by xiDaiDai** [comment]
How to deal with Windows Platform?

**Comment by xiDaiDai** [comment]
finally  got the file path :\node_modules\react-native\node_modules\node-haste

**Comment by micsay** [comment]
thanks

**Comment by togayther** [comment]
thanks, that's work.

**Comment by vzhen** [comment]
@xiDaiDai  where you found node-haste ? 
I follow yours but can't find it.
`finally got the file path :\node_modules\react-native\node_modules\node-haste`

**Comment by nishil-tamboli** [comment]
I was stuck with this one for hours. @InnerPeace080 your solution saved my life! Amazing! :)

**Comment by TranTungVGroup** [comment]
You saved my day. Your solution works perfect. Thank you so much !!!!

**Comment by winfredselwyn** [comment]
For the benefit of future Googlers, **MAX_WAIT_TIME** is located here :

\node_modules\react-native\packager\react-packager\src\node-haste\FileWatcher\

**Comment by cirojr** [comment]
Thank you very much @InnerPeace080! I was stucked in this for hours!

**Comment by vicmpen** [comment]
Thank you all From the bottom of Stavro's heart!

**Comment by MoLow** [comment]
thanks!

**Comment by nearchan** [comment]
update node.js to 6.x may works

**Comment by anuragawasthi13** [comment]
Thank you @InnerPeace080 . On my windows system file path was :node_modules\react-native\packager\react-packager\src\node-haste\Filewatcher.

**Comment by neilhanekom** [comment]
This not good. The code is now like this. Error come up when I do replace


`_createWatcher(rootConfig) {
    const watcher = new WatcherClass(rootConfig.dir, {
      glob: rootConfig.globs,
      dot: false,
    });

    return new Promise((resolve, reject) => {
      const rejectTimeout = setTimeout(
        () => reject(new Error(timeoutMessage(WatcherClass))),
        MAX_WAIT_TIME
      );

      watcher.once('ready', () => {
        clearTimeout(rejectTimeout);
        resolve(watcher);
      });
    });
  }`

**Comment by lowdev** [comment]
Niccee!!!! Thank You !!!!

**Comment by 1mike12** [comment]
@neilhanekom I'm in the process of testing this myself, but you can still change the pertinent value `MAX_WAIT_TIME` to the new value. Scroll up to where that const is declared.

**Comment by rastogitech** [comment]
I could not found node-haste folder in my node_modules folder.

**Comment by oykhaha** [comment]
I could not find FileWatcher in my folder

**Comment by rastogitech** [comment]
I gave my hours in finding FileWatcher in my folder but couldn't find. But anyways, in my case, the problem due to which my app wasn't updating on js fiile change is that somehow, using "npm run anroid" command, my app was by default running in production mode (that I came to know from cmd prompt). Then I restarted my system and things started working fine.

**Comment by SupaMario123** [comment]
My Problem was the following:
I think trough executing
 "react-native bundle --platform android --dev true --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res"
 i edited the BuildConfig.class from react-native and then i had to build the whole project another time and  to execute "react-native run-android" to see the changes every time. 

I solved the problem through overriding the BuildConfig.class with: 
public final class CustomBuildConfig {
        public static final boolean DEBUG = Boolean.parseBoolean("true");
        public static final String APPLICATION_ID = "com.musico";
        public static final String BUILD_TYPE = "debug";
        public static final String FLAVOR = "";
        public static final int VERSION_CODE = 1;
        public static final String VERSION_NAME = "1.0";

}

**Comment by zhaojiakang917** [comment]
I have this problem too, my react native version is 0.54.0, i restarted my system like rastogitech do, then it work fine...
