### ISSUE TITLE
[Border] Draw order for borders is last?

### ISSUE THREAD

**Issue by jcgertig** [facebook/react-native#726]
While working on an example for the way the current iteration of the Animation API works I ran across this.

https://www.dropbox.com/s/45cm1hnyelmb95u/Screenshot%202015-04-07%2015.10.21.png 

Which raises the question do borders get drawn after all components?

**Comment by brentvatne** [comment]
@jcgertig - the border code changed significantly recently, and a big change to the animation api is under way as well. If you can post the code that you used to generate that, we can try it on the newer version and see what the result is!

**Comment by christopherdro** [comment]
@jcgertig Any updates on this issue?

**Comment by brentvatne** [comment]
Closing because not enough information to proceed! :smile: Can reopen if you share some code @jcgertig! Also, check out the new `Animated` api, it's great :)
