### ISSUE TITLE
Linking a phone number with extension in Android is not working.

### ISSUE THREAD

**Issue by sunglee** [facebook/react-native#7265]
Linking a phone number without an extension works without any issues.
However, when an extension is added, it is not showing up in the Android Phone app. It only shows phone number only. For example, the following code will open a phone app with only 1 (234) 567-8900.

`
Linking.openURL('tel:12345678900,1111')
`

Is it an Android bug? Can this be fixed in React Native?

Thanks.

**Comment by radko93** [comment]
This is not a react-native bug. You can't use `,` or `p` in Android Dial Intent URI. Look at [this](http://stackoverflow.com/questions/11774884/android-how-to-make-a-call-that-includes-or-p-in-the-dial), maybe you will find a workaround.

**Comment by satya164** [comment]
@facebook-github-bot answered
