### ISSUE TITLE
packager: a way to blacklist some folders/files in a RN app?

### ISSUE THREAD

**Issue by gre** [facebook/react-native#7271]
Hi,
I have some folders under my root app like for instance a standalone node project that are not used by the app but for something else. How can I tell the packager to ignore these? It breaks when packager try to read the content of node_modules of that sub project, it shouldn't have enter there in the first place (because I never depend on it from any of the RN app jsbundle !!)

**Comment by radko93** [comment]
There is a [`blacklist.js`](https://github.com/facebook/react-native/blob/master/packager/blacklist.js) in `react-native/packager`.
Make a `rn-cli.config.js` in your project folder root and do something like this:
```
var blacklist = require('react-native/packager/blacklist');

var config = {
  getBlacklistRE(platform) {
    return blacklist(platform, [
      /node_modules\/my-package\/excluded-directory\/.*/
    ]);
  }
};

module.exports = config;
```

**Comment by gre** [comment]
thanks @radko93 !!

**Comment by dukeflyheli** [comment]
The code above is outdated or was incorrect, getBlacklistRE and blacklist do not take any parameters.

`var blacklist = require('react-native/packager/blacklist');

var config = {
  getBlacklistRE() {
    return blacklist([
      /node_modules\/my-package\/excluded-directory\/.*/
    ]);
  }
};

module.exports = config;`

**Comment by kirkstrobeck** [comment]
I was suffering the same thing at https://github.com/facebook/react-native/issues/12582

My code ended up being

```js
const blacklist = require('react-native/packager/blacklist');

module.exports = {
  getBlacklistRE: () => blacklist([
    /coverage\/.*/,
  ]),
};
```

and my `package.json` `start` script became

```json
"start": "react-native run-ios --config=rn-cli.config.js",
```

**Comment by alinz** [comment]
blacklist is not exists anymore in react-native 46 :( so after a little bit of research, i found out that we have to use `metro-bundler/build/blacklist` instead of `react-native/packager/blacklist`.

**Comment by rcorrie** [comment]
thanks @alinz that works for me

**Comment by azundo** [comment]
As of react-native 47 I have to do something like:

```
const metroBundler = require('metro-bundler');

module.exports = {
  getBlacklistRE: function() {
    return metroBundler.createBlacklist([/coverage\/.*/]);
  }
};
```

**Comment by samuela** [comment]
@azundo That doesn't work for me as of react-native 0.48.3 and metro-bundler 0.11.0: https://github.com/facebook/metro-bundler/issues/58

**Comment by nicolascouvrat** [comment]
@samuela 
Seems to work that way now (yey, folder changes...)
```javascript
const blacklist = require('metro-bundler/src/blacklist')
var config = {
  getBlackListRE() {
    return blacklist([ 
      // your folders here
    ]);
  }
};

module.exports = config;
```

**Comment by esutton** [comment]
After trying about all of the half-dozen above variations...

## blacklist du jour
## 2018 February 20 answer that works with RN 0.53

const blacklist = require('metro/src/blacklist');
```
const config = {
  getBlackListRE() {
    return blacklist([
      /react-codemod\/.*/,
    ]);
  },
};

module.exports = config;
````

**Comment by theRealRobG** [comment]
@esutton 
`getBlackListRE` -> `getBlacklistRE`

**Comment by esutton** [comment]
@theRealRobG Thank you!
