### ISSUE TITLE
NavigationTabsReducer from NavigatorExperimental looks buggy

### ISSUE THREAD

**Issue by Nopik** [facebook/react-native#7273]
Are those few lines: https://github.com/facebook/react-native/blob/master/Libraries/NavigationExperimental/Reducer/NavigationTabsReducer.js#L74-L78 correct?

They seem to:

- modify incoming state
- add `tabs` property to resulting state, and it seems that nobody is reading that property

**Comment by lacker** [comment]
That link doesn't work any more, so I'm going to close this issue. Sorry for not responding faster here. Feel free to reopen if there is still a problem, especially if this is causing an actual bug.
