### ISSUE TITLE
the development server returned response error code :404

### ISSUE THREAD

**Issue by allenyulun** [facebook/react-native#7274]
when I run:./gradlew :Examples:Movies:android:app:installDebug
![image](https://cloud.githubusercontent.com/assets/8003195/14885049/a4cd144a-0d7b-11e6-9045-ee7c615f35e8.png)
the AwesonmeProject is my first react-native module

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

PS. Please make sure you have the packager started & running in the correct folder, looks like you are trying to run a project whereas the packager runs in the folder of the previous one.

**Comment by allenyulun** [comment]
@grabbou  Thanks, yeah ,I forget to close the previous one, Then I restart it ,but error like this 
![image](https://cloud.githubusercontent.com/assets/8003195/14886903/d9110446-0d85-11e6-88d3-9e3c3a887f34.png)
I can't connect to development server

**Comment by grabbou** [comment]
Have you tried following the steps in error box? Isn't that changing anything?

**Comment by allenyulun** [comment]
@grabbou yeah ,I tried,but it's no use

**Comment by allenyulun** [comment]
@grabbou  i forget the last :./packager/packager.sh ...

**Comment by deju** [comment]
@allenyulun Turn on the `WIFI`.

**Comment by ShayanAhmad** [comment]
quit the "react-native run-android", then do "adb reverse tcp:8081 tcp:8081" and then do the "react-native run-android" and the code shall work on "Reload JS".

**Comment by omhybrid** [comment]
i have same problem please give me solution

**Comment by khawajah** [comment]
react-native start

**Comment by a1exlism** [comment]
Maybe you could use `npm` instand of cnpm.

**Comment by Stupidism** [comment]
@a1exlism Have you met the same problem and solved by this way?

**Comment by guozhiyuanasd** [comment]
who can tell me how to solve？

**Comment by Stupidism** [comment]
I found several problems related with this error, and here are my solutions to solve this problem: 
1. use `react-native start` [doc](https://facebook.github.io/react-native/releases/0.34/docs/getting-started.html)
![image](https://cloud.githubusercontent.com/assets/5801015/23781434/43ca88ac-0588-11e7-85ae-d82160f22aa7.png)
2. use `npm` instead of `cnpm`

**Comment by ericvicenti** [comment]
The movies sample has been removed from the core RN repo. Feel free to publish standalone example apps, and we can curate a list of them for the website.

**Comment by thiswhy** [comment]
I have the same problem.The code can worked in IOS ,but can not be worked in android .If you have solue this problem ,tell me ,thanks~

我有同样的问题。本来运行好好的项目突然出现这个问题，我原本以为是代码的原因，但是我从git拉下来可以运行的代码也出现了这个问题。是不是我的Android环境在mac上出现问题了。一定要帮帮我解决一下这个问题。谢谢你~

**Comment by rochapablo** [comment]
This worked for me (still not happy)

```
    compile ('com.facebook.react:react-native:0.48.4') { force = true }
```

Where `0.48.4` is your current version

**Comment by Taym95** [comment]
This should work! 
`compile ('com.facebook.react:react-native:YOUR_REACT_NATIVE_VERSION') { force = true }`
instead of
`compile "com.facebook.react:react-native:+"`
But why?

**Comment by rochapablo** [comment]
Indeed! Why!?

Last Friday it was working all good and yesterday I just start the project without changes and I got that error.

So, if you guys know why this start please, let me know.

**Comment by jeffzing** [comment]
@rochapablo apparently, your android react-native version ahead of your react-native version,use react-native:+ is not preciseness
