### ISSUE TITLE
[Android]Nested scrollview will crash the app

### ISSUE THREAD

**Issue by cuitianze** [facebook/react-native#7276]
A horizontal scrollview with nested vertical scrollview will crash the app.

Android version: 4.4.4 KTU84P (MI 3)
Android version: 4.4.2 (HUAWEI PE-TL10)

**Comment by charpeni** [comment]
What version of Native React you use?

Can you provide a code sample ? You can even host it on [rnplay](https://rnplay.org/).

**Comment by cuitianze** [comment]
"react-native": "0.21.0"

**Comment by cuitianze** [comment]
I will show the code sample later,  please wait for a moment.

**Comment by radko93** [comment]
It may be not related to a specific version, but make sure you use newest RN version when posting issues.

**Comment by cuitianze** [comment]
I found this problem is not related to nested scrollview, thanks for your guys.
https://github.com/facebook/react-native/issues/5997

**Comment by cuitianze** [comment]
The problem is related to [nested nested nested nested nested nested nested nested nested nested] View or Text. I hope that React-Native Team would fix this bug someday.

**Comment by naveensingh-daffodil** [comment]
any workaround for this issueeeee????????????
