### ISSUE TITLE
WebView: Different behaviors of "user-select" depending on the position of the element

### ISSUE THREAD

**Issue by adrianomelo** [facebook/react-native#7278]
This bug is related with the iOS WebView component. I tried to reproduce this behavior in several browsers but I didn't succeed. I'm not sure if it's a React Native bug or if it's related with iOS WebKit.

When a page has an element with `user-select: none` and a child of this element needs to be selectable, the WebView of react native is changing its behavior depending on the position of the child element.

In the example below, if `margin-top > ~500px`, then the user can select the text. if `margin-top is < ~500px` the user can't select the text. And if you change the property from `margin-top` to `margin-bottom`, you are able to reproduce the bug as well.

````
var React = require('react');
var ReactNative = require('react-native');
var { AppRegistry, WebView } = ReactNative;

var html = `
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=320, user-scalable=no">
  <style>
    .class1 {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
    }
    .class2 {
      margin-top: 470px; /* change this value to 500px to be able to select the text */
      -webkit-touch-callout: default;
      -webkit-user-select: text;
    }
  </style>
</head>
<body>
  <div class='class1'>
      <div class='class2'>Select me if you can!</div>
  </div>
</body>
</html>
`;

var WebViewTest = React.createClass({
  render: function () {
    return (
      <WebView
        source={{ html }}
        scalesPageToFit={true}
      />
    );
  },
});

AppRegistry.registerComponent('WebViewTest', () => WebViewTest);
````

React Native Version: 0.24.1
Tested on: iOS Simulator > iPhone 6 and rnplay.org

**Comment by dsibiski** [comment]
Can you provide the link on rnplay.org?

**Comment by adrianomelo** [comment]
I guess it is solved. I tried to reproduce it today using rnplay but I couldn't. I am closing the issue.
