### ISSUE TITLE
PickerIOS React.createElement: type should not be null, undefined, boolean, or number.

### ISSUE THREAD

**Issue by julioahurtado** [facebook/react-native#7282]
As stated in the title i receive this when using the PickeriOS. It gives me the warning whenever I initially run the application or when the picker is moved. the Picker code is as follows. 

 ```
<PickerIOS
  selectedValue={this.state.OccuType}
  onValueChange={(OccuType) => this.setState({OccuType})}>
     {Object.keys(OccupancyType).map((name) => (
          <PickerItemIOS
             key={name}
             value={name}
             label={OccupancyType[name].name}
              />
))}
</PickerIOS>
```
The code for the objects that it is using is:
```
var OccupancyType = {
    Residential: {
      name: 'Residential'
    },
    Multi: {
      name: 'Multi-Unit Residential'
    },
    Public: {
      name: 'Public Assembly'
    },
    Strip: {
      name: 'Strip Mall'
    },
    ComInd: {
      name: 'Commercial/Industrial'
    },
    High: {
      name: 'High Rise'
    }
};
```
Now the Picker works. Heres an [image](http://i.imgur.com/3AvaOU0.png). [Heres](http://i.imgur.com/bEQaA1S.png) the warning that it gives me.

I'm am currently on React Native ^0.24.1 and developing on a Mac for an iOS device.

**Comment by AndrewTHuang** [comment]
What does the render method of `VandenbergFire` look like?

**Comment by damusnet** [comment]
@facebook-github-bot close

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-0** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.

**Comment by regniraj** [comment]
`import {View,PickerIOS,Text,PickerItemIOS} from 'react-native';`
causes this issue 
fixed by 
`import {View,PickerIOS,Text} from 'react-native';
var PickerItemIOS = PickerIOS.Item
`
