### ISSUE TITLE
node v6.0.0,  console.log(formatBanner(...)) crashed

### ISSUE THREAD

**Issue by hitbear518** [facebook/react-native#7287]
After upgrading to node v6.0.0, `node node_modules/react-native/local-cli/cli.js start` will crash at node_modules/react-native/local-cli/server/server.js line 93, which is
`  console.log(formatBanner(
    'Running packager on port ' + args.port + '.\n\n' +
    'Keep this packager running while developing on any JS projects. ' +
    'Feel free to close this tab and run your own packager instance if you ' +
    'prefer.\n\n' +
    'https://github.com/facebook/react-native', {
      marginLeft: 1,
      marginRight: 1,
      paddingBottom: 1,
    })
  );`

in terminal it looks like
![image](https://cloud.githubusercontent.com/assets/5070531/14908473/1ef90cc2-0e0a-11e6-81d0-095e51318260.png)

you can workaround this by assign return value of formatBanner(...) to a variable and then console.log it .

---

react-native version 0.24.1 on Mac

**Comment by bosung90** [comment]
I don't think react-native works with node6 yet. I was having trouble with it yesterday when I tried to run it on Android from Windows

**Comment by janicduplessis** [comment]
Once you workaround this do you get any other errors on node 6 or does it works fine? Looks like a bug in node 6 since this code is pretty normal.

**Comment by hitbear518** [comment]
It works fine for now, but I'm not sure what caused this.

**Comment by janicduplessis** [comment]
Just tested and it worked for me too.

**Comment by hitbear518** [comment]
This is weird, suddenly it worked all fine now, no workaround needed.
So before and now I both tested an empty react native project which use `react-native init` command, and it worked perfectly now instead of crashed before.
I have no idea if the problem is about the China GFW and npm, or something I don't know.
Should I close this issue?

**Comment by janicduplessis** [comment]
Yea, let's close this for now.

**Comment by ide** [comment]
I've hit this error too but didn't look into what was happening.

That's strange that the issue went away. Did you run `npm install` again? Maybe you had node_modules made for Node 5, and upgraded to Node 6, and they are working fine (while node_modules made for Node 6 might have issues).

Trying to think of reasons why this issue would magically go away when Node 6.0.0 hasn't changed and this line is a simple console.log call. There's got to be a bug in the native layer somewhere...

**Comment by janicduplessis** [comment]
I never hit the issue but I did `rm -rf node_modules && npm install` before running it.

**Comment by poyannabati** [comment]
I'm getting the same (?) issue with an empty project.

**Comment by poyannabati** [comment]
Works fine when using nvm to switch to v5.11.1

**Comment by stereodenis** [comment]
```
node -v
v6.2.0
npm -v
3.8.9
```

```
npm start --reset-cache 

> WTCCEuroSport@0.0.1 start /Users/stereodenis/work/evrone/WTCCEuroSport
> node node_modules/react-native/local-cli/cli.js start

 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "start" "--reset-cache"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! WTCCEuroSport@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WTCCEuroSport@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the WTCCEuroSport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/react-native/local-cli/cli.js start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs WTCCEuroSport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls WTCCEuroSport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/stereodenis/work/evrone/WTCCEuroSport/npm-debug.log
```
