### ISSUE TITLE
app crash on RN 0.21.0

### ISSUE THREAD

**Issue by jameshen17** [facebook/react-native#7292]
Got app crash on RN 0.21.0, stacktrace as below：

`---java.lang.NullPointerException
com.facebook.react.uimanager.UIImplementation.notifyOnBeforeLayoutRecursive(677)
com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(463)
com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(454)
com.facebook.react.uimanager.UIManagerModule.onBatchComplete(433)
com.facebook.react.bridge.NativeModuleRegistry.onBatchComplete(139)
com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.onBatchComplete(437)
com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(-2)
android.os.Handler.handleCallback(733)
android.os.Handler.dispatchMessage(95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(31)
android.os.Looper.loop(136)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(187)
java.lang.Thread.run(841)`

codes as below:

```
  private void notifyOnBeforeLayoutRecursive(ReactShadowNode cssNode) {
    if (!cssNode.hasUpdates()) {
      return;
    }
    for (int i = 0; i < cssNode.getChildCount(); i++) {
      notifyOnBeforeLayoutRecursive(cssNode.getChildAt(i));
    }
    cssNode.onBeforeLayout();
  }
```

It seems cssNode is Null.

**Comment by dsibiski** [comment]
@jameshen17 Can you please provide some more information, like what platform are you running on, what version of Node, etc.

Also, we really would need some sort of minimal sample repo/example that we could run to be able to replicate the crash. Without it it will be really hard for anyone to help you.

**Comment by jameshen17** [comment]
@dsibiski  some information as below:
ReactNative 0.21.0
Android 4.4 device

it's random issue, I don't have reproduce steps, just met only once.
Maybe you can do something to avoid app crash at least.
