### ISSUE TITLE
Bundler missing assets

### ISSUE THREAD

**Issue by matclayton** [facebook/react-native#7295]
We have our own build pipeline (to be able to use relay with react-native) and got confused for weeks with react native not bundling in assets on device, after much debugging we found that its not possible to set --assets-dest to a sub folder of the build directory. Despite it all bundling without errors, the bundle wont show any images on a live device due to the change in path. I would consider this a bug and the bundler should probably highlight the issues (or fix them). Reporting this issue incase it confuses anyone else and hopefully this can be helpful

**Bad**
cli.js bundle --entry-file ./native/index.ios.js --platform ios --dev false --bundle-output ./build/ios/main.jsbundle --assets-dest ./build/ios/react-assets/

**Good**
cli.js bundle --entry-file ./native/index.ios.js --platform ios --dev false --bundle-output ./build/ios/main.jsbundle --assets-dest ./build/ios/

**Comment by lacker** [comment]
Yeah, the bundler should probably just show a clear error message. How exactly do you reproduce this - can you give an example starting from a fresh project with `react-native init` ?
