### ISSUE TITLE
Testing the issues bot

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#7296]
Please ignore, just testing a GitHub bot.

**Comment by mkonicek-tester** [comment]
@facebook-github-bot label Android

**Comment by mkonicek-tester** [comment]
@facebook-github-bot label iOS

**Comment by damusnet** [comment]
Hey @mkonicek, somehow the @facebook-github-bot doesn't seem to like me :(
See #7328 for example. Do you maybe know why? I thought anyone could use it...

**Comment by mkonicek** [comment]
@damusnet Awesome that you'd like to help us with managing GitHub issues! To have access to the bot please add yourself to the first line here (send a PR): https://github.com/facebook/react-native/blob/master/bots/IssueCommands.txt

Please check out the guidelines on managing issues: https://github.com/facebook/react-native/blob/master/docs/IssueGuidelines.md

**Comment by damusnet** [comment]
@mkonicek Thanks! Did just that! Totally missed the fact that there was a whitelist.
From the [React Native: A year in review](https://code.facebook.com/posts/597378980427792/react-native-a-year-in-review/) article it seemed open to anyone :)
Maybe it should be mentioned on the [IssueGuidelines](https://github.com/facebook/react-native/blob/master/docs/IssueGuidelines.md)?

**Comment by mkonicek-tester** [comment]
@damusnet Good point about adding a link in IssueGuidelines! If you want to do that I'm happy to accept  a PR :)

**Comment by mkonicek** [comment]
@damusnet Good point about adding a link in IssueGuidelines! If you want to do that I'm happy to accept a PR :)

**Comment by mkonicek-tester** [comment]
@facebook-github-bot label Android

**Comment by mkonicek-tester** [comment]
@facebook-github-bot label Android

**Comment by mkonicek-tester** [comment]
@facebook-github-bot label Android
