### ISSUE TITLE
[JS] Warn when `npm install -g react-native`

### ISSUE THREAD

**Issue by vjeux** [facebook/react-native#730]
Several people didn't add -cli and then got confused that it didn't work.

**Comment by frantic** [comment]
Possible solutions: use `postinstall` hook to run `npm list -g react-native &>/dev/null && echo "Looks like you installed react-native globally, did you mean react-native-cli?"`

**Comment by jaygarcia** [comment]
This happened to a colleague last week. :P

**Comment by sreejithr** [comment]
I've made a pull request #889. I put a `WARNING: ` with red color and underline before the message. Please do check if it complies with the project's style.

Btw, how about having a prompt where the user can opt to get react-native uninstalled from global?

**Comment by vipulnsward** [comment]
This can be closed similar to https://github.com/facebook/react-native/pull/828 ?
