### ISSUE TITLE
Android: Some .ttf fonts cause 'Layout -n < 0' Error

### ISSUE THREAD

**Issue by jsncmgs1** [facebook/react-native#7301]
For version 0.22.0, Android only, on a 2015 Macbook Pro:

I have some custom fonts in my application, OpenSans and FiraSans, both from Google Fonts as well as some variants, such as OpenSans-Light, FiraSans-Bold, etc.  Everything works fine on iOS.

Android renders the OpenSans font's fine.  When it tries render `<Text>` with FiraSans fontFamily, I get this error:
<img width="427" alt="screen shot 2016-04-29 at 3 44 32 pm" src="https://cloud.githubusercontent.com/assets/5445942/14927679/4c9efe36-0e21-11e6-8044-446949085a9c.png">

If I remove the font from the app, the error goes away and it just uses the default, so I don't think it's a naming issue.  I'm not really sure what to do with this error message. I tried changing font sizes, but no luck.

**Comment by mmazzarolo** [comment]
Still having the same issue on `react-native@0.33`.  
Anyone have any suggestion on this? It is happening even on [common fonts](https://fonts.google.com/specimen/Fira+Sans?selection.family=Fira+Sans)...

**Comment by jleepeak** [comment]
Still having on react-native@0.37

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by Deviloppeur** [comment]
I had the same problem using this font (FiraSans). I used the official font (https://github.com/mozilla/Fira) and it worked. Hope that can help.

**Comment by morfsys** [comment]
Same issue with Rubik font, please reopen
