### ISSUE TITLE
Android Bottom navigation 

### ISSUE THREAD

**Issue by jfarriagada** [facebook/react-native#7305]
Is there any way to use bottom navigation in native react ?
[https://www.google.com/design/spec/components/bottom-navigation.html#](url)

**Comment by dsibiski** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-5** [comment]
Hey @jfarriagada! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
