### ISSUE TITLE
"You must specify a width and height for the image" always warns message if image is inside <Text>

### ISSUE THREAD

**Issue by huston007** [facebook/react-native#7315]
Hello. I just found that react-native always warns about image (inside `<Text>`) sizing even if width and height are set.
Example markup: 
```javascript
      <View style={styles.container}>
        <Text>
        	<Image
            source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}}
            style={{width: 123, height: 123}}
        	/>
        </Text>
      </View>
```

Here is the warning:

<img width="273" alt="screen shot 2016-05-01 at 02 34 30" src="https://cloud.githubusercontent.com/assets/4318513/14939210/453966c0-0f45-11e6-9528-05241f61698e.png">

This reproduces only on iOS at the moment.

Please check my sandbox where it is reproduced: https://rnplay.org/apps/iDvmwQ

**Comment by DannyiCracked** [comment]
https://github.com/facebook/react-native/blob/f7bcb3e98d489bb40ee8fd7dd69918521344f657/Libraries/Image/Image.ios.js#L228

It appears the above snippet can be removed, judging by this commit: https://github.com/facebook/react-native/commit/2cbc9127560c5f0f89ae5aa6ff863b1818f1c7c3

**Comment by lacker** [comment]
Looks like that snippet is indeed removed in master
