### ISSUE TITLE
Build failed: Crunching Cruncher failed

### ISSUE THREAD

**Issue by anchetaWern** [facebook/react-native#7320]
I'm having issues with app:mergeDebugResources task.

**error:**

```
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Crunching Cruncher abc_tab_indicator_mtrl_alpha.9.png failed, see logs
```

I just created a new react native project with this command. No plugins and other code added yet.

```
react-native init MyProject
```

From `package.json` version 0.24.1 of React is installed:

```
{
  "name": "TestReact",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.24.1"
  }
}
```

The error occurs for android, not really sure if the same problem exists with iOS.
I'm using Ubuntu for development.

Gradle is at version 2.4 according to the `gradle.properties` file:

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip
```

**Comment by anchetaWern** [comment]
for anyone having the same problem. this solved the issue for me:

http://stackoverflow.com/questions/22701405/aapt-ioexception-error-2-no-such-file-or-directory-why-cant-i-build-my-grad

It's an issue with 64-bit OS, because aapt isn't available you have to install these 2 packages:

```
sudo apt-get install lib32stdc++6 lib32z1
```

**Comment by micsay** [comment]
thanks,that works for me.

**Comment by bozzmob** [comment]
Thanks! It worked for me too. :+1:
