### ISSUE TITLE
Enable D-pad Navigation

### ISSUE THREAD

**Issue by jerson** [facebook/react-native#7322]
Hi, I'm trying to make an application for Android TV but navigation does not work, it seems to lack implement "D-pad Navigation"

http://developer.android.com/intl/es/training/tv/start/navigation.html#d-pad-navigation

React Native supports this ?, or have plans to implement it?

excuse me do not speak much English, it is only google translate ✌️

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @jerson and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by frankiewiczkamil** [comment]
@ghost  @DanielMSchmidt 

> This also helps us use the GitHub bug tracker for bugs only.

In fact it seems that there might be buggy behaviuor when using d-pad remotes. 
I tested my RN app with d-pad remote and `Button`'s `onPress` handler is not triggered as it should be (with remote's OK button). Arrow keys work fine.
[This is offical android guide](https://developer.android.com/training/tv/start/navigation.html) for that, IMO it should work in RN like in pure android developed apps...

Can we reopen that?

**Comment by NikolaBorislavovHristov** [comment]
@jerson @frankiewiczkamil 
You have to create new abstraction on top of touchable component that listen for keypress events when it is focused and remove that listener when it is blur. At this moment in [Stremio beta](https://play.google.com/store/apps/details?id=com.stremio.beta) we have manage to implement this. At this moment it is coupled with our internal code, but later we could open-source it. If you are still interested in implementing such feature i can tell you more.

**Comment by frankiewiczkamil** [comment]
@NikolaBorislavovHristov thank you for reply. 
I have installed Stremio Beta on an android stb and the navigation is nice and intuitive - very good job if you ask me.
I guess that you have also implemented `nextFocus*` handling, am I right?

> later we could open-source it

I think it would be great for RN community and for achieving one of most important RN's goals, which is _run everywhere_.
In such case, can you estimate if and when is it possible to e.g. put it as npm module? I can wait for a while and participate in such project.

**Comment by NikolaBorislavovHristov** [comment]
@frankiewiczkamil 
I didn't use nextFocus. i let the OS to decide which is the next item.
