### ISSUE TITLE
File UTI used instead of MIME type

### ISSUE THREAD

**Issue by yedidyak** [facebook/react-native#7329]
In RCTAssetsLibraryRequestHandler, sendRequest, there is 

      NSURLResponse *response =
      [[NSURLResponse alloc] initWithURL:request.URL
                                MIMEType:representation.UTI
                   expectedContentLength:length
                        textEncodingName:nil];

This is incorrect, and can lead to errors upstream where the file mimeType is the UTI. For example, I have a problem where the file meta data now say 'public.jpeg' instead of 'image/jpeg'

**Comment by yedidyak** [comment]
@nicklockwood, I see that you wrote this and very similar code in RCTImageLoader, but there you added the actual mimeType instead of the UTI, is there a reason it isn't here?

**Comment by nicklockwood** [comment]
No, that was probably just a mistake on my part.

**Comment by yedidyak** [comment]
@nicklockwood  I'll add a pull request to fix it then.

**Comment by nicklockwood** [comment]
Thanks!

**Comment by yedidyak** [comment]
Corrected in Pull Request #7349
