### ISSUE TITLE
Can't animate ToolbarAndroid using Animated

### ISSUE THREAD

**Issue by papermana** [facebook/react-native#7335]
Hi,

I'm trying to apply animation to the ToolbarAndroid component, but my code results in an error. I reproduced the issue in a new project using the following code:

```
import React, {
  Animated,
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  ToolbarAndroid,
  View
} from 'react-native';

const AnimatedToolbarAndroid = Animated.createAnimatedComponent(ToolbarAndroid);

class toolbarTest2 extends Component {
  constructor(props) {
    super(props);

    this.state = {
      toolbarHeight: new Animated.Value(56),
    };
  }

  componentDidMount() {
    Animated.timing(
      this.state.toolbarHeight,
      {
        toValue: 112,
        duration: 750,
      }
    ).start();
  }

  render() {
    return (
      <View style={{flex: 1}}>
        <AnimatedToolbarAndroid style={{
          height: this.state.toolbarHeight,
          backgroundColor: 'blue',
        }} />
        <View style={styles.container}>
          <Text style={styles.welcome}>
            Welcome to React Native!
          </Text>
          <Text style={styles.instructions}>
            To get started, edit index.android.js
          </Text>
          <Text style={styles.instructions}>
            Shake or press menu button for dev menu
          </Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('toolbarTest2', () => toolbarTest2);
```

This code works when I use Animated.View, but when I replace it with ToolbarAndroid, I get an error message saying this.viewConfig is undefined when executing function setNativeProps: ([link to screenshots](http://imgur.com/a/EcKmt)).

I'm developing on Ubuntu Linux, testing on Nexus 5 (Android 6.0.1), using React Native 24 (but I also tested it with 25-rc with no differences).

**Comment by ssomnoremac** [comment]
I've never tried to make an animated component out of a native one but I suspect that's your problem based on that error.  `Animated` can only be used with non-native components -- I think. I would suggest using a different toolbar like the one in the `react-native-router-flux` if you want to apply your own animations. It's already using Animated and you can probably tap into that api and customize it to do and look how you want.

**Comment by papermana** [comment]
I eventually sidestepped the issue by creating my own header bar. However, I'm pretty sure `Animated` is supposed to work on native components, considering that e.g. `Animated.View` is one. I'm guessing there needs to be some additional native code for a component to work with `Animated`, so it's just missing in `ToolbarAndroid`. Whether that's something that really has to be fixed, I don't know.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/cant-animate-toolbarandroid-using-animated

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
