### ISSUE TITLE
ARM linker error using RN>=0.24.0 as a Pod

### ISSUE THREAD

**Issue by rh389** [facebook/react-native#7337]
This issue was introduced by https://github.com/facebook/react-native/commit/2f2703936d1b41d0d36f0b12aee2939d341aa65f between v0.23.1 and v0.24.0, and is still present in master.

When building a project where RN is installed as a CocoaPod, I get the linker error ```ld: illegal text-relocation to 'anon' in ... from '_RCTProfileTrampoline'```

Pod projects are (usually?) built with a Mach-O type 'Dynamic library'. Changing build settings so that the 'React' target has a Mach-O type of 'Static library' fixes/hides the problem, but I'm out of my depth trying to go any further with this.

To reproduce easily, checkout https://github.com/facebook/react-native, open `React/React.xcodeproj`, change Build Settings -> Linking -> Mach-O Type to 'Dynamic library' and build against an ARM device. This works prior to that commit, and fails after it.

@tadeuzagallo might be interested.

**Comment by keeth** [comment]
Got hit by this too.  Thanks for pointing out the culprit revision so that I can revert in my branch too.

**Comment by tadeuzagallo** [comment]
This commit fixed a different issue with jumping further than the relative jump range, I'll look into fixing this, thanks for investigating.

**Comment by tadeuzagallo** [comment]
I fixed the build, will send a diff as soon as I get a 32-bit device, just to be sure everything is working (probably tomorrow).

**Comment by Elyx0** [comment]
Been hit by the same in RN 26.2

**Comment by keeth** [comment]
@Elyx0 looks like it's fixed in 0.27

**Comment by faisalattock** [comment]
I am facing the same issue, who can i fix it?
