### ISSUE TITLE
Dimensions not updating on iPad due to screen rotation.

### ISSUE THREAD

**Issue by ghuh** [facebook/react-native#7340]
On an iPad (both physical and simulator), the Dimensions are not getting updated correctly after screen rotation.  The same code works just fine on an iPhone.

What is really interesting is that it appears that the Dimensions are getting set on iPad, just one rotation behind.  So, every time I call Dimensions as I rotate the device repeatedly between landscape and portrait, the width and height are always reversed of what they should be.

This was using RN v0.24.0-rc3. (i.e. after https://github.com/facebook/react-native/commit/b653d43e2e9d8a5506818b47d69993328132bbe4)

**Comment by simosalmi** [comment]
I'm having the same issue. Is anybody working on this? A solution would be much appreciated. Thanks

**Comment by ghuh** [comment]
This is still broken as of RN v0.31.0

**Comment by mahlon-gumbs** [comment]
I've just run into this with RN v0.33.0 and RN v0.34.0.

**Comment by ghuh** [comment]
I'm now running into the same issue on an Android 7.0 simulator with RN v0.33.0

**Comment by messense** [comment]
Just run into this issue with React Native 0.37.

**Comment by mrpp01** [comment]
I tried to reproduce this bug, but it seems to work fine for me.

**Comment by adrienbataille** [comment]
When I'm rotating the iPad, dimensions are not updated as you can on pictures:

![capture d ecran 2016-12-08 a 14 03 59](https://cloud.githubusercontent.com/assets/1434301/21023696/a221eab6-bd4f-11e6-82c4-49a337a87273.png)
![capture d ecran 2016-12-08 a 14 04 07](https://cloud.githubusercontent.com/assets/1434301/21023698/a4e82184-bd4f-11e6-91e3-d201f2a04dd6.png)

If you want to test it: https://github.com/adrienbataille/test-react-native

Note: It works fine on iPhone

### Additional Information

React Native version: 0.39.1
Platform: iOS
Operating System: MacOS - Sierra

**Comment by manicakes** [comment]
I believe my PR here: https://github.com/facebook/react-native/pull/11350 fixes the bug.

**Comment by michaelcpuckett** [comment]
+1

**Comment by sospedra** [comment]
still having the issue, the PR looks unmerged

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/dimensions-not-updating-on-ipad-due-to-screen-rotation

**Comment by alainib** [comment]
i test my react native app on a ipad air MD791NF/A with a 2048 x 1536 screen 
with `Dimensions.get("window")` i get ontScale  480 x  320. what i'm missing ?
