### ISSUE TITLE
feature: can merge NativeAppEventEmitter and DeviceEventEmitter?

### ISSUE THREAD

**Issue by jetzhliu** [facebook/react-native#7341]
NativeAppEventEmitter and DeviceEventEmitter has similar (or same?) API, how about merge them into `NativeEventEmitter`?

**Comment by grabbou** [comment]
Removed issue template for clarity.

**Comment by Bhullnatik** [comment]
Is there really any more difference than one is for Android and the other for iOS? I couldn't find any docs mentioning one vs the other, but I have never been able to use `NativeAppEventEmitter` on Android, and even the documentation on creating native modules uses [`DeviceEventEmitter` on Android](http://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript) and [`NativeAppEventEmitter` on iOS](http://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript).

**Comment by grabbou** [comment]
> Is there really any more difference than one is for Android and the other for iOS? 

Both are available on both platforms. You can check how to use it [here](https://github.com/johanneslumpe/react-native-fs/pull/91/files#diff-52e5c01506e28a2dc71dc07cb11e6e44R217)

I am going to close this one since there's some work to make an emitter scoped to native module, as per Nick commit here: https://github.com/facebook/react-native/commit/9ee1f37bade91d7db490cb3cb702104f268654ae

**Comment by actonw** [comment]
I think that at least the documentation should be updated to reflect that they are not platform-specific, since the iOS and Android guides do differ in what module it uses in the guide.

**Comment by philjoseph** [comment]
I agree that the documentation is confusing here. Worth updating it. I would love to do it myself I was clear enough about this important feature but I am not yet.

**Comment by sunny635533** [comment]
I am also confusiing here.Please update the documentation about them.

**Comment by grabbou** [comment]
I am happy to answer any questions you might have - I don't have time myself to contribute to the documentation right now, but I am happy to provide you with some extra info :)

**Comment by sunny635533** [comment]
Thank you , grabbu. I found the doucmentation here https://facebook.github.io/react-native/docs/native-modules-ios.html. I tried all Emitter.The conclusion is that DeviceEventEmitter and NativeAppEventEmitter only be used in android, NativeEventEmitter only be used in ios.

**Comment by grabbou** [comment]
Please refer to my [original comment](https://github.com/facebook/react-native/issues/7341#issuecomment-216514036) where I outlined the differences. Both are available on both platforms.

**Comment by FaiChou** [comment]
`DeviceEventEmitter` for android communicating with native.

`NativeEventEmitter`  for iOS communicating with native.

`NativeAppEventEmitter` are deprecated.

Is it right?

And is there any react-native event module (or js module) for communicating between react components? like listener or subscriber?

**Comment by FaiChou** [comment]
Is is possible using [Event interface](https://developer.mozilla.org/en-US/docs/Web/API/Event) in react-native?


Or can component be the [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget)?

> EventTarget is an interface implemented by objects that can receive events and may have listeners for them.

> Element, document, and window are the most common event targets, but other objects can be event targets too, for example XMLHttpRequest, AudioNode, AudioContext, and others. 

> Many event targets (including elements, documents, and windows) also support setting event handlers via on... properties and attributes.

**Comment by FaiChou** [comment]
I am using self designed [NotificationCenter](https://gist.github.com/FaiChou/62bfbc19752b98b42199978137358749) for sending and receiving messages between components.

Is it recommended by official?
