### ISSUE TITLE
Default flexDirection should be 'row', not 'column'

### ISSUE THREAD

**Issue by antoinerousseau** [facebook/react-native#7376]
The default style value for `flexDirection` is `'column'`.
According to the [specs](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction) (referenced in [LayoutPropTypes.js](https://github.com/facebook/react-native/blob/2529179769ff7f24f9b91acc5417e19983958ff6/Libraries/StyleSheet/LayoutPropTypes.js#L60)), it should be `'row'`.

React Native version: 0.24.1
Device: Android (Genymotion)

**Comment by ide** [comment]
@vjeux how much do you care about spec compliance? My understanding is that React Native borrows some ideas from flex box but doesn't actually implement the CSS spec, which will matter even less if React DOM does its own layout in the future.

**Comment by antoinerousseau** [comment]
Imho it's okay to not care about specs, but only if there is a good reason.
In any case, it would be good to provide the default values in the docs then.

**Comment by sesm** [comment]
@antoinerousseau the reason for this might be the fact, that mobile phones are usually held in portrait mode, while desktop computer displays are usually in landscape mode.

**Comment by vjeux** [comment]
I tried to document the decisions behind the default values here and a css reset you can use on your web projects to have the same behavior: https://github.com/facebook/css-layout/blob/master/README.md

For the default row, I have never understood why this choice was made in CSS, it doesn't make any sense to me. The only reason I can think of is that the original use cases where flexbox was designed for were things that normal css doesn't work and involve horizontal things maybe?

If you are not convinced that this is a good choice, look at the number of View you output in your app and the number of flexDirection: 'row'. The second number is likely ridiculously small.

**Comment by vjeux** [comment]
@ide: css-layout actually does (at least try baring bugs) to follow the css spec. The goal is that anything you write with React Native can be rendered pixel perfect on the web using a lightweight polyfill like react-native-web.

Where we can have some wiggle room with the spec is with default values and we can introduce some values like paddingHorizontal that are easy to translate to real css values

**Comment by vjeux** [comment]
Also, the defaults have been modeled to make View behave like a div.

**Comment by antoinerousseau** [comment]
Thanks for all these clarifications!


> Also, the defaults have been modeled to make View behave like a div.

That makes sense.
