### ISSUE TITLE
text Align :'right' doesn't work for placeholder when multiline is true

### ISSUE THREAD

**Issue by HananeAlSamrout** [facebook/react-native#7378]
In my code i have 2 textInputs, one has one line and the other has multiple lines, the input is arabic so i have to enable textAlign: 'right', my problem is when i set multilines to true, the placeholder text remains on the left side of the text input, any idea how to solve this? my code is the following:

View:

```
               ` <View  style={{ position: 'relative' }}>
                    <TextInput
                        style={forms.textInput}
                        value={this.state.telephone}
                        placeholder={'رقم هاتفك'}
                        placeholderTextColor={'rgba(0,0,0,0.6)'} 
                        onChangeText={(val) => this.setState({telephone: val}) } />
                    <Icon name="android-phone-portrait" size={27} color="rgba(0,0,0,0.6)" style={{ position: 'absolute', top: 10, right: 24 }}/>
                </View>
                <View  style={{ position: 'relative' }}>
                    <TextInput
                        style={[forms.textInput,{height: 120}]}
                        multiline={true}
                        value={this.state.desc}
                        numberOfLines={4}
                        placeholder={'اقتراحك'}
                        placeholderTextColor={'rgba(0,0,0,0.6)'} 
                        onChangeText={(val) => this.setState({desc: val}) }/>
                    <Icon name="ios-help-outline" size={27} color="rgba(0,0,0,0.6)" style={{ position: 'absolute', top: 10, right: 24 }}/>
                </View>`
```

Style:

```
               `
                   textInput: {
                               height: 40, 
                               borderColor: 'rgba(0, 0, 0, 0.4)',
                               borderWidth: 2,
                               margin: 15,
                               marginTop: 5,
                               backgroundColor: '#fff',
                               color: 'rgba(0, 0, 0, 0.9)',
                              paddingRight: 40,
                               textAlign :'right'
                             },
                            `
```

<img width="283" alt="screen shot 2016-05-04 at 10 10 04 am" src="https://cloud.githubusercontent.com/assets/8542325/15007506/3b5df82e-11e2-11e6-8bfd-65dee2a99b0b.png">

**Comment by adamski** [comment]
I would also like to raise this issue. I have centrally aligned TextInputs, one of them being multiline - the placeholder does not respect the centre alignment in the multiline TextInput.

**Comment by JuliusMalisauskasDB** [comment]
It seems that this feature was fixed in 0.33 and now it is back in 0.35?

**Comment by miclaus** [comment]
+1

**Comment by holyxiaoxin** [comment]
Facing this as well. Flex property breaks when multiline is true for IOS TextInput. It's fine in Android.

**Comment by philjoseph** [comment]
+1 There is a similar issue - #10812  on Text component with a workaround but it does not seem to help here

**Comment by theminerymike** [comment]
I just fixed this issue.

The issue was fixed once before, and referenced here http://stackoverflow.com/questions/37020690/text-align-right-doesnt-work-for-placeholder-when-multiline-is-true

I applied the same update, in the same file, but inside updateFrames, just at the bottom, I put the line `_placeholderView.textAlignment = _textView.textAlignment;`

I was having this issue with 0.42.0, the version I'm currently using.

I was going to make a commit for this, but it appears that the function no longer exists in master. I guess some major updates have been made to this file.

**Comment by shergin** [comment]
That file was heavily refactored (by me) in master thought. Therefore I believe that issue was fixed as part of that refactoring because we have this line now: https://github.com/theminery-hr4/react-native/blob/master/Libraries/Text/RCTUITextView.m#L108

**Comment by shergin** [comment]
Therefore, as I can see from the screenshots, we can also have this another much more complicated RTL-related issue.
