### ISSUE TITLE
Cannot find module './local-cli/cli.js'

### ISSUE THREAD

**Issue by hufeng** [facebook/react-native#738]
react-native init AwesomeProj

module.js:340
    throw err;
          ^
Error: Cannot find module './local-cli/cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/AwesomeProj/node_modules/react-native/cli.js:7:18)
    at Module._compile (module.js:456:26)

```
λ AwesomeProj  tree -L 3
.
├── node_modules
│   └── react-native
│       ├── Examples
│       ├── LICENSE
│       ├── Libraries
│       ├── PATENTS
│       ├── README.md
│       ├── React
│       ├── cli.js
│       ├── init.sh
│       ├── node_modules
│       ├── package.json
│       └── packager
└── package.json

7 directories, 7 files

λ AwesomeProj  more package.json 
{
  "name": "AwesomeProj",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "^0.3.5"
  }
}


```

**Comment by arthuralee** [comment]
Ignore the mention of a fix above - it was wrong.

It seems like `react-native-cli` needs to be updated. It doesn't come straight from the repo so I guess it got out of sync in light of recent changes to the paths. 

https://www.npmjs.com/package/react-native-cli
cc @spicyj as he was the last one who updated it.

**Comment by vjeux** [comment]
Sorry about this, it is now fixed. https://github.com/facebook/react-native/pull/706#issuecomment-90799052

Thanks a lot for reporting this!

**Comment by anil-sidhu** [comment]
use npm install command
