### ISSUE TITLE
[IOS] use RCTImageView in my custom view, not show image. I debug watch to _bridge.imageLoader issues nil

### ISSUE THREAD

**Issue by zhonshu** [facebook/react-native#7387]
I use RCTImageView not use UIImageView, Because RCTImageView already have Cache url image .
My code:
RCTImageView *groupImageView = [[RCTImageView alloc] initWithBridge:nil];
    groupImageView.frame = CGRectMake(15, 5, 70, 70);
    groupImageView.contentMode = UIViewContentModeScaleAspectFit;
    [self.contentView addSubview:_groupImageView = groupImageView];

RCTImageSource *imageSource = [RCTConvert RCTImageSource:json];
[self.groupImageView setSource:imageSource];

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow
