### ISSUE TITLE
When can we expect support for 'web-search' and other keyboardType in TextInput for Android?

### ISSUE THREAD

**Issue by shraddha1704** [facebook/react-native#7388]

**Comment by radko93** [comment]
Don't post all this autogenerated text in issue message. Android does not support `web-search` keyboard type, check [Input type](http://developer.android.com/reference/android/text/InputType.html) in Android docs.

**Comment by brentvatne** [comment]
Hi there! Please post feature requests to https://productpains.com/product/react-native/ -- as @radko93 pointed out this isn't supported but you might be able to get something similar thanks to https://github.com/facebook/react-native/commit/dd8caf4cf21941aff5afc7e919ced58ec564f3a3 -- this is only available on master right now though.
