### ISSUE TITLE
[ANDROID] Unable to pass sourceMap argument to packager

### ISSUE THREAD

**Issue by ColCh** [facebook/react-native#7393]
We use crashlytics and it's needed to have a sourcemap of our js file.
It's a problem when running release build, because we just can't pass `--sourcemap-output` argument to packager. And we forced to use local *react.gradle* instead of bundled one from node_modules. (Gool ol' copy-paste not welcome)

This bug was introduced by #6610
Commit: a7cde8045ba10d67896cc5b203d397eaf4f395d6

Solution:
Add a boolean flag (*generate source maps?*) into commented-out section before `apply from: "../../node_modules/react-native/react.gradle"` line and consume it.

**Comment by rayshih** [comment]
Seems like they provide a new way to inject config.

**Comment by ColCh** [comment]
Yeah, @rayshih . Now it's possible to pass additional arguments to packager, by https://github.com/facebook/react-native/commit/1f2027a1fe740b159f120663d6ddb9ca381d48af

Sourcemap argument can be passed like:
```groovy
project.ext.react = [
  extraPackagerArgs: ["--sourcemap-output", "path/to/bundle.js.map"]
]
```
(However, I didn't tested it, but it should work though)

I think, that this issue is resolved now, and I will close it then.

**Comment by rayshih** [comment]
I just tried it, and it works :)

**Comment by IjzerenHein** [comment]
I can also confirm that it works (tried with v0.29). I'm using the following config in `build.gradle` to generate the source-map in the same location as the release bundle file:

```gradle
project.ext.react = [
	extraPackagerArgs: ["--sourcemap-output", "$buildDir/intermediates/assets/release/index.android.jsbundle.map"]
]
apply from: "../../node_modules/react-native/react.gradle"
```

**Comment by drudge** [comment]
How can this be done when variants are introduced?

**Comment by ColCh** [comment]
@drudge as v0.29 I guess?
