### ISSUE TITLE
[0.25.1] Unfocussed Warning Yellowbox

### ISSUE THREAD

**Issue by GantMan** [facebook/react-native#7394]
Using Mac, RN 0.25.1, problem occurs on iOS and Android.  After upgrading to 0.25.1 I get the warning that `ReactNative.createElement` is deprecated.  I have scanned every file I use and I do not use the deprecated `ReactNative.createElement`.  Is it possible that this error is coming from node_modules?  I can't see how I'd get it any other way.   If so, it shouldn't be alerting me about node_modules using deprecated syntax right?  Or at the least, can this give me a line number/file?  I have nothing to go on for fixing this warning.

![simulator screen shot may 4 2016 5 53 44 pm](https://cloud.githubusercontent.com/assets/997157/15031860/aeb2379c-1221-11e6-9c50-75e6dca2080f.png)

https://github.com/infinitered/ignite/tree/master/ignite-base
`createElement` is used once, and comes from `react` as warning wants.  Still get warning.

**Comment by kraffslol** [comment]
This might have to do with the new deprecation in RN 0.25. Look at the deprecations part on `https://github.com/facebook/react-native/releases/tag/v0.25.1`

**Comment by ide** [comment]
grep through all your node_modules for createElement calls and see which ones are getting imported from react-native instead of react.

**Comment by GantMan** [comment]
I did a preliminary pass, and did not find anything.

I also ran ` $ grep -r -l react-native node_modules | xargs grep -l createElement` which did not turn up anything worth mentioning.   I'm interested if anyone else is getting this warning.  

I'm proud of running a warning free dev environment, but I really can't crack this one.

**Comment by magicismight** [comment]
This is very very annoying.
Do I have to change EVERY module I have used in my project to keep off this warning?

**Comment by satya164** [comment]
@GantMan You most probably don't use createElement directly. `<SomeComponent />` is transpiled to `React.createElement` calls.

**Comment by satya164** [comment]
Also read the release notes for examples - https://github.com/facebook/react-native/releases

**Comment by grabbou** [comment]
You can hide this warning which might be another option. There's an open issue already for stack traces you can track here - #5834

**Comment by GantMan** [comment]
@grabbou - I agree, I too would enjoy seeing a warning from node_modules, but only if I KNEW it was from node_modules.   This needle in a haystack warning starts to ebb at sanity.

I've researched my node_modules to try to find nothing, and if what @satya164 is saying, that it might be coming from something transpiled, I'm a bit at a loss on how I'm supposed to rebuff this warning at all.

I guess this ticket really does tie in on #5834, since what I ultimately want is a way forward to squash the warning.   Feel free to close this ticket in favor of 5834.  We can reopen if needed.

**Comment by ide** [comment]
You could turn off the YellowBox warning if it annoys you.

**Comment by GantMan** [comment]
@ide - yes, I could, but that's a really not a solution.  YellowBox notifications are great!  and useful 99% of the time, it's only this one which isn't.  Every other YellowBox warning is usually findable and fixable by removing deprecated code.  

I'm afraid of turning off YellowBox and losing the useful feedback it was designed to provide.

**Comment by chirag04** [comment]
@GantMan you can selectively ignore warning that you don't like using:
```
console.ignoredYellowBox = ['Warning: ...'];
```

**Comment by Jiafan** [comment]
I solved it like this .
```
import React, { Component } from 'react';

import { StyleSheet,TouchableHighlight,Text } from 'react-native';
```

Just do what the warning telling us to do.

**Comment by agat** [comment]
Hello i have similar error. `react 0.14.8, react-native 0.25.1`

`ExceptionsManager.js:76 Warning: ReactNative.Component is deprecated. Use React.Component from the "react" package instead.` in Chrome console.

You can reproduce this with minimal code:

`index.ios.js`
```
import React, {
    Component
} from 'react';
import {
    Text,
    AppRegistry
} from 'react-native';

class App extends Component {
    render () {
        return (
            <Text>{'Hello'}</Text>
        );
    };
};

const app = () => {
    AppRegistry.registerComponent('pn', () => App);
}

app('ios');
```

**Comment by GantMan** [comment]
looking at the example provided by @agat 

This means, `react-native init AwesomeProj` doesn't have this warning because it places separate code inside eacy .ios/.android file, but the moment you try to move this code to an imported lib to share, you can't help but get this warning.

With that said, I would say this warning is either oversensitive or indicative of a significant problem with the deprecation.  In either case and this ticket nolonger has to do with #5834 anymore.

**Comment by michelmongkhoy** [comment]
Hi,

I got the same issue. 
Looks like, when lazy developer like me are copy/pasting the code from this [page](https://facebook.github.io/react-native/docs/embedded-app-ios.html#content), you got this issue. 

By chance, if you check the markdown on GitHub, you have a [working code](https://github.com/facebook/react-native/blob/master/docs/EmbeddedAppIOS.md#create-your-react-native-app) that doesn't make the warning. 

You can check the differences to see what you need to do. 
Might be helpful to update the website so others can avoid this problem 😄 

Working code below: 
``` javascript
'use strict';

import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

var styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'red'
  }
});

class SimpleApp extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>This is a simple application.</Text>
      </View>
    )
  }
}

AppRegistry.registerComponent('SimpleApp', () => SimpleApp);
```

**Comment by rclai** [comment]
FYI, if you guys have been using the `react-redux@3.x`, you will get this warning. Just upgrade to the latest `react-redux`, change this

`import { connect } from 'react-redux/native';`

to

`import { connect } from 'react-redux';`

and the warning should disappear.

It looks like you won't get that `fbjs` error of death anymore.

**Comment by GantMan** [comment]
Greetings all, I spent a good amount of time today trying to remove this yellowbox issue.  I searched through all `node_modules` for `.*React .*['|"]react-native` and edited the files in place when any node_module used the older syntax.  I STILL have a warning, and I can't identify where/how to fix this.

**Comment by jeromegrosse** [comment]
So did I. Could it be that Babel 'translates' some import into the deprecated code? Is there any way to read the code generated by babel?

**Comment by GantMan** [comment]
FINALLY got all my warnings gone! *PHEW* did updating of dependencies, and fortunately all libs seem to have cleared themselves of this mess :)

gotta admit I was worried, but fortunately the libs I depend on have updated.

**Comment by grabbou** [comment]
Great to hear that! I can also see this improving which makes me happy as the 0.26 is waiting for the upgrade :)

Can we close this now or is there anything to add?

**Comment by GantMan** [comment]
Yup!  Good to run a clear project again!

**Comment by egold** [comment]
1. Debug in Chrome
2. Expand the warning (shows up as an error in Console)

Looks like in my case, it was `react-native-vector-icons` causing the issue.

![image](https://cloud.githubusercontent.com/assets/403964/15307590/6954cd06-1b89-11e6-9154-59e2ca50b79b.png)
