### ISSUE TITLE
[26.0-rc1] Bundle sourceMapURL

### ISSUE THREAD

**Issue by arbesfeld** [facebook/react-native#7397]
It appears that running `react-native bundle` in `26.0-rc1` creates a source map that looks like this:

`sourceMappingURL=bundle.js.map/*utf8:264abef9372bac0542a4b2869cc3541ceb78e5a1*/`.

When a load `bundle.js` in a Worker on Chrome, it's not able to resolve the SourceMap. Perhaps this `utf8` tag should be on a new line?

**Comment by arbesfeld** [comment]
Either we need a new line before here: https://github.com/facebook/react-native/blob/master/local-cli/bundle/output/hash.js#L32

Or after here: https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Bundler/Bundle.js#L105

Happy to make a PR with the fix

@davidaurelio

**Comment by Kerumen** [comment]
Reference https://github.com/getsentry/sentry/pull/3414#issuecomment-224524829

**Comment by benvinegar** [comment]
I wish there was a PR or issue that explained some of the motivation of this change, but it looks like it came straight from Facebook.

The [Source Map Revision 3 Protocol](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.z8wbphyi88iu) says this about encoding:

> Encoding
> For simplicity, the character set encoding is always UTF-8.

**Comment by Kerumen** [comment]
But I think the tag should be on a new line. Definitely a bug thant must be solved.

**Comment by davidaurelio** [comment]
We have removed it some time ago. Sorry for breaking you guys!
