### ISSUE TITLE
Error: cannot find find variable: window

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/react-native#740]
I wanted to offset some code duplication by requiring some modules and giving them global scope. 

In my index.ios.js  I reference a file which gives a few libs global scope (e.g. window.React = require('react-native')). I've found changing window to global works. 

What's curious is references to window that aren't execute immediately seem to be working fine. Is the window object aimed to be supported or should I be doing things differently?

**Comment by arthuralee** [comment]
`window` gets assigned here: https://github.com/facebook/react-native/blob/master/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L33

Tracing back, the code above is triggered by calling `require('react-native')`, so not being able to `window.React = require('react-native')` makes sense. But it seems like `window` should be available after requiring `require('react-native')`.

**Comment by kyle-ssg** [comment]
Yeah having found a similar issue using setTimeout related stuff before requiring react-native I tried this approach, however it didn't work. I have a feeling global wouldn't work when debugging with chrome? Either way for now I went with the following :

```javascript
var React = require('react-native'),
    window = global || window;

window.React = React;
window._= require('lodash');
//and so on
```

**Comment by arthuralee** [comment]
I just tried it in Chrome and it seems to work. I think the `global` variable is available at the highest level (`index.ios.bundle`).

**Comment by kyle-ssg** [comment]
Ah good to know, I'll start using that where applicable. Cheers for the help
