### ISSUE TITLE
JS Exception: TypeError: undefined is not an object (evaluating 'modules.length') 

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#7400]
When I change some code (I have hot-reloading enabled), my app crashes to homescreen often. Logcat shows me:

`Got JS Exception: TypeError: undefined is not an object (evaluating 'modules.length')`

Is there something I can do about this, it make my development really slow :(.

**Comment by fab1an** [comment]
I traced it down to the following: When my React class inherits from a super class, e.g.

```javascript
class Base extends React.Component {
}

class App extends Base {
}

```

and I update something inside `App`, react-native will crash.

**Comment by grabbou** [comment]
Closing as it seems to be a duplicate of https://github.com/facebook/react-native/issues/7199#issuecomment-216247419
