### ISSUE TITLE
how to aviod the suggestions in keyboard for android

### ISSUE THREAD

**Issue by shaikhussian** [facebook/react-native#7403]
Hai i tried to avoid suggestions in keyboard for that, i wrote **autoCorrect=false** it workes fine in IOS but in android it not working can any one give me suggestions that how to avoid suggetions in android keybord, Below i am posting the image and my TextInput code
 ```
<TextInput
        style={styles.TextInput}
        value={this.state.currentWord}
        onChangeText={(text) => this.setState({currentWord:text.trim()})}
        placeholder="Type Your word here"
       autoCapitalize='characters'
      autoCorrect={this.state.autoCorrect}
      autoFocus={this.state.autoFocus}/>
```
![demo](https://cloud.githubusercontent.com/assets/11956308/15042039/38ef9fb4-12de-11e6-9a83-f16870ddd5c8.png)
Here i want to avoid suggestions, please let me know whether it is bug (or) any solution for it

**Comment by radko93** [comment]
I can confirm that on RN 0.25.1, Android 5.1.1. Looking for a fix.

**Comment by radko93** [comment]
It actually works with Google Keyboard on my phone (on `master`), does not work with Swiftkey Keyboard. So that's probably not RN bug.

**Comment by shaikhussian** [comment]
@radko93 Thank you for tour response i am always getting swiftkey keyboard how to get the Google Keyboard when using TextInput, And is there any possibility to avoid suggestion for swiftkey keyboard

**Comment by radko93** [comment]
You must install Google Keyboard if you want to use it. It's not a good place to discuss android keyboards.

**Comment by brentvatne** [comment]
@radko93 all over it again :) This seems to be the correct answer, I'm not sure what we can do here about handling different Android keyboards but I'd be curious to hear people's thoughts about it!
