### ISSUE TITLE
Error: undefined is not a function (evaluating 'UIManager.setChildren(containerTag,createdTags)')

### ISSUE THREAD

**Issue by gooftroop** [facebook/react-native#7409]
Environment:
- react-native 0.26.0-rc
- react 15.0.2
- Android 5.1.1 API 22
- Mac OSX 10.11.14

Issue:
When running my app (in dev mode), I am getting the following error:

<code>E/ReactNativeJS: undefined is not a function (evaluating 'UIManager.setChildren(containerTag,createdTags)')</code>

All attempts at debugging have failed on my part. The Android app contains both native and react-native code, but I currently have no NativeModules or Views - just an Activity whose onCreate is:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Fabric.with(this, new Crashlytics(), new CrashlyticsNdk());
        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "Insights");
        setContentView(mReactRootView);
    }
```

I've attached a screenshot of the emulator:

![screen shot 2016-05-05 at 12 01 10 pm](https://cloud.githubusercontent.com/assets/2867867/15048821/292831d8-12b9-11e6-81e3-966027fe88f5.png)

**Comment by gooftroop** [comment]
I see that commit 3a5457cd7cf97171c3435a157f158eefa52bab0a added 'setChildren' to UIManager, but looking at the Java code on my machine, it does not appear that NativeViewHierarchyManager.java in react-native-0.20.1 has this ReactMethod.

**Comment by grabbou** [comment]
@gooftroop yep, that commit is a part of 0.26-rc release.

**Comment by Jonrock23** [comment]
I upgraded my Android app to RN 0.26 and I started getting this issue. Can anyone please tell me how they addressed it. Thanks

**Comment by jeduan** [comment]
Having the same problem here

**Comment by jeduan** [comment]
@Jonrock23 cleaning and rebuilding in Android Studio helped in my case

**Comment by Jonrock23** [comment]
Thanks @jeduan had to clean npm cache, close RN packager and rebuild with Android Studio

**Comment by mnadbader** [comment]
I have the same issue. i have cleaned npm cache , closed Packager and build with Android studio but that not resolved my problem.

**Comment by GantMan** [comment]
I am also getting this error, and no amount of clearning or cache-busting is helping resolve.

**Comment by payneio** [comment]
Same here.

**Comment by donotwarry** [comment]
Have the same problem

**Comment by mnadbader** [comment]
i resolved the problem by deleting an RN Module ( spinkit). Guys verify your external modules integration

**Comment by tuckerconnelly** [comment]
Yeah getting this too after upgrading to 0.26.2. I got a temporary workaround by re-adding the deleted code from UIManager.js

```js
if (!UIManager.setChildren) {

  /**
   * Index cache (used by setChildren())
   */
  UIManager._cachedIndexArray = function(size) {
    var cachedResult = this._cachedIndexArray._cache[size];
    if (!cachedResult) {
      var arr = [];
      for (var i = 0; i < size; i++) {
        arr[i] = i;
      }
      this._cachedIndexArray._cache[size] = arr;
      return arr;
    } else {
      return cachedResult;
    }
  };
  UIManager._cachedIndexArray._cache = {};

  /**
   * Fallback setChildren() implementation for Android
   */
  UIManager.setChildren = function(containerTag, createdTags) {
    var indexes = this._cachedIndexArray(createdTags.length);
    UIManager.manageChildren(containerTag, null, null, createdTags, indexes, null);
  };
}
```

**Comment by jayshah123** [comment]
Yeah, getting this after upgrading to 0.26.1

**Comment by esutton** [comment]
@tuckerconnelly  Thank you!   I can develop code again!

I wasted hours trying to figure out why it ran fine on iOS but not Android.

**Comment by holyxiaoxin** [comment]
@tuckerconnelly this works for now. Thanks.

Using `0.26.1` and after monkey-patch, it works. Hope that this gets fixed properly.

**Comment by donotwarry** [comment]
@tuckerconnelly  thanks, that works now

**Comment by yangqing0314** [comment]
I have the same problem too, when I use "npm init"  that default react-native version was "^0.26.1", the react version was "15.0.2",I have this problem.
I resolved the problem by degradation react-native version to "^0.25.1" ,the react version to "0.14.8"

**Comment by ssx29984744** [comment]
@yangqing0314 thank you! it works!
I hava the same problem too.
react-native version relegated to 0.25.1 == > I change "dependencies": {
    "react-native": "^0.25.1"
  } and reinstall =>npm install =>  npm start ==>reload js.

**Comment by MerlinYu** [comment]
I think react-native version  is not stable. When I want to develop with android ,there are many problem.
