### ISSUE TITLE
Error using simple lodash _.defer

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/react-native#741]
Having got lodash to work (either with lodash or lodash-node) I've found the following behaviour: 
 Code: 
```javascript
var _ = require('lodash');
_.defer(function(){
    console.log('callback')
}.bind(this));
```

Error: 
 message: undefined is not a function (evaluating 'setTimeout(function() { func.apply(undefined, args); }, wait)')", {"line":2866,"column":24,"sourceURL":"http://localhost:8081/index.ios.bundle"}

**Comment by spicyj** [comment]
If you `require('react-native')` before requiring lodash, does it work? Guessing this is an initialization order problem because we're not really treating setTimeout and friends as polyfill modules but we probably should be.

**Comment by kyle-ssg** [comment]
Ah great catch! That worked. Could this issue also affect setting variables with window scope ? 

E.g. 

window._ = require('lodash') ?
