### ISSUE TITLE
<Image> component appears in inspector but is blank/white (iOS simulator)

### ISSUE THREAD

**Issue by DerHowie** [facebook/react-native#7415]
``
  <Image source={require('image!name')} />
``
When I run this, I think it's being recognized because the dimensions seem to be right, however it is blank.

`` 
  <Image source={require(./images/name.png)} />
``
I tried this initially but it throws an error saying that it cannot find the module. This error recommended I run three commands. I did not have any success after following facebook's instructions.

I completely remade the project and have recreated the same problem.

**Comment by aprabaldi** [comment]
We are experiencing the same issue, but on an iPad Pro instead of the simulator. Did you find any workaround?
