### ISSUE TITLE
[Android]In Webview, alert isn't working.

### ISSUE THREAD

**Issue by coolguy001tv** [facebook/react-native#7419]
I am using rn 0.23.1 with win7.
I find that in rn's webview, when I want to alert something, it doesn't work ( only in Android).
[Here's my demo](https://rnplay.org/apps/Gwun0Q) .
The source code of `http://www.coolguy.pw/test/i.html` is like this:

```
<!DOCTYPE html>
    <html>
    <head>
    <script>

    function clicked() {
         alert("clicked");
         window.WebViewBridge && window.WebViewBridge.send('doSomething')
    }
</script>
</head>

<body >
<button onclick="clicked()">Touch me</button>
<script>
  function insert(text){
    var div = document.createElement("div");
    div.innerHTML = text;
    document.body.appendChild(div);
  }
  insert(alert.toString());
  alert("aaaa");
</script>
</body>
</html>
```

So run in ios, it's ok to pop up "aaaa","hello", even when you click the button, you can see "clicked";
But run in android, none is popped up , even when you click the button.

**Comment by charpeni** [comment]
Can you try with react-native@0.25.1 ?

Since the version 0.25.1 the Android WebView now uses WebChromeClient as default client and I thought it could maybe fix this issue.

**Comment by coolguy001tv** [comment]
I tried 0.25.1 but still failed, even if I repack the apk.

**Comment by coolguy001tv** [comment]
Didn't anyone suffer this problem?

**Comment by jainmitesh09** [comment]
For iOS, it works sometimes and other times it doesn't. Any fixes?

**Comment by coolguy001tv** [comment]
@jainmitesh09 Recently I found that when in RN 0.31(android), the alert is ok .

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
