### ISSUE TITLE
[Android] Value inconsistency when not using "Debug in Chrome"

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/react-native#7421]
I am currently developing an app for iOS/Android.
iOS does not have this issue. However, on my Nexus 6P,
When converting strings such as this:

'Fri Jul 24 2015 08:00:00 GMT+0900 (JST)'

into Date objects with `var foo = new Date()`, it seems valid when I have the Chrome Debugger on,
yet when I turn it off,
it becomes 'Invalid Date' in the Android Studio console, and the app cannot progress as it can't convert it to a Date object.

I'm not sure which level of the stack this issue could be happening in, so addressing it here.

**Comment by damusnet** [comment]
@Naoto-Ida this is probably related to the [JavaScript Environment](https://facebook.github.io/react-native/docs/javascript-environment.html#javascript-runtime) not being the same in debug/not debug, although it runs just fine in my Safari.

I suggest using a library such as [moment.js](http://momentjs.com/docs/) that is battle tested to avoid inconsistencies.

**Comment by ide** [comment]
Nothing we can really do about this without writing a Date polyfill. Try to write your code in a way that works on JSC and V8, just as you'd make your website work on Safari and Chrome.

**Comment by Naoto-Ida** [comment]
Thanks guys. I guess I'll have to read up on the differences between JSC and V8.

In my code, I'm just trying to get the hour from a Date object.
So not sure how I can write this in another way.

**Comment by Naoto-Ida** [comment]
FYI, when not using the debugger (I'm presuming it uses JSC?),
it doesn't like any datetime strings that contain anything related to timezones.
Also, it doesn't think dates separated by `-` are valid.

So I had to convert all my datetimes to "yyyy/MM/dd HH:mm:s" format for it to be convertible into a
Date object when in debug/non-debug mode.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-value-inconsistency-when-not-using-debug-in-chrome

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by alexsmartens** [comment]
Hi there,
I'm also having this problem
