### ISSUE TITLE
ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by Ericat** [facebook/react-native#7426]
As an experiment, I am trying to make isomorphic-relay work in react-native, but I stumble onto the error below as soon as I try to import a component into `renderOnServer.js`.

This has been mentioned before [here](https://github.com/facebook/relay/issues/26#issuecomment-193959380), but I am not sure how to fix it.

```
/node_modules/react-native/Libraries/react-native/react-native.js:15
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
```

This crashes the entire graphql server.

I am on a Mac, versions:
react-native@0.25.1
react-relay @0.8.1
isomorphic-relay@0.7.0-beta.0

My `renderOnServer.js` now is minimal: 

```
import IsomorphicRelay from 'isomorphic-relay';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import Relay from 'react-relay';
import AppHomeRoute from './routes/AppHomeRoute';
import MyComponent from './components/MyComponent'; // offending line

export default (res, next) => {
  return next();
};
```

in `server.js`:
```
[...]
app.get('/', (req, res, next) => {
  renderOnServer(res, next);
});
[...]
```

Full stack trace:
```
/Users/ericat/nativeRelay/node_modules/react-native/Libraries/react-native/react-native.js:15
if (__DEV__) {
    ^

ReferenceError: __DEV__ is not defined
    at Object.<anonymous> (/Users/ericat/nativeRelay/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ericat/nativeRelay/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (MyComponent.js:2:1)
    at Module._compile (module.js:425:26)
```

What am I doing wrong? It looks like a bug. If I set `var __DEV__ = true;` at the beginning of the file, the next error would be: 

```
Error: Cannot find module 'ReactNative'
[...]
    at Object.<anonymous> (/Users/ericat/nativeRelay/node_modules/react-native/Libraries/react-native/react-native.js:181:27)
```

**Comment by vning93** [comment]
+1

**Comment by satya164** [comment]
You can't import React Native on server of course. When you import a component which imports React Native, you'll get this error. You can make 2 components, `MyComponent.js` and `MyComponent.native.js` for browser and native respectively.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-8** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
