### ISSUE TITLE
issue with 'Video View' has no proptype for native prop 'RCTVitamioView.testID' of native type 'String' ...... after that error, i have updated the both react-native and node.js .. while trying to implement the plugin of vitamio for video view faced many issues but resolved all of them, now unable to resolve that issue   

### ISSUE THREAD

**Issue by sdfrao** [facebook/react-native#7427]
[He

`)) there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
- [ ] Does this occur on iOS, Android or both?
- [ ] Are you using Mac, Linux or Windows?

**Comment by radko93** [comment]
Please make a description for this issue and post some code examples. Don't use issue title for describing it.

**Comment by grabbou** [comment]
This looks like a 3rd party issue (since the issue is coming from RCTVitamioView). Please open up an issue in the author repo to troubleshoot it.

Thanks :)

**Comment by sdfrao** [comment]
I am trying to add the video in my application, tried different projects(react-native-android-vitamio, react-native-video, react-native-video-gstreamer ....) available on github. unable to rectify the exact error. 
Is react native allow video view??
