### ISSUE TITLE
Versioned documentation points to source on master - Broken PanResponder link

### ISSUE THREAD

**Issue by easyCZ** [facebook/react-native#7428]
The currently deployed version (RN docs 0.25) of the documentation on [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html#content) contains a broken link to [PanResponder.js](https://github.com/facebook/react-native/blob/master/Libraries/vendor/react/browser/eventPlugins/PanResponder.js). I believe this is due to the recent move of the PanResponder into the _Interaction_ module.

I poked around and the documentation website, when built locally, has the correct link. I am assuming the deployed version of RN docs is stale. Could we push the new version so that developers do not end up confused as the current documentation refers heavily to the source of the PanResponder.

This issue is bound to happen frequently as master is likely to be out of sync with a stable release (and the documentation page hardcodes a link to the master branch in [HeaderWithGithub.js](https://github.com/facebook/react-native/blob/master/website/core/HeaderWithGithub.js#L29)).  

This could be solved by building the documentation with a reference to the respective branch. This would prevent the links of older version getting broken as the project evolves. What do you think? I'm happy to send in a PR.

Thanks

Edit: Fix link

**Comment by grabbou** [comment]
cc: @bestander

**Comment by bestander** [comment]
@easyCZ, yes it makes sense.
Send the PR.
