### ISSUE TITLE
UIExplorer - NDK Android compilation issue

### ISSUE THREAD

**Issue by vpasquier** [facebook/react-native#7430]
Hello,

I would like to run UIExplorer to see if animations works properly on Android. (reason: https://github.com/aksonov/react-native-router-flux/issues/355)

However, after looking to existing closed issues, I cannot find the resolution of this problem:

- `./gradlew :Examples:UIExplorer:android:app:installDebug`
- `Execution failed for task ':ReactAndroid:buildReactNdkLib`
- `ndk-build` failure (no explicit exception)

So:

- I run `ndk-build` to compile C libraries
- `react-native/ReactAndroid/src/main/jni/react/Android.mk: Cannot find module with tag 'fb' in import path`

Here my NDK env:

````
ANDROID_NDK=Android/sdk/android-ndk-r11c
NDK_PROJECT_PATH=react-native/ReactAndroid/src/main/jni/react
NDK_MODULE_PATH=react-native/ReactAndroid/src/main/jni
NDK_ROOT=Android/sdk/android-ndk-r11c
````

Thank you very much.

**Comment by charpeni** [comment]
http://stackoverflow.com/questions/36209774/unable-to-run-react-native-uiexplorer-example-project/36213150#36213150

http://facebook.github.io/react-native/docs/android-building-from-source.html#content

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-2** [comment]
Hey @vpasquier and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by vpasquier** [comment]
I wouldn't create an issue without googling it. Im working in OS too, maintaining OS repositories on github so I understand you. And stackoverflow is of course well known of my police forces.

I couldn't find anything related to that. So anyway, i will give up.

One last question:

Why React-Native is using C or C++ libraries to make their UIExplorer works?
Thank you

**Comment by charpeni** [comment]
Don't give up, you must use `android-ndk-r10e` and I linked you this stack-overflow answer because I noticed you used `android-ndk-r11c`, check your NDK env.

NDK is used to build react-native from source instead of the prebuilt version distributed on npm.

**Comment by vpasquier** [comment]
@charpeni Really appreciated. Thank you very much. 

I tried with the 10e to launch again the script itself and it failed again but back to the gradle command it worked like a charm.

Ok, I promise, one last question for my culture and the big picture:

`react-native/ReactAndroid/src/main/jni/react`

Is the NDK part is existing only for performances and memory handling or is there another purpose to provide C++ codes to react-native for Android?

Thank you !

**Comment by ide** [comment]
Performance, ability to call JSC methods, and cross-platform w iOS.

**Comment by vpasquier** [comment]
Thank you very much @ide.

So I'm wondering now if facebook will use Nashorn in future once Android N will be released (java 8 support). Would be better for monitoring i guess. Not for performances I guess...

Thank you all of you.

**Comment by ide** [comment]
I don't think so because FB is investigating JSC-specific optimizations and iOS uses JSC as well. Even the Chrome debugger with V8 causes problems so maybe we want to converge on JSC everywhere if we can provide a good developer experience.
