### ISSUE TITLE
Groups App - Flashing Images

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#7433]
Hi,

I've been looking into how best to deal with the flashing images that occur (I assume) due to them being loaded asynchronously on react native's background thread.

I thought I'd take a look at the Groups app by Facebook and I noticed that when you switch between the initial tabs (Groups, Notifications, Discover, Settings) the images don't flash. However when you go into a group and switch between the tabs there (Group, Photos, Group Chat, Events, Info) the images flash.

It seems like either they're using a native tab bar controller for the first tab bar or are some how retaining the elements and not moving them off of the dom.

Any insight would be much appreciated - at the moment it really doesn't feel native because of this.

Thanks!
Luke

**Comment by brentvatne** [comment]
@lprhodes - Can you post a video demonstrating what you're experiencing so it's clear what you mean by flashing images? Thanks!

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-6** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.
