### ISSUE TITLE
Non-editable TextInput text selection not working on android

### ISSUE THREAD

**Issue by vdrg** [facebook/react-native#7437]
Hi!
On iOS, if you have a non-editable TextInput you can still select the text. On android for some reason this isn't possible. I don't know if this is a bug or if it is how it's intended to be, but it would be great if android also supported this. (A "selectable" prop for Text component would be even cooler :) ).

Thanks!

**Comment by radko93** [comment]
I've tried to make it working using `view.setTextIsSelectable(true)`but that does not help here. I think it's more related to android itself.

**Comment by brentvatne** [comment]
This would be a nice feature to have, I agree! Even better if we can specify what we want to add to the context menu, and callback into JS from it.. :)

**Comment by brentvatne** [comment]
@vdrg - can you create an issue on [ProductPains](https://productpains.com/product/react-native/) for this? Thanks!

**Comment by vdrg** [comment]
https://productpains.com/post/react-native/select-text-in-text-elements someone was faster :P

**Comment by lacker** [comment]
Since this is a feature request rather than a bug I am going to close this issue and point interested folks to product pains instead.
