### ISSUE TITLE
How can I let through a touch to the underlying scroll view?

### ISSUE THREAD

**Issue by o-e** [facebook/react-native#744]
I have a partly transparent View overlayed over a ScrollView and cannot successfully let a touch get through to the underlying ScrollView. I have played around with what is described here https://facebook.github.io/react-native/docs/gesture-responder-system.html but cannot make it to work. Is this possible to do?

**Comment by ide** [comment]
Does pointerEvents="none" work for you?

**Comment by o-e** [comment]
Oh, I had totally missed that one. pointerEvents="box-none" made the trick (with "none" I could not catch touches on children). Big thanks!

**Comment by heyman333** [comment]
@ide That is right!
