### ISSUE TITLE
onNavigationStateChange isn't triggered for pushstate or #!

### ISSUE THREAD

**Issue by robertgonzales** [facebook/react-native#7443]
This can be duplicated in the UIExplorer example. Go to https://medium.com/ and click on an article — the url stays the same.

Any known workarounds?

**Comment by satya164** [comment]
@robertgonzales Is this on Android or iOS?

**Comment by robertgonzales** [comment]
iOS

**Comment by lacker** [comment]
I think this issue is missing enough information - in particular a link to the example code that does not work. Also do medium links actually change the url? I'm going to close this issue but feel free to reopen if you have a link to for example a rnplay.org code sample reproducing the problem.
