### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by nvtcp9x** [facebook/react-native#7446]
I'm have a bug when i use google maps component: **"Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'"** (in Firefox: TypeError: Argument 1 of Window.getComputedStyle does not implement interface Element)
And here is the code:
 ```
 <GoogleMapLoader
        containerElement={
          <div
            {...this.props}
            style={{
              height: `100%`,
            }}
          />
        }
        googleMapElement={
          <GoogleMap
            ref={(map) => (this._googleMapComponent = map) && console.log(map.getZoom())}
            defaultZoom={3}
            defaultCenter={{ lat: -25.363882, lng: 131.044922 }}
          >
          </GoogleMap>
        }
      />
```
This code is very simple (i use [react-google-maps component](https://github.com/tomchentw/react-google-maps)), and in the other project i can run it normaly, but in this project is not, so i really don't know why, please help me fix this problem

**Comment by satya164** [comment]
Looks like you're trying a React component and not React Native. Please file a bug report in [react-google-maps-component](https://github.com/tomchentw/react-google-maps/issues) for bugs in that component.
