### ISSUE TITLE
[ScrollView] Provide a way to set ScrollView's scrollIndicatorInsets separately from the contentInset

### ISSUE THREAD

**Issue by ide** [facebook/react-native#745]
I'm building a refreshable scroll view and this is one of the missing pieces. When the refresh indicator is visible, I increase the top contentInset but want the scrollIndicatorInset to stay the same. Implementing this is probably easy but I would like to solicit API ideas since insets are tricky because of `automaticallyAdjustContentInsets`.

**Comment by rjchatfield** [comment]
+1

**Comment by liuda101** [comment]
+ 1

**Comment by sahrens** [comment]
hmm, I don't have any clever ideas....maybe just a bool coupleContentAndIndicatorOffsets?

**Comment by ericvicenti** [comment]
@ide, if you want to make a quick example playground to demo this issue, it might make a goodfirsttask

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/scrollview-provide-a-way-to-set-scrollviews-scrollindicatorinsets-separately-from-the-contentinset
