### ISSUE TITLE
[Android] Youtube video doesn't work on Webview on Android 4.x. An error occurred. Please try again later. (Playback ID: XXXX)

### ISSUE THREAD

**Issue by 7kfpun** [facebook/react-native#7454]
Youtube video doesn't work on Webview on Android 4.x, but works normally on Android 5.0+ and every version of iOS (both emulator and real device). Do anyone know how to fix it?

Here is the code and the screenshot:
https://github.com/7kfpun/YoutubeReactNative
![screenshot](https://raw.githubusercontent.com/7kfpun/YoutubeReactNative/master/screenshot.png)

- react-native 0.25.1

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
I tried your code into Genymotion Android 4.2.2, the video works fine except full screen mode.

**Comment by 7kfpun** [comment]
Thanks @charpeni ! I tried on Genymotion Android 4.2.2 and it worked, but not on 4.4.4.

<img width="1209" alt="screen shot 2016-05-10 at 10 02 45 am" src="https://cloud.githubusercontent.com/assets/2672802/15133558/74b6559a-1696-11e6-9250-a387e9cfcc74.png">

**Comment by charpeni** [comment]
It's seems an issue with the hardware acceleration on Android 4.4.4 and not specific to React Native since it doesn't work in the native browser.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-4** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
