### ISSUE TITLE
problem with keyboard when using TextInput in modal

### ISSUE THREAD

**Issue by sasikg** [facebook/react-native#7455]
i am using modal to add referral code on top of a view with phone number where it uses 
keyboardType = {"numeric"}
but i am getting 
"Can't find keyplane that supports type 8 for keyboard iPhone-PortraitChoco-DecimalPad; using 1022227301_PortraitChoco_iPhone-Simple-Pad_Default" in my console but key board appears on device , problem occurs when i am using modal no keyboard appear on iPhone
![simulator screen shot 9 may 2016 3 11 02 pm](https://cloud.githubusercontent.com/assets/13790938/15105961/7e92a2b0-15f8-11e6-8502-800adca77f99.png)

**Comment by radko93** [comment]
I think it's an issue with Xcode/iOS SDK. Check [this](http://stackoverflow.com/questions/24871532/xcode-ios-8-keyboard-types-not-supported) Stackoverflow thread.

**Comment by brentvatne** [comment]
@radko93's solution sounds right!
