### ISSUE TITLE
Can't run app in android without adb

### ISSUE THREAD

**Issue by TitoDKM** [facebook/react-native#7457]
Hi.

I create my app and when I run with adb all is OK but when I release the apk and I try to run this on other device it always says "Can't find variable: __fbBatchedBridge"

What can I do?

Thanks

**Comment by radko93** [comment]
There are many answers on Stackoverflow or here, just [Google](https://www.google.pl/#q=Can%27t+find+variable%3A+__fbBatchedBridge) for it.

**Comment by TitoDKM** [comment]
I know, but all answers says that start react native or bundle the asset manually, the first solution works only if device are connected via ADB and the second solutions not works for me so I think that my issue is different.

**Comment by radko93** [comment]
Have you tried setting connecting you device using Wifi then?

**Comment by brentvatne** [comment]
@radko93 is right, lots of answers to this out there :)
