### ISSUE TITLE
Animated.View testing doesn't work [jest]

### ISSUE THREAD

**Issue by acresta88** [facebook/react-native#7458]
Hi, 
I'm trying to have minimal UI tests for my app, to check if the components are rendered correctly. I have an App.js component that contains the state of the app and some Animated.View objects. Before introducing the Animated.View I didn't have a problem to test if the App component was rendered correctly with this code:
`
'use strict';

jest.autoMockOff();

const React = require('react-native');
const utils = require('react-addons-test-utils');

jest.dontMock('../js/containers/App.js');
var App = require('../js/containers/App.js');

describe('App', () => {
  let view;

  function renderView(props) {
    const renderer = utils.createRenderer();
    renderer.render(<App {...props}/>);
    const output = renderer.getRenderOutput();

    return {
      props,
      output,
      renderer
    };
  }
});
`
But as soon as I introduced some Animated.View object it fails with the following (and not too informative message):

`
Runtime Error
SyntaxError: Unexpected identifier
    at Function (native)
    at createMockFunction (*/node_modules/jest-cli/src/lib/moduleMocker.js:153:10)
    at makeComponent (*/node_modules/jest-cli/src/lib/moduleMocker.js:236:9)
    at generateMock (*/node_modules/jest-cli/src/lib/moduleMocker.js:283:16)
    at */node_modules/jest-cli/src/lib/moduleMocker.js:293:20
    at Array.forEach (native)
    at generateMock (*/node_modules/jest-cli/src/lib/moduleMocker.js:288:30)
    at Object.generateFromMetadata (*/node_modules/jest-cli/src/lib/moduleMocker.js:311:16)
    at Loader._generateMock (*/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:256:25)
    at Loader.requireMock (*/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:677:45)
`

I'm using react 0.19 and jest 0.8.2 on mac
is there a way to mock Animated.View? should it work exactly like the View components?

**Comment by damusnet** [comment]
Have you tried using https://github.com/lelandrichardson/react-native-mock ?

**Comment by acresta88** [comment]
@damusnet no I haven't tried that one, should I just replace `const React = require('react-native');` with `const React = require('react-native-mock/mock');` ?

**Comment by damusnet** [comment]
I haven't used it myself so I'm not sure, but I don't think so. There are plenty of tutorials on how to use it though. See [this one](https://medium.com/@thisbejim/testing-react-native-components-with-enzyme-d46bf735540#.9in2fwoex) for example.

@facebook-github-bot stack-overflow

**Comment by brentvatne** [comment]
StackOverflow indeed :) Good luck resolving it! react-native-mock seems like an excellent choice here.
