### ISSUE TITLE
[0.26.0-rc] Keyboard events not firing

### ISSUE THREAD

**Issue by sjmueller** [facebook/react-native#7460]
The following code stopped working in 0.26.0-rc:
```
DeviceEventEmitter.addListener('keyboardWillShow', () => console.log('will show'));
```
I suspect it is because this commit is needed in some way for this release:
https://github.com/facebook/react-native/commit/e72163f0f2182eaae939006ff3bb70420c095605

When I added `init` manually in `RCTKeyboardObserver.m`, the events started firing again.

**Comment by janicduplessis** [comment]
Hit this issue too, good catch. I added the commit to the list to cherry pick in 0.26.

**Comment by rturk** [comment]
@sjmueller I think you can close this issue..

**Comment by sjmueller** [comment]
Roger that!
