### ISSUE TITLE
[TabBarIOS] TabBarIOS.Item selectedIcon always tinted by tintColor

### ISSUE THREAD

**Issue by cauchywei** [facebook/react-native#7467]
I have couples of icons as TabBar Icon, but when I try to set `icon` and `selectedIcon` , I found that (unselected) icon always tinted by gray, selectedIcon always tinted by `tintColor` ( default is blue).
so the gay tint and `tintColor` covered all the icon's detail.

I noticed @urbancvek  has resolved a similar issue in [@urbancvek c206417](https://github.com/facebook/react-native/pull/7264), so we can set `renderAsOriginal` in `TabBarIOS.Item` to prevent gray tinting from iOS default props, but it can't prevent `tintColor` tinting selectedIcon.

I have resolved the issue through modifying `RCTTabItem.m` and `RCTTabItemManager.m`, I will pull a request to fixed it

![image](https://cloud.githubusercontent.com/assets/15445392/15111885/baa80c08-161c-11e6-9c26-b24e4d08f22d.png)
![image](https://cloud.githubusercontent.com/assets/15445392/15113072/b764c6e6-1624-11e6-9c22-7967fe3546db.png)
![image](https://cloud.githubusercontent.com/assets/15445392/15113053/941427fe-1624-11e6-909d-62a2628153aa.png)

**Comment by urbancvek** [comment]
Hey is this picture from the my old code or did you take a picture afterwards you modified the code?
I know you can do this with the code I've written. But you cannot control the color of the image with tintColor or unselectedTintColor but this is intented... renderAsOriginal tells the app "Just ignore the tintColors and render the image as you are given". So all you have to do is create two separate images one for unselected state and selected. Make them look exactly as you would like them to look in an app. Then just pass them as icon and selectedIcon and set renderAsOriginal prop to true. All you have to do next is to set tintColor and unselectedTintColor to control the text under the icon and that's it you should get the result it's expected.

**Comment by cauchywei** [comment]
Thanks for your reply😁
This picture from my modified code

(1) What  confusing me is that I have changed `RCTTabBarItem.m` line 87 from 
```Objective-C
self.barItem.image = _icon;
```
to
```Objective-C
self.barItem.image = [_icon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
```
like your code while it only work with unselectedIcon look like the following picture (I use react-native-0.25.1)
![4397ee77-e9fe-43e3-92c1-697ca8ca1173](https://cloud.githubusercontent.com/assets/15445392/15133946/3ed1c91a-169a-11e6-92b2-45ab37c33be4.png)

(2) So I add the following code (also modified other files ) to control selectedIcon，it works!
```Objective-C
- (void)setSelectedIcon:(UIImage *)selectedIcon
{
    _selectedIcon = selectedIcon;
    self.barItem.selectedImage =  [selectedIcon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
}
```

(3) According to my practice, so my "Enhance TabBarItem" means we can add 3 props ( `renderAsOriginal `, `renderIconAsOriginal`, `renderSelectedIconAsOriginal `) to TabBarItem,  to control      respectively whether or icon and selectedIcon tinted by tintColor 😌

**Comment by urbancvek** [comment]
Yeah you are actually right. Selected icon is controlled by tintColor and it shouldn't be. You can create a PR for that, but I would only use one renderAsOriginal that controls both icon and selectedIcon, because it's more of a bugfix of my code rather than a new feature. Also make sure you create checks if the selectedIcon even exists, otherwise you may receive some errors. Thanks for a fix in advance :D

**Comment by cauchywei** [comment]
Yeah, I will do it later, thanks for your tips :)

**Comment by zhaotai** [comment]
hi, has the problem from @cauchywei been solved ?
I have updated the react-native to 0.27-rc2 but I'm still stuck with that problem.
The selected icon still will be tint by tintColor although I set the renderAsOriginal to true.

**Comment by urbancvek** [comment]
I think the fix is not included in a release yet.. have you found it in release notes. If you want the latest repo with this fix included you can just `npm install https://github.com/facebook/react-native.git`. This will clone this repo's current state and will have everything in it.

**Comment by zhaotai** [comment]
@urbancvek Thanks, guy. I have solved this problem by changing the image. The white space in the picture is replaced by transparent block. And it works. Also, you must change the image type to `.png`.

**Comment by urbancvek** [comment]
Awesome!! 🎉

**Comment by mike866** [comment]
You can use `renderAsOriginal` flag on your `<TabBarIOS.Item>` to fix this issue 😇.
