### ISSUE TITLE
app link is not being installed on phone

### ISSUE THREAD

**Issue by texas697** [facebook/react-native#7468]
using "react-native": "^0.22.0"
for some reason the app link is not being installed on my LG G5 Android 6.0.1. There are no errors when I run "react-native run-android". The only way I can launch it is when it opens by default after installing on the phone. 

The only thing I have changed recently is in the AndroidManifest.xml file. For some reason it stopped working when I tried install on phone. Starting Intent was throwing a error:

```
`Starting: Intent { cmp=com.transistorsoft.rnbackgroundgeolocationsample/.MainActivity }
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.transistorsoft.rnbackgroundgeolocationsample/.MainActivity } from null (pid=15754, uid=2000) not exported from uid 10252
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2812)
	at com.android.commands.am.Am.runStart(Am.java:887)
	at com.android.commands.am.Am.onRun(Am.java:364)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:105)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:251)`
```

 and google research led me to add 
` android:exported="true"`

to this section
```
    <activity
        android:exported="true"
        android:name=".MainActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:label="@string/app_name">
      </activity>
```

which solved that problem. So maybe that has affected it?

**Comment by radko93** [comment]
You can always do `react-native upgrade` to set `AndroidManifest` to default version. Modifying `AndroidManifest` (e.g. changing name or `Intents`) may lead similar issues that you've encountered.

**Comment by brentvatne** [comment]
Are you able to post the full contents of the AndroidManifest beforehand? What did you change? @radko93's tip would work. Also it looks like `react-native run-android` surfaced the "Permission Denial" error -- it could potentially be useful to catch any errors in starting the intent and recommending to check the AndroidManifest and possibly restore it to default, anyone up to send a PR for that?

**Comment by lacker** [comment]
Closing this issue for lack of information. Feel free to reopen if there is information to let us make progress.
