### ISSUE TITLE
Errors in UIExplorer example

### ISSUE THREAD

**Issue by subpublicanders** [facebook/react-native#748]
I'm having lots of problems with the UIExplorer example.
- Changing date in DatePickerIOS leads to 'NSRangeException' in xcode.
- Selecting an item in ListView - Paging leads to a 'NSInvalidArgumentException' in xcode.
etc.

The errors are not leaving any javascript debugging messages, xcode just crashes.
I'm using OSX Yosemite and xcode6.2.
Anyone else?

**Comment by CharlieTruong** [comment]
I'm also getting the same problems on my machine, same setup as @subpublicanders .

**Comment by arthuralee** [comment]
The DatePicker problem seems to be related to #749, #756

**Comment by a2** [comment]
See #749.
