### ISSUE TITLE
scale:0 inside position:absolute container blocks all touch input

### ISSUE THREAD

**Issue by jussi-kalliokoski** [facebook/react-native#7481]
Having a view with `{ transform: [{ scale: 0 }] }` inside a view with `{ position: 'absolute' }` seems to be quite buggy.

Example on the playground: https://rnplay.org/apps/kax0aA

- On iOS, this somehow blocks all touch input to the app.
- On Android, it doesn't block touch input, but the scale is not applied either.

**Comment by lacker** [comment]
Hey, I'm really sorry nobody got to this issue. That said, that rnplay link doesn't work for me any more. It probably decayed at some point. I'm going to close this issue because I don't know what action to take, but if you have a functional repro of this problem feel free to reopen.
