### ISSUE TITLE
ListView behaviour break encapsulation ?

### ISSUE THREAD

**Issue by ahanriat** [facebook/react-native#7484]
Hi everyone !! 😄 

**The issue**
I've noticed the `ListView` behaviour break encapsulation has it shows its internal recycling row mechanism, when removing a row for instance.

**What ??**
When removing a row from a `ListView`, it shifts all rows below instead of removing the row, and I assume this is because the row is recycled.
However, all rows below the removed one are re render with the props of the following row, but the state of the previous row !! 
Here a super class ascii representation of the `ListView` behaviour (__*__ means the row has been re rendered)
```
[component 0, props: 'bob']                               [component 0, props: 'alice']*
[component 1, props: 'alice']    Removing first row =>    [component 1, props: 'john']*
[component 2, props: 'john']          
```
And here is what I expect: (component are not shifted)
```
[component 0, props: 'bob']                               [component 1, props: 'alice']
[component 1, props: 'alice']    Removing first row =>    [component 2, props: 'john']
[component 2, props: 'john']          
```
I'm convinced that components should be pure, and that way there should have no issue with the state inside the component, but even when doing that, there is still some flickering with images when the row is re rendered for example.

**Yeah.. do you have a gist or something ?** 👼 
-> Here it is https://rnplay.org/apps/-eFamQ  ✨  

**My question(s)**
- I know there are many optimisations behind `ListView`, but don't you think `ListView` should have the same behaviour has `ScrollView`, and do the optimisation under the hood ?
- if Yes, do you think it's possible to do so ?

Best !!

**Comment by ide** [comment]
Are you using React keys on your list rows?

**Comment by ahanriat** [comment]
I tried both, and the result is still the same, you can check the example I wrote on React Native Playground https://rnplay.org/apps/-eFamQ

![screen shot 2016-05-10 at 14 31 16](https://cloud.githubusercontent.com/assets/1374161/15146467/e6da26ea-16bb-11e6-9a21-4df1630ab6b7.png)

**Comment by brentvatne** [comment]
@ahanriat - I've found that when it's possible to remove items from rows in ListViews, it's best to pass in an object with `{someId: obj, otherId: obj2}` and an identities array `['someId', 'otherId']` as the first and second arguments to `cloneWithRows` -- see: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListViewDataSource.js#L142-L167

If you don't care about the order, you should just be able to pass in the object :)

This is kind of cryptic and not so well documented I think -- if you'd like to submit a docs PR to improve this it would be appreciated!

**Comment by ahanriat** [comment]
@brentvatne Thanks a lot for the explanation !! Sure I'll submit a PR to improve the documentation !
