### ISSUE TITLE
:app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by juanjopa95** [facebook/react-native#7489]
Im using: 
RN v 0.25
Android Studio 2.1
Android SDK tools 25.1.3
Try with Android Simulator and Genymotion to run the app

--Im doing the tutorial app developing on windows for android, and error apeared:---

Microsoft Windows [Versión 10.0.10586]
(c) 2015 Microsoft Corporation. Todos los derechos reservados.

C:\WINDOWS\system32>cd c:\MyFirstRNProject

c:\MyFirstRNProject>react-native run-android
Starting JS server...
Starting the packager in a new window is not supported on Windows yet.
Please start it manually using 'react-native start'.
We believe the best Windows support will come from a community of people
using React Native on Windows on a daily basis.
Would you be up for sending a pull request?
Building and installing the app on the device (cd android && gradlew.bat installDebug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0251Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 50.626 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by charpeni** [comment]
https://facebook.github.io/react-native/docs/getting-started.html ?

**Comment by brentvatne** [comment]
Hi there! Please follow the getting started guide and if you run into issues then we'd suggest posting them to StackOverflow, until you're able to confirm that it is indeed a bug and not a configuration mistake :) We have limited bandwidth to help out with troubleshooting setup issues. Thanks! Good luck!

**Comment by huangyk** [comment]
I also encountered this problem, how are you, could you tell me how do you solve?

**Comment by juanjopa95** [comment]
Hello, i only installed the Java development kit , build and worked ??

Enviado desde mi iPhone

El 19/10/2016, a las 9:52 a.m., hello_world <notifications@github.com<mailto:notifications@github.com>> escribió:


I also encountered this problem, how are you, could you tell me how do you solve?

-

**Comment by vzhen** [comment]
@huangyk @juanjopa95   
I fixed this by reinstall java jdk. 
This happened to me yesterday because of Windows java updated and cause my new init react native project no longer work.

**Comment by hellomaya** [comment]
If you have Android studio, then try open the android code, and run 'project' ==> 'clean', or just do cd android & ./gradlew clean, probably solve the issue.

**Comment by ashishkankal** [comment]
Im facing the same issue
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files (x86)\Java\jre1.8.0_161 contains a valid JDK installation.

**Comment by rodrigofbm** [comment]
For Linux:
nano ~/.bashrc

export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

if you have Java installed
