### ISSUE TITLE
BuildConfig doesn't propagate properly

### ISSUE THREAD

**Issue by charpeni** [facebook/react-native#7493]
I noticed that `BuildConfig` doesn't seem to be propagated properly on react-native@0.25.1.

I was wondering why the feature introduced with #5071 isn't enabled on debug mode. After some investigations, I noticed that `BuildConfig.DEBUG` from [com.facebook.react.BuildConfig](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/common/build/ReactBuildConfig.java) is always false.

But from the `MainActivity.java`, `BuildConfig.DEBUG` returned true.

Probably related : http://stackoverflow.com/questions/21365928/gradle-how-to-use-buildconfig-in-an-android-library-with-a-flag-that-gets-set

cc @mkonicek @astreet

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by summerYanguang** [comment]
how it solved?

**Comment by charpeni** [comment]
@summerYanguang We don't know at this time.

**Comment by ozamarripa** [comment]
I also noticed the same issue as I wanted to have the debugging in the webview enabled but is relying on the ReactBuidlConfig.DEBUG to be true but is always set as false but I couldn't find a way to fix this, is there any progress on this?

**Comment by foghina** [comment]
Seems like this is a known issue with the gradle toolchain: https://code.google.com/p/android/issues/detail?id=52962

I guess the workaround would be to stop using `BuildConfig` and rely on `DevSupportManager#getDevSupportEnabled()` instead. You can get an instance of `DevSupportManager` from `ReactInstanceManager#getDevSupportManager()`.

PRs welcome :)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/buildconfig-doesnt-propagate-properly

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by theobouwman** [comment]
I'm facing this issue right now. No clue on how to fix it. Plz help
