### ISSUE TITLE
TouchableOpacity is slow with remote debug off

### ISSUE THREAD

**Issue by pbrito** [facebook/react-native#7497]
HI!
I'm trying react-native with NavigationExperimental on a android device.
I notice having a slower interaction with a element `withTouchableOpacity` when remote debug is off.
If I chose the option "debug js remotely" then the response to touch gets snappier .
Is that normal?

**Comment by brentvatne** [comment]
Hi there! This kind of question is better suited for StackOverflow or Discord until you have confirmed that it is a bug. Also, try this with dev mode disabled and you should find that it works as expected :)

**Comment by pbrito** [comment]
Thanks!
What I was missing is that you also have to explicitly do "Reload JS" after disabling dev mode.
Now it works.

**Comment by brentvatne** [comment]
Oh great :) Thanks for following up @pbrito!
