### ISSUE TITLE
Geolocations say:  Unable to retrieve location PERMISSION DENIED

### ISSUE THREAD

**Issue by iDVB** [facebook/react-native#750]
react-native@0.3.1

navigator.geolocation does not seem to work. I've ensured I am selecting ALLOW in the simulator, and I've set the custom cords to be Lat: 55.02  Lng: -1.42  but still getting the error **PERMISSION DENIED**

It also appears that all my linkages are correct:
![Linkages](http://goo.gl/NHyrsw)

**Comment by brentvatne** [comment]
https://facebook.github.io/react-native/docs/geolocation.html#content - "/!\ ATTENTION /!\ You need to add NSLocationWhenInUseUsageDescription key in Info.plist to enable geolocation, otherwise it's going to fail silently! !/ !/" - did you do this?

**Comment by frantic** [comment]
We should probably have the native module check whenever `NSLocationWhenInUseUsageDescription` is set and show warning / redbox. Anyone wants to send a quick PR? :)

**Comment by brentvatne** [comment]
@frantic - on it, PR coming!

**Comment by brentvatne** [comment]
@iDVB - confirmed that with custom location set and `NSLocationWhenInUseUsageDescription` configured, this works:

![screen shot 2015-04-08 at 3 15 11 pm](https://cloud.githubusercontent.com/assets/90494/7056612/1594f1b6-de02-11e4-9047-318b46edf862.png)

**Comment by iDVB** [comment]
Looks like that value is indeed set. 
![value](http://goo.gl/02Rdqu)

BTW, the code I'm using is from this [tutorial](http://www.raywenderlich.com/99473/introducing-react-native-building-apps-javascript).

**Comment by brentvatne** [comment]
@iDVB - that happened to me and then I went into Debug > Location and chose Apple, pressed CMD+r to reload and it worked. Then switching to a custom location worked too, after that. Let me know if that helps!

**Comment by iDVB** [comment]
WORKS! Kinda fiddly setup though. Not even sure what fixed it as I did, multiple refreshes, restarts of the Simulator and swapping the location from **custom** to **Apple** and back.
Thanks for the help.

**Comment by coderdave** [comment]
I also keep getting "permission denied" even with `NSLocationWhenInUseUsageDescription` in the `Info.plist`.

**Comment by kyleskwon** [comment]
Restarting the simulator helped me fix this issue

**Comment by milon87** [comment]
navigator.geolocation.watchPosition through permission denied in Android OS>5

**Comment by QQizi** [comment]
Problem still occur for me.
NSLocationAlwaysUsageDescription & NSLocationWhenInUseUsageDescription are set

**Comment by QQizi** [comment]
The info.plist need NSLocationAlwaysAndWhenInUseUsageDescription & NSLocationAlwaysUsageDescription aswell

**Comment by 91ranjan** [comment]
Isn't this correct?

         <key>NSLocationAlwaysUsageDescription</key>
	<string>Some description</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Some description</string>
