### ISSUE TITLE
not able to use navigator again when used in componentWillMount.

### ISSUE THREAD

**Issue by sasikg** [facebook/react-native#7503]
this is my code

class SplashPage1 extends Component {
  componentWillMount() {
    var navigator = this.props.navigator;
    setTimeout(() => {
      navigator.replace({
        name: 'splashpage2',
      });
    }, 3000);
  }

render() {
    return (
      <Navigator
       initialRoute={{name: ''}}
       renderScene={(route, navigator) => (
        <View style={styles.innercontainer}>
          <TouchableOpacity style={styles.nextButton}
            onPress={this.onButtonPressed}>
            <Image style={styles.nextButton}
              source={require('../img/startexperiencing_btn.png')}/>
          </TouchableOpacity>
        </View>
        )}
      />
    );
  }

onButtonPressed() {
    this.props.navigator.push({
      name: 'main',
    });
  }
}

when the button event is fired , i get the error as

[tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'this.props.navigator')

**Comment by brentvatne** [comment]
Hi there!

Please post these types of issues to StackOverflow! The problem, by the way, is that you're using ES6 classes and not binding the callback (`onPress={this.onButtonPressed.bind(this)}`)
