### ISSUE TITLE
onLayout works differently in iPhone and iPad simulators

### ISSUE THREAD

**Issue by anttitakalahti** [facebook/react-native#7504]
This might be an issue with the xCode but I am getting strange values for Dimensions.get('window'). In iPhone simulator it works as expected and shows the new values for height and width but using iPad simulator (iPad Air 2 and iPad Pro) I get the old height and width. This results in broken views as I try to fit the login screen to full page using margin for status bar and calculating the height of the keyboard.

**Comment by radko93** [comment]
This was also reported here #7340. I'm going to test this on iOS now.

**Comment by radko93** [comment]
I've made a little research and it seems to be a iOS behaviour (bug). Made an empty app and with this code:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[NSNotificationCenter defaultCenter] 
         addObserver: self 
         selector: @selector(deviceOrientationDidChange:) 
         name: UIDeviceOrientationDidChangeNotification object: nil];
    
    return YES;
}

- (void)deviceOrientationDidChange:(NSNotification *)notification {
    // using this statusBarOrientation since code in RN repo is depreciated in iOS8
    NSLog(@"%ld", (long)[[UIApplication sharedApplication] statusBarOrientation]);
}
```
From my tests:
* iPhone is fine
* iPad:
```
2016-05-11 14:50:28.498 Playground iOS[66600:4777507] 1 // on startup
2016-05-11 14:50:33.097 Playground iOS[66600:4777507] 1 // after screen rotation from portrait to landscape
2016-05-11 14:50:42.946 Playground iOS[66600:4777507] 3 // back from landscape to initial portrait orientation
```

So it seems the first orientation change is not being set properly.

Tested on XCode 7.3, iPhone and iPad both simulators.

**Comment by ghuh** [comment]
Note that, for #7340, I tested this on a physical iPhone 6s and a physical iPad Air 2 and got the same behavior so this is not just a simulator issue.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/onlayout-works-differently-in-iphone-and-ipad-simulators

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (73/60 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:44822)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsfU-004M1X-EH
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:57:02 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsfT-0002EE-LV
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:57:00 -0700
Date: Thu, 27 Oct 2016 14:55:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605419;
	bh=z7KB6sGjySXFUylsEm7uD1CKlEaRHa5Uu2j6Ud1Wat8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VJqe+kq3oFwHzEq13qYnrXquk/LeSQQCLxGOqK+YLlQ9oyUf8oG0hZUDj8udyUgCJ
	 nFticp0mtgdmIsrDb6I97GpGRAxqn6cUCLI9+s92FRpx6wYtRVuiRQlrLzjuqrK+RB
	 Zq+mWZ6H0vw094yPkrMq5UPAu7zosgmKJnVoPoCc=
