### ISSUE TITLE
Process 'command 'node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by devux** [facebook/react-native#7507]
Hello all,
         I'm getting these error while building APK using this https://facebook.github.io/react-native/docs/signed-apk-android.html

Error:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

**Comment by damusnet** [comment]
I just had this error myself, and saw it on other threads, though I can't seem to find them.
Make sure you have node in your path, and maybe try rebooting your computer. This did it for me.
If that works, did you have Android Studio open at the same time?

**Comment by devux** [comment]
Hi damusnet thanks for reply. I think the error is due to react-native-router-flux after removing react-native-router-flux plugin I didn't get the error but I need the plugin for routing any other way ?? to do this?

**Comment by charpeni** [comment]
I'll close this issue since it's related to react-native-router-flux. https://github.com/aksonov/react-native-router-flux/issues/666

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-0** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by petrbela** [comment]
FWIW, closing Android Studio fixed the problem.
