### ISSUE TITLE
[WebView iOS] autoplay not working in inline videos

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#7512]
```
<WebView
...
allowsInlineMediaPlayback={true}
mediaPlaybackRequiresUserAction={false}
/>
```
Autoplay works in android, but not on iOS

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by charpeni** [comment]
> NOTE : "In order for video to play inline, not only does this property need to be set to true, but the video element in the HTML document must also include the webkit-playsinline attribute."
[WebView documentation](https://facebook.github.io/react-native/docs/webview.html#allowsinlinemediaplayback)

Did you check this?

**Comment by stereodenis** [comment]
@charpeni yep. I have this attribute

**Comment by dsibiski** [comment]
@stereodenis Is there a sample url that we can use for testing? Perhaps a sample app you can create on rnplay.org?

What version of RN are you using?

**Comment by stereodenis** [comment]
problem was in react-native-bridge

**Comment by stereodenis** [comment]
https://github.com/alinz/react-native-webview-bridge/pull/90
