### ISSUE TITLE
[Node 4] npm install fails

### ISSUE THREAD

**Issue by oreqizer** [facebook/react-native#7515]
I'm using v. 0.26-rc (tried also 0.25). I'm getting this following error on my travis ci build on Node 4:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/129483321/log.txt

I can't really comprehend what's going on besides some C++ compiler issues, sorry.

**Comment by dsibiski** [comment]
@oreqizer Does using npm3 help any?

**Comment by oreqizer** [comment]
yes, it works on both Node 5 and 6

**Comment by dsibiski** [comment]
I meant to ask does using npm3 with Node 4 solve the issue? It appears that you're using npm2 in the error log.

**Comment by oreqizer** [comment]
haven't tried that - i'll try and come back

**Comment by ide** [comment]
You might need to update gcc -- make sure your C compiler tools are up to date. Some of the tests for RN run using Node 4 + npm 2 so I think the issue is local to your computer.

**Comment by oreqizer** [comment]
that's a Travis CI test, not mine at home

**Comment by ide** [comment]
Same thing -- try updating GCC on your Travis box.

**Comment by bestander** [comment]
RN Travis is running Node4 and runs e2e tests fine https://travis-ci.org/facebook/react-native/jobs/130779992
