### ISSUE TITLE
Should NavigationExperimental reducers accept 'reset' as one of default action types?

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#7516]
I want to reset `navigationState` tree completely into `initialState` when user logs out.
By looking at the source, default reducers currently do not support 'reset' action.

Could it be a good idea to implement standard 'reset' support for every reducer?
So they will simply return `initialState` when they receive an action with type 'reset'?

**Comment by mmazzarolo** [comment]
@joonhocho you should probably follow [this](https://github.com/facebook/react-native/issues/7422)

**Comment by jmurzy** [comment]
@joonhocho NavigationExperimental has no intention to deal with hierarchical navigation states, @807726bcb47ef5b17860c5969a661bee1f8fc651.

🍺

**Comment by lacker** [comment]
This looks like a "wontfix" so I am going to close this issue. You might want to check out ExNavigation, FWIW.
