### ISSUE TITLE
Documentation on how to add  and use cocoa pods to react-native project?

### ISSUE THREAD

**Issue by prabakarviji** [facebook/react-native#7517]
It would be great if there's documentation about how to add and use cocoa pods libraries in RN for iOS.If it is fine, we'll submit a PR.

**Comment by radko93** [comment]
There is configuration setup is [here](https://facebook.github.io/react-native/docs/embedded-app-ios.html#install-react-native-using-cocoapods). Installing Cocoapods it's the same as usual and there is a article about linking native libraries [here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content).
