### ISSUE TITLE
[Android] Clipboard.getString() error: "...only one callback may be registered to a function in a native module."

### ISSUE THREAD

**Issue by actonw** [facebook/react-native#7522]
I'm trying to use the `Clipboard` module. It works fine in iOS, however, in Android I am getting the following error:

<img width="493" alt="screen shot 2016-05-11 at 3 22 47 pm" src="https://cloud.githubusercontent.com/assets/19315311/15198489/79ce0cd4-178c-11e6-987b-1ffe5a7a505e.png">

To test, I made a new React Native project and tried the following code:

``` javascript
// index.android.js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Clipboard
} from 'react-native';

class clippy extends Component {
  render() {
    Clipboard.getString();
    return (
      <View>
        <Text>
          Welcome to React Native!
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('clippy', () => clippy);
```

And I am getting the same error.

Any thoughts?

**Comment by TanTan-TT** [comment]
await Clipboard.getString();

**Comment by actonw** [comment]
@TanTan-TT using es7 or not does not seem to affect the issue.

**Comment by wkh237** [comment]
This happens on android if you invoke the same Callback in native more than once.

**Comment by actonw** [comment]
@wkh237 can you explain more? I am not attaching a callback in this scenario; in my own app, I'm attempting to use the promise interface (which I assume creates a callback internally). How am I supposed to use the `Clipboard` module?

**Comment by Fanghao** [comment]
Something similar also happened to our prod iOS app which is using 0.26.
`The callback showActionSheetWithOptions() exists in module RCTActionSheetManager, but only one callback may be registered to a function in a native module.`

**Comment by RubenSandwich** [comment]
This is also happening to me, expect for a custom native module I developed, it seems to be related to passing in the promises reject and resolve block to a native method.

**Comment by bradens** [comment]
Running into this...on ios with a custom native module.  The native module call is in a resolve block of a promise, so I would suspect that @RubenSandwich is correct.

**Comment by sajjad26** [comment]
Also ran into this on android in a custom module for audio player.
`The callback setOnCompleteCallback() exists in module RNAudioPlayer, but only one callback may be registered to a function in a native module`
Everything works when the first time audio played, but when the audio is played the second time the above error occurs when the audio completes.

**Comment by jbrodriguez** [comment]
I'm getting this as well with a custom native module.

Not sure how to fix it though.

I've checked the AsyncStorage implementation as a reference, and I'm not doing anything different.

**Comment by jbrodriguez** [comment]
Well, turned out I was invoking the callback twice in the native method and thus the error.

**Comment by Mr7Cat** [comment]
but office doc say :"A native module is supposed to invoke its callback only once. It can, however, store the callback and invoke it later.", how to fix it? I need to invoke the callback more than once...

**Comment by alextkd** [comment]
On iOS is the same problem

**Comment by alextkd** [comment]
I used NativeAppEventEmitter in order to capture the events sent from Native and on react native you need to use the bridge to send them
```
[self.bridge.eventDispatcher sendAppEventWithName:@"callStatusNotification"
                                                     body:@{@"state": userInfo[@"state"], @"callID": userInfo[@"CallID"], }];
```

And on RN app:

```
this.callStatusListener = NativeAppEventEmitter.addListener(
                'callStatusNotification',
                this.handleCallStateChange.bind(this)
            );
...
this.callStatusListener.remove(); //will stop notifications
```

**Comment by ytqiu** [comment]
@Mr7Cat, it's saying we can store callback reference, but can not reference callback directly. so we can use: __block RCTResponseSenderBlock senderBlock = callback; temp store callback.

**Comment by FaiChou** [comment]
```
/**
 * These block types can be used for mapping input event handlers from JS to view
 * properties. Unlike JS method callbacks, these can be called multiple times.
 */
typedef void (^RCTDirectEventBlock)(NSDictionary *body);
typedef void (^RCTBubblingEventBlock)(NSDictionary *body);
```

It's ok

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-clipboardgetstring-error-only-one-callback-may-be-registered-to-a-functi

**Comment by Kottidev** [comment]
@hramos , i got this error with package react-native-firebase : 

> Unhandled JS Exception: The callback createShortDynamicLink() exists in module RNFirebaseLinks, but only one callback may be registered to a function in a native module.
