### ISSUE TITLE
Sharing code between React Native and React

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#7523]
Hello, 

Is there a roadmap of sharing views between React and React Native code? What's the canonical place to look at it?

**Comment by ide** [comment]
Not sure there's any roadmap for this beyond the fact that you can write high-level components that require just "react" and they'll work everywhere. cc @vjeux

**Comment by vjeux** [comment]
Nothing planned indeed. You should look at react-native-web project which is pretty exciting in that direction

**Comment by joewood** [comment]
There was a recent blog post about suggested directory layout of regular React and React Native that had some good suggestions: http://jkaufman.io/react-web-native-codesharing/

**Comment by ihor** [comment]
I've just made a blog post how I share code between React and React Native applications http://ihor.burlachenko.com/code-sharing-between-react-and-react-native-applications/
