### ISSUE TITLE
Android RefreshControl 「undefined is not an object (evaluating 'ReFreshLayoutConsts.SIZE')」

### ISSUE THREAD

**Issue by LiushuiXiaoxia** [facebook/react-native#7528]
I just use RefreshControl in ListView, and import RefreshControl,but it not work.

undefined is not an object (evaluating 'ReFreshLayoutConsts.SIZE')

**Comment by charpeni** [comment]
What version of React Native are you using ?

Can you provide a snippet ? You can even host it on [rnplay.org.](rnplay.org)

**Comment by janicduplessis** [comment]
I think you have a type, it should be `RefreshLayoutConsts.SIZE` and not `ReFreshLayoutConsts.SIZE`.

**Comment by LiushuiXiaoxia** [comment]
"dependencies": {
        "react": "^0.14.8",
        "react-native": "^0.24.1"
    }

**Comment by janicduplessis** [comment]
This value is imported from native, have you updated your react native version recently? Maybe try runnning `react-native update` and rebuilding the app.

**Comment by LiushuiXiaoxia** [comment]
I have just update the react native version

```
    "dependencies": {
        "react": "^0.14.8",
        "react-native": "^0.25.1"
    }
```

but it stil does not work

**Comment by janicduplessis** [comment]
I meant updating the project files with `react-native upgrade`. Could you also link the content of your `android/app/build.graddle` file?

**Comment by LiushuiXiaoxia** [comment]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:0.20.1"
}

**Comment by janicduplessis** [comment]
Ok, it seems like your android native version (0.20) doesn't match your js (0.25). Running `react-native upgrade` should fix it.

**Comment by janicduplessis** [comment]
The android build files changed a lot around version 0.21, now the native library is installed from node_modules instead of downloading it from maven.

**Comment by LiushuiXiaoxia** [comment]
config maven to node_modules

```
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../React/node_modules/react-native/android"
        }
```
config build.gradle
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
}
```

```
    renderContent() {
        if (this.state.renderPlaceholderOnly) {
            return (
                <View style={{flex:1, justifyContent:'center'}}>
                    <Text>正在加载中...</Text>
                </View>
            );
        } else {
            return (
                <ListView
                    style={styles.listview}
                    dataSource={this.state.data}
                    enableEmptySections={true}
                    renderRow={(rowData)=>{
                            return (
                                <ListItem theme={rowData} onItemClick={this.onItemClick.bind(this)}/>
                            );
                        }}
                    refreshControl={
                      <RefreshControl
                        refreshing={this.state.refreshing}
                        onRefresh={this.onRefresh.bind(this)}
                      />
                    }
                />
            );
        }
    }
```
but it stilly does not work.

```
 E/ReactNativeJS: undefined is not an object (evaluating 'RefreshLayoutConsts.SIZE')
```

我也是醉了。。。

**Comment by LiushuiXiaoxia** [comment]
![react](https://cloud.githubusercontent.com/assets/3643574/15246659/36845a3a-1941-11e6-84fb-9302f555f5b4.jpg)

**Comment by dyguests** [comment]
Same problem.
It works on iOS.works on release apk on Android.not work on debugging on Android.

```json
  "dependencies": {
    "react": "15.3.2",
    "react-native": "0.37.0",
  }
```
![image](https://user-images.githubusercontent.com/7933189/36705958-a6fd9f8c-1ba2-11e8-947c-581cb93d83d3.png)
![image](https://user-images.githubusercontent.com/7933189/36705973-b7ee4558-1ba2-11e8-9c5c-357d99a81419.png)
