### ISSUE TITLE
how to put line through text ?

### ISSUE THREAD

**Issue by baofen14787** [facebook/react-native#753]
<Text>  not support css : 

```
text-decoration: line-through;
```

This function is how to achieve ?

**Comment by iostalk** [comment]
Help!Help!

**Comment by mattotodd** [comment]
Not all css is available for use, yet.

**Comment by brentvatne** [comment]
You can implement your own custom component for this until it's added in to core: [strike through on UILabel](http://stackoverflow.com/questions/13133014/uilabel-with-text-struck-through) and [how to create your own components for react-native](https://github.com/facebook/react-native#extensibility)

**Comment by baofen14787** [comment]
@brentvatne  thanks

**Comment by vkurchatkin** [comment]
This could be trivially added the same way as in https://github.com/facebook/react-native/pull/482 with `NSStrikethroughStyleAttributeName` attribute

**Comment by KJlmfe** [comment]
I contribute the code  and made a pull request https://github.com/facebook/react-native/pull/845#

Wait for FB merge.

**Comment by brentvatne** [comment]
@KJlmfe - thanks, closing this issue as the discussion as moved to the PR now :smile:

**Comment by Premjeet-Singh** [comment]
In react-native you can use :    
             textDecorationLine: 'line-through'
