### ISSUE TITLE
justifyContent doesn't work for nested elements of Image with internal source

### ISSUE THREAD

**Issue by mrharel** [facebook/react-native#7534]
Basically, I was trying to center a `View` inside an `Image` which is used as the background image. 

When the image source is using a `uri:'http...` scheme everything works as expected as can be seen here:
https://rnplay.org/apps/75XPrQ

However, if we change the source scheme to `<Image source={require('image!image1')}>....</Image>` then the nested items are not centered. 

Here is the render code:
```
<View style={{flex:1}}>
      <Image
      	source={{uri:"http://www.planwallpaper.com/static/images/colorful-triangles-background_yB0qTG6.jpg"}}
      	resizeMode="cover"
         style={{flex:1}}
      > 
      	<View
          style={{height:60, backgroundColor:"red", justifyContent: 'center' }}
        >
          	<View
           	 style={{height:40, width: 40, backgroundColor:"blue", alignSelf:"center" }}
          	></View>
        	</View>
				</Image>

      </View>
```

this result the following:

![screen shot 2016-05-12 at 16 09 38](https://cloud.githubusercontent.com/assets/473889/15217495/0df5f05a-185c-11e6-9989-fd1792cee929.png)

but when we change the source scheme the blue square disappears, and we can't center the blue square anymore.

**Comment by lacker** [comment]
I didn't know that views inside images were supported. I would suggest just doing the layout with View components, and only having images be children. Either way this is now a pretty old issue so I am going to close it. If that workaround doesn't work for you then please feel free to open a new issue.
