### ISSUE TITLE
Nested Text nodes do not render margin or padding in their layout

### ISSUE THREAD

**Issue by nicinabox** [facebook/react-native#7536]
## Summary

I'm trying to intend a nested list (`ul > li > ul`) using `Text` with `paddingLeft` applied. On nested `Text` nodes neither margin or padding seems to be applied to the layout. I'm not totally sure if this is a bug or if this is the expected behavior with the relative Text layout (but it still seems less than ideal).

<img width="305" alt="screen shot 2016-05-12 at 11 17 33 am" src="https://cloud.githubusercontent.com/assets/246280/15221944/2e7fd904-1833-11e6-807f-c0b055f9edd4.png">

## Example

https://rnplay.org/apps/5_STOQ

## Versions

I'm using 0.23.1, but the issue is also present in RNPlay using 0.24.1. I'm not sure about 0.25.0.

## Platforms

iOS, Android

## Development env

OSX

**Comment by rogchap** [comment]
This is due to the way nested text renders (for convenience). Think of nested text as `inline` elements and the (most) outer text to be a `block` element.

You can use `View`s to get the same effect, it's just the text is not nested:

``` jsx
<View style={styles.ul}>
  <Text style={styles.li}>
    {BULLET}
    item one
  </Text>
  <Text style={styles.li}>
    {BULLET}
    item two
  </Text>
  <View style={[styles.ul, styles.nestedUl]}>
    <Text style={styles.li}>
      {BULLET}
      nested one
    </Text>
    <Text style={styles.li}>
      {BULLET}
      nested two
    </Text>
  </View>
</View>
```

https://rnplay.org/apps/vf1slA
