### ISSUE TITLE
[0.26.0-rc] HMR for functional components broken

### ISSUE THREAD

**Issue by oreqizer** [facebook/react-native#7539]
Hi,

hot-reloading functional components is broken in version **0.26.0-rc**, throwing the following error:

<img width="376" alt="screen shot 2016-05-12 at 17 51 33" src="https://cloud.githubusercontent.com/assets/11172408/15227945/d7019724-1889-11e6-9980-901b50a9ac87.png">

The file I tested it on is:
https://github.com/oreqizer/reactizer/blob/develop/src/native/app/App.js

on 0.25, both variants work.
on 0.26-rc, only the 'class' one works.

Opening it from scratch or reloading fixes this. it gets broken only by hot-reloading

**Comment by oreqizer** [comment]
OK reporting that this is solved in 0.27-rc.

**Comment by grabbou** [comment]
Cherry-picked into 0.26.1 :)
