### ISSUE TITLE
React.findNodeHandle is undefined

### ISSUE THREAD

**Issue by powerc9000** [facebook/react-native#7544]
After version 0.25 React.findNodeHandle is undefined.

This is because you now have to require React from the React package instead of ReactNative and findNodeHandle was removed

**Comment by ide** [comment]
This is intentional. The solution is to write this:

```js
import ReactNative, {
  // your other imports
} from 'react-native';

...

ReactNative.findNodeHandle(component)
```

**Comment by powerc9000** [comment]
Ahh I thought i had done this and was under the impression it didn't work
but maybe I made a mistake.

**Comment by AndrewJikun** [comment]
it didn't work.

**Comment by AndrewJikun** [comment]
import ReactNative, {
  // your other imports
} from 'react-native';

...

ReactNative.findNodeHandle(component)   it did not work
