### ISSUE TITLE
Images are not bundled in the package when creating offline bundle

### ISSUE THREAD

**Issue by akaila** [facebook/react-native#7561]
Versions tried: 0.23.x, 0.25.1

I have an image in my project that I am requiring as part of my RN view. This is an image on my local file system (and not in iOS/Android project). Running the code in simulator shows up the image.

However when I create an offline bundle the image is not packaged as part of the js bundle and as a result the require returns null and no image shows up. This is one of the major features after deprecation of image! and should be fixed IMO.

**Comment by damusnet** [comment]
Can you provide some test code to reproduce the issue please?

**Comment by damusnet** [comment]
@facebook-github-bot label Needs Response from Author

**Comment by charpeni** [comment]
Are you using react-native-router-flux ? Could be related https://github.com/aksonov/react-native-router-flux/issues/671

**Comment by damusnet** [comment]
@facebook-github-bot close

**Comment by damusnet** [comment]
@facebook-github-bot no-reply

**Comment by githubxun** [comment]
i have the same issue ! ! !

**Comment by charpeni** [comment]
Be sure you don't have anything that can block the access to these assets like image viewer, Android Studio, xcode etc.

**Comment by charpeni** [comment]
@facebook-github-bot no-reply

**Comment by facebook-github-bot-5** [comment]
Closing this issue as more information is needed to debug this and we haven't heard back from the author. Once there's more information we can reopen the issue.

**Comment by akaila** [comment]
Sorry this fell off radar. Here are the steps to reproduce it:
- Create a RN project with images baked as assets (example: https://ifelse.io/2015/11/16/react-native-quickstart-and-including-images/)
- Run and execute the project in XCode simulator -> everything works fine and image shows up
- Now create an offline bundle using curl -> Notice that the image is not baked into the bundle anymore!
- Run the offline bundle on a device -> No image shows up !

**Comment by damusnet** [comment]
@facebook-github-bot open

**Comment by damusnet** [comment]
@facebook-github-bot open

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by facebook-github-bot-6** [comment]
Okay, reopening this issue.

**Comment by charpeni** [comment]
@akaila I reopened this issue, but be sure that doesn't have something blocking the access to the image, like Image Viewer, may be the packager ?

> Now create an offline bundle using curl -> Notice that the image is not baked into the bundle anymore!

Can you explain ?

**Comment by akaila** [comment]
That is correct. I am not opening the image in a viewer. Anyhow if that was the case then my local packager would fail as well.

**Comment by alexkendall** [comment]
Im currently having this issue RN 0.34

**Comment by lacker** [comment]
I think we need a more concise repro to make progress. Images do seem to work in offline bundles in general so it seems like there must be something else going on in the setups that don't work. I'm going to close this issue but if someone has a specific repro of this happening please feel free to reopen.

**Comment by mienaikoe** [comment]
currently having this issue in RN 0.48

**Comment by MrtnvM** [comment]
Same issue in RN 0.52. Please fix it
