### ISSUE TITLE
[iOS] Race condition causing deadlock during app startup due to module initialization process

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#7562]
I was running my app with commit 68b2f49a314ae07681353d89b89f2a7f28cef10d and I sometimes hit a deadlock during startup. Here's what I learned during debugging.

The race condition is in the initialization of the native modules.

Activity on the main thread:
- The main thread is [looping through the modules to initialize them](https://github.com/facebook/react-native/blob/68b2f49a314ae07681353d89b89f2a7f28cef10d/React/Base/RCTBatchedBridge.m#L375-L392).
- This leads to this thread wanting to initialize the `UIManager`. However, the background thread (below) is already in the middle of initializing the `UIManager`. Consequently, the lock for the module data for the `UIManager` is locked and the main thread waits for the lock to become unlocked (this will never happen).

Activity on a background thread:
- The background thread is [looping through the modules to collect their configs](https://github.com/facebook/react-native/blob/68b2f49a314ae07681353d89b89f2a7f28cef10d/React/Base/RCTBatchedBridge.m#L413-L418). This is causing modules to become initialized.
- This leads to this thread starting to initialize the `UIManager` (at this point, this thread holds the lock for the module data for the `UIManager` and it will never release it)
- While initializing the `UIManager`, it runs the `UIManager`'s `setBridge` method. [`setBridge` causes the initialization process for the `AccessibilityManager` to start running](https://github.com/facebook/react-native/blob/68b2f49a314ae07681353d89b89f2a7f28cef10d/React/Modules/RCTUIManager.m#L314).
- The `AccessibilityManager` requires the main thread so this thread attempts to run code on the main thread causing the deadlock: the main thread is waiting for this thread to release the `UIManager`'s lock and this thread is waiting to run code on the main thread.

### Workaround

Commenting out [this code](https://github.com/facebook/react-native/blob/68b2f49a314ae07681353d89b89f2a7f28cef10d/React/Modules/RCTUIManager.m#L311-L314) seems to work around the issue.

cc @nicklockwood

**Comment by lacker** [comment]
It's not clear to me how to make progress here, I think we need a minimal sample app or some more info about thread state during the deadlock, if this bug is still happening. I'm going to close the issue but feel free to reopen if you do have more information.
