### ISSUE TITLE
[iOS] build failed with travis

### ISSUE THREAD

**Issue by xudafeng** [facebook/react-native#7565]
I guess React Native can't run tranforming success in travis ios env, but I can not get the reason for too many days.

This is the [travis/log](https://travis-ci.org/xudafeng/autoresponsive_react_native_sample/builds/130211593).This is the [repo](https://github.com/xudafeng/autoresponsive_react_native_sample).

```
 "react-native": "~0.19.0"
```

```
xcodebuild clean build -scheme autoresponsive_react_native_sample -configuration Debug -sdk iphonesimulator9.3 CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
```

**Comment by ide** [comment]
Tests on Travis CI are currently passing on master: https://travis-ci.org/facebook/react-native/branches so I believe the problem is with your own repo and not react-native.
