### ISSUE TITLE
[Docs] Make Platform/OS combinations linkable in "Getting started"

### ISSUE THREAD

**Issue by Andreyco** [facebook/react-native#7574]
I really love new concept of picking Platform/OS combination in "Getting started" docs section.   
What I miss is ability to link to "active" combination. This is crucial and easier to share.

**Comment by janicduplessis** [comment]
cc @JoelMarcey @vjeux

**Comment by vjeux** [comment]
Agreed, we have an internal task for it. Not sure when we'll get to it. The search results are also broken because of the toggler

**Comment by Andreyco** [comment]
What's the scope of your internal task? Are you considering support for this pattern (and doing it right) site-wide, or just fixing it in "Getting started"

**Comment by damusnet** [comment]
@facebook-github-bot label Documentation

**Comment by vjeux** [comment]
Only looking to fix the hash portion of the url. Not planing to expand this design to more places on the website for now

**Comment by Andreyco** [comment]
Thanks for the info

**Comment by lacker** [comment]
This design is improved a lot now so i'm marking this issue as fixed
