### ISSUE TITLE
[NavigationExperimental] When scroll mapview to right, NavigationView swipes back at the same time.

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#7576]
I have a MapView inside a NavigationCardStack (where you can swipe right to go back to the previous scene).

When I scroll right inside the MapView, the swipe event is sent to both MapView and NavigationView, so that MapView scrolls as well as NavigationView animates 'swiping back' motion.

**Comment by skevy** [comment]
cc @ericvicenti @hedgerwang

**Comment by ericvicenti** [comment]
Does MapView respect the touch responder system? The map view should return true from `onMoveShouldSetResponder`, and the NavigationCard will not become the touch responder

**Comment by joonhocho** [comment]
https://github.com/facebook/react-native/issues/7572 may be related?

**Comment by lacker** [comment]
This looks stale and also we are about to deprecate MapView in favor of react-native-maps so I think this is either working or a wont-fix. I'm going to close this issue and suggest that people migrate to react-native-maps if this is recurring.
