### ISSUE TITLE
[0.26.0-rc] [Android] Could not find generated setter for class

### ISSUE THREAD

**Issue by scriptjs** [facebook/react-native#7587]
Latest rc emits the following from logcat:

05-16 14:41:46.577  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
05-16 14:41:46.578  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
05-16 14:41:46.579  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
05-16 14:41:46.579  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
05-16 14:41:46.580  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
05-16 14:41:46.581  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
05-16 14:41:46.584  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
05-16 14:41:46.585  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
05-16 14:41:46.585  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
05-16 14:41:46.586  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
05-16 14:41:46.586  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
05-16 14:41:46.600  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
05-16 14:41:46.601  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
05-16 14:41:46.601  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
05-16 14:41:46.616  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
05-16 14:41:46.625  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
05-16 14:41:46.625  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
05-16 14:41:46.626  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
05-16 14:41:46.627  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
05-16 14:41:46.628  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
05-16 14:41:46.629  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
05-16 14:41:46.629  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
05-16 14:41:46.629  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
05-16 14:41:46.630  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageViewManager
05-16 14:41:46.630  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textfrescosupport.FrescoBasedReactTextInlineImageShadowNode
05-16 14:41:46.630  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
05-16 14:41:46.634  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
05-16 14:41:46.634  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
05-16 14:41:46.635  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
05-16 14:41:46.636  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
05-16 14:41:46.637  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
05-16 14:41:46.639  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
05-16 14:41:46.639  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
05-16 14:41:46.639  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
05-16 14:41:46.640  2311  2329 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager

I am running this from Mac OSX.

This may be a duplicate of https://github.com/facebook/react-native/issues/6692 however that issue specifies version 0.22. This occurs with any app generated using the cli.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/0260-rc-android-could-not-find-generated-setter-for-class

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:50711)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzseF-004LQD-Fa
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:55:45 +0000
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzseD-0000vb-Ok
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:55:42 -0700
Date: Thu, 27 Oct 2016 14:55:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605340;
	bh=IATIltSkqhMOauGXaNz6E6gvuo3dKYONJZ+dzTiZvKQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aiSrKhGCvAquc/9b+aeg1wzKrcwRbb98XUffJ32eWJEDhdci4+3I6XKyZe9iAbMAt
	 tIkcGBZMB4F92zHnpFQgyHK98pK2xhE+fb2Vk6HQz/8MZGligZcFT6h3/TgPcRpslg
	 sXjL0dsTPWaUOg3+1HMoz3e/Ow0aRZbXlfKDMMtE=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (70/60 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:44766)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsez-004Lm7-2O
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:30 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsey-0002B8-4P
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:29 -0700
Date: Thu, 27 Oct 2016 14:55:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605387;
	bh=jW5AtJ5J4LKVMUCKqXO90A844SJ5YXeDsow3PGCVTUU=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LzFAnCRXtBq6wPtFUqmc5HFW6cFaqeXoBcutHJPgByrbvF7KnYN1txWK4oimB0zJw
	 Q02tuUQ8z4uq3Wdu3SsJefNkI0xLHC0ZT5X2d5Y3OSM8EDOSO9W5a9BdqYKiPy22cD
	 nHdvoI+goxQj3OMkz5uT5qj6SS0UWsd2RWLw2k0o=
