### ISSUE TITLE
[ScrollView] scrollTo fires a momentumScrollEnd event

### ISSUE THREAD

**Issue by ncuillery** [facebook/react-native#7591]
When playing with the ScrollView component, I spotted an unwanted (I guess) momentumScrollEnd event when using the `scrollTo`method. This occurs every time with iOS.

I created a playground [here](https://rnplay.org/apps/rO8PWg) and a personal repo [here](https://github.com/ncuillery/rn-scrollview-fix) based on the official ScrollView example.

To reproduce, scroll the panel (momentum scroll or not) and click on the button "Scroll to start" which trigger a "scroll to top" action

Tested with RN 0.25.1, Mac, iOS only

**Comment by lacker** [comment]
Sorry if it's a dumb question, but why exactly is this an unwanted event? I can't seem to find a canonical list of what events are supposed to fire when during scrolling, which perhaps is its own problem.

**Comment by christopherdro** [comment]
@facebook-github-bot icebox
