### ISSUE TITLE
error page's background color is white.

### ISSUE THREAD

**Issue by Janrin** [facebook/react-native#7600]
when i integrating with Existing Apps(IOS), redbox's background color is white, so that i can't see the error detail and bottom button

**Comment by dsibiski** [comment]
Can you provide a minimal example repo for us to test it on? This will also ensure that it isn't something else in your codebase possibly causing it. Thanks! 😄

**Comment by Janrin** [comment]
I found the reason that my code causing it, Thanks!

**Comment by arabscimitar** [comment]
@Janrin I have the same issue what case this in your code

**Comment by Mark2xv** [comment]
What did you see, denvercoder9?
😭

@Janrin
Please tell us what you found out. I'm seeing the same issue with a brownfield app (AKA custom integration)
