### ISSUE TITLE
Geolocation watchPosition not behaving as expected

### ISSUE THREAD

**Issue by Jonrock23** [facebook/react-native#7604]
On Android the distanceFilter option seems to be ignored and I get responses every 20 seconds. I would like to only update my location when it changes by 5 meters. Does anyone know how to achieve this? My code is as below

```
this.watchID = navigator.geolocation.watchPosition((pos)=>{
   var crd = pos.coords;
   this.updateLocation(crd.latitude, crd.longitude);
},
{enableHighAccuracy: true, timeout: 1000, maximumAge: 0,distanceFilter:5});
```

I even tried setting the distanceFilter to something crazy like 200 but it still updates every 20s

**Comment by CharlieIGG** [comment]
Well this is old @Jonrock23 but I'd like to know if you ever found a way to fix this, since I'm running into the same problem.

**Comment by sibelius** [comment]
@Jonrock23 @CharlieIGG did u guys figure it out?

**Comment by sibelius** [comment]
I think they are following this API: https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions

it has no `distantFilter`

**Comment by CharlieIGG** [comment]
@sibelius I never did figure it out, had to deal with it. The project's been paused for over a month now though, and so I haven't revisited the problem.

**Comment by sibelius** [comment]
my idea is to use a setTimeout or a setInterval and use `navigator.geolocation.getCurrentPosition()` from time to time

**Comment by Jonrock23** [comment]
I solved it by writing a Native Module (Java) and then call it
inJavascript. For my case I only needed to make it work on Android but my
guess is you would probably need to do something similar for iOS. I hope
that helps.

*{*
    "*name*":Blessing Jonamu,
    "*career*": Mobile/Web Developer,
    "*cell*":+27710830336,
    "*web*":http://blessingjonamu.co.za,
    "*social*": <https://www.facebook.com/tjonamu>
<https://twitter.com/blessingjonamu>
<https://za.linkedin.com/in/blessing-jonamu-3848a751>
*}*

**Comment by sibelius** [comment]
@Jonrock23 could u share some code about this?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by simonbuchan** [comment]
A bit late, but it looks like the example code is passing the options as the error callback. Try adding `null,` before the options.
