### ISSUE TITLE
[Andriod][ListView] Layer exceeds max / Unable to create layer for ReactViewGroup when applying renderToHardwareTextureAndroid to (wrapper view of) ListView and rendering too many rows

### ISSUE THREAD

**Issue by JaxGit** [facebook/react-native#7623]
Just found this rare case and log here to help others.
Guessing rendering component with increasing size to hardware texture on GPU may be a bad practice we should prevent.

**Origin scenario:** 
there was a time we need renderToHardwareTextureAndroid to get the correct measurement of screen in order to implement some special scrolling behaviours. 
At first it was fine, but as data getting from the API and populating to ListView grows, it finally reached a point that the size(height) of the wrapper view exceeded the max dimensions supported by the GPU, which broke the app without any js errors.
Luckily we didn't need any special behaviours later and renderToHardwareTextureAndroid prop could be removed. 

**Code snippet:**
```
content = ( <ScrollView style = {{flex: 1}}
                            ref="scrollView"
                            onScroll={this.determineScrollDirection}
                            onMomentumScrollEnd={this.updateContentOffset}
                            onScrollEndDrag={this.handleScroll}
                            scrollEventThrottle={100}>
                            {carousel}
                            <View ref="timelineView"
                                renderToHardwareTextureAndroid={true}
                                style = {{flex: 1}}>
                                <SGListView
                                    dataSource = {this.ds.cloneWithRows(this.props.feeds)}
                                    renderRow = {this.renderRow}
                                    style = {styles.timelineListView}
                                    enableEmptySections = {true}/>
                            </View>
                        </ScrollView>);
```

**Log from Android Studio/IntelliJ:** 
05-18 20:23:21.945    2877-2892/com.appName W/OpenGLRenderer﹕ Layer exceeds max. dimensions supported by the GPU (1472x17088, max=16384x16384)
05-18 20:23:21.945    2877-2892/com.appName D/OpenGLRenderer﹕ Current memory usage / total memory usage (bytes):
    TextureCache          1855584 / 25165824
    LayerCache                  0 / 16777216 (numLayers = 0)
    Layer size 1472x2304; isTextureLayer()=0; texid=207 fbo=1; refs=1
    Layers total   13565952 (numLayers = 1)
    RenderBufferCache           0 /  2097152
    GradientCache            2048 /   524288
    PathCache             2493087 /  4194304
    TessellationCache           0 /  1048576
    TextDropShadowCache         0 /  2097152
    PatchCache                  0 /   131072
    FontRenderer 0 A8      524288 /   524288
    FontRenderer 0 RGBA         0 /        0
    FontRenderer 0 total   524288 /   524288
    Other:
    FboCache                    0 /        0
    Total memory usage:
    18440959 bytes, 17.59 MB
05-18 20:23:21.945    2877-2877/com.appName D/AndroidRuntime﹕ Shutting down VM
05-18 20:23:21.945    2877-2877/com.appName E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.appName, PID: 2877
    java.lang.IllegalStateException: Unable to create layer for ReactViewGroup
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:323)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-18 20:28:22.083    2877-2877/com.appName I/Process﹕ Sending signal. PID: 2877 SIG: 9

**Environment:** 
react-native@0.24.1   Android   Mac

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/andriodlistview-layer-exceeds-max-unable-to-create-layer-for-reactviewgroup-when-applying-rendertohardwaretextureandroid-to-wrapper-view-of-listview-and-rendering-too-many-rows

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (69/60 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:44760)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzset-004Ljb-PU
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:24 +0000
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzset-0002An-5f
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:23 -0700
Date: Thu, 27 Oct 2016 14:55:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605382;
	bh=0JYeCh3krzA4hWFIj4Sd7qjvwVZMUaT1k/qcidsdy/w=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZK4NCx2hMatL1H9BU1UVwd8TxBNlNxrOw0eyrenwJrXQABB7avkyeywxd5e6bos/8
	 sqzWZsnLPNcR4VpCDyTN59rp30FIjUpIjxMxQJXAWec3YG+Afk4eEbnY0vY3JgJHLY
	 mz32oFvElI0a0Rvnkbqdsd150DJNnw3B+urULi08=

**Comment by SudoPlz** [comment]
I'm experiencing that issue as well.. Any solutions? Why is this closed?
