### ISSUE TITLE
[0.26.0][NavigationExperimental] Warning after upgraded to 0.26.0

### ISSUE THREAD

**Issue by hitbear518** [facebook/react-native#7626]
After update to 0.26.0, I got an warning `Warning: Failed propType: SceneView: prop type 'sceneRendererProps' is invalid; it must be a function, usually from React.PropTypes. Check the render method of  'NavigationCard' `，I checked `NavigationCard`, found that in `SceneView` there is `    sceneRendererProps: NavigationPropTypes.SceneRenderer,` so `NavigationPropTypes.SceneRender` is an Object, except that, I don't know what the warning mean. Is it a bug or not?

**Comment by hitbear518** [comment]
#7518 
Is the warning related to this pr?

**Comment by ide** [comment]
Yes that PR fixes this issue.

**Comment by edmofro** [comment]
I'm getting "Warning: Failed propType: Required prop `sceneRendererProps.isRequired` was not specified in `SceneView`. Check the render method of `NavigationCard`." with 0.27.2

**Comment by satya164** [comment]
@edmofro It's fixed in 0.28.0-rc. You can safely ignore the warning in 0.27.2
