### ISSUE TITLE
[Android][0.25.1][TextInput] Typed text not displaying in select devices

### ISSUE THREAD

**Issue by sreejithr** [facebook/react-native#7631]
[OnePlus X](https://oneplus.net/x) and [Micromax Canvas Spark Q380](http://www.micromaxinfo.com/mobile-phones/smartphones/canvas-mobiles/canvas-spark-q380) are 2 problem devices.

When you type into a `<TextInput>`, the text doesn't get displayed on-screen. When you navigate out of the page, the typed characters get displayed all in one shot. 

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  TextInput,
  View,
  Text
} from 'react-native';

class TestPlace extends Component {
  constructor(props) {
    super(props);
    this.state = {text: ""};
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>{this.state.text}</Text>
        <TextInput style={{height: 40, width: 800, color: "red"}}
          keyboardType={'numeric'}
          onChangeText={text => {
            this.setState({text: text});
          }}
          value={this.state.text}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('TestPlace', () => TestPlace);
```

More details:
- React Native version: `0.25.1`
- Android version: `4.4.4` and `5.1` had this issue.
- React version: `0.14.8`
- I'm using a Mac.

**Comment by MikeOrtiz** [comment]
I have also run into this issue with two Galaxy S6 running 5.1.1. 

An HTC One M8 and Galaxy S5 running 4.4.4 did not have this issue. A Galaxy S7 running 6.0.1 was also fine.

**Comment by ericvicenti** [comment]
Is this still broken in recent versions of RN? We aren't seeing too many reports of this, so it may be fixed or maybe there aren't very many people with these devices.

**Comment by sreejithr** [comment]
@ericvicenti We don't have this issue anymore with our apps. But I'll test `v0.37` on a Micromax Canvas Q380 and if I manage to get my hands on it, on a One Plus X and post my findings here.

**Comment by TBouder** [comment]
Hi ! I'm working with React Native 0.40.0 and I have the exact same issue with an android device (Version 5). It happens only on a few pages (My login form has no issue, and my account creation form (the same component with differents props) is broken). I think the issue is still here :(

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android0251textinput-typed-text-not-displaying-in-select-devices

**Comment by MohamedAssaf** [comment]
I'm using react-native-cli version 2.0.1 and the textInput still doesn't show the text typed from the keyboard
