### ISSUE TITLE
couldn't get the native call queue:bridge configuration isn't available.that is why???

### ISSUE THREAD

**Issue by appbeijing** [facebook/react-native#7633]
couldn't get the native call queue:bridge configuration isn't available. this probably indicates there was an issue loading the js bundle,e.g. it wasn't packaged into the app or was malformed. check your logs('adb logcat') for more information

**Comment by pewh** [comment]
Hi @appbeijing , how can you resolve that issue? I get this error message when upgrade to RN 0.26 with React 15.0.2.  Thanks

**Comment by zhqchen** [comment]
I get the error too  RN 0.26 with React 15.0.2, Android 6.0

**Comment by jiangqqlmj** [comment]
I get the error too RN 0.26.3 with React 15.0.2, Android 4.4.

**Comment by grsabreu** [comment]
I got the same error after upgrading form 0.25 to 0.26

**Comment by tyxo842** [comment]
I got the same error,perhaps because I get a error : 'MSBUILD : error MSB4132: 无法识别工具版本“2.0”。可用的工具版本为 "4.0"。'  when I run 'npm install' . I solved the problem with deleting the node_modules and modify the package.json with latest react version and then npm install again.
