### ISSUE TITLE
Integration of facebook analytics

### ISSUE THREAD

**Issue by zsajjad** [facebook/react-native#7634]
Any plans of integrating facebook analytics as a component just like geolocation. It will be great feature.

**Comment by charpeni** [comment]
https://github.com/facebook/react-native-fbsdk#analytics-for-apps ?

**Comment by charpeni** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-8** [comment]
Hey @zsajjad! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
