### ISSUE TITLE
REFUSED_STREAM with Okhttp and Nginx

### ISSUE THREAD

**Issue by rahuljiresal** [facebook/react-native#7642]
Okhttp fails when there is `REFUSED_STREAM` in HTTP/2. This happens with newer versions of nginx that use HTTP/2. GET requests get processed correctly, however, for POST, it fails with nginx complaining that the client prematurely closed the stream.

`client sent stream with data before settings were acknowledged while processing HTTP/2 connection`

More info here - https://github.com/square/okhttp/issues/2543 and https://github.com/square/okhttp/issues/2506

Because of this, okhttp does not work with some of the newer nginx servers. 

The fix is to configure `OkHttpClient` with other protocols for it to use. Here's the fix -- https://github.com/wallabag/android-app/pull/256.

As per OkHttp's javadocs, 
> The client will prefer the most efficient transport available, falling back to more ubiquitous protocols.
>
> If multiple protocols are specified, <a href="http://tools.ietf.org/html/draft-ietf-tls-applayerprotoneg">ALPN</a> will be used to negotiate a transport.

However, if you enable all possible protocols (like I tried in the PR here https://github.com/facebook/react-native/pull/7641), you will still get `PROTOCOL_ERRORS` maybe half the time. So instead of the change, the solution might be to add this to your `MainActivity`.

```java
    @Override
    protected void onStart() {
        super.onStart();

        OkHttpClient client = OkHttpClientProvider.getOkHttpClient();
        List<Protocol> protocolList = new ArrayList<>();
        protocolList.add(Protocol.HTTP_1_1);
        client.setProtocols(protocolList);
    }
```

**Comment by AndrewJack** [comment]
>Disabling HTTP/2 in OkHttp will work. It's sad, but it'll work. Both OkHttp and Nginx are going to make code changes for this issue.

https://github.com/square/okhttp/issues/2543#issuecomment-219309038
