### ISSUE TITLE
[RCTNetworking][iOS] Bad response string caused by incrementalUpdates === true

### ISSUE THREAD

**Issue by ultragtx** [facebook/react-native#7646]
react-native 0.26.0

When receiving data from a network request with incrementalUpdates === true, The native RCTNetworking module decodes every part of the response data into string and send it to JS immediately. But in my case, there are Chinese characters in the response data and the incremental decoding may fail here:

```
RCTNetworking.m
- (void)sendData:(NSData *)data forTask:(RCTNetworkTask *)task {
...
  // Attempt to decode text
  NSString *responseText = [[NSString alloc] initWithData:data encoding:encoding];
  if (!responseText && data.length) {

    // We don't have an encoding, or the encoding is incorrect, so now we
    // try to guess (unfortunately, this feature is available in iOS 8+ only)
    if ([NSString respondsToSelector:@selector(stringEncodingForData:
                                               encodingOptions:
                                               convertedString:
                                               usedLossyConversion:)]) {
      [NSString stringEncodingForData:data
                      encodingOptions:nil
                      convertedString:&responseText
                  usedLossyConversion:NULL];
    }

    // If we still can't decode it, bail out
    if (!responseText) {
      RCTLogWarn(@"Received data was not a string, or was not a recognised encoding.");
      return;
    }
  }
...
}
```

Because only a part of the response data is being decoded, the first decoding attempt may fail, so it will try to guess the encoding, but the Chinese characters may be decoded into something like `иї™д»¶иЎЈжњЌе§`.

I didn't test on android so I'm not sure whether android has this issue.

**Comment by ultragtx** [comment]
To make things clearer, the encoding is always correct which is UTF-8 in my case, but the incremental decoding may fail.

**Comment by ultragtx** [comment]
Maybe we should encode each part of the response data into Base64 string, send to JS, and decode the whole Base64 string into UTF8 string (or other encodings).

Just like RCTWebSocketModule: https://github.com/facebook/react-native/commit/ed930b4710a494671b1a9147616799722d60938e

**Comment by ultragtx** [comment]
@nicklockwood Sorry to bother you, but I think this can be a critical issue.

**Comment by yutin1987** [comment]
+1 QQ

**Comment by alexHlebnikov** [comment]
Same issue here, the only workaround is extending a custom XMLHttpRequest.

**Comment by alexHlebnikov** [comment]
Also, setting ```incrementalUpdates = false;``` in ```RCTNetworking.android.js``` and ```RCTNetworking.android.js``` helps out.

**Comment by ultragtx** [comment]
This commit (https://github.com/facebook/react-native/commit/08c375f828fd7755b75660c701c70207f3629c6c) add Blob support to RCTNetworking, which use Base64 to transfer data from native to JS, maybe we can do something similar to solve the encoding issue.

**Comment by origsun** [comment]
This problem troubled us for months. We were unable to reproduce stably but it did happen from time to time.  @ultragtx Thanks for pinpointing the cause. 

setting `incrementalUpdates = false;` in `RCTNetworking.android.js` helps.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctnetworkingios-bad-response-string-caused-by-incrementalupdates-true

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
