### ISSUE TITLE
Hot Reload -- factory is not a function (in 'factory(global, _require)')

### ISSUE THREAD

**Issue by patrickml** [facebook/react-native#7648]
Whenever I have hot reload enabled and I update my code I get the following error 

`factory is not a function` here is a screenshot 

<img width="369" alt="screen shot 2016-05-19 at 10 40 43 pm" src="https://cloud.githubusercontent.com/assets/7581369/15415739/cbba9e54-1e12-11e6-9aea-2c565509afc1.png">

I have tried creating a new react native projects and have found no solution to this issue. At first i thought it had to do with the use of stateless components, but I do not believe this is the case as I continued to periodically (1/3 times) get the issue without them.

I am using React Native `^0.26.0` on a Mac running `OSX 10.11.3` i have not tested this issue on Andriod only on `iOS` 

If I had any additional information I would post it, however I do not, as this happens with a new project as well.

If anyone would like me to provide any information such as package.json etc. please let me know.

**Comment by grabbou** [comment]
If I am not wrong we've fixed that @martinbigio https://github.com/facebook/react-native/pull/7568

@mkonicek @bestander shall we cherry-pick that to 0.26? HMR seems super important. Note - with super dumb example (RNTestApp) it works well, so that's why it passed the manual e2e tests.

**Comment by patrickml** [comment]
@grabbou so is there nothing I can do other than to wait for version 0.27?

**Comment by grabbou** [comment]
You can npm install 0.26.1 tomorrow with the fix included :) Just need to get home, but it's a bit late today.

**Comment by patrickml** [comment]
<3 thanks
