### ISSUE TITLE
NDK build fail ?! MacOS + android-ndk-r10e

### ISSUE THREAD

**Issue by kkmoving** [facebook/react-native#7652]
I clone the code and try to run the example. But it always fail !!!

My environment:
MacOS
ndk: android-ndk-r10e

Fail trace:

make: Entering directory `/Users/cw/work/mine/android/kkprojects/react-native/ReactAndroid/src/main/jni/react/jni'
[armeabi-v7a] Compile++ thumb: reactnativejni <= JSCPerfLogging.cpp
[armeabi-v7a] Compile++ thumb: reactnativejni <= JSLogging.cpp
[armeabi-v7a] Compile++ thumb: reactnativejni <= OnLoad.cpp
[armeabi-v7a] Compile++ thumb: reactnativejni <= ProxyExecutor.cpp
[armeabi-v7a] SharedLibrary  : libglog_init.so
/Users/cw/work/develop/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.8/include/mutex
Error:(779) undefined reference to 'std::__get_once_mutex()'
Error:(783) undefined reference to 'std::__set_once_functor_lock_ptr(std::unique_lock<std::mutex>*)'
Error:(790) undefined reference to 'std::__set_once_functor_lock_ptr(std::unique_lock<std::mutex>*)'
/Users/cw/work/mine/android/kkprojects/react-native/ReactAndroid/src/main/jni/first-party/fbgloginit/glog_init.cpp
Error:(140) undefined reference to 'std::__once_functor'
Error:(140) undefined reference to '__once_proxy'
Error:error: ld returned 1 exit status
make: *** [/Users/cw/work/mine/android/kkprojects/react-native/ReactAndroid/build/tmp/buildReactNdkLib/local/armeabi-v7a/libglog_init.so] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory`/Users/cw/work/mine/android/kkprojects/react-native/ReactAndroid/src/main/jni/react/jni'
:ReactAndroid:buildReactNdkLib FAILED
Error:Execution failed for task ':ReactAndroid:buildReactNdkLib'.

> Process 'command '/Users/cw/work/develop/android-ndk-r10e/ndk-build'' finished with non-zero exit value 2

**Comment by charpeni** [comment]
What version or commit of React Native are you using?

**Comment by grabbou** [comment]
Works on master #doing#release

**Comment by DearDominic** [comment]
ndk: android-ndk-r10d  

always fail !!!

**Comment by hey99xx** [comment]
@DearDominic Then maybe you should alway use android-ndk-r10e, that will always succeed !!!

Read first https://facebook.github.io/react-native/docs/android-building-from-source.html#download-links-for-android-ndk

**Comment by DearDominic** [comment]
@hey99xx  Thank you

**Comment by DearDominic** [comment]
@hey99xx   I tried android-ndk-r10e, but doesn't work

**Comment by hey99xx** [comment]
I have been successful with android-ndk-r10e on both Mac and Linux (EC2) computers.

Your error says `undefined reference to 'std::__get_once_mutex()` and bunch of errors from std namespace, so but that std object comes from within a file inside Android NDK, so I'm not sure why it cannot find those functions.

Can you comment what version of React you're trying to build, and what's the build tools version of Android SDK that you have? Also are you targeting a specific Android architecture (armeabi, x86 etc.)?
I have never tried the example Movies app but I believe that always works out of the box.

What's the Mac version you're using btw? Do you have XCode installed? I don't want to lead you into the wrong direction but as far as I remember lots of command line compilers come together with XCode.

**Comment by DearDominic** [comment]
@hey99xx  Thank you very Much, I still think the reason for this error is because the File directory , I tried to move the ReactComm to ReactFile ,and it worked!

**Comment by ericvicenti** [comment]
The movies sample has been removed from the core RN repo, so I think we can close this

**Comment by hey99xx** [comment]
@ericvicenti Did you even read this issue in the first place? It **literally** had nothing to do with movies sample app.
