### ISSUE TITLE
`react-native run-android` crash on Windows 7

### ISSUE THREAD

**Issue by ghost** [facebook/react-native#7656]
When I run `react-native run-android` it always fails. The cause is, packager (`react-native start`) is now successfully started in the background, as in Unixes. The problem is, in Windows, those two kill each other with `EPERM` errors (over deletion of already deleted files, afaict). That is, either fix the packager / builder not to crash each other, or don't run the packager automatically (as an alternative, defer running it until there is app:installDebug phase, when it is safe).

Thanks.

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

Any Android project suffices.

- [ ] What's the **version** of React Native you're using?

0.26

- [ ] Does this occur on iOS, Android or both?

Android

- [ ] Are you using Mac, Linux or Windows?

Windows 7 Pro 64bit

**Comment by janicduplessis** [comment]
Another solution I can see is to make the packager ignore the native android build directories.

**Comment by herby** [comment]
Dependent modules in node_modules are also built, so there are a few build dirs to ignore. Bur yes, that coild be done (and maybe it would also speed it up a bit) 

Dňa 21. mája 2016 8:23:51 CEST používateľ Janic Duplessis <notifications@github.com> napísal:

**Comment by lacker** [comment]
I think we need to consider Windows 7 as unsupported - Microsoft doesn't even support it any more. I'm going to close this issue but @janicduplessis if you actually do intend to fix this then feel free to reopen it.
