### ISSUE TITLE
[NavigationExperimental] Android support?

### ISSUE THREAD

**Issue by actonw** [facebook/react-native#7661]
Is there currently Android support for NavigationExperimental? I'm trying to use it, but when I use the NavigationCard all I get is a blank screen; when I eschew NavigationCard, the scenes don't change and animations in NavigationHeader lag pretty badly.

@ericvicenti

**Comment by ericvicenti** [comment]
I just tested NavigationCard within the UIExplorer examples and it looks fine. Can you post a code snippet and specific react-native version number?

**Comment by actonw** [comment]
Code snippet:
```javascript
import React from 'react';
import {
  View,
  NavigationExperimental,
} from 'react-native';

const {
  AnimatedView,
  Card,
  Header,
} = NavigationExperimental;

import { chooseView } from '../menuItems';

export function Navigation({ navigation, onNavigate }) {
  return (
    <AnimatedView
      navigationState={navigation}
      onNavigate={onNavigate}
      renderOverlay={props => (
        <Header
          {...props}
          renderTitleComponent={props => {
            const title = props.scene.navigationState.title
            return <Header.Title>{title}</Header.Title>
          }}
        />
      )}
      renderScene={(props) => {
        return (<Card
          {...props}
          key={props.scene.navigationState.key}
          renderScene={({ scene: { navigationState } }) => {
              console.log(navigationState);
              const CurrentView = chooseView(navigationState.key);
              return <CurrentView />;
          }}
        />);
        const CurrentView = chooseView(props.scene.navigationState.key);
        return <CurrentView key={props.scene.navigationState.key} />;
      }}
    />
  );
}
```

I'm using react-native 0.26.0.

**Comment by satya164** [comment]
Are using an emulator or a real device?

**Comment by actonw** [comment]
@satya164 I'm using Google's stock emulator w/ Google APIs.

**Comment by satya164** [comment]
@actonw Try using Genymotion or a Real device.

**Comment by actonw** [comment]
@satya164 I am not able to use genymotion or a real device at this point. I'm not sure exactly what relevance this has, since the `NavigationCard` does not involve any unique native code.

**Comment by actonw** [comment]
@ericvicenti @satya164 Adding `style={{ flex: 1}}` to the `NavigationAnimatedView` component seems to have fixed the lack of display in Android, however the opacity/animation is not quite the same. 
<img width="419" alt="screen shot 2016-05-24 at 12 14 23 pm" src="https://cloud.githubusercontent.com/assets/19315311/15516748/20b4d94e-21a9-11e6-9ed7-28e1ebd4dd72.png">

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/navigationexperimental-android-support

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (65/60 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:50888)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsej-004Led-MG
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:14 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsei-00019H-7Y
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:13 -0700
Date: Thu, 27 Oct 2016 14:55:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605371;
	bh=7BF+D1sN5idyrTazvR6+e3Lrwb0laUFB4VOTJMJDKS4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=sZR74q+Fz+xFzs+iUtZezzPu/0Ero2K/yMNTJG/l+8iP9i9o53uCJbL7fesSEJTTo
	 wjOKjjvVu5A+DOAAcYdNYkRkk/Iu5vo4GwTVsWYxNu7uUKfkgZoGhmId6WM6hbNy4U
	 KZUC6082a44crk9uvbnR1EjaxjuWvb7gjnNYUgMs=
