### ISSUE TITLE
Incorrect Flexbox Positioning Causing Gaps

### ISSUE THREAD

**Issue by 509dave16** [facebook/react-native#7662]
### Summary
Basically the layout engine is incorrectly positioning columns and rows of elements in some very niche cases. The "margin" by which it is off is 100ths of a dp unit, which causes the tiniest of gaps to appear between columns and rows. I encountered this issue when using a simple formula to calculate a ratio that would adjust the fontSize, padding, and borderWidth of some Views(i.e. cells) in a Grid-like layout based on the screen size. I was testing this on 4 device emulators: a 4 WVGA(Nexus S), Nexus 6, Nexus 7(2012), and Nexus 9. And my physical Moto G 1st gen.  I chose the 4 aforementioned device emulators since there width in dp units is spread between(or after) the following breakpoints: 240, 400, 560, 720. I would attempt to pick a ratio, but it always seemed to work on all but one of the emulators(or the physical device). I tried this over and over until I found that 0.01 ratio per 3.2 dp units happens to work if I don't Math.floor the computed values for the fontSize, padding, and borderWidth. However if I tried more devices I'm sure this would break as well.

### Required Details
- Live example: https://rnplay.org/apps/E9S6xQ
```javascript
let ratio = (smallestDimension / 2.9) * 0.01;//change the divisor to 3.2 if you want to see the positioning fixed.
```
- Screenshot of incorrect positioning for both a column and a row:
![Alt Text](http://s20.postimg.org/epxgrp159/incorrect_flexbox_positioning.png "Image of positioning bug.")
- Versions of React Native that this bug has been tested to occur on: 0.20.0, 0.21.0, 0.24.1, 0.25.1, 26.0
- This bug occurs on both Android and IOS. I was only able to test IOS on rnplay.org and there are additional weird artifacts that show up that I can't even describe.
- I am developing on a Windows machine.

**Comment by lacker** [comment]
Hmm, I can't repro on that live example or on a modern RN. I know Emil has made a bunch of css layout bugfixes since this was reported, so it's quite possible it's fixed, but it's also possible that it's dependent on some part of the guts that just make it flaky. I totally believe there are still bugs in this, and I would like to track them down, but I dunno if this report has any path to finding them at this point. I am going to close this issue, but if you can still find these off-by-a-pixel bugs in the layout with current RN then I would love to see a new issue - especially if it repro's on rnplay.org .

**Comment by 509dave16** [comment]
@lacker Thanks for taking a look at this issue! I know you guys have a tall order combing over all the React Native issues. I have thought about helping categorize the issues, because some are not as critical as others. Anyways I'm working right now to post a new issue and an RN Playground Project. My previous project got wiped when they changed their infrastructure.

**Comment by lacker** [comment]
Expo's Snack might be a better way to go nowadays - that looks a lot hotter than the old RN playground.

**Comment by 509dave16** [comment]
@lacker Woah. That is really recent. I'll try to use that instead if that service is preferred. Thanks for the recommendation!

**Comment by 509dave16** [comment]
@lacker Here's my new issue with all the pertinent details https://github.com/facebook/react-native/issues/13305
