### ISSUE TITLE
require function without full commonjs leads to footguns

### ISSUE THREAD

**Issue by calvinmetcalf** [facebook/react-native#7663]
must like browserify and webpack react-native allows modularization via require, but unlike those other tools react-native does not provide the process global at all times (#7607), you can't require the built in node ones (defunctzombie/commonjs-assert#21).

Some fixes

- pull in those by default (via [node-libs-browser](https://www.npmjs.com/package/node-libs-browser))
- give a better error message when one of those can't be found

**Comment by lacker** [comment]
I think this is a dupe, I am closing this issue

**Comment by hawkrives** [comment]
@lacker Do you have a tracking bug for the dupe? I'd like to follow along.

**Comment by lacker** [comment]
Sorry for not just pasting the link in the first place! I was probably brain dead after sorting through a huge list of issues that day.
