### ISSUE TITLE
Babel error with custom .babelrc since 0.26

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#7666]
I integrate react-native in a existing application.
I created a subfolder `js` with the javascript and start it with this activity:

```java
mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getApplication())
            .setBundleAssetName("index.android.bundle")
            .setJSMainModuleName("js/index.android")
            .addPackage(new MainReactPackage())
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build();
```

In the `js` folder I have a `.babelrc` containing:
```javascript
{
    "presets": ["react-native"]
}
```

In my root folder (which also contains node_modules) I have another `.babelrc` which I need for other build-steps:

```javascript
{
    "presets": ["es2015"]
}
```

Since `0.26` react-native complains when I have this file with "es2015" in it. When I delete it, it works:

```
> SyntaxError: <project>/node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js: Unexpected token (56:13)
>   54 |    */
>   55 |   addListener(
> > 56 |     eventType: String, listener, context: ?Object): EmitterSubscription {
>      |              ^
>   57 |     return this._subscriber.addSubscription(
>   58 |       eventType,
>   59 |       new EmitterSubscription(this._subscriber, listener, context));
```

**Comment by satya164** [comment]
This is expected, since files under `node_modules` get transpiled with the config at the project root. I don't think this is a new behaviour with 0.26

**Comment by fab1an** [comment]
It might have to do with `babel`, but I don't think so. I tried several older babel version before 6.9 and they didn't work either. It seems to me that the react-native-preset changed with 0.26?

**Comment by satya164** [comment]
It's been always like that with Babel. No idea how it ever worked for you. May be earlier it worked because of some caching issue.

@facebook-github-bot expected

**Comment by aarmand** [comment]
Webpack starts looking for your babelrc from the point of entry. once it finds it will use that one. You might consider mulitple entry points. https://webpack.github.io/docs/configuration.html

**Comment by fab1an** [comment]
I don't have a webpack config in this project.

**Comment by satya164** [comment]
@fab1an Mostly because no one has set it up yet. It'd be awesome if you could send a PR for it.

**Comment by fab1an** [comment]
I can check it out, but I guess a simple `babel src -d lib` step won't do, at the size of this project. :D

**Comment by ide** [comment]
The packager caches files that haven't been modified, so precompilation doesn't help that much and adds more complexity to source maps and the build. For RN I've found it's much better not to publish compiled files to npm -- the subset of JS defined by babel-preset-react-native is the language of RN, not ES5.

**Comment by satya164** [comment]
@ide I'd say that not pre-compiling has actually resulted in tons of issues with Babel config and such,

- It's quite problematic to use with other code which is pre-compiled with Babel
- Sourcemaps are screwed up when you've dependency that has a `.babelrc` with different config, sometimes it even breaks the code
- It's kinda difficult to use different configs for the other code when the project has different types of code mixed, so you're pretty much locked to use RN's preset for everything
- Since the packager transpiles `node_modules`, we've to be careful about which transforms we enable not to affect third party code, for example, enabling strict mode breaks many third party modules

Though it's not really RN not being pre-compiled, but packager transpiling code it's not supposed, the simplest solution is to pre-compile RN code. I personally had lots of issues with it which wouldn't exist if RN was pre-compiled.

I think @cpojer also wanted to do this to improve Jest's performance. @davidaurelio also said that he wanted to do this.

**Comment by fab1an** [comment]
Well, the same language (es2015 + jsx + some extensions) is used by quite a few other projects as well.

The problem with not pre-compiling is that it's really hard to write any code that depend on react-native. 

I just published a styling module (https://github.com/fab1an/react-native-tachyons) and couldn't use react-native's `StyleSheet` because I would have to somehow transpile react-native's code in my plugin. This is a gigantic source for potential errors.

**Comment by fab1an** [comment]
Addendum: Issues like this might also go away with precompilation: https://github.com/facebook/react-native/issues/7679

I can try to help out here, but I need some support:

Everything seems to be imported from "react-native/Libaries/react-native". So possibilities:
* a) Move all Javascript out from there into a separate `src` folder with the same structure and compile it into the place it was before or
* b) Compile javascript into a different `dist` directory and change `package.json` to reference that.

I think a) would be easier.

* Does some of the javascript code in `Libraries/` rely on non-js files being in the same directory?

**Comment by fab1an** [comment]
Ok, what I did so far:

1. copied the whole `Libaries` folder and cleaned out any non-js files:
  
  ```
   cp -R Libraries/ src/
   find src -type f -not -name "*js" -print0 | xargs -0 rm
  ```

2. created a `.babelrc` in src and installed the presets and plugins:
  ```javascript
{
      "presets": ["es2015", "react"],
      "plugins": [
        "transform-object-rest-spread",
        "transform-class-properties",
        "syntax-trailing-function-commas",
        "babel-plugin-syntax-async-functions"
      ]
}
  ```

3. compiled everything from `src` back into `Libraries`

   `node_modules/.bin/babel src/ -d Libraries` 

4. replaced `require('React')` with `require('react')` to clear the warnings

   One warning still appearing is:

  ```
You or one of the Babel plugins you are using are using Flow declarations as bindings.
Support for this will be removed in version 6.8. To find out the caller, grep for this
message and change it to a `console.trace()`.
```

5. linked this using `npm link` into an existing project and tried running the packager:
(`./node_modules/react-native/packager/packager.sh start --reset-cache`)

 This gives me an error about files being duplicated: 
   ```
[12:47:16 PM] <END>   Building (deprecated) Asset Map (68ms)
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: NavigationTreeNode
  Paths: /Users/fabian/dev/forks/react-native/Libraries/CustomComponents/Navigator/Navigation/NavigationTreeNode.js 
collides with /Users/fabian/dev/forks/react-native/src/CustomComponents/Navigator/Navigation/NavigationTreeNode.js
```

For testing purposes I just moved the src folder (the original source) elsewhere and ran the packager again.

Now I don't get warnings by the packager but a `404` on the phone:

![screen shot 2016-05-25 at 12 51 13](https://cloud.githubusercontent.com/assets/55547/15537547/6630e8cc-2277-11e6-8373-a55085c0e7e8.png)

(my react-native entry is in `js/index.android.js`)

I don't know anything about haste or the packager, so any clues on how to proceed?

**Comment by fab1an** [comment]
Ok, the next thing I will try is trying to serve everything from webpack directly and circumvent the packager.

What is the packager used for besides compiling from babel?

**Comment by satya164** [comment]
@fab1an module bundling, hot reload, serving and bundling assets etc.

**Comment by fab1an** [comment]
Mhm, but all of that are things that webpack can do, can't it?

Anyway, I tried serving things from `webpack-dev-server` now, which needs https://github.com/yuanyan/haste-resolver-webpack-plugin to be able to resolve react-native's files.

I get a ton of errors, especially from files in `Libraries/CustomComponents/NavigationExperimental/` which do `require("react-native")` themselves.

I think i'll stop my efforts now, because I just don't know enough about haste.

I hope we'll see precompiled react-native sometime anyway ;)

**Comment by satya164** [comment]
@fab1an feel free to take stab at pre-compiling if you want

**Comment by fab1an** [comment]
See my comments above, I spent about 5 hours here, I precompiled the source, but (I think) haste is getting in the way.
My install fail with messages like "__DEV__" isn't defined etc. No idea what to do with them.

**Comment by satya164** [comment]
@fab1an Oh sorry, missed it.

> created a .babelrc in src and installed the presets and plugins:

You need to use `babel-preset-react-native` to compile the files

> This gives me an error about files being duplicated:

You need to remove the source files/duplicate compiled files. RN packager uses Haste and there'll be conflicts when 2 files have same `@providesModule` declaration

After compilation, you might wanna add `node_modules` to your `.babelignore` to ensure that babel transforms are not applied to RN files again,

**Comment by fab1an** [comment]
I did all that, but at the moment, I'm stuck with this error: https://github.com/facebook/react-native/issues/7814

(Without any precompilation or something)

**Comment by satya164** [comment]
Is it `__DEV__` or `DEV`? If it's `DEV`, it's certainly a typo, and you can try changing it to `__DEV__`.

**Comment by fab1an** [comment]
__DEV__

**Comment by satya164** [comment]
@fab1an Looks like a typo somewhere. try changing it to `__DEV__`.

**Comment by fab1an** [comment]
@satya164 Look at the line 15 in the bug that is linked:

../node_modules/react-native/Libraries/react-native/react-native.js:15

it says `__DEV__` there. It is not a typo, it's some weirdness by node-haste (I guess).

**Comment by satya164** [comment]
@fab1an Hmm... Got confused by `Markdown` changing the `__`.

It's weird. I've been using 0.26 and never had this issue. One quick workaround can be to set it `global.__DEV__ = true` until we figure out the issue.

**Comment by satya164** [comment]
Also, are you on master? Is this a clean install? If your example is reproducible, will be great if you can push it to GH and link to it in that issue.

**Comment by fab1an** [comment]
I'm on a custom project using react-native master, like stated earlier in this thread. When I set `__DEV__` like you said the next thing I get is
````
[node-haste] Encountered an error while persisting cache:
> Error: Cannot find module 'ReactNative'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/fabian/dev/react-native/Libraries/react-native/react-native.js:177:27)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
```

Unfortunately I don't have any more time to look into this, I already spent hours here.

I know how to work with "normal" es6, babel and node-requires, but since `react-native` seems to have it's own package manager and module resolving it's just a depressing hunt for invalid path for me, so good look to the next person :).

**Comment by satya164** [comment]
@fab1an It'll be great if you can push what you already have.

**Comment by fab1an** [comment]
@satya164 This is my branch. Contrary to what I said in this thread I know compiled from `Libraries` to `dist` and not the other way round now, to get a nicer diff.

https://github.com/fab1an/react-native/tree/precompile-babel

**Comment by satya164** [comment]
@fab1an Thanks. Will check it out when I've time.

**Comment by fab1an** [comment]
Great, I'm sure it's worth it.

Building, transpiling and packaging is always a pain, so better stick with how everybody else is using babel, webpack etc… IMHO.

**Comment by fab1an** [comment]
I opened a proper bug for that, closing this.
