### ISSUE TITLE
AlertIOS typo in doc

### ISSUE THREAD

**Issue by limulidae** [facebook/react-native#7667]
https://facebook.github.io/react-native/docs/alertios.html

The **AlertsIOS** utility provides two functions: alert and prompt. All functionality available through AlertIOS.alert is also available in the cross-platform Alert.alert, which we recommend you use if you don't need iOS-specific functionality.

**Comment by terrysahaidak** [comment]
@limulidae just submit the PR which fixes that instead of submitting an issue.
