### ISSUE TITLE
Map annotations' reference by view index is fragile

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#7672]
On iOS with v0.22 through v0.26, the relationship between RCTMapAnnotationView and its respective react view is maintained using the index of the react view in the list of react subviews on the MKMapView instance.  Unfortunately, this is not stable if views come and go.

Worse yet, this is super fragile if the manager gets the delegate call -mapView:viewForAnnotation: prior to the react subview existing on the MKMapView.

**Comment by jwyld** [comment]
My workaround for the crash currently is to detect the invalid index reference in -mapView:viewForAnnotation:.  It creates the view, but does not set the content view on the RCTMapAnnotationView.  In -[RCTMap insertReactSubview:atIndex:], I have it recognize the content view is not set correctly and sets the subview as the content view on the RCTMapAnnotationView.

**Comment by lacker** [comment]
I'm closing this issue in favor of recommending the use of react-native-maps, see https://github.com/facebook/react-native/issues/8016
