### ISSUE TITLE
Map annotations on iOS are not always centered

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#7673]
On iOS v0.22 - v0.26, the map annotations are not always centered properly.  Commit [97fe0ea] tried to get this properly but was not done correctly.  Annotation views use a center offset which is 0,0 by default.  This means the annotation subview itself must be placed at center.  -[RCTMapAnnotationView layoutSubviews] only attempts to set the bounds which will give it the correct size, but it doesn't preserve the centering.

At this time, I can not provide a small sample as this is part of our whole project right now.

**Comment by lacker** [comment]
I'm closing this issue in favor of recommending the use of react-native-maps, see https://github.com/facebook/react-native/issues/8016
