### ISSUE TITLE
Failed to build DependencyGraph: Watchman error

### ISSUE THREAD

**Issue by aliajoudanian** [facebook/react-native#7675]
I getting this error when I want to run my project on Android emulator.

```
[Hot Module Replacement] Server listening on /hot

React packager ready.

Failed to build DependencyGraph: Watchman error: query failed: synchronization failed: Permission denied. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
Error: Watchman error: query failed: synchronization failed: Permission denied. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
    at /Users/Ali/Desktop/app/Test/node_modules/react-native/node_modules/node-haste/lib/crawlers/watchman.js:63:11
    at process._tickCallback (node.js:368:9)
```

I tried "watchman watch ~path" , "sudo" & "chmod" but they didn't help me.

**Comment by zeroleo12345** [comment]
i have the same problem. and maybe this cause the emulator could not connect to development server.
still finding solution.

**Comment by zeroleo12345** [comment]
cd AwesomeProject,  and execute `chmod -R 777 *` it still failed.
after i give the permission to the top dir, it work!
`chmod 777 AwesomeProject`

**Comment by neverlous** [comment]
same issue

**Comment by ide** [comment]
Can you post your watchman version if you are commenting on this issue? The latest version is 4.7.0 so try upgrading if you have an old version.

**Comment by neverlous** [comment]
I don't know why, it is OK when I uninstall watchman. Can't understand....

**Comment by sajjidakr** [comment]
anyone figured out the solution yet ?

**Comment by RGTimothy** [comment]
If you are using ubuntu, try to run it with superuser mode. Run `sudo su` first, input your password, then try again to run your project.

**Comment by RGTimothy** [comment]
If you are using ubuntu, try to run it with superuser mode. Run `sudo su` first, input your password, then try again to run your project.
This is working for me.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
