### ISSUE TITLE
Geolocation API automatically reverts to 100m accuracy on iOS

### ISSUE THREAD

**Issue by rburgst** [facebook/react-native#7680]
The current implementation of the geolocation API always reverts back to an accuracy of 100m after receiving the first location update.

- [x] Code snippet

https://facebook.github.io/react-native/docs/geolocation.html
    
    componentDidMount() {
        this.startGpsWatch();
    }

    startGpsWatch() {
        let geoOptions :GeoOptions = {
            enableHighAccuracy: true,
            distanceFilter: 3,
            timeout: 20000,
            maximumAge: 4000,
            accuracy: 1,
        };
        this.watchID = navigator.geolocation.watchPosition(
            this.onLastPositionReceived.bind(this),
            this.onLastPositionError.bind(this),
            geoOptions
        );

    onLastPositionReceived(position) {
        console.info("accuracy", position.accuracy);
    }

- [x] What's the **version** of React Native you're using?

latest 0.26.1

- [x] Does this occur on iOS, Android or both?

only on iOS

- [x] Are you using Mac, Linux or Windows?

Mac

The issue seems to stem from this code https://github.com/facebook/react-native/blob/2310494f328de903a4bc00636b9a89ffd2b24f62/Libraries/Geolocation/RCTLocationObserver.m#L337

    - (void)locationManager:(CLLocationManager *)manager
       didUpdateLocations:(NSArray<CLLocation *> *)locations
    {
       ...
       
    // Reset location accuracy if desiredAccuracy is changed.
    // Otherwise update accuracy will force triggering didUpdateLocations, watchPosition would keeping receiving location updates, even there's no location changes.
    if (ABS(_locationManager.desiredAccuracy - RCT_DEFAULT_LOCATION_ACCURACY) > 0.000001) {
        _locationManager.desiredAccuracy = RCT_DEFAULT_LOCATION_ACCURACY;
    }

Where `RCT_DEFAULT_LOCATION_ACCURACY ` is 100m.

The rationale for this code is somewhat unclear to me. The comment does not seem to fit to the implementation.

**Comment by lacker** [comment]
The code you are linking to is inside `didFailWithError` so it looks like the accuracy is only resetting on an error. My suspicion is that in your project it is actually erroring a lot for some reason which is causing those resets. I'm going to close this issue since it's been a while but if this theory is incorrect feel free to reopen.

**Comment by rburgst** [comment]
In my tests this was happening quite frequently therefore ruining the functionality. IMHO the code should still revert to the previously set `desiredAccuary`.

**Comment by rburgst** [comment]
Also I believe your analysis is wrong. In addition the same code can be found in https://github.com/facebook/react-native/blob/master/Libraries/Geolocation/RCTLocationObserver.m#L269

```
- (void)locationManager:(CLLocationManager *)manager
     didUpdateLocations:(NSArray<CLLocation *> *)locations
```

**Comment by leokaessner** [comment]
@rburgst Did you find a solution? We still struggle with that problem. As the constant is defined as makro, we even can't really subclass or categorize the RCTLocationObserver.

**Comment by rburgst** [comment]
I did modify the react native code. As I have it checked in I always put it
back when upgrading.





On 01.06.2017 at 14:40, Leo Käßner <notifications@github.com> wrote:


@rburgst <https://github.com/rburgst> Did you find a solution? We still
struggle with that problem. As the constant is defined as makro, we even
can't really subclass or categorize the RCTLocationObserver.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react-native/issues/7680#issuecomment-305480955>,
or mute the thread
