### ISSUE TITLE
Strange Behaviour backgroundColor in ListView running in iphone6Plus

### ISSUE THREAD

**Issue by Sdoy** [facebook/react-native#7684]
http://stackoverflow.com/questions/37381894/react-native-strange-behaviour-backgroundcolor-in-listview-running-in-iphone6pl

**Comment by rogchap** [comment]
Please don't (re)post questions here as it clogs up the issues list.
Use the tag `react-native` on stackoverflow.

**Comment by jaygarcia** [comment]
@Sdoy please close this issue.

**Comment by ide** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-8** [comment]
@ide tells me to close this issue. If you think it should still be opened let us know why.
