### ISSUE TITLE
Connection to http://localhost:8081/debugger-proxy?role=client timed out. Are you running node proxy? If you are running on the device, check if you have the right IP address in `RCTWebSocketExecutor.m`.

### ISSUE THREAD

**Issue by phongyewtong** [facebook/react-native#7685]
I run 

> react-native init Test1

 and run 

> react-native run-ios simulator

. After 3 secs this show up
<img width="255" alt="screen shot 2016-05-22 at 1 29 18 pm" src="https://cloud.githubusercontent.com/assets/4919605/15459234/c8405d98-20d5-11e6-9504-c126972a3c3d.png">

Connection to http://localhost:8081/debugger-proxy?role=client timed out. Are you running node proxy? If you are running on the device, check if you have the right IP address in `RCTWebSocketExecutor.m`.

I am running on mac and simulator. I dono if this is a bug? I didnt even change the sample code.

**Comment by rogchap** [comment]
Are you running the packager?

```
npm start
```

**Comment by phongyewtong** [comment]
I ran. still happened.
this is my package.json
{
  "name": "Test1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.1"
  }
}

**Comment by rogchap** [comment]
And the packager shows no errors?

**Comment by phongyewtong** [comment]
what do you mean by "packager show no errors"? sorry i just use react-native for 3 weeks

**Comment by rogchap** [comment]
The packager is the what transform your JS code and runs the debugging proxy... should look something like this:

![image](https://cloud.githubusercontent.com/assets/270252/15460896/675ee034-20f9-11e6-8193-e9362ad418ec.png)

Can you please follow these exact steps to see if you still get the error:

```
react-native init Test2
cd Test2
react-native run-ios
```

**Comment by phongyewtong** [comment]
<img width="866" alt="screen shot 2016-05-23 at 1 25 36 pm" src="https://cloud.githubusercontent.com/assets/4919605/15461058/f20034a0-20e9-11e6-8ad7-3ec2c521cf29.png">

**Comment by rogchap** [comment]
Did you follow the steps above? Looks like you're still trying to run Test1
Do you have remote debugging enabled?

**Comment by phongyewtong** [comment]
Its works now using another name. hmm...what did it just happen?

**Comment by rogchap** [comment]
Something must have gone wrong during `init`

**Comment by jhalborg** [comment]
If anyone finds this later on, this helps: https://stackoverflow.com/a/43285071/1409779 (an answer to an SO post from the same author as this issue)

**Comment by SSTPIERRE2** [comment]
+1 This happens to me often while developing/debugging on device. Behavior seems to be inconsistent. The only correlation I can find is if you let the device screen turn off/go to sleep for some variable length of time, it doesn't have to be very long. Sometimes simply restarting the build through Xcode works, sometimes I have to close packager terminal and clean the project.

That being said, I love React/RN and think you're all awesome, keep on keepin' on!

**Comment by srshah19** [comment]
For any future readers, this usually happens when you are running "Debug JS remotely" on multiple devices. Try to turn that off on all simulators/actual devices and rerun the project. It should work.

**Comment by karna41317** [comment]
@srshah19 not really. new project--> running on real device(and no other), in debug mode and debug js remotely . i get this error  while loading jsbundle.

**Comment by drpiou** [comment]
@srshah19 Happens to me every 5-30min every day. I have to switch on and then off the airplane mode to be able to connect again with the debugger. This occures even without the debugger, and even if I have the debugger on only one device connected at all (debugger and packager).

**Comment by jforaker** [comment]
For anyone in the future, I encountered this error when running a release build in the ios emulator. 

***TO FIX:***
`command D` in the emulator and deselect "Debug JS Remotely"

![image](https://user-images.githubusercontent.com/2042031/36125784-748e06e8-1023-11e8-957e-b0ab403c05fa.png)

**Comment by cglacet** [comment]
@drpiou Wow, I don't want to know why it worked, but it did.
