### ISSUE TITLE
Image label load remote Failed 

### ISSUE THREAD

**Issue by studentdeng** [facebook/react-native#769]
After setting the Image Label source attribute, this error occured.

[RCTLog][tid:0x7d8bb140][RCTUIManager.m:710]>No manager class found for view with module name "RCTNetworkImageView".

I'm trying to make 'Integration with Existing App'. my podfile is:

pod 'React'
pod 'React/RCTText'

Definitely I'm missing something, is there anyone help?

**Comment by a2** [comment]
You need to add `pod 'React/RCTImage'` to your Podfile.

**Comment by studentdeng** [comment]
thanks
