### ISSUE TITLE
Problems with React dependency on 0.26.1

### ISSUE THREAD

**Issue by avishayil** [facebook/react-native#7697]
When performing `npm install`, for some reason I have to install react@15.0.2 again, otherwise packager throwing an error while running the app.

NPM Warning:
````
npm WARN react-native@0.26.1 requires a peer of react@15.0.2 but none was installed.
````

Error:
![Error](http://i.imgur.com/y5s0ngO.png)

**Comment by rushabh1191** [comment]
same error.!

**Comment by jcmartins** [comment]
npm WARN react-native@0.26.1 requires a peer of react@15.0.2 but none was installed.
sudo npm ls -g --depth=0
/usr/lib
├── flow-bin@0.25.0
├── npm@3.9.2
├── UNMET PEER DEPENDENCY react@15.1.0
├── react-native@0.26.1
├── react-native-cli@0.2.0

**Comment by ide** [comment]
This is your problem: `UNMET PEER DEPENDENCY react@15.1.0`. 15.1.0 does not match 15.0.2.

**Comment by digitalcatnip** [comment]
is there any way to fix this?  I've been fighting and trying to upgrade React Native to 0.26.1 all day.  Any time I run npm update I now get this error.  I've tried deleting node_modules with no luck.  Now I can't even run my app!

"npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.26.1 wants react@15.0.2"

**Comment by avishayil** [comment]
I managed to solve it adding exact version of react to my package.json:
"react": "15.0.2"

Try it.

**Comment by satya164** [comment]
`npm install -S react@~15.0.2`

**Comment by digitalcatnip** [comment]
@avishayil 's suggestion fixed it.  I removed the ^ in package.json and re-ran npm update and it's all better now - except my app won't run because of the whole React / React-Native break I think.

**Comment by aaronschachter** [comment]
@avishayil @digitalcatnip  -- Are you adding into the `dependencies` object?

I may be adding `react `into the wrong section of package.json. Setting both as dependencies still throws the warning:
> npm WARN react-native@0.26.1 requires a peer of react@15.0.2 but none was installed.


```` 
 "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.1"
  }
````

**Comment by ide** [comment]
Remove the "^" from the react version:
```json
  "dependencies": {
    "react": "15.0.2",
    "react-native": "^0.26.1"
  }
```

**Comment by celrak** [comment]
Just to be clear, react-native now requires react?

**Comment by walter211** [comment]
still met this problem after removing ^

**Comment by MerlinYu** [comment]
I check packge.json 
"dependencies": {
    "react": "^15.0.2",
.....
}

then I npm install -S react@~15.0.2 to solve this warn.

**Comment by ravirupareliya** [comment]
After upgrading from version 0.38.0 to 0.42.0 i am getting this error

    java.lang.RuntimeException: Unable to load script from assets 'index.android.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:198)
     at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:33)
     at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:216)
     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:994)
     at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
     at java.lang.Thread.run(Thread.java:761)
