### ISSUE TITLE
[Portability] About make react native code could run on web browser

### ISSUE THREAD

**Issue by yuanyan** [facebook/react-native#770]
We try to do this, and expect to know how react native team think about it? 
cc @vjeux

**Comment by tjwudi** [comment]
@yuanyan I don't think this is not necessary. Native and web are totally different experiences. You can port your app code into React.js app, but that would be a tremendous work.

**Comment by jaygarcia** [comment]
I have no idea why you would want to do this.

**Comment by vjeux** [comment]
This is on my mental todo list of things to do with the project. It would be awesome to have View, Text, Image and the gesture system working on the web. This way you can share components that are not platform specific between the three codebases.

**Comment by yuanyan** [comment]
@jaygarcia For write once, run everywhere

**Comment by yuanyan** [comment]
@tjwudi Yes,  it's not a easy work if we port native component to React.js web.

**Comment by sandorTuranszky** [comment]
What about mobile web browsers? Can I use iOS device to navigate to url and see the app with more or less native look and behaviours?

**Comment by ClemMakesApps** [comment]
@yuanyan I don't think react-native web browser compatibility is coming anytime soon. As mentioned by the Facebook Team, they are [not following the write once, run everywhere paradigm](http://facebook.github.io/react/blog/2015/03/26/introducing-react-native.html).

**Comment by yuanyan** [comment]
@ClemMakesApps We make it happened, write once, run everywhere:

![screenshot](http://img2.tbcdn.cn/L1/461/1/8cd483f3a1dc2455cd5f8539667a55c69f38114f)

**Comment by vjeux** [comment]
@yuanyan omg this is awesome! Do you think that you'll be able to submit pull requests to core? :)

**Comment by brentvatne** [comment]
Consolidating this issue into #182 :smile:
