### ISSUE TITLE
babel strict mode transform is not working with v0.26

### ISSUE THREAD

**Issue by formatlos** [facebook/react-native#7700]
since v0.26 babel strict mode transform is not working anymore. I get different errors mostly of internal methods which try to use setters on read-only objects.

**Comment by jmurzy** [comment]
@formatlos Cannot reproduce. What errors are you seeing? Did you try running the packager with ``--reset-cache``

**Comment by formatlos** [comment]
Actually someone of my team added 'babel-polyfill' at some point. Removing it resolved the issues.

**Comment by formatlos** [comment]
I tried everything from removing and re-installing node_modules, cleaning watcher, cleaning packager cache. The error occurs in polyfillLazyGlobal function in InitializeJavaScriptEngine.js line 82

![error](https://cloud.githubusercontent.com/assets/214001/15644000/a27984b0-2650-11e6-85e5-346dc84cca50.png)

**Comment by formatlos** [comment]
seems that it doesn't work with `WebSocket`

**Comment by greg5green** [comment]
Also having the same problem over here. Errors include "Properties can only be defined on Objects." (same as @formatlos posted) and "Unhandled JS Exception: Module RCTLog is not a registered callable module."

**Comment by andrewbrereton** [comment]
I am also having the same issues.

When I `Reload JS` I will randomly see either of these errors:

```
Module RCTEventEmitter is not a registered callable module.

__callFunction
    index.ios.bundle?platform=ios&dev=true&hot=true @ 11456:10
<unknown>
    index.ios.bundle?platform=ios&dev=true&hot=true @ 11368:22
guard
    index.ios.bundle?platform=ios&dev=true&hot=true @ 11319:3
callFunctionReturnFlushedQueue
    index.ios.bundle?platform=ios&dev=true&hot=true @ 11367:6
```

Or this one:

```
Properties can only be defined on Objects.

set
    index.ios.bundle?platform=ios&dev=true&hot=true @ 28986:22
get
    index.ios.bundle?platform=ios&dev=true&hot=true @ 28983:12
setupDevtools
    index.ios.bundle?platform=ios&dev=true&hot=true @ 32834:18
setUpDevTools
    index.ios.bundle?platform=ios&dev=true&hot=true @ 29096:14
<unknown>
    index.ios.bundle?platform=ios&dev=true&hot=true @ 29123:14
loadModuleImplementation
    index.ios.bundle?platform=ios&dev=true&hot=true @ 127:8
guardedLoadModule
    index.ios.bundle?platform=ios&dev=true&hot=true @ 63:37
_require
    index.ios.bundle?platform=ios&dev=true&hot=true @ 54:18
<unknown>
    index.ios.bundle?platform=ios&dev=true&hot=true @ 100300:9
```

I am using react-native v0.27.1

My .babelrc:

```
{
  "presets": [
    "react",
    "es2015",
    "stage-1",
    "react-native-stage-0/decorator-support"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "babel-plugin-transform-decorators-legacy"
  ]
}
```

**Comment by satya164** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
This happens because `polyfillLazyGlobal` uses a top level `this` and the `transform-es2015-modules-commonjs` replaces top level `this` with undefined to match the es module spec.

I'll submit a PR to use `global` instead of `this` and it will fix this issue. In the meantime you can use the `babel-preset-react-native` or make sure your `transform-es2015-modules-commonjs` transform has `allowTopLevelThis` set to true.

**Comment by dchambers** [comment]
These instructions didn't work for me (react-native 0.27.2 in case it matters), but I've found that the problem goes away if I merely dismiss the error by pressing `Esc`, and then enable debugging within Chrome (`Cmd` + `D` & 'Enable Remote JS Debugging').
