### ISSUE TITLE
Hot Module Reloading crashes packager when adding images.

### ISSUE THREAD

**Issue by dslounge** [facebook/react-native#7703]
Hi,

I've been trying to figure a problem with the packager server. Whenever I add a new image to my files the packager server crashes due to `Syntax Error: ... Unexpected character '�'`. Here's a screenshot: 

<img width="1028" src="https://cloud.githubusercontent.com/assets/492403/15477739/4f101d8c-20e4-11e6-8547-70c678d3f133.png">

Should HRM be trying to parse images? Is there a way that I can get to not do that?

**Comment by jpokrzyk** [comment]
It builds a map on server startup. You just have to restart the server. It's not an HMR issue. If you just do a regular reload I think you'll have the same problem unless that got changed recently.

**Comment by fab1an** [comment]
This happens because, for some reason, the package tries to parse image files (or even sent them through babel). I tried using a `ignore` or `only` directive in my `.babelrc` which make the error go away, but crash the transformer at a different point instead.

**Comment by viix** [comment]
same problem

**Comment by satya164** [comment]
Duplicate of #7279
