### ISSUE TITLE
[0.26.1][iOS] Native UI component hangs application with chrome debugger active

### ISSUE THREAD

**Issue by spreech** [facebook/react-native#7707]
I am having an issue when I add an iOS native UI component to a new React Native project the application hangs if you enable the chrome debugger whilst the UI component is included in the project.

I have created a very simple example application here:

[https://github.com/spreech/rnnativecompissue](https://github.com/spreech/rnnativecompissue)

If you run the above it will hang once you enable the debugger. If you comment out RCT_EXPORT_MODULE() at MapViewManager.m:20 and rebuild the app will work correctly even with the debugger attached.

I have been following: [https://facebook.github.io/react-native/docs/native-components-ios.html#content](https://facebook.github.io/react-native/docs/native-components-ios.html#content)

I am using: 

OSX
iOS
RN: 0.26.1

**Comment by mikesurowiec** [comment]
I'm experiencing a similar issue on RN 0.26.1. When I enable "debug JS remotely" the simulator will freeze completely

**Comment by Elyx0** [comment]
Confirmed too when using React via Cocoapods. RN 26.2

**Comment by huangbong** [comment]
I can confirm this bug exists as well. Frustrating to try and use the debugger to see console.log statements and the whole thing just crashes. RN 0.26.0. I don't think I ran into this issue on 0.25.

**Comment by mikesurowiec** [comment]
Just so you all know, I don't experience this issue on 0.27.0-rc

**Comment by nikolugano** [comment]
I can confirm this as well. It happens both in simulator and on device (when use development server) and since I moved to 0.26.2. Using react and fbsdk via Cocoapods

**Comment by alloy** [comment]
I also had this issue and can confirm that after upgrading to 0.27.0-rc1 the issue is gone.

**Comment by tarun29061990** [comment]
Still facing this issue while doing transition between screens. Debugging on MotoE and chrome debugger is active. My react-native version is 0.27.2
