### ISSUE TITLE
No way to disable scroll/bounce in WebViews

### ISSUE THREAD

**Issue by lwansbrough** [facebook/react-native#771]
Would be useful for folks incorporating WebViews to be able to disable scrolling and bounce features.

**Comment by magicismight** [comment]
+1
I hate the bounce in the browsers and WebViews!
It would be really wonderful I can disable the bounce.

**Comment by christopherdro** [comment]
Not sure if this was unavailable before but now you can set the the property `bounces` to false.
Here is an example.
https://rnplay.org/plays/E_Nbsw

**Comment by lwansbrough** [comment]
@christopherdro Implemented by yours truly in https://github.com/facebook/react-native/pull/767

:)

**Comment by christopherdro** [comment]
:+1:
