### ISSUE TITLE
Super expression must either be null or a function, not null

### ISSUE THREAD

**Issue by binoyskumar** [facebook/react-native#7711]
## Version
$ react-native -v

react-native-cli: 0.2.0
react-native: 0.26.1

## Steps to reproduce

Build the code below of index.ios.js in xcode

'use strict';
var React = require('react-native');
var styles = React.StyleSheet.create({
  text: {
    color: 'black',
    backgroundColor: 'white',
    fontSize: 30,
    margin: 80
  }
});
class PropertyFinderApp extends React.Component {
  render() {
    return React.createElement(React.Text, {style: styles.text}, "Hello World!");
  }
}
React.AppRegistry.registerComponent('PropertyFinder', function() { return PropertyFinderApp });

## Expected Behavior

Hello World! 

## Actual Behavior

Error : Super expression must either be null or a function, not null

<img width="367" alt="screen shot 2016-05-23 at 11 49 04 pm" src="https://cloud.githubusercontent.com/assets/6707899/15480081/342fd662-2141-11e6-9cfe-5d373d585aad.png">

**Comment by ide** [comment]
This part is the problem: `var React = require('react-native');`. Instead write:
```js
var React = require('react');
var ReactNative = require('react-native');
```

**Comment by skatpgusskat** [comment]
@ide what if the other react-native modules use still ``` var React = require('react-native'); ``` ?
