### ISSUE TITLE
Can't find variable: Reflect

### ISSUE THREAD

**Issue by Sean-Snow** [facebook/react-native#7712]
I want use Reflect.getPrototypeOf,
but i got a error:
Can't find variable: Reflect

version:  0.26.1
os: MAC 0.11.5

**Comment by damusnet** [comment]
Reflect is [not available in Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect#Browser_compatibility), therefore I assume it is not available in JavaScriptCore either.

**Comment by ide** [comment]
You'll have to polyfill Reflect yourself.
