### ISSUE TITLE
InteractionManager.runAfterInteractions doesn't finished properly

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#7714]
here's the demo
![111](https://cloud.githubusercontent.com/assets/2595058/15495968/b79c1c7a-21c5-11e6-9413-c7b761049263.gif)

I surpposed `InteractionManager.runAfterInteractions` should be fired after the Navigaor's transition, but i notice that there is 1 or 2 px left when it fires, and it's really a user experience related issue as i want to update the view after transition to avoid the lag during navigation, now i've found a workaround as the following, call `requestAnimationFrame` before `setState` and then it works fine.

```
InteractionManager.runAfterInteractions(() => {
  requestAnimationFrame(()=>{
    LayoutAnimation.easeInEaseOut();
    this.setState({
      questions: data.questions,
    });
  });
})
```

so i'm asking if it works as designed or a bug

**Comment by jeanregisser** [comment]
I noticed a similar issue. In my case I'm using the Animated api with specific interpolation steps.

**Comment by nickhudkins** [comment]
We're also seeing this which causes a little "jump" at the end. While a requestAnimationFrame hack can "fix" it, it introduces other issues, (delays rendering enough to cause flashes of content that would not otherwise exist) Anyone have insight into what could have caused this?

**Comment by lacker** [comment]
Can you provide some sample code that causes this bug to happen? That would make it easier to reproduce this. Also you're talking about code that uses `Navigator`? In general the Navigator animations aren't using native animations so you won't get optimal smoothness, the solution is probably to use some library that does support native animations like `react-navigation`.

**Comment by nickhudkins** [comment]
@lacker I suspect in the future I will only be using native animations, so this is no longer a problem for me. However, if I get a little bit of time I can push up a reduced test case to show what occurs.

**Comment by lacker** [comment]
Yeah using native animations is probably the way to go. I don't even know if this is going to be fixable - with non-native animations there are some cases where you get a few frame gap and there is not much to do about it.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/interactionmanagerrunafterinteractions-doesnt-finished-properly
