### ISSUE TITLE
[NavigationExperimental] Scene remonted at route change

### ISSUE THREAD

**Issue by mvaivre** [facebook/react-native#7717]
I'm currently using:
- `Android 6.0.1`
- `RN 0.26.1`
- `react-native-router-flux 3.26.1`

This issue has already been signaled in several places (https://github.com/aksonov/react-native-router-flux/issues/489, https://github.com/lelandrichardson/react-native-maps/issues/207).
It seems that scenes are **re**mounted on top of each other when navigating back to them. In my app, it's especially visible on a Scene where I have a fullscreen `MapView` (see screenshot bellow).

It's obviously very heavy, my component resubscribes to `eventListners` etc...

![screenshot_20160524-120736](https://cloud.githubusercontent.com/assets/6715943/15500737/6249d21e-21aa-11e6-9fc4-e90bd02ad0c7.png)

**Comment by mvaivre** [comment]
@ericvicenti: hi Eric! Sorry for bringing this up, but is it a known issue on your side? It really breaks my app by flooding the memory. Also, I'm not sure why the behavior is different with the MapView. It's like the animation stops too soon, leaving the component above the previous one. And if I try to pan, the gesture is handled by the "most behind" component only.

**Comment by jmurzy** [comment]
See the discussion [here](https://github.com/ericvicenti/navigation-rfc/issues/69). These issues were addressed in ericvicenti/navigation-rfc#61. You should upgrade to **v0.28.0-rc.0**.

**Comment by mvaivre** [comment]
@jmurzy Thanks a lot! Great to have some news about that.

**Comment by satya164** [comment]
@facebook-github-bot answered
