### ISSUE TITLE
Unable to resolve module ReactDefaultPerf from 

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#7719]
```
Unable to resolve module ReactDefaultPerf from /Users/stereodenis/work/evrone/e2_wtcc/node_modules/react-native/Libraries/react-native/react-native.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/ReactDefaultPerf and its parent directories

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```
react-native 0.26.1

**Comment by mmazzarolo** [comment]
I had the same problem yesterday.  
Make sure you're using `"react": "15.0.2"`.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-2** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by holyxiaoxin** [comment]
Make sure it's `15.0.2` and not `^15.0.2`

**Comment by shizy569** [comment]
thanks @mmazzarolo @holyxiaoxin

**Comment by anthonyivol** [comment]
If it can help, I got this error when I forgot to wrap custom components into a <View/> one :

throw the error
`...
import App from './app/app.js';

class client extends Component {
  render() {
    return (
        <App />
    );
  }
}
AppRegistry.registerComponent('client', () => client);`

works
`...
import App from './app/app.js';

class client extends Component {
  render() {
    return (
      <View>
        <App />
      </View>
    );
  }
}
AppRegistry.registerComponent('client', () => client);`

**Comment by smitthakkar1** [comment]
I was getting this error and it was a silly mistake. I'm sure most of you don't do this:

I was importing the file like this : import file from 'file';
But actual way was : import file from './file';

That works.
P.S. I also run the command "yarn" before doing above change.
