### ISSUE TITLE
OSX crashes and reboot after "react-native run-ios" since last El Capitain minor-update

### ISSUE THREAD

**Issue by itinance** [facebook/react-native#7726]
Sometimes, when i run my app in iOS-Simulator for the first time after booting OSX, the whole system freezes and crashes down then, with auto-reboot. This happens since my last OSX-Update some days ago to El Capitan 10.11.5 (15F34) from a previous El Capitan build.

**Update**: if you read this the first time, please consider my latest update: https://github.com/facebook/react-native/issues/7726#issuecomment-223111716

Mostly i can this reproduce then:

1. reboot the OS
2. open terminal
3. cd into my project directory
4. run command "react-native run-ios"

It will open iOS Simulator "iPhone 6 with iOS 9.3". The app will being loaded, then rendered and then the system is going to freeze completely, where no mouse- and keyboard-input will work any more. Some seconds later the whole system (OSX) is going to be reboot displaying a black crash-screen.
Doing the same again will end in a crash-reboot-start-app-loop.
So i can this reproduce many times with the same steps on every iteration.

The only way to get RN then working for iOS is, to open XCode, select another iOS-Version to 9.2 and start the project directly from XCode, while "react-native run-ios" would result in the crash again.
Is anyone experiencing the same?

I think it has something to do either with iOS 9.3 Simulator and/or in combination with Debugging in Chrome. Because when i start the project directly from XCode, the debugging mode will not being enabled automatically and everything works fine. When i start the project via command line from react-native with "react-native run-ios" instead, the debugging mode will be auto-enabled (maybe because of a previous stored session?), chrome will be launched and the debugger-tab is displayed. But then, some seconds later, always the crash happens in exact this scenario i reported above at the beginning of my issue.

**Versions:**
react-native-cli: 0.2.0
react-native: 0.25.1 and 0.26.2
node: 6.0.0
npm: 3.8.9
OSX: 10.11.5 (15F34)
Google Chrome: 50.0.2661.102 (64-bit)

I would like to figure out the root cause. Everyone is welcome to tell me, which steps could be help to dive into this issue further and how to get more helpful information.

**Comment by syzer** [comment]
👍

**Comment by willfong** [comment]
Does this happen on a new project, or just that one specific project?

**Comment by syzer** [comment]
for me updated old project

**Comment by itinance** [comment]
startet while working on an existing project, which i created 4 weeks ago

**Comment by siemya** [comment]
👍

**Comment by syzer** [comment]
fork workaround one might try to disable disable debugger(old one was debug with chrome... new one says 'debug js remotely')

**Comment by siemya** [comment]
I am also having a similar problem after upgrading my mac to 10.11.5 and my xcode to 7.3.1.

After starting the react-native server with "react-native start" command, i run my xcode project and it works fine. But as i toggle the "Debug Js Remotely" or "Enable Live Reload" buttons, my app freezes which is running on the simulator. İf i try to run it again, it only show a white blank screen, and i can only make it work again after i reset content and settings of the simulator. It is really annoying and mainly i can't debug in chrome from now on...

**Comment by itinance** [comment]
From now on i can't do anything with iOS-Simulators. I can only test my app on real iOS-device, because starting the app in iOS-Simulator leads to frozen OSX and rebooting my mashine. Any time, reproducable.

Android Simulator with Genymotion works pretty fine and also to with connected devices (both iOS and android)

Now this happens also if no debug mode is enabled. It crashes not at the first screen which opens on app launch, but as soon i will navigate to a screen that uses sqlite-database. 

I will try to isolate the code to get further into this issue. But it takes a lot of time. When OSX goes frozen, it take a half minute, and the rebooting process takes more 2 minutes....

**Comment by itinance** [comment]
I have an update: every view containing a ScrollView or ListView will reboot my mac.

**Comment by itinance** [comment]
A new update: its not the ScrollView or ListView alone, its the Image-Component, but not in isolated project.

I have the following code e.g.:

```
		return (
			<View style={{ flex: 1 }}>

				<Image source={require('./background.png')} style={styles.backgroundImage}>

					<ListView
						dataSource={this.state.dataSource}
						renderRow={this.renderRow.bind(this)}
						style={styles.listView}
					/>

				</Image>

		    </View>
		);

```

When i navigate to this View, OSX freezes complete, waits a minute and reboot then. When i remove the image tag, this crash will NOT happen. 
When i dont encapsulate the ListView within the Image and put the image above the listview instead (at the same level like the listview in parents view hierarchy), iOS will crash again.

Not every view with an image leads to a OSX-Crash in iOS-Simulator, but screens that have background images do so. I tried to isolate this to a fresh new project, but then it wasn't reproducable. i think, there must be more components in the game to lead to this osx-crash ....

**Comment by mroswald** [comment]
@itinance can you provide the whole component please?

**Comment by itinance** [comment]
@mroswald It is very huge containing many sub components from other different files. I don't know if this would make sense without publishing the whole app. What do you mean?

**Comment by itinance** [comment]
@mroswald i created a gist with it: https://gist.github.com/itinance/7d1c45623174c25dab19a0075a1231c7

**Comment by mroswald** [comment]
@itinance From a first view: There is a lot of potential for optimization ;-) You are doing a lot of stuff in the render method -> try to avoid this, especially defining constants. I'm note sure what SearchBar is doing, but you should bind the method on this context (via constructor or using class property). Maybe you're having a loop somewhere in there, but I can't see where on a first look. You shouldn't use the datasource in your state directly and based on your data ```rowHasChanged: (row1, row2) => row1 !== row2``` is wrong in the most cases when your object is not flat (obviously it's not).

BUT! Related to your problem ( :-) ): Having a ListView inside of an Image is maybe not the best idea, try to remove the wrapping image. I'm not a swift dev but the RCTImage has some event listeners regarding it's layout. So maybe this is causing your issue.

**Comment by itinance** [comment]
@mroswald first, thank you! Your answer raises questions: 

1. "rowHasChanged: (row1, row2) => row1 !== row2 is wrong in the most cases when" 
What would be a better solution here?

2. "Having a ListView inside of an Image is maybe not the best idea," 
What i wanted to achieve is a background image. Are there better approaches to do that?

**Comment by mroswald** [comment]
1) comparing an object in javascript doesn't work with `===`, just e.g. deepDiffer or similar functions for deep comparision (deepDiffer is private API from react-native and functions like this can be cpu-intensive, so be careful). This is a big topic, not so easy to explain. But in most cases, using deepDiffer is OK

2) as I said, I'm not sure if that's a good idea. Since I don't know your usecase I'd suggest do have an Image in the background and the ListView positioned above. But maybe your problem is solved when using deepDiffer :-) Working with `react-native` is always a bit of trying a bit, having a look at the performance indicators. Using `Image` as a wrapper for `ListView` seems a bit risky to me, maybe that's wrong. At this time it's always a good idea to have a look at the F8 app, they solved it as I suggested with overlaying the background image image your content instead of wrapping it (https://github.com/fbsamples/f8app/blob/b5df451259897d1838933f01ad4596784325c2ad/js/common/ParallaxBackground.js)

**Comment by itinance** [comment]
@mroswald regarding 1): i used the same comparison that facebook uses in its documentation: https://facebook.github.io/react-native/docs/listview.html
so i am very confused now. who is right?

**Comment by mroswald** [comment]
@itinance everybody is right :-) The example you mentioned is flat. comparing a string against a string with `===` operator is valid. But having complex data structures (e.g. objects in your case) needs you to do other methods for comparison

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/osx-crashes-and-reboot-after-react-native-run-ios-since-last-el-capitain-minor-update

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
