### ISSUE TITLE
[Packager] Requiring json file failed

### ISSUE THREAD

**Issue by tjwudi** [facebook/react-native#773]
I have one **config.json** in the **app** directory, and also a **List.js**.

In **List.js**, it tries to load **config.json** using `require` (which is common in node.js). But it failed.

![screen shot 2015-04-09 at 11 04 20 pm](https://cloud.githubusercontent.com/assets/5257816/7069699/ca2ea5b2-df0c-11e4-86f1-38fd9f596549.png)

**Comment by jaygarcia** [comment]
I've had similar issues. I think it might have to be w/ the fact that the CommonJS implementation is not a full implementation for this framework.

**Comment by ericvicenti** [comment]
This would be nice to support.

Internally, we would just rename to `.js` and add a `module.exports = ` to make it a normal JS module.

cc @amasad

**Comment by amasad** [comment]
This landed internally, should land here next sync.

**Comment by alexaivars** [comment]
would this be the same issue as trying todo require('./package') resulting in 'unknown module' ?

**Comment by brentvatne** [comment]
@alexaivars - if when you do that you are trying to require package.json then yup, same thing

**Comment by alexaivars** [comment]
awesome, hope the next sync lands soon.

**Comment by amasad** [comment]
I didn't know that `require('./package')` resolved to `package.json`. I think it just works for hard coded `.json` files. @alexaivars can you confirm that it doesn't work?

**Comment by alexaivars** [comment]
@amasad I can confirm that this is true and that it's a quite common practice to require package.json in this fashion. I however first noticed this since react-native chocked when I required cheerio.

**Comment by paulgessinger** [comment]
Any news on this front? 

I found that most scrapers seem to require some package that does this doe there is not much to be gained by switching to another library. #231 says the JSON requiring bug was fixed, yet I'm still getting errors with 0.4.4

**Comment by amasad** [comment]
@paulgessinger Yeah, `require('./package.json')` works, no?
The issue @alexaivars is explaining is omitting the "json".

**Comment by amasad** [comment]
Fixed this internally, should land next sync.

**Comment by cgarvis** [comment]
+1
