### ISSUE TITLE
after i update the react-native. I got this error, "undefined is not an object (evaluating 'React.PropTypes.bool')".

### ISSUE THREAD

**Issue by TuangWang** [facebook/react-native#7732]
after i update the react-native. I got this error, "undefined is not an object (evaluating 'React.PropTypes.bool')".

OS: MAC
react native: 0.26.1
iOS

**Comment by nihgwu** [comment]
please read the changelog before you upgrade your RN, React has been seperated from React-Native since RN0.25   
change
```
import React, {
  PropTypes,
  ...
} from 'react-native';
```
to
```
import React, {
  PropTypes
} from 'react';
import {
  ...
} from 'react-native';
```

**Comment by ide** [comment]
@nihgwu is right. Thanks for answering.

**Comment by devekoperiOS** [comment]
I have done changes, but still gives me the error.

**Comment by nihgwu** [comment]
@devekoperiOS perhaps the third-party components haven't upgrade to RN0.26

**Comment by VishalBumpy** [comment]
i am also getting the same issue... @nihgwu your solution did'nt helped... any idea ?

**Comment by nihgwu** [comment]
@VishalBumpy perhaps you just forget to install 'react'? it's not installed automatically when you init a new project

**Comment by VishalBumpy** [comment]
@nihgwu  I did, still i am getting the same error

**Comment by VishalBumpy** [comment]
@nihgwu i solved the issue... seems my npm ran into some error. :)

**Comment by asystat** [comment]
Sorry guys, I am struggling with react-native as a beginner and when you suggest to "update the file" i have no idea which file are you referring to... Could you please point me to the file that needs to be changed? @nihgwu @devekoperiOS
