### ISSUE TITLE
RCTJSErrorFromCodeMessageAndNSError missing important parts of NSError

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#7736]
I would test and submit a patch, but it seems node_modules/react-native/ changes (included via CocoaPods) are not actually compiling in my project (even with a clean!), so I am filing this bug instead since I don't have time/interest to debug it further.

I was using react-native-fbsdk, and received an error message from the FB API server for the quest "/me/picture?type=large&fields=url". Unfortunately, `RCTJSErrorFromCodeMessageAndNSError` ignored very important parts of the error message (ie, userInfo) in producing a JS-visible exception, wasting me time in trying to diagnose a root cause.

The NSError in the debugger was this:
```
error = (NSError *) domain: @"com.facebook.sdk.core" - code: 6
  _userInfo = (__NSDictionaryI *) 1 key/value pair
    [0] = @"com.facebook.sdk:FBSDKErrorDeveloperMessageKey" @"Response is a non-text MIME type; endpoints that return images and other binary data should be fetched using NSURLRequest and NSURLConnection"
      key = (__NSCFConstantString *) @"com.facebook.sdk:FBSDKErrorDeveloperMessageKey"
      value = (__NSCFConstantString *) @"Response is a non-text MIME type; endpoints that return images and other binary data should be fetched using NSURLRequest and NSURLConnection"
```

Unfortunately, `RCTJSErrorFromCodeMessageAndNSError` uses code and domain, but completely ignores `userInfo`, resulting in a very unhelpful error being raised back to my JS code that has no mention of the MIME type error:
```
error: {
  code: "ECOM.FACEBOOK.SDK.CORE6"
  domain: "com.facebook.sdk.core"
  message: "The operation couldn’t be completed. (com.facebook.sdk.core error 6.)"
  nativeStackIOS: Array[35]
  __proto__: Object
}
```

This is with React Native 0.25, on iOS (haven't tried Android), and I am using a Mac to debug. I cannot provide a minimal code snippet for `rnplay` since I do not know how to create this `NSError` without using `react-native-fbsdk`.

I assume adding this code to `RCTJSErrorFromCodeMessageAndNSError` should be sufficient for iOS (didn't poke at Android yet), but since I cannot test I don't feel comfortable submitting a formal pull request:
```
    if (error.userInfo) {
      errorInfo[@"userInfo"] = error.userInfo;
    }
```

Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctjserrorfromcodemessageandnserror-missing-important-parts-of-nserror

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
