### ISSUE TITLE
A bug about scrollView eating taps.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [facebook/react-native#7737]
I just noticed that if a listView(scrollView) got multiple textInput on it, you can't switch to next textInput without dismiss keyboard first, which is not consistent with native experience. And I know this is happening because `scrollResponderHandleStartShouldSetResponderCapture` 
> eat taps while the keyboard is up

I can simply fix this by exchange the implementation of  `scrollResponderHandleStartShouldSetResponderCapture` and `scrollResponderHandleStartShouldSetResponder`. And by add `TextInputState.blurTextInput(TextInputState.currentlyFocusedField())` to `touchableHandleResponderRelease` to dismiss keyboard if user touch any touchable that not textInput (actually it still will dismiss keyboard but will send a open keyboard request and iOS will ignore the dismiss event).  
But there seems to be more things to do. Like dismissing keyboard when scrolling depend on user's option. And I am new to this project and afraid of breaking something. So I need to know whether I am in the right track before I proceed.  
BTW it will be very nice if someone can answer this question: [How does React Native require(moduleName) work?](http://stackoverflow.com/questions/37370618/how-does-react-native-requiremodulename-work)

**Comment by samuelkraft** [comment]
Have you tried [keyboardShouldPersistTaps](https://facebook.github.io/react-native/docs/scrollview.html#keyboardshouldpersisttaps) and [keyboardDismissMode](https://facebook.github.io/react-native/docs/scrollview.html#keyboarddismissmode) on the ScrollView?

**Comment by Nick-The-Uncharted** [comment]
@samuelkraft Wow, you are right !   
keyboardShouldPersistTaps={true} and keyboardDismissMode={'on-drag'} solved this, but I am not sure whether this will work on Android since keyboardDismissMode is not available in Android.   
I got caught by the the thought `the tap was eaten by scrollview too early` and forget to check other property. But I think it is weird to having to do some configure to get normal expected behavior.

**Comment by joonhocho** [comment]
+1 having the same issue.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/a-bug-about-scrollview-eating-taps

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
