### ISSUE TITLE
Scroll doesn't appear when keyboard is open, neither it change the position of popup views (displaying on center)

### ISSUE THREAD

**Issue by naveensingh-daffodil** [facebook/react-native#7740]
&lt;View style={{flex:1, justifyContent:'center', alignItems:'center'}}&gt;
&lt;TextInput&gt;some text....&lt;/TextInput&gt;
&lt;/View&gt;
Expected Output: TextInput must be centered align (both vertically and horizontally )  
->This runs perfectly until we focus on textInput. 
->But in some cases, when we focus on TextInput and keyboard is appeared on screen, we expect TextInput to move upward to align itself (as its parent set it to centered align) but it didn't move and stick just above the keyboard (most weird thing is that it mostly occurred after noon). 

same case happens with ScrollView, 

&lt;ScrollView style={{flex:1, justifyContent:'center', alignItems:'center'}}>
&lt;TextInput&gt;some text....&lt;/TextInput&gt;
&lt;TextInput&gt;some text....&lt;/TextInput&gt;
&lt;TextInput&gt;some text....&lt;/TextInput&gt;
&lt;TextInput&gt;some text....&lt;/TextInput&gt;
&lt;/ScrollView&gt;

when i focus on Last TextInput , scrollbar don't appears

**Comment by charpeni** [comment]
What version of React Native are you using ? Android, iOS or both?

Can you provide a well formatted sample ? You can even host it on https://rnplay.org/.

**Comment by naveensingh-daffodil** [comment]
my version is 0.20.0

following sample will generate this case.

(<View style={{flex:1}}><ScrollView>

    <TextInput>1</TextInput>
    <TextInput>2</TextInput>
    <TextInput>3</TextInput>
    <TextInput>4</TextInput>
    <TextInput>5</TextInput>
    <TextInput>6</TextInput>
    <TextInput>7</TextInput>
    <TextInput>8</TextInput>
    <TextInput>9</TextInput>
    <TextInput>10</TextInput>
</ScrollView></View>

-> focus on 9 no. textinput than it will move upward but we will not
able to scroll to 1 or even 10 no textinput unless we hide the
keyboard



Best Regards,

*Naveen Singh Dahiya*
*Associate IT*
Daffodil Software Ltd.
Hisar (Haryana), India
www.daffodilsw.com
+919991000199

**Comment by naveensingh-daffodil** [comment]
right now i'm using android


Best Regards,

*Naveen Singh Dahiya*
*Associate IT*
Daffodil Software Ltd.
Hisar (Haryana), India
www.daffodilsw.com
+919991000199

**Comment by naveensingh-daffodil** [comment]
any update?????

**Comment by ThaJay** [comment]
I have found another issue and the file KeyboardAvoidingView.js
https://github.com/facebook/react-native/issues/8180#issuecomment-227707119

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/scroll-doesnt-appear-when-keyboard-is-open-neither-it-change-the-position-of-popup-views-displaying-on-center

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (68/60 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:50905)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzseo-004Lgv-9Z
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 21:56:19 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsem-0001AX-PT
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 14:56:17 -0700
Date: Thu, 27 Oct 2016 14:53:58 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477605376;
	bh=KyhQlEiGlv7kT6CNl871yf0iWmmMtn2IYTl4xZ1PLgE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZY5Bint0dJq0+w1Lyi1f2qB3H82Y0a7W0WKi3DYEflUImPxgAHObNmZ64yi+5rjJE
	 jSDhIUc8bkoMVNfH23YLMMY7FKVzWQ6/HqHdf+tUqrwugrygF1NVzGXkdRN7VmDWlM
	 VS/VZA7gSis++Rv3t7kyVOHRHYe1ab+fN30sahf4=
