### ISSUE TITLE
On ios devices do not show gif image after press Home button and reopen app

### ISSUE THREAD

**Issue by bormanEcwid** [facebook/react-native#7741]
Code snipped is available on https://rnplay.org/apps/dAC_hg

Steps for reproduction:
- open application (you can see animated gif-image)
- press home button (application will be collapsed)
- reopen application (animated gif-image will be hidden)

It appears only on ios devices

react-native v 0.24.1

**Comment by charpeni** [comment]
There are 2 pull requests that will fix this issue soon. #7629 #7612

Thank you for reporting this issue, I'll close it to keep the repo clean since it's should be already fix.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-0** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
