### ISSUE TITLE
[iOS] Navigator NavigationBar height isn't updated when status bar is hidden

### ISSUE THREAD

**Issue by samuelkraft** [facebook/react-native#7749]
The height of the status bar is set here: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesIOS.js#L36

It is not updated when the status bar is hidden with `<StatusBar hidden={true}/>` which creates a gap at the top. The same issue occurs when the device is in landscape when the status bar is hidden by default.

This is only an issue on iOS and can be shown in UIExplorer by hiding the status bar.

<img width="278" alt="screen shot 2016-05-25 at 12 35 43" src="https://cloud.githubusercontent.com/assets/2223418/15537127/f9d204c4-2274-11e6-9244-1bac2afdbd6f.png">

**Comment by samuelkraft** [comment]
@janicduplessis I see some discussion in #6195. Can we use currentHeight in iOS as well inside NavigatorNavigationBarStylesIOS.js ?

**Comment by janicduplessis** [comment]
currentHeight is only implemented partially on Android. We had some discussion about a status bar dimension API but it is not implemented.

**Comment by af7** [comment]
Hi! Is there a way to get the Height of the NavigatonBar (not StatusBar) for any device? Like what they do with "Dimensions"? I could not find this info anywhere. Thanks!

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-navigator-navigationbar-height-isnt-updated-when-status-bar-is-hidden

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by hnryjms** [comment]
Here's my workaround for anyone that ends up at this ticket, utilizing the convenient `prop` for the navigation styles:

```js
import NavigatorNavigationBarStylesIOS from "react-native/Libraries/CustomComponents/Navigator/NavigatorNavigationBarStylesIOS";
import _ from 'lodash';

const { Stages, ...rest } = NavigatorNavigationBarStylesIOS;
const NavigatorNavigationBarStylesNoStatusBarIOS = {
    ...rest,
    Stages: _.mapValues(Stages, (stage) =>
        _.mapValues(stage, (item) =>
            _.merge({}, item, { top: 0 })))
};

export default NavigatorNavigationBarStylesNoStatusBarIOS;
```

```js
<Navigator
    navigationBar={
        <Navigator.NavigationBar
            navigationStyles={NavigatorNavigationBarStylesNoStatusBarIOS}
            routeMapper={ /* ... */ }
        />
    }
    /* ... */
/>
```
