### ISSUE TITLE
Huge memory leak with Navigator and MapView: app crashes after minimal use

### ISSUE THREAD

**Issue by allthetime** [facebook/react-native#7763]
Version 0.26.2 (tested on 0.24.0 as well)

iOS, OSX (tested on Android, does not crash)

Hi, so I've been pulling my hair out for the last day trying to figure this out, but I'm not getting anywhere. At first I thought it was something I was doing, the structure of my project, the way I handle state, but now I have created the most simple version of my app possible and am still encountering a crippling memory issue. 

Basically, I have a listView, and when you press one of the rows, it takes you to a new route that contains a map view. There is a simple navigatorBar set up to handle going back and forth between these two views. 

https://rnplay.org/apps/HY_p-w

If you go back and forth between the routes, memory use climbs to about 250MB, a memory warning is then shown in the debugger, and then usage drops. If you go back and forth a couple more times, a few more memory warnings come out and then the app crashes.

In the rnplay the app does not 'crash', but you will notice that after pressing a row, and back a few times (about 10) it will reload the app even though there have been no changes. This is the point when the app just crashes on my device. 

![](http://imgur.com/TihMwx9.jpg)

So, am I missing something here? Is there something fundamentally wrong with the way I have set up the Navigator that it is just piling the heap up with copies of the MapView?

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by allthetime** [comment]
Still happening Version 0.29.1

I'm surprised that there isn't more information about this. I'm curious if other's are experiencing the same thing. It seems the memory management in the ios maps package needs some work.

Currently memory usage rises 100MB+ simply from  zooming in and out and panning around in a small area.

Making navigator transitions to and from a map seems to inflate the issue as well. Going back and forth between two views (push/pop) also crashes.

**Comment by tiero** [comment]
Still happens to me in RN 0.31 and maps 0.71, but I don't use Navigator to navigate in or out, but switching inside a render if a certain button is pressed 

I'm going to fork and look inside native code and AirMap

A mapView component is crucial in every enterprise mobile app

**Comment by satya164** [comment]
BTW you can also try https://github.com/lelandrichardson/react-native-maps for now.

**Comment by Andrewpk** [comment]
react-native-maps doesn't help. something is causing a retain cycle on the mapview's VKMapView. Mapview gets released but private vkmapview never gets released. Here's an example of an orphaned VKMapView:
<img width="940" alt="screen shot 2016-08-25 at 2 44 32 am" src="https://cloud.githubusercontent.com/assets/1033728/17959378/fd5a5330-6a6d-11e6-8afa-664ecf8248bd.png">

**Comment by alexHlebnikov** [comment]
Hey guys, I'm recently having a lot of memory leak errors with MapView on Android. Could they be connected with this issue? 
I'm using react-native-maps, RN 0.31.0 to 0.33.0.RC.0, devices with Android 4.4 - Android 7.0. 
Here is my stack trace of the crash:

__Exception java.lang.OutOfMemoryError:__
```
android.graphics.Bitmap.nativeCreateFromParcel (Bitmap.java)
android.graphics.Bitmap.access$000 (Bitmap.java:31)
android.graphics.Bitmap$1.createFromParcel (Bitmap.java:1308)
android.graphics.Bitmap$1.createFromParcel (Bitmap.java:1300)
abb.onTransact (:com.google.android.gms.DynamiteModulesB:101)
android.os.Binder.transact (Binder.java:347)
pny.a (:com.google.android.gms:242)
pgv.a (:com.google.android.gms:1254)
pgx.a (:com.google.android.gms:186)
pgp.a (:com.google.android.gms:6166)
pnx.onTransact (:com.google.android.gms:106)
android.os.Binder.transact (Binder.java:347)
com.google.android.gms.maps.model.internal.zza$zza$zza.zzc ()
com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap ()
com.airbnb.android.react.maps.AirMapMarker.getIcon (AirMapMarker.java:271)
com.airbnb.android.react.maps.AirMapMarker.createMarkerOptions (AirMapMarker.java:291)
com.airbnb.android.react.maps.AirMapMarker.getMarkerOptions (AirMapMarker.java:227)
com.airbnb.android.react.maps.AirMapMarker.addToMap (AirMapMarker.java:249)
com.airbnb.android.react.maps.AirMapView.addFeature (AirMapView.java:429)
com.airbnb.android.react.maps.AirMapManager.addView (AirMapManager.java:274)
com.airbnb.android.react.maps.AirMapManager.addView (AirMapManager.java:28)
com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren (NativeViewHierarchyManager.java:387)
com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute (UIViewOperationQueue.java:175)
com.facebook.react.uimanager.UIViewOperationQueue$2.run (UIViewOperationQueue.java:782)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:829)
com.facebook.react.uimanager.UIViewOperationQueue.access$1500 (UIViewOperationQueue.java:44)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:868)
com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame (GuardedChoreographerFrameCallback.java:32)
com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:131)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:789)
android.view.Choreographer.doCallbacks (Choreographer.java:591)
android.view.Choreographer.doFrame (Choreographer.java:560)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:777)
android.os.Handler.handleCallback (Handler.java:730)
android.os.Handler.dispatchMessage (Handler.java:92)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1046)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:862)
dalvik.system.NativeStart.main (NativeStart.java)
```

**Comment by Andrewpk** [comment]
I've submitted a bug to apple regarding this - it's just as big of a problem in an entirely native storyboard driven or objective-c example app as it is in react native.
Sample project I submitted had no code or strong references to the MKMapView other than the storyboard. Navigating to the mapview's VC created the MapView and its private VKMapView. Navigating from the mapview's VC caused the MKMapView to be dealloc'd and its private VKMapView was retained.
Performing this cycle repeatedly caused additional VKMapView objects to be alloc'd and retained long after the mapview was released.

**Comment by lacker** [comment]
We are deprecating mapview, so I am going to close this issue. If you still get this problem in things other than mapview then I encourage you to reopen a new issue with clear repro code. Thanks!

**Comment by otoinsa** [comment]
Navigator still leaks memory (does not clear view after new are pushed in, resulting in eventual crashes), why is this closed?

**Comment by pigflymoon** [comment]
+1
