### ISSUE TITLE
arrow functions not binding `this` in RN26 when using a .babelrc file.

### ISSUE THREAD

**Issue by siderakis** [facebook/react-native#7766]
http://stackoverflow.com/q/37449580/322765

In my project `this` is no longer bound when using arrow functions after upgrading to React Native 26.

If I don't use a `.babelrc` in the example below it works with arrow functions.  When a `.babelrc` is added arrow functions no longer work.

.babelrc
=======
```
{
  "passPerPreset": true,
  "presets": [
    {"plugins":["../schema/babelRelayPlugin"]},
    "react-native",
  ]
}
```

I also tried:

```
{
  "passPerPreset": true,
  "presets": [
    {"plugins":["../schema/babelRelayPlugin"]},
    "react-native-stage-0",
  ]
}
```
and

```
{
  "passPerPreset": true,
  "presets": [
    {"plugins":["../schema/babelRelayPlugin"]},
    "react-native",
    {"plugins":["transform-es2015-arrow-functions"]},
  ]
}
```

----------

This errors
--------------------

    class NoArrow extends Component {
      constructor(){
        super();
        this.state={x:0};
      }
    
      inc = ()=>{
        this.setState({x:this.state.x+1});
      }
      render() {
        return (
          <View style={styles.container}>
            <Text style={styles.welcome} onPress={this.inc}>
              Welcome to React Native! {this.state.x}
            </Text>
    
          </View>
        );
      }
    }

[![enter image description here][1]][1]
----------

This works
----------

    class NoArrow extends Component {
      constructor(){
        super();
        this.state={x:0};
        this.inc=this.inc.bind(this);
      }
    
      inc(){
        this.setState({x:this.state.x+1});
      }
      render() {
        return (
          <View style={styles.container}>
            <Text style={styles.welcome} onPress={this.inc}>
              Welcome to React Native! {this.state.x}
            </Text>
    
          </View>
        );
      }
    }

When adding/removing `.babelrc` also run:

 - watchman watch-del-all
 - npm start --reset-cache
 - I also edit the file (adding a comment) to make sure it recompiles.

----------

Side note: funny thing is this works even with the `.babelrc`

    class NoArrow extends Component {
      constructor(){
        super();
        this.state={x:0};
      }
    
      render() {
        return (
          <View style={styles.container}>
            <Text style={styles.welcome} onPress={()=> this.setState({x:this.state.x+1})}>
              Welcome to React Native! {this.state.x}
            </Text>
    
          </View>
        );
      }
    }

  [1]: http://i.stack.imgur.com/thsAe.png

**Comment by charpeni** [comment]
[Accepted answer on SO.](http://stackoverflow.com/a/37474298/4483873)

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-6** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
