### ISSUE TITLE
ListView can add scrollToSection(position) function?

### ISSUE THREAD

**Issue by xu6148152** [facebook/react-native#7767]
Like   
android ``public void setSelection(int position)``,
ios ``(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath ``

**Comment by charpeni** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-4** [comment]
Hey @xu6148152! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
