### ISSUE TITLE
Offical docs about create native ui component may be something wrong.

### ISSUE THREAD

**Issue by 646030315** [facebook/react-native#7773]
I want to create a native android component, so i exetend SimpleViewManager , but the src property setting method in offical docs show this way:
`@ReactProp(name = "src")
    public void setSrc(ReactImageView view, @Nullable String src) {
        view.setSource(src);
    }`
but the setSource method by  ReactImageView need another parameter ResourceDrawableIdHelper Like this below:
`@ReactProp(name = "src")
    public void setSrc(ReactImageView view, @Nullable String src) {
        view.setSource(src, new ResourceDrawableIdHelper());
    }`
Problem is the class ResourceDrawableIdHelper has package access, i can't construct it.
Is the framework update but the docs  or the docs with something wrong.
I am new to reactive , so i don't know how to do with the problem docs.

**Comment by JuanbingTeam** [comment]
same question~

So, how to set the source of Image in custom view？

**Comment by 646030315** [comment]
No idea...maybe you can see fresco's source code.

发自我的 iPhone

**Comment by zo-chu** [comment]
So, are there any news?  Any suggestions?

**Comment by kibiz0r** [comment]
`ResourceDrawableIdHelper` has a `getInstance()` method.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
