### ISSUE TITLE
[IOS/MAC] -Integrating react-native app with existing apps not creating .workspace

### ISSUE THREAD

**Issue by binoyskumar** [facebook/react-native#7775]
# Link which was followed
https://facebook.github.io/react-native/docs/embedded-app-ios.html

##Version

react-native-cli: 0.2.0
react-native: 0.26.2

# Does this occur on iOS, Android or both?
IOS only.
##Are you using Mac, Linux or Windows?
Mac

# Issue

The **pod install** step in the link is not creating the .workspace  (*Yourproject.xcworkspace*).
I have tried commands :
_**$pod setup
$pod install**_

# Expected output

Yourproject.xcworkspace getting created

# Actual result

Analyzing dependencies
[_!] The dependency `React/Core (from `/Users/i312654/ReactNativeSamples/SimpleApp/node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTImage (from `/Users/i312654/ReactNativeSamples/SimpleApp/node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTNetwork (from `/Users/i312654/ReactNativeSamples/SimpleApp/node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTText (from `/Users/i312654/ReactNativeSamples/SimpleApp/node_modules/react-native`)` is not used in any concrete target.
The dependency `React/RCTWebSocket (from `/Users/i312654/ReactNativeSamples/SimpleApp/node_modules/react-native`)` is not used in any concrete target.

<img width="1085" alt="screen shot 2016-05-26 at 2 41 49 pm" src="https://cloud.githubusercontent.com/assets/6707899/15569728/06b80766-2350-11e6-802c-e128f36352d3.png">
_

**Comment by binoyskumar** [comment]
Found the solution by myself. Thank god!

after recent changes in cocoapod the tutorial in the link provided dont work. Solution might me trivial for many but since i am not familiar with mac environment, i found it difficult to find this solution 

# [SOLUTION]

1. Open terminal in IOS folder of your app

2. run $*pod init*

3. Open the newly created podfile in ios folder. Copy contents of podfile from tutorial link and paste below *target 'SimpleApp' do* and save the podfile.

4. now run 
$*pod setup*    [optional step]
$*pod install*

5. Now you can see all the files are downloaded and .workspace is also created. Cheers!

# Podfile
<img width="652" alt="screen shot 2016-05-26 at 4 15 25 pm" src="https://cloud.githubusercontent.com/assets/6707899/15572263/1fbd9606-235d-11e6-8999-3db30bcde0d5.png">

**Comment by 2015lucky** [comment]
I also met with the same question ,please tell me how to solve it ,thank you very much.
