### ISSUE TITLE
Upgrading to 26 - docs wrong (maybe??)

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#7777]
I followed the docs to upgrade from 0.25.1 to 0.26.2 which says to run `npm install --save react-native@0.26`.  However, this doesn't seem to work, you the error `UNMET PEER DEPENDENCY react@0.14.8`.  It doesn't seem to change the react version in package.json from 0.14.8 to 15.0.2.

If I manually change package.json to:

    "dependencies": {
      "react": "^15.0.2",
      "react-native": "^0.26.2",
      ...

And run `npm install` I get another UNMET PEER DEPENDENCY error:  
 
![screen shot 2016-05-26 at 10 38 32](https://cloud.githubusercontent.com/assets/5489469/15570452/0ab398de-232e-11e6-9837-9fd3095b8b85.png)

What can cause this, maybe some other dependency in my package? Any suggestions on how to fix it?

I've tried `rm -rf node_modules && npm install` and get the same error as above plus a warning: `npm WARN react-native@0.26.2 requires a peer of react@15.0.2 but none was installed.`

**Comment by satya164** [comment]
change the version to `"react": "~15.0.2",` and run `npm install`.

**Comment by jeveloper** [comment]
It wont work with 15.1 yet, thats for 0.27 i believe
i suggest specifying exact version "15.0.2"

issue resolved

**Comment by devekoperiOS** [comment]
Can you please let me know where do I change  version?

**Comment by npomfret** [comment]
I solved it by removing all ~ and ^ symbols from my package.json so **all** dependencies have explicit versions. 

Your package.json should contain:

    "react": "15.0.2",
    "react-native": "0.26.2",

And then ran:

    npm cache clean && watchman watch-del-all && rm -rf node_modules && npm install && npm start -- --reset-cache.
