### ISSUE TITLE
[Android][ScrollView][0.27] pagingEnabled: true with horizontal: false not working

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#7780]
I have ScrollView with pagingEnabled: true, horizontal: true. And inside this ScrollView I have another ScrollViews with pagingEnabled: true, horizontal: false.
In iOS all works as expected, but in Android vertical paging not works.

https://rnplay.org/apps/vUevwg (no 0.27 version, try local)
0.27.0-rc
Android
Mac

**Comment by dmmiller** [comment]
Vertical paging is not supported in Android. We haven't needed it internally at FB yet.  You are welcome to put up a pull request for it.  Should be more or less a copy of what I did in the horizontal one.  I'd be happy to review it.

**Comment by raymondchooi** [comment]
@dmmiller I implemented your changes for the vertical ScrollView and have created a pull request: https://github.com/facebook/react-native/pull/10999
