### ISSUE TITLE
Latest packager: "Requiring unknown module" if dynamic moduleId

### ISSUE THREAD

**Issue by pesterhazy** [facebook/react-native#7785]
After updating RN (from 0.19 to 0.26.2), boot-react-native projects cannot require modules anymore.

In boot-react-native, we dynamically load modules by name (i.e. there's a function goog.require that calls RN's require with a string parameter). These modules are present as javascript files in the `node_modules` folder. For example, I'd do `goog.require("cljs.core")` which would load `cljs.core.js` form node_modules ([code](https://github.com/mjmeintjes/boot-react-native/blob/master/resources/mattsum/boot_rn/js/goog_base.js#L39)).

This [broke](https://github.com/mjmeintjes/boot-react-native/issues/49) somewhere between 0.19 and 0.26.2. From looking at RN's code, I'd guess that this is because `moduleId` is now typically an integer (though perhaps there's an exception for dev mode?).

My assumption is that the packager somehow statically analyzes the dependency js and finds all the `require("modulename")` statements, replacing modulename with an integer id. Is this behavior documented somewhere?

What would the correct moduleId be with the new packager?

**Comment by pesterhazy** [comment]
https://github.com/facebook/react-native/commit/5071907b27f59a54b02f12a579b545205f073cd8 seems to imply that "verbose module names" (strings) were removed in favor of numeric canonical ids. As of 0.27.0rc1, verbose names seem to be back in dev mode.

**Comment by pesterhazy** [comment]
Verbose module names now work again in 0.30.0. I've created a new issue for the remaining problem at https://github.com/facebook/react-native/issues/7785

**Comment by oximer** [comment]
I also interested to figure out how to figure the ID of a module. I'm guessing that the packager is building a map that bind name with id. Where I can find that map?
