### ISSUE TITLE
Webview component: jsEvaluationValue is undefined in Android

### ISSUE THREAD

**Issue by areina** [facebook/react-native#7788]
Hi,

I'm using a Webview component and trying to define the height of it automatically. For that, I'm using `injectedJavaScript` and `onNavigationStateChange`, and it's doesn't work in Android. There is no value for `jsEvaluationValue` in the event of `onNavigationStateChange` callback.
This is an extract of the code that I'm using:

``` js
var SampleApp = React.createClass({
      getInitialState: function () {
        return {
            webViewHeight: 100 // default height, can be anything
        };
    },
  render: function() {
          var html = '<p><strong>WebView Content</strong></p><ul><li>Foo</li><li>Bar</li><li>Baz</li><\/ul>';
    return (
      <View style={{paddingTop: 20}}>
                <Text>This is above the WebView.</Text>
                <WebView
                    html={html}
                    injectedJavaScript="document.body.scrollHeight;"
                    javaScriptEnabled={true}
                    scrollEnabled={false}
                    onNavigationStateChange={this._updateWebViewHeight}
                    automaticallyAdjustContentInsets={true}
                    style={{height: this.state.webViewHeight}}/>
                <Text>This is below the WebView.</Text>
            </View>
    );
  },
    //called when HTML was loaded and injected JS executed
    _updateWebViewHeight: function (event) {
        //jsEvaluationValue contains result of injected JS
      console.log("jsEvaluationValue: ");
      console.log(event.jsEvaluationValue);
        this.setState({webViewHeight: parseInt(event.jsEvaluationValue)});
    }
});
```

And here you can check a live example: https://rnplay.org/apps/At-z4A

There you can see how it works properly on iOS but it doesn't work on Android. Locally I'm using Linux, React 15.0.2 and React-Native 0.26.0

Thanks!

**Comment by RocketBuildDev** [comment]
Any luck on finding an answer? I am running into the same issue.

**Comment by cvongrim** [comment]
Any luck on this? I am running into the same problem.

**Comment by xyos** [comment]
I used this Gist (I had to adapt it to ES6 Classes):

https://gist.github.com/epeli/10c77c1710dd137a1335

**Comment by waqas19921** [comment]
Having same issue on android using react-native 0.30.
That link also [](https://gist.github.com/epeli/10c77c1710dd137a1335) does not work for me
as i have an html without <html> and <body> tags

**Comment by xyos** [comment]
basically this is what I'm using now, you might want to change the css.

**Comment by GantMan** [comment]
Anyone have the courage to finally fix this?  Working with height with hacks is getting kind of embarrassing :(

I'm not sure I would succeed in this PR, but it should be a priority, I would think.

**Comment by Naoto-Ida** [comment]
@xyos You just saved me from losing my hair. Thank you.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/webview-component-jsevaluationvalue-is-undefined-in-android
