### ISSUE TITLE
CameraRollExample crashes and reboots iPhone 6

### ISSUE THREAD

**Issue by jsierles** [facebook/react-native#779]
Testing this component on an iPhone 6, also with a trimmed down implementation, causes a crash and occasional reboot.

Here's what I can see in the Xcode error window: "Warning: ScrollView doesn't take rejection well - scrolls anyway"

Any better way to debug?

**Comment by jaygarcia** [comment]
That's because ScrollView is a beast!

**Comment by jaygarcia** [comment]
OK, seriously, does it crash in the UI explorer example or is this just your implementation that's crashing?

**Comment by jsierles** [comment]
it crashes the UIExplorer on the device. On the simulator, I haven't tested with more than a handful of images. I'll do that now though.

**Comment by jsierles** [comment]
So far, testing in the simulator with 10 images generates the same warnings, but no memory error or crash. The scrolling is pretty jerky: https://www.youtube.com/watch?v=YSMo1-2b1Qw

**Comment by polyvision** [comment]
Having the same problem with UI explorer and in my own app. Tested in on an iPhone 5S with iOS 8.3

    2015-04-11 21:54:16.640 UIExplorer[1344:412065] >
    RCTJSLog> "Warning: ScrollView doesn't take rejection well - scrolls anyway"
    2015-04-11 21:54:22.541 UIExplorer[1344:412170] Connection to assetsd was interrupted or assetsd    died

**Comment by Iragne** [comment]
Well as far as i tests this issue it's an memory problem.
It's cause by the way to load the image.

https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L48

```Objective-c
UIImage *image =  [UIImage imageWithCGImage:[representation fullResolutionImage] scale:1.0f orientation:(UIImageOrientation)orientation];
```
I would like to propose an attribute to Image to suggest the loading of the asset Thumbail. but i'm not fan of that. I think the issue is more complex than that. I's an architecure one.

for thumb we need to use this method 

```Objective-c
UIImage *image = [UIImage imageWithCGImage:[asset thumbnail]];
```

**Comment by admmasters** [comment]
This is also occurring for me... intermittently while scrolling in the simulator in my own app.

**Comment by Iragne** [comment]
Hi all
i create the PR https://github.com/facebook/react-native/pull/1406
It's solve for me the issue if you have a better idea to solve it feel free

Thanks

**Comment by brentvatne** [comment]
Dup #902
