### ISSUE TITLE
Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by texas697** [facebook/react-native#7790]
after upgrading to react-native-0.26.2 I am getting this error

> Cannot read property 'object' of undefined

![react](https://cloud.githubusercontent.com/assets/6617881/15594314/1bee738e-237a-11e6-9629-35f84f421d0c.png)

The chrome console only shows default error messages. 

here is package.json.

```
  "dependencies": {
    "@remobile/react-native-splashscreen": "^1.0.3",
    "firebase": "^3.0.3",
    "jwt-decode": "^2.0.1",
    "moment": "^2.12.0",
    "node-uuid": "^1.4.7",
    "q": "^1.4.1",
    "react": "15.0.2",
    "react-native": "0.26.2",
    "react-native-action-button": "^1.1.4",
    "react-native-android-statusbar": "^0.1.2",
    "react-native-animatable": "^0.6.0",
    "react-native-background-geolocation-android": "git+ssh://git@github.com/transistorsoft/react-native-background-geolocation-android.git",
    "react-native-button": "^1.5.0",
    "react-native-device-info": "^0.9.3",
    "react-native-drawer": "^2.2.3",
    "react-native-file-uploader": "0.0.2",
    "react-native-gifted-spinner": "0.0.4",
    "react-native-gmaps": "git+ssh://git@github.com/transistorsoft/react-native-gmaps.git",
    "react-native-image-picker": "^0.18.17",
    "react-native-keep-screen-on": "^1.0.3",
    "react-native-maps": "^0.4.2",
    "react-native-modalbox": "^1.3.3",
    "react-native-orientation": "^1.16.0",
    "react-native-router-flux": "^3.26.5",
    "react-native-simple-store": "^1.0.1",
    "react-native-vector-icons": "^2.0.2",
    "react-timer-mixin": "^0.13.3",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "eslint": "2.10.2",
    "eslint-plugin-react": "5.1.1",
    "eslint-plugin-react-native": "1.1.0-beta"
  }

```

here is output from adb logcat

> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: FATAL EXCEPTION: main
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: Process: com.metrostudy.app.surveytracker, PID: 19492
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImplAO$WEx@27727a7 -- permission denied for this window type
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:608)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:330)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:570)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManagerImpl$3$1.run(ReactInstanceManagerImpl.java:414)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5551)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
> 05-26 15:01:32.621 19492 19492 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: Process: com.metrostudy.app.surveytracker, PID: 16192
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: Requiring unknown module "buffer", stack:
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:387
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: i@2:177
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: <unknown>@381:2868
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:511
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: i@2:177
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: <unknown>@380:333
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:511
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: i@2:177
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: <unknown>@379:198
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:511
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: i@2:177
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: <unknown>@11:103
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:511
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: t@2:240
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: i@2:177
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: <unknown>@583:9
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:90)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:343)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
> 05-26 16:28:53.873 16192 16224 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: Process: com.metrostudy.app.surveytracker, PID: 16810
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: Requiring unknown module "buffer", stack:
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:387
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: i@2:177
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: <unknown>@381:2868
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:511
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: i@2:177
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: <unknown>@380:333
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:511
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: i@2:177
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: <unknown>@379:198
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:511
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: i@2:177
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: <unknown>@11:103
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:511
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: t@2:240
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: i@2:177
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: <unknown>@583:9
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:90)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:343)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
> 05-26 16:29:46.031 16810 16829 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: Process: com.metrostudy.app.surveytracker, PID: 16895
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: Requiring unknown module "buffer", stack:
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:387
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: i@2:177
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: <unknown>@381:2868
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:511
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: i@2:177
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: <unknown>@380:333
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:511
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: i@2:177
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: <unknown>@379:198
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:511
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: i@2:177
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: <unknown>@11:103
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:511
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: t@2:240
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: i@2:177
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: <unknown>@583:9
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:90)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:78)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:343)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:432)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
> 05-26 16:30:03.452 16895 16914 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: FATAL EXCEPTION: mqt_js
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: Process: com.metrostudy.app.surveytracker, PID: 25077
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: java.lang.RuntimeException: com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:24)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.devsupport.DevSupportManagerImpl.handleException(DevSupportManagerImpl.java:169)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:485)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:33)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: Caused by: com.facebook.react.bridge.JavaJSExecutor$ProxyExecutorException: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:187)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	... 3 more
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: Caused by: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.IoBridge.sendto(IoBridge.java:511)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at okio.Okio$1.write(Okio.java:80)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at okio.RealBufferedSink.flush(RealBufferedSink.java:221)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.squareup.okhttp.internal.ws.WebSocketWriter.writeFrame(WebSocketWriter.java:233)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.squareup.okhttp.internal.ws.WebSocketWriter.sendMessage(WebSocketWriter.java:180)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.squareup.okhttp.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:110)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.JSDebuggerWebSocketClient.sendMessage(JSDebuggerWebSocketClient.java:168)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.JSDebuggerWebSocketClient.executeJSCall(JSDebuggerWebSocketClient.java:141)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at com.facebook.react.bridge.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:180)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	... 7 more
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file descriptor)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.Posix.sendtoBytes(Native Method)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.Posix.sendto(Posix.java:211)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	at libcore.io.IoBridge.sendto(IoBridge.java:509)
> 05-26 19:20:20.142 25077  7920 E AndroidRuntime: 	... 19 more

**Comment by lacker** [comment]
I don't think we have enough information here to figure it out. I am going to close this issue but if this is still a problem then I suggest clicking on the redbox to see what line the failure is happening in and going from there.
