### ISSUE TITLE
CSS Operating System Colors

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/react-native#7794]
This is more for academic purposes than anything, but I recently discovered that CSS has color keywords based on operating system definitions. 

http://codepen.io/kevinSuttle/full/pbzxZZ/

I tried this in Electron, and it works, but not in RN.
Notice `backgroundColor: Highlight;`

![electron-css-system-properties](https://cloud.githubusercontent.com/assets/95672/15598273/64f9c1e2-23a6-11e6-9065-af610793ab60.gif)

![react-native-css-system-colors-error](https://cloud.githubusercontent.com/assets/95672/15598272/64f8fc6c-23a6-11e6-992f-18db7ea05c8a.png)
===

Mac 10.11.5 / iOS 9.3 (SimulatorApp-645.9)
react-native-cli: 0.2.0
react-native: 0.26.2

https://facebook.github.io/react-native/docs/colors.html

**Comment by lacker** [comment]
The way CSS works in React Native is not exactly CSS, it is based on the css-layout library. We recently added a bunch more docs to explain how this works so hopefully those docs are clearer now. I'm going to close this issue but if you believe there is a bug or a misdocumentation somewhere feel free to reopen.
