### ISSUE TITLE
Can't find variable: __fbBatchedBridge in android release

### ISSUE THREAD

**Issue by zsajjad** [facebook/react-native#7801]
Our app is in release mode and published on play store we are receiving a lot of crash reports mentioning:

```
java.lang.RuntimeException: ReferenceError: Can't find variable: __fbBatchedBridge (<unknown file>:1)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:158)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
	at java.lang.Thread.run(Thread.java:818)
```
Can you please mention if we are missing something while making final build.

**Comment by Victor880829** [comment]
Run this code in your project route：

react-native bundle --platform android --entry-file index.android.js --bundle-output android/app/index.android.bundle --dev false

and then copy the file "index.android.bundle" in your project folder.

Your problem will be solved！

**Comment by sreejithr** [comment]
@Victor880829 No need to copy the file manually with this command:
```
react-native bundle \
   --assets-dest ./android/app/src/main/res/ \
   --entry-file ./index.android.js \
   --bundle-output ./android/app/src/main/assets/index.android.bundle \
   --platform android \
   --dev true
```

**Comment by xvalentino** [comment]
@sreejithr Do we need to run this command every time we build our release? Maybe this should be in the docs?

**Comment by Victor880829** [comment]
@xvalentino 
No, this command is to generate bundle file in the project, but if your js files have changed you should generate the bundle file again.

**Comment by christopherdro** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @christopherdro says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
