### ISSUE TITLE
Why does CocoaPods say React library is deprecated?

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#7812]
Going to https://cocoapods.org/pods/React, I see:
```This library is deprecated.```

Unfortunately, I see references to CocoaPods in many places, including the official React Native documentation:
https://facebook.github.io/react-native/docs/embedded-app-ios.html

Is it deprecated or not? I suspect one or the other is in need of updating. (And should I be worried about my personal use of React via CocoaPods using that setup described?)

**Comment by ide** [comment]
What's deprecated is using RN from the CocoaPods podspec repository.

Using the CocoaPods CLI tool to link RN from node_modules is still supported and there are no plans at this time to drop support for it.

**Comment by mikelambert** [comment]
Thanks for the quick answer. Maybe it's worth a message on the CocoaPods podsepec repository saying the above?
