### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by sarovin** [facebook/react-native#7814]
i have a react-native@0.26.2 project on OSX. 
I have deleted the node_modules folder and after i have given the following commands:

```
npm i
react-native upgrade
```

but I get this error:

```
> .../node_modules/react-native/Libraries/react-native/react-native.js:15
> if (__DEV__) {
>     ^
> 
> ReferenceError: __DEV__ is not defined
```

How do I fix? I can't run my project now...

**Comment by sarovin** [comment]
Removing .babelrc seems to fix the problem.

My .babelrc:

```
{
  "presets": ["react-native"]
}
```

**Comment by someok** [comment]
I use same config, but not meet the problem

Saro Vindigni <notifications@github.com>于2016年5月30日周一 01:40写道：

**Comment by sarovin** [comment]
You have react-native@0.26.2? 
Can you try to delete the directory node_modules? 
And after give:
`npm i && react-native upgrade`

**Comment by sarovin** [comment]
I had not entered 'babel-preset-react-native' in my package.json

**Comment by alex1007** [comment]
@sarovin @xuchuandong 666 has different meanings in different cultures. It represents a thumbs up in China. Haha.

**Comment by sarovin** [comment]
Thanks @alex1007...I'm better now 😌
