### ISSUE TITLE
Is it possible to have 2 RCTRootView rendered at the same time?

### ISSUE THREAD

**Issue by nishp1** [facebook/react-native#7828]
Version: 0.26.2
OS: MacOS
Target Platform: iOS

Is it possible to render 2 RCTRootView at once from Swift? Is that even supported? Used to work in 0.24.1 but not in 0.26.2. 

Second RCTRootView needs to be rendered async-ly via a bridged call from Swift after user clicks on a button in the first RCTRootView. When rendering the second RCTRootView, I see "Loading from localhost" forever and it never completes loading. My suspicion is that it may be due to having 2 bridges open.

**Comment by javache** [comment]
Yes, that is supported. We'd recommend using a single bridge and reusing that for both root views.

**Comment by nishp1** [comment]
Thanks @javache. Didn't you know you could create a bridge and share that across with root views. 👍

**Comment by nishp1** [comment]
With this approach, if I had a say a global redux store instantiated, would that instance be shared? Or would each RootView get its own copy?

**Comment by ide** [comment]
The Redux store would be shared. One bridge = one JS heap = one copy of Redux (unless you made two stores in JS, of course).

**Comment by nishp1** [comment]
> One bridge = one JS heap

Perfecto! Thank you so much, appreciate the help.

**Comment by NSKevin** [comment]
But there's another question. If I have two RCTRootView with the same module name, how do I deal with it? For example, I'm using the ReactNative now, but I receive a remote push. Then I click the push , the other RCTRootView will be created and pushed, but with the same module name.
