### ISSUE TITLE
Error animating text color

### ISSUE THREAD

**Issue by joshfarrant** [facebook/react-native#7837]
When trying to animate the color of a Text component in the following way, I get the following error:

```
render() {

    const anim = new Animated.Value(0);

    var color = anim.interpolate({
        inputRange: [0, 255],
        outputRange: ['rgba(0, 0, 0, 1)', 'rgba(255, 255, 255, 1)']
    });

    return (
        <Text style={{color: color}}>Hello, world</Text>
    );
}
```

> You attempted to set the key `_value` with the value `9.326837512967053` on an object that is meant to be immutable and has been frozen.

<img width="376" alt="screen shot 2016-05-30 at 20 27 04" src="https://cloud.githubusercontent.com/assets/6840861/15657026/14fed9be-26a5-11e6-9ce9-44cef2a3bbcb.png">

![image](https://cloud.githubusercontent.com/assets/6840861/15657083/91668934-26a5-11e6-8c24-de4864d35f70.png)

The problem is fairly evident in that 2nd image, which led me to think this may be a limitation of React Native.

I've tested this on iOS with react-native 0.26.2. It's worth noting that this works works flawlessly if I swap out the Text component with a View, and animate `backgroundColor` rather than `color`.

**Comment by ide** [comment]
You can't animate raw React components -- you need to use Animated.Text.

cc @vjeux any ideas for how to improve the error message when someone tries to use AnimatedValue with a non-animatable component? I don't have a good idea for this without making normal components aware of Animated...

**Comment by joshfarrant** [comment]
Ah apologies, I didn't realise this, thank you @ide. In hindsight I was testing with an Animated.View when it did work, not a regular View, a definite oversight on my part!

**Comment by vjeux** [comment]
@ide I came to the same conclusion you did. Since Animated was still an experiment at the time I didn't want to do it but I think it would be a good idea now.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/error-animating-text-color

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
