### ISSUE TITLE
Is it possible to change or add configureScene's PushFromRight to PushFromLeft in React Native?

### ISSUE THREAD

**Issue by Daariush** [facebook/react-native#7842]
Since we are making an app for _Persian/Farsi_ language, the writing is from Right to Left. The issue in page transitions or segues is that it only has the PushFromRight option and we want change this to Push From **LEFT**.

Im a beginner in React Native and also not a professional coder, can anyone help me on this?

**Comment by jeanregisser** [comment]
Looks like you already posted this on Stackoverflow: http://stackoverflow.com/questions/37538315/is-it-possible-to-change-or-add-configurescenes-pushfromright-to-pushfromleft-i

Which is the right place for these questions.

Can you please close this issue. Thanks.
