### ISSUE TITLE
Guild for reading the trace of Profiling Android UI Performance

### ISSUE THREAD

**Issue by alcat2008** [facebook/react-native#7846]
I've been following the guide, but when I open the trace link in Chrome, it failed with error in console logs.

```
Uncaught TypeError: Object.observe is not a function
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
Uncaught (in promise) TypeError: timelineViewEl.updateDocumentFavicon is not a function
```

How to deal with it?

**Comment by xvalentino** [comment]
I believe this is a problem with systrace itself. Object.observe was deprecated in all the newer browsers, so now we can't open the trace unless we are using an older browser. If you manage to get it open, lmk because I've also been trying to find a way to read the trace.html file. Hope this helps!

**Comment by IjzerenHein** [comment]
As a temporary workaround you can use the following approach:

- Save the .html dump file to disk
- Open tab in chrome `chrome://tracing`
- Load file in the tracing console

**Comment by xvalentino** [comment]
Oh awesome. Thank you so so much! @IjzerenHein

**Comment by alcat2008** [comment]
Nice, it worked for me. Thank you! @IjzerenHein
