### ISSUE TITLE
'padding' not work in android

### ISSUE THREAD

**Issue by 999946** [facebook/react-native#7848]
# Code

``` JS
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class Test extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          WELCOME
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    backgroundColor:'red',
    fontSize: 20,
    textAlign: 'center',
    padding: 10,
  }
});

AppRegistry.registerComponent('Test', () => Test);
```
-  Android
  ![qq20160531-0](https://cloud.githubusercontent.com/assets/3955230/15671267/a8aedc88-275c-11e6-80d5-40fc5b0ffe21.png)
-  iOS
  ![simulator screen shot 2016 5 31 6 18 41](https://cloud.githubusercontent.com/assets/3955230/15671256/96a4b634-275c-11e6-9fb7-513040b03105.png)
# Versions

"react": "^15.1.0",
"react-native": "^0.27.0-rc2"

**Comment by alimek** [comment]
why no apply padding to the `View` rather than to Text? or did you try `margin` in Text?

**Comment by xxn520** [comment]
I have the same problem。But change to ` margin ` is work well。

**Comment by tomazahlin** [comment]
I have the same problem, margin works.

**Comment by xiDaiDai** [comment]
+1

**Comment by bawn** [comment]
+1

**Comment by liuliangsir** [comment]
marginLeft: -40 not work

**Comment by apopek** [comment]
margin not work too for me

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/padding-not-work-in-android

**Comment by FakhruddinAbdi** [comment]
+1
