### ISSUE TITLE
breaking bug with Firebase

### ISSUE THREAD

**Issue by PierBover** [facebook/react-native#7864]
I'm not certain if this is a Firebase bug or a React Native one...

I'm building for Android. I haven't tried in iOS.

The error says:
> undefined is not an object (evaluating 'a.toLowerCase')

I have started a fresh project with latest versions:

```
  "dependencies": {
    "firebase": "^3.0.3",
    "react": "^15.0.2",
    "react-native": "^0.26.2"
  }
```

I have tried putting `node_modules/firebase/` in the `.babelignore` as [suggested here](https://github.com/facebook/react-native/issues/6566). I'm not having the same error... but I tried just in case.

I'm only initialising firebase in the standard manner, otherwise the project is fresh created with `react-native init MyProject`:

```
		firebase.initializeApp({
			apiKey: "XXXXX",
			authDomain: "XXXXX",
			databaseURL: "XXXXX",
			storageBucket: "XXXXX",
		})
```

Here is a screenshot of the device:

![screenshot_20160531-202012](https://cloud.githubusercontent.com/assets/226483/15695592/4faeff52-276e-11e6-914b-f9e5d28c10c2.png)

**Comment by PierBover** [comment]
If I remove the `firebase.initializeApp` bit the project runs fine.

**Comment by PierBover** [comment]
This is the `index.android.js`

I've only added the firebase bit and the import.

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import firebase from 'firebase';

class ASC extends Component {
	constructor(props){
		super(props)
		firebase.initializeApp({
			apiKey: "XXXXX",
			authDomain: "XXXXX",
			databaseURL: "XXXXX",
			storageBucket: "XXXXX",
		})
	}
  render() {
    return (
	...
    );
  }
}

const styles = StyleSheet.create({
...
});

AppRegistry.registerComponent('ASC', () => ASC);
```

**Comment by PierBover** [comment]
Same problem on iOS

![image](https://cloud.githubusercontent.com/assets/226483/15696388/87f5ec66-2775-11e6-8ae2-b7102f817e0f.png)

**Comment by ide** [comment]
Can you debug what's going on and identify the root cause?

**Comment by PierBover** [comment]
I'm new to RN...

So I debugged in Chrome and got this.

![image](https://cloud.githubusercontent.com/assets/226483/15696569/4aefe932-2777-11e6-8a74-60687f862992.png)

After searching for `This browser is not supported` I found this on [StackOverlfow](http://stackoverflow.com/questions/37500106/this-browser-is-not-supported-in-ios-simulator):

> The new Firebase Authentication currently doesn't work in React Native due to a dependency on the window object. We're looking if that's something we can improve, but no guarantees.

So it seems it's a known Firebase bug...

Closing this.

**Comment by PierBover** [comment]
So this problem makes Firebase unusable with React Native.

The "workaround" is losing FB authentication and importing this directly:

```
var app = require('firebase/app');
var database = require('firebase/database');
```

and then simply:

```
app.initializeApp(...)
```

Losing auth, analytics, etc, **basically makes Firebase unusable for React Native projects**.

I've complained in the [Firebase Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/firebase-talk) and I invite anyone wanting to use Firebase on RN to do the same.

**Comment by dcworldwide** [comment]
Ok I understand your workaround now. 

I do need the auth module however, only for the api and now the Oauth UI flows.  I tried to un-minify the fb js code and look for a solution but It didn't seem obvious to me at first glance. 

I'm pretty determined to find a solution (and at least keep pushing google to restore compatibility).

**Comment by PierBover** [comment]
Yes, without auth it makes Firebase unusable for anything serious.

You also lose (at least) analytics...

**Comment by PierBover** [comment]
@dcworldwide your options are as follow...

1) Fix the JS SDK (probably impossible)
2) Make a native to JS bridge like [I outlined here](https://medium.com/@Pier/firebase-is-broken-for-react-native-7f78b7a066da) using the native SDKs by Firebase
3) Find another backend provider like Meteor

I'd say 2 is the best one... [someone started a project](https://github.com/holmesal/react-native-firebase) but it's quite experimental and only for iOS. Also it seems abandoned.
