### ISSUE TITLE
What limitation on AsyncStorage?

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#7869]
I try to load the large volume of data, but AsyncStorage throws warning what database or disk is full.
Have Any ideas?

**Comment by ide** [comment]
6MB on Android, indefinite on iOS: https://stackoverflow.com/questions/32875726/how-large-is-asyncstorage-in-react-native/

**Comment by antoxi4** [comment]
What to do in this case with Android?

**Comment by ide** [comment]
You could write your own storage implementation. That's one of the features of React Native.

**Comment by arv** [comment]
What is the motivation for the size limitation on Android?
