### ISSUE TITLE
RefreshControl for WebView

### ISSUE THREAD

**Issue by ncnlinh** [facebook/react-native#7870]
Hi, I know it's been a while since we deprecate `PullToRefreshViewAndroid` and move to `refreshControl={}`, but `RefreshControl` does not support `WebView` at all. Therefore, I have no choice but to use PullToRefreshViewAndroid for my `WebView`.

I have been tapping on the yellow boxes and dismissing them since we deprecate `PullToRefreshViewAndroid` and now we decided to remove it for good but I hope somehow we can bring back `PullToRefreshViewAndroid`

Thank you for reading.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot feature

**Comment by ncnlinh** [comment]
I thought #7447 would remove PullToRefreshViewAndroid for good?

**Comment by ncnlinh** [comment]
Also, thank you for the `console.ignoredYellowBox` tip!

**Comment by ncnlinh** [comment]
Any updates on this?

**Comment by janicduplessis** [comment]
I don't really have the time to work on this at the moment if someone wants to send a PR it would be great. What I suggest is adding support for WebView by doing something as we do in ScrollVIew https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L531

Also have you tried just wrapping your WebView with RefreshControl like you do with PullToRefreshViewAndroid? I think it might actually work.

**Comment by enyce12** [comment]
> Also have you tried just wrapping your WebView with RefreshControl like you do with PullToRefreshViewAndroid? I think it might actually work.

This works on android but throws an error on iOS:

![simulator screen shot 19 10 2016 13 57 17](https://cloud.githubusercontent.com/assets/5004390/19517872/10063992-9604-11e6-89ae-4ebfb77b5c4e.png)

**Comment by vasklund** [comment]
I've managed to get this working on iOS and Android with something like:

```js
<ScrollView refreshControl={<RefreshControl .../>}>
  <WebView bounce={false} ... />
</ScrollView>
```

This approach, however, has the caveat that the scroll event sometimes is captured by the WebView, sometimes by the ScrollView.

**iOS:**
* If you swipe down (scroll up), the `ScrollView` sees the scroll event and the `RefreshControl` spinner shows.
* If you first swipe up (scroll down), then change direction and swipe down without lifting your finger, the `WebView` sees the scroll event, and the `RefreshControl` spinner never shows.

**Android:**
* If you swipe down (scroll up), the spinner shows no matter what. You can't scroll up in the `WebView` at all.

I think the most robust way forward here is to implement support for RefreshControl directly into `WebView`, as suggested above.

**Comment by enyce12** [comment]
I got it working both for android and iOS using RCTScrollView for the latter. Will make a pull request.

**Comment by lacker** [comment]
Thanks for bringing this up. Since this is a feature request rather than a bug report and it has had some discussion I am going to close the issue. I think at this point the best way to go for this sort of extension is to build a separate UI component that has this functionality you want. Good luck!

**Comment by Kerence** [comment]
I've found a solution to perfectly add pull refresh to webview for both android and ios.
the key is to use the js bridge to notify rn whether enable pull to refresh or not.
the following code was tested against react native 0.38.1.
class YourComponent extends React.Component{
  ......
 state={enablePTR:true}
  render(){
	return (<ScrollView refreshControl={<RefreshControl enabled={this.state.enablePTR} />} onLayout={(ev)=>this.setState({scrollViewHeight:ev.nativeEvent.layout.height})}>
       <WebView enableNavigate={false} source={{uri:this.state.uri}} 	   ref={(r)=>this.webview=r}style={{width:Dimensions.get('window').width,height:this.state.scrollViewHeight}} {...this.props}
            injectedJavaScript="window.onscroll=function(){window.postMessage(document.documentElement.scrollTop||document.body.scrollTop)}"
                        onMessage={this.onMessage.bind(this)}
                      />
                   </ScrollView>)
   }
   
onMessage(e){
	  //document.documentElement.scrollTop||document.body.scrollTop returns the distance between scroll bar and top position
      this.setState({enablePTR:e.nativeEvent.data==0})
    }
}

**Comment by natterstefan** [comment]
@Kerence 

```js
state = {
  enablePTR: true
}

render() {
  return (
    <ScrollView refreshControl={} onLayout={(ev) => this.setState({scrollViewHeight: ev.nativeEvent.layout.height})}>
    <WebView
        style={{width:Dimensions.get('window').width,height:this.state.scrollViewHeight}} 
        enableNavigate={false}
        source={{
           uri: this.state.uri
        }}
        ref={(r) => this.webview = r}
        {...this.props}
        injectedJavaScript="window.onscroll = function() { window.postMessage(document.documentElement.scrollTop||document.body.scrollTop)}" 
        onMessage={this.onMessage.bind(this)}/>
  )
}

onMessage(e) {
      //document.documentElement.scrollTop||document.body.scrollTop returns the distance between scroll bar and top position
      this.setState({
        enablePTR: e.nativeEvent.data == 0
      })
}
```

Maybe it's just me, but I do not see how this should enable the PTR feature:

```
   enablePTR: e.nativeEvent.data == 0
```

Wouldn't this just tell the `ScrollView` that it should refresh when the user scrolls to the top again, but not really "on Pull to Refresh"? Or am I missing something? Would be awesome if you could help me out here. Thank you :)

**Comment by M1st1ck** [comment]
@natterstefan 
```
<ScrollView
  refreshControl={
    <RefreshControl
      enabled={this.state.enablePTR}
     ...
    />
  }
>
```
