### ISSUE TITLE
Exception on reaload js in iOS Simulator

### ISSUE THREAD

**Issue by magicismight** [facebook/react-native#788]
When I reload js in iOS Simulator,the development server console will throw an exception as followed and crashed, I had to rerun app from Xcode everytime!

Opening /Users/osx/Desktop/zhuanla/index.ios.js with subl
 ERROR  spawn subl ENOENT
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn subl","path":"subl"}
Error: spawn subl ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

**Comment by jaygarcia** [comment]
I've never run into this. Does this occur with the out of the box examples from this repository?

**Comment by brentvatne** [comment]
@magicismight - do you use sublime text by any chance?

**Comment by frantic** [comment]
When you see RedBox you can tap on rows with stack frames and packager will open your editor of choice on exact file/line number. You probably configured `$REACT_EDITOR` to be `subl`, however `subl` command can't be found. Try [this](https://www.sublimetext.com/docs/3/osx_command_line.html)

**Comment by jaygarcia** [comment]
The react editor has always been subl since I first tried this project.  It must be default 

JG



:: sent from my mobile device ::

**Comment by magicismight** [comment]
@frantic Thanks.
That is the problem.I didn`t install subl.
I will close this issue
