### ISSUE TITLE
Install failed on react-native run-android

### ISSUE THREAD

**Issue by braxtonfair** [facebook/react-native#7885]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [No] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [No] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [No] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [`react-native run-android`] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [[CMD]](https://gyazo.com/2c9794d44b09438180737c99e7051e3c) Provide **screenshots** where appropriate
- [0.26.3] What's the **version** of React Native you're using?
- [Android] Does this occur on iOS, Android or both?
- [Windows] Are you using Mac, Linux or Windows?

**Comment by charpeni** [comment]
Gradle told you "_No connected devices_" that's why it doesn't work.

You need to connect one device or setup an emulated one. Since you're on Windows, be sure the device drivers are installed. You should be able to see your device from `adb devices`.

I'll refer you to the documentation : https://facebook.github.io/react-native/docs/running-on-device-android.html#content

**Comment by charpeni** [comment]
@facebook-github-bot answered

**Comment by braxtonfair** [comment]
I want to use an emulated device, wouldn't that be different?

**Comment by satya164** [comment]
@braxtonfair Check the emulator's documentation on how to setup ADB.
