### ISSUE TITLE
This shouldn't be possible.

### ISSUE THREAD

**Issue by pubacademy** [facebook/react-native#7886]
Not all that important, but it did say congratulations so I thought I would send it along. 

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

Happened after I connected my Nexus 5X and ran

`react-native run-android`

for the first time. Hitting reload JS, solves the issue. I received no further information running

`react-native run-android --info --stacktrace`

if there is another place for crash logs, I'll be happy to send it along.
![screenshot_20160601-204609](https://cloud.githubusercontent.com/assets/2949210/15730658/7b52bdd2-283c-11e6-931f-e38eb25b4693.png)

- [ ] What's the **version** of React Native you're using?
react-native-cli: 0.2.0
react-native: 0.25.1

- [ ] Does this occur on iOS, Android or both?
Just on a Nexus 5X running 6.0.1, and it hasn't happened in simulators, on an iPad or anywhere else.

- [ ] Are you using Mac, Linux or Windows?
Mid 2015 15 inch Mac using OSX v. 10.11.5 w/ setup via homebrew, react cli

If you need any more info, let me know and I'll send it along. I've reproduced it twice so far and only on launch does it seem to happen.

**Comment by ide** [comment]
I believe this has been fixed in an upcoming version of React Native. (It was possible :P)
