### ISSUE TITLE
ListView Bugs,borderWidth or borderRadius Bugs

### ISSUE THREAD

**Issue by Sdoy** [facebook/react-native#7888]
I have run the 'UIExplorer' demo ,and change some code in the 'ListViewGridLayoutExample.js' file.
The source code:
[https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ListViewGridLayoutExample.js#L128](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/ListViewGridLayoutExample.js#L128).
```  
row: {
    justifyContent: 'center',
    padding: 5,
    margin: 3,
    width: 100,
    height: 100,
    backgroundColor: '#F6F6F6',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#CCC'
  },
```
then I change it into this:
```
row: {
    justifyContent: 'center',
    padding: 5,
    margin: 3,
    width: 100,
    height: 100,
    backgroundColor: 'green',
    alignItems: 'center',
    borderWidth: 0.5,
    borderRadius:0,
    borderColor: '#CCC'
  },
```
The difference is **'borderWidth'** and **'borderRadius'** property.

While running in iPhone6s
![1618720b-aa38-4e36-812a-b2a0a4910133](https://cloud.githubusercontent.com/assets/10302939/15732249/3ebab6be-28ae-11e6-888e-a16feb47dd28.png)
It looks well!

But strange backgroundColor behaviour happened in iPhone6s Plus.
![e3355e96-775f-4977-926c-aeb7cd3bbaf9](https://cloud.githubusercontent.com/assets/10302939/15732268/62304488-28ae-11e6-94f6-8a0c78a4bbfd.png)
And I also found, If change the code into 
`
...
 borderWidth: 1,
 borderRadius:0,
 ...
`
or 
`
...
 borderWidth: 0.5,
 borderRadius:1,
 ...
`
the strange backgroundColor disappear.

**So ,this is ListView Bugs? or Borders Bug?**

**Comment by jaygarcia** [comment]
I don't think that this is an issue with listView, it's an issue with how you are using borders.  

The math for borders gets fuzzy in those edge cases you highlighted.  I've done the same by accident. Just use normal values, like borderRadius: 3 and it will work fine.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-bugsborderwidth-or-borderradius-bugs

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
