### ISSUE TITLE
[IOS] RCTCameraRoll There is no automatic introduced

### ISSUE THREAD

**Issue by Sean-Snow** [facebook/react-native#7889]
RCTCameraRoll There is no automatic introduced，
CameraRoll  can't use

version: 0.26.3

**Comment by charpeni** [comment]
I do not understand, can you elaborate a bit more?

**Comment by charpeni** [comment]
@facebook-github-bot label Needs more information

**Comment by Sean-Snow** [comment]
the lib RCTCameraRoll need Manually add to my project @charpeni
