### ISSUE TITLE
ActionSheetIOS crashes when using 'anchor' for iPad positioning

### ISSUE THREAD

**Issue by samuelkraft** [facebook/react-native#7890]
As documented [here](https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L36) ActionSheetIOS should accept 'anchor' with a ref in order to position it correctly on iPad. Adding anchor just crashes the app on both iPhone and iPad. 

Example with both showActionSheet and showShareActionSheet: https://rnplay.org/apps/1TLCVQ

<img width="518" alt="screen shot 2016-06-02 at 10 34 29" src="https://cloud.githubusercontent.com/assets/2223418/15738857/a208de68-28ad-11e6-82a2-305ace9532d8.png">

**Comment by javache** [comment]
Ah, it looks like this class is missing an @synthesize. Will send a PR.

**Comment by samuelkraft** [comment]
Thanks!
