### ISSUE TITLE
With async/await, setState may cause an error.

### ISSUE THREAD

**Issue by rocman** [facebook/react-native#7891]
``` JavaScript
async loadData() {
  await someThingAsync();
  // Before running to here, the Component may be unmounted, and so making setState uncallable.
  this.setState(xxx)
}
```

The typical way to deal with the setState uncallable problem would be to cancel the logic calling setState on componentWillUnmount. However, we are using async/await, and there's no way to do so.

Here to ask for the official advice. Maybe Component could do the cancellable for most cases?

**Comment by satya164** [comment]
@rocman How to cancel the request is completely up-to your code. This is not a RN bug, so I would recommend you to post on stackoverflow.
