### ISSUE TITLE
how to get the  component  in  OnPress event  by  e.target

### ISSUE THREAD

**Issue by wudongkuo** [facebook/react-native#7892]
i use TouchableOpacity  to make a buttons contianer,  

 ```
class  TestNick extends  Component{
	_onPress(e){
		//e.target  number???  eg :26
	}
	render(){
		return (
			<TouchableOpacity onPress={this._onPress}>
				<View  style={{marginTop:100,height:300,width:300,backgroundColor:'red'}}>
				</View>
				<View style={{height:100,width:100,backgroundColor:'blue'}}>
				</View>
			</TouchableOpacity>
		)
	}
}
```
but the e.target   is number!!!!!

how to get the component instance by the e.target?

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @wudongkuo and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-2** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by sasivarnan** [comment]
@wudongkuo I am also facing that same issue.
Have you found a solution for that?

**Comment by inetfuture** [comment]
wondering too, I want to intercept events of certain components at the most top level component, how do I check the event target's type?

**Comment by ncuillery** [comment]
The corresponding SO question was hard to find so I link it here : http://stackoverflow.com/questions/38651770/how-can-i-get-real-elment-by-node-id-react-native

**Comment by dragonwong** [comment]
看评论很欣慰，装逼者被踩，回答者被赞，大快人心！

**Comment by fxfactorial** [comment]
The linked SO doesn't work anymore: 

```
const ReactNativeComponentTree = require('ReactNativeComponentTree');

... in some handler
const elem = ReactNativeComponentTree.getInstanceFromNode(e.target);

```

**Comment by appsthatmatter** [comment]
in current RN version you need this statement:
`import ReactNativeComponentTree from 'react-native/Libraries/Renderer/src/renderers/native/ReactNativeComponentTree';`

**Comment by windhost** [comment]
In current version:
import ReactNativeComponentTree from 'react-native/Libraries/Renderer/shims/ReactNativeComponentTree';

**Comment by wudongkuo** [comment]
to real words, that make us heart down on RN.
and no expect on you official to fix the  sh*t feature .
---------------------one more thing------------------
i have stop works on react native, all focus on web, it is the further .

**Comment by Rolandisimo** [comment]
@windhost am I doing something wrong? Doesn't work for me. 
Example code:
```
   <TouchableOpacity
       style={styles.filterOption}
       onPress={this.onOptionPress}
   > ...
   //...
    private onOptionPress(event: GestureResponderEvent) {
        const element = ReactNativeComponentTree.getNodeFromInstance(event.target);
        console.log(element)
        // Get inner text and set the filter
    }
```
