### ISSUE TITLE
Modal broken in 0.26.2 (Android)?

### ISSUE THREAD

**Issue by robertftw** [facebook/react-native#7893]
I've been using the modal for a while and had no problems until I updated to 0.26.2. Now the modal looks like this in a clean project (looks the same in my current larger project as well):
![image](https://cloud.githubusercontent.com/assets/3406006/15739707/93fd45e4-28b1-11e6-9404-786344ca178c.png)

Code:
```
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Modal,
  Dimensions
} from 'react-native';
var {height, width} = Dimensions.get('window');
class rnTest extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Shake or press menu button for dev menu
        </Text>
        <Modal>
          <View style={{ flex: 1, backgroundColor: 'red' }}>
            <Text style={{ color: 'white' }}>{width} x {height}
            </Text>
          </View></Modal>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('rnTest', () => rnTest);
`
```

**Comment by nicowrp** [comment]
Dirty, but for me add the width property to first View Container did the work : 
`<Modal>` 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<View style={{ flex: 1, width: width, backgroundColor: 'red' }}>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`           <Text style={{ color: 'white' }}>{width} x {height}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            </Text>`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          </View>`
`</Modal>`

Furthermore, if I add the transparent property, modal width is broken.

**Comment by robertftw** [comment]
@nicowrp Doesn't work for me...

**Comment by satya164** [comment]
closing in favor of #7708
