### ISSUE TITLE
[Touchable] "Cannot find single active touch" invariant violation when tapping with multiple fingers

### ISSUE THREAD

**Issue by ide** [facebook/react-native#79]
Repro: Open the "View" example screen in the UIExplorer and tap repeatedly with multiple fingers. The red box pops up with an invariant violation eventually. The more fingers you tap with (try four), the easier it is to repro.

```
Invariant Violation: Cannot find single active touch
	recordTouchTrack
	extractEvents
	extractEvents
	handleTopLevel
	_receiveRootNodeIDEvent
	receiveTouches
	jsCall
	_callFunction
	applyWithGuard
	guardReturn
	callFunctionReturnFlushedQueue
	[native code]
	global code
```

**Comment by ckknight** [comment]
This is also reproducible with the following steps:

1. Place index finger
2. Place middle finger
3. Lift index finger
4. Place index finger
5. Lift middle finger
6. Place middle finger

**Comment by mrdanlee** [comment]
+1 - Occurs when you use two finger drag on a list or scroll view

**Comment by dvdhsu** [comment]
+1. Also happens when you zoom on a ScrollView, but then lift one finger off.

This issue has been around for a while. Is there anybody interested in taking this up? I don't have the time right now, unfortunately.

**Comment by Iragne** [comment]
+1
do you create a PR ??
@dvdhsu

**Comment by dvdhsu** [comment]
Looking at the source code, this check only occurs when you're in dev mode. Seeing that it was working in production, I just ignored the problem. LMK if you still want me to make it?

**Comment by jessepollak** [comment]
+1 for this occurring in dev mode

**Comment by liubko** [comment]
+1
react-native v0.5.0

**Comment by sahrens** [comment]
I remember seeing a task about this internally that got fixed, and I can't seem to repro now.  Please re-open if you can repro in v0.6.0-rc
