### ISSUE TITLE
[ListView] Images in ListView blocks rendering?

### ISSUE THREAD

**Issue by tjwudi** [facebook/react-native#790]
I have a **ListViewItem.js** which have an inner image

```
<TouchableHighlight underlayColor="#ccc" onPress={this._navigateToDetail}>
  <View style={styles.container}>
    <View style={styles.leftCol}>
      <Image style={styles.couponImage} source={{uri: 'http://placehold.it/80x80'}}/>
    </View>
    <View style={styles.rightCol}>
      <Text style={styles.couponTitle}>{this.props.coupon.title}</Text>
      {companyTitle}
    </View> 
  </View>
</TouchableHighlight>
```

The internet access was very slow, so the `<Image/>` seems to block the list rendering process. List cannot show up. 

I tried to `console.log` in **ListViewItem#render`, and it only output once. It was expected to output six times.

Also I tried to reset contents in simulator, but it doesn't work. Is there any solution for this? Do I have to manually `fetch` image?   @vjeux

**Comment by Iragne** [comment]
@tjwudi The react is based on asyc and threads
so image cannot block direcly the app.

can you provide more information about react version and your code thanks

**Comment by christopherdro** [comment]
@tjwudi any luck at resolving this issue?

**Comment by brentvatne** [comment]
Closing until we hear back from @tjwudi!
