### ISSUE TITLE
what cause the `NSRangeException` crash

### ISSUE THREAD

**Issue by LeezQ** [facebook/react-native#791]
I write these code: 
```
  renderHeader: function() {
    var replyCount = this.state.replyCount ? this.state.replyCount: 0;
    console.log(replyCount);
    return (
      <Text>{replyCount} comments</Text>
    );
  },
```
and here is the crash happen: 
![image](https://cloud.githubusercontent.com/assets/972813/7083776/64ccd81a-df98-11e4-992a-5027f9d4a255.png)

but If I write like this:
```
  renderHeader: function() {
    if (this.state.replyCount) {
      return (
        <Text>{this.state.replyCount} comments</Text>
      )
    } else {
      return null;
    }
  },
```
and I have a initial state in my `getInitialState`: 
```
 getInitialState: function() {
    return {
      dataSource: new ListView.DataSource({
        rowHasChanged: (row1, row2) => row1 !== row2,
      }),
      isLoading: true,
      replyCount: 0,
    }
  },
```

so what cause the problem ?

**Comment by magicismight** [comment]
This had been fixed in the latest version [#756](https://github.com/facebook/react-native/issues/756)
Try update react-native

**Comment by LeezQ** [comment]
still crash， my react-native version is `0.3.11`  @a2

**Comment by brentvatne** [comment]
@LeezQ - are you still seeing this? It does look very much like #756, maybe you had to restart XCode?

**Comment by brentvatne** [comment]
@LeezQ - I ran your first example here and it worked fine with the latest version, although I had to make sure that `getInitialState` at least returned `{}`, so I'm going to close this issue. Ping me if it persists and provide the full error message and full component that causes it so I can run that on my own and verify.
