### ISSUE TITLE
"error on socket" after SocketRocket: In debug mode. Allowing connection to any root cert 

### ISSUE THREAD

**Issue by inturbidus** [facebook/react-native#7914]
I'm getting an error when trying to observe a Parse Query.

> SocketRocket: In debug mode. Allowing connection to any root cert
> error on socket

```
  observe(props, state) {
    var query = new Parse.Query('Get');
    return state.isLoading ? { items: query } : null;
  }

  _executeQuery() {
    this.setState({ isLoading: true });
  }
  
  render() {

   function setSelectedOption(option){
      this._executeQuery();
      this.setState({
        selectedCustomSegment: option,
        gender: option,
      });
    }
    
    console.log(this.data.items);
    return (<View></View>);
  }
```

Here's the versions I'm using in my package.json

    "react": "15.0.2",
    "react-native": "^0.26.2",
    "react-native-keyboard-aware-scroll-view": "0.0.7",
    "react-native-navbar": "^1.2.2",
    "parse": "^1.6.14",
    "parse-react": "^0.5.0",
    "events": "^1.1.0",

I'm using VS Code and running on iOS Simulator.

- [X] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [-] Provide **screenshots** where appropriate
- [X] What's the **version** of React Native you're using? 0.26.2
- [X] Does this occur on **iOS**, Android or both?
- [X] Are you using **Mac**, Linux or Windows?

**Comment by inturbidus** [comment]
After debugging the RCTWebSocket.xcodeproj, got the root error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

So this is probably just a connection problem.

**Comment by inturbidus** [comment]
Confirmed.  Some issue with the simulator behind firewall.

**Comment by danieljvdm** [comment]
How was this fixed?

**Comment by pewh** [comment]
+1 face same issue on real device

**Comment by saudpunjwani101** [comment]
same issue

**Comment by shuaibird** [comment]
@danieljvdm I use shadowsocks + proxifier to get this issue resolved.

**Comment by RameshSain** [comment]
1. Select hardware from menu 
2.Erase All content and settings

**Comment by knowge** [comment]
I had same issue and socket-io client connection problem, and still same warning but I figured out the connection problem. If anyone has a problem about connecting to socket-io server, you guys try this;

Pass "transports: ['websocket']" parameter as option in connect() function. 

```
const socketIOConnOpt = {
            'force new connection': true,
            reconnection: true,
            reconnectionDelay: 10000,
            reconnectionDelayMax: 60000,
            reconnectionAttempts: 'Infinity',
            timeout: 10000,
            **transports: ['websocket']**
        };
        const socket = SocketIOClient.connect(endpointUrl, socketIOConnOpt);
```
