### ISSUE TITLE
[iOS] Initial value of AppState.currentState is incorrect when app is launched into the background

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#7919]
### Bug

When the app is launched into the background, `AppState.currentState` should be `'background'`. However, instead, if you read it too soon, its value is `'active'`. If you wait long enough, it'll become `'background'`.

I haven't tested this on Android but I suspect Android has the same bug. It looks like [the JavaScript code initializes `currentState` to `active`](https://github.com/facebook/react-native/blob/7028929d8f44872e790376875c7971155bb99f81/Libraries/AppState/AppState.js#L86-L90) and then relies on an async call to set it to its actual value.

### Impact

When an app launches into the background, it's common to want to handle this case specially to minimize the amount of work that is done (for example, there's no need to render UI). This bug breaks such optimizations by causing the app to think it's being launched into the foreground even though it's being launched into the background. By the time `AppState.currentState` has the correct value, the app has already started some unnecessary work.

### Repro Steps

Tested with react-native 0.26.3.

1. Use `react-native init` to create a new project.
2. Put the following code after the project imports in `index.ios.js`:

   ```
  console.log('init currentState: ' + AppState.currentState);
  setInterval(function () {
    console.log('currentState: ' + AppState.currentState);
  }, 1000);
   ```
3. Edit the app's capabilities. Under "Background Modes" check "Background fetch".
4. Go to the `Product > Scheme > Manage Schemes` menu item.
5. Select the app
6. Under "Run", go to the "Options" tab
7. Check "Launch due to a background fetch event"

Run the app. You should see the following logged to the console:

```
init currentState: active
currentState: background
currentState: background
...
```

Instead, I would expect the first line to read `init currentState: background`

### Possible fix

Can we fix this by including `UIApplication`'s `applicationState` in `constantsToExport` of the `AppState` module? Then we can initialize `currentState` to that value rather than to `'active'`.

It looks like this approach was already tried and then it was reverted (https://github.com/facebook/react-native/commit/0fb3d8de83c4d8b79a8a110e9cd1300b39ab8918). Why?

cc @zjj010104

**Comment by rigdern** [comment]
@zjj010104 @nicklockwood Any thoughts on the "Possible fix" listed above? It's important for me to get this bug fixed for my app. However, it looks like the fix I have in mind was already tried and reverted. I'd like to understand why and what the right way to fix this would be.

**Comment by charpeni** [comment]
@facebook-github-bot label iOS
