### ISSUE TITLE
webview release source={require(xxx.html)} not work

### ISSUE THREAD

**Issue by lisong** [facebook/react-native#7924]
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

`<WebView source={require('./helloworld.html')} />`

ios release/debug is OK, android debug is OK too, only broken on android release versions, is blank page, nothing rendered.
- [0.27.rc1] What's the **version** of React Native you're using?
  0.27.rc1
- [android] Does this occur on iOS, Android or both?
  android release
- [mac] Are you using Mac, Linux or Windows?
  mac

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by jak4** [comment]
I'm having the same issue with 0.26.3. Any known workarounds?

**Comment by Cap32** [comment]
The same issue with 0.27.2

**Comment by Kureev** [comment]
It happens on iOS as well: https://github.com/facebook/react-native/issues/8996

**Comment by 289420843** [comment]
How to solve？

**Comment by jatazoulja** [comment]
happens on android release build, seems to be working on emulator. the url somehow points to `http://localhost:8081/`on debug build.

**Comment by sodik82** [comment]
same here 0.37 - onload event is fired but only white page is shown. what's funny that I could not "reuired" html between apk assets but maybe it is hidden somewhere else.

**Comment by Micjoyce** [comment]
same here 0.39.2,  When I release andorid apk, webview can not load html by require('./index.html') , but ios work well.
How to fix this? someone has any idea?

**Comment by aayushanand99** [comment]
Facing same issue 0.38.1. Please tell how to solve or some workaround for webViewBridge?

**Comment by Lxxyx** [comment]
SameProblem.

**Comment by askishore999** [comment]
You might wanna check this solution.

https://github.com/facebook/react-native/issues/505#issuecomment-244463151

**Comment by FuadBalashov** [comment]
Still seeing this with 0.42

**Comment by jedt** [comment]
this works as a workaround for me: https://github.com/facebook/react-native/issues/505#issuecomment-218480163

**Comment by Traviskn** [comment]
I'm running into this issue on 0.44 as well.

**Comment by bitfabrikken** [comment]
HTML files still not being packaged in Android release on React Native 0.45.1

**Comment by hyochan35** [comment]
When will this be fixed? This is really annoying..

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, we're automatically closing issues after a period of inactivity. Please do not take it personally!

If you think this issue should definitely remain open, please let us know. The following information is helpful when it comes to determining if the issue should be re-opened:

- Does the issue still reproduce on the latest release candidate? Post a comment with the version you tested.
- If so, is there any information missing from the bug report? Post a comment with all the information required by the [issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md).
- Is there a pull request that addresses this issue? Post a comment with the PR number so we can follow up.

If you would like to work on a patch to fix the issue, *contributions are very welcome*! Read through the [contribution guide](http://facebook.github.io/react-native/docs/contributing.html), and feel free to hop into [#react-native](https://discordapp.com/invite/0ZcbPKXt5bZjGY5n) if you need help planning your contribution.

**Comment by yosimasu** [comment]
### Is this a bug report?

Yes



### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  6.10.3
  Yarn:  0.24.5
  npm:  3.10.10
  Watchman:  4.7.0
  Xcode:  Xcode 9.0 Build version 9A235
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-alpha.12 => 16.0.0-alpha.12
  react-native: 0.48.4 => 0.48.4


### Steps to Reproduce



(Write your steps here:)

1. create `index.html`
```
<html>
    <head>
        <title>Title</title>
    </head>
    <body>
        <h1>Hello</h1>
        <h2>World</h2>
    </body>
</html>
```
2. modify `index.ios.js` and `index.android.js`
```
3. 

### Expected Behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Just write down what you thought would happen.
-->

(Write what you thought would happen.)

### Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't just say "it doesn't work"!
-->

(Write what happened. Add screenshots!)

### Reproducible Demo

<!--
  Please share a project that reproduces the issue.
  There are two ways to do it:

    * Create a new app using https://snack.expo.io/ and try to reproduce the issue in it.
      This is useful if you roughly know where the problem is, or can’t share the real code.

    * Or, copy your app and remove things until you’re left with the minimal reproducible demo.
      This is useful for finding the root cause. You may then optionally create a Snack.

  This is a good guide to creating bug demos: https://stackoverflow.com/help/mcve
  Once you’re done, copy and paste the link to the Snack or a public GitHub repository below:
-->

(Paste the link to an example project and exact instructions to reproduce the issue.)

<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

**Comment by yosimasu** [comment]
I create new [issue](https://github.com/facebook/react-native/issues/16133)

**Comment by HHuiHao** [comment]
this works as  for me!!!
![](https://user-images.githubusercontent.com/8486113/33197119-6b6d7380-d11e-11e7-8891-035465233935.png)

**Comment by Lxxyx** [comment]
@HHuiHao Great
This works. You just need write a simple shell script to cpoy you html files to android assets.

**Comment by Arshiamidos** [comment]
#16133
just ckeckout my answer it worked for me

**Comment by Arshiamidos** [comment]
#16133
just ckeckout my answer it worked for me
i used ckeditor
