### ISSUE TITLE
KeyboardObserver class doesn't exists but using in Keyboard.js

### ISSUE THREAD

**Issue by nizsheanez** [facebook/react-native#7930]
- Look to https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=KeyboardObserver - 
KeyboardObserver class doesn't exists but using in Keyboard.js and NativeEventEmitter except not null
- **Screenshot** http://image.prntscr.com/image/6b590a66e1bd4c53a685a342e016ff63.png
- **Version** v0.27.0-rc2 
- **Platform** - I only checked on iOS
- **OS** - I using Mac (10.11.5)

It happening when i using ListView:
```js
import {ListView} from 'react-native'

new ListView.DataSource({
     rowHasChanged: (row1, row2) => row1 !== row2,
})
```

**Comment by nizsheanez** [comment]
i think it was my miss-configuration, start project from scratch and using rnpm - fixed it.

**Comment by someok** [comment]
I have this problem too after upgrade to 0.27, can you share the solution?

thanks

**Comment by someok** [comment]
Oh, It's the pod config problem:(

**Comment by oureta** [comment]
`npm install -g rnpm`
`rnpm link`

https://github.com/facebook/react-native/issues/8025

**Comment by notlose** [comment]
Hi @someok did you resolve the problem? i am looking for solution too
