### ISSUE TITLE
Issue after upgrade to 0.26.2

### ISSUE THREAD

**Issue by zh-wowtv** [facebook/react-native#7944]
I got the following error when I run **npm start -- --reset-cache**:

> ENOENT: no such file or directory, open 'ReactComponentTreeDevtool.js'

After I upgrade to react 0.26.2. My package.json:

>    "react": "15.0.2",
>    "react-native": "^0.26.2",

What could be the reason?

**Comment by xxsnakerxx** [comment]
@zh-wowtv Update react to 15.1.0 and RN to 0.27

**Comment by zh-wowtv** [comment]
Got another issue when I upgrade to 15.1.0 and 0.27. Please refer to: https://github.com/fbsamples/f8app/issues/66

**Comment by andrewbrereton** [comment]
Did you run `react-native upgrade`?

**Comment by zh-wowtv** [comment]
Fixed

**Comment by ralberts** [comment]
@zh-wowtv Seems I am running into the same problems :-).  Do you happen to have a fork?  Or would you be up for posting your package.json and other changes?
