### ISSUE TITLE
Add a timeout for Image uri loading on Images.

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native#7952]
Hello, I noticed that if I pass a **uri** as the source of my Image, and the link is not right, or it takes to long to load, I will never get an **onError** event, as if nothing bad ever happened.

1. Could you please throw an error when the uri does not respond or takes too long to do so? 

2. It would be great if you allowed us to add a timeout (in milliseconds) before the error is thrown, something like `uriTimeout`.

**Comment by charpeni** [comment]
Could be interesting.

@SudoPlz Are you up for a pull request?

**Comment by charpeni** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-6** [comment]
Hey @SudoPlz! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
