### ISSUE TITLE
listview out of memory

### ISSUE THREAD

**Issue by iceskyblue** [facebook/react-native#7960]
I have 1000 row need to display in a listview, when the listview scrolling ,the memory increase so fast. 
when the listview scroll to 600 rows, it can't scroll any more, and out of memory occur.
os: android
compile sdk: 23

another: the scrollto function can't scroll to a row. if the row have not rended.

**Comment by vharuty** [comment]
@iceskyblue Could you please provide a code to reproduce? Thanks

**Comment by iceskyblue** [comment]
@vharuty mycode is:
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  ToastAndroid,
  TouchableOpacity,
  Image,
  NativeModules,
  DeviceEventEmitter
} from 'react-native';

var dataControl = NativeModules.AchievementDataControl;

var dataSet = [];
var ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});

class reactNative extends React.Component {
	
	constructor(props) {
		super(props);
		//var datas = this._generaRow();
		this.state = {dataSource: ds.cloneWithRows(dataSet)};
		//setTimeout(this.updateData.bind(this), 5000);
		this._listDataChanged = this._listDataChanged.bind(this);
	}    
	
	//updateData(){
	//	dataControl.getData(this.dataCallback.bind(this));
	//}
	
	dataCallback(data){
		dataSet = JSON.parse(data);
		this.setState( {dataSource: ds.cloneWithRows(dataSet)});
	}
	
	_generaRow(){
			for(var ii=100; ii<10000;ii++){
				dataSet.push({'paimin':ii+10});
			}
			return dataSet;
	}
	
	componentWillMount(){
		DeviceEventEmitter.addListener(
                       'achievement_data_changed',
                       this._listDataChanged);
	}
	
	_listDataChanged(e:Event){
		dataControl.getData(this.dataCallback.bind(this));
	}
	
    _renderRow(rowData: Object,sectionID: number, rowID: number) {
	
		var retialOpacity = 0;
		var lltubStyle = styles.lltubShow;
		var imgSource = 'rank_normal';
		var rowBg = '#d9d6d7';
		var indexTextColor = '#f06100';
		var index = rowID*1+1;
		if(rowID == 0){
			imgSource='rank_one';
			rowBg='#fb684b';
			indexTextColor = '#bc4f00';
		}else if(rowID == 1){
			imgSource='rank_two';
			rowBg='#fb684b';
			indexTextColor = '#666666';
		}else if(rowID == 2){
			imgSource='rank_three';
			rowBg='#fb684b';
			indexTextColor = '#532810';
		}
		
		if(rowData.haslltub === false){
			lltubStyle = styles.lltubGone;
		}
		
		if(rowData.hasRetail === true){
			retialOpacity = 255;
		}
		
    return (
        <TouchableOpacity>
          <View style={{backgroundColor:'#d9d6d7'}}>
            <View style={{flexDirection: 'row', alignItems: 'center', paddingLeft: 10, paddingRight: 10, backgroundColor:rowBg}}>
				<View>
					<View style={{backgroundColor:'#aaaaaa', width:6, height:80, marginLeft: 32}}/>
					<Image source={{uri:imgSource}} style={[{alignItems: 'center', justifyContent: 'center', width:70, height:72},{position: 'absolute', top:0, left: 0}]}>
						<Text style={{color:indexTextColor}}>
						{index}
						</Text>
					</Image>
				</View>
				<Image source={{uri:'rn_head'}} style={{marginLeft:32, width:40, height:70}}  resizeMode={Image.resizeMode.stretch}/>
				<Image source={{uri:'rn_center'}} style={{flex:1, height:70, justifyContent:'center'}} resizeMode={Image.resizeMode.stretch}>  
						
					<View style={{flexDirection:'row'}}>
					   <View style={{alignItems: 'center'}}>
						   <Image source={{uri:'bg_photos_normal'}} style={{width:55, height:55, alignItems: 'center', justifyContent:'center'}} resizeMode={Image.resizeMode.contain}>
							   <Image source={{uri:'photos_small'}} style={{width:20, height:20}} resizeMode={Image.resizeMode.contain}>
							   </Image>
						   </Image>
					   
					   </View >
					   <View style={{ justifyContent: 'center'}}>
							<View  style={{flexDirection:'row', alignItems: 'center'}}>
							  <Image source={{uri:'icon_mark_retail',width:15, height:15}} resizeMode={Image.resizeMode.contain} style={{opacity:retialOpacity}}>
							  </Image>
							  <Text style={{marginLeft:3, fontSize: 16, color:'#555555'}}>
								  {rowData.userName}
							  </Text>
							</View>
							<Text style={lltubStyle}>
								业务提成
								<Text style={{color:'#f06100', fontSize:14}}>
									{rowData.tvTub}
								</Text>
							</Text>
							<Text style={{color:'#555555', fontSize:14}}>
								{rowData.achievementType}
								<Text style={{color:'#f06100', fontSize:14, paddingLeft:3}}>
									{rowData.achievement}
								</Text>
							</Text>
					   </View>
					</View>
				</Image>
				<Image source={{uri:'rn_tail'}} style={{width:12, height:70}}  resizeMode={Image.resizeMode.stretch}/>
            </View>
          </View>
        </TouchableOpacity>
    );
   }
   
    render() {
      return (
        <ListView
		  pageSize={20}
		  removeClippedSubviews={true}
		  enableEmptySections={true}
          dataSource={this.state.dataSource}
          renderRow={this._renderRow}
        />
      );
    }
 
}

var styles =StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
	paddingRight: 10,
	marginLeft:20
  },
  thumb: {
    width: 50,
    height: 50,
  },
  lltubShow:{
	  color:'#555555', 
	  fontSize:14, 
	  marginRight:8
  },
  lltubGone:{
	  width:0,
	  height:0
  }
});

**Comment by glcrazier** [comment]
I guess it's an existing issue because the listview doesn't support recycling at this moment.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-out-of-memory

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
