### ISSUE TITLE
Running react-native run-ios occurs an error?

### ISSUE THREAD

**Issue by DreamXiao** [facebook/react-native#7965]
xiaoheng:~ xiaoheng$ react-native init AwesomeProject
This will walk you through creating a new React Native project in /Users/xiaoheng/AwesomeProject
Installing react-native package from npm...
Setting up new React Native app in /Users/xiaoheng/AwesomeProject
AwesomeProject@0.0.1 /Users/xiaoheng/AwesomeProject
└── react@15.1.0 

To run your app on iOS:
   cd /Users/xiaoheng/AwesomeProject
   react-native run-ios
   - or -
   Open /Users/xiaoheng/AwesomeProject/ios/AwesomeProject.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   cd /Users/xiaoheng/AwesomeProject
   react-native run-android
xiaoheng:~ xiaoheng$ cd /Users/xiaoheng/AwesomeProject
xiaoheng:AwesomeProject xiaoheng$  react-native run-ios
Found Xcode project AwesomeProject.xcodeproj
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
/Users/xiaoheng/AwesomeProject/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: xcrun simctl list devices
xcrun: error: unable to find utility "simctl", not a developer tool or in PATH

    at checkExecSyncError (child_process.js:486:13)
    at Object.execFileSync (child_process.js:506:13)
    at _runIOS (runIOS.js:62:19)
    at runIOS.js:24:5
    at tryCallTwo (/Users/xiaoheng/AwesomeProject/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/xiaoheng/AwesomeProject/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/xiaoheng/AwesomeProject/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (runIOS.js:23:10)
    at Object.run (/Users/xiaoheng/AwesomeProject/node_modules/react-native/local-cli/cli.js:87:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:88:7)

**Comment by yanghuxiao** [comment]
Xcode > Preferences > Locations 
And assigning the Command Line Tools

**Comment by DreamXiao** [comment]
@yanghuxiao thank you .it's done!

**Comment by gotoAndBliss** [comment]
I just upgraded to Xcode 8.3 , and I have my command line tools selected ( they're the only selectable ones ), but I'm still getting this error 

```
)
Found Xcode project ratSlapMobile.xcodeproj
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk" cannot be located.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH

Command failed: xcrun instruments -s
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk" cannot be located.
xcrun: error: unable to find utility "instruments", not a developer tool or in PATH
``

**Comment by Elethier** [comment]
@gotoAndBliss I was running into the same error with xcodebuild. You should check the value of the `SDKROOT` environment variable. Even after upgrading Xcode, mine was still set to `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk`. I suggest you change it to `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk`.
