### ISSUE TITLE
RefreshControl showing issue on RN 0.27

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#7976]
I have an issue with `RefreshControl` with React Native 0.27.x on iOS. The `RefreshControl` is creeping up on the top right side of my view until I use it the first time:

![simulator screen shot jun 7 2016 3 11 18 pm](https://cloud.githubusercontent.com/assets/2040807/15858704/1c26e204-2cc2-11e6-9f78-cd124d2037bf.png)

The weird thing is that if I don't pass the `tintColor` prop, it works great.

Here is my `RefreshControl`:
```
<RefreshControl
  refreshing={isRefreshing}
  onRefresh={this.handleRefresh.bind(this)}
  tintColor={Colors.RED1}
  colors={[Colors.BLUE1, Colors.RED1, Colors.ORANGE1]}
  progressBackgroundColor={Colors.WHITE1} />
```

cc @janicduplessis

**Comment by dozoisch** [comment]
I'm getting the exact same thing in iOS simulator.

Using:
```
              <RefreshControl
                refreshing={this.state.refreshing}
                onRefresh={this.handleRefresh}
                title="Refresh"
              />
```
It disappears once the view gets touched.

**Comment by agat** [comment]
Temporary fix — remove `title` property from `RefreshControl `.

**Comment by marcosinigaglia** [comment]
Same issue, I fix removing `tintColor` prop.

**Comment by janicduplessis** [comment]
Do you know if this issue only happens since 0.27?

**Comment by Bhullnatik** [comment]
@janicduplessis I'm not sure, we skipped 0.26.x versions due to various bugs. 0.25.x was working fine.

**Comment by dozoisch** [comment]
@janicduplessis I was on 0.26.3 before it was fine!

**Comment by spyro92** [comment]
Same issue here with tintColor

**Comment by zerko** [comment]
@janicduplessis it is 0.27 only issue.

**Comment by lisong** [comment]
0.28.0 happens too!

**Comment by vanBrunneren** [comment]
I'm facing this issue with RN 28.0 even if I remove tintColor and title:

```
<ListView
	renderSectionHeader={this._renderSectionHeader.bind(this)}
	refreshControl={
		<RefreshControl
			refreshing={this.state.isRefreshing}
			onRefresh={this._onRefresh.bind(this)}							
			/>
	}
	onEndReached={ () => this._onEndReached() } 
	dataSource={this.state.dsHomeViewList}
	renderHeader={this._renderHeader.bind(this)}
	renderRow={this._renderHomeList.bind(this)}
	renderFooter={this._renderFooter.bind(this)} />
```

![juni-27-2016 14-41-10](https://cloud.githubusercontent.com/assets/11269836/16380120/71c38588-3c75-11e6-81e2-042dc300b09a.gif)


does anyone has a working temporary (or better a stable) fix for this?

**Comment by magrinj** [comment]
As a temporary fix I just set the background color of my row, or header or whatever you have at the top of the list view on your app. I take a look in the `RefreshControl` class and in native component and I can't see anything different since the `0.27`, maybe something change in the style engine.

**Comment by plrthink** [comment]
same issue here with just passing `refreshing` and `onRefresh` props to `RefreshControl`。

**Comment by plrthink** [comment]
my app has two tab bar at the bottom and each one will render its own listview. what's interesting is that this problem only occurs when I switch the listview and then switch back. It looks like the upper two screenshots also have this kind of layout.

<img width="359" alt="screen shot 2016-07-04 at 16 41 58" src="https://cloud.githubusercontent.com/assets/2429369/16555711/92cde1f4-4208-11e6-8417-2fd367d6e65f.png">

**Comment by tofrookie** [comment]
how to fix it

**Comment by ios122** [comment]
@tofrookie @plrthink  Test  iOS With 0.29.0 , solve this by backgroundColor,
```
<RefreshControl
           style={{
             backgroundColor:'##0000',
           }}
          refreshing={this.state.refreshing}
           />
```

**Comment by TanTan-TT** [comment]
```
<RefreshControl
           style={{
             backgroundColor:'transparent',
           }}
          refreshing={this.state.refreshing}
           />
```
Setting backgroundColor to transparent is worked for me

**Comment by rclai** [comment]
I'm on 0.29.0 and it's happening to me.

**Comment by messense** [comment]
Same issue on 0.30.0

**Comment by ghuh** [comment]
Same issue on 0.31.0-rc.0 while only passing in refreshing and onRefresh.  Setting backgroundColor to transparent seems to have fixed the issue.

**Comment by GantMan** [comment]
This bug has persisted for a very long time and is actually part of several apps for us now.  So I submitted a PR in the hopes of assuaging our pain until @janicduplessis et. al. find a better way.

**Comment by GantMan** [comment]
@Bhullnatik - you can close this, my PR was accepted, this will be fixed.

**Comment by uc-asa** [comment]
I'm using 0.30 
<RefreshControl
				            refreshing={ this.state.isRefreshing }
				            onRefresh={() => this._onRefresh()}
				            style={{
				             	backgroundColor : 'transparent',
				          	}}
				            tintColor="#ccc"
				            title="Loading..."
				            titleColor="#5a6d7d"
				            colors={['#ff0000', '#00ff00', '#0000ff']}
				            progressBackgroundColor="#ffff00"
		          		/>


It works for me
