### ISSUE TITLE
[Android] React-Native calls socket.io initializer multiple times when NOT connected to the JS Debugger

### ISSUE THREAD

**Issue by bvanderdrift** [facebook/react-native#7978]
```
react-native-cli: 0.2.0
react-native: 0.26.1
Mobile OS: Android
OS: Ubuntu 14.04 LTS
```

I'm creating a simple chat client for learning purposes ([Repo](https://github.com/bvanderdrift/MyReactNativeChatApp)) using a fork of the socket.io chat-example project ([Repo](https://github.com/bvanderdrift/chat-example)).

I noticed multiple connections coming in on the socket.io server if I was **not** using the debugger on my development device.

I traced it back to the Socket io constructor being called with a parameter passed by React-Native. The constructor returns a value upon reaching

https://github.com/socketio/socket.io-client/blob/master/socket.io.js#L55

```
function Socket(uri, opts){
  if (!(this instanceof Socket)) return new Socket(uri, opts);
  ...
}
```

`this` is in this case an object `m_context` which is created in a method in the C++ code

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/jni/react/JSCExecutor.cpp#L164

These parameters can be found if the contents of the `this` object are printed.

I don't know how the C++ code calls the Socket.io code which is imported as an external node module. I noticed the original creation upon calling `io.connect('http://localhost:3000', {jsonp: false})` doesn't use the same return as the C++ code.

Stack trace of the call:
```
E/unknown:React(32096): error@58225:12
E/unknown:React(32096): Socket@78031:14
E/unknown:React(32096): connect@82528:16
E/unknown:React(32096): <unknown>@82838:10
E/unknown:React(32096): <unknown>@7778:18
E/unknown:React(32096): callTimer@7549:9
E/unknown:React(32096): callTimers@7572:17
E/unknown:React(32096): __callFunction@6931:28
E/unknown:React(32096): <unknown>@6835:22
E/unknown:React(32096): guard@6789:3
E/unknown:React(32096): callFunctionReturnFlushedQueue@6834:6
```

All the `<unknow>` parameters are enormous stacktraces with `mountComponent`/`mountChildren`/`update`/`run` etc. calls in them.

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-react-native-calls-socketio-initializer-multiple-times-when-not-connected-to-the-js-debugger

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by AnsalAli-mudano** [comment]
I just encountered a related issue. ie, when connected to the debugger socketio never called.

> "react-native": "0.38.0",
> "socket.io-client": "^1.7.1"
