### ISSUE TITLE
Vanilla react-native build fails when using Auth0's react-native-lock

### ISSUE THREAD

**Issue by sbefort** [facebook/react-native#7980]
The Auth0 team says this is a React Native issue:

https://github.com/auth0/react-native-lock/issues/60

**Comment by charpeni** [comment]
It seems to be an integration issue to me and it's seem resolved.

I'll close it, if you still have this issue, please let me know and provide more information.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-2** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
