### ISSUE TITLE
Keyboard module isn't in 0.27.1

### ISSUE THREAD

**Issue by powerc9000** [facebook/react-native#7986]
The release notes claim 

>Keyboard events should now be registered via Keyboard module (currently Keyboard module is not exposed, require it globally or wait for the 0.27.1 that will be released later today / tomorrow morning)

But if you look at the tag it isn't required.
https://github.com/facebook/react-native/blob/v0.27.1/Libraries/react-native/react-native.js

**Comment by undef1ned** [comment]
`import Keyboard from 'Keyboard'`

this worked for me

**Comment by kfiroo** [comment]
`const Keyboard = require('Keyboard');`
This works for me on 0.27.1

In the release it said:
> require it globally or wait for the 0.27.1

What does that mean? How should we require it when using 0.27.1?

**Comment by satya164** [comment]
cc @grabbou

**Comment by grabbou** [comment]
Yes, this is getting released today. Sorry for the delay. I'll close this issue once the release is out.

**Comment by grabbou** [comment]
Part of 0.27.2 (Circle build in progress)

**Comment by grabbou** [comment]
@kfiroo sorry for the bad description, I've replaced it with examples showing how to require it based on the version you are running :)

**Comment by kfiroo** [comment]
@grabbou Awesome, Thanks! 👍
