### ISSUE TITLE
ActivityIndicatorIOS doesn't hide initially in 0.27

### ISSUE THREAD

**Issue by Purii** [facebook/react-native#7987]
There seems to be a bug with `ActivityIndicatorIOS ` in the latest stable release. 

1. Set `animating={false}` **dynamically** works as expected (ActivityIndicatorIOS is hidden)
2. Set `animation={false}` as **initial prop** won't hide it.

## Reproduce

*I assume that HMR is enabled for steps 3-5. Otherwise just use the template below.*

1. Fresh project: react-native init helloWorld
2. Add `<ActivityIndicatorIOS animating={false} />` to `index.ios.js`
3. Run the simulator, e.g. via `react-native run-ios` --> **Is shown and not animated**
4. Change prop to `<ActivityIndicatorIOS animating={true} />` --> **Is shown and animated**
5. Change prop back to `<ActivityIndicatorIOS animating={false} />` --> **Is hidden as it should**

### Template

```javascript
...
import {
  AppRegistry,
  ActivityIndicatorIOS,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
...
class helloWorld extends Component {
  constructor(props) {
    super(props);
    this.state = {
      animateActivityIndicatorIOS: false,
    }
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={() => this.setState({animateActivityIndicatorIOS: !this.state.animateActivityIndicatorIOS})}>
          <Text>Toggle ActivityIndicatorIOS</Text>
        </TouchableOpacity>
        <Text>{'\n'}This ActivityIndicatorIOS should be shown initially, although animating=false:{'\n'}</Text>
        <ActivityIndicatorIOS animating={this.state.animateActivityIndicatorIOS} />
      </View>
    );
  }
}
```

**Comment by charpeni** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
It seems like calling `UIActivityIndicator.stopAnimating` doesn't work before the view has been layed out. I had a similar issue with `RefreshControl` and what I ended up doing is calling it in the first call you `layoutSubviews`. If someone wants to submit a PR to fix this it would be great as I'm pretty busy at the moment :)

**Comment by timjacobi** [comment]
Can this be closed?
