### ISSUE TITLE
Animated View inside TouchableNativeFeedback

### ISSUE THREAD

**Issue by janicduplessis** [facebook/react-native#7996]
I get an error (`Attempted to assign to readonly property.`) when nesting an `Animated.View` inside a `TouchableNativeFeedback`. 

Here is a minimal repro case.
``` js
class Test extends Component {
  state = {
    animatedValue: new Animated.Value(0),
  };

  render() {
    return (
      <TouchableNativeFeedback>
        <Animated.View style={{ color: this.state.animatedValue }}>
          ...
        </Animated.View>
      </TouchableNativeFeedback>
    );
  }
}
```

This happens because the animated value object gets frozen / sealed when it's animated view is a direct child of `TouchableNativeFeedback`. Adding a intermediate View between the `TouchableNativeFeedback` and the `AnimatedView` works around the issue.

**Comment by timotius02** [comment]
Any progress on getting this fixed. I have an Android project where I'm testing animating flex values inside a TouchNativeFeedback and this is proving to be a major hurdle since I can't add an intermediary View.
