### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by nick** [facebook/react-native#80]
I just pulled the latest commits and when I try to run the UIExplorer example I get this:

![screen shot 2015-02-19 at 8 51 21 am](https://cloud.githubusercontent.com/assets/939/6270067/80933e78-b814-11e4-86ba-990640cdbe6b.png)

Also get this in the log:

```
2015-02-19 08:49:11.725 UIExplorer[39524:4212632] CLTilesManagerClient: initialize, sSharedTilesManagerClient
2015-02-19 08:49:11.727 UIExplorer[39524:4212632] CLTilesManagerClient: init
2015-02-19 08:49:11.727 UIExplorer[39524:4212632] CLTilesManagerClient: reconnecting, 0x7fada40806e0
RCTJSLog> "Error: 
 stack: http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:1949:29
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:1326:22
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:1136:36
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:1088:20
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:1025:24
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:983:31
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:938:20
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
applyWithGuard@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:871:25
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:194:39
global code@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:33154:9
 line: 1949
 message: Can't find variable: process", {"line":1949,"column":29,"sourceURL":"http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle"}
RCTJSLog> "Error: 
 stack: ModuleError@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:105:23
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:206:28
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:20370:22
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:20334:35
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30
applyWithGuard@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:871:25
require@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:194:39
global code
 line: 208
 message: Requiring module "warning" which threw an exception", {"name":"ModuleError","message":"Requiring module \"warning\" which threw an exception","stack":"ModuleError@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:105:23\nrequire@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:206:28\nhttp://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:20370:22\nrequire@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30\nhttp://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:20334:35\nrequire@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:243:30\napplyWithGuard@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:871:25\nrequire@http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle:194:39\nglobal code","framesToPop":2,"line":208,"column":8,"sourceURL":"http://localhost:8081/Examples/UIExplorer/UIExplorerApp.includeRequire.runModule.bundle"}
```

**Comment by mschipperheyn** [comment]
Getting this issue against current version on a cleanly created project

    	2015-06-06 13:32:25.968 [error][tid:com.facebook.React.JavaScript] "Error: 
	 stack: keyMirror@http://localhost:8081/index.ios.bundle:1717:28
	http://localhost:8081/index.ios.bundle:1624:34
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:1404:29
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:1257:31
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:1177:54
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:1131:20
	require@http://localhost:8081/index.ios.bundle:245:30
	applyWithGuard@http://localhost:8081/index.ios.bundle:885:25
	require@http://localhost:8081/index.ios.bundle:196:39
	global code@http://localhost:8081/index.ios.bundle:43774:9
	 line: 1717
	 message: Can't find variable: process", {"line":1717,"column":28,"sourceURL":"http://localhost:8081/index.ios.bundle"}
	2015-06-06 13:32:25.971 [error][tid:com.facebook.React.JavaScript] "Error: 
	 stack: http://localhost:8081/index.ios.bundle:2704:29
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:21041:22
	require@http://localhost:8081/index.ios.bundle:245:30
	http://localhost:8081/index.ios.bundle:21000:35
	require@http://localhost:8081/index.ios.bundle:245:30
	applyWithGuard@http://localhost:8081/index.ios.bundle:885:25
	require@http://localhost:8081/index.ios.bundle:196:39
	global code
	 line: 2704
	 message: Can't find variable: process", {"line":2704,"column":29,"sourceURL":"http://localhost:8081/index.ios.bundle"}

**Comment by mschipperheyn** [comment]
Hmm, after trying various things. A full restart solved it

**Comment by chumster** [comment]
Interesting... now I'm see it:

2015-06-06 19:23:52.022 [error][tid:com.facebook.React.JavaScript] "Error: 
 stack: http://192.168.1.64:8081/index.ios.bundle:2047:29
require@http://192.168.1.64:8081/index.ios.bundle:245:30
http://192.168.1.64:8081/index.ios.bundle:1424:22
require@http://192.168.1.64:8081/index.ios.bundle:245:30
http://192.168.1.64:8081/index.ios.bundle:1234:36
require@http://192.168.1.64:8081/index.ios.bundle:245:30
http://192.168.1.64:8081/index.ios.bundle:1156:54
require@http://192.168.1.64:8081/index.ios.bundle:245:30
http://192.168.1.64:8081/index.ios.bundle:1127:20
require@http://192.168.1.64:8081/index.ios.bundle:245:30
applyWithGuard@http://192.168.1.64:8081/index.ios.bundle:885:25
require@http://192.168.1.64:8081/index.ios.bundle:196:39
global code@http://192.168.1.64:8081/index.ios.bundle:46141:9
 line: 2047
 message: Can't find variable: process", {"line":2047,"column":29,"sourceURL":"http://192.168.1.64:8081/index.ios.bundle"}

**Comment by dvcrn** [comment]
Is there a workaround for this? I just started having this issue as well

**Comment by jaredly** [comment]
@amasad did you ever add an option to clear the cache?
