### ISSUE TITLE
MapView annotation requiring custom icon fails with: Image source size {128, 128} does not match loaded image size {0, 0}

### ISSUE THREAD

**Issue by mauron85** [facebook/react-native#8004]
react-native version: 0.27.1

I was following [mapview example](https://facebook.github.io/react-native/docs/mapview.html) to use custom annotation icon.

```
<MapView
  style={styles.map}
  annotations={[
    {title: 'Thumbs Up!',
    latitude: 48.3124827,
    longitude: 18.0182664,
    image: require('image!uie_thumb_big')}
  ]}
/>
```
But I get error  Image source size {128, 128} does not match loaded image size {0, 0}

When I use  ```image: require('./uie_thumb_big')}```, it runs fine.

**Comment by charpeni** [comment]
Please use Leland Richardson's [react-native-maps](https://github.com/lelandrichardson/react-native-maps) as it is more feature-complete than our internal implementation.

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by facebook-github-bot-3** [comment]
Hey @mauron85, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by charpeni** [comment]
@facebook-github-bot close
