### ISSUE TITLE
fetch error should report responseText and status code

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#8006]
Currently, if fetch runs into a network request problem, it just prints "Network request failed". 

So, you have to step through a bunch of code to find out what is really going on. Simply printing the status code and responseText often gives you a perfect idea of what is going on. I suggest you add that.

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #7306

**Comment by facebook-github-bot-4** [comment]
@charpeni tells me this issue is a duplicate of #7306. Let's discuss there, closing this one.
