### ISSUE TITLE
iOS MapView annotations with custom views display as pins

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#8016]
On iOS react-native v0.26, it's possible for -[RCTMapManager mapView:viewForAnnotation:] to be called prior to an annotation's custom view to be inserted as a subview.  This is related to #7672.

If the manager needs to produce the annotation view, it's fine for all annotation types except those which have declared a custom view.  If it is a custom view and the react view has not been inserted into the subview, the following expression with fail:

(annotation.viewIndex != NSNotFound &&
      annotation.viewIndex < mapView.reactSubviews.count)

This will cause the code to fall through to produce a standard iOS pin.

Later, the custom view will be inserted into the map view's reactSubviews.  When it is, there is no association to a RCTMapAnnotationView to be hooked up as the content view.  The annotation will always be displayed as a pin at this point.

**Comment by charpeni** [comment]
Unfortunately, map component is not maintained anymore at least by the React Native Core Contributors team.

You should use [react-native-maps](https://github.com/lelandrichardson/react-native-maps) as it is more feature-complete than our internal implementation.

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by facebook-github-bot-3** [comment]
Hey @jwyld, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by jwyld** [comment]
Ha!  That's awesome.  Earlier I had a different issue written stating MapView should be removed from Core and placed into Experimental.  I couldn't write it without it coming off as critical and scathing.  I even made mention of the exact same 3rd party component as a better alternative.

I didn't see an issue file for moving MapView or removing it.  Can we repurpose this issue, or should I file a different one?

**Comment by charpeni** [comment]
I don't know exactly what's going to happen with the Map component, but I can say you should definitly move to [react-native-maps](https://github.com/lelandrichardson/react-native-maps).

I asked it in the oss group, you can follow the discussion [here](https://www.facebook.com/groups/reactnativeoss/permalink/1533524910277471/).

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by lacker** [comment]
Hey, we don't have an issue for this but we are working on figuring out how to deprecate stuff. We clearly need a system for doing it, and maps is our first target. I'm going to close this particular issue since the deprecation is the way to go here.
