### ISSUE TITLE
Bot testing

### ISSUE THREAD

**Issue by charpeni** [facebook/react-native#8026]
https://www.facebook.com/groups/reactnativeoss/permalink/1559394357690526/

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by charpeni** [comment]
cc @mkonicek @sdwilsh

**Comment by sdwilsh** [comment]
We have logging this time at least, but the bot seems to think you do not have permission to execute commands.  That is probably due to @mkonicek playing with settings on the UI page that clobbered my manual settings to work once a code push actually went out.

I've just re-set that up.  @charpeni, can you try again?

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by facebook-github-bot-6** [comment]
Hey @charpeni, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
@sdwilsh It seems fine for commands except the label one.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-8** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by facebook-github-bot-7** [comment]
Okay, reopening this issue.

**Comment by charpeni** [comment]
@facebook-github-bot label ios

**Comment by sdwilsh** [comment]
No logs for the labeling failure.  Looking into it more.

**Comment by mkonicek** [comment]
So happy to see this working, thank you so much Shawn!

<img width="779" alt="screen shot 2016-06-09 at 4 55 07 pm" src="https://cloud.githubusercontent.com/assets/346214/15936444/f65e1cde-2e62-11e6-8a97-341c5b4c51a8.png">

**Comment by sdwilsh** [comment]
Found the bug.  I'm putting a diff together now, and the fix should be out in a few hours.

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by sdwilsh** [comment]
Alright, the fix is now out (I think).

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by sdwilsh** [comment]
Indeed it is resolved.

**Comment by charpeni** [comment]
Yeah!! Thank you @sdwilsh :)

**Comment by sdwilsh** [comment]
It's my bad that it broke, but it should also respond a lot faster now 
that we are using the webhook to get data :)

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by charpeni** [comment]
@sdwilsh again :(

**Comment by sdwilsh** [comment]
Nothing appears to be wrong or broken.  Care to try again @charpeni?

Also @zpao is currently oncall, so he'll be dealing with this if it's still broken.

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by charpeni** [comment]
It's working again.

This is weird, it seems that every month or 2 months the bot is down for a few days and after it comes back like nothing. Unfortunately, this always happens when I want to do some triage.

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by sdwilsh** [comment]
Our API requests were getting denied by GitHub due to bad authentication.  I can't explain why, but this was using an older code path that I have now updated.  Can you try again @charpeni?

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by charpeni** [comment]
@sdwilsh nop :(

**Comment by sdwilsh** [comment]
Hmm, the old code still ran.  It would seem the release process for this code isn't what I thought it was.  Let me do some more investigating.

**Comment by sdwilsh** [comment]
I'm 90% sure we are running the new code now.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by charpeni** [comment]
@sdwilsh Running yes, working no.

See the label _Failed Commands_.

**Comment by sdwilsh** [comment]
Yeah, I just landed a fix for that.  The new code path has *much* better logging.  It'll take a little while for that to get all pushed out, and I'm out of the office a bit this afternoon, so probably won't be able to test this until tomorrow.

**Comment by charpeni** [comment]
Thank you for your time @sdwilsh !

**Comment by sdwilsh** [comment]
FWIW, we're working on a way to allow you to use GitHub (requires push permission) for this without actually being able to push code.  Then you don't need to even use the bot.

**Comment by charpeni** [comment]
That would be perfect and less noises in issues!

**Comment by sdwilsh** [comment]
I forgot to comment this morning: we should be good to retest this now.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by charpeni** [comment]
Great! Thanks @sdwilsh.

By curiosity, any ETA for GitHub access without push permission?

**Comment by sdwilsh** [comment]
My initial estimate was about a month ago.  I keep running into edge cases and legacy permission grants that I'm having to deal with and clean up, but I would expect it to be live by the end of August, assuming other things don't come up and take up my time.

**Comment by charpeni** [comment]
Feel free to ping me if you need anything.

**Comment by charpeni** [comment]
@sdwilsh Bad news, something happened again in https://github.com/facebook/react-native/issues/15308 and in others issues as well. 

(cc on call @ericnakagawa)

**Comment by sdwilsh** [comment]
The "good" news for me is that @zpao is oncall this week...

**Comment by zpao** [comment]
We found the last place (hopefully) we were caching credentials, resulting in the long running job trying to do some things with the original (but no longer valid due to rotation) credentials. Quick fix incoming so once that's in we'll restart the job and should be all set.

For a bit of additional info: the reason it half worked in that issue is because commenting goes through new code (which doesn't cache) but closing the issue went through the old code (which hasn't migrated to the better pattern).

**Comment by charpeni** [comment]
@zpao Thank you. 

I'd say you could remove @mkonicek from the bot error message since he doesn't work for Facebook anymore. His inbox will thank me.

**Comment by charpeni** [comment]
Hey @sdwilsh, any news about GitHub access without push permission?

**Comment by sdwilsh** [comment]
Not yet.  The long-tail of issues we need to resolve before enabling this happens to be longer than expected.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
Hey @sdwilsh @zpao, something is wrong with the bot again.

**Comment by sdwilsh** [comment]
@cdelahousse is oncall, but I suspect this is due to an issue around our webhook processing being delayed (although it should be all caught up now).

**Comment by sdwilsh** [comment]
@charpeni, I forgot to mention that we've rolled out issue management permission internally (back in December).  @hramos should be able to get that setup for you.

**Comment by charpeni** [comment]
Hey @sdwilsh,

Héctor has already set me up, thank you for your amazing work. :tada:
