### ISSUE TITLE
MapView custom marker dimensions

### ISSUE THREAD

**Issue by andyfenelon** [facebook/react-native#8037]
currently there is no means to set the dimensions of a custom marker image and markers are rendered at actual size. When these are used on retina devices they have blurry edges. 

i would propose  something like this so the dimensions can be set for @2x  

```
      if (!view && image && tintColor, width, height) {
        view = <Image
          style={{
            tintColor: processColor(tintColor),
            width: width,
            height: height
          }}
          source={image}
        />;
        image = undefined;
      }
```

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by charpeni** [comment]
Unfortunately, map component is not maintained anymore, at least by the React Native Core Contributors team.

You should use [react-native-maps](https://github.com/lelandrichardson/react-native-maps) as it is more feature-complete than our internal implementation.

**Comment by charpeni** [comment]
@facebook-github-bot bugfix

**Comment by facebook-github-bot-4** [comment]
Hey @andyfenelon, we're a small team and rely on the community to fix issues that don't affect fb apps. If you're sure this is a bug can you send a pull request with a fix?
