### ISSUE TITLE
Timestamp in IOS camera roll showing 1970 date

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#8044]
Using RN 0.27.2...

Running the [Camera Roll example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/CameraRollExample.js) in the UIExplorer code shows all images as having a timestamp in Jan 1970.  I don't _think_ this used to be the case.  I've checked using images on my phone and they're also all coming out with Jan 1970 timestamps.

<img width="470" alt="screen shot 2016-06-10 at 10 41 45" src="https://cloud.githubusercontent.com/assets/5489469/15960539/38afd0c4-2ef8-11e6-98cf-f05b60f96493.png">

The native Photos app shows the correct dates:

<img width="466" alt="screen shot 2016-06-10 at 10 44 24" src="https://cloud.githubusercontent.com/assets/5489469/15960570/5b6af0bc-2ef8-11e6-80e2-445eeab6fc01.png">

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by ide** [comment]
Probably off by a factor of 1000 (Obj-C sec vs JS msec).

**Comment by npomfret** [comment]
Think its a regression though - sure it used to work.

**Comment by npomfret** [comment]
It's broken on android

**Comment by lacker** [comment]
Is this still broken? This is the sort of thing it would be great to get a fix + unit test for - until we have better test coverage random stuff like this will break too frequently.

**Comment by npomfret** [comment]
It's still happening but I'm not 100% sure it's a bug, maybe an intentional change in behaviour. If you multiply the values by 1000 you can convert to a date, so the API is returning seconds since the epoch rather than millis (as it used to).

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
