### ISSUE TITLE
Text input doesn't unblurring when hide keyboard on Android

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#8062]
When i hide keyboard textinput doesn't unblurred and after i cant type text on textinput.

**Comment by Timson020** [comment]
you can use the scrollview 
ex:
<scrollview>
<textinput style={{width:100,height:30}}/>
<textinput style={{width:100,height:30}}/>
</scrollview>

**Comment by guyca** [comment]
I'm also facing this issue. I have a basic `<TextInput />` element

1. click `TextInput` -> soft keyboard is displayed
2. dismiss keyboard with back button (Keyboard is now hidden and TextInput is stil focused)
3. clicking on TextInput again doesn't bring up the soft keyboard
