### ISSUE TITLE
Running development server on non-standard port (one other than 8081) causes remote debugging connection launch failure. 

### ISSUE THREAD

**Issue by joshyhargreaves** [facebook/react-native#8068]
**version**: RN 0.27.2
**platforms present**: only occurs on IOS as far as I'm aware. 
**development platform**: OSX (mac). 

As McAfee antivirus runs on port 8081, I have been using another port for development purposes. 

I have found that all debug features function with no issue when running the development server on a port other than 8081, however there is a failure to launch remote debugging when using said alternate port. 

**obviously we can specify an alternate port as follows**

```
NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:7999/index.ios.bundle?platform=ios"];

"start": "node node_modules/react-native/local-cli/cli.js start --port 7999"
```

**this is the error when launching remote debugging on 7999**
<img width="1075" alt="screen shot 2016-06-12 at 12 45 33 am" src="https://cloud.githubusercontent.com/assets/1807207/15987990/76378e24-3037-11e6-976a-1cd34631c81a.png">

When running on port 8081 tapping 'enable remote debugging' from the debug menu opens a new tab in chrome and debugging connects as expected, however when not on port 8081, no tab in chrome is opened. You may even load the debug window yourself at http://localhost:7999/debugger-ui (for example) but the IOS simulator fails to connect.

**Comment by teiketu** [comment]
I run into the same issue. I start the packager with command `react-native start --port 8080` to avoid conflict with McAfee port 8081. "Live Reload" and "Hot Reloading" are working well. But when I tap the "Remote JS Debugging", chrome open a new tab and in console window I get error as "http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=true&minify=false 403 (Forbidden)"

**Comment by bbodenmiller** [comment]
I'm also having the same issue on Windows.

**Comment by zjaml** [comment]
I'm having the same issue. Mcafee is using 8081 port so I have to use another port for remote debugging, which seems unsupported now.

**Comment by DevCappe** [comment]
I'm having the same issue on Windows.

**Comment by aksappy** [comment]
Is there a way to fix this?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/running-development-server-on-non-standard-port-one-other-than-8081-causes-remot
