### ISSUE TITLE
[0.25+] touch event in an updated listview item is triggered only after second touch

### ISSUE THREAD

**Issue by badaz** [facebook/react-native#8075]
Since 0.25, when you replace a Component containing a Touchable inside a ListView, the Touchable won't receive the next touch event but only the one after that.

Here is a sample code to illustrate the bug: https://rnplay.org/apps/O3pGEA

WARNING ! This won't work in rnplay since it runs on 0.24.1 (not on 0.25)
but you can copy the code inside a 0.25, 0.26 or 0.27 react-native app to see the bug.

Try to long press any of the Touchable items (yellow buttons) which will make it turn into antoher Touchable component (red button), then try to touch it again, it will trigger the parent's touch event instead, then the next time you touch it it will trigger its event normally.

```
'use strict';

import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  Alert,
  TouchableOpacity,
  TouchableWithoutFeedback,
} from 'react-native';

var SampleApp = React.createClass({
  getInitialState: function() {
    return {rowChanged: null};
  },

  getDataSource: function() {
    const dataSource = new ListView.DataSource({
      rowHasChanged: (row1, row2) => !is(row1, row2),
    });

    const items = [1, 2, 3, 4, 5, 6];

    return dataSource.cloneWithRows(items);
  },
  
  onPressItem: function(item) {
    Alert.alert(
      'List item touched',
      'List item #' + item,
      [
        {text: 'OK', onPress: () => this.setState({rowChanged: null})},
      ]
    );
  },
    
  onPressBackground: function() {
    Alert.alert(
      'Background touched',
      'Background touched',
      [
        {text: 'OK'},
      ]
    );
  },
  
  renderRow: function(rowData) {
    return (
      <View style={styles.container}>
        {this.state.rowChanged !== rowData && 
          <TouchableOpacity style={{padding: 10, backgroundColor: 'yellow', margin: 10, borderRadius: 5}}
            onPress={() => this.onPressItem(rowData)}
            onLongPress={() => this.setState({rowChanged: rowData})}
          >
            <Text>rowData</Text>
          </TouchableOpacity>
        }
        {this.state.rowChanged === rowData &&
          <TouchableOpacity style={{padding: 10, backgroundColor: 'red', margin: 10, borderRadius: 5}}
            onPress={() => this.onPressItem(rowData)}
            onLongPress={() => this.setState({rowChanged: null})}
          >
            <Text>rowData</Text>
          </TouchableOpacity>
        }
      </View>
    );
  },
  
  render: function() {
    const dataSource = this.getDataSource();
    return (
      <TouchableWithoutFeedback onPress={this.onPressBackground}>
        <View style={styles.container}>
          <ListView contentContainerStyle={[styles.container, {justifyContent:"center", alignItems:"center"}]}
            dataSource={dataSource}
            renderRow={(rowData) => this.renderRow(rowData)}
          />
        </View>
      </TouchableWithoutFeedback>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 28,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    fontSize: 19,
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by phil-allcock** [comment]
I am getting the same issue, but with a ScrollView instead of a ListView.

**Comment by badaz** [comment]
Must be a problem with the scrollview part of the list view then

**Comment by phil-allcock** [comment]
Just as an additional note. With my issue you will log in with an account and then get a scroll list of items. If I enter my log in details through the on screen keyboard, I am unable to interact with the items within the scroll list. However, if I set my code to log in without the need to use the keyboard, then the items work as expected.

**Comment by badaz** [comment]
I believe yours is another pb which has been addressed here : https://github.com/facebook/react-native/issues/4087

**Comment by miserylee** [comment]
I think I got the same issue.
When I press a component and not release, in the duration the component did unmount, then in the new page the first press cannot work.

here is my sample code and my RN version is 0.27.2.

```
import React, {Component} from 'react';
import {
  AppRegistry,
  Navigator,
  View,
  Text,
  TouchableOpacity,
  StyleSheet
} from 'react-native';

class ComponentA extends Component {

  handleLongPress () {
    this.props.navigator.replace({component: ComponentB});
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onLongPress={this.handleLongPress.bind(this)}>
          <Text style={styles.text}>I'm componentA, LongPress me!!</Text>
        </TouchableOpacity>
      </View>
    );

  }
}

class ComponentB extends Component {

  handlePress () {
    this.props.navigator.replace({component: ComponentA});
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.handlePress.bind(this)}>
          <Text style={styles.text}>I'm componentB, Press me!!</Text>
        </TouchableOpacity>
      </View>
    );

  }
}

class APP extends Component {

  render() {
    return (
      <Navigator
        initialRoute={{component: ComponentA}}
        renderScene={(route, navigator) => {
          return <route.component navigator={navigator} />;
        }}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  text: {
    fontSize: 50
  }
});

AppRegistry.registerComponent('APP', () => APP);
```

**Comment by badaz** [comment]
My pb disappeared with 0.28 but I had a new one instead : longpressing a Touchable Opacity in a list view sometimes left the component with incomplete opacity after release. I managed to solve this problem by simplifying my component : instead of unmounting it to replace it with another one on long press I just modified its style. Anyway I don't know if it will help you since it had nothing to do with navigator to start with.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/025-touch-event-in-an-updated-listview-item-is-triggered-only-after-second-touch

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by manggit** [comment]
Just ran into this issue too, is there a work around?

**Comment by maggialejandro** [comment]
Same issue here
I'm opening a modal with a TextInput and a ListView, after I start typing I need to press twice over a list's Item, first to hide the keyboard then to trigger the Item's event handler

**Comment by maggialejandro** [comment]
Same issue here
I'm opening a Modal with a TextInput and a ListView, after I start typing I need to press twice over a list's Item, first to hide the keyboard then to trigger the Item's event handler

**Comment by core433** [comment]
Also ran into this issue... as a workaround calling this.forceUpdate() seems to work.
