### ISSUE TITLE
How to set up the position of the RefreshControl

### ISSUE THREAD

**Issue by zhongjie-chen** [facebook/react-native#8079]
```javascript
refreshControl={
                <RefreshControl
                  refreshing={this.state.isRefreshing}
                  //onRefresh={this._onRefresh.bind(this)}
                  style={{top: 200}}
                  colors={['#ff0000', '#00ff00', '#0000ff','#3ad564']}
                  progressBackgroundColor="#ffffff"/>}
```

**Comment by janicduplessis** [comment]
You can use `progressViewOffset` on android

**Comment by janicduplessis** [comment]
I'll close this for now feel free to reopen if it wasn't what you were looking for.

**Comment by zhongjie-chen** [comment]
```javascript
contentContainerStyle={{paddingTop: 50}}
          refreshControl={
              <RefreshControl
                refreshing={this.state.isRefreshing}
                //onRefresh={this._onRefresh.bind(this)}
                progressViewOffset ={50}
                colors={['#ff0000', '#00ff00', '#0000ff','#3ad564']}
                progressBackgroundColor="#ffffff"/>}
```
contentContainerStyle={{paddingTop: 50}} progressViewOffset ={50} 
It is not working

**Comment by jrs-onforce** [comment]
@zhongjie-chen could you re-open this?

progressViewOffset works when pulling to refresh, but when the 'refreshing' property is set to true when the component mounts, the offset does not seem to be recognized and it draws at the very top.  From there, again, when pulling to refresh, progressViewOffset is respected.

**Comment by janicduplessis** [comment]
@jrs-onforce You can open a new issue as this seems like a bug.
