### ISSUE TITLE
Could not connect to development server. Ensure that the packager server is running

### ISSUE THREAD

**Issue by wangxinarhat** [facebook/react-native#8086]
I run the AwesomeProject on linux and run the android simulator, an error occurs:

![screenshot from 2016-06-13 15-21-44](https://cloud.githubusercontent.com/assets/14964925/15999900/57b69ca6-310e-11e6-8dca-b329aa3edd01.png)

why the packager server is not started automatically?

**Comment by 281330** [comment]
make sure that in your project root, you do `react-native start` to start the packager.

**Comment by wangxinarhat** [comment]
@281330 it works, thanks
