### ISSUE TITLE
`componentWillMount` not be called after rootView.appProperties update.

### ISSUE THREAD

**Issue by lizouzt** [facebook/react-native#8087]
I tried this demo on [DOC](http://facebook.github.io/react-native/releases/0.26/docs/communication-ios.html#properties).
And figure out not  `componentWillMount` but `componentDidUpdate` will be called after appProperties update.
Is that right way to use?

Obj-C:
```
- (void)actionTimer:(NSTimer *)timer
{
  __weak typeof(self)weakSelf = self;
  
  self.number++;
  NSString *ppp = @"9999999999999999999999";
    
  NSString *itemId = [NSString stringWithFormat:@"%@%d",ppp,self.number];
  NSString *token = @"db120e74e3596aa7704ed9a6c4e84816";
  NSDictionary *queryProps = @{@"itemId": itemId, @"accessToken": token};

  ((RCTRootView *)weakSelf.window.rootViewController.view).appProperties = queryProps;
    
  NSLog(@"I'm timer:: %d", weakSelf.number); 
}
```
JS:
```
 componentDidUpdate () {
        console.log("**********************");
        console.log(this.props.itemId);
        console.log("**********************");
    }

    componentWillMount () {
        //TODO::rootView
        console.log("**********************");
        console.log(this.props.itemId);
        console.log("**********************");
    }
```

**Comment by gre** [comment]
I guess you should give initial props like this instead:

in your AppDelegate.m


```objc
  NSMutableDictionary *props =
  @{
    @"foo": 42
     ...
  }.mutableCopy;
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:...
                                               initialProperties:props
                                                   launchOptions:launchOptions];
```

**Comment by lizouzt** [comment]
Have look this section please.  @gre 

RCTRootView also provides a read-write property appProperties. After appProperties is set, the React Native app is re-rendered with new properties. The update is only performed when the new updated properties differ from the previous ones.

```
NSArray *imageList = @[@"http://foo.com/bar3.png",
                       @"http://foo.com/bar4.png"];

rootView.appProperties = @{@"images" : imageList};
```

It is fine to update properties anytime. However, updates have to be performed on the main thread. You use the getter on any thread.

There is no way to update only a few properties at a time. We suggest that you build it into your own wrapper instead.

> Currently, JS functions componentWillReceiveProps and componentWillUpdateProps of the top level RN component will not be called after a prop update. However, you can access the new props in componentWillMount function.

**Comment by javache** [comment]
I believe you won't get these callbacks because the component is already. Instead `componentWillUpdate` and `componentDidUpdate` will be called on your component.

**Comment by lizouzt** [comment]
Damn right.And the doc it wrong.So make it correct.
