### ISSUE TITLE
PanResponder is not working when there are multiple touches  

### ISSUE THREAD

**Issue by faisalil** [facebook/react-native#8094]
Hey, 

I am trying to implement a pinch gesture and I am trying to use PanResponder for that. However, looks like there is a bug, when I have a single touch, I get all events (start, move, end) and it working well. However, when I do a 2 figures, i only get a start event a directly after a terminated event. Any pointers to what might be going wrong? 

Faisal

**Comment by allthetime** [comment]
I've implemented zooming with PanResponder without issue. 

The supplied argument `gestureState` is relatively useless for this case as it doesn't return useful data (except for the number of touches)

You have to use `evt.touchHistory.touchBank` which is an array of all the touches.

I'll just show you the shell of my PanResponder creator (removed all specifics)
```
this._panResponder = PanResponder.create({
  onStartShouldSetPanResponder: (evt, gestureState) => true,
  onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
  onMoveShouldSetPanResponder: (evt, gestureState) => true,
  onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

  onPanResponderGrant: (evt, gestureState) => {
 // do stuff on start
  },
  onPanResponderMove: (evt, gestureState) => {
 // do stuff on move
//
//   THIS IS WHERE YOU USE evt.touchHistory.touchBank
//
  },
  onPanResponderTerminationRequest: (evt, gestureState) => true,
  onPanResponderRelease: (evt, gestureState) => {
  },
  onPanResponderTerminate: (evt, gestureState) => {
  },
  onShouldBlockNativeResponder: (evt, gestureState) => {
    return true;
  },
});

```

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by slorber** [comment]
@allthetime what's the difference between `touchBank` and `evt.nativeEvent.touches` ?

Also, for me it's not working very well because when I put a 2nd finger on the element, no more `onPanResponderMove` event is triggered unfortunatly. Any idea?

I'm trying to implement solution of https://stackoverflow.com/a/37449923/82609

**Comment by MiLeung** [comment]
Seems like touches and multiple touches can only act on one element. I have two elements and each should have their own PanResponder, but when I have multiple touches, only the first onPanResponderMove gets called.

**Comment by uditalias** [comment]
@faisalil is your PanResponder inside a <Modal /> ?
