### ISSUE TITLE
[Android] Use the JavaScript Engine of React Native to execute JavaScript code

### ISSUE THREAD

**Issue by rocman** [facebook/react-native#8096]
Since React Native introduce a JavaScript Engine to the project, theoretically, we can use it to execute the JavaScript code other than those for React Native Components. However, the API to do this is buried deep inside. I guess it's possible to provide it public, and so we will be saved from introducing another JavaScript Engine and making the APK larger.

**Comment by geirman** [comment]
Pull requests are welcome. In case you're not up for sending a PR, you should post to [Product Pains](https://productpains.com/product/react-native/?tab=top). It has a voting system and if the feature gets upvoted enough it might get implemented.

**Comment by geirman** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-1** [comment]
Hey @rocman! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
