### ISSUE TITLE
[Android]timestamp in gesture event different from iOS

### ISSUE THREAD

**Issue by ldn0x7dc** [facebook/react-native#8104]
Two problems:
1. Android is using 'timeStamp' while iOS is using 'timestamp'; (Seems an [old issue](https://github.com/facebook/react-native/issues/4046))
2. Android is using nano seconds while iOS is using milliseconds.(Brought in by [this commit](https://github.com/facebook/react-native/commit/f2c1868b56bdfc8b0d6f448733848eafed2cd440))

Those problems force us to check the platform when using the **timestamp**, which could be avoided.

**Comment by satya164** [comment]
It would be awesome if you can send a PR by changing both to `timeStamp` and fix android to use milliseconds.

**Comment by christopherdro** [comment]
Related #4627

**Comment by 0rland0** [comment]
The timestamp accuracy will be fixed with this pull request https://github.com/facebook/react-native/pull/8199
Is anyone working on renaming 'timestamp' to  'timeStamp' in iOS already?

**Comment by satya164** [comment]
@0rland0 There was a PR, but I don't think it's active. Send a new PR please :)

**Comment by 0rland0** [comment]
Ok I will try to do that.
@ldn0x7dc Would it be possible to upload the code where you used the gesture so I can directly test on that?

**Comment by 0rland0** [comment]
Does this issue really still exist? I just tried it out with the [PanResponderExample](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/PanResponderExample.js) which uses touch events. On Android AND iOS I could access the timestamp of the touch event with
`e.timeStamp`. Calling `e.timestamp` gave me on both platforms an 'undefined'.
I tested it with setting a breakpoint in different methods in the PanResponderExample e.g. in th _handlePanResponderMove method.

**Comment by ldn0x7dc** [comment]
@0rland0 
I've just tested with RN 0.28 and on android it's 'timeStamp' while on iOS it's 'timestamp'. 
You can check file [TouchesHelper](https://github.com/facebook/react-native/blob/f2c1868b56bdfc8b0d6f448733848eafed2cd440/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/TouchesHelper.java), which assign 'timeStamp' to TIMESTAMP_KEY

**Comment by sharnik** [comment]
The naming on Android has been changed to timestamp (iOS style) in this commit: https://github.com/facebook/react-native/commit/8aeeb4d6a06e4c3cb3e480bbad3f55f83b78a626

It's already on master.
