### ISSUE TITLE
Question: MapView region delta units

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#8110]
When setting a region for a MapView the docs say to pass in `{latitude: number, longitude: number, latitudeDelta: number, longitudeDelta: number}`.  What are the units of measurement for `latitudeDelta` and `longitudeDelta`?

Similarly, what is the unit of the `accuracy` value in the gps coordinate?

**Comment by tpisto** [comment]
Hi! Here is awesome article about MapView and its relation to Mercator Zoom levels (like google mapa zoom levels). Article has nice picture explaining lat and lng deltas.

http://troybrant.net/blog/wp-content/uploads/2010/01/15-lat-lng-corners-zoom-201.png

**Comment by npomfret** [comment]
Many thanks!
