### ISSUE TITLE
"ImagePipelineFactory was not initialized" error when launching UIExplorer example

### ISSUE THREAD

**Issue by qdk0901** [facebook/react-native#8114]
Hi,
  Just clone the source and compile following the Getting Started guide, and launch the UIExplorer example, then encounter the "ImagePipelineFactory was not initialized". Here is the screenshot: 

![image](https://cloud.githubusercontent.com/assets/1351536/16067936/ea6c8344-32f3-11e6-9f2f-b4399ea35e8c.png)

**Comment by r4ccoon** [comment]
Hi, I ve got the same thing,
What I did was, I closed the app (kill it from task manager). 
Make sure the packager runs, and reopen the app. 
I saw the same error screen, but clicking "RELOAD" button would make it disappear.

**Comment by chamchamgo** [comment]
#8398

**Comment by leeight** [comment]
https://github.com/facebook/react-native/pull/8398
