### ISSUE TITLE
'fetch' failed [version: 0.28.0-rc.0]

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#8118]
Using 'fetch' to send request, it failed. Error message is 'Network request failed'. My code works well with '0.27'

**Comment by nihgwu** [comment]
I'm using RN0.28 and it works fine, both POST and GET method, so perhaps u missed something

**Comment by 12d** [comment]
Could you show me your code? My project was upgrade from "0.24''

**Comment by 12d** [comment]
'Image' can not send request too, it runs into "onLoadEnd"

**Comment by 12d** [comment]
'Image' can not display, here is my code: `<Image source={{height:200,width:300,uri: 'http://facebook.github.io/origami/public/images/blog-hero.jpg'}}/>`

**Comment by 12d** [comment]
I have resolved it by adding 'Allow Arbitrary Loads' 
![resolve](https://cloud.githubusercontent.com/assets/1748202/16109900/bcdbad02-33dd-11e6-83ce-e3dfa169c592.jpg)

**Comment by charpeni** [comment]
I'll close this issue as it has been resolved with _Allow Arbitrary Loads_, if not feel free to let me know.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-1** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by CaleyD** [comment]
If this is the solution then shouldn't `react-native init` and `react-native upgrade` be updated to set this flag?

**Comment by cubbuk** [comment]
I am getting this error while uploading video file, I can upload a video upto-3-4 seconds, but when I try it something longer I get this error. Any idea?

**Comment by artokun** [comment]
In case anyone is wondering where you add Allow arbitrary loads:
<img width="1139" alt="screen shot 2016-07-21 at 8 07 44 pm" src="https://cloud.githubusercontent.com/assets/7666455/17045536/eda7e538-4f7e-11e6-903c-a243257306e8.png">

Go down to `App Transport Security Settings` > hit the `+` button > select `Allow Arbitrary Loads ` > change the bool value to `YES`

**Comment by cooperka** [comment]
Keep in mind this might be a security risk for you and your users to allow non-secure connections... https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/

**Comment by proactive-solutions** [comment]
Still getting the issue with RN version 0.45

Jun 27 16:23:36 Administrators-Mac-mini Experiments[38809] <Notice>: { [TypeError: Network request failed]
	  line: 15459,
	  column: 29,
	  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }

![screen shot 2017-06-27 at 4 24 03 pm](https://user-images.githubusercontent.com/13619716/27584332-391a2ae8-5b55-11e7-8e17-a9c98bf5d63c.png)

**Comment by hazeeb** [comment]
Still having this issue even after adding 'Allow Arbitrary Loads', exception domains.
`react-native: 0.50.4`

**Comment by GopiKrishna10** [comment]
@hazeeb Have you solved the issue.

**Comment by hazeeb** [comment]
@GopiKrishna10 Not yet. :(

**Comment by CSMarco** [comment]
Also having the issue, but only in debug build on iOS. That problem doesn't occur on a release build for me.

**Comment by ThomasAriano** [comment]
Still having this issue, have followed all suggested steps.
