### ISSUE TITLE
Error updating to 0.27.2: "Unable to resolve module ReactNative from Users/.../node_modules/react-native/Libraries/react-native/react-native.js"

### ISSUE THREAD

**Issue by weiyisheng** [facebook/react-native#8125]
here is the error, i have done all the tips, but not fix it , some get this :
<img width="372" alt="screen shot 2016-06-15 at 8 13 25 pm" src="https://cloud.githubusercontent.com/assets/8224651/16079376/cf76f8ca-3335-11e6-9cbf-d25aa32076b9.png">

**Comment by Ehesp** [comment]
Which version of React do you have installed (not React Native)?

**Comment by weiyisheng** [comment]
@Ehesp  thanks for reply, i just resolved this by update the React to 15.0.1, my old React version is 0.14.2(which cause this error)
