### ISSUE TITLE
TransformStyle is missing.

### ISSUE THREAD

**Issue by deepsyx** [facebook/react-native#8135]
I've been researching in the past 3 hours and couldn't find any solution to this, but transformStyle is missing from style. I would like to implement https://davidwalsh.name/demo/css-cube.php the following animations, but can't do it without `transform-style: preserve-3d`. 

Any ideas are greatly appreciated.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-1** [comment]
Hey @deepsyx! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
