### ISSUE TITLE
Simplify and make platform-specific code doc prescriptive

### ISSUE THREAD

**Issue by caabernathy** [facebook/react-native#8157]
Reference: http://facebook.github.io/react-native/docs/platform-specific-code.html

This doc can be simplified and made prescription by discussing the two options around handling Platform-specific code. We could also through in some design considerations, ex: Navigator use.

**Comment by lacker** [comment]
I think this is better than it was in the first place, so I'm going to close this issue. Pull requests welcome too ;-)
