### ISSUE TITLE
Create a new Layout doc

### ISSUE THREAD

**Issue by caabernathy** [facebook/react-native#8163]
Revamp Flexbox documentation. Including runnable examples would be ideal.

**Comment by mkonicek** [comment]
For inspiration, some resource people often use:
- https://css-tricks.com/snippets/css/a-guide-to-flexbox
- http://flexboxfroggy.com

**Comment by jondot** [comment]
@mkonicek also, check out this https://github.com/facebook/react-native/issues/8227 :)
