### ISSUE TITLE
Debugging - enhance existing doc

### ISSUE THREAD

**Issue by caabernathy** [facebook/react-native#8164]
Reference: http://facebook.github.io/react-native/docs/debugging.html

This document could use some improvement. It feels quite dense and complex. Things to consider:

- Adding info on how to see console.log statements in iOS
- Removing the custom JavaScript debugger support content

**Comment by hramos** [comment]
In #8010 I cleaned up the custom debugger section, and added more information on accessing logs in Xcode. @caabernathy do you think that PR resolves this issue or could the doc be improved more?

**Comment by hramos** [comment]
See #8323
