### ISSUE TITLE
Push latest tag to CocoaPods

### ISSUE THREAD

**Issue by tptee** [facebook/react-native#817]
Looks like 0.2.1 is the latest version uploaded to CocoaPods. Can someone with access push the latest tag?

**Comment by hojberg** [comment]
+1

**Comment by JAvery** [comment]
+1

Current podspec is at 0.3.1 but latest version in the Specs is 0.2.1

**Comment by vjeux** [comment]
cc @a2

**Comment by cxfeng1** [comment]
+1

**Comment by paramaggarwal** [comment]
+1

**Comment by JAvery** [comment]
FYI, Looks like it has been updated.

[CocoaPods' React Spec](https://github.com/CocoaPods/Specs/tree/6290b6ff8c00ec6dadeefe617b1b92019aa4d29a/Specs/React)

**Comment by tptee** [comment]
Beautiful. Closing!
