### ISSUE TITLE
[iOS][RN v0.26.3] StatusBar barStyle light-content not working

### ISSUE THREAD

**Issue by Proyoyo** [facebook/react-native#8171]
Hi there,
I tried to change the colour of icons in status bar to be white. I used barStyle = "light-content" props. However, it only works when I first introduced the code. Subsequent render/app refresh will change it back to default for some reason. Here's a screenshot of my code:

![screen shot 2016-06-17 at 10 20 35 am](https://cloud.githubusercontent.com/assets/11515661/16137325/6824c3dc-3475-11e6-9c84-1865ea3e0f50.png)

**Comment by rogchap** [comment]
In your `Info.plist` have you made sure that `UIViewControllerBasedStatusBarAppearance` is set to `NO`

I had a similar issue, but the `UIViewControllerBasedStatusBarAppearance` **was** set to `NO`, but for some weird reason was type `String` and not `Boolean`; making sure this Key is a `Boolean` solved my issue.

**Comment by seb-bizeul** [comment]
Same here on RN 0.37

**Comment by ptomasroos** [comment]
I'm using as @rogchap said.
```
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
```

Works fine with light-content

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/iosrn-v0263-statusbar-barstyle-light-content-not-working

**Comment by Proyoyo** [comment]
@rogchap @ptomasroos 
I'm still encountering this issue. I've made sure that UIViewControllerBasedStatusBarAppearance is set to false in info.plist and that the type is Boolean.
