### ISSUE TITLE
Issue on loading component with TabBarIOS from Navigator

### ISSUE THREAD

**Issue by jojonarte** [facebook/react-native#8173]
I've been trying to load up a component through RenderScene function under Navigator. If the route doesn't contain any corresponding object based on the route.object I would fire up the navigator to return the view with the tabBarIOS, the code on the second snippet is how the TabView looks.

`  renderScene: function(route, navigator) {
          if(route.login) {
            return (
              <LoginScreen
                navigator={navigator}
                onLogin={route.callback}
                />
            );
          }

            return (
                <HomeTab navigator={navigator}/>
            );
          
      }
`

The component with the tabs and supposedly the homepage after logging in is this 

`    import React, { Component } from 'react';
    import {
      AppRegistry,
      TabBarIOS,
      StyleSheet
    } from 'react-native';

    var Welcome = require('./welcome.ios');
    var More = require('./more.ios');

    export default class TabBarIOSSpike extends Component {
      constructor(props) {
          super(props);
          this.state = {
            selectedTab: 'welcome'
          };
        }

      render() {
        return (
          <TabBarIOS selectedTab={this.state.selectedTab}>
            <TabBarIOS.Item
              selected={this.state.selectedTab === 'welcome'}
              icon={{uri:'featured'}}
              onPress={() => {
                  this.setState({
                      selectedTab: 'welcome',
                  });
              }}>
                <Welcome/>
            </TabBarIOS.Item>
            <TabBarIOS.Item
              selected={this.state.selectedTab === 'more'}
              icon={{uri:'contacts'}}
              onPress={() => {
                    this.setState({
                        selectedTab: 'more',
                    });
              }}>
              <More/>
            </TabBarIOS.Item>
          </TabBarIOS>
        );
      }
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF',
      },
      welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10,
      },
      instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5,
      },
    });
`

I've been getting the weird error below. By the way, I've tested loading the hometab as the homepage and it works fine, only in this case if its wired up from the navigator that it occurs.

    Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Navigator`.

**Comment by grabbou** [comment]
Hey, we use Github for issues only and all questions should be asked on StackOverflow. Please consider posting your question up there providing more details on what specifically you'd like to achieve! 

This is for us to keep the number of issues smaller so that we can iterate on React Native versions faster and provide you with the better developer experience. 

If you have any ideas on how we could improve the entire process, please share your thoughts on [React Native Community](https://www.facebook.com/groups/react.native.community/?ref=nf_target&fref=nf) group.
