### ISSUE TITLE
通过compile "com.facebook.react:react-native:0+"获取到的是react-native-0.20.1，为什么获取不到你们最新的版本（react-native DirectX）？

### ISSUE THREAD

**Issue by github-lisong** [facebook/react-native#8174]
1、通过compile "com.facebook.react:react-native:0+"获取到的是react-native-0.20.1，为什么获取不到你们最新的版本（react-native DirectX）？

**Comment by cpunion** [comment]
**react-native** only publish on npm, so you can reference newest library in **node_modules**, like this:

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}
```

And please ask question on StackOverflow.

**Comment by github-lisong** [comment]
@cpunion 
我的配置如下：
`buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}`

**Comment by cpunion** [comment]
I created a project and compile with below steps:
```
react-native init TestVer
cd TestVer/android
./gradlew assembleDebug
```

Then run `find . -iname "*.jar" | grep react-native`, the output is:
```
./app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.27.2/jars/classes.jar
./app/build/intermediates/exploded-aar/com.facebook.react/react-native/0.27.2/jars/libs/infer-annotations-1.5.jar
```

It's the newest react-native libraries.

You can generate a new project, and check what is different.

**Comment by MingLanCheng** [comment]
@cpunion I wonder weather you can speak Chinese or not. If you can, why do you answer the question in English.

**Comment by MingLanCheng** [comment]
@cpunion thanks for helping others any way, good job

**Comment by github-lisong** [comment]
@cpunion 
compile "com.facebook.react:react-native:0.27.2"

<img width="654" alt="2016-06-17 12 27 59" src="https://cloud.githubusercontent.com/assets/10386453/16141775/9d2f1110-3491-11e6-8d94-7e8b8e0727cd.png">

**Comment by github-lisong** [comment]
@cpunion  @MingLanCheng
create a react project:

``````
react-native init AwesomeProject
cd AwesomeProject
react-native run-android
``````

Log The following：
<img width="809" alt="2016-06-17 2 14 06" src="https://cloud.githubusercontent.com/assets/10386453/16142259/525f6df6-3496-11e6-92d3-417cd1d27fa6.png">

**Comment by MingLanCheng** [comment]
@github-lisong 
你设置了自己的包依赖库是吧，不是官方的这库。你的库地址
http://jcenter.bintray.com/com/facebook/react/react-native/
最新的版本就是给你下载的0.20.1，没有更新到官方最新的版本，所以你怎么下也都是这个版。
个人猜测原因在这里

**Comment by MingLanCheng** [comment]
你们两个的配置文件有点区别，他的搜索本身仓库在先，你的网络下载在先。
![qq 20160617154027](https://cloud.githubusercontent.com/assets/6308331/16143821/d847778c-34a1-11e6-993a-ea8759dec879.jpg)    ![qq 20160617154104](https://cloud.githubusercontent.com/assets/6308331/16143822/d870123c-34a1-11e6-8832-3d524942b7ed.jpg)
他的机子安装有官方最新版，而你的老去那个没有更新的地址下载老版。

以下是网上找到的更新本地RN的方法，希望有所帮助：

http://blog.csdn.net/wagnteng/article/details/50549869

建议修改配置文件如他那样，搜索本地仓库在前，更新本地版本。

**Comment by github-lisong** [comment]
@MingLanCheng
非常感谢你！

你提供的思路，我都尝试过。

http://blog.csdn.net/wagnteng/article/details/50549869这文章，我之前已看到过，并且按他的思路去做，然而，我还是没有更新到最新的库。

**Comment by nihgwu** [comment]
这种问题跑这来开 issue 合适吗？

**Comment by nihgwu** [comment]
If you think you have to create an issue to solve the problem, please try to describe it in English so that the others can help you and will help the others who come into the same problem
I've noticed that you also created another issue, beware that here is not QQ group or bbs, 
be helpful please, try to find answer on StackOverflow

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @github-lisong and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by github-lisong** [comment]
@nihgwu 
你好，我这这里提问题，碍着你嘛事了？合不合适，你算老几，我都懒得理你，FUCK！

**Comment by nihgwu** [comment]
@github-lisong shame of you

**Comment by nihgwu** [comment]
@charpeni so the `ISSUE_TEMPLATE` is useless for those guys 😂

**Comment by charpeni** [comment]
@nihgwu It sounds like. I don't understand his message, but I guessed by the last word that was not friendly at all.

**Comment by HangYang** [comment]
@github-lisong  shame on you.

**Comment by ucoker** [comment]
@github-lisong shame on you.You should read `ISSUE_TEMPLATE ` first.

**Comment by crayygy** [comment]
@github-lisong Shame on you.

**Comment by zjxuzhj** [comment]
@github-lisong Shame on you

**Comment by alivelee** [comment]
@github-lisong Shame on you

**Comment by xiahei** [comment]
@github-lisong  Shame on you.

**Comment by walkmansk** [comment]
@github-lisong Shame on you.

**Comment by ClassicOldSong** [comment]
@github-lisong Shame on you.

**Comment by q545244819** [comment]
@github-lisong Shame on you.

**Comment by septs** [comment]
@github-lisong Shame on you.

**Comment by harrot** [comment]
Shame on you.

**Comment by 2yuri** [comment]
@github-lisong Shame on you.

**Comment by qulc** [comment]
@github-lisong Shame on you.

**Comment by andyhuzhill** [comment]
@github-lisong  shame on you.

**Comment by pasturn** [comment]
@github-lisong Shame on you.

**Comment by pasturn** [comment]
@github-lisong Shame on you.

**Comment by pasturn** [comment]
@github-lisong Shame on you.

**Comment by pasturn** [comment]
@github-lisong Shame on you.

**Comment by pasturn** [comment]
@github-lisong Shame on you.

**Comment by Jaggle** [comment]
@github-lisong Shame on you .

**Comment by Edward-Shaw** [comment]
@github-lisong Shame on you.

**Comment by github-lisong** [comment]
@nihgwu @Edward-Shaw  @Jaggle @andyhuzhill  @2yuri @harrot @ClassicOldSong 你们都是些什么东西，我提个问题在这里，我得罪你们什么了，有疑问我在这里提有错？你们这帮喜欢装逼的货，我无语死了，只会欺负国人，也没见你们有什么大的能耐，还不是一天用着老外的东西，有能耐得用在刀刃上，呵呵。

**Comment by 2yuri** [comment]
@github-lisong 别张口骂人行吗，二逼。我一个一个问题回答你
1，你提个问题在这里，并没有得罪我们什么，就是觉得丢脸
2，有疑问在这里提本身并没有什么大错，但是谦虚谨慎一点不好吗？别人善意提醒你一下看一下issue template，你看你自己什么态度？
3，我们不喜欢装逼，不欺负国人，别为你自己的傻逼行为开脱行吗？
4，至于最后一句话，我都懒着跟你扯扯，还呵呵？我呵呵你一脸。

**Comment by cqm1994617** [comment]
卧槽，我怎么在github上玩出了百度贴吧的感觉？

**Comment by zhongjie-chen** [comment]
https://github.com/zhongjie-chen/rn_rank 来波福利

**Comment by on99** [comment]
Well.. Someone please lock the conversation.

**Comment by nihgwu** [comment]
@on99 agree with you, it shouldn't be spawned, and here is my last response
![image](https://cloud.githubusercontent.com/assets/2595058/16368246/9d43bf78-3c5e-11e6-9a78-0eb08345d44a.png)

**Comment by Jun321** [comment]
Shame on u too

**Comment by blade254353074** [comment]
@github-lisong shame on you

**Comment by Vhyn** [comment]
@cqm1994617 可惜github不能楼内回复，233

![滑稽](http://joymepic.joyme.com/article/uploads/allimg/201509/1441689490894369.jpg)
