### ISSUE TITLE
onResponderRelease not works on android devices

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#8177]
Exactly speaking, 
onResponderRelease is not triggered on Android if it nested with Text, but works well with IOS devices. Here is my quite simple code: 

```
render (){
        return (
            <Text>
            <Image onResponderRelease={()=>{alert(1)}} onStartShouldSetResponder={()=>true} source={{height: 100, width: 100, uri: 'http://dimg04.c-ctrip.com/images//u00l0400000000dq8C668.jpg'}}/>
            </Text>
        )
}
```

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by antoxi4** [comment]
Same issue on Lenovo Tab Only

**Comment by lacker** [comment]
I think we need more information - could you provide a project that reproduces this on rnplay.org? I am going to close this issue but please feel free to reopen if you do have that info.

**Comment by Piwaii** [comment]
Hi. Here is a little example of onResponderRelease working on IOS but not on Android. The alert is shown on the release event on IOS, but not on Android.
https://rnplay.org/apps/2rkKsA

**Comment by zachrnolan** [comment]
Having the same issue on RN 0.43.3.
