### ISSUE TITLE
Install release build error Android

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#8183]
After generate key and build release. i cant install it to device. When i try install app, jus keep error 'Parse error'
There was a problem parsing the package.

When i try install with console keep error 
Task 'installRelease' not found in root project 'RNApp'. Some candidates are: 'uninstallRelease'.

**Comment by idajimenez** [comment]
@antoxi4 did you manage to solve this? I am also encountering this error.

**Comment by liuhong1happy** [comment]
@antoxi4 I have same question! Why had you closed the issue?

**Comment by heracek** [comment]
This seems to be the answer: https://github.com/xinthink/rnmk-demo/issues/7#issuecomment-218613454
(you have to to setup a keystore + configure signing)

cc @liuhong1happy, @antoxi4
