### ISSUE TITLE
[JS] Add 'react-native log'

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8186]
Reading logs with React Native should be super easy, right now it's not. You have to:
- Run `adb logcat` on Android
- Use Xcode, Nuclide etc. on iOS. See http://stackoverflow.com/questions/30115372/how-to-do-logging-in-react-native

We should have a command 'react-native log' that prints logs for a running Android emulator / iOS simulator or connected device. For that we'll need to detect whether an Android or iOS simulator is running or a device connected (e.g. using `adb devices` or something similar on iOS). It seems reasonable to:
- Start simple and first add two separate commands: `react-native log-android`, `react-native log-ios`
- Later add `react-native log` that detects what kind of devices are connected and calls either `log-android` or `log-ios`.

The command should be implemented as part of the CLI. To get started, see https://github.com/facebook/react-native/blob/master/local-cli/cliEntry.js

**Comment by grabbou** [comment]
In terms of the command itself, I'd suggest this should be done as an `rnpm-plugin` so that we can merge it easily and it won't produce any conflicts with our PR?

**Comment by mkonicek** [comment]
`react-native log-ios` and `log-android` implemented in https://github.com/facebook/react-native/pull/8352  	🎉

**Comment by farwayer** [comment]
Nice! But what is about using command with several connected devices? Ideally it will be nice to have a possibility to specify device id for command. Something like `react-native log <IOS-OR-ANDROID-DEVICE-ID>` or simply `react-native log` if it is only one device connected.
