### ISSUE TITLE
[Android] Redbox, dev menu are shown behind <Modal>

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8187]
If you display a `<Modal>` and then log `console.warning`, the YellowBox is shown behind the Modal. It should always be shown on top of application UI.

Fixing this will likely need some Android experience and changes in Java code.
- Modal: https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/views/modal
- Redbox: https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/devsupport

**Comment by javache** [comment]
@frantic Didn't you fix this already?

**Comment by frantic** [comment]
No, I was working on elements inspector for modals and I didn't have enough time/experience to dive into Android windows ordering issue.

**Comment by lacker** [comment]
Fixed according to https://github.com/facebook/react-native/issues/8193
