### ISSUE TITLE
Error using LinkingIOS - undefined is not an object

### ISSUE THREAD

**Issue by danielkramer** [facebook/react-native#819]
I'm simply trying to open a url:

```
LinkingIOS.openURL("https://facebook.com/PlayUpwordsApp");
``` 

And getting:

```
message: undefined is not an object (evaluating 'RCTLinkingManager.openURL')"
```

I added RCTLinking.xcodeproj to my project and I'm still getting the same error.  Any thoughts?  I do notice the libRCTLinking.a file is red in Xcode.. does that mean it's not being built?  I did add that .a file to the "Linked Frameworks and Librarys" section of my project.

**Comment by dimoreira** [comment]
Not working for me either. +1

**Comment by rkstar** [comment]
seems like this should be done automatically when you do `let {LinkingIOS} = React`  no?

**Comment by nicklockwood** [comment]
`let {LinkingIOS} = React` only includes the JavaScript code, not the native code. We split the native code into distinct libraries to keep the binary size down for apps that aren't using all of the features, so you need to include all of the libraries that contain the native modules you want to use in your app.

**Comment by rkstar** [comment]
ok!  for anyone else who finds this... here is instructions: https://facebook.github.io/react-native/docs/linking-libraries.html

**Comment by cherniv** [comment]
@rkstar link to this doc has changed, now it is: [](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) . `LinkingIOS` needs Step 3
