### ISSUE TITLE
[Android] Add a Copy button in the redbox

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8192]
On iOS when you get a redbox (the red screen shown for JS or native errors) there's a Copy button which copies the error message and stack trace to the host (your laptop's) clipboard. This works when using a simulator, maybe also when using a device?

We should have this button on Android too. You'll need to test this on:
- Genymotion
- Google's emulator

If it's possible to copy the text to the host keyboard only on one of them, we should detect what type of device we're running on and only display the button when it's possible to copy the text.

Experience required: Android.

**Comment by donyu** [comment]
This was added in https://github.com/facebook/react-native/blob/7cf4e3665ac064b0a7c559656d8e2b32f727f486/ReactAndroid/src/main/java/com/facebook/react/devsupport/RedBoxDialog.java#L292-L304
