### ISSUE TITLE
Modal shouldn't cover the Element inspector

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8193]
When the Element inspector is shown and a `<Modal>` is rendered at the same time, the Modal covers the Element inspector. This shouldn't be the case :)

Experience required: JS.

**Comment by Ehesp** [comment]
The modal covers everything for me, can't even access the dev menu.

**Comment by frantic** [comment]
We've fixed this internally, should be a trivial fix in OSS. The idea is to wrap the content of the modal into `<AppContainer>` that provides all development level tools – inspector, yellow box, etc.

![image](https://cloud.githubusercontent.com/assets/192222/16158344/b4a8d4a4-3471-11e6-85e4-dbe158b049dd.png)

**Comment by mkonicek** [comment]
@frantic Oh cool, so the Modal effectively render the YellowBox and the children:
https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/AppContainer.js

**Comment by mkonicek** [comment]
> The modal covers everything for me, can't even access the dev menu.

I created a separate issue for this. The trick with `AppContainer` might not be enough for the dev menu being behind Modal might need changes in native (at least on Android): https://github.com/facebook/react-native/issues/8187

**Comment by mkonicek** [comment]
@frantic Can you explain this a bit more please? Did you mean `<Modal>` should render an `<AppContainer>` by default?

**Comment by BilalBudhani** [comment]
@frantic I'm looking into this issue as well. It would be great if you can explain a bit more.

**Comment by aakashsigdel** [comment]
@mkonicek as mentioned by @frantic, wrapping the contains of the modal in AppContainer does seem to solve the problem. Could you please tell me what is the status on this issue? Should I open a PR for this?

**Comment by satya164** [comment]
@aakashsigdel Yeah, would be cool if you can send a PR.

**Comment by aakashsigdel** [comment]
@satya164 I tried to include the master branch as dependency in my project, but it fails with `"Requiring unknown module "react/lib/ReactPropTypesSecret"`. 

I followed the guide from the docs: `Building React Native from source`
https://facebook.github.io/react-native/docs/android-building-from-source.html

Is there something I am missing?

**Comment by christopherdro** [comment]
Fixed via https://github.com/facebook/react-native/commit/05de4dbb94a4f09fd9a23a423e8328038d7b9c01
