### ISSUE TITLE
Add missing API / Component docs

### ISSUE THREAD

**Issue by caabernathy** [facebook/react-native#8202]
Reference: https://www.facebook.com/groups/reactnativeoss/permalink/1530162503947045/
See also: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js

We have some missing reference docs. Some on purpose, others need to be added.

First let's figure out what's missing then go from there.

**Comment by caabernathy** [comment]
@lacker, @JoelMarcey, @vjeux - curious on rehashing thoughts here. Options are:

1. Automatically show docs based on what's exported in code: https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js
2. Manually add the ones shown as is being done right now.

I prefer a version of (1) even if we end up documenting APIs, Components that are deprecated or experimental.

**Comment by vjeux** [comment]
1) works for me if you can implement it :)

**Comment by lacker** [comment]
I did #2 for the ones that work, but still some are missing: ART, Platform, Touchable, Keyboard in particular

**Comment by lacker** [comment]
We concluded it's nontrivial to add those extras, so I think this issue is no longer too helpful and we should just close it. Issues of the form "component X needs better docs" are still legit though.
