### ISSUE TITLE
Update existing API / Component docs

### ISSUE THREAD

**Issue by caabernathy** [facebook/react-native#8203]
Master issue for updating existing reference docs to conform to autogen updates.

These are the most visited Component and API docs:

**Components:**

- [x] 1. - View (**JM**)
- [ ] 2. - ListView (**JM**)
- [x] 3. - Navigator (**CA**)
- [x] 4. - TextInput (**JM**)
- [x] 5. - Image (**JM**)
- [x] 6. - Text (**JM**)
- [ ] 7. - ScrollView (**JM**)
- [ ] 8. - TouchableHighlight (**HR**)
- [ ] 9. - NavigatorIOS (**CA** ...)
- [x] 10. - WebView (**CA** )
- [ ] 11. - Modal (**EN**)
- [ ] 12. - TabBarIOS (**CA**)
- [x] 13. - MapView (**CA**...)
- [ ] 14. - TouchableOpacity (**HR**)
- [ ] 15. - Picker (**CA**)
- [ ] 16. - StatusBar (**CA**)
- [ ] 17. - ToolbarAndroid
- [ ] 18. - ActivityIndicatorIOS (**EN**)
- [ ] 19. - DrawerLayoutAndroid
- [ ] 20. - TouchableWithoutFeedback (**HR**)
- [ ] 21. - RefreshControl

**APIs:**

- [x] 1. - AsyncStorage (**CA**)
- [ ] 2. - Animated (**CA**)
- [ ] 3. - PushNotificationIOS
- [ ] 4. - Alert
- [ ] 5. - Linking
- [ ] 6. - CameraRoll
- [ ] 7. - ART (**EN**) 

Let's work through this list and update the docs to use jsdoc for APIs and make sure details are filled out for API and components. See the StatusBar and AlertIOS doc for examples of what the finished doc should contain. We're looking for the following:

- Good intro section with caveats listed
- A quick initial example strongly suggested
- Document all method description and parameters
- Document types
- Add prop descriptions

These docs can be broken out into individual issues (especially the bigger ones).

**Comment by lacker** [comment]
Since we were using this issue primarily to get organized around the docs lockdown I don't think it's needed any more
