### ISSUE TITLE
what happened?  the problem about react-native init  

### ISSUE THREAD

**Issue by yangqiang1223** [facebook/react-native#8206]
My enviroment like this
$nvm ls 
        v6.2.1
->       system
default -> system
node -> stable (-> v6.2.1) (default)
stable -> 6.2 (-> v6.2.1) (default)
iojs -> iojs- (-> system) (default)

when i use react-native init --verbose  to create a project 

    ├── user-home@2.0.0 
    ├── xdg-basedir@2.0.0 
    ├─┬ yeoman-assert@2.2.1 
    │ └── path-exists@2.1.0 
    └── yeoman-welcome@1.0.1 

npm WARN react-native@0.27.2 requires a peer of react@15.1.0 but none was installed.
npm verb exit [ 0, true ]
npm info ok 

then,it no response! 

I tried to install react@15.1.0 and then retry init 

the same problem

only has node_modules and package.json in MyProject

what happened

**Comment by 281330** [comment]
I can't reproduce that issue.  Maybe you need to install it globally?

**Comment by yangqiang1223** [comment]
Has Done!

**Comment by yangqiang1223** [comment]
I uninstalled the nodejs 6.2.2
and reinstall the 4.4.5 version 
init success...
