### ISSUE TITLE
jsCodeLocation choice

### ISSUE THREAD

**Issue by nkt** [facebook/react-native#821]
Why `jsCodeLocation` couldn't be defined by compiler, instead of programmer?
I've googled, XCode provide `DEBUG` macro, so we could do something like this:
```objc
#if DEBUG
  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];
#else
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
```
And also add compilation callback that would be update `main.jsbundle`.

**Comment by romanonthego** [comment]
it would also be extra nice to have *npm build* (or something like it) command provided by default.

**Comment by arthuralee** [comment]
@romanonthego I gave your idea a try at #851!

**Comment by romanonthego** [comment]
thx, will totaly look into it.
