### ISSUE TITLE
tabios binding listview or scrollview, switching times when, by chance listview or scrollview element can not click

### ISSUE THREAD

**Issue by oyhk** [facebook/react-native#8212]
TabBarIOS binding listview or scrollview, switching times when, by chance listview or scrollview element can not click

code:
 `<TabBarIOS tintColor={Colors.tab_bar} barTintColor={Colors.white}>
                <Icon.TabBarItemIOS
                    title="日程表"
                    iconName="arrange"
                    color={Colors.white}
                    selectedIconName="arrange"
                    selected={this.state.selectedTab === 'calendar-patient-appointment'}
                    onPress={() => {
                        this.setState({
                            selectedTab: 'calendar-patient-appointment',
                        });
                    }}>
                    <Scrollview.../>
                </Icon.TabBarItemIOS>
                <Icon.TabBarItemIOS
                    title="患者"
                    iconName="patient"
                    color={Colors.white}
                    selectedIconName="patient"
                    selected={this.state.selectedTab === 'patient'}
                    onPress={() => {
                        this.setState({
                            selectedTab: 'patient',
                        });
                    }}>
                    <ListView.../>
                </Icon.TabBarItemIOS>
</TabBarIOS>`

**Comment by KishPatel1996** [comment]
Bump, am having a similar issue to @oyhk

**Comment by sibelius** [comment]
@oyhk could u provider more information? and a better code snippet with indentation or a repo to reproduce this issue?

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
