### ISSUE TITLE
DatePickerIOS is not displayed properly in 4in screens

### ISSUE THREAD

**Issue by thevishnupradeep** [facebook/react-native#8222]
![simulator screen shot 19 jun 2016 09 55 11](https://cloud.githubusercontent.com/assets/5638461/16175611/c2c641c2-3604-11e6-9f47-20fd997c0b79.png)

The component works perfectly in iPhone 6 and 6 Plus. 

I don't know if this is something from my side. Posting the component code here as well:

`<View style={styles.Section}>
          <Text style={styles.FormTitle}>Deadline: {dateFormat(this.state.deadline, "ddd, mmm dS, h:MM TT")}</Text>
          <DatePickerIOS date={this.state.deadline} mode="datetime"
          onDateChange={(deadline) => { this.setState({ deadline }); }} />
        </View>`

**Comment by christopherdro** [comment]
What's defined in {styles.Section}?

**Comment by vishnupradeep93** [comment]
`Section: {
    backgroundColor: '#ffffff',
    borderRadius: 5,
    marginTop: 20,
    marginLeft: 5,
    marginRight: 5,
    padding: 10,
    shadowColor: "#DDDDDD",
    shadowOpacity: 1,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0
    }
  },`

**Comment by christopherdro** [comment]
Have you tried remove all margins and padding to test?

**Comment by vishnupradeep93** [comment]
Hi, Sorry for the late reply. Yes I've tried. Both from the component and the parent. That only partially solved the issue. It was still not properly in center.
