### ISSUE TITLE
Could not install the app on the device, read the error above for details.

### ISSUE THREAD

**Issue by trainerplus1** [facebook/react-native#8225]
I tried to run `react-native run-android` command on my command line and I got the result like the following.
```
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         file:/C:/Users/DELL/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/C:/Users/DELL/.m2/repository/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         AwesomeProject:app:unspecified
         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.27.2
   > Could not find com.android.support:recyclerview-v7:23.0.1.
     Searched in the following locations:
         file:/C:/Users/DELL/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         file:/C:/Users/DELL/.m2/repository/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
     Required by:
         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.27.2
   > Could not find com.android.support:support-v4:23.1.1.
     Searched in the following locations:
         file:/C:/Users/DELL/.m2/repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
         file:/C:/Users/DELL/.m2/repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/support-v4/23.1.1/support-v4-23.1.1.pom
         file:/F:/Android/react/AwesomeProject/node_modules/react-native/android/com/android/support/support-v4/23.1.1/support-v4-23.1.1.jar
     Required by:
         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.27.2 > com.facebook.fresco:fresco:0.10.0 > com.facebook.fresco:drawee:0.10.0
         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.27.2 > com.facebook.fresco:fresco:0.10.0 > com.facebook.fresco:imagepipeline:0.10.0
         AwesomeProject:app:unspecified > com.facebook.react:react-native:0.27.2 > com.facebook.fresco:fresco:0.10.0 > com.facebook.fresco:imagepipeline:0.10.0 > com.facebook.fresco:imagepipeline-base:0.10.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.502 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```
Please someone tell me why this happaning. I set everything clear. I mean the Android SDK, Java, Etc,Etc

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-7** [comment]
Hey @trainerplus1 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by trainerplus1** [comment]
@facebook-github-bot-7 I already asked the question there. But no one could answer this. Because of that I posted the question here as a issue.

**Comment by timzaak** [comment]
@trainerplus1 after update android sdk, I can run.

**Comment by xphaul** [comment]
i have this problem . i tried updating my sdk but still no luck . 

`A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.facebook.react:react-native:0.28.0.
     Searched in the following locations:
         file:/Users/paulgonzales/.m2/repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.pom
         file:/Users/paulgonzales/.m2/repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.jar
         https://jcenter.bintray.com/com/facebook/react/react-native/0.28.0/react-native-0.28.0.pom
         https://jcenter.bintray.com/com/facebook/react/react-native/0.28.0/react-native-0.28.0.jar
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.pom
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/android/m2repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.jar
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/google/m2repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.pom
         file:/usr/local/Cellar/android-sdk/24.4.1_1/extras/google/m2repository/com/facebook/react/react-native/0.28.0/react-native-0.28.0.jar
     Required by:
         Near:app:unspecified
`

**Comment by trainerplus1** [comment]
@xphaul I tried many ways to solve this problem but non of them worked for me. I done many things to avoid the problem by asking on StackOverflow.  No one have solution for this problem.

**Comment by xphaul** [comment]
@trainerplus1 well i think ill settle now on my older version of react-native . maybe someday someone can help us with this issue :(

**Comment by francoislaberge** [comment]
For future explorers, I ran into this problem too as of the latest release today. The way I got around it was by following the previous version of the Mac/Android installation documentation:
http://facebook.github.io/react-native/releases/0.28/docs/getting-started.html

**Comment by francoislaberge** [comment]
I had to do this trouble shooting step as well:
http://facebook.github.io/react-native/releases/0.28/docs/getting-started.html#virtual-device-not-created-when-installing-android-studio
