### ISSUE TITLE
 [fatal][tid:main] Unable to execute JS call: __fbBatchedBridge is undefined

### ISSUE THREAD

**Issue by hotarzhang** [facebook/react-native#8226]
It was working less than 2 weeks ago but now it's show " Unable to execute JS call: __fbBatchedBridge is undefined"

**Comment by christopherdro** [comment]
@hotarzhang Most likely an issue with trying to connect to the packager with Android.
If your trying to run on it on a device, make sure you run `adb reverse tcp:8081 tcp:8081`

**Comment by hotarzhang** [comment]
@christopherdro Thanks for getting back so quickly. But it's running with mac.setp is:
```
open MyReactNative.xcodeproj in Xcode
Product -> Run
```
and then  the same error happens when clicking Run.

**Comment by christopherdro** [comment]
@hotarzhang Are you trying to build with the simulator or an actual device?

**Comment by hotarzhang** [comment]
@christopherdro  Yes, trying to build with the simulator.

**Comment by hotarzhang** [comment]
Thanks, It's solved.

**Comment by drdpedroso** [comment]
@hotarzhang Can you post the solution, please?

**Comment by LFZJun** [comment]
@hotarzhang  Can you post the solution, please?

**Comment by jDeppen** [comment]
Switching iOS devices in the simulator was the fix for me

**Comment by Nualiian** [comment]
@jDeppen kind of a workaround, but resetting the simulator fixes it for me as well
