### ISSUE TITLE
How to embed a react view into a uiview?

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#823]
I wonder whether it is possible to embed a react-created-view into a view created by Objective-C,if it is possible, how to do it?Thank you.

**Comment by jaygarcia** [comment]
I imagine using a webview is the only way to do this.  You'd need to setup event and gesture handlers. 

JG



:: sent from my mobile device ::

**Comment by iostalk** [comment]
No, actually I don't want to use a webview.
React Native allows js to call native ui components, what I want to do is opposite, which depends the ability of native code embeding a component declared and written in jsx side.

**Comment by jaygarcia** [comment]
So you want to use JSX to write a custom component that is only configured by JSx and include it in your RN app?

I really want to help you, but Your initial question confused me. 


JG
 

:: sent from my mobile device ::

**Comment by iostalk** [comment]
Sorry, my initial question is such an asshole...
Exactly what I want to do is embed a defined-in-jsx view within the Objective-C code.The defined-in-jsx view's logics maybe is independent and it is just contained in a uiview.
I imagine this can help separate the frequently changed business from the permanent business, which is like webview do in the app store app.

**Comment by iostalk** [comment]
One word is how to embed a written-in-jsx-native-view into a written-in-objc-view?

**Comment by brentvatne** [comment]
@iostalk - https://facebook.github.io/react-native/docs/embedded-app.html#content

**Comment by iostalk** [comment]
That's good but ReactView seem be added as a rootview, could I add a reactview as a subview of an existed uiview

**Comment by brentvatne** [comment]
@iostalk - sure, I believe you can just make the react root view the subview of any view that you like

**Comment by iostalk** [comment]
Thank you very much

**Comment by iostalk** [comment]
Sorry I still have a question, the document just introduced how to embed a react view in a uiview, and if I want to call a react view controller in the Objective-C code, how to do it?

**Comment by tadeuzagallo** [comment]
You just use an `UIViewController` with a `RCTRootView` as it's view.

**Comment by iostalk** [comment]
OK, I see see...
