### ISSUE TITLE
Images reload every time View is rendered

### ISSUE THREAD

**Issue by zachgibson** [facebook/react-native#8231]
Should Images be re-rendering every time an iOS view is changed? 

Anytime you dismiss a native controller and come back to your app there's a bit of time where RN Images are not there because they are being loaded again. If you have a lot of Images in the View you're coming back to, the time of seeing no Images increases—note the TabBar icons in the first GIF.

**React Native App** (Images reload): 
![image-flickers](https://cloud.githubusercontent.com/assets/10658888/16179464/633ee182-362c-11e6-83ae-8ba5d325e72b.gif)

**Native iOS App** (Images seem to not reload): 
![image-doesnt-flicker](https://cloud.githubusercontent.com/assets/10658888/16179465/6a4232c2-362c-11e6-8098-536536959b0c.gif)

I tested this with TabBarIOS, logging Image onLoad, each time you switch tabs Images are loading again. Looking at some native apps it seems like once your images are loaded in a view each time you come back to that view the images don't re-render.

_I'm running React Native 0.27 on a Mac_. I've only seen this on iOS, not sure about Android.

Side note: The first screenshot (my app) is not using TabBarIOS, when using TabBarIOS the TabBar icons do not re-render when swiping back into the app from Safari View Controller.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label iOS

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label Perf

**Comment by 281330** [comment]
not sure, but maybe you can cache the image/data you're using in that bottom bar because that seems like data that shouldn't need to be reloaded right?

**Comment by samuelkraft** [comment]
Adding [defaultSource](https://facebook.github.io/react-native/docs/image.html#defaultsource) to local images seems to improve it for me.

**Comment by zachgibson** [comment]
@samuelkraft defaultSource fixes the local images problem. That commit seems to address this problem too. Thanks for the suggestions!
