### ISSUE TITLE
border color on a single side of a View with borderRadius not visible

### ISSUE THREAD

**Issue by kulmajaba** [facebook/react-native#8236]
On a View with borderRadius, setting border color (either for all sides or just one) and border width for only one side (e.g. borderLeftWidth) has no effect. Removing the borderRadius or using borderWidth instead of borderLeftWidth makes the border visible.

Using Windows and testing with Android emulator, React Native version 0.27.2

**Comment by jdeniau** [comment]
kind of the same thing here with borderStyle dashed + borderBottomWidth 1 : the border is not visible. 
Removing the style or make the width global display the border

**Comment by mdibaiee** [comment]
I have the same problem.

```javascript
{
  borderRadius: 999,
  borderTopWidth: 1,
  borderColor: 'white',
}
```

Actually it seems the border _is_ drawn, so if I set `borderTopWidth` to something like `10`, I can see the border, but the color is not applied, instead the default color is used.

**Comment by parkerdan** [comment]
`{
borderTopColor: 'pink',
borderTopWidth: 5,
}`
everything works with that style....add one line
`{
borderTopColor: 'pink',
borderTopWidth: 5,
borderTopRightRadius:5,
}`
and the radius shows, but the pink border is gone....  this is an Android problem only, iOS is great...I wish Android would go away

**Comment by razvan-tudosa** [comment]
I'm having the same issue. When I try to hide the left border without having border radius it works. When I put the border radius the left border is not hidden anymore. 
The issue reproduces only on Android, on iOS it works as it should.

Anyone has any idea what's going on?

**Comment by mattisx** [comment]
Still having this issue. Now having to release with a double width border thickness on one side of container.

**Comment by brentvatne** [comment]
Moving discussion to #11042 because the title is a more accurate description of the problem
