### ISSUE TITLE
PanResponder velocity return error values on Android.

### ISSUE THREAD

**Issue by PonyCui** [facebook/react-native#8238]
React-native version 0.27.0
relate to https://github.com/facebook/react-native/commit/f2c1868b56bdfc8b0d6f448733848eafed2cd440 this commit.
The touch event timestamp returns nanoseconds.
But PanResponder didn't update expectedly, it calculates velocity using millisecond yet.
It causes lots of issue, such as Navigator gesture not response as expectedly.

**Comment by wilsonpage** [comment]
I ran into this and had to roll back to `0.26`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/panresponder-velocity-return-error-values-on-android

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (71/60 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56487)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzswO-0004Wm-NH
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:14:29 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzswN-00015o-0H
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:14:28 -0700
Date: Thu, 27 Oct 2016 15:14:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606466;
	bh=HnFI26j1796el/URF8m6EmxHbJPcRUU9RFbV/zEMwDQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VuzBVo+hbzzQPkn6yLxzaIlo6m+IPBvFbfYoqBuhap4/IdqvfIfXqmWeel/EqyxpI
	 vOciqgI67nz4hayN/LDkwFi5j4fOJBSoA1FyT7LujIGzewDbEb9fkwjpU+31LRejrL
	 OkkjVdiGKBfvuW2Fs6F31PosLQY/+Aa2y3Eh6ThE=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (74/60 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46834)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsx0-0004lg-5l
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:15:08 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzswz-00047L-D2
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:15:06 -0700
Date: Thu, 27 Oct 2016 15:14:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606505;
	bh=q8+RwZhhrbkBfxcXZUMznr3AC3/v3U/u0acSvz2OPgE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Bd9gVmp+ZVn/2pa2oyj9rmbkvXBnvODXXdSsY7cxZ//T+IGBBuWJA41sf5d6OUusT
	 FWh8xxQG5bcd4goNo8CywSg1CrEZsppd2NfXAYXHOy95wv/xUkWYqt+9CEU08CU+pQ
	 Yk49LIYlRUst8kQQVvO8xiIUjwlETukYhgffpFM0=
