### ISSUE TITLE
Image.getSize on Android is weird

### ISSUE THREAD

**Issue by 12d** [facebook/react-native#8241]
Running 'Image.getSize'  twice, the first time, I can get the size of image, but the second time get zero.

```
    componentDidMount(){
        Image.getSize('http://facebook.github.io/react/img/logo_og.png',function(height, width){
            console.log(height);
            console.log(width)
        })
        Image.getSize('http://facebook.github.io/react/img/logo_og.png',function(height, width){
            console.log(height); //output: 0 (iOS is OK, Android gets zero)
            console.log(width) // output: 0 (iOS is OK, Android gets zero)
        })
    },
```

**Comment by 281330** [comment]
What happens if you do it for a different source?

**Comment by charpeni** [comment]
Thank you for this reporting. 

It has recently been fixed by 99e2a67b3992c3d76fa519a5880d7abc5c57b7a2  and it will be landed soon into 0.28 or 0.29-rc.

I'll close this issue, please feel free to reopen it if it doesn't fix your issue.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-1** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
