### ISSUE TITLE
react native horizontal Listview how inside Listview rows? why renderRow  no create horizontal Listview

### ISSUE THREAD

**Issue by RongjieChen** [facebook/react-native#8242]
same for title.

**Comment by Ehesp** [comment]
Can you please give more information. The question doesn't make much sense in either.

**Comment by nihgwu** [comment]
I think this should be labeled stackoverflow as it's just a question to know how to build a specific layout, btw, although i know the Chinese meaning of the title but i missed the point either 😂

**Comment by RongjieChen** [comment]
![image](https://cloud.githubusercontent.com/assets/1474815/16196682/77cc8f54-3731-11e6-8dc0-a74246ee10ea.png)
@Ehesp @nihgwu  like this layout, do you have any ideas?

**Comment by nihgwu** [comment]
but i still don't know what's the problem when you are building this kind of view, and i don't think there would be any problem to achieve that

**Comment by nihgwu** [comment]
i got it, in the horizontal listview, it should be `renderRow={()=>this.renderObjectItem()}` , and please try to ask this kind of question on SO or QQ group, it would be more efficient😃

**Comment by RongjieChen** [comment]
@charpeni renderRow={this.renderObjectItem}  this method in ES6 not work , it not bind this,  need arrow function or bind

**Comment by charpeni** [comment]
Of course, IMO binding methods in the constructor is a proper way. :)

A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary.

**Comment by RongjieChen** [comment]
@nihgwu not work , do you have any demo in listview items add horizontal listview.

**Comment by nihgwu** [comment]
@charpeni you are definitely right, but that's your style, you can't assume the others doing the same way, i using this style `renderItem = () => {}` 😄

**Comment by RongjieChen** [comment]
@charpeni  thx ,  IMO binding methods in the constructor is a proper way.

**Comment by nihgwu** [comment]
@RongjieChen please try to provide your own demo on appetize.io

**Comment by nihgwu** [comment]
https://itunes.apple.com/cn/app/niu-du-neoreader/id1111443079?l=en&mt=8
i'm using vertical listview + horizontal listview in this app and it works great, so you have to check your code more carefully

**Comment by charpeni** [comment]
Unfortunately, as @nihgwu said, GitHub issues are for bugs only.

I suggest you to : 

1. Remove the `horizontal` prop
2. Verify your methods (binding, calls and render)
3. Do a working vertical ScrollView
4. Add `horizontal` prop

If you still need help, do not be afraid of Stack-Overflow.

I'll close this issue, if you finally found a bug please reopen an issue with more information.

**Comment by charpeni** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-1** [comment]
Hey @RongjieChen and thanks for posting this! @charpeni tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.

**Comment by RongjieChen** [comment]
i don't know write error , @nihgwu do you have simple demo like this

**Comment by nihgwu** [comment]
please check carefully, OK?

**Comment by forrest-pan** [comment]
[rn-HorizontalListView-embed-into-native-listview.zip](https://github.com/facebook/react-native/files/327398/rn-HorizontalListView-embed-into-native-listview.zip)

[src.zip](https://github.com/facebook/react-native/files/327439/src.zip)

I may have a same problem, and i upload the demo apk and src zip above.
my problem is:
I embed a react-native horizontal listview into a native listview. When I slip the rn horizontal listview， it look slow slip， and i think there maybe some event conflict between the rn horizontal listview and native listview.
however, i embed it into a base layout(such as linearlayout), the rn horizontal listview sliding more smoothly,  doesn't have any slow.

Looking forward to your reply.
