### ISSUE TITLE
[WebView, iOS simulator] Can't type 'r' character

### ISSUE THREAD

**Issue by stereodenis** [facebook/react-native#8246]
after this coomit https://github.com/facebook/react-native/commit/2d32a6df27dc60b0e965b638e8e45147f9d4b892
I can't type 'r' character in a WebView input in Simulator

**Comment by javache** [comment]
The shortcut has been disabled in https://github.com/facebook/react-native/commit/1e88c1261cbd0a82644c27b9cdf2fa2dcb526641
