### ISSUE TITLE
css-layout-192 and later breaks flex row layout

### ISSUE THREAD

**Issue by douglowder** [facebook/react-native#8248]
After commit 8afcaa36e661c921bded4ab4127cc6ed785c9004 (import of css-layout-192 to 196), horizontal grid layout is broken (at least on iOS); the layout does not seem to wrap.  I backed out just the changes in Layout.c and Layout.h, and expected behavior is restored.

Screen shot of UIExplorer's ListView grid layout example, before css-layout-185:

![simulator screen shot jun 20 2016 8 10 54 am](https://cloud.githubusercontent.com/assets/5151180/16199701/794d4d7c-36bf-11e6-9123-94e46b44c5fd.png)

After 8afcaa36e661c921bded4ab4127cc6ed785c9004:

![simulator screen shot jun 20 2016 8 12 15 am](https://cloud.githubusercontent.com/assets/5151180/16199717/840bf89e-36bf-11e6-990b-fdb357eb6649.png)

**Comment by javache** [comment]
@emilsjolander
