### ISSUE TITLE
Document how to connect to a non-default packager port on Android

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8252]
It's possible to start the packager locally on a different than the default port 8081:

    react-native start --port 8088

(Try going to localhost:8088 in your browser)

How to get the device to connect to the packager on that port, however?

On iOS, you can change the port in AppDelegate.m.
On Android, the port seems to be hardcoded in [AndroidInfoHelpers.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/AndroidInfoHelpers.java), maybe it's possible to simply pass different arguments to `adb reverse tcp:8081 tcp:8081`?

A good place to put this info would be the "Running on device" docs, both iOS and Android:
- http://facebook.github.io/react-native/docs/running-on-device-ios.html
- http://facebook.github.io/react-native/docs/running-on-device-android.html

This is quite highly upvoted request on Product Pains:
https://productpains.com/post/react-native/allow-packager-port-to-be-configurable-change-from-8081/

**Comment by burgalon** [comment]
@mkonicek actually maybe I need to split this and add it to Running on IOS?
