### ISSUE TITLE
Flexbox - Document how to write responsive apps

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#8255]
I get this question a lot: How to have different styles for an iPhone vs iPad?

I haven't tried this but you could use this library to check for screen size and simply use different styles (just use an if statement): https://www.npmjs.com/package/react-native-device

Also found this article: https://medium.com/@elieslama/responsive-design-in-react-native-876ea9cd72a8#.5a22xco5a

**Comment by samuelkraft** [comment]
In our app we use onLayout on the root view that returns width and height - then update the styles with an if statement. This works great for rotation/ipad split view etc. A lot of libraries depend on Dimensions which doesn't always update on rotation/screen changes. Here's an [example article](https://corbt.com/posts/2016/03/16/detecting-orientation-in-react-native.html) how to implement it.

**Comment by mkonicek** [comment]
Thanks @samuelkraft, good point about screen rotation!

**Comment by fab1an** [comment]
Take a look at my library: https://github.com/fab1an/react-native-tachyons, which helps in creating responsive apps by specifying spacing relative to font-size.

**Comment by lacker** [comment]
I think the Flexbox docs are a lot better now so perhaps this is satisfied. If not then I welcome a PR martin ;-) I am going to close this issue for now but thanks for opening it in the first place becacuse it helped us prioritize that docs lockdown.
