### ISSUE TITLE
[NavigationExperimental] Migrate NavigationCardStack to NavigationTransitioner

### ISSUE THREAD

**Issue by ericvicenti** [facebook/react-native#8262]
Currently `NavigationCardStack` depends on `NavigationAnimatedView`, which we plan to deprecate.

This is one of the final steps we need to take before we can rename `NavigationExperimental` to `Navigation`

**Comment by satya164** [comment]
Closing since this is done.

**Comment by jreziga** [comment]
Still called NavigationExperimental :v
