### ISSUE TITLE
Text inside Listview row UI issue

### ISSUE THREAD

**Issue by jojonarte** [facebook/react-native#8270]
![alignment](https://cloud.githubusercontent.com/assets/11880365/16219690/986a22b0-37ba-11e6-8539-04ceaf65dd6a.png)

As you could see on the listview where the a subdescription of each should have a long string, the entire text just goes continuously to the right instead of properly aligning itself same as what happened on the description on the blue background.

I find it weird that it is not functioning the same way when it is rendered on the row of the listview.

Your insights would be welcome on how I could solve this issue of styling. I would like to have the row text to show up just like in the comments of Facebook.

Here is a snippet of the renderRow component

```
render()
 {
    var data = this.props.data;
    return (
      <View style={styles.container}>
          <Image style={styles.avatar} source={require('../images/avatar.jpg')} />
          <View style={styles.inner_container}>
            <Text style={{fontWeight: '500', fontSize: 13,textAlign:'justify'}}>{username}</Text>
            <Text style={{flex: 1, fontWeight: '300', fontSize: 14, marginTop: 5, textAlign:'justify',allowFontScaling: true}}>
            {data.comment}
            </Text>
          </View>
      </View>
    );
  }
```

**Comment by Ehesp** [comment]
You need to wrap the text which is supposed to "multi line"  in a view with rowDirection set to column. On my phone so can't really give a decent example.

**Comment by jojonarte** [comment]
I modified it this way still the same, I think there is no rowDirection so I tried with flexDirection
`return (
      <View style={styles.container}>
          <Image style={styles.avatar} source={require('../images/avatar.jpg')} />
          <View style={{flexDirection: 'row'}}>
            <Text style={{fontWeight: '500', fontSize: 13,textAlign:'justify'}}>{username || "Anonymous"} </Text>
              <Text numberOfLines={2} style={{flex: 1, fontWeight: '300', fontSize: 14, marginTop: 5, textAlign:'justify',allowFontScaling: true}}>
                {data.comment}
              </Text>
          </View>
      </View>
    );`

**Comment by Ehesp** [comment]
Sorry was half asleep - I meant `flexDirection`. Whats the styles of your `styles.container`?

**Comment by jojonarte** [comment]
Yup I fixed it just by adding flex: 1 to the view that I wrapped it with 💃
