### ISSUE TITLE
[iOS] Images not being released using Navigator?

### ISSUE THREAD

**Issue by Naoto-Ida** [facebook/react-native#8276]
I'm currently trying to optimize our app.

We have a section of the app where we have lots of images displayed using a `ListView`.
Just rendering this consumes a lot of CPU and memory (which is another issue).

Navigation is done by the `Navigator`.
When I use `pop()`, it goes back to the main page as intended, but
CPU and memory seem to be the same as the previously mentioned section.
I've even manually emptied the states when `componentWillUnmount` is called in the ListView.

Has anyone run into this issue? Or am I misunderstanding the documentation's description of `pop()`?

**Comment by sibelius** [comment]
consider using ReactNativeExperimental (https://facebook.github.io/react-native/docs/navigation.html)

or https://github.com/exponentjs/ex-navigation

**Comment by Naoto-Ida** [comment]
@sibelius Thanks, will use these in our next React Native project.
