### ISSUE TITLE
Empty Getting Started when Clicking on Docs from Showcase

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/react-native#8286]
Click on Showcase in the header bar. Then click on Docs.

**Comment by BilalBudhani** [comment]
works fine for me on React Native 0.28 version. What version do you see?

**Comment by JoelMarcey** [comment]
Oh yeah, I am not seeing it any longer either (I am using Chrome). :/

@lacker Can you still reproduce this behavior?

**Comment by lacker** [comment]
Yeah I can still repro. Use Firefox, pull fresh from master, go to http://localhost:8079/react-native/showcase.html then click "Docs" in the header.

**Comment by JoelMarcey** [comment]
Yeah -- this seems to be a FireFox specific problem, which makes it worse in my mind :/

**Comment by lacker** [comment]
OK I will debug further....

**Comment by lacker** [comment]
fixed with https://github.com/facebook/react-native/pull/8335
