### ISSUE TITLE
Couldn't find preset “es2015” relative to directory

### ISSUE THREAD

**Issue by hotarzhang** [facebook/react-native#8296]
When I'm trying to start a new react-native project from scratch I'm getting this message.
`Error: Couldn't find preset "es2015" relative to directory "/Users/hotar/Dev/Projects"`
and code is:
```
OptionManager.prototype.resolvePresets = function resolvePresets(presets, dirname, onResolve) {
    return presets.map(function (val) {
      if (typeof val === "string") {
        var presetLoc = (0, _resolve2.default)("babel-preset-" + val, dirname) || (0, _resolve2.default)(val, dirname);
        if (presetLoc) {
          var _val = require(presetLoc);
          onResolve && onResolve(_val, presetLoc);
          return _val;
        } else {
          throw new Error("Couldn't find preset " + (0, _stringify2.default)(val) + " relative to directory " + (0, _stringify2.default)(dirname));
        }
      } else if ((typeof val === "undefined" ? "undefined" : (0, _typeof3.default)(val)) === "object") {
        onResolve && onResolve(val);
        return val;
      } else {
        throw new Error("Unsupported preset format: " + val + ".");
      }
    });
  };
```

**Comment by fab1an** [comment]
Do you have a file called `.babelrc` in one of the parent-folders `/Users/hotar` `Dev` or `Projects`?

**Comment by hotarzhang** [comment]
@fab1an  Year. It's. Thangk you. And I did this
```
$ npm i babel-preset-react-native --save-dev
$ echo '{"presets": ["react-native"]}' > .babelrc
```

**Comment by RahulBairagi** [comment]
When i try generate android apk of my react project it shows following error.  but normally when i run on expo its fine. i have been followed all required procedure when makes android apk.
 
F:\GeneratAPK _ReactCode\SakeWiz-Native\node_modules\react-throttle\lib\index.js: Couldn't find preset "es2015" relative to directory "F:\\GeneratAPK _ReactCode\\SakeWiz-Native\\node_modules\\react-throttle"

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1
