### ISSUE TITLE
Async Storage "iOS Data Storage Guidelines" issue

### ISSUE THREAD

**Issue by grif-ecwid** [facebook/react-native#8304]
Hi!

Our application was rejected for "iOS Data Storage Guidelines" issue. I found that AsyncStorage data is stored in Documents folder (see https://github.com/facebook/react-native/blob/master/React/Modules/RCTAsyncLocalStorage.m#L70) We store in storage lot of information about catalog and it's grow up quickly.

Is there any restriction to move data file into Cache directory or mark it like NSURLIsExcludedFromBackupKey YES? May be add parameter to AsyncStorage.setItem which one will be add this flag?

**Comment by robclouth** [comment]
Hey, same problem. Did you manage to fix this?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/async-storage-ios-data-storage-guidelines-issue

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (69/60 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46708)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvu-0004LS-Pw
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:59 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvu-00040n-4L
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:58 -0700
Date: Thu, 27 Oct 2016 15:13:47 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606437;
	bh=f9UFExtNshKFXjn/5sIyXlTtT+jnFhoPeMdDsgVAA2U=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TPSdJGL8Ceb9bBYl/THJuZ7mBtCJj+9mZyNKnmr2g9aARiJ/8sTlI75fkR0DIl5A5
	 ck4l0eewGBX1DGX9XTFLY9yAYfdUNrUahHEoWCtob7+jNCrdj4JAc838yhJepY0NHi
	 xr6pylCtRzHI0ZJlhWm/+VQW/wGZubXaUSC+HgMw=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (73/60 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46772)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzswr-0004gr-5k
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:14:58 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzswq-000469-HX
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:14:57 -0700
Date: Thu, 27 Oct 2016 15:14:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606495;
	bh=GydwTfts8Ny+nYilJbzb77yN6l8DQDbyQOw808p0Mss=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MMVPP1n0j+N3HD5dGpmMVMu8gr4DONokRXSVq2DPuzEmuypH60kiWiXvmSrAr5iUR
	 7mSn9bv37cTKqWbxWl741+3wZbCX0DIP/vDsh89SH8yM5DWE0AuL5bNjHEetoxb2pk
	 RvwwlZ7gycoDDtKEfvLkOY6TbPA8EEKQhSPH4o9c=

**Comment by robclouth** [comment]
I would argue that this is a bug. The documents folder is public facing and can be accessed via iTunes. This isn't an appropriate place for settings.
