### ISSUE TITLE
Style prop for TouchableNativeFeedback and TouchableWithoutFeedback

### ISSUE THREAD

**Issue by efkan** [facebook/react-native#8307]
I've reported that feature request on [that ProductPains' page](https://productpains.com/post/react-native/style-prop-for-touchablenativefeedback-and-touchablewithoutfeedback). 

If you need `style` prop in TouchableNativeFeedback or TouchableWithoutFeedback use please increase the request count.

#### Issue:

I can use `style` prop in `TouchableHighlight`. 

However,  `TouchableNativeFeedback` and `TouchableWithoutFeedback` components don't have `style` prop.

To give shape the components style prop is necessary.

**Comment by jalooc** [comment]
@efkan just out of curiosity - why have you closed this issue - did you find any reasons why not to do this?

**Comment by efkan** [comment]
Those days fb developers directed us to product pain web site for the new feature request.

The reason was this.

**Comment by jalooc** [comment]
I see that product pain's issue is also stale. Maybe it's time to reopen this one? Imho the feature could help writing more consistent code.

**Comment by ZakherM** [comment]
I was having the same issue. But I wrapped the TouchableWithoutFeedback element with a view and styled the view instead. And I wrapped everything inside the TouchableWithoutFeedback with another view with a style identical to the parent view. This seems to have fixed it for me.
