### ISSUE TITLE
Lots of issues upgrading 0.26 to 0.28

### ISSUE THREAD

**Issue by allthetime** [facebook/react-native#8312]
Hi, I'm just throwing this out there hoping someone has gone through the same process I'm attempting right now. 

I'm trying to upgrade from 26 to 28 and getting lots of deep errors (not related to specific modules, but fundamental react-native stuff)

Before I dive in, I'm curious if anyone has recently pulled this off with an existing project and if you have any tips for me...

**Comment by alloy** [comment]
> Before I dive in, I'm curious if anyone has recently pulled this off with an existing project and if you have any tips for me...

In order for people to be able to determine whether or not they have had the same issues you should always include as much information in tickets as you can. E.g. build errors, CLI output, screenshots, etc.

Also please keep in mind that the RN team has reserved this place for detailed discussion about bugs/features, whereas general chatter/tips is requested to be taken place on e.g. StackOverflow.

**Comment by allthetime** [comment]
@alloy 

Yeah, sorry, I know, I'm just kind of desperate and StackOverflow has a pretty terrible response rate for react-native issues.

**Comment by alloy** [comment]
@allthetime There’s also the chat channel on http://www.reactiflux.com, maybe that might be more helpful for your situation.

**Comment by allthetime** [comment]
@alloy I'll head over there. Thanks for your response :)
