### ISSUE TITLE
Windows issue: Could not install app on the device, read the above for the details.... while running "react-native run-android" command

### ISSUE THREAD

**Issue by prashen** [facebook/react-native#8313]
![last](https://cloud.githubusercontent.com/assets/5449548/16265503/5931abf2-389d-11e6-952d-1da12c043cb4.jpg)

I am getting these error when running "react-native run-android". Need suggestion why this coming. My Emulator port is showing 5554 port.

@lacker #

**Comment by prashen** [comment]
![second last](https://cloud.githubusercontent.com/assets/5449548/16364498/1af363e6-3c06-11e6-9761-26d3d0083b98.png)

I am able to build package file in emulator but after the app opens in the emulator i am getting this error. Can you please tell me where i am getting it wrong. Don't know why React native documentation for windows is so complicated. Give some exe installation package. I am trying to install in windows from 1 week. Still stuck!!!!!!

**Comment by lacker** [comment]
In your screen shot there's an error saying, "error, something else is using this port". Can you check if something else is using that port? For example, an old copy of the packager. I would try killing all running processes and re-trying `react-native run-android` anew.

**Comment by prashen** [comment]
Thanks! 
I am now able to run app on my emulator as well as on my moto g2 physical device via usb.
I have to always type command after connecting devices and checking it typing code "adb devices" then "adb reverse tcp:8081 tcp:8081". After these code i am able to build a working package on my emulator/device.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/windows-issue-could-not-install-app-on-the-device-read-the-above-for-the-details-while-running-react-native-run-android-command

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (70/60 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56401)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsw9-0004RF-Lr
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:14:14 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsw7-0000vd-V8
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:14:13 -0700
Date: Thu, 27 Oct 2016 15:13:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606450;
	bh=Kvh+/zTeX+WKWBd/YZw92H/9f5vF08WzZAToop2uv+w=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=inWHKuZWsriR80fmvunYCnUQA+GyPSw8BDxqROQf3I0X1lFGg0ILOrMsJWeVUL82p
	 cvKSw7elINln9DegUaqJYg1IrgfvssB2sOaBqALNH7z9+tn/8VWpYx1b9jMn/VcRzm
	 eE8ACFx4p9XpISl7tlTEknnzyHW80gy0SP0SorVk=
