### ISSUE TITLE
New ProgressBar component that renders a horizontal progress bar on iOS and Android

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#8315]
In order to render a horizontal progress bar, a user must choose between `ProgressViewIOS` and `ProgressBarAndroid` depending on the platform the app is running on. Both of these components are similar enough in functionality that it makes sense to build a new cross-platform component, `ProgressBar`.

`ProgressBar` renders a horizontal progress bar on both platforms using the existing React Native component for the targeted platform. On iOS, this would use `ProgressViewIOS`, and on Android it would use `ProgressBarAndroid`.
## 

We are cleaning up the [Known Issues](https://github.com/facebook/react-native/blob/a9d8d1cab6d0196604e7ffcb4670ee675b093d69/docs/KnownIssues.md) doc as part of this week's React Native Documentation Lockdown.

A handful of issues are flagged in that document which belong in the issue tracker, not in the docs.

**Comment by AgtLucas** [comment]
@hramos Any update about this? Thanks!

**Comment by hramos** [comment]
@AgtLucas this is still up for grabs

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/new-progressbar-component-that-renders-a-horizontal-progress-bar-on-ios-and-andr

**Comment by zenkhas** [comment]
This issue should be Open again, it makes more sense to provide a Horizontal ProgressBar component out of the box that works with both platforms.

**Comment by matthargett** [comment]
@hramos I'd like to re-open this so my colleague @jhampton can do this work. We discussed this a few months ago.
