### ISSUE TITLE
Create new ViewPager component that provides paging functionality on iOS and Android

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#8316]
Paging between views can be implemented on iOS using `ScrollView` with `pagingEnabled={true}` and on Android using `ViewPagerAndroid`.

We can unify them in a new `ViewPager` component that works cross-platform.
## 

We are cleaning up the [Known Issues](https://github.com/facebook/react-native/blob/a9d8d1cab6d0196604e7ffcb4670ee675b093d69/docs/KnownIssues.md) doc as part of this week's React Native Documentation Lockdown.

A handful of issues are flagged in that document which belong in the issue tracker, not in the docs.

**Comment by Ehesp** [comment]
@hramos was any work done on a unified ViewPager component?

**Comment by hramos** [comment]
@Ehesp no, this is still up for grabs

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/create-new-viewpager-component-that-provides-paging-functionality-on-ios-and-and
