### ISSUE TITLE
Android refresh control scroll behavior interrupts horizontal scroll view

### ISSUE THREAD

**Issue by calebmer** [facebook/react-native#8326]
On Android, when scrolling through horizontal `ListView`, if you scroll slightly up as well the `RefreshControl` starts to appear. This is undesirable and does not happen in iOS. When scrolling horizontal normally you cannot scroll up and down at the same time, one shouldn’t be able to activate the refresh control when scrolling horizontally.

To reproduce this behavior, start scrolling left/right then move your finger down as in a refresh. The refresh control will come down and interrupt your horizontal scroll.
- Minimum code sample: https://rnplay.org/apps/T7drbA (or pasted below).
- React Native version is `^0.26.0`.
- Occurs only on Android.
- Using a Mac.

Code sample:

``` jsx
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  RefreshControl,
  ScrollView,
} = React;

var SampleApp = React.createClass({
  getInitialState: function() {
    return {
      dataSource: new ListView.DataSource({ rowHasChanged: (a, b) => a !== b })
    }
  },
  render: function() {
    return (
      <ListView
        dataSource={this.state.dataSource.cloneWithRows([1, 2, 3])}
        refreshControl={<RefreshControl refreshing={false}/>}
        renderHeader={() => (
          <ScrollView horizontal>
            <View style={[styles.box, { backgroundColor: 'red' }]}/>
            <View style={[styles.box, { backgroundColor: 'green' }]}/>
            <View style={[styles.box, { backgroundColor: 'blue' }]}/>
          </ScrollView>
        )}
        renderRow={row => <View><Text>{row}</Text></View>}
      />
    );
  }
});

var styles = StyleSheet.create({
  box: {
    width: 200,
    height: 200,
  }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by mangogogos** [comment]
Definite +1, this will even occur when setting scrollEnabled: false on the Scroll/ListView. RefreshControl definitely shouldn't activate if you can't even scroll vertically in the first place.
cc @janicduplessis

**Comment by kunkun12** [comment]
+1

**Comment by Guocover** [comment]
I got the same problem, hope for help!

**Comment by tuneZola** [comment]
Also I, :)

**Comment by ouabing** [comment]
+1 here

**Comment by Kowaio** [comment]
Bringing this up again after encountering the problem. Current version used is RN 0.39. Thanks!

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-refresh-control-scroll-behavior-interrupts-horizontal-scroll-view

**Comment by superandrew213** [comment]
@calebmer did you come up with a workaround for this?
