### ISSUE TITLE
[XMLHttpRequest] responseHeaders doesn't include cookies

### ISSUE THREAD

**Issue by asamiller** [facebook/react-native#833]
The headers object returned in XMLHttpRequest's `request.responseHeaders` doesn't include `Set-Cookie`. Is it possible to get the cookie value from a XMLHttpRequest response?

**Comment by browniefed** [comment]
@asamiller @brentvatne There was a solution posted here https://github.com/joeferraro/react-native-cookies

**Comment by browniefed** [comment]
Solved here #1274
