### ISSUE TITLE
Android not sending headers and body with fetch()

### ISSUE THREAD

**Issue by andrispraulitis** [facebook/react-native#8332]
Hi,

I'm very new to RN. I've been working with iOS only so far. Today I upgraded to RN 028 and tried Android too, but got stuck at login screen. Seems that Android is not sending headers and body using fetch() and not sure how to fix.

**Working on Mac with:**
Android Studio for sdk
Genymotion for emulator

Perhaps some tools/settings missing on Android sdk? Can anyone help?

**Comment by lacker** [comment]
Can you provide some specific code that reproduces this problem?

**Comment by andrispraulitis** [comment]
@lacker Not much there, just a basic fetch test

`function authenticate(user_data) {
	return dispatch => {
		const endpoint = 'http://dev.example.co.uk/auth';
		const requestOptions = {
			method: 'POST',
			headers: {
				'Accept': 'application/json',
				'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
			},
			body: 'email=andris%40example.co.uk&password=123456'
		}
		
		return fetch(endpoint, requestOptions)
			.then(response => {
				console.log(response);
			});
	}
}`

response on iOS:
<img width="637" alt="ios" src="https://cloud.githubusercontent.com/assets/8721800/16307664/0650bc6c-395a-11e6-840e-be690cc0e7c4.png">

response on Android:
<img width="662" alt="android" src="https://cloud.githubusercontent.com/assets/8721800/16307692/1a8e56bc-395a-11e6-976f-8a3acaf23fc9.png">

If it helps the backend for this is Craft CMS with this plugin: [https://github.com/pixelandtonic/ElementAPI](url)

**Comment by andrispraulitis** [comment]
Domain exception issue locally, works fine connecting to live server.
