### ISSUE TITLE
[IOS] React-Native 0.28.0 App not running in IOS 10 and Xcode 8

### ISSUE THREAD

**Issue by alexanderniebuhr** [facebook/react-native#8344]
Hello,

As @nickstamas said in #8108 there is an Problem with running an React Native App in Xcode 8 and IOS 10. I get same output such as:

`nw_endpoint_flow_protocol_disconnected [1.1 ::1.8081 cancelled socket-flow (null)] Output protocol disconnected`

Images of the App are just shown with the gray light blue weird background color (see Picture). And my app also seems unresponsive in the Simulator.

Is there a workaround for this Problem yet? 
Or can anyone help to solve this Problem?

Thx Alex

![vinoa screenshot png](https://cloud.githubusercontent.com/assets/15894713/16294070/e3a74db0-391e-11e6-9043-650cc9ba728a.png)

**Comment by mixophrygian** [comment]
The commit purported to provide iOS 10 support is slated to be released with version 0.29:

https://github.com/facebook/react-native/commit/7c8b91442b3547cf94c752f234210bef0848c00a

**Comment by bourgois** [comment]
Seems to be now waiting for 0.34 :(
That can be a problem with many user moving to ios 10 later this week !

**Comment by dijonkitchen** [comment]
It looks like this commit is in the master branch no? It's tagged with the release candidate for version 0.34, but it's also tagged with prior releases, specifically 0.29, so it should already be merged in. 

Another reputable source: https://twitter.com/vjeux/status/742651239922606080

Have there been any issues running iOS 10 or Xcode 8?

**Comment by bourgois** [comment]
Well we still have problems with Xcode 8 and need to do the work around describe in https://github.com/facebook/react-native/issues/8584 ...
Didn't yet do full test on iOS 10

**Comment by dijonkitchen** [comment]
That fix as well as upgrading to RN 0.33.0 (along with React 15.3.1) seems to work.

**Comment by namelesstv** [comment]
As @dijonkitchen linked,[ this comment solved it for me](https://github.com/facebook/react-native/issues/8584#issuecomment-236366222)
 
P.S. I was experiencing this issue in react-native 0.30.0 + react 15.2.1
