### ISSUE TITLE
Date.toLocaleDateString() ignores country settings on Android

### ISSUE THREAD

**Issue by rburgst** [facebook/react-native#8349]
- [x] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.

``` javascript
    let testDate = Date.UTC(2016, 6, 23, 10, 0, 0, 0);
    let output = new Date(testDate).toLocaleDateString();
    return         <Text style={styles.text}>{output}</Text>;
```

https://rnplay.org/apps/bGMmOA
- [x] Provide **screenshots** where appropriate
1. go to phone settings and change the language to Deutsch (Deutschland)
   ![sample_app___react_native_playground](https://cloud.githubusercontent.com/assets/22971/16299937/4d4cdf96-393d-11e6-97d2-feb186e400f5.png)
2. launch the app
   ![on_device](https://cloud.githubusercontent.com/assets/22971/16299898/175a66ce-393d-11e6-9a55-829630ac858c.png)
### Expected:

`23.06.2016`
### Actual:

`07/23/16`
- [x] What's the **version** of React Native you're using?

0.28
- [x] Does this occur on iOS, Android or both?

only Android, on iOS this works fine.
- [x] Are you using Mac, Linux or Windows?

Mac

**Comment by kyo504** [comment]
Is there any progress on this? I also have this issue on 0.30.

**Comment by jan-happy** [comment]
+1

**Comment by zurodtl** [comment]
I've got same issue

**Comment by areiterer** [comment]
The issue is also reproducable with 0.40.0

**Comment by belliAndrea** [comment]
same issue

**Comment by TyrealGray** [comment]
Still have this issue with 0.43.3

**Comment by soraphis** [comment]
this issue is really annoying and i can't understand how this issue can be open since nearly a year.
sure there are tons of date-format-npm-packages out there, but that's so unnecessary.

btw this is related: http://stackoverflow.com/questions/42218022/react-native-reacts-differently-when-not-debugging-remotely

**Comment by Pimm** [comment]
Still reproducible with 0.46.3.

**Comment by ccsilveira** [comment]
+1

**Comment by ide** [comment]
This is because JSC on Android doesn't include the locale settings. It would increase the size of the APK by ~2MB so it's not clear whether we want to include this.

**Comment by soraphis** [comment]
imho the issue should stay open, as far as i know it is still a problem in the latest release, and the issue is inactive for a while because people accept it as problem and use workarounds.

**Comment by hramos** [comment]
Is there a PR open that attempts to address the issue?

**Comment by jayzhou215** [comment]
now seems use `new Date().toLocaleDateString()` crash directly in android huawei phone with 1.0.0, while it is ok in ios,
use `new Date().toString()` ok

**Comment by erdemkeren** [comment]
Same here with @jayzhou215. Tried with physical Samsung Galaxy Note 4, Android Studio and Genymotion emulated  Google Pixel 7.1.0 API 25.

**Comment by ljuborados** [comment]
This definitely shouldn't be closed.
new Date().toLocaleDateString() still isn't working correctly, and is really a basic feature.

**Comment by OleksiiLyhun** [comment]
I also have the same problem. Using react-native version 0.55.4
