### ISSUE TITLE
[NavigationExperimental] Best way to dynamically change content of overlay from scene?

### ISSUE THREAD

**Issue by joonhocho** [facebook/react-native#8350]
I want to control / update content of `overlay` from the `scene` component.
For example, I want to dynamically change nav bar title based on user interactions inside a `scene` without doing any navigation.

Afaik, the following is a simplified version of how `scene` and `overlay` are rendered inside a `AnimatedView` or `CardStack`.
```javascript
<AnimatedView>
  {scene}
  {overlay}
</AnimatedView>
```

Correct me if I am wrong, but currently, it seems the only way to trigger rerendering of `overlay` from the `scene` is to update `navigationState`.
That means we need to use a `reducer` to create a new `navigationState`, which will cause rerendering of `scene` as well as `overlay`.
It sounds like an overkill and too heavy work for such a trivial task.

Another way I can think of is to expose a new API via `context` that can override `overlayProps`.
Here's a simplified code snippet for the concept:
```javascript
class ContainerWithContext extends Component {
  getChildContext() {
    return {
      setOverlayProps: (overlayProps) => this.setState({overlayProps})
    };
  }
  renderOverlay() {
    return this.props.renderOverlay({
      ...this.props,
      ...this.state.overlayProps,
    });
  }
  render() {
    return (
      <View>
        {this.renderScene()}
        {this.renderOverlay()}
      </View>
    );
  }
}

const Overlay = ({title}) => <View><Text>{title}</Text></View>;

class Scene extends Component {
  static contextTypes = { setOverlayProps: PropTypes.func }

  updateNavTitle(title) {
    this.context.setOverlayProps(title);
  }
}
```

I can help with PR if you think this is a good idea.
What are your thoughts on this?

**Comment by jmurzy** [comment]
I would not use `context`, as it would be an overkill. There seems to be multiple ways to approach this. But I'm not convinced this belongs within `NavigationExperimental`. The low level nature of `NavigationExperimental` enables greater abstractions to be built up in higher layers.

Also, NavigationAnimatedView is [deprecated](facebook/react-native@8ce7ad4). As for NavigationTransitioner, `renderScene` and `renderOverlay` are also deprecated. `NavigationTransitioner` now [delegates](facebook/react-native@c57bac4) the rendering of all its children to a user provided render function. This addresses the issue discussed [here](facebook/react-native#7210). A nice side effect of this is that it allows full control over both the `scene` and `overlay` components.

That means you can just pass in a `ref` (to your overlay) in props to your scenes and just call a function directly on your `overlay` component to mutate its internal state. Let me know if this doesn't make sense and I'll put together an example. Oh and then there is Redux 😆

🍺

**Comment by joonhocho** [comment]
I've used Redux before, but haven't needed it yet since I started using Relay, but I think it's the time to use it together with Redux.

**Comment by chirag04** [comment]
or you can also use an event emitter like the way exnavigation does:
https://github.com/exponentjs/ex-navigation/blob/6271d5cb1cdfa0336cdf57edff44d0a3ea3f7550/src/ExNavigationRouter.js#L57-L59

**Comment by joonhocho** [comment]
I will close this as recommended solutions make sense.

**Comment by RichardLindhout** [comment]
How can I make a reference to the header from my navRoot?

I have this now.

`    <NavigationCardStack
          onNavigateBack={this._handleBackAction.bind(this)}
          navigationState={this.props.navigation}
          onNavigate={this._handleNavigate.bind(this)}
          renderScene={this._renderScene}
          renderOverlay={this._renderHeader} />`

`  _renderHeader(props){
    const { route } = props.scene
    
    return (
      <Header
            route={route}
          
            _goBack={this._handleBackAction.bind(this)}
            _handleDrawerAction={this._handleDrawerAction.bind(this)}
            ref={(header) => { return this.header = header  }}>>
      </Header>
  )
  }`


When I try to do a function on the header from my navroot component
header.consoleLog()

**I get an error in my application. this.headerconsoleLog is not a function.** 


Header component code snippets

`class Header extends Component {
  constructor(props){
    super(props)

    this.consoleLog = this.consoleLog.bind(this)
  }



  consoleLog(){
    console.log('Change header via other component');
  }`

**Comment by RichardLindhout** [comment]
@jmurzy What can I do to reference my header in e.g. my scenes?

**Comment by Paul-Todd** [comment]
@jmurzy - I am still battling on how to change the overlay from a scene. What I would like to do is change the buttons and title from some of my view components created in the renderScene function.

Have you built the sample you mentioned above so we see how this is supposed to work?
