### ISSUE TITLE
React native 0.28 use fetch get data catch error

### ISSUE THREAD

**Issue by febobo** [facebook/react-native#8351]
use fetch on chrome borwser
![image](https://cloud.githubusercontent.com/assets/9276376/16299994/fba0587a-396f-11e6-9e76-59cfd530d88f.png)

use React native 0.28
![image](https://cloud.githubusercontent.com/assets/9276376/16300353/24074966-3972-11e6-804c-5c1aaf5e0ffc.png)
error 
![image](https://cloud.githubusercontent.com/assets/9276376/16300449/93982480-3972-11e6-8ac1-b6ea9f007fa4.png)

It makes me very confused  
use 0.25 fetch is ok,

**Comment by febobo** [comment]
I put http replace https is ok ,but me don't understand is why
![image](https://cloud.githubusercontent.com/assets/9276376/16301320/5da5b3b0-3977-11e6-8c2d-b4cb276eeca7.png)

**Comment by musicode** [comment]
the reason is Apple recommand use https by default.

**Comment by damly** [comment]
http://stackoverflow.com/questions/36289125/react-native-fetch-from-https-server-with-self-signed-certificate

**Comment by faisalil** [comment]
Found the problem. Looks like as part of the upgrade, the following changes happened to plist.Info:

Removed :
```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>

```
Added : 
```
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>NSAppTransportSecurity</key>
	<!--See http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/ -->
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>

```
https://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/ for more info. You basically need to add the http domains that you use to the plist.Info

**Comment by febobo** [comment]
OK，thx ，i already update plist.info , fix it

**Comment by ericmasiello** [comment]
@faisalil what version of React Native made this change to the xcode project's Info.plist file? Was it in version 28?

**Comment by ericmasiello** [comment]
Nevermind. I was able to track it down. So to anyone that was curious, this did change in the ios generator in 28 

28: https://github.com/facebook/react-native/blob/v0.28.0/local-cli/generator-ios/templates/app/Info.plist
27: https://github.com/facebook/react-native/blob/v0.27.0/local-cli/generator-ios/templates/app/Info.plist
