### ISSUE TITLE
flow not checking propTypes for newly created "react-native init" project

### ISSUE THREAD

**Issue by tomduncalf** [facebook/react-native#8357]
Setup: OS X El Capitan, Flow: 0.26, react-native-cli: 1.0.0, react-native: 0.23.1, Atom: 1.8.0, Nuclide: 0.146.0

It seems that `flow` is not properly checking propTypes of react-native components for a new project created with `react-native init`.

If I modify `index.ios.js` to have an invalid property on one of the components, for example:

```
<View style={styles.container} accessible='123'>
```

(where accessible should be `PropTypes.bool`), I get no error either in Nuclide or when running `flow`. I also get no autocompletion of props in Nuclide.

`flow` is doing something, however, as if I write a plain function e.g. `function test(a: string)` and try and call it with the wrong type e.g. `test(3)`, I do get an error in both `flow` and Nuclide.

I have the same problem with this starter kit repo: https://github.com/jhabdas/react-native-webpack-starter-kit but interestingly, not with the F8App from https://github.com/fbsamples/f8app – with the later, autocomplete and propType checking acts like I would expect it to.

**Comment by dleen** [comment]
I get the same issue when importing ```View``` from the usual location:
```import { View } from 'react-native';```

No error is shown when making the same type error as described in the issue above. However when importing directly from the file ```node_modules/react-native/Libraries/Components/View/View.js``` i.e.

```import View from 'react-native/Libraries/Components/View/View'```

I get the correct error:

```
src/components/Home.js:22
 22:   <View style={styles.container} accessible='123'>
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React element `View`
 22:   <View style={styles.container} accessible='123'>
                                                 ^^^^^ string. This type is incompatible with
109:     accessible: PropTypes.bool,
                     ^^^^^^^^^^^^^^ boolean. See: node_modules/react-native/Libraries/Components/View/View.js:109
```

So something is getting list along the way. I'll try take a deeper look.

**Comment by tomduncalf** [comment]
Ah, nice find. I wonder if the culprit could be https://github.com/facebook/react-native/blob/master/Libraries/react-native/react-native.js#L9 – the way the modules are exported is using `get`ters, which that line says Flow doesn't support, so I wonder if that is disabling Flow for anything that is required from the `main` entry point rather than directly?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/flow-not-checking-proptypes-for-newly-created-react-native-init-project

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
