### ISSUE TITLE
"Could not connect to developmenet server" for newly created projects since yesterday.

### ISSUE THREAD

**Issue by charlie-rc** [facebook/react-native#8358]
Hello,

Since yesterday, i am trying to create new project and build debug apk but getting error "could not connect to development server" where my old projects are working fine.

I am using updated versions for react native, npm and nodejs.

Please help.

**Comment by faisalil** [comment]
Are you debugging in an emulator? or real device?

**Comment by huangbong** [comment]
I think he's on a real device with the packager running on his computer. RN no longer binds the packager to 0.0.0.0 - instead it's only bound on localhost? Correct me if I'm wrong. I'm also experiencing this issue.

**Comment by charlie-rc** [comment]
Actually i am facing the problem, both when running on emulator (android studio) and on actual device both.

**Comment by IlyasM** [comment]
I am also experiencing this issue on real device on 0.29.0-rc

**Comment by jbultmann** [comment]
Not sure if it's the same issue but a newly created project of mine fails to start the development server with an error concerning ES6 Arrow functions
Could be a missing babel compiling step for the development server or an error in the babel configuration.

<project>/node_modules/react-native/local-cli/server/formatBanner.js:48
    chalkFunction: (fn) => fn,
                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (<project>/node_modules/react-native/local-cli/server/checkNodeVersion.js:12:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by charlie-rc** [comment]
"So i told nvm to use the 6.2.2 as default "....please can you explain how can i try this using terminal?

**Comment by npomfret** [comment]
I've just upgraded to 0.28.0 and I'm getting `Could not connect to development server` red box error message when I try to view my app in the iOS simulator.  There were no errors in npm, however after a few attempts i see `[Error: not opened]`.

The same goes for a physical iOS device, however I've also tried a physical android device and it works fine on there.

I then tried a fresh _AwesomeProject_ and that works fine on the iOS simulator.

So I'm wondering if the `react-native upgrade` process has some how broken the Xcode project files.

**Comment by npomfret** [comment]
Solve it - i made a mistake merging `Info.plist` and lost this:

```
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      ...

```

**Comment by terrysahaidak** [comment]
Any fix?

**Comment by xiangfengsu** [comment]
**me too !!!**
Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://192.168.1.245:8081/index.ios.bundle?platform=ios&dev=true

**Comment by jbultmann** [comment]
@charlie-rc 
"So i told nvm to use the 6.2.2 as default "....please can you explain how can i try this using terminal?
Sorry for the delay. You can use the command: `nvm alias default 6.2.2` to tell nvm to load this one as default

**Comment by kaelhem** [comment]
@jbultmann
Thx! I had the same issue, and this fix it for me too.

**Comment by victoriafrench** [comment]
Ok did the upgrade, just spent the past 4 hours trying to get the emulator working. Now the emulator works, but when I try to build the native app for my phone I get the same (fn) => (fn) error that jbultmann got above. Using node 6.2.2. Only happens when attempting to build for the device. Anyone?

**Comment by victoriafrench** [comment]
moving my issue to a new bug as it is bigger than this and not related to NSAllowArbitraryLoads

**Comment by ajaxmac** [comment]
@npomfret's solution worked for me - adding this to my Info.plist solved it:
` <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
      ...
`

**Comment by victoriafrench** [comment]
That only solves the issue with the emulator (because the connection to
localhost isn't ssl). I have this in the plist. Its compiling for a real
device that is failing

**Comment by Amerr** [comment]
@npomfret  please elaborate solution  on how to fix this issue. Is just confusing

**Comment by npomfret** [comment]
As of RN 0.29, if you want to deploy to a physical iOS device, you need to ensure that your apps `Info.plist` file contains the following:

```
	<key>NSAppTransportSecurity</key>
	<!--See http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/ -->
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

Be warned that this is now considered a security risk (read [this](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/)). You can specify a particular domain (but not an ipaddress i believe).  You don't need to do this in order to deploy to the simulator because the default settings in `Info.plist` allow http access to localhost.  And you don't need it when you push you app to production.

And your `AppDelegate.m` file will also need something like:

```
  #ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://<your-laptop-ip-address-here>:8081/index.ios.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #endif

```

**Comment by JosephDev** [comment]
@npomfret your solution is work. For other people, I attached my Info.plist 
RN 0.29.x Info.plist should like this
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSExceptionDomains</key>
	<dict>
		<key>localhost</key>
		<dict>
			<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
			<true/>
		</dict>
	</dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```
To connect local server with ip address, we need not only `NSExceptionDomains`, but also `NSAllowsArbitraryLoads`

Thanks @npomfret

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/could-not-connect-to-developmenet-server-for-newly-created-projects-since-yesterday

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (66/60 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46700)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvg-0004Fc-Kd
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:45 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvg-0003zN-11
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:44 -0700
Date: Thu, 27 Oct 2016 15:13:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606423;
	bh=onXbszdflbViQL/oQUFk+3tCAc3pGFQnPZqaNSy3uxw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=p77Ipvo4QaWdf6ecMwoOekDPU/vbLyMvX31bzYgZpmKiRzve/uewmMuXJQu73Sx1r
	 dpK6ff7zBV6BYnv8bXz5dGXgDkDoYNlU1fL9qh4i91ZDs2I5OMjvtbLj4NSClFsJgn
	 kHtY4jjpNTmct12b2Cp8dUUnMH8yeFutSEIF6C28=

**Comment by ajiprasetyo** [comment]
i had same problem like you and i resolved it,
my mobile device android version 5.0.2
i open terminal windows and run adb reverse tcp:8081 tcp:8081
maybe can help you

**Comment by JosephDev** [comment]
@ajiprasetyo on your physical device, you can set the url on developer setting.
Here is some steps from [official site](https://facebook.github.io/react-native/docs/running-on-device.html)

0. Make sure your laptop and your phone are on the same Wi-Fi network.
1. Open your React Native app on your device.
2. You'll see a red screen with an error. This is OK. The following steps will fix that.
3. Open the in-app Developer menu.
4. Go to Dev Settings → Debug server host for device.
5. Type in your machine's IP address and the port of the local dev server (e.g. 10.0.1.1:8081).
6. Go back to the Developer menu and select Reload JS.

**Comment by ajiprasetyo** [comment]
@JosephDev thanks its work too, if u want run project via wi-fi :)

**Comment by rajathithan** [comment]
This can be resolved by the dev settings inside the emulator , please visit my site for more information,

http://gadoth.com/react-native-series-post-1-installation-setup/
