### ISSUE TITLE
AssertionError in 0.26.0 -> 0.26.2

### ISSUE THREAD

**Issue by 9mm** [facebook/react-native#8373]
Hello,

I upgrade from `0.26.0` to `0.26.2` several weeks ago.

The largest error I have right now in sentry (with over 7,000 exceptions vs 2nd error place @ 1,000 exceptions) is the following:

```
java.lang.AssertionError: null
    at java.lang.Thread.run
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    at android.os.Looper.loop
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    at android.os.Handler.dispatchMessage
    at android.os.Handler.handleCallback
    at com.facebook.react.uimanager.events.EventDispatcher$DispatchEventsRunnable.run
    at com.facebook.infer.annotation.Assertions.assertNotNull
```

When I look at the 'affected releases' section of sentry, I can see the only version this error appears on is the latest version of my app, where I upgraded from `0.26.0` to `0.26.2`.

I'm about to attempt to update to `0.29.0-rc.0`, so I'll see how that goes (it will take time to gather crash reports). I figured this might be helpful though to see what changed going from `0.26.0` -> `0.26.2`

**Comment by 281330** [comment]
Did you do `react-native upgrade`?

**Comment by 9mm** [comment]
Yes

**Comment by grabbou** [comment]
FYI that's the assertion that fails -> https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/EventDispatcher.java#L312
