### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by bhatti** [facebook/react-native#838]
I am using react-native 0.3.4 and trying to integrate a 3rd party library lighstreamer (http://www.lightstreamer.com/distros/Lightstreamer_Allegro-Presto-Vivace_6_0_20150213/Lightstreamer/DOCS-SDKs/sdk_client_javascript/tools/generator.html). I tried using namedspace version of the library but my application gets "Can't find variable: document" when I include that library using require tag. Is there a way to fix this?

**Comment by siuying** [comment]
There is no ``document`` in React Native's JavaScriptContext, its not a web page. It might be easier to work to write a native module and bridge it.

**Comment by brentvatne** [comment]
@bhatti - @siuying is right, there is no `document` var in the context where JS executes for react-native. I had a look at the source that was generated and unfortunately it was minified, so it was very tough to tell what might be required to add support for it. If you're in the market for a websocket library, you might want to have a look at [RCTWebsocket](https://github.com/tptee/RCTWebSocket) and keep an eye on #619. Good luck!

**Comment by ustcqidi** [comment]
I am using react-native 0.33.0.  I have not tried any 3rd party library, but my application gets "Can't find variable: document".  Is there a way to fix this?  

This is the stack trace , which is captured and sent from online customer's Device.  I have not reproduced locally.

Error Domain=RCTErrorDomain Code=1 "Unhandled JS Exception: ReferenceError: Can't find variable: document" UserInfo={NSLocalizedFailureReason={"line":1,"column":43,"sourceURL":"http://static.iqiyi.com/js/demo/PaopaoSignCalenderRN/index.ios.bundle.js"}, NSLocalizedDescription=Unhandled JS Exception: ReferenceError: Can't find variable: document, RCTJSStackTraceKey=(
        {
        column = 0;
        file = "http://static.iqiyi.com/js/demo/PaopaoSignCalenderRN/index.ios.bundle.js";
        lineNumber = 1;
        methodName = "";
    }
)}
