### ISSUE TITLE
SIGSEGV crash on Android

### ISSUE THREAD

**Issue by rahuljiresal** [facebook/react-native#8386]
This issue seems somewhat related to #6760 , but different enough for a different issue.

The main differences are --
1. The crash happens when there are a lot of components (e.g. 1000 Views nested inside each other). But in the particular instance of our app, the crash also happens when there are relatively fewer components (~100) and we receive a 4xx, 5xx level response from a HTTP call. I have not been able to reproduce this in an isolated project with ~100 components and failed HTTP requests.
2. I am experiencing the crash when I'm NOT connected to Chrome Debugger. It works fine when connected to the debugger.

All I see is this, without a stack trace whatsoever.
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbbadbeef in tid 27250 (mqt_js)`

Since the issue happens when I'm not connected to the debugger, it makes it more serious because I cannot distribute the app. Any leads on how to debug this would be helpful.

**Comment by fab1an** [comment]
See my comment here: https://github.com/magicismight/react-native-svg/issues/38#issuecomment-228360483

**Comment by rahuljiresal** [comment]
So, I created a barebones project to replicate the crash. I put breakpoints at all 3 lines you mentioned in the comment, it didn't stop at any of those before the crash. It stopped at those lines during startup of the app, probably when it was laying out the components.

Here's the dummy app I made, in case you wanted to see if you can reproduce → https://github.com/rahuljiresal/DummyCrashTest

**Comment by fab1an** [comment]
Seem to be related to: #4172

**Comment by rahuljiresal** [comment]
Checked that. Not using Google Analytics. Also, the shared libraries are the same for 64 bit and 32 bit architectures. Pretty sure that's not the issue.

**Comment by rahuljiresal** [comment]
So, after poking around, I found that this line is the culprit → https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/jni/react/JSCHelpers.cpp#L40

I added log statements before and after the line. It never returns from the function `JSEvaluateScript`. Crash happens when it is inside that function. The function `JSEvaluateScript` is not defined anywhere, looks like its a third-party ndk library that gets downloaded(?). Kinda stuck at this point.

**Comment by rahuljiresal** [comment]
FWIW, also tried disabling JIT like mentioned in this comment https://github.com/facebook/react-native/issues/6760#issuecomment-227827239

Didn't work.

**Comment by rahuljiresal** [comment]
I found the problem. It was the npm dependency we were using called [qwest](https://github.com/pyrsmk/qwest) as a wrapper over XHR. I swapped it with another wrapper [axios](https://github.com/mzabriskie/axios) and couldn't reproduce the crash.

There was no invalid JS in qwest, no unexpected exceptions or anything suspicious that I could see. My guess is that the android-jsc simply did not like that JS code and crashed. It seems to be okay with this other wrapper.

I am wondering if it has something to do with the fact that the sources android-JSC is built from is over 20 months old. JavaScriptCore crashing on valid JS is worrisome.

**Comment by asata** [comment]
"AndroidManifest.xml" add application line

> android:hardwareAccelerated="false"

**Comment by hellogerard** [comment]
[This comment](https://github.com/react-native-community/react-native-svg/issues/38#issuecomment-243656198) in the `react-native-svg` repo solved this crash for me. To save you from clicking thru, I added:

```js
shouldComponentUpdate() {
  return false;
}
```

to all my SVG components.  Note this may not help you if you are animating your SVGs.

**Comment by tomfrew** [comment]
We are getting the same issues.

App crashes on Android as soon as an HTTP request returns a 4xx or 5xx response. (In our case triggered by a request to get some analytics settings that doesn't exist so 404s)

When debugging via chrome the issues doesn't happen. We also can't reproduce the crash when the app is built with production flags.

We're tried various suggestions from the related issue threads but so far nothing has worked.

It crashes very reliably for us so if anyone has any debugging suggestions then please let me know!

**Comment by AlbertBrand** [comment]
We might have found the cause for this crash, see PR #11804. Can you check whether the proposed fix solves this crash?

**Comment by shahen94** [comment]
I have this issue too, But it works fine when debugging via Chrome

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/sigsegv-crash-on-android
