### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by wfkbyni** [facebook/react-native#839]
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! react-native@0.3.11 start: `./packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native@0.3.11 start script './packager/packager.sh'.
npm ERR! This is most likely a problem with the react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Desktop/sych_github/react-native/npm-debug.log
MacdeMac-mini:react-native mac$ npm install
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /Users/mac/.npm/source-map/0.1.31
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/mac/.npm/source-map/0.1.31'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/mac/.npm/source-map/0.1.31']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/mac/.npm/source-map/0.1.31',
npm ERR!   parent: 'react-native' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/Desktop/sych_github/react-native/npm-debug.log

**Comment by LeezQ** [comment]
try running this command again as root/Administrator.

**Comment by Iragne** [comment]
sudo npm start

**Comment by frantic** [comment]
Most likely your npm installation is weird, it happens sometimes when you install package with sudo or get node from official website (not brew). This might help (see the bottom of the page) http://facebook.github.io/react-native/docs/troubleshooting.html#npm-locking-error

**Comment by brentvatne** [comment]
@wfkbyni - feel free to ping me if the above solutions don't fix the problem, otherwise closing the issue
