### ISSUE TITLE
in the maven center the last version is 0.20.1

### ISSUE THREAD

**Issue by iceskyblue** [facebook/react-native#8391]
in the maven center the last version is 0.20.1
http://facebook.github.io/react-native/releases/0.26/docs/embedded-app-android.html#content
when Integrating react native to an existing Apk, I can only get the last version react native is 0.20.1.
why???????????

**Comment by simonvaucher** [comment]
The upgrade instructions are buried somewhere.
Basically, you should update the project's build.gradle to:
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$projectDir/../../node_modules/react-native/android"
        }
    }
}
```
and the app's build.gradle to:
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
...
    compile 'com.facebook.react:react-native:+'  // From node_modules
}
```

Works up until 0.25.1, I cannot ensure anything for later versions.

**Comment by ide** [comment]
@simonvaucher is right - the AAR is distributed with npm, not Maven.

**Comment by npomfret** [comment]
Hmm, so if I'm building a native module, where do I get the latest react-native jar file from if not maven?
