### ISSUE TITLE
reactive run-android failed "could not install *smartsocket* listener: Address already in use"

### ISSUE THREAD

**Issue by node-rookie** [facebook/react-native#8401]
:app:assembleDebug UP-TO-DATE
    :app:installDebug
    05:53:18 E/adb: error: could not install *smartsocket* listener: Address already in use
    05:53:18 E/adb: ADB server didn't ACK
    05:53:18 E/adb: * failed to start daemon *
    05:53:18 E/adb: error: cannot connect to daemon
    05:53:18 E/ddms: '/Users/bjhl/Library/Android/sdk/platform-tools/adb,start-server' failed -- run manually if necessary
    :app:installDebug FAILED

 the simulator i used is genymotion

**Comment by node-rookie** [comment]
i had solved this problem; when i check my system path , i found  two android sdk paths; delete one of them, then it works well

**Comment by aryeharmon** [comment]
@node-rookie i have:
```
export PATH=$PATH:/usr/local/android-sdk-linux/
export PATH=$PATH:/usr/local/android-sdk-linux/tools
export PATH=$PATH:/usr/local/android-sdk-linux/platform-tools
export PATH=$PATH:/usr/local/android-sdk-linux/build-tools
```

in ~/.bashrc

when i removed the last 3 i still get the error

**Comment by ihormihal** [comment]
I cannot find a solution too. Setting ADB path in Genymotion to Android SDK has no effect.

**Comment by Sinapse87** [comment]
I have exactly the same problem. Happened to me after using my pixel. I spent over three hours now!

**Comment by YL2014** [comment]
I have the same problem, and it no work for me

**Comment by Sinapse87** [comment]
Guys, I might have found the solution, are you all using Android Studio IDE?

**Comment by YL2014** [comment]
I had solved that. Just set the host `127.0.0.1 localhost`, then it runs ok. Actually, I also close my proxy, the network maybe a case.

**Comment by jsroyal** [comment]
Just check whether your path is correct set or not
![image](https://cloud.githubusercontent.com/assets/10773353/24396425/c6b88a98-13c0-11e7-833e-a59c503b444a.png)

**Comment by daveamol** [comment]
I had the same issue and just did 
```
ps -ef | grep 5037
505 11809     1   0  4:44PM ??         0:07.17 adb -P 5037 fork-server server --reply-fd 4
```
Got another adb process already running but not sure why it was started

Just did a kill -9 11809 and started adb server and its working fine now

**Comment by marlonoso** [comment]
@Sinapse87 Yes, the problem began once I installed Android Studio IDE

**Comment by degaray** [comment]
I have the same problem. It also started when I updated to a newer Android Studio IDE

**Comment by jsroyal** [comment]
Can you post here your log what is problem you facing?

**Comment by degaray** [comment]
I had another process  running on the same port as adb. I killed it and it worked fine.

**Comment by jsroyal** [comment]
@degaray Good . GO for it.

**Comment by tanghb** [comment]
@YL2014 Thanks, it works.

**Comment by this-miguel** [comment]
Also, if there is anyone still having this problem, take a look at the response of this guy https://stackoverflow.com/a/45456154/6115334  for me that solved the problem. I had an `adb` old version that was being found first in my path variable, It was not the version I was expecting to be executed, this old version is the one the always was having the port taken.

**Comment by pdescham49** [comment]
Same issue windows 7 without the Android SDK installed; using the genymotion adb. 

All i did to fix was add the 'C:\Program Files\Genymobile\Genymotion\tools' to the system path.. Presto..

**Comment by wikieswan** [comment]
the adb version on your system is different from the adb version on the android sdk platform-tools
[link](https://stackoverflow.com/questions/38512025/react-native-run-android-mismatch-version-adb-server-version)
it works for me

1 check sys adb version

    # adb version
    Android Debug Bridge version 1.0.39

2 check sdk adb version

    # cd /Users/wan-mac/Library/Android/sdk/platform-tools
    # ./adb version
    Android Debug Bridge version 1.0.32

3 copy

    # sudo cp /Users/wan-mac/Library/Android/sdk/platform-tools/adb /usr/local/bin

that's all

**Comment by naserbeheshti** [comment]
Great job @wikieswan. It works. Thanks.

**Comment by joelmellon** [comment]
I'm using Genymotion's adb, and needed to add it to my PATH environment variable. eg. in `~/.bash_profile`:

`export PATH=$PATH:/Applications/Genymotion.app/Contents/MacOS/tools`

**Comment by xleotranx** [comment]
Great job @wikieswan.  Thanks.

**Comment by 77ukhtar** [comment]
@wikieswan thank you, works now 
it sucks when this happened to you close to a deadline :disappointed:

**Comment by dpnthanh** [comment]
@wikieswan thanks, you solutions worked for me

**Comment by syukurzay** [comment]
I think this will solve your problem
write cmd: ps -ef | grep 5037

**Comment by theripper225** [comment]
great's job @wikieswan i resolved my problem trough your solution. thx

**Comment by pankaja92** [comment]
@wikieswan I get this on my SDK adb version and sys adb version both.

```
Android Debug Bridge version 1.0.36
Revision 1:7.0.0+r33-2

```
And have set to  _Use custom Android SDK tools_ in Genymotion. 

But when I run start Genymotion and run `adb devices` to check. This is what I'm getting.

```
List of devices attached
adb server version (39) doesn't match this client (36); killing...
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
```

Is there anyway to fix this ?

**Comment by sunilkumarc** [comment]
Following the steps here - https://docs.expo.io/versions/latest/guides/genymotion.html#find-genymotions-copy-of-adb-on-macos worked for me!

**Comment by kangdawei** [comment]
1.Genymotion settings=> ADB=>use customer Android tools
2.close Android Studio
3.yarn start
