### ISSUE TITLE
Debugging files sometimes get messed up

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#8407]
It is not always happen. But sometimes when you open js debugging the file shows wrong.
For example if you open file A in chrome develop tools , you maybe see another file B.
The file B is the file that is required on first line of file A. Just like 
import {something} from 'B' or 
var something = require('B')

It seems that the chrome debugger fetch the source code of file B and place it onto the file A.

It happens on React-native 0.24 and I upgrade to 0.27 the problem is still there.

**Comment by jaygarcia** [comment]
I've had the same issue and just kinda lived with it. :(

**Comment by narychen** [comment]
@jaygarcia It's really painful especially when you have some hard to debug bugs and just could not open the target source code file.

**Comment by jaygarcia** [comment]
I feel your pain. I've just been dealing w/ it. :(

**Comment by jayshah123** [comment]
Experiencing chrome (remote debug) sourcemapping problem in debugging, 
even with a simple file added debugger; statement, the breakpoint is off by 4-5 lines, 
Using this in RN 0.26.3. Any tips for finding the root cause of the problem ?

**Comment by yueshuaijie** [comment]
Same problem with 0.27.2.
Is 0.28.0 OK?

**Comment by narychen** [comment]
I think there may be something wrong with hot reloading. Because in the old version where there was no hot reloading, nothing wrong happened. After I upgraded to 0.24, it happened and I switched my version to 0.27.2, the problem is still there. 
Don't know if 0.28.0 is ok.

**Comment by Dev-Simon-Chen** [comment]
i  met the same problem with 0.27.2,and after updating to 0.28 ,the problem stil there.l

**Comment by sunnylqm** [comment]
Not only files get messed up, console.log and watched values are also misleading(wrong).
Anyone aware of this serious issue? @mkonicek @ide @satya164

**Comment by flare216** [comment]
I'm expering this issue too! RN 0.27.2

**Comment by limulidae** [comment]
'turn off hot reloading' is a workaround.

**Comment by narychen** [comment]
@limulidae how to turn off it ? I

**Comment by narychen** [comment]
@limulidae  I never enable hot reloading. You mean remove it from the source code?

**Comment by limulidae** [comment]
@narychen 
I have a blind combination, not 100% success, but better than 100% fail.
(I dont know which steps are necessary btw.)

(1) turn off live reload or hot reload
http://imgur.com/O0EzsLc
(2) run packer by yourself.
$node_modules/react-native/packager/packager.sh --skipflow  --nonPersistent --reset-cache
(3) remove all breakpoints, close all chrome source window.

**Comment by narychen** [comment]
This problem is due to Chrome's bug.
Using Chromium(chrome canary) could fix it.

**Comment by satya164** [comment]
@narychen Can you link to the Chromium bug?

**Comment by narychen** [comment]
@satya164 I changed to chrome canary and all messed up problems gone. 
link is https://bugs.chromium.org/p/chromium/issues/detail?id=611328
