### ISSUE TITLE
[iOS] Integrating into existing app: RCTJSCWrapper.h 'string' file not found

### ISSUE THREAD

**Issue by actonw** [facebook/react-native#8414]
I'm attempting to integrate a React Native component into an existing Swift app. I am following the instructions here: https://facebook.github.io/react-native/docs/embedded-app-ios.html

1. The documentation is unclear on the steps to bridge the RN view to the Swift app. It says to create a ReactView.h, and then a ViewController.m, and then goes on to say "For Swift apps there is no need for that." No need for what - the ViewController.m, the ReactView.h, or both???? Very poor wording.

2. Either way, when I create a ReactView.swift file:

```swift
import UIKit
import React

class ReactView: UIView {

  let rootView: RCTRootView = RCTRootView(bundleURL: NSURL(string: "http://localhost:8081/index.ios.bundle?platform=ios"),
    moduleName: "SimpleApp", initialProperties: nil, launchOptions: nil)

  override func layoutSubviews() {
    super.layoutSubviews()

    loadReact()
  }

  func loadReact () {
        addSubview(rootView)
        rootView.frame = self.bounds
  }
}
```

And import it into a View in Xcode, when I build the project I get the following error:

`RCTJSCWrapper.h: 'string' file not found`
`ReactView.swift: Could not build Objective-C module 'React'`

**Comment by actonw** [comment]
Downgrading React to 0.27 seems to at least allow me to build without errors. I note that RCTJSCWrapper.h does not exist in this version.

**Comment by hjhcn** [comment]
I meet some errors.

**Comment by nicolai86** [comment]
Same issue here. Using cocoapods for dependency management. It's due to the ObjC++ introduced, but the `React.podspec` file seems to be configured correctly.

**Comment by 520xiaopohai** [comment]
same  question +1

**Comment by actonw** [comment]
Maybe @alexeylang can provide some insight?

**Comment by luhui** [comment]
Got same issue in both OC-based and swift-based project, should be change something in build settings?

**Comment by alexeylang** [comment]
You need to add `-lc++` flag to fix this error (see [this commit](https://github.com/facebook/react-native/commit/8aa82d3b33c00fb7f226bb732c472feb2b955adf) for example).
Do you guys use Cocoapods? I don't see this flag in podspec

**Comment by luhui** [comment]
@alexeylang Add -lc++ flag still not working on version 0.28.
And yes, I am using Cocoapods.
I just create a clean project, follow [this](https://facebook.github.io/react-native/docs/embedded-app-ios.html) guideline which @actonw mentioned at the beginning, still failed with same issue.

**Comment by sdcooke** [comment]
We've managed to find a workaround that works for now.

We're seeing the same issue (on the 0.29 RC, but I assume it would be the same on 0.28) - also using Cocoapods. Under the suspicion that it's to do with importing ObjC++ in Swift files we:
 * updated `HEADER_SEARCH_PATHS` to include `node_modules/react-native/React/Base`
 * removed all `import React` lines
 * added the necessary `#import "RCTBridgeModule.h"` lines for all of the modules we're using in our bridging header

It seems to work now but we'd much rather use `import React` like we do with all of our other pods if possible - particularly as we use more of the API, not having to add each line to the bridging header would be great.

**Comment by nicolai86** [comment]
In my case the error seems from having dependencies which require React, e.g. `BVLinearGradient`.

A CocoaPod compatible workaround looks like this: 

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
use_frameworks!

workspace 'one'

target 'one' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    #
  ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'Fabric'
  pod 'Crashlytics'
end

post_install do |installer|
  targets = installer.pods_project.targets.select { |t| %w(BVLinearGradient).include?(t.name) }
  targets.each do |target|
    target.build_configurations.each { |configuration|
      configuration.build_settings['ALWAYS_SEARCH_USER_PATHS'] = 'YES'
    }
  end
end
```

notice the `post_install` hook which overrides the generated xcconfig file.

**Comment by actonw** [comment]
So it sounds like this is a cocoapods config issue?

**Comment by rh389** [comment]
I think more fundamentally this is because `RCTJSCWrapper.h` has a C++ dependency in the header itself (a typedef using `std::string`), effectively in React's public API, which means the `React` module exposed by the Pod isn't a valid Objective-C module and one result is that it can't be imported by swift. 

It looks like it ought to be straightforward to change this signature to a `const char *` and restore Objective-C compatibility, but I don't well enough understand what this JSCWrapper is actually doing or what it's for.

**Comment by alexeylang** [comment]
Alright, I've changed the API in https://github.com/facebook/react-native/commit/85983d0ae4fac0fc22048bd0d729cdc3ca755d91. Can you guys test it now?

**Comment by rh389** [comment]
That works for me - thanks. Can we expect it to land in 0.29?

**Comment by okrasnob** [comment]
If there is a need to use 0.28, you may use the following "post_install" script in "Podfile"
<pre><code>
post_install do |installer|
  # installer is not used here
  
  def searchAndReplaceInFile(searchDir, searchFileNamePattern, searchPattern, replacePattern)
    print "Searching recursively: " + searchDir + " for '#{searchFileNamePattern}'\n"
    Dir.glob("#{searchDir}/**/#{searchFileNamePattern}") do |foundFileName|
      print "Modifying '" + foundFileName + " with: \n"
      print "  searchPattern: '" + Regexp.escape(searchPattern) +
            "', replacePattern: '" + Regexp.escape(replacePattern) + "'\n"
      foundFile = File.read(foundFileName)
      foundFileNew = foundFile.gsub(/#{searchPattern}/, replacePattern)
      File.open(foundFileName, "w") { |file| file << foundFileNew }
    end
  end

  workDir = Dir.pwd
  supportFilesDirName = "#{workDir}/Pods/Target Support Files"

  # "Comment out the line: #import "RCTJSCWrapper.h" in "React*umbrella\.h" files
  # "\1" in regex is the first matched regex group: "#import "RCTJSCWrapper.h"
  searchAndReplaceInFile(supportFilesDirName,
                       "React*umbrella\.h",
                       "(^.*RCTJSCWrapper.h.*$)",
                       '// \1')

  # add 'exclude header "RCTJSCWrapper.h"' to "React*modulemap" to remove warning:
  # &lt;module-includes&gt;:1:1: Umbrella header for module 'React' does not include header 'RCTJSCWrapper.h'
  searchAndReplaceInFile(supportFilesDirName,
                         "React*modulemap",
                         "(^.*umbrella header.*$)",
                         "\\1\n  exclude header \"RCTJSCWrapper.h\"\n")
end

</code></pre>
