### ISSUE TITLE
JavaScript's .sort() method works in simulator but not on iOS device

### ISSUE THREAD

**Issue by ademars94** [facebook/react-native#8423]
I am trying to sort a list of events by date using JavaScript's built in .sort() method.  I am using a ListView to display the data.  In `dataSource.cloneWithRows()` I pass in a function that is supposed to return a sorted array of events.  For some reason this works fine in the simulator but doesn't work on my iOS device.  Any help is appreciated!

**Comment by ide** [comment]
Date objects are processed differently on JSC and V8. Not much we can do about that. I'd recommend using a custom comparator function to make sure to perform the same comparisons on all platforms.

**Comment by ademars94** [comment]
Well I wrote a custom sorting algorithm that's still not working.  It's taking the array I want to sort, looking at the startDateTime property `new Date(arr[index].startDateTime)` on each item in the array, and comparing it with the next index in the array.
```
bubbleSortDates = (arr) => {
    for(var i = arr.length - 1; i >= 0; i--) {
      for(var j = 1; j <= i; j++) {
        if (new Date(arr[j - 1].startDateTime) > new Date(arr[j].startDateTime)) {
          var temp = arr[j - 1];
          arr[j - 1] = arr[j];
          arr[j] = temp;
        }
      }
    }
    return arr;
  };
```
I really can't understand how this one doesn't work.  Logically it makes complete sense, and this works on the simulator as well.  What is it about the JavaScript environment when running on iOS that might be breaking this?

**Comment by ademars94** [comment]
@ide

**Comment by ide** [comment]
I forget the specifics but generally you don't want to use `new Date(string)` if that's what's happening. Use `new Date(number)`.

**Comment by ademars94** [comment]
@ide I tried using `new Date("dateString").getTime()` which returns an integer, and compare using that, but still no luck.  I've tested my function in Chrome and Safari and it seems to work fine in Safari's JSC environment.  I'm starting out with a date string because I am getting JSON back from a REST API, so I'm not sure how I would pass a number to `new Date()`

**Comment by ademars94** [comment]
@ide The sort method works fine on my device provided I have it connected to the remote debugger in Chrome, loading the JS from my computer's IP address.  When I try to use the static JS bundle, it no longer works.

**Comment by mkraft** [comment]
I'm getting this bug too. Using a custom comparator doesn't work without the debugger using JavaScript's `sort()`.

**Comment by ademars94** [comment]
If your issue has to do with sorting dates, you're in luck.

Originally, I was trying to directly compare two JS Date objects here:

```javascript
// this code exists in a loop, see earlier post
if (new Date(arr[j - 1].startDateTime) > new Date(arr[j].startDateTime)) { 
  //fun stuff in here
}
```

And since the different runtime environments handle dates differently, it was breaking.

Definitely take a look at the Moment.js library.  I am using Moment to make sure the formats stay consistent when comparing dates and when I'm hopping between the dev server and static JS bundle.

So this line:

```javascript
let aDate = moment(array[j - 1].startDateTime, moment.ISO_8601);
```

Will give me back the startDateTime (which is a JS Date object), formatted as Moment's [.ISO_8601 format](http://www.iso.org/iso/home/standards/iso8601.htm).  Now I can compare dates all day long until my fingers fly off.

Here's my updated block o' code 4 reference:

```javascript
sortByDate = (array) => {
    for (let i = array.length - 1; i >= 0; i--) {
      for (let j = 1; j <= i; j++) {
        // Use moment to format dates before they are compared
        let aDate = moment(array[j - 1].startDateTime, moment.ISO_8601);
        let bDate = moment(array[j].startDateTime, moment.ISO_8601);
        if (aDate > bDate) {
          let temp = array[j - 1];
          array[j - 1] = array[j];
          array[j] = temp;
        }
      }
    }
    return array;
  };
```

**Comment by mcconkiee** [comment]
had the same issue, and dug up [this gem](https://github.com/facebook/react-native/issues/3982#issuecomment-154842833)

**Comment by halaharr** [comment]
Hi,
   I am having same issue. I am trying to sort contacts and show in FlatList. It works in simulator but when I publish the app for testing on devices it does not sort. Here is my sample code. Please let me know if you guys were able to solve this issue.


        phoneContacts.slice.sort((a, b) => {
          const aName = (a.buttonTitle === '+Add' ? '0' : '1') + a.firstName.toLowerCase();
          const bName = (b.buttonTitle === '+Add' ? '0' : '1') + b.firstName.toLowerCase();
          if (aName < b.bName) return -1;
          if (aName > bName) return 1;
          return 0;
        });

Thanks
