### ISSUE TITLE
[bug] Android: ScrollView does not automatically adjust height when elements are removed

### ISSUE THREAD

**Issue by cinupina** [facebook/react-native#8424]
**RN Version:** 0.28, and also 0.24 on rnplay.org
**Platform:** Android only, tried Kitkat and Marshmallow (iOS is fine)
**Dev machine:** Mac OS X El Capitan

On Android (but not iOS), ScrollView does not readjust height when the content height decreases, until the user taps or scrolls. When the user is viewing the bottom of the ScrollView, this causes whitespace in the place of the removed content.

Minimal code snippet: [scroll down, then tap on Remove button to repro]
```
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  ScrollView,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
} = React;

var SampleApp = React.createClass({
  getInitialState: function() {
  	return { count: 50 }
	},

  remove: function() {
    this.setState({ count: 20 });
  },
 
  createElements: function(count) {
  	var elements = [];
  	for (var i = 0; i < count; i++) {
  		elements.push(<Text key={i}>{i}</Text>);
		}
    return elements;
	},

  render: function() {
    return (
      <View style={styles.container}>
        <ScrollView>
      		{this.createElements(this.state.count)}
					<TouchableHighlight onPress={this.remove}>
        		<Text>Remove</Text>
      		</TouchableHighlight>
        </ScrollView>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
    marginTop: 20,
  }
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by mangogogos** [comment]
+1 this has driven me nuts for ages

**Comment by iniestano8** [comment]
+1

**Comment by iniestano8** [comment]
Actually, iOS is not fine when you change the count to 40 from 50,  there is a blank area appears,  -_-!
![image](https://cloud.githubusercontent.com/assets/5787530/16863168/9f96f934-4a82-11e6-801b-1bc87f06fa29.png)

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/bug-android-scrollview-does-not-automatically-adjust-height-when-elements-are-removed

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (68/60 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46706)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvt-0004Kn-NN
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:59 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvt-00040W-0G
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:57 -0700
Date: Thu, 27 Oct 2016 15:13:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606436;
	bh=hgrGosxuJG5HOLFrSYN3Emj6lc6viOEQvxqU63pkV8U=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=uckeOfNO7yV9eGRn9UlaK2v5JzyGEKiDhKgh2W+k9OSvZ884MIps59xEG3OhekQWI
	 7hcxAzYgP3xDOfc5Y3OrLr8Cm6mEVmY1SKaysp+JFWXAubl9WA5okrzeqvq4dZqsCf
	 5qlSIFeie1kzgdG+P0JQfXqdgNZkyhdhfzf6tEvc=

**Comment by sorcerdu** [comment]
+1
