### ISSUE TITLE
How to downgrade properly to a lower version of RN

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [facebook/react-native#8430]
Refer [here](http://stackoverflow.com/questions/38024203/proper-mechanism-to-downgrade-react-native) on the issue.

I wanted to use [enzyme](https://github.com/airbnb/enzyme) for shallow rendering and testing RN components but enzyme happens to want React 15.1.0, while RN 0.26.0 (Which was what I was using) wants React 15.0.2.

And then I upgraded (ran `react-native upgrade`) after npm installing RN 0.26.3 then realized I should be at 0.28 for newer React version. But after that [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) broke and I got `Failed to build DependencyGraph: @providesModule naming collision:`.

So I just reverted all my changes from git. And since then had been unable to do an `npm install`.
I keep running into 
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.26.3 wants react@15.0.2
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0

```
So whats RN recommended way to downgrade ? (Note that package.json has all the right versions I want RN 0.26.0 and React 15.0.2, but still the above error)

**Comment by grabbou** [comment]
I am going to close this issue since there's already StackOverflow question (great!) and it has more details.

PS. I've already answered there, hope it helps.

**Comment by levarberry** [comment]
Would have been nice to include a link before closing the ticket.   This is the first result coming up on Google.

**Comment by lindseybaron** [comment]
[Proper mechanism to downgrade react-native](http://stackoverflow.com/questions/38024203/proper-mechanism-to-downgrade-react-native) maybe?

**Comment by chetankotkar** [comment]
following worked for me 
 
npm install react-native@x.x.x   for ex: npm install react-native@0.43.4

**Comment by crajesh238** [comment]
How to downgrade globally?
