### ISSUE TITLE
[Android] App Crashes On Exit ( XMLHttpRequest related )

### ISSUE THREAD

**Issue by tje3d** [facebook/react-native#8433]
If a request is in processes and you exit the app, application will crash.

Sample Code:
```
import React from 'react';
import { View } from 'react-native';

class Thecomp extends React.Component {

  constructor(props) {
    super(props);

    this.xhr = null;
  }

  componentWillUnmount() {
    if (this.xhr != null) {
      this.xhr.abort();
      this.xhr = null;
    }
  }

  componentDidMount() {
    this.xhr = new XMLHttpRequest();

    var url = "http://SOMEWHERE/";

    this.xhr.open('GET', url);
    this.xhr.send();
  }

  render() {
    return (
      <View>
        App Crash
      </View>
    )
  }

}

module.exports = Thecomp;
```

But this one wont get crash if you exit app after 2 sec:
```
import React from 'react';
import { View } from 'react-native';

class Thecomp extends React.Component {

  constructor(props) {
    super(props);

    this.xhr = null;
  }

  componentWillUnmount() {
    if (this.xhr != null) {
      this.xhr.abort();
      this.xhr = null;
    }
  }

  componentDidMount() {
    this.xhr = new XMLHttpRequest();

    var url = "http://SOMEWHERE/";

    setTimeout( () => {
      this.xhr.abort();
    }, 2000 );

    this.xhr.open('GET', url);
    this.xhr.send();
  }

  render() {
    return (
      <View>
        App Crash
      </View>
    )
  }

}

module.exports = Thecomp;
```

I don't sure but maybe something related to APP Exit or componentWillUnmount.

**Comment by tje3d** [comment]
To simulate the issue, you can use this URL ( this page response after 10 seconds ):
`http://tasoft.ir/github/delay.php`

**Comment by tje3d** [comment]
Found a workaround:
Abort request on "hardwareBackPress" event using BackAndroid.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-app-crashes-on-exit-xmlhttprequest-related-

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (72/60 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46756)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzswQ-0004Xd-56
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:14:31 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzswP-000448-Fb
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:14:30 -0700
Date: Thu, 27 Oct 2016 15:13:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606468;
	bh=RTJZpid+kEdQ+8XtHHHT0Ga4FCzMGZwlQ59AUqCV1+I=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1isOcUgD8fc8HZdykxyRFS2eL7QOvC82uxSygQ0n96PQfRG+yhWEx/QzKScGKNXos
	 xEguA7CtlUaROB6rZVWyZryNKsLD+YdTQlIFtfrXfa+S9Cad0Dwyk8pSKNquajou5k
	 adWXTq/nlKkOpxzI+aFDK9gBj+2+tTczRpHKgQrA=
