### ISSUE TITLE
[doc] Build from source: wrong location of `local.properties`?

### ISSUE THREAD

**Issue by antoinerousseau** [facebook/react-native#8439]
On this page:
https://facebook.github.io/react-native/docs/android-building-from-source.html
It says that I can create a `local.properties` file with the `sdk.dir` and `ndk.dir` variables, and put it at _the root of your react-native checkout_... at first I was confused, should I add it to `node_modules/react-native/`? But finally it worked when I put it in `android/`.
So unless I misunderstood something, the doc should be fixed.

**Comment by christopherdro** [comment]
Yes, local.properties are for your own project and belong in the `android/` directory. Will try and update docs to reflect this.

Thanks for reporting.

**Comment by antoinerousseau** [comment]
Thanks, let me know if you are too busy, I can make the PR.
