### ISSUE TITLE
NavigatePop without Animation

### ISSUE THREAD

**Issue by Vani-gurnani** [facebook/react-native#8440]
Currently NavigationCardStack and NavigationCar both forcefully use the Animation. We have a usecase where a User goes through a wizard on click of Edit Profile and when he/she is done we go back to main screen.

When we go back to main screen we see Animation of so many views popping back. 

**Check the following video in Slow Motion (When Clicking Skip >>). All Screens Show Popping Animation **

![out](https://cloud.githubusercontent.com/assets/13322122/16360932/d782ac32-3b30-11e6-8c7e-77929cc22c8e.gif)

**Comment by tkjone** [comment]
did you have any luck resolving this @Vani-gurnani ?  

I ran into the same issue with NavigationCardStack (RN-30).  I believe this issue could be resolved if we were provided access to the `ANIMATION_DURATION` constant here:  https://github.com/facebook/react-native/blob/c658cc545f0e8c508ab44389deed39801f4e472c/Libraries/CustomComponents/NavigationExperimental/NavigationCardStackPanResponder.js#L28

Does anyone know this is going to be a possibility?  The alternative solution is to just build a custom version of the `NavigationCardStack`.

**Comment by tkjone** [comment]
Thanks @satya164!  That was the approach I ended up using.  Curious as to why it was not provided as an option for the `NavigationCardStack` as this component already uses `NavigationTransitioner`.

**Comment by satya164** [comment]
@tkjone `NavigationCardStack` was recently migrated to use `NavigationTransitioner` and had a different implementation earlier.
