### ISSUE TITLE
ActionSheetIOS.showShareActionSheetWithOptions not able to share local image file

### ISSUE THREAD

**Issue by vinaydate** [facebook/react-native#8442]
I am trying to share a local image file with `ActionSheetIOS.showShareActionSheetWithOptions`.

I can display image from the local file with following jsx:

`<Image source={{uri: 'file:///' + this.path}} style={styles.png}/>`

But with same path (i.e. `'file:///' + this.path`) assigned to `url` key of the object parameter to `ActionSheetIOS.showShareActionSheetWithOptions`, does not share file. Only text assigned to `message` key of the parameter is shared.

react-native version: 0.27.2

I am running app on an **attached** iPhone 4S iOS 9.3.2 device.

Dev machine: Mac os x 10.11.5

**Comment by christopherdro** [comment]
You have a extra `/` in your file path.
Try `file://' + this.path`

**Comment by vinaydate** [comment]
@christopherdro, appreciate your help. I tried with `file://`, but it did not work either. The `this.path` is having value `/var/mobile/Containers/Data/Application/60127A89-D21F-4125-881E-D7D145830455/Documents/test.png`, if at all this helps.

And just a gentle reminder, I can display image with the same path and triple '/' after 'file'. So I was wondering, what is that makes `Image` to understand the path and not `ActionSheetIOS.showShareActionSheetWithOptions`?

**Comment by sheparddw** [comment]
I have the same issue. When emailing, only the subject/message carry through. There is no attachment.
If I share via Airdrop, the file transfers fine, but I get a strange file name. Example: (null)-257D026032E9-1.data
If I rename the file to the correct name and extension, the file works properly.
It is able to find the file just fine but not email it or airdrop with the name intact.
Any ideas?

**Comment by sheparddw** [comment]
Passing the file URL instead of the file contents to UIActivityViewController fixes the issue.
Created a PR with the fix: https://github.com/facebook/react-native/pull/9693

**Comment by lacker** [comment]
Looks like this is fixed now
