### ISSUE TITLE
[0.28.0] App crashes when cannot resolve request (after upgrading to RN 0.28.0, iOS)

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#8452]
Hi.

I've got the issue: when my iOS app is going offline and the user tries to make a request for data (while pressing button, for example), the app shows this screen and crashes after that:
<img width="312" alt="2016-06-22 18 10 06" src="https://cloud.githubusercontent.com/assets/4746464/16266050/b43b8f52-38a4-11e6-9ff3-7a6f28e075c8.png">

When Internet connection is on, app works perfectly.
I have a guess, what the problem is somewhere in Network module.

I've started get this error right after upgrading from 0.25.1 to 0.28.0.
I'm using MacOS 10.11.5, Xcode 7.3. 

UPDATE. In terminal I've got this error log:

```javascript
Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/a.khlebnikov/sites/www/drugstores/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:60:7
    at /Users/a.khlebnikov/sites/www/drugstores/node_modules/react-native/packager/react-packager/src/Server/index.js:241:10
    at tryCallOne (/Users/a.khlebnikov/sites/www/drugstores/node_modules/promise/lib/core.js:37:12)
    at /Users/a.khlebnikov/sites/www/drugstores/node_modules/promise/lib/core.js:123:15
    at flush (/Users/a.khlebnikov/sites/www/drugstores/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by satya164** [comment]
Can you share a reproducible example showing your bug?

**Comment by ryankask** [comment]
I'm not sure if the error log message ("Error validating module options: child "platform" fails because") is specific to this issue. I was seeing the same the same message for something else when I upgraded from 0.27 to 0.28. In my case, it seemed like this was masking the underlying problem.

That being said, other users are seeing the same message: https://github.com/facebook/react-native/issues/8297 Could this be related?

**Comment by alexHlebnikov** [comment]
Here is same problem error screen in Android emulator. 

![screenshot 2016-06-30 16 07 18](https://cloud.githubusercontent.com/assets/1951398/16484770/dba1ad9a-3edc-11e6-850b-66d99369d912.png)

@satya164 I'l try to do an example page soon.

**Comment by chiraggshah** [comment]
@satya164 
Maybe this might help to create an example app. I am facing a similar issue and it happened just after I used this library : https://github.com/corbt/react-native-keep-awake
Its just a simple library and can be used for recreating the issue. I agree with @ryankask that this error is masking some underlying problem

I get the following error when Remote JS Debugging is enabled: 
`Cannot read property 'activate' of undefined`
while the terminal shows : 
```
Error: Error validating module options: child "platform" fails because ["platform" must be a string]
    at /Users/chirag/Workspace/bigbinary/pukkasoft/racehero-mobile/node_modules/react-native/packager/react-packager/src/lib/declareOpts.js:61:13
    at /Users/chirag/Workspace/bigbinary/pukkasoft/racehero-mobile/node_modules/react-native/packager/react-packager/src/Server/index.js:227:20
    at tryCallOne (/Users/chirag/Workspace/bigbinary/pukkasoft/racehero-mobile/node_modules/promise/lib/core.js:37:12)
    at /Users/chirag/Workspace/bigbinary/pukkasoft/racehero-mobile/node_modules/promise/lib/core.js:123:15
    at flush (/Users/chirag/Workspace/bigbinary/pukkasoft/racehero-mobile/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
```

And the following error when the Remote JS debuging is disabled:
`undefined is not an object (evaluating '_reactNative.NativeModules.KCKeepAwake.activate')`
while the terminal just says `symbolicate`

**Comment by satya164** [comment]
cc @corbt any idea why this happens?

**Comment by chiraggshah** [comment]
@satya164 : Also I forgot to mention that the error occurs when I install the app on the simulator by running `react-native run-ios` but works perfectly fine if I run it from xcode

**Comment by satya164** [comment]
@chiraggshah Hmm. Might be an issue with build scripts.

cc @bestander can you ping someone who has knowledge about the iOS build scripts?

**Comment by chiraggshah** [comment]
Not sure if its just iOS related. It fails on android emulator as well.

**Comment by satya164** [comment]
@chiraggshah Does this happen if you reset the packager cache?

**Comment by chiraggshah** [comment]
@satya164 : Yes, I have tried that as well.

**Comment by chiraggshah** [comment]
@satya164 : Sorry, I thought you meant `react-native start --reset-cache`. Yes running `node_modules/react-native/packager/packager.sh --reset-cache` solved the problem on iOS. 
Thanks. :)

But I do see `Cannot read property 'activate' of undefined` still occurring on android although I dont see any error on terminal.

**Comment by alexHlebnikov** [comment]
Example code:
```var RCTNetworking = require('RCTNetworking');
var XMLHttpRequest = require('XMLHttpRequest');

class CustomXMLHttpRequest extends XMLHttpRequest {
    constructor() {
        super();
    }

    sendImpl(method, url, headers, data, incrementalUpdates, timeout) {
        this._subscriptions.push(RCTNetworking.addListener(
            'didSendNetworkData',
            (args) => this.__didUploadProgress(...args)
        ));
        this._subscriptions.push(RCTNetworking.addListener(
            'didReceiveNetworkResponse',
            (args) => this.__didReceiveResponse(...args)
        ));
        this._subscriptions.push(RCTNetworking.addListener(
            'didReceiveNetworkData',
            (args) => this.__didReceiveData(...args)
        ));
        this._subscriptions.push(RCTNetworking.addListener(
            'didCompleteNetworkResponse',
            (args) => this.__didCompleteResponse(...args)
        ));

        incrementalUpdates = false;

        RCTNetworking.sendRequest(
            method,
            url,
            headers,
            data,
            incrementalUpdates,
            timeout,
            this.__didCreateRequest.bind(this),
        );
    }
}

export default CustomXMLHttpRequest;
```

I need CustomXMLHttpRequest because this bug - https://github.com/facebook/react-native/issues/7646
The main idea is set ```incrementalUpdates = false;```
And this works till 0.29

**Comment by danieldunderfelt** [comment]
I also see this bug. I think it comes from the code that throws the yellowbox for unhandled promise rejections, but the `error` parameter of the `onUnhandled` method in `Libraries/Promise.js` on line 19 is undefined. So usually it works, but in some cases the error is undefined and that is not checked for.

**Comment by bestander** [comment]
Would you send a PR?
Cc me.

**Comment by lacker** [comment]
fixed
