### ISSUE TITLE
RefreshControl interferes with paginated horizontal ListView [Android] v0.28

### ISSUE THREAD

**Issue by maikokuppe** [facebook/react-native#8454]
A list view of this form sometimes results in being stuck between pages.

```
<ListView
  horizontal={true}
  pagingEnabled={true}
  refreshControl={<RefreshControl/>}
  [...] />
```

[Here](https://rnplay.org/apps/iZFsIA) is a complete code example. Note that it doesn't work online, since rnplay's version of react-native is too old.

When moving the finger to the side and then moving it down, the ListView gets stuck in the current position, because the refreshControl is triggered. The refresh action is not necessarily triggered. But the refresh symbol moves into view a little bit, which makes the ListView stick where it is.

I don't know how to handle this properly, but the ListView should at least snap back to a valid page position here.

A general practical usecase of this would be a list of elements of which the user may refresh each one individually.

**Comment by mangogogos** [comment]
+1

**Comment by CreepGin** [comment]
I can confirm the same behavior on my end with RN 0.34.1 (tested on android).

Basically if you stick a RefreshControl on top of any Horizontal scrolling, things break.

**Comment by lacker** [comment]
Are you interested in sending a PR to fix this?

It isn't clear to me whether the right answer is fixing this, or just making it clear that refresh controls are only intended to work vertically. I am inclined toward the latter but if someone has a fix in mind that would be a different story.

**Comment by maikokuppe** [comment]
I'm not planning to make a PR in the near future, since I'm currently working with non-RN related stuff.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/refreshcontrol-interferes-with-paginated-horizontal-listview-android-v028
