### ISSUE TITLE
'Reload' did not change when I modified a js file

### ISSUE THREAD

**Issue by hiphonezhu** [facebook/react-native#8461]
0.28.0 does not work while 0.27.0 works well.
When I init a React-Native project, after change a js file, reload does not work well

**Comment by Chanasit** [comment]
same as me

**Comment by satya164** [comment]
Can you provide more information on what exactly not working? Live reload? HMR?

**Comment by hiphonezhu** [comment]
@satya164 
 'Reload JS', there is no error happened on the terminal

**Comment by shtefanntz** [comment]
I confirm this as well. I've tried previous fixes before (restarting the server, resetting the cache), but it still doesn't react to file changes. 

Another thing noticed is the rather long time for the sever to start: 
[6:14:35 AM] <END>   Crawling File System (292668ms)

**Comment by dsibiski** [comment]
@hiphonezhu: Are you definitely enabling "Live Reload" in the simulator? The "Live Reload" setting is set and persisted for each app. If you build a new app it will default to not having it enabled. Can you verify that setting? You didn't mention if you were performing this step or not.

**Comment by hiphonezhu** [comment]
@dsibiski I am sure that I do not enabling "Live Reload", just 'reload js'

**Comment by jude-liu** [comment]
I have the same problem whether enable "Live Reload" or "Hot Reloading", or both of them.

**Comment by gapgag55** [comment]
I reloaded not changing. same!!

**Comment by arthur-xavier** [comment]
@satya164, I believe this is the same as #8635

**Comment by shtefanntz** [comment]
Still reproducing in RN 0.29 :(

**Comment by shtefanntz** [comment]
Apparently, the fix isn't related to RN.
I followed the instructions from @InnerPeace080 in #7257 and everything works as before

**Comment by xiDaiDai** [comment]
+1

**Comment by micsay** [comment]
+1,thanks

**Comment by vzhen** [comment]
anyone solution?  i have the same issue on 0.30 to 0.32

**Comment by guilhermebruzzi** [comment]
Same issue on 0.32

**Comment by togayther** [comment]
same issue on android device with react-native 0.32.

finally, i found method to solve this problem.

in file "react-native\packager\react-packager\src\node-haste\FileWatcher\index.js"
you can increase "MAX_WAIT_TIME" variable. such: 360000.

and change function "_createWatcher"

to
```
_createWatcher(rootConfig) {
    const watcher = new WatcherClass(rootConfig.dir, {
      glob: rootConfig.globs,
      dot: false,
    });

    return new Promise((resolve, reject) => {
      const rejectTimeout = setTimeout(
        () => reject(new Error([
            'Watcher took too long to load',
            'Try running `watchman version` from your terminal',
            'https://facebook.github.io/watchman/docs/troubleshooting.html',
          ].join('\n'))),
        MAX_WAIT_TIME
      );

      watcher.once('ready', () => {
        clearTimeout(rejectTimeout);
        resolve(watcher);
      });
    });
  }
```
that's all and work for me.

**Comment by af7** [comment]
I also have exactly the same problem on v0.32:  "the hot reload and live reload options are not appearing."

@togayther Does your solution solves this problem too?

**Comment by togayther** [comment]
yes, its work for me. @af7

**Comment by davidaurelio** [comment]
We only support HMR for React components, with all the limitations of https://github.com/gaearon/react-transform-hmr#readme

**Comment by omhybrid** [comment]
i have same issue please give me solution
