### ISSUE TITLE
Re-render ListView slow when once row changed

### ISSUE THREAD

**Issue by Shinichi52** [facebook/react-native#8462]
Hi All,
my repo using listView at WatchList.js
when data changed about 8-10/1 second list view very slow? 
You can clone at https://github.com/Shinichi52/ExpamleApp.git

**Comment by louisgv** [comment]
@Shinichi52 please reformat your  issue.  Put all the code in a gist or a public repo so those who wanted to help can check it out.

**Comment by Shinichi52** [comment]
@louisgv  thanks for feedback. I reformat my issue. My repo: https://github.com/Shinichi52/ExpamleApp.git.

**Comment by sibelius** [comment]
@Shinichi52 could u share in which file do u have a problem with ListView?

which version of react native?
