### ISSUE TITLE
locals[0] does not appear to be a `module` object with Hot Module Replacement API enabled.

### ISSUE THREAD

**Issue by LeBlaaanc** [facebook/react-native#8463]
I'm getting the following error after enabling hot reloading (iOS Simulator and Device):

```
locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

proxyReactComponents
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:5218:16
<unknown>
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:1475:1078
loadModuleImplementation
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:127:8
guardedLoadModule
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:63:37
_require
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:54:18
<unknown>
    index.ios.bundle?platform=ios&dev=false&minify=false&hot=true:77149:9
```

This is after a fresh install of 0.28 using `react-native init Home`, upgrading React and RN to `^15.2.0-rc.1` and `^0.29.0-rc.0` respectively, then running `react-native upgrade`. Node version is 6.1.0 but also did it in 4.

**Comment by LeBlaaanc** [comment]
I should mention after hitting `Dismiss` I end up with:
```
Unhandled JS Exception: Module RCTLog is not a registered callable module.

RCTFatal + 124
-[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 584
<redacted> + 144
<redacted> + 284
<redacted> + 60
-[RCTModuleMethod invokeWithBridge:module:arguments:] + 1684
-[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 712
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.452 + 1144
_dispatch_call_block_and_release + 24
_dispatch_client_callout + 16
_dispatch_queue_drain + 1036
_dispatch_queue_invoke + 464
_dispatch_client_callout + 16
_dispatch_root_queue_drain + 2344
_dispatch_worker_thread3 + 132
_pthread_wqthread + 1092
start_wqthread + 4
```
Maybe this is the underlying problem?

**Comment by satya164** [comment]
cc @grabbou I believe we had faced the same issue.

@LeBlaaanc can you provide a sample project demonstrating the issue?

**Comment by LeBlaaanc** [comment]
@satya164 does it just straight out of doing react-native init Foo

**Comment by grabbou** [comment]
Yeah, had it as well, cc: @martinbigio as you were looking for other repros.

**Comment by alexHlebnikov** [comment]
I've faced same issue after upgrading from 0.28 to 0.29 RC0. 
I've cannot solve it so I've downgraded back to 0.28.

**Comment by nihgwu** [comment]
please check this https://github.com/facebook/react-native/pull/8091
I've mentioned the issue there, and you can solve the issue by using the old js bundle path
`jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];`
 or launching the patch https://github.com/facebook/react-native/commit/9845f49581023302fcb33487bd6df2f7ce8825fa manully

**Comment by pavlelekic** [comment]
I'm facing the same issue.

**Comment by pavlelekic** [comment]
If I leave dev=true then I'm not able to have a production build, I'm stuck with the slow dev version :(

**Comment by mmazzarolo** [comment]
Having the same issue on `ract-native@0.33.0`... any suggestion?

**Comment by arilitan** [comment]
I just randomly started experiencing this as well, anyone find a solution?

**Comment by jeremyong** [comment]
Been seeing this issue for multiple releases. Developing without it is extremely frustrating

**Comment by fabriziomoscon** [comment]
Hi guys,
Suddenly my hot reloading stopped working with this error message.
It turned out that I set `__DEV__=false` in the Development Menu by mistake.
Checking the tick back gets rid of the error and Hot Reload works as before.

I understand that this is not a good compromise if you want to develop with hot reloading and `__DEV__=false`, but in my case I had just triggered it by mistake so hopefully this comment could still help somebody.

**Comment by greygatch** [comment]
I ran into this issue only in production environments.

Found that when process.env.NODE_ENV was undefined, shit would blow up, and I got this error.

Solution:

`process.env.NODE_ENV="production"`

**Comment by codebymikey** [comment]
For me this error occurs in Dev mode, when "JS Dev Mode" is disabled, but "Enable Hot Reloading" is also enabled.

Disabling "Enable Hot Reloading" fixes it, but sometimes you want hot reloading without JS dev mode enabled.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/locals0-does-not-appear-to-be-a-module-object-with-hot-module-replacement-api-en
