### ISSUE TITLE
ES6 Android issue with RN 0.28

### ISSUE THREAD

**Issue by belemaire** [facebook/react-native#8464]
I have updated one of my app to RN 0.28 and I am now having an issue (red screen - see screenshot below for reference) when I am launching the app.

I have pinpointed the specific issue to be related to this PR #8099, more specifically this [Section](https://github.com/facebook/react-native/pull/8099/files#diff-cb910bd1233e7351becdc4aca5ad3688R178) of code.

If I comment this whole block of code, the issue goes away and the app starts correctly and works fine.

I dived a little bit deeper and found out that the culprit is in this line of code, making use of ES6 iterator / for of operator.

```javascript
for (const key of reactAPIs) 
```

If I replace this line using a ES5 standard for loop, the issue is going away.

For some reason, I am only having this problem on Android, not iOS. 

I was not able to reproduce yet using a fresh project kickstarted using `react-native init`. Will look into this issue a bit more tomorrow, trying to find the root cause. Just wanted to open an issue if anyone has any idea / what to look for, before I dig deeper.

![android-bug](https://cloud.githubusercontent.com/assets/1390588/16404731/72dd7776-3cb6-11e6-811c-8a7b167d2e8b.png)

**Comment by belemaire** [comment]
Closing issue after more investigation seems to be really related to our app as I tried to put a `for of` statement at a key point in our app and got the same issue. Seems like the babel plugin for `for of` was not correctly loaded or don't know exactly ... still looking into it, but 'a priori' definitely not a RN related issue. Will reopen if needed

**Comment by amcsi** [comment]
I'm getting this issue as well.
Strangely, re-initting react-native on the same directory always yields this error, whereas if I init react-native in any other directory, I get the expected starter page.

versions:
```
react-native-cli: 2.0.1
react-native: 0.39.2
```

**Comment by KristoferEng** [comment]
Keep running into this error. Any thoughts on how to fix?
