### ISSUE TITLE
[Docs] Missing documentation for ActionSheetIOS

### ISSUE THREAD

**Issue by ustun** [facebook/react-native#847]
ActionSheetIOS has no docs. Does this mean the component is unstable or is it an oversight?

**Comment by brentvatne** [comment]
@ustun - seems to me that it is just undocumented, the source is simple enough to read through for now but if you want to contribute docs that would be awesome

See: [RCTActionSheetManager.m](https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m) and [ActionSheetIOS.js](https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/ActionSheetIOS.js)

**Comment by brentvatne** [comment]
https://facebook.github.io/react-native/docs/actionsheetios.html#content
