### ISSUE TITLE
Error building project ("transforming index.android.js took longer than 301 seconds.")

### ISSUE THREAD

**Issue by alwx** [facebook/react-native#8475]
Hello, everybody.
Everything was absolutely fine, but now I can't build my project anymore and every time I try I see the following error:
> ...
> [10:14:28 PM] <END>   Building Dependency Graph (5403ms)
[node-haste] Encountered an error while persisting cache:
> Error: TimeoutError: transforming /Users/alwxndr/Documents/Dev/_2016/rn-app/index.android.js took longer than 301 seconds.
> You can adjust timeout via the 'transformTimeoutInterval' option
>     at /Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/react-native/packager/react-packager/src/JSTransformer/index.js:95:28
>     at tryCallOne (/Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/promise/lib/core.js:37:12)
>     at /Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/promise/lib/core.js:123:15
>     at flush (/Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/asap/raw.js:50:29)
>     at _combinedTickCallback (node.js:370:9)
>     at process._tickCallback (node.js:401:11)
/Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/promise/lib/done.js:10
      throw err;
      ^

> Error: TimeoutError: transforming /Users/alwxndr/Documents/Dev/_2016/rn-app/index.android.js took longer than 301 seconds.
You can adjust timeout via the 'transformTimeoutInterval' option
    at /Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/react-native/packager/react-packager/src/JSTransformer/index.js:95:28
    at tryCallOne (/Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/promise/lib/core.js:37:12)
    at /Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/alwxndr/Documents/Dev/_2016/rn-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)```

More importantly, even if I do `git checkout <sha of some old commit>` in my project, I can't make it buildable. Maybe it is some cache error or something like that, but, of course, I am not sure. Brief googling didn't help.

`react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output main.jsbundle --assets-dest ./ios` doesn't work too.

**Comment by zaynyatyi** [comment]
I have same issues. Happened when i switched to react-native 0.28 from 0.26.3.

**Comment by alwx** [comment]
Downgrading doesn't help. I believe it is not a 0.28-specific issue.

**Comment by phil-allcock** [comment]
I have tried to reclone the project and still hitting the same error

**Comment by dannytip** [comment]
+1

**Comment by jaiesZ** [comment]
+1

**Comment by zaynyatyi** [comment]
i wrapped json as a string in js file as a quickfix and parsing it in runtime.

**Comment by alwx** [comment]
@zaynyatyi it is, of course, bad solution for production releases. 
I spent the day working on it, still have no idea why it happens.

**Comment by Bhullnatik** [comment]
It seems to be coming from the last version of [babel/babylon](https://github.com/babel/babylon). 
Downgrading it to `6.8.1` instead of `6.8.2` fixes the issue for me.

**Comment by zaynyatyi** [comment]
@alwx it is, but currently it's a blocker and it's just a quick solution while there is no fix
@Bhullnatik that worked, thanks.

**Comment by alwx** [comment]
@Bhullnatik it works, thanks!

**Comment by ColCh** [comment]
How did you downgraded this package?  You've installed it like `npm i -E babylon@6.8.1` ?

**Comment by zaynyatyi** [comment]
@ColCh just go to node_modules/react-native and do `npm i babylon@6.8.1` there

**Comment by ColCh** [comment]
No way for me. Even with this command:
```
cd node_modules/react-native; npm install babylon@6.8.1; cd ../../;
```

Build log below. 
```
[1:41:54 PM] <START> Building in-memory fs for JavaScript
[1:41:54 PM] <END>   Building in-memory fs for JavaScript (429ms)
[1:41:54 PM] <START> Building in-memory fs for Assets
[1:41:55 PM] <END>   Building in-memory fs for Assets (163ms)
[1:41:55 PM] <START> Building Haste Map
[1:41:55 PM] <START> Building (deprecated) Asset Map
[1:41:55 PM] <END>   Building (deprecated) Asset Map (68ms)
[1:41:55 PM] <END>   Building Haste Map (852ms)
[1:41:55 PM] <END>   Building Dependency Graph (20340ms)
[1:45:25 PM] <END>   find dependencies (229341ms)
[node-haste] Encountered an error while persisting cache:
> Error: TimeoutError: transforming /Users/someuser/example-project/node_modules/react-native/node_modules/immutable/dist/immutable.js took longer than 301 seconds.
> You can adjust timeout via the 'transformTimeoutInterval' option
>     at /Users/someuser/example-project/node_modules/react-native/packager/react-packager/src/JSTransformer/index.js:95:28
>     at tryCallOne (/Users/someuser/example-project/node_modules/promise/lib/core.js:37:12)
>     at /Users/someuser/example-project/node_modules/promise/lib/core.js:123:15
>     at flush (/Users/someuser/example-project/node_modules/asap/raw.js:50:29)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/someuser/example-project/node_modules/promise/lib/done.js:10
```

**Comment by zaynyatyi** [comment]
@ColCh what's your `npm list babylon` says in root of your project?

**Comment by ColCh** [comment]
@zaynyatyi 
```sh
$ npm list babylon
Foo@0.0.1 /Users/someuser/Foo
├─┬ babel-core@6.10.4
│ └── babylon@6.8.3 
└─┬ react-native@0.28.0
  └── babylon@6.8.1 
```

**Comment by zaynyatyi** [comment]
looks like issues fixed, you can upgrade babylon to latest (6.8.3) on
react-native

вт, 5 июл. 2016 г. в 18:48, Max Sysoev <notifications@github.com>:

**Comment by ColCh** [comment]
Yeah, I noticed that version bumb.

```sh
$ npm list babylon
Foo@0.0.1 /Users/someuser/Foo
├─┬ babel-core@6.10.4
│ └── babylon@6.8.3 
└─┬ react-native@0.28.0
  └── babylon@6.8.3 
```

Checked on old build which failed with `babylon@6.8.1` now builds succesfully... Nice! 👍 

RN depends on `"babylon": "^6.8.2",` ( https://github.com/facebook/react-native/commit/8b803c6143732915a6a390a2e1495e9355372aef ), and according to semver, `6.8.3` will be installed, if you run `npm install react-native`

**Comment by jarradh** [comment]
We're still experiencing this regardless of the upgrade to `react-native@0.36.0`

**Comment by rasom** [comment]
This error can appear again because of `babel-plugin-transform-es2015-block-scoping@6.18.0`. To fix it you nee to downgrade it to `babel-plugin-transform-es2015-block-scoping@6.15.0`

https://github.com/babel/babel/issues/4795

**Comment by cogwheel** [comment]
Downgrading babel no longer fixes this starting around react native 0.43.0. It breaks the build in another way (I can't recall at the moment).

**Comment by tobowers** [comment]
i'm having the same problem with an expo app

**Comment by jeaye** [comment]
I've opened a metro bug for this here https://github.com/facebook/metro/issues/111
