### ISSUE TITLE
how to integrate RN as a static library 

### ISSUE THREAD

**Issue by walter211** [facebook/react-native#8483]
Hi ,

I am tring to integrate ReactNaitve to my project as a SDK, is there any clear way to do this?

thanks for help!

**Comment by walter211** [comment]
` jsCodeLocation = [NSURL URLWithString:@"http://localhost:9381/index.ios.bundle?platform=ios&dev=true"];
  
  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */
  
//     jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  
//  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
//                                                      moduleName:@"ASTSDKRNLibrary"
//                                               initialProperties:nil
//                                                   launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AST_SDK_ReactNative"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  
  
//  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  
  //  [Twitter logInWithMethods:completion:]
  
  // TODO: Change where the log in button is positioned in your view
  //  logInButton.center = rootView.center;
  //  [rootView addSubview:logInButton];
  
  rootViewController.view = rootView;
  [[[UIApplication sharedApplication] delegate] window].rootViewController = rootViewController;`

**Comment by javache** [comment]
Please see http://facebook.github.io/react-native/releases/0.29/docs/tutorial-integration-with-existing-apps.html
