### ISSUE TITLE
Problem with children container width

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#8484]
How i can fix this problem?
I need a difference width but not bigger than parrent.

![screenshot_2016-06-29-09-25-02](https://cloud.githubusercontent.com/assets/11519065/16442828/d07e6fc0-3ddd-11e6-8396-6b9ce00cb04d.png)

**Comment by jeanregisser** [comment]
Hi @antoxi4, this kind of question should be asked on http://stackoverflow.com/.
Could you do that and close this issue? Thanks.
