### ISSUE TITLE
<Best Camera Roll Image> does it work on Android

### ISSUE THREAD

**Issue by zhongjie-chen** [facebook/react-native#8485]
[Best Camera Roll Image](http://facebook.github.io/react-native/docs/images.html#best-camera-roll-image)

**Comment by zhongjie-chen** [comment]
When the image component shows big-size image, will it automatically compress the image?

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot feature

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label android

**Comment by facebook-github-bot-8** [comment]
Hey @zhongjie-chen! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!
