### ISSUE TITLE
PanResponder inside of Listview not working correctly

### ISSUE THREAD

**Issue by K-Leon** [facebook/react-native#8488]
I noticed this issue first when i tried to use the new SwipableListView component:

**The PanResponder used to handle the Swiping inside of ListView Items "catches" all ScrollEvents of the ListView resulting in an blocked ListView**. There's no working way for all platforms to prevent the Child component from locking the Listview.

**iOS:**
On iOS you can fix this by adding a larger threshold to call the lock, due to the fact that direction specific Scrolllocking is implemented in JS: 
https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableListView.js#L132-L138

**Android:**
On Android this leads to a unusable ( randomly locking ) ListView, because Direction Locking is 'native'. At least i've no idea how to disable it. 

The same issues apply to 0.27. 

I pieced together a minimal running example in 28 that shows the issue on iOS and Android. ( Android is in 0.28 even more broken - at least for 4.x )

**Example:**
https://github.com/K-Leon/react-native-scrollbug

To get this working i needed to upgrade SwipableListView with latest master Version because there are a few bugs.

Another one that needs to get changed to get the example up and running:
https://github.com/facebook/react-native/blob/master/Libraries/Experimental/SwipeableRow/SwipeableListView.js#L55 
Has to be changed to: `getRowData: (data, sectionID, rowID) => data[sectionID][rowID],` )

For this and a few other small ones i'll send a pull request as soon as i could figure out what's going on and how it's possible to fix android scrolling. 

cc: @fred2028

**Comment by K-Leon** [comment]
Ok i located the issue:

for android:
`onShouldBlockNativeResponder: (event, gestureState) => false` misses.

**Comment by joshuapinter** [comment]
@K-Leon Praise you 🙏  

I was hunting down how to fix this for about an hour or so before I randomly stumbled upon your post. Thank you for not only posting this Issue but then coming back here and adding the solution. This is what makes the programming world go 'round. 

Cheers.
