### ISSUE TITLE
Documentation for TabBarIOS icons

### ISSUE THREAD

**Issue by adrian-social-prod** [facebook/react-native#849]
Please add a description of how to set non-default icons and labels in TabBarIOS to the docs.

**Comment by brentvatne** [comment]
@adrian-social-prod - will do

**Comment by brentvatne** [comment]
@adrian-social-prod - for now, you can see it here: https://github.com/facebook/react-native/blob/master/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L53-L61

```javascript
    /**
     * A custom icon for the tab. It is ignored when a system icon is defined.
     */
    icon: Image.propTypes.source,
    /**
     * A custom icon when the tab is selected. It is ignored when a system
     * icon is defined. If left empty, the icon will be tinted in blue.
     */
    selectedIcon: Image.propTypes.source,
```

For example:

```javascript
<TabBarIOS.Item icon={require('image!icon')}  title="Blue Tab">Blue Tab</TabBarIOS.Item>
```

![screen shot 2015-04-14 at 8 54 51 pm](https://cloud.githubusercontent.com/assets/90494/7152046/b4ac60be-e2e8-11e4-83d3-023d476ec138.png)

**Comment by brentvatne** [comment]
Easy fix here is to just add `'../Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js',` to [extractDocs.js](https://github.com/facebook/react-native/blob/master/website/server/extractDocs.js#L118), but then it would also make sense to add that to the `React` export object. Alternatively, we could modify the doc generator to allow us to group components on one page. Thoughts @vjeux?

**Comment by brentvatne** [comment]
Added in https://github.com/facebook/react-native/commit/9ee6cd61682c19d3373a388474b9071ed729078b

**Comment by crysfel** [comment]
How can I use high resolution images for the icons in the tabs?

**Comment by jedt** [comment]
Hey @crysfel, you can use high resolution images or retina images by suffixing @2x to the file name. for example:

icon@2x.png

**Comment by gilnuy** [comment]
hi,@brentvatne 
i just do it like yours, but it doesn't work. still tint blue.

```
selectedIcon={require('image!icon')}
```

![image](https://cloud.githubusercontent.com/assets/4455464/15090626/7474fc54-1460-11e6-9e21-b1877e282a57.png)
