### ISSUE TITLE
HMR not working for non-component code

### ISSUE THREAD

**Issue by inetfuture** [facebook/react-native#8490]
`lib.js`:

```js
import React, { Component } from 'react';
import { Text } from 'react-native';

const log = () => {
  console.log('hello');
};

class MyText extends Component {
  render() {
    return (
      <Text>Hello</Text>
    );
  }
}

export { log, MyText };
```

`index.ios.js`:

```js
import { log, MyText } from './lib';
...
  onPressLog() {
    log();
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight onPress={this.onPressLog} style={{padding: 20, backgroundColor:'red'}}>
          <Text style={{color: 'white'}}>Call Log</Text>
        </TouchableHighlight>
        <MyText></MyText>
      </View>
    );
  }
...
```

Hot reloading works for changes of `MyText` but not `log`.

I'm not sure if this is not supported or a bug, please help.

Environment: OS X 10.10.5, node 6.2.1, react-native 0.28

**Comment by inetfuture** [comment]
@martinbigio @davidaurelio @Kureev

**Comment by davidaurelio** [comment]
@inetfuture this is expected. Hot module reloading is (loosely?) compatible with the webpack implementation. Google it, and you will find more information.

The gist is that it’s impossible to update many types of modules safely. It happens to be possible for React components.

**Comment by davidaurelio** [comment]
@martinbigio mentioned that [this change here](https://github.com/facebook/react-native/commit/c0c80d7ace30caa8b436153b3c7143e0e9f4d8f7#diff-77c8c669e87e237a871dbeec98b9ba58R228) might solve your problem.

If you have time I’d like to know whether it helps. Thanks.
