### ISSUE TITLE
IOS: Image Source change issues

### ISSUE THREAD

**Issue by KinanKazmi** [facebook/react-native#8500]
I'd been building an app and recently upgraded from 0.23 to 0.28 and latest React aswell. The Android just had views issues but the iOS app broke. It gives the error JSON null for RCTImage, without mentioning any line number. Figuring it down to the bits, i found that the Image's source does not take new data anymore, whether it's from props or state. Even tried using the defaultSource prop but nothing. Upon ignoring the red screen error message (esc) the red disappears and the view seems to have loaded the image just fine. The Image's source does get changed, but it shows that error first. So the thing works but gives an error for no reason ?
I think it probably makes the image source "null" for a bit before placing the new correct source there? And that bugs out xCode? I'm also using the prop resizeMode='contain' with all the images.
Really hoping to having this fixed because my app relies heavily on props for images and state changes on images source and null values for images source.

**Comment by yuanyuli** [comment]
when change <Image> source  ,you should do this.forceUpdate()  immediately .or you can change the source of Image.props only . In my project , if I change the style and source of <Image> together, i should click the button five times that the Image would change.
Just experience from myself.

**Comment by KinanKazmi** [comment]
So what exactly was changed in Image component that its not temporarily taking an empty source?
How do i fix it across the whole app?
