### ISSUE TITLE
Android always re-fetching the whole JS bundle after rebuild

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#8504]
As I remember it was not happen on old version maybe 0.17 or some version earlier.
But after I upgraded to 0.24 and 0.27.2, it would always happen. 
It is a waste of time when you have to do some native android coding.
On ios it is not happen.

And btw I have to say that every time I upgraded my react-native, I always found something got worse.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-always-re-fetching-the-whole-js-bundle-after-rebuild

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46692)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvW-0004BS-DK
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:35 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvV-0003xm-Ib
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:34 -0700
Date: Thu, 27 Oct 2016 15:13:15 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606413;
	bh=h6ohIX8GMD3pTBZRm+E8IIAs4jpu1u88pY5sl5GhChc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZoDnM/qa33Wrm07WK9b9Lwvt+ks57uq6uZjUSRzXyUYoA1e1AlB+KCBcilxgXka6x
	 qxrQSizV6xxc94VCITnLxMu+27WS1/RN0pkSsrjtEFtxwMaTf0C+5b85K5i5UND9RZ
	 DursuD9PVvbrMATEOlJ9yenKmymTliKbm+RiGzVo=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (67/60 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56324)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsvs-0004K5-1q
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:57 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsvq-0000k5-Lj
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:55 -0700
Date: Thu, 27 Oct 2016 15:13:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606433;
	bh=pMYSY+TcFWH0XHt4+yZ6U/H+cSjZlgXmSorl98mOMXY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ul46LWBv2ppm9/7Aka2xd4LeAh1uaTmjUQrtudIIxaDICvb90/aSmKXysVBRixzZg
	 RGzySOw2Rm0evLiKCY2Gfd3avXXsgUOTuQrEW/hJOyneoyhtU3hKdwQ3ZQjRN/cNXU
	 VQEmGOsJq+bn9BfsW3Kt5H8gppZt4Sy0jCVzqxRo=
