### ISSUE TITLE
[Android] Copy button in the redbox should also support Windows and Linux platforms

### ISSUE THREAD

**Issue by lebronJ** [facebook/react-native#8510]
This is not a bug report but **Help Wanted**!

I have added a new feature of adding copy button in the redbox for RN Android, which copies the error message and stack trace to the host (your laptop's) clipboard. Please see [Add Copy and Dismiss Button in RN Android Red Box](https://github.com/facebook/react-native/commit/dc3fce06ea6db48285d31d8d00889c942d4b8aee) and have a try on it!

However it's only supported on Mac OS for now. The reason is just that I don't have available Windows or Linux computers to test this feature on. So I appreciate anyone's help to add this feature on these two platforms.

Actually I already have the code for you, which I think should work.
Please see https://github.com/facebook/react-native/blob/master/local-cli/server/util/copyToClipBoard.js

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
'use strict';

var child_process = require('child_process');
// Changes begin.
var iconv = require('iconv-lite');
// Changes end.
var spawn = child_process.spawn;

/**
 * Copy the content to host system clipboard.
 * This is only supported on Mac for now.
 */
function copyToClipBoard(content) {
  switch (process.platform) {
  case 'darwin':
    var child = spawn('pbcopy', []);
    child.stdin.end(new Buffer(content, 'utf8'));
    return true;
  // Changes begin.
  case 'linux':
    var child = spawn('xclip', ['-selection', 'clipboard']);
    child.stdin.end(new Buffer(content, 'utf8'));
    return true;
  case 'win32':
    var child = spawn('clip', []);
    child.stdin.end(iconv.encode(content, 'utf16le'));
    return true;
  // Changes end.
  default:
    return false;
  }
}

module.exports = copyToClipBoard;
```

The code between `// Changes begin.` and `// Changes end.` are the only things to be added by you. (Don't forget to add the dependency for iconv at the beginning.)
Hope this will work on Windows and Linux!

If anyone needs more information on this, feel free to contact me.

**Comment by leeight** [comment]
@lebronJ 

```
  case 'win32':
    var child = spawn('clip', []);
```

`clip` not exists on Windows

**Comment by rmevans9** [comment]
It does in some versions @leeight https://technet.microsoft.com/en-us/library/cc754731(v=ws.11).aspx

**Comment by jrodiger** [comment]
I'm running windows 10 and I'm interested in helping test this feature, but I'm new to working with react native and I'm not sure how to go about using this feature. Any guidance would be welcome, thanks!

**Comment by lebronJ** [comment]
@jrodiger Thanks for your interest! This feature is extremely easy for you to test and enable on Windows. Here are some steps as follows:
(1) Make a mistake and trigger a red box, where I believe there will be a copy button on the bottom.
(2) Pressing the copy button should behave the same as on Mac OS (copy the red box information onto your host PC clipboard), however it's not enabled on Windows as I described in this issue.
What you could help is to follow my guidance in this issue above and try to enable this feature at [https://github.com/facebook/react-native/blob/master/local-cli/server/util/copyToClipBoard.js](https://github.com/facebook/react-native/blob/master/local-cli/server/util/copyToClipBoard.js)

Hope this will help and this feature will be enabled with your effort and help!

**Comment by saigrandhi** [comment]
@lebronJ Is it necessary for us to build from source when we are testing this out? Or can we just change the `copyToClipBoard.js` file react-native directory of the node_modules of the project?
I am having some trouble building from source and was wondering if this method is appropriate.

**Comment by jasonporta** [comment]
This is almost a month old. Are you still looking for help? I'm home two to three days per week specifically to contribute and essentially build my portfolio, but I'm new at contributing. I know how to fork and clone but I I've never actually submitted anything to an existing project.

**Comment by jrodiger** [comment]
![image](https://cloud.githubusercontent.com/assets/17132071/22268689/70f2aa6c-e256-11e6-932d-b9c7e9b2d7b5.png)
@lebronJ I tested the proposed code on Windows 10, and received this output from my packager. I am now going to test the other section of the proposed code on a Ubuntu virtual machine, and share the results. Please let me know where to go from here regarding the Windows 10 code, and what you or anyone else recommends trying next. Thanks!

**Comment by jrodiger** [comment]
@lebronJ Just noticed that I left out "var iconv = require('iconv-lite');". With this correction the feature works on Windows 10. https://github.com/facebook/react-native/pull/11959 Also saw this pull request with the fix so I believe this should be included in the next version. Currently in the process of testing on Linux now

**Comment by jrodiger** [comment]
@lebronJ I tested your code on Linux on React Native 0.41, and pressing the copy button causes an error. If anyone has any recommendations of what to try next please let me know, otherwise I'm going to continue to research this feature on my own. The error message I received is as follows:
![screenshot from 2017-02-07 22-26-01](https://cloud.githubusercontent.com/assets/17132071/22723037/22da7a56-ed89-11e6-9bab-1681a04b3ed1.png)

**Comment by saigrandhi** [comment]
@lebronJ We tested your code once again on Ubuntu with RN 0.41 and got the copy button to work after installing xclip with `sudo apt-get install xclip`.

Is it possible to add xclip as one of the dependencies when installing react-native on Linux?

**Comment by jrodiger** [comment]
@lebronJ This thread can be closed now that the functionality has been implemented for Windows: https://github.com/facebook/react-native/commit/10a29aa95438d1f65739fa91b608f29779c2d5c1 and Linux: https://github.com/facebook/react-native/commit/0fe0fc038b1cbc0f3be29f1e3a752c2feb153285

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-copy-button-in-the-redbox-should-also-support-windows-and-linux-platform
