### ISSUE TITLE
[RCTRootView reactTag]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by fergusding** [facebook/react-native#8517]
After I integrate my native iOS project with react-native according to the official docment, run but it crash. The stack information:

reason: -[RCTRootView reactTag]: unrecognized selector sent to instance 0x7f84b8d77040
callStackSymbols: (
	0   CoreFoundation                      0x0000000112433d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000111ea7deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000011243cd3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000112382b17 ___forwarding___ + 487
	4   CoreFoundation                      0x00000001123828a8 _CF_forwarding_prep_0 + 120
	5  XXX                              0x000000010b3cdd13 -[RCTRootView reactTag] + 339
	6   XXX                              0x000000010b3ce1eb -[RCTRootView bundleFinishedLoading:] + 187
	7   XXX                              0x000000010b3ce106 -[RCTRootView javaScriptDidLoad:] + 454
	8   CoreFoundation                      0x00000001123fdc8c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	9   CoreFoundation                      0x00000001123fd9cb _CFXRegistrationPost + 427
	10  CoreFoundation                      0x00000001123fd732 ___CFXNotificationPost_block_invoke + 50
	11  CoreFoundation                      0x00000001124461e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1986
	12  CoreFoundation                      0x00000001122f5679 _CFXNotificationPost + 633
	13  Foundation                          0x000000010f0b6cd9 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	14  XXX                              0x000000010b371c4f __38-[RCTBatchedBridge executeSourceCode:]_block_invoke.271 + 239
	15  libdispatch.dylib                   0x0000000112cd6d9d _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000112cf73eb _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000112cdf1ef _dispatch_main_queue_callback_4CF + 1738
	18  CoreFoundation                      0x000000011238d0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	19  CoreFoundation                      0x000000011234eb99 __CFRunLoopRun + 2073
	20  CoreFoundation                      0x000000011234e0f8 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x0000000113104ad2 GSEventRunModal + 161
	22  UIKit                               0x000000010f54bf09 UIApplicationMain + 171
	23  XXX                              0x000000010ae1dbbf main + 111
	24  libdyld.dylib                       0x0000000112d2b92d start + 1
)

RN Version 0.28.0

Any help for me?

**Comment by KBvsMJ** [comment]
@fergusding  try to 👍  Build Settings -> other linker flags -> -ObjC

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/rctrootview-reacttag-unrecognized-selector-sent-to-instance

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
