### ISSUE TITLE
React context async initialization may be blocked in Android

### ISSUE THREAD

**Issue by nkuznetsow** [facebook/react-native#8519]
The issue related with code https://github.com/facebook/react-native/blob/f0f2645ec7dbf69e185b1090e237b657b3daa28a/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerImpl.java#L724

In ReactInstanceManagerImpl.java for async initialization of react context used next code:

```
mReactContextInitAsyncTask = new ReactContextInitAsyncTask();
mReactContextInitAsyncTask.execute(initParams); 
```

Method execute() of AsyncTask runs task in thread, that shared between all task by default. Therefore React context initialization will be blocked until all earlier started by execute() tasks will not be finished.

The line 

`mReactContextInitAsyncTask.execute(initParams); `

must be replaced with 

`mReactContextInitAsyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, initParams);`

**Comment by ide** [comment]
cc @andreicoman11, blame says you might be the best person to comment on this.

**Comment by andreicoman11** [comment]
I'm not convinced wether this is actually better. If you run the initialization in parallel with the other async tasks, you might be starved for resources while all the other async tasks finish. If you are in the same executor pool with the rest of the tasks, you have to wait for your turn, but then you have more resources at your disposal. Either way, we would have to measure this, @lexs you interested in giving this a go?

**Comment by lexs** [comment]
I think it's probably ok to just change it to `AsyncTask.THREAD_POOL_EXECUTOR` but let me run a test internally this week. Internally I doubt this will have any effect as we don't really run any AsyncTasks before this.

**Comment by lexs** [comment]
I didn't see any perf difference internally so I landed this in https://github.com/facebook/react-native/commit/c57eb94b347f1be8fe625bf65ba4af38dccf5917
