### ISSUE TITLE
RN-0.28 Unhandled JS Exception: Cannot read property 'showActionSheetWithOptions' of undefined

### ISSUE THREAD

**Issue by swliu920322** [facebook/react-native#8521]
Hello guys,
I upgraded react-native version from 0.27.2  to 0.28  recently and got an exception during debugging. The exception msg as below:
"Unhandled JS Exception: Cannot read property 'showActionSheetWithOptions' of undefined"
first i click the button which add image success,then i longPress the image so that i want to delete it, 
then error happened,
import { ActionSheetIOS } from 'react-native'
 ActionSheetIOS.showActionSheetWithOptions({
     ...})

Is there anybody also have the same problem? And how do u fix it?

thx advance

**Comment by jaygarcia** [comment]
Your code looks good.

Is `ActionSheetIOS` truly `undefined` in your implementation code?

**Comment by yueshuaijie** [comment]
I encountered similar problems. Try to uninstall `react-native` and install `react-native@0.28.0` again.

**Comment by rawrmaan** [comment]
For anyone who gets stuck on this again, I had to:
1) Reinstall my app on my device through Xcode
2) Add `RCTActionSheet.xcodeproj` to my project and link `libRCTActionSheet.a` as described here: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by chirag04** [comment]
closing as per above comment.
