### ISSUE TITLE
Simulator could not connect to development server

### ISSUE THREAD

**Issue by Darwinium** [facebook/react-native#8523]
I tried to change ip address that I could test on the device.

After changing lines in AppDelegate.m I did rebuild the application and restarted the server (npm start).

As you can see, the server is visible from the browser, everything works fine, but inside the app says that cannot connect to the server.
`jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.1:8081/index.ios.bundle?platform=ios&dev=true"];`

After restart project I see:
```
2016-07-01 13:12:07.949 PropertyFinder[10626:5440580] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
2016-07-01 13:12:09.964 [fatal][tid:main] Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate

URL: http://192.168.1.1:8081/index.ios.bundle?platform=ios&dev=true
```

**Screenshot:** 
![screenshot](http://dl2.joxi.net/drive/2016/07/01/0001/2707/121491/91/faf405e34d.png)

**I also tried open this ip in Safari Simulator:** 
![screenshot](http://dl2.joxi.net/drive/2016/07/01/0001/2707/121491/91/d1ecd028d1.png)

_node: v6.2.2
react-native-cli: 1.0.0
react-native: 0.28.0_

**Comment by jaygarcia** [comment]
try this:
Edit Info.plist to allow transport security:

Here's mine. You don't need the goruck-staging.moduscreate.com line. ;)
![2016-07-01_15-28-19](https://cloud.githubusercontent.com/assets/180031/16532568/bd76db00-3fa0-11e6-8d33-17f321573bbb.png)

**Comment by cpsubrian** [comment]
I was having this same problem testing on-device. Adding 'Allow Arbitrary Loads' got me one step further (to a different error). This can't be a sustainable solution though can it? Shouldn't an Exception Domain with the correct IP address also fix this (it didn't for me).

**Comment by tylerxo** [comment]
@jaygarcia's solution worked for me. Would be nice to know why this popped up, though.

**Comment by JBerendes** [comment]
It suggests that Apple would rather shift the liability of allowing that app behavior on to the app developer.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/simulator-could-not-connect-to-development-server

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (65/60 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:46698)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsve-0004Er-Vy
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:13:44 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsve-0003z4-7E
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:13:42 -0700
Date: Thu, 27 Oct 2016 15:12:59 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606421;
	bh=NNP6wkeKkkla4rEwatrHwelWyTDcze8HAUbS/EUvVfw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oifVcs1PKb+ly++au7QoLSX5NjaHSToC644xIcE1Bzgq3FZAFIyQ3pTt8iKdHbBOh
	 +pRbLlOB6MfIuq/k+Fg3/PQeVpEdpuGWJqjPqsYMA74GLMhEIKhzCQpszbifAvgh1V
	 CVb8yMeNOXPo9aW4pen72xaqqxLgnrd7CtYrOluk=
