### ISSUE TITLE
[iOS] Cannot create an archive when using Pods

### ISSUE THREAD

**Issue by alwx** [facebook/react-native#8534]
Kinda strange problem. My Podfile contains this line:
```pod 'React', :path => '../node_modules/react-native', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket']```
and seems like everything works (I can easily run my application), but when I try to create an archive (to upload my application to AppStore) I see the error that my application contains duplicate symbols. Somthing like that:
```ld: 227 duplicate symbols for architecture x86_64```

<img width="863" alt="screen shot 2016-07-02 at 14 16 28" src="https://cloud.githubusercontent.com/assets/911127/16540074/ffefb156-4067-11e6-9d52-18e188ff0444.png">
If I remove the libraries that are in my Podfile from *Link binary with libraries* list, I am able to create an archive, but when I run this application, I see another error: it runs but closes immediately showing something like "Native module cannot be null".

Is there something missing in the documentation? Should Pods be integrated some other way?

**Comment by alloy** [comment]
You should not add those libraries to the Link Phase in your Xcode project. The linkage should be done by the xcconfigs that CocoaPods generates for you.

I can't say much about the problem without having more information. Can you provide an example project that reproduces the problem?

**Comment by alloy** [comment]
This can probably be closed due to inactivity.

/cc @bestander @brentvatne
