### ISSUE TITLE
Using okhttp3 library with react-native

### ISSUE THREAD

**Issue by efkan** [facebook/react-native#8535]
Hello,

I've been developing a `native-module` to use in my `react-native` project.
And my native module uses `okhttp3` library. 

However when I run the command of `react-native run-android` I get the following exception:

    Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
    Unknown source file : com.android.dex.DexException: Multiple dex files define Lokhttp3/Address;

I guess both of `react-native` and I add `okhttp3` library to use in the same app.

Is there any chance to use `okhttp3` library which is added by `react-native`?

or is there any chance to overcome this issue?

I have also asked the question on the [stackoverflow](http://stackoverflow.com/q/38160078/3765109)

**Comment by satya164** [comment]
I'm using OkHttp 3 in my RN app just fine. Here's what I've in my `build.gradle` - https://github.com/belng/pure/blob/master/android/app/build.gradle#L178

I'm going to close this issue as this is a question which more suited to StackOverflow and not an issue with React Native.
