### ISSUE TITLE
Alignment impossible when mixing english/CJK text with non-default font

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native#8540]
When a `<Text>` is aligned well in english, the alignment breaks and becomes inconsistent when localized to CJK. This appears to work fine with the default font, but breaks with any non-default font.

In particular, the `En` in `<Text>En</Text>` will be aligned differently than the `En` in `<Text>En日本語</Text>`. It also means alignment in a localized app becomes effectively impossible.

Here's an example of this, with both the default font, as well as another standard default iOS font. (I first discovered it when using my own custom font).
https://rnplay.org/apps/N8PZVA
And here is an image of side-by-side texts that align differently when containing CJK:
![CJK Alignment issues](https://cloud.githubusercontent.com/assets/7953259/16543361/eeaf1828-409e-11e6-8820-b9fc52a00a69.png)

This occurs with RN 0.24.1 and RN 0.27. I see it on iOS, but haven't checked on Android.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/alignment-impossible-when-mixing-englishcjk-text-with-non-default-font

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:55907)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsuR-0003k4-ML
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:12:28 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsuP-00009C-Ha
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:12:27 -0700
Date: Thu, 27 Oct 2016 15:12:15 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606344;
	bh=uzxNm2hRHd/qfB2mVbT3e+GyYSzwJtC88Hq6v2oQD7E=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KiJGniMH1wUo+pfOnW4Gmys6NRYRRs2l793sdyQxinbtnpuQb8b0jpW3mlzqrmqMV
	 pv8a2p8AxldQyISWIl0mpECBN/FoLgHCJJ6pysuF6UpB0NgG/PlT+PvTvflWJv9qqF
	 eSVCOALrVdJyT2YNLEx3TrVPpdBJcdkUGOirl+bk=
