### ISSUE TITLE
"react-native init ***" crash if loglevel is set "info" in .npmrc

### ISSUE THREAD

**Issue by LHoin** [facebook/react-native#8542]
When I have "loglevel=info" in .npmrc file
I run react-native init XXX, I get the error below:
.............
npm info install lodash@4.13.1 into /Users/LHoin/source-github/test/node_modules/react-native/node_modules/babel-preset-fbjs/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-helper-define-map
npm info installOne lodash@4.13.1
npm info install lodash@4.13.1 into /Users/LHoin/source-github/test/node_modules/react-native/node_modules/babel-preset-fbjs/node_modules/babel-plugin-transform-es2015-classes/node_modules/babel-template
npm info installOne lodash@4.13.1
npm info linkStuff xmldom@0.1.22
npm http 304 https://registry.npm.taobao.org/asap
npm info install babel-helpers@6.8.0
npm info
`npm install --save --save-exact react-native` failed

when I remove the line "loglevel=info" in .npmrc, react-native init success

my enverionment
node: 4.4.7
react-native-cli: 1.0.0

**Comment by stowball** [comment]
Yep, this is definitely an issue (on OS X at least). I tried your Getting Started instructions multiple times with many versions node and npm, restarts aplenty and everything else until I found this issue.

It seems `loglevel` is to set `info` from `warn` in /Users/<User/.npmrc by default if you had previously installed with the nodeJS installer

**Comment by LHoin** [comment]
@stowball Thank you for reply. Though I wasted a lot of time when I got this error, it was really not a serious problem.

**Comment by lacker** [comment]
This is working for me now in master, so I'm going to close this issue. If there's still a problem it would be great if you could provide more specific info for how to reproduce so that I can reproduce it.
