### ISSUE TITLE
Buil fails on cirle-ci environments

### ISSUE THREAD

**Issue by vaukalak** [facebook/react-native#8545]
There several builds, that are failing on the same circle-ci step:
https://circleci.com/gh/facebook/react-native/8670
https://circleci.com/gh/facebook/react-native/8657
https://circleci.com/gh/facebook/react-native/8668
All those builds are for different pull requests, that touches completely different parts of the project.

**Comment by satya164** [comment]
cc @bestander

**Comment by bestander** [comment]
Thanks for noting, I am bisecting the reason in https://github.com/facebook/react-native/pull/8544

**Comment by bestander** [comment]
I'll close the issue because we are going to get master back to green within a day.
Please look for green on master branch and rebase https://circleci.com/gh/facebook/react-native then
