### ISSUE TITLE
version 0.27.2:  Shake Gesture not working

### ISSUE THREAD

**Issue by MiLeung** [facebook/react-native#8546]
I've been testing an app on my iPhone 6 and I've been using the shake gesture a lot to bring up the dev tools (mostly for manually reloading, enabling hot reloading, and debugging remotely), but then for some reason, my phone wouldn't connect to the node server, so I  uncommented "jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];" in the AppDelegate.m and that fixed the connection issue, but then I realized the shake gesture stopped working.  I downloaded some other apps to make sure the accelerometer and gyroscope hardware is still working and it is, so it's a software issue.

I've tried deleting the app and running again and restarting packager, but I still can't seem to get the shake gesture to work on device.  Shake gesture works on iOS simulator though.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/version-0272-shake-gesture-not-working

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:56018)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bzsup-0003t4-4W
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 22:12:53 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1bzsun-0000JN-Qx
	for bunny@thumbmunkeys.com; Thu, 27 Oct 2016 15:12:50 -0700
Date: Thu, 27 Oct 2016 15:12:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1477606368;
	bh=/Flh6XgZ19LRWBdET0r2okyLECc8RlBOXW64CRJpuu0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j+F3mbJlhOImdyLATzSUbXKrHAVTLubpAzrWsVSaP+ssyflwKQoa7eBobwbcRu5iD
	 quMbPDiKXkyvFNXpwCc43rKBSG8mnPV86ijCSYg6tOG06YwjBr8i60e9M9E9vvryNb
	 LOYAfg/BnDW8wdsSoxpK3D5Qt/oop9UaauLVwud4=

**Comment by malithjkmt** [comment]
You can bring up the dev tools by just running below command on the terminal.
adb shell input keyevent KEYCODE_MENU
