### ISSUE TITLE
Common React Native code for multiple iOS app projects?

### ISSUE THREAD

**Issue by SeeTechnologies** [facebook/react-native#8549]
I’ve added React Native to an existing iOS app following these instructions - https://facebook.github.io/react-native/docs/embedded-app-ios.html 

However the existing app is not a simple single-project iOS app (like the instructions are written for), the app is architected in such a way that there are multiple (more than a dozen) iOS app projects that all share common code from an Objective-C static library project. The directory structure is like this:

|-MainDirectory
|  |-CommonStaticLibraryProjectDirectory
|  |-iOSAppProject1Directory
|  |-iOSAppProject2Directory
|  |-...
|  |-iOSAppProject15Directory
 
Instead of having a separate copy of the ReactComponent directory (contains index.ios.js and all the other React Native JS files) under each iOSAppProjectDirectory it would be much better to have a single ReactComponent directory (similar to the Objective-C static library project) in a common location such as:

|-MainDirectory
|  |-CommonStaticLibraryProjectDirectory
|  |-ReactComponent
|  |-iOSAppProject1Directory
|  |-iOSAppProject2Directory
|  |-...
|  |-iOSAppProject15Directory

If I move the ReactComponent directory to this common location one level above the iOS apps root directories the node dev server starts OK but get React Native error in simulator: "Unable to resolve module apsl-react-native-button from <directory of JS file with instance of apsl-react-native-button>: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/apsl-react-native-button and its parent directories. This might be related to https://github.com/facebook/react-native/issues/4968…"

The 3 suggested steps to resolve issue #4968 does not work. Only removing references to 3rd party components makes it possible to use a ReactComponent directory outside of the iOS apps root directories.

I also tried a symbolic link in the iOS apps root directories to the ReactComponent directory in the common location. The node dev server starts OK but get React Native error in simulator: "Cannot find entry file index.ios.js in any of the roots: [“<iOS app root directory>","<iOS app root directory>/ReactComponent”]”

The only way I’ve got this to work (aside from not using any 3rd party components) is to copy the ReactComponent directory from the common location to within the iOS apps root directories.

Is there any way make this React Native code reusable from a common directory without resorting to a hack of creating a script to copy the ReactComponent common code to each dozen+ iOS app root directories?

I have tried React Native versions 0.21.0, 0.24.1, 0.25.1, 0.27.2 and 0.28.0 and all have this issue.

Thanks.

**Comment by Lokeh** [comment]
After moving the directory, did you redo the `pod install` step and change where the pod is located?

Likewise, you'll need to change the command you run to point to where your new react code lives: 
```bash
(JS_DIR=<new react code directory>; cd node_modules/react-native; npm run start -- --root $JS_DIR)
```

**Comment by SeeTechnologies** [comment]
Thanks for responding @Lokeh 

I did do both of the things you specified previously - this is how I got it working in the common location, but only without 3rd party references. Once I add 3rd party references in that configuration the "4968 error" appears.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/common-react-native-code-for-multiple-ios-app-projects

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
