### ISSUE TITLE
Tooling: webhooks to add labels to PRs

### ISSUE THREAD

**Issue by ide** [facebook/react-native#855]
From brief chat w @vjeux we want to improve the code review workflow using labels. The labels will show the state of each PR and help contributors and reviewers be on the same page wrt the next step for each PR. I imagine the flow to mostly look like:

1. Contributor submits PR. Label: [needs-review]
2. Reviewer imports PR into Differential
3. Reviewer has some questions but no requests for changes yet, submits comments
4. Contributor responds to questions
5. Reviewer posts new comments asking for changes (can Differential ping a webhook when this happens?) Label: [needs-revision]
6. Contributor updates PR by updating their branch. Label: [needs-review]
7. Reviewer accepts the diff and lands it through Differential
8. Bot automatically creates a corresponding Git commit and pushes it to GitHub. Bot removes the label from the PR and closes it.

(@vjeux are there parts that are different that from what you have in mind?)

**Comment by vjeux** [comment]
Actually i would skip the differential part of the process. We should review it without knowing the fb-side of things and when it's accepted then only at this point do the phabricator import. I want to move towards a world where tests in open source are the "source of truth" and if something breaks internally we need to add a test in open source. This will make going github first easier when we do it.

1. Contributor submits a PR. [Needs Review] <--- bot
2. Reviewer manually tags it as [Needs Revision]
3. Contributor updates the PR. [Needs Review] <--- bot
4. Reviewer manually tags it as [Accepted]
5. Reviewer imports it, get it accepted inside of fb, lands it...

So, for this task, the only thing that needs to be done is whenever a pull request is updated, need to remove the review tag and replace it with [Needs Review] (except if it's already been accepted)

**Comment by ide** [comment]
Makes sense, thanks for the clarification.
