### ISSUE TITLE
Linking.canOpenURL cannot tell if the URL is invalid

### ISSUE THREAD

**Issue by clh161** [facebook/react-native#8553]
I am with `RN 0.29 RC` on `iOS`
The `Linking.canOpenURL` returns `false` even if `Linking.openURL(url)` does work. I guess this happens because at the first time the user attempts to open the url and then a popup will be shown to ask user's permission and `Linking.canOpenURL` will returns `false`. Although this may be logically correct as it is a fact that user cannot open the url if the permission has not been granted, I cannot tell if this is due to invalid URL (i.e. the user has not installed the specific app that has the scheme and I want to remind the user to install or redirect to app store) or permission problem in this case. My code is like this:

    var url = 'myscheme://';
            Linking.canOpenURL(url).then(supported => {
                if (!supported) {
                    alert('Cannot open!')
                } else {
                    return Linking.openURL(url);
                }
            }).catch(err => console.error('An error occurred', err));

**Comment by gre** [comment]
I've noticed it too and have used the `url` module (from node) to actually parse the URL and add my own validation.
maybe you should do this too?

**Comment by yueshuaijie** [comment]
According to the doc http://facebook.github.io/react-native/docs/linking.html#canopenurl, maybe missing urlscheme in `LSApplicationQueriesSchemes` inside `Info.plist` ?

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/linkingcanopenurl-cannot-tell-if-the-url-is-invalid

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by NawazKhanMd** [comment]
My url is from file:// .I have already added the file in LSApplicationQueriesSchemes in info.pList

it says 

`2017-11-02 13:24:12.352492+0530 VisionPlanner_BFM_Mobile[1105:205855] -**canOpenURL: failed for URL: "file:///var/mobile/Containers/Data/Application/918B4A13-100E-4A9F-B7CD-D334DC2A7039/Documents/download.jpg" - error: "The operation couldn’t be completed.** (OSStatus error -10814.)"
2017-11-02 13:24:12.354 [error][tid:com.facebook.react.JavaScript] **'An error occurred', { [ReferenceError: Can't find variable: url]**
  line: 111806,
  column: 64,
  sourceURL: 'http://192.168.30.63.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }`
