### ISSUE TITLE
What is the keyboard in the simulator when I use TextInput?

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#856]
I use a TextInput component in my view, but it seems that when the textinput is focused, the keyboard doesn't be shown in the simulator.

**Comment by o-e** [comment]
You need to activate it in the simulator (the fact that it is invisible does not has to do with react native). Use Command K.

**Comment by brentvatne** [comment]
@iostalk - if @o-e's suggestion doesn't fix it (I suspect it will) then feel free to ping me again on this issue, otherwise closing it
