### ISSUE TITLE
Modal dismissing keyboard crash

### ISSUE THREAD

**Issue by markbrown4** [facebook/react-native#8562]
Mac OSX
react-native: 0.24.1

In the following component when clicking Cancel I get the following in the XCode console and the Modal closes then opens and then freezes.

> Warning: Attempt to dismiss from view controller `<UIViewController: 0x7fa152e17ca0>` while a presentation or dismiss is in progress!

``` js
'use strict';
import React, {
  Component,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  Dimensions,
  DeviceEventEmitter,
  LayoutAnimation,
} from 'react-native';

class Example extends Component {
  constructor(props) {
    super(props)

    var dimensions = Dimensions.get('window')

    this.state = {
      notes: '',
      width: dimensions.width,
      height: dimensions.height,
    }
  }
  componentWillMount() {
    DeviceEventEmitter.addListener('keyboardWillShow', this.keyboardWillShow)
    DeviceEventEmitter.addListener('keyboardWillHide', this.keyboardWillHide)
  }
  componentWillUnmount() {
    DeviceEventEmitter.removeAllListeners('keyboardWillShow')
    DeviceEventEmitter.removeAllListeners('keyboardWillHide')
  }
  keyboardWillShow = (e)=> {
    let height = Dimensions.get('window').height - e.endCoordinates.height - headerHeight
    LayoutAnimation.easeInEaseOut()
    this.setState({ height })
  }
  keyboardWillHide = (e)=> {
    let height = Dimensions.get('window').height - headerHeight
    LayoutAnimation.easeInEaseOut()
    this.setState({ height })
  }
  open() {
    this.setState({ open: true })
  }
  close() {
    this.setState({ open: false })
  }
  save() {
    this.setState({ open: false })
  }
  render() {
    return (
      <ScrollView keyboardShouldPersistTaps={ true }>
        <TouchableOpacity onPress={()=> this.open() }>
          <Text>Open</Text>
        </TouchableOpacity>
        <Modal
          animationType="slide"
          visible={ this.state.open }
          style={{ flex: 1 }}
        >
          <TouchableOpacity onPress={()=> this.close() }>
            <Text>Cancel</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={()=> this.save() }>
            <Text>Save</Text>
          </TouchableOpacity>
          <TextInput
            width={this.state.width}
            height={this.state.height}
            defaultValue={ this.state.notes }
            onChangeText={(notes)=> this.setState({ notes }) }
            autoFocus={ true }
            multiline={ true }
          />
        </Modal>
      </ScrollView>
    )
  }
}
```

When I remove `keyboardShouldPersistTaps={ true }` from `<ScrollView>` it doesn't crash but that's there so that clicks on these buttons works when the input has focus.

The only fix I have found so far to this issue is to dismiss the keyboard and then proceed in a timeout.

``` js
close() {
  dismissKeyboard()
  setTimeout(()=> {
    this.setState({ open: false })
  })
}
```

Fact: `setTimeout` literally fixes _everything_

**Comment by charpeni** [comment]
Can you test with react-native@0.28 or 0.29.0-rc.2 ?

**Comment by markbrown4** [comment]
Same behaviour in `0.28.0` for me.

**Comment by markbrown4** [comment]
It's intermittent, seems to happen much _less_ in `0.28` but it still happens once in a while.

Here's a screen recording:
https://dl.dropboxusercontent.com/u/13632257/ModalKeyboardCrash.mov

**Comment by mschipperheyn** [comment]
+1

**Comment by manishtpatel** [comment]
+1 I can reproduce it with latest 0.37, same behaviour as @markbrown4 sample, any known workaround at this time?

**Comment by mini-eggs** [comment]
Same issue here on 0.39.1

**Comment by rkho** [comment]
0.40.0 has the same issue; closing a modal after a keyboard was used causes the modal to jump back up and crash the app.

**Comment by mini-eggs** [comment]
Found a really great 'work around.' Although, probably best practice to do it this way all along.

```
import { Keyboard } from 'react-native'
...
Keyboard.removeAllListeners('keyboardDidHide') 
// not totally necessary and may be harmful if you do this in more than one location, works for my case
Keyboard.addListener('keyboardDidHide', () => { this.checkSubmit() })
// checkSubmit is a function the pulls up the modal
Keyboard.dismiss() 
```

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/modal-dismissing-keyboard-crash

**Comment by iremlopsum** [comment]
@hramos This issue still exists in 0.48.1 both on iOS and Android. As others, I found a workaround for it, but it took me way too long to find what was causing the crash. Could you please re-open this issue?

**Comment by charpeni** [comment]
Let's reopen it then.

**Comment by charpeni** [comment]
@facebook-github-bot reopen

**Comment by AggarwalAnkit** [comment]
I am also getting this issue. I have a modal which contains TextInput. The problem is when I close the modal, it closes properly but when I press home button (without closing modal) and again come back to the app and close the modal it reopens itself and freezes. I removed the text input and it started behaving properly. But I have other modals in my app which have input field and the issue is not happening there. So, I checked the difference and the difference was my this modal (which is not working properly) has input field with autofocus true. I removed that and it started working properly. But I want that autofocus. I am unable to find the bug as I am new to react native. Please someone help here. Thanks

**Comment by agrosner** [comment]
showing successive modals without a timeout also triggers this issue. This does not happen on Android and it works much smoother on Android.
