### ISSUE TITLE
Semantic Issue when building RN project in XCode 8.0

### ISSUE THREAD

**Issue by chrisv95** [facebook/react-native#8575]
When trying to build a valid RN project in XCode 8.0 (which runs on Android), I get the following error:

Ignoring return value of function declared with warn_unused_result_attribute in RCTSRWebsocket.m, at the lines where the SecRandomCopyBytes() method is called.

I cannot find any solution to this problem. Any advice?

**Comment by charpeni** [comment]
@facebook-github-bot label iOS

**Comment by sibelius** [comment]
fixed on RN33

or follow this comment: https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

**Comment by chrisv95** [comment]
@sibelius for your information perhaps, I could fix this issue by downgrading to a previous version of XCode; 8.0 wouldn't work back then.

**Comment by ide** [comment]
This has been fixed in master; closing out.
