### ISSUE TITLE
Loading Images From Bundle Broken in IOS 10

### ISSUE THREAD

**Issue by myusuf3** [facebook/react-native#8582]
This was previously working before beta 2, now using the previous API to load images from the bundle. We are now currently seeing this following 

we are using the following syntax for loading images. 

```js
<Image
source={require('../images/heart.png')}
style={styles.heartIconImage} />
```

![image](https://cloud.githubusercontent.com/assets/156825/16597138/60289a4c-42c5-11e6-93da-080d3f0e1209.png)

**Comment by myusuf3** [comment]
@facebook-github-bot label iOS

**Comment by aprilzero** [comment]
We are doing `resizeMode: 'stretch'` on some of these, I wonder if that is causing some new issues. Besides that everything is very straightforward. Just some simple png-24's.

```
cardIconImage: {
    height: 48,
    width: 48,
    resizeMode: 'stretch',
}
```

**Comment by janicduplessis** [comment]
Do loading images from xcode assets still works? (`require('image!asset_id')`)?

**Comment by myusuf3** [comment]
@janicduplessis that was removed in previous react version.

**Comment by aprilzero** [comment]
Update: this seems to just be a problem with any png transparency in iOS10 Beta 2.

**Comment by eduardinni** [comment]
Fixed in iOS 10 beta 4 (Developer)

**Comment by janicduplessis** [comment]
👍
