### ISSUE TITLE
[Getting Started] Error: ignoring return value of function declared with warn_unused_result attribute

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#8584]
Hi there, I'm snagged after a fresh install today:

$ react-native init AwesomeProject
$ react-native run-ios

Full log:
https://gist.github.com/andresn/1f35d718da9fc57542bb399460f2efd0#file-gistfile1-txt-L109

react-native@0.28.0
react-native-cli@1.0.0
XCode Beta 8.0
Mac OS X El Capitan v.10.11.5

I think this is specific to having Xcode-beta 8.0 installed, because running the app through beta-7.3 does work.

**Comment by liweiz** [comment]
I had similar experience today. But it was on macOS beta. Build failed on both XCode 7.3.1 (7D1014) and 8.0 beta 2 (8S162m). I did try $ react-native run-ios but got error: 

> 
>  ERROR  ENOENT: no such file or directory, lstat '/AwesomeProject/ios/build/ModuleCache/3F1D94PC0NUP2/AVFoundation-1M2ASOEW37WIZ.pcm-53d428b3'
> {"errno":-2,"code":"ENOENT","syscall":"lstat","path":"/AwesomeProject/ios/build/ModuleCache/3F1D94PC0NUP2/AVFoundation-1M2ASOEW37WIZ.pcm-53d428b3"}
> Error: ENOENT: no such file or directory, lstat '/AwesomeProject/ios/build/ModuleCache/3F1D94PC0NUP2/AVFoundation-1M2ASOEW37WIZ.pcm-53d428b3'
>     at Error (native)

macOS: 10.12 Beta (16A239j)
react-native-cli: 1.0.0
react-native: 0.29.0

Same two errors on both versions of XCode under Semantic Issue, when I tried build with XCode: 

-     /AwesomeProject/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute
-     /AwesomeProject/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1334:5: Ignoring return value of function declared with warn_unused_result attribute

**Comment by samtgarson** [comment]
+1 on this, getting almost exactly the same output as OP 😭 

Could be related to https://github.com/facebook/react-native/issues/8108?

**Comment by cpruijsen** [comment]
I'm also facing this error :(

**Comment by crsanthony** [comment]
same :(

**Comment by huangkaiw3n** [comment]
I'm running into this issue as well. I'm on Xcode Version 8.0 beta 2. And OS X 10.11.5. I've got almost the same log too

**Comment by jlietart** [comment]
Same issue here :(

**Comment by adeolafadeyibi** [comment]
Same issue here:(

**Comment by zhaop4133** [comment]
Same issue here:(

**Comment by isramartinez** [comment]
Same issue here on Xcode version 8.0 beta 3

**Comment by adeolafadeyibi** [comment]
I uninstalled Xcode version 8.0 beta 3 and installed 7.3 and now everything works fine.

**Comment by TimBroddin** [comment]
Just doubleclick on the RCTWebSocket project in your navigator and remove the flags under *build settings* > *custom compiler flags*

<img width="883" alt="schermafbeelding 2016-07-30 om 15 47 45" src="https://cloud.githubusercontent.com/assets/528287/17270862/0f397686-566d-11e6-8db5-76a17cbd620b.png">

Your project should compile just fine now!

**Comment by alessiodionisi** [comment]
Thank you!!

**Comment by jdmarshall** [comment]
Having the same issue, but on XCode 7.2.1

I think the fact that upgrading XCode fixes this for some people has more to do with temporary files being retained somewhere and the installer deletes them.  

What is the -proper- way to clear a working directory and rerun a build with react-native?  I'm having problems with rebuilding and having components that have been deleted or renamed still causing errors, which means that some part of the build is not removing intermediate results between builds.

**Comment by danawhite** [comment]
Thanks for this!!

**Comment by javache** [comment]
Fixed by https://github.com/facebook/react-native/commit/2f788524112d59f62a295e7f4b0c1cfa0f6203fe

**Comment by sirgalleto** [comment]
How to upgrade to this version o this code in a "old" project @javache?

**Comment by javache** [comment]
We don't release patches for old releases, but you can apply these changes yourself.

**Comment by sirgalleto** [comment]
Oh thanks. I'll try

**Comment by tristanbbq** [comment]
Thanks @TimBroddin - it worked for me too!

**Comment by jmitch0901** [comment]
@TimBroddin your the man!

**Comment by dwilt** [comment]
I feel so embarrassed to be posting this. I can't figure out how to delete those flags. I tried hitting the delete key, right clicking on them, checking the file menu, but can't find anything. Someone please put me out of my misery.

![image](https://cloud.githubusercontent.com/assets/1065539/18600298/c2877c46-7c11-11e6-8d7d-e702ce685a19.png)

**Comment by dwilt** [comment]
Oh, I figured it out. It was the values inside of those menus. Not the items themselves.

![image](https://cloud.githubusercontent.com/assets/1065539/18600472/979b5484-7c12-11e6-849e-34dad84e5fa1.png)

**Comment by raysmithdev** [comment]
@TimBroddin + 1

**Comment by jiangqqlmj** [comment]
thank you,this is fine~

**Comment by yongqianvip** [comment]
thank you @TimBroddin

**Comment by gviligvili** [comment]
@TimBroddin  Thank you so much.

**Comment by beast** [comment]
👍

**Comment by MrPluto** [comment]
:+1:

**Comment by digitalcatnip** [comment]
If we upgrade our React Native version after applying the above fix to remove the flags, will the upgrade restore the new patch for 0.34 properly?

**Comment by jariwalabhavesh** [comment]
Thank you @TimBroddin

**Comment by JimmyStavros** [comment]
@TimBroddin That did the trick, thanks.

**Comment by nicmar** [comment]
If you're like me, and trying to get FirebaseReactNativeSample to work, you need to go to FirebaseReactNativeSample > Libraries > RCTWebsocket.xcodeproj and then search in the right side for "custom", and you'll find it. It worked for me after doing that :)

**Comment by wallacyyy** [comment]
@TimBroddin you are such a hero.

**Comment by frostfat** [comment]
I updated to Sierra, initialised a new rn project, removed the flags and I still get the error: Application AppName has not been registered. This is either due to a require() error during initialisation or failure to call AppRegistry.registerComponent. Any thoughts?

**Comment by edin-m** [comment]
@frostfat +1

**Comment by Hamiltontx** [comment]
TimBroddin tks a lot, save me time.

**Comment by seanfuture** [comment]
@edin-m's solution of (void) in front of line temporarily worked for us on Sierra .. TY

**Comment by noprom** [comment]
Also faced with this problem, but my settings here is empty:
<img width="1278" alt="1" src="https://cloud.githubusercontent.com/assets/8455444/19769513/425b0310-9c8e-11e6-987c-ba9326c14fb9.png">

Here is my environment:
```
react-native-cli: 1.0.0
react-native: 0.32.0
xcode:Version 8.0 (8A218a)
mac:10.12 (16A323)
```
Thanks in advance.

**Comment by breadadams** [comment]
@noprom it looks like you're searching in your main project. If you click **RCTWebSocket** in the sidebar, and then search in Build Settings, you should see it.

**Comment by xugy0926** [comment]
@TimBroddin  i love u

**Comment by jtanori** [comment]
@TimBroddin you are the MVP here.

**Comment by heliosPortal** [comment]
@TimBroddin, Bless your children, give them names...

**Comment by dhwrwmgwra** [comment]
@TimBroddin You rock

**Comment by qxqxqxqx** [comment]
@dwilt I do take a while to figure it out,hahaha

**Comment by IWantToLearnCoding** [comment]
@TimBroddin God bless you children...
