### ISSUE TITLE
Dimensions.get('window').width incorrect in Android 6.0.1

### ISSUE THREAD

**Issue by bennyguitar** [facebook/react-native#8587]
**Phone**
- Nexus 5
- Android 6.0.1

**React Native**
- 0.28.0 stable release

**Problem**

When running in release mode, whenever the orientation changes, the screen width/height are never updated using`Dimensions.get('window')`. No matter what, whether I'm in Portrait or Landscape mode, I receive this value back from the Dimensions.get call:

`{ width: 360, height: 592 }`

This really is only a problem because on iOS the Dimensions will get updated correctly. So I can't just take the min of the two and call it a day.

**Comment by stoffern** [comment]
workaround would be to check rotation on android

**Comment by jskuby** [comment]
I ran into the same issue, and came up with the same workaround, as @stoffern.  We created a service that uses the react-native-orientation package to register a listener on orientation change that determines which values from the `Dimensions.get('window')` call are cached as the current height and width.  Here's a simplified version of what we did:

```
// screenService.js
import { Dimensions } from 'react-native';
import Orientation from 'react-native-orientation';

let screen = {};

Orientation.addOrientationListener(orientation => {
  const { height, width } = Dimensions.get('window');
  const min = Math.min(height, width);
  const max = Math.max(height, width);
  const isLandscape = orientation === 'LANDSCAPE';
  screen = {
    height: isLandscape ? min : max,
    width: isLandscape ? max : min,
  };
});

export default { screen };
```

Then we just call our module like `screenService.screen.height` to get the current value.  The logic works for Android and iOS, so no conditional code is required. Hope that can help someone until the issue is resolved.

**Comment by samuelkraft** [comment]
You can also listen on the onLayout event on your root view in order to get the correct width & height. This works on orientation change without any other packages. Check out this blogpost for an example https://corbt.com/posts/2016/03/16/detecting-orientation-in-react-native.html

**Comment by jskuby** [comment]
My original approach was to use onLayout, however our use case is to support dynamic styles for rotation and the onLayout callback was being fired after rotation completed, meaning you could see the components getting restyled after the rotation animation finished.

With the react-native-orientation package our callback is fired right after the screen begins to rotate, which means our new styles are applied during rotation and we get no jank once the rotate animation completes.  Maybe something to keep in mind depending on your use case.

**Comment by samuelkraft** [comment]
Good point! The delay is visible on both android and iOS unfortunately. 
I had some mixed results with the orientation package when testing it, although that was a while ago and things might have improved since!

**Comment by markspolakovs** [comment]
@jskuby I had to modify your workaround like this:
```js
import { Dimensions } from 'react-native';
import Orientation from 'react-native-orientation';

let screen = {};

const setScreenSize = orientation => {
  const { height, width } = Dimensions.get('window');
  const min = Math.min(height, width);
  const max = Math.max(height, width);
  const isLandscape = orientation === 'LANDSCAPE';
  screen = {
    height: isLandscape ? min : max,
    width: isLandscape ? max : min,
  };
};

Orientation.addOrientationListener(setScreenSize);

setScreenSize(Orientation.getInitialOrientation());

export default { screen };

```

**Comment by mhdayyoob** [comment]
Can you please any one show a example of 

how to get window width in react-native

**Comment by saravanannnallasamy** [comment]
const window = Dimensions.get('window');

<Text style={{ fontSize: 48}}>Height is {window.width}</Text>

**Comment by saravanannnallasamy** [comment]
Dimensions.get('window').width;

**Comment by tjswk2008** [comment]
I ran into the same issue.
I think this is an issue with Nexus devices, as they have navigation bars. I don't know if there is any method to get the navigation bar's height.

![image](https://cloud.githubusercontent.com/assets/17583754/25844625/9de77d34-34dd-11e7-8f3d-d8b02a961230.png)

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/dimensionsgetwindowwidth-incorrect-in-android-601
