### ISSUE TITLE
webview for android shows white screen after the load is complete(on load complete method call) 

### ISSUE THREAD

**Issue by RonakKhandelwal** [facebook/react-native#8593]
It works for most of the url's but when I try to use it for url opening google docs then it shows a blank screen test url

https://docs.google.com/gview?url=https://vaultedgetemp.storage.googleapis.com/20128af0-98f5-4a5c-b33a-c3fdcc5b0015-view.pdf

**Comment by npomfret** [comment]
Same problem here.

**Comment by arkilis** [comment]
can you post your code.

**Comment by lacker** [comment]
This issue is missing a repro project and has been for some months so I am going to close it. If you still see a similar problem then I encourage you to reopen a new issue.

**Comment by sun2rise** [comment]
@RonakKhandelwal, @npomfret have you solved this problem somehow?

**Comment by esutton** [comment]
+1 on Android only on RN 0.53.3. Same URL works fine in the Android browser.  Is there a URL string length issue?  

My URL with jwt including token is 958 characters long.

https://github.com/facebook/react-native/issues/14499#issuecomment-371162265

@opolyo01  @Ilyaololo did you solve this?

I have same blank screen **WebView** when displaying a URL with a large jwt token.  The url is 958 characters long.

- Using: **RN 0.53.3**
- Android only.  
- Copying the URL works fine on native Android browser on both a desktop ,
- Changing from https to http does not help.

Is there a string length limit?

The URL string length including token is 958 characters:

@RonakKhandelwal, @npomfret have you found a work-around? 

I am about to resort to **react-native-webview-bridge** on Android.

````
https://acme.com.io/user?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZC
TmpkRlFqRTBPRFl5TkVJeVEwUkJPRUZFT1VFNE4wWXpNZyJ9.eyRwczovL2F1dGguc3Vic2l
....
HV9Pcyya_g8xq_VmLKvFx4JF7EqeKXXOQbGx5iDJohQkQJ0O85C0HF3LtvBvf9xBHSpMhtZ
gWQVsXhMfqNX1gmg23dwzbGroPz4k_EQ057GKTajVwwnWDXpgz6JAVTuFQ6S9Dg1ZQEtw
````

````
  render() {
    // uri is 958 character in length
    console.log('dbg: WebScreen uri.length', this.props.uri.length);
    console.log('dbg: WebScreen uri:\, this.props.uri);
    return (
      <WebView
        source={{ uri: this.props.uri }}
        style={{ marginTop: 0 }}
        scalesPageToFit
        onError={() => {
          this.trackLoadTime(-1);
          }}
        onLoadEnd={() => this.onLoadEnd(0)}
      />
    );
  }
````
Using:
````
		"react": "^16.2.0",
		"react-native": "^0.53.3",
````

**Comment by shamanking** [comment]
I have same issue:

I use: 
"react": "16.2.0",
"react-native": "0.54.0",

This is my code:

 ```
const url_doc = `https://docs.google.com/gview?url=${documentPath}&embedded=true`;

    return (
      <WebView
        style={{ flex: 1 }}
        source={{ uri: url_doc }}
        startInLoadingState={true}
        javaScriptEnabled={true}
        automaticallyAdjustContentInsets={true}
        injectedJavaScript={jsCode}
        onError={(err)=>alert(JSON.stringify(err))}
        ignoreSslError={true}
        onLoadEnd={(data) => console.log('OnloadEnd', data)}
      />
    );
```

Sometime, it's return white screen
