### ISSUE TITLE
RefreshControl has a bug on iOS platform

### ISSUE THREAD

**Issue by cizhaoyang** [facebook/react-native#8595]
When I use 'RefreshControl' of component on iOS platform,there is a black ActivityIndicator on the top right corner

**Comment by tofrookie** [comment]
+1

**Comment by kkgelu** [comment]
+1 after upgrading to 0.28

**Comment by kkgelu** [comment]
This duplicates #7976

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #7976

**Comment by facebook-github-bot-0** [comment]
@charpeni tells me this issue is a duplicate of #7976. Let's discuss there, closing this one.
