### ISSUE TITLE
nested `fetch` calls error

### ISSUE THREAD

**Issue by tgoldenberg** [facebook/react-native#8599]
When I do a single `fetch` call, it works and I can access the response. When I nest a second `fetch` inside the response, I get the error below `NotFoundError`. 

I am using latest version of `react-native`, 0.28, Mac, and on iOS. I am also using `Deployd` as an API.

![screen shot 2016-07-06 at 10 09 38 am](https://cloud.githubusercontent.com/assets/10930134/16620877/1c6e51aa-4362-11e6-83a7-eb7012717ad5.png)

```javascript
fetch(`${API}/conversations?${conversationQuery}`)
    .then(response => response.json())
    .then(conversations => {
      let userIds = _.uniq(_.flatten(conversations.map(d => ([d.user1Id, d.user2Id]))));
      console.log('USER IDS', userIds);
      let userQuery = {
        "id": { "$in": userIds }
      };
      fetch(`${API}/users?${userQuery}`)
      .then(response => response.json())
      .then(users => this.setState({ conversations, users }))
      .catch(err => { console.log('ERR: ', err)})
      .done();
    })
    .catch(err => { console.log('ERR:', err)})
    .done();
```

**Comment by tgoldenberg** [comment]
I should also mention that this only fails when I have the Chrome debugger turned on

**Comment by zhongjie-chen** [comment]
Could you tell me about the  method of  `done()`?

**Comment by gre** [comment]
Yeah I don't think `.done()` exist in Promise spec.
It is available in promise libraries like `Q` but not in Promise AFAIK.

**Comment by tgoldenberg** [comment]
It works now. I don't have any explanation, since I didn't change anything, and can't come up with a reasonable solution as to why it works as opposed to before (not dependent on Wifi, etc.). Closing this.
