### ISSUE TITLE
What's the diffrence between NavigatorIOS and Navigator

### ISSUE THREAD

**Issue by iostalk** [facebook/react-native#860]
Sorry but I am so confused and the document doesn't touch this, thank you

**Comment by brentvatne** [comment]
@iostalk - `NavigatorIOS` wraps `UINavigationController` and renders out a navigation bar for you, allowing you to control things such as tint colour and buttons. `Navigator` is a component that leaves implementing the actual view up to you and allows you to control routing through the app similar to `NavigatorIOS`. Check out the docs and compare the props :smile: and you will see what I mean.
