### ISSUE TITLE
[0.29]Native animated module is not available

### ISSUE THREAD

**Issue by ZhenjieRuan** [facebook/react-native#8602]
when trying out native animation on iOS, encountered this error
![img_0008](https://cloud.githubusercontent.com/assets/6864390/16622075/c84be11e-4366-11e6-891d-1a5c86242da3.jpg)

**Comment by Roconda** [comment]
Same here. Also added the NativeAnimtions to my project as a Library.

**Comment by alloy** [comment]
Have you tried to clean your Xcode project (Command-Shift-K) or delete the project’s `DerivedData` dir?

**Comment by Fanghao** [comment]
u need to add `RCTAnimation.xcodeproj` and `libRCTAnimation.a` to your project like in the PR https://github.com/facebook/react-native/commit/19e2388a76a7792ace166b64b9f1fc4695b62f1f

**Comment by rodriguesbreno** [comment]
Is this module available in android?

**Comment by rturk** [comment]
According to my Google play crash report this is the main cause of crashes for my Android App:

Thousands of crashes with same error:
**Native animated module is not available**

**Comment by lacker** [comment]
This seems like an un-reproducible build problem that has gone away in recent build so I am going to close this issue.

**Comment by Liqiankun** [comment]
@Fanghao I added it to my Podfile. Then i installed it! It still didnot work!

**Comment by trinadhkoya** [comment]
Make sure you have  RCTAnimation.xcodeproj and whether  libRCTAnimation.a to your project liked or not
