### ISSUE TITLE
[0.29] rnpm and react-native link stopped working

### ISSUE THREAD

**Issue by stoffern** [facebook/react-native#8603]
After the update to 0.29: `rnpm link` and `react-native link` is not linking correct!

It will try to link everything into `MainActivity.java` resulting in import and nothing more, while MainApplication.java is empty.

@foghina this is broken after your update.

**Comment by GantMan** [comment]
Wow.  That's a helluva miscommunication.  I'll try to ring whatever alarm bells I can find.

**Comment by charpeni** [comment]
cc @grabbou @mkonicek

**Comment by foghina** [comment]
cc @Kureev

**Comment by skellock** [comment]
Changing from `MainActivity.java` to `MainApplication.java` fixes this issue in this file:

https://github.com/facebook/react-native/blob/master/local-cli/rnpm/core/src/config/android/index.js#L38

This will, however, break < 0.29 which sucks.

I noticed there's a patching system whereby you detect version numbers for breaking changes?  I didn't go further than this for now.

For a work around in our own repos, we can change `native_modules/react-native/local-cli/rnpm/core/src/config/android/index.js`.

**Comment by stoffern** [comment]
Changing the path is not a good solution.
We need to add a new path to the config and do a check if `MainApplication.java` exists, if so then write to that file instead.

**Comment by GantMan** [comment]
@stoffern and @skellock  - integrated that feedback into a quick PR.  Hopefully this helps.

**Comment by grabbou** [comment]
We don't have to care about versioning here since `rnpm` is bundled with `react-native` and always version specific.

@Kureev can you submit a quick patch since that's Android-part? CC me, I'll ship it and we will do the `.2` version since that's crucial.

**Comment by grabbou** [comment]
PR hints:

1) Add `MainApplicationPath` to config here -> https://github.com/facebook/react-native/blob/master/local-cli/rnpm/core/src/config/android/index.js#L62
2) Use it instead in the patching function -> https://github.com/facebook/react-native/blob/master/local-cli/rnpm/link/src/android/registerNativeModule.js#L30 and here -> https://github.com/facebook/react-native/blob/master/local-cli/rnpm/link/src/android/registerNativeModule.js#L35

**Comment by stoffern** [comment]
@GantMan guess we can close thisone now?
