### ISSUE TITLE
HorizontalSwipeJumpFromRight doesn't mirror HorizontalSwipeJump.

### ISSUE THREAD

**Issue by mwiley** [facebook/react-native#8604]
I'd expect Navigator.SceneConfigs.HorizontalSwipeJumpFromRight to look and behave like Navigator.SceneConfigs.HorizontalSwipeJump but on the other side of the screen. Instead, the transition for the scene going out is different.

In react-native/Libraries/CustomComponents/Navigator/NavigatorSceneConfigs.js, you can find this snippet at line 578.

```
  HorizontalSwipeJump: {
    ...BaseConfig,
    gestures: {
      jumpBack: {
        ...BaseLeftToRightGesture,
        overswipe: BaseOverswipeConfig,
        edgeHitWidth: null,
        isDetachable: true,
      },
      jumpForward: {
        ...BaseRightToLeftGesture,
        overswipe: BaseOverswipeConfig,
        edgeHitWidth: null,
        isDetachable: true,
      },
    },
    animationInterpolators: {
      into: buildStyleInterpolator(FromTheRight),
      out: buildStyleInterpolator(ToTheLeft),
    },
  },
  HorizontalSwipeJumpFromRight: {
    ...BaseConfig,
    gestures: {
      jumpBack: {
        ...BaseRightToLeftGesture,
        overswipe: BaseOverswipeConfig,
        edgeHitWidth: null,
        isDetachable: true,
      },
      jumpForward: {
        ...BaseLeftToRightGesture,
        overswipe: BaseOverswipeConfig,
        edgeHitWidth: null,
        isDetachable: true,
      },
      pop: BaseRightToLeftGesture,
    },
    animationInterpolators: {
      into: buildStyleInterpolator(FromTheLeft),
      out: buildStyleInterpolator(FadeToTheRight),
    },
  },
```

I believe animationInterpolators.out should be ToTheRight, and not FadeToTheRight. There is no ToTheRight in this file. In my application I solved this by creating my own NavigatorSceneConfigs that looks similar to the included one, and copied ToTheLeft like this so I can have the scene configured how I want.

```
const ToTheRight = {
  transformTranslate: {
    from: {x: 0, y: 0, z: 0},
    to: {x: Dimensions.get('window').width, y: 0, z: 0},
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
  opacity: {
    value: 1.0,
    type: 'constant',
  },

  translateX: {
    from: 0,
    to: Dimensions.get('window').width,
    min: 0,
    max: 1,
    type: 'linear',
    extrapolate: true,
    round: PixelRatio.get(),
  },
};
```

This problem could be solved easily like this, unless that's how it's intended to work.

**Comment by stoffern** [comment]
@mwiley I think this HorizontalSwipeJump is supposed to simulate the native Android transition, as they are like this.

But there is no problem in creating custom scenes for this.

**Comment by mwiley** [comment]
I'm also having a hard time understanding why they're named the way they are, because we were describing them based on the direction the new scene moves in and the old moves out, it would be switched.

**Comment by yueshuaijie** [comment]
https://github.com/facebook/react-native/commit/cadc753e4c2c364d78dd2fa69499832ab52c65cd add `ToTheRight`, which is exactly what you need.

**Comment by mwiley** [comment]
Awesome, but it doesn't entirely fix my issue, since HorizonalSwipeJumpFromTheRight doesn't use ToTheRight, or any of the other scene configs.

**Comment by yueshuaijie** [comment]
@mwiley Maybe the author @vjeux could tell.
https://github.com/facebook/react-native/commit/2ed2d20dfe22e5fa53bad8f0b02af95f336febd1

**Comment by beeant** [comment]
I'm having this issue too...

**Comment by lacker** [comment]
At this point we are planning to create a new navigation library and encourage people to migrate to that, so I don't think we are going to change `Navigator` behavior for a while. For the meantime you might want to try ExNavigation instead, or just use one of these workarounds. I am going to close this issue.
