### ISSUE TITLE
What happen to docs of react native???

### ISSUE THREAD

**Issue by prashen** [facebook/react-native#8609]
![screenshot 2016-07-06 23 29 00](https://cloud.githubusercontent.com/assets/5449548/16628968/87cd6fde-43d1-11e6-9ff3-d0baa7dad3f5.png)
(the movie and f8 tutorial was on the left side but not now)

I am using react native website and was practicing movie app. Suddenly the page disappear from the site and now i can't find that page. Since evening till now I saw three different documentation pages of react-native site. I am confused here now that where to start studying. I am studying docs but now there are many changes to documentation which makes me again starting it in a new way. Now also unable to test that movie tutorial. Can I get those movie app tutorial url? Or those tutorials are existing in the new site update? (may be I am not getting it).

1. This is a doc url - `https://facebook.github.io/react-native/docs/getting-started.html`

2. Then what's this? a Specific version vise url? Is it?- `https://facebook.github.io/react-native/releases/0.24/docs/getting-started.html`

Please do not make developers confused in the documentation. I know react-native documentation need improvement. Upgrading site should not mean removing some sections or articles. You need to think about that it may possible that some user/developer may be studying that tutorials/article. Stability is important. @lacker

**Comment by lacker** [comment]
We did remove that movie tutorial. We think the current tutorial content is better. I didn't intend to remove it from the old versions of the website, though. If you still want that literal content then you can check the git history.

I do think that sometimes we need to remove articles to make the average article quality better. We removed 5-10 pages but we added in more than we removed. Sorry!
