### ISSUE TITLE
LinkingIOS.addEventListener("url", callback) not getting passed url

### ISSUE THREAD

**Issue by stuartlynn** [facebook/react-native#861]
I am trying to implement callbacks for URL triggering of the app while its running as described here (https://facebook.github.io/react-native/docs/linkingios.html#content). I have added 

    - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString    *)sourceApplication annotation:(id)annotation {
        return [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
    }

to AppDelegate.m and have included 

    componentDidMount:function() {
        LinkingIOS.addEventListener('url', this._handleLoginCallback);
    },
    componentWillUnmount: function() {
      LinkingIOS.removeEventListener('url', this._handleLoginCallback);
    },
    _handleLoginCallback: function(event) {
       console.log(event)
    },

To one of my react components. When the URL is opened in the app the handleLoginCallback function is triggered as expected but event is an empty hash. 

When I set breakpoints in the objective-c code I can see the url being passed correctly all the way through to RTCEventDispatcher#sendDeviceEventWithName but it doesn't seem to be making it through the bridge to the javascript code.

This is using react-native version 0.3.11

**Comment by christopherdro** [comment]
@stuartlynn Are you still having this issue?

**Comment by stuartlynn** [comment]
It seems to be working now. Will close the issue. Thanks for checking in

**Comment by christopherdro** [comment]
:+1:
