### ISSUE TITLE
[0.29.0] `react-native init` broken?

### ISSUE THREAD

**Issue by cpsubrian** [facebook/react-native#8610]
```
$ react-native --version
react-native-cli: 1.0.0
react-native: n/a - not inside a React Native project directory
```

```
$ cd /tmp
$ react-native init TestApp
This will walk you through creating a new React Native project in /private/tmp/TestApp
Installing react-native package from npm...
module.js:327
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/tmp/TestApp/node_modules/react-native/local-cli/generate/generate.js:14:16)
    at Module._compile (module.js:409:26)
    at loader (/private/tmp/TestApp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/private/tmp/TestApp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**/tmp/TestApp/package.json**
```
{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react-native": "0.29.0"
  }
}
```

**Comment by cpsubrian** [comment]
```
$ npm --version
3.8.8
```

**Comment by christopherdro** [comment]
Just came across this as well. Looking into it

**Comment by RobTS** [comment]
Same here when trying to build the iOS application, packager breaks.

**Comment by cpsubrian** [comment]
I also got failures when trying to upgrade an existing app, so I figured "lets start with a fresh one and go from there" :wink:

**Comment by tychota** [comment]
I had this as well. I'm on a PR.

**Comment by cpsubrian** [comment]
Its probably upstream? My `yeoman-environment` folder is empty (no lib). Trying an older version.

![screenshot 2016-07-06 11 43 00](https://cloud.githubusercontent.com/assets/319152/16630358/ea4f59d2-436e-11e6-8e17-bb7a8ad36ab2.png)

**Comment by RobTS** [comment]
Seems it was updated today
![screen shot 2016-07-06 at 20 48 34](https://cloud.githubusercontent.com/assets/1608080/16630536/1be3c6da-43bb-11e6-9ad6-dcb8815316ae.png)

**Comment by tychota** [comment]
Seems that 1.6.1 has a lib directory.

**Comment by christopherdro** [comment]
Ya just noticed that as well. Trying to install the latest manually doesn't work for me either.

**Comment by gabceb** [comment]
Same thing for `react-native upgrade`

**Comment by cpsubrian** [comment]
`react-native upgrade` worked for me after manually installing `yeoman-environment@1.2.7` (note this will only work if on npm>=3 since it flattens everything).

**Comment by RobTS** [comment]
Works for me when adding `"yeoman-environment": "1.6.1"` to `package.json`

**Comment by tychota** [comment]
```
npm install yeoman-environment@1.6.1
cp -R node_modules//yeoman-environment/ node_modules/react-native/node_modules/
```
worked for me to upgrade

**Comment by tychota** [comment]
I'm on a PR that fix the version to 1.6.1.

**Comment by cpsubrian** [comment]
@tychota Or even just lock it to `~1.2.7` (instead of `^1.2.7`). Since that's the last version that was explicitly updated to.

**Comment by kageurufu** [comment]
I created an issue with yeoman-environment, as 1.6.2 tarball has no source files. The best solution would be for them to upload a fixed version

**Comment by tychota** [comment]
Oki @cpsubrian will do this.

**Comment by cpsubrian** [comment]
Agree with @kageurufu, hopefully they are prompt :smile:

**Comment by tychota** [comment]
https://github.com/facebook/react-native/pull/8614

**Comment by tychota** [comment]
Pr done : hopefully reviewed really fast and released as soon as possible.

For those who can't init a new project.
```
npm install -g rninit
rninit init [Project Name] --source react-native@tychota/react-native#dee78a73aa815e59f29d8de1bfc3851363652c9c
```
