### ISSUE TITLE
Documentation: Networking page links to navigators / next page are broken

### ISSUE THREAD

**Issue by valscion** [facebook/react-native#8611]
http://facebook.github.io/react-native/releases/next/docs/network.html

1. > To manage the transition between these screens, you will need to learn about [navigators](http://facebook.github.io/react-native/docs/using-navigators.html).
  
  This "navigators" links is broken and instead redirects to the documentation front page.

2. The "Next →" link is also broken on that page

I'm just following the [We Need Your Help](http://facebook.github.io/react-native/blog/2016/07/06/toward-better-documentation.html#we-need-your-help) instructions here :smile:

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation
