### ISSUE TITLE
Keyboard shortcuts don't work for the simulator

### ISSUE THREAD

**Issue by KishPatel1996** [facebook/react-native#8613]
Somehow my keyboard shortcuts no longer work on the simulator.  I have to simulate a shake gesture to access the developer menu.  Any idea on how to fix this?

**Comment by mroswald** [comment]
Did you check `Hardware > Keyboard > Connect Hardware Keyboard` from the menu or tried it with `⇧ ⌘ K`?

**Comment by KishPatel1996** [comment]
@mroswald That worked!  Thanks so much.
