### ISSUE TITLE
[rnpm] unable to link a @author/modulename module

### ISSUE THREAD

**Issue by ElvisChiang** [facebook/react-native#8623]
react-native 0.29
MacOS / bash
using module: @remobile/react-native-toast

I tried to installed @remobile/react-native-toast first
```
npm install @remobile/react-native-toast --save
```

which package.json would look like
```json
  "dependencies": {
     "@remobile/react-native-toast": "^1.0.4",
```

I tried
```bash
$ react-native link react-native-toast
{ [Error: Cannot find module '/Users/elvis/work/tool/node_modules/react-native-toast/package.json'] code: 'MODULE_NOT_FOUND' }
$ react-native link \@remobile/react-native-toast
{ [Error: Cannot find module '/Users/elvis/work/tool/node_modules/@remobile/package.json'] code: 'MODULE_NOT_FOUND' }
```
the path should be
```
node_modules/@remobile/react-native-toast/package.json
```

**Comment by satya164** [comment]
cc @Kureev

**Comment by Kureev** [comment]
We have exactly the same issue here https://github.com/rnpm/rnpm/issues/182. Let's mark this thread as a "main" for this discussion.

**Comment by Kureev** [comment]
Can somebody give me an access to scoped npm package with RN module inside? Otherwise, I'm unable to test a potential fix.

**Comment by satya164** [comment]
@Kureev what about the example in the issue?

```sh
npm install @remobile/react-native-toast
```

**Comment by Kureev** [comment]
Oh, I was sure it's private. My bad. I'll debug on this one 👍

**Comment by Kureev** [comment]
Quick update: I'll do my best to investigate it before this weekend.

**Comment by rturk** [comment]
I'm having the same issue with  "@exponent/react-native-action-sheet": "^0.2.0"
How to reproduce:
1) Use RN29.1
2) npm @exponent/react-native-action-sheet --save
3) run react-native link

**Comment by Kureev** [comment]
#9118 has been merged, so I assume this issue to be fixed in next release

**Comment by Kureev** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment]
@Kureev tells me to close this issue. If you think it should still be opened let us know why.
