### ISSUE TITLE
Using Modal in an app with status bar hidden = true results in status bar being shown

### ISSUE THREAD

**Issue by RonakKhandelwal** [facebook/react-native#8627]
Bug?

**Comment by satya164** [comment]
Please mention your React Native version and platform.

**Comment by RonakKhandelwal** [comment]
react-native-cli: 0.2.0
react-native: 0.24.1
platform: android
dev platform: macOSX

**Comment by RonakKhandelwal** [comment]
reproducible????

**Comment by satya164** [comment]
Can you also post a screenshot? Are you referring to the grey line at the top?

**Comment by RonakKhandelwal** [comment]
<img width="482" alt="screen shot 2016-07-08 at 3 02 59 pm" src="https://cloud.githubusercontent.com/assets/14109057/16683408/530fcfec-451d-11e6-904d-a1342fdc99c9.png">
<img width="572" alt="screen shot 2016-07-08 at 3 02 48 pm" src="https://cloud.githubusercontent.com/assets/14109057/16683409/5314b688-451d-11e6-9523-125b283ee65e.png">

**Comment by RonakKhandelwal** [comment]
the status bar

**Comment by nihgwu** [comment]
I think the `StatusBar` on `Modal` can't be controlled and will be a blur one on Android right now. 
I remembered there was a PR to add support for `translucentStatusBar` to `Modal` but caused test fail, then the PR was not shipped eventually, around 0.27-0.28

**Comment by nihgwu** [comment]
Well I noticed that you are using RN0.24, so the `StatusBar` on `Modal` will always gray and can't be controlled, after 0.28( or 0.27) it will be a translucent one but still can't make it transparent

**Comment by nihgwu** [comment]
Here it is https://github.com/facebook/react-native/pull/7157 it was introduced in 0.27

**Comment by satya164** [comment]
cc @jemise111

**Comment by nihgwu** [comment]
@satya164 do you work for 24 hours a day... find you at any time and everywhere, it's crazy

**Comment by satya164** [comment]
@nihgwu Haha. I try to be online when I can :D

**Comment by nihgwu** [comment]
@satya164 It will be so great if you have any time to take a look at this one https://github.com/facebook/react-native/commit/1048e5d3445094393298d4e818ff04c41f4e56a7 
It's really a breaking change and i'm sure it will Influence the others
I was trapped by that for days before find the cause and revert that commit manually to avoid the issue #8607

**Comment by nihgwu** [comment]
actually for this issue, there are two different `StatusBar`, turn on the hidden prop will hide the `StatusBar` on the `View` under the `Modal` , the showing `StatusBar` is on `Modal` and can't be controlled or hidden before RN0.27.
so it's not an issue for the newest version

**Comment by satya164** [comment]
@nihgwu Sorry, I've no context on the code.

**Comment by RonakKhandelwal** [comment]
Ohk so versio issue I guess

**Comment by kfiroo** [comment]
@nihgwu I'm having the same issue with RN0.32.0.
I have a view that hides the status bar and opens a `Modal`.
The Modal shows the status bar.
You said it's not an issue after RN0.27.0 - what did you mean? Can I control the status bar for the modal view somehow?
Thanks

**Comment by nihgwu** [comment]
@kfiroo I've explained https://github.com/facebook/react-native/issues/8627#issuecomment-231333690 those are two different StatusBar on View an Modal, you can't control the StatusBar on Modal right now

**Comment by kfiroo** [comment]
@nihgwu Ok, I thought you meant that there is a way after RN27 :)
Thanks!

**Comment by ShaikhKabeer** [comment]
Just go to  styles.xml of android/app/src/main/res/values/styles.xml  and put this code in Base application theme


<style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">
        
    </style>

After putting code, remove generated folders from android/app/build/generated folder and again do 
react-native run-android . It will work

**Comment by netsmertia** [comment]
I am still facing the same issue. Is there any react-native solution.
