### ISSUE TITLE
Hot reloading not reloading when calling React.createClass with a variable

### ISSUE THREAD

**Issue by arthur-xavier** [facebook/react-native#8635]
## The background
I'm trying to setup PureScript with ReactNative. It works properly without Hot Reloading enabled, but when I try using it, it just won't work at all. So I've started debugging it and changing the JavaScript modules (generated by PureScript) by hand.

My `index.android.js` goes like this:
```javascript
require('./output/Notta.Android.Main').main();
```

And inside `output/Notta.Android.Main/index.js` I have:
```javascript
var Notta_App = require("../Notta.App");
module.exports = {
  main: function() {
    return ReactNative.AppRegistry.registerComponent('App', function() { return Notta_App.app; });
  }
};
```

And inside `output/Notta.App/index.js`, where I've spotted the problem:
```javascript
var React = require('react');
var ReactNative = require('react-native');

var spec = {
  render: function() {
    return React.createElement(ReactNative.Text, {}, 'Hello, world!');
  }
};
var app = React.createClass(spec);

var app2 = React.createClass({
  render: function() {
    return React.createElement(ReactNative.Text, {}, 'Hello, world!');
  }
});

module.exports = {
  app: app
};
```

## How it happens
If I use the three (vanilla JS) files as I've shown above, the Hot Module Replacement won't reload. The `Hot loading...` toast shows on my phone screen but nothing happens.

I strongly believe this is a problem with Packager not being able to detect and crawl through changes on variable references for class specs, because if I change the exports for `output/Notta.App/index.js` to `app2` (the class which does not have a variable as specification), then it works:

```javascript
module.exports = {
  app: app2
};
```

### Environment
node v4.0.0
react-native v0.28.0
react-native-cli 1.0.0

_Also worth knowing that I'm testing on a real Android device, not on an emulator._

**Comment by arthur-xavier** [comment]
I believe this might be related to (or maybe the same problem as) #8490 and #8461.

**Comment by davidaurelio** [comment]
HMR basically means enabling https://github.com/gaearon/react-transform-hmr#readme

We only really support React components with the limitations of that project. If the result of the purescript transform is something undetectable by that transform, it will simply not work.
