### ISSUE TITLE
React Native tag Image with Typescript.

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#8638]
I have the following component written in Typescript:
```Typescript
const Welcome = (p: any) => 
  <View>
    <Image source={require('../assets/welcome-background.png')} />
  </View>

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: null,
    height: null
  }
})
```
which compiles to this:
```javascript
const Welcome = (p) => React.createElement(View, null, React.createElement(Image, {source: require('../assets/welcome-background.png')}));
const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: null,
        height: null
    }
});
```

Thus is throwing me this error:
<img width="319" alt="screen shot 2016-07-07 at 2 06 08 pm" src="https://cloud.githubusercontent.com/assets/5099344/16663915/018e7870-444c-11e6-9388-7cb5ef6a145f.png">
Is there a flag or an alternative way to load the images in the source tag? (the image is in where it says to be)

**Comment by ReggaePanda** [comment]
@nschurmann do you have a fix for this error?
