### ISSUE TITLE
Navigator does not pop view until animation has stopped

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react-native#864]
The Navigator component in question is the JS-reimplementation. Here is an example using a ListView. Notice that the back button does not work, until the ListView has stopped scrolling:

3.8MB gif coming up:
![Navigator back button bug]
(http://lum.pe/navigator_bug_listview.gif)

**Comment by ericvicenti** [comment]
Is that a normal ScrollView? I couldn't replicate this in the [navbar example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigationBarSample.js). Could you post a simplified code snippet that shows this bug?

**Comment by johanneslumpe** [comment]
That'S a ListView inside the JS Navigator. Interestingly I also cannot reproduce it in the UIExplorer examples. I'll dig a little deeper and report back when I found something!

**Comment by johanneslumpe** [comment]
I was actually able to confirm the same behavior in the UIExplorer, after adding a timeout, which would call `navigator.pop()` after 1 second. As long as I was scrolling, or the scrollview was moving, the timeout function did not fire. Only ever after the scrolling stopped, the view would be popped. I'll see that I get a basic example done as soon as possible.

**Comment by tadeuzagallo** [comment]
It's probably already been fixed on 75e4e124fa510577865766845fcd0ebd1b8e175a

Before that commit, timers were added to the runloop in `NSDefaultRunLoopMode`, which means it wouldn't fire during UI events, when it's in `UITrackingRunLoopMode`.

The old code is here: https://github.com/facebook/react-native/blob/8a57c4e9807cee5a4196cc50b40bc9e040c02398/React/Modules/RCTTiming.m

Could you confirm if it fixed your problem?

**Comment by johanneslumpe** [comment]
@tadeuzagallo yeah it's fixed now in `0.4` :)

**Comment by deelite1** [comment]
Crystalmurray 200@gmail.com
