### ISSUE TITLE
`Text#letterSpacing` is undocumented

### ISSUE THREAD

**Issue by blackxored** [facebook/react-native#8645]
Hi,
While I gladly found that `letterSpacing` is indeed supported (tested on iOS) there doesn't seem to be a mention of it in the documentation, I was able to find the PR otherwise I wouldn't have known :D

**Comment by christopherdro** [comment]
Hey! You can see style options for the `<Text />` component here: http://facebook.github.io/react-native/releases/next/docs/text.html#style
