### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by sandysaders** [facebook/react-native#8646]
I've been looking into whether `react-native` supports SVG. I'm working on a few charting components that are rendered to SVG and want to make them work on react-native. However I don't know if `react-native` can understand SVG. If it does not support SVG is it something that is in the pipeline to be added into `react-native`?

**Comment by nihgwu** [comment]
You can use `Art` in `react-native` or `react-native-svg`

**Comment by sandysaders** [comment]
@nihgwu  any place I can see examples? I'm not sure what `Art` is. Is it part of `react-native` or is it a third-party library. `react-native-svg` is no longer being maintained, so i'm not sure if thats a good option.

**Comment by nihgwu** [comment]
https://github.com/magicismight/react-native-svg is still in active development and is production ready, why do you say it's no longer being maintained? for `Art`, it's a part of `react-native` and there are only a few documents about it, perhaps you have to read the source code

**Comment by kennetpostigo** [comment]
@nihgwu , My mistake I thought that was another project I had seen abour react-native svg that said it was no longer being maintained.

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot feature

**Comment by facebook-github-bot-7** [comment]
Hey @sandysaders! Thanks for opening the issue, however it looks like a feature request. As noted in the [Issue template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) we'd like to use the GitHub issues to track bugs only. Can you implement the feature as a standalone npm module? If not consider sending a pull request or a create an entry on [Product Pains](https://productpains.com/product/react-native). It has a voting system and if the feature gets upvoted enough it might get implemented. Closing this now, thanks for understanding!

**Comment by seekshiva** [comment]
I just published a new package that lets you load remote svg images!

`react-native-remote-svg`

https://yarnpkg.com/en/package/react-native-remote-svg
