### ISSUE TITLE
[Android] Container borderRadius covered by sub view

### ISSUE THREAD

**Issue by ldn0x7dc** [facebook/react-native#8649]
![qq20160708-0 2x](https://cloud.githubusercontent.com/assets/3940989/16677759/883b6ddc-450b-11e6-9fa4-56bf0fb886e1.png)
The sub view does not respect container border radius.
Problem exists only  on Android (on iOS, using `overflow: 'hidden'` will solve it).
I'm using react-native 0.28.
Example:

```
<View
  style={{height: 40, borderRadius: 20, backgroundColor: 'red', paddingHorizontal: 5, overflow: 'hidden'}}>
  <View style={{flex: 1, backgroundColor: '#0000ff66'}}/>
</View>
```

**Comment by SudoPlz** [comment]
I have the same exact problem using an Image child..!

**Comment by mwiley** [comment]
I'm having this problem on 0.32.

**Comment by mwiley** [comment]
https://github.com/facebook/react-native/issues/3198

This looks like the same issue.

**Comment by lacker** [comment]
Let's use https://github.com/facebook/react-native/issues/3198 instead - it has more discussion and the two issues are dupes. TLDR work is in progress to fix this
