### ISSUE TITLE
ListView initialListSize and pageSize does not work

### ISSUE THREAD

**Issue by aliouchka** [facebook/react-native#8650]
hi, i'm trying to set the ListView initialListSize  and pageSize but it does not work, i'm still having all my datasource rendered, can someone help please ? thx ^^

**Comment by antoxi4** [comment]
+1

**Comment by nickzuber** [comment]
Bump

**Comment by besarthoxhaj** [comment]
You probably have your ListView nested inside a ScrollView or something similar. You can either move it out or give your ListView a height (stylewise).

```js
<ListView
  style={{height:400}}
  initialListSize={10}
  // ...
/>
```

**Comment by ericnakagawa** [comment]
Hi @aliouchka, this is an old issue. I'm hoping you've been able to resolve this issue on your own.

**Comment by tiempham** [comment]
@ericnakagawa can You link this issue!
