### ISSUE TITLE
[Docs] Update docs for "Running on Device"

### ISSUE THREAD

**Issue by jefflau** [facebook/react-native#8651]
Hi there,

I'm new to React Native and I was having problems with Running on Device yesterday on iOS. I was following this section of the docs:

https://facebook.github.io/react-native/docs/running-on-device-ios.html

I realised after I was using 0.28 and in the latest stable release 0.29 you don't have to change `localhost` to your IP Address on the network as stated in these docs.. In fact I couldn't even find localhost in the `AppDelegate.m` so this part no longer seems relevant and may be confusing to people reading it.

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by inetfuture** [comment]
I'm curious, how does it work now?

**Comment by charpeni** [comment]
@inetfuture You can refer to 8c29a52c54392ce52148e7d3aa9f835537453aa4

**Comment by inetfuture** [comment]
get it, thanks
