### ISSUE TITLE
[0.29] After 'react-native upgrade' from 0.28, 'react-native run-android' does not work as expected.

### ISSUE THREAD

**Issue by gijoehosaphat** [facebook/react-native#8653]
So I followed the steps for upgrading to 0.29 outlined in the release notes here:
`https://github.com/facebook/react-native/releases/tag/v0.29.0`
I upgraded from 0.28.

I upgraded any modules that were previously passing the Activity in the constructor, and the app builds successfully. However it does not run via `react-native run-android` due to the switch in the AndroidManifest to set the activity name to '.MainApplication' instead of '.MainActivity'. Here is the error:
`Starting the app on 192.168.56.102:5555 (/usr/local/opt/android-sdk/platform-tools/adb -s 192.168.56.102:5555 shell am start -n com.myapp/.MainActivity)...
Starting: Intent { cmp=com.myapp/.MainActivity }
Error type 3
Error: Activity class {com.myapp/com.myapp.MainActivity} does not exist.
`

I can clearly see that the command is still asking to launch from '.MainActivity'. And looking at `react-native-local-cli/runAndroid/runAndroid.js` still has hardcoded references to '.MainActivity':
`$ cat node_modules/react-native/local-cli/runAndroid/runAndroid.js | grep 'MainActivity'
        const adbArgs = ['-s', device, 'shell', 'am', 'start', '-n', packageName + '/.MainActivity'];
        'shell', 'am', 'start', '-n', packageName + '/.MainActivity'
`

What's the deal? Did I miss something? Is there another package I should be using/upgrading to get this working again?

**Comment by satya164** [comment]
Do you have sample code somewhere where we can take a look?

**Comment by gijoehosaphat** [comment]
Unfortunately it is a private repo. Is this expected to work?

If you have specific questions about specific files I can share them.

For the record, creating a fresh RN install on 0.29 does work and the app launches in the same manner. I've tried to track down everything I can between the two projects to see what I may have missed that is different, but no such luck. Fresh install seen here:
`Starting the app on 192.168.56.102:5555 (/usr/local/opt/android-sdk/platform-tools/adb -s 192.168.56.102:5555 shell am start -n com.awesomeproject/.MainActivity)...
Starting: Intent { cmp=com.awesomeproject/.MainActivity }`

**Comment by satya164** [comment]
@gijoehosaphat Share your MainActivity, MainApplication and AndroidManifest.xml files.

**Comment by fab1an** [comment]
I had to use a fully qualified name for both package and activity: `android:name="my.company.MainApplication"` `android:name="my.company.MainActivity"` to make it work.

It might have to do with build-variants and changed application-ids.

**Comment by satya164** [comment]
@fab1an That shouldn't be necessary. I'm going to close this issue since the migration instructions are written in the release notes.

**Comment by fab1an** [comment]
@satya164 OK. For me it didn't work using the dot-notation `.MainActivity`.

**Comment by satya164** [comment]
@fab1an Did you try clearing the gradle cache `./gradlew clean` and deleting the build folder?

**Comment by fab1an** [comment]
I don't remember, I'll give it a try later, thanks.

**Comment by wodezhuanshu** [comment]
@satya164   ` package="shanyao.simpleapp"> `   ` <application
        android:name="shanyao.simpleapp.application.SYApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity
            android:name="shanyao.simpleapp.MainActivity"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>`

MainActivity.java

`
package shanyao.simpleapp;
public class MainActivity extends ReactActivity {

    @Override
    protected String getMainComponentName() {
        return "simpleapp";
    }


}`

Starting the app on 8ed93e0 (D:\Android\sdk/platform-tools/adb -s 8ed93e0 shell am start -n shanyao.simpleapp/.MainActivity)...
Starting: Intent { cmp=shanyao.simpleapp/.MainActivity }
Error type 3
Error: Activity class {shanyao.simpleapp/shanyao.simpleapp.MainActivity} does not exist.


could you help me ?

**Comment by wodezhuanshu** [comment]
@satya164   my RN version  
     "react": "15.3.2",
    "react-native": "0.36.1"
