### ISSUE TITLE
Inconsistent ListView Separator line width

### ISSUE THREAD

**Issue by latusaki** [facebook/react-native#8655]
Something is off with the rendering of rows / separators in ListView, on specific Android screen sizes.

The effect can be seen on this screenshot:

![screen shot 2016-07-08 at 15 04 38](https://cloud.githubusercontent.com/assets/2336352/16690292/09dd4370-451f-11e6-84a5-5bb8f9356ba5.png)

If the width of the separator changes to 0.5, then we get some separators hidden completely:
![screen shot 2016-07-08 at 15 18 36](https://cloud.githubusercontent.com/assets/2336352/16690331/43cee0e8-451f-11e6-9e0a-b0e3d1b58eac.png)

I cannot reproduce this when using 'borderBottom' on the example application, although on my mobile app, there are still issues even when using that.

The actual device where this problem was found is:
Galaxy Samsung Ace 4, Android v4.4.4 (4", 480 x 800 pixels)

This can be reproduced with at least one default android emulator:
Nexus One (3.7", 480 x 800: hdpi) Android 5.1.1 - API Level 22

I have reproduced this with android API 19 and 23 on same screen size.

Have tested with RN 25, 28, 29.

An example application that will reproduce the issue on the said emulator:
https://rnplay.org/apps/uQNuXg

**Comment by latusaki** [comment]
Another strange behavior, when adding borderBottom to the rows as well as having a separator, they both render.

![image](https://cloud.githubusercontent.com/assets/2336352/16692859/8ae61086-452a-11e6-8287-2063984aa939.png)

**Comment by nihgwu** [comment]
I think it's just a visual issue on scaled emulator, you will find that it works great on real devices
I use `StyleSheet.hairlineWidth`(== 1/PixelRatio.get()) everywhere in my app, and have the save visual problem on both Android and iOS emulators but it works pretty nice on real devices

**Comment by latusaki** [comment]
No, as mentioned on ticket, this happens on an actual device as well.
On 8 Jul 2016 6:15 p.m., Neo <notifications@github.com> wrote:I think it's just a visual issue on scaled emulator, you will find that it works great on real devices
I use StyleSheet.hairlineWidth(== 1/PixelRatio.get()) everywhere in my app, and have the save visual problem on both Android and iOS emulators but it works pretty nice on real devices

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/inconsistent-listview-separator-line-width

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by JonasJonny** [comment]
http://stackoverflow.com/questions/38012355/reactnative-listview-inconsistent-separator-lines/42147001#42147001

**Comment by Jacse** [comment]
Still seeing this on actual devices. @JonasJonny unfortunately your link contains no fix.

**Comment by RobCherry** [comment]
I am seeing the same issue on FlatList on certain devices (specifically the Nexus 5X, which has a PixelRatio of 2.625).

**Comment by rasmniel** [comment]
Same here on a Nexus 5x. Generally seems to be happening to border styling inside lists.

**Comment by andidev** [comment]
Still there in 0.54.3
