### ISSUE TITLE
[iOS 9.3][0.29.0] onLayout does not work on immediate child of TouchableWithoutFeedback

### ISSUE THREAD

**Issue by rclai** [facebook/react-native#8656]
I tested this inside an iPhone 6s Simulator.

It works inside `TouchableOpacity` and `TouchableHighlight` though. I have not tested in Android.

``` jsx
<TouchableWithoutFeedback>
  <View
    onLayout={({ nativeEvent }) => {
      // This log doesn't happen
      console.log(nativeEvent);
    }}
    style={{
      width: 10,
      height: 10,
    }} />
</TouchableWithoutFeedback>
```

I have to put `onLayout` on the `TouchableWithoutFeedback` as a workaround.

**Comment by yueshuaijie** [comment]
Is this same problem as #8755 ?

**Comment by ide** [comment]
Great call. Sure looks like it: https://github.com/facebook/react-native/blob/65ff8192dd6a542485d1ea0647eadee44d76a55b/Libraries/Components/Touchable/TouchableWithoutFeedback.js#L175

You'll have to put your onLayout handler either on the TouchableWithoutFeedback component or a child of the View.

**Comment by stenrap** [comment]
I'm seeing the same problem with RN 0.29.1 on both an iPad (iOS 9.3) and a Samsung Galaxy S6 (Android 6.0.1); however, in my case putting `onLayout` on the `TouchableWithoutFeedback` is not working. Here's what I'm returning from `render()`:

```javascript
return (
    View({},
        Modal({animationType: 'none', onRequestClose: () => {}, transparent: true},
            TouchableWithoutFeedback({onPress: () => this.backgroundTapped()},
                View({style: [styles.modalContainer, {height: Dimensions.get('window').height, width: Dimensions.get('window').width}]},
                    ListView({
                        dataSource: this.props.dataSource,
                        pageSize: 100,
                        renderRow: (rowData) => this.renderRow(rowData),
                        scrollRenderAheadDistance: 44 * 60,
                        style: [styles.listContainer, {left: (Dimensions.get('window').width - 282) / 2, top: (Dimensions.get('window').height - (44 * 7)) / 2}]
                    })
                )
            )
        )
    )
);
```

I've tried putting `onLayout` on the out outer View, the Modal, the TouchableWithoutFeedback, the inner View, and the ListView—but it doesn't work anywhere. It does, however, work on the outer view in the iOS Simulator.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-930290-onlayout-does-not-work-on-immediate-child-of-touchablewithoutfeedback

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by meros** [comment]
I am still seeing this issue in 0.50
