### ISSUE TITLE
[Android][0.29] No longer possible to access Activity from SimpleViewManager

### ISSUE THREAD

**Issue by marcshilling** [facebook/react-native#8661]
According to the 0.29.0 upgrade docs, it's now very easy to extend `ReactContextBaseJavaModule` and  use `getCurrentActivity` to get the activity reference in native Android **modules**. However, it no longer appears to be possible to get access to the current activity from native Android **UI Components**.

Continuing a discussion started [here](https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d#commitcomment-18177188), I need access to the activity so that I can create a `FragmentManager` to add a `Fragment` to the `FrameLayout` being vended from `SimpleViewManager`. There was a suggestion that `ReactContext.getCurrentActivity()` be made public, which seems like a bad idea, but I can't think of another way.

**Comment by satya164** [comment]
Have you tried https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d#commitcomment-18177294 ?

**Comment by marcshilling** [comment]
Yeah, that's me discussing the issue in those comments also 😛 . After that discussion went nowhere, I decided to open this issue.

**Comment by satya164** [comment]
@marcshilling yes, but you didn't reply if `view.getContext` works.

**Comment by marcshilling** [comment]
It didn't.

**Comment by InnerPeace080** [comment]
hi . this is my workaround to solve this problem . hope it will help u
https://github.com/InnerPeace080/react-native/commit/c0838f0ce3f7348dfcce96b56b685bcc4a633edf

**Comment by marcshilling** [comment]
@InnerPeace080 you should send a pull request so we can get this in core!

**Comment by nickjanssen** [comment]
+1 I also cannot access Activity any longer, I need it in the constructor phase in order to get a SplashScreen working. Calling `getCurrentActivity()` in the constructor simply returns null.

```
public class SplashScreen extends ReactContextBaseJavaModule {

    public SplashScreen(ReactApplicationContext reactContext) {
        super(reactContext);

        getCurrentActivity() // null
    }
```

**Comment by marcshilling** [comment]
@nickjanssen that's actually different from the issue being discussed here. You are extending `ReactContextBaseJavaModule`, which has access to `getCurrentActivity()`. See [this comment](https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d#commitcomment-18092224) about why you can't use `getCurrentActivity()` in the constructor.

This issue is regarding `SimpleViewManager` extensions not having `getCurrentActivity()`, which is an issue that still remains in `0.30.0`.

**Comment by skevy** [comment]
@foghina any thoughts on this? Seems like something super useful to get fixed.

**Comment by foghina** [comment]
Having `getPackages` take an `Activity` parameter is a much worse idea than making `ReactContext#getCurrentActivity()` public, for the following reasons:

1. We don't want to tie package / module / viewmanager creation to an `Activity`, as we want to be able to initialize a react instance in any context.
2. As the *current* in `getCurrentActivity()` suggests, the `Activity` can change over time. Holding a reference to whatever the activity was at react instance creation time is both incorrect and a memory leak.

As long as we properly document `getCurrentActivity()` (I think it already is documented in caps that you shouldn't hold references to the result), it should be fine to make it public.

**Comment by marcshilling** [comment]
This is fixed in `v0.31.0` because you can now call `getCurrentActivity()` on `ReactApplicationContext` 👍

**Comment by lschmierer** [comment]
In `SimpleViewManager#createViewInstance()`, `ThemedReactContext#getCurrentActivity()` seems to return `null`.
This is probably because of the `Activity` is not initialized when `ReactNativeHost` is created in the `Application`.

**Comment by marcshilling** [comment]
@lschmierer correct

**Comment by lschmierer** [comment]
So, what to do in this case? Is there any way to create the `ViewManager` later on?

**Comment by marcshilling** [comment]
I'm not sure. What I'm doing is creating a placeholder object:
```java
    @Override
    protected FrameLayout createViewInstance(ThemedReactContext context) {
        mFrameLayout = new FrameLayout(context);
        return mFrameLayout;
    }
```

And then actually doing the work of adding the activity-dependent view to the FrameLayout later on when props change.

**Comment by lschmierer** [comment]
Thank you, this seems to be a decent woraround!

**Comment by foghina** [comment]
> In `SimpleViewManager#createViewInstance()`, `ThemedReactContext#getCurrentActivity()` seems to return `null`.

Hmm, that's a bug IMO. It happens because we call `startApplication` in `onCreate()` but we only set the current activity in `onResume()`. Created #9310 to track,

**Comment by lschmierer** [comment]
`ThemedReactContext#getCurrentActivity()` seems to be allways `null` in react-native version 0.31.0. At least on property setting it is still `null`.
@marcshilling on which react-native version did your workaround worked?

**Comment by ankitsinghania94** [comment]
@marcshilling I have follow the same procedure to implement VrVideo in React Native that u have done in https://github.com/XebiaStudio/react-native-google-vr-panorama 
But after passing context activity to VrVideoView (activity).. i m getting a  error 
![screen shot 2016-12-22 at 1 51 59 pm](https://cloud.githubusercontent.com/assets/23092940/21419488/eadb4640-c84d-11e6-82f1-565aa79baa30.png)
![screen shot 2016-12-19 at 7 31 59 pm](https://cloud.githubusercontent.com/assets/23092940/21419506/08353840-c84e-11e6-87e3-b049d4f056cc.png)
