### ISSUE TITLE
[iOS 7.1.2][0.29.0] RCTPushNotificationManager throws NSInvalidArgumentException [UIConcreteLocalNotification category]

### ISSUE THREAD

**Issue by jan-happy** [facebook/react-native#8662]
Tested my app on an old iPhone 4 with the latest iOS Version for it.
Runs fine on other devices with iOS 8&9, but raises this exception on iOS 7.1.2

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIConcreteLocalNotification category]: unrecognized selector sent to instance 0x15df9cb0'

Commenting out line 45 and 75 in RCTPushNotificationManager.m fixed it for me since I don't need categories in my local push notifications.

```
45 //notification.category = [RCTConvert NSString:details[@"category"]];
75 //formattedLocalNotification[@"category"] = RCTNullIfNil(notification.category);
```

**Comment by Dean177** [comment]
I am having the same problem. Does iOS 7.1.2 not support categories for notifications?

**Comment by jan-happy** [comment]
Yes, categories came with iOS 8. Could anyone patch this? Right now, Notifications are unusable in iOS 7.

**Comment by Dean177** [comment]
I have absolutely no idea what i am doing in objective-c, but would something like:
```objective-c
#define SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)

if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"6.0")) {
    notification.category = [RCTConvert NSString:details[@"category"]];
}

...

if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"6.0")) {
    formattedLocalNotification[@"category"] = RCTNullIfNil(notification.category);
}
```

**Comment by jan-happy** [comment]
Yes, that should do it!
Could maybe @corbt or @nicklockwood look into it? It totally breaks PushNotifications under iOS 7.
Thank you!

**Comment by corbt** [comment]
Sorry, only have time for dealing with my own bugs for the moment. :)

**Comment by Dean177** [comment]
It looks like this is now moot:
React native v0.34 drops iOS 7 support:
https://github.com/facebook/react-native/commit/07553d0f1c61173edad804c4e7a93c902719e05b

**Comment by ericnakagawa** [comment]
Hi @jan-happy, I'm closing this issue since RN no longer supports iOS 7. Were you able to find a suitable workaround?
