### ISSUE TITLE
[iOS10] Transparent images broken

### ISSUE THREAD

**Issue by aprilzero** [facebook/react-native#8665]
All images that use pngs with alpha transparency (in our app there are a lot of them, so this has been particularly catastrophic) are rendering incorrectly in the latest iOS10 version.

Our usage is pretty standard... `<Image source={require('image.png')} />` and a png-24 with alpha channel.

Here are some examples of what it looks like when broken:

![image](https://cloud.githubusercontent.com/assets/114380/16703343/631b769e-4521-11e6-912b-3fa2d82f13f1.png)

![image](https://cloud.githubusercontent.com/assets/114380/16703328/422378f6-4521-11e6-930b-541897e9cfcc.png)

![image](https://cloud.githubusercontent.com/assets/114380/16703492/f532e020-4522-11e6-8c1d-d6b994fb3e02.png)

At first we thought it was just not able to load the images, but it seems it is just a problem with rendering any images that are transparent. 

I'm not sure if this is just an iOS bug or something related to React Native's implementation of the images. It is a new issue in Beta 2. However, other apps don't seem to be running into this problem, and Apple just released it as a public beta for anyone to start using, so that is a bit worrying.

Has anyone else experienced this issue? Is there some new thing needed to let images use transparency?

**Comment by piotrbielaska** [comment]
Hi. I have installed iOS 10 public beta 1 and I have same bug in Gyroscope. I wasn't able to find it in any other app I use.

**Comment by brentvatne** [comment]
We have noticed this too. @javache @bestander - any idea if you guys have seen this on fb apps and have a fix internally?

**Comment by myusuf3** [comment]
it occurs in tweetbot and moves as well, not a strictly react native issue.

**Comment by bestander** [comment]
Shared internally

**Comment by s-bz** [comment]
Also affects Safari, Google Maps etc.

**Comment by leecade** [comment]
👍

**Comment by paramaggarwal** [comment]
I believe this is not related to React Native. Seeing this across the system.

**Comment by eduardinni** [comment]
Fixed in iOS 10 beta 4 (Developer)
