### ISSUE TITLE
RN creates thousands of native TextViews [Performance] 

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8670]
I'm looking into improving performance and used AndroidStudio to track memory allocation while pressing a button to switch from one screen to another.

This is what I found:
![screen shot 2016-07-09 at 11 25 31](https://cloud.githubusercontent.com/assets/55547/16707267/34cbc3aa-45c8-11e6-983b-8430a9171172.png)

RN seems to create thousands of TextViews for a layout pass. Why is that the case?

- Version: 0.29
- Android
- Mac

**Comment by astreet** [comment]
What does this UI look like? The text view create calls you're seeing are coming from ReactJS if those are the stack traces you're seeing, which I would only expect if you're app actually has a ton of <Text> views in it.

**Comment by fab1an** [comment]
It consists of a list with a a modal form displayed over it. 
There are about 60 textviews displayed, certainly not 2800. 


-- 
Sent from my iPhone

**Comment by astreet** [comment]
It also seems to be creating 60 EditTexts? How many of those are in the app? Are you sure this isn't counting across reloads? If so, can you paste your app code?

**Comment by fab1an** [comment]
I have two or three `EditText`s. This is not across reloads. Just tested again: Switching from my LoginScreen to my HomeScreen reproducibly creates exactly 192 `TextView`s.

Can't share my app code directory because of company guidelines, but maybe I can create a test-case later, if I have time.

**Comment by fab1an** [comment]
Ok, I can share this, it's my root-"navigator" component, that does my fading and so on:

```jsx
import { View, Animated } from 'react-native';
import React, { PropTypes as pt } from "react";
import { checkState } from "util/Preconditions";
import _ from "lodash";
import * as components from "./components";
import ModalShade from "./ModalShade";
import { Logger } from "util/logging/Logger";

const L = Logger.getLogger("MyNavigator");

class MyNavigator extends React.Component {
    static propTypes = {
        currentScene: pt.object.isRequired,
        modalView: pt.object
    }

    state = {
        animate: false,
        fadeAnim: new Animated.Value(),
        previousScene: null
    }

    render() {
        /* current scene by props */
        const currentScene = this.props.currentScene;

        /* previous scene is set in state */
        const previousScene = this.state.previousScene;

        /* modalView */
        const modalView = this.props.modalView;

        return (
            <View cls="flx-i">
                {/* PREVIOUS SCREEN */}
                {this.previousScene
                 ? <Animated.View
                     cls="absolute--fill"
                     key={previousScene.name}
                     style={{
                         opacity: this.state.fadeAnim.interpolate({
                             inputRange: [0.5, 1],
                             outputRange: [1, 0]
                         })
                     }}
                   >
                       {React.createElement(components[previousScene.name], previousScene)}
                   </Animated.View>
                 : null}
                {/* NEW SCREEN */}
                <Animated.View
                    cls="absolute--fill"
                    key={currentScene.name}
                    style={{opacity: this.state.fadeAnim}}
                >
                    {React.createElement(components[currentScene.name], currentScene)}
                </Animated.View>
                {/* MODALVIEW */}
                {modalView
                 ? <View
                     cls="flx-i"
                     key={modalView.name}
                   >
                       {React.createElement(components[modalView.name], modalView)}
                   </View>
                 : null}
            </View>
        )
    }

    componentWillReceiveProps(nextProps) {
        if (this.props.currentScene.name === "LoginScreen" && nextProps.currentScene.name === "HomeScreen") {
            this.setState({
                animate: true,
                previousScene: this.props.currentScene
            })

        } else {
            this.setState({
                animate: false,
                previousScene: null
            })
        }
    }

    componentDidUpdate() {
        if (this.state.animate) {
            this.state.fadeAnim.setValue(0.5);
            Animated.timing(
                this.state.fadeAnim,
                {toValue: 1}
            ).start();
        }
    }
}
```

**Comment by astreet** [comment]
This is not going to be easy for me to look into without something reproducible on my end: it doesn't look like I can run that?

I wonder if each animation frame is somehow creating and throwing away a scenes-worth of text views?@sahrens, do you see any issues with the use of animated here?

**Comment by fab1an** [comment]
If you don't have any further tips i can try out on my end, I'll investigate more and create a working test-case, I just want to spare myself the time, if possible. Thanks.

**Comment by astreet** [comment]
Yeah sorry, I don't have any tips: this isn't something I've seen before.

**Comment by fab1an** [comment]
NP, I got a bad conscious because of opening so many bugs in RN anyway ;).

**Comment by fab1an** [comment]
Okay, I've created a runnable example. Add these 5 files to a vanilla react-native project:

https://gist.github.com/fab1an/c13d1887bedc4fe76b6ae3529778f4fb

When I run that using Android Studio and tap to switch from `View1` to `View2` I get 54 allocated `TextView`s :

![screen shot 2016-07-12 at 15 23 41](https://cloud.githubusercontent.com/assets/55547/16768593/3ee0bcae-4845-11e6-82e5-a912a29c2547.png)

**Comment by fab1an** [comment]
@astreet Is that enough for you to check it out?

**Comment by astreet** [comment]
I got your app running but am not seeing a bunch of view commands being sent to Java (see screenshot). I also don't see any animation in your demo. Can you set SPY_MODE = true in MessageQueue.js and tell me if you see something similar to this screenshot when you run `adb logcat | grep createView`, or if you see a lot more createView's?

![screen shot 2016-07-14 at 13 32 38](https://cloud.githubusercontent.com/assets/594924/16839608/e69d4cfe-49c7-11e6-9a30-14bcabbcef79.png)

**Comment by fab1an** [comment]
The animation in the sample just jumps from 0-100 and isn't really animated. 

I have the same output you have:

![screen shot 2016-07-14 at 14 55 04](https://cloud.githubusercontent.com/assets/55547/16840098/13a98bf8-49d3-11e6-8860-c0c3a21cacc6.png)

Still, tested again with Android Studio monitor: 54 TextViews created.

**Comment by astreet** [comment]
I think something is either up with Android Studio or up with the methodology you're using: are you sure you aren't forgetting to clear tracked allocations between reloads or something? Here's what I just tested:

I put a static count int in ReactTextView.java that counts the number of times the constructor is called and prints it using `android.util.Log`. I counted 8 total. I also put a breakpoint in the android system `TextView` constructor and again counted 8 constructions. Can you also repro this on your end?

**Comment by fab1an** [comment]
Hm… I get to same results. I think I read the results wrong: These aren't actually allocations of `TextView`s, but various theme-related objects that are instantiated in the constructor.

Since the TextView has many cascading constructors that is why there are so many invocations of `<init` listed…
