### ISSUE TITLE
[0.29.1] Commits to cherry pick

### ISSUE THREAD

**Issue by satya164** [facebook/react-native#8676]
cc @grabbou

**Comment by satya164** [comment]
c0316c695d679ba2d8157904014e1d3849a811fa

**Comment by stoffern** [comment]
c3f4d79 - Fix for "react-native link"

**Comment by satya164** [comment]
https://github.com/facebook/react-native/commit/6d3c7b8a4c1d1a0552a21cfabe03a8d1f344d1ed - Fix 'Unexpected EOF' in old bridge

**Comment by AndrewJack** [comment]
https://github.com/facebook/react-native/commit/b5c3550857bd7360e7b5b6e227d795f859202245 - "Don't hard crash if you get a null stack trace in Android"

**Comment by satya164** [comment]
9b184cc0f43194f8db73d2fea0b23b1284c487f9 - Fix bug in cancelling last task in TaskQueue

**Comment by charpeni** [comment]
65ff8192dd6a542485d1ea0647eadee44d76a55b - Remove instructions about IP address on iOS

**Comment by grabbou** [comment]
Closing as all were cherry-picked and release is being made now.
