### ISSUE TITLE
Error: EPERM: operation not permitted, open 'C:\Users\Win8\.babel.json'

### ISSUE THREAD

**Issue by ubillythekid** [facebook/react-native#8678]
Hi everybody!
I get this error when I try to create AwesomeProject
runnins as admin, running powershell as admin 
I try to folow this tutorial:
https://facebook.github.io/react-native/docs/getting-started.html
I use Genymotion as a emulator provider.
In fact everything was "up and running" yesterday, when I used the same command, I know because I even got the AwesomeProject running  in emulator(nexus 7 tablet)
So I deleted the project, cause I wanted to make a new one.
I'm a beginner in programming(I didnt work with javascript or node.js before)

I only know some php.

..........................................................................................
PS C:\rnprojects> react-native init AwesomeProject
This will walk you through creating a new React Native project in C:\rnprojects\AwesomeProject
Installing react-native package from npm...
Setting up new React Native app in C:\rnprojects\AwesomeProject
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\Win8\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.writeFileSync (fs.js:1327:33)
    at save (C:\rnprojects\AwesomeProject\node_modules\babel-register\lib\cache.js:57:40)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
.....................................................................................................................
I think you can see the versions here probably the latest stable version of anything:

 "_from": "react-native-cli@latest",
  "_id": "react-native-cli@1.0.0",
  "_inCache": true,
  "_installable": true,
  "_location": "/react-native-cli",
  "_nodeVersion": "4.4.5",
  "_npmOperationalInternal": {
    "host": "packages-16-east.internal.npmjs.com",
    "tmp": "tmp/react-native-cli-1.0.0.tgz_1464957130165_0.2410504559520632"
  
  },
  "_npmVersion": "2.15.5",
  "_phantomChildren": {},
  "_requested": {
    "name": "react-native-cli",
    "raw": "react-native-cli",
    "rawSpec": "",
    "scope": null,
    "spec": "latest",
    "type": "tag"
 ............................................
dependencies": {
    "chalk": "^1.1.1",
    "minimist": "^1.2.0",
    "prompt": "^0.2.14",
    "semver": "^5.0.3"

Thanks in advance!

**Comment by ubillythekid** [comment]
Issue solved:my User folder eas in read-only

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-0** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.

**Comment by blemelin** [comment]
About this issue, I noticed that on Windows, the same problem can happen if the file is marked as hidden.
