### ISSUE TITLE
usage of zIndex in Stylesheet.create() results in an error.

### ISSUE THREAD

**Issue by KishPatel1996** [facebook/react-native#8683]
In the specs and docs, there seems to be a way to set zIndex [here](http://facebook.github.io/react-native/releases/0.29/docs/layout-props.html#zindex), but setting zIndex throws an error saying zIndex cannot be set.  Any idea of what may be causing this?

**Comment by satya164** [comment]
zIndex was added in 0.30-rc. You're probably using an old version. Please wait till 0.30-rc becomes stable.
