### ISSUE TITLE
Anyone using react-native bundle command but generated a .jsbundle.meta file?

### ISSUE THREAD

**Issue by joint-song** [facebook/react-native#8686]
I upgraded react-native to 0.29.
Using `react-native bundle` command in terminal will generated a new .jsbundle.meta file. But it did not seem to have much effect. Helps.

**Comment by joint-song** [comment]
Maybe my fault.

**Comment by joint-song** [comment]
It mybe my fault.

**Comment by huangqiaobo** [comment]
@joint-song 
I use 0.30, and find the file,too.
What this file is used for ?

**Comment by alloy** [comment]
@davidaurelio I’m also not sure what the purpose of this file introduced in ae6afcf3f65a84fa45dd999a916e33285b41d640 is. Is it a build artefact only or should we be saving these along with bundles and source maps?

**Comment by davidaurelio** [comment]
Sorry for all the confusion. The file contains the sha1 of the bundle (20 bytes) and an encoding byte (0 = unknown, 1 = ascii, 2 = utf8, 3 = utf16).

I will hide it behind a flag
