### ISSUE TITLE
Warning message points to URL only accessible within Facebook internal network

### ISSUE THREAD

**Issue by ccheever** [facebook/react-native#869]
The file `packager/react-packager/src/DependencyResolver/haste/polyfills/Array.prototype.es6.js` contains the follow error message:

```js
          get: function() {
            console.error(
              'Your code is broken! Do not iterate over arrays with ' +
              'for...in. See https://fburl.com/31944000 for more information.'
            );
          }
```

The URL will only load inside the Facebook network.

It probably should be changed to something publicly accessible.

**Comment by brentvatne** [comment]
It looks like this is gone now :smile:
