### ISSUE TITLE
NPM modules get required from wrong directory

### ISSUE THREAD

**Issue by jnyryan** [facebook/react-native#8695]
Fresh install of react-native sample project following Getting Started Guide for iOS and Mac.

Looks like npm is looking for the modules in a directory lower than the app directory, directly in ```/Users/j/tmp``` rather than in ```/Users/j/tmp/AwesomeProject```

```
brew install watchman
npm install -g react-native-cli
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

Trying to run the sample project, emulator starts and displays redbox error.

```
Unable to resolve module /Users/j/tmp/node_modules/redbox-react/lib/index.js from 
/Users/j/tmp/AwesomeProject/index.ios.js: 
Unable to find this module in its module map or any of the node_modules directories under 
/Users/j/tmp/node_modules/redbox-react/lib/index.js and its parent directories ...",
```

Platform: OSX 10.11.5,  nvm: 0.31.1, Node: v6.0.0, react": "15.2.1", "react-native": "0.29.0"

**Comment by Tenkir** [comment]
I'm having this issue as well.

**Comment by Tenkir** [comment]
#4968

**Comment by jnyryan** [comment]
@tenkir I saw that issue, the workaround didn't fix the failure. FWIW it was on a relatively fresh machine, never had react before and node installed with nvm.

**Comment by jnyryan** [comment]
I recreated the project in a new folder (i.e. not ~/tmp) and it worked. Could be the use of that folder but i cannot confirm that.
