### ISSUE TITLE
undefined is not an object (evaluating 'RNI18n.locale')

### ISSUE THREAD

**Issue by cadr-sa** [facebook/react-native#8697]
Hello , I'm using fresh install , and every time I try to run the app (IOS and Android). I get the following error
![screen shot 2016-07-11 at 8 31 04 pm](https://cloud.githubusercontent.com/assets/1207996/16740193/8fa394f8-47a6-11e6-8db0-685ede7dedf8.png)

node -v : v6.4.0
npm -V : 3.10.3
react: 15.2.1
react-native:0.29.0
OS: OS X EL Capitan 10.11.5
xcode : 7.3.1

**Comment by yarnball** [comment]
I am having the same problem. Did you resolve this?
