### ISSUE TITLE
NavigationTransitioner props and previousProps inconsistent

### ISSUE THREAD

**Issue by dguillamot** [facebook/react-native#8700]
Hello, 

I'm using RN v0.29. In v0.28, NavigationTransition was working well with the renderScene prop. Now, in v 0.29 - I've seen the recent changes to NavigationTransitioner to use a render() prop and pass currentProps and previousProps to the render() prop so that the developers can control the animations. 

When completely ignoring prevProps we do not see animations, and sometimes are sent to a blank screen. When using prevProps, we occasionally get an animation (although not always), but the leaving/old screen does not animate out from center to left. 

Is this a bug in NavigationTransitioner in v0.29? If not, is there any documentation or example using NavigationTransitioner since the v0.29 redesign? My goal is to have new screens animate from right to center, and the old screen animate from center to left (and off the display). 

```
  renderScene(props, prevProps) {
    let scene = props.scene;
    if (prevProps && prevProps.scene) {
      scene = prevProps.scene;
    }
    const interpolatedStyle = NavigationCard.CardStackStyleInterpolator.forHorizontal(props);
    return (
      <NavigationCard
        {...props}
        style={[interpolatedStyle]}
        key={scene.route.key}
        renderScene={this.renderInnerScene.bind(this)}
      />
    );
  }
```

In the above sample, I've tried various permutations of which props are passed into forHorizontal, and which props and scene are sent as props to NavigationCard but nothing is working with v0.29, hm.

**Comment by jmurzy** [comment]
[`NavigationCardStack`](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js) can be regarded as reference impl. Let me know if the below snippet doesn't work the way you expected.

```js
render(): ReactElement<any> {
  return (
    <NavigationTransitioner
      navigationState={this.props.navigationState}
      render={this._render}
      style={this.props.style}
    />
  );
}

_render(props: NavigationTransitionProps): ReactElement<any> {
  const {
    renderOverlay
  } = this.props;

  let overlay = null;
  if (renderOverlay) {
    overlay = renderOverlay({
     ...props,
     scene: props.scene,
    });
  }

  const scenes = props.scenes.map(
   scene => this._renderScene({
     ...props,
     scene,
   })
  );

  return (
    <View
      style={styles.container}>
      <View
        style={styles.scenes}>
        {scenes}
      </View>
      {overlay}
    </View>
  );
}

_renderScene(props: NavigationSceneRendererProps): ReactElement<any> {
  const isVertical = this.props.direction === 'vertical';

  const style = isVertical ?
    NavigationCardStackStyleInterpolator.forVertical(props) :
    NavigationCardStackStyleInterpolator.forHorizontal(props);

  const panHandlersProps = {
    ...props,
    onNavigateBack: this.props.onNavigateBack,
  };
  const panHandlers = isVertical ?
    NavigationCardStackPanResponder.forVertical(panHandlersProps) :
    NavigationCardStackPanResponder.forHorizontal(panHandlersProps);

  return (
    <NavigationCard
      {...props}
      key={'card_' + props.scene.key}
      panHandlers={panHandlers}
      renderScene={this.props.renderScene}
      style={[style, this.props.cardStyle]}
    />
  );
}
```

🍺

**Comment by dguillamot** [comment]
Thanks @jmurzy , This is similar to what we had in an earlier version (minus the panHandlers) but just re-implemented to make sure. It gets us most of the way but it still causes issue with a couple of our screens not rendering. I will look into it some more and try and troubleshoot or edge cases, thanks again.
