### ISSUE TITLE
[fatal][tid:main] Unable to resolve module react 

### ISSUE THREAD

**Issue by XiaoLiz** [facebook/react-native#8702]
I run xcode project prompted the following error：

[tid:main] Unable to resolve module react from /Users/chenchen/Documents/project/mywebsite/index.ios.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/react and its parent directories

Do the checklist before filing an issue:

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

I follow the above instructions, but still valid

**Comment by stoffern** [comment]
@XiaoLiz I think this could be a problem with PATH+npm on windows.
Please try the following:
reinstall all to latest:
```
npm: 3.10.3
node: 6.3.0
react-native: ^0.29.0
react: 15.2.1
```

Then:
```
rm -rf node_modules 
npm clean cache
watchman watch-del-all
npm i
npm start -- --reset-cache
```

**Comment by XiaoLiz** [comment]
@stoffern  The need to install npm install react ?

**Comment by stoffern** [comment]
Yes, `react-native` uses `react` framework to get its structure.

`import React, {Component} from 'react'
`

**Comment by XiaoLiz** [comment]
![Uploading 3FE095BF-C8D8-4580-9EA1-0B3E9FEACC27.png…]()

**Comment by XiaoLiz** [comment]
@stoffern According to the above process still not been resolved

**Comment by XiaoLiz** [comment]
@stoffern According to the above method is still not able to solve this problem

**Comment by XiaoLiz** [comment]
According to the above method is still not able to solve this problem

**Comment by stoffern** [comment]
@XiaoLiz can you post your `index.ios.js` code?

**Comment by XiaoLiz** [comment]
init project index.ios.js



/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class mywebsite extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('mywebsite', () => mywebsite);

**Comment by stoffern** [comment]
@XiaoLiz no problems there.
is your project located here: /Users/chenchen/Documents/project/mywebsite ?

what happends if you run:
`./node_modules/react-native/packager/packager.sh start --reset-cache`

**Comment by XiaoLiz** [comment]
@stoffern   

Yes !  my project located here: /Users/chenchen/Documents/project/mywebsite 


my run:

./node_modules/react-native/packager/packager.sh start --reset-cache

![image](https://cloud.githubusercontent.com/assets/15154383/16794031/e0ba3e98-4907-11e6-994a-0798031557b9.png)

**Comment by stoffern** [comment]
@XiaoLiz is your `package.json` and your `node_modules` folder inside: /Users/chenchen/Documents/project/mywebsite ?

**Comment by XiaoLiz** [comment]
@stoffern 

Yes !

**Comment by senpng** [comment]
@XiaoLiz 
you not install  `react`
```
npm i --save react
```
不谢！

**Comment by lacker** [comment]
Looks like this has been solved.
