### ISSUE TITLE
View shifts down and breaks when StatusBar changes size (not compensating for enlarged StatusBar)

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#871]
When using apps that make the StatusBar bigger (Maps during direction mode, Phone app during calls) and going back to my app the view doesn't update to compensate for the enlarged StatusBar and everything gets pushed down. This completely breaks things like TabBar.

broken:
![img_3629](https://cloud.githubusercontent.com/assets/287288/7172010/70515da4-e395-11e4-8d5e-f2c546b7f544.PNG)

normal:
![img_3630](https://cloud.githubusercontent.com/assets/287288/7172007/646caa8e-e395-11e4-8788-0b41bab7b722.PNG)

**Comment by soheil** [comment]
I found wrapping everything in this fixes this issue:

```
      <View style={{flex: 0, height: require('Dimensions').get('window').height}}>
```

**Comment by brentvatne** [comment]
:smile: nice!
