### ISSUE TITLE
How to reuse ReactInstanceManager

### ISSUE THREAD

**Issue by Ray-Ni** [facebook/react-native#8710]
As the document has said:

`A ReactInstanceManager can be shared amongst multiple activities and/or fragments. You will want to make your own ReactFragment or ReactActivity and have a singleton holder that holds a ReactInstanceManager. When you need the ReactInstanceManager (e.g., to hook up the ReactInstanceManager to the lifecycle of those Activities or Fragments) use the one provided by the singleton.`

ReactInstanceManager can be reuse in diffrent activity or fragment.
But it seems one ReactInstanceManager can only load one js bundle. 

So how can I reuse ReactInstanceManager to load another js bundle ?

**Comment by ide** [comment]
ReactInstanceManager can use only one bundle. The document is just saying that you can share that bundle across several activities if you want.

**Comment by jkwangbest** [comment]
#15108
