### ISSUE TITLE
Offline bundle documentation out of date

### ISSUE THREAD

**Issue by Ryanthegiantlion** [facebook/react-native#8716]
See https://github.com/facebook/react-native/blob/master/docs/RunningOnDeviceIOS.md#using-the-offline-bundle

In particular 'Uncomment the line, jsCodeLocation = [[NSBundle mainBundle] ..'

The [app delegate file](https://github.com/facebook/react-native/blob/master/local-cli/generator-ios/templates/app/AppDelegate.m#L21) no longer contains that line (since 0.29). So it is not clear how to build a production version of the app. I am not sure if incorrect documentation counts as a bug but this seems like a pretty important thing to sort out . . .

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by PierBover** [comment]
I was just going to add this.

It seems when selecting `Release` in the Build Configuration of the Scheme there is no more need to edit that line.

![image](https://cloud.githubusercontent.com/assets/226483/16780934/78545f74-483e-11e6-89bd-c326e5e6f87b.png)

![image](https://cloud.githubusercontent.com/assets/226483/16780925/692c5d26-483e-11e6-80f8-0f3b3465285a.png)

**Comment by npomfret** [comment]
How do you load js from a url since 0.29??  I'm trying (and failing) to test on a  physical device.

**Comment by Ryanthegiantlion** [comment]
It looks like it is supposed to be detecting the i.p address [automatically](https://github.com/facebook/react-native/commit/8c29a52c54392ce52148e7d3aa9f835537453aa4)

You might want to try logging what the host string gets in RCTBundleURLProvider.m

**Comment by PierBover** [comment]
> It looks like it is supposed to be detecting the i.p address automatically

Yes, that was my experience as well with 0.29.0.

@npomfret what problem are you having?

**Comment by npomfret** [comment]
If I run on a physical device now it loads the offline bundle only (and by default).  So I can't shake to reload the javascript files any more.

The upgrade process `react-native upgrade` is a nightmare in terms of merging.  Maybe I missed something.  Any idea what I should look for?

**Comment by mintuz** [comment]
I am seeing a slightly different problem where it keeps loading the server bundle instead of the static bundle. I am trying to release to AppStore as well. Is the documentation missing something for releasing to AppStore.

**Comment by PierBover** [comment]
> If I run on a physical device now it loads the offline bundle only (and by default). So I can't shake to reload the javascript files any more.

@npomfret are you compiling for release or debug on your build configuration?

If you are compiling for release then the debug menu and loading JS from the dev server are automatically disabled.

**Comment by npomfret** [comment]
Thanks for the reply - how do I check please? I see a debug menu if I shake the phone so I believe I'm running a debug configuration when I press _run_ in xcode.  If I look at the scheme under _Run_ it says _Debug executable_.  

I've not changed anything, other than upgrading from RN 0.28 to RN 0.29.

I just don't see a way to tell the app to load JS from my laptop instead of the pre packed bundle any more.

**Comment by PierBover** [comment]
If you can see the menu you are indeed in debug mode.

Loading the files from your dev server on your laptop should happen automatically since 0.29.0.

**Comment by JosephDev** [comment]
I have the same problem with @npomfret  
On simulator it's fine, but on physical device, it loads pre-bundled only. :(
I changed schema as @PierBover 's comment but no luck.

**Comment by npomfret** [comment]
@JosephDev - checkout my solution here: https://github.com/facebook/react-native/issues/8358

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/offline-bundle-documentation-out-of-date

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by jifromz** [comment]
I've been stuck in this problem, my app is working fine in debug mode but when I test it using release mode it stuck with unknown error on main.jsbundle. I am using RN v0.43.
