### ISSUE TITLE
Debugger and device times have drifted - Android 0.29.0

### ISSUE THREAD

**Issue by markbrown4** [facebook/react-native#8720]
I'm unable to Debug in Chrome on an Android device  in react-native `0.29.0`
Running Android image "Google Nexus 5 - 6.0.0 - API 23" in genymotion.

I'm seeing this whenever interacting with an Android app:

https://dl.dropboxusercontent.com/u/13632257/drift.png

Unspecial example app

``` js
import React, { Component } from 'react';
 import {
   AppRegistry,
   View,
   Text,
   TouchableHighlight,
 } from 'react-native';

 class App extends Component {
   render() {
     return (
       <View style={{ flex: 1 }}>
         <TouchableHighlight onPress={()=> 'nothing to see here'}>
           <Text>
             Click Me
           </Text>
         </TouchableHighlight>
       </View>
     )
   }
 }

AppRegistry.registerComponent('App', () => App);
```

**Comment by charpeni** [comment]
Did you try running the command `adb shell [...]` that was mentioned in the error?

**Comment by markbrown4** [comment]
I did, the error continued to show.

**Comment by satya164** [comment]
Does the time on Genymotion match your system's time? If not, try adjusting it.

**Comment by markbrown4** [comment]
They appear to be in sync, both currently showing 9:15PM

```
adb shell "date `date +%m%d%H%M%Y.%S`"
Tue Jul 12 21:13:58 EDT 2016
```

**Comment by stoffern** [comment]
This has been canged from exception error to warning  here https://github.com/facebook/react-native/commit/ed4db631faf0091a92179e9fd629ce06e4704d1e
The app will not crash anymore after this.

cc @yungsters

**Comment by markbrown4** [comment]
@stoffern How can I pull this down and test it before an npm release?
I tried changing the source in node_modules but looks like the java files need to be compiled?

Unfortunately this is a complete dead end for me.  With the debugger I get that error, without the debugger I get another random error that I can't debug:

https://dl.dropboxusercontent.com/u/13632257/color.png

**Comment by satya164** [comment]
@markbrown4 https://facebook.github.io/react-native/docs/android-building-from-source.html

**Comment by blackjable** [comment]
Do you know when this fix will be on a published release?

**Comment by inithink** [comment]
The command seems it doesn't care timezone.

**Comment by eremzeit** [comment]
I got the error, but when I ran the command I got this:

```
$ adb shell "date `date +%m%d%H%M%Y.%S`"
date: cannot set date: Operation not permitted
Fri Aug  5 16:10:39 PDT 2016
```

It would appear that I don't have permissions to change the android device?

**Comment by vandervidi** [comment]
Im getting "date: cannot set date: Operation not permitted" too.
Any solution for this?

**Comment by JordyMoos** [comment]
You can run `su` in the shell to get root

**Comment by KamWis** [comment]
> You can run su in the shell to get root

Logging as a root doesn't help. Still 

> date: cannot set date: Operation not permitted

Does it have sth to do with emulator itself?

**Comment by lacker** [comment]
Seems like the original problem should now be fixed so I am going to close this issue. If people are running into similar problems in the future, I suggest opening new issues. Thanks folks!

**Comment by stoffern** [comment]
If you run into this issue again. turn on NTP on the phone and on the computer

**Comment by matthamil** [comment]
I came across this issue in RN 0.41.2, and I resolved it by stopping my Android emulator and rerunning it.

**Comment by wildQueequeg** [comment]
set time manually on android device

**Comment by pihyper** [comment]
According to this SO thread http://stackoverflow.com/questions/38938791/react-native-cannot-run-adb-shell-date-date-mdhmy-s, the solution is to


**Inside the emulator goto Settings > Date & Time

1. Deselect Automatic timezone.
2. Adjust your timezone manually.
3. Deselect automatic date & time and set correct time**

**Comment by stoffern** [comment]
Lets just say that making the same time and date on both device and computer will do the trick! 😉

**Comment by DevCappe** [comment]
adb root
adb shell "date `date +%m%d%H%M%Y.%S`"

**Comment by luqmanrom** [comment]
I am getting this error when running `adb shell "date `date + %m%d%H%M%Y.%S`"` as suggested in the warning message:

```
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```



This works for me.

`adb shell "date `date +%G%m%d.%H%M%S`"`

**Comment by mikeumus** [comment]
+1 to @pihyper and @stoffern and the rest but don't forget the time zone too!

**Comment by selmansamet** [comment]
I am getting:
```
$ adb shell "date `date +%m%d%H%M%Y.%S`"
time 061807362018.49 -> 1677819874.0
settimeofday failed Bad file number
```
