### ISSUE TITLE
[Android] Error when parsing JSON

### ISSUE THREAD

**Issue by PierBover** [facebook/react-native#8726]
I'm trying to parse a JSON file but I get this in `adb logcat`

```
ReactNativeJS: JSON Parse error: Unrecognized token '?'
```

This is the code for testing.
```
fetch("http://pierbover.com/pub/book.json", {method: "GET"})
  .then((response) => response.json())
  .then((responseData) => {
  console.log(responseData);
})
  .done();
```
This doesn't work in a browser due to CORS, but other JSONs in that server work fine with RN.

I've tried validating the JSON and all validators report it's OK.

I've attached the file in a ZIP since Github doesn't allow JSONs. I didn't copy and paste the text on purpose in case there is some hidden character or encoding gremlin going on.

[book.json.zip](https://github.com/facebook/react-native/files/360168/book.json.zip)

**Comment by c-h-** [comment]
@PierBover Could be related to https://github.com/facebook/react-native/issues/4961#issuecomment-231806590. I see characters in that response that might be problematic; not sure.

**Comment by PierBover** [comment]
It's a mystery. Other JSONs with the same latin characters and format work perfectly fine.

It's only this particular file that crashes the app.

**Comment by satya164** [comment]
Fixed in https://github.com/facebook/react-native/commit/6d3c7b8a4c1d1a0552a21cfabe03a8d1f344d1ed

**Comment by dakdreams** [comment]
i have a same problem!!!

**Comment by PierBover** [comment]
@dakdreams after investigating my issue we found that there were some invalid invisible characters in the JSON because someone had pasted and copied the JSON in Slack.

No validators we used recognised these characters as invalid, and that was another big problem.
