### ISSUE TITLE
[0.29] `Constructor` has no propType for native prop `RCTView.maxHeight` of native type `CGFloat`

### ISSUE THREAD

**Issue by raineroviir** [facebook/react-native#8728]
Using iOS on a Mac. RN 0.29.  Xcode 7.3.1

Steps to reproduce:

react-native init project
react-native run-ios

Brings us to:
![screen shot 2016-07-12 at 5 59 17 pm](https://cloud.githubusercontent.com/assets/10455065/16788478/61567b2e-485a-11e6-893c-ecfb5f1b8cb4.png)

**Comment by raineroviir** [comment]
This issue was fixed with a restart.  

Always remember to restart after you upgrade your Xcode!

**Comment by skyFi** [comment]
@raineroviir  my Xcode version: 7.3.1  upgrade it to 8.X ? thx

**Comment by skyFi** [comment]
just restart your project,while Xcode version is 7.3.1,nice job

**Comment by raineroviir** [comment]
I restarted my computer, having upgraded from 7.x.x to 7.3.1

**Comment by itinance** [comment]
Just for the record in case others would ran into this issue like me. If a simple restart is not enough, the following steps helped me finally:

1. Delete node modules, reset npm cache and watchman and reinstall everything from scratch:

`rm -rf node_modules/ && npm cache clear && watchman watch-del-all && npm i`

2. Start packager with --reset-cache option:

`node node_modules/react-native/local-cli/cli.js start --reset-cache`
