### ISSUE TITLE
CameraRollManager not defined in iOS

### ISSUE THREAD

**Issue by scerelli** [facebook/react-native#8738]
It seems that there is a bug in 0.29/iOS. 
After importing `CameraRoll` from `react-native` I tried to save a file inside the gallery but it seems that there is some problems in `CameraRollManager`; basically on android it works well but on iOS `CameraRollManager`seems to be `undefined`.

this is what i tried to do:

```js
CameraRoll.saveToCameraRoll(uri)
```

and testing on an iPhone it returns 

```js
Cannot read property 'saveToCameraRoll' of undefined
Unhandled JS Exception: Cannot read property 'saveToCameraRoll' of undefined
```

i tried to import the native module directly and actually is undefined on ios

edit: same error in 0.28

**Comment by grabbou** [comment]
In order to use `CameraRoll` you have to add `CameraRoll.xcodeproj` (it's inside `Libraries` folder) - see [this](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) guide.

**Comment by henkkasoft** [comment]
I first found this post but this was better:
https://github.com/facebook/react-native/issues/4560
