### ISSUE TITLE
TouchableNativeFeedback doesn’t render its direct child

### ISSUE THREAD

**Issue by mquandalle** [facebook/react-native#8755]
Hi,

References aren’t working for the `TouchableNativeFeedback` direct child. The following snippet demonstrates the issue:

``` js
const MyComponent = React.createClass({
  onPress() {
    console.log(this.refs.myView); // undefined!
  },

  render() {
    return (
      <TouchableNativeFeedback onPress={this.onPress}>
        <View ref="myView">
          <Text>Touch me</Text>
        </View>
      </TouchableNativeFeedback>
    );
  }
})
```

I also provided a minimal reproduction with RNPlay: https://rnplay.org/apps/lJXLPw. The problem happen with React Native v0.29 on Android.

**Comment by ide** [comment]
What if you use callback refs?

**Comment by mquandalle** [comment]
Not callback refs aren’t called either.

**Comment by ide** [comment]
It looks like TouchableNativeFeedback doesn't render the direct child at all: https://github.com/facebook/react-native/blob/65ff8192dd6a542485d1ea0647eadee44d76a55b/Libraries/Components/Touchable/TouchableNativeFeedback.android.js#L208

@mkonicek would you happen to know who authored TouchableNativeFeedback and could explain why not rendering the direct child was necessary (or if it can be changed)? The blame history goes back to the first RN Android commit: https://github.com/facebook/react-native/blame/42eb5464fd8a65ed84b799de5d4dc225349449be/Libraries/Components/Touchable/TouchableNativeFeedback.android.js#L200

**Comment by arnavyagnik** [comment]
is there any progress here? I'm stuck at a use case here.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
