### ISSUE TITLE
App crashes when I changed tabBar repeatedly and rapidly [tid:com.facebook.react.RCTExceptionsManagerQueue] -0.25.1

### ISSUE THREAD

**Issue by iniestano8** [facebook/react-native#8766]
when i change my tabbar  repeatedly and rapidly , it crashes with the exception:
`
2016-07-14 11:19:24.916 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'spring.systemShouldAdvance')
2016-07-14 11:19:24.984 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'spring.systemShouldAdvance')
`

**Comment by kompot** [comment]
Got the some issue with similar symptoms.

@iniestano8 aren't you using `react-native-simple-router` (https://github.com/react-native-simple-router-community/react-native-simple-router/) for navigation?

**Comment by iniestano8** [comment]
@kompot no, and i have no idea why it happend  -_-!

**Comment by maxcodes** [comment]
I'm having the same issue. It seems to be related to https://github.com/facebook/rebound-js. For me it happens randomly when triggering an infinite scroll.

**Comment by santong** [comment]
I have same issue.

**Comment by bonbonez** [comment]
Has someone figured out what's wrong?

**Comment by udfalkso** [comment]
I think @maxcodes is right.  RN itself has no mention of systemShouldAdvance but it does show up in rebound, which is used by Navigator.  This would explain why some of us see issues when switching quickly between tabs in our apps.

http://facebook.github.io/rebound/javadocs/com/facebook/rebound/Spring.html#systemShouldAdvance()

react-native/Libraries/CustomComponents/Navigator/Navigator.js
```
this.springSystem = new rebound.SpringSystem();
```

Seems like improvements in use of Animated in 0.37 and 0.38 might help?

**Comment by hramos** [comment]
Can you reproduce this on [rnplay.org](https://rnplay.org/)? Please provide a link.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
