### ISSUE TITLE
ActivityIndicator not showing on device (Samsung Galaxy s5)

### ISSUE THREAD

**Issue by bogdancarmanus** [facebook/react-native#8771]
- [0.28.0 ] What's the **version** of React Native you're using?
- [Android ] Does this occur on iOS, Android or both?
- [ Mac ] Are you using Mac, Linux or Windows?

**Comment by mhollweck** [comment]
Can you provide a Code Snippet?

**Comment by bogdancarmanus** [comment]
```
<ActivityIndicator
color="black"
size="large"
/>
```

It works great on the emulator. It works on a Nexus 4 as well but when running on a Samsung Galaxy s5 the ActivityIndicator doesn't show up.

**Comment by bogdancarmanus** [comment]
I would like to add that the Samsung Galaxy S5 is running Android Marshmallow (6.0.1).

**Comment by esganzerla** [comment]
Same happening to me on Moto G4 (Android 6.0.1). Works fine on Moto G3 (Android 6.0).
I'm using React-native v0.35.0.

It shows the ActivityIndicator element (as you can see the top bar on the image below), I've set the background to it to test. Just does not show the spinner.
![screenshot_20161014-150547](https://cloud.githubusercontent.com/assets/15572427/19397867/0cd6f0fa-9220-11e6-921d-3d7ec5206216.png)

**Comment by Tsury** [comment]
Also experiencing this with React Native 0.38.0 and a Nexus 6p running Android 7.0

**Comment by esganzerla** [comment]
I forgot to comment here. Turns out it was an Android bug for me. I noticed that even the turning off Android ActivityIndicator was not showing up and after I factory resetted my mobile it started working.

**Comment by cuongtructran** [comment]
Hi guys, 

I'm using Galaxy S7 Edge with latest version (Android 6.0.1) and I'm having the same issue. The ActivityIndicator doesn't show up. I tested with emulator and it works fine. 

Any clue?

**Comment by esganzerla** [comment]
@cuongtructran This seems to be a bug in the Android installation. I factory reset my phone and it worked fine after that. There were also default system ActivityIndicator not showing before that.

**Comment by pierre-H** [comment]
Same problem with a Samsung J3.

**Comment by justinlok** [comment]
Same problem with Samsung Galaxy S6

**Comment by Aleksandern** [comment]
Same problem with Samsung Galaxy Note 3  (Android 5.0)

**Comment by esganzerla** [comment]
Do you guys see the ActivityIndicator on the native Android informations? Like when turning the phone off?

As I mentioned before, I was not seeing it on other parts as well, and when I factory reset the phone it worked. Seems to me like an Android bug.

**Comment by ashafizullah** [comment]
Same problem with Asus Zenfone 2. I already try to restart my phone, but ActivityIndicator still not showing on real device, but its work on Genymotion emulator. @esganzerla
