### ISSUE TITLE
Application can not start . Watch error

### ISSUE THREAD

**Issue by Julious1994** [facebook/react-native#8777]
I cant run my app on emulator.

If i do any changes it gives following error:

when fire command npm start

![screenshot from 2016-07-14 17-20-37](https://cloud.githubusercontent.com/assets/16513909/16838604/9c826774-49e7-11e6-89f3-ca103a920400.png)

**Comment by carera** [comment]
Stupid question, but do you have enough space on your drive?

**Comment by satya164** [comment]
@Julious1994 Try installing watchman.

**Comment by Julious1994** [comment]
watchman cant be installed

**Comment by Julious1994** [comment]
[carera](https://github.com/carera) I have enough space on my drive 335 GB free space

**Comment by ide** [comment]
Try this, it looks related to the watcher: https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

But yea installing Watchman is the recommended solution.

**Comment by Julious1994** [comment]
Thanks
[ide](https://github.com/ide) . You solved my problem. Thank you very much!!!!
