### ISSUE TITLE
[TextInput][Android] blurOnSubmit not working with multiline

### ISSUE THREAD

**Issue by kulmajaba** [facebook/react-native#8778]
When using `multiline={true}` in combination with `blurOnSubmit={true}` the TextInput should blur when enter is pressed. Instead, pressing return inserts a new line.

Tested on both Android and iOS, issue occurs on Android only. iOS works fine.

Using React Native 0.28.0, testing on Android emulator and device, Android version 6.0.1

Sample app: https://rnplay.org/apps/CFQA2A

**Comment by alexprice91** [comment]
Bump

**Comment by mmazzarolo** [comment]
Still same issue on `0.33`

**Comment by ericnakagawa** [comment]
@kulmajaba @alexprice91 @mmazzarolo Hi folks, I'm checking in to see if this issue is still persisting for you folks.

**Comment by mmazzarolo** [comment]
@ericnakagawa I can't test it right now, I'll give you some feedback the next time I'll use the `blurOnSubmit` and `multiline` combo

**Comment by kulmajaba** [comment]
@ericnakagawa Just checked with React Native 0.40 on Android 7.1.1 device, issue still persists.

**Comment by Fouppy** [comment]
@ericnakagawa I can confirm that this issue still exists as of RN 0.42.

**Comment by flyher** [comment]
The issues still exist in `"react-native": "0.43.4"` and Android 6

**Comment by adamjacob** [comment]
Has anyone had any success with any work arounds?  I'm still seeing this issue on 0.46.1

**Comment by richchurcher** [comment]
Confirmed on Android with 0.46.4: still doesn't work.

**Comment by danlin604** [comment]
`blurOnSubmit` is no longer working on the snack provided. Pressing enter only gets me a new line, with no way to submit the TextInput.

**Comment by RobertSheaO** [comment]
Just discovered this issue myself, still and issue with React Native 0.50

**Comment by SuhairZain** [comment]
@richchurcher I can confirm that blurOnSubmit is no longer working on the snack provided. It creates a new line instead of submitting.

Xiaomi Redmi 3S
Android 6.0.1
MIUI 8.5.4.0

**Comment by BlagojeV93** [comment]
blurOnSubmit in combination with multiline works now for me! Using React Native 52.2

**Comment by NachoJusticia** [comment]
These configuration is working as expected for me in *react-native v0.55.3*
```
<TextInput
          returnKeyType='done'
          multiline
          autoFocus
          blurOnSubmit={true}
          autoCorrect={false}
          maxLength={1000}
          numberOfLines={4}
          onChangeText={onTypeComment}
          placeholder={I18n.t('SHARE_DETAILS')}
          style={styles.textArea}
          underlineColorAndroid={'rgba(0,0,0,0)'}
          value={comment}
        />
```
