### ISSUE TITLE
React Packager not reloading

### ISSUE THREAD

**Issue by yooneskh** [facebook/react-native#8784]
I am developing on windows (8.1) and am using genymotion (2.7.2 and Nexus 5 device with android 4) for simulator. 

The problem is that i cannot get the reload to work. i have done the adb reverse tcp:8081 tcp:8081 .

The only way to get the new files to be seen is to do another react-native run-android . 

Any help?

**Comment by stoffern** [comment]
Android: ctrl+m inside AVD
Click Reload

Read specs: http://facebook.github.io/react-native/releases/0.29/docs/debugging.html#reloading-javascript

**Comment by yooneskh** [comment]
@stoffern i already know this. I go to genymotion, open the so called menu, hit the reload and nothing happens.

**Comment by yooneskh** [comment]
To clarify even more, this set of action happens successfully

- i run the app in the emulator

**Comment by yooneskh** [comment]
To clarify even more, these actions complete successfully

- i run the app in the emulator
- open the menu
- select "enable hot reload"
- React Packager shows some messages about transforming some things and such
- the app fetches js bundle, flashes and things go back to where they were

but my changed files are not there. 

since the app and React Packager seem to successfully talk with each other, i guess React Packager just does not see the changes.

**Comment by malaman** [comment]
@yooneskh . 
Try `watchman watch-del-all` and restart packager.

**Comment by StellwagJo** [comment]
Having same issues here. Worked with react-native 0.23 & 0.27. Hot reloading always worked as expected. 
Since my upgrade on 0.29.1 (stable) the hotreloading doesn't reload the code.

**Comment by psrustik** [comment]
I have same issue on react native 0.28 and windows 10

**Comment by vzhen** [comment]
exactly same issue on Windows 7

**Comment by togayther** [comment]
same issue on android device with react-native 0.32.

finally, i found method to solve this problem.

in file "react-native\packager\react-packager\src\node-haste\FileWatcher\index.js"
you can increase "MAX_WAIT_TIME" variable. such: 360000.

and change function "_createWatcher"

to
```
_createWatcher(rootConfig) {
    const watcher = new WatcherClass(rootConfig.dir, {
      glob: rootConfig.globs,
      dot: false,
    });

    return new Promise((resolve, reject) => {
      const rejectTimeout = setTimeout(
        () => reject(new Error([
            'Watcher took too long to load',
            'Try running `watchman version` from your terminal',
            'https://facebook.github.io/watchman/docs/troubleshooting.html',
          ].join('\n'))),
        MAX_WAIT_TIME
      );

      watcher.once('ready', () => {
        clearTimeout(rejectTimeout);
        resolve(watcher);
      });
    });
  }
```
that's all and work for me.

**Comment by sebahattint** [comment]
I also had the same problem. Working now. Thanks guys!
**react-native:** 0.32.0
**react-native-cli:** 1.0.0
**OS:** Windows 10

**Comment by Brokray** [comment]
Had the same issue, @togayther's solution fixed it. Thanks :)
react-native: 0.30.0
OS: Windows 10

**Comment by TrustTheBoy** [comment]
I also had the same problem.For help  Thanks guys!  
react native 0.33/0.34
OS:Windows 10

**Comment by Neungzad** [comment]
+1 , I also had the same problem.

**Comment by aljux** [comment]
I still have this problem even with @togayther's fix.
react-native-cli: 1.0.0
react-native: 0.36.0
macOS 10.12.1
