### ISSUE TITLE
Updating build number with `agvtool new-version -all {build number}` doesn't work

### ISSUE THREAD

**Issue by peterprokop** [facebook/react-native#879]
agvtool returns with:

```
Setting version of project {project} to: 
    {build number}.
Also setting CFBundleVersion key (assuming it exists)
Updating CFBundleVersion in Info.plist(s)...
$(SRCROOT)/iOS/Info.plist
Cannot find "$(SRCROOT)/iOS/Info.plist"
```

**Comment by oblador** [comment]
Had the same problem, solved it by making the path relative. Just remove `$(SRCROOT)/` from the "Info.plist File" setting under Build Settings and it works just fine.

**Comment by christopherdro** [comment]
@peterprokop 
Did the solution from @oblador work for you?

**Comment by peterprokop** [comment]
@christopherdro haven't tried it.
Used something like 
`/usr/libexec/PlistBuddy -c "Set CFBundleVersion $TRAVIS_BUILD_NUMBER" ./iOS/Info.plist`
instead.

**Comment by brentvatne** [comment]
@oblador - that worked for me as well, submitted a PR to update the SampleApp accordingly

**Comment by csemresari** [comment]
Thanks @oblador
