### ISSUE TITLE
JS file with 1000+ image map gives fs operation timeout

### ISSUE THREAD

**Issue by nak1b** [facebook/react-native#8794]
I have javascript file that looks like below. It has lots of object (1000+). As we cannot use dynamic name for images in react-native this is my work around.

```
"grinning": {
        "image": require('./images/1f600.png'),
        "shortname": ":grinning:",
    }
```

I am requiring this file in some other react native function and looping to display all the images. But getting internal error on requiring too many images in javascript file.

`{"type":"InternalError","message":"react-packager has encountered an internal error, please check your terminal error output for details"}`
In terminal it says

`fs operation timeout`

This works if i remove few entries from the file.

Any suggestion or better approach

**Comment by satya164** [comment]
At least on Android you can package the assets manually and use `{ uri: 'file://path/to/file' }` as the source.

**Comment by nak1b** [comment]
@satya164 thanks this will solve issue with android any idea about iOS?

**Comment by shahen94** [comment]
👍  have the same issue

**Comment by ide** [comment]
Do you have watchman installed?

**Comment by ColCh** [comment]
Have you tried to specify file operation timeout (See this commit https://github.com/facebook/react-native/commit/8edb9524035b0c034135a81551ba955ee514dbd4 )

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/js-file-with-1000-image-map-gives-fs-operation-timeout
