### ISSUE TITLE
White screen on android

### ISSUE THREAD

**Issue by ramsestom** [facebook/react-native#8796]
Hi
   I just started with react-native. I am developing on windows and when trying the "getting-started" example (https://facebook.github.io/react-native/docs/getting-started.html) it results into a white screen on my android device (when calling "react-native run-android"). I also tried another react-native app (downloaded from https://github.com/oney/RCTWebRTCDemo) and same thing, it only shows a white screen.
I don't see any error in my windows prompt console so I don't know what can be the issue....

**Comment by ramsestom** [comment]
Actually this is working now. Looks like it takes some times for the app to appear on screen (had a white screen during 30s with the "getting-started" demo app so I thought it wasn't working)
That is something you should add to the "getting-started" tutorial to warn new user that they may experience a white screen for multiple seconds/minute before the app actually appears on their device...

**Comment by su8hash** [comment]
Are you using physical device here ,You Need to be in same network and device should be able to connect to server (Android Steps Below)
1). If Using USB Debugging then run 'adb reverse tcp:8081 tcp:8081' from your "C:\Users\<UserName>\AppData\Local\Android\sdk\platform-tools"
this will forward mobile's call for localhost:8081 to PC's localhost:8081,  here 8081 is port your server is running

2). If over Wifi on same network shake phone to open developer menu and go to 'Dev Setting' and enter Debug Server Host and Port  as <your_PC_IP>:8081 here

I think this should help it does takes a few seconds sometime for app to load
