### ISSUE TITLE
how  listen applicationDidBecomeActive event

### ISSUE THREAD

**Issue by littleweb** [facebook/react-native#880]

**Comment by brentvatne** [comment]
@littleweb - see [AppStateIOS](https://facebook.github.io/react-native/docs/appstateios.html#content) - if this doesn't resolve your problem, ping me here

**Comment by mschipperheyn** [comment]
It seems to me that foreground status is not the same as waking up from sleep. How would you detect that a phone wakes up from sleep (and needs to reinialize websockets). Or is the expected approach in this scenario to check for an active websocket connection when the app comes to the foreground? That would be less desirable
