### ISSUE TITLE
using Navigator during componentWillMount bug

### ISSUE THREAD

**Issue by getnashty** [facebook/react-native#8801]
In the process of upgrading from RN 0.22 to RN 0.29

In 0.22 this worked perfectly.

That said, in my project, I check a property in the componentWillMount fn, and if the property isn't present I navigate the user to a different component. Essentially an auth check.

This was working in RN 0.22, but with 0.29 it navigates to the different component (properly), and then that component immediately goes away (to seemingly nowhere) - leaving me with a blank white screen.

Its almost as if the previous navigation isn't done, so it decides to finish it after the next navigation has started...

This is my code that used to work:

```
componentWillMount() {
   if (!this.props.user.username) {
     this.props.navigator.push({
       component: SettingsContainer,
     });
   }
 }
```

if I wrap it in a setTimeout, it does work - except the initial component loads first (obviously) which is not what I want.

I assume this is a bug, as it was working in a previous version.

**Comment by yueshuaijie** [comment]
Tested on 0.29.1, it works OK.

**Comment by getnashty** [comment]
I'm also using 0.29.1 @yueshuaijie, when I changed it to navigator.pop() - I got this error https://github.com/febobo/react-native-redux-FeInn/issues/32, digging in further

**Comment by getnashty** [comment]
This is how my Navigator is setup, that might be related to this issue (although it worked fine before...)

```
  _renderScene(route, navigator){
    var Component = route.component;
    return (
      <Component {...route.props} navigator={navigator} route={route} />
    );
  }

  _configureScene(route, routeStack){
    if (route.noSwipeBack) {
      return {
        ...Navigator.SceneConfigs[route.sceneConfig || 'PushFromRight'],
        gestures: {}
      };
    } else {
      return Navigator.SceneConfigs[route.sceneConfig || 'PushFromRight'];
    }
  }

  render() {
    return (
      <Provider store={store}>
        <Navigator
          initialRoute={{ component: AuthContainer }}
          renderScene={this._renderScene}
          configureScene={this._configureScene}
        />
      </Provider>
    );
  }
```

**Comment by getnashty** [comment]
@yueshuaijie I can't imagine its actually working for you... When I change the navigator to use replace instead of push - it replaces the scene which loaded prior to the currently mounting component, instead of replacing the currently loading component / scene. What results do you get with replace?

**Comment by yueshuaijie** [comment]
@getnashty I mean, I use navigator to push another component in `componetWillMount`(without using `setTimeout`) works OK in 0.29.1

If I use `navigator.pop()` in `componentWillMount`, I didn't get any error, but nothing happens.

If I use `navigator.replace()`, it just works as expected(replacing the current mounting component). But I got a warning: `setState(...): Can only update a mounted or mounting component...`

**Comment by yueshuaijie** [comment]
@getnashty Your Navigator setup code `renderScene` seems OK to me(almost same as mine)

**Comment by getnashty** [comment]
@yueshuaijie are you just setting it in the initialRoute component's componentWillMount? 

My problem is specifically happening when using the navigator to push to a component, and then that component pushes again to a different (3rd) component during its' componentWillMount cycle.

ie:

COMPONENT A (initial route, touchable event - navigator push to b)
|
COMPONENT B (componentWillMount - navigator push to c, before component mounts)
|
COMPONENT C (component B should never be seen). 

The error is component C loads, and then disappears.

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/using-navigator-during-componentwillmount-bug

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
