### ISSUE TITLE
Customize the scrolling boundaries logic on a ScrollView

### ISSUE THREAD

**Issue by mquandalle** [facebook/react-native#8815]
Hello,

This feature request aims to provide an additional parameter to the `<Scrollview>` component that would be used to customize its behavior when the `pagingEnabled` mode is set to true.

Currently the paging mode works by assuming that the right edge of the current page is the left edge of the following page, this is basically the logic that is implemented [here](https://github.com/facebook/react-native/blob/b67d4a20d73f00dd42806b6c275f0982832462ac/ReactAndroid/src/main/java/com/facebook/react/views/scroll/ReactHorizontalScrollView.java#L304). That is a reasonable default, however forcing this model prevent doing other paging layout. One of these currently impossible layout is when the previous and the following pages overlap the current one so that their respective edges are visible on the screen, like in [this dribble example](https://dribbble.com/shots/2264301-Connections-app-Cards). Another example is the horizontal screenshots gallery in the Google Play Store where multiple screenshot are visible on the screen at the same time, but scrolling boundaries are still defined at the beginning of each individual image—it’s a bit difficult to describe it with words.

Since the current scrolling boundaries logic is pretty straightforward,

```java
private void smoothScrollToPage(int velocity) {
  int width = getWidth();
  int currentX = getScrollX();
  // TODO (t11123799) - Should we do anything beyond linear accounting of the velocity
  int predictedX = currentX + velocity;
  int page = currentX / width;
  if (predictedX > page * width + width / 2) {
    page = page + 1;
  }
  smoothScrollTo(page * width, getScrollY());
}
```

would it makes sense to rewrite it in JavaScript and be able to customize it at the `ScrollView` level?

**Comment by maxs15** [comment]
Would love to see such a feature !!!

**Comment by maxs15** [comment]
@nicklockwood is it possible to change the width of the pages when using the UIScrollView ``pagingEnabled``property on IOS ?

**Comment by lacker** [comment]
This seems like a reasonable feature request, but it hasn't gotten much feedback after some time has passed. You might want to put it on Product Pains. For now, I'm going to close this issue.
