### ISSUE TITLE
I use require in  Image tag，but it does not work。

### ISSUE THREAD

**Issue by imochen** [facebook/react-native#882]
```javascript
<Image source={require('image!back_button')} style={Styles.backButton} />
```

run without any error , but the image did not show ？

how can i resolve it?

thanks!

**Comment by imochen** [comment]
now , it has been resolved . but , i think you should make a demo for this。otherwise, someone maybe do not konw how to use！

**Comment by wangzhe1995** [comment]
you will set width and height

**Comment by imochen** [comment]
need Images.xcassets folder and  xx.imageset

**Comment by wangzhe1995** [comment]
@imochen The problem here is obviously not like this，If the picture is not in Images.xcassets which then displays an error, instead of not displaying an error
