### ISSUE TITLE
undefine is not a function(evaluating 'UIManager.measureViewsInRect')

### ISSUE THREAD

**Issue by phpjoe** [facebook/react-native#8823]
Hi, I have a error when i use the UIManager.measureViewsInRect in the android environment, but in the ios  it works fine.

this is my code:
`render(){
        let that = this;
        let letterArr = this.letters.map((item,index)=>{
            return (<View
                key={index} pointerEvents="none"
                style={ styles.letterItem }>
                <Text>
                    {item}
                </Text>
            </View>);
        })
		return (
            <View style={ styles.container}>
                <View style={ styles.brandWrap }>
        			<ListView
                        ref='scrollview'
                        dataSource={this.ds}
                        renderRow={this._renderBrand}
                        renderSectionHeader={this._renderBrandHeader}
                        renderSeparator={this._renderSeparator}/>
                    <View style={ styles.leterNav }
                        onStartShouldSetResponder={returnTrue}
                        onMoveShouldSetResponder={returnTrue}
                        onResponderGrant={this._detectAndScrollToSection}
                        onResponderMove={this._detectAndScrollToSection}
                        onResponderRelease={this._resetSection}>
                        {letterArr}
                    </View>
                </View>
            </View>);
	}
_detectAndScrollToSection(e) {
        var ev = e.nativeEvent;
        var rect = {width:1, height:1, x: ev.locationX, y: ev.locationY};

        UIManager.measureViewsInRect(rect, e.target, noop, (frames) => {
            if (frames.length) {
                var index = frames[0].index;
                if (this.lastSelectedIndex !== index) {
                    this.lastSelectedIndex = index;
                    this.refs.scrollview.scrollTo({y:this.letterPosition[this.letters[index]],x:0})
                    //this.onSectionSelect(this.props.sections[index], true);
                }
            }
        });
    }`

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/undefine-is-not-a-functionevaluating-uimanagermeasureviewsinrect

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
