### ISSUE TITLE
<Image /> component is not working with external URL on Android

### ISSUE THREAD

**Issue by olebedev** [facebook/react-native#8827]
Does anyone know why `<Image />` component with external(HTTPS) URL is not working correctly on Android?

I've tried to render avatar but Android just skip this `<Image />` component like it does not exist.

I'm a newbie in RN and Andriod, thanks in advance.

---
1. rnplay - https://rnplay.org/apps/9v6bpg
2. 
```javascript
<Image source={{
    url: "https://yabs.yandex.ru/resource/B4_LwOqnl6akXYQRO4jj2R_banana_20141031_1.png",
  }} style={{width: 148, height: 90}} />
```
3. RN@0.29
4. It occur on Android only
5. I'm using Mac

**Comment by mateoKaradza** [comment]
It does not work because you are using url instead of uri (ends with 'i')

**Comment by olebedev** [comment]
Thanks!
