### ISSUE TITLE
Error when trying to debug from device

### ISSUE THREAD

**Issue by vitch** [facebook/react-native#883]
After following the instructions to [run my app on a device](http://facebook.github.io/react-native/docs/runningondevice.html#content) I still got an error when I shook the device and tried to enter debug mode:

```
[RCTWebSocketExecutor.m:108] WebSocket connection failed with error Error Domain=NSPOSIXErrorDomain Code=61 "The operation couldn’t be completed. Connection refused"
2015-04-16 16:35:58.255 [error][tid:main][RCTWebSocketExecutor.m:50] Connection to http://localhost:8081/debugger-proxy timed out. Are you running node proxy? If you are running on the device check if you have the right IP address on `RCTWebSocketExecutor.m` file.
```

With help from @vjeux on IRC we got it down to [RCTWebSocketExecutor.m#L33](https://github.com/facebook/react-native/blob/862d9fba09046b6ca82bcc75197de69cbfb8fa41/Libraries/RCTWebSocketDebugger/RCTWebSocketExecutor.m#L33) where `localhost` is hardcoded. 

Hardcoding my current IP address in there fixed the issue for me but the actual fix will obviously involve passing through the value of `jsCodeLocation`.

**Comment by vjeux** [comment]
There are two other urls that are suspiciously hardcoding localhost:

https://github.com/facebook/react-native/blob/862d9fba09046b6ca82bcc75197de69cbfb8fa41/React/React.xcodeproj/project.pbxproj#L465
https://github.com/facebook/react-native/blob/862d9fba09046b6ca82bcc75197de69cbfb8fa41/React/Base/RCTRedBox.m#L85

cc @frantic

**Comment by kiddkai** [comment]
This works, thanks..

**Comment by jtremback** [comment]
Is there some solution to this? I've written a script that switches these by finding and replacing but it seems janky.

**Comment by brentvatne** [comment]
@jtremback - this is being tracked in #1429 now, PR welcome!

**Comment by jtremback** [comment]
@brentvatne wasn't there another PR where someone had written objC code to switch the IP?

**Comment by brentvatne** [comment]
@jtremback - hmm, it sounds vaguely familiar but having looked through several hundred issues in the last few days I'm having a hard time remembering exactly, if you find it let me know

**Comment by aleclarson** [comment]
#6362 and #6345 both have a go at fixing this issue
