### ISSUE TITLE
index.android.map parse fail cause `new.target` not suppot

### ISSUE THREAD

**Issue by jiw0220** [facebook/react-native#8848]
import {Component} from 'react';
export default class BaseScreen extends Component {
    constructor(props) {
        super(props);
        if (new.target === BaseScreen) {
            throw 'BaseScreen can not instantiation';
        }
    }
}

index.android.map parse fail cause `new.target` not suppot

**Comment by ide** [comment]
I believe Babel doesn't support new.target, this isn't supported.
