### ISSUE TITLE
Transform Error: Using removed Babel 5 option when importing gesture recognizers

### ISSUE THREAD

**Issue by toddflan** [facebook/react-native#8849]
I tried to ![screen shot 2016-07-17 at 1 32 04 pm](https://cloud.githubusercontent.com/assets/20504584/16902391/e30d5e46-4c22-11e6-9ad3-a30ea3dd71f6.png) and am getting this error:

![screen shot 2016-07-17 at 1 14 04 pm](https://cloud.githubusercontent.com/assets/20504584/16902336/bb85b3b0-4c21-11e6-8bf2-fde064a09e3a.png)

I've googled and tried several things but none have worked. I've seen a lot about a .babelrc file but don't know where that is.

Any help is greatly appreciated!

**Comment by grabbou** [comment]
Please fill an issue inside the `react-native-gesture-recognisers` repository, it's likely an issue on their end. Thanks!
