### ISSUE TITLE
[AppStateIOS] Can only have one listener, and general issue with AppStateIOS

### ISSUE THREAD

**Issue by drkibitz** [facebook/react-native#885]
See this line:
https://github.com/facebook/react-native/blob/72d3d724a3a0c6bc46981efd0dad8f7f61121a47/Libraries/AppStateIOS/AppStateIOS.ios.js#L85

This looks like a mistake at first glance, but still wanted to make sure.

If this is a compatibility API ok, but I am doubting it given how new this code-base is.

My suggestion, ditch wrapping RCTDeviceEmitter, and just make this module a simple object with currentState property, and potentially wrapping more future calls to RCTAppState.

---

On another note... a suggestion would be to **drop this module altogether**, and take a look at unifying many of the UIApplication APIs under a single module (e.g. RCTApplication), maybe this is what this module is for? Then introduce a new module like "RCTDevice".

There's quite a few other issues floating around about a device API, I myself have written one for orientation, battery state, and whatnot, but have not made it available. There's already [something available on react.parts](https://github.com/pjjanak/react-native-viewport) (but quite different than mine I'm afraid). I'm sure there's more ;)

---

I believe it's important to get these right, as they will most likely always be used in production apps... well used if available, otherwise always reimplemented ;)

**Comment by brentvatne** [comment]
@drkibitz - thanks for the report! This is fixed now: https://github.com/facebook/react-native/blob/master/Libraries/AppStateIOS/AppStateIOS.ios.js#L92-L103

The events are communicated through the `RCTDeviceEventEmitter` so you could access all of the events through that, this module just wraps that to make it even simpler to manage.

I'd love to see your module, could you share it?

**Comment by drkibitz** [comment]
@brentvatne Thanks, it's really nothing special I never intended to share, I'll see if I can get it into an archive.

**Comment by drkibitz** [comment]
I haven't been keeping as close of an eye on things as I was a month ago, was there anything added for orientation support?

**Comment by brentvatne** [comment]
@drkibitz - unfortunately not :(

**Comment by drkibitz** [comment]
@brentvatne, here you go https://github.com/drkibitz/react-native-device-state

be kind :wink:

**Comment by brentvatne** [comment]
Thanks! Will check it out tomorrow
