### ISSUE TITLE
Run on device for iOS? (RN .29)

### ISSUE THREAD

**Issue by natdm** [facebook/react-native#8850]
Running on a device for iOS on .29 seems to be different than where I was at (.26).

On .29, the AppDelegate.m file is vastly different than it was. there's no comments explaining what to do for dev or production. 

Docs say:
Open ios/YourApp/AppDelegate.m
Uncomment the line, jsCodeLocation = [[NSBundle mainBundle] ...

My AppDelegate.m has a jsCodeLocation but not [[NSBundle mainBundle] ...

`#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  [[RCTBundleURLProvider sharedSettings] setDefaults];
   jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"BidSmart"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

@end`

When I comment out the jsCodeLocation variable in my AppDelegate.m, I get "Unable to execute JS call: __fbBatchedBridge is undefined" on the app - but it builds successfully.

**Comment by rturk** [comment]
@natdm since you've changed AppDelegate.m you need to rebuild your project and reload the app

**Comment by mkonicek** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @mkonicek says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by natdm** [comment]
@rturk I thought I did that - I had react-native update all my files.

**Comment by natdm** [comment]
Just tried the same thing on a new project and it still failed - so there's probably a different way than the docs describe to package .29 to the device.

**Comment by nathanajah** [comment]
Hey @natdm, can you give me the details on how is your network being setup?

The new AppDelegate.m should be able to detect your IP address automatically.

**Comment by natdm** [comment]
It's nothing different than it was before I upgraded, but it's possible that would explain my other issue - I can't make a network call within the app if I run the app on the cell without trying to bundle the JS file to the phone. 

I can get to 192.168.0.13:3000/wherever in Safari on my device, but I can't make the call within my app now that I upgraded - failed network call. It will work in the emulator though, when everything is set to localhost.

This doesn't work no matter what network I'm on - been to three locations, all 3 used to work before this.

Not sure what to give you on my network settings. The phone and mac are both on the same network and can reach each other outside of the application. The app has a socketed connection that works fine, but not anything else. Again, this all worked perfectly before the upgrade.

**Comment by nathanajah** [comment]
Can you try to access 192.168.0.13.xip.io:3000 from your phone? We added the xip.io workaround to circumvent the App Transport Security limitation.

**Comment by natdm** [comment]
I'm currently at work so my network location has changed. I can get to 172.xx.xx.xx.xip.io:3000 in the browser though.

I can't get to it from the app on the phone.

Console error:

> ExceptionsManager.js:70 Error caught at loginAuth TypeError: Network request failed(…)reactConsoleError @ ExceptionsManager.js:70console.error @ YellowBox.js:59(anonymous function) @ authLogin.js:74(anonymous function) @ login.js:26tryCallOne @ core.js:37(anonymous function) @ core.js:123JSTimersExecution.callbacks.(anonymous function) @ JSTimers.js:79callTimer @ JSTimersExecution.js:69callImmediatesPass @ JSTimersExecution.js:127callImmediates @ JSTimersExecution.js:142(anonymous function) @ MessageQueue.js:136guard @ MessageQueue.js:41__callImmediates @ MessageQueue.js:136(anonymous function) @ MessageQueue.js:94guard @ MessageQueue.js:41callFunctionReturnFlushedQueue @ MessageQueue.js:92onmessage @ debuggerWorker.js:39

**Comment by natdm** [comment]
And here is the authLogin function calling the console.error() (line 74 is the console error call):

```
loginAuth(profile.userId, profile.email, profile.phone, (err, user_info) => {
                    if (err) {
                        this.setState({ loading: false, disabled: false });
                        console.error("Error caught at loginAuth", err);
                        setError("fatal", err.toString())
                        return
                    }
                    const newProfile = Object.assign({}, profile, {
                        user_id: user_info.user_id
                        , auth_id: profile.userId
                        , email: user_info.email
                        , opt_in_email: user_info.opt_in_email
                        , phone: user_info.phone
                        , opt_in_phone: user_info.opt_in_phone
                        , opt_in_notified: user_info.opt_in_notified
                        , card: user_info.card
                        , cc_warning: user_info.cc_warning
                    });

                    login(newProfile);

```
And the loginAuth function:


```


export const loginAuth = (auth_id, email, phone, cb) => {
 
    authorize((auth_key, headers) => {
        fetch(authLogin, {
            method: "POST",
            body: JSON.stringify({ auth_id, email, phone }),
            headers
        })
            .then(response => response.text())
            .then(responseText => JSON.parse(responseText))
            .then(responseText => cb(null, responseText.payload))
            .catch(e => cb(e, null));
    });
};
```

And authorize:

```

export default authorize = (cb) => {
    AsyncStorage.getItem('userToken', (err, auth_key) => {
        if (err) {
            console.error("Error getting the auth_key from async storage", err);
            //TODO: Throw app error here and show a friendly screen
        } else {
            const headers = {
            'Authorization': `bearer ${auth_key}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json'
        };
            cb(auth_key, headers)
        }
    })
};
```

**Comment by natdm** [comment]
And I can make all my API calls in Safari with xip.io

**Comment by nathanajah** [comment]
How is the login network request being setup? Do you just specify an IP address or do you have a domain name?

**Comment by natdm** [comment]
I'm only working with the URL's I pasted above - all IP's and I change them depending on what location I'm at.

**Comment by nathanajah** [comment]
Ah, sorry, I didn't read your last comment.

https://github.com/facebook/react-native/pull/5355

That pull request changed the ATS settings from `NSAllowArbitraryLoads`, which means that any network request is allowed, to an exception just to the localhost only.
Because of this, you'll need to add exceptions to any HTTP request that you do. (HTTPS request will be allowed, if I understand this correctly).

In addition to this, since Apple's ATS settings doesn't allow numerical IP address, you'll need to have some workaround for it. We do that for the packager by using <ip_address>.xip.io, which will redirect to <ip_address>.

**Comment by natdm** [comment]
Well that did it - for now I just disabled it. I went through all the changes from .26 to .29.1 and seemed to have missed this. 

RN is changing so fast.

Thank you so much for your help, @nathanajah !

**Comment by natdm** [comment]
@nathanajah  - How would I package on the device?

**Comment by nathanajah** [comment]
What do you mean by "package on the device"?

**Comment by natdm** [comment]
I mean if I leave the AppDelegate.m the way it is, build through XCode to my device, the packager is running on my macbook. If I close the packager, the app dies. How do I create a production-ready package for the app in .29?

**Comment by nathanajah** [comment]
Have you tried running the app without the packager running?
It should have an auto-switch built in now - if the packager is running, it will use the packager. If it's not, it should use the bundle.

**Comment by natdm** [comment]
If I build the app, close the packager, restart the app, I get this error:
![img_1523](https://cloud.githubusercontent.com/assets/11272201/16924178/d72db66a-4cd2-11e6-96c3-00418b25e4ef.PNG)

**Comment by natdm** [comment]
I had remote debugging turned on. Works great without it.. apparently I've missed a lot. Thanks again @nathanajah

**Comment by nathanajah** [comment]
Great! Maybe we can look into how to provide a better error message or automatically disable remote debugging on bundle.

**Comment by natdm** [comment]
Would be a good idea. I had to take a look at the RCTWebSocketExecutor.m to figure out what was going on. Small hiccup.
