### ISSUE TITLE
[iOS] Image not loaded, warning RCTImageLoader.m:599 PERF ASSETS Loading image at size{1920,1200}, which is larger than the screen size {750,1334}

### ISSUE THREAD

**Issue by weixingsun** [facebook/react-native#8853]
Image function works properly in Android, but blocked in iOS 9.3.1.
A very very simple code as following:
<Image key={pic.uri} source={{uri:'...'}} style={{width:DEVICE_WIDTH,height:DEVICE_HEIGHT}} />
From the log, it looks like tried 3 attempts: 
1.with original size: 1900,1200
2.with device size: 751,1334
3.with device size: 751,1334
![big_image_error](https://cloud.githubusercontent.com/assets/5229930/16904795/40deb2cc-4cf0-11e6-8f4c-b0f37c2adb40.PNG)

Should I shrink my photo size?

**Comment by weixingsun** [comment]
does anybody have this problem on iOS ? @@

**Comment by flaviotobi** [comment]
I have those warnings in my app to. But because they are only warnings i didn't pay much attention in resolving them.
But i would like to know whats going on :)
How was blocked in iOS? my app runs normal with that warning, can you give more details? 
iOS 9.3

**Comment by ioslcf** [comment]
meet this too, can anybody solve this pro?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/ios-image-not-loaded-warning-rctimageloaderm599-perf-assets-loading-image-at-siz

**Comment by danieldelouya** [comment]
I get these warning too

**Comment by eyalw** [comment]
I get them too

**Comment by danieldelouya** [comment]
@eyalw I solved it by looking at the imageStyle prop for ImageBackground where i set `resizeMode: 'contain'`

For example: 
```
 <ImageBackground source={require('../../assets/bg.png')} style={styles.image} imageStyle={styles.imageStyle}>
              {this.props.children}
</ImageBackground>
```

**Comment by tangweikun** [comment]
I got this warning because of I forgot set the Image width
Just set a width that small than screen width can solve this warning
