### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException

### ISSUE THREAD

**Issue by lotosbin** [facebook/react-native#8857]
when enable remote js Debugging ,sometime throw JsonParseException.

![qq 20160718151413](https://cloud.githubusercontent.com/assets/221294/16907984/8041f6c2-4cfa-11e6-85e4-2bec08e75d98.png)
![qq 20160718151623](https://cloud.githubusercontent.com/assets/221294/16908005/9f9e85f8-4cfa-11e6-86c1-96981bf16d68.png)

c:\Users\liubinbin\Documents\2ours\sloth-app>react-native -v
react-native-cli: 1.0.0
react-native: 0.29.2

c:\Users\liubinbin\Documents\2ours\sloth-app>

**Comment by sd5869** [comment]
I am also facing the same issue please fix this.

**Reproducing the Error:**
- ignite new MyApplication
- react-native run-android

Then turn on the remote js debugging and then perform any action by tapping on buttons 

**Screenshot of device** 
![screenshot_20160718-144256](https://cloud.githubusercontent.com/assets/8257951/16910476/7a21758c-4cf6-11e6-81f7-d94ae3271550.png)

**dependency versions:**
- react-native-cli: 1.0.0
- react-native: 0.28.0
- ignite: 1.3.0

**Comment by Elyx0** [comment]
Bumping for annoyance.
react-native 0.29

**Comment by lotosbin** [comment]
#6679
 #8512
