### ISSUE TITLE
listview row not display ,it show when i touch 

### ISSUE THREAD

**Issue by Ping5841** [facebook/react-native#8865]
iOS 9.2
RN 0.29

**Comment by MrPing** [comment]
I have the same problem with RN 0.30 and iOS 9.3.2. No problem previously with RN 0.25.

![](https://media.giphy.com/media/l41YdMzgnCGPEM8bm/giphy.gif)

**Comment by cpsubrian** [comment]
Can also report this with `RN 0.30.0-rc.0`. Trying `removeClippedSubviews={false}` in the meantime.

**Comment by chirag04** [comment]
let's consolidate the discussion in #8607
