### ISSUE TITLE
Could not install the app on the device, read the error above for details.

### ISSUE THREAD

**Issue by RainliFu** [facebook/react-native#8868]
``` 
jax$  react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug...

Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

jax$ adb devices
List of devices attached
192.168.56.101:5555	device
```

how can I fix it , On my computer .
It's ok for react-native run-ios 
and it's ok for react-native run-android  on my company computer

**Comment by cyprusglobe** [comment]
you might check the permission on android/gradlew

they should be 755 not 644

run ```chmod 755 android/gradlew``` inside your app root folder and that should solve your error

**Comment by RainliFu** [comment]
@cyprusglobe 
Thanks for your help,I will try later!
My company computer is ok .

**Comment by srahulprdxn** [comment]
@cyprusglobe Your suggestion worked. Thanks a lot.

**Comment by RocWangv** [comment]
It works for me too !! Thx!!! @cyprusglobe

**Comment by scheriff** [comment]
@cyprusglobe should this be put in documentation?

**Comment by cmaring** [comment]
Works for me too. Thanks.

**Comment by uragecz** [comment]
I have simillary issues but error message looks -```
```
 Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define La
ndroid/support/v7/appcompat/R$anim;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexM
erger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerg
er.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerg
er.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.j
ava:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:1
89)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuff
ers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.jav
a:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)

Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

:app:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_101\bin\java.exe'
' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 22.166 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:6876) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 2): TypeError: Cannot read property 'message' of undefined
```
```

**Comment by nysin** [comment]
@cyprusglobe thanks your advice.it's useful

**Comment by liyanxi** [comment]
@cyprusglobe 
Thanks for your help.
This pit is good!

**Comment by AshokICreate** [comment]
how about windows i am getting the same error?

**Comment by ignacy130** [comment]
Had similar problem, but with 
`NoClassDefFoundError`. Uninstalling java and jdk, rebooting and installing java and jdk (x86 and x64) helped me.

**Comment by JamesJin038801** [comment]
Thanks, it worked!

**Comment by hanweixing** [comment]
@cyprusglobe it works for me too, thanks

**Comment by leon2017** [comment]
if your android rom is MIUI ROM,find the solution: go settings -> developer option -> close MIUI optimization

**Comment by sukeyang** [comment]
Thanks, it worked! good !

**Comment by eaintphyo** [comment]
I got the same error on windows. Could you give me some solutions?

**Comment by coderabsolute** [comment]
Am running into similar issue and am not sure how to @cyprusglobe's solution....

**Comment by eaintphyo** [comment]
I also try like this as you commented, but the error has not gone. I want to run with external device.

**Comment by eaintphyo** [comment]
I finally figured out the problem and solved it.

**Comment by Anndyang2017** [comment]
@eaintphyo ,我想知道你是怎么解决的呀！？

**Comment by Anndyang2017** [comment]
@eaintphyo ,can you share the experience! thanks!

**Comment by eaintphyo** [comment]
@Anndyang2017 Here's my solution,
https://stackoverflow.com/questions/43521533/error-could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain/44150895#44150895

**Comment by fulushan** [comment]
@cyprusglobe  thanks!

**Comment by muhtarA** [comment]
@cyprusglobe you're clever
thx man

**Comment by MauriceMahan** [comment]
@cryptobiote Thanks for this.

Windows users will want to run `chmod 755 android/gradlew.bat`

**Comment by muhtar93** [comment]
Yes, i know
But i'm mac users :)

**Comment by MintyOwl** [comment]
I am on windows and I got this working by reinstalling `react-native-cli`

`npm uninstall -g react-native-cli`

`npm install -g react-native-cli`

**Comment by MintyOwl** [comment]
On windows, this can be resolved by reinstalling `react-native-cli`

`npm uninstall -g react-native-cli`

`npm install -g react-native-cli`

Restart powershell and Android Studio. You must start a new project and delete old ones.

`react-native init NewProject`

**Comment by WeslleyNasRocha** [comment]
It worked for me :+1:

**Comment by kostyaVyrodov** [comment]
It helped on windows:
Run 'react-native run-android' via cmd as admin

**Comment by sheyda93** [comment]
hi , when I wanna run project , I have this error , guide me plz: 
Scanning 556 folders for symlinks in C:\Users\sheyda\shidi\node_modules (63ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

Unzipping C:\Users\sheyda\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv\gradle-2.14.1-all.zip to C:\Users\sheyda\.gradle\wrapper\dists\gradle-2.14.1-all\8bnwg5hd3w55iofp58khbp6yv
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.gradle.wrapper.Install.unzip(Install.java:159)
        at org.gradle.wrapper.Install.access$500(Install.java:26)
        at org.gradle.wrapper.Install$1.call(Install.java:69)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by kostyaVyrodov** [comment]
@sheyda93 
I sometimes still run into the error, and you can try to perform next steps: 
1. Go to android-sdk\platform-tools\adb.exe and run via cmd: adb.exe devices
You should make sure that device is really visible
2. Remove all files from the dir: <yourproject>../android/app/build
(the build dir should be empty)
3. Uninstall app from emulator (if you have already installed it)

Try to install again

**Comment by marceloaraujo** [comment]
@cyprusglobe Man, you saved my life. Thanks a lot!!!

**Comment by enzeberg** [comment]
For Windows:
@kostyaVyrodov is right. Running "react-native run-android" via cmd as admin helps. Use cmd as admin, but not PowerShell.

**Comment by labidiaymen** [comment]
@enzeberg Running "react-native run-android" via cmd as admin helps me also.

**Comment by ngoctuong96** [comment]
how to check permission on android/gradlew?

**Comment by TheHemantKaushik** [comment]
**I'm running command as:**

`sudo react-native run-android`

**Comment by shenghaoAN** [comment]
It works for me.

**Comment by joelGarcia93** [comment]
I was facing same issue, I fixed by running "npm install" Lol

**Comment by TheHemantKaushik** [comment]
I tried "sudo react-native run-android", working fine!

**Comment by marcelloJr** [comment]
Basta modificar a permissão da pasta `android/grandlew` dentro da raiz do projeto, ou você pode rodar o comando `sudo react-native run-android`...

**Comment by guguji5** [comment]
"chmod -R 777 android/grandlew" doesn't work in my mac

**Comment by Allajah** [comment]
I have a same issue on Ubuntu 16.04.3. I tried `chmod 755 android/gradlew` but it doesn't work

**Comment by AnandanRajkumar** [comment]
> Starting JS server...
> Building and installing the app on the device (cd android && gradlew.bat install
> Debug)...
> Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html


List of devices attached
C4F12440556EC9E device

if i try this chmod 755 android/gradlew

i am getting chmod not a internal and external commend
Note: i am using windows 8.1

this will happen after npm run eject

please any one help to solve this.

**Comment by uguryiilmz** [comment]
Why there is still no solution for windows??

**Comment by akshayseth** [comment]
For me enabling developer options in emulator worked.I mean obviously you have to do that boi!

**Comment by nullxlren** [comment]
今天也遇到这个问题，刚解决，在项目下：
执行：chmod 755 android/gradlew    =>没解决
执行： chmod 755 . =>已解决

**Comment by VivekHA** [comment]
Hello,
Im getting same error message.

C:\Projects\MobApp\Project1\sample1>react-native run-android
Scanning folders for symlinks in C:\Projects\MobApp\Project1\sample1\node_modules (249ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip

Exception in thread "main" java.net.UnknownHostException: services.gradle.org
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
        at com.sun.net.ssl.internal.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:59)
        at org.gradle.wrapper.Install$1.call(Install.java:46)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:46)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Where do i run this commend ? chmod 755 android/gradlew
if i run this in terminal i get this error message : 'chmod' is not recognized as an internal or external command,
operable program or batch file.
