### ISSUE TITLE
support SceneConfigs for navigator replace.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native#887]
We need to create navigation something like this:

``a -> b -> c -> d`` back button on b, c, d should take you back to ``a`` at all times.

We are using replace for navigation from ``b->c->d`` However there is  no animation support for replace. 

Is there a better way to do this with animations?

@vjeux

**Comment by vjeux** [comment]
@ericvicenti

**Comment by ericvicenti** [comment]
Instead of using `replace`, use `push` to animate to `b->c->d`

Then, instead of doing a pop on the back button press, do `popToTop()`, so pressing back will always take you to `a`

**Comment by chirag04** [comment]
@ericvicenti `a` here was just for example and not the top of the stack. Actually there is one more view before `a`.

**Comment by ericvicenti** [comment]
Have you tried `popToRoute(route)`?

http://facebook.github.io/react-native/docs/navigator.html#navigation-methods

**Comment by chirag04** [comment]
popToRoute give me ``Invariant Violation: Calling pop to route for a route that doesn't exist!"``

**Comment by chirag04** [comment]
So here is the hierarchy: x -> a -> b -> c -> d.

A back on b, c or d should take you back to a. b to you to c though. I use replace in b to take you to c and so on for d

I hope the context is clear.

**Comment by Kureev** [comment]
I'm not sure, but it seems you're trying to access re-create the same route, when you need to pass **exactly** the same route. So maybe storing a link to the route object and using it may help.

**Comment by chirag04** [comment]
nope. I'm not trying to create the same route. I just want that when you are on c and you press back it should jump to a instead of b.

**Comment by Kureev** [comment]
Yeah, I got your case. Could you provide gist with example or smth?

**Comment by chirag04** [comment]
Codebase is too long for a gist etc. 

This is what i do in b.js
```
if(this.state.runNext) {
      return this.props.navigator.replace({
        component: require('./c'),
        sceneConfig: Navigator.SceneConfigs.FloatFromRight,
      });
    }
```

**Comment by Kureev** [comment]
```javascript
if(this.state.runNext) {
  this.props.navigator.popToRoute({
    component: require('./c'),
    sceneConfig: Navigator.SceneConfigs.FloatFromRight,
  });
}
```
Doesn't work?

**Comment by ericvicenti** [comment]
@Kureev, close, but that creates a new route object. The navigator will look in the route stack for that object but it cannot be found. You need a reference to the exact same route object, you cannot create a similar one.

@chirag04, if you want an animation then you should use push. Replace will swap out the scene immediately.

If I understand correctly, then you want to make it easy to get back to the `x` scene. At some point you surely call `navigator.push(xRoute)` in order to load the `x` scene in the first place. You need to save a reference to `xRoute` so you can later call `navigator.popToRoute(xRoute)`. Does that make sense?

If you put your code in a simplified gist, I can show you how to do that.

**Comment by chirag04** [comment]
@ericvicenti popToRoute makes sense and like you said i will need to store reference to the parent Scene. Is there a set way of keeping a reference to the parent Scene or should i just pass that as prop to the child scene.

**Comment by ericvicenti** [comment]
You could pass as a prop, or if you only want to render that scene once, you could put the route in a module.

**Comment by chirag04** [comment]
Sure, That seems to work here. 

Just a suggestion: just like ``parentNavigator``, can we support ``parentRoute`` in the navigator?

**Comment by ericvicenti** [comment]
I am hoping to move away from `parentNavigator`, because it is very confusing when child scenes have direct access to the parent hierarchy.

Can you use `parentNavigator.route` for that?

**Comment by chirag04** [comment]
Ah i see. Makes sense. I din't try ``parentNavigator.route`` yet. Will let you know.

Thanks for taking the time out to help me. You guys are awesome.

**Comment by franjoSpark** [comment]
i have similiar problem with error message "undefined is not a object evaluating sceneConfig..."
I'm using .popToPop() and it's working, but after change route app crash with above error, so problem was I did't bind this on my function with popToPop method...
sry for eng
