### ISSUE TITLE
Trigger Pop instead of Jump to horizontal swipe jump

### ISSUE THREAD

**Issue by cpsiaki** [facebook/react-native#8877]
By default it seems that when you push a route onto the navigator with HorizontalSwipeJump and then swipe back to the root route (lol), it will JumpTo instead of pop.

Is there a way to make it pop?

Thanks!

**Comment by cpsiaki** [comment]
I changed line 680 in react-native/Libraries/CustomComponents/Navigator/Navigator.js to:

          if (releaseGestureAction === 'pop' || releaseGestureAction === 'jumpBack') {

Just in case anybody else wants to know.

**Comment by malcolmyu** [comment]
Hi, @cpsiaki. I meet the same problem, but I'm wondering whether it's a bug or by design: **the swipe gesture will not clean scenes**.

```js
if (releaseGestureAction === 'pop') {
  this._cleanScenesPastIndex(destIndex, recorder);
}
```

**Comment by beeant** [comment]
I ran into this problem too, and here's how I fixed it.

```javascript
<Navigator
  ...
  configureScene={(route) => Object.assign(
    {},
    Navigator.SceneConfigs.HorizontalSwipeJump,
    {
      gestures: {
        pop: Navigator.SceneConfigs.HorizontalSwipeJump.gestures.jumpBack,
      },
    },
  )}
/>
```
