### ISSUE TITLE
How to init at specific version

### ISSUE THREAD

**Issue by hasen6** [facebook/react-native#8879]
How can I init a new project at a specific version?

$ react-native@27.2 init newProject --verbose

Doesn't work for example. I asked on stackoverflow and was told to install once, delete the node_modules and then run the following:

$ npm install -S react-native@0.27.2

But 1. this is very long winded since it means installing twice and 2. it doesn't work properly since other areas are also different for each version, for example the AppDelegate.m.  The only reliable way is to install at a certain version from the beginning so the whole project is that version.

With every new release of React Native, more and more plugins become incompatible and are largely not supported by their authors. So the only option is to continue using previous versions that work with the plugins.

**Comment by stoffern** [comment]
> With every new release of React Native, more and more plugins become incompatible and are largely not supported by their authors. So the only option is to continue using previous versions that work with the plugins.

I would say that this is not the reality as most plugins gets updated quite often.
There is no breaking changes for plugins in react since 0.26. Altho there is a bug in 0.29, 0.29.1 for `react-native link` this is fixed in the 0.29.2

If you absolutely want 0.27.2 then:
```
- npm i -S react-native@0.27.2
- npm upgrade
```
and you are good to go, no double installation.

**Comment by hasen6** [comment]
Most is not all. There's a plugin I use on almost every project and it hasn't been updated for 6 months. What I'm using is 29.2 so....

Isn't that code exactly the same as I referenced in my first post? That doesn't create a project, all it changes is are the node modules so you'd have to install 29.2 and then delete the node modules. Also it wouldn't alter any of the project files like.....well it's all in my first post, no point in repeating it all again.

**Comment by stoffern** [comment]
@hansen6 what plugin is that?

**Comment by hasen6** [comment]
react-native-linear-gradient

**Comment by hasen6** [comment]
Its beside the point anyway, I just want to know how to install a project that is not the latest version. I tried the method you describe prior to this but running the project resulted in instant failure because the appdelegate was also different. Its just not reliable or even practical to do that.

The most practical way is to install a new project from scratch with a specific version of RN. New versions of any program are not always the ultimate or most useful version so you have to have the option to install previous versions.

**Comment by stoffern** [comment]
@hansen6 just tested `react-native-linear-gradient` working like a charm on RN 0.29.2.
https://github.com/stoffern/rnGradiantTest

**Comment by hasen6** [comment]
So to be clear, its not possible to install anything other than the latest version? The only way is to install the latest version first, delete node_modules, reinstall with previous version and then try to fix any other files outside of node_modules.

**Comment by grabbou** [comment]
```
$ react-native init --version 0.27.0
```
See more details here: https://github.com/facebook/react-native/blob/master/react-native-cli/index.js#L51

**Comment by hasen6** [comment]
So it can be done after all. Ok great.

**Comment by vsakos** [comment]
I got it working with
`react-native init AppName --version 0.47.2`
