### ISSUE TITLE
borderRadius is never applied on Android when image contains another component

### ISSUE THREAD

**Issue by 5in4** [facebook/react-native#8885]
While working perfectly on iOS, border radius is never applied to an image if it contains any other component:

`
<Image style={ { borderRadius: 10, width: 300, height: 100 } } source={{ uri: 'https://placekitten.com/300/100' }}>
                <Text>SampleText</Text>
</Image>
`

ios:
<img width="329" alt="ios" src="https://cloud.githubusercontent.com/assets/286750/16942670/a2ffa040-4d97-11e6-8db3-b047356f06c5.png">

android:
<img width="381" alt="android" src="https://cloud.githubusercontent.com/assets/286750/16942704/d4729998-4d97-11e6-9913-37f3b84f7096.png">

I am using RN 0.29.0, and this is happening across all Android devices. I am currently building from osx

**Comment by austinksmith** [comment]
I'd imagine the "fix" for this would be to wrap the image in a view that contains border radius instead. Eg. 
`<View style = {{flex: 1,  borderRadius: 10}} ><Image style={ {width: 300, height: 100 } } source={{ uri: 'https://placekitten.com/300/100' }}> <Text>SampleText</Text> </Image> </View>`

**Comment by 5in4** [comment]
Tried it, unfortunately the images still had no borderRadius applied.

**Comment by Dynom** [comment]
@5in4 did you try it with a more recent RN version?

**Comment by yazgazan** [comment]
I managed to get around this by having the Text after the image and setting it to `absolute/top:0`.

```jsx
<View style={container}>
  <Image {/*...*/} />
  <Text style={{ position: 'absolute', top: 0 }}>{text}</Text>
</View>
```

This could could probably be fixed by using RN 0.30.0 (see [v0.30.0 release notes](https://github.com/facebook/react-native/releases/tag/v0.30.0) )

**Comment by 5in4** [comment]
I tried it on RN 0.30 and on 0.31 RC, behavior doesn't change.

@yazgazan seems to be reasonable workaround

**Comment by StellwagJo** [comment]
Still having this issue with RN 0.31 on Android

**Comment by leeight** [comment]
Still having this issue with master on Android

**Comment by Canedo** [comment]
Still having the same issue with RN 0.36 on Android.

**Comment by SushilShrestha** [comment]
Managed to solve the problem using the `borderRadius` attribute on the Image instead of providing as style.
RN 0.40
```js
<Image
  source={{uri: 'http://lorempixel.com/400/300/'}}
  height={100}
  resizeMode="cover"
  borderRadius={10}
>
  <MyCustomComponent />
</Image>
```

**Comment by anti-nerd** [comment]
Thanks @SushilShrestha for this. It works for me and has maybe saved me a couple of potentially agonizing minutes trying to find solutions. I have a `Button` element within my image which screwed up with its styling a bit, but adding `borderRadius={50}` to the `Image` and maintaining `resizeMode: "cover"` in my styles fixes the issue.

**Comment by dariocravero** [comment]
@SushilShrestha that works for me too, thanks :).

However, do you get a warning like `You're setting the style { bordeRadius: ...} as a prop. You should nest it in a style object. E.g.: { style: { borderRadius: .. } }` when using it? I guess it makes sense since the docs say it's meant to be used in the style only. However, [there's a setter for it](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java#L119-L136) which I reckon it's why it works outside of style.

I wonder why it's not being picked up when it's defined as a style though because it works if the style is manually set through the react-devtools!

**Comment by leethree** [comment]
@dariocravero I'm seeing the warning only on iOS. The warning goes away if I set `bordeRadius` prop only when `Platform.OS === 'android'`.

**Comment by pintocarlos** [comment]
We tried the trick of applying the border radius to the Image and it works inconsistently. Only some corners look rounded at random. This only happens on Android.

**Comment by pintocarlos** [comment]
This was fixed in RN 0.50.4

**Comment by vvavepacket** [comment]
I am using RN 0.51.0 and issue still persists

**Comment by xavier86** [comment]
+1

**Comment by kelset** [comment]
I suggest you check this other issue https://github.com/facebook/react-native/issues/2468#issuecomment-308840184

(this is in fact a duplicate)

**Comment by vijaya06** [comment]
borderRadius is not working in right Side only.

**Comment by alzalabany** [comment]
using .54 and issue still exsists on android

**Comment by thangkho** [comment]
using RN 0.54.2 and issue still exists on android. so sad

**Comment by amitassaraf** [comment]
Still happening & currently using @SushilShrestha 's fix

**Comment by suprraz** [comment]
0.55 and still exists on android.

**Comment by hpbyte** [comment]
this fixes for me
`<ImageBackground source={{ }} borderRadius={20}>
 <Text>Placeholder Text</Text>
</ImageBackground>`

**Comment by askarhu** [comment]
`resizeMode="cover"` and `borderRadius={n}` got it to work on Android. Thanks for the tip, resizeMode is the key and also using borderRadius on the element itself.

**Comment by kelset** [comment]
Closing this since in #2468 there are multiple viable solutions.
