### ISSUE TITLE
[Android] Error while updating property 'src' of a view managed by: RCTImageView

### ISSUE THREAD

**Issue by mhollweck** [facebook/react-native#8895]
Upgraded a project from 0.27.1 to 0.29.2 and changed all necessary things for Android as written here https://github.com/facebook/react-native/releases/tag/v0.29.0. -- same project works with iOS just fine!

Any idea why this is happening?

**Comment by DmytroT** [comment]
the same problem when updated from 0.28 to 0.30
any updates?

**Comment by yuanboGeng** [comment]
you can try 
app=>build.gradle
compile "com.facebook.react:react-native:0.29.2"

android => build.gradle
maven{
            url "$rootDir/../node_modules/react-native/android"
        }

**Comment by DmytroT** [comment]
it doesn't work:
Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.facebook.react:react-native:0.29.2. 
the same for 0.30

**Comment by binqiangsun** [comment]
is this solved?

**Comment by DmytroT** [comment]
It doesn't

четвер, 28 липня 2016 р. користувач Binqiang Sun <notifications@github.com>
написав:

**Comment by xujinyang** [comment]
![image](https://cloud.githubusercontent.com/assets/4199903/17800238/edefc9b0-6613-11e6-8aab-5f7b2538e591.png)

l am not happy because this crash

**Comment by xujinyang** [comment]
@mhollweck @DmytroT @binqiangsun  are you fix it ? please update here

**Comment by Richard-Cao** [comment]
@satya164

**Comment by 6pm** [comment]
RN 0.33 version not works too

**Comment by radirk** [comment]
Not sure if this applies to your project, but I had success with updating 

https://github.com/FuYaoDe/react-native-app-intro

**Comment by steveliles** [comment]
We saw the same issue when `src` prop is an array of candidate images with dimensions and some of the objects in the array are missing a dimension (height or width). The problem only manifests on Android.

This works:

```
  <Image style={{width:140,height:140}} source={[{
    uri: 'https://facebook.github.io/react-native/img/opengraph.png',
    width: 100,
    height: 100
  }, {
    uri: 'https://facebook.github.io/react-native/img/opengraph.png',
    width: 200,
    height: 200
  }]}/>
```

This breaks with redbox and 'Error while updating property 'src' of a view managed by: RCTImageView':

```
  <Image style={{width:140,height:140}} source={[{
    uri: 'https://facebook.github.io/react-native/img/opengraph.png',
    width: 100,
    height: 100
  }, {
    uri: 'https://facebook.github.io/react-native/img/opengraph.png',
    width: 200
  }]}/>
```

**Comment by MattFoley** [comment]
I don't know if this is helpful, but this only happens when LayoutAnimation is enabled.

**Comment by HAPENLY** [comment]
I use the 0.42.3 version, also appeared in this issue, how to solve?

**Comment by agrass** [comment]
I'm with RN0.35 also with this issue in some devices. Any workaround?

**Comment by raihanabbas232** [comment]
having same issue in August too...

**Comment by jeftarmascarenhas** [comment]
I resolve with
`<Image
      style={styles.backgroundImage}
      source={require('./bg-user.jpg')}
  />`
image local not use  property 'uri';
