### ISSUE TITLE
Error in react-packager

### ISSUE THREAD

**Issue by saveliy-kremen** [facebook/react-native#8899]
Error in react-native/packager/react-packager/src/Server/index.js :653
SyntaxError: Unexpected token )

**Comment by KGALLET** [comment]
which version of RN are u using?

**Comment by saveliy-kremen** [comment]
last

**Comment by ide** [comment]
My guess is that you're using an old version of Node. Try installing nvm and running:

```sh
nvm install 6
nvm alias default node
```

**Comment by saveliy-kremen** [comment]
The error persists:
Error in react-native/packager/react-packager/src/Server/index.js :623
SyntaxError: Unexpected token )

**Comment by saveliy-kremen** [comment]
My guess is that extra comma https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Server/index.js :line 652

**Comment by ide** [comment]
Maybe a bad babel config somewhere then?

**Comment by saveliy-kremen** [comment]
I do not know.
I'm trying to do everything on the instructions on Win7:
choco install nodejs.install
choco install python2
npm install -g react-native-cli
react-native init Project

D:\Локальные проекты\React\Native\Project\node_modules\react-native\packager\react-packager\src\Server\index.js:623
      ),
      ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Локальные проекты\React\Native\Project\node_modules\babel-register\lib\node.js:166:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Локальные проекты\React\Native\Project\node_modules\react-native\local-cli\bundle\buildBundle.js:17:16)

**Comment by grabbou** [comment]
Please share output of `node --version` and `ls -all` when run from within the root folder of your project.

**Comment by jackbillstrom** [comment]
node --version
`v6.4.0`

ls -all
```
total 165
drwxr-xr-x 1 Administratör 197121   0 Aug 27 20:54 ./
drwxr-xr-x 1 Administratör 197121   0 Aug 27 20:44 ../
drwxr-xr-x 1 Administratör 197121   0 Aug 27 20:54 node_modules/
-rw-r--r-- 1 Administratör 197121 207 Aug 27 20:54 package.json
```

I have the exact error, followed the setup guide on the official website.

**Comment by rozele** [comment]
@jackbillstrom which version of npm?

**Comment by jackbillstrom** [comment]
@rozele  Currently running NPM 3.10.7.

**Comment by jackbillstrom** [comment]
@ide @grabbou Any help? Seen the error on Stackoverflow but no answers on those questions. Will become insane without RN :(

**Comment by localhosted** [comment]
Same error in https://github.com/facebook/react-native/issues/10033

**Comment by lacker** [comment]
Hey, without being able to reproduce this I don't think we can make progress here. I think we would need more information, specifically a way to reproduce this bug consistently on a new setup. I am going to close this issue but if you do have enough information to reproduce it then feel free to open a new issue.

**Comment by rozele** [comment]
@lacker I was able to reproduce this consistently by creating a directory name with non-ASCII characters, but either way I think leaving #10154 open should cover the majority of these issues.  The babel-core change was already made, we just have to wait for a new release and take the upgrade here.
