### ISSUE TITLE
blank scene on navigator.pop() (RN 0.29.2)

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#8904]
I have an issue where I am getting a completely blank scene when I use `navigator.pop()` to go up the the only scene in the stack.

It seems to happen when a state change occurs that affects both the parent scene (the blank one) and the child scene (the one thats getting popped).

The blank scene is a ListView, and swiping it seems to force it to display correctly.

Any idea what could be causing this?

**Comment by chirag04** [comment]
see if removeClippedSubviews={false} helps.

refer: https://github.com/facebook/react-native/issues/8607 & https://github.com/facebook/react-native/issues/1831

**Comment by npomfret** [comment]
Many thanks.
