### ISSUE TITLE
Syntax Error: "errorMessage" is read-only

### ISSUE THREAD

**Issue by ueatest** [facebook/react-native#8906]
React Native: v0.29.2
OS: Mac
Error occurs on iOS when `react-native run-ios` is run on a new project after `react-native init project`.
Haven't tested on Android.

Found this being fixed in [#8347](https://github.com/facebook/react-native/pull/8347) ([0.30-rc](https://github.com/facebook/react-native/releases/tag/v0.30.0-rc.0)).

**Comment by ide** [comment]
Closing this because a fix is ready and will be going on in a future release.
