### ISSUE TITLE
scrollResponderScrollNativeHandleToKeyboard not responsive on first tap

### ISSUE THREAD

**Issue by lifehackett** [facebook/react-native#8910]
`react-native@0.28.0 iOS`

I have a login screen and would like the screen to scroll when the keyboard is visible.  On the Xcode Simulator, this works every time, including the first.  When I run the app on my iOS 6 device, either through Xcode or TestFlight, the view does not scroll on the initial tap, but does scroll on **most** subsequent taps.

I have noticed that increasing the `setTimeout` duration to 1000 mili-second gets it to work on the first tap and seemingly all subsequent taps, but obviously is not a good user experience.

From what I have found on StackOverflow and your issues threads this seems to be the most common way to solve this use case, but I don't like relying on `setTimeout` generally, especially since it seems to be the source of the problem.

Is there another/better way to solve this that doesn't rely on `setTimeout`?

```
<ScrollView
        contentContainerStyle={ styles.container }
        ref="scrollView"
        scrollEnabled={ false }
      >
<View style={ styles.loginFormContainer }>
          <View style={[ styles.inputContainer , { borderBottomColor: getBorderColor(s.isUsernameError) } ]}>
            <Text style={[ styles.inputLabel, { color: getLabelColor(s.isUsernameError) } ]}>USERNAME</Text>
            <TextInput
              autoCapitalize="none"
              autoCorrect={ false }
              autoFocus={ false }
              clearButtonMode="always"
              keyboardType="email-address"
              onChangeText={ this.onChangeUsername }
              style={[ styles.inputField, { width: inputWidth } ]}
              ref="username"
              onFocus={ this.onFocus }
              onBlur={ this.onBlur }
              returnKeyType="next"
              enablesReturnKeyAutomatically={ true }
              onSubmitEditing={ this.onSubmitUsername }
              blurOnSubmit={ false }
              value={ s.username }
            />
          </View>
          <View style={[ styles.inputContainer , { borderBottomColor: getBorderColor(s.isPasswordError) } ]}>
            <Text style={[ styles.inputLabel, { color: getLabelColor(s.isPasswordError) } ]}>PASSWORD</Text>
            <TextInput
              autoCapitalize="none"
              autoCorrect={ false }
              clearButtonMode="always"
              onChangeText={ this.onChangePassword }
              secureTextEntry={ true }
              style={[ styles.inputField, { width: inputWidth } ]}
              ref="password"
              onFocus={ this.onFocus }
              onBlur={ this.onBlur }
              returnKeyType="done"
              enablesReturnKeyAutomatically={ true }
              onSubmitEditing={ this.onLogin(s.username, s.password) }
            />
          </View>
        </View>
      </ScrollView>

    onFocus() {
        setTimeout(() => {
          let scrollResponder = this.refs.scrollView.getScrollResponder();
          scrollResponder.scrollResponderScrollNativeHandleToKeyboard(
            ReactNative.findNodeHandle(this.refs.password),
            120,
            true
          );
        }, 100);
    },
```

**Comment by chirag04** [comment]
you probably want to use keyboard events rather than using onFocus. I'm successfully using KeyboardAvoidingScrollView that autoscroll based on keyboard events. Heres my source code: https://gist.github.com/chirag04/d7a7d58f4afc9520a51f511ce7f67788

**Comment by lifehackett** [comment]
Thank you for your snippet.  This does appear to fix my issue.  I don't love the UX with this approach though as the view scrolls on a delay after the keyboard. I replaced `keyboardDidShow` with `keyboardWillShow` and it seems to work much better.  You might want to try out that change.

I find it confusing that in the source code comments for `scrollResponderScrollNativeHandleToKeyboard` it says
> This method should be used as the callback to onFocus in a TextInputs' parent view.

The on event approach seems more intuitive to me, but it seems odd to include that comment otherwise.  I certainly like removing the `setTimeout` from the code with this approach.

Thanks again @chirag04
