### ISSUE TITLE
Swift for iOS

### ISSUE THREAD

**Issue by zh-wowtv** [facebook/react-native#8912]
As we know, Swift is becoming the main language to develop iOS app. I'm wondering when will react-native will support it. I mean it will auto generate the Swift project when we run:

> react-native init myApp

**Comment by ide** [comment]
I suspect this primarily depends on when Facebook decides to start introducing Swift into the main app. Swift and the tools have been relatively unstable so that might be awhile out. cc @javache

**Comment by zh-wowtv** [comment]
@ide Actually I think Swift is quite stable already. I've had a few projects in Swift.

**Comment by javache** [comment]
The core of React Native is written in Objective-C and is not likely to change soon, we're moving more of our core to C++, which Swift has limited interoperability with.

That shouldn't stop you from writing your own native modules in Swift, you just need a small bridging header and it'll work with React Native: https://facebook.github.io/react-native/docs/native-modules-ios.html#exporting-swift
