### ISSUE TITLE
“Keystore was tampered with, or password was incorrect” when attempting to generate signed apk

### ISSUE THREAD

**Issue by MiLeung** [facebook/react-native#8913]
Version 0.29.1
Android Only

I start off by running keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 in my project directory.

Then I put my-release-key.keystore in my project's android/app directory.

Now, there isn't a ~/.gradle/gradle.properties directory like facebook says there is, but there is a gradle.properties in the android folder, so I set up my gradle variables and my gradle.properties ends up looking like this:

```
android.useDeprecatedNdk=true
MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=password123
MYAPP_RELEASE_KEY_PASSWORD=password123
```

Next, I open up android/app/build.gradle and add my gradle variables and set it for release like this:

```
...
android {
    ...
    defaultConfig { ... }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            ...
            signingConfig signingConfigs.release
        }
    }
}
...
```

And then I finally run cd android && ./gradlew assembleRelease and get the error in the title saying that my Keystore was tampered with or my password is correct.

Because I've done this cycle so many times, I'm inclined to believe that I am somehow tampering with the keystore.

**Comment by fangaofeng** [comment]
i have same problem。When i use AS build release apk，AS is ok。i try many time。

**Comment by IgorGanapolsky** [comment]
I am facing the same issue.  Using **Build -> Generate Signed APK** in android studio works, but putting the config in **build.gradle** doesn't.

**Comment by ashwin0003** [comment]
~/gradle/gradle.properties means
c:/Users/UserName/.gradle/gradle.properties (Windows)
That file isnt local to Ur project. Its available to all Ur projects which use gradle.

Works for me if I edit the above file instead of files in project.


Same steps as U. Only change being location of gradle.properties.

**Comment by MiLeung** [comment]
@IgorGanapolsky How?  What directory do you have to be in to generate the APK with Android Studio?

@ashwin0003 Could you elaborate?

**Comment by satya164** [comment]
I'm going to close this issue since this is an issue specific to React Native. Feel free to continue discussion here or move to StackOverflow.

**Comment by ashwin0003** [comment]
~/ means Ur user home directory.

For windows 7/10 its C:\Users\UserName
For Ubuntu its /home/UserName

Setting up gradle variables 
```
Place the my-release-key.keystore file under the android/app directory in your project folder.
Edit the file ~/.gradle/gradle.properties and add the following (replace ***** with the correct keystore password, alias and key password),
MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=*****
MYAPP_RELEASE_KEY_PASSWORD=*****
These are going to be global gradle variables, which we can later use in our gradle config to sign our app.


```

The first step is at Ur react native project folder.
The 2nd step is at the user home folder.

Note his explanation about global gradle variables. 1st step project folder. 2nd step global gradle installed folder.

Main point being ~/ means C:\Users\UserName\ for windows and /home/UserName/ for Ubuntu.

Example.

My folders
Windows 10.

React project e:\React\AwesomeProject
Windows drive c:

Setting up gradle properties.
1) Placed keystore file at e:\React\AwesomeProject\android\app
2) Edited c:\Users\Ashwin\.gradle\gradle.properties


U messed up the 2nd step. U edited the wrong file. U eidted e:\React\AwesomeProject\android\gradle.properties. Ur supposed to edit c:\Users\Ashwin\.gradle\gradle.properties



No probs with react-native. U didnt understand the meaning of ~/. That is a pretty basic thing to know.

**Comment by edmofro** [comment]
I was trying to build based on a project-specific gradle.properties (i.e. at projectDir/android/gradle.properties), but a global gradle.properties I had configured during a previous project was being used instead. The fix for me was to delete my global gradle.properties (i.e Users/YourName/.gradle/gradle.properties)

**Comment by Yoruba** [comment]
I have the same problem, did create multiple keystores over and over again but still the message.
'Keystore was tampered with, or password was incorrect'. The gradle.properties is located when building and is finding the correct keystore. I can list the entries of the keystore.

Version React Native: 0.46.1
OS: Win 10

`keytool -genkey -v -keystore test.keystore -alias test -keyalg RSA -keysize 2048 -validity 10000`

gradle.properties

```
MYAPP_RELEASE_STORE_FILE=test.keystore
MYAPP_RELEASE_KEY_ALIAS=test
MYAPP_RELEASE_STORE_PASSWORD=mypassword 
MYAPP_RELEASE_KEY_PASSWORD=mypassword
```

```
##\android\app>
Enter keystore password:

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 1 entry

test, Jul 10, 2017, PrivateKeyEntry,
Certificate fingerprint (SHA1): ##:##
```

**Comment by MiLeung** [comment]
After two years, I solved this by removing ~/gradle.properties

Completely forgot about posting this lol
