### ISSUE TITLE
Documentation inconsistencies in FlexBox

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#8920]
There are a couple of inconsistencies between these pages, which RN links to.

1. https://facebook.github.io/react-native/docs/layout-props.html
2. https://github.com/facebook/css-layout
3. https://css-tricks.com/almanac/properties/

* RN says that "alignItems: stretch" is default instead of "flex-start", yet the link to css-tricks says that "alignItems: stretch" is actually the default everywhere
* https://github.com/facebook/css-layout says that only flexDirection "row" and "column" are supported, whereas RN's doc says that "row-reverse" and "column-reverse" work as well.
* "align-self: stretch" seems to be the default for Flexbox as mentioned on css-ticks, yet RN seems to have a different default. This is not mentioned in the documentation.

**Comment by satya164** [comment]
> RN says that "alignItems: stretch" is default instead of "flex-start", yet the link to css-tricks says that "alignItems: stretch" is actually the default everywhere

There was a change in css-layout recently making it closer to spec. Seems our docs haven't been updated. Would be awesome if you could send a PR.

> "align-self: stretch" seems to be the default for Flexbox as mentioned on css-ticks, yet RN seems to have a different default. This is not mentioned in the documentation.

Is this still true with latest RN?

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by gmuraleekrishna** [comment]
Fixed this issue in #9397
