### ISSUE TITLE
can't find react-native-0.28.0 without appcomact in android studio

### ISSUE THREAD

**Issue by oscarthecat** [facebook/react-native#8928]
http://stackoverflow.com/questions/38481823/cant-find-react-native-package-in-external-libraries

We have two modules named app and lib. Since we have to add rn into lib, we have added lib's build.gradle with :

dependencies {
compile fileTree(include: ['*.jar'], dir: 'libs')
compile "com.facebook.react:react-native:+"  // From node_modules}
and in project's build.gradle

allprojects {
repositories {
    mavenLocal()
    jcenter()
    maven {
        // All of React Native (JS, Android binaries) is installed from npm
        url "$rootDir/../node_modules/react-native/android"
    }
}}
and node_modules has been downloaded and put in the usual folder,with package.json

"dependencies": {
"react": "15.1.0",
"react-native": "0.28.0" }
and G:\dev>react-native -v
react-native-cli: 1.0.0
react-native: 0.28.0

We event have
<orderEntry type="library" exported="" name="react-native-0.28.0" level="project" />
in the lib.iml, and can find react-native 0.28's dependencies like okhttp-3.2.0 and okio-1.8.0(never used or added before) in studio's External Libraries,

But react-native-0.28.0 never appears in studio's External Libraries and not valid for the code.

Any ideas why that happen? Thanks in advance.

update

After I put compile 'com.android.support:appcompat-v7:23.1.1' in app module's dependency react-native-0.28.0 appears... that's very strange, Is that a bug or something?

**Comment by bestander** [comment]
This seems like something Android Studio specific.
My guess - you may not have installed com.android.support:appcompat-v7:23.0.1 in your Android SDK and Android Studio hides react-native library because of errors

**Comment by lacker** [comment]
I will assume this is fixed or sufficiently-answered by Konstantin because it's been quiet for a while.
