### ISSUE TITLE
navigator.geolocation.getCurrentPosition -> Unable to fetch location within 0s

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#8931]
Using Rn 0.29.2

I'm trying to get the location on receipt of a push notification in iOS.  I have a the timeout parameter set to _1000_, but I'm getting this error message:

`{code: 3, message: "Unable to fetch location within 0s.", PERMISSION_DENIED: 1, POSITION_UNAVAILABLE: 2, TIMEOUT: 3}`

Any idea what I need to do to get this to work?

**Comment by npomfret** [comment]
The error message is just incorrect.  No matter what timeout you set it always says _0s_ apparently.  However, the timeout is being honoured by the code.  But still no gps data, it always times out.

**Comment by npomfret** [comment]
The solution is to add `NSLocationAlwaysUsageDescription` to your `Info.plist` file.

**Comment by codeNgamer** [comment]
@npomfret I've got `NSLocationAlwaysUsageDescription` in my `Info.plist` file but my submission to apple got kicked back cause of this error. Apparently, this error also occurs when connected to Ipv6 network.
