### ISSUE TITLE
ListView sticky header not working even using renderSectionHeader property for Android

### ISSUE THREAD

**Issue by kenma9123** [facebook/react-native#8937]
Hello everyone, thank you for react-native such a great technology :) Anyway, I've been testing some component lately and found a bug on ListView component on Android when rendering a list with section headers. The supposedly header to be stickied at the top of the content then get push by the next one is not working. The iOS equivalent works just fine tho.

I'm using react-native `0.29.2` on windows 7 64bit with react-native-cli `1.0.0`. With `23.0.1` android SDK.

I also put a sample App [here][2](view rnplay.org) that you can test. The version of that app is `0.24.1` tho but it seems still not working right.

According to the [docs][1]:

> renderSectionHeader function 
> 
> (sectionData, sectionID) => renderable
> 
> If provided, a sticky header is rendered for this section. The sticky
> behavior means that it will scroll with the content at the top of the
> section until it reaches the top of the screen, at which point it will
> stick to the top until it is pushed off the screen by the next section
> header.

But it seems really not working for me. Here is my full code.

    import React, { Component } from 'react';
    import {
      AppRegistry,
      StyleSheet,
      Text,
      View,
      ListView
    } from 'react-native';
    
    const styles = StyleSheet.create({
      row: {
        flex: 1,
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee'
      },
      rowText: {
        color: 'black'
      },
      subheader: {
        backgroundColor: 'rgba(0,0,0, 0.5)',
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10
      },
      subheaderText: {
        color: '#fff'
      }
    });
    
    class ListViewTest extends Component {
    
      renderListRowView(rowData) {
        const { state, label, alarm = false } = rowData;
    
        return (
          <View style={styles.row}>
            <Text style={styles.rowText}>{label}</Text>
          </View>
        );
      }
    
      renderSectionHeader(data, sectionId) {
        return (
          <View style={styles.subheader}>
            <Text style={styles.subheaderText}>{sectionId}</Text>
          </View>
        );
      }
    
      getSource() {
        return [{
          name: 'Category 1',
          todos: [{
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'checked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }]
        }, {
          name: 'Categor 2',
            todos: [{
            state: 'checked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'checked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'checked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }, {
            state: 'unchecked',
            label: 'Eat Food'
          }]
        }, {
          name: 'Category 3',
          todos: [{
            state: 'unchecked',
            label: 'Go with the flow'
          }, {
            state: 'checked',
            label: 'Go with the flow'
          }, {
            state: 'unchecked',
            label: 'Go with the flow'
          }, {
            state: 'unchecked',
            label: 'Go with the flow'
          }, {
            state: 'unchecked',
            label: 'Go with the flow'
          }]
        }];
      }
    
      renderListViewData() {
        var data = this.getSource();
        var sectionIds = [];
    
        data.map((list) => {
          sectionIds.push(list.name);
          data[list.name] = list.todos;
        });
    
        return {data, sectionIds};
      }
    
      render() {
        var ds = new ListView.DataSource({
          sectionHeaderHasChanged: (r1, r2) => r1 !== r2,
          rowHasChanged: (r1, r2) => r1 !== r2
        });
    
        var {data, sectionIds} = this.renderListViewData();
    
        let dataSource = ds.cloneWithRowsAndSections(data, sectionIds);
    
        return (
          <View style={{flex: 1}}>
            <ListView
              ref="listview"
              dataSource={dataSource}
              renderRow={this.renderListRowView}
              renderSectionHeader={this.renderSectionHeader}
              automaticallyAdjustContentInsets={false}
              scrollEnabled={true}
            />
          </View>
        );
      }
    }
    
    AppRegistry.registerComponent('ListViewTest', () => ListViewTest);

Any help would be really appreciated. Looking forward. Thank you!

  [1]: https://facebook.github.io/react-native/docs/listview.html
  [2]: https://rnplay.org/apps/TqUHtQ

**Comment by ide** [comment]
The short answer is that sticky headers aren't supported on Android.

**Comment by kenma9123** [comment]
Hmm that sad then. The docs must have at least put a tag there that it only works for ios. Just like what they did on other properties for platform specific. Any workaround for this?

**Comment by ide** [comment]
There was an issue open for this feature but no one cared enough to implement it. I'm not sure if there's a good workaround, you could try listening to the scroll events and writing the logic to manually figure out the sticky header and absolutely position it but I bet it would be janky. This needs to be implemented at the native level.

**Comment by kenma9123** [comment]
If that's the case then I think lets just ignore it. But well, hopefully this would be implemented too. And at least update the docs to avoid confusion. Thanks
