### ISSUE TITLE
Uploading large files returns error "File descriptor closed"

### ISSUE THREAD

**Issue by cubbuk** [facebook/react-native#8938]
I am trying to upload files using FormData with fetch. I can upload images and videos which are not large, but when I try to upload larger files, fetch throws error `typeError: Network request failed`. When I investigated a bit more, I see that `onreadystatechange` event returns ``readyState` 4,  `status`  0 and responseText: 'File descriptor closed'`. Here is the output:

```
{
   type:'readystatechange',
   target:{
      UNSENT:0,
      OPENED:1,
      HEADERS_RECEIVED:2,
      LOADING:3,
      DONE:4,
      readyState:4,
      responseText:'File descriptor closed',
      status:0,
      timeout:0,
      upload:{

      },
      _aborted:false,
      _hasError:true,
      _method:'POST',
      _url:'https://fakeservice/upload',
      _timedOut:false,
      _incrementalEvents:false,
      responseHeaders:undefined,
      _requestId:null,
      _cachedResponse:undefined,
      _headers:{

      },
      _responseType:'',
      _sent:true,
      _lowerCaseResponseHeaders:{

      },
      _subscriptions:[

      ]
   },
   currentTarget:{
      UNSENT:0,
      OPENED:1,
      HEADERS_RECEIVED:2,
      LOADING:3,
      DONE:4,
      readyState:4,
      responseText:'File descriptor closed',
      status:0,
      timeout:0,
      upload:{

      },
      _aborted:false,
      _hasError:true,
      _method:'POST',
      _url:'https://fakeservice/upload',
      _timedOut:false,
      _incrementalEvents:false,
      responseHeaders:undefined,
      _requestId:null,
      _cachedResponse:undefined,
      _headers:{

      },
      _responseType:'',
      _sent:true,
      _lowerCaseResponseHeaders:{

      },
      _subscriptions:[

      ]
   },
   eventPhase:2,
   bubbles:false,
   cancelable:false,
   timeStamp:1469093512802,
   isTrusted:false
}
```

 Does anyone have any idea how to solve this?

Thanks

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/uploading-large-files-returns-error-file-descriptor-closed

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
