### ISSUE TITLE
NavigatorIOS: resetTo keeps old rightButton

### ISSUE THREAD

**Issue by awiss** [facebook/react-native#894]
When I attempt to call `navigator.resetTo(new_route) `with a new route, the rightButton the old page previously had is still there. This happens whether or not I have something in `new_route.rightButtonTitle` or not.

**Comment by MandarinConLaBarba** [comment]
I also find it keeps the `title` and `rightButtonTitle`.

**Comment by Lapixx** [comment]
The same thing seems to happen (or rather, not happen) when using `navigator.replace(new_route)`.

**Comment by michalvalasek** [comment]
Same problem here (with `navigator.replace`).

**Comment by pwmckenna** [comment]
I believe this is a duplicate of https://github.com/facebook/react-native/issues/476

**Comment by brentvatne** [comment]
Indeed, same issue was #476
