### ISSUE TITLE
[Documentation] wrong link to Gesture Responder System in Handling Touches 

### ISSUE THREAD

**Issue by aimak** [facebook/react-native#8943]
Hello,

There seems to be a small issue with the last link from this page : https://facebook.github.io/react-native/docs/handling-touches.html

It should redirect to https://facebook.github.io/docs/gesturerespondersystem.html but I think that the actual page is https://facebook.github.io/react-native/docs/gesture-responder-system.html

**Comment by charpeni** [comment]
@facebook-github-bot label Documentation

**Comment by charpeni** [comment]
Thank you for reporting, fix should land soon.
