### ISSUE TITLE
Device Debug Menu

### ISSUE THREAD

**Issue by tarang9211** [facebook/react-native#8947]
Hey guys!

I am using react-native to build an app. I created a new project yesterday and ran it on my iPone 6s and I could open the developer menu by shaking the device to enable hot reloading.

Today, when I started the app via `react-native run-ios` and opened the `xcodeproject` and ran it on my phone, the developer menu had only four options. It did not have the tab for hot reloading.

If I tap the the `Debug JS Remotely` option, I receive the following error

`WebSocket connection failed with error Error Domain=NSPOSIXErrorDomain Code=61 "The operation couldn’t be completed. Connection refused"`

**Comment by haodetong** [comment]
same issues with me

**Comment by tarang9211** [comment]
What version of react-native are you running? I am using 0.30.0 and it seems fine.

**Comment by jimmyhmiller** [comment]
I get this issue only on certain wifi networks. Does anyone have any insight into how the discovery mechanism works here so I can try to debug this further?

**Comment by philipstanislaus** [comment]
Fixed it with the following entry in `./ios/App/info.plist` (Xcode 8.1, react-native 0.37.0): 

```
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>192.168.0.127</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
        <key>localhost</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>
```

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
