### ISSUE TITLE
Please reconsider restrictions in PATENTS (Additional Grant of Patent Rights Version 2)

### ISSUE THREAD

**Issue by PublicParadise** [facebook/react-native#8952]
I work for a bigger software company and our legal department has advised me to avoid using Facebook's `react-native` framework in any of our products, because of statements made in the second paragraph of Facebook's Additional Grant of Patent Rights Version 2 in react-native's [PATENTS](https://github.com/facebook/react-native/blob/master/PATENTS) file:

>The license granted hereunder will terminate, automatically and without notice,
if you (or any of your subsidiaries, corporate affiliates or agents) initiate
directly or indirectly, or take a direct financial interest in, any Patent
Assertion: (i) against Facebook or any of its subsidiaries or corporate
affiliates, (ii) against any party if such Patent Assertion arises in whole or
in part from any software, technology, product or service of Facebook or any of
its subsidiaries or corporate affiliates, or (iii) against any party relating
to the Software.

According to our legal department, the issue is that if our company initiated a patent claim or lawsuit against Facebook, then our license and right to use the framework would automatically terminate. This would apply if our company sued for any Facebook patent infringement (it’s not limited to the framework). Thus using react-native in any of our products would expose our company to risks we don't feel comfortable taking.

Please note that those concerns have also been raised by others (i.e. [Google employees](https://news.ycombinator.com/item?id=9271331)) and have unfortunately not been resolved by updating [PATENTS](https://github.com/facebook/react-native/blob/master/PATENTS) to version 2 as suggested by https://github.com/facebook/react-native/issues/402 .

Thank you for reconsidering the second paragraph of Facebook's Additional Grant of Patent Rights Version 2 in react-native's [PATENTS](https://github.com/facebook/react-native/blob/master/PATENTS) file. 

I would love to move forward and recommend choosing `react-native` for one of our future products.
At this point I cannot do that.

**Comment by tangledfruit** [comment]
@PublicParadise: Thanks for raising this. I'm in a similar situation.

**Comment by ide** [comment]
cc @jamesgpearce 

Airbnb, Apple, Netflix, Twitter, and Walmart are some examples of big companies that are OK with the license. Some of them use only React and not RN so the patents may be different but the license is the same. Last I heard at ReactConf, the licensing terms had been reworked so the wording was acceptable to Google's legal team.

N.B. I don't work at Facebook nor am I a lawyer, just telling you public info I know.

**Comment by RemeJuan** [comment]
SO you want them to change their terms so that you are legally able to file a lawsuit against them, seems silly to me and more than enough reason for them to NOT change it.

**Comment by PublicParadise** [comment]
@RemeJuan: See, I am not a lawyer either, just a dev like @ide. Now, hypothetically: what if Facebook really did commit patent infringement against the company I work for? Shouldn't my company have the right to bring this case to court without having to pull all apps from the store that use react-native? My company doesn't really want to sue anybody unless it has to. From what I understand it is very important that we have the freedom to do so without disrupting our ongoing business. 

@ide A lot of threads I found were referring to version 1 and version 2 is indeed an improvement. But I am not sure whether for example Google now permits the usage of Facebook open source code.

**Comment by jaynsw** [comment]
It should be "To use RN, all parties agree no patent war against each other"

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/please-reconsider-restrictions-in-patents-additional-grant-of-patent-rights-version-2

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by gaearon** [comment]
React Native has been relicensed as MIT.

https://github.com/facebook/react-native/commit/26684cf3adf4094eb6c405d345a75bf8c7c0bf88
