### ISSUE TITLE
Unable to align text with various sizes to the top

### ISSUE THREAD

**Issue by zevmo** [facebook/react-native#8953]
We are attempting to have the text fields, next to one another, each with varying sizes, and it seems that we can never get them to align to the top together. We've tried all the standard params & settings, but to no avail.

There seems to be a margin or padding on top and bottom that is variable by font size, so when combining various sizes next to one another, they never quite line up.

Any way to override these?

Example code (stripped down and simplified): https://rnplay.org/apps/-CsnxQ

![screen shot 2016-07-21 at 3 42 20 pm](https://cloud.githubusercontent.com/assets/2286035/17037569/9bcdd214-4f5f-11e6-8a01-6f9840438df0.png)
![screen shot 2016-07-21 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/2286035/17037814/b5a6555c-4f60-11e6-9af6-90fd5bbfb6fb.png)

**Comment by stief510** [comment]
+1

**Comment by stief510** [comment]
Is there any update on this?

**Comment by zevmo** [comment]
I'm shocked that no one else has this issue.

**Comment by zevmo** [comment]
Alone in the wilderness, I guess

**Comment by lacker** [comment]
I'm sorry for leaving you alone in the wilderness! So, I thought this is just how fonts worked - there is not necessarily a "top" to align them to. I suggest just mucking around with hard-coded constants until it looks nice. Anyway, I am going to close this issue under the theory that you have found a workaround. Good luck and thanks for bringing this up!

**Comment by zevmo** [comment]
@lacker Thanks for the response. We were unable to find a solution, so we changed the design. We haven't been able to find a way to make it work in a traditional sense. I'll continue to play around with it and update here if I come up with anything.

Best,
Z
