### ISSUE TITLE
[Packager] how does react native find ActivityIndicatorIOS when using require('ActivityIndicatorIOS')?

### ISSUE THREAD

**Issue by lzyy** [facebook/react-native#896]
for example, this is the `webView.ios.js` header

```
var ActivityIndicatorIOS = require('ActivityIndicatorIOS');
var EdgeInsetsPropType = require('EdgeInsetsPropType');
var React = require('React');
var ReactIOSViewAttributes = require('ReactIOSViewAttributes');
var StyleSheet = require('StyleSheet');
var Text = require('Text');
var View = require('View');
```

`ActivityIndicatorIOS` is in `Libraries/Components/ActivityIndicatorIOS/ActivityIndicatorIOS.ios.js`

while `EdgeInsetsPropType` is in `Libraries/StyleSheet/EdgeInsetsPropType.js`

where is the search path setting?

---

PS: in `ListView.js`, there is 

```
var React = require('React');
```

but when is `React` be installed? `package.json` doesn't contain it.

**Comment by ide** [comment]
The packager uses two methods to look up modules. The first is based on docblock headers: if you write "@providesModule X" in the first docblock this enables require('X'). The other method is Node's resolution.

To answer your question, you are seeing the first type of module resolution. Grep for @providesModule <moduleName>

**Comment by lzyy** [comment]
that's it! thanks for ur help :)

PS: which module is doing the work?

**Comment by brentvatne** [comment]
ping @ide

**Comment by ide** [comment]
@lzyy what is your question?

**Comment by lzyy** [comment]
@ide the question is I didn't find `@proviedModels ReactClass` under react-native project, so wondering where does it come from. so after dig into the system node_modules dir, finally found the definition. so find my answer.

the second question is how `@provideModeuls module` declared in comments make it a real module, it seems is the effort of `JSTransform`, it has `--use-provides-module` parameter. but when is `JSTransform` involved?

**Comment by ide** [comment]
When you run the packager and load a bundle, it scans all the files for `@providesModule` and adds them to the dependency graph: https://github.com/facebook/react-native/blob/4673dca0b0941f9f8a61970b0d0829807f26f9bc/packager/react-packager/src/DependencyResolver/haste/DependencyGraph/index.js#L448

**Comment by jeffpc1993** [comment]
But I can seem to access 
`const EdgeInsetsPropType = require('EdgeInsetsPropType ')` from a file within node modules folder. This project has react-native as it's dependency.
I instead have to specify full path like 
`const EdgeInsetsPropType = require('react-native/Libraries/StyleSheet/EdgeInsetsPropType')`

**Comment by cotyembry** [comment]
@jeffpc1993 I still can't get the require statements to work.. I used the full path. I even tried using import statements and I'm still not being able to split my project up into multiple files..

**Comment by cotyembry** [comment]
.
