### ISSUE TITLE
why must inherit from RCTViewManager

### ISSUE THREAD

**Issue by fragno** [facebook/react-native#8965]
sometimes, I want to add some feature to the native component, but I have to inherit from RCTViewManager, why can't I just inherit from RCTScrollViewManager for example?
after look into the iOS source code, the problem may be in RCTComponentData line 399.
`class_copyMethodList`，this method could not return super class methods，why is the design？

**Comment by ide** [comment]
I believe this design wasn't intentional -- just that the code wasn't written to support inheritance because it wasn't needed and the original authors may have written their code with composition instead of inheritance in mind.

**Comment by fragno** [comment]
3ks, now I get the point.
