### ISSUE TITLE
[Docs] Docs don't explain how to create an offline bundle

### ISSUE THREAD

**Issue by jefflau** [facebook/react-native#8974]
I'm looking at this link:

http://facebook.github.io/react-native/docs/running-on-device-ios.html

at: "Using the offline bundle", but the code doesn't match up to what is in my `ios/YourApp/AppDelegate.m`. It's telling me to uncomment the line `jsCodeLocation = [[NSBundle mainBundle] ..`, but that doesn't exist in my `AppDelegate.m`.

Could this be related  to the 0.29 feature for not having to change localhost to my computer's IP address to run the app on my device?

Thanks

**Comment by jlc467** [comment]
@jefflau Think you are right. The line to uncomment referenced by the docs was removed in this commit 8c29a52c54392ce52148e7d3aa9f835537453aa4 "Implemented automatic IP detection for iOS."

**Comment by MacKentoch** [comment]
It seems like a bit more information will be needed. 
For most of developers it may remain a bit unclear.

**Comment by charpeni** [comment]
@facebook-github-bot duplicate #8716
