### ISSUE TITLE
[Push Notifications] - RCTPushNotificationManager.h file not found

### ISSUE THREAD

**Issue by ademars94** [facebook/react-native#8976]
React Native v0.27

After following all of the steps listed in Issue #3831, I am still getting the file not found error for `RCTPushNotificationManager.h`

I have added `RCTPushNotificationIOS.xcodeproj` to the Libraries folder in my app, I have added `libRCTPushNotification.a` to the Link Binary With Libraries section of Build Phases, and I have added the correct path (recursive) to Header Search Paths.  I am getting the error when I try to import `RCTPushNotificationManager.h` in `AppDelegate.m`.

What is going on here?

**Comment by ademars94** [comment]
Whoops.  Turns out I didn't have the correct path in my Header Search Paths.

**Comment by redflasher** [comment]
for fast(and bad, but work) solution you cab use absolute path, such as:

`#import "<path_to_your_project>/node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.h"`
