### ISSUE TITLE
Import libraries to android "rnpm link"

### ISSUE THREAD

**Issue by akzhou** [facebook/react-native#8978]
iOS can run well,but android crash when launch.

package.json:![2016-07-23 1 08 42](https://cloud.githubusercontent.com/assets/1425193/17064987/19206188-5072-11e6-8140-e9828bec58c1.png)
launch app : ![2016-07-23 1 07 54](https://cloud.githubusercontent.com/assets/1425193/17065051/62e39a24-5072-11e6-9c9b-8f0215241e55.png)
logcat:
![2016-07-23 1 14 58](https://cloud.githubusercontent.com/assets/1425193/17065175/f51501a8-5072-11e6-8cdd-253d912f181d.png)

**Comment by satya164** [comment]
cc @Kureev any idea what's this error message?

**Comment by Kureev** [comment]
Can I see `index.js:14`?

**Comment by akzhou** [comment]
It's the react-native-cookie lib cause the problem.
https://github.com/joeferraro/react-native-cookies/issues/37

@Kureev @satya164  thanks!
