### ISSUE TITLE
RouteStack doesn't work

### ISSUE THREAD

**Issue by austinksmith** [facebook/react-native#8979]
Hi, so I'm attempting to refactor my navigator component with a static header instead of a custom one I had previously. My goal here is to be able to use methods like jumpTo and popTo instead of simply using push everywhere since that doesn't unmount some scenes I'd like unmounted to keep people from scrolling back to them.

I have the following logic.

```
   const routes = this._getRoutes();
    <Navigator 
            initialRoute={routes[0]}
            initialRouteStack={routes}
            renderScene={this._renderScene.bind(this)}
            navigationBar={this._navBar(routes)}
            configureScene={(route) => {
            if (route.sceneConfig) {
              return route.sceneConfig;
            }
            return Navigator.SceneConfigs.HorizontalSwipeJump;
          }} />
```

```
  _getRoutes() {
    return [
      {id: 'SplashView', index: 0},
      {id: 'HomeView', index: 1},
      {id: 'OtherView', index: 2},
      {id: 'RequestView', index: 3},
      {id: 'SettingsView', index: 4},
      {id: 'ProfileView', index: 5}
    ];
  };

  _navBar(routes) {
    return (
      <Navigator.NavigationBar style={main_styles.header} routeMapper={this._navigationBarRouteMapper(routes)} />
    );
  }
```

In my routeMapper i have tried the following logic..

`navigator.jumpTo(routes[1]);`
` navigator.jumpTo({id: 'HomeView', index: 1});`
` navigator.jumpTo('HomeView');`
` navigator.jumpTo(1);`

No matter what I do i always get the exact same error which is that I'm attempting to jump to a route that isn't in the route stack but I explicitly defined it to be in the route stack so how can i make use of these methods?

**Comment by holyxiaoxin** [comment]
Any idea how to get it to work? I can't seem to get jumpTo to work too

**Comment by austinksmith** [comment]
Looks like the problem is worse than it simply not working, when you define initialRouteStack in the navigator component every single route defined is mounted and then unmounted, this results in warnings in the console about calling setState on unmounted components because of the order of execution. 

```          <Navigator 
            initialRoute={routes[0]}
            initialRouteStack={routes}
            renderScene={this._renderScene.bind(this)}
            navigationBar={this._navBar(routes)}
            configureScene={(route) => {
            if (route.sceneConfig) {
              return route.sceneConfig;
            }
            return Navigator.SceneConfigs.HorizontalSwipeJump;
          }} />```

The above logic will call componentDidMount and componentWillUnmount on every single route you pass to the initialRouteStack, the navigator component will then fail to remember the route stack when attempting to use methods like jumpTo etc. as mentioned previously. It appears that routeStack functionality is simply broken in its current state and is unusable in the way described in the documentation, especially since it does not respect the componentDidMount function as it calls unmount as soon as it calls did mount leading to a race condition of setState calling after the component has become unmounted.

**Comment by austinksmith** [comment]
So the problem appears to come from the jumpTo function itself, it is checking for index of on an array of objects. As far as I know this will never check if the value within each object exists because it doesn't know how to handle transversing between each object. Ideally this would be standardized and simply checking for the id or title of each scene you pass.

#This will never work because routeStack is composed of objects that contain internal variables meaning object to object matching will never occur. As far as I know indexOf doesn't work this way at all, it will check for values within the array such as ["HomeView", "OtherView"] but it cannot transverse the objects themselves or match entire objects.

Simply test case...

var myArr = [{id: "HomeView", index: 1}];
var present = myArr.indexOf({id: "HomeView", index: 1}); 
//And now present === -1, even though we've defined exactly the same object and checked for its existence.

```
  jumpTo: function(route) {
    var destIndex = this.state.routeStack.indexOf(route);
    invariant(
      destIndex !== -1,
      'Cannot jump to route that is not in the route stack'
    );
    this._jumpN(destIndex - this.state.presentedIndex);
  },
```

This should instead have been written something similar to this.. 

```
 jumpTo: function(routeID) {
  	var destIndex = -1;
  	for (var i = this.state.routeStack.length - 1; i >= 0; i--) {
  		if(this.state.routeStack[i]['id'].indexOf(routeID) != -1) {
  			destIndex = i;
  		}
  	};
    invariant(
      destIndex !== -1,
      'Cannot jump to route that is not in the route stack'
    );
    this._jumpN(destIndex - this.state.presentedIndex);
  },
```

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/routestack-doesnt-work

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.
