### ISSUE TITLE
Signed apk not being generated

### ISSUE THREAD

**Issue by RemeJuan** [facebook/react-native#8980]
I upgraded to 0.30 this morn but now when I run './gradlew assembleRelease' I am only getting the unsigned apk instead of both the signed and unsigned one.

All my files were correctly updated post upgrade, signingConfigs is there with the correct file names, keyfile is in android/app the build process is not reporting any errors or warning.

Here is the build outpu

`
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library
:app:prepareComAndroidSupportRecyclerviewV72301Library
:app:prepareComAndroidSupportSupportV42321Library
:app:prepareComFacebookFrescoDrawee0110Library
:app:prepareComFacebookFrescoFbcore0110Library
:app:prepareComFacebookFrescoFresco0110Library
:app:prepareComFacebookFrescoImagepipeline0110Library
:app:prepareComFacebookFrescoImagepipelineBase0110Library
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library
:app:prepareComFacebookReactReactNative0300Library
:app:prepareOrgWebkitAndroidJscR174650Library
:app:prepareReleaseDependencies
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:generateReleaseBuildConfig
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources
:app:mergeReleaseResources
:app:bundleReleaseJsAndAssets
[9:00:41 PM] <START> Building Dependency Graph
[9:00:41 PM] <START> Crawling File System
[9:00:41 PM] <START> find dependencies
[9:00:48 PM] <END>   Crawling File System (7057ms)
[9:00:48 PM] <START> Building in-memory fs for JavaScript
[9:00:49 PM] <END>   Building in-memory fs for JavaScript (197ms)
[9:00:49 PM] <START> Building in-memory fs for Assets
[9:00:49 PM] <END>   Building in-memory fs for Assets (157ms)
[9:00:49 PM] <START> Building Haste Map
[9:00:49 PM] <START> Building (deprecated) Asset Map
[9:00:49 PM] <END>   Building (deprecated) Asset Map (88ms)
[9:00:49 PM] <END>   Building Haste Map (326ms)
[9:00:49 PM] <END>   Building Dependency Graph (7746ms)
[9:01:00 PM] <END>   find dependencies (18491ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: D:\Documents\Projects\cycle-culture-app-react\android\app\build\intermediates\assets\release\index.android.bundle
bundle: Copying 21 asset files
bundle: Done writing bundle output
bundle: Done copying assets
:app:processReleaseManifest
Warning: D:\Documents\Projects\cycle-culture-app-react\android\app\src\main\AndroidManifest.xml:9:5-100 Warning:
        uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:9 to remove other declarations but no other declaration present
Warning: D:\Documents\Projects\cycle-culture-app-react\android\app\src\main\AndroidManifest.xml:10:5-101 Warning:
        uses-permission#android.permission.WRITE_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:10 to remove other declarations but no other declaration present
D:\Documents\Projects\cycle-culture-app-react\android\app\src\main\AndroidManifest.xml:9:5-100 Warning:
        uses-permission#android.permission.READ_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:9 to remove other declarations but no other declaration present
D:\Documents\Projects\cycle-culture-app-react\android\app\src\main\AndroidManifest.xml:10:5-101 Warning:
        uses-permission#android.permission.WRITE_EXTERNAL_STORAGE was tagged at AndroidManifest.xml:10 to remove other declarations but no other declaration present
:app:processReleaseResources
:app:generateReleaseSources
:app:processReleaseJavaRes UP-TO-DATE
:app:compileReleaseJavaWithJavac
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources
:app:lintVitalRelease
:app:proguardRelease
:app:dexRelease
:app:packageRelease
:app:assembleRelease

BUILD SUCCESSFUL

Total time: 58.699 secs

`

**Comment by alsh76** [comment]
same issue RN v 0.29

```
./gradlew assembleRelease
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:react-native-fetch-blob:compileLint
:react-native-fetch-blob:copyReleaseLint UP-TO-DATE
:react-native-fetch-blob:preBuild UP-TO-DATE
:react-native-fetch-blob:preReleaseBuild UP-TO-DATE
:react-native-fetch-blob:checkReleaseManifest
:react-native-fetch-blob:preDebugAndroidTestBuild UP-TO-DATE
:react-native-fetch-blob:preDebugBuild UP-TO-DATE
:react-native-fetch-blob:preDebugUnitTestBuild UP-TO-DATE
:react-native-fetch-blob:preReleaseUnitTestBuild UP-TO-DATE
:react-native-fetch-blob:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-fetch-blob:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-fetch-blob:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-fetch-blob:prepareComFacebookReactReactNative0292Library UP-TO-DATE
:react-native-fetch-blob:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-fetch-blob:prepareReleaseDependencies
:react-native-fetch-blob:compileReleaseAidl UP-TO-DATE
:react-native-fetch-blob:compileReleaseRenderscript UP-TO-DATE
:react-native-fetch-blob:generateReleaseBuildConfig UP-TO-DATE
:react-native-fetch-blob:generateReleaseAssets UP-TO-DATE
:react-native-fetch-blob:mergeReleaseAssets UP-TO-DATE
:react-native-fetch-blob:generateReleaseResValues UP-TO-DATE
:react-native-fetch-blob:generateReleaseResources UP-TO-DATE
:react-native-fetch-blob:mergeReleaseResources UP-TO-DATE
:react-native-fetch-blob:processReleaseManifest UP-TO-DATE
:react-native-fetch-blob:processReleaseResources UP-TO-DATE
:react-native-fetch-blob:generateReleaseSources UP-TO-DATE
:react-native-fetch-blob:processReleaseJavaRes UP-TO-DATE
:react-native-fetch-blob:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-fetch-blob:extractReleaseAnnotations UP-TO-DATE
:react-native-fetch-blob:mergeReleaseProguardFiles UP-TO-DATE
:react-native-fetch-blob:packageReleaseJar UP-TO-DATE
:react-native-fetch-blob:compileReleaseNdk UP-TO-DATE
:react-native-fetch-blob:packageReleaseJniLibs UP-TO-DATE
:react-native-fetch-blob:packageReleaseLocalJar UP-TO-DATE
:react-native-fetch-blob:packageReleaseRenderscript UP-TO-DATE
:react-native-fetch-blob:packageReleaseResources UP-TO-DATE
:react-native-fetch-blob:bundleRelease UP-TO-DATE
:react-native-orientation:compileLint
:react-native-orientation:copyReleaseLint UP-TO-DATE
:react-native-orientation:preBuild UP-TO-DATE
:react-native-orientation:preReleaseBuild UP-TO-DATE
:react-native-orientation:checkReleaseManifest
:react-native-orientation:preDebugAndroidTestBuild UP-TO-DATE
:react-native-orientation:preDebugBuild UP-TO-DATE
:react-native-orientation:preDebugUnitTestBuild UP-TO-DATE
:react-native-orientation:preReleaseUnitTestBuild UP-TO-DATE
:react-native-orientation:prepareComAndroidSupportAppcompatV72220Library UP-TO-DATE
:react-native-orientation:prepareComAndroidSupportSupportV42220Library UP-TO-DATE
:react-native-orientation:prepareComFacebookFrescoDrawee061Library UP-TO-DATE
:react-native-orientation:prepareComFacebookFrescoFbcore061Library UP-TO-DATE
:react-native-orientation:prepareComFacebookFrescoFresco061Library UP-TO-DATE
:react-native-orientation:prepareComFacebookFrescoImagepipeline061Library UP-TO-DATE
:react-native-orientation:prepareComFacebookFrescoImagepipelineOkhttp061Library UP-TO-DATE
:react-native-orientation:prepareComFacebookReactReactNative0110Library UP-TO-DATE
:react-native-orientation:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-orientation:prepareReleaseDependencies
:react-native-orientation:compileReleaseAidl UP-TO-DATE
:react-native-orientation:compileReleaseRenderscript UP-TO-DATE
:react-native-orientation:generateReleaseBuildConfig UP-TO-DATE
:react-native-orientation:generateReleaseAssets UP-TO-DATE
:react-native-orientation:mergeReleaseAssets UP-TO-DATE
:react-native-orientation:generateReleaseResValues UP-TO-DATE
:react-native-orientation:generateReleaseResources UP-TO-DATE
:react-native-orientation:mergeReleaseResources UP-TO-DATE
:react-native-orientation:processReleaseManifest UP-TO-DATE
:react-native-orientation:processReleaseResources UP-TO-DATE
:react-native-orientation:generateReleaseSources UP-TO-DATE
:react-native-orientation:processReleaseJavaRes UP-TO-DATE
:react-native-orientation:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-orientation:extractReleaseAnnotations UP-TO-DATE
:react-native-orientation:mergeReleaseProguardFiles UP-TO-DATE
:react-native-orientation:packageReleaseJar UP-TO-DATE
:react-native-orientation:compileReleaseNdk UP-TO-DATE
:react-native-orientation:packageReleaseJniLibs UP-TO-DATE
:react-native-orientation:packageReleaseLocalJar UP-TO-DATE
:react-native-orientation:packageReleaseRenderscript UP-TO-DATE
:react-native-orientation:packageReleaseResources UP-TO-DATE
:react-native-orientation:bundleRelease UP-TO-DATE
:react-native-vector-icons:compileLint
:react-native-vector-icons:copyReleaseLint UP-TO-DATE
:react-native-vector-icons:preBuild UP-TO-DATE
:react-native-vector-icons:preReleaseBuild UP-TO-DATE
:react-native-vector-icons:checkReleaseManifest
:react-native-vector-icons:preDebugAndroidTestBuild UP-TO-DATE
:react-native-vector-icons:preDebugBuild UP-TO-DATE
:react-native-vector-icons:preDebugUnitTestBuild UP-TO-DATE
:react-native-vector-icons:preReleaseUnitTestBuild UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-vector-icons:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-vector-icons:prepareComFacebookReactReactNative0292Library UP-TO-DATE
:react-native-vector-icons:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-vector-icons:prepareReleaseDependencies
:react-native-vector-icons:compileReleaseAidl UP-TO-DATE
:react-native-vector-icons:compileReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:generateReleaseBuildConfig UP-TO-DATE
:react-native-vector-icons:generateReleaseAssets UP-TO-DATE
:react-native-vector-icons:mergeReleaseAssets UP-TO-DATE
:react-native-vector-icons:generateReleaseResValues UP-TO-DATE
:react-native-vector-icons:generateReleaseResources UP-TO-DATE
:react-native-vector-icons:mergeReleaseResources UP-TO-DATE
:react-native-vector-icons:processReleaseManifest UP-TO-DATE
:react-native-vector-icons:processReleaseResources UP-TO-DATE
:react-native-vector-icons:generateReleaseSources UP-TO-DATE
:react-native-vector-icons:processReleaseJavaRes UP-TO-DATE
:react-native-vector-icons:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-vector-icons:extractReleaseAnnotations UP-TO-DATE
:react-native-vector-icons:mergeReleaseProguardFiles UP-TO-DATE
:react-native-vector-icons:packageReleaseJar UP-TO-DATE
:react-native-vector-icons:compileReleaseNdk UP-TO-DATE
:react-native-vector-icons:packageReleaseJniLibs UP-TO-DATE
:react-native-vector-icons:packageReleaseLocalJar UP-TO-DATE
:react-native-vector-icons:packageReleaseRenderscript UP-TO-DATE
:react-native-vector-icons:packageReleaseResources UP-TO-DATE
:react-native-vector-icons:bundleRelease UP-TO-DATE
:app:prepareCityByCityReactNativeFetchBlobUnspecifiedLibrary UP-TO-DATE
:app:prepareCityByCityReactNativeOrientationUnspecifiedLibrary UP-TO-DATE
:app:prepareCityByCityReactNativeVectorIconsUnspecifiedLibrary UP-TO-DATE
:app:prepareComAirbnbAndroidReactNativeMaps071Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0292Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources
:app:bundleReleaseJsAndAssets
[1:32:11 PM] <START> Building Dependency Graph
[1:32:11 PM] <START> Crawling File System
[1:32:12 PM] <START> find dependencies
[1:32:18 PM] <END>   Crawling File System (6824ms)
[1:32:18 PM] <START> Building in-memory fs for JavaScript
[1:32:18 PM] <END>   Building in-memory fs for JavaScript (400ms)
[1:32:18 PM] <START> Building in-memory fs for Assets
[1:32:19 PM] <END>   Building in-memory fs for Assets (274ms)
[1:32:19 PM] <START> Building Haste Map
[1:32:19 PM] <START> Building (deprecated) Asset Map
[1:32:19 PM] <END>   Building (deprecated) Asset Map (134ms)
[1:32:19 PM] <END>   Building Haste Map (502ms)
[1:32:19 PM] <END>   Building Dependency Graph (8013ms)
[1:32:35 PM] <END>   find dependencies (23416ms)
bundle: start
bundle: finish
bundle: Writing bundle output to: /Users/ashishkevich/Projects/city-by-city/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output
bundle: Copying 13 asset files
bundle: Done copying assets
:app:processReleaseManifest
:app:processReleaseResources
:app:generateReleaseSources
:app:processReleaseJavaRes UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
:app:preDexRelease UP-TO-DATE
:app:dexRelease UP-TO-DATE
:app:packageRelease
:app:assembleRelease
:react-native-fetch-blob:compileReleaseSources UP-TO-DATE
:react-native-fetch-blob:assembleRelease UP-TO-DATE
:react-native-orientation:compileReleaseSources UP-TO-DATE
:react-native-orientation:assembleRelease UP-TO-DATE
:react-native-vector-icons:compileReleaseSources UP-TO-DATE
:react-native-vector-icons:assembleRelease UP-TO-DATE

BUILD SUCCESSFUL

Total time: 53.356 secs
```

**Comment by NoviceGopher** [comment]
I am on windows 10 and I am facing the same problem. Unsigned apk generated!! :(

**Comment by NoviceGopher** [comment]
hack-ish solution is to run this command on your existing apk inside `android/app` folder to get your signed apk.

`jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore appkey.keystore app-release-unsigned.apk appkeyalias`

**Comment by sibelius** [comment]
@RemeJuan did u figure it out?

Mine is generating only: app-release-unsigned.apk inside android/app/build/outputs/apk

**Comment by nemosdo** [comment]
have the same problem

**Comment by nicholasstephan** [comment]
I'm getting this issue not too with RN0.40. Got a hanging question on stackoverflow: http://stackoverflow.com/questions/41727542/react-native-doesnt-assemble-signed-android-app.

**Comment by sibelius** [comment]
my problem was that my keystore was wrong

**Comment by nicholasstephan** [comment]
I don't think it's the keystore file in `android/app`.

My `android/app/build.gradle` file has the following:

`signingConfigs {
        release {
            if (project.hasProperty('MY_RELEASE_STORE_FILE')) {
                storeFile file(MY_RELEASE_STORE_FILE)
                storePassword MY_RELEASE_STORE_PASSWORD
                keyAlias MY_RELEASE_KEY_ALIAS
                keyPassword MY_RELEASE_KEY_PASSWORD
            }
        }
}`

my `./gradle/gradle.properties` has 

`MY_RELEASE_STORE_FILE=*****.keystore
MY_RELEASE_KEY_ALIAS=*****
MY_RELEASE_STORE_PASSWORD=*****
MY_RELEASE_KEY_PASSWORD=*****` 

where the STORE_FILE is the filename of the keystore in `android/app`. 

I've used 

`keytool -list -v -keystore ****.keystore | grep "Alias name\|Creation date"`

which asks me for my password and gives me the alias, those are all right. 

Are there any other properties that need to line up with the keystore for it to work?

If it is the keystore itself that's broken somehow, how would I go about regenerating it? Is that even possible?

**Comment by nicholasstephan** [comment]
Ok. It's definitely not the keystore. I've gone through the [Generating Signed APK](https://facebook.github.io/react-native/docs/signed-apk-android.html) steps from scratch: made a new signing key, updated my gradle properties, updated the gradle config, and tried to build a release APK. 

Same result... nothing but an unsigned apk in my build outputs.

**Comment by nicoschi** [comment]
I found a solution changing buildTypes like this:
buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

**Comment by ThePaulMcBride** [comment]
Why isn't this part of the docs?!

**Comment by eskizo** [comment]
been scratching my head for an hour, @nicoschi has the solution there

THIS should be in the docs

**Comment by sdotson** [comment]
In case somebody else tries the above and it still doesn't work:

> My problem ended up being that I was that `~/.gradle/gradle.properties` isn't referring to the file in your project directory but the one in the root directory of your operating system. Once I moved the variables to that location, I was able to generate a signed apk!

**Comment by subhajitmondalglb** [comment]
Its there in docs in buildTypes release :  signingConfig signingConfigs.release
But it can be missed by any one. So there should be some special note for that.  👍

**Comment by DonaldN92** [comment]
If you have this problem 
Keystore file ... not found for signing config 'release'.

Try it:

signingConfigs {
        release {
          //if (project.hasProperty("key_tota.jks")) {
              storeFile file("key_tota.keystore")
              storePassword "@ndroid"
              keyAlias "key_tota"
              keyPassword "@ndroid"
          //}
        }
    }
