### ISSUE TITLE
Long Term Release

### ISSUE THREAD

**Issue by PaulBGD** [facebook/react-native#8990]
I've used React Native for a while, so a while ago when a client asked what app technology we should use, I said React Native. We used React Native 0.19, which at the moment has several core bugs. I'm wondering if there's any plans to support some sort of LTS release, that has bug fixes backported to it for a while after. 

Constantly updating to the latest version of React Native isn't always a very good choice, but currently it's a required choice if you run into any of these bugs.

**Comment by alexprice91** [comment]
+1 on update fatigue

**Comment by grabbou** [comment]
@PaulBGD could you please re-ask your question on the Facebook Community group where more core contributors is hanging out? We use Github issue tracker for bugs only and this explains lack of comments yet.

In regards to the release cycle itself, React Native is still in development releasing a new version every two weeks. I haven't heard of any LTS plans but there might be something being prepared at Facebook that I am unaware of. 

As I said, better to ask in the group.
