### ISSUE TITLE
Image Component Path Issue with Double quote strings

### ISSUE THREAD

**Issue by chetnadaffodil** [facebook/react-native#8993]
Path of the Image is not found when working with strings having double quotes.
However when replaced by single quotes, the image path is found.
![error](https://cloud.githubusercontent.com/assets/17562095/17083741/b24c23a6-51c6-11e6-9020-0040b298417f.png)

**Comment by jkimbo** [comment]
@chetnadaffodil can you include the relevant code snippet that is causing the issue so that I can try and reproduce?

**Comment by lacker** [comment]
Hmm this should be totally impossible. Strings with single and double quotes are handled exactly the same way by the runtime. So I guess it is just a mystery. Anyway without more information I don't think we'll be able to help debug here, so I am going to close this issue. Good luck....
