### ISSUE TITLE
Could not invoke WebSocketModule.connect

### ISSUE THREAD

**Issue by pewh** [facebook/react-native#9003]
I get an error after use socketcluster-client. I think this is related to RN WebSocketModule, not the module (https://github.com/SocketCluster/socketcluster-client/issues/55)

![0313e0c2-525c-11e6-81dd-d5f3f76e66cf](https://cloud.githubusercontent.com/assets/881358/17095280/e4abe05e-527d-11e6-9c53-fb26b947ba0b.png)

Tested on RN 0.29 Android. Use npm version 3.

**EDIT:**
I remove socketcluster-client and change it with native websocket module. I still get same error. But when I comment the code, it didn't throw an error. So I'm sure this is a bug from WebSocket.

This is how I reproduce that error:
```const ws = new WebSocket('ws://anything-host') ```

**Comment by prateekj2** [comment]
I can confirm on this problem with RN 0.20 Android

**Comment by lacker** [comment]
I think this would need more sample code to be reproducible. I'm going to close this issue but please feel free to file a new one if it is still a problem and you have a sample app to reproduce it.

**Comment by zhaixiaoou** [comment]
I have the same error  @lacker 
![image](https://cloud.githubusercontent.com/assets/9987397/20176576/671e0b48-a783-11e6-90a9-284aaf2e8626.png)

**Comment by lacker** [comment]
OK - please open a new issue including code that reproduces it like a rnplay.org link.

**Comment by zhaixiaoou** [comment]
I dont use any code about WebSocketModule.I fetch data from Android native。I  dont know why throw this error.
