### ISSUE TITLE
Add renderOverlay method in NavigatiorTransitioner component

### ISSUE THREAD

**Issue by shahen94** [facebook/react-native#9006]
NavigationAnimatedView had a renderOverlay props,
but now i can't render overlay in new NavigationTransitioner component

![screen shot 2016-07-25 at 4 43 21 pm](https://cloud.githubusercontent.com/assets/13334788/17101706/07dc83c2-5287-11e6-8297-88b137fd2b04.png)

is it possible ?

**Comment by ryankask** [comment]
Yes it's still possible but you need to modify the `render` function and render the overlay in there. 

Have a look at the `NavigationCardStack` custom component and you can see how it's done: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L131

**Comment by shahen94** [comment]
That's it!
 Thank you !
