### ISSUE TITLE
Navigator inside a View

### ISSUE THREAD

**Issue by lessthan1** [facebook/react-native#9007]
I'm using the newest react-native version (0.3) and I experience a strange error on my Android 6.0.1. When a navigator is inside a View it (navigator) does not show at all. Is there a way to fix this?

`<View><Navigator initialRoute=...........  ...../></View>` - not rendering
`<Navigator initialRoute=...........  ...../>` - rendering

**Comment by shahen94** [comment]
@lessthan1 `<View style={{ flex: 1 }}><Navigator initialRoute=........... ...../></View>`

**Comment by lessthan1** [comment]
this works!!! Thx for the quick reply dude.
