### ISSUE TITLE
[CocoaPods] Podspec doesn't set up header search paths for <CSSLayout> imports

### ISSUE THREAD

**Issue by ide** [facebook/react-native#9014]
RN includes CSSLayout files using angle brackets like `#import <CSSLayout/CSSLayout.h>`, which don't work with CocoaPods right now since CP flattens the headers by default. We either need to figure out how to preserve the directory hierarchy just for `React/CSSLayout` or preserve the entire directory hierarchy and set up the header search path to be recursive I think.

**Comment by Gladkov-Art** [comment]
It seems that I have similar issue related to importing CSSLayout. 
I can't build `React` pod. Compiling of `CSSNodeList.c` fails with `fatal error: 'CSSLayout/CSSLayout.h' file not found`.
Probably my setup will be useful:
**package.json:**
```
{
  "name": "Chat",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "~15.2.1",
    "react-native": "~0.31.0",
    "react-native-gifted-chat": "0.0.3"
  }
}
```
**podfile:**
```
target 'Chat' do
   use_frameworks!

   pod 'React', :path => './node_modules/react-native', :subspecs => [
    'CSSLayout',
    'Core',
    'RCTText',
    'RCTWebSocket',
    'RCTImage',
  ]
end
```
I have latest stable version of XCode (7.3.1), cocoapods v1.0.1 and new swift project. 
I've tried to delete `Pods/`, `node_modules/`, `Podfile.lock` and install everything again.

**Comment by cknitt** [comment]
Same problem here. Downgrading to 0.30 worked for me, too.

**Comment by guysegal** [comment]
Same here .We have react native project with Swift and the error started to occur on 0.31.
We also downgraded to 0.30 and it solved it..

**Comment by moosch** [comment]
+1 I did the same as @guysegal and it's fine

**Comment by rh389** [comment]
This looks to be down to a Cocoapods/Xcode bug, but I haven't found a clean solution yet - https://github.com/CocoaPods/CocoaPods/issues/4605

**Comment by sdcooke** [comment]
It's not clean but we've worked around this using an npm postinstall script that rewrites imports: `replace(/#(include|import) <CSSLayout\/([A-Za-z]+)\.h>/, '#$1 "$2.h"');` (`#import <CSSLayout/CSSlayout.h>` becomes `#import "CSSLayout.h"`)

Definitely not clean or ideal and may or may not work depending on how you're using React in your codebase. Thought I'd post here just in case it helps anyone else.

**Comment by guysegal** [comment]
Seems like its a blocker for a lot of projects to upgrade to 0.31..

**Comment by senpng** [comment]
I do not know if this is not the best solution, but the problem can be solved by this, modify `React.podspec`, and `pod install`.

`React.podspec` in `node_modules/react-native/`

```
react_path = __dir__
  
s.subspec 'Core' do |ss|
    ss.dependency            'React/CSSLayout'
    ss.source_files        = "React/**/*.{c,h,m,mm,S}"
    ss.exclude_files       = "**/__tests__/*", "IntegrationTests/*", "React/CSSLayout/*"
    ss.frameworks          = "JavaScriptCore"
    ss.libraries           = "stdc++"
    ss.pod_target_xcconfig = { "CLANG_CXX_LANGUAGE_STANDARD" => "c++14", "HEADER_SEARCH_PATHS" => react_path + "/React" }
  end
```

**Comment by rh389** [comment]
After doing some digging I think @sdcooke's solution is the right one, so I've submitted a PR to get it changed at source.

In the mean time, I'm using `"postinstall": "find ./node_modules/react-native \\( -name *.h -o -name *.m \\) -print0 | xargs -0 sed -i '' -e 's:<CSSLayout/\\(.*\\)>:\"\\1\":g'"`

**Comment by senpng** [comment]
In Swift Project.
Try `"postinstall": "find ./node_modules/react-native \\( -name *.h -o -name *.m \\) -print0 | xargs -0 sed -i '' -e 's:<CSSLayout/\\(.*\\)>:\"\\1\":g'"`
And build error，
<img width="800" alt="qq20160901-0" src="https://cloud.githubusercontent.com/assets/7333114/18158241/9befd452-7054-11e6-9601-9d296fd3cfdf.png">

**Comment by senpng** [comment]
I tried to solve this problem。
I was such a modification:
**package.json**
```json
{
  "name": "xxxxxxx",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "bundle": "react-native bundle --platform ios --entry-file index.ios.js --bundle-output bundle/main.ios.jsbundle --assets-dest bundle/ --dev false",
    "postinstall": "find ./node_modules/react-native \\( -name *.h -o -name *.m \\) -print0 | xargs -0 sed -i '' -e 's:<CSSLayout/\\(.*\\)>:\"\\1\":g'"
  },
  "author": "senpng@qq.com",
  "license": "ISC",
  "dependencies": {
    "react": "^15.3.0",
    "react-native": "^0.32.0",
    "react-native-fs": "^2.0.1-rc.2"
  }
}
```
**the most important is** `"postinstall": "find ./node_modules/react-native \\( -name *.h -o -name *.m \\) -print0 | xargs -0 sed -i '' -e 's:<CSSLayout/\\(.*\\)>:\"\\1\":g'"` (thinks @rh389 )

Edit `node_modules/react-native/React.podspec` File:
**line 46**
```podspec
 s.subspec 'CSSLayout' do |ss|
    ss.source_files        = "React/CSSLayout/**/*.{c,h}"
    ss.header_mappings_dir = "React"
  end
```
_changed to_
```podspec
 s.subspec 'CSSLayout' do |ss|
    ss.source_files        = "React/CSSLayout/**/*.{c,h}"
  end
```
Before `pod install`

**Comment by rh389** [comment]
Good find - that seems to be because CocoaPods will usually copy all headers to the same directory, but specifying `React` as a `header_mappings_dir` overrides that behaviour to preserve all paths under `React`, so has quite a wide impact (@alloy may have more insight). https://github.com/facebook/react-native/pull/9544 works too by removing the subspec completely, and I guess adding a recursive user header search path would also work (you could do that from your own Podfile or as a workspace setting).

**Comment by alloy** [comment]
#9544 is definitely the good long-term solution, in the interim there are many stopgap solutions. Yours work, as would @rh389’s:

> I guess adding a recursive user header search path would also work (you could do that from your own Podfile

Which can be done with a `post_install` hook https://guides.cocoapods.org/syntax/podfile.html#post_install.

**Comment by hitbear518** [comment]
can anyone tell me how should i add a recursive user header search path for workaround before pr merged?
