### ISSUE TITLE
[ListView] Example CameraRollView in UIExplorer crashes

### ISSUE THREAD

**Issue by subpublicanders** [facebook/react-native#902]
When opening up the CameraRollView and scrolling the images, the app crashes on my device (iphone 6) each time. I've tried both on iOS 8.2 and 8.3.

Gives nothing more then 
2015-04-17 14:57:53.446 UIExplorer[327:29846] Connection to assetsd was interrupted or assetsd died
2015-04-17 14:57:55.035 UIExplorer[327:29496] Received memory warning.

**Comment by kamilkp** [comment]
Same problem

**Comment by Fanghao** [comment]
I think it's their scrollView/ListView problem. Loads all the content and triggers the memory issue.

It is basically equivalent to https://github.com/facebook/react-native/issues/499

**Comment by browniefed** [comment]
I believe this issue has been solved with latest PRs #1704 
Although it sits unmerged. Based on the issues it appears this was due to loading the wrong size of thumbnails, which has been fixed facebook side and (possibly?) synced over already.
@brentvatne already solved
