### ISSUE TITLE
[Android] Can't include a ReactRootView inside a native ScrollView

### ISSUE THREAD

**Issue by ncuillery** [facebook/react-native#9022]
I'm trying to refactor an existing app by incrementally replacing content with RN views. I face an exception when I include a ReactRootView inside a native ScrollView: 

```

java.lang.IllegalStateException: The root catalyst view must have a width and height given to
it by it's parent view. You can do this by specifying MATCH_PARENT or explicit width and 
height in the layout.`.
```

As the parent view is a ScrollView, the ReactRootView gets the height measurement `UNSPECIFIED` and the exception is explicitly thrown here:
https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java#L82-L86

This block exists from the day one of the Android release and there is no information about the reason of this restriction. Why is it here ? Will it be removed in the future ? Is there a workaround  ? (I should specified I can't refactor the native ScrollView into a RN ScrollView due to legacy reasons, the ScrollView is the app's central element of navigation, coming with overscroll, animations, etc.)

To reproduce the problem, just checkout my [repo](https://github.com/ncuillery/RnWithinScrollView) and run with Android Studio. It's just the Android Studio ScrollView example where I have included the ReactRootView following the official integration guide. Significant lines of code are [here](https://github.com/ncuillery/RnWithinScrollView/blob/master/app/src/main/java/com/cuillery/nicolas/rnwithinscrollview/ScrollingActivity.java#L55-L60).

**Comment by mkonicek** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-cant-include-a-reactrootview-inside-a-native-scrollview

Product Pains has been very useful in highlighting the top bugs and feature requests:
https://productpains.com/product/react-native?tab=top

Also, if this issue is a bug, **please consider sending a pull request with a fix**.

**Comment by iFarSeer** [comment]
I add ReactRootView inside a native ScrollView, 
layoutparams.width is match_parent, and layoutparams.height is wrap_content.
in the method onMeasure, width is right, but height always is zero.

Do you fix it?

**Comment by lilong9898** [comment]
same problem. Extend ReactViewGroup class, in the subclass override onMeasure method, get rid of the assertion. just a workaround.

**Comment by hslls** [comment]
@iFarSeer 有找到解决方案吗？

**Comment by iFarSeer** [comment]
@hslls 没有找到解决方案，只能说现在ReactRootView和Native view结合的场景，RN的支持不到位，或者RN团队的工作重点不在这里。
