### ISSUE TITLE
[ActivityIndicator][Android] Indicator stays hidden if initialized as animating={false}

### ISSUE THREAD

**Issue by kulmajaba** [facebook/react-native#9023]
Originally discovered on http://stackoverflow.com/questions/38579665/reactnative-activityindicator-not-showing-when-animating-property-initiate-false

If `ActivityIndicator` is initialized with `animating={false}`, the Indicator will stay hidden even when changing `animating` to `true`. When initialized as animating the changes behave as expected.

Tested on Android emulator and Device, running Android 6.0 and 6.0.1. Also tested on iOS device which works as expected. Testing done with Windows 8.1.

```
'use strict'

import React, { Component } from 'react';
import {
    AppRegistry,
    Text,
    View,
    TouchableHighlight,
    ActivityIndicator
} from 'react-native';

class SampleApp extends Component {
    constructor() {
        super();

    this.state = {
            show: false
        };
    }

    render() {
        return (
            <View>
                <TouchableHighlight onPress={ () => this.setState({show: false}) } >
                    <Text>HIDE</Text>
                </TouchableHighlight>

                <TouchableHighlight onPress={ () => {this.setState({show: true}) } >
                    <Text>SHOW</Text>
                </TouchableHighlight>

                <ActivityIndicator animating={this.state.show} size="large"/>
            </View>
        );
    }
}

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

**Comment by alannesta** [comment]
got the same issue on Android. Seems to be a bug with the `animated` property. Currently using the workaround of either rendering the ActivityIndicator or completely hide it based on the state

**Comment by kulmajaba** [comment]
@alannesta Using React Native 0.30. I've used the same workaround, rendering a separate loading view when needed.

**Comment by antoinerousseau** [comment]
I have the opposite bug: it sometimes freezes instead of hiding

**Comment by esutton** [comment]
Same issue on React Native 0.32.

ActivityIndicator did not work so I went back to AndroidProgressBar which had yellow box warning under 0.32 for manually calling a React.PropTypes validation function.

Work-around was to use null when not animating should be false

```
                  let spinner = (this.state.working) ? (
                    <ActivityIndicator
                    animating={true}
                    size="small"
                    />
                  ) : (
                      null
                  );
```

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/activityindicatorandroid-indicator-stays-hidden-if-initialized-as-animatingfalse

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by prithsharma** [comment]
Is this fixed? Is there any workaround?
The productpains post doesn't have any updates.

**Comment by fcpauldiaz** [comment]
I'm still having this error on RN 0.40

**Comment by raphkr** [comment]
The simplest I did was 

<ActivityIndicator
   animating={true}
   style = {{ opacity : this.state.animate ? 1 : 0 }}
/>

**Comment by Brian-Kaplan** [comment]
@raphkr i don't like that at all... Then it's always animating... not the best

**Comment by sryze** [comment]
I'm seeing this bug on Android too (Android 7.1 emulator). The `opacity: 0` solution from this post worked for me:

http://stackoverflow.com/questions/38579665/reactnative-activityindicator-not-showing-when-animating-property-initiate-false

**Comment by mirzavu** [comment]
This one is simple and background is not clickable when loading:

```
{ this.state.loading &&
     <View style={styles.loading}>
          <ActivityIndicator
                 animating = {true}
                 color = '#bc2b78'
                 size = "large"/>
     </View>
}
```

and in styles
```
loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF88'
  }
```

**Comment by Dror-Bar** [comment]
Can confirm this is still happening in Android RN: 0.51.0.
I'm using a conditional JSX expression as a workaround but strange this hasn't been fixed yet.

**Comment by alexsmartens** [comment]
+1 I have the same problem

**Comment by charpeni** [comment]
Let's reopen it then.

**Comment by changulpaye** [comment]
Did anyone find the solution? I am also stuck at the same problem.

**Comment by fcpauldiaz** [comment]
@changulpaye 
```jsx
<ActivityIndicator
   animating={true}
   style = {{ opacity : this.state.animate ? 1 : 0 }}
/>
```

**Comment by ocarreterom** [comment]
This is still happening in 0.54.4.

**Comment by djhr** [comment]
same here...

**Comment by yagoazedias** [comment]
Same here... using version 0.55.2

**Comment by alexsmartens** [comment]
It's definitely a problem, however solution proposed by @esutton worked out for me

**Comment by MardariG** [comment]
In 0.55.4 also happening

**Comment by TingAli** [comment]
This is still an issue to this day :(

**Comment by Bradzer** [comment]
Is there any way to work around that bug ?

**Comment by ocarreterom** [comment]
@Bradzer https://github.com/facebook/react-native/issues/9023#issuecomment-281440940

**Comment by ernanirst** [comment]
Still running into this on react-native `0.58.3`

**Comment by NomanGul** [comment]
Same Problem here... By the way, I'm using redux-saga middleware

**Comment by lucasmotta** [comment]
Just ran with this issue on react-native `0.59.0` too. My solution was to pass a `key` prop to the ActivityIndicator to trigger a re-render:

```js
return <ActivityIndicator animating={loading} key={loading ? 'loading' : 'not-loading'} />
```

**Comment by nhunzaker** [comment]
I took a layout snapshot of the example provided above, and it looks like the container for the progress indicator is displaying, but the actual indicator itself has width/height of 0:

![image](https://user-images.githubusercontent.com/590904/59954333-f91cbb80-9438-11e9-9a8e-dfd8b8526430.png)

For some reason the indicator's width/height isn't getting updated.

**Comment by nhunzaker** [comment]
I think I might have a fix for this here: https://github.com/facebook/react-native/pull/25354

Seems too trivial. Curious what others have to say.

**Comment by grantespo** [comment]
I have the latest version of RN, still getting this issue.

**Comment by borislemke** [comment]
Still getting this issue with RN 0.61.4
