### ISSUE TITLE
Can't inspect components in `Modal`

### ISSUE THREAD

**Issue by shahen94** [facebook/react-native#9025]
It's impossible to inspect Components in Modal View

**Comment by scarlac** [comment]
Seeing the same issue here, on iOS.

I'd like to add that the inspector can be activated and works fine, but once a modal opens, the content within it will not be affected by the inspectors state, ie. pressing on components will not actually inspect anything, it'll activate the pressed item normally. Once the modal is closed, the underlying components are revealed, including the inspector "window" and it works as usual.

**Comment by stereodenis** [comment]
https://github.com/facebook/react-native/pull/9600

**Comment by shahen94** [comment]
Seems like it's fixed.
I'm going to close this issue
