### ISSUE TITLE
AppState addEventListener && removeEventListener #fail RNv0.27

### ISSUE THREAD

**Issue by eladgel** [facebook/react-native#9026]
When using Appstate.addEventListener('change', this._someFunction);
on componentDidMount and then AppState.removeEventListener('change', this._someFunction);
All is working fine!

however when I add .bind(this) to my function all hell breaks loose
====>  Appstate.addEventListener('change', this._someFunction.bind(this));
====> when calling AppState.removeEventListener('change', this._someFunction.bind(this));
The listener is not removed... please advise, Im sure this is related to the binding

**Comment by ide** [comment]
You need to pass the same function instance in. When you call bind() it creates a new instance.

**Comment by puzpuz** [comment]
have the same problem, what if I need reference to 'this.props' inside of '_someFunction' ?

**Comment by paulief** [comment]
+1, is it not possible to reference `this` in your callback method? @ide

**Comment by paulief** [comment]
never mind, figured out the solution with the help of:
https://gist.github.com/Restuta/e400a555ba24daa396cc

@puzpuz
