### ISSUE TITLE
[0.31] Commits to cherry pick into stable release

### ISSUE THREAD

**Issue by ide** [facebook/react-native#9029]
- [x] #9015 [CocoaPods] Create a CSSLayout subspec that preserves the header directories 
- [x] 857d2b8eae901a0a88be8b2a37b660b01e3ff8ff - change lineBreakMode to ellipsizeMode

**Comment by AndrewJack** [comment]
https://github.com/facebook/react-native/commit/ffb690f072aa7dccb2d21f7b6902f6818abb534d

**Comment by marcshilling** [comment]
Make getCurrentActivity() public on ReactContext - https://github.com/facebook/react-native/commit/760656461197605ee26769ed73989f78e4753038

**Comment by grabbou** [comment]
@marcshilling I was just going to add that one automatically. Been requested a lot, in fact I've just answered SO question where people were asking about that particular thing.

**Comment by marcshilling** [comment]
@grabbou sweet! Yeah, it's been a breaking change in one of our apps and I've been unable to upgrade past `0.28` so I'm excited for it to land!

**Comment by grabbou** [comment]
e8b508144fdcdea436cf4d80d99daec757505c70

**Comment by grabbou** [comment]
To rc.2 / stable:
- e7b85bd7fab0c0ed35cd1539fecbf1afaa0e0360

**Comment by grabbou** [comment]
To stable / rc2:

https://github.com/facebook/react-native/commit/8ad748ac7d6c27e3d89706a5542e62fd088ba8d2

**Comment by AndrewJack** [comment]
--reset-cache no longer accept a boolean parameter. - https://github.com/facebook/react-native/commit/b21c8f16146d928baff897a8d01bdefdf808250f
