### ISSUE TITLE
AnimationExperimental positionX/Y

### ISSUE THREAD

**Issue by finalquest** [facebook/react-native#903]
Hi.
I know that the whole animation library is very experimental. As is state in the Class name.
But I'm trying to use it to do a simple translation animation and I've been facing some issues.
I have a whole screen view which I want to move over the Y axis offscreen by 80px.
When I used -80 as the toValue, the screen was moved out of the screen almost completly.
Debuggin the RCTAnimationExperimentalManager I see that the starting point of the view is 281 instead of 0.
I dont know if I'm setting some wrong style or flex layout, or if this is inteded.

Regards.

**Comment by brentvatne** [comment]
Hi @finalquest - I've tried to use this library myself and ran into a bunch of issues with how it determined start and end values. I'd recommend using [react-tween-state](https://github.com/chenglou/react-tween-state) for now, you can see [react-native-modal](https://github.com/brentvatne/react-native-modal) for an example of how I have used it. My current understanding of the animation module is that going to be replaced entirely, so I wouldn't use it unless I had to. Let me know if your issue persists with react-tween-state and I will reopen this issue!
