### ISSUE TITLE
setTimeout is broken

### ISSUE THREAD

**Issue by bradennapier** [facebook/react-native#9030]
Not really sure here but somethign is fishy.. I am running on device via debug mode.

``` 
componentDidMount()` {
    console.log('Modal Mounts!')
    setTimeout(() => {
      console.log('Open')
      this.props.openModal()
    }, 10000)


  }
```

This will always fire instantly... about 100 ms 

``` 
componentDidMount() {
    console.log('Modal Mounts!')
    setTimeout(() => {
      console.log('Open')
      this.props.openModal()
    }, 30000)


  }
```

Fires instantly as well

``` 
componentDidMount() {
    console.log('Modal Mounts!')
    setTimeout(() => {
      console.log('Open')
      this.props.openModal()
    }, 80000)


  }
```

Fires after about 30 seconds

**Comment by bradennapier** [comment]
To further illustrate this problem...

```
console.log('In Modal')
setTimeout(() => console.log('Five Seconds'), 5000)
```

![image](https://cloud.githubusercontent.com/assets/15365418/17151609/1745916c-5329-11e6-913b-be47de14d400.png)

**Comment by mangogogos** [comment]
Check that your device/simulator's time matches that of your computer!

**Comment by matto1990** [comment]
There is already an issue open for this. There doesn't seem to be any fix on the way however.

https://github.com/facebook/react-native/issues/4470

**Comment by lacker** [comment]
Looks like this is now fixed as discussed in https://github.com/facebook/react-native/issues/9436 .

**Comment by kkusanagi** [comment]
got problem with 0.49.5 version. 

setTimeout(() => console.log('Five Seconds'), 5000) // NOT WORKING

setTimeout(() => console.log('ZERO Seconds'), 0) // WORKING

**Comment by JanithaR** [comment]
@mangogogos Is correct. I had the problem of time drifting more than 60s and I corrected it but still there was a few seconds difference between the emulator and the system. Hilariously by the time I read his comment and looked back at the emulator I realized my code had actually executed after the delay.
