### ISSUE TITLE
[iOS] Multiple request handler error when uploading a photo from assets-library

### ISSUE THREAD

**Issue by halilb** [facebook/react-native#9031]
I'm getting the following error when I try uploading a photo from asset-library.

> The RCTURLRequestHandlers RCTImageLoader and RCTAssetsLibraryRequestHandler both reported that they can handle the request { URL: assets-library://asset/asset.JPG?id=9F983&ext=JPG}, and have equal priority (0). This could result in non-deterministic behavior.

You can reproduce the problem by opening **XMLHttpRequest** example from **UIExplorer** project and simply tapping on **Upload** button.

I tracked down the problem and it seems it's introduced with commit 98f06c8.

**Comment by nathanajah** [comment]
Thanks for reporting! I'll fix it.

**Comment by alexanderjarvis** [comment]
@nathanajah the introduction of this https://github.com/facebook/react-native/commit/98f06c88764d505ef0514d8b6a1d514c2768ea5e#diff-6c79938e43c7e10abca60323d26f1935 disables the ability to upload video using an asset-library url

**Comment by jslz** [comment]
hi, We seem to be seeing it with react-native version 0.44.0. It is rare and nondeterministic so hard to have a repro case.
![image](https://user-images.githubusercontent.com/27701565/26956204-e8f580be-4c70-11e7-89bd-55f8522bb99c.png)

**Comment by arjunkathuria** [comment]
^ +1, any fixes ?
