### ISSUE TITLE
Upgrading to 0.30.0 Unhandled JS Exception: this._nativeModule.addListener is not a function. (In this._nativeModule.addListener )

### ISSUE THREAD

**Issue by mebinum** [facebook/react-native#9036]
![Error Issue](https://cloud.githubusercontent.com/assets/231835/17166789/737fdfa2-541c-11e6-8928-4a8f6de42a04.png)

Trying to upgrade from  react@0.14.8 and  react-native@0.25.1 to 0.30.0 and I'm getting the following error above for iOS

I've tried the suggestions in #8025 #7679 , also tried clean and rebuilding the project in xcode, deleting the `node_modules` folder and reinstalling but not luck. 

The application is for iOS running on a Mac v10.11.5  any help with this would be much appreciated

my package.json contains the following libraries

```
                  "dependencies": {
                      "react": "^15.2.0",
                      "react-native": "^0.30.0",
                      "react-native-google-signin": "^0.6.1",
                      "react-native-swipeout": "^2.0.12",
                      "react-redux": "^4.4.5",
                      "redux": "^3.5.2",
                      "redux-actions": "^0.10.0",
                      "redux-logger": "^2.6.1",
                      "redux-persist": "^3.1.1",
                      "redux-promise-middleware": "^3.3.2",
                      "redux-thunk": "^2.1.0",
                      "seed-react-native": "^1.0.21"
            },
                "devDependencies": {
                      "babel-eslint": "^6.1.0",
                      "eslint": "^3.0.1",
                      "eslint-plugin-flowtype": "^2.3.0",
                      "eslint-plugin-react": "^5.2.2",
                      "remote-redux-devtools": "^0.3.3"
                    }`
```

**Comment by sgwilym** [comment]
This has become a pretty pressing issue for me, with none of the old staples working: nuking `node_modules`, `pods`, clearing watchman, and cleaning Xcode.

**Comment by sgwilym** [comment]
Fixed this issue with that old chestnut: clearing XCode’s DerivedData. 🙄

**Comment by oillamp** [comment]
@sgwilym thanks a lot, clear DerivedData, it does work.

**Comment by zo-chu** [comment]
Hey, have the same issue on 0.31.0 version. Clearing DerivedData ,  node_modules,  etc , didn't work,  does anyone have any idea what else I can do?

**Comment by krillov** [comment]
@zo-chu I have the same problem. Have you found a solution maybe?

**Comment by zo-chu** [comment]
@krillov nope. Still bothers me, tried to reinstall this component again but no luck :/

**Comment by krillov** [comment]
@zo-chu Ok. I downgraded to 0.30 again just to test it and it works fine.

**Comment by oillamp** [comment]
@zo-chu after npm install , and before pod install, try to close xcode and simulator

**Comment by zo-chu** [comment]
@oillamp  nope, unfortunately no luck.  It seems like it can't see this module and that's it.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/upgrading-to-0300-unhandled-js-exception-thisnativemoduleaddlistener-is-not-a-function-in-thisnativemoduleaddlistener-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
