### ISSUE TITLE
Background color visible through the border of a border radius

### ISSUE THREAD

**Issue by frostney** [facebook/react-native#904]
When a `<View />` component uses `backgroundColor` and `borderRadius`, the background color is still visible over the edges of the border.

Screenshot:
![reactnative-borderradiusbug](https://cloud.githubusercontent.com/assets/554648/7204116/06aeb4f0-e520-11e4-9361-9f97e78f441b.png)

Example code:
```javascript
var MyComponent = React.createClass({
  render() {
    return <View style={styles.example} />
  }
});

var styles = StyleSheet.create({
  example: {
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'black'
  }
});
```

**Comment by brentvatne** [comment]
Hi there! Try setting `overflow: hidden`, does that fix it?

**Comment by brentvatne** [comment]
@vjeux - was it intentional that this require specifying an overflow? I can imagine that this could be related to performance

**Comment by brentvatne** [comment]
@vjeux - scratch that, I can't reproduce this with the above code.

@frostney - does this still occur on 0.4.0 for you?

**Comment by frostney** [comment]
`overflow: hidden` does fix it for me. Thank you.
I hope it's ok that I'm closing this issue.

**Comment by brentvatne** [comment]
@frostney - no problem, glad it helped! :smile:

**Comment by ms88privat** [comment]
overflow: 'hidden' does fix it for me too. 

Thats not the expected css behaviour. Maybe we should write it in the docs. 

Greetings

**Comment by nicklockwood** [comment]
I believe this now works correctly.

**Comment by MITDelian** [comment]
I still have this issue but only with absolutely positioned views. The overflow: 'hidden' works for me as well.

**Comment by BGuven** [comment]
It is still an issue but overflow: 'hidden' works. Thanks.

**Comment by uandco** [comment]
The issue with overflow is you can't use shadows anymore as they are considered as overflowing elements.

**Comment by anceque** [comment]
as @uandco mentioned, the overflow cannot be used together with shadow properties.. What is the workaround here?
