### ISSUE TITLE
ReactImageView.java's maybeUpdateView method exception

### ISSUE THREAD

**Issue by iceskyblue** [facebook/react-native#9040]
some times the the maybeUpdateView method returned from 
boolean usePostprocessorScaling =
mScaleType != ScalingUtils.ScaleType.CENTER_CROP&&
mScaleType != ScalingUtils.ScaleType.FOCUS_CROP

it's so strange!!!

**Comment by lacker** [comment]
I think this issue is missing sufficient information, so I am going to close it.
