### ISSUE TITLE
[iOS]How to deal with two RCTRootView with the same module name?

### ISSUE THREAD

**Issue by NSKevin** [facebook/react-native#9047]
If I have two RCTRootView with the same module name, how do I deal with it? For example, I'm using the `RCTRootView1` now, but I receive a remote push. Then I click the push , the `RCTRootView2` will be created and pushed, but with the same module name.When I come back to the `RCTRootView1`'s viewController,all click event not working.

**Comment by sauceypan** [comment]
Did you end up finding a solution to this?

**Comment by Lessica** [comment]
I am facing the same issue...
