### ISSUE TITLE
fetch in react-native not working on ios

### ISSUE THREAD

**Issue by alirezavalizade** [facebook/react-native#9051]
Im fresh in React-native im want fetch data from a server...this is my code :

```
componentDidMount = ()=> {
        this.handleRequest();
    };
    handleRequest = ()=> {
        fetch("http://********.ir/product/")
            .then((response) => {
                console.log(response);
                return response.json();
            })
            .then((res)=> {

                console.log(res);
                this.setState({data: res});

            })
            .catch((reason) => {
                console.log(reason);
                this.setState({faildLoad: true});
                AlertIOS.alert(
                    "reason",
                    "Response Body -> " + JSON.stringify(reason)
                )
            })
            .done();
    };
```

and this is error log :

```
{ [TypeError: Network request failed]
  line: 24473,
  column: 21,
  sourceURL: 'http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
```

I dont have any allow cross origin problem because im testing this api whit ajax in my website...what is the problem? i see very examples and cant find any deference between them...Tnx

**Comment by dominhhai** [comment]
For simulator: check this thread https://github.com/facebook/react-native/issues/4415
For device: check this [doc](https://facebook.github.io/react-native/docs/running-on-device-ios.html#app-transport-security)

**Comment by alirezavalizade** [comment]
I find my problem please see this [Allow Arbitrary Loads](http://stackoverflow.com/questions/38587451/image-source-uris-with-https-ssl-work-http-do-not-work-react-native-v0-30-0/38587838?noredirect=1#comment64565216_38587838)
