### ISSUE TITLE
Flow error in NavigationError/NavigationHeaderTitle

### ISSUE THREAD

**Issue by flegall** [facebook/react-native#9058]
Hi,

I'm encountering this flow error below since we upgraded React Native from 0.27 to 0.29.
I've tried reproducing it in a separate project, but I really can't reproduce it outside of our project.
I'm not sure if it's a Flow bug or a RN one.
Ignoring the directory in flow makes flow throw "Required module not found" errors.

We are using the same .flowconfig as react-native v0.29.0.
We are using react-native 0.29.0 & flow 0.27.0

Regards,

```
~/code/fluo/diagnosis /master $ npm run flow

> diagnosis@1.0.0 flow /Users/flegall/code/fluo/diagnosis
> flow --color always

Launching Flow server for /Users/flegall/code/fluo/diagnosis
Spawned flow server (child pid=7020)
Logs will go to /private/tmp/flow/zSUserszSflegallzScodezSfluozSdiagnosis.log
mobile/node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/NavigationHeaderTitle.js:52
 52: // $FlowIssue(>=0.26.0) #11432532
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression


Found 1 error

```

**Comment by satya164** [comment]
Send a PR to fix it please :)

**Comment by ide** [comment]
You might need to update your .flowconfig to ignore $FlowIssue pragmas. See RN's .flowconfig for an example.

**Comment by satya164** [comment]
@ide The examples which use `NavigationHeader` don't have Flow enabled. May be that's why we aren't catching Flow errors in `NavigationHeader` related stuff. There's another error regarding `children` prop (which Flow doesn't support) which isn't caught by CI. I have this error in `0.30` and my config is pretty identical to RN's.

**Comment by ide** [comment]
@satya164 thanks for the explanation, that makes sense. Sounds like we should get CI to check these files then.

**Comment by flegall** [comment]
@ide I'm already ignoring $FlowIssue pragmas using the same suppress_comment regex as RN .flowconfig

But the warning is about a $FlowIssue suppression that is not used, right ?
I will make a PR that removes the useless $FlowIssue, this seems to fix the problem on my setup.

**Comment by flegall** [comment]
Ok removing the $FlowIssue pragma doesn't work on react-native repository : 

I'm facing this flow error when trying : 

```

~/code/github/react-native /master $ npm run flow

> react-native@1000.0.0 flow /Users/flegall/code/github/react-native
> flow

Launching Flow server for /Users/flegall/code/github/react-native
Spawned flow server (child pid=17996)
Logs will go to /private/tmp/flow/zSUserszSflegallzScodezSgithubzSreact-native.log
Libraries/CustomComponents/NavigationExperimental/NavigationHeader.js:89
 89:       return <NavigationHeaderTitle>{title}</NavigationHeaderTitle>;
                  ^^^^^^^^^^^^^^^^^^^^^^^ React element `NavigationHeaderTitle`
 52: const NavigationHeaderTitle = ({ children, style, textStyle, viewProps }: Props) => (
                                                                               ^^^^^ property `children`. Property not found in. See: Libraries/CustomComponents/NavigationExperimental/NavigationHeaderTitle.js:52
 89:       return <NavigationHeaderTitle>{title}</NavigationHeaderTitle>;
                  ^^^^^^^^^^^^^^^^^^^^^^^ props of React element `NavigationHeaderTitle`


Found 1 error

```

**Comment by satya164** [comment]
@flegall I think you can change the children prop to be `children?` in `NavigationHeaderTitle`

**Comment by flegall** [comment]
@satya164 it seems to work, PR on the way ...
