### ISSUE TITLE
[iOS] <Image> or <View> is to be nested within <Text> as child of <Text> the layout overlap

### ISSUE THREAD

**Issue by ymmuse** [facebook/react-native#9059]
When i set the lineHeight of Text that is to be nested within Text as child of Text, I get the layout overlap. Here is my code:

```javascript
class nestedImage extends Component {
  render() {
    return (
       <Text style={{lineHeight: 30}}>
          hello{'\n'}
            <Text>
            <View style={{width: 300, height: 100, backgroundColor: 'steelblue'}} />{'\n'}world
            </Text>
        </Text>
    );
  }
}
```
![5e7e5ff0-27f6-4451-aaab-104de0788a67](https://cloud.githubusercontent.com/assets/568577/17206609/31713eae-54e3-11e6-8ad1-91356db445b8.png)

Actually, If i remove the child Text that is a parent of View, I can get correct layout, but between the text 'hello' and View lineHeight is incorrect, And the lineHight change to the View Height.

```javascript
class nestedImage extends Component {
  render() {
    return (
       <Text style={{lineHeight: 30}}>
          hello{'\n'}
            {/*<Text>*/}
            <View style={{width: 300, height: 100, backgroundColor: 'steelblue'}} />{'\n'}world
            {/*</Text>*/}
        </Text>
    );
  }
}
```
![68ba16f8-2fa0-4d80-9e3f-50c2eef90fc6](https://cloud.githubusercontent.com/assets/568577/17206900/94cb45e8-54e4-11e6-81ba-7ebf376d0a15.png)

At last,  I found the native module code, that's why the lineHeight change to View height:
[get NSTextAttachment height](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L299-L307)
[setting all text lineHeight](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L412-L415)

I try to fix this problem, i found these code will take out the size of NSTextAttachment and it position.
[boundingRectForGlyphRange](https://github.com/facebook/react-native/blob/master/Libraries/Text/RCTShadowText.m#L157-L165)

About the position incorrect I found a interesting thing that the boundingRectForGlyphRange method cannot get correct position when setting ParagraphStyle.maximumLineHeight.
So I have made a demo about testing boundingRectForGlyphRange on the situation.

```objective-c
    NSMutableAttributedString *s = [_textView.attributedText mutableCopy];
    
    NSMutableParagraphStyle *pstyle = [NSMutableParagraphStyle new];
//    uncomment these the string and image will be overlap
//    pstyle.maximumLineHeight = 30;
//    pstyle.minimumLineHeight = 30;

//  correct display string and image
    pstyle.lineSpacing = 50;
    
    [s addAttribute:NSParagraphStyleAttributeName value:pstyle range:(NSRange){0, s.length}];
    
    NSLayoutManager *layout = _textView.textStorage.layoutManagers.firstObject;
    NSTextContainer *textContainer = layout.textContainers.firstObject;
    NSRange glyphRange = [layout glyphRangeForTextContainer:textContainer];
    NSRange characterRange = [layout characterRangeForGlyphRange:glyphRange actualGlyphRange:NULL];
    [layout.textStorage enumerateAttribute:NSAttachmentAttributeName inRange:characterRange options:0 usingBlock:^(NSTextAttachment *child, NSRange range, BOOL *_) {
        if (child) {
            CGRect glyphRect = [layout boundingRectForGlyphRange:range inTextContainer:textContainer];
            NSLog(@"%@", glyphRect.origin.y);
        }
    }];

    [self setAttributedText:s];

```

Now, I am stucking...

**Comment by ymmuse** [comment]
no anyone know what has happened?

**Comment by ymmuse** [comment]
I wrote a testing demo in [github](https://github.com/ymmuse/uitextviewbug). the detail that you could see the README

**Comment by lacker** [comment]
I can't quite figure out what problem you are reporting exactly. It's also been a while, so I'm going to close this issue. If this is still a problem for you then I suggest opening a new issue and being very clear about what code you are testing, what you see, and what you expect to see.
