### ISSUE TITLE
RCTEventDispatcher is calling missing JS module

### ISSUE THREAD

**Issue by jnhuynh** [facebook/react-native#906]
[React's doc][1] for sending events to JS from native code suggests using RCTEventDispatcher's `sendAppEventWithName:body` method.

The problem is that `RCTNativeAppEventEmitter` does not exist. Not sure what the correct solution to this is. Should we create a `RCTNativeAppEventEmitter` module? Or should the docs suggest using `sendDeviceEventWithName:body`.

```
- (void)sendAppEventWithName:(NSString *)name body:(id)body
{
  [_bridge enqueueJSCall:@"RCTNativeAppEventEmitter.emit"
                    args:body ? @[name, body] : @[name]];
}
```

[1]:http://facebook.github.io/react-native/docs/nativemodulesios.html#sending-events-to-javascript

**Comment by mymickey** [comment]
+1

**Comment by brentvatne** [comment]
@jnhuynh @mymickey - pull request create, closing this issue to move the discussion there!
