### ISSUE TITLE
React Packager can't work-FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by Deain** [facebook/react-native#9062]
- [x] React Native :0.30.0
- [x] this occurs on Android 
- [x] I'm using  Windows

React packager ready.

[18:29:43] <START> request:/index.android.bundle?platform=android&dev=true&hot=true&minify=false
[18:29:43] <START> find dependencies
[18:32:27] <START> request:/index.android.bundle?platform=android&dev=true&hot=true&minify=false
[18:35:48] <START> request:/index.android.bundle?platform=android&dev=true&hot=true&minify=false

<--- Last few GCs --->

  478163 ms: Mark-sweep 1349.7 (1457.6) -> 1349.6 (1457.6) MB, 757.8 / 0 ms [allocation failure] [GC in old space requested].
  478938 ms: Mark-sweep 1349.6 (1457.6) -> 1349.6 (1457.6) MB, 767.8 / 0 ms [allocation failure] [GC in old space requested].
  479707 ms: Mark-sweep 1349.6 (1457.6) -> 1349.5 (1457.6) MB, 773.8 / 0 ms [last resort gc].
  480470 ms: Mark-sweep 1349.5 (1457.6) -> 1349.5 (1457.6) MB, 759.4 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000320019B4639 <JS Object>
    1: indexOf(aka indexOf) [native string.js:~76] [pc=0000000416E47FCD] (this=0000017EA8F22379 <String[320]: C:\Users\Dean\Desktop\RN-BiZhi\node_modules.npminstall\react-native\0.29.2\react-native\node_modules\babel-preset-fbjs\node_modules\babel-plugin-transform-es2015-parameters\node_modules\babel-helper-get-function-arity\node_modules\babel-types\node_modules\babel-traverse\node_modules...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by Deain** [comment]
I don't know what happened, it worked slowly yesterday. But now, boom…… it out of work completely

**Comment by philipheinser** [comment]
@Deain I have the same problem in RN 0.30.0 iOS on Mac. The packager gets an out of memory if i ` require('bigfile.json')` a large json file.

`[19:25:10] <START> find dependencies
transformed 772/773 (100%)[19:26:33] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false

<--- Last few GCs --->

 2603586 ms: Mark-sweep 1389.0 (1434.4) -> 1389.0 (1434.4) MB, 4185.7 / 0 ms [allocation failure] [GC in old space requested].
 2607948 ms: Mark-sweep 1389.0 (1434.4) -> 1389.0 (1434.4) MB, 4361.9 / 0 ms [allocation failure] [GC in old space requested].
 2612190 ms: Mark-sweep 1389.0 (1434.4) -> 1389.0 (1434.4) MB, 4242.6 / 0 ms [last resort gc].
 2616295 ms: Mark-sweep 1389.0 (1434.4) -> 1389.0 (1434.4) MB, 4104.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2b1baf2c9e59 <JS Object>
    2: parseLiteral [/Users/philipheinser/react/node_modules/babylon/lib/parser/expression.js:552] [pc=0xe39c530bb62] (this=0x24f75195bd89 <a Parser with map 0x2bf066eb65c9>,value=0x55c54bf8a71 <String[1]: 0>,type=0x320a6d318481 <String[13]: StringLiteral>)
    3: parseExprAtom [/Users/philipheinser/react/node_modules/babylon/lib/parser/expression.js:467] [pc=0xe39c5...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::TypeFeedbackVector::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::TypeFeedbackMetadata>) [/usr/local/bin/node]
 6: v8::internal::CompilationInfo::EnsureFeedbackVector() [/usr/local/bin/node]
 7: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 8: v8::internal::GenerateBaselineCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 9: v8::internal::GetUnoptimizedCodeCommon(v8::internal::CompilationInfo*) [/usr/local/bin/node]
10: v8::internal::Compiler::GetLazyCode(v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/bin/node]
11: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0xe39c340961b
13: 0xe39c3431ed9

<--- Last few GCs --->

 2714960 ms: Mark-sweep 1390.9 (1434.4) -> 1390.9 (1434.4) MB, 4027.1 / 0 ms [allocation failure] [GC in old space requested].
 2719297 ms: Mark-sweep 1390.9 (1434.4) -> 1390.9 (1434.4) MB, 4336.8 / 0 ms [allocation failure] [GC in old space requested].
 2723635 ms: Mark-sweep 1390.9 (1434.4) -> 1390.8 (1434.4) MB, 4338.7 / 0 ms [last resort gc].
 2727614 ms: Mark-sweep 1390.8 (1434.4) -> 1390.8 (1434.4) MB, 3979.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x197e938c9e59 <JS Object>
    2: readToken [/Users/philipheinser/react/node_modules/babylon/lib/tokenizer/index.js:180] [pc=0x1848474e6168] (this=0x204fd760d889 <a Parser with map 0x2f138cab9171>,code=34)
    3: /* anonymous */ [/Users/philipheinser/react/node_modules/babylon/lib/plugins/jsx/index.js:~24] [pc=0x1848474c6e4b] (this=0x204fd760d889 <a Parser with map 0x2f138cab9171>,code=34)
   ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [/usr/local/bin/node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::CompilationInfo*) [/usr/local/bin/node]
 7: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 8: v8::internal::GenerateBaselineCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 9: v8::internal::GetUnoptimizedCodeCommon(v8::internal::CompilationInfo*) [/usr/local/bin/node]
10: v8::internal::Compiler::GetLazyCode(v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/bin/node]
11: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x18484620961b
13: 0x184846231ed9`

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-packager-cant-work-fatal-error-callandretrylast-allocation-failed-process-out-of-memory

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
