### ISSUE TITLE
Navigator and props.

### ISSUE THREAD

**Issue by vaibhawc** [facebook/react-native#9063]
I am bit confused now. I use RN0.30 and had been navigating smoothly until recently when I found that the page I navigated to was not receiving new props. I expected it to.
Workarounds are there, and I handled it to work for my case also. 
But now I am very curious why navigator doesn't pass my updated props? Is it by design? What was the intention to keep it that way? and do you intent to change it in future? A brief definition and it's place and role in overall architecture will help a lot.
Thanks.

**Comment by grabbou** [comment]
@facebook-github-bot stackoverflow

**Comment by grabbou** [comment]
@vaibhawc There were no changes to Navigator in the releases so far that I am aware of (I haven't also noticed any significant changes to the look & feel of the apps I've done with it). It's likely your question contains potential developer concerns that can be addressed on StackOverflow.
