### ISSUE TITLE
NavigationCardStack onTransition finish

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#9064]
I employ an "isNavigating" property in my reducer to prevent fast clicking to create havoc. Not sure if it's necessary. I need to be able to turn this off at the end of the transition. Is there a way to have an onTransitionEnd callback?

**Comment by ryankask** [comment]
Which version of React Native are you using? 

`NavigationTransitioner`, which NavigationCardStack now uses, has `onTransitionStart` and `onTransitionEnd` props.

`NavigationCardStack` doesn't have these props, however. You might be able to extend the class and override `render()` (https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L123) passing `onTransitionEnd` so you can dispatch an action as needed.
