### ISSUE TITLE
panResponder does not respond to gestures on android

### ISSUE THREAD

**Issue by madox2** [facebook/react-native#9068]
I am trying to implement custom `panResponder` to handle some specific gestures on android device (react native 0.28.0). Running sample code below it should log message if I pull upside down:

``` javascript
import { AppRegistry, View, PanResponder } from 'react-native'
import React, { Component } from 'react'

class Demo extends Component {

  componentWillMount() {
    this._panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onMoveShouldSetPanResponder: () => true,
      onPanResponderTerminationRequest: () => true,
      onPanResponderRelease: (evt, { dx, dy }) => {
        if (dy > 30 && Math.abs(dx) < 15) {
          console.log('drag down')
        }
      },
    })
  }

  render() {
    return (
      <View {...this._panResponder.panHandlers}>
        <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}>
          <View style={{ backgroundColor: 'blue', height: 100, width: 100 }} />
          <View style={{ backgroundColor: 'green', height: 100, width: 100 }} />
        </View>
      </View>
    )
  }

}

AppRegistry.registerComponent('demo', () => Demo)
```

It does work inside blue and green square not in the right part of the view:

![without_collapsable](https://cloud.githubusercontent.com/assets/15847857/17216659/d68fa5e4-54e1-11e6-9240-1255397b8c7a.png)

It seems that android did some optimization and removed nested view (2nd one). As a workaround I set `collapsable` property to `false` and it does work.

``` javascript
<View style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }} collapsable={false}>
```

![with_collapsable](https://cloud.githubusercontent.com/assets/15847857/17216653/d1e862c4-54e1-11e6-85de-8c2828ef0a07.png)

I think this is a bug because if I am right android optimization broke my gesture system.
Furthermore I cannot set `collapsable` property in 3rd party components so that workaround above doesn't work for me.

**Comment by alexHlebnikov** [comment]
Same problem here.

**Comment by lacker** [comment]
I'm confused by these arrow diagrams. What do you mean by "It seems that android did some optimization and removed nested view (2nd one)" - how exactly are you concluding that Android is removing a view?

**Comment by sodik82** [comment]
arrows are just displaying touch gestures.

that conclusion was made from the observation that gestures are properly detected only when `collapsable=false` and the "fact" that android does optimalizations to physical representation of views by removing some of them.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

      The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/panresponder-does-not-respond-to-gestures-on-android

      There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

      If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Comment by augustl** [comment]
Seems like this should remain closed. It's not React Native that optimizes away invisible views. So you have to set views that are invisible to `collapsable={false}` to ensure that they remain in the view hierarchy, if you use invisible views to implement larger touch areas etc.
