### ISSUE TITLE
[Android][ListView] Wrapping items take up the height of the whole container

### ISSUE THREAD

**Issue by quietbits** [facebook/react-native#9069]
It seems like after the update (0.29 or 0.30, not 100% sure which one, but it worked on 0.28) items in a ListView that wrap, take up the height of the whole container. The more items are wrapping, the longer is their height, so I assume it's taking up the container height. There is nothing special in styling or structure there. Just a ListView with item template passed in.

Container styling to make items wrap. If they don't wrap, the height is fine.
`<ListView
    contentContainerStyle={{
        flexDirection: 'row',
        flexWrap: 'wrap'
    }}
    renderRow={ (item) => (<ItemTemplate item={item} />) }
/>`

If flexWrap is set to 'wrap' and there are not enough items to wrap (all fit on one line), the height of the items is fine.

When items wrap:
![Item height wrong](https://cloud.githubusercontent.com/assets/7346473/17218076/850363a0-54b4-11e6-9a53-da00bebedcb2.png)

When items don't wrap:
![Item height correct](https://cloud.githubusercontent.com/assets/7346473/17218089/944dd7f0-54b4-11e6-86ea-7facf404707b.png)

The only fix for this right now is to set a fixed height to the item. Not ideal, but it works for now. Is anyone having this issue? Maybe you have found a better fix?

React Native: 0.30.0
OS: Mac

**Comment by ryankask** [comment]
What happens if you change `contentContainerStyle`to:

```
{ flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start' }
```

This may be related to https://github.com/facebook/react-native/issues/8960.

I wonder if any of these issues are the result of recent changes to css-layout (for example, https://github.com/facebook/css-layout/pull/185).

**Comment by quietbits** [comment]
@ryankask: thanks for the quick response. Unfortunately, adding `alignItems: 'flex-start'` didn't help.

Not sure if it matters, but I have set width for item. When I removed it, it didn't help, though.

**Comment by ryankask** [comment]
@quietbits Interesting. I can reproduce the issue but alignItems fixes it. Could you post the row container's style?

**Comment by quietbits** [comment]
@ryankask, sure. I'm posting the whole item with styles. Maybe there is something off with item element styles.

```javascript
<TouchableOpacity
	style={{ width: 125, elevation: 3, margin: 5, padding: 5 }}
>
	<View style={{ alignSelf: 'center', marginBottom: 5 }}>
		<FadeInImage
			source={{ IMAGE_URL }}
			style={{ height: 125, width: 125 }}
		/>
	</View>
	<View style={{ flex: 1, alignSelf: 'flex-start', marginBottom: 5 }}>
		<Text
			numberOfLines={2}
			style={{ textAlign: 'center' }}>
			[TEXT 1]
		</Text>
	</View>
	<View>
		<Text style={{ textAlign: 'center' }}>[TEXT 2]</Text>
	</View>
</TouchableOpacity>
```
The idea is to have item elements always aligned this way:
- image to the top (it is fixed height)
- text 1 right after the image
- text 2 always at the bottom

Here is illustration of it.

![image](https://cloud.githubusercontent.com/assets/7346473/17295333/9fcf457e-57c9-11e6-958a-1bb38cf0c5f7.png)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/androidlistview-wrapping-items-take-up-the-height-of-the-whole-container

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
