### ISSUE TITLE
Using ListView in 0.4.0 logs "Your code is broken!" warning

### ISSUE THREAD

**Issue by johanneslumpe** [facebook/react-native#907]
When displaying a ListView the following warning is logged:

`"Your code is broken! Do not iterate over arrays with for...in."`

I'm not sure whether it's the ListView or the ScrollView doing something weird.

**Comment by ide** [comment]
See #848, it's the deepDiffer's treating objects as arrays.

**Comment by jbssm** [comment]
So, why was the bug closed? The bug is still there.

**Comment by spicyj** [comment]
It's being tracked in #868.

**Comment by jbssm** [comment]
Ah ok, thanks.
