### ISSUE TITLE
Support setBackground on Android (for Splash Screens)

### ISSUE THREAD

**Issue by chrisknepper** [facebook/react-native#9072]
I'm trying to implement a splash screen for my React Native app on Android.

Per [this StackOverflow discussion](http://stackoverflow.com/questions/8929172/android-activity-background-image), it is possible to give an Android app a splash image by setting `<item name="android:background">@drawable/splash_image_file</item>` in the styles XML. Here's my code:

In `android/app/src/main/AndroidManifest.xml`:

```
 <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@style/AppTheme"
        android:name="android.support.multidex.MultiDexApplication">
```

In `android/app/src/main/res/values/styles.xml`:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:background">@mipmap/splash</item>
    </style>
```

There are files named "splash.png" in each of the mipmap pixel density folders (mipmap-xhdpi, etc...)

The splash screen itself works great, but as soon as the React Native code begins to execute, I am greeted with the following error:

![screenshot jul 28 2016 3 10 43 pm](https://cloud.githubusercontent.com/assets/4976096/17226105/c4796b58-54d5-11e6-8041-d5c04900aa83.png)

And sure enough, glancing at `ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java` [link](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewGroup.java) it throws an error when attempting to call setBackground. I'm wondering why this method isn't supported?

My current workaround is to start the app with another `Activity` that does not extend `ReactActivity`, but the user sees a blank white screen while `MainActivity` is loading the JS.

Using React Native `0.25.1`.

**Comment by RichardBoyewa** [comment]
Please any update on this issue. I am having the same issue... I tried all the resources, but just couldn't solve this issue. Is is a framework issue?
@chrisknepper , have u solved the issue?

**Comment by mehcode** [comment]
@chrisknepper @RichardBoyewa Take a look at https://github.com/mehcode/rn-splash-screen -- there is an example https://github.com/mehcode/rn-splash-screen/tree/master/example and docs https://github.com/mehcode/rn-splash-screen/blob/master/docs/android.md

**Comment by RichardBoyewa** [comment]
@chrisknepper 
Adjust your AppTheme and remove the added line

```<item name="android:windowBackground">@drawable/splash</item>```

**Comment by chrisknepper** [comment]
@mehcode I'd prefer to not use a third-party dependency for this, given that it is standard app functionality and works fine for iOS (guide). If it can work for iOS using the standard implementation, we should be able to do the same for Android.

@RichardBoyewa Using `android:windowBackground` instead of `android:background` prevents the app from crashing, but does not scale the splash screen or factor in the height of the Android UI (notification bar, on-screen navigation buttons, etc...), so the aspect ratio looks bad.

**Comment by mehcode** [comment]
@chrisknepper I linked you to detailed documentation to show you how to do it. The plugin usage is optional. The plugin gives you a "second stage" splash screen that you can hide with javascript to give yourself more loading time if you want.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/support-setbackground-on-android-for-splash-screens

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
