### ISSUE TITLE
[iOS][0.30.0][0.29.2][PushNotificationIOS] getInitialNotification() returns empty object

### ISSUE THREAD

**Issue by antihate** [facebook/react-native#9076]
componentWillMount() {
      PushNotificationIOS.getInitialNotification()
      .then((notification) => {
        alert('coldLaunchPush: ' + JSON.stringify(notification));    
      });
    }

(V0.30.0, V0.29.2) (IOS, MAC)
Cold app launch from remote push returns empty object `{}` It was working on V0.28.0 with popInitialNotification() which got deprecated.

Is this a bug or I'm missing something? Asked on [stackoverflow](http://stackoverflow.com/questions/38601210/react-native-0-30-00-29-2-pushnotificationios-getinitialnotification-retur) didn't received any response.

**Comment by ymmuse** [comment]
The bug has been fixed in v0.31.0

**Comment by antihate** [comment]
Thanks for the info but I just read the release notes for V0.31.0 and I didn't find any related commit to this issue?

**Comment by ymmuse** [comment]
Yes, It does not. But it has been [fixed](https://github.com/facebook/react-native/commit/58202b7ba4cbb701fb5a1e6bfeaf6de7035d8707)

**Comment by grabbou** [comment]
Here's similar question -> http://stackoverflow.com/questions/38645181/how-to-work-with-react-natives-pushnotificationios-getinitialnotification that I've answered earlier today.

Going to close it for now as @ymmuse reports it to be fixed. @antihate in case you encounter this issue on 0.31-rc, please let me know and we will reopen.

**Comment by antihate** [comment]
I'll report back after 0.31 release, Thanks!

**Comment by markgoodyear** [comment]
@AntiHate I had this issue on 0.30, and can confirm everything is working as expected with 0.31.0-rc.1.

**Comment by AntiHate** [comment]
Yes, its fixed, Thankyou everybody!
