### ISSUE TITLE
Packager: recognize alternate require statements

### ISSUE THREAD

**Issue by pesterhazy** [facebook/react-native#9084]
The RN packager scans the JavaScript entry point and its dependency for occurrences of `require("lib")`. A project I work on (https://github.com/mjmeintjes/boot-react-native/issues/49) makes the packager work for ClojureScript. ClojureScript uses Google Closure dependency management internally. Long story short, to make this work we need to recognize statements of the form `goog.require("lib")` in addition to just `require`.

This patch makes things work for us: https://github.com/pesterhazy/boot-react-native/blob/develop/example/rn-goog-require.patch. I realize this is custom code. Would you guys be willing to accept a PR that makes the packager recognize alternate `require` statements, possibly by making this configurable?

`boot-react-native` is quite useful as it allows us to write RN apps in ClojureScript; similar problems might affect other compile-to-js languages that want to target RN as well.

**Comment by lacker** [comment]
I think it would be okay as long as the behavior is testable, the PR is small, and there is a way to make it clear that this won't break non-ClojureScript use cases. The exact line probably depends on the pull request, so if you are still interested in this I think the way to go would be to prepare a PR and then discuss it from there.

**Comment by oximer** [comment]
I also interested to figure out how to figure the ID of a module. I'm guessing that the packager is building a map that bind name with id. Where I can find that map?
