### ISSUE TITLE
DrawerLayoutAndroid lock mode need to be set dynamically

### ISSUE THREAD

**Issue by RichardLindhout** [facebook/react-native#9092]
I use NavigationExperimental with a DrawerLayout (https://github.com/iodine/react-native-drawer-layout)

(This implement the React Native DrawerLayoutAndroid feature on Android devices.)

It is possible to set the lock mode via the props of the drawerlayout, but I don't want that because on some views the drawer have to work.

I need to set the lock mode  drawerLockMode={'locked-closed'} when the user navigates to another view because I want to have the swipeback properly working.

However I can't find a way to set the drawerLockMode dynamically. Maybe this is possible and I'm wrong but I think it is not available.

I think it should be a good idea to make this working. Maybe I will send a PR request but I don't know if I'm smart enough for that ;)

```
  <DrawerLayout
        drawerWidth={300}
        drawerPosition={DrawerLayout.positions.Left}
        renderNavigationView={() => navigationView}

        ref={(drawer) => { return this.drawer = drawer  }}>
        <View style={{flex: 1, alignItems: 'center', position:'absolute'}}>
          <Text style={{margin: 10, fontSize: 15, textAlign: 'right'}}>Hello</Text>
          <Text style={{margin: 10, fontSize: 15, textAlign: 'right'}}>World!</Text>
        </View>

        <NavigationCardStack
          onNavigateBack={this._handleBackAction.bind(this)}
          navigationState={this.props.navigation}
          onNavigate={this._handleNavigate.bind(this)}
          renderScene={this._renderScene}
          renderOverlay={this._renderHeader} />

        </DrawerLayout>
```

- I use react-native 0.30
- This bug occurs on Android
- I am using Mac

PS: It's not possible to render the drawerlayout on the Home component because I need the drawer to overlay the HeaderView of the NavigationCardStack.

**Comment by ryankask** [comment]
There are several ways to do this and it depends on the shape and structure of your navigation state. 

If you have a top level stack you can simply set the drawer to locked if the currently active route index is greater than 0. 

drawerLockMode={this.props.navigation.index > 0 ? 'locked-closed' : 'something else'}

Would that work?

By the way, you should check out the react-native channel on Discord. It's a great place to ask questions and everyone there is really helpful.

**Comment by RichardLindhout** [comment]
Wow that worked like a charm! Thank you and thanks for your suggestion I joined the Discord channel!
