### ISSUE TITLE
StyleSheet.fullScreen is not compatible with React 15.3.0

### ISSUE THREAD

**Issue by steida** [facebook/react-native#9093]
Warning: You are manually calling a React.PropTypes validation function for the 'bottom' prop on 'StyleSheet.fullScreen'. This is deprecated...

**Comment by marcusmotill** [comment]
Experiencing this on react 15.2.0 and react-native 0.30.0

**Comment by neiker** [comment]
Same here, see this issue in React:
https://github.com/facebook/react/issues/7131
And the corresponding PR:
https://github.com/facebook/react/pull/7132

**Comment by satya164** [comment]
> @neiker I suggest you to downgrade to react 15.2.1 until RN support react 15.3.0

Isn't this just an warning? No need to downgrade.

**Comment by mehcode** [comment]
It's a very annoying warning (I get about about a 1000 yellow boxes every reload). Enough to make me downgrade unless it was super nice in 15.3.x I wanted and even then I'd probably fork react to make it stop warning me.

**Comment by steida** [comment]
@mehcode Easy fix: https://github.com/este/este/blob/617441c75ecf0a0262c06f34dcda1a66b4b8dddc/src/native/index.js#L5

**Comment by fabriziomoscon** [comment]
@satya164 this is a big deal for development experience because with 1000 yellow boxes every little step in development takes 10 seconds. I understand there are workarounds but if I can express my thoughts this is a deal breaker for upgrading.

**Comment by neiker** [comment]
@satya164 yeah, it's just a warning, but a really annoying one.

**Comment by steida** [comment]
Common, you can hide one warning easily.

**Comment by satya164** [comment]
> this is a big deal for development experience because with 1000 yellow boxes every little step in development takes 10 seconds.

You can hide the specific warning by following the steps here - https://github.com/facebook/react-native/blob/654a36018c069aca836c512ce71c0e325ca1ff7e/Libraries/ReactIOS/YellowBox.js#L49

**Comment by satya164** [comment]
Also would be nice if someone can send a PR to fix this issue in RN core.

**Comment by neiker** [comment]
Is fixed in RN 0.31.0

https://github.com/facebook/react-native/commit/5db5ee9f556ee0486f4e805425807fc74e23a9d3

**Comment by satya164** [comment]
@neiker Thanks. Closing this then.
