### ISSUE TITLE
ListView onChangeVisibleRows() stops being triggered after 100 rendered rows

### ISSUE THREAD

**Issue by 39otrebla** [facebook/react-native#9101]
Hi. I have the need of trigger certain actions relying on current visible rows. I am using onChangeVisibleRows(visibleRows, changedRows), here is an example:

```
onChangeVisibleRows={(visibleRows, changedRows) => {
          console.log(changedRows)
          if (Object.keys(visibleRows).length > 0) {
            let v = {}
            Object.keys(visibleRows).map(o => {
              Object.keys(visibleRows[o]).map(i => {
                v[i] = null
              })
            })
            this.setState({visible: v})
          }
        }}
```

But as soon as I reach 100 rendered rows, onChangedVisibleRows is no more triggered.

An example of the console.log() above:

> > 2016-07-30 12:50:12.453 [info][tid:com.facebook.react.JavaScript] { s1: { '96': true } }
> > 2016-07-30 12:50:12.524 [info][tid:com.facebook.react.JavaScript] { s1: { '94': false } }
> > 2016-07-30 12:50:13.070 [info][tid:com.facebook.react.JavaScript] { s1: { '97': true } }
> > 2016-07-30 12:50:13.485 [info][tid:com.facebook.react.JavaScript] { s1: { '95': false } }
> > 2016-07-30 12:50:13.637 [info][tid:com.facebook.react.JavaScript] { s1: { '96': false, '98': true } }
> 
> [........]
> 2016-07-30 12:50:13.948 [info][tid:com.facebook.react.JavaScript] { s1: { '97': false, '99': true } }
> 
> 2016-07-30 12:50:14.043 [info][tid:com.facebook.react.JavaScript] { s1: { '100': true } }
> 2016-07-30 12:50:14.187 [info][tid:com.facebook.react.JavaScript] { s1: { '98': false } }
> 2016-07-30 12:50:15.482 [info][tid:com.facebook.react.JavaScript] { s1: { '99': false } }
> 2016-07-30 12:50:15.737 [info][tid:com.facebook.react.JavaScript] { s1: { '100': false } }
> 
> NO MORE OUTPUT 

RN@0.30 on Mac OS X El Capitan

**UPDATE**
On Android it's not even implemented.

**Comment by tiero** [comment]
👍

**Comment by HiZhenyu** [comment]
try

_updateVisibleRows: function(updatedFrames?: Array<Object>) {
    if (!this.props.onChangeVisibleRows) {
      return; // No need to compute visible rows if there is no callback
    }
    if (updatedFrames) {
      updatedFrames.forEach((newFrame) => {
        if(newFrame.height == 0 || newFrame.width == 0) return ;
        this._childFrames[newFrame.index] = merge(newFrame);
      });
    }


add:
if(newFrame.height == 0 || newFrame.width == 0) return ;

**Comment by tiero** [comment]
@facebook-github-bot label ios

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/listview-onchangevisiblerows-stops-being-triggered-after-100-rendered-rows

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
