### ISSUE TITLE
Android,RN0.30 WebView Render Error

### ISSUE THREAD

**Issue by sansancloud** [facebook/react-native#9106]
render: function() {
return (

      <Navigator
        initialRoute={{ title: 'Awesome Scene', index: 0 }}
        renderScene={(route, navigator) =>
       <WebView
            source={{uri: 'http://www.sansancloud.com'}}
          />
        }
      />
    );
}

this code can't show webview .

because website 'http://www.sansancloud.com' has css   body {position:fixed}
may be zIndex  confuse

**Comment by lacker** [comment]
I think this would need more information to make progress.
