### ISSUE TITLE
Text not appearing in Android

### ISSUE THREAD

**Issue by stenrap** [facebook/react-native#9110]
I'm developing an app with React Native 0.29.1 and React 15.2.1 in Mac OS X El Capitan 10.11.5. I'm seeing an issue where some text is visible in iOS, but not visible in Android. I've been able to reproduce the issue at rnplay.org—notice that the text below the numbers ("Profile", "Demographics", and "Account") appears in iOS but not in Android:

https://rnplay.org/apps/IhRZ-A

Is there something wrong with my styles, or is this perhaps a bug?

**Comment by skatpgusskat** [comment]
@stenrap I guess the ```stepCircle```'s size(width, height) is (32, 32), so overflowed child component(in this case, ```stepXNameText```) has hidden.
why don't you renew layout without setting ```StepNameText``` into ```StepCircle```?

**Comment by stenrap** [comment]
Thank you, @skatpgusskat, you were exactly right—I fixed this by moving the step name text out of the circle view. I didn't realize that Android defaults to `overflow:hidden` and there's no way to change that (according to an [older version of the docs](http://facebook.github.io/react-native/releases/0.23/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android)).
