### ISSUE TITLE
Rotate transform not working on Android

### ISSUE THREAD

**Issue by stenrap** [facebook/react-native#9112]
I'm working on an app with React Native 0.29.1 and React 15.2.1 on Mac OS X El Capitan 10.11.5. I've created a tooltip component that is displaying perfectly on iOS, but not on Android—the arrow at the bottom of the tooltip isn't displaying correctly. Here's a sample app on rnplay.org that demonstrates the issue. Looks like maybe a problem with the rotate transform (click SUBMIT to see the tooltip appear):

https://rnplay.org/apps/-p7gAw

**Comment by ryankask** [comment]
Android does not support `overflow: 'visible'` so you need to make sure the arrow is not positioned below the bottom of the parent.

**Comment by stenrap** [comment]
Thank you, @ryankask, you were right. I fixed it by making the arrow a sibling instead of a child with a negative bottom value. I'm not sure why this information about `overflow` (and the entire "Known Issues" page) got pulled out of the React 0.29 documentation, but [it's still in the 0.28 docs](http://facebook.github.io/react-native/releases/0.28/docs/known-issues.html#the-overflow-style-property-defaults-to-hidden-and-cannot-be-changed-on-android).
