### ISSUE TITLE
com.github.facebook.watchman.plist for write: Permission denied

### ISSUE THREAD

**Issue by MappleHero** [facebook/react-native#9116]
I am studying react-native.And I follow the tutorials on the website.When I execute "react-native run-ios". It happens some error messages.

```
Looking for JS files in
   /Users/Mapple/Developer/React-native-workspace/HelloWorld 

[19:16:32] <START> Building Dependency Graph
[19:16:32] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

2016-07-30T19:16:32,265: [cli] Failed to open /Users/Mapple/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Permission denied

2016-07-30T19:16:32,265: [cli] Failed to open /Users/Mapple/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Permission denied

Watchman:  watchman--no-pretty get-sockname returned with exit code null 2016-07-30T19:16:32,265: [cli] Failed to open /Users/Mapple/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Permission denied

 ERROR  watchman--no-pretty get-sockname returned with exit code null 2016-07-30T19:16:32,265: [cli] Failed to open /Users/Mapple/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Permission denied

Error: watchman--no-pretty get-sockname returned with exit code null 2016-07-30T19:16:32,265: [cli] Failed to open /Users/Mapple/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Permission denied

    at ChildProcess.<anonymous> (/Users/Mapple/Developer/React-native-workspace/HelloWorld/node_modules/fb-watchman/index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```
I find there is no file-com.github.facebook.watchman.plist in the /Users/Mapple/Library/LaunchAgents. I tried a variety of ways, but it does not play a role。

**Comment by MappleHero** [comment]
I solve my problem.There is a file in my directory called “org.lantern.plist”.I guess it's because of the Lantern software.So when I delete /Users/Mapple/Library/LaunchAgents and re create it,and re execute the command “react-native init HelloWorld”,my problem has solved.

**Comment by MappleHero** [comment]
fix #9116

**Comment by MappleHero** [comment]
Close #9116

**Comment by anil826** [comment]
I have same issue on my OS X EI captain Please let me know how to fix it.
I have tried all the methods. 

 ERROR  watchman--no-pretty get-sockname returned with exit code null 2016-12-05T23:36:00,866: [cli] Failed to open /Users/anilyadav/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

**Comment by brianarpie** [comment]
@anil826 my guess is ~/Library/LaunchAgents is still owned by root. You can resolve this by deleting the directory and creating it as the current user. The following worked for me:

```
rm ~/Library/LaunchAgents
mkdir ~/Library/LaunchAgents
```

cheers

**Comment by anil826** [comment]
@brianarpie thanks for the reply the issue is solved now there is a linking problem in my MAC Seria OS so after removing the default linking and problem is  solved  for me.... :)

**Comment by olsio** [comment]
@brianarpie deleting the directory might delete other LaunchAgents a better solution would be to update the user:

`sudo chown -R $(whoami):staff ~/Library/LaunchAgents`

In my case the offending party was LastPass, I raised a bug with them, the installer seems to create the directory as root.

**Comment by alien-col** [comment]
Thanks @olsio, indeed LastPassis the culprit.

**Comment by BenBtg** [comment]
Thanks @olsio, Same here. LastPass!

**Comment by w-wonk** [comment]
Thanks a lot @brianarpie !
