### ISSUE TITLE
How can i scrollTo Bottom

### ISSUE THREAD

**Issue by wangzhe1995** [facebook/react-native#913]
ScrollView how can i scroll to the bottom

**Comment by ide** [comment]
Compute the y offset from the content size and viewport size, and call scrollTo.

**Comment by wangzhe1995** [comment]
but i can i get viewport size ?

**Comment by ide** [comment]
Look in the source code to learn how the UIManager.measureX methods are used. You can measure the scroll view and its content view. If you are using a ListView you will need to write your own ListView that measures the height of every single row to compute the content size.

**Comment by bdeezz** [comment]
Where do you call the scrollTo method?

**Comment by ide** [comment]
@bdeezz, something like:

```js
render() {
  return <ScrollView ref="scrollView" />;
}

onSomeEvent() {
  this.refs.scrollView.scrollTo(0); // will scroll to the top at y-position 0
}
```

**Comment by Obooman** [comment]
@wangzhe1995  [Scroll to bottom of ScrollView in React Native](http://stackoverflow.com/questions/33049731/scroll-to-bottom-of-scrollview-in-react-native) see this .

**Comment by winterbe** [comment]
I came up with [this solution](https://github.com/facebook/react-native/issues/8003).

**Comment by yzsolo** [comment]
there is a component for listView to scroll to top, hope it is uesful to someone: [scrolltotop](https://www.npmjs.com/package/react-native-scrolltotop)

**Comment by rbndg** [comment]
One way is to perform a transform on the ScrollView and the inner elements.
This allows you to to use the  scrollTo(0) function

`
<View ref="container"
  style={{transform: [{rotate: '180deg'}] }} >
>
<ScrollView/>
</View>

`

**Comment by fritx** [comment]
Try this out: https://github.com/fritx/react-native-auto-scroll

![image](https://cloud.githubusercontent.com/assets/6647633/19101767/80015504-8afd-11e6-937b-bb33740fd509.png)

**Comment by VladPolynko** [comment]
Try this:
<ScrollView ref="scrollView"
            onContentSizeChange={(width,height) => this.refs.scrollView.scrollTo({y:height})}>
</ScrollView>

**Comment by septemptus** [comment]
@VladPolynko this seems to work fine for me on Android, but on iOS it scrolls below the ScrollView content (as if there was no lower boundary for the ScrollView) (RN 0.38.0)

**Comment by mkdotcom** [comment]
Same issue than @septemptus

**Comment by stevenyap** [comment]
Same issue as @septemptus 
ScrollView in iOS has no lower boundary and gives a bigger height.
My shortcut is to give a manual offset for iOS-only.

**Comment by mstmustisnt** [comment]
https://facebook.github.io/react-native/docs/scrollview.html#scrolltoend

**Comment by jwebcat** [comment]
scrolltoend method still scrolls past the end of the ScrollView on IOS.

**Comment by nickgrealy** [comment]
This solved it for me...
https://stackoverflow.com/questions/29310553/is-it-possible-to-keep-a-scrollview-scrolled-to-the-bottom

**Comment by sturmenta** [comment]
<ScrollView ref={ref => this.scrollView = ref}>

onSomeEvent = () => {
  this.scrollView.scrollTo({ x: 0});
}

This worksssss
