### ISSUE TITLE
[WebView] cannot load url with utf symbols 

### ISSUE THREAD

**Issue by skv-headless** [facebook/react-native#914]
I'm trying to open https://ru.wikipedia.org/wiki/Заглавная_страница page and it fails. To fix that I make encodeURI before passing to WebView. Maybe it is possible to do it inside WebView component.

**Comment by brentvatne** [comment]
@skv-headless - could you send over a pull request with that change?

**Comment by nicklockwood** [comment]
This should probably be handled inside [RCTConvert NSURL:], however we tried that before and ran into problems where the @2x suffix on images URLs was being double-encoded.

This is on my radar to fix, but it requires some care since it potentially affects many different components.

**Comment by brentvatne** [comment]
@nicklockwood - #1069 is a dup of this with some extra info:

@paramaggarwal 
> Yes, the issue is a duplicate, but this one causes a full app crash, so we need a nil check on cacheKey till a proper fix is in place.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tadeuzagallo** [comment]
@nicklockwood is it still an issue?

**Comment by nicklockwood** [comment]
I believe it's fixed
