### ISSUE TITLE
JSON Streaming in React Native?

### ISSUE THREAD

**Issue by ambarc** [facebook/react-native#9140]
Hello,

What would be the analog of JSONStreams in Node in React Native land? I'm dealing with a JSON stream that isn't Web Sockets based but needs to stay open and listen.

We've tested out a Node centric solution using the JSONStreams package but that doesn't translate into React Native due to platform issues.

https://www.npmjs.com/package/JSONStream

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow
