### ISSUE TITLE
Webview loading state (renderLoading) is never shown

### ISSUE THREAD

**Issue by ustun** [facebook/react-native#915]
Looks like WebViewState is never set to loading, hence the renderLoading function is never executed.

**Comment by Benmidi** [comment]
Add this attribute to your <WebView> tag: startInLoadingState={true}

**Comment by mjw56** [comment]
:+1:

**Comment by brentvatne** [comment]
@Benmidi's comment is completely correct :smile:

**Comment by walterwhite007** [comment]
Hi @brentvatne - Is it possible to show the webview as the page loads? Right now the webview loads for a long time(a spinner) and displays the finally rendered content at the end. If there is a way we could show the webview partially loaded content as the page loads the data the end user will atleast get a feel that the view is loading the web page. I tried different options given in the WebView documentation but none seems to help. Following is the code I am using for your reference.

         <WebView
           source={{uri: this.props.name}}
           startInLoadingState={true}
         />
