### ISSUE TITLE
Freeze and crash of React-Native application after returning from background mode, or switching from another application.

### ISSUE THREAD

**Issue by mobileDevNativeCross** [facebook/react-native#9159]
I use React-Native for IOS and Android, and my application freezes and sometimes crashes after coming back from background mode or switching between the applications. 
The freezing happens on any of the screens and is unpredictable. 
Under the “freezing”, I mean the buttons may not be working for 10 seconds (sometimes more), although ListView and ScrollView respond to the scroll with no holdback. 
After application restart, it works properly.

The application has more than 10 screens, has local AsyncStorage storage, cloud real-time database Firebase (javascript library), PubNub real-time messaging service is activated (javascript library). 
Below is the package. json, in which there are the installed modules.

```
{
  "name": "MyApplication",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "@remobile/react-native-splashscreen": "^1.0.3",
    "firebase": "^2.4.2",
    "firebase-token-generator": "^2.0.0",
    "react": "^0.14.8",
    "react-native": "^0.24.1",
    "react-native-accordion": "^0.2.4",
    "react-native-android-blurryoverlay": "^0.2.2",
    "react-native-blur": "^0.7.11",
    "react-native-button": "^1.4.2",
    "react-native-checkbox-field": "^1.0.6",
    "react-native-collapsible": "^0.6.0",
    "react-native-drawer": "^2.0.0",
    "react-native-extra-dimensions-android": "^0.17.0",
    "react-native-gcm-android": "^0.2.0",
    "react-native-gifted-messenger": "0.1.4",
    "react-native-gifted-spinner": "0.0.3",
    "react-native-image-picker": "^0.20.0",
    "react-native-keyboard-aware-scroll-view": "^0.1.2",
    "react-native-linear-gradient": "^1.5.12",
    "react-native-modalbox": "^1.3.3",
    "react-native-radio-button-classic": "0.0.5",
    "react-native-realtimemessaging-android": "^1.0.6",
    "react-native-router-flux": "^3.22.23",
    "react-native-share": "^1.0.10",
    "react-native-swipeout": "^2.0.12",
    "react-native-system-notification": "^0.1.11"
  }
}
```

Need you assistance with these freezing and crashes. Thank you.

**Comment by jawang35** [comment]
@mobileDevNativeCross Do you know what is producing the freeze? Our team is getting the same issue reported but it is inconsistent I am unable to reproduce it myself.

**Comment by sibelius** [comment]
@mobileDevNativeCross could u share a repo to reproduce this issue?

**Comment by inetfuture** [comment]
As my unstandard, In background, js thread will be suspended, so firebase and pubnub connection will be lost, after resume, there could be a lot to catch up, maybe firebase or pubnub sync blocks js thread?

**Comment by krishbhattacharyya** [comment]
I am facing same issue in my app. 

After login I navigate to main page -> Then minimize the app  or close the app with login state -> after 4 or 5 days kept in this state ( But for the short time this is not happening ) -> then I open the app got the main page -> No data available -> app is crashed when I click another button.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/freeze-and-crash-of-react-native-application-after-returning-from-background-mod-1

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.
