### ISSUE TITLE
Add support for RNPM plugins from packages matching "react-native-*"

### ISSUE THREAD

**Issue by rozele** [facebook/react-native#9168]
RNPM has a recent commit that supports finding plugins from packages named with "react-native-*" (https://github.com/rnpm/rnpm/commit/769b69264f035fe366132df777fab7f6fd3bf03f). We use this feature to ship the `run-windows` command plugin inside the react-native-windows package (https://github.com/ReactWindows/react-native-windows/blob/master/package.json#L41).  Can we apply this commit here as well?

cc @Kureev @grabbou

**Comment by grabbou** [comment]
Already sent as a PR. Thanks for reminding us of cherry-picking changes that happened in the meantime :)
