### ISSUE TITLE
debugger.html - window.require("BatchedBridge")["processBatch"] is undefined

### ISSUE THREAD

**Issue by mjw56** [facebook/react-native#917]
Hi RN team, 

I'm experiencing this issue after upgrading to 0.4.0. I confirmed from one other person in IRC that this is happening to them as well.

The packager will load the app fine, but when the app opens in simulator or on a device, there is only a white screen. When opening chrome dev tools, it will show that there is an error in ```debugger-ui.html``` at line 54: ```Uncaught TypeError: Cannot read property 'apply' of undefined```

```javascript
'executeJSCall:method:arguments:callback:': function(message, sendReply) {
  var returnValue = [[], [], [], [], []];
  try {
    if (window && window.require) {
      // it breaks here
      returnValue = window.require(message.moduleName)[message.moduleMethod].apply(null, message.arguments);
    }
  } finally {
    sendReply(JSON.stringify(returnValue));
  }
}
```
putting a catch there reveals a little more information:
```
TypeError: Cannot read property 'apply' of undefined
    at messageHandlers.executeJSCall:method:arguments:callback: (http://localhost:8081/debugger-ui:54:79)
    at WebSocket.ws.onmessage (http://localhost:8081/debugger-ui:82:5)
```

This is what ```executeJSCall:method:arguments:callback:``` is called with before it breaks:

![image](https://cloud.githubusercontent.com/assets/161528/7217287/543c95b0-e5ee-11e4-8434-d651c8a9251c.png)

I hope this helps. In the meantime I will downgrade to 0.3.11. Let me know if you need anymore info.

**Comment by mjw56** [comment]
When I run this same code in 0.3.11 it looks like it is calling with ```moduleMethod: "callFunctionReturnFlushedQueue"``` instead of ```"processBatch" ```



![image](https://cloud.githubusercontent.com/assets/161528/7217326/afa07a2c-e5f1-11e4-9e51-5c0609c7c1c0.png)

**Comment by frantic** [comment]
Thanks for reporting, I'll take a closer look soon

**Comment by unknownexception** [comment]
Same here. 

Steps to reproduce: 
1. Install react-native-cli@0.4.0 and `react-native init test-app && cd test-app`.
2. Install react-native-icons@latest https://github.com/corymsmith/react-native-icons/
3. Run the app, get white screen + error `Uncaught TypeError: Cannot read property 'apply' of undefined`  in console.

**Comment by mjw56** [comment]
Ok, I have an update. @unknownexception your comment made me suspect it was versions of RN that packages are using.

I have three packages in my app that are dependent on RN:

```
"react-native-navbar"
"react-native-side-menu"
"react-native-video"
```

After installing them locally and pointing them to 0.4.0, my app is working with 0.4.0! :tada: :

**Comment by unknownexception** [comment]
@mjw56, thanks, now it works. I hope npm@3 will help to deduplicate dependencies (it seems `peerDependency` has failed and nobody uses it anymore).

**Comment by mjw56** [comment]
@unknownexception ok great, I'm wondering if there is anything we could do in the meantime to prevent something like this from happening again in the future? @frantic

**Comment by ide** [comment]
Something like peer dependencies (or whatever succeeds it) makes sense. I'll go out on a limb and say all of the React Native modules so far shouldn't specify react-native as a regular dependency. Even if React's native side correctly handles multiple copies of the JS side, it's important to keep the JS bundle small for boot times especially on an iPod touch or 4s.

One way React could guard against this would be to set a global flag when first loaded, and warn/throw if the flag is already set.

**Comment by mjw56** [comment]
@ide so is that the way it is happening now is that multiple copies of RN are being loaded on the device for every module which has RN as a dependency?

**Comment by ide** [comment]
I believe so unless you've run npm dedupe. I haven't looked at an actual JS bundle to verify that though.

**Comment by mjw56** [comment]
So this issue was resolved with either a module declaring a react-native peerDependency or upgrading their react-native version to 0.4.0 for an app using 0.4.0. I am going to close this for now. I'm not sure if something should be added to the docs about this, I'd be happy to send a PR.
