### ISSUE TITLE
No sound is played for local notification after upgrade to 0.30 in iOS

### ISSUE THREAD

**Issue by varungupta85** [facebook/react-native#9181]
No sound is played when a local notification is received after update to `0.30`. This was working fine in `0.24`. I am using `PushNotificationIOS` to schedule local notification in iOS. Has anyone else experienced this problem? I am using a Mac. I just created a new project using `react-native init TestLocalNotification` to make sure there is nothing wrong in my app. I have below code in the `index.ios.js` file. I see the local notification after I click on the `Welcome to React Native` text and then go to home screen by pressing `shift + cmd + h` but no sound is played. I have tried using both default and custom sound.

```
class TestLocalNotification extends Component {
  componentDidMount() {
    PushNotificationIOS.requestPermissions()
  }

  scheduleLocalNotification = () => {
    console.log('Scheduling local notification')
    PushNotificationIOS.scheduleLocalNotification({
      fireDate: Date.now() + 60000,
      alertBody: 'Notificaiton',
      soundName: 'default'
    });
  }

  render() {
    return (
      <TouchableOpacity onPress={this.scheduleLocalNotification}>
        <View style={styles.container}>
          <Text style={styles.welcome}>
            Welcome to React Native!
          </Text>
        </View>
      </TouchableOpacity>
    );
  }
}
```

**Comment by skatpgusskat** [comment]
On simulator, Local Notification's sound often doesn't work. it's a bug. could you try it on your device?

**Comment by npomfret** [comment]
I have sound working, but it doesn't work for a custom sound.  I've debugged it as far as I can - I can see the soundName property being set correctly in RCTConvert (UILocalNotification), and I've tested that my mp3 file is available as a resource - but it always plays the default sound, and never the custom sound.

**Comment by lacker** [comment]
The two bug reports here seem different because one is saying there's no sound and the other is saying it uses the default sound. Since there was no answer to the first question I think the original bug is blocked on investigation here so I am going to close this issue. If people run into similar problems then I suggest opening new issues for them. Thanks folks!
