### ISSUE TITLE
ToolbarAndroid's actions is disappear

### ISSUE THREAD

**Issue by Gmonking** [facebook/react-native#9183]
TextInput is focus and ToolbarAndroid's actions is disappear when I setState

**Comment by DanielMSchmidt** [comment]
Could you please explain the problem a bit more? A [RNPlay](https://rnplay.org/) snippet would help here. In addition this is a problem which should be posted to [StackOverflow](http://stackoverflow.com/), as it seems to be more of a programming problem than one with react-native itself.

**Comment by jaystramel** [comment]
I wrote up a similar (maybe the same) issue here:  https://github.com/facebook/react-native/issues/11209
