### ISSUE TITLE
Support libraries location changed

### ISSUE THREAD

**Issue by jcampbell05** [facebook/react-native#9189]
the support libraries have moved location and thus react native deosn't compile:

React Native looks in the `.m2` folder but android still stores them in `libraries`

Creating a symlink fixes this.

**Comment by hramos** [comment]
Can you add a bit more context? Is there something specific we should do to fix this?

**Comment by jcampbell05** [comment]
This was due to there being mutiple android SDKs and one was older due to Genymotion installing its own
