### ISSUE TITLE
Unit tests not enabled and failing cases DependencyGraph-test

### ISSUE THREAD

**Issue by bartolkaruza** [facebook/react-native#9192]
@davidaurelio I was working on a proposed change on node-haste and the package server. You moved node-haste to the react-native repo a few days ago, which makes it a lot easier for that particular development flow ( thanks 👍 ).

Running the unit tests in node-haste DependencyGraph-test I noticed most of them are skipped. This is because of ```fdescribe``` at line 6038

I noticed that fdescribe was making two failing unit tests be skipped:
```
● DependencyGraph › get sync dependencies (win32) › it should work with absolute paths
```
and
```
● DependencyGraph › get sync dependencies (win32) › it should get dependencies
```

I'm not sure if they are critical, but I thought I would let you know in case this accidentally ships. 

@deepaksisodiya

**Comment by davidaurelio** [comment]
thanks for bringing it up – we fixed it in 13994d5810519c9fc08f892bcf625d2fb0c633a1
