### ISSUE TITLE
issue setting source and height/width at the same time

### ISSUE THREAD

**Issue by jcharbo** [facebook/react-native#9193]
Hi, when I change the Image source and height/width  style attributes at the same time the image doesn't always refresh.  The loadstart event fires each time but loadend doesn't fire.  My state object has source,height, and width and my image control looks like so:   `<Image source={this.state.coverImage} resizeMode='stretch' style={{width:this.state.coverImageDisplayWidth, height:this.state.coverImageDisplayHeight}} />`

If I change all 3 state properties at once the image does not refresh.  If I change only the source it refreshes or if I set the source to null and then set the three properties it works.  Please advise.
thanks

**Comment by skatpgusskat** [comment]
I tested it, but work well. could you tell me your RN version, and show your full code?

**Comment by jcharbo** [comment]
I'm on 29.1.  The code is below.  It uses react-native-image-picker to look up the image.  I added a comment above the line that I'm using as a workaround.  If you do not set coverImage to null then the problem occurs more than half of the time.

`import React, { Component } from 'react';
import { View, Navigator, Dimensions, TextInput, Image, ScrollView, TouchableOpacity, StyleSheet, Text } from 'react-native';
import ImagePicker from 'react-native-image-picker';
var Platform = require('react-native').Platform;


var full_width = Dimensions.get('window').width; //full width
var full_height = Dimensions.get('window').height; //full width


export default class CreateJump extends Component {
    constructor(props){
        super(props)
        this.state = {
            overlayOpacity:.8,
            coverImage:require('../image/photo5.png'),
            coverImageDisplayHeight:300,
            coverImageDisplayWidth:full_width
        }
    }

    coverImage(){
        return(
            <View style={{flex:1,alignItems:'center'}}>
                <Image source={this.state.coverImage} resizeMode='stretch' style={{width:this.state.coverImageDisplayWidth, height:this.state.coverImageDisplayHeight}} >
                        <View style={{justifyContent:'center', alignItems:'center'}}>
                            <TouchableOpacity>
                                <Text style={{marginTop:this.state.coverImageDisplayHeight/2,color:'white'}} onPress={() => this.selectImage()}>{(this.state.overlayOpacity==0?'Change':'Add')} Cover Photo</Text>
                            </TouchableOpacity>
                        </View>
                </Image>
            </View>

        )
    }

    selectImage(){
        ImagePicker.showImagePicker({}, (response) => {
            console.log('Response = ', response);

            if (response.didCancel) {
                console.log('User cancelled image picker');
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            }
            else {
                var source;
                if (Platform.OS === 'ios') {
                    source = {uri: response.uri.replace('file://', ''), isStatic: true};
                } else {
                    source = {uri: response.uri, isStatic: true};
                }
                var displayHeight,displayWidth;
                if(response.width>response.height){
                    displayWidth=full_width;
                    displayHeight=parseInt((displayWidth/response.width)*response.height);
                }
                else{
                    displayHeight=300;
                    displayWidth=parseInt((displayHeight/response.height)*response.width);
                }

//if you remove the following setstate code then the image will not refresh properly the majority of the time
                this.setState({
                    coverImage: null,
                });

                this.setState({
                    coverImage: source,
                    coverImageHeight:response.height,
                    coverImageWidth:response.width,
                    coverImageDisplayHeight:displayHeight,
                    coverImageDisplayWidth:displayWidth,
                    overlayOpacity:0
                });
            }
        });
    }

    render() {
        return(
        <ScrollView style={styles.tabView} horizontal={false}>
            <View>
                {this.coverImage()}
            </View>

        </ScrollView>
        );
    }


}
    const styles = StyleSheet.create({
        tabView: {
            flex: 1,
            backgroundColor:'#fff'

        },

    });
`

**Comment by skatpgusskat** [comment]
@jcharbo It's seem local image. I tested with online image. Anyway, The PR #9137 is about this.

**Comment by jcharbo** [comment]
thanks

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/issue-setting-source-and-heightwidth-at-the-same-time

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
