### ISSUE TITLE
ListView does not render correctly when row moved to above the current scroll position

### ISSUE THREAD

**Issue by ghuh** [facebook/react-native#9200]
For a ListView with multiple headers and enough data to scroll, if the list is scrolled to the bottom and an item is added at the top (above the viewable area), then the ListView renders rows and headers on top of each other (or sometimes just really close to each other).  Also, there will be empty spaces where presumably one of those rows/headers belong.

Note that if you modify the example to either have 1 header or use cloneWithRows with no headers, the problem seems to go away.

This was not a problem in RN 0.25.1 but is a problem as of v0.31.0-rc.0.  I tested on iPhone 6s, both simulator and real device.

To reproduce, run the following code on an iPhone 6s, scroll all the way to the bottom, and click on a row near the bottom, then scroll back up and feast your eyes on the disaster.  For best results, click on a few rows.

``` javascript
componentWillMount: function() {
        this._listData = {
            "header 1": [
              "item 1",
              "item 2",
              "item 3",
              "item 4",
              "item 5",
              "item 6",
              "item 7",
              "item 8",
              "item 9",
              "item 10",
              "item 11",
              "item 12",
              "item 13",
              "item 14",
              "item 15",
              "item 16",
              "item 17",
              "item 18",
              "item 19",
              "item 20",
              "item 21",
              "item 22",
              "item 23",
              "item 24",
              "item 25",
              "item 26",
              "item 27",
              "item 28",
              "item 29",
            ],
            "header 2": [
              "item 30",
              "item 31",
              "item 32",
              "item 33",
              "item 34",
              "item 35",
              "item 36",
              "item 37",
              "item 38",
              "item 39",
              "item 40",
              "item 41",
              "item 42",
              "item 43",
              "item 44",
              "item 45",
              "item 46",
              "item 47",
              "item 48",
              "item 49",
              "item 50",
              "item 51",
              "item 52",
              "item 53",
              "item 54",
              "item 55",
              "item 56",
              "item 57",
              "item 58",
              "item 59",
            ],
        }
},

getInitalState: function() {
        return {
            ds: new ListView.DataSource( {
                        rowHasChanged: (r1, r2) => r1 !== r2,
                        sectionHeaderHasChanged: (s1, s2) => s1 !== s2
                        }
            ).cloneWithRowsAndSections(
                this._listData
            ),
        };
},

render: function() {
        return (
            <ListView
                dataSource = { this.state.ds }
                renderRow = {
                    ( rowData, sectionId, rowId, highlightRow ) =>
                    {
                        return (
                            <Text
                                onPress = {
                                    () => {
                                        this._listData = JSON.parse( JSON.stringify( this._listData ) );

                                        this._listData[sectionId].splice( rowId, 1 );

                                        let newSection = Object.keys( this._listData )[ 0 ];

                                        this._listData[newSection].unshift( rowData );

                                        this.setState(
                                            {
                                                ds: this.state.ds.cloneWithRowsAndSections( this._listData )
                                            }
                                        );
                                    }
                                }
                                style = {{padding:8}}
                            >
                                { rowData }
                            </Text>
                        );

                    }
                }
                renderSectionHeader = { ( sectionData, sectionId ) => { return ( <Text> { "HEADER:" + sectionId } </Text>) } }
            />
        );
},
```

**Comment by sharq1** [comment]
+1
I don't know exactly on which RN version this started happening, but I noticed it a few releases ago (about RN0.27) and it's happening until now. It end's up rendering like on below screenshot. Happens every time on simulator and real devices.
![image](https://cloud.githubusercontent.com/assets/1241239/18203797/848e1164-7119-11e6-86ab-79ba731bcf34.png)
Usually it rerenders nearly correctly upon scrolling the listview just a little bit (still some zIndex - like issues are visible).

Using section headers and refreshControl.

**Comment by sharq1** [comment]
When debugging ListView/ScrollView components led me nowhere I decided to hack around the problem.
One way that worked was switching scroll component on `renderScrollComponent` attribute with each change that would led to rendering error. This forced redraw of the whole list.

But the _not-so-hacky_ workaround is to scroll to the top of the list before actually modifying it, like so:
```
  componentWillReceiveProps(props) {
    this.refs.listview.scrollTo({y: 0})
    this._updateDataSource(props)
  }
```

**Comment by sharq1** [comment]
Despite the fix section headers break when in conjunction with RefreshControl:

![screencast 2016-10-10 10-19-43](https://cloud.githubusercontent.com/assets/1241239/19230158/3beacfce-8ed3-11e6-80a3-945c0481f2e1.gif)

**Comment by kevinnguy** [comment]
@sharq1 your workaround with scrolling the listview to the top worked! I hope this issue can be resolved in a cleaner way.

**Comment by nicholeuf** [comment]
Scrolling above the content is a good workaround, but any idea when this will be fixed?

**Comment by L-Jovi** [comment]
+1 , how about progress now?  I use RN 0.37

**Comment by JensDebergh** [comment]
We are experiencing similar issues even on `ListView` without the section headers.

This issue mostly occurs when trying to prepend data to the existing dataset.
Scrolling to to before prepending the data does not fix it for us.

Any ideas? 👍

**Comment by L-Jovi** [comment]
I find that temporary method to resolve this issue, put your ListView component inner the ScrollView, whatever you scroll and change the row, the render works well.

hope make sense and could help people who encounter here.

**Comment by hramos** [comment]
Closing as ListView is deprecated in 0.43. Use FlatList.
