### ISSUE TITLE
WebView Bug Report

### ISSUE THREAD

**Issue by willsuwei** [facebook/react-native#9201]
I found WebView has a bug which will affect both iOS and Android. It might be important because I believe this is the reason why we cannot use it to login to neither Google nor Live account.
Here is the detail.
If there is an onNavigationStateChange function, which is similar to the following, then we will get redundant rendering call and http request.

```
  onNavigationStateChange: function(navState) {
    this.setState({
      backButtonEnabled: navState.canGoBack,
      forwardButtonEnabled: navState.canGoForward,
      url: navState.url,
      status: navState.title,
      loading: navState.loading,
      scalesPageToFit: true
    });
  },
```

I created a test website by using NetBeans. the Following code is from index.html:

```
<html>
    <head>
        <title>Simple Post</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <form action = "Confirm" method = "GET">
            <input type ="text" name="info" value="GET information">
            <input type="submit" value="Submit">
        </form>
        <form action = "Confirm" method = "POST">
            <input type ="text" name="info" value="POST information">
            <input type="submit" value="Submit">
        </form>
    </body>
</html>
```

And the following code is from Confirm.java:

```
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        System.out.println("Servlet was called! Information: " + request.getParameter("info"));
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet Confirm</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>The Information: " + request.getParameter("info") + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        System.out.println("Method: Get");
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        System.out.println("Method: Post");
        processRequest(request, response);
    }
```

If I submit the form which is using GET method, then the page will be redirect with no problem.
Console output:
  -Info:   Method: Get
  -Info:   Servlet was called! Information: GET information

But when submitting the form which is using POST method, then WebView will firstly send a correct Post request and then followed by a weird Get request.
Console output:
  -Info:   Method: Post
  -Info:   Servlet was called! Information: POST information
  -Info:   Method: Get
  -Info:   Servlet was called! Information: null

A quick and temporary fix for this bug is to delete onNavigationStateChange function. But I hope React Native can fix that redundant call officially on the next update.

**Comment by willsuwei** [comment]
I found WebView has a bug which will affect both iOS and Android. It might be important because I believe this is the reason why we cannot use it to login to neither Google nor Live account.
Here is the detail.
If there is an onNavigationStateChange function, which is similar to the following, then we will get redundant rendering call and http request.
```
  onNavigationStateChange: function(navState) {
    this.setState({
      backButtonEnabled: navState.canGoBack,
      forwardButtonEnabled: navState.canGoForward,
      url: navState.url,
      status: navState.title,
      loading: navState.loading,
      scalesPageToFit: true
    });
  },
```
I created a test website by using NetBeans. the Following code is from index.html:
```
<html>
    <head>
        <title>Simple Post</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <form action = "Confirm" method = "GET">
            <input type ="text" name="info" value="GET information">
            <input type="submit" value="Submit">
        </form>
        <form action = "Confirm" method = "POST">
            <input type ="text" name="info" value="POST information">
            <input type="submit" value="Submit">
        </form>
    </body>
</html>
```
And the following code is from Confirm.java:
```
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        System.out.println("Servlet was called! Information: " + request.getParameter("info"));
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet Confirm</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>The Information: " + request.getParameter("info") + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        System.out.println("Method: Get");
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        System.out.println("Method: Post");
        processRequest(request, response);
    }
```
If I submit the form which is using GET method, then the page will be redirect with no problem.
Console output:
  -Info:   Method: Get
  -Info:   Servlet was called! Information: GET information

But when submitting the form which is using POST method, then WebView will firstly send a correct Post request and then followed by a weird Get request.
Console output:
  -Info:   Method: Post
  -Info:   Servlet was called! Information: POST information
  -Info:   Method: Get
  -Info:   Servlet was called! Information: null

A quick and temporary fix for this bug is to delete onNavigationStateChange function. But I hope React Native can fix that redundant call officially on the next update.

**Comment by satya164** [comment]
Would be awesome if you can send a PR to fix this

**Comment by eamonpenland** [comment]
any update on this? I'm having an issue with following server redirects for an oauth2 login flow. I keep getting an issue with ssl errors however im hitting the endpoint with ssl enabled on heroku.

![screen shot 2016-09-14 at 2 29 06 pm](https://cloud.githubusercontent.com/assets/3287982/18524761/d64ec7a6-7a87-11e6-930c-db0bee76e406.png)


Couldn't find anything online to help me out either

**Comment by lacker** [comment]
I think this issue is stale + a dupe so I am going to close it.

**Comment by unicornRainbows** [comment]
Why the F??? It does work now.. at least :)
