### ISSUE TITLE
Android app crashes when geolocation permission is not given

### ISSUE THREAD

**Issue by calclavia** [facebook/react-native#9202]
Using React Native v0.30

It seems like React Native apps will crash when geolocation permission is revoked on Android API 23. I tested this by setting targetSdkVersion to 16, and this allowed the app to work even with geolocation permission revoked. It would be great if we can target API level 23, but instead of having the app crash, simply cause the navigator.geolocation to return an error like it does in API level 16. That way the app itself can decide how to tell the user to enable geolocation rather than crashing without an error message.

To replicate, create a React Native app that requires Android permission, and set the target SDK version to 23. Revoke the geolocation permission when prompted (or through Application Manager). The app will crash upon launch.

**Comment by satya164** [comment]
Would be awesome if you can send a PR to migrate to new permissions model.

Refer https://github.com/facebook/react-native/commit/b7352b46671d09471d6aa9355ea41368ea05df96 to see how to use the permissions module.

**Comment by alexHlebnikov** [comment]
Same problem here. 
I'm using RN PermissionsAndroid and if users denies geolocation request in modal, the app crashes. 

I'm on RN 0.33.0.RC.0.

**Comment by calclavia** [comment]
Update: Happens pm RN 0.33 as well. Can confirm

**Comment by calclavia** [comment]
Seems like method described in https://facebook.github.io/react-native/docs/permissionsandroid.html works well.
