### ISSUE TITLE
accessing system sound API

### ISSUE THREAD

**Issue by love4shen** [facebook/react-native#9212]
I am working on an alarm clock app. I want the device to vibrate and play sound when the time is up. The `Vibration`/`VibrationIOS` API is officially available. However I could not find an API for accessing system sound, for example, the ringtone when a call comes in, or the default alarm sound. I do find a few package that can play sound file, but what I want is just a few system default sound clips that I can specify the names, maybe just like the `sound` property in `aps` in `PushNotificationIOS` (I apologize if I misuse this API as an example, I haven't used it yet, just scan through the docs)?

If there isn't a way right now, will this be part of official APIs in the future, or it's not on the plan?

**Comment by jacobp100** [comment]
https://react.parts/native?search=sound

**Comment by ide** [comment]
You should write your own sound module or look for an existing one e.g. where jacobp100 suggested.

**Comment by maxsdev** [comment]
Useless comments ever.
