### ISSUE TITLE
NavigationExperimental is missing willfocus and didfocus events

### ISSUE THREAD

**Issue by ng-marcus** [facebook/react-native#9214]
Using React 0.31 branch NavigationExperimental is working well, but it seems to be missing some lifecycle events.

In particular, I need to know when the transition between scenes has finished, as componentDidMount is called at the start of the transition, and I want to display a modal and do some compute intensive work once the transition has completed.   

The old Navigator has willFocus and didFocus events.

**Comment by ryankask** [comment]
The events you're looking for are available on `NavigationTransitioner`: https://github.com/facebook/react-native/blob/0.31-stable/Libraries/NavigationExperimental/NavigationTransitioner.js#L37

They are `onTransitionStart` and `onTransitionEnd`. Are you using `NavigationCardStack`? Those props aren't exposed on that component. I've seen a few issues about that so perhaps they should. It would be a simple feature to add.

If you're mainly looking to do some expensive work after the transition has happened, you can use `InteractionManager.runAfterInteractions` in `componentDidMount` (https://facebook.github.io/react-native/docs/interactionmanager.html).

There's some more information here: https://facebook.github.io/react-native/docs/performance.html#slow-navigator-transitions

Does this help?

**Comment by ng-marcus** [comment]
I am using NavigationCardStack but wrapping the call in  runAfterInteractions did the trick!  I use that throughout my app but didn't think to use it in componentDidMount.

It helps a lot, thanks!

**Comment by arilitan** [comment]
I am using NavigationCardStack as well, I am having an issue with slow animations once the components are already mounted. I want to delay the render of the scenes until the navigator transition is completed. Would be ideal to expose the onTransitionStart and onTransitionEnd callbacks, anyone find a way around this?

**Comment by simonsmith** [comment]
I think this issue should be re-opened. I think it's very common to want to know when a component has been rendered again as part of a navigation event. Right now I can navigate to a component, go to another and then press back but have no way to know that same component has rendered again. It's at that point I might wish to refresh some data for example.

Is this something that `onTransitionStart`/`End` would allow? If so I'll open a separate issue.

**Comment by arilitan** [comment]
@simonsmith I was able to effectively control this by having my navigator component listen for changes in the navigation states. I'm using redux and whenever the navigation state changes i set a transitioning flag on the navigator state that gets passed into the scenes as as a prop. When the interaction manager is finished transitioning i reset the flag. On each scene that is being rendered, I check in shouldComponentUpdate if the transitioning flag if set, and if so the function returns false.

here is example code from my Navigator component

```  componentWillReceiveProps(nextProps){
    if(!_.isEqual(this.props.navigationState, nextProps.navigationState || this.props.tab !== nextProps.tab)) {
      this.setState({transitioning: true})
      InteractionManager.runAfterInteractions(() => {
        this.setState({transitioning: false})
      })
    }
  }

  render() {
    const { navigationState } = this.props
    const direction = _.last(this.props.navigationState.routes).type === 'swishStoryViewer' ? 'vertical' : 'horizontal'
    return (
      <NavigationCardStack
        navigationState={navigationState}
        onNavigateBack={this.props.pop}
        style={styles.container}
        cardStyle={styles.cardStyle}
        direction={direction}
        enableGestures={false}
        renderScene={this._renderScene}/>
    )
  }```

In renderScene the transitioning state is passed as a prop to the scene.

In the scene components:

```  shouldComponentUpdate(nextProps){
    return !nextProps.navigator.transitioning
  }```

**Comment by simonsmith** [comment]
@arilitan Thanks for sharing.

So does this allow you to know when an individual component has been transitioned to? This looks like it just doesn't call render when a transition is happening. Perhaps similar to this? - https://github.com/facebook/react-native/issues/7720#issuecomment-246168997

I effectively need a `componentDidNavigate` or something, which would keep firing even after it has been mounted.

**Comment by arilitan** [comment]
@simonsmith you can accomplish this using redux and having the individual component listen for changes in your navigation state. Whenever a new route is pushed, i create a unique key for it in the action creator. That key is then transferred to the component as a prop in the renderScene function. In the redux selector (mapStateToProps) I check if the last route of the navigation state has the same key as the component itself (and in my case if the active tabs are the same as well) if true you know that screen is active. To know exactly when it becomes active ie `componentDidNavigate` you can check in `componentDidReceivesProps` when this flag changes from false to true. 

Here is my selector function to check if a given component is in focus:

```
const isFocusedSelector = createSelector(
  [
    navigationRoutesSelector,
    navigationTabsSelector,
    (state: any, props: {navigator: navigatorProps}) =>  props.navigator.key,
    (state: any, props: {navigator: navigatorProps}) =>  props.navigator.tab,
  ],
  (navigationState, tabState, key, tab) => {
    const selectedTab = tabState.routes[tabState.index].key
    const focusedKey = _.last(navigationState).key
    return key === focusedKey && tab === selectedTab 
  }
)
```

**Comment by simonsmith** [comment]
I see, okay. I was thinking of using the `isActive` property in `sceneProps` object. Seen here - https://github.com/facebook/react-native/blob/a76547f7ac16a7a648d65f80655cee6ac84c365f/Libraries/NavigationExperimental/NavigationTypeDefinition.js#L44-L50

It would need to be passed into the components in the `renderScene` method, but it seems fairly reliable. Only issue I have with that is components are rendered twice but I think that issue I linked to has a way round it.

Thanks again for sharing
