### ISSUE TITLE
IOSPicker Children Bug

### ISSUE THREAD

**Issue by nickzuber** [facebook/react-native#9216]
#### React-Native v0.20.0^

Question regarding intended behavior for the `IOSPicker` component. 

The picker component assumes that its children are all React elements and does not do any sort of check when attempting to read children properties.

[Source code I'm referring to:](https://github.com/facebook/react-native/blob/a2fb703bbb988038323c55b29b40e8f5ff52966d/Libraries/Components/Picker/PickerIOS.ios.js#L48-L53)

```js
ReactChildren.forEach(props.children, function (child, index) {
  if (child.props.value === props.selectedValue) {
    selectedIndex = index;
  }
  items.push({value: child.props.value, label: child.props.label});
});
```

The important thing to look at is `child.props.value` -- this assumes that a child element has a `props` property and checks its _value_ which will throw an error if `props` doesn't exist.

This prevents us from performing lazy evaluations on `Picker` children:

```jsx
<Picker ...>
  {someFalseCondition &&
    <Picker.Item label="conditionalOption" value="0" />
  }
  <Picker.Item label="option1" value="1" />
  <Picker.Item label="option2" value="2" />
  ...
</Picker>
```

Since `someFalseCondition` will return `false`, we end up with:

```jsx
<Picker ...>
  {false}
  <Picker.Item label="option1" value="1" />
  <Picker.Item label="option2" value="2" />
  ...
</Picker>
```

Which will throw an error since the `Picker` component assumes _all_ of the children have properties. 

Is this intended behavior? Seems like a bug to me.. I feel like we should be able to do things like this. If this is a bug, I'll gladly make a PR to fix this issue.

[RN playground example](https://rnplay.org/apps/3UXQRA)

![screen shot 2016-08-04 at 12 07 06 pm](https://cloud.githubusercontent.com/assets/10540865/17409171/093206c2-5a3c-11e6-99f1-60543fcc805c.png)

**Comment by fragno** [comment]
I think u should do like this.
```js
<Picker ...>
  {someFalseCondition ? (
    <Picker.Item label="conditionalOption" value="0" />) : null
  }
  <Picker.Item label="option1" value="1" />
  <Picker.Item label="option2" value="2" />
  ...
</Picker>
```

**Comment by nickzuber** [comment]
@fragno That won't work either -- the whole point is that the `Picker` component _assumes_ its children is a valid React component. It doesn't matter if we return `false`, `null`, or `undefined`, it will still throw an error.

```js
child.props.value

// translates to...

null.props.value // still throws error
```
