### ISSUE TITLE
iOS simulator: assertion failed (various other errors)

### ISSUE THREAD

**Issue by derdav3** [facebook/react-native#9218]
Somehow I managed to break it.. If I create the sample app, run it on the simulator and log-ios I get plenty of error messages. The project still compiles, but this can't be good 😏 

excerpt:

```
Aug  4 21:02:51 Davids-iMac assertiond[79149] <Error>: assertion failed: 16A254g 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Aug  4 21:02:51 Davids-iMac Unknown[79149] <Error>: 
Aug  4 21:02:51 Davids-iMac assertiond[79149] <Error>: assertion failed: 16A254g 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Aug  4 21:02:51 Davids-iMac Unknown[79149] <Error>: 
Aug  4 21:04:01 Davids-iMac routined[79135] <Error>: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104
```

 My version of rn:
react-native-cli: 1.0.0
react-native: 0.30.0

I've tried running it with react-native start -- -reset-cache, tried different simulators.. no luck yet
- [x] Are you using Mac, Linux or Windows?
  -Mac

appreciate any tips!
thanks

**Comment by herve1976** [comment]
I have the same issue and the compilation takes for ever because of this.

**Comment by FMCorz** [comment]
Same.

```
$react-native -v
react-native-cli: 1.0.0
react-native: 0.29.2
```

**Comment by zeffon** [comment]
The same for me 
My version of rn:
react-native-cli: 1.0.0
react-native: 0.31.0

**Comment by AugustoL** [comment]
Same Here. RN 0.30

**Comment by cyphire** [comment]
Me as well..

**Comment by uronly14me** [comment]
Same here!

``
react-native-cli: 1.0.0
react-native: 0.32.0

**Comment by GentryRiggen** [comment]
Samsies

react-native-cli: 1.0.0
react-native: 0.32.0

**Comment by GentryRiggen** [comment]
Hey Team,
I was able to get this to work for me. I had the Xcode-Beta 8v6 installed and I believe it switched my 'iOS Deployment Target' to '10'.

Open up Xcode 7 and change the 'iOS Deployment Target' to '9.3' ('Info' tab of your project) and go ahead and run the app. You should now be able to go back and use `react-native run-iso` again from the terminal.

Stay native my friends,
Gentry

**Comment by sathyakumarseshachalam** [comment]
Same here. I am not able to find 'iOS Deployment Target' in info tab of Xcode either

**Comment by vovkasm** [comment]
@GentryRiggen don't know as for Xcode 8, but for Xcode 7 setting target to 9.3 don't fix the problem.

react-native: 0.34.1

Seems like this related to animations or input handling. (Assertions occurs when react-native-button clicked, when tabs on TabBarIOS clicked, etc...)

**Comment by silesky** [comment]
react-native-cli: 1.0.0
react-native: 0.36.0

the `127.0.0.1 localhost` hack does not fix the issue. My code compiles, but it  makes my log file hard to read. I can't say that it affects app performance.

**Comment by lucianomlima** [comment]
Same for me. My apps runs from CLI but don't run in Xcode.

react-native: 0.39.2
react-native-cli: 2.0.0

**Comment by idrougge** [comment]
Example app starts with `react-native run-ios`  but every time a `TouchableHighlight` is clicked, `log-ios` reports:
`Feb  7 17:01:38 Iggys-MacBook-Air Unknown[63820] <Error>: 
Feb  7 17:01:38 Iggys-MacBook-Air assertiond[63820] <Error>: assertion failed: 15F34 13A344: assertiond + 12188 [93893311-6962-33A7-A734-E36F946D8EBA]: 0x1`
as well as:
`Feb  7 17:01:49 Iggys-MacBook-Air CoreSimulatorBridge[63824] <Warning>: Pasteboard change listener callback port <NSMachPort: 0x7faeb2707b60> registered`

react-native: 0.41.2
react-native-cli: 2.0.1

**Comment by steveliles** [comment]
@idrougge ...

```Feb 14 10:42:01 localhost CoreSimulatorBridge[6978] <Warning>: Pasteboard change listener callback port <NSMachPort: 0x7fbd07c0a390> registered```

... seems to be caused by connecting to log-ios - it is always the most recent message immediately after i connect.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/ios-simulator-assertion-failed-various-other-errors

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.

**Comment by JooLuiz** [comment]
Same here, my RN version is:
react-native-cli: 2.0.1
react-native: 0.52.2
