### ISSUE TITLE
RCTJSONStringify() encountered the following error: Invalid type in JSON write (__NSGlobalBlock__)

### ISSUE THREAD

**Issue by huangqiaobo** [facebook/react-native#9227]
I want to send a oc block to RN when create the rootView
```
NSMutableDictionary *props = [NSMutableDictionary dictionary];

AnyBlock block = ^() {
NSLog(@"block");
};

[props setObject:event forKey:@"block"];

RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:[JOReactNativeManager sharedInstance].bridge moduleName:moduleName initialProperties:props];
````
then I see the error
RCTJSONStringify() encountered the following error: Invalid type in JSON write (__NSGlobalBlock__)
is there anyway to send a block to RN module when creating rootView ?

**Comment by huangqiaobo** [comment]
I find that, if i stop remote js debugging, the code work fine and i can run the block in js side.
but if i start debug js remotely, it will run to _RCTJSONStringifyNoRetry function and crash in
`    NSData *jsonData = [NSJSONSerialization
                        dataWithJSONObject:jsonObject options:(NSJSONWritingOptions)NSJSONReadingAllowFragments
                        error:error];`
because there is a block in jsonObject

**Comment by ide** [comment]
All values must be JSON-serializable if you want to send them to JS so sending blocks is not supported.

**Comment by huangqiaobo** [comment]
@ide 
But, if I stop remote js debugging, I can send blocks to JS successful.
I think the RCTWebSocket is not support sending blocks to JS, but react native is support.

The _RCTJSONStringifyNoRetry function is in RCTWebSocket. If I stop remote js debugging, It will never run into this function and will not crash;

I think it is a bug of RCTWebSocket;

**Comment by huangqiaobo** [comment]
@ide 
if i stop remote js debugging
![qq20160816-1](https://cloud.githubusercontent.com/assets/8543985/17687193/afb6d32a-63a5-11e6-913d-5ac88f9c56d8.png)
![qq20160816-2](https://cloud.githubusercontent.com/assets/8543985/17687195/b10230b2-63a5-11e6-92c9-da7ba0cd9303.png)
![qq20160816-3](https://cloud.githubusercontent.com/assets/8543985/17687196/b5f838fa-63a5-11e6-8255-af41da6ceaad.png)
![qq20160816-4](https://cloud.githubusercontent.com/assets/8543985/17687218/d482f116-63a5-11e6-8301-62d1a2764f74.png)

works fine !

If I start debug js remotely , send block to JS failed
![qq20160816-5](https://cloud.githubusercontent.com/assets/8543985/17687287/5893c7e6-63a6-11e6-89c2-f03887a7192f.png)

**Comment by ide** [comment]
The JavaScriptCore API has special support for blocks but synchronous calls from the remote JS VM are not supported -- the VM is running on a different computer and uses async WebSockets. Sending Obj-C blocks across computers is simply not supported.

**Comment by huangqiaobo** [comment]
@ide 
Does it will be supported after?
It is very useful for me .
I want to send blocks between RCTRootViews .

In my app, I have native navigation controller .
I have two ViewController . And every ViewController has its own RCTRootView . All of the rootViews has the same bridge .

In the module of first RCTRootView, I call a oc func and send a JS block as parameter .

In the OC func, I will create the second ViewController and use the navigation controller to push it .

Then , I want to send the block to the rootView of second ViewController to implement callback between two modules in different rootViews .

: )
