### ISSUE TITLE
Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by phil-007** [facebook/react-native#9232]
error message:
2016-08-05 16:16:19.394 [error][tid:com.facebook.react.JavaScript] Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
2016-08-05 16:16:19.398 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

xcode:7.2  osx:10.11.5

1.https://facebook.github.io/react-native/docs/native-modules-ios.html
2.Objective-c code
```
#import "CalendarManager.h"
#import "RCTConvert.h"

@interface CalendarManager()

@property (nonatomic, copy) RCTResponseSenderBlock            mBlock;

@end

@implementation CalendarManager

- (dispatch_queue_t)methodQueue
{
    return dispatch_get_main_queue();
}

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(addEvent:(NSString *)title)
{
    self.mBlock(@[[NSNull null], @[@1, @2, @3]]);
}

RCT_EXPORT_METHOD(findEvents:(RCTResponseSenderBlock)callBack)
{
    self.mBlock = callBack;
}

@end
```

3.package.json
```
{
  "name": "MarkLite",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.0.2",
    "react-native": "0.26.1"
  }
}
```
4.index.ios.js
```
'use strict';

import {
  AppRegistry,
  NativeModules
} from 'react-native'

var CalendarManager = NativeModules.CalendarManager;
CalendarManager.findEvents((error, events)=>{
  console.log('findEvents callback :'+events);
});

CalendarManager.addEvent('this is a test');

module.export = CalendarManager;
AppRegistry.registerComponent('CalendarManager', () => CalendarManager);
```
use the RCTRootView
```
    NSURL *jsCodeLocation = [NSURL
                             URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
    RCTRootView *rootView =
    [[RCTRootView alloc] initWithBundleURL : jsCodeLocation
                         moduleName        : @"CalendarManager"
                         initialProperties : nil
                          launchOptions    : nil];
    UIViewController *vc = [[UIViewController alloc] init];
    vc.view = rootView;
    [self.navigationController pushViewController:vc animated:YES];
```

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @phil-007 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
