### ISSUE TITLE
react-native upgrade with 0.31

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#9234]
When launching `react-native upgrade` with the last version (0.31), it stops immediately with this error: 

```
rnpm-upgrade ERR! ERRPACKAGEJSON No package found. Are you sure it's a React Native project?

config.getProjectConfig is not a function
```

We tried with different node versions but always have this error. 

Anyone has an idea? cc @grabbou

**Comment by magrinj** [comment]
Maybe the internalisation of `rnpm` ? cc @grabbou

**Comment by rozele** [comment]
@magrinj: You must have `rnpm-plugin-upgrade` as a dev dependency.  Since [rnpm](http://github.com/rnpm/rnpm) has been merged into [react-native](http://github.com/facebook/react-native), you should just be able to use `react-native upgrade` instead of `rnpm upgrade`.

**Comment by magrinj** [comment]
@rozele Thanks for your answer, but I already have `rnpm-plugin-upgrade` as a dev dependency, and I use the `react-native upgrade` command.

**Comment by satya164** [comment]
cc @Kureev how about merging `rnpm-plugin-upgrade` to RN core? It'll enable us to remove the yeoman dependency altogether.

**Comment by Richard-Cao** [comment]
same error.

**Comment by Kureev** [comment]
I'll try to hack it on the weekend if I have a time

**Comment by oziks** [comment]
I had the same problem but I solved it:
* remove `rnpm-plugin-upgrade` dev dependency in `package.json`
* clean `node_modules` with `npm prune`
* run `react-native upgrade` works fine :)

**Comment by Richard-Cao** [comment]
@oziks Fine!!!Thx

**Comment by magrinj** [comment]
Thanks @oziks, for those who have an error like `Can't find rnpm-plugin-upgrade` after doing @oziks instruction, juste remove your `node_modules` folder and run an `npm i` (`npm prune doesn't solve the problem for me`). Don't forget to remove `rnpm-plugin-upgrade` in your dev dependency before that.

**Comment by Bhullnatik** [comment]
@oziks Thanks!

**Comment by duzliang** [comment]
I solved it just tow steps:

1.remove rnpm-plugin-upgrade dev dependency in package.json
2.run react-native upgrade
