### ISSUE TITLE
Add CLI plugin source information for each command

### ISSUE THREAD

**Issue by rozele** [facebook/react-native#9236]
It would probably be a good idea for each command to be associated with its source package in some way and to report that information in the help information.  E.g., if I add `rnpm-plugin-windows` and run `rnpm windows --help` I should see some information that the command comes from `rnpm-plugin-windows@0.2.0` or something of the like.   

I might also want to see the package source information in the main `react-native --help` command.  I noticed in https://github.com/facebook/react-native/issues/9234 that there was a comment about being confused on the source of a duplicate "upgrade" command in `react-native --help`.  The issue might have been more transparent if the command source info was given.

cc @grabbou @Kureev

**Comment by grabbou** [comment]
Good idea, we should print if a command comes from a 3rd party module. I'll take a closer look in a while and send over a PR.
