### ISSUE TITLE
RCTNetworking - didReceiveNetworkIncrementalData error w/ RN 0.31

### ISSUE THREAD

**Issue by TGPSKI** [facebook/react-native#9248]
Greetings,

I am getting redbox using NetInfo on RN 0.31. I do not get this error when I downgrade to RN 0.30. I am using code very similar to the NetInfo example in the RN documentation to check connectivity status. Let me know if you need any additional details. 

![image](https://cloud.githubusercontent.com/assets/12532803/17449392/01e5648a-5b0f-11e6-9a13-e2a386660011.png)

Here's the code I am using to check connectivity status:

``` javascript
NetInfo.isConnected.addEventListener(
      'change',
      this.handleConnectivityChange.bind(this)
    );

handleConnectivityChange(isConnected) {
    switch (isConnected) {
    case true:
      this.setState({
        connectivity: true
      });
      break;
    case false: 
      this.setState({
        connectivity: false
      });
      break;
    }
  }

componentWillUnmount() {
    NetInfo.isConnected.removeEventListener(
      'change',
      this.handleConnectivityChange.bind(this)
    );
```
## System info
- OSX 10.11.3
- RN 0.31
- iOS 9.3, running on simulator and device

**Comment by Richard-Cao** [comment]
if you use `react-native run-ios` report this error.

try use `xcode`  to run.

**Comment by glassysky** [comment]
+1
After removed `fetch` method in my code, the redbox disappeared.
But apparently I can't send any request with it.

(It runs well with android)

**Comment by TGPSKI** [comment]
Updates:

I spent a few days wrestling with RN and the upgrade from 0.30 to 0.31. I created a new sample project with RN 0.31 and used the same NetInfo code as above, and I could not reproduce the error. 

I switched back to the original project, reset my content and settings on the simulator, and ran the same code with RN 0.31. I didn't get a redbox this time around.

Seems to me like clearing the device and resetting had some positive effect. There also seems to be a difference in behavior between an upgraded vs new 0.31 project.

I still don't have a clear answer or failure mechanism. It would be great to understand what is happening with this bug to a deeper level.

Also @Richard-Cao: in my case, it would always be preferred to run builds outside of xcode. I don't want a version upgrade on RN break my testing and CI flow.

**Comment by Richard-Cao** [comment]
@TGPSKI waiting solution……

**Comment by kesha-antonov** [comment]
Started with Xcode and all worked.

**Comment by twinzen** [comment]
I had come across same issue two hours ago and then found this page, and just resolved it by below few steps.

1\ Shutdown iPhone simulator that run by `react-native run-ios`
2\ Open Xcode
3\ Set the active schema as simulator (e.g. iPhone 6 simulator)
![image](https://cloud.githubusercontent.com/assets/1499928/17830214/396cf770-66f8-11e6-861f-b12270bff69d.png)
4\ Wait for Xcode to build
5\ Run iPhone simulator by `react-native run-ios` again

In my case, I hit the problem after connecting and running the app on my own device. 
After running on my own device (via Xcode), the active schema become "Generic iOS device".

Hope above can help.

**Comment by elie222** [comment]
Doing `Simulator > Reset Content and Settings...` fixed it for me.

**Comment by mikeygee** [comment]
I am getting this error on every `fetch` call with 0.31 and higher. I am on a hybrid app, so I thought it might have to do with Cocoapods not updating properly, but I put some breakpoints in RCTNetworking, and confirmed it was using the updated files. Resetting simulator and clean building didn't make any difference for me.

**Comment by lacker** [comment]
It seems like a number of people have found these workarounds valid so I am going to close this issue. Thanks folks for reporting this!
