### ISSUE TITLE
Flow errors caused by console properties not found in object type

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native#9250]
Flow version: 0.30.0
React-Native version: 0.31.0,

Flow error log is listed below,

> node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js:74
>  74:   console._errorOriginal = console.error.bind(console);
>                ^^^^^^^^^^^^^^ property `_errorOriginal`. Property not found in
>  74:   console._errorOriginal = console.error.bind(console);
>        ^^^^^^^ object type

> node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js:76
>  76:     console._errorOriginal.apply(null, arguments);
>                  ^^^^^^^^^^^^^^ property `_errorOriginal`. Property not found in
>  76:     console._errorOriginal.apply(null, arguments);
>          ^^^^^^^ object type

> node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js:98
>  98:     console.reportErrorsAsExceptions = true; // Individual apps can disable this
>                  ^^^^^^^^^^^^^^^^^^^^^^^^ property `reportErrorsAsExceptions`. Property not found in
>  98:     console.reportErrorsAsExceptions = true; // Individual apps can disable this
>          ^^^^^^^ object type

Any way to solve these flow errors? thanks

.flowconfig content:

```
[ignore]

# We fork some components by platform.
.*/*.android.js

# Ignore templates with `@flow` in header
.*/local-cli/generator.*

# Ignore malformed json
.*/node_modules/y18n/test/.*\.json

# Ignore the website subdir
<PROJECT_ROOT>/website/.*

# Ignore BUCK generated dirs
<PROJECT_ROOT>/\.buckd/

# Ignore unexpected extra @providesModule
.*/node_modules/commoner/test/source/widget/share.js

# Ignore duplicate module providers
# For RN Apps installed via npm, "Libraries" folder is inside node_modules/react-native but in the source repo it is in the root
.*/Libraries/react-native/React.js
.*/Libraries/react-native/ReactNative.js
.*/node_modules/jest-runtime/build/__tests__/.*

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
node_modules/react-native/flow
flow/
decls/

[options]
module.system=haste

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

experimental.strict_type_args=true

munge_underscores=true

module.name_mapper='^image![a-zA-Z0-9$_-]+$' -> 'GlobalImageStub'
module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(2[0-9]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(2[0-9]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)?:? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy

unsafe.enable_getters_and_setters=true

[version]
^0.30.0
```

**Comment by januswel** [comment]
Use flow-bin 0.29.0 for react-native 0.31.0
If you don't know a valid flow version for each react-native versions, type `cd /tmp && react-native init a`, then see a last line of `/tmp/a/.flowconfig`.

**Comment by satya164** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-4** [comment]
Closing this issue as @satya164 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by rayshih** [comment]
I am using another library that force me to use flow 0.31
and here is my solution:

add this:

```
declare var console: any
```
