### ISSUE TITLE
Change package name, already taken in Google Play

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#9255]
I'm looking to change the package name on the project. Usually react native creates a project like:

`com.myproject`, usually this makes it very hard to name your project because it may be already used in google play (my case now).

I already finished the development of my app and i would like to publish it, but i need to change `com.myproject` to something like `com.mycompany.myproject`. Is there any documentation to do this on react native?

**Comment by ide** [comment]
I think it's largely the same as doing this for any other Android app. `git grep <package name>` and maybe codemod (https://github.com/facebook/codemod) to help you rename things?

**Comment by nschurmann** [comment]
@ide i don't want to rename the app, i just want to change the package name so i can upload it to google play safely :)

**Comment by ide** [comment]
I understand, I don't think there's a lot specific to React Native here though. I would imagine it's similar to renaming Java packages and then some other Android-specific fields in various config files, hence my suggestion to grep and rename.

**Comment by rmevans9** [comment]
I actually have gone through this. It is just the same as with a standard android app. Off the top of my head the places you will have to update the package name to:

android/app/src/main/AndroidManifest.xml
android/app/src/main/PATH/TO/JAVA/FILES/MainActivity.java
android/app/src/main/PATH/TO/JAVA/FILES/MainApplication.java

Changing only the package name. This would leave the app name intact and allow you to upload your app. I am going to close this now.

@facebook-github-bot answered

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @rmevans9 says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
