### ISSUE TITLE
ImageView not display with uri source

### ISSUE THREAD

**Issue by meodemsao** [facebook/react-native#9260]
```
<Image source={{uri: 'http://facebook.github.io/react/img/logo_og.png'}} style={{width:50,height:50}}/>

<Image source={{uri: 'https://dantri4.vcmedia.vn/6ec8d34d/zoom/344_258/4b56d7e481/2016/08/06/cay-xanh-1470463874682.jpg'}} style={{width:100,height:100}}/>

```
image 1 not display 
image 2 display ok

i  test with react-native 0.28 -> 0.32

macos 10.11.6 , xcode 7.3.1

**Comment by ide** [comment]
Use an HTTPS URL instead of HTTP for the first image: https://facebook.github.io/react/img/logo_og.png. iOS blocks HTTP connections.

**Comment by meodemsao** [comment]
@ide 

this image also not display when use http or https 

<Image source={{uri: 'https://img.f29.vnecdn.net/2016/08/05/ho-guom-JPG-6781-1470369615_180x108.jpg'}} style={{width:50,height:50}}/>

<Image source={{uri: 'http://img.f29.vnecdn.net/2016/08/05/ho-guom-JPG-6781-1470369615_180x108.jpg'}} style={{width:50,height:50}}/>

**Comment by meodemsao** [comment]
@ide : thanks
i add this to info.plist and work fine 

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>

```
