### ISSUE TITLE
[iOS] Memory leak in RCTModalHost?

### ISSUE THREAD

**Issue by rigdern** [facebook/react-native#9265]
It looks like RN currently isn't calling `invalidate` on any of the `RCTModalHostViews` because `_hostViews` is never allocated. I think [this line](https://github.com/facebook/react-native/blob/1168d0db45dc6105a4e88a7749ad5867d37049d2/React/Views/RCTModalHostViewManager.m#L45) should have a `!` in the condition.

My assumption is that the intention of this line is to allocate `_hostViews` exactly 1 time but it looks like it's currently allocating it only if it is already allocated.

**Comment by Roshanjossey** [comment]
@ide: Can we close this issue?
