### ISSUE TITLE
react-native init XXX --verbose long time???

### ISSUE THREAD

**Issue by XingdaLee** [facebook/react-native#9266]
OSX:
![image](https://cloud.githubusercontent.com/assets/12740778/17460929/392eb83a-5cac-11e6-89d7-38278940d0e0.png)

![image](https://cloud.githubusercontent.com/assets/12740778/17460931/49042fe2-5cac-11e6-8bf9-c79614870fca.png)

**Comment by nihgwu** [comment]
because you are in China, you can use TaoBao's repository https://cnpmjs.org/ , would be much faster

**Comment by sundayha** [comment]
@nihgwu yep

**Comment by ide** [comment]
That progress bar is the `npm install` step.
