### ISSUE TITLE
[Perf] react native js code  run  slower on machine than on simulator

### ISSUE THREAD

**Issue by philonpang** [facebook/react-native#927]
hello, when i finish my react native js code and run on real machine , but i am very surprize that , it runs more slower than on the simulator.

the slow view is that: on a navigator scrollview, i put nearly fifty ball image view on one view
![Uploading iOS Simulator Screen Shot Apr 17, 2015, 21.24.35.png . . .]()

i dont know how it case my react view too slow render, could you help me out??

**Comment by philonpang** [comment]
<View style={{flex:1}}>
				<View style={{flex:1, flexDirection:'column'}}>
					<View style={{flex:1, marginHorizontal:5, backgroundColor:'rgba(0,0,0,0)'}}>
						<TouchableOpacity onPress={this.props.onPress}>
							<Image style={{width:35,height:40.5}}
								   source={this.props.selected?BetBallSel:BetBallNormal}>
							   <Text style={[{fontSize:18,textAlign:'center',marginVertical:6,color:'#c33f51'},this.props.selected==true?{color:'white'}:{}]}>
							   		{this.props.title}
							   </Text>
							</Image>
						</TouchableOpacity>
					</View>
					{missView}
				</View>
			</View>

**Comment by paramaggarwal** [comment]
That happens with any app running in the Simulator, because your Mac CPU is much more powerful than the mobile CPU on your phone.

**Comment by jaygarcia** [comment]
Is this something that you could make this issue a standalone project in GitHub so we can try to reproduce and help?

JG

 :: @moduscreate

:: sent from my mobile device ::

**Comment by philonpang** [comment]
Hello, this is my demo code , could you help me to check the code why the view render slowly on machine , thanks very much...
git:
https://github.com/philonpang/NLDynamicDeploy_React.git

**Comment by philonpang** [comment]
@jaygarcia @paramaggarwal  hello,below is my demo git url:
https://github.com/philonpang/NLDynamicDeploy_React.git
