### ISSUE TITLE
TextInput autoCorrect does not update last word on submit

### ISSUE THREAD

**Issue by cpsiaki** [facebook/react-native#9273]
I'm experiencing an issue with TextInput. It seems autoCorrect does not update the text on the last word of input when submitting. My TextInput snippet looks like this:

```
                <View style={styles.inputs}>

                    {this.props.props.pictures ? <TouchableOpacity style={styles.button}
                        onPress={this.takePicture}
                        underlayColor='#E6CFA8'>

                        <Image style={styles.buttonImage} source={require('../images/cameraicon-41.png')} />
                    </TouchableOpacity> :
                    <View />}

                    <TextInput
                        style={styles.newInput}
                        value={this.state.newMessage}
                        keyboardType="default"
                        placeholder="Message..."
                        returnKeyType="default"
                        multiline={true}
                        autoCorrect={true}
                        ref="newMessage"
                        autoCapitalize='sentences'
                        onFocus={this.inputFocused.bind(this, "newMessage")}
                        onBlur={() => {this.refs.listView.getScrollResponder().scrollTo({y: 0})}}
                        onChangeText={this.updateMessageState} />

                    <TouchableOpacity style={styles.button}
                        onPress={() => this.sendMessage('')}
                        underlayColor='#E6CFA8'>

                        <Text style={styles.buttonText}>Send</Text>
                    </TouchableOpacity>

                </View>
```

If I set my sendMessage function to blur the TextInput, the autocorrect takes effect, the text in the TextInput component changes, but the onChangeText function (this only sets State) will not fire and this.state.newMessage will not update.

```
sendMessage: function (url) {
    this.refs.newMessage.blur()
    return;
}
```

The same thing happens if I set returnKeyType to "submit" and tap the submit button on the text.

Ideally, I'd like not to have to blur to trigger the autocorrect change so that the TextInput can stay focused but baby steps.

Has anybody experienced this? Anybody have a solution?

Thanks

**Comment by dsibiski** [comment]
I think that this is the same as what was reported here: https://github.com/facebook/react-native/issues/2552

I haven't tested this fix in a while so I'm not sure if it would still work. If you could test the solution that would be great.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-autocorrect-does-not-update-last-word-on-submit

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
