### ISSUE TITLE
Unsupported layout animation createConfig property (null)

### ISSUE THREAD

**Issue by ilansas** [facebook/react-native#928]
Trying to render my scene, which contains a SlideMenu in which each items change my Content View, I get that error : 

    [RCTLog][tid:0x7f8f7054b4b0]
    [RCTUIManager.m:466]>Unsupported layout animation createConfig property (null)

I don't really understand where it comes from, because I don't actually use any animation (at least on purpose, I suppose it's an internal thing).

It actually happens when I change the View is supposed to change, by clicking on "Dismiss" on the Emulator, the View is in fact changing. 

I'm sorry if I'm not clear, feel free to tell me, here is my code : 

My menu which triggers the change of View :

    var Menu = React.createClass({
      render: function() {
        return (
          <View style={styles.container}>
            <Section 
              id='suggestions' 
              icon='&#xF0A7;'
              name='SUGGESTIONS'
              toggleSlideMenu={this.props.toggleSlideMenu} 
              setFragment={this.props.setFragment}/>
           
              //Some other sections
          </View>
        );
      }
    });

My component to render : 
    
    var Suggestions = React.createClass({
    	render: function() {
    		return (
    			<View style={styles.container} />
    		);
    	}
    });
    
    var styles = StyleSheet.create({
    	container: {
    		flex: 1, 
    		backgroundColor: '#4455FF',
    	},
    });
Where the component should render:

    var GeneralTemplate = React.createClass({
    render: function() {
        var fragment = this.props.fragment;
        return(
          <View style={styles.container}>
            {fragment}
          </View>
        );
      }

**Comment by liubko** [comment]
@ilansas hi, I'm getting the same error. Did you solve this issue?

**Comment by ilansas** [comment]
Yes :) See it right here https://github.com/facebook/react-native/issues/1135#issuecomment-98903335

**Comment by liubko** [comment]
It works now. Thanks
