### ISSUE TITLE
Image animation (changing images) didnt' work on IOS

### ISSUE THREAD

**Issue by washaq** [facebook/react-native#9280]
Hi i try to animation image i have 2 images and i change it after 1 second in a loop but i don't in ios frame change but image remain the same and in Android it works fine. Can any one help me?
componentDidMount() {

```
setInterval(() => {
    var imageIndex = this.state.imageIndex+1;
      if (imageIndex >= animationImages.length) {
          imageIndex = 0;
      }
      this.setState({imageIndex:imageIndex})
    }, 1000);
}
```

above is how i run it in loop
and below is how i change the image

```
<Image
                style={styles.happyCatContainer}
                source={animationImages[this.state.imageIndex]}/>
```

and this is how i declare images on top

```
const animationImages = [
        require('./Resources/onboarding_messages/happyCat1.png'),
        require('./Resources/onboarding_messages/happyCat2.png'),
    ]
```

this works in android but ios just frame updated image remain the same.

**Comment by asciiman** [comment]
I am having a similar issue:

```
  render() {
    let icon = this.state.myChatsSelected ? ALL_CHATS_ICON : ALL_CHATS_ICON_SELECTED;
    return (
      <View style={styles.feedButtonBar}>
        <Image source={icon} />
        <TouchableHighlight
          style={styles.feedButton}
          onPress={() => this._changeSelection('my')}
        >
          <Text>Hi</Text>
        </TouchableHighlight>
        <TouchableHighlight
          style={styles.feedButton}
          onPress={() => this._changeSelection('all')}
        >
          <Text>Bye</Text>
        </TouchableHighlight>
      </View>
    );
  }

  _changeSelection(feed) {
    this.setState({ myChatsSelected: feed === 'my' });
    this.props.onChange(feed);
  }
```

It's strange it seems to depend on which images I use.  Some don't refresh and some do.  Also, it looks like it is loading the dimensions of the new image because the container is resizing, but the image is not changing.

**Comment by asciiman** [comment]
The key was adding a "key".  :-)

`<Image source={icon} key={icon} />`

Now the image is reloading.

**Comment by washaq** [comment]
@asciiman  thanks dude can't bleave it works lol nice work where you find this is it in doc?

**Comment by washaq** [comment]
@asciiman  but in case of animation of image sequence its jerky so for ios i  use gif

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/image-animation-changing-images-didnt-work-on-ios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
