### ISSUE TITLE
I have made whole UI, but when I am adding a SrollView on the parent View , the view is shrinking , what should I do ?

### ISSUE THREAD

**Issue by rajatgupta1993** [facebook/react-native#9282]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.

None of the above, create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
- [ ] Does this occur on iOS, Android or both?
- [x] Are you using Mac, Linux or Windows?

**Comment by Dean177** [comment]
This isn't really an issue with react native, the issue template you declined to fill out mentions that usage questions should go on StackOverflow:

Regardless:
If you want it to look exactly the same as it did before except scrollable, wrap the contents of the scroll view in a view and set the height:
```
<ScrollView>
  <View style={{ height: ??? }}}>
    ...
  </View>
</ScrollView>
```

**Comment by petergarnaes** [comment]
I have the same issue. My code looks like this:

```
var MyComponent = React.createClass({
    getInitialState() {
        return {
            keyboardHeight: 0
        }
    },
    componentDidMount: function () {
        this.db = new Store('wiosoft');
        this.orderCollection = this.db.collection('order', {unique: 'id'});
        this.keyboardDidShowListener = Keyboard.addListener('keyboardWillShow',this.keyboardDidShow);
        this.keyboardDidHideListener = Keyboard.addListener('keyboardWillHide',this.keyboardDidHide);
        
    },

    componentWillUnmount: function () {
        Keyboard.removeAllListeners('keyboardDidShow');
        Keyboard.removeAllListeners('keyboardDidHide');
    },

    keyboardDidShow: function (e) {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        let newSize = Dimensions.get('window').height - e.endCoordinates.height;
        console.log('newSize is: '+newSize);
        this.setState({
            //visibleHeight: (newSize-100)
            visibleHeight: newSize,
            keyboardHeight: e.endCoordinates.height
        });
    },

    keyboardDidHide: function (e) {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        this.setState({
            visibleHeight: Dimensions.get('window').height,
            keyboardHeight: 0
        });
    },
    render: function (){
            return (
                <View style={[{flex: 1}]}>
                    <ScrollView style={{flex: 1}}>
                        ......
                    </ScrollView>
                    <View style={[{height: this.state.keyboardHeight}]}/>
                </View>
            );
        }
});
```

If you look at the pictures you see that the component does not go all the way down to the beginning of the keyboard, nor goes all the way up to component on top (the selector). It is especially problematic in the bottom.

When the keyboard is not toggled, the bottom of the component goes all the way down where it is supposed to, but the top of the component still does not go all the way to the top. 

![scroll-bug](https://cloud.githubusercontent.com/assets/1044051/17638636/69bfaf5c-60b9-11e6-8cae-92d3f0f2ad96.png)
![scroll-bug2](https://cloud.githubusercontent.com/assets/1044051/17638637/69c06154-60b9-11e6-8157-6775bf085e89.png)

**Comment by RD1991** [comment]
Hey @petergarnaes ,
you can try 
<ScrollView style={{flex: 1}}>
       <View style={{flex:1}}> 
            ....
      	{this.dummyView()}
      </View>
</ScrollView>

...
...

dummyView: function(){
	return (
	<View style={this.dummyViewHeight()}>
	</View>
	)	
},
dummyViewHeight: function(){
	return {
		height:this.state.keyboardHeight,
	}
}

You always needs a view inside scrollview which have fix height, so try to add dummyHeight and whenever keyboard appears , set its keyboard height to dummyView height :)

**Comment by petergarnaes** [comment]
Thanks @RD1991! Turns out the bottom issue is me not accounting for the tab bar underneath the keyboard, so that is completely my fault.

However the top is still not correct no matter if keyboard is on or off, even using your suggestion. With the following code I still get some padding in the top. I have set the background colour of the scrollview, which shows that it has the correct layout, but the scrolling and its nested components still start at an offset.

```
var MyComponent = React.createClass({
    getInitialState() {
        return {
            keyboardHeight: 0
        }
    },
    componentDidMount: function () {
        this.keyboardDidShowListener = Keyboard.addListener('keyboardWillShow',this.keyboardDidShow);
        this.keyboardDidHideListener = Keyboard.addListener('keyboardWillHide',this.keyboardDidHide);

    },

    componentWillUnmount: function () {
        Keyboard.removeAllListeners('keyboardDidShow');
        Keyboard.removeAllListeners('keyboardDidHide');
    },

    keyboardDidShow: function (e) {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        let newSize = Dimensions.get('window').height - e.endCoordinates.height;
        this.setState({
            keyboardHeight: e.endCoordinates.height
        });
    },

    keyboardDidHide: function (e) {
        LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
        this.setState({
            keyboardHeight: 0
        });
    },
    render: function (){
            return (
                <View style={[{flex: 1}]}>
                    <ScrollView style={{flex: 1}}>
                        ......
                    </ScrollView>
                    <View style={[{height: this.state.keyboardHeight}]}/>
                </View>
            );
        }
});
```
![scroll-bug3](https://cloud.githubusercontent.com/assets/1044051/17643635/eb7027dc-613d-11e6-8ae4-0a8bfcce21ba.png)

**Comment by RD1991** [comment]
@petergarnaes try putting your code into [rnplay](https://rnplay.org/) , i'll update it as per solution.

**Comment by damusnet** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-0** [comment]
Hey @rajatgupta1993 and thanks for posting this! @damusnet tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
