### ISSUE TITLE
Production crashes - RN 0.26.3

### ISSUE THREAD

**Issue by guysegal** [facebook/react-native#9283]
We see in production these kind of crashes:

"Couldn't call JS module 0, method 0: bridge configuration isn't available. This probably means you're calling a JS module method before bridge setup has completed or without a JS bundle loaded"

What does this error stands for? What's module 0 and method 0?

**Comment by hramos** [comment]
Looks like this is a question rather than a specific issue. I'm going to close this, if you believe this was in error feel free to reopen and make sure to fill out the template.
