### ISSUE TITLE
TextView is not correctly sized if it is styled with maxWidth

### ISSUE THREAD

**Issue by lachezar** [facebook/react-native#9293]
The text in the TextView is being partially displayed if its stylesheet contains `maxWidth` property.

Screenshot with `maxWidth: 300`:
![screen shot 2016-08-08 at 5 15 12 pm](https://cloud.githubusercontent.com/assets/130336/17485071/d06f38d8-5d8c-11e6-8bac-cd1568716e0b.png)

Screenshot without using `maxWidth`:
![screen shot 2016-08-08 at 5 15 49 pm](https://cloud.githubusercontent.com/assets/130336/17485070/d0580410-5d8c-11e6-8988-0fb6f45b8b94.png)

Minimal code snippet:

```
import React, { Component } from 'react';
import { AppRegistry, View, Text, StyleSheet } from 'react-native';
import Dimensions from 'Dimensions';

export default class Message extends Component {
  constructor(props) {
    super(props);
  } 
  render() {
    return (
      <Text style={ styles.bubble }>{ this.props.sender }: { this.props.text }</Text>
    );
  }
}

const styles = StyleSheet.create({
  bubble: {
    maxWidth: 300, // the bug occurs only when maxWidth is present in the styles
    marginBottom: 10,
    padding: 10,
    backgroundColor: '#0086EF',
  }
});
```

Works correct on Android, the problem occurs only in iOS (EDIT 09.08.2016: after testing it again with Android I can reproduce the problem there also, so it affects iOS and Android).
react-native: 0.31.0

**Comment by wli** [comment]
I just came across something that looks quite similar. I can repro on Android, but not 100% about iOS yet.

Minimal RN Play example that shows the problem on android: https://rnplay.org/apps/aSc6cw

Top text line has `maxWidth: 300` applied and shows the text getting cut off.

![overflow-both](https://cloud.githubusercontent.com/assets/649892/19669700/5bd2d0a4-9a16-11e6-8fbe-35259332ef25.png)

**Comment by ide** [comment]
@emilsjolander are you the best person to look into this issue or should it go to someone more familiar with the Android side of RN?

**Comment by emilsjolander** [comment]
Given how it repros differently on ios and android I would assume there is something funky with the text measurement logic. Someone on RN is best to look at this. Happy to help if this turns out to be a layout issue and not a measurement issue.

**Comment by hramos** [comment]
@wli what version did you repro this on? Has the behavior changed at all between 0.31 and 0.37?

What would you expect the rendering to look like when maxWidth is used?

**Comment by wli** [comment]
@hramos This was on 0.33.0, haven't had a chance to repro on the latest version yet, but I may be able to check on 0.36 if rnplay updates to exponent SDK11.

I expect the text to wrap onto a second line, and effectively leave a right margin.

**Comment by yuriyvl** [comment]
@hramos This behavior is still present on 0.37

**Comment by davidaurelio** [comment]
cc @emilsjolander

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/textview-is-not-correctly-sized-if-it-is-styled-with-maxwidth

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.
