### ISSUE TITLE
react-native link add empty lines in strings.xml

### ISSUE THREAD

**Issue by charpeni** [facebook/react-native#9294]
For each package that are linked by `react-native link` an empty string is added into `res/values/strings.xml`.

`react-native unlink` removed them as well.

Is this normal ? Maybe [makeStringsPath](https://github.com/facebook/react-native/blob/7028929d8f44872e790376875c7971155bb99f81/local-cli/rnpm/link/src/android/patches/makeStringsPatch.js#L4-L8) should not add a new line if the package does not contain any parameters.

react-native@0.31.0
react-native-cli@1.0.0

cc @grabbou @Kureev

**Comment by charpeni** [comment]
@facebook-github-bot label Tooling

**Comment by grabbou** [comment]
Sounds good to me. Mind sending a PR?
