### ISSUE TITLE
import com.facebook.react.ReactActivity; cannot find symbol

### ISSUE THREAD

**Issue by georgi-kovachev** [facebook/react-native#9296]
error: cannot find symbol
import com.facebook.react.ReactActivity;
                         ^
  symbol:   class ReactActivity

I am trying to build the android app using 'react-native run-android' but i get above error.

This is my MainActivity.java

package com.conversations;

import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Conversations";
    }
}

I use React-native 0.30.0 and react version of 15.2.0

**Comment by georgi-kovachev** [comment]
I updated some files and now i get this error.

MainApplication.java:20: error: cannot find symbol
      return BuildConfig.DEBUG;

**Comment by georgi-kovachev** [comment]
Fixed issue by applying same changes from recent react native app.

**Comment by hindsricardo** [comment]
@georgi-kovachev what was the fix? I'm having the same issue after upgrading to react-native 49.5 and react 16.0.0

**Comment by ufolux** [comment]
You can try these ways to fix this problem
1. You can do "File" -> "Invalidate Caches...", and select "Invalidate and Restart" option to fix this.
2. If the first one doesn't work, you can 
- Exit Android Studio
- Back up your project
- Delete all the .iml files and the .idea folder
- Relaunch Android Studio and reimport your project
