### ISSUE TITLE
[HELP WANTED] Setting header for image source

### ISSUE THREAD

**Issue by ospfranco** [facebook/react-native#9299]
Hey, I'm trying to fetch an image from one of our services, however there is a small problem, we set our verification token on our headers, therefore this:

`<Image source={{uri: 'https://myservice/api/image.jpg'}}/>`

doesn't work

For our normal requests we are using `fetch` which works just fine, however if I try to pull an image with it I get, I get the returned object, but have no idea how to bind it the Image component, if I pass it directly as source={imageData} I get an error, image is displayed, but get an error from the Image component.

<img width="166" alt="screen shot 2016-08-08 at 17 06 42" src="https://cloud.githubusercontent.com/assets/1634213/17496279/8999f828-5d8a-11e6-87d1-f96bbdea2966.png">
<img width="377" alt="screen shot 2016-08-08 at 17 06 28" src="https://cloud.githubusercontent.com/assets/1634213/17496281/8abdd8dc-5d8a-11e6-8199-7f8da3af0bcf.png">

**Comment by ospfranco** [comment]
after some fumbling around I found this: https://github.com/facebook/react-native/pull/7338/files, however this is not documented, and I'm about to test if it works on android.

**Comment by DanielMSchmidt** [comment]
Hey, I did a PR for the missing documentation: #9304
