### ISSUE TITLE
Open source JS navigator

### ISSUE THREAD

**Issue by ide** [facebook/react-native#93]
It sounds so much simpler than UINavigationController bridging. cc @vjeux @jordwalke
Thanks!

**Comment by ericvicenti** [comment]
http://facebook.github.io/react-native/docs/navigator.html

https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/Navigator/NavigatorExample.js

https://github.com/facebook/react-native/tree/master/Libraries/CustomComponents/Navigator

Fortunately we got this in for the open source release. Let me know what you think!

**Comment by ide** [comment]
With some custom nav bar implementations that simulate iOS's style, this could quickly surpass UINavigationController. Really great @ericvincenti. BTW I noticed some small issues causing crashes with the UIExplorer example and put up #200 as a fix.

**Comment by jordwalke** [comment]
:+1: 
Thanks @ericvicenti

@tadeuzagallo is working on getting hardware touches to be aligned with the screen refresh rate/cycle which is going to make it even better!

Check out the F8 app which uses this for all of its transitions/gestures.
