### ISSUE TITLE
Slow rendering of CameraRoll images since 0.4.0

### ISSUE THREAD

**Issue by VonD** [facebook/react-native#930]
Hi,

Images from the CameraRoll are very slow to render since 0.4.0 (up to a minute). Downgrading to 0.3.11 solves the issue.
This can be reproduced in a brand new app, or in the UIExplorer for example. I can attach some sample code to the issue if needed.

Thanks

**Comment by nicklockwood** [comment]
That would be helpful - thanks!

**Comment by VonD** [comment]
To reproduce

```
react-native init TestImagesLoadingTime
```

then replace the contents of `index.ios.js` with this : https://gist.github.com/VonD/a530d21a53499a085080

Below are the captures of the same code with react-native 0.3.11 and 0.4.0 (sorry, the second one is quite heavy)

![capture-0 3 11](https://cloud.githubusercontent.com/assets/752330/7230530/1255c3ce-e76f-11e4-8916-cffec14e736e.gif)

![capture-0 4 0](https://cloud.githubusercontent.com/assets/752330/7230534/17d5720e-e76f-11e4-93d0-6df036faa912.gif)

**Comment by rt2zz** [comment]
I can confirm the issue - the Image component appears to specifically be slow with CameraRoll images.

**Comment by scottdixon** [comment]
+1 @rt2zz

**Comment by arypurnomoz** [comment]
+1

**Comment by adrian-social-prod** [comment]
+1

**Comment by scottdixon** [comment]
Here's a work-around: http://stackoverflow.com/a/29903737/2313477

**Comment by rt2zz** [comment]
@scottdixon that may be a seperate issue, but I just tested on 0.4.1 and loading the lower quality image does not solve the delay issue.

I did some debugging through the obvious image code, and everything is returning fast, RCTImageLoader.m `loadImageWithTag` which returns to RCTStaticImageManager.m `RCT_CUSTOM_VIEW_PROPERTY(imageTag, NSString, RCTStaticImage)` are are both running with minimal latency, yet there still is a lag of ~5s before the actual image renders to screen.

**Comment by adrian-social-prod** [comment]
I have cameraroll on a tab and it is very slow to render the images, but if i click another tab straight away and come back quickly then the images are shown. Seems like the image does not trigger a loaded event, but once cached it works immediately

**Comment by plredmond** [comment]
possibly related xcode logging about `assetsd`?
```
2015-04-30 11:39:42.464 ...[1274:189831] Connection to assetsd was interrupted or assetsd died
2015-04-30 11:39:42.637 ...[1274:190017] Communications error: <OS_xpc_error: <error: 0x19caaba80> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x19caabe78> { length = 22, contents = "Connection interrupted" }
}>
```

**Comment by aroth** [comment]
I have developed a quick fix for this issue at https://github.com/aroth/react-native. The slow load times can be resolved by wrapping the asset callback in a dispatch_async call:

```
dispatch_async(dispatch_get_main_queue(), ^{
    callback(nil, image);
});
```

Secondly, loading a large number of images will trigger memory warnings and/or OOM crashes. Using the thumbnail method of the ALAsset class can help remedy this (especially useful when iterating over images from the camera roll). I have updated image loading code to take in a representation string:  full, screen or thumbnail. The default is 'full' if not provided.

```
<Image
  source={asset.node.image}
  representation={'thumbnail'}
  style={imageStyle}
/>
```
Full pull request pending.

**Comment by rt2zz** [comment]
@aroth thanks! dispatch_async definitely fixes the load time

**Comment by brentvatne** [comment]
@aroth - nice one :smile:

**Comment by VonD** [comment]
@aroth thanks!

About the image representation property : RN docs mention that the Image component already picks the most efficient representation (http://facebook.github.io/react-native/docs/image.html#best-camera-roll-image) : does your implementation do something different/more about it ?

About your PR : what's the status on that ?

**Comment by bparadie** [comment]
@aroth You might want to remove `npm-debug.log` from your https://github.com/aroth/react-native/commit/453064b743f7417b6c969ab135442a08eccacb04 commit.

**Comment by aroth** [comment]
I've created a pull request at https://github.com/facebook/react-native/pull/1263 to address the slow CameraRoll image load issue only. 

As for asset representation (fullScreen, fullResolution, or thumbnail)  -- I would like to address that concern separately in another Issue/PR. As is, even with this PR, loading several full resolution CameraRoll images will cause memory to spike and the app will likely crash. Thumbnail versions should be accessible and used when appropriate. 

@vonD - I may be wrong, but it appears that the docs are a bit misleading. If you review RCTImageLoader.m you will see that the full resolution image is loaded for any image passed into loadImageWithTag: with an assets-library prefix. 

```
UIImage *image = [UIImage imageWithCGImage:[representation fullResolutionImage] scale:1.0f orientation:(UIImageOrientation)orientation];
```

My previous implementation did not automatically handle this. Instead, it required passing in a representation string (full, screen or thumbnail). I'm looking into the issue further to see if it can be handled in a more efficient way.

**Comment by VonD** [comment]
@aroth thanks for the clarification. Have you been able to make progress on making the representation configurable ? That would indeed be very useful. Should I open an issue for that ?
Also, if the reprensentation is configurable, the orientation should be too, to avoid, e.g. displaying an upside down thumbnail.

**Comment by brentvatne** [comment]
The fix for this has been merged!

**Comment by brentvatne** [comment]
@VonD - if the fix doesn't solve all of your issues, it would be great if you could open another issue! :smile:

**Comment by aroth** [comment]
@brentvatne Thanks, this was merged internally by @nicklockwood a couple of weeks ago.

@VonD We still need support for configurable representation and orientation of ALAssets/PHAssets.

https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L81
https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L82

Another issue should be opened. I will try to involve myself this week. Thanks again.

**Comment by bparadie** [comment]
@brentvatne @VonD CameraRoll in 0.6.0 is still dog slow for me.

Any thoughts on this note from the [ALAssetRepresentation](https://developer.apple.com/library/prerelease/ios/documentation/AssetsLibrary/Reference/ALAssetRepresentation_Class/index.html) documentation?

> IMPORTANT
> 
> The Assets Library framework is deprecated as of iOS 9.0. Instead, use the Photos framework instead, which in iOS 8.0 and later provides more features and better performance for working with a user’s photo library. For more information, see Photos Framework Reference.
> 
> In the Photos framework, the PHAsset and PHImageManager classes provide functionality for fetching an asset’s image or video data.

**Comment by VonD** [comment]
The issue about the image representation can be found here : #1567
