### ISSUE TITLE
`getInitialState` not calling after webpack + babel

### ISSUE THREAD

**Issue by leecade** [facebook/react-native#931]
src:

```js
export default class extends React.Component {

  getInitialState() {
    alert(77)
    return {
      index: 0
    }
  }

  render() {
    return (
      <View>
      </View>
    )
  }
}
```

transformed:

```js
_createClass(_class, [{
	    key: 'getInitialState',
	    value: function getInitialState() {
	      alert(77);
	      return {
	        index: 0
	      };
	    }
	  }, {
	    key: 'render',
	    value: function render() {
	      return _React$StyleSheet$Text$View$ScrollView2['default'].createElement(_React$StyleSheet$Text$View$ScrollView.View, null);
	    }
	  }]);
```

and `React.createClass` works fine.

Should I not use babel?

Look forward native supports `let` / `const`, use babel maybe not a good choice.

**Comment by brentvatne** [comment]
@leecade - there is did you mean to do `AlertIOS.alert(77)`?

Regardless, because this isn't currently supported in the standard build of react-native, you might have better luck discussing it here: https://github.com/roman01la/react-native-babel or in irc. :smile:

**Comment by iamdustan** [comment]
Also, es6 React.Component has a different signature. See: https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes

```
export default class extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {index: 0};
  }

  render() {
    return (
      <View>
      </View>
    )
  }
}
```

**Comment by brentvatne** [comment]
good point @iamdustan - that should fix it for you @leecade

**Comment by leecade** [comment]
ok thanks @iamdustan
