### ISSUE TITLE
ReactContext#getCurrentActivity() is null in createViewInstance()

### ISSUE THREAD

**Issue by foghina** [facebook/react-native#9310]
See discussion on #8661 for more info, we should never create views before we have an attached activity. This means we can either move the call to `startApplication` to `onResume` or set the current activity in `onCreate`.

**Comment by lschmierer** [comment]
`ThemedReactContext#getCurrentActivity()` seems to be allways `null` in react-native version 0.31.0. At least on property setting it is still `null`.

**Comment by nicolas-yaros** [comment]
Is there any updates? Still null for me

**Comment by foghina** [comment]
Fixed in 96e4121.

**Comment by lschmierer** [comment]
Is this going to be released in 0.32 or only in 0.33-rc?

**Comment by foghina** [comment]
It will probably be in the next RC.

**Comment by cornedor** [comment]
Do I have to wait for 0.33 or is there another way to get an Activity in a view?

**Comment by cosmith** [comment]
Could this also cause a crash in `PermissionsModule` too for me in some cases? https://github.com/facebook/react-native/blob/e70d1dba58bdb92eb5a025c6348303e9c650148c/ReactAndroid/src/main/java/com/facebook/react/modules/permissions/PermissionsModule.java#L123-L126
