### ISSUE TITLE
Unrecognized command 'android' with react-native 0.31

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [facebook/react-native#9312]
![screen shot 2016-08-09 at 5 19 02 pm](https://cloud.githubusercontent.com/assets/13464885/17515350/84eec0ee-5e55-11e6-8d38-0449eede68a3.png)

**Comment by satya164** [comment]
can you run `ls` in your project and post the results?

**Comment by SupriyaKalghatgi** [comment]
@satya164 The `android` folder structure goes this way on `react-native upgrade`
![screen shot 2016-08-09 at 10 01 31 pm](https://cloud.githubusercontent.com/assets/13464885/17524643/1660b3da-5e7d-11e6-99b1-6c398a2231f5.png)

**Comment by ThaJay** [comment]
subscribing.
I nuke my android folder sometimes. What happened to react-native android?

**Comment by adamboduch** [comment]
My current work-around is to have a `generate-android-project.js` script that looks like this:
```javascript
const fs = require('fs');
const generate = require('react-native/local-cli/generate/generate.js');

generate([
  '--platform', 'android',
  '--project-path', process.cwd(),
  '--project-name', JSON.parse(
    fs.readFileSync('package.json', 'utf8')
  ).name,
]);
```
Then you can just:
```
node generate-android-project.js
```
This has the exact same effect as:
```
react-native android
```

**Comment by SupriyaKalghatgi** [comment]
But what about `react-native android`?
There has to be replacement command for this instead

**Comment by wildQueequeg** [comment]
I have this issue as well:
```

$ react-native run-android
Android project not found. Maybe run react-native android first?

$ react-native android
  Unrecognized command 'android'
  Run react-native --help to see list of all available commands

$ ls
RouterConfig.js		components		ios			package.json
android			index.android.js	node_modules
assets			index.ios.js		notes
```

**Comment by satya164** [comment]
cc @grabbou @Kureev can you take a look at this one please?

**Comment by Flavien** [comment]
This should be reopened as this still happens on the latest version.

**Comment by SupriyaKalghatgi** [comment]
@Flavien With latest of RN
`react-native upgrade` does the complete work for you

**Comment by cogwheel** [comment]
I still get the Android project not found error after running react-native upgrade, and it still suggests running a non-existent command. This should be reopened.

**Comment by temitope** [comment]
@cogwheel any fix for adding android/ios folders to an RN project?

**Comment by a1exlism** [comment]
@SupriyaKalghatgi Thanks for your update.

**Comment by gameboy87** [comment]
This should be definitely re-opened as it causes the same error.

**Comment by gameboy87** [comment]
![image](https://cloud.githubusercontent.com/assets/1721339/25833848/dfb27ecc-3491-11e7-9fc6-b92ae30478d6.png)

**Comment by gameboy87** [comment]
OK. My **Problem got fixed** by enabling Virtual Device from BIOS in Windows 10 and ran the emulator in Background (**I am novice to Android**)! But still, why it didn't run in my connected Android device directly ?

**Comment by jose2007kj** [comment]
thanks @SupriyaKalghatgi

**Comment by huxaiphaer** [comment]
Whats the final answer ? me too am stuck

**Comment by jose2007kj** [comment]
@huxaiphaer  `react-native upgrade` hopes this will help as said by @SupriyaKalghatgi
