### ISSUE TITLE
[Discussion] Equivalent to querySelector()

### ISSUE THREAD

**Issue by staltz** [facebook/react-native#932]
I am doing something unconventional with React Native, so keep in mind I'm not doing idiomatic React. Basically I need to do something like `document.querySelector(refOrSomeId)` from the top-level of the app, to get a particular element, and attach an event handler. Put it differently, I'm looking into how to make custom event delegation.

I've looked into getNodeHandler() but it doesn't help me since I'm not making components (no ReactOwner), instead I'm making just ReactElements. To be more precise, an Observable of ReactElement.

My program is essentially: create a empty event stream that serves as a proxy for the "press" event stream. I create a stream ("Observable") of ReactElement based on the proxy event stream. Then I render the Observable of ReactElement. And then I need to attach the press handler, and feed press events back into the proxy event stream. It's comparable to this, in JavaScript for the web:

```js
let vtree$ = Cycle.createStream(function computer(interaction$) {
  return interaction$.choose('.field', 'input')
    .map(ev => ev.target.value)
    .startWith('')
    .map(name =>
      h('div', [
        h('label', 'Name:'),
        h('input.field', {attributes: {type: 'text'}}),
        h('h1.header', `Hello ${name}`)
      ])
    );
});

let interaction$ = Cycle.createStream(function user(vtree$) {
  return Cycle.render(vtree$, '.js-container').interaction$;
});

interaction$.inject(vtree$).inject(interaction$);
```

Can this be done without further modifications to RN source? If it requires modifications, can anyone point me to the right direction so I can attempt to do some changes?

**Comment by brentvatne** [comment]
You'll probably want to look into `RCTUIManager` and `RCTEventDispatcher`. 

Not exactly equivalent to `document.querySelector` but you can find the native element corresponding to a given node handle (which you can get from the ref) by doing:

```objc
  [_bridge.uiManager addUIBlock:^(RCTUIManager *uiManager, RCTSparseArray *viewRegistry) {
        UIView *view = viewRegistry[reactTag];
        // do something with the view
 }];
```

Not sure if this helps, I'm not very familiar with FRP so some of your question went over my head.

**Comment by staltz** [comment]
Thanks, that sounds like helpful pointers.

**Comment by browniefed** [comment]
@brentvatne seems closeable 
@staltz anything come of this? Might be helpful to people that stumble upon this in the future.

**Comment by staltz** [comment]
Yeah I guess you can close. It would be helpful to get this done, but apparently won't come from the `react-native` library. I suppose a third-party library could provide this functionality. I'll try going with attaching event listeners on the virtual component tree instead.

**Comment by ide** [comment]
This is more about React than RN (the iOS bridging layer). Maybe it makes sense to expose info about the native view layer (whether it's UIViews or DOM nodes) but I think we first want to start with APIs at the virtual component level.
