### ISSUE TITLE
[Android] Overflow:'visible' not working

### ISSUE THREAD

**Issue by flaviotobi** [facebook/react-native#9322]
Hi. The issue is pretty simple,  overflow:'visible' work in iOS but is not working in Android.
Below you have an example to show  my problem. 
Example: https://rnplay.org/apps/2O3XkQ

Any hack to pass this problem is welcome :)

Additional Information:
React-Native: 0.31.0
Mac -  OS X El Capitan

**Comment by ide** [comment]
`overflow: visible` is not supported on Android due to how its View system works. No plans to change that AFAIK.

**Comment by joncursi** [comment]
Would it be possible to update the documentation to call this out? [From what I see here](https://facebook.github.io/react-native/docs/view.html#style), `overflow: 'visible' | 'hidden'` is available on both platforms.

**Comment by flaviotobi** [comment]
@joncursi  can you tell me the react native version that you are using ?

**Comment by joncursi** [comment]
@flaviotobi I'm using `0.34.1`!

**Comment by exera** [comment]
to achive overflow hidden effect i give fixed height and backgroundColor it works, background color doesn't matter. is it normal or just a dirty hack?

```
<View style={{height:100,backgroundColor:'black'}}>
  <View style={{width:50,height:50,backgroundColor:'powderblue'}}></View>
  <View style={{width:50,height:50,backgroundColor:'skyblue'}}></View>
  <View style={{width:50,height:50,backgroundColor:'black'}}></View>
</View>

**Comment by flaviotobi** [comment]
@joncursi maybe the difference is in the version of react-native.

@exera its a dirty hack from my point of view, but if works :) i did something dirty too to resolve my issue. xD

**Comment by GarimaMathur07** [comment]
@ide How can i achieve `overflow: visible` effect in android
