### ISSUE TITLE
react native compile fail in macOS Sierra 10.12

### ISSUE THREAD

**Issue by huangminlinux** [facebook/react-native#9332]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:
- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.
## None of the above, create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
- [ ] Does this occur on iOS, Android or both?
- [ ] Are you using Mac, Linux or Windows?

when i open my old project compile it and I got fail in RCTWebSocket after that:
/Users/HuminiOS/Desktop/workproject/jpush-react-plugin/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:459:3: Ignoring return value of function declared with warn_unused_result attribute

/Users/HuminiOS/Desktop/workproject/jpush-react-plugin/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1301:5: Ignoring return value of function declared with warn_unused_result attribute

**Comment by sibelius** [comment]
fixed on RN33

or follow this comment - https://github.com/facebook/react-native/issues/8584#issuecomment-236366222

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/react-native-compile-fail-in-macos-sierra-1012

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
