### ISSUE TITLE
fetch undefined with jest (0.31)

### ISSUE THREAD

**Issue by Bhullnatik** [facebook/react-native#9333]
When using jest (`jest-cli@14.1.0` and `jest-react-native@14.1.2`) with `react-native@0.31.0`, all tests fail with this error:

```
● Runtime Error
  - ReferenceError: fetch is not defined
        at Object.<anonymous> (node_modules/react-native/Libraries/Fetch/fetch.js:17:23)
```

`react-native@0.30.0` under the same config works fine.

I don't know the internal mechanics well enough to fix it myself or is the issue is more from Jest than React Native unfortunately. :/

**Comment by satya164** [comment]
cc @cpojer

**Comment by cpojer** [comment]
We'll fix it in Jest momentarily. See https://github.com/facebook/jest/issues/1397
