### ISSUE TITLE
require('NativeModules').KeyboardObserver got a undefined

### ISSUE THREAD

**Issue by oillamp** [facebook/react-native#9335]
after i upgrade react-native@```0.26.3``` -> react-native@```0.27.1```

i got a red green with 'Native module cannot be null'

after debugger it, 

find in ```Libraries/Components/Keyboard/Keyboard.js```
```
const NativeEventEmitter = require('NativeEventEmitter');
const KeyboardObserver = require('NativeModules').KeyboardObserver;
```
the KeyboardObserver got a undefined.

should i need to update podfile add RCTKeyboardObserver ?

i do this, but it does not work.

current version:
```
react@15.1.0
react-native@0.27.1
mac@10.11.6
```

thanks a lot.

**Comment by rmevans9** [comment]
The release notes for 0.27.0 note a change to how you import the Keyboard object - just to make sure, did you update to the new method of importing the keyboard object?

ref - https://github.com/facebook/react-native/releases/tag/v0.27.0

**Comment by oillamp** [comment]
@rmevans9  yeah, i did it, but not work.

in the last, delete node_modules folders and npm install  solve it
