### ISSUE TITLE
"react-native is not recognized as an internal or external command" while initializing a project

### ISSUE THREAD

**Issue by warmwater** [facebook/react-native#9342]
Hello

I set up development environment and did some practice projects in OS X and it works fine.

Now, I am trying to do the same thing in Windows 7, but  I've got stuck in the beginning....

I am using Windows 7, following the instruction of the offical [Getting Start Guide](https://facebook.github.io/react-native/docs/getting-started.html), installed **nodejs**(6.3.1), **python2** by [chocolatey](https://chocolatey.org/). then global install **react-native-cli**(1.0.0) by npm

When I was trying to initializing a new project with the command-line tool
> react-native init test1

It return the message:
>'react-native is' not recognized as an internal or external command

Is there anything I missed? I couldn't find any information on internet and I have reinstalled nodejs and react-native-cli for several times, and tried on two computers.

cheers

**Comment by warmwater** [comment]
Problem solved after I add npm path to global path config instead of user path....

**Comment by CAMMG** [comment]
what's the meaning of "add npm path to global path config instead of user path...."
I meee the same problem..

**Comment by warmwater** [comment]
![image](https://cloud.githubusercontent.com/assets/19963/17580671/06380a2e-5fd3-11e6-9e3d-62d70bc7e934.png)

add path of npm module to system variables instead of user variable

**Comment by CAMMG** [comment]
It works!!!!!!Thank you so............much!!!!!!!

**Comment by warmwater** [comment]
UPDATE: the other PC works fine without modifying system variables manually...I am confused...

**Comment by HienNguyen711** [comment]
Hi, I follow your steps but it didnot work. Still the same problem(react-native is not recognized as an internal or external command, operable program or batch file.
I have copied the path of npm folder, System32, etc as following your instructions. I use Win7.
Any recommendation?

**Comment by ememumoh** [comment]
@HienNguyen711 Run this command at your CMD: npm config list  it is very possible that your environmental variable for npm is pointing to the location. When you run this command, it will give you the location.

**Comment by gbenga504** [comment]
Also worked well for me, Thanks a lot

**Comment by ioncomanci** [comment]
,,, it broke my node instalation ((((

**Comment by mrugeshrocks** [comment]
I have tried the above answers but it didn't work for me . 

What worked for me is here 
http://stackoverflow.com/a/41347543/6481928

**Comment by hiteshsahu** [comment]
I had to run cmd as admin, otherwise, it won't work. I am running window 7 -64 bit.

**Comment by pallavbohara** [comment]
This worked for me.
npm install -g react-native-cli

**Comment by coreybyrum7** [comment]
Thanks :) @pallavbohara

**Comment by thaibinhnguyenduc** [comment]
In Windows, Please follow this image, you will solve this issue.
![config node js](https://user-images.githubusercontent.com/15172078/28243712-39bfb4be-69ff-11e7-9ef2-21a054afd1c0.png)
![config android tools](https://user-images.githubusercontent.com/15172078/28243713-39ce305c-69ff-11e7-833a-f26d223d2698.png)

**Comment by Mohammed-Saeed** [comment]
**add path of npm module (C:\Users\your user name\AppData\Roaming\npm) to system variables instead of user variables**

Worked For Me Thanks Alot

**Comment by rafa-ulloa** [comment]
@warmwater you da MVP

**Comment by Brahma-S-P** [comment]
i used the above method but it is still not working i added the path to the system variables please help. I am using windows 8.1

**Comment by mshavandi** [comment]
solved this issue by uninstalling Node.js and then reinstalling it using installer in [Node page](https://nodejs.org/en/download/)
