### ISSUE TITLE
if "request.build" support below

### ISSUE THREAD

**Issue by scanry** [facebook/react-native#9344]
for example：
           Builder build = new Builder().url(url);
           build.localAddress(new InetSocketAddress(tempIp, 0));
           SocketAddress sa = new InetSocketAddress(host,port);
           Proxy proxy = new Proxy(Proxy.Type.HTTP, sa);
           build.proxy(proxy);
           Request request = build.build();

if "request.build" support above, i think the "okhttp" will be flexible.

**Comment by scanry** [comment]
sorry .this issues is for okhttp3.

**Comment by rmevans9** [comment]
As you have pointed out this is not an issue with React Native but okhttp3 instead I will close this issue. Thanks!

**Comment by rmevans9** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment]
@rmevans9 tells me to close this issue. If you think it should still be opened let us know why.
