### ISSUE TITLE
ImageEditor in iOS not quite as good as Android (IMO!)

### ISSUE THREAD

**Issue by npomfret** [facebook/react-native#9345]
When cropping or scaling an image using the ImageEditor in android the API helpfully returns a path to a file on disk, where are the iOS version returns a uri to a base64 encoded string.  In my case, having access to the binary file is very helpful, however...

In my opinion it's not obvious (enough) from the API that the image will be stored in memory, and I'm worried about running out of memory, especially on smaller devices.  I know there's an API for removing them.  But I think a better solution would be something similar to the android approach, which is to store the image on disk and return a `file://` uri to the cropped image. And add a new API call for loading the cropped image as a base64 encoded string, but don't store that data in memory.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/imageeditor-in-ios-not-quite-as-good-as-android-imo

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (66/60 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34579)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6718-000jR4-4O
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:07 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c6716-00083U-CM
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:05 -0700
Date: Sun, 13 Nov 2016 18:28:58 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090543;
	bh=8SxoFzHT+1wgGsHoHP3iP7AUmHZkw87mT8KRKk/iyOQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RaI17G3vf5ttZsnsLivYQ7vQNcpkaZYB7K9E4gD8Yz03KJbFnNlPjGmmyVXYST7sR
	 joUqNxzoB7EPS43nJIiEaWlygjN7joLBQTLYBp7+JLwSqknkFMfDr8zU2nn/0OJcQN
	 4TXtSKDRugxYmDIrJNOEPjY9RbHVhxyDk7rDl3Zw=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (67/60 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34590)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671A-000jRn-F9
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:09 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c6719-000853-9z
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:08 -0700
Date: Sun, 13 Nov 2016 18:28:59 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090545;
	bh=ZcQ6m+KRRxs9SYQ0/9cht/AKc/TpGy4hqFsn3k+QmdE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XQk46vyYMxsrU/+o5NgM1jKihm5coYvNsfKF73JLZWlcNv5Ry5BKm0r/wLI6Y0JaW
	 nqagprUEhlkhF8Ufu8BJPI9PCeoeQcVNb0qpDC6pwoh9MNRuNqDx/PT3ETaLZdLIIo
	 nhL8CMGDjmwx/2ZW+nh9SAU/mRHMMZvjHIlHl7no=
