### ISSUE TITLE
iOS: No way to handle app termination on JS side

### ISSUE THREAD

**Issue by tsareg** [facebook/react-native#9348]
I'm trying to do some clean up on JS side (mainly - send a single HTTP request) when app is closed by user.
As some answers on SO suggest, I tried to implement `applicationWillTerminate` method in AppDelegate.m and pass a prop to `rootView`:

``` objective-c
- (void)applicationWillTerminate:(UIApplication *)application
{
  NSMutableDictionary *newProps = [NSMutableDictionary dictionary];
  if (self.rootView.appProperties != nil) {
    [newProps addEntriesFromDictionary:self.rootView.appProperties];
  }
  newProps[@"appWillTerminate"] = @YES;
  self.rootView.appProperties = newProps;
}
```

and then in my Root view on JS side:

``` javascript
componentWillReceiveProps(nextProps) {
    if (nextProps.appWillTerminate) {
        // Do clean up
    }
}
```

but JS code inside if clause is not executed.

So I was wondering if there is any other way to do something on JS side when app terminates.
I was also looking into AppState component, but it also doesn't support app termination.

**Comment by rmevans9** [comment]
I haven't tested this theory but maybe the bridge is getting cleaned up prior to you trying to do your cleanup? A work around if that is the case is to simply make your HTTP request from the native code. Sometimes you will need to do things in the native side if the bridge is unavailable (the biggest situation that happens off the top of my head is when your app is in the background)

**Comment by rmevans9** [comment]
@facebook-github-bot label iOS

**Comment by tsareg** [comment]
@rmevans9, thanks! Definitely, executing code on native side is an option, but this requires duplicating some logic on native side (the request is not so easy), so I was looking for a JS solution if any.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-no-way-to-handle-app-termination-on-js-side

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (65/60 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34510)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6711-000jNj-9Q
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:01 +0000
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c6710-00080F-28
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:28:58 -0700
Date: Sun, 13 Nov 2016 18:28:53 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090537;
	bh=0WmmaveYUrNSFeiqTjRpYJ2jO5mDySYChCl7PJTe5G8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=orzDB56B7zDeh4zsN2Fbm0Uq7sA880gXyWJA3U/H3wwDcvH28pM8jolNJ98Ornjkr
	 r3XTuWOjjD8MkzSYbW+hOvP3SNolSkaY5axrbKwukzQY5S8ApBTqfozqr3nE9P1KmD
	 ne8obxdXNU59TUxjdtj4ti7wMz1DX9td8VpTSZAI=

**Comment by aleclarson** [comment]
Perhaps a Facebook employee that knows more about the native bridge can help us?

It would be a dream come true to handle `applicationWillTerminate` and background tasks from the JS side.

**Comment by jcharlet** [comment]
hi @aleclarson , do you have some code to share to show how to write data on native side to handle app termination as you explained..? I'm using asyncStorage at the moment to store data, and I have no idea how to access/store stuff on native side. Any hint/ things you would recommend looking at?
