### ISSUE TITLE
Systrace doesn't produce detailed JS Thread calls info

### ISSUE THREAD

**Issue by tadas-subonis** [facebook/react-native#9349]
I've tried using systrace like this:

```
C:\Python27\python.exe systrace.py --time=15 -o D:\tmp\traces\trace7.html sched gfx view -a com.insasd
```

but it doesn't show anything for mqt_js thread, apart that it is busy. I wasn't able to see detailed JS calls as shown on the docs. Debug mode is enabled.

Also, I've tried adding

```
import {View, StyleSheet, BackAndroid, StatusBar, ActivityIndicator, Systrace} from "react-native";
Systrace.setEnabled(true);
```

but it throws exception:

```
E/ReactNativeJS(30175): undefined is not a function (evaluating 'global.nativeTraceEndSection(TRACE_TAG_REACT_APPS)')
I/ReactNativeJS(30175): 'Failed to print error: ', 'undefined is not a function (evaluating \'global.nativeTraceBeginSection(TRACE_TAG_REACT_APPS,profileName,args)\')'
E/ReactNativeJNI(30175): Got JS Exception: TypeError: undefined is not a function (evaluating 'global.nativeTraceEndSection(TRACE_TAG_REACT_APPS)') (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:18511)
E/ReactNativeJNI(30175): Got JS Stack: endEvent@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:18511:29
E/ReactNativeJNI(30175): loadModuleImplementation@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:135:18
E/ReactNativeJNI(30175): guardedLoadModule@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:70:32
E/ReactNativeJNI(30175): _require@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:18
E/ReactNativeJNI(30175): http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:1490:21
E/ReactNativeJNI(30175): loadModuleImplementation@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:127:8
E/ReactNativeJNI(30175): guardedLoadModule@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:63:37
E/ReactNativeJNI(30175): _require@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:54:18
E/ReactNativeJNI(30175): global code@http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:12
E/unknown:React(30175): Exception in native call from JS
E/unknown:React(30175): com.facebook.react.devsupport.DebugServerException: TypeError: undefined is not a function (evaluating 'global.nativeTraceEndSection(TRACE_TAG_REACT_APPS)') (http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:18511)
```

I am using WIndows 10 with Android

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/systrace-doesnt-produce-detailed-js-thread-calls-info

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (70/60 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38548)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671F-000jTk-JW
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:15 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671F-00062I-3E
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:13 -0700
Date: Sun, 13 Nov 2016 18:28:59 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090552;
	bh=JKkLa46w45S5IMoRhMCwXjRbW72tdOFoijP2EbX42cQ=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=bz3vA/yrsXL1p2a5R4tdNXHuZf/JAMx+dZFJoNfLeN8bE/XsGlczEwwK3siuTLLqX
	 UiEnL9uKeREpfShOVDlaS3qb/rVT9pbCOIinzTy6K0g4Jb1vy9Qvqk06iCVhu5AORc
	 AlERZNoIezfD6UiWoTDnn+rwaxrcLazzEhTnZgqQ=
