### ISSUE TITLE
[Packager] Production server

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#935]
Hello,

I've noticed that during development we use a development server. 

    (JS_DIR=`pwd`/ReactComponent; cd Pods/React; npm run start -- --root $JS_DIR)

How can I set a production server?

Thanks!
JM

PS: In the `Movies` project I saw that you are starting a server when the app starts. How can I do that?

**Comment by jaygarcia** [comment]
I don't think Apple would approve an app that fetches its logic from a web server. 

Also, the reason the web server launches is because it's hard coded in the build process through scripting. 



JG


:: sent from my mobile device ::

**Comment by iostalk** [comment]
You can just write a node.js static server to archieve it: https://github.com/koajs/static
Before you upload your scripts to the static file folder of server, you have to combine the scripts into one bundle file first: `http://localhost:8081/Examples/2048/Game2048.includeRequire.runModule.bundle -o main.jsbundle`

**Comment by 7ynk3r** [comment]
Thanks for the solutions!!!

**Comment by paramaggarwal** [comment]
In the production version of your app, you would bundle the JS instead of fetching from a development server, like the one in development mode. To bundle the final JS file into your app, follow the instructions here: https://github.com/facebook/react-native/blob/master/Examples/Movies/Movies/AppDelegate.m#L26-L43

**Comment by nicklockwood** [comment]
@jaygarcia As far as we know – based on the new guidelines – Apple don't have a problem with you downloading and running JS code from a server, provided that the app that you release continues to behave substantively the same as the one that was submitted for review.

That said, none of our existing React Native apps at FB are downloading their code in production - they all use static bundled JS as suggested in the documentation.

**Comment by paramaggarwal** [comment]
If a production version of the app were to fetch the JS from the server on launch, it would be incredibly slow. Ideally there should be a bundled version which would update in the background and be used on the next launch of the app - magically updating the app!

**Comment by iostalk** [comment]
So we can embed the js-bundle in the app when being submitted to review, and when published, we can download some new js-bunlde in the background, then we don't need to submit for review any more.

**Comment by nicklockwood** [comment]
@paramaggarwal yes, that would be a better approach in most cases

**Comment by nicklockwood** [comment]
@iostalk provided that you only use the download facility to fix bugs or make very minor feature changes, yes, that seems to be what Apple are suggesting with their latest developer guidelines.

**Comment by jaygarcia** [comment]
@nicklockwood thanks for the heads up.  I must be going by old rules. It's been a while since i've pushed a Hybrid app to the app store personally =)

**Comment by jaygarcia** [comment]
I guess the one thing to remember (per @nicklockwood's comment), is that you can't deploy new ObjC dependencies (static libs, classes, etc) w/out rebuilding & resubmitting to the app store.

Question for @nicklockwood: does FB's current implementation for this type of background-update fail silently?

**Comment by jacobjiangwei** [comment]
@nicklockwood, Does that means we could deploy new feature without release a new app , instead we could just update the JS ?

I heard this is just UI , never thought this could do some logics.

**Comment by jacobjiangwei** [comment]
@nicklockwood, Does that means we could deploy new feature without release a new app , instead we could just update the JS ?

I heard this is just UI , never thought this could do some logics.

**Comment by brentvatne** [comment]
- Packager isn't intended to be run as a production server
- A best practice for updating deployed JS to an App Store-deployed app hasn't been established yet but it would be awesome if someone from the community could come up with a module or blog post for this

@jacobjiangwei - yup, anything that is in the JS, as long as you don't update the native code

**Comment by avnerbarr** [comment]
Is it possible to load the code from NSDocuments directory instead of the main bundle?

**Comment by nicklockwood** [comment]
@avnerbarr yes, you can specify a bundleURL that points to a file inside your documents folder, although you'd need some additional native code that copies a js bundle into the documents folder in the first place before first loading the rootview. There's no way to ship an app with files pre-installed in the docs folder.

**Comment by avnerbarr** [comment]
I opened another question here:
https://github.com/facebook/react-native/issues/1805

In my case the code is created after the matter - so I need to "hot load" it from the documents directory. 

How can I facilitate that?

Thanks
