### ISSUE TITLE
ImagePickerIOS

### ISSUE THREAD

**Issue by xiangfengsu** [facebook/react-native#9350]
Hey there and thank you for using React Native!

React Native, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:
- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). We use StackOverflow for usage question and GitHub for bugs.
- [ ] Have an idea for a feature? Post the feature request on [Product Pains](https://productpains.com/product/react-native/). It has a voting system to surface the important issues. GitHub issues should only be used for bugs.
## None of the above, create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.
- [ ] Provide a **minimal code snippet** / [rnplay](https://rnplay.org/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of React Native you're using?
- [ ] Does this occur on iOS, Android or both?
- [ ] Are you using Mac, Linux or Windows?

**Comment by rmevans9** [comment]
This does not tell us what you are actually creating this issue for. Can you provide details around what issue you are having?

**Comment by rmevans9** [comment]
@facebook-github-bot label Needs more information

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/imagepickerios

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (68/60 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34634)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671E-000jTP-Nv
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:14 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671D-000867-K7
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:12 -0700
Date: Sun, 13 Nov 2016 18:28:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090550;
	bh=v/e97vaXkdAEB1FDHXkezk3HhdRU2LNMsl36LNQvVDY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LvgowTJyNVkv3T/6HTf0DmNdc3PLwsrrsSoHALEa+Pc3uGrUdF3SJcmwJy9zU4Bag
	 z4p59r/p8ZvlIzZhQ6Apodratsilc5qTH+a0vPqSEhSyEpUs6twP+hkvyFPxqBtWWF
	 3ASMt+NrEZaLv0I35cocy+whA30pjm2da3AYph1E=
