### ISSUE TITLE
[iOS] App crashes when trying to display a Red Box error message

### ISSUE THREAD

**Issue by yleflour** [facebook/react-native#9353]
- Device: iPhone Simulator (any)
- OS: OSX 10.11.6
- React Native: 0.26.2
- React CLI: 1.0.0
- watchman: 4.5.0
- environment: development

I am working on a react native project within a team and am the only one facing this issue.
When I launch the app on the iOS simulator, whenever I have an issue in my code the app crashes as it tries to display the Red Box with the error.

![image](https://cloud.githubusercontent.com/assets/1863461/17593444/29b1877e-5fe6-11e6-9503-31791e8b05cc.png)

I haven't found any solution to this issue and seem to be the only one facing it in my team.

What I have tried:
- Reinstalling the project from scratch
- Removing the app from the simulator device
- Creating a new simulator device
- Cleaning and rebuilding the app

As of now, none of these have worked.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/ios-app-crashes-when-trying-to-display-a-red-box-error-message

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (62/60 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34486)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c670v-000jLu-6j
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:28:55 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c670u-0007zH-13
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:28:52 -0700
Date: Sun, 13 Nov 2016 18:28:50 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090530;
	bh=0kR/OLwElESAmm5E4WVGTGb4i01NNMok0QhRWNzFjYI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BZM1KWseMKQZJU8hmR6VjgIjXe8S4z7B8xMCZONcCSIKADzfvhxkXiZ6vW3ubCx0I
	 Ds/FL22j+8HTt7OMH4RBX8iV5dv/Zwg7yzOqdnkV8QRHr+XE0ikPAGTetzAJ7Lvth/
	 NQsVMSHjDZIjvOovEk0/CWAaVOsijbm2MZ4o6xCk=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (74/60 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34678)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671T-000jZ8-9V
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:28 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671R-00088k-Uh
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:27 -0700
Date: Sun, 13 Nov 2016 18:29:00 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090565;
	bh=CePWQt+mYoew0gUQ1mvUGBVqmgQVsCZl4SnOoGyO4Uo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=2YgKIZKI+q5GYgLXMxTW27M1J0c02/6kiyYB6Ip4kBpPMkWg4mKBbb94dbigfiOqb
	 mVe1Y6uOnb99+yBdn9EdXe90VczVXgwQNBdgfSvTAKrRccMLf05VwsvduCGmVI0Had
	 kMk40rlysh8ch4G3uYx33za+PDTaEjqyvHWLjZZk=
