### ISSUE TITLE
_this2.setState is not a function error in react-native

### ISSUE THREAD

**Issue by tinajohnson** [facebook/react-native#9357]
I have this code for a drop down menu: 
```
    <Picker
        selectedValue= {() => {this.state.attendance}}
        onValueChange= {(att) => this.setState({attendance: att})}>
        <Picker.Item label="Present" value="present" />
        <Picker.Item label="Half Day" value="halfday" />
        <Picker.Item label="Informed Absent" value="in-absent" />
        <Picker.Item label="Uninformed Absent" value="un-absent" />
    </Picker>
```
But I get an error, "_this2.setState is not a function" on running the app. I know how react-native doesn't auto bind, but from my research the arrow syntax ought to fix it. Anyone knows why this error is still being throw?

**Comment by tinajohnson** [comment]
People on #reactnative IRC channel helped out! Realised it was the enclosing function that required the binding,
```
renderRow={this._renderRow.bind(this)}
```
Added .bind(this), and worked like a charm.

**Comment by mobilemaster5** [comment]
Thank you @tinajohnson !
