### ISSUE TITLE
iOS Release Build Instructions Out of Date

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#9358]
[Documentation](https://facebook.github.io/react-native/docs/running-on-device-ios.html) on how to build a release for production—or even how to get an app to run without the development server—seem out of date. It would also be useful for it to be completely beginner friendly: stuff like development schemes aren’t too obvious if you haven’t done it before!

I would be happy to add to the documentation. However, I have no idea how to get a build that doesn’t use the development server.

**Comment by kirandwarkan** [comment]
It does seem that the latest version does not generate the line mention under the "Using the offline bundle" subheading of the [Documentation](https://facebook.github.io/react-native/docs/running-on-device-ios.html) page. 
Try substituting the jsCodeLocation line in the AppDelegate.m to 
"jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];"
During the build, a "main.jsbundle" is put into the app package. That's what this line of code will try to find.

**Comment by rmevans9** [comment]
@facebook-github-bot label Documentation

**Comment by kirandwarkan** [comment]
Looking into this a bit more. The "Running on Device iOS" for React Native 0.31 should have had the same instructions as the [current master](https://github.com/facebook/react-native/blob/master/docs/RunningOnDeviceIOS.md).
Would it be worth adding explicit instructions about clicking on the project name in the toolbar in XCode to expose the "Edit Scheme" options and selecting release for the build configuration?

**Comment by ericvicenti** [comment]
It looks like this doc has been fixed. Thanks for bringing this to our attention!

https://github.com/facebook/react-native/commits/master/docs/RunningOnDeviceIOS.md
