### ISSUE TITLE
Static Image Assets not picking up @2x and @3x images

### ISSUE THREAD

**Issue by tonyrzhang** [facebook/react-native#9359]
Hello!

Is there anything I have to do to get the @2x, @3x images to start working? I have an image component that is using this as the source `require('../img/logo.png')` and in my img folder I have `logo.png`, `logo@2x.png`, and `logo@3x.png`, but it isn't getting the larger images. Is there a step I"m missing here?
And just to clarify they're currently just in my `js/img` folder, not in xcode or android studio.

Thanks

**Comment by tonyrzhang** [comment]
Fixed the issue on my end.

**Comment by tonyxiao** [comment]
@tonyrzhang is it expected to automatically work then?

**Comment by shoshi** [comment]
@tonyrzhang What was the solution for you?

**Comment by devanshsadhotra** [comment]
@tonyrzhang  , what was the solution?
