### ISSUE TITLE
Help me make the subview beyond borders of parent view in android

### ISSUE THREAD

**Issue by namduongkh** [facebook/react-native#9367]
apologize for my english
i have two view:

`<View style={{position: 'absolute', top: 0, left: 0, height: 100, width: 300}}>
     <View style={{position: 'absolute', top: 50, left: 0, height: 100, width: 100}}>
     </View>
</View>`

but subview can not exceed the borders of parent view when run in android
please help me fix

![screen shot 2016-08-12 at 9 17 24 am](https://cloud.githubusercontent.com/assets/17775345/17611045/de021cde-606d-11e6-9238-181de61fc9c1.png)

**Comment by ide** [comment]
Overflow is not supported on Android. You will have to make the parent view larger.
