### ISSUE TITLE
Testing Jest Documentation Outdated

### ISSUE THREAD

**Issue by loopdtw** [facebook/react-native#9371]
Platform: Mac 10.11.6 El Capitan
React Native Version: 0.30.0
The documentation for testing with jest doesn't work as described.

Will result in the following screenshot
![2 bash](https://cloud.githubusercontent.com/assets/19647583/17616390/01067ff2-60a7-11e6-8dfd-6292412f2d05.jpg)

**Comment by brentvatne** [comment]
cc @cpojer

**Comment by cpojer** [comment]
Please use http://facebook.github.io/jest/docs/tutorial-react-native.html#content

(there is a small issue with 0.31 right now but we are fixing that).
