### ISSUE TITLE
[WEIRD PROBLEM] ios use much more memory when js debugging is disabled than enabled

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#9376]
It's really weird.
When I enable remote JS debugging, the xcode memory monitor show my app only use about 40MB memory. Even I display a lot of images it only use about 50MB.
But if I disable the js debugging, the memory use will be around 100MB and when a lot of images shows it will exceed 300MB.

I am using react-native 0.27.2

**Comment by narychen** [comment]
Enable and disable operation is using the dev menu, not turn off it in AppDelegate.m.

**Comment by narychen** [comment]
And I feel that my app run a bit faster when debugging is enabled. I run it on iphone 5 device.

**Comment by ide** [comment]
When you enable remote JS debugging, the JS runs remotely and you're using Chrome's JS heap instead of JSC's so this is expected.

**Comment by narychen** [comment]
@ide I just thought about this cause.  Thanks.
