### ISSUE TITLE
RefreshControl blocks onScrollEndDrag events

### ISSUE THREAD

**Issue by Deadlysmile** [facebook/react-native#9377]
On Android when scrolling to 0 offset refresh control starting mounting, and scrolling stops, you can't even scroll again with current touch, but events(onScrollEndDrag) not triggered. If you poll down enough you surely get triggered 'onRefresh' event from 'RefreshControl' where you can at least know that offset is 0, but if you don't poll enough... 
Maybe there any workaround, or i'm missing something?

```
handleScrollEndEvents(e){
  console.log(e)
}
render() {
  return(
    <ListView
      ref={(c) => this._list = c}
      refreshControl={
        <RefreshControl
          refreshing={this.state.isRefreshing}
          onRefresh={this._onRefresh}
        />
      }
      onMomentumScrollEnd={this.handleScrollEndEvents}
      onScrollEndDrag={this.handleScrollEndEvents}
    />
  )
}
```

**Comment by rmevans9** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/refreshcontrol-blocks-onscrollenddrag-events

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (64/60 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34508)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6710-000jNb-QX
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:00 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c670z-000806-Id
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:28:58 -0700
Date: Sun, 13 Nov 2016 18:28:43 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090536;
	bh=HTtebHlZylHhPlOKNMgR4vXwykt8SG8He89TV+NpG1c=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=dRbADSsFRItpL4THiQV4QxlPKUL7vUjyn+e65TpAdbxS6hWH4AilurRGZ8rfz21eK
	 76MU2g47Yl1H3FkmCgmLJCxHfIoBnWJPDWGnPNUUsq1sHCv1mjGqBY9ykmKr+0ZyX5
	 eIsulEZJeUeMV/J4nzt/fJMK6OztLJZlsfSd1t2I=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (69/60 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38546)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671E-000jTY-Vv
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:14 +0000
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671E-000629-ER
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:13 -0700
Date: Sun, 13 Nov 2016 18:28:48 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090552;
	bh=/9An2Fd2Jq57ERyOLDQv3FNqnLMME57YoGgp2wnJSno=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1wpsmk6Uz9DYf+EVlpCJShuvkT1g0BUB+qsdLGRDFB68yK/g9/nuaSt95QqnISOov
	 kVdx9IPcE0CgSw6Hma+4viJuAp+BMp+/Ny/ubYuco4wXOw/+yvcpfQrB70djjruRpf
	 +Vt2SUDf8xVW47oP4k9Zg1E6028tf7blYD7z4DXQ=

**Comment by raynor85** [comment]
Given e an event coming from an async action, console.log(e) messes up the log system and sometimes the IDE get stuck, preventing you from seeing any further logs before suddenly presenting a dump of never ending log nonsense, so I strongly suggest to avoid doing so. Your issue could be simply related to this. Try to use console.log(!!e) instead, or try logging other more meaningful and reasonably smaller properties to display.
