### ISSUE TITLE
Chrome network requests

### ISSUE THREAD

**Issue by knapeto** [facebook/react-native#9378]
Hey,

I need show http requests. When I updated to new version of Reac-native (0.31.0) React (15.2.1), feature with delete 
```javascript
import { View, Text, StyleSheet } from 'react-native';
GLOBAL.XMLHttpRequest;
```
show error `ReferenceError: XMLHttpRequest is not defined`.

I read somewhere that it can be implemented by Charles. Do you have some experience to draw up guidance on how to achieve a listing of HTTP requests?

RN version 0.31.0

@ide Thanks you for reply!

**Comment by ide** [comment]
I recommend Charles Proxy or similar proxy software. The Chrome debugger is not a faithful representation of JSC on the device for several reasons (different JS VM, different performance characteristics, entirely async) and Chrome's network stack is different than the device's. So if you want to debug what is truly going on in your app you should use a network inspector that works with your device.

Get Charles Proxy here: https://www.charlesproxy.com. There is a free trial and if you find it useful it's $50 to keep using. All of the documentation for how to use it is here: https://www.charlesproxy.com/documentation. I recommend reading the section that says "iOS" on this page https://www.charlesproxy.com/documentation/faqs/. It tells you how to debug network connections from iOS apps, there's nothing different about React Native so do the same as you would for any other iOS app.
