### ISSUE TITLE
Android com.facebook.react.bridge.Arguments::createMap() crashes after the first time

### ISSUE THREAD

**Issue by fabriziomoscon** [facebook/react-native#9379]
My Android app crashes when `com.facebook.react.bridge.Arguments` :: `createMap()` is called after the first time.

react-native: **`0.31.0`**
Platform: real device Nexus 4 5.1.1 API level **22**
code example:
https://github.com/fabriziomoscon/react-native-twilio/blob/b723e0718d99e95a070ae2ea1216b5f2e0c38e3b/android/src/main/java/com/rogchap/react/modules/twilio/TwilioModule.java#L336

logcat:

```
08-12 19:25:31.999 1991-2748/com.numberhack.debug D/MediaManager: playing sound DISCONNECT as id 4
08-12 19:25:32.001 1991-2822/com.numberhack.debug D/SoundPoolPlayThread: starting playback
08-12 19:25:32.562 1991-1991/com.numberhack.debug D/MediaManager: play complete for stream 4
...
08-12 19:25:36.877 1991-1991/com.numberhack.debug I/Choreographer: Skipped 132 frames!  The application may be doing too much work on its main thread.
08-12 19:25:43.436 1991-2748/com.numberhack.debug D/com.rogchap.react.modules.twilio.TwilioModule: onDisconnected with errorConnection declined
08-12 19:25:48.493 1991-2748/com.numberhack.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x74 in tid 2748 (Thread-63380)
```

it always crashes at this line: 
https://github.com/facebook/react-native/blob/d344963123142a08de9d64d0c2d1294f8fcad8a6/ReactAndroid/src/main/java/com/facebook/react/bridge/WritableNativeMap.java#L63

Using Android studio debugger I narrowed down the problem and I can reproduce it 100% of the time. I am not sure if I am using `WritableMap` correctly, but I got it working similarly in other parts with no crashes.

Any help is appreciated.

**Comment by ggsrivas** [comment]
@fabriziomoscon  I am facing same issue. Have you got any solution?

**Comment by fabriziomoscon** [comment]
nope, still same situation...

**Comment by ggsrivas** [comment]
@fabriziomoscon  I could figure out the problem in my case. I was trying to send Event to React native from native android as mentioned in below example,
https://facebook.github.io/react-native/docs/native-modules-android.html#sending-events-to-javascript

In my case, reactContext value was not. Probably, react native was not loaded completely. When I tried to trigger sendEvent, after everything was loaded and reactInstanceManager was initilaized, it worked fine. I understand that it might not help you fix your issue, but you can definitely check whether all required modules are correctly loaded or not.
