### ISSUE TITLE
[Bug][Android] NativeMethodMixins don't work unless the view has a native property

### ISSUE THREAD

**Issue by hey99xx** [facebook/react-native#9382]
NativeMethodMixins don't work unless the view has a native property. As far as I know this bug only happens on Android, I'm testing with a device on Android Marshmallow API 23, according to one of my coworkers the example below has no issue on iOS.

I've brought down my test case to this simple component.

```javascript
class MyComponent extends React.Component {
    render() {
        return (
            <View ref="myView" style={{opacity:1}}>
                {this.props.children}
            </View>
        );
    }
    componentDidMount() {
        this.refs.myView.measureInWindow((x,y,width,height) => {
            console.log(x,y,width,height)
        });
    }
}
```

When you render this component, you should see something like `0 0 50 0` in the console while debugging with Chrome. Now if I remove `style={{opacity:1}}` part, I get `undefined undefined undefined undefined` in the console. The expected behavior is I should keep getting the same log even when the style prop is removed.

Putting break points in NativeViewHierarchyManager#createView method, it was never invoked with `myView` when the native property is removed. I check which views are created on the native side by printing with `findNodeHandle` function.

**Comment by rmevans9** [comment]
@facebook-github-bot label Android

**Comment by hey99xx** [comment]
I suspect NativeViewHierarchyOptimizer would be responsible of this bug. If React detects that `myView` is simply pass through and does not create its native view (android.view.ViewGroup), NativeViewHierarchyManager will not be able to find the actual native views even when they're requested. When I do put a style property, React likely detects that the view needs a native view. 
I'm not going to be able to confirm my suspcision until Monday when I'll be in office. Hopefully an Android engineer ( @mkonicek ?) would see this bug report soon.

**Comment by hey99xx** [comment]
Since I've created this bug, I have verified my suspicion that the backing native view was never created. Now I always force it to be created with collapsable property. It's a minor annoyance, but I can live with it.
