### ISSUE TITLE
Sticky section headers on iOS do not work if ListView has contentContainerStyle with paddingTop

### ISSUE THREAD

**Issue by brentvatne** [facebook/react-native#9384]
Feel free to set paddingBottom, that works fine. But paddingTop breaks it - no section header ever "sticks" - workaround for now is to use marginTop or set padding on a container of the ListView.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/sticky-section-headers-on-ios-do-not-work-if-listview-has-contentcontainerstyle-with-paddingtop

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (71/60 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38550)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671H-000jUr-Ky
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:16 +0000
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671H-00062f-84
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:15 -0700
Date: Sun, 13 Nov 2016 18:28:49 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090554;
	bh=xgcdQcpGLoTRxi6K3gJ5qbMC0uXLq3qjOO5OqeLaSn0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=18kGxaa//SGDqjNdS8E/rO603sGfudDXH+0gyCPwJTxYcOYI+4yt723wakjhmgY2P
	 etf3qXREsqaht5Dt4GPaxkx3pD0sj+10xjNbH/+gmZoy5yXYpJPSprfRwQL4vgqJmn
	 lzs4lB84N1Ft3oGR7Ey5+tlmVsrBaeTqnCZs0H1E=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (73/60 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:38556)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c671L-000jWh-NQ
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:29:21 +0000
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c671L-000635-Ag
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:29:19 -0700
Date: Sun, 13 Nov 2016 18:28:51 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090558;
	bh=qeEUgh9eJsj+85LfNXx222l5H/Tw36zpPupKtZVD9WY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jMAwk2te8l5mSmBx3hwRMZVHWrpXnBKVz/qSph4yGADcpJy1jns+I6u2HeVf5JwmU
	 f0utEfq7rAHFrSlOl1IKV78PZCA/NJoKKZsEa9UnTDq7sI5heSBt/gCgmQM0bZ/ADG
	 NJGR46852M08opWYTmQstTwHTML5GxRnNdkYUxQo=
