### ISSUE TITLE
borderRadius, overflow and flex scaling

### ISSUE THREAD

**Issue by Duelsik** [facebook/react-native#9385]
I have hard time with overflow in borderRadius'ed box with flex items in it.

https://rnplay.org/apps/Prov-g

screenshoot:
![pobrane](https://cloud.githubusercontent.com/assets/8364951/17642419/55d15026-6146-11e6-93bb-3e9240b659ee.png)

I think the 'not cropping' behaviour is incorrect, and I expect cropping in this case.
I am using 0.31 rn and it happens in android (tested on device and rnplay) and iOS (tested in rnplay).
I am coding under Windows 10.

**Comment by stoffern** [comment]
add `overflow: 'hidden' `

**Comment by Duelsik** [comment]
Done, but it is not fixing my problem (it was there before, but it wasn't work [container])

**Comment by Liroo** [comment]
overflow: 'hidden' i not working well on Android, I'm getting the same issue 🆙

**Comment by lacker** [comment]
I think this overflow behavior will get fixed in an upcoming overhaul to the layout engine. I estimate January or February release

**Comment by stoffern** [comment]
dupe https://github.com/facebook/react-native/issues/3198
@hramos 😉
