### ISSUE TITLE
How do I navigate/slide left or right with React Native?

### ISSUE THREAD

**Issue by martco** [facebook/react-native#939]
![slide_right](https://cloud.githubusercontent.com/assets/420959/7244366/415ef8c8-e78f-11e4-8a3a-498ffc082e86.gif)

I want to be able to tap on a row in a list and slide to the right to view a related view. How do I do that with React Native? I'm using `translate3d` in the gif above.

**Comment by chrisalexander55** [comment]
Look in react-native/examples/uiexplorer.

**Comment by mjw56** [comment]
You could use [Navigator](https://facebook.github.io/react-native/docs/navigator.html#content) and push a route when you tap on a row.

**Comment by martco** [comment]
@mjw56 @chrisalexander55 you sirs, are gentlemen and scholars
