### ISSUE TITLE
ScrollView's ScrollTo is not working.

### ISSUE THREAD

**Issue by jo2010** [facebook/react-native#9392]
My scroll views changes dynamically after the initial render. I want to scroll to bottom automatically every time when the content change.

_onContentSizeChange(contentWidth, contentHeight) {
    this._scrollView.scrollTo({ x: 0, y: contentHeight, animated: false });
  }

```
  <ScrollView
    ref={(c) => { this._scrollView = c; }}
    onContentSizeChange={this._onContentSizeChange}
  >
 </ScrollView>
```

even tried with the following code

```
_onContentSizeChange(contentWidth, contentHeight) {
    InteractionManager.runAfterInteractions(() => {
      this._scrollView.scrollTo({ x: 0, y: contentHeight + 200 , animated: false });
       console.log("called _onContentSizeChange  contentHeight" + contentHeight );
    });
  }
```

```
 componentDidUpdate() {
    InteractionManager.runAfterInteractions(() => {
      this._scrollView.scrollTo({ x: 0, y: 1000, animated: false });
       console.log("called componentDidUpdate");
    });
  }
```

Also, tried calling scroll in an button click event

**Comment by jo2010** [comment]
Ignore this. I found out it was because of scrollview within a scrollview.

**Comment by scarlac** [comment]
@jo2010 Can this be closed? Seems like you may have re-opened it by mistake.

**Comment by stoffern** [comment]
@ide repoened thisone. why?
