### ISSUE TITLE
Failed to build DependencyGraph: Watchman error: query failed: synchronization failed: Operation timed out.

### ISSUE THREAD

**Issue by ptaking** [facebook/react-native#9395]
I have searched for this issue and seemed like no one have exact solution for this. I've tried to restart packager, watchman and my computer too.
![nh ch p man hinh 2016-08-14 luc 16 53 33](https://cloud.githubusercontent.com/assets/12915431/17648450/2ca00076-6240-11e6-925a-c0fd9fcb2b03.png)

```
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/anhpt/Documents/ReactProjects/sample

[4:50:26 PM] <START> Building Dependency Graph
[4:50:26 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[4:50:30 PM] <START> request:/index.ios.bundle?platform=ios&dev=true&minify=false
[4:50:30 PM] <START> find dependencies
Failed to build DependencyGraph: Watchman error: query failed: synchronization failed: Operation timed out. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
Error: Watchman error: query failed: synchronization failed: Operation timed out. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
    at /Users/anhpt/Documents/ReactProjects/sample/node_modules/node-haste/lib/crawlers/watchman.js:63:11
    at process._tickCallback (node.js:406:9)

```

watchman 4.6.0
OS X 10.11.2

**Comment by ptaking** [comment]
Anyone here?

**Comment by vshy108** [comment]
Get some hints here?
#2191

**Comment by ptaking** [comment]
I've tried everything in there. I also tried to manually start `watchman watch` but it is still not working.

**Comment by neverlous** [comment]
the same issue

**Comment by sajjidakr** [comment]
same issue , anyone with the answer ?

**Comment by petehouston** [comment]
Some recommendations:

* The project directory is mapped or symlink-ed by other apps or services, such as mapping with Vagrant box, mapped as a Dropbox directory... Don't do this, watchman will fail to watch.
* Re-install Homebrew and watchman if you upgrade your OS X version. Any OS X update will mess with Homebrew directory. 
* Give sufficient read/write permission to directory. `0644` will be fine.
* Completely clear all node caches. Make sure to run npm or Yarn as regular users. Execute them as superuser will cause node modules completely stranger and can't be watched.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
