### ISSUE TITLE
The TextInput`s Paste toolTip can not set chinese, i already set the language and keyboard to  chinese, but not effective.as follows

### ISSUE THREAD

**Issue by MingYe-dz** [facebook/react-native#9407]
@![image](https://cloud.githubusercontent.com/assets/19658375/17656055/4386f44a-62e8-11e6-9914-0cf3209fba0c.png)

**Comment by lavystord** [comment]
Open `Xcode`,click `TARGET -> Info -> Custom iOS Target Properites -> Localization native development region` and select `China`

**Comment by MingYe-dz** [comment]
great， it works！ thank you very much

**Comment by lavystord** [comment]
@facebook-github-bot answered
