### ISSUE TITLE
First touch action in component first time rendering is never triggered 

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native#9409]
My components are under NavigationExperimental.CardStack.
Let say I have touchable button in Main page,
after the Main page first time rendered,
the first time I click the touchable button, it never trigger the onPress event.
But it will trigger if it is not first time click and the page is not first time be rendered.
I have no clues how to solve this. thanks.

**Comment by jairtrejo** [comment]
I have a similar problem. If I use CardStack it renders my views just fine, but inside it touch events stop working altogether. Did you manage to figure it out, @vshy108 ?

**Comment by jairtrejo** [comment]
I was inadvertently modifying the navigationState object before doing setState, fixing that got rid of the problem. It might also be related to changing it during a transition.
