### ISSUE TITLE
Is there something wrong with TouchableOpacity?

### ISSUE THREAD

**Issue by ele828** [facebook/react-native#941]
When I use the ``TouchableOpacity`` I met a problem

If the element has opacity style, like {opacity: 0.5}, which is the  child element of the TouchableOpacity, When I click this element and then this element's opacity goes wrong, maybe it turns to {opacity: 1}. I think normally it should go back to 0.5.

Thanks

**Comment by brentvatne** [comment]
@ele828 - you are correct, it [sets it back to 1.0](https://github.com/facebook/react-native/blob/master/Libraries/Components/Touchable/TouchableOpacity.js#L107-L115) - I'm not entirely sure I understand your use case though, sometimes code is the best language - can you post an example please? :smile:

**Comment by ele828** [comment]
Yeah, of course.
	<TouchableOpacity activeOpacity={0.3} onPress={this._search}>
		<View style={styles.searchButton}>
			<Text style={styles.searchText}>Search</Text>
		</View>
	</TouchableOpacity>

	searchButton: {
		width: 120,
		height: 50,
		top: 35,
		opacity: 0.7,
		alignSelf: 'center',
		borderRadius: 10,
		borderColor: '#da766b',
		backgroundColor: '#e01a3c',
		borderWidth: 1,
	}

**Comment by brentvatne** [comment]
@ele828 - thanks, that definitely looks like a bug

**Comment by brentvatne** [comment]
@ele828 - moved discussion over to #977 where I provide a fix, thanks! :smile:
