### ISSUE TITLE
[Android 6.0+] StatusBar translucent={true} doesn't works

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#9413]
I've found a problem: on Android 6.0+ status bar doesn't renders as it must with ```translucent={true}``` enabled. 
On Android 4.4+ and Android 5.0+ it works as expected.

Here is my status bar code:
```
<StatusBar
 animated={true}
 barStyle={barStyle}
 backgroundColor={backgroundColor}
 translucent={true}
 showHideTransition={'fade'}
/>
```

Tested on: 
RN 0.31.0
Google Nexus 5x  (Android 6.0)
Google Nexus 4 (Android 5.0)
Meizu MX (Android 4.4.4)

**Comment by satya164** [comment]
Can you post a screenshot?

cc @janicduplessis

**Comment by alexHlebnikov** [comment]
Hi @satya164 ! 

Here is screenshot from emulator. 
![screenshot 2016-08-16 03 06 58](https://cloud.githubusercontent.com/assets/1951398/17677823/b46d0fa2-635e-11e6-8ef5-74805fdbcc1e.png)

The StatusBar must be semitransparent and behind the app header. But it's on top of app screens. And because of that every app screen is now shifted down by the StatusBar on it height. 

I must say, what on 0.29.0 and 0.30.0 (as I remember) there was no such behaviour with StatusBar.

**Comment by mehcode** [comment]
Can confirm that at least on RN 0.30.0 `<StatusBar translucent/>` works as expected. Haven't upgraded to 0.31.0 but was planning to today and will update if I see this regression as well.

**Comment by alexHlebnikov** [comment]
@mehcode @janicduplessis 

Now I can confirm the same problem on Nexus 5x with Android 7.0 and RN 0.31.0. 

![screenshot_20160816-114615](https://cloud.githubusercontent.com/assets/1951398/17688615/06eb7556-63ab-11e6-9a36-b3687ebf1066.png)

Also, I can confirm the problem is *not* reproduced on same device, but on RN 0.30.0.

**Comment by alexHlebnikov** [comment]
Also checked RN 0.32.0 RC.0 - same problem there.

**Comment by nihgwu** [comment]
I'm using the `StatusBar` with the same props and it works as expected on those RN versions
Google Nexus 6, 6.0.0

**Comment by mehcode** [comment]
To follow up -- I also have no problems with `translucent` in Android 6.x / RN 0.31.0

---

@alexHlebnikov To try and understand where @nihgwu and I differ from you, how do you use `<StatusBar/>` ?

I have a single `<StatusBar />` component that is rendered near the root view as

```
<StatusBar translucent backgroundColor="rgba(255, 255, 255, 0)" />
```

I use a borderTop to give a color under the statusBar depending on the needs of the scene.

**Comment by alexHlebnikov** [comment]
@mehcode I'm using single ```<StatusBar />``` inside my root view. Here is my code:
```
<StatusBar
  animated
  barStyle={barStyle}
  backgroundColor={backgroundColor}
  translucent
  showHideTransition={'fade'}
/>
```

I checked RN 0.30.0 on Nexus 5x and StatusBar shows great, just like it must be. 
But on RN 0.31.0 and 0.32.0.RC it's always shows incorrectly.

**Comment by alexHlebnikov** [comment]
Hmm. It might sounds strange, but could the issue be connected with Android permissions? 
Permission politics was changed on Androids 6+. I'm detecting user geolocation in my app. Before the app launches on Android 6+ there is a system popup asking for geolocation. Could it be because of that? On Android 4 and 5 there is no such popup.

Permissions I use:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by janicduplessis** [comment]
@alexHlebnikov I know there is an issue about Modals + StatusBar that cause not work properly, you may be right and it could be related. Maybe try removing the permission request to test.

**Comment by alexHlebnikov** [comment]
@janicduplessis thanks, I'll try turn off permissions and then share the results.

**Comment by alexHlebnikov** [comment]
@janicduplessis @mehcode

So here is what I found.
Here is the lines of code I removed from AndroidManifest.xml:
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
```

__Without this code (StatusBar is correct)__ :
![without-geo](https://cloud.githubusercontent.com/assets/1951398/17771998/7739c09e-6570-11e6-87ca-4629c02913d0.gif)

__With this code (StatusBar is broken)__ :
![with-geo](https://cloud.githubusercontent.com/assets/1951398/17772021/a65d2000-6570-11e6-94de-69d8e51093cf.gif)

So, the problem is in Android system modal.

**Comment by alexHlebnikov** [comment]
I've almost forgot. 
For permissions handling, I'm using this package - [react-native-android-permissions] (https://github.com/lucasferreira/react-native-android-permissions)

If there is some other way to make geolocation permission work on Android 6.0+ without this package - I'm gladly try it.

**Comment by satya164** [comment]
@alexHlebnikov there's a `PermissionsAndroid` module in master. Not released yet though.

**Comment by mehcode** [comment]
@alexHlebnikov Do you ask for permissions immediately? It looks like it. Try waiting a bit (eg. after the first render cycle). I use that same module but don't ask immediately and it works fine.

**Comment by janicduplessis** [comment]
Here's the related issue: #7474. StatusBar uses [this](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/statusbar/StatusBarModule.java#L125) to get the decor view and add a `OnApplyWindowInsetsListener` to it. Maybe it gets the wrong view when a dialog is opened. If someone could look into it it would be great :).

**Comment by janicduplessis** [comment]
If waiting a bit before asking for permissions (setTimeout) does fix it it would probably confirm my theory.

**Comment by alexHlebnikov** [comment]
@mehcode @janicduplessis yes, I'm asking for permissions immediately. 
Thank you guys, I'll try yours suggestion and tell about the results.

**Comment by alexHlebnikov** [comment]
Yep, it worked! Huge thanks for help guys!
