### ISSUE TITLE
Is offload animation ready for navigator?

### ISSUE THREAD

**Issue by narychen** [facebook/react-native#9421]
It's been a long while since the [production pain ](https://productpains.com/post/react-native/offload-some-animations-from-js-thread-for-better-perf) has been launched.
I saw there were both ios and android PR has been merged.
But the [official doc](https://facebook.github.io/react-native/docs/performance.html) says nothing about it.  The performance bottleneck of navigator is still there.

**Comment by DanielMSchmidt** [comment]
I think there was a talk about this at the last [react-conf](https://www.youtube.com/watch?v=0MlT74erp60#t=18m46s) and I think there were also some mentions in this video from the [react-europe](https://www.youtube.com/watch?v=1oL_OJ3UePU).

What would you like to see included in the docs?

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot label Documentation

**Comment by narychen** [comment]
@DanielMSchmidt The first video you gave is too early to be related to what I'm talking about.
The second video is all about the JIT of react-native. So I think you might be mis-understanding what I mean of  offloading animations

**Comment by DanielMSchmidt** [comment]
Yes, seems so, sorry about that

**Comment by satya164** [comment]
We also need to move to `Animated.Event` instead of calling `setValue` directly in `NavigationExperimental`. Would be great if someone can send a PR for that.

**Comment by narychen** [comment]
@satya164 Does the old navigator has some plan of it ? Since a lot of project use navigator already rather than NavigationExperimental. It's  a lot of work to migrate to the new one.

**Comment by satya164** [comment]
@narychen I think the old navigator doesn't use `Animated`. So it won't be possible to use native animations there.

**Comment by narychen** [comment]
@satya164 Does the new NavigationExperimental enable offloading animation ?

**Comment by satya164** [comment]
It doesn't now. But since it uses `Animated`, it'll be possible once the work on native animations is complete.

**Comment by narychen** [comment]
@satya164 Will the NavigationExperimental be the official support of navigation? Should I migrate all my navigator code to NavigationExperimental?

**Comment by satya164** [comment]
@narychen Yes, it'll be the officially supported way going forward. If you're migrating to `NavigationExperimental`, keep in mind that while it's pretty stable as of now, there are small API changes here and there every release.

**Comment by nickhudkins** [comment]
I'd love to see this move forward. What can I do to help out here? Has work begun to use Animated.Event rather than setValue?

**Comment by ptomasroos** [comment]
Android Animated.Event has landed in master but IOS is still waiting in line being pulled. But you should def be able to run native offloading and Android and fork against migrating setValue to Animated.Event

https://github.com/facebook/react-native/pull/9253
https://github.com/facebook/react-native/pull/9598

**Comment by nickhudkins** [comment]
To make sure I understand what is between the current implementation and offloading the animations:

1.) The animations need to be configured to `useNativeDriver`. This piece is quick and simple.
2.) onLayout needs to be moved to an implementation that leverages Animated.event.

Am I missing any other pieces here?

**Comment by nickhudkins** [comment]
For those who want to follow along: #10289 implements this change

**Comment by narychen** [comment]
I've tried the current implementation of offloading. Found that a lot of property such as view's height cannot be animated in native. Will this be fixed in the future or just never be done?

**Comment by K-Leon** [comment]
@nickhudkins I've seen u closed your Pull Request. Native Events haven't been working well enough yet?

**Comment by nickhudkins** [comment]
I ended up merging in master and butchering another merge and couldn't get
my test suite running properly so I closed it for now so that it isn't just
sitting open untested and messy. I'll re-open again once I can ensure
passing tests. Native Events however work wonderfully and make an enormous
improvement.

**Comment by K-Leon** [comment]
Great work! Thank you very much for your effort - I'm looking forward to see this landing it will be a real gamechanger.

**Comment by lacker** [comment]
The original question is answered so I am going to close this issue. Thanks folks for helping out!
