### ISSUE TITLE
[Android][0.30.0] image not show when use specific bundle js file

### ISSUE THREAD

**Issue by InnerPeace080** [facebook/react-native#9422]
I write a application can update js file via network . But when i run from downloaded js bundle file, image is not showing

i use " require('./abc.png') " for source of image component .

Everything fine with react native version 0.17 . (i writed a application have this feature with react native 0.17)

Do anyone know how to fix it? thank you

**Comment by rmevans9** [comment]
How are you updatting the js via the network? Are you using something like Code Push or AppHub?

**Comment by InnerPeace080** [comment]
i write my own module . Task is simple, i download bundle file and place it into data folder of app and then i overwrite getJSBundleFile() function in MainApplication.java to point to my downloaded bundle file.

for now. i resolve this problem by use object {uri:''} for source prop of image.

**Comment by rmevans9** [comment]
I am not sure that the issue here is related to React Native but rather just how you are handling updating the JS. Check out Code Push or AppHub as they both do about the same thing and they are able to pull images with updates as well. Closing this since this is not a React Native issue.

**Comment by rmevans9** [comment]
@facebook-github-bot close
