### ISSUE TITLE
Is it possible to style the standard react-native android picker?

### ISSUE THREAD

**Issue by abhisheklf** [facebook/react-native#9430]
I am unable to style it. There is hardly any documentation on styling Picker. I want to know how to set the fontFamily. How to set the color and background color on the Picker.items?

https://facebook.github.io/react-native/docs/picker.html

Setting fontFamily or background color doesn't work. Wrapping it up in a View and giving style attributes to View also doesn't work.

```
<Picker
   style={styles.picker} // cannot set fontFamily here
   selectedValue={this.state.selected2}
   onValueChange={this.onValueChange.bind(this, 'selected2')}
   mode="dropdown">
   <Item label="hello" value="key0" /> // cannot set backgroundColor here
   <Item label="world" value="key1" />
</Picker>

```

here is the snippet on RNPlayground
https://rnplay.org/apps/oAR0qA

I posted a question on SO but didn't get any answers:
http://stackoverflow.com/questions/38921492/how-to-style-the-standard-react-native-android-picker

I am using RN 0.29 , Android and working on a Mac

**Comment by rmevans9** [comment]
React Native uses the standard Android Spinner for the picker. To customize what you are looking for you will do it just like you would in Android... with the Android theme. Some of the attributes are able to be set in React Native via the style but some of the more core elements of the picker (like the font used) is driven by native Android. To update the style for Android you would do something like:

http://stackoverflow.com/questions/13703233/style-android-spinner

**Comment by rmevans9** [comment]
@facebook-github-bot answered

**Comment by abhisheknalin** [comment]
Thanks for the pointer. Unfortunately I am not a native andorid developer so I have trouble understanding the solution. I added the following snippet to /res/values/styles.xml but nothing changed.

```
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
    </style>
    <style name="SpinnerItem">
        <item name="android:textColor">#993399</item>
        <item name="android:background">#993399</item>
    </style>
    <style name="SpinnerDropDownItem">
        <item name="android:textColor">#993399</item>
        <item name="android:background">#993399</item>
    </style>

</resources>

```

Do I need to make changes elsewhere also?

**Comment by abhisheknalin** [comment]
I solved it with the help of SO community. See the solution here: http://stackoverflow.com/a/39141949/2381508

**Comment by rulgf** [comment]
@abhisheknalin It works great, thanks. Do you know how can I use a custom font for the spinnerItem?

**Comment by appielife** [comment]
Is it possible to center align the text item in both picker parent and dialog . 
Can someone help
