### ISSUE TITLE
[0.32.1] Commits to cherry pick into stable release

### ISSUE THREAD

**Issue by grabbou** [facebook/react-native#9431]

**Comment by satya164** [comment]
FYI we've bunch of regressions in latest release - https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+label%3ARegression

**Comment by sjmueller** [comment]
I haven't seen it mentioned yet, but I'm noticing big problems with image loading and caching in 0.32. In fact it seems like images are not cached at all, resulting in super slow image load times (especially for repeated images like avatars). It prompted me to look through the commit history, and the large image cache refactor could be the culprit: ddc70ff

Should I create a separate issue or is there already something out there covering it?

**Comment by bestander** [comment]
@sjmueller, please raise a separate issue with a video example if you can and cc people related to the change.
Also cc me, I'll link it internally.

**Comment by grabbou** [comment]
Nothing explicitly listed so will release w/o cherry-picks.

**Comment by bestander** [comment]
@grabbou, we want to investigate the image caching issue internally a bit.
Can we delay stable forma day or two?

**Comment by grabbou** [comment]
It's not yet deployed so it's up to you. Just let me know so I'll update interested ppl via twitter :)

**Comment by sjmueller** [comment]
Hey all, apologies for the delay regarding image cache / decoding issues. Would you still like me to submit an issue, or did your internal investigation yield the same findings?

**Comment by bestander** [comment]
Yes Sam, please submit one.
Also if you could help investigating it would be much appreciated

**Comment by nihgwu** [comment]
@sjmueller I've noticed that issue too, when i preview the loaded image, the image is loaded again, seems the cache doesn't work, I'm using RN0.32RC0

**Comment by satya164** [comment]
Let's cherry-pick b4999fca0d783bfaeb47200e434760aae8badb14

**Comment by mkonicek** [comment]
> Let's cherry-pick b4999fca0d783bfaeb47200e434760aae8badb14

Yes please. This is the fix for Chrome debugger by @lexs, awesome!

**Comment by javache** [comment]
Could someone provide some repro instructions for the caching issue? Does this happen on iOS or Android? What are example image URLs that are not cached?

**Comment by grabbou** [comment]
Also bring back android command from `rnpm` - in the morning.

@javache @bestander @sjmueller shall we move to a separate issue so the cherry-pick thread is not polluted with unrelated comments?

**Comment by mkonicek** [comment]
> shall we move to a separate issue  

Yes, is there an issue for the image caching? If not just create one :)

**Comment by bestander** [comment]
Yes, we should definitely

**Comment by rclai** [comment]
Question: is [this](https://github.com/react-native-community/react-native-video#load-files-with-the-rn-asset-system) little note still in effect?

**Comment by alloy** [comment]
If [this](https://github.com/facebook/react-native/pull/9544) fix for building a framework version of React (with e.g. CocoaPods) gets merged before the release, I’d love to see that go in.

**Comment by bestander** [comment]
To pick into 0.32.1
- [ ] https://github.com/facebook/react-native/pull/9544 CocoaPods + css-layout
- [ ] https://github.com/facebook/react-native/issues/9581 - image caching bug

**Comment by grabbou** [comment]
@alloy looks like it's not yet merged, but I'll do as a 0.32.1 as @bestander suggested.

**Comment by MajeedThaikas** [comment]
I concor

**Comment by alloy** [comment]
@grabbou This can be closed.
