### ISSUE TITLE
Auto-correct balloon text upside down

### ISSUE THREAD

**Issue by freakinruben** [facebook/react-native#9435]
Whenever I use a keyboard for a language that doesn't have built-in auto-correct support, react-native seems to use it's own implementation using a little balloon above the `TextInput`. On both iOS and Android the text in this balloon is upside down.

I've tried to remove all styling and properties of my `TextInput` but nothing seems to affect this behaviour. Is this a bug of react-native?

Screencap:
![autocorrect upside down](https://cloud.githubusercontent.com/assets/326344/17706525/b0619d32-63dc-11e6-9901-2118d96ef684.gif)

**RN Version**: 0.31.0 (but have seen it since 0.19, the first RN version I've usd)
**Platform**: iOS and Android (Simulator, iPhone 6s, Samsung Galaxy S4)
I'm using a Mac.

I can't reproduce the problem on a Nexus 4 though but it has auto-correct support for all keyboards I've tried.

Code snippet:
```js
import React, { Component } from 'react';
import { StyleSheet, TextInput, View } from 'react-native';


export default class Inputfield extends Component {
  render () {
    return (
      <View style={style.container}>
        <TextInput
            autoCorrect={true}
            editable={true}
            style={style.field}
            underlineColorAndroid="transparent"
        />
      </View>
    );
  }
}


const style = StyleSheet.create({
  container: {
    backgroundColor:  '#f7f7f7',
    marginBottom:     10,
    marginRight:      70,
    marginLeft:       2,
    height:           40,
    alignSelf:        'stretch',
    borderColor:      '#9edbee',
    borderWidth:      2,
    borderRadius:     4,
  },

  field: {
    color:            '#6BCCEB',
    fontSize:         16,
    fontFamily:       'montserrat',
    textAlign:        'left',

    paddingTop:       10,
    paddingBottom:    5,
    flex:             1,
    alignSelf:        'stretch',
    height:           30,
    textAlignVertical: 'top',
  },
});
```

**Comment by VishalRocks** [comment]
I tried returning the same component and received it correctly with no upside down. Can you push your repo here so that we can regenerate your issue?

**Comment by freakinruben** [comment]
@VishalRocks Thanks for the quick reply. After I saw your message I double checked if it might be something else in my app and I found out that [react-native-invertible-scroll-view](https://github.com/exponentjs/react-native-invertible-scroll-view/) seems to be the cause here.. 
When I don't invert the scroll, the auto-correct works fine. If I change it to a horizontal scroll-view the auto-correct gets flipped horizontally..

![screen shot 2016-08-16 at 23 26 09](https://cloud.githubusercontent.com/assets/326344/17716517/455ba938-6409-11e6-8eae-26a093cb393d.png)

The library sets the `scaleY` of the ScrollView to `-1` and then adds another `scaleY` of `-1` to each child in the scroll-view.. So it seems the auto-correct tooltip is not a (sub)-child of the scroll-view, am I correct? 
Is there any way I can control the styling of the tooltip (besides turning auto-complete off)?

**Comment by VishalRocks** [comment]
they had a similar issue:https://github.com/exponentjs/react-native-invertible-scroll-view/issues/8
and looking at how invertible-scroll-view is implemented..it is not for text input.

**Comment by freakinruben** [comment]
Ok, will try to find another solution.. Thanks

**Comment by ide** [comment]
Closing this since it's not related to RN core. The tooltip style is controlled entirely via iOS. If you can figure out its parent view in the native UIView hierarchy, we might be able to unflip the parent and therefore the tooltip as well.
