### ISSUE TITLE
PanResponder onPanResponderRelease doesn't calls on Android

### ISSUE THREAD

**Issue by shahen94** [facebook/react-native#9447]
I have this code in my render function.

``` js
<Animated.View
        style={[styles.wrap, { left }]}
        {...this.scrollResponder.panHandlers}
      >
        {initialRender &&
          <View style={styles.wrap} {...this.listViewResponder.panHandlers}>
            <ListView
              ref={ref => this.listView = ref}
              onScroll={this.handleScroll}
              dataSource={posts}
              renderRow={this.renderRow}
              renderSectionHeader={this.renderHeader}
              onEndReachedThreshold={300}
              onEndReached={this.getPosts}
              enableEmptySections={true}
              refreshControl={
                <RefreshControl
                  refreshing={refreshing}
                  onRefresh={this.onRefresh}
                />
              }
            />
            {!onProfile && this.renderSettings()}
          </View>
        }
        {this.renderComments()}
        {loading && !refreshing && <Loading />}
      </Animated.View>
```

``` js
componentWillMount() {
    this.listViewResponder = PanResponder.create({
      onMoveShouldSetPanResponderCapture: this.setMove,
      onPanResponderMove: this.handleMove,
      onPanResponderRelease: this.handleMoveEnd,
      onPanResponderTerminationRequest: () => false
    });
    this.scrollResponder = PanResponder.create({
      onStartShouldSetPanResponderCapture: (e) => e.nativeEvent.pageY < THUMB_SIZE,
      onPanResponderRelease: this.handlePress,
    });
  }
```

It's works fine on **iOS**,
But on **Android** onPanResponderRelease doesn't calls every time.

**Comment by Smallpath** [comment]
Hello,  on **Android**, `onPanResponderTerminate` will be called rather than `onPanResponderRelease`, you can add following statement to make it work

```
onPanResponderTerminate: this.handleMoveEnd
```

**Comment by mikeygee** [comment]
I am also having an issue with Android only. In my case, I am putting pan responder handlers on a `ListView`. It detects my gesture starting, but if the gesture also scrolls the list view, it seems to stop responding (stops calling `onPanResponderMove` and also never calls `onPanResponderTerminate` or `onPanResponderRelease`). It works fine on iOS. For Android, it seems to only work on non-scrolling views.

**Comment by viix** [comment]
+1

**Comment by AlbertBrand** [comment]
As a workaround, I found out that you should add the panResponders to an inner view of the ListView. So, don't do:
`<ListView {...panResponder.panHandlers}>[children]</ListView>`
but do
`<ListView><View {...panResponder.panHandlers}>[children]</View></ListView>`
An Android listview natively intercepts touches which kills JS touch events on the listview and its parents but not on any children.

**Comment by shahen94** [comment]
@AlbertBrand Thank you for your feedback.
But in that case how we can render row , header, separator etc. ?

**Comment by AlbertBrand** [comment]
Sorry, my bad, my proposed solution only works for ScrollViews, not ListViews.
`<ScrollView {...panResponder.panHandlers}>[children]</ScrollView>`
but do
`<ScrollView><View {...panResponder.panHandlers}>[children]</View></ScrollView>`.

But I suspect that the following will work: add the panHandlers on all the inner views rendered in `renderRow` and `renderSectionHeader`. Also you should add `onPanResponderTerminationRequest() => false` to the panresponder to make sure you're taking over touch events. That's what you're trying to do, right?

**Comment by shahen94** [comment]
@AlbertBrand Yes, That's it.
But it didn't  help me.

**Comment by Mohamed-Abo-El-Soud** [comment]
I'm having a similar issue here. Testing on an iPhone simulator the onPanResponderRelease calls but doesn't on my android phone. Is this not implemented on the native side?

**Comment by shahen94** [comment]
@Mohamed-Abo-El-Soud It's implemented, Looks like it's fixed in this version.

**Comment by reinisseredzins** [comment]
+1

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while. Maybe the issue has been fixed in a recent release, or perhaps it is not affecting a lot of people. Either way, it does not seem like there has been any traction on this issue for some time.

The issue is being copied over to our feature request tracker at Canny: https://react-native.canny.io/admin/board/feature-requests/p/panresponder-onpanresponderrelease-doesnt-calls-on-android

There you can upvote issues that are important to you. This will help contributors identify the issues that the community cares about.

If you think this issue should definitely remain open here in the issue tracker and not on Canny, let us know.
