### ISSUE TITLE
animate gif not working in ios and android

### ISSUE THREAD

**Issue by roysG** [facebook/react-native#9450]
os: mac
version react native:
react-native-cli: 1.0.0
react-native: 0.31.0

Run the simple code on device or emulator:

'use strict';

import React, {PropTypes,} from 'react';
import {View, Text, StyleSheet,TouchableHighlight,ScrollView,Image, Component,TextInput, AppRegistry} from "react-native";

var AwesomeProject = React.createClass({
    render: function() {
        return (
            <View style={styles.container}>
                <Image style={{width: 100, height: 100}} source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} />
            </View>
        );
    }
});

var styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1
    }
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);

**Comment by ryankask** [comment]
Can you provide a working example?

render() isn't returning anything.

**Comment by ryankask** [comment]
@facebook-github-bot label Needs more information

**Comment by waleedarshad-vf** [comment]
I am facing this same issue. i have gif url when i put this into image tag it don't get load. screen is just blank but image is working fine.

**Comment by roysG** [comment]
Sorry,
Run the code:


'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Image,
  Text,
  View,
} = React;

var AwesomeProject = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
<Text>Some text.. </Text>
        <Image style={{width: 100, height: 100}} source={{uri: 'http://www.clicktorelease.com/code/gif/1.gif'}} />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1
  }
});

AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);


The result: Gif image is not show.

**Comment by charpeni** [comment]
Hmm, that's weird because Android handle images with Fresco and iOS has it's own librarie to handle that.

I think it's probably an integration issue on your side.

Can you test that a PNG or jpg can be displayed in the same code ? If yes, can you test with an another gif URL? And a local one.

**Comment by haibinyu** [comment]
maybe you should use https instead of http.

**Comment by roysG** [comment]
Thanks, the fix for the problem was to replace the url to https on ios, and for android is to add the the presco library to build.gradle.

But i put notice that if i put few gifs the render time is very slow, there is any solve for that issue?

Maybe do some cache? or option to stat gif only when scrolling to the specific gif

**Comment by ryankask** [comment]
You can implement lazy loading or perhaps there is a library that already does that. You can use JS Coach to discover React Native libraries: https://js.coach. I came across https://github.com/IskenHuang/react-native-scrollview-lazyload which may help or provide some direction.

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-9** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.
