### ISSUE TITLE
Custom fonts not linking in Android (rnpm)

### ISSUE THREAD

**Issue by magicspon** [facebook/react-native#9453]
Hello,

Having issues linking fonts with react-native-android.  Based on this post:
https://medium.com/@gattermeier/custom-fonts-in-react-native-for-android-b8a331a7d2a7#.hwnpill6f

The two fonts are in
/android/app/src/main/assets/fonts/

GT-Walsheim-Bold.tff
GT-Walsheim-Regular.tff 

(i've tried all lowercase, no dashes, etc etc, makes no difference)

package.json 
```
"rnpm": {
    "assets": ["android/app/src/main/assets/fonts"]
  }
```

when i run `rnpm link assets` I get the foillowing error:

```
It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/stockley/websites/straightline/mobile/Straightline/android/app/src/main/assets/fonts/GT-Walsheim-Bold.ttf'
Please file an issue here: https://github.com/rnpm/rnpm/issues
```

Any ideas what's going on here.  Is there another way to use custom webfonts with react native android.

Thanks

**Comment by magicspon** [comment]
Moved to the root of my project.  Now works... 

Sorry... closing issue

**Comment by kamalk333** [comment]
what you did can you please mention? I had the same error.
@magicspon

**Comment by magicspon** [comment]
![image](https://cloud.githubusercontent.com/assets/3268717/24199108/586e1b76-0f00-11e7-960a-c924c7b09c74.png)

eee... I can't remember... was some time ago...

package.json
```
   ...., 
  "rnpm": {
    "assets": [
      "fonts"
    ]
  }
```
