### ISSUE TITLE
npm server crashes on each js error

### ISSUE THREAD

**Issue by subpublicanders** [facebook/react-native#946]
Running v0.4.0 my mpn server crashes on every js error.
I need to re-run the xcode project each time.

Crashing gives
```
Opening /Users/subpublic/Documents/jobb/rnd/rnd_node/react-native/Tryout/node_modules/react-native/node_modules/react-tools/src/classic/element/ReactElementValidator.js with subl
execvp(): No such file or directory
 ERROR  spawn ENOENT
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn"}
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
Process terminated. Press <enter> to close the window
```

**Comment by mjw56** [comment]
Try upgrading flow and watchman to latest.

**Comment by coderdave** [comment]
This happened to me quite a bit also on versions less than v0.4.0.

I noticed that if I click the "Reload JS" link on the bottom right of the red screen instead, it works fine.

**Comment by aroth** [comment]
+1

**Comment by frantic** [comment]
Good catch, sent a fix internally.

Btw, did you guys know that you can configure editor for React, and packager will open it when you click on stack trace?

![](http://g.recordit.co/z2lLoh8WVF.gif)

**Comment by coderdave** [comment]
I've tried both `export EDITOR=atom` and `export REACT_EDITOR=atom` in my `.bashrc` file but I still get the following error in the node terminal window when I click on one of the stack trace.
Opening /Users/coderdave/Documents/apps/MyApp/index.ios.js with subl
execvp(): No such file or directory
 ERROR  spawn ENOENT
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn"}
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

This then crashes the server and I have to restart.

It's still trying to open Sublime for some reason?

**Comment by frantic** [comment]
@coderdave - weird, do you use bash as your login shell? Try restarting your terminal, then open a new tab and run `env | grep REACT_EDITOR`.

**Comment by coderdave** [comment]
It's working now. I had to add it to my `.bash_profile` file instead. Both `export EDITOR=atom` and `export REACT_EDITOR=atom` works.

Maybe the instructions need to be updated?

**Comment by frantic** [comment]
@coderdave please send a PR :)
