### ISSUE TITLE
Plans on supporting native animations for transform? (translate, scale)

### ISSUE THREAD

**Issue by nschurmann** [facebook/react-native#9467]
Hello there!, are there plans for supporting native animations for transformations?, the issue is that low end phones get huge impact when doing lot's of animations in the JS thread. So taking those animations to the UI thread should be best i think.

**Comment by nihgwu** [comment]
https://github.com/facebook/react-native/pull/8839
give it a search before asking 😄 https://github.com/facebook/react-native/pulls?utf8=%E2%9C%93&q=NativeAnimated

**Comment by nschurmann** [comment]
thanks @nihgwu , thought it's not very clear how i can use this on my projects. Just by adding it?, or i need to add a prop?

**Comment by nihgwu** [comment]
read the changes especially the examples and you will find the answer, (simply add a `useNativeDriver: true`)

actually I won't recommend you to use native animations in production right now as there are still some bugs with it but you can give it a try

Try to use `LayoutAnimation` if you can, and it works with transform as well, I've created a simple game in React Native and use a lot of animation effects, 

https://github.com/nihgwu/react-native-sudoku

Hope it would help you, and you will notice that I disabled `useNativeDriver` as the reason I've mentioned, but I used it in another app as it just uses very simple animations and the native animations perform as espected

**Comment by janicduplessis** [comment]
@nschurmann You can check https://productpains.com/post/react-native/offload-some-animations-from-js-thread-for-better-perf for progress, I'll try to keep it updated. As @nihgwu mentioned it is still a work in progress and not documented. The NativeAnimated UIExplorer example can be a good place to get started (https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NativeAnimationsExample.js).
