### ISSUE TITLE
Picker - undefined is not an object (evaluating 'this.props.children[position].props)

### ISSUE THREAD

**Issue by vhoen** [facebook/react-native#9468]
I am encountering a weird behaviour when using Picker. 

I use a Picker as follows : 

```
<Picker
  mode="dropdown"
  style={styles.pickerField}
  selectedValue={this.state.dayAndTime}
  onValueChange={(text) => this.setState({ dayAndTime: text })}
>
  <Picker.Item label="Le 5/07 à 15H" value="0" key="0" />
</Picker>
```

When the screen displaying this picker is loaded, I got an error screen saying (cf. screenshot below) : undefined is not an object (evaluating 'this.props.children[position].props)

From what I gathered, my problem come from line 106 of Libraries/Components/Picker/PickerAndroid.android.js, it seems that onValueChange creates it, so I removed it, and I don't have the error anymore.

I use react-native 0.31.0, I use an android api 23 virtual device with genymotion.

Is there something I am missing ?

![pickererror](https://cloud.githubusercontent.com/assets/5245902/17780109/1bbff85e-6562-11e6-8699-2e7d3a3bca66.png)

**Comment by vhoen** [comment]
Error was triggered because there was only one Picker.Item, after I added one, everything went smoothly.

**Comment by alexsotocx** [comment]
@vhoen I get the same issue and I have several items and it's triggered when the value changed.
I'm using react 0.33
```javascript
renderEventPicker() {
    let { project } = this.props;
    let { report } = this.state;
    if(project.eventTypes.length > 0) {
      return (
        <Picker
          selectedValue={this.state.eventTypeId}
          onValueChange={(data) => {
            report.eventTypeId = data;
            report.eventCategoryId = null;
            this.setState({report});
          }}
        >
          <Picker.Item key={0} label={'Tipo de evento'} value={''} />
          {project.eventTypes.map((eventType) => <Picker.Item key={eventType.id} label={eventType.name} value={eventType.id} />)}
        </Picker>
      );
    }
    return null;
  }
```

Is there something I'm missing?

**Comment by alexsotocx** [comment]
I found it... The error was that ```selectedValue={this.state.eventTypeId}``` was null for ever...

**Comment by willoughby** [comment]
Having the same issue as @alexsotocx, However if you add to static items, you can select them with no error, but any items dynamically added in a map throw the error reported

**Comment by alexsotocx** [comment]
@willoughby please refers to #9927

**Comment by dkaushik94** [comment]
@willoughby Same. Got a response and rendering it after setState.  When value is changes i am thrown this error.

**Comment by luoyjx** [comment]
so, i found a resolution that we can create an array contains blank Item before use it.

```
render() {
    const pickerItems = this.props.depts.map(dept => {
      return (
        <Picker.Item key={'d' + dept.id} label={dept.name} value={dept.id} />
      )
    })

    pickerItems.unshift(<Picker.Item key="d0" label="选择部门" value="" />)

    return (
        <Picker
             selectedValue={this.state.deptId}
             onValueChange={value => this.setState({ deptId: value })}>
             {pickerItems}                  
        </Picker>
    )
}
```

**Comment by luoyjx** [comment]
```
render() {
    const pickerItems = this.props.depts.map(dept => {
      return (
        <Picker.Item key={'d' + dept.id} label={dept.name} value={dept.id} />
      )
    })

    pickerItems.unshift(<Picker.Item key="d0" label="选择部门" value="" />)

    return (
        <Picker
             selectedValue={this.state.deptId}
             onValueChange={value => this.setState({ deptId: value })}>
             {pickerItems}                  
        </Picker>
    )
}
```

**Comment by rafaelgrilli92** [comment]
I had the same issue and I fixed setting an empty array as the default value of my dataSource prop:

```
const defaultProps = {
	label: '',
	dataSource: []
};

const PickerWithLabel = (props) => {
	return (
		<View style={styles.container}>
			<Label style={styles.label}>{props.label}</Label>
			<Picker style={styles.picker} mode="dropdown" { ...props }>
				<Picker.Item label="--- Select ---" value="" />
				{
					props.dataSource.map(({ label, value }) => (
						<Picker.Item key={value} label={label} value={value} />
					))
				}
			</Picker>
		</View>
	)
}

PickerWithLabel.defaultProps = defaultProps;
```

**Comment by misheki** [comment]
I resolved my issue using the suggested workaround by @luoyjx!

`_renderModalStatePicker = () => {

        const pickerItems = Object.keys(this.state.statelist).map((key) => {
            return (<Item label={this.state.statelist[key]} value={key} key={key}/>) //if you have a bunch of keys value pair
        })     
        pickerItems.unshift(<Item key="as" label="All States" value="as" />)

        return(
            <View>
                <ListItem>
                    <Text>States</Text>
                </ListItem>
                
                <Picker
                    mode="dropdown"
                    placeholder="Choose a state"
                    selectedValue={this.state.selectedState}
                    onValueChange={this.handleSelectState.bind(this)}>  
                    {pickerItems}
                </Picker>
            </View>
        );
    }`
