### ISSUE TITLE
[Text] SampleApp's Text tag display error on device!

### ISSUE THREAD

**Issue by yueliangwen** [facebook/react-native#947]
SampleApp display`<Text style={styles.welcome}>Welcome to React Native!</Text>` error on device(iphone6 plus)!Show `Welcome to React` only, `Native` is gone!

**Comment by brentvatne** [comment]
@yueliangwen - this is on the base project, with nothing changed? And it does not happen in the simulator?

Can anyone else with an iPhone 6 plus confirm?

**Comment by yueliangwen** [comment]
@brentvatne - Change `localhost` to the ip address of my computer only. It's all right in the simulator!
 `Welcome to Reactive Native!` is right! `Welcome to ReacT Native!` is right! Keep `Welcome to React Native!`, and change `fontSize` of `styles.welcome` to 24 is right! Very strange!

**Comment by cgarvis** [comment]
We've experienced something similar with text on iPhone 6s and the iPhone 6 simulator.  No issues on iPhone4s and iPhone 5s.  I'll see if I can start a new project and replicate.

**Comment by cgarvis** [comment]
Screenshots:

iPhone 5s
![iphone5s](https://cloud.githubusercontent.com/assets/213125/7658431/3d1fd99e-fb08-11e4-8a50-3f399faf14fe.png)

iPhone 6 Plus
![iphone6plus](https://cloud.githubusercontent.com/assets/213125/7658443/4e8214a4-fb08-11e4-8a78-151580008e92.png)

Seems that iPhone 6 is fine.

**Comment by esauter5** [comment]
![screen shot 2015-05-26 at 3 23 13 pm](https://cloud.githubusercontent.com/assets/1442232/7821214/3e90c174-03bb-11e5-89b1-36fd536a47f6.png)

When adding some height to the text element, you can see that the last word wraps to a new line. If I don't set an explicit height, the wrapped text is not visible. It would appear that the whatever size React Native is setting the text element to is a pixel or two short causing it to wrap.

**Comment by esauter5** [comment]
A temporary hack I've found to work is adding an extra space of text to the end of `Text` components. The seems to add the extra few pixels necessary so that nothing gets cut off. I have a wrapper around the React `Text` component so I've added this extra space there so that I don't have to manually fix each individual problematic component. I also added an extra space at the beginning to try to balance things out.

**Comment by brentvatne** [comment]
@esauter5 - is this still happening for you on master? Not much activity on here and haven't run into it myself, so closing for now

**Comment by esauter5** [comment]
@brentvatne Not sure. The hack I used fixed the issue so I haven't run into it. When I get some time I'll take some time to figure out if I still see it without the hack and if so I'll let you know.

**Comment by brentvatne** [comment]
Thanks for the quick response @esauter5 - nobody has reported on this in a while so it is probably fixed but it would be amazing if you were able to verify that when you get the chance! :heart:
