### ISSUE TITLE
Clicking on scheduled notification restart the app on Android

### ISSUE THREAD

**Issue by oziks** [facebook/react-native#9470]
I wonder if this is a known problem?

My problem is related to this issue https://github.com/Neson/react-native-system-notification/issues/63 

> Whenever I click on a scheduled notification, my app completely restarts instead of waking up from the background, even though it's still running in the background.

I'm testing with:
 - `react-native` : `0.31.0`
 - `Android` : `5.1.0`

Thanks.

**Comment by charpeni** [comment]
Did you configure your intent as described in the [Linking documentation](https://facebook.github.io/react-native/docs/linking.html)

**Comment by oziks** [comment]
Oh no! Thanks, its works fine now :)
