### ISSUE TITLE
fetch() doing GET instead of POST (iOS)

### ISSUE THREAD

**Issue by m-vdb** [facebook/react-native#9471]
Hi there,

I'm using `react-native` 0.28 version for iOS and every time I use `fetch()` to perform a `POST` with JSON content (I'm using a JSON RESTful API), the requests is done as a `GET`. Here is a sample code:
```javascript
fetch('https://domain.com/api', {
  method: 'POST',
  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},
  body: JSON.stringify({
    key: 'value'
  })
}).
  then((response) => {
    console.log('Done', response);
  });
```
I know that the requests switches to a `GET` because I double-checked the logs on the API side. I thought it was something to do with `CORS` (but apparently no such thing in `react-native`) and `ATS` (but already turned off by default, plus my domain is HTTPS). I've tried from a browser and from a `curl` and it worked perfectly, so a priori no issue on server configuration. Any idea what's going on here?

NB: I already opened a question on [stackoverflow](http://stackoverflow.com/questions/38901149/fetch-doing-get-instead-of-post-on-react-native-ios) but no luck yet.

**Comment by m-vdb** [comment]
Also I mention that I tried to debug the code until the bridge to native code and I noticed nothing wrong. I tried to debug the native code but couldn't find any clue. I double-checked that `ATS` is disabled just to be sure.

**Comment by Sean-Snow** [comment]
react-native api fetch work。  check  your  restful api

**Comment by m-vdb** [comment]
After further digging, it was definitely an issue with the API + fetch. I was missing a slash at the end of the URL and the API issued a 301, that `fetch` didn't handle correctly. So I don't know if there is something to fix in the `fetch` function (and underlying mechanisms) but I'm closing this since this is no longer a blocker for me.
