### ISSUE TITLE
Android Scrollview does not clear when using RefreshControl

### ISSUE THREAD

**Issue by kirandwarkan** [facebook/react-native#9472]
I have encountered an issue with a ScrollView (on Android only) still being rendered on screen after a RefreshControl is used to toggle the state of my main view. This results in the ScrollView being overlayed on top of the newly rendered view. Subviews of the scrollview itself don't seem to be rendered, but its background is. I have created a quick sample project to reproduce the issue using React Native 0.31 (also had the issue using RN 0.26.3).
[Sample project](https://github.com/kirandwarkan/RN31Scrollview)

Desired Result:
Change the view rendered based on a state change after pulling down to refresh. From the iOS example screenshot, the red view is cleared and only the blue view is visible.
[Initial View](https://github.com/kirandwarkan/RN31Scrollview/blob/master/screenshots/2016-08-18-android-initial-view.png)
[Desired Result](https://github.com/kirandwarkan/RN31Scrollview/blob/master/screenshots/2016-08-18-ios-correct-view.png)

Actual Result (AndroId):
The red view is overlayed on top of the blue view. 
[Android with uncleared scrollview](https://github.com/kirandwarkan/RN31Scrollview/blob/master/screenshots/2016-08-18-android-incorrect-view.png)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-scrollview-does-not-clear-when-using-refreshcontrol

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:34180)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6700-000j2t-C6
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 02:27:58 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c66zz-0007ll-2O
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 19:27:56 -0700
Date: Sun, 13 Nov 2016 18:27:54 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479090474;
	bh=EERXMF+UACeajIwDj9h9zu6yq/B4comrzbfVYJgYO/o=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Qtp6Jq9Z44/HFWjnoGK2yFjIuiREZq1r8uDF5QAqSwfwKAzAHmO/sLu1kWSksHTf3
	 CWgDrpK2BCsjs2WgnRv0bsLmkQoRZjlInbEqLm/HwhVV8as7gZTKzwbsyCe/H4TuAi
	 uJN/7ChQQO+nV2kZIzVdqMLZf20O3QsWmZiFnAlg=
