### ISSUE TITLE
Android: Crash on app launch (react-native 0.31) 

### ISSUE THREAD

**Issue by silverspace** [facebook/react-native#9477]
Do the checklist before filing an issue:
- [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

Based on the stack trace, it looks like the issue could be related to JSCExecutor::callFunction() attempting to dereference a null pointer:
https://github.com/facebook/react-native/blob/master/ReactCommon/cxxreact/JSCExecutor.cpp L.365
## None of the above, create a bug report

08-18 20:47:58.042 13586-14316/com.samsara.driver A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14316 (mqt_js)
08-18 20:47:58.152 288-288/? A/DEBUG: **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
08-18 20:47:58.152 288-288/? A/DEBUG: Build fingerprint: 'samsung/gt58wifixx/gt58wifi:6.0.1/MMB29M/T350XXU1BPE3:user/release-keys'
08-18 20:47:58.152 288-288/? A/DEBUG: Revision: '4'
08-18 20:47:58.152 288-288/? A/DEBUG: ABI: 'arm'
08-18 20:47:58.152 288-288/? A/DEBUG: pid: 13586, tid: 14316, name: mqt_js  >>> com.samsara.driver <<<
08-18 20:47:58.152 288-288/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-18 20:47:58.202 288-288/? A/DEBUG:     r0 00000000  r1 000037ec  r2 00000006  r3 9d2eb978
08-18 20:47:58.202 288-288/? A/DEBUG:     r4 9d2eb980  r5 9d2eb930  r6 00000000  r7 0000010c
08-18 20:47:58.202 288-288/? A/DEBUG:     r8 00000004  r9 b8aca670  sl 71c26558  fp 00000000
08-18 20:47:58.202 288-288/? A/DEBUG:     ip 00000006  sp 9d2eb340  lr b6d02efd  pc b6d052f8  cpsr 400e0010
08-18 20:47:58.222 288-288/? A/DEBUG: backtrace:
08-18 20:47:58.222 288-288/? A/DEBUG:     #00 pc 000442f8  /system/lib/libc.so (tgkill+12)
08-18 20:47:58.222 288-288/? A/DEBUG:     #01 pc 00041ef9  /system/lib/libc.so (pthread_kill+32)
08-18 20:47:58.222 288-288/? A/DEBUG:     #02 pc 0001ba13  /system/lib/libc.so (raise+10)
08-18 20:47:58.222 288-288/? A/DEBUG:     #03 pc 00018c81  /system/lib/libc.so (__libc_android_abort+34)
08-18 20:47:58.222 288-288/? A/DEBUG:     #04 pc 00016840  /system/lib/libc.so (abort+4)
08-18 20:47:58.222 288-288/? A/DEBUG:     #05 pc 0004ee41  /data/app/com.samsara.driver-1/lib/arm/libgnustl_shared.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+220)
08-18 20:47:58.222 288-288/? A/DEBUG:     #06 pc 0004d93b  /data/app/com.samsara.driver-1/lib/arm/libgnustl_shared.so (_ZN10__cxxabiv111__terminateEPFvvE+2)
08-18 20:47:58.222 288-288/? A/DEBUG:     #07 pc 0004d96b  /data/app/com.samsara.driver-1/lib/arm/libgnustl_shared.so (_ZSt9terminatev+10)
08-18 20:47:58.222 288-288/? A/DEBUG:     #08 pc 0004d977  /data/app/com.samsara.driver-1/lib/arm/libgnustl_shared.so (_ZN10__cxxabiv112__unexpectedEPFvvE+2)
08-18 20:47:58.222 288-288/? A/DEBUG:     #09 pc 0004cd7d  /data/app/com.samsara.driver-1/lib/arm/libgnustl_shared.so (__cxa_call_unexpected+96)
08-18 20:47:58.222 288-288/? A/DEBUG:     #10 pc 0002a40d  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so (_ZN8facebook5react11JSCExecutor12callFunctionERKSsS3_RKN5folly7dynamicE+252)
08-18 20:47:58.222 288-288/? A/DEBUG:     #11 pc 0002e1b7  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so
08-18 20:47:58.222 288-288/? A/DEBUG:     #12 pc 0002fdfd  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so
08-18 20:47:58.222 288-288/? A/DEBUG:     #13 pc 00018fb9  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so (_ZNKSt8functionIFvvEEclEv+12)
08-18 20:47:58.222 288-288/? A/DEBUG:     #14 pc 00019b15  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so
08-18 20:47:58.222 288-288/? A/DEBUG:     #15 pc 000142ed  /data/app/com.samsara.driver-1/lib/arm/libreactnativejnifb.so
08-18 20:47:58.222 288-288/? A/DEBUG:     #16 pc 0015f61f  /data/data/com.samsara.driver/cache/slice-com.facebook.react-react-native-0.31.0_79dae5f40368700e06771efc0710b48a928a4c08-classes.dex (offset 0x10f000) (void com.facebook.react.bridge.queue.NativeRunnable.run()+74)
08-18 20:47:58.222 288-288/? A/DEBUG:     #17 pc 037a11df  /system/framework/arm/boot.oat (offset 0x2f81000)
- [x] What's the **version** of React Native you're using?
  react-native 0.31
- [x] Does this occur on iOS, Android or both?
  Crash only occurs on Android. This is not 100% reproducible either, seems to intermittently crash in development on app launch. 
- [x] Are you using Mac, Linux or Windows?
  Mac

**Comment by Caijiacheng** [comment]
we can produce frequently . sounds it raised more at samsung phone?

## The Stack

09-09 18:05:00.851: A/libc(479): Fatal signal 6 (SIGABRT), code -6 in tid 532 (mqt_js)
09-09 18:05:00.971: I/DEBUG(21958): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-09 18:05:00.971: I/DEBUG(21958): Build fingerprint: '**`samsung`**/trlteduoszc/trltechn:5.0.1/LRX22C/N9100ZCU1BOE2:user/release-keys'
09-09 18:05:00.981: I/DEBUG(21958): Revision: '12'
09-09 18:05:00.981: I/DEBUG(21958): ABI: 'arm'
09-09 18:05:00.981: I/DEBUG(21958): pid: 479, tid: 532, name: mqt_js  >>> com.creative.bubble <<<
09-09 18:05:00.981: I/DEBUG(21958): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-09 18:05:01.031: I/DEBUG(21958):     r0 00000000  r1 00000214  r2 00000006  r3 00000000
09-09 18:05:01.031: I/DEBUG(21958):     r4 9f7ffdb8  r5 00000006  r6 0000000b  r7 0000010c
09-09 18:05:01.031: I/DEBUG(21958):     r8 00000004  r9 9f519098  sl a21dfa70  fp 00000000
09-09 18:05:01.031: I/DEBUG(21958):     ip 00000214  sp 9f7ff860  lr b6f26fd1  pc b6f4a970  cpsr 600f0010
09-09 18:05:01.031: I/DEBUG(21958): backtrace:
09-09 18:05:01.031: I/DEBUG(21958):     #00 pc 00037970  /system/lib/libc.so (tgkill+12)
09-09 18:05:01.031: I/DEBUG(21958):     #01 pc 00013fcd  /system/lib/libc.so (pthread_kill+52)
09-09 18:05:01.031: I/DEBUG(21958):     #02 pc 00014beb  /system/lib/libc.so (raise+10)
09-09 18:05:01.031: I/DEBUG(21958):     #03 pc 00011531  /system/lib/libc.so (__libc_android_abort+36)
09-09 18:05:01.031: I/DEBUG(21958):     #04 pc 0000fcbc  /system/lib/libc.so (abort+4)
09-09 18:05:01.031: I/DEBUG(21958):     #05 pc 0004ee41  /data/app/com.creative.bubble-1/lib/arm/libgnustl_shared.so (__gnu_cxx::__verbose_terminate_handler()+220)
09-09 18:05:01.031: I/DEBUG(21958):     #06 pc 0004d93b  /data/app/com.creative.bubble-1/lib/arm/libgnustl_shared.so (__cxxabiv1::__terminate(void (*)())+2)
09-09 18:05:01.041: I/DEBUG(21958):     #07 pc 0004d96b  /data/app/com.creative.bubble-1/lib/arm/libgnustl_shared.so (std::terminate()+10)
09-09 18:05:01.041: I/DEBUG(21958):     #08 pc 0004d977  /data/app/com.creative.bubble-1/lib/arm/libgnustl_shared.so (__cxxabiv1::__unexpected(void (*)())+2)
09-09 18:05:01.041: I/DEBUG(21958):     #09 pc 0004cd7d  /data/app/com.creative.bubble-1/lib/arm/libgnustl_shared.so (__cxa_call_unexpected+96)
09-09 18:05:01.041: I/DEBUG(21958):     #10 pc 0002a40d  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so (facebook::react::JSCExecutor::callFunction(std::string const&, std::string const&, folly::dynamic const&)+252)
09-09 18:05:01.041: I/DEBUG(21958):     #11 pc 0002e1b7  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so
09-09 18:05:01.041: I/DEBUG(21958):     #12 pc 0002fdfd  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so
09-09 18:05:01.041: I/DEBUG(21958):     #13 pc 00018fb9  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so (std::function<void ()>::operator()() const+12)
09-09 18:05:01.041: I/DEBUG(21958):     #14 pc 00019b15  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so
09-09 18:05:01.041: I/DEBUG(21958):     #15 pc 000142ed  /data/app/com.creative.bubble-1/lib/arm/libreactnativejnifb.so
09-09 18:05:01.041: I/DEBUG(21958):     #16 pc 00134fcb  /data/dalvik-cache/arm/data@app@com.creative.bubble-1@base.apk@classes.dex

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-crash-on-app-launch-react-native-031-

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by MaheshNandam** [comment]
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31476 (alhost:8097/...)


Facing the same issue


react- 16.0.0
react-native - 0.50.4
