### ISSUE TITLE
OkHttp leak

### ISSUE THREAD

**Issue by droidwolf** [facebook/react-native#9478]
OkHttp: A connection to http://localhost:8097/ was leaked. Did you forget to close a response body?

RN 0.31.0

**Comment by tioback** [comment]
This happens to me whenever I call an URL that doesn't exist, for instance `http://asdf/`.

**Comment by vsona** [comment]
I met the same mistake, will you solve it?

**Comment by christopherdro** [comment]
@droidwolf @tioback Is this still an ongoing issue?

**Comment by walkerXiong** [comment]
+1

**Comment by stoffern** [comment]
I can confirm this, RN v 0.44, Android running for a long while standby and the simulator reports that message.

**Comment by HanAsteroid** [comment]
W/OkHttp: A connection to http://localhost:8097/ was leaked. Did you forget to close a response body?
                                                         
                                                         [ 05-09 15:03:34.517  2908: 2908 E/         ]
                                                         process stopped due to unexpected signal 13
                                                         
the android app can not send any requests anymore when it happened,i need help !!!!!

**Comment by naivehhr** [comment]
![1](https://cloud.githubusercontent.com/assets/5243456/25989269/004a64d0-372e-11e7-9b8c-4368e6b21723.gif)

Always request for port 8097

react: 16.0.0-alpha.6
react: 0.44.0
platform: ios

**Comment by stoffern** [comment]
Woud this be related to this? 
https://github.com/square/okhttp/issues/2311

**Comment by hramos** [comment]
This issue has been inactive for a while. It's possible that the bug has been fixed since this issue was originally submitted, or perhaps it is not affecting a great amount of people, or a workaround has been provided. Either way, we're going to close this in order to allow the community to focus on more pressing issues.

If you strongly believe this issue should remain open, please provide a justification below.

**Comment by julien-leclercq** [comment]
I strongly believe this issue should remain open, here is a notification.

**Comment by mayeco** [comment]
![image](https://user-images.githubusercontent.com/369490/34240052-47ee8d78-e5ea-11e7-9288-09c9fec0db01.png)

**Comment by hramos** [comment]
Can you open a new issue?
