### ISSUE TITLE
rnpm link failing

### ISSUE THREAD

**Issue by Jorenm** [facebook/react-native#9489]
Version 0.30.0
Windows 10

I'm trying to link the Auth0 library, but am getting an error.

I'm running: "rnpm link react-native-lock" as per their docs, but getting the following error:

rnpm-link ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/rnpm/rnpm/issues

**Comment by damusnet** [comment]
Hi @Jorenm, may I suggest you open an issue on https://github.com/rnpm/rnpm/issues or on the Auth0 issue tracker instead of here?

**Comment by damusnet** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-0** [comment]
@damusnet tells me to close this issue. If you think it should still be opened let us know why.

**Comment by Jorenm** [comment]
The rnpm repository is closed for new issues, since it was apparently merged into this repo. If you think it's an Auth0 issue, and not an rnpm issue, then I shall post it there.

**Comment by damusnet** [comment]
Yes, I see that now, that the rnpm repo is closed for new issues. Have you tried updating your RN version to use `react-native link` instead of `rnpm`?

**Comment by Jorenm** [comment]
I made an issue over at auth0, and the problem was on their end.

**Comment by damusnet** [comment]
Thanks for reporting back :)
Glad it all worked out ok.
