### ISSUE TITLE
"Your code is broken! Do not iterate over arrays with for...in." <-- NO. your code is broken! :)

### ISSUE THREAD

**Issue by jaygarcia** [facebook/react-native#949]
FYI.  This is currently in the repo.  Having this explode like this from the Facebook team-written code is not nice :(.

I saw this in my own project yesterday, and noted that I had not used "for in" loops. 

![dafuq](https://cloud.githubusercontent.com/assets/180031/7252812/1653600c-e806-11e4-8a48-0cbc40b0ae01.gif)

**Comment by magicismight** [comment]
+1
It occurred when I updated the react native to the lastest version(0.4.0)
My code wasn't broken before I updated react native!

**Comment by chirag04** [comment]
+1 I had the exact same problem today.

**Comment by brentvatne** [comment]
This is being tracked in #868 and a fix is on the way :smile:

(See also #907 and #870 - this is a popular one!)

**Comment by xcatliu** [comment]
+1

Solved the problem by updating react-native@0.4.0 to react-native@0.4.1
