### ISSUE TITLE
fetch js bundle fail

### ISSUE THREAD

**Issue by beilunyang** [facebook/react-native#9492]
I started react packager  and installed app on my device by running 'react-native run-android'...
but when open app and start fetch js bundle, the react packager happened a error...    

[14:17:29] <START> request:/index.android.bundle?platform=android&dev=true&hot=false&minify=false
[14:17:29] <START> find dependencies

<--- Last few GCs --->

   95730 ms: Mark-sweep 1335.6 (1434.4) -> 1330.7 (1434.4) MB, 354.0 / 0 ms [allocation failure] [GC in old space requested].
   96087 ms: Mark-sweep 1330.7 (1434.4) -> 1330.7 (1434.4) MB, 356.9 / 0 ms [allocation failure] [GC in old space requested].
   96456 ms: Mark-sweep 1330.7 (1434.4) -> 1330.7 (1434.4) MB, 369.1 / 0 ms [last resort gc].
   96815 ms: Mark-sweep 1330.7 (1434.4) -> 1330.7 (1434.4) MB, 358.5 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1183fc6c9e59 <JS Object>
    1: PromiseIdResolveHandler(aka PromiseIdResolveHandler) [native promise.js:~117] [pc=0x2dab3da13c05] (this=0x1183fc604189 <undefined>,K=0x346ebd19f749 <JS Object>)
    2: PromiseHandle(aka PromiseHandle) [native promise.js:90] [pc=0x2dab3dafdb26] (this=0x1183fc604189 <undefined>,y=0x346ebd19f749 <JS Object>,D=0x1183fc6c1f49 <JS Function PromiseIdResolveHandler (SharedFunctionInfo 0x1183fc67...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
./packager.sh: line 11:  1389 Abort trap: 6           node "$THIS_DIR/../local-cli/cli.js" start "$@"
~
Process terminated. Press <enter> to close the window  

so, i can't fetch js bundle...and show the information 'could not connect to development server'. ...
i don't know how to solve the problem.....

**Comment by beilunyang** [comment]
version:

- nodejs v6.2.1
- react-native-cli v1.0.0
- react-native v0.31.0

**Comment by yulongsun007** [comment]
so ,how are you resolve it ?  i have also met this problem

**Comment by beilunyang** [comment]
这个问题是由某些版本的npm引起的，你可以切换npm的版本，然后npm install 来解决...一开始我使用的是cnpm v4.2.0,然后重新通过npm v3.9.3 安装就不会引发这个错误了。
