### ISSUE TITLE
[Android] modal cannot work if ReactRootView is created and cached in previous activity

### ISSUE THREAD

**Issue by markzhai** [facebook/react-native#9496]
When I do pre-load of ReactRootView in previous Activity (in a hybrid app):

```java
        ReactRootView rootView = new ReactRootView(activity);
        rootView.startReactApplication(
                ((ReactApplication) activity.getApplication()).getReactNativeHost().getReactInstanceManager(),
                reactInfo.getMainComponentName(),
                reactInfo.getLaunchOptions());
```

and later use the created view in ReactActivity directly

```java
setContentView(mReactRootView);
```

Modal cannot show in this case then (works fine if I do not do this pre-load), I guess this is due to Android window issue as it is using the previous native activity to add window.

Any ideas on this? TimePickerAndroid works just fine.

react-native 0.31, Mac, Android.

**Comment by jokester** [comment]
Creating ReactRootView with a [MutableContextWrapper](https://developer.android.com/reference/android/content/MutableContextWrapper.html) might be a workaround (so we can change underlying context in the 2nd Activity).

**Comment by markzhai** [comment]
@jokester it works, thanks

**Comment by AndrewCloud** [comment]
Hello，I got the same problem, but I dont know how to use  MutableContextWrapper to solve this problem, could you show me ?
