### ISSUE TITLE
importing 'requireNativeComponent' causes a crash

### ISSUE THREAD

**Issue by CoderGLM** [facebook/react-native#9499]
RCTMapView.js: 
```
import { requireNativeComponent } from 'react-native';

export default requireNativeComponent('RCTMapView', null);
```

MapView.js: 
```
import React, { Component } from 'react';
import {
  requireNativeComponent,
} from 'react-natvie';

import RCTMapView from './RCTMapView';

export default class MapView extends Component {
  render() {
    return <RCTMapView {...this.props} />;
  }
}
```

Use MapView.js: 
```
        <MapView
          style={styles.map}
          pitchEnabled={false}/>
```

Here is the crash: 
![simulator screen shot 2016 8 21 2 46 08](https://cloud.githubusercontent.com/assets/13973117/17835780/19ce5376-67ae-11e6-8ebe-6371cf4fef3f.png)

And if I remove  importing requireNativeComponent in MapView.js, it works, why?

**Comment by AgtLucas** [comment]
@CoderGLM Which React Native version are you using?

**Comment by CoderGLM** [comment]
react-native-cli: 1.0.0
react-native: 0.31.0

**Comment by Cordazar** [comment]
Because of spelling. Try the below code instead.

```
import {
  requireNativeComponent,
} from 'react-native';
````

**Comment by CoderGLM** [comment]
GOD, Actually misspelled, Thanks a lot. @Cordazar
