### ISSUE TITLE
NavigationTransitioner: refactoring between 0.28 and 0.29 makes it re-render a scene when navigating back

### ISSUE THREAD

**Issue by p16** [facebook/react-native#9502]
Hi there,
upgrading from 0.28 to 0.29 (this happens also up to 0.31) I got a problem when navigating back to a previous scene.

In 0.28 the scene would not re-render. In 0.29 the previous scene will re-render.

This behaviour seems to be related to the fact that a scene is "unmounted" as soon as the next scene is rendered. Going back will basically recreate the scene from scratch. I'm not sure this was intended and in my opinion this change defeats the purpose of having a navigator that should show you the previous scene without re-rendering, as a native navigator usually do.

I think the change happened in this commit https://github.com/facebook/react-native/commit/3a6231432a48f49d67d24fa87dac75e8fb7ac345#diff-2829ac115b33c48fbd4110134089d971L170 . It seems that a reference to the already rendered scenes is no longer kept and the scenes are considered "unmountable" by react.

Given that my assumption may be incorrect, this is the code I'm using to implement the navigation https://gist.github.com/p16/30e72f2b6e74d1bf9b35ebca78128ba7 . Maybe I'm just using a component the wrong way for 0.29 changes :) 

P.S.: I think that also https://github.com/facebook/react-native/issues/9479 may be related to this.

**Comment by satya164** [comment]
cc @hedgerwang

**Comment by ryankask** [comment]
In 0.29 `NavigationTransitioner` lost its `renderOverlay` and `renderScene` props.

Are you using `NavigationTransitioner` or `NavigationCardStack`? If you're using the former, you'll want to switch to use `NavigationCardStack` in >0.30 or update the `render()` method so it looks like: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L215

The gist you posted seems like it wouldn't work correctly you're only rendering one `NavigationCard` for the stack (see the last comment I wrote in #9479).

**Comment by p16** [comment]
Hi @ryankask ,
thanks for the info, I'm using `NavigationTransitioner` and `NavigationCard`. I'll try to switch to `NavigationCardStack` and report how that goes.

> [...] it wouldn't work correctly you're only rendering one `NavigationCard` [...]

Ok, when working with `0.28` I was relying on the [`NavigationTransitioner` to do that](https://github.com/facebook/react-native/commit/3a6231432a48f49d67d24fa87dac75e8fb7ac345#diff-2829ac115b33c48fbd4110134089d971L166) for me, and if understand that correctly that's not the case anymore. Make sense :)

I'll try `NavigationCard` and report back how it goes. Thanks!

**Comment by ryankask** [comment]
@p16 Hi there! I'm going to close this issue but if you're still having trouble, feel free to report back here or join us on Reactiflux (http://www.reactiflux.com/)

**Comment by ryankask** [comment]
@facebook-github-bot answered

**Comment by facebook-github-bot-5** [comment]
Closing this issue as @ryankask says the question asked has been answered. Please help us by asking questions on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only.

**Comment by p16** [comment]
Hi @ryankask , sorry for this late reply.

Both solution you suggested work fine, thanks!

* Using `NavigationCardStack` add a sliding transition that was not good for me and I could not find a way to remove that (I didn't dig that much on it :) )
* Using `NavigationTransitioner` with the [implementation](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L205) you linked did the trick.

Thank you very much!

P.S.: [This](https://gist.github.com/p16/30e72f2b6e74d1bf9b35ebca78128ba7#file-001-navigation-using-navigationtransitioner-rn-0-31-js) is the new navigation code I've implemented following @ryankask 's suggestion.
