### ISSUE TITLE
Network request failed on Android emulator

### ISSUE THREAD

**Issue by nodegin** [facebook/react-native#9506]
I'm using React Native v0.31.0 on OS X, when I try up upload an image to my API endpoint the error `Network request failed` occurs immediately.

![2016-08-22 00 44 25](https://cloud.githubusercontent.com/assets/8536244/17838496/974c654c-6801-11e6-8b90-e8cddb60f7a5.png)

Here's the code snippet:
```js
const body = new FormData()
body.append('snapshot', {
  uri: this.state.imageUri,
  name: 'image.jpg',
})
//try {
  let uploaded = await fetch(`${this.props.app.apiUrl}/saveImage`, {
    method: 'POST',
    headers: {
      'X-Token': this.props.app.token,
      'Accept': 'application/json',
      'Content-Type' : 'multipart/form-data',
    },
    body,
  })
  uploaded = await uploaded.json()
  if (!uploaded) {
    throw new Error
  }
  alert('uploaded')
/*} catch (error) {
  console.log(error)
  // error is "[TypeError: Network request failed]"
}*/
```

The `this.state.imageUri` variable looks like `file:///data/data/com.myapp/cache/IMG_20160822_002751969567625.jpg`

In iOS simulator, the image can be uploaded successfully, the bug only occurs in Android.

Thank you very much.

**Update**

By removing `body` from the request I can successfully post to the server

**Comment by nodegin** [comment]
Solved by adding `type` property to image field.
```js
body.append('snapshot', {
  uri: this.state.imageUri,
  type: 'image/jpeg',
  name: 'image.jpg',
})
```
Closing this issue.

**Comment by sibelius** [comment]
@nodegin how do u know the image type?

**Comment by ravirajn22** [comment]
It worked for me @nodegin , how come it works for IOS without type and android only with type
