### ISSUE TITLE
[Packager] "Requiring unknown module" error for module from package.json browser field

### ISSUE THREAD

**Issue by gitim** [facebook/react-native#9518]
Hi! After upgrading to the react-native@0.32 I am getting
<img width="321" alt="2016-08-22 10 55 59" src="https://cloud.githubusercontent.com/assets/3778452/17847517/70d9250e-685f-11e6-8526-f904d5526fef.png">

in my project I am using https://github.com/yahoo/intl-messageformat, which has browser field in its package.json https://github.com/yahoo/intl-messageformat/blob/master/package.json#L31-L34, and while trying to [require](https://github.com/yahoo/intl-messageformat/blob/master/index.js#L9) `./lib/locales` it fails. 
Seems these https://github.com/facebook/react-native/pull/2208, https://github.com/facebook/node-haste/pull/77, https://github.com/facebook/node-haste/issues/62 related to my issue.

**Comment by jgkim** [comment]
Same here. Is there any workaround?

**Comment by gitim** [comment]
> Same here. Is there any workaround?

I can see the only workaround is to fork a dependency and remove browser field from its package.json or wrap the `require` in the fork with try/catch.

**Comment by jgkim** [comment]
@gitim Thanks for the answer. However, I'm using `react-intl`, which depends on `intl-messageformat`, and `react-intl` itself has also the same issue. :(

**Comment by davidaurelio** [comment]
Fixed with #5710b230a2a0f2b29553fbf94af5147a2e030f44

**Comment by gitim** [comment]
@davidaurelio cool, thanks!

**Comment by lukescott** [comment]
@davidaurelio I see that commit is supposed to be on `0.35.0-rc.0`.

This is what I have in my package.json:
```
   "browser": { "crypto": false },
   "react-native": { "crypto": false }
```
But I get this:

<img width="195" alt="screen shot 2016-09-30 at 4 22 09 pm" src="https://cloud.githubusercontent.com/assets/486224/19009562/1d2934dc-872a-11e6-8aa0-ae7aaee7cd0e.png">

I've tried all the suggestions for clearing cache and reinstalling npm modules. Can't get it to work.

What am I doing wrong here?

**Comment by davidaurelio** [comment]
@lukescott this might be due to a long standing bug in our browser field logic :-( sorry about that

**Comment by adarshTS** [comment]
@gitim @davidaurelio how did u fix this? I have the same error 
![2nd-error](https://user-images.githubusercontent.com/22904766/28963937-7bd64768-7928-11e7-9cc5-6531b8c8fb3f.jpg)

when I did a few corrections it shifter from module 3 to 4 in the same error
