### ISSUE TITLE
Websocket error preventing device build v0.31.0

### ISSUE THREAD

**Issue by nickmacia** [facebook/react-native#9527]
I've upgraded to RN v.0.31.0 which has apparently automated the connection to my device from xcode, so that I don't have to set the url string for my ip. Ideally, I should hit the run button in xcode and it my app should just run on my device, given that both my device and laptop are on the same wifi network (which they are). However, I am getting a websocket error that informs me that no listeners are registered, and my react native packager never finishes loading. In my app, i have a shortened menu which only allows me to reload, debug js remotely, show inspector and show perf monitor- omitting all other options, such as live reload, etc. The websocket error verbatim reads: "Sending `websocketFailed` with no listeners registered." Additionally, on reload, it tells me (on the top banner that briefly appears) that its loading from a pre-bundled file, which is not what I want. Note, my setting for the build scheme is "debug".

I am not sure how to fix this since before I always just adjusted the url in my AppDelegate.m file and my app would run.

**Comment by jchoi18** [comment]
Don't think the websocket error is preventing your build. I get that warning (not error) as well, just means you haven't put a listener for that event in your RCTEventEmitter.

**Comment by jrwm** [comment]
I've got the same issue ...

**Comment by nickmacia** [comment]
I'm closing this. See #9617.
