### ISSUE TITLE
Stateless functional components does not work reliable

### ISSUE THREAD

**Issue by steida** [facebook/react-native#9531]
It sometimes works, but not when the stateless component has a StyleSheet and we are modifying it.

RN 0.31

**Comment by grabbou** [comment]
Are you able to provide a reproducible example showing such behaviour? I've never had such issue and using functional components quite extensively.

**Comment by steida** [comment]
Damn, it works with clean React Native 0.32, but I had two issues in Este and pure React Native installation which were fixed when stateless component was rewritten to ES6 class.

![screen shot 2016-08-23 at 00 46 01](https://cloud.githubusercontent.com/assets/66249/17874491/38b5630a-68cc-11e6-8958-67c79f170374.png)

Second I am not able to reproduce now.

Closing it now. Life sucks.
