### ISSUE TITLE
Issues in facebook website

### ISSUE THREAD

**Issue by saadaouad** [facebook/react-native#9534]
Hello,  I just discovered a tow smalls issues in the facebook website, can you give me please the path of repository facebook in github ?
Cordially.

**Comment by ryankask** [comment]
Which site do you mean? The React Native documentation found at this URL https://facebook.github.io/react-native/?

If so, can you paste a link to the page?

**Comment by Kureev** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-0** [comment]
@Kureev tells me to close this issue. If you think it should still be opened let us know why.

**Comment by saadaouad** [comment]
@ryankask I mean the official website facebook

**Comment by Kureev** [comment]
There is no public repository for a facebook website. 
Please, consider using website interface to report a problem:
![image](https://cloud.githubusercontent.com/assets/2273613/17895328/0d61e198-694d-11e6-989f-d122e985ac24.png)

**Comment by saadaouad** [comment]
Thanks @Kureev
