### ISSUE TITLE
NativeAnimated documantation

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#9536]
Is there any documentation for NativeAnimated? 
For example, witch properties can be animated, witch easings can be used, some tips and examples, etc.

**Comment by nihgwu** [comment]
right now the best document is the examples in `UIExplorer` https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/NativeAnimationsExample.js
and the source code https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/NativeAnimatedHelper.js#L85-L107
