### ISSUE TITLE
PushNotificationIOS Cannot read property 'requestPermissions' of undefined

### ISSUE THREAD

**Issue by qingfeng** [facebook/react-native#954]
![image](https://cloud.githubusercontent.com/assets/18495/7261261/ea27f0a4-e8a2-11e4-8d23-8851f55a590c.png)

What is the reason? thanks....

**Comment by qingfeng** [comment]
```
class indexContent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      tabIndex: 1,
    };
  }

  componentWillMount() {
    PushNotificationIOS.addEventListener('notification', this._onNotification);
  }

  componentWillUnmount() {
    PushNotificationIOS.removeEventListener('notification', this._onNotification);
  }


  render() {
    PushNotificationIOS.requestPermissions();
    return (
      <TabBarIOS>
        <TabBarIOS.Item
    .......
```

**Comment by qingfeng** [comment]
Resolved. . .

look please, The document did not write

![image](https://cloud.githubusercontent.com/assets/18495/7261717/7c3da666-e8a6-11e4-9127-120f068a03cc.png)

![image](https://cloud.githubusercontent.com/assets/18495/7261720/815774ec-e8a6-11e4-8bab-2f118fe072d3.png)

**Comment by lazywei** [comment]
thanks .... this should be added into document ...........

**Comment by ohadpartuck** [comment]
@qingfeng your answer is not clear, what should be added and from where should I add it ?
thanks

**Comment by aymericbouzy** [comment]
Building with Xcode rather than running the command `react-native run-ios` solved it for me.
