### ISSUE TITLE
Why gifs in android works very slow?

### ISSUE THREAD

**Issue by roysG** [facebook/react-native#9543]
I have page with few gifs on it and it works very slow.

Does it bug ? or is suppose to be so slow?

As i understand react is working in native component and not in webview.

Please assist.

**Comment by franzejr** [comment]
Could you give more information? How about the gif size ?

**Comment by charpeni** [comment]
You're right, React Native is working in native components and not in WebView as Cordova/Phonegap do.

On Android, images are handled by [Fresco library](http://frescolib.org/) and it shouldn't be slow.

Are you in remote debugging JS mode? Go to the dev settings and unchecked JS Dev.

**Comment by charpeni** [comment]
@facebook-github-bot label Needs more information

**Comment by rickyn73** [comment]
@roysG  You tried this on web view of React Native or you have created separate screen, to render it in Native code itself.

**Comment by valetarton** [comment]
I have also ran into this issue
when I call the image via 
<Image source={require('path-to-gif')} />
(gif loads super fast)
vs
<Image source={{uri: 'path_to_gif_found_in_drawable'}} />
(gif is painfully slow)

I even ensured in my dev settings, dev was turned off.
Any thoughts?
