### ISSUE TITLE
Can a UDP client/server be built on React Native for Android and IOS?

### ISSUE THREAD

**Issue by wjrivera** [facebook/react-native#9547]
I'm in need for an UDP client that I can send a package over my network and be read by my custom boards written in C.  So far I'm using a MEAN stack for my web server and native android app, but I'm looking to move to a Hybrid app to minimize code for future releases.
Any help would be greatly appreciated.
Thank you

**Comment by martinalderson** [comment]
Sure, you can bridge react native with native code that could send udp packets.

**Comment by ide** [comment]
Yeah, write the Obj-C and Java code that you normally would in order to send UDP packets and then expose a higher-level API to JS. One feature of React Native is that if something cannot be done in JS, you can write native code to do it, so a ton of things are doable.
