### ISSUE TITLE
Using React Native views in RecyclerView

### ISSUE THREAD

**Issue by martinalderson** [facebook/react-native#9549]
We are trying to place React Native views (with initialprops) into recyclerview.

Everything seems to load but the react native view doesn't show unlless we force size, then get crash:

IllegalViewOperationException: ViewManager for tag 871 could not be found

 and then when we add another one we get a crash:

com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 0 view tag: 1
                                                                    detail: View tag:11
                                                                     children(0): [
                                                                    ],
                                                                     indicesToRemove(1): [
                                                                   0,
                                                                    ],
                                                                     tagsToDelete(1): [
                                                                   3,
                                                                    ]

We are using RN version 0.23.1 - would upgrading the version help? We use a similar approach on iOS and it is flawless.

**Comment by Jarred-Sumner** [comment]
Not sure exactly what `RecyclerView` is, but I'm experiencing this error message as well on an Android device.

**Comment by freakinruben** [comment]
Me too on Android, without using `RecyclerView`. It happens always when the app is brought back from the background. Using RN `0.33.0` atm

**Comment by cherniv** [comment]
Same error on android, RN 0.38.1

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by sun2rise** [comment]
I'm on 0.49.5 and it still happens on my android

**Comment by hpyfei** [comment]
0.49.5, have the same problem

**Comment by androidsihai1** [comment]
0.52.0,have the same problem. open app crash  quick.
