### ISSUE TITLE
0.32 "released" but not available on npm

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#9555]
0.32 seems to be released and is referenced everywhere as such for a few days now, but it is not available on npm yet.

**Comment by nihgwu** [comment]
There is a regression about image cache and they are working it out
https://github.com/facebook/react-native/issues/9431#issuecomment-241248540

**Comment by grabbou** [comment]
Yup, here's some explanation https://twitter.com/grabbou/status/768491901846687744
