### ISSUE TITLE
[DatePickerIOS] minuteInterval not work with mode="time" minimumDate={min} maximumDate={max}

### ISSUE THREAD

**Issue by charlesLin** [facebook/react-native#9566]
render() {
  let {year, month, day} = new Date();
    let min = new Date(year, month, day, 8);
    let max = new Date(year, month, day, 22);
return (
<DatePickerIOS
              date={this.state.date}
              mode="time"
              minuteInterval={10}
              minimumDate={min} maximumDate={max}
              onDateChange={(date) => this.setState({date})}
              />);

I found that minuteInterval works on iOS emulator, but not work at real device both minuteInterval and date range feature.

**Comment by ilove8** [comment]
I have a same problem, but not work also my simulator. I'm use version 0.31

**Comment by olliebrennan** [comment]
Ditto. I am running 0.33.0 and this does not work. I am not using min/max date either. Keeping it simple.

**Comment by ferndopolis** [comment]
Confirming same issue. 
Running Xcode 8.0, 
React Native UIExplorer (master branch), with 10 minute interval 
<img width="373" alt="screen shot 2016-09-30 at 9 22 01 am" src="https://cloud.githubusercontent.com/assets/764493/18999009/1c10c04a-86f0-11e6-9368-70a90a4e1b70.png">

CalabashSmokeTest Native UIDatePicker with 30 minute interval
https://github.com/calabash/ios-smoke-test-app
<img width="375" alt="screen shot 2016-09-30 at 9 19 36 am 1" src="https://cloud.githubusercontent.com/assets/764493/18999010/1fc62bf8-86f0-11e6-8f3d-53aa68389859.png">

**Comment by dsibiski** [comment]
@nicklockwood Do you think that your latest commit to the DatePicker could be preventing the `minuteInterval` prop from being set somehow? I wonder if there is something else going on here...

https://github.com/facebook/react-native/commit/c1aff6b116dd8ca42dd81ab59a542a3a6d18e46e#diff-bb7f9a35dd5ae2a59fcff0292caf41f3

**Comment by dsibiski** [comment]
See my comment here for a workaround: https://github.com/facebook/react-native/commit/002024cc456246761421f6e5c354466baa819843#commitcomment-19473525

**Comment by ferndopolis** [comment]
@dsibiski yes, confirming that adding back ```width: 320``` to datePickerIOS style does fix this issue.

**Comment by fr1n63** [comment]
Still an issue at RN 0.38 - minuteInterval isn't passed through in any combination of props.

**Comment by MiLeung** [comment]
I found a workaround for this issue.  In DatePickerIOS, set the minuteInterval prop to a local state.
e.g. `minuteInterval={this.state.minuteInterval}`
Then, in `componentDidMount()`, set `this.state.minuteInterval` to the desired minuteInterval.
e.g.
`
componentDidMount() {
    this.setState({minuteInterval: 5});
}
`

**Comment by dsibiski** [comment]
@MiLeung Thanks! That works great! 👍

**Comment by albinhubsch** [comment]
@MiLeung sorry, that fix did not work for me.

It should be added to the issue that I only see this issue on my iPhone 5c, not my iPhone 6 or the simulator...

**Comment by MiLeung** [comment]
@albinhubsch (These are just ideas)
- Is your 5c on the latest iOS?
- Is your date picker component actually mounted before calling `this.setState({minuteInterval: 5});` or are you return `null` as a result of some logic in your render method?
- What version of RN are you using?  (I was using 39.2 when I found this workaround)

**Comment by maxperry** [comment]
I confirm [@dsibiski workaround](https://github.com/facebook/react-native/commit/002024cc456246761421f6e5c354466baa819843#commitcomment-19473525) works on RN 0.37.  Just add `minWidth: 320` to the DatePickerIOS style.

**Comment by tiaaaa123** [comment]
Both workaround does't work for me in `react-native@0.40.0`

**Comment by Blue-Lan** [comment]
@tiaaaa123 
@dsibiski workaround does work on RN 0.40 for me.
I think some better solutions without modifying native library should be conceived,
or it will be painful every time I upgrade RN to a new version.

**Comment by kyangy** [comment]
@MiLeung method worked for me

**Comment by kushanson** [comment]
@MilLeung your method worked for me on react-native v0.44.3. This is a nice workaround that doesn't involve hacking or forking the react-native libraries. Thank you for sharing!

**Comment by wsun** [comment]
Has anyone had any luck getting minuteInterval to work on RN >= 0.45? Setting fixed width worked for me up to RN 44, but something seems to have changed, such that neither of the above workarounds work.

**Comment by alexbuicescu** [comment]
@wsun, MiLeung's workaround is working for me on RN = 0.48

**Comment by hugoh1995** [comment]
Hey the previous workaround only worked for me when I added a constructor with a different value than the one inside the componentDidMount() method. I set it to 0 in the constructor and to 15 in the componentDidMount() which then worked.

**Comment by Stas-Buzunko** [comment]
@hugoh1995 what version of react native does it work in for you?

**Comment by grabbou** [comment]
This is still an issue.

**Comment by grabbou** [comment]
You can easily debug this by going to RNTester `DatePickerExample` and changing the type of last example to `time` only.

**Comment by dulmandakh** [comment]
This is fixed in #23923. And will be included in a next release.
