### ISSUE TITLE
Proper way to modify ScrollView top or contentInset

### ISSUE THREAD

**Issue by josebalius** [facebook/react-native#957]
Hey guys, my problem is that I have a ScrollView with a couple of text fields, and i want to for the view to scroll up whenever a field is focused (or keyboard) opens. At the moment I have

```
<ScrollView contentInset={{top: (this.state.keyboardOpen) ? -100: 0}}>
   <TextInput onFocus={() => this.setState({keyboardOpen: true})} />
</ScrollView>
```

which changes the state correctly but the scrollview doesn't scroll, if i manually scroll just a bit then the view updates and uses the new contentInset but it doesn't happen automatically.

Is there a better way to do this with RN?

**Comment by ide** [comment]
This is kind of tricky to do with React's programming model but I guess I would use an onScroll handler to track the current contentOffset. When the keyboard opens, increase the bottom contentInset and then call scrollTo(trackedContentOffset + keyboardHeight).

**Comment by josebalius** [comment]
@ide how do you call scrollTo() on a ScrollView?

**Comment by ide** [comment]
Something like `this.refs.scrollView.scrollTo`. The React documentation talks about refs and is a good place to learn if this is the first time you're using them.

**Comment by josebalius** [comment]
@ide ah of course! Just not used to it yet in RN....still in the "holycrap this all really works" stage lol thanks i'll give that a try.

**Comment by josebalius** [comment]
@ide Happy to say this worked perfectly. Thank you.

**Comment by dimoreira** [comment]
@josebalius Can you post your solution?

**Comment by josebalius** [comment]
@dimoreira sure here is what I did

```
<ScrollView ref="scrollView">
   <TextInput onFocus={() => this.refs.scrollView.scrollTo(100)} onBlur={() => this.refs.scrollView.scrollTo(0)} />
</ScrollView>
```

Hope this helps

**Comment by josebalius** [comment]
@ide do you know if any changes have gone into the scrollview animation? This same functionality that I implemented now scrolls really slow, before it was fluid but after updating to 0.4.4 it is pretty slow (almost 2 seconds when it used to take 0.5 at most)

**Comment by ide** [comment]
@josebalius: I'm not aware of what could have caused this slow down. Doesn't seem good though - can you open a new issue with more detail?

**Comment by josebalius** [comment]
@ide nvm :( it was this: http://stackoverflow.com/questions/8624519/simulator-slow-motion-animations-are-now-on somehow I had toggled that on....sorry about that. What gave me the clue was the keyboard was slow to come up everywhere.

**Comment by ide** [comment]
=)
