### ISSUE TITLE
Release mode for iOS on React 0.30.0 

### ISSUE THREAD

**Issue by jr-k** [facebook/react-native#9571]
Hello,

I created a fresh new project with "react-native init my-project"
- I run the app with xcode on "debug" scheme: all green
- I run the app with xcode on "release" scheme: I got these errors : 

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTRootView", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I also checked : [https://github.com/facebook/react-native/issues/2685] and [https://github.com/facebook/react-native/issues/4210] but I didn't found a workaround

Any idea ?

Thanks !

**Comment by jreziga** [comment]
I tried the Dead Code Stripping but now I've this issue : 

clang: error: no such file or directory: '/Users/JRK/Library/Developer/Xcode/DerivedData/MyProject-bnzmjjqcrjgkhidsszdjivdzxnhe/Build/Products/Debug-iphonesimulator/libReact.a'

I have libReact.a in my build phases for both "MyProject" and "MyProjectTests"

**Comment by ksloan** [comment]
I'm seeing the exact same issue... any idea what's causing this?

**Comment by RD1991** [comment]
May be just try by disabling bitcode in build settings.
