### ISSUE TITLE
Navigator not returning anything

### ISSUE THREAD

**Issue by laclance** [facebook/react-native#9576]
My navigator wasn't rendering anything (only a white screen) so I have reduced it to bare minimum and still get nothing. I am using windows and android and react-native 0.31.0".

    `import React, { Component } from 'react';
    import {
      AppRegistry,
      StyleSheet,
      Text,
      Navigator
    } from 'react-native';

    class MyApp extends Component {
      render() {
        return (
            <Navigator style={styles.container}
                initialRoute={{ title: 'My Initial Scene'}}
                renderScene={(route, navigator) => {
                    <Text>Hello</Text>
                }}
            />
        );
      }
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
      },
    });

    AppRegistry.registerComponent('MyApp', () => MyApp);`

**Comment by krishbhattacharyya** [comment]
As per my knowledge navigator will not render anything. You should use navigator bar or view in react native.  Navigator is  just used for route. In your code this only route. Please close this issue. Go through - https://facebook.github.io/react-native/docs/navigator.html.

**Comment by laclance** [comment]
Yes, I understand, thank you,

**Comment by wonnage** [comment]
Wait a minute, this answer makes no sense - your code should be rendering "Hello". I ran into this same issue and the problem is that if you apply `alignItems: center`, it prevents the Navigator from rendering anything. This also makes no sense - can someone explain why that's the case?
