### ISSUE TITLE
Does TextInput's actual height includes border and padding？

### ISSUE THREAD

**Issue by LitleCarl** [facebook/react-native#9580]
As you can see:

```
style={{
          width:100,
          height: 30,
          borderWidth:1,
          paddingTop:100
             }}
```

The expected size is to be 100*132.

However it is 100*102 which height of 102 is made up of paddingTop and borderWidth.

Does this have something to do with element type like inline or block type?

**Comment by LitleCarl** [comment]
<img width="347" alt="64b56950-a9c4-43ca-9bf1-869d50a4d710" src="https://cloud.githubusercontent.com/assets/8946363/17954562/553b10b8-6aae-11e6-9e67-39ac58a2b0f5.png">

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox
