### ISSUE TITLE
Funny way to speed up Android startActivity() view rendering

### ISSUE THREAD

**Issue by shihpeng** [facebook/react-native#9582]
First of all, I am not sure if this is bug or something, I also [posted this on StackOverflow](http://stackoverflow.com/questions/39135931/funny-way-to-speed-up-react-native-android-view-rendering) and hope someone can help to confirm or solve this.

In my app, some pages are launched by using `startActivity()`. However, we found that `ReactRootView`s in new Activities rendered very slow, which makes the screen almost ~500ms delay. The `onCreate()` method in the called Activity like:

```
public class PageActivity extends AppCompatActivity {

    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;
    private ReactContext mReactContext;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = getIntent();
        String uriString = intent.getStringExtra("uri");

        // use the cached ReactInstanceManager
        mReactInstanceManager = MyApplication.getReactInstanceManager();

        mReactRootView = new ReactRootView(this);
        mReactRootView.startReactApplication(mReactInstanceManager, uriString, null);
        setContentView(mReactRootView);
    }
    ....
}
```

To solve this issue, we found that by adding a dummy `ReactRootView` creation line in the `Application`'s `onCreate()` method significantly speed up view rendering in the new Activities.

Just add the line like this:

```
public class MyApplication extends Application implements ReactApplication {

    // cache the ReactInstanceManager
    private static ReactInstanceManager mReactInstanceManager;

    private static ReactContext mReactContext;

    @Override
    public void onCreate() {
        super.onCreate();
        initConifg();
        // the dummy ReactRootView creation
        ReactRootView reactView = new ReactRootView(MyApplication.getApplication());
    }
    ...
}
```
 
The following is the systraces of the same Activity with/without the dummy ReactRootView line:

Without the line: 
<img width="993" alt="2016-08-25 10 38 33" src="https://cloud.githubusercontent.com/assets/651300/17955574/da0a97d0-6ab5-11e6-91bb-1e05cf96fdf7.png">

With the line:
<img width="1012" alt="2016-08-25 10 38 41" src="https://cloud.githubusercontent.com/assets/651300/17955544/9ac2ada6-6ab5-11e6-8e2b-b976dfb01b2d.png">

As you can see, the very slow frame is gone if the line is added. 

Hope someone can help to confirm (or bust) this, thanks.

I am using React-Native 0.31, this only occurs in Android.

**Comment by JeffreyLeeSpokeo** [comment]
How does that help? Because you aren't using the ReactRootView from the MyApplication are you?
