### ISSUE TITLE
run-android is failing in Windows

### ISSUE THREAD

**Issue by echorohit** [facebook/react-native#9584]
- [x] What's the **version** of React Native you're using?  

```
$ react-native -v
react-native-cli: 1.0.0
react-native: 0.31.0
```
- [x] Does this occur on iOS, Android or both? Android
- [x] Are you using Mac, Linux or Windows? Windows 7

I am trying to build my app and install it on running emulator device.  I am getting this exceptions when I run this command.

```
$ react-native run-android
JS server already running.
Running C:\Users\Rohit Kumar2\AppData\Local\Android\Sdk/platform-tools/adb reverse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat installDebug...
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.PathAssembler.getDistName(PathAssembler.java:84)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:40)
        at org.gradle.wrapper.Install.createDist(Install.java:42)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by rmevans9** [comment]
I would recommend manually running gradlew.bat as I have found that it sometimes prints more of the error message when you do that. Simply cd to android directory and then run "gradlew.bat installDebug"

**Comment by Fabho** [comment]
When I run gradlew.bat installDebug I have this output
* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Unable to upload some APKs

**Comment by echorohit** [comment]
@rmevans9 I did same already. But again the same error is there. I think the error is more of android virtual device manager. Gradle is not able to set up project.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/run-android-is-failing-in-windows

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
