### ISSUE TITLE
Session or temporary cache / persistence?

### ISSUE THREAD

**Issue by iq-dot** [facebook/react-native#959]
Hi guys,

Is there a way to have store some items in a temporary persistence say while the app is running / loaded but disappears upon the app closing?

This is so that upon opening the app, I can re-fetch but after re-fetching I can for optimisations sake keep in in some fast local memory.

I currently use AsyncStorage for long-term persistence but was wondering if there was anything for fast short-term temporary persistence? Sort of like having a singleton being passed around.

**Comment by ide** [comment]
Could you simply use a global singleton as you mentioned?

**Comment by nicklockwood** [comment]
Not currently, but it's an interesting idea. Obviously you can store stuff in JS memory, but it can't be shared between RootViews.

A generic key-value store BridgeModule that wraps a dictionary would be very simple to write. In fact, here's all the native code you'd need if you feel like making one for yourself (completely untested of course) :-)

RCTKeyValueStore.h file

  #import <RCTBridgeModule.h>

  @interface RCTKeyValueStore : NSObject<RCTBridgeModule>
  @end

RCTKeyValueStore.m file

  #import "RCTKeyValueStore.h"
  #import "RCTConvert.h"

  @implementation RCTKeyValueStore
  {
    NSMutableDictionary *_store;
  }

  RCT_EXPORT_MODULE()

  - (instancetype)init
  {
    if ((self = [super init])) {
      _store = [[NSMutableDictionary alloc] init];
    }
    return self;
  }

  RCT_EXPORT_METHOD(setValues:(NSDictionary *)values)
  {
    [_store addEntriesFromDictionary:values];
  }

  RCT_EXPORT_METHOD(getValues:(NSStringArray *)keys callback:(RCTResponseSenderBlock)callback)
  {
    NSDictionary *values = [_store dictionaryWithValuesForKeys:keys];
    callback(@[values]);
  }

  RCT_EXPORT_METHOD(deleteValues:(NSStringArray *)keys)
  {
    [_store removeObjectsForKeys:keys];
  }

  @end

It (and the data in it) would persist for the lifetime of the bridge, but would not survive a cold app restart or a Cmd-R. Hope that helps!

**Comment by ide** [comment]
@nicklockwood - couldn't you achieve the same with a global JS object, which has the same scope and life cycle as a bridge module? You'd then get a synchronous API and skip marshalling data across the bridge. I could be missing something. The entire DataStore.js could be `/** @providesModule DataStore */`, no code at all maybe.

**Comment by nicklockwood** [comment]
@ide, yeah I guess so. Mine was more fun to write though ¯\_(ツ)_/¯

**Comment by iq-dot** [comment]
A js solution would be great but what I have tried gave me no luck with
persistence lost on view change.

**Comment by ide** [comment]
@iq-dot could you explain what you mean when you say "view change"?

**Comment by iq-dot** [comment]
As in for example I have a TabBar view and I switch tabs to which re-renders part of the view, which re-requires a module that I tried to use to hold a value in memory, which works as long as I am in the same view and it hasn't been replaced.

Could you show me an example @ide on what you are proposing? Do you mean something like this:

```
var DataStore = {
} 

module.exports = DataStore
```

**Comment by mjw56** [comment]
@iq-dot I've used flux to solve what I think is a similar problem to what you are describing.

Basically, I had a component on the parent level who was always alive and would need to get updates from a component deep in the route stack. I have the parent level component listening to a flux Store which is alive for life of the app. So when I am deep into the stack, I can send an action to update the store and notify my parent-level component of the changes.

**Comment by iq-dot** [comment]
Flux does sound appealing, I was actually unsure of integrating it with react-native in the beginning so it is nice to see someone using it.

Although for me not sure if I am able to integrate that into my app at this stage, I may have to delay that with more time in hand.

**Comment by ide** [comment]
@iq-dot that DataStore module is what I had in mind. Two different components in the same React app will get the same copy of the module so they can use it to share data with each other.

It sounds like you are using a UITabBarController and multiple RCTRootViews if you are unable to share data between screens. In this case you could make all the root views share the same bridge, and then the RCTRootViews will share modules.

**Comment by iq-dot** [comment]
Yeah I had another go and I can solve it with a pure JS solution in my case.

Nicks idea is good for when you are dealing with multiple root views and flux I guess will be similar to the JS solution talked about here.

For now I could close this ticket and perhaps looking at a bridging module as part of a future extension? I am sure it would be useful not to touch AsyncStorage all the time.
