### ISSUE TITLE
URLSearchParams sometimes available

### ISSUE THREAD

**Issue by dantman** [facebook/react-native#9596]
RN implements the Fetch API as a method of making HTTP requests. [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is part of a related standard directly referred to by the Fetch API standard. It is both used by `URL` for managing query arguments and is also the native way of building `application/x-www-form-urlencoded` requests as the `FormData` object only works for `multipart/form-data` requests. `URLSearchParams` can either be converted to a string to use as body or passed directly to fetch as the body property.

A URLSearchParams implementation exists in the RN codebase, in fact when I started porting an API generator that used `require('http')` to use Fetch instead so I could use it in React Native, I was directly using `URLSearchParams` and it worked.

However I've discovered that sometimes an action triggering a HTTP request using `URLSearchParams` in my app will work and other times the exact same action and HTTP request using `URLSearchParams` will generate an error like this.
![screenshot_20160825-154146](https://cloud.githubusercontent.com/assets/53399/17988345/7fa2b104-6ada-11e6-8bb2-4f3b7f40f17d.png)

Originally I wasn't certain about what situations it worked and which ones it did not; however, recently I've noticed that when 'Debug JS Remotely' is enabled things work and when disabled I get the error.

My current presumption is that React Native bundles the `URLSearchParams` used by the Fetch API when remote debugging is enabled and omits it when it is not.

This is potentially extremely unexpected for a developer. It's a part of a standard API, requested by an API RN claims to implement, and when a developer is testing their code when they write it it is available; but later on when they come back to the same code they finished writing things are suddenly broken.

**Comment by ryankask** [comment]
I hadn't heard of `URLSearchParams` before but that seems useful!

This was actually brought up before and it was decided not to add it: https://github.com/facebook/react-native/issues/6141.

React Native doesn't bundle `URLSearchParams` but when you use "Debug JS Remotely", you're JS is running in Chrome which I suppose does natively support it.

You're best bet at the moment is to use a polyfill.

**Comment by dantman** [comment]
Oh, I wasn't aware that in that mode all the JS was running in Chrome, I thought it was just a bridge that forwarded what was needed for debugging.

Things have changed a little since that bug:
* That bug referred to the Jxck/URLSearchParams polyfill and noted it was marked as WIP
* The currently dominant polyfill appears to be [WebReflection/url-search-params](https://github.com/WebReflection/url-search-params)
* github/fetch (the Fetch API polyfill RN uses) actually has a devDependency on WebReflection/url-search-params
* https://github.com/github/fetch/issues/296#issuecomment-196432365: github/fetch explicitly supports the `URLSearchParams` polyfills and doesn't appear to plan to implement them itself, instead implying that `URLSearchParams` and the Fetch polyfill should be used together

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/urlsearchparams-sometimes-available

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close
