### ISSUE TITLE
[WebView] Allow passing allowsInlineMediaPlayback as a boolean

### ISSUE THREAD

**Issue by jonathanong** [facebook/react-native#960]
currently doing adding `_webView.allowsInlineMediaPlayback = YES;` in `RCTWebView.m` to get around this.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/#//apple_ref/occ/instp/UIWebView/allowsInlineMediaPlayback

**Comment by brentvatne** [comment]
@jonathanong - can you create a PR for this? seems like a simple change, you can refer to the recently pushed [Native UI Components](https://facebook.github.io/react-native/docs/nativecomponentsios.html#content) guide or ping me on irc @notbrent if you need a hand.

**Comment by erikdung** [comment]
Could you please show me where to add this in RTCWebView.m? Thanks

**Comment by brentvatne** [comment]
@erikdung - you can add that here: https://github.com/facebook/react-native/blob/master/React/Views/RCTWebView.m#L39

**Comment by erikdung** [comment]
Great. Thanks. I solved my problem when creating app with youtube videos. I disabled fullscreen mode.

**Comment by facebook-github-bot-3** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by MadRabbit** [comment]
+1 can we make this happen? also while you're on it, could you add an option for `mediaPlaybackRequiresUserAction`

**Comment by brentvatne** [comment]
@MadRabbit - PR welcome!

**Comment by chirag04** [comment]
https://github.com/facebook/react-native/commit/7da42e3950169b12c78a450ac83cbee8c9141dff added option for ``allowsInlineMediaPlayback`` in webView.

@jonathanong closing this infavour of that commit. Let me know if we need to reopen this.

@MadRabbit Can you open a separate issue for ``mediaPlaybackRequiresUserAction`` and possibly PR?
