### ISSUE TITLE
Stack trace symbolication fails when importing a module that itself imports whatwg-fetch

### ISSUE THREAD

**Issue by jeanregisser** [facebook/react-native#9605]
I came across an interesting bug while playing with [apollo-client](https://github.com/apollostack/apollo-client) and React Native.
What happened is red box stack traces would not be symbolicated anymore.

Digging deeper I identified it was caused by the fact that `whatwg-fetch` was also being imported by apollo-client.

Here's a sample code to reproduce the issue:

``` jsx
// This import triggers the problem and results in an undefined 'fetch' 
// exported by react-native/Libraries/Fetch/fetch.js
import 'whatwg-fetch'; 
// Same problem would occur if you try to import any other 3rd party module
// that transitively imports 'whatwg-fetch'. For instance:
// import ApolloClient from 'apollo-client';

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

class MyProject extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}

// Intentional typo to trigger the red box stack trace
const styles = StyleShee.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('MyProject', () => MyProject);
```

This happens on both iOS and Android.
Confirmed on RN 0.31 and 0.32. Using OSX.

Here's what happens in the normal case (when `whatwg-fetch` is not imported directly):
1. An exception is raised because of the typo
2. Symbolication code is triggered and  [symbolicateStackTrace.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace.js) is loaded
3. [fetch](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace.js#L14) hasn't been required yet, hence [Libraries/Fetch/fetch.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/Fetch/fetch.js#L15) is loaded
4. [whatwg-fetch](https://github.com/github/fetch/blob/v1.0.0/fetch.js) is loaded
5. It checks that [fetch is not yet polyfilled](https://github.com/github/fetch/blob/v1.0.0/fetch.js#L4) 
6. Since `global.fetch` is [lazily loaded](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L180), it takes the exported `fetch` of `Libraries/Fetch/fetch.js` which is currently `undefined` as `Libraries/Fetch/fetch.js` has not yet finished loading
7. `whatwg-fetch` finishes setting the global `fetch`
8. `fetch` is now available from the global context, hence it's can be correctly exported by [Libraries/Fetch/fetch.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/Fetch/fetch.js#L17)
9. `fetch` does it jobs and symbolication succeeds

Here's what happens in the buggy case (when `whatwg-fetch` is imported directly or indirectly by another module):
1. [whatwg-fetch](https://github.com/github/fetch/blob/v1.0.0/fetch.js) is loaded
2. it checks that [fetch is not yet polyfilled](https://github.com/github/fetch/blob/v1.0.0/fetch.js#L4)
3. Since `global.fetch` is [lazily loaded](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L180), it triggers the load of [Libraries/Fetch/fetch.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/Fetch/fetch.js)
4. However, as `whatwg-fetch` is currently being loaded, nothing happens
5. Hence an undefined `fetch` is now exported by [Libraries/Fetch/fetch.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/Fetch/fetch.js#L17) as `whatwg-fetch` has not yet set the global `fetch`
6. `whatwg-fetch` then finishes setting the global `fetch`
7. The exception raised because of the typo is triggered
8. Symbolication code is triggered and  [symbolicateStackTrace.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace.js) is loaded
9. [fetch](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace.js#L14) has already been required but is exported as `undefined`
10. Symbolication hence fails and throws a new exception 

```
2016-08-26 16:40:26.501 [warn][tid:com.facebook.react.JavaScript] Unable to symbolicate stack trace: fetch is not a function. (In 'fetch(devServer.url+'symbolicate',{
method:'POST',
body:JSON.stringify({stack:stack})})', 'fetch' is undefined)
```

I'm not yet sure what the best fix is.
- we could remove `const {fetch} = require('fetch');` from [symbolicateStackTrace.js](https://github.com/facebook/react-native/blob/63931b1a683c924ddbe86140a189b79427541d32/Libraries/JavaScriptAppEngine/Initialization/symbolicateStackTrace.js#L14)
- or make sure `fetch` is not lazily loaded
- else?

I'm happy to send a PR with whichever way you think is best.

Let me know if all is clear.

**Comment by gsinovsky** [comment]
Hi @jeanregisser, I encountered this issue as well and I haven't been able to find an ideal solution either, in my case is the [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch/) package which imports the `whatwg-fetch` and causes the conflict with React Native that you described. My temporary workaround has been to comment [this](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-browserify.js) file. I'm using RN 0.31.0-rc.1.

**Comment by hilkeheremans** [comment]
Also experiencing this issue on RN 0.34, both because of `isomorphic-fetch` and another, in-house library.

I'm not sure I agree with either of the two solutions you propose, mostly because they introduce some fragility/potential perf issues.

I submitted PR #10247 which should provide a more robust workaround. More info there - feel free to comment (t)here if you do not agree with the proposed solution.

**Comment by lacker** [comment]
https://github.com/facebook/react-native/pull/10247 is merged so I believe this should be fixed. Thanks everyone for providing feedback and fixing things!
