### ISSUE TITLE
Navigator.NavigationBar - cannot set property '_key' of undefined

### ISSUE THREAD

**Issue by andyfen** [facebook/react-native#9610]
<img width="379" alt="screen shot 2016-08-26 at 13 41 52" src="https://cloud.githubusercontent.com/assets/5710962/18019889/295d51b4-6b93-11e6-8c79-99a55ec576d6.png">

> "react-native": "0.32.0",

tested with the example code still getting this error ?

test code 

```
class App extends Component {
  render() {
    const routes = [
      {title: 'First Scene', index: 0},
      {title: 'Second Scene', index: 1},
    ];
    return (
      <Navigator
        initialRoute={routes[0]}
        initialRouteStack={routes}
        renderScene={(route, navigator) =>
          <TouchableHighlight onPress={() => {
            if (route.index === 0) {
              navigator.push(routes[1]);
            } else {
              navigator.pop();
            }
          }}>
          <Text>Hello {route.title}!</Text>
          </TouchableHighlight>
        }
        style={{padding: 100}}
        navigationBar={
           <Navigator.NavigationBar
             routeMapper={{
               LeftButton: (route, navigator, index, navState) =>
                { return (<Text>Cancel</Text>); },
               RightButton: (route, navigator, index, navState) =>
                 { return (<Text>Done</Text>); },
               Title: (route, navigator, index, navState) =>
                 { return (<Text>Awesome Nav Bar</Text>); },
             }}
             style={{backgroundColor: 'gray'}}
           />
        }
      />
    );
  }
}


```

**Comment by samuelkraft** [comment]
I have a similar issue. `undefined is not and object (evaluating '_this._key = guid()')` in NavigatorNavigationsBar.js:114 after upgrading to 0.32. 

Building with Xcode 8 for iOS 10 - not sure if related.

**Comment by johnryan** [comment]
Seeing a similar looking issue with the WebView component "Cannot read property 'props' of undefined" in  `WebView._this2._onLoadingStart`. The error goes away if I downgrade to RN 0.31.0.

**Comment by chrise86** [comment]
Also getting `undefined is not an object (evaluating '_this._key = guid()')` on RN `0.33.0`.

**Comment by AWDGroup** [comment]
I still have the same issue using RN 0.35.0

[![Screen Shot 2016-10-22 at 15.13.24.png](https://s12.postimg.org/jqixrvuz1/Screen_Shot_2016_10_22_at_15_13_24.png)](https://postimg.org/image/u0lcr4kuh/)

```
 <Navigator
                style = { styles.container }
                navigationBar={
                    <Navigator.NavigationBar
                        routeMapper={{
                            LeftButton: (route, navigator, index, navState) =>
                            { return (<Text>Cancel</Text>); },
                            RightButton: (route, navigator, index, navState) =>
                            { return (<Text>Done</Text>); },
                            Title: (route, navigator, index, navState) =>
                            { return (<Text>Awesome Nav Bar</Text>); },
                        }}
                        style={{backgroundColor: 'gray'}}
                    />
                }
                initialRoute = { { name: ROUTES.TODOS } }
                renderScene = { this.renderScene.bind(this) }
                configureScene = { () => { return Navigator.SceneConfigs.FloatFromRight; } } />
```

**Comment by PhillippOhlandt** [comment]
Any updates on this?

Cloned a project at work with react-native 0.35.0 and get the `react native undefined is not an object (evaluating '_this._key = guid()')` error. It works for all others, though.

**Comment by PhillippOhlandt** [comment]
Found the solution. `npm install guid --save`. It's imported from react native, but not required. Such a mess :fire:

**Comment by AWDGroup** [comment]
@PhillippOhlandt I tried your suggested solution, but I'm still getting the same error as soon as I'm using the built in Navigator.NavigationBar, did you change anything else? can you paste your .babelrc file? Thanks

**Comment by PhillippOhlandt** [comment]
@AWDGroup ok, what I also had to do: 

Commenting the line `_this._key = guid()` (the one he complained) out, restart the packager and app, see it working, uncomment the line again and see it working again. I am pretty sure this isnt a real fix but at least I was able to work. Did I already say that it's a mess?

**Comment by hramos** [comment]
Navigator has been deprecated in favor of the [`react-navigation`](https://reactnavigation.org) library.
