### ISSUE TITLE
Fetch not support cookie anymore?

### ISSUE THREAD

**Issue by jaggerwang** [facebook/react-native#9620]
### Environment
react@15.3.1
react-native@0.32.1

### Problem
After installed app to simulator or device, On first login, the cookie from server not saved, caused login failed. Press cmd=R to reload app, login again, succeed!

```javascript
/**
 * Zai Qiu Chang App
 * https://www.zaiqiuchang.com/
 */

import {Actions} from 'react-native-router-flux';
import URL from 'url';

import logger from '../logger';
import {store} from '../setup';
import * as actions from '../actions';
import * as apis from './';

export function getApi(url, query={}, {method='GET', headers={}, timeout=5000}={}) {
  url = URL.parse(url, true);
  url.query = query;
  url = URL.format(url);
  let request = new Request(url, {method, headers, timeout});
  return fetchApi(request);
}

export function postApi(url, data={}, {method='POST', headers={}, timeout=5000}={}) {
  if (Object.keys(data).length == 0) {
    data._ = 'fix android empty body bug';
  }
  let body = new FormData();
  for (let [k, v] of Object.entries(data)) {
    body.append(k, v);
  }
  let request = new Request(url, {method, headers, body, timeout});
  return fetchApi(request);
}

export async function fetchApi(request) {
  let responseJson = null;
  try {
    logger.debug(request.url);
    store.dispatch(actions.loadingStart());
    let response = await fetch(request);
    if (!response.ok) {
      throw new apis.HttpError(response.status, apis.HTTP_STATUS[response.status]);
    }
    responseJson = await response.json();
    let {code, message, data} = responseJson;
    if (code != 0) {
      throw new apis.ResultError(code, message, data);
    }
  } catch (error) {
    return Promise.reject(error);
  } finally {
    store.dispatch(actions.loadingEnd());
  }
  logger.debug(responseJson);
  return responseJson;
}
```

**Comment by jaggerwang** [comment]
Is this related to the app name. I changed the name from default 'app' to 'zaiqiuchang' recently.

**Comment by jaggerwang** [comment]
And I found the Response of fetch is not containing 'Set-Cookie' header, even server returned.

Server response header:
![image](https://cloud.githubusercontent.com/assets/1255011/18031420/612b35f4-6d12-11e6-96d0-68c37127aa71.png)

Fetch response header:
![image](https://cloud.githubusercontent.com/assets/1255011/18031428/9b89f9c4-6d12-11e6-9dd0-b536a8e51dfe.png)

**Comment by Smallpath** [comment]
+1

Android
react@15.3.1
react-native@0.32.0

**Comment by Smallpath** [comment]
Any updates? I saw the fetch still can't get cookie in UIExplorer using v0.33

**Comment by jaggerwang** [comment]
I'm ok now after upgrading RN to 0.32.1.

**Comment by Smallpath** [comment]
Thanks a lot ! I will try it at once

**Comment by Smallpath** [comment]
@jaggerwang I tried 0.32.1 but still failed . The process that fetch set/get cookie works perfect , however the cookie isn't here in the response header. 

Can you find the cookie at the response rather than wireshark?

**Comment by jaggerwang** [comment]
Yes, it's still not working. I previously add Cookie header in code for debugging, after upgrade RN to 0.32.1, I removed these code, and it's still working, so I thought the bug is solved. But after I reinstalled app in simulator, the bug is came out again.

**Comment by jaggerwang** [comment]
I found the reason. It seems it take a while to save cookie, so you can not request immediately after received cookie header, you should wait a few seconds. It's so weird!

**Comment by jaggerwang** [comment]
Confirmed again. When first login on simulator or device, the cookie from server not saved, caused login failed. Reload app, login again, succeed!

**Comment by jaggerwang** [comment]
My fault! The server not response Set-Cookie header correctly.
