### ISSUE TITLE
reload will crash on version 0.32.0

### ISSUE THREAD

**Issue by zackteng** [facebook/react-native#9622]
### Environment

iOS
react@15.3.0
react-native@0.32.0
MacBook Pro OSX EI Capitan 10.11.6

### Problem
When i reload current React Native view(CMR+R or press Reload on Developer Menu), sometimes it will crash. (The version 0.31.0 is not crash)
The crash message is like this:
![image](https://cloud.githubusercontent.com/assets/6346325/18032336/a01c1bc6-6d34-11e6-9656-2d25db5ecf2c.png)
or
![image](https://cloud.githubusercontent.com/assets/6346325/18032325/4f81a578-6d34-11e6-9bbf-a8614bc90ec8.png)

I use React Native Integration With an Existing  App, my code is:
AppDelegate.m
![image](https://cloud.githubusercontent.com/assets/6346325/18032375/650137fa-6d35-11e6-80ab-e94ef4de75fc.png)

ListViewController.m
![image](https://cloud.githubusercontent.com/assets/6346325/18032384/9c70b846-6d35-11e6-8e84-8f38c67e487a.png)

**Comment by jan-happy** [comment]
Had the same problem yesterday, but cannot reproduce today.

**Comment by hunghc** [comment]
Hello, I figured out this problem by
File: RCTRootView.m
Import _RCTBridge+Private.h_
Change _[self bundleFinishedLoading:_bridge];_ to  _[self bundleFinishedLoading:[_bridge batchedBridge]];_

Hope this help!!

**Comment by zackteng** [comment]
It seems ok on version 0.33
