### ISSUE TITLE
[NavigationCardStack] componentWillMount called on every route

### ISSUE THREAD

**Issue by ggordan** [facebook/react-native#9628]
Hi all,

I'm not sure if this is a bug/feature or just me misusing the NavigationCardStack, but I've noticed that for every route that I push, the `componentWillMount` method is called on every single component in the routes array. So for example,

- I push a route (`NavigationStateUtils.push`) a to render component `A`, at index 0 at which point the `componentWillMount()` of `A` triggers as the component is rendered (as expected).
- I press a button which pushes a route to render the component `B` using `NavigationStateUtils.push`. At this point, the `componentWillMount` is called for `A` again, and `B`.
- I follow the above again for component `C` at which point `A`, `B` and `C` are re-rendered. 

So the question is whether there is a way to turn this off (or at least only render the last two scenes)?

**Comment by ryankask** [comment]
Can you post some example code that demonstrates this? This shouldn't be happening.

**Comment by ggordan** [comment]
@ryankask certainly. I've removed things that I don't believe a relevant, however

The Main component which is in charge of rendering the application screens. It is wrapped in the `react-native-drawer` component and is connected to redux. The component is class based.

```javascript

  _renderScene (data) {
    const propsToPass = {
      onNavigate: this.props.onNavigate,
      key: data.scene.route.key
    }

    const Screen = screens[data.scene.route.screen].handler

    return (
      <App>
        <Screen {...propsToPass} />
      </App>
    )
  }

  _renderOverlay (props) {
    const { scene } = props

    const header = screens[scene.route.screen].header
    if (!header) {
      return false
    }

    const propsToPass = {
      onMenuToggle: this.openMenu.bind(this),
      ...props
    }

    return React.createElement(header, propsToPass)
  }

  render () {
    return (
      <Drawer
        tapToClose
        ref={ref => this._drawer = ref}
        openDrawerOffset={100}
        content={<Menu closeMenu={this.closeMenu.bind(this)} />}>
        <NavigationTransitioner
          navigationState={navigationState}
          style={styles.container}
          render={(props) => <NavigationCardStack
            {...props}
            style={styles.container}
            onNavigateBack={() => this.props.actions.navPop()}
            renderOverlay={this._renderOverlay}
            renderScene={this._renderScene}
            key={props.scene.route.key}/>
          }/>
      </Drawer>
    )
  }
```

The two action creators

```javascript
export const navPush = screen => ({
  type: NAV_PUSH,
  payload: screen
})

export const navPop = () => ({
  type: NAV_POP
})
```

The navigation reducers

```javascript

const loggedOutState = {
  key: 'LoggedOutNavigation',
  index: 0,
  routes: [
    { key: 'Login', screen: 'Login' }
  ]
}

const generateRoute = (screen, title) => ({
  key: `${screen}.${Date.now()}`,
  title: title || screen,
  screen
})

export default createReducer(loggedOutState, {
  [NAV_PUSH]: (state, payload) => {
    const { index, routes } = state
    if (routes[index].screen === payload) {
      return { ...state }
    }
    return NavigationStateUtils.push(state, generateRoute(payload))
  },
  [NAV_POP]: (state, payload) => NavigationStateUtils.pop(state),
  [LOGIN_SUCCESS]: (state, payload) => NavigationStateUtils.push(state, generateRoute('Dashboard'))
})

```

And the `createReducer` function

```javascript
export default (initialState, reducerMap) => {
  return (state = initialState, action) => {
    const reducer = reducerMap[action.type]
    return reducer
      ? reducer(state, action.payload)
      : state
  }
}
```

All the routes are pushed/popped using the the two action creators.

**Comment by ryankask** [comment]
`NavigationCardStack` actually renders its own `NavigationTransitioner`. It's totally fine to use more than one `NavigationTransitioner` but based on your choice of key I'm not sure if that's what you meant.

So basically in the `Drawer` you just want to render `NavigationCardStack` on its own, passing it your navigation state. Check this out: https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStack.js#L109

**Comment by ggordan** [comment]
@ryankask that resolved my issue, thanks. Guess I should poke around before submitting an issue. So after removing the `NavigationTransitioner` all is working as expected. Thanks!
