### ISSUE TITLE
Remove the first line indent for <Text>

### ISSUE THREAD

**Issue by younthu** [facebook/react-native#9632]
Hi, 

  I used <Text> in a <View>, with property "numberOfLine={5}", it works except that it has first line indent.

 How can i remove the first line indent please?

**Comment by ggordan** [comment]
Does your text start with a white space `<Text> Hello </Text>` vs `<Text>Hello</Text>`

**Comment by younthu** [comment]
@ggordan , You are right.

It seems the react native translated the space before {} as a space char.
`
<Text numberOfLine={5}> {textValue}</Text>
`

there is a space between '{5}>' and '{textValue}', it is a keng(坑).

Thank you ggordan!
