### ISSUE TITLE
syntax errors hidden when using remote debugging

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#9638]
- build on device or emulator using `react-native run-android` and then `react-native start` (it has never automatically started for me)
- test the app with remote debugging activated
- make a syntax error in your code
- reload js
- the following errors pop up in Chrome:

```
GET http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false 500 (Internal Server Error)
```

and

```
Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false' failed to load.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:33
```

without remote debugging activated the red screen tells you the location of the error.
- This occurs on both Android and iOS (have only tested it on Android myself)
- react-native 0.32.0
- Ubuntu Gnome 15.10

**Comment by shmily617** [comment]
I met the same problem.
BTW, did you find any solution?

**Comment by ThaJay** [comment]
The only way to see the location of the syntax error I found is to disable remote debugging when you have this. It then reloads and the syntax error will show up on the red error screen inside the app.

**Comment by shmily617** [comment]
I have wrote a login & register function, which use socket to communicate with server. However, it dosen"t work unless  in the condition that **Debug JS Remotely** in simulator. Now, I am trying it on IOS devices, I met this problem. And I have to **Debug JS Remotely**, or my function will not work.

**Comment by ThaJay** [comment]
What version of react-native are you using? I have lost websockets at version 30 so maybe try 29.2 as well?
all this information is in the op already

**Comment by shmily617** [comment]
I am using version30 ,and now I have solved my problem by add  `  NSURL *jsCodeLocation;
  [[RCTBundleURLProvider sharedSettings] setDefaults];
#if DEBUG
  [[RCTBundleURLProvider sharedSettings] setJsLocation:@"10.107.31.112"];
#endif` before `jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];` in **AppDelegate.m**

**Comment by ThaJay** [comment]
Nice, could you maybe check if it's in v0.33.0-rc.0 already and make a pull request if it's not?

**Comment by noahschutte** [comment]
@shmily617 Can you please provide a code sample of your implemented code?

**Comment by mhsekhavat** [comment]
I tried suggestion of @shmily617  but it didn't work. Is there any plan on resolving this issue?

**Comment by ThaJay** [comment]
just disable remote debugging and reload.
fix the error and enable remote debugging again.

I would not count on the react-native team to chime in on this ...

**Comment by mhsekhavat** [comment]
I found out details of import error are logged in react-native remote server logs. Look for them in output logs of `npm start` command on server instead of exception itself on device.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by amackintosh** [comment]
I just spent about 20 mins experiencing this and getting extremely confused over the output I was seeing.

Long story short, I had:
```
const onLoginSuccess = ({ token, navigation }) => {
```

instead of:
```
export const onLoginSuccess = ({ token, navigation }) => {
```

in my action creators file, so it was as mentioned above, a syntax error because I wasn't exporting the function, so it was blowing up.

It could be an opportunity to improve the debugging, I don't know. It should have somehow told me the function didn't exist. I thought it was running and getting really confused why there was a bundle error that I couldn't even inspect.

**Comment by ThaJay** [comment]
Import errors are a dfferent issue, but they are indeed hard to read as well. I have to decypher a blob of text on the red screen to figure out the name of the module that failed to import.
