### ISSUE TITLE
I am using fetch api to call the service , but it is keep hitting the server , I don't know why

### ISSUE THREAD

**Issue by rajatgupta1993** [facebook/react-native#9642]
function making the request : 
It is my container : 

class UserPreviewContainer  extends React.Component{
 constructor(props){
  super();
     this.state = { 
                    isLoading:'false', 
                    userPreview:props.data,
                    };
        this.getUserPreview = this.getUserPreview.bind(this);
        this.getUserPreviewSuccess = this.getUserPreview.bind(this);
        this.getUserPreviewError = this.getUserPreviewError.bind(this);
   
}
componentWillMount(){
   this.getUserPreview();
}

getUserPreview(){
  var request = {
                method:'GetCommunityMembers',
                onSuccess:this.getUserPreviewSuccess,
                onError:this.getUserPreviewError,
                input: { uid: this.props.data.id, cid: activeComId},
             };
  api._post(request) ; //this function works fine as I have used it in other service calls too
}
getUserPreviewSuccess(response){
  console.log('-------UserPreviewContainer123 response returned--------');
  console.log(response);
  console.log('-------UserPreviewContainer123 response returned--------');
  this.setState({userPreview:response})
  return false;
  
}
getUserPreviewError(error){
    console.log(error);
}

render(){
   console.log('-------UserPreviewContainer123 response returned--------');
  console.log(this.props.data);
  return (
        <UserPreview userDetails={this.state.userPreview}/>
      );
 }
}
const mapDispatchToProps = (dispatch) => {
  return {
  }
};

const mapStateToProps = (state) => {
   return {
       store:state,
     
   };
};
module.exports =  connect(mapStateToProps, mapDispatchToProps)(UserPreviewContainer);

my component : 

class UserPreview extends React.Component{
				 constructor(props){
				  super();
				     this.state = { 
                    isLoading:'false', 
                   
                    };

 				}

 				 componentWillReceiveProps(nextProps) {
         
				   }
				   shouldComponentUpdate(nextProps, nextState){
				       return (this.props.userDetails !== nextProps.userDetails)?true:false;
				   }

				   componentWillUpdate(nextProps, nextState){

				   }
				   componentDidUpdate(prevProps, prevState){

				   }
				 onBackPressed() {
				 	this.props.navigator.pop({Name:'UserPreview'})
				 }

				render(){

					console.log('1213124343534');
					console.log(this.props.userDetails);

					return(
							<View //full page container
							style={{flex:1, width:deviceWidth,height:deviceHeight}}>
							
							<View  // header
							style={{flex:1,flexDirection:'row',alignItems:'center',backgroundColor:'#00A55B'}}>

									<View
									style={{flex:2,}}>
									  <TouchableHighlight
							 			style={{flex:1,justifyContent:'center',alignItems:'center'}}
							 			onPress={this.onBackPressed.bind(this)}>
										<Image 
							 			style={styles.headerImage}
							 			source={require('./images/back-arrow.png')}/>
							 		  </TouchableHighlight>
									</View>

							<View
							style={{flex:10,justifyContent:'center',alignItems:'center'}}>

								<Text style={{color:'white',
								 			fontWeight:'700',
								 			fontSize:16,
								 			textAlign:'center'}}> </Text>

							</View>

							 <View 
			    		style={{flex:2,justifyContent:'center',alignItems:'center'}}>
			    		<TouchableHighlight
			    		underlayColor='gray'
			    		onPress={this.press}>
			    		<Image
			    		style={{height:20,width:20,resizeMode:'contain',}}
			    		source={require('./images/icon-more-white.png')}/>
			    		</TouchableHighlight>
			    	</View>

							</View>  
		
					<View 
					style={{flex:7,}}>

					<View
					style={{flex:5,backgroundColor:'#E0E0E0'}}>

							<View
							style={{flex:5,paddingLeft:10,paddingRight:10,}}>  

									<View
									style={{flex:9,flexDirection:'row'}}>

									<View style={{flex:1}}></View>
									<View
									style={{flex:4,justifyContent:'flex-end',alignItems:'center',paddingBottom:10}}>
									   <Image 
							 			style={{height:150,width:150,resizeMode:'contain'}}
							 			source={require('./images/no-image.png')}/>
							 		</View>

									<View style={{flex:1}}></View>

									</View>

									<View
									style={{flex:2,}}>
									<Text
									style={{flex:1,color:'#000000',
									 		fontWeight:'400',
									 		fontSize:18,
									 		textAlign:'center' }}>rajat </Text>
									</View>

								

							</View>

							<View
							   style={{flex:2,paddingLeft:10,paddingRight:10,}}>
							   <View
								  style={{flex:12,paddingLeft:10,paddingRight:10,paddingBottom:10,justifyContent:'center',alignItems:'center',flexDirection:'row'}}>
									

									 <View
									    style={{flex:1}}>
										<TouchableHighlight
											 underlayColor='gray'
											 onPress={this.press}
											 style={[styles.button, {marginRight:2}]}>
											<View style={{flex:1,flexDirection:'row',alignItems:'center',justifyContent:'center',}}>
											 <View 
											    style={{paddingRight:5}}>
											    <Image
										    		style={{height:20,width:20,resizeMode:'contain'}}
										    		source={require('./images/chat.png')}/>
											</View>
											 <View
											      style={{paddingLeft:5}}>
											       <Text style={styles.buttonText}>Message</Text>
											 </View>
											 </View>
										  </TouchableHighlight>
	                                </View>
                                 <View 
                                     style={{flex:1,}}>
                                           <TouchableHighlight
						 underlayColor='gray'
						onPress={this.press}
						 style={[styles.button, {marginRight:2}]}>
					<View style={{flex:1,flexDirection:'row',alignItems:'center' ,justifyContent :'center', }}>
						 <View 
						style={{paddingRight:5}}>
						  <Image
						style={{height:20,width:20,resizeMode:'contain'}}
						source={require('./images/phone-call.png')}/>
							</View>
								 <View
								 style={{paddingLeft:5}}>
								 <Text style={styles.buttonText}>Call </Text>
								</View>
									 </View>
							 </TouchableHighlight>

                                    </View>

							</View>
			    	</View>
</View>

</View>
                               <View
				style={{flex:5,justifyContent:'flex-start',alignItems:'flex-start', paddingLeft:20 ,    paddingTop:20}}>

				<Text style={{fontSize:16,color:'#000000'}}> ABOUT</Text>
				<Text style={{fontSize:15,marginTop:10}}> Developer at Dobble Pvt Ltd </Text>

				</View>
                      </View>
)
	}

-as soon we get response from our API, it starts hitting itself again and again somehow, we tried to put some console messages in componentWillMount of our container to check whether it is going there to call getUserPreview function, but it is not going there at all, so we are not getting any clue from where it starts hitting infinite time

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @rajatgupta1993 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
