### ISSUE TITLE
TextInput cannot be positioned with Flexbox

### ISSUE THREAD

**Issue by michaelAndersonCampingWorld** [facebook/react-native#9646]
### Issue Description

When flexbox is used to position children, TextInput ignores the positioning. Neither `justifyContent` nor `alignItems` seems to affect it.
### Steps to Reproduce / Code Snippets

```

'use strict';

var React = require('react-native');
var {
  AppRegistry,
  Dimensions,
  StyleSheet,
  Text,
  TextInput,
  View,
} = React;

var SampleApp = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to the React Native Playground! This is the sample iOS app.
        </Text>
        <Text style={styles.instructions}>
          Just edit and save with Cmd+S. Changed will be reflected immediately in the simulator.
        </Text>

        <TextInput style={styles.instructions} />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 28,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    borderColor: 'blue',
    borderWidth: 2,
    height: 30,
    width: Dimensions.get('window').width - 20,
  },
});

AppRegistry.registerComponent('SampleApp', () => SampleApp);
```

![screen shot 2016-08-29 at 1 58 31 pm](https://cloud.githubusercontent.com/assets/17009004/18065359/c76d03d6-6df0-11e6-90ca-6de5136f7102.png)

 [RN playground](https://rnplay.org/apps/bwTYtw) uses RN 0.24.1 but it behaves exactly as it does on my simulator with RN 0.32.
#### Expected Results

I expect the TextInput to be centered both in the flow and cross axis.
### Additional Information
- React Native version: 32
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by mu1ex** [comment]
Yup. It doesnt respond to flex box styling. A quick fix is to encapsulate the `<TextInput>` inside a `<View>` component, as the `<View>` component responds to flexbox styling.

**Comment by michaelAndersonCampingWorld** [comment]
@mu1ex I discovered that after quite a bit of frustration. Is that by design? I think it's a bug because it's supposed to support all the View props.

**Comment by Zyphrax** [comment]
I just ran into this as well. I would have expected the TextInputs to be centered.
@mut1ex thank you for the workaround

**Comment by lacker** [comment]
I would just wrap this in a View. I think the documentation is just unclear on this point - there are a few other examples where it's not clear which props actually work on a TextInput.

**Comment by shergin** [comment]
#11892

**Comment by viphsx123** [comment]
Any idea on how to resolve this problem？  inside a <View> component ？

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/textinput-cannot-be-positioned-with-flexbox-1
