### ISSUE TITLE
[Touchable] locationX of nativeEvent is relative to subview

### ISSUE THREAD

**Issue by gabro** [facebook/react-native#966]
Hi all,
I'm trying to build a simple star rating component.
I have a container `View` and several subviews (namely, the stars). The `render` function is dead simple:

```
render() {
    var stars = _.times(this.props.maxRating, i => {
      var starOn = require('image!star');
      var starOff = require('image!star-off');
      var source = this.state.rating > i ? starOn : starOff;
      return <Image key={i} source={source} style={{width: 100, height: 100}}/>;
    });
    return (
      <View
        style={styles.container}
        onStartShouldSetResponder={e => true}
        onResponderGrant={this.handleGrant}
        onResponderRelease={() => this.setState({ active: false })}
        onResponderMove={this.handleMove}>
        {stars}
      </View>
    );
  }
```

I need to determine the touch location relative to the container `View`, and this is my attempt

```
  handleGrant(e) {
    ...
    var x = e.nativeEvent.locationX;
    ...
  }
```

Surprisingly, the value I retrieve is relative to the subview (i.e. the single star) as opposed to the container view, which seems to contradict the [documentation](https://facebook.github.io/react-native/docs/gesture-responder-system.html#responder-lifecycle):

> locationX - The X position of the touch, relative to the element

What I'm I doing wrong here?

**Comment by gabro** [comment]
Actually, I noticed the `locationX` is correct given the target.
If inside `handleGrant` I log `this.getNativeNode()`, I get `2`, while `e.target` is a number between 3 and 7 (i.e. the subviews)

**Comment by brentvatne** [comment]
Seems like this is resolved :smile:

**Comment by gabro** [comment]
@brentvatne are you sure? I just tested it on my star-rating project and I can reproduce the exact same behavior.

**Comment by brentvatne** [comment]
Oh sorry @gabro - I thought from your follow up comment that you had resolved it.

**Comment by gabro** [comment]
Sorry, ambiguous comment. What I meant is that the location is correct given the target, but the target is wrong, as it's one of the subviews instead of the view.

**Comment by brentvatne** [comment]
cc @spicyj

**Comment by spicyj** [comment]
I think this is working as intended. The events come in the same no matter where the listener is, so there's no way this could give the location relative to your container. You probably want to measure the container's position and then subtract that from pageX and pageY.
