### ISSUE TITLE
Cannot make whole TouchableNativeFeedback component clickable

### ISSUE THREAD

**Issue by Henny777** [facebook/react-native#9661]
I am trying to make a slider menu in Android. Therefor I made TouchableNativeFeedback with a View parent and Icon and text children wrapped in. Problem is the whole component isn´t clickable. Only the first 10% from the left hand side is clickable.

I have tried deleting all styling and switch to TouchableOpacity, TouchableWithoutFeedback and TouchableHighlight, but problem still remains.

import React from 'react'

import {View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Platform
} from "react-native";

var DrawerMenuItem = React.createClass({

  propTypes: {
    onClick: React.PropTypes.func,
    text: React.PropTypes.string.isRequired,
    iconName: React.PropTypes.string.isRequired
  },

  render: function() {
      return(
        <TouchableNativeFeedback onPress={this.props.onClick} style={[styles.menuitem, {borderWidth: 1, borderColor: colors.blue}]}>
    <View>
            <Icon
              name={this.props.iconName}
              size={24}
              color={colors.lightBlack}
              />
            <Text>{this.props.text}</Text>
   </View>
        </TouchableNativeFeedback>
      )
  }

});

module.exports = DrawerMenuItem;

And in DrawerContent.js:

import React from 'react'
import DrawerMenuItem from './DrawerMenuItem'
import {View,
  Text,
  StyleSheet,
  TouchableOpacity,
  TouchableNativeFeedback,
  BackAndroid,
  ScrollView,
  Image,
  Platform
} from "react-native";

var DrawerContent = React.createClass({

  propTypes: {
    onClick: React.PropTypes.func,
    resetStack: React.PropTypes.func,
    closeDrawer: React.PropTypes.func,
  },

  _onPress: function(viewToShow){
    this.props.onClick(viewToShow);
    this.props.closeDrawer();
  },

 render: function() {
      return (

        <View>
          <View>
            <View style={{flex: 1, flexDirection: 'column', justifyContent: 'flex-end'}}>
              <Text>{reduxStore.getState().user.name}</Text>
              </View>
              <Image resizeMode='cover' source={require('../../resources/images/rf_logo_vit.png')}></Image>
        </View>
        <ScrollView showsVerticalScrollIndicator={false} style={styles.menu}>
          <View>
            <DrawerMenuItem onClick={() => {this._onPress('##')}} iconName='line-chart' text={'###'}/>
            <DrawerMenuItem onClick={() => {this._onPress('##')}} iconName='bar-chart' text={'###'}/>
            <DrawerMenuItem onClick={() => {this._onPress('##')}} iconName='bullseye' text={Localize('###')}/>
            <DrawerMenuItem onClick={() => {this._onPress('##')}} iconName='phone' text={Localize('###')}/>
            <DrawerMenuItem onClick={() => {this._onPress('##')}} iconName='file-text' text={Localize('###')}/>

          </View>
          </ScrollView>
        </View>

      );
    }
});

DrawerContent is the slider menu and its working. But only the first 10% of the component is clickable. I wish to make the whole component clickable. I mean everything inside TouchableNativeFeedback. Right now it only half of the Icon.

* React Native version: 0.31.0
* Platform(s) Android (also same problem in IOS)
* Operating System: macOS

**Comment by DanielMSchmidt** [comment]
@facebook-github-bot stack-overflow

**Comment by facebook-github-bot-9** [comment]
Hey @Henny777 and thanks for posting this! @DanielMSchmidt tells me this issue looks like a question that would be best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). StackOverflow is amazing for Q&A: it has a reputation system, voting, the ability to mark a question as answered. Because of the reputation system it is likely the community will see and answer your question there. This also helps us use the GitHub bug tracker for bugs only. Will close this as this is really a question that should be asked on SO.
