### ISSUE TITLE
Parse import doesn't work properly on 0.32.0

### ISSUE THREAD

**Issue by didierfranc** [facebook/react-native#9671]
### Issue Description

Parse import doesn't work with react-native 0.32.0, well working on 0.31.0

#### 0.31.0
<img width="752" alt="capture d ecran 2016-08-30 a 23 53 05" src="https://cloud.githubusercontent.com/assets/14132464/18108559/10b75db2-6f0d-11e6-9a57-674ca64029d4.png">

#### 0.32.0
<img width="756" alt="capture d ecran 2016-08-30 a 23 57 23" src="https://cloud.githubusercontent.com/assets/14132464/18108661/87227766-6f0d-11e6-8cbc-fe61da8c8aef.png">

### Steps to Reproduce / Code Snippets

````
var Parse = require(parse/react-native)
````
#### Expected Results

The same behavior on 0.31 and 0.32

### Additional Information

* React Native version: 0.32.0
* Platform(s) (iOS, Android, or both?): iOS probably both
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by callmephilip** [comment]
Seeing this issue as well. Any word on possible resolution/source of problem?

**Comment by callmephilip** [comment]
reproduced here: https://github.com/bakery/parse-react-native-32

**Comment by didierfranc** [comment]
Ugly solution is [here](https://github.com/ParsePlatform/Parse-SDK-JS/issues/342#issuecomment-243890242) ...

**Comment by callmephilip** [comment]
Any updates on this? I have been trying to hunt down the source of this issue but without much luck - I did however notice that RN's packager does not seem to have a module id for "react-native" when called through their patched [require](https://github.com/facebook/react-native/blob/master/packager/react-packager/src/Resolver/polyfills/require.js#L43) function, instead it passes the string literal "react-native" (and not a module id integer)

**Comment by robtaireeo** [comment]
@didierfranc does this solution work for release builds as well ?

**Comment by didierfranc** [comment]
Fixed by this [merge](https://github.com/ParsePlatform/Parse-SDK-JS/commit/2956decbe54f2cf6d2c17ff1b4d8db98327410d6) I close.

cc @robtaireeo  @callmephilip
