### ISSUE TITLE
`resizeMode: 'cover'` is Applied Differently to Local Image than Remote Image

### ISSUE THREAD

**Issue by kevinvangelder** [facebook/react-native#9674]
### Issue Description

Given a local and a remote image with the same dimensions, `resizeMode: 'cover'` does not scale down the local image when placed inside a wrapper view that is smaller than the image, but does correctly scale down the remote image.
### Steps to Reproduce / Code Snippets

Minimal Replication App: https://github.com/kevinvangelder/imageTest
- Alternate between the local image (line 23) and the remote image (line 24) of index.ios.js
#### Expected Results

The local image should be scaled down so that one of the two dimensions fit the wrapper view, just like with the remote image.
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): iOS (unsure if Android has the same issue or not)
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by skellock** [comment]
Using `{ width: null, height: null }` fixes this.  

Sounds like one must explicitly opt out of autosizing when the loading local images into an `Image` whose size is governed by the parent (by flex or position:absolute).

The docs do talk about sizing topics.  They say dimesions are automatically applied. Which probably what is happening here.  This scenario does feel a bit like a rough edge though.

@kevinvangelder perhaps update the docs to mention this opt-out scenario?

**Comment by sidgwick** [comment]
@skellock Thanks, it works for me.

**Comment by satya164** [comment]
Yeah, if someone could send a PR to update the docs, it'll be awesome.

**Comment by sandeepskak** [comment]
@satya164 @skellock looks like this is already in the docs [here](https://facebook.github.io/react-native/docs/images.html): 
```
Note that image sources required this way include size (width, height) info for the Image. If you need to scale the image dynamically (i.e. via flex), you may need to manually set { width: undefined, height: undefined } on the style attribute.
```

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
