### ISSUE TITLE
shadowView super (of ID 415) not found

### ISSUE THREAD

**Issue by RocWangv** [facebook/react-native#9676]
### Issue Description

ExceptionsManager.js:76 Exception 'shadowView super (of ID 415) not found' was thrown while invoking replaceExistingNonRootView on target RCTUIManager with params (
    415,
    427
)

### Steps to Reproduce / Code Snippets

    _renderTabView() {
        const {sorts, loadingSort} = this.props;
        let content;
        if (sorts.length > 0 && !loadingSort) {
            content = <ScrollableTabView
                style={styles.category}
                initialPage={0}
                renderTabBar={()=><ScrollableTabBar style={{borderWidth: 0}} inactiveTextColor='#fff'/>}>
                {sorts.map((sort)=>this._renderTab(sort))}
            </ScrollableTabView>
        }
        return content;
    }

    _renderTab(sort) {
        const {merchants, isRefreshing} = this.props;
        const dataSource = this.state.dataSource.cloneWithRows(merchants[sort.sortid] === undefined ? [] : merchants[sort.sortid]);
        return <View key={sort.sortid} tabLabel={sort.sortname}>
            <YYListView
                dataSource={dataSource}
                renderRow={this._renderRow.bind(this) }
            />
        </View>;
    }`

     _renderRow(row) {
            <View>......</View>
        }

    export default class YYListView extends Component {
        // 构造
        constructor(props) {
            super(props);
        }

    render() {
        const {dataSource, renderRow, onEndReached, renderFooter, refreshing, onRefresh} = this.props;
        let view;
        if(!refreshing && dataSource.getRowCount() === 0){
            view = <Status titleIcon={require('../../image/no-data.png')}/>;
        }else{
            view = <ListView
                dataSource={dataSource}
                renderRow={renderRow}
                enableEmptySections={true}
                onEndReached={onEndReached}
                onEndReachedThreshold={0}
                renderFooter={renderFooter}
                refreshControl={
              <RefreshControl
                refreshing={refreshing}
                onRefresh={onRefresh}
                tintColor="#ffffff"
                title="加载中..."
                titleColor="#ffffff"
                main="#ffffff"
                progressBackgroundColor="#ffffff"
                />}
            />
        }
        return (view)
    }
    }
    YYListView.propTypes = {
        dataSource: PropTypes.any.isRequired,
        renderRow:  PropTypes.func.isRequired,
        refreshing: PropTypes.bool.isRequired,
        onEndReached: PropTypes.func,
        renderFooter: PropTypes.func,
        onRefresh: PropTypes.func
    }'

### Additional Information

* React Native version: 
    "react": "15.2.1",
    "react-native": "0.31.0",
* Platform(s) (iOS, Android, or both?): IOS , and not run is Android yet.
* Operating System (macOS, Linux, or Windows?): MACOS

**Comment by RocWangv** [comment]
I forgot a `return` in [_renderRow] ....

**Comment by tomazahlin** [comment]
I also have this problem and my code looks fine. These error messages are really horrible!

**Comment by bski006** [comment]
had same problem
        <ScrollView
          horizontal={true}>
          {media.map ((elem)=> (
            <View key={`${id}`}>...</View>
          ))}
        </ScrollView>

turns out id's definition was missing...

**Comment by kkamperschroer** [comment]
I just ran into this same error when I had an exception being thrown in my `mapStateToProps`. So just one more place to look for anyone else encountering this.

**Comment by gritzko** [comment]
@kkamperschroer thank you

**Comment by gritzko** [comment]
I've got this after I eslint'ed the entire project, by the way.
So many possibilities...

**Comment by lukecwilliams** [comment]
Strangely I can repro this by adding a double-slash comment in between two rendered React Native items.  Changing the comment to correct style `{/* My comment */}` fixes the issue.

Seems like a fairly strange error message for this issue!  The linter also does not pick this up.

```
<Text>...</Text>
// Invalid comment style
<Text>...</Text>
```

Full error message:
```
Exception 'shadowView super (of ID 46) not found' was thrown while invoking replaceExistingNonViewRoot on target UIManager with params (
  46,
  120
)

RCTFatal
```

**Comment by brzezinskip** [comment]
I have the exact same isssue

> Exception 'shadowView super (of ID 46) not found' was thrown while invoking replaceExistingNonViewRoot on target UIManager with params (
49,
56
)
RCTFatal

But I don't have any comments between the components in my code. It started to happen after upgrading to (0.46.4), it's pretty tough to track down where it comes from.

**Comment by lukecwilliams** [comment]
I've seen this today when trying to implement Native Base Picker as well, without any bogus comments.

React Native may be showing this error message in a variety of cases now, which seems like a bug.

**Comment by brzezinskip** [comment]
Update:
It appears that this error was shown to me because of react-navigation update. There were some breaking changes in there and I had to update my codebase to fix them, after that, there was no more shadowView error.

**Comment by lukecwilliams** [comment]
@brzezinskip Can you provide a few details?  We're using react-navigation as well.

**Comment by brzezinskip** [comment]
@lukecwilliams We were using such syntax for navigationOptions:
```typescript
    public static navigationOptions = {
        header: {
            visible: false,
        },
    };
```
which has been changed to
```typescript
    public static navigationOptions = {
        header: null,
    };
```
and

```typescript
    public static navigationOptions = {
        title: ({ state }) => state.params.title,
        header: {
            visible: false,
        },
    };
```
which has been changed to
```typescript
    public static navigationOptions =
        ({ navigation }) => ({
            title: navigation.state.params.title,
            header: null,
        })
```
might not be the case for you though.

**Comment by lukecwilliams** [comment]
@brzezinskip Not our case, but thanks for pointing those out.
