### ISSUE TITLE
Run shell script failed when I use Xcode to build project with release deployment.

### ISSUE THREAD

**Issue by niyaoyao** [facebook/react-native#9677]
### Issue Description

The log of error when build project looks like below.
- node /Users/niyao/Company/Projects/EVE/EVERN/node_modules/react-native/local-cli/cli.js bundle --entry-file index.ios.js --platform ios --dev false --reset-cache --bundle-output /Users/niyao/Library/Developer/Xcode/DerivedData/EVE-bzggtbnrxixkvwgqyewmpxepvljo/Build/Products/Release-iphonesimulator/EVE.app/main.jsbundle --assets-dest /Users/niyao/Library/Developer/Xcode/DerivedData/EVE-bzggtbnrxixkvwgqyewmpxepvljo/Build/Products/Release-iphonesimulator/EVE.app

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);

Error: ENOENT: no such file or directory, open 'package.json'
### Error Scenario

After I use package.json as below to `npm install` new version, the error happens within release deployment scheme.

```
{
  "name": "NYProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "lint": "./node_modules/eslint/bin/eslint.js index.ios.js index.android.js react/",
    "watch": "npm-watch"
  },
  "watch": {
    "lint": {
      "patterns": [
        "react",
        "index.ios.js",
        "index.android.js"
      ],
      "extensions": "js",
      "ignore": ".node_modules",
      "quiet": false
    }
  },
  "dependencies": {
    "react": "15.3.1",
    "react-native": "^0.32.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "eslint": "^3.3.1",
    "eslint-plugin-react": "^6.1.2",
    "eslint-plugin-react-native": "^2.0.0",
    "npm-watch": "^0.1.6"
  }
}
```

The shell runs failed when build project within **_Release**_ build configuration.

```
"./NYProject/node_modules/react-native/packager/react-native-xcode.sh"
```
#### Expected Results

Xcode could run shell when build the project. Before I upgrade the package.json configuration, it did run successfully.
### Additional Information
- React Native version: 
  react-native-cli: 0.2.0
  react-native: 0.32.0
- Platform(s) (iOS, Android, or both?): 
  Xcode 7.3.1 iOS 
- Operating System (macOS, Linux, or Windows?): 
  OS X 10.11

**Comment by chetstone** [comment]
Did you get this error after upgrading react-native to 0.32?

I wonder if it has something to do with the fact that your project is named NYProject but your app is EVE.app? Maybe the bundler is assuming that they have the same name? 

I'm seeing the same error (in Release only) and have a similar naming situation (because, history).

I noticed when running `react-native upgrade` that in many places in my pbxprj file where the name of my project is encoded they are now using a template `<%= name>`. I didn't accept the changes. I don't know when this change came about, I just upgraded from RN 0.24 to RN 0.32.

**Comment by chetstone** [comment]
On further investigation, this error happens in line 20 of `react-native/local-cli/android/android.js`
(in an `iOS` build !!!). The bundle command is running in the ios subdirectory and for some reason is looking for a package.json in that directory.

Super-funky workaround: I added the following `package.json` file int the `ios` subdirectory:

```
{
    "name": "foobar"
}
```
wtf?

**Comment by niyaoyao** [comment]
@chetstone Yes, after upgrading react-native to 0.32 , the error happens.

Actually, the ```NYProject``` of key ```name``` has nothing to do with iOS project. It's just a react module name to create react view.

I think the most probably reason cause the error is JavaScript dependence library named 'fs.js'. But, I'm not sure.

**Comment by habovh** [comment]
I'm having the same issue on RN 0.34.1.
Were you guys able to sort it out?

**Comment by caabernathy** [comment]
I saw the same issue. A fix was to modify node_modules/react-native/packager/react-native-xcode.sh

    # Xcode project file for React Native apps is located in ios/ subfolder
    #cd ..
    cd ${REACT_NATIVE_DIR}/../..

This fix https://github.com/facebook/react-native/pull/9525 appears to have triggered the issue. In my case I saw this because I have a non-standard set up from the one you see when running react-native init.

**Comment by habovh** [comment]
You're right @caabernathy, I was able to sort it out by making the same changes as I neither don't have a standard "template" project.
Removed the `cd ..` line and adjusted the location of the `node_modules`'s `react-native` folder.

**Comment by niyaoyao** [comment]
I solve this problem with package.json as below
`
{
  "name": "<Product Name>",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "lint": "node node_modules/eslint/bin/eslint.js index.ios.js index.android.js react/",
    "watch": "npm-watch"
  },
  "watch": {
    "lint": {
      "patterns": [
        "react",
        "index.ios.js",
        "index.android.js"
      ],
      "extensions": "js",
      "ignore": ".node_modules",
      "quiet": false
    }
  },
  "dependencies": {
    "eslint": "^3.5.0",
    "eslint-plugin-react": "^6.2.2",
    "react": "15.3.1",
    "react-native": "^0.33.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-eslint": "^6.1.2",
    "eslint": "^3.3.1",
    "eslint-plugin-react": "^6.1.2",
    "eslint-plugin-react-native": "^2.0.0",
    "npm-watch": "^0.1.6"
  }
}
`

**Comment by plevavas** [comment]
I'm agree with @caabernathy. In the file react-native/local-cli/android/android.js, the default function try to read a package.json file. But when i run the script with XCode, the current directory is the subdirectory 'ios'. There isn't package.json file in this directory.

The code below fix the issue for me, but i think it's not the best solution. Another solution is to add a empty package.json file in the ios directory.

```js
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */
'use strict';

var generate = require('../generate/generate');
var fs = require('fs');

function android(argv, config, args) {
  console.log("TEST");
  return generate([
    '--platform', 'android',
    '--project-path', process.cwd(),
    '--project-name', args.projectName,
  ], config);
}

module.exports = {
  name: 'android',
  description: 'creates an empty android project',
  func: android,
  options: [{
    command: '--project-name [name]',
    default: () => {
      try {
        fs.accessSync('package.json', fs.F_OK);
        return JSON.parse(
          fs.readFileSync('package.json', 'utf8')
        ).name;
      } catch (e) {
        console.log('package.json doesn\'t exists in this directory : ' + process.cwd());
      }
    },
  }],
};
```

**Comment by lacker** [comment]
It sounds like there are workarounds for this so I am going to close this issue. Thanks folks for bringing this up and sharing solutions!
