### ISSUE TITLE
why do you focus on Objective-C instead of Swift 

### ISSUE THREAD

**Issue by muhasturk** [facebook/react-native#968]
When I open my react-native project in Xcode, there are lots of Objective-C code instead of Siwft. Just wondering why? Is there any detailed documentation about this subject?

**Comment by nicklockwood** [comment]
There's a discussion of the reasons in this thread:

**Comment by nicklockwood** [comment]
TL;DR;

* React Native was already in an advanced stage of development before Swift was announced
* Swift is still changing frequently, and the tools are very unstable and slow for large projects
* The dynamic binding and macro tricks we are using would be difficult to implement in Swift

**Comment by muhasturk** [comment]
Thank you for reply.

**Comment by brentvatne** [comment]
:smile:
