### ISSUE TITLE
It is not possible anymore to hot reload or debug on a real device

### ISSUE THREAD

**Issue by maluramichael** [facebook/react-native#9688]
### Issue Description

I want to debug an app on my iPhone but when i press the 'Debug JS Remotely' it crashes with the error '' and the button 'Hot Reload' is not even visible.

It seems like the packager is building always a pre built bundle of the app. There is no 'loading from xy' message at the top anymore and the build phase 'Bundle React Native code and images' inside Xcode takes really long.
### Code Snippets

_AppDelegate.m_

```
/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import <Fabric/Fabric.h>
#import <Crashlytics/Crashlytics.h>

#import "AppDelegate.h"

#import "RCTBundleURLProvider.h"
#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    [Fabric with:@[[Crashlytics class]]];

    NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"Watchlist"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    UIViewController *rootViewController = [[UIViewController alloc] init];
    rootViewController.view = rootView;
    self.window.rootViewController = rootViewController;
    [self.window makeKeyAndVisible];
    return YES;
}

@end

```
#### Expected Results

Debug with Google Chrome and use the hot reload feature.
### Additional Information
- React Native version: 0.31.0 and 0.32.0
- Platform: iOS
- Operating System: osx 10.11.6

**Comment by cpsiaki** [comment]
Did you find out what was happening here?

**Comment by maluramichael** [comment]
Unfortunately no

**Comment by maluramichael** [comment]
I testet this with a fresh 0.32.0 project.

```react-native init Test```

On a real device it is still showing 'Loading from pre bundled file'

**Comment by maluramichael** [comment]
Now i commented this line and started the packager via the terminal with `npm start`. Simulator is showing `loading from localhost:8081` and the device `loading from pre bundled file`
![screen shot 2016-09-05 at 22 20 27](https://cloud.githubusercontent.com/assets/1489383/18256552/18d0c4c6-73b7-11e6-9926-80281c72fec8.png)

**Comment by af7** [comment]
+1 This is serious, I have lost ours trying to figure out what I may be doing wrong (since I upgraded from v0.21 to v0.32 and could not be sure if I did something wrong). Eventually, I verify that I experience the same bug, which hinders development.

**Comment by cpsiaki** [comment]
Hey guys, this fixed it for me:

https://github.com/facebook/react-native/issues/8737

this answer:

Ok, the answer is to have this in your AppDelegate.m:
```
  #ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.64:8081/index.ios.bundle?platform=ios&dev=true"];
  #else
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
  #endif
```
And this in your Info.plist:
```
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
</dict>
```

**Comment by af7** [comment]
@cpsiaki Thanks, the format here is wrong, how should I place them?

<key>NSAppTransportSecurity</key>
	<dict>
      <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>

**Comment by cpsiaki** [comment]
Just completely remove:

```
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>localhost</key>
            <dict>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**Comment by cpsiaki** [comment]
I didn't try putting the 
```
<key>NSExceptionDomains</key>
        <dict>
            <key>localhost</key>
            <dict>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
```
Inside one level of <dict> (combining the two), looking at it now, it seems like it might work, but I'm not going to do that right now. I removed that bottom part completely and it worked so I just kept it that way. Maybe I'll try the other thing later.

**Comment by af7** [comment]
FYI, I did the following that keeps the other key too and it worked.

Many thanks! 
I spent hours* with frustration on this matter as no documentation could help.

```
<key>NSAppTransportSecurity</key>
	<dict>
	    <key>NSAllowsArbitraryLoads</key>
        <true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
```

**Comment by maluramichael** [comment]
Could it be possible that it has something to do with my network? At work everything is fine. I can debug, hot reload etc. At home i push the app to my device and it stuck at the launch screen for some seconds and then loads the pre build version.

**Comment by maluramichael** [comment]
Here is an update of my situation after many restarts, starting charles, wireshark, restart my network etc.

### My app on the phone is just showing this for a couple of minutes
![iphone](https://cloud.githubusercontent.com/assets/1489383/18327520/38a42d66-754b-11e6-8089-3389a9d416bf.jpg)

### The debugger crashed
<img width="1669" alt="reactnativedebugger" src="https://cloud.githubusercontent.com/assets/1489383/18327519/38a1b72a-754b-11e6-82c4-c89f30427a7f.png">

### Terminal showing me that something loaded
<img width="827" alt="terminal" src="https://cloud.githubusercontent.com/assets/1489383/18327521/38a50bb4-754b-11e6-9689-f5a45f49ca67.png">

### And wireshark says everything responded
<img width="1028" alt="wireshark" src="https://cloud.githubusercontent.com/assets/1489383/18327522/38a64c68-754b-11e6-8a0b-7f2728183cae.png">

**Comment by gwendall** [comment]
Same here.

**Comment by gwendall** [comment]
Happened after upgrading to RN 0.33 (from 0.25).

**Comment by pekkanikolaus** [comment]
Same problem here, with an iPad Pro on iOS 9 and XCode 8.0 Beta 3.

- The menu doesn’t have the hot reload button
- The packager is reachable from the iPad (I can open x.x.x.x:8081 in the browser and get „React Native packager is running"
- Tried the info.plist change above, but when I do it XCode complains about info.plist being in an incorrect format

Not sure what to do here.

**Comment by philipstanislaus** [comment]
Fixed it with the following entry in `./ios/App/info.plist` (Xcode 8.1, react-native 0.37.0): 

```
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>192.168.0.127</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
        <key>localhost</key>
        <dict>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>
```

**Comment by j-wang** [comment]
I experienced the same problems with similar setups to everyone. I prefer NOT to hardcode or revert back to the old way (< RN 0.29) since that then takes away all the work that went into making the device load from the development server (when available) and prebundled (when not)... and also having the correct settings for you go into release.

Strangely, my problem got solved by simply removing `.xip.io` from line 83 in react-native-xcode.sh.

https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh

If you look at the script, which is run every time you build, it already handles putting exceptions into the .plist file when in debug.

**Comment by RobTS** [comment]
Experienced this as well now, was a pretty frustrating day. RN 0.43.3, iOS, not even moving the code to a new project seemed to fix it. the solution above from @j-wang solved it for me.

**Comment by jkimbo** [comment]
@robts my pr (https://github.com/facebook/react-native/pull/13326) got merged recently so I'm guessing it will be included in the next release

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/it-is-not-possible-anymore-to-hot-reload-or-debug-on-a-real-device

**Comment by praveenkumarc86** [comment]
@hramos Still an issue in RN v0.54.4
