### ISSUE TITLE
ProgressBarAndroid deprecated PropTypes validation

### ISSUE THREAD

**Issue by gogamwar** [facebook/react-native#9692]
### Issue Description

When using the ProgressBarAndroid I get a warning with the following text:

> Warning: You are manually calling a React.PropTypes validation function for the `indeterminate` prop on `AndroidProgressBar`. This is deprecated and will not work in the next major version. ...

![RN ProgressBarAndroid bug](https://cloud.githubusercontent.com/assets/13474134/18144158/db091586-6fcd-11e6-877e-54cbb8a6cd81.png)

### Steps to Reproduce / Code Snippets

just `return <ProgressBarAndroid style={{ flex: 1 }} />` in render method

### Additional Information

* React Native version: 0.32.0
* React version: 15.3.1
* Platform(s): Android 6.0.1
* Operating System: Ubuntu 16.04

**Comment by gogamwar** [comment]
Switched to using `ActivityIndicator`

**Comment by martinezguillaume** [comment]
Oh my god, I completely forgot the new ActivityIndicator component.... Thanks

**Comment by vovkasm** [comment]
`0.40.0-rc.2` still have the issue... Sad (

**Comment by faysalsoufiiane** [comment]
i solved it with this solution
[stackoverflow](https://stackoverflow.com/questions/42707846/rn-progressbarandroid-manually-calling-react-proptypes-for-the-indeterminate)
