### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by feng003** [facebook/react-native#9695]
My frist install the android studio in the windows 7.
The config of SDK Platforms , I chooice Android 6.0 (Marshmallow) that  contains Google APIs、Intel x86 Atom System Image、Intel x86 Atom_64 System Image and Google APIs Intel x86 Atom_64 System Image,and SDK Tools that contains Android SDK Build-Tools 23.0.1 and Android SDK Build-Tools 23.0.3.

$ react-native run-android
Starting JS server...
Running F:\Android\sdk/platform-tools/adb reverse tcp:8081 tcp:8081
error: no devices/emulators found
Could not run adb reverse: Command failed: F:\Android\sdk/platform-tools/adb re
erse tcp:8081 tcp:8081
Building and installing the app on the device (cd android && gradlew.bat instal
Debug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0320Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:processDebugResources'.
  
  > at index 4
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED
- Platform(s) :Android
- Operating System:Windows7_64

**Comment by neverlous** [comment]
I meet this problem as you, which when I use Genymotion. But when I change another virtual device, it passed. You may try.

**Comment by feng003** [comment]
which virtual device ? Now I do not use  Genymotion, and only install android studio.

**Comment by sunnylqm** [comment]
You need to open sdk manager and **reinstall** sdk build tools.

**Comment by ccgitgit** [comment]
I solved the same problem by installing "Android SDK Platform 23" and "Soures for Android 23" under Android 6.0 (Marshmallow)

**Comment by ericnakagawa** [comment]
Hi @feng003, looks like @ccgitgit 's solution offers a fix or workaround for this issue.

**Comment by maromdahari** [comment]
had the same issue. 
packager could not close AndroidManifest file which was open.
Closed it on editor and it worked.

**Comment by MauroNavaLuevanos** [comment]
I solve it uninstalling Android SDK Tools from Android Studio, after in the cmd I run the app, automatically the Android SDK Tools `` will be installed and the app works

**Comment by SajidAli65** [comment]
**I solve this issue.**

E:\AndroidData\mobile-app\AwesomeProject\android\app\build

remove the all files in build folder and run the app, the app work properly

**Comment by Adcrazynoga** [comment]
Thanks SajidAli65. Last thing I try. It work ")
