### ISSUE TITLE
[TouchableHighlight] Automatically forward setNativeProps to the root subcomponent

### ISSUE THREAD

**Issue by ide** [facebook/react-native#97]
TouchableHighlight calls setNativeProps on its child, which is automatically handled by native views but not user-level composite components. In the examples I can think of off the top of my head, you'd typically want a composite component to forward setNativeProps to its root subcomponent i.e. the implementation looks like:

```javascript
setNativeProps(nativeProps) {
  this.refs['root'].setNativeProps(nativeProps);
}
render() {
  return <Subcomponent ref="root">...</Subcomponent>;
  // If Subcomponent is composite, it will recursively forward setNativeProps
}
```

I propose this to be the default implementation if a component does not implement setNativeProps. This retains flexibility while I believe behaving reasonably in the default case.

**Comment by brentvatne** [comment]
This seems useful!

**Comment by ide** [comment]
Feels like this would result in a change to React since the component renderer would need to hook up each owner's setNativeProps to the root it owns. Perhaps there is a less intrusive way with a mixin that we can experiment with and then make the change to React once we understand the space better. I think there is something useful here with automatic proxying between the owner and its root, like making onLayout work for composite components as well.

**Comment by brentvatne** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out it's new home: https://productpains.com/post/react-native/touchablehighlight-automatically-forward-setnativeprops-to-the-root-subcomponent
