### ISSUE TITLE
ScrollView fires "onLayout" and "onContentSizeChange" all the time

### ISSUE THREAD

**Issue by fab1an** [facebook/react-native#9702]
ScrollView fires `onLayout` and `onContentSizeChange` all the time upon scrolling, even if the values haven't changed.

RN 0.32

**Comment by rigdern** [comment]
@fab1an what platform are you seeing this on? I'm seeing a similar bug on Android on `v0.32.0-rc.0`.

**Comment by edmofro** [comment]
Also getting this, Android, ```v0.32.0-rc.0```

**Comment by lacker** [comment]
I think this issue is lacking enough information to reproduce, so I am going to close it. If you are still working on this then please feel free to open a new issue! Especially helpful would be a sample app on rnplay.org that can reproduce this problem.
