### ISSUE TITLE
zindex proepry remove the element.

### ISSUE THREAD

**Issue by roysG** [facebook/react-native#9704]
Hi,

I have issue with zIndex.
I have button that show some overlay for post.
When i click on share button i see the overlay button, but when i click on it again the element post is remove from the screen.

In found the zindex as the bug when i tried to remove this property and everything worked well without the zIndex.

The problem is that the overlay is behind the image

**Comment by hlynn93** [comment]
#8968 ?

**Comment by roysG** [comment]
yes

**Comment by roysG** [comment]
But there is no any fix for that?

**Comment by tioback** [comment]
Not yet, but there's a workaround: 
- in Android, reduce the height and borders to 0. 
- in iOS, return null

Don't try Android's solution for iOS, as it won't work. The same for iOS's solution in Android.
