### ISSUE TITLE
require('fs')

### ISSUE THREAD

**Issue by sabeurthabti** [facebook/react-native#971]
So I am trying to read a file and then parse it into json. Anyway is fs supported? I will update this when I am home. 

thanks

**Comment by sabeurthabti** [comment]
https://github.com/sabeurthabti/react-native-css/issues/1

I am developing something for fun and I need to use FS, I will investigate more tonight. Any tips would be helpful.

**Comment by brentvatne** [comment]
I believe you will need to write a [native module](https://facebook.github.io/react-native/docs/nativemodulesios.html#content) to interact with the filesystem, a good example of this is with `AsyncStorage` - [check out the source](https://github.com/facebook/react-native/blob/master/React/Modules/RCTAsyncLocalStorage.m) - it saves and loads and parses a JSON file :smile:

**Comment by frantic** [comment]
@sabeurthabti - think of React Native more like about browser environment, not node. `fs` is nodejs module that depends on nodejs implementation and will not work on RN. @brentvatne is right, look at `AsyncStorage` :)
