### ISSUE TITLE
Minification breaks certain libraries

### ISSUE THREAD

**Issue by yogiben** [facebook/react-native#9711]
We're using a library in our Android RN app.

It works fine in dev, but breaks once minified.

Is there a way to skip minification of certain files?

**Comment by maluramichael** [comment]
Which libraries and which lines break?

**Comment by ide** [comment]
The current minifier is Uglify (may change to Babili later) so if you can figure out how to tell Uglify not to minify certain functions that would probably work for you.

**Comment by you-fail-me** [comment]
@ide Is there a way to generate a non-minified apk with react-native?

**Comment by ide** [comment]
Grep through the build process searching for `minify` and change whatever code is requesting `minify=true` in a packager URL to `minify=false`.

**Comment by yogiben** [comment]
In the end, we solved this by disabling mangling:

```
function minify(filename, code, sourceMap) {
  const minifyResult = uglify.minify(code, {
    fromString: true,
    inSourceMap: sourceMap,
    outSourceMap: true,
    mangle: false, // ADD THIS LINE
    output: {
      ascii_only: true,
      screw_ie8: true,
    },
  });
```
in `node_modules/react-native/packager/react-packager/src/JSTransformer/worker/minify.js`

We haven't found a nice way to commit this into version control yet.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/minification-breaks-certain-libraries

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by ds300** [comment]
@yogiben you might be interested in [patch-package](https://github.com/ds300/patch-package) for future situations like this. I use it to prevent mangling myself :-)

**Comment by coreh** [comment]
For future reference: As of September 2017 the file that needs to be patched (as described by @yogiben's instructions) has been moved to the `metro-bundler` module, so the path should now be:

```
node_modules/metro-bundler/src/JSTransformer/worker/minify.js
```

If you're using `patch-package` to patch it, here's **patches/metro-bundler+0.9.2.patch**:

```diff
diff --git a/node_modules/metro-bundler/src/JSTransformer/worker/minify.js b/node_modules/metro-bundler/src/JSTransformer/worker/minify.js
index 3f61ce9..4927afb 100644
--- a/node_modules/metro-bundler/src/JSTransformer/worker/minify.js
+++ b/node_modules/metro-bundler/src/JSTransformer/worker/minify.js
@@ -46,10 +46,11 @@ function minify(inputCode, inputMap) {
     fromString: true,
     inSourceMap: inputMap,
     outSourceMap: true,
+    mangle: false,
     output: UGLIFY_JS_OUTPUT_OPTIONS });
 
 }
 
 module.exports = {
   noSourceMap,
-  withSourceMap };
\ No newline at end of file
+  withSourceMap };
```

**Comment by jackylimel** [comment]
The file path mentioned here: https://github.com/facebook/react-native/issues/9711#issuecomment-327552716 is changed. It should be:

`node_modules/metro-minify-uglify/src/minify.js`
