### ISSUE TITLE
PushnotificationIOS.requestPermissions Not working If user choose "Dont Allow" first time.

### ISSUE THREAD

**Issue by rimzici** [facebook/react-native#9715]
Using RN 0.31

PushNotificationIOS.requestPermissions().then(permission => { });

working for the first time.
explaining the scenario and issue facing, 
1. When user clicks "allow" for the request my 
PushNotificationIOS.addEventListener('register', (token) => { });

listener gets called and i am able to receive token,

But if the user clicks "Dont Allow" in the promise iam receive the permission object with correct values as {alert:0,badge:0,sound:0} But this time my register event never gets fired , so no token. incase if the user turns on notification in the settings I would like to receive token again. for that i tried PushNotificationIOS.requestPermissions().then(permission => { }); but its never getting called and not able to generate token again.
so finally it seems 
PushNotificationIOS.requestPermissions().then(permission => { });
works only for the first time, second time its not opening the request popup.
Thanks in Advance

**Comment by rmevans9** [comment]
If I am understanding correctly then this is actually expected behavior for iOS. If a user denies permissions then anytime you ask for permission it simply tells your app that it has been denied without prompting the user. Otherwise it would become annoying to the end user. If the user then allows your app to have the permission (be it push or geolocation or any others) the next time you call requestPermissions it should resolve automatically with a token.

**Comment by ide** [comment]
Yeah. This is how iOS works, closing.

**Comment by rimzici** [comment]
Thanks @rmevans9  @ide : 
I have been trying to generate token , if user chooses to "Diss Allow" notification initially and afterwards if he chooses to switch it on , from to settings. 
As You said i understand it will be annoying if he app keep on throwing pop up even after user rejects.
So I could see the   PushNotificationIOS.requestPermissions().then(permission => { }); resolves the permission with out a pop up and gives the permission object.
I dont need that pop up to annoy user, Issue iam facing is.
If user disallows notification initially token registration is happening.
I dont know why , From this link [what](http://stackoverflow.com/questions/18478325/is-it-possible-to-get-the-device-token-even-if-push-notification-is-not-enabled) i could infer is ,
even if user diss allow we must receive token. if so the problem will be solved. I can use that token afterwards, when user switch on notification.
In my case since no token there i was expecting to get when user toggles the settings. But there 
if  use 
PushNotificationIOS.requestPermissions().then(permission => { }); 
it resolves internally and throws '1' as permission enabled but not able to register for push notification, so that no token.
Please tell me if I am doing something wrong.
Thank You very much.

**Comment by rimzici** [comment]
Solved the issue.
After putting my register event listener inside constructor it works. 
Sorry Team. Was my ignorance 
thank you

**Comment by joshuapinter** [comment]
Super strange but in order for `PushNotificationIOS.requestPermissions()` to resolve the `Promise`, you _need_ to add an event listener, like this: 

```js
PushNotificationIOS.addEventListener('register', (token) => {});
```

What's even more interesting is that it doesn't even have to be the `'register'` event, it could be `'notification'` or `'localNotification'` as well and they all work.

So this is what I ended up using anywhere I needed to get and handle the `requestPermissions()` Promise resolve:

```js
componentWillMount() {
  // NOTE: You absolutely need this for requestPermissions() promise to resolve.   
  PushNotificationIOS.addEventListener('register', (token) => {});
}

componentWillUnmount() {
  PushNotificationIOS.removeEventListener('register', (token) => {});
}
```

Is this expected behaviour?

**Comment by petersuwara** [comment]
@joshuapinter thank you, saved me so much time. I had the addEventListener inside the callbacks or requestPermissions and could never get any to activate. You saved me a night of no sleep. Appreciate it.

**Comment by joshuapinter** [comment]
@petersuwara Man, they still haven't fixed this yet? What version of React Native are you using?

**Comment by petersuwara** [comment]
@joshuapinter, my issue was slightly different.

Overall, I just think they haven't communicated best practices and clear examples. It is open source beta after all.

Don't understand the hype. After using it for 3 months and releasing an app. I'm going back to the safety and surety of a less painful experience with Native swift on iOS.

**Comment by joshuapinter** [comment]
@petersuwara If you do any Android development, you'll completely understand the hype of not having to code interfaces in .xml. :)

**Comment by petersuwara** [comment]
@joshuapinter, well yeah I haven't had the pleasure. But CSS JSX tags aren't too far off. :) 

The safety and comfort of Swift and iOS, if only it was a ubiquitous experience... ;)
