### ISSUE TITLE
Tab Bar is broken when In-Call Status Bar is active

### ISSUE THREAD

**Issue by soheil** [facebook/react-native#972]
![screen shot 2015-04-22 at 11 39 27 am](https://cloud.githubusercontent.com/assets/287288/7282360/651af5fe-e8e4-11e4-85e8-b0fd2743a878.png)

**Comment by brentvatne** [comment]
@soheil - as discussed in IRC, built a library for you that fixes this: https://github.com/brentvatne/react-native-status-bar-size :smile:

![height](https://cloud.githubusercontent.com/assets/90494/7289913/aa573c80-e92b-11e4-9bd7-daeaf860956f.gif)

Could add this back into `StatusBarManager` perhaps when it has all of the kinks worked out, cc @tadeuzagallo @vjeux

**Comment by soheil** [comment]
beautiful!

I also thought it'd be nice to be able to add an icon to NavigationIOS
instead of text:

so in `RCTWrapperViewController.m` I added an image if there is no text
passed (it'd be nice to add its own prop):
```
- (void)viewWillAppear:(BOOL)animated
...

    self.navigationItem.title = _navItem.title;

    if (!_navItem.title) {
      UIImage *image = [UIImage imageNamed:@"logo.png"];
      self.navigationItem.titleView = [[UIImageView alloc]
initWithImage:image];
    }
```

good job though!

**Comment by soheil** [comment]
beautiful!

I also thought it'd be nice to be able to add an icon to NavigationIOS
instead of text:

so in `RCTWrapperViewController.m` I added an image if there is no text
passed (it'd be nice to add its own prop):
```
- (void)viewWillAppear:(BOOL)animated
...

    self.navigationItem.title = _navItem.title;

    if (!_navItem.title) {
      UIImage *image = [UIImage imageNamed:@"logo.png"];
      self.navigationItem.titleView = [[UIImageView alloc]
initWithImage:image];
    }
```

good job though!

**Comment by soheil** [comment]
@brentvatne also this bug still occurs even with the StatusBar height known, I thought I could modify the height of the main view based on the StatusBar height but that didn't work. So I think we need another solution, but your StatusBar size is still a nice addition.

**Comment by brentvatne** [comment]
@soheil - you could add some negative margin when the status bar is larger to offset it

**Comment by soheil** [comment]
I haven't tried - margin, but increasing the height only worked when status
bar got bigger but when it shrunk again decreasing the height oddly enough
made no effect.
