### ISSUE TITLE
[NavigatorExperimental] Override Styles for NavigationHeader? Bottom Border

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#9721]
I have written a custom NavigationHeader component and applied my own unique styles. However, it seems some of the core react native styles are hardcoded to the component and cannot be overwritten. I.e. there is a thin border on the bottom that I can't seem to get rid of. I'm going after the effect where the header blends into the page content by having the same background color, however the line is messing up the experience.

<img width="381" alt="screen_shot_2016-09-02_at_7_30_44_pm" src="https://cloud.githubusercontent.com/assets/4974609/18220855/138442ba-7144-11e6-8420-ffa941f30dc1.png">

**Comment by ryankask** [comment]
What styles are you passing to `NavigationHeader`?

Passing something like `<NavigationHeader style={{ borderBottomWidth: 0 }} />`should work.

**Comment by joncursi** [comment]
@ryankask wow, that did the trick! Thank you!
