### ISSUE TITLE
[fetch] Failed API request breaks app

### ISSUE THREAD

**Issue by jbhatab** [facebook/react-native#973]
This is what happens when I make a failed api request. Are failed api requests supposed to break the app like this? Is there a good way to have a fallback?

![screen shot 2015-04-22 at 4 05 37 pm](https://cloud.githubusercontent.com/assets/2458718/7285368/9374e8b8-e909-11e4-8682-3f0550e8406a.png)

**Comment by burriko** [comment]
Can we see your code? I haven't had any problems catching errors from network problems so far.

Here's an example using fetch().

```javascript
fetch('http://example.com/stuff.json')
      .then(response => response.json())
      .then(json => this._handleResponse(json))
      .catch(error => {
        React.AlertIOS.alert(
          'Error',
          'There seems to be an issue connecting to the network.'
        );
      });
```

**Comment by joshbedo** [comment]
Adding a `catch` solved this issue for me, thanks! :)

**Comment by brentvatne** [comment]
This should only happen in development mode, if you can reproduce with development mode disabled, please ping me and I'll reopen this issue! @jbhatab

**Comment by udfalkso** [comment]
This is now crashing my application when building in Release mode.  I believe since updating to RN 0.13.  

I also had to change from fetch() to window.fetch() or the app crashed.  Is that related somehow?  

Anyone else?  Thanks
