### ISSUE TITLE
onFocus function doesn't be called when I press TextInput that is onFocus

### ISSUE THREAD

**Issue by endpress** [facebook/react-native#9732]
## [Android]

Sometimes keyboard hides but textInput is onFocus. How do I open keyboard again ?

I want to press the textInput to open keyboard but I can't find the function called by textInput.

**Comment by endpress** [comment]
![Uploading code.png…]()

**Comment by endpress** [comment]
<img width="545" alt="code" src="https://cloud.githubusercontent.com/assets/13311095/18236723/bc14b3e2-735b-11e6-97f9-5de1c95eb6d8.png">

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/onfocus-function-doesnt-be-called-when-i-press-textinput-that-is-onfocus

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (71/60 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43236)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660o-000NjI-0v
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:43 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660m-0004hw-M1
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:41 -0700
Date: Sun, 13 Nov 2016 17:24:39 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086680;
	bh=Fk8g1Uj5OHzaJRrYlVK4mJ/iEXbKf8A4407MsMHMlKI=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rzMc46mTpT6zifyvSEns0vJ7jz5NEsZUjH6it+cVjNz7VIqez/tkV0yvRlnjCJJxL
	 UvvZVvep8/RAzh0aW7iLHh4EXCwylVCr6l5ft9Zv/sKBugn0qdPiR2lu0bSuYojyoW
	 9B7z7+Isep2pD0omj6ysx2CfciPpe/5jMUQuMekU=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (74/60 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43241)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660q-000NkO-C0
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:45 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660p-0004ix-6Y
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:44 -0700
Date: Sun, 13 Nov 2016 17:24:42 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086682;
	bh=vjX2npqPvguYpOHuDeIlCrN7ijc7y6/cwi8iLlSjRO8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=I/PTkDimy6o57yTFaygasjV8vDtEVPSy4xQkAuFdvqwq3Hn98O/QhfSDj+0bTAZiF
	 ZXm3YA4pVy3apX819dfMUtp88TRXswgokp5O8niU0+rl6bXoclFZK0W1ZM5+9MoCzS
	 qiNSXTH2F08I37PfW15cCR608ndnZFWvU7ToQk2I=
