### ISSUE TITLE
long running functions getting killed

### ISSUE THREAD

**Issue by jcharbo** [facebook/react-native#9733]
Hi, I'm using version 32 of rn.  If I force a function to take 5 seconds or so by using a timeout it never returns.  On some components it's as short as 1300 mils.  Can someone please explain what's happening?  

This is important because if a network issue causes a delay in db query results then the data will never be returned because the function seems to be dying.  

The following code does not write to the console for me but if I change the number to 2000 or so it does.  This is in my root component.

```

class Home extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
    }
    setTimeout(function(){
      console.log('test')
    }, 5000);

  }

```

Thanks

**Comment by jacobp100** [comment]
IIRC this was a regression when using remote debugging.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/long-running-functions-getting-killed

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (73/60 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43240)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660p-000Nk0-P5
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:44 +0000
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660o-0004ir-GC
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:43 -0700
Date: Sun, 13 Nov 2016 17:24:41 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086681;
	bh=OgBQF0lijL5/MixO9XgLaiOFuTqpi6S0WKqnTdz5rRo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=2FdQhSxlwVAn+IiUrhbJKv5JcUGqKNFSfVydmbZF/QO4kNO+FKsdmWQCbIYXdmsDr
	 1/MT/A3cQ6eiNI4nlhJEwSw+drcvHjGP+H3MJ945jjCFC0c1TkJDrZ8Alo53yev233
	 p24Zc31h4wKYRaYvCoEMx8hSsqeCTtkOqMJxkGJ4=
