### ISSUE TITLE
Native events no longer being received after pressing back button and bringing app to foreground

### ISSUE THREAD

**Issue by ncodes** [facebook/react-native#9739]
### Issue Description

I am sending events from a service started by a native module. I noticed that when the back button is pressed once or twice, it expectedly moves the application to the background and then when I bring the application back to the foreground, events are no longer being received even though the native events are still being emitted.  
#### Expected Results

I expected the listeners in my component to resume listening for events
after the listeners are added in the `componentWillMount` method.
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/native-events-no-longer-being-received-after-pressing-back-button-and-bringing-app-to-foreground

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (63/60 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:42474)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65yD-000Mt2-Vk
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:22:03 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65yC-0003sW-Hp
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:22:01 -0700
Date: Sun, 13 Nov 2016 17:21:50 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086519;
	bh=HC3BXT8PiCNqIDr1+DruIJrqBcCvIzroxQ6NpHwlkdM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Hx5ZwhgzLUJEasa5zDN5JYuWAGHNCsAewETe8uThsdxMRMGpOXQm6MRPelJWUPI4m
	 y553G3GySky5N5dmq+Gx7kcJ2o0JPvNMyrbTviaRV9kL+MN865U0Adj0zUIPmHyurQ
	 C1r7gTuxDOCs0uXIfj8bc0hKVT5Ws5QuJ7Op7Ytw=
