### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by ThaJay** [facebook/react-native#9743]
<img width="487" alt="screen shot 2016-09-05 at 15 32 48" src="https://cloud.githubusercontent.com/assets/9341747/18249389/2f9063d0-737e-11e6-9827-e121c6894307.png">
On Android it's not a problem, only on IOS.
When you set a key `'string'` to value `undefined` it will succeed. with the following code:
```
function set(key, value) {
  return AsyncStorage.setItem(key, JSON.stringify(value))
}
```
But, if you then try to retrieve that item with the following code, the above error pops up.
```
function get(key) {
  function parseJson (item) {
    try { return JSON.parse(item) }
    catch (e) { return item }
  }
  return AsyncStorage.getItem(key).then(item => parseJson(item))
}
```
Because of the nature of the stacktrace (It does not show my code, there are too many internal function calls to have mine show up) it took me a really long time to figure out what was going on here, it was not obvious to me that AsyncStorage was producing this error.

Anyway, the following code solves it (just check instead of blindly set):
```
function set(key, value) {
  value = JSON.stringify(value)
  if (value) return AsyncStorage.setItem(key, value)
  else console.log('not set, stringify failed:', key, value)
}
```

### Thoughts:
- check for unparsable values on setItem
- improve error message to better reflect what the problem is so we can include the check (like in my example)

**Comment by Abusal7** [comment]
+1

**Comment by javache** [comment]
If you're using flow, it should highlighted to you that `AsyncStorage.setItem` expects a non-null key and value. The error on the iOS side is expected as you can't have null entries in an array.

**Comment by muhtarA** [comment]
you saved my live
