### ISSUE TITLE
Use class name AwesomeProject for all code examples in docs pages

### ISSUE THREAD

**Issue by piengeng** [facebook/react-native#9745]
### Issue Description

Request docs improvement to allow newbies to copy and paste code examples directly from website to local file. 
https://facebook.github.io/react-native/releases/next/docs/{PAGE}
I'm following examples along {getting-started.html}. with `react-native init AwesomeProject; ...; react-native run-android;` with android emulator on my computer.

When I'm trying the next example from {tutorial.html} I get 'Application AwesomeProject has not been registered' error msg on emulator. There's two ways to rectify it, either I do a `react-native init newPrj` or I change the code from the copied code class name from each example to AwesomeProject. 
It's just taking too much time for copy-pasting learning approach if I need to reinit react-native or change the class name to AwesomeProject on every tutorials. 

#### Expected Results

Just a suggestion, please change all class name to AwesomeProject for every tutorial page? Since newbies follow examples from {getting-started.html}. would be nice if we can just copy & paste to follow the examples from https://facebook.github.io/react-native/releases/next/docs/*

### Additional Information

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): Windows

**Comment by lacker** [comment]
You could just not paste that part? If you want to send a pull request, that would be great. Otherwise, I think this is not too bad to leave as is. I'm going to close this issue but if someone wants to either go change this, or somehow make the communications clear how this works, I think it would be "nice to have".
