### ISSUE TITLE
React Native Debug (Chrome): “Activate Breakpoints” not working as expected

### ISSUE THREAD

**Issue by afilp** [facebook/react-native#9746]
Are you aware of the following behavior?
(React Native Debug (Chrome): “Activate Breakpoints” not working as expected)

http://stackoverflow.com/questions/39319077/react-native-debug-chrome-activate-breakpoints-not-working-as-expected

I asked the question on SO but I think that you should also note about that because it seems to be a bug in the debugging behavior.

**Comment by afilp** [comment]
Has anybody confirmed this behavior? 

It happens always and it is very disturbing, I wonder if this does not happen to others. Can you please let me know? Thanks.

**Comment by rudyhuynh** [comment]
I confirm this, just use console.log all the time.

**Comment by afilp** [comment]
@rudyhuynh It is strange that only us report this, it is an annoyance to have to switch from "disable breakpoints" to "enable breakpoints" all the time when we simply reload the app to test a change (if hot reloading is not suitable).

Is it working OK to the react-native core developers? If yes, how? Thanks!

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
