### ISSUE TITLE
Cancelling offscreen image loads causing crashes in 0.33.0-rc.0 

### ISSUE THREAD

**Issue by lprhodes** [facebook/react-native#9751]
### Issue Description

I'm using RN 0.33.0-rc.0 and have a standard list view that continues to load more rows (using Relay) as the user scrolls down:
![simulator screen shot 6 sep 2016 10 41 59](https://cloud.githubusercontent.com/assets/162989/18258730/9ccf4bbe-741e-11e6-9ff3-49374bf9b28b.png)

If you scroll through the list on device (iPhone 6S) I'm frequently seeing crashes - all look to be related to the cancelling of loading images once the view has gone off screen. 

**Crash Traces**
<img width="1032" alt="screen shot 2016-09-06 at 10 45 15" src="https://cloud.githubusercontent.com/assets/162989/18258770/5e1ca9ec-741f-11e6-83ee-e6193887f242.png">
<img width="1045" alt="screen shot 2016-09-06 at 10 45 02" src="https://cloud.githubusercontent.com/assets/162989/18258774/5e753d50-741f-11e6-8562-a5598476e48d.png">
<img width="975" alt="screen shot 2016-09-06 at 10 44 46" src="https://cloud.githubusercontent.com/assets/162989/18258771/5e65e79c-741f-11e6-9200-017b7060a306.png">
<img width="1037" alt="screen shot 2016-09-06 at 10 44 28" src="https://cloud.githubusercontent.com/assets/162989/18258772/5e6a5e58-741f-11e6-91ac-9aa14dfaaac4.png">
<img width="1043" alt="screen shot 2016-09-06 at 10 44 16" src="https://cloud.githubusercontent.com/assets/162989/18258773/5e704b24-741f-11e6-932c-35da4a9953bf.png">

#### Expected Results

Deallocated instances not called or instances to be retained

### Additional Information

* React Native version: 0.33.0-rc.0
* Platform(s) (iOS, Android, or both?): iOS (not tested Android)
* Operating System (macOS, Linux, or Windows?): iOS 10

**Comment by ymmuse** [comment]
I have met same crashes in RN 0.32.0

**Comment by janmonschke** [comment]
This is still happening for us on 0.35.0
