### ISSUE TITLE
Set borderColor cash

### ISSUE THREAD

**Issue by senpng** [facebook/react-native#9754]
**My Code:**

``` javascript
<Image source={{ uri: 'http://img.ithome.com/images/v2.3/ithome.logo.png' }} style={styles.avatar} />
var styles = {
  avatar: {
    width: 80,
    height: 80,
    borderWidth: 2,
    borderRadius: 40,
    borderColor: 'red'
  }
}
```

![image](https://cloud.githubusercontent.com/assets/7333114/18264793/f0a65b80-7444-11e6-9bd1-7fb909e79207.png)

**And I change code(`RCTViewManage.m Line:181`):**
![image](https://cloud.githubusercontent.com/assets/7333114/18264854/36ec1a80-7445-11e6-963b-bd5a30617fc0.png)
to

``` objc
RCT_CUSTOM_VIEW_PROPERTY(borderColor, CGColor, RCTView)
{
//  if ([view respondsToSelector:@selector(setBorderColor:)]) {
//    view.borderColor = json ? [RCTConvert CGColor:json] : defaultView.borderColor;
//  } else {
    view.layer.borderColor = json ? [RCTConvert CGColor:json] : defaultView.layer.borderColor;
//  }
}
```

can work;

**react native version:**

```
"react": "^15.3.0",
"react-native": "^0.32.0",
```

**Comment by leeight** [comment]
Looks like it was fixed on the master branch?

![image](https://cloud.githubusercontent.com/assets/104052/18336832/329f19ea-75bd-11e6-96cf-72333baab4e8.png)

**Comment by senpng** [comment]
Thinks. I'm working in swift project, And now reviewed code in master branch. There seems to be no change to solve this problem

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/set-bordercolor-cash

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (72/60 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:35008)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660p-000Njw-4U
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:44 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660o-0002b4-J0
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:43 -0700
Date: Sun, 13 Nov 2016 17:24:42 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086682;
	bh=3RpvYwxPJQ1jX5twrEXYrhNo0zwoNvSbS/9NUpr1z7c=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=g6mZhwmrE9R9knaEmvyIY5/mP0HGr96EKWFcd5nrNnhn/qK8Ny1www3Fz+EZPsHXu
	 qtlgoAP3Q5ESNEoWX/zjNzMW1+LhwOclpE5+f/AoIZV94n4JbucAZSCGQSlYDYLNyJ
	 kpGH1Owyxv2OQ6nHe2brAwPokX9aRw55pdJRMPR4=
