### ISSUE TITLE
Android old RN activity crash after the new RN activity quit

### ISSUE THREAD

**Issue by oscarthecat** [facebook/react-native#9760]
hi all, currently we have two RN activity, rn1 and rn2, and RN version is 0.28
### Issue Description

rn1 starts rn2, and when rn2 quits(pressed back key), rn1 crashed
### Steps to Reproduce / Code Snippets

ReactInstanceManager(ReactInstanceManagerImpl) is a single instance, and rn1 and rn2's are using two different modules in one js bundle, thus we just have one React Context. And we will call 
`mReactRootView.unmountReactApplication();
        mReactRootView = null;`
in activity's onDestory.
#### Expected Results

we checked the code, and find when rn1 starts, ReactInstanceManager‘s ’ on onHostResume was called. Then rn2 starts, the calling sequence is:

rn1 - ReactInstanceManager‘s ’ on onHostPause
rn2 - ReactInstanceManager‘s ’ on onHostResume

when rn2 quits
rn2 - ReactInstanceManager‘s ’ on onHostPause
rn1 - ReactInstanceManager‘s ’ on onHostResume
rn2 - ReactInstanceManager‘s ’ on onDestroy (cause ReactInstanceManager/ReactContext state 
spoiled )
rn1- ReactInstanceManager‘s ’ on onDestroy(crash, because ReactContext's activity can't get FragmentManager)

Is there any mistake in this usage? Or how can we solve this ? Thanks very much!
### Additional Information
- React Native version: 0.28
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Windows

**Comment by charpeni** [comment]
@facebook-github-bot label Android

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/android-old-rn-activity-crash-after-the-new-rn-activity-quit

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (61/60 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:42438)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65yB-000Ms4-TE
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:22:01 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65yA-0003rh-Me
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:21:59 -0700
Date: Sun, 13 Nov 2016 17:21:47 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086518;
	bh=Yanq5J0i9mGj4hjCmRNcEJkk2G99pyoBMF77Ih8Jfm4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=dRUkxLwKDfcfoFFSuv40IM0Mxx/Fhf1FFbpxI1LDPSrhC+9BQYFhgoqQZTDj5yFwf
	 930jlfRlaWeLxFDk7dHSEW/ZhiDCna/sQW2xYTYfS2zpkhy6yu3feUe6CTbrQL5kWi
	 TmBwa3ODistMk7MlpRWJczx3wOYcml43V6PP0OXo=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (68/60 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43077)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660E-000NXP-7A
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:07 +0000
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660D-0004TA-15
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:05 -0700
Date: Sun, 13 Nov 2016 17:24:04 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086644;
	bh=gt3sFsYa/1IHH0H7BOMR8eVoDyEtMIpZLkRc7bvdm8U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lzoywQAnjZEV1e+wI2MZD31pqvfEkVrkuDE13FtAiUrPdfRc7Gv31BwfqygOCdonx
	 8/Dy/rZihSfhMM3ybdrLHplFlCC0Nl2KZEagh3YqtF1ZKcQD1cdVg5dtA6w/FSVGid
	 ZDun89NV6TyovxFuU4VMu+dCr9MPFXND/S5Vh9z4=

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (69/60 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:34982)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c660K-000NZm-IP
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:24:13 +0000
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c660J-0002aT-PN
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:24:12 -0700
Date: Sun, 13 Nov 2016 17:24:10 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086650;
	bh=o04ab+Kmoy9cDkl007BlUTh2pQ1v+mXnr1dhisj3E/E=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Y0ZOYLmkz9G4osyMtvmqDdTai/N5qwU/UtYBm1wJQx9JcqjSIXcWWssunIOGHAGdi
	 zFX6BNY0tKcUqzcpZRQ2j6UG782qtuq/86kMGBWRT61fSBAfqy4bR9CYbtCXS/qr1o
	 Fl+JwNcU0wyCAMyTecedakMN8xvVjoz9ABlnpi0I=
