### ISSUE TITLE
Cant receive notification token , when user clicks "dont allow" for requestPermission Alert:

### ISSUE THREAD

**Issue by rimzici** [facebook/react-native#9761]
RN : .31 also tried in .32
Using "PushNotificationIOS" component.

### Issue Description

cant receive token, when user choose not to receive, push notification[clicks "Dont Allow"].
As per my understanding from this [http://stackoverflow.com/questions/18478325/is-it-possible-to-get-the-device-token-even-if-push-notification-is-not-enabled](url) link , we must receive token, no matter what user chooses. 
Since no token when user dis allow initial pop up , and cant call the token "register" event after that , at any point, I am not able to reactivate push notification for that user, if he choses to activate it in the settings.
Addition info:
using "register" "notification" etc event listeners inside my ComponentWillMount() method.
### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

would like to receive token even though user dis allow push notification during app installation.
or else must be able to generate one , when user enables push notification later.

### Additional Information

* React Native version: 31
* Platform : iOS
* Operating System (macOS, Linux, or Windows)

**Comment by rimzici** [comment]
Solved the issue.
After putting my register event listener inside constructor it works. 
Sorry Team. Was my ignorance 
thank you

**Comment by charpeni** [comment]
I'll close this issue since it has been resolved.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-5** [comment]
@charpeni tells me to close this issue. If you think it should still be opened let us know why.
