### ISSUE TITLE
iphone6 9.3 XMLHttpRequest request error!but ios8.2 success

### ISSUE THREAD

**Issue by XingdaLee** [facebook/react-native#9763]
code:
    var request = new XMLHttpRequest();
    request.onreadystatechange = (e) => {
      if (request.readyState !== 4) {
        return;
      }
      if (request.status === 200) {
        console.log('success', request.responseText);
      } else {
        console.warn('error');
      }
    };

```
request.open('GET', 'http://www.baidu.com/');
request.send();
```

**Comment by XingdaLee** [comment]
my version ：
"react": "15.2.1",
   "react-native": "0.31.0",

**Comment by leeight** [comment]
iOS ATS

https://developer.apple.com/library/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW14

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/iphone6-93-xmlhttprequest-request-errorbut-ios82-success

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (67/60 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:43040)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c6604-000NU2-Di
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:23:58 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c6603-0004OU-2A
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:23:56 -0700
Date: Sun, 13 Nov 2016 17:23:54 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086634;
	bh=XzXu9BuER4Bv4VFrxaAdSXPInw3TrE6sCFiAQlbQT6o=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Abr9j4wuFvCgn6avkznxa5JVzewOvaL1qzdNHwej4TzV49vIcXT89GZDH4G22IL2O
	 jANN1Vi8jhk1tUMNtjtzStxinv323ODawCFvkNbLwEMF8UYU5X5sdVDKL5sgd/GyN9
	 xvTSL371TO0G9amldjm39DTxcxHmFPwWek4DYZ44=
