### ISSUE TITLE
FUndefined is not an object (evaluating 'RNI18n.locale')

### ISSUE THREAD

**Issue by yarnball** [facebook/react-native#9765]
### Issue Description

All projects (starters, blank starter offical one) cause the same error:

`Undefined is not an object (evaluating 'RNI18n.locale')`
### Steps to Reproduce / Code Snippets

To setup my code, I followed the offical facebook guide:
1. npm install -g react-native-cli
2. react-native init ProjectName
3. react-native run-ios
- I tried running from the cmd "react-native run-ios" and from the .xcodeproj file
- I have tried with a fresh (unmodified) react-starter repo
- I have tried with a new simulator (Xcode, new iOS version & device)
- I get no errors in the console/bash
- I uninstalled (then re-installed) react native (via npm)

Error from X-code console:

> 2016-09-06 21:48:56.897 [warn][tid:main][RCTEventEmitter.m:54] Sending `websocketFailed` with no listeners registered.
> 2016-09-06 21:48:56.991 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'RNI18n.locale')
> 2016-09-06 21:48:56.994 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'RNI18n.locale')
> 2016-09-06 21:48:57.008 [warn][tid:com.facebook.react.JavaScript] Unable to symbolicate stack trace: The stack is null
> 2016-09-06 21:48:57.064 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.
> 2016-09-06 21:48:57.066 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module.
> 2016-09-06 21:48:57.072 [warn][tid:com.facebook.react.JavaScript] Unable to symbolicate stack trace: The stack is null
#### Expected Results

Projects to build and work!
### Additional Information
- React Native version: 0.32
- Platform(s) (iOS, Android, or both?): iOS simulator (all versions). Android not tested
- Operating System (macOS, Linux, or Windows?): macOS

Screenshot attached
![2016-09-06 at 4 28 47 pm](https://cloud.githubusercontent.com/assets/13043067/18272832/735f55b2-747d-11e6-810b-c2ef00f7d5c0.jpg)

**Comment by nihgwu** [comment]
It's obvious that the third-party module wasn't linked right, please follow the tutorial provided on the home page of the module to link it first

**Comment by sharnik** [comment]
> It's obvious that

It's hardly obvious. 

Instead of being condescending maybe you can point out which part of the stacktrace makes it obvious for you?

**Comment by nihgwu** [comment]
@sharnik the first line has told you that `RNI18n` is undefined, isn't it obvious enough?

**Comment by yarnball** [comment]
@sharnik Thanks, I agree- what's obvious to @sharnik isn't necessarily obvious to me.

Doesn't seem it was related to third-party module being linked right. I actually needed to reboot my laptop and it worked. I have triggered it again (some how) but rebooting fixes. I'll investigate to try and find the cause.

**Comment by nihgwu** [comment]
sorry for my arbitration then

**Comment by lacker** [comment]
FWIW it isn't obvious to me either, but I'm glad that this problem got solved! I am going to close the issue and thanks to everyone for helping out here.
