### ISSUE TITLE
Webview Issue: onLoad and onLoadEnd fire multiple times before pageload ends 

### ISSUE THREAD

**Issue by anotherstarburst** [facebook/react-native#9766]
### Issue Description

The webview methods which should fire at the end of a page load, seem to fire before pageload ends. 
### Steps to Reproduce / Code Snippets

```
  `<WebView
        source={{ uri: "http://www.bbc.com" }}
        style={ localStyles.webviewContainer }
        javaScriptEnabled = { true }
        injectedJavaScript={ this.state.webviewInjectedScript }
        onNavigationStateChange = { alert("onNavigationStateChange")}
        onLoadEnd = {alert("onLoadEnd")}
        onLoad = {alert("onLoad")}
      />`
```
#### Expected Results

One would expect the alerts to each fire once. However, on opening a new webview with the bbc.com link, the alerts each fire multiple times. Any ideas on what may be causing this?
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): iOS (untested on Android)
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by superandrew213** [comment]
[#4945](https://github.com/facebook/react-native/issues/4945)

**Comment by christopherdro** [comment]
Duplicate
