### ISSUE TITLE
Video not visible, I can hear audio in Android Simulator.

### ISSUE THREAD

**Issue by Johnny1109** [facebook/react-native#9767]
Video not visible, I can hear audio in Android Simulator.

any suggestion friends?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue!

It looks like your description is missing some additional detail. Can you please add all the info specified in the [template](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported. 

We can reopen the issue once sufficient information has been provided. Thanks!
