### ISSUE TITLE
Execution failed for task ':app:packageAllDevDebugClassesForMultiDex'. > java.util.zip.ZipException: duplicate entry: com/facebook/proguard/annotations/DoNotStrip.class

### ISSUE THREAD

**Issue by holiday** [facebook/react-native#9770]
### Issue Description

:app:packageAllDevDebugClassesForMultiDex FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageAllDevDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/facebook/proguard/annotations/DoNotStrip.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

### Steps to Reproduce / Code Snippets

Here is my list of dependencies:
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:support-v4:23.0.1'
    compile 'com.android.support:appcompat-v7:23.0.1'
    //compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.squareup.dagger:dagger:1.2.1'
    provided 'com.squareup.dagger:dagger-compiler:1.2.1'
    compile 'com.github.frankiesardo:icepick:2.3.5'
    provided 'com.github.frankiesardo:icepick-processor:2.3.5'
    compile 'com.jakewharton:butterknife:3.0.0'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.kevinsawicki:http-request:5.6'
    compile 'com.mobsandgeeks:android-saripaar:1.0.3'
    compile 'com.google.zxing:core:3.1.0'
    compile 'com.google.zxing:javase:3.1.0'
    compile 'com.google.zxing:android-integration:3.1.0'
    compile 'com.fasterxml.jackson.core:jackson-core:2.2.3'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.2.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.2.3'
    compile 'com.j256.ormlite:ormlite-core:4.48'
    compile 'com.j256.ormlite:ormlite-android:4.48'
    compile 'com.crashlytics.android:crashlytics:1.+'
    compile 'com.squareup.retrofit:converter-protobuf:1.4.1'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
    compile 'com.joanzapata.android:android-iconify:1.0.8'
    compile 'com.google.maps.android:android-maps-utils:0.3.3'
    compile 'se.emilsjolander:stickylistheaders:2.5.2'
    compile 'com.applause:applause-sdk:3.4.6@aar'
    compile 'com.webtrends:webtrends-android-sdk-release-lib-3.0.6@aar'
    compile 'com.facebook.react:react-native:0.32.0'
    compile 'com.squareup.retrofit:retrofit:1.8.0'
    compile 'com.github.clans:fab:1.6.2'

//We are also using a few more other dependencies not listed here

#### Expected Results

It compiles.

### Additional Information

* React Native version: 0.31+
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by holiday** [comment]
This issue was resolved, it was determined that facebook's "conceal" library was being pulled in twice in our project via an aar file. It was pretty cumbersome to locate it however we found it. 

Closing this issue now.

**Comment by cinder92** [comment]
@holiday  where did you find the duplicate file? i'm having same issue but with okhttp3...

**Comment by holiday** [comment]
Turns out our react native library was conflicting with another jar that was pulling in the conceal library. I found it by decompiling all the jar files we had in the project. You may have luck updating all your dependencies to the latest version. Check all your jar files to see what they are pulling in. Research all your libs documentation or source code to see if they are importing the same library. 

This took like 2 weeks to find btw...i dont know why its so hard to detect issues like this on Android, iOS is much easier.

**Comment by boopathit** [comment]
And how to resolve it after finding it @holiday I'm a newbie so please help.....
