### ISSUE TITLE
Reload (from dev menu) should call onHostDestroy or any other event to detect Reload

### ISSUE THREAD

**Issue by mauron85** [facebook/react-native#9773]
Thank you guys for amazing work
### Issue Description

I'm developing [react-native-background-geolocation](github.com/mauron85/react-native-background-geolocation/). While working on [this issue](https://github.com/mauron85/react-native-background-geolocation/issues/10), I've identified potential problem within my module logic and Reload (from dev menu) functionality.

In my module I'm creating [LocationService](https://github.com/mauron85/react-native-background-geolocation/blob/master/android/src/main/java/com/marianhello/bgloc/LocationService.java) similar to android [MessengerService](https://developer.android.com/reference/android/app/Service.html#RemoteMessengerServiceSample) from android examples.
In [BackgroundGeolocationModule](https://github.com/mauron85/react-native-background-geolocation/blob/master/android/src/main/java/com/marianhello/react/BackgroundGeolocationModule.java#L397) I'm binding to this service (and starting it) on user request (from js). Module **should** unbind from service on **onHostDestroy** (LifecycleEventListener) method (this part is not in my repo yet).

However it seems Reload doesn't call **onHostDestroy** or any other event to detect Reload event. As result client (module) client will be binding to service twice, which leads to **java.lang.IllegalStateException: "This message is already in use"** and app crash.

```
AndroidRuntime  D  Shutting down VM
                E  FATAL EXCEPTION: main
                E  Process: com.marianhello.RNBGExample, PID: 11937
                E  Theme: themes:{default=overlay:com.resurrectionremix.pitchblack, fontPkg:com.resurrectionremix.pitchblack, com.android.systemui=overlay:com.resurrectio
                   nremix.pitchblack, com.android.systemui.navbar=overlay:com.resurrectionremix.pitchblack}
                E  java.lang.IllegalStateException: { when=0 what=4 target=com.marianhello.react.BackgroundGeolocationModule$IncomingHandler } This message is already in 
                   use.
                E      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:538)
                E      at android.os.Handler.enqueueMessage(Handler.java:631)
                E      at android.os.Handler.sendMessageAtTime(Handler.java:600)
                E      at android.os.Handler.sendMessageDelayed(Handler.java:570)
                E      at android.os.Handler.sendMessage(Handler.java:507)
                E      at android.os.Handler$MessengerImpl.send(Handler.java:721)
                E      at android.os.Messenger.send(Messenger.java:57)
                E      at com.marianhello.bgloc.LocationService.sendClientMessage(LocationService.java:369)
                E      at com.marianhello.bgloc.LocationService.handleLocation(LocationService.java:348)
                E      at com.marianhello.bgloc.AbstractLocationProvider.handleLocation(AbstractLocationProvider.java:81)
                E      at com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider.onLocationChanged(DistanceFilterLocationProvider.java:318)
                E      at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:285)
                E      at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
                E      at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:230)
                E      at android.os.Handler.dispatchMessage(Handler.java:102)
                E      at android.os.Looper.loop(Looper.java:148)
                E      at android.app.ActivityThread.main(ActivityThread.java:5461)
                E      at java.lang.reflect.Method.invoke(Native Method)
                E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 unknown:React  W  Calling JS function after bridge has been destroyed.
```
### Steps to Reproduce / Code Snippets
1. Create android Service similar to [MessengerService](https://developer.android.com/reference/android/app/Service.html#RemoteMessengerServiceSample) 
2. In ReactContextBaseJavaModule bind to it.

```
...
void doBindService() {
    // Establish a connection with the service.  We use an explicit
    // class name because there is no reason to be able to let other
    // applications replace our component.
    if (mIsBound) { return; } //member variable to prevent client to bind multiple times, but doesn't help when Reload is done (Module is reinstantiated so it is false again)

    mMessenger = new Messenger(new IncomingHandler());

    final Activity currentActivity = this.getCurrentActivity();
    Intent locationServiceIntent = new Intent(currentActivity, LocationService.class);
    locationServiceIntent.putExtra("config", mConfig);
    currentActivity.bindService(locationServiceIntent, mConnection, Context.BIND_IMPORTANT);
  }
...
```
1. In some point. Do app Reload from dev menu
2. Send some IPC Message from Service to client.
3. App will crash, because client was registered twice, so same Message was sent twice to same client (which is illegal action in Android)
#### Expected Results

Event that is sent before react-native will do Reload, so we can unbind from service.
### Additional Information

Addtional description also here:
http://stackoverflow.com/questions/39354236/android-how-to-prevent-binding-to-remote-messenger-service-twice-to-prevent-java?noredirect=1#comment66039454_39354236
- React Native version: 0.29
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): all

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/reload-from-dev-menu-should-call-onhostdestroy-or-any-other-event-to-detect-reload

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (66/60 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter01.reliabledns.org ([199.96.156.50]:42957)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65zr-000NPp-DC
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:23:45 +0000
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195] helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by filter01.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65zq-0004KH-7E
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:23:43 -0700
Date: Sun, 13 Nov 2016 17:23:41 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086621;
	bh=DTm/UvhvtdKknS9NrTr5lbPCfskfcc4Eefs7MIa9Njw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HjNXtMBMCf21kSuFHnDAZE3dFn3on6a8v0ocDPKwqdstikLCNfB6lp+YhQPoRkS4/
	 NvoO9PapmqByYy2OHhdQyR1r/oiJzQPZHvlvHFUuvpEjLuLsZHDVxnrWvKgsfQ00xt
	 OsZoZGhfiOIRmiqfaLyHW/yJf54gFH15Xb8KbRYk=

**Comment by grabbou** [comment]
This is unfortunate. Some sort of event should be called to clean up resources.

**Comment by mauron85** [comment]
IMO unfortunate is also approach how reported issues are just closed without any comment. I appreciate any guy who is working hard on react-native, but for me as reporter this approach is very rude and frustrating.

**Comment by ofirdagan** [comment]
+1

**Comment by lucasbento** [comment]
@mauron85: how did you end up solving this?

**Comment by mauron85** [comment]
@lucasbento I don't think I actually solved satisfactorily. I just fixed the crash but lot problems remained.

**Comment by lucasbento** [comment]
@mauron85, @grabbou, @charpeni: can this issue be reopened? I think it's valid, useful and should be implemented at some point.

**Comment by mauron85** [comment]
@lucasbento. I don't see any reopen button here. So I can not.

**Comment by charpeni** [comment]
@lucasbento Sure, let's reopen it.

**Comment by spectralsun** [comment]
how is this still not fixed? it surely can't be difficult to provide SOME kind of event when the app has been reloaded from the dev menu

**Comment by CrazyPython** [comment]
I suppose it may be difficult to send an event to the JS side, because it would require the native side to wait synchronously for the JS call stack to complete, something React Native is not (yet) designed for. Perhaps this functionality will be available after [React Native's is redesigned internally](https://facebook.github.io/react-native/blog/2018/06/14/state-of-react-native-2018#architecture).

**Comment by mauron85** [comment]
I was not talking about js side, rather native java. Add event to LifecycleEventListener.java

**Comment by CrazyPython** [comment]
I'm aware.

**Comment by grabbou** [comment]
I am reopening this. It's still an issue and we need a way to clean up resources when we reload the app. It's been really hard for me to clean up resources. If there's anyone knowing a better workaround, please let me know.

CC: @kmagiera maybe you happen to have a better context here?

**Comment by ferrannp** [comment]
So basically I think the behavior is correct (`onHostDestroy` not called) because the Host (`Activity`) is not destroyed. For what we talked though, I'd be nice if we could nootify native modules if the JS has been reloaded. This is of course, a DEV only issue.

**Comment by dulmandakh** [comment]
IIRC, there is no default way to notify native module if JS reloaded. But you can have native method and call it on componentDidMount() a component to do the binding.
