### ISSUE TITLE
Screen rotation using RCTRootView.h

### ISSUE THREAD

**Issue by 7ynk3r** [facebook/react-native#9775]
### Issue Description

There is no screen rotation transition when using `RCTRootView.h` . 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6763798/18287183/dd7af652-742a-11e6-8271-3a8607c79cdb.gif)

### Steps to Reproduce / Code Snippets

I'm following the tutorial for https://facebook.github.io/react-native/docs/integration-with-existing-apps.html

The only change is that I'm using a navigation controller with a controller containing the react native view.

AppDelegate.m

        UINavigationController *nav = [[UINavigationController alloc] init];
        UIViewController *resps = [[MMResponsesListRN alloc] init];        
        [nav pushViewController:resps animated:NO];

MMResponsesListRN.m

    - (void)viewDidLoad {
        [super viewDidLoad];
        // Do any additional setup after loading the view.
        
        NSURL *jsCodeLocation = [NSURL
                                 URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
        RCTRootView *rootView =
        [[RCTRootView alloc] initWithBundleURL : jsCodeLocation
                             moduleName        : @"RNHighScores"
                             initialProperties :
         @{
           @"scores" : @[
                   @{
                       @"name" : @"Alex",
                       @"value": @"42"
                       },
                   @{
                       @"name" : @"Joel",
                       @"value": @"10"
                       }
                   ]
           }
                              launchOptions    : nil];
    //    UIViewController *vc = [[UIViewController alloc] init];
        self.view = rootView;
    //    [self presentViewController:vc animated:YES completion:nil];
    }

#### Expected Results

I'd expect something better than that.

### Additional Information

* React Native version: "react-native": "^0.32.0"
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by javache** [comment]
This is not well-supported in React Native on iOS right now, since layout is calculated and applied asynchronously, so changes are only applied after the animation completes.

Feel free to post and up-vote this on [ProductPains](https://productpains.com/product/react-native/) and we may prioritize it.
