### ISSUE TITLE
Add support for resource-id

### ISSUE THREAD

**Issue by jsdevel** [facebook/react-native#9777]
### Issue Description

There currently isn't a way to find elements by resource-id using appium/uiautomatorviewer.

`react-native` currently supports `contentDescription` via `accessibilityLabel`.  This is great for clickable elements, but not so great for testing other things like splash screen visibility.

I'd be more than willing to add support for this, but am currently not aware of how `react-native` builds the android views.  If someone could give me some guidance on how `android:id` could be added to a view then I'd most certainly be willing to give it a shot.  My understanding of `android:id` (per the [View docs on IDs](https://developer.android.com/reference/android/view/View.html)), is that it must be set in the XML prior to view creation.

I don't believe this is a duplicate of #7135, because I'm not proposing that we break the way testID currently works, more that I feel it would be nice if `testID` could add it's value to the corresponding view component in the XML.
### Steps to Reproduce / Code Snippets
- Add `testID="something"` to any component (e.g. `View`)
- Run the app on an android device
- Run `uiautomatorviewer`

You'll notice that `resource-id` is empty

![without-id](https://cloud.githubusercontent.com/assets/2605980/18291362/3a56eac8-743c-11e6-9c86-5cfc3b210d9e.png)
#### Expected Results

`resource-id` has a value like `com.myApp:id/something`
### Additional Information
- React Native version: `0.32`
- Platform(s) (iOS, Android, or both?): Android.
- Operating System (macOS, Linux, or Windows?): All

**Comment by jsdevel** [comment]
@tuckerconnelly referenced `BaseViewManager` [here](https://github.com/facebook/react-native/issues/7135#issuecomment-232379887).  I'm thinking it could be modified to do something like this:

```java
  @ReactProp(name = PROP_TEST_ID)
  public void setTestId(T view, String testId) {
    try {
      view.setId(R.id.class.getField(testId).getInt(null));
    } catch (Exception e) {
      // swallow
    }
    view.setTag(testId);
  }
```
The trick is gaining access to `R` which resides in the application's package.

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/add-support-for-resource-id

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by dshn197** [comment]
I am testing a react-native application and I do feel I require the support for resource-id. Can you guys open up this ticket again?

**Comment by Vetalyo** [comment]
I have the same trouble, for Robo tests needed resource-id for each page component.
Any news about this? Very need this functional. :disappointed:

**Comment by thecopy** [comment]
Yes we need this as well.

**Comment by rodrix** [comment]
Something new about this issue?
My testing crew is stuck without this. ;/

**Comment by shivasrini** [comment]
+1 that this will help testing

**Comment by jnrepo** [comment]
+1 need this for testing

**Comment by oleksandrriabykh** [comment]
PLZ, make us happy. Add resource-id support

**Comment by dorangao** [comment]
+1, Please. It will make life easier.

**Comment by jkwohlfahrt** [comment]
+1

**Comment by evanjmg** [comment]
My workaround for testing right now is accessibility Label. However, this does not help with prelaunch Google Play testing :(

**Comment by vefimofff** [comment]
+1 our team finds this feature really helpful. Are there any plans on moving this forward?
