### ISSUE TITLE
Source map for the bundle is not generated correctly when fat arrow function is used

### ISSUE THREAD

**Issue by changsi-an** [facebook/react-native#9778]
### Issue Description

Source map is not generated correctly when fat arrow function is used.
### Steps to Reproduce / Code Snippets

Create a react native project

```
react-native init react_native_example2
```

Add a fat arrow function in the main component (*\* index.ios.js**).

``` javascript
1  /**
2   * Sample React Native App
3   * https://github.com/facebook/react-native
4   * @flow
5   */
6  
7  import React, { Component } from 'react';
8  import {
9    AppRegistry,
10    StyleSheet,
11    Text,
12    View
13  } from 'react-native';
14  
15  class react_native_example2 extends Component {
16  
17    op1() {
18      console.log("hi")
19    }
20  
21    op2 = () =>{
22      console.log("hi")
23    }
24  
25    render() {
26      return (
27        <View style={styles.container}>
28          <Text style={styles.welcome}>
29            Welcome to React Native!
30          </Text>
31          <Text style={styles.instructions} onPress={() => this.op1()}>
32            To get started, edit index.ios.js
33          </Text>
34          <Text style={styles.instructions} onPress={this.op2}>
35            Press Cmd+R to reload,{'\n'}
36            Cmd+D or shake for dev menu
37          </Text>
38        </View>
39      );
40    }
41  }
42  
43  const styles = StyleSheet.create({
44    container: {
45      flex: 1,
46      justifyContent: 'center',
47      alignItems: 'center',
48      backgroundColor: '#F5FCFF',
49    },
50    welcome: {
51      fontSize: 20,
52      textAlign: 'center',
53      margin: 10,
54    },
55    instructions: {
56      textAlign: 'center',
57      color: '#333333',
58      marginBottom: 5,
59    },
60  });
61  
62  AppRegistry.registerComponent('react_native_example2', () => react_native_example2);
63  
```

Run the app

```
react-native run-ios
```

Pull down the bundle and the source map

```
curl "http://localhost:8081/index.ios.bundle" -o index.ios.bundle
curl "http://localhost:8081/index.ios.map" -o index.ios.map
```

Those two files are attached. 
[Archive.zip](https://github.com/facebook/react-native/files/457848/Archive.zip)

Then use the following script to inspect the source map:

``` javascript
var fs = require('fs');
var sm = require('source-map');

var sourceMap = './index.ios.map';
var smap = JSON.parse(fs.readFileSync(sourceMap));

var sourceMapConsumer = new sm.SourceMapConsumer(smap);

console.log(sourceMapConsumer.generatedPositionFor({
    source:'ORIGINAL_SOURCE_LOCATION_for_index.ios.js', 
    line: 18, 
    column: 0
}));
```

it yields:

```
{ line: 1504, column: 0, lastColumn: null }
```

But in index.ios.bundle file, line 1504 is a blank line:

![image](https://cloud.githubusercontent.com/assets/14335429/18291817/0f1511b6-743f-11e6-87ac-e7f1ec3a6e9f.png)

**Removing the fat arrow function`op2` can have the line in `op1` reported correctly.**
#### Expected Results

The line in the bundle should be reported as 1509, where it actually is at.
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): iOS (haven't tested Android)
- Operating System (macOS, Linux, or Windows?): macOS (haven't tested others)

**Comment by changsi-an** [comment]
@MSLaguana

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/source-map-for-the-bundle-is-not-generated-correctly-when-fat-arrow-function-is-used

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by bunnyboy1** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tajindersingh.3012@gmail.com
    Domain thumbmunkeys.com has exceeded the max emails per hour (65/60 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from filter03.reliabledns.org ([69.175.33.179]:34894)
	by en02-ams.stablehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1c65zC-000NDP-CX
	for bunny@thumbmunkeys.com; Mon, 14 Nov 2016 01:23:03 +0000
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194] helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by filter03.reliabledns.org with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1c65zB-0002XC-NV
	for bunny@thumbmunkeys.com; Sun, 13 Nov 2016 18:23:02 -0700
Date: Sun, 13 Nov 2016 17:23:01 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1479086581;
	bh=B4HXP4V5OgYHRi80acILtZI7e3+CRtNYU4kVv61q9L0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lLtEL/fe163cZ/nKe7cl1FtuTF0qAXW9+JDNZFCvqFj5r/Snrdl1hky7kzRTUiwEU
	 +A0vJLh4VU++cpKGIJ1esvw6meF5heSgPCaMGsflWY+tojlTFRs9kzumxoKxIzR1HY
	 2JpLFNjq0TFgJcCy3F/5TKJTRyB3czxabXJhIw10=
