### ISSUE TITLE
Red borders around images

### ISSUE THREAD

**Issue by joshbedo** [facebook/react-native#978]
So right now i have a problem where all of my `<Image />` tags have red borders around them. I tried loading different images to make sure that it wasn't something to do with the location of the image but i can't seem to fix it. Here is a screenshot of what i'm seeing. Does anyone have any ideas? Also i was wondering about the best way to debug this

![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_65558/lJmWYNKxFNubWVCJsTH6C1uxYubrUf/Monosnap%2B2015-04-22%2B19-26-22.png?Expires=1429831772&Signature=F4wEJii4tr71qQmEXJL7~IzS9KX6iWQ5~oDnm1PO5EeiwWBa~pnLlX0ye4aRkJfrtXHKnZelBuwPuGPvX9o0wJV0K8ifYKqqJrTicJ1Lf5D2mEpgDv0AIjJuWids9ezCy1cAhT5Z-MdeW1VEtOmQgxiqr6us8XWn3PbxvFIlANkEm~uhLk09rb~OcGhgQb~2flKbx8HYTB2lBNn5Md42HOwi~pWpeiRse3gIbxZx5PPthQ4jR4qJfR6UztWRG3tMMrPuu5WQvsyTC2SxWxwZyI5R0LTtM-nG1qpHvlKg4ujCVPSuraAnxaXkID~SQtX1enSTJoOcqSfW8hLKTz6ANg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by frantic** [comment]
Did you add images to Images.xcassets in Xcode? Is there anything in Xcode logs?

**Comment by joshbedo** [comment]
I'm using `<Image source={{uri: 'http://randomimageurl' }}  style={{width:20, height:20}} />` so i shouldn't need to worry about `Images.xcassets` unless i'm using `require('image!imagename')`, right?

**Comment by brentvatne** [comment]
@joshbedo - can you post a project where this happens to Github and link us to it? that would probably be the easiest way for us to discover the problem

**Comment by joshbedo** [comment]
@brentvatne Yup, I'm using React Native Router - https://github.com/t4t5/react-native-router

**Comment by joshbedo** [comment]
So i recreated the application and it doesn't happen anymore.. I guess someone happened with the xcodeproj or some other area that broke images.

**Comment by jonmorehouse** [comment]
Hey guys, I'm having the same issue. Over in the #reactnative irc.

@brentvatne

**Comment by dsibiski** [comment]
Hey @jonmorehouse, I'm having this issue as well...were you able to find a fix for it besides just recreating the project?

**Comment by dsibiski** [comment]
Actually, I found out why it wasn't working for me...I hadn't included the `RCTImage.xcodeproj` library in my iOS Project. Once I added it and linked the product, everything worked fine.
