### ISSUE TITLE
Does sectionIDs (array) and rowIDs (array) of cloneWithRowsAndSections of ListView has to be array, can't it be Set?

### ISSUE THREAD

**Issue by Aggie123** [facebook/react-native#9782]
About this function of ListView: cloneWithRowsAndSections(dataBlob, sectionIdentities, rowIdentities) 
I'm trying to pass sectionIdentities and rowIdentities here as set, but it doesn't work. 
Would be better if  cloneWithRowsAndSections can support set data structure.
Thanks!

**Comment by ide** [comment]
Want to send a PR to use iterall to support sets? https://github.com/leebyron/iterall

**Comment by hey99xx** [comment]
What would be the iteration order of a set iteration though? How are you going to have consistent iteration order over a set?

From the docs @ide provided, iterall should work with ES6 JavaScript sets since it will use Symbol.iterator functions which should be available on sets.

**Comment by ide** [comment]
@hey99xx Sets are ordered based on insertion

**Comment by hey99xx** [comment]
@ide you're right. I assumed it would be like Java or one of the other languages without guaranteed iteration order for sets. It's strange that JS does that in my opinion. 

Still, I don't see the benefit of ListView accepting sets, accepting arbitrary iterables makes sense though, if it already doesnt.

**Comment by ide** [comment]
The point of iterall is to support all Iterables. If you implement the Iterable protocol, your data structure will work.
