### ISSUE TITLE
react-native link fails on Windows 10

### ISSUE THREAD

**Issue by afilp** [facebook/react-native#9787]
When I use this on Windows 10...
react-native link react-native-svg

...I get this:
![image](https://cloud.githubusercontent.com/assets/7850073/18306129/1e1b6ba6-74f3-11e6-883f-75db85ecaa26.png)

It seems that the linking fails due to this. 

Any ideas why I get the above message and if it is indeed a bug?

Thank you.

**Comment by grabbou** [comment]
Interesting, what's the react-native version you are using? CC: @Kureev

**Comment by Kureev** [comment]
Does it happens only with this module? Have you tried to link something else?

**Comment by af7** [comment]
I am using version v0.32 but it did it on other versions too, from v.029+ that I tested.

It also happened with "react-native-code-push", so I believe it is a global issue related to Windows not interpreting correctly characters or strings that are OK in Unix (I assume). You know much better obviously, if you can test it with a project do you get the same? (in Windows)

**Comment by afilp** [comment]
I can confirm that this does not happen anymore, so issue closed.
