### ISSUE TITLE
Image component onLoadingStart/onLoadingFinish/onLoadingError props

### ISSUE THREAD

**Issue by jordanna** [facebook/react-native#98]
Not sure if this is on your radar, but I'm playing around with `RCTNetworkImageView` and its manager to see if I can expose them. It's mostly so I can fade in the image (vs. simply appearing) when `onLoadingFinish` is called, but they could be useful for other use cases :)

**Comment by jordanna** [comment]
Just took a stab at it since I'm working on a prototype that needed the feature.

**Comment by brentvatne** [comment]
Closing issue as there is now a corresponding pull request :smile: thanks
