### ISSUE TITLE
[NavigationExperimental] Dealing with race conditions on CardStack

### ISSUE THREAD

**Issue by MinusFour** [facebook/react-native#9801]
I've been having this issue with the navigation router in where I can't update the current route while the navigation animation is being performed. This means that I can't have the next scene update the route object inside the state when its component is being mounted. For example, I push a scene, the scene components gets mounted and does a HTTP request to fill out some route specific details and updates the route object, the animation begins. If it updates the route object while the animation is happening the animation stops somewhere in between and you can't interact with any other UI component (BackAndroid works for example), it sort of looks like it crashes (although it doesn't).

It seems that if I really want to avoid having this race condition I need to stop updating the route object all together and handle the route state separately. I've been trying to separate the route state inside the redux state but so far it has proven to be very hard and not very clean. I think the only way to deal with this is if I manage the route state as the component state but it's also not very clean.

What is the best approach to manage route state?

**Comment by ljharb** [comment]
ping @ericvicenti per our in-person discussion

**Comment by ericvicenti** [comment]
We currently don't support the ability to change the route in the middle of a transition. So I think this is a valid issue, but there are ways to get around it for your use case.

If you're fetching info from network, I would think that the data should come from a different part of your store. For example, if you're navigating to a person's profile but you don't know the name until the network resolves, you could put the person ID in the route (which will not change), and your title component could be connected to the appropriate name from the store.

**Comment by MinusFour** [comment]
We are kind of managing stuff just like you say from different parts of the store and then we just map it. However some kind of details are really route specific. For example, a list of items to display in a specific route (where there can be more than one instance of a scene). We've run into many problems managing these lists separately. When we pop out a route from the navigator state we also take out the information relevant to the route and since both components are needed to create the transition, the component that is about to be popped out will clear out the information before doing the transition.

Our components actually fail because they are looking for stuff that isn't there any more. We could handle that specific scenario, but then again best case scenario is that the user sees the scene being popped out without the information during the transition (in our case, a listView of images that takes almost the whole screen) which is far from being ideal. This is partly the reason why I've been wondering if it'd be better to set the route information as part of the component state. Though we'd lose a great deal of flexibility, I think.

Right now, we are only storing server pagination information on the route but it's not the only thing we've wondered about storing in the route object.

**Comment by ryankask** [comment]
I've been putting this sort of data elsewhere in the store and accessing it via connect(). 

What kind of trouble are you having separating the route state from the other state the component needs?

In the case of scenes being popped, I'm not 100% I understand what you mean but I've done some hacky things where I define `shouldComponentUpdate => !scene.isStale` on the scene component.

**Comment by satya164** [comment]
Putting data in the route object seems hacky.

**Comment by MinusFour** [comment]
> In the case of scenes being popped, I'm not 100% I understand what you mean but I've done some hacky things where I define shouldComponentUpdate => !scene.isStale on the scene component.

Basically, my store action pops the route (and its information) which triggers the navigation change and the animation. However the information is lost before the animation begins which clears out the current scene information. So, the user pops the route then it flashes the scene clean and the animation begins.

Did you create your own kind of connect that doesn't update with values from the store if the scene passed is being popped out? Not sure what `isStale` reflects or when does it do it.

> Putting data in the route object seems hacky.

Well, it seemed pretty natural to me. Other than the fact that to avoid mutations I have to create a new array for `routes`, a copy of the route object and then insert it back into the array with the square braces notation.

> Probably you should do it separately by listening to the state changes.

I don't understand what you mean by that. What we are doing right now is returning a `connect` component on the `renderScene` method. We have an action that pops the route plus the route information. Even if we listened to the state changes manually with `subscribe` and then trigger an action separately that clears out the route information wouldn't we still run into the same situation (popping information while the animation is being performed)? The only way I'd see this working is if I pop out the route information after the animation finishes but I wouldn't know how to do it.

**Comment by ryankask** [comment]
I don't use a custom connect or anything. `isStale` is a property of the `NavigationScene` state from the `NavigationScenesReducer`. When a route is in the previous routes but not in the current routes, it is considered stale. This happens when you pop a scene. 

For some components I use this value to avoid rendering as a result of state changes that happen while animating the "pop" (basically, to avoid what you mentioned above even though I don't store scene specific state in the routes).

At the moment I only use this when rendering modals and I usual alias the prop as `isHiding` to avoid it knowing too much about the internals of the navigation system.

I don't think it's possible to access this value when it changes if you're using `NavigationCard` until v0.33 (after https://github.com/facebook/react-native/commit/6c4d3c39c670e087930fcdae566e82db4b081113).

**Comment by MinusFour** [comment]
Well, I do see a `isStale` property being injected on the `renderScene` method or do you mean it might not be reflecting the correct value? I'll give it a shot (I'm using 0.31). If the component being wrapped by `connect` has its own `shouldComponentUpdate` mechanism it can override `connect` state updates right?

**Comment by ryankask** [comment]
Prior to the commit referenced above, `NavigationCard` wrapped its `renderScene` in a `SceneView` component that implemented `shouldComponentUpdate`: https://github.com/facebook/react-native/blob/0.32-stable/Libraries/CustomComponents/NavigationExperimental/NavigationCard.js#L76

If the route state didn't change then the component wouldn't see a `false` `isStale` value. Since you're updating the route state it may not be an issue for you.

**Comment by MinusFour** [comment]
Here's a test that reproduces my problem:

https://github.com/MinusFour/routeTest

I would have set it up on rnplay but I think it doesn't manage extra dependencies and they don't seem to have a RN version that it's up to date with current NavigationExperimental changes.

It's a very simple app, all it does is show colors (it only works with android). Each color is actually a button that pushes a new scene in the navigation state. When each scene gets mounted, the state gets populated with the colors to display.

The repo has 2 extra branches. The `flashes` branch actually have both problems. If you run that one, you'll see the race condition (which can be disabled in `store.js`, just change `enableRaceCondition` to false) and how the route colors disappear when popping out the scene. The `normal` branch works as it should (although I disabled the race condition manually).

Some screencasts:

The one with flashes when the scene pops out and has the race condition:

![Flashes](https://i.imgur.com/abLacNw.gif)

The other one that is ok (race condition disabled)

![Normal](https://i.imgur.com/uwEFziT.gif)

> Prior to the commit referenced above, NavigationCard wrapped its renderScene in a SceneView component that implemented shouldComponentUpdate: https://github.com/facebook/react-native/blob/0.32-stable/Libraries/CustomComponents/NavigationExperimental/NavigationCard.js#L76

> If the route state didn't change then the component wouldn't see a false isStale value. Since you're updating the route state it may not be an issue for you.

I think I understand your point. I can't update the route state because then I'd have the race condition. So I pretty much got to wait until `renderScene` behaviour changes in 0.33?

**Comment by chirag04** [comment]
cc @skevy this is a problem in exnavigation also.

**Comment by mario-jerkovic** [comment]
Also if someone uses Relay instead, and pushes new scene that is an Relay container, he will get janky slide animation, as relay renders itself two times, before he gets the data from GraphQL server and after. The only work around is something similar @MinusFour provided, rendering "empty" scene and catching on transition-end event that will cause rendering Relay container, this way I ensure smooth animations.

**Comment by chirag04** [comment]
@mario-jerkovic or you can just injectTaskSchedular `environment.injectTaskScheduler(InteractionManager.runAfterInteractions);`.

**Comment by mario-jerkovic** [comment]
@chirag04 thanks :) , this is more cleaner solution

**Comment by mmazzarolo** [comment]
Hey guys, hope I'm not off-topic:
Since `react-native@0.33.0` whenever I push/reset a route `renderScene` is called twice... any suggestion on how to avoid this behavior? Is this related to this issues?  
It as working correctly before the update.
@ericvicenti 

Snippet for reference, nothing fancy though
```javascript
// CardStack
<CardStack
  navigationState={navigationState}
  onNavigate={dispatch}
  renderOverlay={this._renderToolbar}
  renderScene={this._renderScene}
  style={styles.container}
/>

// RenderScene
_renderScene = (props) => {
  const { currentRoute } = this.props
  switch (currentRoute.key) {
    case 'splashScreen': return <SplashScreen />
    case 'authScreen': return <AuthScreen />
    case 'mainScreen': return <MainScreen />
    default: return null
  }
}

// Reducer
export const initialState = {
  key: 'root',
  index: 0,
  routes: [routes.splashScreen]
}

export default (state = initialState, action) => {
  switch (action.type) {
    case actionTypes.PUSH: {
      const { route } = action
      if (state.routes[state.index].key === (route && route.key)) return state
      return navigationStateUtils.push(state, route)
    }
    case actionTypes.POP: {
      if (state.index === 0 || state.routes.length === 1) return state
      return navigationStateUtils.pop(state)
    }
    case actionTypes.RESET: {
      const { route } = action
      return { ...state, index: 0, routes: [route] }
    }
    default:
      return state
  }
}
```

**Comment by mmazzarolo** [comment]
Documented issue and temporary solution: #7720... but following Navigation Experimental development is really hard 😢

**Comment by MinusFour** [comment]
@ryankask your suggestion seems to be working pretty well on RN 0.33. My global state now has an array with the respective route information which can be accessed by the same index.

```javascript
let initialState = {
   index : 0,
   routes: [{ key : '0', sceneName : 'index'}],
   routeInfo : [{}]
}
```

Though I can't just use StateUtils, I need some wrappers. For example, push and pop:

```javascript
let pushRoute = (state, route) => {
	let nextState = StateUtils.push(state, route);
	nextState.routeInfo = [...nextState.routeInfo, {}];
	return nextState;
};

let popRoute = state => {
	let nextState = StateUtils.pop(state);
	nextState.routeInfo = nextState.routeInfo.slice(0, -1);
	return nextState;
};
```

I just need to pass around `scene.isStale` to my scene component through the connect component and make it so it doesn't update when it's stale, just like you said:

```javascript
	renderScene({ scene }){
		let route = scene.route;
		switch(route.sceneName){
			case 'index':
				return <IndexScene />;
			case 'colors':
				return <ColorsSmart isStale={scene.isStale}/>;
			default:
				return null;
		};
	}
```

```javascript
	shouldComponentUpdate(nextProps){
		return !nextProps.isStale;
	}
```

There are some inconveniences around my connect component though. Ideally, the `connect` component shouldn't try to retrieve route information from the state nor should it try to render said route information changes (because it just not there anymore). At the moment I have to do something like:

```javascript
function mapStateToProps(state, ownProps){
    let currentRouteInfo = state.routeInfo[state.index],
         colors = currentRouteInfo && currentRouteInfo.colors;

    return { colors, isStale : ownProps.isStale };
}
```

Some extra checks are required, etc.

**Comment by lacker** [comment]
It seems like workarounds are available and the conversation has converged here, so I'm going to close this issue. Thanks everyone for helping out!
