### ISSUE TITLE
Android Image asset error

### ISSUE THREAD

**Issue by zhonshu** [facebook/react-native#9804]
ReactImageView.java setSource function 

source:  file:///android_asset/drawable-xxhdpi/app_img_bank_card_add.png

mControllerListener =>onFailure
java.io.FileNotFoundException: /android_asset/drawable-xxhdpi/app_img_bank_card_add.png: open failed: ENOENT (No such file or directory)

Indeed from the file:///android_asset/drawable-xxhdpi/app_img_bank_card_add.png

![image](https://cloud.githubusercontent.com/assets/6829979/18339323/7cb0ac60-75d1-11e6-82f3-d4c3edd710de.png)

**Comment by nihgwu** [comment]
https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources
you just need to provide the image's name, RN will resolve the path for you, `<Image source={{uri: 'app_img_bank_card_add'}} />`

**Comment by tgoldenberg** [comment]
I am having a similar issue. When I invoke `./gradlew assembleRelease`, I get the following messages, implying a wrong type for an image file that doesn't exist.

```java
/Users/thomasgoldenberg/Desktop/SpeakitTeacher/android/app/build/generated/source/r/release/com/speakitteacher/R.java:1780: error: <identifier> expected
        public static final int 3rdparty_telephoneinput_images_ar=0x7f020000;
                               ^
/Users/thomasgoldenberg/Desktop/SpeakitTeacher/android/app/build/generated/source/r/release/com/speakitteacher/R.java:1780: error: <identifier> expected
        public static final int 3rdparty_telephoneinput_images_ar=0x7f020000;
```

When I go to the file /android/app/build/generated/source/r/release/com/speakitteacher/R.java, I see that the path to these images is stored as an `int` for some unknown reason

```
public static final class drawable {
        public static final int 3rdparty_telephoneinput_images_ar=0x7f020000;
        public static final int 3rdparty_telephoneinput_images_cl=0x7f020001;
        public static final int 3rdparty_telephoneinput_images_pe=0x7f020002;
        public static final int 3rdparty_telephoneinput_images_us=0x7f020003;
```

Would really appreciate any help in how to get past this.

**Comment by tgoldenberg** [comment]
For me what worked was doing a file search for images similar to the ones that were throwing the error in the Finder and then deleting them to prevent them entering the Java code. No idea how they got there though...

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-image-asset-error
