### ISSUE TITLE
[IOS] How load bundle from laptop with wifi?

### ISSUE THREAD

**Issue by antoxi4** [facebook/react-native#9805]
Documentation on web site is not valid. Because line jsCodeLocation = [[NSBundle mainBundle] is not commented, and i don't understand where i need set my ip address?

**Comment by christopherdro** [comment]
As of RN 0.29.0 this process is automated. Just make sure you are connected to the same wifi network with your phone and laptop.

Also, double check that the documentation version matches the version of RN you are running.
