### ISSUE TITLE
TouchableHighlight onPress issue on iPad physical device

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#9809]
### Issue Description

I made a ListViewGridLayout starting from this example:
[react-native/Examples/UIExplorer/js/ListViewGridLayoutExample.js](https://github.com/facebook/react-native/blob/2f73ca8f7675977f839ad5bfcb5045ff33621803/Examples/UIExplorer/js/ListViewGridLayoutExample.js)
I made it with class style and not React.createClass (Itested both version anyway)
Like the example my __renderRow_ function returns a TouchableHighlight, when _onPress_ is fired from the TouchableHighlight i would like to use something like

``` js
this._pressRow(rowID) { /*do something with rowID*/ }
```

**It works perfectly on the iOS simulator but not on my iPad:
 when the _pressRow function is fired the argument passed is undefined or empty**
### Steps to Reproduce / Code Snippets

minimal example

``` js
class ListViewGridLayout extends Component {
_pressRow(rowID) {
console.log(`selected row id: "${rowID}");
}

_renderRow(item, sectionID, rowID) {
    return (
      <TouchableHighlight onPress={() => this._pressRow(rowID)}>
          <Text>{item.name}</Text>
      </TouchableHighlight>
    );
  }

render() {
    return(
      <ListView
        enableEmptySections={true}
        dataSource={this._createDataSource(this.props.items)}
        renderRow={this._renderRow}
      />
    );
  }
}
```
#### Expected Results

_expected_ output example

``` bash
selected item with id: "0"
```

_real_ output

``` bash
selected item with id: "undefined"
#or
selected item with id: ""
```
### Additional Information
- React Native version: 0.32.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by sun2rise** [comment]
Anyone found a solution to this? Is it impossible to have a grid with an onPress event? :(

**Comment by book87118** [comment]
HI, you can just instead  `renderRow={this._renderRow}` to 
`renderRow = {this._renderRow.bind(this)}`
I think it would be ok

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.
