### ISSUE TITLE
TextInput in a ListView not working at the bottom of the screen

### ISSUE THREAD

**Issue by reyesr** [facebook/react-native#9822]
### Issue Description

TextInputs at the bottom of the screen in a ListView automatically and immediately dismiss the keyboard on focus, making it impossible to write anything in it. However it does not happen after the application initial loading, but after the user puts the application in the background and then active again.

I reproduced the problem on Android 4.4 and Android 6, on both emulators and devices, with react-native 0.33.0-rc1, 0.32.1, and 0.30.0, all have the issue.
### Steps to Reproduce / Code Snippets

Please see the captures below for the reproduction.

First: Start the application. Everything works fine (see left screen). Then, put the application in the background, by any means, and then back to it (as shown in right screen). 
![step1](https://cloud.githubusercontent.com/assets/2188620/18382343/e68f5582-7680-11e6-97c1-dfa8789ddcfd.gif)![step2](https://cloud.githubusercontent.com/assets/2188620/18381813/568195a6-767e-11e6-87f2-aefc2b4f3051.gif)

Now any time you tap on a TextInput located at the bottom of the screen, the keyboard shows then hides immediatly, and it's not possible anymore to type text in it.

![step3](https://cloud.githubusercontent.com/assets/2188620/18381821/5ea49ea4-767e-11e6-9da6-b0f935b45384.gif)

Here is below the code that reproduces the issue:

`index.android.js`

```
import React, { Component } from 'react';
import {AppRegistry,Text,View, ListView, TextInput} from 'react-native';

class TestTextInput extends Component {

  constructor(props) {
    super(props);
    let datasrc = new ListView.DataSource({rowHasChanged: (r1, r2) => (r1 !== r2)});
    let items = [];
    for (let i=0; i<30; i++) {
      items.push({count:i});
    }
    this.state = {dataSource: datasrc.cloneWithRows(items)};
  }

  render() {
    return (
      <View style={{flex:1}}>
        <ListView dataSource={this.state.dataSource}
                  style={{flex:1}}
                  renderRow={(row)=>(
                      <View style={{flexDirection: "row", borderBottomWidth:1, borderBottomColor:"#333", padding: 24}}>
                        <Text style={{}}>{row.count}</Text>
                        <TextInput style={{flex:1, backgroundColor: "#bbb"}}/>
                      </View>
                  )}
        />
      </View>
    );
  }
}

AppRegistry.registerComponent('TestTextInput', () => TestTextInput);
```
### Additional Information
- React Native version: 0.33.0-rc1, 0.32.1, and 0.30.0, (at least)
- Android, tested on 4.4 (emulator) and 6.0 (emulator and device)

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/textinput-in-a-listview-not-working-at-the-bottom-of-the-screen

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by adamski** [comment]
I am having this issue. Any solutions?

**Comment by susan-github** [comment]
Any update ? I have the same issue on RN 0.38.0

**Comment by ChanNagihong** [comment]
still having this problem at RN 0.42, Could anyone help? please

**Comment by tianxind** [comment]
Yes I am having this issue as well.

**Comment by magrinj** [comment]
Same for me, any solution ? :/

**Comment by wv1124** [comment]
android:windowSoftInputMode="adjustPan"
