### ISSUE TITLE
[Packager] Start worker farm in a daemon?

### ISSUE THREAD

**Issue by aleclarson** [facebook/react-native#9829]
It would be nice to not reload `babel` & friends whenever changing packager code (or if I have to reset the cache). I imagine such a thing could be used by CLI tools too (to reduce up startup time).

Or does this already exist?

**Comment by aleclarson** [comment]
At least for NPM 2 this is relevant. http://goer.org/Journal/2015/11/npm-3s-flatter-module-tree-makes-babel-much-much-faster.html

/cc @davidaurelio @ide

**Comment by davidaurelio** [comment]
We’ve experimented with that in the past, without being too successful. I’m not gonna say no if somebody sends a solid PR, though.
