### ISSUE TITLE
[Image] pointerEvents prop for Image component?

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#9834]
There are a variety of use cases where being able to specify `pointerEvents` on an image would solve zIndex / overlap / touch event complexities. Please see https://github.com/lelandrichardson/react-native-maps/issues/562#issuecomment-246076794 as an example.

It appears that wrapping the Image component in a 

``` jsx
<View
  pointerEvents="none"
/>
```

doesn't seem to do the trick either.

**Comment by hey99xx** [comment]
Why wouldn't having  `<View pointerEvents="none"><Image/></View>` not solve the issue? That should make the entire view untouchable. Even without it, a view itself does not have a touch interaction of its own, so a view like `<View><Image/></View>` should not need any pointer events as far as I understand. Can you share the code example that doesn't work?

zIndex docs are here https://facebook.github.io/react-native/docs/layout-props.html#zindex . I'm not sure how pointerEvents relate to zIndex though.
