### ISSUE TITLE
0.33.0 Duplicate javax.inject in Android with DI framework

### ISSUE THREAD

**Issue by sampengilly** [facebook/react-native#9846]
### Issue Description

When upgrading an existing Android application from React Native 0.29.0 to 0.33.0 I encountered an issue with a Duplicate Zip Entry in proguard. Compiling without proguard points to a "Multiple dex files define javax/inject/Provider;" error.

0.33.0 Adds the new lazy loading of modules and appears to introduce a dependency on `javax.inject` in order to use the `javax.inject.Provider` interface. As my app has a dependency on a DI framework (Roboguice) that also includes `javax.inject` as a transitive dependency I have encountered a clash.

The steps for excluding a transitive dependency from the DI framework in gradle don't work as the Roboguice "masks" the `javax.inject` dependency. As `javax.inject` doesn't show up in the gradle dependency tree after upgrading to React Native 0.33.0 I would assume the same can be said about React Native. I've also tried to exclude the dependency from React Native regardless to see if the issue is resolved that way but the error remains.

``` groovy
compile('com.facebook.react:react-native:0.33.0') {
    exclude module: 'javax.inject'
}
```
### Steps to Reproduce / Code Snippets

Add `org.facebook.react:react-native:0.33.0` and `org.roboguice:roboguice:3.0.1` as compile dependencies in gradle and attempt to compile the app.
#### Expected Results

`javax.inject` should only be depended on once. Either by allowing it to be excluded as a transitive dependency or not depending on it in React Native and instead using a local `Provider` interface. I'll look at doing a PR for the latter option in the morning if that's an acceptable solution.
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by charpeni** [comment]
@facebook-github-bot label Icebox

**Comment by charpeni** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with ProductPains! Check out its new home: https://productpains.com/post/react-native/0330-duplicate-javaxinject-in-android-with-di-framework

ProductPains helps the community prioritize the most important issues thanks to its voting feature.
It is easy to use - just login with GitHub.

Also, if this issue is a bug, please consider sending a PR with a fix.
We're a small team and rely on the community for bug fixes of issues that don't affect fb apps.

**Comment by charpeni** [comment]
@facebook-github-bot close

**Comment by fkoester** [comment]
Having the same problem with `react-native-0.40`. @sampengilly Did you ever manage to solve this issue?

**Comment by dmendis** [comment]
@fkoester I think @sampengilly ended up recompiling roboguice to resolve the issue 😞. I'll let him elaborate.

**Comment by fkoester** [comment]
Thanks for your quick answer! I just noticed roboguice has "retired" anyhow: https://github.com/roboguice/roboguice

Then I noticed that the library I wanted to use (which depended on roboguice) does not really need it, so I patched that one to work without it and now it finally builds 😄
