### ISSUE TITLE
iOS Version Compatibility?

### ISSUE THREAD

**Issue by StevenLangbroek** [facebook/react-native#985]
I've been going through the documentation, but couldn't find anything: which versions of iOS does React Native support? Also, could you share some current thoughts about which versions of Android you would like to support?

**Comment by nicklockwood** [comment]
We support iOS 7 and above.

**Comment by nicklockwood** [comment]
The Android version currently works on Jelly Bean (API level 16) and above. The team are hoping to be able to support Ice Cream Sandwich (API level 15) and above, but can't commit to that at this time.

**Comment by vjeux** [comment]
@nicklockwood thanks for the info, would be nice to put it somewhere in the docs :)

**Comment by brentvatne** [comment]
@vjeux - added this to the getting started page:

![](http://url.brentvatne.ca/1jrZP.png)

**Comment by lrqstudy** [comment]
wonderful~

**Comment by dustin-H** [comment]
Due to the react-native Readme.md this is not correct anymore:

> Supported operating systems are >= Android 4.1 (API 16) and >= iOS 8.0.

https://github.com/facebook/react-native
