### ISSUE TITLE
Native Animation malfunction when drive several views simultaneously

### ISSUE THREAD

**Issue by nihgwu** [facebook/react-native#9858]
I'm writing [a sudoku game in React Native](https://github.com/nihgwu/react-native-sudoku), and I can't wait to use the **Native Animation** feature to drive native animations, but there is something wrong when I turn on `useNativeDriver`, here is the DEMO:

![na](https://cloud.githubusercontent.com/assets/2595058/18443336/0a4fdbc2-7947-11e6-8471-915e1bad30ab.gif)

When I try to animate a dozen of cells, some of them will stay static forever even they should animate in later occasion( in this case, the cell [6] in the left top comer should animate but stay still). If I turn off `useNativeDiver`, every cell animates as expected, related code: https://github.com/nihgwu/react-native-sudoku/blob/master/app/components/Cell.js#L69-L85

I've test it on iOS will RN0.33RC0 and RN0.34RC0 and still the same. 

It seems that Native Animation works great if I animate one view in each action, but will malfunction if I animate several views simultaneously.

**Comment by janicduplessis** [comment]
Do you know if the same bug happens on Android? Mostly looking to know if the bug happens in the native iOS implementation or somewhere else.

**Comment by nihgwu** [comment]
only on iOS

**Comment by nihgwu** [comment]
UPDATE: I've tested with RN0.38RC0, seems the freeze issue has gone, but there is still another issue as the following, the view froze during animation, I've check the commits and seems only #10663 hasn't been shipped, does it's relevant with that? @janicduplessis 

![image](https://cloud.githubusercontent.com/assets/2595058/20166223/4eb96820-a74e-11e6-8d09-127b3a9a921e.png)

**Comment by janicduplessis** [comment]
Yes #10663 did fix a lot of issues with native animations on iOS for me.

**Comment by nihgwu** [comment]
I've tested with #10663 and it works great, close this then
