### ISSUE TITLE
[WebView] network Activity Indicator for WebView

### ISSUE THREAD

**Issue by gnatok** [facebook/react-native#986]
Hello there.
Do we have possibility to use network Activity Indicator for WebViews without modifying files in Xcode?

**Comment by nicklockwood** [comment]
Not yet. I've created a task to implement this.

**Comment by nicklockwood** [comment]
To be clear, do you want to display a loading indicator inside the webview itself, or are you talking about the network activity indicator that appears in the status bar on the top of the screen?

**Comment by gnatok** [comment]
@nicklockwood Network activity indicator that appears in the status bar on the top of the screen. Thanks
