### ISSUE TITLE
Android TextInput doesn't display its UI

### ISSUE THREAD

**Issue by jbrodriguez** [facebook/react-native#9862]
### Issue Description

The TextInput component for Android doesn't display its UI in 0.33

This is how it looks

![image](https://cloud.githubusercontent.com/assets/1305422/18447232/52301918-78eb-11e6-84dc-23cfa6232796.png)

I've traced the issue back to this commit https://github.com/facebook/react-native/commit/959c8b170e53e8db23931ad175d81d071e167695#diff-b48972356bc8dca4a00747d002fc3dd5

Not sure if the spread operator is working as expected.

### Steps to Reproduce / Code Snippets

If you revert the commit, it works fine.

Just use TextInput on Android. 

I tried this with react-native-form-generator. 

It works fine on ios, it's just android having the issue.

#### Expected Results

This is how it should look (and how it looks with the commit reverted)

![image](https://cloud.githubusercontent.com/assets/1305422/18447173/1b9f4acc-78eb-11e6-947d-0ce6148e385c.png)

### Additional Information

* React Native version: 0.33
* Platform(s) (iOS, Android, or both?): android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by jbrodriguez** [comment]
Closing since this is an issue with react-native-form-generator, not RN's TextInput

**Comment by omerdn1** [comment]
This is actually an issue with RN, I'm having the exact same issue. I can type into TextInput but the UI won't show up.
