### ISSUE TITLE
React Native v0.32 has a breaking change to Android not mentioned in the release notes

### ISSUE THREAD

**Issue by comountainclimber** [facebook/react-native#9863]
It is not clear to me how to submit a PR to update previous version release notes but there is a breaking change not listed in version .32 release notes of react-native... This change affects all Android dependencies that leverage React Native's Event.java class...

[ In v 0.31 and below the constructor for this class looked like ](https://github.com/facebook/react-native/blob/0.31-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java)

`  protected Event(int viewTag, long timestampMs) {
    init(viewTag, timestampMs);
  } `

[however now this constructor only takes one input as a parameter](https://github.com/facebook/react-native/blob/0.32-stable/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java) (in versions 0.32+):

`  protected Event(int viewTag) {
    init(viewTag);
  }`

This is a change that is not only not listed as a breaking change, its not even mentioned in the release notes.

**Comment by comountainclimber** [comment]
This breaks all dependencies expecting Event to take two params and it seems like integrating some backwards compatibility would not be too difficult...

**Comment by chirag04** [comment]
cc @grabbou @satya164

**Comment by satya164** [comment]
This is a protected constructor (meaning it can only be used inside the React Native package) and doesn't look like the part of the public API.

**Comment by comountainclimber** [comment]
@satya164 wont any native android component that uses the Event class be broken from this change though?

**Comment by jsdevel** [comment]
Looks like the `Event` class is public, so any sub-class extending it would be affected.

**Comment by satya164** [comment]
I'll add it to the release notes anyways.
