### ISSUE TITLE
[Website] Showcase should not be tied to a specific release

### ISSUE THREAD

**Issue by hramos** [facebook/react-native#9865]
The [Showcase](http://facebook.github.io/react-native/showcase.html) is versioned, meaning that any additions won't be displayed for 2 - 4 weeks until the commit is picked up by a React Native release maintainer.

The Showcase lists apps that are already using React Native today, and has no relation to RN releases. Lets have the Showcase load the latest data from master, just like we already do with the  [React Native blog](http://facebook.github.io/react-native/blog/).

### Context

Artsy was [added 19 days ago](https://github.com/facebook/react-native/pull/9569) and their blog post was published on August 15, 2016, but we cannot yet tweet about it because the 0.33 Showcase doesn't list them yet.

**Comment by hramos** [comment]
@bestander do you know what would be the best way to go about this? Versioning is not handled when the website is generated during development (as far as I can see when running `npm start` on my machine), and it seems like the special case for the blog is handled in `publish-gh-pages.js`.

**Comment by bestander** [comment]
@hramos, yeah blog has a special case in React Native website and it is updated on every master branch push.
See all "blog" notes in https://github.com/facebook/react-native/blob/master/website/publish-gh-pages.js#L114

The blog specific code could be a bit generalized and expanded to showcase as well.
Send a PR and cc me.
Also links in the header need to be going to root `/showcase` as with `/blog`

**Comment by petrgazarov** [comment]
Looks like the above PR went through, any reason this issue remains open?

**Comment by bestander** [comment]
Thanks for reminding
