### ISSUE TITLE
IOS ListView Bug Report

### ISSUE THREAD

**Issue by cuisuichuan** [facebook/react-native#9868]
OS: IOS
RN: 0.29.2
Description: I have a Custom Component, In different places use
roters[0] = Custom Component ListView has data
roters[2] = Custom Component
when I open roters[2], the roters[0] Listview data disappear, but you can touch or slide screen, The data will  come out again.

**Comment by nihgwu** [comment]
It's a known issue a quite a long time #8607

**Comment by cuisuichuan** [comment]
@nihgwu  Thanks
