### ISSUE TITLE
No such file or directory ReactAndroid/TEST_DEFS

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#9871]
```
IOError: [Errno 2] No such file or directory: '/xxx/yyy/zzz/react-native/ReactAndroid/TEST_DEFS'
```
### Steps to Reproduce / Code Snippets

`buck test ReactCommon/cxxreact/tests`
### Additional Information
- React Native version: master
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Mac

**Comment by lacker** [comment]
Bucks tests are generally working now so I think I should close this issue.
