### ISSUE TITLE
AwesomeProject close quickly after run  in the iOS Simulator

### ISSUE THREAD

**Issue by jekey** [facebook/react-native#9874]
Hi:
I just test the AwesomeProject by the [https://facebook.github.io/react-native/releases/next/docs/getting-started.html](url)
run the following command 

react-native init AwesomeProject
cd AwesomeProject
react-native run-ios

I see the AwesomeProject in Simulator ,but AwesomeProject exit quickly ! I click the icon of AwesomeProject,It exit quickly too. I run the project in Xcode , everything is normal . 
Why?

**Comment by LilyJ** [comment]
I'm having the same problem. I just installed everything and generated the project.

When I ran `react-native run-ios` from the CLI, it returned `** BUILD SUCCEEDED **`. The simulator ran just fine but when I click to open the project, it crashed.

When I ran the simulator from Xcode, it got stuck on the white page where it says "Powered by React Native" and I couldn't see the welcome message. Xcode also throws an error in `main`.

**Comment by jekey** [comment]
first run npm start, then ok

**Comment by nelsonr** [comment]
@jekey as you said, running `npm start` first and then `react-native run-ios` solved it.

If this is intentional then perhaps it should be added to the documentation.

**Comment by LilyJ** [comment]
@jekey @nelsonr Thanks! It works after `npm start`.

**Comment by huiyinchu** [comment]
Same issue, but run npm start then react-native run-ios is not working for me. 
I tried to open project in xcode, hang with this "libc++abi.dylib: terminating with uncaught exception of type NSException"

**Comment by peresbruno** [comment]
@huiyinchu, hello... Same error here:

xCode output: libc++abi.dylib: terminating with uncaught exception of type NSException

Have you solved this problem? How? Thanks!

**Comment by 1c7** [comment]
same here on macOS + run-ios

**Comment by joaoh82** [comment]
Thanks! I had the same problem!

**Comment by 1c7** [comment]
Hi everyone
I know why now.
Shadowsocks cause this problem.
my problem is fixed right after Shadowsocks is closed

**Comment by dragonwong** [comment]
@1c7 thx

**Comment by wkarim86** [comment]
I had the same issue in mac. I just unchecked Web Proxy(HTTP) and Secure Web Proxy (HTTPS) under Systems Preferences > Network > Advance > Proxies
That's it and React Native start working

**Comment by peresbruno** [comment]
In my case, to solve the problem:

- Open ios project in xcode
- Run project inside xcode
- See xcode logs

For me the problem are not related to react native directly, but with a plugin.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/awesomeproject-close-quickly-after-run--in-the-ios-simulator-1

**Comment by kichiwa** [comment]
Hi there, 
Yesterday, I still run-ios OK. But today, I have this problem. I think I need to cleanup node, npm, yarn and install again.

**Comment by masudhossain** [comment]
I too am still having a problem with this. I uninstalled NPM, Node, Brew, react-native..and than reinstalled everything. And still getting the same error. 

My other swift apps works fine, but it's only the react-native app that closes right away. I also am making sure `npm start` is running too.

**Comment by johanleroch** [comment]
Yes same as @masudhossain

**Comment by stanleynguyen** [comment]
I am having the same problem as @masudhossain too

**Comment by kwhitley** [comment]
Another vote for this issue... I'll try and resolve myself and share the solution.

**Comment by marendra** [comment]
same here, automatic closing after packager loading dependecy graphics done

**Comment by flyinghawker** [comment]
same here, I thought it might be due to the new version of 0.48, but it still happened when I roll back to 0.47.

**Comment by marendra** [comment]
I rolled back to 0.45.1 boom, running perfectly

**Comment by tforssander** [comment]
Had the same issue on 0.48.0 and got it working again on 0.47.2.

**Comment by quangduz** [comment]
Me 2,

====
Loading dependency graph, done.
Bundling `index.ios.js`  [development, non-minified, hmr disabled]  100.0% (301/301), done.
====

But Awesomeproject always close immediately at welcome screen, tried on xcode still the same.

Bellow solution works for me (not need to rollback anything):

Go to your project, edit package.json.
**Find:**

` "scripts": { `



**Add bellow:**

`"postinstall": "sed -i '' 's/\\[headers\\[@\"Content-Length\"\\] unsignedIntValue\\]/\\[headers\\[@\"Content-Length\"\\] intValue\\]/' ./node_modules/react-native/React/Base/RCTMultipartStreamReader.m"`

**Then**
Open terminal, CD to your project, run : **npm link**


Hope its works for you :)

**Comment by why-absystem** [comment]
worked.. thanks @quangduz. awesome..

**Comment by marendra** [comment]
hmm why now after using @quangduz soution then  run npm link, my react-native said "child process err"?

**Comment by quangduz** [comment]
Hi,
This solution use for 0.48.0, not for 0.45.1
I think you need to update your react native to 0.48.0.

**Comment by marendra** [comment]
it worked, for my solution i just run : chmod -R 777 node_modules  , many thanks @quangduz

**Comment by johanleroch** [comment]
Hi @quangduz, the problem is solved with your solution!
Thank you ;-)

**Comment by D-plus** [comment]
Hi, I have the same issue.
react-native-cli: 2.0.1
react-native: 0.48.0
I tried to use @quangduz solution, but had this WARN after run: npm link : 
npm WARN lifecycle r_n_todo@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) r_n_todo@0.0.1 sed -i '' 's/\[headers\[@"Content-Length"\] unsignedIntValue\]/\[headers\[@"C
ontent-Length"\] intValue\]/' ./node_modules/react-native/React/Base/RCTMultipartStreamReader.m /Users/.../Documents/stud/r_n_todo
up to date in 3.37s.
Thanks.

**Comment by quangduz** [comment]
@D-plus : Whats your OS ? I guess Ubuntu or Windows ?

**Comment by vsakos** [comment]
I got it working with

    react-native init AppName --version 0.47.2

**Comment by D-plus** [comment]
@quangduz: My OS is: macOS Sierra 10.12.6 (16G29)

**Comment by quangduz** [comment]
I think this is error about npm permission when work with wd (working directory). 
Founded some solutions for you in this case:

```
1. Run sudo npm run postinstall manually. OR
2. Run npm install --unsafe-perm OR
3. Run sudo chown -R my_name /usr/local
```

Good luck !

**Comment by D-plus** [comment]
@quangduz Thanks man! The first option works 1. Run sudo npm run postinstall

**Comment by johnpalaganas** [comment]
So there's currently no solution to make it work for 0.48.0?

I can't seem to run
`sudo npm run postinstall`

I get this...
```
npm ERR! missing script: postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2017-09-04T02_15_29_981Z-debug.log
```

**Comment by quangduz** [comment]
Congrats,
RN 0.48.1 fixed this problem. But it dont work with FBSDK 0.6.1 .... Use 0.6.0

**Comment by faisal3413** [comment]
This issue occurs because iOS build folder not updating.
just delete 'build' folder from 'ios' and run react-native run-ios again and it should work.

**Comment by neo125874** [comment]
@faisal3413 thanks a lot, u really saved my day...
