### ISSUE TITLE
[Bug] [Android/iOS] RefreshControl will break ScrollView when you will remove ScrollView component with refreshing property enabled

### ISSUE THREAD

**Issue by papasnippy** [facebook/react-native#9875]
For better understanding add `style={{ backgroundColor: "rgba(255, 0, 0, 0.3)" }}` to NativeRefreshControl.

How to reproduce bug:
1. Add ScrollView and RefreshControl.
2. Enable refreshing on RefreshControl.
3. Instead of disabling refreshing just remove ScrollView from document.

Now ScrollView layout still on document and not deleted. It will overlap all app view and you can do nothing with it.

**Comment by lacker** [comment]
Could you provide a rnplay.org link that reproduces this problem?

**Comment by papasnippy** [comment]
@lacker https://rnplay.org/apps/DLJSew

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/bug-androidios-refreshcontrol-will-break-scrollview-when-you-will-remove-scrollv
