### ISSUE TITLE
Intent to Implement: Replace UIWebView with WKWebView

### ISSUE THREAD

**Issue by jacobp100** [facebook/react-native#9878]
Now that we're iOS 8+ only, it would be good to move from UIWebView to WKWebView. I'd like to take this on, but it would be good to know of any cross-cutting concerns and dependencies at Facebook that might affect this.

Dependents:
#9762

**Comment by nihgwu** [comment]
there is already a community component https://github.com/CRAlpha/react-native-wkwebview . I'm using it with little changes

**Comment by nihgwu** [comment]
and here is the further discussion https://github.com/facebook/react-native/issues/321

**Comment by ide** [comment]
Yeah, I wouldn't let yourself be blocked by Facebook - write whatever component you want and publish it to npm.

**Comment by fungilation** [comment]
+1 for moving from legacy and poorly performing UIWebView. Together with #9762

**Comment by lacker** [comment]
Let's carry on the discussion in the associated pull request https://github.com/facebook/react-native/pull/10456 - if we don't merge that PR, then I don't think this issue will provide additional value.
