### ISSUE TITLE
Feature Request: an option to disable Image cache for development

### ISSUE THREAD

**Issue by gre** [facebook/react-native#9879]
RN is caching image when they are downloaded, and this even if you reload your app. The only way to clear that cache AFAIK is to uninstall and reinstall the app.
for development mode, there should be a way to always disable the image cache.
a bit like in Chrome Network:
<img width="464" alt="screen shot 2016-09-13 at 11 09 57" src="https://cloud.githubusercontent.com/assets/211411/18468102/b834fb86-79a2-11e6-8843-aafffba17b42.png">

maybe it could be an option in the dev menu?

**Comment by satya164** [comment]
I think we should have a way to clear the image cache for specific URL/all URLs. I've struggled a lot with this caching.

**Comment by leeight** [comment]
How about add `disableCache` prop to `<Image disableCache={true} />`, and then call `ImageRequestBuilder.disableDiskCache()`?

**Comment by gre** [comment]
That could work, but I would also imagine there should be a global settings to set the Image cache strategy to use across the whole app.
My initial usecase would be to disable all images in dev mode, but not in prod mode.

**Comment by jbrodriguez** [comment]
This is one of the reasons I'm currently Image wrapped in a https://github.com/wkh237/react-native-fetch-blob/ based component.

It allows me to control caching, let's me get protected images, among other features :)

**Comment by satya164** [comment]
Would be great if RN had more control over the cache though. I think something like `Image.clearAllCache()` would solve @gre 's and my use case at least.

**Comment by leeight** [comment]
@satya164 `ImageLoaderModule` already provided `queryCache` api, so i think it's better add `clearAllCache` api on it rather than on `ImageModule`.

**Comment by lacker** [comment]
It seems like the conversation has converged here. I think it would be ok if someone submitted a PR to implement a `Image.clearCache()`, but it would probably also be ok to just punt on this one. I'm going to close this issue since it's been stale for a while but I welcome a pull request to improve things here!
