### ISSUE TITLE
Number.toLocaleString() polyfill

### ISSUE THREAD

**Issue by pewallin** [facebook/react-native#988]
Seems like .toLocaleString is not supported (ie, formatting thousand separators correctly depending on user locale, for instance showing 1000 as 1,000 in the US and as 1 000 in Sweden.

**Comment by brentvatne** [comment]
@pewallin - neat, can you put together a PR including this polyfill?

**Comment by pewallin** [comment]
https://www.npmjs.com/package/globalize is a more robust solution.

**Comment by brentvatne** [comment]
Looks like you're tracking this in #1042 now :smile:
