### ISSUE TITLE
npm install --save --save-exact react-native failed

### ISSUE THREAD

**Issue by kfir124** [facebook/react-native#9881]
### Issue Description

react-native init fails with this error:
**`npm install --save --save-exact react-native` failed**
there are no other errors in the console window.

> npm info lifecycle isarray@1.0.0~preinstall: isarray@1.0.0
> npm info lifecycle readable-stream@2.1.5~preinstall: readable-stream@2.1.5
> npm info lifecycle strip-bom-stream@1.0.0~preinstall: strip-bom-stream@1.0.0
> npm info lifecycle vinyl@1.2.0~preinstall: vinyl@1.2.0
> npm info lifecycle walker@1.0.7~preinstall: walker@1.0.7
> npm info lifecycle watch@0.10.0~preinstall: watch@0.10.0
> npm info lifecycle whatwg-fetch@1.0.0~preinstall: whatwg-fetch@1.0.0
> npm info lifecycle isomorphic-fetch@2.2.1~preinstall: isomorphic-fetch@2.2.1
> npm info lifecycle which@1.2.11~preinstall: which@1.2.11
> npm info lifecycle window-size@0.1.0~preinstall: window-size@0.1.0
> npm info lifecycle yargs@3.10.0~preinstall: yargs@3.10.0
> npm info lifecycle wordwrap@1.0.0~preinstall: wordwrap@1.0.0
> npm info lifecycle optionator@0.8.1~preinstall: optionator@0.8.1
> npm info lifecycle escodegen@1.8.1~preinstall: escodegen@1.8.1
> npm info lifecycle ast-query@1.2.0~preinstall: ast-query@1.2.0
> npm info lifecycle gruntfile-editor@1.2.0~preinstall: gruntfile-editor@1.2.0
> npm info lifecycle wrap-ansi@2.0.0~preinstall: wrap-ansi@2.0.0
> npm info lifecycle wrap-fn@0.1.5~preinstall: wrap-fn@0.1.5
> npm info lifecycle ware@1.3.0~preinstall: ware@1.3.0
> npm info lifecycle wrappy@1.0.2~preinstall: wrappy@1.0.2
> npm info lifecycle once@1.3.3~preinstall: once@1.3.3
> npm info lifecycle end-of-stream@1.0.0~preinstall: end-of-stream@1.0.0
> npm info lifecycle duplexify@3.4.5~preinstall: duplexify@3.4.5
> npm info lifecycle once@1.3.3~preinstall: once@1.3.3
> npm info lifecycle end-of-stream@1.1.0~preinstall: end-of-stream@1.1.0
> npm info lifecycle once@1.4.0~preinstall: once@1.4.0
> npm info lifecycle inflight@1.0.5~preinstall: inflight@1.0.5
> npm info lifecycle glob@5.0.15~preinstall: glob@5.0.15
> npm info lifecycle commoner@0.10.4~preinstall: commoner@0.10.4
> npm info lifecycle glob@6.0.4~preinstall: glob@6.0.4
> npm info lifecycle globby@4.1.0~preinstall: globby@4.1.0
> npm info lifecycle glob@7.0.6~preinstall: glob@7.0.6
> npm info lifecycle glob@7.0.6~preinstall: glob@7.0.6
> npm info lifecycle rimraf@2.5.4~preinstall: rimraf@2.5.4
> npm info lifecycle run-async@0.1.0~preinstall: run-async@0.1.0
> npm info lifecycle xdg-basedir@2.0.0~preinstall: xdg-basedir@2.0.0
> npm info lifecycle xmlbuilder@4.0.0~preinstall: xmlbuilder@4.0.0
> npm info lifecycle xmldom@0.1.22~preinstall: xmldom@0.1.22
> npm info lifecycle plist@1.2.0~preinstall: plist@1.2.0
> npm info lifecycle simple-plist@0.1.4~preinstall: simple-plist@0.1.4
> npm info lifecycle xtend@4.0.1~preinstall: xtend@4.0.1
> npm info lifecycle through2@0.6.5~preinstall: through2@0.6.5
> npm info lifecycle through2@0.6.5~preinstall: through2@0.6.5
> npm info lifecycle through2@0.6.5~preinstall: through2@0.6.5
> npm info lifecycle through2@0.6.5~preinstall: through2@0.6.5
> npm info lifecycle through2@1.1.1~preinstall: through2@1.1.1
> npm info lifecycle tar-stream@1.5.2~preinstall: tar-stream@1.5.2
> npm info lifecycle decompress-tar@3.1.0~preinstall: decompress-tar@3.1.0
> npm info lifecycle decompress-tarbz2@3.1.0~preinstall: decompress-tarbz2@3.1.0
> npm info lifecycle decompress-targz@3.1.0~preinstall: decompress-targz@3.1.0
> npm info lifecycle through2@2.0.1~preinstall: through2@2.0.1
> npm info lifecycle gulp-sourcemaps@1.6.0~preinstall: gulp-sourcemaps@1.6.0
> npm info lifecycle gulp-util@3.0.7~preinstall: gulp-util@3.0.7
> npm info lifecycle mem-fs@1.1.3~preinstall: mem-fs@1.1.3
> npm info lifecycle mem-fs-editor@2.3.0~preinstall: mem-fs-editor@2.3.0
> npm info lifecycle through2-filter@2.0.0~preinstall: through2-filter@2.0.0
> npm info lifecycle unique-stream@2.2.1~preinstall: unique-stream@2.2.1
> npm info lifecycle glob-stream@5.3.5~preinstall: glob-stream@5.3.5
> npm info lifecycle vinyl-fs@2.4.3~preinstall: vinyl-fs@2.4.3
> npm info lifecycle y18n@3.2.1~preinstall: y18n@3.2.1
> npm info lifecycle yallist@2.0.0~preinstall: yallist@2.0.0
> npm info lifecycle lru-cache@4.0.1~preinstall: lru-cache@4.0.1
> npm info lifecycle cross-spawn@3.0.1~preinstall: cross-spawn@3.0.1
> 
> `npm install --save --save-exact react-native` failed

using `--verbose` will cause the react-native command to fail immediately like that:

```
Installing react-native package from npm...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
### Steps to Reproduce / Code Snippets

`react-native init AwesomeProject`
#### Expected Results

Having a sample project
### Additional Information
- React Native version: Newest (cli is 1.0.0)
- Platform(s) (iOS, Android, or both?): Both
- Operating System (macOS, Linux, or Windows?): Windows7

**Comment by chrisv95** [comment]
I experience the same thing, on Win10.

**Comment by chrisv95** [comment]
Ok, it works now!
What I did....? Nothing different than written above.
Rather than just trying to init the project over and over again.

Why? Because in other npm related software projects, I have the experience that npm fails because of a large dependency set. It just gets clueless and fails. Solution: run again and again and again, till it works.
And that's how it works for me now :-)

**Comment by kfir124** [comment]
Oh wow you are right you just have to keep trying till it works lol

**Comment by jasdeepsingh** [comment]
No shit! you do have to just keep trying until it works!

![giphy](https://cloud.githubusercontent.com/assets/603900/18938641/1ee26bb2-85c8-11e6-874e-11306bd8cff6.gif)

**Comment by madongqiang2201** [comment]
I'm trying over and over,but each time cost me about half hour

**Comment by riterrani** [comment]
I don't know if is a coincidence, but I installed yarn (brew install yarn) and the command worked  correctly.

**Comment by chilismaug** [comment]
By golly, first run of init failed on the "--save-exact" issue, second run worked.

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/npm-install---save---save-exact-react-native-failed
