### ISSUE TITLE
[RCTImageLoader][0.33 & 0.34] Crash

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native#9882]
### Issue Description

When scrolling a listview with items that have image views the app will eventually crash in

[RCTImageLoader.m#L383](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L383) ([Crashlytics Crashreport](http://crashes.to/s/d71a25a1c90))

or in

[RCTImageLoader.m#L502](https://github.com/facebook/react-native/blob/master/Libraries/Image/RCTImageLoader.m#L502) ([Crashlytics Crashreport](http://crashes.to/s/3b623e1df15))

### Steps to Reproduce / Code Snippets

In our app just scroll a longer list that has remote images, eventually it will crash.

#### Expected Results

The app should not crash.

### Additional Information

* React Native version: 0.33.0
* Platform: iOS
* Operating System: macOS

**Comment by pietropizzi** [comment]
This seems to have been introduced in this commit going into RN 0.33: https://github.com/facebook/react-native/commit/14188289fc6254b6704460f7c58e4334f8aa1e25 at least it touches exactly the line that is crashing

**Comment by npomfret** [comment]
I'm getting lots of crashes also, all related I think:

http://crashes.to/s/96034f860eb
http://crashes.to/s/e5f0b80d061
http://crashes.to/s/40184834c7e

**Comment by raspasov** [comment]
Hey guys, we have a similar crash, affecting consistently a number of our users - I think related to the problems people have mentioned so far.

http://crashes.to/s/518580ef4b9 (line 383)
http://crashes.to/s/8ebd91bfbf8 (line 385)

Both crashes on React Native 0.33.

**Comment by littlesome** [comment]
same crash issue
need your help, @javache

**Comment by bsiddiqui** [comment]
We were able to prevent this crash by prefetching images

**Comment by javache** [comment]
We have seen these crashes disappear in v34.

**Comment by raspasov** [comment]
@javache Great! I'll test it out and report back.

**Comment by jerson** [comment]
Same on 34 RC  :(

http://crashes.to/s/7c31b33b411

**Comment by pfeiffer** [comment]
Seeing this as well - also present in 0.32.

**Comment by pietropizzi** [comment]
@javache I can confirm the same severity in 0.34 as was in 0.33. In our app you just have to scroll 2 - 3 pages worth and it crashes. Very reproducible.

**Comment by chandlervdw** [comment]
This has prevented us from upgrading from 0.32. :(

**Comment by chiplay** [comment]
Same issue here, definitely excited to get this fixed and make the upgrade!

**Comment by jerson** [comment]
@chiplay for me Strong reference don't solve this problem :/

http://crashes.to/s/c55a4e38ab1

**Comment by ide** [comment]
Closing this issue since https://github.com/facebook/react-native/issues/9849 is tracking the same bug -- subscribe to that one.
