### ISSUE TITLE
When iOS lock button is pressed and app is in foreground it does not remain active in background (RN 0.31)

### ISSUE THREAD

**Issue by fast4ever** [facebook/react-native#9883]
### Issue Description

Playing with silent push notifications and trying to get them to work when iOS is locked, I discovered that when a RN app is in foreground state and the lock button is pressed the app goes to inactive state and does not end up in background state.
### Steps to Reproduce / Code Snippets

Create a RN app (v0.31)
Log changes to new RN app states
Modify RCTAppState.m startObserving method to log which notification triggered the method.

situation A:
- launch app
- press home button (app goes to background)
- press lock button (phone locks)
- notice that the state switched active->inactive->background

situation B:
- launch app
- press lock button (phone locks)
- notice that state is switched from active->inactive ...but not to background! In native code 'UIApplicationDidEnterBackgroundNotification' does get triggered but this does not put RN in background state.
#### Expected Results

App should be in background state when a user presses the lock button.
### Additional Information
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): iOS

**Comment by lacker** [comment]
It looks like this is fixed now as per https://github.com/facebook/react-native/issues/524

**Comment by fast4ever** [comment]
When I test it with RN 0.41.0-rc.0 I still get the same behaviour: when the lock button is pressed on ios the status goes to inactive, when you push the home button the status goes to inactive then ends up in background. (So when the lock button is pressed the javascript code does not run, but when the app was put to the background first and then the lock button is pressed the javascript code gets triggered correctly)

**Comment by fast4ever** [comment]
When I test it with RN 0.41.0-rc.0 I still get the same behaviour: when the lock button is pressed on ios the status goes to inactive, when you push the home button the status goes to inactive then ends up in background. (So when the lock button is pressed the javascript code does not run, but when the app was put to the background first and then the lock button is pressed the javascript code gets triggered correctly)

**Comment by diegobill** [comment]
I have the same problem. @fast4ever , did you fix the problem?
