### ISSUE TITLE
InteractionManager: undefined is not an object (promise.done.bind)

### ISSUE THREAD

**Issue by jjshammas** [facebook/react-native#9886]
### Issue Description

After upgrading to 0.33, can't seem to use InteractionManager.

```
undefined is not an object (evaluating 'promise.done.bind')

runAfterInteractions
    InteractionManager.js:103
// my code's trace
<unknown>
    NativeMethodsMixin.js:163
__invokeCallback
    MessageQueue.js:268
<unknown>
    MessageQueue.js:130
guard
    MessageQueue.js:42
invokeCallbackAndReturnFlushedQueue
    MessageQueue.js:129
```

### Steps to Reproduce / Code Snippets

```javascript
InteractionManager.runAfterInteractions(() => {
});
```

Looking at InteractionManager's code, I don't seem to understand what it's trying to do. It creates a Promise object, but then tries to hook into its `.done` method…which is not a valid prototype method of a Promise:

https://github.com/facebook/react-native/blob/master/Libraries/Interaction/InteractionManager.js#L102

There seems to be some discussion on this in the commit but it seems to have gotten lost:

https://github.com/facebook/react-native/commit/be09cccb1f2153f84da85214b31cd4cdb4e783ec#diff-67db11a4c1007a2bb6324be53609c5a7R103

#### Expected Results

No error :)

### Additional Information

* React Native version: 0.33.0
* Platform(s) (iOS, Android, or both?): both
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by satya164** [comment]
cc @sahrens

**Comment by sahrens** [comment]
Diff is up internally: D3860551

**Comment by sahrens** [comment]
The issue is that we use a promise implementation internally that does have `done` and we often rely on that without thinking about it...
