### ISSUE TITLE
Image was partially loaded but onLoad was called and onError (on iOS) was not called

### ISSUE THREAD

**Issue by xzdev** [facebook/react-native#9893]
### Issue Description

When using multiple `<Image source='http://someImagePath' />` to load a bunch of network images, some user interaction triggers a navigation update which loads new scene to the top. When coming back to the previous scene, a few of images were partially loaded (as shown in the following picture). 

<img width="155" alt="screen shot 2016-09-14 at 2 13 20 am" src="https://cloud.githubusercontent.com/assets/2880755/18502090/f4756902-7a22-11e6-92b1-f27ee7a75c58.png">

Adding `onLoad` and `onError` (on iOS) to debug, I found onLoad was called and onError was never triggered. That means the broken image was considered as loaded successfully. As the partially loaded images were cached, even triggering another render will still show the broken images.

The issue was recently introduced around 0.28 and it is reproducible on the build 0.32 and 0.33. 

Is there anyone who have the similar issue?
### Additional Information
- React Native version: [0.32 & 0.33]
- Platform(s) (iOS, Android, or both?): [both]
- Operating System (macOS, Linux, or Windows?): [macOS]

**Comment by jsappme** [comment]
+1

**Comment by wcandillon** [comment]
@xzdev Does this happens with remote image? This issue only happens to me for images which I save to the filesystem.

**Comment by xzdev** [comment]
Yes. It happens to me with remote images. It happens when there are multiple remote images loading concurrently and immediately navigate to a new scene. The issue did not occur again on my 6+ after upgrading to the latest IOS.

**Comment by r-bansal** [comment]
Has anyone found a resolution to this - I am noticing this on iOS 9 at the moment.

**Comment by r-bansal** [comment]
@jsappme, @wcandillon - did you guys research this bug further?

**Comment by jsappme** [comment]
@r-bansal I was using a buggy image cache module

**Comment by wcandillon** [comment]
@r-bansal same for me!

**Comment by wcandillon** [comment]
@r-bansal @xzdev You can find more details about why this happens at https://github.com/wkh237/react-native-fetch-blob. This use case is supported in https://github.com/wcandillon/react-native-img-cache

**Comment by shergin** [comment]
@xzdev You are using `react-native-img-cache`, right?
