### ISSUE TITLE
[DevMenu] Debugger unable to launch Dev Tools

### ISSUE THREAD

**Issue by Nosherwan** [facebook/react-native#990]
I am able to get the debugger running by pressing cmd+D. However when I press cmd+R to reload so I can get the changes in my js scripts, it does not get the latest changes, instead I get the following error in the packager:

Launching Dev Tools...
Failed to run launchChromeDevTools.applescript { [Error: Command failed: /Users/nosh/dir/App/node_modules/react-native/packager/launchChromeDevTools.applescript:977:1024: execution error: Google Chrome got an error: Invalid tab index entered. (9)
] killed: false, code: 1, signal: null }

/Users/nosh/dir/App/node_modules/react-native/packager/launchChromeDevTools.applescript:977:1024: execution error: Google Chrome got an error: Invalid tab index entered. (9)

My react-native version is: react-native@0.3.11
watchman vesion is 3.1.0 (installed via $ brew install --HEAD watchman)
OS X 10.10.3
X Code 6.3.1

I have already looked at the watchman issue threads, and reinstalled watchman just to make sure it is not causing any issues. However I am unable to find the log file generated by watchman, which could either be because it has not gotten any issues.

**Comment by sahrens** [comment]
Weird, what version of Chrome are you running?  What is in tab 9?  It sounds like it found the url it was looking for open in tab 9, but chrome didn't accept the command to switch to that tab?

**Comment by Nosherwan** [comment]
Chrome is: Version 42.0.2311.90 (64-bit)
I found a workaround, which was I changed the location of my solution, and it started picking up the js changes. I know there is an issue where if one of the directories has a space in the name it gives an error, but firstly I didn't have any spaces in my directory names in the structure, secondly that one is a different error.
https://github.com/facebook/react-native/issues/297

**Comment by dwilt** [comment]
This is happening to me as well.

**Comment by brentvatne** [comment]
@dwilt - is this still happening? did you fix it?

**Comment by dwilt** [comment]
@brentvatne I can't figure out exactly what I did but it seemed to stop happening. Sorry I couldn't be more help.

**Comment by brentvatne** [comment]
@dwilt - no problem, I'm glad your issue was resolved!

**Comment by frantic** [comment]
Going to close this for now, please reopen if this is still happening

**Comment by brianjd** [comment]
This has just started happening to me now.  Was cause ever determined?

**Comment by brentvatne** [comment]
@brianjd - I don't believe so, I have never experienced it personally. Did @Nosherwan's workaround not help? (https://github.com/facebook/react-native/issues/990#issuecomment-96188544)

**Comment by brianjd** [comment]
I did, didn't fix, so reverted.  Now, I'm not sure what caused it, but now the error has changed.  

```
devtools socket errored WebSocketEvent {type: "error", message: "The operation couldn’t be completed. Connection refused"}
```

Tested it a few different ways for sanity's sake to make sure nothing else on the network was messing with it.  So I reverted to simulator on the local machine using loopback/localhost.  Also tested with the physical phone and machine on a direct /30 link.  I don't know who is refusing what (#$%@& )

**Comment by brianjd** [comment]
Sorry, had to update, forgot to mention the CLI websocket testing.

**Comment by brianjd** [comment]
Ok, and now ` Google Chrome got an error: Invalid tab index entered.` has returned.  I'm too tired for this right now.

**Comment by sudhanshu6247** [comment]
just open google chrome and hit this url http://localhost:8081/debugger-ui
This solved my problem.

**Comment by JanithaR** [comment]
In my case nothing I did worked until I disconnected 'Ciso Anyconnect Secure Mobility Client'.
