### ISSUE TITLE
Can not use Chrome to debug React Native App?

### ISSUE THREAD

**Issue by kirainmoe** [facebook/react-native#9901]
Error was occurred while I was trying to open the ```Debug JS Remotely``` option in my Android emulator.

The follow information was shown in react-native debug app:
> Unable to connect with remote debugger.

I found these error information in my terminal running React packager:
> Launching Dev Tools...
Google Chrome exited with error: { Error: spawn google-chrome ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn google-chrome',
  path: 'google-chrome',
  spawnargs: [ 'http://localhost:8081/debugger-ui' ] }

I have tried to find about the solution of this problem on Google, GitHub issues and StackOverflow, but found nothing. I would be grateful if there is someone who can solve my problem or give me some inspiration.

BTW, I am using React-Naitve 0.32, npm 3.10.7, node v6.5.0. System environment is Arch Linux. Chrome has already installed 'React dev tools' extension.

**Comment by leeight** [comment]
Can you launch Google Chrome using `google-chrome` command in your terminal?

**Comment by kirainmoe** [comment]
@leeight Oh... I built Chrome from AUR, and Chrome's launching command on my system is ```google-chrome-unstable```. After I moved it to ```google-chrome``` it worked normally. I have never thought about this! THX : )

**Comment by fawaz-ahmed** [comment]
`sudo ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome`

or if you are using chromium:
`sudo ln -s /usr/bin/chromium-browser /usr/bin/chromium`
