### ISSUE TITLE
Keyboard pops up after Alert is dismissed

### ISSUE THREAD

**Issue by shahankit** [facebook/react-native#9902]
### Issue Description

I have a `View` with a `TextInput` inside it. Before adding an Alert to View I do dismissKeyboard() called from `react-native/Libraries/Utilities/dismissKeyboard`. After the alert is dismissed the keyboard pops up again and also the TextInput is out of focus because I have already called dismissKeyboard. I have got a bar with Done button above keyboard but because of this even if I try to call dismissKeyboard the keyboard is not dismissed. This is actually an issue with UIAlertView which can be checked [here](http://stackoverflow.com/questions/32744209/ios-9-keyboard-pops-up-after-uialertview-dismissed) and [here](http://stackoverflow.com/questions/30129278/keyboard-pops-up-after-uialertview-is-dismissed-on-ios-8-3-for-ipad)
### Additional Information
- React Native version: 0.30.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): all

**Comment by lacker** [comment]
I think without sample code it is tough to reproduce this issue. I am going to close it but if you have a sample app on rnplay.org that reproduces this problem then it would be great to open a new issue explaining what's going wrong with sample code. Thanks for reporting this!
