### ISSUE TITLE
navigator.geolocation.getCurrentPosition is undefined

### ISSUE THREAD

**Issue by shahen94** [facebook/react-native#9903]
On Both android and iOS i'm getting this error when i want to get my current location.

But when i turning on `Debug JS Remotely` it works fine.

Here is my code:

```
try {
navigator.geolocation.getCurrentPosition(
        ({ coords }) => {
          ...something
        },
        (err) => {
          // 
        },
        { enableHighAccuracy: false, timeout: 20000, maximumAge: 1000 }
      );
} catch (e) {
   console.log(e) // getCurrentPosition is not a function
}
```

**Comment by shahen94** [comment]
I'm also tried to use Geolocation from react-native/Libraries/Geolocation/Geolocation.
It works fine on android but on iOS i'm getting Timeout error.

**Comment by maximeaubaret** [comment]
I'm having the same error using navigator.geolocation.getCurrentPosition on iOS with React 34. 
I have not tried to import "react-native/Libraries/Geolocation/Geolocation" yet.

**Comment by kvs-db** [comment]
I am also facing the same issue - i'm getting this error when i want to get my current location.

But when i turning on Debug JS Remotely it works fine.

Can you tell me how did you fix this?

**Comment by greyvugrin** [comment]
This was caused for me by importing the Navigator component above, more info: https://github.com/facebook/react-native/issues/7495#issuecomment-280821855
