### ISSUE TITLE
Android, RN 0.33 gif Image is not animated

### ISSUE THREAD

**Issue by undef1ned** [facebook/react-native#9908]
I'm using react-native v0.33, however animated gif image is not animated at all, I see the first frame only.

build.gradle has 

> compile 'com.facebook.fresco:animated-gif:0.11.0'

even tried with 0.13.0 - the same

Device: LG G4, Android 5.1.1

**Comment by leeight** [comment]
Can not reproduce it on the master branch.

**Comment by undef1ned** [comment]
Ok, after some investigation it was found that inline images (nested in Text component) are not animated even with the RN 0.35

**Comment by wv1124** [comment]
RN 0.34 can't show gif image

`<Image
				style={{width: WIDTH, height: WIDTH * 7 / 15}}
				source={{uri: 'http://img.1000.com/qm-a-img/prod/1225063/67490b157af9fe9433356d7b05d1b3b3.gif@480w_223h_1wh.gif'}}/>`

**Comment by npomfret** [comment]
I don't believe animated gifs work without adding a dependency. The solution is here https://github.com/facebook/react-native/issues/10537
