### ISSUE TITLE
[MapView] showPointsOfInterest Prop Not Respected in iOS 10

### ISSUE THREAD

**Issue by joncursi** [facebook/react-native#9913]
I've just upgraded Xcode to version 8 and ran my project on an iOS 10 simulator. It appears that specifying `showPointsOfInterest={false}` on the MapView component has lost its effect in the latest version of iOS, as monuments and whatnot are still appearing (they weren't before on previous versions of iOS).

**Comment by lacker** [comment]
We are deprecating MapView and suggest that you use react-native-maps instead. Sorry about that but we hope this diminishes future problems like this because react-native-maps is just better at this point. Good luck!
