### ISSUE TITLE
[Android] Text lineHeight is incorrect for the first line

### ISSUE THREAD

**Issue by alexHlebnikov** [facebook/react-native#9915]
Here is the problem: first line of text have different lineHeight than other lines.
I've tried to add changes from this [commit](https://github.com/facebook/react-native/commit/c79f6177426a417299b5eb13d483613c97b303b3), but it doesn't help.

![screenshot 2016-09-15 11 22 42](https://cloud.githubusercontent.com/assets/1951398/18538333/18608d28-7b37-11e6-9207-5d556a0997b1.png)

You can see - lineHeight of the first line is slightly smaller then in other lines.

Here is my code:

```
<Text style={styles.aboutMessageText}>
    Если вы&nbsp;представляете аптеку, обратитесь к&nbsp;{partnersString}&nbsp;в&nbsp;городе для&nbsp;публикации цен:&nbsp;{'\n'}
    <Text style={styles.aboutMessageText}>{partner.name}</Text>
       <Text>
        <Text style={styles.aboutMessageText}>,{'\n'} почта&nbsp;</Text>
        <Text style={styles.aboutMessageLink} onPress={() => Linking.openURL('mailto:' + partner.email)}>{partner.email}</Text>
    </Text>
    <Text>
        <Text style={styles.aboutMessageText}>,{'\n'} телефон&nbsp;</Text>
        <Text style={styles.aboutMessageLink} onPress={() => this.onPressPhone(partner.phone)}>{partner.phone}</Text>
    </Text>
</Text>
<Text style={styles.aboutMessageText}>
    Если вам не&nbsp;хватает в&nbsp;приложении любимой аптеки, расскажите ей об&nbsp;Аптеках&nbsp;2ГИС.
</Text>

const styles = StyleSheet.create({
    aboutMessageText: {
        color: '#000',
        marginBottom: 24,
        fontSize: 14,
        lineHeight: 20,
        fontFamily: 'FedraSansPro-Normal',
    },
    aboutMessageLink: {
        color: '#A2CD31'
    },
});
```

**Comment by alexHlebnikov** [comment]
While there is still no fix for this, the only workaround I've found is to add `{'\n'}` at the start of your text block and then to add negative marginTop equal to your lineHeight to that text block.

**Comment by jreziga** [comment]
Please try to use .TTF webfont. I had this issue but I was using .OTF

**Comment by alexHlebnikov** [comment]
Hmm. I'm also using .ttf font.

**Comment by jreziga** [comment]
Did you tried with other fonts ?

**Comment by knowbody** [comment]
I have the same issue

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/android-text-lineheight-is-incorrect-for-the-first-line
