### ISSUE TITLE
BackAndroid not working with react-native-router-flux

### ISSUE THREAD

**Issue by RajuPilani** [facebook/react-native#9917]
- react-native-router-flux v3.30.0
- react-native v0.31.0
```
  constructor(props){
  super(props);
  this.handleBackAndroid = this.handleBackAndroid.bind(this);
  }
  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this.handleBackAndroid);
  }

  componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this.handleBackAndroid);
  }
  handleBackAndroid() {
    try {
      Actions.mainPage();
      return true;
    } catch (err) {
      if (onExitApp) {
        return onExitApp();
      }
    return false;
  }}
```
when i press BackAndroidButton then it's call handleBackAndroid function and app exit.

**Comment by ryankask** [comment]
Hi there! This looks like a duplicate https://github.com/aksonov/react-native-router-flux/issues/1163. The issues here are for React Native itself and this looks like a problem with react-native-router-flux.

I've checked my app on Android and the back button is working as it should.

**Comment by ryankask** [comment]
@facebook-github-bot close

**Comment by facebook-github-bot-7** [comment]
@ryankask tells me to close this issue. If you think it should still be opened let us know why.
