### ISSUE TITLE
How to change Icon color in <TabBarIOS> in React Native?

### ISSUE THREAD

**Issue by ReadingSteiner** [facebook/react-native#992]
I tried to change Icon color in <TabBarIOS> using `icon` & `selectedIcon`，but the `icon` is always in `#929292` color, and the `selectedIcon` is always in blue.

Is there anyway to change the icon color?(not in objc way :( plz)

**Comment by ReadingSteiner** [comment]
I found only obj-c solution :( . If I have to write obj-c , why should I  use react-native ?

**Comment by nicklockwood** [comment]
The idea is that all native styling features should be exposed to JS, but it's a work in progress. If you've found a solution, please add a property to expose this to JS and open a pull request, then other people will be able to do it without having to write Objective-C.

**Comment by sahrens** [comment]
@ReadingSteiner: let us know if you need any help with that pull request.

**Comment by ReadingSteiner** [comment]
Sorry :( , I know nothing about Objective-C. I found the obj-c solution [here](https://github.com/facebook/react-native/issues/663), answerd by cmcewen

**Comment by brentvatne** [comment]
Looks like it was solved in #663 and merged in https://github.com/tadeuzagallo/react-native/commit/b0fb6e0566014b4ff9045c32a7eccfca8b6699e7
