### ISSUE TITLE
Ignoring return value of function declared with warn_unused_result attribute

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#9920]
### Issue Description

Just after the Xcode update to version 8.0, i accepted the new license agreement but when i try to do
```bash
react-native run-ios
```
During compilation for iOS, I get this error:
```bash
/Users/sunrising/Documents/Leaff/iFeelReactNative/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:494:3: Ignoring return value of function declared with warn_unused_result attribute
```

### Additional Information

* React Native version: 0.32
* Platform(s) (iOS, Android, or both?): iOS, Xcode Version 8.0
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by sun2rise** [comment]
i opened the project, tried to deploy to simulator from there, i got a warning telling me to perform (automatic) changes to the project, i have done it and this error is now gone

**Comment by holyxiaoxin** [comment]
@sun2rise i got those errors after xcode update as well. There isn't any prompt to perform change. How did you get those prompts? I tried running the project using iphone 6, 6s, 7, 7s and still no prompts.

**Comment by sun2rise** [comment]
@holyxiaoxin i opened the ios project on xcode and run it.. after the error shows, i have seen a warning (on the left side of the window) telling me about the changes, i clicked on it, can you confirm?

**Comment by sun2rise** [comment]
then i have #9921

**Comment by holyxiaoxin** [comment]
@sun2rise I uninstalled xcode 8.0 until this problem is resolved. Using xcode Version 7.3.1 (7D1014) now. can someone else confirm this problem too?

**Comment by berkaey** [comment]
+1

**Comment by edencakir** [comment]
+1

**Comment by berkaey** [comment]
I add ```(void)``` to the beginning of the lines with errors and voila.

**Comment by julien-rodrigues** [comment]
@berkaey used the same solution

**Comment by sun2rise** [comment]
@berkaey , @julien-rodrigues just to ask, i cannot check now but do you think that adding (void) is a clean solution? i mean, that return value is for nothing?

**Comment by julien-rodrigues** [comment]
Didn't say this was a clean solution at all. In fact, every time you have to touch a lib you are using, this is not a clean solution. And as I said I ended up using https://github.com/facebook/react-native/issues/8584#issuecomment-236366222 
This is the best solution to me until the next version of React Native which includes a fix for this problem

**Comment by sun2rise** [comment]
i downgraded xcode but i always missing main.jsbundle... any idea about how to restore it?

**Comment by andresbravog** [comment]
+1

**Comment by sun2rise** [comment]
try
```bash
rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman 
```
as stated here: https://github.com/facebook/react-native/issues/9943#issuecomment-247899222
for me it was the solution!

**Comment by cuonghero** [comment]
Just doubleclick on the RCTWebSocket project in your navigator and remove the flags under build settings > custom compiler flags

**Comment by morenoh149** [comment]
reinstalling watchman did not fix it for me. If I remove the `custom compiler flags` I then get warnings like
* `.../node_modules/react-native/React/Views/RCTScrollView.m:370:7: Use of undeclared identifier '_refreshControl'; did you mean 'refreshControl'?`
* `.../node_modules/react-native/React/Views/RCTScrollView.m:371:6: Unknown receiver '_refreshControl'; did you mean 'UIRefreshControl'?`
etc.
![screen shot 2017-01-15 at 8 12 35 pm](https://cloud.githubusercontent.com/assets/587438/21968104/16852490-db5f-11e6-9792-fde67f32a753.png)

If I attempt to automatically `fix-t` I still remain with an un(automatically)fixable error `.../node_modules/react-native/React/Views/RCTScrollView.m:371:23: No known class method for selector 'removeFromSuperview'`
![screen shot 2017-01-15 at 8 15 17 pm](https://cloud.githubusercontent.com/assets/587438/21968136/7215038e-db5f-11e6-9b3f-8c985520ecd4.png)

Perhaps the ios stuff in RN changed and I need to do something? I'm currently upgrading from 0.17.0.

**Comment by MrHubble** [comment]
@morenoh149 did you find a fix?

**Comment by morenoh149** [comment]
@MrHubble don't think so. I moved on.

**Comment by alinz** [comment]
@MrHubble @morenoh149 You just have to remove the `_` and assign the `refreshControl` to `self.refreshControl`

![screen shot 2017-03-28 at 12 57 00 pm](https://cloud.githubusercontent.com/assets/967050/24417390/34a073c8-13b6-11e7-980d-a0a9b1f67108.png)

that should fix the problem.
