### ISSUE TITLE
WebView subject to SSL policy of of iOS makes loading non https impossible

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#9926]
RN0.33 When I try to load a non ssl domain inside a WebView, I get the same non secure domain exception that I get when I try to fetch a non secure domain that is not in the exceptions list.

Perhaps this is due to the use of the simulator (haven't tried 'live' yet), but in any case, WebView should not be subject to the same policy that prevents non secure fetching from a source not in the exceptions list.

**Comment by ryankask** [comment]
I think all requests are subject to ATS settings, perhaps with the exception from those made with `SFSafariViewController`.

It looks like in iOS 10 there is a new setting `NSAllowsArbitraryLoadsInWebContent` but this along with other settings are controlled in your Info.plist.

**Comment by mschipperheyn** [comment]
Ok, good to know. I'll give that a go, thanks
