### ISSUE TITLE
Integration with Existing App CocoaPods not update

### ISSUE THREAD

**Issue by lisi1987** [facebook/react-native#993]
Integration with Existing App

There is not `RCT_EXPORT_METHOD `macro in `RCTBridgeModule.h` file  and 'RCT_EXPORT' exited.

How can I update?

In my podfile:

```
pod 'React'
pod 'React/RCTText'
```

**Comment by sahrens** [comment]
I think RCT_EXPORT was supposed to be backwards compatible (but deprecated) but might have just broken - @a2 can you take a look and make sure the podfile is working?

**Comment by a2** [comment]
Have you tried the following command?

```bash
$ pod update
```
