### ISSUE TITLE
LayoutAnimation as Component

### ISSUE THREAD

**Issue by gaston23** [facebook/react-native#9932]
Guys, The power of LayoutAnimation is huge, but currently it applies to all layout even if a remote child calls it.

I propose to scope it in a component something like this. 

Wouldn't it be better? How hard would it be to accomplish this?
Thank you

```
<LayoutAnimation easing="easeInOut" enabled={true}>
<Views...>
</LayoutAnimation>
```

**Comment by chirag04** [comment]
There is https://github.com/oblador/react-native-animatable which could give you what you are looking for.

**Comment by gaston23** [comment]
@chirag04 Hi. I don't think ```react-native-animatable``` is near LayoutAnimation. 

LayoutAnimation can even handle deletions.

**Comment by satya164** [comment]
@gaston23 Probably it'll be easier to build something with animated. `LayoutAnimation` works globally, and even though I don't know the internals, I guess it won't be straightforward to scope it to a component.

**Comment by gaston23** [comment]
@satya164 Satya, there are things that you can not accomplish with animated because you don't know previous values or on-the-middle values. That's the magic of LayoutAnimation.

I think react for web already have this 

```
<ReactCSSTransitionGroup
    transitionName={ {
      enter: 'enter',
      enterActive: 'enterActive',
      leave: 'leave',
      leaveActive: 'leaveActive',
      appear: 'appear',
      appearActive: 'appearActive'
    } }>
    {item}
  </ReactCSSTransitionGroup>
```

**Comment by satya164** [comment]
@gaston23 That's true. Probably we'll have CSS transitions support some day.

**Comment by janicduplessis** [comment]
I agree the current API for LayoutAnimation is pretty limiting and flawed. I like the idea of making it a component and it should be possible to implement this easily using context to pass LayoutAnimation params to all child Views and then add a native prop to View that tells if that view can be animated by LayoutAnimation.

**Comment by nihgwu** [comment]
On Android, if I configure `LayoutAnimation`, it will be consumed by `Navigator` too, It's really awful and I have to disable `LayoutAnimation` on Android

**Comment by lacker** [comment]
This seems like a nice-to-have rather than a bug and the discussion seems to have converged so I am going to close the issue. Thanks folks for bringing this issue up!

**Comment by gastonmorixe** [comment]
@janicduplessis  can you give us a basic demo of that approach? Thank you
