### ISSUE TITLE
Impossible to style `SegmentedControlIOS` text and invalid PropTypes for `tintColor` prop

### ISSUE THREAD

**Issue by migueloller** [facebook/react-native#9933]
Currently there is no way to style the text in `SegmentedControlIOS` (e.g., `fontFamily`, `fontSize`, etc.). I tried reimplementing the component from scratch in JS and everything was possible except for the transparent text achieved by the native `UISegmentedControl`.

Could a textStyle prop be added to this component?

Moreover, the `tintColor` prop currently only expects a string but according to the [documentation](https://facebook.github.io/react-native/docs/colors.html) it should also support numbers (e.g., `0xff00ff00`).

**Comment by lacker** [comment]
I think reimplementing the component from scratch would be cool, and I also think it would be best done as a module rather than as part of React Native itself. I am going to suggest that that's the best way forward and close this issue in the meantime. Thanks for bringing this up!
