### ISSUE TITLE
Did not get valid calls back from JS (ReactCommon/cxxreact/MethodCall.cpp)

### ISSUE THREAD

**Issue by leeight** [facebook/react-native#9939]
![image](https://cloud.githubusercontent.com/assets/104052/18576430/015f09a0-7c14-11e6-9fc7-1cca16811770.png)

### Steps to Reproduce / Code Snippets

Open UIExplorer TimePickerAndroid Example

#### Expected Results

Show Time Picker

### Additional Information

* React Native version: master
* Platform(s) (iOS, Android, or both?): Android
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by leeight** [comment]
> Error in example 'simple': "JSON.stringify cannot serialize cyclic structures."

**Comment by cinder92** [comment]
any update on this i have same issue while making a fetch :/

JSON.stringify cannot serialize cyclic structures
