### ISSUE TITLE
react-native init Fail

### ISSUE THREAD

**Issue by Barret-ma** [facebook/react-native#994]
This will walk you through creating a new React Native project in /Users/qitmac000303/AwesomeProject
npm WARN locking Error: EACCES, open '/Users/qitmac000303/.npm/_locks/react-native-f937d6feebda60ab.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/qitmac000303/.npm/_locks/react-native-f937d6feebda60ab.lock failed { [Error: EACCES, open '/Users/qitmac000303/.npm/_locks/react-native-f937d6feebda60ab.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/qitmac000303/.npm/_locks/react-native-f937d6feebda60ab.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "react-native"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/qitmac000303/AwesomeProject/node_modules/react-native, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qitmac000303/AwesomeProject/npm-debug.log
`npm install --save react-native` failed

**Comment by sahrens** [comment]
@frantic Any idea what's going on here?

**Comment by frantic** [comment]
See http://facebook.github.io/react-native/docs/troubleshooting.html#npm-locking-error
Please reopen if the recommendation there doesn't work

**Comment by Barret-ma** [comment]
Thank you very much, I have solved it.@frantic

**Comment by leai-jiang** [comment]
Could you please tell me the solution ? @Barret-ma
