### ISSUE TITLE
react-native init stuck

### ISSUE THREAD

**Issue by sun2rise** [facebook/react-native#9943]
When i make a project with
```bash
react-native init AwesomeProject --verbose
```
i have this message:
```bash
npm WARN react-native@0.33.0 requires a peer of react@~15.3.1 but none was installed.
npm verb exit [ 0, true ]
npm info ok
```
and then the process hangs there forever

in my project folder i have npm_modules folder and the file package.json like this:

```json
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react-native": "0.33.0"
  }
}
```

if i try to
```bash
react-native run-ios
```
the process hangs from the beginning and writes nothing as output, not even an error

i'm on macOS
react-native 0.33

**Comment by pgib** [comment]
I have a similar issue, though mine bails out with:

```
npm WARN react-native@0.33.0 requires a peer of react@~15.3.1 but none was installed.
npm verb exit [ 0, true ]
npm info ok 
Setting up new React Native app in /Users/patrick/pigmik/PikanikMobile
module.js:442
    throw err;
    ^

Error: Cannot find module 'glob-base'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/patrick/pigmik/PikanikMobile/node_modules/parse-glob/index.js:11:16)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/patrick/pigmik/PikanikMobile/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

I'm on El Capitan 10.11.6, and have tried with node 4.2.1, 6.3.1, and 6.6.0 with and without nodenv. Each time yields the same results.

![frustrated](http://i.giphy.com/2rc0zZAlq79eM.gif)

**Comment by sun2rise** [comment]
I'm on El Capitan 10.11.6 too 
Node 6.6.0
This is a nightmare, i don't know what to do on monday... is there a way to reinstall the OS without loosing all the apps and data?

**Comment by feisan** [comment]
I got the similar issue.

react-native-cli: 1.0.0
react-native: 0.33.0
El Capitan 10.11.6

I don't know what's the reason because everything was ok on yesterday.  And I found Imust  run the script with root privilege,  such as

sudo react-native init AwesomeProject
sudo react-native start
sudo react-native run-android

**Comment by pgib** [comment]
Running with `sudo` didn't make a difference for me.

![sobbing](http://i.giphy.com/GN14ap4Mx3Ko0.gif)

**Comment by pgib** [comment]
So, I was able to resolve things by blowing away my `~/.npm` folder. Tested and succeeded on node 4.4.3 and 6.6.0.

**Comment by xiaoneng** [comment]
Same issue.

Reboot after Security Update 2016-001 installed.

Above rm -rf ~/.npm does not work for me.

Can start old project and init new project IF running as root.  Cannot start old project or init new project running as user.

**Comment by sun2rise** [comment]
rm -rf ~/.npm does not work for me neither.. this begins to be frustrating..

**Comment by wemyss** [comment]
+1 same issue here as OP. Using latest version of react-native-cli
node: 6.6.0
macOS: 10.11.6

**Comment by jrzimmerman** [comment]
+1 same issue for the past few days
node: 6.6.0
maxOS: 10.11.6

**Comment by jefe-spain** [comment]
As I wrote in another issue, the same problem, It started to happend after I run the `run android`

I could not create any new project since then. I tried different node version and npm versions but still nothing.

And there is no errour output. 

```react-native@0.33.0` requires a peer of react@~15.3.1 but none was installed.
npm verb exit [ 0, true ]
npm info ok````

**Comment by sun2rise** [comment]
for me it started when i updated xcode to v. 8.. now i downgraded it but still nothing works.
It seems we cannot find a common ground for this thing :(

**Comment by feisan** [comment]
I found the react-native script will run watchman sometimes. When I run 
`watchman version`
It would hang.

After re-install watchman, everything is ok.
`
rm -rf /usr/local/var/run/watchman/
brew uninstall watchman
brew install watchman
`

**Comment by arzyu** [comment]
> After re-install watchman, everything is ok.
>  rm -rf /usr/local/var/run/watchman/ && brew uninstall watchman && brew install watchman

@feisan, this works for me, thanks.

**Comment by jefe-spain** [comment]
Actually yes!! Watchman is the issue. It works like a charm now. @feisan @sun2rise

**Comment by sun2rise** [comment]
@feisan you really changed my monday morning!! thank you, it works!!!

**Comment by sances15** [comment]
@feisan Thanks. Worked like a charm.

**Comment by overbyte** [comment]
+1 @feisan fixed it for me
