### ISSUE TITLE
support ArrayBuffer as fetch body

### ISSUE THREAD

**Issue by inithink** [facebook/react-native#9947]
### Issue Description

fetch simply pass an arraryBuffer to XMLHttpRequest as body,

but XMLHttpRequest pass the arrayBuffer to RCTNetworking module as data

it also simply pass to RCTNetworkingNative.

and native module simply ignore it.

It seems easy to fix.

But I can't build react-native. :(

I want to use it for encrypt packets for production.

Thanks.
### Steps to Reproduce / Code Snippets

`var request = fetch(someUrl {
  method: 'POST',
  body: arrayBuffer,
});`
#### Expected Results

Do not ignore ArrayBuffer body
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): both
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by leeight** [comment]
Try https://github.com/wkh237/react-native-fetch-blob

**Comment by inithink** [comment]
It doesn't take much time.
I don't know about iphone, but in android, only adding about 30 lines needed....(convert arraybuffer to raw array and send it with some field name in js, in java, handle field name with switch case, and make body just using existing helper.)

**Comment by lacker** [comment]
I think trying `react-native-fetch-blob` is a good workaround here, so I'm closing this issue.
