### ISSUE TITLE
UIExplorer examples got rendered twice?

### ISSUE THREAD

**Issue by littlesome** [facebook/react-native#9948]
Hi, I'm playing with the UIExplorer, when I open RCTRootView example, I noticed a flicker, and debugging shows that views are created twice.

Add a log to UIExplorerExampleContainer's renderExample, you can see examples got a re-render after open and before close.

``` 
  renderExample(example, i) {
    // Filter platform-specific examples
    var {title, description, platform} = example;
    console.log('renderExample', i, title);
    ...
```
open example like ActivityIndicator, you got log:
```
UIExplorerExampleContainer.js:38 renderExample 0 Default (small, white)
UIExplorerExampleContainer.js:38 renderExample 1 Gray
UIExplorerExampleContainer.js:38 renderExample 2 Custom colors
UIExplorerExampleContainer.js:38 renderExample 3 Large
UIExplorerExampleContainer.js:38 renderExample 4 Large, custom colors
UIExplorerExampleContainer.js:38 renderExample 5 Start/stop
UIExplorerExampleContainer.js:38 renderExample 6 Custom size
UIExplorerExampleContainer.js:38 renderExample 7 Custom size (size: 75)
UIExplorerExampleContainer.js:38 renderExample 0 Default (small, white)
UIExplorerExampleContainer.js:38 renderExample 1 Gray
UIExplorerExampleContainer.js:38 renderExample 2 Custom colors
UIExplorerExampleContainer.js:38 renderExample 3 Large
UIExplorerExampleContainer.js:38 renderExample 4 Large, custom colors
UIExplorerExampleContainer.js:38 renderExample 5 Start/stop
UIExplorerExampleContainer.js:38 renderExample 6 Custom size
UIExplorerExampleContainer.js:38 renderExample 7 Custom size (size: 75)
```

This may have something to do with NavigationCardStack, and is this a bug or something by design?

* React Native version: v0.34.0-rc.0
* Platform(s) (iOS, Android, or both?): iOS
* Operating System (macOS, Linux, or Windows?): macOS

**Comment by ryankask** [comment]
I don't know much about UIExplorer but if you read through the issue you linked to, you'll see that in RN 0.33 the shouldComponentUpdate methods were removed from `NavigationCardStack` and `NavigationCard`. 

Due to the way `NavigationTransitioner` works, this is expected behaviour.

**Comment by littlesome** [comment]
@ryankask Thanks, I got it. 
I will send a PR to UIExplorerExampleContainer.js to fix this and this issue should be closed.
