### ISSUE TITLE
undefined of object UIManager.RCTView.Constants

### ISSUE THREAD

**Issue by YY030913** [facebook/react-native#9950]
"react": "^15.2.0",
    "react-addons-update": "^15.2.0",
    "react-native": "^0.29.1",
    "react-native-button": "^1.6.0",
    "react-native-vector-icons": "^2.0.3",
    "react-native-voximplant": "^0.1.7"
error:
[erro pic](https://thumbnail0.baidupcs.com/thumbnail/378d63399071e57be56dbf5793f5c406?fid=4062492388-250528-843086815098533&time=1474041600&rt=yt&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-P8W5nbDaN7j5GUVDqGaKcHcETiM%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=6030331614010908693&dp-callid=0&size=c1440_u900&quality=100)

I will appreciate it if you can help me

**Comment by YY030913** [comment]
debug js remote show 'constants' of undefied, but i don't know what is uimanager, is there any api for uimanger

**Comment by leeight** [comment]
https://github.com/facebook/react-native/blob/master/Libraries/Utilities/UIManager.js

**Comment by YY030913** [comment]
@leeight yeah the uimanger file there, but there hasn't any file about rctview of uimanager, it confuse me.my console show the rctview is undefined.

**Comment by leeight** [comment]
It's a dynamic property, maybe you should set some breakpoints on `Libraries/Utilities/MessageQueue.js`
