### ISSUE TITLE
Prevent "Enter" key action

### ISSUE THREAD

**Issue by nickmacia** [facebook/react-native#9953]
There is no way to prevent a TextInput field from updating the text given a key input. For instance, even if I want to reserve "Enter" for a special purpose in a multiline textinput, when I press it the component first forces the on screen text to perform an "Enter" action, namely by adding `\n` to the input value. But I don't want this to happen. I just want to listen for an "Enter" event while suppressing the "Enter" action similar to `onKeyDown.preventDefault()` in javascript for html.

**Comment by Kuzmin** [comment]
Could you not listen for text field changes and when a newline gets added to the end, you trigger your special event, and remove the newline that React Native adds? In my experience this is usually performant enough that you don't see the cursor jumping around etc.

**Comment by nickmacia** [comment]
No, that doesn't work for me. However, the 2`blurOnSubmit2` prop suppresses the added `\n`. I'm closing this issue.
