### ISSUE TITLE
[Android] Can't select text in TextInput

### ISSUE THREAD

**Issue by eremzeit** [facebook/react-native#9958]
I'm using version 0.32.1 and when I long press on text in a `TextInput` it doesn't result in the selection popup that I'd expect (ie. with copy, select all, and paste buttons).  Furthermore, I am unable to select any text at all.  I haven't had a chance to deep dive the react native code yet and see what's going on.  Is anyone else seeing the same issue?

My TextInput is configured like this:

```
          <TextInput
            onBlur={ this._onFinishedEditing.bind(this) }
            placeholder={ this.props.element.placeholderText }
            onEndEditing={ this._onFinishedEditing.bind(this) }
            onChangeText={ (arg) => {
              this.currentText = arg
            }}
            selectTextOnFocus={ true }
            multiline={ true }
            numberOfLines={ 4 }
            underlineColorAndroid={ '#fff' }
          />

```

It seems similar to what was fixed in https://github.com/facebook/react-native/issues/3208.

**Comment by leeight** [comment]
It works fine on the master branch.

![image](https://cloud.githubusercontent.com/assets/104052/18605786/bd485c06-7cce-11e6-93b2-9a11cc5c158d.png)

![image](https://cloud.githubusercontent.com/assets/104052/18605796/f083c7a4-7cce-11e6-8f49-dc4bab8b50c6.png)

**Comment by eremzeit** [comment]
Ah, I only happens when using a `TextInput` inside a `ListView`.

The following code reproduces it:

```
const DebugView = React.createClass({
  componentWillMount: function(){
    this.dataSourceDef = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    })

    this.setState({
      dataSource: this.dataSourceDef.cloneWithRows([ {foo: 1} ])
    })
  },

  render: function(){
    return (
      <ListView
        style={{flex:1}}
        dataSource={this.state.dataSource}
        renderRow={()=> {
          return (
            <View style={{flex: 1}}>
              <TextInput />
            </View>
          )
        }}
      />
    )
  }
})

DebugView.propTypes = {}

export default DebugView
```

**Comment by eremzeit** [comment]
I figured it out.  The culprit is `removeClippedSubviews` on the ListView's underlying ScrollView, which [defaults to true](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/ListView/ListView.js#L463).

If you set `removeClippedSubviews` to false the ListView the text selection box will appear as expected.

It might be difficult to change the default value, but I suggest we at least update the readme to warn people about this potentially unintended behavior.  It currently just describes the option as a performance optimization.

**Comment by eremzeit** [comment]
Any thoughts on this?  I can handle the README change if people don't have the time.  It's a gotcha that should be mentioned, IMHO.

**Comment by xwartz** [comment]
I have the same issue when using `Textinput` inside `ViewPagerAndroid`.

**Comment by debrice** [comment]
I have the same issue, I cannot copy/paste etc... in a TextInput when it is in a KeyboardAvoidingView.
Once back in a View, it's works again :(

**Comment by dioxide** [comment]
same problem

**Comment by iZoid** [comment]
123

**Comment by damvanhuong** [comment]
I have the same issue when using TextInput inside Viewpager on Android 7

**Comment by callmeli** [comment]
same problem,using Textinput inside ScrollableTabView

**Comment by ilya-uryupov** [comment]
Had the same problem, only when using TextInput with multiline={true} inside ViewPagerAndroid, though single-line works fine.
Noticed that when the phone is rotated to landscape and back to portrait, copy-paste starts to work normally. So I made [a hack](https://gist.github.com/ilya-uryupov/7bc9515c6d315d4919ff56ebf4e20411), which renders the TextInput with width set to 99% and after a small timeout changes it to 100%. That makes copy-paste work fine for me.
