### ISSUE TITLE
com.android.builder.testing.api.DeviceException: No connected devices!

### ISSUE THREAD

**Issue by ThanhxD** [facebook/react-native#9959]
### Error

I've just try to use react native to build android applications.
I followed this instruction https://facebook.github.io/react-native/docs/getting-started.html#content, installed all tools, then build AwesomeProject. After running command, **react-native run-android**, I got the error notice **No connected devices** as the title. But I ran the Android Emulator before (I use Genymotion).
In the terminal, the line after **Starting JS server...** says **/bin/sh: 1: adb: not found**.
How can I fix it?
### Additional Information
- React Native version: 0.33.0
- Platform(s) (iOS, Android, or both?): Android
- Operating System (macOS, Linux, or Windows?): Ubuntu 16.04 LTS

**Comment by nihgwu** [comment]
exec `adb devices` to check if the emulator is online

**Comment by ThanhxD** [comment]
@nihgwu it says **adb server version (32) doesn't match this client (36); killing... *daemon started successfully***
But when I start genymontion before command **react-native run-android** then it notices failed to start daemon after line "Starting JS Sever...".
When I power off genymotion then run the command, seem like it starts daemon successfully but still have the error "No devices connected" at the end.

**Comment by nihgwu** [comment]
http://stackoverflow.com/questions/38214012/appium-adb-server-version-31-doesnt-match-this-client-36
http://stackoverflow.com/questions/37674401/adb-android-conflict-with-genymotion

**Comment by ThanhxD** [comment]
Thanks. I forgot to search before ask.

**Comment by gilcierweb** [comment]
In terminal
```

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get update && sudo apt-get install yarn

cd myproject/

sudo rm -rf node_modules/

yarn install
```

https://yarnpkg.com/en/docs/install

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/comandroidbuildertestingapideviceexception-no-connected-devices

**Comment by RohitQSS** [comment]
I am also facing this issue ,Please check your device debugging option is selected or not
