### ISSUE TITLE
TextInput won't clear onKeyPress

### ISSUE THREAD

**Issue by bsiddiqui** [facebook/react-native#9960]
I have a multiline TextInput that I want to clear when the return key is pressed.

I have been able to clear the input with `this.refs.input.clear()` and `this.refs.input.setNativeProps({ text: '' })` but these don't work when using them onKeyPress

This does not work

``` js
onKeyPress={event => if (event.nativeEvent.key === 'Enter') this.refs.input.clear()
```

I would expect that it would clear the input

Using RN 0.31.0

**Comment by antoxi4** [comment]
Where you use this code? Android or IOS? onKeyPress work only on IOS)

**Comment by bsiddiqui** [comment]
@antoxi4 I'm using on iOS

**Comment by lacker** [comment]
I suggest using controlled components so that you can just clear out the data directly, rather than using refs and an uncontrolled form here.

**Comment by Woodswu** [comment]
I also have the same problem

**Comment by Woodswu** [comment]
you can like this 

this is my demo

first set blurOnSubmit={true}

second:
onSubmitEditing={()=>{this.refs.input.clear()}}
