### ISSUE TITLE
TabBarIOS.Item will not ignore tintColor even with renderAsOriginal

### ISSUE THREAD

**Issue by qualifyapp** [facebook/react-native#9965]
### Issue Description

I've been attempting to get the TabBar for our application completed and I've been running into a bit of trouble with the Icons. I've looked all over the place for about two days and even through the UIExplorer demonstrations, all the way down to @urbancvek 's PR notes. 

The Images are all rendered with a tint, and no color can be seen, transparency in the image is also filled by the tint.
### Steps to Reproduce / Code Snippets

You can simply copy the [Example from UI explorer](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/js/TabBarIOSExample.js) to see the problem, however here's a screenshot. (Excuse the oversized icons) 

Please note, Icons are Colored, and the messaging Icon should not be filled out, although it is with the gray unselected tint color, the `selectedIcon` is also filled out with the `tintColor` from the TabBar.

I've tried changing just `renderAsOriginal` to `renderAsOriginal={true}` as shown in the documentation that it is a boolean value, however this didn't have any effect. 

![screen shot 2016-09-17 at 12 35 24 pm](https://cloud.githubusercontent.com/assets/19787444/18609907/4bcc1b94-7cd3-11e6-9900-7bc69806199a.png)
#### Expected Results

The images in the `TabBarItem.IOS` component should be rendered how they are designed when the `renderAsOriginal` prop is set to true, instead of being covered with a tint. Setting `transparent` to the tint color should not hide the Icon either, IMO. 
### Additional Information
- React Native version: 0.33.0 problem persisted in 0.32.0
- Platform(s) (iOS, Android, or both?): iOS
- Operating System (macOS, Linux, or Windows?): macOS

**Comment by qualifyapp** [comment]
I should add that this only appears to happen on iPhone5s and under.

**Comment by lacker** [comment]
Why are the images rendered with a tint? Is that how tab bars work by default on iOS?

**Comment by urbancvek** [comment]
@lacker yes. By default iOS takes an image and renders it as a template (UIImageRenderingModeAlwaysTemplate). I've then added a check here [RCTTabBarItem.m](https://github.com/facebook/react-native/blob/b58c8ad91661ce424b89e2f534cf8eb6d5260d8c/React/Views/RCTTabBarItem.m) at line 90 and 101 for renderAsOriginal prop which then sets the image to display as original (UIImageRenderingModeAlwaysOriginal).

**Comment by XHTeng** [comment]
I found that iPhone 5S and under will always run the self.barItem.image = _icon;  ，not run self.barItem.image = [_icon imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];  ，so I delete the judge ，but I don't know why is it ?

**Comment by adulhani-systango** [comment]
I am also facing same problem on on iPhone5s and under(devices only, works fine on simulator). @XHTeng Have you found any work around for this problem?

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/tabbariositem-will-not-ignore-tintcolor-even-with-renderasoriginal-1
