### ISSUE TITLE
WebView JS Error: undefined is not an object (evaluating '_this.props')

### ISSUE THREAD

**Issue by johnryan** [facebook/react-native#9966]
### Issue Description

I'm using QR code library that internally renders in a WebView (https://github.com/cssivision/react-native-qrcode/issues). When the webview renders it throws the error but does actually render the WebView behind the red box:

<img src="https://cloud.githubusercontent.com/assets/416564/18610083/5c21e8c2-7ce0-11e6-8734-99e5dfabb817.png" width="400">

This issue began in 0.32.0 it seems with this change:

`  _onLoadingStart: function(event: Event) { ... `

To:

`_onLoadingError = (event: Event) => { ... `

### Steps to Reproduce / Code Snippets

Just rendering the QR Code view with this snippet (that is being presented with Navigator)

```
          <View>
                <WebView
                    automaticallyAdjustContentInsets={false}
                    contentInset={{top: 0, right: 0, bottom: 0, left: 0}}
                    source={{html: "TEST HTML"}}
                    opaque={false}
                    underlayColor={'transparent'}
                    javaScriptEnabled={true}
                    scrollEnabled={false}
                />
            </View>
```

#### Expected Results

There should be no error displayed

### Additional Information

* React Native version: 0.34.0-rc0 (but also every version back to 0.32.0)
* Platform(s) (iOS, Android, or both?): Both
* Operating System (macOS, Linux, or Windows?): macOS

Other notes: This seems to be happening in several other places 
- https://github.com/facebook/react-native/issues/9610
- I'm also seeing this error in ViewPagerAndroid.android.js:86  _childrenWithOverridenStyle

**Comment by leeight** [comment]
It works fine on the master

![image](https://cloud.githubusercontent.com/assets/104052/18612488/87fa17a0-7d8d-11e6-8332-830b8fb5fd37.png)

**Comment by johnryan** [comment]
I'll try to make a sample project that specifically reproduces the issue. Thanks for taking a look.

**Comment by johnryan** [comment]
After a lot of digging there was a .babelrc and .eslintrc file that were in the directory (from some template project when i started). It seems that it was disabling es6 features in non-jsx files. After removing that the issue was resolved.

**Comment by proProbe** [comment]
Hello! Im receiving the same error and Im wondering if you could elaborate a bit more about the fix. Our .babelrc is currently
```
{
  "passPerPreset": true,
  "presets": [
    "./scripts/babelRelayPlugin",
    "react-native",
    "stage-3"
],
  "plugins" : [
      "babel-remove-process-env-assignment",
      "transform-inline-environment-variables"
  ]
}
```
is it perhaps the `stage-3` that is too strict?

**Comment by johnryan** [comment]
@proProbe do you have a .eslintrc file? My hunch was that it was:

```
 "ecmaFeatures": {
    "jsx": true
  },

```
that was not allowing the es6 functions in the react-native .js files (NOTE: this could be entirely wrong). I just deleted both the eslintrc and the .babelrc and it worked after that.

**Comment by proProbe** [comment]
@johnryan unfortunately we dont have an .eslintrc. Deleting the .babelrc doesnt seem to work either.

**Comment by johnryan** [comment]
@proProbe do you have any sample code that reproduces the issue?

**Comment by proProbe** [comment]
@johnryan 
```
import React, { Component } from "react";
import {
    View,
    Text,
    WebView,
} from "react-native";



class ExternalUrlViewer extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <View>
                <Text>
                    Should show webviewer
                </Text>
                <WebView
                    source={{uri: 'https://github.com/facebook/react-native'}}
                    style={{marginTop: 20}}
                />
            </View>
        )
    }
}
export default ExternalUrlViewer;
```
does not seem to work for me
sitting on:
"react-native": "^0.33.0",
linux, android

**Comment by proProbe** [comment]
here is a screenshot of the errormsgs

![14446465_10210674391594712_247086339_o](https://cloud.githubusercontent.com/assets/3802899/18741905/d91a4b92-80b1-11e6-9338-51afc2d1f9ef.png)

**Comment by johnryan** [comment]
@proProbe when i run it with:
```
  "react": "15.3.2",
   "react-native": "0.33.0"
```

in a fresh project (i.e. react-native init issue9966) and:

```
class issue9966 extends Component {
  constructor(props) {
       super(props);
   }

   render() {
       return (
           <View style={{"flex": 1}}>
               <Text>
                   Should show webviewer
               </Text>
               <WebView
                   source={{uri: 'https://github.com/facebook/react-native'}}
                   style={{"flex": 1,marginTop: 20}}
               />
           </View>
       )
   }
}

```

It renders as expected. I'd suggest trying to figure out what's different between your project and the fresh one created by react-native-init

**Comment by kamek-pf** [comment]
Any progress here ? I'm seeing the same thing.

**Comment by kamek-pf** [comment]
Found the issue.
See #9151, @orlando's post.
```json
{
  "passPerPreset": true,
  "presets": [
    "react-native"
  ],
  "plugins": [
    "transform-class-properties"
  ]
}
```
You need to explicitely specify `transform-class-properties` even though it's already included in the `react-native` preset. Looks like a Babel bug, we should probably do something about it.

**Comment by chirag04** [comment]
@kamek-pf you should remove "passPerPreset" if you set it only for babel-relay-plugin. Class properties should just work with "react-native" preset.

**Comment by kamek-pf** [comment]
@chirag04 good to know, thanks !
