### ISSUE TITLE
fs operation timeout

### ISSUE THREAD

**Issue by maxifjaved** [facebook/react-native#9967]
I am facing this error when i am trying to build the apk.
Following the step mention on https://facebook.github.io/react-native/docs/signed-apk-android.html

I tested it by running app on physical device(working).

i have the following error: 

`

```
[2:27:37 AM] <END>   Building (deprecated) Asset Map (134ms)
[2:27:38 AM] <END>   Building Haste Map (1229ms)
[2:27:38 AM] <END>   Building Dependency Graph (6630ms)
[2:28:02 AM] <END>   find dependencies (30510ms)
```

```
 fs operation timeout

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

```

`

**Comment by stoffern** [comment]
https://github.com/facebook/react-native/issues/7507 ?

**Comment by lacker** [comment]
Looks like this is a dupe so I am going to close it. Thanks for bringing this up!
