### ISSUE TITLE
Iterable.length has been deprecated

### ISSUE THREAD

**Issue by basequatro** [facebook/react-native#9971]
Because of the current version (3.7.4) of immutable in dependencies, there will be warning in console: "Iterable.length has been deprecated, use iterable.size or iterable.count()".

this warning is removed in immutable@3.8.0

could you please update the immutable version in your dependencies.

**Comment by damusnet** [comment]
Do you still get this warning?

**Comment by christopherdro** [comment]
@facebook-github-bot icebox

**Comment by hramos** [comment]
Hi there! This issue is being closed because it has been inactive for a while.

But don't worry, it will live on with Canny! Check out its new home: https://react-native.canny.io/feature-requests/p/iterablelength-has-been-deprecated
