### ISSUE TITLE
Proxy object only processed when debugging

### ISSUE THREAD

**Issue by mschipperheyn** [facebook/react-native#9974]
I use javascript proxies. When I enable Debug JS Remotely, this works fine. However, when I disable Debug JS Remotely, it seems like my proxies are no longer processed because the javascript Proxy object is no longer present. How do I enable it for production purposes?

**Comment by ide** [comment]
Proxies are only supported in JavaScript environments that natively support them so you can only use them on iOS 10. See http://caniuse.com/#feat=proxy

**Comment by mschipperheyn** [comment]
Ok, I hadn't realized that. Thank you for your quick response. Out of curiosity. Does RN depend on a javascript engine that the native platform supplies or is it just complying its own Javascript engine to whatever the native platform mandates? I would have imagined that RN shipped with an embedded Javascript processing engine to guarantee uniform processing.

**Comment by ide** [comment]
On iOS it uses the system engine. On android it ships with a version of JSC after iOS 8 was released.

**Comment by SukantGujar** [comment]
Just came across this issue at my end as well... Any ideas if/when I would be able to use Native Proxy in Android devices too?
Thanks.

**Comment by alshakero** [comment]
@ide 

>Proxies are only supported in JavaScript environments that natively support them

Does this mean I can use them in Andriod > 5-6.x as per the link?

**Comment by ide** [comment]
@alshakero no because RN Android uses JSC without Proxies. You can use them on iOS 10 only.

**Comment by deecewan** [comment]
@ide sorry to raise an issue from the dead, but is there a reason that android's JSC is still compiled against such an old version? surely this engine ships with the android version of the app, so it could conceivably use an up-to-date version of the engine?

or, alternatively, run against the built-in engine on android?
