### ISSUE TITLE
dead store issue when building with analyzer/clang

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#998]
With Xcode 6.3 (6D570), there is a dead store issue found in Layout.c at lines 645 and 649.  It seems containerMainAxis is set but never read.

This is bad for those of us who try to build clean with the analyzer.

**Comment by tadeuzagallo** [comment]
Hey, I was just working on that: https://github.com/facebook/css-layout/pull/70

Also the analyzer will now run by default on the build, so we try to keep it clean!

**Comment by brentvatne** [comment]
Closing, ping me if this is still an issue for you @jwyld
