### ISSUE TITLE
WebView adds black background and does not refresh

### ISSUE THREAD

**Issue by kestasnarkunas** [facebook/react-native#9986]
WebView component does not refresh on demand and another issue is that it adds black background if changing context inside render. If we have source html set without url, component will display white window once reload is called on it, by doing that I tried to solve black background issue. But both things are not working as they should. If I call reload, it does not trigger re-rendering. (this.refs['htmlWebView'].reload();)

Color scheme: yellow WebView content, green container, white popup component (that is actually set in same level as webView) and unwanted black (what it is - I don't know).

BLACK BACKGROUND ISSUE (main one, just focus on solving this if possible):
1. We have main component that will hold everything inside of it, including WebView component:

```
//all imports...

class MainComponent extends Component {
//all required functions...

 render() {
  //later this will be imported via state into props, for this example we will use local const
  const someText = '<html lang="en"> <head> <title>HELLO</title> <meta charset="utf-8"> <meta name="format-detection" content="telephone=no"> </head> <body> <table> <tbody> <tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr><tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr><tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr><tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr><tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr><tr class="table-row"> <td class="table-data-key"> <div>Column 1</div> </td> <td class="table-data-value"> <div> <div>Column 2</div> </div> <div> <div>extra stuff</div> </div> </td> </tr></tbody> </table> </body> </html>';

const cssInJsSyntax =
      'var tableElement = document.querySelector("table");\
       tableElement.style.tableLayout = "fixed";\
       tableElement.style.width = "100%";\
       tableElement.style.leftPadding = "20px";\
       tableElement.style.borderSpacing = "0";\
       \
       var bodyElement = document.querySelector("body");\
       bodyElement.style.backgroundColor = "yellow";\
       \
       var tbodyElement = document.querySelector("tbody");\
       tbodyElement.style.fontFamily = "font";\
       tbodyElement.style.color = "#054061";\
       tbodyElement.style.fontSize = "' + htmlFontSizeNormal + '";\
       var tdValueNodeList = document.querySelectorAll("td:nth-child(2)");\
       var i;\
       for(i = 0; i <   tdValueNodeList.length; i++)\
        {tdValueNodeList[i].style.textAlign = "right";\
         tdValueNodeList[i].style.borderBottom = "1px solid #9db5c2";\
         tdValueNodeList[i].style.color = "#406980";}\
       \
       var tdKeyNodeList = document.querySelectorAll("td:nth-child(1)");\
       var i;\
       for(i = 0; i <   tdKeyNodeList.length; i++)\
        {tdKeyNodeList[i].style.borderBottom = "1px solid #9db5c2";}\
      var allRows = document.querySelectorAll("td");\
      for (i = 0; i < allRows.length; i++) {\
          allRows[i].style.paddingTop = "16px";\
          allRows[i].style.paddingBottom = "20px";\
          allRows[i].style.paddingLeft = "16px";\
      }\
      ';

    const checkInsets = {
      bottom: this.props.currentState === 'noPopUp' ? 84 : 0
    };

   return(
      <View style={styles.container}>
        <NavigationComponent />
        <WebView
          ref='htmlWebView'
          automaticallyAdjustContentInsets={false}
          source={{ html: someText }}
          decelerationRate='normal'
          scalesPageToFit={Platform.OS === 'ios' ? false : true}
          style={{ backgroundColor: 'green' } }
          injectedJavaScript={cssInJsSyntax}
          javaScriptEnabled={true}
          contentInset={ checkInsets }}/>        
        {this.props.screenState === 'showPopUp' ?
        <SomePopUp onAction={this.props.somePopUpAction}/> : null}
      </View>
    );
 }
}

//styles
const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'green'
  }
});
```
1. Start application, go to component view to see this:
   ![1](https://cloud.githubusercontent.com/assets/21095312/18632209/eec2d854-7e7e-11e6-9f4e-d1dcd3856288.png)
   Everything is fine here
2. Let's add another component to context, then checkInsets is set to 0:
   ![2](https://cloud.githubusercontent.com/assets/21095312/18632304/65bebe5a-7e7f-11e6-83ff-40d953c0d737.png)
   Everything looks good so far!
3. Close component (remove from context) and set checkInsets to 84 (because we will have another component with absolute position that is transparent):
   ![3](https://cloud.githubusercontent.com/assets/21095312/18632329/8ee20d50-7e7f-11e6-9565-b03dfdf74ff0.png)
   And here it is, the black background.
4. Scroll down to get better understanding of what is going on:
   ![4](https://cloud.githubusercontent.com/assets/21095312/18632357/ab22b78a-7e7f-11e6-8dba-8d5819cb8837.png)

What was expected, is that once I change something inside render(...); I want to get the same view again after removing component from same level.

I have noticed, that if you zoom in and out, that background disappears, so I thought what would happen if I did refresh WebView? Well, we will be getting white screen with no content whatsoever. (my guess that WebView requires url to be set and fails to do read on data that it already haves inside of it)
- React Native version: 0.31.0
- Platform(s) (iOS, Android, or both?): both

**Comment by lacker** [comment]
Could you provide a reproduction of this problem on rnplay.org? Just the black-background issue, let's focus on that.

**Comment by hramos** [comment]
Closing this issue because it has been inactive for a while. If you think it should still be opened let us know why.

**Comment by MrPluto** [comment]
@kestasnarkunas any update?

**Comment by kestasnarkunas** [comment]
@MrPluto I should try to recreate it on rnplay once more to see if this issue still there.

**Comment by Cwele** [comment]
Is it possible to have a transparent background color on an WebView? If I try to set background color to transparent it just become white.
