### ISSUE TITLE
[RN 0.31][Android][OSX] Image cache get overloaded and stop loading images

### ISSUE THREAD

**Issue by lcherubini93** [facebook/react-native#9987]
Hello,

I am developing an application with RN 0.31 on OSX for Android and iOS.
I have looked up a lot about this but I couldn't find a solution. There is a point in which the phone stops loading images, exactly when I try to load a list with a lot of images.

I think it is related to an issue with the image cache on Android. On iOS works perfectly.

Please, ask me for any other detail you need to help me, I will bring it as soon as possible.

Thanks,
Lucas

**Comment by sbycrosz** [comment]
It should be related to https://github.com/facebook/react-native/issues/8677
The fixes is on 0.34 stable that'll be released this coming Friday CMIIW
