### ISSUE TITLE
-[RCTBridge setUp] adding notification observer twice

### ISSUE THREAD

**Issue by jwyld** [facebook/react-native#999]
In the -loadBundleAtURL:onComplete: block, -addObserver:selector:name:object: is called twice with the same arguments in the case when there is no error.  Since the arguments are the same, there is no harm, but it's just wasted cycles.

**Comment by tadeuzagallo** [comment]
Thanks, it was already fixed internally, it should be out on the next sync.

**Comment by tadeuzagallo** [comment]
Removed on 5ce9fa4dda79bd925e075afcb552893acdc83628
