### ISSUE TITLE
[Docs][Touchable Highlight] Please list all events that are available to subscribe to

### ISSUE THREAD

**Issue by andresn** [facebook/react-native#9991]
Here's what it looks like you're exposing:
      this.props.onPress || // the only one in the example
      this.props.onPressIn ||
      this.props.onPressOut ||
      this.props.onLongPress

Does it make sense to document here?:
https://facebook.github.io/react-native/docs/touchablehighlight.html

And the same thing for other components as applicable?

**Comment by hey99xx** [comment]
It is already documented. TouchableHighlight says " TouchableWithoutFeedback props... " as the first line of Props documentation to note it accepts all Props that are also applicable to TouchableWithoutFeedback. So when you want to see all props for TouchableHighlight, you also need to look at https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#props

Hope this helps

**Comment by andresn** [comment]
Ah, thank you @hey99xx!
