### ISSUE TITLE
Documentation: Where is the implementation for requireNativeComponent?

### ISSUE THREAD

**Issue by jsdevel** [facebook/react-native#9994]
I'm trying to understand how react-native bridges javascript to native components.  The docs show how to implement a native component from javascript, but they don't show where `require('requireNativeComonent')` comes from or how it works.  I've grepped all through the code and several google searches to no avail.  Thanks!

**Comment by ide** [comment]
```
$ find . -name requireNativeComponent.js
./Libraries/ReactIOS/requireNativeComponent.js
```

**Comment by jsdevel** [comment]
* How is it required by name? I.E. `require('requireNativeComponent')`

**Comment by hey99xx** [comment]
Just FYI, a lot of code is shared between react and react-native repositories. So occasionally you'll have to switch to https://github.com/facebook/react to find the correct code.

Anyways the code is here https://github.com/facebook/react-native/blob/master/Libraries/ReactIOS/requireNativeComponent.js

If you're asking how other files can directly refer to it without any `../ReactIOS` kind of thing, Facebook seems to have a very complex build system and if a class annotates `@providesModule somename` at the top, it becomes its own mini module and others can consume it.

**Comment by jsdevel** [comment]
> if a class annotates @providesModule somename at the top, it becomes its own mini module and others can consume it.

I see!  I suspect the packager is at play here.  Thanks for the reply.

**Comment by hey99xx** [comment]
Hey @jsdevel , since I'm not an official contributor, I cannot close the issue, but if you have no further comments, please feel free to close the issue to keep RN's backlog cleaner.
Thanks,
